### ISSUE TITLE
Swagger UI is changing the protocol in the request from https to http

### ISSUE THREAD

**Issue by bretzmo** [swagger-api/swagger-ui#1006]
The request url that I enter contains https but when I click the Try It Out button, the request url that Swagger UI generates contains http. This is causing no data to be received. I can mimic this behavior in a browser and when using https I receive a valid response, but when I use http in the direct browser request I receive No Data Received. I need to figure out why Swagger UI is changing the protocol.

![screen shot 2015-03-06 at 8 36 14 am](https://cloud.githubusercontent.com/assets/3484310/6529205/ea61c4f0-c3db-11e4-9038-9a7c1095e2fe.png)

**Comment by webron** [comment]
What's the `basePath` in your spec?

**Comment by bretzmo** [comment]
Here is the Swagger config in our code.

![screen shot 2015-03-06 at 8 56 32 am](https://cloud.githubusercontent.com/assets/3484310/6529597/bbeca0d8-c3de-11e4-9884-6bab4af8cd3e.png)

**Comment by webron** [comment]
Okay, so you use Swagger 2.0. Do you have a `schemes` property in your spec? If so, what's in there?

**Comment by bretzmo** [comment]
No I don't have a schemes property.

**Comment by webron** [comment]
Okay, there may be a bug related to that then as it should use https if the spec is hosted on https. Can you try adding `"schemes": ["https"]"` to your root document and see if that resolves it for now?

**Comment by bretzmo** [comment]
I'm not sure where I'm supposed to add that.

**Comment by webron** [comment]
Take a look here - https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/json/petstore-minimal.json#L17-L19 - though of course use https instead of http. I'm not sure how to do that with the library you're using (not sure which library it is actually).

**Comment by bretzmo** [comment]
I forgot to mention that we are using go-restful/swagger.

**Comment by webron** [comment]
I see, in that case, you're using Swagger 1.2. 

In the UI, you have a text box with a URL just before the `Explore` button. Can you open that URL directly in your browser and share the output of it? If you'd rather not share it in public, you can email me directly (email in profile).

**Comment by bretzmo** [comment]
![screen shot 2015-03-06 at 11 49 25 am](https://cloud.githubusercontent.com/assets/3484310/6535082/00623a08-c3f7-11e4-87f9-78763f10d1cc.png)

**Comment by bretzmo** [comment]
Sorry, that was the url without the swagger.json in it....here it the right screen shot.
![screen shot 2015-03-06 at 11 51 16 am](https://cloud.githubusercontent.com/assets/3484310/6535111/35630070-c3f7-11e4-807d-2eaee85aab54.png)

**Comment by webron** [comment]
Okay, so the problem is that your basePath uses http and not https. I'm not familiar with go nor go-resftul so I'm not sure how to fix that, though I assume setting https://github.com/emicklei/go-restful/blob/89af920d613f1e3f771f6460b2629632e7a36ae9/swagger/swagger.go#L119 would solve that issue.

**Comment by bretzmo** [comment]
So our base path is relative. Every time we deploy code the server is torn down a rebuilt, thus a new base path with every deploy.

**Comment by webron** [comment]
That's fine, but you still need to build it with https and not http if you want the operations to run against https.

**Comment by bretzmo** [comment]
I'm not sure what you are saying.

**Comment by webron** [comment]
If you look at the JSON you shared, and look at the `basePath` property, which is the basis for API calls. As long as it uses http and not https, the requests will end up using http. You need to find a way to make sure it ends up being https.

**Comment by Spin45** [comment]
webron, could you all explore allowing a schemeless protocol to be entered, e.g., "//" instead of "http://"? This would allow people who do not want to specify/force one protocol over another to access our Swagger docs and try them out. This would not prevent people from being specific about the protocol they wish to use at all, if so desired.

For example we have both http and https versions of our web assets, including web services using a schemless URL approach (see section 4.2 of RFC 3986) that provides for fully qualified URLs that omit protocol (the HTTP or HTTPS) altogether. When a URL’s protocol is omitted, the browser uses the underlying document’s protocol instead.

This would allow both (http and https) versions of my Swagger docs to have a working "Try It out!" feature.

**Comment by webron** [comment]
@Spin45 - no need to explore. Swagger 2.0 supports it already.

**Comment by webron** [comment]
@bretzmo - any update on this?

**Comment by fehguy** [comment]
please reopen if still an issue.

**Comment by brenovieira** [comment]
Same issue here. My swagger.json is the following (replacing '...' with some data):

```javascript
{
	"swagger": "2.0",
	"info": {
		"version": "v1",
		"title": "Documentation for API",
		"description": "..."
	},
	"host": "apiuat:3030",
	"schemes": ["http",	"https"],
	"paths": {
		"...": { ... }
	},
	"definitions": {
		"...": { ... }
	}
}
```

And I'm calling the swagger-ui in this function:

```javascript
$(function () {
    var version = window.location.href.match(/v\d+(\.\d+)*/); //any v1, v1.2, v1.2.3 ...
    version = version && version[0] ? version[0] : 'v1';
    var url = window.location.origin + '/docs/' + version;

    window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        validatorUrl: null,
        supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
        onComplete: function (swaggerApi, swaggerUi) {
            log("Loaded SwaggerUI");
            
            $('pre code').each(function (i, e) {
                hljs.highlightBlock(e)
            });

            $('#api_info').addClass('container');
            $('input[name=grant_type]').val('password');
        },
        onFailure: function (data) {
            log("Unable to Load SwaggerUI");
        },
        docExpansion: "none",
        apisSorter: "alpha",
        //operationsSorter: "alpha"
    });

    swaggerUi.load();
});
```

When I 'Try it out!' one of my methods, I'm getting the following error on Google Chrome:

> Mixed Content: The page at 'https://apiuat:3030/docs/#!/Auth/AuthHb_Login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://apiuat:3030/api/auth'. This request has been blocked; the content must be served over HTTPS.

Should my swagger.json "schemes" be only ["https"] ? I'm asking this, because I have dev, uat and prod environments and we don't use https in dev (just in uat and production).

I'm using Swashbuckle, by the way.

Thanks

**Comment by webron** [comment]
@brenovieira - I know it looks similar, but it's actually a different issue (or at least potentially). Can you open a separate ticket on it?

**Comment by brenovieira** [comment]
@webron - Sure! But I just saw that we're using swagger-ui.js version 2.1.0-alpha.4.

I updated to 2.1.0 and we'll deploy to uat environment soon, then I'll test if the latest version (2.1.0) is showing the same problem and I open the issue.

**Comment by webron** [comment]
@brenovieira - great, thanks

**Comment by siarheipashkevich** [comment]
Hi, @brenovieira 

I have the same issue, could you please tell me how you resolved your initial issue?

Thanks, Siarhei

**Comment by pruthvigh** [comment]
@webron How do I add schemes to my spring code with springfox?

**Comment by giansalex** [comment]
This work.
<details><summary><code>findReact()</code> method</summary>
<p>

```js
var findReact = function(dom) {
    for (var key in dom) {
        if (key.startsWith("__reactInternalInstance$")) {
            var compInternals = dom[key]._currentElement;
            var compWrapper = compInternals._owner;
            var comp = compWrapper._instance;
            return comp;
        }
    }
    return null;
};
```
</p>
</details>
<hr>

Set *https* scheme:
```js
var ui = SwaggerUIBundle({
   // ....
  onComplete: function() {
     var schemeSelect = document.querySelector('.scheme-container select');
     FindReact(schemeSelect).setScheme('https');
   }
});
```
