### ISSUE TITLE
Can the specification in yaml be provided as a string to the SwaggerUIBundle

### ISSUE THREAD

**Issue by biswa1shaw** [swagger-api/swagger-ui#10105]
we are currently stuck with a product that does not expose a swagger url directly. It however allows to download it as a zipped file.
There is a middleware application that would provide the yaml specs in an http response but as a string like below 
{
  "assetId": <some-uuid>,
  "assetName": <name-of the asset>,
  "specification": "the specification yaml here"
}

I was wondering if there is a way to load this string specification to the swagger ui bundle.

**Comment by ponelat** [comment]
The `spec` argument supports a JS Object version of the API Definition. You can use a  YAML parser (like js-yaml) to convert it to an  object, before passing it into `spec`. Hopefully  the docs help: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#core
