### ISSUE TITLE
Update the favicon to the one used in swagger.io

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-ui#1012]
Please :)

**Comment by mohsen1** [comment]
The favicon is not HiDPI ready. I'm going to create a better one and update swagger.io too

![screen shot 2015-03-09 at 6 01 42 pm](https://cloud.githubusercontent.com/assets/543633/6567550/71949432-c686-11e4-9827-610c0590db4d.png)

**Comment by webron** [comment]
Cool, man. If you need any resources let me know.

**Comment by mohsen1** [comment]
#1018 fixed this
