### ISSUE TITLE
Properly encode slashes in path parameters

### ISSUE THREAD

**Issue by gwicke** [swagger-api/swagger-ui#1013]
Swagger-UI does not currently encode slashes in path parameters supplied in the auto-generated sandbox form. This results in invalid requests whenever the user-supplied parameter value includes a slash.

**Comment by gwicke** [comment]
See also: https://github.com/swagger-api/swagger-spec/issues/93

**Comment by webron** [comment]
This is now managed by https://github.com/swagger-api/swagger-js/pull/280.

**Comment by fehguy** [comment]
please watch the above-mentioned issue in swagger-js
