### ISSUE TITLE
Error when adding swagger-ui-react with bun

### ISSUE THREAD

**Issue by neverm25** [swagger-api/swagger-ui#10148]
### Environment
 - OS: [ubuntu 22.0.4]
 - Node: 22.9.0
 - Bun: 1.1.29

### Description
I am getting the error while adding swagger module with bun on my frontend project.
![image](https://github.com/user-attachments/assets/e3b84956-e576-4def-bbf0-727b1a87a3dd)

**Comment by kaioduarte** [comment]
Works fine with bun 1.1.30. Anyway, I think this should've been reported to the bun repo instead.

![image](https://github.com/user-attachments/assets/302ea545-54c8-4652-b29e-013ede81a372)
