### ISSUE TITLE
Header Parameters not being sent in request

### ISSUE THREAD

**Issue by hamx0r** [swagger-api/swagger-ui#1019]
I have a GET request with a parameter in the header.  When using Swagger UI to "Try it Now", i don't see that parameter on the server side.  If i try using PostMan, the parameter shows up.   

Here's a snippet of the Swagger spec
```
  "/flights":{  
         "get":{  
            "tags":[  
               "flights"
            ],
            "summary":" Paginated flights ",
            "responses":{  
               "default":{  
                  "description":"successful operation"
               }
            },
            "parameters":[  
               {  
                  "paramType":"header",
                  "required":true,
                  "type":"string",
                  "name":"Range",
                  "description":"Range (ie \"500-999\") of flights requested"
               }
            ],
            "produces":[  
               "application/json"
            ]
         }
      },
```

I was using swagger-client.js v2.1.9-M1 then upgraded to v2.1.10-M1 from [swagger-js master branch](https://github.com/swagger-api/swagger-js).  It didn't seem to help.  Am I doing something wrong?  What area of the JS files when Try It Now is clicked?  I don't see any triggers tied to `onclick` or `onsubmit` when using Chrome's Developer Tools.

**Comment by webron** [comment]
This is probably related to CORS. 

One of the headers supplied by the server is `Access-Control-Allow-Headers`, for example:
``Access-Control-Allow-Headers: Content-Type, api_key, Authorization``

In order for the UI to be able to send the `Range` header, you have to add it to that list.

**Comment by hamx0r** [comment]
You were right that my `Access-Control-Allow-Headers` were restrictive.  Even after adding `Range` to the list, the Range header parameter was not showing up at the server side.  Also, `api_key` was not in the `Access-Control-Allow-Headers` list yet that feature is working fine.  

Using PostMan to send test data results in different debug output on the server side (ie printing out `request.headers.items()` _includes_ `Range` with PostMan, but _does not_ include `Range` with Swagger UI).  This convinces me it's a client-side problem, so i'm investigating various JS files.

**Comment by webron** [comment]
Before you dive in there, I'd suggest looking into the web console and see what is actually produced. The Pet Store includes an operation with a header parameter and it works just fine.

**Comment by hamx0r** [comment]
Thanks.  Since i'm using Swagger 2.0, I'd taken a look at the [Pet Store spec here](https://github.com/swagger-api/swagger-ui/blob/master/test/specs/v2/petstore.json).  The only header paramter was the api_key for `DELETE` on `/pet`.  Since `api_key` is used for auth, this is a special case which may not account for the more generalized use of header parameters as part of the API (not just auth).  

Using Chrome's Developer Tools (Network -> All -> Headers) I can see Range with PostMan, but _not_ with Swagger.  Here are the request headers:
*From Swagger*

    Accept:application/json
    Accept-Encoding:gzip, deflate, sdch
    Accept-Language:en-US,en;q=0.8
    Connection:keep-alive
    Host:abc.com
    Referer:https://abc.com/api_docs/
    User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
    X-Identity-Token:<long-token-went-here - we use this instead of api_key>

*From PostMan*

    Accept:*/*
    Accept-Encoding:gzip, deflate, sdch
    Accept-Language:en-US,en;q=0.8
    Cache-Control:no-cache
    Connection:keep-alive
    Host:abc.com
    Range:500-510
    User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
    X-Identity-Token:<long-token-went-here - we use this instead of api_key>

Could the different `Accept` values cause this?

Looks like my issue here is a re-opening of #895.  I used the latest master and dev branches, but the issue still occurred.   The _only_ difference in my code and the current dev branch is in index.html at:
line 63 - We use `X-Identity-Token` instead of `api_key`:
`window.authorizations.add("api_key", new ApiKeyAuthorization("X-Identity-Token", key, "header"));`

And line 89 - Simply change the placeholder on the UI for the token:
`<div class='input'><input placeholder="X-Identity-Token" id="input_apiKey" name="apiKey" type="text"/></div>`

**Comment by webron** [comment]
It's true that the pet store uses the same header as the one defined in the security but that's just for convenience. Can you perhaps provide me with a sample spec exhibiting the issue? I can use that for further testing. If you want to share your own spec but not publish it publicly, you can email it to me (email in profile).

**Comment by hamx0r** [comment]
Sure thing.  Here's a trimmed down spec of my actual project. I tried it with the latest master branch and it shows the same problem (ie Chrome Developer Tools does not show `Range` in the header)
```json
{  
   "info":{  
      "version":"1.0",
      "contact":{  
         "name":"Broken flights",
         "email":"broken@flights.com"
      },
      "title":"Flights API"
   },
   "paths":{  
      "/flights":{  
         "get":{  
            "tags":[  
               "flights"
            ],
            "summary":" Paginated flights ",
            "responses":{  
               "default":{  
                  "description":"successful operation"
               }
            },
            "parameters":[  
               {  
                  "paramType":"header",
                  "required":true,
                  "type":"string",
                  "name":"Range",
                  "description":"Range (ie \"500-999\") of flights requested"
               }
            ],
            "produces":[  
               "application/json"
            ]
         }
      }
   },
   "swagger":"2.0",
   "tags":[  
          {  
         "name":"flights"
      }
   ]
}
```

**Comment by webron** [comment]
@mohsen1 - can you please investigate it? It looks like there's a potential bug here (though if there is, it's probably coming from swagger-js).

**Comment by hamx0r** [comment]
Here's a clue:  I'm using Swagger with a Python Pyramid backend and see this traceback server-side on the error:
```python
    content_range = self.request.headers['Range']
  File "...python2.7/site-packages/webob/headers.py", line 139, in __getitem__
    return self.environ[_trans_name(hname)]
KeyError: 'HTTP_RANGE'
```

I did see some code in swagger-client.js changing strings `toUpperCase`, and it looks that the `Range` parameter is being renamed somehow to be called `HTTP_RANGE`.  

This error does _not_ appear when using PostMan - only when using Swagger UI.

**Comment by jsimmonsc** [comment]
I think this might be related to some weirdness I just tracked down.  Inside the operation.handlebars the response-content-type div is inside of the if type conditional. From reading the spec it isn't required to have the type, so I tried moving the div outside of the conditional and I was able to get it working again.

**Comment by fehguy** [comment]
The issue is much more simple.  The param type is wrong:

```
"paramType":"header"
```

should be
```
"in":"header"
```

After updating that, it works as expected.

**Comment by HungryCollegeMenus** [comment]
I have the same issue and i am using swagger with rails. I have used it like:
param :header, 'auth_token', :string, :required, 'Authentication Token'

and i am getting nil in request.headers['auth_token'].

Can anyone tell me what is wrong here?

**Comment by zia954** [comment]
I have the same issue and i am using swagger with rails. I have used it like:
param :header, 'auth_token', :string, :required, 'Authentication Token'

and i am getting nil in request.headers['auth_token'].

Can anyone tell me what is wrong here?
