### ISSUE TITLE
Prevent Button Shift by Moving 'Copy-to-Clipboard' Button to the Left of Static Controls

### ISSUE THREAD

**Issue by Naegolus** [swagger-api/swagger-ui#10215]
### Content & configuration

Swagger/OpenAPI definition: I think not needed in this case.

Swagger-UI configuration options: Don't know, since I am not using Swagger directly.

### Is your feature request related to a problem?

No problem but UI is a little bit annoying in this small section.

For every endpoint of an API, there are three control elements to the right of an "opblock-summary" class.
Check the screenshots below.
Two of them ("arrow" and "authorization_btn") are always visible,
but the third one ("copy-to-clipboard") is visible only when I move the mouse over them.
Unfortunately the optional control element "copy-to-clipboard" is inserted on the right most place.
Since the control elements are right aligned, the position of the first two elements have to change in this case,
causing me to click on an unintended button => Annoying

For example:
My intention is to click on the "arrow" element.
Therefore I try to click the "arrow" element and move the mouse to the element.
Then the elements get shifted to the left, because the "copy-to-clipboard" appears on the right most place.
Suddenly the "authorization_btn" is under the mouse cursor and is probably clicked.

What makes this even more spicy is the fact, that the process of inserting the "copy-to-clipboard" element is animated,
therefore I have to wait until the animation has finished. Only then I can / should click on the UI (after adjusting the mouse cursor a second time, slightly to the left).

### Describe the solution you'd like

I think for right aligned objects, optional ones should be inserted on the left in general.
For left aligned objects, optional ones should be inserted on the right.

Looking at the web code, this doesn't seem to be a trivial change tbh,
but I am not a web dev ..

### Additional context (Screenshots)

Mouse not over element
![Screenshot from 2024-11-13 15-47-20](https://github.com/user-attachments/assets/ef0c9c7e-f369-476d-aead-42f872b6ccd4)

Mouse over element
![Screenshot from 2024-11-13 15-47-25](https://github.com/user-attachments/assets/3e2cba95-4f3c-4b27-84e0-465255656c00)

Element inspection
![Screenshot from 2024-11-13 15-50-03](https://github.com/user-attachments/assets/4e4fae99-cc8e-410b-a82b-cddd441e8521)

**Comment by Naegolus** [comment]
Another option would be to keep the right most place for the "copy-to-clipboard" button and statically allocate the space for the button, changing only the visibility on mouse-over event.

**Comment by AllanOcelot** [comment]
Hi @Naegolus  - can you please confirm what version of Swagger you are on? I've run the latest master branch locally and the copy Icon is inserted to the left, as expected. 
![image](https://github.com/user-attachments/assets/acf85788-9204-414f-88c5-a4a5817adf3e)

**Comment by Naegolus** [comment]
oh. Wow. Didn't expect that. Nice.
swagger.json tells me `3.0.1`.
This issue can be closed then I think.
