### ISSUE TITLE
Specified null parameter throws error into console

### ISSUE THREAD

**Issue by erycek** [swagger-api/swagger-ui#10226]
### Q&A (please complete the following information)
 - OS: Any
 - Browser: Any
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets] gradle?
 - Swagger-UI version: Ouptut of versions: {"swaggerUI":{"version":"5.17.14","gitRevision":"g8aa52920","gitDirty":true,"buildTimestamp":"Tue, 28 May 2024 05:23:41 GMT"}}
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
After specifying parameter to be null, there is error in console, no request is fired and there is infinite spinner.
There is also no error reported to user

### To reproduce...

1. Have a `GET` request with QUERY parameters.
2. Don't remove the parameter fully, rather set the parameter to null: "key": null
3. Open console
4. Send request
5. See error

### Expected behavior
The request should be sent and no error should be in console.

### Screenshots
![image](https://github.com/user-attachments/assets/c1515e4c-0054-4e87-945a-26671faa2a90)
![image](https://github.com/user-attachments/assets/1860786c-cef0-4947-ae47-083e87f928e8)

**Comment by glowcloud** [comment]
Addressed upstream in Swagger Client: https://github.com/swagger-api/swagger-js/pull/3726. Released as https://github.com/swagger-api/swagger-js/releases/tag/v3.32.2.
