### ISSUE TITLE
Performance when building the page

### ISSUE THREAD

**Issue by marcgise** [swagger-api/swagger-ui#1024]
Hi,

Swagger-ui takes a lot of seconds to fulfill the page, after request the server about the controllers info.

I think that it is because it tries to fill all the DOM at this moment. If you have a lot of controllers (in my case we have more than 30 controllers with a lot of public services), maybe the best way to do that is to fill this element in the DOM when you expand it, instead of filling all the elements at the beggining.

Cheers,
Marc

**Comment by webron** [comment]
@marcgise - I assume you're using Swagger 1.2? It should be much less of an issue with Swagger 2.0.

**Comment by marcgise** [comment]
@webron - swagger.js file indicates version 2.0.47, and swagger-ui.js indicates version 2.1.0-alpha.7...

Thanks.

**Comment by webron** [comment]
I'm talking about the version of the spec, not the version of the UI (though you may want to upgrade to the latest master).

**Comment by marcgise** [comment]
Sorry... We're using the 0.9.4 version, available in maven repository.
		<dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>0.9.4</version>
		</dependency>

**Comment by webron** [comment]
Yes, that's produces 1.2 specs. I know they have plans to release support for 2.0 fairly soon.

**Comment by fehguy** [comment]
There are also massive performance fixes in swagger ui 2.1.9-M1. If is over 100x faster for 1.2 specs which is what that version of swagger-spring-mvc uses

**Comment by marcgise** [comment]
OK thank you very much! I will wait for this release :)

**Comment by fehguy** [comment]
No need to wait. It's releas d, just grab the dist folder from this repo

**Comment by fehguy** [comment]
I stand corrected, 2.1.8-M1 is current release.  Apologies for that

**Comment by marcgise** [comment]
mmmmmm

I have change my current version of swagger-ui for the last 2.1.8-M1, and sincerely I don't see any improvement in the performance...

I have an amount of 48 controllers with a average of 8 services every one, and it takes 15 seconds loading the page...

**Comment by webron** [comment]
Have you cleared your browser's cache? ;)

**Comment by marcgise** [comment]
of course! :) Many many many times :D There is a curious behaviour... The expended time varies, sometimes 7 seconds, 10, 12, 15... It is very very strange...

**Comment by webron** [comment]
Is your API publicly accessible? Can we have a look?

**Comment by fehguy** [comment]
also if you can share a snapshot of the network tab from your browser, that'd be helpful

**Comment by marcgise** [comment]
We have a PRE environment where you can check this behaviour:
http://app3.prodevelop.es/cscturismo/swagger/csc.html

Thanks.

**Comment by marcgise** [comment]
As you can see, we modified a little bit the html in order to remove the API authentication, cause we don't need it.

**Comment by fehguy** [comment]
I think you need to file a ticket with the springmvc folks, or see how you're hosting this.  When I use time + curl from my 200mbps connection, it takes a total of 21 seconds just to download the JSON files.  That means the time is spent either generating or serving the files.  This isn't a swagger-ui issue it seems.

**Comment by marcgise** [comment]
Hello @fehguy, I don't understand how you did it, because as you can see in the attached image, Chrome requests takes only 1.5 seconds.
![imagen001](https://cloud.githubusercontent.com/assets/4680243/6614160/e8d3789e-c896-11e4-83a7-c2a247c3397a.png)

I think it's not fault of swagger-mvc.

**Comment by fehguy** [comment]
I made the requests in serial which is why the time was so long. i will look again shortly

**Comment by fehguy** [comment]
I retract the spring-mvc blame.  Sorry!  It's slow because of this block of code in index.html:

```
          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });
```

You can disable this highlight code and the performance issue should be gone.  I will open a new ticket to look into how we can speed up this rendering.

**Comment by marcgise** [comment]
Thanks fehguy, tomorrow I'll try it at work and I tell you how it goes... thank you very much!

**Comment by marcgise** [comment]
Thank you @fehguy, this workaround does the trick and now it only takes 5 seconds to load the page. Is this code necessary? What is its purpose?

**Comment by webron** [comment]
I believe it is used to provide code highlighting for the JSON models you see along the UI.
