### ISSUE TITLE
Missing some paths when display

### ISSUE THREAD

**Issue by nvcnvn** [swagger-api/swagger-ui#1025]
I have a swagger file http://internavenue.github.io/api/docs/v0.json the content valid and disaply all when using with http://editor.swagger.io/
I try that file with both http://petstore.swagger.io/ and my lastest version on my local machine, in both case some url are missing. For example I can't find "/schools".

**Comment by webron** [comment]
Bug confirmed.

The operations that are not being displayed are the operations that have an empty `tags` property (as opposed to not having it at all). The parsing should treat tag-less operations and operations with no tags the same (i.e. as default).

**Comment by webron** [comment]
@nvcnvn - As a workaround, since you manually created the spec, you can just remove the empty `tags` from the operations, or actually use them to better group and organize the display.

**Comment by nvcnvn** [comment]
Tks you for the workaround!

**Comment by mohsen1** [comment]
This is an issue in swagger-js. Please follow it here https://github.com/swagger-api/swagger-js/issues/291
