### ISSUE TITLE
OAuth scope not correct

### ISSUE THREAD

**Issue by svrooij** [swagger-api/swagger-ui#1031]
According to the [OAuth2.0 specs](https://tools.ietf.org/html/rfc6749#section-3.3) the scope parameter of the Authorization request should be an space delimited list of scopes.
Our authorization server follows the specs and can't easily be changed. To let Swagger-UI follow the specs only one line needs to be changed.

[Line 150 of swagger-oauth.js](https://github.com/swagger-api/swagger-ui/blob/14f27da1141eb83f78e560e12693970417b7319c/lib/swagger-oauth.js#L150)
`url += '&scope=' + encodeURIComponent(scopes);` should be changed to `url += '&scope=' + encodeURIComponent(scopes.join(' '));`

**Comment by mohsen1** [comment]
Please use [`develop_2.0`](https://github.com/swagger-api/swagger-ui/blob/develop_2.0) branch. This issue has been [fixed there](https://github.com/swagger-api/swagger-ui/blob/develop_2.0/lib/swagger-oauth.js#L153)

**Comment by oreporan** [comment]
The links you provided are broken.
I am still getting this issue
thanks
