### ISSUE TITLE
Develop_2.0 doesn't work at 194f2d5fb5c23837ecb5bf00cd5ad8d74dcf50dd

### ISSUE THREAD

**Issue by mwenk-posportal** [swagger-api/swagger-ui#1033]
Using Chrome Version 41.0.2272.89 m: 

Steps: 
- Open JS Console
- Type 1234 in api_key then tab out of field
- Click explore

Expected: 
- No JS console errors. 
- Normal swagger behavior on clicking explore

Actual: 
JS Console shows: 

Uncaught ReferenceError: log is not defined
Uncaught TypeError: undefined is not a function

No perceived change of any kind in browser window

**Comment by mohsen1** [comment]
This issue was fixed in develop_2.0. Thanks for reporting.
