### ISSUE TITLE
"body" parameter of type Array[$ref] not correctly referencing the model

### ISSUE THREAD

**Issue by sufferingtrout** [swagger-api/swagger-ui#1037]
When a body parameter is an Array of type Model, the Model type is not referenced. Only the model path is referenced:

spec doc:
```javascript
{
    "swagger": "2.0",
    "info": {
        "description": "...",
        "version": "1.0.0",
        "title": "..."
    },
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "paths": {
        "/events": {
            "post": {
                "tags": [
                    "events"
                ],
                "summary": "...",
                "description": "...",
                "consumes": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "events",
                        "description": "Array of Events to be processed.",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Event"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "nocontent"
                    }
                }
            }
        }
    },
    "definitions": {
        "Event": {
            "properties": {
                "type": {
                    "type": "string",
                    "description": "thetypeoftheevent."
                }
            }
        }
    }
}
```

Resulting rendering:
![screen shot 2015-03-16 at 2 29 48 pm](https://cloud.githubusercontent.com/assets/7682562/6676945/f35f33ca-cbe8-11e4-82b3-7dac891405e4.png)

This issue can also be seen in the Petstore example app:
http://petstore.swagger.io/#!/user/createUsersWithArrayInput

**Comment by mohsen1** [comment]
I think this is this issue https://github.com/swagger-api/swagger-js/issues/270

**Comment by nyddogghr** [comment]
Hi, there is something I don't understand. it seems that it has been fixed, but i still have this issue.
I'm using master, pulled today.
My generated json is 
```
{
   "parameters":[
      {
         "in":"body",
         "name":"body",
         "description":"The directories to create",
         "required":false,
         "schema":{
            "type":"array",
            "items":{
               "$ref":"#/definitions/DirectoryResource"
            }
         }
      }
   ]
}
```
But I still have this : 
![good1](https://cloud.githubusercontent.com/assets/3328219/6980971/8ea18cec-d9fa-11e4-8db6-6d98484bf1f5.png)

Do you know how to fix this ?

**Comment by webron** [comment]
It's actually not fixed. Please follow https://github.com/swagger-api/swagger-js/issues/343.

**Comment by nyddogghr** [comment]
Ok, thank you, I will wait then

**Comment by nyddogghr** [comment]
Now that it has been fixed in swagger-js, any idea on when it will be fixed in swagger-ui ?

**Comment by webron** [comment]
Can't say exactly when the next release is going to be, but you can always build the project on your own if you need.

**Comment by fehguy** [comment]
this is in swagger-js now, and will be part of next swagger-ui release.
