### ISSUE TITLE
Default Controller supercedes swagger's index.html

### ISSUE THREAD

**Issue by CraigFoote** [swagger-api/swagger-ui#1039]
I have swagger set up including the swagger ui index page. Now we want to implement a default controller with RequestMapping "/**" that will return a structured error object rather than the server's default 404 page. My problem is that this mapping means I can never reach index.html and I'm at a loss as to how this can be done. Anyone have any ideas? Any help greatly appreciated.

**Comment by webron** [comment]
As this is more of a general support question, please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersockethttps://groups.google.com/forum/#!forum/swagger-swaggersocket) for it.
