### ISSUE TITLE
Sorter option with 2.1.8-M1

### ISSUE THREAD

**Issue by julien-maurel** [swagger-api/swagger-ui#1040]
Hi,
I'm trying to migrate my apis to swagger 2.0 and I can't sort APIs in a tag group on the UI like before.
Sorter option have no effect (I tried "alpha" and "method").
I take a look in the code, and I see nothing that call sorter method. This option is no longer available in M1?
Thanks.

**Comment by julien-maurel** [comment]
I did it on my side. I extend MainView.prototype.initialize in my index.html.
If you want, I can do it properly in swagger-ui.js and send you a pull request.
But I see a method operationGroup.sort in swaggerClient, so perhaps you want to do it with another way.
More, in my extention of MainView, I added possibility to sort operations groups (tags in v2), and possibility to give a custom function to sort.

**Comment by fehguy** [comment]
I think it might be better living in the swagger-ui itself.

**Comment by julien-maurel** [comment]
Ok. I'll send you a PR in a moment.

**Comment by julien-maurel** [comment]
PR done!
