### ISSUE TITLE
Cannot find module './lib/swagger-ui/dist/lib/shred/content' 

### ISSUE THREAD

**Issue by collaborator99** [swagger-api/swagger-ui#1041]
Cannot find module './lib/swagger-ui/dist/lib/shred/content' error appears with the latest version v2.1.8-M1.  

The example: dist/index.html produces the same error.

This error did not happen with the last version we were using: version 2.1.0-alpha.7.

Any ideas on how to fix this?

**Comment by mohsen1** [comment]
Could you try develop_2.0 branch?

**Comment by webron** [comment]
@collaborator99 - did you get a chance to test it?

**Comment by mohsen1** [comment]
We removed the dependency to shred now. This issue is not relevant anymore

**Comment by webron** [comment]
That's great news then, can be closed.
