### ISSUE TITLE
List model definitions in Swagger UI

### ISSUE THREAD

**Issue by thomasddn** [swagger-api/swagger-ui#1052]
Hi,

Could an option be provided to have the Swagger UI list all the model definitions just like the Swagger Editor does at the bottom? Having all the model definitions at a glance makes it easier to find a certain definition.

Kind regards,
Thomas

**Comment by fehguy** [comment]
It's an option, marking this for consideration in next major release.

**Comment by cabbonizio** [comment]
+1

**Comment by terion-name** [comment]
+1

**Comment by aldwinb** [comment]
+1

**Comment by seanpk** [comment]
this feature will be especially handy when model inheritance is used and only the "base class" shows up in the docs right now ...

@stefanmeschke - have you done more work on this?

**Comment by JasonArm** [comment]
+1 Please,Please.
_It is weird how swagger-editor shows the definitions in a separate section; but not SwaggerUI_

**Comment by marpereira** [comment]
+1

**Comment by PedroMD** [comment]
+1
Too bad this keeps getting delayed and delayed :\ Hoping it will eventually be implemented...

**Comment by fehguy** [comment]
There is a massive overhaul for swagger-ui going on right now.  That's when this will come in

**Comment by PedroMD** [comment]
Good to know - thanks, @fehguy :)

**Comment by stefanmeschke** [comment]
@seanpk 
I haven't done more work on this.
We worked the last month on an API-Manager including swagger ui export: https://github.com/DREEBIT/swagger-manager
However we would be very please if anyone wants to contribute.

**Comment by webron** [comment]
This was added in 3.0.

**Comment by JasonArm** [comment]
Thank you.
