### ISSUE TITLE
Response with array different then 200 doesn't show.

### ISSUE THREAD

**Issue by marcinskubala** [swagger-api/swagger-ui#1055]
Hi, ui doesn't show the model shema.
```
"responses": {
	"200": {
		"description": "media response",
		"schema": {
			"type": "array",
			"items": {
				"$ref": "#\/definitions\/Media"
			}
		}
	},
	"default": {
		"description": "unexpected error",
		"schema": {
			"$ref": "#\/definitions\/Error"
		}
	},
	"422": {
		"description": "validation error",
		"schema": {
			"type": "array",
			"items": {
				"$ref": "#\/definitions\/ValidationError"
			}
		}
	}
}
```

**Comment by webron** [comment]
You mean it doesn't display it for default and 422?

**Comment by marcinskubala** [comment]
The model schemes for 200 and default are fine, but the 422 is an array of ValidationError and the "Model" and the "Model Scheme" tabs in UI are empty.

**Comment by webron** [comment]
Is there actually a ValidationError model in the definition? It would help if you shared your whole Swagger definition for testing.

**Comment by marcinskubala** [comment]
```
{
    "swagger": "2.0",
    "info": {
        "title": "XXX",
        "version": "XXX"
    },
    "host": "XXX",
    "basePath": "XXX",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application\/x-www-form-urlencoded"
    ],
    "produces": [
        "application\/json",
        "application\/xml"
    ],
    "paths": {
        "\/media": {
            "post": {
                "tags": [
                    "Media Operations"
                ],
                "summary": "Create a new media",
                "parameters": [
                    {
                        "name": "title",
                        "in": "formData",
                        "description": "Media title",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Media Response",
                        "schema": {
                            "$ref": "#\/definitions\/Media"
                        }
                    },
                    "Default": {
                        "description": "Default Error",
                        "schema": {
                            "$ref": "#\/definitions\/Error"
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "schema": {
							"type": "array",
							"items": {
								"$ref": "#\/definitions\/ValidationError"
							}
						}
                    }
                }
            }
        }
    },
    "definitions": {
		"Media": {
            "required": [
				"id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "Error": {
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        },
        "ValidationError": {
            "required": [
                "field"
            ],
            "properties": {
                "field": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Comment by webron** [comment]
Which library produced that spec?

**Comment by marcinskubala** [comment]
zircote/swagger-php v2.x

**Comment by webron** [comment]
I believe this is related to https://github.com/swagger-api/swagger-js/issues/270.

**Comment by webron** [comment]
@marcinskubala - do you mind if I use the Swagger definition you shared here to open an issue on swagger-php? There are three problems with it they should solve.

**Comment by marcinskubala** [comment]
@webron - yep, fill free to share this code, thanks

**Comment by webron** [comment]
@marcinskubala - thanks.

@mohsen1 - can you please confirm this is the same issue?

**Comment by tlbdk** [comment]
Have the same issue, with this schema where the response model is missing for everything but 200:

![image](https://cloud.githubusercontent.com/assets/11635/7115343/28f61c00-e1e8-11e4-9210-6ea775876198.png)


{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Test sample showing swagger error",
        "description": "Show that response headers are not rendered",
        "contact": {
            "name": "Troels Liebe Bentsen",
            "email": "tlb@nversion.dk"
        }
    },
    "host": "localhost",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/test": {
            "post": {
                "summary": "Test",
                "description": "Test stuff",
                "operationId": "doTest",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        }                       
                    },
                    {
                        "in": "header",
                        "name": "ETag",
                        "description": "Used as caching key for future requests",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test stuff response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        },
                        "headers": {
                            "ETag": {
                                "description": "Used as caching key for future requests",
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "headers": {
                            "ETag": {
                                "description": "Used as caching key for future requests",
                                "type": "string"
                            }
                        },
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        }
                    }
                },
                "tags": ["test"]
            }
        }
    },
    "definitions": {
        "test": {
            "required": [
                "test1",
                "test2"
            ],
            "properties": {
                "test1": {
                    "type": "string"
                },
               "test": {
                    "description": "Amount to be payment",
                    "type": "number",
                    "format": "double",
                    "default": 0
                }
            }
        }
    }
}

**Comment by fehguy** [comment]
@mohsen1 can you please look at this?

**Comment by tlbdk** [comment]
Updated to latest version from master and I still see the issue

**Comment by mohsen1** [comment]
I've spent some time looking into this issue. I don't know exactly what we should do here because the way we're passing [`responseModel` to `StatusCodeView` is via `optiosn.responseModel` option](https://github.com/swagger-api/swagger-ui/blob/develop_2.0/src/main/javascript/view/OperationView.js#L124-L136) which is a string and use that string to [lookup `router.api.models` object](https://github.com/swagger-api/swagger-ui/blob/develop_2.0/src/main/javascript/view/StatusCodeView.js#L12)

We're resolving `$ref`s here but we're not doing it deeply. If we were to resolve deeply then should we pass the inner `schema` name string? If we do that, it's not accurate because the model should be the array. 

I think `$ref` resolving mechanism needs a refactoring. We can't rely on little components resolve `$ref`s little by little.

**Comment by ponelat** [comment]
I agree, a little refactoring would be great. I kinda went looking at the same problem...
https://github.com/swagger-api/swagger-ui/issues/671#issuecomment-97431178

**Comment by fehguy** [comment]
please follow parent issue #1248
