### ISSUE TITLE
Support oneOf

### ISSUE THREAD

**Issue by nickretallack** [swagger-api/swagger-ui#1056]
I used a oneOf and it rendered as an empty object.  It seems to be ignored right now.

**Comment by webron** [comment]
`oneOf` is not supported by the Swagger specification.

**Comment by nickretallack** [comment]
Not even in the part where it delegates to jsonschema?

**Comment by webron** [comment]
Not anywhere. We don't delegate to JSON Schema. The spec is very specific about it. We use an extended subset of JSON Schema, and explicitly don't support `oneOf`.

**Comment by hansbeld** [comment]
Unfortunately no. It uses a subset of the draft-4

**Comment by willshulman** [comment]
Just curious. Why was oneOf explicitly not supported?

**Comment by webron** [comment]
@willshulman - https://github.com/swagger-api/swagger-spec/issues/57

**Comment by wir33658** [comment]
This way something like defining a tree structure is not possible ..... Really bad news (Thought Swagger is good, but  - oh, well ....)

E.g.

        "ModelFolder": {
            "properties": {
                "id": {
                    "type": "number",
                    "format": "integer"
                },
                "parentId": {
                    "type": "number",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "itemType": {
                    "type": "string"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "anyOf":[
                            { "$ref": "#/definitions/ModelFolder"  },
                            { "$ref": "#/definitions/Model" }
                        ]
                    }
                }
            },
        "Model": {
            "properties": {
                "id": {
                    "type": "number",
                    "format": "integer"
                },
                "parentId": {
                    "type": "number",
                    "format": "integer"
                },
                "name": {
                    "type": "string"
                },
                "itemType": {
                    "type": "string"
                }
            }


is not possible ?!?!?!?

I don't get it (Please be more pragmatic. But maybe its technically simply not doable in the Swagger implementation).

**Comment by webron** [comment]
It is doable, but please send your question to the google group. It has nothing to do with the UI.

**Comment by rsuter** [comment]
Ok, i have this C# code: 

```
public class TestClass
{
    [Required] // <= not nullable
    public ReferencedClass RequiredProperty { get; set; }

    public ReferencedClass NullableProperty { get; set; }
}

public class ReferencedClass
{
    public string Test { get; set; }
}
```

Both properties reference the same `ReferencedClass` (i.e. it must be a reference in the generated schema). The generated schema would look like this (JSON Schema draft4): 

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "RequiredProperty"
  ],
  "properties": {
    "RequiredProperty": {
      "oneOf": [
        {
          "$ref": "#/definitions/ReferencedClass"
        }
      ]
    },
    "NullableProperty": {
      "oneOf": [
        {
          "$ref": "#/definitions/ReferencedClass"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "definitions": {
    "ReferencedClass": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Test": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}
```

As you can see, the schema for `ReferencedClass` cannot have a type of object AND null because it would be wrong for the first property (`RequiredProperty`). Also the `required` required array does not express nullability but if the field must be defined in JSON or not (it still can be null). 

How would you express this with the Swagger "special" JSON Schema?
