### ISSUE TITLE
Bug rendering <div> in description field (maybe only when markdown is used...)

### ISSUE THREAD

**Issue by liviosoares** [swagger-api/swagger-ui#1057]
If I have this within a description:

description: |
   Markdown works *here*
   But not ```<div>here</div>```

It renders incorrectly in swagger-ui:

![image](https://cloud.githubusercontent.com/assets/888951/6760567/3fefd0ac-cf20-11e4-8395-715be31d67b7.png)

but seems to work correctly in swagger-editor:

![image](https://cloud.githubusercontent.com/assets/888951/6760574/5ddea264-cf20-11e4-917d-2b606a820000.png)

**Comment by mohsen1** [comment]
@liviosoares please confirm your fix and close this bug.
