### ISSUE TITLE
is "description in Model property" supported in swagger 2.0 Yaml spec?

### ISSUE THREAD

**Issue by Ckim15** [swagger-api/swagger-ui#1063]
I tried to run this in swagger ui, it doesn't display the description.
Is the below spec correct?

Here is an definition of Amount Model:

Amount: 
properties:
currency: 
type: string
default: "USD"
description: "This is currency unit"
value:
type: number
format: double
required:
- currency
- value

**Comment by webron** [comment]
It should appear already. Check the Model view of User in this example - http://petstore.swagger.io/#!/user/getUserByName - specifically, the userStatus field.

**Comment by webron** [comment]
@Ckim15 - did you check this again?

**Comment by fehguy** [comment]
Closed as fixed:

![image](https://cloud.githubusercontent.com/assets/249413/7545671/acf0f0dc-f58b-11e4-910a-ce1e2ffd133b.png)
