### ISSUE TITLE
Allow file download dialog for cases of attachment response

### ISSUE THREAD

**Issue by barneaoren** [swagger-api/swagger-ui#1065]
Hi there,

So, I have a server, and it is working pretty good with Swagger-UI.

I have created a response handler for my server, for a GET request with no header parameters & for a unique path.
The response of this specific request contains the header "Content-Disposition" with the value of "attachment; filename=\"main.c\"" and with the body content of a "hello-world" program.

In case I'm performing a direct access via any browser, I'm getting the file download dialog properly.
Unfortunately, once trying to perform the same action via the Swagger-UI, the response is being somehow "down-graded" to be a one without the "Content-Disposition header, and only contains the "Content-Type" header.
The body message has being sent & received properly, but it is only being displayed at the response body part.
I would like to issue a download dialog. I have tried to track the code location for such handler, but was unable to locate it.

I know that it is currently not supported, but can anyone guide me please how to enable such operation?

Thanks in advance

**Comment by fehguy** [comment]
can you please retry?  it should be supported as of 2.1.0-m2

**Comment by webron** [comment]
@barneaoren - any update on this?

**Comment by barneaoren** [comment]
@webron - Actually, I just saw the previous answer.
I will be able to test it again only in 2 days.

@fehguy - As far as I recall, the latest release should only support a download link (not dialog). also, trying to add a "click" even call to that link will be provided with 2 save dialogs popped to the user, as the function is being called twice (for the showResponseStatus and for the showErrorStatus). Both calls are being done no matter what was the response data.

Currenly, Im still using the previous version of Swagger-UI, with a specific hack for re-creating the content-disposition header & with a show dialog handler to overcome the "double click" issue (a global flag dedicated for requests with response data to be downloaded), but it wount really help to share it (it is very local and very simple add-on).

**Comment by fehguy** [comment]
This should be supported now.
