### ISSUE TITLE
Parameter content type isn't shown when 'Try it out' is disabled

### ISSUE THREAD

**Issue by aleung** [swagger-api/swagger-ui#1068]
I use swagger-ui as our API document site. There is no test server deployed so I disable the 'Try it out' option.

But once 'Try it out' option is disabled, parameter content type isn't shown as well. API document need to tell developer what content type (even if it's `application/json`) the request body can be, so I think parameter content type should be shown no matter 'Try it out' option is enable or not.

**Comment by fehguy** [comment]
@ponelat can you look at this?

**Comment by fehguy** [comment]
fixed in master
