### ISSUE TITLE
Can I put multiple SwaggerUi objects in a single HTML page?

### ISSUE THREAD

**Issue by aleung** [swagger-api/swagger-ui#1069]
I created a HTML page following the README and the page renders fine.

``` html
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
<script>
   $(function() {
        window.swaggerUi = new SwaggerUi({url:"http://petstore.swagger.io/v2/swagger.json",dom_id:"swagger-ui-container"});
        window.swaggerUi.load();
   });
</script>
```

Then I tried to change the attribute name `window.swaggerUi` to other name (e.g. `myUi`), API operations weren't shown.

``` html
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
<script>
   $(function() {
        window.myUi = new SwaggerUi({url:"http://petstore.swagger.io/v2/swagger.json",dom_id:"swagger-ui-container"});
        window.myUi.load();
   });
</script>
```

My question is: why SwaggerUi object has to be assigned to `window.swaggerUi`? I searched the javascript and found that `window.swaggerUi` is referred in several places: ApiKeyButton, BasicAuthButton and swagger-oauth. But I don't use the 'Try It Out' option so it should has no affect to me.

**Comment by mohsen1** [comment]
Are you using develop_2.0 branch? If not, we've already fixed this issue. You don't have to append your SwaggerUi instance to window.

**Comment by aleung** [comment]
I'm using v2.1.8-M1 release. Will try latest on develop_2.0 branch. Thanks.

**Comment by aleung** [comment]
develop_2.0 branch works.

My next question: can I put multiple SwaggerUi objects in a single HTML page? 

I tried below code. Sometimes it's rendered correctly but sometimes all operations are shown under the first API. It happens occasionally when reload the page on browser.

``` html
<div id="swagger-ui-container-echo" class="swagger-ui-wrap"></div>
<script>
   $(function() { 
    var swaggerUi = new SwaggerUi({
        url: "/api-spec/echo.json",
        dom_id: "swagger-ui-container-echo"
    });
    swaggerUi.load();
   });
</script>
<hr/>
<div id="swagger-ui-container-uber" class="swagger-ui-wrap"></div>
<script>
   $(function() { 
    var swaggerUi = new SwaggerUi({
        url:"/api-spec/uber.json",
        dom_id:"swagger-ui-container-uber"
    });
    swaggerUi.load();
   });
</script>
```

Products, Estimates and User belong to Uber API but they were shown under Echo API.

![swagger-ui](https://cloud.githubusercontent.com/assets/271538/6820786/26737b06-d30d-11e4-930e-668c1aabd4b1.png)

**Comment by aleung** [comment]
I guess I found the reason.

`SwaggerUi.Views.MainView.addResource()` uses id selector to locale the element `<ul id="resources">` and appends `ResourceView` into it:

``` javascript
$('#resources').append(resourceView.render().el);
```

![domtree](https://cloud.githubusercontent.com/assets/271538/6821726/a9da0cd8-d314-11e4-9e51-276eeda7f7b1.png)

Now since I put multiple SwaggerUi objects with different dom_id into a single page, the ID `#resources` isn't unique any more. If change to use a selector that has `dom_id` in criteria then it might work. Is it possible for SwaggerUi to support that?

**Comment by mohsen1** [comment]
If we scope the selector to `this.el` it should solve this issue. 

So [here](https://github.com/swagger-api/swagger-ui/blob/develop_2.0/src/main/javascript/view/MainView.js#L133) it should be:

```js
 $('#resources', this.el).append(resourceView.render().el);
```

**Comment by mohsen1** [comment]
Please try that change and if it works open a PR with your change against develop_2.0

**Comment by aurelian** [comment]
:+1: I'm also looking for similar functionality.

**Comment by fehguy** [comment]
This should be fully supported now.
