### ISSUE TITLE
Only one path is listed when having duplicate paths

### ISSUE THREAD

**Issue by eduh** [swagger-api/swagger-ui#1070]
I have a simple api with only GET's  on the same path
Example:
/mystuff/?id=1&mode=1   (does provide information)
/mystuff/?id=1&mode=2   (does provide other information)

Now my goal is to describe both methods as seperate things so there are two entries listed....but in version 2.0 only the last get listed in the UI.  In version1.2 it was possible to have duplicate paths with descriptions.  Perhaps the answer is 'redesign your api's' but is there a workaround for it in version 2.0?

**Comment by eduh** [comment]
It is about these lines
    "paths": {
        "/mystuff": {
            "get": {

**Comment by mohsen1** [comment]
In Swagger 2.0 you can't do that. You should either update your API to use path parameter or describe your query parameter in one single path.
