### ISSUE TITLE
Display all paths without grouping by tags

### ISSUE THREAD

**Issue by nickretallack** [swagger-api/swagger-ui#1076]
Sometimes you just want to see what all possible paths are.  It would be nice if there was a view like this, that didn't group the paths by tags.

**Comment by hibikir** [comment]
IMO this is far more than a nice to have. Not having this in the UI, for all intents and purposes, makes having at least one tag per operation to be mandatory, which is not something marked in the spec.

As it is, I can write legal swagger 2.0 that is seen in the UI that looks like a blank page.

**Comment by webron** [comment]
@hibikir - that's not true. All operations that don't have a tag are automatically grouped under the `default` tag. Even if you don't have a single tag in your spec, all the operations would be displayed.

**Comment by webron** [comment]
Closing this one in favor of #1311.
