### ISSUE TITLE
Referenced responses are not rendered

### ISSUE THREAD

**Issue by mbaumgartl** [swagger-api/swagger-ui#1078]
I define some common responses and want to reference them in path endpoint(s):

```yml
swagger: "2.0"

info:
  title: Sample API
  version: 0.0.1

responses:
  ForbiddenError: # 403
    description: Access denied - additional privileges/rights required to retrieve item
    schema:
      $ref: '#/definitions/Error'
  NotFoundError: # 404
    description: Item not found
    schema:
      $ref: '#/definitions/Error'
  GeneralError: # 500
    description: Unrecoverable error - something really bad happened :-(
    schema:
      $ref: '#/definitions/Error'

paths:
  /article/{articleId}:
    get:
      description: Retrieve single article
      parameters:
        - name: articleId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Article
          schema:
            type: object
        403:
          $ref: '#/responses/ForbiddenError'
        404:
          $ref: '#/responses/NotFoundError'
        500:
          $ref: '#/responses/GeneralError'

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
```
The editor renders referenced responses while Swagger-UI doesn't.

**Comment by mohsen1** [comment]
This is probably fixed by the new swagger-js issue. I'll confirm it today

**Comment by fehguy** [comment]
let's add a test around this and close it after verification

**Comment by mohsen1** [comment]
Fixed in develop_2.0 branch at 3de0b36

![screen shot 2015-03-26 at 5 22 25 pm](https://cloud.githubusercontent.com/assets/543633/6859919/bb51f796-d3dc-11e4-9497-37ddcd6fef4c.png)

**Comment by mbaumgartl** [comment]
@mohsen1: Sorry, but I don't see the issue fixed. Neither description nor model is rendered for referenced responses. I opened this issue because I had the same output (I should have attached a screenshot).

**Comment by mohsen1** [comment]
hmmm... I see all the responses but apparently their contents are empty. It's an issue in swagger-js. Follow the issue here:

 https://github.com/swagger-api/swagger-js/issues/329

**Comment by fehguy** [comment]
confirmed fixed from https://github.com/swagger-api/swagger-js/commit/893eb994ec88fd9cc6c2e4d80e67164a4e19b6d8
![image](https://cloud.githubusercontent.com/assets/249413/6879408/92f59ed0-d4b1-11e4-912b-3ef9f3b81181.png)

**Comment by mbaumgartl** [comment]
Thanks for fixing the issue quickly! +1
