### ISSUE TITLE
model editor

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#1083]
As shown in this PR:

https://github.com/swagger-api/swagger-ui/pull/398

Would be nice to add an editor view into the UI.

**Comment by lepinayl** [comment]
I did an alternative solution on this PR [#1088](https://github.com/swagger-api/swagger-ui/pull/1088).

Would be nice if anyone could have a look at it too.

**Comment by fehguy** [comment]
Will merge #1083 to address this.
