### ISSUE TITLE
XML displayed wrong with GitHub Flavored Markdown

### ISSUE THREAD

**Issue by Tucura** [swagger-api/swagger-ui#1087]
If you put your xml in fenced code blocks ( ``` <xmlTag></xmlTag> ```) then all upper cases will be turned into lower cases ( <xmltag><xmltag>).

Work around: put xml code into a html pre code block but you have to encode all < >.

**Comment by mohsen1** [comment]
weird. We're using [marked](https://github.com/chjj/marked). It has no issue in Swagger Editor or when I use marked out of SwaggerUI. Are you sure this is happening in SwaggerUI develop_2.0 branch?

**Comment by webron** [comment]
@Tucura - have you retested with develop_2.0?

**Comment by fehguy** [comment]
Please reopen if still an issue.
