### ISSUE TITLE
convertInfo method doesn't support nulls

### ISSUE THREAD

**Issue by wonderlic-chrisk** [swagger-api/swagger-ui#1092]
In the latest version (2.1.8-M1), if a null is passed for info using swagger 1.2, the convertInfo method will blow up.

```
SwaggerClient.prototype.convertInfo = function (resp) {
  if(typeof resp == 'object') {
    var info = {};

    info.title = resp.title;
    info.description = resp.description;
    info.termsOfService = resp.termsOfServiceUrl;
    info.contact = {};
    info.contact.name = resp.contact;
    info.license = {};
    info.license.name = resp.license;
    info.license.url = resp.licenseUrl;

    return info;
  }
};
```

should be changed to

```
SwaggerClient.prototype.convertInfo = function (resp) {
  if(typeof resp === 'object') {
    var info = {};

    info.title = resp.title;
    info.description = resp.description;
    info.termsOfService = resp.termsOfServiceUrl;
    info.contact = {};
    info.contact.name = resp.contact;
    info.license = {};
    info.license.name = resp.license;
    info.license.url = resp.licenseUrl;

    return info;
  }
};
```

Basically, do the === instead of ==. I can add a pull request if needed.

**Comment by mohsen1** [comment]
Please checkout develop_2.0 branch and let me know if this problem persists there.

**Comment by wonderlic-chrisk** [comment]
I cannot NPM install on the develop_2.0 branch in it's current state. It blows up:

Failed at the swagger-ui@2.1.8-M1 postinstall script.
This is most likely a problem with the swagger-ui package,
not with npm itself.
Tell the author that this fails on your system:
    cd node_modules/swagger-client/; npm install; gulp
You can get their info via:
    npm owner ls swagger-ui
There is likely additional logging output above.
System Windows_NT 6.2.9200

**Comment by mohsen1** [comment]
please do this:

```
cd node_modules/swagger_client
gulp
```
make sure you have gulp

**Comment by wonderlic-chrisk** [comment]
@mohsen1, The develop branch does work. There were actually a few other issues that I ran into once I added the Info object to make my initial issue work. Do you know when the develop version will become the real version?

**Comment by fehguy** [comment]
I expect the convert info method in swagger ui won't be called at all now. This conversion should be happening in swagger js. Can you please verify with master of swagger ui?  We are releasing today after one oauth issue is addressed.

**Comment by wonderlic-chrisk** [comment]
@fehguy, the master version also appears to work.

**Comment by wonderlic-chrisk** [comment]
2.1.0-M2 works, so closing.
