### ISSUE TITLE
support relative URLs

### ISSUE THREAD

**Issue by psinghsp** [swagger-api/swagger-ui#1093]
Look at the discussion here.
https://github.com/swagger-api/swagger-spec/issues/318

According to Swagger 2.0 spec, I can split the APIs into multiple files. It works perfectly with Swagger 1.2 format. But if you use Swagger 2.0 format, Swagger UI does not work at all. Here is a simple example:
```
{
    "swagger": "2.0",
    "basePath": "/rest/json",
    "schemes": [
        "http",
        "https"
    ],
    "info": {
  
    },
    "paths": {
        "/time" : {
            "$ref" : "https://10.0.233.196/rest/json/apiDocs/timeApi.json"
        }
    }
}
```
Ideally, I would like "$ref" to be set to "timeApi.json" because it should be relative to the base document.

Again all this works with Swagger 1.2 way of splitting APIs.Swagger UI does not even make HTTP requests to load any of the referenced URLs.

Can it get fixed soon so that I can migrate to Swagger 2.0? Otherwise, I cannot use Swagger Editor or any of the other toolsets which are around.

**Comment by mohsen1** [comment]
swagger-js is resolving the $refs. Please open this ticket in swagger-js

**Comment by fehguy** [comment]
This support was added yesterday so please make sure you are getting the latest from develop_2.0

**Comment by psinghsp** [comment]
How stable is develop-2.0 branch?

**Comment by psinghsp** [comment]
Also, do relative urls work I.e. are refs resolved wrt to the url of the base document they are in?

**Comment by fehguy** [comment]
It'll be released to master today

**Comment by psinghsp** [comment]
I loaded it just now. It can now load the $ref URLs. It cannot however load "relative" URLs. I want to be able to write:
$ref: "timeApis.json"

and it should be able to resolve the relative URL according to Swagger 2.0 spec.

It does resolve it if it is absolute url like:
$ref: "http://1.1.1.1/myapis/timeApis.json"

Similarly, if I reference a schema in a new file, Swagger UI 2.0 cannot load it. I was able to do this very nicely in 1.2.

For example:
{
    "get" : {
       "responses": {
            "200": {
                    "schema": "#/models/CurrentTime"
            }
       }
     },
     "models" : {
           "CurrentTime" : {
                properties: {
                }
           }
     }

}

This technique works with Swagger 1.2 spec - but does not with swagger 2.0 spec. It allowed us to very nicely separate the schema definitions and API definitions of each resource in a separate file.

**Comment by fehguy** [comment]
I believe you need to prefix your ref:

```
$ref: "#/definitions/timeApis.json"
```

**Comment by fehguy** [comment]
@psinghsp I stand corrected.  It will *not* resolve relative to the URL that is serving the document.  You will have to provide a full path.

**Comment by psinghsp** [comment]
Yes. It does not. It is worse than that. All definitions have to be in the root document. That makes it pretty unusable for us because we have around 1200 schema definitions in separate files based on Swagger 1.2 format. Converting them  by copying all of them in a single document will be quite a bit of work. I guess we will wait till Swagger-UI stabilizes with full support for 2.0 spec.

**Comment by fehguy** [comment]
Help me understand.  You have been using swagger 1.2 and using the new (master) swagger-ui doesn't load the definitions correctly?  Even if across multiple files, it should resolve them.  Can you please share more info?

**Comment by psinghsp** [comment]
Swagger 2.0 UI works perfectly with our 1.2 specs. We were thinking of moving them to Swagger 2.0 specs and that is cause of the problem. So yes, we are using Swagger 2.0 UI - but just not Swagger 2.0 specifications.

**Comment by fehguy** [comment]
ok but under the hood, swagger-ui master converts the 1.x specs to 2.0.  So is the UI not working?

**Comment by psinghsp** [comment]
No - UI is working perfectly with 1.2 format API json files. But if I try to do the same thing by converting a subset of them to Swagger 2.0 JSON format, UI does not work (basically, it cannot resolve the schemas in local files). For example, in 1.2 format, in an API file, I can say the GET operation returns an object using "responseClass". This response class is defined locally in the file and Swagger UI loads it properly. But if I specify this in 2.0, I have to use "schema" keyword and "$ref". $ref to the schema definition in the local file does not work.

**Comment by psinghsp** [comment]
I do not know why Swagger-ui when converting 1.x specs to 2.0 works properly - but cannot do the same if written in 2.0 format.

**Comment by psinghsp** [comment]
I can provide examples if needed.

**Comment by fehguy** [comment]
If you want to see what swagger-js is constructing, please add a JSON.stringify(...) here:

https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L186

**Comment by javiervidal** [comment]
I'm hitting the same problem. I'm writing my swagger.json in 2.0 format from scratch and I would like to split the file in multiple json files. I've just pulled swagger-ui from master. 

If I write:

    "$ref":"http://localhost:3001/a.json"

it works and loads a.json, but it I try to use a relative URL it does not:

    "$ref":"a.json"

**Comment by soix** [comment]
I happen to meet @olensmar at APICraft NY meetup and discussed this. He mentioned relative includes should work and asked to enter an issue. I found this issue and don't want to create a duplicate one. Looking forward for this to be supported in the swagger-ui/editor and codegen.

**Comment by fehguy** [comment]
I will open a ticket in swagger-js for this.  It's not a UI issue.

**Comment by fehguy** [comment]
see here:  https://github.com/swagger-api/swagger-js/issues/417

**Comment by reuzel** [comment]
Hi,

Question: I see this Issue, as well as the issue 417 on swagger.js marked as closed. But it still does not seem to work for me. Am I doing something wrong? Am I missing some configurations?

The API shows, but the reference is not resolved. It displays an empty model for the reference:

```
Dog {
name (string, optional),
owner (people.yml#/Owner, optional)
}

people.yml#/Owner {
}
```

The following test files were used to get to this result. These three yml files are placed in the root of the swagger-ui directory. Swagger-ui is loaded via http://localhost/swagger/. I've updated index.html accordingly.

dog.yml is the API entry point and contains:
```yaml
swagger: '2.0'

info:
  version: '1'
  title: Reference check

basePath: /api

definitions:
  Dog:
    title: "Dog"
    properties:
      name:
        type: string
      owner:
        $ref: 'people.yml#/Owner'
        
paths:
  /Dogs:
    get:
      summary: Gets an 'A'
      parameters:
        - name: name
          in: query
          type: string
      responses:
        200:
          description: The Component resource was updated.
          schema:
            $ref: '#/definitions/Dog'

```

people.yml contains:
```yaml
Owner:
  title: "A Dog owner"
  properties:
    person:
      $ref: "#/Person"
    since:
      type: string
      format: date-time
      
Person:
  title: "Somebody"
  properties:
    name: 
      type: string
    address:
      $ref: 'address.yml'
```

and finally address.yml contains:
```yaml
Address:
  title: An address
  properties:
    street:
      type: string
    number:
      type: int
```

What do I need to do to make this work? I've tried this with the latest develop_20 version (using the dist folder contents)

**Comment by webron** [comment]
Can you open a separate issue instead with the details you provided?
