### ISSUE TITLE
API Filtering

### ISSUE THREAD

**Issue by Flamenco** [swagger-api/swagger-ui#1096]
I have implemented a sweet filter widget.  I await your input and open this up to discussion before proceeding.

What are your thoughts on where this filtering should occur:
1.  On the server via API
2. On the client in javascript

![screen shot 2015-03-29 at 7 09 16 am](https://cloud.githubusercontent.com/assets/819940/6885196/c0121d12-d5e2-11e4-8b94-1a8565133ea9.png)

**Comment by webron** [comment]
First, this is a cool idea and thanks for sharing it with us.

Client vs Server filtering serve a different purpose. Client filtering can be used for convenience, especially when there's a large set of operations available. Server filtering is mostly used for security, to hide operations that should not be exposed to the requesting user.

**Comment by Flamenco** [comment]
My use case is an API that has over 300 items with verbose notes, and I want to quickly go to an entry.  The server approach will be better for performance along with the mentioned security.

Does the current core allow a filtering parameter?  I would prefer to go that route.

**Comment by webron** [comment]
Yes, it does - https://github.com/swagger-api/swagger-core/tree/develop_2.0/modules/swagger-core/src/main/java/com/wordnik/swagger/core/filter.

**Comment by Flamenco** [comment]
That's really nice.  Is there access to the filter via a query string when requesting the spec?

**Comment by webron** [comment]
That's a question for swagger-core :)

**Comment by Flamenco** [comment]
I'm trying to decide on whether or not this filter will refresh using a query string, an ajax call, or just pull down the whole lot and do it in Javascript; That's why I am asking here ;)

**Comment by stefanmeschke** [comment]
Hi Flamenco, nice work! We are searching for this a while. Could you please provide us an example page? :)

**Comment by herberzt** [comment]
I am interested in this as well. I am currently trying to implement a search bar that as you start typing it hides all the paths or methods that don't contain the word that you are typing in. The keyword could correspond to anything from the path name, to the type of method, an emun for a param etc.

**Comment by Flamenco** [comment]
We came to the conclusion that the filtering should be done in the client.  Since the client receives the entire JSON API, it made the most sense to distribute the load off the server to address speed and bandwidth issues.

We wrote our solution in Java and compiled using GWT to Javascript, bypassing the entire swagger ui and using an in-house implementation. Our current solution is not really compatible with the swagger codebase.

**Comment by mgttlinger** [comment]
I have quickly implemented this functionality in jQuery:

    this.apiSearchKeyPressed = function() {
        var pattern, searchterm;
        searchterm = $('#apiSearch').val();
        pattern = new RegExp(searchterm, 'i');
        $('.operation').each(function(i, op) {
          var opDescription, opID, opSummary;
          opID = $(op).prop('id');
          opSummary = $(op).find('a.toggleOperation').text();
          opDescription = $(op).find('.markdown p').text();
          if ((pattern.test(opID)) || (pattern.test(opSummary)) || (pattern.test(opDescription))) {
            return $(op).show();
          } else {
            return $(op).hide();
          }
        });
        return hideEmptyResources();
      };
    
      this.hideEmptyResources = function() {
        return $('.resource').each(function(i, res) {
          var visibleChildren;
          visibleChildren = $(res).find('.operation').filter(function(ii, op) {
            return $(op).css('display') !== 'none';
          });
          if (visibleChildren.size() <= 0) {
            return $(res).hide();
          } else {
            return $(res).show();
          }
        });
    };

I attach the call of the `apiSearchKeyUp` function to the `onkeyup` event of an input element with the id `apiSearch`. I dont think this code is great (mainly due to the fact that I am not a JavaScript dev) but perhaps this can be worked into swagger UI/JS. Maybe you could even search in the swagger object instead of its HTML representation, but I lack the insight into the inner workings of swagger to see if this is a viable alternative.

**Comment by mvindahl** [comment]
I'd like filtering as well since our team works with some pretty large APIs and scrolling up and down is a bit of a pain. Obviously it should be client side. I'd prefer to keep the UI simple, i.e. just a textbox at the top. As you type, it will immediately expand the APIs with matches and it will hide everything else. Maybe even highlight the matched string. I'd say that matching on the URL string and the description of a method would be all that we need.

If you like the idea, I could try to give it a shot and do a PR.

**Comment by webron** [comment]
@mvindahl - it's slightly different than what the OP is about, but it's a nice idea. Perhaps if it's an optional filter (configuration toggle) it would work best.

**Comment by mvindahl** [comment]
Brill. And a good idea to make it opt-in through the config settings. I'll see what I can cook up.

**Comment by fehguy** [comment]
Thanks @mvindahl.  I'm going to close this out, and if you have a generalized filtering solution, let's make it dynamic in the swagger-ui javascript.
