### ISSUE TITLE
Api Key example on documents should be updated to cater for updated Apache

### ISSUE THREAD

**Issue by codemonkeyneo** [swagger-api/swagger-ui#1099]
Hi All,

I had a problem when testing swagger ui and using it with my setup on apache 2.4. The example documentation shows you using an api key 'api_key' under the header parameters section

```
// add a new SwaggerClient.ApiKeyAuthorization when the api-key changes in the ui.
$('#input_apiKey').change(function() {
  var key = $('#input_apiKey')[0].value;
  if(key && key.trim() != "") {
    swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("api_key", key, "header"));
  }
})

```
The "api_key" header should be "api-key" as later apache versions drop invalid header names that contain underscores. The 'api-key' value here will pass through and on the server side be named 'api_key'.
```
```
Here is reference for anyone http://httpd.apache.org/docs/trunk/new_features_2_4.html

> "mod_cgi, mod_include, mod_isapi, ... Translation of headers to environment variables is more strict than before to mitigate some possible cross-site-scripting attacks via header injection. Headers containing invalid characters (including underscores) are now silently dropped. Environment Variables in Apache has some pointers on how to work around broken legacy clients which require such headers. (This affects all modules which use these environment variables.)"

Hope this helps someone and please update documentation , unless there is a better way.

Cheers

Neil

**Comment by webron** [comment]
After some research, technically, underscores are not really forbidden in header names but are not supported by some web servers (in one way or another). Based on the HTTP RFC, they are perfectly legal. Not saying we shouldn't change the default behavior to accommodate a wider range of servers by default, but it's definitely not invalid.

**Comment by fehguy** [comment]
this is an implementation issue, not swagger issue.
