### ISSUE TITLE
Enum schemes render strange when referenced instead of inlined

### ISSUE THREAD

**Issue by mgttlinger** [swagger-api/swagger-ui#1100]
When an enum schema is defined and used by reference it will be rendered in Model as
![image](https://cloud.githubusercontent.com/assets/5120487/6891656/7f38ea9c-d6bd-11e4-9d3d-c00ed99c5116.png)
```
"ApplicationConfigPatch" : {
  "type" : "object",
  "properties" : {
    "variantManagement" : {
      "$ref" : "#/definitions/OperationalState"
    }
  }
},
"OperationalState" : {
  "type" : "string",
  "enum" : [
    "Enabled",
    "Disabled"
  ]
}
```
instead of desired look
![image](https://cloud.githubusercontent.com/assets/5120487/6891686/b4e3b0be-d6bd-11e4-9fc9-0e7765d5b08c.png)
```
"ApplicationConfigPatch" : {
  "type" : "object",
  "properties" : {
    "variantManagement" : {
      "type" : "string",
      "enum" : [
        "Enabled",
        "Disabled"
      ]
    }
  }
}
```

This behavior should at least be noted in the documentation as every other schema does only work by reference (which also does not get mentioned in the documentation).

**Comment by fehguy** [comment]
I don't think your first JSON example is valid.  Please take a look at how entries in the `definitions` section are defined in the swagger spec:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#definitions-object

**Comment by webron** [comment]
@fehguy - I don't see a problem with the first JSON example. Looks valid to me.

**Comment by fehguy** [comment]
@webron the definition for `OperationState` doesn't look valid to me.  There are no properties and I don't think `enum` is supported at top-level.  Am I wrong?

**Comment by webron** [comment]
It doesn't have to contain properties. Since body parameters can be primitives as well, `definitions` can contain primitive definitions including validation constraints such as `enum`. So while an uncommon use case, the definition itself is valid.

**Comment by fehguy** [comment]
OK got it, I stand corrected.  This should really be file against swagger-js though.

**Comment by webron** [comment]
Opened an issue on swagger-js.

**Comment by fehguy** [comment]
This should be fixed now from swagger-js.
