### ISSUE TITLE
Global "produces" and "consumes" not working properly

### ISSUE THREAD

**Issue by mgttlinger** [swagger-api/swagger-ui#1102]
The following spec

```
"/license/{type}" : {
  "put" : {
    "tags" : [
      "license"
    ],
    "summary" : "Uploads license if it's valid",
    "description" : "",
    "parameters" : [
      {
        "name" : "type",
        "in" : "path",
        "decription" : "the type of the license to upload",
        "required" : true,
        "type" : "string",
        "format" : null,
        "enum" : [
           "TestBenchBase",
           "DefectManagement",
           "RequirementsManagement",
           "API",
           "VariantManagement"
         ]
      },
      {
         "name" : "body",
         "in" : "body",
         "decription" : "The license to upload",
         "required" : true,
         "schema" : {
            "$ref" : "#/definitions/LicenseKey"
         }
      }
    ],
    "responses" : {
         ...
    }
  }
}
```
with
```
  "produces" : [
    "application/xml; charset=utf-8"
  ],
  "consumes" : [
    "application/xml; charset=utf-8"
  ]
```
defined globaly produces:
![image](https://cloud.githubusercontent.com/assets/5120487/6900124/bf1c6782-d704-11e4-9331-210513162c18.png)

I would expect both of the content type dropdowns to be set to `application/xml; charset=utf-8`, wich works when set in the Operation object.

**Comment by webron** [comment]
Which version of swagger-ui do you use? This is related to https://github.com/swagger-api/swagger-js/issues/138 which should have been fixed.

**Comment by mgttlinger** [comment]
@webron I pulled from master today so v2.1.0-M2

**Comment by webron** [comment]
Okay, thanks for checking.

**Comment by DDetlefsen** [comment]
I am having the same issue but my API is expecting JSON, not XML.
So I'm having basically the same issue. Not sure if its worth riding the coat tales of this issue or creating a new one.

 "produces" : [
    "application/xml; charset=utf-8"
  ],
  "consumes" : [
    "application/xml; charset=utf-8"
  ]

**Comment by fehguy** [comment]
I've added this to track:
https://github.com/swagger-api/swagger-js/issues/367
