### ISSUE TITLE
port hard coded making request fail

### ISSUE THREAD

**Issue by schengcrouchingtiger** [swagger-api/swagger-ui#1103]
I was using swagger-ui from swagger-node-express. 

then I found this is hard-coded;

      if (url && url.length > 1) {
        url = url[1];
      } else {
        url = "http://localhost:8002/api-docs.json";
      }

the port is hard-coded.

it is different  from the actual port, making the request fail.

**Comment by fehguy** [comment]
I suggest grabbing master from the [swagger-ui](https://github.com/swagger-api/swagger-ui) repo

**Comment by webron** [comment]
@schengcrouchingtiger - did you get a chance to retest it?

**Comment by fehguy** [comment]
Please reopen if still an issue.
