### ISSUE TITLE
Use an inline models title when available

### ISSUE THREAD

**Issue by hamx0r** [swagger-api/swagger-ui#1104]
## Summary
Make use of `title` if present in any schema definition, otherwise use current labeling logic

## Details
Per the [Swagger Spec's section on Schema Objects](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object), the `title` JSON Reference is supported.  When defining any inline Object in a Response Schema, the UI shows **Inline Model** instead of a models name _unless_ it uses `$ref`.

For example, one sees this:
![image](https://cloud.githubusercontent.com/assets/423974/6923098/9951f9c4-d784-11e4-9771-67a6b40276d6.png)

...with this inline schema (notice use of `title`)

    '200': {"description": "UT Software Versions",
        "schema": {
            "title": "SW Ver",
            "properties": {
                "asic": {"type": "array", "items": {"type": "string"}},
                "fpga": {"type": "array", "items": {"type": "string"}},
                "pl1": {"type": "array", "items": {"type": "string"}},
                "pl2": {"type": "array", "items": {"type": "string"}},
                "pl3": {"type": "array", "items": {"type": "string"}}
            }
        }
    }

Yet we see this (notice model's name)
![image](https://cloud.githubusercontent.com/assets/423974/6923256/615675d0-d785-11e4-8893-3724ad23d57c.png)

...when using this `$ref`erenced schema (notice no `title` supplied):

    '200': {"description": "UT Software Versions",
        "schema": {
            "$ref": "#/definitions/SWVer"
        }
    ...
    'SWVer': {
        "properties": {
            "asic": {"type": "array", "items": {"type": "string"}},
            "fpga": {"type": "array", "items": {"type": "string"}},
            "pl1": {"type": "array", "items": {"type": "string"}},
            "pl2": {"type": "array", "items": {"type": "string"}},
            "pl3": {"type": "array", "items": {"type": "string"}}
        }
    }

This implies the referenced object's name is being used as the title here.  Perhaps this should only be done if no `title` is supplied.

Note that the above behavior is seen when a referenced definition has an inline Object definition within it.  Here's an example of a referenced "LDAPUpgrades" Object which itself has an array of Objects (Inline Model 1), and _that_ Object has a `property` ("arguments") which is an Object (Inline Model 2).   
![image](https://cloud.githubusercontent.com/assets/423974/6923461/ba515bb8-d786-11e4-93b2-d281ef4afe73.png)

This screenshot is generated from this schema in my `definitions` section which is then `$ref`erenced:

    '200': {"description": "LDAP Upgrades in Progress",
        "schema": {"$ref": "#/definitions/LDAPUpgrades"}
    }
    ...
    'LDAPUpgrades': {
        "required": ["ldap_upgrades"],
        "properties": {
            "ldap_upgrades": {
                "type": "array",
                "items": {
                        ...
                        "arguments": {"type": "object", "properties": {
                            ....
                            }
                        }
                    }
                }
            }
        }
    }

**Comment by whitlockjc** [comment]
I agree.  The reason we do what we do now is that for referenced models, the name can be inferred based on the reference but for inline models, no name can be inferred so we go with `Inline Model` or some generated version of that based on the number of inline models within a particular hierarchy of models.  I can see `title` being used instead of this generated label.  Let's see what @fehguy has to say.

**Comment by hamx0r** [comment]
Great!  Btw, i'm implementing a fix now and should have a pull request soon.  Not sure if i should make it to `swagger-ui.js` in swagger-ui or `models.js` in swagger-js

**Comment by whitlockjc** [comment]
This is a swagger-js issue.  _(Right now, swagger-js is used to generate this HTML for swagger-ui.)_  The title should be "Use an inline models title when available" or something to that effect.

**Comment by hamx0r** [comment]
Fixed per swagger-js pull #342

**Comment by dmyers** [comment]
@hamx0r Is there a way to add title support for referenced schemas? I have a title property on all of my schemas, but ones that are referenced are not using the title though.

![ss](https://cloud.githubusercontent.com/assets/207171/7842879/afca1a1a-046b-11e5-88b6-dc001e77d2ed.png)

![ss2](https://cloud.githubusercontent.com/assets/207171/7842921/ebb914e0-046b-11e5-98b8-a1b8795c715f.png)
