### ISSUE TITLE
2.1.0-M2 doesn't group swagger 1.2 apis anymore

### ISSUE THREAD

**Issue by ikitommi** [swagger-api/swagger-ui#1106]
all apis are flattened into a single group. coudn't find a official 1.2 online demo anymore to give a url to demonstrate this.

**Comment by fehguy** [comment]
Take a look at http://petstore.swagger.io/api/api-docs.  You'll see the same behavior as before.

**Comment by ikitommi** [comment]
thanks. found the root cause - the new version of swagger-ui really reads the `resourcePath` which we are not setting. Can fix this now.

**Comment by prat0318** [comment]
I also stumbled across this issue. Any particular reasons to use `resourcePath` isntead of resourceListing's `path` being used earlier?
