### ISSUE TITLE
Security Definitions- SwaggerUI

### ISSUE THREAD

**Issue by rajeshakt** [swagger-api/swagger-ui#1108]
Hi Team,

Iam unable to load the security definitions through swagger UI documentations.

Please let me know if i need to include any js file/ div classes.

Thanks,
Rajesh

**Comment by webron** [comment]
Not sure what you mean by that. What are you trying to do exactly, what do you expect to see and what do you actually see?

**Comment by rajeshakt** [comment]
Please find the attached screenshot for reference. Unable to find these when i explored through swagger UI.
![ss1](https://cloud.githubusercontent.com/assets/11755063/6942383/d2a46222-d8a4-11e4-92be-011ac0892a5a.PNG)

**Comment by webron** [comment]
That's because swagger-ui doesn't represent the security definitions that way, and is not intended to.

**Comment by rajeshakt** [comment]
what needs to be done to represent security definitions in SwaggerUI ?
 Do we need to incorporate any .js.

**Comment by webron** [comment]
Currently, there's no way to display that.

**Comment by rajeshakt** [comment]
we needed that urgently for documentation. Any help will be appreciated !

**Comment by mohsen1** [comment]
Basic auth is simply a header. SwaggerUI has an API for adding auth headers. See [here](https://github.com/swagger-api/swagger-ui#custom-header-parameters---for-basic-auth-etc) to learn about the API and [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basic_access_authentication) to learn about HTTP basic auth.

You can make a form somewhere in the UI to process username/passwords and set the auth header if you want

**Comment by rajeshakt** [comment]
My question is when the swagger editor can display, why swagger UI is not doing ?

This needs to be fixed, else how can we share the security information with the consumers?

What I feel is whatever the features are there in swaggereditor should be same in swaggerUI, whereas the later one is restricted to only for documentation/view.

Thanks,

**Comment by webron** [comment]
The editor and ui are two completely separate projects (for now). The UI does not show the security information right now, and there's no 'add-on' to add the display (though you can probably write one on your own). Basic authentication and OAuth2 can be easily integrated into the UI with no special display of the security specifically.

**Comment by shuisman** [comment]
+1
It would be very nice to include the security information in the swagger UI project. This information is very helpful when exploring the API.

**Comment by wesselkranenborg** [comment]
+1

**Comment by ximex** [comment]
:+1:

**Comment by Bazman** [comment]
+1

**Comment by ponelat** [comment]
I agree, most useful to know.
It would be nice if we didn't need to go into the index.html file to add authentication _AND_ to be able to view it of course :smile: ... anyone keen on creating a PR?

**Comment by anirban1c** [comment]
+1 I am hard coding the auth headers at the moment, would love to have this in

**Comment by palamccc** [comment]
+1 :smiley:

**Comment by alexvodovoz** [comment]
+1

**Comment by fela98** [comment]
+1

**Comment by astrodsg** [comment]
:+1:

**Comment by macrosak** [comment]
:+1:

**Comment by sitnikovme** [comment]
:+1:

**Comment by cnlpete** [comment]
:+1:

**Comment by bmulyawan** [comment]
+1

**Comment by jayonsoftware** [comment]
+1

**Comment by kailuowang** [comment]
:+1:

**Comment by nazarhussain** [comment]
+1

**Comment by tmurakam** [comment]
+1

**Comment by geoct826** [comment]
+1

**Comment by JimboABC** [comment]
+1

**Comment by b22n** [comment]
+1

**Comment by cabbonizio** [comment]
+1

**Comment by LBoraz** [comment]
+1 this feature is really needed. I don't see any reason for the Editor to display different information (less complete?) than the UI.

**Comment by nazarhussain** [comment]
The issue is open from last 6 months more than 25 +1. 

Is there any author of `swagger-ui` is reading it to reply those 25+ people.

**Comment by webron** [comment]
@nazarhussain I believe it's obvious that we're reading everything. Not really sure what sort of reply you expect.

**Comment by nazarhussain** [comment]
@webron Thanks for replying. I believe there would plenty of people waiting for this feature. Please suggest the community that does this feature is in your roadmap, if yes then what's the release plan. If no  then what alternative community should look for.

**Comment by webron** [comment]
Right now, on the near roadmap, we have plans to add tighter integration of the security with the UI (cannot give you an ETA). This is not exactly equivalent to this feature request, and I cannot guarantee it will be added as part of it.

In general, we don't publish the roadmap to our tools. Not because we're hiding it, we just don't really work that way. Priorities and resources change all the time, it being, after all, an open source project (or rather a large collection of projects).

It's definitely not my place to suggest alternatives.

**Comment by nazarhussain** [comment]
Thanks a lot a detail response. Now at least every one have insight on this issue and they can look for their alternative plans. 

Swagger alongs with its tools is really Awesome. I love it and will keep loving it.

**Comment by LBoraz** [comment]
for the moment the solution must be to add an "apikey" parameter to every request...

**Comment by rajeshakt** [comment]
resolved internally

**Comment by LBoraz** [comment]
care to share the solution?

**Comment by webron** [comment]
@rajeshakt - while you may have added this feature internally, this is still a very common public feature users want, so I'll reopen this until we resolve it (and we do plan on it).

**Comment by prusswan** [comment]
@LBoraz The current "solution" is use a single api key (the parameter name can be changed) just like the pets example, swagger-ui will just append it to all queries if the value is present. Each of the endpoints needs to indicate (e.g. in the description) whether the authentication parameter is required.

**Comment by grEvenX** [comment]
:+1:

**Comment by jgslima** [comment]
+1
Not sure if swagger team will concur, but maybe as a first step Swagger UI could simply display the information regarding the securityDefinitions element, pretty much how it is done by Editor. That is, simple HTML with no Javascript, only to be used as documentation to the reader.

Again, maybe swagger team philosophy is to only include features in Swagger UI that has Javascript execution support, however in some cases (like mine) we distribute a Swagger UI documentation to partners without the "Try it out" feature anyway, that is, we use Swagger UI as documentation only (which is prety useful).

**Comment by webron** [comment]
The good news is that we're in advanced stages of incorporating the security more tightly with the UI. The bad news is that there's no exact ETA, but it hopefully it shouldn't be long now.

**Comment by LBoraz** [comment]
fantastic

**Comment by thanhson1085** [comment]
+1 Do you have any news?

**Comment by fehguy** [comment]
in the testing phase...

**Comment by Joiningss** [comment]
+1

**Comment by fehguy** [comment]
See pull #2014 and please give feedback on that. There are a couple todos left

**Comment by ximex** [comment]
#2014 is merged

**Comment by ichpuchtli** [comment]
+1

**Comment by pawelprazak** [comment]
+1

**Comment by J4S0Nc** [comment]
+1

**Comment by my-flow** [comment]
+1

**Comment by sulliwane** [comment]
+1

**Comment by Starscream27** [comment]
+ 1

**Comment by ax003d** [comment]
+1

**Comment by merritts** [comment]
+1

**Comment by fehguy** [comment]
This is in the 2.1.5 release.

**Comment by neilyoung** [comment]
When will it be released?

**Comment by webron** [comment]
8 days ago.

**Comment by mnapoli** [comment]
With the latest release I cannot see anything different (with a Basic Auth documented), where is it supposed to display? Do you have any screenshot or link to the pull request?

**Comment by doooks** [comment]
I don't understand why displaying the security information for an API is out of scope. 

http://swagger.io/swagger-ui/ says that Swagger UI is to "dynamically generate beautiful documentation" - why would the API's security mechanism be excluded from the visible documentation? You need that information to write an API client, you might not be using the auto-generated code.

Does anyone have a fork or a PR that renders the security infomation? Otherwise, if I work on a PR would someone on the project team consider that feature?

**Comment by webron** [comment]
@doooks - in general, we love getting PRs that push the project forward, but right now we're focused on a major update to the project and it's probably not the best time to submit such a PR specifically.

**Comment by bcfreitas** [comment]
+1

**Comment by vladkras** [comment]
+1
I had to move apikey to one of required parameters because of this

**Comment by iongion** [comment]
@vladkras amen!

**Comment by leonluocheng** [comment]
+1
I would like to see we have security feature integrated with the swagger UI

**Comment by webron** [comment]
@leonluocheng hmm? the security definitions are displayed in the current version.

**Comment by leonluocheng** [comment]
@webron  I am using swashbuckle.core 5.5.3, maybe that causes this issue. but the swagger generated UI did not display the basic authentication that I specified in app configuration. 

Example:
c.BasicAuth("basic").Description("Basic HTTP Authentication over TLS");

![image](https://cloud.githubusercontent.com/assets/8879694/26411892/b259a7fc-406c-11e7-99e9-86debf27ac1a.png)

**Comment by webron** [comment]
That's a very old version of the UI. Use the latest one and you should be good.

**Comment by Pratyushm91** [comment]
Hi,

I went through the complete thread. I also require to display the basic auth security field for setting client id and secret. And with the new swagger it looks really cool. Kindly let me know if any module available which can render my json file to similar swagger ui format. I already used swagger ui formatter but it is not displaying me the security field.

Thanks.

**Comment by dFarkhod** [comment]
+

**Comment by Farzanehsedarati610** [comment]
hi i need to reauthorize myself on https://doc.people-doc.com/api/?urls.primaryName=Client and its lead me here any assistance?
