### ISSUE TITLE
(Swagger 2.1) GET request with response type of text/plain stopped working

### ISSUE THREAD

**Issue by barneaoren** [swagger-api/swagger-ui#1109]
What that worked for me up until the latest version of swagger, have stopped working since I have recently updated to swagger 2.1.

Here is the API definition...
![swagger_json](https://cloud.githubusercontent.com/assets/11270701/6943064/4442240c-d894-11e4-8200-bccce0260a44.png)

Here is what I see via the chrome monitoring sidebar once executing the API
![in_action](https://cloud.githubusercontent.com/assets/11270701/6943071/492ea850-d894-11e4-877c-34080d182148.png)

Note that in the previous release (2.0) it worked fine & that by performing the GET directly via web access or using REST client (i.e. postman) - the response is being presented perfectly.

Also, I'm changing the server to set the return content-type to application/json - it works ok...

What am I missing here?

Thanks in advance,
Oren

**Comment by webron** [comment]
Can you share a full spec (in text) so we can test it?

**Comment by barneaoren** [comment]
Swagger UI Version	    2.1.0-M2	
Release Date	   2015-03-28	
Swagger Spec compatibility	  1.1, 1.2, 2.0	

downloaded this morning from https://github.com/swagger-api/swagger-ui

**Comment by webron** [comment]
Sorry, I meant the Swagger definition you load in the UI that produces that error.

**Comment by barneaoren** [comment]
Actually.. just take any GET API with no parameters,  empty consumes list and only 1 produces option (text/plain).
You will also need a server that will return a valid response to this kind of GET request...
My server is local so you unfortunatelly I cant share it.

my response hadler looks like this.:

@GET
@PATH ("")
Response answerWithText () {
   ResponseBuilder builder = Response.ok ();
   builder.type ("text/plain");
   builder.entity ("some text here");
   AddOriginHeaders (builder);
   return builder.build ();
}
