### ISSUE TITLE
Swagger-UI: not respecting content-type for DELETE

### ISSUE THREAD

**Issue by psinghsp** [swagger-api/swagger-ui#1111]
I have Swagger 1.2 spec - part of which looks like this. Swagger-UI insists on setting the content-type header to "application/json" when DELETE operation is performed on an id. This causes our server to choke because it ends up parsing an empty string as JSON. How do I tell Swagger-UI to set the content-type to "text/html". I set the tag: "consumes: [text/html]" - but that did not have any effect.
```json
                {
                    "httpMethod": "DELETE",
                    "summary": "Delete a tunnel by id (name)",
                    "nickname": "tunnelsByIdDelete",
                    "responseClass": "void",
                    "produces": ["text/html"],
                    "parameters": [
                        {
                            "name": "id",
                            "description": "Name of the tunnel to be deleted",
                            "paramType": "path",
                            "required": true,
                            "dataType" : "string"
                        }
                    ]
                }
```

**Comment by webron** [comment]
That's actually a 1.1 spec, and may be related to #1109.

**Comment by mohsen1** [comment]
e666485 fixed this. Please try with latest from develop_2.0 branch and let me know if it's not working
