### ISSUE TITLE
Parameters with enum and required produces wired output

### ISSUE THREAD

**Issue by beatjoerg** [swagger-api/swagger-ui#1113]
If a parameter is set to enum and also required, the output is wrong (param name listed twice)

![image](https://cloud.githubusercontent.com/assets/19165/6961020/bf076dda-d927-11e4-9119-44c8251c32d5.png)

                "parameters": [
                    {
                        "name": "prg",
                        "in": "path",
                        "description": "Programm",
                        "required": true,
                        "type": "string",
                        "enum": ["rsj","rsp"]
                    },
                    {
                        "name": "lang",
                        "in": "path",
                        "description": "Language",
                        "type": "string",
                        "enum": ["de","fr","it","en"]
                    }
                ],

**Comment by beatjoerg** [comment]
Just cloned today from master:

/**
 * swagger-ui - Swagger UI is a dependency-free collection of HTML, JavaScript, and CSS assets that dynamically generate beautiful documentation from a Swagger-compliant API
 * @version v2.1.0-M2
 * @link http://swagger.io
 * @license Apache 2.0
 */

**Comment by irhabi** [comment]
+1

**Comment by freak4pc** [comment]
Happening for me as well, cloned from master

```
"parameters": [
                    {
                        "name": "gender",
                        "in": "formData",
                        "description": "Gender of the user",
                        "required": true,
                        "type": "string",
                        "enum": ["m", "f"]
                    }
                ],
```

![image](https://cloud.githubusercontent.com/assets/605076/7177902/3b177dfa-e433-11e4-843f-1268f31054b3.png)

**Comment by mgttlinger** [comment]
Created a pull request for this issue [#1180](https://github.com/swagger-api/swagger-ui/pull/1180)

**Comment by swarupe04** [comment]
Hi. May I know which version/tag should i use to get this fix

**Comment by webron** [comment]
Fixed in develop_2.0. 

@swarupe04 - currently there's no official version with it, but if you need it you can check out the develop_2.0 branch and use that.
