### ISSUE TITLE
is there any way to display only specific API in swagger ui ?

### ISSUE THREAD

**Issue by hashad** [swagger-api/swagger-ui#1114]
Hi,

I'm new to swagger, but I have implemented swagger ui in my project which is using java and spring mvc, and I'm getting all the API I have in project under it and everything is working fine. 
But I want only specific APIs to be shown under swagger ui. Is there any way to do so ?

Currently even if I don't add any swagger annotations for new APIs which I'm developing for my project, as the swagger is already implemented it automatically displays all new APIs under swagger ui. I need to avoid it. Please let me know if there is any way to do so. Thanks in advance.

Regards,
Harshad

**Comment by webron** [comment]
@hashad - since you're using spring-mvc, I assume you use swagger-springmvc/springfox. As far as I know, they have then own methods of filtering APIs and you should check with their documentation or ask a question directly on their repository.

**Comment by hashad** [comment]
Sure, Thank you webron for prompt reply, much appreciated.
