### ISSUE TITLE
Bower version is wrong

### ISSUE THREAD

**Issue by tlbdk** [swagger-api/swagger-ui#1116]
bower swagger-ui#2.1.0-M2     mismatch Version declared in the json (2.1.8-M1) is different than the resolved one (2.1.0-M2)

**Comment by tlbdk** [comment]
Since 2.1.8-M1 was used the develop-2.0 branch and we are on 2.1.0-M2 in stable and 2.1.0-M2 is actually newer code than 2.1.8-M1, it's a bit of a mess with bower. Maybe it would be good for the next release to be 2.1.9-M3 to fix the version issues.

**Comment by todd-richmond** [comment]
going backwards in versions also causes havoc with "mvn versions:display-dependency-updates". It is best to always increase version dot.dot #s regardless of the -M? extension

**Comment by fehguy** [comment]
Thanks and yes.  We will bump versions so the major/minor/build are increasing.
