### ISSUE TITLE
GET request of application/yaml does not display response

### ISSUE THREAD

**Issue by TomDataworks** [swagger-api/swagger-ui#1123]
A GET request of application/yaml will never display a response, when it behaves properly in the Postman client as well as curl. I believe the issue to be related to another issue where getting a message with text/plain fails. https://github.com/swagger-api/swagger-ui/issues/1109

I used FireBug to determine the cause of the error, and it was a null pointer in the header checks for content-disposition and content-description.

Pull request for the fix at: https://github.com/swagger-api/swagger-ui/pull/1122

**Comment by fehguy** [comment]
The PR has been merged, can you please retest and reopen this if still an issue?
