### ISSUE TITLE
Sending multi-part-formdata 

### ISSUE THREAD

**Issue by mayuranchalia** [swagger-api/swagger-ui#1126]
I have a use case where a jersey rest service accepts multiple complex object as `@FormDataParam`.
Below is the code snippet
```java
	@POST
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.MULTIPART_FORM_DATA)
	@ApiOperation(value="setx")
	public Bean setBean(@FormDataParam("beanx")Bean bn1,@FormDataParam("beany")Bean bn2){
		return bn2;
	}
```
I am able to successfully call this service from Jersey client.
Below is the client snippet
```java
final FormDataMultiPart mp = new FormDataMultiPart();
        mp.bodyPart(new FormDataBodyPart(FormDataContentDisposition.name("beanx").build(),
        		bean1,
                MediaType.APPLICATION_JSON_TYPE));
        mp.bodyPart(new FormDataBodyPart(FormDataContentDisposition.name("beany").build(),
        		bean2,
                MediaType.APPLICATION_JSON_TYPE));

        Bean response=webTarget.request().accept(MediaType.APPLICATION_JSON).post(Entity.entity(mp, MediaType.MULTIPART_FORM_DATA_TYPE), Bean.class);
```
##########################################################################
I intercepted the request generated by the client...which is
```
POST /JeresyTestMultipart/rest/servicex HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=Boundary_1_602703068_1428318465523
User-Agent: Jersey/2.1 (HttpUrlConnection 1.7.0_09)
MIME-Version: 1.0
Host: 10.192.163.50:1234
Connection: keep-alive
Content-Length: 378

--Boundary_1_602703068_1428318465523
Content-Type: application/json
Content-Disposition: form-data; filename="beanx"; name="beanx"

{"name":"Paul","value":"Nibin"}
--Boundary_1_602703068_1428318465523
Content-Type: application/json
Content-Disposition: form-data; filename="beany"; name="beany"

{"name":"Mayur","value":"Jain"}
--Boundary_1_602703068_1428318465523--
```

and I am able to get the response successfully.

Now the issue is how to call the this service from swagger UI, I see the the swagger doc is generated and its taking two formData parameter and Model is also present...but the swagger UI is not able to invoke the service , I am getting error code 415.

Please help me with this issue so that I can post multiple complex object from Swagger UI.

**Comment by webron** [comment]
What's the Swagger definition you get from your code?

Strictly speaking, at the moment, Swagger does not support the structure you want to expose. You *can* say your operation accepts several files, but you *cannot* say that these files are of specific type or structure. With the current version of the spec, you also can't have complex data type as form parameters.

**Comment by mayuranchalia** [comment]
{
apiVersion: "1.0.2",
swaggerVersion: "1.2",
basePath: "http://localhost:8080/JeresyTestMultipart/rest",
resourcePath: "/servicex",
apis: [
{
path: "/servicex",
operations: [
{
method: "POST",
summary: "setx",
notes: "",
type: "Bean",
nickname: "setBean",
produces: [
"application/json"
],
consumes: [
"multipart/form-data"
],
parameters: [
{
name: "beanx",
required: false,
type: "Bean",
paramType: "query",
allowMultiple: false
},
{
name: "beany",
required: false,
type: "Bean",
paramType: "query",
allowMultiple: false
}
]
}
]
},
{
path: "/servicex/getx",
operations: [
{
method: "GET",
summary: "getx",
notes: "",
type: "Bean",
nickname: "getBean",
produces: [
"application/json"
],
parameters: [ ]
}
]
}
],
models: {
Bean: {
id: "Bean",
properties: {
name: {
type: "string"
},
value: {
type: "string"
}
}
}
}
}

**Comment by webron** [comment]
That's an invalid definition, but more of a question to swagger-core (I assume you use the wrong dependency). In any case, what you're trying to describe isn't supported by Swagger right now (there are plans to change it in a future version).

**Comment by mayuranchalia** [comment]
I din't get wrong dependency for swagger-core?

**Comment by webron** [comment]
Modifying comments makes it difficult to provide proper support. The original definition you posted was invalid. In any case, what you're trying to do is not supported.

**Comment by mayuranchalia** [comment]
So ,Ron
In future versions of swagger is there plan to support multiple complex objects to be posted as mutipart request.

**Comment by webron** [comment]
There's this issue - https://github.com/swagger-api/swagger-spec/issues/222. I can't comment on whether or not that's going to be included in a future version of the spec.

**Comment by webron** [comment]
Closing as not supported.
