### ISSUE TITLE
consumes application/json - content type as text/plain when post body empty

### ISSUE THREAD

**Issue by swarupe04** [swagger-api/swagger-ui#1131]
our resource api has:
 @Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)

in "try it out" feature, when i use post body as empty, it's sending content type as text/plain instead of application/json, which is causing our api server to raise 415 unsupported media type.

If i set the  post body in swagger ui as empty braces {}, it sends the content type as application/json.

parameter content type does show as application/json in ui page, which indicates swagger core end seems fine.

**Comment by fehguy** [comment]
please track here:

https://github.com/swagger-api/swagger-js/issues/326
