### ISSUE TITLE
JS error when testing uploadFile method (http://petstore.swagger.io/#!/pet/uploadFile)

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-ui#1132]
When testing the uploadFile method (http://petstore.swagger.io/#!/pet/uploadFile) in Swagger-UI, I only provided the required field: petId set to 5, clicked "Try it out" but didn't get any response. 

Found JS error in the console:

![screen shot 2015-04-09 at 2 24 01 pm](https://cloud.githubusercontent.com/assets/934260/7061428/5aa05b98-dec4-11e4-8106-dca727d59b5e.png)

**Comment by xhh** [comment]
I got a similar error when I tried it with all fields filled and file selected:

```
Uncaught TypeError: window.authorizations.apply is not a function
    SwaggerUi.Views.OperationView.Backbone.View.extend.handleFileUpload @ index.js:24
    SwaggerUi.Views.OperationView.Backbone.View.extend.submitOperation @ index.js:24
    p.event.dispatch @ jquery-1.8.0.min.js:2
    g.handle.h
```

btw, no request is sent at all, I guess the js error prevents it

**Comment by fehguy** [comment]
@mohsen1 can you please look at this regression?

**Comment by mohsen1** [comment]
53966f7 fixed this. We're using jQuery for file upload which should change. For that #1164 is filed
