### ISSUE TITLE
Swagger/Swashbuckle OAuth2 Authorizations not set

### ISSUE THREAD

**Issue by danutzplusplus** [swagger-api/swagger-ui#1134]
I've found an issue and I'm not sure where it stems from. The point where it fails in inside a Swagger js library (swagger-ui-js), but it might either because of a misconfiguration in Swashbuckle, or an actual bug in Swagger (version: v2.1.0-M2).

The issue I found was after upgrading Swashbuckle from 4.x to 5 (in 4.x it worked without a hitch), and it manifests in the following way:
I've a couple of WebAPI services exposed using Swashbuckle, and I've configured them (just the same as I've configured 4.x) to use a local OAuth2 token issuer. I hit the [On/Off] button on a particular service, and start the OAuth2 requests, finalizing with the access_token stored locally in swagger (the [On/Off] button is [On], meaning authentication succeeded). 

When I attempt to perform the actual call to the WebAPI service, it breaks locally in the javascript code, in swagger-ui-js, at line nr 900, at the point where it tries to call apply(obj, authorizations) on the reference retrieved from this.authz["oauth2"]

result = value.apply(obj, authorizations); // it breaks here because value is an empty js object, and apply is undefined

I've uploaded a screenshot of the firefox debugger: http://oi61.tinypic.com/2q1wk6e.jpg

I've traced where this.authz[key] is set, and its in the 
SwaggerAuthorizations.prototype.add = function (name, auth) {
  this.authz[name] = auth;

  return auth;
};

I've then traced it, at least I hope I traced it correctly, to:
window.swaggerUi.api.clientAuthorizations.add.apply(window.swaggerUi.api.clientAuthorizations, arguments);
and I noticed arguments is an array, and the "oauth2" key has an empty js object, but I've not been able to find out where that arguments object is populated from.

Anyone else had this issue? Could this be just because of a misconfiguration server-side on my part? I would imagine if this was the case, the OAuth2 flow would break a lot sooner than when trying to perform the actual request with the received bearer token.

Thanks, and I hope someone is able to shed some light on this, and I'm stumped.

**Comment by webron** [comment]
@danutzplusplus - can you share the Swagger definition you get from Swashbuckle? That would help us debug the problem.

**Comment by danutzplusplus** [comment]
Hmm, I'm not sure I understand what you mean by Swagger definition. I've deployed Swashbuckle as a nuget package, and only got the dll. I supposed the dll has the static Swagger js/html? I did download the source code of Swashbuckle from github, but there were no Swagger files, just some SwaggerUI custom assets (discoveryUrlSelector.js, swagger-oauth.js, index.html).

**Comment by webron** [comment]
Eventually, Swashbuckle produces a json file that swagger-ui reads and presents. I need that json.

**Comment by danutzplusplus** [comment]
Can you give me some hints as to how to find that? Should it be locally generated?

**Comment by webron** [comment]
It should be generated at runtime probably. You can open your browser's web console as you open the ui and see what it loads. It should be the input to the SwaggerUi object (the `url` parameter). I'm not sure where Swashbuckle hosts it.

**Comment by danutzplusplus** [comment]
Ok, i've uploaded 3 screenshots I took of the swagger/docs/1 configuration data. I hope this is what you were asking for.
http://oi60.tinypic.com/2zzufm1.jpg
http://oi59.tinypic.com/1539q4k.jpg
http://oi58.tinypic.com/2vmd6dk.jpg

Thanks

**Comment by webron** [comment]
It looks like it is, but I need the actual JSON. Screenshots are not going to help. I understand it may contain details you don't want to share publicly, but you can email them to me directly (email in profile) if that helps.

**Comment by danutzplusplus** [comment]
Can I send you the actual json, but with the values i'd like to keep hidden replaced with generic values?

**Comment by webron** [comment]
Sure, we can try that. I believe the structure would be more important.

**Comment by danutzplusplus** [comment]
I've just sent you an email with the attached json. I hope it helps. Thanks

**Comment by danutzplusplus** [comment]
I've debugged the new version of swagger which doesn't work, and the old one which does, and there indeed seems to be a problem with the call to call to window.authorizations.add(oauth2KeyName, new ApiKeyAuthorization('Authorization', 'Bearer ' + b, 'header'));

In the old version the function calls the ApiKeyAuthorization constructor, setting those 3 keys (auth_type,bearer_token,header), while in the new version it runs through 
window.ApiKeyAuthorization = function() {
    warn('window.ApiKeyAuthorization is deprecated. Please use SwaggerClient.ApiKeyAuthorization.');
    SwaggerClient.ApiKeyAuthorization.apply(window, arguments);
  };

And in the window.ApiKeyAuthorization the arguments is undefined, since those 3 parameters aren't picked up, since window.ApiKeyAuthorization has no parameters in its signature.

Also, in the old version that works, that value.apply which causes the crash in the new one(because value has no apply method set onto it) works perfectly. value has it's value taken from this.authz["oauth2"] which has the proper fields set (the auth type, the bearer token, and most importantly the apply method set on the json)

**Comment by webron** [comment]
@danutzplusplus - thanks for the investigation. apologies for not getting back to you on this.

**Comment by danutzplusplus** [comment]
Seems domaindrivendev on Swashbuckle is also able to reproduce this. 

@webron No worries. I'm just happy people are so nice in investigating this.

**Comment by firefoxNX** [comment]
@danutzplusplus @vprefournier I applied the code fix and I am not able to see the Header "Authorization Bearer <token>". Was there any other code change you had to do?

**Comment by firefoxNX** [comment]
Sorry. I have re-validated on my end and the fix works. Thanks @danutzplusplus @vprefournier

**Comment by webron** [comment]
@danutzplusplus - @vprefournier's PR has been merged to develop_2.0. Can you retest with that branch?

**Comment by danutzplusplus** [comment]
@webron Since I'm using Swagger indirectly, through Swashbuckle, I asked domaindrivendev, back on the swashbuckle issue to test the fix, and apparently he's having some issue with the merged codebase on develop_2.0, but the stand-alone fix seems to be ok.
https://github.com/domaindrivendev/Swashbuckle/issues/267#issuecomment-92473879

**Comment by webron** [comment]
Oh, he shouldn't use the develpo_2.0 branch code in Swashbuckle as that's development and may be unstable. That said, you can download it directly and point it to the Swagger definition Swashbuckle exposes to see if it actually resolves the issue.

**Comment by mohsen1** [comment]
4a81f4fa9fe0d8fa10f5d6e1d590e29a9cf958da should've fixed this. Can you confirm?

**Comment by vcorr** [comment]
Hello, what exactly is the status with this? Is still don't see the bearer header in the request, also tried develop_2.0 branch but no cigar - thanks

**Comment by webron** [comment]
@danutzplusplus - any updates?

**Comment by danutzplusplus** [comment]
Hi, sorry for the late reply. Yeah, last I talked with domaindrivendev he said that until the swagger branch is stable, he introduced your fix manually into Swashbuckle, and deployed a hotfix in nuget. And I'm guessing after your branch is stable he'll take it all in. 

So, your fix seems to work. Thanks. Sorry if I kept this issue from being updated.

**Comment by webron** [comment]
No worries, just glad it worked out.
