### ISSUE TITLE
Adding headers blocks my request, response body no content

### ISSUE THREAD

**Issue by mortias** [swagger-api/swagger-ui#1135]
Hello,

When i declare some header parameters and click the "try it out" button 
it first does an OPTIONS code 200 ok (preflight) with an empty response (body).. 
and doesn't continue to do the actual GET.. 

If i change the type to form then i get a json response back  (so there is no cors issue)
however my dataset is checking the header variables.. and not form variables.

Meaning is this a swagger bug ? why does it not continue with my GET request ?
do i still miss some cors config on option maybe?

tx

**Comment by webron** [comment]
Actually, it *is* a CORS issue.

One of the headers you need to enable in your web application is `Access-Control-Allow-Headers`, and that needs to have the names of the headers that you want to allow (as parameters).

For example, for the petstore sample, we have:
``Access-Control-Allow-Headers: Content-Type, api_key, Authorization``

Without that, the requests which contain those headers would fail.

**Comment by mortias** [comment]
so if i would like to allow another one like "language" or "ipaddress" then it should be 
Access-Control-Allow-Headers: Content-Type, api_key, Authorization, language, ipaddress?

**Comment by webron** [comment]
That is correct.

**Comment by mortias** [comment]
but how is it possible it works on postman then..? and not on swagger?

**Comment by webron** [comment]
It's a limitation of any browser-javascript based tool. Postman does not have those limitations.

**Comment by mortias** [comment]
cool! i hope this works.. searching on it for days :) and my ops is off for a coffee ..

**Comment by mortias** [comment]
Spot on!  I guess the "The name of these headers MUST be supported in your CORS configuration as well" wasn't ringing a bell for me :) https://github.com/swagger-api/swagger-ui/blob/master/README.md#cors-support
