### ISSUE TITLE
Get rid of wrapper classes in specs

### ISSUE THREAD

**Issue by mortias** [swagger-api/swagger-ui#1138]
Hello,

I've seen this issue before without any solution, the question is how to get rid of the wrapper classes in the documentation?

http://newscentral.exsees.com/item/9bc25e10eb8ccd2511a534f54dee4f82-54c0f9e69c3af3aaf136ef320a140da6
http://stackoverflow.com/questions/29115611/swagger-api-model-is-displaying-wrapper-classes

using swagger 1.3.2 specs
i see there is something like this: https://github.com/swagger-api/swagger-core/wiki/overriding-models#in-java-with-swagger-core-version-13x but i can't use it because i'm exporting it as json so i don't have a swagger config..  via https://github.com/kongchen/swagger-maven-plugin

maybe this is a solution.. ? http://devhel.org/how-to-handle-bigdecimals-in-swagger/

tx

**Comment by webron** [comment]
@mortias - these kind of questions belong to the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) if they are generic, or opened on the relevant project exposing the problem. It definitely doesn't belong in swagger-ui.

By following the simple guidelines, it would help us provide better support. Please follow the directions above for further assistance.

**Comment by mortias** [comment]
ok, sure nop !
