### ISSUE TITLE
[Swagger 2.0] Parameters defined at path level are not recognized

### ISSUE THREAD

**Issue by Maks3w** [swagger-api/swagger-ui#1146]
Swagger 2.0 allows to define common parameters at path level instead of define for each http method.

Swagger UI does not inherit the parameters and don't display the form.

**Comment by webron** [comment]
This is a duplicate of #911 and #929.

**Comment by gaillard** [comment]
I tried to use a path level parameter, which was a reference to one at the info level but it does not work. Having a operation level parameter that is a reference to one at the info level does though.

**Comment by webron** [comment]
@gaillard - if you can open a new issue with a (full) small sample definition to test, that would be great.
