### ISSUE TITLE
Download response (i.e. application/zip data) option only creates a link

### ISSUE THREAD

**Issue by barneaoren** [swagger-api/swagger-ui#1151]
current behaviour of the Swagger-UI, in case of content-disposition response, is to create a link to the UI, then the user must click it to start the download.
It is preferred that in such cases, the download will start automatically (by an initiative click event call).

currently, trying to manually add the code to the link click even call, results with 2 click events instead of only 1.
The routine is being called once for showErrorStatus and once for showCompleteStatus.

**Comment by fehguy** [comment]
Please retest, this should be fully supported now.
