### ISSUE TITLE
enum-parameters don't render dropdown anymore with 1.2

### ISSUE THREAD

**Issue by ikitommi** [swagger-api/swagger-ui#1153]
- ui: http://petstore.swagger.io/
- spec: http://petstore.swagger.io/api/api-docs
- in: #!/pet/findPetsByStatus

**Comment by webron** [comment]
@ponelat - Can you please verify this is fixed with your PR as well (or otherwise produce another PR for it/modify the enum PR)?

**Comment by ponelat** [comment]
@webron , @ikitommi 
I just checked with the latest develop_2.0, it seems to be working (renders enum as dropdown, with the spec given above)

**Comment by ponelat** [comment]
looks like tony solved this with swagger-api/swagger-js#376

**Comment by ikitommi** [comment]
great! we moved to 2.0, so not relevant any more. thanks!

**Comment by ponelat** [comment]
@webron this seems resolved.

**Comment by webron** [comment]
Fixed in develop_2.0.
