### ISSUE TITLE
ApiKey is not set when Explore button is clicked

### ISSUE THREAD

**Issue by Maks3w** [swagger-api/swagger-ui#1160]

**Comment by webron** [comment]
Thanks for submitting. Confirmed as a bug.

**Comment by mohsen1** [comment]
4a81f4fa9fe0d8fa10f5d6e1d590e29a9cf958da should've fixed this. Please comment if it's still not working for you

**Comment by Maks3w** [comment]
@mohsen1 There is now way to review the diff. May if you want to merge #1143 we could track future changes.

**Comment by mohsen1** [comment]
@Maks3w your changes in #1143 is good. Could you please make that PR to develop_2.0? That's the workflow here.

**Comment by Maks3w** [comment]
I don't know how to explain this. May the swagger team should take a look to a GIT tutorial.

I CAN'T OPEN A PR TO A BRANCH WHICH NOT HAVE A BUG.

This is, the gitattributes bug ONLY EXISTS ON MASTER

**Comment by Maks3w** [comment]
So this is not about how the contributor should open a PR. This is swagger team should follow the same rules which force the rest to follow.

Branches are unsynced because the repo managers don't follow the same flow.

**Comment by fehguy** [comment]
@Maks3w let's not get into a pissing match.  The flow as it stands is that you need PRs to go into develop_2.0.

Branches are synced.
