### ISSUE TITLE
Multiple SwaggerUi instances not rendering correctly

### ISSUE THREAD

**Issue by pkcinna** [swagger-api/swagger-ui#1161]
SwaggerUi clients (v2.1.0-M2) allow setting the dom_id but the nested template for resources_container is an id instead of a class and all the resources for each swagger client get appended to the first swagger client where it finds ".resources_container".

```javascript
$(function () {
        window.swaggerUi = new SwaggerUi({
            url: 'http://petstore.swagger.io/v2/swagger.json',
            dom_id: "swagger-ui-container",
                ...
        });
        window.swaggerUi2 = new SwaggerUi({
            url: 'http://petstore.swagger.io/v2/swagger.json',
            dom_id: "swagger-ui-container2",
                ...
        });

        // render the two unique swagger clients...
        window.swaggerUi.load();
        window.swaggerUi2.load();
    });

```

**Comment by mohsen1** [comment]
We can change the jQuery selector to scope to root `el`. Can you make that change and make a PR to develop_2.0 branch?

**Comment by pkcinna** [comment]
There may be a few more id's or elements to consider and I'm still getting familiar with the code.  It is better if someone else can tackle it.

**Comment by fehguy** [comment]
This should be fixed now.

**Comment by pkcinna** [comment]
Can you confirm this change went in?  This still is not working in 2.0 dev or 2.1 master for me.  I was not able to find any changes for rev 1161 but that may be issue on my side with using GIT and searching revisions.

**Comment by pkcinna** [comment]
Or maybe the rending of the list is in the right place now but if you click on show/hide in one swagger-ui instance it will expand/collapse all instances on the page.

**Comment by pkcinna** [comment]
Sorry. This seems to work in general but my test case uses the same url in both swagger ui instances.
The problem for supporting this case seems to be an id is generated based on resource name.toggleEndpointListForResource: function(resource) {
   var elem = $('li#resource_' + Docs.escapeResourceName(resource) + ' ul.endpoints');
