### ISSUE TITLE
swagger-ui overrides the "consumes" property with Accept:application/json

### ISSUE THREAD

**Issue by ivan-golubev** [swagger-api/swagger-ui#1166]
I bumped into the same problem as [#485](https://github.com/swagger-api/swagger-ui/issues/485). Swagger-ui (2.0.19 or 2.1.0-M2) keeps setting the Accept:application/json.
Simple POST request with consumes: application/x-www-form-urlencoded and produces: "application/xml; charset=UTF-8".
Here is the swagger.json :
```javascript
{
  "swagger": "2.0",
  "info": {
    "description": "This is a sample documentation.",
    "version": "1.0.0",
    "title": "documentation",
    "contact": {
      "email": "apiteam@wordnik.com"
    }
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "paths": {
    "/users": {
      "post": {
        "summary": "Create profile",
        "description": "Authenticate user with either Facebook id and create a new profile for him.",
        "operationId": "createProfile",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/xml; charset=UTF-8"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "auth_method",
            "description": "facebook",
            "default": "facebook",
            "required": true,
            "type": "string"
          },
          {
            "in": "formData",
            "name": "application",
            "description": "none",
            "required": true,
            "default": "facebook",
            "type": "string"
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      }
    }
  }
}
```
What am I doing wrong? Is there any place in code where I can override this?

**Comment by ivan-golubev** [comment]
I am attaching a screenshot.
![bug_1166_screenshot](https://cloud.githubusercontent.com/assets/7465655/7158408/645550a4-e382-11e4-9e5c-f6ca69e3218a.png)

**Comment by ivan-golubev** [comment]
I have taken the fix from #369 and placed into the swagger-ui.js.
Now swagger works as expected. Thank you.

**Comment by fehguy** [comment]
with #369 merged, please reopen if you have an issue.

**Comment by to-kra** [comment]
was this issue fixed ? as I am experiencing same problem now with actual swagger

**Comment by IanRogers-LShift** [comment]
Has https://github.com/swagger-api/swagger-js/pull/369 been merged into master yet? I'm still seeing this issue in https://github.com/smoketurner/dropwizard-swagger/ 0.9.x which claims to be using swagger-ui 2.1.4

**Comment by Bombenleger** [comment]
Same here, I'm seeing the same issue on current master.

**Comment by IanRogers-LShift** [comment]
I now realise swagger-js and swagger-ui are different things. Although https://github.com/swagger-api/swagger-js/pull/369 has been applied to swagger-js which doesn't seem to fix swagger-ui even though it claims to.

**Comment by webron** [comment]
If you're seeing the same issue in the current master, please open a new ticket. This was closed a year ago (and resolved then). If it exists again, it's a regression.

**Comment by shishirsharma** [comment]
I am still seeing this issue. can you please give a tag/sha where this was fixed ?

**Comment by alexcroox** [comment]
I am still experiencing this issue also

**Comment by webron** [comment]
@alexagranov Which version are you testing with?

**Comment by lupuleti** [comment]
I am still experiencing a similar issue. Even if the Accept header has a default value in the Swagger Configuration (Docket object), when the UI sends a request to the endpoint it will override the Accept header default value with "text/html". The json looks alright:
          {
            "name": "Accept",
            "in": "header",
            "description": "A header to specify the API version and content type.",
            "required": true,
            "type": "string",
            "default": "application/vnd.app.resource-1.0+json"
          }

The curl command is wrong in the UI: curl -X GET --header 'Accept: text/html' ...

Using springfox swagger 2.5 in java.

**Comment by prativapokhrel** [comment]
I had the same issue and I tried to hardcode the swagger.js file which actually worked. I changed "responseContentType = application/json" to "responseContentType = value of accepts parameter". Hope it works for you as well :)
