### ISSUE TITLE
Unable to get controller name in swagger ui

### ISSUE THREAD

**Issue by aiswaryalenin** [swagger-api/swagger-ui#1167]
I have 5 controller.In UI it shows all the four controller services in one section without controller name,after it show userpreference controller with their service.Userpreference controller only showed properly.Please guide me where is something wrong.
![output](https://cloud.githubusercontent.com/assets/11954662/7159194/10034ecc-e39e-11e4-9d4e-1b11a1f24db3.PNG)

**Comment by webron** [comment]
Can you share your api-docs?

**Comment by aiswaryalenin** [comment]
Sorry, I am unable to show api-docs.could you tell me ,Why it shows like this?

**Comment by webron** [comment]
Can you share it in private? If so, the email is in my profile. Without it there's little we can do to investigate it.

**Comment by aiswaryalenin** [comment]
I founded the solution, i wrongly gave the controller path,so that it show like that.Thank for help @webron

**Comment by PavaniAkula** [comment]
I am aslo having the same issue. i have only 4 controllers displayed on the swagger ui while 5 got processed when i run the rake. kindly suggest

**Comment by Shuan-Ku** [comment]
@PavaniAkula - how do you add the comments behind the controller name?  Thank you
