### ISSUE TITLE
Swagger doesn't install with or without sudo.

### ISSUE THREAD

**Issue by freak4pc** [swagger-api/swagger-ui#1172]
Doing "npm start" on latest clone results in numerous 

```
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

Doing "sudo npm start" to remedy, results in : 

```
bower ESUDO         Cannot be run with sudo
```

Any ideas?

**Comment by webron** [comment]
you're doing `npm start` on swagger-ui?

**Comment by freak4pc** [comment]
Whoops. I'm full of clumsy mistakes today. Just noticed instructions say install and gulp.

**Comment by webron** [comment]
Keep in mind that's only if you made changes to the sources and need to rebuild. Otherwise, you can use whatever is under the /dist directory as-is.

**Comment by freak4pc** [comment]
Gotya. thanks :)
