### ISSUE TITLE
"number" type doesnt show in Model Schema

### ISSUE THREAD

**Issue by sheehan** [swagger-api/swagger-ui#1181]
Using this:

```
{
  "swagger" : "2.0",
  "basePath" : "/app/api",
  "paths" : {
    "/test" : {
      "get" : {
        "tags" : [ "test" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "schema" : {
              "$ref" : "#/definitions/Test"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "Test" : {
      "properties" : {
        "stringTest" : {
          "type" : "string"
        },
        "integerTest" : {
          "type" : "integer",
          "format" : "int32"
        },
        "doubleTest" : {
          "type" : "number",
          "format" : "double"
        },
        "booleanTest" : {
          "type" : "boolean"
        }
      }
    }
  }
}
```

I see all four properties in the Model:

![image](https://cloud.githubusercontent.com/assets/253069/7207660/c7e12984-e500-11e4-9118-6e1a93811f57.png)

but the number property is missing from the Model Schema:

![image](https://cloud.githubusercontent.com/assets/253069/7207673/de418b1a-e500-11e4-8638-467a34c0cf6d.png)

**Comment by webron** [comment]
Which version of swagger-ui do you use? Have you tested with the *current* master?

**Comment by sheehan** [comment]
I was using `v2.1.0-M2`. Just updated to the current master and am still seeing the issue.

**Comment by ponelat** [comment]
Confirmed its not working in master, 
but appears to be fixed in https://github.com/swagger-api/swagger-ui/tree/develop_2.0
Which is our development branch.

**Comment by sheehan** [comment]
It's working now, thanks.
