### ISSUE TITLE
Browser crashes while formatting large json response

### ISSUE THREAD

**Issue by MassTroy** [swagger-api/swagger-ui#1184]
When an API response is returned that contains >500 kB of unformatted json, the browser will occasionally/frequently crash while trying to pretty format it for display.

Possible solutions:
1. Do not format json at all if response is larger than a threshold, instead display the unformatted version
2. Truncate the response and format only the first N kB of it. Print a warning to indicate that the response was too large and truncated. Perhaps even add a way to view the raw in a new tab

**Comment by webron** [comment]
@MassTroy - Thank you for the suggestion, but I believe this is exactly what the `highlightSizeThreshold` parameter for SwaggerUi does - https://github.com/swagger-api/swagger-ui#parameters.

**Comment by webron** [comment]
@MassTroy - did you get a chance to test it?

**Comment by fehguy** [comment]
@webron we should set a sensible default for this.
