### ISSUE TITLE
in: body indicates error

### ISSUE THREAD

**Issue by Fluxxo** [swagger-api/swagger-ui#1188]
Open http://editor.swagger.io/#/
Go to line 28, change "query" to "body" -> An error is indicated.
The specification tells me, body should be ok at that point.

**Comment by webron** [comment]
- That's swagger-editor and not swagger-ui.
- Without providing what you have in the editor, there's no way of knowing what's in line 28. For me line 28 is `        Register a new User` which I doubt is what you have.

**Comment by Fluxxo** [comment]
Sorry, raised that issue in the wrong tab. Sorry for that.
There's a default text, that's what I meant.

**Comment by webron** [comment]
It's better to just give all the information than depend on what's there. And there's very little change you can change query to body as is, because their structure is slightly different.
