### ISSUE TITLE
Support for nested resources in body missing

### ISSUE THREAD

**Issue by danielbecker** [swagger-api/swagger-ui#1189]
We are currently in the process of documenting our JSON-only API with swagger.
In this process we encountered the same problem that was mentioned in this previous issue: https://github.com/swagger-api/swagger-ui/issues/58.
The second link mentioned in the ticket is empty and the first one just refers to the default data type page.

What is the correct way of specifying nested parameters in a path?

**Comment by webron** [comment]
What do you mean by nested parameters in a path?

**Comment by danielbecker** [comment]
What I meant by that was an endpoint accepting a JSON object, which can have nested resources.
For example: { "session": "abc", "user":{ "name": "chris" } }

**Comment by webron** [comment]
How is that missing?

**Comment by danielbecker** [comment]
Could you give me a short example of how to do that in swagger?

**Comment by webron** [comment]
Have you seen the [pet store](http://petstore.swagger.io/)? Specifically http://petstore.swagger.io/#!/pet/addPet.

**Comment by webron** [comment]
@danielbecker - did you manage to work it out?

**Comment by danielbecker** [comment]
Well, thanks to your help I was able to work my around the problem. However, it would still be nice to nest objects anonymously.
