### ISSUE TITLE
Incorrect querystring creation

### ISSUE THREAD

**Issue by mbaumgartl** [swagger-api/swagger-ui#1190]
I try to document my not-so-restful API using Swagger. I therefore need to overload paths. Because this is not supported (I found some discussions to that topic), I added parameters to the paths:

```yml
swagger: "2.0"

info:
  version: "0.0.1"
  title: Awesome API

host: "localhost:8003"
basePath: /

schemes:
  - http

produces:
  - application/json

paths:
  /items/{itemId}:
    get:
      parameters:
        - name: itemId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: An item
          schema:
            type: object

  /items/{item}?action=pdf:
    get:
      parameters:
        - name: item
          in: path
          required: true
          type: integer
          format: int64
        - name: template
          in: query
          type: string
      responses:
        200:
          description: Item as PDF
```
If I try to run a request against second endpoint, I end up with an incorrect querystring:
http://localhost:8003/item/1?action=pdf?template=awesome

I know this is an inherited error because defining paths this way is not intended but maybe you can fix it anyway.

Maybe there is already an existing issue but I can't find it anymore (sorry).

Marco

**Comment by webron** [comment]
It's simply not supported by Swagger. You cannot overload paths, and you cannot add query parameters as part of the path.

**Comment by mbaumgartl** [comment]
I know ;-)

My wish seems to be a duplicate of https://github.com/swagger-api/swagger-spec/issues/164.

Is there a real chance Swagger is going to support querystring in paths in a future version?

**Comment by webron** [comment]
No idea. We haven't started making official discussions about it. But for now, it's definitely not supported.
