### ISSUE TITLE
Cannot create a multiple select parameter

### ISSUE THREAD

**Issue by peeter-tomberg** [swagger-api/swagger-ui#1193]
My JSON:
```
parameters": [
	{
		"name" : "interests",
		"in" : "query",
		"description": "The intrests of a user",
		"items": {
			"type": "string"
		},
		"enum": [
				"movies",
				"books",
				"cars"
		],
		"type": "array",
		"collectionFormat": "csv"
	}
]
```

Expected result:

![](http://puu.sh/hmMYP/dd91698842.png)

and the query being:
findByInterests?interests=books,cars

Actual result:
![](http://puu.sh/hmN2f/918d55607f.png)

**Comment by ponelat** [comment]
This was just recently fixed in https://github.com/swagger-api/swagger-ui/pull/1192 and should be coming  up the next release.

**Comment by ponelat** [comment]
@peeter-tomberg the fix is in the develop_2.0 branch.

**Comment by fehguy** [comment]
this is fixed now.
