### ISSUE TITLE
OAuth2 for petstore example fails to launch

### ISSUE THREAD

**Issue by kojoru** [swagger-api/swagger-ui#1194]
"click to authenticate" button doesn't do anything when clicked

Steps to reproduce:

1. Download a fresh swagger-ui copy and launch it. Default petstore example will open.
2. Open "pet"→"PUT /pet"
3. Click button in the topright corner with the exclamation mark.

Expected behavior: OAuth2 flow is initiated
Actual behavior: nothing happens

**Comment by webron** [comment]
@mohsen1 - can you please look into that?
