### ISSUE TITLE
Localization documentation points to files that are not in the repository

### ISSUE THREAD

**Issue by kojoru** [swagger-api/swagger-ui#1195]
The localization docs say the following:
>The localization files are in the dist/lang directory.
>
>To enable translation you should append next two lines in your Swagger's index.html (or another entry point you use)
>
```html
><script src='lang/translator.js' type='text/javascript'></script>
><script src='lang/en.js' type='text/javascript'></script>
```

However mentioned files are not in the `master` or `develop2.0` branch. As a result I'm not able to add localization to my project.

**Comment by kojoru** [comment]
I've noticed that the closed PR #924 had `lang` files while PR #967 which was merged in the end doesn't see to have them. I'm not sure if it's somehow related to the issue at hand.

**Comment by webron** [comment]
@mohsen1 - Can you please look into that?

**Comment by mohsen1** [comment]
It's because #924 had those files in `dist`. I'm making a pr to fix that

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/5abd2819f93984a2d17d43df2b47ef9b4de715ad
