### ISSUE TITLE
UI file responses not downloading

### ISSUE THREAD

**Issue by hamx0r** [swagger-api/swagger-ui#1196]
As of swagger-ui develop_2.0 branch commit d76a62caf7e25115921db44accc61843de1727b2 which included a fix for bug #374, there seems to be a bug preventing the`\\Download` block of code:
```
    // Download
    } else if (headers['Content-Disposition'].test(/attachment/) ||
               headers['content-disposition'].test(/attachment/) ||
               headers['Content-Description'].test(/File Transfer/) ||
               headers['content-description'].test(/File Transfer/)) {
```

 Chrome's Developer Tools console shows `Uncaught TypeError: Cannot read property 'test' of undefined` in swagger-ui.js:21394 (above).   The progress animation runs forever.

The `Content-Disposition` in my response is `attachment; filename=file.zip` and the response is a valid ZIP.  The error suggest `headers[]` isn't being properly populated.  The relevant parts of the Swagger Spec feeding the UI are (esp `responses`):

```
		"/flights/csv/{flight_id}": {
			"parameters": [{
				"required": true,
				"type": "string",
				"name": "flight_id",
				"in": "path"
			}],
			"get": {
				"tags": ["flights"],
				"summary": "\n        Return CSV of flights, one for each flight \"id\" (a CSV list of id's is acceptable)\n        ",
				"responses" : {
					"200" : {
						"description" : "CSV ZIP File",
						"schema" : {
							"type" : "file"
						}
					}, ...
				},
				"parameters": [{
					"name": "flight_id",
					"required": true,
					"in": "path",
					"type": "string",
					"description": "CSV list of flight IDs"
				},
```

**Comment by ponelat** [comment]
the fix looks to be in a pending PR https://github.com/swagger-api/swagger-ui/pull/1122
@webron not sure on the protocol here with other PRs...

**Comment by dariodeltemple** [comment]
We are having a similar issue. In our case we want to download a .crt file. This is the response header:
```
Status Code: 200
Date: Wed, 29 Apr 2015 14:21:05 GMT
Server: servername
Etag: "e1e9bc2cf65550466fc3d1814a3d613de6ae210c"
Access-Control-Max-Age: 1728000
Content-Type: application/octet-stream
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Disposition: attachment;filename="CA.crt"
Access-Control-Allow-Headers: *
Content-Length: 1306
```
Printing headers in swagger-ui.js, showStatus methods shows:
headers: {"content-type":"application/octet-stream"}

Do you have an estimate when this fix will be included?

**Comment by fehguy** [comment]
This should be fixed now, please reopen if you have any issues.

**Comment by Ankitsinghalatjolly** [comment]
This is not yet fixed.
