### ISSUE TITLE
Request documentation on use of "Response Content Type" dropdown

### ISSUE THREAD

**Issue by hamx0r** [swagger-api/swagger-ui#1197]
The dropdown in the Response Class section of the UI is labeled "Response Content Type".  Since it's a dropdown, it implies it's an input for a user to select which type of response he would like to receive for the `200` response of the given method.  However, the documentation does not say how the list of `responses` is intended to be used.  What is the intended use of the dropdown?  Is there a header value sent with a request which results in a response of a particular Content-Type?

**Comment by ponelat** [comment]
There is the 'Accepts' header which tells(or asks) the server for a particular mime type to be sent back. So selecting a 'Response Content Type' should have the desired effect.

**Comment by webron** [comment]
It also corresponds to the `produces` property of the operation.

**Comment by hamx0r** [comment]
From @ponelat and @webron's  comments, the dropdown is _populated_ by the `produces` field of an Operation, and is used to first select what is sent to the server in a  `request` [Accepts header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), which then dictates the MIME type of the `response`, right?  This is good to know.  What's the procedure for updating the [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-5)?  Using the Accepts header on the server-side code would be a cool check to use, now that I know it exists.  In general, i've learned a lot about JSON API programming from using Swagger, and I assume others have as well.

**Comment by ponelat** [comment]
@hamx0r thanks for expanding the explanation.
It's pretty simple to declare 'produces' (and 'consumes' - to tell the server what to expect of your request data).

they're just an array of strings, which will be interpreted as mime types...
```javascript
...
produces: [
  'application/json',
  'application/xml'
]
...
```
They can go in your operations, or globally (i believe)
The [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-5) does detail their declaration, and you can always take a peek at the petstore example spec ( [raw](http://petstore.swagger.io/v2/swagger.json) |  [beautiful](http://jsoneditoronline.org/?url=http://petstore.swagger.io/v2/swagger.json) ), to see where it gets used.

**Comment by hamx0r** [comment]
Thanks @ponelat.  To clarify, I saw that the spec details their _declaration_, but I didn't see where it details their _usage_.   Perhaps to more experienced API devs, the usage (ie "The selected value from the dropdown selector goes into the requests `Accepts` header.") would have been known.   

To prevent document bloat in the spec, would the team be open to using Github's wiki feature for the swagger-ui project?   Currently, all discussion happens with bug reporting.  Perhaps the spec doc could continue to remain the primary reference doc (concise), but the wiki could contain more info for those newer to Swagger and HTTP-based APIs.  Thoughts?

**Comment by webron** [comment]
@hamx0r - we're working on a modified and expanded new website, which will include expanded docs. This is good input with regards to what can go there. I don't want to start a wiki here as all the docs may end up on that website.

**Comment by hamx0r** [comment]
Great! I'll leave it up to you if this issue should then be closed, or linked to whatever is tracking that new website development.

**Comment by webron** [comment]
I've marked it as `Documentation`, but will close it for now. Once we ramp up the new docs, I'll go over all the documentation tickets to see what needs to be covered.

**Comment by wraycode** [comment]
cannot get any other options in dropdown have tried produces any help greatly appreciated https://stackoverflow.com/questions/44660772/swagger-ui-symfony-nelmioapidoc-add-multiple-responsetype-options
