### ISSUE TITLE
Swagger u not able to mapping with  CXFServlet  /* type mapping

### ISSUE THREAD

**Issue by anand4sn** [swagger-api/swagger-ui#1200]
Hi All,

I'm not able to enable swagger ui with /* mapping in CXFservlet mapping. otherwise its woring good.

NOT WORKING - I want to map the CXFServlet below.

```xml
<servlet-mapping>
<servlet-name>CXFServiceServlet</servlet-name>
<url-pattern>/*</url-pattern>
```

WORKING
```xml
 <servlet-mapping>
<servlet-name>CXFServiceServlet</servlet-name>
<url-pattern>/api/*</url-pattern>
```
Could you please anyone help on this.last two day im trying different ways but not able to fix. Thanks in Adavce.

**Comment by anand4sn** [comment]
<servlet-mapping>
<servlet-name>CXFServiceServlet</servlet-name>
<url-pattern>/api/*</url-pattern>

**Comment by webron** [comment]
This is really not the place for such such a question. Please use our [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) to ask the question and provide more details about your set up and issue.

**Comment by anand4sn** [comment]
Thanks webron

**Comment by anand4sn** [comment]
@webron In My office gmail is not accessable so could you please help on this issue here.

Sample  service

  //@Path(" ")  - not required
@Api 
Class MyServiceName{

  @Path("/announcement"
   public void method1(){}

@Path("/event"
   public void method1(){}

} 


My problem is in configuration like previous comment .

   i want to map  servlet mapping  only with /*
    because my servic should call like ( hostname:port/rootcontext/methodRequestmapping)
   http://localhost:8080/myapp/announcement
   http://localhost:8080/myapp/eventtype

Mapping
<servlet-mapping>
<servlet-name>CXFServiceServlet</servlet-name>
<url-pattern>/*</url-pattern>


I dont want to configure like below  ( its working)

   <servlet-mapping>
<servlet-name>CXFServiceServlet</servlet-name>
<url-pattern>/api/*</url-pattern>

http://localhost:8080/myapp/api/announcement -api(or any word shold not come)
   http://localhost:8080/myapp/api/eventtype-

**Comment by anand4sn** [comment]
@webron sorrry to post here. please help or give any github chat group

**Comment by olensmar** [comment]
@anand4sn as webron already mentioned, GitHub is not meant for general support issues - you will either have to get your gmail account working or find some other way to access the swagger google group. Good Luck!

/Ole

**Comment by anand4sn** [comment]
@olensmar Sorry . Thank you.
