### ISSUE TITLE
headers['Content-Disposition'].test(/attachment/) throws error

### ISSUE THREAD

**Issue by joshmackey** [swagger-api/swagger-ui#1201]
Error: TypeError: headers['Content-Disposition'] is undefined

I'm returning type "text/calendar" from the server and the above error gets thrown. It doesn't handle the case if Content-Disposition doesn't exist.

I'm using FF.

**Comment by ponelat** [comment]
It is a bug, there is a pending PR #1122 
#1196 has the same problem.

**Comment by webron** [comment]
Closing as duplicate.
