### ISSUE TITLE
Show format when viewing model.

### ISSUE THREAD

**Issue by ralphvanetten** [swagger-api/swagger-ui#1202]
Is it possible to show the format of a field in the model of an object?
For instance, `shipDate` is of type `string` and has its format set to `date-time`. It would be nice if the model can show something like `(string: date-time, optional)` instead of just `(string, optional)`.

I am referring to this:
![selection_106](https://cloud.githubusercontent.com/assets/1533323/7296479/4f32ef9e-e9c0-11e4-965e-e077dd2f5319.png)

**Comment by iushankin** [comment]
I think it's a good idea.
This model is generated by the code from the [swagger-js](https://github.com/swagger-api/swagger-js) project.
@webron, @fehguy: let's move this issue into the [swagger-js](https://github.com/swagger-api/swagger-js) so, I could implement this feature

**Comment by zyro23** [comment]
for `date-time`, this might be related: https://github.com/swagger-api/swagger-ui/issues/1183

**Comment by webron** [comment]
It's also related to https://github.com/swagger-api/swagger-js/issues/219.

**Comment by yzatslinear** [comment]
Just to be explicit, it would be useful to display any format, not just special ones. For example, if I have type: string, format: foo it should show (string: foo, optional)

**Comment by fehguy** [comment]
see parent issue, #1248
