### ISSUE TITLE
Response Body does not display. UI hangs

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-ui#1204]
I am using swagger for a java application (swagger-jaxrs_2.10-3.10.jar). Whether GET or POST the issue is that the request hangs, meaning that the Response does not display and the in-progress keeps rolling along. However, if I look at the Network traffic I can see that the request was successful (200) and the right response came back. It is just that it will not display in the Swagger UI. And, for GETS, there is always a Body box. Why? It is not needed.

Thanks,

John Harter

**Comment by webron** [comment]
@jharter - `swagger-jaxrs_2.10-3.10.jar` <-- doesn't exist.

As for the hang - is your response relatively large?

As for the body box for GET operations, that would depend on your Swagger definition. We'd need to see it to further assess it.

**Comment by jharter** [comment]
Thanks so much Ron for responding. As to the swagger jar doesn't exist - At the url http://www.java2s.com/Code/Jar/s/Downloadswaggerjaxrs210130jar.htm I downloaded a zip file (http://www.java2s.com/Code/JarDownload/swagger-jaxrs/swagger-jaxrs_2.10-1.3.0.jar.zip). Unzipped, it contains the file swagger-jaxrs_2.10-3.10.jar, which I registered with Meven for my project. Perhaps this is not the right swagger download?

The response I am expecting is not large at all, usually in the order of a few lines of xml or a small json text response. Very small.  The interesting thing about the response is that although Swagger hangs (never expands the page to show the response), I can use Chrome's developer tools to see the network traffic and the correct response was received. But Swagger just shows the "thinking" widget. 

The third thing you mention is the Swagger Definition? I wish I know what that was or where I might find it to edit. I am working in a Java Project, and I am no Java expert. The only places I find any sort of mention of Swagger is in the java source file, beans.xml, and the POM file.

This is how I am setup: I run a local Tomcat to host the application, the results of the Swagger build, and I use a local IIS server to serve up the Swagger UI. This all seems to work fine, but for that pesky body box. However, when I try to hit an endpoint that exists on a remote server, Swagger hangs. Since I can see the proper response in Chrome's developer tool, I don't think there is a cross-domain issue. 

I truly appreciate your advice. Is there something I can send you that will make this situation clearer?

Thanks,

John Harter

**Comment by webron** [comment]
Which JAX-RS implementation do you use? I ask because you use the swagger-jaxrs dependency, and would like to suggest a different path and point you in the right direction.

The version you're using now is extremely old (and buggy) so let's start from there.

**Comment by jharter** [comment]
Thanks. I appreciate your help. Apparently we are using Apache CXF for JAX-RS. Meven for building. When you say the version I am using is buggy, do you mean the version of Swagger or JAX-RS. I hope  Swagger.

This is very cool that you are helping clueless me.

Thanks,

johnh

**Comment by webron** [comment]
The version of swagger-core (not Swagger itself). Take a look at this sample - https://github.com/swagger-api/swagger-core/tree/master/samples/java-jaxrs-cxf. Unfortunately, we don't have a guide specific for CXF but the sample should be enough to get you started. Notice the version of the dependency there and use that (1.5.1-M2).

**Comment by jharter** [comment]
Great. I will check it out. Thanks.

**Comment by webron** [comment]
I'll close this issue for now because we can't do much else with it. Please open a new one if needed. For general support, please use the mailing list.
