### ISSUE TITLE
v1.2 spec doesn't render Model's in "Reponse Class -> Model"

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#1207]
Page: http://petstore.swagger.io/#!/pet/getPetById
Spec: http://petstore.swagger.io/api/api-docs
See screenshot...

![screenshot from 2015-04-24 16 09 26](https://cloud.githubusercontent.com/assets/8438485/7320729/b1db3fdc-ea9e-11e4-8832-e836547e267a.png)

**Comment by webron** [comment]
Fixed in develop_2.0.
