### ISSUE TITLE
How does swagger-ui determine the [BASE URL]? Documentation? 

### ISSUE THREAD

**Issue by alexworden** [swagger-api/swagger-ui#1208]
I can't get my swagger-ui "Try it now" buttons to work when I deploy to https production. When I run locally they work and have the correct URL but in production (https is the only difference is my guess) the path that the cxf server is mapped to is missing from the try-it-now url. 

How is this base path determined in the swagger-ui? I can't find any clear documentation and can't understand how the Javascript works. I'm using swagger on a Java CXF implementation and notice the odd quirks: 

* It seems that the 'value' attribute from the @Api annotation is used to name the api of the top of the swagger-ui docs. This is my basepath but doesn't get used in the try-it-now button. 

* The configured 'basePath' in the swagger BeanConfig defined in my spring config seems to be important to retrieve the spec. This also includes my service's base path. 

* When I try adding a 'basePath' attribute to the @Api annotation, it breaks swagger-ui in my development environment.

**Comment by webron** [comment]
The way it works is *slightly* different between Swagger 1.2 and 2.0.

In 1.2, the `basePath` is used as the scheme+host+context root of the API calls, where the paths of the operations are simply attached to it.

In 2.0, there are three separate properties, namely `schemes`, `host` and `basePath`. All those together build the same `basePath` as was provided in 1.2. The main difference is that if one of the values is missing, then the respective value would be taken from where the Swagger definition is hosted. So, if you don't specify a scheme and you expose your swagger.json via https, then https would be used to make the API calls.

Assuming you use swagger-core, the `value` of `@Api` has nothing to do with the `basePath`. Setting the `basePath` of the `@Api` annotation is also ill-advised and should be used only for specific use cases (which does not seem to apply for you). The `basePath` in the `BeanConfig` is the one used to set the value, but it is completely unrelated to where the Swagger definition itself is hosted.

You mention that the button works in development but not in production, but you don't say what's actually happening. When you click the try it now button, you will see the full URL in the HTML page, and even if not, you can see which URL is being called using your browser's web console. Without the information of the `basePath` value and what you actually get when you click the button, there's not much we can do to help.

Lastly, support questions are better sent through the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket). This is not really bug with swagger-ui, but rather a configuration issue that runs across multiple projects (swagger-core and swagger-ui), and it's actually more likely to be a swagger-core configuration issue. We'd also need the dependency version you use to provide better support.

**Comment by alexworden** [comment]
Thank you so much for the thoughtful reply. Due to the size of the scala dependencies added for this technique, I've decided to generate the swagger spec at compile-time. I'm trying to figure out how best to serve the spec from static content (or potentially templatized content so I can inject the dynamic public service endpoint base-path).

**Comment by webron** [comment]
@alexworden - swagger-core 1.5.X doesn't pull in the scala dependencies anymore (it's pure java), *and* produces Swagger 2.0 specifications. You may want to use that instead and get the benefits of both worlds :)
