### ISSUE TITLE
Request Body Displays when not asked for

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-ui#1212]
On both my GETS and POSTs the Body Request field displays and I don't need it. How do I get rid of it? Here is a sample:

@POST
    @Path("/geolocation")
	@Produces({"application/xml"})
	@Consumes({"application/x-www-form-urlencoded"})
	@ApiOperation(value = "Lookup user geolocation", notes = "No Parameters", response = Geolocation.class)
	@ApiImplicitParams(value = {
			@ApiImplicitParam(name = "type", value = "geo lookup type", required = true, dataType = "String", paramType = "form"),
	})
	@ApiResponses(value = {
		@ApiResponse(code = 400, message = "Invalid IP detected"),
		@ApiResponse(code = 404, message = "Geolocation not found")
	})
    public Geolocation getGeo(MultivaluedMap<String,String> values){
		return getGeoProcess(values, false);

Thanks,

johnh

**Comment by webron** [comment]
That's a question for [swagger-core](https://github.com/swagger-api/swagger-core/), please ask there.
