### ISSUE TITLE
How are Examples rendered?

### ISSUE THREAD

**Issue by Smolations** [swagger-api/swagger-ui#1213]
Not sure if this is a bug or not, but I couldn't find any existing issues related to it.

I spent some time trying to see the effect of adding an Example object to the `examples` key in a Response object. The documentation says that the Example object is "An example of the response message." However, when this object exists in my swagger config, I don't see anything rendering in the UI. I tried a sample object with a couple dummy properties, as well as just a simple string.

Is this feature not implemented yet? And how does it differ from an attached `schema` on the response object?

**Comment by webron** [comment]
I believe it is not implemented yet.

**Comment by fehguy** [comment]
See parent issue #1248
