### ISSUE TITLE
Running swagger-ui in "read only mode"

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-ui#1214]
Make it possible to use the swagger-ui in read only mode, Ie. where I serve up the JSON specs but the actual API backend is not running (and hence the "try it out!" buttons are disabled).

**Comment by fehguy** [comment]
just set `supportedSubmitMethods` per this:

https://github.com/swagger-api/swagger-ui#swaggerui

I believe an empty array will accomplish this.

**Comment by cancan101** [comment]
The click to authenticate button still shows up:
![image](https://cloud.githubusercontent.com/assets/51059/7356765/52da2fb4-ecf8-11e4-9366-3aaf0e4e5e12.png)

**Comment by fehguy** [comment]
OK that's different from what you opened this ticket as.  If you can please re-title this issue then it can be addressed.

**Comment by webron** [comment]
Since you opened a new ticket, we'll close this one.
