### ISSUE TITLE
Displayed name twice when required is set to true

### ISSUE THREAD

**Issue by Ckim15** [swagger-api/swagger-ui#1216]
Hi,

I am having an application which value is required to pick from the drop down list.
Its type is string with defined values in enum. the name (**gender**)  was displayed twice under column parameter and value when required is set to true. Any idea?

    - in: header

      name: gender
 
      required: true

      type: string

      enum:
             - Female
             - Male

   Here is the attached image: 
   

![displaynametwice](https://cloud.githubusercontent.com/assets/10535043/7359647/4aa7c334-ed06-11e4-9868-fd9ecc9f142e.png)

**Comment by ponelat** [comment]
@Ckim15 the fix is in the branch develop_2.0.
I believe @whitlockjc fixed it, but for the life of me I can't find a reference.

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-ui/pull/1180 fixed it, in develop_2.0.
