### ISSUE TITLE
Swagger UI - can it display Minimum value, Maximum value, Pattern, Default Values ??

### ISSUE THREAD

**Issue by aviadavi** [swagger-api/swagger-ui#1217]
I would expect API documentation to include those "Validation rules"

**Comment by webron** [comment]
It displays those when you hover over the property in the Model.

**Comment by aviadavi** [comment]
OK. I see it. (for Range and Pattern, but not for default values)
Any chance to put this information in the model without hovering over the property ? 
I want to be able to generate documentation that does not require hovering over a properties.

I don't want my clients to guess on what property to hover.

**Comment by webron** [comment]
If you can come up with a way to display all the information in a way that's visually appealing and won't make the UI bloated, feel free to create a PR with the implementation.

**Comment by fehguy** [comment]
Or even a mock up of how it could be more effective would be great.

**Comment by aviadavi** [comment]
In RAML 0.8 display looks appealing. 

see example here: https://anypoint.mulesoft.com/apiplatform/popular/#/portals/apis/6308/versions/6302/pages/31760

It looks like there is enough space for everything in that display. doesn't it?

**Comment by DerManoMann** [comment]
What about pattern for a parameter value?

**Comment by DerManoMann** [comment]
To clarify my question - I do have pattern configured for url parameter and wonder if there is any code to support validation for those.

**Comment by tanob** [comment]
@webron the feature of displaying information about the range doesn't seem to be working. If you look at http://petstore.swagger.io/, the `orderId` has a `maximum` and `minimum` specified, if you hover `orderId` in the Model tab it doesn't show.

**Comment by webron** [comment]
@tanob right now, these are displayed for model properties only, and not primitive parameters.

**Comment by michaelbaqadi** [comment]
@webron do you guys now support having maximum and minimum with query parameters such as limit.

**Comment by webron** [comment]
@michaelbaqadi support in what sense?

**Comment by michaelbaqadi** [comment]
For example, we can specify the maximum integer number for the limit parameter.

**Comment by webron** [comment]
@michaelbaqadi - sorry for the late reply, somehow missed the notification on it.

I'm honestly not sure if we support those right now. The best way to find out is to simply test it.

**Comment by webron** [comment]
Closing in favor of #993.
