### ISSUE TITLE
Swagger not able to mapping with  CXFServlet  /* type mapping

### ISSUE THREAD

**Issue by anand4sn** [swagger-api/swagger-ui#1218]
@webron In My office gmail is not accessable so could you please help on this issue here.

Sample service

//@Path(" ") - not required
@Api 
Class MyServiceName{

@Path("/announcement"
public void method1(){}

@Path("/event"
public void method1(){}

}

My problem is in configuration like previous comment .

i want to map servlet mapping only with /*
because my servic should call like ( hostname:port/rootcontext/methodRequestmapping)
http://localhost:8080/myapp/announcement
http://localhost:8080/myapp/eventtype

Mapping

CXFServiceServlet
/*

I dont want to configure like below ( its working)

CXFServiceServlet
/api/*

http://localhost:8080/myapp/api/announcement -api(or any word shold not come)
http://localhost:8080/myapp/api/eventtype-

**Comment by olensmar** [comment]
@anand4sn as already mentioned, GitHub is not meant for general support issues - you will either have to get your gmail account working or find some other way to access the swagger google group. Good Luck!

/Ole
