### ISSUE TITLE
Cannot run "Try it out!" if query param has the name=`commit`

### ISSUE THREAD

**Issue by musbaig** [swagger-api/swagger-ui#1219]
Unable to run "Try it out!" if query parameter has the name=`commit`. Seeing the following GET output string in the logs:

`GET /git-show?key1=value1&key2=value2&commit=Try%20it%20out!&type=2`

If the query parameter is called `commit`, the actual submitted value from the swagger UI input field is ignored, and the string `Try%20it%20out!` is used instead.

**Comment by ponelat** [comment]
Ha! my type of bug :D
