### ISSUE TITLE
No Way to Collapse Operations after Expanding

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-ui#1222]
Unlike "Show/Hide", "Expand Operations" has no matching collapse.
![image](https://cloud.githubusercontent.com/assets/51059/7379640/47c1a306-edc4-11e4-8f73-73146d02ba80.png)

**Comment by cancan101** [comment]
I think `List Operations` might actually be the collapse.

**Comment by tuukkamustonen** [comment]
It's indeed a bit confusing. Would be easier to grasp it if List & Expand were merged into single `Expand/List Operations` (or maybe `Expand/Collapse Operations`) as `Show/Hide`.

Then, one might also wonder `Show/Hide` what actually? Maybe rename as `Show/Hide Endpoints` or something like that...

**Comment by gdagitrep** [comment]
Is this issue resolved? (Is there a way to collapse operations after expanding?)

**Comment by webron** [comment]
We'll close the issue when it's resolved.

**Comment by webron** [comment]
Right, the `List Operations` is pretty much the opposite.
I get the confusion thought, we should try and improve it.

**Comment by webron** [comment]
This is no longer an issue with in the new UI.
