### ISSUE TITLE
Try it out request URL error

### ISSUE THREAD

**Issue by guozhenggang** [swagger-api/swagger-ui#1226]
when I click try it out in the page,It autogeneration request URL like "http://localhost:8080/manager_api/registApp?appName=appname".
But The real Url is "http://localhost:8080/{project-name}/manager_api/registApp?appName=appname".
I think somewhere can set project or base url,but not founded.
what should I do can fix this problem.thanks~~

**Comment by ponelat** [comment]
Have a look at the spec (I'm guessing you're using swagger 2.0?)
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields
Look under 'basePath'

**Comment by guozhenggang** [comment]
I use swagger1.2.I saw the spec but dot understand.   
you tell me what should I do.I'm not good at English.
Am I add a SwaggerPathProvider and override applicationPath() in my CustomJavaPluginConfig?

**Comment by guozhenggang** [comment]
I used SpringMVC+swagger-springmvc 1.0.2.jar to build my project

**Comment by webron** [comment]
@guozhenggang - please upgrade to the latest version of [springfox](https://github.com/springfox/springfox) (used to be swagger-springmvc). You would have to define the `{project-name}` as part of the path of the operations themselves and set that as a path parameter for the users to input.

**Comment by guozhenggang** [comment]
Have other way to fix my problem except upgrade to the latest version?

**Comment by webron** [comment]
You can probably do it with the same version as well, but you need to check with the people at springfox how to do it. This is a matter of the generated Swagger definition and not the way the ui works.

**Comment by guozhenggang** [comment]
thanks very much.How How to dependency springfox(swagger-springmvc) use maven?I saw the  https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields but didn't understood.

**Comment by guozhenggang** [comment]
oh~~I found this page:http://springfox.github.io/springfox/docs/current/

**Comment by webron** [comment]
Closing this issue for now.
