### ISSUE TITLE
referencing objects does not work with the model

### ISSUE THREAD

**Issue by ralphvanetten** [swagger-api/swagger-ui#1228]
When I add a reference to another object it does not show up in the model. But the weird thing is that when I wrap the reference in an array it works:

![selection_108](https://cloud.githubusercontent.com/assets/1533323/7410192/e7b3da50-ef2c-11e4-831a-b62dadc0ff73.png)

however it does show up in the model schema:

![selection_107](https://cloud.githubusercontent.com/assets/1533323/7410201/f5e67592-ef2c-11e4-94b6-7b097d76007d.png)

Is this a bug or is there something wrong with my swagger file. I tried master and develop_2.0, they both gave the same result.
A stripped down version of the swagger file is shown below:

```
{
   "paths" : {
      "/person" : {
         "post" : {
            "parameters" : [
               {
                  "in" : "body",
                  "name" : "body",
                  "schema" : {
                     "$ref" : "Person"
                  }
               }
            ],
            "tags" : [
               "person"
            ],
            "summary" : "Create new person",
            "responses" : {
               "200" : {
                  "schema" : {
                     "$ref" : "Person"
                  },
                  "description" : "Success"
               }
            }
         }
      }
   },
   "swagger" : "2.0",
   "basePath" : "/person",
   "info" : {
      "title" : "Person API",
      "version" : "1",
      "description" : ""
   },
   "tags" : [
      {
         "name" : "person",
         "description" : "Persons"
      }
   ],
   "definitions" : {
      "map1" : {
         "type" : "object",
         "properties" : {
            "anId1" : {
               "title" : "Id",
               "type" : "string"
            }
         },
         "title" : "map1"
      },
      "map2" : {
         "type" : "object",
         "properties" : {
            "anId2" : {
               "title" : "Id",
               "type" : "string"
            }
         },
         "title" : "map2"
      },
       "Person" : {
         "type" : "object",
         "title" : "Information about a person",
         "properties" : {
            "externalId1" : {
               "title" : "first",
               "type" : "object",
               "$ref" : "#/definitions/map1"
            },
            "externalId2" : {
               "title" : "second",
                "type" : "array",
                "items": {
                    "$ref" : "#/definitions/map2"
                }
            }
         }
      }       
   }
}
```

**Comment by webron** [comment]
@ralphvanetten - by definition you need to use full refs. So `"$ref" : "Person"` should be `"$ref" : "#/definitions/Person"`

**Comment by ponelat** [comment]
Yes, and you need to wrap your $ref in a schema... like so
@webron, is a $ref allowed to be outside a schema, like this case?

```javascript
"externalId1" : {
               "title" : "first",
               "type" : "object",
               "schema": {  // < -------------- This will make it work like you expect
                    "$ref" : "#/definitions/map1"
                } // ------------------- :)
            },
...
```
Then it'll work as expected (I tested :) )

**Comment by ralphvanetten** [comment]
Ah, yes, ofcourse... I knew it had to be some silly mistake..
Thanks!

**Comment by ponelat** [comment]
And by tested I mean with the latest source, so it'll be in a release soon :(
There was a bug with it, at some point. Apologies.

**Comment by ralphvanetten** [comment]
@ponelat oh, I guess was a bit optimistic with closing then :)

Anyway, I guess it is fixed in swagger-js? Can you tell which commit and is it documented somewhere how to use your own swagger-js instead of the default one used by swagger-ui?

Thanks.

**Comment by ponelat** [comment]
@ralphvanetten  Funny you should ask!, we wrote up this a fews day(s) ago....
DIY: https://github.com/swagger-api/swagger-ui/issues/1133#issuecomment-96991991
But first a take a look at
What @mohsen1 suggests (npm link) and what I want to add as a feature...
https://github.com/swagger-api/swagger-ui/pull/1220

**Comment by ponelat** [comment]
I made another guide, might be easier to maintain than the DIY version.
https://github.com/swagger-api/swagger-ui/pull/1220#issuecomment-97736915

**Comment by ralphvanetten** [comment]
When I use the develop_2.0 branch of both swagger-ui and swagger-js it is indeed fixed.

Thanks!

**Comment by webron** [comment]
So we can close the issue ;)

**Comment by ralphvanetten** [comment]
Actually. The correct solution is to use:

```
"externalId1" : {
                    "$ref" : "#/definitions/map1"
            }
```

As soon as you add anything else like `title` it does not work. See also https://github.com/swagger-api/swagger-js/issues/402
