### ISSUE TITLE
readOnly shown as "Optional" in POST Method

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-ui#1231]
I would think that read only fields should not be listed at all on POST methods.

```
      "RegistrationSerializer": {
         "required": [
            "email"
         ], 
         "id": "RegistrationSerializer", 
         "properties": {
            "url": {
               "description": null, 
               "required": false, 
               "readOnly": true, 
               "type": "string"
            }, 
            "id": {
               "description": null, 
               "format": "uuid", 
               "required": false, 
               "readOnly": true, 
               "type": "string"
            }, 
```

![image](https://cloud.githubusercontent.com/assets/51059/7424078/18e009da-ef6b-11e4-8ebe-6acf8963dd49.png)

**Comment by ponelat** [comment]
looks like a bug, are you seeing the fields getting sent with the request, or is it just in the UI?

**Comment by cancan101** [comment]
I am using the UI in read only mode so I don't know what actually would get sent. Should the UI be smart enough to no render readOnly fields for POST/PUT/PATCH or should I not sue a model in the spec for those end points with readOnly fields in it?

**Comment by webron** [comment]
Not quite a bug but rather an unimplemented feature.

https://github.com/swagger-api/swagger-js/issues/297

**Comment by cancan101** [comment]
I added this:
```diff
+            if (property.readOnly) {
+              html += ', <span class="propOptKey">readOnly</span>';
+            }
+
```
to the rendering to at least help the UI.

**Comment by webron** [comment]
Feel free to submit a PR ;)

**Comment by aslikeyou** [comment]
Hi, +1 for this issue. I made one model for post,put and get methods. I don't want user to see id field in post or update method.

**Comment by dolmen** [comment]
Related: #884.

**Comment by mprokopowicz** [comment]
Hi, 

a custom css to hide readOnly parameters in put/post does the job, but I have problem with the "example value" generated for put/post: readOnly properties are shown there, but should not.

**Comment by dolmen** [comment]
@mprokopowicz Could you post your CSS hack here?

**Comment by mprokopowicz** [comment]
@dolmen:

I've added following styles to swagger-ui. Perhaps there should be also `.patch .readOnly` selector.
```
.post .readOnly,
.put .readOnly {
    display: none;
}
```

**Comment by DerTomm** [comment]
Short question: I just tested swagger-ui version 2.1.4 and the problem is still existing. Are there any plans to include the CSS file hack in one of the next releases?

**Comment by DerTomm** [comment]
An answer would be great :-)

**Comment by advance512** [comment]
Was this solved?

**Comment by kzhou57** [comment]
It sounds like the issue still in latest version

**Comment by Pokerkoffer** [comment]
any updates on this? Fields annotated with ` @JsonProperty(access = JsonProperty.Access.READ_ONLY)` are still shown in the body where you can send the request.

**Comment by mattbryson** [comment]
Any update, still seeing this...

**Comment by webron** [comment]
This is unfortunately low on our priority list right now. Of course, PRs are welcome to change it, we're definitely not opposed to this getting fixed.

**Comment by mattbryson** [comment]
I've just create this PR  

https://github.com/swagger-api/swagger-ui/pull/3113

its on the 2.x branch, it strips read only properties from the JSON body.  What do you think?
