### ISSUE TITLE
Follow good practices: Make transition from hashbangs (#!) to javascript pushState

### ISSUE THREAD

**Issue by KrzysztofMadejski** [swagger-api/swagger-ui#1236]
http://stackoverflow.com/a/10355561

I still have problems with hashbangs being accumulated if SwaggerUI is not hosted on root url (/).
- Drop not maintained ba-bbq library during transition.

**Comment by KrzysztofMadejski** [comment]
BTW: I guess Backbone is handling transparently history using #! or push state depending on the browser: http://artsy.github.io/blog/2012/06/25/replacing-hashbang-routes-with-pushstate/

**Comment by KrzysztofMadejski** [comment]
Now I'm not so sure if routes and hard links done Backbone-way ie. /pet/addPet are a way to go. Why?
1. You need .htaccess to rewrite abstract urls to base file (a bit harder to deploy)
2. Views in SwaggerUI are not mutually exclusive, they are states that can coexist (finally I'm not firing Backbone actions while changing url, I still relyon bound js events)

Apart from that changing ba-bbq to better maintained https://github.com/browserstate/history.js/ is probably worth considering sometime in the future.

**Comment by ponelat** [comment]
Having pushState, would make the urls look cleaner for starters. And moving some more logic into routes would be nice. But it is something to look over, in more detail.

**Comment by fletcher91** [comment]
I'm new to API documentation so forgive me if this is nonsense.

I was playing around in the petstore example and noticed using a subroute did nothing. Recently I wrote an [article about 'semantic documentation'](http://medium.com/@fletcher91/semantic-documentation-1177d563783c) that boils down to the concept of getting the correct API docs when replacing the commonly used 'api' subdomain with 'doc'.

So, wouldn't it be useful, in addition to pushState, to let the UI show documentation based on its route? E.g. let `http://petstore.swagger.io/store/order` auto-scroll/expand the matching descriptions.

**Comment by KrzysztofMadejski** [comment]
As far as I remember that was working some time ago.


On 9 January 2016 at 15:48, Thom van Kalkeren <notifications@github.com>
wrote:

> I'm new to API documentation so forgive me if this is nonsense.
>
> I was playing around in the petstore example and noticed using a subroute
> did nothing. Recently I wrote an article about 'semantic documentation'
> <http://medium.com/@fletcher91/semantic-documentation-1177d563783c> that
> boils down to the concept of getting the correct API docs when replacing
> the commonly used 'api' subdomain with 'doc'.
>
> So, wouldn't it be useful, in addition to pushState, to let the UI show
> documentation based on its route? E.g. let
> http://petstore.swagger.io/store/order auto-scroll/expand the matching
> descriptions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-ui/issues/1236#issuecomment-170244519>
> .
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by fehguy** [comment]
This was fixed in 2.1.4.  If you try that version, you should see it working fine.  It was broken in master for a bit.

**Comment by webron** [comment]
Will be covered by #2884 (ignore the misleading title).
