### ISSUE TITLE
javascript error when trying to parse API with a GET /apis operation

### ISSUE THREAD

**Issue by olensmar** [swagger-api/swagger-ui#1237]
When attempting to parse the swagger 2.0 definition I first get a warning in the log:

The 'apis' tag conflicts with a SwaggerClient operation function/property name.  Use 'client.apis._apis' instead of 'client.apis.apis'.

and then an error:

spec-converter.js:90 Uncaught TypeError: Cannot set property 'apisGet' of undefined

Using the latest develop_20 branch

/Ole

**Comment by olensmar** [comment]
or should this be reported in swagger-js instead?

**Comment by webron** [comment]
Looks like.

**Comment by olensmar** [comment]
ok - let me see if I can reproduce this with just swagger.js

**Comment by olensmar** [comment]
ok - confirmed this is an issue in swagger-js - closing this and opening issue there...
