### ISSUE TITLE
Swagger UI Hangs on GET Response with a 200

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-ui#1242]
Hi,

If I enter this url (http://localhost:8080/api-utils/2020/geo/video/geolocation/001/011/gt/KGTV) into Chrome or IE, I get a 200 Response with the expected xml or json. If Swagger makes the same request, the UI hangs, spinner runs. However, if I look in my debugger, the Response code was 200 and the Response Body contains the expected xml or json.  Why is Swagger UI hanging. Needed inf?

<dependency>
   <groupId>com.wordnik</groupId>
   <artifactId>swagger-jaxrs_2.10</artifactId>
</dependency>

I am not sure what version of Swagger UI I am using. 

Thanks.

johnh

**Comment by webron** [comment]
We'd need the UI version though. Take a look at the top of the swagger-ui.js file.

It would also help if you share the Swagger definition of the operation that causes the issue.

**Comment by jharter** [comment]
Thanks for your help Ron. It was user error. Yet again.

**Comment by webron** [comment]
No worries, thanks for the update.
