### ISSUE TITLE
When the swagger url has query parameters the api listings urls don't work for v1.2 service descriptions

### ISSUE THREAD

**Issue by dilipkrish** [swagger-api/swagger-ui#1245]
Not a very high priority I suppose, and I can attempt to fix this with a patch. 

In springfox we have this notion of groups. So when we load a url in the swagger-ui if we had something like this `http://localhost:8080/api-docs?group=default` which returns the following resource listing.

`GET http://localhost:8080/api-docs?group=default`

``` json
{
   "apiVersion":"1.0",
   "apis":[
      {
         "description":"bundle",
         "path":"/default/bundle",
         "position":0
      }
   ],
   "authorizations":{

   },
   "info":{
      "contact":"blah blah",
      "description":"ACME Company API's",
      "license":"Apache License 2.0",
      "licenseUrl":"",
      "termsOfServiceUrl":"",
      "title":"ACME API's"
   },
   "swaggerVersion":"1.2"
}
```

When swagger ui tries to load the api listings, the urls it uses appends the api path to the base url. So the api listing requests end up with urls like this

`http://localhost:8080/api-docs?group=default/default/bundle`. it should actually be `http://localhost:8080/api-docs/default/bundle`

**Comment by webron** [comment]
We're focused on the new UI now, which no longer supports Swagger 1.2.
