### ISSUE TITLE
clientAuthorizations are ignored in case of multipart/form-data + file #407

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#1249]
from https://github.com/swagger-api/swagger-js/issues/407

**Comment by henkosch** [comment]
Any news on this bug? I'm having the same problem.

**Comment by fehguy** [comment]
This should be addressed in develop_2.0 as of #1296.  Please reopen if you still see an issue.

**Comment by z0mt3c** [comment]
Works fine, thanks.

**Comment by khozaif** [comment]
what do we need to do so that it works?

**Comment by webron** [comment]
@khozaif what's the issue?

**Comment by khozaif** [comment]
i am trying to upload the file using swagger with client authorization token , but it ignores the token.
