### ISSUE TITLE
Use Bootstrap frontend framework

### ISSUE THREAD

**Issue by dmyers** [swagger-api/swagger-ui#1250]
What do you think of using the [Bootstrap](https://github.com/twbs/bootstrap) frontend framework for Swagger UI?

I think it would make it easier to style as there are themes and variables you can use that would allow for easier customization of Swagger UI.

**Comment by jensoleg** [comment]
I have ported a bootstraped responsive layout to swagger UI. [Check out the github fork](https://github.com/jensoleg/swagger-ui)

This is an example
![Resp example 1](http://ecs.bobbytech.dk/api/images/Swagger_explorer.png)

.. and on small size window

![Resp example 1](http://ecs.bobbytech.dk/api/images/Swagger_explorer_min.png)

You can check it [here](http://ecs.bobbytech.dk/api) by entering a link to your own api swagger file

**Comment by dmyers** [comment]
@jensoleg That looks amazing! I'm incredibly impressed, nice work. It looks very much like Stripe and [Slate](https://github.com/tripit/slate) which I'm a big fan of. It looks to even have most of the Swagger UI functionality too like response schema/sample/codes and everything too and really fully featured. I hope this could be potentially brought into core, I really like Swagger and that design is much easier to digest and read than the current one. :+1: 

I'm going to play around with that, only thing I can think that might be a nice addition is OAuth. I like how Auth0 when you click Try it pops up that modal and asks for the credentials, rather than the current Swagger UI has the on/off switch, it's interesting UI/UX.

**Comment by who** [comment]
@jensoleg Wow, impressive work! :+1:

**Comment by RohanKumarBhoi** [comment]
@jensoleg  i want to customize ur ui to provide sandbox within the response division and response schema within description part.But i am unable to figure it out.Need Help....

**Comment by jensoleg** [comment]
@RohanKumarBhoi I'm not quite sure what your intention is. If you want to customize the UI you have to modify the handlebar templates / css and eventually the view js files. If you want to apply new layout to the response/schema you should look at swagger-client file. Be aware that the response sample and schema are rearranged when resizing the device/browser. It is not obvious how a rearrangement of the response sample/scheme will influence the current responsive design.

**Comment by RohanKumarBhoi** [comment]
@jensoleg Thanks for the help.I think i'm getting it and able to modify and reposition some of the stuffs

**Comment by webron** [comment]
Thanks for opening the ticket (@dmyers) and sharing the implementation (@jensoleg).

We're definitely looking into an overhaul, but can't give specifics (not hiding them, they just don't exist yet). This kind of feedback is helpful for the planning.

**Comment by zachguo** [comment]
@jensoleg Impressive. :+1:

**Comment by Smolations** [comment]
While I like the idea of using a known framework, I would opt for Google's Material Design instead of Bootstrap. That would be my vote.  =]

**Comment by ddaguro** [comment]
@jensoleg This is awesome!  We love it!

**Comment by mukgupta** [comment]
@jensoleg: Thanks for this. Looks much better than the original UI

**Comment by wing328** [comment]
@jensoleg :+1:

**Comment by felipemarques** [comment]
@jensoleg 
![image](https://cloud.githubusercontent.com/assets/2640656/12952449/a5a37ec4-cffd-11e5-93cb-eb1ffd5cbaa1.png)

**Comment by mavencode01** [comment]
+1

**Comment by konczak** [comment]
+1

**Comment by mvarblow** [comment]
+1

**Comment by Misiu** [comment]
@wing328 any news on this? Many of us would like to help with "refreshing" ui.

**Comment by wing328** [comment]
@Misiu is this task assigned to me??

**Comment by Misiu** [comment]
@wing328  sorry for that, I wanted to mention @webron because he wrote that team is considering new UI on 28'th May 2015.
@jensoleg version looks great, maybe team considers making official new UI based on it?

**Comment by webron** [comment]
@Misiu we're not, but there may be some news on that front in a couple of months. These things take time.

**Comment by cnmuc** [comment]
@jensoleg great work! looking forward to a stable version...

**Comment by webron** [comment]
We've just published 3.0. It's not based on Bootstrap, but React, still allowing for more customization.
