### ISSUE TITLE
Individual Text box / Select box Field for Request Payload

### ISSUE THREAD

**Issue by ramsunvtech** [swagger-api/swagger-ui#1256]
I would like to have a textbox / select box for each API Method Request PayLoad rather keeping one field for the whole payload like this below.

`Current Implementation `
```
                "parameters": [{
                    "in": "body",
                    "type": "string",
                    "name": "body",
                    "description": "Key Status",
                    "required": true,
                    "default": "available",
                }],
```

**Comment by webron** [comment]
@ramsunvtech - You need to describe the model in the spec. Right now you're using a string. This is not a ui issue but rather a documentation issue. Fix your documentation and you'd have a better representation of it in the ui.

**Comment by ramsunvtech** [comment]
@webron, You may be miss understood my issue. let me explain in detail. i have request payload of 3 values to register a employee.

```
{
    "empEmail": "john@adam.com".
    "empName": "John",
    "designation": "Director",
    "location": "Austin"
}
```

I need a text box for `empEmail`, `empName` and select box for `designation`, `location` to generate the above request payload.

**Comment by webron** [comment]
Take a look at our [pet store](http://petstore.swagger.io/). If you look at the [swagger.json](http://petstore.swagger.io/v2/swagger.json) you can see in various places a body parameter with the type of `Pet` or `User`. If you check their definitions, you will see they are structured to include several fields. You need to do something similar for your own model.

Keep in mind that would allow users to submit a structured JSON but it will not provide text boxes for the individual properties of the model. Currently, we don't have that functionality but there's an open PR we hope to merge for it.

**Comment by ramsunvtech** [comment]
@webron, In that case, Issue should not be closed since its not resolved and valid issue.

Link that issue where the PR raised !

**Comment by webron** [comment]
It should be closed because there's another open issue about it. Also, as long as you keep your definition as it is, it could never be converted to the model.

#1088 is the PR. #1083 is the issue.

**Comment by ramsunvtech** [comment]
Thanks @webron. This is what i expected. I don't mind in getting this issue closed since we have the similar issue is already opened.
