### ISSUE TITLE
2.1.2-M2 - missing "required" css class for required parameters

### ISSUE THREAD

**Issue by zyro23** [swagger-api/swagger-ui#1257]
just gave 2.1.2-M2 a spin.

required parameters `<input>`s are missing their `required` css class. this allows to "submit" requests even when required inputs are not filled. parameter validation is not applied or at least not visualized.

i do not know what exactly changed but it looks like `jQuery.html(...)` does not like elements having multiple `class` attributes (i am not talking about multiple classes but multiple `class="..."` directives which is not clean imho anyway).

markup: https://github.com/swagger-api/swagger-ui/blob/v2.1.2-M2/src/main/javascript/helpers/handlebars.js - instead of putting multiple classes into one `class` attribute, it looks like `class="parameter" class="required"`.

then, `jQuery.html(...)` does only use the first occurrence being `class="parameter"`: https://github.com/swagger-api/swagger-ui/blob/v2.1.2-M2/src/main/javascript/view/ParameterView.js#L40 - `class="required"` is lost/removed.

example fiddle showing the underlying behavior: http://jsfiddle.net/8a0z6vsL

thanks, zyro

**Comment by webron** [comment]
Confirmed bug.

**Comment by fehguy** [comment]
This broke with https://github.com/swagger-api/swagger-ui/commit/af39ae06037b1b6936594e91f11c9deee382055c
