### ISSUE TITLE
2.1.2-M2 - required model properties shown as optional in the model/signature view

### ISSUE THREAD

**Issue by zyro23** [swagger-api/swagger-ui#1260]
after updating to 2.1.2-M2, required properties are now shown as `optional` in the model/signature view.

this may be related to this change, i think: https://github.com/swagger-api/swagger-js/commit/1b4f031838771edb7caf4d85baf987faa73df0cb#diff-50e1922b706c52965ccc307155b8f407R265

debugging into that code, my `property` has no `required` attribute, but it is listed in the schemas `required` array, which was checked in the removed code (that was working).

i raised this in swagger-ui because i am not sure where the root problem lies. either the schema should be checked (swagger-js) or the property should in fact have that `required` attribute (swagger-ui? swagger-core?).

thanks, zyro

**Comment by webron** [comment]
This is indeed a regression.

**Comment by fehguy** [comment]
I think this was just fixed in https://github.com/swagger-api/swagger-ui/commit/95bf95e91faad6673d1c78d0ab75dc65594c2c17

Could you please try the develop_2.0 branch of swagger-ui?

**Comment by webron** [comment]
@fehguy - problem exists in develop_2.0 as well. Tested against the pet store.

**Comment by fehguy** [comment]
Yep, confirmed.  @ponelat can you please check this out?

**Comment by fehguy** [comment]
Addressed in https://github.com/swagger-api/swagger-js/commit/3f781683f6825f1b4f5f2165b09b9d5948c27b2a

**Comment by zyro23** [comment]
fix just verified with ui 2.1.5-M2. thanks! can be closed, i guess?

**Comment by fehguy** [comment]
Thanks for the follow-up
