### ISSUE TITLE
Workaround for conflicting headers?

### ISSUE THREAD

**Issue by rustybailey** [swagger-api/swagger-ui#1261]
Is there any way to get around conflicting header names? I am using 2-legged OAuth2 in my API, so I have documented the token route which uses an "Authorization" header with "Basic [key]" and the route returns a token. However every other route uses a header that is "Authorization: Bearer [token]" which is implemented using the method below:
``` js
        var accessToken = new SwaggerClient.ApiKeyAuthorization("Authorization", authHeader, "header");
        window.swaggerUi.api.clientAuthorizations.add("key", accessToken);
```
It seems that when that Authorization header is set globally, there is no way for a header with the same name to be overwritten on a route-by-route basis. My only solution right now is disabling the "Try It Now" button for the token route. Is there a way for both of them to exist together while still be able to prepopulate a token?

**Comment by rustybailey** [comment]
After consulting with some members on the #swagger irc, the solution was to set up securityDefinitions in my swagger.json, set "oauth2" as the global security and set "basic" as the security for the token route. Everything works as expected now.

**Comment by webron** [comment]
Thanks for providing the information.
