### ISSUE TITLE
Couple of new issues with model schema display in v2.1.2-M2

### ISSUE THREAD

**Issue by xiehan** [swagger-api/swagger-ui#1263]
This is a continuation of #1147 - most of the original issues have been resolved but now I'm seeing some new, interesting issues. All of these were tested with v2.1.2-M2 in Chrome Canary. Our full Swagger doc is at http://api.npr.org/documentation/beryllium/api-docs which follows the v1.2 Swagger spec.
 
 
 
**Issue 1: Swagger-UI seems to insist on turning empty arrays into arrays of empty objects.**

I have a model where two of the properties are literally just empty arrays 100% of the time and so we've tried to document them as such. The relevant bit of our Swagger doc (not showing nested models etc.) is as follows:

```json
        "UserDocument": {
            "id": "UserDocument",
            "description": "Class UserView Constructs the JSON output for identity services around the user   Actual Swagger model declarations:",
            "required": [
                "attributes",
                "errors",
                "href",
                "items",
                "links",
                "version"
            ],
            "properties": {
                "items": {
                    "description": "Not used, ignored on a PUT",
                    "type": "array"
                },
                "links": {
                    "description": "A list of links, not used by the Identity Service; ignored on a PUT",
                    "$ref": "EmptyObject"
                },
                "attributes": {
                    "description": "Object; see description of a user object below",
                    "$ref": "UserData"
                },
                "version": {
                    "description": "The version of the Collection.Doc+JSON spec being used",
                    "type": "string",
                    "defaultValue": "1.0"
                },
                "href": {
                    "description": "A URL representation of the resource; should generally be ignored by clients unless noted otherwise",
                    "type": "string"
                },
                "errors": {
                    "description": "A list of encountered errors, ignored on POST, PUT",
                    "type": "array"
                }
            }
        }
```

In 2.1.8-M1, these looked as follows:

![screen shot 2015-05-11 at 12 04 36 pm](https://cloud.githubusercontent.com/assets/855115/7569330/fde54712-f7d5-11e4-8c39-ebeee07e6e56.png)

-- which is a little bit awkward (array of null?) but the other tab looked better:

![screen shot 2015-05-11 at 12 04 56 pm](https://cloud.githubusercontent.com/assets/855115/7569336/0b58165e-f7d6-11e4-88ce-c8b32e8a6205.png)

-- that seems more like what I'd expect from this schema definition; indicate that it's an array but say nothing else.

However, this is what's happening in 2.1.2-M2:

![screen shot 2015-05-11 at 12 06 43 pm](https://cloud.githubusercontent.com/assets/855115/7569364/3aebeac6-f7d6-11e4-9c32-42d847d75587.png)

-- it seems to insist on turning this into an array of objects. Now, this I could live with if I absolutely had to, but what's happening on the other tab is clearly more unacceptable:

![screen shot 2015-05-11 at 12 07 47 pm](https://cloud.githubusercontent.com/assets/855115/7569385/641e8d72-f7d6-11e4-9950-72a999a63c93.png)

-- it's giving these empty objects random new names like "Inline Model 1". This is a big no-no for us.

---

**Issue 2: Property descriptions of nested models seem to have gone missing.**

You may have already noticed this in the previous screenshot. Same schema as the last issue (the full thing is at http://api.npr.org/documentation/beryllium/api-docs/identity).

Here's v2.1.8-M1:

![screen shot 2015-05-11 at 12 16 10 pm](https://cloud.githubusercontent.com/assets/855115/7569555/9032636a-f7d7-11e4-8e6f-23cf6034618d.png)

![screen shot 2015-05-11 at 12 17 55 pm](https://cloud.githubusercontent.com/assets/855115/7569603/d2e32a8c-f7d7-11e4-9c2c-30bb5b34756a.png)

Here's v2.1.2-M2:

![screen shot 2015-05-11 at 12 16 21 pm](https://cloud.githubusercontent.com/assets/855115/7569560/973c9266-f7d7-11e4-8089-9bbec7fb86cf.png)

![screen shot 2015-05-11 at 12 18 05 pm](https://cloud.githubusercontent.com/assets/855115/7569606/d6cd2ecc-f7d7-11e4-9896-ba0e2b899cd0.png)

What I can gather from this is that the description seems to be going missing specifically for nested models; it seems to be fine for arrays and primitives.

---

Those were the only issues I could find with model displays. Kudos for knocking out everything else from my last ticket! :)

**Comment by webron** [comment]
@xiehan - thank you for your bug reports. They are a delight to read and we really appreciate the effort you put into them.

**Issue 1**
Unfortunately, there's not much we can do about it. The definition of `"type": "array"` without an accompanying `"items"` property is invalid by the Swagger specification (whether version 1.2 or 2.0). To overcome this, we assume the type of the array contents is just `object`. There's really no way around it. Since the `object` is an undefined model, it translates to `[Inline Model X]`.

**Issue 2**
That indeed seems to be a bug that should be handled.

**Comment by fehguy** [comment]
This should be addressed, and as @webron stated there were some errors in your spec file.  Please reopen if you still see issues!
