### ISSUE TITLE
Swagger-UI is inserting 200 response codes that don't exist (v2.1.2-M2)

### ISSUE THREAD

**Issue by xiehan** [swagger-api/swagger-ui#1266]
This might be related to #1265 but I pulled it out as its own separate issue because Swagger-UI is inserting data that isn't in the original API doc, which could potentially be harmful to users. Tested with v2.1.2-M2 in Chrome Canary. Our full Swagger doc is at http://api.npr.org/documentation/beryllium/api-docs which follows the v1.2 Swagger spec.

I have two different examples of this.

**Example 1:** (from http://api.npr.org/documentation/beryllium/api-docs/identity)

``` json
            "path": "/identity/v2/stations",
            "description": "Set a user's favorite stations",
            "operations": [
                {
                    "method": "PUT",
                    "summary": "Update the logged-in user's favorite station(s)",
                    "nickname": "updateStations",
                    "parameters": [
                        ...
                    ],
                    "responseMessages": [
                        {
                            "code": 201,
                            "message": "Successfully updated the user primary station or there was no change",
                            "responseModel": "UserDocument"
                        },
                        {
                            "code": 400,
                            "message": "A bad request; generally, one or more parameters passed in were incorrect or missing",
                            "responseModel": "ErrorDocument"
                        },
                        {
                            "code": 401,
                            "message": "The authentication failed",
                            "responseModel": "ErrorDocument"
                        },
                        {
                            "code": 429,
                            "message": "The client has exceeded the number of daily calls as per their rate limit. For now, this only applies to prototype applications and untrusted clients. Trusted clients will never be rate-limited, nor will any production apps.",
                            "responseModel": "ErrorDocument"
                        },
                        {
                            "code": 500,
                            "message": "A server error",
                            "responseModel": "ErrorDocument"
                        },
                        {
                            "code": 503,
                            "message": "The system is undergoing maintenance and we are unable to fulfill this request. Look for Retry-After in the header to see the predicted time the system will be back up.",
                            "responseModel": "ErrorDocument"
                        }
                    ],
                    "notes": "Right now, only the primary station can be changed. Previously selected stations will not be deleted, but the new station will be moved to first in the array."
                }
```

Here it is in v2.1.8-M1:

![screen shot 2015-05-11 at 1 31 06 pm](https://cloud.githubusercontent.com/assets/855115/7570917/02a928fc-f7e2-11e4-8211-2f68e2a5e66c.png)

Here it is in v2.1.2-M2:

![screen shot 2015-05-11 at 1 31 37 pm](https://cloud.githubusercontent.com/assets/855115/7570928/13c4ce98-f7e2-11e4-8deb-6baca99baf61.png)

**Example 2:** (from http://api.npr.org/documentation/beryllium/api-docs/authorization)

``` json
            "path": "/authorization/v2/authorize",
            "description": "Get an HTML-based login/signup form to authorize an application",
            "operations": [
                {
                    "method": "GET",
                    "summary": "Show a web-based login/signup form to a user",
                    "nickname": "getAuthorizationPage",
                    "parameters": [
                        ...
                    ],
                    "responseMessages": [
                        {
                            "code": 302,
                            "message": "The correct parameters were passed in and we are redirecting to the authentication page; OR, a valid `redirect_uri` was supplied but there was another error, and the error type and message are embedded in the querystring."
                        },
                        {
                            "code": 400,
                            "message": "A bad request; generally, one or more parameters passed in were incorrect or missing. This error will only be shown if the client did not pass in a valid `redirect_uri`; otherwise, all errors will be returned as 302s to the supplied `redirect_uri`, with the error type and message embedded in the querystring.",
                            "responseModel": "SimpleError"
                        },
                        {
                            "code": 401,
                            "message": "The client credentials were invalid (i.e., the `redirect_uri` does not match what we have stored for this client) or the authorization server denied the request. This error will only be shown if the client did not pass in a valid `redirect_uri`; otherwise, all errors will be returned as 302s to the supplied `redirect_uri`, with the error type and message embedded in the querystring.",
                            "responseModel": "SimpleError"
                        },
                        {
                            "code": 500,
                            "message": "There was an unspecified server error. This error will only be shown if the client did not pass in a valid `redirect_uri`; otherwise, all errors will be returned as 302s to the supplied `redirect_uri`, with the error type and message embedded in the querystring.",
                            "responseModel": "SimpleError"
                        },
                        {
                            "code": 503,
                            "message": "The system is undergoing maintenance and we are unable to fulfill this request. This error will only be shown if the client did not pass in a valid `redirect_uri`; otherwise, all errors will be returned as 302s to the supplied `redirect_uri`, with the error type and message embedded in the querystring.",
                            "responseModel": "SimpleError"
                        }
                    ],
                    "notes": "..."
                }
```

Here it is in v2.1.8-M1:

![screen shot 2015-05-11 at 1 34 39 pm](https://cloud.githubusercontent.com/assets/855115/7570991/93275a34-f7e2-11e4-8705-b50358d9a70f.png)

Compared to v2.1.2-M2:

![screen shot 2015-05-11 at 1 34 50 pm](https://cloud.githubusercontent.com/assets/855115/7570998/99dcf3c0-f7e2-11e4-829e-ff7a5ee973e3.png)

(There is nothing after the 503, just the 'Try it out' button.)

**Comment by webron** [comment]
As explained in the other issue, this is a limitation of migrating 1.2 definitions to 2.0. We are left to assume a successful response carries a 200 response and there's not much we can do about it.

If you want to use the latest version of the UI and have it display correctly, you'll have to upgrade to Swagger 2.0.

**Comment by xiehan** [comment]
@webron Unfortunately Swagger-PHP doesn't support v2.0 (I know it's in progress but it looks like it's still a long way away from being fully-featured and stable) so upgrading is simply not an option for us. We can live with some of the other bugs but if this issue can't be resolved then it's a dealbreaker for us -- there's no way we can upgrade Swagger-UI if it's creating response codes that don't exist.

**Comment by webron** [comment]
I just don't see how we can solve it otherwise.

**Comment by fehguy** [comment]
@webron It seems like we can assume that the lack of a response type in the operation means there's no 200 response code?  It's not even marked as `void`--it's simply absent.  Would that work?

**Comment by webron** [comment]
As said in the other issue, `type` is mandatory. Setting it to `void` is a bare minimum.

**Comment by fehguy** [comment]
Yes, but it's not in this example, or I'm missing it.  Since the conversion logic is handling some malformed specs, perhaps this is an example of how we can handle non-200 response codes.  It's not 1.2 spec compliant but it may accomplish the goal

**Comment by webron** [comment]
@fehguy - fair enough, but there are three cases. One where there's no `type` at all, one where there's a 200 definition *and* a `type` and one where there's a `type` which represents a non-200 response (like 201) which is also explicitly mentioned. To serve @xiehan's needs, I think the solution would be to ignore the `type`' of the operation altogether, but that will not necessarily work for other 1.2 definitions.

@xiehan - please let us know if the above statement is correct (regarding the interpretation of the type).

**Comment by xiehan** [comment]
@webron @fehguy You're mostly right. I will point out that the situation where the `type` was missing altogether for the "updateStations" endpoint was an accidental oversight -- it should have the same `type` as the 201 response (and I've since added it back in to go out with our next code release). This is a relic of the fact that there are multiple developers maintaining these docs and Swagger-PHP doesn't throw an error if you don't specify a `type` (which it does for other fields like `nickname` -- which suggests that there are others out there who didn't catch that this is a hard requirement).

Which leads me to "getAuthorizationPage" where the success response is a 302 -- this one was my bad; I didn't realize `type` was a requirement and assumed nothing should be put there because in this case there truly is no response model; I had just completely missed that there is the option of a `type="void"`. Again this is somewhat an artifact of Swagger-PHP not enforcing the `type` requirement, but I digress.

In any case, I can add the `type="void"` if it helps; that should at least reduce it down to 2 use cases, one where the success response is 200, and one where it isn't (the other options are 201, 202 and 302). The ones in the 200-202 range will always have a `type` and a `responseModel` set, but the 302 wouldn't (it'd have a `type="void"`and no `responseModel`).

**Comment by webron** [comment]
@xiehan - thanks for the update.

I think the main problem is that most people, when using 1.2, did not bother explicitly mentioning the successful response in the `responses` on top of the return type, even though they couldn't explicitly mention the return type. In fact, that's one of the reasons we made the design change in 2.0 to force people to mention the return type. 

As long as we provide support for one use case, the other will suffer. Perhaps the only way to support it is by providing a configuration option of a sort. Even if not exposed clearly, and we can provide a guide to set it.

**Comment by mikewatt** [comment]
By synthesising a 200 response where one wasn't explicitly declared, the only option you have to remove it when using a 2.0 UI with a 1.2 definition is to upgrade the whole definition to 2.0. On the other hand, if the 200 response wasn't added automatically, it would be easy enough to add an explicit 200 response to your 1.2 definition if you really wanted it to show up in a 2.0 UI.

If `type` were ignored altogether, it seems like you could still tweak a 1.2 definition to display correctly after conversion.

**Comment by webron** [comment]
Right, but it seems most people do not declare the the successful responses explicitly, so we'd be forcing more people to manipulate their Swagger definitions.

There's also always the alternative using the 2.0.24 version of the UI, which is 1.2 and earlier only.

**Comment by webron** [comment]
Right now, the only way I can think of solving this is by having a flag that affects the behavior.

**Comment by zuk** [comment]
For anyone coming here from Google, the workaround for now seems to be to roll back to Swagger UI v2.0.24.

**Comment by webron** [comment]
It's unlikely to change at this point. Also, version 3.0 no longer supports 1.2 and older.
