### ISSUE TITLE
Required enum parameters don't display the same as everything else (v2.1.2-M2)

### ISSUE THREAD

**Issue by xiehan** [swagger-api/swagger-ui#1268]
This is minor and I'm assuming is just a one-line change; it's just visually pretty jarring on a page like this:

![screen shot 2015-05-11 at 1 56 11 pm](https://cloud.githubusercontent.com/assets/855115/7571429/9f35abe8-f7e5-11e4-9f46-c73a963475f4.png)

(Description is bolded for every other required parameter type, just not for enums.)

**Comment by webron** [comment]
Just to be clear, the original is a 1.2 definition, right?

**Comment by xiehan** [comment]
Yes

**Comment by fehguy** [comment]
Can you please retry this with 2.1.3-M2 of swagger-ui?  Just released it.

**Comment by xiehan** [comment]
@fehguy Still looks exactly the same to me:

![screen shot 2015-05-13 at 11 39 04 am](https://cloud.githubusercontent.com/assets/855115/7614428/b88aced6-f964-11e4-8065-d6e3111dd310.png)

**Comment by xiehan** [comment]
Fixed by PR #1281

**Comment by webron** [comment]
@xiehan - thanks for the help, much appreciated.
