### ISSUE TITLE
Relative "base URL" display not useful for v1.2 spec (v2.1.2-M2)

### ISSUE THREAD

**Issue by xiehan** [swagger-api/swagger-ui#1269]
Tested with v2.1.2-M2 in Chrome Canary. Our full Swagger doc is at http://api.npr.org/documentation/beryllium/api-docs which follows the v1.2 Swagger spec.

N.B. We are using Swagger-PHP to drive our API docs so this could also be related to zircote/swagger-php#181 (we no longer have a `basePath` set in our resource listing -- not sure if that makes a difference)

In V2.1.8-M1:

![screen shot 2015-05-11 at 2 10 21 pm](https://cloud.githubusercontent.com/assets/855115/7571725/8a09089e-f7e7-11e4-88bf-2b9ba96c3b63.png)

In V2.1.2-M2:

![screen shot 2015-05-11 at 2 10 32 pm](https://cloud.githubusercontent.com/assets/855115/7571747/a1d83e36-f7e7-11e4-8027-2ea79b986ef4.png)

It looks like the decision was made to use relative URLs instead of absolute URLs for this base URL...? But for those of us using the v1.2 spec that's... not very useful.

It's also worth pointing out that for our production site (http://dev.npr.org/api) we've somewhat reskinned Swagger-UI, mainly consisting of wholesale replacing the header, and so the base URL part is the only place on the screen where users can see the URL of the Swagger docs being loaded (without going into the source code). I liked that about V2.1.8-M1 and would hate to see that go away...

**Comment by webron** [comment]
@xiehan - can you please retest with the latest master? I doubt it's been fixed but want to make sure. If it hasn't, I'll mark it as a bug/feature.

**Comment by mikedaly** [comment]
I can confirm that it has not been fixed, as I have this problem as well. Using 2.1.0 release.

**Comment by webron** [comment]
It's unlikely to change at this point. Also, 3.0 has dropped support for 1.2 and older.
