### ISSUE TITLE
Missing response headers after clicking "try it" on requests.

### ISSUE THREAD

**Issue by codeHatcher** [swagger-api/swagger-ui#1271]
When I host the UI-docs on a different domain and click "try it" I don't get the response headers back even though the body and status code come back.
![screen](https://cloud.githubusercontent.com/assets/5360982/7583535/255c122e-f84b-11e4-9cb4-9fabec9509cb.png)
When I host the UI-docs on the same domain and click "try it" it works just fine.

I have set up my node server to allow CORS.

@webron might have more information to add to this.

**Comment by codeHatcher** [comment]
Just to be clear I was expecting the 401 response, that is not a mistake.

**Comment by fehguy** [comment]
I believe this is a dup of #1117
