### ISSUE TITLE
Swagger UI config for booleanValues gone

### ISSUE THREAD

**Issue by dmyers** [swagger-api/swagger-ui#1272]
Did the option to set the config for `booleanValues` change? The readme still references it.

**Comment by webron** [comment]
Looks like a regression.

**Comment by fehguy** [comment]
@webron can you explain this more?

**Comment by webron** [comment]
Sure, from https://github.com/swagger-api/swagger-ui#parameters - 
![screenshot 2015-05-13 15 57 49](https://cloud.githubusercontent.com/assets/241629/7610862/d6b426a4-f988-11e4-9a57-66b016955d04.png)

It seems this feature was lost at some point. We can either declare the feature obsolete or fix it. There's no reference in the current code anywhere to `booleanValues`.

**Comment by Jonnx** [comment]
This is still not resolved. is there a fix in the works or a patch that we apply manually?

**Comment by rcjohnson** [comment]
Found this patch from a while ago where the booleanValues was added.  May try to create a pull request to add this back, but wanted to put this out there as it helped us work around the issue.

https://git.framasoft.org/databrew/swagger-ui/commit/8d3a5010b4872615934b09cd1fd8bd1c18192b26

**Comment by fehguy** [comment]
Please consider sending a PR and it'll get in shortly.  A new swagger-js client is just about ready.

**Comment by curtisgibby** [comment]
I'd love for this issue to be resolved.

**Comment by alexeyauslender** [comment]
Hey ,there.Is anybody going to fix it or this parameter is not relevant anymore ?

**Comment by fehguy** [comment]
It looks like a PR could help get this resolved.

**Comment by webron** [comment]
We've completely dropped this feature in 3.X.
