### ISSUE TITLE
How to link a section to different section in different uri

### ISSUE THREAD

**Issue by Ckim15** [swagger-api/swagger-ui#1279]
Hi,

I am struggling with link an object to its detail information in the same swagger file.

I am currently using html hyperlink.

Here are what I did:

I have a link in GeoAddress definition to see PostalAddress detail in different uri in the same swagger.yaml ( first image);

when I clicked on PostalAddress link, the url on the address bar changed to position where PostalAddress tab should be opened, but it didn't open automatically until I clicked on refresh button/ F5(second image);

![linktopostaladdress](https://cloud.githubusercontent.com/assets/10535043/7613729/11349b14-f958-11e4-8355-58a8804fc6ed.png)
![postaladdressdetail](https://cloud.githubusercontent.com/assets/10535043/7613744/148d3a46-f958-11e4-8c0e-c149fc92bfa9.png)

**Comment by webron** [comment]
I don't really understand what you're trying to do.

**Comment by Ckim15** [comment]
I need to link a note to its details.

Best Regards,
Chantha Kim

**Comment by webron** [comment]
You have to provide more details. I don't know what you mean by 'note', nor 'details'. If don't provide a full description of what you want to achieve, we simply won't be able to help.

**Comment by eli-jordan** [comment]
I think what @Ckim15 is asking, is how to create a hyperlink from the description of one resource to another resource in swagger ui. If this is correct, it is a problem I also ran into, and solved it by using a link like <a href=".#!/{group}/{nickname}">the other resource<a>. I would be interested to know if there is a better way to do this?

**Comment by eli-jordan** [comment]
hahah GitHub created a hyperlink, but you get the idea

**Comment by eli-jordan** [comment]
I.e. href=".#!/{group name}/{nickname}"

**Comment by webron** [comment]
Can't think of another way of doing it.

**Comment by webron** [comment]
For now, this can't really be done because it relies on how the UI generates the links which could change at any time. There should be an issue on swagger-spec that may help it, but it's not part of the spec just yet - https://github.com/swagger-api/swagger-spec/issues/239.
