### ISSUE TITLE
Updating to V2: Request URL has added extra domain. 

### ISSUE THREAD

**Issue by UV-Collin** [swagger-api/swagger-ui#1283]
I'm working on updating to V2, and I am experiencing a problem where there is two instances of the domain being added to the request url. 

The url is coming out like this: 

http://localhost:80/localhost:8080/foo/bar?...

Here is what my json looks like: 

    {
      "apiVersion":"0.2",
      "swaggerVersion":"1.1",
      "basePath":"http://localhost:8080/foo",
      "resourcePath":"/bar",
      "apis":[
        {
          "path":"/bar/test",

**Comment by fehguy** [comment]
Hi @UV-Collin can you share more?  Specifically, what is your api declaration (under /bar/test)?

**Comment by UV-Collin** [comment]
Hi @fehguy. 

    {
  "apiVersion":"0.2",
  "swaggerVersion":"2.1.1-M2",
  "basePath":foo.org",
  "resourcePath":"/gps",
  "apis":[
    {
      "path":"/gps/data/position/{station}/v2",
      "description":"Position operations",
      "operations":[
        {
          "httpMethod":"GET",
          "summary":"Get the position time series for the specified station.",
          "notes":"Retrieves the daily position time series for the station identified by  four character id. <p><b>Returns:</b> DateTime, North(mm), East(mm), Vertical(mm), North Std. Dev.(mm), East Std. Dev.(mm), Vertical Std. Dev.(mm), Solution",
          "responseClass":"string",
          "nickname":"getPositionByStationId",
          "produces": ["text/csv"],
          "parameters":[
            {
              "name":"station",
              "description":"The four character station identifier.",
              "paramType":"path",
              "required":true,
              "allowMultiple":false,
              "dataType":"string",
              "defaultValue":"P378"
            },
            {
              "name":"referenceFrame",
              "description":"The reference frame.",
              "paramType":"query",
              "required":true,
              "allowableValues":{
                "values":[
                  "nam08",
                  "igs08"
                ],
                "valueType":"LIST"
              },
							"defaultValue":"nam08",
              "allowMultiple":false,
              "dataType":"string"
            },
						{
							"name":"analysisCenter",
							"description":"The analysis center.",
							"paramType":"query",
							"required":"false",
							"allowableValues":{
								"values":[
									"pbo",
									"cwu",
									"nmt",
									"unr"
								],
								"valueType":"LIST"
							},
							"defaultValue":"pbo",
							"allowMultiple":false,
							"dataType":"string"
						},
            {
              "name":"starttime",
              "description":"An ISO 8601 datetime indicating the start of the search range.",
              "paramType":"query",
              "required":true,
              "allowMultiple":false,
              "dataType":"Date",
              "defaultValue":"2006-01-01T00:00:00"
            }, 
            {
              "name":"endtime",
              "description":"An ISO 8601 datetime indicating the end of the search range.",
              "paramType":"query",
              "required":true,
              "allowMultiple":false,
              "dataType":"Date",
              "defaultValue":"2012-03-01T00:00:00"
            }, 
            {
              "name":"tsFormat",
              "description":"The output time format. unixEpochMs is the no. of milliseconds from 1970-01-01T00:00:00.",
              "paramType":"query",
              "required":false,
              "allowableValues":{
                "valueType":"LIST",
                "values":[
                  "iso8601",
                  "unixEpochMs"
                 ]
               },
              "defaultValue":"iso8601",
              "allowMultiple":false,
              "dataType":"string"
            },
            {
            "name":"stdDevRange",
            "description":"Provides the values calculated by adding and subtracting 1 standard deviation from each corresponding value.",
            "paramType":"query",
            "dataType":"boolean",
            "allowMultiple":false,
            "required":false,
            "defaultValue":"false"
            }
          ],
          "errorResponses":[
            {
              "code":404,
              "reason":"Invalid Station Id supplied."
            },
            {
              "code":400,
              "reason":"Invalid query parameters."
            }
          ]
        }
      ]
    },

**Comment by fehguy** [comment]
Hi, using this:

```
"swaggerVersion":"2.1.1-M2"
```

Will definitely cause problems, as the `swaggerVersion` is responsible for telling the UI how to render.  Also this looks like a 1.2 spec.  Are you sure you posted the right one?  If you have a 1.2 spec, you can use the codegen--even the online one--to convert it to 2.0.

**Comment by UV-Collin** [comment]
Thanks @fehguy 

I am currently trying to update to 2.0 so I can have schemaless urls. I got the swaggerVersion from the swagger-ui.js file. 

After reading the swagger codegen docs, I'm not sure I understand how that works. I can input my current json file like I posted above, and it will update to a version compatible with 2.0?

**Comment by webron** [comment]
@UV-Collin - you're confusing versions of different things. Is your current Swagger definition generated from code or manually written?

**Comment by UV-Collin** [comment]
@webron The Swagger definition is the json file I have as an example above? If so the definition is manually written.

**Comment by webron** [comment]
Okay, so we have tools that can take those definitions and convert them to 2.0 for you. Is that what you're looking for?

**Comment by UV-Collin** [comment]
Thanks @webron that is what I am looking for.

**Comment by webron** [comment]
Take a look at [swagger-tools](https://github.com/apigee-127/swagger-tools), specifically https://github.com/apigee-127/swagger-tools/blob/master/docs/CLI.md#convert.

**Comment by webron** [comment]
@UV-Collin - any updates?

**Comment by UV-Collin** [comment]
@webron I attempted to get my specification up to v2 using the swagger-tools, I'm thinking I will have to manually update the spec to v2.

**Comment by webron** [comment]
What happened with the swagger-tools update?

**Comment by webron** [comment]
Closing this one for lack of response. Please reopen if needed.
