### ISSUE TITLE
Reusable Parameters are not displaying properly on Swagger UI

### ISSUE THREAD

**Issue by rsung** [swagger-api/swagger-ui#1286]
Many of my APIs have common parameters so I want to define a reusable parameter to be referenced in each endpoint definition. 

This is similar to the issue covered in http://stackoverflow.com/questions/27005105/swagger-use-ref-to-pass-a-reusable-defined-parameter.

The syntax appears to validate correctly in the editor but the ui display them as empty row in parameter definition.

![5-14-2015 11-06-33 am](https://cloud.githubusercontent.com/assets/471863/7634517/64aa5c94-fa29-11e4-80e1-18be41bad491.png)

Please advise.

**Comment by webron** [comment]
Which version have you tried it with?

**Comment by rsung** [comment]
Thanks for the quick reply.  I thought I was running the latest version though https://registry.hub.docker.com/u/marcellodesales/swagger-editor/ (docker container) but it wasn't.

When I built one directly from https://github.com/swagger-api/swagger-editor and used that, the issue above went alway.

Sorry for the noise.  Thanks.

**Comment by webron** [comment]
@rsung - for future reference, you were actually looking for https://github.com/swagger-api/swagger-editor.
