### ISSUE TITLE
Uncaught TypeError: Cannot read property '$ref' of undefined (Swagger-spec 1.2)

### ISSUE THREAD

**Issue by ksimka** [swagger-api/swagger-ui#1287]
```
Uncaught TypeError: Cannot read property '$ref' of undefined
SwaggerOperation @ swagger-client.js:2109
SwaggerResource.addOperations @ swagger-client.js:1862
SwaggerResource.addApiDeclaration @ swagger-client.js:1791
obj.on.response @ swagger-client.js:1739
JQueryHttpClient.execute.obj.complete @ swagger-client.js:2833
p.Callbacks.k @ jquery-1.8.0.min.js:2
p.Callbacks.l.fireWith @ jquery-1.8.0.min.js:2
y @ jquery-1.8.0.min.js:2
p.support.ajax.p.ajaxTransport.send.d @ jquery-1.8.0.min.js:2
```

swagger-client.js:2108
```js
if (type === 'array') {
      type = 'array[' + (param.items.$ref ? param.items.$ref : param.items.type) + ']';
    }
```

**Comment by webron** [comment]
@ksimka - can you also share your Swagger definition?

**Comment by ksimka** [comment]
@webron, I'm sorry, looked into the definition, it's my fault: 'items' is not set when using 'type'='array'.

**Comment by websusk** [comment]
I have tried latest "master" and "2.1.1" and still see this issue with swagger spec 2.0.  Any pointers on how to get past this?

**Comment by webron** [comment]
Do you have a 1.2 spec?

**Comment by websusk** [comment]
I can get one, and it worked with 1.2 but upgraded system to 2.0 spec.  Should I just stay at 1.2 if I want to use this for the time being?  Is there a fix?

**Comment by webron** [comment]
No, but this issue is talking about a problem with a 1.2 definition. If you have 2.0, the cause could be different. How is it generated?

**Comment by websusk** [comment]
Oh, sorry, just went with the same error message, sorry about that.  I'm generating it from the kongchen/swagger-maven-plugin

**Comment by webron** [comment]
Then it looks like there's a bug with it. My guess is somewhere you have `"type": "array"`, but no "items" alongside it.

**Comment by websusk** [comment]
Could this be the cause, out of order of attributes, as "items" is not the next one?

"tags" : {
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "$ref" : "#/definitions/Tag"
          }
        },

**Comment by webron** [comment]
No, order is irrelevant.

**Comment by websusk** [comment]
Or using ENUM issue?

"permissionSet" : {
          "type" : "array",
          "uniqueItems" : true,
          "items" : {
            "type" : "string",
            "enum" : [ "VAL1", "VAL2", "VAL3" ]
          }
        },

**Comment by websusk** [comment]
Does it have to have $ref in the "items" array?

"schema" : {
            "type" : "array",
            "items" : {
              "type" : "integer",
              "format" : "int64"
            }
          }

**Comment by webron** [comment]
I meant what I said :) An "array" with no "items" :)

**Comment by websusk** [comment]
Ha!  Ok, so you mean this "items" should be a JSON array, so it's missing the "[" "]"

"schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }

**Comment by websusk** [comment]
Can you give me an example of a "good" Json format?

**Comment by webron** [comment]
no, I mean it would not exist. at all. you've given here several good examples. I've explained what can cause the problem.

**Comment by websusk** [comment]
I'm back to Earth now, was searching for the wrong string....so I have stuff in there with "type" : "array" and nothing else.  So is this bad format on swagger json generation part then?

**Comment by webron** [comment]
Yes. It may have been solved by a newer version of swagger-maven-plugin, and if you're already using the latest, then you should file a bug with that project.

**Comment by websusk** [comment]
Thank you very much, lovely work by the way. Cheers.

**Comment by maxatbrs** [comment]
I am having a similar issue, anyone able to help me out?

https://github.com/swagger-api/swagger-ui/issues/1677

**Comment by vijayaratha** [comment]
Any solution?..I face this with jaxrs-analyzer plugin generated swagger JSON files.

**Comment by FrancoisThareau** [comment]
Same issue ...

**Comment by webron** [comment]
@FrancoisThareau - do you have a 1.2 spec?

**Comment by FrancoisThareau** [comment]
No sorry, swagger spec 2.0 (generate with the swagger-maven-plugin) and the validator is check ok

**Comment by webron** [comment]
@FrancoisThareau - okay, this is issue is specific to swagger 1.2. Please open a new ticket with the relevant details (version of the ui, a copy of your spec).
