### ISSUE TITLE
ResponseModel doesn't show for secondary responses

### ISSUE THREAD

**Issue by jamesblack** [swagger-api/swagger-ui#1297]
![image](https://cloud.githubusercontent.com/assets/1382609/7689968/5860489e-fd6d-11e4-9501-4a64e0ec8bb8.png)

In the above 405 should show a model

Path Spec

``` get:
  description: Get the current logged-in user
  tags:
    - Account
  responses:
    200:
      description: User found
      schema:
        $ref: '#/definitions/DefaultError'
    405:
      description: Not logged in
      schema:
        $ref: '#/definitions/DefaultError'
```

Definition Spec

``` definitions:
  DefaultError:
    type: object
    properties:
      taco:
        type: string
```

I saw some issues on this, but it doesn't seem to be working, I downloaded the latest code from master and it seems to still have this issue, I have also tried inlining the model, no such luck.

**Comment by elsurudo** [comment]
Also having this issue, with inline schema definition,

**Comment by webron** [comment]
@elsurudo - can you please check which version of swagger-ui you're using?

**Comment by ponelat** [comment]
This is indeed broken, and is part of a refactor aiming to get the markup out of swagger-js and into swagger-ui. This is high up on our priorities and you can follow this issue...
https://github.com/swagger-api/swagger-ui/issues/1248

@elsurudo although inline schemas *do* work in other areas (parameters for example), so more info would be appreciated.

**Comment by chenjianjx** [comment]
When can this be fixed?

**Comment by dobrovi** [comment]
Hi.
Please note, that description for code 200 is not shown anywhere at all. Would be great to fix this too.

**Comment by webron** [comment]
Models are now fully shown for all response types, starting in version 3.0.
