### ISSUE TITLE
Could I change the charset in request header?

### ISSUE THREAD

**Issue by bnupaladin** [swagger-api/swagger-ui#1298]
Hi!
My original Content-Type in request header is "applcation/json". When I try to add to Content-Type a charset other than utf-8, like "applcation/json; charset=gb2312", it always changes to "applcation/json; charset=UTF-8".
Could I change the charset somewhere? Somebody help!

**Comment by webron** [comment]
Just to be sure, how do you change the charset?

**Comment by bnupaladin** [comment]
In the file index.html, add a line into function addApiKeyAuthorization below:
window.swaggerUi.api.clientAuthorizations.add("Content-Type",new SwaggerClient.ApiKeyAuthorization("Content-Type","application/json; charset=GB2312","header"));

**Comment by webron** [comment]
That's not the way to set the content type of the request and it would be overridden.
The content type is controlled by the Swagger specification, specifically the `consumes` property.

**Comment by bnupaladin** [comment]
The consumes property is the Parameter Content Type in test section? I just tried to set the consumes as "application/json; charset=whatever", then the request header's Content-Type changed to "application/json;charset=UTF-8".

**Comment by webron** [comment]
That may be a different issue, but you cannot specify the content type directly as a header.

**Comment by fehguy** [comment]
There is an option in swagger-js to override the requst headers.  You cannot override content-type in the UI like you mentioned.  Please provide a sample spec, or more info and we can look at it.
