### ISSUE TITLE
OAuth2 and Azure Active Directory - invalid_resource

### ISSUE THREAD

**Issue by ChrisHimsworth** [swagger-api/swagger-ui#1302]
I am using Swagger (via https://github.com/domaindrivendev/Swashbuckle) with OAuth2 using Azure Active Directory as the identity provider.
I am managing to authorise my application, but the issue comes when Swagger requests a token from Azure Active Directory, I get the response:
"error":"invalid_resource","error_description":"AADSTS50001: Resource identifier is not provided.

Looking at MSDN docs: https://msdn.microsoft.com/en-us/library/azure/dn645542.aspx, under the heading "Use the Authorization Code to Request an Access Token", there is an optional field called resource, but it seems that in this scenario Microsoft requires this field.

Is there a way in which Swagger can be changed to pass this in (ideally so it can work with solutions like Swashbuckle as well)?

**Comment by webron** [comment]
I'm a bit surprised we haven't encountered this issue until now (there are probably quite a few users with Azure), though perhaps not many use OAuth2. We should easily be able to add the option to add the resource field.

**Comment by webron** [comment]
Closing as an old issue. Please retest with 3.0 and still a problem reopen.

**Comment by SamBartlettXOM** [comment]
Has this been removed as of 5.2.2? I can no longer pass the additional query parameters as documented [here](https://blogs.msdn.microsoft.com/pratushb/2016/04/28/enable-swagger-to-authenticate-against-azure-ad/), which is a bit of an issue for me being on Azure - or is there some other way to do this now that I should be using?
