### ISSUE TITLE
(empty) appears in the Parameters Value column when supportedSubmitMethods is an empty array 

### ISSUE THREAD

**Issue by collaborator99** [swagger-api/swagger-ui#1304]
In the Parameters table, the Value column is not used when in the "read-only" view that occurs by setting supportedSubmitMethods to an empty array. 

That Value column shows "(empty)" for all parameter values.  It would be good to hide the Value column in this situation.

**Comment by juniorvanin** [comment]
Hi, any ideas of when this feature will be available?
Thx

**Comment by kticka** [comment]
Bump

**Comment by webron** [comment]
This feature no longer exists in 3.x.
