### ISSUE TITLE
when using allOf swagger-ui ignores parent schema for display

### ISSUE THREAD

**Issue by paulhill** [swagger-api/swagger-ui#1306]
Swagger uses allOf to denote inheritance to support polymorphism but swagger-ui doesn't take it into account. It should show either the parent schema with some kind of indication it is the parent, or just merge the attributes so the model displayed correctly represents what is required.

**Comment by paulhill** [comment]
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#models-with-polymorphism-support

e.g. using the above example, if you reference Cat as the response schema it won't include "name" in the displayed schema.

**Comment by paulhill** [comment]
http://editor.swagger.io/ does an ok job of listing the parent schema

**Comment by webron** [comment]
@paulhill - long time! `allOf` is known to be not supported yet. Please follow https://github.com/swagger-api/swagger-js/issues/188.
