### ISSUE TITLE
Bug with schema objects

### ISSUE THREAD

**Issue by PlamenVasilev** [swagger-api/swagger-ui#1308]
I have defined in "definitions" custom type and set parameter to use this type.
When I set the "in" to "body" I get the schema on the right and a textarea on the left with content type select. this is OK, but I want to set the "in" to "formData". Then I get text input instead of textarea and I cannot choose content type. the submited object is submited as text instead of object too.

**Comment by webron** [comment]
As explained in the google group, you cannot use models in form parameters. The most you can do is those those as strings and make them free-form. This behavior is intentional.

**Comment by webron** [comment]
@PlamenVasilev - have you made the required changes do your Swagger definition? Otherwise, this is not going to work.
