### ISSUE TITLE
Option to show query parameters in path

### ISSUE THREAD

**Issue by stevage** [swagger-api/swagger-ui#1310]
Maybe a stylistic thing, but it would be nice to have an option to show (optional) query parameters in each API path. For instance:

`/v2/search/{searchtext}?limit={limit}`

(And if so, with CSS span names to make that part stylable)

**Comment by webron** [comment]
That would be relevant if/when Swagger supports query parameters as unique identifiers of paths. Unless you mean something else?

**Comment by stevage** [comment]
Hmm, I'm not sure what you mean by "unique identifiers of paths". What I mean is, where currently the top line of an operation looks like:

`GET /v2/search/{searchtext}                          search`

(and below is a list of  both path and query parameters, such as the 'limit' query parameter in this instance)

allow it to display as:

`GET /v2/search/{searchtext}?limit={limit}           search`

**Comment by webron** [comment]
You want to show all query parameters available to the operation in the path itself?

**Comment by stevage** [comment]
Yep - as an option. I don't know about other APIs, but the one I'm working
with generally has 2-3.

**Comment by titiu7** [comment]
I apologize for bringing up the same issue again. Have you figured out how to do it yet?

**Comment by webron** [comment]
This feature is out of scope for us. You're welcome to write your own plugin to 3.0 that will add that behavior.
