### ISSUE TITLE
Option to suppress "default" title

### ISSUE THREAD

**Issue by stevage** [swagger-api/swagger-ui#1311]
I'm not entirely sure what this word "default"  refers to (or in what situation you'd have more than one resource), but when you only have one it's kind of confusing and ugly:

![screenshot 2015-05-26 10 26 36](https://cloud.githubusercontent.com/assets/678344/7803405/c9b23c94-0391-11e5-863f-955bee53b639.png)

Perhaps either never show it if there's only one, or allow an option for removal?

I ended up forcibly hiding it with CSS:

```
  .resource .heading h2 {
    display:none !important;
  }
```

**Comment by webron** [comment]
@stevage - Swagger 2.0 introduced a new tagging system to allow operation grouping.

The `default` is just the default group used for all operations that are tag-less as they need to show up somewhere. If you have other suggestions, we'd be happy to hear.

**Comment by stevage** [comment]
Ok, thanks - I didn't know about tags.

Suggestions:

- if there no tags at all, don't show "default" - show nothing
- if the "default" tag is always shown first (I don't know if true), then maybe you don't show any text for it.
- maybe "General" or "Untagged" would be better terms than "default".

For my own case, now that I know you can tag, I don't want to hide it anymore :)

**Comment by ponelat** [comment]
We can write in a clause and option for swagger-ui that would show/hide this 'default' tag.

Out of curiosity, what would happen if you were to create a tag called 'default', would untagged resources end up merged into it?

**Comment by webron** [comment]
@ponelat - do I *need* to make a snarky comment here? ;)

**Comment by howarddierking** [comment]
:+1: to this - took me a few minutes today to figure out exactly why I kept seeing "default" everywhere

**Comment by prusswan** [comment]
I wouldn't mind configuring options for a "default" tag, but this does not seem to be part of the specifications..

**Comment by andrewzk** [comment]
+1

**Comment by deckar01** [comment]
I was about to start testing strategies for this issue, but I tagged my API instead. Much better than having everything in one big "default" group. :wink:

Maybe the untagged operations belong below the tagged groups in an uncollapsable container. This would avoid issues with the default group name colliding with a tag name.

**Comment by webron** [comment]
Closing as we're not going to implement it. If anyone wants to submit a PR to that effect, we'll be happy to review.
