### ISSUE TITLE
Query Params within Swagger UI

### ISSUE THREAD

**Issue by mowi62** [swagger-api/swagger-ui#1317]
Hi, 
we have the same issue as this guy,
https://groups.google.com/forum/#!topic/swagger-swaggersocket/lxtOQ9KxOSo

Would it be possible to get a solution for that?
Thank you in advance. 
Seems that https://github.com/swagger-api/swagger-ui/issues/1310 is the same issue?

**Comment by webron** [comment]
If this is for display purposes only, then yes, it's exactly like #1310. If this is to separate paths by query parameters, that's simply not supported by Swagger and as long as it isn't, it won't be supported in the UI.

**Comment by mowi62** [comment]
Ok, thank you for quick response!
