### ISSUE TITLE
  New issue Feature Request: Support for general model documentation.

### ISSUE THREAD

**Issue by csmccoy** [swagger-api/swagger-ui#1319]
Would it be possible to include the ability to document the model's so that they show somewhere, at the bottom for instance, of the page for reference purposes? Use case would be an API has complex models implemented that would warrant additional documentation for a user beyond what is defined in the routes. This would serve that purpose.

**Comment by webron** [comment]
Sorry, just found the issue as we discussed in email - #1052. Closing as duplicate.
