### ISSUE TITLE
Request type drop down for text/csv strange behavior can it be altered ?

### ISSUE THREAD

**Issue by codemonkeyneo** [swagger-api/swagger-ui#1320]
I have swagger UI @version v2.1.0-M2 with the Try it Out button enabled and the Response Content Type select has the available response types available.

Requesting json or xml format is great ; If I look at the network traffic it sends everything correctly

   /GET myservicename.json
   /GET myservicename.xml

The format extensions have nicely been appended to the service name.

HOWEVER,

If I choose text/csv I end up with an internal server error and a UI that just shows the progress dots looping.

Looking at the network traffic it shows ;

/GET myservicename.%7Bformat%7D?

Yikes that doesn't look correct.

How can I correctly give the content type the correct format to use so that I end up calling with the correct format.

i.e.  /GET myservicename.csv

Thanks

**Comment by ponelat** [comment]
From what I've seen, we're only supporting .json and .xml with the {format} URL placeholder ( {format} === %7Bformat%7D when it's URI is encoded).

To support more, we'd either need to add more manually (there shouldn't be that many) or map mime types to file extensions. CSV should be quite common, so this may need to be added soon.

However we continue, at the very least if we _don't_ support that mime-type, we should strip out the {format} part.

So we'll have to see how we continue.

**Comment by codemonkeyneo** [comment]
Cool thanks for that ponelat and webron.

In the meantime I have simply removed those options for my users with a quick jquery remove();

    $("select[name='responseContentType'] option[value='text/csv']").remove();
    $("select[name='responseContentType'] option[value='text/html']").remove();
    $("select[name='responseContentType'] option[value='text/plain']").remove();

**Comment by webron** [comment]
Would suggest to check out 3.0 and see if it works.
