### ISSUE TITLE
Leaving out "description" in "responses" throws "Data does not match any schemas from 'oneOf'" error

### ISSUE THREAD

**Issue by yan-foto** [swagger-api/swagger-ui#1321]
Consider the following example in Yaml:

```yaml
/pets/{id}:
    get:
      summary: Retrieve information about a pet
      responses:
        200:
          schema:
            $ref: '#/definitions/Pet'
```

this would throw `Data does not match any schemas from 'oneOf'` which is misleading since adding the `description` would solve the problem. It would be great if the error code could be corrected.

**Comment by webron** [comment]
This is unfortunately beyond our control right now. This is a matter of third party schema validators and the errors they produce. Unfortunately, they tend to produce errors that are not user friends, although accurate. This does mean there's a need to understand concepts in JSON Schema.
