### ISSUE TITLE
Auto generated json code for Dictionary<string,object> problem

### ISSUE THREAD

**Issue by santoshkaranam** [swagger-api/swagger-ui#1322]
I have a web API whose return type is DTO1. DTO1 has a property P1 of type object 

I have auto generated webapi client using AutoRest.0.9.7

When i try to make a request to webAPi using auto generated client, it gives exception.

Exception when serializing property P1 using JObject.Parse.

The Value of P1 at point when exception was thrown was "value1"...

I believe there is not way to convert string value ("value1") using JObject.Parse.

JObject.Parse always expects the string passed to be a json string.

On contrary when i use JsonConter.Serialize , the serialization works fine..

---------------------------------------------------------------------------------------------------------
Is there a way i can get around this issue or i am doing anything wrong.?

**Comment by webron** [comment]
Which project did you use to generate the client? Was it swagger-codegen or something else?

**Comment by santoshkaranam** [comment]
AutoRest.0.9.7
AutoRest.exe.

Let me re-phrase the issue .. editing currently

**Comment by webron** [comment]
If that's the case, you need to open the issue on [AutoRest](https://github.com/Azure/AutoRest)... we won't be able to help with that.

**Comment by santoshkaranam** [comment]
can i move this issue there some how?

**Comment by webron** [comment]
I wish. Github doesn't have the capabilities to move issues within the same group, let alone between groups.

**Comment by santoshkaranam** [comment]
ok.. Thanks

**Comment by webron** [comment]
Going to close this one for now, hope the AutoRest people could help.
