### ISSUE TITLE
array of models missing lines

### ISSUE THREAD

**Issue by shinymayhem** [swagger-api/swagger-ui#1323]
I have a simple config where an array of models, if the items in the array are a reference to a definition, is missing a couple lines in the model tab, but everything else seems to work as expected. I can't explain it very well, so here's a screenshot and a sample config. This is for version 2.1.5-M2

```yaml
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema:
            properties:
              things:
                  type: array
                  description: Array of things
                  items:
                      $ref: "#/definitions/ThingId"
definitions:
  ThingId:
      type: string
      description: Its a thing
```
![2 1 5-m2-model-array-display-bug](https://cloud.githubusercontent.com/assets/3253971/7895851/4760ca02-0658-11e5-94d2-678dc04c89a5.JPG)

**Comment by webron** [comment]
Can you try the develop_2.0 branch?

**Comment by shinymayhem** [comment]
The issue is the same in develop_2.0

**Comment by webron** [comment]
@ponelat - didn't we handle this one?

**Comment by ponelat** [comment]
@webron This is different, although after a little digging, easily solved.
It must be my greatest fix yet... a single '+' was missing ;D
It was an edge case (there are a few if/elseif/elseif/... blocks) and this little guys was getting overwritten...
```javascript
// Whoops
html = "... } "
// Solved
html += "... } "
```
So we were in affect chopping off the top section.

**Comment by webron** [comment]
Fixed in develop_2.0.
