### ISSUE TITLE
Can't get application/json working on UI, got application/x-www-form-urlencoded instead

### ISSUE THREAD

**Issue by zygis** [swagger-api/swagger-ui#1326]
```
"produces": [
    "application/json"
 ],
"consumes": [
    "application/json"
],
```
But headers sent from browser:
```
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
```
It works ok in editor, but not in UI. Tried "master" and "develop_2.0" branches.

spec: https://developers.soundest.net/api/json/v1.json

**Comment by webron** [comment]
@zygis - if you're going to use `formData` parameters, you have to use `application/x-www-form-urlencoded` or `multipart/form-data` as your `consumes` value. There's just no other way of sending form data parameters.

If you're looking to send a JSON, then your Swagger description needs to change to reflect that. You'd look for sending a `body` parameter with a model describing your fields. Take a look at our online [pet store sample](http://petstore.swagger.io/) and its [Swagger description](http://petstore.swagger.io/v2/swagger.json) to see an example of it.

**Comment by zygis** [comment]
@webron 
Oh, my bad. Thanks for help!
