### ISSUE TITLE
Access Token Scope should be optional with implicit flow

### ISSUE THREAD

**Issue by olivier-squid** [swagger-api/swagger-ui#1329]
I've been struggling with the OAuth process when figured out that the Swagger UI expects scope to be defined whereas our API does not. 
In OAuth's specs, scope is optional : https://tools.ietf.org/html/rfc6749#section-4.2.1

The guilty code is in ```swagger-oauth.js```
```
      if(auth.type === 'oauth2' && auth.scopes) {
```

**Comment by cbornet** [comment]
Also happens with authorization_code flow. We get the code and token but then the auth bearer field is not set into the request header.

**Comment by cbornet** [comment]
Also, if there are no scopes, the scope selection popup should probably not appear and we should be directly sent to the 3rd party auth page.

**Comment by shupp** [comment]
+1, just ran into this with the application flow.

**Comment by bodnia** [comment]
@shupp @olivier-squid @cbornet could you please test this issue in latest master and confirm if this works for you now and the issue can be closed

**Comment by shupp** [comment]
@bodnia The scope issue seems to be resolved, but the token request is putting the client_id and client_secret in the post data, when it should be in the Authorization header (basic auth):

https://tools.ietf.org/html/rfc6749#section-4.4.2

Only the scope and grant_type params should be in the form post data.

Thanks,

Bill

**Comment by cbornet** [comment]
See https://tools.ietf.org/html/rfc6749#section-2.3.1 Putting those params in the request body is authorized but discouraged.

**Comment by shupp** [comment]
@cbornet ah, you're correct.  Thanks for clarifying.

**Comment by shupp** [comment]
@cbornet @bodnia After updating my token url endpoint to support params in the request body, I've confirmed that oauth2 client_credentials (application) flow is working with no scopes defined.

Thanks!

**Comment by webron** [comment]
Thanks!
