### ISSUE TITLE
Security requirements for operations are not inherited from top level security field

### ISSUE THREAD

**Issue by kag0** [swagger-api/swagger-ui#1330]
Current behavior: removing the security field in an operation object when there is a security field defined for the swagger object causes the authentication on/off switch typically found in the top right corner of the operation (in the ui) to disappear. 
Expected behavior: removing the security field causes the on/off switch to display exactly as if it had been defined for the operation object identically to how it was defined for the swagger object

**Comment by webron** [comment]
It'd be best if you could provide us with a sample Swagger definition to load and test.

**Comment by kag0** [comment]
Sorry this is a bit late. Using the petstore example http://pastebin.com/C7N7sgXs.
Here all operations should use the "petstore_auth" security definition unless otherwise indicated. However if you remove the security requirement from an operation like in POST /pet it displays as if there were no security requirement (behavior which should be reserved for when the security requirement is an empty array), when it should inherit the security requirement from the swagger object.

**Comment by webron** [comment]
You'd need to clarify what you mean by "remove". Do you have an empty security property - `"security": []` or do you remove the property entirely?

**Comment by kag0** [comment]
I mean remove the property entirely.

**Comment by lucian303** [comment]
I'm experiencing this as well. Security must be specified for every single path in order for it to apply to that path even if it's declared globally (and should be applied by default). Latest master version 2.1.1.

**Comment by webron** [comment]
Please test with 3.0 and reopen if still a problem.
