### ISSUE TITLE
Using a schema for a PUT body from a definition called "File" bug 

### ISSUE THREAD

**Issue by gaillard** [swagger-api/swagger-ui#1331]
Using a schema for a PUT body from a definition called "File" causes a file upload chooser button to appear instead of a area to put in the body.

**Comment by webron** [comment]
Can you share the specific parameter definition if not a minimal working definition to reproduce it? Sounds like a funny bug though.

**Comment by webron** [comment]
@gaillard?

**Comment by webron** [comment]
Closing due to lack of response (and details). Please reopen if needed.
