### ISSUE TITLE
Add some guides on editing index.html for authentication

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#1335]
In particular guides for...

1. Basic Auth (ie Password Auth)
1. ApiKey Auth
1. Custom request manipluation

1. How to add auth for fetching your spec file.
1. How to include auth within the spec file for certain paths/operations

**Comment by hamx0r** [comment]
Currently, who does one do #4 ?  I'm finding that clicking Explore in Swagger UI does not send the `apikey` in the header when loading a new JSON swagger spec, even though the UI _does_ send the `apikey` in the header for calls per the currently loaded spec.  Per [Security Filtering](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-filtering) in the documentation, one can safely trim his swagger.json for various RBAC requirements, but there doesn't seem to be a straightforward way to send an `apikey` when GETing swagger.json so the API knows what flavor to respond with.

**Comment by fehguy** [comment]
Please try out https://github.com/swagger-api/swagger-ui/pull/2014
