### ISSUE TITLE
url for SwaggerUI options breaks when using spec

### ISSUE THREAD

**Issue by gaillard** [swagger-api/swagger-ui#1338]
On the develop_2.0 branch when url into the SwaggerUi options is null it explodes, for those that are passing in a spec directly. Putting something silly in url fixes it it, I think it has to do with line 20949 of swagger-ui.js.

**Comment by ximex** [comment]
i got an error in line 1462 and 31064

**Comment by webron** [comment]
No longer an issue with 3.0.
