### ISSUE TITLE
Unable to Load Swagger UI

### ISSUE THREAD

**Issue by jasonray** [swagger-api/swagger-ui#134]
When I attempt to load my swagger api docs, I get the following error `0 : error http://localhost:8080/jersey-starterkit/rest/api-docs.json`

When launching 'http://localhost:8080/jersey-starterkit/rest/api-docs.json' manually, the following is presented:

raw:

```
{"apiVersion":"1.0","apis":[{"description":"","path":"/api-docs.{format}/echo"},{"description":"","path":"/api-docs.{format}/hello"}],"basePath":"http://localhost:8080/jersey-starterkit/rest","swaggerVersion":"1.1"}
```

formatted:

```
{
    "apiVersion": "1.0",
    "apis": [{
        "description": "",
        "path": "/api-docs.{format}/echo"
    }, {
        "description": "",
        "path": "/api-docs.{format}/hello"
    }],
    "basePath": "http://localhost:8080/jersey-starterkit/rest",
    "swaggerVersion": "1.1"
}
```

I cannot determine if I setup swagger incorrectly.

**Comment by dinz19** [comment]
GET http:// Server:8015/api/api-docs 404 (Not Found) @ client.js:841

index.html:106 Unable to Load SwaggerUI

I am not able to load SwaggerUI and I'm new to swagger UI. Can you please help me to resolve this?

**Comment by AbhinayThakur** [comment]
@dinz19 facing same problem any fix??

**Comment by dinz19** [comment]
@AbhinayThakur . Yes I got it fixed :)   If you're still facing the issue with it, let me know

**Comment by rajanjjs** [comment]
@dinz19 , I have the same issue "Unable to Load SwaggerUI"
Can you please help me to solve this?
What is the fix?
