### ISSUE TITLE
Support definition.example

### ISSUE THREAD

**Issue by boillodmanuel** [swagger-api/swagger-ui#1344]
Use definition.example if exists instead of building it from definition.property.example which used only string values

**Comment by boillodmanuel** [comment]
I don't know how to contribute because I'm not familiar with coffeescript.

In my javascript code, in swagger-client.js, I've added the lines below:

```javascript
 if (this.definition.example) {
    return JSON.parse(this.definition.example);
  }
```

Full method


```javascript
Model.prototype.createJSONSample = function(modelsToIgnore) {
  var i, result = {}, representations = {};
  modelsToIgnore = (modelsToIgnore||{});
  modelsToIgnore[this.name] = this;
  if (this.definition.example) {
    return JSON.parse(this.definition.example);
  }
  for (i = 0; i < this.properties.length; i++) {
    prop = this.properties[i];
    var sample = prop.getSampleValue(modelsToIgnore, representations);
    result[prop.name] = sample;
  }
  delete modelsToIgnore[this.name];
  return result;
};
```

**Comment by mbbeaubi** [comment]
Please fix this, with this in place I will be able to generate proper examples for my users to try out without having to edit json.

**Comment by webron** [comment]
This should actually be fixed already. Please reopen of you see differently.
