### ISSUE TITLE
Multiple types not working correctly

### ISSUE THREAD

**Issue by stevezau** [swagger-api/swagger-ui#1347]
Hi,

It seems specifying multiple type's breaks "Click to set as parameter value".

Example:
```
        "tasks": {
          "items": {
            "type": "string"
          },
          "type": [
            "array",
            "string"
          ]
        }
```

The Model is shown correctly in swagger-ui

```
SomeModel {
tasks (number,string)
}
```

But the Model Schema is empty? Is this working as designed?

**Comment by webron** [comment]
Multiple types per parameter/property are not supported by the Swagger specification at the moment.
