### ISSUE TITLE
oauth2RedirectUrl option into swaggerUI isn't used

### ISSUE THREAD

**Issue by gaillard** [swagger-api/swagger-ui#1350]
The documented oauth2RedirectUrl option in swaggerUI doesn't actually get used in the /auth calls to the oauth2 provider.

**Comment by gorfik** [comment]
swagger-ui.js 
At least following lines (38-40) must be fixed (options.oauth2RedirectUrl should be used in assignment instead of  options.redirectUrl)
if (typeof options.oauth2RedirectUrl === 'string') { 
window.oAuthRedirectUrl = options.redirectUrl; 
}

**Comment by fehguy** [comment]
@gorfik it would be great if you could send a PR for this.

**Comment by gorfik** [comment]
https://github.com/swagger-api/swagger-ui/pull/1560

**Comment by fehguy** [comment]
Thanks

**Comment by nmarasoiu** [comment]
Hi, in swagger-ui 3.6.0, using oauth2RedirectUrl config option as below, it does not seem to override the oauth2RedirectUrl hardcoded in the js files (localhost:3200). Please advise,Thanks,nicu
  ui.initOAuth({
    clientId: "MOVIEUI",
    appName: "Swagger UI",
    scopeSeparator: " ",
    oauth2RedirectUrl: window.location.origin + "/cache/swagger/oauth2-redirect.html",
    additionalQueryStringParams: {realm_id: "IDAM_REAL"}
  });
