### ISSUE TITLE
Unable to enable XML Response in Swagger UI

### ISSUE THREAD

**Issue by dpatra1** [swagger-api/swagger-ui#1351]
Hi,

I am new to Swagger and i have integrated in my Spring boot application to generate the api documentation. Its working fine with two known issue like:

1) when i am trying to test any API from Swagger UI, i dont have a option to select whether i wanted XML/JSON response option. It always gives me the JSON response only .

Also in case of PUT/POST apis i wanted the request payload to send based upon the users choice like JSON/XML, but i can see only JSON is coming up in the drop down.

I read lots of blog and discussion w.r.t Swagger UI and every where i see its been asked to use consume/produces in the @Apiresponse . I have used them as well but it has no impact at all.

2) Also i have another issue like, i wanted to display some more static html information in the Swagger UI w.r.t my application other than the auto generated API documentation which Swagger is populating after integrating with my application. I tried but un-success to add any static content in the index.html.

can someone help me getting this issue resolved ?

3) Also i have enabled to see the request headers but i  dont see them at all.

Thanks,
Deba

**Comment by dpatra1** [comment]
I am using the below dependency in my maven pom.

        <dependency>
		    <groupId>com.mangofactory</groupId>
		    <artifactId>swagger-springmvc</artifactId>
		    <version>1.0.2</version>
		</dependency>
	
		<dependency>
		    <groupId>org.apache.tomcat.embed</groupId>
		    <artifactId>tomcat-embed-jasper</artifactId>
	    	<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.wordnik</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.5.0-M2</version>
		</dependency>

with java 8

**Comment by ponelat** [comment]
@dpatra1 The Java libraries all generate a spec file, a `.json`. If I can take a look at that, we can see where the problem lies. For instance here is the petstore spec file ... http://petstore.swagger.io/v2/swagger.json

For editing swagger-ui, you can go crazy with the `path-to-ui/src/main/html/index.html` which will be processed and dumped into `path-to-ui/dist/index.html` along the other files when you run `npm run build`. You can also modify the templates....`path-to-ui/src/main/template/*.handlebars`, as long as you remember to build them....`npm run build`

As to the versions, I think you're a little behind and updating will cure a few issues up. @webron will know the latest versions.

**Comment by webron** [comment]
@dpatra1 - please upgrade to the latest version of swagger-springmvc now known as [springfox](https://github.com/springfox/springfox) and try again. Also, remove the swagger-core dependency as you don't need it. 

If after that you still have an issue with the drop-down for mime type selection not appearing, please refer to springfox's manual as you probably missed a step, or ask on their repository directly.

**Comment by dpatra1** [comment]
@webron - Thanks for pointing me to the right path.

I have added the below dependency to my pom now: 
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>swagger-ui</artifactId>
			<version>2.1.8-M1</version>
		</dependency>

Also copied the Swagger2SpringBoot.java from http://springfox.github.io/springfox/docs/snapshot/ 

but when i am trying to http://localhost:8081/springfox/ url in my browser i am getting the below error:
============
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jun 09 10:35:23 PDT 2015
There was an unexpected error (type=Not Found, status=404).
No message available

========================


Can you please help me understanding with this integration issue which i am seeing with spring fix ?

I doubt on the class which i have copied and after that i have updated the basePackageClasses to my MicroService class. Is that correct ? Or it should be my Controller where all my rest web services are declared ?

@SpringBootApplication
@EnableSwagger2
@ComponentScan(basePackageClasses = { BusinessBankingService.class })
public class Swagger2SpringBoot {

**Comment by webron** [comment]
That's more of a question to the springfox people, you should ask in their repository.
Also, 2.1.8-M1 is an old version of the UI. You should look into other ways of integrating the latest with your application.

**Comment by dpatra1** [comment]
@webron - Now i have changed my Swagger2SpringBoot class like below:

<Code>
package com.diginsite.microservices;

import static com.google.common.collect.Lists.newArrayList;
import static springfox.documentation.schema.AlternateTypeRules.newRule;

import java.util.List;

import org.joda.time.LocalDate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.async.DeferredResult;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.builders.ResponseMessageBuilder;
import springfox.documentation.schema.ModelRef;
import springfox.documentation.schema.WildcardType;
import springfox.documentation.service.ApiKey;
import springfox.documentation.service.AuthorizationScope;
import springfox.documentation.service.SecurityReference;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.service.contexts.SecurityContext;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

import com.fasterxml.classmate.TypeResolver;

@EnableSwagger2
@Configuration
@EnableWebMvc
@ComponentScan("com.diginsite.microservices.web")
public class Swagger2SpringBoot {
	@Autowired
	private TypeResolver typeResolver;

	@Bean
	public Docket swaggerSpringMvcPlugin() {
		return new Docket(DocumentationType.SWAGGER_2)
				.groupName("v1-bbs")
				.select()
				.apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any())
				.build()
				.pathMapping("/")
				.directModelSubstitute(LocalDate.class, String.class)
				.genericModelSubstitutes(ResponseEntity.class)
				.alternateTypeRules(newRule(typeResolver.resolve(DeferredResult.class,
								typeResolver.resolve(ResponseEntity.class,
										WildcardType.class)), typeResolver
								.resolve(WildcardType.class)))
				.useDefaultResponseMessages(false)
				.globalResponseMessage(RequestMethod.GET,
						newArrayList(new ResponseMessageBuilder().code(500)
								.message("500 message")
								.responseModel(new ModelRef("Error")).build()))
				.securitySchemes(newArrayList(apiKey()))
				.securityContexts(newArrayList(securityContext()));
	}

	private ApiKey apiKey() {
		return new ApiKey("mykey", "api_key", "header");
	}

	private SecurityContext securityContext() {
		return SecurityContext.builder().securityReferences(defaultAuth())
				.forPaths(PathSelectors.regex("/anyPath.*")).build();
	}

	List<SecurityReference> defaultAuth() {
		AuthorizationScope authorizationScope = new AuthorizationScope(
				"global", "accessEverything");
		AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
		authorizationScopes[0] = authorizationScope;
		return newArrayList(new SecurityReference("mykey", authorizationScopes));
	}
}
</Code>



Now i am seeing an error in my tomcat server while accessing http://localhost:8081/springfox/ along with the above error message in browser:
**WARN 6872 --- [nio-8081-exec-1] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/springfox/] in DispatcherServlet with name 'dispatcherServlet'**

**Comment by webron** [comment]
I really can't help you with anything related to springfox. It's a project on its own. You'd have to ask there.

**Comment by dpatra1** [comment]
Thanks weborn. I was asking because when you recommended to use springfox so i thought i might get some for these issues which i am seeing now.

**Comment by webron** [comment]
@dpatra1 - I just know that it's newer and can generate Swagger 2.0 which you'd want to use now. Any support related to it still needs to go there.

**Comment by brajput24** [comment]
@dpatra1 - remove the @EnableWebMvc  from Swagger2SpringBoot and try this URL http://localhost:8080/swagger-ui.html

**Comment by fehguy** [comment]
Please follow #1248
