### ISSUE TITLE
Fails to show non-JSON parse-able response 

### ISSUE THREAD

**Issue by mortias** [swagger-api/swagger-ui#1354]
Hello,

Refr @webron @ponelat 

We identified a possible regression bug related to the "no content" bug

Basically if the json returned is invalid, in previous versions you got the response back 
anyway but it told me that it was not able to parse it, now i yust get "no content"

For security reasons we prefix our json responses with 
)]}',
{"header":{"code":200,"text":"OK","version":"1.0"},"data":"some data"}

**Comment by mortias** [comment]
ok, we figured out that the thirdparty libs are not relaiable so the only option would be to force the ui to use jquery, meaning set the option useJQuery : true in the SwaggerUI constructor on the index.html

**Comment by ponelat** [comment]
Here is the issue for superagent...
https://github.com/visionmedia/superagent/issues/675

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
