### ISSUE TITLE
Datatype (Model + Model Schema) undefined when parameter type is not defined via $ref

### ISSUE THREAD

**Issue by queirozfcom** [swagger-api/swagger-ui#1357]
Hi.

If one defines a parameter like this:

```json
"parameters": [
  {
    "name": "loginData",
    "in": "body",
    "schema": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string",
          "example":"admin"
        },
        "password": {
          "type": "string",
          "example":"admin"
        },
        "rememberMe": {
          "type": "boolean",
          "example":false
        }
      }
    }
  }
],
```

The datatype stays `undefined` and the Model and Model Schema do not show anything. However, if I define it via `$ref`, i.e.

```json
"parameters": [
  {
    "name": "loginData",
    "in": "body",
    "schema": {
      "$ref": "#/definitions/LoginData"
    }
  }
],
``` 
with the corresponding entry for `LoginData`under definitions, everything works OK (datatype is not `undefined`, Model and Model Schema are displayed). 

Is this expected behaviour? To me it seems more user-friendly to support showing Model and Model Schema when parameters are defined through either of these methods.

**Comment by webron** [comment]
Which version of swagger-ui have you tested it with?

**Comment by queirozfcom** [comment]
@webron "version": "2.1.8-M1",

**Comment by webron** [comment]
Please upgrade to the latest master.

**Comment by queirozfcom** [comment]
@webron Great. Now it says **Inline model** and it is displayed correctly. Thank you for helping. I'll close this.
