### ISSUE TITLE
I'm not able to see the authenticate button in swagger-ui

### ISSUE THREAD

**Issue by rmarpozo** [swagger-api/swagger-ui#1361]
I have an operation, experiments getAll, that uses OAuth2 authentication. Although the information is in the JSON, the button is not displayed. Am I doing anything wrong. Is that a bug?

Operation:

``` js
/experiment: {
  get: {
    tags: [
      "experiments"
    ],
    summary: "Get all experiments",
    description: "getAll",
    operationId: "getAllUsingGET",
    consumes: [
      "application/json"
    ],
    produces: [
      "*/*"
    ],
    parameters: [{
      name: "name",
      in: "query",
     description: "name",
     required: false,
     type: "ref"
  },
  {
    in: "body",
    name: "userPrincipal",
    description: "userPrincipal",
    required: false,
    schema: {
      $ref: "#/definitions/Principal"
    }
  }],
  responses: {
    200: {
      description: "OK",
      schema: {
        type: "array",
        items: {
          $ref: "#/definitions/Experiment"
        }
      }
    },
    401: {
      description: "Unauthorized"
    },
    403: {
      description: "Forbidden"
    },
    404: {
     description: "Not Found"
    }
  },
  security: [{
    oauth2schema: [
      "global"
    ]
  }
]},
```

Security Definitiions:

``` js
securityDefinitions: {
  oauth2schema: {
    type: "oauth2",
    authorizationUrl: "http://localhost:8080/oauth/authorize",
    flow: "implicit",
    scopes: {
      global: "accessEverything"
    }
  }
},
```

**Comment by webron** [comment]
Do you have this fancy little section in your configuration and is it updated to your fields? 

https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L37-L43

**Comment by bandtank** [comment]
@webron I don't understand your comment. Where is that file in my 'configuration' and where do I update the fields? I've read every piece of documentation I can find and I'm not sure how to implement your advice.

**Comment by webron** [comment]
@bandtank - unfortunately, that's not really documented (sigh), I'm just pointing to the specific configuration as it is in the index.html. The online pet store sample can also be used as reference on how to enable it. We really should document it, my apologies.

**Comment by bandtank** [comment]
@webron Thanks for the information.

**Comment by rmarpozo** [comment]
I'm using springfox-swagger-ui 2.0.1 and it seems to be a bug there. The initOAuth function call is commented.

See this bug: https://github.com/springfox/springfox/issues/788

Thanks.

**Comment by webron** [comment]
@bandtank - did you manage to get it working?

**Comment by mgruel** [comment]
I'm running into the same issue, while using version 2.1.3, build from tag of the same version.

The values have been set in the index.html, but after reloading the page, no OAuth-Button is rendered.
I've used a previous version of swagger-ui, in which this was working, but the token was not included in the request.

Which version should be used, if OAuth2 is required?

**Comment by Gobliins** [comment]
I have the same problem. I only get the apikey textfield not the authorize button even when i use the newest swagger ui 2.1.4 with the linked petstore json on petstore.swagger.io.

**Comment by webron** [comment]
The newest swagger-ui is actually 2.2.0.

**Comment by webron** [comment]
This is no longer an issue with 3.0.
