### ISSUE TITLE
swagger-ui use of less

### ISSUE THREAD

**Issue by pm100** [swagger-api/swagger-ui#1364]
Is there a reason why swagger-ui doesnt use any of the less features for simplifying skinning. I mean I expected to see variables call 'boldfont', 'normalfont', 'postColor",'getColor',.... But I dont see them, if I want to use a different font I have to change all references to 'droid sans ' spread throughout the .less files. The 'post' label color (10a54a) appears 7 times in specs.less (not picking on that one - its just an example). Did I miss something? Would people object to an update that made it skin-friendly?

**Comment by ponelat** [comment]
Organizing the Less would be great! It would be nice to consider the possibility of making skinning more accessible.

**Comment by ximex** [comment]
:+1:

**Comment by fehguy** [comment]
This was done with https://github.com/swagger-api/swagger-ui/commit/e6336a3f5ef2fbae99b9eac5a91d6ef682b83e4b
