### ISSUE TITLE
Can not pass multiple authorization keys 

### ISSUE THREAD

**Issue by nemanjapajcin** [swagger-api/swagger-ui#1376]
With latest version of Swagger UI, I'm experiencing same issue as described here:
http://stackoverflow.com/questions/30807936/how-to-pass-multiple-authorization-keys-to-swagger-js.

Version I initially installed (two months old) multiple authorization keys pass worked, but for some reason it fails now.

Copying relevant code chunk below. Am I doing something wrong?

var apiClientIdAuth = new SwaggerClient.ApiKeyAuthorization("client_id", clientId, "query");
window.swaggerUi.api.clientAuthorizations.add("client_id", apiClientIdAuth);
var apiClientSecretAuth = new SwaggerClient.ApiKeyAuthorization("client_secret", clientSecret, "query");
window.swaggerUi.api.clientAuthorizations.add("client_secret", apiClientSecretAuth);

**Comment by ponelat** [comment]
No, its a regression bug. Here is the duplicate...https://github.com/swagger-api/swagger-js/pull/488
