### ISSUE TITLE
Header Authorization is not being setted

### ISSUE THREAD

**Issue by dzfweb** [swagger-api/swagger-ui#1378]
I'm having problem with sending Authorization Header.

function addApiKeyAuthorization() {
        var key = encodeURIComponent($('#input_apiKey')[0].value);
        if (key && key.trim() != "") {            
			window.swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + key, "header"));
        }
	  }
      $('#input_apiKey').change(addApiKeyAuthorization);

**Comment by ponelat** [comment]
Ok, this most likely a CORs issue. 
Take a look at the network tab in your browser, look at the headers and compare them to what you need. https://github.com/swagger-api/swagger-ui#cors-support

Also you may want to strip out the `encodeURIComponent`, as it can mutate your key.

**Comment by fehguy** [comment]
please reopen if you're still having an issue with this
