### ISSUE TITLE
CSRF prevention tokens in cookies

### ISSUE THREAD

**Issue by dan-corneanu** [swagger-api/swagger-ui#1380]
Hi,
I am using swagger-ui to browse a set of APIs. Both the UI and the APIs are deployed on the same domain/server. The API is protected against CSRF by setting a cookie with a CSRF-Token. All Ajax requests are expected to send the value of the cookie in an X-CSRF-Token header otherwise are considered forgeries and are rejected.

As expected, after enabling CSRF protection, all POST/PUT requests initiated from swagger-ui will result in a 401.

Is there a way to customise the headers of the requests to include a dynamic value? (the token is generated for each session)

Ex. 
```javascript
xhr.setRequestHeader('X-CSRF-Token', $.cookie('CSRF-Token'))
```

**Comment by knicholes** [comment]
I have this same problem.  You can set the header with something like 
```javascript
        var csrfCookie = getCookie(CSRF_TOKEN_NAME);
        var csrfCookieAuth = new SwaggerClient.ApiKeyAuthorization("XSRF-TOKEN", csrfCookie, "header");
        swaggerUi.api.clientAuthorizations.add("XSRF-TOKEN", csrfCookieAuth);```

But then that only works once, and every request has the incorrect header and it always fails.  I wish it were clearly documented where we can into swaggerUI's XHR requests.  I'll try using some jquery interceptors to see if I can update this header each time a new XHR is completed.

**Comment by ponelat** [comment]
The clientAuthorizations are interceptors.
Here is a gist showing how to add some dynamic headers...

https://gist.github.com/ponelat/b5ff602aa56d80f7b614

each key in the interceptors will be part of the `clientAuthorizations`
NOTE: to access a cookie, you need to parse the cookie string (this is basic javascript, not swagger)
There are some libs to do it, but take a look at the output like this...
```javascript
var cookie_str = document.cookie;
console.log(cookie_str); // will show you the raw cookie header that you _can_ access
```

**Comment by fehguy** [comment]
Please reopen if you're still having issues with this.

**Comment by patricknolan** [comment]
This is what seems to work for me. 

I'm using ASPNET Core and Swashbuckle.AspNetCore

Does anyone see anything wrong with this?

    authorizations: {
          csrf: function() {
            var cookiearray = document.cookie.split(';');
            for(var i =0 ; i < cookiearray.length ; ++i){ 
              if(cookiearray[i].trim().match('^XSRF-TOKEN=')){ 
                this.headers['RequestVerificationToken'] = 
                  cookiearray[i].replace(`XSRF-TOKEN=`,'').trim();
              }
            }
            return true; // there is a bug, fixed but not in develop_2.0 where returning true will only process _one_ interceptor, you can leave this if it's your only interceptor and when the fix is in, it'll work as expected
          }

**Comment by patricknolan** [comment]
My only issue now is that the first time I hit my service (so I have no cookies yet) I get "The required antiforgery cookie ".AspNetCore.Antiforgery.dHhT1lYi0Ys" is not present."

As I receive the antiforgery cookie from my first call all subsequent calls work.

Does anyone know the correct way of handling this?

**Comment by patricknolan** [comment]
Answer to my question above in case anyone else has same issue...

        public virtual async Task<IActionResult> Login([FromBody] AccountLoginModel model)
        {
                var result = await this.SignInManager.PasswordSignInAsync(model.Email, model.Password, isPersistent: model.RememberMe, lockoutOnFailure: false);
                if (!result.Succeeded)
                {
                    return this.BadRequest();
                }
                var user = await this.UserManager.FindByEmailAsync(model.Email);

                // Must manually set the HttpContext user claims to those of the logged
                // in user. Otherwise MVC will still include a XSRF token for the "null"
                // user and token validation will fail. (MVC appends the correct token for
                // all subsequent reponses but this isn't good enough for a single page
                // app.)
                var principal = await this.PrincipalFactory.CreateAsync(user);
                this.HttpContext.User = principal;

                // Update XSRF token
                var tokens = this.Antiforgery.GetAndStoreTokens(this.HttpContext);

                return this.Ok();
        }

**Comment by patricknolan** [comment]
I just noticed that this.Antiforgery.GetAndStoreTokens(this.HttpContext); is not changing the value of XSRF-TOKEN. Shouldn't this update based on the fact I have changed the HttpContext.User to be the new principal?

**Comment by NiketBajaj** [comment]
I like to know if we have any solution to this problem.

I'm also using ASPNET Core and Swashbuckle.AspNetCore.

And all my controller have ValidateAntiForgeryToken - with this I can't able to go the post/put/delete. I do have [Authorize(Policy = "AdminOnly")] which I do by login in to my AuthenticationController.

How to pass AntiForgeryToken from swagger UI ?

**Comment by pgyschuk** [comment]
I was able fix CSRF problem and to use Swagger "Try it out" post request using `requestInterceptor`

`"swagger-ui-react": "3.31.1"`

React code example
```
import React from 'react';
import SwaggerUI from "swagger-ui-react"
import "swagger-ui-react/swagger-ui.css"
import Cookies from 'universal-cookie';
const cookies = new Cookies();
const DocsPage = () => (
  <SwaggerUI url="/v2/api-docs" requestInterceptor={(request) => {
    request.headers['X-XSRF-TOKEN'] = cookies.get("XSRF-TOKEN")
  }}/>
);

export default DocsPage;
```

**Comment by mllab-nl** [comment]
This might be useful to some of you searching: 
	function getCookie(name) {
		var match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));
		if (match) return match[2];
	}
	
	var ui = SwaggerUIBundle({
	        ...
		requestInterceptor: (request) => { request.headers['X-XSRF-TOKEN'] = getCookie('XSRF-TOKEN'); return request; }
	});
