### ISSUE TITLE
OAuth2 application flow

### ISSUE THREAD

**Issue by ksmithut** [swagger-api/swagger-ui#1383]
Please let me know if this is not the right place to ask this.

I am trying to setup my swagger api to be accessible through swagger-ui, but I'm unable to find out how this is supposed to work.

My securityDefinitions in my json looks like this:

```
{
  ...
  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "tokenUrl": "http://localhost:5100/oauth/token",
      "flow": "application",
      "scopes": {
        "read": "read access"
      }
    }
  }
}
```

When I attach the "security" property to an endpoint, I get the little on/off switch in the ui to turn on authentication. A dialog pops up with the "read" scope, I check the box and click on "Authorize". It seems to be trying to redirect to the "authorizationUrl", but that's not how the application flow works. According to [the spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-15) the authorization url is not a requirement for the application flow, but the tokenUrl should be used. Am I doing something wrong?

I'm not sure what information you need, but I'm using version 2.1.0 of swagger-ui and my swagger api is swagger 2.0 compliant. Let me know what other information you need.

**Comment by webron** [comment]
The current version supports only accessCode and implicit flow. Unfortunately, there's no support for the application flow yet.

**Comment by ksmithut** [comment]
Thanks for your quick response. Is that in the works to be supported in the future?

**Comment by webron** [comment]
I don't recall anyone asking for it specifically, and it is not actively developed at the moment. The existing flows were contributed to us by the community and we'd be more than happy to accept contributions for this flow as well.

**Comment by ksmithut** [comment]
Alright, I'll attempt to wrap my head around the codebase this weekend and see what I can do over the next few weeks.

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-ui/pull/878 added support for the accessFlow code. It may help you understand what needs to be changed and where in order to add support for the application flow. Keep in mind some of the code may have shuffled around, but I hope it helps.

**Comment by webron** [comment]
Also, tests would be great :)

**Comment by ksmithut** [comment]
I figured that was a given :) That link definitely helps speed up my search

**Comment by TomDemeranville** [comment]
Any news on this @ksmithut ?  If not I may look at it myself.

**Comment by ksmithut** [comment]
@TomDemeranville I haven't had a chance to look at it in depth yet. You're welcome to it :)

**Comment by sansjunk** [comment]
+1. Would love see this supported. 
I just wanted to check if any forks have implemented this?

**Comment by TomDemeranville** [comment]
I've just made this work locally.  I'll fix it up to work with master and send a pull request sometime next week.

@fehguy I've also added the ability to handle two different OAuth schemes via one API.  e.g. accessCode and application.  not sure if there's a formal feature request for it, but I've seen others raise it as an issue somewhere.

**Comment by TomDemeranville** [comment]
Fixed.  Pull request here: https://github.com/swagger-api/swagger-ui/pull/1825

**Comment by fehguy** [comment]
thank you @TomDemeranville, I will test and give feedback or merge!
