### ISSUE TITLE
oAuth toggle appears in non-oAuth operation views.

### ISSUE THREAD

**Issue by brownstein** [swagger-api/swagger-ui#1386]
If any oAuth security definitions are present in a swagger spec, the current build will incorrectly display an oAuth toggle in non-oAuth views. Please review and merge https://github.com/swagger-api/swagger-ui/pull/1387 (effectively a one-liner) to fix.

**Comment by webron** [comment]
@brownstein - The online pet store doesn't seem to exhibit this issue.. and it uses the current build.

**Comment by brownstein** [comment]
@webron Yes it does; both master and develop_2.0 exhibit this behavior. The pet store spec lists /pet/{petId} as using api_key for security, the UI definitely still displays the oAuth toggle.

**Comment by webron** [comment]
Right you are. It looks like if there are other operations under the same path with OAuth declarations it would affect all. I was looking at the `/user` operations which don't show it at all.

**Comment by brownstein** [comment]
Indeed; its a minor glitch in how the view code iterates over the available security definitions (it applies any oAuth it sees instead of checking to see if it matches the one declared for the operation). Let me know if there's anything else I need to do to that PR to fix.

**Comment by brownstein** [comment]
Looks fixed.
