### ISSUE TITLE
OAuth flow only selected scopes should be sent to Authorize endpoint

### ISSUE THREAD

**Issue by bigtlb** [swagger-api/swagger-ui#1388]
When clicking on the logon switch, the popup dialog allows a user to select which scopes to authenticate with.  This works fine the first time.  But, subsequent calls are a union of all scopes checked on all previous popup dialogs.

For example:  

* An OAuth service has two scopes - **domain_test** and **domain_prod**
  * Click the logon switch and select **domain_test**, **<code>scope=domain_test</code>** is sent to authorize endpoint
  * Click the logon switch a second time, and select **domain_prod**, both scopes are sent to the authorize endpoint

**Comment by bigtlb** [comment]
Created pull request #1389 which should address this.

**Comment by webron** [comment]
Fixed in 2.1.1. Thanks for the PR.
