### ISSUE TITLE
Testing API results in empty response body

### ISSUE THREAD

**Issue by lucian303** [swagger-api/swagger-ui#1390]
I get this when testing an API endpoint with oAuth2 validation:

```
Response Body
no content

Response Code
0

Response Headers
{
  "error": "no response from server"
}
```

The curl request line works perfectly from the command line. It seems that the Authorization header is not added to the request. The oAuth button is blue and 'on.'

**Comment by webron** [comment]
Can you check the network tab in your web console to see what's actually being sent?

**Comment by webron** [comment]
Also, which version of the UI do you use?

**Comment by lucian303** [comment]
I'm on 2.1.1 (master). Ok, so there are two problems.

One seems to be that it's sending an OPTIONS request instead of a GET request. My testing endpoints are actually here: https://apidev.unifiedcompliance.com/swagger/swagger-0.1.0.yaml and they're both GET. 

The other problem is that it's not sending the Authorization header with the Bearer signature or any Authorization header at all. So even if it's changed to a get request, it will fail there. 

The curl call listed on the page works perfectly and is: 

```curl -X GET --header "Accept: application/json" --header "Authorization: Bearer auth_token_here" "https://apidev.unifiedcompliance.com/dictionary-term/2"```

The curl call actually made as an xhr is below and it doesn't work because the method is wrong and the authorization header is missing.

```curl 'https://apidev.unifiedcompliance.com/dictionary-term/2' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: https://omtdev.unifiedcompliance.com:8500' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8,ro;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36' -H 'Accept: */*' -H 'Referer: https://omtdev.unifiedcompliance.com:8500/' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Access-Control-Request-Headers: accept, authorization' --compressed```

**Comment by lucian303** [comment]
So the problem here was actually with the preflight CORS requests. My OPTIONS endpoint was returning a 4xx. I've fixed my API and am now able to test.

**Comment by govind-s** [comment]
@lucian303 Can you share what fix you have added? I have same scenario.

**Comment by lucian303** [comment]
@govind-s I added CORS support to the API I was hitting. See http://www.html5rocks.com/en/tutorials/cors/
