### ISSUE TITLE
Subs of "allOf" definitiions get all properties of the ensemble

### ISSUE THREAD

**Issue by gaaf** [swagger-api/swagger-ui#1400]
When defining a "allOf" definition, a part which is referenced gets all the properties the ensemble gets. It should keep only its own properties.

In the example below, the "Param" definition incorrectly gets the "param2" property from the "ParamExtended" definition in the ui. It should only have the "test" property.

This is on 2.1.0+ @d75505fb73a6ac4ecbeabc47bd5a42b0f4d3f270

``` json
{
    "swagger": "2.0",
    "basePath": "/", 
    "schemes": [
        "https"
    ],
    "info": {
        "version": "2.1.0",
        "title": "allOf bug demo"
    },
    "paths": {
        "/allof": {
            "post": {
                "parameters": [
                    {
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Param"
                        }
                    }
                ],
                "responses": {
                    "default": {
                        "description": "Return"
                    }
                }
            }
        }
    },
    "definitions": {
        "Param": {
            "type": "object",
            "properties": {
                "test": {
                    "type": "string"
                }
            }
        },
        "ParamExtended": {
            "allOf": [
                { "$ref": "#/definitions/Param" },
                {
                    "type": "object",
                    "properties": {
                        "param2": {
                            "type": "string"
                        }
                    }
                }
            ]
        }
    }
}
```

**Comment by jasonh-n-austin** [comment]
Looks like this is the UI aspect of implementing `allOf` in `swagger-js`: https://github.com/swagger-api/swagger-js/pull/456

**Comment by webron** [comment]
@jasonh-n-austin - yeah, this issue and #1399 should both be controlled by swagger-js.

**Comment by jasonh-n-austin** [comment]
Specifically, in the 'limitations` of swagger-js#456, "The rendering support is not complete. The objects will contain the necessary reference information, but the json sample & mock signatures are not added". I'm assuming this is the rendering support, but the question is, should this be a bug in swagger-js instead?

**Comment by webron** [comment]
Right, the support is not complete doesn't mean that's what's supported should work properly ;) and indeed it is a bug. Should have a respective bug in js as well, yes.

**Comment by jasonh-n-austin** [comment]
Digging into issues a bit deeper, it seems like this might be caught up in moving rendering out of swagger-js and into swagger-ui: https://github.com/swagger-api/swagger-ui/issues/1248. 
@fehguy amirite :question:

**Comment by webron** [comment]
This is no longer an issue in 3.0.
