### ISSUE TITLE
gulp-less version(s) regression

### ISSUE THREAD

**Issue by agubler** [swagger-api/swagger-ui#1403]
Is there any reason why the version of the gulp-less dependency has reverted from "^3.0.1" in v2.1.5-M2 back to "^2.0.1" in v2.1.6-M1 (and upwards to 2.1.8-M1)?

It is causing the error `TypeError: Object #<lib$es6$promise$promise$$Promise> has no method 'done'` during the gulp process.

**Comment by fehguy** [comment]
I believe this is fixed now--please reopen if you're still having an issue.
