### ISSUE TITLE
Ignores basePath when multiple different basePaths are used

### ISSUE THREAD

**Issue by phillro** [swagger-api/swagger-ui#1404]
Given a parent API Doc such as:
https://gist.github.com/phillro/329aa2a2b96837ba8082

Where each resource API doc has a different basePath, the first resources basePath is used for all resources, and their individual basePath value is ignored.

**Comment by webron** [comment]
That works as designed. If you need support for it, you'd have to use the older version - https://github.com/swagger-api/swagger-ui/tree/v2.0.24.

**Comment by phillro** [comment]
The design is to ignore the basePath of resource docs?

**Comment by webron** [comment]
Yes, that's a functionality that was removed in 2.0 and the new version of the UI converts all older versions to 2.0 prior to rendering.

**Comment by phillro** [comment]
v2.0.24 exhibits the same behavior actually.

**Comment by webron** [comment]
Make sure you clear your cache. If that doesn't work, you can try an older version.

**Comment by fehguy** [comment]
This is not a bug of the 2.0 spec support.  Please see cumulative release note that makes this point:

https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.0-M2
