### ISSUE TITLE
can't send POST data 

### ISSUE THREAD

**Issue by xackobo** [swagger-api/swagger-ui#1409]
When I try to send some data via PHP it doesn't arrives to the server but it do with i.e. Postman.

For some reason it's using 'x-www-form-urlencode' not 'application/x-www-form-urlencode'.

Can you solve it?

Thanks!

**Comment by ponelat** [comment]
Thanks xackobo, but I think you were using the editor?... that'll be in this repo...https://github.com/swagger-api/swagger-editor

**Comment by xackobo** [comment]
Ops! thanks!

**Comment by webron** [comment]
Closing for wrong project ;)
