### ISSUE TITLE
Swagger UI does not pick the correct OAuth endpoint during authentication

### ISSUE THREAD

**Issue by bertramn** [swagger-api/swagger-ui#1410]
I am having issues to get swagger-ui to work with an API that requires access tokens from 2 different issuers. The OAuth setup works for a single issuer.  However when I add another issuer into the swagger.json and adjust the security tag on some methods to use the other issuer, the swagger-ui only ever pics the last issuer in the list to present the logon screen. Below the setup I roughly have:

the 2 methods: 

```json
"/methodA": {"get": {
  "tags": ["a"],
  "summary": "method A is only accessible with tokens from issuer A",
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "parameters": [],
  "responses": {"200": {
    "description": "successful operation",
    "schema": {"type": "string"}
  }},
  "security": [{"iss_a": []}]
}}
```

```json
"/methodB": {"get": {
  "tags": ["b"],
  "summary": "method B is only accessible with tokens from issuer B",
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "parameters": [],
  "responses": {"200": {
    "description": "successful operation",
    "schema": {"type": "string"}
  }},
  "security": [{"iss_b": []}]
}}
```

the issuers configuration

```json
"securityDefinitions": {
  "iss_a": {
    "type": "oauth2",
    "authorizationUrl": "https://login.issuer-a.com/authorize",
    "flow": "implicit",
    "scopes": {"openid": ""}
  },
  "iss_b": {
    "type": "oauth2",
    "authorizationUrl": "https://login.issuer-b.com/authorize",
    "flow": "implicit",
    "scopes": {"openid": ""}
  }
}
```

I am using swagger 2.0 spec with swagger-ui version 2.1.0. I also tried the develop_2.0 branch without much luck.

Anyone got any suggestions of what may be going wrong here?

Thanks a lot.

**Comment by fehguy** [comment]
I believe this is a limitation of the current implementation.  It does not expect to have multiple issuers--I'll flag this as a feature enhancement.

**Comment by TomDemeranville** [comment]
Fixed. You can now select from multiple authentication schemes/issuers/securityDefinitions.  

 Pull request here: https://github.com/swagger-api/swagger-ui/pull/1825

**Comment by fehguy** [comment]
this has been merged to master
