### ISSUE TITLE
Incorrect request payload type when using verb DELETE

### ISSUE THREAD

**Issue by codeHatcher** [swagger-api/swagger-ui#1411]
When I set parameter content type as "application/json"
![image](https://cloud.githubusercontent.com/assets/5360982/8348872/077470d6-1acd-11e5-8bd9-04827aeb329a.png)
swagger-ui sends it as form data
![image](https://cloud.githubusercontent.com/assets/5360982/8348884/13e92c1c-1acd-11e5-8820-4b43f519af43.png)

**Comment by webron** [comment]
Which version of swagger-ui are you using?

**Comment by webron** [comment]
Thanks for reporting. Closing this as a dupe of #1435 since we've done further investigation there.
