### ISSUE TITLE
Swagger API client authorization not used in OPTIONS call

### ISSUE THREAD

**Issue by j3grewal** [swagger-api/swagger-ui#1413]
I am making use of custom headers by setting a header through clientAuthorizations in swagger API. I am using this to pass in a required header needed for authentication in my service. However, my api calls fails on OPTIONS call as this header is not passed to OPTIONS call. If I expose my OPTIONS endpoint to public, it works fine. If the client authorizations can be passed into OPTIONS call as well, I won't need to expose these endpoints.

**Comment by ponelat** [comment]
In general OPTIONS calls need to be publicly accessible. This is how browsers what can and can't be accessed. Swagger will fail if it can't get to the OPTIONS. This is true for all browser ajax calls (unless I stand corrected)

**Comment by j3grewal** [comment]
Agreed, in general. But if your API requires authorization, would it be wrong to expect the same level of authorization for OPTIONS calls as well.
Also, what happens if an API does not implement OPTIONS call. Do swagger calls fail then? If not, should they fail if they get 401 back?

**Comment by ponelat** [comment]
This isn't really related to swagger and more about CORS. Which requires pre-flight requests (OPTIONS).
Its not something we designed, its part of the CORS requirements.
So if your server is on another domain from your browser client, it will be subject to CORS and requires the above.

Take a look here for some more info...
http://enable-cors.org/
http://www.html5rocks.com/static/images/cors_server_flowchart.png

**Comment by fehguy** [comment]
Please reopen if still an issue.  CORS is ugly, and you'll just have to dig into it's ugliness to understand it fully.
