### ISSUE TITLE
Inline model definitions display undefined instead of the model

### ISSUE THREAD

**Issue by revent68** [swagger-api/swagger-ui#1415]
The UI tool does not display the model correctly for inline parameters with a schema. Schema displays for our json file in the editor.
![swagger-ui_inline-request-model-undefined_json-sample-blurred](https://cloud.githubusercontent.com/assets/13054329/8363784/30264298-1b36-11e5-9474-cfdc7d39806c.png)
![swagger-ui_inline-request-model-undefined-blurred](https://cloud.githubusercontent.com/assets/13054329/8363789/33af2042-1b36-11e5-85c7-4b97a20f3611.png)

**Comment by whitlockjc** [comment]
What version of swagger-ui are you using?  If I remember correctly, we fixed this.

**Comment by revent68** [comment]
Tried a couple different versions including the latest from master.

**Comment by whitlockjc** [comment]
Can you trying setting `type` to `object` in your `schema` and let me know if that fixes your issue?

**Comment by revent68** [comment]
Adding "type":"object" inside the schema does fix the issue. Thank you!
