### ISSUE TITLE
File upload always sends 47 byte body

### ISSUE THREAD

**Issue by MHova** [swagger-api/swagger-ui#1416]
I'm trying to make use of the swagger-ui [file upload] (https://github.com/swagger-api/swagger-ui/pull/42) feature. My Spring MVC endpoint is annotated as such:

```java
    @RequestMapping(value = "/{id}", method = PUT, consumes = "*/*")
    @ApiOperation(
            value = "Upload a file",
            notes = "Some notes")
    @ApiImplicitParams({@ApiImplicitParam(name = "file", value = "file", required = true, dataType = "file", paramType = "body")})
    public ResponseEntity<?> putFile(@PathVariable final String id,
            @ApiIgnore @RequestBody final byte[] file) throws IOException {

        logger.info("Bytes {}", file.length);
        Files.write(file, new File("c:\\someFile.jpg"));
        
        return new ResponseEntity<Void>(HttpStatus.CREATED);
    }
```

swagger-ui correctly displays the file chooser, but when I select a file and click "Try It Out", the content size of the request sent to my server is always just 47 bytes. I am using Firefox 38.0.5 on Windows 7. Here's a screenshot of the request details captured by Firefox:

![firefox](https://cloud.githubusercontent.com/assets/5972021/8364061/2e8891f0-1b38-11e5-98fc-fad976e89023.png)

Am I doing something wrong?

**Comment by MHova** [comment]
I also noticed that swagger-ui sends the request as `Content-Type:multipart/form-data` even though this is a PUT endpoint. Is there a way to specify a content-type in swagger-ui if the endpoint accepts `*/*`?

**Comment by webron** [comment]
Which version of swagger-ui do you use?

If you want to use file upload, you have to use the `multipart/form-data` or `application/x-www-form-urlencoded` regardless of the HTTP verb used.

**Comment by MHova** [comment]
Thanks for looking into this.

I'm using the latest [Springfox swagger-ui](https://github.com/springfox/springfox/tree/master/springfox-swagger-ui), which uses [swagger-ui 2.1.0](https://github.com/springfox/springfox/commit/bfc534247fb5fa22aca1638572744c099770b6a5) underneath the hood.

Let me phrase my question another way. How can one invoke a `PUT` file upload endpoint using `swagger-ui`? Is it currently possible? If so, how? If not, can support be added using `XMLHttpRequest`?

**Comment by MHova** [comment]
Any update on this?

**Comment by webron** [comment]
I'd need to see the Swagger definition you get for the file upload.

**Comment by MHova** [comment]
Sorry about that. Here's the relevant portion of the swagger json.

``` javascript
"put": {

    "tags": 

[

    "documents"

],
"summary": "Create or update a hosted document",
"description": "An accompanying metadata resource at /metadata/{id} must already exist. Attempts to create/update an externally hosted document will be redirected.",
"operationId": "putDocumentUsingPUT",
"consumes": 
[

    "*/*"

],
"produces": 
[

    "*/*"

],
"parameters": 
[

{

    "name": "id",
    "in": "path",
    "description": "id",
    "required": true,
    "type": "string"

},
{

    "name": "Content-MD5",
    "in": "header",
    "description": "md5",
    "required": false,
    "type": "ref"

},
{

    "in": "body",
    "name": "document",
    "description": "document",
    "required": true,
    "schema": 

        {
            "$ref": "#/definitions/file"
        }
    }

],
"responses": 
{

    "200": 

{

    "description": "OK",
    "schema": 

    {
        "type": "string"
    }

},
"201": 
{

    "description": "Document created"

},
"204": 
{

    "description": "Document updated"

},
"400": 

        {
            "description": "Metadata must be created first|The Content-MD5 you specified did not match what we received."
        }
    }

},
```

**Comment by webron** [comment]
Unfortunately, that's a partial definition and I can't test with it. That shouldn't give you the option to upload a file, and is not the way to describe file uploads using Swagger.

**Comment by fehguy** [comment]
Please reopen if you're still having an issue.  From looking at your spec file, you were using an incomplete swagger implementation or one with a bug.
