### ISSUE TITLE
Doubled apiKey security credentials in generated cURL command 

### ISSUE THREAD

**Issue by PASSTor** [swagger-api/swagger-ui#1420]
I'm trying to build a page with two apIKey security credentials
```
...
"security": [
    { "key": [] },
    { "secret": [] }
  ],
...
```

I set both dynamically with two statements like this:
`window.swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("key", key, "query"));`

Now the issue is, once I visualise the page and play with request under **Try it out!** button: the request is working correctly, while **cURL** command is generated with doubled security credentials:
```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"email\": \"<my_email>\",
  \"password\": \"<my_password>\"
}" "https://<host_goes_here>/v1/sign_in?key=test_key&secret=test_secret&key=test_key&secret=test_secret"
```
, which is incorrect, of course.

I was able to track it down to 
```
Operation.prototype.asCurl = function(args) {
    var obj = this.execute(args, {mock: true});                    
    this.clientAuthorizations.apply(obj);
```
The issue is **BOTH** functions above do add security parameters to the URL. I have no idea what were the reasons to duplicate those lines, so opening this issue, rather than Pull Request.

P.S. i also had to fight another smaller issue, which I created Pull Request for: https://github.com/swagger-api/swagger-js/pull/509

**Comment by fehguy** [comment]
This should be fixed now.
