### ISSUE TITLE
Is it possible to hook custom onSuccess function to specific Operation?

### ISSUE THREAD

**Issue by PASSTor** [swagger-api/swagger-ui#1422]
In my REST API, there're several requests, that depend on each other. E.g. first one gives you a `magic token`, which you can use later in other requests.

Now in order to highlight the importance of dependencies, I would like to always show the latest value of `magic token` you received, while were playing with the API. In order to do so, I need to hook a custom onSuccess function to specific Operation, which produces (returns in response body) those `magic tokens`.

**Now, is it possible at all to write something like?**

```
$(window.swaggerUi.api.pet.findPetById).on('success', myCustomFunction);
```

As you may understand, I would need access to the response body in that custom function.

Thanks a lot for your help in advance.

**Comment by dolmen** [comment]
Yes, it is now possible, but in a different way!
I have implemented the functionality in #2424. It has been merged and it is available in v2.2.10.
