### ISSUE TITLE
$ref schema objects in Responses Definitions Object don't seem to be displayed correctly

### ISSUE THREAD

**Issue by Bazman** [swagger-api/swagger-ui#1423]
$ref schema objects in Responses Definitions Object don't seem to get referenced correctly.

In swagger-editor they do work correctly.

For example in the documentation generated with the YAML below, the /test get 200 response will not have the Success object definition. It will be blank.

Similarly with the Error object.

The description will work correctly, so its finding the response object ok, just not showing the response object.

``` yaml
# API
swagger: '2.0'
info:
  title: Test API
  description: Test API
  version: "0.0.1"
  contact:
    name: test@test.com
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json

paths:
  /test:
    get:
      responses:
        200:
          $ref: "#/responses/GeneralSuccess"
        404:
          description: Missing
        default:
          $ref: "#/responses/GeneralError"

definitions:
  Success:

  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string

###################
# Responses
###################
responses:
  GeneralSuccess:
    description: General success
    schema:
      $ref: '#/definitions/Success'

  GeneralError:
    description: General error
    schema:
      $ref: '#/definitions/Error'
```

**Comment by webron** [comment]
Which version of the UI have you tested it with? Just checked with master and it works fine.

Also, FWIW, having an empty model definition (`#/definitions/Success`) is ill-advised.

**Comment by Bazman** [comment]
I'm using the pre-built dist directory in master. I just updated to see if there were some updates I'd missed but we seem to be using the latest prebuilt dist (which says version 2.1.0 at the top of swagger-ui.js)

I've attached the screenshot of what I'm seeing (I blacked out the URL I'm operating on).

No schema for GeneralError response, or the GeneralSuccess. I added a property to the Success definition as well (think that was an oversight of mine earlier).

![screen shot 2015-07-06 at 10 23 35 am](https://cloud.githubusercontent.com/assets/1335418/8514117/c2506f2c-23c9-11e5-84fb-9d593aabb568.png)

![screen shot 2015-07-06 at 10 23 56 am](https://cloud.githubusercontent.com/assets/1335418/8514119/c97f46e2-23c9-11e5-8b90-9c495cbf9bd8.png)

**Comment by webron** [comment]
I see. So you load the YAML file directly from a hosted location? I think I remember seeing a similar issue.

Can you try converting the YAML to JSON and load that instead? Not as a solution but as a workaround.

**Comment by Bazman** [comment]
Yeah, although the host is the same host as what swagger-ui is installed on.

i.e. the url parameter parsed to swagger-ui is '/global_api/swagger.yaml'

Tried using JSON file and exact same result.

url parameter passed to swagger-ui was /global_api/swagger.json'

```json
{
    "swagger": "2.0",
    "info": {
        "title": "Test API",
        "description": "Test API",
        "version": "0.0.1",
        "contact": {
            "name": "test@test.com"
        }
    },
    "schemes": [
        "https"
    ],
    "basePath": "/v1",
    "produces": [
        "application/json"
    ],
    "paths": {
        "/test": {
            "get": {
                "responses": {
                    "200": {
                        "$ref": "#/responses/GeneralSuccess"
                    },
                    "404": {
                        "description": "Missing"
                    },
                    "default": {
                        "$ref": "#/responses/GeneralError"
                    }
                }
            }
        }
    },
    "definitions": {
        "Success": {
            "properties": {
                "successcode": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
        "Error": {
            "properties": {
                "code": {
                    "type": "integer",
                    "format": "int32"
                },
                "message": {
                    "type": "string"
                },
                "fields": {
                    "type": "string"
                }
            }
        }
    },
    "responses": {
        "GeneralSuccess": {
            "description": "General success",
            "schema": {
                "$ref": "#/definitions/Success"
            }
        },
        "GeneralError": {
            "description": "General error",
            "schema": {
                "$ref": "#/definitions/Error"
            }
        }
    }
}
```

**Comment by webron** [comment]
And if you pass a full URL instead of a relative one?

**Comment by Bazman** [comment]
Same result it seems.

I put that sample swagger.json up here:
https://gist.githubusercontent.com/Bazman/830e883e75aeb132c70d/raw/724b6c3444ca5196310dc32922cc81956b302aad/swagger

And uses my local swagger-ui install to load it with the same result.

**Comment by webron** [comment]
Okay, I'm 99% sure there's an open ticket about it but I can't find it now, so we'll keep this one open. There is indeed the issue you mention. The reason I didn't see it initially is that I test  by including the Swagger definition inline (rather then hosted) where the problem does not occur. As a workaround, for now, you can avoid referencing the global responses and repeat the definitions, but this indeed needs to be fixed.

**Comment by Gillingham** [comment]
Just encountered this same thing. Would really like to avoid the work-around of repeating as our API supports path separated and query separated arguments to API endpoints so the less we have to duplicate the better.

**Comment by webron** [comment]
PRs are always welcome.

**Comment by aaronb-cg** [comment]
I've also experienced this.
I'm new to Swagger but I've had a look at the code to try and see what's going on.

[OperationView.js l133](https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/OperationView.js#L133) processes the responses section for each path/httpMethod combo. It checks for references to definitions but when I log what we have here for our responses $ref it's already been parsed and converted to an object:
```javascript
this.model.responses: 
Object {
  default: Object {
    description: "An error occurred, see the message for more details"
    schema: Object {
      items: Object {
        properties: Object {
          logref: Object {...}
          message: Object{...}
    x-resolved-from: Array[1] {
      0: "#/responses/Error"
      ...
    }
  }
}
```
As it's not in the expected format it is skipped over and `this.model.responseMessages.responseModel` is left as `null`.

Looking at StatusCodeView, which I believe is called next, on [l12](https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/StatusCodeView.js#L12) that checks for the `responseModel` string in `this.router.api.models` which I can see from SwaggerClient (swagger-js/lib/client.js) [l290](https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L290) contains just the definitions converted to [Models](https://github.com/swagger-api/swagger-js/blob/master/lib/types/model.js).

I'd hoped one of the following two options would be a quick fix but neither of them will work:
* If the OperationView passed through the string name of the response then it wouldn't be found in the models
* If the OperationView passed through the already parsed schema object then that also wouldn't work as it's not an instance of Model.

That's as far as I've got so far. I've not yet determined what is converting the response ref into an object before it gets to OperationView, I'll look into that next.
If I can come up with a solution I will put together a PR, if not I'll report back with any more findings that may help someone else.
Any direction or pointers anyone can give me on this would be appreciated.

**Comment by aaronb-cg** [comment]
Ignore all of that.
Previously we were inlining our response definitions which lead to other problems but now we've moved them into actual definitions and just $ref'd them from the responses we're in the same situation as Bazman whereby it works when the spec is local but not when it's hosted.

I believe I've identified the issue and created a [PR](https://github.com/swagger-api/swagger-ui/pull/1512).
OperationView.render()'s parsing of the responses was just checking if the ref started with `'#/definitions/'`, not whether it *contained* it, and when pulled in over AJAX the refs have the URL prepended to them so it wasn't getting picked up.

**Comment by Bazman** [comment]
Great work. I had a look through the code but couldn't work it out myself. From your explanation and the PR looks like you've found the bug :+1:

**Comment by aaronb-cg** [comment]
It looks like this bug is scattered throughout the code, I've just encountered it again when trying to use a `response` definition for a success response. It seems this goes through a different code path to the error responses and hits [helpers.simpleRef()](https://github.com/swagger-api/swagger-js/blob/master/lib/helpers.js#L42). I'll get a PR up for that too (against swagger-js though, obviously).

**Comment by aaronb-cg** [comment]
I've now created a [PR](https://github.com/swagger-api/swagger-js/pull/551) for that too.

**Comment by MaienM** [comment]
The PR seems to fix the issue for me. Is there an ETA on when we can expect this to get merged?

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if you experience otherwise.
