### ISSUE TITLE
Feature-Request: Render Top-Level Element in Model Schema

### ISSUE THREAD

**Issue by adam-taras** [swagger-api/swagger-ui#1425]
I would be happy, if there would be an option in swagger-ui, that renders the top level element of the model schema.
# Example
The following swagger-definition:
```Json
{
  "swagger" : "2.0",
  "info" : {
    "description" : "Show case demo",
    "version" : "0",
    "title" : "Demo"
  },
  "host" : "petstore.swagger.io",
  "basePath" : "/frontend",
  "schemes" : [ "http" ],
  "paths" : {
    "/Method" : {
      "post" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/TopLevelRequest"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful processing",
            "schema" : {
              "$ref" : "#/definitions/TopLevelAnswer"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "TopLevelRequest" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string",
          "example" : "John Doe"
        },
        "address" : {
          "$ref" : "#/definitions/AddressType"
        }
      }
    },
    "AddressType" : {
      "type" : "object",
      "properties" : {
        "country" : {
          "type" : "string",
          "example" : "US"
        }
      }
    },
    "TopLevelAnswer" : {
      "type" : "object",
      "properties" : {
        "result" : {
          "type" : "string",
          "example" : "success"
        }
      }
    }
  }
}
```
is currently rendered this way:
![screen_02](https://cloud.githubusercontent.com/assets/7314434/8379203/b20380da-1c1e-11e5-9ca8-7e270dc9c239.png)

But for some legacy code, I need a rendering in that way:
* for the red marked box at the top:
```Json
{"TopLevelAnswer": {
  "result": "success"
}}
```
* and for the two red marked boxes on the bottom:
```Json
{"TopLevelRequest": {
  "name": "John Doe",
  "address": {
    "country": "US"
  }
}}
```
The main difference here is, that the top level types `"TopLevelAnswer"` and `"TopLevelRequest"` are rendered too. Of course, they also are embedded within opening and closing brackets `{` ... `}`.

It would be nice, if you could extend swagger-ui for this functionality. I tried to hack it myself, but it's too time expensive for me to get familiar with JavaScript and it's tool chain.

**Comment by ponelat** [comment]
That might be out of scope of JSON schema (which is what the definition is based on)
To solve your particular need, you can add a full example, which would get populated in the swagger-ui boxes...
This won't affect implementations derived from the spec, just the examples...
```
 "TopLevelAnswer" : {
      "type" : "object",
      "example": {"TopLevelAnswer": { "result": "success" }},
      "properties" : {
        "result" : {
          "type" : "string",
          "example" : "success"
        }
      }
    }
```

**Comment by adam-taras** [comment]
Hi ponelate. Thanks for your answer and your helpful advise. But we already use this solution for a minimal example, that contains only the necessary fields. And we wanted to have the full example as an option (e.g. by clicking on the right box). But I understand your argument with breaking the schema. So looks like, I have to seek for another solution to handle our legacy code.

**Comment by adam-taras** [comment]
I checked our code again and have to correct my answer. We are using the `default` field for the body parameter. So using your solution with the `example` field combined with our `default` field leads to exactly that behavior I was searching for.

Example: Again the swagger-definition from top of this page with the modifications:
```Json
  ...
  "paths" : {
        ...
        "parameters" : [ {
          "in" : "body",
          "default" : "{ \"TopLevelRequest\": {\n}}",
         ...
  },
  "definitions" : {
    "TopLevelRequest" : {
	  "example" : "{ \"TopLevelRequest\": {\n  \"name\": \"John Doe\",\n  \"address\": {\n    \"country\": \"US\"\n  }\n}}",
	  ...
```
![screen_03](https://cloud.githubusercontent.com/assets/7314434/8455522/8c3ca9c2-2005-11e5-8f26-4b5323762657.png)

So thank you again for your hint. Changing swagger-ui is not the right way. This workaround works for me. I think, we can close this issue.

**Comment by ponelat** [comment]
Awesome, glad you came right!
Pro tip: you don't need to escape the JSON inside `example`...
you can use real JSON and it'll get pretty printed out, so you don't need to worry about it. 
If you do want control over how it gets printed, you can use a string :smiley:

**Comment by adam-taras** [comment]
Well, it's getting even better :smile:. Thanks again
