### ISSUE TITLE
Swagger file requested many times

### ISSUE THREAD

**Issue by lucian303** [swagger-api/swagger-ui#1429]
The UI makes multiple XHR requests for the swagger file, until one of them returns. This can cause the UI to take half a minute or more to load, not to mention the inefficiency and problems with DOSing the endpoint. 

The expected behavior is that there will be one request.

**Comment by ponelat** [comment]
You've hit this bug... https://github.com/swagger-api/swagger-js/issues/489

**Comment by reesew** [comment]
Are there any known hacky workarounds to try in the meantime?

**Comment by lucian303** [comment]
I don't know any workarounds. Hoping it will get fixed soon.

**Comment by aurelian** [comment]
confirmed.

**Comment by ceritium** [comment]
+1

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please retest and reopen if it's not the case.
