### ISSUE TITLE
Swagger-UI doesn't render model's description 

### ISSUE THREAD

**Issue by Medii** [swagger-api/swagger-ui#1430]
According to https://github.com/swagger-api/swagger-ui/issues/751 , I expected swagger-ui to renders model's description, but it seem's it doesn't.
I checked my swagger JSON as it contains model's description.

Can you please let me know whether this feature has been implemented or not?

myModel: 

``` js
{
description: "my model description.",
type: "object",
properties: {id: {format: "int32" ,description: "Property description.",type: "integer"}
}
```

**Comment by caesarxuchao** [comment]
feature request+1 !

**Comment by andronat** [comment]
+1

**Comment by dothebart** [comment]
+1

**Comment by AdamNachman** [comment]
The key benefit here is that you don't have to maintain two entirely different sets of documentation - a document that describes the domain model and entities, and the api calls to mine it.

Having the ability to expose a brief explanation of what an entity represents and how it is used would be of massive benefit.

**Comment by jeffclary** [comment]
+1

**Comment by JeroenDeDauw** [comment]
+1

**Comment by JD-Sky** [comment]
+1

**Comment by jpuigsegur** [comment]
+1
No milestone for this feature ??

**Comment by webron** [comment]
It does now.

**Comment by munnaonc** [comment]
@webron 
Hi, I was just wondering, in which version the "model description feature" is released.

**Comment by webron** [comment]
Should be any version under 3.x.
