### ISSUE TITLE
HTTP status code 404 for DELETE not shown in UI correctly

### ISSUE THREAD

**Issue by typekpb** [swagger-api/swagger-ui#1431]
For the DELETE of the resource, which doesn't exist, we return HTTP code: `404`, however swagger UI seems to interpret it in a wrong way:

![delete_404_swagger](https://cloud.githubusercontent.com/assets/499820/8431883/bda71926-1f3c-11e5-97e5-f5d205d58bfc.png)

However firebug shows:
![delete_404_firebug](https://cloud.githubusercontent.com/assets/499820/8431887/c3711d66-1f3c-11e5-9bd5-8c45cc893891.png)

Moreover if I curl it, I get:

	curl -i -X DELETE --header "Accept: application/json" --header "Authorization: Basic <...>
	HTTP/1.1 404 Not Found
	Access-Control-Allow-Origin: *
	Access-Control-Allow-Methods: POST, GET, PUT, DELETE, PATCH
	Access-Control-Allow-Headers: Accept, Content-Type, Authorization
	Content-Type: application/json
	Transfer-Encoding: chunked
	Date: Tue, 30 Jun 2015 13:30:21 GMT
	Server: WebServer

	Couldn't find entity <...>

**Comment by webron** [comment]
Which version of swagger-ui do you use?

Is the firebug screenshot when you execute it via the UI or another tool?
Do you see anything different in FF's web console's network tab?

**Comment by typekpb** [comment]
>Which version of swagger-ui do you use?

we have a bit customized version (self hosted badge as well as basic auth fields added), but the latest upstream commit it holds is: https://github.com/swagger-api/swagger-ui/commit/c7e07705f22f406caf258e1a032e3dd499c452b3

>Is the firebug screenshot when you execute it via the UI or another tool?

using Swagger UI

>Do you see anything different in FF's web console's network tab

nope, shows 404 as well, with the error msg we provide from the server.

**Comment by typekpb** [comment]
OK, I think I've found an issue, as we were returning not a valid json in the response body, but string only. 

I tried with the:

    "Content-Type": text/plain

and now the Swagger UI shows the correct response code. So it sounds it could not interpret the result correctly with the `Content-Type:application/json` with invalid json. 

Should I close the issue, or is there a need to fix the Swagger UI to overcome situations like this?

**Comment by webron** [comment]
Yeah, the UI is a bit sensitive when it comes to handling content-types. I *think* we have a similar issue open, however I'm not sure. I'd suggest closing this one and opening a specific one about gracefully handling erroneous responses when it comes to content-type (specifically `application/json` as it tries to parse it).

**Comment by typekpb** [comment]
OK, will do
