### ISSUE TITLE
Localization and translation doesn't work

### ISSUE THREAD

**Issue by rubenmch** [swagger-api/swagger-ui#1432]
There isn't any `data-sw-translate` attributes defined. And there isn't any call to `SwaggerTranslator.translate()` so following the readme instructions for localization won't translate anything.

The readme instructions say the following needs to be added to index.html:

```html
<script src='lang/translator.js' type='text/javascript'></script>
<script src='lang/en.js' type='text/javascript'></script>
```

**Comment by bnupaladin** [comment]
I guess you should do it yourself. Add data-sw-translate attribute to tags you want to translate, most in swagger-ui.js. When swagger-ui updates, you should do it again again and again.

**Comment by ponelat** [comment]
Translation has been up'd and in a PR...  fork/comment if you need :)
https://github.com/swagger-api/swagger-ui/pull/1375

**Comment by fehguy** [comment]
Please reopen if still an issue.
