### ISSUE TITLE
loading my swagger.yaml file

### ISSUE THREAD

**Issue by jabr9983** [swagger-api/swagger-ui#1433]
How do I go about loading my swagger.yaml file into swagger ui, there really isn't any documentation on that, and I can't seem to get it working.

**Comment by J4mey** [comment]
Do you mean loading your JSON file? If so, download your JSON file from the swagger editor. Copy and paste that JSON into a Github repository (or somewhere you can turn that raw JSON into a URL). Then copy and paste that URL into the source code of the Swagger index.html file. Hope this helps.

**Comment by jabr9983** [comment]
Thanks I will give it a try now

**Comment by jabr9983** [comment]
Okay I am not getting the option to download the JSON file from the editor.

**Comment by jabr9983** [comment]
Can you give me an example of the url you would be putting in the index.html file please, I'm new to all this stuff so definitely still learning.

**Comment by ponelat** [comment]
The URL from a github repo would look like this...
https://raw.githubusercontent.com/ponelat/swagger-ui/develop_2.0/test/specs/v2/petstore.json
You need to click on the 'raw' button when viewing your file.
A better solution is to use the (free) service from https://rawgit.com/.

**Comment by jabr9983** [comment]
Thank you very much
