### ISSUE TITLE
Response description does not render markdown not designated as code

### ISSUE THREAD

**Issue by lucian303** [swagger-api/swagger-ui#1434]
Only text in between the ``` and ``` is rendered for a responses's description. See below for screenshots from the editor (with the text) and from swagger-ui (without the request/response text).

![screen shot 2015-06-30 at 4 56 01 pm](https://cloud.githubusercontent.com/assets/288151/8441859/105f49c0-1f49-11e5-8cc9-196249f5edc7.png)

![screen shot 2015-06-30 at 4 56 25 pm](https://cloud.githubusercontent.com/assets/288151/8441860/126fd3e2-1f49-11e5-860d-8182de126058.png)

**Comment by webron** [comment]
A Swagger definition snippet would help to analyze this.

**Comment by lucian303** [comment]
@webron Yes, the response section that generated this was:

```
      responses:
        200:
          description: |
            ## Success

            ### Request
            ```curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer oauth2_access_token_here"  https://api.com/control```
            ### Response
            ```
            {
```

the rest of the JSON response was here.

**Comment by drewish** [comment]
I don't think this is actually a bug. The behavior is consistent with GFM:

## Success

### Request
```curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer oauth2_access_token_here"  https://api.com/control```
### Response
```
{
   ...
}
```

If you want the block style you'll need to use multiple lines.

**Comment by drewish** [comment]
Sorry took me a minute to understand there were two separate images there. The first being the editor and second swagger-ui. It does seem like something's incorrect.

**Comment by heldersepu** [comment]
I imagine that most developers keep the response.description short ...
And detailed description usually goes on operation.description 

But Markdown is now supported in the response.description there are a few style issues:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Company/Company_Get
You can see that the `###` are barely visible

**Comment by shockey** [comment]
Closing as an old 2.x issue, feel free to reply if you think this is in error!
