### ISSUE TITLE
swagger DELETE requests changing to incorrect content type

### ISSUE THREAD

**Issue by J4mey** [swagger-api/swagger-ui#1435]
Swagger DELETE requests are submitted as "Content-Type: application/json", however, they are showing up as "Content-Type: application/x-www-form-urlencoded" in API logs. I am receiving an error in the response body saying the format is incorrect when it actually is correct. Please advise. 

![image](https://cloud.githubusercontent.com/assets/13053168/8441906/569db3e0-1f49-11e5-8da1-3fdf6a16fe98.png)

![image](https://cloud.githubusercontent.com/assets/13053168/8441965/b493f7ac-1f49-11e5-9f59-be64cd7e1451.png)

**Comment by ponelat** [comment]
This sounds like a bug I've heard of... thanks for pointing it out

**Comment by webron** [comment]
@J4mey - thanks for reporting.

Which version of swagger-ui are you using?

Can you check your browser's web console's network tab and see what's actually being sent when you click the try it now button?

Can you share your Swagger definition too? Testing the pet-store's delete operations, the problem does not seem to be reproduced.

**Comment by J4mey** [comment]
@webron - Thank you for your response. Extra info is below.

I'm using Swagger-UI version 2.1

I checked Chrome's web console network tab and here is what the Request Headers looks like.
Accept:application/json
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:33
Content-Type:application/x-www-form-urlencoded

Swagger definitions are below

    delete:
      parameters:
        - name: email_address_or_contact_ID
          in: path
          description: Must provide Contact ID or Email Address of contact
          required: true
          type: string
        - name: body
          in: body
          description: User needs to specify either id or name of the Tag that needs to be deleted for the Contact.
          required: true
          schema:
            $ref: '#/definitions/Contact'


    Contact:
    properties:
      contactId:
        type: string
        description: unique identifier for contact
      firstName:
        type: string
        description: "contact's first name"
      lastName:
        type: string
        description: "contact's last name"
      title:
        type: string
        description: "contact's title at their place of business"
      company:
        type: string
        description: company name
      emails:
        type: array
        description: emails
        items:
          $ref: '#/definitions/Email'
      phones:
        type: array
        description: phones
        items:
          $ref: '#/definitions/Phone'
      tags:
        type: array
        description: tags
        items:
          $ref: '#/definitions/Tag'
      campaigns:
        type: array
        description: current and past campaigns
        items:
          $ref: '#/definitions/Campaign'
      status:
        type: object
        $ref: '#/definitions/ContactStatus'
      temperature:
        type: object
        $ref: '#/definitions/ContactTemperature'
      salesRep:
        type: object
        $ref: '#/definitions/ContactSalesRep'
      addresses:
        type: array
        description: street addresses
        items:
          $ref: '#/definitions/StreetAddress'
      subscribed:
        type: boolean
        description: email marketing opt-in
      timezone:
        type: string
        description: timezone
      socialNetworks:
        type: array
        description: social network links for contact
        items:
          $ref: '#/definitions/SocialNetwork'
      instantMessaging:
        type: array
        description: instant messaging ids
        items:
          $ref: '#/definitions/InstantMessaging'
      website:
        type: array
        description: websites for this contact
        items:
          $ref: '#/definitions/Website'
      source:
        type: string
        description: lead source
      referredBy:
        type: string
        description: optional contact name who may have referred this contact
      customFields:
        type: array
        description: custom fields for this contact
        items:
          $ref: '#/definitions/CustomField'

**Comment by webron** [comment]
Thanks but is that the complete definition? Looks like it's missing the `consumes` property.

**Comment by J4mey** [comment]
@webron I tried multiple different variations of the definition using the `consumes` and `produces` properties. It still threw an error in each instance. I can post those different variations as well if you'd like.

**Comment by webron** [comment]
Thing is this, the pet store sample works fine for delete, so I need something that reproduces it fully. One definition, beginning to end, that I can just load and try to see.

**Comment by J4mey** [comment]
@webron  Here is the link to the full JSON file I am using. Thanks for the swift responses. Any help is greatly appreciated.

https://github.com/J4mey/swagger-testing-current/blob/swagger-test-clean-code/clean-JSONV1.1

**Comment by webron** [comment]
Aha! The problem is when adding a `body` parameter to a `DELETE` operation. This indeed causes the content type to magically change to `application/x-www-form-urlencoded` so there's definitely a bug.

I'll refrain from going into the debate of practices of sending a body in a `DELETE` API call though ;)

**Comment by J4mey** [comment]
@webron Thanks so much for pinpointing this issue! I am familiar with some of the best practices for a `DELETE` call, and understand that this doesn't necessarily adhere to that. However, we are developing for another API and are trying to match their specs as closely as possible. One of those specs requires a custom JSON body to allow for deletion of multiple items at the same time. Do you have any ideas for a possible workaround in the meantime? Thanks again.

**Comment by webron** [comment]
A workaround for this issue? Don't have a body for `DELETE` operations :)

A 'workaround' for deleting multiple items at the same time without sending a body? Sure, that's easy.

**Comment by J4mey** [comment]
Hey @webron , I hear you on the “don’t have a body for delete operations”. We’d probably adhere to that for our own development: however we are only testing and documenting this API and are not making the end-decisions. Would love to hear the workaround for deleting multiple items so we can make a recommendation back to our client, but in the meantime, do you know if there’s a quick way to override the automatic content-type change, or if the Swagger UI will eventually be updated to allow the Body to be sent in a delete call?

**Comment by webron** [comment]
Heh, I wasn't trying to suggest that you *should* remove the body for `DELETE` operations but it was just a way of saying this is the bug, and the workaround is to avoid it. It requires a fix, otherwise there's no other solution.
