### ISSUE TITLE
Insecure sanitize function

### ISSUE THREAD

**Issue by adon-at-work** [swagger-api/swagger-ui#1439]
Found the following code at https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/helpers/handlebars.js#L3-L7
```javascript
Handlebars.registerHelper('sanitize', function(html) {
    // Strip the script tags from the html, and return it as a Handlebars.SafeString
    html = html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
    return new Handlebars.SafeString(html);
});
```

If what an attacker would like to inject is `<script>alert(1)</script>`, yes, the sanitize function can turn it to empty. But it's easy to bypass the filter by using `<<script>alert(1)</script>script>alert(1)</script>` instead.

I'm not 100% sure whether this Handlebars helper is still in used. If so, you may like to consider using https://github.com/yahoo/html-purify

**Comment by fehguy** [comment]
Can you send a PR to implement this?  I agree it would be helpful to have a better method.
