### ISSUE TITLE
Weird oauth error

### ISSUE THREAD

**Issue by Korri** [swagger-api/swagger-ui#1440]
I lost a few hours trying to figure out why my oAuth `Authorization` header wasn't sent although it was visible in the curl command, in the end it was my fault, but still swagger ui reacted weird.

So in "security" I had:

``` json
"security": [ "email" ]
```

instead of:

``` json
"security": [ {
    "my_oauth": ["email"]
}],
```

So far, my mistake, but the weird thing is that the first solution actually showed the oauth button, allowed me to get a token from my API, AND added the `Authorization` header to the **curl** request, but never to the **"Try it out!"** request.

It works now, but maybe this is an issue that needs to be fixed.

**Comment by webron** [comment]
Hopefully, this is no longer an issue with the new UI.
