### ISSUE TITLE
Version not displayed when using 1.2 spec

### ISSUE THREAD

**Issue by mikedaly** [swagger-api/swagger-ui#1442]
The version string is not displayed in the footer when using a 1.2 spec. Presumably this is because the field name changed between the two spec versions.

Here is my swagger spec, as returned from my Jersey2-jaxrs endpoint:

```
{  
   "apiVersion":"0.21.00-SNAPSHOT",
   "swaggerVersion":"1.2",
   "apis":[  
      {  
         "path":"/something",
         "description":"Operations on something"
      }
   ]
}
```

**Comment by webron** [comment]
It's unlikely we'll resolve this issue now. 3.0 has dropped support for 1.2 specs entirely.
