### ISSUE TITLE
Unable to set two custom headers with latest swagger-ui 2.1.0 release

### ISSUE THREAD

**Issue by PriscaMoine** [swagger-api/swagger-ui#1444]
I am unable to add two customized headers with the 2.1.0 swagger-ui release, whereas it used to work with 2.1.0-M2 release.

e.g.
swaggerUi.api.clientAuthorizations.add("customHeader1", new SwaggerClient.ApiKeyAuthorization("customHeader1", "value1", "header"));

swaggerUi.api.clientAuthorizations.add("customHeader2", new SwaggerClient.ApiKeyAuthorization("customHeader2", "value2", "header"));

Only the first added header is present in the http OPTIONS request Access-Control-Allow-Headers, the second ont does not appear at all.

e.g. on OPTIONS request heaaders:
Access-Control-Allow-Headers: accept, customHeader1

Therefore my swagger gui client is incompatible with 2.1.0 due to access denied since both custom headers are required in my case. I would liike to upgarde to get advantage of evolutions and bug fixes (in particular the CURL corresponding reuqestwhich is great feature !)

Are you able to reproduce ? and confirm me this issue ?
Do you have a workaround or is it possible to fix it, if yes, when ?

Thanks you in advance for your support !

**Comment by ponelat** [comment]
You've hit a known bug :smile: the fix is in, just waiting to get merged...
https://github.com/swagger-api/swagger-js/pull/488

**Comment by timbuethe** [comment]
I stumbled upon this issue as well. I willing to downgrade to get rid of this bug, however, the release naming is really confusing. What is the latest published release? Which is the latest before this bug was introduced? And what's with all the Milestone releases anyway...?

**Comment by PriscaMoine** [comment]
Hi,

in my experience, downgrading to swagger-ui 2.1.0-M2 allows you to workaround the bug while the fix is not integrated in latest swagger-ui

regards,

**Comment by timbuethe** [comment]
Thanks, this seems to work.

That said, I'm getting the following warning from bower, but it seems to work anyway:
> bower swagger-ui#2.1.0-M2     mismatch Version declared in the json (2.1.8-M1) is different than the resolved one (2.1.0-M2)

**Comment by fehguy** [comment]
This should be addressed now, please reopen if not
