### ISSUE TITLE
Contact, termsOfService and license links in info section should open in a new tab

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-ui#1446]
Use `target="_blank"` to force those links open in a new tab

**Comment by banders** [comment]
Has there been any work on this issue?  I am also keen to see links open in new tabs.

I would actually like to see *all links* open in new tabs, including links embedded in parameter descriptions and elsewhere.  If this change would be undesirable to some users, perhaps we could add a new parameter to SwaggerUi to control how links are opened.
