### ISSUE TITLE
Swagger UI overrides accept header parameter

### ISSUE THREAD

**Issue by lakmali** [swagger-api/swagger-ui#1448]
We are using swagger 2.1.0.

We need to dynamically send different accept header values. For that we added this new parameter accept. But Swagger UI sends application/json as the accept header all the time. We tried setting "produces"  with multiple values. But for that swagger UI sends the first value as the accept header.

Is there any workaround for this? 

```yaml
 get:
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
      produces:
        - "application/xml,application/json"
      parameters:
        - name: id
          allowMultiple: false
          type: string
          required: true
          in: path
        - name: Accept
          type: string
          required: false
          in: header
      responses:
        "200": {}
```

**Comment by webron** [comment]
You can't override the `Accept` header and you have to use `produces` for it.

Your definition is malformed, and not parsed properly by the UI.
There are two issues:
1. The `produces` value needs to be an array of the values you want to support. In your case, it has a single value which is a string containing both values (it just translates to `application/xml,application/json` - it will send both).
2. Your `200` response definition is invalid as it *requires* at least a `description`. However, the current definition says there's no response value (i.e., `void`) which makes the content type irrelevant and as such, the drop-down allowing you to choose the response type will not appear. You have to give it a `schema` value to have the ability to choose a content type.

**Comment by lakmali** [comment]
Thanks for the explanation.

**Comment by Joe23** [comment]
I don't think this problem is fixed. I am able to have the drop down appears, but when click the button "Try it out!", the UI has some kind of preference to application/json, over the application/xml.
![swagger](https://cloud.githubusercontent.com/assets/3357187/23375301/acaa1158-fcdc-11e6-9057-05e2891d0321.jpg)
I tried changes the order in the @producers block and it still only accept application/json.

```
  /v1.0/something2:
    get:
      tags:
      - "v1.0"
      description: ""
      operationId: "getBoth"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "Accept"
        in: "header"
        required: false
        type: "string"
      responses:
        default:
          description: "successful operation"
```

Tested in swagger swagger-ui-2.2.8 and swagger-ui-2.2.6

**Comment by fehguy** [comment]
use this instead:

```yaml
consumes:
  - application/xml
```

Which translates to the `Accept` header.

**Comment by Joe23** [comment]
Thanks for your suggestion. I update my code but looks like same things.

I notice that if I take out the `application/json` from the `produces` and only has `application/xml`, then application/xml in the form works. but as long as `application/json` is in produces, the xml won't work.

**Comment by webron** [comment]
What does your current spec look like?

**Comment by Joe23** [comment]
Here is the full spec.
```yaml
---
swagger: "2.0"
info:
  version: "1.0.0"
  title: ""
host: "192.168.56.1:56489"
basePath: "/sso/"
tags:
- name: "v1.0"
schemes:
- "http"
paths:
  /v1.0/something2:
    get:
      tags:
      - "v1.0"
      operationId: "getBoth"
      consumes:
      - "application/xml"
      - "application/json"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "Accept"
        in: "header"
        required: false
        type: "string"
      responses:
        default:
          description: "successful operation"
```

Also, Here is the Java Class code if you are interested.

```java


import java.util.concurrent.CompletableFuture;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.container.AsyncResponse;
import javax.ws.rs.container.Suspended;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

@Path("/v1.0")
@Api(value = "/v1.0",produces = MediaType.APPLICATION_JSON+","+MediaType.APPLICATION_XML)
public class Sample {
	@GET
	@Path("something2")
	@Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
	@Consumes({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
	public void getBoth(@Suspended final AsyncResponse asyncResponse,@HeaderParam(HttpHeaders.ACCEPT) final String type) {
		CompletableFuture.runAsync(() -> {
			asyncResponse.resume("OK");
		});
	}
}
```

**Comment by webron** [comment]
Remove the `accept` header definition. You should do that from your spec, and from your code. That's simply not how you handle it in either.

**Comment by Joe23** [comment]
ehhh ... if I remove `accept`, then there is no place in the swagger ui to indicate that it can accept either json or xml, which defeat the purpose of API document.

Also, there is no way I can test it.

**Comment by webron** [comment]
That's why you have the `produces`. The reason that won't render for you is that you don't describe the schema for the response. If there's no schema, the response is empty, and then.... the media type is meaningless.

**Comment by Joe23** [comment]
Thanks @webron , it is the response does the trick. For ppl visiting this thread you can add this to the function.
```java
@ApiOperation(response = APIResponse.class, value = "sample test")
```
Then the swagger core will inspect the APIResponse.class to simulate the response structure and sample output.

**Comment by prativapokhrel** [comment]
I had the same issue and I tried to hardcode the swagger.js file which actually worked. I changed "responseContentType = application/json" to "responseContentType = value of accepts parameter". Hope it works for you as well :)

**Comment by yusufomg** [comment]
Hey, I had the same problem. changed name("Accept")  to name("accept") and it's work me :)

@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket api(){
        return  new Docket(DocumentationType.SWAGGER_2).globalOperationParameters(
                Arrays.asList(new ParameterBuilder()
                        .name("accept")
                        .description("Result Type: JSON(application/json)-XML(application/xml)")
                        .modelRef(new ModelRef("string"))
                        .parameterType("header")
                        .required(true)
                        .build()));
    }
}

**Comment by miry** [comment]
References: https://swagger.io/docs/specification/2-0/mime-types/

```
Note that consumes only affects operations with a request body, such as POST, PUT and PATCH. It is ignored for bodiless operations like GET. 
```

I think this the reason, why consumes do not modifies Accept header for ALL verbs.
