### ISSUE TITLE
gracefully handling erroneous responses when it comes to content-type

### ISSUE THREAD

**Issue by typekpb** [swagger-api/swagger-ui#1449]
follow up of the: #1431 

Having: returned `404` for the `delete` action on the resource, having `"Content-Type":"application/json"` returned from the server, but returning the plain text (in the response body), there is shown in the swagger UI:

```
Response body: no content
Response code: 0
Response headers: no response from server
```

which is wrong (seems to be caused by the json parsing errors).

**Comment by ponelat** [comment]
This is due to a bug(or missing feature) of superagent. If the content-type is json, superagent will try to parse it. Which is fine, but if an error occurs, it doesn't show the original body.
We've logged an issue with superagent.

For the workaround, you can use jquery for ajax..
```javascript
new SwaggerUI({
// ...
  useJQuery: true,
// ...
```

**Comment by tperlmutter** [comment]
Not convinced that useJQuery is a workaround here.  I tried it and I'm still having this problem.

**Comment by KrzysztofMadejski** [comment]
I have similar problem (`"Origin is not allowed by Access-Control-Allow-Origin"` being thrown). I believe problem lies in https://github.com/swagger-api/swagger-js/blob/aeb8f31299c062b64b9d9a88dfdc1af0d1f10afd/lib/http.js#L217

`res` will be always set, but `res.text` may be empty. I guess `res.text` should be tested here.

**Comment by webron** [comment]
This is an old issue that I have no easy way of testing with the new UI. As such, will close it for now, but if anyone encounters it, feel free to open a new ticket.
