### ISSUE TITLE
Enable/Disable Different Swagger-UI Options

### ISSUE THREAD

**Issue by dpatra1** [swagger-api/swagger-ui#1452]
Hi ,

I am using Springfox(swagger2) in my project to enable API documentation for my Micro services.

I was wondering how can i enable/disable different options on the Swagger-UI. Now its a dependency jar and i have nothing which i can change it on my code base (which i could do it when i was using swagger1.x version by putting the swagger ui static content in my resource folder and update the .js or html files accordingly.).

Any suggestions ?

I was thinking for making different groups for the APIs in my controller based upon different url patterns in the swagger-ui like:
- /v1/fis/{fiId}/businessCustomer - API urls ends with "businessCustomer" should display under "BusinessCustomer" as a hyperlink
- /v1/fis/{fiId}/companies - API urls ends with "companies" should display under "Company" as a hyperlink

Also i wanted to display the APIs in a order like GET, DELTE, PUT and POST. Something like that.

Any suggestions?

Thanks,
Deba

**Comment by webron** [comment]
As long as you use the webjar, you'll have little to no customization abilities.

You can still do it the same way as you did before and load the static files in your application and modify those based on your needs.

**Comment by dpatra1** [comment]
@webron - Thanks
