### ISSUE TITLE
default value for parameter fails if  ' (single quote) character is present

### ISSUE THREAD

**Issue by youngjohnsilver** [swagger-api/swagger-ui#1453]
It seems if I specify a default value for a parameter such as:

"default" : "SomeValue='some_single_quoted_string'"

what ends up being displayed is only:
SomeValue=
and the 'some_single_quoted_string' is missing from the parameter field. Since the ' (single quote) character is not a special character and cannot be escaped (\') I'm not aware of any way to include single quotes in the default value of a parameter.

**Comment by fehguy** [comment]
escaped the single quote with `&apos;`.
