### ISSUE TITLE
Basic Authentication support in Swagger UI

### ISSUE THREAD

**Issue by javi830810** [swagger-api/swagger-ui#1454]
Could you guys add support for base64 encoding user/password on the UI, like some kind of fancy UI with couple of boxes (something like Postman). 

I know it can be done outside of the box, by using the PasswordAuthorization function. But I think this is a nice thing to have....

thanks

**Comment by fehguy** [comment]
It's trivial to do this, if you would like to contribute the UI, we can wire the implementation.

**Comment by webron** [comment]
This is done.
