### ISSUE TITLE
Swagger-ui is too slow

### ISSUE THREAD

**Issue by nikhiljindal** [swagger-api/swagger-ui#1455]
We have hosted swagger-ui for Kubernetes at http://kubernetes.io/third_party/swagger-ui/

It takes too much time to load.
Any suggestions on how can we reduce the load time?

**Comment by webron** [comment]
Can you try upgrading to the latest master first?

**Comment by nikhiljindal** [comment]
Sure! Will try that.

**Comment by nikhiljindal** [comment]
Have updated the code to use latest swagger-ui code, but now http://kubernetes.io/third_party/swagger-ui/#/ takes even longer to load.

The network tab shows that the page takes more than 16s to load!! Validator seems to be the long tail which is taking more than 2s. Is there a way to disable the validator?

![swagger-ui](https://cloud.githubusercontent.com/assets/10199099/8841275/92a6a032-30a0-11e5-81ba-b5076ae475fe.png)

**Comment by nikhiljindal** [comment]
ok looks like setting validatorUrl to null, should disable it. Will try that.

**Comment by nikhiljindal** [comment]
Its down to 10s now, after disabling validation.
But its still 10s!!

<img width="1427" alt="screen shot 2015-07-23 at 1 27 20 am" src="https://cloud.githubusercontent.com/assets/10199099/8846244/39c6700c-30da-11e5-88cf-bf648c110063.png">

**Comment by webron** [comment]
Sorry about that, we definitely need to investigate it further. I'd also urge you to move to Swagger 2.0 but I know your options are limited right now.

**Comment by nikhiljindal** [comment]
Yes. We use go-restful to generate our swagger-spec which doesnt support 2.0 yet.

**Comment by fehguy** [comment]
Hi @nikhiljindal I'm reproducing this.  Will update the issue shortly after investigation, there should be no reason why it's so slow.

**Comment by fehguy** [comment]
Hi @nikhiljindal please give this a shot:

https://github.com/swagger-api/swagger-ui/pull/1500

and report back how it does for you.

**Comment by nikhiljindal** [comment]
I had to revert to the old version of swagger-ui since the latest was taking too much memory: https://github.com/GoogleCloudPlatform/kubernetes/issues/11852

**Comment by fehguy** [comment]
@nikhiljindal Are you still interested in fixes for the speed, or are you moving away per your reference above?

**Comment by replaysMike** [comment]
I sure am. I'm really suffering here. I have only 10 api endpoints groups shown with a total of 50 api enpoints, but it takes 4 minutes for the UI endpoints to display. What on earth is it doing, and what can I do to make it usable?

**Comment by replaysMike** [comment]
I'm using version 2.1.3 (within latest Swashbuckle for .Net).

**Comment by fehguy** [comment]
Can you please share your spec?  Privately is fine

**Comment by PeterBrende** [comment]
I am having severe performance issues when adding relationships between objects.  We use Nhibernate, and have many parent-child relationships between the entities used in our Web API OData services.  I tried removing all relationships (Swagger UI is very quick).  One by one, I started adding back relationships.  The performance degraded very quickly until it got to the poi
[SwaggerSpec.txt](https://github.com/swagger-api/swagger-ui/files/456998/SwaggerSpec.txt)
nt where it just processes for several minutes before dying (I believe because of memory).  I have attached the spec.
[SwaggerSpec.txt](https://github.com/swagger-api/swagger-ui/files/456976/SwaggerSpec.txt)

**Comment by fehguy** [comment]
Sure enough, this is causing some issues.  Will get back to you on the root cause...

**Comment by PeterBrende** [comment]
@fehguy, FYI, this spec is being generated by Swashbuckle, so I don't really have any control over it.

**Comment by fehguy** [comment]
understood, there is a bug in the library that should be addressed.  I can't speak to any issues in the spec, but this should be fixable.

**Comment by wauk** [comment]
https://github.com/domaindrivendev/Swashbuckle/issues/891

**Comment by webron** [comment]
We've just released version 3.0 of swagger-ui. While it does _not_ support 1.2, it does have some major performance improvements. If you're on 2.0 by now, please test.
