### ISSUE TITLE
Swagger UI with swagger-express

### ISSUE THREAD

**Issue by jabr9983** [swagger-api/swagger-ui#1457]
Does the newest version of swagger ui support response class with a model? I had it working on swagger ui version in swagger express, but then I updated in order to use response messages, and now the modeling method doesn't work. I either need to be able to have an object in the response messages or display the response class. I figure there has to be a way to do this I just don't know what it is.

**Comment by webron** [comment]
When you say 'swagger express' you mean...?

**Comment by jabr9983** [comment]
https://github.com/fliptoo/swagger-express I am using this swagger tool.

**Comment by webron** [comment]
That looks like it produces a very old version of Swagger definitions (i.e., version 1.0). There are some issues with the conversion we do from 1.0 to 2.0 (works well for 1.2, not so much for older versions).
It may be time to consider looking for alternatives to that library.

**Comment by jabr9983** [comment]
Okay do you happen to know of a good way to do inline documentation with swagger in such a way?

**Comment by webron** [comment]
Not really a node user here so I can't recommend one library over another. We do have our own [swagger-node](https://github.com/swagger-api/swagger-node) project, but you can also check out anything under the node.js header [here](http://swagger.io/open-source-integrations/) (make sure to search under Swagger 2.0 support).

**Comment by jabr9983** [comment]
Okay I will take a look

**Comment by jabr9983** [comment]
I appreciate all your help do you happen to have any contacts that use node? I am looking and not seeing a whole lot so I thought I would check.

**Comment by webron** [comment]
We have a large node community. You can either give a shout out on twitter or try your luck at the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).

**Comment by jabr9983** [comment]
Okay thanks I gave it a shot really appreciate all your help.
