### ISSUE TITLE
Allow fragment edition for REUSE usage

### ISSUE THREAD

**Issue by danielm64** [swagger-api/swagger-ui#1458]
The [REUSE philosophy] (https://github.com/swagger-api/swagger-spec/blob/master/guidelines/REUSE.md) relies on YAML fragments for:
* Operations
* Parameters
* Responses
* Models 

Editing these fragments is not supported by swagger-editor.
Currently, we write full swagger 2.0 specs, and, when complete and valid, comment all what should not be in the fragment... 
would appreciate this support to suppress the unnecessary work...

**Comment by webron** [comment]
Wrong project?

**Comment by danielm64** [comment]
... sorry...
can you move to swagger-editor ? Or I re-open there ?

**Comment by webron** [comment]
Better reopen there. Unfortunately, github doesn't have a proper functionality to move issues between projects.
