### ISSUE TITLE
Can't read from server. It may not have the appropriate access-control-origin settings. ?

### ISSUE THREAD

**Issue by interpegasus** [swagger-api/swagger-ui#146]
Hi,

The server returns the following message: 
"Can't read from server. It may not have the appropriate access-control-origin settings."

The API URL is: http://swagger-espn.mobovivo.com/api-docs.json

Could you please help to fix the issue?

Thanks in advance
![Screen Shot 2013-02-11 at 10 54 09 PM](https://f.cloud.github.com/assets/934795/147698/1d480a36-74ca-11e2-85bf-22ec009353cd.png)

**SPEC FILE**

```
{
"basePath": "http://espn-server.herokuapp.com/api",
"swaggerVersion": "0.1a",
"apiVersion": "1.0",
"apis": [
{
    "path": "/info.json",
    "format": "json",
    "description": "Get API info and current match",
    "operations": [
        {
            "httpMethod": "GET",
            "summary": "Get API info and current match",
            "nickname": "info",
            "tags": [
                "production"
            ],
            "deprecated": false
        }
    ]
},
{
    "path": "/info/{id}.json",
    "format": "json",
    "description": "Get API info and current event",
    "operations": [
        {
            "httpMethod": "GET",
            "summary": "Show Event Info.",
            "nickname": "showByIdOne",
            "tags": [
                "production"
            ],
            "deprecated": false,
            "parameters": [
                {
                    "name": "id",
                    "description": "id = 1",
                    "dataType": "integer",
                    "allowMultiple": false,
                    "required": true,
                    "paramType": "path"
                }
            ],
            "errorResponses": [
                {
                    "reason": "Not found",
                    "code": 404
                },
                {
                    "reason": "Invalid ID",
                    "code": 400
                }
            ]
        }
    ]
}
]
}
```

**Comment by SuperMarioX** [comment]
Hi, I could solve this issue on Tomcat server, but it remains a problem on websphere application server profile as a server. Do you have any way to fix this?

Many thx :-)

**Comment by webron** [comment]
Not sure why websphere would be any different. Enabling CORS is normally done at the application level, though tomcat has its own filter you may have used. Just enable it on websphere and you should be done.

**Comment by SuperMarioX** [comment]
http://stackoverflow.com/questions/24277953/how-to-define-cors-in-websphere-application-server-liberty-profile-v8-5
That helps.

**Comment by senid231** [comment]
Why we need to accept CORS for fetching json file?
you don't need it for AJAX GET

**Comment by fehguy** [comment]
You don't need CORS for a GET.  Swagger-js (the underlying library for the UI) does not differentiate in the request process and therefore sends a preflight request.

**Comment by icwatk** [comment]
where do you put the bit of code in to allow CORS? 

Thanks!

**Comment by webron** [comment]
@icwatk - that depends on how you serve your swagger.json and API. no single answer to it.

**Comment by kkirsche** [comment]
I would recommend in the error message including a link to a resource or two to help users who hit this issue more quickly solve the issue they are seeing.

**Comment by webron** [comment]
@kkirsche - while I agree that when it comes to user experience it would be better, there's also this - https://github.com/swagger-api/swagger-ui#or-how-to-deal-with-cant-read-from-server-it-may-not-have-the-appropriate-access-control-origin-settings. It's right there in the README of this project.

**Comment by kkirsche** [comment]
Which doesn't help to individuals running this for a company. The readme only is helpful to the deployer

**Comment by shaaasiiingh** [comment]
Hi,

The server returns the following message: when trying to fetch swagger data in html format.
"Can't read from server. It may not have the appropriate access-control-origin settings."
project structure-swaggerdemo/man/resources/webapp/index.html

The API URL is: http://localhost:8080/config/config/swagger.json
Although, i'm able to fetch when given swagger.json or swagger.yaml


index.html-
 $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "http://localhost:8080/config/config/swagger.json";
      }
Swaggerconfig.java
     BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.0");
        beanConfig.setSchemes(new String[]{"http"});
        beanConfig.setHost("localhost:8080");
        beanConfig.setBasePath("/config");
        beanConfig.setResourcePackage("yourpackage");
        beanConfig.setTitle(" Swagger UI");
        beanConfig.setDescription("swagger ui example.");
        beanConfig.setScan(true);
        beanConfig.setPrettyPrint(true);

web.xml
  <servlet>
          <servlet-name>jersey</servlet-name>
          <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
          <init-param>
              <param-name>jersey.config.server.provider.packages</param-name>
              <param-value>
                  io.swagger.jaxrs.listing,
                  com.oracle.gbu.odi.controller
              </param-value>
          </init-param>
      </servlet>

      <servlet>
          <servlet-name>SwaggerConfigurationServlet</servlet-name>
          <display-name>SwaggerConfigurationServlet</display-name>
          <servlet-class>package</servlet-class>
          <load-on-startup>2</load-on-startup>
      </servlet>

      <servlet-mapping>
          <servlet-name>jersey</servlet-name>
          <url-pattern>/config/*</url-pattern>
      </servlet-mapping>

Could you please help to fix the issue?

Thanks in advance

**Comment by Geralt-x** [comment]
it's very easy.What you should do is change "localhost" to "127.0.0.1"!Then you will success.

**Comment by AssiaHalloul** [comment]
hey i'm working with swagger hub but when i click on try it out for an endpoint i got this error ,could you help me please

access-control-allow-credentials: true  access-control-allow-headers: X-Requested-With,Content-Type,Accept,Origin  access-control-allow-methods: *  access-control-allow-origin: *  cache-control: no-cache  content-length: 0  content-type: application/octet-stream  date: Wed,28 Apr 2021 17:25:24 GMT  etag: W/"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk"  expires: -1  server: Jetty(9.4.29.v20200521)  status: 404 Not Found  x-firefox-spdy: h2  x-powered-by: Express,Phusion Passenger(R) 6.0.8

**Comment by quynguyenhcm** [comment]
Hi, I can access to swagger doc from localhost. However, when host the app within Docker container and do a port forward from localhost to the container, I got the same message` "Can't read from server. It may not have the appropriate access-control-origin settings."`

Can someone suggest solution please?

Thanks
Quy
