### ISSUE TITLE
Referenced arrays aren't displayed correctly in a model

### ISSUE THREAD

**Issue by bandtank** [swagger-api/swagger-ui#1460]
How do I get the Images key to not be displayed? I want to use the Images model in many places, but the displayed format is misleading.

![screen shot 2015-07-08 at 5 06 01 pm](https://cloud.githubusercontent.com/assets/1170415/8584434/a5db2a5a-2593-11e5-9cde-c0d20e8022a6.png)

The actual structure is as follows:

`image : { thumbnail: "...", large: "...", etc. }`

But the image above is causing external users to ask me why the object isn't returned like this:

`image : { Image: {thumbnail: "...", large: "...", etc. }}`

How do you reuse a model without displaying it like what's shown in my image? This is how my JSON file looks:

![screen shot 2015-07-08 at 5 10 08 pm](https://cloud.githubusercontent.com/assets/1170415/8584487/3a9a35a0-2594-11e5-9eb7-17703e5ab3c3.png)

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-editor#541
