### ISSUE TITLE
Swagger UI, Sring MVC, Missing Controller Names and Description

### ISSUE THREAD

**Issue by samillm** [swagger-api/swagger-ui#1464]
Hi,

I'm trying to implement swagger and swagger ui on a spring mvc application.
I am using swagger-springmvc version 1.0.2 and swagger-spring-mvc-ui version 0.4.
Based on the instructions for implementing swagger ui and spring mvc [here](https://github.com/springfox/springfox/blob/v1.0.2/README.md)

I have tried both options 1 & 2
Option 1

Note: Only use this option if you don't need to customize any of the swagger-ui static content, otherwise use option 2.
Use the web-jar which packages all of the swagger-ui static content.
Requires that your app is using the servlet 3 specification.
For non-spring boot applications some extra spring configuration (ResourceHandler's) is required. See: https://github.com/adrianbk/swagger-springmvc-demo/tree/master/swagger-ui
dependencies {
  ...
  compile "org.ajar:swagger-spring-mvc-ui:0.4"
}

![swaggerv1](https://cloud.githubusercontent.com/assets/13263272/8608778/0817dc44-2653-11e5-8071-6c639f5b749b.png)

Option 2

Manually copy all of the static content swagger-ui's dist directory (https://github.com/wordnik/swagger-ui/tree/master/dist)
Provide the necessary view resolvers and resource handlers to serve the static content.
Consult the spring documentation on serving static resources.
The following is one way to serve static content from /src/main/webapp

<mvc:resources mapping="*.html" location="/"/>

<mvc:default-servlet-handler/>

![swaggerv2](https://cloud.githubusercontent.com/assets/13263272/8608774/026762c4-2653-11e5-9d23-98f36e6078d2.png)

When I tried to implement option 1 everything worked correctly.
However, I need to use option 2 as I intend to modify the index.html page.
When trying option 2 the controller description is missing.

Here are my API-Docs:
{"apiVersion":"1.0","apis":[{"description":"Just a test","path":"/default/test","position":0}],"authorizations":{},"info":{"description":"Practice API","title":"Practice API"},"swaggerVersion":"1.2"}

I've looked at [a similar question](https://github.com/swagger-api/swagger-ui/issues/1167) but I can't figure out what I'm doing wrong.

Please help me understand what's wrong and how I can fix it.

Thanks!

**Comment by webron** [comment]
As @dilipkrish has mentioned in the cross-post, you're using an old version of both swagger-springmvc (now springfox) and swagger-ui. Upgrade to the latest and see if the problem persists.
