### ISSUE TITLE
operations display the same response model and schemal

### ISSUE THREAD

**Issue by szsuyuji** [swagger-api/swagger-ui#1465]
when operations have the same  response class Name,but response classes are in different packages.
ui always display one of the response class model in every operation.
i track the json response result,different operations return the different json object.

**Comment by webron** [comment]
Can you share your Swagger definition?

**Comment by fehguy** [comment]
What you're describing is not supported.  There is a single namespace for Response models, and if you want them to be different, you should choose different names.  We're intentionally avoiding a "namespace" feature in the spec to avoid it getting too ugly.
