### ISSUE TITLE
Multiple Error Responses with the same Status Code

### ISSUE THREAD

**Issue by toshe** [swagger-api/swagger-ui#1466]
Is there a way to list several Error Responses with the same HTTP Code? 

For example an API can throw a `403 Forbidden` with `InvalidParametersError` and also a `403 Forbidden` with `ForbiddenError`

Swagger doc version: 1.2

```json
"responseMessages": [
  {"code":401,"message":"UnauthorizedError","responseModel":"error"},    
  {"code":403,"message":"InvalidParametersError","responseModel":"error"},    
  {"code":403,"message":"ForbiddenError","responseModel":"error"},  
  {"code":404,"message":"NoObjectError","responseModel":"error"}    
]

```

In this case there are two different errors with a 403 Status but only one of them is shown in Swagger UI:

![errors](https://cloud.githubusercontent.com/assets/1636022/8633694/ad593020-27d6-11e5-8b88-1115a84398d3.PNG)

Swagger-UI version: `d75505fb73` (latest commit in master)

Is this on purpose (only one code per reason allowed) or is this a bug?

**Comment by webron** [comment]
@toshe - this is indeed by design and not a bug. If you need to represent multiple possible errors, you'd need to do that within the message/model of a single error instance.

**Comment by toshe** [comment]
Hm, okay I just went ahead and listed each error with a comma.
