### ISSUE TITLE
Prevent slashes from being stripped from resource labels

### ISSUE THREAD

**Issue by trdesilva** [swagger-api/swagger-ui#1468]
The API that I'm working on has resources on paths that are multiple levels removed from the base path (e.g. http://host/basepath/foo/bar/baz). Swagger strips the slashes from the paths to the resources when displaying them on the resource list, so the resource at foo/bar/baz is labelled foobarbaz. While it does correctly show the paths of operations when the list is expanded, is there a way to get the slashes to show up in the resource labels? I tried replacing the

    return pathString.replace('/', '');

in SwaggerSpecConverter.prototype.extractTag() with

    return pathString;

but it didn't seem to do anything. I'm using Swagger v1.5.0 with RESTEasy.

**Comment by webron** [comment]
The terminology you use makes it a bit difficult to understand what you mean. Can you share a swagger.json/yaml that exhibits the behavior?

**Comment by trdesilva** [comment]
{"swagger":"2.0","info":{"version":"4.0.0","title":"Datalink REST API"},"host":"localhost:8402","basePath":"/api/v1/resource","tags":[{"name":"agent{id}connector"},{"name":"agent{id}engine"}],"paths":{"/agent/{id}/connector":{"get":{"tags":["agent{id}connector"],"summary":"Retrieves the list of connectors","description":"","operationId":"getConnectorList","produces":["application/json"],"parameters":[{"name":"id","in":"path","required":true,"type":"string"}],"responses":{"200":{"description":"successful operation","schema":{"type":"array","items":{"$ref":"#/definitions/ConnectorReference"}}}}},"post":{"tags":["agent{id}connector"],"summary":"Creates a new connector","description":"","operationId":"createConnectorUntyped","consumes":["application/json"],"produces":["application/json"],"parameters":[{"name":"id","in":"path","required":true,"type":"string"},{"in":"body","name":"body","required":false,"schema":{"type":"object"}}],"responses":{"default":{"description":"successful operation"}}}},"/agent/{id}/connector/{connectorId}":{"get":{"tags":["agent{id}connector"],"summary":"Retrieves details about a connector","description":"","operationId":"getConnector","produces":["application/json"],"parameters":[{"name":"id","in":"path","required":true,"type":"string"},{"name":"connectorId","in":"path","required":true,"type":"string"}],"responses":{"200":{"description":"successful operation","schema":{"type":"object"}}}},"put":{"tags":["agent{id}connector"],"summary":"Updates a connector","description":"","operationId":"putConnector","consumes":["application/json"],"produces":["application/json"],"parameters":[{"name":"id","in":"path","required":true,"type":"string"},{"name":"connectorId","in":"path","required":true,"type":"string"},{"in":"body","name":"body","required":false,"schema":{"type":"object"}}],"responses":{"default":{"description":"successful operation"}}},"delete":{"tags":["agent{id}connector"],"summary":"Deletes a connector","description":"","operationId":"deleteConnector","parameters":[{"name":"id","in":"path","required":true,"type":"string"},{"name":"connectorId","in":"path","required":true,"type":"string"}],"responses":{"default":{"description":"successful operation"}}}},"/agent/{id}/connector/{connectorId}/execute":{"post":{"tags":["agent{id}connector"],"summary":"Runs a connector","description":"","operationId":"executeConnector","consumes":["application/json"],"produces":["application/json"],"parameters":[{"name":"id","in":"path","required":true,"type":"string"},{"name":"connectorId","in":"path","required":true,"type":"string"},{"in":"body","name":"body","required":false,"schema":{"$ref":"#/definitions/ExecutionInstruction"}}],"responses":{"default":{"description":"successful operation"}}}},"/agent/{id}/connector/{connectorId}/status":{"get":{"tags":["agent{id}connector"],"summary":"Checks the status of a connector","description":"","operationId":"getConnectorStatus","produces":["application/json"],"parameters":[{"name":"id","in":"path","required":true,"type":"string"},{"name":"connectorId","in":"path","required":true,"type":"string"}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#/definitions/ConnectorStatus"}}}}},"/agent/{id}/engine":{"get":{"tags":["agent{id}engine"],"summary":"Retrieves details about this engine","description":"","operationId":"getEngine","produces":["application/json"],"parameters":[{"name":"id","in":"path","required":true,"type":"string"}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#/definitions/Engine"}}}}}},"definitions":{"ConnectorStatus":{"type":"object","properties":{"lastModified":{"type":"string","format":"date-time"},"status":{"type":"string"},"statusMessage":{"type":"string"}}},"ExecutionInstruction":{"type":"object","properties":{"task":{"type":"string"}}},"ConnectorReference":{"type":"object","properties":{"connectorId":{"type":"string"},"url":{"type":"string"}}},"Engine":{"type":"object","properties":{"version":{"type":"string"},"hostname":{"type":"string"},"uptime":{"type":"string"},"installPath":{"type":"string"},"environment":{"type":"object","additionalProperties":{"type":"string"}},"jvmProperties":{"type":"object","additionalProperties":{"type":"string"}}}}}}

I'd like the tags, "agent{id}connector" and "agent{id}engine", to match their corresponding paths, "agent/{id}/connector" and "agent/{id}/engine". Looking at the JSON, it seems that it may have been better to open this issue in swagger-core as the slashes are being stripped before the UI is generated.

**Comment by webron** [comment]
This is not an issue with swagger-ui, this is an issue with swagger-core. The tags are generated that way by it (this is intentional by the way). If you feel it should be changed, you should open an issue there.
