### ISSUE TITLE
try it out using oauth2 with swagger spec 1.2 no longer working with swagger ui 2.1.0

### ISSUE THREAD

**Issue by conorroche** [swagger-api/swagger-ui#1470]
I have a project using swagger-ui-2.1.8-M1 and have just tested an upgrade to swagger ui 2.1.0 and there are several issues that mean the "try it out" functionality does not work for me.
It looks like the building of the oauth objects from the swager 1.2 spec json has changed so swagger-oauth.json no longer sees the same object structure it used to and does not work.

specifically:

1) in swagger-oauth.js line 12 

var auths = window.swaggerUi.api.authSchemes || window.swaggerUi.api.securityDefinitions;

the object authSchemes no longer has a scopes property in the oauth 2 item:

![screen shot 2015-07-15 at 16 34 11](https://cloud.githubusercontent.com/assets/4437171/8703394/bbdc9c5e-2b14-11e5-9411-0ea9b64a22e1.png)

This means that the popup has no scope checkboxes when it should.

in line 110:
2) dets.authorizationUrl is expected to be a string but is now an object with the url as a property, this means the url is broken unless i do a workaround like this:

![screen shot 2015-07-15 at 16 29 17](https://cloud.githubusercontent.com/assets/4437171/8703383/ac01f41e-2b14-11e5-9810-92135b404e11.png)

My service.json and other json files are available on https://api.car.ma/apidoc/ref/service.json (note the UI on that domain is still the older one)

**Comment by webron** [comment]
It's unlikely we'll resolve this. 3.0 is out now and no longer supports 1.2.
