### ISSUE TITLE
API Usability and Base paths?

### ISSUE THREAD

**Issue by chachasikes** [swagger-api/swagger-ui#1471]
Hello,

From what I can tell looking through the default Swagger display, the base url appears in the footer. It would be really helpful for API documentation purposes to show the base url near the general introduction, before the different API methods are listed.

I'm tracking this issue down in a quest to solve a problem that I often have with documented API's, which is the simple problem that the active and functional API path is usually not listed prominently. This is especially a concern for people who are encountering a new API for the first time — people don't always know that an API platform is using API documentation, they might not even be developers, just people wanting to know what kind of data is in a particular API that is in use for their work. 

A recent example was the new [Open FEC API] (https://api.open.fec.gov/developers) (which is a publicly iterated API that's in beta right now, and I'm using them as an example because I know that any smart decisions they make will probably influence others!)

From what I can tell, they are using Swagger UI, somewhat modified, and possibly even using this for several other API's, because they publish a bunch of government APIs. When you arrive on a Swagger page, it usually has a route to the documentation page that a developer picks (I know because I've been the one to pick the route before). 

The path might not be listed unless the developer/documentor specifically makes the effort to type the base path in the display & introduction (which is scary because someone might move your domain someday in the far enough future that you might forget, or someone else might not notice your path listing) 

So then, you have to know where to look, and usually a developer is trying to just get basic documentation set up at this point, and it's very likely that this important step will be forgotten, or even that the domain they are using is a development domain and the information will definitely be wrong and be one more thing to keep track of. 

Also, as a developer, it's convenient to have the URL accessible in a way that is easy to cut and paste... for emailing, tweeting, putting into Slack/Hipchat.... etc. Manually editing the URL to include the current version endpoint is tedious, and if you deal with a zillion API's and try to not remember, it's extra work.

I've encountered this problem at least 5 times on various API's, so I'm tracking down the source of this confusion! :) 

The [NY Times developer API page](http://developer.nytimes.com/docs/read/article_search_api_v2) has a nice example of the base url prominently displayed, and it makes it easy to test the URL to ensure that it works, and that you then have everything you need to dive deeper into an API and start understanding how to interface with it.

Anyhow, I want to help solve this issue because surely I'm not the only one.

Thank you!

**Comment by LindsayYoung** [comment]
Hello I thought I would ring in- I am one of the developers on the OpenFEC project. Woking with swagger has been great since we are constantly building endpoints and with swagger, our documentaion can keep up. Initially, we needed to fork swagger to get definitions for the tags. We have abstract concepts that needed more explanation. Once we did that, we added our own styling. 

I thought I would link to our fork in case it is useful. https://github.com/18F/swagger-ui

**Comment by webron** [comment]
@chachasikes - Thank you for opening the ticket with the elaborate explanation. I was going to refer you from the google group here to the 'Swagger UI People' (Hi!) but you beat me to it.

It's good that you bring this issue up as while you may have encountered it several times, sometimes users can't put the finger on what's missing and end up not providing this sort of feedback. 

Time-wise, it's a bit late on my end, so I won't go into the history of the project explaining the reasons of why or how the project is at its current state. Eventually, it's not too important as we're constantly looking forward to improve it. I will say one thing though - Swagger UI at its core is intended to be modified and adjusted by the developers using it (however convenient/inconvenient it is). Pushing things around should be relatively easy and we've seen implementations that entirely change the look and feel of the pages.

As for the usability points you raise, I find they make sense and we need to consider how to approach them. Unfortunately, there are other issues regarding adding the additional information or moving it around, as that may end up overloading the UI with details that may not be relevant to everyone. We need to consider what would be a good approach to solve it, and possibly make some aspects of it configurable/optional.

@LindsayYoung - thanks for sharing the fork. It's always a pleasure seeing the effort and creativity the users put into making the UI better suit their needs. If you find that some specific features would have been better handled directly by the project, feel free to open feature requests as needed.

**Comment by fehguy** [comment]
I'm going to close this out.  I do agree that there are ways to improve the styling and information display inside the UI but it's nearly impossible to make everything configurable and totally impossible to make everyone agree on how information should be displayed.  My suggestion @chachasikes is to fork the UI as @LindsayYoung has (and did an excellent job I will add!).

We definitely appreciate the input and thought process you've put into writing up your ticket.  It's all going to help shape future iterations of the UI (which will have the same constraints as I mentioned above).
