### ISSUE TITLE
Doesn't support loading YAML from URL.

### ISSUE THREAD

**Issue by NicholasRBowers** [swagger-api/swagger-ui#1472]
When a request and subsequent response are created (line 29,710), we assume that the response is coming is formatted in JSON, even though we're now supporting YAML.

`err = new Error('Parser is unable to parse the response');` is triggered when creating the Response object.

If the URL parameter points to a YAML file, it's contents are likely to be transferred with the header `application/json`, because YAML MIME types are not very common.

```
request.parse = {
  'application/x-www-form-urlencoded': parseString,
  'application/json': JSON.parse
};
```

Here, we only allow for processing of two MIME types, so we're kind of stuck.  I would add cases for YAML MIME types and use the already implemented `js-yaml` plugin to process these contents.

This is important because currently our `url` parameter can only consume JSON, while the `spec` contents can ONLY be sent in JSON.  Without this change, I'm unsure of how SwaggerUI can support loading and parsing YAML files?

**Comment by NicholasRBowers** [comment]
This is actually an issue with [SwaggerJS](https://github.com/swagger-api/swagger-js).  My apologies.

**Comment by fehguy** [comment]
This is supported now.
