### ISSUE TITLE
Array parameter and POST can't send value correctly

### ISSUE THREAD

**Issue by neuecc** [swagger-api/swagger-ui#1474]
I'm using Swagger UI v2.1.0

If parameter is array and GET, request is 'foo=1&foo=2&foo=3', it's good.
but when POST, request is 'foo=1,2,3', it's bad.

For example if parameter is

```
a,b,c
d,e,f
```

query will be `foo=a%2Cb%2Cc%2Cd%2Ce%2Cf`, can't parse correctly in server.

Would you change the behavior of POST same as GET?

**Comment by webron** [comment]
Can you share your swagger.json/yaml?

**Comment by neuecc** [comment]
Thank you for response.
Here are my tested swagger.json.

```
{  
   "basePath":"\/api",
   "host":"localhost:12345",
   "info":{  
      "description":"",
      "title":"foo",
      "version":"1.0"
   },
   "paths":{  
      "\/My\/EchoArrayGet":{  
         "get":{  
            "description":"",
            "parameters":[  
               {  
                  "collectionFormat":"multi",
                  "description":"Int32[]",
                  "in":"query",
                  "items":{  
                     "type":"integer"
                  },
                  "name":"foo",
                  "required":true,
                  "type":"array"
               }
            ],
            "summary":"",
            "tags":[  
               "My"
            ]
         }
      },
      "\/My\/EchoArrayPost":{  
         "post":{  
            "description":"",
            "parameters":[  
               {  
                  "collectionFormat":"multi",
                  "description":"Int32[]",
                  "in":"formData",
                  "items":{  
                     "type":"integer"
                  },
                  "name":"foo",
                  "required":true,
                  "type":"array"
               }
            ],
            "summary":"",
            "tags":[  
               "My"
            ]
         }
      }
   },
   "schemes":[  
      "http"
   ],
   "swagger":"2.0"
}
```

**Comment by webron** [comment]
Out of curiosity, which library generates it?

**Comment by neuecc** [comment]
It's generated by my handmade framework. https://github.com/neuecc/LightNode

**Comment by webron** [comment]
@neuecc - that's nice! always great seeing more integrations. The reason I ask is because there are some things I'd change about the output, but we can discuss that separately.

In your example, the POST uses formData parameter and not query. Changing it to query works fine. There is indeed a bug with formData params - https://github.com/swagger-api/swagger-js/issues/529.

**Comment by neuecc** [comment]
Thank you!
I understand the problem and watch swagger-js#529 issue.
