### ISSUE TITLE
The details of the succesfull API call (response: HTTP 200) is not shown in the Response Messages table

### ISSUE THREAD

**Issue by grunci** [swagger-api/swagger-ui#1476]
I have a swagger.json file which contains a swagger 2.0 conform content.

The swagger.json file contains the following 3 responses.  The ’Response Messages’ table in the generated html does not show a row with the information for the success case, see attached image.

```
        "responses" : {
          "200" : {
            "description" : "Details about the response in case of success.",
            "schema" : {
              "$ref" : "#/definitions/ResponseBody"
            }
          },
          "400" : {
            "description" : "There is an error in the specified request body.",
            "schema" : {
              "$ref" : "#/definitions/ResponseBody"
            }
          },
          "401" : {
            "description" : "The user is not authorized to perform the action.",
            "schema" : {
              "$ref" : "#/definitions/ResponseBody"
            }
          }
        }

```
![missingresponse200](https://cloud.githubusercontent.com/assets/10311849/8776747/b18060be-2ef3-11e5-9b66-191c37429a94.PNG)

The ’Response Class (Status 200)’ section is generated on the webpage, with the correct Model Schema, but no description field.

**Comment by webron** [comment]
The current version does not list the successful response at the table but rather above the operation itself.

**Comment by grunci** [comment]
The problem here, that the description part of the successful response remains invisible. That part can contain very important information.

**Comment by webron** [comment]
Fair enough.

**Comment by grunci** [comment]
Thanks :)

**Comment by adamaltman** [comment]
There can also be more than one successful type of response:  200, 201, 202...  I also find it confusing that one appears above, in a different format than the others that appear below.

**Comment by thjaeckle** [comment]
This Issue is tagged for "v2.1.1" but not fixed for that version, or is it?
Still getting the same behavior with 2.1.1 release.

**Comment by viktorminko** [comment]
This problem still remains in 2.1.3

**Comment by ezequielnaftali** [comment]
Hi, we are having the same problem with 2.1.4, is there any plan to fix it?

Thanks.
