### ISSUE TITLE
File params showing Data Type as "undefined" in the UI

### ISSUE THREAD

**Issue by glen-84** [swagger-api/swagger-ui#1478]
See: http://petstore.swagger.io/#!/pet/uploadFile

![file-param](https://cloud.githubusercontent.com/assets/261509/8783910/287d9ad0-2f1f-11e5-9db1-4d737f987cfe.png)

**Comment by kulkarniankita** [comment]
Is anyone working on this?

**Comment by webron** [comment]
@kulkarniankita - just that - `file` :)

**Comment by kulkarniankita** [comment]
What is the entry point to fixing this? @webron

**Comment by glen-84** [comment]
@fehguy I think this was fixed?

**Comment by fehguy** [comment]
Yes, please reopen if you see any issues.

**Comment by donhaggis** [comment]
This seems to be introduced in 2.7.0 again.

**Comment by webron** [comment]
There is no 2.7.0.
