### ISSUE TITLE
Maps appearing in model as 'undefined'

### ISSUE THREAD

**Issue by j-m-baker** [swagger-api/swagger-ui#1482]
Hello,

I've used Wordnik to annotate some Java, ie.

  @ApiModelProperty(value = "Field name and whether to sort ascending (true) or descending (false)")
  public void setSort(Map<String, Boolean> sortOrder) {
    this.sortOrder= sortOrder;
  }

And Wordnik is producing the following JSON extract for SwaggerUI:

"sort":{"$ref":"Map[string,boolean]"}

Which looks correct. But the UI displays:

sort (undefined, optional),

And I can't get any Map to result in the UI presenting a key/value map for the user to complete. I don't to replace the Map with a custom object - is there a way to get this working with SwaggerUI? I've tried 2.1 and the current code on the master branch.

Thanks

**Comment by webron** [comment]
Which java project and version exactly did you use for it?

**Comment by j-m-baker** [comment]
It's something I wrote myself and it is wordnik from the maven repo:

      <groupId>com.wordnik</groupId>
      <artifactId>swagger-jaxrs_2.10</artifactId>
      <version>1.3.12</version>

**Comment by webron** [comment]
swagger-core 1.3.X doesn't support maps at all. You'd have to upgrade to 1.5.X if you want it.

**Comment by j-m-baker** [comment]
The Maven tree suggests it's using swagger-core 2.1 ?


[INFO] +- com.wordnik:swagger-jaxrs_2.10:jar:1.3.12:compile
[INFO] |  +- org.scala-lang:scala-library:jar:2.10.4:compile
[INFO] |  +- com.wordnik:swagger-core_2.10:jar:1.3.12:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-scala_2.10:jar:2.4.1:compile
[INFO] |  |  |  +- org.scala-lang:scala-reflect:jar:2.10.4:compile
[INFO] |  |  |  \- com.thoughtworks.paranamer:paranamer:jar:2.6:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-jsonSchema:jar:2.4.1:compile
[INFO] |  |  +- com.wordnik:swagger-annotations:jar:1.3.12:compile

**Comment by j-m-baker** [comment]
Sorry you mean using this dependency:

      <groupId>com.wordnik</groupId>
      <artifactId>swagger-jaxrs</artifactId>
      <version>1.5.3-M1</version>

**Comment by webron** [comment]
```xml
     <groupId>io.swagger</groupId>
      <artifactId>swagger-jaxrs</artifactId>
      <version>1.5.3</version>
```

**Comment by j-m-baker** [comment]
That's helpful! So for anyone else interested, it appears the packaging of com.wordnik switched to io.swagger at version 1.5.3 (The 1.5.3-Mx releases were under com.wordnik).

**Comment by webron** [comment]
@j-m-baker - yeah, unfortunately we used somewhat confusing version conventions (won't happen in the future). As for the packaging change, we've made the announcement on several platforms, but it makes sense that it is missed, so no worries about it.

Let us know if it helps resolving your issue.

**Comment by j-m-baker** [comment]
It works perfectly. Let me share some more further information. 

There are a lot of examples of how to get com.wordnik working on the 'net, but they no longer work. The Spring configuration is now as follows:

```xml
  <!-- Swagger resources -->
  <bean id="swagger.apilisting" class="io.swagger.jaxrs.listing.ApiListingResource" />
  <bean id="swagger.serializers" class="io.swagger.jaxrs.listing.SwaggerSerializers" />
  <!-- 
    This scans the classes for resources. The basePath value property is set by SwaggerConfigServlet.  
  -->
  <bean id="swagger.config" class="io.swagger.jaxrs.config.BeanConfig">
    <property name="resourcePackage" value="package.of.annotated.interfaces" />
    <property name="version" value="1.0.0"/>
    <property name="title" value="My Service"/>
    <property name="contact" value="abc@def.com"/>
    <property name="scan" value="true"/>
    <property name="basePath" value="/rest"/>
  </bean>  

  <!-- Define the REST services -->
  <jaxrs:server address="/rest">
    <jaxrs:inInterceptors>
        <ref bean="validationInInterceptor" />
    </jaxrs:inInterceptors>         
    <jaxrs:outInterceptors>
        <ref bean="validationOutInterceptor" />
    </jaxrs:outInterceptors>    
    <jaxrs:serviceBeans>
      <bean class="package.to.implementations.of.service" />
      <!-- This provides the Swagger resource listing, ie /swagger.json -->
      <ref bean="swagger.apilisting" />
    </jaxrs:serviceBeans>
    <jaxrs:extensionMappings>
      <entry key="json" value="application/json"/>
      <entry key="xml" value="application/xml"/>
    </jaxrs:extensionMappings>
    <jaxrs:providers>        
      <bean class="com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider" />
      <bean class="com.fasterxml.jackson.jaxrs.xml.JacksonXMLProvider" />
      <ref bean="swagger.serializers" />
      <ref bean="exceptionMapper"/>
    </jaxrs:providers>   
    <jaxrs:features>
      <cxf:logging />
    </jaxrs:features>    
  </jaxrs:server>
```

But this isn't quite enough, because if you deploy an application in a war file under context path /myapp, the Swagger JS does not get the correct path to the API listing service. In this scenario, the BeanConfig:

```xml
    <property name="basePath" value="/rest"/>
```

should be:

```xml
    <property name="basePath" value="/myapp/rest"/>
```

However this is painful, because if the war file changes, so does the Spring configuration. I think it would be helpful to try and resolve this within BeanConfig. My solution is to create a ServletContextListener and update the BeanConfig at runtime:

```java
import io.swagger.jaxrs.config.BeanConfig;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

/**
 * This listener only exists to dynamically set the Swagger Configuration bean
 * basePath with the application context path.
 */
public class SwaggerRuntimeConfig implements ServletContextListener {
  protected Logger logger= LoggerFactory.getLogger(getClass());
  
  @Autowired
  private BeanConfig beanConfig;
  
  @Override
  public void contextInitialized(ServletContextEvent sce) {
    WebApplicationContext ctx = WebApplicationContextUtils.getRequiredWebApplicationContext(sce.getServletContext());
    ctx.getAutowireCapableBeanFactory().autowireBean(this);
    // Add context path to the value set in the XML file
    beanConfig.setBasePath(sce.getServletContext().getContextPath()+beanConfig.getBasePath());
    logger.info("Configuring Swagger with basePath "+beanConfig.getBasePath());
  }

  @Override
  public void contextDestroyed(ServletContextEvent sce) {
  }
 
}
```

**Comment by webron** [comment]
So is the issue resolved? ;)

**Comment by j-m-baker** [comment]
Yes it is resolved. I thought the above may help :) The only item to add is where I've stated:

```xml
    <property name="basePath" value="/rest"/>
```

The CXFServlet servlet-mapping (from the web.xml file) needs to be included, ie.

```xml
    <property name="basePath" value="/api/rest"/>
```
assuming /api/* is mapped to the CXFServlet.

**Comment by Swag33r** [comment]
Hi , I am using all latest version of swagger core and annotations but still map is undefined 
Here the dependencies i am using in gradle build -----

swagger-annotations-1.5.3-M1.jar
swagger-annotations-1.5.9.jar
swagger-compat-spec-parser-1.0.13.jar
swagger-core-1.5.3-M1.jar
swagger-core-1.5.9.jar
swagger-jaxrs-1.5.9.jar
swagger-models-1.0.2.jar
swagger-models-1.5.3-M1.jar
swagger-models-1.5.9.jar
swagger-parser-1.0.13.jar
swagger-springmvc-1.0.2.jar
swagger2markup-0.9.2.jar


What could be the possible reason??

**Comment by fehguy** [comment]
Your dependencies are really crazy, all under the io.swagger package should be 1.5.9 or at least the same version. Please open in swagger-core

**Comment by Swag33r** [comment]
Hi fehguy,
I modified the dependencies 

swagger-annotations-1.5.9.jar
swagger-core-1.5.9.jar
swagger-jaxrs-1.5.9.jar
swagger-models-1.5.9.jar

these are latest one still got undefined for map ???
any clue??

**Comment by fehguy** [comment]
OK well now please share your operation with annotations so we can look.

**Comment by Swag33r** [comment]
These are normal operations like 
@Apimodel ,   @ApiModelProperty(value = " name")
 @Api, @ApiResponse etc nothing much

**Comment by fehguy** [comment]
Share the whole operation or model so nobody has to guess

**Comment by Swag33r** [comment]
Hi ,
its a large project in somewhere we are using mangofactory swagger and io.swagger ? is this a problem?
in Main class SwaggerConfig we are using mangofactory , is there any way to replace mangofactory

**Comment by webron** [comment]
yeah, it doesn't make sense. swagger-springmvc produced swagger 1.2, and io.swagger produces 2.0. If your project is spring-mvc, you should look into Springfox for integration. It definitely seems you're in some sort of a dependency hell.

**Comment by Swag33r** [comment]
Hi Ron,

This is separate question apart from that thread.
I am using Swagger with Spring MVC.

I have a DTO which i am using like this
    @ApiOperation(value = " ", httpMethod = "POST", response =
POSTResponseDTO.class and Response .

same DTO i am using for Requesting the payload.

But in swagger payload Request some filed i want to hide so i use hide =
true but i want them in respone .

To solve this problem i m using diff DTO ,

is there any other solution for this?

How we can write custom annotation in swagger.
