### ISSUE TITLE
Why is 200 status code being added to every endpoint ?

### ISSUE THREAD

**Issue by pkrefta** [swagger-api/swagger-ui#1483]
Hello,

I've an endpoint that doesn't return 200 status. It's documented and returned in JSON (https://www.dropbox.com/s/mx4bsrv22et9pk6/Screenshot%202015-07-23%2000.54.10.png?dl=0). Despite that SwaggerUI shows 200 status code as one the possibilites (https://www.dropbox.com/s/ysdj32dfanham3s/Screenshot%202015-07-23%2000.56.15.png?dl=0) Is this expected behaviour or have I encountered an issue ?

**Comment by webron** [comment]
This is explained in #1266.
