### ISSUE TITLE
Api Resource id's not escaping special characters in shebang function

### ISSUE THREAD

**Issue by nickg415** [swagger-api/swagger-ui#1485]
When working with swagger-ui, I ran into an issue with api resource expanding when refreshing page after clicking into the api operation. The following error was printed to chrome's console (replaced actual api with example one):

```
jquery-1.8.0.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #%7Bversion%7D%2Fpet
```

After digging around for awhile, I found that this was caused by the fact that my api endpoint had curly brackets in it (The project using swagger uses spring which puts path variables into the uri). An example would be:

```
{version}/pet
```

It looks like this is caused by the jquery selectors being performed in window.Docs.shebang, which do not escape the resource before using the selector:

```
//under case 1
$("#"+dom_id).slideto({highlight: false});

//under case 2
$("#"+dom_id).slideto({highlight: false});

// Expand operation
var li_dom_id = fragments.join('_');
var li_content_dom_id = li_dom_id + "_content";


Docs.expandOperation($('#'+li_content_dom_id));
$('#'+li_dom_id).slideto({highlight: false});
```

As an aside, I also noticed that under case 2 in the above snippet, one of the selectors does nothing since dom_id in the scope of case 2 is undefined.

I was able to fix this issue by updating the SwaggerUi.Views.MainView.addResource method to replace invalid characters:

```
resource.id = resource.id.replace(/[[\]{}()*+?,\\/^$|#\s]/g, '_');
```

instead of:

```
resource.id = resource.id.replace(/\s/g, '_');
```

However, looking back at it as I'm writing this up, maybe you could make use of Docs.escapeResourceName() in shebang function instead?

**Comment by fehguy** [comment]
Confirmed that this is working in #1808.  The fix was probably applied earlier but this ticket not updated.

**Comment by rmohr** [comment]
@fehguy, seems like I still see this on 2.2.6 and 2.2.8:

```
jquery-1.8.0.min.js:2 Uncaught Error: Syntax error, unrecognized expression: %2Fkubevirt.io%2Fv1alpha1%2Fnamespaces_func1_0_1_2_content(…)
oe.error @ jquery-1.8.0.min.js:2
o @ jquery-1.8.0.min.js:2
oe.compile @ jquery-1.8.0.min.js:2
pe @ jquery-1.8.0.min.js:2
pe @ jquery-1.8.0.min.js:2
oe @ jquery-1.8.0.min.js:2
find @ jquery-1.8.0.min.js:2
init @ jquery-1.8.0.min.js:1
K @ jquery-1.8.0.min.js:1
shebang @ doc.js:116
```

My entries looks like this:

```
/apis/kubevirt.io/v1alpha1/namespaces/{namespace}/vms/{name}
```

**Comment by fehguy** [comment]
Please try master

**Comment by rmohr** [comment]
@fehguy Can confirm that it works on master.
