### ISSUE TITLE
Finished Loading Resource Information. Rendering Swagger UI

### ISSUE THREAD

**Issue by Ashubgs90** [swagger-api/swagger-ui#1488]
I was trying to add upload file button into UI. For that I changed swagger-ui.js. I got file upload button there but next time it was trying to open, it shows this error. I replaced changed file but still it shows error. Please tell me what I need to do, I am very new to swagger.

**Comment by rcruzper** [comment]
it happens to me too, my api has more than 50 tags and swaggerui renders just a few of them.

**Comment by Ashubgs90** [comment]
@rcruzper Replace swagger-ui.js with latest version of swagger UI.

**Comment by fehguy** [comment]
Please share a spec if you're having trouble with this.  I have never seen tags getting dropped.

**Comment by rcruzper** [comment]
I'm using swagger-ui 2.1.2 and it still happens.
In fact, v2.1.2 is showing less tags than v2.1.8-M1

**Comment by rcruzper** [comment]
It was my fault. I used swagger editor to convert my json to yaml and I found some errors.

**Comment by webron** [comment]
Closing this now. Please reopen if needed.
