### ISSUE TITLE
Crash when retrieving gzip data

### ISSUE THREAD

**Issue by tgrosinger** [swagger-api/swagger-ui#1490]
I have a method that is defined like this:

``` json
"/supportpack/{filename}": {
    "get": {
        "summary": "Download an existing support pack by filename",
        "parameters": [
            {
                "name": "filename",
                "in": "path",
                "description": "Name of support pack to download",
                "required": true,
                "type": "string",
                "format": "string"
            }
        ],
        "produces": [
            "application/x-gzip"
        ],
        "tags": [
            "Support Pack"
        ],
        "responses": {
            "401": {
                "description": "API key provided is invalid for this method",
                "schema": {
                    "$ref": "#/definitions/error"
                }
            },
            "404": {
                "description": "Requested resource could not be found",
                "schema": {
                    "$ref": "#/definitions/error"
                }
            }
        },
        "deprecated": false
    }
}
```

The resulting data is a tar.gz file, how ever even with the `produces` set the browser window completely crashes when the response returns.

Is there a different mime type I can use to cause the browser to download this file rather than trying to handle it and display the result?

**Comment by webron** [comment]
Which version of the UI do you use?

Can you trying adding a successful response to the list of responses with type file? That seems to be missing from your definition.

**Comment by tgrosinger** [comment]
@webron, sorry about the long delay.
I have added a 200 response case with just a description. Since the result is gzip data a schema didn't seem to make sense.

When making the request the browser appears to freeze for a minute, even the "Kill this tab" window pops up. After a few more seconds it comes back to life and the binary data is displayed in the **Response Body** section.

Currently running v2.1.1

Would it be possible to change this so "application/x-gzip" or "application/octet-stream" results start a file download?

**Comment by webron** [comment]
Actually, you can set the schema type to `file` which would make sense for your use case. There may still be an issue here though, of course.

**Comment by tgrosinger** [comment]
I have updated my schema definition to look like this:

```json
    "/supportpacks/{filename}": {
            "get": {
                "summary": "Download an existing support pack by filename.",
                "parameters": [
                    {
                        "name": "filename",
                        "in": "path",
                        "description": "Name of the support pack to download.",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/x-gzip"
                ],
                "operationId": "get",
                "tags": [
                    "Support Pack"
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "type": "file",
                            "description": "Gzipped file"
                        }
                    },
                    "401": {
                        "description": "API key provided is invalid for this method",
                        "schema": {
                            "$ref": "#/definitions/error"
                        }
                    },
                    "404": {
                        "description": "Requested resource could not be found",
                        "schema": {
                            "$ref": "#/definitions/error"
                        }
                    }
                },
                "deprecated": false
            }
        }
```

When I do then get a 200 response it pauses for almost a minute before showing me the binary data in the **Response Body** section. Did I add the `file` schema type correctly?

**Comment by webron** [comment]
Yup, structure is right.

**Comment by tgrosinger** [comment]
Any further suggestions to solve this problem?

**Comment by fehguy** [comment]
@tgrosinger you're looking to get a file download dialog for this use case?  Is that right?

**Comment by tgrosinger** [comment]
Yes, exactly.

**Comment by dgreenbean** [comment]
A change is needed to swagger-ui to handle binary attachments properly.  The example I have been working with is PDF files, but I imagine similar issues would happen with other types like gzip.  This is a hack I've put together to highlight the issue:
https://github.com/swagger-api/swagger-ui/compare/master...dgreenbean:feature/blob?expand=1

**Comment by fehguy** [comment]
Binary attachments are supported now.  Please grab the latest and open a new issue if you still have troubles.
