### ISSUE TITLE
Multiple XHR requests for the same api-docs

### ISSUE THREAD

**Issue by lelininkas** [swagger-api/swagger-ui#1492]
Hi,

For some reason swaggerui on load makes multiple requests to the same /api/api-docs end point.

![multiple_apidocs_requests](https://cloud.githubusercontent.com/assets/2209805/8875094/32de59bc-321f-11e5-8f70-b817a7c75ed2.jpg)

I have only one group (default). The URL is correct and it returns correct JSON. SwaggerUI renders correctly, but takes too long to load because of these multiple requests.

**Comment by webron** [comment]
Which version of the UI do you use?

Which version of swagger do you use in your definition?

**Comment by lelininkas** [comment]
I'm using latest UI version from this git and 2.1.2 springfox-swagger2.

**Comment by lelininkas** [comment]
Here is an example of api-docs response that would cause swaggerUI to do multiple requests (x7 for every path) to api-docs endpoint.
```javascript
{  
   "swagger":"2.0",
   "info":{  
      "description":"API for internal use only",
      "version":"1.0",
      "title":"Test API",
      "termsOfService":"http://test.com",
      "contact":{  
         "name":"info@rest.com"
      },
      "license":{  
         "name":"Apache 2.0 License",
         "url":"http://www.apache.org/licenses/LICENSE-2.0.html"
      }
   },
   "host":"localhost",
   "basePath":"/",
   "tags":[  
      {  
         "name":"string-service",
         "description":"String Service"
      }
   ],
   "paths":{  
      "/services/rest/string":{  
         "get":{  
            "tags":[  
               "string-service"
            ],
            "summary":"getStringList",
            "operationId":"getStringListUsingGET",
            "consumes":[  
               "application/json"
            ],
            "produces":[  
               "*/*"
            ],
            "parameters":[  
               {  
                  "in":"body",
                  "name":"filter",
                  "description":"filter",
                  "required":false,
                  "schema":{  
                     "$ref":"#/definitions/CustomFilter"
                  }
               }
            ],
            "responses":{  
               "200":{  
                  "description":"OK",
                  "schema":{  
                     "type":"string"
                  }
               },
               "401":{  
                  "description":"Unauthorized"
               },
               "403":{  
                  "description":"Forbidden"
               },
               "404":{  
                  "description":"Not Found"
               }
            }
         }
      }
   }
}
```

**Comment by lelininkas** [comment]
Resolver.prototype.resolve is doing the requests in relation to
```javascript
"schema":{  
                     "$ref":"#/definitions/CustomFilter"
                  }
```
What does it expect and why is it failing?

**Comment by webron** [comment]
Is that the full api-docs response you're getting or did you cut it off?

**Comment by lelininkas** [comment]
This is full response. I've created test app. that consist of sole service with path "/services/rest/string". 
```java
    @ApiOperation(value = "Get all strings")
    @RequestMapping(method = RequestMethod.GET)
    public String getStringList(@ApiParam CustomFilter filter)
            throws ResourceNotFoundException {
        return "";
    }
    public class CustomFilter {
        private String query;

        public String getQuery() {
            return query;
        }

        public void setQuery(String query) {
            this.query = query;
        }
    }
```

**Comment by webron** [comment]
That's a bit odd as the definition of CustomFilter (`#/definitions/CustomFilter`) is nowhere to be found there.

**Comment by rkeplin** [comment]
I am seeing the same behavior.  I am using reusable parameters, and they worked fine in the `v2.1.1-M2` tag.  However, when trying to upgrade to the `v2.1.1` tag, I see this bug.

It is easy to reproduce by checking out the `v2.1.1` tag and supplying the [Reusable Parameters Fixture](https://raw.githubusercontent.com/swagger-api/swagger-spec/master/fixtures/v2.0/json/resources/reusableParameters.json) as a spec.

I am on Chrome Version 44.0.2403.125 m (64-bit).

**Comment by yidongnan** [comment]
have the same behavior.  use ```springgox-swagger2 2.1.2```  and  ```swagger-ui 2.1.1```

**Comment by jacobweber** [comment]
I'm seeing the same thing for my API. I don't have a short example to include yet. Using latest Chrome/Mac.

**Comment by lelininkas** [comment]
After some investigation I find that this behavior is normal - as there is no "definitions" object the UI script tries to follow the $ref pointer and retries after failing for predefined number of times. The only request here would maybe be the ability to set the retry count in the parameters.
As this is a problem/feature with Springfox implementation I've created an issue on [their github](https://github.com/springfox/springfox/issues/882).

**Comment by rkeplin** [comment]
I've created a separate issue regarding the multiple requests being made using reusable parameters: #1511.

**Comment by jacobweber** [comment]
I figured out why I was seeing this behavior ... I had "definitions" that contained $refs to other definitions, but a couple of them were missing. The validator didn't pick this up.

**Comment by lukec** [comment]
I was seeing this behaviour when using references to `#/parameters/something` and `#/responses/something`, when those references were valid.  

I have worked around this by expanding those references out manually as part of producing our swagger.json. This lets me refactor common responses & parameters across api calls.

Unfortunately I don't have an example swagger.json to share, but it was easy to reproduce.

**Comment by johndunlap** [comment]
I'm seeing this in my spec as well, having finished spending a couple of very painful days migrating it from 1.2 to 2.0. It's very difficult to track down because the console doesn't tell me which $ref is failing to resolve(which it absolutely should) and it's very difficult to track down manually because the spec file is over 10,000 lines long.

**Comment by lukec** [comment]
I deleted everything out of my spec file until i only had a single parameter or response reference.  I could then easily see it make the extra HTTP request.  Having either `#/parameters/ref` or `#/responses/ref` would trigger the extra HTTP requests, even though they were defined in the same file.

**Comment by johndunlap** [comment]
I'm seeing this problem and I'm not using #/parameters/ref or #/responses/ref anywhere in my spec, though I am using #/definitions/ref

**Comment by johndunlap** [comment]
This bug is really crippling my efforts, at the moment. Normally, this is little more than an annoyance because all of these duplicate requests are served from the browsers cache. However, in my case, I'm filtering the swagger specification on the server side, to remove references to endpoints which the user doesn't have permission to see so that, depending on who you're logged in as, you'll see different endpoints available in the documentation. Because of that, I'm sending a no-cache header and the load time of my docs goes from a few seconds to several minutes.

**Comment by lukec** [comment]
@johndunlap if you're filtering the swagger spec server side, you could use the same workaround that i did, which is to "pre-process" the references yourself - replace the references with the actual reference.  This would eliminate the references from your swagger.json.  I have done that as a workaround to this issue, and it was a couple minutes of coding.

**Comment by johndunlap** [comment]
I have managed to fix my problem but I had to write my own code for doing it because swagger doesn't tell me which references it can't find in the console(which it should absolutely do). I used the following bash script for finding them:
```
#!/bin/bash

SPEC=$1

cat $SPEC |grep \$ref | awk '{print $3}' | sort | uniq | awk 'BEGIN{FS="/"}{print $3}' | awk 'BEGIN{FS="\""}{print "\"" $1 "\""}' > definitions.txt

while read p; do
  grep -q $p $SPEC

  if [ $? != 0 ]; then
    echo "Count not find: $p"
  fi
done <definitions.txt
```

In my case, I had things like this:
```
Count not find: "Array(debt_id)"
Count not find: "date"
Count not find: "datetime"
Count not find: "dateTime"
Count not find: "float"
Count not find: "numeric"
```

Which were artifacts left over from the swagger converter that I used to get my spec *mostly* converted from 1.2 to 2.0.

**Comment by johndunlap** [comment]
@lelininkas I would like to see swagger print an error in the console when it can't follow a reference. That would have saved me the trouble of writing my own script to figure out which refs were broken in a single file spec.

**Comment by hhp21** [comment]
I'm coming across this issue too and my spec file is massive - if there are any issues swagger ui should definitely print an error to say what the issue is. @lelininkas can you please reopen this issue for this request?

**Comment by webron** [comment]
This should not be an issue anymore.
