### ISSUE TITLE
Dockerfile updates

### ISSUE THREAD

**Issue by apobbati** [swagger-api/swagger-ui#1494]
Is there a reason for the current verbosity of the Dockerfile?

It can be shrunk down to the following file:

```
FROM    node:onbuild
MAINTAINER dnephin@gmail.com

ENV     DEBIAN_FRONTEND noninteractive

EXPOSE 8080
```

In `package.json`, we have to add a key/value under `scripts` for `start` like below:

``` js
...
"scripts": {
    "build": "gulp",
    "serve": "gulp serve",
    "prejshint": "gulp",
    "jshint": "jshint .",
    "pretest": "npm run jshint",
    "test": "mocha",
    "start": "./node_modules/gulp/bin/gulp.js serve"
  }
...
```

The build commands stay the same.
What do you think?

**Comment by webron** [comment]
Closing as an old ticket, that might not be relevant with the new UI's dockerfile. That said, if you find ways to improve it, feel free to submit PRs, we love those.
