### ISSUE TITLE
Handle externally referenced schema

### ISSUE THREAD

**Issue by KrzysztofMadejski** [swagger-api/swagger-ui#1498]
ie. giving 

```
"Dataobjects": {
          "type": "array",
          "items": {
            "title": "Dataobject-title",
            "$ref": "https://api-v3.mojepanstwo.pl/schemas/dane/dataobject.json"
          }
        }.
```

would show 
![mpapi-bug1](https://cloud.githubusercontent.com/assets/849975/8938485/349c6148-355f-11e5-9970-881a7905351f.png)
but with a nice title.

It doesn't work in https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.0 (`"swagger-client": "2.1.2"`) while it was working in https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.0-M2 (`"swagger-client": "2.1.0-M2"`)

I'm getting `swagger-ui.js:2950 Uncaught TypeError: Cannot read property 'definition' of undefined` which I've already filed here https://github.com/swagger-api/swagger-js/issues/540

**Comment by webron** [comment]
Regardless of the issue, you should know that you can't add `title` alongside the `$ref`. It would be ignored.

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please test and reopen if needed.
