### ISSUE TITLE
Wrong validation for mime-type in Example Objects

### ISSUE THREAD

**Issue by saul-mtz** [swagger-api/swagger-ui#1499]
If you have a mime type with dots in the [Example Object](http://swagger.io/specification/#exampleObject) you got an error in the swagger-ui

That is problem for [JSON API](http://jsonapi.org/) schemas because you need to accept/dispatch the mime type **application/vnd.api+json**

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
