### ISSUE TITLE
Display Request Headers

### ISSUE THREAD

**Issue by tgrosinger** [swagger-api/swagger-ui#1501]
I am hearing from users of my API that it would be helpful if the request headers were displayed below the Request URL. For example, it is unclear to them right now what header they should use to set the API key. Something like this maybe:
### Request URL

```
https://my.cool.api
```
### Request Headers

```
X-Api-Key: abc123
Content-Type: application/json
```
### Response Body

...

**Comment by tgrosinger** [comment]
Actually, could this be a duplicate of #693? I haven't had a chance to try out the latest release.

**Comment by webron** [comment]
Try it out, but I'm not sure all the headers you request would be displayed.

**Comment by webron** [comment]
We have no plans implementing this at the moment, but if anyone wants to submit a PR for it, we'll be happy to review.
