### ISSUE TITLE
403 Error trying to access the JSON even though CORS is enabled

### ISSUE THREAD

**Issue by Syzygy24** [swagger-api/swagger-ui#1504]
I am opening the UI directly from swagger-ui-master folder, and hosting the json at localhost:8080/swagger.json.

I think I have correctly enabled CORS, my curl output is as follows:

```
$ curl -I "http://localhost:8080/swagger.json"
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS, DELETE
Access-Control-Max-Age: 3600
Access-Control-Allow-Headers: Origin, Content-Type, X-Requested-With, accept
Accept-Ranges: bytes
ETag: W/"29944-1438292710000"
Last-Modified: Thu, 30 Jul 2015 21:45:10 GMT
Content-Type: application/json
Content-Length: 29944
Date: Fri, 31 Jul 2015 18:08:24 GMT
```

<img width="1381" alt="screen shot 2015-07-31 at 11 44 40 am" src="https://cloud.githubusercontent.com/assets/6743279/9014796/830178de-3779-11e5-9649-14e44f7468d4.png">

I'm a bit lost, but right now the only way to make it work is to move the entire swagger-ui-master folder into the project. Am I missing something or is that the only way around this?

**Comment by webron** [comment]
This is not a CORS issue. You're getting 403. The request is not authorized, that's a problem with whatever is serving your swagger.json.

**Comment by Syzygy24** [comment]
I'm using tomcat 7.0.55, but I'm pretty unfamiliar with it. Are there settings that might cause it to refuse that get request?

**Comment by webron** [comment]
The authorization is probably turned on. Can you access your own API? Do you need any credentials for it?

**Comment by anmalaver** [comment]
Hey guys, 
I'm having the same problem, since we're using google authentication to access our API. Is there a way to solve this given this situation?

Thanks!

**Comment by fehguy** [comment]
As @webron mentioned, you should try accessing http://localhost:8080/swagger.json in your browser, preferably in incognito mode.  If you get a login dialog, you'll have to configure Swagger to pass credentials on load, which is documented in the swagger-ui project site.

**Comment by webron** [comment]
Closing for lack of feedback.

**Comment by ciaran036** [comment]
Was a solution found for this issue?

**Comment by arjuntippu** [comment]
Nope
