### ISSUE TITLE
Path params are being requested encoded instead of replaced with values.

### ISSUE THREAD

**Issue by ddumont** [swagger-api/swagger-ui#1506]
This seems to have regressed since at least 2.0.22 (random version in the past that worked for me) and 2.1.0 (random version in the past which did **not** work for me.

I've tried the latest as well, same error.

I'm using 
```
      <dependency>
        <groupId>com.wordnik</groupId>
        <artifactId>swagger-jersey2-jaxrs_2.10</artifactId>
        <version>1.3.12</version>
      </dependency>
      <dependency>
        <groupId>com.wordnik</groupId>
        <artifactId>swagger-jaxrs_2.10</artifactId>
        <version>1.3.12</version>
      </dependency>
      <dependency>
        <groupId>com.wordnik</groupId>
        <artifactId>swagger-core_2.10</artifactId>
        <version>1.3.12</version>
      </dependency>
```
To generate the api...  but I'm unclear on how these versions map in your support mapping table.
ie: what version of the deps above should I use for 2.0 sec compat? How do those packages map to spec versions?

**Comment by webron** [comment]
swagger-core 1.3 procudes 1.2 definitions. If you want to produce 2.0 definitions you'd have to use the 1.5.X branch.

As for the issue mentioned at the title, it is unclear what the actual issue is, but would be impossible to test without an actual Swagger definition to check.

**Comment by ddumont** [comment]
I think ill stick with 2.0.24 for now, it seems to be working.  I didn't realize that 1.3 produces spec 1.2...  heh.

I guess an upgrade would fix it.   I'll close this, thank you for the info!
