### ISSUE TITLE
Swagger-UI requests the swagger spec over plain HTTP even with an HTTPS url defined

### ISSUE THREAD

**Issue by emanuil-tolev** [swagger-api/swagger-ui#1507]
I'm building the `url` param passed to the SwaggerUI constructor dynamically:

``` javascript
var url = current_scheme + '//' + current_domain + "/api/v1/swagger.json";
console.log(url);
window.swaggerUi = new SwaggerUi({
url: url,
...
```

console.log-ing that results in https://mysite.org/api/v1/swagger.json

Yet the request is always made to http://mysite.org/api/v1/swagger.json over plain HTTP. This breaks on production for me since the whole site is served over blanket HTTPS. Anything I can do to convince swagger-ui to actually request the swagger spec from the URL passed in :)?

(This may actually be a swagger-js issue but I'm really not familiar enough with this set of projects yet to be able to tell that on my own.)

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if needed.
