### ISSUE TITLE
Swagger UI does not always show a helpful message.

### ISSUE THREAD

**Issue by BertVerhees** [swagger-api/swagger-ui#1508]
t will be very helpful if error messages say what the error is. 

I got this error-message: "Can't read from server. It may not have the appropriate access-control-origin settings.", two days I looked, experimenting with CORS-settings, etc. I thought it wasn't that, because it worked before, but the error-message was very unambiguous pointing in that direction.

Finally I found the error. I had edited the swagger.json file with vi. I forgot to remove two comma's at the end of a line. I found it by doing a diff with the swagger on another my test machine.
It would have helped me a lot if Swagger had presented a good error-message. Just a hint towards syntax would have been enough.

Maybe the swagger framework could check the swagger-file for syntax, before trying to load it and I don't know what the possibilities are, but it would be great if only a syntax error would be detected, but of course, line-number etc would even be better.

Thanks
Bert Verhees

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if needed.
