### ISSUE TITLE
Multiple XHR requests when using reusable parameters

### ISSUE THREAD

**Issue by rkeplin** [swagger-api/swagger-ui#1511]
I am using reusable parameters, and they worked well in the `v2.1.1-M2` tag.  However, when trying to upgrade to the `v2.1.1` tag, I see many XHR requests being made.  I assume it has something to do with the `$ref` in the parameters.

It is easy to reproduce by checking out the `v2.1.1` tag and supplying the [Reusable Parameters Fixture](https://raw.githubusercontent.com/swagger-api/swagger-spec/master/fixtures/v2.0/json/resources/reusableParameters.json) as a spec.

I am on Chrome Version 44.0.2403.125 m (64-bit).

**Comment by jacobweber** [comment]
I'm seeing multiple requests, and I don't have reusable parameters (but I do have a lot of $refs).

**Comment by rkeplin** [comment]
This has since been fixed, updating to the latest version of Swagger UI has solved the issue.
