### ISSUE TITLE
Escape HTML in curl query

### ISSUE THREAD

**Issue by mgttlinger** [swagger-api/swagger-ui#1514]
If there is HTML code in a string in a parameter example of a request it is not escaped properly in the curl query. For example
    
    {
      "description": "<b>Test</b>"
    }

is rendered as
`{`
  `\"decription\": \"`**`Test`**`\"`
`}`

**Comment by LuissRicardo** [comment]
I'm having a similar issue, with XML.

I've tried with double backslash (\\) before the special symbols, unsuccessfully.

```json
{
"param1": 234,
"param2": "string", 
"xml": "\\<element name\\=\\"Simple\\" color\\=\\"blue\\" />"
}
```

**Comment by fehguy** [comment]
tested in https://github.com/swagger-api/swagger-js/commit/c8c1cfc737111e8dc3752a91058a39ae9d01a7d8

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/efb77652274e99893b11848f02d9dc37d07344aa
