### ISSUE TITLE
OAuth logout doesn't work

### ISSUE THREAD

**Issue by jacobweber** [swagger-api/swagger-ui#1516]
The "Off" button doesn't seem to clear the OAuth token, or prevent the Authorization header from being sent.

On the Swagger [example site](http://petstore.swagger.io/#!/pet/findPetsByStatus), I went to findPetsByStatus, and clicked "On" to authenticate with OAuth. When I made a request to the API, it sent the Authorization header, as expected.

Then I clicked "Off" to log out. When I made another request to the API, it still sent the Authorization header.

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if needed.
