### ISSUE TITLE
Editor generated YAML is invalid but JSON is valid

### ISSUE THREAD

**Issue by zenexius** [swagger-api/swagger-ui#1518]
OK so I generated YAML and JSON using the online editor at http://editor.swagger.io/ with no errors.
But when I use these files with swagger-ui deployed on my server , YAML file validation fails while JSON  file loads without any problem.
A live example if you would like to check
json that is valid
http://54.169.44.104/swagger-ui/?url=/chirashi/fr-chirashi-api-spec.json
yaml that is invalid
http://54.169.44.104/swagger-ui/?url=/chirashi/fr-chirashi-api-spec.yaml
any hint?

**Comment by webron** [comment]
This issue was moved to swagger-api/validator-badge#43
