### ISSUE TITLE
apiKey and basic security not supported

### ISSUE THREAD

**Issue by warhammerkid** [swagger-api/swagger-ui#1523]
I have configured security for one of my operations using the `apiKey` type in the header, but the button for configuring this never shows up. Looking at [MainView.js](https://github.com/swagger-api/swagger-ui/blob/v2.1.1/src/main/javascript/view/MainView.js#L80-L88), it seems that the problem is that an element with the `auth_main_container` class doesn't exist, so the button isn't added. Even when I go back to aefd35237cc9d1867cd2dd342b3d9e68aef29e3e, where the code seems to have been added for this, I can't find any references to `auth_main_container`.

**Comment by huksley** [comment]
I am experiencing the same issue.

**Comment by fehguy** [comment]
Please try out https://github.com/swagger-api/swagger-ui/pull/2014
