### ISSUE TITLE
'Cannot read property 'msie' of undefined' message from jquery.ba-bbq.min.js

### ISSUE THREAD

**Issue by ivanstefanov** [swagger-api/swagger-ui#1527]
I updated JQuery to latest version in order to use Bootstrap (because it needed at least version 1.9.1)

Then an error messages started to appear from  jquery.ba-bbq. The error was:  

"Uncaught TypeError: Cannot read property 'msie' of undefined"

Tried to update it with newer version, but it wasn't updated since 2010 (according https://github.com/cowboy/jquery-bbq/)

**Comment by northborn** [comment]
I'm getting the same error. Apparently Swagger UI is dependent on a bunch of 3rd party libraries, some of which are dependent on old versions of jQuery. So it appears like your only option, thanks to Swagger, is to load multiple versions of jQuery. Swagger is NOT in fact "dependency free" as their docs would have you believe.

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if needed.
