### ISSUE TITLE
basicAuth 

### ISSUE THREAD

**Issue by jbolila** [swagger-api/swagger-ui#1531]
the auth.type is basic on Swagger spec 2.0, instead of 'basicAuth', right?

```js
if (auth.type === 'basicAuth' && $('#basic_auth_button').length === 0) {
```

on view/MainView.js

and the file images/password.jpeg referred on templates/basic_auth_button_view.handlebars doesn't exists.

**Comment by fehguy** [comment]
Please try out https://github.com/swagger-api/swagger-ui/pull/2014 which makes this dynamic.
