### ISSUE TITLE
Authentication Key is not being added for original URL.

### ISSUE THREAD

**Issue by hghammoud** [swagger-api/swagger-ui#1537]
I followed the documentation to add an api_key inside the headers of ajax requests. This works perfectly when the /v2/api-docs is not secured. 

As soon as I request an authorised access to this endpoint /v2/api-docs , the swagger ui stops working and I get a non authorised access error and hence the swaggerui object stops working. This is due to the fact the Swagger adds the token only to the api calls after its initiated and not the the api entrypoint.

Is there any work around to add the token even when calling the  /v2/api-docs? Here is my code.

             var apiUrl = window.location.protocol + "//" + window.location.host;

            if (window.location.pathname.indexOf('/swagger-ui/index.html') > 0) {
                apiUrl += window.location.pathname.substring(0, window.location.pathname.indexOf('/swagger-ui/index.html'))
            }
            apiUrl += "/v2/api-docs";
            console.log('API URL: ' + apiUrl);

            window.swaggerUi = new SwaggerUi({
                url: apiUrl,
                dom_id: "swagger-ui-container",
                validatorUrl : null,
                supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
                onComplete: function(swaggerApi, swaggerUi) {

                    $('pre code').each(function(i, e) {
                        hljs.highlightBlock(e)
                    });

                    addApiKeyAuthorization();
                },
                onFailure: function(data) {
                    log("Unable to Load SwaggerUI");
                },
                docExpansion: "none",
                apisSorter: "alpha"
            });

            function log() {
                if ('console' in window) {
                    console.log.apply(console, arguments);
                }
            }

            function addApiKeyAuthorization(){
                var authToken = JSON.parse(localStorage.getItem("ls.token")).token;
                window.swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("X-Auth-Token", authToken, "header"));
            }

            var authToken = JSON.parse(localStorage.getItem("ls.token")).token;

            window.swaggerUi.load();

I dont know if I was clear with my explanation.

**Comment by acinader** [comment]
hey @hghammoud, if your doc url requires some kind of authentication, you just need to setup the SwaggerUI with the proper config.  Here's an example that would add `api_key=TEST` to the end of your url:

```
 var apiKey = 'TEST';
 window.swaggerUi = new SwaggerUi({
        url: url,
        // note the addition of this line below which will always add this auth to requests.....
        authorizations: { api_key: new SwaggerClient.ApiKeyAuthorization('api_key', apiKey, "query") },
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
....
```

I think this issue can be closed.
