### ISSUE TITLE
Images broken when using http-headers

### ISSUE THREAD

**Issue by agusgr** [swagger-api/swagger-ui#1540]
Hi,

I'm working with the 2.1.1 version and I have the same issue described en #519 

My situation:

When the response handler in the UI detects that the response is an image, put the content in an "<img>" tag and sets the request URL as the src. 
The browser tries to load the image data but the request not have the http headers so the request is rejected by the backend. Digging into the problem I see that the "src" attribute in  tag cannot handle HTTP headers so I think that maybe using the a different approach could work in this situation: instead relaunch the request, encode the response as base64 and use it in "src" as a data uri (<img src="data:image/gif;base64,R0....")

Any other ideas or advices are welcome,

Regards,

Agus

**Comment by agusgr** [comment]
Hi all,

If someone need a workaround, we are dealing with this by changing the header parameter to a query parameter.

In this way, when the request are replayed includes the query param and everything works.

Hope this helps someone,

Regards

**Comment by ddowling-act** [comment]
+1, we're seeing this and we can't use the workaround as described (auth must be a set header)

**Comment by fehguy** [comment]
There's really no way to do this other than to use blob features in javascript to download without AJAX, but that breaks backwards compatibility.  You simply can't set an image URL with headers, AFAIK.
