### ISSUE TITLE
external $ref are ignored - files are not fetched

### ISSUE THREAD

**Issue by yanivc24** [swagger-api/swagger-ui#1541]
Hello 

I have created a json schema that contains two external references:

``` json
{
    "swagger": "2.0",
    "info": {
        "version": "3.0.0",
        "title": "APIs"
    },

    "paths": {
        "/orders/v3/search": {            
            "$ref":"/json-schemas/orders/api/search.json"            
        },
        "/users/v3/search": {
            "$ref":"/json-schemas/users/api/search.json"
        }
    }
}
```

the thing is that looking at the network tab of the browser I see that the swagger editor does not even try to fetch these $ref files. this works very well in swagger-editor though. 

any ideas?

Many Thanks

Yaniv

**Comment by webron** [comment]
Which version of swagger-ui have you tested it with?

**Comment by yanivc24** [comment]
The latest one, currently 2.1.1

**Comment by nrekretep** [comment]
swagger-editor now supports external $ref. While creating my swagger-spec inside swagger-editor I should be able to split a big spec file into multiple smaller files and the editor can resolve the external $refs.
But this doesn't help if the swagger-ui is not able to resovle the external $refs, too. 
Is it possible to get this fixed soon?

**Comment by webron** [comment]
Can you please try the latest version again (2.1.3)?
