### ISSUE TITLE
Path and header variables mixed when constructing the execution path

### ISSUE THREAD

**Issue by mortias** [swagger-api/swagger-ui#1542]
For my "tryitout" button i have some parameters to pass,
the point is when i pass the same variable but a different type the path is constructed incorrectly,

in my parameters list i have
  Language / "en" / path / String
  Language / "nl" / header / String

http://server:port/api/path/services/dev/nl instead of
http://server:port/api/path/services/dev/en  because that one was the query parameter.. ?

**Comment by webron** [comment]
This shouldn't be an issue in the new UI.
