### ISSUE TITLE
Response body empty for text/csv on Firefox

### ISSUE THREAD

**Issue by msprunck** [swagger-api/swagger-ui#1544]
The response body is empty when I request my api with the text/csv mime type. When I inspect the HTML, a link has been generated but the text is empty without any javascript error. See below:

``` html
<a href="blob:http://localhost:8080/6c544eb1-4c5e-414e-9be7-ea66a384ec5e" download="text/csv:example?param=value:blob:http://localhost:8080/6c544eb1-4c5e-414e-9be7-ea66a384ec5e"></a>
```

The url is:
http://localhost:8080/api/v1/example?param=value

Headers:
"content-type": "text/csv; charset=utf8"
"content-disposition": "attachment;filename=example.csv"

I use Firefox 40.0.2 on MacOsx. It works on Chrome and Safari.

**Comment by fehguy** [comment]
This should be fixed now.
