### ISSUE TITLE
Render externalDocs in all applicable locations

### ISSUE THREAD

**Issue by lmprice** [swagger-api/swagger-ui#1545]
I'm currently using Swagger-Core 1.5.3 with Swagger-UI @ 59c1003 , and I'm not seeing the results of any externalDoc additions to in the swagger-ui. I can add an externalDoc at the top level, but it currently isn't working for Operations, Tags, or Models, which are things I think many users would want.

**Comment by nrekretep** [comment]
+1
Am 18.08.2015 21:10 schrieb "lmprice" <notifications@github.com>:

**Comment by obfischer** [comment]
I need this feature too for our documentation.

**Comment by webron** [comment]
We'll use this ticket to collectively add support for all `externalDocs` location in all support spec versions. Modifying the topic to reflect that.

**Comment by chameleon82** [comment]
Need to explain Model properties with external doc
For example:
```scala
class Scheduler(
     @Schema(
        title = "Cron formatted invoice schedule",
        example = "0 0 8 5 * *"
        externalDocs = new ExternalDocumentation(
          description = "Here is how to define it properly",
          url = "http://myconfluence.org"
        )
    )
    cron: String   
)
```

I can see it in UI, but it is in wrong format:
```
example = "0 0 8 5 * *"
externalDocs: OrderedMap { "description" : "Here is how to define it properly", "url" :  "http://myconfluence.org" }
```
instead of actual link. Should i open bug for this issue?

**Comment by wapmorgan** [comment]
Faced the same problem, with `externalDocs` in a tag - it does not rendered.

**Comment by terrencewei** [comment]
We need this features to display the `externalDocs` in tag too, is anyone know when this will be implemented?

**Comment by ErNehaDeshwal** [comment]
I cannot see the URL as clickable link on the Swagger UI. 
please let me know how to do that?
