### ISSUE TITLE
DataType shows String rather than class model repretentacion

### ISSUE THREAD

**Issue by nokiajavi** [swagger-api/swagger-ui#1547]
Hi, I have a pathParam consisting of a @EmbededId and it consists of 2 variables. Their representation in JSON is: {\"id\":1,\"date\":1433109600000}

When Swagger UI represents the Pathparam of that class, it indicates that the datatype is of type String , instead of showing the model representing the class into JSON, as it does with the parameters of body.

My class has the label: @ApiModel @Embeddable @XmlRootElement and its attributes have the @ApiModelProperty

code WEB service: 
public Response createMonth(@ApiParam()	@PathParam("id") PersonEmbeddedId id);

**Comment by webron** [comment]
Swagger doesn't support models for path parameters, only primitives.

**Comment by nokiajavi** [comment]
Ahh ok, There any way represent para a model pathparam ? With a converter or something

**Comment by webron** [comment]
Nope, it's simply not supported. It's generally considered a bad practice.

**Comment by nokiajavi** [comment]
Ok Thanks!
