### ISSUE TITLE
required body parameter keys still shown as optional

### ISSUE THREAD

**Issue by bandtank** [swagger-api/swagger-ui#1549]
The output of the following JSON doesn't list the required keys as required. Is this right? These keys shouldn't show the optional text: summary and send_to.

![screen shot 2015-08-19 at 2 29 21 pm](https://cloud.githubusercontent.com/assets/1170415/9368144/dd945c26-467e-11e5-9c7c-1b669f57385c.png)

![screen shot 2015-08-19 at 2 29 53 pm](https://cloud.githubusercontent.com/assets/1170415/9368148/e0a3e1e8-467e-11e5-9171-ad34d64fc360.png)

**Comment by webron** [comment]
This is using which version?

**Comment by bandtank** [comment]
@webron 2.9.6

**Comment by webron** [comment]
There's no 2.9.6 version of swagger-ui. Take a look at the top of the swagger-ui.js file.

**Comment by bandtank** [comment]
@webron Sorry, it's all still a little confusing. There seem to be 400 different ways to use swagger. My file says this: ` @version v2.1.2-M2`

**Comment by webron** [comment]
Okay, ignore the gem, and try using version from the master branch to load it. There were quite a few bugs in the milestone developments (hence, milestones).

**Comment by bandtank** [comment]
This is working great after ditching the gem. Thanks.
