### ISSUE TITLE
Validator is marking 1.2 spec as Deprecated

### ISSUE THREAD

**Issue by lynnaloo** [swagger-api/swagger-ui#1550]
I've tried this using 2.1.0 and the latest in `master` and the validation fails:

`[{"level":"error","message":"Deprecated Swagger version.  Please visit http://swagger.io for information on upgrading to Swagger 2.0"}]`

```
{
    "apiVersion":"1.0",
    "swaggerVersion":"1.2",
    "apis":[
        {
            "path": "http://blah/thatApi.json",
            "description":"Service"
        },
        {
            "path": "http://blah/thisApi.json",
            "description":"Service"
        }
    ],
    "info":{
        "title":"APIs",
        "description":"API Documentation"
    }
}
```

**Comment by fehguy** [comment]
That's because it is deprecated. We're on 2.0 now

**Comment by lynnaloo** [comment]
Is the compatibility matrix in the README.md out of date? It says that 1.2 spec is still supported.

**Comment by fehguy** [comment]
Deprecated in this context means it is an obsolete version. We will support the tools based on 1.2 but you would be wise to upgrade to 2.0 as we are not adding features for 1.2 spec versions.

**Comment by lynnaloo** [comment]
The json files I'm referring to in my `apis` are 2.0 spec, so that's probably the real reason that I'm not seeing them show up, not the validator.

**Comment by fehguy** [comment]
Hi, I think I understand.  The 2.0 spec files should show up with a validator badge as valid, invalid, or error.  The exception is if the swagger-ui sees `localhost` as the host, it won't bother trying because it cannot reach your machine, since validator is a remote service, and localhost is not routable.

Does that make sense?

**Comment by lynnaloo** [comment]
I updated my example above because the two API paths are actually full urls. However, the resource listing I posted above is 1.2 spec and the two APIs listed are in 2.0 spec. They're all pushed up to my web server, so they're not localhost but the links to the two APIs just don't show.

**Comment by fehguy** [comment]
OK I get it.  This is not a microservice format--it's expecting a [Resource Listing](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#51-resource-listing) and an [API Declaration](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#52-api-declaration).  You can't put a 2.0 spec behind the 1.2 resource listing like I think you're doing.

**Comment by fehguy** [comment]
I suggest if you want to talk through options, jump into here and we can discuss:

webchat.freenode.net/?channels=swagger

**Comment by lynnaloo** [comment]
Thanks @fehguy!
