### ISSUE TITLE
ReferenceError: Handlebars is not defined

### ISSUE THREAD

**Issue by RaviVaranasi** [swagger-api/swagger-ui#1551]
Trying to generate documentation for endpoint from my api-docs.json definition.

Am i missing something or setting up swagger ui incorrectly ?

Below is the exception 

```
this["Handlebars"]["templates"]["apikey_button_view"] = Handlebars.template({"
                                                        ^
ReferenceError: Handlebars is not defined
  at Object.<anonymous> (/app/node_modules/swagger-ui/dist/swagger-ui.js:9:57)
  at Object.<anonymous> (app/node_modules/swagger-ui/dist/swagger-ui.js:32183:7)
```

express controller below:

```
import Handlebars from 'handlebars';
import SwaggerUi from 'swagger-ui';

var app = express();

let swaggerUi = new SwaggerUi({
  url:'/api-docs.json'
});
swaggerUi.load();


// Serve up swagger ui at /docs via static route
var docs_handler = express.static(__dirname + '../../node_modules/swagger-ui/');
app.get(/^\/docs(\/.*)?$/, function(req, res, next) {
    if (req.url === '/docs') { // express static barfs on root url w/o trailing slash
    res.writeHead(302, { 'Location' : req.url + '/' });
    res.end();
    return;
  }
  // take off leading /docs so that connect locates file correctly
  req.url = req.url.substr('/docs'.length);
  return docs_handler(req, res, next);
});
app.get('/api-docs', (req, res) => {
    res.json(swaggerJsonConfig);
});

export default app;
```

**Comment by NiveditN** [comment]
Hi, have you tried importing the modules in ES5 way? 
`var Handlebars = require('handlebars');`
Does that change anything?

**Comment by oaktowner** [comment]
I get the same behavior -- note that I'm not importing the Handlebars module, this seems to be done in the swagger-ui.js file itself.

**Comment by fehguy** [comment]
Howdy, if you're looking to set up swagger-ui, you don't need to use express as an app server.  I may be answering the wrong question, but the easiest way to do this is:

* Clone swagger-ui from git@github.com:swagger-api/swagger-ui.git
* Run http-server from the dist folder:

```
npm install -g http-server
http-server --cors
```

then you can open swagger-ui at `http://localhost:8080`

**Comment by Chris0lsen** [comment]
Hi, similar issue here. I navigated to the node_modules/swagger-ui directory and ran npm install handlebars from there, but got the same error. THEN I entered node_modules/swagger-ui/dist/swagger-ui.js and added var Handlebars = require('handlebars'), and got the following error: 

Error: Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1).

So that's confusing. Anybody else seeing this?

**Comment by fehguy** [comment]
@Chris0lsen can you please rm -rf the `node_modules` and run `npm i` again?

**Comment by ctippur** [comment]
Any updates on this? I am facing the same issue.

**Comment by ctippur** [comment]
I have removed node_modules and tried it. I get the same error.

**Comment by GreenPioneer** [comment]
I am having the same problem

has anyone been able to solve this

**Comment by GreenPioneer** [comment]
@RaviVaranasi @Chris0lsen @fehguy  /\

**Comment by maxiejbe** [comment]
Same issue here. For now I'm just using the online docs generator: http://generator.swagger.io/

**Comment by ChristianRich** [comment]
+1

I have no idea how to run this inside my express app - should be dead simple but getting same errors as your guys.

**Comment by GreenPioneer** [comment]
@ChristianRich 

[Check out my way](https://github.com/greenpioneersolutions/meanstackjs/blob/master/server.mean.js#L299) around it and note the [version im on](https://github.com/greenpioneersolutions/meanstackjs/blob/master/package.json#L146)

**Comment by webron** [comment]
Anyone wants to give it a spin with 3.0?

**Comment by GreenPioneer** [comment]
@webron yea ill give it a try in my [meanstackjs](meanstackjs.com)

**Comment by webron** [comment]
This should no longer be an issue with 3.X.
