### ISSUE TITLE
Multiple basepath for swagger ui

### ISSUE THREAD

**Issue by nooruddin** [swagger-api/swagger-ui#1554]
I am using swagger-ui to provide nice documentation for REST APIs to our clients.
Internally we have two different environments jenkin builds the project to.
E.g. swagger.json is accessible on both environment as:
http://www.myhost.com/xyz/rest/swagger.json
https://www.myhost2.com/rest/swagger.json

Documentation is available as:
http://www.myhost.com/xyz/dist/index.html
https://www.myhost2.com/dist/index.html

swagger api basepath in web.xml is:
```
<init-param>            
          <param-name>swagger.api.basepath</param-name>
          <param-value>/rest</param-value>
</init-param>
```
ISSUE:
I am trying to use "Try it out" feature on documentation page.
The respective request url for both hosts are as follows:
http://www.myhost.com/rest/getAUser
https://www.myhost2.com/rest/getAUser

It works for host2 as it is hitting the correct url.  However it should have hit http://www.myhost.com/xyz/rest/getAUser for host1 but it is hitting the url http://www.myhost.com/rest/getAUser.

Is there a way I can specify multiple basepath for different urls.  Is this a bug or am I doing something wrong in first place.

My swagger-ui html looks something like this.
```
$(function () {
   	  var href = window.location.href;
      var url = href.substring(0, href.lastIndexOf("/dist"));
      console.log(url);
      // Pre load translate...
      if(window.SwaggerTranslator) {
        window.SwaggerTranslator.translate();
      }
      window.swaggerUi = new SwaggerUi({
        url: url + "/rest/swagger.json",
        dom_id: "swagger-ui-container",
    ......
    ......
}
```

**Comment by webron** [comment]
It works as expected as your `basePath` is not the same for the two environments. For one it's indeed `/rest`, but for the other it's `/xyz/rest`. If it's different between the environments, you'd have to set it up so it changes between the environments as well.

**Comment by nooruddin** [comment]
What is the most appropriate way of writing that piece of code? 
Do I handle it in BootStrap or Filter? Any technical advise would be appreciated.
Thanks.

**Comment by webron** [comment]
If you set it from code (even from web.xml in some cases), then you could set it based on some environment variable, yeah, but it would still need to come from the environment itself. If you depend on a specific application server, you may be able to get the information from it.

**Comment by nooruddin** [comment]
Great.  Thanks for prompt response and time.
I saw some programmatic way of achieving that in this issue (https://github.com/swagger-api/swagger-core/issues/62) as recommended by @fehguy.
But I was not able to locate the ConfigReader in swagger-jersey2-jaxrs or swagger-core. I just want to make sure I consider all available swagger functionality before writing any piece of code.

**Comment by webron** [comment]
That's from an older version of the project.

**Comment by nooruddin** [comment]
Ok. Thanks @webron for quick response.

**Comment by nooruddin** [comment]
I was able to resolve this issue by configuring swagger using BeanConfig instead of using Servlet in web.xml

BeanConfig class:

    public class SwaggerBootstrap extends DefaultJaxrsConfig {
    
        /**
         *
         */
        private static final long serialVersionUID = myAutoGeneratedID;
    
        @Override
        public void init(ServletConfig config) throws ServletException {
    
            super.init(config);
            //realPath will be null for host2 and /xyz for host1.
            String realPath = config.getServletContext().getContextPath();
    
            BeanConfig beanConfig = new BeanConfig();
            beanConfig.setVersion("1.0.0");
            beanConfig.setTitle("My API Documentation");
            beanConfig.setSchemes(new String[] {
                    "http", "https"
            });
            beanConfig
            .setResourcePackage("com.example.my.rest.api.package");
    
            beanConfig.setBasePath(realPath + "/rest");
            beanConfig.setScan(true);
        }
    }
and in web.xml:
 

    <servlet>
        	<servlet-name>SwaggerBootstrap</servlet-name>
        	<servlet-class>my.package.to.SwaggerBootstrap</servlet-class>
        	<init-param>
        		
    			<param-name>scan.all.resources</param-name>
    			<param-value>true</param-value>
    		</init-param>
    		<load-on-startup>2</load-on-startup>
        </servlet>
And I changed my pom.xml to start using latest stable version of swagger-jersey2-jaxrs:

    <dependency>
      			<groupId>io.swagger</groupId>
      			<artifactId>swagger-jersey2-jaxrs</artifactId>
      			<version>1.5.3</version>
    		</dependency>

**Comment by webron** [comment]
Great, thanks for the update.
