### ISSUE TITLE
Feature request: Sample JSON

### ISSUE THREAD

**Issue by j-m-baker** [swagger-api/swagger-ui#1555]
I think it would be useful to provide 'sample JSON', ie fully formed JSON objects that the user can easily push into a request. Whilst it's lovely to see a model and edit it, if there are 10 parameters or something and the user is 'new' to the API, a few examples easily illustrate the use cases. 

I guess this would be implemented by some separate service that can return an example, or even by annotating the existing service with a list of examples? The UI would then allow the user to select an example (if available) and run it.

**Comment by jasonh-n-austin** [comment]
This exists, you should add 'example:' to your schema object: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object-examples
Once you add the example object to schema, you'll get example requests/responses in swagger-ui.

**Comment by j-m-baker** [comment]
Can this be implemented using io.swagger, ie annotations?

Also is it possible to set the Content-Type header through the UI, so one can ask the client for XML or JSON and hence the client can send the appropriate response?

**Comment by jasonh-n-austin** [comment]
Not sure what you're asking about on the annotations, and/or what 'io.swagger' is.

`consumes` and `produces` allow you to specify content-types, at the swagger root, or per-operation. 
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#swagger-object
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#path-item-object-example

**Comment by webron** [comment]
@j-m-baker - no, the swagger-core annotations do not allow you to add examples, even though it can be controlled in an alternative way (not very conveniently). Feel free to open an issue on that.

Assuming you're using JAX-RS, swagger-core will parse your `@Produces` annotation for the response type control.

**Comment by j-m-baker** [comment]
I've annotated my service:

```java
@Consumes({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
@Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
```

but Swagger only presents me with a Content-Type control, so no way to select the type I'd like the service to produce.

**Comment by j-m-baker** [comment]
I've checked that the io.swagger service is producing the following in the JSON sent to SwaggerUI:


            "produces":[
               "application/xml",
               "application/json"
            ],

maybe I mis-understand and the UI only displays a Content-Type drop down based on the values in 'consumes'?

**Comment by j-m-baker** [comment]
I'm being useless. The client only sends Content-Type. For some reason, I thought it may send Accept.
