### ISSUE TITLE
With known good token in '?url', enable 'On/Off' box

### ISSUE THREAD

**Issue by jharmn** [swagger-api/swagger-ui#1556]
I've looked through the docs on customizing at https://github.com/swagger-api/swagger-ui#swaggerui and couldn't find this. 

I scenarios where we've pre-populated the access token in swagger-ui (either by hardcoding in `index.html` or redirecting somewhere with `?url=xxx`), the `On/Off` slider on each operation is set to `Off`. As such, we have to go through the OAuth 2 redirect in order to use the already good token. 
If we don't go through the token flow, the existing code does not pass `Authorization` in the CORS/OPTION pre-flight. As such, the `Authorization` header is never passed, and we get 401s on all requests.

Is there an option somewhere to let `SwaggerUI` know that the `On/Off` slider should be set to `On` for all operations?

**Comment by webron** [comment]
As far as I know, we don't expose such an option, but @fehguy would probably know more.

**Comment by webron** [comment]
This is no longer relevant in the new UI.
