### ISSUE TITLE
Disable 'Try it out' button

### ISSUE THREAD

**Issue by peter004** [swagger-api/swagger-ui#156]
How can I just disable 'Try it out' button for specific POST method?

Thanks in advance

**Comment by nikhiljindal** [comment]
Would like to throw in my +1 for a SwaggerUi parameter to remove the "Try it now" button everywhere.

Doesnt look like there is a readOnly Param: https://github.com/swagger-api/swagger-ui#parameters

**Comment by sberardelli** [comment]
+1 for being able to disable it as needed.  Not an all or nothing.
Scenario is in a production environment, I want to allow consumers to perform a GET, see what results, formats, etc are returned.  I do NOT want them to do a PUT, POST, DELETE, etc.
I DO want that ability in a dev, qa, or some other lower environment....

**Comment by webron** [comment]
@sberardelli - as mentioned above, you have the supportedSubmitMethods property that lets you decide which operations are executable. You can look at the http://petstore.swagger.io for example.

**Comment by cnaut** [comment]
The supportedSubmitMethods property seems to just grey out certain areas. Is there a property for completely removing the functionality?

**Comment by tejasdewan** [comment]
Hi,

I am using io.swagger. 

In the swagger-ui.js, you can use 
"21":function(depth0,helpers,partials,data) {
	var method = depth0.method;
	if ( method == "post" )
		{return "          <div class='sandbox_header'>\n            <input class='submit' type='submit' style='display:none' value='Try it out!' data-sw-translate/>\n            <a href='#' class='response_hider' style='display:none' data-sw-translate>Hide Response</a>\n            <span class='response_throbber' style='display:none'></span>\n          </div>\n"; }
    return "          <div class='sandbox_header'>\n            <input class='submit' type='submit' value='Try it out!' data-sw-translate/>\n            <a href='#' class='response_hider' style='display:none' data-sw-translate>Hide Response</a>\n            <span class='response_throbber' style='display:none'></span>\n          </div>\n";
  }

to disable the "Try it out!" for the POST request. Likewise it can be used for other hhtpMethods("delete", etc.) as well.

**Comment by fehguy** [comment]
per @webron, set the `supportedSubmitMethods` values https://github.com/swagger-api/swagger-ui#parameters

**Comment by FerrariAlberto** [comment]
where do i set the supportedSubmitMethods?

**Comment by webron** [comment]
@FerrariAlberto it's not supported in the current version.

**Comment by nickeeromo** [comment]
Just also wanted to voice that an easy way to simply get rid of the button for some http requests would be nice.  Perhaps an annotation could work well?

**Comment by rbjorklin** [comment]
If you use Openapi 3.0.0 it seems to default to all methods disabled. Anyone know how to enable them? Found a converter 2.0 -> 3.0.0 here: https://github.com/mermade/swagger2openapi

**Comment by webron** [comment]
See:
https://github.com/swagger-api/swagger-ui/releases/tag/v3.1.0
https://github.com/swagger-api/swagger-ui/issues/3338

**Comment by mhong19414** [comment]
I just put this in the `onComplete` callback:

```
                onComplete: function(swaggerApi, swaggerUi){
                    ...

                    $('.sandbox_header').each(function(i,e) {
                        $(e).hide();
                    })
                }
```
