### ISSUE TITLE
Swagger-core does not provide example annotation

### ISSUE THREAD

**Issue by j-m-baker** [swagger-api/swagger-ui#1561]
According to (this issue) [https://github.com/swagger-api/swagger-ui/issues/1555], it is possible to include an example request for the Swagger UI, but swagger-core does not implement this. Are there any pointers to get me started in order to add this feature?

**Comment by j-m-baker** [comment]
Someone has made a start on implementing the example:

io.swagger.models.ModelImpl:

```java


    public Object getExample() {
        if (example == null) {
            // TODO: will add logic to construct examples based on payload here
        }

        return example;
    }
```

**Comment by webron** [comment]
@j-m-baker - please open it on the actual project (swagger-core) and not here.
