### ISSUE TITLE
Content-Type: application/json; charset=UTF-8 not valid

### ISSUE THREAD

**Issue by j-m-baker** [swagger-api/swagger-ui#1564]
Swagger sets the header:

Content-Type: application/json; charset=UTF-8 not valid

but application/json has no registered character set.

**Comment by webron** [comment]
Need more info here, the issue is unclear.

**Comment by mherb63** [comment]
The swagger client is generating this:

Content-Type:application/json;charset=UTF-8

The generated code for the Api is expecting something like this:

	@RequestMapping(value = "/{id}", produces = { "application/json" }, consumes = { "application/json" }, method = RequestMethod.GET)


The error is from the swagger ui page:

{"timestamp":1446169080523,"status":400,"error":"Bad Request","exception":"org.springframework.web.HttpMediaTypeNotSupportedException","message":"Content type 'null' not supported","path":"/xxxx/blablabla"}

**Comment by webron** [comment]
Please retest with 3.0 and reopen if needed.
