### ISSUE TITLE
Values for enum possible

### ISSUE THREAD

**Issue by hypknowsys** [swagger-api/swagger-ui#1565]
Hi all,

is it possible to add different values to enum declarations?

Example: 

        {
                        "name": "format",
                        "description": "Response format (json, xml, csv, html).",
                        "enum": [
                            "Here you will find the Format JSON",
                            "Here you will find the Format  XML",
                            "Here you will find the Format  CSV",
                            "Here you will find the Format  html"
                        ],
                        "required": false,
                        "type": "String",
                        "paramType": "query"
             }

So the URL contains format=Here%20you%20will%20find%20the%20Format%20%20XML

What I want is to create a separate value the entires, like 

<option value="1">Here you will find the Format  XML</option>

and results into format=1

Is it possible.

Thanks for any advice,

H

**Comment by fehguy** [comment]
Yes, take a look at the [petstore example](http://petstore.swagger.io/v2/swagger.json) or the [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) for details.

**Comment by hypknowsys** [comment]
Hi fehguy,

thanks for the quick answer. Anyway: I already looked into the example and into the spec. Maybe I 
am blind, but I can not find it. 
Type "Array" produces multiple selection, enum produces one selection (e.g. "enum":["placed","approved","delivered"]} in the example. 

What I want is 
```
<option value="1">placed</option>
<option value="2">approved</option>
<option value="3">delivered</option>
```
(to speak in petstore example language)
Is there a trick for that? 

Thanks for reply,

H

**Comment by webron** [comment]
You can't do that, @hypknowsys - it's not supported by the spec.

**Comment by hypknowsys** [comment]
Hi Ron,
ok: thanks for the quick response and the update. 

Greetings from Germany,


H
