### ISSUE TITLE
How do I tell swagger-ui sandbox to not follow redirect responses?

### ISSUE THREAD

**Issue by christianbellinaef** [swagger-api/swagger-ui#1569]
I'd like for the curl sandbox request to not follow any 302 redirect responses it receives, is there a setting somewhere I can set? Or where in the code could I override this?

**Comment by m-radzikowski** [comment]
From what I found sadly there is no such option right now. I also would like to turn off following redirects by swagger-ui and instead see message about redirect with url, similary to how it works in DHC REST Client addon: https://chrome.google.com/webstore/detail/dhc-rest-client/aejoelaoggembcahagimdiliamlcdmfm

**Comment by kleewho** [comment]
I would also like to disable redirects. Any chance to get at least guidance with implementation?

**Comment by fehguy** [comment]
You mean the curl output only?  Not the value when executing the request?  If so, you should look at the `asCurl` method in swagger-js and add an option to that.

**Comment by kleewho** [comment]
Ok, I will look into that although I was thinking about showing value (rather headers and http status) but without following redirection

**Comment by m-radzikowski** [comment]
I would like to see this feature too. But apparently it's not that easy as the browser automatically follows (AJAX) redirects. Swagger UI executes AJAX requests and probably only gets response after from last endpoint, after any redirects.

So it's almost impossible to not follow that redirect. Why almost? Here: http://stackoverflow.com/a/2573589 you can see there is new JS fetch() API that allows to catch request before redirection. But it's pretty new and supported only in the newest browsers.

See:
http://stackoverflow.com/questions/9177252/detecting-a-redirect-in-jquery-ajax
http://stackoverflow.com/questions/282429/returning-redirect-as-response-to-xhr-request
http://stackoverflow.com/questions/10013812/how-to-prevent-jquery-ajax-from-following-a-redirect-after-a-post

**Comment by fehguy** [comment]
You may be able to write a `responseInterceptor` and catch the `3xx` code.  Give it a shot and report back

**Comment by FinnNk** [comment]
Any news on what you found? This would make it a lot easier to represent async APIs.

**Comment by xperiandri** [comment]
Yep, this is very annoying behavior.

**Comment by xperiandri** [comment]
Moreover when it redirects to static file like image UI constantly display processing indicator and never finishes a request.

**Comment by webron** [comment]
Consider filing a PR to amend the behavior.

**Comment by shockey** [comment]
Even with Fetch (which IE11 doesn't support), if we ask for non-automatic redirection with `{ redirect: "manual" }`, we get an opaque response:

> "manual": Retrieves an opaque-redirect filtered response when a request is met with a redirect so that the redirect can be followed manually.
> 
> https://fetch.spec.whatwg.org/#requests

...

> An opaque-redirect filtered response is a filtered response whose type is "opaqueredirect", status is 0, status message is the empty byte sequence, header list is empty, body is null, and trailer is empty.
> 
> In other words, an opaque filtered response and an opaque-redirect filtered response are nearly indistinguishable from a network error. 
> 
> This also means that JavaScript APIs, such as response.ok, will return rather useless results.
> 
> https://fetch.spec.whatwg.org/#responses

So, we can decide to not follow but the redirect, but in exchange the response comes back with absolutely no information.

---

With this in mind, I'm going to close this out. It's just not possible to create a good user experience around this with the APIs we have access to today.
