### ISSUE TITLE
Absolute references don't work? 

### ISSUE THREAD

**Issue by Darshan-shivashankar** [swagger-api/swagger-ui#1571]
when we load the below swagger on to the swagger-UI we see that the model schema is showing a null value 

[
  null
] 

And when we select Model we don't see the actual reference to the schema. Can some help us here. 

``` json
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "My bug repro API"
    },
    "paths": {
        "/persons": {
            "get": {
                "description": "Gets Person objects",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "title": "ArrayOfPersons",
                            "type": "array",
                            "items": {
                                "$ref": "http://coreapiteam-test.apigee.net/v1/swagger/user.json"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by webron** [comment]
That's due to two problems:

1. CORS is not enabled for that URL. You can solve it for testing purposes using something like http://crossorigin.me/ (not a long term solution).
2. Your reference is wrong. You want to reference the Person inside, so `http://coreapiteam-test.apigee.net/v1/swagger/user.json#/Person`.

**Comment by Darshan-shivashankar** [comment]
Thanks @webron . I have set up the swagger UI on my local jetty server. Can you please point me to the following details : Access-Control-Allow-Origin so that i can enable CORS in my application.

**Comment by webron** [comment]
You mean - https://github.com/swagger-api/swagger-ui#or-how-to-deal-with-cant-read-from-server-it-may-not-have-the-appropriate-access-control-origin-settings?

**Comment by Darshan-shivashankar** [comment]
@webron the following worked "$ref": "http://crossorigin.me/http://coreapiteam-test.apigee.net/v1/swagger/user.json#/Person". But as you mentioned earlier this might not be a long term solution. I have added the CORS support on to my application server 
"coreapiteam-test.apigee.net"

<Add>
        <Headers>
            <Header name="Access-Control-Allow-Origin">*</Header>
            <Header name="Access-Control-Allow-Headers">origin, x-requested-with, accept</Header>
            <Header name="Access-Control-Max-Age">3628800</Header>
            <Header name="Access-Control-Allow-Methods">GET, PUT, POST, DELETE</Header>
        </Headers>
    </Add>

Do we require any further details ?

**Comment by webron** [comment]
Do you have any further issues right now?

**Comment by Darshan-shivashankar** [comment]
@webron I was able to get pass CORS issue. But i am some issue with Swagger UI

Here is my Swagger 2.0 

{
	"swagger": "2.0",
	"info": {
		"version": "0.0.0",
		"title": "My bug repro API"
	},
	"paths": {
		"/persons": {
			"get": {
				"description": "Gets Person objects",
				"parameters": [],
				"responses": {
					"200": {
						"description": "Successful response",
						"schema": {
							"title": "ArrayOfPersons",
							"type": "array",
							"items": {
								"$ref": "http://crossorigin.me/http://coreapiteam-test.apigee.net/v1/swagger/user.json"
								  
							}
						}
					}
				}
			}
		}
	}
}

Here is the user.json

{
	"type": "object",
	"title": "Person",
	"properties": {
		"name": {
			"type": "string"
		}
	}
}

But in the Swagger UI i am seeing a Null value under Model Schema.

![image](https://cloud.githubusercontent.com/assets/1955708/9536079/c7239efc-4cdc-11e5-843a-2e93eeef17d2.png)

Model 

![image](https://cloud.githubusercontent.com/assets/1955708/9536088/dda1dbbc-4cdc-11e5-874c-6c85a051053b.png)

We were able work through this issue in swagger-editor.

https://github.com/swagger-api/swagger-editor/issues/606

Can you please help us here.

**Comment by webron** [comment]
It should work, can't think of a reason right now it doesn't.

**Comment by webron** [comment]
Closing as assuming this is no longer an issue. Please reopen otherwise.
