### ISSUE TITLE
jquery.ba-bbq.min.js

### ISSUE THREAD

**Issue by dmlond** [swagger-api/swagger-ui#1573]
this does not appear to be in active development, and uses Jquery.browser, which is deprecated in jquery 1.9.1 or later.  Are there plans to move away from this jquery plugin for whatever it is doing in the swagger-ui javascript?

**Comment by fehguy** [comment]
We're stuck on this version only because of I.E. 8 support.  I think we're about to drop it but that's the hold up.

**Comment by dmlond** [comment]
cool. Thanks so much. I really like the interface, and it was very easy to wrap into my own system.

**Comment by ob-ivan** [comment]
Not directly related to the subj, but I'd like to see transition to jQuery 1.9 soon, too. I'm stuck with adding Angular Schema Form to SwaggerUI, and that does rely on modifying type property of input elements, which is unsupported by jQuery 1.8.

**Comment by ob-ivan** [comment]
BTW, replacing jQuery 1.8 with (jQuery 1.11 + jQuery Migrate plugin) worked for me. Hope this helps.

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if needed.
