### ISSUE TITLE
Invalid content type (application/octet-stream) for empty POST request body from docs page

### ISSUE THREAD

**Issue by nick13jaremek** [swagger-api/swagger-ui#1576]
Hi there,

I have defined my API in a swagger.json file and everything works fine so far in my local Swagger-UI except for one endpoint which seems to fail strangely.

It is a POST endpoint that requires one parameter in its path, no body content, as follows (I simplified the JSON for more readability): 

    {
        "/app/subscribe/{id}": {
            "post": {
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identifier of the application for which the user subscribes",
                        "required": true,
                        "type": "string"
                    }
                ]
            }
        }
    }

For some reason, when clicking on the "Try it out" button of my local Swagger-UI for this endpoint, I get the following error:

    {
      "code": "InternalError",
      "message": "Invalid content type (application/octet-stream).  These are valid: application/json"
    }

If I do a `curl` operation from the terminal for the same POST request but setting the content type to `application/json` then everything behaves fine.

Alternatively, if I add the `application/octet-stream` content type to the `consumes` object in *swagger.json*, then the "Try it out" request works fine.

It seems that the Swagger-UI does not set the content type of POST requests *without body* to `application/json`, but forces them to be of type `application/octet-stream`.

Do you have any idea what could be causing this scenario?

**Comment by arockstar** [comment]
Maybe I see this issue out of the context swagger specifications, but I would try to set Content-Length: 0 for POST request without body.

About content type “application/octet-stream”.
W3 tells us  - Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".

Don’t know what logic stands for server side requests processing… Assume that it don’t pay attention on given content-type in case empty body. Perhaps :)

**Comment by nick13jaremek** [comment]
@arockstar Everything is cleared up then, it didn't cross my mind to check the HTTP protocol RFC document beforehand.

Thank you very much :)

Closing this issue now. Sorry for the delay.
