### ISSUE TITLE
more feedback when trying to import broken file wanted

### ISSUE THREAD

**Issue by dothebart** [swagger-api/swagger-ui#1577]
I've used File->Ipmort File...
the file I tried had some debug output in place before the json, so it was neither valid yaml nor json.
All that happened was that the blue 'import' button would disable, no feedback why.

**Comment by webron** [comment]
Wrong project?

**Comment by webron** [comment]
Wrong project.

**Comment by dothebart** [comment]
oh, yes, was using the editor.
