### ISSUE TITLE
mark 'required' items visible to the user in 'try this'

### ISSUE THREAD

**Issue by dothebart** [swagger-api/swagger-ui#1579]
one can specify parameters mandatory when composing post-objects; If they're not specified a red message will appear to tell the user they're missing.

However, in the list itself there is no note that its mandatory. Please add a string like _mandatorry_ to the name-Header.

**Comment by mar612** [comment]
While they aren't explicitly labelled, mandatory parameters use boldface in the UI.  Also, mandatory parameters that accept strings have '(required)' entered into the text field by default.

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if needed.
