### ISSUE TITLE
"error": "no response from server" using Spring MVC stub server from codegen

### ISSUE THREAD

**Issue by glederrey** [swagger-api/swagger-ui#1587]
Hi,
I have some issue using the Spring MVC stub server and swagger-ui.. (I post the issue here, but I don't really if the problem comes from swagger-ui or the code provided by swagger-codegen..)

So, the problem is that I never get any response from the Spring MVC server.. Before I had some problems with the CORS.. I could get rid of this problem using this:
```
HttpHeaders headers = new HttpHeaders();
headers.add("Access-Control-Allow-Origin", "*");
headers.add("Access-Control-Allow-Methods", "POST, GET, OPTIONS, DELETE");
headers.add("Access-Control-Max-Age", "3600");
headers.add("Access-Control-Allow-Headers", "x-requested-with");

String str = "Deleted!";

return new ResponseEntity<String>(str, headers, HttpStatus.OK);
```
Now, the problem is that I don't receive any response.. See the picture attached.. Do you have any idea where this could come from??

Thank you in advance
![swagger-ui_no_response](https://cloud.githubusercontent.com/assets/13273462/9762040/fe4ab004-5700-11e5-8414-567ee7caf5f9.png)

**Comment by webron** [comment]
Have you tried running the API call directly? Have you checked the network logs? It's most likely an issue with the server.

**Comment by glederrey** [comment]
The thing is that it's working if I use the curl line or if I run it from my browser.. It's like swagger-ui cannot hear the server.. 

The network log gives a 200 response..

**Comment by webron** [comment]
`headers.add("Access-Control-Allow-Headers", "x-requested-with, Content-Type");` <-- try that.

**Comment by glederrey** [comment]
It didn't worked..

**Comment by webron** [comment]
Then check the browser's console for any errors.

**Comment by glederrey** [comment]
I will.. Just one question.. Is this possible that Java and js doesn't like the json responses?? Or something like that??

**Comment by glederrey** [comment]
Okay, I could make it worked.. 

I wasn't sending a correct JSON response.. Sorry for this.. And thank you a lot for your help..

**Comment by webron** [comment]
Great, thanks for the update.
