### ISSUE TITLE
Can't read from server. It may not have the appropriate access-control-origin settings.

### ISSUE THREAD

**Issue by Darshan-shivashankar** [swagger-api/swagger-ui#1588]
Hi ,

Can someone take a look at the below issue and provide some assistance. We have swagger-UI and the application hosted on the same server. i.e. same host and port. We have hosted the swagger-UI on the jetty server by extracting the swagger-ui-master.zip and copy the swagger-ui-master/dist folder into the jetty-distribution <Home>/webapps folder.

When i try to load the following swagger file http://localhost:8081/swaggerUI/updateCart.json we are seeing the CORS exception.

But when we try with a different swagger file

http://localhost:8081/swaggerUI/FinancialAccount_getFinancialAccountDetails.json it works as expected.

Can someone shred some light here.

**Comment by webron** [comment]
Unfortunately, the error message is misleading. If you can load one from the same application and not the other, it's most likely there's a general issue with the structure of the JSON you're trying to read. 

Try checking the web console for any additional errors when you're loading the file.

**Comment by Darshan-shivashankar** [comment]
@webron Thanks it worked. There was an issue with JSON structure.

**Comment by webron** [comment]
Thanks for the update, glad it worked out.
