### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by krysbzh** [swagger-api/swagger-ui#1590]
Hello,
I'm trying to create the swagger description of the Vtiger API (famous Opensource CRM). I follow the official documentation : https://wiki.vtiger.com/index.php/Webservices_tutorials .
Unfortunately, as you can see in the doc, the URL format of this API is http://vtiger_url/webservice.php?operation=OPERATION_NAME . 
What paths name can I use to identify every operations ? Is there a workaround ?
Exemple of two operations GET with the same path :

> ...
>    "host": "vtiger_url",
>    "basePath": "/",
> ...
>    "paths": {
>        "/webservice.php": {
>            "get": {
> ...
>                "summary": "Get a challenge token",
>                "description": "Get a challenge token from the server. This must be a GET request.",
>                "operationId": "getChallenge",
> ...
>                "parameters": [
>                    {
>                        "name": "operation",
>                        "in": "query",
>                    },
>                    {
>                        "name": "username",
>                        "in": "query",
>                    }
>                ],
>              }
>            },
>        "/webservice.php": {
>            "get": {
> ...
>                "summary": "Execute a query",
>                "description": "description",
>                "operationId": "query",
> ...
>                "parameters": [
>                    {
>                        "name": "operation",
>                        "in": "query",
>                    },
>                    {
>                        "name": "sessionName",
>                        "in": "query",
>                    },
>                    {
>                        "name": "query",
>                        "in": "query",
>                    }
>                ],
>              }
>            },
> ...

**Comment by webron** [comment]
I'm afraid you won't be able to use Swagger to describe that API. Swagger doesn't aim to be able to describe all possible 'REST-like' APIs, and it looks like Vtiger's API doesn't follow some of the more basic standards in the field (not a matter of right or wrong, it is what it is).
