### ISSUE TITLE
Unescaped HTML in value input 

### ISSUE THREAD

**Issue by jpzk** [swagger-api/swagger-ui#1595]
Just for fun, I tried this in the example http://petstore.swagger.io/#!/pet/addPet

In the input field I entered: `<h1>hello world<script>alert('test')</script></h1>`. The script is executed in the curl paragraph. Probably it's not a big deal, nevertheless, I thought it would be good to inform you.

**Comment by webron** [comment]
Thanks!

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/efb77652274e99893b11848f02d9dc37d07344aa
