### ISSUE TITLE
Browserify support?

### ISSUE THREAD

**Issue by achingbrain** [swagger-api/swagger-ui#1596]
Has anyone had any luck with using swagger-ui with Browserify?

I have an app.js file with the follwing:

``` javascript
var SwaggerUi = require('swagger-ui')

var swaggerUi = new SwaggerUi({
  // ... options
})
swaggerUi.load()
```

..and a gulp file with:

``` javascript
gulp.task('js', function () {
  return browserify({
    entries: ['./path/to/app.js']
  })
  .bundle()
  .pipe(source('app.js'))
  .pipe(gulp.dest('path/to/output/folder'))
})
```

Running gulp then results in:

``` sh
> gulp

[17:39:10] Using gulpfile ~/path/to/gulpfile.js
[17:39:10] Starting 'js'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './lib/auth' from '/path/to/my/project/node_modules/swagger-ui/dist'
    at /path/to/my/project/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/path/to/my/project/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/path/to/my/project/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /path/to/my/project/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

(paths changed to protect the innocent)

It looks like swagger-ui inlines swagger-client which has a bunch of calls to `require` which try to find a non-existent `./lib/auth` file.

**Comment by martinwoitzik** [comment]
Same here.. doesn't work with browserify "Cannot find module './lib/auth'"
Any solution available yet?

**Comment by achingbrain** [comment]
I actually had a go at browserifying swagger-ui at the end of last week - [npm](https://www.npmjs.com/package/swagger-ui-browserify), [repo](https://github.com/achingbrain/swagger-ui-browserify)

You have to do some fiddling with your gulpfile to make the web assets available, but it seems reasonably solid apart from that - I'd love to hear any feedback you have.

**Comment by Nautigsam** [comment]
Do you know if it exists alternative to swagger-ui that support browserify, because it seems @achingbrain stopped maintaining his repo. The problem is about jquery-bbq not being maintained, as covered in #1757 .

**Comment by achingbrain** [comment]
> because it seems @achingbrain stopped maintaining his repo

Erm, what gives you that idea?

**Comment by webron** [comment]
There shouldn't be issues using browserify with the new UI. Please file a new ticket if you're having issues.
