### ISSUE TITLE
Invalid cURL command for POST with no body

### ISSUE THREAD

**Issue by benzulanch** [swagger-api/swagger-ui#1600]
The curl command generated for a POST API with no body does not work. The generated command should include an empty data paramter (`-d ""`).

Example schema:

```
/myapi:
    post:
      responses:
        204:
          description: success
```

Generated curl command:

```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" "https://example.com/api/v1/myapi"
```

Running this command results in `HTTP 411 Length Required`.

Adding an empty data parameter to the curl command for the POST body allows the command to succeed:

```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" "https://example.com/api/v1/myapi" -d ""
```

Swagger version: 2.1.2
Curl version: 7.35.0 (x86_64-pc-linux-gnu)

**Comment by webron** [comment]
Is the body marked as required in your definition?

**Comment by benzulanch** [comment]
Not sure I understand the question. I'm not specifying any parameters or definitions.

**Comment by webron** [comment]
If you're not specifying a body parameter, why do you expect a body to be sent?

**Comment by benzulanch** [comment]
Because curl seems to require that a POST command with no body include an empty body parameter in the request.

As it is now, I have to manually append the `-d ""` parameter to the generated curl command in order to run it.

**Comment by webron** [comment]
Why is that related to curl? It looks more like an issue with your server configuration that it expects even a zero length body to be stated when no body is sent. As far as I know, POST does not require the content-length header to be sent if no body is provided, but if that's part of the RFC, then this is indeed an issue. If not, it's up to your server.

**Comment by benzulanch** [comment]
You're correct, it is our server (Ruby WEBrick) that's rejecting it: http://stackoverflow.com/q/2651379

The spec doesn't require there to be a POST body, but some web servers (as in the above) do require it.

So perhaps a configurable option to generate the empty body parameter would be good?

**Comment by webron** [comment]
It can be a feature request, but that would go to swagger-js, if you can open it there.

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
