### ISSUE TITLE
Using statically generated custom swagger.json in swagger-ui

### ISSUE THREAD

**Issue by sacredMonster** [swagger-api/swagger-ui#1602]
Disclaimer: New to everything open source.
I am trying to use a swagger.json file that i generated manually via swagger-editor in swagger-ui to produce a ui that hits a particular API.
I cloned the swagger-ui onto my windows machine, but when I try to build it using npm I get the following error:
![npmfailure](https://cloud.githubusercontent.com/assets/14304071/9894255/83a21c04-5bd6-11e5-8f6e-faf01bf0fa1d.JPG)
Do I need to download additional stuff to work npm and gulp commands work?
I just need to run the swagger-ui locally so that I can access a local copy of my swagger.json to hit the API i desire vs the petstore API.

Thanks

**Comment by fehguy** [comment]
Hi, do you need to rebuild it from scratch?  You might as well do the following:

* clone the swagger-ui repo
* install node (https://nodejs.org/en/)
* install http-server via `npm install -g http-server`

Then you can serve up swagger ui like this:

```
cd swagger-ui/dist
http-server --cors
```

and open swagger-ui from http://localhost:8080/index.html
