### ISSUE TITLE
Huge amount of body root level parameters

### ISSUE THREAD

**Issue by walski** [swagger-api/swagger-ui#1606]
Hey,

I'm about to build a Swagger spec for an already existing API. One endpoint of that API accepts many different root level body parameters. As a simple example lets just assume it's designed a way accepting the following bodies:

``` json
{
  "type": "car",
  "car": {
    "make": "BMW"
  }
}
```

or

``` json
{
  "type": "bike",
  "bike": {
    "color": "black"
  }
}
```

This is a minimal spec for that API:

``` yaml
swagger: '2.0'
info:
  title: Transportation API
host: api.example.com
schemes:
  - https
basePath: /api
produces:
  - application/json
consumes:
  - application/json
paths:
  /vehicles:
    post:
      summary: Create a vehicle
      parameters:
        - name: vehicle
          in: body
          required: true
          schema:
            $ref: '#/definitions/Vehicle
      responses:
        '200':
          description: Vehicle created
definitions:
  Vehicle:
    properties:
      type:
        type: "string"
        enum:
          - bike
          - car
      car:
        $ref: '#/definitions/Car'
      bike:
        $ref: '#/definitions/Bike'
  Car:
    properties:
      make:
        type: string
  Bike:
    properties:
      color:
        type: string
```

In swagger-ui this now ends up in one single body field that is a textarea with a model definition beside it. The only thing I can do with the model definition is either trying to figure things out by browsing through it or get a full dump of the definition pasted into the textarea. The problem with that is, that it will have a `type`, a `car` **AND** a `bike` root property in the body.

What I would like to have instead is some sort of UX that lets me "add" any optional parameter to the body (as defined in the body's model definition).

Is there any way to do that out of the box? Are there any sort of swagger-ui plugins?

The API I'm trying to cover right now comes with ~50 of these optional top level properties of which I only ever need one at a time. For users browsing the swagger-ui for that API feels totally unusable.

(And yes I know that the API design is not exactly perfect but I cannot change that now).

**Comment by fehguy** [comment]
Do you mean the `POST` body is a single object with *many* different properties?  If that's the case you will have to declare them as properties in the `Vehicle` object.

The "loose" way to do this would be to say that your object looks like this (and please correct me if this is wrong, @webron):

```json
{
	"definitions": {
		"Vehicle": {
			"additionalProperties": true,
			"properties": {
				"type": {
					"type": "string"
				}
			}
		}
	}
}
```

**Comment by webron** [comment]
My take on this is that the `type` is actually a discriminator and the others are sub types, that is, inheritance. @fehguy's suggestion works for a general-let's-not-define-anything solution while using the discriminator will allow a let's-define-all-but-allow-choosing-one solution.
Bear in mind that support for discriminator/inheritance is still incomplete in the ui.

**Comment by walski** [comment]
@fehguy Yeah that's what I meant single object many properties.

I really want to define them all as this is meant to be a documentation. I'm just wondering how to do it in a way that I end up with a sane UI. Or is there currently just no way to have that in this scenario? It's so weird it feels like having multiple body parameter is sooooo common in API design and the whole swagger UI seems to go south as soon as I have body parameters rather than query parameters.

Am I doing something wrong there?

**Comment by webron** [comment]
Swagger in general doesn't support multiple body parameter types for a single operation unless they have something in common to serve as a discriminator.

**Comment by walski** [comment]
@webron Sorry maybe my English is not up to par, but what exactly do you mean with a discriminator? Can you give an example? Thanks so much!

**Comment by webron** [comment]
No worries. The `discriminator` is a keyword in the swagger spec allowing you to define polymorphism.

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaDiscriminator
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism

**Comment by walski** [comment]
Perfect, will look at that, thans @webron !
