### ISSUE TITLE
SEO and google-ability of dynamic generation

### ISSUE THREAD

**Issue by erikvanzijst** [swagger-api/swagger-ui#1608]
As we're evaluating swagger-ui for our public-facing API documentation, I wonder if its dynamic approach of downloading `swagger.json` and constructing the page at runtime will prevent the documentation from getting crawled and becoming searchable.

According to Google:

> To make the crawler see what a user sees, the server needs to give a crawler an HTML snapshot, the result of executing the JavaScript on your page.

https://developers.google.com/webmasters/ajax-crawling/docs/learn-more

Is there anything I'm overlooking here, or could this really be an issue?

**Comment by fehguy** [comment]
While google is getting better at rendering & indexing dynamic content, I'm not sure if swagger-ui is indexable.  I do seem to find quite a few swagger-ui instances via google search, but haven't spent a bunch of time figuring out what is being indexed on them.

**Comment by erikvanzijst** [comment]
Google is getter better, but it does not currently run javascript to the point of making ajax calls, as indicated by their docs.

We're evaluating swagger-ui as a candidate for Bitbucket's future API documentation. However, searchability of the documentation is key to making our API accessible.

To verify, I got Google to index our swagger site, which confirmed that it merely looks at the index.html and never pulls down the swagger.json:

![swagger_search](https://cloud.githubusercontent.com/assets/63338/9979101/7284c5aa-5f0c-11e5-869e-b89828c3f48e.png)

Are there plans to make swagger-ui indexable, or providing a way to generate static HTML offline?

**Comment by dolmen** [comment]
Related: swagger-api/swagger-editor#664

**Comment by erikvanzijst** [comment]
So after learning about the `spec` attribute to `SwaggerUi()`, I can confirm that using that over the AJAX-based URL approach fixes the crawling problem.

I embedded the swagger json data in a `.js` file:

    $ ( echo -n 'var spec = ' && curl http://url.to/swagger.json ) > swagger.js

then loaded that synchronously in the page's head:

```javascript
<script src='/swagger.js' type='text/javascript'></script>
```

fed it to `SwaggerUi()`:

```javascript
window.swaggerUi = new SwaggerUi({
  url: null,
  spec: spec,
  ...
```

And Google now indexes correctly:

![swagger-seo](https://cloud.githubusercontent.com/assets/63338/10464490/d2a36212-719e-11e5-89c7-8b037128bd76.png)

**Comment by webron** [comment]
@erikvanzijst - thanks for sharing the details of your research. I'm sure it would prove helpful to other users.

**Comment by imZack** [comment]
wow, very useful hack. it's better to add in docs.
thanks for sharing.
