### ISSUE TITLE
swagger-ui fail to renderer swagger-spec petstore/separate example (problem in allOf $ref handling)

### ISSUE THREAD

**Issue by gurubook** [swagger-api/swagger-ui#1609]
swagger-ui fail to renderer swagger-spec v2.0 petstore/separate example. 
Will report a "Cannot read property 'split' of null" during resolution of relative $ref to Pet.json in NewPet.json definition.
This is caused by Resolver.processAllOf call to Resolver.resolveInline with parameter "root" = null.
Resolver.resolveInline will try to do "root.split('/') and will fail.

**Comment by gurubook** [comment]
More test revealed that swagger-ui/js can only  resolve correctly allOf $ref when the referenced object is an internal reference "#/Something"

**Comment by webron** [comment]
I assume you mean https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/json/petstore-separate.

**Comment by gurubook** [comment]
yes, i tried other $ref style, and allOf work with : 
* if you put all object (Pet and NewPet) in one .json file and made internal reference eg. #/Pet
* absolute reference eg: http://yourhost/spec/Pet.json

**Comment by gurubook** [comment]
With this patch root.split NPE does not occur, but the problem lie elsewhere eg. :
POST /pet body parameter datatype is now : "http://localhost:8000/spec/NewPet.json#Pet.json is not defined!" 

--- cut here 8<-------------------------

diff --git a/dist/swagger-ui.js b/dist/swagger-ui.js
index d64e532..0e7edf7 100644
--- a/dist/swagger-ui.js
+++ b/dist/swagger-ui.js
@@ -2328,31 +2328,33 @@ Resolver.prototype.resolveInline = function (root, spec, property, resolutionTab
       }
       rootTrimmed = true;
     }
-    if(ref.indexOf('#') >= 0) {
-      if(ref.indexOf('/') === 0) {
-        rs = ref.split('#');
-        p  = root.split('//');
-        p2 = p[1].split('/');
-        root = p[0] + '//' + p2[0] + rs[0];
-        location = rs[1];
-      }
-      else {
-        rs = ref.split('#');
-        if(rs[0] !== '') {
-          p2 = root.split('/');
-          p2 = p2.slice(0, p2.length - 1);
-          if(!rootTrimmed) {
-            root = '';
-            for (var k = 0; k < p2.length; k++) {
-              if(k > 0) { root += '/'; }
-              root += p2[k];
-            }
-          }
-          root += '/' + ref.split('#')[0];
-        }
-        location = rs[1];
-      }
-    }
+       if (ref.indexOf('http') === -1) {
+           if(ref.indexOf('#') >= 0) {
+             if(ref.indexOf('/') === 0) {
+               rs = ref.split('#');
+               p  = root.split('//');
+               p2 = p[1].split('/');
+               root = p[0] + '//' + p2[0] + rs[0];
+               location = rs[1];
+             }
+             else {
+               rs = ref.split('#');
+               if(rs[0] !== '') {
+                 p2 = root.split('/');
+                 p2 = p2.slice(0, p2.length - 1);
+                 if(!rootTrimmed) {
+                   root = '';
+                   for (var k = 0; k < p2.length; k++) {
+                     if(k > 0) { root += '/'; }
+                     root += p2[k];
+                   }
+                 }
+                 root += '/' + ref.split('#')[0];
+               }
+               location = rs[1];
+             }
+           }
+       }       
     if (ref.indexOf('http') === 0) {
       if(ref.indexOf('#') >= 0) {
         root = ref.split('#')[0];

**Comment by webron** [comment]
Shouldn't be an issue anymore.
