### ISSUE TITLE
Header values are not sent

### ISSUE THREAD

**Issue by lakmali** [swagger-api/swagger-ui#161]
Hi,

I downloaded swagger from [1] & configured the swagger UI as follows. 

window.swaggerUi = new SwaggerUi({
                discoveryUrl:"<%=discoveryUrl%>",
                dom_id:"swagger-ui-container",
        apiKeyName: "authorization",
        headers: { "authorization": "Bearer TVxmuXH4NU0wSHgHhd54UbSG10Ya"},
        supportHeaderParams: true,
        supportedSubmitMethods: ['get', 'post', 'put'],
                onComplete: function(swaggerApi, swaggerUi){
                 if(console) {
                        console.log("Loaded SwaggerUI")
                        console.log(swaggerApi);
                        console.log(swaggerUi);
                    }
                },
                onFailure: function(data) {
                 if(console) {
                        console.log("Unable to Load SwaggerUI");
                        console.log(data);
                    }
                },
                docExpansion: "none"
            });
            window.swaggerUi.load();
        });

My API needs OAuth headers to be sent to invoke that. But when I monitor through TCP mon I see that headers are set as follows.

Access-Control-Request-Headers: authorization

But header values are not sent, so my requests are failing due to OAuth credentials not being sent. 

When I invoke the API without swagger, the header contains the Authorization header as,

Authorization: Bearer TVxmuXH4NU0wSHgHhd54UbSG10Ya 

Am I missing anything?

Really appreciate any help on this.

[1]https://github.com/wordnik/swagger-core/tree/master/samples/no-server/src/main/html

Thanks,
Lakmali

**Comment by dotadam** [comment]
Hi,

I made the step into the JavaScript code and I realized that the header key need equal with the oauth2 name.

In "SwaggerConfig.cs" :
```
.EnableSwagger(..., c =>
{
    ...
    c.OAuth2("oauth2")
        .Description("OAuth2 Implicit Grant")
        .Flow("implicit")
        .AuthorizationUrl("/Token");
}
```

In injected JavaScript :
```
swaggerUi.api.clientAuthorizations.add("oauth2",
    new SwaggerClient.ApiKeyAuthorization("Authorization", authorization, "header"));
```

[Add OAuth2 Token form in swagger](https://github.com/dotadam/SwaggerOAuth2/blob/master/README.md)
