### ISSUE TITLE
Tag "title" causes Uncaught TypeError: Cannot assign to read only property 'help' of

### ISSUE THREAD

**Issue by bajtos** [swagger-api/swagger-ui#1615]
Steps to reproduce:

```
$ git clone git@github.com:strongloop/loopback-example-composite.git
$ cd loopback-example-composite
$ npm install
$ node .
```

And open `http://localhost:3000/explorer` in your browser.

The console shows the following error:

```
Uncaught TypeError: Cannot assign to read only property 'help' of 
swagger-ui.js:1717
```

The relevant code:

```js
// Bind tag help
if (!_.isFunction(operationGroup.help)) {
  operationGroup.help = _.bind(self.help, operationGroup);
}
```

I guess we need to add "title" to `reservedApiTags`?

**Comment by bajtos** [comment]
Ehm, let me add more meat to the report. The swagger contains a "title" definition (model). In the code above, `tag` is "title", `clientProperty` is "title" too, a thus `operationGroup = self[clientProperty]` sets the group to a string (the value of the swagger title metadata).

**Comment by bajtos** [comment]
@raymondfeng This is the bug you have mentioned yesterday.

**Comment by webron** [comment]
That's using which version of the ui?

**Comment by bajtos** [comment]
@webron we have our own fork for now, it's based on swagger-api/swagger-ui@59c1003 and swagger-api/swagger-js@dd8f847

**Comment by bajtos** [comment]
@webron I've submitted a pull request fixing the issue in swagger-client - see https://github.com/swagger-api/swagger-js/pull/581
