### ISSUE TITLE
Long is rendered inconsistently

### ISSUE THREAD

**Issue by mgttlinger** [swagger-api/swagger-ui#1618]
If I have a member in a schema of type long ("integer" "int64") it is rendered in the "Model" as "integer". If I use long in a path parameter however it is rendered as "long".

Is this a bug or is this the expected behaviour?

**Comment by webron** [comment]
Sounds like a bug.

**Comment by kulkarniankita** [comment]
@webron What is the expected behaviour in the above case?

**Comment by webron** [comment]
@kulkarniankita - in both cases it should be rendered as `long`.

**Comment by JaySWang** [comment]
Hi, any progress?

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if needed.
