### ISSUE TITLE
HTML ID namespace collision when using "/{arg}" and "{arg}/content" paths

### ISSUE THREAD

**Issue by rutsky** [swagger-api/swagger-ui#1620]
Open following schema in Swagger UI:

```
swagger: '2.0'
info:
  description: ...
  version: 1.0.0
  title: ...
paths:
  /{arg}/content:
    get:
      description: ...
      parameters:
        - in: path
          name: arg
          description: ...
          required: true
          type: string
      responses:
        '200':
          description: ...
  /{arg}:
    get:
      description: ...
      parameters:
        - in: path
          name: arg
          description: ...
          required: true
          type: string
      responses:
        '200':
          description: ...
```

Now click on `/{arg}` path:

![selection_015](https://cloud.githubusercontent.com/assets/46573/10044244/fb6932dc-6201-11e5-87c7-1053521533cc.png)

Instead of showing request details, `/{arg}/content` request will be hidden:

![selection_016](https://cloud.githubusercontent.com/assets/46573/10044255/119927f6-6202-11e5-831d-2aca305a7bc0.png)

This is because `/{arg}/content` node has `id="default_get_arg_content"` and `/{arg}` subnode with content has same `id="default_get_arg_content"`, so instead of toggling `/{arg}` content subnode, whole `/{arg}/content` node is toggled.

Note that using same id on multiple tags is not valid in HTML, so behaviour may be different in different browsers, I checked in Firefox.

**Comment by rutsky** [comment]
Can anybody suggest proper way to solve this issue?

Currently I locally patched sources to use double underscores in content identifier `__content`, which solves issue with my schema.
I think proper solution would be to "escape" whole `nickname` (and other identifiers) string before adding it to `id`, e.g. by taking base64 or some hash of it, that is guaranteed to have characters from limited set.

I can try to add add `btoa` dependency and base64-ify identifiers that are used as `id` part, if you this this is a proper solution.

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
