### ISSUE TITLE
Hiding the 200 'response class'?

### ISSUE THREAD

**Issue by Luthien-in-edhil** [swagger-api/swagger-ui#1621]
Since we're having around 200 API endpoints that all return the same response class, I was asked to remove this from the UI. 
I also looked if this was possible via Swagger-core / Springfox, for instance using the @ApiOperation / hidden or -response property (e.g. returning java.lang.Void.class), or specifying a .globalResponseMessage for HTTP 200 in the SwaggerConfiguration / Docket (=> .responseModel(null) ...) - but none of that seems to have this effect. 

Does anyone know if there's a way to achieve this?

thanks in advance!

**Comment by webron** [comment]
There's no way to achieve this.
