### ISSUE TITLE
Markdown issues

### ISSUE THREAD

**Issue by acappiello** [swagger-api/swagger-ui#1622]
I am running into two separate issues related to markdown rendering. I am using the latest sources, currently commit 8bc259558ba7774f814d7426c7794f27c144d2be.

The first is related to #1087, where markdown code blocks with xml have the tags converted to lower case. However, no solution is reached there. As is mentioned there, this does not happen in the Swagger Editor and is not an issue in marked.
For example, I have the following markdown:

``` markdown
    <TestResponse xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
        <Message>It worked!</Message>
        <Success>true</Success>
    </TestResponse>
```

Inspecting the generated html in the Swagger Editor, it becomes

``` html
<pre><code>&lt;TestResponse xmlns:i="http://www.w3.org/2001/XMLSchema-instance"&gt;
  &lt;Message&gt;It worked!&lt;/Message&gt;
  &lt;Success&gt;true&lt;/Success&gt;
&lt;/TestResponse&gt;
</code></pre>
```

In swagger-ui, it becomes

``` html
<pre><code class="xml"><span class="tag"><span class="tag">&lt;<span class="title"><span class="title">testresponse</span></span> <span class="attribute"><span class="attribute">xmlns:i</span></span>=<span class="value"><span class="value">"http://www.w3.org/2001/XMLSchema-instance"</span></span>&gt;</span></span>
  <span class="tag"><span class="tag">&lt;<span class="title"><span class="title">message</span></span>&gt;</span></span>It worked!<span class="tag"><span class="tag">&lt;/<span class="title"><span class="title">message</span></span>&gt;</span></span>
  <span class="tag"><span class="tag">&lt;<span class="title"><span class="title">success</span></span>&gt;</span></span>true<span class="tag"><span class="tag">&lt;/<span class="title"><span class="title">success</span></span>&gt;</span></span>
<span class="tag"><span class="tag">&lt;/<span class="title"><span class="title">testresponse</span></span>&gt;</span></span>
</code></pre>
```

~~So, I'm thinking tags are being converted to lower-case during or close to whenever this extra transformation is happening. However, I'm having trouble finding where this is done.~~

My second issue comes from loading multiple SwaggerUI instances on the same page. I see several past issues that were resolved, but my issue is specific to markdown rendering. I am loading 4 versions of my API with separate dom_id values. It seems that each of the 4 loads causes markdown rendering to occur everywhere, i.e. the first one I load is processed 4 times, the second 3, etc. and the last one displays properly. The only issue from this that I've noticed is that lists are not rendered properly, with lots of extra whitespace.
For example, the markdown

``` markdown
* Success = true, Message = "foo"
* Success = false, Message = "bar"
```

becomes

``` html
<ul><p></p><p></p><p></p>
<p></p><p></p><p></p><li>Success = true, Message = “foo”</li><p></p><p></p><p></p>
<p></p><p></p><p></p><li>Success = false, Message = “bar”</li><p></p><p></p><p></p>
<p></p><p></p><p></p>
</ul>
```

Thanks for any help on these issues.

**Comment by acappiello** [comment]
I've fixed the second issue in acappiello/swagger-ui@941687c39478a21119405d05dbf1a8be9ced3876.

Still not sure what's going on with the first issue though.

**Comment by acappiello** [comment]
The XML issue is due to how the markdown is inserted into the page [here](https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/OperationView.js#L181) and then the markdown is handled later. After this line executes, `$(this.el).html()` in the console shows the altered XML, but `Handlebars.templates.operation(this.model)` in the console shows it correctly. This is also likely the cause of #1491.

**Comment by webron** [comment]
This should no longer be an issue with 3.0. Please reopen if needed.
