### ISSUE TITLE
How to call Basic Authentication protected web services using Swagger UI

### ISSUE THREAD

**Issue by rmahajan1234** [swagger-api/swagger-ui#1623]
Hi

The web services in my project are protected using Spring Security which needs username and password. How do we configure Swagger so when we click on 'TryItOut', the curl command incorprates -u username/password in it?

Thanks
Ram

**Comment by rmahajan1234** [comment]
I saw a note on adding Basic Auth in header at
https://github.com/swagger-api/swagger-ui#header-parameters

Is there any example I can take a look ?

Thanks

**Comment by rmahajan1234** [comment]
Hi

I added following section in dist/index.html. I am using Spring Securty for Basic Authntication. It did not work. Please take a look.


$('#input_user, #input_pass').change(function() {
    var username = $('#input_user')[0].value;
    var password = $('#input_pass')[0].value;

    if(username && username.trim() != "" && password && password.trim() != "") {
        var auth = "Basic " + btoa($('#input_user')[0].value + ":" + $('#input_pass')[0].value);
        window.authorizations.add("key", new ApiKeyAuthorization("Authorization", auth, "header"));
    } else {
        window.authorizations.remove("key");
    }
});







And in the HTML





<form id='api_selector'>
    <div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text"/></div>
    <div class='input'><input placeholder="user" id="input_user" name="user" type="text" size="10"/></div> 
    <div class='input'><input placeholder="pass" id="input_pass" name="pass" type="password" size="10"/></div>
</form>

**Comment by rmahajan1234** [comment]
HTML code looks like this, It did not get attached in previous post:

<form id='api_selector'>
    <div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text"/></div>
    <div class='input'><input placeholder="user" id="input_user" name="user" type="text" size="10"/></div> 
    <div class='input'><input placeholder="pass" id="input_pass" name="pass" type="password" size="10"/></div>
</form>


Thanks

**Comment by rmahajan1234** [comment]
<div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text"/></div>
    <div class='input'><input placeholder="user" id="input_user" name="user" type="text" size="10"/></div> 
    <div class='input'><input placeholder="pass" id="input_pass" name="pass" type="password" size="10"/></div>

**Comment by rmahajan1234** [comment]
It is all working now, Thanks

**Comment by uclesn** [comment]
How did you get this to work? In the latest version of Swagger I still cannot figure it out. I modified the defgault addApiKeyAuthorization funciton in the index.html as follows but this only works when you click "Explorer" to get the actual specification. Once I have it, I try to use "Try It Out" button but the Authorization headers are never sent from there. I have not been able to find a definitive answer as to why it only works in one and not the other. Any thoughts?

`function addApiKeyAuthorization(){
        var key = $('#input_apiKey')[0].value;
        if(key && key.trim() != "") {
            var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", key, "header");
            window.swaggerUi.api.clientAuthorizations.add("key", apiKeyAuth);
            log("added key " + key);
        }
      }`

**Comment by webron** [comment]
Take a look at #1922

**Comment by deepakSK** [comment]
Hi ron ,i got curl -k -d "grant_type=password&username=xxx&password=xxx-345kf" \
        -H "Authorization: Basic aWZia3FGQm5iaVg4STJ5VFVua0xZcTJKSXFZYTphZmdTemJRT0lRTkczY015VmJzdl9ibFJUeDBh" \
         https://xyz server.compute.amazonaws.com:8243/token . How do i transform this to ajax/Jquery request to get token

**Comment by deepakSK** [comment]
Hi ron ,i got curl -k -d "grant_type=password&username=xxx&password=xxx-345kf"
        -H "Authorization: Basic aWZia3FGQm5iaVg4STJ5VFVua0xZcTJKSXFZYTphZmdTemJRT0lRTkczY015VmJzdl9ibFJUeDBh"
         https://xyz server.compute.amazonaws.com:8243/token . How do i transform this to ajax/Jquery request to get token.Please send me that format @ deepak.ou2003@gmail.com

**Comment by pavan-eidiko** [comment]
Hi,
i am new to swagger , trying to find an example on how to add basic authentication to swagger and also i am not much familiar with javascript. it is good if i get a complete example.
swagger version i am using is swagger2.0
Thanks in advance
