### ISSUE TITLE
can't read the api-docs from swagger-ui

### ISSUE THREAD

**Issue by ChrisNotes** [swagger-api/swagger-ui#1624]
I did integrate the swagger 1.2 to my project, and when I am using swagger-ui 2.1.1 version to show the page , it always tell me that "500 : http://localhost:8080/Certificate/rest/sw/api-docs", However If I call the "http://localhost:8080/Certificate/rest/sw/api-docs" in the browser independent, it works, could return json file. Just want to know how to make the swagger-ui 2.1.1 works for swagger 1.2 spec.Thanks

**Comment by webron** [comment]
It works with it, yes. Which library produces your api-docs? This could be an issue with conent-type management.

**Comment by ChrisNotes** [comment]
The jar I am using is swagger-core2.10-1.30 , swagger-jaxrs2.10-1.30,swagger-annotation2.10-1.30, Do I need to change the jar ? or is there any other way to change the content-type for the api-docs.Thanks.

**Comment by webron** [comment]
@ChrisNotes - sorry for the delayed reply.

Looks like you're using a *really* old version of swagger-core (over two years old). Would you mind upgrading to the latest? I hope https://github.com/swagger-api/swagger-core/wiki/1.3--1.5-Migration would help.
