### ISSUE TITLE
missing method to translate raw string in code

### ISSUE THREAD

**Issue by rutsky** [swagger-api/swagger-ui#1625]
Current simple translation system translates html entities that have `data-sw-translate` attribute.

Sometimes it is desired to translate raw string, for example when building error message string:

```
var errors = [];
...
try {
  JSON.parse(value);
} catch (error) {
  var errorMessage = SwaggerTranslator.tr('Failed to parse JSON: ') + error.message;
  errors.push(errorMessage);
}
...
errors.push(SwaggerTranslator.tr('Schema validation failed: ') + error);
...
Handlebars.templates.parameter_validation_status({errorMessage: errors.join('\n')})
```

It is possible to wrap all strings in html entities, render them, and call `window.SwaggerTranslator.translate();`, but this is very tiresome.
(However, having all translatable strings as entities potentially allow to switch language without page reloading, but I don't think this is need to be considered right now.)

It's easy to add such `SwaggerTranslator.tr` method in current implementation of translation system, but currently `SwaggerTranslator` is optionally enabled, so explicit check or helper function required:

```
window.SwaggerUi.tr = function tr(string) {
  if (window.SwaggerTranslator) {
    return window.SwaggerTranslator.tr(string);
  } else {
    return string;
  }
}
```

I would like to implement method to translate raw strings, which solution I should choose?
Add helper function or make SwaggerTranslator required?

**Comment by rutsky** [comment]
Here is an example of not translated raw string added dynamically:
https://github.com/swagger-api/swagger-ui/blob/6d4bc72a64b02efabe931aee2fa4e53b4b400217/src/main/javascript/view/SignatureView.js#L23

**Comment by webron** [comment]
The new version of the UI does not support translations yet. Hopefully when it's reintroduced, this will no longer be an issue.
