### ISSUE TITLE
Cannot add AuthHeaders

### ISSUE THREAD

**Issue by ed0906** [swagger-api/swagger-ui#1627]
Using the following:

    var token = 'xxx';
    var swaggerUi = new SwaggerUi({
      url: "http://" + location.host + "/rest/swagger",
      dom_id: "swagger-ui-container",
      supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
      onComplete: function (swaggerApi, swaggerUi) {
        $('pre code').each(function (i, e) {
          hljs.highlightBlock(e)
        });
      },
      onFailure: function (data) {
        log("Unable to Load SwaggerUI");
      },
      docExpansion: "none",
      apisSorter: "alpha",
      showRequestHeaders: false
    });

    var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("AuthToken", token, "header");
    swaggerUi.api.clientAuthorizations.add("AuthToken", apiKeyAuth);

    swaggerUi.load();

I was following the read me and the above throws an exception as swaggerUi.api is undefined

**Comment by xFragger** [comment]
swaggerUi.api is defined, after running load(), you have to add it later, i guess

```
load: function(){
    // (....)
    this.api = new SwaggerClient(this.options);
  },
```

**Comment by ed0906** [comment]
Yep I solved it by  by moving the `swaggerUi.load();` above the `swaggerUi.api.clientAuthorizations.add("AuthToken", apiKeyAuth);`
