### ISSUE TITLE
A question about responseModel.

### ISSUE THREAD

**Issue by billy3321** [swagger-api/swagger-ui#1628]
Hello, I have a question about responseModel.

My swagger url is:

http://digital.jrf.org.tw/api

My json for swagger ui is at here:

http://digital.jrf.org.tw/apidocs/api-docs.json
http://digital.jrf.org.tw/apidocs/api/articles.json
http://digital.jrf.org.tw/apidocs/api/magazines.json
http://digital.jrf.org.tw/apidocs/api/records.json

And I found, the swagger ui will use responseModel to create request, like this:

http://digital.jrf.org.tw/apidocs/APIArticleIndex
http://digital.jrf.org.tw/apidocs/APIArticleShow
http://digital.jrf.org.tw/apidocs/APIMagazineIndex
http://digital.jrf.org.tw/apidocs/APIMagazineShow
http://digital.jrf.org.tw/apidocs/APIRecordIndex
http://digital.jrf.org.tw/apidocs/APIRecordShow

and each one it will request for 7 times.

I want to stop the request, does there has good way to stop it?

**Comment by webron** [comment]
The best way is to upgrade to the latest version of the spec and the ui.
