### ISSUE TITLE
Error 500: Something bad happened

### ISSUE THREAD

**Issue by gshaxor** [swagger-api/swagger-ui#1629]
I cant export the swagger script...

![image](https://cloud.githubusercontent.com/assets/1691623/10132641/de57d360-65ad-11e5-9668-ade1392785e4.png)

In the editor:
![image](https://cloud.githubusercontent.com/assets/1691623/10132651/f7d88884-65ad-11e5-995f-1f947ee7c2a0.png)

How i can see the problem in detail?

Edit:

In... http://online.swagger.io/validator/debug?url=... i get this error...

[{"level":"error","domain":"validation","keyword":"type","message":"instance type (string) does not match any allowed primitive type (allowed: [\"object\"])","schema":{"loadingURI":"#","pointer":""},"instance":{"pointer":""}}]

**Comment by webron** [comment]
Can you share the JSON itself?

**Comment by gshaxor** [comment]
This the JSON https://www.dropbox.com/s/dun0xtvlppxe7zp/swagger.json?dl=0

**Comment by webron** [comment]
Embarrassing, but this fell off my radar. Closing the ticket as I assume it's no longer relevant but tell me otherwise.
