### ISSUE TITLE
Absolute $ref(s) definitions

### ISSUE THREAD

**Issue by islemus** [swagger-api/swagger-ui#1636]
Hi guys,

When opening a json spec using swagger-ui absolute uri definitions cannot be loaded. after looking to the network tab, it seems swagger-ui is trying to get the definition using a relative path to the location of the spec file 

e.g. http://localhost:8083/specs/http://localhost:8083/definitions/error.json will give a 404 (Not Found)

Is there a parameter to supply that i'm missing ?

**Comment by webron** [comment]
Which version of the ui do you use?
Can you share your definition so the use case is clearer?

**Comment by islemus** [comment]
I'm using swagger-ui v2.1.3

below my use case

I'm hosting both swagger-editor and swagger-ui. 
http://vm-linuxapp-75:8080/swagger/#/ for the swagger-editor and 
http://vm-linuxapp-75:8080/swagger-ui/ for swagger-ui

I have the spec file below hosted at http://vm-linuxapp-75:8080/swagger/specs/occupation.json (inside the swagger-editor). The file references definitions located in http://vm-linuxapp-75:8080/swagger/definitions/ using an absolute url.

Everything works fine in swagger-editor (the preview panel display all the definitions referenced). However, in swagger-ui when i try to load http://vm-linuxapp-75:8080/swagger/specs/occupation.json the json file is successfully loaded, except the definitions are not. It seems that swagger-ui is considering all their url(s) as relative to the spec folder of the spec file. e.g. http://vm-linuxapp-75:8080/swagger/specs/http://vm-linuxapp-75:8080/swagger/definitions/error.json 

Here is a screen shot of swagger-ui 

![capture](https://cloud.githubusercontent.com/assets/12645698/10281409/48e64c9a-6b42-11e5-9a9f-6f7e1a77ce61.PNG)

Here is the spec file

``` json
{
    "swagger": "2.0",
    "info": {
        "title": "Occupations API",
        "description": "This API manages Occupations",
        "version": "1.0.0"
    },
    "host": "localhost:8080",
    "schemes": [
        "http",
        "https"
    ],
    "basePath": "/",
    "produces": [
        "application/json",
        "application/xml"
    ],
    "paths": {
        "/occupations": {
            "get": {
                "tags": [
                    "Occupations"
                ],
                "summary": "Retrieves the list of Occupations",
                "description": "",
                "produces": [
                    "application/json",
                    "application/xml"
                ],
                "responses": {
                    "200": {
                        "description": "An array of Occupations",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/occupation.json"
                            }
                        }
                    },
                    "default": {
                        "description": "Unexpected error",
                        "schema": {
                            "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/error.json"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Occupations"
                ],
                "summary": "Adds a new Occupation",
                "description": "",
                "consumes": [
                    "application/json",
                    "application/xml"
                ],
                "produces": [
                    "application/json",
                    "application/xml"
                ],
                "parameters": [
                    {
                        "name": "occupation",
                        "in": "body",
                        "description": "Occupatione object that needs to be added",
                        "required": true,
                        "schema": {
                            "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/occupation.json"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "M00-01 - If the record was created",
                        "schema": {
                            "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/error.json"
                        }
                    },
                    "500": {
                        "description": "M00-06 - Other cases",
                        "schema": {
                            "$ref": "http://vm-linuxapp-75:8080/swagger/definitions/error.json"
                        }
                    }
                }
            }
        }
    }
}
```
And one definition as an example (error.json)

``` json
{
    "properties": {
        "messageCode": {
            "type": "string"
        },
        "messageType": {
            "type": "string",
			 "enum": [ "Success", "Error", "Warning", "Info"]
        }
    }
}
```

**Comment by islemus** [comment]
@webron,  any updates ? am i missing something ?

**Comment by webron** [comment]
Yup, this looks like a resolution bug. As a workaround for now, if they're all on the same server, you can opt for a relative path.

**Comment by fehguy** [comment]
I'd be amazed if this really is happening on the current branch. I'll look and reply back shortly

**Comment by fehguy** [comment]
please try out the latest master, https://github.com/swagger-api/swagger-js/pull/588 should resolve it.  You can also test from http://petstore.swagger.io

**Comment by islemus** [comment]
Yep  swagger-api/swagger-js#588 resolved the issue, thanks !

**Comment by fehguy** [comment]
great, thanks
