### ISSUE TITLE
$ref not working in with Second Child JSON file

### ISSUE THREAD

**Issue by JayachandranSivaraman** [swagger-api/swagger-ui#1639]
I am working on splitting the json file into multiple parts. $ref is not working on the third json file.
I have a root file swagger.json with the following contents

```js
{  
   "swagger":"2.0",
   "host":"localhost",
   "info":{  
      "title":"BizTalk360 API",
      "version":"7.9.9998.3106"
   },
   "paths":{  
      "/BizTalk360/Services.REST/AdminService.svc/GetSystemGlobalProperties":{  
         "$ref":"http://localhost/api/AdminServices.json#/paths/GetSystemProperties"
      },
      "/BizTalk360/Services.REST/AlertService.svc/GetConfiguredSQLServerNames":{  
         "$ref":"http://localhost/api/AlertServices.json#/GetServerNames"
      }
   }
}
```

As my reference in the swagger.json i have the following contents in AdminServices.json

```js
{  
   "paths":{  
      "GetSystemProperties":{  
         "get":{  
            "summary":"GetSystemGlobalProperties",
            "description":"This API retrieves the system global properties.",
            "produces":[  
               "application/json"
            ],
            "consumes":[  
               "application/json"
            ],
            "tags":[  
               "AdminService"
            ],
            "responses":{  
               "200":{  
                  "description":"Success",
                  "schema":{  
                     "$ref":"http://localhost/api/AdminServices.json#/definitions/BizTalkAdminService-GetSystemProperties"
                  }
               },
               "x-200-errors":{  
                  "description":"Errors",
                  "schema":{  
                     "$ref":"#/definitions/errors"
                  }
               }
            }
         }
      }
   },
   "definitions":{  
      "BizTalkAdminService-GetSystemProperties":{  
         "example":{  
            "success":true,
            "globalProperties":[  
               {  
                  "PropKey":"SYSTEM_TIME_ZONE_ID",
                  "PropValue":"India Standard Time"
               },
               {  
                  "PropKey":"SYSTEM_DATE_TIME_FORMAT",
                  "PropValue":"MM-DD-YYYY HH:mm:ss"
               }
            ]
         },
         "required":[  
            "success"
         ],
         "properties":{  
            "success":{  
               "type":"boolean",
               "description":"<p style=\"color:blue\">Specifies whether the Service has returned the response successfully or not</p>"
            },
            "globalProperties":{  
               "type":"array",
               "items":{  
                  "required":[  
                     "PropKey",
                     "PropValue"
                  ],
                  "properties":{  
                     "PropKey":{  
                        "type":"string",
                        "description":"<p style=\"color:blue\">Specifies the Property key of the global properties</p>"
                     },
                     "PropValue":{  
                        "type":"string",
                        "description":"<p style=\"color:blue\">Specifies the property value of the global properties</p>"
                     }
                  }
               }
            }
         }
      }
   }
}
```

This scenario is working as expected and all the reference is working as expected. but for my second reference file (AlertServices.Json) 

i have the following content and the inner reference (commented) is not working can you please assist me on the same.

```js
{  
   "GetConfiguredSQLServerNames":{  
      "get":{  
         "summary":"GetConfiguredSQLServerNames",
         "description":"This API retrieves the SQL server names which are configured for monitoring in the environment.",
         "parameters":[  
            {  
               "name":"environmentId",
               "in":"query",
               "description":"BizTalk360 environment targeted by this call, to get a list of all available environments and their ids call the GetEnvironments API, Environment ID should be in the format of GUID. For more details about environment id  <a href=\"#!/AdminService/get_BizTalk360_Services_REST_AdminService_svc_GetAllConfiguredEnvironments\" data-innerlink=\"true\" class=\"toggleOperation\">Get All Configured Environments</a>",
               "required":true,
               "type":"string"
            }
         ],
         "produces":[  
            "application/json"
         ],
         "consumes":[  
            "application/json"
         ],
         "tags":[  
            "AlertService"
         ],
         "responses":{  
            "200":{  
               "description":"Success",
               "schema":{  
                  "$ref":"http://localhost/api/AlertServices.json#/AlertService-GetConfiguredSQLServerNames" ---> This reference is not working
               }
            },
            "x-200-errors":{  
               "description":"Errors",
               "schema":{  
                  "$ref":"#/definitions/errors"
               }
            }
         }
      }
   },
   "AlertService-GetConfiguredSQLServerNames":{  
      "required":[  
         "success"
      ],
      "example":{  
         "success":true,
         "serverNames":[  
            "BT360"
         ]
      },
      "properties":{  
         "success":{  
            "type":"boolean",
            "description":"<p style=\"color:blue\">Specifies whether the Service has returned the SQL server names successfully or not</p>"
         },
         "serverNames":{  
            "type":"array",
            "description":"<p style=\"color:blue\">Specifies the SQL server names configured for monitoring in an environment.</p>",
            "items":{  
               "type":"string"
            }
         }
      }
   }
}
```

**Comment by dolmen** [comment]
Please reformat your issue using Markdown. The JSON is not human readable in the current form.

**Comment by webron** [comment]
@dolmen - FTFY ;)

**Comment by webron** [comment]
@JayachandranSivaraman - when you say that it's not working, what do you mean exactly? What do you actually experience when you try?

Also, looking at the sample, it looks like you're using the full URL to refer to itself. Is there any reason for that? Can you try referencing the schema directly?

**Comment by JayachandranSivaraman** [comment]
@Ron-  I have 3 Json files. One is the root swagger.json file and the other 2 is Child files.
I am using "$ref":"#/Parameters/parametername" reference in the 2 child files. For the First file all the parameter reference are working fine. For the Second file the parameter reference is not working. The UI is not rendered if the second file has the parameter reference. I can see the following Message in the UI "Finished Loading Resource Information. Rendering Swagger UI...".


The root Json Files has the following content.

{  
   "swagger":"2.0",
   "host":"localhost",
   "info":{  
      "title":"BizTalk360 API",
      "version":"7.9.9998.3106"
   },
   "paths":{  
      "/BizTalk360/Services.REST/AdminService.svc/GetSystemGlobalProperties":{  
         "$ref":"http://localhost/api/AdminServices.json#/paths/GetSystemProperties"  ---> Refered to the First Child (AdminServices.json File)
      },
      "/BizTalk360/Services.REST/AlertService.svc/GetConfiguredSQLServerNames":{  
         "$ref":"http://localhost/api/AlertServices.json#/GetServerNames" --->Refered to the Second Child(AlertServices.jsonFile)
      }
   }
}

The following is my First Child file(AdminServices.json File). Parameter reference is working fine.

{  
   "paths":{  
      "GetSystemProperties":{  
         "get":{  
            "summary":"GetSystemGlobalProperties",
            "description":"This API retrieves the system global properties.",
"parameters":[
{
"$ref":"#/parameters/environmentId"--> the root Json has this parameter and this reference is working as expected
}

],
            "produces":[  
               "application/json"
            ],
            "consumes":[  
               "application/json"
            ],
            "tags":[  
               "AdminService"
            ],
            "responses":{  
               "200":{  
                  "description":"Success",
                  "schema":{  
                     "$ref":"http://localhost/api/AdminServices.json#/definitions/BizTalkAdminService-GetSystemProperties"--> Reference to the same Json file definition is working as expected
                  }
               },
               "x-200-errors":{  
                  "description":"Errors",
                  "schema":{  
                     "$ref":"#/definitions/errors"
                  }
               }
            }
         }
      }
   },
   "definitions":{  
      "BizTalkAdminService-GetSystemProperties":{  
         "example":{  
            "success":true,
            "globalProperties":[  
               {  
                  "PropKey":"SYSTEM_TIME_ZONE_ID",
                  "PropValue":"India Standard Time"
               },
               {  
                  "PropKey":"SYSTEM_DATE_TIME_FORMAT",
                  "PropValue":"MM-DD-YYYY HH:mm:ss"
               }
            ]
         },
         "required":[  
            "success"
         ],
         "properties":{  
            "success":{  
               "type":"boolean",
               "description":"<p style=\"color:blue\">Specifies whether the Service has returned the response successfully or not</p>"
            },
            "globalProperties":{  
               "type":"array",
               "items":{  
                  "required":[  
                     "PropKey",
                     "PropValue"
                  ],
                  "properties":{  
                     "PropKey":{  
                        "type":"string",
                        "description":"<p style=\"color:blue\">Specifies the Property key of the global properties</p>"
                     },
                     "PropValue":{  
                        "type":"string",
                        "description":"<p style=\"color:blue\">Specifies the property value of the global properties</p>"
                     }
                  }
               }
            }
         }
      }
   }
}

Following is second Child Json(AlertService.json). For this file Parameter reference and Schema reference is not working as expected.
{  
   "GetConfiguredSQLServerNames":{  
      "get":{  
         "summary":"GetConfiguredSQLServerNames",
         "description":"This API retrieves the SQL server names which are configured for monitoring in the environment.",
         "parameters":[  
            {  
             "$ref":"#/parameteres/environmentID"--> the root Json has the parameter environment ID and it is not working as expected
            }
         ],
         "produces":[  
            "application/json"
         ],
         "consumes":[  
            "application/json"
         ],
         "tags":[  
            "AlertService"
         ],
         "responses":{  
            "200":{  
               "description":"Success",
               "schema":{  
                  "$ref":"http://localhost/api/AlertServices.json#/AlertService-GetConfiguredSQLServerNames" ---> This reference to the same Json file defintion is not working
               }
            },
            "x-200-errors":{  
               "description":"Errors",
               "schema":{  
                  "$ref":"#/definitions/errors"
               }
            }
         }
      }
   },
   "AlertService-GetConfiguredSQLServerNames":{  
      "required":[  
         "success"
      ],
      "example":{  
         "success":true,
         "serverNames":[  
            "BT360"
         ]
      },
      "properties":{  
         "success":{  
            "type":"boolean",
            "description":"<p style=\"color:blue\">Specifies whether the Service has returned the SQL server names successfully or not</p>"
         },
         "serverNames":{  
            "type":"array",
            "description":"<p style=\"color:blue\">Specifies the SQL server names configured for monitoring in an environment.</p>",
            "items":{  
               "type":"string"
            }
         }
      }
   }
}

**Comment by dolmen** [comment]
@JayachandranSivaraman Please preview your posts and use Markdown formatting!

**Comment by webron** [comment]
@JayachandranSivaraman - can you check the browser's web console and see what errors you're getting?

**Comment by JayachandranSivaraman** [comment]
@Ron- I followed a different way for my requirement.

**Comment by JayachandranSivaraman** [comment]
@Ron- I have sorted out my problem and its all working fine for my
requirement

On Fri, Oct 9, 2015 at 10:37 AM, Jayachandran S <jayachandranaug29@gmail.com
> wrote:

> @Ron- I followed a different way for my requirement.
>
