### ISSUE TITLE
Custom ParameterBindingAttribute causes methods to be ignored

### ISSUE THREAD

**Issue by raaga123** [swagger-api/swagger-ui#1641]
Hi,

Our application needs to use a custom variation of the FromUri parameter attribute, which we are calling FromDecodedUri. Is there a way to notify Swagger/Swashbuckle of the existence of this attribute? Right now, any method whose parameters are decorated with this attribute are simply ignored when the API doc is generated.

Thanks,
Lyn

**Comment by webron** [comment]
@raaga123 - Can you explain a bit further what you mean by the FromUri parameter or FromDecodedUri? Coudl this be more of a Swashbuckle issue than swagger-ui?

**Comment by raaga123** [comment]
FromUri is a value of the ApiParameterSource enumeration, which is defined in System.Web.Http.Description. Swagger copes with parameters annotated with [FromUri] just fine.

One of our developers created a new attribute of type System.Web.Http.ParameterBindingAttribute. This attribute is called FromDecodedUri, and is intended to work like FromUri except that the parameter is passed through a filter to remove special characters.

The new parameter annotation [FromDecodedUri] behaves as expected in the program, but it seems to confuse Swagger-UI. Any method with a parameter annotated with this attribute simply does not appear in the json output.

**Comment by webron** [comment]
@raaga123 - thanks for the clarification. So this indeed sounds like an issue with Swashbuckle, as it's its responsibility to generate the proper JSON output. swagger-ui simply renders that output. So, if you find that the json generated does not include it, can you please open the issue on Swashbuckle instead?

**Comment by raaga123** [comment]
OK, thanks, will do. (I'm still relatively new to this, so still figuring out which piece is responsible for what. ;) )

**Comment by webron** [comment]
@raaga123 - no worries, there are many working pieces at play. I'm sure the Swashbuckle author will help you out.
