### ISSUE TITLE
basePath needs to be relative to Jersey Context?

### ISSUE THREAD

**Issue by gboysko** [swagger-api/swagger-ui#1642]
I am writing a Jersey-based API and want to use swagger-ui to document and test it. In my web.xml, I need to specify swagger.api.basepath to include a reference to the Context name. Is that correct? If so, that seems flawed as I can deploy the same WAR using any arbitrary Context, but will only work when a specific one is used.

Am I missing something?

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-core#1466
