### ISSUE TITLE
Oauth scheme and scope selection

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-ui#1644]
There are several issues dealing with Oauth scheme and scope selection:
- if multiple schemes are defined in securityDefinitions (for instance "implicit1", "implicit2" and "accessCode"), it is not possible to choose which scheme to use for the oauth dance. The scheme used by swagger ui is undefined (see #1410)
- it should not be possible to choose scopes defined in different schemes
- "password" and "application" flows scopes appear in the selectable scopes

**Comment by frol** [comment]
I think, the only missing part it this the Password Flow support. Everything else described here seems to be already addressed in https://github.com/swagger-api/swagger-ui/pull/1825

**Comment by webron** [comment]
@cbornet you being an active member, I'm not going to just close the ticket. Do you feel this is still an issue? Even with 3.0?

**Comment by cbornet** [comment]
@webron I'll check ASAP but it's probably fixed.

**Comment by webron** [comment]
@cbornet? :)

**Comment by cbornet** [comment]
@webron this is fixed (at least on 3.0). Great job and sorry for the delay 😅
