### ISSUE TITLE
How to get rid of 'api' word from web service URL ?

### ISSUE THREAD

**Issue by rmahajan1234** [swagger-api/swagger-ui#1653]
Hi 

I would like to get rid of word 'api' from web service URLs but I am unable to . I tried to remove it from web.xml but found that either UI won't come up or unable to make a call to the web service method. Here is my configuration:

URL to access index.html = https://myhost.com:8443/MySwaggerCxf/dist/index.html
URL to access swagger.json: https://myhost.com:8443/MySwaggerCxf/api/v1.0/swagger.json
URL to access web service: https://myhost.com:8443/MySwaggerCxf/api/v1.0/pet/12.xml

```xml
web.xml
  <servlet-mapping>
    <servlet-name>CXFServiceServlet</servlet-name>
    <url-pattern>/api/*</url-pattern>    
  </servlet-mapping>

    <init-param>
      <param-name>swagger.api.basepath</param-name>
      <param-value>/api</param-value>      
    </init-param>
```

beans.xml

```xml
  <bean id="swaggerConfig" class="io.swagger.jaxrs.config.BeanConfig">   
    <property name="resourcePackage" value="com.abc.xyz"/>    
    <property name="version" value="1.0.0"/>
    <property name="host" value="myhost:8443"/>            
    <property name="basePath" value="/MySwaggerCxf/api/v1.0"/>    
    <property name="title" value="My Swagger Cxf"/>
    <property name="description" value="This application will list all web services available."/>
    <property name="scan" value="true"/>    
  </bean>
```

Java interface file

```java
@Path("/pet")
@Api(value = "/PetService")
@Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON, MediaType.APPLICATION_FORM_URLENCODED})
@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
public interface PetService {
		
	@GET
	@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
	@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
	@Path("/{pitid}.xml")
	@ApiOperation(value = "/{petid}", notes = "This method will get a Pet by id",  response = Pet.class)	
	public Response getPetXmlById(@PathParam("petid") String id);
```
	
  Thanks
Ram

**Comment by rmahajan1234** [comment]
Trying to paste code here again:

URL to access index.html = https://myhost.com:8443/MySwaggerCxf/dist/index.html
URL to access swagger.json: https://myhost.com:8443/MySwaggerCxf/api/v1.0/swagger.json
URL to access web service: https://myhost.com:8443/MySwaggerCxf/api/v1.0/pet/12.xml 
-----------------------------------------------
web.xml
  <servlet-mapping>
    <servlet-name>CXFServiceServlet</servlet-name>
    <url-pattern>/api/*</url-pattern>    
  </servlet-mapping>

    <init-param>
      <param-name>swagger.api.basepath</param-name>
      <param-value>/api</param-value>      
    </init-param>
----------------------------------------------
beans.xml

  <bean id="swaggerConfig" class="io.swagger.jaxrs.config.BeanConfig">   
    <property name="resourcePackage" value="com.abc.xyz"/>    
    <property name="version" value="1.0.0"/>
    <property name="host" value="myhost:8443"/>            
    <property name="basePath" value="/MySwaggerCxf/api/v1.0"/>    
    <property name="title" value="My Swagger Cxf"/>
    <property name="description" value="This application will list all web services available."/>
    <property name="scan" value="true"/>    
  </bean>
--------------------------------------------------
Java interface file

@Path("/pet")
@Api(value = "/PetService")
@Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON, MediaType.APPLICATION_FORM_URLENCODED})
@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
public interface PetService {
		
	@GET
	@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
	@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
	@Path("/{pitid}.xml")
	@ApiOperation(value = "/{petid}", notes = "This method will get a Pet by id",  response = Pet.class)	
	public Response getPetXmlById(@PathParam("petid") String id);

**Comment by rmahajan1234** [comment]
beans.xml:
  <bean id="swaggerConfig" class="io.swagger.jaxrs.config.BeanConfig">   
    <property name="resourcePackage" value="com.abc.xyz"/>    
    <property name="version" value="1.0.0"/>
    <property name="host" value="myhost:8443"/>            
    <property name="basePath" value="/MySwaggerCxf/api/v1.0"/>    
    <property name="title" value="My Swagger Cxf"/>
    <property name="description" value="This application will list all web services available."/>
    <property name="scan" value="true"/>    
  </bean>

**Comment by rmahajan1234** [comment]
beans.xml one more time ..

    <property name="resourcePackage" value="com.abc.xyz"/>    
    <property name="version" value="1.0.0"/>
    <property name="host" value="myhost:8443"/>            
    <property name="basePath" value="/MySwaggerCxf/api/v1.0"/>    
    <property name="title" value="My Swagger Cxf"/>
    <property name="description" value="This application will list all web services available."/>
    <property name="scan" value="true"/>

**Comment by webron** [comment]
@rmahajan1234 - based on your configuration, your API itself is hosted under `/api`. Removing it from the Swagger documentation would mean the API calls won't be successful. What is it that you're trying to do exactly?

**Comment by rmahajan1234** [comment]
My web service URL is https://myhost.com:8443/MySwaggerCxf/api/v1.0/pet/12.xml

I would like it to become: https://myhost.com:8443/MySwaggerCxf/v1.0/pet/12.xml

If I change web.xml: swagger.api.basepath to be /
and CxfServiceServlet URL-pattern to /*   then I can not access Swagger-UI page (.....dist/index.html), it thinks I am trying to make a web service call.

**Comment by webron** [comment]
Got it. This is more of a URL mapping issue with CXF (possibly generally JEE apps), so you need to research if it's possible to do such mapping. It's not directly related to swagger. The simplest workaround would be to host swagger-ui under a directory and have something like /ui to get to it.

**Comment by rmahajan1234** [comment]
Ron,
I am trying understand your workaround. At the moment, dist folder is under webapp/dist. Do I need to move it somewhere else?
What do I need to do to host Swagger under /ui ? and what config change do I need to make?

Thanks
Ram

**Comment by webron** [comment]
Sorry, I've missed the part it is hosted under /dist. In any case, there's a conflict between hosting your app from the root and wanting to expose static data from the same place. http://stackoverflow.com/questions/30111978/hosting-static-content-and-jax-rs-services-under-the-same-root-context describes a similar case and a partial solution, albeit regarding RESTEasy. There may be a solution in CXF as well, so you may want to raise the issue in their forums if you don't find it in their documentation.

**Comment by fehguy** [comment]
please reopen if still an issue.
