### ISSUE TITLE
Support collectionFormat with formData

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-ui#1657]
Currently, it seems that only csv is supported.

**Comment by webron** [comment]
@cbornet - just tested with `multi` and it works well. Can you elaborate on what you've tried that didn't work?

**Comment by cbornet** [comment]
I tried with ```ssv``` and I got csv.

**Comment by cbornet** [comment]
OK. This is because I use ```formData``` and it is not implemented yet in SwaggerJS. Seems there is a PR for this in https://github.com/swagger-api/swagger-js/pull/537.

**Comment by tellsaqib** [comment]
Although it's not mentioned in Swagger Specs but if you use
`collectionFormat: brackets`
in your spec file then Swagger will send data as proper input array.

**Comment by cheerfulstoic** [comment]
If `brackets` worked at one point, I don't think it does anymore.  I don't see `brackets` anywhere in the `swagger-ui` source, either.

I could also use `collectionFormat` for `formData`...

**Comment by webron** [comment]
This seems to be supported now. Please file a new ticket if needed.

@cheerfulstoic `brackets` is not an official part of the spec and any support for it was dropped.
