### ISSUE TITLE
Swagger (spring mvc) and swagger-ui javascript error (toLowerCase() error)

### ISSUE THREAD

**Issue by Paul776** [swagger-api/swagger-ui#1658]
Hello,

I have included swagger-springmvc in my spring project as well as swagger-ui (v1) (latest version on the github I have copied all the html/js etc.. file in the webapp's doc folder)

http://locahost:8080/api/api-docs returning me a good JSON

When I go to http://locahost:8080/api/doc/index.html

It hangs at http://locahost:8080/api/doc/index.html;Please wait.

There is a javascript error operation.js:662 saying Uncaught TypeError: detectedType.toLowerCase is not a function

I cannot figure out whats going on here, did I miss something in my configuration ?

Thanks

**Comment by webron** [comment]
Looks like you're using an old version of swagger-springmvc. Any chance you could upgrade to the latest which is now called [springfox](https://github.com/springfox/springfox)?

**Comment by brentonmcs** [comment]
I'm also seeing this with the latest Swashbuckle version.

This is happening in the helpers/handlebars.js when it's checking to see if the type is an array and the type is undefined. The param json is generated like this:

{"name":"verified","in":"body","required":true,"schema":{"type":"boolean"}}]

**Comment by kumarz** [comment]
@Paul776 : I am facing the same issue, can you please let me know, how you resolved it ? if you change the lastest version. what is the version that you upgraded to ?

**Comment by datumgeek** [comment]
i had a similar issue in swagger-ui trying to use path variables.

turns out, if the path variable has no caps (and the associated parameter has no caps), it works

otherwise it fails

![image](https://user-images.githubusercontent.com/22680176/29496468-97dcc68e-8590-11e7-9f15-acd07c38310a.png)
