### ISSUE TITLE
swagger-ui: DELETE request with formData returns 415 Unsuported Media Type

### ISSUE THREAD

**Issue by to-kra** [swagger-api/swagger-ui#1659]
API DELETE method is defined to Accept: "application/x-www-form-urlencoded" and takes 1 @FormParam. 

Request works via Chromes Advanced Rest API plugin, 
however it does not via SwaggerUI: where backeng returns: 415 Unsuported Media Type

Only way which works is to use Json instead of FormData, but we want to use FormData - which apparently does not work well with swagger ui.

**Comment by webron** [comment]
Which version of swagger-ui do you use?

Can you take a look at the browser's web console network tab and see what's being sent when you try it out?

**Comment by phpmathan** [comment]
I'm using swagger-ui v2.1.4, and also facing same problem for DELETE method, where form data not send.

curl -X DELETE --header "Accept: application/json" --header "Authorization: Basic 1adcc4463ca5debf58503f4e10918fe39ffe9ec8" "<url>/v1/Api/testAccess.json"

POST/PUT method works fine.

curl -X PUT --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" --header "Authorization: Basic 1adcc4463ca5debf58503f4e10918fe39ffe9ec8" -d "key=name&value=Test" "<url>/v1/Api/testAccess.json"

**Comment by webron** [comment]
Can you provide a sample spec for us to test?

**Comment by phpmathan** [comment]
Download the used API document json from the following link.


I checked the request using firebug, in that form data not send.

**Comment by phpmathan** [comment]
Download the used API document json from the following link.

https://www.dropbox.com/s/02ojg394tdnr3si/apiDocs.json?dl=0

I checked the request using firebug, in that form data not send.

**Comment by Tobion** [comment]
I can confirm @phpmathan. "formData" parameters for DELETE requests are not send. Using "body" or "query" params work or using a different request method. But formData + DELETE doesn't work.

**Comment by fehguy** [comment]
Please open this on swagger-js and it'll get fixed.

**Comment by fehguy** [comment]
This should be fixed.
