### ISSUE TITLE
OperationGroup object doesn't contain "^x-" vendor properties

### ISSUE THREAD

**Issue by dalbani** [swagger-api/swagger-ui#1662]
While trying to use the `SwaggerUI::apisSorter()` functionality, I've seen that the `OperationGroup` objects passed to that function aren't populated with the `x-` properties that I have defined.
Given this example:

``` javascript
{
    "swagger": "2.0",
    "paths": {
        "/endpoint1": {
            "x-order": 1,
            "get": {
                "x-another": "abc",
                ...
            }
        },
        "/endpoint2": {
            "x-order": 2,
            "get": {
                "x-another": "def",
                ...
            }
        }
    }
}
```

I have no way of accessing the (value of) the `x-order` properties in what are turned into `OperationGroup` objects.
(Whereas I _can_ do it for for the `x-another` property by the way.)

In addition to modifying `swagger-ui`, I suppose fixing this would require a change in the `swagger-client` library as well?

**Comment by ponelat** [comment]
Yeah, to get custom x-props of OperationGroup, we would need to change swagger-js... shouldn't be tooo hard.

**Comment by webron** [comment]
Shouldn't be an issue with the new UI.
