### ISSUE TITLE
Work around issues with content type sniffing mechanism

### ISSUE THREAD

**Issue by dalbani** [swagger-api/swagger-ui#1663]
Swagger UI uses some kind of "content type sniffing" mechanism when displaying API responses, which involves making an XMLHttpRequest first and then acting differently depending on the MIME type of the response (e.g. `image/*` are shown through a `<img>` element, text, JSON, etc are shown inside a `<pre>` element, and so on).
The logic is in `OperationView.js::showStatus()` for those who want to see the details.

Now, I find this mechanism a bit clunky at best because of the additional HTTP request (e.g. through the <img> or <video> element).
While it should be possible in theory to repeat identical idempotent (i.e. not PATCH or POST) requests, in many API have requests some "cost" attached (e.g. be it time and/or financial).
So an additional HTTP request can really make a difference in some use cases -- even if it only concerns the API "try out" page.

In addition, this content sniffing mechanism is broken for non-GET requests, as you can't "replicate", say, the original POST request through an `<img>` element!

So at least for operations which are associated with a _single_ possible response MIME type, shouldn't this sniffing mechanism be disabled altogether?

I'd like to hear your opinion.

**Comment by ponelat** [comment]
While we should make effort to reduce HTTP requests in general (for many reasons), I'm not sure here is a case where it makes sense.

So, taking a quick look at the code, here is a rough breakdown..
Execute HTTP request (with a chunk of logic)
Try to guess content, by sniffing
render textual content (no problem here)
render tags with `src` (might trigger another HTTP request)

I think a POST/PATCH/PUT/DELETE request that returns an image(or audio) response, is outside the scope of this project? As it involves some dancing around Blobs (not supported in every browser)

Perhaps we can make it clear that image/audio are naturally(by the browser) requested again in the README... and that steps to provide caching headers would reduce server load.

**Comment by dalbani** [comment]
> I think a POST/PATCH/PUT/DELETE request that returns an image(or audio) response, is outside the scope of this project?

That's indeed something that have to be discussed and decided.

My personal use case is an API that I want to describe in Swagger and which returns an image for POST requests: [Web Map Service](https://en.wikipedia.org/wiki/Web_Map_Service).
But now that I think again about it, my "solution" involving a *single* possible response MIME type doesn't even apply to WMS... Oops!

Maybe a *real* solution would be to support `XMLHttpRequest2`, which is able to return a `Blob` object that can be directly used to render an `<img>`.
See the example shown on http://www.html5rocks.com/en/tutorials/file/xhr2/.
That would save the additional HTTP request that I'm complaining about :-)

**Comment by ponelat** [comment]
For that, we'd only be able to support IE 10+ ... http://caniuse.com/#search=xhr2 , because of Blobs.
However, I do see the need for active requests and img tags (and HTTP costs).

It would be possible to make this happen, but a little involved we'd have to check [superagent](https://github.com/visionmedia/superagent) our main HTTP lib for its support of xhr2 and how we would propagate it to the UI.

**Comment by dalbani** [comment]
XHR2 is indeed not supported on all platforms, but I didn't mean to *completely* switch to XHR2.
The current mechanism can be kept for old browsers.

Regarding `superagent`, it does support XHR2 apparently:
https://github.com/visionmedia/superagent/search?utf8=%E2%9C%93&q=xhr2

**Comment by ponelat** [comment]
So then its all about propagating the Blob to the <img> tag... wanna give it a bash? The backlog is growing, and this won't top the charts as a *must have*.

**Comment by dalbani** [comment]
As it happens, I've just seen that Swagger UI does already make use of the Blob API, for file attachments:
https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/OperationView.js#L608

I'll have a go at implementing something for image/audio elements.

**Comment by ponelat** [comment]
Awesome, let me know if you need any help!

**Comment by dalbani** [comment]
Kind of depends on visionmedia/superagent#654 I reckon.

**Comment by ponelat** [comment]
Best I can do is +1 it then :/

**Comment by dalbani** [comment]
I wrote "kind of" in my previous message because there's a workaround:

```javascript
    request
    .get('/arraybuffer')
    .on('request', function () {
      this.xhr.responseType = 'arraybuffer';
    })
```

But I agree that an official API call would be nicer.

**Comment by ponelat** [comment]
that's not *too* bad.
If it helps get this PR out there, then I wouldn't let it hold you up.

You could add a comment: `// TODO: Pending visionmedia/superagent/pull/655`

Also, it would need to go into the jQuery request, for consistency. I don't think it would be much different?

**Comment by dalbani** [comment]
The present state of affairs of `responseType` in jQuery is quite "messy" apparently:
https://github.com/jquery/jquery/pull/1525

**Comment by ponelat** [comment]
ugh, no-one likes xhr2 :frowning: 
Are they trying to polyfill it? or is it really that challenging to add it to the request?

**Comment by dalbani** [comment]
If I've correctly understood the discussion, they want to implement it "properly", using a plugin-based solution, instead of overloading the main `$.ajax` API call.

**Comment by dalbani** [comment]
The API to set an XHR's `responseType` has been reportedly added in superagent version 1.8.0.
https://github.com/visionmedia/superagent/commit/dbc5d6f8590056c745e0ad9671c7ed6878362e60
https://github.com/visionmedia/superagent/issues/654#issuecomment-260092988

**Comment by fehguy** [comment]
I believe this can be closed now with the latest version of swagger-js.
