### ISSUE TITLE
Option to hide the curl command in swagger response

### ISSUE THREAD

**Issue by mpusarla** [swagger-api/swagger-ui#1664]
Can swagger-ui add an option to hide the curl command in the response?

**Comment by fehguy** [comment]
Yes, you can simply hide it via CSS.  I believe it's "curl" in the css.

**Comment by rwinscot** [comment]
.curl {
	display: none
}
...doesn't get rid of the H4 'Curl' above Request URL.

![curlyz_q](https://cloud.githubusercontent.com/assets/214177/10526566/af4bdcec-7359-11e5-8282-f4a18c9e514d.png)

**Comment by rwinscot** [comment]
Added curl class to H4... can hide entire section now via CSS.

https://github.com/swagger-api/swagger-ui/pull/1676

**Comment by webron** [comment]
Fixed via #1676.

**Comment by cupgit** [comment]
This introduced a bug where two curl boxes were shown. 

Fix in:
https://github.com/swagger-api/swagger-ui/pull/1709

**Comment by anuragmishracrest** [comment]
css is present in lib so we cannot make changes in them.
is there any way to hide through Docket or java configuration?
