### ISSUE TITLE
RFC 6570 Form-Style Query Expansion support

### ISSUE THREAD

**Issue by chrisdostert** [swagger-api/swagger-ui#1665]
the springfox project (swagger spec generator for java spring projects) recently implemented a clever feature to allow the documentation of endpoints with identical paths but varying query parameters. They do this by using an RFC 6570 url template for the path. This works nicely with swagger ui to a point. The missing piece is that although query parameters are expanded, the query parameter variables are not removed from the path.

springfox/springfox#866

**Comment by webron** [comment]
@chrisdostert - I'm afraid springfox decided to implemented something that is well outside the Swagger spec, and is known to be outside of it. As a tool, swagger-ui tries to conform to what Swagger allows. As such, we'd rather not implement support for such features.
