### ISSUE TITLE
How do we Navigate to specific resources in the SwaggerUI 

### ISSUE THREAD

**Issue by Jindam** [swagger-api/swagger-ui#1667]
Hi,
I want to go to specific Resource by appending .../swagger/ui/index/Appoinments
Here,it should navigate to Appointments Controller

**Comment by webron** [comment]
Do you mean display only that resource in the UI or directly open it? Linking to specific resources can be done by something like http://petstore.swagger.io/#!/pet but you can't filter out a single resource only.

**Comment by Jindam** [comment]
Thanks for your reply,I can able to browse list of controllers when I navigate to http://localhost:10000/swagger/ui/index#/.
Can we select the particular controller by appending in the route URL,Something like this http://localhost:10000/swagger/ui/index#/Appointments.
Here,Appointments is the controller name from the list.So that,I can view only particular controller not all the controllers.

**Comment by webron** [comment]
Right now, the only way to do that is by having a different Swagger definition for each controller.

**Comment by Jindam** [comment]
I have more than 100 controllers in the application,so adding definition each time doesn't look good.
Is this requirement can be customized by swagger.?

**Comment by webron** [comment]
Which tool do you use to generate your Swagger definition?

**Comment by Jindam** [comment]
VisualStudio 2015

**Comment by Jindam** [comment]
Can we upload documents to SwaggerUI as a binary file

**Comment by webron** [comment]
Not sure I follow the last question.

**Comment by kbadiger** [comment]
Hi , i have created the restfull apis document by swagger editor , i have a navigation isssue , for example  the url is https://petstore.swagger.io/#/pet/updatePet  , whem you click this it will redirecting to main page instead of the next page , please help me to overcome from this
