### ISSUE TITLE
Possibility to add a default @Consumes and default @Produces

### ISSUE THREAD

**Issue by HenrikHL** [swagger-api/swagger-ui#1669]
My API supports many consume-types and it can produce many different types as well:
xml, json, csv, etc...

Whenever @Consumes is defined on class level - the order in the Swagger-UI is "random". It is never sorted in the order listed in the code. The first item listed in "Response Content type" is selected as default - in my case this is AVRO, and I would like JSON to be default. The same goes for @Produces.

However when @Consumes and @Produces is defined on Operation-level (on the "GET" method) the first item listed is always the default value in the Swagger-UI ("Response Content type").

My guess is that on class level the @Consumes and @Produces is saved in a HashMap or similar unsorted list/map. While when defined on Operation.level - the Swagger-UI reads it directly and thus obeys the listed order...?

I almost never define @Consumes and @Produces on operation-level as it is much easier to define it on class level.

Here is an example of how it looks in my API:
![image](https://cloud.githubusercontent.com/assets/3489388/10418438/8ff653be-705b-11e5-8840-b0f2da3eb924.png)

This has been generated from the following code:

```
@Consumes( {MediaType.APPLICATION_JSON,             //Json
        MediaType.APPLICATION_XML,                  //XML
        "text/csv",                                 //CSV
        SmileMediaTypes.APPLICATION_JACKSON_SMILE,  //Smile
        "text/yaml", "application/yaml",            //YAML
        "application/x-protobuf",                   //Protobuf
        CBORMediaTypes.APPLICATION_JACKSON_CBOR,    //CBOR
        "application/x-avro",                       //AVRO
        MediaType.MEDIA_TYPE_WILDCARD               //*
} )
@Produces( {MediaType.APPLICATION_JSON,             //Json
        "application/hal+json",                     //HAL+Json
        MediaType.APPLICATION_XML,                  //XML
        "application/hal+xml",                      //HAL+XML
        "text/csv",                                 //CSV
        SmileMediaTypes.APPLICATION_JACKSON_SMILE,  //Smile
        "text/yaml", "application/yaml",            //YAML
        "application/x-protobuf",                   //Protobuf
        CBORMediaTypes.APPLICATION_JACKSON_CBOR,    //CBOR
        "application/x-avro"                        //AVRO
} )
public class ComparisonsService {
...
}
```

As can be seen above - JSON is listed first...

A suggestion would be to add a defaultProduces and defaultConsumes on the @ApiOperations

**Comment by webron** [comment]
The solution solution would be to make sure that the the mime types are serialized in order (though that depends if reflection provides that ability) and make sure the list is displayed in order in the ui as well (after all, it's an array).

**Comment by daniogao** [comment]
I am integrating swagger with protobuf. Your content types include protobuf. So could you give me any suggestion. Thanks!

**Comment by webron** [comment]
This issue didn't get a lot of traction, and so it's being closed. If anyone find it important, please file a new ticket.
