### ISSUE TITLE
Plug in multiple swagger spec in the same swagger-ui

### ISSUE THREAD

**Issue by sacredMonster** [swagger-api/swagger-ui#1672]
Hello,

I have multiple swagger.json files (each of these spec files is for one service) and I am trying to have all these spec files plugged into the same swagger-ui. For instance: the api_selector should give me an option to select one of those swagger.json files and the resource should be rendered from the selected spec file.
Is there way to do this?

Thanks

**Comment by fehguy** [comment]
Hi, currently no, you cannot, although it's quite easy to add yourself.  You should be able to do everything in the index.html file that ships with swagger-ui and reload the UI with an `.onChange` event.

**Comment by webron** [comment]
@ponelat shared a solution in the google group that may help your use case - https://groups.google.com/d/msg/swagger-swaggersocket/Uz9UhRzKBo8/ITQkXO-zvwAJ

**Comment by sacredMonster** [comment]
Thanks @webron and @fehguy for your help. The solution @ponelat shared was what I was looking for. With that solution I incorporated the .onChange to refresh the UI without having to click the explore button. But I don't know what am I doing wrong here, cause the selector is not getting updated with the selected option:
Here is the code:

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Swagger UI</title>
  <link rel="icon" type="image/png" href="images/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="images/favicon-16x16.png" sizes="16x16" />
  <link href='css/typography.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/screen.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='print' rel='stylesheet' type='text/css'/>
  <link href='css/print.css' media='print' rel='stylesheet' type='text/css'/>
  <script src='lib/jquery-1.8.0.min.js' type='text/javascript'></script>
  <script src='lib/jquery.slideto.min.js' type='text/javascript'></script>
  <script src='lib/jquery.wiggle.min.js' type='text/javascript'></script>
  <script src='lib/jquery.ba-bbq.min.js' type='text/javascript'></script>
  <script src='lib/handlebars-2.0.0.js' type='text/javascript'></script>
  <script src='lib/underscore-min.js' type='text/javascript'></script>
  <script src='lib/backbone-min.js' type='text/javascript'></script>
  <script src='swagger-ui.js' type='text/javascript'></script>
  <script src='lib/highlight.7.3.pack.js' type='text/javascript'></script>
  <script src='lib/marked.js' type='text/javascript'></script>
  <script src='lib/swagger-oauth.js' type='text/javascript'></script>

  
  
  
  

  <script type="text/javascript">
    $(function () {
      var url = "One.json";

      // Pre load translate...
      if(window.SwaggerTranslator) {
        window.SwaggerTranslator.translate();
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
		validatorUrl: null,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            initOAuth({
              clientId: "your-client-id",
              clientSecret: "your-client-secret",
              realm: "your-realms",
              appName: "your-app-name", 
              scopeSeparator: ","
            });
          }

          if(window.SwaggerTranslator) {
            window.SwaggerTranslator.translate();
          }

          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });
        },
        onFailure: function(data) {
          log("Unable to Load SwaggerUI");
        },
        docExpansion: "none",
        apisSorter: "alpha",
        showRequestHeaders: false
      });;

      window.swaggerUi.load();

      function log() {
        if ('console' in window) {
          console.log.apply(console, arguments);
        }
      }
  });
  </script>
</head>

<body class="swagger-section">
<div id='header'>
  <div class="swagger-ui-wrap">
    <a id="logo">Store Xplorer</a>
    <form id='api_selector'>
	<div class="input">
        <select id="input_baseUrl" name="baseUrl"></select>
      </div>
	<div class='input'><a id="explore" href="#" data-sw-translate>Explore</a></div>
    </form>
  </div>
</div>

<div id="message-bar" class="swagger-ui-wrap" data-sw-translate>&nbsp;</div>
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>

<script>
  var spec = {
    'One': "One.json",
    'Two': "Two.json"
  }
  var sel = $('#input_baseUrl');
  $.each(spec,function(key,val){
    var opt = $('<option>').prop('value', val).html(key);
    sel.append(opt);
  });

  $('#input_baseUrl').change(function() {
  var url = $(this).val();

      // Pre load translate...
      if(window.SwaggerTranslator) {
        window.SwaggerTranslator.translate();
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        validatorUrl: null,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            initOAuth({
              clientId: "your-client-id",
              clientSecret: "your-client-secret",
              realm: "your-realms",
              appName: "your-app-name", 
              scopeSeparator: ","
            });
          }

          if(window.SwaggerTranslator) {
            window.SwaggerTranslator.translate();
          }
          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });

        },
        onFailure: function(data) {
          log("Unable to Load SwaggerUI");
        },
        docExpansion: "none",
        apisSorter: "alpha",
        showRequestHeaders: false
      });
      window.swaggerUi.load();

      function log() {
        if ('console' in window) {
          console.log.apply(console, arguments);
        }
      }
});
</script>
</body>
</html>

**Comment by sacredMonster** [comment]
Thanks @webron  and @fehguy . The solutions that you guys said worked. However, I am hitting this issue when I try to do a ui re-load when the selected service is changed. The re-load works perfectly fine and the APIs are loaded correctly. However, the text value of the selector does not change in the UI and always remains One. Is there any other place that I need to set the selected service?

Index.html present here: https://gist.github.com/sacredMonster/1fdd8fad2d99e4f8b408

Thanks..

**Comment by ponelat** [comment]
@sacredMonster we'd have to change some things... here is an updated gist https://gist.github.com/ponelat/328c2f651760fe3fdab2

**Comment by sacredMonster** [comment]
@ponelat thank you for the help.

**Comment by Ir1sh** [comment]
I imagine with the prevelance of microservices this is going to become a more sought after feature

**Comment by hunt3r** [comment]
We built this into our swagger spec, but it was painful to deal with the version parameter.  I'm in the process of porting all our customizations to the latest version and I can report back when I get through that.  I think the biggest pain point is where do we store the configuration of all our services, end point versions, and environments.  We are micro service oriented.

Our existing swagger ui has a custom header control like this:
![image](https://cloud.githubusercontent.com/assets/324819/23133838/87f46f56-f760-11e6-85b2-2e3e6795a398.png)

We had to come up with a custom JSON object to define that header and keep it up to date. Also, we have a proxy that handles all the pathing by environment, we prefixed the routes with `/dev`, `/staging` etc, but the issue with this is that the swagger spec itself is served from the service, but in each environment it isn't aware of the proxy path.  I had to write a hack into the swagger core that injected this into the base path of the swagger spec on the fly as its accessed.  It would be nice if that was somehow configurable from the swagger ui.

**Comment by ondrejtomcik** [comment]
Hi @hunt3r , is your solution available here on github please?

Thanks

**Comment by claudio-viola** [comment]
@hunt3r   👍  share share share!

**Comment by hunt3r** [comment]
I actually rebuilt the whole thing last week and introduced a python app server that handles all the routing and functions as a proxy to the services.  The solution above required a core hack to swagger ui and I didn't like that. It had to update the basePath and host URL dynamically based on the environment you are using and the /<env> path had to be in the root of all requests.  The new solution handles all of this server side so the swagger ui is completely vanilla. The server routes you to a page that dynamically wires up the spec location on the server render, and the UI doesn't know anything about managing the micro service/environments or proxy locations anymore.  This also allows for deep linking into the handlers now, that was previously broken in my previous solution.

It assumes that your services publish the swagger specs.

It uses a YAML file to configure everything and generate the UI, wireup all the proxies via Tornado, generate the header navigation, etc. I even added a homepage that is generated with links and other info.

I do plan to open source the solution I just haven't gotten it to where its generic enough. It has all the URBN specificity in there right now.  I will post back here within a month or so and link you to the repo when its ready.

**Comment by syedsanahassan** [comment]
@hunt3r can you post whatever we have and we as a community and contribute. Thanks for doing the good work.

**Comment by tfitch** [comment]
I know the issue is already closed but even after reading all the comments it wasn't clear this functionality is now built-in to swagger-ui version 3.x using the `urls` parameter in the `index.html` file.  https://github.com/swagger-api/swagger-ui#parameters

So hopefully this will save some people the trouble of trying to implement the above solutions when this is now a supported feature.

**Comment by davidkastanek** [comment]
> I know the issue is already closed but even after reading all the comments it wasn't clear this functionality is now built-in to swagger-ui version 3.x using the `urls` parameter in the `index.html` file. https://github.com/swagger-api/swagger-ui#parameters
> 
> So hopefully this will save some people the trouble of trying to implement the above solutions when this is now a supported feature.

Updated doc link: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#parameters

**Comment by HansFalkenberg-Visma** [comment]
@tfitch Thanks, that was just what I needed!
The documentation has moved though: https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md
