### ISSUE TITLE
Regression - enum fields are missing from models

### ISSUE THREAD

**Issue by rdiehl** [swagger-api/swagger-ui#1673]
We are using the Swagger spec version 1.3 (not the latest 2.0 spec).  We have a number of model definitions that contain Java enums.  In Swagger-UI version 2.1.3, those enum fields are missing from the swagger UI interface.  This leads to incorrect requests being generated when using the UI.  This functionality worked in previous versions of swagger-ui, I believe we had been using 2.0.24.

Here is a gist of the api-docs endpoint that is generated using the swagger-core JAX-RS annotations:  https://gist.github.com/rdiehl/50c023b84c5b4f3adbfc

We are using swagger-core_2.10-1.3.10.

![screen shot 2015-10-12 at 3 08 02 pm](https://cloud.githubusercontent.com/assets/9591293/10436223/1b203bc0-70f3-11e5-9b6c-38d80183e4a9.png)
![screen shot 2015-10-12 at 3 08 13 pm](https://cloud.githubusercontent.com/assets/9591293/10436224/1b2519a6-70f3-11e5-84bb-839788942279.png)

As you can see from the above screenshots, metadataType shows in the Model description (with an undefined type), but is absent from the Model Schema.  This happens in multiple Models within our system, this is just an example.

**Comment by webron** [comment]
This should be resolved in 3.0. Please reopen otherwise.
