### ISSUE TITLE
SwaggerClient is undefined

### ISSUE THREAD

**Issue by bharrison1984** [swagger-api/swagger-ui#1678]
Using the latest copy from the repo, SwaggerUI appears to fall flat on its face without loading any swagger spec. I tried the Petshop spec, and my local spec and both suffer from the same error.
![2015-10-16_11-47-15](https://cloud.githubusercontent.com/assets/10555123/10547730/dc1e71a6-73fb-11e5-9250-f6df343e6f16.png)
The code from the repo seemed to work fine a few days ago, so this must be a new issue.

**Comment by fehguy** [comment]
rebuilding & pushing now... it looks like the js lib isn't valid in the dist folder.

**Comment by bharrison1984** [comment]
Working fine now, thanks!

**Comment by fehguy** [comment]
thanks!
