### ISSUE TITLE
POST with content-type 'application.json' return bad request for express

### ISSUE THREAD

**Issue by fliptoo** [swagger-api/swagger-ui#168]
Hi,

I am facing some issue with the latest build, all my normal POST now return bad request for express application. i check the request header, i found that when using POST, swagger-ui set content-type to 'application/json', and express return bad request. My temporally solution is add 'consumes: [text/html]' to the api resources.

May i know this is express or swagger-ui issue? Previous swagger-ui version does not has this problem.

**Comment by kamil-kielczewski** [comment]
I use [this](https://stackoverflow.com/a/48413161/860099)

 * consumes={"multipart/form-data"},
 * produces={"text/plain, application/json"},
