### ISSUE TITLE
HTML Anchors

### ISSUE THREAD

**Issue by Collin-Molnar** [swagger-api/swagger-ui#1683]
Using an anchor doesn't expand the service defined by the operationId. 

Steps to replicate.
1. Click on swagger service to expand.
2. Anchor is added to the URL for the service that has been expanded.
3. Copy/paste URL (with anchor) into new browser window. 
4. Service defined by anchor is not expanded.

**Comment by magdiel01** [comment]
I have the same issue, did you found a solution for this?

**Comment by magdiel01** [comment]
@Collin-Molnar You can use this snippet in the "onComplete" callback, it worked for me

// Scroll to the anchor pointed in URL and expand it section
          $( document ).ready(function() {
            var urlAnchor = window.location.hash.replace('!/', '').replace('/', '_');

            setTimeout(function() {
              $('.path a[href="' + window.location.hash + '"]').click();
              $( document ).scrollTop( $(urlAnchor).offset().top );
            }, 700);
          });

**Comment by AlwaysGeeky** [comment]
Did this issue ever get resolved?

**Comment by heldersepu** [comment]
It used to work, here is an example with a slight older version:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#!/Default/Default_Get

But the latest demo does not work:
http://petstore.swagger.io/#

Anyone?

**Comment by webron** [comment]
This is a ticket that was opened on a much older version of the UI, and will not be addressed in it. For support in 3.X, please refer to #2884.
