### ISSUE TITLE
How to use swagger ui master with weblogic on linux machine

### ISSUE THREAD

**Issue by oshin-talreja** [swagger-api/swagger-ui#1684]
Hi,
I want to use swagger ui master for my application which is deployed on weblogic.

I am not able to find a suitable way for it.

Please guide me

**Comment by webron** [comment]
You'd need to add it as a set of static pages to your war application. https://blogs.oracle.com/middleware/entry/publish_static_content_to_weblogic may help.

**Comment by oshin-talreja** [comment]
Not able to get much info from that.... Please guide.

I tried to copy swagger-ui-master folder parallel to web-inf folder than i created war of my project and deployed it on WebLogic. I am to access my project rest api and html pages but index.html page of swagger is not working.

Please guide me how to use swagger ui master in weblogic.

Thanks in advance!! :)

**Comment by webron** [comment]
It really depends on how you build your war file. Eventually, it should directly at the root of your war file and you need to include only the content of the /dist directory, not the whole repository. This is really out of scope for the project though, and if it doesn't work for you, I'd suggest writing up in the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) and perhaps someone could help you.
