### ISSUE TITLE
Swagger 1.5.3 not able to read the JSON for Jersey2.17

### ISSUE THREAD

**Issue by vishakMetric** [swagger-api/swagger-ui#1685]
After successful configuration of Swagger. I'm adding the below snippet code from `index.html` file.

`<div class='input'><input placeholder="http://localhost/swagger/swagger.json" id="input_baseUrl" name="baseUrl" type="text"/></div>`
and
`$(function () { var url = window.location.search.match(/url=([^&]+)/); if (url && url.length > 1) { url = decodeURIComponent(url[1]); } else { url = "http://localhost/swagger/swagger.json"; } window.swaggerUi = new SwaggerUi({ url: url, dom_id: "swagger-ui-container", supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'], onComplete: function(swaggerApi, swaggerUi){ if(typeof initOAuth == "function") { initOAuth({ clientId: "your-client-id", realm: "your-realms", appName: "your-app-name" }); }`

I doubt it is issue with the browser compatibility. 

Below is what I observed in Firebug console.

The 'help' tag conflicts with a SwaggerClient function/property name. Use 'client._help' or 'client.apis.help' instead of 'client.help'. swagger-ui.js (line 1599)

TypeError: Argument 1 of XMLSerializer.serializeToString does not implement interface Node. swagger-ui.js (line 4327, col 25)

I created after `https://github.com/swagger-api/swagger-core/issues/1484` . I'm struck.

Please let me know the fix for same.

Following are the javascript files
1] backbone-min.js
2] handlebars-2.0.0.js
3] highlight.7.3.pack.js
4] jquery.ba-bbq.min.js
5] jquery.slideto.min.js
6] jquery.wiggle.min.js
7] jquery-1.8.0.min.js
8] marked.js
9] swagger-oauth.js
10]swagger-ui.js
11] swagger-ui.min.js
12] underscore-min.js
13] underscore-min.map

**Comment by webron** [comment]
Apologies, this fell off my radar. Closing as probably not relevant anymore. Please reopen if needed.
