### ISSUE TITLE
Missing parameter of type File causes an undefined reference when trying to show error message

### ISSUE THREAD

**Issue by psibernetic** [swagger-api/swagger-ui#1686]
Missing parameter of type File causes an undefined reference when trying to show error message when request is a multipart with formdata.

The request indicator shows activity as is highlighted in screencap.

![formdatamultipart-missingfileparameter](https://cloud.githubusercontent.com/assets/621605/10617619/1656c6e2-7731-11e5-81b2-71628509b676.PNG)

**Comment by webron** [comment]
This should be resolved in 3.0. Please reopen if you experience otherwise.
