### ISSUE TITLE
Swagger 1.5.3: Duplication of key in CURL

### ISSUE THREAD

**Issue by acinader** [swagger-api/swagger-ui#1687]
Steps to reproduce:

On the v2.1.3 tag, open  dist/index.html in a web browser which will open the pet api ui

Add an api key to the input box and click explore

Select the "Get User/{username}" and enter user1 into the username input box.  

click "try it out"

you should get a 200. 

In the `Request URL` field you should see: 

`http://petstore.swagger.io/v2/user/user1?api_key=myFunkyKey`

In the `Curl` field you should see: 

`curl -X GET --header "Accept: application/json" "http://petstore.swagger.io/v2/user/user1?api_key=myFunkyKey&api_key=myFunkyKey"`

Note that the api key is duplicated.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/efb77652274e99893b11848f02d9dc37d07344aa
