### ISSUE TITLE
Swagger 1.5.3: Key not added to requests that require a query string

### ISSUE THREAD

**Issue by acinader** [swagger-api/swagger-ui#1688]
On 1.5.3 Tag, to reproduce:

hit index.html so you get the pet api

add a key to the box and hit explore

open console in browser and verify that request has key (example: `http://petstore.swagger.io/v2/swagger.json?api_key=foo`)

select find pets by status and select a status.  then click "try it" and look at request in console.  Note that the api_key isn't there!  `http://petstore.swagger.io/v2/pet/findByStatus?status=pending`

If you then goto another request that doesn't require a query parameter like "get user by name" and add "user1" and make a request, you'll see that the api_key is appended.

will try and cook up some init tests to trip the behavior.

**Comment by fehguy** [comment]
Thanks, I expect this will be an issue in swagger-js.  There is a pretty straight-forward test structure there if you can try to duplicate this issue.

**Comment by webron** [comment]
This should no longer be an issue. Please reopen if you experience otherwise.
