### ISSUE TITLE
if the base path is not provided in the definition, it should use the URL relative to the location of the swagger definition

### ISSUE THREAD

**Issue by testn** [swagger-api/swagger-ui#1689]
Currently, I run swagger at http://localhost:20000/swagger.json but when I try to access the API, it will try it on http://localhost/operation instead. Notice that it does not maintain the port number.

**Comment by fehguy** [comment]
what do you have for `host`?

**Comment by testn** [comment]
I don't have any host or base path information set.

**Comment by fehguy** [comment]
I cloned swagger-ui and swagger-js from master and am running the following:

Hosting the swagger definitions:
```
cd swagger-js/test/spec/v2
http-server --cors
```

Hosting the swagger-ui:
```
cd swagger-ui/dist
http-server -p 8000
```

From this URL:

`http://localhost:8000/?url=http://localhost:8080/petstore.json`

If you remove the host & port from the `swagger-ui/test/spec/v2/petstore.json`, you'll see operations invoke like such:

```
http://localhost:8080/pet/findByStatus?status=available
```

Which is expected, as the swagger definition is hosted on port 8080

Adding `"basePath": "/foo/bar"` yields this:

```
http://localhost:8080/foo/bar/pet/findByStatus?status=available
```

Which is also expected.

So I can't quite reproduce your issue.  Please let me know where I'm looking at this incorrectly?

**Comment by testn** [comment]
I use angular-swagger-ui. Let me update and try again.

**Comment by testn** [comment]
It's a bug in  angular-swagger-ui. I will open one with them.

**Comment by fehguy** [comment]
thanks for the follow-up
