### ISSUE TITLE
Swagger generates empty post body

### ISSUE THREAD

**Issue by dothebart** [swagger-api/swagger-ui#1691]
as found in https://github.com/arangodb/arangodb/issues/1387 this swagger json: https://gist.github.com/pluma/5a0a62e11ee38e47bed9#file-swagger-json produces an empty post body when trying the POST /NodeTypes operation.
This works properly in the swagger editor and doesn't show anymore errors..

**Comment by fehguy** [comment]
Looks like the parameter name `nodeType` is causing some hell with the JQuery class selector.  It's an easy fix--when naming the elements we should avoid using the raw name and escaping reserved words.

**Comment by fehguy** [comment]
Would like to get #1884 merged first

**Comment by gavincornwell** [comment]
We're hitting the "nodeType" issue with our API definition, is there any plan to merge the pull requests to resolve this issue?

**Comment by webron** [comment]
This should be resolved in 3.0. Please reopen if you experience otherwise.
