### ISSUE TITLE
Model and Model Schema tabs seem to toggle incorrectly

### ISSUE THREAD

**Issue by KevinMitchell** [swagger-api/swagger-ui#1692]
I expand a method and under the response I see tabs for Model and Model Schema.  Initially it shows the model.  If I click on the Model Schema link nothing happens.  If I click on the Model link it then shows the schema.  So it looks like the links are the opposite way round to the text of the links.  Furthermore, if the model is currently shown it might be neater if the model link wasn't just dimmed but wasn't displayed as a link at all.  But that's more cosmetic.

**Comment by webron** [comment]
The color scheme may be confusing, but it actually starts off by showing the Model Schema which is highlighted in black vs gray. If you click on the Model, it'll switch to it, highlight it in black, and Model Schema turns gray.

**Comment by KevinMitchell** [comment]
I think I'm probably getting confused about what is meant by model and model schema here.  Suppose I add a path with a response that defines both a schema and an example. When I view this example in swagger-ui initially the Model tab is dimmed and what I see is the example object for the response (i.e. it shows Puma etc for the example below).  Now I suppose I could interpret the gray text on Model to mean that this is what is currently being shown, and the black text for Model Schema meaning that this button can be clicked to show the schema view.  However, if I click the Model Schema link nothing happens.  And if I click the Model button then it displays the schema.  This is with a local build of the latest git sources.  Here's an extract of the example I was trying; it's inconsistent in that the schema and example aren't compatible, but that presumably is not relevant here.

```
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfPersons
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
          examples:
            application/json:
              name: Puma
              type: Dog
              color: Black
              gender: Female
              breed: Mixed
```

**Comment by anovstrup** [comment]
I agree that the UI is confusing. When you click the "Model" link, the UI displays what I would call a "schema" (it's a generalized description that constrains the set of conforming models). When you click the "Model Schema" link, it displays an instance/example model (i.e., a particular model that conforms to the schema).

**Comment by webron** [comment]
Thanks for the feedback. We'll take it under consideration for future releases.

**Comment by webron** [comment]
This has been modified in 3.0.
