### ISSUE TITLE
Request header content type set to application/xhtml+xml instead of application/json

### ISSUE THREAD

**Issue by YLombardi** [swagger-api/swagger-ui#1693]
I use swagger2 with to document my spring boot application.
When I call the url : http://myapplication/v2/api-docs, the request header says that it accept XML but the api return json.
Here is my configuration : 
```java
@Configuration
@EnableSwagger2
public class Swagger2Config {

@Bean
public Docket welcomeMessageApi() {
    return new Docket(DocumentationType.SWAGGER_2)
            .apiInfo(apiInfo())
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(PathSelectors.any())
            .build();
}

private ApiInfo apiInfo() {
    return new ApiInfoBuilder()
            .title("My API")
            .description("Lorem Ipsum is simply dummy text of ...")
            .termsOfServiceUrl("an url")
            .contact("contact")
            .license("")
            .licenseUrl("")
            .version("2.0")
            .build();
}
```
How can I set the request header to accept json ?

I also create a question on stackoverflow http://stackoverflow.com/questions/33211610/swagger-2-accept-xml-instead-of-json

**Comment by webron** [comment]
Following your SO question, it looks like the problem that [springfox](https://github.com/springfox/springfox) doesn't use the proper mime type when exposing the Swagger spec. Can you open the ticket there instead?

**Comment by fehguy** [comment]
please reopen if still an issue
