### ISSUE TITLE
validatorUrl=null parameter does not work

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#1698]
Issue #630 does not seem to be fixed.

I'm following https://github.com/swagger-api/swagger-ui#parameters
but appending &validatorUrl=null does not work; I still get the red error badge

http://swagger.na.sas.com/swagger-ui/?url=http://swagger.na.sas.com/apis/reports/v1/swagger.json&validatorUrl=null

Also, I really need some way to disable this in index.html or elsewhere, not on the URL,
because I can't control who uses the URL and folks will omit this option.

Issue #630 includes a link to index.html which should show how to set it: 
https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L33
but it is not a link to a specific commit, so the line number is wrong

**Comment by webron** [comment]
@DavidBiesack - the `validatorUrl` is a parameter to the SwaggerUi object. You can add it in your index.html in the object definition: https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L43. You'll notice there are a few of the parameters defined there by default.

**Comment by DavidBiesack** [comment]
Thanks, I misread the doc and though it referred to URL parameters (I know I can pass ?url= in the swagger-ui URL)

**Comment by webron** [comment]
@DavidBiesack - did it work for you? Are we good to close the issue?

**Comment by DavidBiesack** [comment]
Yes, works for me. thanks.

**Comment by webron** [comment]
Ok, thanks for confirming.

**Comment by chenjianjx** [comment]
Can we make it a parameter like the OP thinks it was?  It's actually a common config.  
I even think frontend validation should be disabled by default, because only this way we can test if the backend has implemented the validation well.

**Comment by chenjianjx** [comment]
And it doesn't work for me even if I updated dist/index.html. 


````
      window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
		validatorUrl: null, 
````

I changed the last line to "validatorUrl:undefined".  Still not working.  Swagger UI still requires me to input value for required fields. 
I am using the newest code. 

Can you give an exact example of how to set this up ?

**Comment by dinvlad** [comment]
Same here, it simply doesn't work when I specify it in HTML as above

**Comment by FabianPiconeDev** [comment]
@webron I still have this issue like @chenjianjx .
