### ISSUE TITLE
Selector conflict when having multiple SwaggerUI instances on one page 

### ISSUE THREAD

**Issue by Stitch7** [swagger-api/swagger-ui#1699]
I have a HTML page, which initiates multiple SwaggerUI Instances with different swagger.json files. 
Each instance has a unique domId. In the different swagger json files there are endpoints with the same tag. When i click on one of that endpoints it unfolds the section in the other SwaggerUI instances too. This selector should be prefixed with the domId or something.

I recorded a GIF with a reduced example for better understanding:
http://g.recordit.co/SYyAHnXDzp.gif

**Comment by ponelat** [comment]
You're right - this is a bug. If we're to support multiple instances (we are afaik) then this should be resolved.


We can do this one of two ways... 

1. either allow a parameter something like `{ ..., domPrefix: "uiTwo" }`
1. or we add an entry to the window object (generally unwanted)
1. or (perhaps the best) is to simply use a random string generated at instantiation.

(2) and (3) are *hands free*

This issue also needs resolution ... https://github.com/swagger-api/swagger-js/issues/595

**Comment by webron** [comment]
This should not be an issue with the new UI.
