### ISSUE TITLE
Authorizations do not display in headers view

### ISSUE THREAD

**Issue by jonocodes** [swagger-api/swagger-ui#1702]
I have updated my swagger UI index.html file to support http basic auth.
I have also enabled the headers to be displayed via
showRequestHeaders: true

However the "Request Headers" display does not how any authorizations.

![screenshot from 2015-10-26 09 56 14](https://cloud.githubusercontent.com/assets/1310468/10735982/dfe97d02-7bc7-11e5-9266-c69b1b81e9a3.png)

**Comment by Tronix117** [comment]
:+1: Same issue here, requestHeaders are kind of useless if authorization headers are not shown there

**Comment by fehguy** [comment]
There seems to be some limitation on how you can get request headers from the underlying superagent library when running as localhost.  Can you please try loading http://petstore.swagger.io and hitting your server?

**Comment by webron** [comment]
This should not be an issue with the new UI.
