### ISSUE TITLE
Swagger UI doesn't render decimal number with NaN

### ISSUE THREAD

**Issue by adessaigne** [swagger-api/swagger-ui#1703]
It would be nice if it was possible to display `NaN` values as the result of a request.

It's true that the JSON specification disallows number values such as `NaN` ([see specification](http://www.ietf.org/rfc/rfc4627.txt)). But the JavaScript specification allows these values as valid JavaScript values ([see specification](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf)) and Swagger UI can already send JSON requests with `NaN` in them.

**Comment by dolmen** [comment]
As you already known this is not JSON. Your feature will never work with any compliant JSON implementation.

The point of Swagger is to enable wide operability. Stop thinking about support for this crazy hack.

**Comment by dolmen** [comment]
But as this is open source, you can patch swagger-ui yourself for your local instance...

**Comment by webron** [comment]
This is out of bounds of what we can support.
