### ISSUE TITLE
about UI looks like

### ISSUE THREAD

**Issue by kklam4697** [swagger-api/swagger-ui#1704]
Hello 
      I use swagger-ui to generate my API document as demo shows. But when I use swagger editor , the UI shows on the right is way more beautiful than the demo. Can know why is that?

thank you

**Comment by fehguy** [comment]
Hi, they are different projects with different use cases.  You might open an issue in the swagger-editor project to make a read-only view (I think one is open already).  Otherwise, I think we can close this :)
