### ISSUE TITLE
Add a "NYI" or Not Yet Implemented feature

### ISSUE THREAD

**Issue by rjgoldsborough** [swagger-api/swagger-ui#1706]
We are using swagger at work and would like a way to know whether a certain operation is implemented or not yet. We have found swagger works as a great api prototyping tool and sometimes the docs overtake the actual implementation.

Ideas include a small red or green dot to the left of the operation (I've implemented this and PR will follow), or possibly just greying out the whole section but this would take some color matching I think. I'm not against doing so if this sounds interesting.

**Comment by rjgoldsborough** [comment]
https://github.com/swagger-api/swagger-ui/pull/1707

**Comment by webron** [comment]
This could work only if you use a vendor extension to specify whether the API call is implemented or not, and in that case, I don't know if it should be part of the core library. That said, it shouldn't stop you from expanding the functionality in your own implementation.

Does that make sense?

**Comment by rjgoldsborough** [comment]
Absolutely does. I honestly hadn't even thought past the UI aspect. I have it implemented by just adding an attribute under the operation in the json but actually checking for it is probably a better way.

Will close. Thanks.

**Comment by webron** [comment]
Thanks for understanding, but also sharing the idea. Others may find it interesting too for their process. I'm always excited to see fresh ideas around how Swagger can be used to improve design/development process.

**Comment by jgroom33** [comment]
Can someone please share an example yaml/json that shows how to use this?

**Comment by rjgoldsborough** [comment]
@jgroom33 

sorry for the late response. I never noticed the notification.

You could do something like:
https://gist.github.com/rjgoldsborough/7d81ab483e79156e26cb

http://swagger.io/specification/#pathItemObject for reference.
Basically, add an "implemented" field to the path operation property. defaults to false in my PR.
