### ISSUE TITLE
Swagger UI not displaying swagger.json created from application 

### ISSUE THREAD

**Issue by paraglohiya** [swagger-api/swagger-ui#1708]
I am able to generate swagger.json using new swagger core 1.5.4 but when trying to integrate it swagger ui its not displaying the api.
Below is what I have done.
1. downloaded swagger-ui / dist (css, js, html) into project/webapp folder added index.html into web.xml
1. a) replaced petsorexxxx url with localhost:8090/myapp/api/swagger.json in index.html
2. after restart the application shows Swagger UI page correctly but api;s are not getting displayed
2. a) I also tried getting build version 1682 from github but still the same issues.

swagger.json file 

``` json
{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0",
    "title" : "RMS Data Service API",
    "contact" : {
      "name" : "Parag.Lohiya@marriott.com"
    }
  },
  "host" : "localhost:8090",
  "basePath" : "/myapp/api",
  "tags" : [ {
    "name" : "myresource"
  } ],
  "schemes" : [ "http" ],
  "paths" : {
    "/myresource" : {
      "get" : {
        "tags" : [ "myresource" ],
        "summary" : "Returns user details",
        "description" : "Returns a complete list of users details with a date of last modification.",
        "operationId" : "getIt",
        "produces" : [ "text/plain" ],
        "parameters" : [ ],
        "responses" : {
          "404" : {
            "description" : "User with given username does not exist"
          },
          "200" : {
            "description" : "Successful retrieval of user detail",
            "schema" : {
              "type" : "string"
            }
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/myresource/abc" : {
      "get" : {
        "tags" : [ "myresource" ],
        "summary" : "Returns user details",
        "description" : "Returns a complete list of users details with a date of last modification.",
        "operationId" : "getAppIt",
        "produces" : [ "text/plain" ],
        "parameters" : [ ],
        "responses" : {
          "404" : {
            "description" : "User with given username does not exist"
          },
          "200" : {
            "description" : "Successful retrieval of user detail",
            "schema" : {
              "type" : "string"
            }
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
Can you check the web console in your browser for errors when you load the UI?

**Comment by paraglohiya** [comment]
This is an error on Safari on Mac
I tried the same url in chrome and its working properly. It displaying the resources correctly. (no code change)

Error: Unknown template object: function
ehandlebars-2.0.0.js:26:5017
templatehandlebars-2.0.0.js:26:7388
(anonymous function)swagger-ui.js:191
(anonymous function)swagger-ui.js:230

Error Logs: ReferenceError: Can't find variable: SwaggerUi
(anonymous function)myapp:42
kjquery-1.8.0.min.js:1:16966
fireWithjquery-1.8.0.min.js:1:17720
readyjquery-1.8.0.min.js:1:12445
Djquery-1.8.0.min.js:1:9844

**Comment by webron** [comment]
Aha, so this may be safari specific. Thanks for the details.

**Comment by OliverSanftleben** [comment]
Hello, 

I'm having a similar problem. Swagger core 1.5.4 and Swagger UI 2.1.1 seem not to work together. 

I'm using swagger core in a dropwizard project (with BeanConfig) and getting the following Javascript error:

Zeitstempel: 06.11.2015 11:14:59
Fehler: TypeError: operation is null
Quelldatei: http://localhost:8080/application/swagger-static2/swagger-ui.js
Zeile: 1965

**Comment by OliverSanftleben** [comment]
I found a workaround by setting 

environment.getObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL);

in the 'run' method...

**Comment by fehguy** [comment]
You really should register the SwaggerSerializers `@Provider` so the JSON is correctly processed.  If you're getting a null (as @OliverSanftleben mentioned), then they are definitely not registered.
