### ISSUE TITLE
Using a source swagger.json Url directly from URL parameter

### ISSUE THREAD

**Issue by nodje** [swagger-api/swagger-ui#1719]
Unless I'm mistaken, I haven't found a way to create a URL that would encapsulate a target swagger.json.
I think it would be useful to have this possibility: one could point people directly to an API documentation page. (ex. ```http://petstore.swagger.io/target/http://myrestapi/```)

Right now I encapsulate the swagger-ui project in each of my project, but I think I'd be better off setting up a web instance of swagger-ui and let people use this instance to query my project's swagger.json.

My only problem is that they would have to type/paste in the project's swagger.json URL and that's a showstopper really.

**Comment by fehguy** [comment]
You can actually do so like such:

http://petstore.swagger.io/?url=http://petstore.swagger.io/v2/swagger.json

**Comment by nodje** [comment]
Fantastic, thanks, I didn't realise I could pass the API's parameter as URL param.
