### ISSUE TITLE
@Path("/") not rendered at all

### ISSUE THREAD

**Issue by bojanantonovic** [swagger-api/swagger-ui#1720]
When annotating a Java class with @Path("/"), then the slash ( / ), doesn't appear at all. In any other cases, like @Path("/abc"), the path "/abc" is rendered.

As our code runs, we would like to see the Swagger generated documentation handling it too.

I've tested this one with swagger-maven-plugin 3.0.0, 3.0.1 and 3.1.0, and couldn't find a reference for it elsewhere.

**Comment by fehguy** [comment]
Hi, please open this on [swagger-core](https://github.com/swagger-api/swagger-core) as this is a java problem, not UI problem.
