### ISSUE TITLE
Move swagger-ui javascript initialization out of index.html and into separate javascript file

### ISSUE THREAD

**Issue by brhou** [swagger-api/swagger-ui#1721]
This issue is a feature request to move this block of code into its own javascript file, something along the lines of an `init.js` or `config.js`.

https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L30-L101

The advantage here would be that those reading the documentation could just edit the contents of this file directly instead of having to read through index.html, which for the most part does not need to be modified. Since most users that are looking to use swagger-ui for their own purposes would likely want to change the contents of this code snippet, it would make it easier for both developers to understand and programs to modify if it were a separate file.

**Comment by ponelat** [comment]
+1

**Comment by fehguy** [comment]
If you can send a PR that adds a `config` option in the init AND keeps the current behavior, I'd be happy to merge it.  Just can't break the existing configuration mechanism.

**Comment by webron** [comment]
Closing as implemented in 3.X.
