### ISSUE TITLE
Add option to hide/suppress error response body schema/model

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#1722]
We have a standard error response schema that we use for 4xx and 5xx errors in our APIs. Works fine in Swagger UI, but the view consume a lot of real estate when we expand operations, and these models/schema tend to dominate the API doc, to the distraction of the main/expected body and parameters.

I propose adding an option (settable in index.html for example) that can leave the schema body
hidden by default for 4xx and 5xx responses. 

Related, it would be nice to show the error response with Status code, Description, and Response Model
but in the Response Model show

  Model | Model Schema | Hide

with the default being Hidden.

**Comment by Tronix117** [comment]
:+1:

**Comment by cabbonizio** [comment]
+1

**Comment by webron** [comment]
Closing as this is not something we're going to implement soon. If anyone wants to submit a PR covering this feature, we'll be happy to review.

**Comment by dit-j** [comment]
by the way. there is no reason to show the select box if only one option is present.
