### ISSUE TITLE
Corrupt file in swagger-ui maven repo package: droid-sans-v6-latin-700.eot

### ISSUE THREAD

**Issue by the-james-burton** [swagger-api/swagger-ui#1728]
I am unable to download the swagger-ui-2.1.2 package through my corporate firewall. The Kaspersky virus checker complains of a corrupt file. 

The droid-sans-v6-latin-700.eot file in the swagger-ui package is allegedly corrupt (according to Kasperksy themselves) and the Kaspersky virus checker cannot not scan it, so I am not allowed to download it (and therefore neither is maven).
http://repo1.maven.org/maven2/org/webjars/swagger-ui/2.1.2/swagger-ui-2.1.2.jar

When I try to convert the font droid-sans-v6-latin-700.eot extracted from your package using https://onlinefontconverter.com/ to a TTF, the conversion fails. The other font in your package, droid-sans-v6-latin-regular.eot does convert successfully.

A conversion of droid-sans-v6-latin-700.eot from the Kubernetes package works...
https://github.com/kubernetes/kubernetes/blob/master/third_party/swagger-ui/fonts/droid-sans-v6-latin-700.eot

Can you please check the droid-sans-v6-latin-700.eot file in your package? I think it might be corrupt in some way.

Regards,
James

Note: This issue was [originally raised](https://github.com/springfox/springfox/issues/1033) in the springfox-swagger-ui repo

**Comment by fehguy** [comment]
Hi, we don't maintain that webjar.  You will have to file a ticket with them (http://www.webjars.org/) to get it fixed.  In the meantime, you can grab the distribution from this project in the [releases](https://github.com/swagger-api/swagger-ui/releases) section.

**Comment by the-james-burton** [comment]
No problem, I am happy to raise an issue in the appropriate place. Can you tell me which webjar the droid-sans-v6-latin-700.eot font is from? I've had a search through your code but I can't figure out where you get the font from.

**Comment by the-james-burton** [comment]
I figured it out and created https://github.com/webjars/webjars/issues/1248
