### ISSUE TITLE
Is there any other way to Decode or Parse " json-data " into swagger-php using slim-php framework

### ISSUE THREAD

**Issue by dvikrant** [swagger-api/swagger-ui#1729]
Hello,
I am facing some issue with the swagger UI, that i am not able to decode the json-data in swagger. i dont know whether i am right or wrong..it always give me response as "no-content" and 0(zero) !! But, When i set the paramType-as "form" it works with normal php's slim coding, but as i want data to be parsed from json in that case it is not working at all....!!Then,  i have tried the below steps,
1] I have set the paramType as json, didn't workd..
2] I have also tried to set model schema into body-paramType, not done.. 

Once, let me clear that, data is comming in a json format..!! so, i request you to help me out on this topic
and tell me how this thing works with Swagger..!!
Thank you for your help..!! :)

**Comment by webron** [comment]
If you're getting that, it probably means something is off with the communication to/from the server.
You can use your browser's network tab in the developer console to see the actual request sent and the response, and that would help you isolate the problem.

**Comment by dvikrant** [comment]
Hello webron,

It is really great to see your reply very soon,
let me tell you that, as you said to have look at browsers console, i checked out and found the below things....!!

1] XMLHttpRequest cannot load http://localhost:82/getserv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:90' is therefore not allowed access. The response had HTTP status code 404.

   ---- so this is what i got in console first-time....!! but, when i googled it, it was like to mention the  "Access-Control-Allow-Origin" into ' index.php ' file as header. I set that and got removed the 
"Access-Control-Allow-Origin " error....!! thats ok,fine.....

But, still it throws me below error......

2] " XMLHttpRequest cannot load http://localhost:82/getserv. Invalid HTTP status code 404. "
and now i am stuck here....!! not getting anything,even from googling....!!

Let me tell you that, 
1] My swagger - UI has setup on the local machine at port 90, and
2] My project from local machine has a set-up on port 82.   ok....!!

and i am using Nginx web-server, where in nginx-config file I have kept below 4 lines to HTTP block, so as to swagger work..!!

             add_header 'Access-Control-Allow-Origin' '*';
             add_header 'Access-Control-Allow-Credentials' 'true';
             add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS,PUT';
             add_header 'Access-Control-Allow-Headers' 'Content-Type, api_key, Authorization';

Till now I have done this settings, but not able to parse json-data....so, if you know any better thing that works, then please guide me to the right track....!!
Thanks for showing interest..!!
