### ISSUE TITLE
Feedback if json invalid?

### ISSUE THREAD

**Issue by OliverSanftleben** [swagger-api/swagger-ui#1733]
Hello,

it would be fine if swagger-ui would give the user a feedback, if the swagger.json is invalid.

At the moment I'm getting only a message 'fetching resource list: http://localhost:8080/application/swagger.json; Please wait.', 

![2015-11-06 13_10_29-swagger ui](https://cloud.githubusercontent.com/assets/15686824/10996719/d52b45d0-8487-11e5-8571-20e6fa829fa9.png)

but javascript console says:

TypeError: operation is null
http://localhost:8080/application/swagger-static2/swagger-ui.js
Line 1965

I'm working with swagger-core 1.5.3 and swagger-ui 2.1.2

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
