### ISSUE TITLE
Not able to change the requestUrl

### ISSUE THREAD

**Issue by rohanjoseph** [swagger-api/swagger-ui#1735]
Hi i am not able to change the request URL in the swagger ui .it's always pointing to the localhost. 127.0.0.1:8080. I have hosted it in the amazon. so finally it should fetch the public ip but it is fetching the localhost ip which makes it difficult for us to work.
![images](https://cloud.githubusercontent.com/assets/5681794/11031118/3d9c63b6-86f8-11e5-8fe4-01e12f277939.png)

**Comment by webron** [comment]
What's the value of `host` in your spec?

**Comment by AshrinNida** [comment]
Hi,
I am new to swagger and am facing similar problem.
Am using swashbuckle  5.2.2
NugetPackage : Swashbuckle - Swagger for WebApi 5.2.2
The requested URL is always pointing to local host rather than pointing at hosted server.
Or it should be configurable.
I see that a similar issue has been [fixed](https://github.com/swagger-api/swagger-ui/issues/1343) .
Can you please help me with the same.

Thanks in advance.

**Comment by webron** [comment]
It sounds like a Swashbuckle configuration issue, and you should check with that project. You can always override the host using the swagger-js workaround, but it is indeed a workaround.

**Comment by AshrinNida** [comment]
Thanks a lot for the response . Is it possible to point me to the project
that you mentioned and also can you please help me out in how to override
swagger-js...is it through injectjavascript config or is there some other
way ?
Appreciate you help .
Thanks,
Ashrin

**Comment by webron** [comment]
You mean [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle)?

For the UI, you'd have to modify the code, yes, using something like `swaggerUi.api.setHost(...)`.

**Comment by AshrinNida** [comment]
Yes swashbuckle.
As I have integrated swashbuckle within my web project .I have
swashbuckle.core dll with embedded index n other css n js files. I am aware
of how to inject custom js but here you are recommending me to override one
of the embedded file which am not sure how to do.
I spent a lot of time trying to do that but dint succeed.

**Comment by webron** [comment]
Since you probably use the swagger-ui bundled with Swashbuckle, you'd have to ask in that project.
