### ISSUE TITLE
The property name "nodeName" leads to TypeError

### ISSUE THREAD

**Issue by Thies1965** [swagger-api/swagger-ui#1736]
As soon as one property in an swagger file is named "nodeName", swagger-ui breaks with an uncought exception "TypeError".

The root cause for this lies in the swagger-ui.js line 4223:

``` javascript
      if (t.nodeName) {
        var xmlString = new XMLSerializer().serializeToString(t);

        return this.formatXml(xmlString);
....
```

the test to be a Node has to be changed into:

``` javascript
       if (t instanceof Node) {
        var xmlString = new XMLSerializer().serializeToString(t);

        return this.formatXml(xmlString);
....
```

BTW: That was hard to find ;)

**Comment by fehguy** [comment]
Thanks--this is due to this:

https://github.com/swagger-api/swagger-js/issues/546

and will be addressed on next build of the ui.

**Comment by brocaar** [comment]
I'm running into the same issue, using the latest version (2.2.8) and with a Swagger definition containing a parameter called `nodeName`:

![image](https://cloud.githubusercontent.com/assets/165497/22739190/e521417c-ee0a-11e6-8c45-62edb2170d2e.png)


```
Uncaught TypeError: r.nodeName.toLowerCase is not a function
    at pe (jquery-1.8.0.min.js:2)
    at Function.oe [as find] (jquery-1.8.0.min.js:2)
    at init.find (jquery-1.8.0.min.js:2)
    at C.n.submitOperation (swagger-ui.min.js:13)
    at HTMLInputElement.r (lodash.min.js:1)
    at HTMLLIElement.dispatch (jquery-1.8.0.min.js:2)
    at HTMLLIElement.s (jquery-1.8.0.min.js:2)
```

**Comment by webron** [comment]
@brocaar - can you check master?
