### ISSUE TITLE
Value for parameter is set to (empty) when submittedSubmitMethods is blank

### ISSUE THREAD

**Issue by BrandonShega** [swagger-api/swagger-ui#1737]
I changed `supportedSubmitMethods = []` so that testing our APIs would be disabled.  But now if a field is marked as required it just shows (value) in place of the value.  Is there a way for the user to know that this is required as well?

Here is a screenshot showing the value for the parameter.
![screen shot 2015-11-09 at 4 57 37 pm](https://cloud.githubusercontent.com/assets/1090748/11048068/bdc7c23c-8703-11e5-973c-7b829556ba9f.png)

**Comment by webron** [comment]
Duplicate of #1304.
