### ISSUE TITLE
Let there be a Java-Swing based GUI swagger client? 

### ISSUE THREAD

**Issue by chenjianjx** [swagger-api/swagger-ui#1738]
swagger-ui has too many bugs.  It seems most of them happen because of the javascript language:  not very reliable, no compile-time check, easily affected and limited by browser constraints.  

Let there be a GUI swagger client such as Java and its Swing GUI?  With this robust language we can have a really reliable GUI client.

**Comment by fehguy** [comment]
um

**Comment by rohanjoseph** [comment]
i agree but righ now i am facing a trouble that.......my swagger ui's response url and curl both are responding towards to the 127.0.0.1:8080. Ihave placed swagger in /opt/jetty/webapps/ROOT folder.
![images](https://cloud.githubusercontent.com/assets/5681794/11056483/3c99ada6-87a8-11e5-9b98-d021182dfccd.png)

**Comment by brylie** [comment]
@chenjianjx what bugs are you specifically mentioning?

**Comment by chenjianjx** [comment]
@brylie  for example  https://github.com/swagger-api/swagger-ui/issues/1117

**Comment by brylie** [comment]
Is that bug a side-effect of the JavaScript language?

**Comment by webron** [comment]
Swagger UI is a javascript project. We currently have no plans on creating a Swing version of it, but if anyone from the community wants to create such a project, that would be a welcome contribution.

**Comment by Kitanotori** [comment]
Swing is dead, JavaFX is the way go nowadays in Java desktop world. For UI development, probably Gluon (based on Oracle's Scene Builder) is the best way to go. http://gluonhq.com/open-source/scene-builder/
