### ISSUE TITLE
basePath is not shown in UI

### ISSUE THREAD

**Issue by emirkin** [swagger-api/swagger-ui#1739]
My swagger contains `basePath`, yet the UI rendering does not show it (i.e. `/search` is shown). When I hit "Try it out!", I do see the correct url being assembled and used in the http call. 

```
{
  "swagger": "2.0",
  "info": {
    "version": "1",
    "title": "API Reference",
    "description": "API Reference"
  },
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/search
   ...
  },
  "basePath": "/v1"
}
```

**Comment by webron** [comment]
Which version of the ui do you use?

**Comment by emirkin** [comment]
v2.1.8-M1

**Comment by webron** [comment]
Can you upgrade to the latest version? You're using a fairly old one.

**Comment by emirkin** [comment]
Absolutely. Now that I used the latest, I still see the problem unfortunately.

**Comment by emirkin** [comment]
![screen shot 2015-11-10 at 1 06 02 pm](https://cloud.githubusercontent.com/assets/1053956/11075787/f5f344d0-87ab-11e5-94cd-a347af48e87e.png)

![screen shot 2015-11-10 at 1 06 24 pm](https://cloud.githubusercontent.com/assets/1053956/11075794/fd040d72-87ab-11e5-8415-f77787e07863.png)

**Comment by webron** [comment]
Do you mean you expect it to appear as `/v1/search`? That's not how swager-ui was intended to work. As you can see, the basePath appears at the bottom and anything under it would be displayed as the path. The basePath will not be repeated for each path.

**Comment by emirkin** [comment]
Yes, that is what I expected. I understand why the lib might want to separate the two. Is there a way for me to hack my local code to achieve that presentation change?

**Comment by webron** [comment]
You should be able to change the sources to present it that way by appending the two. @fehguy or @ponelat may be able to point you in the right direction.

**Comment by emirkin** [comment]
@webron  is 2.1.4 that I picked up the latest?

**Comment by webron** [comment]
2.1.4 is current master and not a released version, but you can use it (it's the 'cutting edge' version).

**Comment by ponelat** [comment]
It was quicker to add an option, than to explain (the code is pretty simple) @emirkin take a look at https://github.com/swagger-api/swagger-ui/tree/feature/showBasePathInOperation and add the `showBasePathInOperation: true` to your index.html file. Have fun!
