### ISSUE TITLE
Hide endpoints based on yaml/spec

### ISSUE THREAD

**Issue by GiladShoham** [swagger-api/swagger-ui#1743]
Hi,

I want to add some attribute to my yaml spec for example x-hide : true/false so that the swagger-ui will know to not show those endpoints.
i can't remove them completely from the yaml because im using swagger-node / swagger-express-mw so it's define the express mw based on this yaml, so if i remove them i can't use them at all.
i want them to be reachable but just not presented on the ui (because documentaion isn't ready yet / because they are mostly internally APIs that doesn't interest for the API users).
is there any way to do it?
maybe someone can help me to the best way to do it if there isn't out of the box?

Thanks.

**Comment by fehguy** [comment]
Hi, this is for swagger-node to do.  Can you please open a ticket in that project?  For example, the [swagger-inflector](https://github.com/swagger-api/swagger-inflector) allows `x-inflector-hidden` to create the route but not expose the route in the documentation.

**Comment by wvengen** [comment]
While it's probably best to do this in the json/yaml file, one can use this hack as well _index.html_. Insert between `window.swaggerUi = ...` and `window.swaggerUi.load()`:
```js
      // hack to filter out internal tags, operations and parameters before rendering
      var oldSuccess = window.swaggerUi.getOption('success');
      function filterInternal(x) { return x['x-internal'] !== true && (x['vendorExtensions']||{})['x-internal'] !== true; };
      window.swaggerUi.setOption('success', function() {
        var client = window.swaggerUi.api;
        client.apisArray = client.apisArray.filter(filterInternal);
        client.apisArray.forEach(function(api) {
          api.operationsArray = api.operationsArray.filter(filterInternal);
          api.operationsArray.forEach(function(op) {
            op.parameters = op.parameters.filter(filterInternal);
          });
        });
        return oldSuccess();
      });
```

**Comment by webron** [comment]
You should be able to write a plugin to the new UI to add that functionality.
