### ISSUE TITLE
Corrupt file: droid-sans-v6-latin-700.eot

### ISSUE THREAD

**Issue by the-james-burton** [swagger-api/swagger-ui#1744]
In issue https://github.com/swagger-api/swagger-ui/issues/1728 you advised me to raise a JIRA in with the webjars team. I did so in https://github.com/webjars/webjars/issues/1248.

They say their package is the same as this one https://codeload.github.com/swagger-api/swagger-ui/zip/v2.1.2. Sure enough, this ZIP file contains the corrupt font droid-sans-v6-latin-700.eot.

Sorry for raising another issue but I could not re-open the previous one.  I am trying to get to the bottom of this so I can use swagger-ui in my company without Kaspersky saying it is a virus.

**Comment by ponelat** [comment]
I'm looking into this... it does seem the kubernetes font file is different (their md5sums are, at least).
I cannot seem to find the definitive source... Google fonts has 'DroidSans-Bold'.

If it's blocking you from using this entirely, it seems only fair we resolve this... @webron should we just put in the droid-sans from kubernetes or the (albeit slightly differently named) Google Fonts versions, which has be verified it is the same font.

**Comment by webron** [comment]
@ponelat - whichever seems right to you, no preference here.

**Comment by ponelat** [comment]
@webron ok... I'm going to swap out the fonts to use Google's.
I'm also dropping all but, `.ttf` - @fehguy can you confirm we don't need the other font types? Here is my reference.. http://caniuse.com/#feat=ttf

**Comment by fehguy** [comment]
Should be fine!

**Comment by ponelat** [comment]
I need confirmation that this didn't break IE 9 rendering (or any other for that matter)... I'll get a VM of ie9 when I get a chance.

I've pushed to master... @the-james-burton please confirm you can download the .zip - and re-open if your problem persists, thanks!
I'll close for now

**Comment by the-james-burton** [comment]
Thanks very much for all your help resolving this!

The error only presents itself when downloading a .jar file, which means maven builds including the dependency don't work but .zip downloads are fine. I guess there is some stricter virus checking going on.

I have tried to download http://repo1.maven.org/maven2/org/webjars/swagger-ui/2.1.3/swagger-ui-2.1.3.jar (dated 13 Nov - maybe too old?) but the error is still there.

I will wait for your next release to maven central and then try again.
