### ISSUE TITLE
Open links from descriptions in a new window

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#1745]
Links inside descriptions open inside the same window... would be nice to open those links in a new window (perhaps configurable in an option?)

**Comment by webron** [comment]
@bodnia - can you take a look at this?

**Comment by bodnia** [comment]
@webron it was made in https://github.com/bodnia/swagger-ui/commit/442a7e87204b2762326485a61efb872c0384d5ac
But it looks like it's still not in master. I'll create a PR for this
