### ISSUE TITLE
Swagger UI shows raw html in Response Body frame

### ISSUE THREAD

**Issue by birbird** [swagger-api/swagger-ui#1748]
Hi,

I know this probably not a bug, but I have tried to ask for help in swagger forum and failed.
I think here must be more helpful so I ask here.

I use swagger with Lavarel. When the response is html, the raw html just showed in the response body frame, but not the rendered web page.
I used to use swagger with ruby grape, it could render the html.

I'm not sure if it has something to do with https://github.com/slampenny/Swaggervel
Could anyone please hint me, any help will be highly appreciated.

This is my swagger

```
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0"
    },
    "basePath": "",
    "consumes": [
        "application/json"
    ],
    "produces": [
        "text/html"
    ],
    "paths": {
        "/api/order/create": {
            "post": {
                "tags": [
                    "Order"
                ],
                "produces": [
                    "text/html"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                }
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Root"
                ],
                "produces": [
                    "text/html"
                ],
                "responses": {
                    "200": {
                        "description": "An example resource"
                    }
                }
            }
        }
    },
    "definitions": {
        "errorModel": {
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "integer",
                    "format": "int32"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "order": {
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Comment by ponelat** [comment]
Do you mean to say, that when click on "Try it now" and that resource produces `html`... you see the result of the DOM interpreting the html... or the actual html...

1.
**Hello**

2.
```html
<b> Hello </b>
```

Just trying to understand :smile:

**Comment by birbird** [comment]
@ponelat thanks for your attention
I think the expected result is ```1```, but actually I see is ```2```

**Comment by ponelat** [comment]
@birbird okay... so rendering html (1.) is tricky because it can produce unusual results, is a security risk (for your system, not swagger-ui) and can get corrupted by swagger-ui stylesheets.

Its not hard to implement, but most don't have a usecase for it.

I can point you in the right direction, if you'd like to customize it to suit your needs, but I'm afraid that this feature - will probably not make it into a release.

Perhaps you can explain your usecase, there might be a better way to solve?

**Comment by nicksellen** [comment]
We are using swagger for internal developers to use when writing an SPA frontend, django will return some errors in HTML and it is helpful for the developers to see them properly rendered [1].

I patched swagger-ui.js [2] to enable this, it puts the HTML content into an iframe using the `srcdoc` atttribute, this resolves the stylesheet issue you mentioned, and possibly the security issues too, but it [not supported in ie](http://caniuse.com/#feat=iframe-srcdoc).

Perhaps this makes the usecase clearer :)

[1] rendered django error

![swagger-ui-html-iframe](https://cloud.githubusercontent.com/assets/31616/11182287/f3306030-8c69-11e5-8636-4472e52063f2.png)

[2] swagger-ui patch

```patch
--- swagger-ui.js	2015-09-19 20:58:10.000000000 +0200
+++ swagger-ui.js	2015-11-16 13:45:26.958266568 +0100
@@ -31855,9 +31855,10 @@
 
     // HTML
     } else if (contentType === 'text/html') {
-      code = $('<code />').html(_.escape(content));
-      pre = $('<pre class="xml" />').append(code);
-
+      var iframe = document.createElement('iframe');
+      iframe.srcdoc = content;
+      iframe.style = 'width: 100%; height: 500px;';
+      pre = iframe;
     // Plain Text
     } else if (/text\/plain/.test(contentType)) {
       code = $('<code />').text(content);

```

**Comment by ponelat** [comment]
Thank you for the description @nicksellen.
If it makes development easier, I see no downside. 
The patch would need to be prettied up into a formal PR, if anyone would like to see this merged.

It would need to be made into an option under SwaggerUI. With a note in the README regarding the option and about IE compatibility. The changes would need to be put under `src` then compiled with `gulp` and commited with the `dist` files.

@birbird I'm guessing the above is what you're after?
@webron given the above notes, would you then consider this suitable for a merge?

**Comment by birbird** [comment]
@nicksellen Thanks for your clarification and your contribution.
@ponelat Sorry for the late response, this is exactly the case. We usually use some framework under the API, they usually return a web page if exception occurs in development enviroment. If we can see the error page directly (not some html code), it woud be easier to know what's wrong.

**Comment by ponelat** [comment]
@nicksellen we'd accept a PR if you have the time, given the above notes. Otherwise, @birbird we can put this in the backlog.

**Comment by nicksellen** [comment]
@ponelat great, I'll code it up in the next couple of days, when I can find a moment...

**Comment by arielcloud** [comment]
Any news  about this feature?...

**Comment by nicksellen** [comment]
Hmm, a few more days passed than I intended! I'm afraid I stopped having this requirement, but here's the patch I was using:

```patch
--- swagger-ui.js 2015-09-19 20:58:10.000000000 +0200
+++ swagger-ui.js 2015-11-16 13:45:26.958266568 +0100
@@ -31855,9 +31855,10 @@

     // HTML
     } else if (contentType === 'text/html') {
-      code = $('<code />').html(_.escape(content));
-      pre = $('<pre class="xml" />').append(code);
-
+      var iframe = document.createElement('iframe');
+      iframe.srcdoc = content;
+      iframe.style = 'width: 100%; height: 500px;';
+      pre = iframe;
     // Plain Text
     } else if (/text\/plain/.test(contentType)) {
       code = $('<code />').text(content);

```

**Comment by arielcloud** [comment]
I didn't found this rows in [https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/SwaggerUi.js](url)

**Comment by nicksellen** [comment]
It was from version 2.1.3 and it patches `swagger-ui.js` the dist directory. You'd have to dig around and found out where that bit comes from, grepping for `text/html` should show up something.

If you want to make a PR that will get accepted, you'll have to do a bit more than that though, make it an option, etc. as mentioned in https://github.com/swagger-api/swagger-ui/issues/1748#issuecomment-157024029

**Comment by arielcloud** [comment]
thanks!

**Comment by fehguy** [comment]
I think this can be closed now, please reopen as needed.  Note some functionality may not be possible because of all the fun we've had dealing with security risks.

**Comment by arielcloud** [comment]
@fehguy why did u closed this? I didnt saw that issue resolved

**Comment by fehguy** [comment]
We have to clean the HTML to avoid injecting tags and enabling XSS vulnerabilities.  So yes, raw html is what you should expect to see.

**Comment by snebjorn** [comment]
Would it be possible to get a toggleble flag to active/deactivate this "feature"?

The use case is that when running in "development mode" I want to to see the rendered html from fx AspNet error pages. When in "production mode" I have XSS vulnerability converns and thous I want to just show the html as text.

**Comment by vdwees** [comment]
I am using Swagger UI to document a service, and one of the endpoints returns embeddable content. Swagger UI renders the code as HTML, as described above. However, I found it useful to extend Swagger UI with a button to toggle rendering the html inline, so that it is easy to visualize and interact with the response from the server.

Screenshots are below. Notice the Show/Hide preview button in the bottom left corner. Its a small change that adds a really valuable feature without breaking any existing behaviour (https://github.com/vdwees/swagger-ui/commit/1344e49ca471c5eb4b546c7353a1efcff4456c2d)

Would a formal PR be welcome?

![image](https://user-images.githubusercontent.com/24944371/104166010-68cb1080-53fa-11eb-8fc5-0dcfcd87a2c4.png)

![image](https://user-images.githubusercontent.com/24944371/104166115-8e581a00-53fa-11eb-87e2-74fabbcb6a3a.png)
