### ISSUE TITLE
API declarations with swaggerVersion 1.2 are not loaded

### ISSUE THREAD

**Issue by prantlf** [swagger-api/swagger-ui#1750]
Let's have the JSON files like this:

``` text
/resources.json
/resource1.json
/resource2.json
...
```

The `url` option passed to the `SwaggerUi` is "/resources.json" - the resource listing.  When the API declarations are loaded, the AJAX calls fail, because the URL computation did not cut the resource listing file name, before the API declaration file names were appended:

``` text
"/resources.json/resource1.json"
"/resources.json/resource2.json"
```

The correct paths should look like these:

``` text
"/resource1.json"
"/resource2.json"
```

The version can be "1.0", "1.1" or "1.2" according to the [specification](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md).  However, the URL is constructed correctly only if the version is "1.0".  Should be the path combining the same for all "1.x" versions?  Thank you!

**Comment by prantlf** [comment]
I opened #1751 with a suggested fix.

I noticed, that the latest swagger-js contains different code for the API declaration absolute URL computation.  When the SwaggerUi integrates the newest SwaggerClient, this may need to be re-checked.

**Comment by prantlf** [comment]
Sample content of the `resources.json`:
```json
{
  "apiVersion": "1",
  "swaggerVersion": "1.2",
  "format": "json",
  "apis": [
	{
		"path": "/resource1.{format}",
		"description": "resource1"
    },
    {
		"path": "/resource2.{format}",
		"description": "resource2"
    }
  ],
  "info": {
    "description": "...."
  }
}
```

Sample excerpt of the `resource1.json`:

```json
{
  "apiVersion": "1",
  "swaggerVersion": "1.2",
  "basePath": "http://actualserver/",
  "resourcePath": "/resource1",
  "apis": [
	{
      "path": "api/v1/resource1",
      "description": "resource1",
      "operations": [
        {
          "method": "GET",
...

```

**Comment by prantlf** [comment]
I opened [a new PR for swagger-js](https://github.com/swagger-api/swagger-js/pull/638).  As soon as the swagger-js used in swagger-ui gets upgraded, this problem will be fixed.

**Comment by webron** [comment]
As of 3.0 we've dropped support for older versions of the spec. It's unlikely we'll fix issues related to those versions.
