### ISSUE TITLE
[markup] Span/Link/Div are not Buttons!

### ISSUE THREAD

**Issue by frol** [swagger-api/swagger-ui#1752]
Please, [don't use span/div/a as buttons](http://www.karlgroves.com/2013/05/14/links-are-not-buttons-neither-are-divs-and-spans/).

There is at least one place where I bumped into this - OAuth2 On/Off switch, which is a span with an image on background. You won't know that there is a button at all while the image isn't loaded. I bumped into the issue when the image was corrupted (testing PR #1589) and I spent an hour debugging JS because the corrupted image hasn't even raised a notice in Dev Tools (I would noticed 404 errors for example, but there was silence and I thought something is wrong in JS logic)!

Thank you all contributors for this great project!

**Comment by fehguy** [comment]
I think this is a programming style rather than a bug.  But if you'd like to submit a PR, I'm sure it can be merged in.
