### ISSUE TITLE
Response with inline schema does not show

### ISSUE THREAD

**Issue by vanderlee** [swagger-api/swagger-ui#1753]
Swagger-UI does not show a response with an inline schema other than a `$ref`.

As far as I can tell, the following short snippet should show as the response an object with a single property named "name" of type string. Instead it does not show the schema.

```json
{
    "swagger": 2,
    "paths": {
        "\/user": {
            "get": {              
                "responses": {
                    "200": {
                        "schema": {
                            "type": "object",
                            "required": [
                                "name"
                            ],
                            "properties": {
                                "name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by vanderlee** [comment]
Could anybody please tell me if the above is correct according to the 2.0 spec and/or whether swagger-ui should handle this?

**Comment by fehguy** [comment]
Not quite.  `swagger` must be the string `2.0` (not the number `2`).  In addition, your path must start with a `/`:

```json
{
  "swagger": "2.0",
  "paths": {
    "/user": {
      "get": {
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
Also, just tested it in the current `master` and it seems to be loading well.

**Comment by vanderlee** [comment]
Indeed you are correct, on all accounts.
I guess this issue must have been fixed since I posted it.

There does seem to be an issue with having a schema without an "object" at root:

{
  "swagger": "2.0",
  "paths": {
    "/user": {
      "get": {
        "responses": {
          "200": {
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

**Comment by webron** [comment]
That relates to https://github.com/swagger-api/swagger-ui/issues/1186.

**Comment by vanderlee** [comment]
Indeed, same issue. Closing this one
