### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by agliznetsov** [swagger-api/swagger-ui#1755]
I'm getting this error when try to execute the PUT request using the latest Swagger UI online demo with the following model:
[swagger.txt](https://github.com/swagger-api/swagger-ui/files/36436/swagger.txt)

**Comment by fehguy** [comment]
Looks like you're missing a required field `name`.  Granted, the UI shouldn't puke on it but that's the root cause.

**Comment by fehguy** [comment]
I've opened an issue on swagger-js for this.
