### ISSUE TITLE
Strange "indexOf" error when trying to load Pet Store demo

### ISSUE THREAD

**Issue by franka1** [swagger-api/swagger-ui#1758]
Hello,

I'm a new user and I've been attempting to follow the instructions on the README at "https://github.com/swagger-api/swagger-ui" to just get the Pet Store demo working. I used the "spec" parameter to replace the url with a JSON object, since I had to change the provided JSON's "schemes" field to use "https" rather than "http".  However, when the page tries to render the Swagger UI it encounters the following error:

"Uncaught TypeError: Cannot read property 'indexOf' of undefined (index.js:24)"

The linked index.js file looks has no mention of the indexOf method, leaving me with little idea of what is causing this.

Thanks,
Alex

**Comment by fehguy** [comment]
are you passing the URL?  Can you paste the whole stack trace?

**Comment by franka1** [comment]
I am not passing the URL. Rather, I am using the "spec" option to pass the JSON object directly.

Stack trace:
![screen shot 2015-11-17 at 2 00 53 pm](https://cloud.githubusercontent.com/assets/7845110/11224728/a6ea9d1a-8d33-11e5-931d-bd2b9d713e4e.png)

**Comment by fehguy** [comment]
you currently do need a url to be passed as well even with the spec object.  This isn't ideal but it is required.

**Comment by franka1** [comment]
Huh. So the url field needs to be there even when it isn't being used? That does seem odd. 

In any case that seems to have fixed exactly what I needed so thank you.

**Comment by fehguy** [comment]
Yes.  I'm just wrapping up a release of swagger-js, and will fix this in swagger-ui, so let's please keep the issue open.  It shouldn't behave this way.

**Comment by franka1** [comment]
In that case, glad I could help!

**Comment by jlennox** [comment]
The documentation (https://github.com/swagger-api/swagger-ui#parameters) still reads: 

> Spec | A JSON object describing the OpenAPI Specification. When used, the url parameter will not be parsed. This is useful for testing manually-generated specifications without hosting them. Works for Swagger 2.0 specs only.

**Comment by mattetti** [comment]
by providing the spec data + a url, the data doesn't seem to load and I'm getting a JS error:

```
index.js:164 Uncaught TypeError: Cannot read property 'swaggerOptions' of undefined
```

**Comment by fehguy** [comment]
Hi, an you please add more details, @mattetti ?

**Comment by mattetti** [comment]
@fehguy:

```
var spec = JSON.parse(data.data);
              window.swaggerUi = new SwaggerUi({
                spec: spec,
                url: "http://petstore.swagger.io/v2/swagger.json",
                dom_id: 'swagger-ui-container'
              });
window.swaggerUi.load();
```

My spec is the parsed version of a json file that loads properly in the demo ui and locally. But when loaded directly it fails and the stack trace is pretty useless.

**Comment by fehguy** [comment]
and if you do a `console.log(spec)` what do you get?

**Comment by mattetti** [comment]
my full spec as a valid object

**Comment by fehguy** [comment]
I just tried locally:

```js
      var spec = {
        swagger: '2.0',
        paths: {
          '/foo': {
            get: {
              responses: {
                description: 'ok'

              }
            }
          }
        }
      }
      window.swaggerUi = new SwaggerUi({
        spec: spec,
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            initOAuth({
              clientId: "your-client-id",
              clientSecret: "your-client-secret-if-required",
              realm: "your-realms",
              appName: "your-app-name",
              scopeSeparator: " ",
              additionalQueryStringParams: {}
            });
          }
// ==> continues
```

must be something wrong with your spec object

![image](https://cloud.githubusercontent.com/assets/249413/19372280/488e8bdc-916f-11e6-850a-ee9f205677f3.png)

**Comment by mattetti** [comment]
```
       var spec = {
        swagger: '2.0',
        paths: {
          '/foo': {
            get: {
              responses: {
                description: 'ok'

              }
            }
          }
        }
      }
      window.swaggerUi = new SwaggerUi({
        spec: spec,
        url: 'http://petstore.swagger.io/v2/swagger.json',
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            initOAuth({
              clientId: "your-client-id",
              clientSecret: "your-client-secret-if-required",
              realm: "your-realms",
              appName: "your-app-name",
              scopeSeparator: " ",
              additionalQueryStringParams: {}
            });
      }}});

      window.swaggerUi.load();
```

Finished Loading Resource Information. Rendering Swagger UI...

index.js:164Uncaught TypeError: Cannot read property 'swaggerOptions' of undefinedaddResource @ index.js:164render @ index.js:164render @ index.js:164options.success @ index.js:164SwaggerClient.buildFromSpec @ operation.js:422Resolver.finish @ index.js:230Resolver.resolve @ index.js:137(anonymous function) @ operation.js:163
online.swagger.io/validator?url=http://petstore.swagger.io/v2/swagger.json:1 GET file://online.swagger.io/validator?url=http://petstore.swagger.io/v2/swagger.json net::ERR_FILE_NOT_FOUND

**Comment by mattetti** [comment]
Here is the code live: https://bitbucket-swaggerui.firebaseapp.com/index.1.html

**Comment by fehguy** [comment]
Well it is strange, if you replace your backbone version with this:

```
  <script src='lib/backbone-min.js' type='text/javascript'></script>
```

it works fine.

**Comment by mattetti** [comment]
o_O I went back to the minimized version and it just works. At least I'm unblocked, thanks a lot.

**Comment by fehguy** [comment]
So weird.  I wish I could tell you more what the cause of that is...
