### ISSUE TITLE
Upgrade Handlebars dependency to 4.x?

### ISSUE THREAD

**Issue by brylie** [swagger-api/swagger-ui#1761]
What are the plans to upgrade the Handlebars from 2.x to 4.x?

**Comment by brylie** [comment]
Related #1757

**Comment by fehguy** [comment]
Looking for a contribution to do this.  I haven't heard a bunch of requests to do so.

**Comment by fehguy** [comment]
let's close this out as #1757 covers it.

**Comment by noirbizarre** [comment]
It seems to me that ugrading to Handlebars 4.x is only a subtask of creating a Meteor Package.
It's not the same complexity, the Handlebars upgrade can be delivered alone.
I depends on Handlebars 4.x but I don't intend to use the meteor package.

Why upgrade ? Templates compiled with Handlebars runtime 4.x are not compatible with previous versions.
There is some security issue with previous versions: https://nodesecurity.io/advisories/handlebars_quoteless-attributes-in-templates-can-lead-to-xss

Is it possible to upgrade to Handlebars 4.x regardless of the meteor package progress ?
It will profit to other that depends on it (including the meteor package) and will allow to test both separately, and to have a cleaner merge for Handlebars 4.x.
