### ISSUE TITLE
Replace jQuery BBQ with a maintained package?

### ISSUE THREAD

**Issue by brylie** [swagger-api/swagger-ui#1762]
It seems like the jQuery BBQ package has little or [no ongoing maintenance](https://github.com/cowboy/jquery-bbq/commits/master) and [may be abandoned](https://github.com/cowboy/jquery-bbq/issues/49). What are the plans or thoughts regarding replacing the jQuery BBQ package with a more modern and well maintained package?

E.g. [Query String](https://github.com/sindresorhus/query-string) may be useful.

**Comment by brylie** [comment]
Related: #1757

**Comment by fehguy** [comment]
closing as covered in #1757

**Comment by brylie** [comment]
jQuery BBQ is still causing our project some trouble. Basically, it is conflicting with more up-to-date versions of jQuery, on which our project depends. I believe this original issue should be re-opened, since the outdated and unmaintained jQuery BBQ project is the underlying issue.

**Comment by brylie** [comment]
Related issue(s):

- [Running Swagger UI with jQuery No-conflict](https://github.com/swagger-api/swagger-ui/issues/1647)

**Comment by webron** [comment]
We're not going to reopen it because it's not going to change for version 2.x. Version 3.x which was just released does not depend on jquery.

**Comment by brylie** [comment]
> Version 3.x which was just released

How may we acccess the 3.x release? It is not listed in the Github releases page:

https://github.com/swagger-api/swagger-ui/releases

**Comment by webron** [comment]
It's the master branch, and available in the tags as well.
