### ISSUE TITLE
Overrides sort order

### ISSUE THREAD

**Issue by nastassiar** [swagger-api/swagger-ui#1763]
I am trying to use OrderActionGroupsBy in Swashbuckle to sort my api, but because swagger ui defaults to alphabetic ordering it is overwriting my sorting.

https://github.com/domaindrivendev/Swashbuckle/issues/567

Based off of the documentation it seems like it should default to server order:

> Apply a sort to the API/tags list. It can be 'alpha' (sort by name) or a function (see 
> Array.prototype.sort() to know how sort function works). Default is the order returned by the server 
> unchanged.

Is it intentional that the default apisSorter is alpha?

**Comment by webron** [comment]
Yes, it is. Many language integrations don't offer a way to fine control the order and then it becomes a mess. An alphabetical order makes it at least easier to follow.

**Comment by urbanthings** [comment]
This doesn't seem right - the ReadMe for swagger-ui says, for parameter apisSorter:

"Default is the order returned by the server unchanged."

...yet, as mentioned above, if you omit the apisSorter parameter, the default seems to be alpha-sort.

Is this an error in the ReadMe or an error in swagger-ui?

**Comment by webron** [comment]
@urbanthings - I *believe* that's part of the documentation that wasn't updated with the move to 2.0.
