### ISSUE TITLE
Less/CSS specificity, uniformity and maintainability

### ISSUE THREAD

**Issue by verpixelt** [swagger-api/swagger-ui#1765]
I had a brief look into the code base, especially the Less files. The level of specificity, usage of IDs and general usage of CSS rules is astonishing(frightening). It would be a multi step process to fix all the files and make them more maintainable but it would pay off in the end.
I've opened the first PR to tackle these issues: https://github.com/swagger-api/swagger-ui/pull/1756
I'm willing to continue this journey if you welcome such changes/improvements.

**Comment by fehguy** [comment]
merged #1756, please open any other issues/prs as you see fit.
