### ISSUE TITLE
(bump) renaming api_key

### ISSUE THREAD

**Issue by Luthien-in-edhil** [swagger-api/swagger-ui#1766]
in this issue https://github.com/swagger-api/swagger-ui/issues/36 it was asked if it is possible to rename the api_key to something different. The issue was resolved by implementing this possibility, with an explanation how to use it here: https://github.com/wordnik/swagger-ui#api-key-parameter.
However, I cannot find anything about it there, nor anywhere else - that page anchor neither exists any longer.
There is much talking about how to move the **api_key** to the header, but nothing at all about how to change its name. Was that feature maybe dropped again?

My problem is that our services accept an authorisation parameter named **wskey**.

I don't know exactly how this works (I'm not that familiar with front-end coding, alas) but I'm guessing that the swagger .js code pre-populates any field labeled **api_key** with whatever has been filled in the header text area labeled **api_key**. 
I certainly would like to get that working, but I can't think of any way to achieve that apart from renaming the appropriate variables in the index.html and the javascript files, but that'd be a bit of a dirty hack. 

Is there an easier way to achieve this? Or am I overlooking something obvious?

thanks in advance,
Lúthien

**Comment by webron** [comment]
Just open the index.html file and replace `api_key` with `wskey` at all places.

**Comment by ponelat** [comment]
@Luthien-in-edhil ,  currently there isn't a way to rename `api_key` without changing code... even if it is slight, as @webron suggests.

However there is a plan to include dynamic security... such that the UI would look at the swagger.json file and generate a simple form for the security layers found therein.
@webron am I correct in guessing, this is most likely the next major feature in swagger-ui?

**Comment by webron** [comment]
There's a plan, I can't say it's the next major feature though. There's a ticket about it.

**Comment by webron** [comment]
This should no longer be an issue.
