### ISSUE TITLE
Curl output does not reflect choosen response content type

### ISSUE THREAD

**Issue by zuphilip** [swagger-api/swagger-ui#1767]
As part of the output of an action in the swagger-ui there is also a line for curl with an accept header. But this accept header is always `application/json` regardless of which options one has choosen for the response content type.

For example in [your demo](http://petstore.swagger.io/#/) the [GET pet/findByStatus](http://petstore.swagger.io/#!/pet/findPetsByStatus), choose application/xml as Response Content Type and available as status. Then the shown Curl prompt is
```
curl -X GET --header "Accept: application/json" "http://petstore.swagger.io/v2/pet/findByStatus?status=available"
```

See also

![swagger-curl](https://cloud.githubusercontent.com/assets/5199995/11271322/6c7691b4-8ec5-11e5-9770-ff2658d81db0.jpg)

The same seems to be the case for the `Request Headers` if it is shown. We encountered the error first here https://github.com/infolis/infolis-web/issues/21

**Comment by webron** [comment]
Which version of swagger-ui do you use?

**Comment by webron** [comment]
Nevermind. Now I see what you mean. It should have been resolved already, probably a regression.
https://github.com/swagger-api/swagger-js/issues/504

**Comment by zuphilip** [comment]
Okay. I am looking forward for a fix.
