### ISSUE TITLE
Definition reference in a parameter reference is not resolved.

### ISSUE THREAD

**Issue by DougHaigh** [swagger-api/swagger-ui#1771]
If I reference a parameter that itself references a definition, the UI does not display the definition information - it just displays the definition URL.

Example:

``` JSON

{
    "swagger": "2.0",

    "info":
    {
        "version": "1.0.0",
        "title": "Ref Demo",
        "description": "This demonstrates references to parameter that have references to definitions do not display properly in the swagger UI."
    },

    "parameters":
    {
        "ObjectParm":
        {
            "name": "object information",
            "in": "body",
            "description": "The object's information",
            "required": true,
            "schema": { "$ref": "#/definitions/Object" }
        }
    },

    "paths":
    {
        "/parms":
        {
            "post":
            {
                "summary": "Create the object",
                "description": "Create a new object",
                "parameters":
                [
                    { "$ref": "#/parameters/ObjectParm" }
                ],

                "responses":
                {
                    "201":
                    {
                        "description": "Created",
                        "schema":      { "$ref": "#/definitions/Object" }
                    },

                    "400": { "description": "Bad request"},
                    "401": { "description": "Not authenticated" },
                    "403": { "description": "Forbidden - the user does not have permission to complete this request" }
                }
            }
        }
    },

    "definitions":
    {
        "Object":
        {
            "properties":
            {
                "name":
                {
                    "type": "string",
                    "description": "localizable server name"
                }
            }
        }
    }
}
```

The UI looks like

![image](https://cloud.githubusercontent.com/assets/15949661/11313907/c4ad6a30-8fae-11e5-93c5-64ab91bcea0a.png)

but the editor gets it correct

![image](https://cloud.githubusercontent.com/assets/15949661/11313949/1e559dd2-8faf-11e5-92ed-9261a3da1f43.png)

**Comment by webron** [comment]
Try updating the version of your swagger-ui. The sample you provided loads well with the latest master.

**Comment by DougHaigh** [comment]
Thanks for your response. I was using the "online demo" link on the swagger UI page. Is that the latest version? Is the UI version displayed anywhere so I can check the UI version for our company's UI?

**Comment by DavidBiesack** [comment]
This loads but if you expand the operation, you can see the "Data Type" for the parameters (body) for the POST operation is incorrect - it shows the only URL of the schema ....#/definitions/Object

I put the swagger in a GitHub gist and tried it in [the Swagger UI demo on swagger.io](http://petstore.swagger.io/?url=https://gist.githubusercontent.com/DavidBiesack/9cda3bb134216b4b0530/raw/f11373951b79e724aa803bb7125a96f45b545fb3/swagger-issue-issues-1771.json) where you can see this.

**Comment by fehguy** [comment]
@DougHaigh master in swagger-ui is the current development, while the online demo typically is the latest release.

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
