### ISSUE TITLE
Entering Basic Authentication credentials does not work

### ISSUE THREAD

**Issue by prantlf** [swagger-api/swagger-ui#1777]
I would like to use `SwaggerClient.PasswordAuthorization` by specifying a "basicAuth" authorization type in an API declaration.

I realized that there are a couple of problems with the implementation:

* Values of username and password cannot be read because the selectors are wrong: #1774
* Clicking on the toggling icon quickly shows and then hides again the authentication form: #1775
* When using the schema version 1.2, authorizations of the type "basicAuth" got lost during the conversion to the 2.0 version, which is used internally in the swagger-ui: #1776

----
The authentication form is not styled and does not show up by default.  I made it appear by adding its parent element and providing icon and styling:

```html
<div class="auth_main_container"></div>
```

The fixes above and customizing the `index.html` helped me to get the Basic Authentication working.  Is it the scenario supposed to be used only with the HTML customizatoin?

**Comment by prantlf** [comment]
The schema version conversion problem is in sources of swagger-js.  I opened [a new PR there,](https://github.com/swagger-api/swagger-js/pull/639).

**Comment by fehguy** [comment]
Please try master which has #2014 to address this.
