### ISSUE TITLE
Response definitions fail to parse

### ISSUE THREAD

**Issue by drewwells** [swagger-api/swagger-ui#1782]
This json works on editor.swagger.io, but fails to render responses in swagger-ui.

https://gist.githubusercontent.com/drewwells/f6bad58215d15ab0d8b4/raw/3de3cd9c1120b5418d7d0034aec4140450561a21/gist.json

Relevant piece

```
...
"definitions": {
    "Booking": {
      "type": "object",
      "x-go-package": "bitbucket.org/fitkiq/api/gist"
    },
    "BookingResponse": {
      "description": "BookingResponse represents a scheduled appointment",
      "type": "object",
      "required": [
        "booking"
      ],
      "properties": {
        "booking": {
          "description": "Booking struct\n\nin: body",
          "x-go-name": "Booking",
          "$ref": "#/definitions/Booking"
        }
      },
      "x-go-package": "bitbucket.org/fitkiq/api/gist"
    }
  },
  "responses": {
    "BookingResponse": {
      "description": "BookingResponse represents a scheduled appointment",
      "schema": {
        "$ref": "#/definitions/BookingResponse"
      }
    }
  }
...
```

**Comment by drewwells** [comment]
Probably a duplicate of https://github.com/swagger-api/swagger-ui/issues/1634

**Comment by webron** [comment]
Which version do you use? Looks fine in master.

**Comment by drewwells** [comment]
petstore.swagger.io, I did a gulp on master and tried that too. It seemed to leave off the response models there too

**Comment by webron** [comment]
Yeah, I can confirm it doesn't work on the pet store, but it is already fixed on master. You can either pick that up now or wait for the next release.

**Comment by drewwells** [comment]
Hmm, I tried against the dist folder. It appears `gulp` actually does a git checkout. In `swagger-ui.js` it says version 2.1.4. I'm still seeing an error where the response should be.

json: https://gist.githubusercontent.com/drewwells/f6bad58215d15ab0d8b4/raw/af9b6eaa60d79642f36f49dc8055ed65b8b463b7/gist.json

<img width="811" alt="screen shot 2015-11-25 at 6 51 16 pm" src="https://cloud.githubusercontent.com/assets/239123/11412695/968bb0da-93a5-11e5-8df1-50e4c1f1d6a0.png">

**Comment by webron** [comment]
Ah yes, that's the difference between a self contained spec and a hosted one. There should be an open ticket about it already (not the one you referenced, iirc). I'll look for it later.

**Comment by webron** [comment]
This should no longer be an issue.
