### ISSUE TITLE
Add new param type: json

### ISSUE THREAD

**Issue by schickling** [swagger-api/swagger-ui#1784]
**Note: Moved to https://github.com/go-swagger/go-swagger/issues/140**

It would be nice to have an additional param type like `json` which just takes a go struct and uses it as a default JSON `body`.

Here is an example:

```go
type LoginPayload struct {
	Email    string `json:"email"`
	UserName string `json:"user_name"`
	// Required: true
	Password string `json:"password"`
}

// swagger:parameters login
type ImplicitWrapperStruct struct {
	// In: body
	Body PersonLoginPayload
}
```

**Comment by webron** [comment]
That's pretty much like a body parameter of type object where the operation `consumes` `application/json`.

**Comment by schickling** [comment]
Sorry I somehow managed to create this issue for the wrong repo :cactus:
