### ISSUE TITLE
Is it possible to use custom values in the Model Schema?

### ISSUE THREAD

**Issue by thabemmz** [swagger-api/swagger-ui#1787]
In our current Swagger implementation, we have a model that takes a custom formatted `date` field (format `yyyyMM`), configured like this (the example below is simplified):
```
{
  "definitions": {
    "yearMonthDate": {
      "type": "string",
      "pattern": "^[0-9]{4}(0[1-9]|1[012])$"
    },
    "model": {
      "type": "object",
      "properties": {
        "month": {
          "type": "string",
          "format": "yearMonthDate"
        }
      }
    }
  }
}
```

This model is used in a `PUT` request and should be given to the body. When using the Swagger-UI, the Model Schema displays:
```
{
  "month": "string"
}
```

We'd like to display the date format here instead of `"string"`. I've already tried defining the `default` property on the `month` property as `yyyyMM`, but this feels wrong, since its not a default value for that field.

Using `type: "date"` is not an option, since the API does not support the `yyyy-MM-dd` format.

Is there any possibility to add custom values to properties in Swagger-UI?

**Comment by webron** [comment]
The easy solution would be a hack, using either `default` or `example`. There's no straightforward way to override it as it's not really intended for such cases. We should have probably displayed the pattern in that case (which may already appear on hover).

**Comment by thabemmz** [comment]
Thanks, I wasn't aware of the `example` property. Putting the pattern in there feels less hackish then to put it in the `default`, though `yyyyMM` is not an example input, but a readable format of the date.

Don't know if displaying `pattern` would be a good solution, since `pattern` is a RegEx in this case, that does not make things clearer for endusers. I'd opt for displaying the `format` in such cases - it's up to the developer how to name this `format` property, so he has the ability to name it in a readable way.

**Comment by thabemmz** [comment]
Yeah you're right, but my point was that a regex isn't gonna make things any clearer for endusers I think. I did implement things with `example`, so that's working like a charm :). Thanks for your help.

**Comment by webron** [comment]
Oh yeah, regex definitely doesn't help readability ;)

Are we good to close the issue?

**Comment by thabemmz** [comment]
Yeah fine by me, I got my question answered. It's up to you whether you'd like to create a separate issue for displaying the `format` / `pattern` instead of the `type`, I'd be willing to spend some time to implement it.

**Comment by webron** [comment]
On top, not instead ;) I believe the are a few issues about adding more of the information available in the UI, the trick is to do it in a way that doesn't make the thing look more crowded as it is (part of why the hover option was used in the first place).

And we always appreciate PRs. If you have the time to do it and ideas as to how, please go ahead.
