### ISSUE TITLE
Cannot find how to show basic info

### ISSUE THREAD

**Issue by JeroenDeDauw** [swagger-api/swagger-ui#1788]
I have a rather complex response model for some things that requires some explanation beyond the names of the fields and their types. I cannot find how to display such explanation. Take the below schema (which is far simpler than the most complex thing I have):

``` json
"schema": {
    "type": "object",
    "required": [ "value", "type" ],
    "properties": {
        "value": {
            "type": "mixed",
            "example": "Los Angeles"
        },
        "type": {
            "type": "string",
            "example": "string"
        },
        "values": {
            "type": "array",
            "items": {
                "type": "mixed"
            },
            "minItems": 2,
            "example": [
                "Los Angeles",
                "Madrid",
                "Istanbul"
            ]
        }
    }
}
```

This is within

``` json
"responses": {
    "200": {
```

The "value" and "values" fields needs extra explanation. Adding a description field on the same level as the schema has no effect, same goes for adding a description directly within the schema.

To make matters worse, things such as "minItems" are not getting shown at all. Am I missing something, or is it simply not possible to convey the contract of this format via swagger UI?

This is using swagger UI 2.1.4.

![insufficient](https://cloud.githubusercontent.com/assets/146040/11471983/89213b0a-9769-11e5-83aa-dfb4c836954f.jpg)

**Comment by webron** [comment]
Model descriptions are currently not being displayed - https://github.com/swagger-api/swagger-ui/issues/1430.

The `minItems` *should* appear on hover, but I'm not sure about that property specifically.

Also, there's no type `mixed` so that's not gonna work.

**Comment by JeroenDeDauw** [comment]
> The minItems should appear on hover, but I'm not sure about that property specifically.

Ah, indeed. That's very much not obvious though. Most people are not noticing they can click on model, much less that they can hover over the type of the field there to get some more info.

> Also, there's no type mixed so that's not gonna work.

Yeah, I found that out by the validator yelling at me. Searched a bit and did not find any way to specify the type of this field, so just put "object", which is incorrect, there for now. Is there really no way to do this?

**Comment by webron** [comment]
Can't say with regard to the type as I don't know what you're trying to describe.

**Comment by JeroenDeDauw** [comment]
I'm trying to describe the response model for the value attribute. This model is not fixed. It can be any of a set of models, based on the type of the value. My schema itself does not know what the type will be where, as this is user defined. It can only know which types are supported by the system and what their format is.

**Comment by webron** [comment]
In that case, describing as an object is pretty much all you can do.

**Comment by JeroenDeDauw** [comment]
Thing is, it's wrong to do so, as a scalar is not an object, and it can be a scalar.

**Comment by webron** [comment]
That's why I asked what it can be - you said it's a any of a set of models. Models are objects, not scalar.
If you need it to be *anything*, don't set a type at all. That's equivalent to saying anything goes.
