### ISSUE TITLE
Not able to set the header before clicking on the 'Try it out!' button

### ISSUE THREAD

**Issue by jjorgen** [swagger-api/swagger-ui#1790]
I am having trouble updating the 'Authorization' header information before the user clicks the 'Try it out!' button.
After I discovered that this was not getting updated. I tried to see if I was able to update any header or add a query parameter when the user clicks the 'Try it out!' button.

I found that I was unable to make any changes to either header or add query parameter. I have tried the following variations:
var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", key, "header");
var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", key, "header");
var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", key, "query");

I have here enclosed the index.html file (I have renamed the extension to .txt since html is not a supported extension for attachments.)

[index.txt](https://github.com/swagger-api/swagger-ui/files/47852/index.txt)

**Comment by webron** [comment]
I replied to your google group question. Let's try to keep the communication in one place to avoid duplication.
