### ISSUE TITLE
Slashes in $ref do not work following RFC 6901

### ISSUE THREAD

**Issue by josefguenther** [swagger-api/swagger-ui#1793]
According to RFC 6901 Section 3, forward slashes in references should be encoded as ~1.

See: https://tools.ietf.org/html/rfc6901

In my use case, I have two files.

**main.yaml**

```
paths:
  /account/token:
    $ref: 'account.yaml#/account~1token'
```

**account.yaml**

```
account/token:
  type: object
  ....
account/mine:
  type: object
  ....
```

The forward slashes in the pointer should be encoded as ~1, since referencing 'account/token' will look for an element named 'account' with a child named 'token'.

Currently it does not work...

**Comment by webron** [comment]
This should be fixed in the new UI.
