### ISSUE TITLE
Sections won't collapse

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-ui#1794]
We're trying to integrate swagger-ui into our existing site. Things display correctly, but we cannot get the show/hide to collapse. It tries, and then just keeps it expanded. I don't get any errors, so I'm having a hard time figuring out how to debug this. Any suggestions?

**Comment by webron** [comment]
No errors in the web console?

**Comment by jaydreyer** [comment]
No. No errors. It collapses and then quickly expands again. If we're using jquery 1.11 on the site, but swagger-ui is using 1.8, could that cause the issue? I tried removing 1.8 from the lib folder in dist, but that just lead to an error with jquery.ba-bbq. I might be going down the wrong path with that, anyway.

**Comment by webron** [comment]
Not sure really. Can you try to load it with http://petstore.swagger.io? The collapsing seems to work well there.

**Comment by jaydreyer** [comment]
Yeah, just using the as-is index.html on its own works fine. It's when we try to integrate that into a site that we're running into problems.

**Comment by fehguy** [comment]
You're going to have to use a compatible jQuery version.  We can't support all of them, and it's a requirement for the project.

**Comment by elerocks** [comment]
I've encountered the same problem when integrating swagger to wordpress.
For anyone else wondering: problem was caused by including print.css into webpage (At first I haven't noticed that print.css is for media='print'). So just include bootstrap, typography and screen, that's it.

**Comment by jaydreyer** [comment]
Wow. Thanks, @elerocks ! That worked for me. Glad I came back and read to the bottom a year later!
