### ISSUE TITLE
Swagger-UI does not maintain positioning for SwaggerSpec 1.2 produced documents

### ISSUE THREAD

**Issue by smarkwell** [swagger-api/swagger-ui#1796]
On 2.1.4 and 2.1.1 (do not know when the issue was introduced), Swagger-UI, when no apisSorter is specified or explicitly specifying a function to perform no sort such as

function(a,b){return -1;} 

position is not maintained from the original api-docs produced spec.

From research this is because response.paths is an object and not an array, thus loosing it's position information from the original JSON response.

**Comment by webron** [comment]
Yup, I don't really see that changing.

**Comment by smarkwell** [comment]
The work around I created locally (in javascript, not coffeescript), was to store the original position in OperationGroup by brute forcing it by matching against the oldSwaggerObject.  Unfortunately I doubt this code is pull request suitable as currently implemented.

 var oldPos = -1;
          
          for(var i=0; i < self.oldSwaggerObject.apis.length ; i++){
        	  if(self.oldSwaggerObject.apis[i].description == operationGroup.description &&
        			  self.oldSwaggerObject.apis[i].path == '/' + tag){
        		  oldPos = i;
        		  break;
        	  }
        	  
          }

**Comment by fehguy** [comment]
If we switch to use a Map instead of Object for storing the keys, we can rely on insertion order and therefore support the sort function.  I'd suggest sending a PR along those lines.
