### ISSUE TITLE
Empty form parameters are sent as "undefined".

### ISSUE THREAD

**Issue by Timmmm** [swagger-api/swagger-ui#180]
If you have a POST request with some optional parameters of the type `form`, any that you don't fill in a value for will be sent as "undefined".

The problem is in OperationView.coffee, lines 103 and 113. I would suggest that these parameters should be omitted unless values are typed in. The other alternative is to send blanks.

I believe the lines should be changed to:

103:

```
       if (param.paramType is 'body' or 'form') and param.name isnt 'file' and map[param.name]?
```

and

113:

```
    for param in @model.parameters
      if map[param.name]?
        bodyParam.append(param.name, map[param.name])
```

Or whatever (I don't know CoffeeScript).

**Comment by mikevoets** [comment]
Is this an issue again?

**Comment by fehguy** [comment]
Master has the fix, it is not in a release yet.
