### ISSUE TITLE
Add editable header field manually

### ISSUE THREAD

**Issue by jaysoncena** [swagger-api/swagger-ui#1800]
Is there a way to add a custom, editable header field in the UI without it specified in the spec? Similar to #108

We have a custom authorization similar to AWS APIs where the value of a header depends on the hash of the payload.

**Comment by fehguy** [comment]
Yes, there are multiple ways to do this.

1) In the index.html, you have the ability to add Authorizations directly to the underlying javascript library.  See index.html for an example of adding `api_key` to all requests.

2) The underlying swagger-js client supports both `requestInterceptor`s and `responseInterceptor`s.  That lets you take the payload, manipulate it on outbound request (including adding headers based on payload) for _all_ requests.

Please give that a shot, and reopen this if you're having troubles.
