### ISSUE TITLE
`object` type for `formData` parameters.

### ISSUE THREAD

**Issue by vanderlee** [swagger-api/swagger-ui#1803]
I noticed that you can't use an `object` type for `formData` parameters.

Is there any specific reason for this, since it seems quite possible to submit forms with "key-value" pairs array, which would best map to an `object`.

Or is there perhaps another mechanism that enables an author to specify arrays with key-value pairs inside? None of the array collectionFormats seem to support a key-value pairs.

**Comment by webron** [comment]
Yes, there is. This is a spec limitation. For 'regular' formData types you cannot mention the mime type, and so if you mention the type object, there's no way to know how to serialize it (json, xml, yaml, whatever). In future versions, we may support defining the mime type per formData field (only if the top-level mimetype supports it, which is not always the case), and then we may be able to introduce support to objects in formData.

**Comment by fehguy** [comment]
closing as this is not in the spec.  Feel free to work around it by documenting that your formData param, which _is_ type `string` accepts JSON.  And track the issue in the swagger-spec repository.
