### ISSUE TITLE
Slow ui rendering

### ISSUE THREAD

**Issue by okonkwo** [swagger-api/swagger-ui#1804]
Hi!

We have 42 url groups. Average api-docs size is 200k. Unfortunately rendering is slow (about 2 seconds).
Each SwaggerUi.Views.ResourceView is rendering only once (don't see re-rendering overhead).

Options { ignoreGFM: true, ignoreCodeHighlight: true } are present
version: 2.1.1

Thanks for your suggestions.

**Comment by webron** [comment]
You're still on Swagger 1.2? Are you able to upgrade to 2.0?

**Comment by okonkwo** [comment]
Nope,  version is 2.1.1

**Comment by webron** [comment]
That's the version of the UI (which you'd also want to upgrade for performance enhancements). I'm referring to your Swagger spec itself.

**Comment by okonkwo** [comment]
I see "swagger": "2.0" into json

**Comment by webron** [comment]
Can you try upgrading to 2.1.3 or even master and see if the issue persists?

**Comment by okonkwo** [comment]
I think we will try. but difference between versions is very small.

**Comment by fehguy** [comment]
I have looked into speeding things up, and it's not hard. Fortunately the client loads very large specs quickly so there are some simple rendering optimization a that can be done.

**Comment by okonkwo** [comment]
thanks! we are waiting

**Comment by AdamEther** [comment]
Hi!

Are there any updates?

**Comment by webron** [comment]
@AdamEther - have you tried the current master version?

**Comment by webron** [comment]
We've made a lot of performance improvements with 3.0. Please try it out.
