### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by Sintendo** [swagger-api/swagger-ui#1810]
The last stable release is 2.1.3, but since that one has a bug in it causing many XHR requests for $refs, we looked into using a newer version. So we've switched to 2.1.8-M1, thinking that one's newer, but it's actually *older*.

What is/was the rationale behind this versioning scheme?

**Comment by fehguy** [comment]
Milestones were _pre_ releases.   This is not an uncommon practice but apparently confusing in the npm world.  Pretty soon we'll be past the max milestone numbers so the problem should go away, and we won't ever do this again :)
