### ISSUE TITLE
Curl command not output

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-ui#1815]
Using [this swagger definition](http://yabb.herokuapp.com/v2/api-docs), the Curl command will not be output in the response when calling POST /banner

**Comment by webron** [comment]
Do you not see the curl command at all or does using it doesn't produce the response you expect?

**Comment by cbornet** [comment]
I don't see the curl command
![curl](https://cloud.githubusercontent.com/assets/11633333/11788417/3583a8ce-a291-11e5-8dc1-909aa8858591.png)

**Comment by webron** [comment]
Which version? Tested with master and it shows it.

**Comment by cbornet** [comment]
I tested with the online http://petstore.swagger.io

**Comment by cbornet** [comment]
OK. I just tested with latest master. Now the curl command is output but the image is not correctly set in the form data

**Comment by webron** [comment]
Yup, that's true. Can you open a ticket on that on swagger-js? It's not a swagger-ui issue.

**Comment by cbornet** [comment]
OK

**Comment by JavaHelper** [comment]
Can someone please guide here : https://stackoverflow.com/questions/53379440/swagger-not-working-while-doing-crud-operation-through-ui-also-curl-commands-do
