### ISSUE TITLE
Issue to deploy swagger and application on different host

### ISSUE THREAD

**Issue by oshin-talreja** [swagger-api/swagger-ui#1816]
Hi,
My swagger is deployed on tomcat 8080 port and my application is deployed on different machine with different port.
I made changes in swagger.json file to point that host url.
But it is returning no response from server error.
Please guide.

**Comment by maximn** [comment]
Have a look at `CORS Support` in the readme (https://github.com/swagger-api/swagger-ui)

**Comment by webron** [comment]
Thanks @maximn - that's indeed a CORS issue. The direct link to the explanation is https://github.com/swagger-api/swagger-ui#cors-support. Please follow the guidelines and it would solve your issue.
