### ISSUE TITLE
circular dependency in swagger 1.2  

### ISSUE THREAD

**Issue by NarendraNallabelli** [swagger-api/swagger-ui#1819]
We are using swagger-play 1.3.7 . (play framework  2.2.1 , swagger 1.2)

my model classes are look like this

public class TypeA {
	TypeB b;
       TypeB c;
      }

public class TypeB {
	TypeA a;
        CustomBigdecimal bigdecimal;
        Map<String, Object> additionalmaps;
}

public class TypeC {
	TypeB b;
     }

1. how  to overcome this circular dependency in swagger 1.2   ?  - swagger UI is hanging 
2. how to convert wrapper CustomBigdecimal to Bigdecimal/string ? - result undefined 
3. how do i represent Maps..-- swagger UI is hanging

**Comment by webron** [comment]
@NarendraNallabelli - cross posting the same question across multiple projects and venues isn't helpful and causes us to waste time. I'm sure you can appreciate that it's not helpful to either side. Please take that under consideration.
