### ISSUE TITLE
Formatting issue using local json

### ISSUE THREAD

**Issue by illukarl23** [swagger-api/swagger-ui#1820]
Hi,
I used the Swagger Editor to write my documentation.
when I use the spec property in index.html, the formatting of my swagger.json gets not interpreted and therefore not shown in my Browser (new lines, bold characters, etc.).

What is the reason and what is the solution?

Thanks in advance.

**Comment by webron** [comment]
Can you give a few specific examples? Can you share your swagger.json?

**Comment by illukarl23** [comment]
I used the Master dist. Swagger is Version 2.0.
When i use new Lines in the Swagger Editor I get a JSON with "\n" for new lines.
On the Editor all is fine, when I copy the json in index.html, i get something like this:
Example Description:
	var spec = {
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Example API",
        "description": "This is an exmple for Github, now I want a new Line, \nThanks.",
        "termsOfService": "***",
        "contact": {
            "name": "N/A"
        },
        "license": {
            "name": "****",
            "url": "*****"
        }
    },
.
.
In Browser:
This is an example for Github, now I want a new Line, Thanks
I'm sorry i can't show the real whole json, but I think its understandable.

**Comment by illukarl23** [comment]
Sorry, but you can close this, it was my fault.
I got 2 Versions of SwaggerUi, and somehow I interchanged them.
Its working now.
