### ISSUE TITLE
Swagger-UI not displaying properly on Safari

### ISSUE THREAD

**Issue by habovh** [swagger-api/swagger-ui#1821]
There are a lot of problems using Swagger UI on Safari over untrusted HTTPS (maybe unrelated to issue).

The best is to see the following screenshot:
![capture d ecran 2015-12-17 a 10 39 12](https://cloud.githubusercontent.com/assets/4186230/11866321/ac67004c-a4aa-11e5-8d30-a1b2fe89b140.png)

See that the text is really displayed in a weird manner. I'm not sure whether this has something to do with HTTPS but everything is working fine on Chrome or Firefox.
Seen that before?

**Comment by habovh** [comment]
# Update 1
Apparently the issue is with the `"Droid sans"` font. When I hack the CSS on the fly with the developer console in Safari, and remove `"Droid sans"` from the font-stack (leaving only `sans-serif` in the font stack), everything displays properly.

Having discovered this, I tried to have a look at the font resources that were loaded, and I could find the issue:

> Droid sans regular
![capture d ecran 2015-12-17 a 10 48 12](https://cloud.githubusercontent.com/assets/4186230/11866492/c7bc4b3a-a4ab-11e5-9822-64d99250aaba.png)

> Droid sans bold
![capture d ecran 2015-12-17 a 10 48 20](https://cloud.githubusercontent.com/assets/4186230/11866494/cb39b3f6-a4ab-11e5-9f18-8ac2b8c87f23.png)

Now that's why Safari is struggling to display the page properly, except the titles that are... In bold.

Any idea why this is happening right now?

**Comment by fehguy** [comment]
There were some corrupt don't files in a few of the builds. Have you tried from master?

**Comment by habovh** [comment]
Updated using `master`, now works great, it was because of the font corruption. Closing the issue, thanks for you tip!

**Comment by dilipkrish** [comment]
Not sure what Im doing wrong.. still seeing the issue in master.

![swagger_ui](https://cloud.githubusercontent.com/assets/73257/12653009/2585514e-c5b3-11e5-9b38-e59707a5b5b7.jpg)

I just got latest master
- did an gulp clean
- gulp 
- gulp serve 

that :point_up: is what I see

**Comment by fehguy** [comment]
Aye!  Yes i'm getting that on a clean version of safari.  Will report back in a few.

**Comment by fehguy** [comment]
please try now @dilipkrish

**Comment by dilipkrish** [comment]
:+1: works now! thanks!

**Comment by fehguy** [comment]
thanks for reporting that.  I hope this doesn't revert again.

**Comment by ponelat** [comment]
In case it ever (heaven forbid) does happen again, here is a md5sum digest, to help with debugging...
9e94decf013d3e2c9adcc0b97cc5ce44  src/main/html/fonts/DroidSans.ttf
9e94decf013d3e2c9adcc0b97cc5ce44  dist/fonts/DroidSans.ttf

**Comment by tomjohnson1492** [comment]
I experienced the same issue. I just removed these two fonts from the fonts folder, and now the display is fine.

**Comment by ponelat** [comment]
This has been resolved, @tomjohnson1492 please try pulling the latest from master branch.
