### ISSUE TITLE
Switching off HTML encoding for a value 

### ISSUE THREAD

**Issue by j-m-baker** [swagger-api/swagger-ui#1824]
Hello,

I have a REST API signature:

``` java
  @POST
  @Path("/post/{server}/{template:.*}")
```

And as you can see, the template accepts multiple paths, hence the following URL is valid:

http://target:8080/post/myserver/path/to/thing, where template matches path/to/thing.

Yet in the Swagger UI, the Template value is URL encoded when Swagger generates the URL, ie

http://target:8080/post/myserver/path%2Fto%2Fthing

How can this be avoided?

John

**Comment by webron** [comment]
Swagger doesn't support that kind of templating, so it can't be avoided.

**Comment by j-m-baker** [comment]
Can this issue be marked as something to be included in the next spec of the revision? A "multiple path part" control could be created as a neat UI control, with a +/- button to add/remove fields, which are joined with /?

**Comment by webron** [comment]
There are [several tickets](https://github.com/swagger-api/swagger-spec/search?q=6570&type=Issues) related to it already.
