### ISSUE TITLE
Integer Response Type not shown on swagger-ui 

### ISSUE THREAD

**Issue by chenjianjx** [swagger-api/swagger-ui#1827]
my swagger json: 

````
"responses": {
  "200": {
      "description": "success",
     "schema": {
            "type": "integer",
             "format": "int64"
}
},
````

On swagger ui page,  it says 

```` Response Class (Status 200)  ````

But that's all.

**Comment by yewton** [comment]
This seems to be as same as https://github.com/swagger-api/swagger-ui/issues/1760

**Comment by webron** [comment]
Yup, same issue.
