### ISSUE TITLE
Add description to Query parameters

### ISSUE THREAD

**Issue by Rameeshchandran** [swagger-api/swagger-ui#1828]
I am having a REST service (GET method) as : 
@RequestMapping(value = "value", params = {"param1", "param2"}, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)

While generating the documents the description column for the params are empty.

Provide me with a solution that will add descriptions to the params ( @QueryParam annotation is not giving this result).

Note:
It should be possible to generate documentation like:
Type            Name    Description            Required     Schema  Default
-----           -----   ------------           ---------    ------  ---------
QueryParameter  param1  Description of param1  true         String    test

**Comment by shashi0905** [comment]
You can try @Api annotation on your implementer class with description attribute, something like this -
@Api(value="some name" description="description of your api")

**Comment by Rameeshchandran** [comment]
This is not related with the implementer class.
This is documenting the service definition. I have documented the service using @ApiOperation
@ApiOperation(value = "service summary", 	notes="Service description.")

Also the path variables are documented using@ApiParam as : 
@ApiParam(value=pathParam description.") @PathVariable String pathParam


My GET service is like:

@ApiOperation(value = "service summary", 	notes="Service description.")
@RequestMapping(value = "value", params = {"param1", "param2"}, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public String getData(@ApiParam(value=pathParam description.") @PathVariable String pathParam, @ApiParam(value="requestParam description") @RequestParam("requestParam") String requestParam){
----------------
}

Here the description is missing  for param1 and param2 provide with params = {"param1", "param2"}

**Comment by webron** [comment]
That looks like a spec generation issue rather than a display issue. Please reopen it on the generating project.

**Comment by vaylo** [comment]
`@ApiParam` should need to support at class level as a common part of the URI(which could contain pathParam) to class level. It is nightmare to add the common pathParam to every method.

**Comment by josejdlp** [comment]
Thanks i used @ApiParam(value="requestParam description") to specific a description, now swagger indicate the description
