### ISSUE TITLE
Swagger responds with No response from server

### ISSUE THREAD

**Issue by ARAtIntBitTech** [swagger-api/swagger-ui#1829]
I have added swagger-ui to the project and it returns content when the project is executed on the local host. But when I deploy it on a server and then try to hit an api, it responds like this

{
  "error": "no response from server"
}

When I execute the same CURL command on the server, it works fine. It responds with correct data.

http://dev1.intbittech.com/ImageRXWebServices-1/imagerxdoc/index.html

**Comment by shashi0905** [comment]
Can you ping and check if the server is accessible over network or not ?

**Comment by ARAtIntBitTech** [comment]
The server is accessible over the network. I can run curl commands from my local machine and the server returns data. Likewise the browser also returns data.

**Comment by fehguy** [comment]
You probably have a CORS issue.  In your browser, open the network tab and look for errors.

**Comment by ARAtIntBitTech** [comment]
I had to the change a few settings in nginx.. Seems to be working now

**Comment by rollandmed** [comment]
Hi @ARaqeeb  ,

I have the same issue, it seems to be working for you after some changes on nginx conf file . Could you please share your conf file after update ?

Thanks.

**Comment by osumac24** [comment]
@ARaqeeb Can you share your solution?
