### ISSUE TITLE
[v2.0.46] Can't use Swagger for "apis" collection

### ISSUE THREAD

**Issue by simhamed** [swagger-api/swagger-ui#1830]
Hello :)
I have an API (among others) called "apis" to list all the users subscribed to a specific API.
I noticed that on Swagger 2.0.46, I can't call my collection "apis".

Here's an extract : 

<pre>
"paths": {
        "/apis": {
            "post":{
                "tags": ["apis"],
                "summary": "Creates a new API",
                "description": "Creates a new API",
                "operationId": "createApi",
                "parameters": [
                    {
                        "name": "apiName",
                        "in": "formData",
                        "description": "The api's name",
                        "required": true,
                        "type": "string",
                        "paramType": "body",
                        "allowMultiple": false
                    },
</pre>

If I replace "tags": ["apis"] with "tags": ["appis"], it works and I can see my POST method!
Else, I get a "Fetching ressource" message without having anything!

Anyone can help me please ?
Is there any restriction ? and any solution to this problem ?
Thank you!!

**Comment by simhamed** [comment]
My bad, just found this : 
https://github.com/swagger-api/swagger-js/issues/405
So "apis" was added to the reservedClientTags list... makes sense!

I made it work by adding a space at the end => ["apis "]
If you have anything better to make it work, I'm opened to your solution!

**Comment by fehguy** [comment]
Hi, you should be able to use your API as-is but you'll need to grab a newer version.  Please see about updating your swagger ui instance.
