### ISSUE TITLE
Multiple apis in a single swagger-ui

### ISSUE THREAD

**Issue by daw3rd** [swagger-api/swagger-ui#1831]
I have two separate sets of services in a single web app (tomcat, java, jersey, etc).  The services are exposed as separate servlets in web.xml.  As such I have separate base paths.  Therein lies the rub I suppose. I have two swagger-ui/dist trees, one for each base path.  But once the first access is made to either dist tree, the swagger-ui always presents the swagger.json from the first tree and won't switch to the other. I tried using a single web.xml entry specifying both paths in the basepath parameter, but this did not help.  Any help/suggestions, much appreciated.  

BTW, I saw a similar post but it was closed as out of scope.  Googling shows many people looking for this capability.  I hope you'll consider a way to support this sort of thing if it not currently.

**Comment by fehguy** [comment]
Hi, can you please open this in swagger-core?

**Comment by daw3rd** [comment]
You sure to push things off your plate quickly :)
