### ISSUE TITLE
Add header fields in the UI

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-ui#1833]
I can see that in the doc and code there is a way to add some custom HTTP headers for a request. However, there is no way to do it directly in the browser (for a classical user for example). Can you add input fields in the UI to handle this case ?
i mean, for each possible request, add a way to add custom headers as a couple ("key","value").

**Comment by fehguy** [comment]
Yes, it's easy.  The UI would define the inputs as "in: header" and the parameters can be specified in the standard UI form flow.
