### ISSUE TITLE
FIle upload is not working

### ISSUE THREAD

**Issue by nayandas88** [swagger-api/swagger-ui#1834]
Hi,

I am using following sbt for swagger UI-
"com.wordnik" % "swagger-play2_2.10" % "1.3.3",

File uploading is not working form swagger page.File is getting stored as 0 kb.
But same is working from postman.
Anyone please suggest what is the issue?

**Comment by fehguy** [comment]
Hi, please update your server--this is a very old version.  Take a look at the samples here:

https://github.com/swagger-api/swagger-samples

Also ensure you're using a recent version of swagger-ui.

**Comment by nayandas88** [comment]
Hi,

Thank you for your help.
samples does not contain any java play project.
If I used "io.swagger" % "swagger-play2_2.11" % "1.5.0", then I am facing issue with play dependency conflict in play 2.2.1.
Would it be possible to  suggest play version and corresponding swagger play version?

**Comment by fehguy** [comment]
Here is the play compatibility chart:

https://github.com/swagger-api/swagger-play#compatibility

**Comment by nayandas88** [comment]
Thank you.
Please confirm if the upload issue will be resolved with swagger play jar-
"com.wordnik" % "swagger-play2_2.10" % "1.3.7" as I am using play version 2.2.
