### ISSUE TITLE
Error with security policy between Swagger UI and Swagger Editor

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-ui#1835]
I don't really know where to put this issue since it concern both "Swagger-Editor" and "Swagger-UI".

In the Swagger definition, in the editor, I need to specify the security. For example:
```
swagger: '2.0'
info:
  title: Some API
  version: 1.0.0
host: localhost:8080
schemes:
  - http
securityDefinitions:
  authentication:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` 
...
```

And in the methods (paths:), I also need to specify that the security is necessary:
```
paths:
  /tenants:
    get:
      security:
       - authentication: []
      summary: Get all tenants
...
```

In the editor, everything works fine, I can render a valid HTML document and I can test my methods, the server answer well.

However, in the Swagger UI, using the "swagger.json" downloaded from the Swagger Editor, this is not working.
I have added the Authorization header in the index.html file with the line specified in the Swagger UI doc, but the header is not correctly added to the request (curl/http).
To solve the problem, I must remove from the "swagger.json" file the security bloc in the method
```
paths:
  /tenants:
    get:
      summary: Get all tenants
...
```
And then, it's working.

I don't think it's normal and I think a "swagger.json" file should be working correctly on both Swagger UI and Swagger Editor.
I think it's important to keep the security bloc in the method definition (because maybe some request don't require an authentication ?). That's why I am reporting this issue in the Swagger UI project.

**Comment by fehguy** [comment]
They are two different projects, and it's possible that the behavior isn't consistent with the specification itself.  Please share the whole specification so we can help.

**Comment by hiveship** [comment]
Can't reproduce it now, I close the issue and will re-open it later if needed.
