### ISSUE TITLE
Feature Request: Catalogue of Definitions

### ISSUE THREAD

**Issue by t11n** [swagger-api/swagger-ui#1837]
# Feature request for a "Catalogue of Definitions"

Hi there,
I would like to place a feature request for a "Catalogue of Definitions".
## Reason 1

In our project, we have a polymorphic rest resource. Let's name it /pets here. When you want to get or create pets, you have to provide a concrete pet, as a cat, a dog or a fish. Now, we are not able to specify multiple response types via the swagger docs, so we have to state the response of /pets is an (abstract) pet. No user knows there is a cat, a dog or a fish, though. Therefore the user needs some kind of catalogue of definitions where to look this up.
## Reason 2

Even if we do provide a concrete data structure for an endpoint, this data structure may use other, shared structures inside it, like pet accessories (related objects and so on). With the current implementation of the GUI, these "sub-structures" would be shown in place several times. This is fine for now, but I wonder if developers would not prefer a unique catalogue that holds all data structures. The REST UI can always link to the catalogue.
## Reason 3

Reason 3 is not really a reason, but a more of a "good reason to do it". All definitions are provided by the the swagger-docs. So it would probably be fairly easy to visualise a catalogue from there. Also, definitions that are present in the docs, but are not referenced anywhere directly in the API will not appear in the GUI at all at present. As it is the case with our "pet accessories". An (abstract) pet does not have any accessories, but a cat and a dog does, and the fish does also have different ones. Even if specified as definitions, these accessories will not show up in the GUI, as they are not used by the (abstract) pet.
## Current Workaround for our company

For our project, we are actually in deep need of this feature, but nobody on our side is familiar enough with JavaScript to extend swagger-ui this way. So we are going to implement this feature in PHP and link the catalogue as external reference. But maybe this sounds appealing to others and somebody has the resource to extend swagger ui in this, or a similar way.

Thanks,
Thomas

**Comment by webron** [comment]
This is done in 3.0.
