### ISSUE TITLE
Incorrect parsing when compared to Swagger editor

### ISSUE THREAD

**Issue by Growiel** [swagger-api/swagger-ui#1838]
Hello,

I'm using the lastest version of swagger-ui and the live version of swagg-editor and I find myself with different results when using the two.

My file is working perfectly as expected in the editor but it looks like the UI si not following some of my $ref.

Because Swagger doesn't support aliases, I came up with a workaround using a custom "x-paths-definitions" where I setup my Operation objects and then $ref them where needed in paths.

Here's the file (slimed down to the minimums):

```
swagger: '2.0'
info:
  title: Example
  description: Example
  version: 1.0.0
host: 'example.com'
basePath: /
schemes:
  - http
produces:
  - application/json
paths:
  /rest_auth:
    $ref: '#/x-paths-definitions/auth_index'
  /rest_auth/login:
    post:
      $ref: '#/x-paths-definitions/auth_index/post'
x-paths-definitions:
  auth_index:
    post:
      tags:
        - Auth
      summary: Logs the user in
      description: |
        Tests a pair of user_id and password to log the user in.
        <br /><br />
        Aliases: /rest_auth/login, /rest_auth
      parameters:
        - name: body
          in: body
          description: The user_id and password of the user trying to login.
          required: true
          schema:
            required:
              - user_id
              - password
            properties:
              user_id:
                type: string
              password:
                type: string
            type: object
      responses:
        '200':
          description: User object of the newly logged-in user + user_cd + blog_cd
          schema:
            properties:
              user:
                type: object
              user_cd:
                type: integer
              blog_cd:
                type: integer
            type: object
```

Here's an image of what is rendering in the Editor:
![Editor rendering](http://i.imgur.com/rHEm0eP.png)
This is what I want: two different endpoints (/rest_auth and /rest_auth/login) with the exact same POST documentation, because they are indeed the same one.

Here's what Swagger-UI is doing:
![UIrendering](http://i.imgur.com/X65atIv.png)
The endpoint using the $ref is now empty. 

This is, to say the least, disappointing as I spent about two days on my API documentation and when I finally decided to show a first version to a colleague, the UI screwed up a lot of my work...

If it's an not an issue and I'm doing something wrong, please let me know.

**Comment by fehguy** [comment]
what version of swagger-ui are you using?  What is the URL that you're hosting your specification on?

**Comment by Growiel** [comment]
I'm using the latest master of swagger-ui, I just re-downloaded and tested again for good mesure about 1 minute ago.

I just uploaded the specification here: http://www.growiel.com/swagger/swagger.json . I made sure it's accessible from http://petstore.swagger.io/ .

The online validor did gave me some errors that the editor didn't... Who to trust ?

**Comment by webron** [comment]
I'm afraid that's not a valid definition. A specific HTTP verb must be an Operation Object and operation objects cannot be references - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operationObject. So... trust the online validator.

**Comment by Growiel** [comment]
Should I move this to Swagger-editor then ? 
If it's not valid I'm okay with it but the editor should really return the error then.

Any ideas how I can achieve what I want to with the current spec ?

In my example I removed it, but my `x-paths-definitions/auth_index` Path Object also has a "GET" and "PUT" Operation objects. I do not want those copied into `/rest_auth/login` because this is only a duplicate of the POST method from the index, not the GET and PUT.

**Comment by webron** [comment]
You can reference a collection of operations, but that's pretty much it.

If you'd like to open an issue on the editor that it doesn't throw an error when it should, that would be great. Would definitely help us track the issue and get it resolved.

**Comment by Growiel** [comment]
Sadly that makes Swagger unusable to me. I do not want to update every aliases of my documentation when I need to update the method.

I don't really understand why every object isn't able to be a $ref, or why $ref doesn't just work like an include of some sort, since the validation is done on the final compiled JSON anyways...

I'll open the issue in the editor and then go search for a replacement. Sigh.

**Comment by webron** [comment]
Fair enough, Swagger doesn't aim to solve all problems and there are certainly use cases it may not fit.
