### ISSUE TITLE
Image upload doesn't work

### ISSUE THREAD

**Issue by getvictor** [swagger-api/swagger-ui#1846]
/pet/{petId}/uploadImage isn't working when file is specified. Instead of uploading the actual file, the request contains:

`file=%5Bobject%20File%5D`

Using latest master https://github.com/swagger-api/swagger-ui/tree/d919a5e7799f86cbea3c8b194e153d7b7530ac5f

![capture](https://cloud.githubusercontent.com/assets/2685025/12076038/74d22fc8-b15f-11e5-9bf4-61587f778f1c.png)

**Comment by fehguy** [comment]
This has been fixed by https://github.com/swagger-api/swagger-ui/commit/d032bd2d8f9c617dfac0510f7238580c6191d2e8
