### ISSUE TITLE
Where is the "Try it Out" button for "OPTIONS" http request type?

### ISSUE THREAD

**Issue by danilobreda** [swagger-api/swagger-ui#1847]
The button "Try it Out" does not shows if i have a "OPTIONS" type of request.

![swaggerbug](https://cloud.githubusercontent.com/assets/14843499/12090286/a56dde7c-b2d4-11e5-8e88-8e4293f84183.png)

**Comment by fehguy** [comment]
Please check your 'supportedSubmitMethods' when initializing swagger ui

**Comment by danilobreda** [comment]
Im using the http://petstore.swagger.io/, and yes, it does not have it.
```
supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
```
if somebody add 'options' on this, can be a good thing.

The real problem is from the Swashbuckle - Swagger for WebApi, im getting a error on it, but its not part of this issue anymore.

Thanks for support.

**Comment by webron** [comment]
By default we don't enable it, and it's not likely to change. The idea of it is that it's meant to be customizable so just change the configuration in your copy and you're done.
