### ISSUE TITLE
Problem receiving file after POST method

### ISSUE THREAD

**Issue by glederrey** [swagger-api/swagger-ui#1848]
Hi,

I have a problem when I try to get back a file after a POST method using Swagger-UI and the Spring-MVC server generated using Swagger Codegen. 

My function consists of posting a picture to the server, then I do some stuff with this picture and finally I send it back.. In order to send it back, I'm doing a redirect.. This works perfectly with the GET methods but it doesn't work with the POST functions.. 

![screenshot](https://cloud.githubusercontent.com/assets/13273462/12095105/dfa254f0-b30c-11e5-95c0-d7510201e028.png)

The screenshot I added shows you what's going on.. So, the POST method is working and redirects to another function which is a GET.. (I also tried with a 307 redirect and a POST method to display the picture, doesn't work either..) 
The problem seems to come from Swagger-UI because at the end, it does a third call which is a GET on the original POST method.. 

Do you know how I can get rid of this problem?? 

Thank you in advance.

P.S.: I saw that the issue #1652 is similar.. I tried the suggested fix but it did not worked.. 
P.S.: I also tried to return a type file.. But I always get a 406 error.. This problem surely concerns Swagger Codegen.. So if you think that it's better to use this solution, I'll ask the guys working on Swagger Codegen.

**Comment by glederrey** [comment]
Hi again,

I come back, because I still have this problem even if you changed some things.. 

From what I saw, you're not doing the GET request to load the picture.. Which is good.. =)

But, now, I cannot upload a picture in Swagger-UI anymore (even with the GET method that was working).. You'll find a screenshot attached.. 

By the way, it's working properly using the browser or using a client library (Python) generated by Swagger-Codegen.. 

Thanks in advance
![screenshot](https://cloud.githubusercontent.com/assets/13273462/12715292/d1842e56-c8d9-11e5-946f-cc8776f96df6.png)

**Comment by fehguy** [comment]
This should be fixed by https://github.com/swagger-api/swagger-ui/tree/4bdaeba797224bde922f3cefe55a6807428437a8, please try it out and give feedback on #2404

**Comment by fehguy** [comment]
Fixed by https://github.com/swagger-api/swagger-ui/commit/656808b20cffcca4f6daff1741c4685d70be5757
