### ISSUE TITLE
Display order of parameters vs. responses in swagger-ui

### ISSUE THREAD

**Issue by ebullient** [swagger-api/swagger-ui#1850]
The swagger-editor is consistent with placement of parameters before response data. This makes sense to me as a developer as I have to code the request to get the response that I'm after.

The swagger-ui shows them in inverse order, the difference between /stores/order in the full petstore example in the editor is easier to read and understand than http://petstore.swagger.io/#!/store/placeOrder where it is easy to initially confuse the return value for the input parameter.

For the delete operation: http://petstore.swagger.io/#!/store/deleteOrder which has no response body, you see the order of operation, parameters, result.  It is much more consistent if the API is always shown in this order. Operation (top line), Parameters (including data types if present), Response (value and messages).

**Comment by maxlath** [comment]
If anyone is still interested, this can easily be done by editing the [operation template](https://github.com/swagger-api/swagger-ui/blob/master/src/main/template/operation.handlebars) and move the `response-class` block below `form.sandbox`, which gives [this commit](https://github.com/inventaire/swagger-ui/blob/544d7b6863c55e67675be6ca5a604b8921a78cc2/src/main/template/operation.handlebars).

**Comment by webron** [comment]
This has changed in 3.0.
