### ISSUE TITLE
IE9 does not load petstore.swagger.io without developer tools

### ISSUE THREAD

**Issue by mjhaller** [swagger-api/swagger-ui#1851]
This is basically a duplicate of https://github.com/swagger-api/swagger-ui/issues/207.  In my local swagger-ui instance, I have tried to remove all references to console.log, and still see the problem.

I've tried pointing ie9 to petstore.swagger.io and it has the same problem.  I also tried opening the latest `index.html` that is in github and it has the exact same problem.  Opening developer tools (even just once while ie9 is open) will make the endpoint links appear and work.

I can see that there are already fixes for ie9, so possibly this is a regression.  Maybe one of the dependencies?

I noticed that swagger-ui `README.md` mentions supporting ie8 and greater.  This problem only shows up on IE9, which is a (sad) requirement for my project.

**Comment by webron** [comment]
We no longer support IE9.

**Comment by mjhaller** [comment]
Good move!
