### ISSUE TITLE
Try-It-Out > response headers missing

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#1854]
I only see a small subset of response headers reported by this feature. It'd be nice if all of them are there, as now my response description doesn't match the live example. Browser is reporting these headers present, so it's got to be that swagger-ui JS code is not parsing them all.

Having request headers displayed would be nice also, but I guess that's covered by issue #1501.

Thanks!

**Comment by fehguy** [comment]
Are you talking about the raw response headers from your actual request?  It seems that the underlying super-agent library is hiding some of the response headers.

**Comment by hlubovac** [comment]
Maybe we should forget this. I realized that the missing-headers behavior happens only when the target API is  hosted at "localhost". Maybe there is something special about that that both the browser and that library are doing.

For example, for the same API code base, swagger-ui displays this via "localhost:port":
```javascript
{
  "pragma": "no-cache",
  "content-type": "application/json",
  "cache-control": "no-cache",
  "expires": "-1"
}
```
... and this via a non-localhost hostname (internal no-dot name)
{
  "pragma": "no-cache",
  "date": "Thu, 07 Jan 2016 00:45:56 GMT",
  "x-paging-total-items": "5",
  "x-paging-page-size": "20",
  "server": "Microsoft-IIS/7.5",
  "x-powered-by": "ASP.NET",
  "paging-links": "<http://server/api/resources?meta=false&links=false&limit=20&page=1>; rel=\"first\"; title=\"First Page\", <http://server/api/resources?meta=false&links=false&limit=20&page=1>; rel=\"current\"; title=\"Current Page\", <http://server/api/resources?meta=false&links=false&limit=20&page=1>; rel=\"last\"; title=\"Last Page\"",
  "content-type": "application/json",
  "cache-control": "no-cache",
  "x-paging-current-page": "1",
  "x-paging-total-pages": "1",
  "content-length": "3886",
  "expires": "-1"
}
```

Maybe it's something else that's different and I'm not seeing it. Regardless, it works as expected at the location that I need, so maybe there's no need to waste time on this. Sorry about if you wasted any so far.

Thank you.
