### ISSUE TITLE
"url" querystring parameter to default Swagger spec no longer working in Swagger UI 2.1.4

### ISSUE THREAD

**Issue by cabbonizio** [swagger-api/swagger-ui#1856]
Today we upgraded our in-house Swagger UI to version 2.1.4.   The first thing I noticed was opening the UI with a url parameter (used to default to a Swagger spec so user doesn't have to enter in textbox.    

For instance,
http://swagger.host.com?url=http://swagger.host.com/documentation/swagger.json

This used to work with 2.0.24 but doesn't seem to work with 2.1.4.    I can still manually take the URL hosting the Swagger json and plug into the textbox to get the Swagger spec in the UI though.   

This was a very important feature as we provide hyperlinks for the consumers of our services with the "url" querystring parameter already filled out to make it easier to get there.

**Comment by webron** [comment]
Seems to work for me...?

**Comment by cabbonizio** [comment]
Strange, we just downgraded to 2.1.3 and it began working again.   I had my admin re-upgrade to 2.1.4 and it broke again.   This is all I got at this point unfortunately.

**Comment by cabbonizio** [comment]
@webron I also noticed, although probably unrelated, an error in the console related to the new jsonEditor that was introduced with 2.1.4.  These were the only 2 oddities I saw with this version so far.   We're back to 2.1.3 now probably should have let 2.1.4 bake-in a bit :)

**Comment by webron** [comment]
Sorry for the trouble. We'll have to investigate it.

**Comment by fehguy** [comment]
@cabbonizio you'll need to add another line to your index.html:

https://github.com/swagger-api/swagger-ui/blob/master/src/main/html/index.html#L23

**Comment by cabbonizio** [comment]
@fehguy and @webron, for some reason when my admin pulled down from master it didn't include that reference for the jsonEditor javascript include.   I tested it locally and things look better.  He must have inadvertently overwritten the index.html file since it seems to be in there.  I'm having him re-push (via Docker) swagger-ui from master and hopefully the issue with the "url" parameter is fixed.  Once I verify I will close this one.  Many thanks for your help.

**Comment by cabbonizio** [comment]
Problem resolved, closing this one.   Thanks for your help!
