### ISSUE TITLE
Incorrect, CORS-related error message displayed for invalid JSON in single-host scenario

### ISSUE THREAD

**Issue by davidwcarlson** [swagger-api/swagger-ui#1858]
# Thanks
I am setting up swagger/swagger-ui for the first time so I apologize in advance if I've missed something somewhere, this seems like an awesome tool.  Thanks!

### Set up
This issue is reproducible when serving the API, swagger definition file and the swagger UI files from the same host using either swagger UI versions 2.1.4 and 2.1.3

My swagger definition file (named `portal-api-doc.json`) consists of the following:

```
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "Simple API"
    },
    "paths": {
        "/": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
            }
        }
    }
}
```

In the course of debugging, I forced my Response headers to include the cors information, even for the HTTP GET which should be unnecessary:

###### Request Headers
```
GET /publicApi/portal/v1/portal-api-doc.json HTTP/1.1
Host: localhost:8080
```
###### Response Headers
```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH, OPTIONS
Access-Control-Allow-Headers: Content-Type, api_key, Authorization
Access-Control-Allow-Credentials: true
Content-Encoding: gzip
Content-Type: application/json
Content-Length: 131
```

### Observed
When attempting to load the swagger UI with this setup, I am presented with the message:
>  **Can't read from server. It may not have the appropriate access-control-origin settings.**

### Expected
The underlying problem is actually the trailing comma in the swagger definition (after the `responses` object).  The definition file is valid javascript but is invalid JSON.  The swagger online editor renders this invalid JSON successfully and reports it as valid.  Removing this comma to produce valid JSON allows the swagger UI to render correctly.

The user should be presented with a message similar to:
> **The swagger definition is not valid JSON, please check the syntax**

### Justification
It's unclear how often this issue is affecting users, but judging by the volume of questions related to CORS issues, any false positives are going to confuse and discourage adoption by convincing a busy developer that their infrastructure is somehow 'incompatible' with swagger.

**Comment by webron** [comment]
Thanks, that's a known issue. We have multiple tickets opened on this. Can't find the core issue, but #1508 is an example for it. Really appreciate the long explanation but will close this in favor of the other tickets.
