### ISSUE TITLE
Distinguish Required/Optional JSON POST/PUT Parameters

### ISSUE THREAD

**Issue by sibblegp** [swagger-api/swagger-ui#186]
Right now, in the JSON model spec for POST/PUT parameters, there is no way to tell which are required and which are optional (at least when looking at the model schema).

I suggest color coding those that are optional vs. required.  Thoughts?

**Comment by milind-pawar** [comment]
If you need to identify required fields of a json, just see this:
Account:
    type: object
    required: [accountName]
    properties:
      accountName:
        type: string
      description:
        type: string  

So this means a "accountName" field of json is a required field.
