### ISSUE TITLE
response schema default doesn't work

### ISSUE THREAD

**Issue by PavelPolyakov** [swagger-api/swagger-ui#1872]
Hi,

Here is my response schema:
```
      responses:
        200:
          description: boolean
          schema:
            type: boolean
            default: false
```

Which results to this:
![image](https://cloud.githubusercontent.com/assets/839290/12329497/eefb38a0-bae0-11e5-90f6-92555f9959bc.png)

As you see - there is no response schema from the one side, and the default value is not taken into attention from the other side.

Do you think it's a bug, or I am doing something wrong?

Regards,

**Comment by PavelPolyakov** [comment]
ah, sorry, that code is generated by swagger-server, not swagger-ui :)

you are great, then!

**Comment by PavelPolyakov** [comment]
the only question left is the response description in the swagger ui, for some reason the ```boolean``` declaration was not taken into attention.

Regards,

**Comment by fehguy** [comment]
Hmm I do think this is a bug in the UI, although it's a little weird.

The response content type of `application/json` should actually forbid you sending a primitive value as a response.  `true` is not valid JSON...

**Comment by PavelPolyakov** [comment]
I think ```true``` is a valid json:
![image](https://cloud.githubusercontent.com/assets/839290/12349474/3943a674-bb70-11e5-9998-78551056b77e.png)

**Comment by PavelPolyakov** [comment]
For those who could be interested.

```true``` is indeed not a valid JSON response (validator: https://jsonformatter.curiousconcept.com/) .

In case you should not return anything important in your query, you can just response with ```204``` code.
