### ISSUE TITLE
OAuth Security Definitions seem to be disabled

### ISSUE THREAD

**Issue by dzuluaga** [swagger-api/swagger-ui#1873]
Resources show a switch to indicate that they're secured. However, the switch doesn't do anything when I click on it. See it here. Am I missing anything?

![swagger_ui](https://cloud.githubusercontent.com/assets/1755383/12334886/4772e4cc-bab1-11e5-8ac2-6a31bf46b21c.png)

**Comment by fehguy** [comment]
You need to enable the oauth2 support in your index.html:

https://github.com/swagger-api/swagger-ui/blob/bfa4a221cb6cdaa620a78083886f8b6bda8db948/dist/index.html#L51-L58

**Comment by dzuluaga** [comment]
Got it. It worked after a few tweaks to authorizationUrl and the parameters mentioned above with a new app on Instagram.

**Comment by fehguy** [comment]
Great, thanks for following up.
