### ISSUE TITLE
Access token is not being included in requests

### ISSUE THREAD

**Issue by dzuluaga** [swagger-api/swagger-ui#1875]
hello, the access_token doesn't seem to be included in any of the requests. Therefore, the API returns 404 responses. Am I missing anything? Swagger instagram attached.
[swagger_instagram.yaml.txt](https://github.com/swagger-api/swagger-ui/files/91244/swagger_instagram.yaml.txt)

![swagger_ui](https://cloud.githubusercontent.com/assets/1755383/12342962/5626f91c-bae4-11e5-9caa-7fbb14746ea4.png)

**Comment by webron** [comment]
You're talking specifically about the curl command?

**Comment by dzuluaga** [comment]
Including the request. Even if I inspect the AJAX call generated in the browser, it doesn't contain the token:

```
curl 'https://api.instagram.com/v1/users/test' -H 'Origin: http://localhost:8080' \
-H 'Accept-Encoding: gzip, deflate, sdch' \
-H 'Accept-Language: en-US,en;q=0.8,es;q=0.6' \
-H 'Accept: application/json' -H 'Referer: http://localhost:8080/' \
-H 'Connection: keep-alive' --compressed
```

**Comment by webron** [comment]
And this is using master?

**Comment by dzuluaga** [comment]
Correct. I've just recloned to replicate the issue and make sure any of my changes to idnex.html are affecting it.

**Comment by webron** [comment]
Well then, congratulations. You've found a bug and you get :cookie: for it!

**Comment by webron** [comment]
@bodnia Please have a look at this one, we should have handled it a long time ago.
@dzuluaga - sorry for the delay.

**Comment by bodnia** [comment]
@dzuluaga sorry for late response. Could you please try latest master (with building the project with `gulp`) and updating node_modules (swagger-js submodule) and let us know the result?
Thank you in advance!

**Comment by dzuluaga** [comment]
Thanks Anna. Will do. Let me get back to you.

On Mon, Jun 20, 2016 at 12:05 PM, Anna <notifications@github.com> wrote:

> @dzuluaga <https://github.com/dzuluaga> sorry for late response. Could
> you please try latest master (with building the project with gulp) and
> updating node_modules (swagger-js submodule) and let us know the result?
> Thank you in advance!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/swagger-api/swagger-ui/issues/1875#issuecomment-227237915>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABrI9xttZ3zSFpEjuC--lMQAKXpjYeaKks5qNuRmgaJpZM4HFZqV>
> .
>



-- 
Diego Zuluaga | apigee <http://www.apigee.com/> | m: +1.415.299.9983 | twitter
@dzuluaga <http://twitter.com/dzuluaga> @apigee <https://twitter.com/apigee>
| skype dzuluaga | *Apigee Community <http://community.apigee.com/>* for
answers, ideas and support!
"First do it, then do it right, then do it better - this is my mantra for
successfully getting things done. It's all about the iteration."

**Comment by bodnia** [comment]
@dzuluaga could you please clarify if you still experiencing the issue or this may be closed?

**Comment by bodnia** [comment]
@dzuluaga any updates on it? thanks!

**Comment by dzuluaga** [comment]
Thanks @bodnia for following up. I apologize, I haven't been able to look at this. I need to clear my schedule. If someone has cycles to test steps above in the image, then it should be good to go. I promise to review it as soon as I have a chance.

**Comment by bodnia** [comment]
@dzuluaga could you please confirm this is working for you? Thank you!
