### ISSUE TITLE
File names submitted by a mulit-part form is not url encoded

### ISSUE THREAD

**Issue by chenjianjx** [swagger-api/swagger-ui#1876]
If I upload a file with swagger-ui to post a multi-part form,  the file name is not url-encoded.  As a result, non-ascii characters will be sent and parsed as 'Content-Disposition' header value on the server side, which normally will get garbage code. 

My example: 

```
------WebKitFormBoundaryexGzzGYbE1VW0UIM
Content-Disposition: form-data; name="file"; filename="中国人民万岁.XLS"
Content-Type: application/octet-stream


------WebKitFormBoundaryexGzzGYbE1VW0UIM--
```

According to http rfc, headers should contain only ascii characters.

**Comment by webron** [comment]
This should work properly in 3.0.
