### ISSUE TITLE
Ignores charset of Produces Annotation in Accept header

### ISSUE THREAD

**Issue by carstenlaengerer** [swagger-api/swagger-ui#1877]
REST WS with charset in the Produce annotations result in wrong swagger.json. The charset is simple ignored.

@Produces("text/plain;charset=UTF-8") results to "produces" : [ "text/plain" ] in the swagger.json.

Hence, Calling the the REST WS by swagger result in HTTP 406

**Comment by fehguy** [comment]
This looks like a swagger-core issue, not swagger-ui.  Please open a ticket [there](https://github.com/swagger-api/swagger-core/issues)
