### ISSUE TITLE
definition refs are not processed correctly

### ISSUE THREAD

**Issue by PavelPolyakov** [swagger-api/swagger-ui#1878]
Hi,

I'm trying to separate my swagger definition using `$ref` option of the specification.

Here, I have prepared the example:
https://github.com/PavelPolyakov/swagger-ui-refs

In the file [index.yaml](https://github.com/PavelPolyakov/swagger-ui-refs/blob/master/index.yaml) I include `paths` and `definitions`:

```
swagger: "2.0"
info:
  title: Customers API
  description: Customers API
  version: "1.0.0"
host: localhost:3000
schemes:
  - http
  - https
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
paths:
# customers section
  /customers:
    $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
```

And, in the [path ref](https://github.com/PavelPolyakov/swagger-ui-refs/blob/master/paths/index.yaml), later, I refer the `NewCustomer` definition:
![image](https://cloud.githubusercontent.com/assets/839290/12358267/a97ab766-bbac-11e5-9456-522927553590.png)

In the swagger ui it results to this:
![image](https://cloud.githubusercontent.com/assets/839290/12358281/c194a9e2-bbac-11e5-82c9-f402f02fe99f.png)

If I refer the `NewCustomer` data structure directly, it would not be an issue anymore:
![image](https://cloud.githubusercontent.com/assets/839290/12358347/11b7c7b0-bbad-11e5-9402-17039c23aa81.png)
but it doesn't surprise me :), because it's completely different way of referencing.

What I want to ask - should the initial `$ref` thing work? I think yes.

You can checkout the repository and reproduce the issue yourself, doing the next:

```
npm i
gulp
# open http://localhost:8080/ui in the browser
```

Thanks,

**Comment by fehguy** [comment]
Please remove the `./` in your reference.  That will tell the resolver that the path is relative to the current path location.  So for example, if your definition is here:

```
http://foo.bar.com/baz/swagger.json
```

a relative reference of `"$ref": "path/to/my/file.json#/models/MyModel"` should correctly resolve here:

```
http://foo.bar.com/baz/path/to/my/file.json
```

And in that document locate the MyModel:
```
{
  "models": {
    "MyModel": {
        ...
    }
  }
}
```

IF the URL that you are passing is not to a document like `swagger.json`, it should end with a `/`:

```
http://foo.bar.com/baz/
```

Which the resolver will simply _append_ the path:

```
http://foo.bar.com/baz/path/to/my/file.json
```

**Comment by PavelPolyakov** [comment]
@fehguy 

Thanks for helping me.

However, when I remove the ```./``` it looks the next way:
![image](https://cloud.githubusercontent.com/assets/839290/12363957/14ca016a-bbcc-11e5-8270-5b0b96ebd224.png)

(it looks like it doesn't parse the path, I don't even see such network query, everything ends after ```index.yaml```)

While the ```/paths/index.yaml``` is ok:
![image](https://cloud.githubusercontent.com/assets/839290/12363965/291bdcce-bbcc-11e5-9411-bbbe4ef4c33d.png)


Could you, pleas, be so kind, and check it in my example? Or guide me a bit further :)

Regards,

**Comment by webron** [comment]
@PavelPolyakov - there are a few problems with the way you use the references.

First:

```yaml
definitions:
  $ref: ./definitions/index.yaml
```

is not supported by the spec. You can `$ref` individual definitions, but not the `definitions` as a whole.

Second, in https://github.com/PavelPolyakov/swagger-ui-refs/blob/master/paths/index.yaml, you have:

```yaml
  parameters:
    - name: request
      in: body
      description: customer
      required: true
      schema:
        $ref: '#/definitions/NewCustomer'
```

The ` $ref: '#/definitions/NewCustomer'` is a *local* reference to that file (starting with the `#`), and you have no `/definitions/NewCustomer` defined in that file. The generated URL you see in the output is accurate - it tries to find `/definitions/NewCustomer` under `/paths/index.yaml` and... it can't.

**Comment by PavelPolyakov** [comment]
@webron 

Correct, so that was the question.

Is that possible to somehow reference definitions, which were required in the ```index.yaml```, from the other files. Is that possible to require definitions just once and then reference them?

I thought that it is supported by the standard, isn't it ?

Regards,

**Comment by webron** [comment]
I don't follow your question as all your files are called `index.yaml` so I don't know which refers to what.

I *think* there was an issue on the spec asking to allow referencing from `definitions`, but can't find it right now. Normally, it doesn't make much sense.

If you want to reference definitions from one file to another, you'll always have to have a path URL (whether full or partial). Anything that comes after the `#` is a local reference and must exist in the file itself.

**Comment by PavelPolyakov** [comment]
@webron 

Thanks, so I must ref the filename each time. If I want to use definitions from the file B to the file A.

But, is that possible to somehow hold all the definitions in the one file?
And reference them somehow like this:
```path/to/my/file.json#/models/MyModel``` ?

Because I think it doesn't worked for me as well.

Or it's a rule of thumb - we need to split definitions file by file and reference each file separately.

**Comment by webron** [comment]
You should absolutely be able to have a single file with all your definitions and reference those from all other files. If that doesn't work for you, then it should be resolved. Try writing up an example like you did when first opening this ticket and if it doesn't work, we can use that to investigate the issue further.

**Comment by PavelPolyakov** [comment]
@webron 

Hi, I have updated the example here https://github.com/PavelPolyakov/swagger-ui-refs .


1. Now I reference each definition separately, as you have mentioned that it's not correct to ```$ref``` block as a whole:
```yaml
definitions:
  NewCustomer:
    $ref: /definitions/NewCustomer.yaml
```
2. In the file *paths/index.yaml* I reference ```index.yaml``` file and definition which I'm looking for in particular:
```yaml
schema:
        $ref: /index.yaml#/definitions/NewCustomer
```

All of these results to the next:
![image](https://cloud.githubusercontent.com/assets/839290/12387257/91848fe4-bdcb-11e5-909a-a74fae130e0b.png)

Which is not correct, because the schema reference is absolute, not relative.

Even if I update it to the next:
```yaml
schema:
        $ref: ../index.yaml#/definitions/NewCustomer
```

I will receive the next:
![image](https://cloud.githubusercontent.com/assets/839290/12387319/fd68af4c-bdcb-11e5-9ad0-e71355d6b769.png)

Which is not very correct, because, as I understand we can reference a part of the file.

I suppose, that I can have missed something from the specification and still trying to do something which not goes in a raw with it. But my goal is the same - gather all the definitions in one file (possible by ```$ref```-ing them; be able to refer the definitions from the other files).

Regards,

**Comment by fehguy** [comment]
While I _believe_ that is a legal definition in JSON schema (@webron can comment on that), I know it's not supported in the underlying javascript client.  I suggest opening an issue on [swagger-js](https://github.com/swagger-api/swagger-js/issues) about this specific limitation.

**Comment by webron** [comment]
@PavelPolyakov - what @fehguy said. It looks like there's an issue resolving absolute references. If you change https://github.com/PavelPolyakov/swagger-ui-refs/blob/master/paths/index.yaml#L15 to `../definitions/NewCustomer.yaml` it works as expected.

**Comment by PavelPolyakov** [comment]
@webron 
 
It is correct, and today I do that thing. However, the relative references are worse, because each time you change the file location (put it deeper), you need to change the reference.

So I will use it, of course, but looking forward for the update, where it would be possible to use the absolute paths.

**Comment by webron** [comment]
@PavelPolyakov - well, there are merits for both relative and absolute paths.

As @fehguy suggested, the best way to get this issue resolved is to open a ticket on [swagger-js](https://github.com/swagger-api/swagger-js) because the issue arises from that project and is not really related to swagger-ui.

**Comment by webron** [comment]
Should be resolved.
