### ISSUE TITLE
Feature request: combining JSON schema

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#1879]
Will there be support for displaying complex schema within the UI? Question is about this:
http://spacetelescope.github.io/understanding-json-schema/reference/combining.html

I'm really after finding a way to display inline definitions for properties which may contain different runtime types. For example, I have a situation where an object displayed as:

```
some_resource
{
  some_property(object)
}
```

could, on runtime, be either:

```
some_resource
{
  some_property(another)
}

another
{
  blah(string)
}
```

or:

```
some_resource
{
  some_property(something_else)
}

something_else
{
  blah(int)
}
```

Possibly, this can be solved by defining swagger-json as this:

```
{
    definitions:
    {
        some_resource:
        {
            title: " ",
            type: "object",
            properties:
            {
                some_property:
                {
                    anyOf:
                    [
                        {
                            "$ref": "#/definitions/another",
                            description: "something about {another}"
                        },
                        {
                            "$ref": "#/definitions/something_else",
                            description: "something about {something_else}"
                        }                       
                    [
                }
            }
        },
        another:
        {
            title: " ",
            type: "object",
            properties:
            {
                blah:
                {
                    "type": "string",
                    "description": "something about \"blah\" text"
                }
            }
        },
        something_else:
        {
            title: " ",
            type: "object",
            properties:
            {
                blah:
                {
                    "type": "integer",
                    "format": "int32",
                    "description": "something about \"blah\" number"
                }
            }
        }
    }
}
```

Maybe I have it defined badly, but I'd somehow want this (or similar):

```
some_resource
{
  some_property(another or something_else)
}

another
{
  blah(string)
}

something_else
{
  blah(int)
}
```

Or, is there another solution?

**Comment by webron** [comment]
There's support for `allOf`, there's no support for `oneOf` or `anyOf` as that's not supported by the spec.

**Comment by 4hopp** [comment]
Hello everyone,

same problem here, I need to specify something to either be a string or an object. I understand that the current standard does not support the `oneOf` keyword, but since it probably will be in the specification, version 3.0 (see here: https://github.com/OAI/OpenAPI-Specification/issues/57#issuecomment-239226502) … Would it take much of an effort to support `oneOf` (or `x-oneOf`, as long as it's still 2.0) in Swagger-UI already, at least in an developement version?

Thanks for your time!
Sincerely
Joshua Hopp

**Comment by webron** [comment]
This will be added with support for OAS3.

**Comment by mattdeboard** [comment]
it's not clear to me whether OAS3 will support e.g. `"type": ["string", null]` or if the expectation is that these should not be included in required fields

**Comment by fehguy** [comment]
What you show above is not supported, but what _is_ supported is `oneOf` or `anyOf` to allow different types to be described in a single schema.  `null` is not valid in the schema.

**Comment by mattdeboard** [comment]
Ok, sorry if I'm forcing you to repeat yourself, but just for my own understanding, what you're saying is that Swagger/OAS has no support for optional/maybe/nullable/whatever types, right? No such thing as `"type": null` or `"type": ["string", null]`, yeah? 

If I'm understanding right, is there a way to express this concept in a way that is json-schema compliant?

**Comment by webron** [comment]
@mattdeboard I believe you found the relevant OAS ticket. `null` value support has been added with the `nullable`property.
