### ISSUE TITLE
Feature Request: Display the implicit OAuth2 scope if available

### ISSUE THREAD

**Issue by brycefisher** [swagger-api/swagger-ui#1880]
Full details here: https://github.com/coreos/quay-docs/issues/55 . Issue discovered on Quay docs.

Repeating here:

---

The [API discovery endpoint](https://quay.io/api/v1/discovery) already contains information about which implicit scope is required for each endpoint:

<img width="454" alt="screen shot 2016-01-15 at 9 46 37 am" src="https://cloud.githubusercontent.com/assets/220106/12360487/242ccc1e-bb6d-11e5-8260-cd36d2d6b0e7.png">

However, in the corresponding html shown on [the generated API docs](http://docs.quay.io/api/swagger/#!/tag/listRepoTags) doesn't show the required scope anywhere that I can see.

<img width="786" alt="screen shot 2016-01-15 at 9 49 57 am" src="https://cloud.githubusercontent.com/assets/220106/12360543/81623c16-bb6d-11e5-972b-a8b82ac34e2b.png">

Clicking on the `off` pops up this modal, which displays the scopes required by the Swagger UI to run all of the examples; it does not indicate the minimum scopes required for that API endpoint. See screenshot:

<img width="452" alt="screen shot 2016-01-15 at 2 04 46 pm" src="https://cloud.githubusercontent.com/assets/220106/12366686/836839ce-bb91-11e5-8349-7d37305d7644.png">

It would be nice to list out the scopes somewhere in the html to more easily determine which scopes are necessary to grant to an OAuth application for a specific use case.

**Comment by fehguy** [comment]
@brycefisher it's actually in a _hover_ over the toggle.  Do you see that?

**Comment by brycefisher** [comment]
@fehguy -- thanks for the speedy response! I'm not sure why, but I'm able to see that div. I can see the `display:block` inline style being applied on hover, but I'm unable to see those scopes.

Knowing I can look here is a big improvement for me already (albeit in the inspector). Thanks for that!

What do you think about simply displaying the scopes all the time (not just on hover)?

**Comment by fehguy** [comment]
I'm no designer... but would be happy to if someone can come up with a nice way to do so.  What version of swagger-ui are you on?

**Comment by webron** [comment]
@brycefisher if you have any further thoughts on this, please share, otherwise we should close the ticket.

**Comment by brycefisher** [comment]
Totally! Are you interested in a PR for this change? Or do you not want to make this kind of cosmetic change to the design?

**Comment by webron** [comment]
can you create a mock of what you envision it to look like?

**Comment by brycefisher** [comment]
Sure! Here's the gist of what I'm envisionsing until I can make a better mockup:

-------------------------

## Parameters

Parameter | Value | Description | Parameter Type | Data Type
-------------- | ------- | ---------------- | --------------------- | --------------
repository |  ....    | .... | ... | ... | ...

## Security

Minimum OAUTH2 scope: _repo:read_

## Response Message

HTTP Status Code | Reason | Response Model | Headers
-------------------------- | ---------- | --------------------- | ----------
200 | .... | .... | ... | ...

**Comment by webron** [comment]
Should no longer be an issue with the new UI.
