### ISSUE TITLE
What's the difference for the two function "Request.prototype.end" and "this.on ('end', ...) in the function Request(method, url)" in swagger-ui.js

### ISSUE THREAD

**Issue by LouisZou** [swagger-api/swagger-ui#1887]
I write a local swagger definition and test it .
I found there is a strange flow for it. when I click the "Try it out", the requst flow will call the function name "Request.prototype.end" 
after "   r.end(function (err, res) {".

But if I use the swagger.json from swagger.io. the flow will be : 
this.on('end', function(){ in the function "function Request(method, url) {"
after "   r.end(function (err, res) {".

what's the difference for them and why the flow is different for the two json files?

**Comment by webron** [comment]
No longer relevant in 3.X.
