### ISSUE TITLE
Is it possible to render Response ReasonPhrase ?

### ISSUE THREAD

**Issue by all4Git** [swagger-api/swagger-ui#1890]
Hi,

I use Swashbuckle with my .NET web api projet.
I added a Filter to my web api, to authorize only https requests, not http ones.
When an http request is sent, the response is 403, with this additionnal ReasonPhrase : "HTTPS is required". But when I call an operation through SwaggerUI, I can see the 403 in the "Response code" section, but the ReasonPhrase appears nowhere (there is no "Response reason" section).
When I call directly the operation with its URL, I can see the 403 and the reason phrase.
As 403 is also used for other forbidden reasons, I would have liked to specify the ReasonPhrase for each case, to help client to see what the problem is. I think it would be something useful for the client.
Is there a way to add the ResponsePhrase in SwaggerUI, when rendering a response ?

Thanks.

**Comment by webron** [comment]
If it's part of the *spec* it should be rendered. If it's not part of the spec, then that's an issue with Swashbuckle, not the UI.
