### ISSUE TITLE
Display All Cases about Business Error.

### ISSUE THREAD

**Issue by wjc133** [swagger-api/swagger-ui#1895]
our team define the response like this:

```
{
    code:123,
    message: "success",
    data:[
        {
            id:xxx,
            xxx:xxx,
            ...
        },
        ...
    ]
}
```

We use 'code' field to represent  various business error. So I want to display all cases in swagger-ui. Specially when the code is the correct one, I want it to show the structure of data. What should I do for this?

**Comment by webron** [comment]
You would just structure it as an object. Any explanation of what a code means would come in the description of the object (or the response).
