### ISSUE TITLE
refs with the same filename are parsed only once

### ISSUE THREAD

**Issue by PavelPolyakov** [swagger-api/swagger-ui#1898]
Hi,

Another swagger-ui (or swagger-js, I don't know how to check whose issue is that) issue.

Here is the repository with the issue reproduction:
https://github.com/PavelPolyakov/swagger-ui-refs-same-filename-issue

Here is the yaml:

``` yaml
paths:
  /a:
    get:
      summary: Method A
      description: Method A
      operationId: getA
      tags:
        - API
      responses:
        200:
          schema:
            $ref: /folderA/enum.yaml
  /b:
    get:
      summary: Method B
      description: Method B
      operationId: getB
      tags:
        - API
      responses:
        200:
          schema:
            $ref: /folderB/enum.yaml
```

folderA/enum.yaml

``` yaml
type: string
enum:
  - A
  - B
  - C
```

folderB/enum.yaml

``` yaml
type: string
enum:
  - B
  - C
  - D
```

Here is the result:
![image](https://cloud.githubusercontent.com/assets/839290/12477235/a7dc59d8-c02e-11e5-89e9-8b027f6608e1.png)

As you see - for some reason swagger ui shows the content from the _folderB/enum.yaml_ two times, while should show the different ones.

Regards,

**Comment by webron** [comment]
Should no longer be an issue with the new UI.
