### ISSUE TITLE
Overridden path-level parameters appear in operation display

### ISSUE THREAD

**Issue by andylowry** [swagger-api/swagger-ui#1913]
If a parameter specified in the path-level "parameters" property has the same name and "in" values as a parameter specified for an operation, the path-level parameter should be overridden by the operation-level parameter. Swagger-UI shows both parameters in display of the operation in this case.

Try this gist in swagger-ui as an example:

https://gist.githubusercontent.com/andylowry/319b343dbf6c38a88bfa/raw/568c1f9fa41d84061e938d61cf76cafea6d5be0c/param-ovedrride.yaml

**Comment by webron** [comment]
This is no longer an issue with the new UI.
