### ISSUE TITLE
The request doesnot work for https restful server

### ISSUE THREAD

**Issue by LouisZou** [swagger-api/swagger-ui#1916]
I used swagger-ui to make a web environment for my swagger definition file.
When I test it I found the request is not sent to the server if I use schemes to https.
If I use http it can work normally.
I can access both the https and http restful server by curl command.

**Comment by fehguy** [comment]
Hmm many, many people use https so perhaps you can open your network debugger in your browser and share the details.

**Comment by LouisZou** [comment]
Thanks fehguy.

I found the reason is the remote https server is not certified for my browser.
It works now after I resolved the SSL for my browser.
A simple workaround is as the following:
in chrome, open the https url directly and trust it or download the cert file and add it into browser.

**Comment by fehguy** [comment]
Thanks for following up.  I'll close this issue.
