### ISSUE TITLE
gulp-clean package deprecated

### ISSUE THREAD

**Issue by molokoloco** [swagger-api/swagger-ui#1917]
I have replaced https://www.npmjs.com/package/gulp-clean with https://www.npmjs.com/package/del as i got warning after install. Cf. recommandation here http://stackoverflow.com/questions/24396659/how-to-clean-a-project-correctly-with-gulp
In gulpfile.js (L31) :
<code>gulp.task('del', function(cb) {
  del(['./dist'], cb);
});</code>

**Comment by webron** [comment]
Should no longer be an issue in 3.X.
