### ISSUE TITLE
Swagger UI doesn't display nullable types

### ISSUE THREAD

**Issue by bssergy** [swagger-api/swagger-ui#1920]
If I have nullable type of property in my definition:
```
type: [integer, null]
```
this property do not show.

**Comment by webron** [comment]
The spec doesn't support two things you do here - multiple types and null as a type. Swagger-UI will not support either of those if and until they are added to the spec.

**Comment by bssergy** [comment]
So, how can I specify that property can be nullable?

**Comment by webron** [comment]
You can't. It's not supported by the spec. https://github.com/OAI/OpenAPI-Specification/issues/229
