### ISSUE TITLE
Authorization Fails, but running the cURL directly in CMD succeeds.

### ISSUE THREAD

**Issue by derekrivers** [swagger-api/swagger-ui#1922]
I have a bizzare problem, using the "Try it yourself" button, the server returns Authorization is denied.

When i take the cURL that is presented in the swagger UI, and run it via command line, it passes Authorization and return the JSON response as expected.

![image](https://cloud.githubusercontent.com/assets/11353624/12614891/68d9021a-c4fa-11e5-8978-44245e1161c3.png)

The full cUrl is below.

curl -X GET --header "Accept: application/json" --header "Authorization: Bearer  cPW8R8v8MTGUvWL3jlPItoaOr8ZI31OYr9uVIT2-mtSaw8UfjiC4K6_3tJV6QoAqDaZx1gk6CjY0puPfdjrdwqwskfVzJU67w69XW3mOcjXJZj3onJgYbLUknUh2DjCYauqYkm1MDW-mLHID58yVySdAnFx4-FDhKSn0G-jjPKcQyyChd_UslXp8Sv83YCVqBlZVGcDP8UBEFv9awOMUPnvXp2QpHvb95EHZE2YkYjDQdoL6KIu>DR8x34fA7Q8V_-pMJxBDhCJqZF_4MoKSlyjC7TqVbsEdqinG6Y1NibJOh-_Ev5I9XI8noEejJiBtK32g2CKcR84Q3JONTfXzV_P-HAo-K949lGcClXgXJFknULKEQTdGPgtrFVIhCqv4CyQ9qEJPOD29QPbKhVRgI3A2PIDEppWkgHO-qjQAQAQ" "http://localhost:42291/api/v1/lenders"

Here is the beginning of the spec file, to show which version I'm using etc.

![image](https://cloud.githubusercontent.com/assets/11353624/12638800/da63c418-c597-11e5-95c3-5df56d8c5e8a.png)

Here is the JSON from the spec doc concerning the method i'm trying to hit..

![image](https://cloud.githubusercontent.com/assets/11353624/12638600/6c3d3e34-c596-11e5-92d7-cfd1735b370d.png)

Here is the security definition

![image](https://cloud.githubusercontent.com/assets/11353624/12638619/97336fdc-c596-11e5-89fb-7dc6757860b1.png)

I'm injecting the following JavaScript function into swagger UI to change the request header

```javascript

$('#input_apiKey').change(function () {
    var key = $('#input_apiKey')[0].value;
    var credentials = key.split(':'); 
    $.ajax({
        url: "http://localhost:42291/token",
        type: "post",
        contenttype: 'x-www-form-urlencoded',
        data: "grant_type=password&username=" + credentials[0] + "&password=" + credentials[1],
        success: function (response) {

            var bearerToken = "Bearer " + response.access_token;

            window.swaggerUi.api.clientAuthorizations.remove('api_key');

            var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", bearerToken, "header");

            window.swaggerUi.api.clientAuthorizations.add('key', apiKeyAuth);
            
            alert("Login Succesfull!");
            
        },
        error: function (xhr, ajaxoptions, thrownerror) {
            alert("Login failed!");
        }
    });
});

```

Ask you can see by the cURL in the image above, the Bearer Token is present. But its never attached when i hit "Try It Yourself".

I've tried using Postman and cURL to hit this api method with a valid Token and they both work fine.

Its only through the swagger UI that its failing.

**Comment by webron** [comment]
Would need more info than that... what does your spec look like? how do you define the authorization? And so on... not much to work with here :)

**Comment by derekrivers** [comment]
I've update the original Post webron, I'm using Swagger 2.0 via swashbuckle for ASp.NET WEB API.

I really wanna get this working, as its a great feature.

Hopefully i've gave you enough info, if there's anything missing just let me know.

**Comment by webron** [comment]
It's never attached because you're setting the authorization as an apikey and not oauth2, and there's a name mismatch between the spec and the key you're providing. That's not really how the oauth2 integration works in swagger-ui. 

swagger-ui currently does not support the `password` flow. There are two pending PRs that have not been merged yet. You can test those yourselves to see if they help resolve your issue.

**Comment by derekrivers** [comment]
Ahh!!! I've been stuck with this for days. Simply correcting the name mismatch has solved the issue.

Thanks for your help Ron! This can be closed off, appreciate your time.

**Comment by webron** [comment]
Thanks for the update. We're planning on improving the integration with security soon, so be on the look out for future versions.
