### ISSUE TITLE
Security Information is Missing

### ISSUE THREAD

**Issue by jonbuck16** [swagger-api/swagger-ui#1923]
The swagger UI does not show any security information that was written into the originating YAML definition. 

I have added a securityDefinitions section to the API and then within the appropriate paths I have referenced the definition, now within the HTML that is rendered on the right hand side of the editor it shows a security section at the top and within the paths however if I download a JSON representation of API and use the UI tool to view the documentation it doesn't show the security section at the top nor do the paths that require security show any information therefore a user of the API has no idea that basic authentication is required for example...

Any ideas anyone??

I am using version 2.1.4 of the UI and version 2.9.8 of the editor...

**Comment by webron** [comment]
Please see #1108.
