### ISSUE TITLE
"title" field creates empty json objects

### ISSUE THREAD

**Issue by tomjohnson1492** [swagger-api/swagger-ui#1925]
When you use the "title" field when describing the structure of a JSON object, the Swagger UI replaces the default "inline_model" reference name with the "title" you specified. However, the JSON referent object becomes empty. See this [Swagger forum thread](https://groups.google.com/forum/#!topic/swagger-swaggersocket/UcAjHY2_BB0) for more details.

**Comment by fehguy** [comment]
@bodnia do you have any ideas on this?

**Comment by grouchal** [comment]
Hi - any ideas when this might be released - is a pain of a bug for us.

**Comment by bodnia** [comment]
@grouchal could you please provide an example of where this doesn't work as in latest master this is already fixes? Thank you advance!

**Comment by grouchal** [comment]
Hi @bodnia this does work - but it is not released - would be great if a versioned release could be made that we can reference from our projects - we have to use fixed version numbers in our projects.

**Comment by philippone** [comment]
Hi,
the bug is not completely fixed. It does not work in my response messages. Here is a snippet of my yaml definition:
```
	...
      responses:
        '200':
          description: Success
          schema:
            title: Dashboards		/* here it works */
            type: array
            items: &ref_4
              title: dashboards    	/* here it works */
              type: object
              required:
                - id
                - boardName
              properties:
                id:
                  description: "Used to identify a widget truck by it's id."
                  type: integer
                  format: int64
                boardName:
                  description: Represents the name of the given dashboard. The board name is used by the ui.
                  type: string
        '401': &ref_5
          description: Unauthorized
          schema: &ref_0
            title: Error			/* does not work: displays inline_model instead of Error */
            type: object
            required:
              - message
            properties:
              message:
                type: string
        '404': &ref_7				/* does not work: displays inline_model instead of Error */
          description: Not Found
          schema: *ref_0
        default: &ref_9
          description: Error
          schema:
            title: Error			/* does not work: displays inline_model instead of Error */
            type: object
			...
```
			
I found a quick fix but I had to edit some lines in swagger-client ([changes](https://github.com/swagger-api/swagger-js/pull/714)). Maybe someone has a solution for swagger-ui?

**Comment by webron** [comment]
Should be resolved. Reopen if not.
