### ISSUE TITLE
"fetching resource list: undefined; Please wait" appears when "spec" is used instead of "url".

### ISSUE THREAD

**Issue by collaborator99** [swagger-api/swagger-ui#1927]
This message appears while loading when "spec" is used in stead of "url":
"fetching resource list: undefined; Please wait"

We are eager to have this fixed since it looks like an error.  A slight workaround is to pass url: "" in addition to to "spec" which then results in this message:
"fetching resource list: ; Please wait"

Also, the message display could be improved to be more standard the message started with a capital letter and if "Please wait" was an ellipsis.  So something more like either "Fetching resource list..." (when using spec) or "Fetching resource list from <url>..." (when using url)

**Comment by daledupreezISC** [comment]
:+1: 
I also need to do this on a project where the API is relative to the current path, so we need to manipulate the base Swagger spec before rendering.

**Comment by webron** [comment]
No longer an issue with 3.X.
