### ISSUE TITLE
Jquery.slideto.min.js origins

### ISSUE THREAD

**Issue by mkuznyetsov** [swagger-api/swagger-ui#1928]
Hello.
We are going to use Swagger UI in our Eclipse Che project https://www.eclipse.org/che/
Could you please provide information about dependency "jquery.slideto.min.js", we need to know it's origins, source, license etc, so this library can be approved. 

Also, we'd like to ask for upgrading some of dependencies to the versions, approved by Eclipse:
- Highlight.js to 8.8.0
- Jquery to 1.8.1
- Underscore.js to 1.8.3

Thank You.

**Comment by fehguy** [comment]
Hi, the dependency upgrades should be fine, providing the tests pass.

The `slideto` plugin is from here:

https://github.com/Sleavely/jQuery-slideto

**Comment by webron** [comment]
No longer relevant in 3.X.
