### ISSUE TITLE
Need fix typo 'xlmns'

### ISSUE THREAD

**Issue by rick22sun** [swagger-api/swagger-ui#1931]
In swagger-ui.js, function
```
var getNamespace = function (xml) {
    ...
    var name = 'xlmns';
```
here `'xlmns'` should be `'xmlns'`.

**Comment by bodnia** [comment]
@webron Could you please change this in [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#xml-attribute-prefix-and-namespace) too?

This is from specification:
`
<Person id="123">
    <sample:name xlmns:sample="http://swagger.io/schema/sample">example</sample:name>
</Person>
`

**Comment by webron** [comment]
Well, that's awkward. Fixed, thanks.

**Comment by bodnia** [comment]
this issue is resolved, @webron could you please close it?
