### ISSUE TITLE
allowEmptyValue not implemented?

### ISSUE THREAD

**Issue by rick22sun** [swagger-api/swagger-ui#1934]
Looks like allowEmptyValue not implemented. The goal is to produce a query parameter `?param1` without any value and the '=' sign. Tried the following

```
{
        in: "query",
        name: "param1",
        type: "string",
        required: false,
        allowEmptyValue : true
}
```

with different type, but can't send `?param1` in the URL.  The closest I can get is `?param1=true` using:

```
{
        in: "query",
        name: "param1",
        type: "string",
        required: false,
        enum : ["true"]
}
```

Ideally, if allowEmptyValue = true, then ui presents a checkbox: when checked send `?param1`, else just do not include the parameter.

**Comment by Hronom** [comment]
Same here, very useful to implement reset logic for values, otherwise it can be implemented.

Is there any progress on this?

**Comment by Hronom** [comment]
Same here, very useful to implement reset logic for values, otherwise it can be implemented.

For case:
```
required: false,
allowEmptyValue : true
```
need to draw checkbox. If you check it - the swagger ui will send `?param1` or `?param1=`, otherwise there no be parameter in request.

Is there any progress on this?

**Comment by Hronom** [comment]
Same here, very useful to implement reset logic for values, otherwise it can't be implemented.

For case:
```
required: false,
allowEmptyValue : true
```
need to draw checkbox. If you check it - the swagger ui will send `?param1` or `?param1=`, otherwise there no be parameter in request.

Is there any progress on this?
