### ISSUE TITLE
Header parameters and Redirect

### ISSUE THREAD

**Issue by glederrey** [swagger-api/swagger-ui#1935]
Hi,

I encountered a problem using Swagger-UI.. (There's no problem while using the Web Browser or a client library generated by Codegen)

First, le me explain my call.. I call a function that will process some things and then will redirect to another page to send back a picture.. I attached a screenshot under it..

![screen2](https://cloud.githubusercontent.com/assets/13273462/12718248/8f6b9d88-c8ed-11e5-8d08-c2cb5bc61252.png)

This is "working".. (Still have some issues with getting the picture, see #1848).. But the problem comes when I'm entering some headers parameters (here appId and appKey).. Swagger-UI does then a OPTIONS call before doing the POST one and don't do anything after that.. Normally, it should redirect as it is done before (without the headers parameters).. See the calls on the second screnshot.. 

![screen1](https://cloud.githubusercontent.com/assets/13273462/12718187/19bdc67e-c8ed-11e5-9d8e-d702aa00f89c.png)

Am I doing something wrong with the headers?? Or does anyone also encountered this problem?? 

Thank you

**Comment by webron** [comment]
Have you added the headers to your CORS configuration?

**Comment by glederrey** [comment]
Hi @webron,

Yes, I added them into the `Access-Control-Allow-Headers`.. That's what you meant by your question??

**Comment by webron** [comment]
Yes. Can you share the output of `curl -I <url of api>`?

**Comment by glederrey** [comment]
@webron I'll give you the output at 09-10am CET.. I don't have my computer for the work..

**Comment by glederrey** [comment]
@webron Here is the output.. There's something weird because it says that the HEAD requests are not supported.. 

>

```
curl -I http://localhost:8080/nviso/api/cloud/v1/worker/nviso/photo/process/url
HTTP/1.1 405 Request method 'HEAD' not supported
Date: Tue, 02 Feb 2016 08:49:02 GMT
Allow: GET
Content-Type: text/html; charset=ISO-8859-1
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 385
Server: Jetty(9.2.9.v20150224)
```

**Comment by webron** [comment]
Yup, and it also doesn't show the CORS headers. So either they are not set, or the lack of `HEAD` support is going to make it more difficult to investigate.

**Comment by glederrey** [comment]
The things is that I'm using the Spring MVC server generated using Swagger Codegen.. So, do you know if there's a way to accept the HEAD requests??

**Comment by webron** [comment]
There are resources on the web on how to enable it, but that also depends on the Spring version and so on. I'd suggest doing a quick search on that.

**Comment by glederrey** [comment]
Okay, I will do that.. Thank you for your help..

**Comment by ravibhushan29** [comment]
add another cors extension to chrome... and enable it ... then it will work
