### ISSUE TITLE
Various parameter options, such are maxLength, are not displayed when the method is GET

### ISSUE THREAD

**Issue by collaborator99** [swagger-api/swagger-ui#1936]
Looking at the Parameters table for a GET, I see no place where the maxLength etc. appears.  

For example:

```
{
    "name": "stateProvince",
    "in": "query",
    "description": "",
    "required": false,
    "maxLength": 2,
    "type": "string"
}
```

**Comment by jfiala** [comment]
It would be nice to see this information (minLength, maxLength) as mouseover as it can be seen in the response Models.

**Comment by jjzabkar** [comment]
Perhaps this issue should be tagged as "can-use-for-docs"?
https://github.com/springfox/springfox/labels/can-use-for-docs

**Comment by jjzabkar** [comment]
+1

Related:
* https://github.com/springfox/springfox/issues/1227
* https://github.com/springfox/springfox/issues/1296

**Comment by webron** [comment]
See #993.
