### ISSUE TITLE
multipart/form-data parameters sent as "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by jftregor** [swagger-api/swagger-ui#1938]
Hello,

I'm currently writing some documentation about a REST service where some POST request requires a long string parameter to be handled as a multipart/form-data string.
Unfortunately, Swagger-UI sends this string parameter as  "application/x-www-form-urlencoded" form and, of course, the service does not accept it.

Here is a minimalistic swagger YAML file reproducing this behavior:

```
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
host: '127.0.0.1:8080'
paths:
  /:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: key
          required: false
          type: string
          description: some string parameter
          default: "some value sent as multipart form data"
      responses:
        200:
          description: OK
```

I found a workaround, providing this modified YAML where I added some fake `file` parameter asking people who read my doc not to use it :-(

```
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
host: '127.0.0.1:8080'
paths:
  /:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: key
          required: false
          type: string
          description: some string parameter
          default: "some value sent as multipart form data"
        - in: formData
          name: fake
          required: false
          type: file
          description: DO NOT USE, this is a workaround for Swagger-UI (otherwise above parameter is not sent as multipart/form-data)
      responses:
        200:
          description: OK
```

Is there something wrong or am I missing something here ?
BTW, I tried this on 2.1.3 and 2.1.4 versions...

Regards

**Comment by webron** [comment]
You're doing fine, this is a bug.

**Comment by jylinman** [comment]
Yeah I ran into this today as well-- my YAML code works fine on http://editor.swagger.io/#/ but when I run it with a freshly gulp'd swagger ui it does just as you say.  +1 for fix ;)

**Comment by qrpike** [comment]
Has this been fixed? Thakns,

**Comment by fehguy** [comment]
Hmm yes this is a regression.  The underlying issue is in swagger-js, I'm opening an issue there, it should be easy to fix.

**Comment by webron** [comment]
Should be resolved.
