### ISSUE TITLE
Preserve schema order for fields in embedded object editor

### ISSUE THREAD

**Issue by dtribble** [swagger-api/swagger-ui#1939]
For the Try It feature, the new embedded object editor is great. I was surprised by the order the body object presents its fields in the editor. I think it would be improved if it presented the fields in the order they appear in the schema. At least for our schemas, the parameters are listed in a semantically useful order. Thought it's legal JSON, it's strange to see a field order of "city, street2, zip, street1, state" for a body address instead of the more typical order.

**Comment by webron** [comment]
@lepinayl - people use your awesome work :) Would you mind taking a look at this issue?

**Comment by lepinayl** [comment]
@webron @dtribble I'm planning to get back to work on this feature current Feb (been running low on capacity the last few weeks). I'll first need to fix some stuff so that we are in sync with JSON Editor master instead of the custom build we have right now. Then I'll be glad to look into that kind of improvements ;)

**Comment by lepinayl** [comment]
@webron @dtribble  Don't know where to post updates regarding this feature, so I'll do it here ;)

I'm currently waiting for https://github.com/jdorn/json-editor/pull/456 to put reviewed/merged. Once that's done we will be able to use JSonEditor official main branch or release. I will then look into this issue.

**Comment by webron** [comment]
@lepinayl great, thanks for the update!

**Comment by dtribble** [comment]
@lepinayl yes thank you for the update. Still quite interested :)

**Comment by PlopSpark** [comment]
Hi everyone, 

I'm also interested in seing the body fields to not appear in random order. When specifying required parameters they can sometimes go to the end of the JSON builder form. Is there any way to control the apparition order of those fields ?

Thanks.

**Comment by tdudgeon** [comment]
Just checking what was meant by the last comment by @Elpayet.
I think I'm also seeing this - I have a OpenAPI definition that has a multipart/form-data request, and I'm finding that whilst swagger-ui displays the form fields in the order that is present in the OpenAPI definition when the request is made the order of the fields is different. This can cause difficulties.
I would hope that the request would respect the order of the fields.
Is this what was meant by your comment? If not I can create new issue.

**Comment by tdudgeon** [comment]
@webron You closed this issue but the work was still to be done. Should it be re-opened, or a new issue created?

**Comment by shockey** [comment]
@tdudgeon, please open a new issue - and please share some details of what exactly you're trying to achieve, as I don't know of many use cases that would require specifically ordered form data key/value pairs. thanks!
