### ISSUE TITLE
Model Schema when "response" definition includes examples

### ISSUE THREAD

**Issue by josephmcdermott** [swagger-api/swagger-ui#1946]
I believe including the output format within the Model Schema output (in my case "application/vnd.api+json") is not a true representation of the data format returned, since it is the data within that is returned. See screenshot:

<img width="281" alt="josephmcdermott 2016-02-04 at 17 42 35" src="https://cloud.githubusercontent.com/assets/6955944/12823977/d45f003a-cb66-11e5-8c29-d41654deacae.png">

Furthermore, when you have multiple format examples, both of them are included in the output. Some consumers could find this confusing.

My responses format is like this:

```
"responses": {
    "200": {
        "description": "success",
        "schema": {
            "$ref": "#/definitions/Product"
        },
        "examples": {
            "application/vnd.api+json": {
                "data": {
                    "type": "Product",
                    "id": "123",
                    "attributes": {
                        "id": "123",
                        "name": "Product Name",
                        "price": "123.45"
                    }
                }
            },
            "application/json": {
                "id": "123",
                "name": "Product Name",
                "price": "123.45"
            }
        }
    }
}
```
1. It would be good if the Model Schema output started from { "data": {
2. It would be great if only the example relating to the currently selected output format was rendered, and the example was updated when the output format was changed.

**Comment by fehguy** [comment]
This is a bug.  It shouldn't list the content type in the examples.

**Comment by josephmcdermott** [comment]
Ah OK, do you know if it is on the roadmap, if so/if not, my second suggestion would be awesome to allow flicking between response format examples :) Great product by the way!

**Comment by fehguy** [comment]
Yep, we'll get that fixed shortly

**Comment by josephmcdermott** [comment]
Not pestering as I know you guys are busy, but how shortly is shortly? :) :+1:

**Comment by patric-eberle** [comment]
Have the same problem. Additionally, the first example of the path verb overrides the following ones.

```
---
swagger: '2.0'
info:
  version: 1.0.0
  title: A Swagger editor study
consumes:
  - application/vnd.api+json
produces:
  - application/vnd.api+json
paths:   
  /c-examples:
    get:
      responses:
        "200":
          description: |
            This example will override every other in this path.
          schema:
            $ref: "#/definitions/demo"
          examples:
            application/vnd.api+json:
              data:
                title: A title
                text: The content text
    patch:
      responses:
        "200":
          description: |
            This example will be overwritten by "get" example.
          schema:
            $ref: "#/definitions/demo"
          examples:
            application/vnd.api+json:
              data:
                title: An other title
                text: An other content text
definitions:
  demo:
    type: object
    properties:
      foo:
        title: foo
        type: string
```

![swagger-ui](https://cloud.githubusercontent.com/assets/10571945/20555500/ccaf1306-b162-11e6-8fc2-3681e06bb0e5.png)

**Comment by fehguy** [comment]
Shortly :)  Sorry that was a long "shortly".

I did dig into this today, and we cut a release of 2.2.7 unfortunately without this fix.  We can turn around another build "shortly" as well.

The current logic is not super smart.  There are only two different example builders--one for JSON and another for XML.  The JSON logic looks like this:

https://github.com/swagger-api/swagger-ui/blob/7e426ac0cd27f1db508d827942b971254fd913a7/src/main/javascript/view/partials/signature.js#L561

Thus if the content-type does not _start_ with `application/json`, it will not be considered.

We can change this to look in the examples' key:

```
/^application\/.*json/i.test(key)
```

to return the value in the example.  Would that do the trick?

Also @patric-eberle the overwriting of examples should be fixed now.

**Comment by DalSoft** [comment]
@fehguy this would definitely solve domaindrivendev/Swashbuckle.AspNetCore#228 at the moment I'm creating multiple definitions of the same object so that I can have multiple examples without them being overridden. But this pollutes swagger.json, using the _Examples_ key rather than _Example_ would mean I could remove this hack, by providing multiple Examples that reference only one definition.

**Comment by kjg** [comment]
I just ran into this too, but even "application/json" as the key in the example still renders the entire hash including the top level "application/json".

Also it would be great if I could ```

```json
"examples": {
  "application/json": {
    "$ref": #/path
  }
}

**Comment by josephmcdermott** [comment]
@fehguy coming up to the one year anniversary since I created this ticket, would be great to give it a release as a birthday present 'shortly' ;)

**Comment by kjg** [comment]
It looks like the [`return` ](https://github.com/swagger-api/swagger-ui/blob/38f74164a7062edb5dc80ef2fdddda24f3f6eb85/src/main/javascript/view/partials/signature.js#L567) inside the forEach isn't doing what the developer intended. It just breaks out of the current iteration early, but keeps looping, and doesn't return anything from the parent function. http://stackoverflow.com/questions/34653612/what-does-return-keyword-mean-inside-foreach-function/34653650

**Comment by fehguy** [comment]
@josephmcdermott well good news, we're in alpha testing for a complete refresh of this project, and yes this is fully supported.  More announcements in the coming weeks, but because of that effort, we're not doing major work on the current (master) version.

**Comment by kjg** [comment]
@fehguy is there any way to get access to this alpha for testing?

**Comment by webron** [comment]
We're not yet at a stage that it's ready for even alpha usage. It will be in a few weeks - we're pushing it hard.

**Comment by webron** [comment]
Please try 3.X and report us with any issues.
