### ISSUE TITLE
contextpath/hostname missing from url

### ISSUE THREAD

**Issue by yaneyba** [swagger-api/swagger-ui#1947]
Hello,
I created a basic OWIN ASP.NET Web API2, installed SwashBuckle via Nuget, then configured the SwaggerConfig.vb file as follow:

Public Module SwaggerConfig
Public Sub Register()
Swashbuckle.Bootstrapper.Init(GlobalConfiguration.Configuration)
SwaggerSpecConfig.Customize(Sub(c)
c.IncludeXmlComments(GetXmlCommentsPath())
End Sub)
End Sub

Private Function GetXmlCommentsPath() As String
    Return String.Format("{0}bin\AuthServerApi.xml",  System.AppDomain.CurrentDomain.BaseDirectory)
End Function
End Module

When I hit the "Try it out!" button - On the Remote Server - to test the API, here's what I get:

On IIS (Release Mode) - NOT WORKING - "xxx.xxx" a.k.a my actual API is missing from the URL

Request URL:
http://mydevwebserver:80/xxx.xxx/api/audiences
Response Code: 404

But On IIS Express (Debug Mode) it works as expected
Request URL:
http://localhost:50648/api/audiences
Response Code: 200

Thanks for your help.

Nae

**Comment by webron** [comment]
@yaneyba - is this using the swagger-ui included with Swashbuckle? it seems like a configuration issue, but that's more on the Swashbuckle end so you should ask there.

**Comment by yaneyba** [comment]
> is this using the swagger-ui included with Swashbuckle? yes

**Comment by webron** [comment]
Then please open the ticket on swashbuckle as it's probably a configuration issue.
