### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by laiddlai** [swagger-api/swagger-ui#1957]
I am using Swagger 1.5.4.  I would like to add support for HTTPS for our project.   I found that I had to make a change in swagger-ui.js in order to make it work for HTTPS.  See line 1390:

```js
  if (typeof this.url === 'string') {
    location = this.parseUri(this.url);
    if (typeof this.scheme === 'undefined' && typeof this.schemes === 'undefined' || this.schemes.length === 0) {
      this.scheme = location.scheme || 'http';
    } else if (typeof this.scheme === 'undefined') {
      this.scheme = this.schemes[0] || location.scheme;  <----- line 1390
    }
```
I have to change line 1390 to become:
```js
      this.scheme = location.scheme || this.schemes[0];
```
in order to make HTTPS work.

The code change basically reverses the order of looking up the scheme.  After the change, it will look up the scheme from location.scheme first.  If it is null / empty, then use the first scheme (this.schemes[0]).   

I think this agrees with the logic a few lines above:
```js
    if (typeof this.scheme === 'undefined' && typeof this.schemes === 'undefined' || this.schemes.length === 0) {
      this.scheme = location.scheme || 'http';
```
which also uses location.scheme as the first attempt.

I am not sure if there are other test cases that require the code at 1390 to stay in its current state.   If not, I would like to see if it is possible to have this change be in the next release of Swagger.

Thanks.

**Comment by michaelreynolds** [comment]
I concur. This resolves the same issue I was having.

**Comment by nooruddin** [comment]
I resolved this 1.5 and after switching to 2.0, HTTPS didn't seem to work.  This issue reminded me of the change and everything is in place.  Please do add this to next release. Thanks.

**Comment by offero** [comment]
Is scheme support on a branch/tag now?

**Comment by fehguy** [comment]
Please look at 2.2.3 or later for a proper fix for this.
