### ISSUE TITLE
Where did DroidSans.ttf come from?

### ISSUE THREAD

**Issue by ShaneWilton** [swagger-api/swagger-ui#1959]
[DroidSans.ttf](https://github.com/swagger-api/swagger-ui/blob/7a5f6b2c595891ffc10705f5d7d760a4df51b951/dist/fonts/DroidSans.ttf) is much larger than the official file served by Google (40K versus 186K). I'm also getting a suspicious error from Chrome when trying to load this font.

```
Failed to decode downloaded font: http://localhost:8080/fonts/DroidSans-Bold.ttf
(index):1 OTS parsing error: GSUB: table overruns end of file
```

A search for the SHA256 hash of the file returns only a [Russian VirusTotal scan](https://www.virustotal.com/en/file/f51b88945f4c1b236f44b8d55a2d304316869127e95248c435c23f1e4142a7db/analysis/) performed on December 2nd, 2015.

I'd be curious to know where @fehguy found this file, since none of the samples I'm finding from official sources match the hash.

Additionally, I'd recommend replacing the file with the official font, [available from Google](https://www.google.com/fonts/specimen/Droid+Sans): at the very least, it's a smaller file.

**Comment by frankcash** [comment]
:+1:

**Comment by fehguy** [comment]
Please send a PR.

**Comment by richardjhall** [comment]
:+1:

**Comment by webron** [comment]
No longer an issue with 3.X.
