### ISSUE TITLE
use operation instead of entire JSON file

### ISSUE THREAD

**Issue by humblefools** [swagger-api/swagger-ui#1961]
var swaggerUi = new SwaggerUi({
      url:"http://localhost:8000/swagger/JSON/petstore.json",
      dom_id:"swagger-ui-container"
    });
    swaggerUi.load();

Instead of using entire JSON file in url , is there a way by which we can use a particular operation , so that dom_id is for that particular operation. So let's say I have 3 operations , GET , POST and PUT , I want to create three different divs being initialized on the basis of three operations nnot just one big div having id as swagger-ui-container.

**Comment by webron** [comment]
I'm afraid there isn't a way to do that, though we've thought about implementing it as it makes sense for some use cases.
