### ISSUE TITLE
swagger-ui doesn't work without trailing slash

### ISSUE THREAD

**Issue by DerekYangYC** [swagger-api/swagger-ui#1966]
When using `Grizzly` to host static content of `swagger-ui`, `http://localhost/swagger/` works fine but `http://localhost/swagger` doesn't, which results in 404 not found error in the back end.

I post a question [here ](http://stackoverflow.com/questions/35123194/jersey-2-render-swagger-static-content-correctly-without-trailing-slash)in details

**Comment by webron** [comment]
That's a grizzly configuration issue, and unrelated to swagger-ui. You'll have similar issues hosting any other static content.
