### ISSUE TITLE
No endpoints shown

### ISSUE THREAD

**Issue by hobarrera** [swagger-api/swagger-ui#1968]
When using my own JSON file (exported from the swagger editor), I don't see any endpoints, just the description (where GFM is not being parsed, but I don't care as much about that - yet).

My JSON file is available here: https://raw.githubusercontent.com/shipnow/docs/build/swagger.json

The swagger editor, and apiary both parse this fine, and display all the endpoints, but swagger ui doesn't show any (just paste the above URL in the demo site).

**Comment by fehguy** [comment]
Well, this is invalid JSON so, nothing should display it.  Put `http` in quotes.

**Comment by hobarrera** [comment]
Sorry, I should have pointed to the exact commit which had the swagger-ui-generated file (the latest master a minute ago had a manually edited version):

https://raw.githubusercontent.com/shipnow/docs/e04ba58a8343c0ebc733b71354bf861ed08e5e14/swagger.json

**Comment by hobarrera** [comment]
Also: I tried both schemes `http`, and `https`, with the same result, though I don't think it should be what's breaking.

**Comment by hobarrera** [comment]
Can we reopen this? Or should I open a different issue?

**Comment by webron** [comment]
While technically that spec is valid, I wouldn't say it follows 'best practices'. You should be able to resolve it by moving the schema definitions under `definitions` and then refer those from both the parameters and the responses.

**Comment by fehguy** [comment]
well in fairness, @webron, the spec is valid and it's causing a javascript error in swagger-ui.  We should fix it.

**Comment by webron** [comment]
I said it's valid :-) just suggested a workaround.

**Comment by hobarrera** [comment]
Thanks for pointing that out and the suggestion, I'll adapt it to follow best practices (I really prefer to follow conventions, and for readability by others), but I think it's fair to leave this issue open since it should not crash for a valid spec file.

**Comment by webron** [comment]
This should no longer be an issue with 3.X. Please reopen otherwise.
