### ISSUE TITLE
Scroll to section referenced in fragment identifier

### ISSUE THREAD

**Issue by gwicke** [swagger-api/swagger-ui#1972]
Swagger-UI provides helpful links to auto-expand specific sections, but does not by default scroll to the expanded section. I think scrolling to the relevant section would be very helpful especially for complex APIs, as it would make sure that the referenced section is in view after loading.

**Comment by heldersepu** [comment]
Also we should scroll after we get a response after click in [Try it out!] button.
Some JS like this, should suffice:
$("#Controller_Controller_Action")[0].scrollIntoView();

**Comment by webron** [comment]
The links to operations is currently not implemented in the new UI, but hopefully we'll include this as part of the implementation.
