### ISSUE TITLE
POST method as form-data throws 415 error

### ISSUE THREAD

**Issue by chaithchey** [swagger-api/swagger-ui#1977]
Hi,

I have a POST method with formdata which throws 415 unsupported content-type error.it seems the below code in swagger-ui.js sets the formData content type as  application/x-www-from-urlencoded instead of application/json.

// if any form params, content type must be set
    if (definedFormParams.length > 0) {
      if (opts.requestContentType) {             // override if set
        consumes = opts.requestContentType;
      } else if (definedFileParams.length > 0) { // if a file, must be multipart/form-data
        consumes = 'multipart/form-data';
      } else {                                   // default to x-www-from-urlencoded
        consumes = 'application/x-www-form-urlencoded';
      }
    }
  }

**Comment by webron** [comment]
You can't really send formData parameters with a content type of application/json.
