### ISSUE TITLE
Inconsistent enter key behaviour

### ISSUE THREAD

**Issue by c-knowles** [swagger-api/swagger-ui#198]
The enter key seems to submit for some APIs but not others. Taking the pet store example:
- The first three POSTs use enter for a new line in the request body. This is understandable.
- "Updated user" PUT uses enter for submit. It's in the "/user" section.
- "Get user by user name" GET uses enter for submit. It's in the "/user" section.
- "Logs user into the system" GET doesn't seem to do anything on pressing enter. It's in the "/user" section.
- "Find pet by ID" GET uses enter for submit. It's in the "/pet" section.
- "Finds Pets by tags" GET uses enter for submit. It's in the "/pet" section.

I'm using the latest consumer version of Chrome 26.0.1410.64m and the current master with the petstore example at http://petstore.swagger.wordnik.com/api/api-docs.json.

**Comment by fehguy** [comment]
@ponelat can you look at this please?

**Comment by webron** [comment]
Closing this out as it's most likely not an issue anymore with the latest UI. Of course, if anyone feels differently, please file a new ticket.
