### ISSUE TITLE
Image render broken in Swagger UI

### ISSUE THREAD

**Issue by gabrielacosta** [swagger-api/swagger-ui#1981]
Hi, 

I have some problems trying to render an image in Swagger. 

My image is returned as image/jpeg from the server. I read in 
https://github.com/swagger-api/swagger-ui/pull/327
https://github.com/swagger-api/swagger-ui/issues/152

That only those mime types are supported. There is any special way or header that swagger required to render the image properly?

![error_swagger_image _render](https://cloud.githubusercontent.com/assets/8519425/13228393/2b11dde4-d972-11e5-854a-abeae4ada29a.PNG)

I check the image and programatically it is download properly. The content type and the length are correct. 

I'm using the swagger-ui.js version 2.1.4.  
Additionally, I notice when I upload the image using the form-data the image does not upload complete and the type file appear as undefined.

![error](https://cloud.githubusercontent.com/assets/8519425/13228517/de0cd926-d972-11e5-854b-d92f0a3a41cf.PNG)

I'm using this definition for upload the image.

```
/user/{id}/avatar:
    put:
      operationId: UploadUserProfilePicture
      summary: Upload a given profile picture for a given user.
      description: |
        This methods will received the profile picture and stored it for the given user in the system.
      tags:
        - User
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of user that will have the new avatar
          required: true
          type: string
        - name: photo
          in: formData
          description: The user photo
          type: file
          required: true
      responses:
        '201':
          description: Photo upload successful
          schema:
            type: string
        '400' :
          description: |
            Validation error, The current list of validation errors that are possible []
          schema:
            $ref: '#/definitions/Error' 
```

Could you please give me some help about this issue, it is anything missing in my file specification?

Kind regards, 

Juan

**Comment by fehguy** [comment]
Please look at 2.2.3 or later.  There was a bug and it should be fixed now.
