### ISSUE TITLE
Swagger UI Should Add Tailing Slash to URLs

### ISSUE THREAD

**Issue by ragnarok111** [swagger-api/swagger-ui#1983]
Any web servers will consider a URL without a trailing slash to be a file reference. This is doubly true if you have a parameter that can contain a ".".

Consider the template http://example.com/api/email/{username}. If your username is john.smith, the URL will be http://example.com/api/email/john.smith. At the very least, .NET WebApi2 will fail this URL because it's looking for a file called john.smith.

Swagger should ensure there is a trailing slash. Especialy after parameters. The URL http://example.com/api/email/john.smith/ will work fine.

**Comment by fehguy** [comment]
So... I think that's really not true at all.  In fact, I would flip it and say that WebApi2 is the exception, not the rule.

Consider adding the trailing slash to your definition if that's key to how your service works:

`http://example.com/api/email/{username}/`

should work just fine.

**Comment by ragnarok111** [comment]
Good suggestion. It didn't work though. The swagger definition still shows /api/email/{username}. Of course that could be an issue with Swashbuckle. However, is it best to have every developer in the world add a trailing slash to every template definition from now until the end of time, or ask the Swagger team to do it for us?

**Comment by webron** [comment]
Technically, a URL with and without a trailing slash are not the same. Most web servers treat them the same though. The Swagger spec doesn't say anything explicit about it though. If you a trailing slash is critical to you, you'd need to add it to the path yourself. Adding it in the tools would be wrong as it can change the intent of the spec author.

**Comment by ragnarok111** [comment]
Fair enough. I guess I was thinking of swagger as a tool instead of a spec. I'll open an issue with Swashbuckle about about respecting trailing slashes in URL templates.
