### ISSUE TITLE
Use filename disposition parameter in downloads

### ISSUE THREAD

**Issue by davehagler** [swagger-api/swagger-ui#1991]
Currently when an api returns "content-type": "application/octet-stream" and "content-disposition": "attachment", a filename is generated for the download that looks like

[content type]:[url parameters]:generated

In cases where the api returns a filename= disposition parameter, this value could be used when saving the downloaded file.

For example if this header is sent in the response

"content-disposition": "attachment; filename=my_file.txt"

Then the downloaded file would be called "my_file.txt"

**Comment by webron** [comment]
Fixed by #1993.
