### ISSUE TITLE
externalDocs not displayed in the swagger-ui

### ISSUE THREAD

**Issue by iainalexander** [swagger-api/swagger-ui#1992]
Hi,

We are using swagger-ui and are interested in including links to our documentation in the swagger-ui. There is an externalDocs field which seems perfect for this use but when supplied a value for this, it wasn't displayed in the swagger-ui.

Using a test file, I added an externalDocs entry to the test.json file and confirmed that the file is being used in the swagger-ui. However, the externalDocs isn't getting displayed in the ui. See the attached file for the screenshot. 

"paths":{"/pet":{"post":{
.........
"externalDocs":{"description":"Find out more!!!","url":"http://swagger.io"}
}

I cloned the latest version of swagger-ui earlier today (Feb 24th, 2016). 

Any help on this is appreciated.

thanks,
Iain
<img width="2481" alt="screen shot 2016-02-24 at 4 40 32 pm" src="https://cloud.githubusercontent.com/assets/17462345/13302981/a8b4cb68-db1a-11e5-8f13-8205de5f8d7d.png">

**Comment by dpmartin990** [comment]
I am having this same issue.  Have you had any luck?

**Comment by iainalexander** [comment]
What I did as a workaround is put the link to the documentation into the
Implementation Notes section, but it would be better to have it in the
externalDocs. I have had no success in getting the externalDocs to show up
in the operation's section of the swagger-ui.

**Comment by HenrikHL** [comment]
I am also having problems with this

**Comment by mibeumer** [comment]
I also find it cool if the externalDocs would be displayed.

**Comment by AndrewCampbellSynchronoss** [comment]
I'm seeing something similar. 

This is my externalDocs object
```
 "externalDocs": {
    "description": "externalDocs description",
    "url": "http://www.example.com/externalDocs_url"
  },
```
And this is what I see:

<img width="379" alt="screen shot 2016-04-27 at 10 20 25" src="https://cloud.githubusercontent.com/assets/13764960/14847720/1c29ecc2-0c62-11e6-9b99-11b348b9dd0e.png">

It doesn't seem to matter where I put the externalDocs object (as long as it is valid).

**Comment by obfischer** [comment]
+1

**Comment by webron** [comment]
Closing in favor of #1614.
