### ISSUE TITLE
Can't load local json through spec parameter.

### ISSUE THREAD

**Issue by juanjoLenero** [swagger-api/swagger-ui#1994]
I'm trying to load a swagger 2.0 definition via the spec parameter like so:

``` js
window.swaggerUi = new SwaggerUi({
        spec: myLocalSpec,
        //...
```

I was loading my file via jsonp like this:

``` html
 <!-- jsonp handler function -->
  <script type="text/javascript">
      window.setApi = function (jsonSpec) {
          this.myLocalSpec = jsonSpec
      }
  </script>

 <!-- load jsonp -->
  <script type="text/javascript" src="my-swagger-api.jsonp"></script>
 <!-- my-swagger-api.jsonp contains: setApi({swagger-json}); -->

 <!-- Set up swaggerUI -->
 <script type="text/javascript">
    window.swaggerUi = new SwaggerUi({
        spec: window.myLocalSpec,
        // ...
    });
 </script>
```

I even tried inlining the json file in the script, but both approaches fail:
![image](https://cloud.githubusercontent.com/assets/2656008/13334324/18d11d82-dbd1-11e5-8caf-dd694daf34a3.png)

That same api is displayed correctly when loaded through a server via the `url` parameter.

**Comment by fehguy** [comment]
Not sure about JSONP but I do know that setting the object when initializing swagger-ui works fine.  You also need to provide a URL still, perhaps that's your issue

**Comment by juanjoLenero** [comment]
Thank you, I added the url back in and my spec is loaded correctly. Is this the intended behaviour? The main `README.md` says:
![image](https://cloud.githubusercontent.com/assets/2656008/13334598/623e0ff6-dbd2-11e5-8ff0-8986479b240d.png)
What should I set the url to if I'm going to be using the local json file?

**Comment by fehguy** [comment]
It is a bug right now, you can put anything and it is ignored.

**Comment by DesignByOnyx** [comment]
I'm doing the same thing and found a viable solution. Even though you didn't specify a URL, SwaggerUI is still attempting to parse it or validate it. You can set the `validatorUrl` to null to get past the error:

```js
new SwaggerUi({
    spec: jsonpResult,
    validatorUrl: false
    ....
});
```

**Comment by webron** [comment]
should no longer be an issue with 3.X.
