### ISSUE TITLE
Swaggeer UI does not render responses aright

### ISSUE THREAD

**Issue by silvano-lohn** [swagger-api/swagger-ui#1996]
Hi, Swagger Editor responses:

![success](https://cloud.githubusercontent.com/assets/1571138/13351664/16f45c2c-dc67-11e5-93bb-b0a6147e887a.png)

Swagger UI responses:

![error](https://cloud.githubusercontent.com/assets/1571138/13351708/6c8002cc-dc67-11e5-9fd7-e7013eb7b204.png)

Tested with master and 2.1.4

**Comment by fehguy** [comment]
@bodnia It looks like this may be a regression in the ui rendering.

**Comment by bodnia** [comment]
@silvano-lohn could you please provide a spec or even a part of it so that I can reproduce the issue? Thank you in advance!

**Comment by silvano-lohn** [comment]
@bodnia, spec in zip file.

[swagger.zip](https://github.com/swagger-api/swagger-ui/files/153525/swagger.zip)

**Comment by bodnia** [comment]
@silvano-lohn thanks for providing the spec. I tested in latest master and in v2.1.4, please see attached 
![screen shot](https://cloud.githubusercontent.com/assets/8950657/13458716/9b02e290-e077-11e5-99a4-b180a2228923.png)
I wonder if you could try to use latest master.

**Comment by silvano-lohn** [comment]
@bodnia, i did more tests,

- pointing the definition spec.json (definition from Swagger Editor) in Swagger UI, the responses render is ok.
- pointing the swagger.json from server API (http://..../v1/swagger.json) in Swagger UI, the responses render fail.

**Comment by bodnia** [comment]
@silvano-lohn thanks for an update, I'll check this.

**Comment by bodnia** [comment]
@silvano-lohn I put the spec you provided and swagger-ui into server and still got following result. 
<img width="1021" alt="screen shot 2016-03-14 at 9 59 58 am" src="https://cloud.githubusercontent.com/assets/8950657/13738184/a7d33dd2-e9cb-11e5-98ff-cee0d9e8dc0e.png">

When even using http://petstore.swagger.io/ and 
[swagger.zip](https://github.com/swagger-api/swagger-ui/files/171546/swagger.zip)
the result is still the same. Could you please try http://petstore.swagger.io/ is this works for you?

**Comment by bodnia** [comment]
@silvano-lohn could you please clarify if this issue is still reproduced or the issue may be closed?

**Comment by webron** [comment]
Should no longer be an issue in 3.X.
