### ISSUE TITLE
Primitive long rendered as integer in model definitions

### ISSUE THREAD

**Issue by moeomer** [swagger-api/swagger-ui#1999]
Correctly defined Long (type = integer, format = int64) are still being rendered as integer in model definitions. Similarly date-time issue from #1183 is also occuring. The example petstore seems to have the same problem, as pet ID is rendered as integer.

**Comment by danjor** [comment]
I confirm that with a correctly defined Long and dateTime the format Long and dateTime is not being displayed, issue from #1183 seems to be still occuring. For the format Long, the type displayed is integer and for the format dateTime the type displayed is string. This is a real problem to understand how to use an API if the format is not displayed.

**Comment by grouchal** [comment]
we are also seeing this error and are also a bit confused about the status of the bug.

**Comment by JaySWang** [comment]
Hi, any progress?

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
