### ISSUE TITLE
Issue with listing of apis

### ISSUE THREAD

**Issue by jithinanneri** [swagger-api/swagger-ui#2000]
If I have two apis from different name spaces, swagger ui lists it incorretcly
For Example:

I have the below two apis.
api 1: Employees.GetEmployees()
api 2 : Customers.GetCustomers()

But the swagger ui list them as 
Employees.GetEmployees()
Employees.GetCustomers()
 Customers.GetEmployees()
 Customers.GetCustomers()

Please help

Thanks
Jithin

**Comment by fehguy** [comment]
Can you explain more?  Is this swagger 1.2 or 2.0?  What version of the UI?

**Comment by jithinanneri** [comment]
Hi,

I am using the following packages.

<package id="Swashbuckle" version="5.2.2" targetFramework="net451" />
<package id="Swashbuckle.Core" version="5.2.2" targetFramework="net451" />

Thanks
Jithin

**Comment by jithinanneri** [comment]
Hi,

I have tried with below package as well, but the response is same.

<package id="Swagger.Net" version="0.5.5" targetFramework="net451" />
  <package id="Swagger.Net.UI" version="1.1.0" targetFramework="net451" />

Thanks
Jithin

From: Jithin Anneri
Sent: Tuesday, March 01, 2016 10:18 AM
To: 'swagger-api/swagger-ui'; swagger-api/swagger-ui
Subject: RE: [swagger-ui] Issue with listing of apis (#2000)

Hi,

I am using the following packages.

<package id="Swashbuckle" version="5.2.2" targetFramework="net451" />
<package id="Swashbuckle.Core" version="5.2.2" targetFramework="net451" />

Thanks
Jithin

**Comment by webron** [comment]
@jithinanneri - that doesn't tell us which version of swagger-ui. Can you also share the spec?

**Comment by jithinanneri** [comment]
Hi Ron,

Hope this helps

[cid:image001.png@01D173B8.E0FEB2A0]
Thanks
Jithin

**Comment by webron** [comment]
Github doesn't support attaching files using email.

**Comment by jithinanneri** [comment]
Hi Ron,
Swagger.net.ui
Version 1.1.0

Thanks
Jithin

**Comment by webron** [comment]
It's unlikely to be the version. The version of the ui should be at the top of the swagger-ui.js file.
We'd still need a copy of your spec to understand the problem.

**Comment by jithinanneri** [comment]
Hi Ron,

This is the version which lists in nuget.

What exactly you mean by spec? Are you looking for the requirement spec?

Thanks
Jithin

**Comment by jithinanneri** [comment]
Hi Ron,

I have apis spread across different namespaces.

For example
Namespace : Company.Corporate.Portal.abc.Api.Controllers
Api : GetCustomers

Namespace:Company.Corporate.Portal.def.Api.Controllers
Api:GetEmployes

Company.Corporate.Portal.ghi.Api.Controllers
Api:GetRevenues

When swagger ui lists the apis , I get nine entries instead of three

1. Company.Corporate.Portal.abc.Api.Controllers.GetCustomers
2. Company.Corporate.Portal.def.Api.Controllers.GetCustomers
3. Company.Corporate.Portal.ghi.Api.Controllers.GetCustomers
4. Company.Corporate.Portal.abc.Api.Controllers. GetEmployes
5. Company.Corporate.Portal.def.Api.Controllers. GetEmployes
6. Company.Corporate.Portal.ghi.Api.Controllers. GetEmployes
7. Company.Corporate.Portal.abc.Api.Controllers. GetRevenues
8. Company.Corporate.Portal.def.Api.Controllers. GetRevenues
9. Company.Corporate.Portal.ghi.Api.Controllers. GetRevenues


Thanks
Jithin



From: Jithin Anneri
Sent: Tuesday, March 01, 2016 1:45 PM
To: 'swagger-api/swagger-ui'; swagger-api/swagger-ui
Subject: RE: [swagger-ui] Issue with listing of apis (#2000)

Hi Ron,

This is the version which lists in nuget.

What exactly you mean by spec? Are you looking for the requirement spec?

Thanks
Jithin

**Comment by webron** [comment]
@jithinanneri Swashbuckle is a separate library that allows for you to generate a Swagger spec from your code, and that is consumed by swagger-ui. Swashbuckle also wraps swagger-ui and provides it to you out of the box. We do not write nor maintain Swashbuckle and we don't know which version of swagger-ui it wraps (so giving us Swashbuckle related components and versions doesn't help us).

At the end of the day, Swashbuckle produces a swagger.json file (something like http://petstore.swagger.io/v2/swagger.json), that's your swagger spec (and the file we need to see). swagger-ui simply takes specs and displays them - it doesn't care what produces those specs. In order to find where the spec is hosted and how you can access it directly (and you can), I'd suggest reading Swashbuckle's documentation which includes that information.
