### ISSUE TITLE
IE does not load/install custom fonts

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#2002]
IE 10 reports this for the 2 "/fonts/DroidSans" fonts:

CSS3114 "@font-face failed OpenType embedding permission check. Permission must be Installable."

I know nothing about fonts, but a quick Google-search shows that the actual font files need to be created with some "embedding bits set to Installable" (so, it might not be only server configuration fixable); see: http://stackoverflow.com/questions/5587956/make-adobe-fonts-work-with-css3-font-face-in-ie9

Thanks.

**Comment by fehguy** [comment]
Can you please test with master?  I believe we had some font voodoo for a while, fixed by @bodnia

**Comment by hlubovac** [comment]
I saw this on master/dist.
