### ISSUE TITLE
curl "Accept" header issue in relation to the "Response Content Type" selection

### ISSUE THREAD

**Issue by kchsieh** [swagger-api/swagger-ui#2003]
I am using v2.1.4, for some reason the "Response Content Type" does not show up with the spec below and the generated curl command is this (notice the --header 'Accept: text/html' which is strange and nowhere to be found in my spec):

`curl -X GET --header 'Accept: text/html' --header 'app_id: my_id_here' --header 'app_key: my_key_here' --header 'sid: 123456' 'http://localhost:3000/student'`

```
{
  "swagger": "2.0",
  "info": {
    "description": "This is a sample spec.",
    "version": "1.0.0",
    "title": "Debug the ui",
    "contact": {
      "email": "do-not-reply@berkeley.edu"
    }
  },
  "host": "localhost:3000",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/xml",
    "application/json"
  ],
  "paths": {
    "/student": {
      "get": {
        "summary": "Sample of REST service",
        "description": "Dummy spec. to debug the swagger-ui accept issue.",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "app_id",
            "description": "3Scale id",
            "default": "my_id_here",
            "required": true,
            "type": "string"
          },
          {
            "in": "header",
            "name": "app_key",
            "description": "3Scale key",
            "default": "my_key_here",
            "required": true,
            "type": "string"
          },
          {
            "in": "header",
            "name": "sid",
            "description": "Studet ID",
            "default": "123456",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful"
          },
          "404": {
            "description": "Something is wrong"
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
It doesn't appear because your `200` response doesn't state it returns anything. The issue with the `curl` is different.

**Comment by kchsieh** [comment]
Thanks for the tip, I have updated my swagger.json to include schema (see below) and the "Response Content Type" selection is showing up.  But the generated curl header still says 'application/json', when I selected 'application/xml':
`curl -X GET --header "Accept: application/json" --header "app_id: my_id_here" --header "app_key: my_key_here" --header "sid: 123456" "http://localhost:3000/student"`


**Updated swagger.json:**
```
{
  "swagger": "2.0",
  "info": {
    "description": "This is a sample spec.",
    "version": "1.0.0",
    "title": "Debug the ui",
    "contact": {
      "email": "do-not-reply@berkeley.edu"
    }
  },
  "host": "localhost:3000",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/xml",
    "application/json"
  ],
  "paths": {
    "/student": {
      "get": {
        "summary": "Sample of REST service",
        "description": "Dummy spec. to debug the swagger-ui accept issue.",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "app_id",
            "description": "3Scale id",
            "default": "my_id_here",
            "required": true,
            "type": "string"
          },
          {
            "in": "header",
            "name": "app_key",
            "description": "3Scale key",
            "default": "my_key_here",
            "required": true,
            "type": "string"
          },
          {
            "in": "header",
            "name": "sid",
            "description": "Studet ID",
            "default": "123456",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": { "type": "string" }
          },
          "404": {
            "description": "Something is wrong"
          }
        }
      }
    }
  }
}
```

**Comment by xpxu** [comment]
To make it more simple, I think you can delete "produces" in "student" and try it again. A "produces" on the top level is enough.

**Comment by kevprice83** [comment]
This has been tried and the same error is still produced.

**Comment by kevprice83** [comment]
Still experiencing the same problem as described above. Any update on a fix for this?

**Comment by kevprice83** [comment]
any updates on this issue?

**Comment by jlh424** [comment]
I am having the same problem, with 'Accept: text/html' showing up in the curl command even though I have not specified that anywhere.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/efb77652274e99893b11848f02d9dc37d07344aa

**Comment by kchsieh** [comment]
@fehguy are you sure this has been fixed.  I just downloaded the code from the dist folder (this is from master branch) and the generated curl command is fixed to "text/html" like below:

```
curl -X GET --header 'Accept: text/html' --header 'app_id: my_id_here' --header 'app_key: my_key_here' --header 'sid: 123456' 'http://localhost:3000/student'
```

**Comment by fehguy** [comment]
@kchsieh it's been extensively tested, but there's always the possibility of an issue.  Can you please share the definition that is producing this?

**Comment by kchsieh** [comment]
@fehguy , thanks for the quick response.  My swagger.json spec. is in my March 1st comment above.

**Comment by fehguy** [comment]
OK I just tested this and get the following:

```
curl -X GET --header 'Accept: application/json' --header 'app_id: my_id_here' --header 'app_key: my_key_here' --header 'sid: 123456' 'http://localhost:3000/student'
```

Can you please make sure you don't have a cached copy of swagger-ui.js in your browser?

This issue was originally against ef0fc16276847b22e43a1dc488e246faf20e6e8b but I've updated it to the release 2.1.15 in https://github.com/swagger-api/swagger-ui/pull/2245

**Comment by fehguy** [comment]
@kchsieh please pull master / dist and retest?

**Comment by kchsieh** [comment]
@fehguy , just downloaded master/dist again and this time I tested it without put them into my Rails application (suspect it was caching somehow).  But when I select 'application/xml' from the 'Response Content Type', the generated curl script still says 'application/json'.  Fyi, tested using 3 different browsers and got the same issue.

**Comment by fehguy** [comment]
OK to be clear, you're now getting a different response than before?

**Comment by kchsieh** [comment]
correct
