### ISSUE TITLE
Easier branding and customization: variables for colors

### ISSUE THREAD

**Issue by hangtwenty** [swagger-api/swagger-ui#2006]
If the colors were all done with variables, or possibly some variables and some color functions, it would be easier for organizations to brand Swagger UI. Since [LESS is already used](https://github.com/jensoleg/swagger-ui/tree/master/src/main/less) it would just be a matter of refactoring. Then people could edit colors more easily (and I think changing up the colors is probably one of the most first changes people may want to make when branding to match their organization's brand).

**Comment by webron** [comment]
The new UI should allow you to much more easily customize it.
