### ISSUE TITLE
Preview pane folded sections not kept while editing

### ISSUE THREAD

**Issue by zanona** [swagger-api/swagger-ui#2007]
Sometimes, when editing documents, even though that are a few paths of the preview which are folded and if there is an error on the markup for example, all folded sections will open in the preview section meaning that, quite constantly I would have to manually close all of the again to focus on a specific area. With an API with more than 20 endpoints it becomes quite difficult to manage if all code and preview folding are not kept in sync unfortunately.

**Comment by webron** [comment]
Are you referring to swagger-editor?

**Comment by zanona** [comment]
Sorry @webron, I didn't realise it was a different repository. I will post it over there.
