### ISSUE TITLE
Is swagger-UI support area in WebApi？

### ISSUE THREAD

**Issue by jiangxiaoqiang** [swagger-api/swagger-ui#2010]
My route rule like this:

```
        public override void RegisterArea(AreaRegistrationContext context)
        {
            context.MapRoute(
                "Collect_default",
                "Collect/{controller}/{action}/{id}",
                new { action = "Index", id = UrlParameter.Optional }
            );
        }
```

How to make swagger-ui support this structure(Areas in WebApi),like ASP.NET MVC Area?

**Comment by webron** [comment]
Support what structure? swagger-ui renders Swagger spec files - the code you shared doesn't give us that information.

**Comment by youngj1805** [comment]
is the swagger support mvc areas document api controller follow areas
ex: 
http://localhost//swagger/ui => for main api
http://localhost/{area}/swagger/ui => for area api

**Comment by kalexii** [comment]
I'm sorry but "is the swagger support mvc areas document api controller follow areas" looks like unordered collection of words to me. Can you clarify, is any steps required to enable Area support?
I'm using Swagger-Net which is a fork of Swashbuckle with latest Swagger onboard, however I can't just go "localhost/{area}/swagger/ui", it goes 404 on me.

**Comment by hujingbao** [comment]
Is there anybody who can answer this question?

**Comment by gaborbalazs** [comment]
Any update?

**Comment by shockey** [comment]
This is out of scope for Swagger UI itself - being able to support areas and have multiple UIs deployed for each of them is a question for higher-level tools that make use of Swagger UI.
