### ISSUE TITLE
path parameter: Can we rewrite url like /class/{name}/ to be /class/

### ISSUE THREAD

**Issue by xpxu** [swagger-api/swagger-ui#2012]
Hi Expert, 

We have a url like /class/{name}/, and we need to rewrite it to be /class/.  Obviously, {name} is a path parameter here and it can't be empty. 

Is there any workaround to realize it?

Thx  a lot !

**Comment by webron** [comment]
@xpxu I don't understand the question. `/class/` and `/class/{name}` are two distinct URLs. There's no rewriting, you just declare an additional path.

**Comment by xpxu** [comment]
@webron It's simple to use two distinct URLs, but given our situation, It's better to use just one URL(i.e. /class/{name}/). Note that there is a '/' at the end. 

In a word, we want to use one URL to process the following situations:
/class/
/class/steven/

Can we do that with current Swagger UI?

**Comment by fehguy** [comment]
@xpxu no, you cannot.  Those are different urls, the only way it could be one is if `{name}`--the path parameter--was optional, but that's not allowed by the [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
