### ISSUE TITLE
Non-Ascii characters in header values

### ISSUE THREAD

**Issue by firefoxNX** [swagger-api/swagger-ui#2016]
Hi All,

I am trying to send non-ascii characters like emoji's 🍌 or non-English characters (such as Devnagiri) in header value. The request  never gets sent to the server. Since Swagger-UI use jQuery to make XMLHttpRequest - Is it because of jQuery that non-ascii characters in header values are blocked?

**Comment by webron** [comment]
We no longer use jQuery. Try the latest version.
