### ISSUE TITLE
Using allOf: JSON Schema in Swagger 2.0 Data Definitions

### ISSUE THREAD

**Issue by stevendearborn** [swagger-api/swagger-ui#2019]
I am reusing components of data definitions in more complex ones, using allOf: - $ref: '<component location and name>'.  All parses fine, however when I try to 'Send Request' in Swagger UI, instances of component types seems to replicate on each request. Swagger UI does not seem to manage these objects correctly.

I would prefer to reuse component data definitions rather than copy & paste, since manually doing so will generate human errors and inconsistencies between copy definitions.

Is there another way to define a property of an object is another complex data definition?

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
