### ISSUE TITLE
Swagger-UI defaulting to https for basePath when testing the API

### ISSUE THREAD

**Issue by maneeshsahu** [swagger-api/swagger-ui#2022]
I have a Swagger UI that I load from a https location. If the swagger resource has a basePath of http://address/, and I click 'Try it out!' on an API, the Request URL is modified with a https:// and therefore the call fails.

**Comment by fehguy** [comment]
This is a browser limitation.  If you load from a secure page, you cannot call a non-ssl API.  There are ways to do it, but with a proxy.
