### ISSUE TITLE
Uncaught ReferenceError: JSONEditor is not defined

### ISSUE THREAD

**Issue by boly38** [swagger-api/swagger-ui#2023]
I am using swagger UI since more than 6 weeks without any issue.

Each build of my app will get back the latest https://github.com/swagger-api/swagger-ui/archive/master.tar.gz ,  unpack it and use it as dependency.

Today (@version v2.1.4 ) I'm facing this issue on google chrome and on firefox. A Javascript error on page load :

`Uncaught ReferenceError: JSONEditor is not defined`

(cf stack into attached image )
![capturesw](https://cloud.githubusercontent.com/assets/3100576/13666075/f3bcef6e-e6af-11e5-95d6-52b061831aa5.JPG)

So the swagguer UI is not available.. Do you have any idea on how to fix it ?

Seems on firefox  the following action fix the issue :

- Options > "advanced" section> tab "network" >"Clear now" under "Offline Web Content and User Data"

but I'm unable to fix it on google chrome.

I tried suggested workaround [here ](https://github.com/josdejong/jsoneditor/issues/100) without success.

thanks

**Comment by boly38** [comment]
Ok just found it. Nothing elated to swagger code but an integration issue (not to say that issue were between the chair and keyboard..)
I'm using maven-download-plugin to wget the swagger-ui distrib master.zip file,. By default this maven plugin cache the downloaded artifact into maven repository. 

With wget>skipCache argument, I am able to download v2.1.4. So this case, on my dev env, I see that there is some new changes (since v2.1.0) on swagger `dist/index.html`. 

Following this changes there is no more javascript error of course. Sorry for this noise, I close the issue

**Comment by malcolmsparks** [comment]
I'm getting exactly the same error with 2.1.4 - in both firefox and chrome:

![ff](https://cloud.githubusercontent.com/assets/163131/15904454/0283c0be-2da9-11e6-8408-326eadbf4ba2.png)

**Comment by fehguy** [comment]
I'm guessing that you have different script imports in your html file than are in the [dist/index.html](https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html).  Can you please make sure that you have the same files?

**Comment by malcolmsparks** [comment]
That was it, thanks!

**Comment by knolleary** [comment]
Minor point, but needs making: this is a breaking change that was made in a Patch level version number change.... if you were embedding swagger-ui in your own app, you ought to expect to pick up patch level changes without having to modify anything for things to still work.

The requirement to add JSONEditor as a new import ought to have been done under a Minor version change (ie 2.1.3 -> 2.2.0).

**Comment by fehguy** [comment]
Totally agree, sorry about that--it should have been a non-patch version.
