### ISSUE TITLE
DELETE API Is Not Working through Swagger-ui-master

### ISSUE THREAD

**Issue by oshin-talreja** [swagger-api/swagger-ui#2024]
DELETE API which has JSON Request is not working through Swagger ui master. It showing an eror message: **HTTP Status 415 - Unsupported Media Type</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Unsupported Media Type</u></p><p><b>description</b> <u>The server refused this request because the request entity is in a format not supported by the requested resource for the requested method.**

**Comment by webron** [comment]
What do you see in the network console when you run the operation?

**Comment by webron** [comment]
Closing due to lack of response. Reopen if needed.
