### ISSUE TITLE
Problem with defining array of objects in yaml in swagger

### ISSUE THREAD

**Issue by narottam88** [swagger-api/swagger-ui#2028]
I am having problem in defining the array of objects in yaml.Swagger editor is giving error every time I try to define the type: array part of the ymal.I defined it, but it is not write as it is giving error.Following is the json I am trying to define in swagger yaml.
```
{
	"CountryCombo": {
		"options": {
			"option": [{
				"id": "GB",
				"value": "GB Great Britain"
			}, {
				"id": "US",
				"value": "US United States"
			}, {
				"id": "AD",
				"value": "AD Andorra, Principality of"
			}, {
				"id": "AE",
				"value": "AE United Arab Emirates"
			}, {
				"id": "AG",
				"value": "AG Antigua and Barbuda"
			}, {
				"id": "AI",
				"value": "AI Anguilla"
			}, {
				"id": "AL",
				"value": "AL Albania"
			}, {
				"id": "AM",
				"value": "AM Armenia"
			}, {
				"id": "AN",
				"value": "AN Netherlands Antilles"
			}, {
				"id": "AO",
				"value": "AO Angola"
			}, {
				"id": "AQ",
				"value": "AQ Antarctica"
			}]
		}
	}
}
```
Can anyone suggest me how would I define this json in yaml?

**Comment by fehguy** [comment]
First, that's not a valid definition.  For a model schema, you need to use `properties` for each of the items.

Next, you should open a swagger-editor issue in the https://github.com/swagger-api/swagger-editor project.
