### ISSUE TITLE
Title as model name for definition

### ISSUE THREAD

**Issue by gaplyk** [swagger-api/swagger-ui#2029]
After generation of schema i'm getting 

```json
{
 "definitions" :{
   "SomeRequest": {
      "title": "Cool request structure.",
      "description": "This is request object.",
      "type": "object",
      "required": [
        "field"
      ],
      "properties": {
        "field": {
          "description": "Field is a string",
          "type": "string",
        }
      },
    },
 }
}
```

and on the page I see:
```
Cool request structure. { 
   field (string): Field is a string
}
```

I don't think this is appropriate to use title as Model Name.

**Comment by webron** [comment]
Should be fixed by https://github.com/swagger-api/swagger-js/pull/735.

**Comment by stoicflame** [comment]
So, I hate to be contrary, but what if I _liked_ using the title? When you're dealing with swagger.json files that have been generated by code generators, the model name is often ugly...
