### ISSUE TITLE
Random behavior in Swagger-UI rendering

### ISSUE THREAD

**Issue by asteriosm** [swagger-api/swagger-ui#2032]
I have a GET rest service (among others).
First of all, when I deploy my application in some cases, the swagger-ui hangs I see this:

![renderingswagger](https://cloud.githubusercontent.com/assets/4466518/13810562/2f765810-eb79-11e5-86f8-0931b76fe1d6.png)

And I see only 2 out of 7 tags (chdconstands and hazmat)

Then I redeploy my application **with no changes in my code** and I see the same thing.
I redeploy many times and in some random time (second, third deploy) **with no changes in my code**
I see this:

![swaggerall](https://cloud.githubusercontent.com/assets/4466518/13810656/9b67f3bc-eb79-11e5-9f38-97bcc421e696.png)

which are all my tags.

Then in some of my rest service the @QueryParam interpreted as **body** by swagger

![hazmatbody](https://cloud.githubusercontent.com/assets/4466518/13810745/fedad3c4-eb79-11e5-81f3-b08410204e4b.png)

Then I redeploy my application **with no changes in my code** and I see the same thing.
I redeploy many times and in some random time (second, third deploy) **with no changes in my code**
I see this:

![hazmatok](https://cloud.githubusercontent.com/assets/4466518/13810758/153e0f46-eb7a-11e5-8e4a-ae6205db9ef0.png)

How is this possible?

```
@ApplicationScoped
@Path(ChdRESTConstants.HAZMAT_ITEM_MODULE)
@Produces(MediaType.APPLICATION_JSON)
@Api(value = "Hazmat")
public class HazmatRestService extends BaseRESTService {

    @Inject
    ChdHazmatManager chdHazmatManager;

    @Inject
    ChdLoggingManager chdLoggingManager;

    @GET
    @Path("{hazmatId}")
    @ApiOperation(value = "Get a Hazmat based on ID", response = HazmatDetailsDTO.class, responseContainer = "")
    @ApiResponses(value = { @ApiResponse(code = 400, message = ApiResponseMessages.INVALID_REQUEST, response = ErrorContainer.class),
            @ApiResponse(code = 500, message = ApiResponseMessages.INTERNAL_SERVER_ERROR, response = ErrorContainer.class),
            @ApiResponse(code = 503, message = ApiResponseMessages.SERVICE_UNAVAILABLE, response = ErrorContainer.class) })
    public Response getHazmat(@PathParam(ChdRESTConstants.HAZMAT_ID) @ApiParam(defaultValue = "IMDG_0001") String hazmatId,
            @QueryParam(SharedRESTConstants.VERSION_TYPE) @ApiParam(defaultValue = "ONLINE", required = true) VersionType versionType) {
        try {
            ValidationUtil.validateEnum(VersionType.class, versionType, false);
            HazmatDetailsDTO hazmatDetailsDTO = chdHazmatManager.getHazmat(hazmatId, versionType);

            return Response.ok().entity(hazmatDetailsDTO).build();
        } catch (HazmatException e) {
            return handleException(e);
        }
    }
```

The swagger dependency:

```
<dependency>
	<groupId>io.swagger</groupId>
	<artifactId>swagger-jersey-jaxrs</artifactId>
	<version>1.5.6</version>
</dependency>
```

**Comment by webron** [comment]
@asteriosm you didn't mention which version of swagger-ui you're using.

As for the issue itself, the inconsistency is indeed odd, but it's unclear if the root is swagger-ui or swagger-core. To investigate it further, you should save the *spec* you're getting when you see one behavior, and compare it to the spec you're getting when the behavior is off. If they are the same, the issue is indeed with swagger-ui. If they are different, the issue is with swagger-core.

**Comment by asteriosm** [comment]
@webron I am using swagger ui 2.1.4

I compared the spec of **body** with **correct** interpretation and has differences

![diffs-body-correct](https://cloud.githubusercontent.com/assets/4466518/13819625/e8171818-eba2-11e5-93e6-912647d731c7.png)

So apparently the issue is with swagger-core (probably).

**Comment by webron** [comment]
In that case, please open the ticket on swagger-core - though I'll admit this is extremely odd. As a first step, I'd suggest upgrading to 1.5.8, and if you encounter the issue again, by all means open the ticket there and we'll investigate it with you.
