### ISSUE TITLE
Relative URLs for swagger.json don't work correctly

### ISSUE THREAD

**Issue by f8k8** [swagger-api/swagger-ui#2033]
When specifying a relative URL for the swagger.json file, if the URL for the main page specifies a document (such as index.html), the generated URL for the swagger.json file is incorrect. E.g. accessing something like:

http://example.com/documentation/index.html

Specifying ./swagger.json for the JSON URL results in a URL of:

http://example.com/documentation/index.html/./swagger.json

Instead of:

http://example.com/documentation/./swagger.json

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
