### ISSUE TITLE
Swagger UI not rendering

### ISSUE THREAD

**Issue by sstrange** [swagger-api/swagger-ui#2035]
I've followed the instructions and am able to get my raw swagger JSON at "http://localhost:16715/swagger/docs/v1" with all my XML comments.  I can copy/paste this into editor.swagger.io and it displays ok. 

But "http://localhost:16715/swagger/" is not rendering. This is the screenshot with javascript console.
Anyone know what the issue could be?
![image](https://cloud.githubusercontent.com/assets/7025212/13823387/8bb6dfe0-eb66-11e5-9451-dfa580320216.png)

**Comment by webron** [comment]
Which instructions? You're missing some critical files there.

**Comment by sstrange** [comment]
I followed the instructions [here](https://github.com/domaindrivendev/Swashbuckle).
I've added the swashbuckle nuget package, edited SwaggerConfig.cs, and pointed it to my xml comment file.  
`using System.Web.Http;
using WebActivatorEx;
using Edi.Address.Service;
using Swashbuckle.Application;

[assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]

namespace Edi.Address.Service
{
    public class SwaggerConfig
    {
        public static void Register()
        {
            var thisAssembly = typeof(SwaggerConfig).Assembly;

            GlobalConfiguration.Configuration
                .EnableSwagger(c =>
                {   
                    c.SingleApiVersion("v1", "name of my service");
                    c.IncludeXmlComments(string.Format(@"{0}bin\AddressService.XML",
                        System.AppDomain.CurrentDomain.BaseDirectory));
                })
            .EnableSwaggerUi();
        }
    }
}`

**Comment by webron** [comment]
Then that's an issue you should open with Swashbuckle. If you just take the files under the /dist folder in this repo, put them in your app as static files and point the index.html to your Swagger spec generated by Swashbuckle, you won't have the above issue.

**Comment by vimcat** [comment]
Reproduce this issue by loading index.html from dist. It tries to load jQuery but fails because require is undefined.

**Comment by sstrange** [comment]
Thanks for the replies. 
I'm able to load /dist/index.html when /dist is added as static files and pointed to my swagger json.   The swashbuckle index.html at /swagger still has the above issue when I load it from localhost, but strangely it works when I deploy it.  I have no idea what's going on. 

@vimcat please expound on "fails because require is undefined"

**Comment by vimcat** [comment]
![screen shot 2016-03-28 at 3 43 35 pm](https://cloud.githubusercontent.com/assets/76280/14092472/f1a825ae-f4fb-11e5-9e80-c6220b3fd1bf.png)

**Comment by vimcat** [comment]
![screen shot 2016-03-28 at 3 45 03 pm](https://cloud.githubusercontent.com/assets/76280/14092498/1a53334a-f4fc-11e5-8f27-e21e69f60a3c.png)

**Comment by vimcat** [comment]
I have it working now, I was trying to load the files that were installed via jspm. I forked the repo, rebuilt dist and copied over everything under dist into my static swagger folder.

**Comment by webron** [comment]
Seems like this can be closed now. Please reopen if needed.
