### ISSUE TITLE
Support for multiple body parameters

### ISSUE THREAD

**Issue by bmmathe** [swagger-api/swagger-ui#2036]
I know there can only be one body parameter but it would be nice to break out the body parameters (like form parameters) so you can document each one of them independently and supply them like a form post.  One drawback for using form parameters if you can't click the "Model" and have a complex type filled out for you in the text box.  Essentially the way this would work is you would make multiple body parameters and they would be compiled into one json document upon submit.

**Comment by webron** [comment]
There really is no reasonable way of doing that - way too many edge cases.
However, try setting `jsonEditor` to `true` - https://github.com/swagger-api/swagger-ui#parameters and see if that helps.

**Comment by webron** [comment]
Oh, and lovely dog :)

**Comment by webron** [comment]
Closing for no feedback. Feel free to reopen.
