### ISSUE TITLE
Swagger cannot specify path application

### ISSUE THREAD

**Issue by careerly** [swagger-api/swagger-ui#2037]
When reporting a bug, please provide the following details:
- swagger-ui version 2.1.4

![image](https://cloud.githubusercontent.com/assets/6613507/13842254/2b56871a-ec68-11e5-915b-add054495c7d.png)

![image](https://cloud.githubusercontent.com/assets/6613507/13842274/4a3ff544-ec68-11e5-9d2f-e40c93645a49.png)

When you get a getApiListing interface, you can support the configuration of the specified path app, because the api-doc interface is not consistent with the actual interface path is not consistent with the actual interface path

**Comment by webron** [comment]
Can you provide more details? The issue is unclear.

**Comment by careerly** [comment]
Sorry, this is not a question of UI swagger, thank you
