### ISSUE TITLE
Current build does not pass Travis CI test

### ISSUE THREAD

**Issue by f8k8** [swagger-api/swagger-ui#2038]
As of commit 52f3b6d50ec727a8f4d8ddd06388a7edb5d4f97e the Travis CI test is failing. After fixing what I think is an unrelated path issue for the V2 test on Windows (the test was using \ instead of / as part of the URL for the petstore.json on Windows - see commit 7df2785776ca850a7e6d5dcb8577a269a2a4fca7), the test run fine locally, so I'm wondering if this is maybe to do with the node version being used in the test. Locally I have 5.5.0, and the test runs on 4.2. Running npm version gives:
`npm version
{ 'swagger-ui': '2.1.4',
  npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.5.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }`

And running npm test gives:

> swagger 1.x spec tests
> waiting for server to start
> waiting for UI to load
>     V should have "Swagger UI" in title
>     V should render element: swagger-ui-container (54ms)
>     V should render element: resources_container
>     V should render element: api_info
>     V should render element: resource_pet
>     V should render element: resource_store
>     V should render element: resource_user
>     V should render element: header
>     - should find the contact name element
>     V should find the pet link (60ms)
>     - should find the pet resource description
>     V should find the user link (62ms)
>     V should find the store link (53ms)
> 
>   swagger 2.0 spec tests
> waiting for server to start
> waiting for UI to load
>     V should have "Swagger UI" in title
>     V should render element: swagger-ui-container
>     V should render element: resources_container
>     V should render element: api_info
>     V should render element: resource_pet
>     V should render element: resource_store
>     V should render element: resource_user
>     V should render element: header
>     V should find the contact name element
>     V should find the contact email element
>     V should find the contact url element
>     V should find the pet link (62ms)
>     V should find the pet resource description (54ms)
>     V should find the user link (48ms)
>     V should find the store link (50ms)
> 
> 
>   26 passing (15s)
>   2 pending

**Comment by webron** [comment]
Should be fixed now, thanks.
