### ISSUE TITLE
Switch Authorize and Explore buttons

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-ui#2043]
We recently introduced the new authorization integration in the system, and the `Authorize` button appears next to the URL bar and the `Explore` button appears after it.

We should switch the location of the buttons. The `Explore` is affected by the URL bar, and the `Authorize` appears only if there are security requirements that are described in the spec.

**Comment by srlopez** [comment]
Hi @webron Ron, @KarimJedda
How can i insert 'security requirements' in my yaml.

I just installed 'connexion' and test my api.yaml, but i cannot see any 'Authorize' button.
I try to test with this [https://github.com/KarimJedda/connexion_jwt_example](https://github.com/KarimJedda/connexion_jwt_example)  

This is the api
```
swagger: '2.0'
basePath: /api
info:
  title: Dummy Api

paths:
  '/stuff':
    get:
      tags: [stuff]
      operationId: zblaaaa.get_secret
      summary: Give me sugar sugar
      responses:
        200:
          description: Something secret

securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
```

Thanks in advance

**Comment by webron** [comment]
@srlopez why are you commenting on this here? This is unrelated to the issue on the ticket. If you encouter an issue, please open a separate ticket on it.

**Comment by srlopez** [comment]
Sorry @webron , I remove my question, and this comment too.
Just i need some help to show the `Authorize` button
