### ISSUE TITLE
String array with enum no longer showing as options

### ISSUE THREAD

**Issue by perrydt** [swagger-api/swagger-ui#2050]
In version 2.1.3 and earlier, a string array with enums would display as a multi-select control, but in 2.1.4 it's just displaying textarea like it would for a string array with no enum:

``` json
{
  "name": "subscriptionStatus",
  "in": "query",
  "required": false,
  "type": "array",
  "items": {
    "type": "string",
    "enum": [
      "subscribed",
      "trial",
      "unsubscribed"
    ]
  },
  "collectionFormat": "multi"
},
```

The above used to display as a multi-select with options <blank>, subscribed, trial, and unsubscribed but is just a textarea in 2.1.4.

I'm noticing the same behavior in the Petstore example now (e.g. for the 'status' parameter of findByStatus).  Is it intentional?  The problem is that without the multi-select the UI gives no indication of what values are even allowed.

**Comment by webron** [comment]
Thanks for reporting, this is indeed a regression.

**Comment by webron** [comment]
Should no longer be an issue with 3.0.
