### ISSUE TITLE
Incorrect escaping of double qoutes 

### ISSUE THREAD

**Issue by tjwise** [swagger-api/swagger-ui#2059]
Using swagger.ui v2.1.4, And I have a service that POSTs one JSON string parameter.  Any double quote marks in that string gets escaped, and sent literally to the service, causing a parsing error.  That is, I enter in Swagger.ui Value field

{"Name":"Tom West", "City": "Boston"}

Both request and response content type are application/json.  However, what gets sent to the service is:

{\"Name\":\"Tom West\", \"City\": \"Boston\"}

The curl command shows similarly:

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '"{\"Name\":\"Tom West\", \"City\": \"Boston\"}"' 'http://localhost:9000/service-under-test'

Notice that the entire string is enclosed in single and double quotes.  I can copy and strip the backslashes from the string, and the opening/closing double quote, and it will work correctly.

I'm running on Win 10.  The copy/paste of the curl fails with git-bash.

**Comment by DavidBiesack** [comment]
Maybe close this as a dup of #2058 ?

**Comment by webron** [comment]
Thanks @DavidBiesack.
