### ISSUE TITLE
/scheme routes don't work

### ISSUE THREAD

**Issue by chatch** [swagger-api/swagger-ui#2061]
Any api path with name 'scheme' fails when loading the swagger ui front page. 

Stack trace:

TypeError: api is undefined
[3]</SwaggerClient.prototype.makeUniqueOperationId()
 swagger-ui.js:1728
[3]</SwaggerClient.prototype.buildFromSpec/</</<()
 swagger-ui.js:1648
arrayEach()
 swagger-ui.js:12028
createForEach/<()
 swagger-ui.js:13361
[3]</SwaggerClient.prototype.buildFromSpec/</<()
 swagger-ui.js:1606

Problem seems to be that the SwaggerClient has a field 'scheme' for storing the HTTP scheme. So in my case it's 'http'.

swagger-ui version: 2.1.4
swagger file attached: i've hacked one of the petstore samples to define a /scheme path.

[swagger.txt](https://github.com/swagger-api/swagger-ui/files/189187/swagger.txt)

**Comment by webron** [comment]
Shouldn't be an issue with 3.X.
