### ISSUE TITLE
Clicking on operations in Internet Explorer opens new tabs

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#2063]
I cloned the latest swagger-ui from GitHub and viewed petstore.

Selection actions in the UI are opening new tabs. 
For example, clicking on a Tag to expand the operations in the tag opens a new tab.
The tag gets expanded in the original tab.
Clicking on an operation both expands the operation and opens a new tab.

Other users experience the same problem, all in Internet Explorer.

The problem does not exist in Chrome or Firefox.

**Comment by fehguy** [comment]
Can you please try applying this patch:

https://github.com/swagger-api/swagger-ui/pull/2044

To see if it solves your issue?

**Comment by DavidBiesack** [comment]
The various click actions in Internet Explorer 11 no longer open a new tab. That was all the validation I did. See details in #2044

**Comment by sheepcount** [comment]
These changes fixed the issue for me as well, both on IE 11 and IE 10. Thanks!

**Comment by webron** [comment]
Closing as should be fixed. Please reopen otherwise.
