### ISSUE TITLE
malformed accept header

### ISSUE THREAD

**Issue by lfender6445** [swagger-api/swagger-ui#2065]
using swagger ui v2.1.4

using swagger blocks ruby gem:

```ruby
          parameter do
            key :name, 'ACCEPT'
            key :in, :header
            key :required, true
            key :type, :string
          end
```

in this case I am submitting `application/vnd.foo.api+json;foo=bar` as the accept header

but i see that `Accept: 2, application/vnd.rentpath.api+json;foo=bar` is being sent up in the network request. Where is the number 2 coming from?

**Comment by fehguy** [comment]
Share more details, this isn't enough to help effectively

**Comment by lfender6445** [comment]
apologies, opened the issue prematurely. i had bad `produces` key which was set to status '204' rather than mime type. specifying empty array fixed it
