### ISSUE TITLE
Translation failures

### ISSUE THREAD

**Issue by xiaolongyuan** [swagger-api/swagger-ui#2066]
When reporting a bug, please provide the following details:
- swagger-ui 2.1.4

```
 <script src='webjars/springfox-swagger-ui/lang/translator.js' type='text/javascript'></script>
    <script src='webjars/springfox-swagger-ui/lang/zh-cn.js' type='text/javascript'></script>
```

`index.js:24Uncaught TypeError: Cannot read property 'toLowerCase' of undefined(anonymous function) @ index.js:24Handlebars.templates.param_list.Handlebars.template.main @ client.js:374e @ handlebars-2.0.0.js:27SwaggerUi.Views.ParameterView.Backbone.View.extend.render @ index.js:24SwaggerUi.Views.OperationView.Backbone.View.extend.addParameter @ index.js:24SwaggerUi.Views.OperationView.Backbone.View.extend.render @ index.js:24SwaggerUi.Views.ResourceView.Backbone.View.extend.addOperation @ index.js:24SwaggerUi.Views.ResourceView.Backbone.View.extend.render @ index.js:24SwaggerUi.Views.MainView.Backbone.View.extend.addResource @ index.js:24SwaggerUi.Views.MainView.Backbone.View.extend.render @ index.js:24window.SwaggerUi.Backbone.Router.extend.render @ index.js:24window.SwaggerUi.Backbone.Router.extend.initialize.options.options.success @ index.js:243.SwaggerClient.buildFromSpec @ resolver.js:4496.Resolver.finish @ spec-converter.js:63(anonymous function) @ schema-markup.js:4626.Resolver.resolve @ schema-markup.js:5036.Resolver.finish @ spec-converter.js:67(anonymous function) @ schema-markup.js:4626.Resolver.resolve @ schema-markup.js:5036.Resolver.finish @ spec-converter.js:67(anonymous function) @ schema-markup.js:4626.Resolver.resolve @ schema-markup.js:5036.Resolver.finish @ spec-converter.js:67(anonymous function) @ schema-markup.js:4626.Resolver.resolve @ schema-markup.js:5036.Resolver.finish @ spec-converter.js:67(anonymous function) @ schema-markup.js:4626.Resolver.resolve @ schema-markup.js:5036.Resolver.finish @ spec-converter.js:67(anonymous function) @ schema-markup.js:4626.Resolver.resolve @ schema-markup.js:5036.Resolver.finish @ spec-converter.js:67(anonymous function) @ schema-markup.js:4626.Resolver.resolve @ schema-markup.js:5033.SwaggerClient.build.obj.on.response @ resolver.js:2135.SwaggerHttp.execute.responseInterceptor @ resolver.js:6955.SwaggerHttp.execute.obj.on.response @ resolver.js:699(anonymous function) @ schema-markup.js:206162.Request.callback @ index.js:24(anonymous function) @ index.js:24163.Emitter.emit @ index.js:24162.Request.end.xhr.onreadystatechange @ index.js:24`

**Comment by webron** [comment]
You're using webjars which we do not maintain. Please try using our version directly, and see if the issue persists.
