### ISSUE TITLE
IMO your commit history is poor.

### ISSUE THREAD

**Issue by sclaughl** [swagger-api/swagger-ui#2069]
Why do you have a new commit for each time your dist/ folder is regenerated? Should your dist directory even be committed?

**Comment by webron** [comment]
The dist folder is meant for users who just want to take swagger-ui and use it without requiring them to go through the build process.

**Comment by sclaughl** [comment]
Hey @webron I appreciate the reply, and I do understand where you're coming from. However as a prospective user of swagger-ui, I just wanted to point out that evaluating the history of the project is difficult and tedious, and I believe a lot of that has to do with inclusion of the dist directory. There are a lot of commits with messages such as "rebuilt" and "ran gulp" that add no value to the history, and diffing versions is hindered by the inclusion of dist files, which developers don't particularly care about. In my opinion it would be better to host the distributables separately (maybe using something like GitHub releases or similar?) Just some feedback for your consideration.

Thanks for your work on swagger (along with the rest of the contributors) -- it looks very useful.

--Stuart

**Comment by webron** [comment]
We're still considering options but for now will close the ticket.
