### ISSUE TITLE
Swagger doesn't work on IE 9

### ISSUE THREAD

**Issue by trcora** [swagger-api/swagger-ui#207]
I can't do the Swagger work on IE 9. FF and Chrome work fine. But when I enable the IE debugger and refresh my swagger html, it works fine too.

Have anyone ever had the same problem?

**Comment by spyropol** [comment]
I came across this today. Can you review the log function, make sure it's working. If I add the below in the index.html it doesn't load.
```
    } else {
        url = "http://petstore.swagger.io/v2/swagger.json";
    }
+   log(url);
    window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
```

**Comment by fehguy** [comment]
@spyropol please open a new issue
