### ISSUE TITLE
Feature Request: Show Reponse-Button after hiding Reponse

### ISSUE THREAD

**Issue by alexandermikuta** [swagger-api/swagger-ui#2072]
After pressing "Try it out" and pressing the "hide response"-button currently the button simply disappears. The only way to get back the response would be to make the call with "try it out" again. for longer running calls this is not the ideal solution. It would be nicer if after pressing "hide response" a button "show response" would be shown instead that can display the response again without reloading it from the server.

**Comment by webron** [comment]
This behavior is now different in the new UI.
