### ISSUE TITLE
Json beautify

### ISSUE THREAD

**Issue by easyest** [swagger-api/swagger-ui#2073]
It would be really nice to be able to expand/collapse response json as sometimes response can be really big.

**Comment by SeriousM** [comment]
yes, that would be awesome! also wrap long messages like stacktraces in case of an error so it's readable

**Comment by nielsch** [comment]
yes please!

**Comment by shockey** [comment]
Closing in favor of https://github.com/swagger-api/swagger-ui/issues/4018.
