### ISSUE TITLE
Fail reference resolving with array type without items property

### ISSUE THREAD

**Issue by MugeSo** [swagger-api/swagger-ui#2074]
swagger-ui version: 2.1.4

```json
{
  "swagger": "2.0",

  "basePath": "/api",

  "info": {
    "title": "sample",
    "version": "1.0.0"
  },

  "paths": {
    "/foo": {
      "get": {
        "description": "Foo",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "A list of pets.",
            "schema": {
              "type": "array"
            }
          }
        }
      }
    }
  }
}
```

For example, schema definition for [`json-schema` its self](http://json-schema.org/schema#) has this.

**Comment by fehguy** [comment]
It's not supported.  Per the specification, `items` is required under an array, see the [docs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).

**Comment by MugeSo** [comment]
@fehguy How about this:

```json
{
  "swagger": "2.0",

  "basePath": "/api",

  "info": {
    "title": "sample",
    "version": "1.0.0"
  },

  "paths": {
    "/foo": {
      "get": {
        "description": "Foo",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "A list of pets.",
            "schema": { $ref: 'http://json-schema.org/schema#'  }
          }
        }
      }
    }
  }
}
```

**Comment by fehguy** [comment]
I don't know what you mean--I do suggest reading the specification so you can understand what is possible.

**Comment by MugeSo** [comment]
I got it.

**Comment by MugeSo** [comment]
@fehguy Please teach me where `items` is required in `Schema Object`. 
I can find description about `items` required in `Header Object` and `Parameter Object` but I can't for `Schema Object`

**Comment by ponelat** [comment]
@MugeSo the swagger spec, is based on JSON-Schema, in the [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object) you'll note a reference to `items` which is gets from JSON-Schema.

However, that said. Its a simple property, and you use this description as a reference... https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject

**Comment by MugeSo** [comment]
@ponelat Thanks, I understand `items` in `Items Object` is required when type is `array`.
There is still no description `items` property of `Schema Object`. 
However I found it is just a omission in spec.

I disappointed found that we can not reference many of existing json schema...

Thanks a lot.

**Comment by MugeSo** [comment]
https://github.com/OAI/OpenAPI-Specification/pull/413
https://github.com/OAI/OpenAPI-Specification/issues/404

**Comment by MugeSo** [comment]
@fehguy @ponelat 
I read spec carefully. 
And I feel sure `items` of `Schema Object` is optional for now.

@ponelat refers `Item Object` but it is not for schema in body. 
> A limited subset of JSON-Schema's items object.  It is used by parameter definitions that are not located in "body".

**Comment by webron** [comment]
@MugeSo - as someone who was involved in writing the spec, I can tell you the intent - `items` is mandatory no matter where you declare the type to be an `array`. We can go back and forth on this, but it won't change.
