### ISSUE TITLE
when consumes/produces format is XML, "Example Value" shows XML but with namespace missing; swagger version -- current version in master branch

### ISSUE THREAD

**Issue by yl96** [swagger-api/swagger-ui#2077]
![id_request_xml](https://cloud.githubusercontent.com/assets/1952233/14335858/557b9b10-fc13-11e5-840d-761b69001f98.jpg)
When reporting a bug, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue

**Comment by yl96** [comment]
![id_request_xml_if_with_namespace](https://cloud.githubusercontent.com/assets/1952233/14335873/72be4b3c-fc13-11e5-83a8-1966cf7bb09d.jpg)

**Comment by gaeljw** [comment]
@yl96 please provide your swagger-ui version and swagger file to reproduce

**Comment by yl96** [comment]
the swagger version is current version in master branch by 04/06/2016.  (It is not any formal released versions, which don't support XML at all)

I am sorry that I couldn't provide you  my swagger file.  We are using XML schema and our rest web service consume and produce XML.  

The request XML "Example Value" looks like below.
<?xml version="1.0"?>
<AddCar>
  <startTime>1970-01-01T00:00:00.001Z</startTime>
  <endTime>1970-01-01T00:00:00.001Z</endTime>
</AddCar>

However, ideally we would like having "Example Value" with namespace (xmlns="urn:com.aba.xyz" ) as below:
<?xml version="1.0"?>
<AddCar xmlns="urn:com.aba.xyz">
  <startTime>1970-01-01T00:00:00.001Z</startTime>
  <endTime>1970-01-01T00:00:00.001Z</endTime>
</AddCar>


Please let me know of any further questions.

Thanks,

Liz



Date: Mon, 25 Apr 2016 08:07:55 -0700

**Comment by webron** [comment]
@yl96 - without a Swagger spec file reproducing the issue, we'll have no way to troubleshoot it.

**Comment by bodnia** [comment]
@webron this ticket may be closed too?

**Comment by webron** [comment]
Fixed in master.

**Comment by yl96** [comment]
Thanks for the update!

Date: Wed, 29 Jun 2016 06:55:42 -0700
