### ISSUE TITLE
Don't render "optional" when a field is "read-only"

### ISSUE THREAD

**Issue by HenrikHL** [swagger-api/swagger-ui#2078]
When setting both required=false (which is default value) and readonly=true in @ApiProperty(...) it makes no sense to display "optional" next to the field in the UI (when using "model" displaymode):
**Code:**

```
@ApiModelProperty(value = "End timestamp of the resource...", readOnly = true)
protected Date versionEnd = endDate;

```

**Result in Swagger-UI:**
![image](https://cloud.githubusercontent.com/assets/3489388/14343573/3dcf4964-fca2-11e5-888f-340556230e75.png)

I would expect that readonly fields are fields provided by server - that should never be set by user...

swagger-ui version: 1.5.3

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
