### ISSUE TITLE
x-example interpreted as default field value, but I think it should be a placeholder

### ISSUE THREAD

**Issue by raarts** [swagger-api/swagger-ui#2080]
v2.1.4. When I provide an x-example field in the swagger json like this:

```
        "parameters": [
          {
            "name": "department",
            "in": "query",
            "description": "Filter by department",
            "required": false,
            "type": "integer",
            "format": "int32",
            "x-example": 1
          },
```

the swagger-ui field will already contain '1'. But I think it should be better shown as a placeholder.

**Comment by webron** [comment]
A placeholder how? It doesn't treat it as the default field value, as that shouldn't even be sent (it's the default value that should probably not be put in the field). It acts as what it is - an example.

**Comment by raarts** [comment]
I'm sorry if I'm not clear. I use this in a GET request in a query parameter. The result is that in the Swagger UI the example value is already filled in. So every time when I try it out I end up removing the value from the field. So my suggestion is to render it as a placeholder value.

**Comment by webron** [comment]
Got it. We'll take that under consideration.
