### ISSUE TITLE
Send Authorization Header when loading the json is not working.

### ISSUE THREAD

**Issue by hiteshpatwari** [swagger-api/swagger-ui#2081]
So, I'm trying to make my json file visible only after authentication. I've the necessary authorization requests setup but, I don't see Bearer token being attached to the request when I first load the JSON file.
- swagger-ui version : 2.0
- a swagger file reproducing the issue

```
window.swaggerUi = new SwaggerUi({
      url: url,
      headers: {"Authorization": "Bearer XYZYZYZYZZYZYZYZY="},
      supportHeaderParams: true,
      dom_id: "swagger-ui-container",
      supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
      onComplete: function(swaggerApi, swaggerUi){
        if(window.SwaggerTranslator) {
          window.SwaggerTranslator.translate();
        }

        $('pre code').each(function(i, e) {
          hljs.highlightBlock(e)
        });

        addApiKeyAuthorization();

      },
      onFailure: function(data) {
        log("Unable to Load SwaggerUI");
      },
      docExpansion: "none",
      jsonEditor: false,
      apisSorter: "alpha",
      defaultModelRendering: 'schema',
      showRequestHeaders: true
    });

    function addApiKeyAuthorization(){
      var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", "Bearer XYZYZYZYZZYZYZYZY=", "header");
      window.swaggerUi.api.clientAuthorizations.add("Authorization", apiKeyAuth);
    }

    window.swaggerUi.load();
```

I never see Authorization header being attached to the request.
Can somebody please help me with this.

This is the request Header I see on Chrome console : 

```
accept:application/json;charset=utf-8,*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Cookie: lolcookie-lolcookie
Host: 127.0.0.1
Referer:127.0.0.1/apidocs.json
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
```

**Comment by hiteshpatwari** [comment]
@ponelat @webron  ... please help me with this.

**Comment by nooruddin** [comment]
Did you get this working by any chance?

**Comment by irhabi** [comment]
@hiteshpatwari 
Try to execute addApiKeyAuthorization() inside onFailure function.

**Comment by bodnia** [comment]
There used to be an option to add api key (as query parameter) to all fetches in swagger-ui including  loading json spec. Current implementation does not have such feature to add anything to fetch of json spec.
@webron could you please clarify if such feature (to add headers or query parameters to spec fetch) is planned to be implemented?

**Comment by webron** [comment]
This is related to https://github.com/swagger-api/swagger-ui/issues/2793#issuecomment-289688082. Might be worth checking with @shockey.

**Comment by shockey** [comment]
I'm a fan of @ponelat's final suggestion in the linked comment, if we're going to implement this.

**Comment by webron** [comment]
Please follow #2793.
