### ISSUE TITLE
Javascript error in docs page

### ISSUE THREAD

**Issue by lazar725** [swagger-api/swagger-ui#2084]
I'm using swagger tools version 0.9.15 with swagger ui version 2.1.4, and I'm seeing a js error when viewing the /docs page. My swagger.yaml file has been validated with a yaml validation tool and no errors were found, and it shows fine in swagger editor. I'm attaching a print screen with the error, as well as the code that bootstraps the application:

<img width="943" alt="swagger-docs-error" src="https://cloud.githubusercontent.com/assets/11555813/14451809/a1d78504-0092-11e6-9f5d-66b955db7f46.png">

`'use strict';

var express = require('express');
var app = express();
var swaggerTools = require('swagger-tools');
var jsyaml = require('js-yaml');
var fs = require('fs');
var cors = require('cors');
var serverPort = process.env.PORT || 8080;

// swaggerRouter configuration
var options = {
  swaggerUi: '/swagger.json',
  controllers: './controllers',
  useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
};

// The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
var spec = fs.readFileSync('./api/swagger.yaml', 'utf8');
var swaggerDoc = jsyaml.safeLoad(spec);

// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  // Set CORS
  app.use(cors());

  // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
  app.use(middleware.swaggerMetadata());

  // Validate Swagger requests
  app.use(middleware.swaggerValidator());

  // Route validated requests to appropriate controller
  app.use(middleware.swaggerRouter(options));

  // Serve the Swagger documents and Swagger UI
  app.use(middleware.swaggerUi());

  // Catch 404
  app.use(function (req, res, next) {
      res.status(404).json({ message: 'Path not found', status: 404 });
  });

  // Catch unhandled errors
  app.use(function (err, req, res, next) {
      res.status(500).json({ message: 'Unexpected error', status: 500, err: err });
  });

  /\* Listen */
  app.listen(serverPort, function() {
      console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
      console.log('Swagger-ui is available on http://localhost:%d/docs', serverPort);
  });
});`

**Comment by fehguy** [comment]
Please share the output of your /api-docs call

**Comment by lazar725** [comment]
`{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Pixoneye API",
    "description": "Specification of Pixoneye API server",
    "contact": {
      "name": "nadav.israel@pixoneye.com"
    }
  },
  "host": "pixoneye-api.azurewebsites.net",
  "tags": [
    {
      "name": "Users"
    },
    {
      "name": "Images"
    },
    {
      "name": "Apps"
    },
    {
      "name": "Events"
    },
    {
      "name": "SDK"
    },
    {
      "name": "Dashboard"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "tags": [
          "Apps"
        ],
        "summary": "Customer login",
        "description": "",
        "operationId": "login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "credentials",
            "description": "Credentials sent when a customer tries to login",
            "required": true,
            "schema": {
              "type": "object",
              "items": {
                "$ref": "#/definitions/LoginCredentials"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/TokenModel"
            }
          },
          "401": {
            "description": "Wrong password or username does not exist",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "x-swagger-router-controller": "Apps"
      }
    },
    "/signup": {
      "post": {
        "tags": [
          "Apps"
        ],
        "summary": "Customer sign up. Creates a new row in the Apps table.",
        "description": "",
        "operationId": "signUp",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "credentials",
            "description": "Credentials sent when a customer tries to sign up",
            "required": true,
            "schema": {
              "type": "object",
              "items": {
                "$ref": "#/definitions/SignupCredentials"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/TokenModel"
            }
          },
          "400": {
            "description": "Passwords mismatch or invalid format",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "409": {
            "description": "Username already exists",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "x-swagger-router-controller": "Apps"
      }
    },
    "/apps": {
      "get": {
        "tags": [
          "Apps"
        ],
        "summary": "Get a list of all apps",
        "description": "",
        "operationId": "getAppsList",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/app"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Apps"
      }
    },
    "/apps/{appID}": {
      "get": {
        "tags": [
          "Apps"
        ],
        "summary": "Find app by ID",
        "description": "",
        "operationId": "getAppById",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "appID",
            "description": "ID of app that needs to be fetched",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/app"
            }
          },
          "404": {
            "description": "App not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Apps"
      },
      "put": {
        "tags": [
          "Apps"
        ],
        "summary": "Update an existing app",
        "description": "",
        "operationId": "updateApp",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "appID",
            "description": "ID of app that needs to be updated",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "appData",
            "description": "App fields",
            "required": true,
            "schema": {
              "type": "object",
              "items": {
                "$ref": "#/definitions/app"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "404": {
            "description": "App not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Apps"
      },
      "delete": {
        "tags": [
          "Apps"
        ],
        "summary": "Delete an existing app",
        "description": "",
        "operationId": "deleteApp",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "appID",
            "description": "ID of app that needs to be deleted",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "404": {
            "description": "App not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Apps"
      }
    },
    "/app-key/{appID}": {
      "get": {
        "tags": [
          "Apps"
        ],
        "summary": "Get app key by appID",
        "description": "",
        "operationId": "getAppKeyByAppId",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "appID",
            "description": "ID of app that needs to be fetched",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "App not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Apps"
      }
    },
    "/images": {
      "post": {
        "tags": [
          "Images"
        ],
        "summary": "Creates a new row in the Images table.",
        "description": "",
        "operationId": "addImage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "imageData",
            "description": "Image data",
            "required": true,
            "schema": {
              "$ref": "#/definitions/image"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation, existing image in database has been updated."
          },
          "201": {
            "description": "Successful operation, new image has been added to database."
          },
          "400": {
            "description": "deviceID or imageID are missing or invalid",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "409": {
            "description": "Image already exists",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Images"
      }
    },
    "/verify-user-token/{token}": {
      "get": {
        "tags": [
          "Apps"
        ],
        "summary": "Verifies user token. If token is valid, returns basic app data. Otherwise, returns false.",
        "description": "",
        "operationId": "verifyUserToken",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "token",
            "description": "App token",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/AppBasicData"
            }
          }
        },
        "x-swagger-router-controller": "Apps"
      }
    },
    "/master-stats": {
      "get": {
        "tags": [
          "Apps"
        ],
        "summary": "Get aggregated statistics for all users.",
        "description": "",
        "operationId": "getMasterStats",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/app"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "x-swagger-router-controller": "Apps"
      }
    },
    "/apps-ids-list": {
      "get": {
        "tags": [
          "Apps"
        ],
        "summary": "Get array of clients' app ids.",
        "description": "",
        "operationId": "getAppsIdsList",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "x-swagger-router-controller": "Apps"
      }
    },
    "/events": {
      "post": {
        "tags": [
          "Events"
        ],
        "summary": "Creates a new row in the Events table.",
        "description": "",
        "operationId": "addEvent",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "eventData",
            "description": "Event data",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Event"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Successful operation"
          },
          "400": {
            "description": "deviceID or timestamp are missing or invalid",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "409": {
            "description": "Event already exists",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Events"
      }
    },
    "/users/{deviceID}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get user by deviceID",
        "description": "",
        "operationId": "getUserByDeviceId",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "deviceID",
            "description": "deviceID of user that needs to be fetched",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Users"
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update user by deviceID",
        "description": "",
        "operationId": "updateUserByDeviceId",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "deviceID",
            "description": "deviceID of user that needs to be updated",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "userData",
            "description": "User data to update",
            "required": true,
            "schema": {
              "type": "object",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Users"
      }
    },
    "/users": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Add new user",
        "description": "",
        "operationId": "addUser",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "userData",
            "description": "User data to insert",
            "required": true,
            "schema": {
              "type": "object",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Successful operation"
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Users"
      }
    },
    "/best-campaign/{deviceID}/{appID}/{creativeID}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Predict best campaign for user by deviceID, appID and creativeID",
        "description": "",
        "operationId": "getBestCampaignPrediction",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "appID",
            "description": "ID of app for which prediction is required",
            "required": true,
            "type": "string"
          },
          {
            "in": "path",
            "name": "deviceID",
            "description": "deviceID of user for whom prediction is required",
            "required": true,
            "type": "string"
          },
          {
            "in": "path",
            "name": "creativeID",
            "description": "creativeID of campaign for which prediction is required",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/BestCampaign"
            }
          },
          "404": {
            "description": "App, device or creative not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-swagger-router-controller": "Users"
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "definitions": {
    "features": {
      "type": "object",
      "properties": {
        "attrHist": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "attrHistScores": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        },
        "subHist": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "subHistScores": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        },
        "mainHist": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "mainHistScores": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        }
      }
    },
    "customerDetails": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "company": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "mobile": {
          "type": "string"
        },
        "address": {
          "type": "string"
        }
      }
    },
    "campaign": {
      "type": "object",
      "properties": {
        "clicks": {
          "type": "integer"
        },
        "impressions": {
          "type": "integer"
        }
      }
    },
    "creative": {
      "type": "object",
      "properties": {
        "campaigns": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/campaign"
          }
        }
      }
    },
    "device": {
      "type": "object",
      "properties": {
        "valid": {
          "type": "integer"
        },
        "invalid": {
          "type": "integer"
        },
        "deviceID": {
          "type": "string"
        }
      }
    },
    "platform": {
      "type": "object",
      "properties": {
        "valid": {
          "type": "integer"
        },
        "invalid": {
          "type": "integer"
        },
        "platformID": {
          "type": "string"
        }
      }
    },
    "imageFeatures": {
      "type": "object",
      "properties": {
        "probs": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        },
        "bestCatID": {
          "type": "integer"
        },
        "bestCatProb": {
          "type": "number",
          "format": "float"
        }
      }
    },
    "Gps": {
      "type": "object",
      "properties": {
        "latitude": {
          "type": "number",
          "format": "float"
        },
        "longitude": {
          "type": "number",
          "format": "float"
        }
      }
    },
    "userStatistic": {
      "type": "object",
      "properties": {
        "platforms": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/platform"
          }
        },
        "devices": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/device"
          }
        },
        "totalUsers": {
          "type": "object",
          "properties": {
            "valid": {
              "type": "integer"
            },
            "invalid": {
              "type": "integer"
            }
          }
        },
        "scannedUsers": {
          "type": "integer"
        }
      }
    },
    "image": {
      "type": "object",
      "description": "One row in images table",
      "properties": {
        "deviceID": {
          "type": "string"
        },
        "imageID": {
          "type": "string"
        },
        "cameraOrientation": {
          "type": "integer"
        },
        "apps": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "source": {
          "type": "string",
          "enum": [
            "CAMERA",
            "FACEBOOK",
            "WHATSAPP",
            "SCREENSHOT",
            "OTHER"
          ]
        },
        "version": {
          "type": "string"
        },
        "gps": {
          "$ref": "#/definitions/Gps"
        },
        "numOfFaces": {
          "type": "integer"
        },
        "facesFeatures": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/imageFeatures"
          }
        },
        "globalFeatures": {
          "$ref": "#/definitions/imageFeatures"
        },
        "imagePath": {
          "type": "string"
        }
      }
    },
    "app": {
      "type": "object",
      "description": "One row in apps table",
      "properties": {
        "key": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "appID": {
          "type": "string"
        },
        "isMaster": {
          "type": "integer"
        },
        "creatives": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/creative"
          }
        },
        "customerDetails": {
          "$ref": "#/definitions/customerDetails"
        },
        "userStatistics": {
          "$ref": "#/definitions/userStatistic"
        }
      }
    },
    "appUser": {
      "type": "object",
      "properties": {
        "appID": {
          "type": "string"
        },
        "isCounted": {
          "type": "integer"
        },
        "creatives": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/creative"
          }
        }
      }
    },
    "User": {
      "type": "object",
      "description": "One row in users table",
      "properties": {
        "deviceID": {
          "type": "string"
        },
        "deviceType": {
          "type": "string"
        },
        "platformType": {
          "type": "string",
          "enum": [
            "ANDROID",
            "IOS",
            "Py"
          ]
        },
        "totalImages": {
          "description": "Total number of images found on user device",
          "type": "integer"
        },
        "scannedImages": {
          "description": "Total number of scanned images",
          "type": "integer"
        },
        "isValid": {
          "type": "integer"
        },
        "errorMsg": {
          "type": "string"
        },
        "appsMap": {
          "description": "appID to UserID",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "apps": {
          "description": "appID to appUser",
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/appUser"
          }
        },
        "features": {
          "$ref": "#/definitions/features"
        }
      }
    },
    "Event": {
      "type": "object",
      "description": "One row in events table",
      "properties": {
        "deviceID": {
          "type": "string"
        },
        "appID": {
          "type": "string"
        },
        "creativeID": {
          "type": "string"
        },
        "campaignID": {
          "type": "string"
        },
        "timeStamp": {
          "type": "number",
          "format": "long"
        },
        "action": {
          "type": "string",
          "enum": [
            "CLICK",
            "IMPRESSION"
          ]
        }
      }
    },
    "LoginCredentials": {
      "type": "object",
      "description": "Object sent when a user tries to login",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "username",
        "password"
      ]
    },
    "SignupCredentials": {
      "type": "object",
      "description": "Object sent when a user tries to sign up",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "passwordRepeat": {
          "type": "string"
        }
      },
      "required": [
        "username",
        "password",
        "passwordRepeat"
      ]
    },
    "TokenModel": {
      "type": "object",
      "description": "Object returned after a successful login or sign-up",
      "properties": {
        "token": {
          "type": "string"
        },
        "tokenExpiry": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "token",
        "tokenExpiry"
      ]
    },
    "BestCampaign": {
      "type": "object",
      "description": "Best campaign prediction",
      "properties": {
        "best-campaign": {
          "type": "string"
        }
      },
      "required": [
        "best-campaign"
      ]
    },
    "AppBasicData": {
      "type": "object",
      "description": "Object returned upon successful user verification",
      "properties": {
        "appID": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "isMaster": {
          "type": "boolean"
        }
      },
      "required": [
        "appID",
        "username",
        "isMaster"
      ]
    },
    "ErrorModel": {
      "type": "object",
      "required": [
        "message",
        "status"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "integer",
          "minimum": 100,
          "maximum": 600
        }
      }
    }
  }
}`

**Comment by lazar725** [comment]
When I copy-paste it it's a mess, but you can see it here:

http://pixoneye-api.azurewebsites.net/api-docs

**Comment by fehguy** [comment]
Hi, seems like your server is down.  Can you see about pasting the JSON or restarting it?

**Comment by lazar725** [comment]
It's up now.

**Comment by lazar725** [comment]
Could you please check it?

**Comment by webron** [comment]
@lazar725 please try with the current master instead of the released 2.1.4. It works well with it.

**Comment by lazar725** [comment]
@webron   I don't quite understand how I'm supposed to do it, because I'm basically requiring swagger-tools in my node script, and the swagger tools automatically loads swagger-ui as its dependency.

**Comment by webron** [comment]
Just don't use the swagger-ui that's provided as a dependency. Clone this repo and use the /dist directory directly.

**Comment by lazar725** [comment]
@webron But how? When I write the line `var swaggerTools = require('swagger-tools');` the swagger-ui is installed automatically inside my node_modules folder. Since everything inside that folder is installed automatically according to my package.json, I cannot manually change there anything once my app is deployed.

**Comment by webron** [comment]
@lazar725 others may be able to help you with that, I have little knowledge in that area. However, there isn't really an issue because it renders fine with the master version. You can just clone it, open the index.html and point it to your swagger spec. You can always check with swagger-tools as to how to replace the version of swagger-ui it installs or how to override it.
