### ISSUE TITLE
[Question] Swagger spec conversion to JSON/XML

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-ui#2085]
Hi,

I'm going to do a development in Swagger UI (and if it's OK, submit a PR ;) ) and I wanted to know where the Swagger description (YAML) is converted into JSON or XML (in the "Example value" for example.
Can someone help me ?

Many thanks !

**Comment by webron** [comment]
YAML conversion to JSON is done anyways when processing, and converting it to XML doesn't make sense. What are you trying to achieve?
