### ISSUE TITLE
Rendering double 0 as 0.0

### ISSUE THREAD

**Issue by jusw85** [swagger-api/swagger-ui#2088]
I'm currently running Swagger-UI v2.1.4.

I've defined 0.0 as a default example value of my double property. However, this renders as 0 in the input parameter model schema. Is it possible to render it as 0.0, to let users know the parameter is double type? 

Thanks!

swagger.json

```
{
    "definitions": {
        "MyRecord": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "myProperty": {
                            "type": "number",
                            "format": "double",
                            "example": 0.0
                        }
                    }
                }
            }
        }
    }
}
```

Model schema

```
{
    "data": {
        "myProperty": 0
    }
}
```

[edit] I've noticed this happens with the response JSON as well. 0.0 in the original JSON response is rendered as 0 in Swagger.

**Comment by webron** [comment]
This should no longer be an issue with 3.X. Please reopen otherwise.

**Comment by mg1308** [comment]
@webron I am still facing this issue in latest version of swagger-ui
