### ISSUE TITLE
Swagger-ui not able to parse host for IPv6 format

### ISSUE THREAD

**Issue by anchaltyagi** [swagger-api/swagger-ui#2089]
swagger-ui version : 2.1.8
a swagger file reproducing the issue: **swagger-client.js**

Description: We are using swagger-ui for our REST APIs. It was working fine when we were in IPv4. We recently had to change to IPV6 and UI breaks there. While debugging we found that swagger-client.js is not able to filter out the host name from IPV6 format. 
Example: [fc00:10:112:54::246] is the IP address for my host when I try to find the host name in request object its filtered out as **host: "[fc00"**.
I feel somewhere in logic when host name is taken from url ":" is used as separator for host and port, but in IPV6 ":" can be used in address also.

Please help us by providing support to IPV6 address format also.

**Comment by fehguy** [comment]
Yes, this has been added at https://github.com/OAI/OpenAPI-Specification/issues/489 for the next version of the specification
