### ISSUE TITLE
How to remove Response Class in Swaggger

### ISSUE THREAD

**Issue by surajdalvi** [swagger-api/swagger-ui#2094]
I am new to a swagger. I am using version v2.1.4 of swagger ui  I write the following code for response:

     "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/test1"
            }
          },
          "401": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/test2"
            }
          }
        }

but when I check it on UI side Swagger show me Response Class and Response Messages. and 200 success part are displayed in Response Class, not in Response Messages.I want to show both status along with their Model in Response Messages and remove Response Class. How I do that please help me?

**Comment by fehguy** [comment]
The default response (200) is shown at the top, not the bottom of the UI.  That's per design.

**Comment by surajdalvi** [comment]
Can I change this please help me into this?
