### ISSUE TITLE
source-less minified files

### ISSUE THREAD

**Issue by onlyjob** [swagger-api/swagger-ui#2097]
`lib` folder contains source-less minified javascripts. Effectively minified code is equivalent of pre-compiled binary -- un-readable, non-modifiable and non-distributable in [Debian](http://debian.org).
It is a bad practice to commit binaries to VCS. 
Please replace all minified files with their original (non-minified) sources.

Read more in https://wiki.debian.org/onlyjob/no-minification

Thanks.

**Comment by webron** [comment]
No longer relevant in 3.X.
