### ISSUE TITLE
Swagger UI not parsing referenced array items

### ISSUE THREAD

**Issue by darkdragon-001** [swagger-api/swagger-ui#2098]
In the following example, Test2 is not parsed.

```
# schema.yaml
$schema: http://json-schema.org/draft-04/schema#
definitions:
  Test1:
    type: array
    items:
      $ref: "#/definitions/Test2"
  Test2:
    type: string
type: object
properties:
  test1:
    $ref: "#/definitions/Test1"
```

Swagger UI model output

```
modules.yaml {
  test1 (Test1, optional)
}
Test1 [
  URL/schema.yaml#/definitions/Test2
]
URL/schema.yaml#/definitions/Test2 {}
```

where URL is my server path and URL/modules.yaml is accessible (Test1 is parsed correclty).

This issue has to do with arrays because it works for objects:

```
# schema.yaml
$schema: http://json-schema.org/draft-04/schema#
definitions:
  Test1:
    type: object
    properties:
      test2:
        $ref: "#/definitions/Test2"
  Test2:
    type: string
type: object
properties:
  test1:
    $ref: "#/definitions/Test1"
```

```
modules.yaml {
  test1 (Test1, optional)
}
Test1 {
  test2 (string, optional)
}
```

**Comment by fehguy** [comment]
You have some indenting issues in your sample above.  Is that what you were trying?

**Comment by darkdragon-001** [comment]
Well, I gave the samples different names, but besides that this is the code I was trying.

What is not indented correctly and why does it work with the non-array version?

**Comment by webron** [comment]
The `type` and `properties` of `Test2` are not indented correctly.

**Comment by darkdragon-001** [comment]
`type` and `properties` do belong to the root and not to `Test2` as shown in the [schema specification example](http://json-schema.org/example2.html) and in [this example on the web](http://spacetelescope.github.io/understanding-json-schema/structuring.html)

**Comment by webron** [comment]
I think we're missing some details here. Looking at the original comment, it seems you're splitting your definition into multiple files. Keep in mind the spec does *not* support full JSON Schema (for example, the `$schema` property is not supported and makes it invalid).

If you can provide with a full set of files (references and all) that exhibits the issue, it'll be easier to understand and check.

**Comment by darkdragon-001** [comment]
```
# excerpt of swagger.yaml
paths:
  /Test:
    x-swagger-router-controller: test
    get:
      description: Returns test
      operationId: getTest
      responses:
        "200":
          description: Success
          schema:
            $ref: #"schemas/schema.yaml"
```

**Comment by webron** [comment]
You can split it to multiple files the way you have (basically covered by [REUSE](https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md)).

Currently you're using a full JSON Schema though which is not supported by the spec (can't use `definitions`, `$schema`). This may not be related to the issue at hand, but I'd rather we concentrate on solving an issue with a valid case.

**Comment by darkdragon-001** [comment]
When not using `definitions`, is it then possible to have multiple declarations in one external file? Or do I have to create one file for every single definition?

_Note: My underlying swagger works with something like this correctly. Only swagger-ui does not work with it correctly._

# excerpt of swagger.yaml
paths:
  /Test:
    x-swagger-router-controller: test
    get:
      description: Returns test
      operationId: getTest
      responses:
        "200":
          description: Success
          schema:
            $ref: #"schemas/schema.yaml#/Tests"

```
# schema.yaml
Tests:
  type: array
  items:
    $ref: "#/Test"
Test:
  type: string
```

**Comment by webron** [comment]
It's possible, yeah, check out the previously linked REUSE guide which shows an example of just that.
The excerpt you have in the comment above is also valid.

**Comment by darkdragon-001** [comment]
When I use the excerpt above, swagger ui shows me the following model

```
Tests [
  URL/schema.yaml#/Test
]
URL/schema.yaml#/Test {}
```

**Comment by ifreecarve** [comment]
I think this is the same problem I'm experiencing with the generated javascript client.  Could it be related to arrays of objects whose definitions contain further `$ref`s?

Here is a minimal version of my yaml file:

```yaml
paths:
  /get_statuses:
    get:
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/Status'
        default:
          schema:
            $ref: '#/definitions/Error'

  /get_results/{test_id}:
    get:
      parameters:
        - name: test_id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/Testresult'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Status:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string

  CustomTestresultFields:
    type: object
    properties:
      custom_step_results:
        type: string

  Testresult:
    type: object
    allOf:
      - $ref: '#/definitions/CustomTestresultFields'
      - $ref: '#/definitions/TestresultBase'
      
  TestresultBase:
    type: object
    properties:
      id:
        type: integer
        format: int32
```

Calls to `get_statuses` work fine -- an array of objects is returned.  

Calls to `get_results` are broken -- an array of the correct length is returned, but all the objects are empty.  Javascript receives these results via a callback `(error, data, response)`, and `response.text` has the data I need.  (In fact, this is my workaround -- `data = JSON.parse(response.text)`)

There are other instances where I'm using an `allOf` definition in my code, so I assume that is (separately) working.  I have not tested generated clients in other languages to see if they exhibit this problem.

**Comment by vortechs2000** [comment]
I'm seeing the same issue.  I have a definition in my main yaml file that $refs an external file.  That external file has a property that $refs a different external file.  In that case, the second $ref gets rendered as the URI for the external file instead of the actual object it refers to.

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
