### ISSUE TITLE
SwaggerUI not loading endpoints

### ISSUE THREAD

**Issue by bebemau** [swagger-api/swagger-ui#2100]
swagger-ui version: 5.0.4

Getting "SwaggerUi is not defined" error when i try to load the page.   What is it that I am missing, I was getting the same error with 4.0 that's why I upgraded the version hoping it will take care of the javascript error.  

Note: Calling docs/v1 i was able to get the valid json back.

Any guidance will be appreciated.

**Comment by fehguy** [comment]
There is no swagger-ui version 5.0.4.  Current release is 2.1.4 https://github.com/swagger-api/swagger-ui/releases
