### ISSUE TITLE
"dependency free"

### ISSUE THREAD

**Issue by tyrsius** [swagger-api/swagger-ui#2101]
The README says that Swagger UI is dependency free, but then goes on to indicate that the `lib` directory contains the swagger dependencies.

Swagger UI is **not** dependency free. It depends on jQuery (and some jQuery plugins), backbone, handlebars, lodash, js-yaml, and more. While it is capable of operating as a "standalone", this meaning is distinct from "dependency free." This claim should be removed from the README, as it is inaccurate.

**Comment by brylie** [comment]
Of particular relevance, the [jQuery BBQ dependency is causing conflicts and bugs](https://github.com/swagger-api/swagger-ui/issues/1762).

**Comment by webron** [comment]
With the new release, we also changed the wording.
