### ISSUE TITLE
Request parameters 'pattern' is not displayed if parameter type is query

### ISSUE THREAD

**Issue by heresandyboy** [swagger-api/swagger-ui#2103]
- swagger-ui version  2.1.4
- a swagger file reproducing the issue
  [swagger.txt](https://github.com/swagger-api/swagger-ui/files/226137/swagger.txt)

For any api endpoints that do not use a request model, i.e query params, there is no way to view the regular expression pattern. Pattern is only displayed if there is a request model and you hover over a parameter on the Model Schema (which I must say I find a bit unintuitive tbh). 

For example in my swagger json attached the path /api/address/search has a postcode parameter with the full pattern shown in the json, but api users have no way of knowing there is a required regex for the parameter.

![image](https://cloud.githubusercontent.com/assets/553990/14644091/bef9f0ca-0648-11e6-99ad-ce1212157c0f.png)

![image](https://cloud.githubusercontent.com/assets/553990/14644028/8c0d2ba0-0648-11e6-8606-3049e90bea51.png)

My preference would be to simply display the 'pattern' in the description field after the description so the details can be viewed up front rather than hover over, but we could make do with introducing the same hover over the Parameter e.g request.postCode, or perhaps on hover over value input box itself would be best.

If anyone is aware of a way to customise the swagger ui to combine the Description and pattern fields (I'm using Swashbuckle 5.0 with an ASP.net web api) then please let me know.

**Comment by paulwilton** [comment]
Also would like this feature -  hover or option to display pattern next to description
Would be nice if the swagger UI validated the input against the pattern as well

**Comment by ljwagerfield** [comment]
Issue is present for `in: header` parameters too. Would be useful to support this in the UI to assist with JWT tokens, etc.

**Comment by webron** [comment]
See #993.

**Comment by githoober** [comment]
I still cannot find where it's fixed.

**Comment by webron** [comment]
It wasn't fixed.
