### ISSUE TITLE
Dockerfile isn't suitable for production

### ISSUE THREAD

**Issue by Vanuan** [swagger-api/swagger-ui#2109]
Current Dockerfile has some limitation and fields for potential improvement:

1) It's based it on Ubuntu image which is not small. We can use alpine or smaller base
2) Does it really need Java? It reads as dependency-free
3) To shrink it's size even further, we can write a script that installs, builds and removes all dependencies not needed for production. We can use nginx if it's enough.

**Comment by fehguy** [comment]
Yes, honestly the swagger-ui dockerfile was community contributed, I'd suggest we follow the [swagger-editor](https://github.com/swagger-api/swagger-editor/blob/master/Dockerfile) Dockerfile and:

* Use Alpine
* Use http-server with CORS enabled
* Copy only the pre-built files from `dist`

It's pretty easy to do this, do you want to take a shot and send a PR?

**Comment by Vanuan** [comment]
The tricky part is how to specify swagger doc file.
Here's a naive implementation.

**Comment by Vanuan** [comment]
When I created this issue I wan't aware that there was a dist folder committed to the repo.

**Comment by romant** [comment]
Hi @Vanuan - check out PR #2128.

As for the specification of the swagger doc file; we're working on that with [Project Platypus](https://github.com/vmware/platypus)

**Comment by Vanuan** [comment]
Yeah, sed. I saw that approach. I was thinking that there should be a better way.
This would be the ideal usage:

`docker-compose.yml`:

```
version: '2'
services:
  swagger-ui:
    image: swagger-ui:latest
    volumes:
      ./swagger.json:/app/dist/swagger.json:ro
```

Additionally, it would be great if I could replace template and css without needing to `sed` anything.

**Comment by Vanuan** [comment]
Here it is: https://hub.docker.com/r/vanuan/swagger-ui/

**Comment by programster** [comment]
I like @Vanuan propsition of a compose file which specifies using a read-only volume that has the swagger.json spec in it. At the moment it's a pain in the butt to set up a separate site that accepts CORS requests just to direct the swagger-ui to point to the swagger file's url. 

Also, I agree with this:

> Additionally, it would be great if I could replace template and css without needing to sed anything.

I think a large portion of users (such as myself) are setting up the swagger UI just to display their _own_ API documentation, not for grabbing other people's swagger spec file paths and plugging that into their swagger-ui deployment. Hence it would be a great idea to get rid of that header bar and just display our own swagger documentation.

**Comment by webron** [comment]
This should no longer be an issue with the new UI. If you find there's room for additional improvements, please consider submitting a PR to improve it.
