### ISSUE TITLE
Display @ExtensionProperty on the swagger-ui.html

### ISSUE THREAD

**Issue by mibeumer** [swagger-api/swagger-ui#2110]
Version: 2.1.4

Swagger-Core has the @ExtensionProperty annotation. It would be nice if these would be visible on the swagger-ui.html.

Is there a configuration to make them visible or can we provide a function to make the additional properties visible?

Kind Regards
mibeumer

**Comment by webron** [comment]
We're not going to support it soon, however you should be able to write a plugin to the new UI that would display those.
