### ISSUE TITLE
&reg converted to ® in curl command generated by swagger-ui

### ISSUE THREAD

**Issue by pivotal-nader-ziada** [swagger-api/swagger-ui#2113]
Spring boot application version 1.3.3 using spring-fox version 2.4.0 

We have a query parameter called "language" and another called "region". When the swagger-ui page generates the curl command that can be copied to run in the command line, it changes to &reg as in the following example

Expected:
http://service-url/path?language=EN&region=US&country=USA

Actual:
http://service-url/path?language=EN®ion=US&country=USA

**Comment by fehguy** [comment]
This is fixed by https://github.com/swagger-api/swagger-js/issues/798

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/efb77652274e99893b11848f02d9dc37d07344aa
