### ISSUE TITLE
Basic Auth shouldn't require a password

### ISSUE THREAD

**Issue by drewish** [swagger-api/swagger-ui#2114]
The BasicAuth dialog shouldn't require a password. I've got an API I'm trying to use that only requires a username. There is no password so I should be able to submit the empty string.

- swagger-ui version 2.1.4
- a swagger file reproducing the issue
```
swagger: '2.0'
info:
  title: Demo
  version: vDemo
host: example.com
schemes:
- https
consumes:
- application/json
produces:
- application/json
security:
- api_key: []
paths:
  /sites:
    get:
      summary: List of sites
      tags:
      - site
      description: This route is most useful for finding a site's ID for subsequent requests.
      responses:
        default:
          description: Something.


securityDefinitions:
  api_key:
    type: basic
    description: Enter the API key as the username and set the password to an empty string. You can locate and manage your API keys from the API Credentials page.
```
![screen shot 2016-04-22 at 12 46 59 pm](https://cloud.githubusercontent.com/assets/68750/14751695/596dc942-0888-11e6-97de-2a0c30969895.png)

**Comment by fehguy** [comment]
Hmm, I guess we didn't consider that use case.  It should be trivial to implement, if you don't mind sending a PR

**Comment by drewish** [comment]
Yeah happy to, I'll put one in on Monday.

**Comment by drewish** [comment]
Wasn't on Monday but I finally got a chance to put a PR up.

**Comment by webron** [comment]
@bodnia please review the PR.

**Comment by bodnia** [comment]
@webron please merge the PR.
