### ISSUE TITLE
Validate payload in UI?

### ISSUE THREAD

**Issue by atdiff** [swagger-api/swagger-ui#2119]
It would be good if the JSON payload was being validated within the editor against the Swagger schema. Is this in place anywhere or are there any plans for it?

**Comment by webron** [comment]
Looks like the wrong project. If relevant, please open on [swagger-editor](https://github.com/swagger-api/swagger-editor). Can't say I see validation as part of the tool though.

**Comment by atdiff** [comment]
@webron I see this as being a part of Swagger UI actually.  (I can edit my comment above).  For instance, on http://petstore.swagger.io/#!/pet/addPet, I think having the payload validated when clicking "Try it out" makes sense.  Thoughts?
 I can open a new iissue if this one can't be reopened.

**Comment by webron** [comment]
I can reopen the issue, but it still doesn't make sense to me, no. swagger-ui is not intended as a full-fledged testing tool and at the moment it falls out of scope. We may change that in the future.

**Comment by atdiff** [comment]
@webron I don't think it needs to be a full-fledged testing tool.  Validation of the payload seems like a simple thing to incorporate.  If a person is going to click "Try it out", it seems logical to know whether the request and payload were valid or not as a part of that information.  Seems useful.
