### ISSUE TITLE
Swagger UI removes Content-Type params received from server

### ISSUE THREAD

**Issue by vcabbage** [swagger-api/swagger-ui#2121]
- swagger-ui version: 2.1.4
- a swagger file reproducing the issue: I don't think this is specific to a swagger file, but I can create one if necessary.

I'm working with an API that requires versioning in the Accept header. The required Accept header value is in the format `application/json; version=1`.

The curl examples produced by swagger-ui don't include these, just `--header 'Accept: application/json'`, without the version parameter. I found that this header does not come from the swagger file, but from the Content-Type header received from the server.

After confirming that the server was responding with `application/json; version=1` I looked more deeply and found that swagger-ui [strips the first semi-colon and everything after it](https://github.com/swagger-api/swagger-ui/blob/ba0a396d14c2a39b0e12aac0748955776bc2aef0/src/main/javascript/view/OperationView.js#L670).

``` javascript
// if server is nice, and sends content-type back, we can use it
if (headers) {
    contentType = headers['Content-Type'] || headers['content-type'];
    if (contentType) {
        contentType = contentType.split(';')[0].trim();
    }
}
```

My question is whether this is desired behavior and whether it would be possible to at least make this stripping optional so that the curl command will be properly generated for APIs like this that require the Accept header param.

Thanks in advance.

**Comment by fehguy** [comment]
Hi, the accept header that you're sending should be configured by the `produces` array for the operation--it will use whatever value you have when generating the request.  The stripping of the response is different--that's after the request has been executed.  You may want that value, but what I'm saying is that the first is the _request_ and the splitting is the _response_.

Can you please confirm that you have the `produces` set correctly in your definition?

**Comment by vcabbage** [comment]
Thanks for the response. Below is an example of the `produces` config.

API commands issued from swagger UI itself work great. It's only the example curl commands that exhibit the issue.

``` json
"tags": [
    "auth"
],
"summary": "Get an API key",
"consumes": [
    "application/json"
],
"produces": [
    "application/json; version=1"
],
```

**Comment by fehguy** [comment]
Got it, this is an issue in the curl rendering.  I'll get this fixed.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/efb77652274e99893b11848f02d9dc37d07344aa
