### ISSUE TITLE
Swagger-ui redirects automatically when no trailing slash used

### ISSUE THREAD

**Issue by to-kra** [swagger-api/swagger-ui#2126]
We use swagger JAXRS with Websphere & swagger-ui. We recently found that if you use no trailing slash when accessing swagger-ui, "something" does redirect with the hosting server name, instead of the requesting host with adding that trailing slash. We suspect its swagger-ui. This will not work with proxy url.

**Comment by fehguy** [comment]
I don't think that's possible inside swagger-ui.  Please check your server settings.

**Comment by rohitkhatri** [comment]
I'm also facing this issue, can anyone help me here please?
