### ISSUE TITLE
Swagger requires response body schema for HEAD

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#2127]
When defining a `head` operation, I must specify a schema, and Swagger will show a Mode | Model Schema panel even though `HEAD` requests do not return a response body. I should be able to specify a `HEAD` and list a `produces: [ ... ]` array for the `Accept` header and Swagger UI should use those values (the _Response Content Type_ drop down) but not show the response schema.

If I remove the schema from the '200' response, the UI does not show the _Response Content Type_ drop down, so the user cannot invoke the `HEAD` operation with the correct `Accept` header (one instead must define a extra `in: header` parameter, duplicating the content of the default `produces`).

Below is a subset of the sample Uber schema which shows this. Try this in Swagger UI both with and without the schema for the `head` operation's 200 response.

```
# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Uber API
  description: Move your app forward with the Uber API
  version: "1.0.0"
# the domain of the service
host: api.uber.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
  - application/xml
paths:
  /products:
    get:
      summary: Product Types
      description: |
        The Products endpoint returns information about the *Uber* products
        offered at a given location. The response includes the display name
        and other details about each product, and lists the products in the
        proper display order.
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Products
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'

    head:
      summary: Product Types
      description: |
        The Products endpoint returns information about the *Uber* products
        offered at a given location. The response includes the display name
        and other details about each product, and lists the products in the
        proper display order.
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Products
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
definitions:
  Product:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
```

**Comment by webron** [comment]
Not displaying the content type choice is unrelated to a `head` operation and is a known issue (covered in a different ticket). However, if there's no response, what meaning is there to the `produces` value? It affects nothing.

**Comment by DavidBiesack** [comment]
`produces` is the only way to declare the allowed values the `Accept:` header as well as what goes into the  *Response Content Type* drop down... unless there is another way?

**Comment by webron** [comment]
It is, yes - I'm not sure why that's an issue though, can you explain?

**Comment by DavidBiesack** [comment]
User's cannot correctly call HEAD from Swagger UI without the response content type drop down. The service returns the same headers as the GET (Content-Type, Content-Length, ETag, etc) so the Accept header is required for the UI to make the correct call (and to generate the correct curl command, etc.)   Our APIs allow multiple Accept headers (for GET and therefore also for HEAD) with different corresponding response bodies (for GET) and headers (for GET and HEAD).

**Comment by webron** [comment]
Thanks for the clarification, that makes sense. We'll need to take care of that.

**Comment by webron** [comment]
This is no longer an issue with the new UI.
