### ISSUE TITLE
Can we make sub tags

### ISSUE THREAD

**Issue by faizaantrialx** [swagger-api/swagger-ui#2129]
1. abc
      i. xyz
         a. xyz- api call
         b. ....
      ii. pqr
          a. ....
          b. ....
2.

**Comment by webron** [comment]
swagger-ui doesn't support it and there's no plan to add this functionality. You can modify the code to achieve this functionality.

**Comment by faizaantrialx** [comment]
Thanks Ron

**Comment by kamil-kielczewski** [comment]
@webron - why?

**Comment by webron** [comment]
@kamil-kielczewski because it goes beyond what the specification defines.

**Comment by kamil-kielczewski** [comment]
@webron - yes you have right, how ever it is very practical feature (especially for large APIs) and may be "incorporated" into to specification in future. How ever my proposition (i think) will be simpler than @faizaantrialx : we can use following convention in tags names (using dots to nesting subtags):

```
user.client   # and use this tag to client GET/POST/...
user.seller   # and use this tag to seller GET/POST/...
user.admin   # and use this tag to admin GET/POST/...
books    # use this to general books GET/POST...
books.sell  # use this to GET/POST... associated with the sell
books.management # use this to GET/POST... associated with the books management
```

And in output web-page we will get:

```
user >
       client >
GET
POST
...
       seller >
GET
POST
...
       admin >
GET
POST
...

books >
GET
POST
...
       sell >
GET
POST
...
       management >
GET
POST
...
```

If you give me some tips where Is the code of swagger-ux wich generate view I can try to implement this feature

**Comment by kritika020594** [comment]
Is this issue yet not resolved?

How can we get the following sub tagging-

ABC

4.0
..
..
..
4.5
..
..
..

XYZ

3.3
..
..
3.4
..
..

Means an api having different version and is categorized accordingly

**Comment by zer0890** [comment]
anyone got a solution about this possibility ?
