### ISSUE TITLE
Map as Param won't render

### ISSUE THREAD

**Issue by nooruddin** [swagger-api/swagger-ui#2134]
I have an API where I take Map of Strings as input.  Looks like Swagger UI won't render the api.  Stuck in js while rendering the inline model.  Here is the sample code for quick debugging.
I am using 1.5.9-SNAPSHOT right now.

Rest Interface:
```
package com.mystuff.examplerestdef;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

import java.util.Map;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import com.mystuff.MyExampleClass;

@Path("/")
@Api(value = "/example", tags = "example")
@Produces(MediaType.APPLICATION_JSON)
public interface ExampleRest {

    @GET
    @ApiOperation(value = "give list from map", notes = "Try it out to get list of values", response = MyExampleClass.class)
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = MyExampleClass.class)
    })
    @Path("example")
    public MyExampleClass getStuff(Map<String, String> stringMap);
}
```

Rest Implementation:
```
package com.stuff.example;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import com.mystuff.examplerestdef.ExampleRest;

@Produces(MediaType.APPLICATION_JSON)
@Path("/")
public class ExampleRestImpl implements ExampleRest {

    @Override
    public MyExampleClass getStuff(final Map<String, String> stringMap) {

        final MyExampleClass myExampleClass = new MyExampleClass();
        final List<String> list = new ArrayList<String>(stringMap.values());
        myExampleClass.setListStuff(list);
        myExampleClass.setMapStuff(stringMap);
        return myExampleClass;
    }
}
```

Sample POJO:
```
package com.mystuff.example;

import java.util.List;
import java.util.Map;

public class MyExampleClass {

    private Map<String, String> mapStuff = null;
    private List<String> listStuff = null;

    public List<String> getListStuff() {
        return listStuff;
    }

    public Map<String, String> getMapStuff() {
        return mapStuff;
    }

    public void setMapStuff(final Map<String, String> mapStuff) {
        this.mapStuff = mapStuff;
    }

    public void setListStuff(final List<String> listStuff) {
        this.listStuff = listStuff;
    }
}
```

Error in Console:
![capture](https://cloud.githubusercontent.com/assets/1689581/14969202/009a0092-1076-11e6-9f87-23e3d7a113b0.JPG)

**Comment by nooruddin** [comment]
Not sure if this co-relate to this issue(https://github.com/swagger-api/swagger-ui/issues/1248)

**Comment by webron** [comment]
@nooruddin java code doesn't help when trying to work on swagger-ui issues. We'd need the actual spec file to be able to troubleshoot this.

**Comment by nooruddin** [comment]
@webron Sorry for unnecessary information.  There you go.
```
{
  "swagger": "2.0",
  "info": {
    "description": "This is API Dashboard",
    "version": "1.2.0",
    "title": "API Documentation",
    "contact": {
      "name": "XYZ TECHNOLOGIES LTD."
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "basePath": "/rest",
  "schemes": [
    "http",
    "https"
  ],
  "securityDefinitions": {
    "cwak": {
      "type": "apiKey",
      "name": "cwak",
      "in": "header"
    }
  },
  "definitions": {
    "MyExampleClass": {
      "type": "object",
      "properties": {
        "mapStuff": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "listStuff": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
That example loads fine in the master version of swagger-ui (after adding an operation that references it).

**Comment by nooruddin** [comment]
I do have the 2.1.4 version of `dist` folder in my project and I generate spec using swagger-core jersey 2 integration.  So I never manually edit the spec file.  Is there a way to have the spec generated correctly using swagger core annotations and jersey providers?

**Comment by webron** [comment]
I don't follow. Are you saying the generated spec file is different than what you shared here?

**Comment by nooruddin** [comment]
No.  That is exactly the spec file generated.  May be I misunderstood you.  What did you mean when you said "after adding an operation that references it".  Where did you add that?

**Comment by webron** [comment]
The spec you shared has no operations and will render nothing in swagger-ui. I had to add an operation that references the model so that *something* is displayed.

**Comment by webron** [comment]
```json
{
  "swagger": "2.0",
  "info": {
    "description": "This is API Dashboard",
    "version": "1.2.0",
    "title": "API Documentation",
    "contact": {
      "name": "XYZ TECHNOLOGIES LTD."
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "basePath": "/rest",
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/hello": {
      "post": {
        "description": "test",
        "parameters": [
          {
            "name": "test",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/MyExampleClass"
            }
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "cwak": {
      "type": "apiKey",
      "name": "cwak",
      "in": "header"
    }
  },
  "definitions": {
    "MyExampleClass": {
      "type": "object",
      "properties": {
        "mapStuff": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "listStuff": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

**Comment by nooruddin** [comment]
So my question is: How do I do it through annotations from swagger-core? Because I use `BeanConfig` from `io.swagger.jaxrs.config` package and registering swagger jaxrs provider in web.xml to generate me the spec file,
```
<param-name>jersey.config.server.provider.packages</param-name>
<param-value>
        io.swagger.jaxrs.listing, my.packages
</param-value>
``` 
which is loaded by swagger-ui automatically.  I never add any operation manually to spec file.  I want my project to generate the spec file automatically.  So how do I annotate my methods to have that operation being added to my spec file.  My sample code is posted above and shows annotations I use.

**Comment by webron** [comment]
Okay, this is getting a bit all over the place.

swagger-core generates a swagger spec. swagger-ui reads a swagger spec. swagger-ui doesn't care about the source of the spec itself.

The spec you shared loads fine in swagger-ui and is displayed correctly. No javascript errors. You're saying the output of swagger-core does cause you errors, so either you didn't share the output you get from swagger-core, or there's no issue with swagger-ui.

I don't know why you keep pulling to swagger-core though. If there's an issue with the output of swagger-core and you're not getting in the swagger spec what you expect to get from the code, please open the ticket on swagger-core and provide the relevant details there.

We can't keep going back and forth on this with tidbits of information.

**Comment by nooruddin** [comment]
@webron Ok. Thanks for the input.  I could not figure out what's causing the problem. So I just replaced the entire dist folder to what's on master branch and reapplied changes we made to js, css and html and it seems to work.  This issue can be closed.
