### ISSUE TITLE
Examples not rendered if there is no schema

### ISSUE THREAD

**Issue by eminence** [swagger-api/swagger-ui#2135]
Reproduced with the latest version (v2.1.4 on http://petstore.swagger.io/)

Yaml file:

```yaml
swagger: '2.0'
info:
  title: Test API
  description: Test API
  version: "1.0.0"


paths:
  /testAPI:
    get:
      produces:
        - text/plain
        - application/json
      description: test API
      responses:
        200:
          description: When all goes well
          examples:
            text/plain: "This is some example output"
            application/json: {msg: "This is some example output"}
    
```

Within Swagger-editor, I can clearly see both examples.  But in Swagger-ui, the examples are not shown.

Here is a copy of the above yaml file, for use with petstore : https://gist.githubusercontent.com/eminence/3868b27d319259601df779c45547857d/raw/193469c1558bcc721c5c516a283490ef9e357e9e/test.yaml

**Comment by webron** [comment]
Can't say it's an issue. If there's no schema, there's no response content. If there's no response content, the examples are meaningless.

**Comment by eminence** [comment]
Might there be cases when you don't want to document the full schema (or can't document it), but still want to show documents?   I'm thinking about scenarios where swagger is used to document existing APIs that are poorly designed and don't have a schema.  (I suppose in this case, a "dummy schema" should be used).

What about documenting this?  Maybe "An example of the response message.  Examples are meaningless if there is no schema defined".  (Bonus points for enforcing this in the editor)

Thanks for your quick reply!

**Comment by webron** [comment]
I'm afraid this doesn't make sense. You're documenting the API saying it returns nothing, and then you go ahead and say it returns something. If you can't describe it, leave it as an empty schema, but define a schema.

**Comment by eminence** [comment]
Ok, understood.  Perhaps the only open topic is to more clearly document this, if you think that's necessary.  

Thanks.
