### ISSUE TITLE
Swagger API's not returning the defined mock data

### ISSUE THREAD

**Issue by 2007ay** [swagger-api/swagger-ui#2137]
Hi, 
Swagger behaving very strange . Its not returning the mock data the one which i have defined , It always returning me some thing random data or system generated data like below

[
  {
    "id": "tempor aliquip",
    "name": "cillum ea labore ut"
  },
  {
    "id": "esse irure",
    "name": "aliqua reprehenderit ut"
  },
  {
    "id": "sunt ex",
    "name": "dolor velit"
  }
]
This is not the data what I have in my mock controller.

Can someone please in this .

 "swagger-connect": "^0.6.0",
"swagger-tools": "^0.9.13",

**Comment by webron** [comment]
This has nothing to do with swagger-ui, you should probably open the ticket on swagger-tools or whichever top-level tool you're using.
