### ISSUE TITLE
Support for $ref in securityDefinitions

### ISSUE THREAD

**Issue by richvdh** [swagger-api/swagger-ui#2139]
If there are several APIs which share `securityDefinitions`, it would be useful to factor them out to a separate file, using JSON refs.

**Comment by webron** [comment]
As the spec doesn't support it, we won't support it in the tool. If you'd like to see a change in the spec, please file a ticket on the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification).

**Comment by richvdh** [comment]
Thanks. Raised as https://github.com/OAI/OpenAPI-Specification/issues/680.
