### ISSUE TITLE
swagger-ui doesn't represent complex type as it defined.

### ISSUE THREAD

**Issue by ReinhardXu2007** [swagger-api/swagger-ui#2141]
When reporting a bug, please provide the following details:
- swagger-ui 2.1.4
- a swagger file reproducing the issue
`{"swagger":"2.0","info":{"version":"1.0.0","title":""},"host":"localhost:8080","basePath":"/jd/service","schemes":["http"],"paths":{"/test/customModel2":{"get":{"operationId":"customModel2","produces":["text/plain"],"parameters":[{"name":"p","in":"path","required":true,"type":"string"},{"name":"q","in":"query","required":true,"type":"string"},{"name":"requestInBean","in":"query","required":false,"schema":{"$ref":"#/definitions/MyRequest"}}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#/definitions/GenericResponseObject"},"headers":{}}}}}},"definitions":{"GenericResponseObject":{"type":"object","properties":{"code":{"type":"string"},"message":{"type":"string"},"data":{"type":"object"}}},"EmbededMyRequest":{"type":"object","properties":{"bean":{"type":"string"}}},"MyRequest":{"type":"object","properties":{"name":{"type":"string"},"value":{"type":"string"},"bean":{"$ref":"#/definitions/EmbededMyRequest"}}}}}`

I have an issue when using swagger-ui.
As there is defined a complex type of param in my operation, the form generated by swagger is still represented as a common string.
Is there any way to resolve it?

PS: This spec is displayed as expected in swagger-editor

**Comment by webron** [comment]
Complex models can only be used as body parameters. There's no support for them in path/query/header/formData parameters. If it's displayed properly in the editor, it's a bug there.
