### ISSUE TITLE
Exposing "x-amples" in UI

### ISSUE THREAD

**Issue by JasonArm** [swagger-api/swagger-ui#2142]
We are using "x-amples" to provide mapping between requests and responses; including multiple examples of the same time.
The standard "examples" in the response and in the model don't allow you show that request
 "X" gives a response "Y".

**Currently**, this information is hidden in the spec, and not exposed in the UI documentation.
It would be great if there was a way show this valuable information?
_I'm not a UI programmer, but even some guidance on how to extend the UI would be helpful?_

**Comment by fehguy** [comment]
Hi, if you're not a UI programmer then the current UI is not easily extendable and you shouldn't try (unless you want to become a UI programmer).

We are working on a new version of the UI which will be extensible without heavy programming knowledge.  But I do believe there is enough in the current UI for you to use the examples logic using `x-example` for scalar parameters and `x-examples` for body parameters.

There is support for `examples` in the response section by using the `default` keyword for content-type.
