### ISSUE TITLE
Object.assign() is not supported in Internet Explorer

### ISSUE THREAD

**Issue by thomasmey** [swagger-api/swagger-ui#2144]
When reporting a bug, please provide the following details:
- swagger-ui version
9eb4e003a9d0832b58e1b1154cbc19a50f09a8f0

- a swagger file reproducing the issue
Internet explorer 11 doesn't seem to support Object.assign() method used in https://github.com/swagger-api/swagger-ui/blame/master/src/main/javascript/utils/utils.js#L5

introduced by https://github.com/swagger-api/swagger-ui/commit/e08b7be581258c8a5a674833900debdbb69ea365

see also https://msdn.microsoft.com/de-de/library/dn858229(v=vs.94).aspx

**Comment by fehguy** [comment]
Thanks @thomasmey, this should be resolved in master now.
