### ISSUE TITLE
Add textarea in Query Parameter

### ISSUE THREAD

**Issue by surajdalvi** [swagger-api/swagger-ui#2145]
Hi,
I am new to swagger. Currently, I am using swagger ui version **v2.1.4**. My API consists query parameters. Into that one parameter accepts JSON body. I want to show this parameter into **textarea**. Currently, it showing in **input** tag . also, I want to display Parameter content type below that **textarea**. How I do that please help me?

**Comment by webron** [comment]
This is out of scope for us, but we'll try to issue a guide to customize the UI.
