### ISSUE TITLE
Can't read from server [...]

### ISSUE THREAD

**Issue by marcoliceti** [swagger-api/swagger-ui#2154]
Hi. I wrote a **valid** swagger file and I'd like to feed it to `swagger-ui`.

(I know the file is valid because I validated it with [swagger-cli](https://www.npmjs.com/package/swagger-cli) and with the [online editor](http://editor.swagger.io/#/)).

To avoid CORS issues, I copied my swagger file inside the `dist` folder and started a temporary local web server with the [node http-server module](https://www.npmjs.com/package/http-server). When I paste the URL of my swagger file I get the error `Can't read from server. It may not have the appropriate access-control-origin settings`.

<img width="1280" alt="schermata 2016-05-12 alle 12 59 54" src="https://cloud.githubusercontent.com/assets/1493439/15212522/7ac82a24-1841-11e6-9459-d8fff8b2bf75.png">

As you can see from the screenshot, the swagger file _is_ read from server, so the error message is obviously wrong. And the sentence `It may not have the appropriate access-control-origin settings` is kind of misleading: the `swagger-ui` and my swagger file come from the same origin, so CORS issues shouldn't be involved.

The `swagger-ui` version I used is `2.1.4`.

**Comment by fehguy** [comment]
Share the file, please?  Just because the swagger-editor says it's valid doesn't necessarily mean it's valid.  There are some situations that cannot be programmatically checked (they are decreasing, but it is possible).

**Comment by marcoliceti** [comment]
```json
{
  "swagger": "2.0",
  "info": {
    "title": "ZeroTitoli",
    "version": "0.0.0",
  },
  "schemes": [ "https" ],
  "consumes": [ "application/json" ],
  "produces": [ "application/json" ],
  "paths": {
    "/partite": {
      "post": {
        "description": "
          Creazione di una nuova partita per un certo gruppo. Occorre indicare
          sia il gruppo sia le informazioni sulla nuova partita. L'utente deve
          essere amministratore del gruppo indicato.
        ",
        "parameters": [
          {
            "name": "partita",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Partita"
            },
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "La partita è stata creata con successo.",
            "schema": {
              "$ref": "#/definitions/Partita"
            }
          },
          "403": {
            "description": "L'utente non è amministratore del gruppo indicato."
          }
        },
      }
    }
  },
  "security": [
    {
      "api_key": []
    }
  ],
  "definitions": {
    "Partita": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "giorno": {
          "type": "string"
        },
        "ora": {
          "type": "string"
        },
        "circolo": {
          "type": "string"
        },
        "quota": {
          "type": "string"
        },
        "note": {
          "type": "string"
        },
        "gruppo": {
          "type": "string",
          "description": "ID del gruppo per il quale è stata creata la partita."
        }
      },
      "required": [ "giorno", "ora", "circolo", "gruppo" ]
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "in": "header",
      "name": "X-ZeroTitoli-Api-Key"
    }
  }
}
```

**Comment by fehguy** [comment]
Hi, your contents are not valid JSON.  Try opening it in a JSON viewer and you'll see a number of errors:

* line 5, dangling comma
* line 13, multi-line string should be delimited with `\n`
* dangling comma after your path definition

![image](https://cloud.githubusercontent.com/assets/249413/15434151/917add0a-1e83-11e6-90f9-117ab2bf8e64.png)

**Comment by marcoliceti** [comment]
Thank you. The editor I use didn't complain and I didn't think about using a JSON validator. However, a more specific error message could be helpful. I think the failure of `JSON.parse` can be detected.
