### ISSUE TITLE
How to load Swagger YAML file hosted on a private git repository on Swagger UI?

### ISSUE THREAD

**Issue by JeanLebrument** [swagger-api/swagger-ui#2157]
Hello,

I'm looking for a way to automatically load a  YAML file hosted on a private git repository on Swagger UI?

I found some informations about `authorizations` on the README but I would appreciate a little bit more of help. I'm stuck finding how to properly configure the `authorizations` to fetch a file hosted on a private repo.

Any suggestions?

Best,

**Comment by claudio-viola** [comment]
@JeanLebrument  You can generate a github token with read access in your repository settings and use the github url with the token as parameter.
It will work.

**Comment by webron** [comment]
It really depends on the vendor of your private git repo ad what kind of API they expose.
