### ISSUE TITLE
README talks about input_apiKey but has been removed

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-ui#2158]
The README talks about using `input_apiKey`, but that element seems to have been removed from the html page.

**Comment by ChristianRich** [comment]
+1

**Comment by webron** [comment]
@bodnia since we updated the authorization mechanism, the README needs to be updated.

**Comment by zuk** [comment]
So any clues on how to get something like the old `input_apiKey` behaviour turned back on?

**Comment by fehguy** [comment]
Yes, recall that if you don't have the authorization in your definition, you can always add it back by reverting to the index.html from the previous version of swagger-ui (pre 2.2.x)

**Comment by cancan101** [comment]
I filed this issue May 2016 but it looks like 2.1.x releases were still being cut after then, so I assume this change happened some time earlier than the 2.2.x release?

**Comment by fehguy** [comment]
It's possible that you filed against master which may have been between releases.  I suggest pulling a tag from the 2.1.x and using the index.html from there.

**Comment by webron** [comment]
Gone from README.
