### ISSUE TITLE
Swagger UI generates incorrect request when using the fields box

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-ui#2159]
_From @jbockerstette on May 16, 2016 17:22_

I am using swagger ui with content type = application/vnd.api+json.

If I use the UI for a GET, it generates the following:
curl -X GET --header 'Accept: application/vnd.api+json' 'http://107.170.10.170:16006/1/articles'
which is correct.

If I then use the UI for a GET with the fields box containing "[articles]=title" no quotes, it generates:
curl` -X GET --header 'Accept: application/vnd.api+json' `'http://107.170.10.170:16006/1/articles?fields=%5Barticles%5D%3Dtitle'

This is not the correct format. IT SHOULD generate this:
curl -X GET --header 'Accept: application/vnd.api+json' 'http://107.170.10.170:16006/1/articles?fields%5Barticles%5D=title'

It should not add '=' after fields AND it should not encode the '=' before title.

_Copied from original issue: swagger-api/swagger.io#105_

**Comment by fehguy** [comment]
So no, what you're describing is not what it should be doing.  If you have a query param, with a name of `fields` and you pass a parameter value _with an `=`_, by definition that value must be escaped.  The `=` has a special meaning when passing query parameters, and to not escape it would cause more trouble than good.

I suggest that your server perform the URL Decoding function on the query parameter values before reading them, and you will then see the `[articles]=title`.
