### ISSUE TITLE
Angular Location service picks up shebang changes

### ISSUE THREAD

**Issue by aouji** [swagger-api/swagger-ui#2160]
On the latest master (as of https://github.com/swagger-api/swagger-ui/tree/767a37c5d7819f71b2540ccef651cc57e785cdae), when I try to expand a block in my angular app, the block gets expanded, but angular also picks up the shebang route change and changes the page. Seems like https://github.com/swagger-api/swagger-ui/pull/1607 had fixed the issue but https://github.com/swagger-api/swagger-ui/pull/1808 has removed the fix. I had to add the following to prevent angular from picking up the route change:

``` javascript
   SwaggerUi.Views.OperationView.prototype.toggleOperationContent = function(event) {
        var elem = $('#' + Docs.escapeResourceName(this.parentId + '_' + this.nickname + '_content'));
        if (elem.is(':visible')){
            event.preventDefault();
            $.bbq.pushState('#/', 2);
            Docs.collapseOperation(elem);
        } else {
            event.preventDefault();  // This line is not in master
            Docs.expandOperation(elem);
        }
    };
```

**Comment by safinalexey** [comment]
Lol, really, @fehguy can you return that line into master?)

**Comment by webron** [comment]
This should not be an issue with the new UI.
