### ISSUE TITLE
ReferenceError: $ is not defined on load bug

### ISSUE THREAD

**Issue by thomasnal** [swagger-api/swagger-ui#2161]
Accessing swagger-ui via url "http://hostname/parent_folder/" loads ui properly from index.html. Although, accessing it via url "http://hostname/parent_folder" fails loading the ui leaving output in the browser console,

```
ReferenceError: $ is not defined
```

Note the difference of slash '/' causing the swagger-ui to fail loading.

Version: MASTER cloned on 11th May, 2016.

**Comment by webron** [comment]
Please try with 3.X.
