### ISSUE TITLE
Securing the swagger ui

### ISSUE THREAD

**Issue by lazyspark** [swagger-api/swagger-ui#2163]
Is there a way a secure swagger UI, so only developers can see it and not everyone else who can just browse to the site? Is there a quick configuration somewhere which will allow this?

**Comment by webron** [comment]
It's a set of static pages. You can add any authentication layer through your web/app server that's configurable.

**Comment by lazyspark** [comment]
Thanks. I think then my question should be directed to the nuget package I am using. In this case I am using Swashbuckle will post there.
