### ISSUE TITLE
XML generation leads to "Uncaught RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by ojauch** [swagger-api/swagger-ui#2167]
I'm using the latest master version of swagger-ui.

If I define XML as valid consume or respond content type, swagger-ui isn't able to render all resources and aborts the rendering with the error message "Uncaught RangeError: Maximum call stack size exceeded" on the chrome console. If I set 'isXML' in OperationView and ParameterView to false everything works fine.

The swagger input files I want to use contain some recursive definitions.

**Comment by webron** [comment]
Please provide us with a spec that reproduces the issue so we can investigate it.

**Comment by ojauch** [comment]
This example spec reproduces the error on my instance: https://oskarjauch.me/swagger.json

**Comment by ojauch** [comment]
I think this bug occurs if a definition contains two loops of the same reference. The problem is that a model gets even removed from modelsToIgnore if the generator recognized that this model has caused a loop. For example:
`product {
  ...
  linkedProduct: {
    ref product
  },
  otherUserAlsoBought: {
    items: ref product
  }
}`
The XML generation can only work if the model 'product' doesn't get removed from modelsToIgnore until the generation of the root product is finished. I think I fixed this in my pull request but unfortunately travis had problems running 'npm install' and now shows errors in my pull request.
