### ISSUE TITLE
swagger ui ignores description field on model

### ISSUE THREAD

**Issue by asafbennatan** [swagger-api/swagger-ui#2169]
swagger ui - version 2.14

swagger.json model part:

`Category: {
type: "object",
required: [
"name"
],
properties: {
id: {
type: "string"
},
name: {
type: "string",
minLength: 1,
maxLength: 50
},
description: {
type: "string"
},
creationDate: {
type: "string",
format: "date-time"
},
updateDate: {
type: "string",
format: "date-time"
}
},
description: "Used to classify all types extending Baseclass"
}`
 UI:
![image](https://cloud.githubusercontent.com/assets/8994764/15456670/0110ee54-2080-11e6-9f2b-3706c06b78d8.png)

**Comment by webron** [comment]
This is resolved in 3.X.
