### ISSUE TITLE
Delete incorrect tag 2.0.17 (redundant with v2.0.17)

### ISSUE THREAD

**Issue by dolmen** [swagger-api/swagger-ui#2172]
In the Git repository, the format for release tags is vX.Y.Z, but a tag [`2.0.17`](https://github.com/swagger-api/swagger-ui/tree/2.0.17) exists in addition to [`v2.0.17`](https://github.com/swagger-api/swagger-ui/tree/v2.0.17).

Fix:
```
git tag -d 2.0.17
git push origin :2.0.17
```

**Comment by fehguy** [comment]
thanks, done.
