### ISSUE TITLE
tokenUrl not displayed in "Authorize" popup when using oauth2

### ISSUE THREAD

**Issue by stegob** [swagger-api/swagger-ui#2173]
Hi,

I am trying to integrate our authentication mechanism in swagger but it seems that swagger-ui does not behave as expected. Our authentication scheme is based upon oauth2 with client credentials grant ("application" flow in swagger terminology). According to the OpenAPI 2.0 specs, the "application" flow requires the tokenUrl to be defined in the swagger and that's we have done.
However, when clicking on "Authorize" button, at the top of the swagger-ui, when the "Available authorizations" popup comes up, the token URL is not displayed, only the "Authorization URL" field is present and is empty in our case. I have used a network sniffer and I have seen that although the tokenUrl is not displayed, it is still requested when selecting our scope and clicking on "Authorize" inside the popup window. However, it is a bit misleading to see "Authorization URL" when our "application" flow would have required to see the tokenUrl value.

Moreover, with "application" flow, I would have expected to send my client credentials in an Authorization header with bearer scheme but they are currently sent in the body with URL form encoded. Is there an easy way to force the client credentials to be sent in an Authorization header and to encode them in base64 ?

Here is the swagger-ui version used:
swagger-ui: master branch, commit aafca0f1933c8357bf5716e30ffa2f371f392b68.

Here is an extract of my swagger API doc:

{
...
    "securityDefinitions": {
        "okapi": {
            "type": "oauth2",
            "description": "Authentication made through okapi",
            "flow": "application",
            "tokenUrl": "https://okapi.xxx.xx/oauth/access_token",
            "scopes": {
                "HTTPS@kv-horsprod": "Default scope for hors-prod environment"
            }
        }
    },
    "security": {
        "okapi": [
            "HTTPS@kv-horsprod"
        ]
    },
...
}

Regards,

stegob

**Comment by webron** [comment]
This should be fixed in 3.X.
