### ISSUE TITLE
lib directory contains several libraries without licenses and copyright notices. This is a violation of the licenses of those libraries.

### ISSUE THREAD

**Issue by keskival** [swagger-api/swagger-ui#2174]
You should list the licenses and copyrights somewhere. As the libraries are not managed by package.json or bower.json, they bypass all the typical license checker tools.
A METALICENSE.md file should be ok, if you include the following information:

The respective licenses are listed here:

| File | License | Copyright |
| --- | --- | --- |
| lib/backbone-min.js | [MIT](https://github.com/jashkenas/backbone/blob/master/LICENSE) | 2010-2016 Jeremy Ashkenas, DocumentCloud |
| lib/handlebars-2.0.0.js | [MIT](https://github.com/wycats/handlebars.js/blob/master/LICENSE) | 2011-2016 by Yehuda Katz |
| lib/highlight.7.3.pack.js | [BSD 3-clause](https://github.com/isagalaev/highlight.js/blob/master/LICENSE) | 2006, Ivan Sagalaev |
| lib/jquery-1.8.0.min.js | [MIT](https://github.com/jquery/jquery/blob/master/LICENSE.txt) | jQuery Foundation and other contributors, https://jquery.org/ |
| lib/jquery.ba-bbq.min.js | [MIT and GPL](http://benalman.com/about/license/) | 2010 "Cowboy" Ben Alman |
| lib/jquery.slideto.min.js | [MIT](https://github.com/Sleavely/jQuery-slideto/blob/master/LICENSE) | 2015 Joakim Hedlund |
| lib/jquery.wiggle.min.js | [MIT](https://github.com/wilhelm-murdoch/jQuery-Wiggle/blob/master/LICENSE.txt) | 2011 - Wilhelm Murdoch wilhelm.murdoch@gmail.com, TheDrunkenEpic http://www.thedrunkenepic.com |
| lib/marked.js | [MIT](https://github.com/chjj/marked/blob/master/LICENSE) | 2011-2014, Christopher Jeffrey (https://github.com/chjj/) |
| lib/swagger-oauth.js | [Apache License 2.0](https://github.com/swagger-api/swagger-ui/blob/master/LICENSE) | 2016 SmartBear Software |
| lib/underscore-min.js | [MIT](https://github.com/jashkenas/underscore/blob/master/LICENSE) | 2009-2016 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors |
| lib/underscore-min.map | [MIT](https://github.com/jashkenas/underscore/blob/master/LICENSE) | 2009-2016 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors |

**Comment by keskival** [comment]
Apparently the newer version in the master branch has more libraries I have not checked, so the above list is not exhaustive. It also includes some files with licences given in the header (some headers are missing the copyright notice).
You can also add the license/copyright notices in the headers of the respective files.

**Comment by webron** [comment]
@keskival - thanks for bringing it to our attention.

**Comment by webron** [comment]
In 3.X, we no longer use this mechanism. All the dependencies are managed via the package.json.
