### ISSUE TITLE
Allow Swagger UI explore OAuth protected API definitions

### ISSUE THREAD

**Issue by AlexanderYastrebov** [swagger-api/swagger-ui#2177]

**Comment by csurbier** [comment]
+1

**Comment by shockey** [comment]
This is implemented :smile: just define an OAuth2 security scheme in your definition, and click `Authorize` near the top of Swagger-UI.

**Comment by AlexanderYastrebov** [comment]
@shockey Hello. It does not support definitions which are OAuth protected, i.e. which require Authorization to get API definition itself.

**Comment by shockey** [comment]
@AlexanderYastrebov, that isn't something we support currently.

However, you can implement that yourself with the [`requestInterceptor` and `responseInterceptor` options](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#network). Look for the `req.loadSpec`/`res.loadSpec` flags within an interceptor, and then attach your OAuth2 token to the request.

**Comment by shockey** [comment]
Converting this to a feature request

**Comment by shockey** [comment]
Closing as a duplicate of https://github.com/swagger-api/swagger-ui/issues/4324.
