### ISSUE TITLE
Wrong curl for the uploading of a file

### ISSUE THREAD

**Issue by AlexElin** [swagger-api/swagger-ui#2178]
Swagger-ui (v 2.1.4) gets wrong curl for file uploading.

I upload a file on http://petstore.swagger.io/#!/pet/uploadFile. 
Swagger gets the curl: 
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' 'http://petstore.swagger.io/v2/pet/1/uploadImage'

Although the curl should be like:
curl  -F "file=@/pathToFile"  'http://petstore.swagger.io/v2/pet/1/uploadImage'

see the http://stackoverflow.com/questions/12667797/using-curl-to-upload-post-data-with-files and https://curl.haxx.se/docs/manpage.html

**Comment by fehguy** [comment]
I think this would be nice, but it's impossible to do so.  The `@pathToFile` is strictly forbidden from javascript so there is no way to get the _path_ from the browser (browsers will send `fakepath` as the path location).

It would, however, be better if we showed the file _name_ instead, which is possible.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/efb77652274e99893b11848f02d9dc37d07344aa
