### ISSUE TITLE
Displaying Inline objects using formData as in

### ISSUE THREAD

**Issue by stcrestrada** [swagger-api/swagger-ui#2182]
Hi!,

I am currently using swagger-ui version 2.0. I have a json object that has nested kv pairs, which I can't submit using the type formData. 

Here is my json array:
```json
[
  {
    "firstName": "string"
    "lastName": "string",
    "dob": "string",
    "Address": {
      "street1": "string",
      "city": "string",
      "state": "string",
      "country": "string"
    },
    "phone": 0,
    "email": "string"
  }
]
```
Street, city, state, and country are considered the be the an inline model in swagger, but I don't want to submit the information as "in" "body", rather as "in" "formData". 

Any suggestions, I can't find anything on the web. 

Thanks!, 

Stephen

**Comment by fehguy** [comment]
Yes, that's because `formData` is _not_ JSON.  It's `x-www-form-urlencoded` or `multipart/form-data`.  If you want to send JSON in a _html form_, you should enable the `jsonEditor` per here:

https://github.com/swagger-api/swagger-ui#parameters
