### ISSUE TITLE
Delete Endpoint is not shown but present

### ISSUE THREAD

**Issue by Gobliins** [swagger-api/swagger-ui#2185]
I am using SwaggerUI release 2.1.4

This is my spec:

[sessions-v1.txt](https://github.com/swagger-api/swagger-ui/files/293124/sessions-v1.txt)

The delete /sessions/v1 endpoint is present but is not displayed in SwaggerUI

**Comment by Gobliins** [comment]
can someone confirm or better  find a solution?

**Comment by webron** [comment]
If you're talking about `delete /sessions/v1` I see it. 

If you're really talking about `delete /sessions/v1/delete` then you don't see it because... it's not in the spec.

**Comment by Gobliins** [comment]
@webron Yes i am talking about

'delete /sessions/v1'

Which version of swaggerui do you use?

**Comment by webron** [comment]
Current master.

**Comment by Gobliins** [comment]
I tested it under Linux, the endpoint appeared... is there a difference/problem between linux and windows by parsing the json spec?

**Comment by webron** [comment]
Doubtful. Same browser type + version?

**Comment by Gobliins** [comment]
I tested it in Chrome as well as in Firefox under Windows Server -> No Endpoint Shown
Same under Linux Server -> Endpoint Shown

**Comment by Gobliins** [comment]
OK i found out it is a cache problem from browser, issue can be closed !

**Comment by webron** [comment]
Thanks for the update.
