### ISSUE TITLE
Response examples

### ISSUE THREAD

**Issue by Somebi** [swagger-api/swagger-ui#2186]
Is there a way to display response examples? Well formatted pretty printed json for example.

Another feature would be awesome. If we could pre-fill fields with some test parameters, to test/try example right away.

**Comment by hlubovac** [comment]
Also see this: https://github.com/swagger-api/swagger-ui/pull/2469#event-925154274

* * *

Just something I noticed: example-json will be displayed for "success" responses (200 OK, 201 Created), but it will only work in swagger-ui while also appearing valid per swagger-editor if it's in a format such as this example snippet (paths > path-value > method-name > responses):

YAML:
```
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/errors-container'
          examples:
            application/json:
              jsonapi:
                version: '0.1'
                meta:
                  name: Sample API
                  location: 'https://localhost:44342/api/data'
              meta:
                request:
                  method: ''
                  url: null
                  uid: E69A10A5-05F6-5C3D-3B6C-0AE5E38F648A
                  received: '2017-01-19T22:16:21.1709246-07:00'
                  completed: '2017-01-19T22:16:21.6993952-07:00'
                  milliseconds: 528.4706
              errors:
                - title: Marvin-Abshire
                  detail: >-
                    Nisi nulla magnam hic magnam consectetur alias fugit. Et
                    alias dolor quia et doloribus doloribus corrupti. Est et
                    sapiente tempora nihil enim et placeat eligendi.
```

JSON:
```
"400": {
	"description": "Bad Request",
	"schema": {
		"$ref": "#/definitions/errors-container"
	},
	"examples": {
		"application/json": {
			"jsonapi": {
				"version": "0.1",
				"meta": {
					"name": "Sample API",
					"location": "https://localhost:44342/api/data"
				}
			},
			"meta": {
				"request": {
					"method": "",
					"url": null,
					"uid": "E69A10A5-05F6-5C3D-3B6C-0AE5E38F648A",
					"received": "2017-01-19T22:16:21.1709246-07:00",
					"completed": "2017-01-19T22:16:21.6993952-07:00",
					"milliseconds": 528.4706
				}
			},
			"errors": [
				{
					"title": "Marvin-Abshire",
					"detail": "Nisi nulla magnam hic magnam consectetur alias fugit. Et alias dolor quia et doloribus doloribus corrupti. Est et sapiente tempora nihil enim et placeat eligendi."
				}
			]
		}
	}
}
```

So, even though the above is valid and shows in other swagger-ui flavors, my conclusion is that the above works in this/classic swagger-ui (at least for me) only when the above status code is `200`. For me, for `400`, this definition above gets ignored, and I see an example JSON to be something that's likely generated by swagger-ui's script:

```
{
  "jsonapi": {
    "version": "string",
    "meta": {
      "name": "string",
      "location": "string"
    }
  },
  "meta": {
    "request": {
      "method": "string",
      "url": "string",
      "uid": "string",
      "received": "2017-01-20T19:42:06.663Z",
      "completed": "2017-01-20T19:42:06.663Z",
      "milliseconds": 0
    }
  },
  "error": [
    {
      "title": "string",
      "detail": "string"
    }
  ]
}
```

Refer to this as another example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/api-with-examples.yaml

Notice how JSON there is defined as a string (swagger-editor will let you export this as JSON, for comparison). When I attempted to do the same, it was valid per swagger-editor, but it was causing a fatal JavaScript error in swagger-ui.

Hopefully that helps. I'm not affiliated with swagger-ui team.
