### ISSUE TITLE
Boolean parameter in body causes Swagger page to not render that controller, and all controllers alphabetically after

### ISSUE THREAD

**Issue by Thunderforge** [swagger-api/swagger-ui#2190]
I have an endpoint that includes a boolean in the body of the request. The generated schema looks like this:

```
"parameters": [

    {
        "in": "body",
        "name": "someBoolean",
        "description": "someBoolean",
        "required": false,
        "schema": {
            "type": "boolean"
        }
    }

],
```
This is a valid endpoint, and I can use it just fine. However, when I try to render this in Swagger UI, I get the following:

![swagger failure edited](https://cloud.githubusercontent.com/assets/6200170/15511556/aa6b29ac-21a1-11e6-9141-31fe6ce180bc.png)

Note that the top of the page has the message "Finished Loading Resource Information. Rendering Swagger UI..." and there is an error in the console. The full error is as follows:

    swagger-ui.min.js:10 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    (anonymous function) @ swagger-ui.min.js:10
    Handlebars.templates.param_list.Handlebars.template.main @ swagger-ui.min.js:1
    e @ handlebars-2.0.0.js:27
    SwaggerUi.Views.ParameterView.Backbone.View.extend.render @ swagger-ui.min.js:10
    SwaggerUi.Views.OperationView.Backbone.View.extend.addParameter @ swagger-ui.min.js:10
    SwaggerUi.Views.OperationView.Backbone.View.extend.render @ swagger-ui.min.js:10
    SwaggerUi.Views.ResourceView.Backbone.View.extend.addOperation @ swagger-ui.min.js:11
    SwaggerUi.Views.ResourceView.Backbone.View.extend.render @ swagger-ui.min.js:11
    SwaggerUi.Views.MainView.Backbone.View.extend.addResource @ swagger-ui.min.js:10
    SwaggerUi.Views.MainView.Backbone.View.extend.render @ swagger-ui.min.js:10
    window.SwaggerUi.Backbone.Router.extend.render @ swagger-ui.min.js:10
    options.success @ swagger-ui.min.js:10
    y.buildFromSpec @ swagger-ui.min.js:2
    a.finish @ swagger-ui.min.js:3
    (anonymous function) @ swagger-ui.min.js:2
    a.resolve @ swagger-ui.min.js:2
    a.finish @ swagger-ui.min.js:3
    (anonymous function) @ swagger-ui.min.js:2
    a.resolve @ swagger-ui.min.js:2
    a.finish @ swagger-ui.min.js:3
    (anonymous function) @ swagger-ui.min.js:2
    a.resolve @ swagger-ui.min.js:2
    a.finish @ swagger-ui.min.js:3
    (anonymous function) @ swagger-ui.min.js:2
    a.resolve @ swagger-ui.min.js:2
    a.finish @ swagger-ui.min.js:3
    (anonymous function) @ swagger-ui.min.js:2
    a.resolve @ swagger-ui.min.js:2
    a.finish @ swagger-ui.min.js:3
    (anonymous function) @ swagger-ui.min.js:2
    a.resolve @ swagger-ui.min.js:2
    a.finish @ swagger-ui.min.js:3
    (anonymous function) @ swagger-ui.min.js:2
    a.resolve @ swagger-ui.min.js:2
    n.on.response @ swagger-ui.min.js:2
    l @ swagger-ui.min.js:2
    e.on.response @ swagger-ui.min.js:2
    (anonymous function) @ swagger-ui.min.js:2
    f.callback @ swagger-ui.min.js:10
    (anonymous function) @ swagger-ui.min.js:9
    r.emit @ swagger-ui.min.js:10
    n.onreadystatechange @ swagger-ui.min.js:10

Also in this particular example, there are four controllers: cluster-controller, message-controller, status-controller, and test-controller. The endpoint above is inside of status-controller and it does not appear on the page. However, the next controller alphabetically, test-controller, also does not appear, with no indication about the source of the problem or that other controllers are prevented from displaying.

This bug was originally [reported to Springfox](https://github.com/springfox/springfox/issues/1325), an implementation of Swagger with the Java Spring library, but I was told that it was in fact an issue with Swagger UI and its lack of support for a boolean parameter in the body, as shown above.

We are using Swagger UI 2.1.4.

**Comment by webron** [comment]
This is resolved in master already, please use that branch.
