### ISSUE TITLE
Array types render the namespace prefix but not the XML namespace

### ISSUE THREAD

**Issue by oconnorp** [swagger-api/swagger-ui#2191]
In the example below, an element defined as an array, when rendered in the UI, does not include the XML namespace.  For elements defined as primitive types (and at the same level as errors) include the namespace declaration correctly.

Expecting `<com:errors  xmlns:com="http://www.botw.com/schemas/rest/common">` but only get

`<com:errors>`

Swagger UI version: 2.1.4

From swagger file:

```yaml
errors:
        type: array
        description: Typically the response will havee EITHER a data element OR an errors element.  However, for partial responses, where some but not all of the products can be returned, there will be both a data and errors element.
        items:
          $ref: "#/definitions/Error"
        xml:
          name: errors
          namespace: http://www.botw.com/schemas/rest/common
          prefix: com
          wrapped: true
```

**Comment by bodnia** [comment]
part of https://github.com/swagger-api/swagger-ui/issues/2077
