### ISSUE TITLE
Enum titles support in swagger 2.1.4

### ISSUE THREAD

**Issue by velan123** [swagger-api/swagger-ui#2194]
Hello, the jdorn/jsoneditor used by swagger has the option to specify enum_titles for an enum. Enum titles allows the programmer to display different values in dropdownlist from the option value of the dropdown list. Is possible to do that in swagger? I tried and is not working. If not, can you implement this feature?

**Comment by webron** [comment]
Unfortunately, this is not supported by the spec.
