### ISSUE TITLE
allOf with external file references

### ISSUE THREAD

**Issue by marcogiglione** [swagger-api/swagger-ui#2196]
When you have a so defined allof attribute

"allOf": [
        {
          "$ref": "./operationMessage.json"
        },
        {
          "$ref": "./questionnaire.json"
        }
      ]

In which references are read from external files, it wasn't able to load definition

**Comment by dmytrobr** [comment]
For external references  I put reference to object defined inside file, not just file itself. For example your reference would look like: "./operationMessages.json#/MyMessage.

**Comment by marcopiraccini** [comment]
@dmytrobr to put the file only is correct. Indeed is the spec example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-separate/spec/swagger.json#L108

**Comment by webron** [comment]
This should no longer be an issue. We have an issue with relative URLs at the moment, but if you use the same construct with full URLs, it should work fine.
