### ISSUE TITLE
obj.enableCookies:true with useJQuery:true not working

### ISSUE THREAD

**Issue by Somebi** [swagger-api/swagger-ui#2197]
Using master branch.
I have noticed, that jQuery wrapper is not processing any options passed in the constructor.
Neither passed parameters are passed into execute of that wrapper.

**Comment by Somebi** [comment]
should set withCredentials:true and crossDomain:true

**Comment by Somebi** [comment]
or at least pass beforeSend callback

**Comment by webron** [comment]
Should not be an issue with the new UI.
