### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by assafko** [swagger-api/swagger-ui#2198]
when using swagger 2.1 i see page only renders after all endpoint data is received 
is there a way to:
1.lazy load the different endpoints when expanded
2.show a "loading" icon/message till all data received 

Thanks!

**Comment by webron** [comment]
@assafko - I believe we covered this in the google group?

**Comment by assafko** [comment]
Thanks !

**Comment by mseabaugh** [comment]
I know this is an old thread but can you point me to the google group that references lazy loading?
