### ISSUE TITLE
How to display an example rather than Inline Model {}

### ISSUE THREAD

**Issue by mal** [swagger-api/swagger-ui#2199]
I have an endpoint that accepts a map of objects attached to arbitrary key names, I can spec this using `additionalProperties` however it means that the example given in the UI for the request is just `Inline Model {}` which communicates very little. I've attempted to add an `examples` property to provide a sample request but this does not seem to get used.

Am I going about specifying this type of request incorrectly? Is there a better way to achieve what I'm attempting or is this simple a current limitation of swagger UI?

I have tried to grok the various issues, posts and docs about request examples to no avail. I have tried and had no success with `example`, `examples`, `x-example` and `x-examples`. I've also tried moving the inline part of the schema into a definition, however I was then met with `Uncaught TypeError: Swagger 2.0 does not support null types ([object Object]).  See https://github.com/swagger-api/swagger-spec/issues/229.` but unfortunately the referenced issue provided little in the way of help to my particular case.

Any help would be most appreciated as swagger UI is checking all the boxes for every other endpoint I've had to spec and I'd hate to have go looking elsewhere over a single example.

---

Swagger UI version: v2.1.0-alpha.6-1081-g56a62d9 (via `git describe`)
Test case:
```yaml
---
swagger: 2.0

host: localhost
basePath: /

info:
  title: Test Case
  version: 1.0.0

consumes:
- application/json
produces:
- application/json

schemes:
- http

definitions:
  Request:
    properies:
      data:
        description: Request data
        type: object
      method:
        description: HTTP method
        enum:
        - GET
        - PATCH
        - POST
        - PUT
        - DELETE
        type: string
      path:
        description: Request URI
        type: string
    required:
    - method
    - path

paths:

  /batches:
    post:
      description:
      operationId: create
      parameters:
      - in: body
        required: true
        name: body
        description:
          Map of request objects with significant keys.
        schema:
          type: object
          additionalProperties:
            $ref: #/definitions/BatchRequest
        examples:
          application/json:
            foo:
              method: GET
              path: /content/12
            bar:
              data:
                featured: true
              method: PATCH
              path: /content/15
      responses:
        201:
          description: Created
        400:
          description: Bad request
      summary: Create a new batch
```

**Comment by Afbcary** [comment]
https://xkcd.com/979/

**Comment by mal** [comment]
In case it's helpful, I eventually got something close to what I wanted by using the `example` key and placing it inside the `schema` and dropping the `content-type`. It doesn't solve the `Inline Model {}` issue, but it does instead show the desired example on the right hand side, and allow you to click it to copy it into the editable `textarea` so you can modify it before making a test request. Hope this helps!

```yaml
  /batches:
    post:
      description:
      operationId: create
      parameters:
      - in: body
        required: true
        name: body
        description:
          Map of request objects with significant keys.
        schema:
          type: object
          additionalProperties:
            $ref: #/definitions/BatchRequest
          example:
            foo:
              method: GET
              path: /content/12
            bar:
              data:
                featured: true
              method: PATCH
              path: /content/15
      responses:
        201:
          description: Created
        400:
          description: Bad request
      summary: Create a new batch
```

**Comment by Jeckyli** [comment]
Is it doable in Swagger 1.5.3? 

Sorry I'm not very familiar with the YAML format above, our code has Swagger Java Annotations for API descriptions like `@ApiParam()`

**Comment by webron** [comment]
@Jeckyli - Nope, you'd have to upgrade to the latest version.

**Comment by Jeckyli** [comment]
@webron ok, thanks for the quick response

**Comment by Jeckyli** [comment]
OK, looks like I was wrong, we were indeed using Swagger 2.2.2, I mistook the swagger-annotations-1.5.3 within it. 

So I still have this question, my POST API's request body is of Map type instead of the object class, but I still want to show the user  what keys can they have. Without switching to use a dedicated class as ApiModel for the body, can I simply add this info to the empty request body column on Swagger UI?

**Comment by webron** [comment]
You seem to be confusing things. There's no such thing as 'Swagger 2.2.2' because Swagger is not a single project. swagger-ui has a version 2.2.2 but it definitely doesn't bundle swagger-annotations in it or has anything to do with Java. swagger-core does *not* have a version 2.2.2.

**Comment by Jeckyli** [comment]
@webron Yes indeed, sorry about the confusion. We are using `springfox-swagger2`, version `2.2.2`, which uses below

    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-annotations</artifactId>
      <version>1.5.3</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-models</artifactId>
      <version>1.5.3</version>
      <scope>compile</scope>
    </dependency>

And regarding `swagger-ui` we use

    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>2.4.0</version>
    </dependency>

But after looking into it a little, seems that to make it happen, the Swagger generated API documentation JSON data must contain the part I need, and `Swagger-UI` just present that JSON in web page? Not sure if I understand this correctly though. If so, should I ask this question in a different project? Thanks a lot for the help.

**Comment by webron** [comment]
I have no idea if/how Springfox supports generating the examples so you'd need to ask them.

**Comment by Jeckyli** [comment]
Again, sorry about the confusion earlier. But after I read more and understand deeper of the different parties here, seems to me the question I have is still regarding on Swagger, especially Swagger-Annotation if I get it right. 

So basically the issue I have is my API takes a `Map<String, Object>` object in request body, like this,

```java
@ApiOperation(
		value = "Submit user data")
@RequestMapping(
		value = "/userData",
		method = RequestMethod.POST,
		consumes = {MediaType.APPLICATION_JSON_VALUE},
		produces = "application/json")
public ResponseEntity<?> submitUserData(
		@RequestBody
		@ApiParam(
			value = "JSON format input, keys allowed are key1, key2, key3."
		) Map<String, Object> userInput
```
I want to present the users a sample or the input schema, but I don't know how to properly put this info in Swagger, as by default it shows `Model Schema` as `{}` , I'd like to see something like,

```json
{
	"key1":"sample value1",
	"key2":"sample value2",
}
```

The generated Swagger JSON is as follows,

```json
{
  "in": "body",
  "name": "userInput",
  "description": "JSON format input, keys allowed are key1, key2, key3.",
  "required": false,
  "schema": {
    "type": "object"
  }
}
```

So here are my main questions based on my understanding,

1. Looks like if I can manage to put `additionalProperties` into the generated JSON like the issue filer did here, I should be able to get what I want, a key list for the users to follow. But I'm really not sure how to achieve this with annotations.

2. Same applies for the `example` used by the filer here, not sure how can I generate that with Swagger-Annotations.

I think the bottom line is I'm using a Map for request body type, thus I cannot utilize `@ApiModel` and `@ApiModelProperties` to customize the documents. Or can I? 

Sorry about the repeating questions, I'm getting more and more familiar with Swagger now, but probably still not enough yet. If this is not the right place for me to ask this question, could you kindly point me to the right direction? Thanks a lot.

**Comment by fehguy** [comment]
Hi, Springfox is great, and it utilizes some libraries from the [swagger-core](https://github.com/swagger-api/swagger-core) library.  But how it uses them is really up to that library, so I'd suggest that you open an issue [there](https://github.com/springfox/springfox).

**Comment by Jeckyli** [comment]
Sure, just posted one under Springfox. Thanks for the pointer. 

However one thing I'm still not very sure is that seems to me even though I'm depending on Springfox library, in my code I'm using the Swagger-Annotation interfaces directly. That's why I wrote up the previous comment with the details. 

So is that the annotations only represent the spec, and Springfox in my case handles the actual generation of Swagger data based on my usage? (kinda like javax and implementation libraries?) But even so, wouldn't the spec and annotations themselves determine the generated Swagger data? Or it depends on different implementation libraries behavior? 

Feeling I'm getting close to connect everything, really appreciate the help here!

**Comment by fehguy** [comment]
No problem.  This challenge is _how_ the annotations are interpreted is up to the library.  Springfox does it differently.  I'm not saying that it won't end up being a swagger-core issue, but it's quite possible to read the annotations and do different things with them.

**Comment by Jeckyli** [comment]
Got it, I'll follow up my question with them. 

I know I've been bugging you guys quite a bit, but I'll just (shamelessly) throw out this one last question. I now understand Springfox does all the API data/doc generation following Swagger spec. But my issue here is to try to find out the right usage of the annotations for my case rather than an unexpected behavior observed, then is it still an issue with Springfox? I don't even know whether there is an annotation usage (and if there is what is it) that is supposed to generate the Swagger data I want, so not sure if this is a valid question to them instead of Swagger-Annotation?

**Comment by fehguy** [comment]
Just remember that how the annotations are interpreted is up to SpringFox.  So it's worth posting the question there.  I really have no idea how they read them, and subsequently what they do with them, so that's your best starting point.

**Comment by hellsinglord22** [comment]
Where you create new `SwaggerUi` object, you add this script to the `onComplete` option . 
```
          $('.description').css('display', 'none');
          $('.snippet').css('display', 'block');
```
this will show example by default not the ugly inline models :)
