### ISSUE TITLE
In Chrome the formatXml in OperationView.js needs a long time to finish

### ISSUE THREAD

**Issue by yuxiaomin** [swagger-api/swagger-ui#2200]
This issue happens to the latest swagger-ui version 2.1.4.

To reproduce this issue open http://petstore.swagger.io/#!/pet/findPetsByStatus in chrome enter "available" in status textbox then click "Try it out" button. Then you can see that the progress icon freeze for a long time until the xml response shows. 

I also use 2.1.4 swagger-ui to build an API tester in my project. I find that the issue is caused by the formatXml method in OperationView.js. In chrome it needs more than one minute to format the large xml but in Firefox this process is much faster, only need about one second.

**Comment by webron** [comment]
This shouldn't be an issue with 3.X.
