### ISSUE TITLE
HowTo avoid InternetExplorer default cache effect

### ISSUE THREAD

**Issue by boly38** [swagger-api/swagger-ui#2203]
Using swagger-ui version  v2.1.4

Hello
I'm using Swagger and I would like to avoid cache effect with Internet Explorer (I know that this is a bad browser ;)).
By default, IE will cache json answer and If I do this sequence on a CRUD ReST API I've not the expected result

- get items => res A
- post new item => res B
- get items => res C

In my case, res A == res C but a new item is expected as res B is a success (I don't reproduce on another browser than IE).

To avoid this cache effect and as updating browser default cache policy is not an acceptable workaround, I find this way to add header to each ReST Query

    var apiKeyCacheA = new SwaggerClient.ApiKeyAuthorization("If-Modified-Since", "Mon, 26 Jul 1997 05:00:00 GMT", "header");
    var apiKeyCacheB = new SwaggerClient.ApiKeyAuthorization("Cache-Control",     "no-cache", "header");
    var apiKeyCacheC = new SwaggerClient.ApiKeyAuthorization("Pragma",             "no-cache", "header");
    // (...) 
    window.swaggerUi = new SwaggerUi({
        authorizations: {
                key:keyAuth,
                cacheA:apiKeyCacheA,
                cacheB:apiKeyCacheB,
                cacheC:apiKeyCacheC
        },
    // (...)

  My question is: does exist a better solution to do the same things ?

thanks

**Comment by fehguy** [comment]
Yea, well we should probably be invalidating the caches regardless.  You do have better options for this.

Create a request interceptor and set the headers _before_ the request is sent:

```js
var interceptor = {
  requestInterceptor: {
    apply: function (requestObj) {
      var headers = request.Obj.headers || {};
      headers['If-Modified-Since'] = 'Mon, 26 Jul 1997 05:00:00 GMT';
      headers['Cache-Control'] = 'no-cache';
      headers['Pragma'] = 'no-cache';
      return requestObj;
    }
  }
};

// assign the request interceptor in the UI
new SwaggerClient({
      url: 'http://localhost:8000/v2/petstore.json',
      requestInterceptor: interceptor.requestInterceptor,
...
```

If you like, consider opening an issue in swagger-js and we can add it as a simple option.

**Comment by boly38** [comment]
to be continue here : [swagger-js issue #792](https://github.com/swagger-api/swagger-js/issues/792)
