### ISSUE TITLE
Simple POST method not displayed in UI

### ISSUE THREAD

**Issue by danielm64** [swagger-api/swagger-ui#2204]
Hi,

I downloaded today the latest master version (2.1.4) and if most of my APIs are correctly handled, some fail with this version...

I extracted the problem (without understanding which is it...). Correctly display in swagger-editor (online demo), validator-badge ok, but method not displayed in ui...
The "Rendering Swagger UI" message does not disappear but none error displayed... And unfortunately, I'm not a Javascript expert to debug...

Attached:
 - screenshot of ui rendering
 - yaml sample file to reproduce

Thanks.
Daniel.

![postnotdisplayed](https://cloud.githubusercontent.com/assets/12515281/15858837/d327383c-2cc2-11e6-8a66-2a8199fdf831.png)

[POSTNotDisplayed.yaml.txt](https://github.com/swagger-api/swagger-ui/files/302666/POSTNotDisplayed.yaml.txt)

**Comment by webron** [comment]
@danielm64 - just tried running the provided sample. It loads well, both when I convert it to JSON and embed it into the the index.html and when I host the yaml file and load it in swagger-ui with the URL.

The text 'Finished Loading Resource Information....' that you see at the top does indicate an issue though. So assuming you are using the latest master (and not the released 2.1.4) and you can reproduce it locally, can you check your web console for any errors?

**Comment by danielm64** [comment]
Thanks @webron .
Yes, there's an error message in the console (using Chrome):
![postnotdisplayed-chromeconsole](https://cloud.githubusercontent.com/assets/12515281/15885338/eb442972-2d56-11e6-9c0e-e1279ae0988a.png)

**Comment by fehguy** [comment]
Hi, I have tested this too and cannot reproduce it with master.

**Comment by webron** [comment]
@danielm64 - can you try re-cloning the repo and give it another go? If it works for both @fehguy and me with master, and it doesn't for you, I'm not sure how to continue investigating it.
