### ISSUE TITLE
Invoking "OPTIONS" method causes javascript error

### ISSUE THREAD

**Issue by thomseno** [swagger-api/swagger-ui#2207]
Having a spring-boot application with spring-boot-actuator activated, calling options method of /health endpoint results in the following error:

![swagger_ui_und_new_issue_ _swagger-api_swagger-ui](https://cloud.githubusercontent.com/assets/4829874/15892148/6f306db0-2d78-11e6-949c-8b39bd85d9a4.jpg)

swagger-ui version 2.1.4 (provided via spring-fox 2.5.0)

**Comment by webron** [comment]
Can you try the latest master?

**Comment by thomseno** [comment]
Hi, tried latest master of swagger-ui. Built dist, integrated into dptingfox-swagger-ui [springfox-swagger](https://github.com/springfox/springfox) and tested my demo spring-boot application. Works 👍 
So, issue can be closed... but what is the schedule of next release of swagger-ui (so that springfox can integrate latest version)?

**Comment by webron** [comment]
We're planning on a release soon, just need to finish a few fixes.
