### ISSUE TITLE
[Enhancement] Hide blank "Base URL"

### ISSUE THREAD

**Issue by deckar01** [swagger-api/swagger-ui#2208]
Version: `v2.1.4`

When the `basePath` is empty the template is still rendering the label.

![ base url: , api version: 1.0.0 ](https://cloud.githubusercontent.com/assets/3108007/15895757/a045c984-2d52-11e6-8e4a-0878af121324.png)

It would be more consistent if the label was hidden when the `basePath` is empty, to match the way [the version label](https://github.com/swagger-api/swagger-ui/blob/master/src/main/template/main.handlebars#L23) is rendered. I image the conditional comma would be slightly more complex.

**Comment by webron** [comment]
No longer an issue with 3.X.

**Comment by ravindramavenwave** [comment]
I got the problem resolved by using the same version of swagger-ui(2.6.1) and swagger2(2.6.1)
