### ISSUE TITLE
PATCH does not have input fields for parameters

### ISSUE THREAD

**Issue by michellesanver** [swagger-api/swagger-ui#2210]
In a PATCH operation the parameters do not have an input box, changing to GET or any other method shows the input boxes, so it is really only for PATCH. 
<img width="1425" alt="screen shot 2016-06-09 at 14 09 57" src="https://cloud.githubusercontent.com/assets/570982/15929674/acc026da-2e4e-11e6-87f3-1e69c9954d28.png">

swagger-ui version: 2.1.3

JSON: [https://gist.github.com/michellesanver/f76f8922b41fbbc27ee4e2283b094592](url)

**Comment by webron** [comment]
Make sure that `patch` is included in the `supportedSubmitMethods` array - https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L55.

**Comment by michellesanver** [comment]
Thanks! I checked but it's there.

**Comment by michellesanver** [comment]
Thank you so much! Turns out the bundle we were using for Symfony in PHP overrode the submit methods and did indeed not have PATCH as one, easy fix once you know it but would have taken me ages to find without this reply <3
