### ISSUE TITLE
How to generate a Json file 

### ISSUE THREAD

**Issue by tianxiaoliang** [swagger-api/swagger-ui#2212]
I set up a Swagger UI, I want to generate A json File and publish it in nginx , when user input a json URL and click explore ,user can see the doc.
The problem is how I can generate this json file automatically from code?

**Comment by webron** [comment]
@tianxiaoliang - this is more of a general support question that should go to the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket). If you'd like to generate a swagger spec from your code, you'd need to choose a library that works with your environment. Check out the list at [swagger.io](http://swagger.io/open-source-integrations/). If you need further assistance, post the question with the details in the group.
