### ISSUE TITLE
Help - How to - Spring

### ISSUE THREAD

**Issue by royremi** [swagger-api/swagger-ui#2215]
I'm using spring boot and documenting my api with swagger.

I have a post action that consume a json object.

Swagger show me a default object like.

{
    variable = "test"
    active = true
}

I would like to be able to change the default model displayed in the swagger-ui page. Like active = false instead of true.
is it possible?

I tried to use @ApiModelPropertied but I don't see any default value available.

Thanks for the help!

**Comment by webron** [comment]
I'm not sure if you're using swagger-core or springfox. It's also unclear if you're looking to change the example, or actually set the default value to be false. Either way, this is not an issue with swagger-ui, but to the project you use to generate the spec. Please reopen the ticket on the appropriate project and you'll get further assistance there.

If you're uncertain which project, use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) to post the question and we'll take it from there.
