### ISSUE TITLE
Potential contribution to improve accessibility - curious to get feedback from contributors

### ISSUE THREAD

**Issue by brittag** [swagger-api/swagger-ui#2216]
Hi Swagger people! I work for [18F](https://18f.gsa.gov/), a team in the United States federal government, and we have [a fork of Swagger UI](https://github.com/18F/swagger-ui) with [a number of customizations](https://github.com/18F/swagger-ui/commits/master) we made to better support [Section 508 accessibility standards](https://www.section508.gov/). We'd like to contribute these customizations upstream to this main project, since we figure that many other teams and users would benefit from better accessibility as well.

The tricky part is that our changes are based on an old version. So before we do the work of preparing a pull request for this current version, I'd like to check with current contributors and maintainers: Do you think these changes would fit well into the current state of this project and its roadmap? If so, would you prefer to dig through our commits and salvage anything useful, or would you prefer that we prepare a pull request? Thanks!

**Comment by webron** [comment]
Thanks for reaching out. 

The version of swagger-ui that you're using is indeed old - it's before we even officially announced support for 2.0, but was rather a work in progress.

In general, we're always open to accept changes and PRs if those make sense for the public.
Before we decide if/how we should proceed, is it possible to get some more details as to the essence of the changes? I'm worried that just following the commits may not give level of clarify in such changes.

**Comment by resjwa** [comment]
Hi guys! I, too, am working on a project that needs swagger-ui to meet 508 standards. It seems that @brittag made some contrast and labeling adjustments (looks great!), but there are still some issues, I think. For instance, the show/hide controls, and the info associated with them need some JS/ARIA help in order to be 508 compliant, I think. Is there a current effort going on for 508/UI, or is swagger-UI not compliant out of the box, and needs customization in order to be fully 508-compliant?

**Comment by brittag** [comment]
Unfortunately I don't think our team is going to have time available to help with moving our work upstream soon, but please draw from our work if helpful!

**Comment by resjwa** [comment]
Thanks @brittag - There's more investigation on this matter in progress. I could post here if Swagger-People want.

**Comment by robinwhittleton** [comment]
Yes please.

**Comment by CodingSamurai** [comment]
I'm also interested in making sure Swagger UI is 508 compliant.

**Comment by ponelat** [comment]
Closing this out in favour of https://github.com/swagger-api/swagger-ui/issues/7350 where the latest work on accessibility is being actively worked on. It's also possible to look at the `cat: a11y` GitHub label for other related tickets.
