### ISSUE TITLE
JavaScript runtime error: Object.keys: argument is not an Object error while using Swagger UI in IE 11.

### ISSUE THREAD

**Issue by disha-s** [swagger-api/swagger-ui#2221]
I am getting the following error while using Swagger UI in Internet Explorer 11.

Unhandled exception at line 2, column 27219 in http://localhost:52697/service/help/swagger-ui.min.js

0x800a138f - JavaScript runtime error: Object.keys: argument is not an Object.

I am using "Swashbuckle.SwaggerUi": "6.0.0-beta9"

**Comment by webron** [comment]
@disha-s - that's the version of Swashbuckle, not swagger-ui. Check the version at the top of the swagger-ui.js file.

**Comment by disha-s** [comment]
swagger-ui.js file has version 2.7.1.

**Comment by webron** [comment]
Can you verify that please? Current version is 2.1.4... 2.7.1 doesn't exist.

**Comment by disha-s** [comment]
where do i look for the version?

**Comment by peyterkim** [comment]
Getting a similar error in ie11

`SCRIPT438: Object doesn't support property or method 'assign' 
swagger-ui.js, line 19177 character 9`

The Swagger UI loads with all my endpoints but the security definitions have a problem so the 'Authorize' button doesn't show up. The top of the page hangs on `Finished Loading Resource Information. Rendering Swagger UI...`

**Comment by fehguy** [comment]
Can you please confirm your versions for swagger-ui and swagger-js?  Look in your swagger-ui.js file, you'll see something like this:

```
/**
 * swagger-ui - Swagger UI is a dependency-free collection of HTML, JavaScript, and CSS assets that dynamically generate beautiful documentation from a Swagger-compliant API
 * @version v2.1.4
 * @link http://swagger.io
 * @license Apache-2.0
 */
```

```
/**
 * swagger-client - swagger-client is a javascript client for use with swaggering APIs.
 * @version v2.1.15
 * @link http://swagger.io
 * @license Apache-2.0
 */
```

**Comment by peyterkim** [comment]
```/**
 * swagger-ui - Swagger UI is a dependency-free collection of HTML, JavaScript, and CSS assets that dynamically generate beautiful documentation from a Swagger-compliant API
 * @version v2.1.4
 * @link http://swagger.io
 * @license Apache-2.0
 */

**Comment by fehguy** [comment]
@bodnia can you please look at this?

**Comment by eavonius** [comment]
This is definitely an issue in IE11 for me as well. This is using the latest nuget package version of Swashbuckle 5+ as of August 4th. Looks like there may have been some commits, but it's still not readily available.

**Comment by bodnia** [comment]
@eavonius could you please confirm if you still can reproduce the issue with latest master?

**Comment by fehguy** [comment]
Please see https://github.com/swagger-api/swagger-ui/commit/a906cffea4550eaa5369e4933a50753213cf09df

**Comment by peyterkim** [comment]
@fehguy - are you sure that a906cff is the commit that addresses this issue?

**Comment by peyterkim** [comment]
to fix the IE issue, did you just add the es5-shim library to the repo and add it as a reference in index.html?

**Comment by bodnia** [comment]
@peyterkim [this](https://github.com/swagger-api/swagger-ui/issues/2221#issuecomment-242513323) is correct
