### ISSUE TITLE
Make it possible to jump to a model via custom markdown

### ISSUE THREAD

**Issue by kkworden** [swagger-api/swagger-ui#2222]
This is just a suggestion. When a user is writing their API documentation, they should be able to link to a model (or any other object in their API) by using hyperlinks. Although the `$ref` object is good when documenting a response or a parameter, being able to reference models in summaries and descriptions is crucial to good documentation. 

For example when writing a description, since markdown is supported, it would make sense to be able to link to a model using anchor tags like so:

```
...
      responses:
        200:
          description: 'Returns a Response object whose **data** field contains a [Question](#/models/Question).'
          schema:
            $ref: '#/definitions/Response'
...
```

Then when a user views the documentation, `Question` would be rendered as a hyperlink that would jump them to that model in the documentation.

This would be trivial to accomplish with Angular. I don't know if this is already possible in the current version of Swagger (v2.0); I have been unable to find documentation on the subject. I could submit a PR, but if this is feature already being planned or currently exists, it should be documented on the wiki or on the site's specification.

**Comment by etki** [comment]
+1

**Comment by webron** [comment]
Pretty much implemented in 3.X.

**Comment by ssimplix** [comment]
@webron, how can I create an anchor to a model? Don't see any ID's in models and anything about it in docs.
