### ISSUE TITLE
Ampersand character within triple backquotes is incorrectly rendered

### ISSUE THREAD

**Issue by dalbani** [swagger-api/swagger-ui#2225]
It seems that all `&` characters contained within triple backquotes are incorrectly rendered, as `&amp;` instead of simply `&`.
For example, for this definition:

`````` yaml
swagger: '2.0'
info:
  title: Test API
  description: |
    A description with an ampersand with triple backquotes:
    ```&```
...
``````

The result is:
![backquotes](https://cloud.githubusercontent.com/assets/1470270/16154018/448326e2-34a9-11e6-9eda-e0dffc47331a.png)

Version: latest `master` as of today, i.e. commit `efb77652274e99893b11848f02d9dc37d07344aa`.

I supposed the issue is not _directly_ related to SwaggerUI itself, but I have no idea which dependency library is responsible for the rendering.

**Comment by bholt** [comment]
Running into this myself. I think it may be a bug in the `marked.js` library:

- chjj/marked#779
- chjj/marked#287

**Comment by asnelzin** [comment]
Actually, it reproduces not only with ampersand, but with some other special characters. Is there any progress?

**Comment by jobec** [comment]
Same here.
Make putting code examples in the `description` rather useless...

The Swagger Editor doesn't have this problem btw.

**Comment by webron** [comment]
Please retest with 3.X.

**Comment by dalbani** [comment]
@webron: still applicable on 3.0.18.
Can be tested with something as simple as ``
```&```  `&`
``.
It's rendered in both cases as `&amp;`.
On the other hand, `<code>&</code>` works fine.

**Comment by webron** [comment]
The `&` is known and is tackled in a different ticket, I just can't find it now.
