### ISSUE TITLE
POST resource with image/png wont display actual image

### ISSUE THREAD

**Issue by helt** [swagger-api/swagger-ui#2226]
I'm using swagger-ui by adding springfox 2.5.0 wrapper to my spring-boot application. 

The resource is responsible for generating an `image/PNG` out of a rather complex parameter-set. Thats why the parameters are `POST`-ed to the resource. as result, the image is transmitted in the `ResponseBody`

This approach works, when I use postman, or use the resource in my actual webapplication frontend. However, swagger does something strange:

a) the result image is the default "browser-didnt-find-an-image-at-this-url" image 
b) in the console, swagger POSTs the correct request, but then triggers a subsequent GET on the same address which is not bound:
![swagger-bug](https://cloud.githubusercontent.com/assets/1732112/16151754/fd8a7416-349e-11e6-8fe0-742a9047dcc1.png)

It appears like swagger-ui simply inserts a `<img>` tag into the response body area which obviously doesnt know anything about the fact that it should POST to the address.

Would it make sense to insert the POST response body into the `<img>`-tag as base64-encoded image, instead of simply inserting a `<img>` which GETs the resource?

**Comment by yvdh** [comment]
I confirm this, I have the exact same problem. I would really appreciate this feature ...

**Comment by helt** [comment]
can someone point me to the code, where i could add this?

**Comment by fehguy** [comment]
Hmm.  This is probably an issue in swagger-js.  @helt if you have a sample specification, could you please share it in that project in a new issue?  I will get that tested quickly, we do have a release of swagger-ui coming soon and I'd like to get this resolved first.

**Comment by helt** [comment]
uhm, to be honest, i only use swagger, and all the nitty gritty details does the springfox plugin. Before I stumbled over this bug, I wasn't even aware that there is some kind of specification on the disk / on a rest service, that swagger uses... So I'm pretty unknowledgable regarding this matter.

@fehguy What do you need exactly? [I added a gist from my `api-docs` response](https://gist.github.com/helt/1c435d87a44d3429710279eac7afbd48#file-api-docs-json), maybe this helps to get things started?!

**Comment by dgreenbean** [comment]
This is the same problem I have run into with issue #1652.  Unfortunately, I don't have a ready-made example on hand.  Basically, any POST route that accepts image/png will have this problem.

**Comment by helt** [comment]
@fehguy did my comment from july, 9th address your information need?

**Comment by yvdh** [comment]
Nope. A post which expects an image in the response still results in an extra GET that returns a 'Method not accepted' (obviously).

**Comment by fehguy** [comment]
OK, so two things going on here.

First, to be clear--and this is different from what @dgreenbean is saying, your definition is _not_ posting an image to the server.  It's posting an object `ImageParameters`.

Next the response is being represented as a `FileSystemResource`.  This could be ok, but in your case, there is no corresponding `FileSystemResource` object defined in the `definitions` block.  Thus, when swagger-ui receives a response, it is expecting something very different from what is received.  If you are sending back an image, you would be describing it as follows:

```
type: string
format: byte
```

When a response of type `image/jpg` is received by swagger-ui, you'll get a rendering of it in the UI.

**Comment by dgreenbean** [comment]
Has that changed recently?  As of a few months ago, any route accepting an HTTP POST and returning Content-Type image/png would not work in Swagger UI.  The POST request would succeed, but Swagger would put the route in the src of an img tag, causing a subsequent GET request.

**Comment by fehguy** [comment]
It definitely renders in-line, I tested today.  Can you please retest against master?  Only one `GET` per image operation.

**Comment by helt** [comment]
@fehguy uhm. not sure, but a `GET` request should not be issued at any point in time, as that verb is not supported by the url. 

Seems to me like thats the pain point here. The path allows post requests ONLY, anything else is not supported.

**Comment by fehguy** [comment]
@helt ah hah!  I've reproduced this.  The comments above had me confused, stand by for an update on this.

**Comment by fehguy** [comment]
@helt FYI we've released a new version of swagger-js and will be working on this before the next swagger-ui release.

**Comment by fehguy** [comment]
This should be fixed in https://github.com/swagger-api/swagger-ui/tree/4bdaeba797224bde922f3cefe55a6807428437a8

Please give your feedback on #2404 so I can know to merge.

**Comment by fehguy** [comment]
Fixed by https://github.com/swagger-api/swagger-ui/commit/656808b20cffcca4f6daff1741c4685d70be5757

**Comment by helt** [comment]
ty. awesome. but hard for me to test it as my actual enviroment is feeded by components downstream...

**Comment by fehguy** [comment]
@helt just open a new issue if you have any issues on this
