### ISSUE TITLE
Gulp 'dist' task does not work with newest 'gulp-header' version.

### ISSUE THREAD

**Issue by K1ll3rF0x** [swagger-api/swagger-ui#2227]
Hi,

I forked this project, installed dependencies and tried to produce a new build with  the 'dist' task, but it does not work.

The problem seems to be in code line where you add the header text on top of the concatted code: **header(banner, { pkg: pkg })**. 
This breaks the filestream, so uglify will receive an empty stream and no built files are saved in the './dist' folder.

The actual problem seems to be in the newest 'gulp-header' version, which is 1.8.3. I tested building with version 1.2.2 and the build passes with no problems.

I suggest that you use at least Tilde Ranges (~) instead of Caret Ranges (^) in your package.json, so new versions of dependencies will not break the build tools. 
Using NPM Shrinkwrap would be even better.

Node version: 4.4.5
NPM version: 3.9.5

**Comment by omarsmak** [comment]
I have a similar issue with this as well

**Comment by alessandrovaccaro** [comment]
I also have the same issue as @K1ll3rF0x . I have tested that everything seems to be working correctly with gulp-header@1.8.2. Also there is an [issue](https://github.com/tracker1/gulp-header/issues/41) open on gulp-header project that might be related to this problem.

**Comment by K1ll3rF0x** [comment]
Haha, thanls @alessandrovaccaro. :+1: 
I was just looking at that issue myself, and was about to reference it here, but you were faster than me.

**Comment by alessandrovaccaro** [comment]
@K1ll3rF0x actually I am glad you narrowed it down to gulp-header, I had my hard time to understand what was the cause of the incomplete build. Also because gulp itself carries on and doesn't trow any obvious error.

**Comment by K1ll3rF0x** [comment]
However, this issue might be more possible reason for our problem: [gulp-header#36](https://github.com/tracker1/gulp-header/issues/36), because we are not getting any unhandled errors and concatted JS-files are not physically on the disk when adding headers in them. 
It seems that version gulp-header 1.8.4 is coming in near future.

**Comment by tracker1** [comment]
Okay, gulp-header 1.8.6 should correct all outstanding issues... my fault for merging without doing a thorough enough review/consideration of the issue.

I've refactored detection to use vinyl's built in conventions.

**Comment by K1ll3rF0x** [comment]
Now that the build process is working fine again, I'll close this issue.
Nevertheless, I'll create a new issue related to improving the dependency management of this project to avoid similar issues in the future.
