### ISSUE TITLE
External reference to examples object

### ISSUE THREAD

**Issue by mdigirolami** [swagger-api/swagger-ui#2228]
It seems to me that latest swagger-ui release doesn't support external reference (to another file/resource, not only to a specific definition within the current swagger file) for "examples object", I mean this:

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#examplesObject.

It is that? I tried to use external reference with swagger-ui 2.1.4 but it seems to me that they aren't resolved, can you confirm this? If yes, please can you confirm that instead this will be possible with a next/future release and approximately the related release date?

Thanks in advance!
Marco

**Comment by fehguy** [comment]
That link is to the 3.0 spec which isn't released. But tibia possible that they are the same for 2.0 and not working as expected.

Please open an issue in the swagger-js project and provide an example

**Comment by mdigirolami** [comment]
ok, done: https://github.com/swagger-api/swagger-js/issues/801

Thanks.
Marco
