### ISSUE TITLE
Adding examples to the response does not seem to work for arrays of objects

### ISSUE THREAD

**Issue by switzer** [swagger-api/swagger-ui#2230]
Hi - I am using the version of swagger UI that is in SwaggerHub.

I have a response definition that contains an example.  The response is an object:

```
        200:
          description: The filter that was requested is returned
          schema:
            $ref: '#/definitions/Filter'
          examples:
            application/json: |-
              {"name": "bidstream.country"}
```

When clicking on the 'Example Value' under 'Response Class (Status 200)', I get the example as expected.

However, when I try to define a response that is an array of the same object as above, the example does not show.

Here is the response code definition that does not work:

```
        200:
          description: An array of filters
          schema:
            $ref: '#/definitions/Filters'
          examples:
            application/json: |-
              [
                {"name": "bidstream.country"},
                {"name": "bidstream.creative_size"},
                {"name": "bidstream.device_ids"},
                {"name": "authenticated.accurate"},
                {"name": "authenticated.direct"}
              ]
```

Note that the filters object above is defined as an array of object of a Filter type.  Both definitions are as follows:

```
definitions:
  Filter:
    type: object
    properties:
      filter_id:
        type: string
      name:
        type: string
  Filters:
    type: array
    items:
    - $ref: '#/definitions/Filter'
```

I am not sure if there is an issue or if my definition is not correct in some way.

**Comment by webron** [comment]
This should no longer be an issue in the new UI.
