### ISSUE TITLE
Improve project dependency management

### ISSUE THREAD

**Issue by K1ll3rF0x** [swagger-api/swagger-ui#2232]
The project dependency management should be improved to produce consistent builds in Travis and by developers and to avoid issues like this: #2227.

Where to start?
Ideally, builds should be always consistent and predictable. 
First, I suggest that Tilde Ranges _(~)_ should be used instead of Caret Ranges _(^)_ in the package.json, so new versions of dependencies will not break the build tools. This way one gets critical patches, but not possibly breaking minor changes. 
However, this is not perfect, because one has to trust that the developer of a package does not publish any breaking changes. Additionally, the underlying dependencies of packages can also change if the package is using version ranges, like most are.

To resolve these issues, one should use _NPM Shrinkwrap_ and always use dependency versions that have been confimed working. However, the drawback of this approach is that the project manager has to update the dependencies manually. The big plus is that we get always predictable builds and no unnecessarily broken builds in build automation.

**Comment by noizbuster** [comment]
+1

**Comment by webron** [comment]
We've discussed this among ourselves and decided not to do it.
