### ISSUE TITLE
Removing ":port" from Request URL 

### ISSUE THREAD

**Issue by kennytnguyen** [swagger-api/swagger-ui#2236]
I'm on swaggerVersion: "1.2" right now and when I send a request URL, it sends a 

"https://{server_ip}:{port}/....."

How do I get rid of the ":{port}" values from the Request URL?

**Comment by fehguy** [comment]
Is it using a standard port?  What does your `basePath` look like?

**Comment by kennytnguyen** [comment]
my base path looks like

{{server_proto}}://{{server_ip}}/{{api_url}}. but they come out as 
{{server_proto}}://{{server_ip}}:{port}/{{api_url}}. it's using internal port.

**Comment by kennytnguyen** [comment]
oops. yes* a standard port.

**Comment by fehguy** [comment]
OK got it.  I think this was introduced recently with swagger-js 2.1.15.  Could you please open an issue in [that project](https://github.com/swagger-api/swagger-js) and it'll get fixed?

**Comment by kennytnguyen** [comment]
Okay, I'll wait in the meantime. Thanks!

**Comment by kennytnguyen** [comment]
Fixed. In shred.bundle.js.

`  url: {
    get: function() {
      if (!this.scheme) { return null; }
      return sprintf("%s://%s%s%s",
          this.scheme, this.host, getPortString(this.scheme, this.port), //removed Port
          (this.proxy ? "/" : this.path) +
          (this.query ? ("?" + this.query) : ""));
    },`

you can take out the colon from %s://%s%s%s
