### ISSUE TITLE
Escaping of | within a table cell of a description

### ISSUE THREAD

**Issue by ralfhandl** [swagger-api/swagger-ui#2237]
I'm generating Swagger descriptions from code artifacts. Part of the overall description is best represented as a table, but some of the table cells contain text that includes the `|` character.

GFM documentation says to escape the `|` with a backslash as `\|`, and this works e.g. here in GitHub:

```
foo | bar
----|----
baz | qux\|quux
```

results in 

| foo | bar |
| --- | --- |
| baz | qux|quux |

Unfortunately this works neither in Swagger UI nor in Swagger Editor. 

What does work in Swagger Editor is HTML-escaping the `|` as `&#x7c;`

![capture](https://cloud.githubusercontent.com/assets/951576/16333166/1c8b4fba-39fa-11e6-841c-a647a72c8385.PNG)

Yet this does not work in Swagger UI, it apparently first decodes `&#x7c;` into `|` and then feeds it onto the formatter, resulting in three columns for the second table line, and loss of the `|`:

![capture2](https://cloud.githubusercontent.com/assets/951576/16333231/7f06cdae-39fa-11e6-8aeb-4b3515e247ea.PNG)

Thanks in advance
Ralf

**Comment by heldersepu** [comment]
Weird `&#x7c;` worked for me on UI:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Company/Company_Post
This issue has been open for quite a while maybe it got fixed along the way...

**Comment by ralfhandl** [comment]
You're right, it works with Swagger UI 3.10.0.
Still broken in Swagger UI 2.x, and I assume it will stay that way.
