### ISSUE TITLE
Map query parameters are not working as expected.

### ISSUE THREAD

**Issue by dilipkrish** [swagger-api/swagger-ui#2241]
Given the following definition

```java
  //spring-mvc definition
  @RequestMapping(value = "/category/{id}/map", method = RequestMethod.POST)
  public ResponseEntity<Void> map(@RequestParam Map<String, String> test) {
    return ResponseEntity.ok(null);
  }

   //Jax-rs definition
   @POST
   @Consumes("application/x-www-form-urlencoded")
   public void map(MultivaluedMap<String, String> test) {
     // Store the message
   }
```

Produces the following spec. The spec is a valid spec for the parameter (test) which is an open ended grab  bag of query parameters. 

```json
{
   "basePath":"/springfox",
   "host":"localhost:8080",
   "info":{
      "contact":{
         "name":"springfox"
      },
      "description":"",
      "license":{
         "name":"Apache License Version 2.0",
         "url":"https://github.com/springfox/springfox/blob/master/LICENSE"
      },
      "termsOfService":"http://springfox.io",
      "title":"Springfox petstore API",
      "version":"2.0"
   },
   "paths":{
      "/category/{id}/map{?test}":{
         "post":{
            "consumes":[
               "application/json"
            ],
            "operationId":"mapUsingPOST",
            "parameters":[
               {
                  "description":"test",
                  "in":"query",
                  "items":{
                     "additionalProperties":{
                        "type":"string"
                     },
                     "type":"object"
                  },
                  "name":"test",
                  "required":true
               }
            ],
            "produces":[
               "*/*"
            ],
            "responses":{
               "200":{
                  "description":"OK"
               },
            },
            "summary":"map",
            "tags":[
               "category-controller"
            ]
         }
      }
   },
   "swagger":"2.0",
   "tags":[
      {
         "description":"Category Controller",
         "name":"category-controller"
      }
   ]
}
```

However in swagger-ui, when we load this spec, we see this error 

<img width="490" alt="screen shot 2016-06-26 at 8 37 52 am" src="https://cloud.githubusercontent.com/assets/73257/16362610/5e0c6af2-3b79-11e6-8b88-cb47f9e731e0.png">

_NOTE:_ This error manifests itself in editor.swagger.io as well.

**Comment by fehguy** [comment]
Maps are not supported in query params in the 2.0 spec but you shouldn't get this error. Are you using master?

**Comment by dilipkrish** [comment]
This is using 2.14 (the latest released swagger-ui). If you c&p the json in editor.swagger.io, you should see the same error. It may ultimately be a problem in swagger.js, haven't dug into it I'm afraid.

**Comment by fehguy** [comment]
Please retry with Master

**Comment by dilipkrish** [comment]
Sure. Will let u know. Is there an ETA on the next cut of swagger-ui? Seems like it has a lot of good fixes

**Comment by fehguy** [comment]
Very soon, in fact, I'd like to this week.

**Comment by igreenfield** [comment]
What the status of this?

**Comment by Mario-Eis** [comment]
+1

**Comment by borellaster** [comment]
I have the same problem using @ResquestParam with java.util.Map.

**Comment by ouaibsky** [comment]
Same for us with @ResquestParam with java.util.Map<String, String>

**Comment by galaxya2009** [comment]
Is there any update on this? We really want to use swagger in our rest api and it will be helpful for me to avoid  separately documenting everything if swagger works

**Comment by fehguy** [comment]
Well, query parameters with Maps are simply not supported in the specification, and therefore not in the UI.  You can only have primitives, arrays of primitives for query and path parameters.  If you have a Map, it should be in a _body_ parameter with a `POST` operation.  This is not a restriction of swagger-ui, it's a restriction of the OpenAPI Specification.

That said, the specification will be changing in 3.0 to allow complex schemas in all inputs.  That will solve it, but not with the 2.0 spec.

**Comment by galaxya2009** [comment]
Hi 

If you see spring ref
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestParam.html 

It does support Map. 
What is rough timeline for 3.0

**Comment by fehguy** [comment]
An implementation of a spec and a spec are quite different, and we can't control what people do with the spec implementation itself other than discourage things that are not supported.  3.0 sometime this year.

**Comment by dilipkrish** [comment]
Here is the link to the (openapi issue for 3.0](https://github.com/OAI/OpenAPI-Specification/issues/349#issuecomment-180581603).

The [springfox](http://springfox.io) implementation favors minor spec transgressions  over gaps in the documentation especially for common spring usage patterns (and jax-rs patterns). However, I feel the swagger-ui should identify _any_ transgression rather than throw its hands up in the air with an error that is hard to trace or do root cause analysis without stepping through the debugger.

**Comment by galaxya2009** [comment]
Thanks for replying. Do you guys know what is the alternative to MAP<String,String> @requestparam , where I can accept n number of request parameters.

**Comment by st2rseeker** [comment]
You can get get the request param map by:
`Map params = request.getParameterMap();`
(if you add the `HttpServletRequest request` into the function)
and then you can get your parameters from there.

Waiting for a fix for the issues, but for now that's an acceptable hack. :)

**Comment by MilanDi90** [comment]
Hi @dilipkrish,
Is this still not supported in later versions of springfox (ie. 2.10.* or 3.0.0)
