### ISSUE TITLE
Request header "Content-Type" is not being sent with request

### ISSUE THREAD

**Issue by manish2aug** [swagger-api/swagger-ui#2242]
Hi,
Not sure how I can refer another logged issue here so just posting the url. I logged this on springfox repository but it was mentioned that this issue should be logged on this repository.

[https://github.com/springfox/springfox/issues/1361](url)

**Comment by fehguy** [comment]
@manish2aug this has been fixed in master for swagger-ui.  Please use that and reopen if you still see a problem.
