### ISSUE TITLE
Enum model scheme not being displayed in response status

### ISSUE THREAD

**Issue by danny95djb** [swagger-api/swagger-ui#2246]
I'm using springfox 2.5.0 (not sure what version of swagger-ui is being used). When an enum is present in the response type the model schema and description are not being displayed.
Heres the Json:
`"responses":{  
               "200":{  
                  "description":"OK",
                  "schema":{  
                     "type":"string",
                     "enum":[  
                        "SUCCESS",
                        "FAILED"
                     ]
                  }
               }`

**Comment by webron** [comment]
Try using the latest master.

**Comment by danny95djb** [comment]
@webron im not sure how to go about that

**Comment by webron** [comment]
Clone this repository, open dist/index.html and point it to your spec.

**Comment by danny95djb** [comment]
I'm getting an access control error at the moment, will report back when i have spare time to try and fix
