### ISSUE TITLE
Try-It response headers only show "Content-Type"

### ISSUE THREAD

**Issue by abreksa4** [swagger-api/swagger-ui#2250]
swagger-ui version: master (23bb103)

When using the "Try-It" functionality, the only headers shown under "Response Headers" is "Content-Type". However, the Network tab of Firebug shows the remaining headers for the request. 

This can be reproduced with the [Petstore example swagger document](http://petstore.swagger.io/v2/swagger.json).

**Comment by webron** [comment]
Closing in favor of #2261 - you came first, but he has pictures ;)
