### ISSUE TITLE
External reference not resolved

### ISSUE THREAD

**Issue by mdigirolami** [swagger-api/swagger-ui#2255]
Hi all,
I'm using swagger-ui 2.1.4.

I have some problems with references, in attachment you can see the screenshot with the problem: the referenced content (definition of probB) is not visible into swagger-ui.
Please note that the used URL is correct (if I open the URL on a separate browser window the file is correctly detected and downloaded). I tried to replace the URLwith the corrispondent in absolute form (http://localhost:8090/apibp/api/operationExitCode_test.json) but I have the same problem.

If you take in account the attached screenshot:
- to define "propA" I have not used an external reference;
- to define "probB" I have used an external reference, but its definition is not showed.

In attachemnt you can also see used json files:
- swagger-test-reference.json: the main file;
- propA-noref.txt: the definition of propA (no reference);
- propB-ref.txt: the definition of propB (with reference to file operationExitCode_test.txt);
- operationExitCode_test.txt: the referenced file from parent propB-ref.txt.

Can you help me?
Thanks
Marco

![swagger-reference-problem](https://cloud.githubusercontent.com/assets/12843872/16566520/87dc5408-4215-11e6-99fc-41ef9b9ebdc9.png)
[swagger-test-reference.txt](https://github.com/swagger-api/swagger-ui/files/346616/swagger-test-reference.txt)
[propA-noref.txt](https://github.com/swagger-api/swagger-ui/files/346617/propA-noref.txt)
[propB-ref.txt](https://github.com/swagger-api/swagger-ui/files/346618/propB-ref.txt)
[operationExitCode_test.txt](https://github.com/swagger-api/swagger-ui/files/346619/operationExitCode_test.txt)

**Comment by webron** [comment]
Two suggestions:
1. Test it with master and not 2.14.
2. Change the references from `./....` to just `....`. This may work - it's a workaround though as what you have should work as well, but it helps with analysis.

**Comment by mdigirolami** [comment]
I've changed references as suggested in point 2 but the problem remains, I also tried again with absolute URLs but it's the same.
I've tried with master code but I contine to see the problem.

It seems to me very strange, is it possible for you to try to reproduce the problem (even using my posted files)?

**Comment by webron** [comment]
Yeah, it looks like there's an issue with the deeper resolution (probably rooting in swagger-js). Thanks for providing the samples, helped testing (nice touch with modifying the internal files to point to txt as well).

**Comment by mdigirolami** [comment]
Hi Ron!
did you get the chanche to get a look into the problem or testing something?

tnks
Marco

**Comment by webron** [comment]
@mdigirolami - not personally, no. Can't give you an ETA on this.

**Comment by TobiasXy** [comment]
In my project I'm currently at more than 4000 lines of code in one file and it's still growing.
Is there currently (until this bug is fixed) any way to not have everything in one file?

**Comment by fehguy** [comment]
@tobiasxy this scenario is very specific and in general external references work fine. Please share details of the issue you're having if it's different from this one, and in a new ticket

**Comment by webron** [comment]
This should be resolved in 3.X.
