### ISSUE TITLE
Multiplie versions same REST API docs

### ISSUE THREAD

**Issue by scion4581** [swagger-api/swagger-ui#2260]
Hello. I didnt find any info about how to make multiplie version of same REST API.

Is there any way to achieve this?

**Comment by webron** [comment]
You can follow the instructions at https://gist.github.com/webron/7c41db7f777471fcbc10 to see how to load multiple specs in a single instance of swagger-ui. However, managing multiple versions is not necessarily related to swagger-ui, so for further questions, please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).
