### ISSUE TITLE
Some headers are missing from "Response Headers" output

### ISSUE THREAD

**Issue by HouzuoGuo** [swagger-api/swagger-ui#2261]
Swagger UI is from master branch, revision 23bb1039b931dd8e27598de261cdc52b6ea698c8.

API definition in JSON explicitly says the API endpoint shall respond with a header "Authorization", yet the header is not shown in the "Response Headers" output, see this screenshot:

![screenshot from 2016-07-06 08-36-56](https://cloud.githubusercontent.com/assets/563872/16609564/7204f626-4355-11e6-9d14-158abf9a74bb.png)

JSON is the following:

<pre>
{
  "swagger": "2.0",
  "schemes": [
    "http"
  ],
  "host": "localhost:12113",
  "basePath": "/v1",
  "produces": [
    "application/json"
  ],
  "consumes": [
    "application/json"
  ],
  "info": {
    "version": "1.3.2",
    "title": "SwaggerUI Test",
    "description": "test\n"
  },
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "definitions": {
    "Category": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    }
  },
  "paths": {
    "/token": {
      "post": {
        "tags": [
          "Token"
        ],
        "summary": "auth test",
        "description": "auth test\n",
        "parameters": [
          {
            "name": "domain",
            "in": "formData",
            "description": "name",
            "required": true,
            "type": "string"
          },
          {
            "name": "email",
            "in": "formData",
            "description": "Email for a user to authenticate.",
            "required": true,
            "type": "string"
          },
          {
            "name": "password",
            "in": "formData",
            "description": "Password",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "User credentials accepted",
            "headers": {
              "Authorization": {
                "description": "JWT token string",
                "type": "string"
              }
            }
          },
          "401": {
            "description": "User credentials not accepted."
          }
        }
      }
    }
  }
}
</pre>

**Comment by fehguy** [comment]
To be clear, you're saying that a response header is not being displayed?  That is the issue?

**Comment by webron** [comment]
@fehguy something changed in what headers are being displayed in general. If you take the version that's currently deployed to petstore.swagger.io, and run the POST /pet operation, you'll see a nice list of headers. Running master locally shows less of those.

**Comment by fehguy** [comment]
Last I looked into this, some headers were being removed by superagent.  So that may be the case, I'll take a look.

**Comment by abonec** [comment]
I have the same issue with this json  https://gist.github.com/abonec/baea5cfac177ba53726af24a62a82793

**Comment by abreksa4** [comment]
+1

**Comment by fehguy** [comment]
I believe this is a CORS issue.  You may need to expose the missing headers with `'Access-Control-Expose-Headers': 'Content-Disposition'` on your server, where `Content-Disposition` is the header you want to appear.

**Comment by abreksa4** [comment]
@fehguy That did the trick for me, headers are now showing in the 'Response Headers' section.

**Comment by bkapellusch** [comment]
+1 .... I see the response header when using Postman or ARC,  but not when using swagger UI.

**Comment by webron** [comment]
Shouldn't be an issue anymore.

**Comment by stevebor1** [comment]
> I believe this is a CORS issue. You may need to expose the missing headers with `'Access-Control-Expose-Headers': 'Content-Disposition'` on your server, where `Content-Disposition` is the header you want to appear.

CORS issue exposing Content-Disposition for me while using the swagger-ui embedded within my Vue application. Adding `'Access-Control-Expose-Headers': 'Content-Disposition'` to my Spring Filter fixed the issue!
