### ISSUE TITLE
Header are not added from java script  with swaggerUi.api.clientAuthorizations.add(), but exist in Curl

### ISSUE THREAD

**Issue by hmahida** [swagger-api/swagger-ui#2263]
When reporting a bug, please provide the following details:
- swagger-ui version 2.0
- a swagger file reproducing the issue : index.html

I am trying to add header named 'token' for each api call as;

swaggerUi.api.clientAuthorizations.add("key1", new SwaggerClient.ApiKeyAuthorization("token", "xxxxxxxxxxxxxxxxx", "header"));

But I do not receive that header on server, also inspecting request header in browser is not showing that newly added header, it just send standard default headers.

But, swagger info message for the curl request for the same shows the header I added.
What could be the reason?

**Comment by fehguy** [comment]
My guess is your server does not support the header `bearerToken`?  It's the same code so it should be trying to send it.  Take a look at your OPTIONS calls to see what it's trying and post back.

**Comment by hmahida** [comment]
Thanks for reply ! @fehguy   Here, I get the jwt token after my basic Auth request to server. In response I receive 

token: " JWT Token" 
and then I need to send that token for all the API request after that to server.

So, for my GET request, the pre flight OPTIONS is responding;

Request Method:OPTIONS
Status Code:401 Unauthorized

As token is not exist in header, I check  that using debug on server side.

Hope I am clear here!

**Comment by hmahida** [comment]
Ok, I have updated my server side to response Pre Flight request.

So, now for OPTIONS request I get 200, but still the actual request header has no "token" header I added as.
swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("token", "xxxxxxx", "header"));

Please help!!!

**Comment by hmahida** [comment]
Hi,
Here is part of yaml file;


securityDefinitions:
  key:
    type: "apiKey"
    in: "header"
    name: "token"
  
host: "10.x.1.x"

basePath: "/a/bs/api/v1"
schemes:
- "https"
produces:
- "application/json"

paths:
  /GetConfig:
    get:
      tags:
      - "Devices"
      security:
        - key: []
      summary: "Get Device Config"
      description: "Information about the current configurations for device."
     
      parameters:
.
.
.

And I use ;

swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("token", bearerToken, "header"));

my request Header sent is as;

OPTIONS /a/bs/api/v1/GetConfig?Id=6 HTTP/1.1
Host: :10.x.1.x
Connection: keep-alive
Access-Control-Request-Method: GET
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Access-Control-Request-Headers: accept, token
Accept: */*
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6

CURL created as;

curl -X GET --header 'Accept: application/json' --header 'token: ffsdfsdffsfdffsdfsdfsdf' 'https://10.x.1.x/iot/bs/api/v1/GetConfig?sensorId=6'
Thanks!

**Comment by jamesjara** [comment]
I have trying to solve same issue for around 8 hours,I can not add any header for the button Try, forthe first load will work

**Comment by wmbutler** [comment]
Same issue here. Any thoughts on resolution timeframe?

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
