### ISSUE TITLE
Example of enum values and of list of objects are not represented correctly

### ISSUE THREAD

**Issue by bureaquete** [swagger-api/swagger-ui#2264]
swagger-ui version -> 2.5.0

The problem I have with swagger is that I wanted to use `@ApiModelProperty` with example values, to generate default RQ objects for each API. But the example values I put for list of integers, or enums with values never work well... As an example;

```
public class TheClass {

    @ApiModelProperty(example = "1,2,3")
    private List<Integer> numbers;

    @ApiModelProperty(example = "1")
    private TestEnum testEnum;
}

public enum TestEnum {
    IN(1), OUT(2);

    private final Integer value;

    TestEnum(Integer value) { this.value = value; }
}
```

When this `TheClass` used in a given controller's RQ object, its json becomes this;

```
"test":{  
   "numbers" : "1,2,3",
   "testEnum" : "OUT"
}
```

Though I wanted to get this;

```
"test":{  
   "numbers" : [1,2,3]
   "testEnum" : "1"
}
```

But since the field example only accepts String values, I need to know whether what I want to do is possible or not?

**Comment by webron** [comment]
There's no swagger-ui 2.5.0. However, the issue is with the spec generation, not the spec display. Please open the ticket on the project you use to generate your spec.
