### ISSUE TITLE
Multiple example values supported?

### ISSUE THREAD

**Issue by gkumar7** [swagger-api/swagger-ui#2265]
Possible feature request:

The ui seems to currently support only viewing the first enumeration as the "Example Value". Is it possible to show multiple example values in the ui?

``` yaml
enum:
  - value1
  - value2
  - value3
```

Should correlate two "Model, Example Value 1, Example Value 2, Example Value 3" in the UI.

**Comment by webron** [comment]
Closing as this didn't attract feedback from other users. Unlikely to happen.
