### ISSUE TITLE
Swagger UI doesn't display parameters when references are flattened

### ISSUE THREAD

**Issue by anjayajodha** [swagger-api/swagger-ui#2267]
I'm trying to use the Swagger UI with a dereferenced JSON file, using this [dereferencer](http://bigstickcarpet.com/swagger-parser/www/index.html). 

This works with the sample Pet Store API, but fails when I use the Azure Swagger api from [here](http://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/2015-06-15/swagger/compute.json)

Steps to Reproduce on Swagger UI 2.1.4
1. Paste the URL to the JSON into the dereferencer, and select "Dereference It!"
1. Select the resulting text and paste it into its own JSON file.
1. Load the output JSON file in to the UI and select "Explore".
1. Expand an API section and Path. 
1. For the Pet Store API, the parameters will display correctly, for the Azure API, it will not display any parameters.

**Comment by webron** [comment]
It'd help if you can provide the dereferenced JSON.

**Comment by anjayajodha** [comment]
Here's a link to the [Pet Store JSON](https://raw.githubusercontent.com/anjayajodha/flattenedjson/master/dereferenced_petstore.json) and the [Azure API JSON] (https://raw.githubusercontent.com/anjayajodha/flattenedjson/master/dereferenced_azure.json).

**Comment by fehguy** [comment]
I don't think this is valid swagger.  At a quick glance, you have some schema objects which have properties without keys, and `allOf` as a sibling, which I think is not legal

**Comment by anjayajodha** [comment]
Okay, I'll take a look at that. The validator gave me a green "Valid" button, so I thought it was legal.

**Comment by webron** [comment]
It's hard to read such a spec, but there are certainly things about it that are 'not right' rather than being invalid.

That said, if it's a single file, why would you bother dereferencing it in the first place?

If you can point to a specific operation + parameter that doesn't appear in the UI, it'd help isolate the actual problem.
