### ISSUE TITLE
Uncaught RangeError: Maximum call stack size in grails

### ISSUE THREAD

**Issue by Andrius89** [swagger-api/swagger-ui#2268]
I'm working with grails 2.5.4 and whenever I declare ManyToMany relationship between two domain models I'm getting Uncaught RangeError: Maximum call stack size.
- swagger-ui version: v2.1.4
- a swagger file reproducing the issue: lodash.min.js, index.js 

![maximum call stack size](https://cloud.githubusercontent.com/assets/20418375/16765332/17639dc6-483c-11e6-9c6d-79293de941af.png)

**Comment by fehguy** [comment]
Please grab master and re-test.  This should be addressed

**Comment by Andrius89** [comment]
I updated swagger with a latest version from master but this problem still retains.

**Comment by webron** [comment]
Shouldn't be an issue with the latest version.
