### ISSUE TITLE
External refs within arrays not fully working

### ISSUE THREAD

**Issue by mbalex** [swagger-api/swagger-ui#2277]
**Version**: db1d742 (zip download via github)

**Problem summary**:
An array as base schema cannot properly reference external jsons within external references jsons. The reference within the reference isn't expanded in the UI.

Using external references:
- Array -> Object(1) **works**
- Array -> Object(1) -> Object(2) **does not work** (only expands Object(1) but not Object(2))
- Object -> Array -> Object(1) -> Object(2) **works** (since Object is the base schema)

Using internal references:
- Array -> Object -> Object **works only if** not within the same swagger space as the non working external reference variant (something must destroy ref resolution).

Attached are the files I used to try out different use cases:
[refarrayissue.zip](https://github.com/swagger-api/swagger-ui/files/366432/refarrayissue.zip)

And here a screenshot with the problem:
![refissuewitharray-swagger-ui](https://cloud.githubusercontent.com/assets/6682351/16881135/f2c8485c-4ab8-11e6-98b5-29ad3fc861d5.PNG)

**Comment by pfebolo** [comment]
True, you can not see the definition of an object, if it is in an external file (YAML / JSON) and the object is in an Array.  . It's frustrating

**Comment by fehguy** [comment]
Looks like this is working now 
![image](https://cloud.githubusercontent.com/assets/249413/20577091/95ef1560-b175-11e6-920b-d13a90e36c13.png)
