### ISSUE TITLE
how to add object descriptions on a different page or module

### ISSUE THREAD

**Issue by onkarganjewar** [swagger-api/swagger-ui#2278]
- swagger-ui version: V2.0

Currently I'm in the process of integrating Swagger UI to my existing Spring MVC RESTful service. Everything is working great. There is just one thing that I'm not able to figure out; **is there any way that I could include the objects descriptions as a separate module in a Swagger UI?** 
    As long as I understand, Swagger provides the response object schema and model which includes all the description that we provide for a particular variable or entity of an object. But, the same definition or description gets attached to all the operations which use that same object for their implementation. For instance, there is an object named 'Biller' in my project and I use it for 4 different REST calls, so now the same description about the 'Biller' object is getting attached to all those different REST calls. 
Earlier I used different documentation tool for my project and it had provided me with a way to place all the objects along with their descriptions in a separate module. So that the user had a way to parse through all the objects descriptions before going on to check their usage in various REST calls.
I have attached the screenshots of my previous documentation along with the current Swagger UI implementation of my project. Please take a look and let me know if there is any way that I could place the objects descriptions in a different module than the REST calls in Swagger UI. 

![swagger](https://cloud.githubusercontent.com/assets/14006620/16890901/e4bdfb5a-4aa7-11e6-9451-8b8946db1d17.png)
![billerrest](https://cloud.githubusercontent.com/assets/14006620/16890900/e4bcad36-4aa7-11e6-8f45-ff7b42d47843.png)
![fps](https://cloud.githubusercontent.com/assets/14006620/16890902/e4be7bca-4aa7-11e6-8c49-4a5e5747907b.png)

**Comment by webron** [comment]
Out of the box - no, there isn't a way to do that. You can of course modify the sources to fit your needs.
