### ISSUE TITLE
Feature request: Add posibility to enter clientId and clientCredentials when authorizing

### ISSUE THREAD

**Issue by prochnowc** [swagger-api/swagger-ui#2284]
We have WebAPI which uses "Application" flow (clientId and clientCredentials). When we expose our documentation using Swagger UI we dont want to put clientId and clientCredentials in index.html, the user should be able to choose these parameters.
Please add possibility to let the user enter these parameters in the authorize dialog.

**Comment by webron** [comment]
Can you check if the latest version does that already?

**Comment by webron** [comment]
Closing due to lack of feedback. If anyone encounters this and feels it's still an issue, either add a comment or a submit a new ticket.
