### ISSUE TITLE
Links are not relative, cause bad navigation

### ISSUE THREAD

**Issue by tyrsius** [swagger-api/swagger-ui#2286]
I am using swagger ui `v2.1.4`.

I am rendering on a non-root page `site.com/api/myApi`. The Swagger docs endpoints that get rendered are all links, and they point to the root site with a hash `site.com/#!/default/get_v1_apis`. Clicking any of these inputs causes the browser to navigate back to the home page.

How do I get these links to be relative to the page they are on?
Or, is there a way to disable the hash navigation and not update the URL at all?

**Comment by tyrsius** [comment]
It even happens if I rewrite the url on all the anchors to `javascript:void(0);`, or call `preventDefault()` from a click handler. This is super weird behavior

**Comment by tyrsius** [comment]
I just disabled BBQ

```
window.$.bbq.pushState = () => {}
```

**Comment by alechirsch** [comment]
+1

**Comment by webron** [comment]
Shouldn't be an issue with the latest version.
