### ISSUE TITLE
dist\swagger-ui.js code has a problem for <if>  condition in SwaggerClient.prototype.initialize

### ISSUE THREAD

**Issue by hzwei206** [swagger-api/swagger-ui#2290]
swagger-ui version: I download the zip code, don't know the version
code file: swagger-ui-master.zip\swagger-ui-master\dist\swagger-ui.js

when I deployed the swagger-ui dist with tomcat, the chrome hint: 
XMLHttpRequest cannot load http://localhost:8082http//petstore.swagger.io/v2/swagger.json

so I debug the swagger-ui.js, found that: 
////////////////////////////////////////////////////////////////////////
the error code:
///////////////////////////////////////////////////////////////////////
SwaggerClient.prototype.initialize = function (url, options) {
     .........................
  if(**this.url && (this.url.indexOf('http:') === -1 || this.url.indexOf('https:') === -1)**) {
    // no protocol, so we can only use window if it exists
    if(typeof(window) !== 'undefined' && window && window.location) {
      this.url = window.location.origin + this.url;
    }
  }

  options = options || {};
  .............................
}
////////////////////////////////////////////////////////////////////////
the first **if** condition is error! when the value of "this.url"  has "http://", it still into the if code.

swagger-ui-master.zip\swagger-ui-master\dist\swagger-ui.min.js has same problem.

**Comment by hzwei206** [comment]
modify the || to && : 
if(this.url && (this.url.indexOf('http:') === -1 **&&** this.url.indexOf('https:') === -1))

**Comment by maxbrokman** [comment]
I'm also having this issue having just downloaded dist as well

**Comment by fehguy** [comment]
Please re-pull from master.  Preparing for a release and that commit slipped in unnecessarily.

**Comment by fehguy** [comment]
fixed in 2.1.5
