### ISSUE TITLE
Swagger-ui issue with large-ish APIs

### ISSUE THREAD

**Issue by Nepoxx** [swagger-api/swagger-ui#2292]
I get the following "error" on the UI: 

```
Finished Loading Resource Information. Rendering Swagger UI...
```

Here is my swagger file: https://gist.githubusercontent.com/Nepoxx/892b9d725bbd707f7ca3b4a13a7ae2e2/raw/801a19197d34a4fae154e2e139da6ac0f5925be2/api.json

which can be used with http://petstore.swagger.io/ for instance (the bug will happen as well).

The issue seems to be coming from the `/userinfo` path, if I change the `tags` to anything else, the page fails differently.

Any idea what might be wrong?

**Comment by fehguy** [comment]
Try 2.1.5, just released today.   This page renders just fine for me with it:

![image](https://cloud.githubusercontent.com/assets/249413/17038589/4f3153fe-4f4b-11e6-8507-b98709adb0f2.png)

**Comment by Nepoxx** [comment]
Latest version does fix this. Thank you!

**Comment by fehguy** [comment]
great, thanks for confirming!
