### ISSUE TITLE
OAuth: Second time authorize is not working

### ISSUE THREAD

**Issue by frankietaylor** [swagger-api/swagger-ui#2294]
Steps to reproduce:
- Go to http://petstore.swagger.io/
- Click on Authorize
- Click Cancel
- Click on Authorize
- Select OAuth scopes - say read:pets
- Click on Authorize in the dialog

(Nothing happens)

Expected: Should do authorization as expected

**Comment by frol** [comment]
It seems to be resolved as I cannot reproduce it anymore.

**Comment by fehguy** [comment]
Please open a new issue if you see this again.
