### ISSUE TITLE
OAuthSchemeKey undefined in onOAuthComplete()

### ISSUE THREAD

**Issue by ralfstuckert** [swagger-api/swagger-ui#2296]
I set up swagger 2.0 with spring boot in order use implicit flow with a login page. I f I click the authentication button, my login site pops up, a bearer token is generated and passed to the swagger UI site. But the bearer token (resp. the authorization header) is not set in requests. After some debugging I isolated the problem:

In `o2c.html` the method `window.opener.onOAuthComplete(qp);` is called, where qp in this case contains the access token, e.g.
`{ "access_token": "e680a84e-9719-40a2-91d9-9989c5b4c22b" }`

But the method `onOAuthComplete` in `swagger-oauth.js` accepts two parameters, the token and the oauth schema key:
`window.onOAuthComplete = function onOAuthComplete(token,OAuthSchemeKey) {`

At the end of this method the second parameter is used to add an authorization:

`window.swaggerUi.api.clientAuthorizations.add(OAuthSchemeKey, new SwaggerClient.ApiKeyAuthorization('Authorization', 'Bearer ' + b, 'header'));`

Since the `OAuthSchemeKey` is now undefined, it will not be found (and used) later on when making an actual request. When I fixed this live in debugger and set the `OAuthSchemeKey` to my scheme name "oauth2", everything worked quite well, the bearer token was set in every request.

**Comment by huiwang** [comment]
+1

**Comment by webron** [comment]
Closing as likely no longer an issue in the new UI. If anyone finds it's still an issue, either add a comment or file a new ticket.
