### ISSUE TITLE
Publish Docker image to Dockerhub

### ISSUE THREAD

**Issue by omeid** [swagger-api/swagger-ui#2298]
It would be nice if you guys setup an official docker image using [Docker trusted builds](https://docs.docker.com/docker-hub/builds/).

This would allow people to use swagger ui with just one command

``` bash
docker run -p 80:8080 swagger-api/swagger-ui-builder
```

**Comment by programster** [comment]
I agree. For now there is the schickling/swagger-ui image which has 50k+ pulls and 34 stars so its definitely in demand!

**Comment by webron** [comment]
It's there.
