### ISSUE TITLE
Unusual behaviour with header

### ISSUE THREAD

**Issue by AkashMalhotra** [swagger-api/swagger-ui#2300]
Using the latest Swagger-UI, I noticed some odd layout behavior which causes the widgets to move around when I flip between APIs. Note: this occurs every time the window.swaggerUi.load(); is called Should I modify the css or what? If you go to the demo ,you will also see the authorize button disappear for a second when explore is clicked.

http://giphy.com/gifs/l0MYEhoVvCWPPTQre

**Comment by webron** [comment]
Shouldn't be an issue with 3.X.
