### ISSUE TITLE
Issue with $ref and external references

### ISSUE THREAD

**Issue by aguerotSOVINTY** [swagger-api/swagger-ui#2304]
Hi all,

I am using http://petstore.swagger.io as my swagger-ui container.

I am having a hard time trying to setup $ref external references. They are not resolved by swagger-ui 
You can clone this project for repro code and steps: https://github.com/aguerotSOVINTY/repro-testswaggerreferecences

Here are the repro steps as described in readme.md file:
Repro steps:

launch express server: node index.js
navigate to http://petstore.swagger.io
enter http://localhost:8888/test.json and click on explore
expand Queries / /get/{id}
on 200 response, click on model
 -> http://localhost:8888/test.json#/definitions/ErrorResponse {}
    this is resolved as a remote $ref whereas it is defined as local in test.json
 -> http://localhost:8888/Customer.json#/definitions/Customer {}
    this reference exists but is not found  
 => are not resolved

same on Commands / post /myCustomActionName
 -> http://localhost:8888/test.json#/definitions/ErrorResponse {}

If I merge the content of customer.json and toto.json with test.json everything works fine.

I'd be glad if anyone could shed some light on why I'm facing this issue.

Rgds

**Comment by webron** [comment]
Well, I think you're facing it because there's a bug.

**Comment by aguerotSOVINTY** [comment]
If you can point me to the right direction, I'm willing to dig in further into swagger-ui to try to locate the issue more precisely

**Comment by fehguy** [comment]
Please look at swagger-js in the tests. If you can help produce a failing test in that structure, it will can applied to swagger-UI on next update

**Comment by aguerotSOVINTY** [comment]
I've identified that this is the combination of allOf and external $ref that causes the issue. 
I'm not too sure tho that this is swagger-js that is causing the issue. From what I can see, data seems consistent from swagger-js point of view

**Comment by aguerotSOVINTY** [comment]
I confirm that my swagger file is displayed correctly using http://editor.swagger.io
So I think the issue lies on swagger-ui's side rather than swagger-js

**Comment by webron** [comment]
@aguerotSOVINTY swagger-editor doesn't use swagger-js...

**Comment by aguerotSOVINTY** [comment]
Ok my bad. I wrote a test case for swagger-js and created a pull request [https://github.com/swagger-api/swagger-js/pull/828](url)
