### ISSUE TITLE
slashes in path

### ISSUE THREAD

**Issue by nmalik** [swagger-api/swagger-ui#2305]
Hi,

My URL is like this:-
http://localhost:8080/TestLocal/rest3/env/Test%20Logic/test1/2/merge 

now in this test1/2 is my folder name and I want to encode this slash to %2F where as rest slashes shall not be encoded. Does swagger supports any parameter based encoding for such case that partly we encode the URL?

**Comment by webron** [comment]
Slashes are not supported in path parameters, if that's what you're asking.

**Comment by fehguy** [comment]
All path parameters are encoded
