### ISSUE TITLE
Publish on Packagist for Composer (PHP)

### ISSUE THREAD

**Issue by teohhanhui** [swagger-api/swagger-ui#2310]
It should be easy to publish this package on [Packagist](https://packagist.org/) for use with [Composer (PHP)](https://getcomposer.org/).

It'll help our use case in https://github.com/api-platform/core/issues/538#issuecomment-236628218

**Comment by teohhanhui** [comment]
We can contribute a `composer.json` if you agree to proceed with this.

**Comment by DerManoMann** [comment]
Is this really published? 
https://packagist.org/search/?q=swagger-api%2Fswagger-ui does't give me a match...

**Comment by teohhanhui** [comment]
We'll need @fehguy to publish it on Packagist.

**Comment by fehguy** [comment]
@teohhanhui is right, we have the composer file but have not been publishing to Packagist.

I've just enabled this, so please confirm that it's showing up as expected:

https://packagist.org/packages/swagger-api/swagger-ui

**Comment by DerManoMann** [comment]
:+1:  works for me
