### ISSUE TITLE
Swagger UI ignores protocol schemes for operations

### ISSUE THREAD

**Issue by arthurdm** [swagger-api/swagger-ui#2314]
From the spec, you can specific "schemes" at the operation level:

"The transfer protocol for the operation. Values MUST be from the list: "http", "https", "ws", "wss". The value overrides the Swagger Object schemes definition."

But the Swagger UI is not taking that into consideration.  For example, in the Swagger 2.0 snippet below the operation declares the http scheme, while the overall doc declares https.  When I hit the "Try it Out" button I was expecting the invocating to be http, but it was https instead.

The issue seems to be with swagger-ui.js, where it is only looking at the top-level schemes, and not at each operation's potential schemes. 

{
....
"/libertyswagger.mybluemix.net/airlines/": {
"get": {
"tags": [
"Airline Booking API"
],
"summary": "Retrieve all available airlines",
"description": "",
"operationId": "getAirlines",
"schemes": [
"http"
],
......
}

**Comment by webron** [comment]
Should be resolved in 3.X.
