### ISSUE TITLE
Conditionally prevent URL-hash navigation and history clobbering

### ISSUE THREAD

**Issue by alexander-bauer** [swagger-api/swagger-ui#2321]
I am using Swagger UI within another application, which depends on hash navigation to function. There is no way to prevent the call to `$.bbq.pushState`, which happens [several times](https://github.com/swagger-api/swagger-ui/search?utf8=%E2%9C%93&q=%24.bbq.pushState&type=Code) within the codebase. This clobbers the URL hash used by my application, and does not appear to be necessary for the basic functionality of the UI -- only for history and page bookmarks.

I was able to prevent this by crawling the DOM and changing all anchor `href`s to the current hash, and by setting `$.bbq.pushState = function() {}`. This is working for me because Swagger UI is the only thing making use of the JQuery BBQ library, but is nonetheless an awful hack.

An option like `hashNavigation` that could be set to false when initializing the `SwaggerUi` object would be very helpful in my case.

I am using Swagger UI version 2.1.4.

**Comment by fehguy** [comment]
Yes, I believe this should be made a configuration.

**Comment by hitman001** [comment]
+1

**Comment by webron** [comment]
No longer relevant with the new UI.

**Comment by nkorai** [comment]
Is this no longer relevant with the new UI? How so? I'm using v3.4.0 and it's still an issue for me as it changes the URL hashes. Granted I am using the dist version.

**Comment by jkcreative-web** [comment]
Hi, I know it's an old thread but since I just started learning more about how to use SwaggerUI, I came across the same issue as OP because I had the property "deepLinking: true", which I thought was for something different. When I removed this the plugin stopped changing the URL hash. Hope it's useful to someone.
