### ISSUE TITLE
Uploading files and JSON in same request: undefined type

### ISSUE THREAD

**Issue by jtorres-viavansi** [swagger-api/swagger-ui#2322]
Good day, I'm getting an error with a method that uses fileupload and JSON objects in same request. According to the official documentation of jersey, you can do that like that (https://jersey.java.net/apidocs/latest/jersey/index.html):

     @POST
     @Consumes(MediaType.MULTIPART_FORM_DATA_TYPE)
     public String postForm(
             @DefaultValue("true") @FormDataParam("enabled") boolean enabled,
             @FormDataParam("data") FileData bean,
             @FormDataParam("file") InputStream file,
             @FormDataParam("file") FormDataContentDisposition fileDisposition) {
         ...
     }

I've defined my method as follows:

    @POST
    @Path("/document")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "Verifies the signature in the passed document",
        notes = "Verifies the signature in the passed document",
        response = VerifierDocumentResponseDTO.class)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "ResponseVerifierDocumentDTO with verification result", response = VerifierDocumentResponseDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = VerifierDocumentResponseDTO.class),
        @ApiResponse(code = 403, message = "Forbidden", response = VerifierDocumentResponseDTO.class),
        @ApiResponse(code = 500, message = "Internal server error", response = VerifierDocumentResponseDTO.class)
    })
    public VerifierDocumentResponseDTO verifyDocument(
            @ApiParam(value = "Authentication string", required = true) @HeaderParam("Authorization") String authString,
            @ApiParam(value = "VerificationRequestDTO object", required = true) @FormDataParam("verificationRequestDTO") VerificationRequestDTO verificationRequestDTO,
            @ApiParam(value = "Original document to verify", required = true) @FormDataParam("originalDocument") InputStream originalDocument,
            @ApiParam(value = "Signed document", required = true) @FormDataParam("signedDocument") InputStream signedDocument) {

The parameter **verificationRequestDTO** is marked as undefined in swagger.json and swagger-ui:
![](http://descargas.viavansi.com/swagger-ui.png)

Any help will be apreciated. Thanks a lot.

**Comment by fehguy** [comment]
I believe you should open this in swagger-core.  To be clear though, the `formData` may only be a primitive type, not JSON.  This is changing in the 3.0 spec but for now, that's how it is.

**Comment by jtorres-viavansi** [comment]
Ok since it's changing in the 3.0 spec, I suposse I don't need to open this issue in swagger-core. Thanks for your help.
