### ISSUE TITLE
documenting data type constraints 

### ISSUE THREAD

**Issue by varunsingh9** [swagger-api/swagger-ui#2323]
Hi ,
I am using swagger with my sails application. Wanted to know if we can document data type constraints like 
1)length ,required etc.
```
Name:{
Type: 'string(50)’,
Required: true,
Unique: true
}
```
2)	cross field constraints like if gender is male then salutation should be Mr.
```
Gender:{
Type:'string’,
Enum: [‘M’, ‘F’]
}

Salutation{
Type: ‘string’,
Enum: [‘Mr’, ‘Ms’]
}
```
Using npm modules: sails-swagger & swagger-ui

**Comment by fehguy** [comment]
yes but you need to use the JSON schema draft 4 syntax.  Take a look at http://editor.swagger.io for an interactive way to validate your definitions.

**Comment by varunsingh9** [comment]
Hi ,

but how to get the that format . would that be a manual process or is there some parameters /way to automate it .

**Comment by fehguy** [comment]
there are a zillion resources on how to automatically generate the definitions.  Please start out at http://swagger.io and look at the tooling section.
