### ISSUE TITLE
Swagger-UI should ignore required properties for the PATCH method

### ISSUE THREAD

**Issue by gbking** [swagger-api/swagger-ui#2327]
The PATCH method is used to update partial resources and I can not think of any case where a property should be required for a patch. Yet, when I set a property as required, it will show up as required and at least Swagger editor will not let me send the request unless I set the property. In the UI it will, but it still mistakenly displays it as required.
This becomes an issue when defining a definition that is used for multiple types of request methods. For example when using one definition for a POST, PUT and PATCH method. Especially when this definition is very long, it seems stupid to have to copy-paste it just so that the required properties show up as optional in the PATCH method.

I am experiencing this issue in version 2.1.4.
I am not attaching a swagger file because this issue is easy to replicate in the Swagger editor.

**Comment by mehdy** [comment]
any news on this?

**Comment by webron** [comment]
Hmm, kinda missed the original ticket but... no - the behavior will not change.
It's up to you when you describe the API to describe whether something is required or not. If you feel that for PATCH something is not required, just don't mark it as such. There's really nothing in the project to be done for this.

**Comment by mehdy** [comment]
I agree. the point is that I have a definition which requires some attributes in POST method and doesn't require anything in PATCH method. is there any way I could use the same definition and just change the required attributes?

**Comment by webron** [comment]
Well, that's the wonder that's called JSON Schema - it doesn't offer an elegant solution for it. There are ways to maybe make it _slightly_ less painful, but at the end of the day, you'd still need two separate definitions.
