### ISSUE TITLE
Required boolean parameters have to be set to true

### ISSUE THREAD

**Issue by gbking** [swagger-api/swagger-ui#2328]
Swagger will mistakenly detect a required boolean parameter to not be set when its value is set to "false" and therefore not allow to send the request. This should not be the case since "false" should also be a valid value for a boolean parameter. Just because a boolean parameter is required to send the request doesn't mean that it has to be set to "true".

I am experiencing this issue in version 2.1.4.
I am not attaching a swagger file, because this issue is easy to replicate in the Swagger editor.

**Comment by fehguy** [comment]
Are you talking about swagger-ui or swagger-editor?

**Comment by gbking** [comment]
Sorry, I though that I also saw this behaviour in the UI, but it is indeed an editor-issue only. I have created a new issue in the editor repository and I'm closing this one.
