### ISSUE TITLE
DISCUSS: Any interest in seeing a typescript angular2 swagger Ui?

### ISSUE THREAD

**Issue by DavidParks8** [swagger-api/swagger-ui#2329]
Please discuss the pros and cons of moving the swagger ui to more modern frameworks.

**Comment by fehguy** [comment]
It's in progress and will be pushed here in 4-8 weeks.  Lots to do in order to make this jump, but it's imminent.

**Comment by wpitallo** [comment]
Any updates on this?

**Comment by siddamreddy** [comment]
Does it supports typescript and angular2 in swagger Ui? If yes, please provide me samples of swagger-Ui docs.

**Comment by ali-habibzadeh** [comment]
2018 and still nothing

**Comment by fehguy** [comment]
@ali-habibzadeh bro it's been updated to react in 3.x.  Pull and enjoy
