### ISSUE TITLE
Multiple SwaggerUI + OAuth2 = index.js:24 Uncaught TypeError: Cannot read property 'api' of undefined

### ISSUE THREAD

**Issue by Gobliins** [swagger-api/swagger-ui#2330]
[sessions-v1.txt](https://github.com/swagger-api/swagger-ui/files/424272/sessions-v1.txt)
[monitoring-v1.txt](https://github.com/swagger-api/swagger-ui/files/424273/monitoring-v1.txt)
[index.txt](https://github.com/swagger-api/swagger-ui/files/424274/index.txt)

See also: https://stackoverflow.com/questions/38971725/swagger-ui-oauth-index-js24-uncaught-typeerror-cannot-read-property-api

Version: SwaggerUI 2.2

first of all i am using a bit modified version of the standard html/js code offered from swagger-ui.

Changes are rather simple, instead of using only a single SwaggerUI element like:

```
window.swaggerUi = new SwaggerUi({
    ....

window.swaggerUi.load();
```

we  iterate over them and create lots of swaggerUI elements:

```
function addSwaggerUI(url, dom_id, host){
        window[dom_id] = new SwaggerUi({
        ....

window[domId].load();
```

this is our iteration:

```
var services = [{SERVICE_SPECS}];
  var doc_container = document.getElementById('service-doc-container');
  var index = 0;
  services.forEach(function(serviceSpec) {
    var swaggerNode = document.createElement('div');
    swaggerNode.id = "swagger-ui-container-" + index;
    swaggerNode.className = "swagger-ui-wrap";

    var messageNode = document.createElement('div');
    messageNode.id = "message-bar-" + index;
    messageNode.className = "swagger-ui-wrap";

    doc_container.appendChild(swaggerNode);
    doc_container.appendChild(messageNode);
    log("adding service documentation for " + serviceSpec);
    addServiceDocumentation(serviceSpec, swaggerNode.id, "{SERVICE_HOST}");
    index++;
  });
```

This worked quiet well until we started using securityDefinitions oAuth:

```
"securityDefinitions": {
    "OauthSecurity": {
        "type": "oauth2",
        "authorizationUrl": "http://localhost/oauth/dialog",
        "flow": "implicit",
        "scopes":{  
            "write:sessions":"kill sessions",
            "read:sessions":"get sessions"
        }
    }
```

Now i get on each swaggerUI this error:

```
index.js:24 Uncaught TypeError: Cannot read property 'api' of undefined
```

Original swaggercode:https://github.com/swagger-api/swagger-ui/tree/master/dist see index.html

Can someone help to fix this?

**Comment by webron** [comment]
We'd need at least two specs that you use by minimum the reproduce the issue.

**Comment by Gobliins** [comment]
Hi, I have added two specs (json) (sessions is the one with oauth) and the index.html (i uploaded everything as .txt since the other types were not supported to attach.

**Comment by Gobliins** [comment]
any news?

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
