### ISSUE TITLE
Can anyone provide me Demo example of Spring MVC Oauth 2.0 with swagger2

### ISSUE THREAD

**Issue by bhargavkawale** [swagger-api/swagger-ui#2331]
I was already try but authorize button was not clickable
![screenshot from 2016-08-17 15 13 22](https://cloud.githubusercontent.com/assets/20911300/17732021/982620a6-648d-11e6-91a4-a8bbc1ba9940.png)

i was use following dependency

	<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.4.0</version>
		</dependency>
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger-ui</artifactId>
		    <version>2.4.0</version>
		</dependency>

following is my swagger config source:

`	public static final String securitySchemaOAuth2 = "oauth2";
    public static final String authorizationScopeGlobal = "global";
    public static final String authorizationScopeGlobalDesc ="accessEverything";
	
	@Bean
	public Docket api() {
		/*return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
				.paths(internalPaths()).build().securitySchemes(Arrays.asList(authorizationCodeFlow()))
				.securityContexts(Arrays.asList(securityContext()));*/
		 return new Docket(DocumentationType.SWAGGER_2)
	                .select().paths(internalPaths()).build()
	                .securitySchemes(newArrayList(securitySchema()))
	                .securityContexts(newArrayList(securityContext())).enable(true);
	}
	
	private Predicate<String> internalPaths() {
        return or(
                regex("/Common/.*"),
                regex("/Property/.*")
        );
    }

    private OAuth securitySchema() {
        AuthorizationScope authorizationScope = new AuthorizationScope(authorizationScopeGlobal, authorizationScopeGlobal);
        LoginEndpoint loginEndpoint = new LoginEndpoint("http://localhost:8082/oauth/authorize");
        GrantType grantType = new ImplicitGrant(loginEndpoint, "access_token");
        return new OAuth(securitySchemaOAuth2, newArrayList(authorizationScope), newArrayList(grantType));
    }

    private SecurityContext securityContext() {
        return SecurityContext.builder()
                .securityReferences(defaultAuth())
                .forPaths(internalPaths())
                .build();
    }

    private List<SecurityReference> defaultAuth() {
        AuthorizationScope authorizationScope
                = new AuthorizationScope(authorizationScopeGlobal, authorizationScopeGlobalDesc);
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0] = authorizationScope;
        return newArrayList(
                new SecurityReference(securitySchemaOAuth2, authorizationScopes));
    }
	
	`

**Comment by webron** [comment]
We cannot provide support for swagger-ui when packaged through third party tools, in this case, Springfox. I have no idea which version of swagger-ui is provided there.

Try using the current master version of swagger-ui. If it works, you'd need to direct your question to Springfox. If it doesn't, you'd need to provide us with the spec that's being loaded to swagger-ui.
