### ISSUE TITLE
Automate authorization

### ISSUE THREAD

**Issue by abonec** [swagger-api/swagger-ui#2332]
Is it possible to add automation to authorization from one of the api method? I use bearer api authorization method and need to fill 3 fields after authorization and all fields will reset when I reload page.

It will be much worse when api would reset token after each request.

 It will be nice if swagger would do this for me.

**Comment by webron** [comment]
Anything is possible with code, but that's something you'd need to write. Swagger/OpenAPI doesn't describe a flow between operation calls, so it can't be automated based on the spec alone.

**Comment by abonec** [comment]
I mean a simplest situation. I have one authorization entry point which return 3 headers that I use for access for all other apis as is. That is, there is a simple rule to map response headers to authorization headers but not any coding.

Problem is that is very hard to copy & paste each header by hand each time. It even harder because current version doesn't show response headers.

**Comment by webron** [comment]
And yet, this is something that is not and cannot be provided by the UI. Just because the headers are not displayed (due to a bug) doesn't mean the data is not available. But if you want to add support for it, you'd need to do that yourself.
