### ISSUE TITLE
Why aren't dependencies managed trough bower.json?

### ISSUE THREAD

**Issue by riichard** [swagger-api/swagger-ui#2336]
At the moment swagger-ui claims to be dependency free, but uses jquery as a dependency. 
I can understand you want to deliver swagger-ui pre-built in the dist folder. But all these third party libraries are also hard-coded into the lib folder, then copied to the dist folder in the build.

Dependencies are easier to manage trough a package manager like bower. 

May I change this behavior and integrate wiredep in the build process?
The package will then still be ready to use via the code in the dist folder, but offers more flexibility in it's dependencies and version management.

**Comment by fehguy** [comment]
we're switching to use webpack so please don't spend your time on this right now.

**Comment by luxflux** [comment]
@fehguy is there an issue where this process is tracked?
