### ISSUE TITLE
Stuck at fetching resource list: http://localhost:9000/docs/swagger.json; Please wait.

### ISSUE THREAD

**Issue by SangeetaGulia** [swagger-api/swagger-ui#2337]
I am a newbie to swagger and i am stuck after doing the following things on an error: 
I am using the following dependencies: 
- "com.iheart" %% "play-swagger" % "0.2.1-PLAY2.5",
- "org.webjars" % "swagger-ui" % "2.1.4"

Following are the routes:
![image](https://cloud.githubusercontent.com/assets/17196401/17799358/c2f7931c-65f7-11e6-921a-661db9644532.png)

Following is the expected response type:
case class Output(response: JsValue)

This is the screenshot of where i am getting struck:

![image](https://cloud.githubusercontent.com/assets/17196401/17799276/f264f456-65f6-11e6-9083-945cb5e5e2a8.png)

This is what i get in the auto generated json file(where it gets struck with error : fetching resource list):

{"paths":{"/assets/{file}":{"get":{"tags":["routes"],"parameters":[{"name":"path","type":"string","required":true,"in":"query"},{"name":"file","type":"asset","required":true,"in":"path"}]}},"/docs/swagger.json":{"get":{"tags":["routes"],"summary":"swagger definition","description":"for swagger UI to consume"}},"/client/view":{"get":{"tags":["routes"],"responses":{"200":{"description":"success","schema":{"$ref":"#/definitions/models.Output"}}}}}},"definitions":{"models.Output":{"properties":{"response":{"type":"play.api.libs.json.jsvalue","required":true}},"required":["response"]}},"tags":[{"name":"routes"}]}

and this is my default swagger.json file(which i have created) : 
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Weather API",
    "description": "A sample API that uses a Mashape weather API as an example to demonstrate features in the swagger-2.0 specification",
    "termsOfService": "http://helloreverb.com/terms/",
    "contact": {
      "name": "Tom Johnson",
      "email": "tomjohnson1492@gmail.com",
      "url": "localhost:9000"
    },
    "license": {
      "name": "MIT",
      "url": "http://opensource.org/licenses/MIT"
    }
  },
  "host": "localhost:9000",
  "basePath" : "localhost:9000",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/text"
  ]
}

I am refering to link : https://github.com/iheartradio/play-swagger

**Comment by vincent-zurczak** [comment]
Hi! It seems your swagger.json file is incomplete.
It should have a "definitions" property defining the types used by your REST operations.

**Comment by SangeetaGulia** [comment]
Actually i am using iheartradio/play-swagger : (https://github.com/iheartradio/play-swagger)
It only ask for minimum swagger.json file: 
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Weather API",
    "description": "A sample API that uses a Mashape weather API as an example to demonstrate features in the swagger-2.0 specification",
    "termsOfService": "http://helloreverb.com/terms/",
    "contact": {
      "name": "Tom Johnson",
      "email": "tomjohnson1492@gmail.com",
      "url": "localhost:9000"
    },
    "license": {
      "name": "MIT",
      "url": "http://opensource.org/licenses/MIT"
    }
  },
  "host": "localhost:9000",
  "basePath": "/docs",
  "schemes": [
    "https",
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ]
}

and automatically generates the paths and definitions using the routes file.
Following is the demo project which i have created using the same:

https://github.com/SangeetaGulia/testSwagger 

in brief: 
These are the routes: # Routes
![image](https://cloud.githubusercontent.com/assets/17196401/17831724/826f732e-670e-11e6-9685-578e9158bd82.png)

and these are the paths and definitions generated for my routes : 
{
"paths":{
"/":{
	"get":{
	"tags":["routes"],
	"responses":{
		"200":{
			"description":"success",
			"schema":{
				"$ref":"#/definitions/models.Test"
					}
				}
			}
		}
	},
"/docs/swagger.json":{
	"get":{
		"tags":["routes"],
		"summary":"swagger definition",
		"description":"for swagger UI to consume"
		}
	}
},
"definitions":{
	"models.Test":{
		"properties":{
			"name":{"type":"string"}
			},
		"required":["name"]
		}
	},
	"tags":[{"name":"routes"}]
}

It contains definitions, but still i am getting the same error. Am i missing on something??
Is there any other way to auto generate the spec from my routes.??

**Comment by webron** [comment]
Please try the latest version.

**Comment by Ankele** [comment]
我也遇到了同样的问题，楼主解决了么？
