### ISSUE TITLE
no rendering when using 'in: body' with an empty supportedSubmitMethods

### ISSUE THREAD

**Issue by CelesteGH** [swagger-api/swagger-ui#2338]
swagger-ui version 2.2.0
[API_WSA_0.0.1.yaml.txt](https://github.com/swagger-api/swagger-ui/files/426654/API_WSA_0.0.1.yaml.txt)

We want to deactivate the try button but cant because nothing is rendered when using in:body.

**Comment by webron** [comment]
No longer an issue with the new UI.
