### ISSUE TITLE
JSON-Repsonse does not get formated when thrown as WebApplicationException

### ISSUE THREAD

**Issue by Baumeln** [swagger-api/swagger-ui#2345]
Hello,

I am using swagger-ui 2.1.4 and I ran into a smal problem.

``` json
"Custom response message" : {
            "type" : "object",
            "required" : ["code"],
            "properties" : {
                "code" : {
                    "type" : "integer",
                    "format" : "int32",
                    "description" : "The code is type of http status code",
                    "readOnly" : true
                },
                "message" : {
                    "type" : "string",
                    "description" : "The message can hold specific information about the response",
                    "readOnly" : true
                }
            }
        },
```

When I just want to respond with a smal piece of text, I return an instance of the above object, wrapped into a Jersey-Response. This works perfectly so far. I am now in an situation where I cannot return the response, so I throw it wrapped by an WebApplicationException. It appears as expected in the "Response Body"-Field but does not gets formated. Everythink just stands in one line. Like this:

``` json
{"code":404,"message":"A container with identfier '5' does not exist"}
```

Any idea if it could by my fault or a bug?

Best regards
Baumeln

**Comment by webron** [comment]
Is this still an issue for you?
