### ISSUE TITLE
Add specific header settable by the user

### ISSUE THREAD

**Issue by ybarbaria** [swagger-api/swagger-ui#2349]
Hello, 

I want to add two specific header for some request. I would like that the user can set the value and when he click on "try" the headers are added to the ajax request. 

Have you any solution?  I have make an web api asp.net core and I use this version of swasbuckle : "Swashbuckle": "6.0.0-beta902"

Thx

**Comment by webron** [comment]
This is a question for Swashbuckle. Header parameters are part of the spec and swagger-ui will show them and allow users to input value, if they are provided in the spec.
