### ISSUE TITLE
Make customization easier

### ISSUE THREAD

**Issue by jacobweber** [swagger-api/swagger-ui#2355]
Hi. Really appreciate the work you've done on this project. However, one issue I always run into is that it's very difficult to customize.

For example, I want to reuse the API list, but present a different header and different inputs for adding authorizations, compared to the Pet Store example. But I've run into several problems:
- The core SwaggerUI code references specific UI elements, like #header.
- For some reason the call to hljs, to update syntax highlighting, only happens if you call initOAuth. So if I don't want to use your OAuth UI, I don't get syntax highlighting.
- There's no clear separation between the CSS for the header, and the CSS for the API list. For example, styles for .swagger-ui-wrap, which surrounds the Pet Store header, are in the same files as styles for #resources, which is in the API list.

It would also be nice if the code for the API list were easier to customize, but to me that's secondary to separating out the header code.

I'm using version 2.2.2.

**Comment by webron** [comment]
Thank you for your input. The second point in your list sounds more like a bug.

We're working on a an update that will allow you for better and easier customization, but at the moment, no ETA.

**Comment by jacobweber** [comment]
Sounds good. I opened #2356 for the second point.

**Comment by arcxyz** [comment]
Any updates on this? 

I have something done on my local environment for an easier theme development. I've added a new folder inside `/src/main` called `themes` and move the `templates` and `less` folders into another folder called `default`. Something like this:

```
└── src
    └── main
        ├── html
        ├── javascript
        └── themes
            ├── default
            │   ├── less
            │   └── templates
            ├── awesome-theme-1
            │   ├── less
            │   └── templates
            └── awesome-theme-2
                ├── less
                └── templates
```

I also changed some gulp tasks to watch for handlebars file changes and compile them. I need to cleanup some project specific code and I'll send a PR with the changes.

**Comment by fehguy** [comment]
Hi, the problem with how this project is built is, customization is more "modification" than anything.  We're working on some major structural changes to make this easier, so I suggest sitting tight for those.

**Comment by jdoubleu** [comment]
Any updates on this?

I'd like to be able to create custom themes.

I appreciate your work and can't wait to see this feature.

**Comment by webron** [comment]
So yes, the new Swagger-UI does allow it to be done more easily, but it would take us some time to document the process. 

In the meantime, we invite you to explore the new sources.

**Comment by ostranme** [comment]
@jdoubleu Hope this helps - https://github.com/ostranme/swagger-ui-themes

**Comment by shockey** [comment]
Swagger-UI 3, along with our new customization documentation, should get you going with customizing the layout. See here: https://github.com/swagger-api/swagger-ui#customization.

Closing!
