### ISSUE TITLE
Syntax highlighting requires OAuth

### ISSUE THREAD

**Issue by jacobweber** [swagger-api/swagger-ui#2356]
Using swagger-ui 2.2.2, the call to hljs, to update syntax highlighting, only happens if you call initOAuth. So if I don't want to use your OAuth UI, I don't get syntax highlighting. This is a change from 2.1.x. It affects the "Model Schema" in the response and body-parameter definitions.

**Comment by webron** [comment]
Shouldn't be an issue in 3.X.

**Comment by jacobweber** [comment]
That's true, but only because there's no syntax highlighting at all in 3.x. 😀
