### ISSUE TITLE
use urldecode content in tags cause a problem that i can't expand the api dom

### ISSUE THREAD

**Issue by xuminwlt** [swagger-api/swagger-ui#2357]
When reporting a bug, please provide the following details:
- swagger-ui version 2.2.0
- a swagger file reproducing the issue

tags = /xxx or in chinese 宠物
GET  pet/1    getPet
I click the GET ,nothing happend，although the url changed to #!/xxxxxUSEGET
Is there caused by URLDecode or URLEncode problem?

**Comment by webron** [comment]
Possibly. Can you share a spec so we can test it?

**Comment by blackshadowwalker** [comment]
Here's  the reason:


##  Version-2.5.0 work's OK:
![qq 20161012164542](https://cloud.githubusercontent.com/assets/5380980/19303513/81419480-909b-11e6-83fe-f091f8feea88.png)

##  Version-2.6.0 can not expand api

**Comment by fehguy** [comment]
There is no 2.6.0 of swagger-ui

**Comment by dilipkrish** [comment]
This is a bundled swagger-ui that comes with Springfox. All it is is a webjar packaged version of the latest released swagger-ui distro. It is likely a bug in 2.2.5.
