### ISSUE TITLE
Support inline code examples

### ISSUE THREAD

**Issue by grokify** [swagger-api/swagger-ui#2364]
A nice feature of some API explorers is to have code examples available in addition to the form submission.

inContact has done a nice job of integrating this into Swagger UI below but it seems like they grafted this on themselves. When you click on the language code samples tabs in their implementation, a code sample appears.

It would be great to have something like this native to Swagger UI.

Swagger UI: https://developer.incontact.com/API/AgentAPI#/

<img width="626" alt="screen shot 2016-08-29 at 7 07 22 am" src="https://cloud.githubusercontent.com/assets/209872/18037462/4bfd52e8-6db7-11e6-826a-d46efe84b763.png">

**Comment by webron** [comment]
Closing as this is for now out of scope for us. We might be able to do it at some point, depending on changes to other projects, but until then, there's not much we can do.

**Comment by codestellar** [comment]
@grokify @webron This npm package will help:
[https://www.npmjs.com/package/swaggerui-snippets](https://www.npmjs.com/package/swaggerui-snippets)
