### ISSUE TITLE
Support for nested Objects in swagger-ui

### ISSUE THREAD

**Issue by viveksinhadot** [swagger-api/swagger-ui#2365]
Hi Team,
I have started using swagger hub for publishing APIs. I am facing some limitations while trying to add Objects in swagger Editor.

Example:
Object User: {
"name";
"id";            //required
"age";
"ratePlan";        //object
"appliances";     //array
}

Object RatePlan: {
"rateId";      //required
"startDate";     //required
"endDate";
}

I am facing two limitations when I use "Try It Out" on any API (PUT call), which uses "User" object:
1. It asks for adding "RatePlan.rateId" and "RatePlan.startDate" field. But because RatePlan is not a mandatory field in "User", I want users to use the API without ratePlan, but if they enter any ratePlan then they must put rateId and startDate fields.
2. If we don't enter any appliance, the array "appliances" gets set as [] in the API call generated, but ideally it should either be set to null or should not get serialised (like any primitive field). Setting value as empty array i.e. [] provides wrong information.

**Comment by webron** [comment]
Shouldn't be an issue in 3.X.
