### ISSUE TITLE
npm run build error following the swagger ui instructions

### ISSUE THREAD

**Issue by allen2005ca** [swagger-api/swagger-ui#2367]
swagger-ui@2.2.2 is the version.

[npm-debug.pdf](https://github.com/swagger-api/swagger-ui/files/445813/npm-debug.pdf)

Following this instruction below: 

Build

You can rebuild swagger-ui on your own to tweak it or just so you can say you did. To do so, follow these steps:

Windows Users: Please install Python before follow below guidelines for node-gyp rebuild to run.

npm install
npm run build
You should see the distribution under the dist folder. Open ./dist/index.html to launch Swagger UI in a browser

**Comment by heinrichj** [comment]
Seems to be the same issue as in #2348

**Comment by fehguy** [comment]
fixed by https://github.com/swagger-api/swagger-ui/pull/2416
