### ISSUE TITLE
Vulnerable jQuery version

### ISSUE THREAD

**Issue by zerg32** [swagger-api/swagger-ui#2368]
Currently swagger-ui uses jQuery 1.8 that has a security issue. 
Here is a jquery bug: http://bugs.jquery.com/ticket/11290

**Comment by vinay-g** [comment]
XSS Vulnerability - https://domstorm.skepticfx.com/modules?id=56b4dfde108b7c00007363ac

**Comment by webron** [comment]
3.X doesn't use jquery anymore.
