### ISSUE TITLE
allowMultiple - Different behavior swagger-ui & swagger-codegen

### ISSUE THREAD

**Issue by aperinot-orange** [swagger-api/swagger-ui#2370]
Since https://github.com/swagger-api/swagger-ui/issues/118 was added (The relation between  https://github.com/swagger-api/swagger-ui/issues/118 and this one is just a guess), there is now a different behavior between swagger-codegen & swaggger-ui (both in latest versions).

With a field spec like this (generated using @ApiParam with allowMultiple = true) :
`{
  "name" : "properties",
  "in" : "query",
  "description" : "format expected => properties=p1,p2",
  "required" : false,
  "type" : "array",
  "items" : {
	"type" : "string"
  },
  "collectionFormat" : "multi"
}`

On swagger-codegen, it is generating an API call "properties=p1,p2,p3" (exactly what I expect)
while in swagger-ui the API call is "properties=p1&properties=p2&properties=p3"

Maybe is there a new way to declare it in the swagger spec to get a "properties=p1,p2,p3" in swagger-codegen AND swagger-ui ?

I also tried to set the type to "string" instead of "array" to generate the correct thing in swagger-ui, but it's not working neither.

Also, the issue may be related to swagger-codegen only, but since they provide the behavior I expect, I posted here.

**Comment by fehguy** [comment]
I believe the behavior in swagger-ui is correct.  the `collectionFormat` is what tells the array serialization how to work, and `multi` does indeed have a repeating parameter name.  What you're seeing in codegen should really be `csv`, and is worth reporting as a bug there.
