### ISSUE TITLE
can't download file.

### ISSUE THREAD

**Issue by orbitboy007** [swagger-api/swagger-ui#2371]
I am new to swagger and require to download file but when i click on try out it only show header like
{
  "x-powered-by": "Express",
  "access-control-allow-origin": "*",
  "content-type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=utf-8",
  "content-disposition": "attachment; filename=\"all.xlsx\"",
  "content-length": "19",
  "etag": "W/\"13-901ea176\"",
  "date": "Wed, 31 Aug 2016 16:40:59 GMT",
  "connection": "keep-alive"
}

how can i actually download file using swagger??

**Comment by fehguy** [comment]
Please look at #2404 which can be tested in this commit:

https://github.com/swagger-api/swagger-ui/tree/4bdaeba797224bde922f3cefe55a6807428437a8

**Comment by fehguy** [comment]
Fixed by https://github.com/swagger-api/swagger-ui/commit/656808b20cffcca4f6daff1741c4685d70be5757
