### ISSUE TITLE
if one of the tags has forward slash in it, details of method wont expand when clicked.

### ISSUE THREAD

**Issue by sreeshas** [swagger-api/swagger-ui#2372]
- swagger-ui version 2.2.2, 2.2.1
- a swagger file reproducing the issue
  [swagger-issue.txt](https://github.com/swagger-api/swagger-ui/files/448818/swagger-issue.txt)

This issue is reproducible in both 2.2.2. and 2.2.1. 
It cannot be reproduced in 2.1.4 and works as expected. This looks like regression.

I was able to resolve it by using the fix mentioned here.
https://github.com/swagger-api/swagger-ui/issues/1485 

![browser console screenshot](https://cloud.githubusercontent.com/assets/553879/18155352/e2de61fa-6fc1-11e6-8c97-4385e1139207.png)

**Comment by morris** [comment]
A similar issue arises when using umlauts in tags

**Comment by dkiser** [comment]
Just confirmed this problem does indeed exist on `@version v2.2.6`.  The patch from #1485 fixes for me as well.

**Comment by dkiser** [comment]
Any updates on a mainline fix for this?

**Comment by webron** [comment]
No, but PRs are welcome.

**Comment by sreeshas** [comment]
@webron Is #1485 the correct fix for this issue?  If it is, i can submit a PR which is essentially this commit https://github.com/sreeshas/swagger-ui/commit/4e2295dda89c58e5ab1ba149f114cae865185342

**Comment by webron** [comment]
@sreeshas based on @fehguy's comments on #1485, I would assume so.

**Comment by sreeshas** [comment]
Added a PR  https://github.com/swagger-api/swagger-ui/pull/2558

**Comment by fehguy** [comment]
Merged
