### ISSUE TITLE
Authorization header displayed in Curl but not in Request Headers

### ISSUE THREAD

**Issue by adrienpetel** [swagger-api/swagger-ui#2375]
Hi, 

I'm currently using springfox-swagger2  v2.5 and springfox-swagger-ui v2.5 with Spring MVC
to generate documentation for my REST APi
I'm using an ApiKey which is send in "Authorization" header.  

This header appears correctly in Curl : 

`curl -X GET --header 'Accept: application/json' --header 'Authorization: apiKey' 'http://localhost:8080/spring-java-swagger/search'`

but not in requestHeaders which just display 

```
{
  "Accept": "application/json"
}
```

Is there a way to make 'Authorization' header appears in both? 

I've set up a demo repository to demonstrate the issue at https://github.com/adrienpetel/springfox-demos.git in spring-java-swagger subproject.

**Comment by aabadia** [comment]
I have the same problem. Any solution?

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
