### ISSUE TITLE
Swagger ui ignores methods with same path

### ISSUE THREAD

**Issue by rainoko** [swagger-api/swagger-ui#2376]
- problem occurred since 2.1.x
- in version 2.0.X if same path but different content types were used, swagger ui displayed multiple services.

Relevant part of json:
[relevant.txt](https://github.com/swagger-api/swagger-ui/files/450096/relevant.txt)

We use content type for api versioning so we have to support multiple path with different parameter examples and models.
v2.0.24 worked nicely for us, because we can describa old pethods as deprecated. But v2.0.24 has many other bugs which are resolved in later versions.

**Comment by webron** [comment]
This is a really old version of the spec, we don't support that anymore.
