### ISSUE TITLE
UI is not able to load yaml specification

### ISSUE THREAD

**Issue by asingla82** [swagger-api/swagger-ui#2377]
browse console reports the following stack trace while loading yaml specs. 

`index.js:24 Uncaught ReferenceError: jsyaml is not definedcreateJSONSample @ index.js:24render @ index.js:24addOperation @ index.js:24render @ index.js:24addResource @ index.js:24render @ index.js:24render @ index.js:24options.success @ index.js:24SwaggerClient.buildFromSpec @ operation.js:528Resolver.finish @ index.js:320(anonymous function) @ index.js:144Resolver.resolve @ index.js:223response @ operation.js:264responseInterceptor @ operation.js:802obj.on.response @ operation.js:817(anonymous function) @ operation.js:1057Request.callback @ index.js:24(anonymous function) @ index.js:24Emitter.emit @ index.js:24xhr.onreadystatechange @ index.js:24`

I debug and the issue is the index.html does not import the js-yaml.min.js. I think this  [commit](https://github.com/swagger-api/swagger-ui/commit/515f1420268e579445ebb91df47ba941e5cce2b3#diff-e1175d4e9a518448975c60a1d560a597) broke the code.

For the same reason, petsotre.swagger.io breaks for yaml specs.

**Comment by fehguy** [comment]
@bodnia is this expected?

**Comment by bodnia** [comment]
@asingla82 could you please confirm if http://petstore.swagger.io/?url=http://petstore.swagger.io/v2/swagger.yaml doesn't work for you and which browser you use?

**Comment by asingla82** [comment]
I use chrome and this link is working. Although it does not work for the specs I have. I also downloaded the 2.2.2 version on my local and have the same issue. But If I fix the index.html for the missing javascript file as I mentioned above, it stats working.

**Comment by asingla82** [comment]
Got it. Issue is the examples in the specs. I had it like below.
examples:
    application/json: |
         {
            "code": 500,
            "message": "Internal server error"
         }

Removed the pipe (|) and it works now.
