### ISSUE TITLE
Get default host name from textfield

### ISSUE THREAD

**Issue by heinrichj** [swagger-api/swagger-ui#2388]
- Swagger-UI version: 2.2.2

If I have a swagger.json file which does not contain a host field, swagger-ui will fire requests for the "try it out" buttons against localhost. The reason is, that the ui takes localhost as default in case the host field has not been specified in the swagger file.
`  this.host = parent.host || 'localhost';`

The behaviour I'd expect however would be that the ui uses the host of the path where the swagger.json file resides.

In our swagger specification files we do not set the host field. Depending on the stage where we deploy the services the hostname changes and we don't wan't to generate a new server stub and do the manual adjustments for each stage we deploy to, because that is an automated process.

I'd expect the server to reside on the same host as the swagger.json file and only if that is not the case I'd expect the host property to be set.

**Comment by fehguy** [comment]
What you're describing is the expected behavior.  This must be a regression.

**Comment by heinrichj** [comment]
Hello fehguy,

thank you for your response.
To me it looks like it is not a swagger-ui issue rather than that it seems that the code that is responsible for this behaviour is in swagger-js projectn which is just included in the dist of swagger-ui as a dependency.
Can you confirm that? If so should we close this issue here and recreate it in swagger-js or can you transfer this issue between projects?

**Comment by fehguy** [comment]
@heinrichj that is correct.  Swagger-JS has all the smarts for doing this.  If you want to open a ticket in that repo, I'll close this one.  Just ref it back to here?

**Comment by heinrichj** [comment]
Closing this issue due a new issue in the correct repo https://github.com/swagger-api/swagger-js/issues/849
