### ISSUE TITLE
Optional query parameters display value as "undefined"

### ISSUE THREAD

**Issue by rwfaulkner** [swagger-api/swagger-ui#2389]
For a Get method optional query parameters display value as "undefined"
This causes the query parameter to default to "undefined" for the "try it out" button. User must blank out the value in order to not send it with the "try it out" button. Note in version 2.1.4 value parameter was blank for optional parameters.

swagger-ui version: 2.2.3

See attached swagger-ui.pdf for display issue and swagger_json.pdf for query parameter definition.
[Swagger_UI.pdf](https://github.com/swagger-api/swagger-ui/files/459616/Swagger_UI.pdf)
[swagger_json.pdf](https://github.com/swagger-api/swagger-ui/files/459617/swagger_json.pdf)

**Comment by fehguy** [comment]
Please try the latest master and report back?

**Comment by rwfaulkner** [comment]
Looks to be fixed on latest Master
