### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by sunshineo** [swagger-api/swagger-ui#2390]
When reporting a bug, please provide the following details:
- swagger-ui version
  2.2.0 above
- a swagger file reproducing the issue

It's about your documentation.
You changed the UI. Removed the api_key box. (Personally I feel that is a wrong decision. The new pop up window looks so ugly and hard to use but that is my personal opinion and a separate topic.)
Now your documentation about adding api_key to header is not working any more
https://github.com/swagger-api/swagger-ui#header-parameters

**Comment by webron** [comment]
No longer relevant.
