### ISSUE TITLE
No Authorize button

### ISSUE THREAD

**Issue by sunshineo** [swagger-api/swagger-ui#2391]
When reporting a bug, please provide the following details:
- swagger-ui version
latest master
- a swagger file reproducing the issue

It's about the UI.

![swagger](https://cloud.githubusercontent.com/assets/1072766/18333793/249e18e6-7527-11e6-8695-2cad9dd80774.jpg)

**Comment by fehguy** [comment]
As of 2.2.x, the Auth is rendered dynamically.  Please see the [release notes](https://github.com/swagger-api/swagger-ui/releases).

But... please note that the index.html can be modified on your own, and you can add the auth button in.  The authorization can occur exactly like it did before with the current library release.

**Comment by sunshineo** [comment]
@fehguy I did not see anything about the Auth button rendered dynamically in the release notes. Nothing explains how is it rendered dynamically. My service require api-key in the header, how did swagger-ui decide that my service does not need the Auth button? Why is the UI even bother trying to render that dynamically?

**Comment by sunshineo** [comment]
@fehguy Can you re-open this ticket?

**Comment by fehguy** [comment]
Please read the release notes:

https://github.com/swagger-api/swagger-ui/releases/tag/v2.2.1
## New features

* Integrated authentication! Now your basic auth, apiKey, OAuth 2.0 Implicit security definitions are automatically rendered in the UI #1923, #1922, #1889


Add the securityDefinition as described by the specification and it'll render automatically.

Or use the old index.html and jam it in on your own.

**Comment by sunshineo** [comment]
@fehguy Thank you for the links. I think I finally understand it now. I probably need to specify on the server side what kind of auth method am I using and then the UI will automatically show the components. Thank you!

**Comment by fehguy** [comment]
exactly.  Please open any issues you may run into, but this should make things much easier for everyone.

**Comment by sunshineo** [comment]
@fehguy After couple hours of research, failed to specify securityDefinition because I'm using dropwizard and the sample project https://github.com/swagger-api/swagger-samples/tree/master/java/java-dropwizard does not have it. I checked the annotations https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X but found nothing either.
