### ISSUE TITLE
Can i convert my rest api into Open Api specidications

### ISSUE THREAD

**Issue by manishkvaish** [swagger-api/swagger-ui#2393]
I have a 100s of rest apis, one with its json code present at: 

https://www.biodiversitycatalogue.org/services/98.json

Please tell me, is there a way to convert my json to follow Open API specifications, so that i can generate Swagger UI for that.

I saw Swagger Editor and SwaggerCodegen, but i do not know , how to use these exactly with my json file.

could anyone please go to the above url to check my json and suggest me some solution.

Thanks

**Comment by heinrichj** [comment]
For my understanding you already have RESTservices for which you additionally want to generate an OpenAPI conform swagger.json file which you can open in swagger-ui.

In case you are using spring-mvc I think you could use https://springfox.github.io/springfox/
As far as I know this will generate a swagger.json file from your existent spring mvc implementation which you can enrich with swagger annotations.

**Comment by manishkvaish** [comment]
Thanks for the reply,
actually  i am not using Spring MVC, is there any other way possible .
 i am following https://github.com/zircote/swagger-php
as i am new to Swagger,and do not know exactly about all its working, so if you can suggest ,can i get help from this library?

**Comment by fehguy** [comment]
you'll have to convert your definition structure--whatever it is--into swagger format.
