### ISSUE TITLE
Model - Byte converted into string

### ISSUE THREAD

**Issue by jhayotte** [swagger-api/swagger-ui#2398]
**swagger-ui version**: "Swashbuckle": "6.0.0-beta902"

See below the model generated in swagger ui
![image](https://cloud.githubusercontent.com/assets/7420027/18410116/12ef42c6-7759-11e6-9256-aada949c42e1.png)
And see below the model where there is a parameter in byte
![image](https://cloud.githubusercontent.com/assets/7420027/18410120/464e7cae-7759-11e6-9e96-9c2a9d3f0836.png)
And this parameter expects string in the model generated by Swagger while it should be a byte.

Then if we trust the model generated by swagger we get a JSON incorrect format error.

**Comment by fehguy** [comment]
Are you using Swashbuckle?  I'm guessing, and if so, the issue is on that project.
