### ISSUE TITLE
Stuck at fetching...

### ISSUE THREAD

**Issue by angeloh** [swagger-api/swagger-ui#24]
After I executed 'middleman', the UI works fine. However, if I give my local resources.json (http://localhost:9000/resources.json), it stops at 'Fetching _register...' , where register is one of controller.

If I just paste these two links to browser, it returns correct JSON string.
http://localhost:9000/resources.json
http://localhost:9000/register.json

What am I missing on this UI library?

**Comment by SangeetaGulia** [comment]
Hi, 
I am  facing similar problem. Stuck while fetching.

The json file is generated but on console, i am getting an error: 
Uncaught TypeError: Cannot read property 'definitions' of null.............. pointing to
schema-markup.js file           --->  if (schema.$ref) {

Also when i tried to use generated json file in swagger editor. I can see errors :
Missing required property: responses .... here i am using auto generated json file.
Refering to link : https://github.com/iheartradio/play-swagger

Any help would be appreciated.

**Comment by webron** [comment]
Well, opening a new ticket would help, and also providing the spec(s) that make you experience the issue(s). We can't do much without the specs.
