### ISSUE TITLE
OPTIONS method is missing

### ISSUE THREAD

**Issue by dgofman** [swagger-api/swagger-ui#2400]
https://github.com/swagger-api/swagger-ui/blob/6f8599d1a58b8abbd2bd7a7eb0be5d2a866c2e26/src/main/html/index.html#L54

"options" is missing in array.

Now I have manually patch files:

vi swagger-ui.js line 4758 replace

if (this.method === 'post' || this.method === 'put' || this.method === 'patch' ||
to
if (this.method === 'post' || this.method === 'put' || this.method === 'patch' || this.method === 'options' ||

vi swagger-ui.js add lines starts from 24420

/**
 * OPTIONS `url` with optional `data` and callback `fn(res)`.
 *
 * @param {String} url
 * @param {Mixed|Function} data or fn
 * @param {Function} fn
 * @return {Request}
 * @api public
 */

request.options = function(url, data, fn){
  var req = request('OPTIONS', url);
  if ('function' == typeof data) fn = data, data = null;
  if (data) req.send(data);
  if (fn) req.end(fn);
  return req;
};

**Comment by webron** [comment]
It's missing on purpose. The idea behind that line is that it's configuration and can be modified based on your own needs. If you need to add `options`, just add it in your local copy.

**Comment by LucasAmorimSilva** [comment]
@webron , How can I set my Django project to allow OPTIONS melhod??? I tried so hard to use django-cors-headers, but, so far, no success. My frontend is in Angular 1.

Thank you!
