### ISSUE TITLE
How to Remove leading and trailing spaces in header/query param values in swagger ui

### ISSUE THREAD

**Issue by venkataharishbillapati** [swagger-api/swagger-ui#2401]
How can we remove extra trailing/leading spaces in swagger ui for header values or query parameter values? @fehguy

**Comment by webron** [comment]
what do you mean?

**Comment by venkataharishbillapati** [comment]
![swagger e](https://cloud.githubusercontent.com/assets/17884568/18528441/198df2da-7a97-11e6-95f8-685323b264ff.PNG)

**Comment by venkataharishbillapati** [comment]
In the above example is there any possibility to remove spaces before example in swagger ui?

**Comment by webron** [comment]
You mean other than removing the spaces in the spec itself?

**Comment by venkataharishbillapati** [comment]
Yes...If some one gives unknowingly spaces before and later of the word they type I want the spaces to be removed.

**Comment by webron** [comment]
That seems somewhat out of scope. And input is an input. There should be a way to manipulate user input, though to me that beats the purpose of the tool.
