### ISSUE TITLE
when i try to send an json array,http body format seems  wrong.

### ISSUE THREAD

**Issue by zxspopo** [swagger-api/swagger-ui#2402]
when i try to send an json array,http body format seems  wrong.

![image](https://cloud.githubusercontent.com/assets/6873014/18496682/6dc30fc6-7a5a-11e6-851a-36363f4e40b6.png)

![image](https://cloud.githubusercontent.com/assets/6873014/18496699/88536d04-7a5a-11e6-90db-7696746a4671.png)

**Comment by webron** [comment]
I *think* there was a change that in case of arrays, the different values would be enter-separated. So you'd have one object, return, another object and so on. Can you give that a try? Not saying it makes sense, just a suggestion on how to overcome it right now.
