### ISSUE TITLE
BUG in rendering array with items of different types 

### ISSUE THREAD

**Issue by brunohms** [swagger-api/swagger-ui#2403]
People in my company have defined some weird arrays for back end/front end communication.

These arrays have more than one type as it items, and when swagger renders it they can become very messy as can be seen in the figure below.

![image](https://cloud.githubusercontent.com/assets/9116041/18521131/50070bb4-7a81-11e6-8bc4-0bff5cce243d.png)

I cannot give the full file of my swagger as I work in a company, however I managed to create a smaller yaml that is also able to reproduce this problem.
[swagger.txt](https://github.com/swagger-api/swagger-ui/files/472735/swagger.txt) (Uploaded as a txt because git doesn't support yaml files.)

I would very much appreciate if you guys could solve this problem.

**Comment by webron** [comment]
This is not an issue. The spec simply does not support multi array types.
