### ISSUE TITLE
OAuth-2.0 supported flows

### ISSUE THREAD

**Issue by Gobliins** [swagger-api/swagger-ui#2406]
It's not a real issue, but i would like to understand which OAuth2 flows SwaggerUI ( I am using v2.2) support and i found no real documentation about it. Can someone tell me which flows are supported?

I am in need of "Authorization Code Grant flow" where user login is required and also, i am looking for the "Client Credentials flow" (Could this be application flow in swaggerui?). Are these two supported and what do i have to put in my json spec?

Until now i got:

`"securityDefinitions": {   
    "OauthSecurity": {   
        type": "oauth2",
                "authorizationUrl": "https://adfsserver/adfs/oauth2/authorize",   
                "tokenUrl": "https://adfsserver/adfs/oauth2/token",   
                "grantType" : "authorization_code",
         "flow": "accessCode",
         "scopes":{  
                  "write:sessions":"kill sessions",
                  "read:sessions":"get sessions"
                 }
        }
    },`

*note: I have used AccesCode since i thought it could be same as auth. grant code flow.

**Comment by fehguy** [comment]
Currently only the implicit flow is supported in the UI.  Password / access code flows will be added soon.

**Comment by mdhalgara** [comment]
@fehguy - looking forward to this feature as we're waiting to incorporate it in our project.  Do you by any chance have a time frame on when this will be added?

**Comment by webron** [comment]
No ETA, but we're working on it.

**Comment by mdhalgara** [comment]
Thanks for letting us know!  :)

**Comment by mdhalgara** [comment]
@webron - thanks for letting us know!

**Comment by webron** [comment]
All flows should be supported in 3.X.
