### ISSUE TITLE
buildUrl does not resolve relative links

### ISSUE THREAD

**Issue by dolmen** [swagger-api/swagger-ui#2407]
The SwaggerUI.buildUrl function does not resolves relative links such as `../swagger.json` or `./swagger.json`.

swagger-ui version: 2.2.3 (master)

**Comment by fehguy** [comment]
You mean you're passing a relative link to it?  I don't know that really makes sense

**Comment by dolmen** [comment]
I wanted to use a relative link, assuming it would be resolved relative to the URL of the document from which Swagger UI is invoked.
A relative link is better in my case to avoid hard coding the hostname in the URL for dev/testing/prod environments.
I wrote a workaround by building the absolute spec URL before passing it to SwaggerUI. The code is not online anymore as my company collapsed.
