### ISSUE TITLE
Error in console in case of an empty parameter

### ISSUE THREAD

**Issue by chaya7908** [swagger-api/swagger-ui#2410]
In case swagger json contains an header parameter with an empty string in `name` attribute,
clicking on "Try it" button - causes a javascript failure which isn't handled in the code.
> Uncaught SyntaxError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': '' is not a valid HTTP header field name.

- swagger-ui version **2.1.4**
- a swagger file reproducing the issue 
```
{
    "swagger": "2.0",
    "info": {
        "title": "My Flow API",
        "version": "0.0.1"
    },
    "basePath": "/",
    "paths": {
        "/url": {
            "get": {
                "summary": "Summary",
                "description": "Description",
                "parameters": [
                    {
                        "name": "",
                        "in": "header",
                        "description": "",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "default": {
                        "description": ""
                    }
                }
            }
        }
    }
}
```

**Comment by fehguy** [comment]
ok, well `name: ""` is neither valid per the spec nor useful.  I suppose we could reject loading your definition?  If that's what you're after, please open an issue in swagger-client and it could be done.
