### ISSUE TITLE
Swagger response referencing

### ISSUE THREAD

**Issue by simar15** [swagger-api/swagger-ui#2412]
Hi I am working with Swagger version 2.10.3

I need to create reference file for http responses, (400,401,404) which produce the same result for all the methods, hence better to reference than to create redundant block of code.

`responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              _id:
                $ref: '#/definitions/Id'
              _links:
                type: object
                properties:
                  curies:
                    $ref: '#/definitions/Curies'
                  self:
                    $ref: '#/definitions/Self'
              name:
                type: string
                description: The name of the category.
        
          $ref: '#/definitions/responses'
          `

response 200 is different for different methods.  

and this is what I have under definitions:
`definitions:

  responses:
    type: object
    properties:
      '400':
       type: string
       default: Bad Request.`

but I get the error

✖ Swagger Error
Not a valid response definition
Jump to line 103
Details
 Object

Any help with this would be really appreciated.

When reporting a bug, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-editor#1067
