### ISSUE TITLE
curl command ignores selected Response Content Type and defaults to Accept: application/json

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#2413]
Create the following Swagger document

```
swagger: '2.0'
info:
  version: 0.0.1
  title: Swagger UI issue
  description: "curl command ignores selected Response Content Type and defaults to Accept: application/json"
host: www.example.com
basePath: /swaggerIssues
paths:
  '/tryMe':
    get:
      produces:
        - application/vnd.sas.api+json
        - application/json
      responses:
        '200':
          description: top-level API object
          schema:
            title: top-level-links
            $ref: '#/definitions/api'
definitions:
  api:
    properties:
      name:
        type: string
        description: The API name
      version:
        type: string
        description: The API version
```

View in Swagger-UI.
Expand the `GET /tryMe` operation
The _Response Content Type_ drop down should default to the first item in the `produces` list, `application/vnd.sas.api+json`
Click the **Try it out!** button.
The sample curl command ignores the selected type:

```
curl -X GET --header 'Accept: application/json' 'http://www.example.com/swaggerIssues/tryMe'
```

and uses `Accept: application/json` instead of `Accept: application/vnd.sas.api+json`

**Comment by DavidBiesack** [comment]
package.json shows this is ` "version": "2.1.4"`

**Comment by fehguy** [comment]
Can you please test against 2.2.3?  There are substantial fixes in the asCurl logic

**Comment by DavidBiesack** [comment]
I still see this with 2.2.3 - just downloaded it and also refreshed the browser.
(Is there some way to see the actual version in the browser UI?)

**Comment by fehguy** [comment]
Thanks for verifying.  Looking through the code, it appears that the curl command is using the _actual_ `Content-Type` from the response, not what you specified in the request, which is clearly not right.

**Comment by jusw85** [comment]
I can verify this is occurring in 2.2.5

**Comment by kchsieh** [comment]
I can confirm this is still an issue in the latest 2.2.6.

**Comment by kchsieh** [comment]
In fact, I am currently using 2.1.3 in production, so this is an issue started way back.  And I have been very patiently waiting for the bug fix for quick some time now.  Please, please, someone take a closer look at what is causing this issue, much appreciated.

**Comment by webron** [comment]
This should be fixed in 3.X.

**Comment by DavidBiesack** [comment]
@webron does PR #2679 need to be closed?

**Comment by webron** [comment]
@DavidBiesack as you probably noticed, I'm on a spree organizing the tickets, and then I'll move the PRs. By minimum, the PRs would need to be resubmitted against the 2.x branch, and we'll evaluate those case by case. Please allow me some time to get to reviewing the PRs.
