### ISSUE TITLE
Double HTTP in curl command

### ISSUE THREAD

**Issue by carloscorrales** [swagger-api/swagger-ui#2415]
- swagger-ui version: 2.2.2

I'm finding an issue when moving an application to a production stage. When I try to test any path, it adds automatically a http:// before the url, leading to a no response from server error, because of "ERR_NAME_NOT_RESOLVED".

Checking the request URL, I can see something similar to this:

http://http://mydomain/mypath

Could you provide any advice?

Best regards

**Comment by webron** [comment]
Can you share your spec?

**Comment by carloscorrales** [comment]
Hi, thanks for your superfast response.

I have just changed the index.html file to use my url instead of the one by default:

Lines 34-41:

```
 <script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "http://mydomain/swagger.json";
      }
```

I'm able to access the Swagger-UI page, but when I try to do a POST, I get the error posted above.

I can also see several Errors using the Swagger validator, and they must be related.

http://online.swagger.io/validator/debug?url=http://mydomain/swagger.json

Using http://localhost:3000/swagger.json in development everything works like a charm...

**Comment by webron** [comment]
I'm still going to need your spec... Would be hard to figure it out without it.

**Comment by carloscorrales** [comment]
Ouh, I just discovered the issue. It is because of the fact I'm using swagger-jsdoc (https://www.npmjs.com/package/swagger-jsdoc) for generating the specs, and it wasn't properly configured. I was adding there a http:// that wasn't necessary.

Sorry for the inconvenience and I hope you didn't lose too much time.

Best regards and thanks again

**Comment by webron** [comment]
No worries, glad you got it sorted out, and thanks for providing the details. It may help someone else in the future.
