### ISSUE TITLE
UI fails to parse swagger with duplicate member (passes in editor and validator)

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#2418]
See also full details and sample swagger.yaml in https://github.com/swagger-api/validator-badge/issues/93 . trying to open that swagger.yaml in swagger-ui fails, I got only

**failed to parse JSON/YAML response**

and no further indication of what was wrong.  Since the editor and validator-badge (debug) did not report any problems with the YAML, I was only able to find the problem when I turned on swagger-ui JavaScript debugging in Chrome. The console only showed  **cannot parse JSON/YAML content**. I set the JS debugger to halt on exceptions. Eventually I found an exception: a schema definition in the larger swagger.yaml file had two `description` fields. Removing the `duplicate` field resolved the error.

Here is a small sample Swagger 2.0 document that is clean in the editor and validator but does not load in swagger-ui : 

```yaml
swagger: '2.0'
info:
  description: validator-badge does not detect yaml error that causes swagger-ui failure
  version: 1.0.0
  title: validator false negative
host: 'www.example.com'
basePath: /
paths:
  /score:
    get:
      produces:
        - application/json
      responses:
        200:
          description: A score result
          schema:
            $ref: '#/definitions/scoreResult'
definitions:
  scoreResult:
    properties:
      outputs:
        type: string
        description: the score output data
      scoreRequest:
        description: This is the description of this member.
        type: string
        description: Oops, this schema has two description members.
      version:
        type: integer
        format: int32

```

**Comment by fehguy** [comment]
this is an invalid spec.  You should not expect it to work

**Comment by DavidBiesack** [comment]
I don't expect it to work. I expect some error indication/report, not a UI that simply halts. As is, the tools do not tell me what is wrong. Instead, swagger-ui swallows the exception caught in the bowels. The other tools do **not** find/report the invalid document.

**Comment by fehguy** [comment]
I believe that's a different issue, and you did report it in the validator.  Will see if it can be detected there.

**Comment by gigi888** [comment]
Many thanks for DavidBiesack to post the troubleshooting tips. Very helpful to me!

**Comment by magick93** [comment]
I'm also getting the same response from swagger-ui, but no indication as to what the problem is.

{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a sample.",
    "version" : "v1",
    "title" : "Shiftwork PlannerEngine",
    "termsOfService" : "https://gitlab.com/hughestech/plannerengine",
    "contact" : {
      "name" : "Anton Hughes",
      "url" : "http://shiftwork.io",
      "email" : "kurrent93@gmail.com"
    },
    "license" : {
      "name" : "Shiftwork 1.0",
      "url" : "https://gitlab.com/hughestech/plannerengine"
    }
  },
  "host" : "localhost:8080",
  "basePath" : "/rest",
  "tags" : [ {
    "name" : "nurserostering",
    "description" : "Operations about staff planning roster"
  } ],
  "schemes" : [ "http" ],
  "paths" : {
    "/nurserostering/solution/solve" : {
      "post" : {
        "tags" : [ "nurserostering" ],
        "summary" : "Solve a schedule plan",
        "description" : "Starts a planning job",
        "operationId" : "solve",
        "produces" : [ "application/json;charset=UTF-8" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "description" : "Planning Parameterization",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/NurseRosterParametrization"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/JsonMessage"
            }
          },
          "400" : {
            "description" : "Invalid ID supplied"
          }
        }
      }
    }
  },
  "definitions" : {
    "JsonMessage" : {
      "type" : "object",
      "properties" : {
        "text" : {
          "type" : "string"
        }
      }
    },
    "NurseRosterParametrization" : {
      "type" : "object",
      "required" : [ "firstShiftDate", "lastShiftDate", "planningWindowEnd", "planningWindowStart" ],
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        },
        "name" : {
          "type" : "string"
        },
        "firstShiftDate" : {
          "$ref" : "#/definitions/ShiftDate"
        },
        "lastShiftDate" : {
          "$ref" : "#/definitions/ShiftDate"
        },
        "planningWindowStart" : {
          "$ref" : "#/definitions/ShiftDate"
        },
        "planningWindowEnd" : {
          "$ref" : "#/definitions/ShiftDate"
        },
        "hardConstraintMatches" : {
          "type" : "integer",
          "format" : "int32"
        },
        "softConstraintMatches" : {
          "type" : "integer",
          "format" : "int32"
        },
        "firstShiftDateDayIndex" : {
          "type" : "integer",
          "format" : "int32"
        },
        "lastShiftDateDayIndex" : {
          "type" : "integer",
          "format" : "int32"
        }
      }
    },
    "Shift" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        },
        "shiftDate" : {
          "$ref" : "#/definitions/ShiftDate"
        },
        "shiftType" : {
          "$ref" : "#/definitions/ShiftType"
        },
        "index" : {
          "type" : "integer",
          "format" : "int32"
        },
        "label" : {
          "type" : "string"
        },
        "staffRequired" : {
          "type" : "integer",
          "format" : "int32"
        }
      }
    },
    "ShiftDate" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        },
        "dayIndex" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "dateString" : {
          "type" : "string"
        },
        "dayOfWeek" : {
          "type" : "string",
          "enum" : [ "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY" ]
        },
        "shiftList" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Shift"
          }
        },
        "date" : {
          "type" : "string",
          "format" : "date"
        },
        "label" : {
          "type" : "string"
        },
        "weekendSundayIndex" : {
          "type" : "integer",
          "format" : "int32"
        }
      }
    },
    "ShiftType" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        },
        "code" : {
          "type" : "string"
        },
        "index" : {
          "type" : "integer",
          "format" : "int32"
        },
        "description" : {
          "type" : "string"
        },
        "startTime" : {
          "type" : "string"
        },
        "endTime" : {
          "type" : "string"
        },
        "nightShift" : {
          "type" : "boolean",
          "default" : false
        }
      }
    }
  }
}
