### ISSUE TITLE
Embedding Swagger UI

### ISSUE THREAD

**Issue by sathomps** [swagger-api/swagger-ui#2420]
Before I dig too far, I want to be sure it's possible to embed the ui.  My application is currently using angular 1.5.8 along with webpack, gulp, browserify.  When serving my app running gulp, I get the following warning & error on page load.

WARNING in ./~/swagger-ui/dist/swagger-ui.js                                                                                                                           
Critical dependencies:                                                                                                                                                 
3152:486-493 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results. 

Module not found: Error: Cannot resolve module 'b' in c:\Users\igen361\workspace\ws-main\api-registry-ui\node_modules\swagger-ui\dist                                  
 @ ./~/swagger-ui/dist/swagger-ui.js 21852:8-21854:10

**Comment by ponelat** [comment]
Yes... its not advised to bundle this, as it wants to control the page ( or DOM ). In other words, there will be mixed results. If it compiles ( the missing module probably can be worked around )

So there is no support for _commonjs_ bundling at this point. Something I'm sure the future will hold.

We've had iframe setups to help mitigate this, but it also has its own challenges. If you're in angular, it might be worth visiting swagger-editor ( which is also in angular 1.x)

**Comment by sathomps** [comment]
Thanks for the info, I'll check out the swagger-editor.
