### ISSUE TITLE
to get swagger file on openfire server

### ISSUE THREAD

**Issue by faakruddin** [swagger-api/swagger-ui#2421]
i am new to swagger actually i am working on openfire server while i am trying to get swagger.json file but i am unable to get can any one help me what is the context path to get swagger.json file on openfire.

 

i am trying to get path is :http:localhost:7070/(myplugin path)/(myurl)/swagger.json

**Comment by fehguy** [comment]
I don't think this is a swagger-ui issue.

**Comment by faakruddin** [comment]
hai @fehguy while i am trying same application on tomcat it generates swagger.json file, but i am trying on openfire for same application it is not generates
