### ISSUE TITLE
SwaggerUI always adding security header

### ISSUE THREAD

**Issue by PaoloneM** [swagger-api/swagger-ui#2422]
Hi,
  I'm experimenting this problem with both Latest commit f7424a7 and SwaggerUI middelware distributed with swagger-tools (node.js server code generated by Swagger Editor).

This is part of my swagger yaml:

```
info:
  description: "iPatrol API interface"
  version: "1.0.0"
  title: "iPatrol API"
host: "127.0.0.1:8080"
basePath: "/v1"
schemes:
- "http"
securityDefinitions:
  jsonWebToken:
    type: apiKey
    name: Authorization
    in: header
produces:
- "application/json"
paths:
  /device/{deviceId}/alarm:
    put:
      tags:
...
  /device/{deviceId}/pong:
    put:
      security:
        - jsonWebToken: []
...

```

I have defined a Security Definitions Object with a single security scheme, no API level Security Requirement Object and finally enforce the security schemes only on a couple of operations.

In the last commit swagger-ui, the header should be added by this:

```
    authorize: function () {
        this.authsCollectionView.collection.forEach(function (auth) {
            var keyAuth, basicAuth;
            var type = auth.get('type');

            if (type === 'apiKey') {
                keyAuth = new SwaggerClient.ApiKeyAuthorization(
                    auth.get('name'),
                    auth.get('value'),
                    auth.get('in')
                );
                 this.router.api.clientAuthorizations.add(auth.get('title'), keyAuth);

```

while in swagger-tools provided code, I've modified `clientAuthorizations` usage as follow:

```
var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization( "Authorization", "Bearer " + key, "header" );
window.swaggerUi.api.clientAuthorizations.add( "jsonWebToken", apiKeyAuth );

```

The result is that Swagger-UI adds Authorization header on every call for both operations with security enforced and operations with no security enforced, while expected behavior is to add the header only if security in enforced for the operation.

Am I doing something wrong in my swagger definition file that enforces security to all operations? Swagger editor only shows security panel on operations I have enforced security to.

Thanks.
Paolo

**Comment by dolmen** [comment]
Have you tried adding an explicit empty array for the default security (property 'security' at the top level)?
```
security: []
```

**Comment by PaoloneM** [comment]
Thanks @dolmen, it works putting the empty array in individual operations, not globally.

**Comment by fehguy** [comment]
your spec is correct, it shouldn't be applying the security to all operations.

**Comment by webron** [comment]
Should be fixed in 3.X.
