### ISSUE TITLE
Swagger-UI does not fully respect schemes (when using https)

### ISSUE THREAD

**Issue by hareesh-blippar** [swagger-api/swagger-ui#2423]
Swagger UI version - 2.2.5
Swagger version - 2.0

The schemes portion of my spec is as shown below -

```
schemes:
  - https
```

I'm hosting Swagger UI, and my yaml openapi spec on an http server.  My api server (which is documented using the openapi spec) on the other hand only accepts https (as clearly defined in the schemes portion of the spec which does not contain http).

However, the try it out feature of Swagger UI ends up making an http request to my api server instead of https!

**Comment by fehguy** [comment]
Please pull 2.2.5, just published.

**Comment by hareesh-blippar** [comment]
The issue still exists in 2.2.5 :(

**Comment by dolmen** [comment]
I'm also affected by this issue.

**Comment by fehguy** [comment]
you are correct.  Please try master, and if that fixes it, we can release 2.2.6

**Comment by dolmen** [comment]
This is fixed on master! 855b6c3170a47062bdb561a932369185e586d946

**Comment by webron** [comment]
Great, thanks for the confirmation @dolmen!

**Comment by fehguy** [comment]
Thanks for confirmation, I'll get 2.2.6 out shortly today

**Comment by raym** [comment]
@fehguy bump for getting 2.2.6 out. i am temporarily downgrading until 2.2.6 is out

**Comment by taroutatsou** [comment]
Am I the only one who can't get it working even with swagger-ui-2.2.5 ?

My swagger.json contains `"schemes":["https"]` , I load the UI locally using the node http-server module without SSL and in order to access my API I need to use https. The request generated is still using http.

**Comment by fehguy** [comment]
Yes, it should be this weekend.  There is another fix that is being added that is taking a bit of time.

**Comment by mastertinner** [comment]
I'm still getting this issue in 2.2.6...

**Comment by webron** [comment]
Should be fixed in 3.X.
