### ISSUE TITLE
UI omits the accept (Response Content Type) dropdown for non-JSON response

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#2425]
For the Swagger below, the `produces` is XML, not JSON. (We don't have a schema because this is an external spec, [application/gml+xml](https://en.wikipedia.org/wiki/Geography_Markup_Language) )
The POST operation does not show the Response Content Type drop down, so the user cannot select the media type. (and if `produces` only contains one, it should still show that type, for documentation purposes, as is done if there is only one JSON media type.)

Swagger UI is 2.2.3

Swagger document:

```
{
    "swagger": "2.0",
    "info": {
        "version": "1",
        "title": "No Response Content Type when produces XML",
        "description": "The UI omits the response content type drop down for non-JSON"
    },
    "schemes": [ "http" ],
    "host": "www.example.com",
    "basePath": "/producesXml",
    "paths": {
        "/service": {
            "post": {
                "summary": "Create a resource",
                "produces": [
                    "application/gml+xml",
                    "application/xml"
                ],
                "consumes": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "regionId",
                        "in": "query",
                        "description": "The GML region ID",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK, application/gml+xml resonse returned",
                        "type" : "string"
                    }
                }
            }
        }
    }
}

```

**Comment by DavidBiesack** [comment]
screenshot: 
![producesxml](https://cloud.githubusercontent.com/assets/545944/18843604/b8d2c97a-83e7-11e6-9bc9-fee722a0c58f.png)

**Comment by fehguy** [comment]
Your `responses` objects _must_ have a `schema` tag.  just using `type: string` won't work--try that and reopen if you still see an issue.

**Comment by DavidBiesack** [comment]
Unfortunately, I don't have JSON schema for GML; it is a large/complex XML schema. I also don't want to convert XSD that to JSON; it would create huge bloat in the Open API with no real benefit (the media type is sufficient). I would prefer swagger-ui be more flexible and be able to support non-JSON (but also non-empty) responses and still render the drop down so the client can specify an `Accept` header.. the two are orthogonal. I don't care if the UI does not show a model schema here; the API consumer will know what GML is.

How does one specify non-JSON responses (such as text/html, text/csv, application/pdf, image/png, or aplication/gml+xml using Open API?

**Comment by webron** [comment]
In the current version, you can use `type: file` - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types.
