### ISSUE TITLE
Feature - Swagger UI Summary & Description html encoding

### ISSUE THREAD

**Issue by JBaltika** [swagger-api/swagger-ui#2432]
Hi guys,

Just before i want to ask some technical question, i want to say big thanks for hard work! Impressive! 

I upgraded to the latest version of swagger ui and found the encoding was added for summary and description fields. And this is great feature for 90% of cases involved development. Humans make mistakes and that takes care. However, for some who is uses swagger in .net world, the json is generated from Visual studio xml documentation and adding the links & images/diagrams to summary & descriptions fields. This makes a swagger-ui on steroids! 

So, my question is : 
                Would be possible add a global flag like html encode  description and summary & set it to true. This would allow for folks who wants write html disable/enable and everybody happy.  What do you guys think?

![swagger-ui-html](https://cloud.githubusercontent.com/assets/1755340/18974421/da11e7b6-8670-11e6-88e0-c86b84070d9f.jpg)

**Comment by fehguy** [comment]
Consider using markdown, I believe it's supported there.  We walk a line between security and flexibility, and the security risks of XSS injection have been causing this.  But MD is safe, and supported.

**Comment by JBaltika** [comment]
can you forward example/link/docs. I tried enter markdown, but it didn't worked.

Thanks J.B

**Comment by fehguy** [comment]
```json
{
  "summary": "it **works**"
}
```

**Comment by JBaltika** [comment]
Awesome! Its was caching issue on server. Thanks!
