### ISSUE TITLE
Swagger UI does not display response models properly

### ISSUE THREAD

**Issue by hareesh-blippar** [swagger-api/swagger-ui#2433]
Swagger UI version - 2.2.5
Swagger version - 2.0

I found the following issues with the way Swagger UI displays responses (refer example screenshot attached in the end).

My response definition is as follows

```
      responses:
        200:
          description: User response
          schema:
            $ref: '#/definitions/User'
        201:
          description: Another response
```

```
  User:
    type: object
    description: User data
    properties:
      Groups:
        type: array
        items:
          $ref: '#/definitions/Group'
      Roles:
        type: array
        items:
          $ref: '#/definitions/Role'
```
1. The response model displayed by Swagger UI is ambiguous. In the given example screenshot, it is not clear that the response is just the User object, and that the Group and Role objects are just contained inside the User object.
2. The description of the user object _`description: User data`_ (which is pretty important since it is a summary) is missing from the response model shown by Swagger UI.
3. Responses are displayed either at the top in Response Class (for status 200, when a schema is present), or at the bottom in Response Messages (for status 201; or for status 200 if the schema was absent). This behavior is inconsistent.
4. The response description (which is pretty important since it is a summary) is not displayed if the response is shown at the top.
5. The response description is displayed if the response is shown at the bottom, but it is called _reason_ instead of _description_ o.O

<img width="973" alt="response models" src="https://cloud.githubusercontent.com/assets/14183519/18975984/35f49fbe-8663-11e6-83bf-6da3585a1f55.png">

**Comment by fehguy** [comment]
where is `Another Response` coming from?  What is your 201 definition?

**Comment by hareesh-blippar** [comment]
@fehguy - Just updated the original ticket with more clarifications. My 201 definition is
```
        201:
          description: Another response
```

**Comment by fehguy** [comment]
Some feedback:

1.  I believe the first item is the top-level object.  Anything else is contained.

2. Yes, that's a missing piece of metadata

3. Not quite, we will take the lowest code `success` response and put it at the top.  Others to the bottom.  This was a design choice, and will likely change soon

4. As with 2, yes this is missing

5.  Send a PR please :)

**Comment by hareesh-blippar** [comment]
@fehguy - Thanks for the quick follow up. Will try to send a PR with improved response formatting that I've been using for my docs.

**Comment by webron** [comment]
No longer an issue with 3.X.
