### ISSUE TITLE
swagger ui doesn't get base path when swagger uses snake case for schema json

### ISSUE THREAD

**Issue by xunnanxu** [swagger-api/swagger-ui#2434]
swagger-ui version: 2.2.5

Swagger allows you to change global json property naming style. When snake case is used, it changes "basePath" to "base_path" and thus swagger ui cannot grab the path any more.

Not sure if this should belong to here or swagger core.

**Comment by fehguy** [comment]
This must be in your underlying library.  Is this a generated server, using swagger-core, springfox, etc?

**Comment by xunnanxu** [comment]
This is [swagger play integration 1.5.2](https://github.com/swagger-api/swagger-play) using swagger core.
