### ISSUE TITLE
Posting an associative array alongside with formdata doest work

### ISSUE THREAD

**Issue by anouarabdsslm** [swagger-api/swagger-ui#2435]
I'm not sure if there is already a solution for this
I need to post an associative array my end point , somethign like 

```
[
    "description" => "Blah",
    "animal" => [
        "cats"=>["donna", "dupy"],
        "dogs"=>["gum", "gunyo"],
    ],
    "humans" => ["human", "human"]
]
```

alognside with some formData , I have tried to use the `in=body` post the json representation for the array but in this case params defined as formdata wasn't included within the request payload , its only include the json format in the body box. Any idea to resolve this.

**Comment by fehguy** [comment]
You can't have `formData` plus a `body` parameter.
