### ISSUE TITLE
Model rendering does not respect minimum value

### ISSUE THREAD

**Issue by vanderlee** [swagger-api/swagger-ui#2436]
Actual behaviour: Models are rendered by showing `default` values.
If no `default` is specified, `0` is used instead, even if a `minimum` is set that does not allow `0`.

Expected behaviour: Set the value closest to `0` that is allowed by the `minimum` (et al.) settings.

Swagger-UI v2.2.5

`{
    "swagger": "2.0",
    "info": {
        "title": "Demo",
        "version": "v1.0.0"
    },
    "paths": {
        "\/resources": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#\/definitions\/Field"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Field": {
            "type": "object",
            "properties": {
                "id": {
                    "format": "int64",
                    "minimum": 1
                }
           }
        }
    },
}`

**Comment by fehguy** [comment]
Yes, the example generator isn't intelligent enough to honor the min/max values.  Consider sending a PR to address this.
