### ISSUE TITLE
Response Message's Example Value not shown

### ISSUE THREAD

**Issue by renatolond** [swagger-api/swagger-ui#2441]
Hi!
I'm using swagger-ui-2.2.5, and I'm having some trouble seeing the example on non-successful responses. I think this might be related to the issue discussed in #671, but I'm not sure.
I changed the Uber API swagger editor example to include what's happening with me:
[example.zip](https://github.com/swagger-api/swagger-ui/files/513302/example.zip)

Also, here's a screenshot on how it appears to me:
![screenshot_20161006_112024](https://cloud.githubusercontent.com/assets/173791/19147121/fc47de76-8bb6-11e6-8d1a-b2fa0948fc88.png)

**Comment by webron** [comment]
Should no longer be an issue with 3.X.
