### ISSUE TITLE
Request header always shows json content type

### ISSUE THREAD

**Issue by AndrewCampbellSynchronoss** [swagger-api/swagger-ui#2443]
When request headers turned on, the request header always shows a json content type even if another is selected in the Response Content Type dropdown.

<img width="939" alt="screen shot 2016-10-06 at 13 27 39" src="https://cloud.githubusercontent.com/assets/13764960/19152222/f3cdd860-8bc8-11e6-8ea3-10cc4013dfa2.png">

Screenshot is from an instance running swagger-ui.js version v2.2.5 with http://petstore.swagger.io/v2/swagger.json. The only change made is to set `showRequestHeaders` to `true` in index.html.

**Comment by webron** [comment]
Should no longer be an issue with 3.X.
