### ISSUE TITLE
"required: false/true" is not possible in Response schema

### ISSUE THREAD

**Issue by rtmummels** [swagger-api/swagger-ui#2444]
Swagger Editor version: 2.10.3
The following swagger contents is rejected by the editor, the "required" seems not to be allowed:

      responses:
        200:
          description: Successful response. The deviceId can be returned.
          schema:
            title: newDeviceId
            required: false #NOT ALLOWED??
            type: string
            description: Returned OneM2M OID by the platform.

However, this should be possible according to http://swagger.io/specification/#schemaObject

**Comment by fehguy** [comment]
please open this in the swagger-editor project
