### ISSUE TITLE
Method versioning

### ISSUE THREAD

**Issue by makedonmax** [swagger-api/swagger-ui#2445]
Hello,
we want to add versioning through headers to our REST API method, like this:

```
@RequestMapping(value = "/list", method = RequestMethod.GET, headers="Version=1")   
public @ResponseBody List<DataV1> getList() {...}

@RequestMapping(value = "/list", method = RequestMethod.GET, headers="Version=2")   
public @ResponseBody List<DataV2> getList() {...}
```
And 2nd method will have one more input parameter and will return another data type.
Swagger specification file is generated automatically.

Is it possible to force Swagger-UI to show only 1 method ("../list") with possibility to change a version?

I'd be grateful for any ideas or suggestions.

**Comment by kosiakMD** [comment]
nice idea
