### ISSUE TITLE
Getting auth sections to display

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-ui#2446]
Hi,
I'm using the latest 2.2.5 version of swagger-ui.

When I use editor.swagger.io and paste in a swagger spec we have, there is a nice Security section at the top with the flow, auth urls and scopes. Additionally, for each operation at the bottom, there is a security section containing schema and scopes.

When I use swagger-ui against the same specs I use in editor, I'm not seeing any of this. The best I can get so far is a button that opens a window with info using "auth-container".

Is there a way I can get my specs to look like what I see at editor.swagger.io?

Thanks!

**Comment by fehguy** [comment]
the swagger-ui renders an auth window based on your `securityDefinitions`.  It follows oauth implicit flow, api key, basic auth.  If you're not seeing something, check your security definitions and provide more details here, like a spec.

**Comment by jaydreyer** [comment]
Sounds good. I've re-written ours to show that info as part of the docs and not as a pop-up window, similar to how it appears on editor.swagger.io.
