### ISSUE TITLE
eureka & swagger-ui

### ISSUE THREAD

**Issue by yihukurama** [swagger-api/swagger-ui#2454]
When reporting a bug, please provide the following details:
- swagger-ui 2.6.0 + eureka    Brixton.SR5
- 
I just use swagger ui and eureka for my project. However there is no reproducing about the issue, swagger-ui work well but eureka cannot found the application name. I use two day for this bug, at last I common all about swagger ui and eureka found the service.Could you help me to solve this issue.

**Comment by webron** [comment]
There's no swagger-ui 2.6.0, the current version is 2.2.6.
If you're saying swagger-ui is working correctly, it sounds like you should reach out for the support for eureka - we can't really help you with that I'm afraid.
