### ISSUE TITLE
Array not working

### ISSUE THREAD

**Issue by kwaazaar** [swagger-api/swagger-ui#2458]
This is contained in the swagger.json:

``` json
     "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Topic"
              }
            }
          }
        },
```

Yet, the (packed) SwaggerUI displays 'inline model':
![swaggerui-array](https://cloud.githubusercontent.com/assets/8937587/19589786/9321e1c6-976e-11e6-9d5a-873f303a206f.png)

[swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/543725/swagger.json.txt)

I'm using Swashbuckle 6.0.0-beta902 in my .NET Core project. I have no clue where to find the Swagger-UI version (maybe add to the HTML (generator-tag in head or render in footer)?).

**Comment by fehguy** [comment]
Can you please share the definition for the `Topic` model?

**Comment by kwaazaar** [comment]
It's at the end of the attached swagger.json.txt:
```
         "Topic": {
            "type": "object",
            "properties": {
                "id": {
                    "format": "int64",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                }
            }
        }

```

**Comment by gislikonrad** [comment]
I have this issue as well. I'm using Swashbuckle 5.5.2 which has swagger-ui built in from checkin f7424a700989e89929e0404f12a8363cc8d27bfd.

**Comment by kwaazaar** [comment]
The sources of my code can be found here: [https://github.com/kwaazaar/Resonance](https://github.com/kwaazaar/Resonance)

**Comment by drakej** [comment]
#2325 seems to be the same issue

**Comment by webron** [comment]
This should no longer be an issue with 3.X.
