### ISSUE TITLE
Path of "/" is initially hidden on page load

### ISSUE THREAD

**Issue by scmorse** [swagger-api/swagger-ui#2459]
swagger-ui version: 2.2.6

a swagger file reproducing the issue:

```
{
    "swagger": "2.0",
    "schemes": ["http"],
    "paths": {
        "/": {
            "post": {
                "description": "Fake description",
                "responses": {
                    "200": {
                        "description": "Success",
                        "examples": {
                            "application/vnd.v1+json": "{}"
                        }
                    }
                },
                "produces": ["application/vnd.v1+json"],
                "operationId": "post",
                "tags": [""],
                "summary": "Fake summary"
            }
        }
    },
    "tags": [],
    "basePath": "/",
    "host": "192.168.99.100:3000",
    "info": {
        "title": "service-fake",
        "version": "1",
        "description": "Fake info description"
    }
}
```

For some reason, an entry in `"paths"` where the route described is `"/"` is hidden initially. One has to click "show/hide" to show the docs for this route.

![screen shot 2016-10-21 at 4 16 45 pm](https://cloud.githubusercontent.com/assets/4519249/19610319/df0d7e2a-97a9-11e6-8698-121af16ebb36.png)

**Comment by scmorse** [comment]
I also discovered that when there are multiple routes, and one of them is "/", clicking the "show/hide" for the "/" route shows/hides all of the routes.

**Comment by webron** [comment]
It's not because of the "/" path, it's because the tag you assigned to the operation is "", being an empty string, so it ends up being invisible.

**Comment by scmorse** [comment]
I removed the empty string from the tags array and the problem persists. It still is hidden by default on page load. I also tried removing the `"tags": []` from the response itself, and the endpoint row is still hidden by default on page load.

Here is an even more minimal example where the problem still occurs:

```
{
    "swagger": "2.0",
    "schemes": ["http"],
    "paths": {
        "/": {
            "get": {
                "description": "Fake description",
                "summary": "Fake summary"
            }
        }
    },
    "host": "192.168.99.100:3000",
    "info": {
        "title": "service-fake",
        "version": "1",
        "description": "Fake info description"
    }
}
```

**Comment by webron** [comment]
It works for me with the latest master - it appears under the `default` tag.

**Comment by scmorse** [comment]
What determines whether or not a route or group of routes is visible on page load? I'm talking about the basic description line, like this:

<img width="977" alt="screen shot 2016-10-24 at 12 47 23 pm" src="https://cloud.githubusercontent.com/assets/4519249/19654883/0fa07ac0-99e8-11e6-9c3d-8996084c1c96.png">

They are visible in some page loads and not visible in others. I want them all to be visible at first, and then the user can expand an individual endpoint to get more info.

**Comment by webron** [comment]
Okay, that has nothing to do with the originally mentioned issue though.

Check out the `docExpansion` parameter under https://github.com/swagger-api/swagger-ui#parameters.

**Comment by scmorse** [comment]
That docExpansion parameter is useful, thank you.

I think I jumped to conclusions as to the cause of the problem, assuming it was because of the "/" path, but the row not showing is the row not being visible is the same problem I originally had.
