### ISSUE TITLE
Make `Response Messages` section collapsable

### ISSUE THREAD

**Issue by Pchelolo** [swagger-api/swagger-ui#2463]
The Response Messages section in the UI takes up a lot of space without being useful most of the time. I would suggest making it collapsible (with a little '+'), this way the "Make Request" button is visible from the start. Otherwise it was a bit confusing at first to see the input fields but not see a button - had to scroll down. I don't think moving the button above the response messages is good because the results of the call show up below it, thus it would totally separate response doc from request doc.

**Comment by webron** [comment]
@Pchelolo we just released a new version. The responses is of a similar construct, with the successful response now being part of that list. Would love for you to check it out and share your thoughts.

If you still think it should be collapsed, I'm wondering if you'd expect them all to be collapsed or just the non 2XX responses (which are the erroneous ones).

**Comment by Pchelolo** [comment]
I guess with the new UI this request is irrelevant since the 'try it out' button was moved up. Feel free to close

**Comment by webron** [comment]
Thanks for the input. We're still going to make some layout changes, would love your input as we move forward.

**Comment by NPi2Loup** [comment]
In ours case, it may be usefull to collapse all erroneous responses.

We have a lots of standard error code support with standard response format. 
Like 👍 
400 | Bad request : parsing error (json, number, date, …)
401 | Unauthorized : no valid session
403 | Forbidden : not enought rights
422 | Unprocessable entity : validations or business error
429 | Too many request
500 | Internal server error
We may removed them from API description, but API contract will be incomplete.

Theses infos take a lot of space, are redundant and so aren't very usefull.
Maybe juste show the possible codes and collapse examples ?

**Comment by shockey** [comment]
@NPi2Loup, I like this! For my part, I'd be interested in discussing whether segmenting them by 1xx, 2xx, 3xx, etc.. is a good approach. Feel free to open a ticket :smile:
