### ISSUE TITLE
Swagger UI ignores certain HTML tags

### ISSUE THREAD

**Issue by zolcsi** [swagger-api/swagger-ui#2468]
Question: I am using v.2.6.0 and have in @ ApiOperation in 'notes' field a well formatted html, which was shown perfectly before in version 2.1.5.
Newly some tags seem to be ignored/filtered out/who knows?
Like: `<br>, <ul></ul>`
Do you have any thoughts about it?

**Comment by fehguy** [comment]
Use markdown for formatting.  Also you may need to reopen your issues in swagger-core, which is what supports the `@ApiOperation`.

**Comment by zolcsi** [comment]
Thanks, markdown works.
