### ISSUE TITLE
Exceptions when request and response contain image file

### ISSUE THREAD

**Issue by kevinmreynolds** [swagger-api/swagger-ui#2470]
We have an API that takes a file as part of a _multipart/form_ POST, and returns a file.  This is leading to a couple of exceptions in swagger-ui that are preventing the response from being displayed, leaving the user stuck looking at the throbber.  

The first is a **YAMLException** being thrown in _JQueryHttpClient.prototype.execute_.  This is caught and logged as 'unable to parse JSON/YAML content'.  There seems to be an assumption in this code that the response will be JSON or YAML, which is not the case here.  The content-type is image/png.

The second is **Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.**.  This is coming from _OperationView.showStatus_ line 756 (in the Image conditional block).  Here, it looks like the assumption is that _content_ is a Blob, but it is actually a string.  I'm not sure if it should have been turned into a blob by this point, or if there should be handling for the case where it's a string.
- swagger-ui version: 2.2.6
- a swagger file reproducing the issue:

``` yaml
swagger: '2.0'
info:
  title: Some Service
  version: "0.1.0"
  description: A service.
basePath: /
paths:
  /api/v1/files:
    post:
      produces:
        - image/png
      consumes:
        - multipart/form-data
      parameters:
        - name: File 
          in: formData
          description: file to be processed
          required: true
          type: file
        - name: params
          in: formData
          description: parameters
          required: true
          type: string
      responses:
        '200':
          description: response body contains output image file
          schema:
            type: file
```

**Comment by fehguy** [comment]
Please test with 2.2.7, there were a bunch of fixes pushed in the image download.  Reopen if you still see issues

**Comment by kevinmreynolds** [comment]
I'm no longer seeing the Uncaught TypeError.  However, it is still not rendering the image.  I'm still seeing the 'unable to parse JSON/YAML content' error that's being thrown from the JQueryHttpClient in the swagger-js project.  Should I open this as a new issue under that repo?

**Comment by fehguy** [comment]
Please do. Are you using internet explorer or requesting jquery for some other reason?

**Comment by kevinmreynolds** [comment]
I've opened https://github.com/swagger-api/swagger-js/issues/906
I think the reason jquery is used is due to the form containing a file upload.  In OperationView.js, I see this:
```
if (isFileUpload) {
       ...
        opts.useJQuery = true;
       ...
        return this.model.execute(map, opts, this.showCompleteStatus, this.showErrorStatus, this);
      }
```
