### ISSUE TITLE
when i send the type of Long param to request server, the request was failed

### ISSUE THREAD

**Issue by bolyack** [swagger-api/swagger-ui#2475]
when i send the type Long param to request server, the request fails
 version number used: springfox-swagger-ui  2.2.2
i send a request constains the type of Long param to server, Request response failed because of the parameter type， see attachment for details.
![u1](https://cloud.githubusercontent.com/assets/11990762/19883312/95bafe0c-a04e-11e6-8e36-5c221e0e941c.jpg)
![u2](https://cloud.githubusercontent.com/assets/11990762/19883316/96e4fb16-a04e-11e6-9770-2df85d0a32fe.jpg)
![u3](https://cloud.githubusercontent.com/assets/11990762/19883307/9384b290-a04e-11e6-97ef-b3b0c976d852.png)

**Comment by bolyack** [comment]
the server code:
`	@ApiOperation(value = "get user detail info")
	@ApiImplicitParam(name = "id", value = "user ID", required = true, dataType = "Long")
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public User getUser(@PathVariable Long id) {
		return users.get(id);
	}`

**Comment by bolyack** [comment]
i find the question , Because of the method should be add a attribute "paramType"

**Comment by fehguy** [comment]
ok so did you solve it?
