### ISSUE TITLE
Response Messages (Response Model) failing for application/xml

### ISSUE THREAD

**Issue by ritwik-dell** [swagger-api/swagger-ui#2477]
When reporting a bug, please provide the following details:
- swagger-ui version = 2.2.6
- a swagger file reproducing the issue

Following are the excerpts from my swagger file:

```
produces:
  - application/xml
  .....
  .....
      responses:
        200:
          description: Success response
          schema:
            $ref: '#/definitions/cars'
        400:
          $ref: '#/responses/bad-request-error'

definitions:
  cars:
    $ref: './common/car.schema'
  response-status:
    $ref: './common/response-status.schema'

responses:
  bad-request-error:
    description: Response for badly formed request
    schema:
      $ref: '#/definitions/response-status'

```

The **car.schema** and **response-status.schema** are simple json files defining their structure.

While SwaggerUI was able to render car.schema appropriately in the "Model | Example Value" of "Response Class (Status 200)" section, it failed to do so ONLY in the "Example Value" of the "Response Messages" --> "Response Model" section. 

While the "Model" tab was able to refer and pull the external reference and render it correctly on the UI, the "Example Value" tab just showed:

```
<?xml version="1.0"?>
<!-- invalid XML -->
```

When I change the `produces` from `application/xml` to `application/json`, everything works fine.

Feel free to reach out to me for any additional clarifications.

**Comment by fehguy** [comment]
Please retest against master.  We had some issues rendering the XML which should be addressed now.
