### ISSUE TITLE
Swagger UI stripping HTML

### ISSUE THREAD

**Issue by paul3291** [swagger-api/swagger-ui#2478]
In the latest Swagger-UI 2.2.6 and it looks that it's also in 2.2.4, that some html tags are being lost/removed after the structure is built from the swagger json. If you load the http://petstore.swagger.io/v2/swagger.json you will notice that the POST pet model has details concatenated together as shown below.

![image](https://cloud.githubusercontent.com/assets/2818069/19917386/efa2f730-a116-11e6-98e3-6d433196e2f8.png)

It looks like the original html that is generated is like this

![image](https://cloud.githubusercontent.com/assets/2818069/19917428/64d1c78e-a117-11e6-8403-116cdbd8dda1.png)

But this is what end up in the browser (chrome)
![image](https://cloud.githubusercontent.com/assets/2818069/19917454/aaedbe1c-a117-11e6-9f0f-e1987608b7cd.png)

**Comment by paul3291** [comment]
Just wondering if the html content is being over sanitized? It appears that the table that is being stripped was previously shown as a hover tool tip to data type, min/max size, etc..

**Comment by fehguy** [comment]
yes, it was pretty aggressive in the stripping.  It looks like this is rendering correctly now, please take a look at master when you can.

**Comment by paul3291** [comment]
Thanks Tony, looks good to me as well..

**Comment by fehguy** [comment]
thanks @paul3291
