### ISSUE TITLE
Hide ModelBinder paramter from Swagger UI. ASP.NET C#

### ISSUE THREAD

**Issue by nmathurbkn** [swagger-api/swagger-ui#2479]
I am preparing a web api using ASP.NET C#. To apply swagger UI I installed 5.4.0 version of Swashbuckle package.

I have two queries .. (searched web but nothing find that can work in C# ... or maybe I am not able to apply the same to my C# code .. so finally decided to ask here) .. >>

```
1. How to hide particular parameter from swagger UI
2. How to hide some properties from Swagger UI.
```

**How to hide particular parameter from swagger UI**
My api have Model Binder Objects as parameters in some of the methods/actions.  I don't want/need ModelBinder Parameters to show in swagger ui. 

One more reason to hide them is that UI is showing all properties of the ModelBinder Object in UI and it is looking very bad in UI. Suppose I have one in parameter and one ModelBinder parameter (this have 4 properties) total parameter display in UI are 5 and I need to show only 1. Something like following ...

```
> myIntParamter  ..............
> myModelBinder.<Parameter1>k__BackingField	query	integer  ...............
> myModelBinder.<Parameter2>k__BackingField	query	string  ................
> myModelBinder.<Parameter3>k__BackingField	query	string  ...............
> myModelBinder.<Parameter4>k__BackingField	query	string  .............

```
So, above is showing unnecessary data in swagger ui.  

**How to hide some properties from Swagger UI**
suppose I am using same model to create and update any entity .. e.g. Address ..

So the model is:
```
AddressId
Address.
PhoneNo.
```

Now for my add method I dont want to show AddressId ..but for update I want to show all properties.. this is just and example ..in real case my requirement is to hide 4-5 properties from UI. 

Please help.

**Comment by fehguy** [comment]
Sorry, but this is just for the UI.  This is definitely a Swashbuckle question, I suggest you ask there.
