### ISSUE TITLE
request payload is not sent in json format even when produce is set to application/json

### ISSUE THREAD

**Issue by Ankita-codemax** [swagger-api/swagger-ui#2480]
When reporting a bug, please provide the following details:
- swagger-ui version: @version v2.1.4
- a swagger file reproducing the issue: swagger-ui.js

We have swagger with following settings
e.g 
"produces": [
        "application/json"
    ],
// post param as below
"parameters": [
                    {
                        "name": "userName",
                        "in": "formData",
                        "description": "Email id of the user.",
                        "required": true,
                        "type": "string",
                        "format": "email"
                    },
                    {
                        "name": "password",
                        "in": "formData",
                        "description": "Password of the user.",
                        "required": true,
                        "type": "string",
                        "format": "password"
                    }
                ], 

when we click try out  the content type is set as
 Content-Type: application/x-www-form-urlencoded

and request payload is sent as below
 'userName=test&password=test'

we are expecting it to be as follow 
 Content-Type: application/json 
request payload:
{userName:test,password:test'}

So is there any way to sent the request in json format?

**Comment by fehguy** [comment]
x-www-form-urlencoded does not, by the specification, support JSON values in the fields.  You'll have to wait for the 3.0 spec.
