### ISSUE TITLE
Description text is incorrectly escaped

### ISSUE THREAD

**Issue by jrc** [swagger-api/swagger-ui#2482]
swagger-ui 2.2.6

Input:
```
swagger: '2.0'
info:
  version: 0.0.0
  title: Hello, world!
  description: |
    Lorem ipsum & < > <tag>.

    `Lorem ipsum & < > <tag>.`

        Lorem ipsum & < > <tag>.
paths: {}
```

Expected output (and this is what you get from http://editor.swagger.io/ ):
```
Lorem ipsum & < > <tag>.
Lorem ipsum & < > <tag>.
Lorem ipsum & < > <tag>.
```

Actual output (from swagger-ui 2.2.6):
```
Lorem ipsum & < > .
Lorem ipsum &amp; &lt; &gt; .
Lorem ipsum &amp; &lt; &gt; .
```

**Comment by fehguy** [comment]
Yes, we are not allowing HTML elements in the descriptions which do not fit in a white list.  The editor should be doing the same thing, and if not, it's a defect.

**Comment by jrc** [comment]
Shouldn't at least the characters & < > should be allowed in descriptions, without being mangled?
