### ISSUE TITLE
Test UI does not send HTTP GET body

### ISSUE THREAD

**Issue by joehoppe** [swagger-api/swagger-ui#2486]
Copying issue from Ahoy to Swagger-UI: https://github.com/domaindrivendev/Ahoy/issues/148

My web service expect a get request with a body. The generated swagger look correct (see below), the ui shows it with parameter type "body" and even the generated curl statement is correct (and works), but when the request is send from UI, it has no body.

Method definition in controller:
[HttpGet("testbody/{param}")]
[SwaggerResponse(System.Net.HttpStatusCode.OK, Type = typeof(IEnumerable<String>))]
public IActionResult GetTestBody(String param, [FromBody]String properties = null) {

curl: curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/json' -d 'property' 'http://localhost:61240/api/Ldap/testbody/param'

Excerpt from generated swagger.json:

```json
"/api/Ldap/testbody/{param}": {

"get": {
    "tags": [
        "Ldap"
    ],
    "operationId": "ApiLdapTestbodyByParamGet",
    "consumes": [
        "application/json",
        "text/json",
        "application/json-patch+json"
    ],
    "produces": [ ],
    "parameters": [
        {
            "name": "param",
            "in": "path",
            "required": true,
            "type": "string"
        },
        {
            "name": "properties",
            "in": "body",
            "required": false,
            "schema": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "schema": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "204": {
            "description": "No Content"
        }
    },
    "deprecated": false
}
},
```

@joehoppe
joehoppe 
commented 3 months ago
I am seeing the same thing with 6.0.0-beta901 for posts. The CURL statement works, but the only way to get parameters to be passed from the UI is to mark the parameters as [FromQuery]. Parameters without an attribute, or using [FromBody], the UI does not pass. Verified using Fiddler.

**Comment by fehguy** [comment]
Per http spec, get requests are not allowed to have a body.  Even if you define it, no tool _should_ support it.

**Comment by joehoppe** [comment]
I didn't copy the additional comments over from the other thread. It's also happening for posts.

"I am seeing the same thing with 6.0.0-beta901 for posts. The CURL statement works, but the only way to get parameters to be passed from the UI is to mark the parameters as [FromQuery]. Parameters without an attribute, or using [FromBody], the UI does not pass. Verified using Fiddler."

**Comment by fehguy** [comment]
@joehoppe can you please post your swagger definition into http://editor.swagger.io to see if you have any syntax errors in it?  That should help isolate where the problem is

**Comment by joehoppe** [comment]
I'm using Swashbuckle which I believe generates the swagger definition for me... What do you suggest as the next steps?
