### ISSUE TITLE
How to insert linebreak in Swagger v2.2.3

### ISSUE THREAD

**Issue by nerdofcups** [swagger-api/swagger-ui#2492]
Hello everyone,

I recently upgraded my Swagger version from v2.1.4 to v2.2.3. Previously, I'd been using \<br> to generate my linebreaks. However, it seems like Swagger no longer supports HTML tags and is exclusively using Markdown.

I was wondering how to insert linebreaks into my notes section in Swagger. I tried inserting \<br> and \n but neither are working. Any help would be much appreciated.

**Comment by webron** [comment]
Actually, markdown supports HTML tags, so if it stopped working, it's a bug.

**Comment by fehguy** [comment]
This was fixed, please try master.
