### ISSUE TITLE
SwaggerUI not able to pass api_key in header

### ISSUE THREAD

**Issue by ritwik-dell** [swagger-api/swagger-ui#2495]
When reporting a bug, please provide the following details:
- swagger-ui version = SwaggerUI 2.2.6
- a swagger file reproducing the issue = See below.

In my Swagger file, I have my api_key defined as a header parameter.

```
    "securityDefinitions": {
        "api_key": {
            "type": "apiKey",
            "name": "api_key",
            "in": "header"
        }
    },
```

When I am pulling it up on SwaggerUI, the authorize button is able to read it and show cases the following: 
![image](https://cloud.githubusercontent.com/assets/9384995/20243083/15717784-a905-11e6-933a-ddb5eb4c9d10.png)

However, when I am clicking on "Try-it" button, it is not sending in the "api_key" header. Instead here is how the request goes out: 

```
OPTIONS /api-url HTTP/1.1
Host: api-host.com
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Access-Control-Request-Headers: api_key, content-type
Accept: */*
Referer: http://localhost:8080/swagger-ui-2.2.6/dist/?url=http://localhost:8080/swagger.json
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

Note: It sends the header field `api_key` as a value of `Access-Control-Request-Headers` instead of sending something like `api_key=ABCD` as the server is expecting.

On the server side I can see that the requests are failing because the expected "api_key" header is missing and it is throwing an HTTP 401 which I get back on the client.

Please advise if this is a bug or am I missing something.

**Comment by fehguy** [comment]
When you define your `securityDefinitions`, you must apply them to the definition.  If you want `api_key` applied to _all_ operations, add this at the top level:

```
"security": {
  "api_key": []
}
```

then the api_key will be applied to all operations.

**Comment by codepandy** [comment]
@ritwik-dell 
Hi,
Did you solve the problem? I meet the same problem.

**Comment by codepandy** [comment]
I have solved the problem,the parameter of "content-type" must be included in header.
the below is the key code:
```
          {
            "in": "header",
            "name": "content-type",
            "description": "content-type",
            "required": true,
            "type": "string",
            "default": "application/x-www-form-urlencoded"
          }
```

**Comment by webron** [comment]
@codepandy you should never specify `content-type` as a header. That's why you have the the `consumes` property.

**Comment by codepandy** [comment]
@webron 
I think so,I have set the ```consumes``` property,but the request is error.

**Comment by longseespace** [comment]
I have exactly the same problem. No matter what I did, the header was never sent.

```
{
  paths: {...},
  definitions: { },
  swagger: "2.0",
  schemes: [],
  tags: [],
  basePath: "",
  docsPath: "/docs",
  consumes: ["application/json"],
  produces: ["application/json"],
  info: { },
  ignore: {
    tags: [ ]
  },
  security: {
    jwt: [ ]
  },
  securityDefinitions: {
    jwt: {
      type: "apiKey",
      name: "Authorization",
      in: "header",
      required: true
    }
  }
}
```

**Comment by FrederikNygaardSvendsen** [comment]
@longseespace I have the same problem as well. Did you ever find a solution?

**Comment by longseespace** [comment]
@FrederikNygaardSvendsen I don't remember the details but seems that this config works for me

```
{
    docsPath: '/docs',
    uiIndex: true,
    security: {
      name: 'jwt',
      type: 'apiKey',
      in: 'header',
    },
    securityDefinitions: {
      jwt: {
        type: 'apiKey',
        name: 'Authorization',
        in: 'header',
      },
    }
}
```

**Comment by longseespace** [comment]
Sorry it was the config for `feathers-swagger`. You can read the code here https://github.com/feathersjs-ecosystem/feathers-swagger/blob/c910094b917f775b23f4a2eed7bd9394e68e37dd/src/index.js#L15

Hope this can help

**Comment by Meera9** [comment]
@FrederikNygaardSvendsen this is working for me https://github.com/swagger-api/swagger-ui/issues/5646#issuecomment-1782597849
