### ISSUE TITLE
Problem with special chars in swagger json files

### ISSUE THREAD

**Issue by vguna** [swagger-api/swagger-ui#2496]
Hi.

I'm using swagger-ui 2.1.4. It seems there is a problem with special characters like german umlauts in the swagger json file. I simply took the swagger pet store example json and put some german umlauts to an exsting description like so:

`
"description": "pet status in the store öäüßÖÄÜ"
`

Invoking the swagger ui leads to the following error message:

`Can't read from server. It may not have the appropriate access-control-origin settings.`

Removing the umlauts, make it work again.
Any clues what might be wrong?

**Comment by webron** [comment]
Should no longer be an issue with 3.X.
