### ISSUE TITLE
Add support for version in path

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-ui#2498]
Suppose we have
> http://localhost:9001/api/v1/user
> http://localhost:9001/api/v2/user

I want to see api for version 1 and version 2 separately, not in the same documentation.
![hbeln](https://cloud.githubusercontent.com/assets/4563564/20270280/247a3f5a-aa8f-11e6-8259-907aeb4e3bc5.png)

**Comment by webron** [comment]
To do that, either use different spec files for each version, or use a different tag for each version.
