### ISSUE TITLE
Javascript error when "Try it out" POST method

### ISSUE THREAD

**Issue by korest** [swagger-api/swagger-ui#2500]
I'm using swagger-ui 2.2.6 version.
When I'm trying to do POST request with json BODY I'm getting error:
![error](https://cloud.githubusercontent.com/assets/8270886/20309496/d3f2e998-ab50-11e6-91e2-0a9101230958.png)
How can I fix it?

**Comment by webron** [comment]
Please provide a copy of your spec and a mention of which operation triggers the issue.

**Comment by korest** [comment]
Nothing special. I have next file with specs:

```
swagger: "2.0"
info:
  title: API
  description: API
  version: "1.0.0"
basePath: /
consumes:
  - application/json;charset=UTF-8
produces:
  - application/json;charset=UTF-8

tags:
  - name: Test

paths:
  /tests:
    post:
      tags:
        - Test
      summary: Create test
      description: Create test
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Test"
      parameters:
        - in: body
          description: json
          required: true
          schema:
            $ref: "#/definitions/TestRequest"

definitions:
  TestRequest:
    description: Test
    properties:
      testId:
        type: string
        description: Test unique indetifier
        example: "1"
    required:
      - testId
  Test:
    description: Test
    properties:
      id:
        type: string
        description: Test unique identifier
        example: "1"


```

After adding some body I click on "Try it out" on swagger-ui and nothing happens, I can see above error in console and progress bar on the right in infinite loop. For example without request body only with header parameter "Try it out" works.

**Comment by webron** [comment]
Your body parameter is missing a `name`, making it an invalid spec.

**Comment by korest** [comment]
Thanks sorry for bothering you. Thought that spec would not render with errors.
