### ISSUE TITLE
Swagger integration with protobuf

### ISSUE THREAD

**Issue by daniogao** [swagger-api/swagger-ui#2501]
Hi, I'm integrating swagger with protobuf. I found a solution here https://coreos.com/blog/gRPC-protobufs-swagger.html, a proxy between swagger ui and backend server should be set up. This is not exactly what I want. Any suggestion? Thanks!

**Comment by fehguy** [comment]
perhaps you can share what you're after?

**Comment by daniogao** [comment]
Ideally I want swagger takes a proto and json data as input. Then it serializes the data into protobuf bytes and sends to server. Finally it gets protobuf bytes result from backend server and derializes to json format. You can have a reference to #1669. How can I make swagger support content type of protobuf. Thanks!

**Comment by webron** [comment]
Closing as this is out of our capacity. If anyone would like to submit a PR to add support for this, we'd be happy to review it.

**Comment by softboy99** [comment]
we also need it
