### ISSUE TITLE
Missing linebreaks in Model view since 2.2.3

### ISSUE THREAD

**Issue by Vayu** [swagger-api/swagger-ui#2504]
Model rendering looks a bit broken in all versions since v2.2.3. Some line breaks are missing and enums also look very strange. Looks like <br/> is being lost/stripped. Might be related to #2492

See below screenshots with 2.2.2 (above) and 2.2.3 (below)
![swaggerui2 2 2](https://cloud.githubusercontent.com/assets/626781/20393950/21599108-acde-11e6-9289-89862c617052.png)
![swaggerui2 2 3](https://cloud.githubusercontent.com/assets/626781/20393953/253d1466-acde-11e6-8c12-c14837635a39.png)

**Comment by fehguy** [comment]
Yes, this was probably an unwanted side effect from the security fixes put in to avoid XSS.  Can you please try #2505 to see if that fixes it for you?

**Comment by Vayu** [comment]
@fehguy it is my PR and yes it fixes this issue for me
