### ISSUE TITLE
Expose setting the markdown settings from marked.js

### ISSUE THREAD

**Issue by shabda** [swagger-api/swagger-ui#2509]
Swagger UI version 2.2.6
`Marked` exposes a number of settings, see https://github.com/chjj/marked#usage.

There should be an option to pass on these while creating the `SwaggerUi` object. In particular the `breaks` option will enable linebreaks in specs showing up correctly while rendered.

**Comment by fehguy** [comment]
This makes sense--do you have time to contribute a PR?

**Comment by webron** [comment]
Using a different library now... which is also going to change soon.
