### ISSUE TITLE
Image response not shown (after version >5.4)

### ISSUE THREAD

**Issue by NochnoiAngel** [swagger-api/swagger-ui#2512]
When reporting a bug, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue

**Comment by webron** [comment]
There's no version 5.4. is 2.2.6.

**Comment by fehguy** [comment]
2.2.7 has improved image rendering.  If you still have an issue (or want to write version 5.4 for us!) please open a new ticket.
