### ISSUE TITLE
Is there any extension links in swagger ui code ?

### ISSUE THREAD

**Issue by tnpradeep** [swagger-api/swagger-ui#2515]
When reporting a bug, please provide the following details:
- swagger-ui version : 2.2
- a swagger file reproducing the issue :

I am using swagger ui and i need to customize the behavior of try it out.
Instead of directly hitting the endpoint I need the request to go through my code. So instead of pushing my code in between the core swagger ui, I want to know if I can extend the functionality outside the swagger ui component.

Above scenario is an example, I know its not a proper use case for swagger ui.
I have some requirements where instead of using default behavior if i need to customize or define my own behavior how it can be achieved.

Externalizing my customization helps in easy upgrade of swagger UI releases in future.

Thank you.

**Comment by webron** [comment]
What kind of functionality?

**Comment by tnpradeep** [comment]
We want to use our own themes
Flexible Headers addition
We want the try out calls to go through our servlet layer, so we can do metering of calls.
And We need to gracefully handle session as our application needs users to login to perform any actions.

So extension points helps.

**Comment by fehguy** [comment]
Yes, please read up on how you extend swagger-ui via the communication library, swagger-js.  There you can override the hosts, ports, etc., and provide request/response interceptors to route traffic to different lcoations.
