### ISSUE TITLE
swagger-ui: swagger-ui.min.js:1 Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by sbelvadi** [swagger-api/swagger-ui#2516]
Not able to view the details of the operations in the REST webservice.
When I access the http://localhost:8080/<context root>/v2/api-docs - I am able to list the REST ws operations or methods.

Inspecting the Console (Chrome developer tools)

swagger-ui.min.js:1 Uncaught TypeError: Cannot read property 'type' of undefined(…)(anonymous function) @ swagger-ui.min.js:112 @ swagger-ui.min.js:1f @ handlebars-2.0.0.js:27(anonymous function) @ handlebars-2.0.0.js:279 @ swagger-ui.min.js:1f @ handlebars-2.0.0.js:27(anonymous function) @ handlebars-2.0.0.js:27main @ swagger-ui.min.js:2e @ handlebars-2.0.0.js:27render @ swagger-ui.min.js:10addParameter @ swagger-ui.min.js:10render @ swagger-ui.min.js:10addOperation @ swagger-ui.min.js:11render @ swagger-ui.min.js:11addResource @ swagger-ui.min.js:10render @ swagger-ui.min.js:10render @ swagger-ui.min.js:10options.success @ swagger-ui.min.js:10y.buildFromSpec @ swagger-ui.min.js:2a.finish @ swagger-ui.min.js:3a.resolve @ swagger-ui.min.js:2response @ swagger-ui.min.js:2l @ swagger-ui.min.js:2e.on.response @ swagger-ui.min.js:2(anonymous function) @ swagger-ui.min.js:2f.callback @ swagger-ui.min.js:10(anonymous function) @ swagger-ui.min.js:9r.emit @ swagger-ui.min.js:10n.onreadystatechange @ swagger-ui.min.js:10

**Comment by webron** [comment]
Can't help you without the spec.

**Comment by sbelvadi** [comment]
I am sorry. This is the first time I am using swagger-ui. Here is what I have in my POM for spring REST ws. What is strange is I have another web service (Spring) and I am able to use the same version and swagger-ui works. Not sure what the error means or what the issue could be..
Thanks for looking into this

	
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.5.0</version>
		</dependency>

		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.5.0</version>
		</dependency>

**Comment by webron** [comment]
Swagger-ui loads a json or a yaml file generated by Springfox and renders it. Without that file, we cannot further investigate the issue.

**Comment by sbelvadi** [comment]
Trying to find the file. Is there a default location of the file and a default name.

**Comment by webron** [comment]
There is, but Springfox does something different. You'd need to check their docs.

**Comment by sbelvadi** [comment]
Trying to get some help with
https://github.com/swagger-api/swagger-ui/issues/2548
