### ISSUE TITLE
markdown stripping xml tags inside code block

### ISSUE THREAD

**Issue by kkarabian** [swagger-api/swagger-ui#2518]
When inserting an xml code block into a description field, the xml tags are removed.  I end up with bare text.  See below for example file.

When reporting a bug, please provide the following details:
- swagger-ui version
v2.2.6
- a swagger file reproducing the issue
swagger: '2.0'
info:
  title: Ares
  description: |
    Asynchronous REport Scheduler providing a simple API for scheduling reports and being alerted when they are completed.

    ```
    <paper_text>When a source and display are <match_group slot="1" id="0"><match>connected, the source first</match> queries the display's 
    <match>capabilities by reading the monitor EDID</match></match_group> block over an IC link.</paper_text>
    ```

**Comment by kkarabian** [comment]
Please don't punt!

**Comment by approaching236** [comment]
Still getting this issue, have you discovered a workaround?

**Comment by webron** [comment]
This is just how markdown works - it will try to render html elements as html, but it doesn't really tell the difference between actual html elements or xml elements or whatnot. So it will be treated like an HTML page, and the elements would 'disappear'. If you want to show those characters, you'd need to escape them just like you would in an html document.
