### ISSUE TITLE
Response examples override examples in other HTTP methods

### ISSUE THREAD

**Issue by commscheck** [swagger-api/swagger-ui#2520]
# Steps to reproduce

Create a valid Swagger YAML file with a single path with multiple HTTP methods (e.g. POST and PUT). For each method, provide a response with the same code but different examples.

# Expected behaviour

When displaying the section for each HTTP method for a path, the examples relating to that HTTP method are shown.

# Actual behaviour

The examples from the first HTTP method is duplicated into the other HTTP method sections. The examples for the other HTTP methods cannot be viewed.

# Notes

- Examples are displayed correctly in the [Swagger editor](http://editor.swagger.io/).
- Swagger UI versions tested: 2.2.2, master (46fbae2).

# Full YAML reproducing the issue
https://gist.github.com/commscheck/b67525a136cd41797fff88759f4657d2

# Example snippet

```yaml
paths:
  /foo/bar:
    post:
      [...]
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/responseObject'
          examples:
            "My POST Example":
              [...]
            "My second POST Example":
              [...]
    put:
      [...]
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/responseObject'
          examples:
            "My PUT Example":
              [...]
            "My second PUT Example":
              [...]
```

**Comment by webron** [comment]
Okay, this is one of the best bug reports we've ever received. Thank you.

**Comment by fehguy** [comment]
I was hoping that @webron's enthusiasm would mean he'd fix this.

OK looks like internally the example is being connected to the model definition.  So the example for `responseObject` is setting the example for `responseObject` in _general_.  It should be kept separate for each instance of `responseObject`.

@webron is that the best bug report comment you've seen?

**Comment by webron** [comment]
@fehguy no.

**Comment by fehguy** [comment]
OK digging in a bit more, I see the issue.

First off, there is a bug where the example is copied to the model reference.  That needs to be fixed.

However, @commscheck you are using the `examples` section incorrectly.  While it does accept a plain object, the intention from the specification is that the `examples` contains content-type keys and object values.  For example:

```yaml
responses:
  '200':
    description: A
    schema:
      $ref: '#/definitions/A'
    examples:
      application/json:
        status: Winning!
```

If using the keys like this, you'll see the behavior is correct.  I'll look at the reference fix though.  (still waiting on some recognition from @webron )

**Comment by fehguy** [comment]
Fixed by https://github.com/swagger-api/swagger-ui/commit/49a1169878b50ccb4d237dedf22ac472b4c2b5d6
