### ISSUE TITLE
Cannot add custom header to request to fetch JSON

### ISSUE THREAD

**Issue by i300543** [swagger-api/swagger-ui#2522]
We need to generate docs for our  API, which uses older swagger version (1.2)

our api has a /docs path, which returns the following json with GET:
{
    "apiVersion": "1.0",
    "swaggerVersion": "1.2",
    "apis": [
        {
            "path": "/workspace",
            "description": "Workspace manager"
        },
        {
            "path": "/admin/builder",
            "description": "Builder manager (admin)"
        },
        {
            "path": "/analytics",
            "description": "Analytics manager"
        },
        {
            "path": "/builder",
            "description": "Builder manager"
        },
        {
            "path": "/auth",
            "description": "Authentication manager"
        },
        {
            "path": "/runner",
            "description": "Runner manager"
        },
        {
            "path": "/profile",
            "description": "User profile manager"
        },
        {
            "path": "/admin/runner",
            "description": "Runner manager (admin)"
        },
        {
            "path": "/user",
            "description": "User manager"
        },
        {
            "path": "/project",
            "description": "Project manager"
        }
    ],
    "info": {
        "title": "Eclipse Che REST API",
        "description": "",
        "termsOfServiceUrl": "",
        "contact": "",
        "license": "Eclipse Public License v1.0",
        "licenseUrl": "http://www.eclipse.org/legal/epl-v10.html"
    }
}

--------------------------------------------------------------------------
the trouble is this: to get it u need to be authenticated with bearer token.
when i try to get the json with rest client while providing header:
Authorization : Bearer <token_value> 
i get the json back

but i cannot seem to manage swagger-ui to add the header to the request.

i was trying to follow this guide: https://github.com/swagger-api/swagger-ui#custom-header-parameters---for-basic-auth-etc
but still it does not work.

i am modifying index.html file inside dist folder as follows:

...
  window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            // initOAuth({
            //   clientId: "your-client-id",
            //   clientSecret: "your-client-secret-if-required",
            //   realm: "your-realms",
            //   appName: "your-app-name",
            //   scopeSeparator: " ",
            //   additionalQueryStringParams: {}
            // });
          }

          if(window.SwaggerTranslator) {
            window.SwaggerTranslator.translate();
          }
        },
        onFailure: function(data) {
          log("Unable to Load SwaggerUI");
        },
        docExpansion: "none",
        jsonEditor: false,
        defaultModelRendering: 'schema',
        showRequestHeaders: true
      });

    

      window.swaggerUi.load();
        var token = "Bearer <token_value>";
      
      window.swaggerUi.api.clientAuthorizations.add("bearer", new    SwaggerClient.ApiKeyAuthorization("Authorization", token, "header"));
      function log() {
        if ('console' in window) {
          console.log.apply(console, arguments);
        }
      }
  });
  </script>

does this "bearer" key needs to be defined in some other place ?
i have seen people say it needs to be defined in securityDefinitions,
is that part of the json that returns from the API ? and if it is, i cannot access it without authentication, and i need the header for authentication.

i seem confused :)
I am using swagger-ui cloned from master branch (latest)
Please help if you are able,

Thanks in advance
Sergey

**Comment by fehguy** [comment]
Add your authorizations in the `onComplete` block
