### ISSUE TITLE
swagger-ui not consistent with swagger editor preview

### ISSUE THREAD

**Issue by sebastianovide** [swagger-api/swagger-ui#2523]
using the same [swagger.yaml](https://api.flyflock.io/swagger.yaml), just compare the difference between the  [swagger editor](http://editor.swagger.io/#/?import=https://api.flyflock.io/swagger.yaml ) and the [swagger ui ](http://petstore.swagger.io/?url=https://api.flyflock.io/swagger.yaml )

any ideas ?

**Comment by Jfach** [comment]
+1

**Comment by webron** [comment]
Yes, they are different projects and have different views.
