### ISSUE TITLE
Json data not parsed in response body (release 2.2.7)

### ISSUE THREAD

**Issue by jiveshsg** [swagger-api/swagger-ui#2528]
The following is displayed in Response Body:

> can't parse JSON.  Raw result:
> 
> [object Blob]

Was working fine till v2.2.6
Checked the Content-Type response header, its properly sent as application/json.

**Comment by fehguy** [comment]
Please try 2.2.7, released tonight

**Comment by jiveshsg** [comment]
Tried already, its the bug in 2.2.7 only, thats why reported. Tried master as well (same bug).
Was fine till 2.2.6

**Comment by fehguy** [comment]
Hmm can you please share your spec?

**Comment by fehguy** [comment]
well @jiveshsg it is indeed broken.  Fix on the way.
