### ISSUE TITLE
throwing exception "failed to execute createObjectUrl" when rendering contentType image/png 

### ISSUE THREAD

**Issue by stojy** [swagger-api/swagger-ui#2530]
swagger-ui version.. 2.2.6 and 2.2.8

![image](https://cloud.githubusercontent.com/assets/11408611/20622180/969cf82e-b33c-11e6-9016-98a950964426.png)

Related issues..
https://github.com/swagger-api/swagger-ui/issues/2470
https://github.com/abelsilva/swaggerwcf/issues/52

**Comment by fehguy** [comment]
Please show your request headers

**Comment by stojy** [comment]
Headers when using swagger - doesn't work.
![image](https://cloud.githubusercontent.com/assets/11408611/20654095/d4f6ba0e-b550-11e6-902a-8927a3999f1c.png)

Headers when using chrome url directly (no swagger) - works.
![image](https://cloud.githubusercontent.com/assets/11408611/20654194/e781340a-b551-11e6-8106-2f34c52a163c.png)

**Comment by fehguy** [comment]
You're requesting `application/json` and getting `image/png`.  Change your definition to allow `produces: image/png`

**Comment by stojy** [comment]
Thanks, explicitly setting the request header type (via the produces) has fixed the issue.

However, it's worth noting..
1. This appears to be a breaking change from an earlier version of swagger-ui v2.1.4 (as used swaggerWcf v1.1.5).  The earlier swagger-ui handled the unexpected response content type by automatically making an additional request with a compatible accept type.
![image](https://cloud.githubusercontent.com/assets/11408611/20740675/fd2cfe06-b6ff-11e6-92b0-e2525e0c42ac.png)
![image](https://cloud.githubusercontent.com/assets/11408611/20740693/20104590-b700-11e6-812f-656c25781e52.png)


2. Perhaps swagger-ui should handle the case where the content type in the response header doesn't match the request header?  i.e. similar to chrome where the response type is soley used to render the output.  Or at a minimum, show a useful error message instead of the 'infinite swirly'.

**Comment by fehguy** [comment]
The double calls were creating their own issue. Can you please open an issue for the point about the infinite loading throbber?
