### ISSUE TITLE
[Feature] Implement OAuth2 scopes all/none toggling in the auth dialog

### ISSUE THREAD

**Issue by frol** [swagger-api/swagger-ui#2531]
I have over a dozen of scopes in my project and selecting every single of them (especially during API debug) is a tedious and boring task.

I would love to have a way to either toggle all scopes ON/OFF at once, or default them to all-enabled by default, or even have a configuration to specify which scopes should be enabled by default.

/cc @MugeSo

**Comment by pwielgolaski** [comment]
:thumbsup: I would like to have selected by default

**Comment by fehguy** [comment]
I suggest that this becomes a configuration rather than a default.  I'd be happy to pull that in.

**Comment by pwielgolaski** [comment]
How could we make it configurable? 
Happy to implement it as option.

**Comment by fehguy** [comment]
Best if we can pass an option when initializing swagger-ui:

https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L52-L66

something like `autocheckScopes: true`?

**Comment by webron** [comment]
Closing as no contributions came in. If anyone would like to submit a PR, we'd be happy to review it.
