### ISSUE TITLE
Swagger UI - Nested external references not being resolved

### ISSUE THREAD

**Issue by iq-dot** [swagger-api/swagger-ui#2536]
I have searched the past issues and noticed this bug has been on/off and has appeared multiple times.

I am using the latest version of the schema and my issue is that nested external $ref is not being resolved (I am testing locally):

```
  /data:
    get:
      tags:
        - atm
      description: 'Get some data'

      parameters:
        - $ref: '#/parameters/userAgent'

      responses:
          200:
            description: Successful response with data
            headers:
              Cache-Control:
                type: string
                description: Describes how long this response can be cached
            schema:
              type: array
              items:
                $ref: 'http://localhost:8000/schema/user.yaml'
```

User.yaml:

```
type: object
properties:
  name:
     type: string
  address:
     $ref: 'http://localhost:8000/schema/address.yaml'
```

So the issue is that address.yaml DOES NOT get resolved but user.yaml DOES get resolved.

I checked the network tab and only user.yaml is downloaded. I am using the lastest version from master.

**Comment by BiteBit** [comment]
+1

**Comment by sardorv** [comment]
+1

**Comment by vortechs2000** [comment]
+1

**Comment by webron** [comment]
This should no longer be an issue with 3.X.

**Comment by SoumenDass** [comment]
This is still happening with Openapi 3.0 (I pulled swagger-ui from github master branch). 

main yml
```
content:
  application/json:
    schema:
      $ref: 'SubSchema.yml'
```

SubSchema.yml
```
type: object
properties:
     flag:
        schema:
          $ref: '#/components/schemas/yn_string'
components:
    schemas:
         yn_string:
         type: string
         enum:
            - Y
            - N
```

The model in swagger ui shows "flag" as:
```
restrict_to_enum	{
}
```
nstead of showing it as enum.

**Comment by webron** [comment]
@SoumenDass the SubSchema.yml file is invalid (indentation is wrong). If you'd like us to test it, I'd suggest filing a new ticket and providing full API definitions and not snippets.
