### ISSUE TITLE
Incorrect api key sent

### ISSUE THREAD

**Issue by chriswebster** [swagger-api/swagger-ui#2537]
When reporting a bug, please provide the following details:
- swagger-ui version 2.2.8
- a swagger file reproducing the issue - https://gist.github.com/chriswebster/56678c8d3fbea09c3f8a0c5b26a32435

Using the above swagger file and the below steps:

1. Click the red ! for resource1 and add key "1" using the authorize button, notice the request curl has --header 'Authorization: 1' 
2. Click the red ! for resource2 and add key "2" using the authorize button, notice the request curl has --header 'Authorization: 2'
3. Use the "Authorize" green button next to the text box on top of the user interface to logout from from the api key in step 1. 
4. When trying to use resource1, even after adding back the api key "1" as in step 1, the curl request will continually show --header 'Authorization: 2' , even though the blue ! when selected has key "1".

**Comment by webron** [comment]
This should no longer be an issue with 3.X.
