### ISSUE TITLE
definition properties: format, minimum, maximum, example (at least) all missing from documentation

### ISSUE THREAD

**Issue by readnotify** [swagger-api/swagger-ui#2539]
The documentation is omitting lots of useful information that is present in the API.
for example: here is some documentation output:

errorModel {
 errorCode:	number *
 errorMessage:	 string *
 errorDescription:	string *
}

And as you can see - the definition is *significantly* more rich:

definitions:
  errorModel:
    type: object
    required:
    - errorCode
    - errorMessage
    - errorDescription
    properties:
      errorCode:
        type: number
        format: float
        minimum: 100.0
        maximum: 600.0
        example: 400.1
      errorMessage:
        type: string
        example: missing recipientEmailAddresses
      errorDescription:
        type: string
        example: You need to supply one or more recipient email addresses inside the recipientEmailAddresses property, but you did not supply any

Please update the doc generator so it uses all the richness of the definitions!  Developers *need* to know that stuff!!!

**Comment by webron** [comment]
See #993.
