### ISSUE TITLE
Unhelpful and suspect error "instance failed to match at least one required schema among 2"

### ISSUE THREAD

**Issue by readnotify** [swagger-api/swagger-ui#2541]
The UI is simply displaying that error - google suggests that the payload carrying that error has significantly more detail, except the UI is not rendering any of it: there needs to be a way to see the entire error, not just this small description.

And, on the subject of the error itself: it suddenly started today, I don't think it's correct - all my backed-up YML produces the same error now, but none of them had errors when I backed them up last week.

... and on the subject of the error wording: that is a totally useless description.  I have no idea whatsoever what it might mean, or what it's referring to, or why.  This is a textbook example of "how never to write an error message".  Please find what issued that error, and adjust it to include something useful that we can find/reference/understand!

**Comment by fehguy** [comment]
I just don't think anyone can help without more information than you're giving.  And I believe you're talking about swagger-editor, not swagger-ui.

If you'd like help or have a general idea, provide some details please.
