### ISSUE TITLE
curl or request with cookie

### ISSUE THREAD

**Issue by a373953795** [swagger-api/swagger-ui#2543]
HI
 At that time I used it out try, I need to carry cookie, but found that the generation of curl or request  are not  in my expectations of the cookie information,
![qq 20161130104234](https://cloud.githubusercontent.com/assets/18180196/20737763/dd74cc1c-b6e9-11e6-9297-d77fc328f123.png)
How to do it?

**Comment by fehguy** [comment]
It's not supported by he specification so not implemented. You'll have to do it on your own, sorry
