### ISSUE TITLE
"try it out" button should not be enabled until required authorizations is entered by user

### ISSUE THREAD

**Issue by thomasvng** [swagger-api/swagger-ui#2544]
When reporting a bug, please provide the following details:
- swagger-ui version
   2.2.8
- a swagger file reproducing the issue
  https://gist.github.com/chriswebster/56678c8d3fbea09c3f8a0c5b26a32435

Load up the swagger file into swagger-ui.  Expand GET /resource 1.  It requires authorizations and the ui shows a red "!".  the "try it out" button should not be enabled until red "!" becomes blue (authorize info is entered by user).

**Comment by lomori** [comment]
Actually I don't agree with that. There are cases when you want to try it out even before authorization, the obvious one being to verify that the API endpoint is indeed protected and/or if it's returning the proper error code and description message.

**Comment by webron** [comment]
Right. In the future we may offer two testing modes, 'strict' and 'go crazy', but for now, this is not an issue.
