### ISSUE TITLE
Error when OAuth loginEndpoint contains a query parameter

### ISSUE THREAD

**Issue by gonzalad** [swagger-api/swagger-ui#2546]
Hello,

I'm using swagger UI with OAuth enabled and using the OAuth authorization code flow.
I'm using a authorizationUri containing a query parameter, such as : http://localhost:9080/oidc/idp/authorize?claims=roles.

Problem is all code in swagger ui just appends ?<queryParam> to authorizationUri.
See for instance https://github.com/swagger-api/swagger-ui/blob/95553a597b4a55d96c2139b975bdadb700533966/lib/swagger-oauth.js#L155

So, I end up with a double ?, like (look at ?claims=roles?):
http://localhost:9080/oidc/idp/authorize?claims=roles?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A7777%2Fwebjars%2Fspringfox-swagger-ui%2Fo2c.html&realm=oauth2schema&client_id=GMh7j7-6OZaoyw&scope=openid&state=oauth2schema

- swagger-ui version : 2.2.2
- swagger file reproducing the issue is attached
[swagger-oauth-query-param.txt](https://github.com/swagger-api/swagger-ui/files/622345/swagger-oauth-query-param.txt)

**Comment by webron** [comment]
Closing as should not be relevant in the new UI. If you still experience the problem, please add a comment or file a new ticket.
