### ISSUE TITLE
mismatch in request header accept type and response header content-type causes infinite loading throbber

### ISSUE THREAD

**Issue by stojy** [swagger-api/swagger-ui#2547]
Refer details in #2530.  Swagger-ui 2.2.8.

Recommendations..
1. Change swagger-ui to show an error message (e.g. "unexpected response content-type, have you specified the correct 'produces:' type(s)") instead of the infinite throbber.
2. Change swagger-ui to show a warning message (e.g. same message as error), but correctly render the content as specified in the response header.

**Comment by webron** [comment]
Should behave differently with 3.X.
