### ISSUE TITLE
Try-Out request never sent if OAuth authenticated

### ISSUE THREAD

**Issue by atomfried** [swagger-api/swagger-ui#2550]
Hello there,

I'm having a weird issue with swagger-ui 2.2.5:

* I click the try out button and get 403 as expected.
* I aquire an oauth access token.
* I click the try out button... and the request times out.

My API is logging requests and the authenticated request actually never reaches the server.  If I copy the curl command from the first request and supply a token manually it works fine.

In my understanding the try out request are made by the browser and since the first request works, it should not be a network issue, right?

I'm quite mystified, does anyone have a thought on this?

Take care

M

**Comment by fehguy** [comment]
Can you please retest with the latest master?

**Comment by fehguy** [comment]
Reopen if you're still having an issue.  Verified to be working in the petstore sample on master.
