### ISSUE TITLE
Allow password to be blank for basicAuth form

### ISSUE THREAD

**Issue by patcon** [swagger-api/swagger-ui#2555]
Sometimes an API will use the username for an API key, and leave password blank. It would be great if the project could support documenting these APIs. (The form currently just won't submit.)

https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/BasicAuthModel.js

**Comment by patcon** [comment]
Or maybe this is best implemented as a change to the spec, with "apiKey" getting a new option for the "in" key: "username" (and perhaps "password", alternatively).

Any thoughts on where best to tackle this?

**Comment by fehguy** [comment]
This should be fixed now.
