### ISSUE TITLE
map dataType is treated as inline

### ISSUE THREAD

**Issue by dr3s** [swagger-api/swagger-ui#2564]
When reporting a bug, please provide the following details:
- swagger-ui version 2.2.8
- a swagger file reproducing the issue : https://gist.githubusercontent.com/anonymous/9ca4b9eeca273d64e2e3598aea458a08/raw/8a016825e15ec9fd3029c6be8575d46b64e474f9/test.json

itemViews is a map dataType that seems to match the spec yet it renders as an inline model.  It is explicitly an object with additionalProperties ref of ItemView

ItemView is in the definitions but not rendered in the model for the Item.itemViews map

**Comment by dr3s** [comment]
maybe this should be in swagger-js instead.  just let me know

**Comment by dr3s** [comment]
#913

**Comment by dr3s** [comment]
https://github.com/swagger-api/swagger-js/issues/909

**Comment by webron** [comment]
Should no longer be an issue in 3.X.
