### ISSUE TITLE
Response Model Schema is coming as empty object in Swagger - C# | Swashbuckle

### ISSUE THREAD

**Issue by JerryGoyal** [swagger-api/swagger-ui#2573]
This is my API:

    /// <summary>
            /// Gets activity logs.
            /// </summary>
            /// <param name="locationId">Location id.</param>
            /// <param name="filter">Activity log filter options.</param>
            [CHAPIAuthorize()]
            [ResponseType(typeof(ActivityLogResponse))]
            public async Task<HttpResponseMessage> FetchActivityLogs(int locationId, ActivityLogFilterOptions filter)
            {
                try
                {
                    var response = await _activityLogLogic.GetActivityLogs(CHIdentity.User, locationId, filter);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                catch (HttpRequestException ex)
                {
                    return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, ex.Message + "\n" + ex.InnerException.Message);
                }
                catch (Exception ex)
                {
                    return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, ex.Message);
                }
            }

Defination of `ActivityLogResponse` class:

     public class ActivityLogResponse
        { 
           public List<ActivityLogMessage> ActivityLogs { get; set; }
           Logs { get; set; }
        }

In swagger JSON ***responses*** `"$ref": "#/definitions/Object"` is coming instead of `ActivityLogFilterOptions`

See `Responses` in following Swagger Json:

     "/api/locations/{locationId}/FetchActivityLogs": {
                "post": {
                    "tags": [
                        "ActivityLog"
                    ],
                    "summary": "Gets activity logs.",
                    "operationId": "ActivityLog_FetchActivityLogsBylocationId-dee1fe1d-a83d-49bd-9b18-b78dd048f18dfilter-eb6017e4-d009-4182-8bb5-a1b8fc50af63",
                    "consumes": [
                        "application/json",
                        "text/json",
                        "application/xml",
                        "text/xml",
                        "application/x-www-form-urlencoded"
                    ],
                    "produces": [
                        "application/json",
                        "text/json",
                        "application/xml",
                        "text/xml"
                    ],
                    "parameters": [
                        {
                            "name": "locationId",
                            "in": "path",
                            "description": "Location id.",
                            "required": true,
                            "type": "integer",
                            "format": "int32"
                        },
                        {
                            "name": "filter",
                            "in": "body",
                            "description": "Activity log filter options.",
                            "required": true,
                            "schema": {
                                "$ref": "#/definitions/ActivityLogFilterOptions"
                            }
                        }
                    ],
                    "responses": {
                        "200": {
                            "description": "OK",
                            "schema": {
                                "$ref": "#/definitions/Object"
                            }
                        }
                    },
                    "deprecated": false
                }
            },

![image 2](https://cloud.githubusercontent.com/assets/7106086/21390059/da71dbaa-c7aa-11e6-9c47-e662f6f35dc0.png)

How to load `ActivityLogFilterOptions` here instead of `{}`?

**Comment by webron** [comment]
This is not an issue with swagger-ui but with the library that generates your swagger.json. Please open the ticket on Swashbuckle.
