### ISSUE TITLE
Swagger cannot resolve external schema files with JSON Reference $ref: '/path/to/file.json'

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#2574]
Given the Open API document below, swagger-ui version 2.2.8 cannot resolve the first external schema via a JSON Reference. 
```
          schema:
            $ref: "/schema/resource.json"
```
Instead the Swagger UI shows an error on resource1 but the $ref works OK on resource2:

![open-api-ref](https://cloud.githubusercontent.com/assets/545944/21400529/8d403600-c77e-11e6-993a-5302e22d9e2a.png)

Note also that the HTML markup meant to highlight the error is visible in Swagger UI.

I'm running this on localhost: 

http://localhost/swagger-ui-dev/?url=http://localhost/apis/testApi/swagger.yaml

As per [JSON Reference draft-pbryan-zyp-json-ref-03](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03)

*If the URI contained in the JSON Reference value is a relative URI, then the base URI resolution MUST be calculated according to [RFC3986](https://tools.ietf.org/html/rfc3986#section-5.2), section 5.2.  Resolution is performed relative to the referring document.* 

the reference "/schema/resource.json" should resolve to "http://localhost/schema/resource.json" (which works in resource2 in the example)

The complete schema reference 
```
  $ref: "http://localhost/schema/resource.json"
```
works in `/resource2`, as does a relative reference in `/resource3`, 
```
  $ref: "resource.json"
```
(For the third case, the `resource.json` file was copied to sit next to the `swagger.yaml`, i.e. in `http://localhost/apis/testApi/resource.json`)

Being able to resolve a reference such as  
```
  $ref: "/schema/resource.json"
```
is important for Open API document portability and shared schema files - when moving the Open API document and schema files from localhost to dev/test/prod hosts, I should be able to use relative URIs and not have to rewrite URIs.

The full Open API document is
```
swagger: "2.0"
info:
  title: "Test API"
  description: "Demonstrate problem with external schema"
  version: "1"
basePath: "/testApi"
paths:
  /resource1:
    get:
      summary: "Get a resource"
      description: "The schema reference $ref: \"/schema/resource.json\" does not work"
      produces:
      - "application/json"
      responses:
        200:
          description: "The result"
          schema:
            $ref: "/schema/resource.json"
  /resource2:
    get:
      summary: "Get a resource"
      description: "The schema reference $ref: \"http://localhost/schema/resource.json\" works"
      produces:
      - "application/json"
      responses:
        200:
          description: "The result"
          schema:
            $ref: "http://localhost/schema/resource.json"
  /resource3:
    get:
      summary: "Get a resource"
      description: "The schema reference $ref: \"resource.json\" works"
      produces:
      - "application/json"
      responses:
        200:
          description: "The result"
          schema:
            $ref: "resource.json"
```

and sample the schema (at `http://localhost/schema/resource.json`) is
```
{
    "id" : "http://localhost/schema/resource.json",
    "title" : "A resource",
    "properties": {
        "id": {
            "type": "string",
            "description": "The resource ID"
        }
    }
}

```

**Comment by BastienAr** [comment]
Up

Same problem here, changing all the uri to match files absolute uri is a pain in the ass.

**Comment by webron** [comment]
I've tested this with the new UI and it seems to work as expected. Please let us know if the issue persists.
