### ISSUE TITLE
composer: swagger-api/swagger-ui has not been updated to latest releases

### ISSUE THREAD

**Issue by mweibel** [swagger-api/swagger-ui#2576]
Currently on packagist, the repository for composer packages, the [package swagger-api/swagger-ui](https://packagist.org/packages/swagger-api/swagger-ui) has not been updated with the latest version of swagger. It lists 2.2.4 as the latest version while the latest version should be 2.2.8 according to [NPM](https://www.npmjs.com/package/swagger-ui) and the [GitHub releases page](https://github.com/swagger-api/swagger-ui/releases).

Would be nice if that could get updated :) 
Thanks 👍

**Comment by Tobion** [comment]
Normally it should get updated automatically on packagist based on github tags.

**Comment by fehguy** [comment]
I've re-triggered an update.  Should be there now.

**Comment by mweibel** [comment]
Awesome, thanks!

**Comment by hpcergar** [comment]
I know this issue is closed, but I'm trying to do the same to retrieve the 3.x tags via composer and in packagist you can only reach v2.2.10. Maybe there is a hook or something not finding the packagist endpoint?

Thanks for your work, by the way!

**Comment by webron** [comment]
@hpcergar we didn't have a composer file for 3.X until this week. Today's release should end up in packagist.
