### ISSUE TITLE
Issue with xml array element name

### ISSUE THREAD

**Issue by ritesh-garg** [swagger-api/swagger-ui#2577]
swagger-ui version: 2.2.8

This is related to [swagger-core-2047](https://github.com/swagger-api/swagger-core/issues/2047). Even if correct json representation is sent back as response; swagger-ui still uses the array element wrapper name for each item.

For instance, for the following representation:

```
{
   .
   .
      "animals":{
         "type":"array",
         "xml":{
            "wrapped":true
         },
         "items":{
            "type":"string"
            "xml":{
              "name":"animal"
            }
         }
      }
  .
  .
}
```

the xml it would generate in sample is:

```
<animals>
        <animals>value</animals>
        <animals>value</animals>
        <animals>value</animals>
</animals>
```

But it should be:

```
<animals>
        <animal>value</animal>
        <animal>value</animal>
        <animal>value</animal>
</animals>
```

**Comment by fehguy** [comment]
Fixed by #2581
