### ISSUE TITLE
UTF-8 filename isn't supported in Content-Disposition header 

### ISSUE THREAD

**Issue by rootext** [swagger-api/swagger-ui#2579]
When reporting a bug, please provide the following details:
- swagger-ui version : 2.2.8

Swagger-ui generates link for response as a file.
File name isn't extracted from header if it is encoded with  UTF-8.
Example:  `Content-Disposition: attachment; filename*=UTF-8''"test.pdf"`

https://tools.ietf.org/html/rfc6266

**Comment by fehguy** [comment]
This should be supported in master now.

**Comment by rootext** [comment]
The issue is still reproduced.  Commit: 64dc3060b3700b12e466f8d67b7d7ec3574b015f

Request URL
http://127.0.0.1:8080/api/******/4028b8815964bd62015964be07700001

Response Headers
{
  "pragma": "no-cache",
  "date": "Thu, 05 Jan 2017 12:58:59 GMT",
  "x-content-type-options": "nosniff",
  "content-type": "application/vnd.ms-excel",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "content-disposition": "attachment; filename*=UTF-8''\"test.csv\";",
  "content-length": "27722278",
  "expires": "0"
}

Response Body
Download 4028b8815964bd62015964be07700001

Link HTML:
<a href="blob:http://127.0.0.1:8080/cf503c29-4da8-4239-a269-e89b79eec6a7" download="**application/vnd.ms-excel:4028b8815964bd62015964be07700001:blob:http://127.0.0.1:8080/cf503c29-4da8-4239-a269-e89b79eec6a7**">Download 4028b8815964bd62015964be07700001</a>

Expected Link HTML:
<a href="blob:http://127.0.0.1:8080/cf503c29-4da8-4239-a269-e89b79eec6a7" download="**test.csv**">Download 4028b8815964bd62015964be07700001</a>
