### ISSUE TITLE
"Authorize" button requires at least 1 scope to be enabled in application flow

### ISSUE THREAD

**Issue by rondagostino** [swagger-api/swagger-ui#2580]
Under the latest version of swagger-ui (v2.2.8 plus all recent merges) the "Authorize" button at the top of the UI will not allow the user to make an authorization request to retrieve an empty token when there are 1 or more endpoints that require at least 1 scope.  See attached swagger.withscopes.yaml file -- the Authorize button at the top will not make a request for a token until "scope1" is checked.  However, if you expand the operations and click the red exclamation point next to the "/noscoperequired" endpoint you will be able to make a request for an empty token.  The presence of the "/scope1required" endpoint is causing the "Authorize" button to be unable to request an empty token.

The "Authorize" button at the top of the UI will make a request for an empty token when all of the endpoints require no particular scope.  See attached swagger.noscopes.yaml file -- the Authorize button at the top will make a request for an empty token.

The "Authorize" button should allow the user to keep all available scopes unchecked and make a request for an empty token.

[swagger.zip](https://github.com/swagger-api/swagger-ui/files/671073/swagger.zip)

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
