### ISSUE TITLE
Cannot read property 'errors' of undefined

### ISSUE THREAD

**Issue by faganchalabizada** [swagger-api/swagger-ui#2582]
i just install swagger-ui from [here](https://github.com/swagger-api/swagger-editor/releases/download/v2.10.4/swagger-editor.zip) and it is not working even with default API DOC. 
I also try to install from npm, but in this case index.html opened like a empty page.
> 
> angular-ui-router.js:4303 Uncaught TypeError: Cannot read property 'errors' of undefined
>     at Object.cb (angular-ui-router.js:4303)
>     at Worker.r (index.js:5558)
> (anonymous) @ angular-ui-router.js:4303
> r @ index.js:5558
> f346cc1….worker.js:78Uncaught ReferenceError: window is not defined

**Comment by webron** [comment]
Wrong project. Please open the ticket on swagger-editor.
