### ISSUE TITLE
Can we select the protocol from a combobox at the swagger doc schemes in the ui and try to make call?

### ISSUE THREAD

**Issue by emreerguden** [swagger-api/swagger-ui#2583]
Can we select the protocol from a combobox at the swagger doc schemes in the ui and try to make call?
Because the swagger-js code tries to decide but maybe if this new feature exists there is no need to understand if the api protocol is http or https? I manually made a fix for the broken chrome swagger ui extension of swagger because of this problem, thanks.

**Comment by webron** [comment]
We're going to have support for it soon, but can't provide an ETA.

**Comment by emreerguden** [comment]
There is a problem in swager-js for this matter. Chrome swagger ui extension stopped for working for schemes http and https. Either this functionality required or my pull request in swager-js needed for the fix

My pull request for swager-js chrome-extension-fix :) 
Let me code scheme multiple sceheme selection or please help this merge to be accepted and let us get back our extension in chrome working, thanks.

https://github.com/swagger-api/swagger-js/pull/913

**Comment by webron** [comment]
It'll probably take some time for it to be reviewed... end of year, people are off (and I'm afraid I can't review it myself).

**Comment by emreerguden** [comment]
Issue solved with the merge of my swager-js pull request. Thanks
