### ISSUE TITLE
List<Map<String, Object>> body parameter produces Array[undefined] data type on Swagger UI

### ISSUE THREAD

**Issue by s101d1** [swagger-api/swagger-ui#2585]
I'm using swagger annotation on dropwizard framework. I have HTTP POST API method which having request body parsed as List of Map<String, Object>:

```
@POST
public Response postFoo(@NotNull List<Map<String, Object>> foos) {
    ...
}
```

On the generated swagger UI, the body's `Data Type` is showing `Array[undefined]`.

I have tried adding `@ApiParam` to the `foos` param with `example` property set but the body data type is still showing `Array[undefined]`.

Is there a way to override the body's data type on the swagger UI?

**Comment by webron** [comment]
There is no way of doing it in swagger-ui, and this is not this project's issue. If the library that generates your spec doesn't generate the right output, you need to open the ticket on that library.

**Comment by s101d1** [comment]
I'm using swagger annotation on dropwizard, I initially reported the issue in swagger-core as I think this is problem in swagger core library, but they told me to open issue in swagger-ui.

**Comment by webron** [comment]
Sorry about the constant redirects. Can you share me a link to the issue on swagger-core?

**Comment by s101d1** [comment]
Here it is: https://github.com/swagger-api/swagger-core/issues/2026

**Comment by webron** [comment]
Thanks. Can you share the actual swagger.json file you get from swagger-core? If you can't share everything, share at least the part that's covering the method and the mismatched type.

**Comment by s101d1** [comment]
I don't know how to get the swagger.json, do you have any idea? 

FYI the swagger ui itself is generated by [dropwizard-swagger](https://github.com/smoketurner/dropwizard-swagger) library. So I just need to put some annotations, and then the swagger ui can be accessed in `http://localhost:<your_port>/swagger` when the dropwizard runs.

**Comment by s101d1** [comment]
Ok, I got it:
```
{
  "swagger" : "2.0",
  "info" : { },
  "basePath" : "/",
  "tags" : [ {
    "name" : "foos"
  } ],
  "schemes" : [ "http" ],
  "paths" : {
    "/foos" : {
      "post" : {
        "tags" : [ "foos" ],
        "operationId" : "postFoo",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "additionalProperties" : {
                "type" : "object"
              }
            }
          }
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
Well, I stand corrected. The issue is indeed with swagger-ui. Thanks for providing the input.

**Comment by tadhgpearson** [comment]
I'm also seeing this issue.
As a cursory glance, it looks like additionalProperties simply isn't supported yet >> https://github.com/swagger-api/swagger-ui/blob/fa5de88f5d43d98bb7fa39d02927bd43bb04b823/src/main/javascript/view/partials/signature.js#L872

**Comment by webron** [comment]
This should no longer be an issue in 3.X.

**Comment by tadhgpearson** [comment]
I can confirm that this is the case.
