### ISSUE TITLE
How can I add client certificate to a request sent by swagger UI to my API?

### ISSUE THREAD

**Issue by rigupt** [swagger-api/swagger-ui#2589]

**Comment by johnmilimo** [comment]
I really need this feature. Any support?

**Comment by AnkitaKumar** [comment]
Hi,
How was this issue resolved?

**Comment by rigupt** [comment]
There is nothing special required from swagger to support this. The browser should ask for the cert when swagger tries to send the request, mimicking the behavior when you try to make the same request from the browser directly, instead of swagger UI.

**Comment by gravip214** [comment]
When we are defining the YAML file for swagger, Is there any way to define in the YAML to ask for .crt and .key file when executing the API? May I Know how it implemented?

**Comment by 304NotModified** [comment]
related: https://github.com/swagger-api/swagger-ui/issues/8020
