### ISSUE TITLE
Can't change the request url in version 2.2.8

### ISSUE THREAD

**Issue by LuoPQ** [swagger-api/swagger-ui#2593]
I try to change the request URL by swaggerUi.api.setHost, and the property swaggerUi.api.host actually is changed, but when I click try it out, the request URL doesn't change.

version 2.2.8

**Comment by fehguy** [comment]
Looks like a regression in swagger-js.  Could you please open an issue there?

**Comment by LuoPQ** [comment]
@fehguy  sorry, what do you mean open an issue there

**Comment by fehguy** [comment]
If you could please [create an issue here](https://github.com/swagger-api/swagger-js), then it'd be very helpful.  A new swagger-ui release is coming tonight so please try to do so soon...

**Comment by LuoPQ** [comment]
@fehguy I just did it here [https://github.com/swagger-api/swagger-js/issues/922](Can't change the request url in swagger-ui version 2.2.8)
