### ISSUE TITLE
AWS Signature authorization support for API Gateway  

### ISSUE THREAD

**Issue by chgangaraju** [swagger-api/swagger-ui#2594]
I am trying to test the API Gateway API which has AWS_IAM authentication. As discussed here in [stackoverflow](http://stackoverflow.com/questions/36336072/how-to-calculate-aws-signature-v4-in-swagger-before-request), please provide support for adding `Authorization`,`X-Amz-Date` headers that can be calculated using `AccessKey`,`SecretKey`.

**Comment by fehguy** [comment]
Please don't double-post, it just clutters up answers.  See below.

There is built-in support in swagger-js to add requestInterceptors to do just this. The swagger-ui project uses [swagger-js](https://github.com/swagger-api/swagger-js) under the hood.

Simply create a request interceptor like such:

```
requestInterceptor: {
  apply: function (request) {
    // modify the request object here
    return request;
  }
}
```
and apply it to your swagger instance on creation:

```
window.swaggerUi = new SwaggerUi({
  url: url,
  dom_id: "swagger-ui-container",
  requestInterceptor: requestInterceptor,
```

Here you can set headers in the request object (note, this is not the standard javascript http request object, inspect it for details). But you do have access to all headers here, so you can calculate and inject them as needed.
