### ISSUE TITLE
Fetching resource list in wrong URL

### ISSUE THREAD

**Issue by gperozzo** [swagger-api/swagger-ui#2595]
Hello,

I'm using swagger in ASP.NET Core Web API, **version v1**.
Everything works fine in localhost but after I published the web api to a linux server, swagger UI doesn't work anymore.

I got this error: 
fetching resource list: http://localhost:60549/swagger/v1/swagger.json; Please wait.
Can't read from server. It may not have the appropriate access-control-origin settings.

The problem is that URL (http://localhost:60549) is wrong.

Correct Web API URL (just for example): http://testapi.sytes.net

**In startup.cs I have this:**

            services.ConfigureSwaggerGen(options =>
            {
                options.SingleApiVersion(new Swashbuckle.Swagger.Model.Info
                {
                    Version = "v1",
                    Title = "RDScan API",
                    Description = "xxxxxx",
                    TermsOfService = "xxxxxx",
                    Contact = new Swashbuckle.Swagger.Model.Contact { Name = "xxxxx", Email = "xxx@xxxx.com", Url = "http://xxxxxx" }
                });

                // Determine base path for the application.
                var basePath = PlatformServices.Default.Application.ApplicationBasePath;

                // Complete path
                var xmlPath = Path.Combine(basePath, "RDScanWebAPI.xml");

                // Set the comments path for the swagger json and ui.
                options.IncludeXmlComments(xmlPath);                

                // Registra a configuração para o upload de arquivos
                options.OperationFilter<FileOperation>();
            });

**Swagger Index file:**

      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
          url = "http://testapi.sytes.net/swagger/v1/swagger.json";
      }

And when I access **http://testapi.sytes.net/swagger/v1/swagger.json** everything is OK.

Can you guys help me?

**Comment by fehguy** [comment]
This is due to a configuration in your application server.  Please open an issue on that project--swagger-ui is just going to render whatever it spits out.
