### ISSUE TITLE
Endpoint with same path and HTTP method but different content-types?

### ISSUE THREAD

**Issue by vguna** [swagger-api/swagger-ui#2596]
I've got an endpoint which consumes JSON as well as MultiPart FormData as body under the same path and HTTP method (PUT). Now I'm wondering how this is handled by swagger-ui. In the one case it would have to provide a textbox (JSON) in the other case a file select button. How would a documentation for this look like? Is this even supported?

**Comment by fehguy** [comment]
You can have different types as long as the http verbs are different.

**Comment by vguna** [comment]
Ok, that means it is currently not supported, right :)? Since in both cases it is `@PUT`. Are there any plans to add support for it? Since, at least for JAX-RS, it's a valid constellation.

**Comment by Olivermugambi** [comment]
I have the same problem too. I have three @POST requests to the same endpoint that each require a different json body.

**Comment by fehguy** [comment]
This is how the swagger specification is designed.  See here for details:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
