### ISSUE TITLE
xmlObject presentation for Array with different property and element names

### ISSUE THREAD

**Issue by emilw** [swagger-api/swagger-ui#2601]
Hi,
I do not manage to get the xmlObject instruction working when setting an array with array property different from element name according to the Swagger spec:
http://swagger.io/specification/#xmlObject
(It's the last example in the specification)

I try to define it like this:
```json
"ArrayNoWrapAndDefinedParentAndChild": {
    "type": "array",
    "items": {
        "type": "string",
        "xml":{
            "name":"Child"
        }
    },
    "xml": {
        "name":"Parent",
        "wrapped":false
    }
},
```
My expected output as an example from Swagger UI would be:
```xml
<Parent>
  <Child>value</Child>
  <Child>value</Child>
</Parent>
```
But instead i get:
```xml
<Child>string</Child>
```
When changing to wrapped: true instead of false, i get the desired result. Is it a bug in Swagger UI or is it a mistake in the specification?
(http://swagger.io/specification/#xmlObject)

When reporting a bug, please provide the following details:
- Swagger UI version, the latest: http://petstore.swagger.io
- https://raw.githubusercontent.com/emilw/MixedStuff/master/Development/Web/OpenAPI/MySwaggerFile.json

**Comment by webron** [comment]
It's a mistake in the example in the spec. `wrapped` needs to be `true`.

**Comment by emilw** [comment]
Thanks for feedback, will you fix the examples or should i report this somewhere else?

**Comment by webron** [comment]
I'll fix it, thanks for pointing it out.
