### ISSUE TITLE
Clicking Request Model Signature Container should not copy read-only properties to request input field

### ISSUE THREAD

**Issue by leonliem** [swagger-api/swagger-ui#2602]
Version 2.2.10

I have this model:
```
  DataModel:
    type: object
    properties: 
       use_only_in_response: 
         type: string
         readOnly: true
```
In a POST request, this use_only_in_response property is labeled as read-only in the model signature container.

Usually, if click the model, this request demo data will be copied to the request input box. 

However, the use_only_in_response read-only property is also copied to the input box.

From [Swagger Spec](http://swagger.io/specification/#schemaObject): 
_Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but MUST NOT be sent as part of the request._ 

I would like to ask, if this read-only property MUST NOT be used as request, why Swagger UI still copy it into request input. Is this against the spec and can we fix this? 

----
Background: we're trying to use Swagger UI to let external customer to test our API, and our system will report error if such use_only_in_response property are brought in request. 
We hope this doesn't confuse our customer, and from user experience perspective, we don't want them to manually remove these "read-only" properties. Currently, we have to create separate model for request for work around.

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
