### ISSUE TITLE
Properties of `swaggerApi` arg of `onComplete` callback mixed with `api` items

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#2608]
Not that I noticed a problem (yet), but I haven't done anything to produce this (e.g. altered runtime code), while my API-related names are placed in the same "bucket" as swaggerui-related data - which, IMO, is going to result in overwritten information sooner or later. Just wanted to report that, in case it's been overlooked.

See screenshots:

![image](https://cloud.githubusercontent.com/assets/3127736/21897355/96cce64e-d8a6-11e6-98ea-2e098aecda61.png)

![image](https://cloud.githubusercontent.com/assets/3127736/21897376/a4a834a8-d8a6-11e6-9dc1-8fd4a79ab1fb.png)

**Comment by fehguy** [comment]
Well, I believe we correctly sanitize names and overwriting something isn't possible.  You can see how it's done here:

https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L27

So to avoid cluttering up the issues (and there are a lot of issues), I'll close this out, you can reopen if you see it not behaving correctly.

**Comment by hlubovac** [comment]
I believe that the warning is real, though. I proved it by naming a tag (within swagger-json) to be one of the members of that object above (I chose "debug"), after which I see this logged in the console:

"helpers.js:18 The 'debug' tag conflicts with a SwaggerClient function/property name.  Use 'client._debug' or 'client.apis.debug' instead of 'client.debug'."

However, there are no noticeable errors on the page: endpoints related to endpoints within that tag. Unfortunately, I cannot easily/quickly test using one of the reserved words as the name of a `definition` or another piece from the document.

It's up to you. IMO, restrictions of this kind, when they can be avoided, shouldn't exist. In other words, I shouldn't be forced not to name something "debug" just because of documentation site.

Thanks.

**Comment by fehguy** [comment]
I hear you, but what i'm saying is, it will transparently "make it work".  You can name your tag group `debug` or `apis` or whatever.  The function being bound to the swagger-client will be renamed with an underscore prefix, but you can still access it by name from the apis array.

So tag `apis`:

```
// note the change from `apis` to `_apis`:
client._apis.help();

// however referencing as such has no change whatsoever:
client.apis['apis'].help();
```

Likewise I have a tag `Z-Wave`, which is an illegal object key name.  I can reference it as such:

```
// note the change from hyphen to underscore:
client.Z_Wave.help();

// but unchanged in the object hash:
client.apis['Z-Wave'].help();
```

So, you can use the convenience names as bound to the object, but they have obvious limitations.  If you don't like that, then ignore it and use the `apis` object hash key.  Therefore there are no restrictions except if you want to use a convenience binding.
