### ISSUE TITLE
xmlObject on referenced type sets name of property

### ISSUE THREAD

**Issue by emilw** [swagger-api/swagger-ui#2610]
Hi,
I just need to understand if this is the intended behaviour or if it's a bug i Swagger UI.

If i have a property represented like it's done here:
```json
"AccrualCodeString": {
                    "$ref": "#/definitions/IntegrationCodingDimensionsDto",
}
```
The definition "#/definitions/IntegrationCodingDimensionsDto" have xml property set to "CodingDimensions".
My expected output in XML would have been:
```xml
<AccrualCodeString >
    <Dimension1>string</Dimension1>
    <Dimension2>string</Dimension2>
.
.
  </AccrualCodeString >
```
But instead i get:
```xml
<CodingDimensions>
    <Dimension1>string</Dimension1>
    <Dimension2>string</Dimension2>
.
.
  </CodingDimensions>
```
Why does the referenced property types xml object name take over the property name? It does not make sense in my world....
To get my intended behaviour i need to force an xml object onto the property with the same name as the property like it's done bellow:
```json
"AccrualCodeString": {
"$ref": "#/definitions/IntegrationCodingDimensionsDto",
"xml":{
"name":"AccrualCodeString"
 }
},
```
Then i will get:
```xml
<AccrualCodeString >
    <Dimension1>string</Dimension1>
    <Dimension2>string</Dimension2>
.
.
  </AccrualCodeString >
```

Is it possible to get some clarity in this?

**Comment by webron** [comment]
It behaves as expected. When you're referencing a different model, effectively what happens is that you copy that definition into the new one. So, the xml information is copied along and is used to give you the output you're seeing.

**Comment by emilw** [comment]
Thanks for feedback. When i look into the specification it's not clear that it will change the behaviour e.g. overwrite the property name for xml, will other tools that interpret the standard work the same way or how do you see it? I get that your explanation is for how your code works in Swagger UI, but i think more in general terms. Can you point me to where in the spec this is written...if not, can that be clarified in the spec?

For me it's still a really strange behaviour that the property name changes for XML but not for the JSON. The code that i need to write to generate that behaviour will need to check if there exists an xml object on the referenced type, if so, then write the same name as the property as xml. This feels odd.

**Comment by webron** [comment]
I don't really understand your confusion. The spec doesn't talk directly about JSON References and their behavior and assumes the behavior as defined by its own spec. Overriding xml names is a way to overcome an issue when specifying xml structures in JSON. Since JSON Schema is already used, there's no need to allow for overriding of JSON name properties, you just define them as they are.
The XML Object in the spec is very explicit and says what `name` is used for, which is, overriding the existing name.

**Comment by emilw** [comment]
Hi,
Yes, i guess my confusion is due to the JSON References, i did not understand that it was specified somewhere else. I though still think it's a strange behaviour, and that might be due to that i see it from a C# class perspective. I never thought that a type could redefine a property name on the one that references the type. Just to clarify so you see my side of it:

Here is a property defined on class X, it's called AccrualCodeString and references IntegrationCodingDimensionDto.
```c#
public IntegrationCodingDimensionsDto AccrualCodeString { get; set; }
.
.
.
```
Here is the IntegrationCodingDimensionDto defined, with an XmlType attribute to control how the root element should be named when that class is used on it's own:
```c#
[XmlType("CodingDimensions")]
    public class IntegrationCodingDimensionsDto
    {
.
.
.
```
When serializing object of type X to an XML it will look as bellow:
```xml
<X>
<AccrualCodeString >
    <Dimension1>string</Dimension1>
    <Dimension2>string</Dimension2>
 .
 .
  </AccrualCodeString >
</X>
```
But getting it in Swagger UI will give me for XML:
```xml
<X>
<CodingDimensions>
    <Dimension1>string</Dimension1>
    <Dimension2>string</Dimension2>
.
.
.
  </CodingDimensions>
</X>
```
And in JSON:
```json
{
"AccrualCodeString":{"Dimension1":"string"...}
}
```
I guess the whole "Type took over property name" is the use case that i had hard time getting my head around, but seeing it from JSON References i understand it better. 
Thanks for feedback anyway, i appreciate it. I buy that you rely on a standard and cannot do anything about it, i just wanted to point out why i got confused.
Hope you are fine with discussing it :-)!

**Comment by webron** [comment]
Of course, discussions are a great way of learning. I'll close the ticket for now, but if you have additional questions don't hesitate to ask.
