### ISSUE TITLE
Multiple Queryparam are not compiling in ui before hitting the host

### ISSUE THREAD

**Issue by KV029942** [swagger-api/swagger-ui#2613]
Hello All,

Swagger UI script not compiling multiple QueryParam's.

It looks like Curl Command is correctly generated so i believe we are configuring APIParam correctly, but when I hit send ,the host server is receiving only one param and missing second query parameter. when I copy the swaggerUI curl command and ran it from command prompt, it is working as excepted. 

Here is the curl command :
curl -X POST --header 'Content-Type: text/plain' --header 'Accept: text/plain' -d 'testing'
 'http://xxxxxxxxxxxxxxx:9080/xxx/xxx/submit?FIELD1=FIELD1&EXTRA=test1&EXTRA=test2'
 
I was thinking swagger UI not compiling the second query parameter appropriately.  

Please find my test schema attachment [Here](https://github.com/swagger-api/swagger-ui/files/709211/swaggercontent.txt)

These are the annotations in java class:  [Java config ](https://github.com/swagger-api/swagger-ui/files/709213/java_config.txt)

We are using 2.2.7 swagger-ui version and the issue is reproducible with all the versions of swagger-jersey-jaxrs and swagger-jersey2-jaxrs.

<dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jersey-jaxrs</artifactId>
            <version>1.5.12</version>
<dependency

<dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jersey2-jaxrs</artifactId>
            <version>1.5.12</version>
<dependency

Can someone point me to fix this?
Thanks!

**Comment by fehguy** [comment]
Latest master does what I'd expect it to:

![image](https://cloud.githubusercontent.com/assets/249413/22006880/8cae4eac-dc23-11e6-8cde-352365fec2ff.png)

![image](https://cloud.githubusercontent.com/assets/249413/22006885/956e0492-dc23-11e6-880d-1d3dd0391147.png)

![image](https://cloud.githubusercontent.com/assets/249413/22006888/9a6a9b7c-dc23-11e6-9166-44bac42d4424.png)

Do you see otherwise in your network inspector?

**Comment by KV029942** [comment]
We don't have network inspector but we enabled ibm server logs to track http header. 

When we test from swagger UI, this is what server receiving:
- - ipaddress - [17/Jan/2017:10:17:25] "POST /xxx/yy/submit?FIELD1=test HTTP/1.1" 403 30

Only first parameter getting received in server and missing rest of the EXTRA query params.


To confirm this, I ran curl command by copying from swagger UI and executed in command line.

curl -X POST --header 'Content-Type: text/plain' --header 'Accept: text/plain' -d 'testing' 'http://localhost:9080/xxx/yy/submit?FIELD1=baz&EXTRA=foo&EXTRA=bar'

Server received all the query param.
- - ipaddress - [17/Jan/2017:10:32:31] "POST /xxx/yy/submit?FIELD1=test&EXTRA=foo&EXTRA=bar HTTP/1.1" 403 30

BTW we are using swagger ui 2.2.7, we can install master copy(2.2.10) if that helps.

Swagger UI:
![swaggerui_test](https://cloud.githubusercontent.com/assets/6536304/22030010/ee89f1c0-dca1-11e6-8fd4-58a14fbebaca.JPG)

**Comment by webron** [comment]
There shouldn't be an issue with 2.2.7 but try with latest.
What you're seeing in your server is not necessarily a good indication - there are other parts that can affect what's being sent.
Just open the network console in your browser and see what's actually being sent.

**Comment by KV029942** [comment]
We will try with latest version, In the meanwhile here is our network console while sending the request.



![swaggerui_test2](https://cloud.githubusercontent.com/assets/6536304/22038262/0fcca2a6-dcc0-11e6-9c97-057eca31c3a5.JPG)

Currently I am not sure whether it is browser specific or application related or swagger ui after looking into the  browser network console. 


Query String Parameters in network console looks little different. First Parameter builded along with url, second and third parameters displaying in differently section.



 BTW I tested in different clients (like SOAPUI / REST Client) which worked fine but through swagger UI it is failing. Sorry if this is out of your scope. Thanks!!


Again here is our config:
  ```
@Path("submit")
    @POST
    @Consumes(MediaType.TEXT_PLAIN)
    @Produces(MediaType.TEXT_PLAIN)
    @ApiOperation(value = "Submit ", notes = "")
	@ApiResponses(value = {@ApiResponse(code = 500, message = "Internal Server Error") })
    @Override
    public Response processSubmit(
    		@ApiParam(value = "", required = true) @QueryParam("FIELD1") final String field1, 
    		@ApiParam(value = "", required = true) final String content,
    		@ApiParam(value = "", required = true, allowMultiple= true) @QueryParam("EXTRA") final List<String> list)
```

**Comment by webron** [comment]
From the network console you can see that `EXTRA` is being sent twice, which is what you expect it to - that means that swagger-ui behaves as expected. What happens once it leaves the browser and gets into your app is in your domain...

**Comment by KV029942** [comment]
That makes sense, Will look into this. 

Thanks for your time. 

Much Appreciated!
