### ISSUE TITLE
Path Response with multiple items in "allOf" is not rendered properly.

### ISSUE THREAD

**Issue by zorang** [swagger-api/swagger-ui#2616]
- swagger-ui version 2.2.10
- a swagger file reproducing the issue
[generate-swagger-json.json.zip](https://github.com/swagger-api/swagger-ui/files/712518/generate-swagger-json.json.zip)

There is path which contains reference to an definition: http://take.ms/71Fhc
That definition exists here: http://take.ms/cxLm8 and contains an property called "currency".

But when we render the swagger ui  we don't see the "currency" property of that definition rendered: http://take.ms/fubsS

**Comment by webron** [comment]
The issue seems to be not with the multiple `allOf` but the depth of it.
As a workaround, you can extract the `partner` definition (the one containing the `allOf`) to a separate definition, and $ref it from `partner, it would render properly.

**Comment by zorang** [comment]
@webron yes that workaround have helped. 

It really would be good to have that fix to avoid polluting of definitions with possible definitions conflicts and overlapping.

**Comment by webron** [comment]
This should no longer be an issue with 3.X.
