### ISSUE TITLE
MultipartFile[] doesn't show correctly

### ISSUE THREAD

**Issue by SylarChen** [swagger-api/swagger-ui#2617]
https://github.com/springfox/springfox/issues/1072

**Comment by webron** [comment]
The spec doesn't allow multiple file uploads, so we can't really support it.

**Comment by Hronom** [comment]
Guys I see in UI this when I have parameter `@RequestPart(value = "file", required = true) List<MultipartFile> file,`
![multifiles](https://user-images.githubusercontent.com/429993/44782831-34d85300-ab91-11e8-90e7-99c27b01aa97.png)
So it seems like supported, but swagger ui not send two files when I press execute.

Is it bug?

**Comment by NABEEL-AHMED-JAMIL** [comment]
Is any update on this issue?

**Comment by ruanwenjun** [comment]
@webron Hi , I can choose MultipartFile[] in the swagger UI. But  it doesn't work on the controller, I get empty in the request.
But when i use postman to send my request, it work well.
My swagger-ui version is 2.9.2 .

**Comment by HichamOUAHIDI** [comment]
is any update on this issue ?

**Comment by NABEEL-AHMED-JAMIL** [comment]
not yet
