### ISSUE TITLE
Same endpoint, Same http verb, different content type

### ISSUE THREAD

**Issue by Olivermugambi** [swagger-api/swagger-ui#2618]
swagger-ui v2.0
I have an endpoint (/eft) where I can post requests of three types. But when I try to document, swagger UI overwrites all the other contents except the last one.

**Comment by fehguy** [comment]
This is per design.  Please look at the spec to understand what is legal in your design.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
