### ISSUE TITLE
LOW: $ref description in wrong place

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#2622]
Sorry, I couldn't easily determine whether this has already been reported, as searching for "description" yields pretty much all issues :)

Consider this YAML:
![image](https://cloud.githubusercontent.com/assets/3127736/22128159/88f96ebe-de5c-11e6-84d2-7569fc07cbcc.png)

Notice how property `meta` is defined inline, while property `attributes` points to a `$ref` elsewhere. Also notice how swagger-editor flags `description` that accompanies `$ref`, while the one that accompanies the inline definition is fine. On the other side, it appears that swagger-ui only honors `description` that appears alongside `$ref`, while it ignores the one defined inline. By swagger-ui ignoring it, I mean that it doesn't display it within the model (next to its name, I guess). On the contrary, `description` value accompanying `$ref` gets displayed next to the property.

**Comment by webron** [comment]
This should no longer be an issue with 3.X.
