### ISSUE TITLE
android client generation problem on list of enum

### ISSUE THREAD

**Issue by dvalishvili1** [swagger-api/swagger-ui#2627]
- swagger-ui version '2.0'
- generated on http://editor.swagger.io/

enum is:
  `public enum CardType
    {
        Unknow = 0,
        Amex = 10,
        Visa = 11,
        MasterCard = 12,
        Maestro = 13
    }`
 property in model:
`public IEnumerable<CardType> PaymentMerchants { get; set; }`

generated android client model is:
`  public enum List&lt;PaymentMerchantsEnum&gt; {
     Unknow,  Amex,  Visa,  MasterCard,  Maestro, 
  };`

`  @SerializedName("PaymentMerchants")
  private List<PaymentMerchantsEnum> paymentMerchants = null;`

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#4631
