### ISSUE TITLE
Response description does not render HTML markup

### ISSUE THREAD

**Issue by banders** [swagger-api/swagger-ui#2630]
Using swagger-ui 2.2.8.

With a **response description** that includes an HTML `a href`, the link is not marked up in swagger-ui.   For example: 
```
"responses": {
"200": {
"description": "A list of matching sites or intersections and their physical locations. See <a href='https://github.com/bcgov/api-specs/blob/master/geocoder/geocoder-developer-guide.md#resource-representations-in-http-responses' target=\"_blank\">addresses response</a>"
}
}
```

Full swagger file 

[This issue](https://github.com/bcgov/ckanext-openapiviewer/issues/15) (from another project that utilizes swagger-ui) shows a screenshot of how swagger-ui 2.2.8 renders the above swagger snippet.  swagger-ui 2.1.4, and possibly other versions, did correctly render the HTML markup in the above snippet.

Note: markup of `a href` in other fields within the swagger API definition seem to render correctly.  For example, there is no problem with rendering of `a href` markup in parameter descriptions.

**Comment by fehguy** [comment]
Use markdown--we don't allow HTML because of XSS vulnerabilities.  See https://github.com/swagger-api/swagger-ui/issues/1864 for more details.
