### ISSUE TITLE
How to add "Raw" link

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-ui#2633]
I don't have "Raw" in swagger. How to add "Raw" link?

<img width="972" alt="f535f85c-e2dc-11e6-95bc-07ba68de7260" src="https://cloud.githubusercontent.com/assets/4563564/22331708/94cd939a-e3d5-11e6-8292-91fa93a60bab.png">

**Comment by webron** [comment]
The "raw" link was removed when 2.0 support was added, since 2.0 is a single file (for the most part). If the 'explore' textbox is visible, that's the same URL for the 'raw' input. If it's not, and you want to show it, you can easily add it yourself.
