### ISSUE TITLE
DataType Model view for request no formatting for maxLength fields

### ISSUE THREAD

**Issue by QuasiSoDo** [swagger-api/swagger-ui#2634]
- swagger-ui version: 2.2.6

I am trying to format the DataType model and want to have a formatted output including javax.validation.constraints.Size; 

Firefox displays the model without spaces or other formatting. 

This is the field in my POJO: 

`   @NotNull
   @Size(max = 60)
   @ApiModelProperty("Straße. ")
   private String street;`

Excerpt swagger.json request result: from my log-file: 

> "properties" : {
>         "street" : {
>           "type" : "string",
>           "description" : "Straße. ",
>           "minLength" : 0,
>           "maxLength" : 60
>         },

Rendered as (in Firefox 50.1.0)

![auswahl_001](https://cloud.githubusercontent.com/assets/25366613/22333719/cc944bc8-e3d7-11e6-981c-962197e6bc7a.png)

It is unclear to me if this is expected behaviour, or there exists functionality to format the output, or if it is a bug. 

If any more information is required, i will provide it :) !

**Comment by webron** [comment]
This is resolved in 3.X.
