### ISSUE TITLE
i need to know how to handle application/pdf file

### ISSUE THREAD

**Issue by HarshadPatel4** [swagger-api/swagger-ui#2639]
I have used the swagger-ui version 2.1.5

When i pass the pdf file to the swagger at that time its take like

%PDF-1.4
%����
4 0 obj
<</Linearized 1/L 357550/O 6/E 354549/N 1/T 357356/H [ 1216 234]>>
endobj
                 
xref
4 46
0000000016 00000 n
0000001450 00000 n
0000001558 00000 n
0000002048 00000 n
0000004413 00000 n
0000006649 00000 n
etc.....

and header was

--header 'Content-Type: application/json' --header 'Accept: application/pdf'

So i need to get help
is their any way to handled it?
Thanks for any help in advance please :(

**Comment by webron** [comment]
This should just work now in the new UI.
