### ISSUE TITLE
TypeError when the API are splitted between files

### ISSUE THREAD

**Issue by njordr** [swagger-api/swagger-ui#2640]
Hi.

I'm using the last version of swagger-ui (https://github.com/swagger-api/swagger-ui/commit/38f74164a7062edb5dc80ef2fdddda24f3f6eb85) 

I created the API docs with the swagger editor and all went well.
When I try to visualize them with the UI, it gives me this error:

TypeError: can't assign to properties of (new String("definitions.yaml")): not an object

This is the entire directory of files. They're served from an http server with cors enabled
[docs.zip](https://github.com/swagger-api/swagger-ui/files/744817/docs.zip)

**Comment by webron** [comment]
This should no longer be an issue with 3.X.
