### ISSUE TITLE
Swagger definitions does not work with @FeignClient

### ISSUE THREAD

**Issue by deepank-sharma** [swagger-api/swagger-ui#2642]
When reporting a bug, please provide the following details:
- swagger-ui version 2.4.0
- a swagger file reproducing the issue

When I am using a FeignClient in my Controller method to call the backend APIs , Swagger does not generate the definitions of all the Model VOs. I just see a single property named type:"object" for all.

I tried adding @ApiIgnore to the FeignClient interface just to see if it ignores it and works but since I am autowiring the FeignClient in my Controller it does not seem to work.

**Comment by webron** [comment]
So, there's no swagger-ui version 2.4.0, and I have no idea what @FeignClient is. It sounds like the issue should be opened on the project producing it. Swagger-ui simply renders what it's getting. If your spec includes more information than just type object, then please open the ticket again, with the correct version of swagger-ui and the spec itself for us to reproduce the issue.
