### ISSUE TITLE
swagger-ui breaks for POST request.

### ISSUE THREAD

**Issue by candysmurf** [swagger-api/swagger-ui#2643]
When reporting a bug, please provide the following details:
- swagger-ui version

Swagger Editor
Version 2.10.4

- a swagger file reproducing the issue

When tried to load the json file(https://gist.github.com/candysmurf/eebde06ee0eac93317651969901e2978) as POST, it gave the following error in the response when using swagger-ui.

```
{message: "invalid character '-' in numeric literal", fields: {}}
fields
:
{}
message
:
"invalid character '-' in numeric literal"
Name
Path

```
Note that the input works from curl or chrome rest client but not in swagger-ui.

See gist for swagger.json where POST/tasks was what I tested.

https://gist.github.com/candysmurf/f5603e035704a65e0527ddebc0d8dc3e

**Comment by candysmurf** [comment]
I looked into it. The reason is that swagger-ui passes OPTIONS as the method instead of POST or PUT.

The following is the output from my PUT operation:
```
DEBU[2017-02-06T14:37:29-08:00] API request                                   _module=_mgmt-rest index=35 method=OPTIONS url=/v2/plugins/collector/mock/2

DEBU[2017-02-06T14:37:29-08:00] API response                                  _module=_mgmt-rest index=35 method=OPTIONS status=Method Not Allowed status-code=405 url=/v2/plugins/collector/mock/2

```

**Comment by candysmurf** [comment]
I solved my own issue.

**Comment by cosbor11** [comment]
@candysmurf - how?
