### ISSUE TITLE
JSON input did not save by swagger-ui

### ISSUE THREAD

**Issue by candysmurf** [swagger-api/swagger-ui#2644]
When reporting a bug, please provide the following details:
- swagger-ui version: Version 2.10.4
- a swagger file reproducing the issue
https://gist.github.com/candysmurf/6ee732ac99e8c018d8b27680c2b7e0d2

when inputting JSON into metrics, the input didn't get saved. Please see two attached screenshots.

![task-1](https://cloud.githubusercontent.com/assets/13841563/22665068/3b260dd6-ec68-11e6-9a5b-6f819b2b5689.png)

![task-2](https://cloud.githubusercontent.com/assets/13841563/22665071/3e11a276-ec68-11e6-9a73-706bf9d3787a.png)

**Comment by webron** [comment]
The screenshots are of swagger-editor (and so is the version). Please open the ticket on the right project.
