### ISSUE TITLE
Show a loader/spinner instead of a string called "fetching resources..." in Swagger UI

### ISSUE THREAD

**Issue by aditya-code-blooded** [swagger-api/swagger-ui#2645]
Hello,

I really loved Swagger. It greatly reduced the complexity in documenting API's.

My swagger-ui version is v2.2.10. Recently I have been developing 'yaml' specifications for my API's. After the specifications are ready and validated, I downloaded the Swagger UI to my machine. As specified in the tutorial, I moved all my swagger spec files of my API to the 'dist' folder.

But I don't want to use the Swagger UI as it is. I modified the default UI. I added and removed few components from the UI. While doing so, I stumbled across an issue. I don't call this as a bug, but it would be better if the following feature is added:
While loading the specification file, the Swagger UI displays "fetching resource list; Please wait.". This message kind of disrupts the beauty of Swagger UI since it is placed right at the top. I have simply edited the code which does this, as follows: (this is swagger-ui.js)

`SwaggerClient.prototype.build` = function (mock) {
 `` if (this.isBuilt) {
    return this;
  }

  var self = this;

  if (this.spec) {
    //console.log('fetching resource list; Please wait.');
    this.progress('');
  } else {
    //console.log('fetching resource list: ' + this.url + '; Please wait.');
    this.progress('');
  }

  var obj = {
    useJQuery: this.useJQuery,
...`

Now, the message won't get displayed. But this 'hack' has another drawback. The user of the Swagger-UI will not know why the web page got stuck (when he/she clicks on the 'explore' button and the Swagger will try to fetch the resource.)

Forgive me if my explanation is not proper. In simple terms, as the title says, how should I display a spinner/loader on the Swagger UI instead of the "fetching resources..." message. I am new to JavaScript and jQuery. I read about promises, but I don't know how to accomplish my goal.

A quick response is greatly appreciated.

Thanks! :)

**Comment by webron** [comment]
The behavior is different in 3.X.
