### ISSUE TITLE
<pre> tags in parameter descriptions are always 200px in height, regardless of their contents

### ISSUE THREAD

**Issue by michaelkourlas** [swagger-api/swagger-ui#2647]
Version: current master (38f7416)

\<pre> tags in parameter descriptions are always 200px in height, regardless of what is contained within them. They should at least be no larger than their contents.

For example, when swagger-ui renders the following spec (in Chrome 56), the code block containing "This is some code" is too large:

![capture](https://cloud.githubusercontent.com/assets/1672388/22710929/3e5aaba2-ed4d-11e6-920a-2abeb13b7571.PNG)

```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Sample",
  },
  "paths": {
    "/test": {
      "get": {
        "summary": "Test",
        "responses": {
          "200": {
            "description": "Test",
            "schema": {
              "$ref": "#/definitions/Test"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Test": {
      "properties": {
        "test": {
          "type": "string",
          "description": "This is a test\n```text\nThis is some code\n```"
        }
      }
    }
  }
}
```

**Comment by dwickern** [comment]
Easy workaround by adding to `index.html`:
```
    <style>
      .swagger-section .swagger-ui-wrap .model-signature pre {
        height: initial;
      }
    </style>
```

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
