### ISSUE TITLE
Anchor links open a new tab/window

### ISSUE THREAD

**Issue by michaelkourlas** [swagger-api/swagger-ui#2648]
Links in the main description are always opened in a new tab/window, even if they are anchor links on the same page. They should simply jump to the anchor rather than open a new page.

For example, when swagger-ui renders the following spec (in Chrome 56), the link "link" opens a new tab:
```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Sample",
    "description": "# heading1 #\n[link](#heading2)\n\n# heading2 #\nText"
  },
  "paths": {
    "/test": {
      "get": {
        "summary": "Test",
        "responses": {
          "200": {
            "description": "Test",
            "schema": {
              "$ref": "#/definitions/Test"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Test": {
      "properties": {
        "test": {
          "type": "string",
          "description": "This is a test\n```text\nThis is some code\n```"
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
This should no longer be an issue with the new UI.

**Comment by akrz** [comment]
Its still and issue. Clicking on an anchor will open a new tab

**Comment by shockey** [comment]
@akrz as of now, external links are intentionally opening in new tabs, and internal anchor links within a definition are not supported.
