### ISSUE TITLE
Array validation prone to js errors

### ISSUE THREAD

**Issue by jdmg94** [swagger-api/swagger-ui#2655]
On  ```dist/swagger-ui.js``` **version  v2.2.10** the array validation is done by calling the ```type``` property of the object, instead of using [isArray](http://www.w3schools.com/jsref/jsref_isarray.asp), in some cases, this breaks the rendering of the documentation. 

My proposition here is to change all the ```param.type === 'array'``` evaluations in favor of ```param.isArray```

<img width="1021" alt="screen shot 2017-02-08 at 1 45 10 pm" src="https://cloud.githubusercontent.com/assets/4754734/22755465/dfdf602e-ee08-11e6-9170-e6b508b25906.png">

**Comment by webron** [comment]
This should no longer be an issue with 3.X.
