### ISSUE TITLE
Have apisSorter and operationsSorter default to alpha

### ISSUE THREAD

**Issue by OlafvdSpek** [swagger-api/swagger-ui#2657]
Could apisSorter and operationsSorter both default to alpha?
It'd make more sense then a semi-random ordering.

```
apisSorter: "alpha",
operationsSorter: "alpha",
```

**Comment by webron** [comment]
It's not semi random, it's based on the order they're written in the spec. If you want it alphabetized, just set it that way.

**Comment by OlafvdSpek** [comment]
> it's based on the order they're written in the spec.

Is it?

https://github.com/swagger-api/swagger-ui/issues/2017#issuecomment-193909415

BTW, for operationsSorter: "method" it might make sense to sort on (method, name) instead of just (method).

**Comment by andrew-regan** [comment]
Are the following parameters still supported in 3.0.x? I'm running 3.0.2 and seeing out of order API's even when these are set in index.html:

```
apisSorter: "alpha",
operationsSorter: "alpha",
```

**Comment by webron** [comment]
@andrew-regan not yet.

**Comment by andrew-regan** [comment]
Thanks for confirming!

**Comment by OlafvdSpek** [comment]
@webron They just default to alpha, right? ;)

**Comment by webron** [comment]
@OlafvdSpek not sure, tbh. I'd guess natural order, but could be wrong.

**Comment by risa** [comment]
+1, thanks!

**Comment by shockey** [comment]
Closing; [`tagsSorter` and `operationsSorter`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#display) are now implemented in 3.x.

**Comment by OlafvdSpek** [comment]
@shockey Great! Do they also default to alpha though?

**Comment by shockey** [comment]
@OlafvdSpek they don't by default, we'll by sticking with best-effort natural order by default.

However, `alpha` is just one config parameter away 😄

**Comment by OlafvdSpek** [comment]
Good defaults are important. ;)
