### ISSUE TITLE
Values of "description" field within "$ref" definitions are not displayed anywhere

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#2660]
I reported this in details at swagger-editor project: [issue 1184](https://github.com/swagger-api/swagger-editor/issues/1184). Please take a look. I think that swagger-editor and swagger-ui are not in agreement where this description field needs to be, so, I'm suggesting that you discuss and see if any tweaks are due and where.

Thanks.

**Comment by webron** [comment]
The behavior has been fixed.
