### ISSUE TITLE
OAuth2 Password Flow is not functional

### ISSUE THREAD

**Issue by frol** [swagger-api/swagger-ui#2661]
Swagger UI 2.2.9+ seems to contain OAuth2 Password Flow support, but when I try to use it, it just silently ignores the received `access_token`.

You can use my demo OAuth2 server hosted on heroku with the swagger config:

~~https://flask-restplus-example-server.herokuapp.com/api/v1/swagger.json~~

https://dl.dropboxusercontent.com/u/18807070/tmp/swagger.json

Credentials:

Username: `root`
Password: `q`
Client ID: `documentation`
Client Secret (it is optional as it is only required to refresh access key when it expired): `KQ()SWK)SQK)QWSKQW(SKQ)S(QWSQW(SJ*HQ&amp;HQW*SQ*^SSQWSGQSG`

Try selecting any of the scopes and click `Authorize`. The UI will get re-rendered, but the access token doesn't get populated to the requests, and (!) red sign indicator that the scope is not available stays (instead of becoming blue).

This bug is reproducible on the petstore: http://petstore.swagger.io/ (just use my `swagger.json` mentioned above).

OAuth2 Password Flow used to work fine and I still have an older (functional) version of it in my fork: https://github.com/frol/swagger-ui/tree/implement-oauth2-password-flow-rebased. Yet, none of the officially released versions of Swagger-UI include a working OAuth2 Password Flow support :(

/cc @webron @bodnia @MugeSo

**Comment by MugeSo** [comment]
I got 404 for `http://petstore.swagger.io/auth/oauth2/token` when Ｉ tried as you say.

Is there any access control using `origin` or `referer` header?

**Comment by frol** [comment]
Hmmmm, on the second try with petstore it turned out to be working, but it renders "Authorize" button in the right top corner twice:

![swagger ui](https://cloud.githubusercontent.com/assets/304265/22966872/b74a853a-f36c-11e6-9a87-746baf84d02c.png)

I have updated the `swagger.json`.

Now I have to understand why Swagger-UI releases don't work locally on my end... :(

**Comment by frol** [comment]
Oh, well, the original issue is my bad. I used a custom `onOAuthComplete`, where I haven't migrated from `window.swaggerUi` to `window.swaggerUiAuth`. By the way, I still don't understand how useful `lib/swagger-oauth.js` is. For me, dropping it and just implementing an `onOAuthComplete` global function makes oauth2 happy.

Just for the reference, here is my `onOAuthComplete`:

```javascript
onOAuthComplete = function onOAuthComplete(token, OAuthSchemeKey) {

  if (token === '') {
    alert("Authorization failed for unknown reason, please, check your credentials!")
    return
  }

  if(token.error) {
    var checkbox = $('input[type=checkbox],.secured')
    checkbox.each(function(pos) {
        checkbox[pos].checked = false
    })
    alert(token.error)
  }
  else {
    var access_token = token[window.swaggerUiAuth.tokenName]

    if (!OAuthSchemeKey) {
      OAuthSchemeKey = token.state;
    }

    if(access_token) {
      // if all roles are satisfied
      window.swaggerUi.api.clientAuthorizations.add(OAuthSchemeKey, new SwaggerClient.ApiKeyAuthorization('Authorization', 'Bearer ' + access_token, 'header'))
      window.swaggerUi.load()
    }
  }
}
```
