### ISSUE TITLE
Group operations by first path entry

### ISSUE THREAD

**Issue by OlafvdSpek** [swagger-api/swagger-ui#2662]
Could operations be grouped by the first path entry (pet, store, user, etc) by default if no tag is set?

**Comment by webron** [comment]
Not OOTB.

**Comment by OlafvdSpek** [comment]
Via a setting then?

**Comment by webron** [comment]
It's not implemented.

**Comment by OlafvdSpek** [comment]
I know, hence the feature request.

**Comment by webron** [comment]
It's unlikely we'll implement it any time soon. If it's important to you, I'd suggest you look into it yourself.

**Comment by webron** [comment]
Closing for new. If anyone want to submit a PR that implements this, we'd be happy to review.
