### ISSUE TITLE
Auth button doesn't indicate missing OAuth2 scopes anymore

### ISSUE THREAD

**Issue by frol** [swagger-api/swagger-ui#2664]
There used to be a warning sign ([yellow (!)](https://github.com/swagger-api/swagger-ui/blob/f321c62edc53fc5e51fbe08d813921820f1a85db/src/main/html/images/explorer_icons.png)) when a user is authenticated, but OAuth2 scopes are not sufficient.

Looking at the code: https://github.com/swagger-api/swagger-ui/blob/f321c62edc53fc5e51fbe08d813921820f1a85db/src/main/template/auth_button_operation.handlebars it seems that this logic is lost. Is it intentional?

**Comment by webron** [comment]
Can you check the latest master?

**Comment by frol** [comment]
@webron #2774 blocks me in my attempts working with OAuth2.

**Comment by webron** [comment]
@frol what about now?

**Comment by frol** [comment]
@webron I will give it a try later today.

**Comment by frol** [comment]
@webron I have checked it and discovered another bug in OAuth2 Password Flow, so I PRed #3226. Once I resolved that I could proceed to test this one, and the "lock" indicator still does not indicate that there are missing OAuth2 scopes. They are either all locked or all unlocked.

**Comment by shockey** [comment]
This sounds like v2, so I'm closing. If I'm mistaken, bump this thread and I'll reopen!

**Comment by richardctrimble** [comment]
This is still an issue in v3

**Comment by ricardoccpaiva** [comment]
any news on this?

**Comment by shockey** [comment]
Folks: per the [Swagger Contribution Guide](https://github.com/swagger-api/.github/blob/master/CONTRIBUTING.md#voting), please refrain from making comments that only serve to bump the issue or indicate interest — use Reactions to vote for issues instead. Thanks!

**Comment by ponelat** [comment]
Going to consolidate this into #5062 as I believe it captures the essence of it (ie: indicating missing scopes)
