### ISSUE TITLE
jsonEditor: true disallows optional parameters

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-ui#2665]
In version 2.2.10, I've set the jsonEditor property to true as this makes it easier to fill in details for using the "Try it out" button.  However, there seems to be no way to simply leave off a property at that point, meaning all the optional items are still sent a value of an empty string.

That's not good as there's a big difference between not sending a parameter and sending an empty string, which on something like a PATCH call would mean blanking out the existing set value.

**Comment by webron** [comment]
No longer relevant in the new UI.

**Comment by x-iron** [comment]
Hi @webron , do you mean in the new version of swagger, this issue has been fixed?

**Comment by zedrdave** [comment]
I am also running into this issue (with Swagger v.2.0) and can't seem to figure out how to get the JSON editor to skip optional fields (especially non-strings) that are left empty (it sends an empty string no matter what).

Setting `x-nullable:true` does not seem to help either.

@webron Could you point me in the direction of the UI feature that addresses that?
