### ISSUE TITLE
Not a Valid Parameter Definition - Many Errors, yaml attached

### ISSUE THREAD

**Issue by windswept321** [swagger-api/swagger-ui#2666]
My yaml file gives a lot of errors in the online editor for reasons I can't seem to figure out.
Attached is a simplified version.

[swaggeryaml.yaml.zip](https://github.com/swagger-api/swagger-ui/files/778912/swaggeryaml.yaml.zip)

**Comment by webron** [comment]
Please open the ticket on swagger-editor.
