### ISSUE TITLE
Issue parsing the swagger.json

### ISSUE THREAD

**Issue by GianfrancoFrau** [swagger-api/swagger-ui#2667]
When reporting a bug, please provide the following details:
- swagger-ui version: 2.2.10 
- a swagger file reproducing the issue: https://m3.vivocha.com/a/gianfranco/api/v2/swagger.json

Hi! Using the latest version of swagger-ui we're encountering this issue

<img width="1207" alt="schermata 2017-02-16 alle 16 04 26" src="https://cloud.githubusercontent.com/assets/5883607/23026604/10a9c47e-f462-11e6-8c42-27504875b355.png">

[swagger.json here](https://m3.vivocha.com/a/gianfranco/api/v2/swagger.json) and the [json schema for Client resource here](https://m3.vivocha.com/a/gianfranco/api/v2/schemas/client)

**Comment by webron** [comment]
Loads well in 3.X!
