### ISSUE TITLE
UI confused by multiple $ref schema with same file name

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#2668]
Given an Open API document which references (`$ref`) multiple external schema which differ in URL but not in the last path element (all use .`../schema.json`), the  Swagger UI gets confused and does not resolve the schema correctly... "last one wins"

```
swagger: "2.0"
info:
  version: "1"
  title: A Sample API
  description: swagger tools ignore schema with different paths

basePath: '/sample'
paths:
  /thing:
    post:
      summary: Return a thing
      description: Return the JSON representation of a `thing` resource.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/model'
      responses:
        '200':
          description: OK
definitions:
  model:
    title: A sample model
    description: A model that which represents a `thing` resource. contains members a, b, and a version.
    properties:
       a:
          description: Model **A**
          type: object
          $ref: http://localhost/open-apis/schemas/a/schema.json
       b:
          description: Model **B**
          type: object
          $ref: http://localhost/open-apis/schemas/b/schema.json
       version:
          description: "[semantic version](http://semver.org/)"
          type: string
```

`http://localhost/open-apis/schemas/a/schema.json` contains:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id" : "http://swagger.na.sas.com/open-apis/schemas/a/schema.json",
    "title": "Link",
    "description": "Model schema for **A**",
    "properties": {
        "foo": {
            "type": "string",
            "description": "some data...."
        }
    }
}
```
and `http://localhost/open-apis/schemas/b/schema.json` contains

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id" : "http://localhost/open-apis/schemas/b/schema.json",
    "title": "Link",
    "description": "Model schema for **B**",
    "properties": {
        "bar": {
            "type": "string",
            "description": "some other data...."
        }
    }
}

```
Notice that while the model correctly shows the titles for the two different schemas, the Example Value body (copied into the text area in the sceeenshot below) applies the wrong schema `http://localhost/open-apis/schemas/b/schema.json` to the member `a`:
```
{
  "a": {
    "bar": "string"
  },
  "b": {
    "bar": "string"
  },
  "version": "string"
}
```
(instead of `"foo" : "string"` for member `"a"`)

This forces us to use a workaround of using unique file names on all the schema documents, rather than unique *path* names with file names `.../schema.json`.

Also note that the UI abbreviates the URI to just 'schema.json' so that they are not differentiable by name (only by title)

![swagger-ui-schema-confusion](https://cloud.githubusercontent.com/assets/545944/23034759/d8826e96-f44a-11e6-8e07-0c3700f95558.png)

Something similar occurs in swagger-codegen
[swagger-codegen/issues/4768](https://github.com/swagger-api/swagger-codegen/issues/4768).

Swagger UI is "version": "2.2.10",

**Comment by webron** [comment]
This is resolved in the new UI.
