### ISSUE TITLE
Cannot View data from table created in Microsoft Azure in swagger-ui

### ISSUE THREAD

**Issue by kshitijakarkar** [swagger-api/swagger-ui#2669]
swagger-ui api version: 2.0.0
OS : Windows 10 64-bit

I created a mobile app in Microsoft Azure and deployed it using swagger-ui. My app has database connected to it with 2 tables : categories and subcategories. subcategories has foreign key constraint on id_fk that references to id in categories table. I can view data of both tables in Azure but I have problems viewing data from subcategories table in swagger-ui. Need help on it.

I am attaching screenshots of Microsoft Azure, I can view data in tables.
I am also attaching link of swagger-ui. I can see data in categories after clicking try it out  but not in subcategories.
http://frugalapp.azurewebsites.net/swagger/ui/?url=http://frugalapp.azurewebsites.net/swagger#/

![categories](https://cloud.githubusercontent.com/assets/10734173/23040229/6c21f28a-f445-11e6-85a6-c3fa513f7420.png)
![subcategories](https://cloud.githubusercontent.com/assets/10734173/23040230/6c243a7c-f445-11e6-88fa-90d0a8ff9de2.png)

**Comment by darrelmiller** [comment]
Hi @kshitijakarkar 

You may find that the MSDN forum for Mobile Apps https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=azuremobile or the Azure-mobile-services tag on StackOverflow http://stackoverflow.com/questions/tagged/azure-mobile-services would be a better place to ask about this as it looks like it is more likely an issue with that service than Swagger-ui.  If you don't get an answer there, ping me and I'll find someone from the team who can help.

**Comment by kshitijakarkar** [comment]
Hello @darrelmiller ,
Thank you for quick response. I went through the links you provided, though useful I could find very little related to my issue. I am new to Azure as well as Swagger-ui and there is high possibility that my implementation is not correct. I did contact Azure support and he assured me that problem is in the end service and not on the portal. He also encouraged me to open an issue here. I can use some help from your team. 
Thank you.

**Comment by webron** [comment]
Unfortunately there's not much we can do. Swagger-UI simply takes whatever you feed to it and presents it. If it's not generated from the Azure side, there's nothing we can do about it. Things like database and such are irrelevant to us - it's more about what's actually being produced by your app, and that's not something we can answer.
