### ISSUE TITLE
additionalQueryStringParameters not provided for OAuth2Scheme of Flow = application

### ISSUE THREAD

**Issue by ckittel** [swagger-api/swagger-ui#2671]
Version: `Swashbuckle.AspNetCore` (1.0.0-rc1) via NuGet

In my `Startup.cs` `Configure` method, I have the following for swagger:
```csharp
app.UseSwagger();

app.UseSwaggerUi(c =>
{
    c.ConfigureOAuth2("MyClientID", "MyClientSecret",  string.Empty, "Swagger UI", 
            additionalQueryStringParameters: new Dictionary<string, string>
            {
                {"audience", "MyAudienceValue"}
            });
}
```
and in `ConfigureServices` I have:
```csharp            
services.AddSwaggerGen(c =>
{
    c.AddSecurityDefinition("oauth2", new OAuth2Scheme
    {
        Type = "oauth2",
        Flow = "application",
        TokenUrl = "https://myauthservice.com/oauth/token"
    });
});
```

However, in the UI when it goes to make the HTTP POST off to the `TokenUrl`, the values in `additionalQueryStringPrameters` are not included in the body.
```
client_id=MyClientId&client_secret=MyClientSecret&scope=&grant_type=client_credentials
```
I was expecting the HTTP POST body to look like
```
client_id=MyClientId&client_secret=MyClientSecret&scope=&grant_type=client_credentials&audience=MyAudienceValue
```
Am I doing something wrong, or is this parameter not working with `Flow = "application"`?  Is there a reasonable workaround?

**Comment by ckittel** [comment]
Sorry, posted to wrong project, meant to post on [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/304).  Closing.

**Comment by ckittel** [comment]
So, after opening the issue with the Swashbuckle team, they referred me back to the Swagger UI project proper, siting the usage of `additionalQueryStringParameters` in conjunction with `Flow = "application"` is something that is handled in this project.  So reopening my original post.

Thoughts?

**Comment by webron** [comment]
Can you try the latest master?

**Comment by ckittel** [comment]
@webron Since I'm using this as part of Swashbuckle.AspNetCore, I'll report back once this makes its way downstream.  Thanks again.  (Issue can stay closed.)

**Comment by webron** [comment]
@ckittel - thanks. Since this is a fresh release, we're bound to make frequent changes in the upcoming months (so far, we've had weekly releases). I'd highly recommend, for testing purposes, to use our repo directly and not rely on third party distributions as those may not be updated as quickly as we do.
