### ISSUE TITLE
Improve the presentation of the "contact" information content

### ISSUE THREAD

**Issue by banders** [swagger-api/swagger-ui#2673]
Using swagger-ui 2.2.8

The contact information from a swagger 2.0 file is presented in a way that is not always ideal.  For example, given [this swagger file](https://raw.githubusercontent.com/banders/api-specs/master/bcgnws/bcgnws.json)
`

the contact information is rendered as:

![image](https://cloud.githubusercontent.com/assets/1737873/23086978/6ac03696-f525-11e6-80b0-73c038c7ecb8.png)

This presentation is not ideal because a) there is inadequate spacing between the "external doc", the "contact" info and the "license" and because b) the email address in the "contact" section does not belong to a "developer".

Can we please improve the page layout for display of the "info" content?

**Comment by webron** [comment]
@Minasokoni can you check the linked PR and see if it makes sense? If so, we can migrate the changes to 3.X.

**Comment by webron** [comment]
This shouldn't be an issue in the new UI - if you have further feedback, please add a comment or submit a new ticket.
