### ISSUE TITLE
Issue while exploring api-docs :  Uncaught TypeError: Cannot read property 'indexOf' of null 

### ISSUE THREAD

**Issue by epikosrest** [swagger-api/swagger-ui#2678]
- swagger-ui : Swagger api-docs shows "apiVersion":"1.0","swaggerVersion":"1.2"
- a swagger file reproducing the issue

Api doc return response with json output while accessing following url
http://localhost:8081/Service/api-docs

The json response is 
{"apiVersion":"1.0","swaggerVersion":"1.2","apis":[{"path":"/test","description":"Example"}],"info":{"title":"Apis","description":"Resources"}}

But while exploring same url i.e. http://localhost:8081/Service/api-docs
from swagger ui (http://15mbp-12180:8081/docs/ , Note this shows swagger UI)
I am seeing following exception

Uncaught TypeError: Cannot read property 'indexOf' of null
    at module.exports.SwaggerSpecConverter.declaration (operation.js:424)
    at module.exports.SwaggerSpecConverter.convert (operation.js:410)
    at response (resolver.js:315)
    at responseInterceptor (schema-markup.js:26)
    at obj.on.response (schema-markup.js:30)
    at schema-markup.js:232
    at Request.callback (client.js:1192)
    at Request.<anonymous> (client.js:1192)
    at Request.Emitter.emit (dumper.js:648)
    at XMLHttpRequest.xhr.onreadystatechange (client.js:1192)

Any Idea why the value is null ? Also the code that caught this exception is (based on developers tool source output is)
 
Operation.prototype.supportedSubmitMethods = function () {
  return this.parent.supportedSubmitMethods;
};

and Swagger Ui got stuck with message
"fetching resource list: http://localhost:8081/EpikosRestService/api-docs; Please wait."

**Comment by webron** [comment]
You're using an older spec version - 1.2. It's possible that the sub-paths are inaccessible or something is wrong with them (for example, http://localhost:8081/Service/api-docs/test). It's highly recommended you find the way to upgrade to the latest version of the spec.

**Comment by epikosrest** [comment]
Can you help me which spec version I should be using in  this case ?
I have following dependency in the service pom , which generate api-docs . Also I cloned and build latest swagger ui and have copied the dist folder content which shows the UI just fine but expore is not working. 

<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-jersey2-jaxrs</artifactId>
			<version>1.5.8</version>
		</dependency>

        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jersey2-jaxrs_2.10</artifactId>
            <version>1.3.13</version>
            <scope>compile</scope>
        </dependency>

**Comment by webron** [comment]
That's really old version of swagger-core. Take a look at https://github.com/swagger-api/swagger-core/wiki/1.3--1.5-Migration.

**Comment by nitinaryal** [comment]
Thanks webron for pointer. Please close the issue.

**Comment by epikosrest** [comment]
Thanks webron for pointer.
