### ISSUE TITLE
Add text-input and Headers for Content-Type=text/plain

### ISSUE THREAD

**Issue by 0xC0DEBA5E** [swagger-api/swagger-ui#2681]
When Content-Type is set to `text/plain` or `text/plain; charset=utf-8`:
- the Content-Type header of the request is missing. 
- there is no way to include plain-text in the request as the normal param-input values are ignored.

Also, when you don't select anything, there is an empty `Content-Type:`-Header in the request, which could lead to unexpected results.

Suggestion: Add a `<input type="text" ... />` for the content of the request (instead of parameter input tags), when Content-Type is set to  an "unsupported" Mime-Type.
```yaml
# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Person

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /person:
    # This is a HTTP operation
    post:
      # Describe this verb here. Note: you can use markdown
      description: |
        Create new `Person`
      # This is array of GET operation parameters:
      
      consumes:
        - 'text/plain; charset=utf-8'
        - 'application/json'
      
      parameters:
        # An example parameter that is in query and is required
        -
          name: name
          in: body
          description: Size of array
          required: true
          schema:
            type: string
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: string
```
P.S.: I'm using `v2.10.4` of the swagger-editor.

**Comment by webron** [comment]
Thank you for the suggestion, but it looks like you meant to open this on swagger-editor. This is swagger-ui. Please resubmit on the other project.

**Comment by 0xC0DEBA5E** [comment]
Oops, and there was already an open issue for this. I added it there.
Issue was here: [Posting body as text/plain not working](https://github.com/swagger-api/swagger-editor/issues/1153)

**Comment by webron** [comment]
Thanks!

**Comment by kamil-kielczewski** [comment]
I use [this](https://stackoverflow.com/a/48413161/860099)

 *     consumes={"multipart/form-data"},
 *     produces={"text/plain, application/json"},
