### ISSUE TITLE
POST String body gets enclosed with additional quotes when using jsonEditor

### ISSUE THREAD

**Issue by StasKolodyuk** [swagger-api/swagger-ui#2682]
Hi!

When trying to post string value via swagger-ui with jsonEditor enabled, the request body gets enclosed into additional quotes.

Here's the link to original issue expressing more details: https://github.com/springfox/springfox/issues/1684

**Comment by webron** [comment]
No longer relevant with the new UI.

**Comment by buzea** [comment]
Can anyone provide a fix version for this bug?
