### ISSUE TITLE
Cannot see rendered content

### ISSUE THREAD

**Issue by marcosmoreno** [swagger-api/swagger-ui#2686]
We are trying to start documenting with swagger in confluence and have a swagger file. My colleagues are viewing the swagger content  without an issue. However, as I try to read the page I see nothing but the title (when I edit the page I see the content and everything is there) and get the following in the debug console:

`POST https://ourcompanydomain.atlassian.net/wiki/plugins/servlet/ac/net.oharagroup.confluence.plugins.confluence-open-api/open-api5757numbersnumbers95841330 404 (Not Found)`

We have discarded permission options as I am trying with an administrator user. Also tried with different browsers (Chrome and Firefox) with same result. No specific javascript blockers whatsoever. Any idea on what can be happening?

- swagger-ui version: 1.1.4-AC (test license)
- a swagger file reproducing the issue: not relevant, as it seems to fail before trying to render the file.

Any help would be appreciated!

**Comment by webron** [comment]
Umm, what's 1.1.4-AC (test license)?

**Comment by marcosmoreno** [comment]
The version is the number that appears in the confluence plugin page. The "test license" is because it says the subscription is due in one month, so I assume we are still not engaged in a yearly contract.

**Comment by webron** [comment]
If you're using some sort of a confluence plugin, you should open the ticket with its provider. We have nothing to do with it and can't really debug issues related to it.

**Comment by marcosmoreno** [comment]
Oooops, I was pointed here by the colleague that installed the plugin in my company. I will do my research and ask the right people. Thank you and sorry for the noise!
