### ISSUE TITLE
SwUI cors issue, non-preflight request expecting incorrect response headers.

### ISSUE THREAD

**Issue by vikramaroskar** [swagger-api/swagger-ui#2693]
When sending a GET request, (not an OPTIONS request), I'm getting CORS error, even though Chrome shows STATUS is 200.

![swa_ui_issue](https://cloud.githubusercontent.com/assets/19361170/23329517/3d96b050-fb60-11e6-9d6f-aaf492a746cc.png)

The problem as far as I can see, is Swagger UI is expecting 
- Access-Control-Allow-Headers 
- Access-Control-Allow-Methods

even though it's sending a GET Request for <url>/v2/api-docs 
and not OPTIONS for the preflight checks. 

My understanding is Access-Control-Allow-Origin should be always returned by any CORS server and 
Access-Control-Allow-Headers & Access-Control-Allow-Methods should only be returned when making a OPTIONS request.
(reference: http://restlet.com/company/blog/2015/12/15/understanding-and-using-cors/)

As an additional check, my current setup works correctly in POSTMAN ui..
i.e. only when Access-Control-Allow-Origin is returned, even then the response json is correctly rendered.

**Comment by webron** [comment]
It's actually likely that this is not a CORS issue at all, based on your screenshot. Check the browser console for errors.

**Comment by vikramaroskar** [comment]
Thanks @webron 

There was a cors issue initially. But, I managed to resolve it, from the server side.
So closing it.
