### ISSUE TITLE
allOf support problem

### ISSUE THREAD

**Issue by zcb22000** [swagger-api/swagger-ui#2697]
When reporting a bug, please provide the following details:
- swagger-ui version : master
- a swagger file reproducing the issue
In my definition, i used allOf to support extend class.
My yaml is : 
  QueryDeviceDataHistoryDTOCloud2NA:
    required:
    - devices
    allOf:
    - $ref: './commonDF.yaml#/definitions/PageDTO'
    - properties:
        devices: 
          type: array
          items:
            $ref: '#/definitions/DeviceDataHistoryDTO'

But it does not resovled in html of DeviceDataHistoryDTO, it display as follow: 
QueryDeviceDataHistoryDTOCloud2NA {
devices (Array[http://localhost:8090/swagger-ui/yaml/./definitions/deviceManageDF.yaml#/definitions/DeviceDataHistoryDTO]),
totalCount (integer, optional): totalCount  ,
pageNo (integer, optional): pageNo ,
pageSize (integer, optional): pageSize 
}
http://localhost:8090/swagger-ui/yaml/./definitions/deviceManageDF.yaml#/definitions/DeviceDataHistoryDTO {}

And it can accessed fine of http://localhost:8090/swagger-ui/yaml/./definitions/deviceManageDF.yaml.

Is there any error?

**Comment by zcb22000** [comment]
Does it not supported parent class where using allOf in swagger ui with java ?

**Comment by webron** [comment]
Should be resolved in 3.X.
