### ISSUE TITLE
How to write url in swagger UI?

### ISSUE THREAD

**Issue by litttlefisher** [swagger-api/swagger-ui#2698]
v2.2.10

I need "HTTP GET" to qry something, and query param is a dto such as "class Person{}",but I do not know how to use in swagger ui.

<img width="1005" alt="qq20170227-172712 2x" src="https://cloud.githubusercontent.com/assets/19563352/23355713/05677ea4-fd12-11e6-8a09-2498ccd0ebfa.png">

How can i do?

Otherwise, it is diffcult to use English to new issue for me!

**Comment by fehguy** [comment]
GET does not support a `body` parameter.
