### ISSUE TITLE
Sqgger Post with [FromBody] object is always null

### ISSUE THREAD

**Issue by PvAsh** [swagger-api/swagger-ui#2699]
Hi I have MVC WEbapi application and recently another developer has added swagger for api documentations.
I have below two references in my website app.
Swashbuckle.Core.Net45.5.2.1
Swashbuckle.Net45.5.2.1

swagger docs are working fab as far as get methods are concerned. But with POST methods only get the object values when posted in FromUri . When posted with FromBody they are always null. Not sure where I need to start from as I am bit new to this. any help would appreciate.

**Comment by webron** [comment]
Please test master.
