### ISSUE TITLE
Ampersand character being escaped in rendered documentation

### ISSUE THREAD

**Issue by brylie** [swagger-api/swagger-ui#2700]
When reporting a bug, please provide the following details:
- swagger-ui version: ^2.2.10
- a swagger file reproducing the issue

One of our community members reported that Swagger UI is escaping ampersand characters (&) in their swagger document:

![screenshot_20170227_152130](https://cloud.githubusercontent.com/assets/17307/23362945/ca67b0fa-fd00-11e6-9f4c-3ac144e80f4f.png)

It seems that contents of the `description` field within the `info` object are being escaped. How can they format the description text, so that the ampersand is rendered correctly?

**Comment by webron** [comment]
Can you check the latest master?

**Comment by brylie** [comment]
We have an [issue to upgrade Swagger UI to 3.x](https://github.com/apinf/platform/issues/2349) in our project.

**Comment by webron** [comment]
@brylie any update?

**Comment by brylie** [comment]
cc: @marla-singer

**Comment by sdwr98** [comment]
I am seeing this issue with swagger-ui version 3.2.0

**Comment by shockey** [comment]
https://github.com/swagger-api/swagger-ui/pull/3712 may solve this.
