### ISSUE TITLE
Using different field requirements for the same model in request vs response

### ISSUE THREAD

**Issue by egodolja** [swagger-api/swagger-ui#2702]
I'm wondering if the following scenario is possible using Swagger2.0:
Request:
TestRequest  : {
      "field1": "f1"
      "commonModel": {
             "field2": "f2",
             "field3": "f3",
             "field4": "f4",
             "field5": "f5"
       }
}
Response:
TestResponse : {
     "field6" : "f6",
     "commonModel" : {
             "field2": "f2",
             "field3": "f3",
             "field4": "f4",
             "field5": "f5"
      }
}
"field5", inside of CommonModel, is not an accepted field in the request, however it is being populated in the response. Is there a way to indicate in the swagger that "field5" is not accepted in the request so as to 
not cause confusion for the user and avoid unnecessary validation for a field that's not accepted.

**Comment by webron** [comment]
Sounds like [`readOnly`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaReadOnly).
