### ISSUE TITLE
Missing Property Descriptions, referenced from external assemblies, on Swagger UI

### ISSUE THREAD

**Issue by shashidhardasyam** [swagger-api/swagger-ui#2704]
I am using Swagger in a Web Api project and here is what i see in Swagger UI.

![capture](https://cloud.githubusercontent.com/assets/15112304/23594372/7a7c7f58-01e7-11e7-98bc-0ebad10e6a5d.PNG)

Problem is that the class, 'Remark', is missing property descriptions. It actually belongs to an external library, referenced in the project. is there a way to fetch those descriptions in SwaggerUI?
I use Swashbuckle v5.5.3 package.

**Comment by webron** [comment]
Can't do much without a spec to reproduce the issue.
