### ISSUE TITLE
Stray comma in model listing when using list markdown

### ISSUE THREAD

**Issue by pauldzy** [swagger-api/swagger-ui#2705]
When a swagger definition description includes a markdown list, a stray comma appears at the end of the description. This can be seen here
http://petstore.swagger.io/?url=https://api.swaggerhub.com/apis/pauldzy/StrayComma/1.0.0
under the inventory model name definition. It is also visible on SwaggerHub interface in the same place.

Apologies if this is nitpicky.

Swagger-codegen version

version v2.2.10

Steps to reproduce

http://petstore.swagger.io/?url=https://api.swaggerhub.com/apis/pauldzy/StrayComma/1.0.0

Related issues

I could not find anything similar in the swagger-codegen issues.

Thanks,
Paul

**Comment by webron** [comment]
@pauldzy - it's not stray, but it does look awkward. If you notice, there's a comma at the end of every property. Take a look at this:

<img width="541" alt="screenshot 2017-03-06 09 19 48" src="https://cloud.githubusercontent.com/assets/241629/23621070/1b940134-024e-11e7-84fa-02a4c189d5b4.png">

The good news this is changing in our new version and will no longer be an issue.

**Comment by pauldzy** [comment]
Thanks for the fast response.  That makes sense. 

Cheers,
Paul
