### ISSUE TITLE
Update docker hub to include v2.2.10 tag

### ISSUE THREAD

**Issue by hvindin** [swagger-api/swagger-ui#2706]
Dockerhub currently only has 2 tags, [latest and v2.2.9](https://hub.docker.com/r/swaggerapi/swagger-ui/tags/).

Tag [v2.2.10](https://github.com/swagger-api/swagger-ui/tree/v2.2.10) was cut 2017/01/04 so it would be nice for it to be published the same as v2.2.9

**Comment by webron** [comment]
Too late, we're ahead. ;)
