### ISSUE TITLE
@Api(tags="") tags is chinese

### ISSUE THREAD

**Issue by lvhh0** [swagger-api/swagger-ui#2708]
i am using swagger ui 2.2.10 , and i met a problem is that i add a @Api(tags="")  tags is chinese when i click  request url like 'POST /api/upload/upload' is not open

**Comment by webron** [comment]
Issue is unclear.

**Comment by dilipkrish** [comment]
@webron I think the problem here is that when swagger.json encounters an unicode string in the tags. It doesnt expend the operations. You end up with a javascript error.

**Comment by dilipkrish** [comment]
Here is a more detailed report https://github.com/springfox/springfox/issues/1580

**Comment by webron** [comment]
@dilipkrish thanks for the explanation, but without a sample spec we can't do much to test it. Plus, I'd ask the user to test with 3.x first.

**Comment by kojz** [comment]
> @dilipkrish thanks for the explanation, but without a sample spec we can't do much to test it. Plus, I'd ask the user to test with 3.x first.

swagger ui 2.9.2  not support tags chinese
