### ISSUE TITLE
Feature request: better handling of large swagger-json

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#2710]
So, my swagger-json is huge (3-4 MB and growing). Let's not talk about whether there is anything in there that possibly shouldn't be: it validates, if that helps accept this for a minute. There are over hundred tags within it, with several endpoints each, each with a dozen or so object definitions. I'm working on presenting jsonapi.org-structured data.

I have 6 different swagger-ui presentations: this project being one, ReDoc, another 3 that are likely forks of this project (cause they look similar), and another one totally different presentation.

This one and the "responsive" flavor of the same perform the worst: download-time aside, processing swagger-json takes minutes. Literally. Every time. Chrome. I have file handlers set up to instruct the browser to cache every single file, even swagger-json (which does happen), so downloading time is not relevant here.

I don't have exact measurements to give you, but when I said "minutes", I meant it: 3+. I was hoping you can test or plan some improvements.. I'm willing to attach the swagger-json that I'm working with, if you'd like to see how that performs for you.

I don't want to be or sound ungrateful: I am getting this for free, but I also want to help by giving feedback. My previous work-around for this exact same problem was to section my swagger-json by tag,  embed some html/markdown into swagger-json, targetting this particular ui and this particular problem, then heavily modify swagger-ui html, js and css to work with it and properly link between those sectioned tag-pages. This time around (this is my 2nd attempt at the same project), I am trying to avoid modifying swagger-ui (of any of the 6 flavors) beyond basic configuration (otherwise, it becomes a big maintenance problem to follow up with upgrades).

Swagger 3 and swagger-ui-3 were mentioned recently as coming; I was hoping that this parsing and rendering problem will be taken into consideration.

Thanks.

**Comment by fehguy** [comment]
Hi @hlubovac we are releasing a new library to read the definitions.  If you want to share it (privately if you like), it would be very helpful for performance testing.

**Comment by hlubovac** [comment]
I sent that info to your private email. Let me know if  you didn't get it, please.

**Comment by webron** [comment]
@hlubovac can you try the latest master?

**Comment by hlubovac** [comment]
This issue was reported by myself relative to the behavior of v2. If v2 is being retired, then it's ok to close this.

**Comment by webron** [comment]
Thanks.
