### ISSUE TITLE
Error when trying "PUT" endpoint from swagger-ui. Working with Postman.

### ISSUE THREAD

**Issue by JFCote** [swagger-api/swagger-ui#2713]
I'm using swagger-ui from Maven using this: "org.webjars" % "swagger-ui" % "2.2.8"

I don't know if it's a feature or a bug and couldn't find anything about this in my research. I discovered that in swagger-ui, you **need** to have a body parameter in a PUT request. Is this normal?

My swagger.yaml is perfectly valid and I haven't seen in any documentation that a PUT request needs to have a body parameter. I understand why it make sense to have one but why is it mandatory?

When I do "Try it out!" in swagger-ui, I receive an HTML instead of json and it don't even reach my server code. In the HTML that I receive, there is this line:

```html
<p id="detail">
            For request 'PUT /api/actors/pools/reset' [Error decoding json body: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@113644cc; line: 1, column: 0]]
        </p>
```

As for "Why do you have a PUT without a body? PUT is for update after all, so you need data!". I agree but my case is a "reset" call. It take the state of an existing "pool" object and reset it to  default values. So in a way, it is clearly an update. I can get around this by creating an empty body but I want to know why swagger-ui enforce this.

When I try the same request in Postman, everything works as expected and my code is reach and it returns the expected json.

Here is what the json looks like for this endpoint:

```json
"/api/actors/pools/reset" : {
      "put" : {
        "tags" : [ "Actors" ],
        "summary" : "Reset the actor pools",
        "description" : "",
        "operationId" : "resetPools",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/ResponseMeta"
            }
          }
        }
      }
    },
```

**Comment by webron** [comment]
We don't manage those webjars and I have no idea what version is included there. I can guess it's 2.2.8 but who knows.

First try the latest master from this repository. If you still have an issue with it, please provide a full minimal spec we can use to test and not a snippet.

**Comment by JFCote** [comment]
@webron : Perfect. I will try this tomorrow. I'm also pretty sure that the webjar uses the same versioning for simplicity.
But I will try the master and see if the issue can be replicated. 
Thanks!

**Comment by JFCote** [comment]
@webron : I have reproduced with the master.

To reproduce, use the json below. Just click on "Try it out" and **make sure your server has a real endpoint at this address** (or modify the path to a real put endpoint on your server which don't need any parameter). If you don't, you will receive this error "Action Not Found" which has nothing to do with this bug (it's just a 404).

```json
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "Sample API"
    },
    "paths": {
        "/api/actors/pools/reset": {
		  "put": {
			"tags": [
			  "Actors"
			],
			"summary": "Reset the actor pools",
			"description": "",
			"operationId": "resetPools",
			"responses": {
			  "200": {
				"description": "OK",
				"schema": {
				  "$ref": "#/definitions/ResponseMeta"
				}
			  }
			}
		  }
		}
    },
	"definitions": {
		"Error": {
		  "type": "object",
		  "required": [
			"type"
		  ],
		  "properties": {
			"type": {
			  "type": "string"
			},
			"details": {
			  "type": "string"
			},
			"exception": {
			  "type": "string"
			}
		  }
		},
		"ResponseMeta": {
		  "type": "object",
		  "required": [
			"code"
		  ],
		  "properties": {
			"code": {
			  "type": "string"
			},
			"details": {
			  "type": "string"
			},
			"exception": {
			  "type": "string"
			},
			"errors": {
			  "type": "array",
			  "items": {
				"$ref": "#/definitions/Error"
			  }
			}
		  }
		}
	}
}
```

Here is the full HTML I receive, for reference:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Bad Request</title>
        <link rel="shortcut icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAlFJREFUeNqUU8tOFEEUPVVdNV3dPe8xYRBnjGhmBgKjKzCIiQvBoIaNbly5Z+PSv3Aj7DSiP2B0rwkLGVdGgxITSCRIJGSMEQWZR3eVt5sEFBgTb/dN1yvnnHtPNTPG4PqdHgCMXnPRSZrpSuH8vUJu4DE4rYHDGAZDX62BZttHqTiIayM3gGiXQsgYLEvATaqxU+dy1U13YXapXptpNHY8iwn8KyIAzm1KBdtRZWErpI5lEWTXp5Z/vHpZ3/wyKKwYGGOdAYwR0EZwoezTYApBEIObyELl/aE1/83cp40Pt5mxqCKrE4Ck+mVWKKcI5tA8BLEhRBKJLjez6a7MLq7XZtp+yyOawwCBtkiBVZDKzRk4NN7NQBMYPHiZDFhXY+p9ff7F961vVcnl4R5I2ykJ5XFN7Ab7Gc61VoipNBKF+PDyztu5lfrSLT/wIwCxq0CAGtXHZTzqR2jtwQiXONma6hHpj9sLT7YaPxfTXuZdBGA02Wi7FS48YiTfj+i2NhqtdhP5RC8mh2/Op7y0v6eAcWVLFT8D7kWX5S9mepp+C450MV6aWL1cGnvkxbwHtLW2B9AOkLeUd9KEDuh9fl/7CEj7YH5g+3r/lWfF9In7tPz6T4IIwBJOr1SJyIGQMZQbsh5P9uBq5VJtqHh2mo49pdw5WFoEwKWqWHacaWOjQXWGcifKo6vj5RGS6zykI587XeUIQDqJSmAp+lE4qt19W5P9o8+Lma5DcjsC8JiT607lMVkdqQ0Vyh3lHhmh52tfNy78ajXv0rgYzv8nfwswANuk+7sD/Q0aAAAAAElFTkSuQmCC">
        <style>
            html, body, pre {
                margin: 0;
                padding: 0;
                font-family: Monaco, 'Lucida Console', monospace;
                background: #ECECEC;
            }
            h1 {
                margin: 0;
                background: #AD632A;
                padding: 20px 45px;
                color: #fff;
                text-shadow: 1px 1px 1px rgba(0,0,0,.3);
                border-bottom: 1px solid #9F5805;
                font-size: 28px;
            }
            p#detail {
                margin: 0;
                padding: 15px 45px;
                background: #F6A960;
                border-top: 4px solid #D29052;
                color: #733512;
                text-shadow: 1px 1px 1px rgba(255,255,255,.3);
                font-size: 14px;
                border-bottom: 1px solid #BA7F5B;
            }
        </style>
    </head>
    <body>
        <h1>Bad Request</h1>

        <p id="detail">
            For request 'PUT /api/actors/pools/reset' [Error decoding json body: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@667bbadd; line: 1, column: 0]]
        </p>

    </body>
</html>
```

Like I said, when I try the with Postman, there is no problem. There is absolutely no code in my endpoint, just a return code 200.

If you have any more question, don't hesitate!

**Comment by webron** [comment]
Just tried it and it works as expected. I suspect the issue is with the `consumes` or `produces` not being specified. Postman might use different defaults, we default to `application/json`.

**Comment by JFCote** [comment]
@webron : Ok, that is strange... I will try to specify this when I get to work tomorrow and see if it works. Thanks!

**Comment by JFCote** [comment]
Hi @webron , I find the problem.

Swagger-ui will add in the header this: `--header 'Content-Type: application/json'` (in the curl command)

My server don't like this when there is no body at all (no payload) and that the request header has the "content-type" specified to json. It seems that by default, my server tries to open the json but since it is empty, it crash and show the html page.

I don't know if it's a problem on my side, or if swagger-ui should not send "content-type" when there is no payload at all... What do you think?

**Comment by webron** [comment]
Probably both.

**Comment by JFCote** [comment]
Ok so should we create a task for this on swagger-ui? I will try to check if the problem is in my implementation or in the core of play framework itself.

**Comment by webron** [comment]
Sounds reasonable. I checked with our upcoming version of the UI and the behavior is the same there.

**Comment by JFCote** [comment]
@webron I've been to the bottom of the issue and talked with the guys from the Play Framework. 
You can see it here: https://github.com/playframework/playframework/issues/7092

As far as I understand the problem, it seems that it's ok for Play Framework to show an error if swagger-ui indicate that it will provide a Json (content-type) and instead provides an empty body. It does not follow the RFC rule.

I'm pretty sure swagger-ui should check if there is no parameter in a PUT request and act accordingly instead of always setting the content-type to a default value.

I'll let you decide what you want to do about it!
Have a good day! :)

**Comment by shockey** [comment]
Looks like this is solved in the current v3, the example operation above yields the following cURL:

```sh
curl -X PUT "http://editor.swagger.io/api/actors/pools/reset" -H "accept: application/json"
```
