### ISSUE TITLE
Swagger-UI fails on head operations

### ISSUE THREAD

**Issue by dpeger** [swagger-api/swagger-ui#2716]
**swagger-ui version: 2.2.10 and 2.1.5**

The attached examples will either completely fail to render due to an error in the JavaScript ([swagger.json](https://github.com/swagger-api/swagger-ui/files/830573/swagger.json.txt)) or display a validation error badge in swagger-ui and the operation is not excutable ([swagger.yaml](https://github.com/swagger-api/swagger-ui/files/830574/swagger.yaml.txt)).

JavaScript error for swagger.json:
```
Uncaught TypeError: Cannot read property 'parameters' of null
    at 6.module.exports.6.Resolver.resolve (resolver.js:137)
    at response (client.js:239)
    at responseInterceptor (http.js:79)
    at 5.SwaggerHttp.execute.obj.on.response (http.js:98)
    at http.js:362
    at Request.158.Request.callback (client.js:699)
    at Request.<anonymous> (client.js:521)
    at Request.162.Emitter.emit (index.js:140)
    at XMLHttpRequest.158.Request.end.xhr.onreadystatechange (client.js:779)
```

#### Attachments:
- [swagger.json](https://github.com/swagger-api/swagger-ui/files/830573/swagger.json.txt)
- [swagger.yaml](https://github.com/swagger-api/swagger-ui/files/830574/swagger.yaml.txt)

**Comment by dpr-rec** [comment]
Both files validate fine on online.swagger.io/validate:

http://online.swagger.io/validator/debug?url=https://github.com/swagger-api/swagger-ui/files/830574/swagger.json.txt

http://online.swagger.io/validator/debug?url=https://github.com/swagger-api/swagger-ui/files/830574/swagger.yaml.txt

**Comment by dpeger** [comment]
Both files validate fine on online.swagger.io/validator:

http://online.swagger.io/validator/debug?url=https://github.com/swagger-api/swagger-ui/files/830574/swagger.json.txt

http://online.swagger.io/validator/debug?url=https://github.com/swagger-api/swagger-ui/files/830574/swagger.yaml.txt

**Comment by webron** [comment]
Your spec is not valid. Lose the `null` values.

**Comment by dpeger** [comment]
It's generated by swagger-core (1.5.12) and validates fine in the validator. So this is a core issue?

**Comment by webron** [comment]
It's a configuration issue. You didn't include the SwaggerSerializers.

**Comment by dpeger** [comment]
Could you perhaps be a little bit more specific or point me to some docu?

**Comment by dpeger** [comment]
My JSON output now looks better - no null values anymore. I had to add `io.swagger.jaxrs.listing.SwaggerSerializers` as provider to the respective JAX-RS server.

However swagger-ui now provides the API listing for both input formats (YAML and JSON) but still displays an error badge in the bottom left corner and the head operation is still not executable.

#### Attachments:
* [swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/832086/swagger.json.txt)

**Comment by webron** [comment]
Seems to work well with 3.X.
