### ISSUE TITLE
relative $ref + array of objects with $ref inside doesn't work

### ISSUE THREAD

**Issue by craffael** [swagger-api/swagger-ui#2717]
Hi,

It seems that swagger-ui has problems when it should render an array of objects where the objects again contain $ref's to other files. In fact, consider the following set of three swagger files (which should be in the same folder):

    # swagger.yaml
    swagger: '2.0'
    info:
      version: 0.0.0
      title: Simple API
    paths:
      /path:
        get:
          responses:
            200:
              description: An array of all users present in the system.
              schema:
                type: array    # Comment this line and
                items:         # this line to make it work
                  $ref: 'bar.yaml'

    # bar.yaml
    type: object
    
    properties:
      language:
          $ref: 'foo.yaml'

    # foo.yaml
    type: string
    enum: ["de", "en", "fr", "it"]

Swagger-ui renders this as
![image](https://cloud.githubusercontent.com/assets/15138672/23769220/febf6bac-050e-11e7-97b1-30f927705d45.png)
which is clearly wrong.

If I comment the marked lines in swagger.yaml, I get the expected result:
![image](https://cloud.githubusercontent.com/assets/15138672/23769269/2c12466a-050f-11e7-8dac-9ce0ed2f4072.png)

Swagger-ui Version: 2.2.10

Raffael

**Comment by webron** [comment]
This should no longer be an issue in the latest UI.
