### ISSUE TITLE
Replace %20 on Request URL for _

### ISSUE THREAD

**Issue by natyoliveira** [swagger-api/swagger-ui#2718]
Hello!

I'm getting %20 on my Resquest URL, and I want to remove it and replace for  _

For example I sent 'parameter one' as get parameter through swagger-ui.
In header we will see:
Request URL: http://.../parameter%20one

The request url is working fine, but I'm trying to replace this %20 for  _ like this:
Request URL: http://.../parameter_one

Is that possible?

**Comment by fehguy** [comment]
Create a request interceptor and you can mutate the URL.  There are tests that show how to do it here:

https://github.com/swagger-api/swagger-js/blob/master/test/request.js#L457
