### ISSUE TITLE
object-assign-pollyfill.js does not declare origin, copyright or license

### ISSUE THREAD

**Issue by mrpotes** [swagger-api/swagger-ui#2720]
The origin of the file `lib/object-assign-pollyfill.js` is unclear. It appears to be a copy-paste from [MDN's Object.assign page in May 2016](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign$revision/1062604). If this is indeed its origin (the polyfill there is character-for-character exactly the same), it would be helpful to people distributing swagger-ui to provide a comment header in the file specifying as such, and a header describing [its license terms](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses) so that they can be sure they are entitled to redistribute.

Something like:
```
/*
  This source is taken from MDN on <date>, original here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign$revision/1062604
  Any copyright is dedicated to the Public Domain. http://creativecommons.org/publicdomain/zero/1.0/
*/
```

**Comment by webron** [comment]
It might be difficult to trace back, but this should no longer be an issue with 3.X.
