### ISSUE TITLE
Open API 3.0 Spec

### ISSUE THREAD

**Issue by AlJohri** [swagger-api/swagger-ui#2723]
Hi, I was wondering if there's any plans to start supporting the OpenAPI 3.0 spec. Thanks!

https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md

**Comment by webron** [comment]
Yes.

**Comment by AlJohri** [comment]
Great, thanks @webron. Any ideas on a timeline?

**Comment by webron** [comment]
As soon as we can.

**Comment by fehguy** [comment]
@AlJohri what @webron actually meant to say is, we're updating the project structure so the 3.0 support can be added soon.  Since the spec isn't finalized we're not racing to complete it.  There are still some features that need documentation discussion and clarity.  But it is in progress now

**Comment by AlJohri** [comment]
@fehguy @webron Great to hear! Would love to see an issue label or parent issue I can track when it starts to makes sense. Appreciate the work

**Comment by webron** [comment]
Thanks! I'm not sure exactly how we're going to track it yet, but it will follow on an upcoming major update... very very soon.
