### ISSUE TITLE
response Content-Type: image/svg+xml is falsely treated as XML instead of image

### ISSUE THREAD

**Issue by LuiSlacker** [swagger-api/swagger-ui#2724]
When server response's content Type is image/svg+xml it is treated as XML instead of image and throws: 'xml.replace is not defined'

The 2nd boolean expression in line 749 in src/main/javascript/view/OperationView.js should be changed.

I'm using swagger-ui version: 2.2.10

<img width="1671" alt="screen shot 2017-03-13 at 16 55 48" src="https://cloud.githubusercontent.com/assets/6152940/23863203/64e07f36-080f-11e7-89f8-9a29a85e44a3.png">

```/**
* @swagger
* /testRoute:
*   post:
*     tags:
*       - Math
*     description: whatever
*     consumes:
*       - multipart/form-data
*     produces:
*       - image/svg+xml
*     responses:
*       200:
*         description: whatever
*/`

**Comment by webron** [comment]
Well, it _is_ an XML. If you'd like to see it being rendered, consider submitting a PR to that effect - we'll be happy to review.
