### ISSUE TITLE
Authentication popup does not work when more than one SwaggerUI added to the page

### ISSUE THREAD

**Issue by shaash** [swagger-api/swagger-ui#2727]
Authentication popup does not open when multiple swaggerUi is added to a single page. The swaggerUI is instantiated with different dom_id for each swagger, for example "swagger-ui-container-1" and the next one "swagger-ui-container-2". 

When I look at the swagger-ui.js, I see the dom_id passed to SwaggerUI is not passed on to PopupView. It started working when the code is modified to use passed in value. 

My question is how to get this change into SwaggerUI master. 

SwaggerUI Version- 2.2.10
[swagger-ui.js.zip](https://github.com/swagger-api/swagger-ui/files/844172/swagger-ui.js.zip)

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
