### ISSUE TITLE
"Try it out" POSTs formData with wrong content-type

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#2728]
Regardless of whether I specified request content type to be "multipart/form-data" or "application/x-www-form-urlencoded", the script behind the button submits as "multipart/form-data". This is based on what the browser reports. Not a big deal, but perhaps it should respect the definition. Or, perhaps I'm misunderstanding something? Thanks.

**Comment by hlubovac** [comment]
Just to add: what I stated above is true when there is a parameter with `type=file`. When there isn't one, "application/x-www-form-urlencoded" gets respected. However, unless I'm mistaken. file upload is possible as "application/x-www-form-urlencoded" also. Tthose 2 browser-provided encoding types vary in size of content they produce, but both should work. HTML-form does "application/x-www-form-urlencoded" by default, when there is `<input type=file/>` present.

**Comment by webron** [comment]
This should no longer be an issue with 3.X.
