### ISSUE TITLE
Few js files fail to load in chrome.

### ISSUE THREAD

**Issue by mgupta1308** [swagger-api/swagger-ui#2729]
When reporting a bug, please provide the following details:
- swagger-2.1.10

Following files fail to load:
![image](https://cloud.githubusercontent.com/assets/25215754/24029551/2d9de7de-0afd-11e7-965b-ff0bc80e35f7.png)

I have tried following options available on web:
1. Cleared cache
2. Checked none of the chrome extensions were blocking the files to load.
3. Loading failed with incognito tab as well which by default has extensions disabled
4. Tried upgraded version of chrome - chrome canary
5. Disabled cache and tried to load it again. 
6. Disabled hardware acceleration under system settings, the issue could be seen again.

**Comment by webron** [comment]
Please try 3.X.
