### ISSUE TITLE
Adding a config via the index.htm isn't respected. 

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#2736]
@webron @bodnia 
If I add a config, via `index.html` it gets overwritten by the pre-built config file. Which means I can't add a config via index.html, because the pre-built config file (swagger-config.yaml) is part of the bundle, unless I re-build the code without it.

**Comment by bodnia** [comment]
Default order of overriding configs: `swagger-config.yaml` -> config passed to constructor `SwaggerUIBundle(configs)`

When enabled ConfigsPlugin:
 `swagger-config.yaml` -> config passed to constructor `SwaggerUIBundle(configs)` -> `configUrl` passed to constructor `SwaggerUIBundle(configs)` -> query parameter `config` with configs url as a value

This is tested in latest master with no re-build
