### ISSUE TITLE
Supporting swagger 3.0.0-rc0

### ISSUE THREAD

**Issue by gsi-delmo** [swagger-api/swagger-ui#2741]
I can read from README.md:

_This is the new version of swagger-ui, 3.x_

Does it mean supporting of swagger 3.0.0-rc0? If not: when do you expect to release an editor to support the new version of swagger? Is already there some editor in the web?

Thanks in advance

**Comment by fehguy** [comment]
No this version does not support the 3.x spec yet. It will soon, in develop branches until the 3.0 spec is released
