### ISSUE TITLE
API spec fetching doesn't send cookies

### ISSUE THREAD

**Issue by jonathanhuet** [swagger-api/swagger-ui#2744]
I have recently updated to 3.0.2 and the fetch function that requires the API spec doesn't send the cookies in the headers load. Those cookies was sent in the previous version of Swagger UI

Notes: 
- I need cookies, because I need to perform some special actions on API spec before sending the JSON ( authentication, preformatting...) depending on those cookies ( php: session_start )
- All the requests are made in the same domain

I have fixed it by adding  in `SwaggerUIBundle.js`  after 
`(t=t.requestInterceptor(t)||t),` 
this 
`t.credentials="same-origin",`

With this, cookies are sent.

For more information, please don't doubt to ask for it

**Comment by larshp** [comment]
looks like above should be fixed in https://github.com/swagger-api/swagger-js/blob/99fcb7c0550b65b45eb67c8d744c4b2176620c49/src/http.js

**Comment by webron** [comment]
Consider submitting a PR to resolve it, and we'll review.

**Comment by jonathanhuet** [comment]
It will be nice to contribute with you! 

Do you have any place/wiki that explains how you test / compile , tools , etc ?

**Comment by larshp** [comment]
I have created a PR: https://github.com/swagger-api/swagger-js/issues/970

**Comment by larshp** [comment]
above pull request has been merged, and I have tested with 3.0.5, and it works

so I think the issue can be closed

**Comment by zhanghuanchong** [comment]
It looks like it should use `include` instead of `same-origin` now.

```js
request.credentials = 'include';
```

https://web.dev/introduction-to-fetch/#sending-credentials-with-a-fetch-request
