### ISSUE TITLE
Swagger UI on master doesn't match the demo

### ISSUE THREAD

**Issue by JLLeitschuh** [swagger-api/swagger-ui#2749]
I'm confused. The current docker image doesn't match the UI here: http://petstore.swagger.io/

Where can this version of the UI be found?

**Comment by fehguy** [comment]
you can get it on tag v3.0.2.  Soon master will be pushed to `latest`..

**Comment by JLLeitschuh** [comment]
Does this include the docker image? Is there command to grab that?

**Comment by fehguy** [comment]
Yes:

```
docker pull swaggerapi/swagger-ui:v3.0.2
docker run -p 80:8080 swaggerapi/swagger-ui
```

I'll make sure it's in `latest` shortly
