### ISSUE TITLE
Issue when rendering nullable properties

### ISSUE THREAD

**Issue by jonathanhuet** [swagger-api/swagger-ui#2759]
On properties that are nullable, there is no separation between the type and the value

**Expected result**
A separation (i.e.: blankspace or comma) between the 2 values

**Current result**
Both property types are "glued"
![image](https://cloud.githubusercontent.com/assets/20546455/24155610/a19a297c-0e54-11e7-95a9-b3879bc348b5.png)

**Steps to reproduce**
Declare the type of a property as follows:
```yaml
rate:
              type: ['integer','null']
```

Thanks

**Comment by webron** [comment]
The spec doesn't support `null` as a type, nor multi types as array (`type: [`integer`, `string`]). This is something we won't fix.

**Comment by jonathanhuet** [comment]
OK, thanks webron. You already commented it in so many issues :S . Sorry!
