### ISSUE TITLE
Validator badge is always enabled and can't be disabled

### ISSUE THREAD

**Issue by Deraen** [swagger-api/swagger-ui#2761]
Previously validator badge was hidden if the false value (`null`, `false`) was explicitly provided as `validatorUrl`, or if the spec was being loaded from localhost: https://github.com/swagger-api/swagger-ui/blob/2.x/src/main/javascript/view/MainView.js#L57-L65

New validator badge component always uses the default url if `validatorUrl` value is not truthy: https://github.com/swagger-api/swagger-ui/blob/33e5775dcff74c306904c6c7d0e2816828ba9878/src/core/components/online-validator-badge.jsx#L10

I think the default validatorUrl should only be used if the value is `undefined`, that is, when no explicit value is not set. Hiding the validator when spec is served from localhost is also good idea, as validating that going to fail always.

**Comment by i-ghost** [comment]
It was quite useful to set a value of `null` as we host static swagger-ui sites which the validator can't reach. The alternative is to host our own validator internally, which would be a waste of resources in our pipeline.

**Comment by fehguy** [comment]
The ability to remove the validator is a missing feature.  It will be addressed shortly

**Comment by bodnia** [comment]
@Deraen @i-ghost in latest `master` validator badge can be disabled with config `validatorUrl` other than `undefined`, when `undefined` - default validator is displayed

**Comment by bodnia** [comment]
fixed with https://github.com/swagger-api/swagger-ui/commit/0b668ccf2a08a3494a5a148fe53898a87c8bd5fb
