### ISSUE TITLE
petstore.swagger.io does not open in IE11 at all!

### ISSUE THREAD

**Issue by aslivker** [swagger-api/swagger-ui#2762]
Open http://petstore.swagger.io/ in IE11 - the browser page is all empty and development console shows errors.

**Comment by shockey** [comment]
Looks like some polyfills for `Promise` and `Symbol` are missing

**Comment by shockey** [comment]
Fixed in https://github.com/swagger-api/swagger-ui/releases/tag/v3.0.3
