### ISSUE TITLE
TypeError: t.toJS(...).filter is not a function when rendering swagger.json spec

### ISSUE THREAD

**Issue by JLLeitschuh** [swagger-api/swagger-ui#2763]
Example of your UI displaying our spec:

http://petstore.swagger.io/?url=https://artifactory.plexxi.com/api-docs-local/connect/swagger.json

This spec would render fine in your old version of the swagger UI but now we get a bunch of errors in the console.

`
swagger-ui-bundle.js:32753
`
```
TypeError: t.toJS(...).filter is not a function
    at swagger-ui-bundle.js:69695
    at Object.isAuthorized (swagger-ui-bundle.js:361)
    at t.value (swagger-ui-bundle.js:74970)
    at t.n.render (swagger-ui-bundle.js:32753)
    at p._renderValidatedComponentWithoutOwnerOrContext (swagger-ui-bundle.js:44622)
    at p._renderValidatedComponent (swagger-ui-bundle.js:44622)
    at p._updateRenderedComponent (swagger-ui-bundle.js:44622)
    at p._performComponentUpdate (swagger-ui-bundle.js:44622)
    at p.updateComponent (swagger-ui-bundle.js:44622)
    at p.receiveComponent (swagger-ui-bundle.js:44622)
n.render @ swagger-ui-bundle.js:32753
```

Given that there are errors according to the validator this may make sense. However, this spec rendered fine before so I'm confused why it doesn't still work.

**Comment by andrew-regan** [comment]
This can be closed. It's caused by the validation error in our schema.

**Comment by fehguy** [comment]
Would be nice to know what it was so we can provide better error messages!

**Comment by andrew-regan** [comment]
Looks like the developer that wrote our JSON file just copy/pasted the security section from here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityRequirementObject

So it was defined as this:
```
    "security": {
        "api_key": []
    },
```
Instead of being a list:
```
"security": [{"api_key": []}],
```

**Comment by webron** [comment]
Let's keep it open and see if we can handle it in a friendlier way.

**Comment by shockey** [comment]
Good news: our global try/catch for components is keeping React from dying on this render error.
