### ISSUE TITLE
Unable to get input Parameter 

### ISSUE THREAD

**Issue by AlwaysAbhl001** [swagger-api/swagger-ui#2764]
![localhost_ui](https://cloud.githubusercontent.com/assets/26591838/24185857/61048e50-0efb-11e7-8545-844379d07b02.JPG)
![onlineeditor_ui](https://cloud.githubusercontent.com/assets/26591838/24185858/615cb864-0efb-11e7-97ff-6aef3fb6b9bc.JPG)

### In my Local Host unable to get parameter input box unlike swagger online editor. what was the mistake i had done ?

**Comment by AlwaysAbhl001** [comment]
Here comes my json file

{
    "swagger": "2.0",
    "info": {
        "title": "Sample Employee Api Docmentation",
        "version": "v1"
    },
    "schemes": [
        "http"
     ],
    "consumes": [
        "application/json",
        "application/xml"
    ],
    "produces": [
        "application/json",
        "application/xml"
    ],
    "basePath": "http://localhost/",
    "paths": {
        "/api/{EmpId}": {
            "get": {
                "description": "Return the Employee based on Id",
                "operationId": "FindEmployeebyId",
                "summary": "Get Employee based on Id.",
                "parameters": [
                    {
                        "name": "EmpId",
                        "in": "path",
                        "description": "EmpId is an integer of format int32",
                        "required": true,
                        "type": "integer",
                        "paramType": "body"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response",
                        "schema": {
                            "$ref": "#/definitions/Employees"
                        }
                    }
                }
            }

        }

    },
        "definitions": {
            "Employees": {
                "type": "object",
                "properties": {
                    "EmpId": {
                        "type": "integer"
                    },
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "age": {
                        "type": "integer"
                    }
                }
            }
        }    
}

**Comment by hkosova** [comment]
In your .json file, change
```
"basePath": "http://localhost/"
```
to
```
"host": "localhost"
```

**Comment by AlwaysAbhl001** [comment]
Thanks mate.

but getting Type mismatch error ,  what was the wrong.

**Comment by AlwaysAbhl001** [comment]
Even without passing any parameter(getAll) getting same error.  

![typemismatcherror](https://cloud.githubusercontent.com/assets/26591838/24193731/5d811514-0f19-11e7-9478-14993505845c.JPG)

**Comment by hkosova** [comment]
Make sure you have
```
"host": "localhost"
```
and not
```
"host": "http://localhost"
```
`host` must not include http://, this prefix is specified by `schemes`.

**Comment by AlwaysAbhl001** [comment]
![iis_404](https://cloud.githubusercontent.com/assets/26591838/24194336/afab5dd4-0f1b-11e7-990e-b1ff39d56dc2.JPG)
![responseheader](https://cloud.githubusercontent.com/assets/26591838/24194352/bc36ae82-0f1b-11e7-8868-442beca9cde5.JPG)

When I'm using "host": "localhost"

**Comment by hkosova** [comment]
"Try it out" requires a working API server that would handle the requests - do you have one on localhost?

If your API lives on a different server, e.g. `dev-server.mycompany.com`, change the `host`, `basePath` and `schemes` appropriately.

**Comment by AlwaysAbhl001** [comment]
> "Try it out" requires a working API server that would handle the requests - do you have one on localhost? **YES**

> If your API lives on a different server, e.g. dev-server.mycompany.com, change the host, basePath and schemes appropriately.

if my sever seems -> dev-server.mycompany.com then what would be my host, bassePath and schemes ?

**Comment by AlwaysAbhl001** [comment]
Changed my host working fine for api/Employyes but for  by api/EmployeebyID call 
![errorbyid](https://cloud.githubusercontent.com/assets/26591838/24196517/125801d2-0f24-11e7-8b17-3e5fc9a04d52.JPG)

My json:

`{
    "swagger": "2.0",
    "info": {
        "title": "Sample Employee Api Docmentation",
        "version": "v1"
    },
    "schemes": [
        "http",
        "https"
     ],
    "consumes": [
        "application/json",
        "application/xml"
    ],
    "produces": [
        "application/json",
        "application/xml"
    ],
    "host": "localhost/SwaggerTest",
    "paths": {
        "/api/EmployeebyID/{Id}": {
            "get": {
                "description": "Return the Employee based on Id",
                "operationId": "FindEmployeebyId",
                "summary": "Get Employee based on Id.",
                "parameters": [
                    {
                        "name": "Id",
                        "in": "path",
                        "description": "EmpId is an integer of format int32",
                        "required": true,
                        "type": "integer",
                        "format": "int32",
                        "minimum": "1.00",
                        "maximum": "10000.0"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response",
                        "schema": {
                            "$ref": "#/definitions/Employee"
                        }
                    }
                }
            }

        },

        "/api/Employees": {
            "get": {
                "summary": "Get All Employees.",
                "Description": "Returns a list of Employees",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Employee"
                            }
                        }

                    }
                }
            }
        }

    },
        "definitions": {
            "Employee": {
                "type": "object",
                "properties": {
                    "EmpId": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "age": {
                        "type": "integer"
                    }
                }
            }
        }    
}`

**Comment by AlwaysAbhl001** [comment]
@hkosova  forget to publish my application. Now every thing working thanks every much :)

**Comment by AlwaysAbhl001** [comment]
![post](https://cloud.githubusercontent.com/assets/26591838/24239995/12f516f4-0fd6-11e7-9b84-5cb0c562a00b.JPG)

{
    "swagger": "2.0",
    "info": {
        "title": "Sample Employee Api Docmentation",
        "version": "v1"
    },
    "schemes": [
        "http",
        "https"
    ],
    "consumes": [
        "application/json",
        "application/xml"
    ],
    "produces": [
        "application/json",
        "application/xml"
    ],
    "host": "localhost/SwaggerTest",
    "paths": {
        "/api/DeleteEmployee/{id}": {
            "delete": {
                "summary": "Delete an Employee",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "An employee record deleted based on Id",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Employee Deleted Sucessfully"
                    }
                }
            }
        },
        "/api/EmployeebyID/{Id}": {
            "get": {
                "operationId": "FindEmployeebyId",
                "summary": "Get Employee based on Id",
                "parameters": [
                    {
                        "name": "Id",
                        "in": "path",
                        "description": "EmpId is an integer of format int32",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucessfull",
                        "schema": {
                            "$ref": "#/definitions/Employee"
                        }
                    }
                }
            }
        },
        "/api/Employees": {
            "get": {
                "summary": "Get All Employees.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Employee"
                            }
                        }
                    }
                }
            }
        },
        "/api/Employeebyage/{Age}": {
            "get": {
                "description": "Return the Employee based on Id",
                "summary": "Get Employee based on age.",
                "operationId": "FindEmployeebyage",
                "parameters": [
                    {
                        "name": "Age",
                        "in": "path",
                        "description": "age is an integer of format int32",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucessfull",
                        "schema": {
                            "$ref": "#/definitions/Employee"
                        }
                    }
                }
            }
        },
        "/api/AddEmployee": {
            "post": {
                "summary": "Add an Employee",
                "description": "Adds a new Employee to the employees list.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "type": "Employee",
                        "required": true,
                        "description": "An Employee to create.",
                        "schema": {
                            "$ref": "#/definitions/AddEmployee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Employee Added Sucessfully"
                    }
                }
            }
        },
        "/api/UpdateEmployee": {
            "put": {
                "summary": "Update an Employee",
                "description": "Updates an exist employee",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "type": "Employee"
                        "description": "An Employee to be updated.",
                        "schema": {
                            "$ref": "#/definitions/Employee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Employee Added Sucessfully"
                    }
                }
            }
        }

    },
    "definitions": {
        "Employee": {
            "type": "object",
            "properties": {
                "EmpId": {
                    "type": "integer",
                    "format": "int32"
                },
                "FirstName": {
                    "type": "string"
                },
                "LastName": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                }
            }
        },
        "AddEmployee": {
            "type": "object",
            "properties": { 
                 "FirstName": {
                    "type": "string"
                },
                "LastName": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                }
            }
        }
    }
}

**POST and PUT**  for both operations I'm facing this scenario, how could i over come this ?
