### ISSUE TITLE
Where is the lang dir?

### ISSUE THREAD

**Issue by NoGrief** [swagger-api/swagger-ui#2765]
for localization, the lang in 'dist' directory is missing. 3.0.2

**Comment by webron** [comment]
There's no localization support in 3.X yet.

**Comment by arthurdm** [comment]
+1

**Comment by leochr** [comment]
+1

**Comment by leochr** [comment]
@webron any idea when the localization support will be added for 3.X?

**Comment by webron** [comment]
It's not currently on our roadmap, due to time constraints. We consider the feature important though, and would be happy to review PRs that help add this feature back.

**Comment by shockey** [comment]
Closing as a duplicate of https://github.com/swagger-api/swagger-ui/issues/2488

**Comment by obender** [comment]
Hi, 
We wold like to implement that feature and contribute it, any guide how to do so?

**Comment by shockey** [comment]
@obender please join the discussion in #2488 or email me (kyle.shockey@smartbear.com) if you'd like to discuss how best to architect an internationalization feature 😄
