### ISSUE TITLE
On petstore.swagger.io the requests are listed but I can not open them

### ISSUE THREAD

**Issue by shral** [swagger-api/swagger-ui#2767]
On [petstore.swagger.io](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#/ECHO-RS) my requests are listed but I can not open them (toggle button not working). 
On the bottom of the page shows me that the schema is valid (green button)!

[hier](https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json) you can find my schema.

**Comment by fehguy** [comment]
Your spec is pretty much invalid.  Look at these references:

```
      responses:
        '200':
          description: device list
          schema:
            $ref: deviceList.schema.json
        default:
          description: unexpected error
```

Please check the validity of your spec before opening issues--the validator will ensure the _structure_ is OK but not the _content_.

**Comment by webron** [comment]
Looks like there's an issue with resolving relative references.

**Comment by buunguyen** [comment]
I think @fehguy's assessment is correct. SwaggerClient throws error because the refs are invalid. Nothing to do with relative references (which we indeed don't support yet).

**Comment by webron** [comment]
How are the refs invalid? It's simply pointing to a file name, which is relative to the location of the spec. That's a valid reference. As long as the ref value doesn't start with `#`, it's an external reference.

**Comment by buunguyen** [comment]
You're right. I misunderstood the "relative" term, thought you were talking about `../` and the likes. Looks like UI bug, JS provides a mechanism to pass in `basePath`.

**Comment by buunguyen** [comment]
The fix was released. Please check.

**Comment by shral** [comment]
It's working, thanks!
