### ISSUE TITLE
JSON Body Data Parameter Objects Smushed Together When Displayed

### ISSUE THREAD

**Issue by xquery-guy** [swagger-api/swagger-ui#2768]
I am using a $ref for the parameter object, which is correct.
It looks like the padding or the arrangement of divs is off when swagger-ui tries to create the areas where you fill in your values. Take a look at the screenshot:
![image](https://cloud.githubusercontent.com/assets/26603893/24206441/3d774b12-0eec-11e7-92be-bf4f56bab80a.png)

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-UI 2.x is no longer under development. We'd be happy to consider any suggestions about Swagger-UI 3, though!

Closing as 2.x wontfix.
