### ISSUE TITLE
default value is not working

### ISSUE THREAD

**Issue by nextofsearch** [swagger-api/swagger-ui#2773]
It's been a month or so that I haven't used swagger-ui. Today I tested out the swagger.json which used to work does not work as intended. The 'default' value specified in the definition is not set in swagger-ui for the example json. I can see 'default' field name and value in the ui but not working.

```
        property :customerId do
          key :type, :integer
          key :format, :int32
          key :default, 1
          key :description, 'Customer Id'
        end
```
I noticed the look and feel of swagger-ui has been changed so I assume something is changed. Should I use different field name instead of 'default' now?

**Comment by nextofsearch** [comment]
It seems that now swagger-ui uses 'example' field name, not default. Is this an intended behavior?

**Comment by webron** [comment]
It should use both, but example should take priority.

**Comment by bodnia** [comment]
@nextofsearch the priority is that we place example, if it's not provided then default value. If there is no example, default will be displayed in ui.
Please re-open the issue if case of any troubles
