### ISSUE TITLE
No authorization headers available in generated API server

### ISSUE THREAD

**Issue by SonnyRajagopalan** [swagger-api/swagger-ui#2775]
Hello,

I have my security definitions in the preamble section of my `swagger.yaml` like so:

    securityDefinitions:
      Bearer:
        description: |
          For accessing the API a valid JWT token must be passed in all the queries in
          the 'Authorization' header.
          A valid JWT token is generated by the API and retourned as answer of a call
          to the route /login giving a valid user & password.
          The following syntax must be used in the 'Authorization' header :
           Bearer: header.payload.signature

        type: apiKey
        name: Authorization
        in: header

And the protected routes have this:

      description: |
        blah blah
      tags:
        - Tag                  
      security:
        - Bearer: []

Now, when I launch this using Swagger UI, I see the API showing up the Security section of the authentication for getting the Authorization token. Also, all the protected routes have the check box for the associated security token (Bearer). But, when I generate the `node-js` server stub and launch the server stub, I no longer see an authentication section of the API, nor it it as being included as a parameter in the `body` for the protected routes.

Is this normal behavior? If not, what am I missing?

Any help is appreciated.

Thanks,
Sonny.

**Comment by webron** [comment]
If you have an issue with the generated code, open the ticket on [swagger-codegen](https://github.com/swagger-api/swagger-codegen). It's got nothing to do with the UI.

**Comment by SonnyRajagopalan** [comment]
FWIW, It is not clear if this is an issue in codegen or UI.

**Comment by webron** [comment]
Your definition looks correct. If it works as expected in the UI and not in the generated code... the issue is with the codegen

**Comment by SonnyRajagopalan** [comment]
Fair enough. Thanks for your quick responses. I am going to raise this in
codegen.

**Comment by SonnyRajagopalan** [comment]
<rant>
@webron Sorry to be harping on this, but this also is related to the highly anticipated feature described in https://github.com/swagger-api/swagger-ui/issues/1108

I have to second that request. This is kinda basic feature, in my opinion, but again, I harp. </rant>

**Comment by webron** [comment]
I don't see how the generate server is related to #1108.
