### ISSUE TITLE
requrest: add public/ to .npmignore

### ISSUE THREAD

**Issue by vvakame** [swagger-api/swagger-ui#2778]
I'm using swagger-ui v2.x on PaaS (GoogleAppEngine) environment via npm.
My environment can't running Docker and any other application.

I uses `dist/swagger-ui/index.html` but swagger-ui v3.x is not including any *.html.
Is there any good migration 2.x to 3.x method?
I think add public/ dir to .npmignore file is a quick way.

**Comment by antechrestos** [comment]
Same here, used to expose `index.html` in my application but now I only have a `dist`directory with a css and a js... :cry:

**Comment by webron** [comment]
Not relevant anymore. public does not exist.

**Comment by vvakame** [comment]
We need a migration method from 2 to 3.
Is there a recommended way?
