### ISSUE TITLE
Facing issues in swagger-ui.js

### ISSUE THREAD

**Issue by skaushikWebuy** [swagger-api/swagger-ui#2779]
I have been facing issues in using the swagger-ui with my swagger json files as listed below:

1. Getting CORS error as my swagger-ui hosted domain is not same as my service domain
2. Getting Curl error in js script on windows when interacting with my service.
3. Need to display my Custom error codes
4. Width of description - if it increases then the test does not wrap around
5. PUT and POST are not working
6. Want to view my custom error messages not the 'no content' message
7. Want to consider endpoint versions and environment url must switch

**Comment by webron** [comment]
1. Then fix the CORS issue. It's documented in the README.
2. I don't know what that means.
3. I don't know what that means.
4. An example would help.
5. 'Doesn't work' describes nothing.
6. I don't know what that means.
7. I don't know what that means.
