### ISSUE TITLE
How to call Authenticated API via swagger

### ISSUE THREAD

**Issue by akashjain132** [swagger-api/swagger-ui#2782]
I've created some API for my application, all the APIs are for the authenticate user except one which is used to make user authenticate.

I am maintaining all the APIs in swagger. Everything working fine. I am calling the first API to make user authenticate.

**www.example.com/endpoint/registerDevice** I got the expected result but when I called the second API and got the result as error message you are not the authenticate user then I realized that swagger is not persisted the session cookie.

Yes I've checked my API in POSTMAN chrome extension it set the session cookie in my browser but when I call it via swagger UI it doesn't.

Is there any way to maintain session in swagger?

**Comment by webron** [comment]
Which version of swagger-ui did you try it with?

**Comment by akashjain132** [comment]
I am using swagger 2.2.10

**Comment by larshp** [comment]
try latest 3.0.5, also see https://github.com/swagger-api/swagger-ui/issues/2744

**Comment by webron** [comment]
This should actually be fixed now. Please reopen if not.
