### ISSUE TITLE
Swagger UI Not Working

### ISSUE THREAD

**Issue by AroraAsh** [swagger-api/swagger-ui#2783]
I am using jersey 2.25 with swagger 1.5.13. I can Access the Swagger JSON at the following url in my app

http://localhost:8080/InterestMatcherMaven/rest/swagger.json

I have added The dist folder in my WebContent folder and i try to open it at the following url:-

http://localhost:8080/InterestMatcherMaven/

it shows the following error in the chrome console:-

index.html:68 GET http://localhost:8080/dist/SwaggerUIBundle.js 404 (Not Found)
index.html:69 GET http://localhost:8080/dist/SwaggerUIStandalonePreset.js 404 (Not Found)
index.html:73 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (index.html:73)

**Comment by hemikak** [comment]
Getting same error as `SwaggerUIBundle is not defined`

**Comment by webron** [comment]
Which version of swagger-ui did you test try it with?

**Comment by hemikak** [comment]
I checked with 3.0.1

**Comment by webron** [comment]
Please check with the master.

**Comment by AroraAsh** [comment]
Also if its of any relevence i am using tomcat 8.
I just tried with the latest master branch and i am getting the following errors for the swagger ui :-

swagger-ui-standalone-preset.js Failed to load resource: the server responded with a status of 404 (Not Found)
swagger-ui.css Failed to load resource: the server responded with a status of 404 (Not Found)
swagger-ui-bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
swagger-ui-standalone-preset.js Failed to load resource: the server responded with a status of 404 (Not Found)
(index):75 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload ((index):75)
http://localhost:8080/public/favicon-16x16.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/public/favicon-32x32.png Failed to load resource: the server responded with a status of 404 (Not Found)
swagger-ui.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by webron** [comment]
We should pushed a few more changes to master. Please try again.

**Comment by fractalocity** [comment]
I followed these instructions; probably the best Instructions i've seen anywhere pertaining to swagger (and clearest), and it doesn't work https://idratherbewriting.com/learnapidoc/pubapis_swagger.html#create-a-swagger-ui-display
and i'm pretty sure the problem is not the person who wrote the instructions or me. Anything nodejs not related to swagger is a pieces of cake. anything swagger related is a living nightmare and 90% of the time something is going to go wrong.

**Comment by shockey** [comment]
@fractalocity, we'd love to help, but you haven't shared any specifics that may lead to a solution.

Feel free to open a new issue with more information about what you're experiencing!

**Comment by fractalocity** [comment]
Thanks for the reply; i didn't expect anyone to read and reply. might as well post the hang-up; it's worth a shot. thanks

**Comment by smuthiya** [comment]
I am getting the same error with my Web APIs built using ASPNETCore - 'SwaggerUIBundle' is undefined 
I get this error when i navigate to /swagger to see the UI - but noting loads in browser and I get this error in browser console. However my json endpoint is working i.e. /swagger/v1/swagger.json I get json response back with my API details. But Swagger UI does not work

**Comment by shockey** [comment]
@smuthiya, this usually happens when the page serving Swagger-UI is pointing to the wrong path for Swagger-UI's assets (for example, your Swagger-UI assets are at `http://mysite.com/api/swagger/swagger-ui.js` but your HTML is looking for `http://mysite.com/swagger-ui.js`).

**Comment by mesuttalebi** [comment]
@shockey How to Fix?

**Comment by algirdask** [comment]
@smuthiya this seems related to ASPNETCore compatibility issues. I had same issue as you, adding StaticFiles dependency helped. From [here] https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/438)

**Comment by tariknz** [comment]
Thanks, adding Microsoft.AspNetCore.StaticFiles did it for me.

**Comment by MohdZaid259** [comment]
i deployed the express backend web app. 
but after deployment swagger ui is not being displayed, im getting the blank page with these errs
( it was working in localhost )
Uncaught SyntaxError: Unexpected token '<'
swagger-ui-standalone-preset.js:3 
Uncaught SyntaxError: Unexpected token '<'
swagger-ui-init.js:1390  
Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload
