### ISSUE TITLE
Complete example of how to consume a REST endpoint needed

### ISSUE THREAD

**Issue by vzelenko** [swagger-api/swagger-ui#2784]
Can you guys please include at least 1 working example either in tests or README file on how to consume a RESTful service, start to finish?

Something like an example from: https://github.com/swagger-api/swagger-js/tree/2.x would do nicely.

**Comment by webron** [comment]
@vzelenko - you pointed to swagger-js, and opened the ticket on swagger-ui. Are you asking how to use swagger-js or how to use swagger-ui? There's not a lot to it when it comes to swagger-ui, but if you can explain what's not clear, I'll make sure we document it.

**Comment by vzelenko** [comment]
@webron - my mistake.  I meant to put it under swagger-js section.  My issue is that since the upgrade from 2.x to 3.x branch there seems a significant API change without any examples on how to connect to a Swagger enabled service and consume an endpoint.

Or I was just missing something.  Either way, we can close this issue as it is in the wrong place.
