### ISSUE TITLE
Swagger incorrectly URL-encodes colons in parameters replaced in path segments

### ISSUE THREAD

**Issue by carlos-azb** [swagger-api/swagger-ui#2785]
Colons should not be encoded in URL path segments, according to https://tools.ietf.org/html/rfc3986#section-3.3

**Comment by webron** [comment]
Which version of Swagger-UI have you tested this with?

**Comment by carlos-azb** [comment]
I am using a ZIP I downloaded from master today.

**Comment by webron** [comment]
Can you share a sample spec to help us see the behavior? It would help also to show what the expected result would be for that spec.

**Comment by carlos-azb** [comment]
I am attaching a tiny application and the spec includes an example for the parameter and the expected result. Please let me know if it is not self-explanatory.

Thanks!
[swagger-ui-bug-2785.zip](https://github.com/swagger-api/swagger-ui/files/869634/swagger-ui-bug-2785.zip)

**Comment by webron** [comment]
Yup, I see it now. Would you consider investigating it and trying to submit a PR to fix it? The issue would be in swagger-js.

**Comment by carlos-azb** [comment]
I created this PR: https://github.com/swagger-api/swagger-js/pull/977

**Comment by webron** [comment]
This doesn't seem to be an issue anymore. Please reopen if needed.
