### ISSUE TITLE
Fresh install docker panic

### ISSUE THREAD

**Issue by Noqomo** [swagger-api/swagger-ui#2789]
Receiving format error panics on fresh install following quick-start:

**System**

(Running in VM - VirtualBox v5.1.14)

- Distributor ID: Ubuntu
- Description: Ubuntu 16.10
- Release: 16.10
- Codename: yakkety

**Prereq version**

`$ node --version`

> v7.7.4

`$ npm --version`

> 4.1.2

`$ docker --version`

> Docker version 1.12.6, build 78d1802

`$ swagger --version`

> 0.7.5

**Process**

`$ docker pull swaggerapi/swagger-ui`

> Using default tag: latest
> latest: Pulling from swaggerapi/swagger-ui
> Digest: sha256:954f4cf4b58e1df98986ad8904f7de0cdd52e7018e6295b6782d12296fcb00fb
> Status: Image is up to date for swaggerapi/swagger-ui:latest

`$ docker run -p 80:8080 swaggerapi/swagger-ui`

**Error**

> panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
> 	panic: standard_init_linux.go:178: exec user process caused "exec format error"
> 
> goroutine 1 [running, locked to thread]:
> panic(0x835c1a0, 0x975dcc40)
> 	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x326
> github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0x975d5974)
> 	/build/runc-z27ggU/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x2c1
> panic(0x835c1a0, 0x975dcc40)
> 	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x3fd
> github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x975d55fc, 0x9753c8f0, 0x975d5684)
> 	/build/runc-z27ggU/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0xfd
> github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x97562f60, 0x86ba6d58, 0x975dcc40)
> 	/build/runc-z27ggU/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x474
> main.glob.func8(0x9757c460, 0x0, 0x0)
> 	/build/runc-z27ggU/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x57
> reflect.Value.call(0x8302680, 0x842f740, 0x13, 0x838d738, 0x4, 0x975d5934, 0x1, 0x1, 0x0, 0x0, ...)
> 	/usr/lib/go-1.6/src/reflect/value.go:435 +0xeeb
> reflect.Value.Call(0x8302680, 0x842f740, 0x13, 0x975d5934, 0x1, 0x1, 0x0, 0x0, 0x0)
> 	/usr/lib/go-1.6/src/reflect/value.go:303 +0x8c
> github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x8302680, 0x842f740, 0x9757c460, 0x0, 0x0)
> 	/build/runc-z27ggU/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x25f
> github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x838fc58, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x840e0a0, 0x51, 0x0, ...)
> 	/build/runc-z27ggU/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xda7
> github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0x9758a240, 0x9752e070, 0x2, 0x2, 0x0, 0x0)
> 	/build/runc-z27ggU/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x92b
> main.main()
> 	/build/runc-z27ggU/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main.go:132 +0xa60

**Comment by fehguy** [comment]
Doesn't happen to me, so must be something environmental on your side.

**Comment by fehguy** [comment]
Please reopen if you can't find a solution
