### ISSUE TITLE
Data type Boolean renders empty droplist

### ISSUE THREAD

**Issue by stusta** [swagger-api/swagger-ui#279]
Using the latest from the develop-2.0 branch (commit b2637fc4bcb61bc92840200aea88055dbaa161f8), I've found these problems with parameters with a data type of boolean and a parameter type of form (Content-Type is application/x-www-form-urlencoded):
- They are rendered with a list with no values in it.
- When I tried setting booleanValues to an array of 0,1, I found that swagger.js wasn't setting a booleanValues property on SwaggerAPI. Once I hacked that, values were rendered in the list. But when I POSTed it, the field wasn't submitted.

**Comment by queirozfcom** [comment]
I'm on `master` and the following parameter list also causes the default value for `"rememberMe"` to be true (on Model Schema), even though I've explicitly set `false` as you can see below:

```json  
        ... other stuff ignored
        "parameters": [
          {
            "name": "loginData",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string",
                  "example": "admin"
                },
                "password": {
                  "type": "password",
                  "example": "admin"
                },
                "rememberMe": {
                  "type": "boolean",
                  "example": false
                }
              },
```

**Comment by webron** [comment]
Commenting on an issue that was closed two years ago doesn't help, @queirozfcom. It's definitely not related. Please open a new one. Also, you didn't set the default value, you set the example.
