### ISSUE TITLE
Operations do not respect tag ordering 

### ISSUE THREAD

**Issue by agouldsfi** [swagger-api/swagger-ui#2790]
The current 3.x ui does not honor sorting tagged operations by the order of  tags in the base spec, nor does it appear to sort alphabetically.

**Comment by hlubovac** [comment]
I also noticed this.

**Comment by fehguy** [comment]
This is a bug, we need to fix it.

**Comment by jeffreypriebe** [comment]
As a workaround for now, I did a [basic "sort alphabetically"](https://github.com/swagger-api/swagger-ui/issues/2818#issuecomment-300644718), in case that helps for your situation.

**Comment by shockey** [comment]
This bug was fixed in https://github.com/swagger-api/swagger-ui/pull/3324 - the fix is available in the latest version of Swagger-UI.

Thanks for reporting this, @agouldsfi!
