### ISSUE TITLE
Authorization Lock with no modal

### ISSUE THREAD

**Issue by jtoliver** [swagger-api/swagger-ui#2792]
I have an issue where I can see the lock on the endpoints, but clicking on it produces no modal. Also there isn't a authorization button. Any help would be appreciated.

**Comment by jtoliver** [comment]
![screen shot 2017-03-26 at 9 19 46 pm](https://cloud.githubusercontent.com/assets/611293/24337389/6dfde88c-126a-11e7-91b4-ca8ca0550ee5.png)

**Comment by webron** [comment]
Yup, I believe we had a bug around that. Can you pull `master` and try? Should be resolved there.

**Comment by jtoliver** [comment]
That works. Thanks!

I did want to point out that master/dist/index.html is missing `default`. Without  causes an error.

```
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset.default
    ],
```

**Comment by jtoliver** [comment]
Nevermind, It works without it on the server, and doesn't work locally weird. Its working on the server. I'm going to leave it alone. I'm tired. :)

Thanks again
