### ISSUE TITLE
Not able to send cookies through http request while calling for swagger.json

### ISSUE THREAD

**Issue by swaraj2204** [swagger-api/swagger-ui#2794]
I am required to send cookies through request so that my single sign-on works. I have attached the following 
` window.onload = function () {
        // Build a system
        const ui = SwaggerUIBundle({
            url: "/myurl/swagger.json",
            validatorUrl: null,
            dom_id: '#swagger-ui',
            useJQuery:true,
            enableCookies:true,
            supportHeaderParams:true,
            presets: [
                SwaggerUIBundle.presets.apis,
                // yay ES6 modules ↘
                Array.isArray(SwaggerUIStandalonePreset) ? SwaggerUIStandalonePreset : SwaggerUIStandalonePreset.default
            ],
            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout"
        })
`
This seems not working because there is no cookie in request header
`Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Connection:keep-alive
Host:localhost:5000
Referer:http://localhost:5000/myurl/swagger/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36`

Let me know how to fix it.

**Comment by edwardfung123** [comment]
A temporary workaround using jsonp to fetch the spec until they fix this issue.

```javascript
window.foo = function(spec){                                                                        
  const ui = SwaggerUIBundle({                                                                      
    spec: spec,                                                                                     
    dom_id: '#swagger-ui',                                                                          
    presets: [                                                                                      
      SwaggerUIBundle.presets.apis,                                                                 
      // yay ES6 modules ↘                                                                          
      Array.isArray(SwaggerUIStandalonePreset) ? SwaggerUIStandalonePreset : SwaggerUIStandalonePreset.default
    ],
    plugins: [                                                                                      
      SwaggerUIBundle.plugins.DownloadUrl                                                           
    ],
    layout: "StandaloneLayout"                                                                      
  })
  
  window.ui = ui                                                                                    
} 
window.onload = function() {                                                                        
  // Build a system
  var script = document.createElement('script');                                                    
  script.src = '/swagger/swagger.json?callback=foo'                                                 
  
  document.getElementsByTagName('head')[0].appendChild(script);                                     
  
}  
```

**Comment by webron** [comment]
@shockey - Can you check and verify if https://github.com/swagger-api/swagger-js/pull/981 will resolve this issue as well?

**Comment by swaraj2204** [comment]
@edwardfung123 The solutions is good and it is sending cookie fine but I have got following error with swagger.json

> swagger.json:1 Uncaught SyntaxError: Unexpected token :

![selection_003](https://cloud.githubusercontent.com/assets/7427446/24392961/c26873d4-13b3-11e7-9278-4511f4654633.png)

**Comment by edwardfung123** [comment]
@swaraj2204 You have to update the server to support JSONP first.

**Comment by swaraj2204** [comment]
@edwardfung123  I am using this within my webapps on tomcat, should I do it via ajax or some other way

**Comment by edwardfung123** [comment]
sorry I didn't know tomcat and the architecture of your webapp. I am using this with my Flask app and I have a special page to render the swagger spec if the user is logged in (by checking the session in cookies). if there is callback specified in the query string. Here is the code

```python
@app.route('/swagger/swagger.json')
def spec():
  ret = {} # the raw spec.
  # authentication is done somewhere else. So you cant find it here.

  from flask import request
  callback = request.args.get('callback')
  if callback:
    return callback + '(' + ret + ');'
  else:
    return ret
```

**Comment by marcgibbons** [comment]
#981 appears to tackle the execute portion. I think this pertains to the downloadUrl plugin.

Adding `credentials: "same-origin"` or `include` for CORS to the fetch options will send cookies.
https://github.com/swagger-api/swagger-ui/blob/633fa101b9325b9d40879217b2300103bda4815c/src/core/plugins/download-url.js#L16

**Comment by shockey** [comment]
Thanks to everyone for helping us identify this issue!

Just merged in a change from @marcgibbons that should fix this. Please reply if there are any lingering issues!
