### ISSUE TITLE
Support MIME-types other than `application/json` in the downloadUrl plugin

### ISSUE THREAD

**Issue by marcgibbons** [swagger-api/swagger-ui#2798]
Congratulations on the v3 release!

After upgrading, I discovered a regression caused by the HTTP Accept header being restricted to `application/json` in the downloadUrl plugin.
https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/download-url.js#L18

As part of django-rest-swagger / django-rest-framework, we render our OpenAPI spec using the `application/openapi+json` MIME type as is proposed in https://github.com/OAI/OpenAPI-Specification/issues/110, though no formal decision appears to have made on an official format.

Given that our OpenAPI schema generator does not respond to `application/json`, the request from SwaggerUI fails content negotiation. 

Can `Accept` be made more permissive e.g. `"Accept": "application/json,*/*"`?

**Comment by webron** [comment]
@marcgibbons - did you try the latest version? We tried tackling the issue using https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/download-url.js#L16.

**Comment by marcgibbons** [comment]
@webron Yes, latest from master. Included a PR. 🍻
