### ISSUE TITLE
Tag content always expanded

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#2799]
`docExpansion: "none"` from v2 didn't work

**Comment by webron** [comment]
Yes, it's noted in the [Known Issues](https://github.com/swagger-api/swagger-ui#known-issues) that most configuration options are not implemented yet.

**Comment by webron** [comment]
For everyone who's interested in this feature (I imagine users will come here from the closed issues as well).

We understand the importance of this feature, however at the moment, we can't prioritize it very high (just limited resources). It would be great if anyone would attempt to submit a PR to add this functionality. I'm aware that our documentation is (very) lacking, but hopefully for those of you who know your javascript, following how some of the [other configs](https://github.com/swagger-api/swagger-ui#parameters) work, would at least give you a hint as to what should be changed. If you have specific questions, we'll definitely try to help.

We're also in the process of writing up some guidelines to submitting PRs, that would help you and us in the process, but that shouldn't stop you from making changes. The basics are - make sure to add tests and if you need to add a distributed dependency, check with us first.  We appreciate all the help we'll get, as I'm sure other users of this project. We'll do our best to review PRs as soon as possible, and make the process iterative as needed.

**Comment by hlubovac** [comment]
do you have dev setup instructions anywhere

**Comment by webron** [comment]
As mentioned, the documentation is lacking. Whatever is available can be found in the README.

**Comment by drjonnicholson** [comment]
Thanks @webron for the update (and consolidating the issues).

**Comment by hlubovac** [comment]
Never worked with docker. Installed. Ran its "hello world". Executed this
```
docker pull swaggerapi/swagger-ui
docker run -p 81:8080 swaggerapi/swagger-ui
```
(81, because my IIS is using 80)

"http://localhost:81/" displays the familiar "Swagger Petstore".

I had some exposure to nodejs in the past, know my way around JS. I can't locate swagger-ui files to start editing. Or, is this just to run a precompiled and pre-installed version of swagger-ui in a docker VM?

Should I not be downloading the source to my local drive using git.exe, and then install dependencies via npm.exe, and run it using node.exe (then edit, test, push branch, create PR, etc)?

**Comment by webron** [comment]
You don't need docker to develop. It's just https://github.com/swagger-api/swagger-ui#how-to-run.

**Comment by hlubovac** [comment]
OK, works (finally).

So, to clarify: what's the requirement again? To display tags collapsed/uncollapsed, driven by a setting, that would be fed to `SwaggerUIBundle` function (accompanied by tests somehow)? I know I created this issue, but verifying just in case :)

Still not promising that this will work out, but I'll try.

**Comment by gwynjudd** [comment]
@webron I tried `npm run dev` to see if it would pick up changes I made to the codebase and play around with it, but it disn't seem to pick up any changes I made (https://github.com/swagger-api/swagger-ui/issues/3143) - is it supposed to pick up changes? Otherwise how to develop?

**Comment by hlubovac** [comment]
Nope; sorry: based on hints that I see around, this is all React syntax, which is beyond me. I was able to find that the relevant logic is in /src/core/components/operations.jsx ("is-open"; within the massive return statement), but I can't figure out how to wire that up with anything external. I don't even know how to debug this thing :(

**Comment by gwynjudd** [comment]
@hlubovac these days I'm using vscode for pretty much all development unless I have to use something else. I tried even just changing the "isOpen" logic to just return false to see what would happen, but it seemed to have no effect at all, so I think there is some development step I was missing to get it to rebuild.

**Comment by hlubovac** [comment]
I did the following steps to make that run:
```
git clone https://github.com/swagger-api/swagger-ui.git ./swagger-api/swagger-ui
```
That path was just my choice, within a folder that I named "projects" :).
Then:
```
npm install
```
That took a while. Close to 900 folders within `node_modules` got downloaded/created.
Then:
```
npm run dev
```
That also isn't super quick. It seems that everything is getting "compiled" (transformed) from this JSX syntax to nodejs language. I didn't look around to see where the produced nodejs files get dumped.

After that, http://localhost:3200 was showing v3 version of Petstore.

This compilation process seems to repeat each time I stop/start the service. But, then I also discovered that changes done within JSX files quickly get propagated all the way to the browse (I could see this in browser's console; no clue what mechanism is being used for this). So, I was able to see that my test change (I **added** a bogus value within quotes for `className` for the "is-open" and the opposite use-cases) gets communicated to the browser right away, as I could see my class-name value applied to the "section" element of a "tag", as it's being clicked to collapse/uncollapse.

So, hopefully that helps, if you know your way around React :)

**Comment by gwynjudd** [comment]
@hlubovac thanks for that, yes I can see that as well. I wasn't accustomed to how this reloading was working - I guess I was expecting to see it reload. OK I'll play around and see if I can affect the logic in any way

**Comment by gwynjudd** [comment]
@hlubovac is this your plan for resolving https://github.com/swagger-api/swagger-ui/issues/2710 (and similarly https://github.com/swagger-api/swagger-ui/issues/1919)? Just wondering if we are trying to solve the same issue

**Comment by hlubovac** [comment]
I just added a comment to #2710 as it being irrelevant to v3. So, not that one.

I wasn't aware of #1919, so not that one either.

I was trying to see if I'll be able to figure out a solution for this particular one (#2799), to have the "tag" content initially collapsed, driven by a startup setting, like this:

![image](https://cloud.githubusercontent.com/assets/3127736/26657408/7d2bbeec-4618-11e7-9a34-676dbc38d946.png)

But, unfortunately, I don't know how to work with these code files (and I can't find time to get started at the moment), so I'm a fluke. :)

**Comment by gwynjudd** [comment]
@hlubovac please try out my PR, I think it solves the issue

**Comment by hlubovac** [comment]
I downloaded your doc-expansion branch, and I see the change, but - which file did you add this to: `docExpansion: "none"` - to test the new setting?

**Comment by gwynjudd** [comment]
Sorry, after I went to lunch I realised that wouldn't be clear. Just add it to the bundle config like so:

```
  // Build a system
  const ui = SwaggerUIBundle({
    url: "http://petstore.swagger.io/v2/swagger.json",
    dom_id: '#swagger-ui',
    docExpansion: 'none',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })
```

**Comment by hlubovac** [comment]
I added a comment to your PR. Hopefully it meets their standards. Thank you!
