### ISSUE TITLE
Example JSON values displayed badly

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#2800]
before:
![image](https://cloud.githubusercontent.com/assets/3127736/24369562/40838a28-12d9-11e7-9216-cdaeabdaa15b.png)

after:
![image](https://cloud.githubusercontent.com/assets/3127736/24369539/2cd6dc14-12d9-11e7-969c-23af950e613b.png)

I see that the PRE tag is used and that JSON parts have been SPAN-ified individually. I don't know what the intention is, but please also consider users wanting to clipboard-copy examples.

**Comment by webron** [comment]
Can you share a sample spec for us to test with?

**Comment by hlubovac** [comment]
Just sent you an example to your private email.

**Comment by webron** [comment]
Thanks for the spec.

There are two issues - one on your end, one on ours.

Your definition isn't valid. Response examples need to be maps of a media type to their respective example.  Without copying the entire thing, it should be more like:
```json
            "examples": {
            	"application/json": {
              		"jsonapi": {
                		"version": "1.0.6275.27581 @ 2017.3.7.689 Alpha",
                			"meta": {
```

However, even fixing that ends up not rendering properly, and that's on us.

**Comment by hlubovac** [comment]
I only ommitted media type because it was, otherwise, showing in v2"s example box. I'll try again, though.

Thanks!

**Comment by bodnia** [comment]
@hlubovac response examples are grouped by `mime type` https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#example-object 
The fix is now in latest master.

**Comment by hlubovac** [comment]
my take is that [anything] is not a replacement until it's thaf 100%. examples swagger 2.0 dont show in v2 unless how i set them. if i move them only to make partiallly functional replacement happy, then i lose v2 which is still functionally superior over v3. maybe move this to v2 bugs then and fix if there 😁

**Comment by bodnia** [comment]
@webron could you please assist

**Comment by webron** [comment]
@hlubovac I don't understand what's missing. The behavior in v2 is incorrect. What @bodnia did here is accurate, maybe just missing a pretty print.

**Comment by webron** [comment]
Looks like the comment was deleted. Closing as fixed.
