### ISSUE TITLE
Other url pattern for swagger-ui

### ISSUE THREAD

**Issue by Hemimc** [swagger-api/swagger-ui#2803]
Hi everyone!
Ii wanted to know if there is a way to have an other url pattern to access Swagger doc on Swagger ui. Im working with Jersey with Eclipse IDE. For exemple, im using LocalHost:8080/api/restapi/swagger.json right now to access my doc for my rest services but i want to make doc for an other package (so not restapi) and I want to be able to acess it with an other url like this : LocalHost:8080/api/newPath/swagger.json. 

Can you tell me how to do it step by step? I searched a lot but could not find what I'm looking for. 

Thanks in advance!

Edit : all my swagger configurations are in Web.xml of my API so I don't have a class like "Application" or "AppConfig".

**Comment by webron** [comment]
This looks like a question to [swagger-core](https://github.com/swagger-api/swagger-core/).
