### ISSUE TITLE
Improving readability: Response headers could be formatted better

### ISSUE THREAD

**Issue by arthurdm** [swagger-api/swagger-ui#2808]
<img width="992" alt="screen shot 2017-03-27 at 8 06 13 pm" src="https://cloud.githubusercontent.com/assets/5042215/24383106/f60f5508-1328-11e7-94df-67a670d285cd.png">

If the response headers were each on its own line and it would be a lot easier to read.

**Comment by webron** [comment]
It was supposed to be that way 😕
