### ISSUE TITLE
dist setup results in issues loading scripts

### ISSUE THREAD

**Issue by pgodzin** [swagger-api/swagger-ui#2814]
In the past, the dist folder contained a lib/css/etc folder, and I was able to successfully copy that file structure to launch my webapp. However, copying the current structure, I get 404 errors trying to get the scripts (https://localhost:17070/dist/SwaggerUIBundle.js). 

What is the right way to setup using dist folder?

**Comment by shockey** [comment]
Hi @pgodzin!

I fixed an issue with relative paths in the index.html [thirteen days ago](https://github.com/swagger-api/swagger-ui/commit/997a31c0b504a6be34a5916bb86d3458b81a49e4). Are you still seeing issues when using the latest code on master? 

You should be able to serve the whole dist folder from any path with your server and have it work.

**Comment by pgodzin** [comment]
Yes, can confirm the dist folder now works properly when all files are places on the same level in a directory structure. Thanks!
