### ISSUE TITLE
Swagger-UI 3.0.3 Try It Out ignoring Spec Schemes

### ISSUE THREAD

**Issue by mgeorgy** [swagger-api/swagger-ui#2816]
I've just deployed Swagger-UI and the 'Try It Out' appears to be ignoring the schema specified in the spec file.

File contains:
```
schemes: [https]
```
When I attempt to Try It Out, the attempt fails and the resulting curl command is:
curl -X GET http://api...

Any suggestions on what may be causing this?  I also tried implementing the schemes as:
```
schemes:
 - https
```

**Comment by shockey** [comment]
@bodnia, can you look into this?

**Comment by smudliyar** [comment]
@webron @bodnia i am still getting "http" instead of "https", i have taken master branch code

curl -X GET "http://domain/v1/endpoint?access_token=adsdadads&type=1" -H  "accept: application/json" -H  "content-type: application/json"

Swagger specs
----------------------
schemes:
  - https

**Comment by hansvd** [comment]
I also still have the same problem (using the master branch).

**Comment by bodnia** [comment]
@hansvd @smudliyar I downloaded latest `master` and run dist/index.html with 
```
schemes:
  - https
```
Result:
<img width="1229" alt="screen shot 2017-04-06 at 8 35 19 pm" src="https://cloud.githubusercontent.com/assets/8950657/24767717/9f12f52e-1b08-11e7-83f2-d040061eef8e.png">

Please clarify how you run swaggerUI or please share your spec to look into this.

**Comment by hansvd** [comment]
swaggerUI (latest master) runs in apache web server

example spec:
`{
    "swagger": "2.0",
    "info": {
        "description": "",
        "version": "6.0.0",
        "title": "Server API"
    },
    "host": "abc.def.net:10000",
    "tags": [
        {"name": "heartbeat"}
    ],
    "schemes": ["https"],
    "paths": {
        "/heartbeat": {"get": {
            "tags": ["heartbeat"],
            "operationId": "getClichedMessage",
            "produces": ["text/plain"],
            "responses": {"200": {
                "description": "successful operation",
                "schema": {"type": "string"},
                "headers": {}
            }}
        }}
    }
 }`

Result:

![image](https://cloud.githubusercontent.com/assets/503068/24770767/68b50fdc-1b0b-11e7-82d1-2421499080e6.png)

**Comment by mgeorgy** [comment]
I've just updated to Master and am still seeing the same issue.  Swagger UI is run via an Apache Web Server.  I've confirmed the schemes specified is HTTPS, yet the curl command is still HTTP resulting in an error when I "Try It Out".

**Comment by webron** [comment]
@bodnia when testing it, try hosting the spec rather than embedding it. Perhaps that's the source of the problem.

**Comment by mgeorgy** [comment]
@webron that may be the difference, as that is how I'm using the UI (hosting, albeit on the same server, the spec).

**Comment by webron** [comment]
@mgeorgy if you get a chance, can you test it by embedding it into the index.html?

**Comment by gkapkowski** [comment]
After some digging I've found the culprits:
https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/spec/selectors.js#L294
https://github.com/swagger-api/swagger-ui/blob/master/src/standalone/layout.jsx#L69

What is happening: In above line 294 if state object does not contain `scheme` value it will always return `http`. This alone does not cause the issue because there is `Schemes` component that allows setting scheme from the UI, BUT, as line 69 shows, displaying of this Schemes component is dependent on `securityDefinitions` being present in your specification. 

As a workaround I've added `securityDefinitions` key to my specification.

```
schemes:
  - https
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
```

**Comment by bodnia** [comment]
@gkapkowski you're right, I thought fix with displaying schemes is fixed. So the issue was is that there is no schemes dropdown. I'll push the fix asap, or you can submit a pr and I'll merge

**Comment by gkapkowski** [comment]
I'll leave it to you if that's not a problem. I'm not familiar enough with the codebase to confidently do the fix.

**Comment by bodnia** [comment]
@gkapkowski @mgeorgy @hansvd the fix is in the latest master

**Comment by shockey** [comment]
Releasing this fix; closing.

Please reply if this is in error.
