### ISSUE TITLE
API Method Sorting v3.0.2

### ISSUE THREAD

**Issue by UzairXlade** [swagger-api/swagger-ui#2818]
With the reference of [StackOverflow Question](http://stackoverflow.com/q/42977003/3006390) API methods are not sorted or do not have option to sort it, please guide, how to sort api method.

**Comment by webron** [comment]
It's not implemented yet. See [Known Issues](https://github.com/swagger-api/swagger-ui#known-issues).

**Comment by UzairXlade** [comment]
Is there any work around to do sorting in 3.0.2 version, how it is sorting now, any **hint**? 
So that i can make some custom changes for this time. until the issue is resolved.

**Comment by bodnia** [comment]
Implemented in latest master https://github.com/swagger-api/swagger-ui/pull/2924

**Comment by dotasek** [comment]
The latest dist doesn't seem to respect the apisSorter parameter mentioned in the StackOverflow comment. Did #2924 address this, or just operationsSorter?

**Comment by bodnia** [comment]
@dotasek now it's only `operationsSorter` implemented

**Comment by jeffreypriebe** [comment]
@dotasek API level sort is relatively straight-forward. I have a [basic "sort all API tags by alpha" here](https://github.com/jeffreypriebe/swagger-ui/tree/feature/AlphaSortOperations). It's a [very small change](https://github.com/jeffreypriebe/swagger-ui/commit/dbeca72844e9101d6e79213ff8b8f88a958ae19c) and I didn't implement the configurable `apiSorter` option nor is there any choice that isn't alpha nor does it sort APIs without tags I don't think.
