### ISSUE TITLE
Config parameter to hide "OPTIONS" requests from UI

### ISSUE THREAD

**Issue by carlnordenfelt** [swagger-api/swagger-ui#2819]
OPTIONS requests aren't generally something that a developer would intentionally call and they don't generally need documentation. That said, when generating swagger documentation from a lot of provider (for example AWS API Gateway) the OPTIONS requests are in the spec.
It would be great if it was possible to configure SwaggerUI to not render these at all.

**Comment by carlnordenfelt** [comment]
Never mind, I realized that this is a simple css fix :)

**Comment by akshaybheda** [comment]
How did you fix it?

**Comment by carlnordenfelt** [comment]
Should've of curse posted that in my response :)

Add the following to a custom css-file and include after the swagger css-file:
```
.opblock-options {
    display: none;
}
```

**Comment by akshaybheda** [comment]
i am learning odata now. Thanks for your help. 
I wanted to know why those odata options are used and                          `c.InjectStylesheet(containingAssembly,"Swashbuckle.Dummy.SwaggerExtensions.testStyles1.css");`
In this what is this containing assembly. Can you help me with that?

**Comment by carlnordenfelt** [comment]
Sorry, not familiar with that.
