### ISSUE TITLE
POST,PUT,DELETE Methods are not working in swagger ui but GET Works

### ISSUE THREAD

**Issue by skaushikWebuy** [swagger-api/swagger-ui#2825]
Hi 

POST,PUT,DELETE Methods are not working in swagger ui but GET Working for all my endpoints.
I even tried copy paste executing the curl command on shell and it is also working.

Is there any configuration I have to do in my server or swagger json to overcome this issue.

**Comment by webron** [comment]
We can't do much with 'not working'. If you'd like us to help, provide us with a spec that reproduces the problem and tell us which version of swagger-ui you're using.

**Comment by skaushikWebuy** [comment]
I am using Windows 8 and it seems as per below url there may be spaces in curl request that is made through the swagger-ui.js file 

Pls refer below url

http://stackoverflow.com/questions/36361572/curl-6-could-not-resolve-host-application

Also it says that curl work with double quotes and single quotes with the curl library.

**Comment by skaushikWebuy** [comment]
http://stackoverflow.com/questions/6884669/curl-1-protocol-https-not-supported-or-disabled-in-libcurl

**Comment by webron** [comment]
I can't help you if you don't answer my questions.

**Comment by skaushikWebuy** [comment]
I am using Swagger version 3.0

**Comment by webron** [comment]
Hate doing this, but I have to close the ticket. There's no 'Swagger' product (there's swagger-ui, swagger-core, swagger-editor...), there's no version 3.0 (all our versions are in the format of X.X.X) and you did not provide with a spec to reproduce the issue. If you can't spend the extra time to provide us with proper details, I can't spend the extra time to help resolve the issue.

**Comment by skaushikWebuy** [comment]
swagger-ui version v2.2.8
