### ISSUE TITLE
POST,PUT,DELETE Methods are not working in swagger ui but GET Works

### ISSUE THREAD

**Issue by skaushikWebuy** [swagger-api/swagger-ui#2828]
swagger-ui - Swagger UI version v2.2.8

POST,PUT,DELETE Methods are not working in swagger ui but GET Working for all my endpoints.
I even tried copy paste executing the curl command on shell and it is also working.

Is there any configuration I have to do in my server or swagger json to overcome this issue.

I am using Windows 8 and it seems as per below url there may be spaces in curl request that is made through the swagger-ui.js file

Pls refer below url

http://stackoverflow.com/questions/36361572/curl-6-could-not-resolve-host-application

Also it says that curl work with double quotes and single quotes with the curl library.

http://stackoverflow.com/questions/6884669/curl-1-protocol-https-not-supported-or-disabled-in-libcurl

**Comment by webron** [comment]
Please don't repeatedly open tickets. You're still not providing all the details and you're wasting our time.

**Comment by skaushikWebuy** [comment]
I did mention the swagger version that I am using. In earlier ticket also I
did mention that I am using Swagger UI version v2.2.8. But it got closed. I
do value your time but the issue I am facing is non-trivial. I am looking
forward for co-operation from you.

Thanks,

Sachin Kaushik

**Comment by skaushikWebuy** [comment]
Please list me the details that I may have to provide

**Comment by flik** [comment]
I have the same issue. Here is my swagger annotations detail:

curl request in swagger ui is not sending any param in post request.
```

/**
 * @SWG\Info(title="Dogs API", version="1.0.0")
 */


 /**
 * @SWG\Definition(
 *     definition="Login",
 *     required={"email", "password"},
 *     @SWG\Property(
 *         property="email",
 *         type="string",
 *         description="User Password"
 *     ),
 *     @SWG\Property(
 *         property="password",
 *         type="string",
 *         description="The password of the user"
 *     )
 * )
 */


     /**
     * @param str $email, str password
     *
     * @SWG\Post(
     *     path="/login/index.php",
     *     @SWG\Response(
     *         response="200",
     *         description="Returns a single dog by its ID",
     *         @SWG\Schema(ref="#/definitions/Login")
     *     ),
     *     @SWG\Response(
     *         response="404",
     *         description="No dog with the given ID was found"
     *     ),
     *     @SWG\Parameter(
     *         name="email",
     *         description="User Email",
     *         in="path",
     *         required=true,
     *         type="string"
     *     ),
     *     @SWG\Parameter(
     *         name="password",
     *         description="User Password",
     *         in="path",
     *         required=true,
     *         type="string"
     *     ),
     *     consumes={"application/json"},
     *     produces={"application/json"},
     * )
     */
```
