### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by Adzter** [swagger-api/swagger-ui#2832]
http://swagger.io/docs/swagger-tools/#swagger-ui-documentation-29

The above documentation specifies there's a HTML folder however this seems to have been removed in the following commit:
https://github.com/swagger-api/swagger-ui/commit/bd8344c80879f245cf6bbff8122967137f37ceff

How can I now edit the html template? I'm looking to rename the <title> tag but can however find no reference to it.

The build file always seems to have a hardcoded:
`<title>Swagger UI</title>`

**Comment by cl3m3nt666** [comment]
head 
```html
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Swagger UI</title>
```
In swagger-ui/dist/index.html ?

**Comment by Adzter** [comment]
Does modifying the file post-build not defy the point of the build process?

If I'm making changes, then re-building then i'll have to repeat my changes post build. Although not a huge issue for just the <title> tag. This seems like a step down from the previous handlebars setup?

**Comment by webron** [comment]
The documentation in the swagger.io website refers to the 2.X version. We're in the process of updating that to 3.x, just not there yet. Will try to get someone to help you with the current questions though.

**Comment by bodnia** [comment]
@Adzter do you use 2.x version or 2.x?

**Comment by bodnia** [comment]
@Adzter in 2.x path to source index.html is `/src/main/html/index.html`. It can be modified and after build it appears in `dist` folder with new title.

**Comment by shockey** [comment]
FYI, In 3.x, `dist/index.html` isn't a generated file, it's static. It's just in `dist` for backwards compatibility, since 2.x had it there.

**Comment by Adzter** [comment]
I'm using 3.x

**Comment by shockey** [comment]
As I mentioned before, `dist/index.html` is a static file, not a generated file, so making changes to it is safe and won't be destroyed by later builds.

If modifying the HTML directly doesn't suit your taste: you could write a plugin that uses [react-helmet](https://github.com/nfl/react-helmet) to manage the document `<head>`, or just do a `document.title = "My Title"`.

Alternatives to changing the Swagger specification URL that's loaded via `index.html` include providing a `?url=http://mycompany.com/swagger.json` query parameter when you open Swagger-UI.
