### ISSUE TITLE
New configuration option to hide and collapse new Models section in 3.0

### ISSUE THREAD

**Issue by andrew-regan** [swagger-api/swagger-ui#2834]
3.0 has added a new "Models" section at the end of the UI that is expanded by default. It would nice to add 2 new configuration settings that would:

1. allow this to be hidden since this section wasn't in SwaggerUI 2.0
2. collapsed by default if its not hidden

Screenshot from 3.0.3:
<img width="500" alt="screen shot 2017-03-31 at 7 41 42 pm" src="https://cloud.githubusercontent.com/assets/13903094/24572812/3fac6f74-164a-11e7-82d9-9b6c6e2135d0.png">

**Comment by 1Map** [comment]
+1

**Comment by dwickern** [comment]
👍  The `docExpansion` setting supports 'list' (expand both tags and models) or 'none' (expand neither tags nor models). It would be nice to have a new setting to expand tags but not models

**Comment by bertnz** [comment]
In our API models are quite complex but definitely a secondary action when perusing an API - the list of operations is key so we would also want the list expanded but not the model. dwickern's design seems perfect.

**Comment by MockingbirdME** [comment]
I'd like to +1 this as well; we just implemented Swagger-UI into our documentation and I'd love to collapse models, but not tags, by default.

**Comment by Freemahn** [comment]
+1 to dwickern's design.

**Comment by SubiyaCryolite** [comment]
+1 to dwickern's design.

**Comment by heldersepu** [comment]
I would love to see this implemented...
But I don't quite agree with @dwickern design, I would prefer a backwards compatible approach:
- Keep `docExpansion` as is that way current existing users are not affected 
- Add a new `modelExpansion` that will control the Models section

**Comment by heldersepu** [comment]
Has anyone looked into `defaultModelExpandDepth` that seem to be new option...

**Comment by kevineger** [comment]
I personally don't like the generic `defaultModelExpandDepth` configuration as it will also collapse the _Model_ view for specific API routes.

**Comment by dwickern** [comment]
@heldersepu My proposal would be backwards compatible with the current `docExpansion`, since you can detect whether it's set to a string or an array

**Comment by heldersepu** [comment]
@dwickern remember this tool is integrated with many other languages 
A setting that can be a string or an array would problematic in a strongly typed language.

**Comment by dwickern** [comment]
It would be one type or the other, depending on what API this other language wants to support/expose

**Comment by webron** [comment]
I don't really see how the proposed solution does not introduce a new issue by not allowing what `docExpansion` currently allows.

**Comment by dwickern** [comment]
The proposal will still support the current values (`'list', 'full', 'none'`) and alternatively an array of things to expand for more granular control.

`'list'` is equivalent to `[ 'tags', 'models' ]`
`'full'` is equivalent to `[ 'tags', 'models', 'operations' ]`
`'none'` is equivalent to `[ ]`

**Comment by webron** [comment]
I see it now, but don't really like it. There's a hierarchy between tags and operations. What if someone puts `[ 'operations' ]`?

**Comment by dwickern** [comment]
Then operations are expanded by default and tags are not

**Comment by webron** [comment]
Yeah, I can already see the support tickets coming on that one. It's not the right approach, sorry.

**Comment by heldersepu** [comment]
This issue can be closed, the PR was merged.
