### ISSUE TITLE
Swagger UI generating Curl command that truncating the query string [version 3.0.2]

### ISSUE THREAD

**Issue by smudliyar** [swagger-api/swagger-ui#2839]
Swagger UI generating  Curl command as pasted below and due to this query string truncating

curl -X GET http://domain:8080/v1/endpoint?access_token=affsfafasfa&type=1 -H "accept: application/json" -H "content-type: application/json"

the correct Curl command should be like this

curl -X GET 'http://domain:8080/v1/endpoint?access_token=affsfafasfa&type=1' -H "accept: application/json" -H "content-type: application/json"

the difference between above two command is quote around http url . So please tell me how to achieve this in swagger ui [ version 3.0.2 ] ?

**Comment by smudliyar** [comment]
@bodnia @webron I have just taken fresh clone after you have  commit the fix, i got the version  "version": "3.0.4".
But still the issue is there which seems to be not resolved 
curl -X GET http://petstore.swagger.io/v2/pet/1 -H  "accept: application/xml" -H  "content-type: application/json"

curl -X GET http://domain/v1/endpoint?access_token=fhf&type=4 -H  "accept: application/json" -H  "content-type: application/json"

**Comment by bodnia** [comment]
@smudliyar this fix is not versioned yet, please use the latest `master`. The new version will be tagged soon. Sorry for inconvenience

**Comment by smudliyar** [comment]
@bodnia @webron I have used latest master  but still quote is missing from Curl command
curl -X GET http://petstore.swagger.io/v2/pet/12 -H  "accept: application/xml" -H  "content-type: application/json" 

Could u plz do testing at your end?

**Comment by bodnia** [comment]
@smudliyar pushed latest built dist folder. Please check

**Comment by smudliyar** [comment]
@webron @bodnia its fixed now, i am getting  quote around endpoint url. 
Thanks

I have found couple of more issues, i will create new ticket for it
