### ISSUE TITLE
Running the latest release throws javascript error

### ISSUE THREAD

**Issue by df-jsykes** [swagger-api/swagger-ui#284]
SyntaxError: invalid label
[Break On This Error]   

'opening->other': 1,

swagger-ui.js (line 1969, col 16)

ReferenceError: SwaggerUi is not defined
[Break On This Error] 

Actually, the petstore runs, so must be something on my side.

**Comment by DonBranson** [comment]
Did you ever figure this out? I'm getting the same thing.

**Comment by fehguy** [comment]
@DonBranson this issue is a couple years old.  Can you open a new issue if you're having trouble?

**Comment by DonBranson** [comment]
@fehguy I will if I think there's an issue. Probably just something I'm doing wrong.

**Comment by DonBranson** [comment]
Oddly enough, the issue was in the code I just slapped together, and not your proven code. ;)

The reference I used to swagger-ui,js was misrouted by my config. I fixed that and it's working fine.
