### ISSUE TITLE
HTTP 406 when only "application/yaml" is produced

### ISSUE THREAD

**Issue by AvoH** [swagger-api/swagger-ui#2842]
My Spring Controller defines spec retrieval @RequestMapping with produces = "application/yaml".
This works well with Swagger-UI 2.x, while Swagger UI 3.0.4 fails with HTTP 406. 
Adding "applicatiopn/json" to "produces" makes 3.0 work even if only yaml is returned, but it breaks Swagger-ui 2.x.

**Comment by webron** [comment]
Do you have a live example of that?

**Comment by AvoH** [comment]
[apidocs.zip](https://github.com/swagger-api/swagger-ui/files/891354/apidocs.zip)

Don't have it live. Here is a sample project. 
Run as SpringBoot app. http://localhost:8080/swagger-ui/index.html
Sample yaml config with produces application/yaml is at http://localhost:8080/api/config, which results in 406.
Same config with produces {"application/yaml", "application/json"} at yaml config with produces application/yaml is at http://localhost:8080/api/config2 works.

**Comment by webron** [comment]
Thanks for the sample. Never used spring boot, so gonna need a few more instructions to run it.

**Comment by AvoH** [comment]
If in IDE, it should be in Run As->Spring Boot App

or you can use maven:

mvn spring-boot:run

**Comment by webron** [comment]
@AvoH Thanks. Going to close this one as a duplicate of #2798. If you follow the ticket, you'll see there's a pending PR. Until merged, you can make the change locally and get it to work.

**Comment by AvoH** [comment]
Great, Thanks!
