### ISSUE TITLE
Authorization Code flow not working

### ISSUE THREAD

**Issue by AvoH** [swagger-api/swagger-ui#2844]
Getting validation error during Authorization for an API using flow=accessCode:

"Validation Erroroauth2RedirectUri configuration is not passed. Oauth2 authorization cannot be performed."

Can be reproduced in http://petstore.swagger.io/ 
GET /pet/findByStatus

**Comment by bodnia** [comment]
@AvoH oauth2 authorization works only with server and defined `oauth2RedirectUrl` in config. 
Default value is `oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"`. You can use our dev server by running `npm run dev`, this server is hosted on `localhost:3200`.
To change this configuration please pass `oauth2RedirectUrl` to constructor:

```
const ui = SwaggerUIBundle({
    oauth2RedirectUrl: [here new ouath2 redirect is passed],
    url: "http://petstore.swagger.io/v2/swagger.json",
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
```

Please let me know if you have any issues with this and I'll assist.

**Comment by bodnia** [comment]
@AvoH please re-open in case of any questions

**Comment by drmikecrowe** [comment]
In swagger-3.x, does oauth2-redirect.html work properly?  For me (not sure if this is my app specifically), createForm does NOT redirect back--it returns the JSON directly.

I updated it to use JQuery POST to exchange the token (such as below):

```js
    $.ajax({
      url:     action,
      data:    {
        "code":          qp.code,
        "redirect_uri":  location.protocol + "//" + location.host + location.pathname,
        "grant_type":    "authorization_code",
        "client_secret": auth.clientSecret,
        "client_id":     auth.clientId
      },
      method:  "POST",
      success: function (json) {
        var isValid = ("token_type" in json);
        json.state = "OauthAccessCode";
        oauth2.callback({auth: oauth2.auth, token: json, isValid: true});
        window.close();
      }
    });
```

**Comment by redtachyons** [comment]
Same issue, I can't find the config file to set this parameter in swagger 3

**Comment by bodnia** [comment]
@redtachyons @drmikecrowe currently the flow with redirection is implemented, and support of both: handling redirect and json response from server is under implementation.

**Comment by bodnia** [comment]
@redtachyons @drmikecrowe @AvoH could you please test pr https://github.com/swagger-api/swagger-ui/pull/2953 if this works for you properly, then it can be merged. Thank you in advance

**Comment by bodnia** [comment]
@AvoH thanks for your feedback in PR, could you please test latest master and re-open issue if there is anything wrong. Thanks
