### ISSUE TITLE
Error with PetStore on Heroku example project

### ISSUE THREAD

**Issue by dinezbabu** [swagger-api/swagger-ui#2847]
When i added new header to GETmethod i get the error. please find the screen shot below. Without header the example works fine.

<img src="https://cloud.githubusercontent.com/assets/10957217/24652743/92846b9e-1950-11e7-9971-bf20b47343a0.png" alt="Code mainpulated for testing purpose">

**Comment by hkosova** [comment]
Answered your question here: http://stackoverflow.com/questions/43186417/why-does-swagger-editor-show-undefined-headers-for-an-operation-with-a-custom

P.S. This repository is for Swagger UI, not Swagger Editor. For Editor issues you should use https://github.com/swagger-api/swagger-editor.

**Comment by webron** [comment]
Thanks @hkosova.
