### ISSUE TITLE
Implement `x-servers` so that we can use `servers` field from OAS 3.0... today.

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#2854]
Multiple hosts/servers is an awesome feature.
We can wait for OAS 3.0 full implementation... or we can make this a quick pollyfill ( a taste of things to come ).

To do so within the OAS 2.0 structure we just call it `x-servers`.
It can be a plugin, doesn't have to be part of this repo ( or the bundle, it _could_ be part of this repo as an opt-in feature. ).

It would override `host` + `schemes` + `basePath` and add a component to select which host ( fill out the template ) we want to try-it-out against.

**Comment by webron** [comment]
We _are_ going to wait for 3.X for this.
