### ISSUE TITLE
Failed to load spec

### ISSUE THREAD

**Issue by EvgenyOrekhov** [swagger-api/swagger-ui#2855]
The [master](https://github.com/swagger-api/swagger-ui/tree/b9c14028824adca48ffde6b88f94a46047b30d7d) version of Swagger UI says "Failed to load spec" to all my specs.

Example spec: http://api.test4.twinshub.ru/swagger.json

Steps to reproduce:
1. Clone the repo
2. Open `dist/index.html` in a browser
3. Paste `http://api.test4.twinshub.ru/swagger.json` into the "Explore" input
4. Press "Explore"

![2017-04-04-185222_742x384_scrot](https://cloud.githubusercontent.com/assets/8045060/24666152/26638b3a-1968-11e7-9650-1516f5ff22a7.png)

**Comment by webron** [comment]
This is a CORS issue. Please follow the guide at https://github.com/swagger-api/swagger-ui#cors-support.
