### ISSUE TITLE
Swagger Curl command contains "http" even-though swagger specs defined "https"   

### ISSUE THREAD

**Issue by smudliyar** [swagger-api/swagger-ui#2856]
Swagger Curl command contains "http" even-though swagger specs defined "https"   

curl -X GET "http://somedomain/v1/endpoint?access_token=adadadasd&type=1" -H  "accept: application/json" -H  "content-type: application/json"

Here is the snippet of swagger specs
--------------------------------------------------
swagger: '2.0'
host: 'somedomain'
basePath: /v1
schemes:
  - https

**Comment by hansvd** [comment]
Duplicates #2816

**Comment by webron** [comment]
Thanks.
