### ISSUE TITLE
3.0.3 Parser expectations does not match swagger editor and standalone validator - Duplicate mapping key

### ISSUE THREAD

**Issue by matthieugeerebaert** [swagger-api/swagger-ui#2862]
Unfortunately 3.x swagger-ui throws error that are not detected by swagger editor or standalone validator..
Swagger UI 2.x ok

Will it be possible to focus on iso expectations between tools ?

Swagger file:
[swagger.zip](https://github.com/swagger-api/swagger-ui/files/895694/swagger.zip)

![2017-04-05 11_08_21-swagger ui](https://cloud.githubusercontent.com/assets/3653040/24698304/6d4ddf68-19f0-11e7-9824-73c63addc031.png)

**Comment by shockey** [comment]
Looks like your Swagger document is invalid- `definitions.ProblemDetails` appears twice. Removing the duplicate fixed the problem for me.

This error could be more helpful, though- I'm going to look into making it better.

**Comment by matthieugeerebaert** [comment]
Great ! Thank you Shockey for your quick fix, it will help our users, it will be greater with the key name but I guess it's more relative to the lib you use..

Note: Line number is not the same as visual studio code checker wich is more accurate, but that's ok :)  ( 4275 versus 4265 ) 
![4275](https://cloud.githubusercontent.com/assets/3653040/24742400/5f2df264-1aaa-11e7-9607-9a8850136592.png)
