### ISSUE TITLE
SwaggerUI doesn't show model schema

### ISSUE THREAD

**Issue by aihaiyue123** [swagger-api/swagger-ui#2866]
SwaggerConfig:
![image](https://cloud.githubusercontent.com/assets/24245864/24736145/ed4f15d8-1ab8-11e7-968c-1f8b83551a6a.png)
swagger-ui.html:
![image](https://cloud.githubusercontent.com/assets/24245864/24736248/6efa7b68-1ab9-11e7-8978-f5341d80f647.png)

**Comment by aihaiyue123** [comment]
![Uploading image.png…]()

**Comment by aihaiyue123** [comment]
If the SwaggerConfig is changed into this，it works:
@Bean
	public Docket platformApi() {
		return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).forCodeGeneration(true).select().apis(
				 RequestHandlerSelectors.any())
				//.paths(PathSelectors.regex(".*/(api|entity).*"))
				.build();
	}

**Comment by webron** [comment]
Even without seeing your spec, I can tell it's an invalid one. You can't have more than one body parameter. Please open the issue on whichever project you use to produce the spec to resolve it there.

**Comment by aihaiyue123** [comment]
Sorry,I am Using 
springMvc 
pringfox-swagger2 2.5.0 
springfox-swagger-ui2.5.0

**Comment by webron** [comment]
Then open the ticket on Springfox.

**Comment by aihaiyue123** [comment]
Ok,Thanks!
