### ISSUE TITLE
"Authorized" status not updating on oauth2 flow completion

### ISSUE THREAD

**Issue by travisbrkr1234** [swagger-api/swagger-ui#2870]
I am having a problem using the OAuth2 flow where the the "Authorized" status is never updated on completion of the oauth2 token grant. I am using the access_code(authorization_code) flow

My dup steps:
- Instantiate new a new ui (SwaggerUIBundle)
- Pass in my:
 - oauth2RedirectUrl
 - url
 - tokenUrl
- Run 'npm run dev'
- Click the "authorize" button
- Type in my client id and secret
- Check applicable scopes
- Click Authorize, a new tab opens up for me to authenticate
- Click allow application
- Token is generated
- I close the new tab
- The "Authorize" button still exists, so I click it again
- The screen flashes, and the "Authorize" button turns into "Logout", as well as the "Authenticated" status appears.

**Comment by MateuszKubuszok** [comment]
I have the same error. Additionally I can see that after the Logout button appears, the OAuth2 data is broken: the authorization header is `"authorization: Bearer undefined"`.

I also have 3 other flows defined (application, implicit and password) and none of them works as well. I know that application flow is not supported and UI only display it, but implicit and password are broken for me:

 * when I click on the scopes to mark them, nothing happens, neither with the UI (checkbox is still not checked) nor int console log,
 * then I click authorize also nothing happens, but in the console I can see:

    ```
    Uncaught TypeError: t.map is not a function
        at c (http://localhost:8080/swagger3/swagger-ui-bundle.js:65:31141)
        at http://localhost:8080/swagger3/swagger-ui-bundle.js:65:31396
        at Array.reduce (native)
        at l (http://localhost:8080/swagger3/swagger-ui-bundle.js:65:31213)
        at Object.p [as mergeInQueryOrForm] (http://localhost:8080/swagger3/swagger-ui-bundle.js:66:220)
        at Object.fetch (http://localhost:8080/swagger3/swagger-ui-bundle.js:66:391)
        at http://localhost:8080/swagger3/swagger-ui-bundle.js:73:26827
        at Object.dispatch (http://localhost:8080/swagger3/swagger-ui-bundle.js:36:3829)
        at dispatch (<anonymous>:2:1507)
        at Object.authorizePassword (http://localhost:8080/swagger3/swagger-ui-bundle.js:29:15463)
    ```

For me workaround for those issues was a downgrade to Swagger UI 2.2.10. Versions from 3.0 onward seem to be broken to me.

**Comment by bodnia** [comment]
@MateuszKubuszok can you please share the spec to reproduce this issue?

**Comment by MateuszKubuszok** [comment]
@bodnia 
[swagger.json.zip](https://github.com/swagger-api/swagger-ui/files/950054/swagger.json.zip)

I used `mock-id` and `mock-secret` to for accessing mock data.

I returned to check Swagger UI 3 today (API grew bigger in the meantime) and found out that it is pretty much not working due to https://github.com/swagger-api/swagger-ui/issues/2923. I can prepare smaller example later on.

**Comment by bodnia** [comment]
@MateuszKubuszok @travisbrkr1234 can you please test the latest master and re-open the issue in case of any bugs. thank you

**Comment by MateuszKubuszok** [comment]
@bodnia  It seems to work for me now, thanks!
