### ISSUE TITLE
What happened to requestInterceptor?

### ISSUE THREAD

**Issue by tyrsius** [swagger-api/swagger-ui#2872]
did `requestInterceptor` get renamed or is it gone completely? I depend on this to handle "try it out" requests for APIs on multiple hosts.

**Comment by webron** [comment]
It's currently not supported in 3.X. We'll need to work on bringing it back.

**Comment by arun-deva** [comment]
We are using requestInterceptor to solve the problem described here: https://github.com/swagger-api/swagger-ui/issues/1888
Any idea when this feature might be available in 3.x?

**Comment by webron** [comment]
@arun-deva not soon, unless we get community contributions.
