### ISSUE TITLE
Example value not pre-populated

### ISSUE THREAD

**Issue by pgodzin** [swagger-api/swagger-ui#2874]
Previously, the @ApiParam example property value was used to pre-populate the input field. In 3.0.X, after pressing "Try it out", the input field remains blank.

**Comment by webron** [comment]
From what I had tested, it works as expected. Can you share a spec for us to try out?

**Comment by pgodzin** [comment]
{"name":"version","in":"query","description":"The release date of the version of the API you want to use. Specify dates in YYYY-MM-DD format.","required":true,"type":"string","x-example":"2016-09-27"}] 

![What I see](http://imgur.com/72NUgoS.png)

**Comment by webron** [comment]
@bodnia did we add support for `x-example`?

**Comment by pinoy4** [comment]
OT
@pgodzin I noticed you are stating the use of YYYY-MM-DD format in the description. I suggest you also set the `format` property to `date` as suggested in the docs:

    Common Name     type    format          Comments
    dateTime        string  date-time       As defined by date-time - RFC3339

[RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14)

**Comment by bodnia** [comment]
@webron we do not have support for `x-example` now

**Comment by dawez** [comment]
Has been the the support for x-example been added ? Is this supposed to be added in the future ?

**Comment by shockey** [comment]
@dawez, support has not been added, though it is a planned feature. 

A pull request that implements the feature is welcome, if you need the feature and have the time 😄

**Comment by dawez** [comment]
just created a pull request: #3538

**Comment by pgrever** [comment]
It appears that for body content only x-examples (plural, not the singular x-example) is supported in the code annotations.  We are using this.  However, the change submitted only looks for x-example.  Would it be possible to support x-examples too?  Maybe just use the value of the first example in the list?
