### ISSUE TITLE
Enum are "anonymous" in the Model preview section, it shows only "Enum" - 3.x

### ISSUE THREAD

**Issue by matthieugeerebaert** [swagger-api/swagger-ui#2875]
There are two points:
enum reference from parameter, and enum reference from another definition object

This definition was ok for swagger-ui 2.x and swagger-parser": "~3.4.1. But it is now ko with swagger-ui 3.x and online swagger editor.. :(

In swagger-ui 3.x both model and parameter are "anonymous"

```
  "definitions": {
    "Type": {
      "description": "",
      "type": "string",
      "enum": [
        "1",
        "2",
        "3",
        "4"
      ]
    }
  }
```
[enum.swagger.json.zip](https://github.com/swagger-api/swagger-ui/files/905257/enum.swagger.json.zip)

![enum](https://cloud.githubusercontent.com/assets/3653040/24793889/ff736d2e-1b83-11e7-9623-4c61ad0bcf2b.png)

![image](https://cloud.githubusercontent.com/assets/3653040/24796404/214b2802-1b8d-11e7-8ac3-523019606392.png)

In swagger editor: error for parameter reference

![image](https://cloud.githubusercontent.com/assets/3653040/24797111/1e2aca8a-1b90-11e7-9f45-fad88586dc81.png)

It's very confusing from one version to another, and from one tool to another :)

**Comment by webron** [comment]
As you said, there are two separate issues here.

In the models view (@bodnia) - anything that's not an object has no name, an it should (the name of the definition).

In the operation view - you can't reference types from non-body parameters. This is split into two - @shockey, we need to make sure the new validator marks this as an error (like the old one). And two (@bodnia, @shockey) - no type should be displayed for the parameter when it's invalid.

**Comment by matthieugeerebaert** [comment]
Hello,

Concerning "you can't reference types from non-body parameters", I think the problem is more relative to Open API Initiative spec. Problem for current spec with enums, wich are absolutely usable as query or path param ( string, int etc ), is that when using code generator we are facing anonymous enums, sometimes 3/4 times the same enum.. That's why we used to referenced enum definition from non body parameters. It worked like a charm before with swagger-ui ui 2., and swagger code gen :)

OAI ( swagger ) should allow use of enum definition :) It 's also more natural to define them in model and then use it in model, body param, or path/query/header param

**Comment by webron** [comment]
3.0 is already going to allow it. But 2.0 does not, and we will not support it in the UI. You can still use enums directly in the parameter definition, just not reference it.

**Comment by hkosova** [comment]
There's a workaround to reference an enum using YAML `&anchors` as shown in https://github.com/OAI/OpenAPI-Specification/issues/300#issuecomment-77669429. Not all tools support that - it depends on the tool's YAML parser - but Swagger UI does.

**Comment by webron** [comment]
Non-object definitions now have the name displayed under the Models section, and the editor shows errors for the wrong definition.
