### ISSUE TITLE
Model element titles not rendered

### ISSUE THREAD

**Issue by liamdennehy** [swagger-api/swagger-ui#2879]
Simple model elements seem to only be displaying their definitions (in my example: def2, def3), while complex elements have their names rendered (def1, def4)
[Simple model](https://www.wiemax.net/swagger-ui/?url=/Dump/an.yaml)

The relevant div sections in the rendered HTML seem to be wrapped in this block:
`<!---react-text: ###--->`
Where '###' is a number

**Comment by webron** [comment]
Closing as duplicate of #2875.
