### ISSUE TITLE
Models inconsistently validated depending on Explore url type

### ISSUE THREAD

**Issue by liamdennehy** [swagger-api/swagger-ui#2880]
When using an absolute URL for the model, a nice green "Valid" is shown at the bottom of a view.
`https://www.somehost.net/swagger-ui/?url=https://www.somehost.net/swagger/model.yaml`
Using a relative link is not so kind:
`https://www.somehost.net/swagger-ui/?url=/swagger/model.yaml`

**Comment by webron** [comment]
That makes sense. We pass the URL as you provide it to the validator. We could compute it before sending it, but tbh, that would be a low priority on the list.

Please consider submitting a PR.

**Comment by heldersepu** [comment]
It seems this has been fixed...
both urls work on the initial request, and here are some working test of my own:

http://turoapi.azurewebsites.net/swagger/ui/index?url=http://offleaseonly.azurewebsites.net/swagger/docs/V1

http://turoapi.azurewebsites.net/swagger/ui/index?url=/swagger/docs/V1

**Comment by shockey** [comment]
Closing in favor of https://github.com/swagger-api/swagger-ui/issues/2978.
