### ISSUE TITLE
Try out still not working when no host is specified

### ISSUE THREAD

**Issue by steinsag** [swagger-api/swagger-ui#2887]
Tested with 3.0.5 distribution release from github. Still same situation as with #2760. In my swagger.json, I only have:

- basePath: /somePath
- schemes: HTTP, HTTPS

Swagger UI is served on the same host. Still, in Chrome Network Tab, I see that URLs of the form

`http:///basePath/resource`

are requested when clicking the Try Out button.

**Comment by shockey** [comment]
Can you provide me with your spec?

If it's private, feel free to email me at kyleshockey@gmail.com.

**Comment by steinsag** [comment]
I removed all sensitive data from my swagger.json and I can reproduce it with this rather simple one:

`{
            "basePath": "/live/API/WS",
            "consumes": [
                "application/json"
            ],
            "definitions": {
                "ExampleUser": {
                    "properties": {
                        "enterpriseId": {
                            "description": "ID of enterprise the user belongs to",
                            "example": 123456,
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            },
            "info": {
                "title": "Example API",
                "version": "2017-07"
            },
            "paths": {
               "/SWISSCOM/Sep/User/{userId}": {
                    "get": {
                        "description": "Returns a single user",
                        "parameters": [
                            {
                                "default": "some-id",
                                "description": "ID of the user",
                                "in": "path",
                                "name": "userId",
                                "required": true,
                                "type": "string"
                            }
                        ],
                        "responses": {
                            "200": {
                                "description": "list of all users",
                                "schema": {
                                    "$ref": "#/definitions/ExampleUser"
                                }
                            }
                        },
                        "summary": "Get single initialized user by ID.",
                        "tags": [
                            "example"
                        ]
                    }
                }
            },
            "produces": [
                "application/json"
            ],
            "schemes": [
                "https",
                "http"
            ],
            "security": [
                {
                    "BasicAuth": []
                }
            ],
            "securityDefinitions": {
                "BasicAuth": {
                    "type": "basic"
                }
            },
            "swagger": "2.0",
            "tags": [
                {
                    "description": "API for example platform",
                    "name": "example"
                }
            ]
}`

**Comment by webron** [comment]
Issue confirmed. curl is generated correctly, but call execution leaves out the host.

**Comment by webron** [comment]
Closing in favor of #2904.
