### ISSUE TITLE
The swagger-ui does not support JSON Array as RequestBody

### ISSUE THREAD

**Issue by helxiong** [swagger-api/swagger-ui#2888]
**i use swagger-ui/dist as a new Java Web project,
when i pass JSON array as RequestBody, it happened exception like this:**
2017-04-10 16:16:32.557 [http-bio-8080-exec-5] DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Resolving exception from handler [public com.cummins.cdp.cd.api.model.response.Result com.cummins.cdp.cd.api.controller.CustomerRegisterApi.registrationPost1(java.util.ArrayList<com.cummins.cdp.cd.api.test.BaseParam>)]: org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Can not instantiate value of type [simple type, class com.cummins.cdp.cd.api.test.BaseParam] from String value ('['); no single-String constructor/factory method

**And this is my java code:**
@RequestMapping(value = "/maps", method = RequestMethod.POST)
	@ResponseBody
	@ApiOperation(value = "获得商品信息", notes = "获取商品信息(用于数据同步)", httpMethod = "POST", produces = MediaType.APPLICATION_JSON_VALUE)
	@ApiResponses(value = { @ApiResponse(code = 200, message = "商品信息"),
			@ApiResponse(code = 201, message = "(token验证失败)", response = String.class),
			@ApiResponse(code = 202, message = "(系统错误)", response = String.class) })
	public void getCommodity(@ApiParam(value = "Json参数", required = true) @RequestBody ArrayList<BaseParam> param)
			throws Exception {
		System.out.println("size:" + param.size());
		System.out.println(param.get(0).getShopName());
	}

Thanks a lot!

**Comment by webron** [comment]
The java code is not really relevant. We need to see the spec you're loading into the UI.
Also, which version of swagger-ui do you use?

**Comment by helxiong** [comment]
This is screenshot of my project structure:
![Uploading 捕获.PNG…]()

This is screenshot of swagger-ui.js and index.html:
![Uploading image.png…]()

and, what is needed?

**Comment by helxiong** [comment]
**This is my Java code of Swagger config:**

@Configuration
@EnableWebMvc
@EnableSwagger
public class SwaggerConfig extends WebMvcConfigurerAdapter {

	private SpringSwaggerConfig springSwaggerConfig;

	// Required to autowireSpringSwaggerConfig
	@Autowired
	public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
		this.springSwaggerConfig = springSwaggerConfig;
	}

	/**
	 * EverySwaggerSpringMvcPlugin bean is picked up by the swagger-mvc
	 * framework - allowing for multiple swagger groups i.e. samecode base
	 * multipleswagger resource listings.
	 */
	@Bean
	public SwaggerSpringMvcPlugin customImplementation() {
		return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(apiInfo()).includePatterns(".*")
				.useDefaultResponseMessages(false).apiVersion("1.0").build();
	}

	private ApiInfo apiInfo() {
		ApiInfo apiInfo = new ApiInfo("Test API List Platform", "Test Api list based on Swagger and built using Java.",
				"", "", "Test", "");
		return apiInfo;
	}

	@Override
	public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
		configurer.enable();
	}

}

**This is my java code of Spring mvc controller:**
@Controller
@Api(value = "commodity", description = "商品管理", produces = MediaType.APPLICATION_JSON_VALUE)
public class CommodityController {

	@RequestMapping(value = "/maps", method = RequestMethod.POST)
	@ResponseBody
	@ApiOperation(value = "获得商品信息", notes = "获取商品信息(用于数据同步)", httpMethod = "POST", produces = MediaType.APPLICATION_JSON_VALUE)
	@ApiResponses(value = { @ApiResponse(code = 200, message = "商品信息"),
			@ApiResponse(code = 201, message = "(token验证失败)", response = String.class),
			@ApiResponse(code = 202, message = "(系统错误)", response = String.class) })
	public void getCommodity(@ApiParam(value = "Json参数", required = true) @RequestBody ArrayList<BaseParam> param)
			throws Exception {
		System.out.println("size:" + param.size());
		System.out.println(param.get(0).getShopName());
	}

}

**This is url of index.html:**
url = "http://localhost:8080/swagger-api/api-docs";


this is part of the swagger-ui.js:
 * @version v2.2.10
 * @link http://swagger.io
 * @license Apache-2.0


anything else u need?

**Comment by webron** [comment]
yes, the actual spec that's loaded in the UI. I can't do anything with your java code.

**Comment by helxiong** [comment]
![Uploading shot.PNG…]()

**Comment by helxiong** [comment]
![Uploading shot.PNG…]()

**Comment by helxiong** [comment]
Is it convenient for you to give me your email? 
I give my package to you 
Thanks  👍

**Comment by webron** [comment]
You can send me the spec in an email, sure, but please don't send me the java project.

**Comment by helxiong** [comment]
**This is my pom.xml:**
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>my test</groupId>
	<artifactId>swagger-api</artifactId>
	<packaging>war</packaging>
	<version>0.0.1-SNAPSHOT</version>
	<name>swagger-api Maven Webapp</name>
	<url>http://maven.apache.org</url>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		
		
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j-impl</artifactId>
			<version>2.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
			<version>1.6.6</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.7</version>
		</dependency>
		
		
		<dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.4.2</version>
		</dependency>
		
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>

	</dependencies>
	<build>
		<finalName>swagger-api</finalName>
	</build>
</project>

**Comment by helxiong** [comment]
**This is my index.html:**
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="IE=edge">
  <title>Cummins API Platform</title>
  <link rel="icon" type="image/png" href="images/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="images/favicon-16x16.png" sizes="16x16" />
  <link href='css/typography.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/screen.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='print' rel='stylesheet' type='text/css'/>
  <link href='css/print.css' media='print' rel='stylesheet' type='text/css'/>

  <script src='lib/object-assign-pollyfill.js' type='text/javascript'></script>
  <script src='lib/jquery-1.8.0.min.js' type='text/javascript'></script>
  <script src='lib/jquery.slideto.min.js' type='text/javascript'></script>
  <script src='lib/jquery.wiggle.min.js' type='text/javascript'></script>
  <script src='lib/jquery.ba-bbq.min.js' type='text/javascript'></script>
  <script src='lib/handlebars-4.0.5.js' type='text/javascript'></script>
  <script src='lib/lodash.min.js' type='text/javascript'></script>
  <script src='lib/backbone-min.js' type='text/javascript'></script>
  <script src='swagger-ui.js' type='text/javascript'></script>
  <script src='lib/highlight.9.1.0.pack.js' type='text/javascript'></script>
  <script src='lib/highlight.9.1.0.pack_extended.js' type='text/javascript'></script>
  <script src='lib/jsoneditor.min.js' type='text/javascript'></script>
  <script src='lib/marked.js' type='text/javascript'></script>
  <script src='lib/swagger-oauth.js' type='text/javascript'></script>

  
  
  
  

  <script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "http://localhost:8080/swagger-api/api-docs";
      }

      hljs.configure({
        highlightSizeThreshold: 5000
      });

      // Pre load translate...
      if(window.SwaggerTranslator) {
        window.SwaggerTranslator.translate();
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            initOAuth({
              clientId: "your-client-id",
              clientSecret: "your-client-secret-if-required",
              realm: "your-realms",
              appName: "your-app-name",
              scopeSeparator: " ",
              additionalQueryStringParams: {}
            });
          }

          if(window.SwaggerTranslator) {
            window.SwaggerTranslator.translate();
          }
        },
        onFailure: function(data) {
          log("Unable to Load SwaggerUI");
        },
        docExpansion: "none",
        jsonEditor: false,
        defaultModelRendering: 'schema',
        showRequestHeaders: false,
        showOperationIds: false
      });

      window.swaggerUi.load();

      function log() {
        if ('console' in window) {
          console.log.apply(console, arguments);
        }
      }
  });
  </script>
</head>

<body class="swagger-section">
<div id='header'>
  <div class="swagger-ui-wrap">
    <a id="logo" href="http://swagger.io"><img class="logo__img" alt="swagger" height="30" width="30" src="images/logo_small.png" /><span class="logo__title">swagger</span></a>
    <form id='api_selector'>
      <div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text"/></div>
      <div id='auth_container'></div>
      <div class='input'><a id="explore" class="header__btn" href="#" data-sw-translate>Explore</a></div>
    </form>
  </div>
</div>

<div id="message-bar" class="swagger-ui-wrap" data-sw-translate>&nbsp;</div>
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
</body>
</html>

**Comment by helxiong** [comment]
**This is swagger-ui.js:**

/**
 * swagger-ui - Swagger UI is a dependency-free collection of HTML, JavaScript, and CSS assets that dynamically generate beautiful documentation from a Swagger-compliant API
 * @version v2.2.10
 * @link http://swagger.io
 * @license Apache-2.0
 */

**Comment by helxiong** [comment]
**This is Spring MVC controller:**

package com.swaggerui.list.api.controller;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.swaggerui.list.api.test.BaseParam;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;

@Controller
@Api(value = "commodity", description = "商品管理", produces = MediaType.APPLICATION_JSON_VALUE)
public class CommodityController {

	@RequestMapping(value = "/maps", method = RequestMethod.POST)
	@ResponseBody
	@ApiOperation(value = "获得商品信息", notes = "获取商品信息(用于数据同步)", httpMethod = "POST", produces = MediaType.APPLICATION_JSON_VALUE)
	@ApiResponses(value = { @ApiResponse(code = 200, message = "商品信息"),
			@ApiResponse(code = 201, message = "(token验证失败)", response = String.class),
			@ApiResponse(code = 202, message = "(系统错误)", response = String.class) })
	public void getCommodity(@ApiParam(value = "Json参数", required = true) @RequestBody ArrayList<BaseParam> param)
			throws Exception {
		System.out.println("size:" + param.size());
		System.out.println(param.get(0).getShopName());
	}
}

**Comment by helxiong** [comment]
**This is my swagger config:**

package com.swaggerui.list.api.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.DefaultServletHandlerConfigurer;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;

import com.mangofactory.swagger.configuration.SpringSwaggerConfig;
import com.mangofactory.swagger.models.dto.ApiInfo;
import com.mangofactory.swagger.plugin.EnableSwagger;
import com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin;

@Configuration
@EnableWebMvc
@EnableSwagger
public class SwaggerConfig extends WebMvcConfigurerAdapter {

	private SpringSwaggerConfig springSwaggerConfig;

	// Required to autowireSpringSwaggerConfig
	@Autowired
	public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
		this.springSwaggerConfig = springSwaggerConfig;
	}

	/**
	 * EverySwaggerSpringMvcPlugin bean is picked up by the swagger-mvc
	 * framework - allowing for multiple swagger groups i.e. samecode base
	 * multipleswagger resource listings.
	 */
	@Bean
	public SwaggerSpringMvcPlugin customImplementation() {
		return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(apiInfo()).includePatterns(".*")
				.useDefaultResponseMessages(false).apiVersion("1.0").build();
	}

	private ApiInfo apiInfo() {
		ApiInfo apiInfo = new ApiInfo("Test API List Platform", "Test Api list based on Swagger and built using Java.",
				"", "", "Test", "");
		return apiInfo;
	}

	@Override
	public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
		configurer.enable();
	}
}

**Comment by webron** [comment]
We need a file that looks like http://petstore.swagger.io/v2/swagger.json.

**Comment by virgo47** [comment]
I got the same problem when I omitted `responses` in the `get` section. After I added them (e.g. just 405 from example) it worked.
