### ISSUE TITLE
Make the Swagger UI display the deprecate tag

### ISSUE THREAD

**Issue by eyala** [swagger-api/swagger-ui#289]
Swagger-core respects and passes on the Java @Deprecated annotation. It would be nice if Swagger-UI, by default, displayed this information on operations

**Comment by fehguy** [comment]
this is now supported in develop_2.0

**Comment by CraigFoote** [comment]
Sorry it's not clear to me how I can deprecate a controller method :(

**Comment by webron** [comment]
@CraigFoote - a controller method?

**Comment by CraigFoote** [comment]
Sorry, bad terminology I guess. My rest endpoints are documented with @API* annotations at the controller method level. I've marked the method @Deprecated and added the Javadoc @deprecated but swagger UI renders as before, no indication of deprecation. Reading this issue leads me to think maybe I can edit one of those @API annotations to produce a change in the way swagger UI renders the endpoint, presumably with a strikethrough font. Am I on close? Thanks for the quick reply BTW.

**Comment by webron** [comment]
@CraigFoote - this is an issue with the library generating the Swagger definition rather than with swagger-ui as it probably doesn't parse the `@Deprecated` annotation. I'd suggest opening an issue on that library.

**Comment by jkoepcke** [comment]
The current "Warning: deprecated" headline is only visible after you show the details of an operation. And since it has the same style as the remaining info, it is hardly visible. I created a pull request here:

https://github.com/swagger-api/swagger-ui/pull/1740

This change shows the deprecated operations strikethrough.
