### ISSUE TITLE
Provide spec chooser drop-down functionality instead of URL input box for shared instances

### ISSUE THREAD

**Issue by zyv** [swagger-api/swagger-ui#2891]
Hi,

Currently, Swagger UI has an input box where the spec URL can be entered. For shared intranet installations, it would be great to have a drop-down that allows to browse through available specs.

The contents for the drop-down should be retrievable from a local spec repository (or hot served) as JSON and might contain spec name, spec url, maybe tags and whether it's a default spec. Using this data the drop-down can be rendered.

I have implemented a prototype, which you can find here:

https://github.com/moneymeets/swagger-ui/commits/moneymeets/v3.0.5

The way it works is that it looks for `/specs/list_specs.json` and uses this to render drop-down. In our case, this is a static file generated by our CI server upon changes to our spec repository. Just to clarify the idea and provide some code for inspiration...

I'm not submitting a pull request, because first, I think, it would be great if maintainers could make their opinion on this feature, what should be contained in JSON and how it should be rendered, what should be the configuration interface, etc.

Many thanks for working on Swagger UI!

**Comment by degerstrom** [comment]
Inspired by the modifications made by @zyv I made similar modifications to accomodate some of our needs. In my version, the endpoint to retrieve the JSON list of specs is defined as a JavaScript variable in the HTML document, and each item in the JSON must have a `url` (which is a **full** url to the JSON file) and `title` attribute. The dropdown displays the title, not the URL.

My commit is here: https://github.com/EcoOnline/swagger-ui/commit/a6acd70de7911e78df0a7a1e6ed3e5f4df317a24

**Comment by webron** [comment]
@zyv, @degerstrom  (and anyone else watching) - can we discuss the details on how you see this feature being implemented? Once we agree on those, if either of you submit a PR to add it, we'd merge it in. Due to limited resources I can't put it high on the priority list, but it doesn't mean we won't take contributions to add it.

**Comment by lukastosic** [comment]
@webron 
On our projects we often have one of 2 scenarions, sometimes even combined:
1. Maintain live multiple versions of API
2. Develop with "documentation first" approach (we spend lots of time to design our API in swagger before we do implementation)

For couple of days now we used solution from @zyv ( I just saw solution from @degerstrom , I haven't tested it out) and it works pretty good .. we have our own internal user friendly domain with deployed swagger and all supported and future (in development) versions for our developers. Works good for us 👍 

For one of the projects we have dedicated repository with only documentation files, any update there triggers Jenkins that deploys it to (docker) environment where everybody (that matters ;) ) can see documentation for the app.

Also it is good that with specific file `list_specs.json` I can customize what files to show, so for public deployment I can show only files (versions) that are deployed on prod, but on internal environment I can also show "in-progress" version(s) for developers

**Comment by zyv** [comment]
@webron 

Our use case at @moneymeets is same as p. 2 of @lukastosic : we have a repo with swagger specs for our APIs, which is connected to Jenkins and specs are checked & deployed internally to our Swagger UI instance, where you can select an API out of the available options and interact with it.

Being extremely busy (and having absolutely no clue about frontend development), I only did the smallest possible changes to allow for this use case, but I think it would be nice to:

1. Make a knob to allow specifying the location of spec listing in the configuration (also a full URL, which would make it possible to host spec lists & Swagger UI on different servers)
2. Think about some optional metadata for the spec listing (like captions to be shown in the list), and, in any case, make it a list of dicts, rather than a list of strings
3. Make it possible to specify relative or absolute URLs as spec locations, or maybe make a knob in the config like base path, although I'm not sure whether the latter is actually a good idea

I think that changes by @degerstrom go in this direction, but sadly I didn't have time to look into them.

In any case, I would be very happy if this were included in the distribution or made available as a plugin in any form or shape that would be useful to us, because I certainly would like to avoid maintaining our own fork of Swagger UI, just because of this little change...

**Comment by zyv** [comment]
@slavaschmidt not sure how much time do you have to OSS work these days, but I'm pinging you, because you might be also interested in upstreaming spec chooser into Swagger UI. Stuff you are currently using for API First Hand is way out of date... upstreaming it will mean that you don't have to maintain your fork ;-)

**Comment by shockey** [comment]
Hi everyone, just wanted you to know that I laid out a basic plugin setup for a dropdown spec selector in another ticket: https://github.com/swagger-api/swagger-ui/issues/3103#issuecomment-302623899

@webron, +1 for a plugin repository 😄

**Comment by webron** [comment]
@shockey I like the idea, but we need to figure out the packaging

**Comment by webron** [comment]
This is now implemented via #3261.

**Comment by zyv** [comment]
Wow, awesome, thank you guys, will have a look into it!

**Comment by webron** [comment]
This is thanks to @supergibbs's generous contribution 😄
