### ISSUE TITLE
CSRF tokens in version 3.x

### ISSUE THREAD

**Issue by mark4prime** [swagger-api/swagger-ui#2896]
Is it possible to add headers to a specific request in version 3.x as the methods referred to here #1380 no longer appear to work in version 3.x ? I know how to get the required value for the header but there does not appear to be a way to set this in the request anymore.

**Comment by webron** [comment]
Unfortunately, it's not supported yet in 3.x. See https://github.com/swagger-api/swagger-ui/issues/2793 for more details.

**Comment by shockey** [comment]
Closing this as 3.x now supports `requestInterceptor` and `responseInterceptor` (see #2793 and the README for more information).
