### ISSUE TITLE
configuring OAuth for 3.x

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#2897]
Previously we could configure the oauth client id, client secret, realm, appname, scope separator in the index.html.  This made sense, since these would typically be static for a single API, and swagger-ui would render the UI specifically for it.

It's not clear how this is done with swagger-ui 3.x.  We want to have a way to configure the above values as the end user will really have no idea what they are, nor should they have any business messing with them.

I'd like to see a way to configure them in the index.html like before, and have it documented in the README.md.  This is a high priority because until they're in here documented, the OAuth support is almost useless.

**Comment by banejasika** [comment]
Any update on this?
