### ISSUE TITLE
Update documentation of configurations

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#2898]
The _allowed_ configurations for the UI are documented [here](https://github.com/swagger-api/swagger-ui/blob/master/src/plugins/configs/index.js):

```
const CONFIGS = [ "url", "spec", "validatorUrl", "onComplete", "onFailure", "authorizations", "docExpansion",
    "apisSorter", "operationsSorter", "supportedSubmitMethods", "highlightSizeThreshold", "dom_id",
    "defaultModelRendering", "oauth2RedirectUrl", "showRequestHeaders" ]
```

The README is missing many of these configuration values, which means either this list above is wrong, or there are features that we have that are not documented

**Comment by webron** [comment]
These configurations are listed, but not all implemented. As far as I know, the implemented configs are documented.

**Comment by bodnia** [comment]
All implemented configs are documented.
