### ISSUE TITLE
can't execute call when enum is default value 

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#2902]
See below.  In this definition:

https://generator.swagger.io/api/swagger.json

There is a definition where a value is required to execute.  As you can see, the selected value is "valid" but it won't let you select.  You have to choose the 2nd value in order to make a call.

![image](https://cloud.githubusercontent.com/assets/249413/24933381/e83164e6-1eca-11e7-9685-d3a75841ea41.png)

**Comment by shockey** [comment]
Confirmed, working on it!

**Comment by webron** [comment]
Also resolved in master by #2841.
