### ISSUE TITLE
missing host still not working

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#2904]
This should have been addressed but as of now, I'm not seeing proper behavior.

Using this URL against the petstore, which is latest master:

http://petstore.swagger.io/?url=https://generator.swagger.io/api/swagger.json

I see two issues.

First, the CURL url is incorrect.  Note the protocol should be `https`:

![image](https://cloud.githubusercontent.com/assets/249413/24933850/73002380-1ecd-11e7-9c12-44bae8d29556.png)

Next, the request never actually succeeds.  Note the URL in the network console:

![image](https://cloud.githubusercontent.com/assets/249413/24933869/84edebae-1ecd-11e7-9217-cf162d2ed0ec.png)

**Comment by Bert-R** [comment]
I see slightly different behavior with 3.0.5. The good news is that it works for me, even with HTTPS. The only issue that I see is that the displayed curl command is wrong.

You can try it out yourself here: https://beta.prd.yona.nu/swagger-ui/index.html. If you just take the first operation and provide a nonsense user ID and password, you'll get an error, which indicates that request properly reaches the server.

The curl command is wrong:

```
curl -X POST "http://users/asdf/pinResetRequest/request" -H  "accept: application/json" -H  "content-type: application/json" -H  "Yona-Password: asdf"
```

That should have been:

```
curl -X POST "https://beta.prd.yona.nu/users/asdf/pinResetRequest/request" -H  "accept: application/json" -H  "content-type: application/json" -H  "Yona-Password: asdf"
```

So: HTTPS and the right host name.

The Swagger spec is referenced as ``../swagger/swagger-spec.yaml`` from ``index.html``.

**Comment by shockey** [comment]
Scheme problem is fixed: if no scheme is defined in the spec, we will try to extract a valid scheme from the URL the spec is loaded from (doesn't affect relative-path spec URLs) before falling back to `http` as a last resort.

For the second part, looks like `baseUrl` in swagger-js is being called _twice_ when Execute is clicked- it's called once with the `contextUrl`, and once without. The actual request that fires is the one without, which breaks the functionality. Investigating.

**Comment by shockey** [comment]
Found it- fix incoming.

**Comment by larshp** [comment]
thanks, now it works for me 👍

**Comment by Bert-R** [comment]
The curl command is now right but unfortunately HTTPS doesn't work anymore.

I've logged #2919 for this.
