### ISSUE TITLE
API with HTTP Basic behind Apache

### ISSUE THREAD

**Issue by senty** [swagger-api/swagger-ui#2905]
Hi guys,
i have tried to use latest Swagger-ui (branch 2.x) to call API.

Problem is, that API server is behind apache with HTTP Basic Auth.

**I have added into my swagger yaml following**
`securityDefinitions:`
` devsec:`
`    type: basic`
`security:`
`  - devsec: []`

**But when i hit button 'Try it out!' generated is request :**
Request URL:https://dev.XXX.com/rest/wall
Request Method:OPTIONS
Status Code:401 Authorization Required
Remote Address:195.80.163.50:443
Referrer Policy:no-referrer-when-downgrade
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:sk,cs;q=0.8,en-US;q=0.6,en;q=0.4,zh-TW;q=0.2,zh;q=0.2
Access-Control-Request-Headers:authorization
Access-Control-Request-Method:GET
Cache-Control:no-cache
Connection:keep-alive
Host:dev.XXX.com
Origin:http://api-doc.XXX.com
Pragma:no-cache
Referer:http://api-doc.XXX.com/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**How can i "decorate" that each request from SwaggerUI towards API server will have Authorization Header ?**

Thank you very much !

**Comment by webron** [comment]
It looks like the issue is with your server. For some reason it requires authentication for OPTION calls, and it shouldn't. See https://github.com/swagger-api/swagger-ui/issues/2663#issuecomment-280059347 for more details.

**Comment by senty** [comment]
@webron thank you very much for help !
I guess setup exception for OPTION will solve problem (https://stackoverflow.com/questions/23618072/how-i-can-avoid-requesting-basic-authentication-when-http-method-is-options-on-a)

i will update with result ...

thanks

**Comment by senty** [comment]
Hi,
confirming - after i allowed OPTION without http basic -> everything is fine
