### ISSUE TITLE
New swagger ui is sending unnecessary content-type header

### ISSUE THREAD

**Issue by nahidakbar** [swagger-api/swagger-ui#2909]
Even when it is just making get requests and is not sending any kind of payload.

I haven't even set any consumes directives in the spec.

This was not an issue with the old UI and that was the correct behaviour.

While just making simple requests cross domain does not require any kind of special implementations, sending custom headers like these requires implementation of server side CORS preflight.

**Comment by webron** [comment]
With https://github.com/swagger-api/swagger-js/pull/1016 merged, this will be fixed in Friday's release.
