### ISSUE TITLE
Missing configuration in v3.0.5

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-ui#2911]
I notice that none of these options from version 2 are being honored.  Is this just a case of "not yet implemented" or has the way this works changed?

        // This one is what sorts the methods inside the tags
        operationsSorter: function (a, b) { 
            var order = { 'get': '0', 'post': '1', 'patch' : '2', 'put': '3', 'delete': '4' }; 
            var foo = order[a.method].localeCompare(order[b.method]);
            if (foo == 0) {
                return a.path.localeCompare(b.path);
            } else {
                return foo;
            }
        },

        // This one is what sorts the tags.
        apisSorter: 'alpha',

        // This makes the model show by default, with all the parameter descriptions
        defaultModelRendering: 'model',

        jsonEditor: true

**Comment by webron** [comment]
Not implemented yet. See [Known Issues](https://github.com/swagger-api/swagger-ui#known-issues) and the available [parameters](https://github.com/swagger-api/swagger-ui#known-issues).

**Comment by dotasek** [comment]
Is there any way to indicate the priority of each parameter implementation? The lack of apisSorter and docExpansion are pretty much the only thing keeping me from transitioning to 3.x

**Comment by webron** [comment]
The ticket is marked as P2, meaning it's second-tier priority. If it's important to you, consider submitting a PR to add the functionality (with tests 😄).

**Comment by krishnan-unni** [comment]
Hi, is there a timeline or ETA on the availability of JSON Form Editor in 3.x version. Thats what I am waiting fro migrating to 3.x

**Comment by shockey** [comment]
`tagsSorter`, `operationsSorter`, and `defaultModelRendering` are implemented now.

JSON Form Editor is being tracked here: https://github.com/swagger-api/swagger-ui/issues/2771

Closing, thanks everyone!
