### ISSUE TITLE
(New Swagger UI ) Authorize button not sending custom access-token in headers

### ISSUE THREAD

**Issue by Alfafc** [swagger-api/swagger-ui#2913]
I have this ApiKeyAuthDefinition:

`access-token:{description: "Access token Authentication", type: "apiKey", name: "access-token", in: "header"}
description:"Access token Authentication"
in:"header"
name:"access-token"
type:"apiKey"`

I also have a specific SwaggerSpecFilter that only allow to see my swagger.json when you have authorized with required access-token.

Using main Authorize button in new Swagger-ui , wont send the access-token in headers, so SpecFilter dont show me all methods in swagger.json.
This work well in old version.

Let me now if anybody else is experincing this or if you need more info.
Thanks!

**Comment by webron** [comment]
When you define a security inside the spec, it's related to the API itself, not access to the spec. We have not yet implemented in 3.x a way to send those headers when accessing the spec.

**Comment by shockey** [comment]
Closing; the [`requestInterceptor` option](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#network) solves this :smile:
