### ISSUE TITLE
Basic auth dialog in 3.0.5

### ISSUE THREAD

**Issue by svechin** [swagger-api/swagger-ui#2914]
I have basic auth in swagger configuration:
"securityDefinitions": [
    {"type": "basic"}
  ] 

when i click authorize on UI i get dialog but after entering credentials and clicking authorize button in dialog - nothing happens. did I miss anything?

**Comment by webron** [comment]
can you share your spec?

**Comment by svechin** [comment]
here is part of the spec, nothing else what is related to security.
but spec is validated successfully in 3.0.5 and it works in 2.x

may be it could help - i wasn't able to install swagger-ui using npm because there were errors related to msbuild so i just cloned it and copied dist folder. 

{
  "info": {
    "title": "111",
    "description": "111",
    "version": "1.0.0"
  },
  "basePath": "localhost:3010/api/v1",
  "tags": [    
....
  ],
  "securityDefinitions": [
    {
      "type": "basic"
    }
  ],
  "swagger": "2.0",
  "paths": {
...
  }
}

**Comment by webron** [comment]
That's not a valid spec. `securityDefinitions` are meant to declare security schemes, and `security` is meant to apply them.

**Comment by svechin** [comment]
thanks, but even if i add something like 
"security":[
    {
      "basic": {}
    }
  ]

it behaves the same - auth button in dialog does nothing

**Comment by webron** [comment]
But your `securityDefinitions` is invalid. This is why I asked for a full working spec, so I can play with it, test it, and either confirm the bug or give you a working solution.

**Comment by svechin** [comment]
Here is spec which is enough to reproduce issue. Apply spec, click authorize, enter credentials, click authorize again - i expect modal to be closed and basic header will be send with requests.

Thank you for your efforts!

`{
  "info": {
    "title": "Api",
    "description": "External Api",
    "version": "1.0.0"
  },
  "basePath": "localhost:3010/api/v1",
  "tags": [
    "Users"
  ],
  "securityDefinitions": [
    {
      "type": "basic"
    }
  ],
  "security":[
    {
      "basic": []
    }
  ],
  "swagger": "2.0",

  "paths": {

    "/users": {

      "get": {
        "tags": [
          "Users"
        ],
        "description": "Returns users",
        "operationId": "user-lists",
        "produces": [
          "application/json"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "User response"
          }
        }
      }
    }
  }
}`

**Comment by webron** [comment]
Change your `securityDefinitions` to this:
```json
  "securityDefinitions": {
        "basic": {
            "type": "basic"
        }
    }
```

**Comment by svechin** [comment]
it works. thank you!
