### ISSUE TITLE
Body input parameter showing as form not raw JSON?

### ISSUE THREAD

**Issue by eneropp-dave** [swagger-api/swagger-ui#2921]
Hi,

I had this working on some code a few weeks ago, but I lost the code and can't work out if I'm doing something stupid, or the feature has changed in a more recent version of swagger ui (I think I also updated while rewriting the code).

I am using Swagger annotation inside a project, and swagger UI to view it, I have a POST route using the body input parameter which uses a swagger definition for the schema. I want to display a form on swagger UI that looks like the below, either with the body pre-populated with the JSON, or to click on the JSON model to populate the body parameter, but what I am getting is a form rather than the JSON:

What I want to see is similar to this:
![image](https://cloud.githubusercontent.com/assets/19832838/25087577/ce6d5a46-2367-11e7-927e-f3da3e04dbdc.png)

What I actually see is the below:
![image](https://cloud.githubusercontent.com/assets/19832838/25087553/a4a8233a-2367-11e7-8f2e-f3ff7b444e6e.png)

The code I am using is:

```
/**
* @SWG\Definition(
*        definition="test_input_id",
*        required={"test_input"},
*        @SWG\Property(property="test_input", type="string", example="456"),
*        @SWG\Property(property="test_input2", @SWG\Property(property="test_input3", type="string", example="720")),
* )
 */
```

```
$app->post('/test_account_num_from_id_Function', function($request, $response, $args) use ($app){
/**
 * @SWG\Post(
 *     tags={"Utility"},
 *     path="/test_account_num_from_id_Function",
 *     summary="Test harness to check generic functions and play with other ideas before putting into full methods",
 *		 consumes={"application/JSON"},
 *		 produces={"application/JSON"},
 *     @SWG\Parameter(name="body",in="body",description="JSON input", required=true, @SWG\schema(ref="#/definitions/test_input_id")),
 *     @SWG\Response(response="200", description="Success"),
 *     @SWG\Response(response="500", description="Internal server error"),
 * )
 */
  try{
     // <code here>
  }catch(Exception $e){
     // <code here>
  }
  finally{
     // <code here>
  }
});
```

It is frustrating because I know I had it working before I lost the code, and the form is working with the model on the right, when I click it then it changes the values, so I'm sure I'm pretty close

**Comment by eneropp-dave** [comment]
Just confirmed - I am on Swagger UI 2.1.4 and haven't updated it since lost the code, so it is definitely me

**Comment by hkosova** [comment]
Looks like you have [`jsonEditor: true`](https://github.com/swagger-api/swagger-ui/tree/2.x#parameters) (aka JSON form editor) in your Swagger UI initialization code.

**Comment by eneropp-dave** [comment]
Thanks, you are quite right, I didn't realise that setting existed but changing it gets the behaviour i wanted, thanks again
