### ISSUE TITLE
No pretty json for Response examples

### ISSUE THREAD

**Issue by synackSA** [swagger-api/swagger-ui#2928]
I have the following response defined for a 500 Internal Sever error.

    500InternalServerError:
        description: The server encountered an unexpected condition which prevented it from fulfilling the request
        schema:
          allOf:
            - $ref: '#/definitions/Failure'
        headers:
          X-Rate-Limit-Limit:
            description: The number of allowed requests in the current period
            type: integer
          X-Rate-Limit-Remaining:
            description: The number of remaining requests in the current period
            type: integer
          X-Rate-Limit-Reset:
            description: The number of seconds left in the current period
            type: integer
        examples:
          application/json:
            code: -1
            message: The server encountered an unexpected condition which prevented it from fulfilling the request

When I load it up in swagger-ui, it looks like this:

[![Json Response Format][1]][1]

  [1]: https://i.stack.imgur.com/Waoc4.png

Why is the response not formatted in a pretty format over multiple lines, like it is when no example is given and it auto creates one?

    {
      "code": "-1",
      "message": "The server encountered an unexpected condition which prevented it from fulfilling the request"
    }

**Comment by webron** [comment]
Probably jut the conversion to JSON.

**Comment by immesys** [comment]
I would love this feature too.

**Comment by webron** [comment]
Closed by #3238.
