### ISSUE TITLE
formatting issues with authorization panel

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#2929]
After authorizing, we leave the authorization panel visible and show the key in an unformatted text:

![image](https://cloud.githubusercontent.com/assets/249413/25193500/30a572ae-24ec-11e7-916e-b2a8a36e9de1.png)

First, we should probably close it after you add authorization.

Next, we should mask the authorization token once it's entered

Finally, we should use the proper font to render the masked authorization token

**Comment by webron** [comment]
Closing doesn't make sense because you might need to provide multiple authorizations and having to reopen the modal for each one is an odd behavior.

Masking should be simple.
