### ISSUE TITLE
Programmatically setting clientId/clientSecret for OAuth flow

### ISSUE THREAD

**Issue by lakmali** [swagger-api/swagger-ui#2930]
I am trying the OAuth flows in swagger UI latest released version (3.0.6). There it seems to be that we can no longer call "initOAuth" and pre populate the OAuth client credentials. 

Is there any way we can programmatically inject clientId/clientSecret to swagger UI so that end user will not have to input them?

**Comment by webron** [comment]
We're working on it. Duplicate of #2897.

**Comment by lakmali** [comment]
Thanks
