### ISSUE TITLE
 swagger-ui-bundle.js:58880 Could not find component

### ISSUE THREAD

**Issue by mgeorgy** [swagger-api/swagger-ui#2931]
Swagger-ui loads without issue, however when attempting to use the 'Try it out' feature I'm noticing several warnings within the swagger-ui-bundle.js.  Is this known/expected behavior?

The general errors are:
swagger-ui-bundle.js:58880 Could not find component JsonSchema_string_
swagger-ui-bundle.js:58880 Could not find component JsonSchema_integer_
swagger-ui-bundle.js:58880 Could not find component JsonSchema_integer
swagger-ui-bundle.js:58880 Could not find component JsonSchema_string_boolean
swagger-ui-bundle.js:58880 Could not find component JsonSchema_string_full-date

**Comment by fehguy** [comment]
Are you running from the project directory or have you brought swagger-ui-bundle.js into your own project?  If so, can you please share how you did it?

**Comment by mgeorgy** [comment]
I'm running out of the dist directory.

`
DocumentRoot /var/www/swagger-ui/dist
`

**Comment by fehguy** [comment]
eh, that's not the project directory.  I have a feeling you're missing some files in there.

**Comment by mgeorgy** [comment]
Any suggestions on resolving this?  I cloned the project to this directory.  What files do you think I might be missing?

**Comment by shockey** [comment]
These warnings are nothing to be worried about 😄 

In the json schema rendering code, we [optimistically query our system for a number of components](https://github.com/swagger-api/swagger-ui/blob/master/src/core/json-schema-components.js#L39). If the component doesn't exist, those warnings get thrown.

As long as you're not seeing render errors accompanying those warnings, you should be good to go.

@fehguy, if we want to silence these errors, we can modify this code to query for the component before attempting to get a reference to the component.

**Comment by mgeorgy** [comment]
Thank you!

**Comment by Download** [comment]
If it really is nothing to be worried about, it would probably be best to silence the warning. People will worry about it and google the warning and find this issue and add a comment here... Like I'm doing right now.   😄

**Comment by glad4enkonm** [comment]
Hi, it looks like I faced this issue. Could you have a look?
My api responds with int64 number and I can not retrieve instance by this id later,
because value in UI is rounded (4 errors in console are the correct respond from the api ).

![image](https://user-images.githubusercontent.com/11142000/33796904-2c941966-dcfe-11e7-97ec-5b614558774e.png)

**Comment by Download** [comment]
> My api responds with int64 number

Does it actually use all those 64 bits?

It is important to understand that Javascript does not have Integer and Float. Instead, it only has Number, which is a 64-bit floating point format. The integer numbers are encoded as 64 bit floats. [**This means you can only safely store int's that fit in 53 bits**](http://2ality.com/2013/10/safe-integers.html).

Check out [Number.MIN_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER) and [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)... Only ints that fall in this range are 'safe' to be encoded using Number. 

If you need support for larger numbers, the way to do that is by using a custom library, such as [big-number](https://www.npmjs.com/package/big-number). It is a very similar situation to say using 128 bit numbers in Java... It can't be done natively, you need a support library. In JS this happens for integers bigger than 53 bits or floats bigger than 64 bits.

**Comment by glad4enkonm** [comment]
Thanks, Download, for your explanation!
