### ISSUE TITLE
Generate swagger response example

### ISSUE THREAD

**Issue by catchaag** [swagger-api/swagger-ui#2932]
Hi,

I am trying to generate response examples into swagger.json file for all my operations. I see i can generate response in this way only
@ApiResponses(value = { @ApiResponse(code = 200, message = "Returns pet list",response = Pet.class),

Is there any other way to generate response examples into swagger file. It will also be good if i can copy my raw json into my resource and that can go into swagger file. 
Please help.
Thanks

**Comment by webron** [comment]
You can add them manually. Check out http://swagger.io/docs/specification/adding-examples/ for more details.

**Comment by catchaag** [comment]
we can not add a raw json ( { "id": 38, "title": "T-shirt" }) from the code??

**Comment by webron** [comment]
I don't think that option exists. Regardless, this doesn't belong here but in the tool you use to generate the spec.

**Comment by catchaag** [comment]
tool? what are the tools? 
I am generating a spec using my java code and gradle as below
@ApiResponses(value = { @ApiResponse(code = 200, message = "Returns pet list",response = Pet.class),

what tools we have to generate the spec?

**Comment by webron** [comment]
Whichever library you use to generate the spec from your code.

**Comment by catchaag** [comment]
i am using these libraries
compile group: 'io.swagger', name: 'swagger-parser', version: '1.0.21'
compile("io.swagger:swagger-jersey2-jaxrs:1.5.8")
 classpath 'com.benjaminsproule:swagger-gradle-plugin:0.0.6'

**Comment by webron** [comment]
So the project you're looking for is swagger-core. Like I said, I don't think we provide a way of adding examples in it yet.
