### ISSUE TITLE
Can't see Bearer Token in Headers.

### ISSUE THREAD

**Issue by kamleshpaliwal-tudip** [swagger-api/swagger-ui#2935]
Hello Everyone ,
I am using Swagger create documenattion of my existing api n node . I used swagger-ui to do and test the api. I am generating token from postman and using this token in swagger authorization but everytime  I m getting unauthorized access only. Even token is not available in headers also.please help me out.

**Comment by webron** [comment]
Can you explain more what it is you're doing and what doesn't work? It's still a bit unclear.
Also, which version of swagger-ui do you use?

**Comment by kamleshpaliwal-tudip** [comment]
I am using swagger-node-express": "^2.1.3. I am unable to see authorization token in headers. I am attaching some screen shots to clear this whole scenario to you.
First i logged in using postman and generated access token and then i m passing that token in  swagger as shown in pic but when i am giving request to API it is showing that user is unauthorized as shown in  3rd screenshot.
this is code of my index.html


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Swagger UI</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="swagger-ui.css" >
  <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />
  <style>
    html
    {
        box-sizing: border-box;
        overflow: -moz-scrollbars-vertical;
        overflow-y: scroll;
    }
    *,
    *:before,
    *:after
    {
        box-sizing: inherit;
    }

    body {
      margin:0;
      background: #fafafa;
    }
  </style>
</head>

<body>

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:absolute;width:0;height:0">
  <defs>
    <symbol viewBox="0 0 20 20" id="unlocked">
          <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V6h2v-.801C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8z"></path>
    </symbol>

    <symbol viewBox="0 0 20 20" id="locked">
      <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8zM12 8H8V5.199C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="close">
      <path d="M14.348 14.849c-.469.469-1.229.469-1.697 0L10 11.819l-2.651 3.029c-.469.469-1.229.469-1.697 0-.469-.469-.469-1.229 0-1.697l2.758-3.15-2.759-3.152c-.469-.469-.469-1.228 0-1.697.469-.469 1.228-.469 1.697 0L10 8.183l2.651-3.031c.469-.469 1.228-.469 1.697 0 .469.469.469 1.229 0 1.697l-2.758 3.152 2.758 3.15c.469.469.469 1.229 0 1.698z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="large-arrow">
      <path d="M13.25 10L6.109 2.58c-.268-.27-.268-.707 0-.979.268-.27.701-.27.969 0l7.83 7.908c.268.271.268.709 0 .979l-7.83 7.908c-.268.271-.701.27-.969 0-.268-.269-.268-.707 0-.979L13.25 10z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="large-arrow-down">
      <path d="M17.418 6.109c.272-.268.709-.268.979 0s.271.701 0 .969l-7.908 7.83c-.27.268-.707.268-.979 0l-7.908-7.83c-.27-.268-.27-.701 0-.969.271-.268.709-.268.979 0L10 13.25l7.418-7.141z"/>
    </symbol>


    <symbol viewBox="0 0 24 24" id="jump-to">
      <path d="M19 7v4H5.83l3.58-3.59L8 6l-6 6 6 6 1.41-1.41L5.83 13H21V7z"/>
    </symbol>

    <symbol viewBox="0 0 24 24" id="expand">
      <path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z"/>
    </symbol>

  </defs>
</svg>

<div id="swagger-ui"></div>

<script src="swagger-ui-bundle.js"> </script>
<script src="swagger-ui-standalone-preset.js"> </script>
<script>

window.onload = function() {

  // Build a system
  const ui = SwaggerUIBundle({
    url: "api-docs.json",
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })


  window.ui = ui
}
</script>
</body>

</html>

and this is code of my api-docs.json

{

  "swagger":"2.0",
  "info":{
    "version":"1.0.0",
    "title":"mindspree api doc",
    "description":"Sample spec for Swagger",
    "termsOfService":"http://swagger.io/terms/"
  },
  "basePath":"/",
  "tags":[
    {
      "name":"Home",
      "description":"API for something"
    }
  ],
  "schemes":[
    "http"
  ],
  "consumes":[
    "application/json"
  ],
  "produces":[
    "application/json"
  ],
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "paths": {
      "/": {
        "get": {
          "tags": ["info"],
          "description": "Get information about the Github API",
          "responses": {
            "200": {
              "description": "successfully got info",
              "schema": {
                "type": "object",
                "properties": {
                  "current_user_url": {
                    "type": "string"
                  },
                  "authorizations_url": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
    "/user": {
      "put": {
        "tags": [
          "/User"
        ],
        "description": "This route will take to userUpdate function of userController which will update a user and returns updated user withfull details.Roles allowed for this route :(2,student), (3, tutor)",
        "operationId": "getUser",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "User Parameters",
            "in": "body",
            "description": "Update the user into the database",
            "required": true,
            "schema": {
              "$ref": "#/definitions/updateUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "create response",
            "schema": {
              "$ref": "#/definitions/responseUpdateUser"
            }
          }
        }
      }
    }
  },
  "definitions": {
  "updateUser": {
    "properties": {
      "firstname": {
        "required": true,
        "type": "string",
        "example": "vikash"
      },
      "middlename": {
        "required": true,
        "type": "string",
        "example": "Shankar"
      }
    }
  },
  "responseUpdateUser":{
    "properties":{
      "account":{
        "required":true,
        "type":"schema"
      }
    }
  }
}
  }
![screenshot from 2017-04-20 18 29 15](https://cloud.githubusercontent.com/assets/25119254/25232124/f9b1c9fc-25f7-11e7-9069-937b8914d6e2.png)
![screenshot from 2017-04-20 18 29 38](https://cloud.githubusercontent.com/assets/25119254/25232129/fef0a320-25f7-11e7-838d-194a75a1692d.png)
![screenshot from 2017-04-20 18 34 48](https://cloud.githubusercontent.com/assets/25119254/25232169/12cc1f50-25f8-11e7-89f1-4888ed918627.png)

**Comment by kamleshpaliwal-tudip** [comment]
i m hitting /user api

**Comment by webron** [comment]
Thanks, that does help, but I still need to know the version of swagger-ui that you use.

**Comment by kamleshpaliwal-tudip** [comment]
It is "swagger":"2.0"

**Comment by kamleshpaliwal-tudip** [comment]
i think this is the swagger-ui if it is not the swagger ui version. then please tell me how to check it.

**Comment by webron** [comment]
How did you install the UI?

**Comment by kamleshpaliwal-tudip** [comment]
i took just clone as per some readme.md file I am attaching the link of article also.
this is the link here..https://github.com/shawngong/Swagger-Node-Express-For-Existing-APIs/blob/master/README.md

**Comment by webron** [comment]
Did you follow the instructions here - https://github.com/shawngong/Swagger-Node-Express-For-Existing-APIs/blob/master/README.md#cloning-swagger-ui?

**Comment by kamleshpaliwal-tudip** [comment]
yes i followed all the instructions.
 it is hitting my url also. I can send you the screenshot of my server console also.
![screenshot from 2017-04-20 19 24 28](https://cloud.githubusercontent.com/assets/25119254/25234337/6571e2e2-25ff-11e7-9ea6-f3f20ad90b7b.png)

i took the clone and deleted all files except dist folder in that and moved dist folder to root of my project .

**Comment by webron** [comment]
Great, thanks. One last question - when did you clone the swagger-ui repo? did you update it since?

**Comment by kamleshpaliwal-tudip** [comment]
Just today i cloned it .

**Comment by webron** [comment]
@kamleshpaliwal-tudip Thanks for all the details.

I apologize, because I didn't notice it at first. It looks like something is missing from your spec. You have `securityDefinitions` that define the available securities, but you don't apply it to any of the operations using the `security` property. 

You can find out more information about it in - http://swagger.io/docs/specification/authentication/.

**Comment by kamleshpaliwal-tudip** [comment]
thanks for helping . but one last question how i have to put security 
I am putting like this  "/user": {
      "put": {
        "security":
         - Bearer: [],
        "tags": [
          "/User"
        ],
I dont know yaml please can you help me.

**Comment by kamleshpaliwal-tudip** [comment]
it is showing error in json .
i want this in json.

**Comment by webron** [comment]
YAML and JSON are very similar and can be easily converted. Lots of online tools such as https://www.json2yaml.com.

The `security` would translate to:

```json
 "security": [
    {
      "Bearer": []
    }
  ]
```

**Comment by kamleshpaliwal-tudip** [comment]
Thank you very much sir. Really you made my day. Thanks a lot.

**Comment by webron** [comment]
Did it work? Is the issue resolved?

**Comment by kamleshpaliwal-tudip** [comment]
yes sir,it worked.

**Comment by webron** [comment]
Great, happy to hear! Will close the ticket now, but please reopen if needed.

**Comment by kamleshpaliwal-tudip** [comment]
ok sir.

**Comment by AyaMagdyMohamed** [comment]
@webron  is there a way to make the  authorization generic for all operations so don't have to pass "security":
- Bearer: [], to all operations ?
