### ISSUE TITLE
Regex issue in docker-run.sh for VALIDATOR_URL

### ISSUE THREAD

**Issue by redsux** [swagger-api/swagger-ui#2936]
Hello,

I just tried to set VALIDATOR_URL when running your container and it appears that docker-run.sh don't match your regex line 42 `sed -i "s|\(url: url,.*\)`.

There is a useless "url" string, a little fix : `sed -i "s|\(url: .*,\)`

Rergards,
Red

**Comment by fehguy** [comment]
@redsux please send a pr and we'll get it merged

**Comment by redsux** [comment]
@fehguy : Done, pr #2950
