### ISSUE TITLE
Missing dependencies (yarn incompatible)

### ISSUE THREAD

**Issue by andrewcharnley** [swagger-api/swagger-ui#2937]
base64-js

...modules/swagger-ui/dist/swagger-ui.js:1:311

Not within the package.json

**Comment by shockey** [comment]
@andrewcharnley can you elaborate? `yarn install` works for me with `v0.22.0`.

Are you trying to install UI's dependencies, or use UI as a module in another project? Please provide some logs as well, if possible.

**Comment by andrewcharnley** [comment]
I had to add ieee754 and base-64 to the dependencies list otherwise swagger-tools or ui wouldn't launch (I'm sure it was ui though I assume tools serves that out so it shouldn't be ui). Away from console right now but here's the deps;

I'm using lerna configured to use yarn (2.00, 0.23). Only swagger-ui (or tools!) has these dependencies missing.

```  "dependencies": {
    "base64-js": "^1.2.0",
    "express": "^4.15.2",
    "ieee754": "^1.1.8",
    "swagger-tools": "^0.10.1",
    "swagger-ui": "^3.0.5",
    "tcomb": "^3.2.20"
  },
  "devDependencies": {
    "nodemon": "1.11.0",
    "in-publish": "^2.0.0",
    "documentation": "^4.0.0-beta.19",
    "babel-plugin-tcomb": "^0.3.24",
    "babel-cli": "^6.23.0",
    "babel-core": "^6.23.1",
    "babel-istanbul": "^0.12.2",
    "babel-plugin-syntax-flow": "^6.18.0",
    "babel-plugin-transform-builtin-extend": "^1.1.2",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-preset-env": "^1.1.10",
    "mocha": "^3.2.0"
  },
```

**Comment by andrewcharnley** [comment]
Back at console. -rf node_modules and did a fresh install. Will try 3.0.6 to see if that fixes it...

```@sage/process-rtx-legacy: Process 822 (rtx-legacy) ready.
@sage/process-rtx-api: { Error: Cannot find module 'base64-js'
@sage/process-rtx-api:     at Function.Module._resolveFilename (module.js:469:15)
@sage/process-rtx-api:     at Function.Module._load (module.js:417:25)
@sage/process-rtx-api:     at Module.require (module.js:497:17)
@sage/process-rtx-api:     at require (internal/module.js:20:19)
@sage/process-rtx-api:     at r.(anonymous function).exports (/home/osboxes/git/lerna-repo/packages/process-rtx-api/node_modules/swagger-ui/dist/swagger-ui.js:1:311)
@sage/process-rtx-api:     at Object.<anonymous> (/home/osboxes/git/lerna-repo/packages/process-rtx-api/node_modules/swagger-ui/dist/swagger-ui.js:1:2284)
@sage/process-rtx-api:     at Module._compile (module.js:570:32)
@sage/process-rtx-api:     at Object.Module._extensions..js (module.js:579:10)
@sage/process-rtx-api:     at Module.load (module.js:487:32)
@sage/process-rtx-api:     at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by andrewcharnley** [comment]
Same in 3.0.6.

Adding it to your dependencies list fixes it.

I can see require("base64-js"), require("ieee754"). My guess is your bundling them in dist.js and they're not being required in properly. I'm unsure how this works but I don't see why swagger-ui is being loaded within node. Here's the loader:

```
  // initialize the Swagger middleware
  swaggerTools.initializeMiddleware(swaggerDef, (middleware) => {

    // interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
    app.use(middleware.swaggerMetadata());

    // validate Swagger requests
    app.use(middleware.swaggerValidator({ validateResponse: true }));

    // route validated requests to appropriate controller
    app.use(middleware.swaggerRouter({
      controllers:configJSFilesSync([__dirname, 'routes'], ...args)
    }));

    // serve interface (/docs, /api-docs)
    app.use(middleware.swaggerUi());

    // handle errors
    app.use((err, req, res, next) => {
```

**Comment by hughevans** [comment]
Would be great to officially switch to yarn and remove the references to npm in package.json.

**Comment by shockey** [comment]
@hughevans Agree - that's a problem for someone who doesn't have npm.

I'd be jazzed to see a PR that replaces our npm scripts with a Makefile 😄

**Comment by shockey** [comment]
Looks like Webpack is adding these modules to the build automatically, and our `externals` settings for the core files are interfering with it pulling in the module content.

I'm adding exceptions for these two modules to that logic.

**Comment by shockey** [comment]
Should be fixed in master - please reply here if this continues to be an issue 😄

**Comment by dee-lewis** [comment]
Hello, I'm getting an issue with this commit.

webpack-dist.config.js:27
    let exceptionsForWebpack = ["ieee754", "base64-js"]
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by shockey** [comment]
Ah, you must be on an older Node. I'll change it to var - one sec

**Comment by shockey** [comment]
@dee-lewis, can you give it a try now?

**Comment by dee-lewis** [comment]
it works

**Comment by dee-lewis** [comment]
also updating my node version from 5.3 to 7.9 let works now

**Comment by andrewcharnley** [comment]
Thanks. I can see it's fixed on master, is it possible to tag with a minor/patch release flag instead of just 3.x?

Regards, Andrew

**Comment by webron** [comment]
@andrewcharnley we try to make official releases every Friday.
