### ISSUE TITLE
No Content and No Response from server

### ISSUE THREAD

**Issue by dl14** [swagger-api/swagger-ui#2945]
I am new to swagger and I generated the Echo example python-flask server. When I run the server, and I access the online UI, I see GET requests on the server but then when I am on the UI and I run any of the operations I get the following:

Response Body:
No Content
Response Code:
0
Response Headers:
{
   "error": "no response from server"
}

I tried different examples and this happened on all of them. I am running this on a Mac with Python 3.6 installed. Any suggestions on how to fix this?

**Comment by webron** [comment]
Which version of swagger-ui do you use? What does your spec description look like?

**Comment by dl14** [comment]
I haven't installed Swagger UI - do I need too? I have been using the link provided in the readme 
http://localhost:8080/v2/ui/
To access the UI on my browser. On the bottom of the site it says API Version: 1.0.0, how do I find the spec description?

**Comment by webron** [comment]
ok, so you're getting the UI from whichever integration you use for swagger, not sure which one it is. can you share a screenshot of the UI?

**Comment by dl14** [comment]
<img width="1071" alt="screen shot 2017-04-21 at 9 09 05 am" src="https://cloud.githubusercontent.com/assets/24581854/25278719/40a3081a-2672-11e7-9467-39f7f2e0686e.png">

**Comment by webron** [comment]
Somewhat confused by what's going on. It looks like the spec that's being loaded is the one we host publicly as the pet store sample. I don't know why it would do that.

It looks like you're going to have to file a ticket with whichever library produces that.

**Comment by dl14** [comment]
Shouldn't it be? I generated the server from the pet store full example on online swagger editor. Before I try to make my own I wanted to understand an example.

**Comment by webron** [comment]
Okay, having that detail in the first place would have helped.

I don't know why the example isn't working. It could be something in the definition is a bit off, could be that it's an old version of the UI with a bug. You can try using the latest UI first to see if it solves the issue.

**Comment by dl14** [comment]
Whoops I thought I mentioned it in my first post but I guess not, sorry about that. 

How do I update the online generates UI? Or should I download it to get the latest one?

**Comment by webron** [comment]
Yeah, just clone this repo and run it locally. Use the same URL you see in the screenshot to load the spec into the new UI.

**Comment by dl14** [comment]
I cloned the repo, and ran dist/index.html on my browser. Then I put http://localhost:8080/v2/ui/swagger.json on the explore box and it says Failed to load spec. Any steps I'm missing in here?

I was following the Download and Usage tab on this [link](http://swagger.io/docs/swagger-tools/#swagger-ui-documentation-29) but do I need to do anything after downloading the ui from git?

**Comment by webron** [comment]
Yeah, my bad. It would fail due to CORS. I don't know anything about flask. If you know where the current UI is hosted from in the code, you can simply drop in the new UI in it and run the project again.

**Comment by dl14** [comment]
Hmm I'm not sure how to make those changes either.. Is there anyway to update the online ui?

I'm thinking it has to be a version issue because the server is getting GET requests (I see them on the terminal) when I access the online UI but after that it doesn't receive any requests.

**Comment by webron** [comment]
That UI is loaded from the generated app, not online. I really don't know how to update that.

**Comment by dl14** [comment]
Ah okay I see.. So if I generate my own server with basic get and post requests would the version be updated?

**Comment by webron** [comment]
If you use the codegen? no. I looks like it wasn't updated with the new UI yet.

**Comment by dl14** [comment]
Could it be because when I visit the online [editor](http://editor.swagger.io/#/) I have to click on "Switch Back to previous editor" in order to be able to download the server? So maybe the previous editor is outdated?

**Comment by webron** [comment]
No, it has nothing to do with that. The codegen is handled separately.

**Comment by dl14** [comment]
Okay.. so any suggestions on where to go from here?

**Comment by dl14** [comment]
I got an example working and I started making my own "library" server that stores books. For some reason, my response body always shows "do some magic!" Which is the default in the minimal example. Anything I'm doing wrong?

<img width="345" alt="screen shot 2017-04-22 at 7 15 40 pm" src="https://cloud.githubusercontent.com/assets/24581854/25309041/22a32132-2790-11e7-9caf-4c8db49e7086.png">

**Comment by webron** [comment]
I don't understand. It shows it where?

**Comment by dl14** [comment]
The response body for a post or a get is as shown in the image (the one in the image is specifically for a post that I made). However, for the get I know I set the response to be the array of books that get have the specified string as the title so I'm wondering why I only see "do some magic!" as the response body text in the swagger UI.

<img width="960" alt="screen shot 2017-04-22 at 9 24 08 pm" src="https://cloud.githubusercontent.com/assets/24581854/25309707/10d8a3c0-27a2-11e7-8222-b90056324edf.png">

**Comment by webron** [comment]
That's what's returned from the generated code. You'd need to investigate that.

**Comment by dl14** [comment]
Isn't the generated code dependent on the responses that I'm setting in the .yaml file on the editor?

**Comment by webron** [comment]
It should be, but it's based on the template you chose. Suggest you check the code.

**Comment by mustafadefcon** [comment]
Reason for this issue is CORS enabled on browser.
If the API end point is not handling the OPTION method, it will return zero response.
Disable the browser CORS, it will work after that.
For me it work.
