### ISSUE TITLE
Exclude

### ISSUE THREAD

**Issue by alexandermikuta** [swagger-api/swagger-ui#2951]
In the former version of swagger ui properties that were used for swagger-codegen (e.g. x-scalaType) were not displayed in the model-section of the swagger-ui-gui.

`  "properties": {
        "sessionToken": {
          "type": "string",
          "description": "The super administrator authorization token.",
          "x-scalaType": "api.login.AccessToken"
        }`

Is it somehow possible to hide this property in the models-view or this a missing feature/bug?

**Comment by webron** [comment]
It's neither. If you want to hide it, you could write a plugin that filters those out.
