### ISSUE TITLE
Spring Boot [ApiListingReferenceScanner] freezes when deploying to tomcat

### ISSUE THREAD

**Issue by Shadi355** [swagger-api/swagger-ui#2954]
when i am trying to deploy Spring boot app with swagger the deployment freezes on the below line 

2017-04-21 19:10:07.731  INFO 3484 --- [ost-startStop-3] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references

spring boot version : 1.4.1.RELEASE
swagger2 version : 2.6.1

**Comment by webron** [comment]
Please open the ticket on springfox.

**Comment by hc24** [comment]
"Please open the ticket on springfox."?what?

**Comment by shockey** [comment]
@hc24, based on the error message the original filer provided, it's clear that this is not a Swagger-UI issue.
