### ISSUE TITLE
Using SwaggerClient with resources with response code 302 

### ISSUE THREAD

**Issue by chamilaadhi** [swagger-api/swagger-ui#2961]
Hi ,
I'm using SwaggerClient (v 2.2.10). I'm calling a resource which returns HTTP status code 302 with a locaiton header. SwaggerClient does the redirection to the location header once it gets the response and my requirement is to only get the 302 response and not do the redirection request (I want to do the redirection from my code )

Is there any possibility to get the response (with 302 status code) and stop doing the redirection throught this client 

Thanks 

following is a sample code i use in my app to call the api

 
    var swaggerClient = new SwaggerClient({
         url: swaggerURL,
         success: function(swaggerData) {

             var application = {};

             swaggerClient["Application (individual)"].post_applications({
                     "body": application,
                     "Content-Type": "application/json"
                 },
                 function(data) {},
                 function(error) {}
             );
         }
     });

**Comment by webron** [comment]
Please open the ticket on [swagger-js](https://github.com/swagger-api/swagger-js).
