### ISSUE TITLE
Not-specified scheme should be derived from URL of the definition file

### ISSUE THREAD

**Issue by samekmichal** [swagger-api/swagger-ui#2962]
From Swagger specs:
> schemes: The transfer protocol of the API. Values MUST be from the list: "http", "https", "ws", "wss". If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself.

However, after loading a definition file hosted on `https://localhost:8443/api/spec.yaml` which does not define `schemes` property, the Swagger UI is generating requests using http scheme - instead of https.

**Comment by webron** [comment]
This should be fixed in the latest release - make sure to use that. Please reopen if still an issue.

**Comment by samekmichal** [comment]
Isn't http://editor.swagger.io running the latest release?

**Comment by webron** [comment]
Normally, unless we forget to update it ;)
