### ISSUE TITLE
NonBodyParameter Pattern Property Working?

### ISSUE THREAD

**Issue by chassq** [swagger-api/swagger-ui#2963]
Hey,

I added a Doc filter as follows:

    public class VersionQueryParamDocumentFilter : IDocumentFilter
    {
        /// <summary>
        /// Applies query param to parameters collection. Also adds a tag.
        /// </summary>
        /// <param name="swaggerDoc"></param>
        /// <param name="context"></param>
        public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
        {
            swaggerDoc.Tags = new[] {
                new Tag { Name = "version", Description = swaggerDoc.Info.Version }
            };

            foreach(var path in swaggerDoc.Paths)
            {
                path.Value.Parameters = new List<IParameter>();
                path.Value.Parameters.Add(new NonBodyParameter { Default=swaggerDoc.Info.Version, Name="api-version", Type="string", Required=true, In="query", Description="Do not change value!", Pattern=$"^{swaggerDoc.Info.Version}$" });
            }
        }

It simply adds a query string param for api-version value (using Microsoft.AspNetCore.Mvc.Versioning). Adding the param works fine for me but I want to make sure the user cannot change the param value. Was trying to use pattern to limit the value input to a specific value but it does not see to stop the page post. Any ides on how to make this happen?

Any help appreciated!

Thanks!

**Comment by webron** [comment]
If the parameter has a fixed value, try setting it to an enum value of it (or not setting it as a parameter at all).
