### ISSUE TITLE
hide the Response Model Schema completely in swagger-ui

### ISSUE THREAD

**Issue by bullsEye173** [swagger-api/swagger-ui#2964]
I'm using the latest model of swagger 2 and I want to know how to hide the Response Model Schema completely.

Can someone please help me with that??

Thanks,
Dheeraj

**Comment by webron** [comment]
You either need to remove it from the spec, or modify the code to do that. There's no configuration option to remove it.

**Comment by bullsEye173** [comment]
Thanks for the prompt response.

Do you have a sample code or example to either remove it from the spec??

-- Dheeraj

**Comment by webron** [comment]
I do not, and afraid we don't have the capacity to provide guidancefor such changes. You'd have to dive into the code yourself.
