### ISSUE TITLE
How to name Array which I am getting in response?

### ISSUE THREAD

**Issue by kamleshpaliwal-tudip** [swagger-api/swagger-ui#2965]
I have Implemnted swagger for my API documnetion.In there from one of the API I am getting response like this...
{
  "updated_job": [
    {
      "job_id": 2,
      "tutor_id": 1,
      "is_accepted": true,
      "createdAt": "2017-04-24T10:29:22.000Z",
      "updatedAt": "2017-04-25T02:17:31.000Z",
      "id": 10
    }
  ]
}
and in swagger response I can see like this...
[
  {
    "job_id": 2,
    "tutor_id": 1,
    "is_accepted": true,
    "createdAt": "2017-03-21T05:56:37.000Z",
    "updatedAt": "2017-04-21T05:19:20.000Z",
    "id": 10
  }
]

my code is:
"responses": {
        "200": {
          "description": "Updated job Application",
          "schema": {
            "type": "array",
            "items": {
              "$ref": "../definitions/jobApplication.json#/jobApplicationSchema"
            }
          }
        }
}
 

I want updated job: also in response model same as response getting from my API.
please help me..

**Comment by webron** [comment]
For general support questions, please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).
