### ISSUE TITLE
Reusable object properties?

### ISSUE THREAD

**Issue by pqzxc** [swagger-api/swagger-ui#2969]
Hi everyone,

I think Swagger UI is a great tool - thanks for making it! 

I particularly like the fact that you can reuse definitions, parameters and responses to make the YAML code more modular and was wondering if there's any way to do the same for object properties? Some of my object properties are the same as parameters I've defined elsewhere and it would great if I could use a single reference for both.

Is there any way of doing something like this?

```
paths:
  /pet:
    get:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      produces:
      - application/json
      parameters:
      - $ref: "#/parameters/id"
      responses: 
        405:
          description: "Invalid input"
        200:
          schema:
            title: Pet
            type: object
            required: [id, name]
            properties:
              $ref: "#/parameters/id" # Doesn't work :( 
              name:
                type: string
                description: The new pet's name.

parameters:
  id:
    name: id
    in: path
    type: integer
    required: true
    description: The ID.
```

**Comment by webron** [comment]
You can't reference groups of properties, but you can reference individual properties.

**Comment by pqzxc** [comment]
Is there any chance that you could show me a simple example? I couldn't see any examples online (including in the specification).

It would be massively appreciated!

**Comment by webron** [comment]
```yaml
paths:
  /pet:
    get:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      produces:
      - application/json
      parameters:
      - $ref: "#/parameters/id"
      responses: 
        405:
          description: "Invalid input"
        200:
          schema:
            title: Pet
            type: object
            required: [id, name]
            properties:
              id:
                $ref: "#/definitions/id" 
              name:
                type: string
                description: The new pet's name.

definitions:
  id:
    type: integer
    description: The ID.
```

**Comment by pqzxc** [comment]
Thanks for your reply, @webron - I'm very grateful for your help with this.

So, just to confirm: reusable properties must be stated in /definitions and there's no way of having a properties module (/properties) that is separate from definitions?

A further question: I can extend parameter references (i.e. add extra information not included in the reference) but can't do this with property references - why is this? I've provided an example below. 

I've looked online and in the specification but unfortunately can't see anything about this issue.

```
paths:
  /pet:
    get:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      produces:
      - application/json
      parameters:
      - $ref: "#/parameters/id"
        description: The ID. #Works in my project (although not in http://editor.swagger.io/#)
      responses: 
        405:
          description: "Invalid input"
        200:
          schema:
            title: Pet
            type: object
            required: [id, name]
            properties:
              id:
                $ref: "#/definitions/id"
                description: The ID. #Doesn't work
              name:
                type: string
                description: The new pet's name.
                
definitions:
  id:
    type: integer
    
parameters:
  id:
    name: id
    in: query
    type: integer
```

**Comment by webron** [comment]
You can't add extra properties next to $ref's anywhere, regardless of the location of the reference.

**Comment by pqzxc** [comment]
I just double checked to make sure I'm not hallucinating and I can assure you that this bit of code definitely works in my project:

```
parameters:
  - $ref: "#/parameters/id"
    description: The ID. #Works in my project (although not in http://editor.swagger.io/#)
```
with the reusable id parameter defined like this:
```
id:
  name: id
  in: query
  type: integer
```
Perhaps this is an unexpected hack?

If it isn't supposed to work next to a $ref parameter then it's not surprising that it doesn't work next to a $ref property. Thanks for confirming that this isn't supposed to work!

**Comment by webron** [comment]
There's a difference between parameters and properties. In your original example you were actually referencing a property, not a parameter.

The spec does support referencing parameters as well, but the `description` you attach in the example above will be ignored.

**Comment by pqzxc** [comment]
You're absolutely right about my original example and you've been very helpful in clarifying the difference between parameters and properties - thanks again for your help.

However, I can assure you that my example above works in Swagger UI 2.2.8 and `description` doesn't get ignored. In fact, I've been making extensive use of this feature throughout my project because it's very useful to be able to reuse a parameter and customise the description.

**Comment by webron** [comment]
It doesn't get ignored in 2.2.8 because it's a bug there, not because it's a bug in 3.x :) I'm afraid the spec doesn't support that (the 3.0.0 spec that's coming out soon makes that clearer, but it doesn't change the behavior).

**Comment by pqzxc** [comment]
It should be a feature, not a bug! It's so useful! :smile:

**Comment by webron** [comment]
That would suggest it can be done, but it can't. It introduces too many complexities that we can't deal with. It might change in the future in the spec, but until then, don't expect it to work in the UI.

**Comment by pqzxc** [comment]
OK, thanks for the advice!

**Comment by thales-gaddini** [comment]
Hi webron,

In your example, "id" will appear in the Models. Is there a way to prevent that? Or some other way to make a reusable "object" that is not exposed in the UI?

Thanks!

**Comment by webron** [comment]
Not OOTB. At some point we plan on introducing a way to hide all models, but not some. You can always write your own plugin to support any behavior you want.
