### ISSUE TITLE
own css for swagger

### ISSUE THREAD

**Issue by twawszczak** [swagger-api/swagger-ui#2970]
It is not a issue, just a question - is there an easy and elegant way to implement custom css for swagger - ui? Currently, swagger css is injected by JavaScript with whole "layout". To override it i have to use "important" or place my css after head section. Is it there better way?

**Comment by Minasokoni** [comment]
@twawszczak Currently we are not using  the webpack `extract-text-webpack-plugin`, so all css is injected into the DOM. With the extract text plugin it will make an actual css file and link to an external stylesheet. I will be making this update soon.

**Comment by shockey** [comment]
Closing b/c no replies. @twawszczak, please reply if you have any lingering questions 😄
