### ISSUE TITLE
Swagger UI is confused between Route Key and Model Binder's Property when they are same .. any workaround.

### ISSUE THREAD

**Issue by nmathur** [swagger-api/swagger-ui#2971]
Hi there,

This is not an issue, this is a question for help.

I am developing a Web API in ASP.NET MCV using C#.  I have implemented Swagger UI for my API, but I am facing issue in particular situation and need suggestions. I have a model binder class "Order" and Route keys are "customerId", "orderId" (a GET request). 

Class is as followes:
```

public class Order 
{
 public int OrderId { get; set; }
 public int CustomerId { get; set; }
 public int ProductId { get; set; }
 public int OrderAmount { get; set; }
........etc
}

```

Now when I request and pass values ->
http://myapiurl/customer/{customerId}/order/{orderId}
Request e.g. -> **http://myapiurl/customer/41/order/984**

```
 [MyPermissionAttribute]
 [HttpGet]
//Order model binds using orderId 
 public IHttpActionResult GetOrder([ModelBinder(typeof(OrderModelBinder))] Order order)
{
    //return a combined model for customer and order
}

```

At the time of authentication -> MyPermissionAttribute --- IsAuthorized 

```
protected override bool IsAuthorized(HttpActionContext actionContext)
        {
       var orderId = actionContext.ControllerContext.RouteData.Values["orderId"];
      //orderid is returning "{OrderId}" instead of "984" -- Please note casing

       var customerId = actionContext.ControllerContext.RouteData.Values["customerId"];
 //orderid is returning "{CustomerId}" instead of "41" -- Please note casing

}
```

I know that it is possible that this is because of same name of route keys and model properties. I have to be like this. I cannot change them.

I tried to hide properties from Order class using DataContract and [JsonIgnore], but no luck. These type of solutions (DataConract and JsonIgnore) are risky because I may need order class as Json result in other APIs.

**This issue is occurring only in swagger ui. Tried get request from Postman plugin (Google Chrome) and it worked perfectly.**

Please share suggestions, how can I make swagger ui to take correct route key values.

**Comment by webron** [comment]
Would need to see your Swagger API definition in order to understand what's going on.

**Comment by nmathur** [comment]
Hi There,

Here I am sharing code from SwaggerConfig file - 

```
[assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]
public class SwaggerConfig
{
     public static void Register()
     {
          var thisAssembly = typeof(SwaggerConfig).Assembly;

          GlobalConfiguration.Configuration
                .EnableSwagger(c =>
                    {                        
                        c.SingleApiVersion("v1", "API Documentation");                      
                        c.IncludeXmlComments(GetXmlCommentsPath());
                        c.DocumentFilter<AuthTokenOperation>();                       
                    })
                .EnableSwaggerUi(c =>
                    {
                        c.InjectStylesheet(thisAssembly, "Content.swagger-style.css");
                        c.InjectJavaScript(thisAssembly, "Script.swagger-script.js");
                        c.InjectJavaScript(thisAssembly, "Script.basic-auth.js");
                        c.CustomAsset("swagger_test", thisAssembly, "swagger.html.swagger_test.html");
                        c.CustomAsset("api", thisAssembly, "swagger.html.other_version.html");
                    });
        }

        private static string GetXmlCommentsPath()
        {
            return String.Format(@"{0}\App_Data\MyApi.XML", System.AppDomain.CurrentDomain.BaseDirectory);
        }

        private static string GetAuthJsPath()
        {
            var value = String.Format(@"{0}.Script.api-key-header-auth.js", System.AppDomain.CurrentDomain.BaseDirectory);
            return value;
        }

        private static string GetRootUrlFromAppConfig()
        {
            return String.Format("{0}", "http://localhost");
        }
    }
```

**Comment by webron** [comment]
@nmathur Can't do much with the code. I'd need the JSON or YAML representing your API (generated by Swashbuckle).

**Comment by nmathur** [comment]
@webron Sorry, tried a lot, searched on web ... but due to less knowledge I am unable to generate swagger JSON or YAML. But here I am sharing something that may help you to guide me.

Curl for request is ->
curl -X GET --header 'Accept: application/json' 'http://localhost:49397/customer/{CustomerId}/order/{OrderId}?customerId=2&orderId=2'

Also attaching the screen-shot of API Doc.
![query](https://cloud.githubusercontent.com/assets/5699753/25522727/9687a90c-2c21-11e7-80e0-b0ad951cb7a7.png)

**Comment by webron** [comment]
@nmathur take a look at https://github.com/domaindrivendev/Swashbuckle#getting-started - you want the 'Swagger docs' url.

**Comment by nmathur** [comment]
Hello, thanks for rep;y .. find this:

{"swagger":"2.0","info":{"version":"v1","title":"SwaggerNM"},"host":"localhost:49397","schemes":["http"],"paths":{"/customer/{CustomerId}/order/{OrderId}":{"get":{"tags":["Customer"],"operationId":"Customer_Get","consumes":[],"produces":["application/json","text/json","application/xml","text/xml"],"parameters":[{"name":"customerId","in":"query","required":true,"type":"string"},{"name":"orderId","in":"query","required":true,"type":"string"}],"responses":{"200":{"description":"OK","schema":{"type":"object"}}}}},"/api/Customer":{"get":{"tags":["Customer"],"operationId":"Customer_Get","consumes":[],"produces":["application/json","text/json","application/xml","text/xml"],"responses":{"200":{"description":"OK","schema":{"type":"object"}}}}}},"definitions":{"Order":{"type":"object","properties":{}}}}

**Comment by nmathur** [comment]
Any suggestion?

**Comment by webron** [comment]
That spec doesn't describe models at all. It only marks them as `object`.

**Comment by nmathur** [comment]
I was facing issues because of ModelBinder .. my parameter name and ModelBinder's parameter name was same .. I changes the naming of property in model binder and now it is working fine.
