### ISSUE TITLE
Hide top errors?

### ISSUE THREAD

**Issue by juanjoLenero** [swagger-api/swagger-ui#2973]
Our swagger.json is lightly modified to display extra information from our api, this results in errors that are shown on top of the screen, but the api below is displayed fine. We would like to hide these errors, as they distract the developers that consume our documentation.

I've tried to set `validatorUrl` to `false/null/undefined` but that doesn't work.

![image](https://cloud.githubusercontent.com/assets/2656008/25397947/ca18b71c-29af-11e7-8d44-ca751d2edcfd.png)
Swagger-UI V3.0.7

**Comment by webron** [comment]
Those are not validator errors. Which version of swagger-ui do you use?

**Comment by juanjoLenero** [comment]
@webron I'm using the dist folder in V3.0.7

**Comment by webron** [comment]
Interesting. Can you share your spec?

**Comment by juanjoLenero** [comment]
Swagger editor is a little more detailed with the errors.

I'm sure the spec is far from perfect, it's autogenerated from an [npm package].(https://github.com/glennjones/hapi-swagger)
![image](https://cloud.githubusercontent.com/assets/2656008/25399010/99817dc4-29b3-11e7-9df8-a7ba753a1fce.png)

@webron sure, but I would rather not post it publicly, can I mail it to you?

**Comment by webron** [comment]
Absolutely. Email in profile.

**Comment by inad9300** [comment]
Any progress on this front? I get an even weirder error saying "undefined http://petstore.swagger.io/v2/swagger.json", when in fact I'm passing the `url` parameter to the `SwaggerUIBundle` function and am able to see all the documentation properly. I'm using the latest version -- 3.1.6.

![swagger-pet-errors](https://user-images.githubusercontent.com/3440331/29664437-dd38281c-88cf-11e7-9205-bbd15ee92ea9.png)

**Comment by shockey** [comment]
I've recently shared a way to hide errors in Swagger-UI: https://github.com/swagger-api/swagger-ui/issues/3366#issuecomment-363258562

Closing, as this is inactive! Feel free to reply if there's anything else.
