### ISSUE TITLE
CORS and Basic Authenticion Error

### ISSUE THREAD

**Issue by bimalyn-IBM** [swagger-api/swagger-ui#2975]
When making a request from `https://hostname/swagger-ui.new/dist/#!/tag1` I receive the following error in the console:

```
Loading mixed (insecure) active content "http://hostname/pkg/tag1" on a secure page
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hostname/pkg/tag1. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

A few questions:

1. Why is it making a request over http for the first request?
2. Why is there a CORS error if the hostname and port match?
3. Why aren't the basic authentication headers being set?

This behaviour arose after `v2.2.10`.

Here is a reduced version of my `swagger.yaml`:

```yaml
---
swagger: "2.0"
info:
  version: "1.5.9"
host: "hostname"
basePath: "/pkg"
tags:
- name: "tag1"
- name: "tag2"
- name: "tag3"
schemes:
- "https"
paths:
  ...
securityDefinitions:
  basic:
    type: "basic"
definitions:
  ...
securityRequirement:
- basic: []
```

**Comment by webron** [comment]
Which version of swagger-ui did you try it with?

**Comment by bimalyn-IBM** [comment]
I tested it with `v3.0.3` - `v3.0.7`, and they all behaved in the same manner.

**Comment by webron** [comment]
It would be difficult to test this without a proper setup. Can you create a sample app we can run to take a look at it?

**Comment by bimalyn-IBM** [comment]
Here is a very simple app that I just though together: [https://github.com/bimalyn-IBM/swagger-test-app-v3-cors-auth](https://github.com/bimalyn-IBM/swagger-test-app-v3-cors-auth).

I am running everything though that included nginx config file.
Again it works in `2.x`, but not in `3.0.7`

**Comment by bimalyn-IBM** [comment]
I just added the CORS part to my nginx config today when I started to use `3.0.7`

**Comment by bimalyn-IBM** [comment]
You'll also need to change the host on line 13 of `server.js`

**Comment by webron** [comment]
Thanks for the sample, but I'm not really sure how to run that to reproduce the issue. Can you provide more details?

**Comment by bimalyn-IBM** [comment]
Sure.

Install node, and then run `npm install` in the folder of code I wrote, and then run `node server.js`

At this point you should be able to access the endpoints `/pkg/static` and `/pkg/swagger.json` on `http://localhost:3000` (ie `http://localhost:3000/pkg/static`)

Install nginx, and either add that nginx conf inside of your main config or add it to the `conf.d` folder inside of the nginx directory. Depending on what distro you are running you may or may not have the `conf.d` folder.

You can create a simple `ssl.conf` file:

```
ssl_certificate cert.pem;
ssl_certificate_key key.pem;
```

and create a cert key pair:
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes
```

You can either copy the swagger files into the `html` folder or simlink them with something like this:

```
ln -s swagger-ui/dist html
```

restart nginx

Now you should be able to open `https://localhost` (and see the swagger interface), `https://localhost/pkg/static`, and `https://localhost//pkg/swagger.json`.

**Comment by bimalyn-IBM** [comment]
So you should have
```
/etc/nginx
├── conf.d
│   └── https.conf
├── html -> swagger-ui/dist/
├── nginx.conf
├── ssl.conf
├── swagger-test-app-v3-cors-auth
│   ├── nginx.conf
│   ├── package.json
│   ├── route.js
│   └── server.js
├── swagger-ui
│   ├── dist
│   │   └── ...
│   └── ...
├── cert.pem
└── key.pem
```

**Comment by webron** [comment]
It took a long time to set up, but I'm not seeing the issue you mention.

**Comment by bimalyn-IBM** [comment]
So you are able to preform the `GET`, both while authenticated and not, to get the the `You passed` message and the error message respectively? On `v3.0.7`?

**Comment by webron** [comment]
@bimalyn-IBM sorry, this somehow slipped between the emails. Do you still experience the issue?

**Comment by bimalyn-IBM** [comment]
Yes, I am still experiencing the same issue.

I can `git checkout tags/v2.2.10` and everthing is fine and then I `git checkout tags/v3.0.10` and it stops working. I just get back a `TypeError: NetworkError when attempting to fetch resource.`

I noticed that in the curl command line that the for `3.0.10` the `--header 'Authorization: Basic XXX'` is omitted.

**Comment by webron** [comment]
Can you first retry with the latest version?

**Comment by bimalyn-IBM** [comment]
Sorry I misread the tags. So with version `3.0.17`, I get `😱 Could not render this component, see the console.`

Console:
```javascript
Loading mixed (insecure) active content "http://host/endpoint" on a secure page [Learn More]  swagger-ui-bundle.js:72:6935
TypeError: n.get(...) is undefined
Stack trace:
[object Object]  swagger-ui-bundle.js:45:16027
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://host/endpoint. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by bimalyn-IBM** [comment]
I tried again with version `3.1.4` I am still unable to request the page.

After authenticating, the authentication header is still missing.

![swagger 3 1 4](https://user-images.githubusercontent.com/26979538/29185267-5817204a-7dce-11e7-8a13-427d4b2610cc.jpg)

**Comment by shockey** [comment]
Closing; this is pretty stale.

@bimalyn-IBM, if this is still an issue, reply here and I'll get this back into our queue!
