### ISSUE TITLE
Write a small guide on including Swagger UI

### ISSUE THREAD

**Issue by nblackburn** [swagger-api/swagger-ui#2976]
I think it would be good to write a small guide to get started with the new Swagger UI.

It's not good practice to clone and edit the code directly as it would break every time you make updates so a guide on setting up a layout and registering it with swagger and webpack would be great in helping people to get started as it currently feels a little clunky to get there.

**Comment by webron** [comment]
Most of the basic information can now be found under the `docs` folder. We're happy to continue improving the guide as we get more input on what's missing (and of course, as we add/change features).
