### ISSUE TITLE
Swagger UI not loading

### ISSUE THREAD

**Issue by ronakcshah** [swagger-api/swagger-ui#298]
Sorry this may be a dumb question but what I am missing? I can view my apis array and when I go to http://localhost:9090/api-docs/parties/ I can view apioperations details and other information but the UI is not loading. I specified http//localhost:9090/api-docs  as my URL in index.html. 

![screen shot 2013-09-03 at 10 34 59 am](https://f.cloud.github.com/assets/5214360/1073435/c60053fa-14a6-11e3-85df-a184c33bfc5b.png)
![screen shot 2013-09-03 at 10 37 25 am](https://f.cloud.github.com/assets/5214360/1073436/c99519a6-14a6-11e3-9a3f-3cb766521abd.png)

**Comment by nileshkumar9** [comment]
What was the solution to this issue ? Even for me swagger-ui doesn't work in chrome but loads perfectly file on IE.

**Comment by ronakcshah** [comment]
This is a while ago, If i remember correctly, it was something to do with CORS.

**Comment by sagarika-hp** [comment]
can anyone provide the solution to this or any link that will forward me to the solution .m facing the same issue?

**Comment by heldersepu** [comment]
@sagarika-hp every case is different perhaps you can open a new issue providing details and the errors you are facing.

**Comment by Nazgaul** [comment]
I create a small asp.net core api to show you the issue.
this is the link https://github.com/Nazgaul/SwaggerIssue
the ui not working ( don't know why) but the json is working. 
the attach is the issue with hightlight on
![capture](https://user-images.githubusercontent.com/3366179/37023525-e3e5a8f4-212e-11e8-9848-6495ac51b3cb.PNG)

**Comment by ritika-shakwar** [comment]
I got the same issue.... created a swagger doc on 3.0 version...that time working ...now when I hit the end point ..it returns bad request.
