### ISSUE TITLE
pre-select default values for enum array?

### ISSUE THREAD

**Issue by AlJohri** [swagger-api/swagger-ui#2980]
Does the UI currently pre-select default values for an enum array? I can't tell if I'm specifying the spec wrong or if this is not supported by the UI.

UI looks like this:
![screen shot 2017-04-26 at 3 27 16 pm](https://cloud.githubusercontent.com/assets/2790092/25452802/da996a06-2a94-11e7-9058-5a8469d8d79c.png)

Note that the `sort` parameter has no preselected values while the `fields` parameter does.

Schema looks like this:
![screen shot 2017-04-26 at 3 27 00 pm](https://cloud.githubusercontent.com/assets/2790092/25452794/cfa13d0e-2a94-11e7-9879-7626a4fbb8fd.png)

The `sort` parameter is an array of enums while the `fields` parameter is an array of strings.

**Comment by webron** [comment]
I don't think the UI does that.
