### ISSUE TITLE
Swagger-ui issue with container class?

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-ui#2984]
Hi all,

Using the latest 3.0.7 version of swagger-ui. 

I'm trying to integrate it into our developer portal, which is built using angular 1.3 and bootstrap. When the doc ui loads it looks fine but the resource/paths section blows out to the right. If I go through dev-tools in chrome and remove the "container" class from the line `<section data-reactroot class="swagger-ui container">` it looks fine. If I don't, it extends way out to the right and doesn't give a horizontal scrollbar.

I'm assuming that this is because bootstrap doesn't like nested containers. We use a container for every page layout, and then adding in swagger-ui is adding another container. I'm not 100% sure this is the cause, and I'm really not sure how to get around it. 

Any suggestions?

**Comment by shockey** [comment]
We aren't using bootstrap on our end, so this just sounds like a CSS class collision.

@Minasokoni, can you advise on how difficult it would be to change our container class to something like `swagger-container`?

**Comment by Minasokoni** [comment]
@shockey Should be really quick let me make a PR.

**Comment by jaydreyer** [comment]
@Minasokoni's change worked perfectly. Thank you @shockey and @Minasokoni !
