### ISSUE TITLE
Not Including Host Field In Spec Does Not Assume Documentation Host

### ISSUE THREAD

**Issue by rgant** [swagger-api/swagger-ui#2988]
- swagger-ui version 3.0.5~7~
- a swagger file reproducing the issue: [swagger-without-host.json.zip](https://github.com/swagger-api/swagger-ui/files/962036/swagger-without-host.json.zip)
- The SwaggerUIBundle is setup like so:
```
window.onload = function() {
  // Build a system
  const ui = SwaggerUIBundle({
    url: window.location.origin + '/v3/swagger.json',
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
```

According to the spec if the `host` field isn't set then:
> If the host is not included, the host serving the documentation is to be used (including the port).

However it does not seem like that is being handle when you execute a Try it out:
<img width="1210" alt="screen shot 2017-04-27 at 11 13 06" src="https://cloud.githubusercontent.com/assets/710553/25490343/8b22b738-2b3a-11e7-8d82-0b448966b0e7.png">

Without the `host` field set the top of the UI looks like this:
<img width="688" alt="screen shot 2017-04-27 at 11 16 55" src="https://cloud.githubusercontent.com/assets/710553/25490515/1c16e7dc-2b3b-11e7-9063-257533d49c14.png">

And the curl looks like this:
<img width="654" alt="screen shot 2017-04-27 at 11 19 50" src="https://cloud.githubusercontent.com/assets/710553/25490652/769600ee-2b3b-11e7-8c2c-fd5d16daf755.png">

But when the `host` field is set in the swagger.json the execute works and the base url at the top changes: 
<img width="316" alt="screen shot 2017-04-27 at 11 24 42" src="https://cloud.githubusercontent.com/assets/710553/25490892/491a32c4-2b3c-11e7-845d-be81bd101e57.png">

**Comment by shockey** [comment]
@rgant, I'm not able to produce this with [v3.0.7](https://github.com/swagger-api/swagger-ui/releases/tag/v3.0.7) (using dist folder from commit b289d59, with your test spec served from https://acceptable-operation.surge.sh/swagger.json). Try-It-Out hits `https://acceptable-operation.surge.sh/v3/service-collections`, as I would expect.

![image](https://cloud.githubusercontent.com/assets/680248/25513552/b609edc2-2b8a-11e7-895e-c55b22266789.png)

Can you double-check that you're on the latest version?

**Comment by rgant** [comment]
Hmm, it seems I was 3.0.5 instead of 7. In 3.0.7 this issue is resolved.

It's hard to tell what versions you are on since the dist files don't include a version number. Sorry about that.

**Comment by shockey** [comment]
Thanks for the update @rgant. You raise a good point - I'll open a ticket to add a version ref to the project.
