### ISSUE TITLE
Swagger encodes multipart/form-data

### ISSUE THREAD

**Issue by Sidesplitter** [swagger-api/swagger-ui#2989]
Whenever parameters are sent throughout a form with multipart/form-data, Swagger-ui 3.0.7 will encode this form data. This causes some servers to not accept the request, since they do not expect encoded data.

Current behaviour:
```
------WebKitFormBoundaryfpVH8U4cUAWn1Hg1
Content-Disposition: form-data; name="file"; filename="test.zip"
Content-Type: application/zip


------WebKitFormBoundaryfpVH8U4cUAWn1Hg1
Content-Disposition: form-data; name="test"

test%20test
------WebKitFormBoundaryfpVH8U4cUAWn1Hg1--
```

Expected behaviour:
```
------WebKitFormBoundaryfpVH8U4cUAWn1Hg1
Content-Disposition: form-data; name="file"; filename="test.zip"
Content-Type: application/zip


------WebKitFormBoundaryfpVH8U4cUAWn1Hg1
Content-Disposition: form-data; name="test"

test test
------WebKitFormBoundaryfpVH8U4cUAWn1Hg1--
```
The corresponding swagger.yaml:
```yaml
paths:
  /test:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          required: true
          type: file
        - name: test
          in: formData
          required: true
          type: string
      responses:
        200:
          description: Test
```

I'm not sure whether this is expected behaviour or not, but I could not find anything on this issue. Thanks in advance!

**PS**: I'm not sure whether it is intended behaviour to only send data as multipart/form-data when there is a parameter with the file-type, but right now I could not get it to work without adding the file-parameter.

**Comment by hkosova** [comment]
@webron is this the same as #3101 which was closed recently?

**Comment by webron** [comment]
It is, thanks @hkosova!
