### ISSUE TITLE
Is there any way to ignore certain type of errors?

### ISSUE THREAD

**Issue by liuya05** [swagger-api/swagger-ui#2995]
I am working with version 3.0.7.

I have a spec that reference an external swagger doc which have some missing definitions.  These definitions are not directly referenced from my doc.  But they are referenced from the definitions referenced by my doc.  So when I open the page, I got a list of errors saying: "Could not resolve pointer: ...".

This error doesn't prevent me from using the swagger doc and those definitions are not currently used.  The external doc belongs to a different group which I have no control of.  So I cannot remove the missing references.  And that group has no intention to add the missing definitions because they are placeholders for future use.

When I used an older version of swagger ui, no error was reported.  However with version 3.0.7, I keep getting this error.  I would like to ignore this type of error and not display them on top of the page.  Is there any way to achieve that?

Thanks.

**Comment by webron** [comment]
@shockey we should be suppressing all error messages in the UI.

**Comment by webron** [comment]
@liuya05 Do you still experience it with the latest version of swagger-ui?

**Comment by webron** [comment]
Revisiting this, we feel the behavior should remain as-is. The current behavior will alert consumers that something may be wrong with the definition and should encourage maintainers to fix their definitions.
