### ISSUE TITLE
Tag Order Is No Longer Respected

### ISSUE THREAD

**Issue by soluwalana** [swagger-api/swagger-ui#2996]
Swagger-UI Version 3.0.7. Tags no longer respect the order from the server I suspect it is because of this line right here, which turns it into a set rather than a list with the original order.

https://github.com/swagger-api/swagger-ui/blob/7790383ba6c9bc4f3a4c6c7f1f5c4a10318adaa0/src/core/plugins/spec/selectors.js#L194

**Comment by webron** [comment]
Duplicated of #2790.
