### ISSUE TITLE
Please make text box at top used to input URL for swagger spec file wider

### ISSUE THREAD

**Issue by eric-tucker** [swagger-api/swagger-ui#2998]
Current width is 350px and this is too short for most URLs.

There's lots of room on desktop to make this far wider.  Is this a mobile thing?  I made it 700px long on my machine and it's much nicer.

**Comment by webron** [comment]
@Minasokoni - this is at your discretion.

**Comment by Minasokoni** [comment]
@eric-tucker no problem

**Comment by shockey** [comment]
Fixed in #3002 😄
