### ISSUE TITLE
Polymorphism should be reflected in ResponseClass model view

### ISSUE THREAD

**Issue by valdemon** [swagger-api/swagger-ui#300]
Hi, 
it seems that the "discriminator" and/or "subTypes" declaration existing in api json is not anyhow reflected in the swagger-ui ResponseClass model view (checked in 2.0.1).
This concerns the polymorphic result classes, as described in the article: https://gist.github.com/leedm777/5730877.
Is there any vision/timeframe for the implemention of such a feature?

**Comment by fgaule** [comment]
Any news ? It would be great to have it merged soon :)

**Comment by fehguy** [comment]
It's close

**Comment by fgaule** [comment]
@fehguy Excuse me if i'm missing something, but how should it works? I find nothing about "discriminator" neither "subType". Thanks

**Comment by georgespalding** [comment]
Nice to hear that a mege is close, would the merge be to develop or develop_2.0?
I'm also curious if the proposed fix will show models that "extends": "SomeBaseModel".

**Comment by JPMSoftwire** [comment]
Is this still an active issue? Looking for this functionality at the moment - is there any work left to me done on this?

**Comment by fehguy** [comment]
This is all pending work on swagger-js.

**Comment by tiago-loureiro** [comment]
What's the timeline for v2.1 ?

**Comment by fehguy** [comment]
this is merged in https://github.com/swagger-api/swagger-ui/commit/7cc1a36d956ab454168721da4a69762a3739826b

**Comment by muhmud** [comment]
This is still a problem for me in 2.1.4

**Comment by CSberger** [comment]
I still don't see this in 2.1.4

**Comment by SebastianStehle** [comment]
How is this supposed to look like? Would like to see it in action, I think it is an important feature.

**Comment by raderio** [comment]
@SebastianStehle like in https://github.com/Rebilly/ReDoc
![discriminator-demo](https://user-images.githubusercontent.com/4563564/50338458-07872a80-051d-11e9-981e-828754bc6618.gif)

**Comment by SebastianStehle** [comment]
Hi, @raderio My answer is 2 years old. I already moved over to Redoc long ago ;)
