### ISSUE TITLE
I want to make the documentation manually, how Can I do that, a year ago, I was able to do that on the  web site by filling some forms, Now I am able to reach that facility

### ISSUE THREAD

**Issue by shima-mahmoud** [swagger-api/swagger-ui#3001]
When reporting an issue, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue

**Comment by webron** [comment]
Use http://editor.swagger.io/ or clone https://github.com/swagger-api/swagger-editor and run it locally.
