### ISSUE TITLE
Swagger ui is not loading swagger api json

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [swagger-api/swagger-ui#3007]
I have made api documention with the help of swagger-editor. Now I want see it graphically with the help of swagger-ui. I have deployed my json here https://powerful-escarpment-92284.herokuapp.com/swagger.json

Now When I am trying to access it then I am getting an error "Failed to load spec." https://i.stack.imgur.com/DGIgf.png

**Comment by shockey** [comment]
I'm getting this error:

> Fetch API cannot load https://powerful-escarpment-92284.herokuapp.com/swagger.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://petstore.swagger.io' is therefore not allowed access. 
> 
> If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

You need to set up your Heroku application to provide [response CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#The_HTTP_response_headers) in order to allow Swagger-UI on a different origin to access your `swagger.json`. This is not a limitation of our project - it's a security mechanism built into all browsers 😄

**Comment by ajaysaini-sgvu** [comment]
@shockey Thanks! How did you get to know about this.

> Fetch API cannot load https://powerful-escarpment-92284.herokuapp.com/swagger.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://petstore.swagger.io' is therefore not allowed access.

Are you using any tool ?

**Comment by shockey** [comment]
@ajaysaini-sgvu No special tools, I just opened my browser's built-in Developer Tools and looked at the console output.

**Comment by ajaysaini-sgvu** [comment]
@shockey Thank a lot! It worked for me :+1:

**Comment by jchilela** [comment]
Same error. Angular Swegger UI.
