### ISSUE TITLE
How to add logic into "Try it out!" button.

### ISSUE THREAD

**Issue by flytosm** [swagger-api/swagger-ui#3008]
Hi, all
I got a problem when I use swagger(springfox) to create the dynamic document.
I hope someone can help me.
When Document reader want to try out the api, an parameter can not be input by reader, it should be generated by some logic (need to use input parameter and request url).
May I customize the swagger ui, and add the logic into "Try it Out" button.
Is there anyone could share me the detail document (steps) or a sample.
(Can i use both springfox and swagger-ui at the same time? i need to create
a signature by using the input parameter and request url. Dose anyone has any
idea for this ?)
Thanks.

**Comment by shockey** [comment]
You can use the `requestInterceptor` option to mutate request data before it's fired.

I'm closing; please reply if there are lingering concerns :smile:
