### ISSUE TITLE
Wrong Content-Type for multipart/form-data

### ISSUE THREAD

**Issue by aalleexxeeii** [swagger-api/swagger-ui#3009]
When there is an optional file parameter and it is not specified, swagger-ui submits Content-Type: text/plain instead of multipart/form-data.
Example: [swagger.yaml.txt](https://github.com/swagger-api/swagger-ui/files/968646/swagger.yaml.txt)

**Comment by webron** [comment]
Which version of swagger-ui?

**Comment by aalleexxeeii** [comment]
The version currently deployed on http://petstore.swagger.io/

**Comment by owenconti** [comment]
Is this the same as https://github.com/swagger-api/swagger-ui/issues/3075?

**Comment by aalleexxeeii** [comment]
No idea. I would test whether my issue is resolved, but the last version doesn't recognize my YAML definition at all.

**Comment by owenconti** [comment]
There was a syntax error in your YAML file. Try testing on this:

http://petstore.swagger.io/?url=https://gist.githubusercontent.com/owenconti/5e2f9dd8646d395cd4d4399006d30441/raw/f60679d173bd2309aa58be66d2c0c3f2940cc8a5/gistfile1.txt#/configuration/resolve

I see the original POST request go out as `multipart/form-data`.

**Comment by webron** [comment]
Going to close this one as it's an older version of the UI.
