### ISSUE TITLE
Method to set 'Api key authorization'

### ISSUE THREAD

**Issue by supsup** [swagger-api/swagger-ui#3010]
v3

1. user goes to http://petstore.swagger.io/
2. user clicks authorize
3. user scrolls down to  'Api key authorization'
4. user enters value
5. user submits form

Actual: Nothing wrong, I just want to do this with a method call instead of having to use a form.

Ideal flow:
Access to helper method like 
`ui.auth.apiKey = 'foobar'`

**Comment by craigcoles** [comment]
@supsup It would be good to set an API Key from init, like [oAuth](https://github.com/swagger-api/swagger-ui#oauth2-configuration).

**Comment by jodigiordano** [comment]
I have a similar use case.

My API has a simple token authentication scheme (X-Token in a HTTP header) and the Authorize button works fine.
My documentation is internal and I would like to add a dropdown list of all the available users to impersonate with a predefined token for each of them.
Then, when someone choose a user from the list, I want to call something like:

    ui.auth.token = user.token

That way my team can quickly use the API locally with different users without going through the entire authentication workflow.

**Comment by shockey** [comment]
Closing in favor of swagger-api/swagger-ui#2915
