### ISSUE TITLE
Swagger-UI ignoring explore url

### ISSUE THREAD

**Issue by dpeger** [swagger-api/swagger-ui#3013]
When entering a custom URL into the explore URL field on http://petstore.swagger.io/? this URL will completely be ignored and swagger-ui will always use http://petstore.swagger.io/v2/swagger.json as API spec source.

One can provide a custom URL by adding the `url=<custom-swagger-spec>` query parameter (e.g. http://petstore.swagger.io/?url=https://github.com/swagger-api/swagger-ui/files/832086/swagger.yaml.txt) but when pressing Explore, swagger-ui will again user the petstore specs.

- swagger-ui version
 3.0.8
- a swagger file reproducing the issue
not relevant

**Comment by JustinPealing** [comment]
I'm having a similar issue (updating the URL and then pressing explore resets the URL back to the petstore). I've done some digging and it looks like the `downloadUrl` function in `plugins\topbar\topbar.jsx` needs modifying:

    downloadUrl = (e) => {
      this.props.specActions.updateUrl(this.state.url)
      this.props.specActions.download(this.state.url)
      // This line is needed to prevent the form submission from refreshing the page
      e.preventDefault();
    }

**Comment by shockey** [comment]
Just merged the PR for this - the fix will be released as part of our release tomorrow.

Thanks for the input, everyone!
