### ISSUE TITLE
Create a separate commit for builds, much easier to merge/rebase

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#3014]
@shockey @bodnia @webron 
The `/dist` folder often comes into merge conflicts, making feature branches difficult to keep clean and up to date.

Is it possible to enforce a rule ( "enforce "), whereby the `build` happens on its own commit? That way an interactive rebase becomes a smooth operation ( since we just ignore all those build commits, which are useless in a rebase ). The ends are still met, where we have dist built, and in the PR it'll merge happily

Ultimately just our internal practice and a mention in the README?

Food for thought, I can add the note in the readme - if this makes sense.

**Comment by ponelat** [comment]
PS: I think this does happen ( sometimes ). So just making it official?

**Comment by shockey** [comment]
👍 

I already do this. Let's consider codifying this in the README?

**Comment by shockey** [comment]
Another option - start a `CONTRIBUTING` file, as Github officially supports it: https://github.com/blog/1184-contributing-guidelines

CC @bodnia @webron... any thoughts from y'all's end?

**Comment by webron** [comment]
CONTRIBUTING it is.

**Comment by shockey** [comment]
To recap, we've decided to start a `CONTRIBUTING` document.

**Comment by supergibbs** [comment]
In addition, maybe consider a bot? Bootstrap team made a bot that checks to make sure `dist/` isn't edited. https://github.com/twbs/rorschach

**Comment by webron** [comment]
I'm all for anything that can be automated ;)

**Comment by shockey** [comment]
Revisiting this - I think it might be best to do away with the practice of rebuilding between versions altogether.

**Comment by ponelat** [comment]
no manual `dist/`!!! :+1:
