### ISSUE TITLE
Modify request base path based on endpoint URL

### ISSUE THREAD

**Issue by dpeger** [swagger-api/swagger-ui#3015]
I have a Spring application with multiple JAX-RS servers. That is some services are deployed at `<my-server>/api/mammals` and others at `<my-server>/api/reptiles`. The `mammals` and `reptile` part of the service paths are not reflected in the `@Path` annotation of the services as this is a deployment option, that is configured in the Spring configuration classes.

Before swagger-ui 3.0.X I was able to modify the request urls by applying a little patch to the swagger-ui.js file. This is not possible anymore with swagger-ui > 3.0.X as everything is now minified and combined.

Is there any option to modify the request base path based on the actual request URL. For example I want all requests starting with `{mammalId}` to use the `/api/mammals` base path and all requests starting with `{reptileId}` to use the `/api/reptiles` base path.  Maybe there is an option in swagger-core to modify the generated yaml/json API-Spec?

I would be fine with forking swagger-ui and add the modifications there, but here would be the correct place to put this logic?

I can't add the `mammals` and `reptiles` path parts to the `@Path` annotations without modifying the application configuration as well. But this is something I'd like to avoid!

- swagger-ui version
 3.0.8
- a swagger file reproducing the issue
no relevant

**Comment by webron** [comment]
Anything is possible, but I'm afraid we don't have the capacity to go into how to modify this at the moment. You can basically run plugins to touch any part of the flow of the code.

That said, it sounds like you're trying to solve the issue from the wrong direction. If your API is split across multiple servers, it makes sense to either have multiple API descriptions (one per server) or control customize the host at the operation level.

**Comment by dpeger** [comment]
Thanks for your response.

Actually by the time writing down this issue, it already felt like swagger-ui is not the right place to make these adjustments. I now solved this by implementing a `ReaderListener`, that adjusts the paths of the `Swagger` as needed.
