### ISSUE TITLE
window not defined

### ISSUE THREAD

**Issue by andrewcharnley** [swagger-api/swagger-ui#3016]
Latest on npm (3.0.8). 3.0.7 is ok. Given it broke last week as well it needs mentioning this project is way too unstable for distribution with swagger-tools.

````ERROR ReferenceError: window is not defined\n    at Object.<anonymous> (/home/osboxes/git/lerna-repo/packages/process-rtx-api/node_modules/swagger-ui/dist/swagger-ui.js:1:3485)\n    at t (/home/osboxes/git/lerna-repo/packages/process-rtx-api/node_modules/swagger-ui/dist/swagger-ui.js:1:2377)\n    at Object.<anonymous> (/home/osboxes/git/lerna-repo/packages/process-rtx-api/node_modules/swagger-ui/dist/swagger-ui.js:1:2782)\n    at t (/home/osboxes/git/lerna-repo/packages/process-rtx-api/node_modules/swagger-ui/dist/swagger-ui.js:1:2377)\n    at /home/osboxes/git/lerna-repo/packages/process-rtx-api/node_modules/swagger-ui/dist/swagger-ui.js:1:2469\n    at /home/osboxes/git/lerna-repo/packages/process-rtx-api/node_modules/swagger-ui/dist/swagger-ui.js:1:2474\n````

**Comment by shockey** [comment]
@andrewcharnley Thanks for reporting this - sorry you're having issues.

I assume this is happening on page load? How are you using Swagger-UI? I need some more information in order to reproduce this.

**Comment by shockey** [comment]
Made a fix in anticipation of what the problem (almost surely) is.

It's worth noting that should only be cropping up when `swagger-ui`'s core code is run in a non-browser environment. If swagger-tools is doing this, it's likely using the 3.x series wrong.

That said, my pending PR for this moves our version stamping code into the constructor, and shields it with the window guard we use for running our tests in Node.

**Comment by shockey** [comment]
Should be fixed - please reply if any issues linger.

Thanks!
