### ISSUE TITLE
NullPointerException in ApiResourceController.swaggerResources

### ISSUE THREAD

**Issue by 1106285275** [swagger-api/swagger-ui#3019]
springboot +swagger 2.5.0
when I have annoation like  @Aspect @Pointcut @Around and  some defination like Advisor ,swagger worked failed,said as title . how to work out this problem?

**Comment by 1106285275** [comment]
Can it work with the interceptor, if not, it would be a problem

**Comment by webron** [comment]
This should be opened on SpringFox.
