### ISSUE TITLE
Has problem with OAuth2 client credentials authorization flow

### ISSUE THREAD

**Issue by quickwind** [swagger-api/swagger-ui#3020]
When reporting an issue, please provide the following details:
- swagger-ui version
http://editor.swagger.io/#/
- a swagger file reproducing the issue
```
swagger: '2.0'
info:
  description: Spring REST Sample with Swagger
  version: '2.0'
  title: Spring REST Sample with Swagger
  contact:
    name: Wallace Wei
host: 'example.com:80'
basePath: /v1/sample
tags:
  - name: Pet Service
    description: All apis relating to pets
  - name: hello-world-controller
    description: Hello World Controller
schemes:
  - https
paths:
  /hello-world:
    get:
      tags:
        - hello-world-controller
      summary: getGreeting
      operationId: getGreeting
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: name
          in: query
          description: User's name
          required: false
          type: string
          default: Stranger
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Greeting'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Failure
      security:
        - oauth2schema:
            - global
securityDefinitions:
  oauth2schema:
    type: oauth2
    tokenUrl: 'http://securityserver.com/v1/security-service/oauth/token'
    flow: application
    scopes:
      global: global
definitions:
  Greeting:
    type: object
    required:
      - content
    properties:
      content:
        type: string
        example: Jack
        description: The name of the user
      id:
        type: integer
        format: int64
```

When paste above swagger content to http://editor.swagger.io/#/ and click try it button, it sent OPTIONS http://securityserver.com/v1/security-service/oauth/token request, but our security server is expecting POST http://securityserver.com/v1/security-service/oauth/token. Am I missing anything?

**Comment by stefangr** [comment]
The OPTIONS request is to determine if the swagger application is allowed to make a POST request and is part of the Cross Origin Resource Sharing (CORS) mechanism.

**Comment by webron** [comment]
Thanks @stefangr. This is indeed a [CORS](https://github.com/swagger-api/swagger-ui#cors-support) issue. If you want to use this functionality, you'd need to enable it server side (or use a CORS proxy).

**Comment by quickwind** [comment]
@stefangr @webron Totally understand, but we have already returned 200 OK result as following to the OPTIONS request, it still fails:
```
Access-Control-Allow-Methods →POST, OPTIONS
Access-Control-Allow-Origin →*
Allow →POST, OPTIONS
Cache-Control →no-cache, no-store, max-age=0, must-revalidate
Connection →Keep-Alive
Content-Length →0
Content-Type →text/plain;charset=ISO-8859-1
Date →Thu, 04 May 2017 08:53:04 GMT
Expires →0
Keep-Alive →timeout=180, max=100
Pragma →no-cache
Server →Apache-Coyote/1.1
X-Content-Type-Options →nosniff
X-Frame-Options →DENY
X-XSS-Protection →1; mode=block
```

In the Swagger UI it just shows "Auth ErrorTypeError: Failed to fetch", and in wireshark, I can only see one request/response for the OPTIONS method as above. What would be the problem?

**Comment by stefangr** [comment]
@quickwind In the browser console (reachable via F12 in most browsers) you can see what error messages the browser is logging.
In the network tab you can see the request and response headers that the browser sends and receives.

With the exact sample swagger file you posted earlier I do not get a 'Access-Control-Allow-Origin' header in the response.
