### ISSUE TITLE
Path Parameter not properly parsed results in erroneous Test URL

### ISSUE THREAD

**Issue by xlthor** [swagger-api/swagger-ui#3024]
We have an endpoint like this

`https://server.com/services/v1/topics/path1/path2/path3/assets`

where the part `/path1....path2` is variable and the parameter value.

Path annotaion looks like this:

`@Path("{topicPath:[a-zA-Z0-9_/]+}/assets")`

and this works like charm, regardless how long the path is. Swagger UI compiles that to 

`curl -X GET "https://server.com/services/v1/topics/1/123%2F456/]+}/assets" -H  "accept: application/json;charset=utf-8"`

2 issues here: 
The '/]+}' at the end results of an improper parsing of the regex
The value itself is URL-encoded (%2F).

Is there anything we can do around that?

**Comment by webron** [comment]
The spec doesn't support making a variable with slashes in the value for a path parameter (thus making it an arbitrary number of parameters). It will/should be encoded. There's no workaround to it, it's an intentional limitation.

**Comment by xlthor** [comment]
makes sense, THX
