### ISSUE TITLE
When using oauth2 authorization code flow - redirect_uri is not send - 3.0.8 

### ISSUE THREAD

**Issue by rstraszewski** [swagger-api/swagger-ui#3034]
Hi,
When using swagger ui authentication with oauth2 authorization code flow, redirect_uri parameter is not sent to access token request.

I think, that problem is here:

`export const authorizeAccessCode = ( auth ) => ( { authActions } ) => {
 let { schema, name, clientId, clientSecret } = auth
 let form = {
   grant_type: "authorization_code",
   code: auth.code,
   client_id: clientId,
   client_secret: clientSecret
 }`

(Like in #919)

**Comment by webron** [comment]
Can you try master, or the new version we're going to release today?

**Comment by rstraszewski** [comment]
Yes, but unfortunately I can do it after weekend. I'll do it first thing Monday morning.

**Comment by rstraszewski** [comment]
Hi - after update there is other problem, and because of this, I cannot test the one above: 
wrong redirect_uri is send do identity server in request for authorization code - "redirect_uri": "http://localhost:3200/oauth2-redirect.html" (some default value??), instead the one set in SwaggerUIBundle oauth2RedirectUrl property 

This problem I think: #3045

**Comment by komikoni** [comment]
I patched uri and oauth2RedirectUrl in swaggar-ui.js @ 3.0.9, but "redirect_uri" is not sent for token request.

Currently, the following four are sent to Form.

* Grant_type
* Code
* Client_id
* Client_secret

**Comment by rstraszewski** [comment]
Is it by design?

[RFC6749#4.1.3](https://tools.ietf.org/html/rfc6749#section-4.1.3) specifies that parameters, that should be send are: grant_type, code, redirect_uri, client_id - all required

Postman also sends redirect_uri on token request

**Comment by bodnia** [comment]
Fixed with https://github.com/swagger-api/swagger-ui/issues/3081

**Comment by chiragtayal** [comment]
I checked out master branch and added oauth2RedirectUrl paramter in SwaggerUIBundle and still I am seeing that redirect_uri is not being sent to authorization server.
