### ISSUE TITLE
Swagger UI Unable To Map $ref For Nested Model

### ISSUE THREAD

**Issue by gursahibexp** [swagger-api/swagger-ui#3038]
Issue Details : 
I created the JSON Schema path on my localhost. Copied the Swagger-UI module. Added the url in the Swagger-UI. I am getting this error that model not found. This is very strange because the JSON has all the models associated to the JSON Schema. Not sure that isnt it able to find the model by ID ?

- swagger-ui version : v3.0.8
- attaching JSON
![js_error_console_log](https://cloud.githubusercontent.com/assets/19662955/25748070/70bb3c38-31c7-11e7-9ee3-af0981c2856c.jpg)
 file and snapshot of issue.
![2017-05-05_17-28-47](https://cloud.githubusercontent.com/assets/19662955/25748556/17989a40-31c9-11e7-8d27-56201aa67995.jpg)

[Swagger-UI_Issue.txt](https://github.com/swagger-api/swagger-ui/files/979199/Swagger-UI_Issue.txt)

**Comment by webron** [comment]
Swagger-UI 3.X does not support version 1.2 of the spec. If you can't upgrade to 2.0, you'd have to use the older version of the UI.

**Comment by gursahibexp** [comment]
Aah! Thank you for your response. It is working with https://github.com/swagger-api/swagger-ui/tree/v2.2.10
