### ISSUE TITLE
Uncaught ReferenceError: require is not defined, Uncaught ReferenceError: SwaggerUIBundle is not defined

### ISSUE THREAD

**Issue by jtblin** [swagger-api/swagger-ui#3044]
Using npm package `3.0.9`, nothing works as documented. 

1. There is no index.html in dist/
2. Using the index.html from master as starting point, there is no wagger-ui-bundle.js in dist/ neither
3. Using the wagger-ui.js from dist/, I get the following errors:

> Uncaught ReferenceError: require is not defined

> Uncaught ReferenceError: SwaggerUIBundle is not defined

4. There are also errors because the favicons are not in dist/ but well I don't really care about those.

Basically swagger-ui is unusable as packaged/documented. Not sure what one is supposed to do, I'd rather not have to clone the repo to make it works...

Personally ideally, I'd like a standalone (i.e. with dynamic fetching of the spec) available which seems like it was supposed to be the case reading the [release notes](https://github.com/swagger-api/swagger-ui/releases)

> Distribution files & usage
> Swagger-UI places four distribution files in its dist folder, along with a sourcemap (.map) for each file:
> * swagger-ui.js: Swagger-UI's core code without any dependencies.
> * swagger-ui.css: Swagger-UI's styling.
> * swagger-ui-bundle.js: Swagger-UI's core code, with all dependencies included.
> * swagger-ui-standalone-preset.js: A preset that provides the default StandaloneLayout for Swagger-UI. You'll want to include this unless you're creating your own layout file.
> There's also an index.html file in the dist folder that can be opened directly, if you want to quickly get started with using Swagger-UI.

**Comment by webron** [comment]
At the moment, the documentation pushed to NPM is the README for this repo. The README is accurate, however it doesn't clarify which parts of it are relevant to the NPM package.

The `swagger-ui` package indeed does not include the dist folder. That's included in the `swagger-ui-bundle` which *is* mentioned in the README.

**Comment by dylancwood** [comment]
I would like to echo @jtblin's concerns. When swagger-ui is installed by npm as a dependency, the `dist` directory contains only the following files: 
* swagger-ui.css
* swagger-ui.css.map
* swagger-ui.js
* swagger-ui.js.map

The README suggests using `index.js` as an example, but `index.js` does not reference these files. More over, though the js file appears to have some code to detect browser vs AMD vs node require, there are still loads of references to `require` which cause the following error in my browser:
![screen shot 2017-06-08 at 9 52 17 am](https://user-images.githubusercontent.com/5280961/26940618-301dadea-4c30-11e7-82c0-04b4b9464d8d.png)

Can someone please help by providing an example for how to use this package as a dependency? Perhaps we would need to bundle it ourselves using webpack or browserify. IMO, that is not a very friendly model: I would like to use NPM to install the package as a dependency, then expose the JS and CSS files through my server without needing to get webpack involved.

**Comment by shockey** [comment]
@dylancwood `swagger-ui.js` needs require so it can get its dependencies. We're following the node module pattern of declaring dependencies in the package.json and expecting them to be provided at runtime.

If you need the bundle files via npm (since it sounds like you don't have a build pipeline for JS in your use case), we've created a zero-dependency module version of our dist folder as you see it on Github here: https://npmjs.com/package/swagger-ui-dist

Take a look at that module and see if it solves your needs. Feel free to ping me here if you have any questions.

Thanks for using Swagger!

**Comment by dylancwood** [comment]
Hi @shockey: Thank you for pointing me to `swagger-ui-dist`. It will indeed suit my needs.

**Comment by shockey** [comment]
@jtblin, have you had a chance to look at `swagger-ui-dist` as well? Does it suit your needs?

**Comment by shockey** [comment]
Closing due to OP inactivity. Feel free to comment if there are any further thoughts.

**Comment by jtblin** [comment]
No I hadn't seen it and haven't tried it yet but looks like that would solve my original problem. Maybe documenting that in the readme would help with discoverability and giving a full example of how to integrate with it? Thanks for pointing to this!

**Comment by shockey** [comment]
@jtblin, @dylancwood was kind enough to add a message to the top of our main README a couple weeks back, so there's a message there now: https://github.com/swagger-api/swagger-ui/pull/3210
