### ISSUE TITLE
url parameter is ignored in Swagger 3.x it always defaults to the petstore

### ISSUE THREAD

**Issue by talawahtech** [swagger-api/swagger-ui#3045]
swagger-ui version: 3.0.9

I am trying to get swagger-ui to load my api definition file instead of the default petstore one, however modifying the url parameter for SwaggerUIBundle in the index.html file has no effect. 

I was able to work around it by doing a find and replace for "https://petstore.swagger.io/v2/swagger.json" in swagger-ui-standalone-preset.js so my guess is that the presets are overriding the explicitly defined url param.

**Comment by JordanBelford** [comment]
Same issue here. I got a little closer by using 'configUrl' instead of 'url'. The browser at least fetches the file but still uses "https://petstore.swagger.io/v2/swagger.json".

**Comment by JordanBelford** [comment]
@talawahtech 

The example from 3.0.8 worked for me after I changed the url in index.html. Something must have broken 3.0.9 recently.

**Comment by zak905** [comment]
same issue here

**Comment by rstraszewski** [comment]
Same - after 3.0.9 update

**Comment by burnes** [comment]
+1 Same here

**Comment by metroidprototype** [comment]
Can work around this for now by modifying the very end of swagger-ui-standalone-preset.js. Not 100% what other implications this might have, but my v3.0.9 default url seems to be loading properly and the UI is functional. 

Change:
`e.exports='---\nurl: "http://petstore.swagger.io/v2/swagger.json"\ndom_id: "#swagger-ui"\nvalidatorUrl: "https://online.swagger.io/validator"\noauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"\n'`

To (pulled from v3.0.8):
`e.exports="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAqRJREFUeNrEVz1s00AUfnGXii5maMXoEUEHVwIpEkPNgkBdMnQoU5ytiKHJwpp2Q2JIO8DCUDOxIJFIVOoWZyJSh3pp1Q2PVVlcCVBH3ufeVZZ9Zye1Ay86nXV+ue/9fO/lheg/Se02X1rvksmbnTiKvuxQMBNgBnN4a/LCbmnUAP6JV58NCUsBC8CuAJxGPF47OgNqBaA93tolUhnx6jC4NxGwyOEwlccyAs+3kwdzKq0HDn2vEBTi8J2XpyMaywNDE157BhXUE3zJhlq8GKq+Zd2zaWHepPA8oN9XkfLmRdOiJV4XUUg/IyWncLjCYY/SHndV2u7zHr3bPKZtdxgboJOnthvrfGj/oMf3G0r7JVmNlLfKklmrt2MvvcNO7LFOhoFHfuAJI5o6ta10jpt5CQLgwXhXG2YIwvu+34qf78ybOjWTnWwkgR36d7JqJOrW0hHmNrKg9xhiS4+1jFmrxymh03B0w+6kURIAu3yHtOD5oaUNojMnGgbcctNvwdAnyxvxRR+/vaJnjzbpzcZX+nN1SdGv85i9eH8w3qPO+mdm/y4dnQ1iI8Fq6Nf4cxL6GWSjiFDSs0VRnxC5g0xSB2cgHpaseTxfqOv5uoHkNQ6Ha/N1Yz9mNMppEkEkYKj79q6uCq4bCHcSX3fJ0Vk/k9siASjCm1N6gZH6Ec9IXt2WkFES2K/ixoIyktJPAu/ptOA1SgO5zqtr6KASJPF0nMV8dgMsRhRPOcMwqQAOoi0VAIMLAEWJ6YYC1c8ibj1GP51RqwzYwZVMHQuvOzMCBUtb2tGHx5NAdLKqp5AX7Ng4d+Zi8AGDI9z1ijx9yaCH04y3GCP2S+QcvaGl+pcxyUBvinFlawoDQjHSelX8hQEoIrAq8p/mgC88HOS1YCl/BRgAmiD/1gn6Nu8AAAAASUVORK5CYII="`

**Comment by webron** [comment]
Yup, this is a bug, and indeed a big one. We have introduced in 3.0.9 a new mechanism to actually make configs more flexible, but... we ended up breaking the simple way of configuring it.

To get it working for now, check out the instructions at https://github.com/swagger-api/swagger-ui#configs-plugin. What's broken is that the constructor config should take over the pre-compiled configs, otherwise...

**Comment by arungupta2008** [comment]
Is this ug solved I am getting the same issue in ``3.2.0``
