### ISSUE TITLE
docExpansion is not working

### ISSUE THREAD

**Issue by zak905** [swagger-api/swagger-ui#3047]
I am using swagger-ui 3.0.8, and I am trying to get all the operation collapsed on start up using docExapnsion:"none", but it does seem to have any effect. is this option still available? if not, is there any other ways to do it?

**Comment by webron** [comment]
It's not supported yet.

**Comment by urukalo** [comment]
same issue we have here too:
https://github.com/swagger-api/swagger-ui/issues/3088

**Comment by webron** [comment]
Duplicate of #2799.

**Comment by wraycode** [comment]
I just use jquery to collapse them 

`  $.initialize(".is-open", function() {  
    $(".is-open").children('div').hide(); 
  });
`
