### ISSUE TITLE
Errors  - Resolver error - e is undefined when using allOf

### ISSUE THREAD

**Issue by marcoaltieri** [swagger-api/swagger-ui#3051]
Using swagger definition at the bottom of the post with swagger-ui 3.0.9, an error is shown at the top of the page:

```
Errors 
Resolver error
e is undefined
```

If I substitute the definition of TemplateDocument with:

```
  TemplateDocument:
    properties:
      orderTemplateDocument:
        $ref: '#/definitions/TemplateDocument'
```
(removing the allOf: that I wanted to use to specify a description for the field), it works fine.

**Swagger definition:**

```
swagger: '2.0'

info:
  version: "1.0.0"
  title: Contracts API
basePath: /localhost:8080/alfresco/service/api
host: localhost:1337
schemes: 
  - http
  - https
tags:
- name: "Contracts"
  description: "Retrieve, create and update contracts"
securityDefinitions:
  BasicAuth:
    type: basic
paths:
  /contracts/{contractId}:
    get:
      tags:
      - "Contracts"
      produces:
        - application/json
      security:
        - BasicAuth: []
      description: |
        Gets `Contracts` objects.
      parameters:
        -
          name: contractId
          in: path
          description: Contract ID
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Contract"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Contract:
    type: object
    properties:
      contractID:
        type: string
        description: Contract ID
      templateDocument:
        description: Template Document
        allOf:
          - $ref: '#/definitions/TemplateDocument'
  TemplateDocument:
    properties:
      orderTemplateDocument:
        allOf:
          - $ref: '#/definitions/TemplateDocument'
  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string
      code:
        type: string
    required:
    - code
    - message
    - success

```

**Comment by chilmers** [comment]
I'm quite new to Swagger so sorry if I misinterpret this but it seems to me that you might have a circular dependency in your definitions. I.e. TemplateDocument is referencing itself. So from what I understand, you are trying to define that TemplateDocument holds a property orderTemplateDocument, that is a TemplateDocument that holds a property orderTemplateDocument, that is a TemplateDocument that holds a property orderTemplateDocument and so on infinitely. Could this be the problem in this case? Anyhow I like your way of using allOf to get a description alongside a ref, I'm trying to do the same thing and that particular construct doesn't seem to render well in the UI, not sure if that is related to this case though.

**Comment by webron** [comment]
The error doesn't exist anymore. Regardless, that kind of circular reference makes a meaningless definition.

**Comment by marcoaltieri** [comment]
@webron and @chilmers It makes sense for my use case and I think for many other use cases.  
There isn't a circular loop because one object **can** have a reference to another object of the same type but not all the objects have this reference. Actually, in my case there are only two levels: a template for a contract can have reference to a template for orders. Both templates have the same object type but templates for orders will never have a reference to other templates because only a contract has orders.
