### ISSUE TITLE
Error- StatusCode: 500, 'Conflicting schemaIds: Duplicate schemaIds detected'

### ISSUE THREAD

**Issue by Kumarez** [swagger-api/swagger-ui#3055]
I am using Swashbuckle.Core.5.5.3. 

I get Conflicting schemaIds: Duplicate schemaIds detected error when two model classes have same name.

Error Description: Conflicting schemaIds: Duplicate schemaIds detected for types Project.Contracts.Data and Project.Models.Test.Data See the config setting - "UseFullTypeNameInSchemaIds" for a potential workaround

>>I tried using the below options,
1.c.UseFullTypeNameInSchemaIds,
2.c.SchemaId(t => t.FullName.Contains('`') ? t.FullName.Substring(0, t.FullName.IndexOf('`')) : t.FullName);
3.c.SchemaId(t => t.FullName);
but in each option, the api descriptions are not fetched and the page is unresponsive.

>>Tried using [ApiExplorerSettings(IgnoreApi = true)] to ignore the conflicting schema's, which too failed.
>>Cannot rename every model as there are many such models with conflicts.

Is there any option to ignore the conflicts and overcome the issue?

**Comment by webron** [comment]
Please specify the version of swagger-ui you're using and provide a copy of the loaded API description.

**Comment by Kumarez** [comment]
We use Swagger-ui version 2.0

I still did not get any description loaded. Please find the unresponsive page attached when c.UseFullTypeNameInSchemaIds is used.
![swagger_unresponsive](https://cloud.githubusercontent.com/assets/28556030/25885071/fe78c2fc-3573-11e7-956e-080cbb9665a7.png)

**Comment by webron** [comment]
Can you try the latest release?

**Comment by Kumarez** [comment]
Thanks for the suggestion Ron. The cause for the unresponsiveness was found and resolved.

Root cause: Some of the input parameters for the API post methods were IEnumerable which caused the issue.  On removing those obsolete methods, the issue got resolved. :)
Reference :- 
http://stackoverflow.com/questions/35605427/swagger-ui-freezes-after-api-fetch-and-browser-crashes
