### ISSUE TITLE
Question: Plugin custom config?

### ISSUE THREAD

**Issue by jmendiara** [swagger-api/swagger-ui#3061]
Swagger 3.0.9

I'm trying to create a plugin that needs some external config, but I cannot find a pattern to do it

1) The core `whitelist` the config properties that reach the `toolbox.getConfigs()` method
https://github.com/swagger-api/swagger-ui/blob/master/src/core/index.js#L85
(See to #3056 ) so this pattern does not work
```js
const ui = SwaggerUIBundle({
    url: "http://petstore.swagger.io/v2/swagger.json",
    dom_id: '#swagger-ui',
    presets: [ ... ],
    plugins: [ ... ],
    //...
    layout: "StandaloneLayout",
    myCustomKey: 'myCustomValue' // DOES NOT WORK
  })
```

2. If the approach is a factory function like
```js
const ui = SwaggerUIBundle({
    url: "http://petstore.swagger.io/v2/swagger.json",
    dom_id: '#swagger-ui',
    presets: [ ... ],
    plugins: [
      MyPlugin({
        myKey: 'MyValue'
      })
    ],
    layout: "StandaloneLayout"
  })
```
What is the best way to add it to the `toolbox` object?
```js 
// MyPlugin/index.js
module.exports = function(staticConfig) {
  return [
    () => {
      return {
        statePlugins: { 
          myPlugin: {
            selectors: {
              config: _ => staticConfig
            }
          }
        }
      }
    }
  ]
}
// now can be access in components with `this.props.myPluginSelectors.config()`
```
3. Please, some great advice!

Thanks!

**Comment by shockey** [comment]
@jmendiara, I think the way you're doing it with a static selector is the best current way to do it, but it isn't _great_.

Does adding a `custom` object to the config whitelist, where you can put your custom config key/value pairs, sound like a good solution to you?

**Comment by jmendiara** [comment]
> Does adding a custom object to the config whitelist, where you can put your custom config key/value pairs, sound like a good solution to you?

Yes

**Comment by shockey** [comment]
Cool! 

@bodnia, let me know if you agree with this approach and I'll implement it
