### ISSUE TITLE
Unmet Peer Dependency problems for react and webpack

### ISSUE THREAD

**Issue by akhileshkasibatla** [swagger-api/swagger-ui#3062]
Hello @shockey, @webron 

I am using swagger-ui 3.0.9

When i have cloned the repo into my local directory and run an npm install either in local context or global context having the below error

/usr/lib
└─┬ swagger-ui@3.0.9 
  ├── UNMET PEER DEPENDENCY react@15.5.4
  └── UNMET PEER DEPENDENCY webpack@>=1.3.0 `<3

`npm WARN react-addons-perf@0.14.8 requires a peer of react@^0.14.8 but none was installed.`
`npm WARN worker-loader@0.7.1 requires a peer of webpack@>=0.9 <2 || ^2.1.0-beta but none was installed.`
`npm WARN webpack-dev-server@1.14.0 requires a peer of webpack@>=1.3.0 <3 but none was installed.`
`npm WARN react-addons-shallow-compare@0.14.8 requires a peer of react@^0.14.8 but none was installed.`
`npm WARN react-object-inspector@0.2.1 requires a peer of react@^0.14.0 but none was installed.`
`npm WARN webpack-dev-middleware@1.10.2 requires a peer of webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0 but none was installed.`

react and webpack dependencies are not installed even with `sudo npm install -g swagger-ui`

Can anyone fix this or help me over come this issue??

**Comment by akhileshkasibatla** [comment]
Hello @shockey 

Is this issue fixed?? I dont see any fixes in the commits for #3062 in 3.10 ??

**Comment by shockey** [comment]
Hey @akhileshkasibatla, sorry for the delayed response.

The NPM warnings are normal, it's just different modules complaining about dependencies they want. Note that they're warnings, not errors 😄

You should have React and Webpack installed for you when you do an `npm install`.

Questions for you:
- Do you have a `swagger-ui/node_modules/react` and `swagger-ui/node_modules/webpack`directory?
- Does `npm run dev` work for you?

**Comment by akhileshkasibatla** [comment]
Hello @shockey 

Thanks for responding back. Yes i do have those modules in my `swagger-ui/node_modules/` directory.
`npm run dev` works for me now. Earlier even though i had `webpack` and `react` modules in my `swagger-ui/node_modules/` directory `npm run dev` did not work for me. So i had to install those modules in the global context to build core.

Now everything works fine. Thanks for your time.

**Comment by shockey** [comment]
That's strange - npm should import the local `webpack` binary into your PATH for you, [as per the docs](https://docs.npmjs.com/misc/scripts#path). Put differently- `npm run dev` should transparently grab the project's copy of webpack, so you shouldn't need to install it globally.

Can you give me your `ls node_modules/.bin` output?

**Comment by akhileshkasibatla** [comment]
@shockey 

Here you go my `ls node_modules/.bin` ouput. But now everything is working fine. I think you can close this issue.
![node_modules_output](https://cloud.githubusercontent.com/assets/21322268/26419985/9bd7ae2c-407e-11e7-936e-81d80e09960e.PNG)

**Comment by shockey** [comment]
Thanks for providing - i'll keep this on hand in case a problem like this crops up again.

Glad I could help. Closing!
