### ISSUE TITLE
3.0.9 dist files missing

### ISSUE THREAD

**Issue by willin** [swagger-api/swagger-ui#3063]
When reporting an issue, please provide the following details:
- swagger-ui version

3.0.9

- a swagger file reproducing the issue

![snipaste_20170510_172413](https://cloud.githubusercontent.com/assets/1890238/25891988/8db43a56-35a5-11e7-8d71-b3a56a900c95.png)

how to use like 2.x version with dist/ xxx.html  xxx.css xxx.js

**Comment by jb08** [comment]
use v3.0.8 - there's a [bug](https://github.com/swagger-api/swagger-ui/issues/3045) in v3.0.9.

files are there: 

![screen shot 2017-05-10 at 9 30 31 am](https://cloud.githubusercontent.com/assets/8146460/25903916/5dbefe7c-3563-11e7-970c-dc519e6860af.png)

**Comment by willin** [comment]
the same, using yarn

**Comment by shockey** [comment]
Hey @willin, this is intended behavior for the `swagger-ui` package. We changed how it works in 3.0: the package is intended for use via a module loader.

If you're looking for the old style of our entire dist folder in an npm package, check out the `swagger-ui-dist` package, which has the entire dist folder as you see it in Git within a package that has no dependencies.

Let me know if that's what you're looking for!

**Comment by willin** [comment]
yes i get it

```js
<script>
function HideTopbarPlugin() {
  // this plugin overrides the Topbar component to return nothing
  return {
    components: {
      Topbar: function() { return null }
    }
  }
}
window.onload = function() {
  // Build a system
  const ui = SwaggerUIBundle({
    url: location.protocol + '//' + location.host + '${pathPrefix}/api-docs',
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl,
      HideTopbarPlugin
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
</script>
```

i set the url address but still load from `http://petstore.swagger.io/v2/swagger.json`

**Comment by shockey** [comment]
See @willin's comment above, this is a known bug (#3045).

You can use 3.0.8 in the meantime, or wait until Friday, when we'll release 3.0.10 with a fix.
