### ISSUE TITLE
New feature fix for array of objects in the definitions properties section

### ISSUE THREAD

**Issue by akhileshkasibatla** [swagger-api/swagger-ui#3066]
Hello @shockey , @webron 

Currently swagger model definition cannot accept an array of objects in the properties section of the swagger definitions. So I have added a fix for **array of objects in the properties section** in my local development environment which can be a new feature for swagger-ui . This feature makes it way easier for someone to document their rest api who is using array of objects in their model definitions. I have attached the screenshots of how it looks. Will you be interested in this feature so that i can submit a pull request??

![arrayofobjectsexample](https://cloud.githubusercontent.com/assets/21322268/25908227/dcb1216c-3566-11e7-9699-b5dfb395e873.PNG)

![arrayofobjectsmodel](https://cloud.githubusercontent.com/assets/21322268/25908226/dcb02c76-3566-11e7-9dfe-d7ca07c29773.PNG)

**Comment by shockey** [comment]
This looks good to me. @webron can tell you if this is a feature we want 😄

**Comment by webron** [comment]
@akhileshkasibatla can you provide a minimal spec that reproduces the issue in the current UI so I can take a look? If it makes sense, we'd love to get a PR.

**Comment by akhileshkasibatla** [comment]
Hello @webron 

I have attached the JSON File which has the specs and also the screen shot of how swagger model and example value looks if i give array of objects in the definitions properties section. If we give type as an array for a model definition then under items we cannot have an object without a key value. But with my fix instead of giving type as an array we can give type as object and have properties take array of objects which provides the option of having headless objects(Objects without key).

Here is the issue with current version

![modeldefinition](https://cloud.githubusercontent.com/assets/21322268/25958272/733eb09c-362d-11e7-8777-db4723975105.PNG)

![examplevalue](https://cloud.githubusercontent.com/assets/21322268/25958271/732b6032-362d-11e7-8cf9-92cf5a719608.PNG)

Here is the JSON spec
[Employee JSON.txt](https://github.com/swagger-api/swagger-ui/files/993557/Employee.JSON.txt)

**Comment by akhileshkasibatla** [comment]
Hello @webron

Any comments on the above discussion??

**Comment by akhileshkasibatla** [comment]
Hello @webron 

Any comments on the above discussion??

**Comment by webron** [comment]
@akhileshkasibatla apologies for the delay and thanks for your patience.

The JSON you provided is not a valid spec. I'm not entirely sure what you're trying to do there, so I can't offer a fix, but if you help me understand I should be able to do that.

**Comment by akhileshkasibatla** [comment]
Hello @webron 

I have attached two files `Employee_Conventional_Spec.txt` which has specifications as expected by Swagger  and `Employee_With_Array_In_Properties.txt` has properties section **defined as an array of objects** . If we use `Employee_With_Array_In_Properties.json` swagger will throw an error `Schema error at definitions.Employee.properties should be a object` and the `example value` , `model` in the body **section** will look like the attached screenshots. 

![examplevalue](https://cloud.githubusercontent.com/assets/21322268/26511468/6538c8ae-421f-11e7-81f9-0ca2acf517c0.PNG)
![modeldefinition](https://cloud.githubusercontent.com/assets/21322268/26511469/653a0e58-421f-11e7-9204-b08a36a9569f.PNG)

But i have added a fix and created a pull request #3119 to allow users to have array of objects in their properties section which is a valid JSON. With this we can give **type as an object** and have properties take array of objects which provides the option of having headless objects(Objects without key/name) in the properties section.. After the fix we will not have the error and  the `example value` , `model` in the body **section** will look like the attached screenshots

![arrayofobjectsexample](https://cloud.githubusercontent.com/assets/21322268/26511621/1bc6177a-4220-11e7-9c94-82af4f831894.PNG)
![arrayofobjectsmodel](https://cloud.githubusercontent.com/assets/21322268/26511620/1bc29c6c-4220-11e7-96e5-9d46ba5e96a6.PNG)



[Employee_Conventional_Spec.txt](https://github.com/swagger-api/swagger-ui/files/1032915/Employee_Conventional_Spec.txt)
[Employee_With_Array_In_Properties.txt](https://github.com/swagger-api/swagger-ui/files/1032914/Employee_With_Array_In_Properties.txt)

**Comment by webron** [comment]
I have loaded your `Employee_Conventional_Spec.txt` file, and it loads just fine in the UI, no errors, so I'm really not sure what you're trying to fix.

However, we will not accept changes to swagger-ui that break away from what the spec allows. Our goal is to serve the spec, and not deviate from it.

**Comment by akhileshkasibatla** [comment]
@webron 

I am not trying to fix a problem. I am suggesting a new feature which lets users who defines properties in their model definitions as an array of objects. If you load the `Employee_With_Array_In_Properties.txt` you will see errors. It is a valid JSON but not a valid spec for swagger. My changes will make `Employee_With_Array_In_Properties.txt` a valid spec for swagger. It adds much flexibility for model definitions.

**Comment by shockey** [comment]
@akhileshkasibatla, unfortunately changing the Swagger specification is not nearly as simple as making a code change here - Swagger-UI is simply a tool that follows the [Swagger 2.0 specification](http://swagger.io/specification/), as written in 2014.

The [schema object](http://swagger.io/specification/#schema-object-80) in the Swagger specification indicates that the `properties` key inherits from the JSONSchema specification. 

JSONSchema, in turn, defines a valid `properties` value as such:

> The value of "properties" MUST be an object. Each value of this object MUST be a valid JSON Schema.
>
> ([citation](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.18))

As @webron said, this project exists to be in line with the Swagger specification, so we can't accept something that would go against what you see above.

---

My question for you - what are you trying to do inside your spec that requires the use of an array of property definitions? We may have a feature in the specification that will help you achieve it.

**Comment by hkosova** [comment]
@shockey @webron: If I understand the use case correctly, @akhileshkasibatla wants to describe a model with varying properties.

@akhileshkasibatla, the easiest way to do that is to have a single model and just make the varying properties (such as `Bonus` and `TeamId`) optional.

If you _must_ have separate models for some reason, the upcoming [OpenAPI Specification 3.0](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md) will support `anyOf` and `oneOf` for this purpose. So once the 3.0 spec is released and supported, you will be able to have something like this (I think):
```
paths:
  /employee:
    get:
      '200':
        content:
          application/json:
            schema:
              anyOf:
                - $ref: "#/components/schemas/BaseEmployee"
                - $ref: "#/components/schemas/EmployeeWithBonus"

components:
  schemas:
    BaseEmployee:
      type: object
      properties:
        EmployeeName:
          type: string
        Salary:
          type: number
          format: double
  
    EmployeeWithBonus:
      allOf:
        - $ref: '#/components/schemas/BaseEmployee'
        - type: object
          properties:
            Bonus:
              type: number
              format: double
```

**Comment by akhileshkasibatla** [comment]
@hkosova My use case is all about allowing an array of JSON Objects in the properties section to be a valid swagger spec without the need for defining individual model and using `anyOf` to display either of the model or to have varying properties as `optional`.

@webron AND @shockey Thanks for your time.

I hope in future this swagger limitation will be eliminated for `Employee_With_Array_In_Properties.txt` type of valid JSON

**Comment by webron** [comment]
It's very unlikely that it will. 3.0 does add support for `oneOf`/`anyOf` which will cover it, and it's based on the JSON Schema spec, which we are not going to change. Thank you for your time.
