### ISSUE TITLE
403 error don't show Response header and body

### ISSUE THREAD

**Issue by reeperbahnause** [swagger-api/swagger-ui#3072]
I used the current swagger UI running on http://petstore.swagger.io/

I noticed that ``40*`` errors do not show the response header and body.
In my case I want to return the error code and error message as json object in the body like this:
```json
{
  "code": 403,
  "message": "You are not authorized!"
}
````
Even if the body is set correctly and content-type is set, the body/header are not shown in the current version. 

![image](https://cloud.githubusercontent.com/assets/14199872/25949448/e48c9c94-3657-11e7-8b7f-bb8a7bb3d737.png)

**Comment by rolandg** [comment]
+1 same here

**Comment by Lotti** [comment]
+1 (there is a version that actually doesn't have major critical bugs? 3.0.9 doesn't permit to load a swagger. it always defaults to petstore. 3.0.8 doesn't show error responses.. what release can i use?)

**Comment by Lotti** [comment]
3.0.7 doesn't have this problem.

**Comment by rolandg** [comment]
@Lotti my workaround for the petstore issue
```js
    window.onload = function () {

        var url = window.location.origin + '/apidoc/apidoc.json';

        if (location.href.indexOf('?') === -1) {
            window.location.replace(window.location.href + '?url=' + url);
        }
    }
```

**Comment by Lotti** [comment]
@rolandg thank you! I'll stick with 3.0.7 until a new fixed release will appear!

**Comment by rstraszewski** [comment]
Yea, 3.0.7 shows failed response body, but again oauth2 is not working which is important for me...

**Comment by Lotti** [comment]
wow, i'm lucky that I use api_key method ;)

**Comment by webron** [comment]
Thanks everyone for reporting the issue - it's... not great 😕. It looks like #3076 is trying to fix it (or something similar), but it doesn't cover all cases as it seems (at least from my testing). This is going to be a high priority for us to fix, but unfortunately will not make it into today's release.

If anyone wants to give a fix a whirl, we'd appreciate it. Bonus points to anyone adding tests (with or without the fix) so we can make sure this never breaks again in the future.

**Comment by lsimoneau** [comment]
We've just run into this issue, couldn't really figure it out but we found this addition to swagger-js in 3.0.8: https://github.com/swagger-api/swagger-js/blob/v3.0.8/src/http.js#L40-L44

In the `http` method, a condition was added that does:

```
    if (!res.ok) {
      const error = new Error(res.statusText)
      error.statusCode = error.status = res.status
      throw error
    }
```

I'm not familiar with the codebase, but it looks like previously errors responses were returned the same as successful responses, but now they're thrown as exceptions?

It doesn't look like there were any changes in the way HTTP calls are handled in `swagger-ui` when going from 3.0.7 to 3.0.8, so this change in the underlying API might be responsible for the issue?
