### ISSUE TITLE
Petstore uploadImage 'try it out' results in 415 unsupported media type

### ISSUE THREAD

**Issue by jraeymaek** [swagger-api/swagger-ui#3075]
http://petstore.swagger.io/ 

The uploadImage post request contains an empty body and content-type equals "text/plain;charset=UTF-8". Is this a bug?

**Comment by webron** [comment]
Yeah, it is 😕

**Comment by owenconti** [comment]
@jraeymaek @webron I can't seem to reproduce this. Is this still an issue?

**Comment by webron** [comment]
No, seems like this is fixed.
