### ISSUE TITLE
OAuth2 client_id is missing

### ISSUE THREAD

**Issue by orivil** [swagger-api/swagger-ui#3081]
- swagger-ui 3.0.10

![o1vq7 tlxm xk7u2qi7 x w](https://cloud.githubusercontent.com/assets/17449878/26049488/c6e0b642-398d-11e7-9e4b-133d9a9c629a.png)

When I click the "Authorize" button, it jump to the GitHub's 404 page.

After many times I tried, I found the "client_id" parameter is not in the "authorization url".

It goes right only if I manually enter this parameter into Url.

![20170515171126](https://cloud.githubusercontent.com/assets/17449878/26050606/dc093dc4-3991-11e7-8763-57d2caea1a75.png)

**Comment by rstraszewski** [comment]
I have the same problem - what is interesting, in code everything seems fine:
` url += "&redirect_uri=" + encodeURIComponent(redirectUrl)
      + "&realm=" + encodeURIComponent(authConfigs.realm);
      + "&scope=" + encodeURIComponent(scopes.join(scopeSeparator))
      + "&state=" + encodeURIComponent(state)
      + "&client_id=" + encodeURIComponent(clientId)`

so i looked into swagger-ui-bundle.js - and it is not fine ;p
`g+="&redirect_uri="+encodeURIComponent(d)+"&realm="+encodeURIComponent(u.realm),NaN+encodeURIComponent(l.join(m))+"&state="+encodeURIComponent(y)+"&client_id="+encodeURIComponent(f)`

This part: `,NaN`
I changed it into: `+"&scope="`

And it is working ;p so some problem with bundling

Unfortunately redirect_uri is still not send with token request  (Issue: #3034)

**Comment by bodnia** [comment]
fixed https://github.com/swagger-api/swagger-ui/issues/3084
