### ISSUE TITLE
OAS 3.0: Rendering

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#3083]
This ticket tracks line items related to the rendering of OAS 3.0 specs. It does not include line items related to Try-It-Out functionality, or any UI changes to support the Editor experience.

Time estimates formatted as **##h/RiskLevel**. Estimates include tests where applicable.

Work is being done in [this branch](https://github.com/swagger-api/swagger-ui/tree/ft/oas3).

#### Internal plumbing
- [x] Add mechanism for overriding selectors based on spec content **8h/Med**
 (https://github.com/shockey/swagger-ui/commit/1f314ddca2f299167a05aa2712f4faed14443c0c)
- [x] Add mechanism for overriding components based on spec content **6h/Med** (https://github.com/shockey/swagger-ui/commit/614c1ae7f6f13bada97f233a7ab3fbd25679f1ec and https://github.com/shockey/swagger-ui/commit/88848d071b7383c59a2cde9904aa724783317c4a)

#### Supporting changes
- [x] Render reorganized definitions (https://github.com/shockey/swagger-ui/commit/60934107d33c48d0a0e2ab41c090c650eff03924#diff-be155ae7ebea3eda018b85efba94c8b0R41)
- [x] Render reorganized responses **1h/Low**
- [x] Render reorganized parameters **2h/Low**
- [x] Support CommonMark in descriptions **1-2h/Low**
- [x] Render request bodies **4h/Low** (Implemented, needs design work)
- [x] Render cookie parameters **2h/Low**
- [x] Render response ranges **2h/Low**
- [x] Render callbacks **12h/Med**
- [x] Render `deprecated` **4h/Low**
- [x] Render links **6h/Med**
- [x] Render media types in Request Parameters, Request Body, Responses **12h/Med**
- [x] Render schema values with `anyOf`, `oneOf`, `not` **10h/Med**
- [x] Render nullables **1h/Low**
- [x] Render `writeOnly` **2h/Low**

#### Moar changes
- [x] Render `deprecated` in individual properties
- [x] Ensure Markdown XSS protections are still present in new renderer

#### Even moar changes (added 6/28)
- [x] Disable validation badge

#### Ignoring deprecated fields 
**6h/Low** in aggregate
- [x] host
- [x] basePath
- [x] schemes
- [x] consumes
- [x] produces
- [x] definitions
- [x] parameters
- [x] responses

**Comment by shockey** [comment]
### Moar

- [ ] Render `deprecated` in individual properties

**Comment by webron** [comment]
- [ ] `Callbacks` tab should not appear if there are no callbacks defined.
- [ ] `Links` styling needs to be fixed. 
- [ ] `headers` no longer exist under Links (this is from RC2)
- [ ] The `response content type` is aligned to the left and too close to the `Responses` text, makes it look weird. But...
- [ ] The `response content type` should appear individually per response code and no longer at the top of the `Responses`. Each response code can have entirely different content types defined for it.

**Comment by shockey** [comment]
### Status update on changes

> `Callbacks` tab should not appear if there are no callbacks defined.

Done:

![image](https://user-images.githubusercontent.com/680248/27723528-76b4fd0a-5d22-11e7-92ac-0a2e6d769437.png)

---

> `headers` no longer exist under Links (this is from RC2)

Link headers have been annihilated.

---

> The response content type is aligned to the left and too close to the Responses text, makes it look weird. 

Fixed:

![image](https://user-images.githubusercontent.com/680248/27723658-03be6a92-5d23-11e7-836b-7a3fdf594cdd.png)

---

> For callbacks, disable the try it out functionality.

Fixed:

![image](https://user-images.githubusercontent.com/680248/27723769-7d8e896a-5d23-11e7-8e99-01ed11f4657f.png)

Note the small lingering CSS issue inside the callback operation.

---

> Request body should have the content type as a drop down, and the model/example view change based on the choice. It should not show a long list of content types as now.

Done:

![image](https://user-images.githubusercontent.com/680248/27724670-c8d4e212-5d27-11e7-8c10-515b1a2be3b5.png)

---

> > The response content type should appear individually per response code and no longer at the top of the Responses. Each response code can have entirely different content types defined for it.

In progress - the functionality works, just need to finish guarding the code so it fails gracefully.

---

The two lingering Request Body fixes are tricky - the current implementations that provide the generated samples and editing interface are very opinionated about the incoming data (it expects Swagger 2.0 parameters) I have something in progress, but I'll have to wrap it up this weekend.

**Comment by shockey** [comment]
@webron bump - need more info on `Links styling needs to be fixed`
