### ISSUE TITLE
The repo should not include `./dist` directory

### ISSUE THREAD

**Issue by jmendiara** [swagger-api/swagger-ui#3087]
While hacking into the code (npm run dev), every time the project is built, the `./dist` files are generated. 
_almost_ (not every) every master commit includes the `./dist/` files, and with every `git pull` I get conflicts in `dist/`. Some are because the master commits include functionality in `src` that have not been built and my local builds them

So I'm forced to cherry-pick my functionality without `dist` into a rebased clean master every time i need to pull. It's a pain.

Also, i see PR from collaborators with dist folders that probably will cause huge conflicts when not fully rebased, and owners including dist folder with their PRs

If the `dist` is excluded and only generated when publishing (to npm, docker, whatever), dev history maybe is easier

**Comment by webron** [comment]
Thanks for taking the time to write this up. We're aware of the issue, but at the moment it's a necessity. We have various types of users, and not everyone is a developer, certainly not a javascript developer. For those, simply cloning the repo and and running the dist/index.html file is the easiest option without having to build the project.

Granted, this is not the ideal situation, and we've had thoughts on how to improve it, but so far we haven't found the win-win solution.

**Comment by jmendiara** [comment]
> We have various types of users, and not everyone is a developer, [...]  simply cloning the repo 

This approach forces to have `git` installed, and it's not such a common utility to non-dev people. 

So currently there are two approaches to get Swagger-ui
* `git clone` the repo, go to `dist` folder, C&P files.
* People without git can go to [Releases page](https://github.com/swagger-api/swagger-ui/releases) and click [Download Sources], unzip, navigate to the `dist` folder, and C&P to its project.

What about using [github releases](https://github.com/blog/1547-release-your-software)? You simply attach the dist folder, and as another artifact repository can be easily integrated in the publish workflow (which may involve other artifacts repositories as npm, dockerhub, cdn...). This way, the users go to [Releases page] and click [Download Swagger-UI], containing only the files generated with `npm run build`.

Does it sounds reasonable?

**Comment by webron** [comment]
> This approach forces to have git installed, and it's not such a common utility to non-dev people.

Not true. Github allows you to download the repo as a zip file. You'd be surprised how many people do that. Also, a lot of non-devs still have git installed because they deal with tech regardless. Also, there are plenty of non-javasscript devs too who do have git, but don't have node/npm or the knowledge how to switch version.

The github releases is a fair approach, and I'm willing to consider it, but it's still an issue when we refer people to the master version when we push bug fixes before release. Again, dealing with the same target audience.

**Comment by shockey** [comment]
Github releases can be [created programmatically](https://developer.github.com/v3/repos/releases/#create-a-release), so it'd be possible to add creating a zip and [attaching that zip to the Github release](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) to our build process.

**Comment by shockey** [comment]
Closing this, as we've since discontinued the modification of `/dist/` outside of releases.
