### ISSUE TITLE
Collapse tags and models by default

### ISSUE THREAD

**Issue by 1Map** [swagger-api/swagger-ui#3088]
How can I collapse tags and models section by default.  See screenshot:

![image](https://cloud.githubusercontent.com/assets/1152458/26103225/c23f61fa-3a38-11e7-8e00-fba5090a36e7.png)

**Comment by webron** [comment]
We currently do not expose that as a configuration option.

**Comment by urukalo** [comment]
Is there any suggestion how to resolve this elegantly?

**Comment by Cheprer** [comment]
Using the bundle you can specify parameter 'docExpansion'
```javascript
SwaggerUIBundle({
    url: "http://urltoswaggerfile.com",
    dom_id: '#swagger-ui',
    docExpansion: 'none',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  });
```

**Comment by webron** [comment]
Thanks, @Cheprer. With the new config option, this issue can be closed.

**Comment by heldersepu** [comment]
The docExpansion controls both tags and models is there an option for just the models?

**Comment by ddiego2kddl** [comment]
docExpansion: 'none' works fine for me. Thx

**Comment by JS-Java-fullstack** [comment]
I did it by adding the required changes in the swaggerUi. You need to change it as per your requirement as below;

1. docExpansion : "none" - It'll Hide everything.
2. docExpansion : "list"- It'll expand/List all the operations only.
3. docExpansion : "full" - It'll expand everything(Full expand as the name says).

**Comment by BordalloG** [comment]
It may help someone :
applicationBuilder.UseSwagger()
                .UseSwaggerUI(options =>
                {
                    **options.DocExpansion(DocExpansion.None);**
                });
