### ISSUE TITLE
Heroku is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by thysmichels** [swagger-api/swagger-ui#309]
I have a Spring MVC swagger project that is working on localhost but when I deploy it to Heroku I get the following error:

XMLHttpRequest cannot load http://force-com-rest-swagger.herokuapp.com/api/doc/api/v1/account. Origin https://force-com-rest-swagger.herokuapp.com is not allowed by Access-Control-Allow-Origin.

Here is my Swagger js config:

```
$(document).ready(function () {

    displaySwaggerDocuments();

    function displaySwaggerDocuments() {
        var url = '<c:url value="/api/resourceList"/>';
        window.swaggerUi = new SwaggerUi({
            discoveryUrl: url,
            dom_id: "swagger-ui-container",
            supportHeaderParams: false,
            supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
            apiKey: "",
            onComplete: function (swaggerApi, swaggerUi) {
                if (console) {
                    console.log("Loaded SwaggerUI")
                    console.log(swaggerApi);
                    console.log(swaggerUi);
                }
                $('pre code').each(function (i, e) {
                    hljs.highlightBlock(e)
                });
            },
            onFailure: function (data) {
                if (console) {
                    console.log("Unable to Load SwaggerUI");
                    console.log(data);
                }
            },
            docExpansion: "none"
        });

        window.swaggerUi.load();
    }
});
```

Any suggestions?

I tried to set my discoveryUrl to http://force-com-rest-swagger.herokuapp.com/ and also  supportHeaderParams=true but it still gives the same error. 

Any suggestions?

**Comment by SOftEngrAtta** [comment]
i have also getting same issue when i deployed code on heroku 
my server.js file code 

const express = require("express"),
    bodyParser = require("body-parser"),
    morgan = require("morgan"),
    mongoose = require('mongoose');
    jwt = require("jsonwebtoken"),
    expjwt = require("express-jwt"),
    cors = require('cors'),
    app = express();

const { port, mongodbURI } = require("./config");

mongoose
  .connect(mongodbURI, {
    useMongoClient: true
  })
  .then(_ => {
    console.log("mongodb connection connected");
    //listen server
   app.listen(port  || 3000, function() {
        console.log("sms app listening on port : " + port);
    });
  })
  .catch(error => {
    console.error("mongodb connection error: ", error, error.stack);
  });

app.use(cors())


app.use(morgan("dev"));
app.use(bodyParser.urlencoded({
    extended: true
}))
app.use(bodyParser.json());

const authenticationRoutes = require("./app/routes/auth")(app , jwt);
const grnumber = require("./app/routes/gr-number")(app);
const users = require("./app/routes/user")(app);
const feeRoutes = require("./app/routes/fee")(app);
const setupRoutes = require("./app/routes/setups")(app);
const dashboardRoutes = require("./app/routes/dashboard")(app);



app.use("/auth"  , authenticationRoutes);
app.use("/grnumber" , grnumber);
app.use("/users" , users);
app.use("/fee" , feeRoutes);
app.use("/setup" , setupRoutes);
app.use("/dashboard" , dashboardRoutes);


// Handle Unwanted Requests
app.get("*", function(req, res) {
    res.send("sms app server status: RUNNING");
})

// Catch unauthorised errors
app.use(function(err, req, res, next) {
    console.log(err);
    res.status(500).json(err);
});

//authentication middleware
function authenticate(req, res, next) {

    try {
        var user = jwt.verify(req.query['token'], 'mysecret');

        if (user) {
            req.user = user;
            next();
        } else {
            throw 'unauthorised';
        }
    } catch (err) {
        next({
            code: 401,
            message: 'invalid token'
        });
    }

}

And getting error 

Error: 

Failed to load https://git.heroku.com/jeacademy-server.gitdashboard/summary: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 404.

**Comment by webron** [comment]
Commenting on a ticket that was closed 4 years ago will not do you much good. In general, the answer is the same. You need to find a way to enable CORS as suggest above. There's no way around it. We can't help you with Heroku specifically.
