### ISSUE TITLE
Revolver Errors and Resource Get issues

### ISSUE THREAD

**Issue by GianfrancoFrau** [swagger-api/swagger-ui#3090]
When reporting an issue, please provide the following details:
- swagger-ui version: 3.0.10
- a swagger file reproducing the issue: https://n2.vivocha.com/a/gianfranco_n2/api/v2/swagger.json

When I load my swagger.json file I get a bunch of Resolver Error: 
<img width="1242" alt="schermata 2017-05-16 alle 16 23 23" src="https://cloud.githubusercontent.com/assets/5883607/26111012/358c2fec-3a54-11e7-8e39-d02b796480ee.png">
<img width="807" alt="schermata 2017-05-16 alle 16 24 12" src="https://cloud.githubusercontent.com/assets/5883607/26111014/360a822a-3a54-11e7-8c81-3c97325020ab.png">

The resources are parsed correctly:
<img width="972" alt="schermata 2017-05-16 alle 16 25 33" src="https://cloud.githubusercontent.com/assets/5883607/26111041/4e18ddbc-3a54-11e7-8a1f-537dac1b5e93.png">

But when I try to get one: (that doesn't require auth -- NOTE: I'm not using auth because of [#3069](https://github.com/swagger-api/swagger-ui/issues/3069) )
<img width="2048" alt="schermata 2017-05-16 alle 16 28 12" src="https://cloud.githubusercontent.com/assets/5883607/26111178/b7a19c10-3a54-11e7-9450-72a5cd4f5bd9.png">

**Comment by webron** [comment]
Your spec is invalid. You're referencing JSON Schemas which are not supported by the spec. They include keywords that are not allowed such as `$schema`, `oneOf` and so on. It's just not going to work.

**Comment by GianfrancoFrau** [comment]
[$schema](http://json-schema.org/latest/json-schema-core.html#rfc.section.7), [oneOf, anyOf](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.26) and so on, are standard JSON Schema keywords, so we're compliant with the JSON Schema spec.
FYI: [#2667](https://github.com/swagger-api/swagger-ui/issues/2667) using the same swagger.json.

**Comment by webron** [comment]
They are compliant with the JSON Schema spec, they are not compliant with the Swagger/OpenAPI spec which does not allow them.
