### ISSUE TITLE
Can add a function to config the api url suffix?

### ISSUE THREAD

**Issue by chxiaowu** [swagger-api/swagger-ui#3095]
When reporting an issue, please provide the following details:
- swagger-ui version : 2.6.1
- i want a function can config it auto add a ".do" suffix when i "try it out"
![image](https://cloud.githubusercontent.com/assets/3086363/26145837/8dff92aa-3b20-11e7-94b3-4392ce7538a8.png)

**Comment by webron** [comment]
So, there's no version 2.6.1 of swagger-ui...

As for your question, you need to specify that in the API definition, it's not related to the UI.

**Comment by chxiaowu** [comment]
<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.6.1</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.6.1</version>
		</dependency>
Don‘t have version 2.6.1？？？， then what‘s it that I am using,

**Comment by chxiaowu** [comment]
Just fund how to specify  host and port， do you konw how to  specify suffix in swagger ， thanks in advance。

**Comment by chxiaowu** [comment]
Please close this。 i found a way：

`#开发环境
spring:
    profiles: dev
log:
    path: /Volumes/data/logs/envbox-web
    level: INFO    
server:
    port: 8086 
    contextPath: /envbox/v1`


`@Value("${server.contextPath}")
	private String contextPath;

	@Bean
	public Docket createRestApi() {
		Docket docket = new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).host("envbox.valuedaas.com:80")
				.useDefaultResponseMessages(false).pathProvider(new CustRelativePathProvider()).select()
				.apis(RequestHandlerSelectors.basePackage("com.valuedaas.envbox")).paths(PathSelectors.any()).build();
		return docket;
	}

	public class CustRelativePathProvider extends AbstractPathProvider {
		public static final String ROOT = "/";

		@Override
		public String getOperationPath(String operationPath) {
			UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/");
			String uri = removeAdjacentForwardSlashes(uriComponentsBuilder.path(operationPath).build().toString());
			return uri + ".do";
		}

		@Override
		protected String applicationPath() {
			return isNullOrEmpty(contextPath) ? ROOT : contextPath;
		}

		@Override
		protected String getDocumentationPath() {
			return ROOT;
		}
	}`
