### ISSUE TITLE
"Unknown response type" in Firefox 45

### ISSUE THREAD

**Issue by benoitmasson** [swagger-api/swagger-ui#3118]
With the latest SwaggerUI 3.0.10, response body is not shown upon completion in Firefox 45 (with a similar effect to Issues #3021 and #3041, only it happens even in case of success).

The `contentType` property of the `response-body.jsx` component is `undefined`, and thus the body is not displayed.

It works well under Chrome 58.

To reproduce, simply use the sample petstore file.

**Comment by gayanW** [comment]
Not working on firefox-esr either.

**Comment by dlozano** [comment]
Is working with latest OSX 54.0.1 (64-bit)

**Comment by benoitmasson** [comment]
After upgrading my system, it is now working for me with Firefox 52-esr (45-esr was not).

However, I don't expect all my users to have the latest updates, and I am still interested in a fix for this, if anybody has a clue.

**Comment by webron** [comment]
Sorry, I missed the issue when it was opened. We simply don't support FF45, making sure it does will require too much effort which we can't put in. You'd have to update your FF version.
