### ISSUE TITLE
Swagger file upload fails to convert into a UploadedFile object

### ISSUE THREAD

**Issue by jmoon90** [swagger-api/swagger-ui#3123]
swagger-ui version (3.0)

Creating a Swagger doc for my api endpoints. I have a curl command that works in the terminal

`curl -X POST -b "http://localhost:3000/v0/users/4/avatar" -H "accept: application/json" -H "content-type: multipart/form-data" -F avatar=@wolf.b64
`What this returns is an ActionDispatch::Http::UploadedFile object from rails.

However, my swagger doc curl command looks like this

`curl -X POST "http://localhost:3000/v0/users/4/avatar" -H "accept: application/json" -H "content-type: multipart/form-data" -F avatar=wolf.b64`
The avatar param doesn't start with @ which makes it only a string instead of a file.

I need help figuring out how to setup swagger so that @ is added in front of the file name.

This is what my Swagger looks like.

  ```
"post": {
    "tags": [
      "user"
    ],
    "description": "Update user",
    "operationId": "updateUser",
    "produces": [
      "application/json"
    ],
    "consumes": [
      "multipart/form-data"
    ],
    "parameters": [
      {
        "name": "userId",
        "in": "path",
        "description": "ID of the user that needs to be updated",
        "required": true,
        "type": "integer",
        "format": "int64"
      },
      {
        "name": "avatar",
        "in": "formData",
        "description": "Base64 encoded image upload",
        "required": true,
        "type": "file"
      }
    ],
    "responses": {
      "200": {
        "description": "The user avatars was successfully updated"
      },
      "401": {
        "description": "Unauthorized"
      }
    }
  }
},
```

**Comment by jmoon90** [comment]
Any updates?

**Comment by webron** [comment]
@jmoon90 - was in the middle of testing it, and then... life, you know. So, this seems like it's a bug with the curl command generation. Unfortunately, we have to prioritize issues, and it's not at the top of the list.

If you'd like to give it a try yourself and submit a PR, I believe the relevant code can be found in https://github.com/swagger-api/swagger-ui/blob/master/src/core/curlify.js.

**Comment by shockey** [comment]
Closing; the Petstore example of uploading a file with formdata seems to get the `@` prefix now:

<img src='https://shipusercontent.com/ec42a46b483a484ef1861c6b03a50a6e/Pasted%20Image%206.png' title='Pasted Image 6.png' width=822>

@jmoon90, if you're still experiencing this, please bump this thread and I'll reopen!
