### ISSUE TITLE
allOf not working in 3.0.x

### ISSUE THREAD

**Issue by bobvanluijt** [swagger-api/swagger-ui#3127]
When I use `Things` as a response, it does not add the new properties in the UI. In this example that would be `id`.

Response:

```
responses:
  '200':
  description: Successful response.
  schema:
    $ref: '#/definitions/Thing'
```

This seemed to be an issue in the past too.

```
definitions:
  Thing:
    type: object
    properties:
      id:
        type: string
        format: uuid
    allOf:
      - $ref: '#/definitions/ThingCreate'
  ThingCreate:
    properties:
      description:
        description: User readable description of this thing.
        type: string
    type: object
```

_NOTE: It does work in the old editor_

**Comment by webron** [comment]
It's indeed a bug, but you can work around it if you change the definition of `Thing` to:

```yaml
  Thing:
    allOf:
      - $ref: '#/definitions/ThingCreate'
      - type: object
        properties:
          id:
            type: string
            format: uuid
```

**Comment by bobvanluijt** [comment]
Thanks mate :+1:

**Comment by rstraszewski** [comment]
Also have the same problem. Unfortunately swagger file is autogenerated, so I have no way of using this work around.

**Comment by shockey** [comment]
Fixed by https://github.com/swagger-api/swagger-js/pull/1130, which should be released this week 🎉 

![messages image 3246019050](https://user-images.githubusercontent.com/680248/30304242-5a261276-9721-11e7-8c46-dd53b4c4c8ac.png)
