### ISSUE TITLE
Missing translations for oauth "Authorize" button in 2.2.10

### ISSUE THREAD

**Issue by ZuzannaSt** [swagger-api/swagger-ui#3129]
Hi guys, just wanted to point out this small issue. 

Missing translations for oauth "Authorize" button in version 2.2.10.
In following files there is no `data-sw-translate` option set:
https://github.com/swagger-api/swagger-ui/blob/2.x/lib/swagger-oauth.js
https://github.com/swagger-api/swagger-ui/blob/2.x/dist/lib/swagger-oauth.js
and there are no available translations for this action.

**Comment by webron** [comment]
We're not actively maintaining 2.x. If you find an issue, consider submitting a PR to fix it, and we'll look into merging it.
