### ISSUE TITLE
JSONP Support

### ISSUE THREAD

**Issue by AutoSponge** [swagger-api/swagger-ui#313]
I had a need to add JSONP support to the Swagger-UI.  I would appreciated it if someone translated this into coffee and added it.  To use it, make "application/javascript" an acceptable responseType and select it.  If the target API accepts JSONP callback parameters, you'll see the payload and response code.  The headers are faked since you don't have access to them.

Just before the return of OperationView.prototype.submitOperation (currently ln: 1838), add this:

``` javascript
if (opts.responseContentType === "application/javascript") {
    return $.ajax({
        url: decodeURI(this.model.urlify(map)),
        contentType : opts.responseContentType,
        dataType: "jsonp",
        success: (function (showCompleteStatus, parent) {
            return function (data, statusText, request) {
                showCompleteStatus({
                    content: {
                        data: JSON.stringify(data)
                    },
                    status: request.status,
                    getHeaders: function () {return {"Content-Type": "application/javascript"};},
                    request: {
                        url: this.url
                    }
                }, parent);
            };
        }(this.showCompleteStatus, opts.parent)),
        error: (function (showErrorStatus) {
            return function (data) {
                showErrorStatus(data, parent);
            };
        }(this.showErrorStatus, parent))
    });
}
```

**Comment by ava-dylang** [comment]
I would want this, but mostly as a stop-gap for when I would like to play with swagger-ui locally or on a staging host before it gets to its permanent home which should obviously use correct web cross origin acceptance headers since you should be in control of all your hosts generally speaking.
