### ISSUE TITLE
Show Response time for all calls next to Response Body tag.

### ISSUE THREAD

**Issue by csalgo70** [swagger-api/swagger-ui#3135]
Not sure if this is already available or easy to add. It would be very useful to show response time for the calls made on the swashbuckle UI, just like postman shows the response time.

**Comment by webron** [comment]
This is somewhat out of scope for what we're trying to achieve with the UI.

**Comment by shockey** [comment]
FYI, you can measure it now by opening Devtools and catching the API call in the Network tab.

I think this would be nice to have.
