### ISSUE TITLE
Feature request: ability to set oauth2RedirectUrl using env vars in Docker

### ISSUE THREAD

**Issue by shankie-san** [swagger-api/swagger-ui#3138]
Currently, `docker-run.sh` sed's out some placeholders in index.html for env vars that are set when running swagger-ui as a Docker container. This is great; however, there's a need to be able to set `oauth2RedirectUrl` in an environment variable as well – as right now this is 'baked in' to http://localhost:3200/oauth2-redirect.html . 

In #2844 @bodnia suggests changing the constructor of SwaggerUIBundle, which I could obviously do; however, I'd rather use the stock image as it is.

Have you had any thoughts about exposing the config in `swagger-config.yaml` to environment variables?

**Comment by bodnia** [comment]
@shankiesan here is a workaround to use a config plugin for passing any of configs to swagger-ui and re-write existing configs.
All you need to do is to host configs file somewhere in JSON or YAML formats and pass the url to this file as a query parameter `config`. You can read more about it by following the link https://github.com/swagger-api/swagger-ui#configs-plugin
If you have any further questions please let me know.

**Comment by webron** [comment]
@shankiesan does that satisfy your requirements?

**Comment by shankiesan** [comment]
Ah cool thanks @bodnia @webron – it should do what I want! Sorry that I missed that – might be worth explicitly mentioning that in the readme so that lazy people like me who are searching the repo for terms such as `oauth2RedirectUrl` will find what they're looking for 😄 

I'll close the issue for now, but if I run into any problems, I'll come back

**Comment by shankiesan** [comment]
Hmm I'm sure I'll be able to get this to work, but I suppose one disadvantage of this approach is that the oauth2RedirectUrl is likely to be different for different environments (local dev, staging, prod etc), so having this be able to be set by Docker env vars would still be really handy.

From what I can gather, the `docker-run.sh` script is `sed`ing the `index.html` – and it looks like the reason that you haven't allowed it at run-time is that `swagger-config.yaml` is baked in using `webpack` at build time.

Could we have it `sed` `swagger-ui-standalone-preset.js` instead? I might try a fork and see how I get on with that and submit it as a PR if you don't object to the approach in principle. It seems a bit messy as it will break if you ever change the `http://localhost:3200/oauth2-redirect.html` URL; however, it should work.

**Comment by bodnia** [comment]
`swagger-config.yaml` is backed into configs, and changes will not work w/o re-build. But you can just call something like `http://localhost:3200/?config=http://localhost:3200/configs.yaml` 
where `http://localhost:3200/` hosted `index,html` and configs are located `http://localhost:3200/configs.yaml`. These configs will re-write everything from constructor and `swagger-config.yaml`

**Comment by shankiesan** [comment]
Hmm I might be being a newb, but I have swagger running on `http://localhost:8080`, and my config served at `http://localhost:8000/swagger-ui-config.yaml` – so I go to `http://localhost:8080/?configs=http://localhost:8000/swagger-ui-config.yaml` to browse Swagger with my modified configs, and it doesn't appear to load them (nor does it throw an error).

Note that I'm deliberately doing separate ports as :8000 is my Express server (which is also serving `swagger-ui-config.yaml`) – and Swagger UI is running on :8080.

**Comment by bodnia** [comment]
@shankiesan There is a typo, please try http://localhost:8080/?config=http://localhost:8000/swagger-ui-config.yaml

**Comment by shankiesan** [comment]
Thanks @bodnia – that worked. Typos!

What do you think about my use-case for env vars? Your solution worked for now, but these are really environment variables that will change depending on where the app is deployed.

**Comment by bodnia** [comment]
@webron is responsible for feature requests, what do you think about this?

**Comment by webron** [comment]
@shankiesan if you'd like to try to get that to work, sure, that sounds great. Modifying the index.html should be enough because it takes precedence over baked configs. If you do end up submitting a PR for such a change, I'd also ask that you update the README as part of it to explain how it would work for docker users.

**Comment by shankiesan** [comment]
Great, thanks @webron . When you say modifying index.html... do you mean `sed` in the `SwaggerUIBundle` that appears at the end of index.html? If yes, then yeah that shouldn't be too difficult.

Happy to update the readme of course... 😄

**Comment by webron** [comment]
Yeah, I believe that should work, but you know... test, test, test ;)
