### ISSUE TITLE
Models with enum not displaying properly in UI

### ISSUE THREAD

**Issue by fbmattos** [swagger-api/swagger-ui#3139]
Found this using editor.swagger.io

Here's a sample spec:
```
swagger: '2.0'
info:
  version: 1.0.0
  title: temp
paths: {}
definitions:
  model1:
      type: string
      enum:
        - All
        - Enabled
        - Disabled
      default: All
      example: All
```

I expect this to display correctly in the UI/preview tab, but this is what I get:
![image](https://cloud.githubusercontent.com/assets/766336/26502142/9d03383e-4209-11e7-995d-a55d0e07981a.png)

**Comment by webron** [comment]
Thanks @fbmattos. Closing in favor of #2947.
