### ISSUE TITLE
The 18 length Long type appears missing in accuracy

### ISSUE THREAD

**Issue by javanan** [swagger-api/swagger-ui#3141]
db id value is  866950870867243008，

swagger-ui   http://localhost/xx/{id}

response id  866950870867243000    -----  8不见了

**Comment by webron** [comment]
Unfortunately, this is a limitation of Javascript. Not sure if/how we can work around that.

**Comment by johnathan-walker** [comment]
@webron If you don't mind me asking, can you explain the limitation?

**Comment by webron** [comment]
Hopefully this will give you a general idea - https://stackoverflow.com/questions/17320706/javascript-long-integer.

**Comment by hkosova** [comment]
Closing in favor of #2030
