### ISSUE TITLE
How to build and test changes?

### ISSUE THREAD

**Issue by gwynjudd** [swagger-api/swagger-ui#3143]
I'm trying to test out some experimental changes in swagger-ui, but I can't find any documentation on how to build. The readme suggested running this command:

```
npm run dev
```

This creates a server listening on 3200. However it doesn't seem to pick up changes I made in the code base.

**Comment by shockey** [comment]
@gwynjudd, thanks for the feedback, better documentation is definitely on our radar 😄 

`npm run dev` should definitely be picking up your changes. What files have you changed?

**Comment by gwynjudd** [comment]
@shockey sorry please disregard this. It wasn't working as I expected, OR I wasn't noticing, but it turns out it is picking up my changes now.
