### ISSUE TITLE
Update configs system, such that we can add/update swagger-editor settings at runtime.

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#3150]
ping @webron @bodnia @shockey 

So for swagger-editor, it would be nice to control the _ace editor_ options at runtime. I envisaged putting those settings into state, and simply reacting on them ( componentDidRecieveProps => editor.setOptions(...) ). This would allows us to call actions like `editorActions.setOptions({...})` also show the status of certain options ( ReadOnly ) by looking at the state.

@webron mentioned it might be best to ensure _all_ configs behave this way.
Thoughts?

**Comment by shockey** [comment]
So we'd have a set of components that exist to provide interfaces to different non-React parts of the codebase? 

I like this.

**Comment by webron** [comment]
If this is related to **Ace** options only, it might not make sense to scale it out for now, and keep it as an editor-specific configuration. However, even if we do that, it would be good to build it in such a way that it can be propagated to our general config system.

**Comment by shockey** [comment]
Closing this, it exists now :smile:
