### ISSUE TITLE
TypeError: Cannot read property 'operation' of undefined and relative path bug

### ISSUE THREAD

**Issue by julienkosinski** [swagger-api/swagger-ui#3151]
Hello,

With this swagger.json : https://dl.dropboxusercontent.com/s/1eikh4wpldyzet4/swagger-test.json

With 3.0.12 : When trying to send a request to the API (POST for example), I have this error : 

`swagger-ui-bundle.js:68397 Uncaught TypeError: Cannot read property 'operation' of undefined
    at Object.i [as buildRequest] (swagger-ui-bundle.js:68397)
    at swagger-ui-bundle.js:26026
    at swagger-ui-bundle.js:15207
    at swagger-ui-bundle.js:9555
    at swagger-ui-bundle.js:38005
    at Object.r [as executeRequest] (swagger-ui-bundle.js:6562)
    at swagger-ui-bundle.js:26026
    at swagger-ui-bundle.js:15207
    at swagger-ui-bundle.js:9555
    at swagger-ui-bundle.js:71635`

With 3.0.4 : It's working but I need to specify the host (like `"host": "127.0.0.1:8080"`) because relative path isn't working.

Plus, I need to have #2923 fixed for my complete spec.

Thanks :).

**Comment by webron** [comment]
We can't really test it if it doesn't have a `host` defined to test against. When I try it as-is, I just get a CORS error, which is to be expected.

**Comment by julienkosinski** [comment]
Of course... Silly me. I'm going to deploy something as soon as possible to be able to test it.

**Comment by shockey** [comment]
This sounds like https://github.com/swagger-api/swagger-ui/issues/3146, which is pending release on Friday.

If you're up to it, you can try pulling the master branch of swagger-js into your local build of swagger-ui (`npm run build` in swagger-js, then `npm link ../path/to/swagger-js` in ui). 

If that's nonsense to you, tag me here and I'll do a quick deploy of a copy with the fix so you can test it.

**Comment by julienkosinski** [comment]
Ho, great ! :)
I will test it tomorrow when 3.0.13 will be released if that's ok for you, what you say seems not totally nonsense to me but I'm facing some problems to correctly install node right now...

**Comment by shockey** [comment]
Just tested with my final release build for 3.0.13, and this appears fixed.

Please note that petstore.swagger.io will take some time to update (it's manual atm), but you can get the latest version via the `swagger-ui` and `swagger-ui-dist` packages shortly.

I'm closing; please reopen if you have any lingering issues around this!

**Comment by domeniconappo** [comment]
Hi there,
just to let you know, this issue is still happening for Chrome (Version 61.0.3163.100 (Official Build) (64-bit) on Windows 7). It appears for methods where operationId is defined.
Tested with swagger-ui 3.3.0 dist.

Uncaught TypeError: Cannot read property 'operation' of undefined
    at Object.i [as buildRequest] (swagger-ui-bundle.js:56265)
    at swagger-ui-bundle.js:18511
    at swagger-ui-bundle.js:18511
    at swagger-ui-bundle.js:8200
    at swagger-ui-bundle.js:18511
    at Object.r [as executeRequest] (swagger-ui-bundle.js:8200)
    at swagger-ui-bundle.js:18511
    at swagger-ui-bundle.js:18511
    at swagger-ui-bundle.js:8200
    at swagger-ui-bundle.js:69078

**Comment by webron** [comment]
@shockey

**Comment by julienkosinski** [comment]
@domeniconappo I forgot to respond but I don't had the bug anymore last time I checked but it was with previous version.
Thanks for your feedback.
@shockey Thanks for the previous fix which worked for me. :) You can manage (open/close) the issue as needed. Please, for now, see with @domeniconappo for test.

**Comment by domeniconappo** [comment]
Yes, please note that it happens in Chrome while in Firefox there is no issue

**Comment by webron** [comment]
Which version of Chrome?

**Comment by domeniconappo** [comment]
Version 61.0.3163.100 (Official Build) (64-bit) on Windows 7
Read message above:)
 It's the most updated one

**Comment by shockey** [comment]
@domeniconappo, I just tested an operation with an `operationId` defined (one of the Petstore operations) and it worked fine with Swagger-UI 3.3.1 and Chrome 61.

Can you open a new issue and follow the issue template, so we can reproduce the problem you're having? Thanks!

**Comment by domeniconappo** [comment]
@shockey , Thank you for trying.
Sorry, my bad. Just tested again and it works. Yesterday I was testing 3.0.12 and then switched to latest version but probably Chrome's aggressive chaching policy had confused me a bit...
