### ISSUE TITLE
additional params in access token request

### ISSUE THREAD

**Issue by irongomme** [swagger-api/swagger-ui#3154]
- swagger-ui version : 3.0.12

I'm using oauth2 security, and everything works except for the final flow step in access token request. It sends those params : 
  - grant_type:authorization_code
  - code:7uME7iPhH0NhV0XW7OxSm5pMhdSkoI3feEpjIl5R
  - client_id:NTkyYzNiNDJmM2MwODQz
  - client_secret:d53859174eb8d432e5184b82de6b6c67e7139b87

But oauth server needs the redirect_uri in addition to give a good response, otherwise it fails in a 400 error.

How can i make this ? 

I've tried to add additionalQueryStringParams in ui.initOAuth but it doesn't add anything for specific access token request.

**Comment by irongomme** [comment]
Ok, I don't think I need it anymore, because the dev-helpers/oauth2-redirect.html solved my problem by adding redirectUrl to accessToken request headers !

**Comment by webron** [comment]
Thanks for the feedback, @irongomme.
