### ISSUE TITLE
Q: Why does the <Col> component use a "clear" CSS class?

### ISSUE THREAD

**Issue by scottohara** [swagger-api/swagger-ui#3167]
When rendered, the UI produces markup that includes `section` elements with a `clear` class, e.g.

```html
<section class="clear block col-12">...</section>
```

This comes from the `<Col>` component here:
https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/layout-utils.jsx#L76

However I can't see anywhere in the SCSS that `clear` is defined.

This means that if Swagger UI is embedded into a parent page that _does_ define a global `.clear` class, it will use that.

One of my customers has reported a problem where the host application they are embedding Swagger UI into supports 3rd party add-ons.  One of these 3rd party add-ons includes a CSS stylesheet that defines:

```css
.clear {
  clear: both;
  display: block;
  overflow: hidden;
  visibility: hidden;
  width: 0;
  height: 0;
}
```

This means that Swagger UI and this 3rd party add-on are unable to co-exist, because the above CSS hides all `<section class="clear..">` elements rendered by Swagger UI.

As Swagger UI doesn't have it's own definition of `.clear`, I'm wondering why it this class is used in the `<Col>` component; and would it be possible to remove this class?

**Comment by Minasokoni** [comment]
@scottohara the clear seems to be legacy left over from the previous swagger app's html. I will remove it.
