### ISSUE TITLE
Anyway to tell BaseLayout not to expand the model operations by default?

### ISSUE THREAD

**Issue by deostroll** [swagger-api/swagger-ui#3168]
Ui version: 3.0.12.

The standard petstore app shows all model operations to user by default. We are trying to make a custom layout where the default operations for each model is in a collapsed state. Using the example from petstore here is the default state of the app...

![petstore](https://cloud.githubusercontent.com/assets/415336/26711434/decba692-477d-11e7-9d69-9bfad439aee5.png)

In our custom layout we kind of want this collapsed. Again using the petstore reference...

![petstore2](https://cloud.githubusercontent.com/assets/415336/26711458/00c293b4-477e-11e7-8031-720bedfda73d.png)

In the standalone layout, I find that BaseLayout is consumed this way. 

**src/standalone/layout.jsx:(47)**
```
{ !loadingStatus || loadingStatus === "success" && <BaseLayout/> }
```
Is there some way to tell the baselayout to collpase model operations by default? Or is my only approach to write another layout?

**Comment by webron** [comment]
Take a look at https://github.com/swagger-api/swagger-ui/pull/3159.

**Comment by webron** [comment]
This is now in `master`.
