### ISSUE TITLE
Adding a new controller doesn't reflect on the Swagger UI

### ISSUE THREAD

**Issue by gnakkala** [swagger-api/swagger-ui#3177]
Hi

Whenever I add  a new controller to my project and run swagger  UI ,I copy the binaries locally on my machine and copy to  a network location,if I open swagger from localhost it looks fine..the same set of binaries copied to the network location doesnt work,why is that?

I am  swagger-ui version - api version: v1 
- 
```

[assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]

namespace Dashboard
{
    public class SwaggerConfig
    {
        public static void Register()
        {
            var thisAssembly = typeof(SwaggerConfig).Assembly;

            GlobalConfiguration.Configuration 
                .EnableSwagger(c =>
                    {
                     //All commented out code..
                    })
                .EnableSwaggerUi(c =>
                    {
                   //All commented out code..
                   });
        }
    }
}
```

**Comment by webron** [comment]
This is really a question to whatever produces your API definition. Swagger-UI simply loads and displays what is provided to it. If there's an issue of missing artifacts, you should check your generating code.
