### ISSUE TITLE
Show "reguired" in model

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-ui#3186]
Show "reguired" in model, like "optional" are shown. If all fields are required, at the moment is not shown that is required, and is not clear if all fields are required or all fields are optional.

**Comment by webron** [comment]
Which version of swagger-ui do you use? In the current one, "optional" is not shown, and required properties are marked with an asterisk.

**Comment by raderio** [comment]
I use https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui/2.6.1

**Comment by webron** [comment]
That's an old version of swagger-ui. We're not going to change it there. If you want to to see the changes, you'd need to use the latest version.
