### ISSUE TITLE
Curl is generated and Curl is correct.But my Code is Undocumented, Details are TypeError: Failed to fetch, and the Response headers are not content

### ISSUE THREAD

**Issue by LivesMountain** [swagger-api/swagger-ui#3187]
When reporting an issue, please provide the following details:
- swagger-ui version
3v.I downloaded the swagger from the master branch
- a swagger file reproducing the issue
As shown here, when I click Try it out, Curl is generated and Curl is correct.But my Code is Undocumented, Details are TypeError: Failed to fetch, and the Response headers are not content.Please have a look, thanks

I don't know why I can't upload pictures.I'm sorry
![2222](https://user-images.githubusercontent.com/19382017/26857466-4c3fe1ec-4b5d-11e7-81ec-51ab938d60e2.png)

![11](https://user-images.githubusercontent.com/19382017/26857268-0cbd0078-4b5c-11e7-8331-985dc789dd6e.jpg)

**Comment by webron** [comment]
I'm afraid the issue just isn't clear. Can you provide more details?

**Comment by shockey** [comment]
Can you check in the console, for where the request is going? Please provide the exact version you're using as well, you can type `versions` in the console to see what you have.

**Comment by LivesMountain** [comment]
@webron Now I can upload pictures，Please take a look，thank you

**Comment by LivesMountain** [comment]
@shockey Sorry, its version is 3.0.13

**Comment by webron** [comment]
Thanks. Can you check and share with us the error you're getting in your browser's console?

**Comment by LivesMountain** [comment]
@webron I appreciate your prompt reply
The first time I clicked Try it out
![333](https://user-images.githubusercontent.com/19382017/26863189-97ac9b0e-4b83-11e7-9e39-ef60aa33bc44.jpg)
![333330](https://user-images.githubusercontent.com/19382017/26863190-9b918e96-4b83-11e7-90ba-1efe9d921a20.jpg)
After that, the console only has this information
![twice](https://user-images.githubusercontent.com/19382017/26863193-9dd642b4-4b83-11e7-9437-5ceb736b083e.jpg)

**Comment by LivesMountain** [comment]
@webron I've seen you answer other questions about CORS, my "swagger.yaml" file and the "swagger-ui" on the same port under the same IP

**Comment by webron** [comment]
@LivesMountain The CORS applies to two separate things - between swagger-ui and the yaml file, but also between swagger-ui and the application itself. Is the swagger-ui in the same ip and port as the app? If not, you'd need to enable CORS in the application.

**Comment by LivesMountain** [comment]
@webron 
You mean I don't have a CORS between my swagger-ui and app so my "Code = Undocumented" and "Details = TypeError: Failed to fetch"
Ask me what I need to do to solve this problem, whether my swagger-ui Set what parameter, or application needs to support CORS.thank you
Also, can the swagger-ui cancel the CORS mechanism?

**Comment by webron** [comment]
Based on the error in the console, it seems like that's the cause of the issue. I'm afraid the CORS requirement is a browser restriction, and we cannot disable it from swagger-ui.

**Comment by shockey** [comment]
@LivesMountain your application needs to send back `Access-Control-Allow-Origin: *` in order to allow swagger-ui on a different host/port to communicate with it. 

More info here: https://enable-cors.org/server.html

**Comment by LivesMountain** [comment]
@webron @shockey Thank you for your timely reply。The problem has been solved

**Comment by EchoSuzaku** [comment]
I am a novice, without any experience and basic knowledge, finally solved, thanks
