### ISSUE TITLE
Feature request: Syntax Highlighting

### ISSUE THREAD

**Issue by Korri** [swagger-api/swagger-ui#3189]
Swagger 2 had a nice syntax highlighting for json/xml samples.

I might be missing something, but I don't see it in the "Known Issues" section of the `README.md`, is this planned or is there a way to enable it on swagger-ui 3?

**Comment by webron** [comment]
Thanks for bringing it up. As we're focused on OAS3 support, this will not be high on the priority list for now. That said, contributions are always welcome.

**Comment by shockey** [comment]
npm has some nice react components that handle syntax highlighting: https://www.npmjs.com/search?q=react+syntax+highlighting

a community PR that adds this functionality would be wonderful, and not difficult to implement!

**Comment by biggates** [comment]
swagger-ui currently uses [microlight](http://github.com/asvd/microlight) and has a component named `HighlightCode` . I tried to modify it with `highlight.js` and am going through several problems currently:

* highlight.js requires type of language, which is not known yet in this component
* some styles are marked `important` and have to be 
* need to find a way to "alter" component and styles as a plugin
* and a method to avoid `dangerouslySetInnerHTML` (maybe in a react way using [react-lowlight](https://github.com/rexxars/react-lowlight) )

visual effect:

![image](https://user-images.githubusercontent.com/1650579/27480194-9220cbf6-5849-11e7-8c4d-88ffbb57bafc.png)

**Comment by hkosova** [comment]
🎉 Implemented in Swagger UI 3.30.0 (PR https://github.com/swagger-api/swagger-ui/pull/6236).

See also the relevant configuration parameters:
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-syntaxhighlight

**Comment by CodyReichert** [comment]
This works beautifully, thanks to everyone who worked on it. Responses are much more readable now.

Don't mean to be noisy, just wanted to leave some confirmation in the thread for other users searching around. I just upgraded `swagger-ui-bundle.js`/`swagger-ui.css` and voila:

![image](https://user-images.githubusercontent.com/7034627/91585506-c82bf680-e919-11ea-9274-77f8544173ef.png)

The defaults look great.
