### ISSUE TITLE
OAuth2 "password" flow doesn't work with "Request Body" type

### ISSUE THREAD

**Issue by Naid405** [swagger-api/swagger-ui#3191]
- swagger-ui version 3.0.13
- a swagger file reproducing the issue
```
securityDefinitions: {
        OAuth2: {
            type: "oauth2",
            scopes: {
                "api": "API access"
            },
            flow: "password",
            tokenUrl: "/api/v3/oauth/token"
        }
    }
```

If I open the "Authorize" window, type username and password and hit the button it doesn't send the client credentials.
Only after I select other type and select "Request Body" back it start sending client credentials.

**Comment by bodnia** [comment]
@Naid405 the fix is merged to latest master
