### ISSUE TITLE
curl -F bug

### ISSUE THREAD

**Issue by willin** [swagger-api/swagger-ui#3198]
When reporting an issue, please provide the following details:

- swagger-ui version

3.0.10

- a swagger file reproducing the issue

https://github.com/swagger-api/swagger-ui/blob/master/src/core/curlify.js#L21

```js
'/demo/upload': {
  post: {
    responses: {
      200: {
        description: "Success"
      }
    },
    consumes: [
      "multipart/form-data"
    ],
      parameters: [
        {
          type: "string",
          maxLength: 64,
          description: "登录 Auth Token",
          name: "auth",
          in: "formData"
        },
        {
          type: "file",
          description: "要上传的文件",
          name: "file",
          in: "formData",
          'x-mimetype': "image/jpeg, image/png"
        }
      ],
        tags: [
          "demo"
        ]
  }
}
```

![wx20170607-142011](https://user-images.githubusercontent.com/1890238/26866112-54a30546-4b92-11e7-8f1b-aa41b6126c3a.png)

**Comment by shockey** [comment]
I believe this was fixed in https://github.com/swagger-api/swagger-ui/pull/3211.

**Comment by willin** [comment]
tried, nope...

**Comment by shockey** [comment]
@willin, 3.0.14 does not have the fix 😄 

I just deployed the master branch to a static host for you, please try your spec here: http://swagger-ui-master-061417-000820.surge.sh/

**Comment by willin** [comment]
![wx20170614-151257](https://user-images.githubusercontent.com/1890238/27119829-fff59710-50a6-11e7-947c-335fdf0ab13c.png)
![wx20170614-151239](https://user-images.githubusercontent.com/1890238/27119831-029b668e-50a7-11e7-80d1-aa0f19268c8e.png)

**Comment by owenconti** [comment]
Hi @willin, Can you please confirm if this is still an issue? Here is what I am seeing when I use your example spec based off the `master` branch:

<img width="889" alt="screen shot 2017-07-08 at 10 26 12 am" src="https://user-images.githubusercontent.com/791222/27987270-f8f6f632-63c7-11e7-99f3-aa58699dee4f.png">

**Comment by willin** [comment]
```
curl -X POST "http://127.0.0.1:3300/upload" -H "accept: application/json" -H "content-type: multipart/form-data" -F "auth=1111111" -F "file=@grid-18px-masked.png;type=image/png" -F "type=userverify"
```

file upload is now ok.

**Comment by willin** [comment]
#3275 still a trouble.

**Comment by webron** [comment]
Okay, closing this one as fixed then.
