### ISSUE TITLE
Sanitized Markdown causing code examples to be double escaped.

### ISSUE THREAD

**Issue by rswail** [swagger-api/swagger-ui#3199]
swagger-ui branch: master

In a description field I used indented text to display some JSON as code. However, there is a call in ```src/core/components/providers/markdown.jsx``` that sanitizes the source before passing it to Remarkable for display. This causes all of the quotation marks to be escaped. Removing the call in line 6 of the ```markdown.jsx``` file to sanitize fixed the problem (potentially creating an injection security hole).

So the source was (yaml example):

```
description: |
        An example of the first request after connecting would be:

            GET /versions?app=ag

        with the response of:

            200 OK
            {
              "links": {
                "next": null,
                "previous": null
              },
```
However, the HTML generated becomes:

![screen shot 2017-06-08 at 02 18 25](https://user-images.githubusercontent.com/245183/26889241-e1a6549e-4bf0-11e7-9dd5-d9eb946c217c.png)

**Comment by webron** [comment]
Whoops. Thanks for reporting

**Comment by shockey** [comment]
Looks like https://github.com/punkave/sanitize-html/issues/96 is the way forward here.

**Comment by shockey** [comment]
this should be fixed! thanks for raising the issue @rswail.

you can expect the fix to go live in the next version of swagger-ui, to be released this friday.
