### ISSUE TITLE
Hide param

### ISSUE THREAD

**Issue by livia19** [swagger-api/swagger-ui#3201]
what should I do If I don't want the unitID appear in the   APIs? 

@ApiImplicitParams({@ApiImplicitParam(name = "req", required = true, dataType = "XXXX")})
public XXXX<XXXX> Function(@RequestAttribute("unitID") String unitID, @Valid @RequestBody XXXX req) {}

**Comment by webron** [comment]
This is not a swagger-ui question. Based on the code you shared, it looks like you need to take it to Springfox.
