### ISSUE TITLE
operationId is off by one, and the first repeats itself

### ISSUE THREAD

**Issue by Celadora** [swagger-api/swagger-ui#3203]
- swagger-ui version 
3.0.13
- swagger file reproducing the issue 
http://petstore.swagger.io/v2/swagger.json

Set displayOperationId to true, and notice that the operationId's are all off by one, except the first one, which is repeated.

![swaggeruibug](https://user-images.githubusercontent.com/13486978/26915701-f6216f0e-4bdb-11e7-9351-22e3afed6635.png)

Thank you for checking this out!

**Comment by webron** [comment]
@alexkravets - can you take a look at this please? We're scheduled to make a release late tomorrow, and it should be resolved by then. If we can't get it fixed, we might need to revert the change until next week's release.

**Comment by alexkravets** [comment]
Yes, we'll have a look into this.

**Comment by Celadora** [comment]
For now, the easiest solution is to change line 136 in operation.jsx from:

```
let operationId = operation.get("__originalOperationId")
```

to

```
let operationId = operation.get("operationId")
```

However, there will remain the problem of '__originalOperationId' being inaccurate.

Thank you!

**Comment by shockey** [comment]
Fixed this upstream! I'll release these changes to npm later today.

**Comment by shockey** [comment]
Thanks for the help, @Celadora & @alexkravets!
