### ISSUE TITLE
No operations defined in spec! 

### ISSUE THREAD

**Issue by mithilesh-g** [swagger-api/swagger-ui#3205]
Hi, Explored almost all and tried but still not able to solve. 
Swagger UI with JAVA play framework. 
- swagger-ui version : 3.0.13
http://localhost:9000/docs/swagger.json this in browser giving the required json but through swagger-ui it is producing the following message.
**No operations defined in spec!**  
Got stuck whit below situation. 
Thanks
![swagger1](https://user-images.githubusercontent.com/27721394/26925135-2de48a54-4c66-11e7-940a-e88e0e39ccf4.png)
![swagger2](https://user-images.githubusercontent.com/27721394/26925136-2def9d4a-4c66-11e7-987e-eb4bfcc6feab.png)

**Comment by webron** [comment]
You're using the 3.x version of swagger-ui which supports only Swagger 2.0. The definition you have is version 1.2 Either downgrade the UI to 2.x or upgrade the library you use to output 2.0.

**Comment by mithilesh-g** [comment]
Thanks @webron . We were able to solve that with the solution you provided.
But now facing a different error.
I have created a new issue with the link at https://github.com/swagger-api/swagger-play/issues/141
Can you please have a look.

thanks
Mithilesh

**Comment by maliqiang** [comment]
@webron The lasted jar of swagger-springmvc is 1.0.2.Can you give a guid to resolve the problem?thanks.

**Comment by webron** [comment]
Upgrade to the latest version. You're using a very old one.

**Comment by prativapokhrel** [comment]
@webron worked like magic! thanks!! :+1:
