### ISSUE TITLE
Tag Object description not respecting multi-line literals in swagger-editor

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-ui#3208]
_From @derekdecesare on June 8, 2017 7:15_

We cannot incorporate line breaks into the description field for tags.  All other description fields respect markdown and multi-line literals.  This is really hampering readability of our tags for the APIs.

Example:

tags:
  - name: item
    description: | 
      To Do - Create a tag for each resource in your api and tag the operations that relate to that resource. 
      Provide the documentation for the resource in the description of the tag.  
      The following views are supported by this resource. 
      - complete, includes all fields.
      - summary, includes only id, descriptor, name and description. 
      - otherView, includes only id, primaryCategory and secondaryCategories.

_Copied from original issue: swagger-api/swagger-editor#1356_

**Comment by webron** [comment]
Moving this to swagger-ui as this is a rendering issue.

**Comment by webron** [comment]
The current implementation of swagger-ui treats the tags as a single line. 

@derekdecesare - how do you envision it being rendered, considering the collapse/expand is at the tag level?

**Comment by 3flex** [comment]
To chime in here since I just came across the same issue - it might be best to have a summary and a description for each tag. That way the summary would be displayed next to the path at all times, and the description would show when the tag is expanded.

This would be consistent with how paths render.

An alternative would be to rename "description" on the tag to "summary" which implies a single line is appropriate.

**Comment by heldersepu** [comment]
@3flex rename would be a bad break on backwards compatibility, I would strongly advise against it!

@webron I guess the Spec should be reworded to let everyone know this is a single line field:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#tagObject

Field Name | Type | Description
---|:---:|---
<a name="tagName"></a>name | `string` | **Required.** The name of the tag.
<a name="tagDescription"></a>description | `string` | A short description for the tag. [GFM syntax](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) can be used for rich text representation.
<a name="tagExternalDocs"></a>externalDocs | [External Documentation Object](#externalDocumentationObject) | Additional external documentation for this tag.

Also the GFM syntax does not seem to be working, maybe is not supported:
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=ArrayTest

**Comment by shockey** [comment]
Looks like this is resolved in the UI:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/680248/62594555-eb5bb200-b88f-11e9-8fb2-0033d6e4f493.png">

I agree with the merits of a `summary` and `description` field, but that's a task for OpenAPI, not Swagger UI.

Thanks everybody!
