### ISSUE TITLE
Authentication mechanism in swagger UI 3.0.13

### ISSUE THREAD

**Issue by siddamreddy** [swagger-api/swagger-ui#3215]
When reporting an issue, please provide the following details:
- swagger-ui version -3.0.13
- Required Authentication mechanism in swagger UI 3.0.13

Currently I am using below Authentication for Swager 2.1.4. I need Authentication samples in swagger 3.0.13 version. please help on this.
 setAuthenticationToken(swagUI, token) {
         var auth1 = new SwaggerClient.ApiKeyAuthorization("x-ionapi-docrequest", "SWAGGER", "header");
         swagUI.api.clientAuthorizations.add("x-ionapi-docrequest", auth1);

         var auth2 = new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + token, "header");
         swagUI.api.clientAuthorizations.add("Authorization", auth2);
     }

Regards
Naga

**Comment by webron** [comment]
This is currently not supported in 3.x. There are numerous opened tickets about it already.

**Comment by siddamreddy** [comment]
Any idea when it will be implemented

**Comment by webron** [comment]
We're working on it, no ETA.

**Comment by siddamreddy** [comment]
Approximately how many days it will take so that I convey same to my
manager I have close this requirement ASAP

**Comment by webron** [comment]
I don't have an answer to that.

**Comment by siddamreddy** [comment]
Any rough estimate

**Comment by webron** [comment]
No.

**Comment by siddamreddy** [comment]
Any update

**Comment by webron** [comment]
We'll update when we have an update.

**Comment by siddamreddy** [comment]
any update on this
