### ISSUE TITLE
authorization header is set as `bearer ....` instead of `Bearer ...`

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [swagger-api/swagger-ui#3216]
When reporting an issue, please provide the following details:
- swagger-ui version: 3.0.13
- a swagger file reproducing the issue: 

I'm implementing OAuth2 and authorization part goes fine. However, the authorization header is set as `bearer ....` instead of `Bearer ...`, which is rejected by oauth2-server.

![auth](https://user-images.githubusercontent.com/11527341/26972216-155b9a3a-4d11-11e7-98c8-59ec4cc4cfa4.png)

**Comment by josiasmontag** [comment]
Caused by [this issue](https://github.com/swagger-api/swagger-js/issues/1040).

**Comment by webron** [comment]
Please follow the upstream linked issue.
