### ISSUE TITLE
Which one is the working version with dropdown functionality ?

### ISSUE THREAD

**Issue by dipak84patel** [swagger-api/swagger-ui#3231]
I am having hard time finding the right version that you guys have created that has dropdown functionality. I am new to HTML and Java-Script and i would say that my knowledge in both of these languages are not very good. I am currently working on swagger UI and was looking to see if there were any projects that has spec choser drop down functionality. Looks like you guys have made that working. I would appreciate if you guys can provide step by step information such as branch name, how to save files in code ? and how to test the dropdown functionality ? I would appreciate it !

**Comment by webron** [comment]
We never provided a drop down functionality of choosing a spec. Some people have brought it up in previous tickets, and may have provided their own solutions. I think there's also a discussion to add that functionality to the current UI, but it is not yet implemented or available.

**Comment by dipak84patel** [comment]
Okay thank you. Meanwhile i will get myself familiar with front-end stuff.
