### ISSUE TITLE
Integrating swagger-ui with Azure AD OAuth, working but not gracefully

### ISSUE THREAD

**Issue by Calrain** [swagger-api/swagger-ui#3234]
Using swagger-ui@3.0.14

When authenticating with Azure AD OAuth, the goal is to use the OAuth2 authentication of swagger-ui to retrieve an access token from Azure, which will be added as an HTTP header variable to all REST API calls.

It was quite difficult to find the right parameters and settings required to get Azure accepting the OAuth token requests, but in the end Azure is accepting the info being sent to it and Azure returns a Bearer token.

When the Bearer token comes back it comes as a URL Param in the form of:
`http://localhost:3000/swagger/#access_token=eyJ[...]RQ&token_type=Bearer&expires_in=3599&state=VHV[..]ZSk%3d&session_state=3c7[..]04a`

The problem is that I can't then easily grab the access_token value and add it as an apiKey value in future REST API calls.

My work around has been to create two securityDefinitions such as:
```
securityDefinitions: {
  "OAuth2": {
    "type": "oauth2",
    "authorizationUrl": "https://login.microsoftonline.com/d[..snip..]5/oauth2/authorize",
    "flow": "implicit",
    "scopes": {
      "user_impersonation": "Access myAppName"
    }
  },
  "Bearer": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
  }
}
```
In the security definition of a REST API endpoint I do this:
```
security: [
  {
    "Bearer": []
  }
]
```

So when someone uses the Swagger UI for the first time, they click the green `Authorise` button and then Authorize against OAuth2.

A new page then opens at Azure, and Azure does a login and bounces you back to the swagger UI page. 

e.g. `http://localhost:3000/swagger/#access_token=eyJ[...]RQ&token_type=Bearer&expires_in=3599&state=VHV[..]ZSk%3d&session_state=3c7[..]04a`

Then when someone wants to authenticate on a REST API call, they click the padlock beside the end point and they have to manually copy the `access_token` value from the URL, and paste it into the Bearer apiKey value in the format of `Bearer {paste in access_token}`.

Is there any way we could reference a URL parameter in an apiKey definition?

All I need to do is a have some ability to do:
```
  "Bearer": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header",
    "value": "Bearer " + url.param.access_token
  }
```

I know that can't go in the securityDefinitions, but some ability to do that would be great.

I've tried referencing functions in the index.html of the swagger-ui, but can't work out how to do it programmatically, though I can extract the value of the access_token URL parameter.

Is there any way to dynamically build the value for apiKey through some hook in index.html of the swagger-ui?

I know there are lots of questions in this space around authentication, at least this question may help others trying to integrate with Azure AD OAuth.

**Comment by webron** [comment]
A little bit confused - if you do regular OAuth2 authentication for the calls, why do you manually add a Bearer token authentication in the form of an `apiKey` security? Simply say that the operation requires the oauth flow, authenticate, and swagger-ui will send the bearer token in the relevant calls.

**Comment by Calrain** [comment]
When I use OAuth2, Azure returns the Bearer token to swagger-ui as a parameter in the url query string. Then as I open up the REST endpoints in swagger-ui, and click Execute, swagger-ui can't attach the Bearer token to the curl command when calling the REST endpoint.

The addition of the apiKey is the only way I can get swagger-ui to add the 'Authorization' = 'Bearer nnnn' value to the REST call. The REST Endpoint requires that key/value in the HTTP header.

Maybe I'm missing something with how to pass HTTP header variables.

I'm close, as the Bearer token is sitting in the URL, I just can't get each REST API call to take that value and add it as an HTTP Header variable when calling the REST service.

**Comment by webron** [comment]
Good morning, Australia ;) 

Put the Curl command aside for a moment - does the execution itself work?

Also, any chance your app is publicly accessible so I could take a look? You don't have to share it in the ticket, you can send me the details in an email if you prefer to keep it more private.

**Comment by Calrain** [comment]
Good morning :)

Unfortunately I can't open the app right now, but:
- The core application is an AngularJS SPA that is hosted within Node.js, the Node.js app also hosts many REST API endpoints and uses Azure AD for user authentication.
- The Node.js REST API expects users to have an 'Authorization': 'Bearer xxxx' key in their HTTP Header and it validates that Bearer token every invokation.
- The Node.js app is connected to an Azure AD Application space, with users etc.
- There is a link in the SPA to launch the Swagger-UI, which is a standalone app also hosted by the Node.js server. When someone clicks on the 'Swagger' link in the app it launches Swagger-UI in a new window.
- The Swagger-UI app has it's own application space in Azure AD, with permission within Azure AD to use the application space that the REST API is in.
- When someone clicks the green 'Authorize' button in Swagger-UI and you click OAuth2 authorization, it opens a new window to Azure, which does the user id/password challenge, and then bounces the user back to the Swagger-UI URL, but with the token information included in the URL.
- The browser now has the Bearer token it needs to add to the REST API calls, via the HTTP Header in the format `Authorization = Bearer {insert token here}`, but it's as a URL query string with the name `access_token`.
- Within the index.html file for the swagger-ui I can parse out the token value, but can't inject that into all future CURL commands that the swagger-ui screen makes.
- So to fudge it, I added an `apiKey` security definition for each REST API endpoint, and when the users clicks the padlock beside the REST API they can manually add `Bearer {insert token here}` and click Authorize. That way when they call the web service it will add the Authorization HTTP header, and it works.

The issues are that the user has to manually copy/paste the bearer token, and after 10 minutes the bearer token will expire, but the key issue is I would love to have a way to automatically add the bearer token in.

**Comment by webron** [comment]
I'm having to step away from the computer for a bit, so instead of going back and forth, I'll write a few extra details so hopefully you can triage the case further.

To make sure we're on the same page - you pretty much have an app, that depends on Azure AD as an OAuth provider to perform user authentication. You're not doing some magic where you have two separate processes where you have one side of the app perform the authentication, and then you move that token somehow to another part of the app and use that for as long as you can. That's my assumption. Based on the definition you shared, you are using the `implicit` flow of OAuth2, which should be well supported by Swagger-UI.

Now, a standard part of the OAuth2 flow is that the provider returns the token. Assuming Azure AD is compliant with the OAuth2 spec (I assume it does, and can verify with someone from Azure if needed), we should have no problem extracting that access token ourselves, as the spec specifies, and provide it to all subsequent requests.

I'm not saying what you're trying to do shouldn't be supported (and with the current version of Swagger-UI I admit it may _not_ be supported) - however, I'm saying it's most likely that you don't need it at all.

Based on your `securityDefinitons` above, have you tried setting the `security` of the REST API endpoint as the following instead of what you have:

```json
security: [
  {
    "OAuth2": []
  }
]
```

Once authenticated, that should simply take the access_token and send to it the endpoints as part of the request (included the `Bearer` part). I don't know if you've tried that without success, or maybe you didn't realize that's how it's supposed to work. Please provide further feedback (or try and provide the feedback) and we'll take it from there.

**Comment by Calrain** [comment]
Thanks for that, I updated the security part of the REST API endpoint to be that and I'm still having the problem of the Bearer token not being added to the REST calls.

Is there somewhere in the swagger-ui config where I need to say which URL Query Parameter is mapped to the `Authorization = Bearer {token}` HTTP header?

When Azure returns the token it is called `access_token` and it is missing the `Bearer ` prefix that it needs. Azure also returns another key value pair in the URL called `token_type = Bearer`.

It's almost that inside the index.html for the swagger-ui I want to parse the values of `access_token` and `token_type` and then set an HTTP header variable called `Authorization = token_type + " "  + access_token`.

**Comment by Calrain** [comment]
Looking at the Swashbuckle implementation of Swagger, they have an interesting function they can define in their index.html file that looks like this:
```
(function () {
    function addApiKeyAuthorization() {
        var key = $('#input_apiKey')[0].value;
        if (key && key.trim() != "") {
            var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization(swashbuckleConfig.apiKeyName, key, swashbuckleConfig.apiKeyIn);
            window.swaggerUi.api.clientAuthorizations.add("api_key", apiKeyAuth);
            log("added key " + key);
        }
    }
    $('#input_apiKey').change(addApiKeyAuthorization);
})();
```
This was taken from [this StackOverflow question](https://stackoverflow.com/questions/39009758/enable-bearer-token-in-swashbuckle-swagger-document).

Within the index.html file of swagger-ui we have access to some Javascript objects called `SwaggerUIBundle` and `SwaggerUIStandalonePreset` but they don't have methods to allow addition of additional HTTP Header parameters for calls out to REST APIs.

That could be a good way of solving this issue, then every developer can just add additional HTTP Header variables in exactly the format they need, in the swagger-ui index.html file.

**Comment by Calrain** [comment]
Does anyone know if there is a way to dynamically modify clientAuthorizations as in the example in the previous comment, with swagger-ui?

**Comment by Calrain** [comment]
Can close this request.

I've had to downgrade to Swagger-UI 2.x, it works very well with Azure OAuth integration with automatic Bearer token insertion.

Look forward to when Swagger-UI 3.x improves OAuth integration!
