### ISSUE TITLE
What versions of the Swagger spec does Swagger UI support?

### ISSUE THREAD

**Issue by tomjohnson1492** [swagger-api/swagger-ui#3237]
Does Swagger UI 3.0 support the (upcoming) 3.0 version of the Swagger spec?

**Comment by webron** [comment]
It will. We're working on the support for it. Please follow #3083 which also has a link to the working branch.

**Comment by tomjohnson1492** [comment]
Thanks. It might be good to indicate on the Swagger UI 3.0 homepage a note that indicates the version it supports. I was confused by this and thought that UI 3.0 was updated to match spec 3.0.

**Comment by webron** [comment]
That's a fair point, @tomjohnson1492, but it's already there.... https://github.com/swagger-api/swagger-ui#compatibility.

**Comment by tomjohnson1492** [comment]
agghhh, I missed it. Awesome that it's there! Thanks.

**Comment by webron** [comment]
No worries, @tomjohnson1492. We appreciate you watching our back. Keep the feedback coming.
