### ISSUE TITLE
Localization and translation for 3.x？

### ISSUE THREAD

**Issue by kliyes** [swagger-api/swagger-ui#3240]
Hey guys, is there any way to do localization and translation for version 3.x ? In 2.x, we could add lines in index.html like this:
```html
<script src='lang/translator.js' type='text/javascript'></script>
<script src='lang/en.js' type='text/javascript'></script>
```
 but how about 3.x?

**Comment by webron** [comment]
It's not yet supported in 3.X. See [Known Issues](https://github.com/swagger-api/swagger-ui#known-issues).

**Comment by kliyes** [comment]
Hmm...okay

**Comment by webron** [comment]
Closing in favor of #2488.

**Comment by obender** [comment]
Hi, 
We wold like to implement that feature and contribute it, any guide how to do so?
