### ISSUE TITLE
How to set header

### ISSUE THREAD

**Issue by javanan** [swagger-api/swagger-ui#3243]
- swagger-ui version   2.7.0

How to set header

![6 vrbg0n 3 t f3y 957](https://user-images.githubusercontent.com/8219648/27163051-7c38388a-51b7-11e7-9942-5fa7c3dff1a0.png)

![5i zxm mxel i5z pegpr](https://user-images.githubusercontent.com/8219648/27163079-a3c2ccda-51b7-11e7-886d-b816fa279212.png)

**Comment by webron** [comment]
There's no swagger-ui 2.7.0. I don't know what version that is, but it's not the current one. You can look at https://github.com/swagger-api/swagger-ui/issues/818 to find more details how to set bearer tokens in that version.
