### ISSUE TITLE
Create a `wrapComponents`, to replace components

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#3245]
The idea being able to replace components, while getting passed the original component. So that we can extend the UI simply.

@shockey I believe you've got the implementation somewhere.

**Comment by shockey** [comment]
I do have an implementation in the OAS3 branch, which should hit master in the next couple weeks, when we do 3.1. IMO it should be introduced in the 3.1 series.

If there's an immediate need for the feature, I can cherry-pick it out of the OAS3 branch.

**Comment by ponelat** [comment]
@shockey could you link to the oas branch? I might be able to grab it out there, if you don't have the time.

**Comment by shockey** [comment]
This is on master now 😄
