### ISSUE TITLE
Limit in size of the swagger supported with 3.x release?

### ISSUE THREAD

**Issue by erajkovic** [swagger-api/swagger-ui#3247]
Hi,

While testing the migration from an old version (2.x) to the latest available, I found an issue with some swagger documents. The UI remains in 'Loading...' forever and eventually timeout in chrome. with a pop-up that title is 'Page Unresponsive'. I have tried to use the "Wait" option a few times, but it did not complete.
After a few seconds, the UI does confirm that the swagger is valid by rendering the "VALID" green UI element.

![swagger-ui-loading-forever](https://user-images.githubusercontent.com/4298647/27198095-ac6053f4-51c5-11e7-8dcd-8e14d54cba76.png)

To reproduce you can try this link:
http://petstore.swagger.io/?url=https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/commerce166/v1/apis/store/canonical
 
Thanks,
-Eric

**Comment by webron** [comment]
Thanks for the report. The API definition is quite large - 4.3MB so I'm not surprised it's slow, but it shouldn't be this slow. I'm attaching it here so we can investigate further even if the URL is no longer valid.

When https://github.com/swagger-api/swagger-ui/pull/3196 is merged, it could help with the loading of the file, but it's more a workaround than a fix.

[swagger1.json.txt](https://github.com/swagger-api/swagger-ui/files/1079006/swagger1.json.txt)

**Comment by owenconti** [comment]
Hi @erajkovic, are you still experiencing this issue with your example link? http://petstore.swagger.io/?url=https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/commerce166/v1/apis/store/canonical

It seems to load the spec in ~3500ms.

<img width="850" alt="screen shot 2017-07-22 at 4 49 04 pm" src="https://user-images.githubusercontent.com/791222/28495025-b8e1adb2-6efd-11e7-954a-2b84a8e6c538.png">

**Comment by erajkovic** [comment]
Yes, it looks like the issue is now resolved. 
Not sure if this is related to the release of 3.0 or if there was some other change that would explain the improvement.
Going to try to get an update version into our project to see if it's also improving for our integrated use case
https://apicatalog.oraclecloud.com/ui/views/apicollection/oracle-public/commerce166/v1

**Comment by erajkovic** [comment]
Closing the issue as it's now working OK with the latest public version of the UI.
