### ISSUE TITLE
swagger-ui does not add context root and application path to try out url

### ISSUE THREAD

**Issue by starinfor** [swagger-api/swagger-ui#3248]
When reporting an issue, please provide the following details:
- swagger-ui version 3.x as per readme file
- a swagger file reproducing the issue

**Comment by webron** [comment]
Can you provide a file that reproduces the issue?

**Comment by starinfor** [comment]
swagger.json is accessible at <host>:<port>/contextroot/applicationpath/swagger.json

[swagger.txt](https://github.com/swagger-api/swagger-ui/files/1080027/swagger.txt)

Attached is swagger.json

**Comment by webron** [comment]
The `basePath` in your swagger.json isn't set correctly - it's set to the root of your server. You need to make sure it points to the context root of your app.

**Comment by starinfor** [comment]
That resolved my issue. Thanks
