### ISSUE TITLE
Required Parameters in Model View?

### ISSUE THREAD

**Issue by MSW613** [swagger-api/swagger-ui#3255]
Using OpenApi from ServiceStack, [on their forums, I was told this is a Swagger UI issue](https://forums.servicestack.net/t/issues-with-v4-5-11/4121/10).  I have an API that receives a call with about 100 fields via json in the body of the call.  Some are required and most are not.  I am looking for a way that the information about what fields are required/optional can be visible to the end user and also, the end user can use the "Try it out" functionality with the json object as well (as opposed to manually filling out 100 separate fields).  

For the sake of illustration, lets use the following:

```
public class HelloDto
    {
        [ApiMember(IsRequired = true)]
        public string Name { get; set; }
        [ApiMember(IsRequired = false)]
        public List<string> Colors { get; set; }
//another 98 fields here
    }
```

Here is what I have tried so far and the results:

- Having the HelloDto object be the top level request.  In Swagger UI, this renders individual rows for each property, where it is clearly displayed what is required and what is optional.  At the bottom of the list there is a body DTO which allows a cut & paste of the full object for ease of testing.  However, in this case, when you "Try it out!" the UI complains that you haven't filled out any of the required fields from above.  Additionally, the Model View next to that DTO object shows the required fields as optional.

- Having the HelloDto object be a property of the top level object, set to be a Body parameter.  This way, the UI just shows the DTO (without 100 rows of individual fields) but, as above, the Model View of that DTO shows all the fields are optional.  Additionally, the json generated by the UI, is not correct as it only generates the DTO level json, which, when you click "Try it out!" doesn't submit the full json object the API is expecting.

- Having the HelloDto object be a property of the top level object, set to be a Model parameter.  This is an improvement over the previous option in that the complete json is correctly generated, however the main issue of the required fields showing as optional in the model view remains.  

I must say that I would be shocked that Swagger UI doesn't support display of required properties in the Model View as one of the primary purposes of the UI is to provide user documentation, and not knowing which fields are required or not seems like a tragic shortcoming.  In general, I know this is possible as I have seen Swagger documentation that shows this, but apparently that was only on v3 according to the Service Stack team.  I am hoping this is just an issue with them not generating the json correctly.

Below is the json generated by ServiceStack.OpenApi when using the 3rd option above if it helps:
`{"swagger":"2.0","info":{"title":"OpenApiIssues","version":"1.0"},"host":"127.0.0.1:8088","basePath":"/","schemes":["http"],"consumes":["application/json"],"produces":["application/json"],"paths":{"/annotated-hello":{"post":{"tags":["annotated-hello"],"summary":"Creates a new hello.","description":"Creates a new hello.","operationId":"CreateHelloReq_Post","consumes":["application/x-www-form-urlencoded"],"produces":["application/json"],"parameters":[{"name":"Hello","in":"method","schema":{"$ref":"#/definitions/HelloDto"},"required":false},{"name":"Name","in":"formData","type":"string","required":true},{"name":"Colors","in":"formData","type":"array","items":{"type":"string"},"collectionFormat":"multi","required":false},{"name":"body","in":"body","schema":{"$ref":"#/definitions/CreateHelloReq"}}],"responses":{"default":{"description":"","schema":{"title":"String","type":"string"}}},"deprecated":false},"parameters":[{"$ref":"#/parameters/Accept"}]}},"definitions":{"Object":{"properties":{},"description":"Object","type":"object"},"CreateHelloReq":{"title":"CreateHelloReq","properties":{"Hello":{"$ref":"#/definitions/HelloDto","required":false},"Name":{"type":"string","required":true},"Colors":{"type":"array","items":{"type":"string"},"required":false}},"description":"CreateHelloReq","type":"object"},"HelloDto":{"title":"HelloDto","properties":{"Name":{"type":"string","required":true},"Colors":{"type":"array","items":{"type":"string"},"required":false}},"description":"HelloDto","type":"object"}},"parameters":{"Accept":{"name":"Accept","in":"header","description":"Accept Header","type":"string","required":true,"enum":["application/json"]}},"securityDefinitions":{"basic":{"type":"basic"}},"tags":[{"name":"annotated-hello"}]}`

**Comment by webron** [comment]
Like you said, it's supported in swagger-ui 3.X, so I'm not sure what's the issue...

**Comment by MSW613** [comment]
The issue is that there are apparently some major problems with v3, so Service Stack isn't distributing it yet.

In any event, for anyone interested, the issue was that there is a bug in SwaggerUI v2 which doesn't respect the required field on a property and instead there needs to be an array of the required properties in an object at the top of that object.  ServiceStack updated their code to output this list and now SwaggerUI v2 correctly recognizes required fields.

**Comment by webron** [comment]
Okay, it doesn't like there's anything left for us to do. 'Major problems with v3' isn't helpful, not to you, not to us. If anyone from that team wants to work with us on being aware of the major problems and communicate with us on how to help resolve those, we'd be glad for the opportunity.

Other than that, I'm going to close the ticket for now. Please reopen if you think anything else can be done.
