### ISSUE TITLE
JSON gets minified and escaped in responses > examples property

### ISSUE THREAD

**Issue by tomjohnson1492** [swagger-api/swagger-ui#3256]
When I add an `examples` property in the responses object, the example code gets minified. Additionally, if I use `>` or `|` to break the content onto the next line, the JSON gets both minified and escaped. (Ron says the minification is a known bug but not the escaping.)
 
Here's an example: http://idratherassets.com/restapicourse/swaggercomplete/. Expand Weather Data, then look for the "400" Response (test operation). (This comes after the 200 example.) See how the JSON is minified and escaped? Here's a screenshot: https://www.screencast.com/t/hmjVTdPUgMh

If I remove the `>`, then the JSON is minified only: https://www.screencast.com/t/d1eawyVSPsp

The code should neither be minified nor escaped here. If you look at the YAML file (http://idratherassets.com/restapicourse/swaggercomplete/swagger_weather.yml), search for "400:" and you'll see that the JSON is not minified or escaped there. Here's the relevant part of the code:

```
400:
         description: "Test operation"
         examples:
            application/json: >
              {
               "query": {
```
Thanks.

**Comment by shockey** [comment]
This should be fixed in `master`.

Thanks for reporting this bug, @tomjohnson1492!

**Comment by tomjohnson1492** [comment]
Awesome! Thanks for fixing this.
