### ISSUE TITLE
Set the contents of the interface document

### ISSUE THREAD

**Issue by fuquanli** [swagger-api/swagger-ui#3268]
Hi,dear friend.
I have a question that requires your help!
I want to generate interface documentation according to my own wishes,rather than generate all.
I only need a part.
certainly，I know using HiddenApiFilter,but it can not satisfy me.
Because i have part of the interface that does not follow RESTful.
![image](https://user-images.githubusercontent.com/25790404/27371210-69e465d4-5692-11e7-860b-334d757135d4.png)

**Comment by fuquanli** [comment]
I use .net core 2.0,
There are special requirements, need to configure some interface address ".aspx"

**Comment by webron** [comment]
This is not a question for this project. Most likely you're looking for [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle).

**Comment by fuquanli** [comment]
thank you
