### ISSUE TITLE
Show response model instead of example value by default

### ISSUE THREAD

**Issue by roben** [swagger-api/swagger-ui#3269]
It would be great to have an option to show the models in the responses section instead of example values by default, because the example values do not contain model property comments, as JSON does not support them.

**Comment by heldersepu** [comment]
Isn't the [defaultModelRendering](https://github.com/swagger-api/swagger-ui/search?utf8=%E2%9C%93&q=defaultModelRendering&type=) doing that?

**Comment by webron** [comment]
Good catch, @heldersepu! The functionality was added after the ticket was opened. Can be closed!
