### ISSUE TITLE
swagger-ui input text box for body parameters of type string is unusable

### ISSUE THREAD

**Issue by davidmfrey** [swagger-api/swagger-ui#3271]
## Specs
* Swagger spec version 2.0
* Swagger-UI   docker image swaggerapi/swagger-ui  v3.0.5 . a228b9ff44b6

## Problem
I have some older endpoints which accept newline delimited strings which I'm trying define in a swagger spec.

The spec looks like this:
```
post: {
  tags: [
    "NLP"
  ],
  summary: "",
  description: "NLP parse one or more sentences passed in the body of the request",
  operationId: "postNLPParse",
  consumes: [
    "text/plain: charset=utf8"
  ],
  produces: [
    "application/json; charset=utf8"
  ],
  parameters: [
    {
      name: "sentences",
      in: "body",
      description: "Newline delimited sentences",
      required: true,
      schema: {
        type: "string"
      },
    }
  ],
  responses: {
    200: {
      description: "Success",
      schema: {
        $ref: "#/definitions/nlpResponse"
      }
    }
  }
}
```

## Desired solution
Ideally, I would like to be able to edit the string sent as the body in the swagger-ui for testing and demonstration.  However the input text box will not allow spaces or newlines and treats the input as if it should be a JSON object ( forces the first character to be a '{' ). 
<img width="647" alt="screen shot 2017-06-21 at 9 59 50 am" src="https://user-images.githubusercontent.com/3163539/27388117-9d169fbe-5668-11e7-8ed4-755b9ad82950.png">
 Is there anything I can modify in the spec to get around this limitation?

Apologies if this has been addressed somewhere already, I've searched for it and can't find it.

**Comment by webron** [comment]
Not sure how we didn't notice this one until now, but it's definitely not good.

**Comment by webron** [comment]
It's there, it's just a `string`.

**Comment by shockey** [comment]
![image](https://user-images.githubusercontent.com/680248/27396613-5f3cac42-5668-11e7-9116-aadc79044482.png)

I'm not able to reproduce this using editor.swagger.io, which is running Swagger-UI 3.0.14 (you're a few releases behind!). The `sentences` parameter appears as `"string"` in Try-It-Out, and  I'm able to add spaces and newlines to the input.

**Comment by davidmfrey** [comment]
I'll update my swagger-ui to 3.0.14 and try it.

**Comment by webron** [comment]
@shockey I was able to reproduce it with swagger-ui master 😕

**Comment by davidmfrey** [comment]
Yeah, I just updated to 3.0.14 and it's still happening.

**Comment by shockey** [comment]
@davidmfrey, can you provide a full spec that reproduces the issue? I shoehorned your fragment into an existing spec, that may be the source of the inconsistency.

**Comment by davidmfrey** [comment]
@shockey can I email you the spec?  I couldn't find any private message capability on github.

**Comment by shockey** [comment]
@davidmfrey sure, kyleshockey@gmail.com.

**Comment by shockey** [comment]
I see it now, thanks @davidmfrey 😄
