### ISSUE TITLE
Oauth scope not showing in popup ui

### ISSUE THREAD

**Issue by figuerres** [swagger-api/swagger-ui#3272]
When reporting an issue, please provide the following details:
- swagger-ui v2.2.10
I am using a package that uses the swagger ui package.
the Oauth Scopes where shown in the UI in a prior version but are not shown in the current release.

https://github.com/domaindrivendev/Swashbuckle/issues/1118#issuecomment-310095051

the swagger.json file has the oauth settings and the token server url and flow are working just not the scopes.

here is a frgment of the json:

`  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "description": "OAuth2 Implicit Flow",
      "flow": "implicit",
      "authorizationUrl": "https://xxxxxxxxxxxx.com/id/connect/authorize",
      "tokenUrl": "https://xxxxxxxxxxx.com/id/connect/token",
      "scopes": {
        "read": "Read access to protected resources",
        "write": "Write access to protected resources"
      }
    }
  },
  "security": [],
  "tags": []`

no scopes or checkboxes are shown in the popup

trying to work out why they are not working with the package update, the rest of the settings are seen, just not the scopes collection.

**Comment by webron** [comment]
What about the `security` definitions across the spec? Do they ever use any of the scopes?

**Comment by figuerres** [comment]
here is a sample from the huge json file of one api method call:

`   "/api/ActivateObject/Address": {
      "post": {
        "tags": [
          "ActivateObject"
        ],
        "summary": "",
        "operationId": "ActivateObject_Address",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "Item",
            "in": "body",
            "description": "",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ADL.Web.Services.Models.DeleteObjectBindingModel"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          }
        },
        "security": [
          {
            "oauth2": [
              ""
            ]
          }
        ]
      }
    },`

is that what you are asking about ??

**Comment by figuerres** [comment]
did a check with the prior build of my api and the json for that part is the same, so that did not change  when the package was updated.

if i can't get oauth working i am going to have to roll back my project to use the older package version until this is figured out.

**Comment by webron** [comment]
If you look at what you shared, you have `"security": [ { "oauth2": [ "" ] } ]` which means no scopes are needed for that API call - there's nothing to render there.

**Comment by figuerres** [comment]
Ok so then this sounds like the swashbuckle tool that generates the json has a bug that in prior versions of the swagger ui did not cause a problem.

so i need to list the scopes required in that fragment to tell the swagger ui which scopes are needed for this method ?

can we have a default that allows the current json to work ??

**Comment by webron** [comment]
No, this is how the spec works.
I'd also suggest trying the latest version of the UI to see if it behaves differently for you.

**Comment by figuerres** [comment]
to recap:  
is this what my json should look like:
"security": [ { "oauth2": [ "read" , "write" ] } ]

given the scopes i listed before ?

**Comment by webron** [comment]
Assuming those are the scopes you need, yes.

**Comment by figuerres** [comment]
ok, thanks...
i will report this to the project and see what we can do to fix it.

working on a test fix so that i can verify this....

**Comment by figuerres** [comment]
yes that was the problem and now i can fix my app!!!
thanks @webron  for your help in idenifiying the source of the problem!!
