### ISSUE TITLE
Implementing swagger-ui

### ISSUE THREAD

**Issue by juanda99** [swagger-api/swagger-ui#3278]
- swagger-ui version: 3.0.16
- a swagger file reproducing the issue: https://api.arasaac.org/arasaac.json

I've looked through #3000.
My error is: Dynamic page loading failed Error: only one instance of babel-polyfill is allowed

You can have a look at https://beta2.arasaac.org/pictograms/api

@ponelat, I guess it will be solved with next release and [your commit replacing babel polyfill](https://github.com/swagger-api/swagger-ui/commit/4a6716ffed3f71c24f7d2e94ed206895691552f2)?

**Comment by ponelat** [comment]
yeah the babel-polyfill migration ( to transform-runtime ) is in `master`. Still need to ensure swagger-editor is happy with that, before cutting a release ( hopefully within a few days ).

**Comment by juanda99** [comment]
Ok, thank you. Waiting for it!

**Comment by juanda99** [comment]
Error fixed  with 3.017
