### ISSUE TITLE
"undefined" description if there's no description key

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3279]
Specs without `info.description` and parameters without `description` are displayed with "undefined" description.

The issue did not exist in 3.0.12 release (39501c8) but exists in 3.0.14 release (f23b704) and in the latest master.

Spec:
```
swagger: "2.0"
info:
  version: "1.0"
  title: test
paths:
  /:
    get:
      parameters:
        - name: foo
          in: query
          type: string
      responses:
        200:
          description: OK
```

![undefined](https://user-images.githubusercontent.com/8576823/27436246-4b9485c0-5767-11e7-8a86-a0c7346858a0.png)

**Comment by shockey** [comment]
Appears to be caused by https://github.com/swagger-api/swagger-ui/pull/3165.
