### ISSUE TITLE
Swagger UI is sending wrong Accept header [Produces, text/plain, application/json]

### ISSUE THREAD

**Issue by croraf** [swagger-api/swagger-ui#3282]
I set `produces ` to `application/json`, and try to use swagger UI to send a get request. But Swagger UI is sending `text/plain` `Accept `header.

![image](https://user-images.githubusercontent.com/19698636/27456391-2f3cef7c-57a1-11e7-9184-36b2170b03be.png)

What is even more strange, in devtools Network tab it is shown that `Accept: application/json` was sent.

![image](https://user-images.githubusercontent.com/19698636/27456511-a2277b10-57a1-11e7-981e-1172cd0a86f6.png)

And in devtools Console tab I get the following message:

![image](https://user-images.githubusercontent.com/19698636/27456539-c2af61a4-57a1-11e7-83c8-0cadea810ef7.png)

The same error message is shown when I try to access this resource from the browser URL bar (but there I cannot set the Accept header).

swagger-ui version: 2.2.10

I tried all possible combinations in the swagger file, here is the relevant excerpt. `/login` path works fine.
```
swagger: '2.0'
info:
  version: 1.0.0
  title: Whole
  description: >
    Swagger
consumes:
  - application/json
  - text/plain
produces: [application/json]
basePath: '/api'
paths:
  /login:
    post:
      tags: [Login]
      description: Receives login credentials and returns token if credentials are valid
      parameters:
        - name: credentials
          in: body
          description: Credentials object with username and password
          required: true
          schema:
            $ref: '#/definitions/credentials'
      responses:
        '200':
          description: Valid token
          schema:
            $ref: "#/definitions/token"
        default:
          description: unexpected error
          schema:
            type: object
  /ingredients:
    get:
      tags: [Ingredients]
      description: Retrieves a list
      parameters: []
      responses:
        '200':
          description: Array of ingredients
          schema:
            type: array
            items:
              type: string
```

Similar issue is this one, but was closed without discussion: #2450
NOTE: I'm using node.js swagger2-koa to bind swagger.

**Comment by croraf** [comment]
Swager-UI Server doesn't consume application/json, try [ ] #2450

**Comment by croraf** [comment]
#2450

**Comment by webron** [comment]
The other issue was closed because there was no reply from the author.

Have you tried the latest version of swagger-ui?

**Comment by croraf** [comment]
Yes, I saw that he didn't reply :(.
I'm using a library that installed swagger-ui. This is the latest v2 of swagger-ui.
Don't know if I can use v3 of swagger-ui as it is major revision change.

**Comment by croraf** [comment]
I changed GET to POST and it works fine. It obviously does not recognize to put Accept to correct type for GET.

**Comment by webron** [comment]
You can always work around any swagger-ui that's installed via a library. First I would suggest to just clone this repo and run it locally, directing at the API definition generated by that library and see if it works.

**Comment by croraf** [comment]
I installed latest swagger-ui instead of the one installed by the library. 
1. It complains to update create-react-class to 15.5.3 or newer, I have 15.6.0 or something...
2. It complains UNMET react, I didnt have one. It didint install. I installed manually.
3. It complains UNMET webpack, I didnt have one. It didnt install. I installed latest v2, as directed manually.
Still doesn't work.

Don't really know how to do that, I will have to point Swagger-UI to some server, and to do that I used that library, and also to load yml into swagger I used that library.

Can you check if GET that needs application/json response works with 2.2.10 or 3.0.16. You can use my excerpt to test it.

**Comment by webron** [comment]
I tested with the current UI and the snippet you provided. Both the GET and POST produce the right headers.

**Comment by croraf** [comment]
Then maybe the issue is with swagger2-koa library. I referenced the issue there.

**Comment by croraf** [comment]
The issue was related to my use of the library. Issue reference can be found above.
