### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by markkolich** [swagger-api/swagger-ui#3284]
Swagger UI version: `3.0.16`

I must be doing something wrong.

Here's the JS error according to the console (Chrome 59.0.3071.104):

```
swagger-ui-bundle.js:37 TypeError: Cannot read property 'get' of undefined
    at t.value (swagger-ui-bundle.js:80)
    at t.I.n.render (swagger-ui-bundle.js:37)
    at p._renderValidatedComponentWithoutOwnerOrContext (swagger-ui-bundle.js:58)
    at p._renderValidatedComponent (swagger-ui-bundle.js:58)
    at p._updateRenderedComponent (swagger-ui-bundle.js:58)
    at p._performComponentUpdate (swagger-ui-bundle.js:58)
    at p.updateComponent (swagger-ui-bundle.js:58)
    at p.receiveComponent (swagger-ui-bundle.js:58)
    at Object.receiveComponent (swagger-ui-bundle.js:43)
    at Object.updateChildren (swagger-ui-bundle.js:58)
```

Here's my `swagger.json` as served by `http://localhost:9001/api/swagger.json` (yes, lots of blank/empty fields, just trying to get something working):

```json
{
    "basePath": "/api",
    "definitions": {},
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "host": "",
    "info": {
        "contact": {
            "email": "",
            "name": "",
            "url": ""
        },
        "description": "",
        "title": "",
        "version": ""
    },
    "paths": {
        "/foo/bar": {
            "get": {
                "description": "",
                "produces": [
                    "application/json"
                ],
                "protocol": [],
                "summary": "",
                "tags": [
                    ""
                ]
            }
        }
    },
    "schemes": [
        "HTTP"
    ],
    "swagger": "2.0",
    "tags": [
        {
            "description": "",
            "name": ""
        }
    ]
}
```

This does not appear to be a CORS issue &mdash; I'm hosting Swagger UI on the same host/port as the API endpoint I'm trying to consume (`localhost:9001`):

![image](https://user-images.githubusercontent.com/1202420/27465382-0d6ed888-5788-11e7-9d6e-ab0cbb0f60de.png)

Clicking "Try it out" followed by "Execute" results in the `TypeError: Cannot read property 'get' of undefined` error above with an annoyingly cute `😱 Could not render this component, see the console.` in Swagger UI.

The JSON response I see from my API endpoint looks like this (as captured by Chrome dev tools):

```json
{
  "result": [
    {
      "id": "A",
      "description": "Foo"
    },
    {
      "id": "V",
      "description": "Bar"
    },
    {
      "id": "X",
      "description": "Foo"
    },
    {
      "id": "P",
      "description": "Bar"
    },
    {
      "id": "S",
      "description": "Foo"
    },
    {
      "id": "T",
      "description": "Bar"
    }
  ],
  "success": true
}
```

Chrome reports the `GET:/api/foo/bar` as a 200 OK:

![image](https://user-images.githubusercontent.com/1202420/27465655-be412c50-5789-11e7-9944-b353751a0d61.png)

What am I doing wrong?

**Comment by webron** [comment]
OH MY GOD YOU BROKE THE UI!!! :scream:

Just kidding.

So here's the thing... the definition file you provided is not really valid. And by 'not really', I mean pretty much broken. I'd suggest pasting the file into https://editor.swagger.io, fixing the issues and trying again. If the issue persists, let us know.

**Comment by markkolich** [comment]
@webron \<sigh/>

Yeah, ok.

I confirmed this is caused by my "invalid" `swagger.json` definition.  Per your suggestion I whack-a-mole'd out all of the discrepancies using https://editor.swagger.io.  With all of the kinks ironed out, my "hello, world" example definition is working now with Swagger UI 3.0.16.  Thanks for the pointer.

Fwiw, I'm not using any of the off the shelf tools to generate my definition (e.g., `swagger-jaxrs`).  I'm confined to generating the definition myself scanning my controllers and assembling the definition based on `swagger-annotations`.

That said, I find it slightly odd that `swagger-annotations` uses default values that don't pass basic validation.  For instance, in my original definition I had this:

```json
schemes: [
  "HTTP"
],
```

When in fact, what passes validation at https://editor.swagger.io is this (lowercase "http"):


```json
schemes: [
  "http"
],
```

The former came from using the default `@SwaggerDefinition(schemes = Scheme.HTTP)` annotation on my swagger controller.  In other words, the `schemes` field of the `@SwaggerDefinition` annotation only allow me to specify `DEFAULT`, `HTTP`, `HTTPS`, `WS`, `WSS` &mdash; none of which pass validation, as-is in their uppercase form according to https://editor.swagger.io.

Is it expected that such definition values as provided by `swagger-annotations` don't pass validation as-is and require additional massaging, such as lowercasing the values?  There is no documentation or mention of this in the `io.swagger.annotations` package that I could find.

Note `@SwaggerDefinition(schemes = Scheme.HTTP)` was just one example.  There were a few other similar values I had problems with as well.

CC // @fehguy

**Comment by webron** [comment]
It's just a matter of how we serialize the annotations in the Reader classes that we have, or rather how we build the Swagger model classes (which also use uppercase notation) which we then serialize We could add the lowercase values there, but that's not really an issue.

The annotations are meant to help us build the structure, not necessarily a 1:1 translation.

**Comment by markkolich** [comment]
Eh, fair enough.

Thanks for the help!
