### ISSUE TITLE
Required integer query parameter with default 0 invalidates "Try it out" form with value of 0

### ISSUE THREAD

**Issue by petejohnson84** [swagger-api/swagger-ui#3299]
- 3.0.16
```
swagger: "2.0"
info:
  description: "This is a sample server Petstore server."
  version: "1.0.0"
  title: "Swagger Petstore"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "http"
paths:
  /pet:
    get:
      summary: "Get pet"
      description: ""
      operationId: "addPet"
      parameters:
      - name: "offset"
        in: "query"
        type: "integer"
        format: "int32"
        description: "offset"
        required: true
        default: 0
      responses:
        405:
          description: "Invalid input"
```
Note that removing the default and entering value 0 will allow the form to be submitted without problem.

![screen shot 2017-06-26 at 2 49 15 pm](https://user-images.githubusercontent.com/16767811/27561606-10ec8acc-5a86-11e7-8a83-f4e96917570d.png)

**Comment by owenconti** [comment]
I have a PR for this. Just need to add a couple tests before I submit it.

**Comment by petejohnson84** [comment]
This issue appears to be occurring again in v3.4.3.

**Comment by shockey** [comment]
@petejohnson84, yeah I see it too. Investigating now!

**Comment by shockey** [comment]
Just merged a fix for this.

Sorry for the inconvenience, @petejohnson84! The fix will be released tonight.
