### ISSUE TITLE
content-type not working

### ISSUE THREAD

**Issue by nevercodealone** [swagger-api/swagger-ui#3301]
I my api application i can not find the content type in headers

```
swagger: "2.0"
info:
  title: Super API
  description: API description for the silex connector to elasticsearch.
  version: 1.0.0

host: something.com:9001
basePath: /v1
schemes:
  - http
produces:
  - application/json
  - text/html
paths:
  /getData:
    post:
      summary: This route is used on the TYPO3 backend to handle very flexible requests.
      consumes:
        - application/json
        - text/html
      parameters:
        - in: body
          name: Get entity
          description: This is only an example. There are much more possibilities.
          schema:
            type: object
            required:
              - source
              - token
            properties:
              source:
                type: string
                example: something
              token:
                type: string
                example: testify
              table:
                type: string
                example: columnname
      responses:
        200:
          description: Json data.
```

**Comment by webron** [comment]
The issue isn't clear. What steps are you taking, what result do you see, and what do you expect to see?

**Comment by nevercodealone** [comment]
The problem is that the POST on the getData route as no content-type in the header information. I use a silex php API and use 

`if (0 === strpos($request->headers->get('Content-Type'), 'application/json')) {...}`

on the beginning. When i check this part with xdebug there is no content-type set. So my application can not read the data from the request.

**Comment by webron** [comment]
The header is there, although in lowercase (headers are case-insensitive). Check your browser's network console when you execute the call and you should see it there. It seems like the problem is with your code.

**Comment by nevercodealone** [comment]
No it is not there - here are screens from xdebug and console - on postman everything is fine

<img width="799" alt="console" src="https://user-images.githubusercontent.com/17619862/27645808-5a23e148-5c27-11e7-835b-3f258e8c715d.png">

![xdebug](https://user-images.githubusercontent.com/17619862/27645817-60202692-5c27-11e7-8249-d5cb6f39ba5f.png)

**Comment by webron** [comment]
Check the request itself, it's probably an OPTIONS call and not a POST. This is the preflight request done by your browser. If it doesn't work, it suggests that you haven't enabled CORS in your app.

**Comment by nevercodealone** [comment]
CORS are enabled

`$app->register(new CorsServiceProvider, array(
    "cors.allowOrigin" => "http://something.dev",
    "cors.allowMethods" => "GET, POST, OPTIONS"
));`

Otherwise nothing would work. And on postman everything works fine

<img width="603" alt="bildschirmfoto 2017-06-28 um 17 57 08" src="https://user-images.githubusercontent.com/17619862/27647270-3f4dcdc6-5c2b-11e7-80bf-bd8723a1c271.png">

**Comment by webron** [comment]
Postman doesn't require CORS to be enabled.

That piece of code doesn't mean anything to me. Can you take a screenshot of your entire network console when you execute the call?

**Comment by nevercodealone** [comment]
Tomorrow i will do

Am 28.06.2017 6:06 nachm. schrieb "Ron" <notifications@github.com>:

Postman doesn't require CORS to be enabled.

That piece of code doesn't mean anything to me. Can you take a screenshot
of your entire network console when you execute the call?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/swagger-api/swagger-ui/issues/3301#issuecomment-311707981>,
or mute the thread

**Comment by nevercodealone** [comment]
So here we go...the 500 comes because the application can not read any data

![bildschirmfoto 2017-06-29 um 10 32 55](https://user-images.githubusercontent.com/17619862/27678964-6b1d2244-5cb7-11e7-93ab-361a942bdc2d.png)

**Comment by webron** [comment]
That's still a CORS issue as it's an OPTION call. I have no idea why your web server is returning 500 for that, you'd need to investigate it.

**Comment by nevercodealone** [comment]
Ok for now i use Slate for API doc. So I do not know when I can check this.
Every client application and postman is working fine. Only swagger is not
working. So it was easier to change the docu system. You can close the
ticket, when you belive the issue is on my side ;)

But the issue is that swagger is not sending the header information. That
do you also see on the last screen.

2017-06-29 17:32 GMT+02:00 Ron <notifications@github.com>:

**Comment by webron** [comment]
There's no need to send the Content-Type header for OPTIONS call, there's no payload.

**Comment by nevercodealone** [comment]
Ok maybe you do not understand the problem. I want to do a post request. For this i need the content-type in the headers

`paths:
  /getData:
    post:`

As you see in the first post

**Comment by webron** [comment]
I know you want to do a POST request. But before you can, the preflight OPTIONS has to succeed (as a CORS requirement) and that fails. It's got nothing to do with the `content-type` header of the POST request.

**Comment by nevercodealone** [comment]
Ok thanks - you can close the ticket

2017-06-29 21:09 GMT+02:00 Ron <notifications@github.com>:
