### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-ui#3305]
Not an issue but a thank you. We integrated the latest swagger-ui into our developer portal about 3 weeks ago and we've received a lot of great, positive, unsolicited feedback. The new look is really nice, and there are a lot of really cool features that have helped out our consumers. Getting the curl with one click is just one of them. The customization features have been great, too. I've been able to add in a lot of extra things that we have in our specs and now it's all seamless.

**Comment by fehguy** [comment]
@jaydreyer thanks for taking the time to write this.  It really helps the team feel good about the hard work they put into this project!

**Comment by webron** [comment]
@jaydreyer Thanks! It's feedback like this that keeps us going 😄

**Comment by webron** [comment]
Thanks again for the feedback :) Closing just as part of a regular issue cleanup process.
