### ISSUE TITLE
It's possible to configure nested model in query string?

### ISSUE THREAD

**Issue by soulkoden** [swagger-api/swagger-ui#3308]
I have a model description in query string. 

Example query: 
```curl -X POST /my-api?objects[0][id]=2&objects[1][id]=40```. 

Configuration:

```
/**
 * @SWG\Parameter(
 *     name="objects[]",
 *     in="query",
 *     type="array",
 *     @SWG\Items(
 *         ???
 *     ),
 *     collectionFormat="multi",
 * )
 */
```

It's possible to configure in Swagger UI on annotations at this time? Type `object` with model description is no allowed for `query` or did I misunderstood it? 

I correctly understand that this is done using the `@Property` inside `@Items`? If so, how does this relate to each other?

**Comment by webron** [comment]
Version 2.0 of the spec doesn't support it, the next version of the spec will.
