### ISSUE TITLE
Omit host&basepath from spec

### ISSUE THREAD

**Issue by pohckuan** [swagger-api/swagger-ui#3321]
This is what I have in my load-api.json file, 
is there a way to put a dynamic host and basePath in this file instead of the spec? 

window.onload = function() {
  // Build a system
  const ui = SwaggerUIBundle({
    url: "xxxxxxxxxx",
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}

**Comment by webron** [comment]
It's not implemented yet. Please follow https://github.com/swagger-api/swagger-js/issues/1045 for progress.
