### ISSUE TITLE
Shemes dropdown should be hidden if there is only one option

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3326]
The Shemes dropdown should be hidden if there is only one option.
The ```<div class="scheme-container">``` takes close to 100px of prime screen "real estate" and there is no use for it if there is only one option in the dropdown

- swagger-ui version
3.x
- a swagger file reproducing the issue
http://turoapi.azurewebsites.net/swagger/docs/V1

**Comment by shockey** [comment]
I think it's still useful as an indicator of the scheme - without it, you'd need to execute a request to see the scheme being used.

**Comment by heldersepu** [comment]
But is it worth the prime space?
![image](https://user-images.githubusercontent.com/545474/27793392-d460e5e4-5fcb-11e7-91c9-fdd5abac3127.png)
Maybe it should be combined on the same row as the title...

**Comment by webron** [comment]
It's there for documentation purpose and will not be hidden by default. The bar is also used to show authentication if that exists. You're welcome to customize the UI and remove it if you'd rather not show it.
