### ISSUE TITLE
Swagger-ui not accepting JSON security prefix

### ISSUE THREAD

**Issue by denyseflo** [swagger-api/swagger-ui#3327]
Hello !
I'm using Swagger-ui version 3.0.17 but for security reasons, I have a JSON prefix (")]}',\n") on every HTTP requests. 
So when I try to load the Swagger-ui interface with the link http://baseUrl/swagger/index.html , I get an error : 
![swagger error](https://user-images.githubusercontent.com/12645814/27798592-21164dac-6012-11e7-841c-50f6c9b6fe8c.png)

If I click on the "error {...}" button, I get the message : 
`{"schemaValidationMessages":[{"level":"error","message":"Can't read from file /api-docs"}]}`

Here is the code where the JSON prefix is added : 
`<message-converters register-defaults="true">`
`	<beans:bean`
`		class="fr.icdc.dei.fwk.web.converter.MappingJackson2HttpMessageConverter">`
`		<beans:property name="objectMapper" ref="safeJsonObjectMapper" />`
`		<beans:property name="prefixJson" value="true" />`
`		<beans:property name="jsonPrefix" value=")]}',\n" />`
`	</beans:bean>`
`</message-converters>`

Is there any way to make Swagger-ui understand JSON with specific prefix ? 
Thanks for your help :)

**Comment by webron** [comment]
We don't support this right now. Either exclude it from your config, or load the YAML variant instead.

**Comment by denyseflo** [comment]
OK, thanks for your answer !

**Comment by jay8t6** [comment]
@webron can you let me know how it can be done using YAML variant?
