### ISSUE TITLE
Duplicate CSS

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3329]
- swagger-ui version
3.x
- a swagger file reproducing the issue
http://petstore.swagger.io/

I'm in the process of updating Swashbuckle with swagger-ui 3.x an I noticed that the CSS for the ```input.download-url-input``` shows duplicate style in the developer tools, it seems one is from a <style> in the body and the other from the .css file.

![image](https://user-images.githubusercontent.com/545474/27804795-e1884c20-5ffe-11e7-9497-aa109614075d.png)

**Comment by shockey** [comment]
Confirmed. At first look, it appears that `style-loader` and `extract-text-webpack-plugin` are doing double duty, so the styles get packed into the bundle _and_ included as a standalone file.

**Comment by heldersepu** [comment]
Awesome! will test it out after you guys do the Rebuild dist

**Comment by heldersepu** [comment]
Awesome! it works as intended with 3.0.20 !
