### ISSUE TITLE
Duplicate arrows in comboboxes in Chrome and Firefox

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3334]
Swagger UI version: 69420d8559976462279dba5dc3cf7e26c163aedd / master as of July 4 (but 3.0.17 release did not have the issue)
Chrome 59, Firefox 54 on Windows 7

All combo boxes (for `schemes`, MIME type, enums, `urls`, etc.) have duplicate arrows:
![combobox-arrows](https://user-images.githubusercontent.com/8576823/27822927-06a4dc60-60b0-11e7-911c-61596a29244e.png)

In 3.0.17, `<select>` had these CSS rules:
```
.swagger-ui select {
  ...
  -webkit-appearance: none;
  -moz-appearance: none;
  ...
}
```
but they are missing in the latest master.

**Comment by webron** [comment]
@owenconti can you look into this one?

**Comment by heldersepu** [comment]
I just updated to latest and I still have the Duplicate arrows...

the CSS rules:
```css
.swagger-ui select {
  ...
  -webkit-appearance: none;
  -moz-appearance: none;
  ...
}
```
are still missing in the latest

**Comment by owenconti** [comment]
@heldersepu latest release or latest from `master`?

**Comment by hkosova** [comment]
@heldersepu if you are looking at the standalone files in `dist`, they were not rebuilt yet.

**Comment by heldersepu** [comment]
Yes i got latest from master.
... was expecting that now that the issue is closed the standalone files will also be updated. 
I don't have an environment to build this project yet, I guess I should do that...
