### ISSUE TITLE
sending API key as query parameter?

### ISSUE THREAD

**Issue by emckean** [swagger-api/swagger-ui#3337]
In swagger-ui 2.0 this works to add an api key as a query param: 

```
authorizations: {
          api_key: new SwaggerClient.ApiKeyAuthorization("api_key", '<%=data.config.developerKey%>', "query")
        },
```
In swagger-ui 3.0 I think that this *should* be the right syntax but it does not add the api key as a query param: 

`ui.authActions.authorize({api_key: {name: "api_key", schema: {type: "apiKey", in: "query", name: "api_key"}, value: '<%=data.config.developerKey%>'}});`

The security definition in the OAS spec is: 

```
"securityDefinitions": {
    "api_key":{
          "type": "apiKey",
          "name": "api_key",
          "in": "query"}
  },
```
What am I missing? Any suggestions gratefully received. 

I should add that I'm opening this as an issue b/c I think the lack of documentation is the issue. If you tell me what it should be I will write it up and fix it. :)

**Comment by webron** [comment]
@emckean are you trying to set a 'fixed' value for the api key?

**Comment by emckean** [comment]
Yes, exactly :)

**Comment by shockey** [comment]
This will be supported in https://github.com/swagger-api/swagger-ui/issues/2915. Closing

**Comment by shatestest** [comment]
@webron @emckean  can you please let me know what is the solution here.
I am also facing same issue, earlier i used to use swagger 1.2 v now i am using version 2.0
Now it is not working with same code....how should i change the code to fix it. 
below is what i have , what am i missing here.

"authorizations": {
    "api_key": {
      "type": "apiKey",
      "passAs": "qwerty",
	   "in": "query",
      "name": "api_key"
    }
	},

https://stackoverflow.com/questions/49050969/setting-swagger-apikey-in-version-2-0

**Comment by emckean** [comment]
Sorry, I reverted to 2.0 :) 

Do you have something that looks like this?

````json
"securityDefinitions": {
    "api_key":{
          "type": "apiKey",
          "name": "api_key",
          "in": "query"}
  },
  "security": [
      { "apiKey": [] }
    ],
````

**Comment by shatestest** [comment]
yes.
but no use. like the below

  "components": {
     "securitySchemes": {
  "ApiKeyAuth": {
"type": "apiKey",
"in": "query",
"name": "apiKey"
  }
}
  },
  "security": [
{
  "ApiKeyAuth": [ 'qwerty' ]
}
  ],

**Comment by shatestest** [comment]
https://stackoverflow.com/questions/49050969/setting-swagger-apikey-in-version-3-0
