### ISSUE TITLE
Swagger UI showing empty screen with the JSON file

### ISSUE THREAD

**Issue by krishnachaitanya511** [swagger-api/swagger-ui#3341]
When reporting an issue, please provide the following details:
- 2.X
[index.html.txt](https://github.com/swagger-api/swagger-ui/files/1124408/index.html.txt)

I have a list of APIs in a swagger file. I tried opening the URL using the browser but it's showing an empty screen with the JSON file. But If I use the YAML it's working and showing the APIs. 

Could someone please help me with this issue?

**Comment by webron** [comment]
would be hard without the JSON file...

**Comment by shockey** [comment]
@krishnachaitanya511, bump - can you provide a spec that demonstrates the issue you're having?

**Comment by krishnachaitanya511** [comment]
Hello,

We already have a setup which is reading the yaml file and display the API
information in the browser. And I have changed my index.html and pointed it
to the JSon file. But the page shows empty screen with JSON. Any idea about
this?

**Comment by shockey** [comment]
Hmm, I don't know of any issues that would cause raw JSON to be displayed in Swagger-UI. We officially support the loading of both JSON and YAML. 

It sounds like you're saying the JSON and YAML are equivalent, is this correct?

> I have changed my index.html and pointed it to the JSon file

What did you change, exactly?

**Comment by krishnachaitanya511** [comment]
The JSON has been generated from the YAML file using the online compilers.
Those are same but the file format is different.

**Comment by krishnachaitanya511** [comment]
Hello Team,

Please find my YAML and JSON files. Please help me with the above issue.

[swagger_GitQuestion.json.txt](https://github.com/swagger-api/swagger-ui/files/1139122/swagger_GitQuestion.json.txt)
[swagger_GitQuestion.yaml.txt](https://github.com/swagger-api/swagger-ui/files/1139123/swagger_GitQuestion.yaml.txt)

**Comment by shockey** [comment]
@krishnachaitanya511, you don't need to load any other libraries to load JSON 😄 we support YAML and JSON out of the box.

I just tried to load your JSON into Swagger-UI, and got an error: 

> Parser error on line 2054:
>   missed comma between flow collection entries
> 

You can see it for yourself here: http://petstore.swagger.io/?url=https://gist.githubusercontent.com/shockey/7614b9bb2ff7c96de46e19bd358a372e/raw/4a2d661388099ba5a51aa71ecf040c1a66f18cd1/gistfile1.txt

It appears that the error message is correct - line 2054 of your JSON document is missing a comma, see here: https://gist.github.com/shockey/7614b9bb2ff7c96de46e19bd358a372e#file-gistfile1-txt-L2054. 

Please fix the issues in the JSON file so we can see if it loads correctly!

**Comment by krishnachaitanya511** [comment]
Hello Shockey,


It's working now. Thanks for the great help.


Thanks and Regards
Raja KC Chimakurthi
+91 8885888996
*Tip: If you only do what you can do, you'll never be better than what you
are.*

**Comment by shockey** [comment]
Awesome. Glad to help!

Closing.

**Comment by Webern** [comment]
This really shouldn't be closed. Instead, the swagger-ui should provide the user with the parsing error information (instead of just being a blank screen).

**Comment by heldersepu** [comment]
@Webern there is an error shown:
![image](https://user-images.githubusercontent.com/545474/38165158-22171baa-34dd-11e8-830b-8f10b597d7e9.png)

**Comment by Webern** [comment]
I’m sorry, my blank screen was encountered in the vscode plugin. If I can repro again I’ll upload the json file. So far I have seen the blank screen many times with json but never with yaml.

**Comment by webron** [comment]
@Webern we're not really responsible for the vscode plugin. Should you encounter an issue again, please file a _new_ ticket following the template rather than commenting on one that was closed months ago. Keep in mind we need the version of swagger-ui, not the vscode plugin.
