### ISSUE TITLE
HTML reserved chars not displayed properly in parameter description

### ISSUE THREAD

**Issue by ragrub** [swagger-api/swagger-ui#3349]
If in the swagger definition json one parameter contains a description string with an HTML reserved character like ' < & > then it's not displayed properly in the UI.

![unbenannt11](https://user-images.githubusercontent.com/29981194/27963309-f06affe2-6334-11e7-8d73-cb49038b7276.PNG)

- swagger-ui version 3.0.17
[swagger.txt](https://github.com/swagger-api/swagger-ui/files/1131309/swagger.txt)

**Comment by webron** [comment]
This is not a bug. The `description` fields in the spec are defined as supporting markdown. Since markdown is a superset of html, anything in angled brackets is treated as html tags. If you want to display those, you'd need to escape them as you would in html.
