### ISSUE TITLE
Build sequence in `npm run build` always flags bundle as a dirty git build

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#3357]
### How to reproduce

Consider that `npm run build` yields `npm run build-core && npm run build-bundle && npm run build-standalone`.

1. Have a clean working tree in your Swagger-UI directory
2. Run `npm run build-core` to completion
3. Run `npm run build-bundle` to completion
4. Open `dist/index.html`

Observe that `window.versions` indicates that the bundle was built from a dirty git working tree.

Technically, this is correct - by the time `npm run build-bundle` runs, the working tree is dirtied by the file outputs of `npm run build-core`. However, this indicator is not helpful to anyone trying to reason about the state of the source the build comes from.

The `npm run build` command should be treated as atomic, from the perspective of the dirty flag. 

### Possible solutions

1. Customize the arguments going into `git-describe`, in order to ignore `dist/*` changes when checking the working tree status

**Comment by senterright** [comment]
I would like to see this. :)

**Comment by shockey** [comment]
This was fixed by https://github.com/swagger-api/swagger-ui/pull/4684, which parallelized all build steps.
