### ISSUE TITLE
when parameter's default=0, it can't display in swagger-ui.

### ISSUE THREAD

**Issue by insky2005** [swagger-api/swagger-ui#3358]
When reporting an issue, please provide the following details:
- swagger-ui 2.2.10

In swagger-ui.js, in line 3117

    if (defaultValue) {
      defaultValue = sanitizeHtml(defaultValue);
    } else {
      defaultValue = '';
    }

when  defaultValue = 0, it will set defaultValue='',  so, in ui, the parameter's value will be empty.

I think this is a bug.

so, in my project, I changed it like this

    if (defaultValue!=null && typeof defaultValue != "undefined" && defaultValue!=='') {
      defaultValue = sanitizeHtml(defaultValue);
    } else {
      defaultValue = '';
    }

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-UI 2.x is no longer under development. We'd be happy to consider any reports about Swagger-UI 3, though.

Closing as 2.x wontfix.
