### ISSUE TITLE
xlink:href is deprecated

### ISSUE THREAD

**Issue by xylix** [swagger-api/swagger-ui#3359]
As one can see [here](https://github.com/swagger-api/swagger-ui/search?utf8=%E2%9C%93&q=xlink%3Ahref&type=) the code is using xlink:hrefs in multiple places. 

Xlink:href is deprecated, https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href, so the xlinks should be replaced with standard href links.

**Comment by shockey** [comment]
Thanks for the heads-up 😄 

If you have the time, a pull request that fixes this would be awesome!

**Comment by aleatham** [comment]
Hey, if it's just switching the `xlinkHref` to `href` in jsx files, I can make these changes and submit a PR. Do you want to mention both attributes for backwards compatibility? It seems like that was the choice made when keeping both `xmls` and `xmls:xlink` attributes.

**Comment by shockey** [comment]
@aleatham, sorry for the delayed response!

It would be great if you could make this contribution. Keeping both sounds like the best strategy to me!

**Comment by shockey** [comment]
Fixed by #3418 🎉
