### ISSUE TITLE
CORS: access-control-allow-origin send as request header

### ISSUE THREAD

**Issue by SzymonKlimuk** [swagger-api/swagger-ui#3367]
- swagger-ui version: 3.0.17

Why swagger ui sends access-control-allow-origin in requests in Access-Control-Request-Headers?

Access-Control-Allow-Origin is RESPONSE header rather than REQUEST header, so why it sends it as requested in Access-Control-Request-Headers and then send it in for example POST messages as:

access-control-allow-origin: "*"

?

We are doing authentication scenarios using keycloak (password and accessCode flows for example). We checked it on both firefox and chrome browsers. Swagger UI 3.0.17 causes the browser to send OPTIONS request to the keycloak. During this preflight conversation, Swagger UI sends:

Access-Control-Request-Headers:access-control-allow-origin,authorization
Access-Control-Request-Method:POST

while access-control-allow-origin shouldn't appear in any request - because it is the response header.

After that (assuming keycloak was changed to allow this header), when sending the POST to the tokenUrl, it adds access-control-allow-origin: "*"

Is there ANY reason of such behavior?

Regards,

Szymon Klimuk

**Comment by Fredx87** [comment]
Same problem here.
Related issue: https://github.com/swagger-api/swagger-ui/issues/3172

Removing the line where the "access-control-allow-origin" is set in `src/core/plugins/auth/actions.js` and rebuilding the dist folder solved the issue for me.

**Comment by shockey** [comment]
Referencing blame: https://github.com/shockey/swagger-ui/blame/ft/oas3/src/core/plugins/auth/actions.js#L138

@bodnia, can you advise on why this was added?

**Comment by SzymonKlimuk** [comment]
Yes, please add information why it is needed? Maybe we didn't catch the use case for it.

**Comment by bodnia** [comment]
@shockey chrome used not to send CORS requests. Now I tested with no header it works ok.

**Comment by bodnia** [comment]
Once https://github.com/swagger-api/swagger-ui/pull/3481 is ready to merge, the issue will be resolved.

**Comment by bodnia** [comment]
fixed with #3481
