### ISSUE TITLE
External documentation for operations is not styled properly and doesn't take GFM syntax into account

### ISSUE THREAD

**Issue by Rinzwind** [swagger-api/swagger-ui#3384]
See screenshot (Safari v10.1.1): the text about the external documentation seems to have two problems:

1. it's not properly styled and
2. it doesn't seem to take into account that the [Swagger spec](https://swagger.io/specification/#externalDocumentationObject) says “GFM syntax can be used for rich text representation.” (the double asterisks appear literally rather than causing the text to be in bold face).

The Swagger-UI version used is the one in [“dist” in commit 08e84a00](https://github.com/swagger-api/swagger-ui/tree/08e84a0048d657589ca4b1acb274e5e271f0d8bc/dist). The `swagger-debug.json` file is:

	{
	  "swagger": "2.0",
	  "info": {
	    "title": "Sample API",
	    "version": "1.0"
	  },
	  "paths": {
	    "/something": {
	      "get": {
	        "externalDocs": {
	          "description": "**External documentation** can be found at the following link",
	          "url": "http://www.google.com"
	        },
	        "responses": {
	          "200": {
	            "description": "OK" }
	        }
	} } } }

![screenshot external documentation problem](https://user-images.githubusercontent.com/1611248/28201755-c08eee6c-6872-11e7-8fbd-a69621701a12.png)

**Comment by shockey** [comment]
Confirmed: external documentation descriptions are being rendered as plain text. 

Code reference: https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/operation.jsx#L194

**Comment by shockey** [comment]
@Rinzwind I just fixed this, about to turn around and do our weekly release - so a fixed version should be live on npm and github within the hour.

Thanks for reporting the issue!
