### ISSUE TITLE
& symbol renders as &amp; with monospace

### ISSUE THREAD

**Issue by Ohems** [swagger-api/swagger-ui#3385]
Swagger-UI version: 3.0.18

**What happens**
The symbol & is converted to `&amp;` in the following file when shown in the UI:
```
info:
  title: Example data
  version: 1.0.0
  description: Some random characters `@&€#/£∞$§|`
swagger: '2.0'
paths:
  '/data':
    get:
      description: List data
      produces:
        - application/json
      responses:
        '200':
          description: Data
```

**Expected result**
Symbols shouldn't change suddenly, no matter the styling. If I want the text to appear as `&amp;` then I should just be able to write that myself. The same effect doesn't happen with normal, cursive or bold letters.

**Practical case**
If you want to add a quick explanation of how to use an array parameter, you can write something like this to a path description:
```
description: |
    Search based on one or more targetIds.
    For example requesting targets [1,2] would be
    `?targetId=1&targetId=2`
```
And currently it completely breaks in the UI.

**Comment by Ohems** [comment]
On another note, monospace seems to be more screwed up than I thought. ``` Format: `<field>:<order>` ``` renders as `Format: :` and ``` `<order>` ``` renders as ``` `` ```, but ``` `<b>a</b>` ``` renders as `<b>a</b>`. I have no idea what's going on and the scope of this issue suddenly became a lot larger so do whatever you want with it.

**Comment by Ohems** [comment]
It seems that I'm supposed to use HTML escape codes.

**Comment by webron** [comment]
You *are* supposed to use HTML escape codes. Markdown is a superset of HTML, so it just translates to HTML. If you use XML tags in it, it would treat those as HTML, effectively not rendering them. So just like you'd need to escape those in HTML, you need to do the same in markdown.

Out of all the issues you've mentioned, only the first one might be real.

**Comment by shockey** [comment]
The disappearing tags are an effect of the sanitization that we perform on all Markdown fields - that's why your XML-like tags disappeared, while `<b>` was still present.

Properly escaping your Markdown content should solve this issue 😄 

The `&` does sound a bit weird. I'll look into that.

**Comment by Ohems** [comment]
This issue seems to extend to `<` (becomes `&lt;`) and `>` (becomes `&gt;`). It also extends to the object example field which is monospace like this:
<img width="648" alt="screen shot 2017-07-28 at 17 00 21" src="https://user-images.githubusercontent.com/8604342/28720625-6c5fbfac-73b6-11e7-9156-1dad6df6dc03.png">

Offering an example XML response is therefore impossible at the moment.
