### ISSUE TITLE
Round corners on the right of download-url-input

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3394]
Seems that the right corners have changed, now they do not look flush with the button
Here is how they looked before:
http://turoapi.azurewebsites.net/swagger/ui/index

- swagger-ui version
http://petstore.swagger.io/
- a swagger file reproducing the issue
http://petstore.swagger.io/v2/swagger.json

![image](https://user-images.githubusercontent.com/545474/28240411-808d251c-694f-11e7-9491-624ad36c7bc6.png)

**Comment by shockey** [comment]
@Minasokoni, I'd bet this was introduced in #3196 (https://github.com/swagger-api/swagger-ui/pull/3196/commits/fe200f86167b42343ad784436267dc7a3ef2d119, specifically).

**Comment by heldersepu** [comment]
This seems like an easy fix... is there something I'm missing?

**Comment by heldersepu** [comment]
@shockey  Can you tag this issue correctly (label:3.x  && label:Bug) see if that will inspire someone to fix it...

**Comment by shockey** [comment]
@heldersepu, looks like @webron beat me to it 😄 

I believe it is an easy fix - maybe even a one-liner, as you pointed out. Unfortunately, the core team is focused on higher priority issues right now, so this may stay open for a while.

I've added our `Good first contribution` label, which may help attract a contribution for this issue. Also consider opening a PR yourself, if you have the time for it!

**Comment by heldersepu** [comment]
@shockey I've been wanting to setup my dev environment for a while, but between other projects and summer activities, haven't had a chance to do it....

Do you guys have any guide how to setup all the requirements to build/debug?

**Comment by Minasokoni** [comment]
Sorry for the delay on this. I've been slammed with work and didn't think this was critical 😢

**Comment by heldersepu** [comment]
Looks like was fixed in latest version...

**Comment by shockey** [comment]
Good catch @heldersepu! Thanks for reporting this.
