### ISSUE TITLE
Delete Request not working from swagger UI

### ISSUE THREAD

**Issue by infyravi** [swagger-api/swagger-ui#340]
While performing DELETE Operation from swagger UI in playframework,Delete operation is not working.It is expecting json but the delete method is defined  for Long datatype as input parameter.we are using Play 2.1.3.When we enter  id of the Entity to delete ,getting the error message as  message": "400 Error Invalid Json

**Comment by jackphel** [comment]
@alphaadidas thanks that's super helpful!

**Comment by cnmuc** [comment]
@alphaadidas tx, empty body parser worked for me

**Comment by 00bharat7** [comment]
@alphaadidas  -  This saved my precious time. thanks a lot 👍
