### ISSUE TITLE
multipart/form-data parameters sent as "application/x-www-form-urlencoded" - reopen

### ISSUE THREAD

**Issue by kwieconkowski** [swagger-api/swagger-ui#3400]
@webron @owenconti @shockey  I'm reopening the issue (https://github.com/swagger-api/swagger-ui/issues/3375). I have tested today using newest distribution and still doesnt work as supposed. Content-type is 'application/x-www-form-urlencoded' instead of 'multipart/form-data' as it should be.

```
curl -X POST "http://localhost:8080/rest/upload/someMethod" -H "accept: application/json" -H "content-type: application/x-www-form-urlencoded" -d "someParam=example"
```
Swagger document:
```yaml
swagger: "2.0"
info:
  version: "1.0.2"
host: "localhost:8080"
basePath: "/rest"
tags:
- name: "someTag"
schemes:
- "http"
paths:
  /upload/someMethod:
    post:
      tags:
      - "someTag"
      summary: "someSummary"
      description: "someDescription"
      operationId: "uniqueId"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "someParam"
        in: "formData"
        required: false
        type: "string"
      responses:
        200:
          description: "Number of stored documents"
          schema:
            type: "integer"
            format: "int32"
definitions:
```

**Comment by shockey** [comment]
Hi @kwieconkowski, sorry you're having trouble!

I just tried the spec you provided with the latest version (3.0.19) and I see my request going out with  `content-type:multipart/form-data; boundary=----WebKitFormBoundarypofYoBhfSrAukuWK`.

See here: http://petstore.swagger.io/?url=https://gist.githubusercontent.com/shockey/88595ca7fe86a0fa3225f1a979d24943/raw/e15995a5aad3ba6b5030ae427a78469b660eb2f7/3400.yaml

Please make sure you're running the latest version - you can check by opening your browser console and checking the value of `window.versions.swaggerUi`.

Let me know what you find!

**Comment by kwieconkowski** [comment]
Hi @shockey , you are right I did some digging and found two issues, now is working. 

First, the following link (https://github.com/swagger-api/swagger-ui/archive/master.tar.gz) contains version '3.0.17/ge4f9837-dirty', but when we use (https://github.com/swagger-api/swagger-ui/archive/master.zip) is '3.0.19'. I understand that is the newest version.

Second, I was downloading distribution using maven plugin, by default was using caching and returning older versions without downloading again.

@webron  @owenconti  @shockey  Thank you for your help, the issue can be closed now.

**Comment by mglen** [comment]
Encountered this issue as well, and found that bumping to the latest version '3.19.3' did not resolve it.

We had split up the `.css` and `.js files into separate `css/` and `lib/` directories, and edited `index.html` for the new paths. Doing so caused this exact behavior, and moving all the files back to the same level resolved this problem.

Hope this helps anyone else who finds their way here.
