### ISSUE TITLE
Default https schema not working

### ISSUE THREAD

**Issue by StefSchenkelaars** [swagger-api/swagger-ui#3405]
When you provide only `https` as a schema, the `try out!` examples still use `http`. If you reselect `https` from the schemes (just click the one item) before you start trying the api, the examples change to https correctly.

This also includes the example curl commands which in the example file below result in: `curl -X POST "http://example.com/all" -H "accept: application/json"` (so no https while this is the only option).

Hope the issue is clear.

Swagger ui version 3.0.19 (from http://editor.swagger.io/)
```yml
swagger: '2.0'
info:
  title: TestApp
  version: 1.0.0
host: example.com
schemes:
  - https
paths:
  /test:
    post:
      responses:
        '200':
          description: Ok
```

**Comment by owenconti** [comment]
I can't reproduce the issue on first load of either http://petstore.swagger.io/?url=https://gist.githubusercontent.com/owenconti/d630b688aa5c7c68defd1b2efec48fb7/raw/cb7fbf6e1d04ac08d0b58fb9557d72fdfd26fab3/gistfile1.txt  or http://editor.swagger.io.

However, I can reproduce it in the editor when changing the available Scheme from `HTTP` to `HTTPS` or vice-versa.

**Comment by StefSchenkelaars** [comment]
If you add the file with the `url` parameter it works indeed. However if you first go to `http://petstore.swagger.io` and then fill in your url `https://gist.githubusercontent.com/owenconti/d630b688aa5c7c68defd1b2efec48fb7/raw/cb7fbf6e1d04ac08d0b58fb9557d72fdfd26fab3/gistfile1.txt`, it does not work.
