### ISSUE TITLE
Swagger UI not displaying Model and Model Schema

### ISSUE THREAD

**Issue by dkirrane** [swagger-api/swagger-ui#341]
All I'm getting for my Model is the class name and the Model Schema appears as empty?

In the swagger json file I can see Json describing the class.

**Comment by guyappy** [comment]
Hi, I have the same issue, but then on version 2.1.4 (which should have solved this issue?). The model schema and model are both empty (or showing {}) while the Swagger is validated properly.

The UI and source can be found at:
http://bugaboo-api.appythings.com/

thanks!

**Comment by fehguy** [comment]
@guyappy looks like you have some errors in your YAML.  When you have a `schema` object, you do not define a `type` and `items`:

```yaml
          schema:
            # a pointer to a definition
            type: object
            items: 
              $ref: '#/definitions/visitIdentity'
```

Should be:

```yaml
          schema:
            # a pointer to a definition
            $ref: '#/definitions/visitIdentity'
```

**Comment by woco** [comment]
@guyappy @fehguy 
Hi, I got the same issue, but the code looks like fine. So do you have any suggestions for me, thanks~

- **The swagger-ui display:**

![image](https://cloud.githubusercontent.com/assets/11224938/14480869/a4c726fc-015f-11e6-98f0-2856e8c2b4bf.png)

- **and the restController and domain like this:**

![image](https://cloud.githubusercontent.com/assets/11224938/14483265/cb1911b8-0177-11e6-9701-7c736a65e8d5.png)
![image](https://cloud.githubusercontent.com/assets/11224938/14483280/ebc5bfa6-0177-11e6-8e31-813a3abbd611.png)

- **My maven dependency like this: **

```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>2.2.2</version>
</dependency>
<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-swagger-ui</artifactId>
	<version>2.2.2</version>
</dependency>
<dependency>
	<groupId>org.aspectj</groupId>
	<artifactId>aspectjweaver</artifactId>
	<version>1.8.3</version>
</dependency>
<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>bootstrap</artifactId>
	<version>3.3.5</version>
</dependency>
```
