### ISSUE TITLE
Required array query parameter execute shows loading spinner but does nothing

### ISSUE THREAD

**Issue by jmattheis** [swagger-api/swagger-ui#3414]
Version: 3.0.19
Reproducible on [Petstore](http://petstore.swagger.io/) with api: GET-`/pet/findByTags`

When having a required query parameter which can be added more than once and clicking `Exceute` without adding a value to the array query parameter the loading spinner is shown. No request is send it just stays that way.

After adding a value and removing it again an error message is shown while clicking execute. (which is not good styled).

**Comment by webron** [comment]
I can't seem to reproduce it. Can you describe again or provide a screencast?

**Comment by jmattheis** [comment]
Here a gif for better understanding:
![issue-3414-gh](https://user-images.githubusercontent.com/14895212/28402234-010dc8b8-6d1f-11e7-943d-7bcfebadaf71.gif)

**Comment by webron** [comment]
Thanks, that explains it. Definitely an issue.

**Comment by shockey** [comment]
The PR that solves this issue was reverted in v3.0.21 - reopening.

**Comment by shockey** [comment]
The fix for this was reimplemented via https://github.com/swagger-api/swagger-ui/pull/3453 in v3.1.0.

Closing!
