### ISSUE TITLE
Expand/Collapse arrow on the Models

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3422]
- swagger-ui version
latest
- a swagger file reproducing the issue
http://petstore.swagger.io/

The Arrow on the models does not change when we expand and collapse

![image](https://user-images.githubusercontent.com/545474/28421470-46494830-6d33-11e7-9ed4-ea82ba59dc78.png)

![image](https://user-images.githubusercontent.com/545474/28421484-510a7a28-6d33-11e7-8fd9-c426fb3dca09.png)

**Comment by webron** [comment]
Ugh.

**Comment by heldersepu** [comment]
Awesome! it works as intended with 3.0.20 !
