### ISSUE TITLE
Wrong position of "try it out" button in 2.0 specs (ft/oas3)

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3429]
Version: `ft/oas3` branch, as of commit a1ce0e7
Spec: http://petstore.swagger.io/v2/swagger.json

"Try it out" button is misaligned in 2.0 specs:
![try-it-out 2.0](https://user-images.githubusercontent.com/8576823/28458312-f92fa9b0-6e11-11e7-998c-75b4edd1444c.png)

In 3.0 specs the button position is correct (on the right).

**Comment by shockey** [comment]
Fixed. Thanks @hkosova!
