### ISSUE TITLE
Failed to load spec. on Docker Container

### ISSUE THREAD

**Issue by hassanfarid** [swagger-api/swagger-ui#3430]
I have just taken latest docker image.

`#Setup Swagger UI`
`docker pull swaggerapi/swagger-ui`
`docker run -p 3080:8080 --name ae_api_ui -e API_URL=http://generator.swagger.io/api/swagger.json swaggerapi/swagger-ui`

I have a parallel httpd server on same machine, running on port 9080.

When I load the URL: http://generator.swagger.io/api/swagger.json
It works fine.
When I load the URL of httpd server, same file, it doesn't work.
http://10.32.x.x:9080/files/swagger.json

The file is accessible otherwise from browser.
Also in browser, both URLs below have same content.
http://10.32.x.x:9080/files/swagger.json
http://generator.swagger.io/api/swagger.json

**Comment by webron** [comment]
Does your httpd server have CORS enabled?

**Comment by hassanfarid** [comment]
@webron I am not sure; I am running default container of httpd:2.4

Any hints on how to do that?

**Comment by hassanfarid** [comment]
I was able to enable CORS in the container httpd.conf file.

The help content: https://enable-cors.org/server_apache.html

Thanks @webron
