### ISSUE TITLE
Support for enum arrays

### ISSUE THREAD

**Issue by Ohems** [swagger-api/swagger-ui#3433]
Swagger UI version: 3.0.19

Arrays with enum items don't behave correctly in the Swagger UI.

Example yml:
```
info:
  title: Example data
  version: 1.0.0
swagger: '2.0'
paths:
  '/data':
    get:
      parameters:
        - name: data
          in: query
          type: array
          items:
            type: string
            enum: [lol, hi]
      responses:
        '200':
          description: Data
```

When shown in the UI, it looks like this:
![image](https://user-images.githubusercontent.com/8604342/28466705-f2ecae12-6e35-11e7-80b9-9016cd783204.png)

In other words, the array behaves like a single enum value. Adding multiple values and sending an empty array is impossible. This should be fixed, for example by changing it to match the usual behaviour of arrays with the normal input field replaced by an enum selector.

**Comment by hkosova** [comment]
You can select multiple items using Ctrl-click and Shift-click.

**Comment by Ohems** [comment]
Ahh, completely failed to realise that. Could it be more intuitive to allow selecting multiple items without holding Ctrl or Shift? In any case, I'll close this issue.
