### ISSUE TITLE
 Missing image on POST method returning "image/png" content

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3435]
When reporting an issue, please provide the following details:
- swagger-ui version
latest (3.x)
- a swagger file reproducing the issue
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=PngImage

Just try that Post you will see the image will not show.
It seem the Response body just adds an ```img``` not the actual response

**Comment by webron** [comment]
Try setting the `produces` to `image/png`.

**Comment by heldersepu** [comment]
Sorry same result, after changing the produces...

**Comment by webron** [comment]
Yup, after the POST request, I see another GET request to get the image again for some reason. We'll need to look into it.

**Comment by heldersepu** [comment]
Yep, I noticed that too, my issue started with a different controller:
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Image#/Image/Image_Post
on that one the POST was showing the image of the GET:

**Comment by heldersepu** [comment]
Awesome!
will test as soon as the dist gets updated...

**Comment by heldersepu** [comment]
Awesome! it works as intended with 3.0.20 !
