### ISSUE TITLE
OAS 3.0: Request body is uneditable during try-it-out

### ISSUE THREAD

**Issue by jblazquez** [swagger-api/swagger-ui#3436]
Swagger UI version: commit `a1ce0e7` (`ft/oas3` branch)

Looks like it's not currently possible to edit the request body when trying out a particular operation:

<img width="527" alt="1" src="https://user-images.githubusercontent.com/5482684/28476255-33fcd0d0-6e04-11e7-9d9b-55d47b7c4543.png">

Spec:

```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Test",
    "version": "1.0.0"
  },
  "paths": {
    "/test": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "prop": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "default": {
            "description": "A response"
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
The try it out functionality is not implemented yet for OAS3.

**Comment by jblazquez** [comment]
I can definitely use the try it out functionality for OAS3 with the current version in the `ft/oas3` branch. Everything appears to work except for the inability to edit request bodies (request bodies are sent, but they literally are always the example JSON based on the model).

**Comment by webron** [comment]
I'll rephrase - it's not supported. We need to make substantial changes to it and we've yet to start working on it. In fact, before the upcoming release of it, we'll disable the try-it-out button.

**Comment by shockey** [comment]
I just pushed a commit that disables all Try It Out buttons when viewing an OAS3 spec. It includes a styling fix for the Parameters tab bar, that was causing some height issues when viewing callbacks.

---

Things that haven't changed in structure or semantics from Swagger 2.0 will still work in Try It Out, but I'd really recommend waiting until we officially support it. I promise there are subtle bugs that will cause pain, if you try to use the Swagger 2 request constructor with OAS3 😄

**Comment by shockey** [comment]
Also see: #3338.

**Comment by shockey** [comment]
Closing; #3338 will track this feature being implemented.
