### ISSUE TITLE
OAS 3.0: readOnly properties are included in request body examples

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3445]
Version: `ft/oas3` branch, commit a1ce0e7b3c54d66534faf59599c6bce5f23656f2

In 3.0 specs, request body examples generated from the `schema` include read-only properties -- but they should not be included in requests. The issue does not exist in 2.0 specs.

**Spec:**
```
openapi: 3.0.0
info:
  version: 0.0.0
  title: test

paths:
  /users:
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 5
          readOnly: true
        name:
          type: string
          example: Bob
```

**Expected result:** Request body example is:
```
{
  "name": "Bob"
}
```

**Actual result:** Request body example includes the read-only property `id`:
```
{
  "id": 5,
  "name": "Bob"
}
```

**Comment by owenconti** [comment]
@hkosova Running the latest `master` locally, this is what I am seeing with your example spec:

<img width="993" alt="screen shot 2017-09-14 at 2 27 32 pm" src="https://user-images.githubusercontent.com/791222/30454276-fcefcefa-9958-11e7-87c4-e5911e3517b7.png">

<img width="984" alt="screen shot 2017-09-14 at 2 27 38 pm" src="https://user-images.githubusercontent.com/791222/30454282-010bb512-9959-11e7-9506-f710a0ca5602.png">

<img width="983" alt="screen shot 2017-09-14 at 2 27 46 pm" src="https://user-images.githubusercontent.com/791222/30454284-04e87b5c-9959-11e7-9512-ba650e17d0b0.png">

I don't see the `id` property in any of the example objects, however I do see it in the `Model` tab of the request body field.

**Comment by hkosova** [comment]
@owenconti, yes, this seems to be fixed already. :tada: 
Closing.

**Comment by amochohan** [comment]
It looks like this is still an issue for `readOnly` attributes which refer to objects. If I expand on the original example:

```yml

paths:
  /users:
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 5
          readOnly: true
        name:
          type: string
          example: Bob
        another_attribute:
            type: object
            $ref: '#/components/schemas/AnotherModel'
            readOnly: true
```

The `another_attribute` will still be displayed in the `requestBody` example.

**Comment by hkosova** [comment]
@amochohan, `$ref` works by overwriting all of its sibling attributes, so `readOnly` does not actually have effect in your example. You'll need to use something like:

```yaml
        example_attribute:
          readOnly: true
          allOf:
            - $ref: '#/components/schemas/AnotherModel'
```
A similar issue was discussed in https://github.com/swagger-api/swagger-ui/issues/3325#issuecomment-334139931.

**Comment by amochohan** [comment]
Thanks @hkosova, apologies if this wasn't the correct medium through which to have raised this.

**Comment by Adeynack** [comment]
I still have the same problem, observed in SwaggerDoc.
I changed some properties to `readOnly: true`. They disappeared from the `POST` example, but they still show up in the `PATCH` one. Since `PATCH` is a _write_ verb, I expect them not to show up in the example.
