### ISSUE TITLE
OAS 3.0: Indication of whether request body is required

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3449]
Version: `ft/oas3` branch

In 2.0 specs, when a body parameter is required, it is displayed with an "*" in the parameter list.
In 3.0 specs, the fact that `requestBody` is required (or not required) is not indicated in any way.

```
openapi: 3.0.0
info:
  version: 0.0.0
  title: test
paths:
  /:
    post:
      requestBody:
        required: true  # <---
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
```

**Comment by shockey** [comment]
Fixed. Thanks @hkosova!

**Comment by shockey** [comment]
![image](https://user-images.githubusercontent.com/680248/28729992-50155c68-7383-11e7-830e-c7f0cab9f3df.png)
