### ISSUE TITLE
"Try it out" parameter encoding issue - v3.0.20

### ISSUE THREAD

**Issue by kverfaille** [swagger-api/swagger-ui#3455]
From previous posts I noticed that all parameters are encoded, which is fine, but the mechanism gives issues in specific cases. I do not think there is anything wrong with the way we work, so hence this post to report an issue or ask for advice.

**Rest API explained**
Due to circumstances, our base urls looks like this (both need to work): 
- "http://dev.domain.me/router.php?p=rest&__route__". 
- "http://dev.domain.me/rest" (with rewrite =>all works fine, so ignored from now on)

Then there are command paths like this: 
- "/NameByID/{ID}"
- "/NameByID/{ID}&show_deleted=1".

Combining this gives: 
- "http://dev.domain.me/router.php?p=rest&__route__/NameByID/{ID}&show_deleted=1"

Behavior
The first command without paramters encodes well to this:
http://dev.domain.me/router.php?p=rest&amp;__route__/NameByID/F9999

The second command is encoded as shown below which isn't a valid path anymore.
http://dev.domain.me/router.php?p=rest&amp%3B__route__%2FNameByID%2F9999=&show_deleted=1
I notice the following encode issues:
- The ; of the &amp; is now encoded again to %3B
- The /'s the command itself are encoded
- An obsolote '='-sign is added between the command and the paramters 

Is this a bug, since I would expect that only parameters _in the command path (and not the full command path) and parameters behind the command path_ should be encoded? 

If not, are there any suggestions on how to solve/workaround our problem?

Regards,
Kevin

**Comment by webron** [comment]
It looks like you're trying to do something that's not supported by the spec. The basePath and the paths themselves cannot contain query parameters, and in your case, they do (at least the basePath). As this is not supported by the spec, this would lead to unexpected behavior.

I could be misunderstanding your case though. If you feel that's the case, please attach the full API definition.

**Comment by kverfaille** [comment]
Thanks for your answer Ron.

The issue we are facing seems to be caused by encodeURI VS encodeURIComponent. 

If you think that swagger-ui should be able to handle my case; I would suggest to use encodeURI() on the basepath & encodeURIComponent() on everything after the basepath. So not after the ? as it behaves now. If you think it shouldn't work,  just close this issue and we will manage it in our backend. 

**Why we works this way**
The thing is that we work with an (old) in-house-built framework. This framework is used by multiple websites (a lot) and recently we started to renew some parts of it.

The "router.php?p=anypage" is mandatory, it is just a request to router.php that then parses the query parameters to load the correct page. The framework also exposes an Rest API hence "router.php?p=rest". 

So there is no way of getting the query params out of the basepath without adapting all websites and/or their rewrite rules.

It worked perfectly in swagger-ui 2.x, hence I reported it :-).

**Comment by webron** [comment]
Yeah, it sounds like you're using RPC-style APIs which are just not supported by the spec (nor will they be in the upcoming one). If it worked in 2.x, it was more of a bug there than it is here for not working, sorry about that. This is not something we're looking to handle.
