### ISSUE TITLE
OAS 3.0: Model names not displayed in operations

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3457]
Version: `ft/oas3` branch
Spec: https://openapi-converter.herokuapp.com/api/v1/convert?url=http://petstore.swagger.io/v2/swagger.yaml

In 3.0 specs, the "Model" tab in operations does not display the model names.

![model-title](https://user-images.githubusercontent.com/8576823/28564977-6f2e8180-7133-11e7-93f5-0d2245bbeed3.png)

**Comment by shockey** [comment]
![image](https://user-images.githubusercontent.com/680248/28732780-1c2bf640-738e-11e7-8a17-9af3a160dd7b.png)

Fixed!
