### ISSUE TITLE
[npm swagger-ui-dist] POST and PUT requests don't work in swagger-ui-dist 3.0.20

### ISSUE THREAD

**Issue by xgflorin** [swagger-api/swagger-ui#3464]
I installed the UI dist package from npm using `npm install swagger-ui-dist` and I am serving it as it is directly from node_modules using koa-static. When I click the "Try it out" button on a POST or PUT endpoint, I am getting this error in the console:

`Could not find component JsonSchema_string_`

and when I click "Execute" the request is not performed. GET and DELETE work fine.

**Comment by shockey** [comment]
@xgflorin, `Could not find component JsonSchema_string_` is a warning, not a hard error - it comes up from time to time, you don't need to worry about it.

We've been dealing with some issues related to Try-It-Out functionality lately, can you provide a spec that reproduces the problem firing off requests, so we can investigate?

Thanks!

**Comment by shockey** [comment]
Oh, also - please provide the version of swagger-ui-dist that you installed from npm.

`npm ls | grep swagger-ui` should tell you, if you aren't certain.

**Comment by xgflorin** [comment]
@shockey I'm using `swagger-ui-dist@3.0.20` and I found that the petstore spec at http://petstore.swagger.io/v2/swagger.json behaves the same way. I couldn't POST to /pet.

**Comment by shockey** [comment]
@xgflorin Thanks for the info. Can you update to `3.0.21`? We shipped some known issues in 3.0.20, that we fixed in .21 - I hope to get 3.0.20 deprecated on npm as a result.

Please let me know where that gets you!

**Comment by xgflorin** [comment]
Upgrading from 3.0.20 to 3.0.21 fixed it!

**Comment by shockey** [comment]
@xgflorin Awesome! Sorry for the inconvenience. Thanks for using Swagger!

Closing.

**Comment by WorkForPizza** [comment]
Hey I'm getting this same error with `swagger-ui-dist@3.1.4`. Any fixes?

**Comment by webron** [comment]
@WorkForPizza please open a new ticket and provide an API definition to reproduce it.
