### ISSUE TITLE
swagger-ui does not remove java string escape char "\" from @ApiModelProperty example

### ISSUE THREAD

**Issue by heapifyman** [swagger-api/swagger-ui#3465]
I am using version `2.2.10` of `swagger-ui`, at least I think that's the version included by version `2.7.0` of `springfox-swagger-ui`, which I am using with `springfox-swagger2` and spring-boot 1.5.4.RELEASE

I have defined some example value in `@ApiModelProperty` like this

```
@ApiModelProperty(example = "{\"name\": \"foo\", \"age\": 42}")
as part of a model for a body param.
```

The escape chars `\` are kept in swagger-ui's `Example Value`, so that when clicking on it to paste the `Example Value` into `body` param value for testing the REST endpoint, the escape chars `\` are still included - thus transmitting invalid JSON to the endpoint.

Same goes for things like `\n` or `\t`, which are quite common in Java Strings.

The generated `swagger.json` file contains the following:
```
"example": "{\"name\": \"foo\", \"age\": 42}"
```

See: https://github.com/springfox/springfox/issues/1941

**Comment by heapifyman** [comment]
Hi @shockey ,

I just tried with a locally running `v3.0.21`, which I just pointed to the swagger.json generated by springfox by changing the `SwaggerUIBundle`'s `url`.

Unfortunately, the `Example Value` still shows 
```
"data": "{\"name\": \"foo\", \"age\": 42}"
```

In the `Model` part however, the example is correct:
```
example: {"name": "foo", "age": 42}
```

Since I assume that both `Example Value` and the `Model`'s example value are taken from the same part of `swagger.json`, I would say, this is a bug in swagger-ui ?

As said before, the `swagger.json` contains 
```
"example": "{\"name\": \"foo\", \"age\": 42}"
```

I don't know in what other way this example value should be included in `swagger.json` without producing invalid json.

**Comment by webron** [comment]
I hate kicking this back and forth between us and springfox, but to me the issue is there. This is a hard problem in a sense, because the spec doesn't quite help when it comes to example values.

Since the example you're trying to generate is a JSON object, it needs to be represented as such. What actually ends up happening is that Springfox provides a string value, and we just treat it as such.

**Comment by heapifyman** [comment]
ok, thanks.

**Comment by dilipkrish** [comment]
@webron just curious, does swagger-core un-escape the example from the annotation?

**Comment by webron** [comment]
@dilipkrish honestly, not sure. I don't think the current version does, but I believe the next major version will.

**Comment by ramanans** [comment]
I just tried with 2.8.0 (Major version as of 1/19/2018). Still the issue exists.

**Comment by shockey** [comment]
@ramanans, it looks like this was fixed in springfox, you may need to use a newer version of it: https://github.com/springfox/springfox/issues/1941
