### ISSUE TITLE
Dynamics Base URL

### ISSUE THREAD

**Issue by GerardFernandes** [swagger-api/swagger-ui#3466]
My swagger-ui version: latest.

Hi Guys,

I wonder how to parametrize the base request URL, it seems that there isn't any option to do what I need.
Basically, I need to make a new parameter that will be the base URL of my request.

Can anyone help me?

**Comment by webron** [comment]
That's not supported by the spec. The next version of the spec will support it.

**Comment by marc101101** [comment]
@webron is this feature already supported?

**Comment by marc101101** [comment]
@webron is it maybe possible to manipulate the dom?
