### ISSUE TITLE
Regression bug in version 3.0.20

### ISSUE THREAD

**Issue by rflechner** [swagger-api/swagger-ui#3468]
Hi

- swagger-ui-3.0.20
- a swagger file reproducing the issue : http://petstore.swagger.io/v2/swagger.json

Testing of POST with a body seems to be broken with version 3.0.20
![swaggerui-broken](https://user-images.githubusercontent.com/1033822/28629131-d774afdc-7226-11e7-8b12-c373dbc5b842.gif)

But everything is ok with 3.0.19

![swaggerui_ok](https://user-images.githubusercontent.com/1033822/28629213-1fec7f06-7227-11e7-9dd5-39be46041d7c.gif)

Regards

**Comment by webron** [comment]
That's why we had a hotfix release of 3.0.21 earlier this week. Give it a try.

**Comment by rflechner** [comment]
Sorry I didn't see this hotfix.
It's working.
Thanks.

**Comment by webron** [comment]
We forgot to issue release notes - should be fixed shortly. Thanks for checking and reporting!
