### ISSUE TITLE
XML metadata not being honored consistently in XML examples

### ISSUE THREAD

**Issue by abstratt** [swagger-api/swagger-ui#3469]
- swagger-ui: v3.0.20 (git checkout v3.0.20)
- sample Swagger spec : 
[simpler.json.txt](https://github.com/swagger-api/swagger-ui/files/1178151/simpler.json.txt)

I have been trying to generate a Swagger spec for a REST API that is XML-based, so I am relying heavily on XML objects to declare the name for the XML elements and attributes in requests/responses. For some reason, in some cases swagger-ui honors the XML metadata in the generated examples, in others it doesn't.

See below: for propA and propB it fails to honor the XML metadata. For propC it does work as expected. 

![image](https://user-images.githubusercontent.com/2187522/28644945-f2ce6e5c-7231-11e7-9389-809c29743571.png)

**Comment by abstratt** [comment]
Hmm, I see the pattern now. The issue only happens for complex properties that are not multivalued. In that case, the XML metadata under the property definition is not taken into account, instead it is expected to be in the definition of the object itself. 

Did I misinterpret the spec? What if I want to use the same type for two different properties, say, parentProcessA (parent-process-a) and parentProcessB (parent-process-b) - the way it is now, I would end up with the same XML element for both of them.

**Comment by abstratt** [comment]
I noted that if I define a XML object in MyType2, it gets honored everywhere. But that is not correct, it seems:
- under the documentation for the "xml" property, the Swagger spec states:
> This MAY be used only on properties schemas. It has no effect on root schemas
- even if valid, the property definition should win (so I can have properties of the same type declare their own names)

**Comment by abstratt** [comment]
By the way, I do think one should be able to define the XML object on definitions themselves. Or else how could I define the XML metadata for the root element? I guess what the spec is saying is that you can define the XML metadata on properties themselves, or on definitions backing the types used in properties. 

Regardless, the XML metadata defined in a property should always prevail, if both the property, and the definition backing a property type define XML metadata (I guess a mix of them would make sense - use the property XML metadata field if it is there, if not, fall back to the definition XML metadata field, on a field basis?).

**Comment by hkosova** [comment]
```
      propA:
        $ref: '#/definitions/MyType2'
        xml:
          name: prop-a
```

When you use a `$ref`, it shouldn't have any sibling properties, because they are ignored. It's [how `$ref` works](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3):
> Any members other than "$ref" in a JSON Reference object SHALL be ignored.

If you import your spec into http://editor.swagger.io, it will show warnings about this. So, for `xml.name` to have effect, it should be part of the `$ref`erenced definition.

There's further discussion about `$ref` and sibling properties in the OpenAPI Specification repository at https://github.com/OAI/OpenAPI-Specification/issues/556.

**Comment by abstratt** [comment]
Thanks @hkosova, that was my fear, that the limitation came from the spec...

Closing as it is not a problem with swagger-ui itself.
