### ISSUE TITLE
Add support for Ace editor

### ISSUE THREAD

**Issue by apobbati** [swagger-api/swagger-ui#347]
It would be nice to have syntax highlighting, line-numbers, and pop-out for editing post parameters.

Ace would be a great candidate editor to embed instead of <textarea>.
http://ace.c9.io

Also, the response body should be syntax-highlighted based on content-type. that would be awesome.

**Comment by andrewboni** [comment]
+1 on this. Major pain to work without syntax highlighting / line numbers / et al
