### ISSUE TITLE
Is there a way to $ref enums?

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3471]
- swagger-ui version
latest
- a swagger file reproducing the issue
https://github.com/heldersepu/SwashbuckleTest/blob/master/swagger.json#L577

When we use the same enum multiple times in a controller the same enum data gets added per use. 
Is there a way to add the enum to the definitions and only have a reference to it?

**Comment by webron** [comment]
You can only reference an enum from complex objects - meaning only things in body parameters and responses. This changes in the new version of the spec.

**Comment by hkosova** [comment]
@heldersepu In 2.0, if you use YAML instead of JSON, there's a workaround using YAML anchors:
https://github.com/OAI/OpenAPI-Specification/issues/300#issuecomment-77669429

**Comment by heldersepu** [comment]
Awesome, looking forward to the new version...
