### ISSUE TITLE
UI returns error : Not sending proper POST request

### ISSUE THREAD

**Issue by hassanfarid** [swagger-api/swagger-ui#3472]
I have just taken latest docker image.

`#Setup Swagger UI`
`docker pull swaggerapi/swagger-ui`
`docker run -p 3080:8080 --name ae_api_ui -e API_URL=http://generator.swagger.io/api/swagger.json swaggerapi/swagger-ui`

I can visualize the API documentation, but I am unable to try it out in browser.

It returns server response: 'TypeError: Failed to fetch'

This is what UI sends, and fail:
`curl "http://10.x.xx.xx:1300/v2/login" -X OPTIONS -H "Access-Control-Request-Method: POST" -H "Origin: http://10.x.x.x:3080" -H "Referer: http://10.x.x.x:3080/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Access-Control-Request-Headers: content-type" --compressed`

The UI also produced a curl request below, which works from terminal. Does the UI require anyother server verification?

**Comment by webron** [comment]
Do you have a `host` defined in your API definition?

**Comment by hassanfarid** [comment]
@webron Yes, I have. 
"host": "IP:port"

That's the same address I have posted here, just encrypted IP address
```sh
curl "http://10.x.xx.xx:1300/v2/login" -X OPTIONS -H "Access-Control-Request-Method: POST" -H "Origin: http://10.x.x.x:3080" -H "Referer: http://10.x.x.x:3080/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -H "Access-Control-Request-Headers: content-type" --compressed```

**Comment by hassanfarid** [comment]
One more point to note, I don't have a server generated from swagger-generator. I have my own server in c++, that only listen for requests on this port.

**Comment by webron** [comment]
Does your server have CORS enabled?

**Comment by hassanfarid** [comment]
It is not a webs server. However, I access the same server with my web client on the same API.

**Comment by hassanfarid** [comment]
Imagine my server application as c++ application listening on a single port#. On my web client, I make ajax request to IP:port, and it works just fine.

**Comment by webron** [comment]
If it responds to HTTP requests, it's a web server, regardless if you wrote something from scratch or you use an existing framework. You have to make your server CORS enabled otherwise swagger-ui will not work.

**Comment by hassanfarid** [comment]
So, reworked everything to make it re producible.

I wrote my spec and generated nodejs-server code from editor.swagger.io

Hosted nodejs-server in a docker container.
Hosted swagger-ui in another docker container.

Tried to execute one /path - request -> Got an error.
`Error: Route defined in Swagger specification (/validateUser) but there is no defined options operation.<br> &nbsp; &nbsp;at send405 (/usr/src/app/node_modules/swagger-tools/middleware/swagger-router.js:306:13)<br> &nbsp; &nbsp;at swaggerRouter (/usr/src/app/node_modules/swagger-tools/middleware/swagger-router.js:421:16)<br> &nbsp; &nbsp;at call (/usr/src/app/node_modules/connect/index.js:239:7)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/connect/index.js:183:5)<br> &nbsp; &nbsp;at swaggerValidator (/usr/src/app/node_modules/swagger-tools/middleware/swagger-validator.js:371:14)<br> &nbsp; &nbsp;at call (/usr/src/app/node_modules/connect/index.js:239:7)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/connect/index.js:183:5)<br> &nbsp; &nbsp;at swaggerMetadata (/usr/src/app/node_modules/swagger-tools/middleware/swagger-metadata.js:450:14)<br> &nbsp; &nbsp;at call (/usr/src/app/node_modules/connect/index.js:239:7)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/connect/index.js:183:5)`

Copied curl command from swagger-ui and ran it into terminal, addressing same node-js container -> Got correct response.

**Comment by webron** [comment]
Can you try swagger-ui from this repo and not from the docker image?

**Comment by hassanfarid** [comment]
@webron Did you mean run swagger-ui from github repo? https://github.com/swagger-api/swagger-ui

I don't find steps to set this up. I can only find steps for docker container.

I tried with latest docker image v3.2.1; and I get this same response from swagger generated nodejs server.

`Request URL:http://10.32.5.98:1300/v2/validateUser
Request Method:OPTIONS
Status Code:405 Method Not Allowed
Remote Address:10.32.5.98:1300
Referrer Policy:no-referrer-when-downgrade`

This tells me that server does not support OPTIONS method.

I checked from terminal:
`curl -I http://10.32.5.98:1300/v2/validateUser`

`HTTP/1.1 405 Method Not Allowed
Allow: POST
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 1136
Date: Wed, 02 Aug 2017 10:42:19 GMT
Connection: keep-alive`

@webron what is your next suggestion?

**Comment by hassanfarid** [comment]
This is the error from nodejs server (generated today from swagger(): I hope you have latest generator deployed on your servers.

'Error: Route defined in Swagger specification (/validateUser) but there is no defined options operation.
    at send405 (/usr/src/app/node_modules/swagger-tools/middleware/swagger-router.js:306:13)
    at swaggerRouter (/usr/src/app/node_modules/swagger-tools/middleware/swagger-router.js:421:16)
    at call (/usr/src/app/node_modules/connect/index.js:239:7)
    at next (/usr/src/app/node_modules/connect/index.js:183:5)
    at swaggerValidator (/usr/src/app/node_modules/swagger-tools/middleware/swagger-validator.js:371:14)
    at call (/usr/src/app/node_modules/connect/index.js:239:7)
    at next (/usr/src/app/node_modules/connect/index.js:183:5)
    at swaggerMetadata (/usr/src/app/node_modules/swagger-tools/middleware/swagger-metadata.js:450:14)
    at call (/usr/src/app/node_modules/connect/index.js:239:7)
    at next (/usr/src/app/node_modules/connect/index.js:183:5)'

**Comment by webron** [comment]
To run the UI from this repository, all you need to do is clone the repository, and open dist/index.html.

**Comment by hassanfarid** [comment]
@webron Exact same error from running above repo on httpd container that allows CORS.

I think, there's something missing on nodejs server code generated.

`Error: Route defined in Swagger specification (/validateUser) but there is no defined options operation.
    at send405 (/usr/src/app/node_modules/swagger-tools/middleware/swagger-router.js:306:13)
    at swaggerRouter (/usr/src/app/node_modules/swagger-tools/middleware/swagger-router.js:421:16)
    at call (/usr/src/app/node_modules/connect/index.js:239:7)
    at next (/usr/src/app/node_modules/connect/index.js:183:5)
    at swaggerValidator (/usr/src/app/node_modules/swagger-tools/middleware/swagger-validator.js:371:14)
    at call (/usr/src/app/node_modules/connect/index.js:239:7)
    at next (/usr/src/app/node_modules/connect/index.js:183:5)
    at swaggerMetadata (/usr/src/app/node_modules/swagger-tools/middleware/swagger-metadata.js:450:14)
    at call (/usr/src/app/node_modules/connect/index.js:239:7)
    at next (/usr/src/app/node_modules/connect/index.js:183:5)`

**Comment by hassanfarid** [comment]
@webron This is not working. I believe it is related to nodejs-server code.

What you think?

**Comment by shockey** [comment]
Closing since this is pretty old.

@hassanfarid, if you're still having this problem, feel free to reply and I'll reopen and get this into our queue again!

**Comment by hassanfarid** [comment]
@shockey - I am sorry, for not filling on this communication actively. I lost track on this project for a while and got busy with something else.

Last time, I remember I got stuck in issues with swagger-codegen. NodeJS code generated by spec was not functional. Can't find an issue that I might have created for this.

I will discuss when I get back on this again.

**Comment by shockey** [comment]
@hassanfarid, no worries! 

The Codegen is a different project, but if you pick this bit back up feel free to bump here and we can pick up where we left off.

**Comment by devkanthjijj** [comment]
Can we please open this discussion up??? I have the same problem. Am I missing any updates. Please advise.

**Comment by DeepikaSharma11** [comment]
I am facing the same issue. I have enables CORS as well. The request is working from the swagger UI hosted on the same server as the application server but is giving the error for No options defined operation in the swagger and failing

**Comment by webron** [comment]
For better support, please file a new ticket following the issue template.
