### ISSUE TITLE
cacert option in swagger

### ISSUE THREAD

**Issue by SachAtTiwari** [swagger-api/swagger-ui#3479]
When reporting an issue, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue
Hi,

I am just 2 days old in swagger want to give cacert option in YAML

swagger: '2.0'
info:
  description: 'This is swagger test '
  version: 1.0.0
  title: REST Store
  termsOfService: 'http://xxxxx.com/terms/'
  contact:
    email: admin@xxxx.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 52.22.128.100
tags:
  - name: sample
    description: Operations 
    externalDocs:
      description: Testing
      url: 'https://52.22.128.100/'
schemes:
  - https
paths:
  /getName:
    post:
      tags:
        - token
      summary: Test Swagger
      description: ''
      operationId: testSwagger
      produces:
        - application/json
      parameters:
        - in: body
          name: testSwagger
          description: sample
          schema:
            type: object
            required:
              - sample
              - username
              - password
            properties:
              sample:
                type: string
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Success operation
          schema:
            type: object
            properties:
              msg:
                type: string
              sample:
                type: string

This produces below curl command 
curl -X POST "https://52.22.128.100/getName" -H "accept: application/json" -H "content-type: application/json" -d "{ \"sample\": \"string\", \"username\": \"string\", \"password\": \"string\"}"

I want below
curl  --cacert server.crt   -X POST "https://52.22.128.100/getName" -H "accept: application/json" -H "content-type: application/json" -d "{ \"sample\": \"string\", \"username\": \"string\", \"password\": \"string\"}"

or
curl   -X POST "https://52.22.128.100/getName" -H "accept: application/json" -H "content-type: application/json" -d "{ \"sample\": \"string\", \"username\": \"string\", \"password\": \"string\"}" -k

I can't change scheme.

**Comment by webron** [comment]
The spec doesn't support it. You'd either need to modify the code to add the functionality yourself, or open a ticket on the spec asking for it to be added.
