### ISSUE TITLE
OAS 3.0: Rendering oneOf and anyOf

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3490]
Version: 3.1.1

(This issue is specifically about model rendering, not example rendering or validation.)

OpenAPI 3.0 supports `oneOf` and `anyOf` in models. #3083 was supposed to cover "Render schema values with anyOf, oneOf, not", but it looks the rendering is not implemented yet.

On this image, `ArrayOfStrOrInt` is an array of `oneof` string or integer, and the blank item is `CatOrDot` which is `anyOf` Cat or Dog models. The full spec is below.

![oneof anyof](https://user-images.githubusercontent.com/8576823/28570778-5bc85e94-7148-11e7-9580-2a9c725cbaa2.png)

```
openapi: 3.0.0
info:
  version: 0.0.0
  title: test
paths: {}
components:
  schemas:
    # Item type is displayed
    ArrayOfStr:
      type: array
      items:
        type: string

    # Item type is NOT displayed
    ArrayOfStrOrInt:
      type: array
      items:
        oneOf:
          - type: integer
          - type: string

    # Neither model name nor contents is displayed
    CatOrDog:
      anyOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'

    Pet:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            huntingSkill:
              type: string
              description: The measured skill for hunting
              default: lazy
              enum:
              - clueless
              - lazy
              - adventurous
              - aggressive
    Dog:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            packSize:
              type: integer
              format: int32
              description: the size of the pack the dog is from
              default: 0
              minimum: 0
```

**Comment by webron** [comment]
@shockey I forget - wasn't this supposed to be implemented already? Or just in examples?

**Comment by shockey** [comment]
@webron, it was implemented (see https://github.com/swagger-api/swagger-ui/pull/3482/commits/189f048e9181826a4f6a91ac13417ca98c9cfdb9, which is present in the OAS3 rendering PR).

My guess is that it was gobbled by a merge commit - between OAS3 and the Model component changes, that seems possible.

I'll reapply the commit's changes through a new PR.

**Comment by hkosova** [comment]
@shockey - the fix seems to be incomplete and doesn't work for the sample spec I posted above.

It looks like the model renderer expects `type` alongside `oneOf`/`anyOf`, which is not necessarily the case. For example, this is rendered:
```
    CatOrDog:
      type: object  # <---- 
      anyOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
```
but this is not:
```
    CatOrDog:
      anyOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'

    ArrayOfStrOrInt:
      type: array
      items:
        oneOf:
          - type: integer
          - type: string
```

**Comment by hkosova** [comment]
Also, when using
```
    CatOrDog:
      type: object
      anyOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
```
the model names displayed by anyOf are incorrect.

![model-names](https://user-images.githubusercontent.com/8576823/28918973-24334cc4-7854-11e7-905b-4662232b6dd4.png)
