### ISSUE TITLE
OAuth2 + AAD + multi-tenant app (e.g. no redirect_uri)

### ISSUE THREAD

**Issue by cmshawns** [swagger-api/swagger-ui#3495]
- swagger-ui version

2.2.10 (I think. Using Swashbuckle 5.6.0)

- a swagger file reproducing the issue

N/A - To reproduce the issue you would need access to our Azure AD app.

------

We're having some trouble getting the "Try it" button to work with our Azure Active Directory flow. I've looked at a number of issues and tutorials - including [_Enable Swagger to authenticate against Azure AD_](https://blogs.msdn.microsoft.com/pratushb/2016/04/28/enable-swagger-to-authenticate-against-azure-ad/) - but all of them seem to assume that the user will be redirected back to `http://{your_swagger_url}/swagger/ui/o2c-html`.

We use a multi-tenant, native app for authentication - each installation of the web service then authenticates against _their_ tenant, which in turn trusts our app. This means the service does not - **should not** - have the client secret (for the multi-tenant app). Nor can the client app know all the various installations of the web service, so the users cannot be redirected back to them. Our authentication flow returns a token that can then be included (as a Bearer) in successive requests for authentication.

We're using Swashbuckle to generate the UI and I've opened a related issue with them:

domaindrivendev/Swashbuckle#1150

I've tried several things to get authentication working from our Swagger UI, but the closest I can get is one of the following two scenarios after logging in to their AAD:

1. User is redirected back to `http://{their_host}/swagger/ui/o2c-html`, which fails because it hasn't been registered as a trusted client with the AAD app, or
2. User is redirected to a trusted URL we've configured for the AAD app, but fails because this is not an actual endpoint. It's just an identifier.

Any guidance or help that can be provided would be very welcome.

**Comment by shockey** [comment]
@cmshawns, apologies for this not getting any timely attention! I'd be happy to take a look at this, but first I'd like an indication from you that this is still relevant.

Pending that, I'm going to close this ticket. I'll reopen if I hear from you!
