### ISSUE TITLE
Errors thrown when url contains a hash `/#/` and a query param or url encoding

### ISSUE THREAD

**Issue by EWhite613** [swagger-api/swagger-ui#3504]
Can reproduce via http://petstore.swagger.io/#/?foo=bar
and the following error will be thrown:
`Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '#operations-tag-?foo=bar' is not a valid selector.`
The error doesn't seem to affect the demo page but it affects the usage of swagger-ui in our app from https://github.com/rynam0/ember-swagger-ui where the error is similar to the one listed, causing selectors to crash. Version of swagger-ui used is (2.2.10)

**Comment by EWhite613** [comment]
Also crash on urls with encoded components. Example: http://petstore.swagger.io/#/%2

**Comment by webron** [comment]
@EWhite613 Do you have the `deepLinking` configuration turned on?

**Comment by EWhite613** [comment]
@webron I'll try it out I don't think that feature is available in 2.2.10 (version `ember-swagger-ui` uses). I'll try that out locally and see if that works

**Comment by webron** [comment]
Aha, it's not. I assumed you're using the latest, missed that you mentioned it in your original post. However, that version uses a different structure. 

There's not much we can do with that version though, we don't actively maintain it anymore.

**Comment by shockey** [comment]
@EWhite613 Try using http://petstore.swagger.io/?foo=bar#/ instead.

Per the URI syntax specification, query strings must come before fragments:

> relative-ref  = relative-part [ "?" query ] [ "#" fragment ]
>
> [https://tools.ietf.org/html/rfc3986#section-4.2](https://tools.ietf.org/html/rfc3986#section-4.2)

---

You raise a valid point for 3.x though (http://petstore.swagger.io/#/%2) - the fragment value isn't being unencoded correctly. That's a bug!

**Comment by shockey** [comment]
I'll also add - the querySelector in 3.x is contained, so that it doesn't bring down the whole app if it fails. Consider migrating to 3.x 😄
