### ISSUE TITLE
Unable to Add Headers to "Try It Now" Curl Request

### ISSUE THREAD

**Issue by pjm16** [swagger-api/swagger-ui#3506]
hi @webron,
I was having problems working with Swagger-ui headers & wondered if you could offer some direction?

I've cloned the code v3.1.2 & added my own plugin to inject an Authorization token + an api_key into the header. It worked well & I was able to pull down the Swagger document from the server.

However In the "Try It Now" section I noticed the headers were not applied to the CURL methods & I really cant figure out how to do it.  I cant tell if it's an issue eg #3499 or is there something I can do?

In v2 I think it worked natively when we applied the "ApiKeyAuthorization" method as below.
         var auth2 = new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + token, "header");
         swagUI.api.clientAuthorizations.add("Authorization", auth2);

Any advice would be appreciated

![image](https://user-images.githubusercontent.com/29760363/28848823-63d2030c-76e2-11e7-85b3-681fcd413341.png)
![image](https://user-images.githubusercontent.com/29760363/28848836-6ab2187e-76e2-11e7-87d1-4fe81cf72bd0.png)
![image](https://user-images.githubusercontent.com/29760363/28848843-6f528076-76e2-11e7-9fb1-0df6dfcd99a3.png)

**Comment by shockey** [comment]
Hi @pjm16, can you share the complete code for your plugin? That would make this much easier to debug.

**Comment by pjm16** [comment]
hi @shockey thanks for coming back to me.

I've attached my-download-url.js where I'm adding a bearerToken and swaggerType values into the header.  I've attached the client file also fyi - swaggetDoc.ts - where I'm adding those values into the call.

I did come up with *a* solution for adding those same headers into the "Try it Now" Curl commands so I've attached my action.js file which I've updated.  I'm extracting "bearerToken" and "swaggerType" from the config in the same way & adding them into the parsedRequest.headers.

This solution is ok but I'd be still interested in any improvements as it may be a slight hack.  I wondered if there was more of a "plugin" way to do this, rather than updating the swagger-ui code directly

Regards

[my-download-url.js.txt](https://github.com/swagger-api/swagger-ui/files/1200466/my-download-url.js.txt)
[swaggerDoc.ts.txt](https://github.com/swagger-api/swagger-ui/files/1200467/swaggerDoc.ts.txt)
[actions.js.txt](https://github.com/swagger-api/swagger-ui/files/1200468/actions.js.txt)

**Comment by pjm16** [comment]
Hi @shockey, I just saw that my update to actions.js does show my headers in the Curl window, however those headers are not then being used in the "Execute" method.  

So I was still hoping to find a way to display CURL headers that are also used in the request when I hit "Execute"

**Comment by shockey** [comment]
Hey @pjm16, as luck would have it, someone has opened a PR for request and response interceptors: see #3534.

The request interceptor, as proposed, should allow you to mutate the request so that both the cURL output and the live request include your custom headers.

I'm hoping to get that merged this week.

**Comment by pjm16** [comment]
Hi @shockey thanks for the update I think interceptors will work really well here. I'd be interested in going back & updating my solution when they'r'e available.

I ended up adding to the our incoming Swagger documents with something like:
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "SwaggerType": {
            "type": "apiKey",
            "name": "x-some-docrequest",
            "in": "header"
        }
I then called the ui.authactions.authorize method to populate those values - eg
        ui.authActions.authorize(        
        {
            Bearer: {
                name: "Bearer", schema: {type: "apiKey", in: "header", name: "Authorization", description: "Bearer Token"}, value: bearerToken
            }
        })

However, it would be great to just use interceptors rather than having to tweak the Swagger documents as they're not in our control

**Comment by shockey** [comment]
Glad you got it working!

It's always best to describe the authorization you're using, in your document! We have a ticket open for an official API for injecting authorization values at runtime, but it hasn't been implemented yet. When that goes live, that will be a better solution than `ui.authactions.authorize`.

Note that the `authactions` stuff is _not_ part of the official public API, so it could be changed at any time - though I don't know of anything that will be changing it. If you're using that, be careful when bumping the swagger-ui version you're using.

--

FYI, I just merged the interceptor PR, so you should be able to use them in the version that we'll release tomorrow evening.

Closing! Let me know if I can help any more with this, and I'll reopen.
