### ISSUE TITLE
Less- and Greater-Sign in Markdown not rendered correctly

### ISSUE THREAD

**Issue by ravenpride** [swagger-api/swagger-ui#3510]
The issue refers to Swagger-UI 3.1.2.

I've tried to make use of less- and greater signs in the `description` field and failed.

Example:
```
    ```
    This is a less sign <
    This text can be seen...
    ```
```

Generates:
`This is a less sign &lt; This text can be seen...`

I know, that the less/greater sign is problematic in markup due to the element tags in HTML, but I would expect that everything in fenced code blocks is rendered as is. A transformation step that replaces `<` with `&lt;` and `>` with `&gt;` is surely necessary, but the effect is not as desired, I think.

Even worse, the following snippet generates nothing (please note, that any character after the less sign causes this behavior):

```
    ```
    This is a less sign <x
    This text can not be seen...
    ```
```
I would appreciate a hint, how I could work around the issue or a fix that solves it.

Thank you in advance!

**Comment by webron** [comment]
@shockey is this related to the sanitation?

**Comment by shockey** [comment]
Hey @ravenpride, sorry you're having issues.

@webron is onto something, this is a result of our using https://github.com/punkave/sanitize-html to sanitize Markdown after it's converted to HTML.

This issue has been raised on their end several times, it's quite clear that it's a wontfix on their end:

- https://github.com/punkave/sanitize-html/issues/87
- https://github.com/punkave/sanitize-html/issues/88
- https://github.com/punkave/sanitize-html/issues/94
- https://github.com/punkave/sanitize-html/issues/62
- https://github.com/punkave/sanitize-html/issues/142
- https://github.com/punkave/sanitize-html/issues/127

---

`<x...` being mangled makes sense to me, since it effectively represents an unclosed HTML tag in the Markdown. Same with `<`, it could be interpreted as a malformed tag opening.

What does strike me as strange is that escaping it in the description itself (i.e. changing `<` to `&lt;`) doesn't work either.

I think this is a bug, or at least a user experience problem.

**Comment by shockey** [comment]
Poked around a bit more and found a helpful opinion in Remarkable (which we use via `react-remarkable` for Markdown rendering):

> This should be expected I believe. You obviously already know this, but just to re-clarify, the whole premise of a markup language/syntax (like HTML) is just that, there's some sort syntax that's special and used for markup. Hence when you want to use actual < or > in your document, they have to be escaped.
> 
> Now when you're typing markdown though, this shouldn't really make any difference to you, i.e. the person writing the original markdown content in the first place. You shouldn't need to type `&gt;` in your markdown code block instead of just >, because whatever you're using to convert the markdown to html (in this case remarkable), should be doing that for you. The result is that you see the correct thing in the actual html document in the browser.
>
> https://github.com/jonschlinkert/remarkable/issues/147#issuecomment-144340514

**Comment by vyp** [comment]
In case this helps: [remarkable demo](http://jonschlinkert.github.io/remarkable/demo/#md64=JTdCJTIyc291cmNlJTIyOiUyMiU2MCU2MCU2MCU1Q25UaGlzJTIwaXMlMjBhJTIwbGVzcyUyMHNpZ24lMjAlM0MlNUNuVGhpcyUyMHRleHQlMjBjYW4lMjBiZSUyMHNlZW4uLi4lNUNuJTYwJTYwJTYwJTVDbiU1Q24lNjAlNjAlNjAlNUNuVGhpcyUyMGlzJTIwYSUyMGxlc3MlMjBzaWduJTIwJTNDeCU1Q25UaGlzJTIwdGV4dCUyMGNhbiUyMG5vdCUyMGJlJTIwc2Vlbi4uLiU1Q24lNjAlNjAlNjAlMjIsJTIyZGVmYXVsdHMlMjI6JTdCJTIyaHRtbCUyMjpmYWxzZSwlMjJ4aHRtbE91dCUyMjpmYWxzZSwlMjJicmVha3MlMjI6ZmFsc2UsJTIybGFuZ1ByZWZpeCUyMjolMjJsYW5ndWFnZS0lMjIsJTIybGlua2lmeSUyMjpmYWxzZSwlMjJsaW5rVGFyZ2V0JTIyOiUyMiUyMiwlMjJ0eXBvZ3JhcGhlciUyMjpmYWxzZSwlMjJfaGlnaGxpZ2h0JTIyOmZhbHNlLCUyMl9zdHJpY3QlMjI6ZmFsc2UsJTIyX3ZpZXclMjI6JTIyaHRtbCUyMiU3RCU3RA==)

Just to clarify, if you click the source button, you'll see that `<` has indeed been converted to `&lt;`, but of course the text displays as expected. (So what @ravenpride is seeing is a bug in my opinion, but not with remarkable at least.)

Remarkable follows the CommonMark spec, here are the relevant sections from the spec:

http://spec.commonmark.org/0.28/#example-79
http://spec.commonmark.org/0.28/#example-88

In case that helps with bringing up the issue with punkave/sanitize-html. :woman_shrugging:

(Note a new spec version just came out recently and so remarkable may not be up to date with everything the latest spec says.)

**Comment by jnoob** [comment]
I encountered the same problem. In my case, '&' has been converted to '&amp', I modified [https://github.com/swagger-api/swagger-ui/blob/v3.1.6/src/core/components/providers/markdown.jsx](https://github.com/swagger-api/swagger-ui/blob/v3.1.6/src/core/components/providers/markdown.jsx), append `.replace(/&amp;/g, "&")` to the `textFilter` in `sanitizeOptions`. It works.

**Comment by tbarsballe** [comment]
I've encountered a similar issue, trying to document large XML examples inside code blocks.

For example:

![screen shot 2017-09-20 at 4 06 12 pm](https://user-images.githubusercontent.com/9271497/30671819-b9ae3ba8-9e1d-11e7-8266-7fd8abd32140.png)

All < and > are inside code blocks, and should be getting rendered.

**Comment by webron** [comment]
This issue seems to have been resolved. Please reopen or file a new ticket otherwise.
