### ISSUE TITLE
UI does not show the default value when one is assigned for an enum

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#3518]
The GET in the below OpenAPI yaml contains a parameter named imageSize, but the rendering of the query parameters does not disclose the default. Note that swagger-codegen (-l html) includes the default at the end of the description field
```
swagger: "2.0"
info:
  version: "1"
  title: Missing default for enum 
  description: Demonstrate Swagger UI bug not showing default for an enum
basePath: /enumDefault
schemes:
- "http"
paths:
  /example:
    get:
      summary: Get a diagram
      description: Get a diagram
      produces:
      - application/json
      parameters:
      - name: imageSize
        in: query
        type: string
        enum:
        - thumbnail
        - icon
        - scaled
        - fullsize
        required: false
        default: thumbnail
        description: The layout type. 
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/diagram"
          headers:
            Location:
              description: The URL of the diagram.
              type: string
              format: uri
definitions:
  diagram:
    title: Diagram
    description: The representation of a diagram.
    properties:
      id:
        type: string
        description: The unique identifier for the diagram.
      imageSize:
        type: string
        enum:
        - thumbnail
        - icon
        - scaled
        - fullsize
        default: thumbnail
        description: The layout type. 
```

current Swagger UI rendering:
![missing-default-for-enum-parameter](https://user-images.githubusercontent.com/545944/28941964-aea28042-7867-11e7-9106-e17d07319abe.png)

**Comment by bthorstad** [comment]
In addition to not showing the default, the rendering does not enumerate the valid values; whereas `swagger-codegen (-l html)` does.

**Comment by DavidBiesack** [comment]
However the Try it Out drop down does list the enumerated values and properly selects the default. but the doc should also show this w/o having to open the Try It Out. The default for an enum in the definitions/models is shown correctly.

**Comment by masterof0** [comment]
I am having a similar issue where the UI does not show enum options for parameters in the default view or the 'try it out' view. I only get a string input. In this particular example. I have defined values for category, but they do not show in the UI

![enum](https://user-images.githubusercontent.com/565883/31592199-283877fa-b1ec-11e7-8c71-cc95d33c3c29.jpg)

**Comment by shockey** [comment]
@masterof0, I think you're describing a related, but different issue. We'd appreciate it if you would open a new ticket for that!

**Comment by hkosova** [comment]
> @masterof0 commented:
>> I am having a similar issue where the UI does not show enum options for parameters in the default view or the 'try it out' view.
>
> @shockey commented:
>> I think you're describing a related, but different issue. We'd appreciate it if you would open a new ticket for that!

I opened #3873 about rendering enums in parameter descriptions.

**Comment by webron** [comment]
Closing as resolved, thanks for reporting!

**Comment by DenisGorbachev** [comment]
@webron could you please point to commit where the default values are displayed in Swagger UI for 2.0 version of specification? As far as I see in my Swagger UI, it's not resolved yet.

**Comment by shockey** [comment]
@DenisGorbachev, I believe this commit added the default value display: https://github.com/swagger-api/swagger-ui/commit/a47da98b54d122979bb8754e3050a4df0cc50d48
