### ISSUE TITLE
Character  Â  appearing while rendering fields tagged as required

### ISSUE THREAD

**Issue by madheshr** [swagger-api/swagger-ui#3525]
Hi
  We are facing an issue wherein the mandatory fields are getting rendered with a special character- Â.  It appears like 

<field> Â *required
  
  where <field> is my field that has been declared as mandatory

- swagger-ui version: 2.9.0

I have checked the HTML source and see
<meta charset="UTF-8"> as one of the header

I have also checked to see if the file has any special characters, but did not find anything.  I have attached the swagger.json  (renamed to swagger.json.txt to enable upload)
[swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/1201961/swagger.json.txt)

The issue is only present while rendering "mandatory" fields  (fields marked as required = true).
Thanks

**Comment by webron** [comment]
There's no version 2.9.0. We have version 2.1.X and then 3.0.X and now 3.1.X. Please check the version you're actually using,.

Testing the latest version, I do not see the issue you've mentioned.

**Comment by WorkForPizza** [comment]
Had this issue as well. Turns out all I needed to fix it was set the charset in the html. 

Add this line to your header:   
`<meta charset="utf-8">`

**Comment by madheshr** [comment]
Thanks.  In my case we already have the
<meta charset="utf-8"> in the html header

We are using springfox-swagger-ui  version 2.7.0 as a maven artifact

**Comment by shockey** [comment]
This was discussed in another issue: https://github.com/swagger-api/swagger-ui/issues/3166#issuecomment-312619959

Looks like this helped in that case:

```
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
```

Also, it's worth noting that `<meta charset="UTF-8">` is used in our repository (https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L5).

**Comment by madheshr** [comment]
Hi

These two tags did the trick.. Thanks.

**Comment by viv84** [comment]
I had to add the charset="UTF-8"attribute to the 2 javascript tags for swagger-ui-bundle.js and swagger-ui-standalone-preset.js to resolve this. Adding the tags recommended above to the head section did not do the trick using swagger-ui v3.4.3.
<script src="./swagger-ui-bundle.js" charset="UTF-8"> </script>
<script src="./swagger-ui-standalone-preset.js" charset="UTF-8"> </script>

**Comment by Bagge42** [comment]
Hello

Currently facing the issue with Ã‚Â appearing. Attempted with all of the suggested meta additions to the index file, as well as the suggestions from https://github.com/swagger-api/swagger-ui/issues/3525. None works so far. Any ideas?

**Comment by shockey** [comment]
@Bagge42, meta charset should solve your issue.... if not, please open a new ticket 😄
