### ISSUE TITLE
'Try it out' misbehaving in edge

### ISSUE THREAD

**Issue by JoshuaWhatley** [swagger-api/swagger-ui#3533]
Issue is occurring in V3, and seems to be independent of the document used. It is reproducible with http://petstore.swagger.io/v2/swagger.json 

![image](https://user-images.githubusercontent.com/3322909/29047817-713d5826-7b82-11e7-8c80-6551a57ded2f.png)

No failures indicated in the developer tools.

It is unclear at this time whether this is an issue with edge or with the swagger-ui. I am hoping someone might be able to provide some insight into what might be happening here. Otherwise, I am reaching out to the edge folks to see if the issue is on their end.

Edge Version: 40.15063.0.0

**Comment by webron** [comment]
@JoshuaWhatley which version of swagger-ui exactly have you tested this with?

**Comment by JoshuaWhatley** [comment]
I am using 3.0.17. But I was able to reproduce this on petstore.swagger.io I am assuming the most recent version is hosted there?

This doesn't seem to occur with every version of Edge, so I imagine this issue is likely on their end.

**Comment by shockey** [comment]
I think this is related to https://github.com/swagger-api/swagger-editor/issues/1371 - the OP in that ticket was using the same Edge version as you. 

An inability for Swagger-UI to read the `Content-Type` header would cause the `Unknown response type` message, and the underlying Edge bug in the ticket linked has to do with Edge implementing a nonstandard interface for fetch headers.

Try using the workaround I mentioned there - if you remove `window.fetch` before instantiating Swagger-UI, the polyfill we being with us _should_ take over and not give you any issue.

**Comment by JoshuaWhatley** [comment]
Thanks @shockey, I'll add that polyfill and wait on their fix.

**Comment by ltraus** [comment]
Looks like this is a problem still in 3.12?

**Comment by shockey** [comment]
@vaustral yep, nothing was fixed on our end since it’s a browser bug. see the comments and links above for ways to mitigate the problem 😀

**Comment by vaustral** [comment]
Ah thanks, i didn't even see it.
