### ISSUE TITLE
Swagger Authorization Popup - UI usability enhancement 

### ISSUE THREAD

**Issue by JBaltika** [swagger-api/swagger-ui#3537]
Hi guys,
This annoying Swagger authorization popup issue. Its needs a button 'close' at the bottom as  'x' at the top right is not the best place and confusing for folks who starting using swagger. I saw how three different folks (salesman/non-technical) during demos has same issue. 

I think its trivial to add another button to close popup. What do you think?

![swaggerui-popup](https://user-images.githubusercontent.com/1755340/29068656-b6751a40-7c05-11e7-997a-bce169915608.jpg)

**Comment by JBaltika** [comment]
Hi guys, that is the status of this trivial change?

**Comment by webron** [comment]
@shockey button should say `Done`.

**Comment by shockey** [comment]
Fixed by #3939 :smile:

**Comment by shockey** [comment]
Thanks for the report @JBaltika! This will go live as part of our next release.
