### ISSUE TITLE
typeless schemas are not rendered in Models

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3545]
Version: 3.1.4

Schemas without `type` are not rendered in the Models section.

![anyvalue](https://user-images.githubusercontent.com/8576823/29113368-853bbd9a-7cf9-11e7-93b0-33d691d09b3f.png)

2.0 spec:
```
swagger: '2.0'
info:
  title: test
  version: 0.0.0
paths: {}
definitions:
  # this is rendered
  Tag:
    type: string

  # but this is not
  AnyValue:
    description: Can be any value - string, number, object, etc.
```
3.0 spec:
```
openapi: 3.0.0
info:
  title: test
  version: 0.0.0
paths: {}
components:
  schemas:

    # this is rendered
    Tag:
      type: string

    # but this is not
    AnyValue:
      nullable: true
      description: Can be any value, including null.
```

**Comment by hkosova** [comment]
This seems to work in Editor 3.1.12.
@shockey could you please confirm?

**Comment by shockey** [comment]
Appears to work now:

<img width="1418" alt="messages image 4233516752" src="https://user-images.githubusercontent.com/680248/32295553-db0d9294-bf06-11e7-9430-93215d909501.png">
<img width="1418" alt="messages image 871884959" src="https://user-images.githubusercontent.com/680248/32295560-de5832c4-bf06-11e7-9625-4a30ed69da51.png">


Thanks for the report, @hkosova! Some related PR must have fixed this.

Closing!
