### ISSUE TITLE
Sections Server response and Responses are too similar

### ISSUE THREAD

**Issue by lcofre** [swagger-api/swagger-ui#3546]
When using Swagger UI is difficult to distinguish between the sections "Server response" and "Responses".
Users of the documentation usually confuse them taking the example values as the response from the server.
![2017-08-09 16_21_56-swagger ui](https://user-images.githubusercontent.com/1630156/29129514-f9838afa-7d1e-11e7-9cbe-1c8217a848c8.png)

Thanks for this excellent project!

**Comment by shockey** [comment]
My first thought is that a different background color for the code blocks of the server response would be a good differentiator.
