### ISSUE TITLE
Swagger 1.5.10: Request url for each API is wrong

### ISSUE THREAD

**Issue by JessieGit** [swagger-api/swagger-ui#3551]
I am using Swagger 1.5.10. The  host is: https://myapp.rch.stglabs.com:8443/ibm/api/explorer. After the APIs are loaded, the request url for each API becomes: https://myapp:8443/relativePath/apione.
Does anyone know the reason? I have done lots of research online and have tried to specify host by adding this line into server.xml, but no luck.
\<variable name="defaultHostName" value="https://myapp.rch.stglabs.com:8443" /> 

Any suggestion or help will be highly appreciated.

**Comment by shockey** [comment]
@JessieGit, `1.5.10` is not a valid version of Swagger-UI, and I'm not sure we've ever supported configuration via a `server.xml` file, or a `defaultHostName` option.

Are you using Swagger-UI directly, or through a third-party project?

**Comment by webron** [comment]
@JessieGit I'm guessing you're using swagger-core - please file the issue there.

**Comment by JessieGit** [comment]
No, I am using Liberty. The swagger version is: swagger-1.5.10.  I am actually using swagger-annotation. Not sure why you concluded I am using swagger-core. Could you please reopen this issue?

**Comment by JessieGit** [comment]
@shockey I am using swagger-annotation. The liberty api-discovery will work together with swagger-annotation, right? I don't configure swagger via server.xml. I am just configuring the host information. Of course, add api-discovery feature.

**Comment by shockey** [comment]
@JessieGit, this repository is for the Swagger-UI project, which is a JavaScript application that displays Swagger/OpenAPI definitions in a browser. Nobody here is a Java developer, so we can't help you with annotations here.

From a Google search, it appears that the annotations package is a part of the swagger-core project: https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X.

Consider filing an issue over at swagger-core, maybe they can help: https://github.com/swagger-api/swagger-core/issues/new

**Comment by webron** [comment]
@JessieGit - as @shockey mentioned, swagger-annotations is part of swagger-core, which Liberty uses. However, if you're having issues with Liberty, please contact IBM's support, this is out of scope for us.
