### ISSUE TITLE
Slow endpoint loading/open with many paths

### ISSUE THREAD

**Issue by webjoel** [swagger-api/swagger-ui#3560]
[swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/1217892/swagger.json.txt)
I have an API that contains more than 100 paths, after loading in swagger ui and clicking on the endpoint takes a lot time to open, without even showing a "loading", this I have not yet mapped the responses of the path.

Is there any way to improve performance? Lazy loading / rendering? My swagger.json has 128 KB.

Version of Swagger UI: 3.1.4.
Example JSON attached.

**Comment by webron** [comment]
Please add a comment to #1919.
