### ISSUE TITLE
My server port is 8080 authorize url port change to 3200?

### ISSUE THREAD

**Issue by jast90** [swagger-api/swagger-ui#3566]
My server port is 8080 , but  authorize url port change to 3200 looks like :
`http://localhost:8080/oauth/authorize?response_type=code&client_id=foo&redirect_uri=http%3A%2F%2Flocalhost%3A3200%2Foauth2-redirect.html&scope=read%20write&state=TW9uIEF1ZyAxNCAyMDE3IDE2OjIxOjA3IEdNVCswODAwICjkuK3lm73moIflh4bml7bpl7Qp`

**Comment by webron** [comment]
The URLs are provided as part of your API definition. Simply change them there.

**Comment by jast90** [comment]
Add oauth2RedirectUrl can solve it .
```
 const ui = SwaggerUIBundle({
            url: "/v2/api-docs?group=public-api",
            dom_id: '#swagger-ui',
            oauth2RedirectUrl:"/oauth2-redirect.html",
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],
            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout"
        })
```
