### ISSUE TITLE
Petstore opens constantly

### ISSUE THREAD

**Issue by petroskidragan** [swagger-api/swagger-ui#3568]
I have problem with swagger ui version 3.1.4 . I am using <groupId>org.apache.cxf</groupId><artifactId>cxf-rt-rs-service-description-swagger</artifactId> type of Swagger and after runing my application on web only shows Petstore page and not my API UI documentation.  I am accessing:  http://localhost:9001/api-docs?/url=/swagger.json , but it shows Petstore page .

![image](https://user-images.githubusercontent.com/18696091/29270760-89e5c5d6-80f8-11e7-813c-0a2f89277b71.png)

Any help how can I resolve this issue ? 

Hope to hear from you soon

**Comment by webron** [comment]
Try using http://localhost:9001/api-docs?url=/swagger.json instead.
