### ISSUE TITLE
OAS 3.0 doesn't render in IE11, failing to find startsWith function

### ISSUE THREAD

**Issue by arturdzm** [swagger-api/swagger-ui#3571]
Since IE11 doesn't support startsWith function, we could add something like that to define it.

```
if (!String.prototype.startsWith) {
  String.prototype.startsWith = function(searchString, position) {
    position = position || 0;
    return this.indexOf(searchString, position) === position;
  };
}
```

**Comment by shockey** [comment]
Likely solution: add `core-js/es6/string` to [src/polyfills.js](https://github.com/swagger-api/swagger-ui/blob/master/src/polyfills.js), since [that polyfill includes `startsWith`](https://github.com/zloirock/core-js#ecmascript-6-string).

**Comment by floriantraber** [comment]
If this is not planned currently, I will fix it next week as we're impacted by this bug.

**Comment by shockey** [comment]
@floriantraber, feel free to make a contribution :smile: I don't know of anyone working on this currently.

**Comment by craigjbass** [comment]
Came across this bug today - not great as customer relies on IE11. Is there anything we can do to help move #3930 along?
