### ISSUE TITLE
How to send Date as a request header parameter from Swagger-UI?

### ISSUE THREAD

**Issue by msgopalan** [swagger-api/swagger-ui#3572]
Hi,
The date parameter is not getting delivered to the application, if it is been sent from Swagger UI. 

`@ApiImplicitParam(name = "Date", value = "Request Origination time", required = false, dataType = "string", paramType = "header")})`

![image](https://user-images.githubusercontent.com/26313800/29287311-96a031b0-80fa-11e7-81b9-d0598d3df10c.png)

Please help me resolving this issue.

**Comment by webron** [comment]
We recently added a template to new issues asking for information to be provided. We need that information in order to be able to provide better support. Please re-file an issue and follow the questions and guidelines in it.
