### ISSUE TITLE
When Logout not refresh  oauth2 flow the code is old (access code flow)?

### ISSUE THREAD

**Issue by jast90** [swagger-api/swagger-ui#3574]
When I logout and reauthorize then request token but I find the code of the request parameter is not refresh,is a bug or I need add some configuration?

**Comment by shockey** [comment]
Hi @jast90,

We recently added a template to new issues asking for information to be provided. We need that information in order to be able to provide support. Please re-file an issue and follow the questions and guidelines in it.
