### ISSUE TITLE
Custom "Example Value"

### ISSUE THREAD

**Issue by zmacomber** [swagger-api/swagger-ui#3577]
Is there a way to set a custom "Example Value"?  I'm using the "dist" standalone version and initialing via "window.ui = SwaggerUIBundle..." as per the docs on using the standalone (non-nodejs) version.  One would think I could somehow tap into that "SwaggerUIBundle" object or some child and "setExampleValue" or "getExampleValue" but it looks like the only way to update that value is via manipulating the DOM.

**Comment by webron** [comment]
You can set it through your API definition directly, in specific cases.

**Comment by zmacomber** [comment]
@webron Thanks for quick reply.  Is https://swagger.io/docs/specification/adding-examples/ the appropriate place to consult on how to do this?

**Comment by webron** [comment]
If you're using OAS3. If you're using Swagger/OpenAPI 2, then https://swagger.io/docs/specification/2-0/adding-examples/.

**Comment by zmacomber** [comment]
Thanks
