### ISSUE TITLE
Assets not loading

### ISSUE THREAD

**Issue by navsaini** [swagger-api/swagger-ui#3578]
I am using swagger-ui through a React component to display various swaggers, and in the cases of certain swagger specs, the assets do not load correctly. For example -- 
![screen shot 2017-08-15 at 3 10 51 pm](https://user-images.githubusercontent.com/12906210/29334120-f5d26096-81cb-11e7-9ab0-f05786dad2e3.png)
The lock next to the "Authorize" text is missing.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.1.4
| How did you install Swagger-UI? | npm 
| Which browser & version?        | Google Chrome 60.0.3112.90 (Official Build)
| Which operating system?         | macOS Sierra

### Demonstration API definition

Cannot provide entire spec because of confidentiality but can provide certain information about spec.

### Configuration (browser query string, constructor, config.yaml)

```js
        new SwaggerUIBundle({
            dom_id: '#swaggerContainer',
            spec: this.state.spec,
            presets: [presets.apis]
        });
```

### Expected Behavior

Icons should be present where they are not

### Current Behavior

Currently missing these icons

**Comment by shockey** [comment]
I think this is because we're embedding SVGs into our index.html: https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L34.

@Minasokoni, thoughts?

**Comment by Minasokoni** [comment]
@shockey Im going to make the loading of the icons a component and have that append to the DOM so that it loads in with the application without needing the index.html file.

**Comment by markmssd** [comment]
Facing the same issue, any progress on that? :)

**Comment by webron** [comment]
@Minasokoni Look at how many people gave you a 👍 and you left them all disappointed ;)

**Comment by jnovick** [comment]
I'm still having this issue. Why is this issue closed? Is it resolved somewhere?

**Comment by heldersepu** [comment]
@jnovick The issue still open...

**Comment by jnovick** [comment]
Sorry, I saw the word closed referring to Arrow not visible #3995 and thought this issue was marked as closed.

**Comment by shockey** [comment]
This is fixed! Going forward, you won't need to provide the SVG data in the HTML you use to display Swagger-UI.

**Comment by ZimbiX** [comment]
Do I have to do something to enable the fix? =S I've updated our Dockerfile for the image that's supposed to include it, `swaggerapi/swagger-ui:v3.13.4`, but the SVGs don't show up.
