### ISSUE TITLE
Dropdown for discriminator

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-ui#3581]
Please add dropdown for discriminator like
https://github.com/Rebilly/ReDoc/blob/master/docs/images/discriminator-demo.gif

From https://github.com/Rebilly/ReDoc

**Comment by jjakubik** [comment]
This is a duplicate of #2438 and #1526 . But I wonder if the ReDoc solution is close to what is needed for Swagger UI--could it be ported?

**Comment by raderio** [comment]
Any news about when it will added?

**Comment by webron** [comment]
Closing in favor of #2438.
