### ISSUE TITLE
Operation.jsx should become a Container Component

### ISSUE THREAD

**Issue by owenconti** [swagger-api/swagger-ui#3584]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature request
| Which Swagger/OpenAPI version?  | 2 and 3
| Which Swagger-UI version?       | 3+
| How did you install Swagger-UI? | Git clone and `npm run dev`
| Which broswer & version?        | Chrome 60
| Which operating system?         | MacOS

### Demonstration API definition

Any API definition will do.

### Configuration (browser query string, constructor, config.yaml)

None

### Expected Behavior

Expected that container components are responsible for gathering their (and their childrens') data, and checking whether or not they need to re-render.

### Current Behavior

Operation.jsx is currently a regular component which gets passed all of its data and does not check whether or not it needs to re-render, therefore always re-rendering.

### Possible Solution

Introduce container components into the tree.

### Context

This affects all specs, but is very noticeable in large swagger specs.

**Comment by shockey** [comment]
![Don't let your dreams be dreams](https://media.giphy.com/media/ACcXRXwUqJ6Ok/giphy.gif)

**Comment by webron** [comment]
@owenconti consider yourself the winner of this feature request!
