### ISSUE TITLE
host and basepath

### ISSUE THREAD

**Issue by jeusdi** [swagger-api/swagger-ui#3585]
Swagger UI is receiving this json:

```
{
	"swagger": "2.0",
	"info": {
		...
	},
	"host": "guest1:8080",
	"basePath": "dbox/cmng"
}
```

When I'm trying to execute requests, it's trying to make requests on: `"http://guest1:8080/account`. However, It should make request against `"http://guest1:8080/dbox/vmng/account`.

I'm creating this json information on my webapp application:

```
    Swagger swagger = new Swagger().info(info);
    swagger.setHost("guest1:8080");
    swagger.setBasePath("dbox/cmng");
```

How could I solve that? Why does swagger-ui miss it?

**Comment by hkosova** [comment]
`basePath` must have a leading `/`:
```
"basePath": "/dbox/cmng"
```

**Comment by webron** [comment]
@jeusdi - if you follow @hkosova's suggestion, it'll solve the issue.

**Comment by jeusdi** [comment]
Solved! Thanks.
