### ISSUE TITLE
`Try it out` with request without parameters raises TypeError

### ISSUE THREAD

**Issue by jchapuis** [swagger-api/swagger-ui#3587]
### Demonstration API definition
```yaml
swagger: '  2.0'
schemes:
  - http
  - https
consumes:
  - 'application/json'
produces:
  - 'application/json'
paths:
  /v1/health:
    get:
      tags:
        - Health
      summary:
        'Health'
      produces:
        'application/json'
      responses:
        200:
          description: 'Normal response'
          schema:
            $ref: "#/definitions/Status"
      parameters:
definitions:
  Status:
    type: object
    properties: 
      ok:
        type: boolean
      error:
        type: string
```

### Expected Behavior
Trying out request with no parameter with the `Try it out` button should work

### Current Behavior
Getting an `Uncaught TypeError: Cannot read property 'withMutations' of null    at swagger-ui-bundle.js:23172`

**Comment by webron** [comment]
@jchapuis - in the future, please follow our issue template to help us better provide support.

The spec you provided is invalid. Please use http://editor.swagger.io/ to see the validation errors and fix them. Once fixed, the try it out functionality will work even with no parameters.

**Comment by jchapuis** [comment]
@webron ok, thanks for your reply and sorry about that. I still think however that it would be nicer behavior if swagger-ui could fail with a meaningful error in such cases, but I imagine that's not so easy to do.

**Comment by webron** [comment]
Sure, a more graceful error would be great, but this is out of our current capacity. If anyone wants to tackle it and submit a PR, by all means...
