### ISSUE TITLE
Array.forEach Call Stack Exceeded in dist 3.1.5

### ISSUE THREAD

**Issue by tyrsius** [swagger-api/swagger-ui#3589]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger-UI version?       | 3.1.5 `swagger-ui-dist`
| How did you install Swagger-UI? | Downloaded ZIP release
| Which broswer & version?        | Chrome
| Which operating system?         | Mac OS X

### Demonstration API definition
Trying to instantiate bundle with
```
const ui = window.SwaggerUIBundle({
      url: testUrl,
      domNode: this.swaggerContainer,
      deepLinking: false,
      presets: [
        window.SwaggerUIBundle.presets.apis,
        window.SwaggerUIStandalonePreset
      ],
      plugins: [
        window.SwaggerUIBundle.plugins.DownloadUrl
      ],
      layout: 'StandaloneLayout'
    })
```

produces an error
```
"RangeError: Maximum call stack size exceeded
    at Array.forEach (<anonymous>)
    at http://localhost:3000/swagger-ui/swagger-ui-bundle.js:38:712
    at Array.forEach (<anonymous>)
    at e.exports (http://localhost:3000/swagger-ui/swagger-ui-bundle.js:38:639)
    at http://localhost:3000/swagger-ui/swagger-ui-bundle.js:38:919
    at Array.forEach (<anonymous>)
    at http://localhost:3000/swagger-ui/swagger-ui-bundle.js:38:712
    at Array.forEach (<anonymous>)
    at e.exports (http://localhost:3000/swagger-ui/swagger-ui-bundle.js:38:639)
    at http://localhost:3000/swagger-ui/swagger-ui-bundle.js:38:919"
```

**Comment by webron** [comment]
Can you provide the API definition you're trying to load?

**Comment by tyrsius** [comment]
It happens with every API, including `'http://petstore.swagger.io/v2/swagger.json'`

**Comment by tyrsius** [comment]
Apparently it works with `dom_id`, just not with `domNode`

**Comment by webron** [comment]
I see. @oysteinsigholt, given you added `domNode`, can you take a look at the issue please?

**Comment by oysteinsigholt** [comment]
How do you set `this.swaggerContainer`, and what is the html markup for the swagger container?

**Comment by tyrsius** [comment]
@oysteinsigholt `this.swaggerContainer` is an empty `div` set via a React `ref` callback.

**Comment by oysteinsigholt** [comment]
`domNode` was never tested with react dom nodes, so I'm guessing that when it is passed one the configuration deep merge fails as it attempts to merge in the `reactInternalInstance`.

If that is the case, an easy fix would be excluding `domNode` from the deep merge, as it is added to the merged config separately anyways.

Could you try the fix [from this fork](https://github.com/oysteinsigholt/swagger-ui), and report back? I have built everything, so the dist folder can be swapped in quickly.

**Comment by tyrsius** [comment]
@oysteinsigholt that worked 😄

**Comment by oysteinsigholt** [comment]
Fix proposed in #3593.

**Comment by shockey** [comment]
I just merged @oysteinsigholt's fix.

We'll be releasing a new version of the UI later today - this fix will be included in it.

Thanks for the effort on this, everyone!

**Comment by tyrsius** [comment]
Wow, that's an incredible turn around time. You guys are fantastic

**Comment by webron** [comment]
@oysteinsigholt Thanks for handling this, much appreciated!
