### ISSUE TITLE
Deeplink/permalink encoding problem

### ISSUE THREAD

**Issue by ocdevops** [swagger-api/swagger-ui#3596]
If there is space in the Tag, the generated url does not work. Swagger UI does not scroll down to the Tag and does not open the Tag and service.
For example:
http://mydemo.com/demo/#/Payment address/AddPaymentAddress
_Bug or feature request?_  
Bug
_Which Swagger-UI version?_ 
3.x

**Comment by shockey** [comment]
Likely solution: encode URLs with `encodeURI` before updating the fragment. Would need to look into the links we're adding to Tags and Operations as well - they may be affected.

**Comment by DavidBiesack** [comment]
See #3631 for a sample OpenAPI 2.0 document.
It also includes a `?` character as another test case.
