### ISSUE TITLE
Sending additional headers

### ISSUE THREAD

**Issue by faustbrian** [swagger-api/swagger-ui#3605]
I am currently using Swagger UI 3.1.6 and can't figure out how to set additional headers that will be send on every request.

Is there some way I can set additional headers in the swagger.json or even add inputs to the UI where the developer can set the value of those custom headers directly through Swagger UI configuration?

**Comment by faustbrian** [comment]
Is this repetitive way the only way to handle this?

```
parameters:
  customHeader:
    name: custom
    in: header
    type: string
  customHeader:
    name: custom
    in: header
    type: string
  customHeader:
    name: custom
    in: header
    type: string

paths:
  "/api":
    get:
      tags:
      - ''
      summary: ''
      operationId: ''
      parameters:
      - $ref: '#/parameters/customHeader' # Repeat the $refs on every possible request, very repetitive
      - $ref: '#/parameters/customHeader'
      - $ref: '#/parameters/customHeader'
      - in: query
        type: string
        name: q
        description: ''
        required: true
      responses:
        '200':
          description: ''
          schema: {}
```

**Comment by shockey** [comment]
We do have a request interceptor option[1]... but that's for programmatic modification of outgoing requests, not defining custom data at runtime via the UI.

I'm not quite sure what you're trying to achieve here, though. Having `customHeader` defined more than once is invalid YAML, and using the parameter more than once in one operation is against the Swagger/OpenAPI specification (each parameter in an operation must have a unique `name` + `in` combination).

What are you trying to handle by defining custom headers? If you share some more information, we may be able to point you in the right direction.

[1]: https://github.com/swagger-api/swagger-ui#parameters

**Comment by hkosova** [comment]
@faustbrian, what kind of headers are these?

If they are [API keys](https://swagger.io/docs/specification/2-0/authentication/api-keys/), you can describe them using the `securityDefinitions` and `security` keywords instead. Then they will apply globally.

If they are generic headers like `X-RequestId`, `User-Agent`, etc, you'll need to `$ref` them in all requests, because OpenAPI 2.0/3.0 do not have a concept of global parameters. You can `$ref` them on the path level instead of inside operations to reduce the code duplication:

```yaml
paths:
  /something:
    # Path-level parameters, inherited by all operations with that path
    parameters:
      - $ref: '#/parameters/customHeader1'
      - $ref: '#/parameters/customHeader2'
      - $ref: '#/parameters/customHeader3'
  
    get:
      ...
    post:
      ...
    patch:
      ...
```

There are existing feature requests for global parameter and parameter groups in the OpenAPI Specification repository:
[Group multiple parameter definitions for better maintainability](https://github.com/OAI/OpenAPI-Specification/issues/445)
[Global/common parameters](https://github.com/OAI/OpenAPI-Specification/issues/341)

**Comment by faustbrian** [comment]
Yeah I know about the securityDefinitions and security keywords but they are generic headers that are required by the server to know about a few things which is why I am currently doing the `$ref` part in every single request.

Guess I will keep doing that till OpenAPI has support for global or grouped parameters to clean things up, just seems overly repetitive. Thanks!

**Comment by hkosova** [comment]
@faustbrian, there is a workaround using YAML anchors, as [shown here](https://github.com/OAI/OpenAPI-Specification/issues/613#issuecomment-203673611). Instead of repeating all the `$ref`s you'll need to repeat the anchor name only. This works in Swagger Editor/UI.

```yaml
# &-anchors must be defined BEFORE they are *-referenced!

x-globalParameters: &GLOB_PARAMS
  - $ref: '#/parameters/customHeader1'
  - $ref: '#/parameters/customHeader2'
  - $ref: '#/parameters/customHeader3'

paths:
  /something:
    parameters: *GLOB_PARAMS
      
    get:
      parameters:
        - in: query
          type: string
          name: q
          description: ''
          required: true
      ...
    post:
      ...

  /another_path:
    parameters: *GLOB_PARAMS
    get:
      ...
    post:
      ...
```

**Comment by faustbrian** [comment]
Thanks, I will give it a shot.
