### ISSUE TITLE
Hosting a generic UI behing reverse Proxies

### ISSUE THREAD

**Issue by de-robat** [swagger-api/swagger-ui#3606]
Hello, first of all kudos for the swagger-ui. I really like the tool and use it quite a bit.

Right now i'm wondering, if in a multi API environment i am able to host solely one swagger ui and use it to showcase several API-Endpoints.

The Issue is, i cant provide the host and even not the basePath reliably within the swagge.json . There is no way to know before deploying under which url the API will be reachable (especially not in a multi tenant environment).

Let me give an example for further clarification:

Say i've one API named `myApi`. And i could say, my first deployment is in `mydomain.com/mayApi`. Now i hand it over to Customer A, who chooses to Host the same API behind his own reverse proxy which config is therefore subject to change and out of my control. So he goes for `customerA.com/apis/testApi/myApi`.

Opening the url `customerA.com/apis/testApi/myApi/swagger.json` in the Swagger UI works properly. But all Interaction with routes does use the originally implemented host and basePath params from the swagger.json (`mydomain.com/mayApi`) and therefore will fail or not deliver the data of customerA .

A solution could be to assume that the url to the swagger.json it self marks the baseUrl to the API, and will get used in turn for requests too.

Am i missing any Config param or is this kind of Usage simply not anticipated.

This question seems to be related with the PR in Issue #2343 .

Thanks in advance!

**Comment by shockey** [comment]
Hey @de-robat, thanks for reaching out!

if you omit the host/basePath entirely, Swagger-UI will infer it based on the host and path that the swagger.json was fetched from. 

Beyond that, there's just no way to override what's in the swagger.json. I do think this is a valid use case, it makes sense to be able to override the host or basePath at runtime. A PR that achieves this would be welcome 😉 

It's also worth noting that the latest specification version, OpenAPI 3.0, replaced `host` + `basePath` with `servers`. A server can be defined with variables within it (see docs [HERE](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverObject)), so it would be possible to create a servers entry that allows for a completely custom host to be defined. We don't support request execution with OpenAPI 3.0 yet, but it's expected to land in the coming weeks.

**Comment by de-robat** [comment]
Ty for the quick reply! Ofc first of all: what a happy me, that exactly our usecase already will work out of the box :) For overriding the host and basepath on a runtime basis, we are likley going to wrap the swagger-ui into a management tool anyways and may need exactly that. So when the time comes i'll happily provide a PR. Thanks again!
