### ISSUE TITLE
Api key authorization (in header) not working

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3607]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Latest
| Which Swagger-UI version?       | Latest
| How did you install Swagger-UI? | Swagger-Net
| Which browser & version?        | Chrome
| Which operating system?         | Win7

### Demonstration API definition
http://turoapi.azurewebsites.net/swagger/docs/V1
but same is happening on the PetStore

### Expected Behavior
The request should contain the configured header(s)

### Current Behavior
The request is missing the apiKey header

### Context
On my case I was just testing the Api key authorization and kept getting:
***Authorization has been denied for this request*** 
after some debugging I  noticed that on the backend I was not getting the key in the headers, opened fiddler and bamm the request was missing my key...

**Comment by webron** [comment]
None of the operations is defined to use the `apiKey` header.

**Comment by heldersepu** [comment]
Thanks, I see it working with the http://petstore.swagger.io/#/pet/getPetById
That will present a huge challenge, not sure if it will be possible on C# to determine the authorization using reflection...

**Comment by webron** [comment]
As far as I know, Swashbuckle is capable of producing that information somehow.

**Comment by heldersepu** [comment]
I was just working on that!  it has been left to the final developer to include it:
https://github.com/domaindrivendev/Swashbuckle/blob/e0053e1864defa3c4f73ca2a960eb876e257cc9e/Swashbuckle.Dummy.Core/App_Start/SwaggerConfig.cs#L67
Not a good practice!  I'm be looking to automate that....
