### ISSUE TITLE
May I locate at a specified method with <a> tag?

### ISSUE THREAD

**Issue by jnoob** [swagger-api/swagger-ui#3608]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  feature request
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       |3.1.6
| How did you install Swagger-UI? | dist
| Which broswer & version?        |Google chrome 60.0.3112.101
| Which operating system?         | Win10

May I locate at a specified method with <a> tag? I tried to modify the Operation component to add the id attribute to the <a> tag in the operation, it seems not work.

**Comment by shockey** [comment]
Operation ids on the operation DOM nodes seems like something reasonable enough to add to the project itself.

What are you trying to do with the IDs? If you're trying to link to them, we have an option for that, see here: https://github.com/swagger-api/swagger-ui/blob/master/docs/deep-linking.md

If you tell me more about what you're trying to achieve, I can be of more help 😄

**Comment by jnoob** [comment]
exactly what I need!!! Thank you for your supporting!!!!😄👍👍

**Comment by shockey** [comment]
Awesome! Glad I could help 🎉 

Closing!
