### ISSUE TITLE
Swagger UI Docker Possible Host/Validator Issue

### ISSUE THREAD

**Issue by ajmanlove** [swagger-api/swagger-ui#3609]
I've got the swagger-ui docker image locally on my mac. Alongside in another container is my tomcat jersey application hosting the swagger.json connected on a docker bridge and a link. Once I run the docker-compose I am unable to use swagger ui against my application. All I receive are what appear to be host errors:

Safari:
```
Failed to load resource: A server with the specified hostname could not be found. http://api:8080/workflow/swagger.json
```

Chrome:
```
GET http://api:8080/workflow/swagger.json net::ERR_NAME_NOT_RESOLVED
``` 

I can curl the swagger.json successfully from the swagger ui container at that url. I've gone through a fair number of other Issues testing solutions, I don't believe it is a CORS issue as it doesn't appear to actually be hitting my webapp. I've also overwritten the swagger-ui index.html attempting to disable the validator, to no avail:

```
...
  const ui = SwaggerUIBundle({
    url: "http://api:8080/workflow/swagger.json",
    dom_id: '#swagger-ui',
    validatorUrl: null,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })
...
```
I have tried out different approaches to solve using the latest, v3.0.5, and v2.2.9 docker container versions. 

Jersey swagger meta is generated using:

```
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-jersey2-jaxrs</artifactId>
      <version>1.5.16</version>
    </dependency>

    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-core</artifactId>
      <version>1.5.16</version>
    </dependency>
```

Any advice would be appreciated. Unsure if I've actually hit a bug or if I'm missing something obvious. Please feel free to ask for any additional information I can provide.

**Comment by shockey** [comment]
Hey @ajmanlove!

Since Swagger-UI runs in your browser, the request you see failing is coming from your host machine's point of view, not the Swagger-UI container's. You should be able to get this working by exposing your Jersey application to your host machine, and then pointing the Swagger-UI container to that URL by setting the `API_URL` env to point to the API definition your application is serving up.

I know that isn't optimal for docker-compose usage, but getting an API document from the container's point of view instead of the host would require some nginx reverse proxy plumbing that we don't have today (though I'm pretty sure it's possible).

Nota bene: I don't touch the Docker side of the UI a lot. CCing @ponelat, our resident `docker-compose` ninja, for a second opinion here!

**Comment by ponelat** [comment]
Hi there @ajmanlove 
So there are a couple of ways to achieve what I image it is you want.
The easiest is to host your spec publicly. When a browser can reach it, so can swagger-ui via `API_URL`, no need for docker links either. 

Alternatives include curl'ing the spec into the container, when it runs. This would allow you to avoid having to host your spec publicly. It requires one or two lines of code in the docker-run.sh file of swagger-ui ( PRs welcome! ). 

And something based on what @shockey said. We create a simple nodejs server + template. To inject the swagger.json into the index.html. This would remain fresh for each request, as aposed to the docker-run.sh solution which would require you to restart the docker container, when the spec changes.

**Comment by ajmanlove** [comment]
Thank you for the quick replies guys. This all makes total sense and probably should have been obvious to me ;). Hosting this publicly isn't an option yet as this is just a development environment but I will give these other options a try and post back with the result here. Thanks!

**Comment by ajmanlove** [comment]
Excellent, pointing the API_URL to a location accessible from my host machine solved the issue. Thanks again!
