### ISSUE TITLE
Deep linking causing issues in a SPA.

### ISSUE THREAD

**Issue by invictusmaneo** [swagger-api/swagger-ui#3610]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2
| Which Swagger-UI version?       | 3.1.6

### Sample

https://plnkr.co/edit/8ppSJgcZPIUhEzeAzi8P?p=preview

1. Click on Swagger Route.
2. Click on the text next to the Http method.

### Expected Behaviour
The operation display must be toggled.
### Current Behaviour
App is redirected to the app's base location.

### Possible Solution
If deepLinking: false 
Remove the empty href from anchor tag or just remove the anchor tag.

--------------------

If this is indeed a valid bug. I can create a PR for this simple change.
Amazing project ! Thanks for all the work.

**Comment by shockey** [comment]
Confirmed!

Our intended behavior with `deepLinking: false` is to _never_ interact with the URL fragment if disabled. Removing the href attribute (as opposed to what we do now, which is set an empty href) seems like a sane solution to me.

@invictusmaneo, if you have the time to make a PR for this, it would be appreciated!

**Comment by shockey** [comment]
Also - thanks for the plunker! That made this bug way easier to observe  😄
