### ISSUE TITLE
Array[boolean] wrongly rendered

### ISSUE THREAD

**Issue by vanta** [swagger-api/swagger-ui#3618]
I have a following body param definition:

```
{
  "in": "body",
  "name": "body",
  "required": false,
  "schema": {
    "type": "array",
    "items": {
      "type": "boolean"
    }
  }
}
```

which results in following render on UI:

![image](https://user-images.githubusercontent.com/2153370/29774845-548a95ea-8c03-11e7-89c8-e6550a6171db.png)

As you can see the type is recognised correctly (`Array[boolean]`) but HTML component to enter/choose value is not. It is simple `Boolean` param I believe.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.x
| Which Swagger-UI version?       | 2.x
| How did you install Swagger-UI? | 
| Which browser & version?        | All 
| Which operating system?         | All

### Expected Behavior
UI should reflect Swagger API definition, i.e. allow to enter array of booleans.

### Current Behavior
Only single boolean is allowed to enter.

### Context
```
{
  "in": "body",
  "name": "body",
  "required": false,
  "schema": {
    "type": "array",
    "items": {
      "type": "string"
    }
  }
}
```
When `boolean` is replaced with `string` it is rendered correctly (text area):

![image](https://user-images.githubusercontent.com/2153370/29775274-d7be8bf0-8c04-11e7-849b-62920b555d03.png)

**Comment by webron** [comment]
Thanks. This is an issue in 2.x which we're not actively maintaining. Looking at 3.X, it doesn't seem to be an issue there, so suggest upgrading.
