### ISSUE TITLE
why it tries validates local files?

### ISSUE THREAD

**Issue by rafaelcapucho** [swagger-api/swagger-ui#3620]
I'm running using a local `swagger.yaml` file, like:

```
FROM nginx:alpine

COPY ./dist/* /usr/share/nginx/html/
COPY swagger.yaml /usr/share/nginx/html/swagger.yaml
COPY nginx.conf /etc/nginx/

CMD ["nginx", "-g", "daemon off;"]
```

```
docker build -t swagger-api .
docker run --rm --net=my_net --name some-nginx -p 8082:80 swagger-api
```

Considering that it is local, why `swagger-ui` sends it to external validation, of course it will fail:
![a](https://user-images.githubusercontent.com/163367/29781021-2aaaf8ce-8bee-11e7-95c8-68db228acc73.png)

![b](https://user-images.githubusercontent.com/163367/29781020-2a770014-8bee-11e7-964e-92d7f7786829.png)

How can I remove/disable this warning? thx.

**Comment by shockey** [comment]
Hey @rafaelcapucho, we don't do anything fancy with identifying local vs Internet-accessible URLs (which is non-trivial when talking about relative URLs), we just pass what's set as the spec URL to the validator.

You can disable the badge by setting `validatorUrl` to `null`. The README has more documentation on this option: https://github.com/swagger-api/swagger-ui#parameters

**Comment by rafaelcapucho** [comment]
@shockey hey, it works! thanks.  I'm closing.
