### ISSUE TITLE
Swagger validation issues

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [swagger-api/swagger-ui#3621]
I am new to swagger, the API we have created seemed to work just fine when deploying locally, but now it is on Azure we are getting validation errors.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  bug
| Which Swagger/OpenAPI version?      | Latest Swagger version that comes with the Swashbuckle Nuget package
| Which broswer & version?            |  IE 11 and Chrome Version 60.0.3112.101
| Which operating system?             | Windows 10

### Demonstration API definition
https://genesisapi.azurewebsites.net/swagger/index.html
https://genesisapi.azurewebsites.net/swagger/v1/swagger.json

The errors that we are seeing are here:
{"messages":["attribute paths.'/api/crm/ContactDetails'(put).[PrimaryPhysicalAddress.Suburb].type is missing","attribute paths.'/api/crm/ContactDetails'(post).[PrimaryPhysicalAddress.Suburb].type is missing","attribute paths.'/{tenant}/api/crm/People'(put).[ContactDetails.PrimaryPhysicalAddress.Suburb].type is missing","attribute paths.'/{tenant}/api/crm/People'(post).[ContactDetails.PrimaryPhysicalAddress.Suburb].type is missing"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"oneOf","message":"instance failed to match exactly one schema (matched 0 out of 2)","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/parametersList/items"},"instance":{"pointer":"/paths/~1api~1crm~1ContactDetails/post/parameters/41"}}]}

I am looking at the put method for Contact Details, and the method signature is as follows:
[HttpPut]
public virtual IActionResult PutContactDetail([FromRoute] string tenant, int id, ContactDetailsModel details)
        {

I assume that this is the method that swagger is throwing an error about?
What I am trying to figure out is how its throwing the above error.
PrimaryPhysicalAddress is a property of the ContactDetailsModel 

I understand that there are validation errors, but need some direction in what to read to go about fixing these in our API.

**Comment by heldersepu** [comment]
This is a Swashbuckle issue not Swagger-UI!

Your Api is Huge it will be extremely difficult for anyone to help you troubleshoot it. 
You need to ***create a Minimal, Complete, and Verifiable example***, if you need help read this:
https://stackoverflow.com/help/mcve

**Comment by webron** [comment]
Thanks @heldersepu. This is indeed not a swagger-ui issue. For general issues, please use the google group.
