### ISSUE TITLE
Select spec url from pre-defined list

### ISSUE THREAD

**Issue by antonenk** [swagger-api/swagger-ui#3627]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature Request
| Which Swagger/OpenAPI version?  | Doesn't matter
| Which Swagger-UI version?       | Latest - 3.1.7
| How did you install Swagger-UI? | Download master.zip, unpack dist/ to internal website
| Which browser & version?        | Doesn't matter
| Which operating system?         | Doesn't matter

Currently standalone SwaggerUI allows to define default spec url in index.html:
    const ui = SwaggerUIBundle({url: "serviceA.json", ...

It would be nice to choose spec from the pre-defined list:
    const ui = SwaggerUIBundle({urls: ["serviceA.json","serviceB.json","serviceC.json"], ...

In our project four teams develop dozen services separately,
but we would like to see docs for all services on one page.

We created frameset (top frame with links + main frame with swaggerUI where spec defined in query string), but main frame still contains URL field, so native solution seems more accurate.

**Comment by shockey** [comment]
This is available in the 3.1 series 😄 

See the `urls` parameter in the README: https://github.com/swagger-api/swagger-ui#parameters

Defining `urls` correctly will create a dropdown menu of definitions that can be displayed, instead of the usual URL input.
