### ISSUE TITLE
Tags with spaces result in permalinks with unencoded spaces

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#3631]
if a tag has a space in it, the URL in the browser (after clicking on an operation to expand it in the UI) also contains unescaped spaces. The URI should use a +.

if a tag contains special characters such as ? or & they should be URL encoded

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.1.7
| How did you install Swagger-UI? | deploy dist directory to web server
| Which browser & version?        | Chrome
| Which operating system?         | Windows, Linux

### Demonstration API definition

```yaml
swagger: "2.0"
info:
  title: Swagger tags uri
  description: A tag with a space results in a URI with unencoded spaces
  version: "1"
tags:
- name: Tag with spaces
  description: A tag with a space results in a URI with unencoded spaces
- name: Tag with special characters?
  description: A tag with a space results in a URI with unencoded spaces
paths:
  /resource:
    get:
      tags:
      - Tag with spaces
      summary: Get a resouce
      produces:
      - application/json
      responses:
        200:
          description: a result
    post:
      tags:
      - Tag with special characters?
      summary: Post a resouce
      produces:
      - application/json
      consumes:
      - application/json
      responses:
        200:
          description: a result
```

### Expected Behavior

Click on the GET operation. The URL should be

http://www.example.com/swagger-ui/?url=http://www.example.com/swagger-ui-issues/tags-uri.yaml#/Tag+with+spaces/get_resource

### Current Behavior

http://www.example.com/swagger-ui/?url=http://www.example.com/swagger-ui-issues/tags-uri.yaml#/Tag with spaces/get_resource

### Context

Would like to be able to copy URLs to embed in email or web pages when citing an operation, so others can open the UI to the right operation.

**Comment by hkosova** [comment]
This looks like a duplicate of #3596.

**Comment by DavidBiesack** [comment]
yes, that's a dup. I obviously did not find it with the title "Deeplink problem" :-(
Perhaps change the title of  #3596 to make it clearer and easier to find and prevent dups (I don't see a way to do that)

**Comment by shockey** [comment]
Thanks for the report @DavidBiesack! Appreciate you following the issue template 😄 

I've updated the title of #3596, hopefully it helps.
