### ISSUE TITLE
Show raw model

### ISSUE THREAD

**Issue by ShamanR** [swagger-api/swagger-ui#3634]
Is it possible to show *Model schema*? as it was in old v2 versions?
Current model is rather difficult to read, and it doesn't work with $oneOf|$anyOff

**Comment by shockey** [comment]
`$oneOf` and `$anyOf` should be rendered if you're displaying an OAS 3.0 definition (but they aren't supported in the 2.0 specification).

We could display model schemas in a tab within the models, similar to how we display example values and schemas for request bodies. @webron, thoughts?

**Comment by ShamanR** [comment]
Maybe new tab with model schema?

**Comment by webron** [comment]
Swagger-UI didn't show model schemas even in v2. Schemas are useful to specific users, but I suspect the majority of users will not benefit from it. Adding another tab will add to the clutter.

I suggest that if you have a need for it, that you implement it and add it to your own instance as a plugin.
