### ISSUE TITLE
Altering default URL of API spec Swagger UI points to

### ISSUE THREAD

**Issue by Qqwy** [swagger-api/swagger-ui#3635]
The [documentation mentions](https://swagger.io/docs/swagger-tools/#changing-the-default-api-35) that you should 'change the default URL in the constructor' of Swagger UI to ensure other API specifications are filled in there.
As I'd like to present my APIspecification using Swagger UI on my website as the main source of the API's documentation, I wanted to alter this.

However, I am unable to find the snippet of constructor code anywhere inside the downloaded swagger-ui repository. Attempts to alter `swagger-config.yaml` or `/src/core/index.js` did not work, even when running `npm build` after this. 

Is the documentation outdated, or am I missing something? 

In any case, I think a reference to the proper file to edit the default URL would improve the documentation.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3
| Which Swagger-UI version?       | 3.1.7
| How did you install Swagger-UI? | Cloning the Git repository. (`master` branch)
| Which browser & version?        | Any (Tested Chromium and Firefox)
| Which operating system?         | Linux Mint

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by hkosova** [comment]
The constructor is in `dist/index.html`, it looks like this:
```
<script>
window.onload = function() {
  
  // Build a system
  const ui = SwaggerUIBundle({
    url: "http://petstore.swagger.io/v2/swagger.json",
    ...
```
You can change the `url` here.

The doc you linked to is a bit outdated, use the repository [README](https://github.com/swagger-api/swagger-ui/blob/master/README.md) instead.

**Comment by Qqwy** [comment]
Wonderful! I don't know why, but I had the feeling that the `dist` folder was the location that the whole project compiled to (which is true), which would mean that these kinds of settings would be made outside of it and then compiled to those files (which is not, the `index.html` seems to be one  of the files that is untouched).

Thank you for your very clear answer!

**Comment by PaulB88** [comment]
I changed that to my url but it is giving me a failed to load API definition.

**Comment by hkosova** [comment]
@PaulB88 It's hard to help without knowing more details. Please [open a new issue](https://github.com/swagger-api/swagger-ui/issues/new) and fill in the template. Thanks!
