### ISSUE TITLE
Checking - DefaultValue for RequestBody is not working

### ISSUE THREAD

**Issue by VibhutiVohra** [swagger-api/swagger-ui#3637]
I have an API that takes a String input json as RequestBody. The input Json String is then validated against a Java pojo. If the input string matches the pojo then we proceed with the API call. I want the swagger model to show the json corresponding to the pojo. Tried the defaultValue of ApiParam but it does not work. Please help

 @ApiParam(value="CheckCardEligibilityRequest", defaultValue = "I give json here..." 
    ) String checkCardEligibilityRequestV1Json,
            @RequestHeader(value = "uuid", required = false) String uuid, @RequestHeader(value = "Accept", required = true) String accept,
            @RequestHeader(value = "Content-Type", required = true) String contentType) ....

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by shockey** [comment]
Hey @VibhutiVohra, please fill out the Q&A section and provide an API definition that demonstrates your problem, so we can reproduce the issue. Thanks!

**Comment by VibhutiVohra** [comment]
Q | A
-- | --
Bug or feature request? |  Bug
Which Swagger/OpenAPI version? |  Springfox-swagger2 , version 2.5.0
Which Swagger-UI version? |  2.5.0
How did you install Swagger-UI? |  using it in Java
Which browser & version? |  tried in chrome 60.0.31
Which operating system? Windows


API definition
@RequestMapping(value = "/wallet/walletProvisioning/accounts/eligibility", method = RequestMethod.POST)
    @ApiOperation("The purpose of this message is to check with the issuer whether the supplied RPAN is eligible for requesting a tokenized card. The issuer can also provide assets, and terms and conditions to override the default pre-configured values. Note that no risk checks will be performed as part of this call.")
    @ApiResponses(value = {
            @ApiResponse(code = 400, message = "### Request was not processed.\n" + "|Type|Code|Details|\n|----------|----------|--------------------|\n|"
                    + "error|invalidRequest|Missing or invalid Parameters", response = ProvisioningErrorResponse.class),
            @ApiResponse(code = 401, message = "### Missing or invalid authorization header.\n" + "|Type|Code|Details|\n|----------|----------|--------------------|\n|"
                    + "error|unAuthorized|Authorization credentials are missing or invalid", response = ProvisioningErrorResponse.class),
            @ApiResponse(code = 403, message = "### Unauthorized to perform the requested operation on resource.\n" + "|Type|Code|Details|More Info|\n|----------|----------|--------------------|\n|"
                    + "error|accessNotConfigured|The request operation is not configured to access this resource|Channel/Country/Business provided in the request is not supported currently|\n|", response = ProvisioningErrorResponse.class),
            @ApiResponse(code = 500, message = "### API Server Error\n" + "|Type|Code|Details|\n|----------|----------|--------------------|\n|"
                    + "fatal|serverUnavailable|The request failed due to an internal error/server unavailability", response = ProvisioningErrorResponse.class) })
    public @ResponseBody ResponseEntity<?> CheckCardEligibility(@RequestBody(required = true) 
    @ApiParam(value="CheckCardEligibilityRequest", defaultValue = "{\"conversationIdentifier\":\"c8ea4eab-ae65-4945-86b4-3d6e20955c17\",\"tokenRequestorIdentifier\":\"777111\",\"walletIdentifier\":\"string\",\"fpanInformation\":{\"accountNumber\":\"<acccountNumber>\",\"accountSource\":\"ON_FILE\",\"cvv\":\"456\",\"expiryDate\":\"1218\",\"tokenReferenceIdentifier\":\"f9f8bedb-479f-4d03-938d-fe5c73e1a0ea\",\"billingAddress\":{\"addressLine1\":\"1620 SONOMA\",\"addressLine2\":\"Street\",\"addressLine3\":\"1620 SONOMA\",\"city\":\"ALBANY\",\"state\":\"CA\",\"countryCode\":\"US\",\"postalCode\":\"75039\"},\"deviceInformation\":{\"deviceLocale\":\"en-US\",\"deviceType\":\"PHONE\",\"languageIndicator\":\"eng\",\"presentationMode\":\"NFC\",\"secureElementIdentifier\":\"f24a21212123123sddsadadsdasdad2131\"},\"customerInformation\":{\"firstName\":\"Jane Doe\",\"lastName\":\"\"}}}"
    ) String checkCardEligibilityRequestV1Json,
            @RequestHeader(value = "uuid", required = false) String uuid, @RequestHeader(value = "Accept", required = true) String accept,
            @RequestHeader(value = "Content-Type", required = true) String contentType,
            @RequestHeader(value = "businessCode", required = false) String businessCode,
            @RequestHeader(value = "channelId", required = false) String channelId,
            @RequestHeader(value = "countryCode", required = false) String countryCode)  throws UnrecognizedPropertyException, IOException, JsonParseException, JsonMappingException, Exception
    {

**Comment by shockey** [comment]
@VibhutiVohra, thanks! unfortunately, Swagger-UI 2.x is no longer under development, so this isn't something we will fix.

there's a ticket open on Springfox's side to update to Swagger-UI's 3.x series: https://github.com/springfox/springfox/issues/1870

i'm going to close this issue, feel free to reply if you have any other concerns!
