### ISSUE TITLE
Deep linking (deepLinking: true) incompatible with Topbar spec chooser (urls)

### ISSUE THREAD

**Issue by zyv** [swagger-api/swagger-ui#3649]
### Current & Expected Behavior

If you enable deepLinking *and* spec chooser at the same time, the links will not work correctly (wrong spec can be loaded if there is more than one), because loaded spec is not controlled by `url` parameter, but rather chooser selection.

### Possible Solution

Maybe add spec array id as the first segment to the deep link if `urls` & `deepLinking` is enabled at the same time?!

**Comment by zyv** [comment]
@webron @supergibbs @shockey @degerstrom @lukastosic

**Comment by zyv** [comment]
@pchorus fyi

**Comment by Xuanwo** [comment]
I met the same problem, the browser always load the first spec in urls.

Maybe we should add spec's name into deeplinking?

**Comment by zyv** [comment]
Just found a workaround, apparently the following does work:

http://swagger-ui/index.html?urls.primaryName=abc#/Foo/getFoo

Kudos to @poctec

**Comment by shockey** [comment]
@zyv, nice workaround 😄 

There _is_ still a problem here - ideally, the selected URL should be dynamically stored in the URL in the same way that the current tag and operation is, so deep linking URLs are reproducible when `urls` is enabled.
