### ISSUE TITLE
OAS 3.0 "try it out" always uses "Accept: application/json" instead of the selected response type

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3654]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.2.0
| How did you install Swagger-UI? | Using the online editor http://editor.swagger.io
| Which browser & version?        | Chrome 60
| Which operating system?         | Windows 7

### Demonstration API definition
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: test
servers:
  - url: http://httpbin.org

paths:
  /get:
    get:
      responses:
        '200':
          description: OK
          content:
            application/xml: {}
            text/plain: {}
```

Steps to reproduce:
* Expand the operation and click "Try it out".
* Under "Responses", select "application/xml" or "text/plain".
* Click "Execute".

### Expected Behavior
Request is sent with `Accept: application/xml` or `Accept: text/plain` - depending on which response type was selected.

### Current Behavior
Request is sent with `Accept: application/json`.

**Comment by webron** [comment]
Hmm, @shockey?

**Comment by shockey** [comment]
Fix should be live..... shortly 😄 

Thanks @hkosova!
