### ISSUE TITLE
Swagger UI 3 and React BSD+Patents License Issues

### ISSUE THREAD

**Issue by MiErnst** [swagger-api/swagger-ui#3656]
Hi together,
we just wanted to upgrade our Swagger version to the latest 3.x version (from 2.x) but we failed because of license issues with the used React framework and its BSD+Patents license. This might not be a problem for all users of Swagger UI but at least the ones working in bigger companies (which might be a huge amount of users of the target user group of Swagger UI). Some links for information:

https://github.com/facebook/react/blob/master/PATENTS
https://code.facebook.com/posts/112130496157735/explaining-react-s-license/

I know that using React is an architecture decision but maybe for the next major version of Swagger UI you can think of using an framework with a more useful licence.  

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature :-)
| Which Swagger/OpenAPI version?  | doesn't matter
| Which Swagger-UI version?       | 3.x

### Expected Behavior
It could be used by companies.

### Current Behavior
Version 3 could not be used.

### Possible Solution
Using another base framework which is compliant to most company concerns.

### Context
Show stopper for usage in companies which have problems with the PATENTS agreement.

**Comment by Havunen** [comment]
If you guys see this as important factor you could use Inferno to replace React. I'm one of core maintainers of Inferno project and I like swagger. I would be more than happy to help :)

Inferno is MIT licensed

https://github.com/infernojs/inferno

**Comment by webron** [comment]
@MiErnst  - thank you for raising this concern. We've actually been aware of it for a few months now, and have been trying to decide on potential next steps. 

While for us, as an open source project, the implication of the license is not very likely to affect us, we understand the potential implication to our users - and without our users there's no point for this project.

At this point, a complete rewrite using a different framework is not on the table - that would require too many resources which we simply don't have.

The main possible solution would be to replace React with an API-compatible library such as Preact, Inferno, maybe React-lite. However, each of those have pros and cons, and we need to understand the migration process and what limitations that would introduce.

Timing-wise, it's unlikely we'll handle it before finishing OAS3 support.

@Havunen - thanks for the offer to help with migrating to Inferno. If we end up deciding on Inferno as the replacement, we might actually take you up on the offer. I just don't want to rush into a decision right now.

**Comment by MiErnst** [comment]
Thanks for the response but unexpected things happend: https://code.facebook.com/posts/300798627056246

So updating to the new release might fix this issue.

**Comment by webron** [comment]
@MiErnst - yup, you beat me to it (in updating the ticket). 

After seeing that, we're most likely to upgrade to React 16. That said, timing can be an issue. If it's a simple upgrade, it wouldn't be a problem, but if it requires additional code changes, it might have to wait until we finish the OAS3 support.

**Comment by shockey** [comment]
Closing - going forward, Swagger-UI will ship with MIT-Liscensed versions of React (via #3805) 😄
