### ISSUE TITLE
Use format information when rendering data types for request parameters

### ISSUE THREAD

**Issue by clasnake** [swagger-api/swagger-ui#3657]
Hi,

Currently, swagger-ui extracts type information when rendering data types for request parameters. But format information is not taken into consideration.
So the UI doesn't differentiate between int32 and int 64 now for example, which should be a useful information.
Any plan to support this like what we have in response models?
<img width="238" alt="screen shot 2017-09-12 at 6 34 59 pm" src="https://user-images.githubusercontent.com/1590497/30321566-1efefc94-97e9-11e7-8dda-640c7f94299a.png">

Thank you

**Comment by webron** [comment]
It's not taken into consideration in what sense?

**Comment by clasnake** [comment]
<img width="243" alt="screen shot 2017-09-12 at 8 32 34 pm" src="https://user-images.githubusercontent.com/1590497/30325999-8e909882-97f9-11e7-8f78-7c26dc69cc28.png">

@webron Can we display something like integer($int64) for the parameters? Am I missing any configurations?

Thanks

**Comment by webron** [comment]
I'm pretty sure there's an open ticket for this, but can't find it now. Will leave it open for now.

**Comment by clasnake** [comment]
Hi @webron , any progress on this issue? Thanks very much.

**Comment by webron** [comment]
Closing as this is resolved now.
