### ISSUE TITLE
Swagger UI not sending formData parameters

### ISSUE THREAD

**Issue by hydeenoble** [swagger-api/swagger-ui#3663]
I am notr able to use Swagger UI for POST operation as the request is empty nothing is posted to my script

Version
"zircote/swagger-php": "~2.0",
"swagger-api/swagger-ui": "^3.0"

/**
     * Create an Industry.
     *
     * @return \Illuminate\Http\JsonResponse
     *
     * @param Request $request
     *
     * @SWG\Post(
     *     path="/industry",
     *     description="Create an Industry",
     *     operationId="Industry",
     *     produces={"application/json"},
     *     tags={"Industry"},
     *     @SWG\Parameter(
     *     name="name",
     *     in="formData",
     *     @SWG\Schema(ref="#/definitions/Industry"),
     *      type="string",
     *     required=true,
     *     description="Name of industry"
     *     ),
     *     @SWG\Response(
     *         response=200,
     *         description="OK"
     *     ),
     *     @SWG\Response(
     *         response=400,
     *         description="Error",
     *     )
     * )
     *
     */

**Comment by webron** [comment]
Please provide the exact version of swagger-ui you're using and the API definition that you load.

**Comment by hydeenoble** [comment]
Versions

swagger-ui = 2.0
Swagger-PHP = 2.0.11

**Comment by webron** [comment]
That's not the swagger-ui version, and that's not the API definition. The issue templates contains the information how to get the swagger-ui version - that's why we created the issue template and that's why you shouldn't have ignored it. As for the API definition, we need what's actually loaded into the UI, not your PHP code.

**Comment by hydeenoble** [comment]
Apologies about that.

version: "3.2.0"

API definition for where the problem is
`/industry: {
post: {
tags: [
"Industry"
],
summary: "Create an Industry.",
description: "Create an Industry",
operationId: "Industry",
produces: [
"application/json"
],
parameters: [
{
name: "name",
in: "formData",
description: "Name of industry",
required: true,
type: "string"
}
],
responses: {
200: {
description: "OK"
},
400: {
description: "Error"
}
}
}
},`

**Comment by webron** [comment]
You need to set the `consumes` for the operation, if you're using `formData`.

**Comment by hydeenoble** [comment]
Thanks a lot. It worked like magic...
