### ISSUE TITLE
Document tryItOutEnabled parameter

### ISSUE THREAD

**Issue by f3l1x** [swagger-api/swagger-ui#3678]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   Feature
| Which Swagger/OpenAPI version?  | dev-master
| Which Swagger-UI version?       | dev-master
| How did you install Swagger-UI? |  Manually
| Which browser & version?        | Chrome
| Which operating system?         |  OSX

Hi. 

We would like to enable `try-it-button`, but there's no info in README.

I have to figure that out, there is an option `tryItOutEnabled` you should place to your config.

Should I prepare PR?

**Comment by jjohs** [comment]
Per https://github.com/swagger-api/swagger-ui/blob/master/docs/version-detection.md, try it out is not enabled by default. 

I am using swagger-ui v3.2.1 and binding to OpenApi spec v3.0, and the try it out button is not displaying.  Are there v3.0 spec requirements/properties that must be set in order for try it out button to render?

**Comment by webron** [comment]
@jjohs there are two separate things. The 'try it out' not being enabled by default - I need to reword that - what I meant there was that the try it out is a two-step process. Clicking the button opens up the form, and only then you can execute the call.

In 3.1, when we introduced OAS3 support, the try it out functionality was just not available to OAS3 at all - it wasn't just 'disabled', it didn't even show the button. In 3.2 that has changed. If you're using 3.2 and you're seeing weird behavior - please file a separate ticket with details to help us investigate.

**Comment by L-Key** [comment]
I'm using the latest version and the "try-it-out" button is enabled by default. How do I disable it?

**Comment by webron** [comment]
@L-Key that option is not available yet. See #3314.

**Comment by curtisdf** [comment]
I see a number of references to a `tryItOutEnabled` option in the source code, but when I add `tryItOutEnabled: false` into my `const ui = SwaggerUIBundle({ ... });` declaration, it seems to have no effect: the Try It Out buttons still appear.

**Comment by shockey** [comment]
@curtisdf, good thought, but `tryItOutEnabled` is an internal prop that is shared between a few of Swagger-UI's components, not a configuration option 😄

**Comment by webron** [comment]
Closing as there's nothing to document at the moment.

**Comment by curtisdf** [comment]
Thanks for the clarification, @shockey. I understand.
