### ISSUE TITLE
Even more eye-candy for Swagger UI

### ISSUE THREAD

**Issue by lbovet** [swagger-api/swagger-ui#368]
Hi,
This is not an issue but a kind of post to 
1) Congratulate and thank the wordnik team to bring Swagger to all of us.
2) Present two projects that integrate with Swagger:  [Docson](https://github.com/lbovet/docson) and [Typson](https://github.com/lbovet/typson)

You can see the result here http://lbovet.github.io/swagger-ui/dist/index.html
Cheers,
Laurent

**Comment by webron** [comment]
@lbovet - thanks for the note. Feel free to submit a PR to [swagger-spec](https://github.com/swagger-api/swagger-spec) to add it to the list.
