### ISSUE TITLE
UI Stucks while listing/fetching

### ISSUE THREAD

**Issue by SaadHussain** [swagger-api/swagger-ui#3680]
[datajson.zip](https://github.com/swagger-api/swagger-ui/files/1313310/datajson.zip)
Bug
Swashbuckle Version 5.6.0 
Browser IE, Chrome and Firefox
OS Windows 8.1

Json returns fine from my local host
http://localhost:37991/swagger/docs/v1

but browser hangs up while fetching api list

attached here is the json file

**Comment by webron** [comment]
Closing as duplicate of #1919.
