### ISSUE TITLE
OAS 3.0: "Try it out" and relative servers

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3681]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.2.1
| How did you install Swagger-UI? | petstore.swagger.io
| Which browser & version?        | Chrome 61
| Which operating system?         | Windows 7

If `servers` specify a relative URL, such as `/` or `/v2`, "try it out" requests and the cURL command are missing the host name.

Note: Relative `servers` are relative to the host from which the OpenAPI spec is served, not the UI host.

![Relative server](https://user-images.githubusercontent.com/8576823/30584785-806fd42c-9d33-11e7-8a23-626bb92ed273.png)

### Demonstration API definition
https://gist.githubusercontent.com/hkosova/d223eb45c5198db09d08f2603cc0e10a/raw/ae22e290b4f21e19bbfc02b97498289792579fec/relative-server.yaml

Or create a Gist with this contents:

```yaml
openapi: 3.0.0
info:
  version: '1.0'
  title: Relative server test

servers:
  - url: /

paths:
  /octocat:
    head:
      responses:
        '200':
          description: OK
```

### Expected Behavior
* "Try it out" sends the request to `https://gist.githubusercontent.com/octocat`.
* cURL command is:
```
curl -X HEAD "https://gist.githubusercontent.com/octocat" ...
```

### Current Behavior
* "Try it out" sends the request to `http://octocat/`.
* cURL command is:
```
curl -X HEAD "//octocat" ...
```

**Comment by shockey** [comment]
This should be fixed.

Thanks for filing, @hkosova!
