### ISSUE TITLE
dist's Execute produces curl -d command with double quotes around JSON data with unnecessary escapes

### ISSUE THREAD

**Issue by nathant727** [swagger-api/swagger-ui#3684]
Running the https://github.com/swagger-api/swagger-ui/tree/master/dist code against my OpenAPI 3.0 API definition generates Curl commands like the following which can not be executed on a command line:

`curl -d " < JSON-with-unnecessary-escapes > "`

Ideally I would like to see the Curl command produced like this:

`curl -d ' < JSON > '`

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  bug
| Which Swagger/OpenAPI version?  | OpenAPI 3.0
| Which Swagger-UI version?       | latest (3.2.1) downloaded today
| How did you install Swagger-UI? | Copied files from https://github.com/swagger-api/swagger-ui/tree/master/dist and then served to public URL as dropwizard static assets as noted here:  http://www.dropwizard.io/0.9.1/docs/manual/core.html#serving-assets
| Which browser & version?        | Chrome Version 60.0.3112.113 (Official Build) (64-bit)
| Which operating system?         | Mac OS X Yosemite Version 10.10.3

Below is my OpenAPI 3.0 definition where I am seeing this problem.

### Demonstration API definition
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "BMC Software TrueSight Intelligence APIs",
    "description": "APIs to create events, measurements and metrics.",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "https://api.premium.local/v1"
    }
  ],
  "tags": [
    {
      "name": "events",
      "description": "Events",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://documentation.truesight.bmc.com/events"
      }
    }
  ],
  "paths": {
    "/events": {
      "post": {
        "tags": [
          "events"
        ],
        "summary": "Creates a new event.",
        "description": "Every event occurrence is persisted to the database as a RawEvent",
        "requestBody": {
          "description": "Details of the event to create",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/eventBody"
              }
            }
          }
        },
        "responses": {
          "202": {
            "description": "Accepted"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "eventBody": {
        "example": {
          "title": "Simplest event only needs: title, source.ref, source.type and finger print fields.",
          "source": {
            "ref": "linux-T3",
            "type": "conversation"
          },
          "fingerprintFields": "[]"
        },
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "_**Required**_ description of the event."
          },
          "source": {
            "$ref": "#/components/schemas/eventSource"
          },
          "fingerprintFields": {
            "type": "array",
            "description": "The fingerprint is used to uniquely group one or more raw events to a higher order event. The fields used to calculate the fingerprint value are specificed in the fingerprintFields field.",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "eventSource": {
        "type": "object",
        "properties": {
          "ref": {
            "type": "string",
            "description": "The _**required**_ reference / identifier for the event source (e.g. ip address, name, database id, meter observation domain id)."
          },
          "type": {
            "type": "string",
            "description": "The _**required**_ type of event source (e.g. 'host', 'conversation', 'organization')."
          },
          "name": {
            "type": "string",
            "description": "An _**optional**_ descriptive name for the event source."
          },
          "properties": {
            "type": "object",
            "description": "An optional map of [String, Object]"
          }
        }
      }
    }
  }
}
```

### Expected Behavior
Ideally I would like to see a curl command produced with single quotes around the HTTP POST data like this:
`curl -d '{"title":"Simplest event...","source":{"ref":"linux-T3","type":"conversation"},"fingerprintFields":"[]"}'`

### Current Behavior
Instead of getting single quotes around the JSON DATA (HTTP POST data) object I am getting double quotes and escaped quotes are being **_unnecessarily_** inserted into my JSON data like this (also seen in attached Curl.png file):
`curl  -d "{\"title\":\"Simplest event...\",\"source\":{\"ref\":\"linux-T3\",\"type\":\"conversation\"},\"fingerprintFields\":\"[]\"}"`

### Possible Solution
Suggested fix is shown above in the expected behavior.

### Context
We are trying to generate test curl commands that prove our API definition is correct however we can not run the commands generated by the swagger-ui dist code because the double quotes around the HTTP POST data and unwanted escaped quotes inserted into our JSON object.
The attached images shown how our example JSON is modified with unwanted escaped quotes and also surrounded by double quote marks (").
![example_json](https://user-images.githubusercontent.com/20169755/30601039-8ab34de0-9d26-11e7-8969-a1bb81f10454.png)

![curl](https://user-images.githubusercontent.com/20169755/30600910-40898306-9d26-11e7-8919-0fe1dbc27185.png)

**Comment by nathant727** [comment]
Oops.  I see what I'm doing wrong.

**Comment by shockey** [comment]
Glad you solved this, @nathant727. Would you mind sharing what you fixed in case someone stumbles upon this in the future? 😄

**Comment by nathant727** [comment]
I changed my API specification from `"fingerprintFields": "[]"` to `"fingerprintFields": []`
