### ISSUE TITLE
array of anyOf inherited schemas not rendering

### ISSUE THREAD

**Issue by epetitje** [swagger-api/swagger-ui#3689]
Using the online swagger editor, I tried to produce a simple test API using inheritance.
when trying to render the following model, the online editor fails:

```
openapi: '3.0.0'
info:
  version: '1.0.0'
  title: Test
  description: Test API
servers:
  - url: https://mytest.com
paths:
  '/test':
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionsList'
      responses:
        '200':
          description: test
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Action:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    Action1:
      allOf:
        - $ref: '#/components/schemas/Action'
        - type: object
          properties:
            name:
              type: string
              default: "action1"
    Action2:
      allOf:
        - $ref: '#/components/schemas/Action'
        - type: object
          properties:
            name:
              type: string
              default: "action2"
    ActionsList:
      type: array
      anyOf:
        - $ref: '#/components/schemas/Action1'
        - $ref: '#/components/schemas/Action2'

```

the 'ActionsList' cannot be rendered. looking at the console in Safari, I get this stack trace:

TypeError: undefined is not an object (evaluating 'n.get')
value — swagger-editor-bundle.js:3666
render — swagger-editor-bundle.js:6409
_renderValidatedComponentWithoutOwnerOrContext — swagger-editor-bundle.js:40435
_renderValidatedComponent — swagger-editor-bundle.js:40442:85
_updateRenderedComponent — swagger-editor-bundle.js:40414
_performComponentUpdate — swagger-editor-bundle.js:40409:242
updateComponent — swagger-editor-bundle.js:40387:286
receiveComponent — swagger-editor-bundle.js:40371
receiveComponent — swagger-editor-bundle.js:37795
updateChildren — swagger-editor-bundle.js:40182
_reconcilerUpdateChildren — swagger-editor-bundle.js:40041
_updateChildren — swagger-editor-bundle.js:40080
updateChildren — swagger-editor-bundle.js:40074
_updateDOMChildren — swagger-editor-bundle.js:39093:255
updateComponent — swagger-editor-bundle.js:39037:97
receiveComponent — swagger-editor-bundle.js:39019
receiveComponent — swagger-editor-bundle.js:37795
updateChildren — swagger-editor-bundle.js:40182
_reconcilerUpdateChildren — swagger-editor-bundle.js:40041
_updateChildren — swagger-editor-bundle.js:40080
updateChildren — swagger-editor-bundle.js:40074
_updateDOMChildren — swagger-editor-bundle.js:39093:255
updateComponent — swagger-editor-bundle.js:39037:97
receiveComponent — swagger-editor-bundle.js:39019
receiveComponent — swagger-editor-bundle.js:37795
_updateRenderedComponent — swagger-editor-bundle.js:40417
_performComponentUpdate — swagger-editor-bundle.js:40409:242
updateComponent — swagger-editor-bundle.js:40387:286
receiveComponent — swagger-editor-bundle.js:40371
receiveComponent — swagger-editor-bundle.js:37795
updateChildren — swagger-editor-bundle.js:40182

Is anyOf well supported in OpenAPI 3 or are there still problems ?
thank you for your answer,

Etienne

**Comment by hkosova** [comment]
Change
```yaml
    ActionsList:
      type: array
      anyOf:
        - $ref: '#/components/schemas/Action1'
        - $ref: '#/components/schemas/Action2'
```
to
```yaml
    ActionsList:
      type: array
      items:
        anyOf:
          - $ref: '#/components/schemas/Action1'
          - $ref: '#/components/schemas/Action2'
```

**Comment by epetitje** [comment]
thanx a lot
