### ISSUE TITLE
"SwaggerUIBundle is not defined" in tomcat9

### ISSUE THREAD

**Issue by wangp8895** [swagger-api/swagger-ui#3693]
I tried with the lastest master branch(v3.2.1) dist/ and i am getting the error for the swagger ui:

swagger-ui-bundle.js:68267 Uncaught SyntaxError: Invalid regular expression: /[A-Z\xc0-\xd6\xd8-\xde]?[a-z\xdf-\xf6\xf8-\xff]+(?:['鈥橾(?:d|ll|m|re|s|t|ve))?(?=[\xac\xb1\xd7\xf7\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\xbf\u2000-\u206f \t\x0b\f\xa0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000]|[A-Z\xc0-\xd6\xd8-\xde]|$)|(?:[A-Z\xc0-\xd6\xd8-\xde]|[^\ud800-\udfff\xac\xb1\xd7\xf7\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\xbf\u2000-\u206f \t\x0b\f\xa0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\d+\u2700-\u27bfa-z\xdf-\xf6\xf8-\xffA-Z\xc0-\xd6\xd8-\xde])+(?:['鈥橾(?:D|LL|M|RE|S|T|VE))?(?=[\xac\xb1\xd7\xf7\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\xbf\u2000-\u206f \t\x0b\f\xa0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000]|[A-Z\xc0-\xd6\xd8-\xde](?:[a-z\xdf-\xf6\xf8-\xff]|[^\ud800-\udfff\xac\xb1\xd7\xf7\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\xbf\u2000-\u206f \t\x0b\f\xa0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\d+\u2700-\u27bfa-z\xdf-\xf6\xf8-\xffA-Z\xc0-\xd6\xd8-\xde])|$)|[A-Z\xc0-\xd6\xd8-\xde]?(?:[a-z\xdf-\xf6\xf8-\xff]|[^\ud800-\udfff\xac\xb1\xd7\xf7\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\xbf\u2000-\u206f \t\x0b\f\xa0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\d+\u2700-\u27bfa-z\xdf-\xf6\xf8-\xffA-Z\xc0-\xd6\xd8-\xde])+(?:['鈥橾(?:d|ll|m|re|s|t|ve))?|[A-Z\xc0-\xd6\xd8-\xde]+(?:['鈥橾(?:D|LL|M|RE|S|T|VE))?|\d*(?:(?:1ST|2ND|3RD|(?![123])\dTH)\b)|\d*(?:(?:1st|2nd|3rd|(?![123])\dth)\b)|\d+|(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff])[\ufe0e\ufe0f]?(?:[\u0300-\u036f\ufe20-\ufe2f\u20d0-\u20ff]|\ud83c[\udffb-\udfff])?(?:\u200d(?:[^\ud800-\udfff]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff])[\ufe0e\ufe0f]?(?:[\u0300-\u036f\ufe20-\ufe2f\u20d0-\u20ff]|\ud83c[\udffb-\udfff])?)*/: Unmatched ')'
    at RegExp (<anonymous>)
    at Object.<anonymous> (swagger-ui-bundle.js:68267)
    at t (swagger-ui-bundle.js:1)
    at Object.<anonymous> (swagger-ui-bundle.js:68267)
    at t (swagger-ui-bundle.js:1)
    at Object.<anonymous> (swagger-ui-bundle.js:23410)
    at t (swagger-ui-bundle.js:1)
    at Object.<anonymous> (swagger-ui-bundle.js:68267)
    at t (swagger-ui-bundle.js:1)
    at Object.<anonymous> (swagger-ui-bundle.js:1)
(anonymous) @ swagger-ui-bundle.js:68267
t @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:68267
t @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:23410
t @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:68267
t @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:1
i @ swagger-ui-bundle.js:1
t @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:44901
t @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:23410
t @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:105789
t @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:1
(anonymous) @ swagger-ui-bundle.js:1
index.html:76 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (index.html:76)

thanks

**Comment by shockey** [comment]
Hi @wangp8895, please file a new issue that follows the issue template that is provided 😄 

We'd be happy to help, but we need the information we ask for in the template in order to diagnose the issue you're having.

Thanks!
