### ISSUE TITLE
File not downloadable when not application/octet-stream

### ISSUE THREAD

**Issue by ELE3E** [swagger-api/swagger-ui#3694]
I think I found a minor bug in the response-body.jsx file. In the download section, each of the lines of the else if statement needs brackets around it. The AND/OR are interpreted incorrectly which prevents a download link to be generated when for example a text/csv or anything else than application/octet-stream is passed.
I tried to clone the repo, generate a bug branch but I can't seem to push.
lines 51-55 were:

`      /^application\/octet-stream/i.test(contentType) ||
      headers["Content-Disposition"] && (/attachment/i).test(headers["Content-Disposition"]) ||
      headers["content-disposition"] && (/attachment/i).test(headers["content-disposition"]) ||
      headers["Content-Description"] && (/File Transfer/i).test(headers["Content-Description"]) ||
      headers["content-description"] && (/File Transfer/i).test(headers["content-description"])) {`

should be:

`      /^application\/octet-stream/i.test(contentType) ||
      (headers["Content-Disposition"] && (/attachment/i).test(headers["Content-Disposition"])) ||
      (headers["content-disposition"] && (/attachment/i).test(headers["content-disposition"])) ||
      (headers["Content-Description"] && (/File Transfer/i).test(headers["Content-Description"])) ||
      (headers["content-description"] && (/File Transfer/i).test(headers["content-description"]))) {`

If I would like to contribute, should I fork instead of cloning? I get a 403 error when pushing... Sorry, I never felt smart enough to contribute to anything useful :D

**Comment by heldersepu** [comment]
Yes you should fork instead of cloning! then you can submit a Pull Request

**Comment by webron** [comment]
@ELE3E - sure, we're happy to accept PRs. If this is your first time, you can refer to GitHub's documentation. I've also found https://gist.github.com/Chaser324/ce0505fbed06b947d962 which might be helpful.

**Comment by ELE3E** [comment]
I have made a PR
