### ISSUE TITLE
OAuth configuration with support to multiples flows

### ISSUE THREAD

**Issue by jvitor83** [swagger-api/swagger-ui#3696]
It is a feature request!

In a OAuth scenario where:
- the Producer (API creator) only create and configure the API (OAuth scope)
- the Consumer (API client) should create some Application to use the API

**I should say that Swagger-UI must allow any consumer/client to choose/configure what OAUTH FLOW it will use to get the `access_token`.**
What actually happend is that we configure the flow and this only restricts the generation of a token by clients who are using the same flow.

My point is:
- The Producer (API creator) only set the scopes and endpoints from the Identity Provider
- The Consumer choose the Flow and the parameters of those (username, password, client_id, client_secret)

**Comment by hendyp** [comment]
Hi! 
To my knowledge the Identity Provider defines which flows it supports, so it's not up to the consumer to choose freely. 
In addition, the [OpenAPI specification requires to set one flow for a security scheme](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-scheme-object), at least for version 2, so it's not for Swagger-UI to provide all options when the API spec only allows one.
It is, however, possible to provide multiple security scheme objects such as "oauth2 with implicit flow", "oauth2 with application flow" and so on, which allows the user to choose in the "Authorize" dialog, when he scrolls down there. That's how we are specifying and using this.

**Comment by jvitor83** [comment]
> it's not for Swagger-UI to provide all options when the API spec only allows one.
You are right.

> Identity Provider defines which flows it supports
Yes, but at my point is "Identity Provider restricts the flows it allows".

My point is:
If i create some API and 2 clients want to test it, but each one a different flows, then, it will not be supported.

_But maybe you are right and this issue is not from Swagger-UI_

**Comment by jvitor83** [comment]
Anyway, according to this link https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oauthFlowsObject the 3.0 version of OpenApi should allow this.
