### ISSUE TITLE
oauth2 vs auth0: missing audience parameter

### ISSUE THREAD

**Issue by mizerlou** [swagger-api/swagger-ui#3697]
i'm using swagger-ui 3.2.0, implicit oauth2, and auth0.  i'm making use of JWTs.  i need to be able to add an audience parameter to the authorization url to convince auth0 to pass back JWTs instead of opaque tokens.  i tried the "straight forward" way of specifying an audience and it doesn't appear to work.

```json
{
  "swagger": "2.0",
  "info": {
    "title": "foo",
    "description": "foo",
    "version": "1.0.0"
  },
  "consumes": "application/json",
  "produces": "application/json",
  "security": {
    "OAuth2": [
      "read",
      "write"
    ]
  },
  "securityDefinitions": {
    "OAuth2": {
      "type": "oauth2",
      "authorizationUrl": "https://test.auth0.com/authorize?audience=https://foo/bar",
      "flow": "implicit",
      "scopes": {
        "read": "for reading",
        "write": "for writing"
      }
    }
  }
}
```

this ends up redirecting me to:

```
https://test.auth0.com/authorize?audience=https://foo/bar?response_type=token&client_id=...&redirect_uri=...&state=...
```

notice the two question marks.  when redirected to this page, it fails.

if i modify the url, by hand, and change the second ? to an &, like:
```
https://test.auth0.com/authorize?audience=https://foo/bar&response_type=token&client_id=...&redirect_uri=...&state=...
```
and then re-submit, everything works like it should.  i end up with a jwt bearer token and everything.

so, my question is:  how *should* i be specifying this audience parameter to the authorizationUrl?

thanks.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.2.0
| How did you install Swagger-UI? | webjars
| Which browser & version?        | chrome
| Which operating system?         | macos

**Comment by shockey** [comment]
So... this is our fault - when we assemble the entire URL for authorization, we're assuming the URL has no query content: https://github.com/swagger-api/swagger-ui/blob/6b59707af1e4b215b67fc157bed2ab16f8b096b4/src/core/oauth2-authorize.js#L67

To be specific: we're always joining the query string we build up and the `authorizationUrl` with a `?`. A better solution would be to parse the `authorizationUrl`, inject our query values into the object, then reserialize the URL.

**Comment by shockey** [comment]
CC @webron for a priority label 😄

**Comment by shockey** [comment]
### Update

It occurs to me that we have a PR open for this:  https://github.com/swagger-api/swagger-ui/pull/3666

I just approved it, so it should be included in tonight's release. So this will be fixed 😄

**Comment by arthuston** [comment]
@shockey was this ever fixed? I'm still getting this error with Auth0. Here is my security definition:
securityDefinitions:
  ui:
    type: oauth2
    flow: implicit
    authorizationUrl: https://mydomain.auth0.com/authorize?audience=audience
    x-tokenInfoFunc: my-x-token-info-func

From the Swagger Test UI I click the Authorize button and it generates the following URL:
https://mydomain.auth0.com/authorize?audience=audience?response_type=token&redirect_uri=https%3A%2F%2myhost%2Fapi%2Fv1%2Fui%2Fo2c.html&realm=your-realms&client_id=your-client-id&scope=&state=ui

Note the two question marks, one before audience and the second before response_type

I get other errors as well. When I add client_id=my_client_id, I get the error message that client_id must be a string. It is a string.

Please let us know if this bug is actually fixed, and good pointers to how to get this working.

**Comment by shockey** [comment]
@arthuston, yeah, something's definitely wrong there - please make sure you're on the latest version, and if so, open a ticket and tag me in it!

if you have the time, setting up a test environment (definition and Auth0 provisioning) that lets us work on this without scaffolding anything out would help to expedite the process 😄
