### ISSUE TITLE
Allow pressing ENTER key to submit parameters

### ISSUE THREAD

**Issue by ogg** [swagger-api/swagger-ui#37]
When entering a value for a parameter, and hitting ENTER, the whole page is submitted. It would be great if swagger-ui could catch the ENTER key pressed event, and submit the parameters for the relevant operation.

**Comment by vegerot** [comment]
2020 and still can't do this?

**Comment by webron** [comment]
@vegerot I know... we've been waiting for a PR from you for so long. Honestly, I'm a bit disappointed.

**Comment by vegerot** [comment]
My bad.  I'll get right on it

**Comment by gtlsgamr** [comment]
Did you get on it? :)

**Comment by vegerot** [comment]
I've been working on the patch ever since I sent that message.  It's a lot more difficult than I thought it'd be.
