### ISSUE TITLE
Can not use components/securitySchemes in swagger-ui

### ISSUE THREAD

**Issue by lvonk** [swagger-api/swagger-ui#3705]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Open API 3.0.0
| Which Swagger-UI version?       |`version: "3.2.2", gitRevision: "g45e7a541", gitDirty: true, buildTimestamp: "Sat, 23 Sep 2017 20:06:42 GMT", machine: "Kyles-MacBook-Air.local"`
| How did you install Swagger-UI? | `git pull && open dist/index.html`
| Which browser & version?        | `Chrome Version 61.0.3163.91 (Official Build) (64-bit)`
| Which operating system?         | `Mac 10.12.6`

Defining security as follows works:

```yaml
securityDefinitions:
  apikey_auth:
    type: apiKey
    in: header
    name: api_key
```

However this does not seem OpenAPI 3.0.0 compliant (or I can't find the definition of `securityDefinitions` anywhere in https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md).

Defining security according to the docs in [OpenAPI 3.0.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#componentsObject) using `securitySchemes` and clicking the lock icon in the operation does not work and result in the following error in de ui:

```yaml
components:
  securitySchemes:
    apikey_auth:
      type: apiKey
      in: header
      name: api_key
```

<img width="1268" alt="screen shot 2017-09-25 at 19 32 52" src="https://user-images.githubusercontent.com/104943/30822298-89c3f996-a228-11e7-9e5f-d2e850a8b666.png">

Complete `openapi.yaml`:
```yaml
openapi: 3.0.0
info:
  title: Jortt API
  description: Api description jortt
  version: 2.0.0

servers:
  - url: http://localhost:9292/api/v2
    description: Development server

security:
  - apikey_auth: []

paths:
  /customers:
    get:
      summary: Customers
      description: The customers endpoint returns all customers known in Jortt
      operationId: getCustomers
      parameters:
        - name: query
          in: query
          description: A search string for customers
          required: false
          schema:
            type: string
      responses:
        '200':
          description: An array of customers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerList"

components:
  securitySchemes:
    apikey_auth:
      type: apiKey
      in: header
      name: api_key
  schemas:
    Paging:
      properties:
        total_items:
          type: integer
        total_pages:
          type: integer
        page_size:
          type: integer
        current_page:
          type: integer
    Customer:
      properties:
        customer_id:
          type: string
          description: Unique id
        name:
          type: string
          description: Name of the customer
    CustomerList:
      allOf:
        - properties:
            customers:
              description: Contains list of customers
              type: array
              items:
                $ref: "#/components/schemas/Customer"
        - $ref: "#/components/schemas/Paging"
```

**Comment by webron** [comment]
@shockey is this related to the try it out functionality or something else?

**Comment by shockey** [comment]
Looks like this is coming from the authorization feature itself, here's where the error is throwing from: https://github.com/swagger-api/swagger-ui/blob/e80b2f5b3faa227a52499ab6175697049e111e84/src/core/plugins/auth/selectors.js#L37

Adding `securityDefinitions` to a 3.0 document works, because the authorization feature is not OpenAPI-aware at the moment. It looks for the same structures, regardless of the `swagger` or `openapi` value in the document.

Obviously, the real fix is to implement OpenAPI authorization support, but in the meantime, disabling authorization features when an OpenAPI document is present will prevent this sort of issue.

**Comment by hkosova** [comment]
Support for OAS 3.0 `securitySchemes` is covered by #3641 and #3665.

**Comment by shockey** [comment]
Closing this, as the ambiguous Swagger2-in-OAS3 behavior has been solved and the OAS3 securitySchemes functionality is covered in other tickets 😄
