### ISSUE TITLE
IE11 freezes when receiving a simple string response body as "application/json" media type.

### ISSUE THREAD

**Issue by arnaudjolly** [swagger-api/swagger-ui#3710]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 
| Which Swagger-UI version?       |  v2.1.4
| How did you install Swagger-UI? | java project maven dependency from io.swagger:1.5.16
| Which browser & version?        | Internet Explorer 11
| Which operating system?         | Windows 8.1 Pro

### Demonstration API definition

```yaml
basePath: /remote-control
definitions: {}
info:
  description: an application
  title: Remote Control API
  version: '1.0.0'
paths:
  /mode:
    get:
      description: ''
      operationId: getMode
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            enum:
              - RUN
              - MAINTENANCE
            type: string
      summary: Get the application's mode
      tags:
        - mode
schemes:
  - http
swagger: '2.0'
tags:
  - name: mode
```

### Configuration (browser query string, constructor, config.yaml)

`http://localhost:8080/remote-control/mode` (no query string needed)

### Expected Behavior

The simple string should be rendered in the "Response Body" block in the UI.

### Current Behavior

Nothing is rendered as an exception occurs in Javascript console for Internet Explorer when the ui handles the response from the server : `Object.keys : l’argument n’est pas un objet Object`

### Possible Solution

I found that IE11 "Object.keys()" throws a TypeError when you give it something else than an object (ES5 specification).
Chrome and Firefox "Object.keys()" is the ES6 version and convert the argument into an Object before.

Maybe using another method inspired of the polyfill given here could help the UI to handle simple string as response body for application/json media type without crashing IE: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/keys
Maybe there is a simpler solution.

### Context

We have time and budget restrictions (like a lot of projects...) to release a first version of our application.
We expose webservices to monitor some part of the application remotely.
In order to bring good stuff with less effort, we've decided to use swagger to expose a quickly working interface.
During development phase, we have other browsers to test the app and it is fine.
But it seems that the people that will monitor the app are stuck with Internet Explorer (not even a PostMan like tool...).
When they ran their tests, this bug pops out so they aren't able to use our "simple and quick" monitor interface made with Swagger.

**Comment by webron** [comment]
Swagger-core doesn't provide swagger-ui as part of its dependencies, so not sure how you actually got it.

You're using an older, unmaintained version of swagger-ui. Can you try the same use case with the current version?

**Comment by shockey** [comment]
I agree with @webron, using Swagger-UI v3 is the best course of action. 

If you're stuck with v2 for some reason, you could always include an `Object.keys` polyfill in your own code.

**Comment by arnaudjolly** [comment]
Thanks for the replies. Asking myself what should I do to use a newer version of swagger-ui helped me dive into the dependencies and the overall architecture of the app.
swagger-ui v2.1.4 comes from a third-party library

I tested it with the swagger-ui v3.2.2 and no bug comes out of the "try out" button.

We'll go for this version.

**Comment by webron** [comment]
That's great news, @arnaudjolly. Thanks for the update!
