### ISSUE TITLE
multiple tags display

### ISSUE THREAD

**Issue by giuliopulina** [swagger-api/swagger-ui#3711]
Hello, I have a problem with rendering of the following spec with swagger-ui (version 3.2.2):

```
swagger: "2.0"
info:
  version: v2
  title: Test
  description: Test
  contact:
    name: test
    url: test
    email: test
host: localhost
basePath: /test/v2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: apiname
    description: test
paths:
  /test/service1:
    post:
      tags:
        - Category1
        - Etag 
        - Cache
      summary: service1
      description: ''
      operationId: service1
      responses:
        '200':
          description: 200
  /test/service2:
    post:
      tags:
        - Category2
        - Etag 
        - Cache
      summary: test2
      description: ''
      operationId: service2
      responses:
        '200':
          description: 200
```
I use tags for different purposes, and swagger-ui duplicates the endpoint for each tag:

![swagger-ui-duplicated-tags](https://user-images.githubusercontent.com/4653848/30929590-3c9a664e-a3bf-11e7-85f8-cad8afcee550.jpg)

Existing options ('filter', 'maxDisplayedTags') don't fit my need.
Would it be possible to add an option to avoid duplicated endpoints? Like adding an option to categorize endpoints considering the first tag only?

Thanks 
Giulio

**Comment by webron** [comment]
I don't see us adding support for such a feature. Tags are intended for grouping of operations, and as such, an operation will appear under every tag assigned to it.

**Comment by giuliopulina** [comment]
Hello @webron, I see your point, but basically this forces to use only one tag per operation (I don't see the use to have an operation displayed under multiple tags). Do you agree?

**Comment by markus-hsk** [comment]
There are use cases for operations with multiple Tags.
Per example I've an API delivering UserData on /users/_id and /auth/myuser. Both requests deliver an object of user data, so both are categorised under Tag Users, but the second one is also tagged with Authorisation, because it handles the userdata of the authorised user. You see the point?

**Comment by webron** [comment]
@giuliopulina looks like you got an example there. It might not be useful to you, but it can be useful to others.

**Comment by giuliopulina** [comment]
@webron the example described by @markus-hsk is very similar to my use case above :) the only difference is about 'visualization': users of my api don't need to see multiple categorization, and I would like to be free to add tags to the spec without impacting swagger-ui.

I could try to create a PR to introduce such an option, maybe in a similar way swagger-codegen solves the problem of multiple tags (option "apis"), but if you think it's useless/wrong I will stop here :P thanks anyway for the answers

**Comment by webron** [comment]
In quite a few years working on this project, this is the first time I recall anyone asking for it. At the moment, I'd rather we don't add that functionality but will be willing to reconsider of there's more traction.

**Comment by giuliopulina** [comment]
Ok @webron thanks again, I'll close the issue then.
