### ISSUE TITLE
The input on try it out is set to read only

### ISSUE THREAD

**Issue by ndphuong** [swagger-api/swagger-ui#3713]
We are using http://petstore.swagger.io to display api document, it work well
However, several day recently, we cannot edit parameter value when on **try it out** form
All input field seem set to read only

Have any big update recently?

**Comment by webron** [comment]
The UI at http://petstore.swagger.io updates regularly with each week's release. If you're having an issue with the deployed version, share your API definition so we can investigate further.

**Comment by ndphuong** [comment]
[api-docs.txt](https://github.com/swagger-api/swagger-ui/files/1347772/api-docs.txt)
Hi @webron 
That is internal api, so I attach json file

Can you check it?

**Comment by shockey** [comment]
Glad you got it working, @ndphuong.

Closing!
