### ISSUE TITLE
Swagger editor does not recover from errors

### ISSUE THREAD

**Issue by susanxhua** [swagger-api/swagger-ui#3729]
If I start to add, for example, a request method to a valid swagger doc, errors show up since the doc is not valid and this is expected. But when the swagger doc is restored to valid, the error does not go away. I have to do a refresh of the page.

**Comment by webron** [comment]
Thanks for the report, however we can't do much with it. I'm going to close the ticket. We'd still like to hear from you, but we added a ticket template for a reason - we require the details there and without them most issues simply can't be resolved.
