### ISSUE TITLE
"Unknown response type" for empty body responses without Content-Type header

### ISSUE THREAD

**Issue by benzulanch** [swagger-api/swagger-ui#3730]
* swagger-ui version: 3.3.1

"Unknown response type" is displayed for responses with no body (such as 204) if the server does not send a Content-Type header, even though Content-Type shouldn't be required for a 204 response.

**Comment by hkosova** [comment]
Sample spec:
```yaml
swagger: '2.0'
info:
  version: '1.0'
  title: httpstat.us

host: httpstat.us
schemes: [http]

paths:
  /204:
    get:
      responses:
        204:
          description: No content
```
