### ISSUE TITLE
Please provide pretty copies in releases

### ISSUE THREAD

**Issue by MTecknology** [swagger-api/swagger-ui#3732]
When this project creates releases, it would be hugely appreciated if it provided non-minified copies of the file, with the minified version having .min.js/.min.css filenames. This would make it much easier for us to review changes between releases, and would make it easier for me to get this package into Debian, as a dependency of Gitea.

Thanks for any consideration of this proposal!

**Comment by shockey** [comment]
Hey @MTecknology!

You can review source changes by visiting our Releases page. Each version includes a changelog  with references to tickets, and a `Version Diff` link which shows you what changes in the source code between each version.

As for minification... I don't quite see why you'd need an unminified build, it's mostly just going to be a much larger file. Is there some Debian policy about this? The only thing I could find was [this page on the Debian wiki](https://wiki.debian.org/Javascript/Policy) which appears to encourage minification:

> should ship a minified version for each script, generated at build time (use uglifyjs to this purpose)

Some clarification of your needs here would be helpful 😄

**Comment by MTecknology** [comment]
Debian policy is that we need to build the compiled result using our build system, to ensure that the work is actually reproducible and not being maliciously modified during an external build. I /should/ be stripping all of dist/* and rebuilding it using npm, but there's a long list of things that need to happen before that can happen (build dependencies missing from the archives). If you let the build system produce non-minified copies, then I can easily verify the changes in the git repo produced the changes in the final work, then I'd be re-minifying those changes within the build system.

**Comment by strk** [comment]
Agreed, there's a difference between "source packages" and "binary packages". I guess @MTecknology is basically asking for "source packages" ?

**Comment by shockey** [comment]
I just ran some numbers - adding unminified copies of our distribution files to the repository would increase the size of our `dist` folder sixfold (from 2MB to 12MB) 😕 

Aside from the painful thought of socking away 12MB of binary-ish files on a weekly basis in the repository (everyone that clones this repo until the end of time will need to download every version as part of the repository history...), this would also trickle down to the `swagger-ui-dist` npm module and the Docker image.

I understand the need, but I just don't think I can justify the extra size burden this change would bring on our users.

---

As for building within your project... I know Debian is pretty heavy on some of their package policies, but consider that Swagger-UI runs in a sandboxed browser context, which limits the effect that malicious code could have, in contrast to, say, a rogue C library.

If you need guidance on setting up a build process, I'd be happy to help. My naive suggestion would be to use Git submodules to track us as a dependency, and create a build script that runs the Swagger-UI build process.

**Comment by MTecknology** [comment]
I can understand the concern for the size. That's a much larger explosion
than I expected. I'd like to argue the the size /should/ be a one-time
addition, buuuut if I were in your shoes, that argument wouldn't mean too
much.

I would appreciate some help with getting the build process working, and
appreciate the offer, but the current hold-up is on webpack, which requires
another tool that has a known security issue and an author that's not very
interested in working a patch. (FTR- I don't blame them.)
... Personally, I'd rather see them strip the offending code and get on
with life, but that's also not likely to happen.

Once webpack makes its way to Debian main, if that's the only build dep
we're missing, I'm hoping the rebuild process is as simple as 'npm run
build' and will 'just werk' when the package becomes available.

FWIW- one of our requirements is that all build tools for a package must
come from d/main; no other network access is allowed.

I don't suppose there's any way to remove webpack from the build and just
rely on uglyifyjs, is there? I'm sure we wouldn't want it for your regular
builds, but maybe an option for me until webpack comes through?

**Comment by shockey** [comment]
> Once webpack makes its way to Debian main, if that's the only build dep
we're missing, I'm hoping the rebuild process is as simple as 'npm run
build' and will 'just werk' when the package becomes available.
> 

> FWIW- one of our requirements is that all build tools for a package must
come from d/main; no other network access is allowed.

Oof - that's a pretty brutal limitation, if I'm reading this correctly. Swagger-UI has 45 production dependencies and 52 development dependencies, all npm modules. All of these dependencies, and _their_ dependencies, are expected to be present in `node_modules` at build time (see https://github.com/swagger-api/swagger-ui/blob/master/package.json#L41-L140). I'd take a guess that looking to d/main for all of those dependencies won't get too far.

> I don't suppose there's any way to remove webpack from the build and just
rely on uglyifyjs, is there? I'm sure we wouldn't want it for your regular
builds, but maybe an option for me until webpack comes through?

Webpack->uglify is definitely not an option. Webpack orchestrates a lot more than minification, like module resolution, syntax transformations (JSX and ES6/7->ES5 transpilation via Babel), source maps, and module formats for build artifacts. 

You may be able to swap it out for something like Rollup or Browserify, but it wouldn't be a trivial task.

---

Your best bet here may be to create a parallel fork of Swagger-UI that is configured to emit unminified artifacts. You could achieve that by changing `minimize` to `false` in the following files:

https://github.com/swagger-api/swagger-ui/blob/master/webpack-dist-bundle.config.js#L22

https://github.com/swagger-api/swagger-ui/blob/master/webpack-dist-standalone.config.js#L22

https://github.com/swagger-api/swagger-ui/blob/master/webpack-dist.config.js#L25

You could even go further, and customize our [`travis.yml`](https://github.com/swagger-api/swagger-ui/blob/master/.travis.yml) configuration to set up a release process that runs builds for you as needed.

**Comment by MTecknology** [comment]
>

**Comment by MTecknology** [comment]
> Agreed, there's a difference between "source packages" and "binary packages".
> I guess @MTecknology is basically asking for "source packages" ?

To be perfectly honest, I was looking for a "loophole" to bypass having to run any actual build (other than minification) and instead rely on your build. For me to rely on your build, I'd need those massive files so I could personally review--between each release--the diff between each release. I call it a loophole because I'm treating the produced source as the authoritive source, and only because it's easily read as source, easily patched, and easily reviewed. It's also possible to forward patches (to this tracker), even if they were against those intermediary files.

>

**Comment by shockey** [comment]
> I'd need those massive files so I could personally review--between each release--the diff between each release. 

Honestly, I think you're underestimating the effort required to review the diff of a multi-megabyte webapp bundle. Massive is the correct term!

Such a file would not only contain our code, but code of every module that those modules depend on, and so forth. All in all, our production dependency tree has 564 modules in it. Since we track semver ranges for most of our dependencies, a handful of these may update between releases, adding to the diff. If you're not able to trust our releases, then our dependencies should be subject to even _more_ scrutiny - which would be difficult, considering that many of our dependencies publish minified versions of their code, which we have no control over.

I think creating your own build process that emits the unminified source for your consumption is the best way forward.

**Comment by MTecknology** [comment]
> our dependencies should be subject to even _more_ scrutiny

In the same way that swagger-ui is just one of many dependencies, yes... every
dependency in the chain needs review.

> I think creating your own build process that emits the unminified source for your consumption is the best way forward.

I know that it's not. Unfortunately, the best way forward is a miserable path.

(but it's irrelevant to this bug)

**Comment by MTecknology** [comment]
Just to follow up... I was sitting on some pretty wishful thinking. It would never have been accepted into Debian the way I described.

I ended up replacing the swagger-ui stuff with a statically generated copy.
If anyone is ever interested -> https://github.com/MTecknology/static_swagger-ui
