### ISSUE TITLE
Markdown headings not rendered

### ISSUE THREAD

**Issue by avaly** [swagger-api/swagger-ui#3734]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug
| Which Swagger/OpenAPI version?  | `3.0.0`
| Which Swagger-UI version?       | `3.3.1`
| How did you install Swagger-UI? | `swagger-ui-dist` & http://editor.swagger.io/
| Which browser & version?        | Google Chrome 61
| Which operating system?         | Ubuntu

### Demonstration API definition

```yaml
openapi: 3.0.0

info:
  title: Demo
  version: 1.0.0
  description: |
    Welcome to API documentation.

    # Heading 1

    ## Heading 2
    
    ### Heading 3

    #### Heading 4

paths:
  /foo:
    get:
      summary: Get your foo information
      responses:
        '200':
          description: Successful response
          content:
            'application/json':
              schema:
                type: string
```

### Configuration (browser query string, constructor, config.yaml)

Default config

### Expected Behavior

Expected to render all headings in proper `h1`, `h2`, `h3` and `h4` tags.

### Current Behavior

Only headings `h3` and `h4` are rendered with tags. The headings 1 and 2 are rendered without any tags at all.

**Comment by owenconti** [comment]
This is a "bug" with the `sanitize-html` module we use: https://github.com/punkave/sanitize-html/issues/122.

PR incoming.
