### ISSUE TITLE
With OAuth password flow, scopes are double uri-encoded

### ISSUE THREAD

**Issue by bobbyajp** [swagger-api/swagger-ui#3749]
I think there might be a problem with double uri-encoding the scopes in the oauth password flow. I logged every encodeURIComponent() call in swagger-ui-bundle.js, and what is see is this:
encodeURIComponent(myservice:myscope)
encodeURIComponent(password)
encodeURIComponent(myservice%3Amyscope)
encodeURIComponent(myusername)
encodeURIComponent(mypassword)
My scope ("myservice:myscope") is uri encoded twice, first as "myservice:myscope", then as "myservice%3Amyscope". If I remove the encodeURIComponent() call from the snippet "scope:encodeURIComponent(e.scopes.join(" "))", then my tokenUrl stops complaining about invalid scopes.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 
| Which Swagger-UI version?       |3.1.7
| How did you install Swagger-UI? | cloned repo, hosted dist/ folder
| Which browser & version?        | Chrome 61.0.3163.100
| Which operating system?         |  OS X 10.12.3

### Demonstration API definition

Here's the security part:

"securityDefinitions": {
"my_auth": {
"type": "oauth2",
"flow": "password",
"tokenUrl": "https://myhost/oauth/token",
"scopes": {
"service:myscope": "scope for this service"
}
}
},
"security": [
{
"my_auth": [
"service:myscope"
]
}
],

### Current Behavior

scope is double uri-encoded

### Possible Solution

I removed the encodeURIComponent() call from the snippet "scope:encodeURIComponent(e.scopes.join(" "))", and my tokenUrl stops complaining about invalid scopes.

**Comment by bobbyajp** [comment]
@shockey Here's the double uri-encoding issue mentioned in issue #3731.

**Comment by Jaza** [comment]
@bobbyajp @shockey I ran into this issue too - my change in #3840 fixes it.

**Comment by bobbyajp** [comment]
That's great. Thanks for fixing it.
