### ISSUE TITLE
OAS 3.0.0 method name case-sensitivity in Swagger-ui 3.3.1

### ISSUE THREAD

**Issue by micksear** [swagger-api/swagger-ui#3752]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature request
| Which Swagger/OpenAPI version?  | OAS 3.0.0
| Which Swagger-UI version?       | 3.3.1
| How did you install Swagger-UI? | Download Zip from Github
| Which browser & version?        | Chrome 61.0.3163.100
| Which operating system?         | Mac Sierra 10.12.6

If I load a JSON spec with HTTP method names in uppercase, I get a cryptic and unhelpful message 'No operations defined in spec!'.  Making the method names lower case magically causes the spec to load OK.  Although the documentation shows method names in lower case, it doesn't specify that they have to be lower case.  Making swagger-ui cope with either case would be a helpful change to make.

**Comment by shockey** [comment]
Hi @micksear! 

Per the OpenAPI 3.0.0 specification, all field names are case-sensitive ([citation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#format)). 

Later in the document, operation method field names in the Path Item Object are defined as `get`, `put`, `post`, etc in lowercase ([citation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#path-item-object)). Therefore I'd expect `GET`, `PUT`, `POST`, etc to be invalid.

If your definition was made by hand, you should change it to be in line with the specification. If you're using a library to generate it, and are therefore unable to easily fix the case of the methods, I can try to point you in the direction of a custom UI plugin that can work around the method case.

**Comment by micksear** [comment]
OK, I guess you can close this then.  Hopefully it'll serve as a pointer for others getting the same error message though.
