### ISSUE TITLE
Inconsistent behavior with Parameter value and SupportedSubmitMethods?

### ISSUE THREAD

**Issue by ganeshmuthuvelu** [swagger-api/swagger-ui#3759]
1) I have set an empty array for the "SupportedSubmitMethods" that I'm disabling the "try it out" button for all methods.
2) When the UI is generated, I see the "Value" as "(empty)" for all methods that take a non nested complex type as parameter. In the attached screenshot, see the "GiveMeSomething" method.
3) However, see the method "ReadJSON". This is bound to a nested complex type parameter but here I'm able to see a "textArea" for the parameter value.

I feel that this behavior is inconsistent.. At the same time, I would prefer that the editors for the parameter values are always shown, even if the "try it out" buttons are disabled..

![image](https://user-images.githubusercontent.com/28572900/31557896-ac27ce56-b018-11e7-927f-7c0b1ecd68ed.png)

Thoughts?

**Comment by shockey** [comment]
Hi @ganeshmuthuvelu!

Thanks for the report - unfortunately, Swagger-UI 2.x (which you referred to in your screenshot) is no longer under development. We'd be happy to consider any suggestions about the rendering in Swagger-UI 3, though!

Closing as 2.x wontfix.
