### ISSUE TITLE
Swashbuckle.AspNetCore (1.0.0): Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by spmanjunath** [swagger-api/swagger-ui#3764]
'Swagger UI' for an asp.net core application is not listing few of the API's.  The error logged in the browser console is "Uncaught RangeError: Invalid string length", there is no other information displayed.  The generated swagger.json file is valid, and i have attached for reference.  

I used both chrome Swagger-UI extension and the one exposed by .net web application (via Swashbuckle.AspNetCore) and noticed the same issue.
[RoleSwagger.txt](https://github.com/swagger-api/swagger-ui/files/1386908/RoleSwagger.txt)

**Comment by webron** [comment]
Can't seem to reproduce it with the current version of the UI. We don't maintain the chrome extension nor the one exposed by the .net web application, so I have no idea which versions those would be. The issue template contains details how to figure the version out, but you chose to completely ignore it.
FWIW, the API definition is not valid as it has references to models that don't exist.
