### ISSUE TITLE
cannot ignore spring variables

### ISSUE THREAD

**Issue by siluri** [swagger-api/swagger-ui#3765]
cannot ignore spring variables like HttpSession or HttpRequest 

`<springfoxVersion>2.5.0</springfoxVersion>`

Sample:
```
@Api()
@Controller
@RequestMapping(value="/preview", produces = "application/json; charset=UTF-8", method = {RequestMethod.GET})
public class BController {

...

@ApiOperation(value = "")
  @RequestMapping(value = "/requestContext/{id:.+}", method = {RequestMethod.GET}, produces="application/json; charset=UTF-8")
  public @ResponseBody RequestContext getRequestContext(@PathVariable String id, HttpSession session) {
```
Both doesnt ignore HttpSession
`@ApiParam(hidden = true) HttpSession session` `@ApiIgnore HttpSession session`

Always get following error:
```
Resolver error at paths./preview/requestContext/{id}.get.parameters.1.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/HttpSession does not exist in document
```

**Comment by shockey** [comment]
Hi @siluri, at first look this appears to be related to how Springfox is generating your Swagger document, not Swagger-UI's rendering.

Please open your ticket there, but if the problem does end up to be with Swagger-UI, feel free to bump this issue and I'll reopen it.

Thanks!
