### ISSUE TITLE
return "Unknow response type" when response is gzip Encoding

### ISSUE THREAD

**Issue by TopDstar** [swagger-api/swagger-ui#3766]
version: 3.3.2
issue: Return 200 status, but can not analysis response content. return "Unknown response type".

swagger.json:
![default](https://user-images.githubusercontent.com/12229551/31612649-fb12d852-b2b2-11e7-9a7c-e7f1530f1916.png)

Chrome debug:
![default](https://user-images.githubusercontent.com/12229551/31612622-e0d60bee-b2b2-11e7-83cb-62acdb4d92ae.png)

![default](https://user-images.githubusercontent.com/12229551/31612538-98e9a160-b2b2-11e7-932d-06d5c5198948.png)
![default](https://user-images.githubusercontent.com/12229551/31612622-e0d60bee-b2b2-11e7-83cb-62acdb4d92ae.png)

swagger ui return:
![default](https://user-images.githubusercontent.com/12229551/31612565-ab8f89ec-b2b2-11e7-8bc9-f14758ab9a13.png)

Could anyone help me?

**Comment by webron** [comment]
Your server is returning content without setting the `content-type`. That's a bad server. Teach it a lesson!

**Comment by TopDstar** [comment]
Hi @webron , thank you very much! You are right, it works when add content-type into headers of server response.
