### ISSUE TITLE
No operations defined in spec! in last swagger-ui-express, swagger-jsdoc and swagger 2.0 specification

### ISSUE THREAD

**Issue by paveltrufi** [swagger-api/swagger-ui#3770]
I'm using theese packages to generate my Swagger UI with its specification:
* [swagger-ui-express](https://github.com/scottie1984/swagger-ui-express)
* [swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc)

Currently, this is the JSON I am receiving ([image](https://goo.gl/kuZ1MX)) from http://localhost:3000/swagger.json, but swagger-ui doesn't recognize it as a proper JSON ([image](https://goo.gl/c8jyvV))

I don't know what I'm doing wrong. I've been looking for similar problems but they were because of version mismatch between the specification and UI, but I think I'm using the lastest ones.

Thanks for your help.

**Comment by webron** [comment]
Please re-file the issue following the issue template. We need the API definition as a file (we're not going to hand-type it from the image to test it), and we need to know exactly which version of swagger-ui you use.

**Comment by paveltrufi** [comment]
Ok so there was an error in mi program: as I am using Typescript in my development, I was exporting the Object created by swagger-jsdoc like this
```javascript
export default SwaggerJSDoc(options)
```
for some reasons this made the hole object be enveloped by the "default" key. The way I solved it is to use the module.exports sentence instead:
```javascript
module.exports = SwaggerJSDoc(options)
```
So the problem is solved :smile:
