### ISSUE TITLE
Examples not showing up for requestBody

### ISSUE THREAD

**Issue by awalsh-broadsoft** [swagger-api/swagger-ui#3771]
Using swagger-ui 3.3.1 running on Tomcat 9.x, testing with Chrome

I've tried looking up how other have added example(s) to their request body, but I can't seem to find any that work for me.

Here's an example of my openapi.json file:
{
  "openapi": "3.0.0",
  "paths": {
    "/pets/generatePetname": {
      "post": {
        "requestBody": {
          "description": "Generates random pet names",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "jsonschema/pets/generatePetname/post/request.body.schema.json"
              },
              **"example": {
                "$ref": "jsonschema/pets/generatePetname/post/request.body.example.json"
              }**
            }
          },
          **"examples": {
            "application/json": {
              "$ref": "jsonschema/pets/generatePetname/post/request.body.example.json"
            }
          }**
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "jsonschema/pets/generatePetname/post/response.200.body.schema.json"
                }
              }
            },
            "examples": {
              "application/hal+json": {
                "$ref": "jsonschema/pets/generatePetname/post/response.200.body.example.json"
              }}}}}}}}

I've set in bold the parts that don't seem to be working for me. I've tried every combination of swapping them out, such as:
{
  "openapi": "3.0.0",
  "paths": {
...
            "application/json": {
              "schema": {
                "$ref": "jsonschema/pets/generatePetname/post/request.body.schema.json"
              },
            }
          },
          **"examples": {
            "application/json": {
              "$ref": "jsonschema/pets/generatePetname/post/request.body.example.json"
            }
          }**
        },
...
  }
}

Or such as:
{
  "openapi": "3.0.0",
  "paths": {
...
            "application/json": {
              "schema": {
                "$ref": "jsonschema/pets/generatePetname/post/request.body.schema.json"
              },
              **"example": {
                "$ref": "jsonschema/pets/generatePetname/post/request.body.example.json"
              }**
            }
          }
        },
...
  }
}

###Expected behavior:
![expected-swagger-ui-issue](https://user-images.githubusercontent.com/17168790/31636152-f799d140-b28e-11e7-89bf-36172dc247a6.PNG)

###Actual behavior:
![actual-swagger-ui-issue](https://user-images.githubusercontent.com/17168790/31636145-ee848aaa-b28e-11e7-93d7-2c5b213b1bea.PNG)

The example for the response seems to work fine. No matter where I include the $ref for examples, it doesn't seem to show for me in request body. Am I using examples wrong?

Note: This issue seems like it might be similar to:
https://github.com/swagger-api/swagger-ui/issues/3437
However, I wasn't able to use any of the information in that issue to figure out if I was having the same problem.

**Comment by webron** [comment]
As you pointed out with #3437, the rendering of the examples is not yet implemented.
