### ISSUE TITLE
enum for params not registering

### ISSUE THREAD

**Issue by masterof0** [swagger-api/swagger-ui#3772]
![enum](https://user-images.githubusercontent.com/565883/31640212-8e06f5c8-b2a2-11e7-852f-67a19a16bb46.jpg)
When using enum in parameters, The UI only shows a string box and not the options provided in enum

Version 3.x

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.X
| Which Swagger-UI version?       | 3.X
| How did you install Swagger-UI? |  git clone
| Which browser & version?        | Chrome 61, Firefox 56
| Which operating system?         |  Windows 10

Gist of spec:
https://gist.github.com/masterof0/46dd46da6415e7f8ffd36c3de22fdc64

**Comment by shockey** [comment]
Thanks, @masterof0!

CC: #3641

**Comment by hkosova** [comment]
Enums seem to work now in the latest UI 3.4.0 and Editor 3.1.12.

**Comment by shockey** [comment]
I'm seeing that as well, @hkosova - I believe https://github.com/swagger-api/swagger-ui/pull/3796 fixed it.

Closing! Feel free to bump this thread if there are any issues going forward.
