### ISSUE TITLE
Chrome requires --disble-web-security for server variables

### ISSUE THREAD

**Issue by masterof0** [swagger-api/swagger-ui#3773]
Server variables only render when running Chrome with --disable-web-security

Version: 3.X

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   Bug
| Which Swagger/OpenAPI version?  | 3.X
| Which Swagger-UI version?       | 3.X
| How did you install Swagger-UI? | git clone
| Which browser & version?        | Chrome 61
| Which operating system?         |  Windows 10

Spec:
https://gist.github.com/masterof0/46dd46da6415e7f8ffd36c3de22fdc64

When using server variables in Chrome, the server variable does not render, but when running Chrome with the --disable-web-security option, the variable renders as expecte

![server_var](https://user-images.githubusercontent.com/565883/31640839-604a395c-b2a6-11e7-9b34-55aa4f4fd696.jpg)

**Comment by webron** [comment]
@masterof0 thanks for the issue, however, the spec you provided doesn't have server variables defined in it...

**Comment by masterof0** [comment]
Apologies. I updated the gist to reflect the server variables

**Comment by webron** [comment]
Which exact version of the UI do you use? Tried loading it now in Chrome 61 with no issues.

**Comment by masterof0** [comment]
I just did a git pull and it seems to be working. Thank you again

**Comment by webron** [comment]
Awesome, thanks for checking and reporting back.
