### ISSUE TITLE
Never prompted for authentication

### ISSUE THREAD

**Issue by masterof0** [swagger-api/swagger-ui#3774]
I am currently set up for basic auth. When I test any of the endpoints, I get a 401 and am never prompted for credentials. If I run Chrome with --disable-web-security, I am prompted as expected.
This also holds true for Firefox

I originally noticed this problem, but attributed it to CORS, but I think I have that issue resolve (no errors) but the authentication issue still persists

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.X
| Which Swagger-UI version?       | 3.X
| How did you install Swagger-UI? | git clone
| Which browser & version?        | Chrome 61, Firefox 56
| Which operating system?         |  Windows 10

Spec
https://gist.github.com/masterof0/46dd46da6415e7f8ffd36c3de22fdc64

![auth](https://user-images.githubusercontent.com/565883/31642226-73ad0c46-b2af-11e7-8f15-583f963f4f70.jpg)

**Comment by webron** [comment]
It's unclear at what point the basic auth is set up for - is it to load the UI? the API definition? executing a call?

**Comment by masterof0** [comment]
When executing an API call.

**Comment by webron** [comment]
The current version of Swagger-UI doesn't support authentication at all for 3.0.0 call executions. You can see that it's in our #3641 ticket. This feature is slated to be implemented and pushed by the end of the week.

**Comment by masterof0** [comment]
Apologies for the redundant ticket. Thank you

**Comment by webron** [comment]
No worries. It's better to get too many reports than no reports at all. Can never know when we might miss something. I'll be closing the ticket for now, but keep an eye out for this week's release!
