### ISSUE TITLE
index.html does not created using build operation!

### ISSUE THREAD

**Issue by JulieHakobyan** [swagger-api/swagger-ui#3776]
I have some changes in dist\index.html ( I change the url)  and after I build using 'npm run build ' index.html does not created, may be it cannot be created or there are another solution?

**Comment by shockey** [comment]
Hi @JulieHakobyan!

`dist/index.html` is _not_ a generated file. It's a bit of an anti-pattern, but we decided to keep it in `dist` for backwards compatibility with older versions of Swagger-UI.

You should be able to modify `dist/index.html` to suit your needs without needing to build the project.

Does this help?

**Comment by JulieHakobyan** [comment]
Yes. Thank you!
