### ISSUE TITLE
Failed to load spec with no error message

### ISSUE THREAD

**Issue by mooths** [swagger-api/swagger-ui#3782]
Tries to load a swagger JSON data from a swagger.NET  example using the following URL:

http://localhost:53683/webDemo/swagger/docs/v1

I can se in fiddler that the example WebAPI returns the json in UTF8 format:

HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNccmFqYW5cc291cmNlXHJlcG9zXHNsRGVtb1x3ZWJEZW1vXHN3YWdnZXJcZG9jc1x2MQ==?=
X-Powered-By: ASP.NET
Date: Thu, 19 Oct 2017 07:56:45 GMT
Content-Length: 4321

{"swagger":"2.0","info":{"version":"v1"," -..... etc

The sagger UI displays only ''Failed to load spec', no error message.

![image](https://user-images.githubusercontent.com/32263892/31760364-c3b476f0-b4b4-11e7-9194-d622b7d25431.png)

Swagger UI 3.X

I downloaded and unzipped the swagger-ui-master.zip, and run it from dist(/index.html.

**Comment by webron** [comment]
Very likely to be a [CORS](https://github.com/swagger-api/swagger-ui#cors-support) issue.

**Comment by mooths** [comment]
Yep. Took me a while. Fixed it. I had to add the **access** stuff to the .vs applicationhost.config file for my VS.
```
        <httpProtocol>
            <customHeaders>
                <clear />
                <add name="X-Powered-By" value="ASP.NET" />
                <add name="Access-Control-Allow-Origin" value="*" />
                <add name="Access-Control-Allow-Headers" value="Content-Type, api_key, Authorization" />
                <add name="Access-Control-Allow-Methods" value="GET, POST, DELETE, PUT" />
            </customHeaders>
```
Thank you for the swift reply.

However, a fault message with a hint would have been nice. Can't we check the coors stuff, or lack thereof in the response header when this fault appears?

**Comment by shockey** [comment]
Unfortunately, when there is a CORS error, a response never comes back to the application. The browser halts the request and reports a network error back to the application, so it's not possible for us to identify CORS errors specifically.

More information here: https://stackoverflow.com/questions/4844643/is-it-possible-to-trap-cors-errors

**Comment by shockey** [comment]
More specifically, this paragraph explains why browsers do such a thing:

> The browser looks at the response from that "other origin" server and, if it doesn't seem to be "taking part" in CORS - the required headers are missing or malformed - then we're in a position of no trust. We can't be sure that the script running locally is acting in good faith, since it seems to be trying to contact servers that aren't expecting to be contacted in this way. The browser certainly shouldn't "leak" any sensitive information from that remote server by just passing its entire response to the script without filtering - that would basically be allowing a cross-origin request, of sorts. An information disclosure vulnerability would arise.
