### ISSUE TITLE
Missing file browser in "Try it out" for multipart/form file uploads

### ISSUE THREAD

**Issue by dirkschneemann** [swagger-api/swagger-ui#3784]
Previously (in OpenAPI 2.0), when creating an endpoint which takes a file upload via a `multipart/form` `POST` request, the `Try it out` section in Swagger UI showed a `Choose File` button to select a file from my harddisk which then got uploaded when clicking the `execute` button.

Following [the docs on how to do such uploads in OpenAPI 3.0.0](https://swagger.io/docs/specification/describing-request-body/file-upload/), however, I am missing that button in Swagger UI and see a textbox instead with a JSON representation of the `schema`.

Is that expected behaviour (as in not yet implemented for OpenAPI 3.0.0) or is the file upload in my API definition incorrectly written?

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Could be both, depending on if this is expected behaviour 
| Which Swagger/OpenAPI version?  | OpenAPI 3.0.0
| Which Swagger-UI version?       | 3.3.2
| How did you install Swagger-UI? | [https://editor.swagger.io](https://editor.swagger.io) and self-hosted `dist` folder on `nginx`
| Which browser & version?        | Chrome 62.0 & Opera 48.0
| Which operating system?         |  Ubuntu 14.04

### Demonstration API definition

Working example in OpenAPI 2.0:
```yaml
swagger: '2.0'
info:
  title: Some API
  version: '1'
paths:
  /conversion/nmea/geojson:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            type: string
            example: "File upload successful"
```

Non-working example in OpenAPI 3.0.0:
```yaml
openapi: 3.0.0
info:
  title: Some API
  version: "1"

paths:
  /upload:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "File upload successful"
```

### Expected Behavior
![openapi_2 0](https://user-images.githubusercontent.com/3935022/31767795-d3ef2e26-b4cc-11e7-8834-7bc9b96921f5.png)

### Current Behavior
![openapi_3 0 0](https://user-images.githubusercontent.com/3935022/31767801-dc2c7224-b4cc-11e7-9441-4e03f4ea5a50.png)

**Comment by webron** [comment]
Closing in favor of #3641.

**Comment by jascao** [comment]
I meet the same issue, how to fix it?

**Comment by mikefidel** [comment]
I'm afraid I have hit the same road bump. Add one more to the "futures" bucket tally.

**Comment by jonbcampos** [comment]
@webron can this be reopened? Still not seeing and not easy to track in the other list

**Comment by evgenymarkov** [comment]
Same issue

**Comment by agostlg** [comment]
Same issue

**Comment by tmaus** [comment]
Same issue

**Comment by webron** [comment]
@here - this has been implemented and is supposed to work (just tested it myself). If you encounter an issue, please file a new ticket with steps and details to help us investigate.

**Comment by jonbcampos** [comment]
I can say that the update worked for me

**Comment by maxim-danilov** [comment]
The file browser button is still missing. 
My yaml:
```
requestBody:
  content:
    multipart/form-data:
      schema:
        required:
          - file
        properties:
          file:
            type: string
            format: binary
```
My dependencies:
    "swagger-ui-express": {
      "version": "4.0.1",
      "requires": {
        "swagger-ui-dist": "^3.18.1"
      }
    }
