### ISSUE TITLE
Asterisk not displayed in swagger ui page

### ISSUE THREAD

**Issue by drjrakesh** [swagger-api/swagger-ui#3787]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

Here is my parameter section from the json. as you can see there are few Asterisk in the description area, but it's being ignored in ui page.
In my java code I have following
```js
@ApiParam(value = "GroupEndpoints Object <p>The &#42; value in method means ALL http method&#46;</p><p>The &#46;&#42;&#46;&#42;/Courses/&#46;&#42;</p>", required = true)
```
```js
{
"name":"body",
"description":"GroupEndpoints Object <p>The * value in method means ALL http method.</p><p>The .*.*/Courses/.*</p>",
"required":true,
"type":"GroupEndpointList",
"paramType":"body",
"allowMultiple":false
}
```

`?yourQueryStringConfig=here`

**Comment by drjrakesh** [comment]
![swagger-ui-git](https://user-images.githubusercontent.com/15839843/31786834-b09439b6-b4be-11e7-9f6b-9d21fcce1aa0.PNG)

**Comment by webron** [comment]
This is an issue with the java tool you're using. The values need to stay escaped when converted to JSON and they are not.
