### ISSUE TITLE
OAS 3.0 Form Data Try-It-Out object serialization

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#3788]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.3.2
| Which browser & version?        | Chrome 61
| Which operating system?         | macOS High Sierra

### Demonstration API definition

```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: blah
servers:
- url: /
paths:
  /:
    post:
      description: asdf
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                address:
                  # complex types are stringified to support RFC 1866
                  type: object
                  properties: {}
      responses:
        200:
          description: OK
```

### Expected Behavior

I expect my request body value, shown below, to be serialized correctly.

```json
{
  "id": "string",
  "address": {}
}
```
### Current Behavior

The `address` object is not properly serialized before the request is sent:

<img width="342" alt="messages image 4135647482" src="https://user-images.githubusercontent.com/680248/31790766-6d1486d4-b4cb-11e7-81aa-b4417c634b05.png">

### Possible Solution

Non-primitive values should be serialized correctly, here: https://github.com/swagger-api/swagger-js/blob/2a3f113c1c219ec3756a73ffc35e366987ff6f5c/src/execute/oas3/build-request.js#L47

**Comment by banders** [comment]
I am also having a problem with form data in Try It Out.  

Using swagger-ui 3.4.2
OAS3 spec: https://raw.githubusercontent.com/banders/api-specs/upgrade-to-openapi3/jobposting/jobposting.json
(See the POST /jobs operation)

Clicking the execute button using the default request body results in a Javascript error on the page.

**Comment by shockey** [comment]
@banders this seems closely related, so I'll look into that as well. Sorry for the inconvenience!

**Comment by banders** [comment]
@shockey I'm still seeing the same problem I reported in the Nov 3 post.

Using swagger-ui 3.6.0
OAS3 spec: https://raw.githubusercontent.com/banders/api-specs/upgrade-to-openapi3/jobposting/jobposting.json
(See the POST /jobs operation)

"Try it Out" then "execute" results in a jvascript error.  

If you think this is unrelated to the original issue, I can write it up as new issue.

**Comment by shockey** [comment]
@banders, I think you're having a slightly different problem (my original issue was a serialization inaccuracy, not a thrown error), but I'll take a look. If I can reproduce the problem, no need for a ticket.

I'll circle back on this later today 😄

**Comment by banders** [comment]
@shockey I appreciate it.  Thanks!
