### ISSUE TITLE
Input text box with String value is unresponsive while using string with space or new line

### ISSUE THREAD

**Issue by makeshitdev** [swagger-api/swagger-ui#3800]
I am using swagger UI 3

In my project i need to fetch  the String value from input text box.

Input text box becomes unresponsive and it doesn't allow the String value with space or new line. When I enter the space in the input text box , this came up with default value as {}  and not able to remove these braces {} .

I found the same issue has been reported already but still i am facing this .

Already reported issue no :  https://github.com/swagger-api/swagger-ui/issues/3271

**Comment by webron** [comment]
Please file the ticket using our issue template. You haven't provided enough details.
