### ISSUE TITLE
Descriptions not displayed in C# data carrier

### ISSUE THREAD

**Issue by mooths** [swagger-api/swagger-ui#3801]
While testing swagger with Visual Studio 2017 I seem no to get swagger present the attributes of a class in its GUI. The class is used as an parameter to a GET. It is displayed nicely in the GUI as a JSON with its attribute names and types, but no description:

![image](https://user-images.githubusercontent.com/32263892/31875454-88940028-b7ce-11e7-8dc0-fdfd6e13b301.png)

The class looks like this

```
/// <summary>
    /// Mupp data
    /// </summary>
    public class MuppData
    {
        /// <summary>
        /// Constructor for mupp data
        /// </summary>
        public MuppData()
        {
            Value = "?";
        }
        /// <summary>
        /// A string
        /// </summary>
        public string Value { set; get; }
        /// <summary>
        /// Another string
        /// </summary>
        public string Value2 { set; get; }
        /// <summary>
        /// An integer
        /// </summary>
        public int Value3 { set; get; }

        /// <summary>
        /// A sub data
        /// </summary>
        public SubMuppData SubData { set; get; }
    }
```

And the GET like this:

      ` public IEnumerable<MuppData> Get()`

I'm using Swashbuckle.Core and Swashbuckle.WebHost in the example VS solution. I have looked around in the docs but seem not to find how to configure swagger-ui to show the descriptions like the above 'Astring', 'Another string' etc. The swagger UI is displaying the URL: http://localhost:53683/webDemo/swagger/docs/v1. When using the URL the JSON is displayed in the Edge window and the descriptions seem to be in the JSON like this:

```
....
":{"Value":{"description":"A string","type":"string"},"Value2":{"description":"Another string","type":"string"},"Value3":{"format":"int32","description":"An integer","type":"integer"},"SubData":{"$ref":"#/definitions/SubMuppData","description":"A sub data"}}},"
....
```
So what have I missed?

**Comment by hkosova** [comment]
Click the "Model Schema" link - descriptions should be there.

**Comment by mooths** [comment]
And there it is, stupid me! :)
![image](https://user-images.githubusercontent.com/32263892/31878509-a5ff3770-b7da-11e7-869e-97f7173fa97d.png)
Thank you!!!
