### ISSUE TITLE
"transfer-encoding: chunked" issue in swagger ui 3

### ISSUE THREAD

**Issue by makeshitdev** [swagger-api/swagger-ui#3802]
I am using swagger UI 3.

Our rest service will return a XML file which is bigger in size . So the jersey server sends the response as chunks. But swagger receives the first chunk and discarded the remaining chunks with the below message.
"transfer-encoding: chunked"

Could you please help me to resolve this issue.

**Comment by webron** [comment]
Again, please refile the ticket filling the issue template.
