### ISSUE TITLE
transfer-encoding: chunked issue in swagger 

### ISSUE THREAD

**Issue by makeshitdev** [swagger-api/swagger-ui#3808]
Our rest service will return a XML file which is bigger in size . So the jersey server sends the response as chunks. But swagger receives the first chunk and discarded the remaining chunks with the below message.

messgae :  "transfer-encoding: chunked"

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |  2.0 (modified, was 1.5.16 which is swagger-core's version)
| Which Swagger-UI version?       |  3.3.1
| How did you install Swagger-UI? |  Cloned the swaggerUI repository
| Which browser & version?        |  Chrome - 61.0.3163.100
| Which operating system?         |  Windows 10

### Demonstration API definition
Our code is client specific .So i cant share the demo example

### Configuration (browser query string, constructor, config.yaml)
We are using swagger.json which is generated at run time 

### Expected Behavior

Swagger should receive all the splitted chunks of file,compine them and display the full content with content-length header

![image](https://user-images.githubusercontent.com/32867776/31927088-107a074e-b8b0-11e7-9bdc-f6abbb4dc5a8.png)

### Current Behavior

got the message "transfer-encoding: chunked" . file is not diplayed
![image](https://user-images.githubusercontent.com/32867776/31927143-52dcf326-b8b0-11e7-81fc-c5219e94f63e.png)

### Possible Solution
--

### Context
We addressed this issue while downloading the file from our server using  swagger.Same API works well when we are using postman.

**Comment by makeshitdev** [comment]
@webron  Please let me know when this will be fixed.

**Comment by shockey** [comment]
This appears to be fixed!

I tested a chunked download with this definition:

```yaml
swagger: "2.0"

host: jigsaw.w3.org
basePath: /HTTP
schemes: 
- https

produces:
- application/octet-stream

paths:
  /ChunkedScript:
    get:
      description: 
      responses:
        200:
          description: ok
        
```

I also used a web proxy to add `Content-Disposition: attachment`.

The inline display and file download gave me the entire response, as I would expect.

@makeshitdev, if this is still a problem for you, reply here and we'll try to look into this further.
