### ISSUE TITLE
Try-it-out Execute button not working for OAS3

### ISSUE THREAD

**Issue by banders** [swagger-api/swagger-ui#3811]
Using swagger-ui v3.4.0, the Try-it-out Execute button doesn't do anything when clicked.  

Also, the Authorize button is always present, even if the spec has no security.  Could this be related to the problem with the Execute button?

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  bug
| Which Swagger/OpenAPI version?  | OAS3
| Which Swagger-UI version?       | v3.4.0
| How did you install Swagger-UI? | from github, then npm install, then npm run build.
| Which browser & version?        | Chrome Version 61.0.3163.100
| Which operating system?         | Windows 10

The issue can also be seen on the latest code installed at petstore.swagger.io:
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/banders/api-specs/upgrade-to-openapi3/bcgnws/bcgnws.json

### Demonstration API definition
https://raw.githubusercontent.com/banders/api-specs/upgrade-to-openapi3/bcgnws/bcgnws.json

### Configuration (browser query string, constructor, config.yaml)
query string: url=https://raw.githubusercontent.com/banders/api-specs/upgrade-to-openapi3/bcgnws/bcgnws.json

Try to execute any of the paths.  For example you can test with /names/search using required parameter name=Vancouver

### Expected Behavior
The Execute button should launch the request.  

### Current Behavior
The Execute button does nothing, even when required params are filled in.

**Comment by webron** [comment]
Looking at the console logs, there's something that triggers a problem. Note that some operations execute fine - like GET /feature/{featureId}.

As for the authorization button, can you file a separate ticket please?

**Comment by hkosova** [comment]
> Also, the Authorize button is always present, even if the spec has no security.

That's issue #3816.

**Comment by InhexSTER** [comment]
Also try it out button fails when using implicit OAuth flow, the lock icon status shows authorized (locked)
`
Uncaught TypeError: Cannot read property 'oauth_implicit' of undefined
    at index.js:1
    at Array.forEach (<anonymous>)
    at m (index.js:1)
    at Object.o [as buildRequest] (index.js:1)
    at actions.js:234
    at utils.js:121
    at bindActionCreators.js:3
    at wrap-actions.js:14
    at Object.r [as executeRequest] (system.js:166)
    at actions.js:273
`

**Comment by shockey** [comment]
@InhexSTER, an API definition that reproduces that would be helpful 😄

**Comment by InhexSTER** [comment]
```
components:
  securitySchemes:
    oauth_implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://mydomain.com/connect/authorize'
          scopes:
            api: 'Full Accces'
security:
  - oauth_implicit:
    - api 
```

**Comment by shockey** [comment]
OP's issue is due to a problem with string enums - looks like the first option is displayed as selected, but the actual staged request has an empty value for the required parameter (in this case, `outputFormat`). Manually setting the enum value lets the request fire as expected.

**Comment by shockey** [comment]
@InhexSTER, I'm not able to reproduce the problem you're having based on that definition - it sounds like a different problem from the above, though, so please open a new issue (along with a full OpenAPI definition that demonstrates the problem) and I'll happily look at it. Feel free to @ me in the issue.

**Comment by InhexSTER** [comment]
I tried out latest master code and it seems my issue is gone

**Comment by shockey** [comment]
@InhexSTER, glad to hear it! Feel free to bump this thread if the problem crops up again.
