### ISSUE TITLE
Required object validation

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3822]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | latest
| Which Swagger-UI version?       | 3.x
| How did you install Swagger-UI? | Swagger-Net
| Which browser & version?        | Chrome
| Which operating system?         | Win 10

### Demonstration API definition
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Noda#/NodaTime/NodaTime_GetByDate3 

### Expected Behavior
Any input should be correct...

### Current Behavior
The validation shows an error and the input box is colored red

### Possible Solution
PR coming soon

### Context
Just go trough the [Try it out] process enter something like "01-01-2001" and click [Execute] 
...you will see the error shakes the input box.
But there should be no validation there!?!?

**Comment by webron** [comment]
@heldersepu that's not a valid spec... in OAS2, query parameters can't be of type object...

**Comment by heldersepu** [comment]
Interesting, then the bug is on my side...

**Comment by heldersepu** [comment]
Is there any online tool to validate the spec?

**Comment by webron** [comment]
Yes, it's the validator badge that's removed in Swashbuckle's UI distribution ;) Check the bottom of the pet store.
