### ISSUE TITLE
Response header types not displayed with openapi 3

### ISSUE THREAD

**Issue by pratikpai** [swagger-api/swagger-ui#3836]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3
| Which Swagger-UI version?       | 3.4.1
| How did you install Swagger-UI? | Without any customization. Just copying the dist folder. The functionality doesn't work on the online swagger ui editor as well.
| Which browser & version?        | Chrome Version 61.0.3163.100 (Official Build) (64-bit)
| Which operating system?         | Windows 10

### Demonstration API definition

```yaml
openapi: 3.0.0
servers:
  - url: 'https://www.test.com/v1'
info:
  description: >-
    Some API
  version: v1
  title: Test API
tags:
  - name: Test
    description: API for Test
paths:
  '/test':
    get:
      tags:
        - Test
      summary: Test endpoint
      description: >-
        This is a test endpoint
      operationId: test
      parameters:
        - name: Accept
          in: header
          description: application/xml
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Test Successful.
          headers:
            Content-Type:
              description: application/xml
              schema:
                type: string
            X-TestId:
              description: >-
                Test Id.
              schema:
                type: string
          content:
            application/xml:
              schema:
                type: string
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior

It looks like a bug since it not displaying the response header types with the above spec on the online swagger editor also. However, I tried specifying it as per the earlier 2.0 spec i.e.

X-TestId:
   description: >-
      Test Id.
   **type: string**

The above change displays the type but does not conform with the specification.

**Comment by hkosova** [comment]
On an unrelated note, the `Accept` and `Content-Type` headers are not supposed to be defined explicitly, they are derived from `content.<media-type>`. The following is enough:
```yaml
      responses:
        '200':
          description: Test Successful.
          ...
          content:
            application/xml:   # <------
              schema:
                type: string

**Comment by pratikpai** [comment]
Thanks for pointing that out!

**Comment by hkosova** [comment]
This was fixed by https://github.com/swagger-api/swagger-ui/pull/3967 and included in the latest release.

cc @shockey

**Comment by pratikpai** [comment]
Thanks! Working as expected 👍
