### ISSUE TITLE
Appropriate access-control-origin settings

### ISSUE THREAD

**Issue by saprak11** [swagger-api/swagger-ui#3842]
Hello,
I have read numerous issues for enabling CORS issues on here and have enabled CORS on my server but I am still getting the appropriate access-control-origin settings error:
**_Can't read from server. It may not have the appropriate access-control-origin settings._**

1. I have this filter in my Tomcat's web.xml
```
     <filter>
       <filter-name>CorsFilter</filter-name>
       <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
     </filter>
     <filter-mapping>
       <filter-name>CorsFilter</filter-name>
       <url-pattern>/*</url-pattern>
     </filter-mapping>
```

2. I can access my swagger.json when I go to the local URL (http://localhost/myapp/swagger/swagger.json) in chrome.
3. But, It shows the error when swagger's index.html tried to access it. the swagger index.html is located at http://localhost/myapp/swagger/index.html

I am not sure what else to do. Any help will be appreciated.

Thank you

**Comment by webron** [comment]
@saprak11 from your description it sounds like you're using an old version of swagger-ui (and you need to mention which version you're using). If that's the case, it's possible the issue isn't a CORS issue but something else, as the error you're getting can appear as a result of other problems. You'd need to look at the browser's console to see more information.

**Comment by saprak11** [comment]
That was the issue. It was an older version of the UI. Thanks a lot.
