### ISSUE TITLE
server object (rather than servers object) not recognized

### ISSUE THREAD

**Issue by tomjoht** [swagger-api/swagger-ui#3846]
When I use a `server` object rather than a `servers` object, it's not recognized by Swagger UI. The curl request submitted doesn't use the URL specified by `server`. 

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.4.1
| How did you install Swagger-UI? |  from the dist folder
| Which browser & version?        | Chrome, latest
| Which operating system?         | MacOSX

### Demonstration API definition

1. Go to http://idratherassets.com/openapi_servers.yml and copy the spec into the Swagger Editor online.
2. Authorize, and then expand the second endpoint (weather) and click Try it out. 
3. Click Execute. You see the curl request submitted successfully using the URL specified in the `servers` object: `https://simple-weather.p.mashape.com`.
4. Now copy in this spec: http://idratherassets.com/openapi_server_single.yml. The only difference is that the server object is singular and looks like this: 

    ```
    server:
      url: https://simple-weather.p.mashape.com
      description: Production server
    ```
   According to the [servers object documentation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#server-object) in the spec, this is a valid way of defining the `server`.

5. Try to execute an endpoint again. You'll see the curl submitted shows this: 

   ```
    curl -X GET "https://editor.swagger.io/weather?lat=37.3708698&lng=-122.037593" -H "accept: text/plain" -H "X-Mashape-Key: EF3g83pKnzmshgoksF83V6JB6QyTp1cGrrdjsnczTkkYgYrp8p"
    ```

Instead of using `simple-weather.p.mashape.com`, `editor.swagger.io` is used instead. The url specified by the `server` object is ignored.

On a related note, the documentation for the [Server object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverObject) could be a little more clear by adding the object name to the example. I wasn't sure if it was `server` or `servers` in this code example: 

```
url: https://development.gigantic-server.com/v1
description: Development server
```

It would be clearer as this:

```
server:
    url: https://development.gigantic-server.com/v1
    description: Development server
```

However, I'm not sure if the doc is wrong altogether. Maybe a `server` object isn't even allowed. I can't tell based on the description of the [open api object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oasObject.

Even on this [servers doc page](https://swagger.io/docs/specification/api-host-and-base-path/), I couldn't find an example of a `server` rather than a `servers` object.

In the [petstore examples](https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0, where there's just 1 server, it always lists it like this: 

```
servers:
  - url: http://petstore.swagger.io/v1
```

Did I misread the spec on the `server` object? If so, maybe this is simply a doc but and not a Swagger UI bug.

**Comment by hkosova** [comment]
"Server Object" refers to an item in the `servers` array. There's no `server` keyword. A single server is defined as:
```yaml
servers:
  - url: https://development.gigantic-server.com/v1
    description: Development server
```

Swagger Editor reports `server` as an error, by the way.

**Comment by webron** [comment]
Adding to @hkosova's reply - the only place where `server` exists is under the Link Object. 

As for the examples in the specification (while off topic here) - we tried to give examples of the actual object representation and not within a given context. Some objects can be used in multiple places, not necessarily under the same property name, so that would potentially cause more confusion.

**Comment by tomjoht** [comment]
Thanks for clarifying. I misread the documentation. It gets a little confusing when the references to the object name switch between being singular or plural. For example, [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-6) the singular is used, but [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields) some terms are "Paths object" and "Components object." Why not "Path object" and "Component object"? Well, "component" as a singular sounds odd, but I don't get paths versus path. Is "Path" too similar to "Path item object"?

Under [Server object example](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#server-object-example), the doc might be clearer if you moved this section:

```
A single server would be described as:

{
  "url": "https://development.gigantic-server.com/v1",
  "description": "Development server"
}
url: https://development.gigantic-server.com/v1
description: Development server
```

to the [Links section](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#link-object) instead. Reason being, the `servers` object and the `server` object seem to be substantially different. Or at least throw in a clarifying note in that `server` object section that says something like this:

> The `servers` object appears at the root level of your OpenAPI description. Even if you have just one URL, the `servers` object holds an array. However, the `links` object can contain a `server` object (in the singular). If so, within the `links` object the `server` object can appear as a regular object, not as an array, like this...

Or something.

**Comment by webron** [comment]
The Swagger project is no longer responsible for the specification itself, so it's not 'you', it's 'they'.

The objects are named based on what they represents. The `Paths` Object contains multiple paths under it, so does the `Components` object. The `Server` object is a single instance of a server. Whereas the `servers` _property_ is an array of Server objects. When writing the spec, we (the OAI) tried to pay attention to the names and their meaning and there should be sound logic behind each case.

**Comment by shockey** [comment]
Closing, as this appears to be an OAS problem.

@tomjoht, the best place to share feedback on the specification documentation, AFAIK, is the [OAI/OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification/issues) issue tracker :smile: as @webron noted, we (the Swagger-UI team) have no control over it.

**Comment by tomjoht** [comment]
Sorry, the original issue got lost in the discussion about spec clarity. Let me restate it. The issue is that Swagger UI isn't recognizing the servers object when specified at the [operation object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object) level. If you specify one server at the root level, and another at the operation object level, the server url at the operation object level should override the server url at the root level for that operation. Swagger UI isn't doing that. Is that a bug with Swagger UI, or is the spec incorrect?

**Comment by shockey** [comment]
@tomjoht, no worries!

> Swagger UI isn't doing that. Is that a bug with Swagger UI, or is the spec incorrect?

Yeah, that _is_ a problem. We just don't support it at the moment, though I  expect that to change in the nearish future.

It looks like the problem you just described is covered in #3820. Putting aside the OAS discussion, is there anything we covered in this ticket that #3820 does not?

**Comment by tomjoht** [comment]
nope, you can close this. Perhaps from lack of sleep, I forgot that I had already logged #3820. Thanks for your quick reply. Re terminology, I'm still getting used to some of the spec language.
