### ISSUE TITLE
API URL with minus produces error

### ISSUE THREAD

**Issue by SuhovDE** [swagger-api/swagger-ui#3855]
Hi,

I have noticed that when swagger-ui is placed under URL with '-' (minus character) API specification is loaded and form works properly, but on the bottom of the page "Error" block is displayed. When you click it the following log is displayed: 
```js
{
  "schemaValidationMessages": [
    {
      "level": "error",
      "message": "Can't read from file https://some-subdomain.some-domain.com/API/api.json"
    }
  ]
}
```

Tested in IE 11 with swagger-ui 3.4.0

**Comment by shockey** [comment]
Hi @SuhovDE!

It sounds like you're talking about the validator badge, but I'm not certain.

If so: the validation badge uses an external service to validate your definition. If your URL (in your example, `https://some-subdomain.some-domain.com/API/api.json`) isn't accessible from the Internet or requires authentication, the validator badge will fail with an error.

If that isn't the problem - your original ticket doesn't include enough information to go on. I'm going to close this issue, if my note above doesn't explain what's going on, please open a new issue that follows the template we provide.

**Comment by SuhovDE** [comment]
Hi @shockey 
Yes, I'm talking about validator badge.
When I use localhost like https://localhost/API/api.json the badge is not displayed. But when I even use PC name (also with minus) in URL like https://pc-name/API/api.json (this URL should not be accessible from the internet as well with localhost) it is displayed. In both cases URL is correct and api.json can be loaded, Swagger-UI form works also. But only when "-" (minus) character exists in URL badge is displayed.

**Comment by webron** [comment]
@SuhovDE Swagger-UI detects localhost'ed definitions and doesn't display the badge by default. In the case of an internal URL the UI has no way of knowing whether it's accessible or not. You can disable the validator manually by using the parameters as described in the README.

**Comment by SuhovDE** [comment]
@webron , thank you for the solution.
