### ISSUE TITLE
Can’t get proper paragraphs in Markdown in descriptions

### ISSUE THREAD

**Issue by michalrus** [swagger-api/swagger-ui#3867]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.4.1
| How did you install Swagger-UI? | From the `dist/` directory in the repo.
| Which browser & version?        | Chromium 62.0.3202.75 
| Which operating system?         | NixOS 17.09

### Demonstration API definition

```yaml
choose-one: "irrelevant, applies to all / we’re using JSON autogenerated from Haskell / NDA / I don’t know the format to create a minimal repro by hand"
```

### Configuration (browser query string, constructor, config.yaml)

```js
"irrelevant as well, applies to all"
```

### Expected Behavior
Each time there is `"Par 1\n\nPar 2"` in a `"description"` field, we should get proper paragraphs. Paragraph spacing should be greater than 0.

### Current Behavior
There’s no space between `"Par 1"` and `"Par 2"`, they look as if the `"description"` contained just `"Par 1\nPar 2"`. The `<p/>`s are indeed generated correctly, but their `margin` is `0`.

### Possible Solution
Fix `<p/>`’s CSS.

Also: we’re now using `"\n\n\xe005e\n\n"` instead of just `\n\n` as a workaround to add artificial spacing between paragraphs. But this is crazy.

### Context
Describing more complex stuff often requires more than one paragraph. And if they are not spaced with some kind of vertical whitespace (`<p/>` margin), it’s very unreadable.

**Comment by Peter-Simpson** [comment]
Hi, 

I have the lines below in my yaml file but the lines are never treated as paragraphs, all I get is each paragraph starting on a new line but without a gap between it and the preceding line.

Is it the same bug as reported here?

Thanks, Peter

Appearance in Swagger UI:
![image](https://user-images.githubusercontent.com/38855929/52898505-c0dd4600-31d6-11e9-954d-6b04222648b2.png)

YAML File:
![image](https://user-images.githubusercontent.com/38855929/52898483-92f80180-31d6-11e9-8d64-7cad3eea10c3.png)

**Comment by michalrus** [comment]
Yes, yes, indeed it is. Sad. :broken_heart:

**Comment by yufei-cai** [comment]
[This line](https://github.com/swagger-api/swagger-ui/blob/98610f88a6945ff6d97970cdf688d3141deb43f9/src/style/_layout.scss#L451) looks like the cause. Removing it fixed paragraph formatting for me (whatever other effects there may be).

**Comment by westonpace** [comment]
A horizontal rule can be used as a workaround.  Ironically the horizontal rule itself does not display correctly but it does actually create a paragraph.  At least in version 3.23.3.

```
`    put:
      summary: Some summary
      description:
        This description

        ---

        Will have

        ---

        Multiple paragraphs

```

**Comment by webron** [comment]
Everyone, I may be missing something about the use case, but it looks like there may also be an issue with understanding how YAML and markdown work.

Markdown, when rendered, is converted to HTML as-is. Adding `\n` in markdown text is equivalent to putting that in an HTML string, which would be stripped. 

YAML has several controls that can help you manage paragraphs, by using multi-lines. However, it's important to know the differences between using `|` and `>`. Please refer to https://yaml-multiline.info for more information.

However, if I'm missing something about any of your use cases, please provide a fuller example and we'd be happy to look into it.

**Comment by webron** [comment]
Okay, I take it back. Sorry about that. There is an issue and we're looking into it.

**Comment by shockey** [comment]
Looks like #5520 solved this 🎉 

### Input

```yaml
swagger: "2.0"
tags:
  - name: item
    description: | 
      To Do - Create a tag for each resource in your api and tag the operations that relate to that resource. 
      Provide the documentation for the resource in the description of the tag.  
      The following views are supported by this resource. 
      - complete, includes all fields.
      - summary, includes only id, descriptor, name and description. 
      - otherView, includes only id, primaryCategory and secondaryCategories.
paths:
  /:
    get:
      description: "Par 1\n\nPar 2"

```

### Output

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/680248/62594808-c0259280-b890-11e9-8dae-d937411e1cf4.png">
