### ISSUE TITLE
Warning from React.js about a missing a "key" prop

### ISSUE THREAD

**Issue by ninja-inc** [swagger-api/swagger-ui#3871]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0
| Which Swagger-UI version?       | 3.4.3
| How did you install Swagger-UI? | http://editor.swagger.io
| Which browser & version?        | Chrome 61
| Which operating system?         | Mac Sierra

### Demonstration API definition
http://petstore.swagger.io/v2/swagger.json

### Configuration (browser query string, constructor, config.yaml)
nothing special

### Expected Behavior

No warning from React.js

### Current Behavior

When I run swagger-ui on my local with `npm run dev` I encounter below React warning.
```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <form>. See https://fb.me/react-warning-keys for more information.
    in input
```

### Possible Solution
I am ready for PR.

### Context

Chrome shows JS error.

**Comment by shockey** [comment]
Closing; #3872 fixed this.

Thanks @ninja-inc!
