### ISSUE TITLE
Authentication doesn't prompt when re-directing Swagger source

### ISSUE THREAD

**Issue by nickpothier1** [swagger-api/swagger-ui#3877]
### Context
I created a cross-site request in Swagger with the following specification:

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.X
| Which Swagger-UI version?       | 3.X
| How did you install Swagger-UI? |  Download Distribution via GitHub
| Which browser & version?        | Chrome 61
| Which operating system?         | Windows 10

### Expected Behavior
What is supposed to happen is an authentication prompt should occur.

### Current Behavior
I receive the following response:

![1](https://user-images.githubusercontent.com/33462930/32516575-c29f64c4-c3d1-11e7-993b-ce04eede3bf0.png)

As you can see from the image above, the base URL (qa) re-directs to another URL (ba). What is supposed to happen is an authentication prompt should occur. Instead the request just unauthorized and fails:
 
![2](https://user-images.githubusercontent.com/33462930/32516606-dcf4120c-c3d1-11e7-8a9a-041dceffdc6e.png)

I checked the bug that was fixed in Swagger 3.4.0 with issue [3774](https://github.com/swagger-api/swagger-ui/issues/3774), but I believe this issue is different due to the re-direct. Disabling internet security leads to authentication appearing though. Any suggestions on how to move forward?

**Comment by shockey** [comment]
Hi @nickpothier1! Sorry you're having issues. I see from the `WWW-Authenticate` in your response that your server is using HTTP Basic authorization.

I have some clarifying questions:

> an authentication prompt should occur

Have you defined a Security Scheme and requirement for your Basic authorization? You shouldn't expect that Swagger-UI will give you a chance to provide out-of-band authorization for your requests 😄 

If you define your authorization flow inside your OpenAPI definition, you can use the Authorize button built into Swagger-UI to authorize your requests.

More here: https://swagger.io/docs/specification/authentication/basic-authentication/

> Disabling internet security leads to authentication appearing

What do you mean by this? Are you running a firewall on your machine, or are you referring to the `--disable-web-security` Chrome flag?

**Comment by nickpothier1** [comment]
Hi @shockey,

Thanks for the quick reply. We do have a security scheme for Basic Authentication:

  "securityDefinitions": {
    "basic": {
      "type": "basic",
      "description": "Basic HTTP Authentication"
    }

As well we did toggle the --disable-web-security Chrome flag.

Let me know,
Nick

**Comment by webron** [comment]
Is that security scheme applied to the operation in hand? It really would help to see a full definition.

**Comment by shockey** [comment]
@nickpothier1, bump 😄

**Comment by nickpothier1** [comment]
We looked into it more, and we found out it was more of an internal issue vs an issue with Swagger.

Thanks for the help!

**Comment by shockey** [comment]
Great, glad you got it figured out. Feel free to reach out if you have any more issues.

Closing!
