### ISSUE TITLE
Flag to toggle rendering of raw HTML in Response Body frame

### ISSUE THREAD

**Issue by snebjorn** [swagger-api/swagger-ui#3881]
The reason html isn't rendered is discussed in #1748 and is sound.

However when developing a web API it would be very handy to have HTML rendered. For instance when working with ASP.NET Core you can do this:

```
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
```

Which will give you a nice error page (HTML). https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling

So my proposal is to have a flag that can toggle between these two states:

```diff
--- swagger-ui.js   2015-09-19 20:58:10.000000000 +0200
+++ swagger-ui.js   2015-11-16 13:45:26.958266568 +0100
@@ -31855,9 +31855,10 @@

     // HTML
     } else if (contentType === 'text/html') {
-      code = $('<code />').html(_.escape(content));
-      pre = $('<pre class="xml" />').append(code);
-
+      var iframe = document.createElement('iframe');
+      iframe.srcdoc = content;
+      iframe.style = 'width: 100%; height: 500px;';
+      pre = iframe;
     // Plain Text
     } else if (/text\/plain/.test(contentType)) {
       code = $('<code />').text(content);
```
_Source https://github.com/swagger-api/swagger-ui/issues/1748#issuecomment-232041300_

Then 3rd party libraries like [Swashbuckle](/domaindrivendev/Swashbuckle) can set this flag when in _development mode_ and have swagger-ui render the HTML. When running in production the HTML will be displayed as text.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  feature request
| Which Swagger-UI version?       | future

**Comment by webron** [comment]
We are no longer accepting feature requests for the 2.X versions of swagger-ui.

**Comment by snebjorn** [comment]
Oops! I see you're at 3.4.3. I just took the version Swashbuckle referenced.

A future version would suffice :)

**Comment by heldersepu** [comment]
@snebjorn If you can give [Swagger-Net](https://www.nuget.org/packages/Swagger-Net/) a try, that is my fork of Swashbuckle but I'm using the latest of swagger-ui

**Comment by enemyofthedawn** [comment]
@snebjorn You closed this, did using Swagger-Net from @heldersepu solve your problem? If I'm not wrong current version of swashbuckle uses 3.x version of swagger-ui but I still see raw HTML in my responses.

**Comment by snebjorn** [comment]
I didn't find a solution as it was a "nice to have" so it wasn't worth the time.
I don't recall why I closed it. Perhaps I wanted to see what Swashbuckle did when it updated the swagger ui dependency.

**Comment by heldersepu** [comment]
@enemyofthedawn yes I have this problem addressed in my "fork" 
honestly is not a fork anymore, I detach it and have done a LOT of bug fixes and improvements at this point merging will be very very difficult.

But for this issue all you need to worry about is that [Swagger-Net](https://www.nuget.org/packages/Swagger-Net) uses the latest of Swagger-UI
