### ISSUE TITLE
Pre loading base schemas to avoid relative references

### ISSUE THREAD

**Issue by awalsh-broadsoft** [swagger-api/swagger-ui#3883]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.x
| How did you install Swagger-UI? | running on a tomcat servlet
| Which browser & version?        | chrome
| Which operating system?         | windows 10

### Current Behavior
At the moment, while adding APIs to my openapi.json, I've had to change all of the references to relative references.
So the references will change from:
"$ref": "base.dict.schema.json#/definitions/NameField"
to:
"$ref": "../../../base.dict.schema.json#/definitions/NameField"

While the relative reference works, it means that my schema's references are locked into my current directory structure.

### Possible Solution
To avoid this other third party json schema tools will allow you to pre-load base schemas and store them according to their id fields.
So my base.dict.schema.json document will have an id like this:
"id": "base.dict.schema.json#"
and all of my references from other json schema documents can refer to the base like this:
"$ref": "base.dict.schema.json#/defintions/Whatever"

Will swagger-ui ever allow you to pre-load certain schemas so that you don't need to have relative references everywhere in your schema documents?

**Comment by webron** [comment]
`id` is not supported in the spec, so that's not a solution. We could implement a way of specifying a base path for all relative reference resolutions.

However, generally speaking, yes - relative paths do mean that you need to stick to a given directory structure.

**Comment by awalsh-broadsoft** [comment]
Shoot, sorry for not responding. You can close this I think.
