### ISSUE TITLE
Not able to disable validator in swagger ui even after trying in latest version

### ISSUE THREAD

**Issue by naveenkumar-007** [swagger-api/swagger-ui#3886]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by shockey** [comment]
Closing this, as your issue body has absolutely no details.

Please open a new ticket and fill in the template correctly.

**Comment by naveenkumar-007** [comment]
Hi kyle,

I created new ticket. please help.

Thanks,
Naveen

**Comment by naveenkumar-007** [comment]
Hi kyle,

I created new ticket. please help.

Thanks,
Naveen
