### ISSUE TITLE
Unable to build with latest updated version 3.4.4

### ISSUE THREAD

**Issue by gohelkiran30** [swagger-api/swagger-ui#3896]
Just downloaded the latest version and trying to create a build after removing topbar module but its getting failed.
Attached npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle swagger-ui@3.4.4~prebuild: swagger-ui@3.4.4
6 silly lifecycle swagger-ui@3.4.4~prebuild: no script for prebuild, continuing
7 info lifecycle swagger-ui@3.4.4~build: swagger-ui@3.4.4
8 verbose lifecycle swagger-ui@3.4.4~build: unsafe-perm in lifecycle true
9 verbose lifecycle swagger-ui@3.4.4~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/kiran/Downloads/swagger-ui-master/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/kiran/.local/bin:/home/kiran/bin
10 verbose lifecycle swagger-ui@3.4.4~build: CWD: /home/kiran/Downloads/swagger-ui-master
11 silly lifecycle swagger-ui@3.4.4~build: Args: [ '-c',
11 silly lifecycle   'npm run build-core && npm run build-bundle && npm run build-standalone' ]
12 silly lifecycle swagger-ui@3.4.4~build: Returned: code: 1  signal: null
13 info lifecycle swagger-ui@3.4.4~build: Failed to exec build script
14 verbose stack Error: swagger-ui@3.4.4 build: `npm run build-core && npm run build-bundle && npm run build-standalone`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid swagger-ui@3.4.4
16 verbose cwd /home/kiran/Downloads/swagger-ui-master
17 error Linux 4.12.14-200.fc25.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error swagger-ui@3.4.4 build: `npm run build-core && npm run build-bundle && npm run build-standalone`
22 error Exit status 1
23 error Failed at the swagger-ui@3.4.4 build script 'npm run build-core && npm run build-bundle && npm run build-standalone'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the swagger-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build-core && npm run build-bundle && npm run build-standalone
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs swagger-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls swagger-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.4.4
| Which Swagger-UI version?       | 3.4.4
| How did you install Swagger-UI? |  Download Zip
| Which browser & version?        | 
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by hkosova** [comment]
I don't know about the error, but if you just need to remove the Topbar, an easier way is to change `dist\index.html` as follows:
```javascript
  // Build a system
  const ui = SwaggerUIBundle({
    url: "http://petstore.swagger.io/v2/swagger.json",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis
    ]
  })
```

There's no need to rebuild the code in this case.

Credit goes to @shockey - https://github.com/swagger-api/swagger-ui/issues/3229#issuecomment-336556255.

**Comment by heldersepu** [comment]
@hkosova I just tried that modification to the index... 
and there is a message that flashes:
`<h4 data-reactroot="">No spec provided.</h4>`
 before we get to see the swagger-ui.

Another option that I've been using it is to just hide it using CSS:
`.topbar {display:none}`

**Comment by hkosova** [comment]
@gohelkiran30 did you `npm install` before `npm run build`?

**Comment by shockey** [comment]
@heldersepu, are you providing a `url` parameter? If you don't provide a url, the UI doesn't have anything to do.

I see what you're describing with the latest if I omit the default `url: "http://petstore.swagger.io/v2/swagger.json",` in `dist/index.html`.

**Comment by heldersepu** [comment]
@shockey Yes I did, I changed the index.html exactly as suggested by @hkosova

**Comment by heldersepu** [comment]
@shockey  Take a look here: http://nhc-noaa.azurewebsites.net/dist/index.html

**Comment by shockey** [comment]
@heldersepu, thanks, looking now.

---

@gohelkiran30, we've seen this error before (in #2845, #3027, #3153) - in all cases, the problem was different, so this particular stack trace is not helpful.

Some questions for you:
- Did you run `npm install` before running `npm run build`?
- What OS are you using? You left that Q&A section blank.

As seen in #3027, this can be an OS-specific problem.

**Comment by shockey** [comment]
@heldersepu, ah, I see what you're saying now, the message _flashes_. Sorry, I missed that in your original comment!

Let's move this discussion out of this issue - I'll open a new ticket in a moment.

**Comment by gohelkiran30** [comment]
it was npm install issue
thanks all
