### ISSUE TITLE
Low visibility of headers in markdown tables

### ISSUE THREAD

**Issue by hugo19941994** [swagger-api/swagger-ui#3897]
Hi!

Since version 3.3.2 (3.3.1 works fine) the headers of tables inside the response description fields can barely be seen.

I think this behavior changed after commit 2cd4989c056fd02ecf0e88c75910a1b961c2997e

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0, maybe 3.0
| Which Swagger-UI version?       | 3.3.2+
| How did you install Swagger-UI? | Manually
| Which browser & version?        | Chrome 62
| Which operating system?         | Linux

### Demonstration API definition
```yaml
400:
  description:
    | Error Code | Description                                          |
    | --------------- | ---------------------------------------------------- |
    | 1                | Missing X-Client-Code request header |

```

### Expected Behavior
![3-3-1](https://user-images.githubusercontent.com/6431131/32727993-f54c79f0-c87e-11e7-9ea2-8977a03f72e7.png)

### Current Behavior
![3-3-2](https://user-images.githubusercontent.com/6431131/32727994-f5654322-c87e-11e7-9ea4-bb43af485819.png)

### Possible Solution
Can be quickly fixed by changing the layout SCSS file. Just make th white inside .response-col_description__inner

https://github.com/hugo19941994/swagger-ui/commit/9dac9f348400fe859ee7738ea42a433c194b898f

![fix](https://user-images.githubusercontent.com/6431131/32728494-dd1647a6-c880-11e7-8dc5-c034ebc43699.png)

**Comment by owenconti** [comment]
@hugo19941994 Could you please send a full swagger spec?

**Comment by hugo19941994** [comment]
Thanks for taking a look @owenconti !

I realised today that the horizontal bar which separates the headers has bad visibility too. I've sent an alternative PR to yours which also sets the bar to the same color as the text.
