### ISSUE TITLE
Minor (cosmetic): CSS overflow/wrapping issue

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-ui#3899]
![image](https://user-images.githubusercontent.com/3127736/32743264-2416677a-c869-11e7-82c5-f9cae7d046c3.png)

I hope it's clear from the image. Commit dated: 11/11/2017. Horizontal scrollbar does show.

I don't know what's better to suggest: wrap (to avoid horizontal scrollbar, but then presentation might get ugly, being that model-names tend to be long and would word-break badly) or go-wide (with horizontal scrollbar).

Perhaps option #2 is easier, as it's already there (that table.parameters is what drives this); I was going to suggest to maybe remove the right border and right-gradient bg-color to white, but I can't quickly find where the  gray border comes from (I was able to get rid of the "green" one and the corner-radius).

**Comment by webron** [comment]
@hlubovac  can you provide with an API definition that reproduces it?

**Comment by hlubovac** [comment]
I was going to submit what you asked, but then I just discovered that this problem isn't about swagger-json content, but more about CSS related to viewport width.

"Enough" width:
![image](https://user-images.githubusercontent.com/3127736/32914083-92ca3a60-cad1-11e7-8b25-7b5b8174e783.png)

Not enough width:
![image](https://user-images.githubusercontent.com/3127736/32914104-a48ec78e-cad1-11e7-9a0e-71026065c6e3.png)

![image](https://user-images.githubusercontent.com/3127736/32914125-b6439928-cad1-11e7-8d32-b3bc08da579d.png)

Here's the sample that you asked for anyway:
[agent.json.txt](https://github.com/swagger-api/swagger-ui/files/1480152/agent.json.txt)

**Comment by webron** [comment]
@hlubovac just tried loading it in the latest master, and can't really reproduce it (tested in both FF and Chrome).

**Comment by hlubovac** [comment]
That's weird, because I copied master on 11/11, which is the latest, I think.

So, as you're decreasing the width of the window, what happens to these two boxes (green and blank, in the example above)?

**Comment by webron** [comment]
They just get minimized and adjust to the width.

**Comment by hlubovac** [comment]
If we're looking at the same source, `table.parameters` (present within each endpoint-block) will not allow wrapping beyond its width. Maybe you didn't expand an endpoint-block?

Collapsed, everything wraps fine:
![image](https://user-images.githubusercontent.com/3127736/32962869-4699a378-cb8b-11e7-8004-d24b044eaf96.png)

Uncollapsed, it's not:
![image](https://user-images.githubusercontent.com/3127736/32962898-622a65be-cb8b-11e7-8605-c5a1a4decc60.png)

![image](https://user-images.githubusercontent.com/3127736/32962941-95c0b202-cb8b-11e7-8892-5a6d580a2484.png)


But, again, it's cosmetic.

**Comment by webron** [comment]
I'm not really very worried about supporting _that_ width.

**Comment by hlubovac** [comment]
Below 1155px is when it starts overlapping content.
Although that 350 would be nice for my phone :) - but I understand: for the purpose of the content, it's not necessary.

Thanks.

**Comment by iamandrewluca** [comment]
I also encountered issue and found the problem. I'll make a PR.
