### ISSUE TITLE
Oauth2 flow

### ISSUE THREAD

**Issue by Fjandin** [swagger-api/swagger-ui#3901]
Not sure i'm misunderstanding something but i did setup swagger ui with oauth2 implicit. But the redirect uri seems to be hardcoded to `http://localhost:3200/`. Any way to change this?

**Comment by webron** [comment]
Check `oauth2RedirectUrl` under https://github.com/swagger-api/swagger-ui#parameters.

**Comment by shockey** [comment]
Hi @Fjandin!

There's an `oauth2RedirectUrl` configuration option that you can set. Documentation is here: https://github.com/swagger-api/swagger-ui#parameters.

**Comment by Fjandin** [comment]
Ah! Missed that one. Works perfectly. Thanks :)
