### ISSUE TITLE
Providing configuration via Docker

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#3902]
### Expected Behavior

I should be able to set any UI configuration option when using the Docker image.

### Current Behavior

Some Docker ENV=>config mappings exist, but they are arbitrarily chosen and can only accept string values.

### Possible Solution

Expose a `CONFIG_JSON` env variable that is parsed and applied, resulting in something like `CONFIG_JSON='{"docExpansion": "none"}'`.
- More robust, but harder to deal with in practice.
- Writing JSON by hand is a pain, OTOH it's a nice solution for automated uses.

Create 1:1 env<>option bindings, resulting in something like `DOC_EXPANSION=none`.
- Prettier, but requires careful upkeep when new options are added.
- Only allows string values, unless we get very clever. And clever tends to break.

Or..... both?

### Context

Inspired by swagger-api/swagger-editor#1546.

**Comment by Gabology** [comment]
Any update for this?
