### ISSUE TITLE
AdditionalProperties are not displayed in Swagger-UI

### ISSUE THREAD

**Issue by dawaji** [swagger-api/swagger-ui#3918]
Hi,
I'm using Swagger 2 and Swashbuckle precisely.
Swagger-UI 2 doens't show my model correctly. It doesn't interpret the additionalProperties. 

The response of swagger-ui is:

`PocSwaggerWithFluentValidation.Models.DictionaryErrorModel {
ValidationErrors (inline_model, optional, read only)
}
inline_model {}`

The json schema of my model is :
` "PocSwaggerWithFluentValidation.Models.DictionaryErrorModel": {
      "type": "object",
      "properties": {
        "ValidationErrors": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/SeLoger.WebApi.Toolkit.Models.ErrorModel[System.String]"
          },
          "readOnly": true
        }
      }
    },
    "SeLoger.WebApi.Toolkit.Models.ErrorModel[System.String]": {
      "type": "object",
      "properties": {
        "Errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SeLoger.WebApi.Toolkit.Models.IErrorEntry[System.String]"
          },
          "readOnly": true
        }
      }
    },
    "SeLoger.WebApi.Toolkit.Models.IErrorEntry[System.String]": {
      "type": "object",
      "properties": {
        "Code": {
          "type": "string",
          "readOnly": true
        },
        "Message": {
          "type": "string",
          "readOnly": true
        }
      }
    },`

Could you fix the bug?
Thanks

**Comment by webron** [comment]
Swagger-UI 2.x doesn't support additionalProperties. Use Swagger-UI 3.x instead.

**Comment by dawaji** [comment]
Thanks! good to know!

**Comment by dawaji** [comment]
Is there a fix that i can add into my api to render the additional properties or it's too complicated?

Thanks!

**Comment by webron** [comment]
You can use the latest swagger-ui.

**Comment by dawaji** [comment]
Hi, 
I'm using Swashbuckle and the lastest version uses the swagger-ui 2. I'm wondering if i can customize the swagger-ui by injecting some javascript code? is it possible?
Thanks!

**Comment by webron** [comment]
Anything is possible, it's an open source project. However, we do not provide support for swagger-ui 2.X anymore, so for any changes you make, you're on your own.
