### ISSUE TITLE
Need to hide fields from the Response

### ISSUE THREAD

**Issue by timleung22** [swagger-api/swagger-ui#3923]
I am on Swagger 2 with Springfox 2.7.0.  I have APIs that returns classes protoc generated classes.  These classes have many getter/setter methods that are for internal protoc implementations (some of the things are like, OrBuilder and defaultInstanceForType) and it makes no sense to show them to the users.  I want to just show under the Response Class section, for both Model and Example Value, just those properties that are relevant to the users.  

For example, my Example class, which is to be returned by my getXX() API method, 

Example {
allFields (inline_model_9, optional),
childExample (Example, optional),
childExampleOrBuilder (ExampleOrBuilder, optional),
defaultInstanceForType (Example, optional),
descriptorForType (Descriptor, optional),
exampleAlternateId (string, optional),
exampleAlternateIdBytes (ByteString, optional),
exampleBigDecimal (number, optional),
exampleBigDecimalOrBuilder (BigDecimalOrBuilder, optional),
initialized (boolean, optional),
unknownFields (UnknownFieldSet, optional)
}

Only exampleAlternateId and exampleBigDecimal are really what should be shown to the user.

**Comment by webron** [comment]
Take the time to read the ticket template and follow the instructions, instead of ignoring it and hoping for the best. There are details there we actually require.
