### ISSUE TITLE
Select scope with multiple flows in security scheme

### ISSUE THREAD

**Issue by k42b3** [swagger-api/swagger-ui#3925]
Hi, in case we have two flows for the same security scheme and those flows define the same scopes, it is not possible to select a scope from the lower flow since both checkboxes have the same id (in this case i.e. `todo-checkbox-app`).

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenAPI 3
| Which Swagger-UI version?       | master
| How did you install Swagger-UI? | Github
| Which browser & version?        | 
| Which operating system?         | 

```json
"securitySchemes": {
	"app": {
		"type": "oauth2",
		"flows": {
			"password": {
				"tokenUrl": "http:\/\/127.0.0.1\/projects\/fusio\/public\/index.php\/authorization\/token",
				"scopes": {
					"todo": "Todo app",
					"authorization": "Authorization API endpoint"
				}
			},
			"authorizationCode": {
				"authorizationUrl": "http:\/\/127.0.0.1\/projects\/fusio\/public\/developer\/auth",
				"tokenUrl": "http:\/\/127.0.0.1\/projects\/fusio\/public\/index.php\/authorization\/token",
				"scopes": {
					"todo": "Todo app",
					"authorization": "Authorization API endpoint"
				}
			}
		}
	},
}
```

### Expected Behavior
It should be possible to select a scope for each flow.

### Possible Solution
Adding the flow type i.e. `authorizationCode`, `password`, etc. to the id of the element should fix this problem.

**Comment by webron** [comment]
Thanks for the report. Please consider submitting a PR to fix it.

Out of curiosity, which library do you use to generate your API definition?

**Comment by k42b3** [comment]
Hi, ok no problem I have created a PR at #3929 

Iam using Fusio (https://www.fusio-project.org/) to generate this API spec. Note Iam also the author, for the next release I plan to include also the swagger-ui client and while testing I came across this issue.

**Comment by webron** [comment]
@k42b3 thanks for the PR, we'll review it shortly.

Happy to see another library out there. The reason I asked is that it looks like the URLs provided as values seem to be needlessly escaped. Since you're its author, you might want to consider changing that behavior.

**Comment by shockey** [comment]
This appears to be fixed now :smile: thanks @k42b3!
