### ISSUE TITLE
Swagger-UI v3.4.5 OAuth2 Missing Button Authorized

### ISSUE THREAD

**Issue by Zap-Dev** [swagger-api/swagger-ui#3940]
I can not understand why the **authorization** button does not appear.

I'm using the dist version and following the instructions I set:
```
const ui = SwaggerUIBundle({...})

// Method can be called in any place after calling constructor SwaggerUIBundle
ui.initOAuth({
    clientId: "your-client-id",
    clientSecret: "your-client-secret-if-required",
    realm: "your-realms",
    appName: "your-app-name",
    scopeSeparator: " ",
    additionalQueryStringParams: {test: "hello"}
  })
```
but when i run swagger-ui, the Authorize button does not appear

![schermata del 2017-11-21 21-35-38](https://user-images.githubusercontent.com/17761109/33098632-fad3ad48-cf05-11e7-9a75-2799a77e4f0d.png)

**Comment by webron** [comment]
The issue template is there for a reason. Take the time to fill it, so we can help you better.
