### ISSUE TITLE
failed to parse JSON/YAML response in asp.net core 2.0

### ISSUE THREAD

**Issue by masaab** [swagger-api/swagger-ui#3948]
I am getting the error  failed to parse JSON/YAML response. I dont know why have looked into everything doesnot make any sense.
public class Startup
    {
        private readonly IHostingEnvironment _hostingEnv;

        public IConfigurationRoot Configuration { get; }

        public Startup(IHostingEnvironment env)
        {
            _hostingEnv = env;

			var builder = new ConfigurationBuilder()
				.SetBasePath(env.ContentRootPath)
				.SetBasePath(Directory.GetCurrentDirectory())
				.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
				.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: false, reloadOnChange: true)
				.AddEnvironmentVariables();

            Configuration = builder.Build();
		}
  
    
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc(options =>
            {
                options.Filters.Add(typeof(CustomExceptionFilterAttribute));
                options.Filters.Add(typeof(ValidationModelActionFilterAttribute));
            });
            services.AddRouting();
            services.AddAuthorization();

            
            services.AddDistributedMemoryCache();

            if (_hostingEnv.IsDevelopment() || _hostingEnv.IsStaging())
            {

                services.AddSwaggerGen(c =>
                {
                    c.SwaggerDoc("v1", new Swashbuckle.AspNetCore.Swagger.Info
                    {
                        Title = "testREST API",
                        Version = "V1",
                        Description = "API to generate lead and return the url",
                        TermsOfService = "Please see terms and conditions",
                        Contact = new Swashbuckle.AspNetCore.Swagger.Contact
                        {
                            Name = "test",
                            Email = "support@test.com.au",
                            Url = "https://www.test.com.au/"
                        }
                    });

                    var path = System.AppDomain.CurrentDomain.BaseDirectory + "test.Api.Public.xml";
                    var basePath = PlatformServices.Default.Application.ApplicationBasePath;
                    var xmlPath = Path.Combine(basePath, "test.Api.Public.xml");
                    c.IncludeXmlComments(xmlPath);
                });
            }
            
            ResolveDependency.RegisterLogDependency(services, Configuration);
            services.AddSingleton(provider => Configuration);
            ResolveDependency.RegisterDependency(services);
            MapperConfiguration autoMapper = new MapperConfiguration(cfg => cfg.AddProfile<AutoMapperProfileConfiguration>());
            services.AddSingleton(autoMapper);
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(o =>
            {
                o.Authority = Configuration.GetSection("UrlModel:IdentityServerBaseUrl").Value; //"http://localhost:5000";
                o.Audience = "test.api.public";
                o.RequireHttpsMetadata = false;
            });
        }

		// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            app.UseAuthentication();
            
            app.UseMiddleware<RequestResponseLoggingMiddleware>();
            app.UseWhen(context => (context.User.Identity.IsAuthenticated && context.Request.Path.ToString().Contains("businesses")),
               appBuilder => {
                   appBuilder.UseMiddleware<BusinessValidationMiddleware>();
               });
            app.UseWhen(context => (context.User.Identity.IsAuthenticated && context.Request.Path.ToString().Contains("payers/")),
           appBuilder => {
               appBuilder.UseMiddleware<PayerValidationMiddleware>();
           });
            app.UseSwagger();
            app.UseSwaggerUI(a =>
           {
               var basePath = PlatformServices.Default.Application.ApplicationBasePath;
               a.SwaggerEndpoint(Path.Combine(basePath,"/swagger/v1/swagger.json"), "testRest API");
               a.RoutePrefix = "docs";
           });

            app.UseCors("AllowAll");
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseMvc();
        }
    }

**Comment by shockey** [comment]
@masaab, I'm not sure what to do with the Java code you've provided 😕 

I'm going to close this issue - please open a new one, and follow the template. You'll need to provide your Swagger definition in JSON or YAML format (_not_ Java code that generates the definition), and please also include screenshots of what's going wrong.

Feel free to ping me in the new issue. Thanks!
