### ISSUE TITLE
OAuth Token is not used in Try it out request

### ISSUE THREAD

**Issue by christophsteiner** [swagger-api/swagger-ui#3961]
Hello,
 I am using Swagger UI Version 3.5.0 to gather my existing Swagger 2 Endpoints. 
Everything works fine so far. The endpoints themself have a OAuth Config for Password flow 
inside. When I click on authorize the OAuth Authorization works fine.
The Bearer Token is visible in the CURL Example in the Try It Out section and the command
can be copied to a bash and executed successfully. 
The problem is that when pressing on execute the request will be sent without the bearer token.
(Verified by Developer Console of Chrome).
Does anyone have a similar issue?

**Comment by webron** [comment]
What _do_ you see in the developer console?

**Comment by kopax** [comment]
>  When I click on authorize the OAuth Authorization works fine.
What do you mean ? Could you please post your full configuration?

**Comment by christophsteiner** [comment]
Hi, the problem was an HTTP OPTIONS Request that our Oauth Library rejected. 
Thread can be closed. 
Thanks
