### ISSUE TITLE
Body parameter doesn't allow empty string value in the UI, cannot type

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#3966]
When trying to type in the body parameter, of the Try it out form.
I cannot remove all the contents, instead an empty pair of curlies `{}` always pops up.
Then I tried to type out `swagger:<space>` in the textarea and as soon as I type the `<space>` it exists the textarea.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.5.0
| How did you install Swagger-UI? | editor.swagger.io
| Which browser & version?        | Chrome 64
| Which operating system?         | Linux Mint 18.1

### Demonstration API definition

```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: title
  description: description
  termsOfService: terms
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
    
host: httpbin.org
schemes: [http]
paths:
  /post:
    post:
      summary: "Try to type swagger: 2.0 inside the body"
      description: "Try to type swagger: 2.0 inside the body"
      parameters: 
      - in: body
        name: body
        schema:
          type: string
        required: true
        
      responses:
        200:
          description: ok
    
```

### Configuration (browser query string, constructor, config.yaml)

`?yourQueryStringConfig=here`

### Expected Behavior

I can clear the contents of the body-parameter text area and type: `swagger:<space>`
### Current Behavior

The textarea cannot be cleared entirely, and after typing `swagger:<space>` the textarea is converted to some other widget ( a non-editable one ).

#### After trying to "clear" the contents of the textarea
![image](https://user-images.githubusercontent.com/8438485/33424281-07334f70-d5c4-11e7-9f66-cc7946a430c4.png)

#### After having _just_ typed out `swagger:<space>`
![image](https://user-images.githubusercontent.com/8438485/33424296-13f7be12-d5c4-11e7-95de-fe67613bdfbd.png)

**Comment by hkosova** [comment]
@ponelat this looks similar to #3809 (duplicate?)

**Comment by ponelat** [comment]
Yeah pretty much... 
Closing in favour of #3809
