### ISSUE TITLE
TypeError: Failed to fetch with CORS enabled 

### ISSUE THREAD

**Issue by tsira** [swagger-api/swagger-ui#3969]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   Bug
| Which Swagger/OpenAPI version?  3.0
| Which Swagger-UI version?       | 3.5.0
| How did you install Swagger-UI? | npm
| Which browser & version?        | Chrome 62.0.3202.94
| Which operating system?         |  OSX 10.12.6

Gone through the CORS enablement and confirmed it is working on my endpoint. I get a valid return response however the UI is displaying TypeError: Failed to fetch.

$curl-verbose --request OPTIONS "###" --header 'Access-Control-Request-Method: GET'

* TCP_NODELAY set
* Connected to "###" (10.191.128.160) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: "###"
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> OPTIONS "###" HTTP/1.1
> Host: "###"
> User-Agent: curl/7.54.0
> Accept: */*
> Access-Control-Request-Method: GET
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Cookie,Host,X-Forwarded-For,Accept-Charset,If-Modified-Since,Accept-Language,X-Forwarded-Port,Connection,X-Forwarded-Proto,User-Agent,Referer,Accept-Encoding,X-Requested-With,Authorization,Accept,Content-Type
< Access-Control-Allow-Methods: GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH
< Access-Control-Allow-Origin: *
< Access-Control-Max-Age: 1800
< Content-Type: application/json;charset=utf-8
< Date: Thu, 30 Nov 2017 21:34:33 GMT
< Server: Jetty(9.4.z-SNAPSHOT)
< Content-Length: 0
< Connection: keep-alive

**Comment by shockey** [comment]
@tsira, there's not much to go on here. Can you provide a definition that reproduces the problem?

**Comment by tsira** [comment]
Here's my .yaml and a screenshot of what I'm seeing in browser with Swagger UI. Initially I saw that CORS not being enabled was the problem, but now that it is enabled on my endpoints I'm unsure what is causing the error.

![swaggererror1](https://user-images.githubusercontent.com/221682/33508585-0e9dc294-d6b0-11e7-824c-bcad35b19bde.jpg)

```

openapi: 3.0.0
servers:
  - url: 'https://virtserver.swaggerhub.com/RC/remoteSettings/1.0.0'
info:
  description: Remote Settings API
  version: "0.0.2"
  title: Remote Settings API
tags:
  - name: Remote Config
    description: Remote Settings Parent Encapsulation Object
  - name: Remote Settings
    description: Remote Configuration Properties for a Project
  - name: Revisions
    description: Remote Settings Revision History Calls
  - name: Preferences
    description: update Prefs
paths:
  '/projects/{appId}/settings':
    get:
      tags:
        - Remote Config
      summary: Returns a list of existing application settings and their ids.
      operationId: getRemoteConfig
      description: >-
        By passing in a project ID the call will return the currently loaded set
        of Remote Config in the system
      parameters:
        - in: path
          name: appId
          description: pass the AppID for searching the Remote Settings
          required: true
          schema:
            type: string
      responses:
        '201':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getRemoteConfig'
    post:
      tags:
        - Remote Config
      summary: Create a new remote settings configuration with the provided payload. Returns location of new configuration. The name must be either Development or Release.
      operationId: postRemoteConfig
      description: >-
        By passing in a project ID the call will return the currently loaded set
        of Remote Config in the system
      parameters:
        - in: path
          name: appId
          description: pass the AppID for searching the Remote Settings
          required: true
          schema:
            type: string
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getRemoteConfig'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: the url of the request
                    example: /projects/6130759063535538121/settings/Development/
        '409':
          description: "Duplicate settings name"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
                example: "Duplicate settings name"

components:
  schemas:
    remoteConfigBase:
      type: object
      properties:
        appId:
          type: string
          example: "1b1b1c62-d921-41e9-9414-e89c053d1c0c1"
        name:
          type: string
          enum: [Development, Release]
          example: "Development"
        description:
          type: string
          example: "Test get Development Config"
        createdAt:
          type: string
          format: ISO8601ABNF
          example: '2017-08-11T23:15:14Z'
        updatedAt:
          type: string
          format: ISO8601ABNF
          example: '2017-08-11T23:15:14Z'
        contentHash:
          type: string
          format: SHA256
          example: "a53b2b012693a2e9975c7c0488ac9dd4dea536d1"
    getRemoteConfig:
      type: object
      properties:
        Release:
          $ref: '#/components/schemas/remoteConfigBase'
        Development:
          $ref: '#/components/schemas/remoteConfigBase'
    segments:
      description: "The value that is applied for the key for a selected segment of the population of users {segmentKey: segmentValue}"
      type: object
      properties:
        keyvalpair:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              value:
                type: integer
          example: "{ {374: true}, {376: false} }"
    remoteSettingsBase:
      type: object
      properties:
        key:
          type: string
          example: "aRemoteSettingsBool"
        value:
          type: string
          example: "true"
          description: "The Default value for this setting"
        type:
          type: string
          enum: [bool, float, integer, string]
          example: bool
        segments:
          $ref: '#/components/schemas/segments'
    getRemoteSettings:
      type: object
      properties:
        name:
          type: string
          enum: [Development, Release]
          example: "Development"
        description:
          type: string
          example: "These remote settings have a few changes we want to test"
        segmentPriority:
          type: array
          items:
            type: integer
          example: "[374, 376, 375]"
        remoteSettings:
          $ref: '#/components/schemas/remoteSettingsBase'
    putRemoteSettings:
      type: object
      properties:
        notes:
          type: string
        expectedVersion:
          type: string
          description: hash of contents
        segmentPriority:
          type: array
          items:
            type: integer
          example: "[374, 376, 375]"
        remoteSettings:
          $ref: '#/components/schemas/remoteSettingsBase'
    BasicErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600


```

**Comment by shockey** [comment]
Strange.... is there anything in the console tab?

**Comment by tsira** [comment]
Yes! Don't know why I didn't see this yesterday: 

Failed to load https://'##'/projects/0/settings: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

So I need to get the server to reflect the request Header Origin 'http://localhost:8081' as the response value for Access-Control-Allow-Origin?

**Comment by tsira** [comment]
Or is it possible to change the curl that Swagger UI sends to add the no-cors header?

**Comment by shockey** [comment]
@tsira, you're on the right track, but I'd suggest setting `Access-Control-Allow-Origin: *` so you don't have to keep up with which origins you're whitelisting.

Also, note that the `/projects/0/settings` request came back _without_ any CORS headers set:

<img width="620" alt="messages image 2852604063" src="https://user-images.githubusercontent.com/680248/33509523-4a1a97f0-d6b7-11e7-96e0-503ac04535c7.png">

---

I'd suggest using something third-party to deal with CORS - it's kind of a pain to do yourself. http://enable-cors.org/ is a great place to start, and here's some instructions for Jetty specifically (which I noticed in your `Server` header above: https://stackoverflow.com/a/16043524

**Comment by shockey** [comment]
Just read through this again, and something stuck out to me that you may not know about CORS.

There's two CORS mechanisms: inline `Access-Control` headers and `OPTIONS` requests. The former is used for "simple requests", and the latter for "preflight requests" (preflight referring to the OPTIONS call that goes out before the request in question is allowed to fire).

This GET request in question appears to be a simple request, so there's no preflight OPTIONS request for it - the browser will just expect the CORS directives to be present in the response headers for the GET request.

Here's some reading about that: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Examples_of_access_control_scenarios

Effectively, this means you'll need to do more than just handle OPTIONS requests in your server - hence my suggestion to use a library 😄

**Comment by tsira** [comment]
Got it working, just needed to alter some stuff in the Ruby Config 👍  Thanks!

**Comment by shockey** [comment]
Awesome! Glad you got it to work.

Closing.
