### ISSUE TITLE
Using Swagger UI with Create React App

### ISSUE THREAD

**Issue by SMarple** [swagger-api/swagger-ui#3970]
Bug or feature request?         Bug  
Which Swagger/OpenAPI version?  2.0
Which Swagger-UI version?       Latest
How did you install Swagger-UI? npm 

When using create-react-app to create a new application, I tried adding the swagger-ui to the application. When doing this, I get an error because create-react-app uses react 16 and the method for proptype checking changed between react 15 and react 16. By simply using React 15, the swagger UI works fine as expected. Can swagger UI work with react 16? If so, is it a create react app issue that is forcing me to downgrade to react 15?

I used this to see a working example of swagger UI in create-react-app. Just generate using the latest create react app and add the swagger UI same as in this repo: https://github.com/shockey/swagger-ui-cra

**Comment by shockey** [comment]
Hey @SMarple - yeah, this is on our end. Officially we're a React 15 library/application, but we do our best to support React 16. Looks like there's a codemod script for fixing this: https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types

I'm going to try that out now, maybe this will be a quick fix that we can ship tonight :smile:

**Comment by shockey** [comment]
Update: looks like everything is working with React 16. I was thinking of **swagger-api/swagger-editor#1580 Use prop-types dependency for React-16 support** when responding to this.

I used `create-react-app` to set up a new application with the following dependencies:

```json
  {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.0.17",
    "swagger-ui": "^3.5.0"
  }
```

Then I modified `App.jsx` to the following:

```jsx
import React, { Component } from 'react';
import SwaggerUI from "swagger-ui";
import logo from './logo.svg';
import './App.css';

class App extends Component {
  componentDidMount() {
    SwaggerUI({
      dom_id: "#ui",
      url: "http://petstore.swagger.io/v2/swagger.json"
    })
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <div id="ui" />
      </div>
    );
  }
}

export default App;

```

I got this:

<img src='https://shipusercontent.com/86dda8524b6a5f238c056a67368fd1ff/Pasted%20Image%201.png' title='Pasted Image 1.png' width=1792>

--- 

@SMarple, I think the problem is in your application. Are you sure that you're using the latest version of Swagger-UI?

**Comment by SMarple** [comment]
I'll have to investigate this more closely. I confirmed your example works as expected for me with various recent version of the swagger-ui. I'll have to see what might have been causing a conflict and the error I was receiving. Thanks for your help and quick response!

**Comment by shockey** [comment]
@SMarple cool, good luck. don’t be afraid to bump this thread if you can’t get it worked out 😄

**Comment by SMarple** [comment]
Just in case anyone runs into the same problem: Using "swagger-ui": "3.4.4" causes an error: "TypeError: Cannot read property 'oneOfType' of undefined". However, using swagger-ui 3.4.0 or 3.5.0 works fine :) Must've been fixed before I could even report the error with the release of 3.5.0!

Including code snippets just in case someone wants to replicate the problem:

```
  "dependencies": {
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.0.17",
    "swagger-ui": "3.4.4"
  },
```

```
import PropTypes from 'prop-types';
import React, { Component } from 'react';
import SwaggerUI from "swagger-ui";
import logo from './logo.svg';
import './App.css';

class App extends Component {
  componentDidMount() {
    SwaggerUI({
      dom_id: "#ui",
      url: "http://petstore.swagger.io/v2/swagger.json"
    })
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <div id="ui" />
      </div>
    );
  }
  
}

App.propTypes = {
	optionalArray: PropTypes.array
}

export default App;
```
