### ISSUE TITLE
swagger-ui-bundle.js and swagger-ui-standalone-preset.js not shipped with swagger-ui

### ISSUE THREAD

**Issue by ClementVidal** [swagger-api/swagger-ui#3978]
I want to create a simple html page that use `SwaggerUIBundle` js class to setup the swagger ui interface, as demonstrated in [this exemple](https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html).

I'm using webpack to package my project and all it's dependencies.

When installing `swagger-ui` from npm, these two files are not installed (they seams to be excluded from the npm package through the `.npmignore` file) :

- swagger-ui-bundle.js
- swagger-ui-standalone-preset.js

Without these files i'm not able to reproduce the provided exemple.

The only solution i found was to import `SwaggerUIBundle` and `SwaggerUIStandalonePreset` from the `swagger-ui-dist` package instead of the `swagger-ui`.

I found the doc a bit unclear about which package to use:

> swagger-ui is a traditional npm module intended for use in JavaScript web application projects that are capable of resolving dependencies (via Webpack, Browserify, etc).

This sentence sounds like i should use `swagger-ui` and not `swagger-ui-dist` in my situation.

I guess i'm not doing things the right way.

Which package should be effectivly installed ?

Thanks you

**Comment by travispamaral** [comment]
I agree this is something I've ran into. I've been unable to track down exactly why the 2 files are not being included. Any help would be greatly appreciated! 😄

**Comment by brylie** [comment]
Is there a workaround? I am stuck with this issue as well.

**Comment by travispamaral** [comment]
Hey @brylie how are you implementing this? I got around the issue by editing the .npmignore file. I am installing just the dist directory via an npm install ssh+git from my repo. The file looks like below.
```
*
*/
!README.md
!package.json
!dist/swagger-ui.js
!dist/swagger-ui.js.map
!dist/swagger-ui.css
!dist/swagger-ui.css.map
!dist/swagger-ui-bundle.js
!dist/swagger-ui-bundle.js.map
!dist/swagger-ui-standalone-preset.js
!dist/swagger-ui-standalone-preset.js.map
!dist/oauth2-redirect.html
```

**Comment by brylie** [comment]
I just ended up installing the `swagger-ui-dist` package, as it was easiest to get working.

**Comment by shockey** [comment]
Hmm - yeah, I don't see any reason to not put the Standalone plugin into `swagger-ui`.

It was originally excluded based on the thought that most consumers would be embedding Swagger-UI into larger applications, and would have no use for the Topbar.

I'll circle back on this before the end of the week, but if any of you want to beat me to a PR that would be fine :wink: 

Also, an FYI! If you're using a module bundler, your app bundle will be significantly smaller if you use `swagger-ui` instead of `swagger-ui-dist`.
