### ISSUE TITLE
How to bypass Available authorizations dialog in Swagger UI?

### ISSUE THREAD

**Issue by patnolan** [swagger-api/swagger-ui#3984]
Swagger UI has a swagger-oauth.js which displays an "Available authorizations" dialog for selecting the scope(s). The available scopes are defined in code via AddSecurityDefinition.

However, I would like to bypass this dialog and have the scopes automatically selected. Could anyone advise how to do this or even provide the necessary code\config?

Thanks heaps!

**Comment by shockey** [comment]
Hi @patnolan, we no longer offer support for Swagger-UI 2.0.

I'll keep this open, in case someone comes along with an answer for you!
