### ISSUE TITLE
BUG on swagger UI (Response code 0, response header: error - no content) if given type of return value not defined for the given type of http result code

### ISSUE THREAD

**Issue by hidegh** [swagger-api/swagger-ui#3986]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 
**Shwashbuckle.AspNetCore (1.0.0)**

### Demonstration API definition

		[HttpPost]
		**[ProducesResponseType((int)HttpStatusCode.OK)]** // NO CONTENT TYPE
		[ProducesResponseType(typeof(ApiResult), (int)HttpStatusCode.Unauthorized)]
		[ProducesResponseType(typeof(ApiResult), (int)HttpStatusCode.NotFound)]
		[ProducesResponseType(typeof(ApiResult), (int)HttpStatusCode.Conflict)]
		public IActionResult Activate(Guid key, [FromBody]PacketRef packetRef)
		{
			return Ok("SUCCESS");
		}

The code above will lead to the result below, despite a HTTP OK and a string content.
![image](https://user-images.githubusercontent.com/6331063/33613409-d92113fa-d9d4-11e7-80e2-5910ef28918f.png)

Once a **[ProducesResponseType(typeof(string), (int)HttpStatusCode.OK)]** attribute is added, everything works as expected

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior

**Even if the result type is not defined for a given result code, SWAGGER UI should not alter return values.**

### Current Behavior

See it described @ Demonstration API definition.

### Possible Solution

FIX.

### Context

Thought it was an error in the code, but when I tried POSTMAN, API responded as expected and it was clear SWAGGER UI had an issue.

**Comment by webron** [comment]
That's an old version of swagger-ui that we no longer maintain. Try using the latest version.
