### ISSUE TITLE
token sent on callbackUrl but not stored in local storage

### ISSUE THREAD

**Issue by nmarasoiu** [swagger-api/swagger-ui#3993]
Hi,
I can see the accessToken being generated by the authorization server (sent on the redirect/callback uri). However I cannot see it in the browser storage locations (where I saw tokens for other UIs). And it is not sent to endpoints (which is probably an effect).
Please help me investigate this,
Thank you,
Nicu M

**Comment by shockey** [comment]
Hi @nmarasoiu, in Swagger-UI 3 local storage is not used for token storage - the values are kept in memory.

**Comment by nmarasoiu** [comment]
Thank you, but then, I am not sure what is missing, no Authorization header is being sent on requests by swagger ui: 
 with the latest releases (Swagger 1.5.17, Swagger UI 3.6.0 and swagger-akka-http 0.11.2 in my case we use this integration with AkkaHTTP),
And configuring the swagger something like:
@SwaggerDefinition(...
  securityDefinition = new SecurityDefinition(oAuth2Definitions =
    Array(new OAuth2Definition(
      key = "implicitFlow",
      flow = Flow.IMPLICIT,
      authorizationUrl = "..",
      tokenUrl = ".."))),
it works.
However, now, even if the controller methods are annotated with 

@ApiOperation(
  value = "..,
  nickname = "..",
  httpMethod = "GET",..
  authorizations = Array(new Authorization(value="apiAuth", scopes = Array())))

The token is not sent as header (but i did see the accessToken being generated by the autz server and sent back to callback url).

Please help,
Thank you,
nicu

**Comment by shockey** [comment]
@nmarasoiu, can you provide your `swagger.json`? That would be easier to look at :smile:

**Comment by nmarasoiu** [comment]
[swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/1538407/swagger.json.txt)

**Comment by nmarasoiu** [comment]
solved, needed to ask scopes openid profile .

**Comment by Razzeee** [comment]
Have the same problem. The old swagger ui showed the Bearer in the curl window. Doesn't do it with v3 so I'm thinking it doesn't send it. I already added scopes `openid`, `profile` and `email`. The UI even says that it's logged in and that I also can logout.

**Comment by shockey** [comment]
Hi @Razzeee, feel free to open a new support ticket detailing the issue you're having!

**Comment by Razzeee** [comment]
Thanks @shockey but I was able to solved it. As it turns out swashbuckle for aspdotnet had no documentation about security requirements in the docker file.
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements
