### ISSUE TITLE
Arrow not visible

### ISSUE THREAD

**Issue by SylvainAssemat** [swagger-api/swagger-ui#3995]
Hi

I embed the UI looks on my web site

Looks perfect

Just the collapsible arrow, is not **visible** ?!
![sans titre](https://user-images.githubusercontent.com/5692760/33662023-9e14c098-da8a-11e7-972d-fb0a9e9ce808.png)

I dont know why... maybe do you have heard about the same problem ?

Thanks for your help

**Comment by webron** [comment]
We really need more information than that. Which version of swagger-ui do you use? How did you embed it?

**Comment by shockey** [comment]
I think this is #3578 (cc @Minasokoni)

**Comment by SylvainAssemat** [comment]
Thanks shockey

You find out !

God bless you :-)
