### ISSUE TITLE
Help authenticating API calls via Swagger generated C# rest client. 

### ISSUE THREAD

**Issue by moulton01** [swagger-api/swagger-ui#4002]
First off, sorry if this is the wrong place to be posting this sort of query. 

So I have a number of API controllers in a main project. I used (websiteUrl)/Swagger/docs/v1, to get the .json description of the API and then used the swagger online editor tools to generate a C# Rest client for me. 

I then added a simple console application to that project it generated, to try create some sample calls to the generated services. Pretty much following this guide : http://visualbean.io/blog/how-to-use-the-autogenerated-swagger-client/

I first called the auth token api as below with the correct username and password which returns me a token and token type of bearer as below: 

var authApi = new ApiAuthTokenApi();
var auth = authApi.ApiAuthToken("password", userName, password);

This is fine. I then create a new Configuration class and set the API key and API key prefix as suggested in the above guide. Then pass the configuration file to the constructor of my api class files, as below: 

var currencyApi = new ApiCurrencyApi(config);

But whenever I make a call like (var currency = currencyApi.ApiCurrencyFind(1);). I get an unauthorized apiexception. 

Any idea on why this isn't working as I'm expecting it to?

**Comment by shockey** [comment]
Hi @moulton01, sorry you're having problems!

Questions about the generated clients and servers should be raised over at https://github.com/swagger-api/swagger-codegen 😄 

In the meantime, make sure the Swagger/OpenAPI document you're generating from defines and uses a security scheme. Here's how to do that in OpenAPI 3.0: https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by shockey** [comment]
If you have more questions about the security scheme topic, feel free to reply here, as that is not specifically related to the codegen!
