### ISSUE TITLE
swagger-ui 3.6.0 does not override oauth2RedirectUrl from config?

### ISSUE THREAD

**Issue by nmarasoiu** [swagger-api/swagger-ui#4008]
Hi,
In my experience with swagger-ui 3.6.0, 
The oauth2RedirectUrl passed to SwaggerUIBundle.initOAuth in 3.6.0 does not override the oauth2RedirectUrl from swagger-ui.js.
It should, right? Do you have this override working?
Thank you,
Nicu M

**Comment by nmarasoiu** [comment]
I have this in index.html of swagger:

  ui.initOAuth({
    clientId: "MOVIEUI",
    appName: "Swagger UI",
    scopeSeparator: " ",
    oauth2RedirectUrl: window.location.origin + "/cache/swagger/oauth2-redirect.html",
    additionalQueryStringParams: {realm_id: "IDAM_REAL"}
  });
It is taken into account, e.g. I can see the realm_id being sent. However, the oauth2RedirectUrl does no override the oauth2RedirectUrl values in the swagger-ui-bundle.js and other js files.

**Comment by shockey** [comment]
Hi @nmarasoiu!

`oauth2RedirectUrl` can't be provided as part of the `initOAuth` call, as it's a top level configuration item.

Per the [configuration documentation](https://github.com/shockey/swagger-ui/blob/master/docs/usage/configuration.md#how-to-configure), configuration items can be provided in a remote YAML document, constructor configuration object, or the URL query string - so you should be _only_ setting it when you call Swagger-UI.

There is an undocumented/unofficial way to dynamically change the value if you need to, though. Let me know if that's the case!

**Comment by nmarasoiu** [comment]
Ok, in fact the place of the parameter is in the general parameters, not as part of initOAuth. Closing.

**Comment by teriyakigod2** [comment]
@shockey Hi! I'm still having this issue.

My SwaggerUI constructor:

`           const ui = SwaggerUi({
            dom_id: '#swaggerContainer',            
            url: this.props.url,
            spec: this.props.spec,
            presets: [presets.apis],
            oauth2RedirectUrl: `${config.backapi}/oauth/token`,
        });
`
but it doesn't seem to work. Autorize button action sends request as Request URL:http://localhost:3001/oauth/token.

I'm using it in React application as npm package.
Thanks for reply.

**Comment by shockey** [comment]
Hi @teriyakigod2, is this still a problem? My first guess would be that `config.backapi` isn't set, so the oauth2RedirectUrl is being set to `/oauth/token`.

**Comment by teriyakigod2** [comment]
@shockey Hi, thanks for your answer. ```config.backapi``` is set, i've just checked it, so, oauth2RedirectUrl  should be ```/api1/oauth/token```. Then nginx redirects it to my real url.

**Comment by teriyakigod2** [comment]
@shockey we can continue here [https://github.com/swagger-api/swagger-ui/issues/4047](issue).
