### ISSUE TITLE
Requiring schema field hides referenced components

### ISSUE THREAD

**Issue by emft** [swagger-api/swagger-ui#4009]
Here is a minimal example that reproduces my problem:
- Each `Thing` references an array of `SubThing`s
- When `thing_id` **is** a required property of the `Thing` model, the `SubThing` model **does not** render within the `Thing` model
- When `thing_id` **is not** a required property of the `Thing` model, the `SubThing` model **does** render within the `Thing` model
- But I believe the `SubThing` model should render within the `Thing` model regardless

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0.0
| Which Swagger-UI version?       | 3.6.0
| How did you install Swagger-UI? | Run index.html in browser
| Which browser & version?            | Firefox 57.0 and Edge 41.16299.15.0
| Which operating system?             | Windows 10

### Demonstration API definition

```yaml
openapi: 3.0.0
info:
  title: My API
  version: '1.0'
paths:
  /things:
    get:
      summary: List all the things.
      responses:
        '200':
          description: All the things.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Thing'
components:
  schemas:
    Thing:
      type: object
      required:        # Problem line #1 -- model renders when these two are commented out
        - thing_id     # Problem line #2
      properties:
        thing_id:
          type: string
          example: def456
        sub_things:
          type: array
          items:
            $ref: '#/components/schemas/SubThing'
    SubThing:
      required:
        - sub_thing_id
      properties:
        sub_thing_id:
          type: string
          example: abc123
          readOnly: true
```

### Expected Behavior
The `SubThing` model should render within the `Thing` model, like so:
![image](https://user-images.githubusercontent.com/34380013/33778327-09db554e-dbfd-11e7-97f1-b91f6fce86d2.png)

### Current Behavior
The `SubThing` model does not render within the `Thing` model, like so:
![image](https://user-images.githubusercontent.com/34380013/33778360-26d7ae18-dbfd-11e7-867c-f145b121a54c.png)

**Comment by webron** [comment]
Thanks for the report, but someone beat you to it. Closing in favor of #4000.
