### ISSUE TITLE
Cannot pass BASE_URL as env variable when starting swagger ui as a docker container

### ISSUE THREAD

**Issue by zanbel** [swagger-api/swagger-ui#4016]
My use case is to provide documentation for users how to spin up their own swagger UI container and explore the REST api using the `try my` functionality.
This requires the ability to specify the path to swagger.json and base URL both will be available on the host where the app is installed.
After trying what seems to be the most straightforward way to pass this environment variable using `-e BASE_URL` still see the default `localhost/api/v1` when opening the browser.

Step to reproduce:
1. Run the following command
`docker run -d -p 80:8080 -e BASE_URL=acme.com:1234/api/v1/ -e **API_URL=http://acme.com:1234/api/v1/api-docs/swagger.json** --name swagger-acme swaggerapi/swagger-ui`
2. Open browser and navigate to `localhost`
3. Notice that the base URL still appear as the default `localhost/api/v1` although the API_URL env does seem to work as expected.

![image](https://user-images.githubusercontent.com/2638857/33808571-a7d0d53a-ddf1-11e7-8258-c54d0821428f.png)

**Comment by webron** [comment]
Shalom @zanbel - in case you didn't notice, #3957 was merged a couple of weeks ago. Does this solve your issue? Are you using the latest docker image?

**Comment by zanbel** [comment]
@webron thanks for looking into this issue. Thought I did, was pulling the latest version from docker hub, `swaggerapi/swagger-ui:latest` with image id 5d24456529d5, that appears to be 2 weeks old.

When trying to follow instructions on #3957 and building the image locally got a 403 error when opening the browser (with CORS was enabled).

Just to be clear this env variable will support specifying the `host` as well as the `path`, right?

**Comment by zanbel** [comment]
Was able to look back at the issue and it seems that #3957 doesn't really fit the issue reported here. It allows to change the path but the host cannot be configured using this env variable.

**Comment by ldipotetjob** [comment]
Did you get any solution finally? I had the same issue with openapi: "3.0.0" and playFramework and my url base is set on an ENV var
