### ISSUE TITLE
swagger not showing multiple examples in request body

### ISSUE THREAD

**Issue by john1452** [swagger-api/swagger-ui#4017]
| Q                                           | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | SwaggerHub
| Which Swagger-UI version?       | SwaggerHub
| How did you install Swagger-UI? | no using the one from SwaggerHub
| Which browser & version?        | chrome latest 
| Which operating system?         | windows 10

### Demonstration API definition

As stated in documentation here https://swagger.io/docs/specification/adding-examples/
In OpenApi 3.0 swagger supports multiple examples in requestbody. However, on swagger hub this is not the case. I have replicated the example provided in the documentation. It appears that examples in the request body are not taken into consideration when rendering the UI

I have created an example api using the yaml code from the documentation above.
Please see: https://app.swaggerhub.com/apis/SoftInc/kkk/1.0.0

YAML
```yaml
paths:
  /users:
    post:
      summary: Adds a new user
      requestBody:
        content:
          application/json:     
            schema:             
              $ref: '#/components/schemas/User'  
            examples:    
              Jessica:  
                value:
                  id: 10
                  name: Jessica Smith
              Ron:      
                value:
                  id: 11
                  name: Ron Stewart
      responses:
        '200':
          description: OK
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
```
### Current Behavior
The code above includes two examples of the user Jessica and Ron
When the above request is rendered on the UI it's displayed as below.

```json
{
  "id": 0,
  "name": "string"
}
```
### Expected Behavior
Based on the open 3.0 documentation link provided. The expected results should be (multiple examples):

```json
{
  "id": 10,
  "name": "Jessica Smith"
},
{
  "id": 11,
  "name": "Ron Stewart"
}
```

### Context
I want to use multiple examples in a response array to show all the possible errors that can be returned from the end point.

**Comment by hkosova** [comment]
This is being tracked #3437.

**Comment by shockey** [comment]
Closing as duplicate. Thanks @john1452!
