### ISSUE TITLE
How to pass apikey through header so user can have try-it-out functionality.

### ISSUE THREAD

**Issue by north-krimsly-hp** [swagger-api/swagger-ui#4022]
Hello Swagger-ui devs,

We are using Swagger-ui version 3.6.1 with OpenAPI spec version 2 and version 3 JSON files.

We need to be able to use apikey authentication to pass 'apikey' and the value in the header or as a query parameter when making calls to an API presented through Swagger-ui. This way we can instantiate a Swagger-ui instance with the apikey already specified, and the user can have try-it-out functionality without having to manually click Provide Credentials and enter the apikey and value. But it does not appear there is a way to specify the apikey and value programmatically when instantiating a swagger ui object. Is there a way to accomplish this or will it be supported soon?

If there isn't a way to configure apikey authentication in code, then we will have to ask every one of our API teams to generate and document a "test key" for every one of their API's in their documentation and ask them to document for their users how to enter it using the Provide Credentials button. This would be a pretty large effort. It seems like this used to be supported in an earlier version of Swagger-ui so it would be hard to tell our users it doesn't work anymore.

Thanks for any suggestions or help.

**Comment by shockey** [comment]
See my response from #3953:

> We're planning to build out an interface for setting authorization values in the next week or so, see swagger-api/swagger-ui#2915 for details. 

That ticket is now overdue (last week was heavy), so you can expect first-class support for this _soon_. As mentioned above, there are workarounds available if you need this today!

**Comment by north-krimsly-hp** [comment]
Hi shockey, it seems like the requestInterceptor approach does work in my testing. We'll use this workaround for now but we look forward to first-class support soon for apikey authentication. Thanks for your efforts!

**Comment by shockey** [comment]
@north-krimsly-hp, great, glad it's working for you.

Closing! Feel free to reply if anything else comes up.

**Comment by shatestest** [comment]
@north-krimsly-hp  can you please help me please sending apiKey in query in swagger latest version? I am not getting the urls property.
