### ISSUE TITLE
file parameters -> no Curl/URL

### ISSUE THREAD

**Issue by neopaf** [swagger-api/swagger-ui#4023]
using latest version here:
http://petstore.swagger.io/#/pet/uploadFile

when posting, I see NO Curl command or URL.

### Expected Behavior
Curl command, that contains
```
-F parameter=@fileName http://url
```
and URL field separately.

### Current Behavior
No Curl/URL sections visible when using file upload.

### Possible Solution
multipart fields usually contain client file name, and that could be used to construct example Curl command.
without path, just name.
so strip path (both / and \ delimiters) from client file name, and just just file name without path in @fileName.

If you feel that bothering with file names is no good,
just put
```
-F parameter1=@parameter1 -F parameter2=@parameter2 http://url
```
it would also help a lot!

### Context
my tester adores Curl commands there, she just copy/pastes that into test scripts and is happy.
but recently we've added some file uploads, and noticed that there is no Curl nice hint for those :(

**Comment by heldersepu** [comment]
I do see the curl section and it shows:
> curl -X POST "http://petstore.swagger.io/v2/pet/1/uploadImage" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "additionalMetadata=sdfgsdf" -F "file=@test.json;type="

**Comment by neopaf** [comment]
hmm... incorrect report (maybe was not quite awake :(.
I do see curl and url.... but curl command contains no fields:
```
curl -X POST "http://petstore.swagger.io/v2/pet/1/uploadImage" -H "accept: application/json" -H "Content-Type: multipart/form-data"
```

I'm using Mac Safari, latest version.

**Comment by neopaf** [comment]
not even 
* petId
* additionalMetadata

but my dream is 
* file

**Comment by neopaf** [comment]
![2017-12-12 16 48 46](https://user-images.githubusercontent.com/4362564/33887887-6250064a-df5c-11e7-8e08-3a64ac2ae180.png)

**Comment by heldersepu** [comment]
I tested Chrome & Firefox on windows all good there.

**Comment by webron** [comment]
Yeah, seems to not be working well in Safari.

**Comment by hkosova** [comment]
@webron this looks like #3806.

**Comment by neopaf** [comment]
it is indeed. thanks, Helen.
dup :( [And I thought I've searched thoroughly :(

**Comment by shockey** [comment]
@neopaf no worries :smile: thank you for the report, every detail does help!

**Comment by neopaf** [comment]
news update:
next safari
https://developer.apple.com/safari/technology-preview/

will have it normal:
![2017-12-15 12 13 07](https://user-images.githubusercontent.com/4362564/34034945-7f3adfc8-e191-11e7-9ded-10b7d41fd1d9.png)

maybe we don't need to change much.
