### ISSUE TITLE
query params URI-encode is not working properly in swagger-ui 3.6.0

### ISSUE THREAD

**Issue by bungoume** [swagger-api/swagger-ui#4027]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.6.0 or 3.6.1
| How did you install Swagger-UI? | cdnjs
| Which browser & version?        | chrome62
| Which operating system?         | macOS 10.13

### Configuration (browser query string, constructor, config.yaml)

```json
"parameters": [{
  "description": "Japanese-string",
  "in": "query",
  "name": "query",
  "required": true,
  "schema": {
    "type": "string"
  }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior
![image](https://user-images.githubusercontent.com/507733/33924204-49d21bb4-e018-11e7-8e73-ca9841c69e8a.png)

`テスト` should be encoded to `%E3%83%86%E3%82%B9%E3%83%88`

swagger-ui 3.4.0 (OK)
```
Curl
  curl -X GET "http://localhost:8000/text-analysis/v1/parse?query=テスト" -H "accept: */*"
Request URL
  http://localhost:8000/text-analysis/v1/parse?query=%E3%83%86%E3%82%B9%E3%83%88
```

swagger-ui 3.5.0 (OK)
```
Curl
  curl -X GET "http://localhost:8000/text-analysis/v1/parse?query=%E3%83%86%E3%82%B9%E3%83%88" -H "accept: */*"
Request URL
  http://localhost:8000/text-analysis/v1/parse?query=%E3%83%86%E3%82%B9%E3%83%88
```

### Current Behavior
`テスト` -> `%30C6%30B9%30C8`

swagger-ui 3.6.0, 3.6.1, github-master (NG)

```
Curl
  curl -X GET "http://localhost:8000/text-analysis/v1/parse?query=%30C6%30B9%30C8" -H "accept: */*"
Request URL
  http://localhost:8000/text-analysis/v1/parse?query=%30C6%30B9%30C8
```

### Context
non-ascii query parameter does not work.

**Comment by shockey** [comment]
This is coming from a recent Swagger-Client change that uses `String.charCodeAt` to do percent encoding - looks like that strategy falls down for non-ASCII characters.

**Comment by mingderwang** [comment]
My example is "!" miss encoded in curl line, but correct in request URL, as following

curl:  is not correctly encode URL for " !== "  
explain:   The  "!" sign in parameter  is encoded to  \#33 instead of "!", it will fail to run in curl command line.

%20&\#33;%3D%3D%20

Request URL:  This  is correctly encode URL for " !== "
%20!%3D%3D%20
