### ISSUE TITLE
Unintentional Cascading Styles

### ISSUE THREAD

**Issue by Redoubts** [swagger-api/swagger-ui#4028]
I'm trying to put a swagger div in my page, but it's picking up some CSS from my Semantic UI theme in places. For example, the "1.0.0" and "OAS3" bits are picking up line-height attributes for `h2` elements and now look weird: 

![screen shot 2017-12-13 at 10 13 29 am](https://user-images.githubusercontent.com/2435101/33954873-88984ae6-dfee-11e7-9438-cbda0923a48a.png)

Can Swagger UI elements pickup only their own CSS?

**Comment by shockey** [comment]
Hi @Redoubts!

> Can Swagger UI elements pickup only their own CSS?

Elements don't really have a say in what styles they receive, so this is really a problem with your Semantic UI theme not being specific _enough_, and thus bleeding into Swagger-UI.

I'm not really sure how we could do this outside of [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM), which would shield Swagger-UI from being affected by _anything_ outside of itself, but Shadow DOM is currently in the draft stage and lacks full browser support. You could use it yourself, if you only care about supporting Chrome/Safari/Edge (no Firefox or IE).

Swagger-UI does wrap itself in a `div.swagger-ui` element. Unfortunately, there's no way to express "don't affect any element that has a parent with a class at any ancestry level" in CSS, so you can't just wrap your theme in a selector that negates the Swagger-UI container.

I think the best way forward here is:
- Make sure that you're loading your Swagger-UI CSS last, so it has the best shot at cascading over your other styles. It's namespaced under `.swagger-ui`, so this is safe for all your other styles.
- Write CSS that resets the behavior of your theme for Swagger-UI.

The reset code would look something like this:

```css
.swagger-ui {
  h1, h2, h3, h4, h5, h6 {
    line-height: 1em;
  }
}
```

Let me know if this helps!

**Comment by Redoubts** [comment]
Yeah, monkey-patching it like that is a good idea.
