### ISSUE TITLE
Issue in Accordion showing invalid keypath while the accordion is not able to collapse

### ISSUE THREAD

**Issue by harshpbatham** [swagger-api/swagger-ui#4031]
Thanks for A2A i am newbie in swagger i have an issue in opening and closing the accordion and it provide me an error in the devloper tool like this. **"Invalid keypath"**.
![imgpsh_fullsize](https://user-images.githubusercontent.com/11681113/33999672-1e0171a2-e111-11e7-93fb-0443e9edbc51.jpg)

**Comment by shockey** [comment]
Hi @harshpbatham, we'd be happy to look into this, but your report is missing a lot of important details.

I'm going to close this ticket - please open a new one, and follow the template that's provided.

Thanks!

**Comment by harshpbatham** [comment]
i can provide you the code which i have written in the controller can u make me identify where is the mistake or some tag is missing or something else.

![imgpsh_fullsize](https://user-images.githubusercontent.com/11681113/34031717-afd6a9d0-e198-11e7-85c0-9210d00d491f.jpg)
