### ISSUE TITLE
Rendering extensions issue - `x-go-name` property

### ISSUE THREAD

**Issue by pavlos163** [swagger-api/swagger-ui#4039]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Swagger 2
| Which Swagger-UI version?       | editor.swagger.io
| Which browser & version?        | Chrome 62.0.3202.94 (Official Build) (64-bit)
| Which operating system?         | MacOS Sierra 10.12.6

I am slightly confused as to what's the expected behaviour for rendering extensions.

In my swagger YAML file, I have several properties that contain `x-go-name` fields. These are not rendered in editor.swagger.io, which is what I expected and preferred. However, one specific one is rendered, which is not a big problem but quite annoying.

This is part of my YAML spec:

```
  ExampleResponse:
    type: object
    properties:
      aproperty:
        type: string
        x-go-name: AProperty
        example: 'examplestring'
      theproblematicproperty:
        type: array
        items:
          $ref: '#/definitions/ObjectInsideArray'
        x-go-name: TheProblematicProperty
    x-go-package: path/to/package
  ObjectInsideArray:
    type: object
    properties:
      name:
        type: string
        x-go-name: Name
        example: John
      surname:
        type: string
        x-go-name: Surname
        example: Smith
    x-go-package: path/to/package
```

![screen shot 2017-12-18 at 17 34 16](https://user-images.githubusercontent.com/9980011/34120657-57d5526c-e41e-11e7-9625-0c10ad8b4dd2.png)

It is an array of objects and that's the only thing I can think of that differentiates it from the rest of my properties.

**Comment by shockey** [comment]
Hmm, the ArrayModel component might not be filtering correctly. Looks like a bug!

**Comment by webron** [comment]
The rendering of the extensions seems to be fixed. As for showing or not showing the, swagger-ui has a configuration that allows you to toggle it.
