### ISSUE TITLE
Swagger-UI Password Flow and oauth2RedirectUrl problems

### ISSUE THREAD

**Issue by teriyakigod2** [swagger-api/swagger-ui#4047]
Hi! I try to add swagger-ui to my react app anf i've come across the following problem:

this is my Swagger-UI constructor:

```js
       const ui = SwaggerUi({
            dom_id: '#swaggerContainer',            
            url: this.props.url,
            spec: this.props.spec,
            presets: [presets.apis],
            oauth2RedirectUrl: `${config.backapi}/oauth/token`,
        });
```
The problem **one**: it seems that these rules doesn't overwrite oauth2RedirectUrl;
The problem **two**: when i hit autorize button it doesn't send client_id/secret params.

Does anyone know how to solve it?

Thanks for replies.

**Comment by webron** [comment]
Closing this one in favor of #3227 that would tackle the password flow from scratch.
