### ISSUE TITLE
Disabling try it out button in the swagger-ui dist version

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [swagger-api/swagger-ui#4053]
Hello,

I recently downloaded the distribution of swagger-ui (dist) and put it in our web server. Everything works fine and renders well. However we want to now disable the "try it out" button as the APIs refer to critical backends and we donät want developers or users to be able to post data. I have tried everything from a custom plugin, to specifying a specific http method but there seems to be no way to disabling the try it out method. Is this true? Is there a workaround to use or anything at all? 

This is how our index.html looks. Pretty default.

```
<script>
window.onload = function() {
  
  // Build a system
  const ui = SwaggerUIBundle({
     urls: [
    {url:"http://swagger.json",name:"MCH_Services"},
    {url:"http://document_services.json",name:"DocumentServices"},
	{url:"http://swagger.json", name:"Print_Labels"}
    ],
    dom_id: '#swagger-ui',
  deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}

```

Thanks

**Comment by SoucianceEqdamRashti** [comment]
By the way, I have tried to use:
`supportedSubmitMethods: []`
or`
supportedSubmitMethods: ['get']`

But neither works. In both cases the try it out button is available on all methods.

**Comment by SijmenHuizenga** [comment]
Take a look at issue #3725. I came across the same same issue today and i just found out the [fix](https://github.com/swagger-api/swagger-ui/issues/3725#issuecomment-334899276) proposed by @shockey also works for the swagger-ui-dist version.

**Comment by shockey** [comment]
@SijmenHuizenga is correct - my suggestion in #3725 should do the trick.

I'm going to close this, @SoucianceEqdamRashti just reply if you're still having problems and I'll reopen!
