### ISSUE TITLE
swagger-ui does not parse/display model description

### ISSUE THREAD

**Issue by shawnjohnson** [swagger-api/swagger-ui#406]
I noticed that it is possible to add a "description" to a custom data type model - https://github.com/wordnik/swagger-core/wiki/Datatypes : 
The property has an optional human-readable description.

Example:
```
"Pet": {
  "id": "Pet", 
 "description": "A pet is a person's best friend"
...
```

It doesn't appear that swagger-ui is able to display this description, which for me would be really useful!

Please let me know if you need any additional information.

Discussed in Group here:
https://groups.google.com/d/topic/swagger-swaggersocket/wUaMmyfHzys/discussion

**Comment by clepsydra** [comment]
Hi!
I see that this issue is closed, but when I use the current master it does not work: descriptions of models are not shown in Swagger UI. 
I see that there are other related items like 294 - which is also closed - which references to 1248. But that one does not list this issue.
Can you let me know whether this is supposed to be working?
Thanks!

**Comment by webron** [comment]
@clepsydra I'd suggest opening a new ticket if you think there's a bug.

**Comment by HolgerVogelsang** [comment]
I'ts not rocket science:
1. Open swagger-ui.js
2. Search for function processModel(schema, name)
3. Change the first lines of this function to something like this (or whatever you want to display):

```
  function processModel(schema, name) {
    var type = schema.type || 'object';
    var isArray = schema.type === 'array';
    
    var html = schema.description !== undefined ? '<div style=\'margin-left: 0px; font-size: 14px;\'>' + strongOpen + '// ' + schema.description + strongClose + '</div>' : '';
    html += (strongOpen + name + ' ' + (isArray ? '[' : '{') + strongClose);
```

**Comment by samavia** [comment]
The description is visible with defining summary parameter.
![summardetails](https://cloud.githubusercontent.com/assets/7899075/19344775/db06b0e0-913b-11e6-92b6-00a0aa1f4dec.PNG)
