### ISSUE TITLE
IE 11 "Promise" is undefined

### ISSUE THREAD

**Issue by RainbowSYL** [swagger-api/swagger-ui#4061]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

## **I use springfox and swaggerui in my project. But IE11 is not support 'promise' with swagerrui version V3.8.0. How can I solve this problem.**

**Comment by RainbowSYL** [comment]
The version of swagger is V3.8.0

**Comment by shockey** [comment]
Hi @RainbowSYL, as a workaround until this is fixed, you can add a Promise polypill to your page:

```js
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script> 
```

**Comment by RainbowSYL** [comment]
Thank you for your answer.

**Comment by shockey** [comment]
This fix will be released shortly.

Sorry for the inconvenience, @RainbowSYL!
