### ISSUE TITLE
Js Exception

### ISSUE THREAD

**Issue by gnanayakkara** [swagger-api/swagger-ui#4065]
When I access http://localhost:8080/myapp/swagger-ui.html# ,I got below window.
But  /v2/api-docs url works fine and return json content well.

![image](https://user-images.githubusercontent.com/34508294/34479652-03b3c6c6-efce-11e7-847f-6fd055110618.png)
![image](https://user-images.githubusercontent.com/34508294/34479657-0aaf3cda-efce-11e7-8fe5-b50f42ad56f8.png)

And im using 2.4.0 version

**Comment by shockey** [comment]
Hi @gnanayakkara! This looks like a Springfox issue, so you would open an issue there.
