### ISSUE TITLE
Array response bodies simply show 'Array[object]' in model, examples not shown

### ISSUE THREAD

**Issue by kierenj** [swagger-api/swagger-ui#4079]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Don't know - version detection link in issue template broken
| Which Swagger-UI version?       | How can I tell?
| How did you install Swagger-UI? | Via Swashbuckle.AspNetCore
| Which browser & version?        | Chrome 63
| Which operating system?         | Windows 10

### Demonstration API definition
https://gist.github.com/kierenj/5f2d42371abb379c1ebb476378da92f7

### Configuration (browser query string, constructor, config.yaml)
Sorry, I'm not sure how to find this w/Swashbuckle.  Happy to give more detail if needed.

### Expected Behavior
The 400 response to POST /categories (for example) to show a response model and examples.

### Current Behavior
Response Messages table shows:

````
400
One or more errors occurred (BadRequest)
Array[object]
````

### Possible Solution
Not sure

### Context
Trying to have responses which return JSON arrays and document that.  Is it possible?

**Comment by hkosova** [comment]
```
          "400": {
            "description": "One or more errors occurred (BadRequest)",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#\/definitions\/ErrorResult"
              }
            },
            "examples": "{\"$type\":\"RedRiver.Saffron.AspNetCore.ErrorResult[], RedRiver.Saffron.AspNetCore\",\"$values\":[{\"$type\":\"RedRiver.Saffron.AspNetCore.ErrorResult, RedRiver.Saffron.AspNetCore\",\"code\":1004,\"message\":\"Name must be unique\"}]}"
          }
```
The usage of the `examples` keyword is not valid. `examples` is a map of media types to examples, so each example must have the media type specified. Check out https://swagger.io/docs/specification/2-0/adding-examples/, section "Response Examples".

You might also want to use a JSON object/array literally rather than as a string in the example value (although both work in Swagger UI 3.9.0).
```
  "examples": {
    "application/json": {
      "$type": "RedRiver.Saffron.AspNetCore.ErrorResult[], RedRiver.Saffron.AspNetCore",
      "$values": [
        {
          "$type": "RedRiver.Saffron.AspNetCore.ErrorResult, RedRiver.Saffron.AspNetCore",
          "code": 1004,
          "message": "Name must be unique"
        }
      ]
    }
  }
```
Here's how the fixed example looks in Swagger UI 3.9.0:
![Response example in Swagger UI 3.9.0](https://user-images.githubusercontent.com/8576823/34745667-5094b818-f5a2-11e7-9a5e-ccfb132bef60.png)

Since your spec was generated by Swashbuckle, open an issue with them to address incorrect generation of response examples.

**Comment by kierenj** [comment]
Ok, let's ignore examples - the same problem happens if I use a string or null there.  What about the result schema issue?

**Comment by kierenj** [comment]
For example, https://gist.github.com/kierenj/f3c9de2a7dd4ce330096deda14137fce still shows `Array[object]` for "Response Model"

**Comment by hkosova** [comment]
@kierenj [Which version](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/version-detection.md) of Swagger UI do you use? Can you post a screenshot?

Your spec looks OK in the latest UI version (3.9.0):
http://petstore.swagger.io/?url=https://gist.githubusercontent.com/kierenj/f3c9de2a7dd4ce330096deda14137fce/raw/9302f2bbfbbaae840f1f15c3730b2cef67f463c3/demo2.json
![image](https://user-images.githubusercontent.com/8576823/34822094-cc3b026c-f6d6-11e7-9bb9-895b539879b3.png)

**Comment by kierenj** [comment]
Something less than 3.0.8 it looks like - no `versions` global.  I'll ask about updating on Swashbuckle repo!

**Comment by kierenj** [comment]
All good for me on an updated version (in preview on Swashbuckle).  New versions of Swagger UI look great!
