### ISSUE TITLE
How to add custom css in swagger ui using .Net

### ISSUE THREAD

**Issue by jitsingh89** [swagger-api/swagger-ui#4080]
Hi I'm using swagger ui in my web api project. It's very good but i am facing some ui issue in page.
this is the snapshot
![issue](https://user-images.githubusercontent.com/9546697/34667553-839769e0-f48f-11e7-811c-1cabcb06c617.PNG)

 How can I fix this issue by adding custom css. if i have to add custom css then where i have to add. is it in project file or in swagger ui project then i have to  update the project. I am also using swashbuckle to show response message.

Please suggest me.

**Comment by heldersepu** [comment]
That looks like the old version of the UI
@jitsingh89 Are you using swashbuckle ?

**Comment by heldersepu** [comment]
Looks like you already asked this in StackOverflow:
https://stackoverflow.com/questions/48148526/how-to-add-custom-css-in-swgger-ui-using-net
Please close this issue I will answer you there.

**Comment by jitsingh89** [comment]
Yes I am using swashbuckle . Thanks
Please answer there.

**Comment by segibambo** [comment]
> Hi I'm using swagger ui in my web api project. It's very good but i am facing some ui issue in page.
> this is the snapshot
> ![issue](https://user-images.githubusercontent.com/9546697/34667553-839769e0-f48f-11e7-811c-1cabcb06c617.PNG)
> 
>  How can I fix this issue by adding custom css. if i have to add custom css then where i have to add. is it in project file or in swagger ui project then i have to update the project. I am also using swashbuckle to show response message.
> 
> Please suggest me.


Here's was how i was able to solve mine using my own custom css
.swagger-ui .parameters-col_description input[type=text] {
        max-width: 340px;
        /*width:100%;*/
    }

    .swagger-ui .opblock-body pre .headerline
    {
        width:600px !important;
    }

    .swagger-ui textarea {
        width:600px !important;
    }
