### ISSUE TITLE
swagger nginx no centent

### ISSUE THREAD

**Issue by qq494679975** [swagger-api/swagger-ui#4081]
swagger 2.7.0

i use nginx agent server ，when i call on swagger it return

```
{
  "error": "no response from server"
}
```

the curl  is
`curl -X GET --header 'Accept: application/json;charset=UTF-8' 'http://127.0.0.1:7660/wlyy/doctor/admin-teams/count'
`
i find the ip 127.0.0.1 is error and how to change it

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

Please open a new issue, and follow the template. Thanks!
