### ISSUE TITLE
Change default port in the dist version

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [swagger-api/swagger-ui#4082]
Hello,

Is there a way to change the default port from 8080 to some other part in the dist? Or do you need to change the nginx.conf and generate a new dist? Basically the use case is that we want to have several dist of swagger-ui on a host listening on different ports.

Thanks
Souciance

**Comment by hkosova** [comment]
Have you considered using the `urls` parameter to load multiple specs in the same UI instance?
 https://stackoverflow.com/a/45161533/

**Comment by SoucianceEqdamRashti** [comment]
@hkosova , I don't want to change the url specs i.e. the url where the swagger files reside.

I want to change the swagger-ui server port which defaults to 8080. I would like this to be change to some other port. I can't see any parameter to send to change this. If there is one I'd be happy to test it. Thanks.

**Comment by shockey** [comment]
@SoucianceEqdamRashti, it would have been helpful if you had mentioned you're using the Docker image 😄 

Good news - we merged an improvement last week that allows you to change the port used within the container: https://github.com/swagger-api/swagger-ui/pull/4086

**Comment by SoucianceEqdamRashti** [comment]
@shockey , I am not using the docker image. I am using the dist release found here https://github.com/swagger-api/swagger-ui/tree/master/dist which can be run under a standard webserver. I found the answer via stackoverflow.

**Comment by shockey** [comment]
@SoucianceEqdamRashti ah, got it, sorry for the incorrect assumption.

Looks like you got your answer, but yes, that stuff is all up to the web server you're using.
