### ISSUE TITLE
Keeps redrawing an high CPU load when clicking on "Try it out" button

### ISSUE THREAD

**Issue by eLvErDe** [swagger-api/swagger-ui#4085]
Hello,

There's something wrong with swagger-ui 3.x. When clicking on the Try it out button, CPU load raises up to 60%. Clicking on Cancel reduce the load back to 0%.

This has been confirmed with latest 3.9 release on both Firefox and Chrome.

Please find attached a performance screenshot from firefox showing CSS keeps redrawing in an endless soon as soon as I click on Try it out. Stops when clicking on Cancel again.

![screenshot from 2018-01-09 15-02-24](https://user-images.githubusercontent.com/1586757/34724654-e4fec61e-f54e-11e7-8034-83e658da5fc0.png)

**Comment by heldersepu** [comment]
Can you add a link to your swagger.json?

**Comment by shockey** [comment]
This is probably the animation on the Execute button (related: https://github.com/swagger-api/swagger-ui/pull/3807)

**Comment by eLvErDe** [comment]
Looks it's related indeed, however the fix is supposed to be merged but I'm still seeing this on 3.9.0.

**Comment by shockey** [comment]
@eLvErDe right, #3807 added some new CSS rules to give GPU acceleration hints to browsers, but the animation is still there. My guess is that the animation will need to be completely removed if it's still causing problems :smile:

**Comment by eLvErDe** [comment]
Yeah I guess... One dedicated CPU core for the button animation sounds like a bad feature to me :D

**Comment by shockey** [comment]
@eLvErDe feel free to open a pull request that removes it 😄

**Comment by eLvErDe** [comment]
I don't do frontend ;)
