### ISSUE TITLE
Unable to request API schema with Authorization header passed

### ISSUE THREAD

**Issue by and3rson** [swagger-api/swagger-ui#4089]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Latest
| Which Swagger-UI version?       | Latest
| How did you install Swagger-UI? | unpkg.com
| Which browser & version?        | Chrome
| Which operating system?         |  ArchLinux rolling

### Description
I'm trying to request API schema from Django REST framework. It will return different schemas depending on the authorization that is passed to the schema endpoint.

### Expected Behavior
Hitting "Explore" should request API schema with provided credentials.

### Current Behavior
No way to request API schema with "Authorization" header.

Any ideas on how to perform this?

**Comment by pablocoberly** [comment]
Have you tried this? https://github.com/swagger-api/swagger-ui/issues/2793#issuecomment-335360204

**Comment by webron** [comment]
Closing as a workaround (linked) currently exists.
