### ISSUE TITLE
Multi-level grouping of Api Declarations

### ISSUE THREAD

**Issue by decoder318** [swagger-api/swagger-ui#409]
We have hundreds of controllers in our Web Api Project and it is going to increase a lot, and so organized the controllers in separate folders (based on the project module). The namespace of any controller is directly derived from its folder path.

It would be a lot helpful if we can group Api-Declarations, first by the Controller Namespace and then by the Controller Name, and hence can have multiple levels of collapsible groups, like in a tree-view explorer.

**Comment by clintonpatterson** [comment]
I know this issue has been closed, I'd just like to find out if this issue was ever addressed in the 2.0 spec? I can't find any references to it.

**Comment by fehguy** [comment]
Yes, tags are used for grouping in the 2.0 spec.

**Comment by clintonpatterson** [comment]
Could you perhaps direct me to an example using web api? I can't find any.
