### ISSUE TITLE
Allow access to parent dir level files without `../` or `/` at the start of $ref

### ISSUE THREAD

**Issue by riddhi89** [swagger-api/swagger-ui#4091]
Ask:
It would be nice if the $ref resolver is flexible enough to allow for resolution of files in the parent directory without requiring a `/` or a `../`.

For example:
```
├── fileA.yml
├── folderB
│   └── fileB.yml
```

In `fileB.yml` : `$ref: /fileA.yml#/items/id` & `$ref: ../fileA.yml#/items/id` both work to reference `fileA.yml` which is present in the parent directory.

However, in `fileB.yml` : just using `$ref: fileA.yml#/items/id` does not work. 

Are there any plans to support this? If yes, any ETA?

**Comment by heldersepu** [comment]
I assume there are NO plans to support this.
Sounds like a problematic idea, that is standard path navigation, we should not invent our own.

**Comment by shockey** [comment]
Hi @riddhi89, thanks for filing an issue!

Unfortunately, this is not something we plan to support.

The OpenAPI Specification defines `$ref` syntax with the [JSON Reference Specification](https://tools.ietf.org/id/draft-pbryan-zyp-json-ref-03.html), which in turn defers to [RFC 3986](https://tools.ietf.org/html/rfc3986) to specify URL syntax and resolution behavior.

RFC 3986's Section 5.4 (Reference Resolution Examples) clearly defines the behavior of a URL that consists only of a file name, with the example of `g`:

```
 Within a representation with a well defined base URI of

      http://a/b/c/d;p?q

   a relative reference is transformed to its target URI as follows:

  "g"             =  "http://a/b/c/g" 
```

So by introducing this behavior we'd be at odds with the OpenAPI Specification, which would certainly create pain for developers that use other tools in the OpenAPI ecosystem.

With that, I'm going to close this out - please feel free to reply if there are any other thoughts.
