### ISSUE TITLE
error : the prop 'onToggle' is required

### ISSUE THREAD

**Issue by makkaba** [swagger-api/swagger-ui#4093]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.9.0
| How did you install Swagger-UI? | npm
| Which browser & version?        | chrome
| Which operating system?         | mac

### Demonstration API definition
just simple test with react-create-app and official json(http://petstore.swagger.io/v2/swagger.json)

### Expected Behavior

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import SwaggerUI from 'swagger-ui';

class App extends Component {
    componentDidMount(){
        SwaggerUI({
          dom_id: '#swContainer',
          url:'http://petstore.swagger.io/v2/swagger.json'
      });
    }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <div id="swContainer"></div>
      </div>
    );
  }
}

export default App;
```

### Current Behavior

it looks like rendering successfully document page with a little flaw in css style. 
but, in chrome console, error message 
"Warning: Failed prop type: The prop `onToggle` is marked as required in `t`, but its value is `undefined`."

### Possible Solution

life cycle problem maybe.
if i did it in wrong way, please update sample code more detail in guide.

**Comment by shockey** [comment]
This can be safely ignored, looks like this is a stray required prop in our model rendering.

FYI, the warning will only show up when you're developing your app, PropType messages disappear in production!

**Comment by makkaba** [comment]
thank you for checking report!

**Comment by shockey** [comment]
No problem! I'm going to keep this open as a task for myself... Hoping to achieve two things:
- Fix the PropTypes warning
- Attempt to have component names preserved during minification (they're all minified to `t` at the moment, as you can see)

**Comment by shockey** [comment]
Update: preserving function names in Uglify adds 100K to the bundle, so that's not something we're going to be doing.

Still going to fix the PropTypes warning, though :smile:

**Comment by shockey** [comment]
Okay, starting with the next release you shouldn't see these warnings anymore. Thanks for the report, @makkaba!

**Comment by makkaba** [comment]
you are welcome, thank you!! :)

**Comment by jacobweber** [comment]
Does this apply to any such messages? I'm getting:
```
Warning: Failed prop type: The prop `source` is marked as required in `a`, but its value is `undefined`.
Warning: Failed prop type: The prop `schema` is marked as required in `t`, but its value is `undefined`.
```
Not sure what those are referring to, since everything's minified.

**Comment by shockey** [comment]
@jacobweber it does not apply to all such messages, any PropTypes mistakes on our part could trigger this.

Please open a new issue and we'll look into it. I'll also explore a solution that does silence all of these errors!

**Comment by makkaba** [comment]
i will create a new issue about `source` prop.
