### ISSUE TITLE
Import SwaggerUIStandalonePreset from swagger-ui

### ISSUE THREAD

**Issue by AntonDatsik** [swagger-api/swagger-ui#4097]
Hi!
I have a problem with importing SwaggerUIStandalonePreset from swagger-ui. I can't find this file in swagger-ui package. Now, I'm use swagger-ui-dist. But I use it in React application and swagger-ui will be better in this case.

**Comment by pablocoberly** [comment]
Check the dist folder.

**Comment by shockey** [comment]
@AntonDatsik, good news: this was just fixed today 😉 see https://github.com/swagger-api/swagger-ui/pull/4101 for more info

**Comment by AntonDatsik** [comment]
@pablocoberly 
swagger-ui package
http://joxi.ru/V2VgK8aU0RjQeA

**Comment by AntonDatsik** [comment]
Thank you. It is fixed in 3.9.1.
