### ISSUE TITLE
dot contained in operationId changed to "_" when rendered to the browser

### ISSUE THREAD

**Issue by justlees10** [swagger-api/swagger-ui#4109]
if my swagger api's operationId contains dot, it will be changed to "_" when operationId shows on the browser,so my operationId can not be shown correctlly.

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template. It sounds like you're having a valid issue, but we're going to need more information in order to take action.

Please open a new issue, and follow the template. Thanks!
