### ISSUE TITLE
In Angular 5 OpaqueToken is not working 

### ISSUE THREAD

**Issue by SudhakarRao** [swagger-api/swagger-ui#4112]
Hi,

We have recently upgraded to Angular 5 from Angular 4.x.x, 
we are using nswagger version 11.7 to generate the typescript client proxies.

Now the issues are in Angular 5 core package they have removed the OpaqueToken and they replaced this with injectiontoken but whenever nswagger generates the typescript proxies it generation with OpaqueToken .

can someone please tell us shall we replace this manually from OpaqueToken to injectiontoken everytime or 
is there any way we can change in this nswagger configuration or is this issue will be fixed in future version.???

Please see the code below.

`import { Observable } from 'rxjs/Observable';
import { Injectable, Inject, Optional, **OpaqueToken** } from '@angular/core';
import { Http, Headers, ResponseContentType, Response } from '@angular/http';
import { HydrogenAppConfigService } from '../host.config.service';

export const API_BASE_URL = new **OpaqueToken('API_BASE_URL');**`

**Comment by webron** [comment]
nswagger is not a library we maintain. please file a ticket at the right repo.
