### ISSUE TITLE
Failed to parse JSON/YAML response with multiple methods on the same path

### ISSUE THREAD

**Issue by xeagle2** [swagger-api/swagger-ui#4114]
The swagger-ui stopped parsing .json (since the version 2.2.x) if single path contains the multiple methods with the same name. Parsing works good in version 2.1.x

```
@Path("results/{key}")
@GET
@Produces({
  MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN
})
public AsyncResult getResult(@PathParam("key") String key) {
  return new AsyncResultImpl(key);
}
```

```
@Path("results/{key}")
@GET
@Produces({
  MediaType.APPLICATION_OCTET_STREAM
})
public StreamingOutput getResultBinary(@PathParam("key") String key) {
  return new AsyncResultImpl(key).getBinary();
}
```
Below is the snippet of generated json

```
"\/0/results/{key}" : {
      "get" : {
        "tags" : [ "..." ],
        "summary" : "Get a queued result.",
        "description" : "Get a queued result.",
        "operationId" : "getResult",
        "produces" : [ "application/xml", "application/json", "text/plain" ],
        "parameters" : [
          {
            "name" : "key",
            "in" : "path",
            "required" : true,
            "type" : "string",
            "description" : "the key"
          }
        ],
        "responses" : {
          "200" : {
            "schema" : {
              "$ref" : "#/definitions/json_AsyncResult"
            },
            "example" : {
              "key" : "...",
              "progressText" : "...",
              "releaseTime" : 12345,
              "completionTime" : 12345,
              "exception" : {
                "errorKey" : "...",
                "stackTrace" : "...",
                "statusCode" : 12345,
                "error" : "...",
                "message" : "..."
              },
              "operationResult" : {
                "displayInfo" : { },
                "data" : { },
                "dataType" : "..."
              },
              "progress" : 12345.0,
              "completed" : true,
              "startTime" : 12345
            },
            "description" : "the result"
          }
        }
      }
    ,
      "get" : {
        "tags" : [ "..." ],
        "summary" : "Get a queued result as binary.",
        "description" : "Get a queued result as binary.",
        "operationId" : "getResultBinary",
        "produces" : [ "application/octet-stream" ],
        "parameters" : [
          {
            "name" : "key",
            "in" : "path",
            "required" : true,
            "type" : "string",
            "description" : "the key"
          }
        ],
        "responses" : {
          "200" : {
            "description" : "the result"
          }
        }
      }
    }
```

The snippet doesn't violate the schema, but swagger-ui component fails to load it.

Thank you,

**Comment by shockey** [comment]
Hi @xeagle2!

The Swagger/OpenAPI specification doesn't address duplicate operations within the same path, but it's not a good idea to do this, for a few reasons:

1) there's no way for a server or client to know which of the two operations to use in order to validate a request or response, and the OpenAPI Specification offers no guidance to implementers on how to resolve such a situation, so you're likely to get inconsistent behavior with different tools

2) [Section 4 of the JSON Specification](https://tools.ietf.org/html/rfc7159#section-4) suggests that key names in a JSON object be unique:

> A name is a string.  A single colon comes after each name, separating the name from the value.  A single comma separates a value from a following name.  **The names within an object SHOULD be unique.**
> 
> An object whose names are all unique is interoperable in the sense that all software implementations receiving that object will agree on the name-value mappings.
> 
> When the names within an object are not unique, the behavior of software that receives such an object is unpredictable.  Many implementations report the last name/value pair only.  Other implementations report an error or fail to parse the object, and some implementations report all of the name/value pairs, including duplicates.

3) JavaScript (which Swagger-UI is written in), per ECMA 262, [does not support duplicate keys when deserializing JSON](http://www.ecma-international.org/ecma-262/6.0/#sec-internalizejsonproperty), as only the last value for the duplicated key will be kept:

> NOTE: In the case where there are duplicate name Strings within an object, lexically preceding values for the same key shall be overwritten.

---

I'm not sure why the 2.1.x series supported this (I wasn't personally involved in the development of the 2.x versions), but since this is nonstandard, I wouldn't expect to see this supported in the future.

**Comment by hkosova** [comment]
@xeagle2 OpenAPI does not allow duplicate HTTP methods within the same path. A path can only have one GET, one POST, etc., so your spec is not valid.

Different schemas per media type are supported in OpenAPI 3.0 though. That is, you can define a single operation that can return either `application/octet-stream` with schema `A`, or `application/json` with schema `B`, etc.

```yaml
openapi: 3.0.0
...

paths:
  /0/results/{key}:
    get:
      summary: Get a queued result, as XML/JSON or as binary
      operationId: getResult
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: the key
      responses:
        '200':
          description: the result
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                $ref: '#/components/schemas/json_AsyncResult'
              example:
                key: "..."
                progressText: "..."
                releaseTime: 12345
                completionTime: 12345
                exception:
                  errorKey: "..."
                  stackTrace: "..."
                  statusCode: 12345
                  error: "..."
                  message: "..."
                operationResult:
                  displayInfo: {}
                  data: {}
                  dataType: "..."
                progress: 12345
                completed: true
                startTime: 12345
            application/xml: { ... }
            text/plain: { ... }
```

**Comment by xeagle2** [comment]
Hi @shockey, thanks for the quick reply and I'm absolutely agree with you.  Based on JSON spec https://tools.ietf.org/html/rfc7159#section-4, and http://www.ecma-international.org/ecma-262/6.0/#sec-internalizejsonproperty the object names should be unique. 

Json schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json clearly shows that "path" is an object, etc.

From other side saying logically the operations can be potentially distinguished based on the media types produced and consumed as was mentioned also by @hkosova. For example in jsr339 describes it in a chapter "3.7 Matching Requests to Resource Methods" http://download.oracle.com/otn-pub/jcp/jaxrs-2_0_rev_A-mrel-eval-spec/jsr339-jaxrs-2.0-final-spec.pdf.

My question was born due to the fact that some of the projects failed to display swagger json after upgrade of swagger ui from 2.1.x to 2.2.x, and I wanted simply to clarify this.

I believe we will change the library which generates the swagger.json. This issue can be also closed.

Thanks gain for your help.

**Comment by webron** [comment]
Just one addition to that - since 2.0 (of the spec), YAML is a first-class representation of API definitions as well. What's allowed by the spec would need to be supported by both YAML and JSON - and YAML does _not_ allow duplicate keys.

From http://www.yaml.org/spec/1.2/spec.html#id2759572:

> JSON's RFC4627 requires that mappings keys merely “SHOULD” be unique, while YAML insists they “MUST” be.

**Comment by xeagle2** [comment]
That's good to know, thanks @webron
