### ISSUE TITLE
`Content-Disposition` does not take precedence when rendering responses

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#4115]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Any
| Which Swagger-UI version?       | 3.9.1
| How did you install Swagger-UI? | ---
| Which browser & version?        | Any
| Which operating system?         | Any

### Expected Behavior

Responses with a `Content-Disposition: attachment` header should render with an offer to download the file, instead of being subject to the usual rendering flow based on content type.

### Current Behavior

Responses with `Content-Type: application/json` are rendered as JSON even if `Content-Disposition: attachment` is set.

### Possible Solution

Give `Content-Disposition` precedence in response rendering.

### Context

https://github.com/swagger-api/swagger-ui/issues/4098.

**Comment by mikefidel** [comment]
Not only does the Content-Disposition response header appear to take precedence, it appears any trailing Content-Type response header is ignored.  This is only an observation.  But if it is the case, then error checking done by response-body.jsx necessary?

See the curl snapshot provided in Issue [#4098](https://github.com/swagger-api/swagger-ui/issues/4098).  Also the last and closing comment.
