### ISSUE TITLE
Nullable and Non-Nullable versions of a field

### ISSUE THREAD

**Issue by awalsh-broadsoft** [swagger-api/swagger-ui#4119]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Unsure
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.7
| How did you install Swagger-UI? | Tomcat
| Which browser & version?        | Chrome
| Which operating system?         | Windows 7 Pro

### Demonstration API definition
So previously we were using Json Schema and have recently begun migrating to Open API. There's a particular quirk of our implementation that I'm having trouble porting over.
So what we had sometimes for certain fields would be a non-nullable version of the field (the basic field) and a nullable version of the field. It looked somewhat like this:
```json
"definitions": {
  "DescriptionField": {
    "title": "Book Description",
    "type": "string",
    "maxLength": 10
  },
...
  "NullableDescriptionField": {
    "oneOf": [
      {
        "$ref": "#/definitions/DescriptionField"
      },
      {
        "type": "null"
      }
    ]
  }
}
```

We're hoping to port this over, but I think the syntax changes enough that we don't have the same functionality.

An implementation I've considered looks like this:
```json
"definitions": {
  "DescriptionField": {
    "title": "Book Description",
    "type": "string",
    "maxLength": 10
  },
...
  "NullableDescriptionField": {
    "allOf": [
      {
        "$ref": "#/definitions/DescriptionField"
      },
      {
        "nullable": true
      }
    ]
  }
}
```
However, I think there might be a problem with this implementation. I think that because "nullable" defaults to false, that a field couldn't possibly match both schemas, because this would essentially be saying that a matching schema is both nullable = true and nullable = false. Can anyone confirm whether I'm correct in thinking that the above example doesn't work?

Are there any recommendations for how to get nullable versions of fields within Open API 3.0.0?

**Comment by hkosova** [comment]
According to the comments [here](https://github.com/OAI/OpenAPI-Specification/issues/1368) and [here](https://github.com/swagger-api/swagger-ui/issues/3325#issuecomment-334139931), `nullable` needs to be outside of `allOf`:

```json
  "NullableDescriptionField": {
    "nullable": true,
    "allOf": [
      {
        "$ref": "#/definitions/DescriptionField"
      }
    ]
  }
```

**Comment by awalsh-broadsoft** [comment]
Thank you. I think that clears things up for me.

**Comment by webron** [comment]
Closing as @hkosova provided the solution.
