### ISSUE TITLE
relative link points to about:blank

### ISSUE THREAD

**Issue by jmattheis** [swagger-api/swagger-ui#4132]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |  2
| Which Swagger-UI version?       | 3.9.1
| How did you install Swagger-UI? |  Petstore example
| Which browser & version?        | Google Chrome 63.0.3239.132 
| Which operating system?         |  Linux & Windows

### Demonstration API definition
Petstore api

When using a relative path for the swagger definition the url which is shown in the description of the api points to `about:blank`. F.ex. using `v2/swagger.json` as url on http://petstore.swagger.io/

It all worked fine on version 3.1.7

![selection_020](https://user-images.githubusercontent.com/14895212/35097029-af0e7eda-fc4e-11e7-9fd6-104aa53ee909.jpg)

### Expected Behavior

The link to the swagger definition should be correct.

### Current Behavior

The relative link points to `about:blank`

### Context

I wanted to access the swagger definition.

**Comment by heldersepu** [comment]
Looks like a dup of: #4107

**Comment by jmattheis** [comment]
Jup its a dupe thanks!
