### ISSUE TITLE
Download link does not appear for files with openxmlformats content type

### ISSUE THREAD

**Issue by holthauj** [swagger-api/swagger-ui#4135]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.9.0
| How did you install Swagger-UI? | maven
| Which browser & version?        | Firefox 57.0.4 (64-bit)
| Which operating system?         | Windows 7

### Demonstration API definition

```yaml
{"swagger":"2.0","tags":[{"name":"FileController"}],"paths":{"/file":{"get":{"tags":["FileController"],"summary":"Download File","description":"","operationId":"doDownload","produces":["application/octet-stream"],"parameters":[{"name":"id","in":"query","description":"Unique ID for File ","required":true,"type":"string"}],"responses":{"200":{"description":"File returned","headers":{"Content-Disposition":{"type":"string","description":""}}}}}}}}
```

### Expected Behavior

I would expect the download link to appear when the content-type is one of the openxmlformats
application/vnd.openxmlformats-officedocument.wordprocessingml.document
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
### Current Behavior

content-type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
No download link. Garbage text appears on the page instead.
![image](https://user-images.githubusercontent.com/2595766/35112576-0f44dfca-fc44-11e7-9b4d-63f2bd394598.png)
![image](https://user-images.githubusercontent.com/2595766/35112617-35a876a4-fc44-11e7-98c0-92ea2e27bf4a.png)
content-type: application/octet-stream
Works correctly for the same file
![image](https://user-images.githubusercontent.com/2595766/35115555-3c0ac614-fc4e-11e7-87a0-e41998cd842e.png)

### Possible Solution

It looks like the body is getting treated as xml since the content-type contains xml
swagger-ui/src/core/components/response-body.jsx
} else if (/xml/i.test(contentType)) {
      body = formatXml(content, {
        textNodesOnSameLine: true,
        indentor: "  "
      })
      bodyEl = <HighlightCode value={ body } />
}

I tried changing the expression here to exclude openxmlformats. 
} else if (/xml/i.test(contentType) && !/openxmlformats/i.test(contentType)) {
...
}
This made it so that the download link appeared but the document ended up corrupted and could not be opened.

**Comment by shockey** [comment]
There's an open PR for this over at Swagger-Client: https://github.com/swagger-api/swagger-js/issues/1227

Also, I'm about to make a change that forces a download link when `Content-Disposition: attachment` is set, which will solve your specific use case!

**Comment by shockey** [comment]
The Content-Disposition fix will be released shortly.

@holthauj, if that doesn't solve your problems, feel free to bump this thread and I'll reopen.
