### ISSUE TITLE
Interfacing with Google's OAuth2 (openIdConnect)

### ISSUE THREAD

**Issue by mikefidel** [swagger-api/swagger-ui#4142]
Requesting support for clarifying what needs to be done to interface with Google's OAuth2 (i.e. openIdC onnect).  Documentation found in the Swagger-UI README.md's Documentation >> Usage >> [OAuth2 page](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md) appears to be at odds with the [Swagger.io docs page](https://swagger.io/docs/specification/authentication/openid-connect-discovery/). 

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Support
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.9.1
| How did you install Swagger-UI? | Copy of swagger-ui-dist folder, customized index.html hides header
| Which browser & version?        | Chrome (current) and Firefox (current)
| Which operating system?         | Windows 10

### Background Information

User's browser   <-->  AWS S3 Server running Swagger-UI   <-->  www.ndexbio.org (REST API)

Swagger-UI runs on an AWS S3 server, and passes Try-It-Out operations to a CORS enabled data producing server.  The target server's domain is www.ndexbio.org (and subdomains such as test.ndexbio.org, dev.ndexbio.org, etc).  A long list of API paths works well using with basic authentication as well as no authentication for some GET operations.

I'm now updating the OpenAPI document to facilitate authentication using Google's variant of OAuth2, of which [it's documentation](https://developers.google.com/identity/protocols/OpenIDConnect) states is based on OpenID Connect.  When finished, REST methods will work with 3 authentications: Basic, Google OAuth, and no authentication.  I already know how to define the OpenAPI Security: definitions for each path.

I find bits and pieces of documentation, but they are not clear and consistent.  For example...

### From a Swagger.io documentation: 
OpenAPI 3.0.0 SecuritySchemes when following  the [swagger.io docs](https://swagger.io/docs/specification/authentication/openid-connect-discovery/).  Documentation *suggests* this is all that is required for Swagger-UI to authenticate with www.ndexbio.org server.

```yaml
  securitySchemes:
    BASIC_AUTH:
      type: http
      scheme: basic
    GOOGLE_OAUTH2:
      type: openIdConnect
      openIdConnectUrl: https://www.ndexbio.org
```
### From the Swagger-UI README.md link to [OAuth configuration](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md): 
 
`We are told to make a call to the initOAth() method passing several parameters.  As I copy the dist folder and modifications made to index.html, I presume I would add the call there.`

### The maintainers of the www.ndexbio.org server provide [example code](https://github.com/ndexbio/ndex-tutorials/blob/master/single_sign_on/NDEx_Google_SignIn_example.html) showing how to interface with their server(s).  

```
The initialization code given to me seems way different than that shown in the Swagger-UI documentation.
```
I am looking for tips on how to reconcile the different sources of information given above.  The Swagger-UI team is not responsible for the ndexbio-provided documentation.  But I think (hope?) you'll agree the swagger.io and docs found on github are not in complete agreement.  At the end of the day, I wish to be able to move forward on my own -- even if on crutches with the help of your Support engineers. 

### Expected Behavior
n/a

### Current Behavior
n/a

### Possible Solution
n/a

### Context
OAuth is a new remote server API feature.  Not many users using it now, but the maintainers of the server say it will be the default log in protocol in another year.  Presently, basic authentication works (and works very well)!

I've written a thread on Stackoverflow on this.  Once I get this working satisfactory, I intend to give a full answer on how to do it.

**Comment by shockey** [comment]
I'll circle back here soon, but the short answer is that OIDC is currently not supported in our JavaScript tools (Swagger-Client, Swagger-UI, & Swagger-Editor).

**Comment by mikefidel** [comment]
Not a show-stopper.  As I wrote, basic authorization work well enough. And the Google OAuth2 feature has just been rolled out in the third-party application.

**Comment by shockey** [comment]
Hello again!

First, as I mentioned: the current state of things is that the OpenAPI Specification supports the describing of OpenID Connect authorization strategies, but the JavaScript tools have not implemented the logic necessary to follow the OIDC flow... so it would follow that the UI/Editor docs are a bit misleading with regards to OIDC.

(Side note: adding a warning for lack of support in the tools when users add a `type: openIdConnect` security scheme in Swagger-Editor is not the worst idea I've had today, cc @webron)

> As I copy the dist folder and modifications made to index.html, I presume I would add the call there.

Right, at the point that we support OIDC, you will likely use `initOAuth`. Just not today :smile: 

---

We're tracking OIDC support in https://github.com/swagger-api/swagger-ui/issues/3641 (which I still need to update, and will do today). I'm going to keep this open as a Feature ticket, in hopes that others that need this supported will chime in. Of course, if you need me to clarify anything, it's still your ticket, so feel free :smile:

**Comment by mikefidel** [comment]
Actions appear sound and appropriate.  Will close this ticket and monitor when/if action is taken on [#3641](https://github.com/swagger-api/swagger-ui/issues/3641) feature items.

Thanks again for all the help you have been in the recent past and now.
