### ISSUE TITLE
Could not resolve reference

### ISSUE THREAD

**Issue by lkebin** [swagger-api/swagger-ui#4152]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.9.2
| How did you install Swagger-UI? | Just run **dist** directory as document root
| Which browser & version?        | Safari/Chrome
| Which operating system?         | macOS

### Demonstration API definition

```yaml
responses:
    200:
        description: "successful operation"
        schema:
            $ref: "#/definitions/x/Pet"

....
definitions:
    x/Pet:
        type: "object"
        required:
            - "name"
            - "photoUrls"
```

### Configuration (browser query string, constructor, config.yaml)

```js
Default configuration from Swagger-UI repository
```

### Expected Behavior

The documents should be resolve normally

### Current Behavior

```
Errors:
Resolver error at paths./pet/{petId}.get.responses.200.schema.$ref
Could not resolve reference: #/definitions/x/Pet
```
But, the **Models** section display is normal.
![screen shot 2018-01-24 at 17 44 28](https://user-images.githubusercontent.com/1335935/35325296-42863138-012e-11e8-9d93-45783bbb2c49.png)

**Comment by hkosova** [comment]
In JSON references, if the `/` character is part of the node name, it needs to be escaped as `~1`:

```yaml
$ref: "#/definitions/x~1Pet"
```

https://swagger.io/docs/specification/using-ref/#escape
https://tools.ietf.org/html/rfc6901#section-3

**Comment by lkebin** [comment]
@hkosova Thanks!
