### ISSUE TITLE
Order properties not coherent

### ISSUE THREAD

**Issue by DGuidi** [swagger-api/swagger-ui#4154]
Using swagger-ui to load [my json definition](https://gist.github.com/DGuidi/6d951dbb2045c2ec9eb10c10e9609991), I see that properties order is _wrong_ when I show a model from a definition.   

Hope that some images can help explain my problem.
1. This is an example value for a route. Take a look at how properties are ordered: looks the same as _specs_ file...
![screenshot_1](https://user-images.githubusercontent.com/216627/35335473-01a54158-0116-11e8-9ae3-5215b93f8370.jpg)

1. For the same route, if I click __model__, properties are shown in a different order respect to properties in example value
![screenshot_2](https://user-images.githubusercontent.com/216627/35335506-16f75898-0116-11e8-873c-af6a463159d9.jpg)

1. Checked also __model__ section and properties are shown correctly, like in screenshot 1
![screenshot_3](https://user-images.githubusercontent.com/216627/35335558-377edc62-0116-11e8-887e-b61c1f988b9c.jpg)

I'm expecting that order properties is the same in all three screenshot posted above

| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | Tested with v3.9.2 and v2.2.10
| How did you install Swagger-UI? | zip from github and direct deploy
| Which browser & version?        | Chrome  63.0.3239.132 (Official Build) (64-bit)
| Which operating system?         |  Win10

**Comment by heldersepu** [comment]
Ciao Diego,

Your swagger.json definition does not seem to be valid, take a look here:
https://online.swagger.io/validator/debug?url=https://gist.githubusercontent.com/DGuidi/6d951dbb2045c2ec9eb10c10e9609991/raw/50dbf04b23ac4852fbabce71f171cbb491776fa4/swagger.json

Also that definition is HUGE! We have to try break it down to a minimal example...

**Comment by DGuidi** [comment]
> Your swagger.json definition does not seem to be valid
strange messages: I'm using [Nancy.Swagger](https://github.com/yahehe/Nancy.Swagger) to generate definition... maybe I've made a mistake and I'm using a 2.X definition?

**Comment by heldersepu** [comment]
Here i reduced your specs:
http://heldersepu.github.io/hs-scripts/swagger/DiegoGuidi.json
It is valid now:
https://online.swagger.io/validator/debug?url=http://heldersepu.github.io/hs-scripts/swagger/DiegoGuidi.json

And here is how that looks on the UI:
http://petstore.swagger.io/?url=http://heldersepu.github.io/hs-scripts/swagger/DiegoGuidi.json#/default/Iva_Create

**Comment by DGuidi** [comment]
ok thanks, I need to try in my installation to see where's my problem
