### ISSUE TITLE
Cannot use a class selector to style an API Definition (v3.X)

### ISSUE THREAD

**Issue by srpalomino** [swagger-api/swagger-ui#4155]
_swagger.json_

`"description": '<div class="class1"> class1 </div>',`

_src/style/layout.scss_

`.class1 {color: blue;}`

If I use an element selector, the styling renders sucessfully. However, using the class selector doesn't work at all.

Does anyone know why???

**Comment by shockey** [comment]
Short answer: sounds like [specificity](https://www.smashingmagazine.com/2007/07/css-specificity-things-you-should-know/)!

**Comment by srpalomino** [comment]
@shockey Thanks for the article! But the problem is still ongoing.

The least specific selector (div) is the only one that works. All other selectors (id, attribute, class) don't work. Not even inline styling works!

**Comment by shockey** [comment]
Ah, you're right, this is not a specificity problem - I should have read this more carefully :smile: 

Swagger-UI is stripping your class name from your HTML before it renders your description (or any other HTML field, for that matter).  

Here you can see that you're ending up with a plain div, with no classes:
<img src='https://shipusercontent.com/fc9fe1fddffb6225c39ce2d2f3d033a6/Pasted%20Image%201.png' title='Pasted Image 1.png' width=1792>

We're filtering out HTML attributes (like `class`) here: https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/providers/markdown.jsx#L33

Currently, we only allow `sanitize-html`'s default allowed attributes: `href`, `name`, and `target` (see their [README](https://www.npmjs.com/package/sanitize-html) for more context), and in addition allow `title` on `img` elements.

---

OWASP [doesn't mention `class` as an XSS vector](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet), and I can't think of any reason to disallow it, so if this is something that you need, it can be allowed.

As far as I can tell, it would be as easy as adding `"*": ["class"]` to `sanitize-html`'s options. Feel free to open a PR for this, alternatively, I can make the modification (at some point).
