### ISSUE TITLE
how to add custom request param to authentication param?

### ISSUE THREAD

**Issue by gitforpushpak** [swagger-api/swagger-ui#4159]
Hi

I have added one custom request param to my oauth2 security [custom_Id] in our project.So my question is  How can I add the same request param in the Swagger UI auth popup?

I did not find any configuration or solution. Please find below my expected auth params in the Available authorizations Popup.

client_id
client_secret
grant_type
custom_Id

Please suggest me the solution.
Thanks in Advance

**Comment by shockey** [comment]
Hi @gitforpushpak!

Custom OAuth2 parameters are non-standard, so OpenAPI doesn't have any way to describe them. Since OpenAPI can't describe them, we can't render an input for them.

The best you can do is use a `requestInterceptor` to attach any custom data you need to add.

Closing for now, just reply if you'd like to continue this discussion!

**Comment by shockey** [comment]
Oops - forgot to mention the `additionalQueryStringParams` option that `initOAuth` provides, you could use that to add your custom parameter though some custom code, see https://github.com/swagger-api/swagger-ui/blob/743eb8c9c73ec77dc5dba8b101dd1b7ff1a3e1ff/docs/usage/oauth2.md#L3.

**Comment by cristinacimpu** [comment]
Hi @shockey ,

the additionalQueryStringParams option that initOAuth provides is not working.
I have added the following code in my application:

window.onload = function() {
      // Build a system

      const ui = SwaggerUIBundle({

        url: "/openapi",

        dom_id: '#swagger-ui',

        deepLinking: true,

        presets: [

          SwaggerUIBundle.presets.apis,

          SwaggerUIStandalonePreset

        ],

        plugins: [

          SwaggerUIBundle.plugins.DownloadUrl

        ],

        layout: "StandaloneLayout"

      })
      
      ui.initOAuth({
        clientId: "test client id",
        clientSecret: "test client secret",
        realm: "your-realms",
        appName: "your-app-name",
        scopeSeparator: " ",
        additionalQueryStringParams: {test1: "hello"}
  });

      window.ui = ui

    }


But the "Available authorizations" pop-up look like this:
![image](https://user-images.githubusercontent.com/9418233/56376081-b27bcc80-620f-11e9-9cf6-f0dbd302d242.png)


Please suggest me the solution.
Thanks in advance
