### ISSUE TITLE
Incorrect URL creation for OAuth2 flows

### ISSUE THREAD

**Issue by rovinbhandari** [swagger-api/swagger-ui#4163]
Hello! I've done my best to search existing issues but I couldn't find one which described the problem I'm having; please guide me if it's not the case.

I have set up Swagger UI to make requests to the backend using Implicit flow OAuth2. The setup is quite basic:

```
               options.ConfigureOAuth2(
                    /*clientId*/ this.Configuration["Authentication:ClientId"],
                    /*clientSecret*/ this.Configuration["Authentication:ClientSecret"],
                    /*realm*/ null,
                    /*appName*/ "MyApp_SwaggerUI",
                    /*scope-separator*/ " ",
                    /*params*/ new Dictionary<string, string>
                    {
                        {"audience", this.Configuration["Authentication:Audience"]},
                    });
```

However, when I click on the "Authorize" button in Swagger UI, I get "invalid request" from the Auth server. The actual response is:

```
error=invalid_resource&error_description=AADSTS50001:+The+application+named+https://microsoft.onmicrosoft.com/myapp?response_type=token+was+not+found+in+the+tenant+named+MyTenant.++This+can+happen+if+the+application+has+not+been+installed+by+the+administrator+of+the+tenant+or+consented+to+by+any+user+in+the+tenant.++You+might+have+sent+your+authentication+request+to+the+wrong+tenant.
```

On inspecting further, I noticed that the URL created by SwaggerUI for authentication was malformed according to [this](https://tools.ietf.org/html/rfc3986#section-3.4) RFC (also explained in [this](https://stackoverflow.com/a/2924187/1161622) StackOverflow answer). The actual URL created by SwaggerUI for authentication is pasted below; notice the two '?'s. 

```
https://login.microsoftonline.com/MyTenant/oauth2/authorize?resource=https://microsoft.onmicrosoft.com/myapp?response_type=token&redirect_uri=http%3A%2F%2Fmyapp.local%3A44359%2Fswagger%2Fo2c.html&realm=na&client_id=ClientId&scope=&state=oauth2&audience=https%3A%2F%2Fmicrosoft.onmicrosoft.com%2Fmyapp
```

A quick look at the [minified] swagger-oauth.js in the browser shows that **the query params are being appended using a '?' without checking if the login URL has a '?' already**. I see that in the latest version of SwaggerUI codebase, this seems to have been fixed (not entirely sure though), but the fix was not (a). ported back to 2.0 (b). released for Asp.net core.

swaggerUi.api.swaggerVersion returns 2.0 on the console. I'm using the latest Swashbuckle.AspNetCore package (1.1.0).

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Swashbuckle.AspNetCore 1.1.0
| Which Swagger-UI version?       | 2.0
| How did you install Swagger-UI? |  NuGet Package Manager in Visual Studio
| Which browser & version?        | Google Chrome 63.0.3239.132
| Which operating system?         | Windows 10 Enterprise

I hope I've provided enough information for reproducibility and fixing the issue. If it is not the case, please let me know. Hoping for a resolution soon!

Thanks!

**Comment by rovinbhandari** [comment]
Any update on when the new version for Asp.Net Core will be out? Thanks!

**Comment by heldersepu** [comment]
I don't think the team is supporting the 2.0 version any more...

**Comment by rovinbhandari** [comment]
Hence the question on when can I expect the new version of Swagger UI for Asp.Net Core? Because currently I only see version 2.0.

**Comment by heldersepu** [comment]
if the team no longer supports it, I think the  answer will be never, 
there won't be a new version of the 2.x branch

**Comment by rovinbhandari** [comment]
But is it possible to even get Swagger 3.0+ for Asp.Net Core? (Sorry for the confusion but I that's what I wanted to ask from the beginning)

**Comment by heldersepu** [comment]
Of course it is possible, the Swagger-UI is language agnostic, 
- one option is to just drop the files somewhere and you can serve your definition that way...
- another option is to use the url param: http://petstore.swagger.io/?url=http://heldersepu.github.io/hs-scripts/swagger/DiegoGuidi.json#/default/Iva_Create
- the last I see and more complicated option is to integrate the 3.x UI with Swashbuckle.AspNetCore

**Comment by rovinbhandari** [comment]
Thanks for the helpful reply!
Option 2 is a no-go because auth would probably not work (unless petstore.swagger.io is added as a trusted reply url, which I'm not sure is a good idea).
Option 1 could work, but I see Option 3 as the easiest from a consumer perspective. I notice that 3.x UI is available with Swashbuckle for .net standard webapi projects. Any particular reason as to why it's not shipped for Asp.NetCore? That way, I (or any other consumer in my position) wouldn't need to change any code; just consuming a new package would work.

**Comment by heldersepu** [comment]
Swashbuckle is a different project check with them, seems there is some movement:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/543

Where did you see that 3.x UI is available with Swashbuckle for .net standard webapi projects?

**Comment by rovinbhandari** [comment]
Looks promising! Thanks for pointing me to that PR.
I was wrong about 3.x UI in Swashbuckle for .net standard webapi projects; it's actually 2.2.10.

I will close this issue and try the alternative you suggested, or the new Swashbuckle.AspNetCore package. Thank you!
