### ISSUE TITLE
Issue in VALIDATE_PARAMS in swagger-ui version 3.9.2

### ISSUE THREAD

**Issue by nishantgupta91** [swagger-api/swagger-ui#4165]
I am trying to do a GET request to an endpoint which doesn't require any query parameter. It's just a request to get the status of my server. While it works fine with swagger-ui version 3.0.21 with no errors in the console, with the 3.9.2 version, an console error TypeError: Cannot read property 'get' of undefined is obtained. UI gets rendered successfully with correct response, but I am not able to figure out why console error appears. This refers to the VALIDATE_PARAMS in reducers.js 

`[VALIDATE_PARAMS]: ( state, { payload: { pathMethod, isOAS3 } } ) => {
    let meta = state.getIn( [ "meta", "paths", ...pathMethod ] )
    let isXml = /xml/i.test(meta.get("consumes_value"))`

Here, the object "meta" remains undefined. 
As written earlier, request doesn't take any query parameters and JSON response is retrieved from the server. Should I mention Consumes / Produces types somewhere?

![screen shot 2018-01-26 at 5 36 09 pm](https://user-images.githubusercontent.com/7316063/35450142-6e113338-02bf-11e8-8397-87af271b8759.png)

**Comment by shockey** [comment]
@nishantgupta91, thank you for the report!

The good news is, we caught this issue earlier in the week (via https://github.com/swagger-api/swagger-ui/pull/4162/files#diff-35ca1faf1c59ce7112956ed7e5de50f8R55), and a fix should land tonight. The change made provides a default value for `meta` that has the `get` method available.

Closing as this is already fixed!
