### ISSUE TITLE
Unable to have `$ref`, `allOf`, etc under `properties` in a schema.

### ISSUE THREAD

**Issue by jlhawn** [swagger-api/swagger-ui#4168]
I ran into an issue where an API spec for Kubernetes has a definition for a type named `JSONSchemaProps`. This is used for the custom resources feature of k8s - you can define your own API resources and you supply a JSON schema. This means that a JSON schema actually needs to be defined as a JSON schema. This includes the properties `$ref`, `allOf` and others.

Unfortunately, a definition like this one results in errors:

```json
{
  "definitions": {
    "io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps": {
      "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).",
      "properties": {
        "$ref": {
          "type": "string"
        },
...
```

Saying that `$ref` is expected to be of type string. In this case though, I would expect that it's a perfectly legal value. `$ref` is actually the name of that property! It seems like swagger-ui is special-casing it when it shouldn't be.

A similar error occurs with the `allOf` or `anyOf` properties where it expects them to be an array.

If this is not considered a bug in swagger-ui, is there a way to escape `$ref` so that you can actually describe a property whose name is literally `$ref`?

**Comment by shockey** [comment]
Hi @jlhawn, this is working for me in the latest Swagger-UI:

<img src='https://shipusercontent.com/412668eea1e76167f20c8f18239ada5f/Pasted%20Image%201.png' title='Pasted Image 1.png' width=2672>

I'm not seeing any errors (besides the incomplete spec ones), and the $ref property renders as I would expect.

This was, however, an issue in earlier versions... it was patched in Swagger-Client last month: https://github.com/swagger-api/swagger-js/pull/1214

**Comment by jlhawn** [comment]
@shockey Sorry, I guess the errors only occur when you have a nested definition using a `$ref`. Try this JSON on `editor.swagger.io` to see what I mean:

```json
{
  "swagger": "2.0",
  "info": {
   "title": "Kubernetes",
   "version": "v1.8.8"
  },
  "paths": {
    "/foo": {
      "get": {
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CustomResourceValidation"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "JSONSchemaProps": {
      "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).",
      "properties": {
        "$ref": {"type": "string"}
      }
    },
    "CustomResourceValidation": {
      "description": "CustomResourceValidation is a list of validation methods for CustomResources.",
      "properties": {
        "openAPIV3Schema": {
          "$ref": "#/definitions/JSONSchemaProps"
        }
      }
    }
  }
}
```

**Comment by jlhawn** [comment]
![screen shot 2018-01-31 at 5 16 57 pm](https://user-images.githubusercontent.com/1441929/35656149-916a96be-06aa-11e8-8586-25a5125308f7.png)

**Comment by heldersepu** [comment]
I think the problem is on your `"$ref": {"type": "string"}` that looks weird...

**Comment by shockey** [comment]
@heldersepu the case here is actually trying to create a schema parameter by the name of `"$ref"`. Don't worry, the same line of thinking tripped me up too 😉 

---

@jlhawn hmm, yeah, I do see it now. I think I know what's happening.

In Swagger-Client's $ref resolver (which Swagger-UI uses under the hood), we always treat $ref as a blessed property name _unless_ the node's path matches a predefined list of paths where freely named keys are allowed:

https://github.com/swagger-api/swagger-js/blob/master/src/specmap/helpers.js#L1

https://github.com/swagger-api/swagger-js/blob/d615bf013f7c915e354c8906e3761789b077722b/src/specmap/lib/refs.js#L48-L50

Subschemas, clearly, are not included in this whitelist.. so this implementation will need to be reworked to support arbitrarily deep subschemas.

**Comment by heldersepu** [comment]
@shockey  ye, this was a weird one!
I managed to reproduce it on my sample C# WebApi:
http://swashbuckletest.azurewebsites.net/swagger/ui/index
it shows the error but it passes validation

And I used `allOf`, I think this also is part of this: 
https://github.com/swagger-api/swagger-js/blob/bdf670148a68bc40e9684a098baf5f060631a5f7/src/specmap/lib/all-of.js#L16

**Comment by heldersepu** [comment]
@shockey I was looking closely at the `freelyNamedKeyParents` and `properties` is not on the list.
