### ISSUE TITLE
Means to prevent the display of the OpenAPI specification URL link.

### ISSUE THREAD

**Issue by mikefidel** [swagger-api/swagger-ui#4171]
Wish to know if there is a way to prevent the display of the OpenAPI specification URL link.

The sponsor's preference is not to show the URL, if that can easily be avoided.  This is a non-critical, low priority request for support.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Support
| Which Swagger/OpenAPI version?  |  3.0.0
| Which Swagger-UI version?       |  3.9.1
| How did you install Swagger-UI? | Copy the contents of Dist folder, and modify index.html
| Which browser & version?        |  current Chrome & Firefox
| Which operating system?         |  Windows 10

### Configuration (index.html found in Dist folder)
Modifications to index.html found below:

```js
<script>
window.onload = function() {
    
  // NdexOAS
  function HideTopbarPlugin() {
    return {
      components: {
        Topbar: function() { return null }
      }
    }
  }

  // Build a system
  const ui = SwaggerUIBundle({
    url: "http://ndexbio.oas.swagger-ui.custom.s3-website-us-west-2.amazonaws.com/ndex_openapi.json",  // NdexOAS
    dom_id: '#swagger-ui',
    deepLinking: true,
    docExpansion: 'none',  // NdexOAS
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl,
      HideTopbarPlugin  // NdexOAS
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
</script>
```

### Current Behavior
The link to the OpenAPI document is displayed near the top of the info area.  I believe this is done in ...src/core/components/info.jsx.  Rendering appears to be determined on the field named "url".  I could not chase where the contents of that field originates from.  I'm reasonably sure it originates from the url parameter in SwaggerUIBundle({}).  There are alternatives to the url parameter, and I wondered if one of them would prevent the link from being rendered.  I experimented with configUrl, but the outcome was the same.  

Here is a screen snapshot of the link, as outlined in a green box.
![url](https://user-images.githubusercontent.com/20869677/35476881-e6702d7c-036c-11e8-9dd6-74e4cae3a0bd.png)

### Desired Behavior
The link to the OpenAPI document is not rendered. That is, the url link shown in the above screen snapshot is not rendered.

**Comment by shockey** [comment]
Hey @mikefidel! Sorry for the delay here, I knew this was going to take some work in the core code.

I've just merged #4330, which creates some new plug points that you can use to ditch the URL line, like so:

```js
const HideInfoUrlPartsPlugin = () => {
  return {
    wrapComponents: {
      InfoUrl: () => () => null,
      InfoBasePath: () => () => null, // this hides the `Base Url` part too, if you want that
    }
  }
}
```

This will work starting in the next release of Swagger-UI.

Closing for now since this addresses the question pretty directly - feel free to reply if there's anything outstanding.

Thanks for using OpenAPI and Swagger-UI!
