### ISSUE TITLE
parameters not support content?

### ISSUE THREAD

**Issue by zeromake** [swagger-api/swagger-ui#4172]
Q | A
-- | --
Which Swagger/OpenAPI version? | 3.0.0
Which Swagger-UI version? | 3.9.3
How did you install Swagger-UI? | Copy the contents of Dist folder, and modify index.html
Which browser & version? | current Chrome & Firefox
Which operating system? | linux64

see [doc](https://swagger.io/docs/specification/describing-parameters/#schema-vs-content-8)

demo:
``` yaml
openapi: 3.0.0
info:
  title: zero-reader api
  description: ''
  version: 0.1.0
paths:
  '/api/admin/user/{primary_key}':
    get:
      parameters:
        - in: path
          name: primary_key
          required: true
          schema:
            type: integer
        - in: query
          name: filter
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  color:
                    type: string
      summary: Returns a list of users.
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: integer
                  message:
                    type: string
                  data:
                    type: integer
```

but swagger-ui not support?:
![anim](https://user-images.githubusercontent.com/8318747/35496703-27406358-0502-11e8-85fe-1e01602694de.gif)

**Comment by hkosova** [comment]
OpenAPI 3.0 parameters with `content` are not supported yet - see https://github.com/swagger-api/swagger-ui/issues/3641.

**Comment by zeromake** [comment]
@hkosova Thank！

**Comment by shockey** [comment]
Closing in favor of the backlog ticket.

Thanks for the report, @zeromake!
