### ISSUE TITLE
CSP violations - inline javascript & loading third-party fonts

### ISSUE THREAD

**Issue by ashleymercer** [swagger-api/swagger-ui#4187]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.9.3
| How did you install Swagger-UI? | webjars
| Which browser & version?        | All
| Which operating system?         | All

### Expected Behavior
swagger-ui should work when strict `Content-Security-Policy` (CSP) header is set.

### Current Behavior
Two things that currently prevent swagger-ui from loading with a strict CSP:

- inline javascript used to initialise the UI
- loading font files from a third-party domain

### Possible Solution

- inline javascript could be moved to a `.js` file
- font files could be bundled with swagger-ui

**Comment by ashleymercer** [comment]
Related issue: [CSP violations due to inline styles](https://github.com/swagger-api/swagger-ui/issues/3370)

**Comment by shockey** [comment]
Closing in favor of https://github.com/swagger-api/swagger-ui/issues/3370 😄

**Comment by ashleymercer** [comment]
Thanks, I'll follow the other ticket
