### ISSUE TITLE
Integrate with the Existing express Project 

### ISSUE THREAD

**Issue by riteshnus** [swagger-api/swagger-ui#4199]
When i copied the dist folder of swagger-ui in my local directory where swagger.yaml exist, i didnt able to access it. I modified the app file with "app.use('/swagger', express.static(path.join(__dirname, 'api/swagger')));" to get the static content.  And when i am trying to run my server not able to locate it. Also  swagger is moved to react now and there is no index.html. so which file it run specifically now.

**Comment by heldersepu** [comment]
What you mean there is no `index.html` ?
Look again:
https://github.com/swagger-api/swagger-ui/tree/master/dist

**Comment by riteshnus** [comment]
sorry, i have taken the dist files from "node_module/swagger-ui/dist " folder which don't have the index file.

**Comment by heldersepu** [comment]
Questions like this I think you will be better off asking on StackOverflow...

**Comment by riteshnus** [comment]
Sure. Thank you for help
