### ISSUE TITLE
Server can't produce application/json

### ISSUE THREAD

**Issue by dataspun** [swagger-api/swagger-ui#4205]
I get the error `server can't produce application/json` printed to Chrome console when clicking the Try It Out! button.  This occurs for every method defined in my API, and I've failed to find any further information or clues as to why this is happening other than the reference to `swagger-ui.min.js:7` which indicates some kind of mismatch in content negotiation.

Other than this innocuous console error, the API functions correctly both consuming and producing application/json.  I've verified this with Swagger UI, Postman and publishing a Release to a separate server.

I'm using swagger-ui version v2.2.10 via Swashbuckle.AspNetCore.  Has anyone else encountered this error, or have an idea how to fix?  Some sample info on my API calls that result in this error:

`curl -X GET --header 'Accept: application/json' 'http://localhost:5000/foo'`

```
{
  "date": "Thu, 08 Feb 2018 06:22:37 GMT",
  "server": "Kestrel",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8"
}
```

**Comment by scottohara** [comment]
Hi @dataspun,

The error message `Server can't produce application/json` implies that your API definition doesn't have `application/json` listed in its `produces` array.

For reference:

```json
{
  "swagger": "2.0",
  "info": {
    "version": "...",
    "title": "...",
    "description": "..."
  },
  "host": "...",
  "basePath": "...",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json",
    "..any other content types your API consumes..."
  ],
  "produces": [
    "application/json",
    "...any other content types your API produces..."
  ],

  ...

}
```

**Comment by dataspun** [comment]
Thanks @scottohara, but yes my controller and method are both decorated with `[Produces("application/json")]`

**Comment by scottohara** [comment]
I see.

I'm not familiar with Swashbuckle.AspNetCore myself, but it is possible to extract the generated API definition that it creates?

If you're able to provide an example of the generated API definition, I can check it against a standalone version of Swagger UI 2.x for you.

This should at least confirm if the problem is in Swagger UI, Swashbuckle, or the definition that is being generated from it.

**Comment by dataspun** [comment]
I'm unclear how to generate the API definition as you suggested using Swashbuckle.AspNetCore.  I'm also struggling with debugging the swagger-ui logic as it appears minification of the file is forced.
  
I'm assuming this is something I've caused and can fix. but so far no joy.

**Comment by heldersepu** [comment]
@dataspun ` Swashbuckle.AspNetCore` should generate that automatically for you, it is something like:
http://swashbuckletest.azurewebsites.net/swagger/docs/V1

**Comment by dataspun** [comment]
@heldersepu thanks!

**Comment by dataspun** [comment]
This issue appears specific to Swashbuckle.AspNetCore and is discussed in PR [#583](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/583) and issue [#63](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/63).
