### ISSUE TITLE
@ApiParam not working in interface

### ISSUE THREAD

**Issue by piyushj90** [swagger-api/swagger-ui#4206]
I have added @ApiParam annotation in interface method, but it is not working. Please let me know, if it is fixed in v2.8.0.
Below is code sample:
`@ApiOperation(value = "Find")
ResponseDto find(@ApiParam(value = "Filter Criteria", required = true) String filterCriteria,      HttpServletResponse response);`

I am using springfox v2.8.0

**Comment by heldersepu** [comment]
@piyushj90 Are you sure that is a swagger-ui issue and not in springfox ?

**Comment by piyushj90** [comment]
@heldersepu I am not sure, that's why I already mentioned that I am using springfox.

**Comment by heldersepu** [comment]
Can you provide your swagger spec?

**Comment by shockey** [comment]
Closing; this sounds like a Springfox issue.

If it's a Swagger-UI issue, please open a new ticket that follows the provided template! Be sure to provide a Swagger/OpenAPI document, we can't readily interpret Springfox annotations here.
