### ISSUE TITLE
Support for Kerberos and others as type values of Security Scheme Object

### ISSUE THREAD

**Issue by ashishdhyani** [swagger-api/swagger-ui#4208]
Hi 
I tried to setup swagger UI for my RESTful api which is kerberos enabled, but I am receiving 401 error, however the same link works on the browser.
I am using OAS 3.0
Attached swagger.txt
[swagger.txt](https://github.com/swagger-api/swagger-ui/files/1710321/swagger.txt)

could you please tell what is wrong with my specification ?

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template. Specifically, I need more information on what's happening vs what you expect should be happening in Swagger-UI.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!

**Comment by rickalmeidaSB** [comment]
Hey, I'm also looking for this!

**Comment by rickalmeidaSB** [comment]
@webron
