### ISSUE TITLE
Example/Examples in @ApiParam not showing in swagger-ui

### ISSUE THREAD

**Issue by dominicE** [swagger-api/swagger-ui#4209]
At first what we are using:
- Latest Swagger-ui (3.9.3), tested from dist directory and from unpkg.com
- swagger-core 1.5.18 with Java8 and Jersey 2.26

The Problem is our examples are not shown in swagger-ui documentation. If we load our documentation to editor.swagger.io, then it works fine.

Here is an example:
```
		@ApiParam(value = "Printer config in json format", required = false, example = ApiDocuExamples.PRINTER_CONFIG)
		@FormParam("config") String configJson,
```
There is no difference in using example or examples we tried both.
This is how it looks like in swagger-ui:

![image](https://user-images.githubusercontent.com/2743382/36021472-2de869bc-0d86-11e8-8ea2-2c773db42953.png)

Is this a known issue or are we doing something wrong?

**Comment by heldersepu** [comment]
Can you provide your swagger API definition?

**Comment by dominicE** [comment]
Do you mean the complete json/yaml file or the first few lines?

```
    "swagger": "2.0",
    "info": {
        "version": "1.2.0",
        "title": "plentyBase"
    },
```

**Comment by heldersepu** [comment]
everything, if is too long add as a gist

**Comment by dominicE** [comment]
Here is the gist:
https://gist.github.com/dominicE/9a32ffa639354e2abb3e38352da36297

But documentation is WIP

**Comment by heldersepu** [comment]
That is using `"x-example"` that will not show on the UI

```JS
 "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id of printer config which should be updated",
                        "required": true,
                        "type": "integer",
                        "pattern": "\\d+",
                        "format": "int32",
                        "x-example": 1
                    },
                    {
                        "name": "config",
                        "in": "formData",
                        "description": "New printer config",
                        "required": true,
                        "type": "string",
                        "x-example": "{\n    \"configName\": \"Drucker Client Raum\",\n    \"printerName\": \"Brother HL-2270DW series\",\n    \"paperTray\": \"AutoSelect\",\n    \"paperSize\": \"A4\",\n    \"paperOrientation\": \"portrait\",\n    \"paperScale\": \"fit_to_page\",\n    \"duplexMode\": \"\",\n    \"showPrintDialog\": false,\n    \"paperHeight\": 0,\n    \"paperWidth\": 0,\n    \"marginLeft\": 0,\n    \"marginRight\": 0,\n    \"marginTop\": 0,\n    \"marginBottom\": 0,\n    \"autoRotateAndCenter\": false,\n    \"printerPlugin\": \"Standard\"\n}"
                    }
                ],
```

**Comment by dominicE** [comment]
Yeah, but it is auto-generated form example/examples

```
		@ApiParam(value = "Printer config in json format", required = false, example = ApiDocuExamples.PRINTER_CONFIG)
		@FormParam("config") String configJson,
		@ApiParam(value = "Id of an existing printer config", required = false, example = ApiDocuExamples.PRINTER_CONFIG_ID)
		@FormParam("configId") Integer configId)
```

**Comment by heldersepu** [comment]
what do you mean by auto-generated?
auto-magically? something is generating it, that something is your problem not the UI

**Comment by dominicE** [comment]
As mentioned before we are working with swagger-core 1.5.18 and Java8 and Jersey 2.26.

https://mvnrepository.com/artifact/io.swagger/swagger-jersey2-jaxrs

This is providing us an /swagger.json and /swagger.yaml endpoint which will generate those x-example entries

**Comment by heldersepu** [comment]
As mentioned before:  that something (that generetes your swagger.json) is your problem.

**Comment by heldersepu** [comment]
Looking at the pending Pull Request, there is one:
https://github.com/swagger-api/swagger-ui/pull/3538
that should introduce support to `"x-example"` but it seem there are conflicts

**Comment by dominicE** [comment]
Thanks for the pull-request. I will look into this.

How need the example parameter be called in json/yaml that it gets recognized by swagger-ui instead of x-example?

**Comment by heldersepu** [comment]
Look into the OAS spec that you want to target for more details:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

But I guess you can close this issue, there is nothing the UI can do at the moment

**Comment by dominicE** [comment]
Okay, thank you :)

**Comment by tdaskhatri** [comment]
Hi, I want swagger to generate UI according to my customized definition file e.g mySwagger.json. Is there any way to do this? Thanks.
