### ISSUE TITLE
deepObject query parameter doesn't work

### ISSUE THREAD

**Issue by jfboismenu** [swagger-api/swagger-ui#4216]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   Bug
| Which Swagger/OpenAPI version?  | 3.0
| Which Swagger-UI version?       |  3.10
| How did you install Swagger-UI? |  git clone
| Which browser & version?        | Chrome 64
| Which operating system?         | macOS

The webui doesn't seem to handle deepObject correctly. For example:

```
openapi: 3.0.0
servers:
  - url: https://localhost
info:
  description: |
    This is a sample API that allows to reproduce the deepObject UX issue
  version: "1.0.0"
  title: deepObject UX issue
paths:
  /:
    get:
      parameters:
        - in: query
          name: param
          schema:
            type: object
            properties:
              first:
                type: integer
                example: 1
              second:
                type: string
                example: "this is a string"
          style: deepObject
          explode: true
      responses:
        '200':
          description: OK
```
Here's what the web-ui gives:

![screen shot 2018-02-12 at 15 50 47](https://user-images.githubusercontent.com/8126447/36118981-b987c3c2-100c-11e8-842f-0ffa791c41b4.png)

If I were to type first=1 in that box for example, the generated URL would be

`https://localhost/?param[0]=f&param[1]=i&param[2]=r&param[3]=s&param[4]=t&param[5]=%3D&param[6]=1`

As you can see, it simply iterates over each character, uses it's position at the argument name and the letter as the value.

[This code](https://github.com/swagger-api/swagger-js/blob/c8c90e9b8e3a0b0cb8b386e24527345cd666fc47/src/execute/oas3/parameter-builders.js#L34-L51) from `swagger-js` expects an object to be passed as a parameter and wants to iterate over the keys of an object.

It seems like `deepObject` fields in `swagger-ui` should be treated as a JSON document and be unserialized into an object before being passed to `swagger-js`s `parameter-builds.js:query`.

**Comment by mbandrewfoster** [comment]
Also having the exact same issue on swaggerhub. Makes it unusable in it's current state.

**Comment by itsjavi** [comment]
It would be enough to have at least a generated JSON example in a textarea (like a regular JSON body) and then the UI should serialize it properly according to the style.

**Comment by webron** [comment]
Looks like this is fixed. If your experience is different, please report back and we'll reopen the ticket.
