### ISSUE TITLE
Generate Server Broken

### ISSUE THREAD

**Issue by jglisson** [swagger-api/swagger-ui#4220]
The Generate Server feature is not working. Running locally, or at editor.swagger.io. I am just using the Swagger Petstore as an example.

![image](https://user-images.githubusercontent.com/6360789/36154474-94f5333a-109f-11e8-983c-e311e9eecd98.png)

**Comment by heldersepu** [comment]
You skipped a lot of details from the issue template...

**Comment by heldersepu** [comment]
If this issue is purely on the editor it should be reported here:
https://github.com/swagger-api/swagger-editor/issues/new

**Comment by jglisson** [comment]
What else do you need? When you attempt to generate a server or client from the editor, you get a 500 error (as the screenshot displays) in the browser console.

http://editor.swagger.io/

Thanks!

**Comment by jglisson** [comment]
Following threads there reporting the same issue...
