### ISSUE TITLE
swagger-ui version 3.9-3.10 does not send Request Body for OAuth in Authorize button

### ISSUE THREAD

**Issue by Yevhen-Mordak** [swagger-api/swagger-ui#4221]
swagger-ui version 3.9-3.10 does not send Request Body for OAuth on Authorize button

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.10
| How did you install Swagger-UI? | npm
| Which browser & version?        | chrome@latest
| Which operating system?         | windowsx64

### Demonstration API definition

{"swagger":"2.0","info":{"title":"Welcome to the Search API","description":""},"basePath":"/","paths":{"/ProjectLeads":{"post":{"tags":["ProjectLeads"],"summary":"Return filtered listing of project leads the user has a subscription to","description":"Retrieve Project Leads using SearchAPI.Data.ProjectLeadsQueryCriteria to have more granular filtering capabilities","operationId":"ProjectLeadsPost","consumes":["application/json-patch+json","application/json","text/json","application/*+json"],"produces":["application/json"],"parameters":[{"name":"criteria","in":"body","description":"Object that encapsulates all criteria to be applied for filtering","required":false,"schema":{"$ref":"#/definitions/ProjectLeadsQueryCriteria"}}],"responses":{"200":{"description":"Filtered search result for Project Leads","schema":{"$ref":"#/definitions/SearchResults[Project]"}},"401":{"description":"Unauthorized"}}}}},"definitions":{"ProjectLeadsQueryCriteria":{"description":"List of values to filter upon (facet provides the values to select)","type":"object","properties":{"filters":{"$ref":"#/definitions/ProjectLeadsQueryFilters","description":"Query Facets lists"},"includeAllFacets":{"description":"Include All Facets","default":true,"type":"boolean"},"limit":{"format":"int32","description":"Limit search results return count","default":30,"type":"integer"},"offset":{"format":"int32","description":"Scip first X search results","default":0,"type":"integer"},"sort":{"description":"Sort result by 'Field Name'","default":"LastUpdatedDate","type":"string"},"sortDir":{"description":"sort direction is 'asc' or 'desc'","default":"asc","type":"string"}},"example":{"filters":{"bidsToContactRoleGroup":["Owner"],"buildingUse":["Educational","Medical"],"projectValueRange":["$100k - $250k"],"date":{"type":"lastUpdatedDate","value":-90},"location":{"type":"county","value":"us-oh-*"},"searchText":"school"},"includeAllFacets":true,"limit":30,"offset":0,"sort":"LastUpdatedDate","sortDir":"asc"}},"ProjectLeadsQueryFilters":{"description":"Query Filters","type":"object","properties":{"bidsToContactRoleGroup":{"description":"Bids To Contact Role Group","type":"array","items":{"type":"string"}},"buildingUse":{"description":"building Use Name","type":"array","items":{"type":"string"}},"certification":{"type":"array","items":{"type":"string"}},"constructionType":{"type":"array","items":{"type":"string"}},"contractingMethod":{"type":"array","items":{"type":"string"}},"status":{"type":"array","items":{"type":"string"}},"sector":{"type":"array","items":{"type":"string"}},"projectValueRange":{"type":"array","items":{"type":"string"}},"date":{"$ref":"#/definitions/DynamicTypeFilter"},"location":{"$ref":"#/definitions/DynamicTypeFilter"},"searchText":{"default":"","type":"string"}}},"DynamicTypeFilter":{"type":"object","properties":{"type":{"type":"string"},"value":{"type":"object"}}},"SearchResults[Project]":{"type":"object","properties":{"numFound":{"format":"int32","type":"integer"},"start":{"format":"int32","type":"integer"},"docs":{"type":"array","items":{"$ref":"#/definitions/Project"}},"facets":{"type":"object","additionalProperties":{"type":"array","items":{"$ref":"#/definitions/KeyValuePair[String,Int32]"}}}}},"Project":{"type":"object","properties":{"id":{"type":"string"},"title":{"type":"string"},"city":{"type":"string"},"state":{"type":"string"},"county":{"type":"string"},"projectDescription":{"type":"string"},"lastUpdatedDate":{"format":"date-time","type":"string"},"bidDate":{"format":"date-time","type":"string"},"propertyType":{"type":"string"},"documentCount":{"format":"int32","type":"integer"},"publicStatus":{"type":"string"},"startDate":{"format":"date-time","type":"string"},"projectValue":{"format":"float","type":"number"},"buildingUsesString":{"type":"string"},"idocumentDownLoadCount":{"format":"int32","type":"integer"}}},"KeyValuePair[String,Int32]":{"type":"object","properties":{"key":{"type":"string","readOnly":true},"value":{"format":"int32","type":"integer","readOnly":true}}}},"securityDefinitions":{"Bearer":{"name":"Authorization","in":"header","type":"apiKey","description":"JWT Authorization header using the Bearer scheme. Example: \"Bearer <access_token>\""},"oauth2":{"flow":"password","authorizationUrl":"https://logindev.somewhere.com/connect/token","tokenUrl":"https://logindev.somewhere.com/connect/token","type":"oauth2"}}}

### Current Behavior

When User hit 'Authorize' in our case we have 2 options 'jwt token' and 'OAuth', in swagger-ui version 2.x request is POST and have request  body, in version 3.x authorization request does not have request body.

### Possible Solution

My best bet is API v2 cannot be functional in UI v3 (at least 'Authorize' button does not request OAuth). 

### Context

I use Swashbuckle.AspNetCore.Swagger at back-end to generate json, swagger-ui is only pointing to json above, no other changes in swagger-ui.

**Comment by Yevhen-Mordak** [comment]
![image](https://user-images.githubusercontent.com/26307890/36158475-b55ec4fa-10dc-11e8-82bb-b3e5d9bb5784.png)

**Comment by Yevhen-Mordak** [comment]
That was CORS and swagger since version 3 shows more errors in logs (that was confusing comparing to v2.x), that was resolved by hitting auth on the same origin.

another useful note is to add Security to generated json https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/OAuth2Integration/ResourceServer/Swagger/SecurityRequirementsOperationFilter.cs

**Comment by saeedvaziry** [comment]
I have this problem in nodejs

**Comment by Yevhen-Mordak** [comment]
What "this" you mean? Screenshot, details, questions, anything?

**Comment by saeedvaziry** [comment]
Screenshot. Not sending request body
