### ISSUE TITLE
Optional array query params are always sent when example is specified

### ISSUE THREAD

**Issue by theaeolianmachine** [swagger-api/swagger-ui#4223]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0
| Which Swagger-UI version?       | 3.X 
| How did you install Swagger-UI? | editor.swagger.io
| Which browser & version?        | Google Chrome 64
| Which operating system?         | macOS Sierra

### Demonstration API definition

```yaml
openapi: '3.0.0'
info:
  description: >-
    Repro API
  title: Repro API
  version: '1.0'
paths:
  /test:
    get:
      summary: Test get
      parameters:
        - name: fields
          in: query
          required: false
          explode: false
          schema:
            type: array
            items:
              type: string
          style: form
          example:
            - friends
            - family
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
```

### Configuration (browser query string, constructor, config.yaml)
No additional configuration, just using editor.swagger.io with no query params

### Repro
* Click on /test, click on Try it out
* Both examples will be pre-filled in the list of fields for the `fields` param.
* Delete both arguments to the fields param, then send a request

### Expected Behavior

When I set an example for a query array parameter, I should be able to delete all of the examples and run the request without sending over the param itself, e.g:

`curl -X GET "https://editor.swagger.io/test" -H "accept: application/json"`

### Current Behavior

It still sends over the parameter without any args:
`curl -X GET "https://editor.swagger.io/test?fields=" -H "accept: application/json"`

Since I have not specified `allowEmptyValue` to be true, I should expect this parameter not to be sent.

### Possible Solution

* If `allowEmptyValue` is set to false (by default), the field should not be sent in the request if there are no arguments to the param.
* If `allowEmptyValue` is set to true, I should be able to select whether it sends over the request either with the param but without a value, or without the param at all. This is likely dependent on the solution for #4122.

### Context

Unfortunately this means that I can't use examples in the spec for these arguments (there are two, and they are common to all requests), because sending them over empty completely changes the response of the API. It'd be great to still be able to set the examples!

Thanks so much in advance!

**Comment by theaeolianmachine** [comment]
Ping on this - would just like an ack for the sake of knowing this has been seen :).

**Comment by heldersepu** [comment]
Yes it has been seen.
When I saw it for the first time I could not understand what the bug is...
And the more I read the less I see the relation with the example.

**Comment by theaeolianmachine** [comment]
Could you be more specific about what's confusing about the bug report? A concrete example for this:

Let's say that you have a query parameter that specifies exactly the fields you want from the API. By default when you make a GET request to an object, such as `GET example.com/animals/12345`, you get a compact representation back because the API doesn't want to send all data on the the object, such as:

```
{
  "id": 12345,
  "name": "Clifford"
}
```

If I wanted to say get the animal's age and type as well, I could make a request like: `GET example.com/animals/12345?fields=id,name,age,type` and I'd get a response like the following:

```
{
  "id": 12345,
  "name": "Clifford",
  "age": 7,
  "type": "Dog"
}
```

However, sending `GET example.com/animals/12345?fields=` is equivalent to asking for no fields, in which a reasonable response would likely be to at least return the `id`:
```
{
  "id": 12345
}
```

Or worse with an `HTTP 400`.

There is a semantic difference between not specifying the fields parameter (and getting a default response from the API), and specifying an empty array for the fields. Because of how swagger-ui handles examples on array query parameters, it does not respect this because it will always send over an empty array (even if allowEmptyValues is set to false explicitly).

Does that make more sense?

**Comment by heldersepu** [comment]
The title says: Optional array query params are always sent when example is specified
But If I remove them they are not sent...

**Comment by heldersepu** [comment]
Also I come from a Microsoft .Net world... 

Here is where I get muddy 

Including the param or not for me you jumping across actions
- http://swagger-net-test.azurewebsites.net/api/TestMultiGet?id=123
- http://swagger-net-test.azurewebsites.net/api/TestMultiGet


Here is a sample controller
```c#
    public class TestMultiGetController : ApiController
    {
        public string Get()
        {
            return "Get1";
        }

        public string Get(int id)
        {
            return "Get2";
        }
    }
```
___
So what you are showing:
- `GET example.com/animals/12345`
- `GET example.com/animals/12345?fields=id,name,age,type`

For me those are two different actions

**Comment by theaeolianmachine** [comment]
Did you read the bug report? The query parameter is always sent, empty, even when you remove the examples. Empty query parameter != no query parameter being sent at all. I feel this is very explicit in the Expected & Current Behavior section.

Your example is not directly equivalent - it should take an array as a parameter. Here's some pseudocode along those lines:

```csharp
  public class TestMultiGetController : ApiController
    {
        // Let's call this GetNoParams
        public string Get()
        {
            return "Get1";
        }

        // Notice that this takes an array, and not a single parameter
        // Let's call this GetArrayOfFields
        public string Get(Array[] fields)
        {
            return "Get2";
        }
    }
```

And the bug is that GetArrayOfFields gets called every time because it's getting an empty array when the parameter is still sent; GetNoParams never gets called, and there is no way to specify this to Swagger UI to do so.

**Comment by heldersepu** [comment]
Did I read the bug report?
Maybe, Maybe not, Maybe I'm better off not typing anymore

**Comment by theaeolianmachine** [comment]
@heldersepu, I'm sorry - I don't mean to come off as non-constructive here.

I asked that legitimately as a question because the title of this issue was addressed in one of your comments rather than the content of the issue, especially after I wrote an additional example highlighting the exact behavior that's present in this bug and the effects that it has. If it's legitimately not true that you read it, it doesn't feel respectful of my time. Since I had not received direct feedback on some of the text present, and instead felt I received a brief response that felt like it didn't actually address the explanations I'd written, I wanted to clarify what efforts you had put into this up to this point. I appreciate you taking the time to explain this via your own example.

Perhaps something that would be helpful to understand is your knowledge of HTTP independent of C#/.NET? It would certainly make it easier to explain to you my issue if I have a better understanding of where your current knowledge is.

For my use case, this bug effects nearly every API endpoint that we have, so I'd really love to see it at least categorized, and optimistically scheduled - so, I'm sorry for any negative connotations I may have presented.

**Comment by josros** [comment]
I recently upgraded my swagger/swagger-ui from version ```2.7.0``` to ```2.8.0``` and I observed a behavior that might be related to this issue.

Let's say I have a request parameter called ```types``` which is not required and can have ```0..*``` elements assigned.
Swagger-ui ```2.7.0``` did the following in case I didn't choose an element assignment for the ```types``` parameter:

```curl -X GET --header 'Accept: application/json' 'https://url/resource```

What swagger-ui ```2.8.0``` does is:

```curl -X GET --header 'Accept: application/json' 'https://url/resource?types=```

**Comment by shockey** [comment]
Bug confirmed in v3.15.0.
