### ISSUE TITLE
The issue while sending POST request with multipart/form-data attributes

### ISSUE THREAD

**Issue by megusta420** [swagger-api/swagger-ui#4226]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |How to check it out?
| Which Swagger-UI version?       |swagger-ui 3.x
| How did you install Swagger-UI? | Using composer
| Which browser & version?        |Chrome 58.0.3029.110 64bit
| Which operating system?         | Windows 10 as host OS and Ubuntu as guest OS running in operation of vagrant.

### Demonstration API definition

```yaml
     * @SWG\Get(
     *   path="/clients/{id}",
     *   summary="List client details",
     *   operationId="getClientDetails",
     *   tags={"clients"},
     *   @SWG\Parameter(name="id", required=true, type="integer", description="ID of the client", in="path"),
     *   @SWG\Response(response=200, ref="#/definitions/response_200"),
     *   @SWG\Response(response=404, ref="#/definitions/response_404"),
     * )
     *
     *
     *
     * @SWG\Post(
     *   path="/clients/",
     *   consumes={"multipart/form-data"},
     *   summary="Create new client",
     *   operationId="createNewClient",
     *   tags={"clients"},
     *   @SWG\Parameter(name="name", type="string", description="Name of the client", in="formData"),
     *   @SWG\Response(response=200, ref="#/definitions/response_200"),
     *   @SWG\Response(response=500, ref="#/definitions/response_500"),
     * )
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Behavior

Hello. I have small REST API system which allows to CRUD some Resources.
The bug happens while I am trying to make a new Resource with a POST request on my API using this:

```
POST /client/
someparams=somevalues
```
Also I use use Insomnia REST client and have no problems with testing this:

```
POST /client/
and here some params sent as multipart/form-data with content-disposition parameter.
```

All other GET/PUT/DELETE works successfully in swagger-ui. Also the problem happens just while using swagger-ui: there are no such behavior with POSTing in Insomnia.

So I am trying to make a POST with swagger-ui and see that swagger do not send data as multipart/form-data (in Insomnia only this type of request accepted by my Laravel REST app, application/form-x-www-urlencoded is not allowed and do not accepted by my POST /clients/ route).

After that I selected mannualy necessary header like this in the source of config as above:

```
     *   consumes={"multipart/form-data"},
```
And swagger-ui showed me that now the right params sent to the curl:

```
curl -X POST "http://dfs.test/api/clients/" -H "accept: application/json" -H "Content-Type: multipart/form-data" -H "X-CSRF-TOKEN: " -d {"name":"asd"}
```
But! Here is the bug happens. Even with such settings swagger-ui is not accepted by the REST app as valid REST query 'POST /clients/'+some data as form-data. And in the same time Insomnia works correctly.

**Comment by webron** [comment]
Apologies for the late response here, kinda slipped under our radar. The problem is that you have not provided an actual API definition (we can't use the PHP code) so it's difficult to follow it. Please try using the latest swagger-ui version, and if the problem still exists, file a new ticket providing the required details.
