### ISSUE TITLE
customize swagger api logo in spring boot

### ISSUE THREAD

**Issue by narendrasolanke** [swagger-api/swagger-ui#4229]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by webron** [comment]
Can't really help with this kind of a ticket, sorry.
