### ISSUE TITLE
Autoscroll to model section using #model-{Model}

### ISSUE THREAD

**Issue by mgrzechocinski** [swagger-api/swagger-ui#4230]
Hi,

I need to refer few models in SwaggerUI web page from my wiki page. What I'm trying to achieve is to have a direct link, once clicked, will open SwaggerUI page scrolled down to the position of that model.  

I found it working by appending `#model-{Model}` to my Swagger base path. Taking http://petstore.swagger.io as an example, when I simply open it and then append URL with  `#models-Order`, it works fine.

![screen recording 2018-02-15 at 03 28 pm](https://user-images.githubusercontent.com/393518/36261553-00675a50-1265-11e8-800a-a29a1f81bbbc.gif)

However, then I try to open that link, SwaggerUI changes URL to http://petstore.swagger.io/#/model-Order (please notice additional slash after #):

![screen recording 2018-02-15 at 03 31 pm](https://user-images.githubusercontent.com/393518/36261668-6adaab6c-1265-11e8-8b77-a580cb62c2d7.gif)

I'm trying to figure out where the problem might be, or maybe it's not supported by SwaggerUI? Since it's fully reproducable on petstore project I do not suspect my particular nginx/SwaggerUI configuration to be wrong.

Will appreciate any hints around that.

**Comment by heldersepu** [comment]
Looks like this is a dup of a very old issue #1369 that

**Comment by mgrzechocinski** [comment]
Yep. Sorry, didn't find it. Closing.
