### ISSUE TITLE
How can pass default values in swagger_path function?

### ISSUE THREAD

**Issue by Ali7862** [swagger-api/swagger-ui#4233]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by webron** [comment]
Please file an issue again filling the issue template and providing the required details. We can't help you otherwise.
