### ISSUE TITLE
Online validator badge missing image

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#4234]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | "swagger": "2.0"
| Which Swagger-UI version?       | 3.10
| How did you install Swagger-UI? | [Swagger-Net](https://www.nuget.org/packages/Swagger-Net/)
| Which browser & version?        | Chrome
| Which operating system?         | Win10

### Demonstration API definition
http://petstore.swagger.io/

### Expected Behavior
There should not be any missing images

### Current Behavior
First time we load there is loading link with a missing image, see image below:
![image](https://user-images.githubusercontent.com/545474/36384323-e8dc04bc-155c-11e8-95cb-b5911b6a558c.png)

### Possible Solution
Maybe we should hide the "Online validator badge" image until page is fully loaded?

**Comment by heldersepu** [comment]
Here is what I see happening...
When everything is loading we get:
```html
<img alt="Loading..."></img>
```
And this is how it looks once done:
```html
<img alt="Online validator badge" src="https://online.swagger.io/validator?url=...">
```

**Comment by webron** [comment]
Sounds like a reasonable solution to me.

**Comment by heldersepu** [comment]
I did it with a custom css:
```css
img[alt="Loading..."] {
    display: none !important;
}
```

Not sure where to incorporate that...
Maybe on file: 
https://github.com/swagger-api/swagger-ui/blob/master/src/style/_layout.scss

**Comment by webron** [comment]
@shockey ?
