### ISSUE TITLE
Add Api Response Time to Response result

### ISSUE THREAD

**Issue by sagarkul** [swagger-api/swagger-ui#4237]
Current Swagger page, When you hit try it out button.
It shows
Curl, Request URL, Response Body, Response Code and Response Headers

All I want to know is the response time taken by the API.

This will help to check the performance of the API response (time).
Currently, I can go to dev tool and check it on the network tab.
however, it will be convenient if we provide that information along with above results.

**Comment by heldersepu** [comment]
I think that the `displayRequestDuration` is what you need, Right?
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#display

**Comment by webron** [comment]
What @heldersepu said :)

**Comment by sagarkul** [comment]
Great; exactly I was looking for it.
