### ISSUE TITLE
Set Default value using jquery  

### ISSUE THREAD

**Issue by Ali7862** [swagger-api/swagger-ui#4238]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  No
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 2.0
| How did you install Swagger-UI? |  in elixir
| Which browser & version?        | chrome 
| Which operating system?         |  Linux

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior
I need default to set text input value using jquery 

### Context
Please Guide me where I change in code

**Comment by heldersepu** [comment]
You will be better off asking this kind of questions on StackOverflow:
https://stackoverflow.com/questions/tagged/SWAGGER-UI

**Comment by webron** [comment]
We can't provide help with swagger-ui 2.0 anymore, unfortunately.
