### ISSUE TITLE
TypeError: c.concat is not a function

### ISSUE THREAD

**Issue by InfopactMLoos** [swagger-api/swagger-ui#4240]
I added inheritance to my swagger file according to the example on https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/. This somehow triggered an error: ```Resolver errorc.concat is not a function```. I have googled it but this did not give me any results about swagger-ui specifically.

I updated the swagger-ui to the latest version, v3.10.0, but this didn't change anything. 
Any ideas? 

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  x
| Which Swagger/OpenAPI version?  | 2.0 & 3.0
| Which Swagger-UI version?       | v3.10.0
| How did you install Swagger-UI? | composer
| Which browser & version?        | Chrome Version 64.0.3282.167 (Official Build) (64-bit)
| Which operating system?         | Ubuntu Linux 16.04

### Demonstration API definition

This is just a part of the total spec but should be the relevant parts.

```js
{
  "swagger": "3.0.0",
  "info": {
    "version": "1.0.0"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/asset/{assetId}": {
      "parameters": [
        {
          "name": "assetId",
          "in": "path",
          "required": true,
          "type": "integer",
          "pattern": "\\d+",
          "x-example": 1
        },
        {
          "name": "x-customerid",
          "in": "header",
          "required": true,
          "type": "integer",
          "x-example": 1
        },
        {
          "name": "x-username",
          "in": "header",
          "required": true,
          "type": "string",
          "x-example": "test"
        }
      ],
      "get": {
        "tags": [
          "asset"
        ],
        "operationId": "GET_asset-assetId",
        "summary": "Retrieve an asset by id",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "oneOf": [
                {"$ref": "#/definitions/Asset"},
                {"$ref": "#/definitions/Ipdialtone"}
              ]
            }
          },
          "404": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/ResponseMessage"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Asset": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true,
          "description": "Unique identifier for this asset instance",
          "minimum": 0
        },
        "asset_type": {
          "type": "string",
          "description": "Type of asset"
        },
        "customer": {
          "type": "integer",
          "description": "Customer that owns this asset"
        },
        "parent": {
          "type": [
            "integer",
            "null"
          ],
          "description": "Parent asset"
        },
        "start": {
          "type": "string",
          "format": "date",
          "description": "Technical start date, date when this asset was created."
        },
        "end": {
          "type": [
            "string",
            "null"
          ],
          "format": "date",
          "description": "Technical end date, date when this asset was removed."
        },
        "redacted": {
          "type": "boolean",
          "description": "Indicator if this asset has its details hidden"
        },
        "active": {
          "type": "boolean"
        },
        "former_order_id": {
          "type": [
            "string",
            "null"
          ],
          "description": "Legacy system id"
        }
      },
      "required": [
        "asset_type",
        "customer",
        "start"
      ],
      "discriminator": {
        "propertyName": "asset_type"
      }
    },
    "Ipdialtone": {
      "allOf": [
        {"$ref": "#/definitions/Asset"},
        {
          "type": "object",
          "properties": {

          }
        }
      ]
    },
    "AssetCollection": {
      "type": "object",
      "readOnly": true,
      "properties": {
        "offset": {
          "type": "integer",
          "minimum": 0,
          "example": 0
        },
        "limit": {
          "type": "integer",
          "minimum": 1,
          "example": 10
        },
        "total": {
          "type": "integer"
        },
        "_links": {
          "type": "object"
        },
        "_embedded": {
          "type": "object",
          "properties": {
            "assets": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Asset"
              }
            }
          }
        }
      }
    },
    "ResponseMessage": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        },
        "extra": {
          "type": "object"
        }
      },
      "required": [
        "code",
        "message"
      ],
      "example": {
        "message": "Error message",
        "code": 400,
        "extra": {}
      }
    }
  }
}
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
    url: "http://localhost/swagger.json",
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout",
    validatorUrl: null
}
```

### Expected Behavior

I expected a swagger-ui without errors and the documentation showing the schema models.
### Current Behavior

In the top of the ui I see:
```
Errors
Resolver errorc.concat is not a function
Resolver errorc.concat is not a function
```
And in the developer console I see the same error with stacktrace.

Also at the places that normally show the schemas/models I now see empty space.

### Context

Like I said I tried to add inheritance to my existing schema. I followed and mostly copied the example in the link I included above. Since my asset API call can return many different kind of assets with all extra fields depending on the type I need to describe these types individually since the developers implementing the client need more details. Inheritance would be perfect in my case because that would save me a lot of boilerplate.

**Comment by heldersepu** [comment]
at first look: that's not a valid schema...
`swagger": "3.0"`
there is no such an option, see the specs:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md

**Comment by InfopactMLoos** [comment]
Ah ok I just tried 3.0 to rule out version difference. I just checked and updated the spec, still same issue.

**Comment by heldersepu** [comment]
Not sure what your are doing...
`"swagger": "3.0.1"`
is not valid, I think you are mixing OAS2 and OAS3 you can not do that...

**Comment by InfopactMLoos** [comment]
Ok it seems the tag changed in 3.0, I didn't know that. 2.0 used the field swagger to designate the version. If you read my issue I tested with 2.0 and then tried 3.0 to rule out any update that might have fixed the issue. Would have being easier if you just said that instead of pointing to the entire specification. In any case swagger-ui does not seem to care very much because it just renders, maybe it's backwards compatible.
I have found the issue nonetheless. After continuing with the rest of the fields that needed to be added the error appears to be gone. I suspect it had to do with the `properties` being empty as in my example although I think I tried that before. Anyway it is working again so closing the issue.

**Comment by hkosova** [comment]
@InfopactMLoos
1) OpenAPI/Swagger 2.0 (`"swagger": "2.0"`) does not support `oneOf`, it's only supported in OpenAPI 3.0 (`"openapi": "3.0.0"`).

2) This is not a valid type definition (it's valid in JSON Schema but not in OpenAPI):
```
          "type": [
            "string",
            "null"
          ],
```
See [How to define a property that can be string or null in OpenAPI (Swagger)?
](https://stackoverflow.com/a/48114322/113116)
