### ISSUE TITLE
Is there a safe way to hide tags that when expanded have nothing in them?

### ISSUE THREAD

**Issue by marcodarko** [swagger-api/swagger-ui#4243]
Just trying to customize the UI to our specific needs, this layout is currently more complex than I'm used to so I wanna ask a pro.

**Comment by shockey** [comment]
Hi @marcodarko!

I shared a custom plugin that will hide empty tags here: https://github.com/swagger-api/swagger-ui/issues/4157#issuecomment-363917366

Note that you should depend on a specific minor version of Swagger-UI (e.g., `3.10.*`) if you're using the plugin API, as some internal APIs change between minor versions.

**Comment by marcodarko** [comment]
Thank you!
