### ISSUE TITLE
"TypeError: Failed to fetch " in the response using OpenAPI 3.0.0

### ISSUE THREAD

**Issue by iappa1** [swagger-api/swagger-ui#4244]
Hi.
I am trying to create an documentation for an API which needs a basic auth (user/password) and 2 query parametrers. I have written the spec in OpenAPI 3.0.0 format. All good, but in 'try it out' option, I am getting an error like 'TypeError: Failed to fetch' . When I executed generated curl command in terminal, "curl: (60) Peer's Certificate issuer is not recognized " is the error I am getting. 

Generated curl: 
curl -X GET "<my url> "accept: application/xml" -H "Authorization: Basic YXVyb3JhX3Rlc3Q6YXVyb3JhXzU2MzUxJUF1Zw=="

Modified curl:
curl  -k -X GET "<my url> "accept: application/xml" -H "Authorization: Basic YXVyb3JhX3Rlc3Q6YXVyb3JhXzU2MzUxJUF1Zw=="

When I run modified curl, I am getting a response in command line. So Is there anyway I can customize the curlify.js and make the swagger generate the modified curl.

Please help me with this issue. Please note that I am newbie to swagger (started last week).

Thanks in advance.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenApi 3.0.0
| Which Swagger-UI version?       | 
| How did you install Swagger-UI? |  from git
| Which browser & version?        | Chrome
| Which operating system?         | Windows 10

**Comment by hkosova** [comment]
This looks related -- https://github.com/swagger-api/swagger-ui/issues/3239#issuecomment-308331721.

**Comment by iappa1** [comment]
Hi helen,

I tried different ways to  avoid cors errors and finally ended up with a error in the console like 
"Failed to load <my URL> Response for preflight has invalid HTTP status code 400"

PS: 
 ->I have set up a chrome extension for cors. 
 -> I am runnig the swagger UI locally with python server ( also tried online swagger editor, but getting the same error.)
-> I am not sure whether cors is enabled in the server for which I am making a get request.

**Comment by heldersepu** [comment]
@iappa1 cors must be enabled in the "server" for which you are making the get request.

Here are some of my web api that have it:
- http://swagger-net-test.azurewebsites.net/swagger/docs/V1
-  http://offleaseonly.azurewebsites.net/swagger/docs/V1

If cors is enabled you should be able to do something like:
http://petstore.swagger.io/?url=http://heldersepu.github.io/hs-scripts/swagger/4134_swagger.json
That should show the Swagger-UI without any errors

**Comment by iappa1** [comment]
@heldersepu 
Thanks for the info.  Can you please guide me, how can I check whether my server is cors enabled or not. (not in Swaggger - UI).

**Comment by heldersepu** [comment]
Can you post a link to your server?

**Comment by iappa1** [comment]
Actually its my org's domain. I can't do able to do that

**Comment by heldersepu** [comment]
Sorry not much I can do to help in that case...
 I suggest you move to the cloud

Also since this is not a bug close this issue and ask your question on StackOverflow: 
https://stackoverflow.com/questions/tagged/swagger-ui
there is a much bigger audience there

**Comment by shockey** [comment]
@iappa1, as Helder mentioned you need to send CORS preflight headers along with your server responses (most importantly, `Access-Control-Allow-Origin`).

You can find more information about how to go about this here: https://enable-cors.org

**Comment by iappa1** [comment]
Thanks @shockey  and @heldersepu for the help.

I will try enabling CORS at my server side. 

Closing the issue.
