### ISSUE TITLE
How to bypass Available authorizations screen?

### ISSUE THREAD

**Issue by patnolan** [swagger-api/swagger-ui#4247]
When I click the Authorize Button I get the "Available authorizations" dialog for selecting the scope(s) as ecpected. The available scopes are defined in code via AddSecurityDefinition.

However, I would like to bypass this dialog and have the scopes automatically selected. If you have 8 or 10 scopes to check everytime you authorize it can become quite annoying in a dev environment. Could anyone advise how to do this or even provide the necessary code\config?

Thanks heaps!

**Comment by patnolan** [comment]
Ok...I worked out that if I add scopes to the OAuthAdditionalQueryStringParams on UseSwaggerUI rather than to the Scopes property on AddSecurityDefinition, the scopes are used without the need for the user to select them on the Available authorizations screen.

However, how can I bypass the Available authorizations screen all together so the user doesn't even see it?

**Comment by shockey** [comment]
@patnolan, an instance method for programmatically adding authorization data in 3.x is described here: https://github.com/swagger-api/swagger-ui/issues/2915

It's not implemented yet, though.

If you're using Swagger-UI through Swashbuckle, you'd need an interface through Swashbuckle to use the new option, though.

Closing for now - if there's anything else, or I misunderstood something, just reply!
