### ISSUE TITLE
Lazy resolution

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#4248]
### Description

Lazy resolution will allow us to handle larger API definitions more effectively in Swagger-UI.

We currently run entire API definitions through the Swagger-Client resolver when the definition is loaded into the UI. We can save a _lot_ of effort by having the UI request resolved data as needed.

Conveniently, $ref usage is restricted in the Swagger and OpenAPI Specifications, so we can rely on having enough data to populate a list of operations and models without resolving anything, and only resolve things when users interact with the UI.

### Plan

- Create `specActions.requestResolution([...path])`
- Create `specSelectors.getResolvedSubtree([...path])`
- New flow: 
  - requestResolved ->
  - is resolved data cached in state?
    - yes? noop
    - no? async SwC.resolveIn ->
      - update resolved state ->
      - re-render with updated state through `getResolvedSubtree`
- Rework Models & Operations to request and consume resolved subtrees as needed
- Support Swagger-Editor lifecycle in modified rendering (invalidate and re-request resolved subtrees when the spec content updates)
- Move spec metadata out of `resolved` key, into a new `meta` key
- Stop resolving by default (will need to provide an example to folks who will continue relying on `specResolved`)
- Collapse models by default, so they don't need to be resolved until the user interacts with them

**Comment by heldersepu** [comment]
On the "Collapse models by default" there is option to expand to some level
http://petstore.swagger.io/?defaultModelExpandDepth=5&defaultModelRendering=model#/pet/getPetById
After this change we still can use that right?

**Comment by shockey** [comment]
@heldersepu, yes! the default has changed, each model in the models section will collapse by default (level 1 now means “display the container and name, but no content”); this is to avoid needing to do the work until the user expresses their intention to see the model.

how does that feel to you?

**Comment by heldersepu** [comment]
Sounds good.
But this default value still configurable, right? if not then the [configuration](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md) page should be updated

**Comment by heldersepu** [comment]
I think this will address some of the slow loading I'm getting here:
http://petstore.swagger.io/?url=http://nhc-noaa.azurewebsites.net/swagger_ErliSoares.json&filter=_&defaultModelsExpandDepth=5

**Comment by shockey** [comment]
@heldersepu hopefully it will, however modifying the expand depth is going to negate a lot of the benefits 😉

**Comment by heldersepu** [comment]
ohhh I was thinking that the lazy load meant a visual delay... 
...like some sort of animation expanding the models in a lazy way instead of waiting for the full rendered version

**Comment by shockey** [comment]
@heldersepu no worries! it's an ambiguous term 😄 

here's a static build of the changes, you can try them out: http://devilish-coat.surge.sh/#/

**Comment by heldersepu** [comment]
Testing on your build:
http://devilish-coat.surge.sh/?url=http://nhc-noaa.azurewebsites.net/swagger_ErliSoares.json&filter=_&defaultModelsExpandDepth=0
that loads a faster than on the petstore
But if I increase the number to 5 it just crashes...

**Comment by shockey** [comment]
Yeah, I'm seeing that too. I'm playing with it locally, looks like there's a lot of redundant resolving going on with this definition - working on it now. Thanks for the heads up!

On Fri, Feb 23, 2018 at 12:33 PM, Helder Sepulveda <notifications@github.com> wrote:
Testing on your build:
http://devilish-coat.surge.sh/?url=http://nhc-noaa.azurewebsites.net/swagger_ErliSoares.json&filter=_&defaultModelsExpandDepth=0 [http://devilish-coat.surge.sh/?url=http://nhc-noaa.azurewebsites.net/swagger_ErliSoares.json&filter=_&defaultModelsExpandDepth=0]
that loads a faster than on the petstore
But if I increase the number to 5 it just crashes...

**Comment by heldersepu** [comment]
I was thinking that the expanding of the models could be on a timer and inside the timer we do something like: 
`document.getElementsByClassName("model-toggle collapsed")[0].click()`

**Comment by shockey** [comment]
@heldersepu, I like the idea in theory, but the resolver would still be blocking the main thread, so the UI would lock up for a spell without the user initiating work through a click, which feels not-great.

The idea behind that, though (resolving sequentially) may be part of the solution for the spec you provided.

I've isolated the issue to two definitions: `Reserva` and `Patrimonio`. They're either massive, or preserving some type of circular structure, which is causing the thread to crash. I'm not sure if it's a size problem or a loop problem, since I'm getting an out-of-memory error, not a call stack size error.

Stay tuned!

**Comment by heldersepu** [comment]
I guess I have to read on resolvers and how they block the main thread...

But here is a more concrete example on my idea:
Let's start with the page:
http://devilish-coat.surge.sh/?url=http://nhc-noaa.azurewebsites.net/swagger_ErliSoares.json&filter=_&defaultModelsExpandDepth=1
That renders fast 
Then open the browser Dev Tools and in the console paste the following:
```JS
function ExpandModel() {
	const o = document.getElementsByClassName("model-toggle collapsed")
	if (o.length > 0) {
		o[0].click()
		setTimeout(ExpandModel, 100);
	}
}
```
Then all we need to do is execute it `ExpandModel()` that will "slowly" and recursively expand all models without any visible blocking spells

**Comment by shockey** [comment]
@heldersepu gotcha! i'm partial to saying that triggering UI events programmatically would be creating more work then necessary for the UI, but feel free to open a discussion ticket, @webron may have an opinion 😄 

Beyond that... I think I've ironed out the performance issues with the definition you've been looking at. Try this one, @heldersepu: https://halting-coat.surge.sh

**Comment by heldersepu** [comment]
Getting an error on that link: Failed to load API definition.

I just moved to a my laptop and testing my example, I noticed that the fan was kinking in right away...
Triggering those UI events seem to really put a toll on Memory and CPU:
![image](https://user-images.githubusercontent.com/545474/36624257-d8c37660-18da-11e8-9f57-61f3917a0b12.png)

**Comment by shockey** [comment]
@heldersepu, try out https://halting-coat.surge.sh/?url=https://gist.githubusercontent.com/shockey/c62b2370ae3b93c61999158b78eb390b/raw/46e3f01ed576e34250bc6bf04b9e158b9db2b4ce/gistfile1.txt to load the spec you shared earlier.

From my end, the spec initially renders quite fast, and expanding each model takes 0-2 seconds of hard work on the CPU.

Doing the work at UI render time _is_ the idea here, but we do want it to be performant. Let me know if your experience with that definition is very different from mine, or you have another that demonstrates a persisting problem!

**Comment by heldersepu** [comment]
Much Better! the browser does not crash
https://halting-coat.surge.sh/?url=https://gist.githubusercontent.com/shockey/c62b2370ae3b93c61999158b78eb390b/raw/46e3f01ed576e34250bc6bf04b9e158b9db2b4ce/gistfile1.txt&filter=_&defaultModelsExpandDepth=5

Comparing Performance with my UI events idea this approach consumes significantly more memory.
![image](https://user-images.githubusercontent.com/545474/36624456-8ad865a2-18dd-11e8-8d07-194960d4f048.png)

**Comment by heldersepu** [comment]
[halting-coat.surge.sh/.../gistfile1.txt&filter=_&defaultModelsExpandDepth=5](https://halting-coat.surge.sh/?url=https://gist.githubusercontent.com/shockey/c62b2370ae3b93c61999158b78eb390b/raw/46e3f01ed576e34250bc6bf04b9e158b9db2b4ce/gistfile1.txt&filter=_&defaultModelsExpandDepth=5)
35 seconds to fully load

[petstore.swagger.io/.../swagger_ErliSoares.json&filter=_&defaultModelsExpandDepth=5](http://petstore.swagger.io/?url=http://nhc-noaa.azurewebsites.net/swagger_ErliSoares.json&filter=_&defaultModelsExpandDepth=5)
47 seconds to fully load

Not a huge improvement... but I take it.!

You are not buying into the UI events idea, are you?

**Comment by shockey** [comment]
@heldersepu, yep, I'm not quite sold - I don't really see the use case.

As it stands: if you don't need everything on the page on load, then just expand things as you need them; if you do need everything visible, use docExpansion and defaultModelsExpandDepth, you'll have to wait but it'll all be there! Staggering it feels like an odd middle ground to land in, that has the same latency as the manual expansion but without the predictability of CPU cycles happening when the user interacts with the page.

That being said..... Swagger-UI core isn't the end-all-be-all. If you'd like to make a plugin for this functionality, check out [my cornify plugin](https://preview.npmjs.com/package/swagger-ui-cornify) for a starting point.

**Comment by shockey** [comment]
Besides that.... Thanks for the discussion here today! The definition you shared _really_ helped in speeding things up. Excited to ship the fastest Swagger-UI ever 😄

**Comment by shockey** [comment]
fyi, i marked this issue as fixed, but totally happy to keep the discussion going!

**Comment by heldersepu** [comment]
Keeping the discussion going...

With the "UI events idea" the page remains responsive while the models are expanding, with that in mind we could create something like the infinite scroll on the Google images search:
https://www.google.com/search?q=images&source=lnms&tbm=isch
Even if the user sets a high `defaultModelsExpandDepth` we do not need to expand all models right away, perhaps we can wait until the user scrolls down or follows a deep link to a model to do the expand.

Now about my sample definition, it is not mine and I don't  remember who I got it from, but I do remember it was much larger, the original was over 1MB and I managed to reduce it to 40KB ...
So there are developers out there with much larger & complex definitions 
Also my test was with a conservative `defaultModelsExpandDepth=5` if we double that the page will crash

**Comment by heldersepu** [comment]
Looking at the current implementation, the collapsed models show right away:
[petstore.swagger.io/...&url=http://heldersepu.github.io/hs-scripts/swagger/4248_swagger.json](http://petstore.swagger.io/?docExpansion=None&defaultModelsExpandDepth=1&url=http://heldersepu.github.io/hs-scripts/swagger/4248_swagger.json#/)
That is a smaller version of the previous sample definition, but still 50 models.

Expanding small models is quick, but the largest models (such as `Patrimonio` ) takes quite a while, once it shows expanding child models takes no time...
I believe that is because we are loading the entire tree of the model, right?
Maybe lazy loading the model properties on the same way you did the Models is an alternative.

**Comment by heldersepu** [comment]
@shockey  I'm going to create a new issue to improve performance of the model properties

**Comment by Kevin-Prichard** [comment]
@heldersepu, a slight modification to your code produces a single model version. Seldom do I want to open all models at once, especially with a complex API.

Connecting this code to a "toggle all" button next to the %gt; symbol for each model would enable us to manually open just one model entirely.

```
function ExpandModel(modelName) {
	const o = document.querySelectorAll('#model-'+modelName+" .model-toggle.collapsed")
	if (o.length > 0) {
		o[0].click()
		setTimeout(function(){ExpandModel(modelName)}, 100);
	}
}

ExpandModel("YourModelNameHere")
```

**Comment by heldersepu** [comment]
Hi @Kevin-Prichard, I'm glad my code was helpful...
but the problem still exists, if we have a truly complex model it will crash, try with this:
http://swagger-net-test.azurewebsites.net/api/NestedSwag/9

Use your ExpandModel to expand Test0 on that schema, let me know what happens

**Comment by PachowStudios** [comment]
I'm pretty sure this change is what broke our swagger in newer versions. We have a very large definition and rely on splitting up the paths into multiple files.

This used to work in v3.9:
```yaml
paths:
  allOf:
    - $ref: 'common/errors.yaml#/paths'
    - $ref: 'common/versions.yaml#/paths'
    - $ref: 'users/users.yaml#/paths'
    # etc... there's nearly 30 files total
```

Now in the newer versions, swagger just says there's no operations defined.

**Comment by PachowStudios** [comment]
@heldersepu We can't be stuck on 3.9 forever. That isn't really a long term solution.

I've attached a minimal reproduction. If you downgrade to 3.9.2, it works fine.
[swagger-bug.zip](https://github.com/swagger-api/swagger-ui/files/2233400/swagger-bug.zip)

**Comment by heldersepu** [comment]
@PachowStudios For sure someone will look into your issue!

I was able to reproduce it:
Old version is OK:
http://offleaseonly.azurewebsites.net/swagger/ui/index?url=https://raw.githack.com/heldersepu/hs-scripts/master/swagger/4248/index.yaml

Latest shows No operations defined in spec!
http://petstore.swagger.io/?url=https://raw.githack.com/heldersepu/hs-scripts/master/swagger/4248/index.yaml

You should probably open a new issue
