### ISSUE TITLE
Issue in downloading/viewing the PDF content with content type "application/pdf" and "application/octet-stream" in Swagger 3.0

### ISSUE THREAD

**Issue by balaji-tech87** [swagger-api/swagger-ui#4250]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       | 3.X
| How did you install Swagger-UI? | 
| Which browser & version?        | Chrome
| Which operating system?         |  Windows

### Demonstration API definition

Case 1:
responses:
        '200':
          description: "".
          content:
            application/pdf:
              schema:
                type: string
                format: binary

Case 2:
responses:
        '200':
          description: "".
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

### Configuration (browser query string, constructor, config.yaml)

Case1:
curl -X GET "http://localhost:8080/rest/*****true" -H "accept: application/pdf"

Case2:
curl -X GET "http://localhost:8080/rest/*****true" -H "accept: application/octet-stream"

### Expected Behavior
It should either display the PDF content in the browser or it should provide link to download the file.
And with the same curl command returns the download prompt for pdf file, while trying in postman tool.

### Current Behavior

Case 1:
It throws Not acceptable error - 406.

Case 2:
It throws 200 - Unknown response type.

### Context
Writing an api to download the PDF content
![case-1_error](https://user-images.githubusercontent.com/31892403/36587105-0b1f7388-18aa-11e8-8cae-e3939e1f23a2.JPG)
![case-2_error](https://user-images.githubusercontent.com/31892403/36587106-0b722740-18aa-11e8-9218-8439888a3e30.JPG)

**Comment by webron** [comment]
You haven't specified which version of swagger-ui.

Also, in this case, without a live server for us to test against, it would be difficult to reproduce.

**Comment by hkosova** [comment]
@balaji-tech87 your example works fine for me using Swagger UI 3.11.0 and PDFs on GitHub. The response section displays the "Download file" link.

The issue is likely with your server.

<br/>

![PDF download link](https://user-images.githubusercontent.com/8576823/36748921-56da3584-1c0a-11e8-8eca-7098dbd762f8.png)

```yaml
openapi: 3.0.0
info:
  title: PDF test
  version: 0.0.0

servers:
  - url: https://raw.githubusercontent.com

paths:
  /mozilla/pdf.js/master/examples/helloworld/helloworld.pdf:
    get:
      responses:
        '200':
          description: A PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            application/octet-stream:
              schema:
                type: string
                format: binary
```

**Comment by shockey** [comment]
Hi @balaji-tech87!

I ran @hkosova's example through a web proxy that modified GitHub's `Content-Type: application/octet-stream` to be `Content-Type: application/pdf`, and I was able to reproduce the `Unknown response type` error.

<img src='https://shipusercontent.com/5f79f0a9f4e359c6fa4105769a39df67/Pasted%20Image%201.png' title='Pasted Image 1.png' width=1792>

---

> It should either display the PDF content in the browser or it should provide link to download the file.

Swagger-UI does not support inline viewing of PDFs, nor do I expect it to do so in the future. PDF rendering is not easy to do consistently in a web application, and even then it requires heavy libraries.

Swagger-UI does allow for file downloading, as you know - however you'd need to either send `Content-Type: application/octet-stream` or `Content-Disposition: attachment;` to indicate that your response body should be downloaded by the user agent. 

Learn more about `Content-Disposition` [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition).

**Comment by balaji-tech87** [comment]
Hi Team,
Thanks for your quick suggestions by reproducing the issue.
I also have tried by setting **Content-Type: application/octet-stream and with Content-Disposition: attachment**. The pdf link is enabled and it gets downloaded by clicking it.
And thanks for confirming, Swagger-UI doesnot support inline viewing of PDF.

Suggestions:
If possible, please update the spec that "application/octet-stream" needs to used instead of "application/pdf".
Spec Link : https://swagger.io/docs/specification/describing-responses/
Under section : Response That Returns a File

**Comment by balaji-tech87** [comment]
Thanks. Closing the ticket. I will raise new ticket, if any further clarification required. Thanks for your support.
