### ISSUE TITLE
GUID generated by Sql Server doesn't pass validation

### ISSUE THREAD

**Issue by johoye** [swagger-api/swagger-ui#4251]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.10.0
| How did you install Swagger-UI? | NuGet
| Which browser & version?        | Chrome 63.0.3239.132
| Which operating system?         | Windows 10

### Demonstration API definition
![image](https://user-images.githubusercontent.com/5715933/36597769-7dca49da-18aa-11e8-8bd8-3293120c4d1a.png)

### Expected Behavior

6ffefd8e-a018-e811-bbf9-60f67727d806 should be recognized as a valid GUID when used as a parameter. This GUID was generated by SQL Server and should regarded as valid.

### Current Behavior

The following error is produced: "Value must be a Guid"

### Possible Solution

In utils.js in the method validateGuid(val) the RegEx could be changed to allow [0-9a-f] for all characters. Currently there are restrictions to the first character in both of the character-groups 3 and 4

**Comment by heldersepu** [comment]
Looking into it: 

We have regEx to trigger that message
```js
!/^[{(]?[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}[)}]?$/.test("6ffefd8e-a018-e811-bbf9-60f67727d806")
true
!/^[{(]?[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}[)}]?$/.test("8f25150a-cc88-455a-852b-27c1a86972e2")
false
```

**Comment by heldersepu** [comment]
Here are some details from http://guid.us/

>Version one (V1) GUIDs which have a network MAC address embedded and can be recognized by the digit '1' in the third group of digits, for example {644e1dd7-2a7f-18fb-b8ed-ed78c3f92c2b}. 

>Version four (V4) GUIDs use a different algorithm, which is a random number. Where a '4' is in the same position (third group of digits), for example {20380a36-8777-43f7-a79e-65bdb53f4621}. Because of this pattern if a hacker knows the internal state, it is possible to generate the same GUIDs on another system.

If we strictly follow that your GUID does not comply:
6ffefd8e-a018-`e`811-bbf9-60f67727d806

But I guess I should allow any possible GUID in the UI and let the backend be more restrictive...
