### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by LEsperanca** [swagger-api/swagger-ui#4277]
Hi all,

I'm very newbie about node, js and all its ecosystem, so bare with me. I'm trying to debug swagger-ui but I'm having trouble to understand how to debug the application.
I can i debug swagger-ui?

Can i feed a json locally? How? Swagger ui supports Swagger and OpenAPI ? Supports json and yaml?

Thanks in advance

**Comment by Nur777** [comment]
Yes, yes, yes.
Read here please:
https://swagger.io/docs/swagger-tools/#download-33

**Comment by LEsperanca** [comment]
@Nur777 Thanks!
