### ISSUE TITLE
Multiline textbox for header parameter

### ISSUE THREAD

**Issue by jonnyry** [swagger-api/swagger-ui#4278]
I'm trying to get a multiline textbox (`textarea`?) for a header parameter - I have a sizeable header parameter which would benefit from being displayed over more than one line.

Could anyone suggest a way to get a `textarea` for a header parameter?  Do I need to modify Swagger UI before its built?

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature/support request
| Which Swagger/OpenAPI version?  | Swagger 2.0
| Which Swagger-UI version?       | Swagger UI 3.10
| How did you install Swagger-UI? | Download from GitHub
| Which browser & version?        | All
| Which operating system?         | All

### Background ###

I have a fairly awkward API I'm trying to represent in Swagger UI - one of the parameters is a big hulk of JSON that's turned into a base64 string before being sent as an HTTP header over the wire.

I'd like to show the header parameter for the user to see in JSON before it's converted to base64 and sent - the conversion part I have cracked by using the `requestInterceptor` parameter of the SwaggerUIBundle object and converting to base64.

However I haven't been able to find an acceptable solution to display the header parameter in a multiline text box (`textarea`) so the JSON can be properly viewed and edited - I've tried multiple avenues of attack including using javascript, however that particular one interferes with the React rendering. 

Many thanks.

**Comment by jonnyry** [comment]
Found a way to do it, though it's rather hacky:

Above this else clause in `src/core/json-schema-components.js`

```
    else {
        return (<DebounceInput
                       type={ schema.format === "password" ? "password" : "text" }
```

Add the following:

```
    else if (schema["name"] === "parameter_name_to_use_text_area") {
      return (<DebounceInput
                     element="textarea"
                     className={ errors.length ? "invalid" : ""}
                     title={ errors.length ? errors : ""}
                     value={value}
                     minLength={0}
                     debounceTimeout={350}
                     placeholder={description}
                     onChange={ this.onChange }
                     disabled={isDisabled}/>)
    }
```

If anyone can suggest a way that can be done without modifying the source (or using the parameter name to determine whether to produce a textarea or not), I'd appreciate your comment.

**Comment by heldersepu** [comment]
I think the same could be said for any big (non body) parameter, but there are limits for those params...

The url portion of a request can be limited by both the browser and the server.. 
to keep it safe, size should be under 2KB 

Most web servers limit the size of headers. 
- Apache default limit is 8KB, 
- Microsoft IIS it's 16K 

Server will return 413 Entity Too Large error if headers size exceeds that limit.

With that in mind  I would recommend you that anything sizable should go on the body

**Comment by jonnyry** [comment]
Yes agreed, though the JSON field I mention is max 1KB split over multiple lines (before its converted to base64), which still is un-editable in a regular textbox.

I've found a slightly cleaner way to enable textarea support without resorting to testing by name by using an x-* extension in the swagger definition file: 

          `x-multiline: true`

then the if clause above becomes:

          `else if (schema["x-multiline"]) {`

**Comment by heldersepu** [comment]
Sound like you have done all the research and coding...
Send a PR and let's see how the owners feel about this change.

**Comment by shockey** [comment]
FWIW, I think an `x-multiline` hint would be cool 😄

**Comment by webron** [comment]
@jonnyry - closing the issue as it seems you have found a solution. If you need this reopened for further discussion, simply add a note here.
