### ISSUE TITLE
Swagger-UI Not Loading After Merging My Local Branch With Up-To-Date Master

### ISSUE THREAD

**Issue by srpalomino** [swagger-api/swagger-ui#4288]
Hello all!

After the merge, I get the following error messages:

1. No layout defined for standaloneLayout.
2. tachyons.scss is not found or is unreadable.

I looked for tachyons.scss in the project directory, but I didn't find it. 

Does anyone know why Swagger isn't loading?

You can clone [my repo](https://github.com/srpalomino/swagger-ui/tree/ft/3958-make-deeplinking-dynamic) for further investigation.

Thanks!

**Comment by shockey** [comment]
@srpalomino, Tachyons was added as a dependency in the latest version - try running an `npm install` so your local Swagger-UI picks it up.

Let me know if that helps!

**Comment by srpalomino** [comment]
@shockey You helped solve not just one problem, but two!

Thanks again for all your help :+1:
