### ISSUE TITLE
How is dist/index.html built?  Specifically, where is webpack getting it the template to this file? 

### ISSUE THREAD

**Issue by mikefidel** [swagger-api/swagger-ui#4289]
I'm a webpack novice, but yet have seriously (!) tried to figure out where dist/index.html file comes from.  The dist folder is deleted upon every "npm run build".  There are several webpack config files, but as much as I have looked, I can't figure out where the template to dist/index.html comes from.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Support
| Which Swagger/OpenAPI version?  | 3.12.0
| Which Swagger-UI version?       | 3.0
| How did you install Swagger-UI? | clone from github
| Which browser & version?        | Chrome
| Which operating system?         | Windows

### Context

At the moment I copy the dist folder into an AWS bucket, and over-write the built index.html with a variant that includes plugins.  I'd like to automate this using a git branch and a customized index.html that includes an additional plugin function and a SwaggerUIBundle object with a non-default url: value.

To be candid, I've felt this is a dumb question and thus spent a lot of time learning webpack and swagger-ui builds.  Not getting anywhere, I thought it was best to just ask...

Longer term, I want to display an api related to an academic commons database used by researchers around the globe.  I thought I'd keep in on Github pages.

**Comment by shockey** [comment]
Hi @mikefidel! You aren't missing anything - the html assets are manually managed. Webpack does not touch it :smile: 

I know that it's a bit unintuitive to have manually created files in `dist`; we kept `index.html` there for compatibility with previous versions.

**Comment by mikefidel** [comment]
Oooh ... I think I need a drink!  You have no idea how many hours I researched this and couldn't come up with an answer.

Thanks for the input, though.
