### ISSUE TITLE
Use swagger-ui in a react app / petstore

### ISSUE THREAD

**Issue by r-ising** [swagger-api/swagger-ui#4291]
Hello,

I created a small react app with swagger ui:

https://github.com/r-ising/SwaggerCustomLayout

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.12.0
| How did you install Swagger-UI? | npm install swagger-ui
| Which browser & version?        | Chrome 64
| Which operating system?         | macOS

### Demonstration API definition

http://petstore.swagger.io/v2/swagger.json

### Expected Behavior

petstore should be work without errors in a sample project.

### Current Behavior

I get the following error in console of chrome:

```
Warning: Failed prop type: The prop `schema` is marked as required in `t`, but its value is `undefined`.
    in t (created by t)
    in t (created by r)
    in r
    in Connect(r) (created by t)
    in section (created by t)
    in t (created by t)
    in div (created by t)
    in t (created by t)
    in div (created by t)
    in div (created by t)
    in t (created by r)
    in r
    in Connect(r) (at CustomLayout.js:17)
    in div (at CustomLayout.js:13)
    in CustomLayout (created by r)
    in r
    in Connect(r) (created by t)
    in t (created by r)
    in r
    in Connect(r) (created by r)
    in Provider (created by r)
    in r
```

### Possible Solution

Fix swagger.json of petstore or fix swagger-ui?!

### Context

I would like to create a custom layout for the react ui.

Why is the petstore not working in my sample project? How can i fix it? I didn't find any additional information about the error..

**Comment by dcatoday** [comment]
I am also seeing this issues.

**Comment by abaldwin88** [comment]
I received the same `prop 'schema' is marked as required ...` error with the JSON posted below.  I downgraded swagger-ui to version 3.10.0 and the error is gone.

```
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "MyApp",
        "description": "My API",
        "contact": {
            "email": "support@myapp.com"
        }
    },
    "tags": [
        {
            "name": "pet",
            "description": "Pets operations"
        }
    ],
    "host": "api.myapp.com",
    "basePath": "",
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {},
    "definitions": {
        "Pet": {
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "name": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Comment by SauravKarmakar** [comment]
+ 1

**Comment by shockey** [comment]
Seeing this as well, this is the unminified wrapper:

```js
Warning: Failed prop type: The prop `schema` is marked as required in `ModelWrapper`, but its value is `undefined`.
    in ModelWrapper (created by Models)
    in Models (created by _class)
    in _class (created by Connect(_class))
    in Connect(_class) (created by BaseLayout)
    in section (created by Col)
    in Col (created by BaseLayout)
    in div (created by Row)
    in Row (created by BaseLayout)
    in div (created by BaseLayout)
    in div (created by BaseLayout)
    in BaseLayout (created by _class)
    in _class (created by Connect(_class))
    in Connect(_class)
    in section (created by Container)
    in Container
    in StandaloneLayout (created by _class)
    in _class (created by Connect(_class))
    in Connect(_class) (created by App)
    in App (created by _class)
    in _class (created by Connect(_class))
    in Connect(_class) (created by _class2)
    in Provider (created by _class2)
    in _class2
```

**Comment by shockey** [comment]
Clicking this over to bug

**Comment by torbenkorb** [comment]
Same here :( 
Could it be a simple typo schemes/schemas? 
See https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/models.jsx#L17

**Comment by shockey** [comment]
fixed! thanks for reporting 😄

**Comment by r-ising** [comment]
Hi @shockey , 

I upgraded my demo project and the error is gone, thanks for that.
(https://github.com/r-ising/SwaggerCustomLayout)

Now I have a "new" problem with the pet store:

I would like to use the GET /pet/{petId} function, I click "Try it out" then I enter a petId (for example 123) and at least I click "execute".
Now the "petId" input field is red and the id 123 is gone.. 

What did I wrong?

Thanks

**Comment by YaGen** [comment]
@r-ising 
I have the same issue, still not fixed

**Comment by YaGen** [comment]
@r-ising 
version 3.5.0 works fine for me, try it

**Comment by r-ising** [comment]
@YaGen its a problem between v3.10 and v3.11, i created a new issue...
