### ISSUE TITLE
<Deeplink> should not be used to implement deeplinks

### ISSUE THREAD

**Issue by srpalomino** [swagger-api/swagger-ui#4294]
Hello All!

I noticed something recently.

Given that 

- swagger.json is the only interface by which a user adds text to an API definition
- deeplinks are a part of a definition's text
- the only mark up allowed in swagger.json is sanitary html.
- The deeplink component is not sanitary html

Due to all these reasons, I think the deeplink component shouldn't be used to implement deeplinks. Instead I recommend we continue using anchor elements.

I welcome any feedback!!

**Comment by heldersepu** [comment]
Sorry but What problem are you trying to solve?
Can you provide an example?

**Comment by srpalomino** [comment]
@heldersepu Sorry about the confusion

My goal is to use a deep link in the value of the description key in swagger.json.

To do this, I use `<Deeplink>`:
` description: "This is <Deeplink enabled=true path='#/tag' text='my deep link'" /> `

However, this will not work since react components cannot be used in swagger.json.

Therefore, `<Deeplink>` should be removed from the code base since it can't be used in swagger.json. Instead, I recommend using `<a>` to implement deep links since it is legal to use it in swagger.json.

**Comment by shockey** [comment]
@srpalomino, `Deeplink`, at the end of the day, is rendered on the page as an `<a>`. It's used as an abstraction within Swagger UI so that we don't have implementation details of Deeplinks lying around everywhere.

You're free to use `<a>` in your Markdown to create deep links, as we discussed not long ago 😄
