### ISSUE TITLE
swagger-ui sends request with List<Map<String,String>> when controller annotated with "@RequestParam Map<String, String> params"

### ISSUE THREAD

**Issue by urvish-everbridge** [swagger-api/swagger-ui#4296]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 
| Which Swagger-UI version?       |2.8.0
| How did you install Swagger-UI? | spring fox maven dependency
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior
We expect that swagger-ui sends the requests with standard request params in the Map format as described in controller

### Current Behavior
We are using @RequestParam Map<String, String> params in one of the controller methods, when we execute requests from swagger-ui, we get params in the form of List<Map<String,String>> " instead of Map<String,String> params type

**Comment by webron** [comment]
That's a question for springfox, not swagger-ui.
