### ISSUE TITLE
Multiple Routes per Action function

### ISSUE THREAD

**Issue by VikingExplorer** [swagger-api/swagger-ui#4297]
I've got multiple routes per method.  

The UI is showing each route separately.  Is there a way to control that?

Also, is there a way to control what description get's associated with each Route?

swagger": "2.0"

If you're going to iterate through multiple routes, there should be some way to control which document they go into. 

### Context

For example:

        [Route("User")]
        [Route("ユーザー")]
        [ApiExplorerSettings(GroupName = "User")]

Obviously, the multiple routes on the same action have exactly the same behavior. So, what is the point of adding an ui entry for each?  

Perhaps the iteration of routes should be listed inside an entry for an Action, with the name of the action being the first Route?

As you can see, we're using routes to localize the API.  In this case, there would be some value to being able to create Japanese API documentation.

Perhaps, there should be a way to associate Routes with a certain document?  For example:

        [ApiExplorerSettings(RouteGroup = "User:User.EN", RouteGroup="ユーザー:User.JA")]

**Comment by heldersepu** [comment]
This is interesting && funny, I'm assuming you inherited the code with the multi-routes

> Obviously, the multiple routes on the same action have exactly the same behavior.
> So, what is the point of adding an ui entry for each?

I'm sure there is a good reason try to find out what is the point of adding multiple routes?

___

The UI does nothing more than show what you have on your spec, if you want something out of the UI just remove it from your spec...


Also please complete the template when filling the issue, that is very helpful to point you on the right direction, you probably using a 3rd party library to install Swagger-UI you should also ask them how to remove the "duplicates" from the spec

**Comment by VikingExplorer** [comment]
Disappointed in the snark. I did not inherit this. I'm writing it that way. I provided enough information to explain why I'm doing it this way. It's a valid use case.

I installed https://github.com/domaindrivendev/Swashbuckle.AspNetCore

I'm sorry if I incorrectly assumed that this was related to the UI.
