### ISSUE TITLE
Impossible to include base64 encoded imager in info.description section

### ISSUE THREAD

**Issue by nekloth** [swagger-api/swagger-ui#4298]
When trying to include base64 encoded images in API description, 
```<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />```

the generated HTML seems to be sanitized:
```<img>```

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.x
| How did you install Swagger-UI? | /dist folder, on a webserver of my own
| Which browser & version?        | Chrome 64
| Which operating system?         | Windows 10

### Demonstration API definition

```yaml
swagger: "2.0"
info:
  description: |
    This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
    For this sample, you can use the api key `special-key` to test the authorization
    filters.
    <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
  
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
```

### Configuration (browser query string, constructor, config.yaml)
Default configuration

### Expected Behavior
The expected result is to have a red dot drawn in the description. 

### Current Behavior
Nothing is drawn, probably due to Sanitize and XSS risks (see issues #830, #3847 , etc..)

### Possible Solution
Can it be authorized without any injection risks? Can it be a setting?

### Context

For company internal policies and file distribution reasons, I would to add some pictures (team and company logo) inside the API description.

This can be done using a classical IMG html tag refering to an external file.

But I really need to keep the YAML file autonomous (for distribution reason).

**Comment by heldersepu** [comment]
We use sanitize-html with a few custom options:
https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/providers/markdown.jsx#L41

Maybe we should ask the question of  XSS risks on the sanitize-html project?

**Comment by nekloth** [comment]
Question asked.

According to the doc (thanks @heldersepu for the direct link) and the issue [159](https://github.com/punkave/sanitize-html/issues/159), the setting to apply could be ```allowedSchemes: ['http', 'https', 'ftp', 'mailto', 'data']``` to allow data.

Is that something we could imagine to have in Swagger UI?

**Comment by nekloth** [comment]
If you do that, you will introduce a regression! 
Today, you can have http and https, as I was able to include external pictures, referenced by a full URL.

So, to extend by adding just data, the setting should be:  ```allowedSchemesByTag: { img: [ 'http', 'https', 'data' ] }```.

I don't see other tag that may need it.

**Comment by heldersepu** [comment]
Will have to test this... 
but i believe that the allowedSchemes & allowedSchemesByTag work in an additive way.
the default is:
`allowedSchemes: [ 'http', 'https', 'ftp', 'mailto' ]`
and if we do 
`allowedSchemesByTag: { img: [ 'data' ] }`
We are allowing one more scheme to that specific tag

**Comment by nekloth** [comment]
Ok. You seem to be sure, so 👍

**Comment by heldersepu** [comment]
@nekloth you were right we need the: 
`allowedSchemes: ['http', 'https', 'ftp', 'mailto', 'data']`
I submitted a PR, let's see what the team decides...

**Comment by nekloth** [comment]
Ok, great.

Thank you for your help!
