### ISSUE TITLE
BigInteger values are converted to scientific representation

### ISSUE THREAD

**Issue by malkochoglu** [swagger-api/swagger-ui#4306]
Hi,
I have 26 digit BigInteger type id fields. They are converted to scientific representation like
23498230948230948048230482394 - > 2.018030611410829e+25
So any solutions/advice to this except for mapping to String? Or am I missing something ?
TIA...

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       | 2.7.0
| How did you install Swagger-UI? | Maven + Spring Boot
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by heldersepu** [comment]
Try to find out who is doing the conversion, your Api, Swagger-Ui or the browser?
Also please fill in the blanks in the issue template

**Comment by webron** [comment]
@malkochoglu 2.7.0 is not the swagger-ui version, it's springfox. We don't maintain what they do or what they provide, and don't know which version of swagger-ui they actually provide.

Also, BigInteger is not a thing when it comes to the specification. It's up to Springfox to decide how to represent it in your API definition, which again, is not within our scope.

The only way we can help you is if you share the actual version of swagger-ui you're using (and all the instructions are provided in the issue template), and the actual API definition you're trying to load, and not whatever it is you have in your code. When you gather all the details, please file a new ticket following the entire instructions in the issue template.
