### ISSUE TITLE
Can we change the host and add a generated token by js in the new SwaggerUI?

### ISSUE THREAD

**Issue by LuoPQ** [swagger-api/swagger-ui#4308]
With the swagger 2.0, we can use the following code to set host and add a token, can we do that in swagger 3.0?
```
window.swaggerUi.api.setHost(host);
window.swaggerUi.api.clientAuthorizations.add("oauth", new SwaggerClient.ApiKeyAuthorization('Authorization', 'Bearer ' + accessToken, 'header'));
```

**Comment by LuoPQ** [comment]
use `requestInterceptor`  can do that, thanks anyway

**Comment by LuoPQ** [comment]
Is there any better way to do this?

**Comment by shockey** [comment]
the `ApiKeyAuthorization` method is a pending feature, in the meantime there are some workarounds in https://github.com/swagger-api/swagger-ui/issues/2915 that you can use! :smile: 

Closing as a duplicate.
