### ISSUE TITLE
Unable to read api from path (server returned undefined), 302 Found

### ISSUE THREAD

**Issue by sverhagen** [swagger-api/swagger-ui#431]
I have a Spring MVC, Spring Security application that is set up with form authentication, and a JSESSIONID cookie. I dropped a Swagger UI (latest from master) in the secured path, such as:

```
http://localhost:8080/incidentmanager/frontend/app/lib/swagger-ui/index.html
```

Open up the Swagger UI, enter my Swagger API path, press _Enter_ and it loads the overview of resources.

```
GET http://localhost:8080/incidentmanager/rest/api-docs 200 OK
```

The resources are listed, pretty much as expected.

However, none of the API documentation of the resources can be loaded, getting the following error message:

![swagger ui 2014-03-22 22-59-38](https://f.cloud.github.com/assets/2049860/2492753/5b766a54-b250-11e3-9095-85a074cbb9e6.png)

Looking in the console I see the following error:

```
GET http://127.0.0.1:8080/incidentmanager/rest/api-docs/external/com_sun_proxy_Proxy130 302 Found
```

I do notice that the request header for `api-docs` includes a JSESSIONID cookie: `Cookie JSESSIONID=D20C080E296E6EF38B46AD9B062C5D91`, whereas the request header for the endpoints doesn't. Is my problem that the subsequent calls don't pass the JSESSIONID along? If so, how can I fix that?

Observed this with Firefox and Chrome.

Help much appreciated!

**Comment by weichenjushi** [comment]
may be you could try this,
http://127.0.0.1:8080/incidentmanager/frontend/app/lib/swagger-ui/index.html

**Comment by sverhagen** [comment]
Like I said, upgrading resolved the problem for me, so all is good now. If you're experiencing a similar problem, and upgrading doesn't resolve your problem, I think you should open up a new issue. Have a great day.

**Comment by Richardphp** [comment]
I have a similar proble.
It warn:

> Unable to read api 'adver' from path http://mycodeserver.com/docs/json/adver.json (server returned undefined)

But, my colleagues can  open it and everything is ok.I don't know what about this.

**Comment by arivatibm** [comment]
I just started to see the same issue today
any leads ?
