### ISSUE TITLE
Hybrid flow support missing

### ISSUE THREAD

**Issue by enriketrujillo** [swagger-api/swagger-ui#4310]
Im using IdentityServer 4 with the HybridAndClientCredentials grant type. In swagger the clientCredentials flow is working fine but authorizationCode isn't because id_token is missing in the response_type. Is there a way to solve that issue?
Thanks

**Comment by webron** [comment]
I don't know what hybrid flow is - but it's not one of the 4 flows supported by the spec itself, so I don't see us adding support for it in swagger-ui. If you'd like to see support added to it, you'd need to file a ticket with the spec itself.
