### ISSUE TITLE
SwaggerUIStandalonePreset is not defined 

### ISSUE THREAD

**Issue by marcodarko** [swagger-api/swagger-ui#4316]
I'm super new to Swagger so I'm sorry if this has been answered already, I looked everywhere but couldn't find what I needed.

I want to embed the UI in my own project, and I used unpkg to do so as whown here:
[unpkg](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md)

I get the following:

> Uncaught ReferenceError: SwaggerUIStandalonePreset is not defined
> at window.onload

this is what my code looks like:

```
<script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
  <!-- `SwaggerUIBundle` is now available on the page -->
  <script>

  window.onload = function() {

    // Build a system
    const ui = SwaggerUIBundle({
      url: "http://petstore.swagger.io/v2/swagger.json",
      dom_id: '#swagger-ui',
      deepLinking: true,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      plugins: [
        SwaggerUIBundle.plugins.DownloadUrl
      ],
      layout: "StandaloneLayout"
    })
    window.ui = ui
  }
  </script>
```

My end goal is to be able to customize the UI and remove ht topbar and add some custom graphics.
Is this possible?

**Comment by marcodarko** [comment]
Forgot to mention I'm working with a python backend and vueJS, if that makes any difference.

**Comment by heldersepu** [comment]
Looking at my samples on the code I have:

```html
<script src="swagger-ui-bundle-js"> </script>
<script src="swagger-ui-standalone-preset-js"> </script>
```

**Comment by marcodarko** [comment]
I should also mention that I would ideally like to link to those js files in case they update it instead of having them in my source code.

**Comment by marcodarko** [comment]
I got it working including them in my code but wondering if there's a way to not do that.  Seems to be proving quite difficult since I'm not working on a Node app.

**Comment by marcodarko** [comment]
Turns out if I comment out the **SwaggerUIStandalonePreset** and **layout: "StandaloneLayout"** removes the TopBar which I wanted and no need to get the preset js file which I wanted to remove dependencies.  All left was the css and it works perfectly. 

```
<script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
  <!-- `SwaggerUIBundle` is now available on the page -->
  <script>

  window.onload = function() {

    // Build a system
    const ui = SwaggerUIBundle({
      url: "http://petstore.swagger.io/v2/swagger.json",
      dom_id: '#swagger-ui',
      deepLinking: true,
      presets: [
        SwaggerUIBundle.presets.apis,
        //SwaggerUIStandalonePreset
      ],
      plugins: [
        SwaggerUIBundle.plugins.DownloadUrl
      ],
      //layout: "StandaloneLayout" 
    })
    window.ui = ui
  }
  </script>
```

**Comment by Balagii** [comment]
complete working example here: https://github.com/sunnyagarwal008/setup-swagger-ui-in-one-page/blob/master/swagger-ui.html
