### ISSUE TITLE
When docExpansion full, under certain circumstances requestResolvedSubtree not called on initial render

### ISSUE THREAD

**Issue by scottohara** [swagger-api/swagger-ui#4318]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.12.1
| How did you install Swagger-UI? | `git clone && npm run dev`
| Which browser & version?        | Chrome 66
| Which operating system?         | macOS 10.13.3

### Demonstration API definition
http://petstore.swagger.io/v2/swagger.json

### Configuration (browser query string, constructor, config.yaml)

This is admittedly a **very narrow edge case**, and as such should be considered low priority.  There is an effective workaround below.

The prerequisites to reproduce the issue are:

1. API definition **MUST** be supplied using the `spec` config property (not loaded from a `url`)
2. `docExpansion` **MUST** be set to "full"
3. `ui.initOAuth()` **MUST NOT** be called

Here's an excerpt from `dev-helpers/index.html` with the three prerequisites applied:

```js
  window.onload = function() {
    window["SwaggerUIBundle"] = window["swagger-ui-bundle"]
    window["SwaggerUIStandalonePreset"] = window["swagger-ui-standalone-preset"]
    // Build a system
    const ui = SwaggerUIBundle({

      // 1. API definition MUST be supplied using spec, not url
      spec: { <paste contents of petstore JSON here> },

      // 2. docExpansion MUST be set to "full"
      docExpansion: "full",

      dom_id: '#swagger-ui',
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      plugins: [
        SwaggerUIBundle.plugins.DownloadUrl
      ],
      layout: "StandaloneLayout"
    })

    window.ui = ui

    // 3. initOAuth MUST NOT be called
    /*ui.initOAuth({
      clientId: "your-client-id",
      clientSecret: "your-client-secret-if-required",
      realm: "your-realms",
      appName: "your-app-name",
      scopeSeparator: " ",
      additionalQueryStringParams: {}
    })*/
  }
```

### Expected Behavior
API renders with all operations expanded

### Current Behavior
All operations display a loading spinner, but none of them resolve on their own.

Clicking _any_ operation (to collapse it) triggers the `toggleShown` function (in `OperationContainer.jsx`), which then causes all operations to correctly resolve.

It appears that one of the side-effects of calling `ui.initOAuth()` is that the `componentWillReceiveProps()` callback on the OperationContainer is triggered, which requests subtree resolution for all paths.

If `ui.initOAuth()` is commented out, the request for subtree resolution doesn't happen automatically; and requires a user action (such a collapsing one of the operations) to trigger it.

### Workaround
Obviously one workaround is to **always** ensure that `ui.initOAuth()` is called (even if no OAuth config is supplied); but it seems that we may be unknowingly relying on the side-effect of this call for the full-expansion to render correctly.

It is unclear (to me) why this only seems to affect API definitions loaded via `spec` and not via `url`. Presumably there is another similar side-effect at the end of the URL download that triggers a re-render/prop change.

**Comment by shockey** [comment]
One tricky bit about `componentWillReceiveProps` is that it doesn't fire on the first (i.e., mounting) render:

<img width="836" alt="messages image 1882999389" src="https://user-images.githubusercontent.com/680248/37750656-6996316c-2d4b-11e8-99a7-75a325265294.png">

I just opened a PR that duplicates the request logic in `componentDidMount` 😄 

Still not a huge fan of having this in lifecycle methods at all, but I also didn't come up with a better idea, so...

**Comment by shockey** [comment]
Fixed 🎉
