### ISSUE TITLE
"example: undefined" on Model tab in responses

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#4319]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug
| Which Swagger/OpenAPI version?  | 2.0 (but not 3.0)
| Which Swagger-UI version?       | 3.12.1
| How did you install Swagger-UI? | http://petstore.swagger.io
| Which browser & version?        | Chrome 64
| Which operating system?         | Windows 7

If a model property does not have an `example`, then the "Model" tab in Responses displays this property with "example: undefined".

The issue does not happen on the "Model" tab of body parameters, and in the "Models" section at the bottom.

### Demonstration API definition
Petstore - http://petstore.swagger.io/v2/swagger.yaml
Expand the `GET /pet/{petId}` operation.

### Expected Behavior
If a property does not have an `example`, do not display the "example: " text in the property documentation on the Model tab.

### Current Behavior
![image](https://user-images.githubusercontent.com/8576823/37334571-5244533e-26bd-11e8-94e9-aababb1925e6.png)

### Possible Solution
N/a

### Context
N/a

**Comment by heldersepu** [comment]
Also the style of the model box changed:
- "3.12.1"
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=Company&defaultModelsExpandDepth=-1&defaultModelExpandDepth=5&defaultModelRendering=model#/Company/Company_Get
![image](https://user-images.githubusercontent.com/545474/37338376-afa0aac6-268d-11e8-942e-82795ba3a29f.png)

- "3.10.0"
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Company&defaultModelsExpandDepth=-1&defaultModelExpandDepth=5&defaultModelRendering=model#/Company/Company_Get
![image](https://user-images.githubusercontent.com/545474/37338423-c6069488-268d-11e8-8e55-26bca6fc6ea2.png)
