### ISSUE TITLE
switched from HTTP to HTTPS

### ISSUE THREAD

**Issue by dudo** [swagger-api/swagger-ui#432]
After forcing SSL, our docs have started reporting `Can't read from server. It may not have the appropriate access-control-origin settings.`

```
$ curl -I "https://staging.fanmouth.com/api/v1/swagger_doc"
HTTP/1.1 401 Unauthorized
Server: nginx/1.2.6
Date: Wed, 02 Apr 2014 20:45:12 GMT
Content-Type: text/html
Content-Length: 194
Connection: keep-alive
WWW-Authenticate: Basic realm="Restricted"
```

I get a `301 Moved Permanently` if I curl the http.

Does this have something to do with CORS? I'm not really sure how to go about patching this up.

**Comment by vinyll** [comment]
I'm having the same issue here.

I assume you're using Phusion Passenger while I'm using raw Nginx as a proxy.

> passenger... enable all;

I can't find anything about that i the Passenger doc to understand how you solved this.
What does that option do behind?
