### ISSUE TITLE
re- entering Basic Auth pop-up fails with error

### ISSUE THREAD

**Issue by erajkovic** [swagger-api/swagger-ui#4323]
When I tested Basic Auth and re-enter the pop-up, got the following error:

"Could not render this component, see the console" 

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  bug
| Which Swagger/OpenAPI version?  | OpenAPI3
| Which Swagger-UI version?       | 3.12.0
| How did you install Swagger-UI? |  webjar bundle
| Which browser & version?        | Chrome 65
| Which operating system?         | OS.X

### Demonstration API definition
the error details is:
TypeError: f.get is not a function
    at t.value (http-auth.jsx:61)
    at t.render (root-injects.js:93)
    at p._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at p._renderValidatedComponent (ReactCompositeComponent.js:819)
    at performInitialMount (ReactCompositeComponent.js:359)
    at p.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at performInitialMount (ReactCompositeComponent.js:368)
    at p.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)

The security part of the spec look normal:
...
    "securitySchemes": {
      "httpBasic": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": Array[1][
    {
      "httpBasic": Array[0][
        
      ]
    }
  ]

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior
I'll expect to be able to re-enter and see the same screen where user is authenticated.
![apic-openapi-username-authenticated](https://user-images.githubusercontent.com/4298647/37380097-34950c34-26f4-11e8-9f5e-a88d772bd62e.png)

### Current Behavior
Error popup

### Context

![apic-open-api-error-reauthpopup](https://user-images.githubusercontent.com/4298647/37380085-277b3dc0-26f4-11e8-9cce-382ffa1da29f.png)

**Comment by hkosova** [comment]
> The security part of the spec look normal:
> ...
> "security": Array[1][
> {
> "httpBasic": Array[0][

The `Array[1][` thing is not a valid syntax actually. Could you please post your complete definition, or if it's large, post it as a [gist](https://gist.github.com/)?

**Comment by erajkovic** [comment]
Got the file from https://apimatic.io/transformer using their OpenAPI v3 JSON as output - will try to re-run this and see how I got that generated for me - will try to attach the current copy here.

[all-apicatalog-openapi3.json.zip](https://github.com/swagger-api/swagger-ui/files/1811822/all-apicatalog-openapi3.json.zip)

**Comment by erajkovic** [comment]
This was in my original Swagger 2 document - see https://apicatalog.oraclecloud.com/api-docs/swagger-ui2/all-apicatalog-service.json - not sure how we got it there if it was invalid then.

**Comment by webron** [comment]
@erajkovic just tried reproducing it with the attached converted API definition, but it seems to be working well for me...

**Comment by erajkovic** [comment]
Will try to figure out what we did badly on our side - sorry for a non-issue post.
