### ISSUE TITLE
Whitespace is being removed when parsing JSON fields, which messes with Markdown rendering

### ISSUE THREAD

**Issue by jl-g** [swagger-api/swagger-ui#4329]
Markdown elements like headers, and lists are not displayed correctly in the description fields. This happens because, when parsing fields in a JSON swagger doc, some whitespace is being removed. I haven't tested whether this repros for YAML docs.

For example the following description:

    "description": "### Hello
    Hello, world
    
    ### This is a list
    - Item one
    - Item 2
      - Sub item 1
      - Sub item 2
    - Item 3",

Gets rendered like this:
![swagger-ui-bug](https://user-images.githubusercontent.com/37092114/37431457-8d781d66-2792-11e8-940f-33d51cd5f9ff.PNG)

I noticed this related issue: https://github.com/swagger-api/swagger-ui/pull/3353. However, this doesn't seem to be caused by the sanitizer as I see the same results if I disable it. It also doesn't seem to be caused by Remarkable. I logged the value of the description that is being fed into Remarkable, and it was already missing the whitespace. This is what shows up in the console:

    ### Hello Hello, world
    ### This is a list - Item one - Item 2 - Sub item 1 - Sub item 2 - Item 3

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | v3
| Which Swagger-UI version?       | 3.12.0
| How did you install Swagger-UI? | I cloned the repo locally, built, and loaded dist/index.html
| Which browser & version?        | Chrome v64.0.3282.186
| Which operating system?         |  Windows 10

### Demonstration API definition

I'm using the sample Pet Store swagger doc but with the description changed.

    {
        "swagger": "2.0",
        "info": {
            "description": "### Hello
    Hello, world

    ### This is a list
    - Item one
    - Item 2
    - Sub item 1
    - Sub item 2
    - Item 3",
            "version": "1.0.0",
            "title": "Swagger Petstore",
            "termsOfService": "http://swagger.io/terms/",
            "contact": {
                "email": "apiteam@swagger.io"
            },
            "license": {
                "name": "Apache 2.0",
                "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
            }
        },
        "host": "petstore.swagger.io",
        "externalDocs": {
            "description": "Find out more about Swagger",
            "url": "http://swagger.io"
        }
    }

### Configuration (browser query string, constructor, config.yaml)

The default configuration that gets copied to dist/

### Expected Behavior

When parsing a swagger doc, the parser should respect whitespace in fields that can contain Markdown (such as the API description field). 

### Current Behavior

Currently the values that are parsed from the swagger doc and fed into Remarkable have some whitespace stripped out, most noticeably new lines.

### Possible Solution

I don't have a solution at the moment, but I'm guessing whatever JSON parser is being used is collapsing some whitespace. I tried locating the code that parses the swagger doc after its retrieved, but I haven't found it. I'd be happy to help investigate if you could point me in the right direction.

**Comment by heldersepu** [comment]
It works fine for me:
http://swagger-net-test.azurewebsites.net/swagger/ui/index#/ArrayTest/ArrayTest_Put

**Comment by webron** [comment]
@jl-g that's technically not a valid JSON (use any JSON linter out there) - that description string needs to use escaped line breaks and not actual line breaks to become valid.

**Comment by jl-g** [comment]
@webron Yeah I didn't realize I had to escape the line breaks. In retrospect that makes more sense than having the actual line breaks in the JSON. I've verified that it's working as intended, so I'll close the issue.
