### ISSUE TITLE
Swagger / Swashbuckle UI returns "Unknown Response Type" in Edge Browser.

### ISSUE THREAD

**Issue by steveng57** [swagger-api/swagger-ui#4337]
The following issue occurs only in the Edge browser, Chrome and Firefox seem to work fine.

All actions seem to work fine, but in Edge, the return type comes back as unknown, similar to the following.

https://i.stack.imgur.com/6qqBh.jpg

This can be repro'ed by looking at an existing site in Edge such as http://petstore.swagger.io/#/pet/getPetById and doing a POST or GET,
and looking at the return type.

**Comment by WilliamABradley** [comment]
I also occasionally get this in Microsoft Edge (Tested Latest: Microsoft Edge 42.17107.1000.0), but also receive in in the Creators Update too. (41.16299.248.0)

**Comment by shockey** [comment]
@steveng57 @WilliamABradley, is there anything in your Edge browser console when this happens?

**Comment by protoplatoon** [comment]
Hi, I have the same error and this only happened when the answer status is 200. Also, there is nothing in my Edge browser console and the network request is good and it works well on Firefox and Chrome

**Comment by heldersepu** [comment]
When I open Edge on: http://petstore.swagger.io/#/pet/getPetById 
I see a warning:
> Could not find component JsonSchema_integer_int64

**Comment by heldersepu** [comment]
I think I found the problem:
https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/live-response.jsx#L63
```js
const contentType = headers["content-type"]
```

Looks like Edge case is different...

**Comment by heldersepu** [comment]
After the header issue is fix I get a new error:
```
can't parse JSON.  Raw result:

[object Blob]
```

**Comment by heldersepu** [comment]
Here are my findings so far:

Edge
```
response
[object Object]: {_list: Object, _map: Object, size: 11}
```

Chrome
```
response
OrderedMap {size: 13, _map: Map, _list: List, __ownerID: undefined, __hash: undefined}
```

**Comment by heldersepu** [comment]
@shockey Any idea why will the response be a different type of object on Edge?

**Comment by shockey** [comment]
@heldersepu, that sounds like https://github.com/swagger-api/swagger-js/issues/1206

**Comment by shockey** [comment]
as for the header case issue - HTTP headers are case-insensitive, so we should, ideally, normalize the header key names to lower case before trying to get a specific one.
