### ISSUE TITLE
Infinite spinners with using spec property

### ISSUE THREAD

**Issue by int128** [swagger-api/swagger-ui#4344]
I am using Swagger UI 3.12.1 and passing an OpenAPI specification JSON by `spec` property but I got infinite spinners.

- Page: https://int128.github.io/swagger-ui-issue-4344/
- Sources: https://github.com/int128/swagger-ui-issue-4344

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenAPI 2.0
| Which Swagger-UI version?       | Swagger UI 3.12.1
| How did you install Swagger-UI? | Extract from [webjars/swagger-ui](https://github.com/webjars/swagger-ui)
| Which browser & version?        | Chrome 65.0.3325.162
| Which operating system?         | macOS 10.13.3

### Demonstration API definition

Using https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore.yaml

### Configuration (browser query string, constructor, config.yaml)

Using `index.html` with the following script based on https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html.

```html
<script src="./swagger-ui-bundle.js"> </script>
<script src="./swagger-ui-standalone-preset.js"> </script>
<script>
  window.onload = function() {
    SwaggerUIBundle({
      spec: window.swaggerSpec,  // loaded in another script
      validatorUrl: null,
      docExpansion: 'full',

      dom_id: '#swagger-ui',
      deepLinking: true,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      plugins: [
        SwaggerUIBundle.plugins.DownloadUrl
      ],
      layout: "StandaloneLayout"
    })
  }
</script>
<script src="./swagger-spec.js">/* (mandatory) load source */</script>
```

`swagger-spec.js` is the following:

```js
window.swaggerSpec={
  "swagger" : "2.0",
  // snip...
}
```

### Expected Behavior

It should show all items after spinners.

### Current Behavior

I got infinite spinners. Once I click the toggle, all items show up.

### Possible Solution

Swagger UI 3.10.0 works fine but later versions do not work.

### Context

I am the author of [Gradle Swagger Generator Plugin](https://github.com/int128/gradle-swagger-generator-plugin). It can generate a Swagger UI page but it does not work with Swagger UI greater than 3.10.0 (https://github.com/int128/gradle-swagger-generator-plugin/issues/40).

The plugin is shipped with [the custom `index.html`](https://github.com/int128/gradle-swagger-generator-plugin/blob/master/src/main/resources/swagger-ui.html). Please let me know if you have any suggestion to the usage. I will fix it.

**Comment by shockey** [comment]
Thanks for the report, @int128!

This was previously reported over at https://github.com/swagger-api/swagger-ui/issues/4318. @scottohara mentioned a workaround of calling `ui.initOAuth()` to trigger a UI event that renders everything correctly.

As for a fix: I'm going to try to close this out by EOD Friday.

Gonna close this out and track in the earlier ticket. Cheers!
