### ISSUE TITLE
Request body x-www-form-urlencoded displayed as JSON

### ISSUE THREAD

**Issue by mikebywater** [swagger-api/swagger-ui#4345]
When documenting a POST request with the OAS3 spec I cannot represent parameters posted in a html style form as before. 

Previously you could document parameters you wish to post as in:form but now you can only specify parameters in either header, path, query or cookie everything else has to be specified in the requestBody.

I have set the content type of the requestBody to be application/x-www-form-urlencoded but when clicking "try it now" in the UI it makes the json in the text area editable.

![image](https://user-images.githubusercontent.com/3317281/37611980-c9d4d864-2b9b-11e8-890a-cb350a3ec01a.png)

I have set up the requestBody as follows

```yaml
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                fullname:
                  type: string
            encoding:
              fullname:            # color=red,green,blue
                style: form
```

I would expect it to look like a form in this example

![image](https://user-images.githubusercontent.com/3317281/37612111-2f894230-2b9c-11e8-96dc-fb7172f31994.png)

There is a high probability I am being a plonker here, but I cant seem to work out how this should be specified to make it display as a form as it would have in 2.x spec. so this feels like a bug to me.

**Comment by webron** [comment]
This is an unimplemented feature. Follow #3641 for progress.
