### ISSUE TITLE
how we fetch a json object in swggerUIBundle instead of using the url ?

### ISSUE THREAD

**Issue by moadthr** [swagger-api/swagger-ui#4347]
I tried  to use the spec  parametre instead of the url in the swaggerUIBundle but it does'nt work for me. I m wondering if there is something else to do ..? 
 ui = SwaggerUIBundle({			   
			   // url: 
			    spec: {obj},
			    dom_id: '#swagger-ui',
                           ...})

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
