### ISSUE TITLE
Problem with authorizations: empty popup

### ISSUE THREAD

**Issue by nbourdeau** [swagger-api/swagger-ui#4354]
Using version 3.13.0 with OpenApi spec 3.0

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0
| Which Swagger-UI version?       | 3.13.0
| How did you install Swagger-UI? | Downloaded from github
| Which browser & version?        | Firefox 59.0
| Which operating system?         | Linux

### Demonstration API definition
Here is the snippets from our API definition file relevant to authentication:
...
"security": [
    {
      "bearer": []
    }
  ],
...
"components": {
"securitySchemes": {
      "bearer": {
        "type": "HTTP",
        "in": "HEADER",
        "scheme": "Bearer"
      }
    }
...

### Configuration (browser query string, constructor, config.yaml)

window.onload = function() {
  
  // Build a system
  const ui = SwaggerUIBundle({
    url: "/spec.json",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ]
  });

  window.ui = ui
}

### Expected Behavior
When clicking on the authorize button to authorize requests, exepecting the UI to present me with a field to put Bearer header to authorize requests.

### Current Behavior
Popup is empty

### Possible Solution
Don't know what is wrong !

### Context
Tried with different versions and always the same error.
![screenshot at 2018-03-21 09-24-45](https://user-images.githubusercontent.com/6557616/37712267-b8ecf078-2ce9-11e8-9680-35d5838d66e2.png)

**Comment by webron** [comment]
You've provided a partial definition, so it's impossible to provide proper support. If you don't have `securityDefinitions` in your API definition, you won't have any authorizations being rendered.

**Comment by nbourdeau** [comment]
Hi

Here is the complete spec. But securityDefinitions is not part of OpenApi spec 3.x ... it's from the 2.x spec. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md

`
{"openapi":"3.0.0","info":{"title":"Courrier PRO REST API","description":"!!TODO!!","contact":{"url":"http://www.progressionlive.com/courrierpro","email":"*******"}},"servers":[{"url":"http://windows-dev-PC:8080/c2000rest"}],"security":[{"bearer":[]}],"tags":[{"name":"appel"}],"paths":{"/v1/appel/{numeroCie}/{noClient}/{noAppel}/suivi":{"get":{"tags":["appel"],"summary":"","description":"Get tracking information for a previously created call.","parameters":[{"name":"numeroCie","in":"path","description":"Company number","required":true,"schema":{"type":"number"}},{"name":"noClient","in":"path","description":"Customer number","required":true,"schema":{"type":"string"}},{"name":"noAppel","in":"path","description":"Call number returned on \"CreerAppel\" request","required":true,"schema":{"type":"string"}}],"responses":{"200":{"content":{"application/json":{"schema":{"type":"object","$ref":"#/components/schemas/SuiviAppelReturn"}}}},"401":{"$ref":"#/components/responses/Unauthorized"},"500":{"$ref":"#/components/responses/ServerError"}}}},"/v1/appel/{numeroCie}/{noClient}/{noAppel}/supprimer":{"post":{"tags":["appel"],"summary":"","description":"Request to delete a call if not dispatched","parameters":[{"name":"numeroCie","in":"path","description":"Company number","required":true,"schema":{"type":"number"}},{"name":"noClient","in":"path","description":"Customer number","required":true,"schema":{"type":"string"}},{"name":"noAppel","in":"path","description":"Call number returned on \"CreerAppel\" request","required":true,"schema":{"type":"string"}}],"responses":{"200":{"content":{"application/json":{"schema":{"type":"object","$ref":"#/components/schemas/SupprimerAppelReturn"}}}},"401":{"$ref":"#/components/responses/Unauthorized"},"500":{"$ref":"#/components/responses/ServerError"}}}},"/v1/appel/prix":{"post":{"tags":["appel"],"summary":"","description":"Ask for pricing estimation of a call before it's creation.","requestBody":{"content":{"application/json":{"schema":{"type":"object","$ref":"#/components/schemas/Appel"}}},"required":true},"responses":{"200":{"content":{"application/json":{"schema":{"type":"object","$ref":"#/components/schemas/InfoPrixReturn"}}}},"401":{"$ref":"#/components/responses/Unauthorized"},"500":{"$ref":"#/components/responses/ServerError"}}}},"/v1/appel/creer":{"post":{"tags":["appel"],"summary":"","description":"","requestBody":{"content":{"application/json":{"schema":{"type":"object","$ref":"#/components/schemas/Appel"}}},"required":true},"responses":{"200":{"content":{"application/json":{"schema":{"type":"object","$ref":"#/components/schemas/CreerAppelReturn"}}}},"401":{"$ref":"#/components/responses/Unauthorized"},"500":{"$ref":"#/components/responses/ServerError"}}}},"/v1/version":{"get":{"summary":"","description":"Returns the current web service version. Can be used to test connection.","responses":{"200":{"content":{"application/json":{"schema":{"type":"string"}}}},"401":{"$ref":"#/components/responses/Unauthorized"},"500":{"$ref":"#/components/responses/ServerError"}}}}},"components":{"schemas":{"Appel":{"required":["infoCueillette","infoLivraison","infoLivraisonInternational","lignesColis","numeroClient","numeroCompagnie","service"],"type":"object","properties":{"numeroCompagnie":{"type":"number","description":"Company number. 2 numeric characters. This number correspond to Courrier company number in CourrierPRO. This will be provided to you by the Courier company."},"numeroClient":{"type":"string","description":"Customer number. 15 Alphanumeric characters, uppercase. This number correspond to the customer number in CourrierPRO. This will be provided to you by the Courier company."},"numeroBon":{"type":"string","description":"Waybill number. 12 Alphanumeric characters, uppercase."},"service":{"type":"string","description":"Service code. 3 Numeric characters. This code correspond to one of the service codes in CourrierPro A list of all available code will be provided to you to match both systems."},"heureNePasCueillirAvant":{"type":"string","description":"Do not pickup before. 4 Numeric characters format HHMM (ex: 1515 pour 3 hours 15 minutes PM)"},"livraisonPrevueA":{"type":"string","description":"Delivery required at. 4 Numeric characters format HHMM (ex: 1515 pour 3 hours 15 minutes PM)"},"camionRequis":{"type":"number","description":"Truck required. Boolean, 0 = False (default), 1 = True"},"matiereDangereuse":{"type":"number","description":"To indicate if content is Dangerous goods. Boolean, 0 = False (default), 1 = True"},"allerRetour":{"type":"number","description":"To indicate this call will need a return. Boolean, 0 = False (default), 1 = True"},"signatureRequise":{"type":"number","description":"Indicate if a signature is required. Boolean, 0 = False (default), 1 = True"},"MontantCollecter":{"type":"number","description":"Amount to collect. Numeric format 999999.99"},"valeurDeclaree":{"type":"number","description":"Declared value for Insurance. Numeric format 999999.99"},"instructionSpeciale":{"type":"string","description":"Special Instructions. 1000 Alphanumeric characters, Uppercase"},"emailConfirmation":{"type":"string","description":"Email(s) confirmation for the call. 120 Alphanumeric characters. Enter valid email addresses separated by \";\" ex: test1@courrierpro.com; test2@courrierpro.com"},"international":{"type":"number","description":"Indicate if this is an International delivery. Boolean, 0 = False (default), 1 = True.\n- If False, delivery information must be in InfoLivraison section.\n- If True, delivery information must be in InfoLivraisonInternational section."},"infoCueillette":{"type":"object","description":"Informations about the pickup location","$ref":"#/components/schemas/InfoEmplacement"},"infoLivraison":{"type":"object","description":"Informations about the delivery location. Remark: This section is required is International section is not filled.","$ref":"#/components/schemas/InfoEmplacement"},"infoLivraisonInternational":{"type":"object","description":"Informations about the international delivery location. Remark : This section is Required if International is True.","$ref":"#/components/schemas/InfoEmplacement"},"lignesColis":{"type":"array","description":"Information of parcels to deliver. A minimum of one parcel is required. You can specify up to 20 parcels per call.","items":{"type":"object","$ref":"#/components/schemas/LigneColis"}}},"description":"Call information for creation or price estimate request"},"Adresse":{"required":["codePostal","province","ville"],"type":"object","properties":{"adresseLigne1":{"type":"string","description":"First line of address. 45 Alphanumeric characters, Uppercase"},"adresseLigne2":{"type":"string","description":"Second line of address. 45 Alphanumeric characters, Uppercase"},"porte":{"type":"number","description":"Steet number. 8 Numeric characters."},"suffixe":{"type":"string","description":"Suffix. 1 alphanumerical character, Uppercase, valid values : (A to Z, 1,2,3). No special characters"},"direction":{"type":"string","description":"Street direction. 2 alphanumerical characters, Uppercase, valid values : (N,S,E,O,W,NE,NW,NO,SE,SW,SO)"},"designation":{"type":"string","description":"Street designation. 6 alphanumerical characters, Uppercase, as Canada Post street designation names"},"rue":{"type":"string","description":"Street name. 30 alphanumerical characters, Uppercase"},"ville":{"type":"string","description":"City name. 30 alphanumerical characters, Uppercase"},"province":{"type":"string","description":"Province code. 2 alphanumerical characters, Uppercase. Ref.: http://www.pch.gc.ca/fra/1358952103267/1358952179380"},"codePostal":{"type":"string","description":"Postal code. 6 alphanumerical characters, Uppercase"},"suite":{"type":"string","description":"Suite, office #, etc.. 5 alphanumerical characters, Uppercase"}}},"SuiviAppelReturn":{"type":"object","properties":{"statut":{"type":"string","description":"Status (always \"OK\")"},"lignes":{"type":"array","description":"Tracking information list. Note: The first line information is the last status.","items":{"type":"object","$ref":"#/components/schemas/LigneSuivi"}}},"description":"Return information from a call tracking request"},"Telephone":{"required":["numero"],"type":"object","properties":{"numero":{"type":"number","description":"Phone number. Required, 10 Numeric characters, Ex: 4505306883"},"extension":{"type":"number","description":"Phone extension number. Optional, 6 Numeric characters"}}},"Service":{"type":"object","properties":{"code":{"type":"string","description":"Courrier PRO service code"},"description":{"type":"string","description":"Courrier PRO service description"}},"description":"Courrier PRO service"},"LigneColis":{"required":["dimensionA","dimensionB","dimensionC","poids","quantite","type"],"type":"object","properties":{"quantite":{"type":"number","description":"Quantity of this parcel. Numeric format 9999"},"type":{"type":"number","description":"Parcel type. Numerical format 9\nValues : (1 = Envelope, 2 = Box, 3 = Skid, 4 = Other)"},"dimensionA":{"type":"number","description":"First dimension. Numeric format 999999.99"},"dimensionB":{"type":"number","description":"Second dimension. Numeric format 999999.99"},"dimensionC":{"type":"number","description":"Third dimension. Numeric format 999999.99"},"poids":{"type":"number","description":"Parcel weight. Numeric format 999999.999999. Remark : Total weight will be calculated (Quantity * weight)."}},"description":"Information of packages to deliver."},"CreerAppelReturn":{"type":"object","properties":{"statut":{"type":"string","description":"Status (always \"OK\")"},"numeroAppel":{"type":"string","description":"Call number created in CourrierPro"},"prixEstime":{"type":"object","description":"Estimated price calculated informations","$ref":"#/components/schemas/PrixEstime"}},"description":"Return information of a create call request"},"InfoPrixReturn":{"type":"object","properties":{"statut":{"type":"string","description":"Status (always \"OK\")"},"service":{"type":"object","description":"Courrier PRO service","$ref":"#/components/schemas/Service"},"prixEstime":{"type":"object","description":"Estimated price calculated informations","$ref":"#/components/schemas/PrixEstime"}},"description":"Information return for pricing estimate request"},"InfoEmplacement":{"required":["nom"],"type":"object","properties":{"contact":{"type":"string","description":"Pickup contact name. 45 Alphanumeric characters, Uppercase"},"nom":{"type":"string","description":"Company or individual name. 45 Alphanumeric characters, Uppercase"},"reference":{"type":"string","description":"Pickup reference number. 25 Alphanumeric characters, Uppercase"},"adresse":{"type":"object","description":"Pickup address. Remark: if you put any information in Porte section, sections AdresseLigne1 and AdresseLigne2 will be ignored.","$ref":"#/components/schemas/Adresse"},"telephone":{"type":"object","description":"Contact phone number","$ref":"#/components/schemas/Telephone"}},"description":"Informations about the location of pickup or delivery"},"PrixEstime":{"type":"object","properties":{"montantBase":{"type":"number","description":"Basic amount"},"montantPoids":{"type":"number","description":"Extra weight amount"},"montantBoite":{"type":"number","description":"Extra box amount"},"montantAttente":{"type":"number","description":"Extra waiting time amount"},"montantAssurance":{"type":"number","description":"Insurance amount"},"montantEssence":{"type":"number","description":"Fuel surcharge amount"},"montantPSL":{"type":"number","description":"COD charge amount"},"montantAutresCharges":{"type":"number","description":"Others charges amount"},"montantEscompte":{"type":"number","description":"Discount amount"},"montantSousTotal":{"type":"number","description":"Sub-total amount"},"montantTps":{"type":"number","description":"GST Amount"},"montantTvp":{"type":"number","description":"PST Amount"},"montantTvh":{"type":"number","description":"HST Amount"},"montantTotal":{"type":"number","description":"Total Amount"}},"description":"Estimated price calculated informations"},"AdresseInternational":{"required":["adresseLigne1","pays","paysCode","ville"],"type":"object","properties":{"adresseLigne1":{"type":"string","description":"First line of address. 45 Alphanumeric characters, Uppercase"},"adresseLigne2":{"type":"string","description":"Second line of address. 45 Alphanumeric characters, Uppercase"},"adresseLigne3":{"type":"string","description":"Third line of address. 45 Alphanumeric characters, Uppercase"},"pays":{"type":"string","description":"Country name. 35 Alphanumeric characters, Uppercase\nReference : http://www.iso.org/iso/fr/french_country_names_and_code_elements"},"paysCode":{"type":"string","description":"Country code. 2 Alphanumeric characters, Uppercase\nReference : http://www.iso.org/iso/fr/french_country_names_and_code_elements"},"ville":{"type":"string","description":"City name. 20 alphanumerical characters, Uppercase"},"etat":{"type":"string","description":"State or province. 9 Alphanumeric characters, Uppercase"},"zipCodePostal":{"type":"string","description":"Zip or postal code. 12 Alphanumeric characters, Uppercase"}}},"InfoEmplacementInternational":{"required":["nom"],"type":"object","properties":{"contact":{"type":"string","description":"Pickup contact name. 45 Alphanumeric characters, Uppercase"},"nom":{"type":"string","description":"Company or individual name. 45 Alphanumeric characters, Uppercase"},"reference":{"type":"string","description":"Pickup reference number. 25 Alphanumeric characters, Uppercase"},"adresse":{"type":"object","description":"Delivery address.","$ref":"#/components/schemas/AdresseInternational"},"telephone":{"type":"string","description":"Phone number. 20 Alphanumeric characters"}},"description":"Informations about the international location of pickup or delivery"},"LigneSuivi":{"type":"object","properties":{"index":{"type":"number","description":"Sequence to differentiate each line"},"description":{"type":"string","description":"Description of this tracking status.\n- Call finished - delivered (Return) (Note: For a round trip call)\n- Call finished - delivered\n- Call pickuped\n- Call assiged to driver\n- New call"},"date":{"type":"string","description":"Date of this tracking status"},"heure":{"type":"string","description":"Time of this tracking status"},"signature":{"type":"string","description":"Signature of this tracking status. Only on \"Call finished - delivered (Return)\" and \"Call finished / delivered\" status."}},"description":"Line of tracking information for a call."}},"responses":{"Empty":{"description":"The operation succeeded."},"ServerError":{"description":"The server returned an error. See message for details.","content":{"application/json":{"schema":{"properties":{"error":{"type":"string"}}}}}},"Unauthorized":{"description":"Invalid authentication specified or access denied."}},"securitySchemes":{"bearer":{"type":"HTTP","in":"HEADER","scheme":"Bearer"}}}}
`

**Comment by webron** [comment]
You see, that's what happens when I answer tickets during meetings... shouldn't do that.
I had missed that this is OAS3 - however, it's still good you shared the entire API definition.

You actually have numerous errors in you definition, including in the security definitions, which is why nothing is being rendered. I suggest you try loading the definition into https://editor.swagger.io and work on fixing the errors.

**Comment by nbourdeau** [comment]
Thanks for your help. I see what the problem is. These values are case sensitive it seems. Then I build my JSON spec using the OpenApi java model provided by swagger and serializing it using Jackson and the enum are not serializing as expected by the spec ... I will find a workaround ...
It may be out of scope here but adding @JsonValue annotation to these enums would be great !

**Comment by nbourdeau** [comment]
So the correct spec was: 

"securitySchemes": {
"bearer": {
"type": "http",
"scheme": "bearer"
}

Thanks!

PS: next time I will validate my spec with swagger editor first! sorry

**Comment by webron** [comment]
@nbourdeau - feel free to file a ticket regarding the enum `@jsonvalue` suggestion on swagger-core. Can't guarantee a change, but we can investigate it.
