### ISSUE TITLE
I change the  input url with ajax ,but exlore button only still use custom url

### ISSUE THREAD

**Issue by lzbpythoner** [swagger-api/swagger-ui#4357]
I change the  input url with ajax ,but exlore button only still use custom url

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   2.0  
| Which Swagger/OpenAPI version?  |   
| Which Swagger-UI version?       |  latest
| How did you install Swagger-UI? |  github zip
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!

**Comment by shockey** [comment]
PS: Generally you don't want to use element selection to modify values in Swagger-UI. Consider using the Plugin API instead!
