### ISSUE TITLE
Swagger UI wrong cUrl request with Path Param and FormData Param

### ISSUE THREAD

**Issue by WilliamABradley** [swagger-api/swagger-ui#4366]
When using the Swagger UI and a Path Parameter is provided, as well as a FormData Parameter, the Content Type becomes undefined.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2 (Swashbuckle.AspNetCore.SwaggerGen (>= 2.3.0))
| Which Swagger-UI version?       | 3.12.0
| How did you install Swagger-UI? | NuGet Package (Swashbuckle.AspNetCore.SwaggerUI (>= 2.3.0))
| Which browser & version?        | Microsoft Edge 42.17107.1000.0
| Which operating system?         | Windows 10 Insider Preview 17107

### Demonstration API definition

```json
"/api/alerts/{AlertID}/Notes/{AlertNoteID}": {
    "put": {
        "tags": [
            "Alert"
        ],
        "summary": "Edits a Note for an Alert.",
        "operationId": "ApiAlertsByAlertIDNotesByAlertNoteIDPut",
        "consumes": [],
        "produces": [],
        "parameters": [
            {
                "name": "Note",
                "in": "formData",
                "description": "The Updated text of the Note.",
                "required": true,
                "type": "string"
            },
            {
                "name": "AlertNoteID",
                "in": "path",
                "required": true,
                "type": "string",
                "format": "uuid"
            },
            {
                "name": "AlertID",
                "in": "path",
                "description": "Alert ID for Request.",
                "required": true,
                "type": "integer",
                "format": "int64"
            }
        ],
        "responses": {
            "200": {
                "description": "Success"
            },
            "401": {
                "description": "Unauthorized"
            },
            "403": {
                "description": "Forbidden"
            },
            "500": {
                "description": "Internal Server Error"
            }
        },
        "security": [
            {
                "Bearer": null
            }
        ]
    },
    "delete": {
        "tags": [
            "Alert"
        ],
        "summary": "Deletes a Note for an Alert.",
        "operationId": "ApiAlertsByAlertIDNotesByAlertNoteIDDelete",
        "consumes": [],
        "produces": [],
        "parameters": [
            {
                "name": "AlertNoteID",
                "in": "path",
                "required": true,
                "type": "string",
                "format": "uuid"
            },
            {
                "name": "AlertID",
                "in": "path",
                "description": "Alert ID for Request.",
                "required": true,
                "type": "integer",
                "format": "int64"
            }
        ],
        "responses": {
            "200": {
                "description": "Success"
            },
            "401": {
                "description": "Unauthorized"
            },
            "403": {
                "description": "Forbidden"
            },
            "500": {
                "description": "Internal Server Error"
            }
        },
        "security": [
            {
                "Bearer": null
            }
        ]
    }
}
```

### Expected Behavior

```
curl -X PUT \
  http://localhost:62970/api/alerts/3/Notes/da387b73-09c7-4afb-504d-08d591735a4b \
  -H 'Authorization: Bearer {TOKEN}' \
  -H 'content-type: multipart/form-data; boundary={BOUNDARY}' \
  -F 'Note=Updated Text'
```

(Taken from Postman)

### Current Behavior

```
curl -X PUT "http://localhost:62970/api/alerts/3/Notes/da387b73-09c7-4afb-504d-08d591735a4b" \
-H  "accept: application/json" \
-H  "Authorization: Bearer {TOKEN}" \
-H  "Content-Type: undefined" \
-d "Note=Updated%20Text"
```

(Shifted to new Lines manually)

The Content-Type appears to be undefined, causing FormData to not be send properly, which could be due to the Path Parameters.

### Possible Solution

Use the correct Content-Type when Form Data is provided and using Path Parameters.

**Comment by hkosova** [comment]
Swagger UI only adds `Content-Type: application/x-ww-form-urlencoded` automatically to form data requests if there's [no explicit `consumes`](https://github.com/swagger-api/swagger-ui/issues/3583#issuecomment-323204420). Since you definition contains `consumes: []`, it overrides this logic. If you want `multipart/form-data` specifically, you need to define it explicitly:
```
"consumes": [ "multipart/form-data" ],
```

Also, `"Bearer": null` is not valid, it should be `"Bearer": []`. You can use http://editor.swagger.io to check your API definition for syntax errors.

**Comment by heldersepu** [comment]
@WilliamABradley see if your issue is only on Edge ...
I've not been able to get Edge to show a response for example on the petstore:
http://petstore.swagger.io/
all responses show: `Unknown response type`

**Comment by WilliamABradley** [comment]
@hkosova I fixed the issue with the Request failure by attaching the Consumes Attribute to the Action in ASP.NET Core MVC, and then having an Operation Filter to set the consumes to multipart/formdata.

@heldersepu I have experienced this issue with my Swagger UI, where unknown response type occurs, if that is an undiscovered issue, I can create a new issue for it.
