### ISSUE TITLE
DefaultValueAttribute swagger 2.3.0 doesn't work

### ISSUE THREAD

**Issue by pMonfared** [swagger-api/swagger-ui#4369]
i use [defaultValue()] in ASP.net Core (.netStandard Library) to show in Swagger UI as Example Model With Default Data
in previous version work correctly.
but in version 2.3.0 don't work.
i don't know why? please help me!

```
[DefaultValue("simpleSearch")]
public string SearchType { get; set; }
``` 

![image](https://user-images.githubusercontent.com/10448255/37899154-f39e80a0-30ff-11e8-85f5-eaadd1b3aea6.png)
click on model show defaultValue but click on ExampleValue don't show!!

![image](https://user-images.githubusercontent.com/10448255/37899212-1f1fb6b8-3100-11e8-82bf-c75d1b5babdb.png)

**Comment by heldersepu** [comment]
Can you provide an API definition that reproduces your problem?

**Comment by hkosova** [comment]
Sample specs:

2.0:
```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: default value test
paths:
  /:
    post:
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/MyObject'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MyObject'

definitions:
  MyObject:
    type: object
    properties:
      str:
        type: string
        default: Hello, world!
      int:
        type: integer
        default: 42
      uuid:
        type: string
        format: uuid
        default: '9BCD28F0-9711-484B-A160-8F9BC68AE1F4'
      date:
        type: string
        format: date
        default: '2000-01-01'
      # Note that "default" is used in boolean examples
      bool1:
        type: boolean
        default: true
      bool2:
        type: boolean
        default: false
```

3.0:
```yaml
openapi: 3.0.0
info:
  version: 0.0.0
  title: default value test
paths:
  /:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyObject'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyObject'

components:
  schemas:
    MyObject:
      type: object
      properties:
        str:
          type: string
          default: Hello, world!
        int:
          type: integer
          default: 42
        uuid:
          type: string
          format: uuid
          default: '9BCD28F0-9711-484B-A160-8F9BC68AE1F4'
        date:
          type: string
          format: date
          default: '2000-01-01'
        # Note that "default" is used in boolean examples
        bool1:
          type: boolean
          default: true
        bool2:
          type: boolean
          default: false
```

The `default` values were used in autogenerated examples in Swagger UI 2.x:
![Swagger UI 2.x and examples with default values](https://user-images.githubusercontent.com/8576823/38416065-37b36d42-399c-11e8-929f-217fdff6262f.png)

but are not used in UI 3.x:
![Swagger UI 3.x](https://user-images.githubusercontent.com/8576823/38416105-5e3bd666-399c-11e8-96a7-cbcbeee42351.png)

**Comment by webron** [comment]
Going to close this one out for two reasons:
1. There's no version 2.3.0.
2. It's been 2 weeks and no feedback from the OP.

Feel free to refile the ticket following the issue template, providing the details to help us help you.
