### ISSUE TITLE
feature: navigation and search "sidebar"

### ISSUE THREAD

**Issue by JonKohler** [swagger-api/swagger-ui#4373]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  feature
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.latest
| How did you install Swagger-UI? | n/a
| Which browser & version?        | n/a
| Which operating system?         | n/a

### Current Behavior
For small API sets, navigation and search for the APIs you're looking for are relatively easy, as there isn't a lot to scroll through.

For large API sets, where one single API endpoint has a LOT of methods/definitions/otherwise, it can get a bit unwieldy. 

Previous solutions have been along the lines of splitting things into multiple specs, and using a select-specification drop down, but sometimes this isn't practical.

### Possible Solution
We've been working on a react based replacement for our swagger-ui 2.1.4 implementation within our product; however, we're currently changing direction to baseline this as an upgrade from 2.1.4 to 3.x, and would like to port in some of the features that we've added.

Specifically for this feature request, we've built a navigation and search "sidebar", that has the following characteristics: 

1. Groups APIs into "Topics", "API", and "Definitions", similar to how "Slate" API documentation does things
2. Per API, it summarizes HTTP methods into a nicely color code tag on the same line as the API, so you can clearly see what supports things like put/get/post/delete, without it taking up multiple lines (Saving "scrolling")
3. Has a search/filter field at the top, to allow a user to easily "poke around" or search for what they want. As soon as a user types into the search field, the API/definitions areas start getting smaller and more focused

I'm posting this here to garner feedback on this approach, so we can get community input as to whether or not this is useful, and how best to implement it, such that we can do a clean PR when the time is right to upstream this.

Perhaps this is something we initially hide behind a feature flag, or allow some level of top level "toggle", since it would be a significant change to the layout of swagger-ui.

### Screenshots
Here's a quick screenshot from our internal code

You can see in this example, I'm searching up at the top for "vms", and I see all of my API endpoints with "vms" in it, as well as the definitions that have "vms" in them (note: there are a LOT more API/definitions in here, its just a screenshot with the "vms" search on)

<img width="243" alt="screenshot 2018-03-22 02 43 10" src="https://user-images.githubusercontent.com/21041006/37928807-17a26d70-310c-11e8-9572-9085aec62098.png">

**Comment by shockey** [comment]
Interesting feature!

CC: @webron

**Comment by rcrooks** [comment]
I would also love this -- it's the one obstacle between us and converting all our API documentation to Swagger

**Comment by manuwell** [comment]
How can I test this? It's a really great navigation. Can you share the react component and how to implement it?

**Comment by JonKohler** [comment]
we mocked this up, but ultimately gave up on swagger-ui, we're switching to ReDoc for our product.

Closing this out as we have no intention of finishing this (unfortunately)

**Comment by rcrooks** [comment]
we did the same :) thanks @JonKohler
