### ISSUE TITLE
Make requests from SwaggerUI of certain ContentType

### ISSUE THREAD

**Issue by a1ku** [swagger-api/swagger-ui#4375]
Hello,

I use Swagger v2, I work with editor.swagger.io editor. I want the SwaggerUI to be able to execute the requests I define in the docs. 
The API I document only accepts `ContentType=application/json`. Currently, SwaggerUI sends requests in `text/html` content type.
![ct](https://user-images.githubusercontent.com/3973215/37961319-37ba54fe-31b8-11e8-9047-f744d7677694.png)

Here's a snippet from my docs.

```
"paths": {
  "/api/auth_token": {
    "post": {
      "tags": [
        "auth"
      ],
      "summary": "Obtain auth token",
      "description": "Le description",
      "operationId": "getAuthToken",
      "consumes": ["application/json"],
      "produces": ["application/json"],
      "parameters": [
        {
          "in": "body",
          "name": "",
          "description": "User credentials",
          "required": true,
          "schema": {
            "$ref": "#/definitions/Credentials"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "Invalid ID supplied",
          "schema": {
            "$ref": "#/definitions/JWT"
          }
        },
        "401": {
          "description": "Email & password does not match"
        },
        "404": {
          "description": "User not found"
        }
      }
    }
  }
}
```

How do I define the docs to make SwaggerUI send requests with `Content-Type=application/json`?

**Comment by shockey** [comment]
This sounds like a bug to me, your `consumes` value should be setting that Content-Type header.

Can you provide a full API definition that reproduces this error?

**Comment by shockey** [comment]
thanks @a1ku!

the issue is that your body parameter's name is an empty string. providing an actual name should fix this :smile:

**Comment by heldersepu** [comment]
@shockey  Shouldn't the validator show an error on this case?

**Comment by a1ku** [comment]
@shockey You're right. Thank you for the help.

**Comment by shockey** [comment]
@heldersepu, @webron indicated to me that this should be handled in the specification (and then, by the JSONSchema provided by OpenAPI) rather than by Swagger-Editor's extended validation.

---

@a1ku, glad I could help!
