### ISSUE TITLE
Cannot install the latest version

### ISSUE THREAD

**Issue by gitterchris** [swagger-api/swagger-ui#4378]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 
| Which Swagger-UI version?       | 3.13.1
| How did you install Swagger-UI? | `npm install swagger-ui` or `yarn add swagger-ui`
| Which browser & version?        | N/A
| Which operating system?         |  Windows 7

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior

The package should be installed without error. 

### Current Behavior

When I use `npm install swagger-ui`, I get `npm ERR! cb() never called!`. 

When I try `yarn add swagger-ui`, I get 

```
error An unexpected error occurred: "http://[somelink with tgz file here].tgz: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".
```

It seems like the issue is with the yarn publishing. There is a workaround suggested [here](https://github.com/yarnpkg/yarn/issues/2764).

**Comment by shockey** [comment]
I doubt that this issue is us, as tarballs are internal to the npm registry.

What yarn/npm versions are you seeing this with?

**Comment by gitterchris** [comment]
yarn 1.5.1 and npm 5.6.0.

**Comment by shockey** [comment]
I am able to do that:

```sh
➜  code/kyleshockey.com git:(master) yarn add swagger-ui
yarn add v1.5.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning gatsby > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning swagger-ui > react-height > create-react-class@15.5.2: create-react-class has known issues with Browserify before version 15.5.3. Please update create-react-class to 15.5.3 or a newer version.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
warning "gatsby-plugin-react-helmet > react-helmet@5.2.0" has unmet peer dependency "react@>=15.0.0".
warning "gatsby-plugin-react-helmet > react-helmet > react-side-effect@1.1.5" has unmet peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0".
warning "swagger-ui > webpack-dev-server@2.5.0" has unmet peer dependency "webpack@^2.2.0".
warning "swagger-ui > react-addons-shallow-compare@0.14.8" has incorrect peer dependency "react@^0.14.8".
warning "swagger-ui > react-object-inspector@0.2.1" has incorrect peer dependency "react@^0.14.0".
warning "swagger-ui > worker-loader@0.7.1" has unmet peer dependency "webpack@>=0.9 <2 || ^2.1.0-beta".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1026 new dependencies.
✨  Done in 63.88s.
```

Are you using a proxy to connect to the npm registry?

(Aside: we have some deprecations to deal with on our side...)

**Comment by gitterchris** [comment]
Yes, I am behind a corporate proxy. It seems like the issue is with our registry. 

Installing an older version (3.0.21) works for some reason. Thanks for your support. I guess I should close this instead.

**Comment by shockey** [comment]
Sounds good, glad you identified the problem @gitterchris.

I would suggest trying to get at the newer versions - with 3.0.21 you'll be missing quite a bit of polish we've put onto the project over the last several months 😄
