### ISSUE TITLE
disappearing id parameter

### ISSUE THREAD

**Issue by gonenduk** [swagger-api/swagger-ui#4380]
Hi,
I am using OpenAPI 3.0. I defined the id parameter in the components scope. I reference it in the path of a resource so it will be used in all methods of the path.
First click on the path displays the parameter as required. Now if I click again to close the parameter list and then reopen it - the parameter is displayed as () instead of id.
Can be reproduced in the swagger ui online editor as well with this simple yaml:

[issue-yaml.zip](https://github.com/swagger-api/swagger-ui/files/1854031/issue-yaml.zip)

**Comment by shockey** [comment]
This is being tracked in https://github.com/swagger-api/swagger-ui/issues/4327 :smile:

**Comment by shockey** [comment]
Closing as a duplicate.
