### ISSUE TITLE
Unable to infer base url. This is common when using dynamic servlet

### ISSUE THREAD

**Issue by fendo8888** [swagger-api/swagger-ui#4384]
Unable to infer base url. This is common when using dynamic servlet registration or when the API is behind an API Gateway. The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/. Please enter the location manually:

**Comment by shockey** [comment]
Hi @fendo8888!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template, and there's not enough information provided to be able to help with the issue you're having.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
