### ISSUE TITLE
maxProperties, additionalProperties and examples in UI

### ISSUE THREAD

**Issue by svart-riddare** [swagger-api/swagger-ui#4388]
I am using https://editor.swagger.io, and I encountered a minor issues in the rendered documentation when I use `maxProperties` and `additionalProperties` together.

Here is the API description:

```yaml
openapi: 3.0.0
info:
  title: API Documentation
  version: 0.0.0
paths:
  /version:
    get:
      summary: Version Query
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: Version strings
                type: object
                maxProperties: 2
                additionalProperties:
                  title: Version string for each component
                  type: string
                  example: "Backend - Version 1.2.3"
```

In the rendered documentation, an example response is given as

````json
{
  "additionalProp1": "Backend - Version 1.2.3",
  "additionalProp2": "Backend - Version 1.2.3",
  "additionalProp3": "Backend - Version 1.2.3"
}
````

This example does not validate against the provided schema, as there are 3 `additionalProperties` while the schema limits them to 2 according to the `maxProperties` field.

I would have expected the example response to be:

````json
{
  "additionalProp1": "Backend - Version 1.2.3",
  "additionalProp2": "Backend - Version 1.2.3"
}
````

Regards

**Comment by RamiaSaidawi** [comment]
any update on this bug?, i have to change my schema just to make this work with the examples :(

**Comment by mathis-m** [comment]
Yes this should be considered by the sample-gen. With #7043 I have fixed this:

- added min / max length
- added minimum / maximum (+ exclusive)
- added min / max items
- added min / max properties
