### ISSUE TITLE
mac safari "Download headers detected but your browser does not support downloading binary via XHR (Blob)."

### ISSUE THREAD

**Issue by neopaf** [swagger-api/swagger-ui#4398]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  bug
| Which Swagger-UI version?       |2.8.0
| How did you install Swagger-UI? | gradle dependency of  compile group: 'io.springfox', name: 'springfox-swagger-ui', version: 2.8.0
| Which browser & version?        | Safari 11.0.3 (13604.5.6) 
| Which operating system?         |  High Sierra

### Expected Behavior

on a mac safari in 2.7.0 version it was possible to have a REST method return
```
 content-disposition: attachment 
 content-type: text/csv; charset=UTF-8 
 date: Thu, 01 Mar 2018 07:17:33 GMT 
```

hand have that file available for download by clicking a link in reply area.

### Current Behavior

Reply area contains sad message:
````
Download headers detected but your browser does not support downloading binary via XHR (Blob).
```

**Comment by webron** [comment]
@neopaf took a look at the link thread as well. I understand how this can be confusing, but we don't control the springfox libraries and we have no idea which version of swagger-ui is provided with version 2.8.0 of their dependency (hint, it's not version 2.8.0 of swagger-ui). As such, we need you to provide us with the actual version of swagger-ui that you use.

Alternatively, I'd suggest trying to use the latest version of swagger-ui from here. If it works, then either use it, or ask the springfox people to update their version to the latest.

**Comment by dilipkrish** [comment]
Just to clarify for non-springfox users, springfox-swagger-ui is just a thin webjar wrapper for swagger-ui and version 2.8.0 **of the webjar** [uses version 3.9.1 of swagger ui](https://github.com/springfox/springfox/blob/2.8.0/springfox-swagger-ui/build.gradle#L31). 

Now the issue as it pertains to swagger-ui is that in prior versions of (2.x old UI) we were able to hit "Try it out" on endpoints that download files and it would work. In this case ☝️ and endpoint that downloads `text/csv` file. 3.x and beyond and 3.9.1 specifically, does not let you do that. That is the @neopaf  trying to report.

/c @webron

**Comment by webron** [comment]
Thanks for jumping in, @dilipkrish. I'll try to remember that version for future reference.

Regardless, since it's not the latest version, we'd always refer users to try the latest before continuing investigating.

**Comment by shockey** [comment]
I just opened a PR that removes our Safari check, since Safari 11 can handle our XHR/Blob download implementation just fine.

I haven't tested it with older Safari versions, but per [Can I Use's usage stats table](https://caniuse.com/usage-table), Safari < 11 accounts for just 0.7% of browser usage.
