### ISSUE TITLE
Add more languages to Sample Code examples

### ISSUE THREAD

**Issue by gbayarri** [swagger-api/swagger-ui#4401]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  feature request
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | Using 3.X @ Petstore
| How did you install Swagger-UI? | Using 3.X @ Petstore
| Which browser & version?        | Chrome Version 65
| Which operating system?         | Ubuntu 16.04

### Expected Behavior
Ability to put more than one (currently Curl) Sample Code, as found in this link:

https://www.ebi.ac.uk/proteins/api/doc/#!/proteins/search

Screenshot (Curl, Perl, Python, Ruby, Java, R):

![screenshot](https://user-images.githubusercontent.com/19928100/38244804-0eb00278-373c-11e8-96d8-22dbe1ee8821.png)

### Current Behavior
Currently, I can only show sample code for Curl. Maybe I should put something in my code, but I couldn't find an example.

**Comment by webron** [comment]
I'm closing this ticket not because it's not important or useful, but because it is currently out of scope for us for a number of reasons. We might end up implementing it in the future, but not looking to give false hope that this is going to happen soon.

**Comment by TedDriggs** [comment]
Where do these samples get generated in the codebase? I was trying to find it, but all I could find was the curl code.
