### ISSUE TITLE
Nested Tags in Swagger Editor while constructing same api with different versions.,

### ISSUE THREAD

**Issue by kritika020594** [swagger-api/swagger-ui#4403]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature
| Which Swagger/OpenAPI version?  | 3.0
| Which Swagger-UI version?      | 3.0
| How did you install Swagger-UI? | 
| Which browser & version?        | Chrome
| Which operating system?        |  Windows

### Demonstration API definition

```yaml
your: "API definition goes here"
```
Want to have nested tagging for the API to render the various version of it-
For example-

ABC(parent tag)

1.0(child tag)

...get
...post
..get
so on..

2.0(second child)

...get
...post
so on...

XYX(Another parent tag)

..Same as above

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by webron** [comment]
Refiling a ticket after it was closed with an explanation that it's not going to be implemented doesn't help anyone. I know you're aware of the other ticket because you've commented there as well.

**Comment by kritika020594** [comment]
Hi webron, 

The ticket was closed in 2016 so raised it again with the explanation of what is required.

If the feature is not implemented then is there any other way through which we can attain the same functionality?

Thanks in advance.

**Comment by webron** [comment]
Yes, it was closed with an explanation that has no grounds to change. Still not supported by the spec. You can always implement the functionality yourself, it's an open source project.

**Comment by heldersepu** [comment]
@kritika020594 Have you seen the filter functionality?
You can see it in action here: 
http://swagger-net-test.azurewebsites.net/swagger/ui/index
