### ISSUE TITLE
Unknown response type for application/javascript

### ISSUE THREAD

**Issue by jmgpeeters** [swagger-api/swagger-ui#4406]
As per the discussion on https://stackoverflow.com/questions/49632532/swagger-ui-unknown-response-type I'm opening an issue here.

Essentially, I'm trying the swagger-ui to display JSON data that gets sent back with mimetype "application/javascript". Note that I don't have control over the REST api itself, so cannot change this.

I've reduced this to a minimal example. This is my specification file:

    swagger: "2.0"
    info:
      title: Test API
      description: "Sample documentation."
    host: localhost:5001
        
    paths:
      /hello:
        get:
          tags:
            - Test

          produces:
            - application/javascript
          responses:
            200:
              description: OK
              schema:
                type: string

and (for demonstration purposes) I set up a small flask server, with this endpoint,

    ...
    @app.route('/hello')
    def hello():
        return Response('{"A B":["C"],"D":["E"]}', mimetype='application/javascript')

    if __name__ == '__main__':
        app.run(host="0.0.0.0", port=5001)

This gives the

    Response body
        Unknown response type
    Response headers
        content-type: application/javascript 

error in the swagger-ui. If, in the web-server, I change the mimetype to application/json, it all works fine.
OpenAPI specification 2.0 or 3.0 behave the same. Is there a a particular spec missing? Or is this a feature that swagger-ui does not support?

I am using Chrome 65.0, and swagger-ui version 3.13.2 (cloned earlier today from master).

**Comment by shockey** [comment]
Using https://gist.github.com/shockey/78e57f99e10a1ae5c2c208545f892d21 to test this, backed by a server I stood up here at https://zeit.co/kysh/test-server/gqrklcgqld/source?f=index.js

**Comment by shockey** [comment]
`application/javascript` will now be coerced to text for display. Still, `application/json` is better 😉 

Closing as fixed! Thanks for the report, @jmgpeeters.
