### ISSUE TITLE
Operation show/hide toggle does not work properly for some Openapi 3.0.0 specs  

### ISSUE THREAD

**Issue by fbrunet99** [swagger-api/swagger-ui#4409]
When displaying some openapi 3.0.0 documents the initial click of the operation does not show the operation details.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenApi 3.0.0
| Which Swagger-UI version?       | 3.13.1
| How did you install Swagger-UI? | Github clone. Also reproduce issue using online petstore.swagger.io pointed to a local file.
| Which browser & version?        | Chrome 65.0 and Firefox 59.0.2
| Which operating system?         | Mac OS 10.12.6

### Demonstration API definition

```yaml

openapi: 3.0.0
servers:
  - url: 'https://__host__/'
info:
  description: Test API
  version: '1.0'
  title: Test API
  contact:
    name: Sample Person
    email: Sample.Person@adp.com
tags:
  - name: Test API with Schema
    description: Test API with Schema
paths:
  /myApi/v1/associates/documents:
    get:
      operationId: some guid
      responses:
        '200':
          description: Returns documents
      description: Returns documents
      tags:
        - Test API with Schema
      summary: Test API with Schema
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior
Upon clicking an operation, it should toggle between show/hide of the operation details.

### Current Behavior
Initial click of operation quickly shows then hides the details. Subsequent clicks work as expected.

### Possible Solution
Click event may be firing multiple times. Perhaps a trapped error during render causes this. No errors are shown in the console during the behavior.

### Context
I tried several of our swagger documents, all exhibit this behavior. Small changes to the document can cause the problem to go away. For example, removing the operationId or the tag description may result in a document that doesn't reproduce the problem.

**Comment by shockey** [comment]
Confirmed!

**Comment by shockey** [comment]
Fixed 🎉
