### ISSUE TITLE
OpenAPI3: Response shows example generated from schema instead of example given

### ISSUE THREAD

**Issue by fbrunet99** [swagger-api/swagger-ui#4415]
OpenAPI 3: When a response shows an example, it shows one generated from the schema. It does not show the example that was given under content/type/response/value.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenAPI 3.0
| Which Swagger-UI version?       | 3.13.2
| How did you install Swagger-UI? | Git clone
| Which browser & version?        | Chrome Latest
| Which operating system?         | MacOS Sierra

### Demonstration API definition

```yaml
openapi: 3.0.0
servers:
  - url: 'https://__host__/'
info:
  description: Test API
  version: '1.0'
  title: Test API
  contact:
    name: Sample Person
    email: Sample.Person@adp.com
tags:
  - name: Test API with Schema
    description: Test API with Schema
paths:
  /myApi/v1/associates/documents:
    get:
      operationId: some guid
      responses:
        '200':
          description: Returns documents
          content:
            '*.*':
              schema:
                $ref: ./schemas/documents_schema.json
            application/json:
              examples:
                response:
                  value: ./examples/document_sample.json
      description: Returns documents
      tags:
        - Test API with Schema
      summary: Test API with Schema
```

### Expected Behavior
Expect the sample to be shown under the example tab in the response.

### Current Behavior
A sample that has been generated from the schema is shown. This will show generic types such as "string" as a value rather than a realistic value as used in a sample.

### Possible Solution
In core/components/response.jsx, the examples selector (response.get("examples") ) does not pick up all possible examples so subsequent code falls back to a generated version.

This can possibly fixed by modifying response.jsx at about line 108 (inside the "if isOAS3" block) to look a little harder for the examples. Like this:
```js
      if (!examples && content) {
        examples = content.find((data, key) => {
          return data.get("examples")
        })
      }
```
### Context
We need to provide examples with realistic values rather than generic generated ones.

**Comment by hkosova** [comment]
Support for media type examples is being tracked in https://github.com/swagger-api/swagger-ui/issues/3437.

A couple of notes:
1) `*.*` does not look like a valid media type, did you mean `*/*`?
2)  `value` is for inline examples only. To reference an external example you need to use [`externalValue`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#user-content-exampleExternalValue):

```yaml
              examples:
                response:
                  externalValue: ./examples/document_sample.json

```

**Comment by fbrunet99** [comment]
1. Yes *.* is a typo. It should be */* (or application/json)

**Comment by webron** [comment]
Going to close this one out in favor of #3437 - as @hkosova kindly pointed out, it's an unimplemented feature.
