### ISSUE TITLE
Model schema rendering seems broken

### ISSUE THREAD

**Issue by Dantemss** [swagger-api/swagger-ui#4426]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |  3.0
| Which Swagger-UI version?       | 3.13.2
| How did you install Swagger-UI? | yarn for my own project, not sure about the example site
| Which browser & version?        | Chrome 65
| Which operating system?         | OS X

### Demonstration API definition

http://petstore.swagger.io/v2/swagger.json

### Configuration (browser query string, constructor, config.yaml)

http://petstore.swagger.io/#/user/createUsersWithArrayInput (click on Model tab for `body` param)

### Expected Behavior

I would expect examples to be rendered in the Example tab.
I would expect the whole Model schema to be rendered in the Model tab.

### Current Behavior

Some of the schema's attributes are rendered as an example in the Example tab.
Only the schema description is rendered in the Model tab.

### Possible Solution

This is pure speculation, but might have something to do with references ($ref) in the schema. At least the part where the description is the only thing in the Model tab.

### Context

The issue where the Model tab contains only the description also affects the project I am trying to document, not just the example site (In my project, it seems to be caused by `oneOf` with an array of references? Could be a different issue than on petstore.swagger.io)

**Comment by heldersepu** [comment]
Yep this is all over the place:
http://petstore.swagger.io/?docExpansion=full&defaultModelRendering=model

**Comment by shockey** [comment]
I believe #4424 fixes this

**Comment by shockey** [comment]
Fixed in #4424. Sorry for the trouble, @Dantemss!

**Comment by Dantemss** [comment]
Thanks for the fix.
