### ISSUE TITLE
Choose scheme per loaded page

### ISSUE THREAD

**Issue by oguzhanunlu** [swagger-api/swagger-ui#4427]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  probably feature request
| Which Swagger/OpenAPI version?  | 
| Which Swagger-UI version?       | 3.12.0
| How did you install Swagger-UI? | copy-paste dist/ folder
| Which browser & version?        | all
| Which operating system?         | all

### Context

I want Swagger UI to select scheme to be used per loaded page. If I browse an address starting with http://.. it should select http scheme , if this address is https, UI should select https.

Is it possible at the moment? I'm not sure if it is. 

Thanks in advance.

**Comment by webron** [comment]
If a scheme is not specified in the API definition itself, Swagger-UI will use the scheme which is used to load it. If you want to control the behavior beyond that, that would be something you need to implement.

**Comment by oguzhanunlu** [comment]
Thanks for quick response! I tested and it works as expected, picks up loaded scheme. Thanks!

**Comment by webron** [comment]
@oguzhanunlu thanks for confirming it works for you. Can we close the ticket?

**Comment by oguzhanunlu** [comment]
Sure
