### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#4432]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature
| Which Swagger/OpenAPI version?  | Any
| Which Swagger-UI version?       | Latest
| How did you install Swagger-UI? | N/A
| Which browser & version?        | Any
| Which operating system?         | ...

### Context
One thing I like about Gmail is the Keyboard shortcuts:
https://support.google.com/mail/answer/6594?hl=en

Maybe we should implement something like that for the swagger-ui... 
Here are a few ideas:
- Expand all 
- Collapse all
- Open the Authorize dialog
- Jump to the filter ready to type

**Comment by shockey** [comment]
some of this would be addressed by keyboard usability/accessibility in general, as covered in #5290
