### ISSUE TITLE
HPE Fortify detects an issue with cross-document messaging

### ISSUE THREAD

**Issue by williamhavercamp** [swagger-api/swagger-ui#4439]
The specific warning is as follows:

"On line 12 of swagger-ui-standalone-preset.js the program posts a cross-document message with an overly permissive target origin."

swagger-ui-standalone-preset.js version: 3.0.21
HPE Fortify version: 17.20.0183

**Comment by webron** [comment]
@williamhavercamp do you have the option to run it again on the latest version?
