### ISSUE TITLE
Model description not displayed in parameters (body) but it's displayed in responses.

### ISSUE THREAD

**Issue by joselfr** [swagger-api/swagger-ui#4444]
Hello!

We are experiencing a render issue with swagger-ui.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |2
| Which Swagger-UI version?       |Swagger Online Editor
| How did you install Swagger-UI? | NA
| Which browser & version?        |Chrome 63 / Safari 11.1
| Which operating system?         | Ubuntu / Mac OS

### Demonstration API definition

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Public API
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /sessions/:
    post:
      summary: Create a session
      tags:
        - Authentication
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Session'
      responses:
        '201':
          description: Session created
          schema:
            $ref: '#/definitions/Session'
definitions:
  Session:
    type: object
    properties:
      admin_user:
        type: string
        example: "user@example.com"
```
### Expected Behavior
Model description should be displayed both in parameters and responses

### Current Behavior
Only displays on responses
![screenshot_2018-04-16_19-18-59](https://user-images.githubusercontent.com/1237183/38825061-91f92348-41ab-11e8-88c4-34bacef464be.png)

### Possible Solution
Use older editor
![screenshot_2018-04-16_19-21-17](https://user-images.githubusercontent.com/1237183/38825072-9bc9d46c-41ab-11e8-85f9-ac7b263f92a4.png)
(this is not a viable workaround since we would like to use the latest swagger-ui version)

Thanks

**Comment by shockey** [comment]
Hey @joselfr, this has been fixed in Swagger-UI but Swagger-Editor hasn't picked up the fix yet.

We may update the Swagger-UI dependency on editor.swagger.io within the next day or two, but at the latest the fix will be deployed in the next version of Swagger-Editor, which will be released on Friday.

**Comment by joselfr** [comment]
Hey @shockey .

I pulled the latest version and I confirm that it works.

Thanks.

**Comment by shockey** [comment]
Great, glad you got it working :smile: 

Closing!
