### ISSUE TITLE
Downloadable HighlightCode forcing file to response.txt

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#4446]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   Feature
| Which Swagger/OpenAPI version?  | Any
| Which Swagger-UI version?       | Latest
| How did you install Swagger-UI? | PetStore
| Which browser & version?        | Chrome
| Which operating system?         | Win98 (Best OS ever!)

### Demonstration API definition
http://petstore.swagger.io/#/pet/getPetById

### Current Behavior
[Try it out] Enter a 2 on the petId and Execute
The Response body show a nice download button but downloading saves a file (response.txt)
change the response type to Json and Execute and download same file is downloaded.

### Expected Behavior
The filename should reflect the action and the extension should use the response type.
something like:  getPetById.xml or getPetById.json

**Comment by shockey** [comment]
Yeah, this was out of scope for the initial implementation. I'd like to see timestamping in the file name alongside this improvement 😄
