### ISSUE TITLE
Hide the client secret?

### ISSUE THREAD

**Issue by garymacpherson** [swagger-api/swagger-ui#4448]
In an older version of the SwaggerUI when you did the OAuth2 flow to provide authentication, the screen where you selected your scopes was different and didn't show the client ID or (more importantly) client secret.

I have upgraded the version of the package I am using and now the client secret is shown in plain text... how can I hide that?

**Comment by shockey** [comment]
Hi @garymacpherson! Thanks for filing an issue.

There's no way to do this currently unfortunately, but it would be a relatively simple change (great opportunity to file a PR!).

**Comment by webron** [comment]
Let's be clear on something though - whether we hide it from the UI or not, the user can still have access to it as it's embedded in the application itself as part of the configuration, and that's reachable to any user. We _know_ this is vulnerable, and that's the downside of using this kind of authentication in a browser-based application. In short, while we should hide it from the UI, you should _not_ use a real production value in the UI, unless you're willing to take the risk of exposing it.
