### ISSUE TITLE
Upgrade to OAS 3.0.0

### ISSUE THREAD

**Issue by kritika0205** [swagger-api/swagger-ui#4449]
How to migrate from swagger editor 2.0 to swagger 3.0

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature
| Which Swagger/OpenAPI version?  | 3.0
| Which Swagger-UI version?       | 3.0
| How did you install Swagger-UI? | 
| Which browser & version?        | chrome
| Which operating system?         | windows 10

### Demonstration API definition

I have my APIs written in swagger editor 2.0, but I need features which are there in OAS 3.0.0, do we need to install any other editor separately to access the features or we can simply start the project in swagger editor 2.0 itself with OAS 3.0.0 support, please help in guiding me through this transition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by shockey** [comment]
Hi @kritika0205, Swagger-Editor 3.0 supports editing both Swagger/OpenAPI 2.0 and OpenAPI 3.0 out of the box :smile:

**Comment by kritika0205** [comment]
Hi Shockey,

Thanks alot for the reply, can you please guide me if we have to install Swagger-Editor 3.0 separately, if so then from where can i have it.

I am working with Swagger2.0 currently.

I am just a beginner in this, help would really highly be appreciated.

**Comment by kritika0205** [comment]
@shockey

**Comment by hkosova** [comment]
@kritika0205 go to http://editor.swagger.io and paste the following:
```yaml
openapi: 3.0.1
info:
  title: sample
  version: 1.0.0
paths: {}
```
That's it! You now have a minimal OpenAPI 3.0 spec. Check out our [OpenAPI 3.0 syntax guide](https://swagger.io/docs/specification/basic-structure/) for more examples.

**Comment by hkosova** [comment]
@kritika0205 You are using the old Editor 2.x. The new editor is online at http://editor.swagger.io, and you can also install it locally [as explained here](https://github.com/swagger-api/swagger-editor#running-locally).

**Comment by kritika0205** [comment]
Hi Gonen,
thanks for the reply, i will refer it, also can you please check issue Not able to give an option of choice in parameter of requestbody · Issue #4471 · swagger-api/swagger-ui,

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Not able to give an option of choice in parameter of requestbody · Issue...

I have an API which takes an array of integer or "all" in request body of id and perform the required function a...
 |

 |

 |



I am stuck in it, any suggestions or help would highly be appreciated, thanks in advance
    On Tuesday, 24 April, 2018, 1:55:00 PM IST, Gonen Dukas <notifications@github.com> wrote:  
 
 
@kritika0205, please this document on how to convert your swagger 2 definition file into OpenAPI 3:
https://blog.runscope.com/posts/tutorial-upgrading-swagger-2-api-definition-to-openapi-3

Also, it contains a converter to do it automatically for you:
https://openapi-converter.herokuapp.com/

Enjoy!
