### ISSUE TITLE
Authentication with keycloak.js

### ISSUE THREAD

**Issue by wijdench** [swagger-api/swagger-ui#4450]
Hi, i used keycloak.js to authenticate the html file on swagger doc
(swagger-ui-dist@3.13.2)

```
<div id="swagger-ui"></div>
<script type="text/javascript" src="./swagger-ui-bundle.js"> </script>
<script type="text/javascript" src="./swagger-ui-standalone-preset.js"> </script>
<script type="text/javascript" src="https://auth.taiga.voyage/auth/js/keycloak.js"></script>
<script>
    var keycloak = Keycloak({
      "realm": "realmName",
      "url": "url",
      "clientId": "clientId"
    });
      keycloak.init({ onLoad: 'login-required' });
</script>
<script>
  const DisableTryItOutPlugin = function() {
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    }
  }
}

const HideInfoUrlPartsPlugin = () => {
    return {
      wrapComponents: {
        InfoUrl: () => () => null
      }
    }
  }
  
window.onload = function() {
  
  // Build a system
  const ui = SwaggerUIBundle({
    url: "./swagger.json",
    urls: [
    {
      url:"./swagger.json",
      name: 'Docs1'
     },
    {
      url: 'http://Docs2',
      name: 'Docs2'
    },
    {
      url: 'http://Docs3',
      name: 'Docs3'
    },
    ],
    validatorUrl: null,
    dom_id: '#swagger-ui',
    requestInterceptor: (req) => {
      if (req.loadSpec) {
      keycloak.updateToken(5).success(function() {
      req.headers = { 'authorization': 'Bearer ' + keycloak.token }; 
      
    });
    
    }
    return req;
  },
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl,
      DisableTryItOutPlugin,
      HideInfoUrlPartsPlugin
    ],
    layout: "StandaloneLayout",

  })
  window.ui = ui
}
</script>
</body>
</html>

```
I have an issue about requestInterceptor, i need to update the token to insert the token in header request.
the spec url return 'Fetch errorInternal Server Error' before the execution the success of keycloak updateToken.

**Comment by shockey** [comment]
Hi @wijdench, this is because you're using a synchronous requestInterceptor with an asynchronous call to your Keycloak client.

Try this out:

```js
  requestInterceptor: (req) => {
    return new Promise(resolve => {
      if (req.loadSpec) {
        keycloak.updateToken(5).success(function() {
          req.headers = { 'authorization': 'Bearer ' + keycloak.token };
          resolve(req);
        });
      } else {
        resolve(req)
      }
    })
  },
```

**Comment by wijdench** [comment]
Hi, it works well now when i change the spec url, thanks for your support.

But when i refresh the page with url: /api-docs/index.html/?urls.primaryName=Docs2 it returns an empty page with loading icon. and it doesn't send the request for Doc2 or Doc3

`const ui = SwaggerUIBundle({
    urls: [
    {
      url:"./swagger.json",
      name: 'Docs1'
     },
    {
      url: 'http://Docs2',
      name: 'Docs2'
    },
    {
      url: 'http://Docs3',
      name: 'Docs3'
    },
    ],`
am i missing something?

**Comment by shockey** [comment]
@wijdench, `Failed to refresh token` is outside of Swagger-UI's scope - you'd need to dig into what Keycloak and your server is doing in order to get to the bottom of that error.

Did you end up figuring this out?

**Comment by wijdench** [comment]
Hi, 
not yet, on window.onload the keyckloak is initialized but the token is not created yet.

**Comment by shockey** [comment]
@wijdench, I see. Consider not initializing Swagger-UI until your token is created 😄

**Comment by wijdench** [comment]
Hi,
After keycloak is initialized, it send asynchronously another request to get it's token.
in keycloak.js file:
            req.onreadystatechange = function () {
                if (req.readyState == 4) {
                    if (req.status == 200) {
                        kc.profile = JSON.parse(req.responseText);
                        promise.setSuccess(kc.profile);
                    } else {
                        promise.setError();
                    }
                }
            }

this event is fired after the page in completely loaded. i can't find another event to initialize Swagger-UI.

**Comment by wijdench** [comment]
Hi, i found the solution, it's to initialize Swagger-UI on success event of keycloak configuration.
