### ISSUE TITLE
How to define response of file type

### ISSUE THREAD

**Issue by kritika0205** [swagger-api/swagger-ui#4451]
How to define response type with have number as well as file content retrieved.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 2.0
| How did you install Swagger-UI? | 
| Which browser & version?        | chrome
| Which operating system?         | windows 10

### Demonstration API definition

{
    "test_instance_id": 1234,
    "test_id": 102,
    "call_recording":<File_Contents>
}
I have to define above response, i am trying to use following code-
responses:
        # Response code
        '200':
          description: Call result fetched successfully.
          schema:
            "$ref": "#/definitions/call_recording"

And in definition, i am defining this-
call_recording:
    
    properties:
      
      test_instance_id:
        type: number
      test_id:
        type: number
      metric_result:
        type: file

But I am getting error for type: file, how can we get the response

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by hkosova** [comment]
How is the file content returned? E.g. as plain text, base64, etc.

**Comment by kritika0205** [comment]
plain text

**Comment by kritika0205** [comment]
@hkosova my file is of plain text and I am working with Swagger2.0

**Comment by hkosova** [comment]
Plain text is `type: string`.

`type: file` is not used inside JSON.

**Comment by kritika0205** [comment]
Thanks, it worked
