### ISSUE TITLE
The "configUrl" property causes a 401 when Swagger UI is behind basic authentication

### ISSUE THREAD

**Issue by SnuktheGreat** [swagger-api/swagger-ui#4453]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.13.4
| How did you install Swagger-UI? |  copied from dist
| Which browser & version?        | Chrome
| Which operating system?         | Linux

### Problem

We are using the `configUrl` to get a list of URLs that point to Swagger specifications for several of our services. This works fine if the service is exposed without authentication, but when Basic Authentication is present, the `fetch` method causes a 401. This happens after the user already supplied basic authentication credentials to get the `index.html` in the first place and all other calls requiring the same authentication work properly.

Our configuration looks like this:

```javascript
const ui = SwaggerUIBundle({
  configUrl: "/swagger-ui-configuration",
  dom_id: '#swagger-ui',
  deepLinking: true,
  presets: [
    SwaggerUIBundle.presets.apis,
    SwaggerUIStandalonePreset
  ],
  plugins: [],
  layout: "StandaloneLayout",
  validatorUrl: null
});
```

### Expected Behavior

The user supplied credentials to get to Swagger UI. These credentials are also used to load the configuration.

### Current Behavior

The user supplied credentials to get to Swagger UI. Swagger UI calls the configuration without these credentials, causing a 401.

### Possible Solution

In `src/core/plugins/configs/index.js`:

```javascript
// is currently
return fetch(url)
// should be something like
return fetch({url: url, credentials: "same-origin"})
```

I can open a PR with these changes if desired. I expect however that there are considerations I may have missed, since I'm a back-end engineer and basically hacked this in.

### Context

We run the typical microservice architecture, where many APIs are available via one edge service that acts as a proxy. Consumers of our APIs use the Swagger UI bundled with our edge service to have all the documentation in once place. Since we are using service discovery, using the `configUrl` property seemed like the best way to go.

**Comment by shockey** [comment]
Hi @SnuktheGreat! Thanks for filing a ticket.

Though I agree with what you're getting at, I'm wary about changing the credentials option - no doubt changing it would break _someone's_ implementation.

IMO, it'd be better for the config fetcher to allow users to modify the fetch request before it goes out through the existing `requestInterceptor` config option, perhaps with a helpful `loadRemoteConfig` flag to help identify relevant requests.

This would be a small fix, and it sounds like it's significantly blocking your adoption of Swagger-UI, so I'm going to do my best to address this within the next week or two :smile:

**Comment by SnuktheGreat** [comment]
That would be great! Thanks for the rapid response.
