### ISSUE TITLE
Swagger ui are changing path variables for html codes.

### ISSUE THREAD

**Issue by iaguera** [swagger-api/swagger-ui#4461]
Swagger ui are changing path variables for html codes.

Using the swagger ui example of http://petstore.swagger.io/v2/swagger.json, when i POST on /pet/{petId} some value for example "23/" swagger ui change slash character to html code in this case swagger ui changes path value to "23%2", for endpoints whose needs explicit slash character, they will be never called with that behavior. (yeah i know the slash is wrong character for this endpoint its a example).

 Bug or feature request? 
 **I think this is a bug.**
Which Swagger-UI version?
**v3.0.5**
How did you install Swagger-UI? 
**docker container**
Which browser & version? 
**Version 65.0.3325.181 (Official Build) (64-bit)**
Which operating system? 
**MAC OS**

Links of behavior issue:

https://drive.google.com/file/d/11nIYY9popxTaSO-ZNMzhUlQUso6njNo4/view

https://drive.google.com/file/d/11lOpn71b7m9qFFK4YFa42RK4mtm4gBUk/view

### Expected Behavior
When using endpoint with parameter type path must maintain characters like "/".

### Current Behavior
Endpoints with parameter type path are changing characters like "/" to html code "%2".

### Possible Solution
Maintain character inputed by user.

### Context
I cannot use swagger ui with "dynamic" endpoint.

**Comment by shockey** [comment]
Hi @iaguera!

I'm inclined to say that this is the intended behavior - path parameters are generally meant to serve as a placeholder for one segment of a URL. I imagine allowing literal `/` in path parameter template values would make router matching logic much more complex for server-side tooling.

Swagger/OpenAPI 2.0 doesn't explicitly mention anything about percent-encoding (which is confusing), but OpenAPI 3.0 specifically indicates that all parameters present in a URL should be percent-encoded unless `allowReserved: true` is set.

@webron, @hkosova - any thoughts on this?

**Comment by iaguera** [comment]
Hi @shockey,

Thanks for the answer, on swagger ui container, i think It is not possible, send this parameter right?

Can we change this issue intead of a fix to a feature or something like that?

**Comment by hkosova** [comment]
@iaguera OpenAPI does not support unencoded `/` in path parameters. Here's the corresponding feature request - https://github.com/OAI/OpenAPI-Specification/issues/892.

**Comment by webron** [comment]
As @hkosova and @shockey said, this is the intended behavior. Path parameters, at the moment, cannot contain additional path segments. This is an intentional limitation in the spec.
