### ISSUE TITLE
UI get stuck on loading image

### ISSUE THREAD

**Issue by gonenduk** [swagger-api/swagger-ui#4466]
Using swagger-ui-dist version 3.13.5 on Windows.
Happens with chrome 65, 66 and latest Edge.

When the loading image (black circle turning around itself) is shown it gets stuck (stop cycling) and the browser doesn't respond anymore.
Happens when using OpenAPI 3 files. With version 2 of the files it is working well.

Attached is a screen shot:
![loading](https://user-images.githubusercontent.com/1597854/39092854-b1f30b60-461e-11e8-9704-a3350bc8cabe.jpg)

**Comment by jemerald** [comment]
I'm having a similar issue with swagger v2 file, see #4467

**Comment by shockey** [comment]
Hey @gonenduk, sorry for the trouble here.

I believe I've fixed the issue by testing @jemerald's example - can you give this build a try, and see if it solves your issue as well? http://crowded-squirrel.surge.sh

As for a release, I'm going to bring this up tomorrow and see what we can do to get this patch out.

**Comment by gonenduk** [comment]
Hey,
I cannot upload or access my yaml file from the build you provided, so I'm sending a minimum version of my yaml which reproduces the issue on my local machine.

[api3.zip](https://github.com/swagger-api/swagger-ui/files/1937335/api3.zip)

**Comment by shockey** [comment]
Looks like it works! http://crowded-squirrel.surge.sh/?url=https://gist.githubusercontent.com/shockey/852d839ad3540c797b027281e1fe565e/raw/a8c31235c303c9f89be41cedb86d824542f0aae6/api3.yaml

**Comment by gonenduk** [comment]
Great job!
And now the obvious question: when can we have the fix? 😁

**Comment by shockey** [comment]
Looks like we will be doing a hotfix for this, so you can expect one today... right after I do some more testing :smile:

**Comment by jemerald** [comment]
@shockey if you can, please also make a release for swagger-editor too. Thanks
