### ISSUE TITLE
Accept header is hardcoded to "application/json"

### ISSUE THREAD

**Issue by davidecavestro** [swagger-api/swagger-ui#447]
It seems that the `Accept` header for swagger-ui requests is [fixed to `application/json`](https://github.com/wordnik/swagger-ui/blob/master/dist/lib/swagger.js#L352).
This becomes cumbersome when you have an API service that - among other things - let you upload/download attachments. Also because swagger-ui supports files upload.

**Comment by malcolmsparks** [comment]
@fehguy Atleast in versions 2.1.4 and 2.1.8-M1 it's still sending `Accept: application/jso` to the following swagger spec:-

```javascript
{"swagger":"2.0","info":{"title":"Hello World!","version":"1.0","description":"A swaggered String"},"produces":[],"consumes":[],"paths":{"/hello":{"get":{"produces":["text/plain"],"responses":{"default":{"description":""}}}}},"basePath":"/hello-swagger","definitions":{}}
```

This is a shame because it used to work properly. `application/json` is just any other media-type - there's no reason to privilege it.

**Comment by fehguy** [comment]
@malcolmsparks please open a new issue if you're seeing this.

**Comment by prativapokhrel** [comment]
I had the same issue and I tried to hardcode the swagger.js file which actually worked for me. I changed "responseContentType = application/json" to "responseContentType = value of accepts parameter". Hope it works for you as well :)
