### ISSUE TITLE
Swagger-ui v2.2.10 does not have an on/off authentication switch

### ISSUE THREAD

**Issue by harald-quist-stratsys** [swagger-api/swagger-ui#4470]
Downloaded commit 64dc306 and ran the dist/index.hml. The on/off switch for the authentication seems to be missing. Turns out this stopped working in v.2.1.5. This new "style" can be seen in 
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/version-detection.md#swagger-ui-2x-and-under 
I can't imagine that this behaviour is deliberate, as it is much less intuitive now how the authentication works.   

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 2.2.10
| How did you install Swagger-UI? | dist/index
| Which browser & version?        | Any
| Which operating system?         | Win 10

### Demonstration API definition
Petstore sample

### Expected Behavior

The On/Off switch should be reintroduced, or the authentication flow should somehow be made more intuitive. In v.3 the padlock is introduced, making it more intuitive. Maybe this can be done in v.2 as well. 

### Current Behavior

No switch, only exclamation mark.

**Comment by shockey** [comment]
Hi @harald-quist-stratsys! We're no longer working on the 2.x series of the UI, so you should upgrade to v3 if you'd like to take advantage of the newer features.

Thanks for the report regardless - and thanks for using Swagger!

**Comment by harald-quist-stratsys** [comment]
This is not a new feature, but a feature you removed in v.2.1.5. There is still code related to this on/off switch in the code, for example in swagger-oauth.js, there's reference to the `api-ic` - element in multiple places.
```
window.onOAuthComplete = function onOAuthComplete(token,OAuthSchemeKey) {
  if(token) {
    if(token.error) {
      var checkbox = $('input[type=checkbox],.secured')
      checkbox.each(function(pos){
        checkbox[pos].checked = false;
      });
      alert(token.error);
    }
    else {
      var b = token[window.swaggerUi.tokenName];      
      if (!OAuthSchemeKey){
          OAuthSchemeKey = token.state;
      }
      if(b){
        // if all roles are satisfied
        var o = null;
        $.each($('.auth .api-ic .api_information_panel'), function(k, v) { 
          var children = v;
          if(children && children.childNodes) {
            var requiredScopes = [];
            $.each((children.childNodes), function (k1, v1){
              var inner = v1.innerHTML;
              if(inner)
                requiredScopes.push(inner);
            });
            var diff = [];
            for(var i=0; i < requiredScopes.length; i++) {
              var s = requiredScopes[i];
              if(window.enabledScopes && window.enabledScopes.indexOf(s) == -1) {
                diff.push(s);
              }
            }
            if(diff.length > 0){
              o = v.parentNode.parentNode;
              $(o.parentNode).find('.api-ic.ic-on').addClass('ic-off');
              $(o.parentNode).find('.api-ic.ic-on').removeClass('ic-on');

              // sorry, not all scopes are satisfied
              $(o).find('.api-ic').addClass('ic-warning');
              $(o).find('.api-ic').removeClass('ic-error');
            }
            else {
              o = v.parentNode.parentNode;
              $(o.parentNode).find('.api-ic.ic-off').addClass('ic-on');
              $(o.parentNode).find('.api-ic.ic-off').removeClass('ic-off');

              // all scopes are satisfied
              $(o).find('.api-ic').addClass('ic-info');
              $(o).find('.api-ic').removeClass('ic-warning');
              $(o).find('.api-ic').removeClass('ic-error');
            }
          }
        });
        window.swaggerUi.api.clientAuthorizations.add(window.OAuthSchemeKey, new SwaggerClient.ApiKeyAuthorization('Authorization', 'Bearer ' + b, 'header'));
        window.swaggerUi.load();
      }
    }
  }
};
```

**Comment by webron** [comment]
@harald-quist-stratsys unfortunately, it doesn't matter. We don't have the capacity or ability to look into changes around versions earlier than 3.0. You can continue using those versions as-is, or update to the latest and get support on those versions.
