### ISSUE TITLE
What is the use of <swagger dir="ui"> tag, can we have a desired name directory instead of "ui" using this tag ? so that in the target directory with desired name will  created ?

### ISSUE THREAD

**Issue by saru17** [swagger-api/swagger-ui#4477]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by webron** [comment]
Please re-submit the ticket filling the issue template. It contains crucial information for us to be able to provide you with the support you seek.
