### ISSUE TITLE
File upload works but the response rendering shows an "undefined" request url and "no content" response body

### ISSUE THREAD

**Issue by davidecavestro** [swagger-api/swagger-ui#448]
I have an api operation providing file upload features.
Sending the request from swagger-ui works like a charm, but when the server returns a successful response swagger-ui shows _undefined_ as Request url and _no content_ as response body.
It's quite strange because the server response is valid json. Simply the request was a _multipart/form-data_ instead of the usual _application/json_ and the api operation.
This is how the api operation is defined within swagger json configuration took from swagger-jaxrs

```
{
   "method":"POST",
   "summary":"Uploads new file contents...",
   "notes":"",
   "type":"mytype",
   "nickname":"upload",
   "produces":[
      "application/json"
   ],
   "consumes":[
      "multipart/form-data"
   ],
   "authorizations":{

   },
   "parameters":[
      {
         "name":"id",
         "description":"the id ...",
         "required":true,
         "type":"integer",
         "format":"int32",
         "paramType":"path"
      },
      {
         "name":"file",
         "required":false,
         "type":"File",
         "paramType":"body"
      }
   ]
}
```

**Comment by nayandas88** [comment]
I am facing the same issue.I am using swagger core 2.10 but the issue is not fixed yet.Could you please help?

**Comment by webron** [comment]
@nayandas88 - you're using an old version of swagger-core. Please consider upgrading.
