### ISSUE TITLE
Is there a way to generate static API documentation via swagger in a specific format ?

### ISSUE THREAD

**Issue by devdream02** [swagger-api/swagger-ui#4486]
Hi Team,

What i am looking for is a way to generate the API documentation in a specific table like format.

Is there a way that the documentation can be generated from the template i provide.?

Looking forward for some direction.

Thanks & Regards,
Dev

**Comment by webron** [comment]
Take a look at the https://github.com/swagger-api/swagger-codegen project.

**Comment by heldersepu** [comment]
That is pretty cool that the codegen can do something like that, I've only use it to generate client code to consume the API, but yes same engine could be pointed to a different template an bamm:
https://raw.githack.com/swagger-api/swagger-codegen/master/samples/html/index.html

**Comment by devdream02** [comment]
Hi @heldersepu , @webron 

Thanks for suggestion.
I am able to generate the format i wanted by creating a moustache template of my own.

The only issue i am facing now is, i want to render the request example in the generated output but i can't find the corresponding mustache variable for the same.

For eg. - For POST request, the body looks like below json which is generated by spec file.
{
  "key":"value"
}

Is there a way to get this example in the mustache code.

**Comment by heldersepu** [comment]
@devdream02 I think that question will be more appropriate on the codegen project...
