### ISSUE TITLE
Long processing request executed several times

### ISSUE THREAD

**Issue by dlarr** [swagger-api/swagger-ui#4487]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | @version v2.1.4
| How did you install Swagger-UI? | Using node framework swagger-tools
| Which browser & version?        | Firefox 64 bits 59.0.2
| Which operating system?         | Windows

I have a service using a file as form-data. The file is kinda big (3M lines) and processing it is long.
When I launch the service with [try out] button, the service starts and take a long time (say 10 minutes) after a while, apparently, other requests are launched.

This behaviour does **NOT** appears if I close swagger-ui tab after launching the request.

### Demonstration API definition

Here is the description of the service used : 

```yaml
/hexavia/full:
    post:
      tags:
      - "hexavia"
      summary: "Supprime toutes les entrées de la table hexavia et recrée toutes les\
        \ entrée à partir du fichier fourni"
      description: ""
      operationId: "fullHexavia"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "hexaviaFile"
        in: "formData"
        description: "Le fichier complet HEXAVIA"
        required: true
        type: "file"
      responses:
        200:
          description: "successful operation"
        405:
          description: "Paramètre d'entrée invalide"
      x-swagger-router-controller: "Hexavia"
```

### Configuration (browser query string, constructor, config.yaml)

I don't know I am user swagger-tools framework, here is my server code:

```js
'use strict';

var fs = require('fs'),
    path = require('path'),
    http = require('http');

var app = require('express')();
var swaggerTools = require('swagger-tools');
var jsyaml = require('js-yaml');

const env = process.env.NODE_ENV || "local";
console.log('env => ', env);
const config = require('./config/config')[env];
const serverPort = config.referentielPort;

// swaggerRouter configuration
var options = {
  swaggerUi: path.join(__dirname, '/swagger.json'),
  controllers: path.join(__dirname, './controllers'),
  useStubs: process.env.NODE_ENV === 'development' // Conditionally turn on stubs (mock mode)
};

// The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
var spec = fs.readFileSync(path.join(__dirname,'api/swagger.yaml'), 'utf8');
var swaggerDoc = jsyaml.safeLoad(spec);

// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {

  // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
  app.use(middleware.swaggerMetadata());

  // Validate Swagger requests
  app.use(middleware.swaggerValidator());

  app.use(function (err, req, res, next) {
      // All errors that swagger-tools creates/handles are sent downstream via `next`.  This
      // means that all errors swagger-tools creates/handles will be sent here and can be
      // handled as your application deems fit.
      console.log('err', err);
      console.log('req', req);
      console.log('res', res);
      console.log('next', next);
      res.status(500)
      res.send({ error: err })
  });

  // Route validated requests to appropriate controller
  app.use(middleware.swaggerRouter(options));

  // Serve the Swagger documents and Swagger UI
  app.use(middleware.swaggerUi());

  // Start the server
  http.createServer(app).listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
    console.log('Swagger-ui is available on http://localhost:%d/docs', serverPort);
  });

});
```

### Expected Behavior
Request executed only once, even the processing time of the HTTP request is long

### Current Behavior
Request executed several times, at regular interval of time

### Possible Solution
no idea

### Context
Clearing & Feeding a database table with the file content

Thank you for any inputs :)

**Comment by heldersepu** [comment]
Try with the latest version of the UI v2.x is no longer supported

**Comment by dlarr** [comment]
Hello and thx for answering back here :)

I was using 2.X for visual convenience, as more of the service URL can be displayed.

I Will give it a try though. thank you !

**Comment by heldersepu** [comment]
Can you elaborate a bit more on that visual convenience...

**Comment by dlarr** [comment]
Sorry I didn't see your question. Here are my problems against V3.X

1. With v2.X There are a lot more of service lines that are displayed (16 services here)
![image](https://user-images.githubusercontent.com/2865021/39524088-30e09a86-4e18-11e8-9d67-de0656dfbf0b.png)

2. There are numbers of link enabling group manipulation that are really practical, unless I am mistaken, these aren't part of the 3.X UI : 
![image](https://user-images.githubusercontent.com/2865021/39524154-5980f13e-4e18-11e8-881d-ed0321d7671e.png)


(Sorry for delayed answer)

**Comment by heldersepu** [comment]
Yes there have been complaints about the size of the elements on UI 3.x:
https://github.com/swagger-api/swagger-ui/issues/4458

About the:  Show/Hide,  List Operations,   Expand Operations I personally never used them...
The latest has a [filter by tag] feature that is way better than those

**Comment by dlarr** [comment]
Hello,

I reopen this issue because this behaviour is still going on with 3.X

I have a long processing webservice (15 minutes to process) and swagger will always relaunch a request without any action after a while.

**Comment by dlarr** [comment]
Closing again the issue. It had nothing to do with swagger-ui. I Changed the timeout setup for node

```js
  const server = app.listen(serverPort, function() {
      // debug('Express server listening on port ' + server.address().port);
        console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
        console.log('Swagger-ui is available on http://localhost:%d/docs', serverPort);
  });
  server.timeout = 1500000;
```

You can even setTimeout to infinity for a request : 
```js
module.exports.fullHexavia = function fullHexavia (req, res, next) {
  req.setTimeout(0);
  var hexaviaFile = req.swagger.params['hexaviaFile'].value;
  Hexavia.fullHexavia(hexaviaFile)
    .then(function (response) {
      utils.writeJson(res, response);
    })
    .catch(function (response) {
      utils.writeJson(res, response);
    });
};
```

But the behaviour in case node hangsout after timeout is strange : swagger launches another request.
