### ISSUE TITLE
highlighting large response bodies kills browser

### ISSUE THREAD

**Issue by rshan2** [swagger-api/swagger-ui#449]
Bypassing the hljs.highlightBlock call resolves the issue. See below.

    OperationView.prototype.showStatus = function(data) {
      var code, content, contentType, headers, pre, response_body;
      content = data.content.data;
      headers = data.getHeaders();
      contentType = headers["Content-Type"];
      if (content === void 0) {
        code = $('<code />').text("no content");
        pre = $('<pre class="json" />').append(code);
      } else if (contentType.indexOf("application/json") === 0 ||  contentType.indexOf("application/hal+json") === 0) {
        code = $('<code />').text(JSON.stringify(JSON.parse(content), null, 2));
        pre = $('<pre class="json" />').append(code);
      } else if (contentType.indexOf("application/xml") === 0) {
        code = $('<code />').text(this.formatXml(content));
        pre = $('<pre class="xml" />').append(code);
      } else if (contentType.indexOf("text/html") === 0) {
        code = $('<code />').html(content);
        pre = $('<pre class="xml" />').append(code);
      } else {
        code = $('<code />').text(content);
        pre = $('<pre class="json" />').append(code);
      }
      response_body = pre;
      $(".request_url").html("<pre>" + data.request.url + "</pre>");
      $(".response_code", $(this.el)).html("<pre>" + data.status + "</pre>");
      $(".response_body", $(this.el)).html(response_body);
      $(".response_headers", $(this.el)).html("<pre>" + JSON.stringify(data.getHeaders()) + "</pre>");
      $(".response", $(this.el)).slideDown();
      $(".response_hider", $(this.el)).show();
      $(".response_throbber", $(this.el)).hide();

      //Can't highlight large response bodies. 100K limit is arbitrary.
	  if( headers['Content-Length'] < 100000 ) {
	      return hljs.highlightBlock($('.response_body', $(this.el))[0]);
          }
	  else {
	      return $('.response_body', $(this.el))[0];
          }
    };

**Comment by fehguy** [comment]
OK we have the ability to disable the highlight rendering however there may be other renderers which are more efficient.  I'll open a separate ticket for this.
