### ISSUE TITLE
Support response examples for alternative media types

### ISSUE THREAD

**Issue by simonoakesepimorphics** [swagger-api/swagger-ui#4500]
I'm not totally sure if this is a bug or a feature request, but I think the behaviour is in conflict with the OpenAPI Specification so I have labelled it as a bug. I hope you'll correct me if I'm wrong.

I would like to be able to document an API endpoint which responds with `text/csv` format by providing an example response. Currently it is possible to specify an `example` of a media type on an API response object ([OpenAPI spec](https://swagger.io/specification/#mediaTypeObject)), however this is not rendered in the Swagger UI. The description of the property in the specification implies that this example should have precedence over any others, so I would expect it to be visible whether there is an example specified for the response schema or not.

The specification says:
> Example of the media type. The example object SHOULD be in the correct format as specified by the media type. The example field is mutually exclusive of the examples field. Furthermore, if referencing a schema which contains an example, the example value SHALL override the example provided by the schema.

As a workaround I have tried associating the example with the response schema, which does appear on the UI. However this isn't an adequate solution for my particular case. When the `example` property is given in this way, new lines are rendered as `\n`, and the text is enclosed in quotes. This is inappropriate for specifying examples in CSV format.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug
| Which Swagger/OpenAPI version?  | 3.0.1
| Which Swagger-UI version?       | 3.13.6
| How did you install Swagger-UI? | Using maven: org.webjars.swagger-ui.3.13.6
| Which browser & version?        | Chrome 65.0.3325.181
| Which operating system?         | Mac OS High Sierra 10.13.4

```yaml
openapi: 3.0.1
info:
  title: Demo App
  description: |
    Swagger UI response example
  version: '0.1'
paths:
  /example:
    description: Example
    get:
      description: Example GET
      responses:
        '200':
          description: Success
          content:
            text/csv:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        label:
                          type: string
                        type:
                          type: string
                example: |-
                  type, label
                  type A, name A
              example: |-
                type, label
                type B, name B
```
Replicated on Swagger Editor (https://editor.swagger.io/)

### Expected Behavior
* Media type example should override schema example
* New lines should be represented in the example value
* Example value should not be enclosed in quotes

### Current Behavior
* Media type example is not visible
* New lines are respresented as `\n`
* Example value is enclosed in quotes

**Comment by webron** [comment]
Thanks - we qualify this as a feature and not a bug, because it was never implemented. See #3437.
