### ISSUE TITLE
I want to add a new property readCreate similar to readOnly, what are the steps 

### ISSUE THREAD

**Issue by srirnetapp** [swagger-api/swagger-ui#4503]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by shockey** [comment]
@srirnetapp, you should propose any changes to the OpenAPI Specification at https://github.com/OAI/OpenAPI-Specification/issues, not here 😄
