### ISSUE TITLE
allOf merges $ref schemas outside of allOf

### ISSUE THREAD

**Issue by toobulkeh** [swagger-api/swagger-ui#4510]
When using allOf combining $ref and inline schemas, all times the $ref is used are also updated to the inline-schema.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | Swaggerhub SmartBear
| How did you install Swagger-UI? | swaggerhub.com
| Which browser & version?        |  Chrome Latest
| Which operating system?         |  MacOS

### Demonstration API definition

```yaml
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          minimum: 100
          maximum: 600
        message:
          type: string
    UnauthorizedError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            code:
              example: 401
            message:
              example: "Unauthorized"
    NotFoundError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            code:
              example: 404
            message:
              example: "Resource Not Found"
```

### Expected Behavior
The example `404` should only appear for the `NotFoundError` $ref.

```yaml
components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
```

### Current Behavior
The example `404` also appears for the `UnauthorizedError` $ref.

```yaml
components:
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
```

**Comment by webron** [comment]
Thanks for the report, @toobulkeh. The OSS and SwaggerHub versions are similar, but not identical. Testing your definition in the OSS version, it renders as you'd expect. In this case, you should reach out to the in-app support in SwaggerHub, which is available through the chat icon at the top right bar.

**Comment by shockey** [comment]
Yep, this is a bug!

I was just working in this area of Swagger-Client for https://github.com/swagger-api/swagger-js/pull/1275, so I went ahead and patched this while my memory was fresh.

**Comment by shockey** [comment]
Also, @toobulkeh - were you seeing this in the Editor?

I can definitely get this to happen in Swagger-Client directly, but haven't found a way to reproduce this in the UI/Editor.

**Comment by toobulkeh** [comment]
@shockey yes, I mainly use the SwaggerHub in-browser editor right now, and only noticed it there.
