### ISSUE TITLE
Integrating an own component for ApiKeyAuth via Plugin API doesn't work

### ISSUE THREAD

**Issue by ChristophWalter** [swagger-api/swagger-ui#4517]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug (probably)
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.13.4
| How did you install Swagger-UI? | via npm/webpack
| Which browser & version?        | Safari 11.1
| Which operating system?         | MacOS 10.13.4

In our project we use the plugin api to override several components, such as InfoUrl and InfoBasePath which works like expected. If we try the same for the component ApiKeyAuth it doesn't have any impact to our UI, even if we cancel it out completely:

```js
export const ApiKeyAuthPlugin = () => {
	return {
		components: {
			ApiKeyAuth: () => null
		}
	}
}
```
### Demonstration API definition

```json
"security": [
	{
		"api_key": []
	}
],
"securityDefinitions": {
	"api_key": {
		"in": "header",
		"name": "x-api-key",
		"type": "apiKey",
	}
},
```

### Expected Behavior

With the above described plugin, the component should be cleared out which should result in an empty modal in our UI.

### Current Behavior

Nothing happens. The UI looks like without a plugin at all.

### Context

We need to set a default apiKey for our tryout requests from swagger-ui. So the users can decide whether they want to use the default one or their own. Therefore, we want to display the apiKey as a default in the authorization modal. Additionally this apiKey should even be set as default before the user clicks authorize. As this is not possible with the current swagger-ui, we want to create our own plugin to overwrite the apiKeyAuth component.

**Comment by hkosova** [comment]
The default API key can be set using [`preauthorizeApiKey`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#instance-methods). This is supported in Swagger UI 3.13.0+. Is this what you are looking for?

```
// index.html

const ui = SwaggerUIBundle({
  url: "https://my.api.com/swagger.yaml",
  ...
  onComplete: function() {
    ui.preauthorizeApiKey("api-key", "abcde12345");
  }
})
```

**Comment by ChristophWalter** [comment]
Thanks for your fast response. For this specific case using `preauthorizeApiKey` might help us to find a solution. But in general it should be possible to overwrite every component with help of the plugin api, or am I wrong? 

Anyway, there are some more challenges to solve. Our current plan is to ship the default apiKey within the swaggerfile using a custom field, e.g.:
```
'security': [
	{
		'ApiKeyAuth': [],
		'x-default-apikey': 'abc123'
	}
],
```
How can we access this during SwaggerUI initialisation? Or how can we access `ui.preauthorizeApiKey ` using a plugin? And we need the same default token for oauth2, as not all of our apis use apikeys...

**Comment by ChristophWalter** [comment]
Hi @shockey!

Thanks a lot for your response. 👍 

> Try using apiKeyAuth instead of ApiKeyAuth 😄 component names are case-sensitive, and not 100% consistent across the project...

Using `apiKeyAuth` works, great!
 
---

I spotted `ui.specSelectors.specJson()` and started going deeper in deeper:
```js
ui.specSelectors.specJson()._list._tail.array.find(...)
```
Never worked with Immutable.js before, so thanks for this hint. Looks much better!

**Comment by shockey** [comment]
@ChristophWalter no problem! Immutable has a very powerful API, for this particular thing you can use `ui.specSelectors.specJson().getIn(["a", "deep", "path"])` to grab a value deeply within your data. Or you could always use `ui.specSelectors.specJson().toJS()` if you want a plain JS object 😄
