### ISSUE TITLE
npm run build fail

### ISSUE THREAD

**Issue by zhaojigang** [swagger-api/swagger-ui#4524]
hi, i add a param-model.js, and then customized parameter-row.js and base.js, and i execute the command "npm run build", errors occurs:
![image](https://user-images.githubusercontent.com/14085645/39680560-afc63332-51d4-11e8-84fd-d475b797c3f1.png)

then i "tail -500f /Users/jigangzhao/.npm/_logs/2018-05-07T00_51_18_454Z-debug.log"
![image](https://user-images.githubusercontent.com/14085645/39680592-098008d0-51d5-11e8-9cdb-763cda9625f9.png)

- OS: [macOS]
 - Swagger-UI version: [3.9.1]

**Comment by skykoradji** [comment]
I have the same problem.

**Comment by skykoradji** [comment]
It is caused by a package in swagger-client has the third party package that is not compatible with es6. I downgrade the swagger-ui to 3.0.21 and 'npm run build' is successful.  The other way is to fix this by eject your react-scripts and add customized uglify plugin into it.

**Comment by zhaojigang** [comment]
thanks a lot!!!  it works!!! @skykoradji
