### ISSUE TITLE
Nullable values are 0 by default

### ISSUE THREAD

**Issue by enemyofthedawn** [swagger-api/swagger-ui#4528]
I have nullable int  https://swagger.io/docs/specification/data-models/data-types/#null
```
"SomeObject": {
    "type": "object",
    "properties": {
        "something": {
            "format": "int32",
            "type": "integer",
            "nullable": true
        }
    }
}
```

but the default value in swagger ui for this int? property is 0, but it should be null.

**Comment by kojiDev** [comment]
@enemyofthedawn `nullable` means that property can be `null`, it is not a default value, swagger-ui I suppose tries to guess best suited default value/example. Default value of given type seems more informative that `null` so.

**Comment by heldersepu** [comment]
@enemyofthedawn use the `default` if you want to change that behavior
you can see an example here:
http://swagger-net-test.azurewebsites.net/swagger/ui/index#/Company/Company_Get2

@kojiDev 100% agree with you! the UI Default value of given type is more informative

**Comment by webron** [comment]
The responses above pretty much cover it.

**Comment by enemyofthedawn** [comment]
But I used default: null and it is still appearing as 0....

**Comment by heldersepu** [comment]
@enemyofthedawn can you provide your full spec?
