### ISSUE TITLE
Extension examples not rendering from API Mock Addon

### ISSUE THREAD

**Issue by toobulkeh** [swagger-api/swagger-ui#4529]
## Q&A
 - OS: macOS
 - Browser: Chrome
 - Version: SwaggerHub
 - Method of installation: SwaggerHub
 - Swagger-UI version: SwaggerHub Current
 - Swagger/OpenAPI version: OpenAPI 3.0

## Example Swagger/OpenAPI definition:
```yaml
components:
  schema:
    User:
      type: object
      properties:
        id:
          $ref: '#/x-partials/ID-ReadOnly'
x-partials:
  ID-ReadOnly:
    type: integer
    format: int32
    example: 1
    readOnly: true
```

### Describe the bug you're encountering
The ID renders in SwaggerUI example, but not the API Mock server:
![screen shot 2018-05-08 at 3 42 01 pm](https://user-images.githubusercontent.com/1342064/39779230-81ae3906-52d6-11e8-9f31-10d8fb9a1daa.png)

### To reproduce...

1. Go to this URL: https://app.swaggerhub.com/apis/Vaporware/WCS/0.6.0#/user/getUserById
2. Press "try it out"
3. Type in any ID
4. Press Execute
5. See difference between expected output and the API Mock Server

### Additional thoughts
I think this might have to do with an earlier spec I had and restarting the Mock addon -- but I've seen "restarted" that, and see no difference.

I also think it might just be the `x-partials` extension I'm using, which I'm using because [I don't want it in the Models section of SwaggerUI](https://stackoverflow.com/questions/50237256/reusable-component-outside-of-components-schema).

Thanks

**Comment by shockey** [comment]
Hi @toobulkeh,

Since you're a SwaggerHub user, please bring up this issue with their support - there's a `Chat with Support` button near the top right corner of the application.

Thanks for reaching out!
