### ISSUE TITLE
How can I debug swagger-ui when I modified the code?

### ISSUE THREAD

**Issue by zhaojigang** [swagger-api/swagger-ui#4532]
hi, I am a newcomer to react and redux, how can I debug swagger-ui when I modified the code?
 
 - OS: [macOS]
 - Browser: [chrome]
 - Swagger-UI version: [current master]

**Comment by shockey** [comment]
Hi @zhaojigang! Welcome 😄 

I suggest using Chrome's dev tools, [React DevTools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en), and [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) when working with Swagger-UI.
