### ISSUE TITLE
Model name is changed after expansion

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#4536]
## Q&A (please complete the following information)
 - OS: Windows 7
 - Browser: Chrome 66
 - Method of installation: http://editor.swagger.io
 - Swagger-UI version: 3.13.6
 - Swagger/OpenAPI version: 2.0, 3.0

### Content & configuration
Example Swagger/OpenAPI definitions

2.0:
```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: test
paths: {}

definitions:
  Error404:
    title: Not Found
```

3.0:
```yaml
openapi: 3.0.1
info:
  version: 0.0.0
  title: test
paths: {}

components:
  schemas:
    Error404:
      title: Not Found
```

### Describe the bug you're encountering
Consider a model with a `title` that is different from the model's key name in the `definitions` / `components/schemas` collection.
By default (when the models are collapsed), the displayed model name is the model's key name.
But after we expand a model, its displayed name changes to the `title`.
This can be confusing to the end-users of API docs.

### Steps to reproduce
1. Paste the spec above into the Editor.
2. Note the model name in the "Models" section.
3. Expand the model.
4. Note the model name in the "Models" section.

### Expected behavior
The model name should be the same before and after expansion.

### Actual behavior
The model name after expansion differs from the name before the expansion.

### Screenshots
![model-names](https://user-images.githubusercontent.com/8576823/39868926-6682aa24-5464-11e8-8a8d-f5d18a6503d1.png)

**Comment by shockey** [comment]
Gist: https://gist.github.com/shockey/ee8597766b556b6f23ef7e61c28855be
