### ISSUE TITLE
Bad render " Available authorizations" modal in case use pair of API Keys

### ISSUE THREAD

**Issue by DoroninVic** [swagger-api/swagger-ui#4545]
Hello.
My API use apiKey authorizations.
For use API methods client should send two headers:  X-APP-KEY and X-APP-ID
Security section has been configured like it says in docs for use keys together:
<pre>
security:
  - apiKey: []
    appId: []
</pre>
But if open "Available authorizations" for needed API method, it contain list with two different types of authorization. I think if the keys are used together, then in the modal window they should be displayed as one authorization method.

![image](https://user-images.githubusercontent.com/2978685/39934865-e4d969c6-554f-11e8-8da8-7e14b9ea2fa5.png)

Swager UI: v3.14.1

Test spec listing: 
<pre>
swagger: '2.0'
info:
  version: 1.0.0
  title: GATE API HTTP REST example
  termsOfService: 'http://mydomain.test/terms/'
host: mydomain.test
basePath: /ge/
schemes:
  - https
tags:
  - name: test
    description: For example
paths:
  /base/test:
    get:
      tags:
        - test
      summary: test method
      operationId: testMethod
      parameters:
        - name: id
          in: query
          type: integer
          required: true
          minimum: 1
          maximum: 9  
      responses:
        '200':
          description: Success authorization
      security:
        - appKey: []
          appId: []
securityDefinitions:
  appKey:
    type: apiKey
    in: header
    name: X-APP-KEY
  appId:
    type: apiKey
    in: header
    name: X-APP-ID</pre>

**Comment by hkosova** [comment]
Tthanks for the report, but this issue has been reported already: #3521.

**Comment by shockey** [comment]
Closing as a duplicate of #3521.
