### ISSUE TITLE
How to define the schema and the running port of the API?

### ISSUE THREAD

**Issue by embryologist** [swagger-api/swagger-ui#4549]
### Q&A (please complete the following information)
 - OS: [macOS]
 - Browser: [chrome, safari]
 - Method of installation: [dotnet CLI]
 - Swagger-UI version: [ASP.NET CORE 2.4.0]
 - Swagger/OpenAPI version: [Swagger 2.0, OpenAPI 3.0]

### Content & configuration

```
public void ConfigureServices (IServiceCollection services) {
services.AddSwaggerGen (c => { c.SwaggerDoc ("v1", new Info { Title = "ArtNgCore APIs", Version = "v1" }); });
}

```
```
 public void Configure ( IApplicationBuilder app) {
 app.UseSwagger ();
 app.UseSwaggerUI (c => {
                c.SwaggerEndpoint ("/swagger/v1/swagger.json", "ArtNgCore APIs V1");
            });
}

```

### How can we help?
How is it possible to configure the schema and the port of the API?
The default is HTTP, port 5000. 
My app runs SSL. Https and port 5001?

**Comment by shockey** [comment]
Hi @embryologist, it looks like you're using a Java annotation library.

Please open an issue with that library, as Swagger-UI is unrelated 😄 

PS: you'll need to find a way to define a `host` and `basePath` for your Swagger document.

**Comment by embryologist** [comment]
No this is C#, this is my configuration in start up

**Comment by shockey** [comment]
@embryologist I see, apologies for getting it wrong 😄 

You don't provide scheme and host information to Swagger-UI directly - you need to set the [`host` and `schemes`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields) values in your Swagger document, and then Swagger-UI will read those values.

**Comment by embryologist** [comment]
Thank you

**Comment by embryologist** [comment]
@shockey ,
this is the method for `SwaggerDoc`
` public void SwaggerDoc(string name, Info info);`
I can not define schemas in this method, what shall I use

**Comment by shockey** [comment]
@embryologist, it looks like you're using Swashbuckle... you should probably use [`RootUrl` and `Schemes`](https://github.com/domaindrivendev/Swashbuckle#additional-service-metadata).

PS: Swashbuckle is a different library (though they do use Swagger-UI), and I'm not a Java developer - their issue tracker is likely to be a better home for any questions about the Java side of things.
