### ISSUE TITLE
Question - Version of previous UI styling

### ISSUE THREAD

**Issue by sura2k** [swagger-api/swagger-ui#4550]
### Screenshots
![image](https://user-images.githubusercontent.com/1226939/39971842-aa1b9c78-5720-11e8-8c2f-c6e78785f7d3.png)

### How can we help?
What is the last swagger-ui version with above UI look? If it something between 2.3.x to 2.7.x, where can I download it?

**Comment by shockey** [comment]
Hi @sura2k!

Any 2.x version will have this styling: https://github.com/swagger-api/swagger-ui/releases?after=v3.0.0

**Comment by sura2k** [comment]
Thanks. 2.2.10 worked.
