### ISSUE TITLE
Hello,How to run swagger-ui

### ISSUE THREAD

**Issue by fwhezfwhez** [swagger-api/swagger-ui#4551]
windows 10 64 
I've entered its path,and npm install it succesfully
how can i start this server on my browser like swagger-editor
'npm start' doesn't work

**Comment by shockey** [comment]
@fwhezfwhez, there's currently no `npm start` command built into Swagger-UI - but this would be a great opportunity to copy what Swagger-Editor is doing and open a PR!

You can use any HTTP server utility to serve up the `dist` folder. For example...

```js
➜ npm i -g http-server

➜ http-server ./dist
Starting up http-server, serving ./dist
Available on:
  http://127.0.0.1:8080
```

**Comment by rishacha** [comment]
Hi @shockey , can I take this up?

**Comment by shockey** [comment]
@rishacha absolutely! feel free to open a PR and tag me in it.

**Comment by fwhezfwhez** [comment]
well,3q so mch
