### ISSUE TITLE
Input field doesn't show the default value

### ISSUE THREAD

**Issue by joekou** [swagger-api/swagger-ui#4557]
- OS: window7
 - Browser: chrome
 - Method of installation: dist assets
 - Swagger-UI version: 3.14.2
 - OpenAPI version: OpenAPI 3.0

### Content & configuration

OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: test
  version: test
paths:
  '/test':
    get:
      parameters:
        - $ref: '#/components/parameters/testParam'
      responses:
        '200':
          description: Successful response
components:
  parameters:
    testParam:
      name: testHaeder
      in: header
      schema:
        type: string
        default: 'test-value'
```

Swagger-UI configuration options:
```js
const ui = SwaggerUIBundle({
	urls: [{url: "openapi.yaml", name: "API"}],
	dom_id: '#swagger-ui',
	deepLinking: true,
	presets: [
	  SwaggerUIBundle.presets.apis,
	  SwaggerUIStandalonePreset
	],
	plugins: [
	  SwaggerUIBundle.plugins.DownloadUrl
	],
	layout: "StandaloneLayout",
	validatorUrl: null
  })
```

### The bug encountered
The default value as stated in the OpenApi definition above doesn't appear on the swagger-ui.

### To reproduce...
1. Open the swagger-ui page.
2. Click [Get] /test bar.
3. Click the "Try it out" button.
4. testHeader input field doesn't show the default value "test-value".

### Expected behavior
"test-value" would be set in the testHeader input field.

### Screenshots
![image](https://user-images.githubusercontent.com/12831767/40060365-fac2befe-5888-11e8-80a1-f4609229a6d5.png)

### Additional context or thoughts
Somehow the "test-value" value appeared if the property is placed direct under parameter object instead of schema object as below:

```yaml
openapi: 3.0.0
info:
  title: test
  version: test
paths:
  '/test':
    get:
      parameters:
        - $ref: '#/components/parameters/testParam'
      responses:
        '200':
          description: Successful response
components:
  parameters:
    testParam:
      name: testHaeder
      in: header
      default: 'test-value'
      schema:
        type: string
```

**Comment by shockey** [comment]
Fixed.

Thanks for the report, @joekou!
