### ISSUE TITLE
Markdown anchor element used in swagger.json is not rendering

### ISSUE THREAD

**Issue by srpalomino** [swagger-api/swagger-ui#4558]
### Output
![32555223_1893014854062961_9191635578611826688_n](https://user-images.githubusercontent.com/9772415/40076325-9d090d72-584c-11e8-84bb-72e27f156ce1.jpg)

### swagger.json
https://gist.github.com/srpalomino/6baa3764006b6174faa4184d82b89ed3#file-swagger-json-L4

### index.html
https://gist.github.com/srpalomino/145c1f3965e998b69a3ac413ce8598c1

**Comment by hkosova** [comment]
There's an extra space between `[]` and `()`:
```
[Google] (https://www.google.com/)
        ^
```
Change that to:
```
[Google](https://www.google.com/)
```
