### ISSUE TITLE
Getting error ` _specWrapActions2.default is not a function` after running updateJsonSpec()

### ISSUE THREAD

**Issue by srpalomino** [swagger-api/swagger-ui#4559]
### Goal 
Expand and scroll to a tag (without refreshing the page) after clicking an anchor element.

### Problem
The following error message shows up

`TypeError: _specWrapActions2.default is not a function`

And I found out the problem happens in [ori](https://gist.github.com/srpalomino/1fb8ce1a4bd9a7bca527f34a64fbbdb6#file-app-jsx-L18).

Follow the directions [here](https://gist.github.com/srpalomino/1656203404e9ed1c2317b6c33aeb8344) to run my code

**Comment by shockey** [comment]
Closing; @srpalomino you and I chatted about this last Thursday 😄
