### ISSUE TITLE
What HTML is created by the Markdown Component?

### ISSUE THREAD

**Issue by srpalomino** [swagger-api/swagger-ui#4562]
The markdown component generates some HTML [here](https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/providers/markdown.jsx#L18)

Does anyone know what are all possible values `html` can be?? For example, can `html` be a paragraph element containing text and other html elements?

**Comment by shockey** [comment]
@srpalomino, `html` is always an HTML string. The elements you get depend on the input 😄 

Here are some example outputs: https://runkit.com/shockey/5afc8936ef55be0012f58b37

**Comment by srpalomino** [comment]
@shockey
