### ISSUE TITLE
more xml tags for c#

### ISSUE THREAD

**Issue by chaudharisuresh997** [swagger-api/swagger-ui#4568]
Hi
swagger documentation https://swagger.io/docs/specification/describing-parameters/ reveals only what json tags you  have.

But I think what needs to be covered is which tags I can use in my c# code to auto generate swagger doc in swagger UI.
For example to generate summary we use <summary> in c# code.
Can you please list all the c# tags which I can type in c# code so that swagger UI will do rest of the stuff.

**Comment by shockey** [comment]
Hi @chaudharisuresh997, we don't maintain C# bindings for Swagger/OpenAPI, you'd have to inquire about this with whatever library you're using in C#.
