### ISSUE TITLE
invalid sample request for XML POST/PUT body

### ISSUE THREAD

**Issue by cedricbompart** [swagger-api/swagger-ui#4569]
- OS: linux
 - Browser: chrome
 - Version: 66.0.3359.170 
 - Swagger-UI version: 3.14.2
 - Swagger/OpenAPI version: Swagger 2.0 (io.swagger/swagger-jaxrs -> 1.5.19)

I've got a jaxrs service where I'm generating at runtime the swagger definition. I'm using the "getListingJsonResponse" method from the io.swagger.jaxrs.listing.BaseApiListingResource class to produce the JSON definition. Then the definition is used by the Swagger UI index page.

Everything is working as expected, apart of the sample requests for the POST/PUT body.  The sample XML doesn't used the correct case for the XML element. All our elements start with a capital letter.

Here is a snipset of the swagger definition:
```json
{
	"swagger": "2.0",
	"info": {
		"version": "1.0.0"
	},
	"basePath": "/Basket",
	"tags": [
		{
			"name": "basket"
		}
	],
	"schemes": [
		"http"
	],
	"paths": {
		"/MO/Open/Orders/AggregatedBaskets/v1": {
			"post": {
				"tags": [
					"basket"
				],
				"summary": "Create a basket",
				"operationId": "create_1",
				"consumes": [
					"application/xml"
				],
				"produces": [
					"application/xml"
				],
				"parameters": [
					{
						"in": "body",
						"name": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/CreateBasketRequest"
						}
					}
				],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"$ref": "#/definitions/CreateBasketResponse"
						}
					}
				},
				"x-samples": []
			}
		}
	},
	"definitions": {
		"BasketItem": {
			"type": "object",
			"required": [
				"articleID"
			],
			"properties": {
				"articleID": {
					"type": "string",
					"xml": {
						"name": "ArticleID"
					}
				},
				"quantity": {
					"type": "integer",
					"format": "int32",
					"xml": {
						"name": "Quantity"
					}
				}
			}
		},
		"CreateBasketResponse": {
			"type": "object",
			"properties": {
				"serviceErrors": {
					"xml": {
						"name": "ServiceErrors"
					},
					"$ref": "#/definitions/ServiceErrors"
				},
				"basket": {
					"xml": {
						"name": "Basket"
					},
					"$ref": "#/definitions/Basket"
				}
			},
			"xml": {
				"name": "CreateBasketResponse",
				"namespace": "urn:bla.bla.createbasketresponse.v1"
			}
		},
		"CreateBasketRequest": {
			"type": "object",
			"required": [
				"basketItem"
			],
			"properties": {
				"basketItem": {
					"xml": {
						"name": "BasketItem"
					},
					"$ref": "#/definitions/BasketItem"
				}
			},
			"xml": {
				"name": "CreateBasketRequest",
				"namespace": "urn:bla.bla.createbasketrequest.v1"
			}
		}
	}
}
```

Swagger UI uses this as a sample request for the POST body:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CreateBasketRequest xmlns="urn:bla.bla.createbasketrequest.v1">
	<basketItem>
		<ArticleID>string</ArticleID>
		<Quantity>0</Quantity>
	</basketItem>
</CreateBasketRequest>
```

The basket item element should be called "BasketItem" based on the above JSON definition. It looks like the JSON property is used instead of the XML name. For the inner element of an object; the naming are correct (article and quantity).

**Comment by shockey** [comment]
> there is a "ref" attribute to another object definition

@cedricbompart, can you illustrate this? i'm not quite following 😄

**Comment by cedricbompart** [comment]
```json
"CreateBasketRequest": {
	"type": "object",
	"required": [
		"basketItem"
	],
	"properties": {
		"basketItem": {
			"xml": {
				"name": "BasketItem"
			},
			"$ref": "#/definitions/BasketItem"
		}
	},
	"xml": {
		"name": "CreateBasketRequest",
		"namespace": "urn:bla.bla.createbasketrequest.v1"
	}
}
```

...the XML/name for the _basketItem_ object is ignored because there is a $ref which references an external definition.
It's all fixed now; I've "massaged" the JSON output from the swagger implementation and moved the XML declaration to the _BasketItem_ definition.  Ideally the **io.swagger.jaxrs.listing.BaseApiListingResource/ getListingJsonResponse** should return a valid Swagger object!

**Comment by shockey** [comment]
@cedricbompart aha! 

Yes, moving it is the answer here. Other values are not allowed alongside `$ref` values (if you paste this in the Editor you'll see that warning).

Glad you got this fixed 😄
