### ISSUE TITLE
Google recaptcha with swagger

### ISSUE THREAD

**Issue by 1nfinite** [swagger-api/swagger-ui#4575]
I am having no idea of how could i implement google recaptcha into swagger itself so that it is verified by the backend rest api. I try to search in documentation but nothing found.

My question is this possible to be implemented and how?

**Comment by shockey** [comment]
@1nfinite, are you asking how to describe your RECAPTCHA flow in a Swagger document, or how to display it in Swagger-UI?

**Comment by 1nfinite** [comment]
@shockey it is best if i could describe RECAPTCHA flow in swagger document but as far as i concerned, I can't find it in swagger doc. I am referring to open api 2.0

I would expect something like this as an optimum solution.

`Captcha:
    Provider: google
    Site_Key: string
    Secret_Key: string`

and it will be display on swagger ui.

**Comment by shockey** [comment]
@1nfinite, I don't know of any public documentation of Recaptcha in Swagger - if that doesn't exist, you'll have to create operations that define the behavior you're expecting 😄

**Comment by webron** [comment]
@1nfinite captcha for APIs does not make a lot (or any) sense as it defeats the purpose of having code operate APIs (unless you want to use a service that 'cracks' captchas). If you _really_ want to define it, you can use extensions in the spec for it, and as for displaying it, you can create your own plugin that would render it. Searching the repo for plugin examples should yield enough for you to get started with.
