### ISSUE TITLE
Default Value of the parameter do not change when moving from one version to another.

### ISSUE THREAD

**Issue by desaifly** [swagger-api/swagger-ui#4577]
- OS: [Windows]
 - Browser: [chrome]
 - SwaggerAspNetCore version: 2.4
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

 I have used following sample: 
https://github.com/Microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerSample

### Describe the bug you're encountering
When moving from one version to another the default value remains the same in the input box.

### To reproduce...

1. Go To 'Orders' and expand
2. Click on 'Try it out'
3. api-version parameter is  '0.9' - It's correct
4. Select a spec 'V1'
5. go to Orders  (The api-version parameter Default Value shown 1.0, which is correct)
5. Click on 'Try it out'
6. api-version parameter is '0.9' which is incorrect.

### Expected behavior
api-version parameter need to be '1.0'

**Comment by shockey** [comment]
Hi @desaifly, I don't see a Swagger/OpenAPI document in the repository you linked to that I can use to reproduce this. Can you provide one?

Also, screenshots would be helpful here 😄
