### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#4579]
These changes essentially automate the release process earlier: we will be responsible for testing the candidate code manually and then triggering a release, but version bumping, packaging, GitHub release creation + notes, and deployment triggering will happen automatically.

---

### Eliminate version-controlled `dist` folder in favor of publishing a zip file of assets attached to GitHub releases

Benefit: our Git repo won't grow as large over time, and we won't have binaries in our repository, which is a best practice.

Q: Is anyone using us as a submodule? Are we okay with dropping support for that? Recall that submodules track a specific commit, so we're not likely to break anyone's automated implementations.

### Move active development to a `develop` branch, and use `master` for releaseable code

Benefit: what is released (`master`) and what is mainline development (`develop`) is clear in the repository, as opposed to our current practice of "periodic releases cut from `master`".

This follows the widely-adopted Git Flow repository model, which we already loosely follow.

### Automatically compute, commit, and tag new version numbers

Benefit: there's no chance of human error in version numbering, whether that's a typo in one location (git tag, package.json, etc) or a mistaken verison number (bumping patch instead of minor, etc).

Next-version numbers would be derived from Conventional Commit messages via `semantic-release`, and automatically applied everywhere they're needed. Releases would be triggered by committing to `master`.

Danger: muscle memory for `master` could get us into trouble, perhaps using master as mainline development and a differently named branch (`release`?) for new versions would be wise.

Note: we'd need to automate README version table updates as well, for Swagger-UI.

### Generate release notes from Conventional Commit messages

Benefit: the repetitive part of release note authoring is taken care of, leaving us with more bandwidth to add the human parts.

**Comment by shockey** [comment]
More context: a lot of this flow revolves around [Semantic Release](https://legacy.gitbook.com/book/semantic-release/semantic-release/details) 😄

**Comment by heldersepu** [comment]
> Is anyone using us as a submodule?
Yes I do on [Swagger-Net](https://github.com/heldersepu/Swagger-Net) and I know [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) has it too

**Comment by shockey** [comment]
Closing. We did it!
