### ISSUE TITLE
Slash in ref key

### ISSUE THREAD

**Issue by seb2411** [swagger-api/swagger-ui#4591]
### Q&A (please complete the following information)
 - OS: Ubuntu
 - Browser: Chrome/Firefox
 - Version: latest
 - Method of installation: API-Platform
 - Swagger-UI version: 3.15.0
 - Swagger/OpenAPI version: Swagger 2.0

### To reproduce...

Pass a ref with a slash for example : 
```json 
"schema":{
  "type":"array",
  "items":{
    "$ref":"#/definitions/MyModule/my-super-module-resource"
  }
}
```
### Expected behavior
Model/Example showing the related model/example

### Additional context or thoughts
I'm using Swagger UI through API-Platform. I have an issue open here: https://github.com/api-platform/core/issues/1969

**Comment by hkosova** [comment]
`/` in node names needs to be escaped as `~1`:
```
"$ref":"#/definitions/MyModule~1my-super-module-resource"
```

Similarly, `~` is escaped as `~0`:
```
a~b   ->  #/definitions/a~0b
```
Source: [JSON Pointer Specification](https://tools.ietf.org/html/rfc6901#section-3)

<br/>

By the way, if you are going to migrate to OpenAPI 3.0, keep in mind that it only allows the characters `a-z A-Z 0-9 . - _` in [component names](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#components-object). So `MyModule/my-super-module-resource` won't be a valid model name in OpenAPI 3.0.

**Comment by seb2411** [comment]
Thank you @hkosova.

If I'm use the ~1 for the pointer the UI is not converting back the ~1 to /.

So About the Open API 3.0 If I have different modules what do you think is the best way to represent that to have a nice and readable separation ?

**Comment by seb2411** [comment]
Here: 
https://web.tresorit.com/l#k-EZgWVI2IapUodj2-7x4A

But so I will probably stop using `/`

**Comment by hkosova** [comment]
Thanks. That display issue is already being tracked in #4161.

> But so I will probably stop using `/`

That's a good idea. It's best to use the names that are valid identifiers in common programming languages. This will also be forward-compatible with OAS 3.0. :smiley:

**Comment by seb2411** [comment]
Thank you. So I think we can close this.

**Comment by webron** [comment]
Thanks!
