### ISSUE TITLE
how to read special character in rest web services through postman using @formparam annotation

### ISSUE THREAD

**Issue by sachin358** [swagger-api/swagger-ui#4603]
1
down vote
favorite
I have a rest web service whose url is

http://localhost/rest/authenticate?username=username&password=pa+ssw1&rd%

In password parameter have 3 special character.

1) + character read as white space 2) & character remove the all character. for example - my password like this "passw&rd" and it will read like this "passw" 3) % character does not read the proper password, its read the null value.

my API like this ...

@Path("/authenticate") public class AuthenticateService {

private ILiteWebServiceFacade liteWebServiceFacade = ServiceLocator.locateService(ILiteWebServiceFacade.class);

@POST
@Produces(MediaType.APPLICATION_JSON)
public Response authenticate(@FormParam("username") String username, 
                             @FormParam("password") String password)
    throws RestException {

    AuthenticateResponse res = new AuthenticateResponse();
    try {
        res = liteWebServiceFacade.mobAuthenticate(username, password);
    } catch (RestApplicationException e) {
        res.setError(e.getErrorMessage().getErrorCode(), e.getErrorMessage().getErrorMessageKey());
    }
    return Response.ok(res).build();
}
}

Can you please suggest me how to read all these special character?

**Comment by shockey** [comment]
Hi @sachin358, `&` is not allowed in query parameter values, you'd need to percent-encode that value when you build your request.

Also - this isn't a Swagger-UI question, please inquire about your annotation question with the library that you're using for annotations 😄
