### ISSUE TITLE
Api key is not adding into query parameter while sending POST request with multipart/form-data attributes

### ISSUE THREAD

**Issue by teenasharma** [swagger-api/swagger-ui#4605]
### Api key is not adding to query parameter while sending POST request with multipart/form-data attributes getting the following error
![swagger-error](https://user-images.githubusercontent.com/10626137/40677032-1aae5f54-639a-11e8-874b-478ba7d0e91f.png)

 - Swagger-UI version: v2.1.1-M2
 - Swagger-akka-http version : 0.11.0
"com.github.swagger-akka-http" % "swagger-akka-http_2.11" % "0.11.0"

### How can we help?
I have implemented swagger with akka http, API key is adding in query parameter from swagger ui explore button for all the requests except the POST request with multipart/form-data attributes.

Is that a bug or is there any resolution available for it?

**Comment by shockey** [comment]
Hi @teenasharma, this shouldn’t be an issue in the latest version of Swagger UI. Upgrading should resolve this 😄

**Comment by teenasharma** [comment]
Thanks @shockey

**Comment by shockey** [comment]
@teenasharma, that's not an error, that's a response coming back from your server 😄 

If you can provide a Swagger definition and a server to test against, I can take a look to make sure that Swagger-UI is sending everything correctly.
