### ISSUE TITLE
Redirect api requests with key parameter in url query to another url 

### ISSUE THREAD

**Issue by pruthvigh** [swagger-api/swagger-ui#4609]
I want to redirect api requests made to a url with a key in the query parameter to be redirected to another url. How can I do that?
For example www.xyz.com/api/user?api_key=xxxxxxxxxxx redirected to www.abc.com/api/user/**?api_key=xxxxxxxx

**Comment by shockey** [comment]
@pruthvigh, this is something you'd implement in your server, not in a Swagger document. Sending a 302 Found response and a `Location` header should direct your user to the appropriate URL.
