### ISSUE TITLE
add cookie support

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#461]
Now that swagger-js supports cookies (https://github.com/wordnik/swagger-js/commit/07a528985260363f3726a562fbb0f90b6975370f) the swagger-ui should support it as well.

**Comment by mohsen1** [comment]
https://github.com/swagger-api/swagger-ui/pull/1010 will fix this

**Comment by webron** [comment]
Closing this now as not supported by the spec. We should revisit when it is.

https://github.com/swagger-api/swagger-spec/issues/161

**Comment by cbornet** [comment]
FYI, with swagger-ui 2.1.4, you can now use ```enableCookies: true``` in window.swaggerUI to set the withCredentials flag

**Comment by jirkadanek** [comment]
See also https://github.com/OAI/OpenAPI-Specification/issues/15

**Comment by laur89** [comment]
[OAI/OpenAPI-Specification#161](https://github.com/OAI/OpenAPI-Specification/issues/161) - cookie support was apparently added; should this ticket be reopened?

**Comment by webron** [comment]
No. Cookie parameter support will be added as part of the 3.0 support.
