### ISSUE TITLE
Problem with required boolean as operation parameter

### ISSUE THREAD

**Issue by jamesfernando94** [swagger-api/swagger-ui#4612]
#### Issue Info
Swagger UI Version : 3.13.4 (Also Updated and tested on 3.16.0)
This may be related to https://github.com/swagger-api/swagger-ui/issues/3407

#### Problem
When trying execute an operation the pre entered values for the required field is true, however when you try to execute it the swagger UI says that the field is required even though there is a value in it. Also, after this if you open the drop-down and select true it still shows that the field is required.

![Image showing that even though there is a value in the boolean field it is still saying that the field is required](https://user-images.githubusercontent.com/11622177/40843190-1d53be60-65a8-11e8-9c47-1062decf6f46.png)

#### Steps to reproduce

1. Open the operation
2. Click try me out
3. Leave the values as their original values then click execute
5. The required field now turns red
6. Select true in the required field then click execute
8. The required field is still red
9. select false in the required field
10. select true in the required field then click execute
12. This now works

Thanks for any help in advance
James

**Comment by shockey** [comment]
thanks for the report, @jamesfernando94!

**Comment by jamesfernando94** [comment]
Thanks for the Quick Response and fix
