### ISSUE TITLE
How to resolve the Cross Domain with swagger-ui?The problem is still not fix

### ISSUE THREAD

**Issue by dzhyw** [swagger-api/swagger-ui#4617]
How to resolve the Cross Domain with swagger-ui?

use try it now  button！

i use Node.js CORS middleware  npm install cors. and express

but still can't cross domain

**Comment by shockey** [comment]
Hi @dzhyw!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
