### ISSUE TITLE
add support for date-time property

### ISSUE THREAD

**Issue by madisparn** [swagger-api/swagger-ui#462]
api json:
"properties":{"DateTimeField":{"type":"string","format":"date-time"}

at the moment date is simply dispayed as string type in the ui.
is it possible to display it as date-time and create example response with correct value?

**Comment by mirelon** [comment]
Why is this closed? What version fixed this?

**Comment by twocabbages** [comment]
+1.

**Comment by spati-java** [comment]
Do we have solution for this issue, for one my date field I want  only the date in yyyy-mm-dd format (date property), but swagger is  giving me date-time property which includes the time zone  . Any help for this ? I tried to use override schema but it seems from 1.3 version of swagger-core they have removed override schema class , ModelConvertor class does not have addConvertor method either , what is the alternative class to achieve this ?
