### ISSUE TITLE
Content-Type value is not correct

### ISSUE THREAD

**Issue by heyixiaoran** [swagger-api/swagger-ui#4621]
Hi . I get a wrong Content-Type value. 
Actually . I use Swashbuckle.AspNetCore .  
When I post a request . Curl is like "curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' ...."  in Swashbuckle.AspNetCore 2.4 & 2.5

But If I use Swashbuckle.AspNetCore 1.1.0 .  Curl is like “curl -X POST --header 'Content-Type: undefind' ....”
I heard this value is set in swagger-ui . So I want to need some help. Thanks.

Maybe the keyword '[FromForm]' cause this. It's an  old code .  I can't modify this api.
`  

        [HttpPost("Login")]   
        public async Task<IActionResult> Login([FromForm] LoginUser user)    
        {  
                .....  
        }
`

**Comment by shockey** [comment]
Hi @heyixiaoran,

sounds like Swashbuckle is probably not setting the Content-Type in your Swagger definition correctly - if you can provide your definition (not your Swashbuckle annotations) I can take a look.
