### ISSUE TITLE
How should I set --cert and --key option of linux curl in the yaml file 

### ISSUE THREAD

**Issue by TodLiuMeng** [swagger-api/swagger-ui#4623]
For SSL mutual authentication, we set file path in 'curl' options and args.
e.g. curl  xxx.xxx.xxx.xxx --cert ./client.crt --key ./client.key -H .......

So, how should  I deal with my yaml in swagger UI. 
Any Example ,thx

**Comment by shockey** [comment]
Hi @TodLiuMeng, this isn't currently possible - you can follow https://github.com/swagger-api/swagger-ui/issues/4143 for news on a plugin system interface that would allow this.

Cheers!
