### ISSUE TITLE
Security requirement in openapi config breaks the UI

### ISSUE THREAD

**Issue by Thisen** [swagger-api/swagger-ui#4627]
### Q&A (please complete the following information)
 - OS: Windows 8.1 Enterprise
 - Browser: Chrome
 - Version: 66
 - Method of installation: dist assets
 - Swagger-UI version: 3.17.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
**NOTE:** This is obfuscated since I work on software where you need a security clearance.

Example Swagger/OpenAPI definition:
```json
{
  "resourcePackages": [
    "io.swagger.sample.resource",
    "com.company.foo.bar"
  ],
  "prettyPrint": true,
  "openAPI": {
    "info": {
      "version": "1.0",
      "title": "Foo bar",
      "description": "Foo bar"
    },
    "servers": [
      {
        "url": "/foo/bar/",
        "description": "Foobar endpoint"
      }
    ],
    "components": {
      "securitySchemes": {
        "apiKeyAuth": {
          "type": "apiKey",
          "in": "query",
          "name": "authToken"
        }
      }
    },
    "security": {
      "apiKeyAuth": []
    }
  }
}
```

Swagger-UI configuration options:
```js
window.onload = function() {
        var fooUrl = window.location.protocol + '//' + window.location.host + '/foo/bar';

        // Build a system
        const ui = SwaggerUIBundle({
          urls: [
            { url: fooUrl , name: 'Foobar' }
          ],
          dom_id: '#swagger-ui',
          deepLinking: true,
          presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIStandalonePreset
          ],
          plugins: [
            SwaggerUIBundle.plugins.DownloadUrl
          ],
          layout: "StandaloneLayout"
        });

        window.ui = ui
      }
```
### Describe the bug you're encountering

When I supply `"security"` object in openapi-configuration.json, Swagger-UI shows "No operations defined in spec!", but in the console I see the output of screenshot 1.

```json
"security": {
      "apiKeyAuth": []
}
```
If I remove that and add: 
```java
@SecurityRequirement(name = "apiKeyAuth")
```
to my API methods, it works perfectly fine with authorization.

### To reproduce...

1. Add the security scheme to the openapi-configuration.json:
```json
"security": {
      "apiKeyAuth": []
}
```
2. Open the documentation and see the console.

### Expected behavior

The "global" security requirement should work for all endpoints for the defined endpoint.

### Screenshots
Screenshot 1:
![image](https://user-images.githubusercontent.com/10807938/41097015-d6d13a7c-6a56-11e8-9633-e5f0fa0090fa.png)

**Comment by shockey** [comment]
Hi @Thisen! Thanks for filing an issue.

`security` should be an array of Security Requirement objects [when used at the root level of an OpenAPI definition](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields).

Swagger-Editor marks this as an error:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/680248/41127351-705c647a-6a5f-11e8-9ab1-a055a43ea08a.png">

Changing your global security value should solve your issue:

```yaml
  security:
  - apiKeyAuth: []
```

**Comment by Thisen** [comment]
Ahh, I missed that.
I should use it the following way, of course:
```
"security": [
      "apiKeyAuth": []
]
```

Thanks!
