### ISSUE TITLE
schemaValidationMessages":[{"level":"error","message":"Can't read from file /swagger.json"}]

### ISSUE THREAD

**Issue by kumarz** [swagger-api/swagger-ui#4631]
### Q&A (please complete the following information)
 - OS: Liunx
 - Browser: All the browsers
 - Version: latest
 - Method of installation:  dist assets
 - Swagger-UI version: 3.17.0
 - Swagger/OpenAPI version:  swagger-jersey2-jaxrs_2.10-1.3.13.jar

### Content & configuration
 so I have used swagger-jersey2-jaxrs_2.10-1.3.13.jar to generate the swagger.json file.

Swagger/OpenAPI definition:

```swagger.json
-{
  "swagger": "2.0",
  "info": {
    "description": "This service talks to the oracle db of XXXXXXXXX schema. The XXXXXXXXX schema has all the information related to user like roles, accounts etc for XXXXXXXXX.com.All the user related actions are managed in XXXXXXXXX user service.",
    "version": "1.0.0",
    "title": "XXXXXXXXX User Service",
    "contact": {
      "url": "www.XXXXXXXXX.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "basePath": "/XXXXXXXXX-user/service",
  "tags": [
    {
      "name": "Accounts"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/users/accounts/account": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get Account Info",
        "description": "Get the Account information",
        "operationId": "getAccount",
        "consumes": [
          "application/json; charset=utf-8"
        ],
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "accountNum",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "zipCode",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": "successful operation"
          }
        }
      }
    }
  },
  "definitions": {
    "Verification": {
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string"
        },
        "accountNumber": {
          "type": "string"
        }
      }
    }
  }
}

```

Swagger-UI configuration options:
```js
  const ui = SwaggerUIBundle({
    url: window.location.href.replace('swagger-ui.html','service/swagger.json'),
    dom_id: '#swagger-ui',
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })
```

### How can we help?
https://online.swagger.io/validator?url=http://XXXXXXXX.com:9084/XXXXXXX-user/service/swagger.json
calls are getting failed hence I am getting 

{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://XXXXXX.com:9084/XXXXXXX-user/service/swagger.json"}]}

while hitting 

{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://XXXXXX.com:9084/XXXXXXX-user/service/swagger.json"}]}

Please advise to get rid of issue in swagger-ui

**Comment by shockey** [comment]
Hi @kumarz, this is because the online Validator service can't reach your server to fetch your definition.

You can set the `validatorUrl` option to `null` in order to disable the badge:

```js
  const ui = SwaggerUIBundle({
    url: window.location.href.replace('swagger-ui.html','service/swagger.json'),
    dom_id: '#swagger-ui',
    validatorUrl: null,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })
```

**Comment by kumarz** [comment]
@shockey,
Thanks for getting back to me. I really appreciate it. so validatorUrl: null is going to disable the settings to make the server call.

However I would like to disable this in java config way. I have the following settings to initialize the swagger bean. Is there any way to do the validatorUrl: null via java config ?


    @Override
    public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
        configurer.enable();
    }

	@Override
	public void addResourceHandlers(final ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/resources/**").addResourceLocations("/resources/");
		registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
		registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");
	}

**Comment by kumarz** [comment]
@shockey ,
Thank you, After updating the configuration, the validator service error messages are gone from the UI.
