### ISSUE TITLE
Swagger-ui not parsing 'urls' config property

### ISSUE THREAD

**Issue by manojadd** [swagger-api/swagger-ui#4632]
I am using https://www.npmjs.com/package/swagger-ui 3.17 version. I am using the config object with urls parameter but still, it doesn't seem to parse it.

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
