### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gaurav517** [swagger-api/swagger-ui#4637]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 66.0.3359.181
 - Swagger-UI version: 3.13.6
 - Swagger/OpenAPI version: Swagger 2.0

In case of big nested request/response json spec, I get following in console after trying to expand the operation in swagger-ui and the section of operation shows endless spinner. After refreshing we see the operation details.

```
system.js:461 RangeError: Maximum call stack size exceeded
    at immutable.js:2405
    at Le.pe.withMutations (immutable.js:1353)
    at He (immutable.js:2405)
    at Le.set (immutable.js:2096)
    at nt (immutable.js:2780)
    at Ze.set (immutable.js:2686)
    at immutable.js:2651
    at immutable.js:3016
    at immutable.js:2699
    at Le.__iterate (immutable.js:2206)
```

**Comment by shockey** [comment]
Yep, this sounds like #4411 to me - closing as a duplicate, but this report will be considered when it's looked at.

As @heldersepu mentioned, crossposting your Swagger/OpenAPI document into that issue would help make sure things get fixed for you 😄
