### ISSUE TITLE
No operations defined in spec

### ISSUE THREAD

**Issue by 164851225** [swagger-api/swagger-ui#4639]
I'm using swagger 2.8.0
here are my configs 
![image](https://user-images.githubusercontent.com/19471559/41218157-bb61b0bc-6d8c-11e8-9dc0-526e1a0245bd.png)
Logs:
![image](https://user-images.githubusercontent.com/19471559/41218303-3b59a14e-6d8d-11e8-81df-5674e682c6b3.png)
Problem:
![image](https://user-images.githubusercontent.com/19471559/41218245-079202fc-6d8d-11e8-9de8-da192fabaae8.png)

can you solve the problem or give me some suggestions?

**Comment by shockey** [comment]
Hi @164851225,

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
