### ISSUE TITLE
customize or remove swagger ui header top bar

### ISSUE THREAD

**Issue by rsachin** [swagger-api/swagger-ui#4644]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: chrome, firefox
 - Version: 68.x
 - Method of installation: spring boot dependency
 - Swagger-UI version: 2.7.0
 - Swagger/OpenAPI version: 2.7.0

Please advise how can we customize or remove swagger ui header (little green) top bar. I am looking for API that I can use in the SwaggerConfiguration.java in the Spring based project.

Regards,
SR

**Comment by shockey** [comment]
Hey @rsachin!

Unfortunately, we no longer support the 2.x version of the UI.

For info on how to customize the topper in v3.0, see https://github.com/swagger-api/swagger-ui/issues/4315.
