### ISSUE TITLE
Adding json example in multipart/form-data outputs excess json from immutableJS

### ISSUE THREAD

**Issue by dosentmatter** [swagger-api/swagger-ui#4646]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 66.0.3359.181
 - Method of installation: homebrew
 - Swagger-UI version: https://editor.swagger.io/ and
    swagger-editor-dist@^3.3.1 using swagger-ui@^3.12.0
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: '3.0.1'
info:
  title: 'Title'
  version: 1.0.0
paths:
  /path:
    post:
      responses:
        '201':
          description: 'description'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                json:
                  type: object
                  example:
                    a: string
                  properties:
                    a:
                      type: string
```

Swagger-UI configuration options:

I don't know the configuration. This bug happens on https://editor.swagger.io/ and also on [swagger-ui-watcher](https://github.com/moon0326/swagger-ui-watcher).

### To reproduce...

1. Go to https://editor.swagger.io/
2. Paste in the Swagger/OpenAPI definition yaml above.
3. Look a the rendered swagger-ui on the right.
4. The JSON has a bug. It has excess output that looks like it's coming from ImmutableJS.

### Expected behavior
The JSON should just be:
```
{
  "a": "string"
}
```

### Screenshots

This is a screenshot of the JSON with the excess output.
![image](https://user-images.githubusercontent.com/5732253/41392447-5c5a11de-6f55-11e8-804c-dc6b70562ec3.png)

**Comment by shockey** [comment]
thanks for the report, @dosentmatter!

**Comment by dosentmatter** [comment]
Thanks for the fixing it so quickly @shockey!
