### ISSUE TITLE
How has the deepLinking feature's implementation changed?

### ISSUE THREAD

**Issue by srpalomino** [swagger-api/swagger-ui#4647]
@ponelat @shockey 

Would you mind providing an overview of the deepLinking pluggin's implementation after being [refactored](https://github.com/swagger-api/swagger-ui/commit/90157c1a408e9a797ab1669fec9148cb2101b920)?

**Comment by ponelat** [comment]
Hi @srpalomino 
It more or less works the same, the implementation was changed to make a it fit the system a little better.
- parsing of the url is an action, and can be wrapped
- scrolling, now searches for the best candidate to scroll ( usually `body` but anything with a scroll bar works )
- scrolling will only be fired, _when_ the operation / model has been mounted, and will provide a `ref`

Hope that helps :)

**Comment by srpalomino** [comment]
@ponelat Thanks! That cleared things up :+1:
