### ISSUE TITLE
CURL using -d should be surrounded by single quotes

### ISSUE THREAD

**Issue by dneufeldcu** [swagger-api/swagger-ui#4651]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: SwaggerHub (latest?)
 - Method of installation: https://app.swaggerhub.com/
 - Swagger-UI version: SwaggerHub
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
When trying out my API I use the execute command and copy the generated CURL command to my prompt and submit it the CURL command my API returns an error because the -d datablock is not quoted correctly.  SwaggerUI should generate a CURL command where the json payload associated with the -d flag is surrounded by single quotes.

### Describe the bug you're encountering
Properly formatted JSON is properly quoted using single quotes in -d portion of the CURL command generated from the swagger-ui. e.g. the swagger-ui generates:

-d { "myKey": "myValue" }

but should generate:

-d '{ "myKey": "myValue" }'

### To reproduce...

1. Go to [link](https://app.swaggerhub.com/apis/cedardevs/one-stop_search_api_v.2.0.1/2.0.1#/collection/post_search_collection)
2. Click on POST Search Collection
3. Click 'Try it out'
4. Copy the generated CURL command to the console and submit.  The API will throw an error.  
5. Now submit the same CURL command but single quote the json in the -d section.  The API returns the expected result.

### Additional context or thoughts
Reference external example of JSON block surrounded by single quotes when using -d:
[Ref.](https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/Developers/GettingStarted/API%20requests/curl-requests.htm#Sending3)

**Comment by bestmike007** [comment]
It would also go wrong if request body includes special characters like '$', e.g. 

```bash
$ curl -X POST "https://petstore.swagger.io/v2/pet" \
    -H "accept: application/xml" -H "Content-Type: application/json" \
    -d "{ \"id\": 0, \"category\": { \"id\": 0, \"name\": \"$PATH\" }, \"name\": \"doggie\", \"photoUrls\": [ \"string\" ], \"tags\": [ { \"id\": 0, \"name\": \"$PATH\" } ], \"status\": \"available\"}"
```

I think this needs a fix. I'll submit a PR.

Reference: http://wiki.bash-hackers.org/syntax/quoting

**Comment by ctala** [comment]
Same here with hosted instance. But was working properly before.

**Comment by restfulhead** [comment]
Hi @tim-lai,

I can also see this working on editor.swagger.io. However, we're using `3.25.3` in our web app and still see the quotes missing. Is there anything I have to configure?

Our configuration looks like this:
```
SwaggerUI({
        url: this.specUrl,
        domNode: this.el.nativeElement.querySelector('#swagger-ui'),
        deepLinking: false,
        showMutatedRequest: false,
        displayOperationId: true,
        operationsSorter: 'alpha',
        presets: [SwaggerUI.presets.apis],
        plugins: [this.hideInfoUrlPartsPlugin]
      })
```
