### ISSUE TITLE
Query parameter not included in the URL when validating specification

### ISSUE THREAD

**Issue by pavlos163** [swagger-api/swagger-ui#4658]
### Q&A (please complete the following information)
 - OS: macOS High Sierra 10.13.3
 - Browser: Google Chrome 66.0.3359.181 (Official Build) (64-bit)
 - Method of installation: [Confluence Plugin](https://marketplace.atlassian.com/apps/1215176/open-api-documentation-for-confluence?hosting=server&tab=overview)
 - Swagger-UI version: 3.17.1
 - Swagger/OpenAPI version: Swagger 2.0 (built with [Swagger-Maven-Plugin](https://github.com/kongchen/swagger-maven-plugin).

### Bug description
![screen shot 2018-06-18 at 12 07 21](https://user-images.githubusercontent.com/9980011/41532752-2787b206-72f0-11e8-9c7a-88b5fb60f070.png)

I am seeing this picture. When I click on it, I go to the following URL:
`https://online.swagger.io/validator/debug?url=https://<host-and-path>/raw?private_token=<PRIVATE_TOKEN>&ref=master`

And I see this message:
```
{
  "schemaValidationMessages": [
    {
      "level": "error",
      "message": "Can't read from file https://<host-and-path>/raw?private_token=<PRIVATE_TOKEN>"
    }
  ]
}
```

However, as noted before (and as seen in the URL that clicking the picture directed me to) the URL to my swagger spec is:
`https://<host-and-path>/raw?private_token=<PRIVATE_TOKEN>&ref=master`

Note the `&ref=master` at the end, which is not included in the `schemaValidationMessages.message`.

Indeed, without that `ref` query parameter, the URL is not correct, so it's expected that the validator cannot read the file. However, the URL used should take into account all query parameters in the URL.

**Comment by bestmike007** [comment]
https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/online-validator-badge.jsx#L57-L59
