### ISSUE TITLE
Swagger UI - BigDecimal rendered in scientific notation.

### ISSUE THREAD

**Issue by ChandrasekharRajoli** [swagger-api/swagger-ui#4659]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 22
 - Method of installation: SpringFox 2.8.0
 - Swagger-UI version: 3.10
 - Swagger/OpenAPI version: Swagger 2.0

Swagger UI - Rendering BigDecimal in scientific notation. I want to render it as it is in Swagger UI. Please help how to enable this feature.

Please find the below BigDecimal value in Swagger UI and PostMan.
Swagger UI
{
"amount": 1.2345678912345679e+27,
}

PostMan Raw Body
{
"bigDecimal": 1234567891234567891234567891.1234
}

**Comment by shockey** [comment]
Hi @ChandrasekharRajoli, this has been reported before, see https://github.com/swagger-api/swagger-ui/issues/2030 for more discussion on this.

Closing as a duplicate 😄 thanks for filing an issue!
