### ISSUE TITLE
Custom endpoint without the final slash has a bad redirect

### ISSUE THREAD

**Issue by AnthonyMastrean** [swagger-api/swagger-ui#4662]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 67
 - Method of installation: [NuGet](https://www.nuget.org/packages/Swashbuckle.AspNetCore/)
 - Swagger-UI version: 3.12.2
 - Swagger/OpenAPI version: 2.0

### Content & configuration

I'm using a custom [route template](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#change-the-path-for-swagger-json-endpoints) and [route prefix](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#change-relative-path-to-the-ui) per the documentation.

```csharp
app.UseSwagger(options =>
{
    options.RouteTemplate = "nvdm-vrf/api-docs/{documentName}/swagger.json";
});

app.UseSwaggerUI(options =>
{
    options.RoutePrefix = "nvdm-vrf/api-docs";
    options.SwaggerEndpoint("/nvdm-vrf/api-docs/v1/swagger.json", "NVDM VRF API v1");
});
```

### Describe the bug you're encountering

When I navigate to a custom Swagger endpoint, without a final forward-slash (`/`), I am redirected to an incorrect endpoint. Part of the custom route prefix is duplicated.

For example:

```
http://localhost/nvdm-vrf/api-docs
```

Redirects to:

```
http://localhost/nvdm-vrf/nvdm-vrf/api-docs/
```

### To reproduce...

1. Create an ASP.NET Core web api or web application project
2. Install Swashbuckle.AspNetCore via the normal NuGet.org instructions
3. Configure a custom route prefix (changing the options per the linked documentation)
4. Navigate to the Swagger UI endpoint _without_ the final slash (so you hit the built-in redirect)

### Expected behavior

The normal built-in redirect to the endpoint including the final slash should occur.

### Screenshots

![swagger-redirect](https://user-images.githubusercontent.com/217842/41601960-b62cabee-73a7-11e8-9acd-3a982aebab49.gif)

### Additional context or thoughts

I checked and the redirect works as expected with the default endpoint.

```csharp
app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});
```

The endpoint:

```
http://localhost/swagger
```

Redirects to:

```
http://localhost/swagger/
```

**Comment by shockey** [comment]
Hey @AnthonyMastrean! I *think* this a Swashbuckle issue 😄 It appears that the Swashbuckle router isn't handling the case of slash vs no slash correctly.

Here's a rule of thumb for figuring out what's what:
- If it concerns loading the UI in a browser, it's probably **Swashbuckle**
- If it concerns something on the page once the UI has loaded, it's probably **Swagger UI**
- If it concerns an API endpoint returning unexpected results, it's probably **Swashbuckle**
- If it concerns Try-It-Out doing something strange when the endpoint works elsewhere, it's probably **Swagger UI**
- If it concerns something missing or incorrect in your Swagger document, it's probably **Swashbuckle**
- If it concerns incorrect UI behavior for a Swagger document that appears correct, it's probably **Swagger UI**

I'm going to close this out for now, but if the diagnosis on the Swashbuckle side finds an issue with the UI, I'm happy to reopen.

Thanks for the report!
