### ISSUE TITLE
confusing function name in component "try-it-out-button.jsx"

### ISSUE THREAD

**Issue by yshkk** [swagger-api/swagger-ui#4667]
![image](https://user-images.githubusercontent.com/9150795/41710339-0023f26c-7578-11e8-8d05-99fd7c39e806.png)
when clicking the button "Cancel", it triggers the function "onTryoutClick", while clicking the "Try it out" button, "onCancelClick" is triggered, that's really confusing.

And what's more, the prop  "enabled" is also puzzling:  when "enabled===true", the "Cancel" button is shown. So the prop "enabled"  means "enable the cancel button", not the "try it out" button?

Thanks for your time

**Comment by shockey** [comment]
> when clicking the button "Cancel", it triggers the function "onTryoutClick", while clicking the "Try it out" button, "onCancelClick" is triggered, that's really confusing.

Heh, yeah, that does seem backwards. Feel free to open a PR that fixes this if it's bothering you 😄 

> And what's more, the prop "enabled" is also puzzling: when "enabled===true", the "Cancel" button is shown. So the prop "enabled" means "enable the cancel button", not the "try it out" button?

`enabled` answers the question "is Try-It-Out mode currently enabled?". If it isn't enabled, we should show the button that lets the user go into Try-It-Out mode, and if it is enabled, we show a button that lets the user go back to documentation mode.
