### ISSUE TITLE
Disable "server" dropdown menu?

### ISSUE THREAD

**Issue by jftanner** [swagger-api/swagger-ui#4669]
### Q&A (please complete the following information)
 - OS: OSX
 - Browser: Chrome
 - Version: _Varies by developer, generally latest_
 - Method of installation: NPM, via `swagger-ui-express@2.0.8`
 - Swagger-UI version: 3.1.4 (_According to swagger-ui-express README_)
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
servers:
  - url: https://localhost:6021/api
```

Swagger-UI configuration options:
_No custom options specified. Using defaults._

### Screenshots

![image](https://user-images.githubusercontent.com/13968160/41729811-33eaed42-7548-11e8-832a-6828f828b6ed.png)

### How can we help?

We host the SwaggerUI with our API docs in the same app that provides the API. As part of that process, we programmatically modify the `servers` property of the yaml file to contain the correct server name for that instance. (So, for example, you get `localhost` with the proper port when working locally, the staging url when looking at staging, etc.) Because of this, there's only ever one server in the definition when passed to SwaggerUI.

With this being the case, is there a way to disable the "server" dropdown in the swagger UI? With only one server ever available in the list, it seems to take up a lot of unnecessary space.

I suspect we're just missing a simple configuration option, but I couldn't find anything via the Power of Google. :(

Thanks for any advice.

**Comment by jftanner** [comment]
One of the other devs figured it out options that work just fine for our needs:
```
{customCss: '.servers {display: none}'}
```

**Comment by jftanner** [comment]
Well, that's just embarrassing. I guess we can take that code out now. Thanks @hkosova.

**Comment by michael-o** [comment]
I'd like to ask to reopen this one because the actual issues has not been solve. Making the CSS hack will visually hide the element, but not prevent from creating. I have the very same issue here. Our URL section:

```
servers:
  - url: "{contextUrl}/api/v1"
    description: Current Server
```

is actually filitered on the fly by Spring WebMVC.

**Comment by webron** [comment]
@michael-o it's better to file a new issue because it was closed by the author. However, please read @hkosova's [comment](https://github.com/swagger-api/swagger-ui/issues/4669#issuecomment-399572155) as it provides a better solution overall.

**Comment by dum3n** [comment]
I'm using FastAPI (python) and I want to hide `Servers` dropdown in the documentation, the best way I've found so far is to run a javascript chunk to detect when the element loads on the page and hide it.
```

app = FastAPI(docs_url=None)

@app.get("/docs", include_in_schema=False)
async def custom_docs():
    html = get_swagger_ui_html(
        openapi_url="/openapi.json",
        title="API Docs"
    )
    html_body = html.body.decode("utf-8") + """
    <script>let i = setInterval(() => { let s = document.querySelector('.servers'), t = document.querySelector('.servers-title'); if (s && t) { s.remove(); t.remove(); clearInterval(i); } }, 100);
</script>
    """
    return HTMLResponse(content=html_body, status_code=200)
```

**Comment by michael-o** [comment]
> I'm using FastAPI (python) and I want to hide `Servers` dropdown in the documentation, the best way I've found so far is to run a javascript chunk to detect when the element loads on the page and hide it.
> 
> ```
> 
> app = FastAPI(docs_url=None)
> 
> @app.get("/docs", include_in_schema=False)
> async def custom_docs():
>     html = get_swagger_ui_html(
>         openapi_url="/openapi.json",
>         title="API Docs"
>     )
>     html_body = html.body.decode("utf-8") + """
>     <script>let i = setInterval(() => { let s = document.querySelector('.servers'), t = document.querySelector('.servers-title'); if (s && t) { s.remove(); t.remove(); clearInterval(i); } }, 100);
> </script>
>     """
>     return HTMLResponse(content=html_body, status_code=200)
> ```

Why no preprocess the YAML file?

**Comment by dum3n** [comment]
> > I'm using FastAPI (python) and I want to hide `Servers` dropdown in the documentation, the best way I've found so far is to run a javascript chunk to detect when the element loads on the page and hide it.
> > ```
> > 
> > app = FastAPI(docs_url=None)
> > 
> > @app.get("/docs", include_in_schema=False)
> > async def custom_docs():
> >     html = get_swagger_ui_html(
> >         openapi_url="/openapi.json",
> >         title="API Docs"
> >     )
> >     html_body = html.body.decode("utf-8") + """
> >     <script>let i = setInterval(() => { let s = document.querySelector('.servers'), t = document.querySelector('.servers-title'); if (s && t) { s.remove(); t.remove(); clearInterval(i); } }, 100);
> > </script>
> >     """
> >     return HTMLResponse(content=html_body, status_code=200)
> > ```
> 
> Why no preprocess the YAML file?

Could you provide an example please?

**Comment by michael-o** [comment]
> > > I'm using FastAPI (python) and I want to hide `Servers` dropdown in the documentation, the best way I've found so far is to run a javascript chunk to detect when the element loads on the page and hide it.
> > > ```
> > > 
> > > app = FastAPI(docs_url=None)
> > > 
> > > @app.get("/docs", include_in_schema=False)
> > > async def custom_docs():
> > >     html = get_swagger_ui_html(
> > >         openapi_url="/openapi.json",
> > >         title="API Docs"
> > >     )
> > >     html_body = html.body.decode("utf-8") + """
> > >     <script>let i = setInterval(() => { let s = document.querySelector('.servers'), t = document.querySelector('.servers-title'); if (s && t) { s.remove(); t.remove(); clearInterval(i); } }, 100);
> > > </script>
> > >     """
> > >     return HTMLResponse(content=html_body, status_code=200)
> > > ```
> > 
> > 
> > Why no preprocess the YAML file?
> 
> [@michael-o](https://github.com/michael-o) Could you provide an example please?

If the API is bundled with the ap, load the YAML into a hash, drop the servers property and return the bytestream.
