### ISSUE TITLE
"Try it out!" request uses wrong path

### ISSUE THREAD

**Issue by terriyu** [swagger-api/swagger-ui#467]
I'm having trouble getting the "Try it out!" request to work.  My Swagger API spec is at `http://localhost:7777/myapp/api-docs` and this is what I give to Swagger UI.  I have a single resource called `testquery` and it has a GET method.

Swagger UI generates the documentation and it looks great, except that when I click on the "Try it out!" button, it does a request to `http://localhost:7777/myapp/api-docs/testquery`, instead of `http://localhost:7777/myapp/testquery`.  I get a JSON file corresponding to the testquery spec, instead of the "Got it!" string that I'm expecting.

I tried playing around with the parameters `value` and `basePath` in the `@Api` annotation for my testquery method, but nothing worked.  `basePath` is ignored, and whatever I put in `value` is concatenated to `http:/localhost:7777/myapp/api-docs`.  Doing a relative `value = "/../testquery/"` doesn't work.  I'm using Swagger + Jersey + Grizzly framework.

Any ideas?  I'd be grateful for any help.

---

The contents of `http://localhost:7777/myapp/api-docs` are

```
{"apiVersion":"1.0.0","swaggerVersion":"1.2","apis":[{"path":"/testquery","description":"Test query"}]} 
```

The contents of `http://localhost:7777/myapp/api-docs/testquery` are

```
{"apiVersion":"1.0.0","swaggerVersion":"1.2","basePath":null,"resourcePath":"/testquery","produces":["application/json","application/xml"],"apis":[{"path":"/testquery","operations":[{"method":"GET","summary":"Get the test text","notes":"No notes for this method","type":"void","nickname":"getIt","produces":["text/plain"],"authorizations":{},"parameters":[],"responseMessages":[{"code":405,"message":"Invalid input"}]}]}]}
```

My source code looks like this:

```
@Path("/testquery") // Jersey
@Api(basePath = "mystuff", value = "/testquery", description = "Test query") // Swagger
@Produces({ "application/json", "application/xml" })
public class TestQuery {

    /**
     * Method handling HTTP GET requests. The returned object will be sent to the client as "text/plain" media type.
     *
     * @return String that will be returned as a text/plain response.
     */
    @GET // Jersey
    @Produces(MediaType.TEXT_PLAIN) // Jersey
    @ApiOperation(value = "Get the test text", notes = "No notes for this method") // Swagger
    @ApiResponses(value = { @ApiResponse(code = 405, message = "Invalid input") })
    public Response getIt() {
        return Response.ok().entity("Got it!").build();
    }
}
```

**Comment by yaneyba** [comment]
hi @terriyu, did you finally get it resolved? I am experiencing the same issue.

**Comment by webron** [comment]
@yaneyba - this is an ancient issue. If you're experiencing it, make sure you're using the latest version. If that's the case, please open a new ticket with the details.
