### ISSUE TITLE
Swagger UI 2.0 always takes accept header as "application/json" even though I specifically put globally consumes as "text/xml". How do I correct this?

### ISSUE THREAD

**Issue by pruthvigh** [swagger-api/swagger-ui#4673]
Because of this mimatch I am getting a zero response code and empty response headers.

**Comment by shockey** [comment]
@pruthvigh, can you provide a definition that reproduces this issue?

**Comment by pruthvigh** [comment]
`"paths": {
    "/accounts/search": {
      "get": {
        "tags": [
          "account-controller"
        ],
        "summary": "VCDA account API search",
        "operationId": "VCDA account API search",
        "produces": [
          "application/json",
          "application/hal+json",
          "application/xml"
        ],`

This endpoint like many of our endpoints returns a 403 unauthorized access xml response back but, because Swagger UI everytime sends "accept" as "application/json" we are getting a zero response code back. On chrome developer tools network tab I get a correct xml response back.

**Comment by shockey** [comment]
@pruthvigh, a full Swagger definition would be more helpful 😄 

When this happens, are you seeing any errors in your devtools console?

**Comment by kumarz** [comment]
I am experiencing the same issue, my response content type is not getting passed in the swagger call. I tried to view the header on the browser's NETWORK tab. 

I dont see the request content-type header param getting passed in. My service calls are actually expecting it  and because of this the call fails.. Please advise.

**Comment by shockey** [comment]
@pruthvigh @kumarz, please make sure that you've set your services up to send CORS headers.

Docs here: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/cors.md

**Comment by pruthvigh** [comment]
@shockey Like I said before even after I enable CORS I am still seeing a zero response code because Swagger UI takes accept as application/json.
![screen shot 2018-06-26 at 9 34 57 am](https://user-images.githubusercontent.com/11011819/41919585-7e8851d4-7924-11e8-8749-7ccb506dd27e.png)
![screen shot 2018-06-26 at 9 35 21 am](https://user-images.githubusercontent.com/11011819/41919586-7e97ef5e-7924-11e8-8038-8f2a421ca049.png)

These are the responses I get back.

**Comment by shockey** [comment]
Ah, I see now you're using Swagger UI 2.0. We don't support that version any longer (it was discontinued 18 months ago), can you try this with the newest version?

**Comment by kumarz** [comment]
@shockey the latest branch that I see is 2.X is that what you are referring to the latest ?

**Comment by pruthvigh** [comment]
@shockey I am actually an Intern and is developing the portal for our already existing API's. Techwise API's are written in Spring. How much of a code change are we talking here to upgrade to the latest version of Swagger?

**Comment by shockey** [comment]
@kumarz, the latest versions can be found on the `master` branch 😄 

@pruthvigh, it depends on how you're using Swagger UI (if your work os open-source, feel free to drop a link), but most use cases are pretty easy to migrate. If you're using the configuration options, consult the 3.0 documentation to make sure we support it in the new version.

**Comment by pruthvigh** [comment]
@shockey I will try and make the changes and get back If I have any doubts. Thanks much for the help.
I am closing this issue for now.
