### ISSUE TITLE
Unable to see Model after clicking "Try it out" in a POST action

### ISSUE THREAD

**Issue by zilongl** [swagger-api/swagger-ui#4681]
This is for Swagger v2

The steps to reproduce are:
1. Find a POST action
2. Unfold
3. Click "Try it out"

And then, things get funky:
4. Under "Description", click "Model"
**nothing happens...**
5. Above "Parameter content type", click "Cancel"
6. Repeat step 4
**nothing happens...**
7. Click "Cancel" on the right where "Try it out" was.
**Model magically appears 😮** 

It's quite annoying since Model is quite useful to see what each parameter means and if it's mandatory.

**Comment by Scriptodude** [comment]
It is indeed quite annoying, it seems to affect the petstore.swagger.io too, meaning it isn't on our side

**Comment by bestmike007** [comment]
It seems to be designed this way: https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/model-example.jsx#L51-L63, it is the same behavior with the latest version v3.17.3.

I'll submit a PR as a proposal, and I'll publish an url to preview.

**Comment by bestmike007** [comment]
Here is the url to preview the changes: http://bestmike007.com/swagger-ui/issue-4681
