### ISSUE TITLE
Swagger-ui & request model

### ISSUE THREAD

**Issue by AndreyOsadchuk** [swagger-api/swagger-ui#4688]
**Endpoints**

@RestController
@RequestMapping("/api/tests/validations")
public class ValidationTestController {

    @RequestMapping(value = "/phenix/http/req", method = POST, produces = APPLICATION_JSON_UTF8_VALUE)
    public PhenixResp<String> phenixHttpReqTest(@RequestBody @Validated PhenixReq req) {
        return new PhenixResp<>("Good", "Valid sysId=" + req.getWhseSysId());
    }

    @RequestMapping(value = "/phenix/http/req/paginated", method = POST, produces = APPLICATION_JSON_UTF8_VALUE)
    public PhenixResp<String> phenixHttpReqTest(@RequestBody @Validated PhenixReqPaginated req) {
        return new PhenixResp<>("Good", "Valid sysId=" + req.getWhseSysId() + " onPage=" + req.getOnPage() + " page=" + req.getPage());
    }

    @RequestMapping(value = "/phenix/http/req/grid", method = POST, produces = APPLICATION_JSON_UTF8_VALUE)
    public PhenixResp<String> phenixHttpReqTest(@RequestBody @Validated PhenixReqGrid req) {
        return new PhenixResp<>("Good", "Valid sysId=" + req.getWhseSysId() + " onPage=" + req.getOnPage() + " page=" + req.getPage() + " sortBy=" + req.getSortBy() + " filterBy=" + req.getFilterBy() + " gridId=" + req.getGridIdentifier());
    }
}

**Request mapping**
public class PhenixReq {
    private Long whseSysId;

    //Constructors
    public PhenixReq() {
    }

    public PhenixReq(Long whseSysId) {
        this.whseSysId = whseSysId;
    }

    //Getters & setters
    public Long getWhseSysId() {
        return whseSysId;
    }

    public void setWhseSysId(Long whseSysId) {
        this.whseSysId = whseSysId;
    }
}

public class PhenixReqPaginated extends PhenixReq {
    private long page;
    private long onPage;

    //Constructors
    public PhenixReqPaginated() {
    }

    //Getters & setters
    public long getPage() {
        return page;
    }

    public void setPage(long page) {
        this.page = page;
    }

    public long getOnPage() {
        return onPage;
    }

    public void setOnPage(long onPage) {
        this.onPage = onPage;
    }
}

public class PhenixReqGrid extends PhenixReqPaginated {
    private GridIdentifier gridIdentifier;
    private LinkedHashMap<String, SortOrder> sortBy;
    private Map<String, FilterByParameter> filterBy;

    //Constructors
    public PhenixReqGrid() {
    }

    //Getters & setters
    public GridIdentifier getGridIdentifier() {
        return gridIdentifier;
    }

    public void setGridIdentifier(GridIdentifier gridIdentifier) {
        this.gridIdentifier = gridIdentifier;
    }

    public LinkedHashMap<String, SortOrder> getSortBy() {
        return sortBy;
    }

    public void setSortBy(LinkedHashMap<String, SortOrder> sortBy) {
        this.sortBy = sortBy;
    }

    public Map<String, FilterByParameter> getFilterBy() {
        return filterBy;
    }

    public void setFilterBy(Map<String, FilterByParameter> filterBy) {
        this.filterBy = filterBy;
    }
}

**Swagger UI**
Here must be only whseSysId field
![image](https://user-images.githubusercontent.com/13258565/42209521-890dfc10-7eb7-11e8-9590-9b43e9114b57.png)

Here must be only whseSysId , page, onPage fields
![image](https://user-images.githubusercontent.com/13258565/42209738-15711db8-7eb8-11e8-8008-929a4859a804.png)

Here must be whseSysId , page, onPage, gridIdentifier, sortBy, filterBy fields
![image](https://user-images.githubusercontent.com/13258565/42209797-43059920-7eb8-11e8-877f-89cd96bb0cda.png)

**Description**
If you take a look at endpoint method names then you will see same names but they steel has different signatures. I suppose that you are building response map for swagger-ui where key is a name of method. That is why we see in UI same request models(params). Your key in map should containt not only methos name but also income params.

**Comment by AndreyOsadchuk** [comment]
If I assign to this methods different names then UI shows correct request models. Checked!

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Note that you need to provide an API definition (_not_ annotations) when you file.

Thanks!

PS: You're using Swagger UI v2, **which we dropped support for in early 2017**. Consider moving to v3, which we can help you with!
