### ISSUE TITLE
Add integrity attribute to external stylesheet link in index.html

### ISSUE THREAD

**Issue by Liero** [swagger-api/swagger-ui#4689]
### Q&A (please complete the following information)
 - Swagger-UI version: [e.g. 3.17.2]

 ### Problem:

Our internal security policy says, that all external resources linked in html (scripts, css, fonts) must include 'integrity' attribute in order to comply with "Content-Security-Policy"

### Proposed solution

Make sure that all external scripts and css files uses intergrity attribute.

 Replace:

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700"
          rel="stylesheet">

with:

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700"
          rel="stylesheet"
          integrity="sha384-s8lhM4WUVN+t5smKz39OwPzRTBvJS74uRnuAHdkOsEfLTTu4b5jtj1Cm4i7J32Y0"
          crossorigin="anonymous">

**Comment by shockey** [comment]
Sure, feel free to open a PR for this 😄

**Comment by shockey** [comment]
@Liero, FYI - we just dropped our usage of Google Fonts in #4598, so this shouldn't be an issue going forward.
