### ISSUE TITLE
Please update webpack-cli dependency

### ISSUE THREAD

**Issue by jd-carroll** [swagger-api/swagger-ui#4692]
I know this is a trivial request, but it would be great if someone could update the `webpack-cli` dependency.

The 2.0.4 version of `webpack-cli` includes a dependency with a `git://...` version instead of a semantic version.  Simply updating the version to 2.1.5 resolves this issue.  Having `git://` style versions (instead of ~#.#.#) do not work behind our corporate proxy.

Thanks!

**Comment by tim-lai** [comment]
Closing issue. SwaggerUI now uses `"webpack-cli": "^3.3.11"`
