### ISSUE TITLE
parameters with example value always get reset

### ISSUE THREAD

**Issue by 1pete** [swagger-api/swagger-ui#4694]
### Q&A
 - OS: Mac
 - Browser: Chrome
 - Version: 67
 - Method of installation: dist assets
 - Swagger-UI version: 3.17.2
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
swagger: "2.0"
info:
  title: "Swagger UI"
paths:
  /user:
    get:
      summary: "get User"
      parameters:
      - name: "id"
        in: "query"
        type: "number"
        example: "1"
      responses:
        default:
          description: "OK"
```

### Describe the bug you're encountering
Parameters with example value always got reset back to value in spec

### To reproduce...

1. try to execute `GET /user`
1. edit `id` to any value
1. it always get reset back to `1`

### Expected behavior
it should use value that is set.

**Comment by hkosova** [comment]
OpenAPI 2.0 does not support the `example` keyword for parameters, use the extension property `x-example` instead. Also, since the the parameter type is number, the example should be the number `1` not the string `"1"`.

```yaml
x-example: 1
```
After this change "try it out" works just fine.

**Comment by 1pete** [comment]
It worked before in v3.13, but never mind, i'll update my spec.

Thanks.
