### ISSUE TITLE
oAuth2 redirect page does not work with Internet Explorer 

### ISSUE THREAD

**Issue by nicolashenry** [swagger-api/swagger-ui#4702]
### Q&A (please complete the following information)
 - OS: Windows 7
 - Browser: Internet Explorer
 - Version: 11
 - Method of installation: dist assets
 - Swagger-UI version: 3.17.2
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
Any config using oAuth2 authentication flow.

### Describe the bug you're encountering
oAuth2 redirect page does not work with Internet Explorer 11, the redirect page get stuck on an empty webpage (oauth2-redirect.html) with an error (in french sorry):
```
SCRIPT5007: Impossible d’obtenir la propriété  « swaggerUIRedirectOauth2 » d’une référence null ou non définie
``` 
It says 'Impossible to obtain the property "swaggerUIRedirectOauth2" from a null or undefined reference'.

### To reproduce...
Try to use oAuth2 with Internet Explorer 11

### Expected behavior
I except the window to close and be back authenticated on Swagger UI interface (like in Chrome).

### Additional context or thoughts
It seems that window.opener is undefined in Internet Explorer which cause this issue

**Comment by jeremymeng** [comment]
Hit this too. Are there any workarounds?

**Comment by sonphnt** [comment]
I have the same issue too. window.opener is null in IE11 and Microsoft Edge. Do we have a solution for this?

**Comment by jurepurgar** [comment]
Same problem here. I found out that adding the page to the "trusted sites" in IE resolves the problem for both IE and Edge.

**Comment by patricknolan** [comment]
Same issue here. Any resolution for this one? This should be a high priority issue if oAuth2 fails when using IE.

**Comment by tim-lai** [comment]
IE is no longer supported. https://github.com/swagger-api/swagger-ui/issues/5808#issuecomment-576953636
