### ISSUE TITLE
Swagger-UI: insert HTML content after “Execute”

### ISSUE THREAD

**Issue by nundee** [swagger-api/swagger-ui#4703]
Hi,

I have the following customized Swagger-UI layout consisting of two columns. 
In the left pane the SwaggerUI and in the right pane a empty &lt;div&gt; container

[Picture](https://i.stack.imgur.com/t6Okv.png)

The response I get on 'Execute' contains some HTML:
```
<div id="some guid"> 
<script> ... code to fill that div </script> 
```
How can I put this content into the right pane ?
I tried with a **responseInterceptor** but the script gets not executed. 
Is there any callback or event I can use ?

Thanks in advance
Nandi

**Comment by nundee** [comment]
Hi @shockey 
Thank you for your reply. The problem is already solved. I had to put the script (returned by the server) into a "ContextualFragment". This will force the script to execute immediately.
Not a "Swagger UI" problem :)

**Comment by shockey** [comment]
Awesome! Closing 😄
