### ISSUE TITLE
Broken navigation

### ISSUE THREAD

**Issue by KrzysztofMadejski** [swagger-api/swagger-ui#471]
I have problems with navigation (ie. expanding resource list). I guess it's due to fact I am not hosting SwaggerUI as a main page.

It's hosted at: http://mp.local.pl/api/sth
When I click the link http://mp.local.pl/api/sth#!/pet

I would expect location to change accordingly, but instead I'm "redirected" to: 
http://mp.local.pl/api/!/pet

**Comment by paulwilton** [comment]
I have same issue when hosting swagger-ui on a non-root path
what was the fix for this ?

**Comment by KrzysztofMadejski** [comment]
Somebody added/deleted comment, so I will respond to the thread.

It's working in http://petstore.swagger.wordnik.com/ container, because it's hosted under root directory. Put the code in the subdirectory, ie. http://petstore.swagger.wordnik.com/whatever/ and it should stop working.

Finally we've hacked it somehow, can't remember how. The issue is quite old, I'll reopen if we still have this problem with new swagger (if we have time to test it).

**Comment by kbadiger** [comment]
Hi , i have a navigation issue with my swagger ui ,  for example i have a url  like this https://petstore.swagger.io/#/pet/updatePet   and if i copy same url and paste in another tab it is redirecting to main page  istead of this page , please help me to overcome from this.
