### ISSUE TITLE
Generate input value when clicking submit

### ISSUE THREAD

**Issue by verschoof** [swagger-api/swagger-ui#4714]
### Q&A (please complete the following information)
 - Method of installation: Composer
 - Swagger-UI version: v3.17.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### How can we help?
In our API we created a long time ago own annotations.
Now I wanna try if I can use OpenAPI and swagger.

In our API we have the field `hash` this hash are a few fields included a secret key for the hashing.
The keys (most of them) are user input.

Wat I want: The hash field gets a default value "Will be calculated" and when I click on execute I want to generate the hash and put in in the input and then swagger can do the rest, but is this possible?

**Comment by bestmike007** [comment]
You might need to write an auth plugin to solve this. Unless it's a standardized use case it should not be a feature in this project.

However, using a client key/secret pair to sign request parameters could be generalized as a common auth method other than oauth2, basic auth, etc. In such case, the key/secret pair, sign method (e.g. ordered parameter map sign with secret using HMAC_SHA256), timestamp parameter key (e.g. ts, won't be in the parameter form but will be set for each request if present. Might also need to configure the timestamp format, e.g. UNIX time ms, UNIX time seconds, etc.), and client key parameter key, etc.

**Comment by verschoof** [comment]
We also request a timestamp.

It would be nice if there are places I can hook in on the javascript, in this case, if it would possible to hook a function before swagger goes do his thing, I can generate the timestamp en make the hash.

Maybe, it would be nice if I can hook on the "request" input to swagger so I can modify it and return it.

**Comment by bestmike007** [comment]
Yes you can do this with a `requestInterceptor` configuration(https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#network).

**Comment by verschoof** [comment]
Sweet! I go try this out, thanks for the help!

**Comment by verschoof** [comment]
I do have a follow-up question about the `requestInterceptor`, now I get the request, but I also need the documentation of the call it's doing, how do I get that?

I need this so I can see what parameters the docs has, so I can lookup the description of the hash field and see what fields I need for the hashing. 🤔

**Comment by bestmike007** [comment]
I suppose that all the fields other than hash and timestamp are in your docs. Will it be all right if you describe each field with some phrase to indicate if that field will be used for hashing or not?

Or if that's not the case, is that what you need to configure the subset of fields used for hashing in your custom requestInterceptor for each api respectively?

**Comment by verschoof** [comment]
Yes. als the hash and timestamp field are in the docs.
Well, if I go describe each field by it self its hard to see in which order is should be.

For now I have a work around;

When swagger is done with loading I do a ajax request to the json file and save the response in memory.
When I "try out" a call I go match the request path with one of the path's in the json.
After this step I know what call it is and search the hash field and now I can use the description.

The downside is now, that I do 2 times the same call.
