### ISSUE TITLE
Swagger doesn't recognize x-www-urleconded parameters

### ISSUE THREAD

**Issue by Gabriel-Pellegrini** [swagger-api/swagger-ui#4716]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04 x64
 - Swagger/OpenAPI version: Swagger 2.0

### Describe the bug you're encountering

I had a swagger documentation on version 2.0 where i put the path consumes as application/x-www-urlencoded but when i try to request i receive the following error.

`{
    "message": "Request validation failed: Parameter (username) is required",
    "code": "REQUIRED",
    "failedValidation": true,
    "path": [
        "paths",
        "/auth/login",
        "post",
        "parameters",
        "0"
    ],
    "paramName": "username"
}`

### The Request
But i already passed the parameter as we can see on this curl

```
curl -X POST \
http://localhost:10010/v1/auth/login \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'username=LOGIN&password=MYPASS&userType=employee'
```
### Content & configuration
I've used the following Swagger.yaml

Swagger/OpenAPI definition:
```yaml
/auth/login:
# binds a127 app logic to a route
x-swagger-router-controller: "authentication"
x-a127-apply: {}
post:
  summary: Try to login
  description: Try to login with credencials based on username/password. This API will return all "habitant" information if login were successful.
  # used as the method name of the controller
  operationId: login
  consumes: 
    - application/x-www-form-urlencoded
  tags: 
  - Auth
  parameters:
    - name: username
      in: formData
      description: Username to login.
      required: true
      type: string
    - name: password
      in: formData
      description: Password to login.
      required: true
      type: string
      format: password
    - name: userType
      in: formData
      required: true
      default: customer
      <<: *UserType
  responses:
    "200":
      description: Success. If there are attributes with empty values they won´t be returned
      schema:
        # a pointer to a definition
        $ref: "#/definitions/AuthResponse"
    "401":
      description: Unauthorized
      schema:
        $ref: "#/definitions/ErrorResponse"
    "500":
      description: Internal Server Error
      schema:
        $ref: "#/definitions/ErrorResponse"
    "501":
      description: Not Implemented
      schema:
        $ref: "#/definitions/ErrorResponse"

```

### Screenshots

![image](https://user-images.githubusercontent.com/34742130/42572581-1916dce4-84f0-11e8-9294-79f3f13bc81e.png)

### How can we help?
There is anyone that's passed for this problem ?  When i use application/json format it's works normally.

**Comment by hkosova** [comment]
Hi @Gabriel-Pellegrini,

This repository is for Swagger UI, which is a web page that renders interactive API docs, like the one on http://petstore.swagger.io. The error in question is returned by your server and has nothing to do with Swagger UI. Please file an issue with the library/framework you are using on the server side.

`x-a127-apply` suggests you might be using https://github.com/apigee-127/swagger-tools. If so, your issue looks like this one: https://github.com/apigee-127/swagger-tools/issues/409.

**Comment by shockey** [comment]
Closing; this appears unrelated to Swagger UI. Reply if this is in error, and I'll reopen 😄
