### ISSUE TITLE
translation support

### ISSUE THREAD

**Issue by ghost** [swagger-api/swagger-ui#472]
I work for a french speaking organization and we would to like to deploy swagger-UI translated in french. For the moment I translated the hard coded strings in swagger-ui.js directly, but It would be nicer if we could move those strings to a separated file and implement translations support so I don't have to retranslate every new version of the file.

My organisation is willing to give me time to do this. Was there any plans for this or thoughts about how to do it ? If not I can come up with something.

**Comment by ksimka** [comment]
All who also needed localization support, take a look at #924 (very simple, but it works :)

**Comment by webron** [comment]
Does it support RTL languages? ;)

**Comment by ksimka** [comment]
@webron, sure! ))

**Comment by to-kra** [comment]
@fehguy How can I show lang specific swagger-ui ? thanks

**Comment by sergiogragera** [comment]
Hi @fehguy in a previous comment you said:

> Second, the content in the swagger JSON description (that's what I was referring to). We will have the ability to add custom values in it, which can be used by the UI for localization.

What about this?

**Comment by fenomeno83** [comment]
I've created a my solution:
https://github.com/fenomeno83/SwaggerGlobalization
