### ISSUE TITLE
Swagger-ui minified not displaying part of Responses

### ISSUE THREAD

**Issue by ricardodejuan** [swagger-api/swagger-ui#4720]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome, safari, firefox, ...
 - Version: latest
 - Method of installation: npm
 - Swagger-UI version: 3.17.3
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
I have a frontend app using Vue.js (2.5.16) along with vie-cli 3.0 (webpack 4) and swagger-ui (3.17.3):
https://github.com/ricardodejuan/vue_swaggerui

The same problem with vue-cli 2.0:
https://github.com/ricardodejuan/vue_swaggerui_webpack2

When I run in localhost the entire definition is displayed correctly, but when i create the version to production (npm run build) and I am deploying on Pivotal Cloud Foundry using the staticbuildpack I cannot see the Example value or Model inside of the black boxes (see screenshots below)

Swagger/OpenAPI definition:
https://petstore.swagger.io/v2/swagger.json

Swagger-UI configuration options:
```js
import SwaggerUIBundle from 'swagger-ui'
import 'swagger-ui/dist/swagger-ui.css'

SwaggerUIBundle({
        url: 'https://petstore.swagger.io/v2/swagger.json',
        dom_id: '#swagger-ui',
        deepLinking: false,
        presets: [
          SwaggerUIBundle.presets.apis
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ]
      })
```

### Screenshots
https://imgur.com/a/FpzT5C7

### How can we help?
I don't know if the issue is a conflict when I am minifying the app or i am missing any configuration. I have the same issue with Vue-Cli 2.0.

Should i modify something in the webpack to separate files to be minified?

**Comment by shockey** [comment]
@ricardodejuan, this is because some (new-ish) code in the resolver relies on `Function.prototype.name`, which I imagine your minifier is modifying. You should be able to solve this by instructing your minifier to preserve functions named `GeneratorFunction`.

This is, clearly, not a great situation. I'm going to tag this as a bug and look into approaches that _don't_ rely on minifier kindness.

**Comment by ricardodejuan** [comment]
@shockey it worked. Thank so much!!

I modified the UglifyJsPlugin from webpack.prod.conf.js the following:
```js
new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true,
      **mangle: {
        except: ['GeneratorFunction']
      }**
    })
```

**Comment by ChrisBarriere** [comment]
just a type in the mangle configuration of webpack uglify plugin. it's ```reserved``` and not ```except```:
```
mangle: {
    except: ['GeneratorFunction']
}
```

**Comment by shockey** [comment]
This will be resolved (no pun intended) on Thursday, when we cut a new release 😄
