### ISSUE TITLE
How can you minify swagger-ui into one file?

### ISSUE THREAD

**Issue by renier** [swagger-api/swagger-ui#473]
I'm wondering if there is a way to minify and concatenate all the javascript and css into one file (one for js, one for css).

Does this exist already?

**Comment by ejain** [comment]
swagger-ui is unusable over a sluggish network: Docs for a simple API with less than a dozen basic endpoints require ~60 requests ~2mb of data!

**Comment by drewish** [comment]
Any one spent any time on this in the year and a half since then? Pretty insane watching all the connections while waiting for Swagger UI to load.

**Comment by fehguy** [comment]
@drewish if you're seeing an issue, consider opening a new ticket.  Open connections can be for many reasons.

**Comment by drewish** [comment]
Uh it's pretty obvious that it's fetching the dozen or so dependencies.

**Comment by fehguy** [comment]
So as I suggested, open a new issue and you might make sure it's not because of calls to your swagger definition, which may have references that trigger more calls.  Or don't, but that's the right path if you want action
