### ISSUE TITLE
Enum value doesn't change if it's required

### ISSUE THREAD

**Issue by SolidTerre** [swagger-api/swagger-ui#4738]
### Content & configuration
 - OS: macOS
 - Browser: Chrome & Firefox
 - Version: Latest in date
 - Method of installation: dist assets (bug can be reproduced on editor.swagger.io)
 - Swagger version: Swagger 2.0

Trying to implement a get path with parameters in path, with an enum string parameter.

### Describe the bug you're encountering
Enum value doesn't change in request if it's required. When it's not a required value, it changes successfully.

### To reproduce...
1. Open [https://editor.swagger.io](https://editor.swagger.io)
2. Edit the GET path /pet/{petId} to allow enums instead of input (Full file here [swagger-bug.txt](https://github.com/swagger-api/swagger-ui/files/2201661/swagger-bug.txt)) 
3. Try out by selecting ID 1 and executing ==> Correct result
4. Change enum value to ID 2 and execute ==> still trying to get ID 1

### Expected behavior
When changing enum to ID 2, sending a request for parameter ID 2

#### Call with ID 1
![image](https://user-images.githubusercontent.com/8171049/42818523-632043ee-89d1-11e8-982b-42902bef7c0e.png)
#### Call with ID 2
![image](https://user-images.githubusercontent.com/8171049/42818530-68bfdc1a-89d1-11e8-87a7-b35c205051e1.png)

**Comment by bestmike007** [comment]
Duplicate of #4693. Fixed since v3.17.4. The online swagger editor is still using Swagger UI v3.17.3.

**Comment by SolidTerre** [comment]
@bestmike007 thank you for answering and sorry for opening a duplicate then.
