### ISSUE TITLE
Submit An Array of Integer Elements In formdata

### ISSUE THREAD

**Issue by Crackz** [swagger-api/swagger-ui#4741]
Swagger sends the field location (array) as a single value 

![formdataArray](https://image.ibb.co/dr5cTd/Capture.png)

```
/signup: {
        post: {
          tags: ['Authentication'],

          requestBody: {
            required: true,
            content: {
              'multipart/form-data': {
                schema: {
                  type: 'object',
                  properties: {
                    ...schema.CreateUserBody.properties,
                    location: {
                      type: 'array',
                      items: {
                        type: 'integer'
                      },
                      example: [32.3046505, 30.6080822]
                    },
                    profileImg: {
                      type: 'string',
                      format: 'binary'
                    },
                  },

                }
              }
            }
          },
          responses: {
            201: {
              description: 'User Created',
              content: {
                'application/json': {
                  // schema:{
                  //   $ref: '#/components/schemas/User'
                  // }
                }
              }
            }
          }
        },
      }
```

i expected that the field(location) will be repeated for each element in the array 

how would i make it work this way ?

**Comment by hkosova** [comment]
@Crackz So you want a multipart request with duplicate field names?

```
POST /signup
Content-Type: multipart/form-data; boundary=acb

--acb
Content-Disposition: form-data; name="location"

2112
--acb
Content-Disposition: form-data; name="location"

3232
--acb
Content-Disposition: form-data; name="location"

1234
--acb--
```

OpenAPI Specification says this will be the case when [uploading an array of files](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#considerations-for-file-uploads):

```yaml
requestBody:
  content:
    multipart/form-data:
      schema:
        properties:
          # The property name 'file' will be used for all files.
          file:
            type: array
            items:
              type: string
              format: binary
```

but I'm not sure if this is supported for arrays of primitives. @webron do you happen to know this? Exploded arrays `location=2112&location=3232` is the default array style for `application/x-www-form-urlencoding` requests, but it's not clear if exploded arrays can be defined for `multipart`.

**Comment by Crackz** [comment]
[Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#special-considerations-for-multipart-content)

> If the property is a primitive, or an array of primitive values, the default Content-Type is text/plain

but i can't find a way to change this behaviori tried style and explode but failed to make it work.

**Comment by seanmetrix** [comment]
I just ran into this bug as well. My case is with application/x-www-form-urlencoded. I think the issue is related to the requestBody section.

I am attaching an example where explode is set to false in both the parameter block and the requestBody and they behave differently.

![0](https://user-images.githubusercontent.com/314787/44641239-e6ea0200-a97a-11e8-8f26-6b560ec0dc8e.png)

[metrixsean_test_1.0.0_swagger.zip](https://github.com/swagger-api/swagger-ui/files/2322434/metrixsean_test_1.0.0_swagger.zip)

**Comment by webron** [comment]
@seanmetrix since it's a different media type, it's a different issue than the OP. Please file a new ticket so we can work on it separately.

**Comment by hkosova** [comment]
@Crackz the next version of the spec, OpenAPI 3.1, will support exploded arrays in `multipart/form-data` requests, and this is the default serialization style for arrays in form data (i.e. `style: form` + `explode: true`).

**Comment by Crackz** [comment]
i will try it when gets supported 
thanks for keeping me up !

**Comment by mma5997** [comment]
In this [comment ](https://github.com/swagger-api/swagger-ui/issues/4741#issuecomment-416114268) above, I can see that the array types have "Add Item button", but its now showing what type of array is it... here its of type string. 

I am facing a same issue at my end. 
Please can anyone point me to which version its fixed because if I paste the same JSON in editor.swagger.io I can see it as "Add string item".
Thanks :)

**Comment by mathis-m** [comment]
@mma5997 I added the type label and support for nested arrays with [v3.44.1](https://github.com/swagger-api/swagger-ui/releases/tag/v3.44.1). json schema array items (#7007) (2016c18)

**Comment by mma5997** [comment]
Thanks @mathis-m, will test with the dist of that version and get back if any concerns :)
