### ISSUE TITLE
Empty model in Internet Explorer 11

### ISSUE THREAD

**Issue by ljb** [swagger-api/swagger-ui#4748]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Internet Explorer 11
 - Version: 11.165.17134.0
 - Method of installation: N/A
 - Swagger-UI version: That which is used for the pet store demo site
 - Swagger/OpenAPI version: That which is used for the pet store demo site

### Describe the bug you're encountering
Some of the Example Value" and "Model" boxes are empty when viewing the pet store demo site in Internet Explorer 11.

### To reproduce...
1. Start Internet Explorer 11
2. Go to http://petstore.swagger.io/#/user/createUsersWithArrayInput
3. Example Value is `  [ null ] `
4. Click on Model
5. Model is ` [ { } ]`

### Expected behavior
The model should contain values such as id and username. Corresponding values should then be shown in the "Example Value" box also.

### Additional context or thoughts
These problems only occur in Internet Explorer 11. It works as expected in Edge, Firefox and Chrome.

Earlier versions of Swagger UI works properly with Internet Explorer 11. I'm using the Swagger-Net library in my application, and it works with version 8.3.17.101, but it stopped to work with version 8.3.17.302. I guess that that version of the library updated to a version of Swagger UI that contains the problem.

**Comment by shockey** [comment]
Confirmed.

**Comment by shockey** [comment]
Fixed via https://github.com/swagger-api/swagger-js/pull/1358 🎉

**Comment by shockey** [comment]
Fix confirmed in a `swagger-ui@3.17.6` release candidate build. Closing! 🎉

**Comment by shockey** [comment]
Thanks for reporting this, @ljb!
