### ISSUE TITLE
Empty array emits query param without value.

### ISSUE THREAD

**Issue by AmazingTurtle** [swagger-api/swagger-ui#4754]
According to this:
![image](https://user-images.githubusercontent.com/2357438/43039401-a4a53578-8d2c-11e8-9338-624528f91c5c.png)

I do expect to not sent tags at all in the query params:
![image](https://user-images.githubusercontent.com/2357438/43039403-b0965b82-8d2c-11e8-88d1-2b2be8a9b35d.png)

Usually this is interpreted as an array in backends: `[""]`
Therefore we're having 1 item even though we sepcify it to have 0 items in the UI.

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template: specifically, your report lacks a Swagger definition that we can use to reproduce the issue, and information on the OS/browser/UI version you're seeing this in.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
