### ISSUE TITLE
Client-side validation fails for a defined model that is required, even when the auto-populated data is correct

### ISSUE THREAD

**Issue by dantaub** [swagger-api/swagger-ui#4755]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: current master
 - Method of installation: zip file, copy paste 'dist' into node_modeule I'm using
 - Swagger-UI version: 3.17.4+ / master
 - Swagger/OpenAPI version:Swagger 2.0

### Content & configuration

Using this definition:
```
{
  "basePath": "/",
  "definitions": {
    "ReqNameJSON": {
      "properties": {
        "name": {
          "description": "name of person making request",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
  },
  "host": "localhost:8000",
  "info": {
    "description": "Test server",
    "title": "APIs",
    "version": "1.0.0"
  },
  "parameters": {},
  "paths": {
    "/hello/": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "description": "This route will respond greetings to name in json request body.",
        "parameters": [
          {
            "description": "username or email",
            "in": "body",
            "name": "name",
            "required": true,
            "schema": {
              "properties": {
                "name": {
                  "description": "name of person making request",
                  "type": "string"
                }
              },
              "required": [
                "name"
              ]
            },
            "type": "ReqNameJSON"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200 ": {
            "description": " An object with the key 'msg'"
          },
          "default ": {
            "description": " Unexpected error"
          }
        },
        "tags": [
          "hello "
        ]
      }
    }
  },
  "swagger": "2.0",
  "tags": [
    {
      "description": " Test Demo",
      "name": "hello "
    }
  ]
}
```

### To reproduce...

1. Open API in UI
2. Click "try it out" for post
3. Click "Execute"

The box turns red and no network traffic is detected.

### Expected behavior
We expect the client-side validation to pass, since there is properly-formatted JSON with the required properties available.

### Screenshots

![screen shot 2018-07-23 at 10 24 12 am](https://user-images.githubusercontent.com/33430862/43083040-8ac39824-8e63-11e8-8f7a-ac12f72e64bd.png)

### Additional context or thoughts

This seems to be related to client-side validation with required properties. It doesn't change if we're using "header" instead of "body" for "in":.

**Comment by hkosova** [comment]
There are syntax errors in your spec, as you can see if you paste your spec into http://editor.swagger.io.

1) Remove `type: ReqNameJSON` from the body parameter. Body parameters use `schema`, they do not use `type` directly.

2) Remove extra space at the end of the `'200 '` and `'default '`:
   ```
   '200 ':
       ^

   should be
   '200':
   ```

After these fixes "try it out" works OK.

**Comment by dantaub** [comment]
@hkosova  thank you for looking into it and showing me the validation tool. I will continue this discussion with the project maintainer for the library I'm using to generate the swagger.
