### ISSUE TITLE
try-it-out failed to submit a request when there's an enum field in formData.

### ISSUE THREAD

**Issue by SongJoey** [swagger-api/swagger-ui#4756]
### Q&A (please complete the following information)
 - OS: [e.g. macOS] MacOS
 - Browser: [e.g. chrome, safari] chrome
 - Version: [e.g. 22] 67
 - Method of installation: [e.g. npm, dist assets] docker
 - Swagger-UI version: [e.g. 3.10.0] {"swaggerUi":{"version":"3.17.4","gitRevision":"ga994f2cf","gitDirty":false,"buildTimestamp":"Sat, 14 Jul 2018 07:12:57 GMT","machine":"banjo"}}
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'
info:
  title: test doc
  description: 'test doc '
  license:
    name: Copyright @2018
  version: 1.0.0
host: www.example.com
basePath: /test/API
tags:
  - name: devices
    description: devices
schemes:
  - http
  - https
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /devices/add_task/{sn}:
    post:
      tags:
        - devices
      summary: add timer task
      operationId: addTask
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: path
          name: sn
          type: string
          required: true
          description: serial number
        - in: formData
          name: repeat
          type: string
          required: true
          enum: 
            - 0
            - 1
          description: repeatable
        - in: formData
          name: hour
          type: string
          required: true
          description: hour

      responses:
        200:
          description: 'response'
          examples: 
            application/json: {"error":0}
```

### Describe the bug you're encountering
when you first click "try it out", and fill in sn&hour, you can't click execute, nothing happened, there is no error in chrome console either.

you need to click the enum field, select either one, and then execute will work.

### Expected behavior
when you fill the first and the third field, you can submit a request, or there's something prompting me what's wrong.

### Screenshots
![image](https://user-images.githubusercontent.com/1330008/43112695-dc2bc6d4-8f29-11e8-9da1-af6e1c8f28c7.png)

### Additional context or thoughts
I'm not sure if it's related to #4693, but it seems that something wrong with enum field to get a default value.

**Comment by hkosova** [comment]
Confirmed the issue in 3.17.5. The issue not limied to form data and enums, it affects any parameters that have a pre-populated default or example value, e.g.:

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: test

host: httpbin.org

paths:
  /anything/{id}:
    get:
      parameters:
        - in: path
          name: id
          type: string
          required: true
          x-example: 1
        - in: query
          name: foo
          type: string
          default: bar
      responses:
        200:
          description: OK
```
