### ISSUE TITLE
Differentiating between multiple authentication types in the requestInterceptor

### ISSUE THREAD

**Issue by bennyr103** [swagger-api/swagger-ui#4762]
I'm stuck with three different authentication types in our API. I've got a JWT, I've got a BASIC that's not really basic because it doesn't use a user name and password, it takes a single key and enodes it to base64 and pre-pends the request with Basic, and I've got a regular API KEY that has to have "Auth_Key" in the header rather than "Authorization"

I was hoping I could just have the user pop the token in for each and I'd go in and mutate the key using the request interceptor but it turns out there's no way for the request interceptor to know which type of key I'm coming from. Or is there...

If I can't use the requestInterceptor I was looking into using a plugin. If I need to use a plugin would someone be able to give me a simple example how to override the Authorize function?

**Comment by bennyr103** [comment]
I'm using Swagger-Net to get Swagger UI 3.0 injected.

I copied the index.html that Swagger-Net is using and popped in this method

`        function AuthWrapperPlugin() {
            return {
                statePlugins: {
                    auth: {
                        wrapActions: {
                            authorize: (oriAction) => (str) => {
                                if (str.MyTypeOfKey) {
                                    console.log(str.MyTypeOfKey.name);
                                    str.MyTypeOfKey.value = "SOMENEWSTRING";
                                }
                                return oriAction(str);
                            }
                        }
                    }
                }
            }
        }`

And then I added that method to the plugins that are loaded when Swagger UI is loaded. It looks like it's getting triggered after I enter something into the Authorization box and click authorize so this might be the way to do it. Does this override all types of Authentication now? What I mean is, if I add Basic authentication that already works out of the box, will I have to handle it myself or is there a way to call the base method to do it?

**Comment by shockey** [comment]
Hi @bennyr103!

The plugin you have is a great way to do it, but consider renaming `str` to `obj`, since you're actually dealing with an object there - that might be confusing to someone in the future 😄 

>  if I add Basic authentication that already works out of the box, will I have to handle it myself or is there a way to call the base method to do it?

`return oriAction(str)` kicks off the built-in behavior with the data you modified in the plugin code, so you shouldn't have to reimplement anything!

**Comment by bennyr103** [comment]
Thanks, @shockey! I stopped being lazy and tested it out to make sure before I committed my changes.
