### ISSUE TITLE
seems use the wrong request content-type “appliaction/json“ when i post the form data

### ISSUE THREAD

**Issue by startewho** [swagger-api/swagger-ui#4763]
Q&A (please complete the following information)

- OS: [Win10]
- Browser: [chrome]
- Version: [57]
- Method of installation: [dist assets]
- Swagger-UI version: [e.g. 3.17.5]
- Swagger/OpenAPI version: [Swagger 2.0]

Content & configuration

Hereis my swagger.json

     "/api/Auth/LoginByToken": {
          "post": {
            "tags": [
              "Auth"
            ],
            "summary": "使用credential登陆",
            "operationId": "Auth_LoginByToken",
            "parameters": [
              {
                "type": "string",
                "name": "authType",
                "in": "formData",
                "description": "认证类型",
                "x-schema": {
                  "$ref": "#/definitions/UserAuthType"
                },
                "x-nullable": false,
                "enum": [
                  "0",
                  "1",
                  "2",
                  "3",
                  "4",
                  "5"
                ]
              },
              {
                "type": "string",
                "name": "identifier",
                "in": "formData",
                "description": "认证唯一标识",
                "x-nullable": true
              },
              {
                "type": "string",
                "name": "credential",
                "in": "formData",
                "description": "认证标识",
                "x-nullable": true
              }
            ],
            "responses": {
              "200": {
                "x-nullable": true,
                "description": "",
                "schema": {
                  "$ref": "#/definitions/NetResponseOfUser"
                }
              }
            }
          }
        },

Describe the bug you're encountering

I use the latest version 3.17.5

I use the form data to post the data,and the swagger post the data use the content-type:`"application/json"``.

like this:

    curl -X POST "http://localhost:5000/api/Auth/LoginByToken" -H "accept: application/json" -H "Content-Type: application/json" -d "authType=1&identifier=useranmee&credential=asdfdasf"

And when try the version 1.xx .it works as expect.use the content-type "application/x-www-form-urlencoded" to post the data;
here is my swagger's json file:
[swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/2230188/swagger.json.txt)

**Comment by hkosova** [comment]
This happens because your definition specifies
```
  "consumes": [
    "application/json"
  ],
```
Change that to:
```
  "consumes": [
    "application/x-www-form-urlencoded"
  ],
```

**Comment by startewho** [comment]
@hkosova Thanks for your reply.i changed the `consum` to form,it really works ,but most of my requst is json format,so i change the `conusm` to 

```
"consumes": [
     "application/json",
    "application/x-www-form-urlencoded"
  ],
```
it use the json again.
i tried the older version v1. it works as my expect.will there a judgement when i use the form data,or there are  some misunderstandings in my `swagger.json` file

**Comment by hkosova** [comment]
Then leave the global `consumes` set to `application/json` but override `consumes` for that specific operation:
```
 "/api/Auth/LoginByToken": {
      "post": {
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
```
