### ISSUE TITLE
Requests do not use correct enum query parameter

### ISSUE THREAD

**Issue by ctenter-scs** [swagger-api/swagger-ui#4768]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Firefox
 - Version: 61
 - Method of installation: dist assets
 - Swagger-UI version: 3.17.5
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: test
  version: 0.0.0
paths:
  /foo:
    get:
      parameters:
        - in: query
          name: test
          required: true
          schema:
            type: string
            enum:
              - wrongOption
              - correctOption
      responses:
        '200':
          description: OK
```

### Describe the bug you're encountering

If there is an enum query parameter, the user can select the parameter value from a drop down list
in swagger-ui. But the actual request made does not use the selected value, but uses the first element in this drop down list instead.

### To reproduce...

1. Go to 'foo/ Try it out'
2. Click on 'wrongOption'
3. Select 'correctOption'
4. Click on 'Execute'
4. See request url

### Expected behavior
The request url should be

```
/foo?test=correctOption
```

### Actual behavior
The request url is

```
/foo?test=wrongOption
```

**Comment by shockey** [comment]
Hi @ctenter-scs, I'm not able to reproduce this in 3.17.5:

![](http://g.recordit.co/9Ji4SF7Z1r.gif)

Are you certain that you're running the latest version?

**Comment by ctenter-scs** [comment]
Hi shockey, thanks. I've updated to latest version (3.17.6) and the issue has been fixed.
