### ISSUE TITLE
Add a button to select (and/or copy) all content of response

### ISSUE THREAD

**Issue by ilnurshax** [swagger-api/swagger-ui#4771]
Hi! Swagger it is very cool and good solution for design and to work with API. And I'll be very happy if the one feature can be released.

### Is your feature request related to a problem?
I'm always frustrated when I debug the Laravel applications and the calling of debug returns the big pack of text. So it's very complicated to select the all response text and copy it to paste into another editor. 

Another situation is when the one developer asks from me the example of a response. So I need to very accurately select the response content (it may be json, maybe not). And it takes a long time because it is very easy to skip one symbol...

It is may be very cool to add a simple one button like "Select all response content".

### Describe the solution you'd like
Maybe add the very simple button to each response content like a "Select all response content"?

Thanks to all!

**Comment by shockey** [comment]
I think a click-to-select-all functionality (like the one you can observe in the cURL display) would be great here.

**Comment by hkosova** [comment]
@ilnurshax Swagger UI 3.27.0 and later has the "Copy" button in live responses (added in PR https://github.com/swagger-api/swagger-ui/pull/5278). Does this suit your needs?

**Comment by ilnurshax** [comment]
@hkosova Yes, actually. Thanks! 😀
