### ISSUE TITLE
Documentation on @ExternalDocumentation

### ISSUE THREAD

**Issue by smitendu** [swagger-api/swagger-ui#4774]
Hi,

I have been referring to the online documentation for Swagger UI for ExternalDocumentation annotation. The example that is provided for this annotation is faulty and is copy pasted from example for Hidden annotation. Please check the example provided at : https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#externaldocumentation

Please fix the documentation with relevant example for ExternalDocumentation annotation.

Thanks!

**Comment by shockey** [comment]
@smitendu, it sounds like you're describing a swagger-core issue - how does this relate to Swagger UI?
