### ISSUE TITLE
requestInterceptor that returns promise breaks curlify output

### ISSUE THREAD

**Issue by Falx** [swagger-api/swagger-ui#4778]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 67.0.3396.99
 - Method of installation: dist assets
 - Swagger-UI version: 3.17.6
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
```

Swagger-UI configuration options:
```js
SwaggerUI({
          url: "https://api.myjson.com/bins/1h15yo",
          dom_id: '#swagger-ui',
          deepLinking: true,
          presets: [
            SwaggerUIBundle.presets.apis,
          ],
          plugins: [
            SwaggerUIBundle.plugins.DownloadUrl,
          ],
          requestInterceptor: req => {
            //return req;
            return new Promise((resolve, reject) => resolve(req));
          }
})
```

### Describe the bug you're encountering
When using a `requestInterceptor` that returns a promise (that resolves to the request), instead of the pure request, the curl statement generated with curlify results in `curl -X "undefined"`. Although the modified request is being used to send the http request.

### To reproduce...

1. See this jsfiddle: https://jsfiddle.net/falxfalx/6xy24zL9/32/
2. Press play
3. Try it out on GET /pets 
4. Execute
5. Observe generated curl request
6. Now comment requestInterceptor return statement and uncomment the `return req;` line
7. Repeat step 2 through 5 (this is expected behaviour)

### Expected behavior
The displayed curl request should not be undefined.

### Additional context or thoughts
Since I saw that curlify.js has a curl function that is to be called with the request as argument, I suspect that when returning a promise, the curlify call becomes: `curl(promise)` while it should be something like:
```js
const req = await promise;
curl(req);
```

**Comment by Falx** [comment]
Can anyone please confirm this? If not, then I will have to fix this in more hacky way, by rewriting parts of the DOM or something like that..

**Comment by shockey** [comment]
@Falx, bug confirmed - looks to me like we need to await the mutated request in the wrapper we pass to Swagger Client:

https://github.com/swagger-api/swagger-ui/blob/c9e8a67579abcf2b87224b0f058c02fa63561fba/src/core/plugins/spec/actions.js#L407

**Comment by Falx** [comment]
Thank you for confirming this @shockey . Right now I worked around it by showing the unmutated request in the curl section and then adding my request mutations (the same ones I do in requestInterceptor) to the request property of the Curl component, with a wrapComponent plugin.

It would of course be nicer to use the built-in features once this is fixed.

**Comment by arutun** [comment]
Any update on fixing this? It's biting me too, if I set `requestInterceptor` the curl request is hosed.

**Comment by shockey** [comment]
It’s in our queue to be worked on, no promises on a fix ETA. 

If anyone would like to make a PR for this, I’d be happy to go into more detail on what needs to be done.

**Comment by copitz** [comment]
If the request url isn't changed by requestInterceptor asynchronously this issue can be worked around like this:

```javascript
SwaggerUI({
          // ...
          requestInterceptor: req => {
            //return req;
            const promise = new Promise((resolve, reject) => resolve(req));
            promise.url = req.url
            return promise
          }
})
```

**Comment by ruhkopf** [comment]
Adding `showMutatedRequest: false` to the config seems to work for me. Without this option I'm seeing the same issue with the curl output.

**Comment by larsmaultsby** [comment]
> It’s in our queue to be worked on, no promises on a fix ETA.
> 
> If anyone would like to make a PR for this, I’d be happy to go into more detail on what needs to be done.

Could you outline where all the code needs to change to make this happen? I'm working on a project where this would be beneficial. Right now I've got a fork that updates the code to work for ONLY promise based requestIntercept functions.

**Comment by Vishakh-vcc** [comment]
@tim-lai @Falx @shockey ...how to fix this issue. even I am facing the same, my request interceptor is using a proxy which is being shown in the curl rather than the original request , how to show the original request in the curl command

**Comment by Vishakh-vcc** [comment]
> Adding `showMutatedRequest: false` to the config seems to work for me. Without this option I'm seeing the same issue with the curl output.

how to fix this issue. even I am facing the same, my request interceptor is using a proxy which is being shown in the curl rather than the original request , how to show the original request in the curl command...i tried using 'showMutatedRequest' but didnt work

**Comment by blackmad-cradle** [comment]
For the next person who runs into this - the issue is that the Request type here is not the javascript standard Request, it's actually just a raw object. So you can't return a new Request(), you need to return a new POJO (plain old javascript object)
