### ISSUE TITLE
Incorrect validation for int64

### ISSUE THREAD

**Issue by maciejgroenke** [swagger-api/swagger-ui#4779]
Hi
I use swagger-ui with swagger-ui-standalone-preset
My swagger.json file describes parameter as "type":"integer","format":"int64".
However, any value provided to that field is shown as invalid, whether it's int, string, empty field...
I don't get any errors in console, only warning  "Could not find component JsonSchema_integer_int64"

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
