### ISSUE TITLE
Incorrect validation for int64

### ISSUE THREAD

**Issue by maciejgroenke** [swagger-api/swagger-ui#4786]
@shockey 
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 67.0.3396.99
 - Method of installation: npm
 - Swagger-UI version: 3.17.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### Content & configuration
My package.json file
```json
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-scripts": "1.1.4",
    "swagger-ui": "^3.17.0",
    "swagger-ui-dist": "^3.17.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

Example Swagger/OpenAPI definition:
https://petstore.swagger.io

Swagger-UI configuration options:
```js
import SwaggerUI from 'swagger-ui';
import SwaggerUIStandalonePreset from 'swagger-ui/dist/swagger-ui-standalone-preset';

SwaggerUI({
    urls: [{
        url: 'https://petstore.swagger.io/v2/swagger.json',
        name: 'Test'
    }],
    dom_id: '#root',
    presets: [
        SwaggerUI.presets.apis,
        SwaggerUIStandalonePreset
    ],
    plugins: [
        SwaggerUI.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
});
```

### Describe the bug you're encountering
Any value that is inputted into int64 fields are validated as incorrect, whether they're int, string or other values

### To reproduce...

1. Go to 'Find pet by id'
2. Click on 'Try it out'
3. Input correct int value into petId, like 123
4. See validation error - input field is cleared

### Expected behavior
Id should be correct, and the input field shouldn't be cleared

### Screenshots
https://media.giphy.com/media/x4AAkm9bRV9MAlTTQl/giphy.gif

### Additional context or thoughts
I've seen a console warning  "Could not find component JsonSchema_integer_int64" - maybe it's related

**Comment by shockey** [comment]
Thanks for refiling this, @maciejgroenke 😄 

I see you're on 3.17.0. Can you try this with 3.17.6 (the latest) and let me know if it's still happening on your end?

**Comment by maciejgroenke** [comment]
Ok, I found it's a duplicate of https://github.com/swagger-api/swagger-ui/issues/4745, closing
