### ISSUE TITLE
Resolver error - Cannot read property '0' of undefined (it's is back)

### ISSUE THREAD

**Issue by ofavre** [swagger-api/swagger-ui#4787]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Chrome
 - Version: 67.0.3396.99
 - Method of installation: https://editor.swagger.io
 - Swagger-UI version: Probably the latest, 3.17.6 as of this writing
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'
info:
  title: Test
  version: '1.0'
basePath: /
schemes:
  - https
paths:
  /get:
    get:
      summary: Gets things
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/A'
definitions:
  D:
    type: object
    properties:
      z:
        type: string
        description: Some Z string
  C:
    type: object
    properties:
      d:
        title: D
        allOf:
          - description: Some D
          - $ref: '#/definitions/D'
  B:
    type: object
    properties:
      c:
        title: C
        allOf:
          - description: Some C
          - $ref: '#/definitions/C'
  A:
    type: object
    properties:
      b:
        title: B
        allOf:
          - $ref: '#/definitions/B'
          - description: Some B
```

Swagger-UI configuration options:
No idea, I'm testing on editor.swagger.io.

### Describe the bug you're encountering

In essence, #3366 is back, or had only been partially fixed.

### To reproduce...

1. Go to https://editor.swagger.io/
2. Enter the Swagger above
3. Expand anything you will until you reach the definition of A under the models.
   Check that you see no error (in your console or the top of the document.
3. Now expand `A` in the models list
4. Scroll top and you'll see 4 time the error: `Resolver error - Cannot read property '0' of undefined`.

### Expected behavior

The visual output is fine in this example, however there are javascript errors emitted (and the online editor shows them).

### Screenshots

![image](https://user-images.githubusercontent.com/95129/43641478-2776feae-9724-11e8-8e3f-45ebf7c0b756.png)

### Additional context or thoughts

I found this while investigating why some other properties do not show their description, so these JavaScript errors may (or may not) be actually hurting more than it seems in this contrived example.

As suggested in #3366, if you move the A entry under definitions above B (right above or up higher) the problem disappears.
If you remove one level of nesting (remove A and make the end-point reference B directly), you get no issue.
However putting the definitions above the paths changes nothing.

**Comment by shockey** [comment]
This issue was moved to swagger-api/swagger-js#1362
