### ISSUE TITLE
Typo in the latest release tag

### ISSUE THREAD

**Issue by PeterDaveHello** [swagger-api/swagger-ui#4793]
The link in [README.md](https://github.com/swagger-api/swagger-ui/tree/v/3.18.0#compatibility) - [v3.18.0](https://github.com/swagger-api/swagger-ui/tree/v3.18.0) doesn't work, instead, the latest tag is [v/3.18.0](https://github.com/swagger-api/swagger-ui/tree/v/3.18.0), seems to be typo?

**Comment by PeterDaveHello** [comment]
@shockey would you like to take a look? Thanks.

**Comment by shockey** [comment]
@PeterDaveHello, fixed! 

We've been automating more of our release process, looks like we aren't parsing the version branch into a tag correctly 😄

**Comment by PeterDaveHello** [comment]
Thanks!
