### ISSUE TITLE
Is there any configuration parameter to hide Try it out buton

### ISSUE THREAD

**Issue by tnpradeep** [swagger-api/swagger-ui#4797]
Hi All,

Is there any configuration parameter I can pass while initializing SwaggerUIBundle to hide Try it out button ?

Thanks
Pradeep

**Comment by hkosova** [comment]
```
supportedSubmitMethods: []
```
disables "try it out" for all operations.

Here is the full list of configuration parameters:
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

**Comment by shockey** [comment]
Closing as this appears solved - @tnpradeep, feel free to reply if you have more concerns 😄
