### ISSUE TITLE
Exclude model from Models list

### ISSUE THREAD

**Issue by m-demydiuk** [swagger-api/swagger-ui#4803]
### Content & configuration

Swagger/OpenAPI definition:
I use `Swashbuckle.AspNetCore` v3.0.0 / `Swagger-Ui` v3.17.1

### Is your feature request related to a problem?
I need to exlude (i.e. do not show) model in `Models` list. As our partners do not use AspNet.Core, they don't need to know anything about `IFormFile` interface which is specific to AspNet.Core.

### Describe the solution you'd like
It will be very useful for us, to decorate the method parameter with some attribute to exclude `IFormFile` from rendering.
```
public async Task<IActionResult> Post(**[IgnoreModel]**IFormFile document)
```

### Additional context
![image](https://user-images.githubusercontent.com/2910327/43833410-4b214d08-9b13-11e8-8d78-1d4cd14c344a.png)

**Comment by shockey** [comment]
It seems to me that a definition-level `x-renderable: false` field would be a good way to solve this.

Would that work for you, @m-demydiuk?

**Comment by m-demydiuk** [comment]
Resolved here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/846
