### ISSUE TITLE
I'm having trouble implementing swagger-ui in remote server. Throwing can't read file error.

### ISSUE THREAD

**Issue by rbipin** [swagger-api/swagger-ui#4808]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome, Safari, IE
 - Version: [e.g. 22]
 - Method of installation: dist
 - Swagger-UI version:3.0.21
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
window.onload = function() {

  // Build a system
    const ui = SwaggerUIBundle({
        urls: [
            {
                url: "../OASDoc/v1_apidoc.json",
                name:"Version 1.0.0"
            }
              ],
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
```

```
?yourQueryStringConfig
```

### Screenshots

https://i.stack.imgur.com/5hYMz.png

### How can we help?
The swagger-ui is throwing **_can't read the file error_** from the ui. But it is working from local IIS.
The details of the issue along with the sample code is also given below in my stackoverflow questions
[https://stackoverflow.com/questions/51778578/swagger-ui-is-unable-to-load-the-json-specification-file-in-serve](https://stackoverflow.com/questions/51778578/swagger-ui-is-unable-to-load-the-json-specification-file-in-server )

**Comment by shockey** [comment]
Hey @rbipin, can you give me the URL in your address bar where you're accessing Swagger UI?

**Comment by shockey** [comment]
no worries @rbipin, I understand.

Can you see the Swagger document if you go to `http://xxxx.xxxx.com/retailproject//OASDoc/v1_apidoc.json`? That's where Swagger UI is looking for your document, It's possible that your server is configured incorrectly.

If that doesn't illuminate the problem, try opening the Network tab of your browser's dev tools, and take a look at the request that Swagger UI is making to fetch `v1_apidoc.json`.

**Comment by rbipin** [comment]
@shockey : yes, I tried to access the json file (http://xxxx.xxxx.com/retailproject/OASDoc/v1_apidoc.json)
But i'm not able to access the file

**Comment by shockey** [comment]
@rbipin, that would be a problem with your server then - if your server isn't serving up your Swagger document at the right URL (which, based on the config and URL you shared, is the URL I mentioned above), Swagger UI won't be able to do anything 😄

**Comment by rbipin** [comment]
@shockey  thank you for helping me! Your directions were very helpful. I figured it out now and I have fixed it. The issue was the server was not serving static JSON file by default. I added the _mime type mapping_ to me web.config file and it worked.

` <system.webServer>
    <staticContent>
      <mimeMap fileExtension=".json" mimeType="application/json"/>
    </staticContent>
  </system.webServer>`
