### ISSUE TITLE
How to set uniqueItems=true

### ISSUE THREAD

**Issue by bugged84** [swagger-api/swagger-ui#4815]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chroome
 - Swagger-UI version: 3.0.0

### Screenshots
![image](https://user-images.githubusercontent.com/23638686/44240236-c94eb880-a182-11e8-97f1-46690946ec29.png)

### How can we help?
What should I configure in my ASP.NET Core application to control the value of the uniqueItems field shown in the UI screenshot above? I'm using the Swashbuckle.AspNetCore.SwaggerUI NuGet package.

**Comment by bugged84** [comment]
I had a crazy idea to change my response type from IEnumerable<string> to ISet<string> and it worked. The uniqueItems field now has a value of 'true'.

**Comment by shockey** [comment]
Hey @bugged84, I'm closing this out since it isn't a Swagger UI question - you'd have more luck asking this over at Swashbuckle.

Good luck, and thanks for using Swagger! 😄
