### ISSUE TITLE
class HostNameProvider bug?

### ISSUE THREAD

**Issue by p555iii** [swagger-api/swagger-ui#4816]
- OS: [Windows]
 - Browser: [ chrome]
 - Swagger version: [e.g. Swagger 2.9.2,]

When I used springcloudgateway to aggregate the swagger2 document, I found the quoteIfNeeded method under the org.springframework.cloud.gateway.filter.headers.ForwardedHeadersFilter class, which changed the request path (eg localhost:8802) to "localhost:8802" And put "localhost:8802" into the Forward in the request headers. At first I hang the question under the spring-cloud-gateway. The official replies to me that they support IPV6 and add quotation marks before and after the host, which leads to springfox. .documentation.swagger2.web.HostNameProvider's componentsFrom method class resolves host,
String[] hosts = StringUtils.commaDelimitedListToStringArray(host);
            String hostToUse = hosts[0];
            If (hostToUse.contains(":")) {
                String[] hostAndPort = StringUtils.split(hostToUse, ":");
                Builder.host(hostAndPort[0]);
                Builder.port(Integer.parseInt(hostAndPort[1]));
Integer.parseInt(hostAndPort[1]) is equivalent to parseInt("8802""), which throws an error that cannot be type converted.
![d66b0f36-c8e0-4874-9641-a046ff5dfe4a](https://user-images.githubusercontent.com/28823571/44250729-251f4d00-a228-11e8-9760-8b5489d895fb.png)

**Comment by shockey** [comment]
Hey @p555iii, this doesn't appear to be related to Swagger UI - did you mean to open this in the Springfox repository?

Closing for now - if there's anything else, or I misunderstood something, just reply!

**Comment by p555iii** [comment]
Maybe my problem is wrong, but is there a problem with parseInt directly here? I have already encountered this problem and hope that swagger can handle this problem.

**Comment by shockey** [comment]
@p555iii, Swagger UI is a JavaScript project, so we can't help with any (looks like) Java problems 😕
