### ISSUE TITLE
oneOf, anyOf not works

### ISSUE THREAD

**Issue by kalinick** [swagger-api/swagger-ui#4819]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: [chrome, safari]
 - Method of installation: dist assets
 - Swagger-UI version: 3.18.1
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### Content & configuration
oneOf, anyOf not works

Example Swagger/OpenAPI definition:
```yaml
  /v2/teams/{id}:
    delete:
      tags:
      - Teams
      summary: Delete a team
      parameters:
      - in: path
        name: id
        required: true
        type: string
        allowEmptyValue: false
      responses:
        204:
    get:
      tags:
      - Teams
      summary: Get a team by id
      parameters:
      - in: path
        name: id
        required: true
        type: string
        allowEmptyValue: false
      responses:
        200:
          schema:
            oneOf:
              - $ref: "#/definitions/Team1"
              - $ref: "#/definitions/Team2"
```

### Expected behavior
oneOf, anyOf works

### Screenshots

![image](https://user-images.githubusercontent.com/1422388/44264196-5731ae80-a22a-11e8-8367-4849bcc14ea8.png)

**Comment by hkosova** [comment]
Thanks for the report! This issue is already being tracked in #3803.

> Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

Just FYI, `oneOf` and `anyOf` are an OpenAPI 3.0 feature and are not supported in Swagger 2.0.

**Comment by kalinick** [comment]
If, I'm trying to set swagger version > 2.0 it shows me this error 
![image](https://user-images.githubusercontent.com/1422388/44273947-886da700-a249-11e8-93b2-f1bba15c97df.png)

**Comment by hkosova** [comment]
It should be `openapi: 3.0.0` not `swagger: '3.0'`

**Comment by hkosova** [comment]
@kalinick `openapi: '3.0'` is not valid, it should be `openapi: 3.0.0` with the three-digit version number - as explained in the help text on your image. And remove `swagger: '2.0'`.

Check out the [OpenAPI 3.0 syntax guide](https://swagger.io/docs/specification/basic-structure/).

**Comment by kalinick** [comment]
set in general.yaml
openapi: '3.0.0'

set path:
  /v2/teams/{id}/full:
    get:
      tags:
      - Teams
      summary: Get a team by id
      responses:
        '200':
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/FullTeam"

it's not works 
![image](https://user-images.githubusercontent.com/1422388/44327600-c0eacc00-a467-11e8-9215-3a544dc4c135.png)

but works 

  /v2/teams/{id}/full:
    get:
      tags:
      - Teams
      summary: Get a team by id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FullTeam"

![image](https://user-images.githubusercontent.com/1422388/44327652-ebd52000-a467-11e8-8c92-bbb725f509a3.png)

**Comment by shockey** [comment]
@kalinick, as mentioned above, `oneOf` is not currently supported in Swagger UI - you can follow 
https://github.com/swagger-api/swagger-ui/issues/3803 for updates on that feature 😄

**Comment by kalinick** [comment]
Thanks for your support, will be looking forward to the release of this feature :)

**Comment by shockey** [comment]
Glad we could help!

Closing this out in favor of #3803.
