### ISSUE TITLE
Multiple files to SWAGGER_JSON

### ISSUE THREAD

**Issue by serafss2** [swagger-api/swagger-ui#4820]
I would like to know if there's a way to input multiple files to the environment variable `SWAGGER_JSON` variable in Docker that will generate something like a drop list in the UI or something.

For now I have something similar to this on my Dockerfile:

```
ENV SWAGGER_JSON "/docs/doc1.yaml"
```

And would like to know if there's a structure that maybe looks like:

```
ENV SWAGGER_JSON "['/docs/doc1.yaml','/docs/doc2.yaml']"
```

**Comment by shockey** [comment]
This isn't currently possible, but we can add it 😄

**Comment by shockey** [comment]
Once #4965 is merged, you can do this with the following..

Given a directory `foo` with `one.yaml` and `two.yaml` inside of it:

```sh
docker run -e 
\ URLS="[ { name: \"one\", url: \"/foo/one.yaml\"}, { name: \"two\", url: \"/foo/two.yaml\" } ]"
\ -v /Users/kyle/Code/ui/bar:/usr/share/nginx/html/foo -p 8080:8080 swagger-api/swagger-ui
```

**Comment by manjunathrvce** [comment]
How can the same environment variable be set in the docker compose. when I tried it is giving  services.swaggerapp.environment contains an invalid type, it should be an object, or an array

**Comment by shockey** [comment]
@manjunathrvce this issue is resolved, please open a new one!
