### ISSUE TITLE
example of kerberos auth

### ISSUE THREAD

**Issue by keith6014** [swagger-api/swagger-ui#4824]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: OpenAPI 3.0

Looking for an example of schema with kerberos authentication.

**Comment by keith6014** [comment]
anyone?

**Comment by shockey** [comment]
Hi @keith6014, I asked around and it appears that it's currently not possible to describe a Kerberos auth flow in OpenAPI 3.

You can follow the developments on this in the OpenAPI repository: https://github.com/zalando/connexion/issues/649

Closing!
