### ISSUE TITLE
Configuration file downloaded 2 times when using configUrl

### ISSUE THREAD

**Issue by anfle** [swagger-api/swagger-ui#4825]
### Q&A (please complete the following information)
 - Method of installation: npm
 - Swagger-UI version: 3.18.x

### Content & configuration

Swagger-UI configuration options:
```js
import SwaggerUI from 'swagger-ui'
import SwaggerUIStandalonePreset from 'swagger-ui/dist/swagger-ui-standalone-preset'

window.onload = function() {
    const ui = SwaggerUI({
        configUrl: '/api/swagger-config.json',
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUI.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUI.plugins.DownloadUrl
        ],
        layout: 'StandaloneLayout',
        filter: true,
        requestInterceptor: function(request) {
            // handle CSRF
            return request;
        },
        responseInterceptor: function (response) {
          // handle json prefix
          return response
        }
    })
})

window.ui = ui
```
And my swagger-config.json file:
```
{
  "url": "/swagger-portal.json",
  "filter": true,
  "deepLinking": true,
  "validatorUrl": null
}
```

### How can we help?
My swagger config file (define in configUrl parameter) is downloaded two times (illustrated in the screenshot below).
From the code [src/core/index.js](https://github.com/swagger-api/swagger-ui/blob/master/src/core/index.js#L173-L182) and [src/core/plugins/configs/spec-actions.js](https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/configs/spec-actions.js#L10-L12) it's normal.
However I think it might be more efficient to check if the requests parameter exists before calling the _getConfigByUrl_ method in the if condition to avoid double downloading.
Maybe I missed something?

### Screenshots
![swagger](https://user-images.githubusercontent.com/5066422/44451488-31265880-a5f4-11e8-9f28-3b03d1258ca3.png)

**Comment by shockey** [comment]
Hmm, yeah, this does seem like it's duplicated. Good catch!

**Comment by bnasslahsen** [comment]
Hi, 

 Is there any workaround for this issue when we use configUrl ?

**Comment by lrozenblyum** [comment]
Any ideas for a workaround? onComplete is also called twice which is not nice

**Comment by mariem-89** [comment]
@shockey, 

 Is there any workaround for this bug?
 It's really annoying to have the swagger-ui loaded twice. 

 Thank you guys for your help.
