### ISSUE TITLE
Missing description on $ref

### ISSUE THREAD

**Issue by RobertPaasche** [swagger-api/swagger-ui#4829]
### Q&A (please complete the following information)
 - OS: macOS, Windows, Linux
 - Browser: Any
 - Version: any
 - Swagger-UI version:  3.18.1]
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```json
"PersonDto": {
			"type": "object",
			"properties": {
				"salutation": {
					"description": "The selected salutation with all available translations.",
					"$ref": "#/definitions/LabelSetDto"
				},
				"position": {
					"description": "The selected position with all available translations.",
					"$ref": "#/definitions/LabelSetDto"
				}
			},
			"description": "Person data for a specific charset."
		}
```
```yaml
  PersonDto:
    type: "object"
    properties:
      salutation:
        description: "The selected salutation with all available translations."
        $ref: "#/definitions/LabelSetDto"
      position:
        description: "The selected position with all available translations.",
        $ref: "#/definitions/LabelSetDto"
```

### Describe the bug you're encountering
The description provided for salutation is not rendered at the response body.
![image](https://user-images.githubusercontent.com/6502079/44525958-e0415d80-a6e2-11e8-85b7-fff55cf18383.png)

**Comment by hkosova** [comment]
Any keywords alongside `$ref` are ignored - that's how `$ref` works. 

You need to wrap the `$ref` into `allOf` in order for the `description` to have effect:
```yaml
  PersonDto:
    type: "object"
    properties:
      salutation:
        description: "The selected salutation with all available translations."
        allOf:
          - $ref: "#/definitions/LabelSetDto"
      position:
        description: "The selected position with all available translations.",
        allOf:
          - $ref: "#/definitions/LabelSetDto"
```

**Comment by RobertPaasche** [comment]
Ok I had to create empty sub classes like the samples of https://github.com/swagger-api/swagger-core/issues/1549 .
