### ISSUE TITLE
multiple file upload

### ISSUE THREAD

**Issue by xeptore** [swagger-api/swagger-ui#4835]
### Q&A (please complete the following information)
 - OS: ubuntu 18.04
 - Browser: chrome
 - Version: 65
 - Method of installation: npm
 - Swagger-UI version: 3.18.1
 - Swagger/OpenAPI version: openapi3

### Content & configuration
i'm using the same openapi spec for uploading multiple files as described [here](https://swagger.io/docs/specification/describing-request-body/file-upload/#multiple).
![image](https://user-images.githubusercontent.com/29199390/44661695-a93fb480-aa20-11e8-8671-f9882b3b86f3.png)
but it doesn't work and instead of showing the content of the files, it sends __[object File]s__ comma separated items.
![image](https://user-images.githubusercontent.com/29199390/44661888-5286aa80-aa21-11e8-848e-d35c71d019a9.png)

Example Swagger/OpenAPI definition:
here is the complete `requestBody` part of the yaml file
```yaml
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
```

Swagger-UI configuration options:
```js
SwaggerUI({
          url: "openapi.yml",
          dom_id: '#swagger-ui',
          deepLinking: true,
          presets: [
              SwaggerUIBundle.presets.apis,
              SwaggerUIStandalonePreset
          ],
          plugins: [
              SwaggerUIBundle.plugins.DownloadUrl
          ],
          layout: "StandaloneLayout"
})
```

**Comment by hkosova** [comment]
Thanks for the report! This issue is already being tracked in #4600.

**Comment by shockey** [comment]
Closing as a duplicate 😄
