### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by johndunlap** [swagger-api/swagger-ui#484]
My API produces two content types, JSON and XML. When I request JSON from one of my endpoints through swagger UI it correctly displays the JSON with syntax highlighting. However, if I then change the drop down selection and request XML the response comes back and gets indented properly but it is not syntax highlighted. If I completely refresh the page and then request XML first, followed by JSON, then the behavior is reversed and I will get highlighted XML and not highlighted JSON. I managed to fix it in my system by directly hacking the javascript. It looks like there's a CSS class which gets set on the .response-body element(xml or json) which gets set when the first request is made against the endpoint. The proglem is that this class is never toggled when a different content type is requested.

**Comment by fehguy** [comment]
the root issue is that once you hit `try it out`, the formatting will not apply to new requests.
