### ISSUE TITLE
[Feature] Partial usage of external resource already referenced in a schema

### ISSUE THREAD

**Issue by boesing** [swagger-api/swagger-ui#4848]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
openapi: 3.0.0
info:
  description: 
  version: 1.0.0
  title: Whatever
  contact:
    email: max@boesing.email
components:
  schemas:
    PartOfMySharedResponse:
      type: "object"
      properties:
        foo:
          #$ref: '#/components/templates/SharedResponse/properties/foo' # <- wont work
          $ref: '//example.com/shared.yaml#components/schemas/MyResponseDefinitionWithFooAndBarProperties/properties/foo' # <- works
        bar:
          #$ref: '#/components/templates/SharedResponse/properties/bar' # <- wont work
          $ref: '//example.com/shared.yaml#components/schemas/MyResponseDefinitionWithFooAndBarProperties/properties/bar' # <- works
  templates:
    SharedResponse:
      $ref: '//example.com/shared.yaml#components/schemas/MyResponseDefinitionWithFooAndBarProperties'
 ```

### Is your feature request related to a problem?
I guess not, but I would assume, that all references are automatically executed recursively. So, if I want to reference to a property of a specific object and that specific object is a reference itself, I would assume that this reference is prefetched first and then provides the full object, where the first reference can take the parts of.

### Describe the solution you'd like
I would like to access references recursively. So if one reference accesses another, it should be possible to realize, that there is another ref and resolve it before accessing the upcoming definition (properties/bar)

### Describe alternatives you've considered
Actually I'm pointing to the full external resource (which works). But it could be annoying, if that resource will change in near future and then one have to completely change all usages in the yaml definition instead of just changing the templates reference.

**Comment by shockey** [comment]
Hey @boesing!

This isn't currently supported, but it's theoretically possible - JSON Pointer/Refs appears to allow it. I'm going to move this ticket to Swagger Client so we can track it as a feature for the resolver.

**Comment by shockey** [comment]
This issue was moved to swagger-api/swagger-js#1384
