### ISSUE TITLE
jsonEditor feature

### ISSUE THREAD

**Issue by SSCodeChamp** [swagger-api/swagger-ui#4849]
Team -

I am trying to enable JSON editor for request body JSON in my API. But it does not work by adding jsonEditor to true in index.html.Is there any other way of doing it ? I am using latest swagger UI.

// Build a system
              const ui = SwaggerUIBundle({
                  url: "http://localhost:54685/swagger.json",
                  dom_id: '#swagger-ui',
                  deepLinking: true,
                  jsonEditor: true,
                  presets: [
                      SwaggerUIBundle.presets.apis,
                      SwaggerUIStandalonePreset
                  ],
                  plugins: [
                      SwaggerUIBundle.plugins.DownloadUrl
                  ],
                  layout: "StandaloneLayout"

              })

              window.ui = ui
          }

**Comment by hkosova** [comment]
JSON form editor is not supported in Swagger UI 3.x. There's an existing feature request #2771.

**Comment by SSCodeChamp** [comment]
Ok. Thanks. Closing this as There's an existing feature request #2771  for this.
