### ISSUE TITLE
Incorrect Accept header sent from Swagger-UI

### ISSUE THREAD

**Issue by steine-locus** [swagger-api/swagger-ui#485]
I've got a java webapp where I'm doing version control via content negotiation. My method looks like:

    @POST
    @Consumes("application/vnd.mycompany.foo.v1+json")
    @Produces("application/vnd.mycompany.bar.v1+json")
    @ApiOperation(...)
    @ApiResponses(...)
    public Response createBar(
            @ApiParam(required = true) final Foo foo) {
        ..
    }

On the UI, for Parameter Content Type, I select "vnd.mycompany.foo.v1+json". When I [Try it out!], I get back a 406 Not Acceptable. These are the headers that go out:

Accept:       application/json
Content-Type: application/vnd.mycompany.foo.v1+json; charset=UTF-8

So it's not surprising that I'm getting a 406, because my response type doesn't match the accept header. I asked on the google group (https://groups.google.com/forum/#!topic/swagger-swaggersocket/NCQ3ZP7RV40), and was told I should report this as a bug.

I just grabbed the latest build from Download ZIP on the homepage and still see the issue.

**Comment by okigan** [comment]
Seems the issue is back in : 
// swagger-ui.js
// version 2.1.0-alpha.7

**Comment by webron** [comment]
@okigan - can you give more information about your use case? in my test it seems to work fine.

**Comment by okigan** [comment]
Ok found the issue: 

    @Produces({MediaType.APPLICATION_JSON, PROJECT_MODEL_JSON})
    @ApiOperation(value = "Query projects")
    public Iterable<Long> query

But this works: 
    @Produces({MediaType.APPLICATION_JSON, PROJECT_MODEL_JSON})
    @ApiOperation(value = "Query projects", response = Long.class, responseContainer = "List")
    public Iterable<Long> query


Would be nice if UI would show response model as list of Longs: 
![screen shot 2015-01-14 at 9 09 11 am](https://cloud.githubusercontent.com/assets/478302/5743284/38e83a78-9bcd-11e4-9b1b-c6484c43d8a9.png)


And just occurred to me, the model is different based on accept type, is that possible to specify that ?

**Comment by webron** [comment]
That's not really related to the `Accept` header.

As for describing different models per content-type, it is currently not possible. You can follow this issue - https://github.com/swagger-api/swagger-spec/issues/146.

**Comment by ivan-golubev** [comment]
I bumped into the same problem. Swagger-ui keeps setting the Accept:application/json.
Simple POST request with consumes: application/x-www-form-urlencoded and produces: "application/xml; charset=UTF-8".
I have tried swagger-ui-2.0.19, 2.1.0-M2.
What am I doing wrong? Is there any place in code where I can override this?

**Comment by webron** [comment]
@ivan-golubev - can you share your Swagger definition?

**Comment by ivan-golubev** [comment]
OK, here is the swagger.json :
```javascript
{
  "swagger": "2.0",
  "info": {
    "description": "This is a sample documentation.",
    "version": "1.0.0",
    "title": "documentation",
    "contact": {
      "email": "apiteam@wordnik.com"
    }
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "paths": {
    "/users": {
      "post": {
        "summary": "Create profile",
        "description": "Authenticate user with either Facebook id and create a new profile for him.",
        "operationId": "createProfile",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/xml; charset=UTF-8"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "auth_method",
            "description": "facebook",
            "default": "facebook",
            "required": true,
            "type": "string"
          },
          {
            "in": "formData",
            "name": "application",
            "description": "none",
            "required": true,
            "default": "facebook",
            "type": "string"
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
@ivan-golubev - there indeed seems to be an issue there. Can you please open a new ticket with the details?

**Comment by teodora-yankova** [comment]
Hi, has the issue with Accept always being set to application/json been resolved? Thanks!

**Comment by ivan-golubev** [comment]
It hasn't been resolved, but there's a walkaround available - look through
the forums here.

**Comment by to-kra** [comment]
I having same problem

**Comment by fehguy** [comment]
Verified working in master

**Comment by to-kra** [comment]
Hi Fethguy, is it new SWAGGER-UI ? and aslo my DELETE problem mentioned above working ? thx

**Comment by fehguy** [comment]
Yes I have just confirmed.  Please try and post back.

**Comment by salluspeaks** [comment]
Actually the workaround for this to include the response value like -
@ApiOperation(value = "Query projects", **response = Long.class**, responseContainer = "List")
then the swagger will display the Response content type

**Comment by pruthvigh** [comment]
I am having this same issue and have been trying to resolve it from last 24 hours. Even though I specifically mentioned "consumes:["application/xml"]" still the requests go as "Accept: Application/json". Our API endpoint returns an XML response back and because of this I am getting a 0 response code and no content - response body. Our configuration is Swagger 2.0
