### ISSUE TITLE
SwaggerUI 3.18.2 contains in dist folder exactly the same files as it is in version 3.18.1

### ISSUE THREAD

**Issue by piotrzarzycki21** [swagger-api/swagger-ui#4853]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: 68.0.3440.106 
 - Method of installation: Download from GitHub
 - Swagger-UI version: 3.18.2
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
I downloaded newest release by using "Source code" option on the GitHub. Since I'm interested only "dist" I deployed it on my http server. Checked version and it's pointing to 3.18.1 instead 3.18.2.

### To reproduce...
I checked version in Chrome console using `JSON.stringify(versions)`

**Comment by piotrzarzycki21** [comment]
@shockey I have cleared my cache and I'm still seeing 3.18.1. I have even used other browser which I don't use as my default Edge and it's the same.

`file:///Users/kyle/Code/ui/dist/index.html` <- This one which you are showing me is it dist downloaded from that [link](https://github.com/swagger-api/swagger-ui/archive/v3.18.2.zip)?

**Comment by shockey** [comment]
Aha - looks like our `v3.18.2` tag was looking at an older commit.

I've just updated it, can you try downloading from that link again?

**Comment by piotrzarzycki21** [comment]
Perfect! Now it's working :) Thank you!
