### ISSUE TITLE
can't parse JSON

### ISSUE THREAD

**Issue by rokeefe1** [swagger-api/swagger-ui#4855]
### Q&A (please complete the following information)
 - OS: Windows 10 version 1709
 - Browser: Edge
 - Version: 41.16299.611.0
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 3.18
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### To reproduce...

1. Click the execute button for a Get method
2. The response that comes back is "can't parse JSON"

### Expected behavior

The JSON that is returned loads

### Additional context or thoughts

If I hit the endpoint in the browser directly valid JSON is returned.  I put the JSON in a validation tool and it came back as being valid.  I found a post that indicated that this needed to be added to the web.config:

```<add name="Access-Control-Expose-Headers" value="Content-Disposition"/>```

That didn't solve the problem.

This does work in IE11 and Chrome, just not Edge.

**Comment by shockey** [comment]
@rokeefe1, can you share the response that's not being parsed correctly?

**Comment by calmdev** [comment]
Hey, out of curiosity I tried also using Windows 10 with Edge (using version 42 instead of 41 though) and didn't have any issues with JSON response parsing. I used browserstack which lets you test IE edge for free. Test was against an api using the OAS 3 spec using swagger-ui 3.18.2

**Comment by rokeefe1** [comment]
I'm using ASP.Net Web API using Nuget package verison 5.2.6.  I added Swagger using the Swagger-Net Nuget package which references swagger-ui 3.18.  Let me know if there is any other info I can provide or troubleshooting steps you'd like me to take.

**Comment by shockey** [comment]
@calmdev, thanks for pitching in!

@rokeefe1, can you provide a Swagger document that I can use to see this happen on my end?

**Comment by rokeefe1** [comment]
When you ask for a Swagger document what exactly are you asking for?  How do I go about getting that for you?  Please let me know and I'll get it for you right away.

**Comment by rokeefe1** [comment]
Sorry for the delay in the response.  I've attached what I believe you are looking for.
[ApiSwaggerDoc.txt](https://github.com/swagger-api/swagger-ui/files/2372274/ApiSwaggerDoc.txt)

**Comment by IrfanSyed-PSC** [comment]
Same here, I am using Swagger-ui 3.13.6 and it does not work in Edge.

**Comment by cjudd** [comment]
I am having the same problem with Windows 10, Edge Microsoft Edge 41.16299.699.0 (Microsoft EdgeHTML 16.16299) and swagger-ui 3.19.4. Works fine for me in Chrome, Firefox and IE. I always get the response of:

can't parse JSON.  Raw result:
[object Blob]

**Comment by jlw0** [comment]
I'm also seeing this issue with Microsoft Edge 40.15063.674.0 Microsoft EdgeHTML 15.15063.  In my case it is occurring when trying to retrieve the JSON configuration from the _configURL_ query parameter.  It’s odd because Edge works on some sites, but fails on others.  I confirmed that this issue does not occur on IE, Firefox, and Chome.

The problem is occurring because the _getConfigByUrl()_ function from _swagger-ui/src/core/plugins/configs/spec-actions.js_ is receiving a _Blob_ object instead of JSON text when it accesses _res.text_.
```
export const getConfigByUrl = (req, cb)=> ({ specActions }) => {
  if (req) {
    return specActions.downloadConfig(req).then(next, next)
  }
  function next(res) {
    if (res instanceof Error || res.status >= 400) {
      specActions.updateLoadingStatus("failedConfig")
      specActions.updateLoadingStatus("failedConfig")
      specActions.updateUrl("")
      console.error(res.statusText + " " + req.url)
      cb(null)
    } else {
      cb(parseYamlConfig(res.text))
    }
  }
}
```
Later, the _Blob_ object gets incorrectly casted to a _String_ in _loadDocuments()_ from _node_modules/@kyleshockey/js-yaml/lib/js-yaml/loader.js_ and the code is unable to parse JSON from the string “[object Blob]”
```
function loadDocuments(input, options) {
    input = String(input);
```
I believe the problem originates from the _http_ object from the _swagger-client_ npm module.  I’m guessing it isn’t calling handling _Blob_ objects from the _npm-fetch_ response body correctly.  The code in question is in the _serializeRes()_ method from _swagger-js/src/http.js_.
```
export function serializeRes(oriRes, url, {loadSpec = false} = {}) {
  const res = {
    ok: oriRes.ok,
    url: oriRes.url || url,
    status: oriRes.status,
    statusText: oriRes.statusText,
    headers: serializeHeaders(oriRes.headers)
  }

  const contentType = res.headers['content-type']
  const useText = loadSpec || shouldDownloadAsText(contentType)

  // Note: Response.blob not implemented in node-fetch 1.  Use buffer instead.
  const getBody = useText ? oriRes.text : (oriRes.blob || oriRes.buffer)

  return getBody.call(oriRes).then((body) => {
    res.text = body
    res.data = body

    if (useText) {
      try {
        const obj = parseBody(body, contentType)
        res.body = obj
        res.obj = obj
      }
      catch (e) {
        res.parseError = e
      }
    }
    return res
  })
}
```
I’m not much of a JavaScript developer so I’m hoping someone else will be able to follow up and confirm this issue.

**Comment by shockey** [comment]
@jlw0, this sounds like an Edge bug we've dealt with before... try adding this fix to your project: https://github.com/swagger-api/swagger-js/issues/1206#issuecomment-360192722

**Comment by jlw0** [comment]
Yeah, it seems I encountered the same issue.  I tried Microsoft Edge 42.17134.1.0 Microsoft EdgeHTML 17.17134 and I was able to retrieve the JSON from my configuration endpoint.
