### ISSUE TITLE
send Get request with json parameter ,but the request url not send the parameter.

### ISSUE THREAD

**Issue by linconjc** [swagger-api/swagger-ui#4869]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  @RequestMapping(value="/adminListUser",method={RequestMethod.POST,RequestMethod.GET})
	@ApiOperation(value = "管理员获取所有用户信息列表", notes = "{\"scenicIdArr\" : [53361,53356]}")
	public @ResponseBody ServerResponse<BasePageDetail<ViewListUser>> adminListUser( @RequestBody @ApiParam(name="用户列表",value="传入json格式",required=true) ViewListUserCond viewCond)
	{      }
})
```

```
?yourQueryStringConfig
```

### How can we help?

when send the get request by the json parameter,the request url could not send the json data.
so what need I config?

**Comment by linconjc** [comment]
and the responseBody 
{
  "timestamp": 1536748644191,
  "status": 400,
  "error": "Bad Request",
  "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
  "message": "Required request body is missing: public com.omniselling.common.model.ServerResponse<com.omniselling.common.model.BasePageDetail<com.ag.sns.web.user.model.ViewListUser>> com.ag.sns.web.user.controller.UserController.adminListUser(com.ag.sns.web.user.model.ViewListUserCond)",
  "path": "/sns/user/adminListUser"
}

**Comment by shockey** [comment]
Hi @linconjc, this doesn't appear to be related to Swagger UI - did you mean to open this in the Springfox repository?

Closing for now - if there's anything else, or I misunderstood something, just reply!
