### ISSUE TITLE
Avoid Sorting of Parameters

### ISSUE THREAD

**Issue by abhi4151** [swagger-api/swagger-ui#4870]
Is there any way to avoid sorting of parameters in index.html?

Currently the parameters are sorting alphabetically automatically, but I want to preserve the order of the declared annotations.

My Declared annotations:

```
	@ApiOperation(value = "Get Translation Table", notes = "This API is not applicable for CD Unix")
	@ApiImplicitParams({
			@ApiImplicitParam(value = SwaggerSinglePoint.DESC_TRANSLATION_TABLE_NAME, dataType = CDSwaggerPrimitives.STRING, name = SwaggerSinglePoint.TRANSLATION_TABLE_NAME, paramType = CDSwaggerPrimitives.PARAMA_TYPE_QUERY),
			@ApiImplicitParam(value = SwaggerSinglePoint.DESC_TTRANSLATION_TABLE_DATA, dataType = CDSwaggerPrimitives.STRING, name = SwaggerSinglePoint.TRANSLATION_TABLE_DATA, paramType = CDSwaggerPrimitives.PARAMA_TYPE_QUERY)

	})
	@RequestMapping(method = RequestMethod.PUT, produces = CDConstants.JSON_RESPONSE_DATA_FORMAT, consumes = CDConstants.JSON_REQUEST_DATA_FORMAT)
```

Swagger UI:

![image](https://user-images.githubusercontent.com/41680091/45428323-9c78bd00-b6be-11e8-8fbb-f455823be9a4.png)

I just need to preserve the order of the annotations like the one I declared. Because I want the Example Value box to be rendered in the last place.

**Comment by shockey** [comment]
Hi @abhi4151! It looks like your annotation library is the one causing this.

As you can see below, Swagger UI respects the order of parameters as provided in a document:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/680248/45457691-19973880-b6a5-11e8-8342-7f4cd95fdea2.png">

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/680248/45457693-1bf99280-b6a5-11e8-9a68-aaef09edd2f4.png">


I'd suggest looking at the JSON/YAML Swagger document that your annotation library is generating, and see what order things are in there.

I'm going to close this out for now, but if you find that Swagger UI is causing this, feel free to reply and I'll reinvestigate this.

**Comment by dasariy** [comment]
Hi,

I am not using any of YAML files or JSON files to render the page Swagger-ui.html. I am using standard implementation of Swagger-ui. Below are my springfox-swagger-ui versions. In my case how can i avoid sorting of parameters? Any help would be highly appreciated.

 <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.9.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
            <scope>compile</scope>
        </dependency>
