### ISSUE TITLE
Swagger send cut params to server

### ISSUE THREAD

**Issue by webprokopenko** [swagger-api/swagger-ui#4878]
Hi there.
Please help ))
When I send from  swagger UI request to server with params {
  "address": "0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638",
  "tokens": "ZRX",
"tokens":"OMG"
}
the server receives data: 
{
  "address": "0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638",
   "tokens":"OMG"
}
or I send {
  "address": "0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638",
  "tokens": "ZRX",
"tokens":"OMG",
"tokens":"TUSD",
"tokens":"POWR",
"tokens":"KNC"
}
and the server receives next data: 
{
"address": "0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638",
"tokens":"KNC"
}
So params tokens are cut in Swagger. How can I check this problem?
Code in yaml file: 
/api/:
    tags:
      - Get balances of tokens
    post:
      summary: Balance of tokens
      consumes:
        - text/plain
      parameters:
        - in: body
          name: Token List Balance
          description: Token List Balance
          schema:
            type: object
            required:
              - address
              - tokens
            properties:
              address:
                type: string
                default: "0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638"
              tokens:
                type: string
                enum: ['ZRX', 'OMG', 'ZIL', 'REP', 'GNT', 'SNT', 'BNT', 'MCO', 'KNC', 'POWR', 'TUSD']
    responses:
      200:
        description: Success!
      500:
        description: Service unavialable

**Comment by webprokopenko** [comment]
![image](https://user-images.githubusercontent.com/12260853/45536272-9ba07200-b809-11e8-97f0-adc7575acbbe.png)

**Comment by webprokopenko** [comment]
server receive : 
{ address: '0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638',
  tokens: 'OMG' }

**Comment by hkosova** [comment]
You cannot have multiple `tokens` keys in the payload because JSON does not allow duplicate keys. Use https://jsonlint.com to check your JSON for syntax errors.

Does your server expect something like this maybe?
```
{
  "address": "0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638",
  "tokens": ["ZRX", "OMG", "ZIL"]   // <------
}
```
In that case, `tokens` should be defined as an array:
```
tokens:
  type: array
  items:
    type: string
    enum: ['ZRX', 'OMG', 'ZIL', 'REP', 'GNT', 'SNT', 'BNT', 'MCO', 'KNC', 'POWR', 'TUSD']
```

**Comment by webprokopenko** [comment]
But when I send from Postman it's OK
![image](https://user-images.githubusercontent.com/12260853/45539653-0b672a80-b813-11e8-8614-1d40fa610764.png)

**Comment by webprokopenko** [comment]
> You cannot have multiple `tokens` keys in the payload because JSON does not allow duplicate keys. Use https://jsonlint.com to check your JSON for syntax errors.
> 
> Does your server expect something like this maybe?
> 
> ```
> {
>   "address": "0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638",
>   "tokens": ["ZRX", "OMG", "ZIL"]   // <------
> }
> ```
> In that case, `tokens` should be defined as an array:
> 
> ```
> tokens:
>   type: array
>   items:
>     type: string
>     enum: ['ZRX', 'OMG', 'ZIL', 'REP', 'GNT', 'SNT', 'BNT', 'MCO', 'KNC', 'POWR', 'TUSD']
> ```
When I send form from postman server receive valid data
![image](https://user-images.githubusercontent.com/12260853/45540565-71ed4800-b815-11e8-9740-d7442e490c2c.png)

**Comment by hkosova** [comment]
Your Postman example is not JSON, it's form data (`x-www-form-urlencoded`):
```
address=...&tokens=FOO&tokens=BAR
```

In OpenAPI/Swagger this is described as:
```yaml
paths:
  /api/:
    post:
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: address
          type: string
          x-example: '0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638'
        - in: formData
          name: tokens
          type: array
          items:
            type: string
            enum: ['ZRX', 'OMG', 'ZIL', 'REP', 'GNT', 'SNT', 'BNT', 'MCO', 'KNC', 'POWR', 'TUSD']
          collectionFormat: multi
      responses:
        200:
          description: OK
```

**Comment by webprokopenko** [comment]
> Your Postman example is not JSON, it's form data (`x-www-form-urlencoded`):
> 
> ```
> address=...&tokens=FOO&tokens=BAR
> ```
> In OpenAPI/Swagger this is described as:
> 
> ```yaml
> paths:
>   /api/:
>     post:
>       consumes:
>         - application/x-www-form-urlencoded
>       parameters:
>         - in: formData
>           name: address
>           type: string
>           x-example: '0xb4016d8ca33ab5970b1acdc3fb9a63a123a30638'
>         - in: formData
>           name: tokens
>           type: array
>           items:
>             type: string
>             enum: ['ZRX', 'OMG', 'ZIL', 'REP', 'GNT', 'SNT', 'BNT', 'MCO', 'KNC', 'POWR', 'TUSD']
>           collectionFormat: multi
>       responses:
>         200:
>           description: OK
> ```

### It is wonderful. Thank you! Everything is working

**Comment by shockey** [comment]
Closing as resolved 😄 

Thanks for the help, @hkosova!
