### ISSUE TITLE
Add authorization header when loading swagger json end point

### ISSUE THREAD

**Issue by MaklaCof** [swagger-api/swagger-ui#4883]
### Content & configuration
```
buildTimestamp: "Sat, 16 Jun 2018 07:51:13 GMT"
gitDirty: true
gitRevision: "g24faa46"
machine: "travis-job-311a007d-ebec-4b3c-bc7e-58ad5df1e1d8"
version: "3.17.1"
```

### Is your feature request related to a problem?
I would like to restrict access to APIs for unauthorised users in ASP.NET Core with Swashbuckle. I ask how to do it in [SO](https://stackoverflow.com/questions/52314366/add-request-jwt-token-header-when-loading-swagger-json-with-swashbuckle?noredirect=1#comment91610812_52314366), but I got response, that this is not possible.

### Describe the solution you'd like
Solution as I see it is that swagger-ui would also send authorization attribute when loading `swagger.json` (swagger end point) file, when user is logged in with `oauth2`.  
This shouldn't introduce any breaking changes and it is relatively easy to implement.

### Describe alternatives you've considered
I don't have any alternative suggestion. If I want to restrict access to API documentation, I need `authorization` header when loading `swagger.json`.

### Additional context
When different specification is set, 'authorization' header is also set in case when user is logged in.

![chrome_2018-09-17_08-31-05](https://user-images.githubusercontent.com/1589573/45608586-0c3acf00-ba54-11e8-876a-b8d85195b5ed.png)

**Comment by heldersepu** [comment]
I think this could be beneficial to ALL authorizations, (not just to `oauth2`) I've seen similar request in the past on StackOverflow.

And it does not need to be the default it could be an option that way it does not create any back compatibility issues

**Comment by shockey** [comment]
Hey @MaklaCof, we have a ticket for "refetch on authorization" open (https://github.com/swagger-api/swagger-ui/issues/4324) - would that solve your issue here?

**Comment by MaklaCof** [comment]
Hey @shockey.  
It looks it is a duplicate for #4325 not #4324.

Just notice second point in GH-4334 . I think this is it.
