### ISSUE TITLE
Docker Image: not possible to load bind mounted swagger-config.yaml

### ISSUE THREAD

**Issue by glamic-ep** [swagger-api/swagger-ui#4886]
Currently it is not possible to host a external config file (to be loaded via `configUrl`) via nginX in the Docker container itself by bind mounting it into `/usr/share/nginx/html`. The default MIME type is set to `application/octet-stream` in https://github.com/swagger-api/swagger-ui/blob/master/nginx.conf#L9 which prevents the YAML parser from loading the file.

I wanted to replace the `nginx.conf` but when I bind mount it into the Docker container I get errors because in https://github.com/swagger-api/swagger-ui/blob/master/docker-run.sh#L26 and https://github.com/swagger-api/swagger-ui/blob/master/docker-run.sh#L68 `sed -i` is used and that changes the inode of the file because it replaces it. So that doesn't work with bind mounted files.

Here is the patch to `nginx.conf` which worked for me:

```diff
--- nginx.conf
+++ nginx.conf
@@ -15,10 +15,10 @@
   server {
     listen            8080;
     server_name       localhost;
-    root            /usr/share/nginx/html/;
+    index             index.html index.htm;
 
     location / {
-      try_files $uri $uri/index.html =404;
+      alias            /usr/share/nginx/html/;
 
       if ($request_method = 'OPTIONS') {
           add_header 'Access-Control-Allow-Origin' '*';
@@ -46,9 +46,5 @@
           add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
       }
     }
-
-    location /swagger-config.yaml {
-      default_type text/plain;
-    }
   }
 }
```

What I did was:
* get rid of the `index` module to avoid rewrites
* set the document `root` instead
* use `try_files` in the first location block instead of `alias`
* add another location block specifically for `swagger-config.yaml`
* let this file be output by nginX as plain text

**Comment by shockey** [comment]
Hi @glamic-ep! Thanks for the note.

If you'd like to see a code change in Swagger UI, please open a pull request instead of an issue 😄

**Comment by glamic-ep** [comment]
It is still a bug report. Closing it like that is bad practice for any maintainer IMO. Doesn't really encourage me to contribute.
