### ISSUE TITLE
Downloading a file generates a second GET request [without headers]

### ISSUE THREAD

**Issue by giuseppegreco** [swagger-api/swagger-ui#489]
In the following Controller, method getAvatar returns the image of the user's avatar:

```
object Users extends Controller {

  ...

  def getAvatar(imageId: String) = SecuredAction.async { implicit request =>
    daoService.findImage(imageId).flatMap {
      case Some(image) =>
        val contentDisposition = request.getQueryString("inline") match {
          case Some("true") => ContentDisposition.Inline
          case _ => ContentDisposition.Attachment
        }
        serveFile(image, contentDisposition)
      case _ => Future.successful(NotFound)
  }.recover { e => e match {
    ...
  }

  def serveFile(file: MetaFile, contentDisposition: ContentDisposition)( 
    implicit fsService: FsServiceComponent#FsService
  ) = Future {
    val filename = file.filename
    SimpleResult(
      header = ResponseHeader(OK, Map(
        CONTENT_LENGTH -> (s"${file.length}"),
        CONTENT_DISPOSITION -> (s"""$contentDisposition; filename="$filename"; filename*=UTF-8''"""
        + java.net.URLEncoder.encode(filename, "UTF-8").replace("+", "%20")),
        CONTENT_TYPE -> file.contentType.getOrElse("application/octet-stream")
      )),
      body = fsService.enumerate(file)
    )
  }
}
```
The code above forks fine as long as I ignore security. For instance, SecuredAction is a custom Action that manages authorization using Jwt (Json Web Token). Each request needs to have a valid JWT in the AUTHORIZATION header to get authorized... and also this mechanism works fine. The problem is that in case of file download, the method (in this case getAvatar) get invoked twice: the first GET request contains the token, while the second GET request doesn't.

I've tried my REST API with curl: it works fine and DOESN'T generate a second GET as Swagger does.

**Comment by fehguy** [comment]
I'm unable to reproduce this.  If you can re-test with M1, let's reopen this.

**Comment by giuseppegreco** [comment]
Just tried... and I still get two GET requests (as I already told you, 
it works with curl).
j3d

**Comment by webron** [comment]
Is your spec publicly available? If you want to share it in private, feel free to send an email with the details (mail available on profile).

**Comment by jamesearlywine** [comment]
I'm having similar issue.

In Chrome browser:
http://hssticker.indystardev.com/swagger/explore_cache/#!/Sports_Ticker_Cache/get_imageCache_folder_filename
If you use the filename: qfEEqs.png

You'll see that SwaggerUI indicated there is no response from the server.  

..but then it works if you open your web/javascript console. 

..and then when I try it in Firefox, it works fine. 

I notice two requests are being sent to s3 for the image. 

Does anyone know why this would be happening?

--jle
