### ISSUE TITLE
[swagger-ui] Curl's request url without java context name

### ISSUE THREAD

**Issue by sergioluigi** [swagger-api/swagger-ui#4893]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.100
 - Method of installation: Maven
 - Swagger-UI version: 3.19
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

Swagger/OpenAPI definition:
```
resourcePackages:
- com.test
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0'
    title: RestEasy + Swagger Without Spring
servers:
  - url: http://localhost:8080/swagger-resteasy-without-spring-1.0/api
```

### Screenshots
![image](https://user-images.githubusercontent.com/12961631/45923545-9acda700-bebf-11e8-9d01-413bc2652fa4.png)

### How can we help?
Why the curl has not the context name (swagger-resteasy-without-spring-1.0)?

**Comment by shockey** [comment]
@sergioluigi, the YAML you provided isn't a valid OpenAPI definition. Are you using another tool alongside Swagger UI?

My first guess would be to move `servers` under `openAPI`.

**Comment by sergioluigi** [comment]
I solved this issue putting the annotation @OpenAPIDefinition over the class that extends Application.

`package br.com.test;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.servers.Server;

@OpenAPIDefinition(servers = @Server(url = "http://localhost:8080/swaguer-resteasy-without-spring-1.0/"))
@ApplicationPath("/api")
public class ServiceApplication extends Application {

}`

Thank you for your help @shockey

**Comment by shockey** [comment]
Great! Closing as resolved.
