### ISSUE TITLE
Swagger UI Issue with Response for type IEnumerable<KeyValuePair<string, int>>

### ISSUE THREAD

**Issue by Rajgan** [swagger-api/swagger-ui#4900]
Couple of our API controller produces a response of type

`ProducesResponseType(typeof(IEnumerable< KeyValuePair < string, int> >) (int)HttpStatusCode.OK)`

but in Swashbuckle.AspNetCore 3 it creates a model or JSON with full  assembly info like below

> "responses":{"200":{"description":"Success","schema":{"uniqueItems":false,"type":"array","items":{"$ref":"#/definitions/System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int64, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"}}}}}},

This causing problems in consuming app through Autorest client.
It is trying to generate file like

> SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion4000CultureNeutralPublicKeyToken7cec85d7bea7798eSystemDecimalSy stemPrivateCoreLibVersion4000CultureNeutralPublicKeyToken7cec85d7bea7798e.cs.

When we try to create client file we are getting IOException Get-ChildItem : Could not find item
C:\soruce\Generated\Model s\SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion4000CultureNeutralPublicKeyToken7cec85d7bea7798eSystemInt32Syst

**Note:** 
It was working with Swashbuckle.AspNetCore 2.4. Any advice on how to overcome this issue?

**Comment by shockey** [comment]
Hi @Rajgan, I'm going to close this since it doesn't appear to be a Swagger UI-related issue.

Let me know if this in error.

**Comment by Rajgan** [comment]
@shockey then which team I need contact?
