### ISSUE TITLE
doesn't support basic auth?

### ISSUE THREAD

**Issue by lly835** [swagger-api/swagger-ui#4902]
i install swagger-ui by docker, public is dangerous, i want add Authorized.
i can't find basic auth by dockerfile
https://github.com/swagger-api/swagger-ui/blob/master/Dockerfile

**Comment by MitinSany** [comment]
+1, I need It feature also

**Comment by shockey** [comment]
Basic auth is out of scope for our Docker image - if you need it, consider using something like Docker Compose to put a web server in front of Swagger UI that handles auth for you.

**Comment by lly835** [comment]
@MitinSany i has been resolved.
use nginx basic. 
nginx.conf
```
    location / {
      alias            /usr/share/nginx/html/;
      auth_basic "nginx basic http test";
      auth_basic_user_file conf/passwd;
```
