### ISSUE TITLE
APIS doesn't support Multiple parameters

### ISSUE THREAD

**Issue by lly835** [swagger-api/swagger-ui#4903]
docker file

```
ENV API_URL "https://petstore.swagger.io/v2/swagger.json"
ENV API_URLS "[{name:'v2-订单+购物车api', url:'http://test-api.xxxxxx.com/1/git/doc?X-Gitlab-Token=fLM8WF4TwNmJSU4HR&path=/mobile-api/demo.yml'}]"

```

<img width="1010" alt="qq20180927-183655 2x" src="https://user-images.githubusercontent.com/2225913/46140815-bd2b4000-c284-11e8-9d68-1f2435fac334.png">

urlencode '&' to '%26'

```
ENV API_URL "https://petstore.swagger.io/v2/swagger.json"
ENV API_URLS "[{name:'v2-订单+购物车api', url:'http://test-api.xxxxxx.com/1/git/doc?X-Gitlab-Token=fLM8WF4TwNmJSUsN54HR%26path=/mobile-api/demo.yml'}]"

```

<img width="1246" alt="qq20180927-184142 2x" src="https://user-images.githubusercontent.com/2225913/46140933-0e3b3400-c285-11e8-901c-0c6534775b90.png">

**Comment by shockey** [comment]
@lly835, try setting `ENV API_URL ""`

**Comment by lly835** [comment]
> @lly835, try setting `ENV API_URL ""`

i need Multiple url

**Comment by lly835** [comment]
@shockey i has been resolved.
docker-run.sh
```
# replace `url` with `urls` option if API_URLS is set
if [[ -n "$API_URLS" ]]; then
    sed -i "s|^\(\s*\)url: .*,|\1urls: $API_URLS,|g" $INDEX_FILE
fi
```
sed Special treatment for "&".
so the correct is
```
ENV API_URLS "[{name:'v2-订单+购物车api', url:'http://test-api.xxxxxx.com/1/git/doc?X-Gitlab-Token=fLM8WF4TwNmJSUsN54HR\&path=/mobile-api/demo.yml'}]"

```
