### ISSUE TITLE
Auth Error, Error: Bad Request

### ISSUE THREAD

**Issue by bozzltron** [swagger-api/swagger-ui#4905]
### Q&A (please complete the following information)
 - OS: macOs
 - Browser: chrome
 - Version: 69
 - Method of installation: npm
 - Swagger-UI version: ?  swagger-ui-express 3.0.1 comes with a static directory with swagger ui.
 - Swagger/OpenAPI version: 2

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
securityDefinitions:
  oauth:
    type: oauth2
    tokenUrl: /oauth/token
    flow: application
security:
  - oauth: []
```

Swagger-UI configuration options:
```js
// Configure Swagger Docs
let swaggerDocument = yaml.safeLoad(fs.readFileSync('./api/swagger/swagger.yaml', 'utf8'));
app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
```

### Describe the bug you're encountering
I am no longer able to authentication through live docs.  Debugging the POST request to /oauth/token via chrome devtools shows that the client_id and client_secret are not being send.  grant_type is and is the correct value "client_credentials".  

### To reproduce...

1. Go to /docs (my configured router for swagger ui via express)
2. Click on 'Authenticate'
3. Enter 'client_id'
4. Enter 'client_secret'
5. Click modal 'Authenticate' button, which submits the form

### Expected behavior
Should authenticate

### Screenshots
<img width="167" alt="screen shot 2018-09-21 at 11 50 36 am" src="https://user-images.githubusercontent.com/967261/46155123-36527500-c23c-11e8-9fa0-fe576f737365.png">

![screen shot 2018-09-27 at 10 01 49 am](https://user-images.githubusercontent.com/967261/46155204-613cc900-c23c-11e8-9cbe-993ac8feed81.png)

### Additional context or thoughts
I know that the yaml config for OAuth2 is being consumed because its giving me the OAuth2 authentication form.  The break down is in sending the entered credentials.

**Comment by netheodw** [comment]
I have the same error with json format.

**Comment by netheodw** [comment]
i have run the swagger-ui 3.18.3 which is the latest.

**Comment by shockey** [comment]
@bozzltron, upon further investigation, my impression is that we're doing this correctly.

OAuth2 says (emphasis mine):

>  Clients in possession of a client password MAY use the HTTP Basic authentication scheme as defined in [RFC2617] to authenticate with the authorization server [...] The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients that were issued a client password.
> 
> Including the client credentials in the request-body using the two parameters is **NOT RECOMMENDED and SHOULD be limited to clients unable to directly utilize the HTTP Basic authentication scheme** (or other password-based HTTP authentication schemes).
> 
> https://tools.ietf.org/html/rfc6749#section-2.3.1

Since Swagger UI _is_ able to use HTTP basic to transmit the client credentials, we do that instead of including it in the request body.

Let me know if you think I've misinterpreted the spec - happy to take another look.

**Comment by shockey** [comment]
cc: #3227, @frol

**Comment by frol** [comment]
I believe, @shockey is right at his interpretation of the spec, so it seems that Swagger UI does the right thing (i.e. uses HTTP Basic authentication headers to provide `client_id` and `client_secret`) for this authentication flow.

**Comment by bozzltron** [comment]
Thanks for the clarification here.  For future readers the basic authorization header is constructed by base 64 encoded a string that contains client_id and client_secret and is delimited by ":".

**Comment by pacey** [comment]
Hey @shockey , sorry to comment on a closed thread but would it be possible to allow the  HTTP Basic authentication method _or_ the body method? I'm stuck in the middle now where my authentication provider only allows the body method, so integrating that and swagger-ui is impossible.

I appreciate swagger-ui follows the spec correctly, but supporting both way would be helpful for people stuck in my position.

**Comment by shockey** [comment]
@pacey, can you email me about this? I have a branch here, I'd like for you to take a look and tell me if it addresses your use case. `kyle.shockey@smartbear.com`.

**Comment by ksac1** [comment]
I want to use oauth 2 in node js code for our APIs.
Has anybody used it? Please share.

**Comment by ksac1** [comment]
How can I get client key and client secret if the "appliction" oauth2 is getting used for swagger?

**Comment by shockey** [comment]
@ksac1 please open a new issue if you need help!
