### ISSUE TITLE
Is there any configuration parameter through which i can make Model as default visualization for request body

### ISSUE THREAD

**Issue by tnpradeep** [swagger-api/swagger-ui#4927]
Hello All,

Is there any config parameter through which i can make Model view as default visualization for request body instead of Example value which is by default ?

Thanks
Pradeep

**Comment by hkosova** [comment]
Yes
```
defaultModelRendering: "model"
```

https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#display

**Comment by shockey** [comment]
Closing as resolved - thanks @hkosova!
