### ISSUE TITLE
Permalinks don’t work: with tags, and `docExpansion: 'none'`, for operations that don’t have an explicit `operationId`.

### ISSUE THREAD

**Issue by michalrus** [swagger-api/swagger-ui#4929]
When we’re setting `docExpansion: 'none'` in configuration, then giving someone a permalink to a particular endpoint inside a tag, and them clicking it doesn’t do anything for them.

After the page opens for them, all endpoints are still *not expanded*, as if there was no `/#/permalink/part` in the URL.

**Comment by michalrus** [comment]
That’s true, hmmm. But… We’re using 3.19.3, like https://petstore.swagger.io/ — and this Petstore Swagger-UI deployment is not able to expand/deep-link our definition either, if I use `?url=our-swagger.json`.

Can I give you a link to our deployment, so that you can verify? But the API is non-public, so I’d need a private way to contact you. Can I use the email from you profile?

**Comment by shockey** [comment]
@michalrus, sure, shoot me an email and I'll take a look!

**Comment by michalrus** [comment]
@shockey Okay. I was able to minimize this.

So the problem is:

**Permalinks don’t work: with tags, and `docExpansion: 'none'`, for operations that don’t have an explicit `operationId`.**

E.g. this works:

```json
{
  "swagger": "2.0",
  "paths": {
    "/ping": {
      "get": {
        "operationId": "blahBlah",
        "produces": [ "text/plain;charset=utf-8" ],
        "responses": { "200": { "schema": { "type": "string" } } }
      }
    }
  }
}
```

This doesn’t:

```json
{
  "swagger": "2.0",
  "paths": {
    "/ping": {
      "get": {
        "produces": [ "text/plain;charset=utf-8" ],
        "responses": { "200": { "schema": { "type": "string" } } }
      }
    }
  }
}
```

**Comment by michalrus** [comment]
It also seems that `operationId`s with underscores `_` in them fail.

**Comment by shockey** [comment]
Thanks for the update @michalrus!

I'm actually working on that in #4895 right now - I'll add your test cases from the definition you shared, and your notes above.

**Comment by michalrus** [comment]
Thank you very much. =)

We’re auto-generating the `swagger.json` from Haskell’s types anyway, so it was easy to add autogenerated `operationId`s in form of `PUT.v1.permission.role.RoleId.user.me.UserId` etc. It also looks nicer in URLs than those generated fragments.

**Comment by shockey** [comment]
@michalrus, I'm not sure your minimized case is right on the money. 

Both of these work for me (in Chrome on macOS):
- with operationId: http://petstore.swagger.io/?url=https://gist.githubusercontent.com/shockey/7f8670ac020f06f533027a4c94a47482/raw/2ea9246fb170a5a77f4581416f0b3ef990a9e367/with-opid.yaml&docExpansion=none#/default/blahBlah
- without operationId: http://petstore.swagger.io/?url=https://gist.githubusercontent.com/shockey/7f8670ac020f06f533027a4c94a47482/raw/2ea9246fb170a5a77f4581416f0b3ef990a9e367/without-opid.yaml&docExpansion=none#/default/get_ping

Tag expansion (`#/default`) seems to work in both examples as well.

Did I misunderstand something? Let me know - trying to write a test case in my branch for #4895  that covers what you're seeing.

**Comment by shockey** [comment]
The `_` problem is different, I think (and covered in #4895) - that is rooted in my ill-conceived implementation that escapes whitespace in deep link hashes with `_` instead of the now-obvious `%20`. 

`my_operation_id`, when parsed back into Swagger UI from the hash, becomes `my operation id`, which fails to match up with anything that Swagger UI knows about.

**Comment by shockey** [comment]
@michalrus, FYI, I've confirmed that both cases you identified are working on master.

I'll cut releases tonight. Let's keep this open, you tell me if things look better on your end with the new version!

**Comment by shockey** [comment]
@michalrus, any updates here? How is 3.19.4 treating you w/r/t this bug?

**Comment by michalrus** [comment]
It’s working! :sparkles: 

Thank you very much. \^.\^
