### ISSUE TITLE
minimal swagger-ui webpack sample

### ISSUE THREAD

**Issue by absurdist** [swagger-api/swagger-ui#4932]
Hello
Is there an sample project with a minimal swagger-ui  (not -dist) project with webpack?

**Comment by shockey** [comment]
@absurdist, I have a sample project that uses `create-react-app`, which uses Webpack behind the scenes: https://github.com/shockey/swagger-ui-cra

let me know if this isn't what you're looking for!

**Comment by absurdist** [comment]
thank you shockey, I'll read it and see if i can figure out what i want to know.
I'm after a webpack example because i have existing code and sass files built with webpack that I am trying to merge.

**Comment by shockey** [comment]
Gotcha.

Is your current setup giving you any trouble with Swagger UI? It should be pretty straightforward as long as it can handle JS and CSS.

**Comment by absurdist** [comment]
Thank you kyle,

I've got a basic set up working now.

I'll post a link to my boilerplate in github for anyone else who
experiences the confusion I did.

cheers

mat

**Comment by shockey** [comment]
awesome!

closing as resolved.

**Comment by absurdist** [comment]
hi, I'm put my boilerplate swagger in webpack here for anyone else who was to see and `example:`

https://github.com/absurdist/swagger-ui-in-webpack
