### ISSUE TITLE
Current status on 508 compliance and accessibility

### ISSUE THREAD

**Issue by Ryandaydev** [swagger-api/swagger-ui#4935]
I wanted to touch base and see the current status of any efforts for improving accessibility and 508 compliance for the open source swagger UI?

I found the issues below, and some have been closed, so I don't to make duplicate work if there is already an effort in place.

Here are prior gh issues on this topic (some in older versions):
https://github.com/swagger-api/swagger-ui/issues/2216
https://github.com/swagger-api/swagger-ui/issues/3235
https://github.com/swagger-api/swagger-ui/issues/1021

For reference, I ran some automated tests on a site using the 3.18.3 distribution and found quite a few violations, which I could share offline. (I also fixed many of them but only in the swagger-ui-bundle.js, which appears to be a generated file so that probably isn't enough to send in a PR.)

**Comment by shockey** [comment]
Hi @Ryandaydev!

I don't know of anyone working on this at the moment.

If you're interested in making some PRs around this, please reach out to me - we have some UI/UX changes coming down the pipeline, so I'd like to understand what you're planning to do in order to make the components/elements of concern are still relevant.

**Comment by Ryandaydev** [comment]
Nice chatting with you the other day, @shockey. I will wait to see your next release and then will plan on testing and contributing some recommended changes for 508 compliance and accessibility.

Note: if anyone other govvies are interested assisting with this effort, reach out to me directlyl

**Comment by shockey** [comment]
You as well @Ryandaydev - I'll reach out to you within a month with an update.

**Comment by Ryandaydev** [comment]
@shockey I wanted to touch base to see what the current status is?

**Comment by shockey** [comment]
Hi @Ryandaydev - no updates from my end. If you're ready to move forward with your contributions, I can handle the legwork in making sure that they fit in well with anything else coming from our side 😄

**Comment by Ryandaydev** [comment]
OK, so do you suggest that we go ahead and make a pull request off of the 3.18.3 branch?

**Comment by shockey** [comment]
Please open a PR against master - if there are any conflicts, I can take care of them!

**Comment by shockey** [comment]
Closing - this has been addressed out-of-band 😄
