### ISSUE TITLE
Date fields are generating different example dates for JSON and XML

### ISSUE THREAD

**Issue by emilw** [swagger-api/swagger-ui#4939]
The example model generated by Swagger UI generates different example dates.
For JSON it provides Todays date:
![image](https://user-images.githubusercontent.com/2872896/46796461-16977280-cd4d-11e8-87a4-60c8d95491e3.png)

For XML it provides Unix start date:
![image](https://user-images.githubusercontent.com/2872896/46796444-097a8380-cd4d-11e8-98f2-22c38700f3cb.png)

The way the JSON example defaults the example dates makes it more useful when testing out the API:s etc. Is there a reason why it is different today?

**Comment by shockey** [comment]
We're no longer working on or supporting the 2.x series of the UI - please upgrade to v3.

Thanks for the report, though!

**Comment by emilw** [comment]
@shockey , does that means that it's working in the new version?

**Comment by shockey** [comment]
I'm not sure off the top of my head.

You can check by pasting your document into Swagger Editor: https://editor.swagger.io/
