### ISSUE TITLE
can provide button to Open "Model" (Forgive my poor English)

### ISSUE THREAD

**Issue by zjw-swun** [swagger-api/swagger-ui#4949]
old version ui model can show all easy,but new version model can not show all,it is stupid！！！

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
