### ISSUE TITLE
description message is not getting displayed with example object

### ISSUE THREAD

**Issue by AyUsH988** [swagger-api/swagger-ui#4954]
Hi, i wrote a swagger, where in response block i want to display a description and a example object. But i am unable to do that together, either the description message can be displayed or the example object can be displayed.
So this is part of my swagger where i am not getting the description message

```
responses:
  200:
    description: OK
    type: object
    items:
     $ref: '#/definitions/RegOrganisation'
```
so i want both the description and the example object to be displayed.
i have attached the screenshot of my swagger how it is displayed.
so just have a look on this issue.

![55](https://user-images.githubusercontent.com/36485529/47085027-f119d580-d232-11e8-8611-b08b7453f5be.png)

I have raised the issue on swagge-ui-express, you can check it here..
https://github.com/scottie1984/swagger-ui-express/issues/99

**Comment by hkosova** [comment]
The response definition does not look right. If it's an object, it should be:
```yaml
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/RegOrganisation'
```
If it's an array, it should be:
```yaml
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/RegOrganisation'
```
The examples above works fine in the latest version of Swagger UI (3.19.3) and display the response description ("OK").

Try updating your Swagger UI version, and also check your API definition for syntax errors using http://editor.swagger.io. Syntax errors in your API definition can prevent it from rendering properly.

**Comment by shockey** [comment]
Closing as resolved
