### ISSUE TITLE
TypeError: e.split is not a function

### ISSUE THREAD

**Issue by bettyleung** [swagger-api/swagger-ui#4955]
- OS: OSX
 - Browser: chrome 
 - Version: 68.0.3440.106
 - Method of installation: npm
 - Swagger-UI version: 3.19.3,
 - Swagger/OpenAPI version: OpenAPI 3.0

Here is my swagger.yaml response snippet:
```     
responses:
   '200':
      description: 'An excel file.'
      content:
         application/vnd.openxmlformats officedocument.spreadsheetml.sheet:
            schema:
               type: string
               format: binary
```

I unable to define a response to download an excel file. When using the "Try it out" button, the swagger-ui response is a 200 but the details displays: "😱 Could not render this component, see the console". 

The console outputs:
```root-injects.js:95 
TypeError: e.split is not a function
```     
Any ideas why this error is occurring?

**Comment by diogobaeder** [comment]
Hey @bettyleung ,

I faced this issue today, but found out the problem and how to overcome it, so I thought it could be helpful for you too.

The thing is, Swagger UI tries to parse the file content to display in its own UI if you serve the file with the default headers or with forcing "Content-Disposition: inline". However, if you define that header to "Content-Disposition: attachment", Swagger UI should offer you to download it just fine, as expected.

At first I thought this was a bug, but it actually makes sense; the UI tries to be as helpful as possible with parsing the content to display it there, but Excel files don't seem to be parse-friendly for Swagger.

One thing I haven't tried, though, is to define the response headers to signalize that it's a zipped file (xlsx Excel files are actually zipped XML). I'll let you know here if it works.

Cheers,
Diogo
