### ISSUE TITLE
Configure initOAuth in swagger-config.json for Docker

### ISSUE THREAD

**Issue by ithr0n** [swagger-api/swagger-ui#4957]
I am using the docker container swaggerapi/swagger-ui:v3.19.0 and have set the environment variable "CONFIG_URL=https://<my-server>/swagger-config/swagger-config.json"

In this config I have configured swagger-ui (i.a. oauth2RedirectUrl) and the configuration basically works and gets loaded by swagger-ui.
According to the documentation https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md it should be possible to configure the action initOAuth, to define the client_id for authentication.

But all my tries failed. How do I need to configurate it?

My last try was (demo data):
```
{
    ...
    "oauth2RedirectUrl": "https://<my-server>/swagger-ui/oauth2-redirect.html",
    "initOAuth": (configObj) => ui.initOAuth({
        clientId: "your-client-id"
        clientSecret: "your-client-secret-if-required",
        realm: "your-realms",
        appName: "your-app-name",
        scopeSeparator: " ",
        additionalQueryStringParams: {test: "hello"}
    })
}
```

Setting the clientId by environment variable is also not working, see: https://github.com/swagger-api/swagger-ui/issues/3467

**Comment by shockey** [comment]
After our release tomorrow, you'll be able to do this through environment variables 😄
