### ISSUE TITLE
Password flow does not work anymore

### ISSUE THREAD

**Issue by anfle** [swagger-api/swagger-ui#4962]
### Q&A
 - Method of installation: npm
 - Swagger-UI version: since 3.19.1

### Content & configuration
The password flow does not work anymore with the following configuration:
```
#Headers:
Authentication: Basic base64
Content-Type: application/x-www-form-urlencoded

# Form data:
grant_type: password
username: ******
password: ******
```

After the following commit 054d450a45474cd8099622b73653349bea4ec7e9, the default branch is impossible to reach. That's the branch I want to reach with my configuration.

Currently, `passwordType` can be `query`, `request-body` or `basic`: two are handled in the switch, the other one in a previous if condition

**Comment by shockey** [comment]
@anfle, I dug pretty far into this and I can't reproduce the issue. Please provide the following info:

- the `securityDefinition` that you're seeing this with
- a screenshot of the Authorize options you've set when this happens (sounds like you're using the `basic` request type?)

**Comment by anfle** [comment]
Here are the `securityDefinitions` I use:
```json
"securityDefinitions": {
  "OAuth": {
    "type": "oauth2",
    "tokenUrl": "/api/oauth/token",
    "flow": "password"
  }
}
```

I'm using the request-body type.
Here are some screenshots of the problem:
![authorize_3 19 0](https://user-images.githubusercontent.com/5066422/48996222-9a65bc80-f14b-11e8-9dd6-c4043a178060.png)

Version 3.19.0:
In the HTTP request, there is an `Authorization` header with the desired content: `Basic base64(client-id:client-secret)`:
![headers_3 19 0](https://user-images.githubusercontent.com/5066422/48996277-c97c2e00-f14b-11e8-997a-50b0a7acb4fc.png)

And I'm successfully logged in:
![authoized_3 19 0](https://user-images.githubusercontent.com/5066422/48996235-a487bb00-f14b-11e8-985b-388f833db13b.png)

Version after 3.19.0 (error still present in the last release):
No `Authorizaton` header in the `POST` request:
![headers_3 20 1](https://user-images.githubusercontent.com/5066422/48996302-e31d7580-f14b-11e8-99c7-a04c17df7ee9.png)

And there is an error at log in:
![authorize_3 20 1](https://user-images.githubusercontent.com/5066422/48996297-e0228500-f14b-11e8-95e7-80d69191c07f.png)

Let me know if you want more information.

**Comment by shockey** [comment]
@anfle, we've recently reworked the way that the OAuth client credentials are attached to requests. Can you try setting your Client Credentials Location to `Authorization header` in the latest version of Swagger UI and seeing if that works for you?

<img width="285" alt="image" src="https://user-images.githubusercontent.com/680248/52388026-27819780-2a52-11e9-855a-8554a13378c7.png">

**Comment by anfle** [comment]
@shockey Just tested the last version 3.20.6 and it works pefectly in my case.
Thanks

**Comment by shockey** [comment]
@anfle happy to hear it, thanks for following up!
