### ISSUE TITLE
Set default value for boolean property type to false in example section if default and example not provided

### ISSUE THREAD

**Issue by tnpradeep** [swagger-api/swagger-ui#4964]
### Content & configuration

Swagger/OpenAPI definition:
       complete": {
          "type": "boolean"
        }

 Why the default value for boolean type is not set to false in example section of body parameter, if i don't provide default value explicitly and don't provide any example ?

**Comment by shockey** [comment]
@tnpradeep, some environments omit parameters defined as `false`, so we default to true. You're free to override that if you'd like to!
