### ISSUE TITLE
Make the `servers` array configurable via the `SwaggerUI` object

### ISSUE THREAD

**Issue by dirkschneemann** [swagger-api/swagger-ui#4968]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
servers:
  - url: /api
    description: Some description.
 ```

 Swagger-UI configuration options:
 ```js
SwaggerUI({
  dom_id: '#docs',
  url: window.location.href + 'api_specification.yml',
});
 ```

### Is your feature request related to a problem?
The base path of my API (the part after `server URL` as [outlined here](https://swagger.io/docs/specification/api-host-and-base-path/)) is dynamic and can change with each deployment (different branches are served at different paths on the same server).

However, as is well known, using a relative URL under the top level `servers` key, as in
```
servers:
  - url: /api
```
will construct all `Try it out` URLs by appending `/api` relative to the `server URL` and not to the full path. Example:

The docs are hosted at `http://my-server/dynamic/path/docs`, the corresponding API is hosted at `http://my-server/dynamic/path/api`.

The `Try it out` URLs, however, will look like `http://my-server/api` which obviously returns a 404 error.

### Describe the solution you'd like
I would like to be able to configure the `server` array in the specification file via the `SwaggerUI` object. This way, I could do something like this which would make all `Try it out` URLs resolve correctly:
```
SwaggerUI({
  dom_id: '#docs',
  url: window.location.href + 'api_specification.yml',
  servers: [
    {
      url: window.location.pathname.split('/docs')[0] + '/api'
    }
  ]
});
```

### Describe alternatives you've considered
My current work-around is to manipulate the `server` array in my specification file in my application build scripts, using tricks like templating or `sed` or similar. This just doesn't feel right though.

**Comment by shockey** [comment]
@dirkschneemann, have you tried using a relative-path URL instead of an absolute-path URL (see [RFC 3986 s4.2](https://tools.ietf.org/html/rfc3986#section-4.2) for definitions)?

Something like this:
```
servers:
  - url: ../api
```

If your document is at `http://my-server/dynamic/path/docs/swagger.json`, this will point requests at `http://my-server/dynamic/path/api`.

Also: note that a server URL is always relative to where your Swagger document is located, _not_ where Swagger UI is hosted!

**Comment by dirkschneemann** [comment]
I'm afraid that the above-mentioned behaviour is influenced by my reverse proxy and its path stripping rules before forwarding the request to the backend. I'll check this in more detail and get back to it but until then, we can assume that it works as documented.

**Comment by shockey** [comment]
@dirkschneemann, sounds good - looking forward to an update.

**Comment by dirkschneemann** [comment]
Hi @shockey , yep, my problem was indeed due to using the `PathPrefixStrip` rule in my [traefik reverse proxy](https://docs.traefik.io/basics/#matchers) which forwards requests to my Docker container hosting `SwaggerUI` on a webserver.

Using the `servers` key in the specification without such a setup works as expected and is indeed a solution to my initial question.

This thread can be closed then from my point of view, thank you again for your support.

**Comment by shockey** [comment]
@dirkschneemann great! glad you got it figured out 😄
