### ISSUE TITLE
Example not rendered if Definition with Example and $ref 

### ISSUE THREAD

**Issue by tnpradeep** [swagger-api/swagger-ui#4974]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: chrome
 - Version: 69.0.3497.100
 - Method of installation: dist assets
 - Swagger-UI version: 3.19.4
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

```yaml
swagger: '2.0'
info:
  description: 'This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For
    this sample, you can use the api key `special-key` to test the authorization filters.'
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: petstore.swagger.io
basePath: "/v2"
tags:
- name: pet
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: store
  description: Access to Petstore orders
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
schemes:
- https
- http
paths:
  "/pet":
    post:
      tags:
      - pet
      summary: Add a new pet to the store
      description: ''
      operationId: addPet
      consumes:
      - application/json
      - application/xml
      produces:
      - application/xml
      - application/json
      parameters:
      - in: body
        name: body
        description: Pet object that needs to be added to the store
        required: true
        schema:
          "$ref": "#/definitions/Pet"
      responses:
        '405':
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
        - read:pets
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: https://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Category
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  Pet:
    type: object
    required:
    - name
    - photoUrls
    properties:
      id:
        type: integer
        format: int64
      category:
        "$ref": "#/definitions/Category"
        example:
          id: '123'
          name: scooby
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        xml:
          name: photoUrl
          wrapped: true
        items:
          type: string
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          "$ref": "#/definitions/Tag"
      status:
        type: string
        description: pet status in the store
        enum:
        - available
        - pending
        - sold
    xml:
      name: Pet
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
```

### Describe the bug you're encountering
When you provide any schema definition having $ref and an example [ Pet definition in above provided swagger json ], the example is not rendered in the 'Example Value' section of body parameter.

But if you move the example to referenced definition [ Category in above provided swagger json ], it renders properly.

### Expected behavior
Above provided swagger json is valid as per spec, but still swagger-ui won't render the example value properly. I expect it should render the example value either you provide it inline along with $ref or in referenced definition. This allows us to document different example for different references.

### Screenshots
![image](https://user-images.githubusercontent.com/13568762/47651221-9c6a4900-dba8-11e8-94da-b55ee9607928.png)

**Comment by hkosova** [comment]
`$ref` works by replacing itself and all of its sibling elements with the definition it is pointing at, that's why the `example` (any any other attributes) _directly alongside_ `$ref` won't have effect.

As you correctly noted, the solution is to move the example into the referenced definition.
Another possible workaround is to wrap the `$ref` into `allOf`:

```json
"category": {
  "allOf": [
    {"$ref": "#/definitions/Category"},
    {
      "example": {
        "id": "123",
        "name": "scooby"
      }
    }
  ]
}
```

**Comment by shockey** [comment]
@hkosova is correct - you can't have Reference Objects alongside other values.

FYI, Swagger Editor marks this as incorrect:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/680248/47669731-edb31200-db81-11e8-9801-97c0649dc63e.png">

**Comment by shockey** [comment]
@tnpradeep, the fact that it was working in 2.x was a bug - the Swagger/OpenAPI Specification (as well as the JSON Schema specification) is quite clear about the fact that $ref cannot have sibling values.

We hashed this out at length over in https://github.com/swagger-api/swagger-ui/issues/4732 a few months ago. I invite you to take a look at everything mentioned there so that you understand out viewpoint in choosing to not support this going forward.
