### ISSUE TITLE
Missing documentation on simple static distribution

### ISSUE THREAD

**Issue by maral** [swagger-api/swagger-ui#4976]
In the install section, there is no mention of the possibility to just copy the /dist directory to my project. It was in documentation in the older version, so I knew how to do it, however for others it might be confusing, as from the webpage the natural direction is to the [Installation page](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md), which is quite difficult to grasp for non-js programmers.

**Comment by shockey** [comment]
Hey @maral!

Fair point 😄 

Though I'm not a big fan of direct copying, since it locks users into specific versions... you _can_ do it, so we should document it as an option.

**Comment by tomchristie** [comment]
I think it's worth comparing the difference to ReDoc's documentation... https://github.com/Rebilly/ReDoc#tldr

Their TDLR is just a single HTML page that points at a CDN'd version of redoc.

It'd be great if Swagger UI did something similar. Either just being able to copy the /dist files, or being able to immediately point at CDN hosted versions is *really* helpful for allowing developers to just jump in, vs. "Here's an NPM package"

**Comment by shockey** [comment]
@tomchristie, we do document this 😄 https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#unpkg

It is a bit tucked away - I'd be happy to accept a PR that adds a TL;DR to our README!

**Comment by diberry** [comment]
@maral Has a good point. I want to be able to serve the documentation from github -- as static files. I realize the try me now feature won't work but I really just want the static docs. I imagine he and I are not the only ones.

**Comment by shockey** [comment]
fixed in #5095!
