### ISSUE TITLE
Swagger-ui webpack-dev-server blocking react-scripts update

### ISSUE THREAD

**Issue by oupvo01** [swagger-api/swagger-ui#4979]
- OS: [Windows 10]
 - Browser: [n/a]
 - Method of installation: [npm]
 - Swagger-UI version: [3.19.4]

the bug you're encountering

I'd like to update react-scripts inside a create-react-app project. 
After running `npm install --save --save-exact react-scripts@2.0.5`
I get this
![image](https://user-images.githubusercontent.com/42371237/47705633-67e9a200-dc27-11e8-8b70-ed18f69ddc33.png)

`npm ls webpack-dev-server` outputs this
![image](https://user-images.githubusercontent.com/42371237/47705686-94052300-dc27-11e8-982d-08ddb6da035f.png)

I can disable the preflight check that outputs the warning above but I'd rather not do it this way.

**Comment by shockey** [comment]
Yep, this is on us - it’s in our optionalDependencies 🤔 

I’ll move it to devDependencies. This should be resolved in our release on Friday!

**Comment by oupvo01** [comment]
@shockey Thanks for quick answer! I'll eventually reopen this issue if this persists 😄
