### ISSUE TITLE
Calling GET endpoint redirects to POST endpoint

### ISSUE THREAD

**Issue by poonamshah** [swagger-api/swagger-ui#4980]
Calling GET endpoint redirects to POST endpoint

Chrome Version : Version 70.0.3538.77 (Official Build) (64-bit)
Safari Version :  Version 12.0 (12606.2.11)
Firefox Version : 59.0.2 (64-bit)

Swagger Version : 3.19.4

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
