### ISSUE TITLE
Support for property types ipv4, ipv6 and date-time in example values

### ISSUE THREAD

**Issue by cweiske** [swagger-api/swagger-ui#4986]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
openapi: 3.0.0
paths:
  /monitor/connection/status:
    post:
      summary: Test
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TypeTest'
      responses:
        '200':
          description: All ok
components:
  schemas:
    TypeTest:
      type: object
      properties:
        hostname:
          type: string
        ipv4:
          type: ipv4
        ipv6:
          type: ipv6
        current_time:
          type: date-time
 ```

 Swagger-UI configuration options:

(none)

### Is your feature request related to a problem?
The "Example Value" for the TypeTest schema shows several warnings/errors/unsupported:

```
{
  "hostname": "string",
  "ipv4": "Unknown Type: ipv4",
  "ipv6": "Unknown Type: ipv6",
  "current_time": "Unknown Type: date-time"
}
```

### Describe the solution you'd like
Swagger UI should know the types ipv4, ipv6 and date-time and fill them with example IPs and the current time.

### Additional context
The  types are defined here:
https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-7.3

**Comment by shockey** [comment]
https://github.com/swagger-api/swagger-ui/pull/5024 adds support for `format: date` and `format: date-time`... IP address format examples are still unimplemented 😄

**Comment by jeremyhayes** [comment]
@shockey to be clear, #5024 adds support for `date` format...`date-time` support was already there.
