### ISSUE TITLE
Authorize and Try it out buttons

### ISSUE THREAD

**Issue by figuerres** [swagger-api/swagger-ui#5010]
### Q&A (please complete the following information)
 - OS:  windows 10 / server 2016
 - Browser: chrome
 - Version: 70.0.3538
 - Method of installation: bundled dist files
 - Swagger-UI version:  3.19.3
 - Swagger/OpenAPI version:  Swagger 2.0

i have web api's that need a jwt token to execute.
the "try it out" button is enabled even though the UI has not toggled the "padlock icon" to locked.
i do not understand this behavior

if the api needs auth, and the padlock is open then "try it out" should be disabled or should pop up the authorize dialog before showing the execute button ui.

this seems like a flaw in the ui code behavior, if the api method has no security then enable try it out all the time by default.
if the method has security then has the "authorize" button be used and obtained a token, if it has then enable the try it button & the execute ui can be shown.

i have seen other asking to disable or hide the button but not  asking about this case.

**Comment by hkosova** [comment]
This lets you test the endpoints specifically without providing authentication to make sure they return a proper HTTP status code and error response, such as 401 Unauthorized.

**Comment by figuerres** [comment]
found that i had an issue that was creating a redirect to confuse the swagger-ui thanks.
