### ISSUE TITLE
Upgrade to latest Swagger UI Dist

### ISSUE THREAD

**Issue by ocha** [swagger-api/swagger-ui#5012]
### Is your feature request related to a problem?
There are some bugs that were fixed since v3.17 of Swagger UI Dist. 

### Describe the solution you'd like
Upgrade to latest version

### Additional context
If you have enum for path in your api definition, swagger ui v3.17 does not update URL correctly

**Comment by shockey** [comment]
Hey @ocha - are you saying that newer versions of Swagger UI **do** or **do not** have an issue with updating the URL?

**Comment by shockey** [comment]
@ocha, I see. What gem are you using? This probably should be reported to another project, since we don't maintain any gems here.

**Comment by ocha** [comment]
@shockey I am so sorry. I meant to open this ticket in rswag repo.
I was on wrong tab 🤦‍♂️

**Comment by shockey** [comment]
@ocha no worries! 😄
