### ISSUE TITLE
Wrap spec in parent object

### ISSUE THREAD

**Issue by jleck** [swagger-api/swagger-ui#5017]
Hi,

Is there any support for wrapping a JSON spec in a parent object? My API usually returns a parent object with the response status code, metadata etc. Is it possible to tell swagger to get the JSON from a nested key?

Thanks!

**Comment by shockey** [comment]
Hey @jleck, I'm not quite following what you're getting at - can you share an example of what you have in mind?

**Comment by jleck** [comment]
Hi @shockey 

Take the follwing spec:

```json
{
    "openapi": "3.0.0",
    "info": {
        "title": "HyperBolts | API",
        "version": "0.0.1"
    }
}
```

What I would really like to return is:

```json
{
    response: {
        "openapi": "3.0.0",
        "info": {
        "title": "HyperBolts | API",
        "version": "0.0.1"
    },
    status: 200
}
```

So it can follow the structure of all other APIs I have. Hopefully that makes sense. Basically need a way of getting a spec from a nested key in JSON :)

**Comment by shockey** [comment]
Hmm - to be certain, this is what's coming back from the URL that you want to point Swagger UI at?

**Comment by shockey** [comment]
If so, follow up question: how are you using Swagger UI?

**Comment by jleck** [comment]
Correct. I’ve embedded swagger ui as a route in a SPA.

I have middleware on my api that wraps responses in additional metadata like status, generation time etc. Would be quite useful to me keep that included.

**Comment by jleck** [comment]
Backend is php inside docker

**Comment by shockey** [comment]
Gotcha. Can you post a snippet of how you're using Swagger UI in the SPA?

**Comment by jleck** [comment]
```tsx
import * as React from "react";
import SwaggerUi, {presets} from "swagger-ui";
import "swagger-ui/dist/swagger-ui.css";
import "./index.scss";

class Index extends React.Component {
    protected swaggerRef: React.RefObject<any> = React.createRef();

    public componentDidMount() {
        SwaggerUi({
            domNode: this.swaggerRef.current,
            presets: [presets.apis],
            requestInterceptor: this.handleRequest,
            url: getConstant("SWAGGER_URL"),
        });
    }

    public render() {
        return (
            <>
                <Breadcrumbs crumbs={this.getBreadcrumbs()} />
                <Commands commands={this.getCommands()} />
                <div ref={this.swaggerRef} />
            </>
        );
    }

    protected getAuth() {
        return {};
    }

    protected getBreadcrumbs() {
        return [
            {
                href: "/admin",
                label: "Admin",
            },
            {
                href: "/admin/swagger",
                label: "Swagger Docs",
            },
        ];
    }

    protected getCommands() {
        return [
            {
                iconProps: {
                    iconName: "Cancel",
                },
                key: "close",
                name: "Close",
                onClick: () => close(),
            },
        ];
    }

    protected handleRequest(request: any) {
        request.headers.Authorization = `Bearer ${getAuthToken()}`;
        return request;
    }
}

export default Index;
```

**Comment by jleck** [comment]
Ah, yes! WIll give it a go

**Comment by shockey** [comment]
@jleck did it work? 😄

**Comment by jleck** [comment]
Just had a quick play! I couldn't get it to work with your example. However, I changed the text:

```js
response.text = JSON.stringify(response.body.response);
```

And that worked fine :) Can you see any issues with doing that?

**Comment by shockey** [comment]
@jleck nope, if that's what works for you all good!

Closing as resolved 🎉
