### ISSUE TITLE
Need way to hide curl command from swagger response using configuration

### ISSUE THREAD

**Issue by Anujg1983** [swagger-api/swagger-ui#5020]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
 # your YAML here
 ```

 Swagger-UI configuration options:
 ```js
 SwaggerUI({
   // your config options here
 })
 ```

 ```
 ?yourQueryStringConfig
 ```

**Comment by hkosova** [comment]
Here's a plugin that hides the "Curl" section from responses:
```js
// index.html

  const HideCurlPlugin = () => {
    return {
      wrapComponents: {
        curl: () => () => null
      }
    }
  }

  // Build a system
  const ui = SwaggerUIBundle({
    url: "https://petstore.swagger.io/v2/swagger.json",
    ...
    plugins: [
      HideCurlPlugin    // <----
    ],
    ...
  })
```

**Comment by lsloan** [comment]
> ```js
>   const HideCurlPlugin = () => {
>     return {
>       wrapComponents: {
>         curl: () => () => null
>       }
>     }
>   }
> ```

Is there any way to make a plugin like this that makes the "Curl" section collapsible rather than remove it completely?

**Comment by wh81752** [comment]
Very good  request!

The curl section *leaks* by default the API-KEY (if applicable of course). This is a no go. Think about a little presentation demonstrating a given API to a wider audience and - voila, key is leaked.

The first option is to just turn curl off. Works, but I guess we want to see curl once a while.
Second is to collapse. That's a decent solution.
The best is probably to only partially show the API-KEY or show a hash or something,

**Comment by armyofmarkness** [comment]
I too, would love to see this as a configurable option.
