### ISSUE TITLE
 Log In Swagger definition error - Could not resolve reference

### ISSUE THREAD

**Issue by Poornima2210** [swagger-api/swagger-ui#5026]
I am creating swagger.json with help of java code.

 @ApiParam(value = "Endpoint properties") @QueryParam("attributes") final Set<EntryParam> attributeSet
I am unable to see the definition generated for EntryParam(This is our customized class) in swagger.json.
Getting the error
Resolver error at paths./6.1/endpoints.get.parameters.8.items.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/EntryParam does not exist in document

How to generate EntryParam definition in swagger.json OR how to reslove this issue

Note:
But if I change the above code to String or only EntryParam class then it working as expected. Only with Set<EntryParam> it is not working
a. @ApiParam(value = "Endpoint properties") @QueryParam("attributes") final EntryParam attributeSet
b. @ApiParam(value = "Endpoint properties") @QueryParam("attributes") final String EntryParam attributeSet
          
Following details of swagger used in our project.
1. Maven Plugin com.github.kongchen  Vesrion : 3.1.2
2. io.swagger  core  Version: 1.5.4

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
