### ISSUE TITLE
error when service returns model of type byte[]

### ISSUE THREAD

**Issue by TripledT** [swagger-api/swagger-ui#504]
Error that appears in console, Cannot read property 'getMockSignature' of undefined
The issue is in swagger.js at 
```
SwaggerOperation.prototype.isListType = function(type) {
      if (type.indexOf('[') >= 0) {
        return type.substring(type.indexOf('[') + 1, type.indexOf(']'));
      } else {
        return void 0;
      }
    };
```
type is byte[] and the isListType function returns a empty string instead of void.  This causes the getMockSignature error later on.

**Comment by fehguy** [comment]
in the 2.0 spec, this would be:

```json
{
  "type": "array",
  "items": {
     "type": "string",
     "format": "byte"
  }
}
```

The original issue is correct, though, it's not supported

**Comment by fehguy** [comment]
this should be supported in develop_2.0
