### ISSUE TITLE
JWT Token not working when added

### ISSUE THREAD

**Issue by talkersoft** [swagger-api/swagger-ui#5046]
I am using asp.net core 2.1 with the latest version of swagger. When i add my bearer token in the authorization box the Authorization header does not appear to be added to the request and I am unable to call any of my api's which require authorization. I am quite certain i have everything configured correctly in my api, I am even able to call these same methods which require authorization using postman. One thing i noticed is when I look at the request in chrome dev tools I would expect the see the Authorization header in the request, when executing the api from swagger I do not see this Authorization header with the bearer token value. I did read about a past bug somewhere that had to do with URI Encoding of the token, I am wondering if this somehow got reintroduced, I have spend hours trying to find a workaround but to no avail, I will have to use postman but I am hoping for a fix or workaround so that I can introduce swagger on this project.

**Comment by shockey** [comment]
Hi @talkersoft!

If you're seeing the Authorization header in Postman but not in Swagger UI, please make sure that your server is correctly configured to respond to CORS requests. Specifically, make sure that it is sending back an `Access-Control-Allow-Headers` value that includes `Authorization`.

**Comment by shockey** [comment]
More info: https://enable-cors.org/

**Comment by shockey** [comment]
glad you got it figured out!

closing 👍
