### ISSUE TITLE
file download not working from swagger-ui

### ISSUE THREAD

**Issue by vdevpriya** [swagger-api/swagger-ui#5050]
Using swagger-ui : 

<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.6.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.6.1</version>
			<scope>compile</scope>
		</dependency> 

returning this from api:

	return  ResponseEntity.ok()
				.header("Content-Disposition", "attachment; filename=\"" + EscapeUtils.escapeHtml(fileName) + "\"")
				.header("Access-Control-Expose-Headers", "Content-Disposition")
				.contentType(MediaType.APPLICATION_OCTET_STREAM)
				.body(attachment);

If I select 'application/octet-stream', swagger gives 406.
If I select 'application/json', it gives a download link. When I click the link a file named like 'b2cfd124-909b-4be1-9956-356eaed9a8e9' gets downloaded. And it does not contain data . It rather contain teh path pf the file which should have been downloaded.

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
