### ISSUE TITLE
externalDocs Support in swagger2

### ISSUE THREAD

**Issue by UmeshNebhani7303** [swagger-api/swagger-ui#5052]
### Q&A
 - OS: windows 10
 - Browser: chrome
 - Version: 2.9.2 ( version of lib i used in gradle )
 - Method of installation: gradle dependencies
 - Swagger-UI version: N/A ( See below explanation )
 - Swagger/OpenAPI version: N/A ( See below explanation)

### How can we help?
Hi Team, 

I am trying to enable swagger documentation for my Rest API build in spring boot as follows:

@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket commonApi() {
        return new Docket(DocumentationType.SWAGGER_2).select()
                .apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class)).build()
                .apiInfo(apiInfo());
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder().title("Deepsea Test API")
                .description("Test  API")
                .termsOfServiceUrl("")
                .contact(new Contact("Team Superman", null, "superman@amazeen.de"))
                 .build();
    }
}

For dependencies i added following libs in my gradle build
 "io.springfox:springfox-swagger2:2.9.2",
 "io.springfox:springfox-swagger-ui:2.9.2",

By just adding above points, i am able to see Swagger API for my rest end points which i annoted with 
@Api &  @ApiOperation

However i also wanted to add some external documentation in my swagger-ui.html but i havent found any good solution to do that.

Do i need to create swagger.yml file for this? Can you point to some solution which can help?

Here is a **screenshot** what i want.
http://editor.swagger.io/

![image](https://user-images.githubusercontent.com/40858015/49000484-051df480-f15a-11e8-8aa0-1b0a57060861.png)

Regards,
Umesh Nebhani

**Comment by shockey** [comment]
Hi @UmeshNebhani7303,

it looks like Springfox doesn't support this: https://github.com/springfox/springfox/issues/1989

You could always add externalDocs directly to your Swagger definition, like so:
```yaml
swagger: "2.0"

externalDocs:
  description: my docs
  url: http://swagger.io/whatever/url/
```
