### ISSUE TITLE
Missing description for servers: definition

### ISSUE THREAD

**Issue by MichalStehlikCz** [swagger-api/swagger-ui#5054]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Edge
 - Version: 42.17134.1.0
 - Method of installation: dist
 - Swagger-UI version: 3.20.1
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Servers dropdown is missing after update from 3.20.0 to 3.20.1

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Simple test
  description: Simple test of JAX-RS without any dependencies
  version: "1.0"
servers:
  - url: /testws/api
    variables: {}
paths:
  /simple:
    get:
      summary: Get text
      description: Return simple plain text
      operationId: getText
      responses:
        default:
          description: Text
          content:
            text/plain:
              schema:
                type: string
```

Swagger-UI configuration options:
```js
SwaggerUI({
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout",
        validatorUrl: null
})
```

### Describe the bug you're encountering
Servers dropdown is missing after upgrade from 3.20.0 to 3.20.1

### To reproduce...
Servers drop-down missing when page is opened, no steps needed

### Expected behavior
Servers drop-down should be present as in 3.20.0

### Additional context or thoughts
Likely problem in commit
Commit: 2977c93840a897758e9570c6712eb0e803ae7e7d [2977c93]
Parents: db9e24541f
Author: João Abecasis <joao@abecasis.name>
Date: Wednesday, November 21, 2018 03:06:26
Committer: kyle

**Comment by shockey** [comment]
Hi @MichalStehlikCz!

I'm not able to reproduce this - I can see the servers dropdown in 3.20.1.

Using Swagger UI 3.20.1 in my local filesystem's `dist` folder, with the spec you provided:

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/680248/49151001-ddbc5880-f30e-11e8-8dd1-e9a5e9af2bfb.png">

Here's the URL I used to test: https://gist.githubusercontent.com/shockey/4c419777a9efaf1f7443b23730ca5e4a/raw/b873a6a2cffec269a5ba9a9e12804330b9f99617/ui-5054.yaml

**Comment by MichalStehlikCz** [comment]
I must have pulled wrong version - I cannot replicate it either after going back to 3.20.1 from 3.20.0, sorry
