### ISSUE TITLE
Swagger html rendering for response class as a link in the method definition

### ISSUE THREAD

**Issue by hum2u** [swagger-api/swagger-ui#5058]
### Content & configuration

![current](https://user-images.githubusercontent.com/8265108/49311007-cad39080-f494-11e8-8b47-e5d8b7bd7404.PNG)
![desired](https://user-images.githubusercontent.com/8265108/49311008-cdce8100-f494-11e8-8ac3-e9510da33243.png)

Hi.

Currently the swagger HTML rendering the response class definition in the HTML rendering for a method but does not create a link to it from the method definition. See the attached image called "Current"

I would like the HTML rendering of the Responses header of the method definition to have a link to the response class for easy reference, so the desired rendering is as specified in the attached image "Desired", Behind the link would be something like <a href="#MyResponseClass">MyResponseClass</a>

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
