### ISSUE TITLE
Swagger replaces quotes with angled quotes in documentation

### ISSUE THREAD

**Issue by veqryn** [swagger-api/swagger-ui#5060]
In our documentation we have example curl calls and other things using single `'` and double `"` quotes.

For whatever reason, when Swagger pulls in this documentation it insists on replacing the quotes with single `‘’` and double `“”` angled quotes.

Here is an example of what it looks like:
![image](https://user-images.githubusercontent.com/1897829/49322768-b52f8c80-f4cf-11e8-8546-553a09f142a5.png)

This is a bug because when our users copy and paste these commands into their shell, they don't work because of the angled quotes.

We are using swagger docker image: `swaggerapi/swagger-ui:v3.19.3`

And it is the `API_URLS` environment variable to pull the swagger json from another url.

The contents of the swagger json start with:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "Foobar Service",
    "description": "\u003cbr\u003e\u003cp\u003eExample of a simple GET request via curl with bearer HTTP Authentication:\u003c/p\u003e\u003cpre\u003ecurl -X GET \"https://foobar.com/stuff\" -H \"Accept: application/json\" -H \"Authorization: Bearer abc123.xyz.789\"\u003c/pre\u003e",
    "version": "2.0"
  },
  "paths": {}
}
```

**Comment by hkosova** [comment]
Try using Markdown formatting instead of HTML tags. In Markdown, you can make code blocks by indenting the lines by four spaces or wrapping them in triple backticks ` ``` `.

JSON version:
```
"description": "Example of a simple request via curl:\n\n    curl -X POST \"https://api.foobar.com/stuff\" -H \"Accept: application/json\" -H \"Content-Type: application/json\" -d ''{}''",

or

"description": "Example of a simple request via curl:\n\n```curl -X POST \"https://api.foobar.com/stuff\" -H \"Accept: application/json\" -H \"Content-Type: application/json\" -d ''{}''```",
```

YAML version (to illustrate the original formatting):

```yaml
info:
  description: >-
    Example of a simple request via curl:

        curl -X POST "https://api.foobar.com/stuff" -H "Accept: application/json" -H "Content-Type: application/json" -d ''{}''

# or

info:
  description: >-
    Example of a simple request via curl:

    ```
    curl -X POST "https://api.foobar.com/stuff" -H "Accept: application/json" -H "Content-Type: application/json" -d ''{}''
    ```
```

**Comment by shockey** [comment]
Hi @veqryn, I'm not able to reproduce this.

Using this string as an input to Swagger UI:

```
{
  "swagger": "2.0",
  "info": {
    "title": "Foobar Service",
    "description": "\u003cp\u003eExample of a simple request via curl:\u003c/p\u003e\u003cpre\u003ecurl -X POST \"https://api.foobar.com/stuff\" -H \"Accept: application/json\" -H \"Content-Type: application/json\" -d '{}'\u003c/pre\u003e",
    "version": "1.0"
  }
}
```

in Chrome 70, all quotation-like marks that Swagger UI renders into the Info section are either U+0022 quotation marks or U+0027 apostrophes, according to this [Unicode character identifier](http://www.babelstone.co.uk/Unicode/whatisit.html).

Perhaps this is a browser bug? (You didn't fill out the information section of the template, so I don't know what you're using).

**Comment by shockey** [comment]
PS: you don't need to use escape codes to write HTML in your description, this will work fine:

```yaml
info:
  description: '<p>Example of a simple request via curl:</p><pre>curl -X POST "https://api.foobar.com/stuff" -H "Accept: application/json" -H "Content-Type: application/json" -d ''{}''</pre>'

```

But, as @hkosova mentioned, taking advantage of Markdown's readability is even better.

**Comment by veqryn** [comment]
@shockey Here is an easy reproducer:

1. Open http://editor.swagger.io/#edit
2. Delete all contents, then replace with:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "Foobar Service",
    "description": "\u003cbr\u003e\u003cp\u003eExample of a simple GET request via curl with bearer HTTP Authentication:\u003c/p\u003e\u003cpre\u003ecurl -X GET \"https://api.returnpath.com/v2/ecm/pixel_counts?start=2018-10-01T00%3A00%3A00Z\u0026end=2018-10-02T00%3A00%3A00Z\" -H \"Accept: application/json\" -H \"Authorization: Bearer abc123.xyz.789\"\u003c/pre\u003e",
    "version": "2.0"
  },
  "paths": {}
}
```

I see the quotes replaced every time I do this. Please let me know if you do not.

**Comment by shockey** [comment]
Fixed! Thanks for the help @veqryn 👍

**Comment by veqryn** [comment]
Thank you!
