### ISSUE TITLE
Required field not highlighted on click of Execute button (second time)

### ISSUE THREAD

**Issue by tnpradeep** [swagger-api/swagger-ui#5070]
Hello,

In recent version of swagger-ui, required parameter input field is not highlighted on click of execute button second time.

Steps to re-produce
1. Go to http://petstore.swagger.io/#/pet/getPetById
2. Click on Try it out
3. provide an empty space for petId field
4. Click on Execute, now the input field of petId is highlighted in red
5. Click on cancel
6. Click on Try it out
7. Click on Execute
Now the input field is not highlighted in red.

**Comment by shockey** [comment]
Confirmed.

Looks like the parameter validation is working as expected (don't allow the execution unless an integer value is provided) but it isn't being surfaced correctly once Try-It-Out mode is cycled.

**Comment by tim-lai** [comment]
resolved.
