### ISSUE TITLE
Free-form object with application/x-www-form-urlencoded not providing input field in Swagger UI

### ISSUE THREAD

**Issue by mileusna** [swagger-api/swagger-ui#5072]
- OS: MACOS
 - Browser: Safari, Chrome
 - Version: latest
 - Method of installation: web editor and swagger hub
 - Swagger-UI version: current editor on your site
 - Swagger/OpenAPI version: OpenAPI 3.0

I'm using so called "free form" objects in my posts. When I want to post with **application/x-www-form-urlencoded** with "free-form" object, your UI doesn't provide any form of input to insert "free-form" object. If the content-type is application/json then there is an input box to write down the object, but not with application/x-www-form-urlencoded.

<img width="615" alt="screen shot 2018-12-10 at 19 45 01" src="https://user-images.githubusercontent.com/4697935/49754166-aa39e080-fcb5-11e8-9138-745d22c3fb94.png">

Example Swagger/OpenAPI definition:
```yaml
openapi: "3.0.0"
info:
  description: "A sample API for "
  version: "1.0.0"
  title: "Sample"
  contact:
    name: ""
    url: "http://website.com"
    email: "admin@mail.com"
servers:
  - url: https://api.website.com/api
    description: Development server
paths:
  /objects:
    post:
      summary: Create/modify object
      operationId: postObject
      parameters:
        - name: filterParams
          in: query
          description: Additional filter fields
          required: false
          schema:
            type: object
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object  
      responses:
        '200':
          description: Status message
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Status'
components:
  schemas:
    Status:
      type: object
      properties:
        Error:
          description: Error information, if any
          type: object
          properties:
            Code:
              description: Error code
              type: integer
            Message:
              description: Error message
              type: string
        Success:
          description: Success message 
          type: object
          properties:
            Message:
              description: Success message
              type: string
```

**Comment by shockey** [comment]
This is a limitation on our part of the `application/x-www-form-urlencoded` form handling we have implemented - we expect `properties` to be defined and generate key/value pair inputs based on it.

**Comment by mileusna** [comment]
You can use free-form in body if the type is `application/json`. And if your API call supports both `application/json` and `application/x-www-form-urlencoded` you can actually "hack" the Swagger interface.

1) You select the `application/json` from drop down menu and it will ofer you to create free form object. Create your name/value object.
2) Switch back to `application/x-www-form-urlencoded`. The input field for free-form object will disappear. But nevermind that and click **Execute**.
3) Swagger will actually post your free-form object you have created with `application/json` as `application/x-www-form-urlencoded` with no problem.

So, the functionality is there, you just have to enable it, so we won't have to use tricks. ;)

**Comment by shockey** [comment]
Fixed 🙂 thanks for filing, @mileusna!
