### ISSUE TITLE
The provided definition does not specify a valid version field

### ISSUE THREAD

**Issue by jrean** [swagger-api/swagger-ui#5074]
- OS: macOS 10.12.6 (16G1510)
 - Browser: chrome
 - Version: 70.0.3538.110 (Official Build) (64-bit)
 - Method of installation: manual
 - Swagger-UI version: v3.18.3
 - Swagger/OpenAPI version: 3.0

Swagger/OpenAPI definition:
```yaml

openapi: "3.0.0"

servers:
  - url: 'https://domain.test/api/v1'
    description: Dev server

info:
  title: API
  description: API Documentation
  version: '1.0'

paths:
  /:
    get:
      responses:
        '200':
          description: OK

```

Swagger-UI configuration options:
```js

    <script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "{{ $ymlFileUrl }}",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
      // End Swagger UI call region

      window.ui = ui
    }
  </script>

```

When I hit the route serving Swagger-ui I have the following message displayed:

```
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match  openapi: 3.0.n (for example, openapi: 3.0.0).
```

When I test my definition on `https://editor.swagger.io` it is all good!

What am I missing?

Thank you,

J.

**Comment by jrean** [comment]
Solved. It was a pb of properly parsing and returning the definition file.

**Comment by sarangajay** [comment]
Hi jrean, could you lease explain your solution. I am having the same issue with springfox.

Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match  openapi: 3.0.n (for example, openapi: 3.0.0).

**Comment by armstronge975** [comment]
Hi @sarangajay! I just had this same error with Springfox and Swagger UI. I solved this by adding a few things to my **SwaggerConfig.java** file as specified in this [tutorial](https://springframework.guru/spring-boot-restful-api-documentation-with-swagger-2/). Once I added ```extends WebMvcConfigurationSupport``` to the class header and the ```@override``` method, the error went away.

**Comment by soarjon** [comment]
Hi @armstronge975, I tried to solve the problem following the tutorial suggested by you, but problem still occurs. @jrean Could you please explain you solution?

**Comment by shorif2000** [comment]
i have same problem but work fine in https://app.swaggerhub.com/

**Comment by bdzzaid** [comment]
I have the same issue when the server URL contains a server port (ex: http://myserver:80 or https://myserver:443).

I resolved all my url syntax and resolved the issue :-) 
```
openapi: 3.0.3
info:
...
servers:
  - url: 'here an invalid URL' ...
