### ISSUE TITLE
add the author key with @ApiOperation

### ISSUE THREAD

**Issue by zorkeAccount** [swagger-api/swagger-ui#5087]
i hope can have a key "author" in the @ApiOperation for showing the rest-api belong to whom of the teams

**Comment by shockey** [comment]
Hi @zorkeAccount, is this question related to Swagger UI? This project is unrelated to any annotation libraries 😄

**Comment by hkosova** [comment]
Assuming the question is about [Swagger Core](https://github.com/swagger-api/swagger-core) annotations - the author (`info.contact`) can be specified inside [`@OpenAPIDefinition`](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#OpenAPIDefinition) in Swagger Core v. 2.x or inside [`@SwaggerDefinition`](https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#swaggerdefinition) in v 1.5.
