### ISSUE TITLE
Enable $ref URLs to be "injected", "replaced", "variablized", or "parameterized" when rendered

### ISSUE THREAD

**Issue by autopulous** [swagger-api/swagger-ui#5098]
### Content & configuration

Swagger/OpenAPI definition:

Snippet from component **B** (which uses `$ref` to pull in `Options` from component **A**)

    components:
      schemas:
        Options:
          $ref: 'https://dev.A.example.com/sdk/openapi.yaml#/components/schemas/Options'

### Is your feature request related to a problem?

I am deploying _development_ and _production_ versions of an API. I am deploying the `openapi: 3.0.0` specification into a development environment and a production environment. As you would expect the development environment is frequently updated whereas the production environment is a bit slower to change.

I am deploying `openapi: 3.0.0` specifications for _development_ and _production_ to different URLs (something similar to `https://dev.A.api.example.com` for _development_ and `https://A.api.example.com` for _production_ for an API named **A**). I wouldn't have a problem if the `openapi: 3.0.0` specification for API **A** didn't `$ref` API **B**'s `openapi: 3.0.0` specification to include bubble up functionality from API **A** into API **B** (e.g. API **B** is dependent upon API **A** and needs to expose some of the functionality of API **A**)... Because the URL within a `$ref` is fixed, I have to hard code the URL (which for the moment I'm using the _production_ URL `https://A.api.example.com` which for _development_ when API **B** `$ref` is rendered it shows the _production_ version of API **A** (which is wrong from the perspective of the _development_ version of the API).

### Describe the solution you'd like

I'd like a way to parameterize the URL used for `$ref` perhaps with a `base $ref URL` or a substitution using curly braced identifier... it would also be nice to be able to use this same variable for the URLs in places such as `info` -> `license` -> `url` and `info` -> `termsOfService`...

### Describe alternatives you've considered

Forcing the build/deploy process to replace the URL according to a pattern whereas the URLs are defined for the _development_ environment (e.g. `https://dev.A.api.example.com`) and then altered for _production_ (e.g. `https://A.api.example.com`)

### Additional context

Perhaps there's a mechanism that already exists to facilitate what I'm trying to achieve... or perhaps I'm trying to achieve something for which there is a better approach...

**Comment by shockey** [comment]
> Perhaps there's a mechanism that already exists to facilitate what I'm trying to achieve

There is 😉 

I see two options here... you can either use relative URLs in your ref values (e.g. `$ref: "./other-file.yamll#/components/schemas/Options"`) which will be resolved relative to your main definition's location, or use Swagger UI's [`requestInterceptor` option](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#requestinterceptor) to modify outgoing request URLs in different environments to send requests for remote definitions to the correct URL.

**Comment by autopulous** [comment]
Thanks for the suggestion - I have it working now... 

    function httpGetAsync(url, callback) {
        let xmlHttp = new XMLHttpRequest();

        xmlHttp.onreadystatechange = function () {
            if (xmlHttp.readyState === 4 && xmlHttp.status === 200)
                callback(xmlHttp.responseText);
        };

        xmlHttp.open("GET", url, true);
        xmlHttp.send(null);
    }

    const jsYAML = require('js-yaml');

    function parseYamlSpec(yaml) {
        try {
            return jsYAML.safeLoad(yaml);
        } catch (error) {
            console.error('Error parsing OpenAPI YAML to JavaScript object');
            console.error(error);
            return null;
        }
    }

    function interceptRequest(request) {
        const URL_PARSER = /^(.*?[\/]{2})([^0-9].*?\.)?(.*)$/;

        let source = request.url.match(URL_PARSER);
        let deployed = window.location.href.match(URL_PARSER);

        request.url = source[1] + (undefined !== deployed[2] ? deployed[2] : "") + source[3];

        return request;
    }
    
    const SwaggerUI = require('swagger-ui');
    
    function displayOpenApiSpec() {
        httpGetAsync('./openapi.yaml', function (yamlSpec) {
            SwaggerUI({
                dom_id: '#openapi',
                spec: parseYamlSpec(yamlSpec),
                requestInterceptor: interceptRequest
            })
        });
    }

    displayOpenApiSpec();
