### ISSUE TITLE
Encoding is not exploding a array property in requestBody in swagger-ui.

### ISSUE THREAD

**Issue by knobik** [swagger-api/swagger-ui#5106]
### Q&A (please complete the following information)
 - OS: ubuntu
 - Browser: chrome
 - Version: 71.0.3578.98 (Official Build) (64-bit)
 - Method of installation: composer
 - Swagger-UI version: 3.18.3
 - Swagger/OpenAPI version: OpenApi 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
paths:
  /match/started:
    post:
      tags:
        - match
      summary: 'Callback for when a game has started.'
      operationId: 'App\Http\Controllers\Api\V1\MatchController::started'
      requestBody:
        description: 'Something something batman!'
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - match_uuid
              properties:
                game_uuid:
                  type: string
                'player_uuids[]':
                  type: array
                  items:
                    type: string
              type: object
            encoding:
              'player_uuids[]':
                style: form
                explode: true
      responses:
        200:
          description: 'success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api_V1_Match_Started'
```

Swagger-UI configuration options:
```js
const ui = SwaggerUIBundle({
    dom_id: '#swagger-ui',

    url: "http://matchmaking.test/docs/api-docs.json",
    operationsSorter: null,
    configUrl: null,
    validatorUrl: null,
    oauth2RedirectUrl: "http://matchmaking.test/api/oauth2-callback",

    requestInterceptor: function() {
      this.headers['X-CSRF-TOKEN'] = '';
      return this;h
    },

    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],

    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],

    layout: "StandaloneLayout"
  })
```

### Screenshots
![screenshot from 2019-01-04 10-11-56](https://user-images.githubusercontent.com/795254/50680925-cd805300-1009-11e9-95c7-d57b4d422c76.png)

### How can we help?
Encoding is not exploding a array property in requestBody in swagger-ui.
Im getting this command for curl:
```bash
curl -X POST "https://editor.swagger.io/api/v1/match/started" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "game_uuid=test" -F "player_uuids[]=aaa,bbb,ccc"
```

notice this part:
`-F "player_uuids=aaa,bbb,ccc"`

im trying to get this result
`-F "player_uuids[]=aaa" -F "player_uuids[]=bbb" -F "player_uuids[]=ccc"`

**Comment by paul-lysak** [comment]
Observing same behavior with Swagger UI 3.20.3. Here is our request definition:

      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
              properties:
                param1:
                  type: array
                  items:
                    type: string
            encoding:
              param1:
                style: form
                explode: true
 
Both the request sent by SwaggerUI to the server and the generated curl command have `param1` values comma-separated in the same parameter rather then sending them in multiple parameters with the same name.

**Comment by paul-lysak** [comment]
Formally correct, but neither does OpenAPI spec says that array property values must be comma-separated. And such behavior is inconsistent with the handling of multiple files upload through multipart requests.

**Comment by shockey** [comment]
Closing as a duplicate - `Parameter.encoding` is not currently supported, and is being tracked in https://github.com/swagger-api/swagger-ui/issues/3641 (soon to have its own ticket, but in backlog for now).
