### ISSUE TITLE
How to activate "withCredentials: true" support from "swagger-js"

### ISSUE THREAD

**Issue by dalbani** [swagger-api/swagger-ui#5126]
Hi,

Thanks to the code landed in https://github.com/swagger-api/swagger-js/pull/1189, `swagger-js` is now capable of sending credentials (i.e. cookies) within XHR requests in a CORS context.
[The documentation](https://github.com/swagger-api/swagger-js#in-browser) mentions to use the following construct:
```javascript
SwaggerClient.http.withCredentials = true; // this activates CORS, if necessary
```
But it's not clear to me how to set this flag with SwaggerUI, in particular when using with the `SwaggerUIBundle` class as shown on https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L41?

Thanks!

**Comment by Yloganathan** [comment]
I have the same question. For now, I got it to work using requestInterceptor

```
const ui = SwaggerUIBundle({
        url: "https://petstore.swagger.io/v2/swagger.json",
        dom_id: '#swagger-ui',
        requestInterceptor:
          (request) => {
            request.credentials = 'include'
            return request;
          },
        ...
      })
```
