### ISSUE TITLE
'allowEmptyValue' doesn't work if parameter is 'required'.

### ISSUE THREAD

**Issue by mkrup** [swagger-api/swagger-ui#5129]
Swagger UI version is 3.20.5.
I expect that everything should work as in https://github.com/swagger-api/swagger-ui/issues/1934 in the described case but it doesn't.
Swagger UI does not allow to send a request when 'required' parameter is also 'allowEmptyValue'.

**Comment by shockey** [comment]
Regression confirmed:

```yaml
openapi: "3.0.0"

paths:
  /:
    get:
      parameters: 
      - name: one
        in: query
        allowEmptyValue: true
        required: true
        schema:
          type: string
      responses:
        200:
          description: ok
```

PS: @mkrup, please follow the issue template next time 😄

**Comment by shockey** [comment]
thanks for the report, @mkrup!

**Comment by mkrup** [comment]
Great, thank you!
