### ISSUE TITLE
swagger ui doesn't send POST params

### ISSUE THREAD

**Issue by PavloPoliakov** [swagger-api/swagger-ui#513]
Hi,

Here is how swagger ui see my API description:
![image](https://cloud.githubusercontent.com/assets/839290/3787817/ba3fd828-1a37-11e4-9d17-6b577630fba6.png)

And this is what it sends:
![image](https://cloud.githubusercontent.com/assets/839290/3787818/d13001de-1a37-11e4-820a-74dd9cf53f7a.png)

As you see - no params were sent.

Ant thoughts?

**Comment by owaiskhalid95** [comment]
> @fehguy
> 
> I've started experience the issue after I've updated the swagger-ui todays morning.
> 
> I've just updated it once again, both *.js libs from the dist folder. But the issue still takes the place as I think:
> ![image](https://cloud.githubusercontent.com/assets/839290/3788532/a0c443ba-1a6a-11e4-8c44-2cb6927c651d.png)
> 
> As you see - no payload still.

can you please share the payload how you passed it in swagger?

**Comment by webron** [comment]
@owaiskhalid95 this issue relates to an ancient version of Swagger UI which is no longer supported, and is in no way similar to the current version of Swagger UI. If you need assistance, please file a new ticket and follow the issue template.
