### ISSUE TITLE
Authorization header not send

### ISSUE THREAD

**Issue by OlafvdSpek** [swagger-api/swagger-ui#5131]
- OS: Windows 7
 - Browser: Chrome 71
 - Method of installation: git clone, composer update
 - Swagger-UI version: master? Where is this shown?
 - Swagger/OpenAPI version: Swagger 2.0

The Authorize button shows up, I can enter the value but the header is never send.. I read somewhere the definition needs to indicate security is required but how do I handle requests that can be done both with and without security?
Can't Swagger UI always send the header when the Authorization is set via the button?

```
"securityDefinitions":{  
   "ApiKeyAuth":{  
      "type":"apiKey",
      "in":"header",
      "name":"X-API-Key"
   },
   "Bearer":{  
      "type":"apiKey",
      "name":"Authorization",
      "in":"header"
   }
},
```

```
GET /v2/config HTTP/1.1
Host: example.com
Connection: keep-alive
accept: application/json
DNT: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7
```

**Comment by OlafvdSpek** [comment]
Somebody?

**Comment by IkerZamora** [comment]
I'm having the same issue.

**Comment by IkerZamora** [comment]
I solved the issue by adding a "security" section to each route.

```
"paths": {
    "/mypath": {
      "get": {
        "parameters": [ ],
        "description": "",
        "responses": {
          "200": {
            "description": "An array of Objects"
          }
        },
        "operationId": "getSomething",
        "security": [
          {
            "ApiKeyAuth": []
          }
        ]
      }
    }
  }
```

**Comment by OlafvdSpek** [comment]
@shockey I think it should be "type: feature request".

**Comment by Wizkaley** [comment]
Did anybody get this working?

**Comment by hkosova** [comment]
`securityDefinitions` alone is not enough, you also need to add `security` to individual operations or globally.
[Authentication - OpenAPI 3.0](https://swagger.io/docs/specification/authentication/)
[Authentication - OpenAPI 2.0](https://swagger.io/docs/specification/2-0/authentication/)

**Comment by OlafvdSpek** [comment]
Can't Swagger UI always send the header when the Authorization is set via the button?

**Comment by hkosova** [comment]
@OlafvdSpek it will be sent - if your API definition properly applies `security` as required by the OpenAPI Specification.

**Comment by OlafvdSpek** [comment]
1. Why can't it send it if the user entered it but the API definition doesn't specify `security`?
2. How does one specify authorization as optional?

**Comment by hkosova** [comment]
@OlafvdSpek 

1. Please read the OpenAPI Specification. `securityDefinitions` describes the _type_ of the security scheme whereas `security` _applies_ one or more security schemes to operations, specifies which OAuth scopes each operation uses, etc.

2. Add `{}` to the `security` list:
```
security:
- {}
- mySecurityScheme: []
```
