### ISSUE TITLE
Latest release is not available on packagist.org

### ISSUE THREAD

**Issue by weirdan** [swagger-api/swagger-ui#5136]
### Q&A (please complete the following information)
 - Method of installation: composer
 - Swagger-UI version: v3.20.5

### Screenshots
![image](https://user-images.githubusercontent.com/57403/51744597-0790c200-20a9-11e9-8e00-5a07ef9e6ae6.png)
![image](https://user-images.githubusercontent.com/57403/51744645-28591780-20a9-11e9-9d45-3042e9e8ba89.png)

### How can we help?
Currently packagist.org page for SwaggerUI lists 3.20.4 as the latest version available, even though there's a newer release on Github. Please check composer/github integration, and trigger the update manually if necessary.

**Comment by shockey** [comment]
Looks like we were on a legacy GitHub API with Packagist, which meant our updates stopped going out in the new year.

Good news: this is fixed! Packagist is up to date, and will be kept up to date automatically going forward.

See https://jenkins.swagger.io/view/OSS%20-%20JavaScript%20Automated%20Releases/job/oss-swagger-api-packagist-trigger/ for more context.

Thanks for reporting this, @weirdan!
