### ISSUE TITLE
Docker image with `URLS` defined still show pet shop

### ISSUE THREAD

**Issue by JbIPS** [swagger-api/swagger-ui#5138]
Hi,

I'm setting up a Docker container with Swagger-ui using a volume and the `URLS` envar to use multiple files: 
```env
URLS=[{url: "/swagger/file1.yml", name: "file1"}, {url: "/swagger/file2.yml", name: "file2"}]
```
But each time I refresh, even with `DEEP_LINKS=true`, I get the pet shop API printed. I have to select another definition in the TopBar and go back to the first one to see it.

Did I miss a parameter somewhere ?

Thank you

**Comment by g-stawarczyk** [comment]
Hi.

You missed URL parameter. Set `URL` to empty string:
```
URL=''
```

If you're using docker, just add an env property `-e URL=''`

**Comment by JbIPS** [comment]
Thank you, I didn't know it was mandatory when using URLS

**Comment by shockey** [comment]
Reopening this to investigate a bit - perhaps we should be ignoring `url` in the UI itself when `urls` is defined.

**Comment by JbIPS** [comment]
Thank you 😃
