### ISSUE TITLE
Support for @APIParam ( secret="true" )

### ISSUE THREAD

**Issue by vijayansrinivasan** [swagger-api/swagger-ui#514]
Some of the form parameters can be a secret (e.g. password, credit card number, CVV number etc.,)
Need a way to indicate swagger-ui that the form element has to be password

**Comment by fehguy** [comment]
We will support the following with 2.0 specs:

```json
{
   "type": "string",
   "format": "password"
}
```

**Comment by fehguy** [comment]
also see here:  https://github.com/swagger-api/swagger-js/issues/219

**Comment by fehguy** [comment]
the `password` format has been added in https://github.com/swagger-api/swagger-ui/commit/b1efe883db9c44ce119631665fe4efe680d6db86
