### ISSUE TITLE
Repetition of controller methods

### ISSUE THREAD

**Issue by matheusjordan** [swagger-api/swagger-ui#5140]
Hi, I encountered the following problem while documenting my API. The methods of a controller are being repeated (see image below).

![image](https://user-images.githubusercontent.com/43014010/51836881-80c62a00-22e0-11e9-9ba1-019d5d973dc3.png)

My pom file
`
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>`

I still have not found the solution to this problem but if any of you have been through this or solved the problem, please leave your comment as possible!

my project with Swagger Repo link: https://github.com/matheusjordan/syspadara

**Comment by shockey** [comment]
Hi @matheusjordan, I believe your problem has to do with the library you're using to generate your OpenAPI document (i.e., Springfox). Swagger UI just displays what your document describes, so this is probably a Swagger generator bug on their side 😄
