### ISSUE TITLE
Add possibility to change baseUrl (host) on swagger UI

### ISSUE THREAD

**Issue by nikita-clearscale** [swagger-api/swagger-ui#5143]
**feature requst**

The idea of swagger that it already contains host or base url. So user can open `http://localhost:8080/swagger-ui.html` and send request to this server. But this is not a case for private API which should not show all endpoint in single place. In such situations swagger json generated and served from test / dev servers but not in production or stagging environment. (which is close to production)

What if swagger team add a button with ability to change host on UI? In this case I as developer can generate swagger json locally and send request to any other server. And any tester can also visit test /dev server and send requests from it. This very helpful not only for private API testing but in situations when same application deployed to multiple servers - user performs request to original server and can reply this with other and see difference.

![image](https://user-images.githubusercontent.com/26218826/51961582-caa14280-248f-11e9-8916-f99035234e39.png)

**Comment by shockey** [comment]
Thanks for opening an issue, @nikita-clearscale.

This looks pretty similar to https://github.com/swagger-api/swagger-ui/issues/4735, so I'm going to close this in favor of it. When we work on that issue, we'll take another look here and keep your use case and suggestions in mind!
