### ISSUE TITLE
Add username/passwoord to bearer/apiKey authorization

### ISSUE THREAD

**Issue by Bykiev** [swagger-api/swagger-ui#5146]
Hello, I have an issue with the auth process. Everything is working fine if I'll specify the bearer token explicitly, but I want a way to specifiy username, password and ClienId, then get a bearer token and include it in all requests.

I tried to use OAuth, I was able to authorize, but bearer token is not adding to each request. More over, if i press auth on method available authorizations are empty. What's wrong?

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
