### ISSUE TITLE
Display static documentation information for multipart properties

### ISSUE THREAD

**Issue by RichieLoco** [swagger-api/swagger-ui#5164]
Using Swagger-UI v3.20.2, we have noticed that when using multi-part/formdata for the request body, that it won't render any of it at all when selecting the "Try it out" feature.  See screenshot below:
![v3 20 3_multipart_tryitout](https://user-images.githubusercontent.com/1975233/52423004-218dc400-2aef-11e9-9b1a-4926e7bd9781.png)
Whilst in v3.16.0, which I believe was when multipart support was added for OA3 specs, we were able to see that it rendered the section:
![v3 16 0_multipart_tryitout](https://user-images.githubusercontent.com/1975233/52423144-66b1f600-2aef-11e9-8b75-a35fc330bcfe.png)
The issue with us choosing to use v3.16.0 instead of the later v3.20.3 was that the latter fixed a separate issue which was present in earlier versions.  Attached sample snippet of request body: 
[v3.20.3_multipart_snippet.txt](https://github.com/swagger-api/swagger-ui/files/2841616/v3.20.3_multipart_snippet.txt)

Please assist.  Many thanks.
Rich

**Comment by shockey** [comment]
Hi @RichieLoco, this sounds like a rather serious issue but I'm unable to reproduce this.

Here's what I see in Try-It-Out mode in the latest version of Swagger UI:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/680248/52426826-56d0ec80-2ac4-11e9-98c7-cc1eb79aa7b7.png">

The JSON sample is funky (I'll look into that), but the inputs are definitely rendering.

**Comment by RichieLoco** [comment]
Hey @shockey - apologies but I fudged up this post.  You're right, the above appears fine (well, the same as yours does) via "Try it out" feature.  It doesn't render when **not** using that feature... so, if you view the spec in UI without clicking "Try it out" when checking the request body you will not see the json body or file selectors render. Please see the full spec: 
[v3.20.2_multipart_snippet.txt](https://github.com/swagger-api/swagger-ui/files/2841950/v3.20.2_multipart_snippet.txt)

**Comment by shockey** [comment]
@RichieLoco, no worries! For now this is intended behavior - we only show inputs when Try-It-Out is active, to avoid confusion on what the input actually does. We'd be happy to consider a PR that changes how we approach this: for example, a PR that reuses the Model/Example view that actual parameters get.

As for the `OrderedMap` example madness: I've fixed that in #5166, which should ship tomorrow evening. Your examples should display like this going forward:

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/680248/52444342-ab3c9200-2aed-11e9-99ac-ce1ec1ddc839.png">

**Comment by shockey** [comment]
@RichieLoco, proposing that we change the title here to **Display static documentation information for multipart properties** and file it as a feature ticket.

Let me know if that doesn't make sense to you, or misses what you're asking for 😄

**Comment by RichieLoco** [comment]
Ahhh ok, thinking about it makes complete sense now as the user might assume that they can try it out but they wouldn't be able to outside of "Try it out" feature.  I can maybe take a stab at it and submit a PR but I'd have to familiarise myself with the codebase first :)  Thanks for the quick fix on the OrderedMap though!

I will change the title as you mentioned as I misinterpreted this as a bug when it wasn't :) Thanks again.
