### ISSUE TITLE
Swagger UI path variables are broken on react 16+

### ISSUE THREAD

**Issue by iKrushYou** [swagger-api/swagger-ui#5165]
I'm running into an issue with swagger path parameters when serving through react versions greater than 16 (i'm not 100% sure exactly when it stopped working, but i have tested between versions `15.4.1` => `16.4.1` and I can get it working on the former.

I am using the very basic of set ups for my control test -- the petstore.json example (contained inside of the const `spec`)

and here is my App.js
```
class App extends Component {
  componentDidMount() {
      SwaggerUi({
          dom_id: "#swagger-ui",
          spec: spec,
          presets: [presets.apis]
      })
  }

  render() {
    return (
      <div className="App">
        <h1>Swagger Test</h1>
          <div>React version: {REACT_VERSION}</div>
            <div>Swagger version: {SWAGGER_VERSION}</div>
        <div id={"swagger-ui"} />
      </div>
    );
  }
}
```

When trying to make a call through the UI which requires a path variable, the UI acts as if the field wasn't filled in:
![image](https://user-images.githubusercontent.com/1500721/52428180-791c3780-2acf-11e9-9197-28881137ca98.png)
However, that same API test works in React version `15.4.1`. I am not sure what would be causing it and why it's related to the React versions.. but it is quite frustrating. 

Any suggestions or workarounds?

**Comment by shockey** [comment]
Hi @iKrushYou, this is (unfortunately) a known issue, folks are seeing weirdness with React 16 usage (see [`epic: usage in react@16`](https://github.com/swagger-api/swagger-ui/issues?q=is%3Aopen+is%3Aissue+label%3A%22epic%3A+usage+in+react%4016%22)), and parameter inputs seems to be a hotspot for problems.

I'm going to be working on this in the near future - if you'd be open to trying an early seed of what I come up with, email me (address in profile) and I'll be in touch!

**Comment by rfauglas** [comment]
I bumped into the issue... Any advances?  Any way I can help?

**Comment by shockey** [comment]
Hey @iKrushYou - as we discussed over email, using [`swagger-ui-react`](https://www.npmjs.com/package/swagger-ui-react) has solved your issue.

Thanks for all the help!
