### ISSUE TITLE
File Upload for application/octet-stream ZIP file

### ISSUE THREAD

**Issue by melloware** [swagger-api/swagger-ui#5167]
### Q&A (please complete the following information)
 - OS: ALL
 - Browser: ALL
 - Version: Github MASTER
 - Swagger-UI version: LATEST
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Java JAX-RS Definition:
```java
   @ApiOperation(value = "Upload my ZIP", response = String.class)
   @PUT
   @Path("/zipfile")
   @Produces(MediaType.TEXT_PLAIN)
   @Consumes(MediaType.APPLICATION_OCTET_STREAM)
   public Response putZipFile(final InputStream zipStream) {
```

### Screenshots
Put Operation that I want to upload a ZIP File
![image](https://user-images.githubusercontent.com/4399574/52442390-f86e3300-2af0-11e9-8ad7-7bc3783afb51.png)

### How can we help?
I wonder if its possible or if I am doing something wrong but I would like the Swagger UI to offer me a file upload button so I can pick a zip file to upload.  I have seen similar issues here where it allows application/octet-steam to be uploaded for images etc?  Is there something else I need in my ApiOperation?  Or is this something I need to submit a patch for?

**Comment by shockey** [comment]
Hi @melloware!

> I wonder if its possible or if I am doing something wrong but I would like the Swagger UI to offer me a file upload button so I can pick a zip file to upload.

Unfortunately, you won't be able to do this with `application/octet-steam`... Swagger 2.0 only supports file upload via `multipart/form-data` (docs [here](https://swagger.io/docs/specification/2-0/file-upload/)). 

> I have seen similar issues here where it allows application/octet-steam to be uploaded for images etc

These examples were achieved with OpenAPI 3.0, which allows file upload with any media type (docs [here](https://swagger.io/docs/specification/describing-request-body/file-upload/)). The best thing to do would be to upgrade to OpenAPI 3.0, but I'm not sure if the annotation library you're using supports this 🤔

**Comment by melloware** [comment]
@shockey that helps me.  I believe I can upgrade to OpenAPI 3.0.  I will attempt that.   Thanks for pointing me in the right direction.
