### ISSUE TITLE
How to change base url of the swagger UI in spring boot project

### ISSUE THREAD

**Issue by foxivolunteer** [swagger-api/swagger-ui#5174]
I have a spring boot project which is running under `http://localhost:8080/`
I added swagger config file.

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {
	
	@Autowired
	private ServletContext context;
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2)
				.host("localhost")
				.pathProvider(new RelativePathProvider(context) {
					@Override
			        public String getApplicationBasePath() {
			            return "/test";
			        }
				});
	}
}
```

I tried to set default path to `http://localhost:8080/test/swagger-ui.html`
unfortunatly it is still running under `http://localhost:8080/swagger-ui.html`.

I cannot use the `server.contextPath=/test` because it will change all endpoints.

after this modification, the info of the base url which is shown on the start page looks correct

`[ Base URL: localhost/test ]`

but the actual path is still `http://localhost:8080/swagger-ui.html`.

do you have an idea?

this is my dependencies

```
<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>
```

**Comment by shockey** [comment]
Hi @foxivolunteer,

Sounds like your question pertains to Springfox routing, not Swagger UI. Please ask your question over at Springfox 😄
