### ISSUE TITLE
Required parameter in requestBody doesn't block request from executing.

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#5181]
### Q&A (please complete the following information)
 - OS: Linux Mint 18.1
 - Browser: Firefox 
 - Version: 66.07b
 - Method of installation: editor.swagger.io
 - Swagger-UI version: version: "3.20.7", gitRevision: "g3434312c"
 - Swagger/OpenAPI version:OpenAPI 3.0

### Content & configuration
Standard http://editor.swagger.io set up

Example Swagger/OpenAPI definition:
```yaml
info:
  title: Required parameter missing, doesn't block request from executing.
  version: '1'
openapi: 3.0.0
servers: 
- url: http://httpbin.org/anything
paths:
  /foos:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                foo:
                  type: string
              required:
                - foo
              type: object
        required: true # Note this doesn't have an impact
      responses:
        default:
          description: ok
```

### Describe the bug you're encountering
Levaing the `foo` parameter empty, I'm still able to execute the request. Even though the `foo` field is required ( and the UI shows it as required ).

### To reproduce...

1. Click on Try-it-out
2. Click on execute ( leaving the form empty )

### Expected behavior
The form input "shakes", indicating that its a missing and required field.

### Screenshots
![image](https://user-images.githubusercontent.com/8438485/52784548-2528ca00-305e-11e9-8b4c-c110e227413d.png)

### Additional context or thoughts
I think the validateParams reducer doesn't consider requestBody fields.
We may need to consider both the `required` on the requestBody _AND_ the `required` inside each requestBody field.

**Comment by shockey** [comment]
Related: https://github.com/swagger-api/swagger-ui/issues/4899

**Comment by vinaylondhe-highspot** [comment]
The fix for this issue has not been merged yet, right? Because I see the same behavior as @ponelat mentioned above

**Comment by tim-lai** [comment]
@vinaylondhe-highspot Thanks for the the confirmation in latest distribution. We haven't received a contribution PR that would fix this issue.

**Comment by tim-lai** [comment]
Re-labeling this issue as a Feature Request. SwaggerUI does not currently validate OAS3 `requestBodies` or anything that might be inside of `requestBodies`.
