### ISSUE TITLE
No API definition provided. 

### ISSUE THREAD

**Issue by goben2489** [swagger-api/swagger-ui#5186]
### Q&A (please complete the following information)
 - OS: MacOS
 - Browser: Chorme 
 - Version: Version 72.0.3626.109 
 - Method of installation: dist
 - Swagger-UI version: v3.9.3
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
To day i cant fetch json file with swagger-ui

Example Swagger/OpenAPI definition:
I use content of PetStore paste to file json but can not work

### To reproduce...

1. Go to https://petstore.swagger.io/
2. Enable CORS extention chorme
3. enter url file json to url bar
4. Click Explore
5. Show errror No API definition provided.

### Expected behavior

1. I has check syntax with swagger editor has no bug
2. swagger editor can parse my json 

### Screenshots

<img width="1322" alt="screen shot 2019-02-18 at 12 38 23 pm" src="https://user-images.githubusercontent.com/14970253/52930213-27e73000-337a-11e9-95d7-3ee240054b99.png">

**Comment by shockey** [comment]
> 3\. enter url file json to url bar

@goben2489, what URL are you using? Kinda hard to reproduce this without it 😄
