### ISSUE TITLE
Using same path parameter twice is not working 

### ISSUE THREAD

**Issue by smiljana95** [swagger-api/swagger-ui#5187]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Mozilla Firefox, Google Chrome
 - Method of installation: sbt
 - Swagger-UI version: 3.20.5
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```json
"/{key}/{key}.json": {
...
"parameters": [
                    {
                        "in": "path",
                        "description": "Key",
                        "name": "key",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "123"
                        }
                    }
]
```

Swagger-UI configuration options:
```js
SwaggerUI({
        url: url,
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
})
```

### Screenshots
![screenshot from 2019-02-19 16-23-32](https://user-images.githubusercontent.com/33291508/53026217-c484fd00-3462-11e9-87bb-0224f0971d3f.png)

### How can we help?
After upgrading from Swagger 2.0 to OpenAPI 3.0 using the same path parameters twice in the same url isn't working since second parameter isn't resolved. Only the first appearance of the parameter is resolved. (Is there a way to use the same path parameter more than one time?

**Comment by shockey** [comment]
@smiljana95 this will be fixed in the next release of Swagger UI 😄 sorry for the inconvenience!

**Comment by smiljana95** [comment]
@shockey Thank you! No problem. :)
