### ISSUE TITLE
Adding example to multiple schemas

### ISSUE THREAD

**Issue by AlexWehe** [swagger-api/swagger-ui#5195]
- OS: macOS
 - Swagger-UI version: 3.X
 - Swagger/OpenAPI version: 3.0.2

### Content & configuration

Swagger/OpenAPI definition:
```yaml
post:
      security:
        - AppToken: []
      requestBody:
        description: Could recive one of the avaible schemas
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/UserTokenCreationQuery'
                - $ref: '#/components/schemas/AppTokenCreationQuery'
```

### How can we help?

Hi!! I would like to know if there any way to create an example value per schema and show it in the UI of swagger. I'm trying including the `examples` property and passing two diferents values per schema but it doesn't work.

Thank you!!

**Comment by Ibrahimtrrc** [comment]
The problem is with oneOf ... it's not yet supported there is an issue on it I think it's a duplicate of #3803

**Comment by shockey** [comment]
Closing as a duplicate of #3803 😄
