### ISSUE TITLE
custom objectMapper enableDefaultTyping error

### ISSUE THREAD

**Issue by jdgamache** [swagger-api/swagger-ui#5198]
### Q&A (please complete the following information)
 - OS: windows
 - Browser: chrome
 - Version: 72
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 2.9.2
- Sping-boot version: 2.0.3

Hello, 

when I customize my objectMapper with enableDefaultTyping, the swagger-ui stops working. 

	@Bean
	@Primary
	public ObjectMapper objectMapper() {
		ObjectMapper mapper = new ObjectMapper();
		Jackson2ObjectMapperBuilder.json().configure(mapper);
		
		mapper.setSerializationInclusion(Include.NON_NULL);
		mapper.registerModule(new JavaTimeModule());
		mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
		
                // If I comment this line, swagger-ui starts, with no problem
		mapper.enableDefaultTyping(DefaultTyping.NON_FINAL, JsonTypeInfo.As.WRAPPER_OBJECT);
		
		return mapper;
	}

![image](https://user-images.githubusercontent.com/1706900/53515440-ff58e780-3a97-11e9-8030-e841d216eda4.png)

**Comment by shockey** [comment]
Hi @jdgamache, that message isn't coming from Swagger UI - please open an issue with whatever Java project you're using to embed Swagger UI!
