### ISSUE TITLE
Is it possible to dynamically generate apis based on existing apis via plugins?

### ISSUE THREAD

**Issue by lindaosong** [swagger-api/swagger-ui#5204]
As the title, for example, I have an interface now.

`@ApiOperation(value = "get model info by type")
   @GetMapping("/model/{objectClass}")
    public RestResult getModelInfo(@PathVariable Integer objectClass) {
        return resourceFeignClient.getModel(objectClass);
    }`

If I pass in the parameter "1", it means to get the model "apple"; the parameter "2" is passed, which means to get the model "orange". I want to automatically generate api "/model/apple" and "model/orange" corresponding to "/model/1" and "model/2" through custom plugin rules. I don't know if my idea is currently feasible.

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
