### ISSUE TITLE
Update packagist (composer) version

### ISSUE THREAD

**Issue by Adapik** [swagger-api/swagger-ui#5206]
Please, add the latest version to packagist.org and/or enable auto-update:
https://packagist.org/packages/swagger-api/swagger-ui

**Comment by shockey** [comment]
Indeed, looks like our automated job for this failed during the v3.20.9 release: https://jenkins.swagger.io/job/oss-swagger-api-packagist-trigger/3/console

**Comment by shockey** [comment]
Okay, I ran our job again without modifications and it worked - seems like it was an intermittent issue on Packagist's side. v3.20.9 is available now.

I've modified our job to fail when we get a non-OK status code back from the API call, which should alert us about any future issues.

Thanks for reporting this, @Adapik!
