### ISSUE TITLE
Declare schema for JObject

### ISSUE THREAD

**Issue by jasonlaw** [swagger-api/swagger-ui#5209]
Hi, 
I am using ASP.Net Core 2.2. 
Suppose I have a REST api with a JObject type parameter, is there a way to define the schema on the api so that swagger will know how to display it with full schema?
Thanks in advance.

**Comment by shockey** [comment]
@jasonlaw, I'm not familiar with JObjects, but you can always describe an object using JSON Schema and parse it into whatever representation you need in your server.

If you're using an annotation library, you'd need to ask this question in that library's repository.
