### ISSUE TITLE
No Authorize button when using scala-play2

### ISSUE THREAD

**Issue by camomileann** [swagger-api/swagger-ui#5212]
Dear Sir/Madam,

please help to find what's the reason for "authorize" button not showing up.
I'm using `swagger-play2 1.6.0` dependency.
I configure Swagger UI like this:

`window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "http://localhost:9000/swagger",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
      // requestInterceptor: function(request) {
        //   request.headers.Authorization = "Bearer " + key;
        //   return request;
        // },
        requestInterceptor: function (req) {
          req.headers = {
            "Authorization": "Bearer " + document.getElementById("atoken").value
            , "Accept": "application/json",
            "Content-Type": "application/json"
          };
          return req;
        },
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout",

      })`

I try to configure authorization via swagger annotations like this:
`@Api(value = "someValue", authorizations = Array(
  new Authorization(value = "apiKey", scopes = Array())))
class MyController @Inject() (`

**Comment by shockey** [comment]
@camomileann, can you provide me with your Swagger/OpenAPI document?

**Comment by camomileann** [comment]
Hi shockey,
yes, I can. The important thing that this document is generated automatically, I use annotations in my scala classes.
		{
		swagger: "2.0",
		info:  {
		version: "beta",
		title: "",
		contact:  {
		name: ""
		},
		license:  {
		name: "",
		url: "http://licenseUrl"
		}
		},
		host: "localhost:9000",
		basePath: "/",
		tags:  [
		 {
		name: “mum”
		},
		 {
		name: “mr”
		},
		
		 {
		name: "whitelist"
		},
				 {
		name: "admin"
		}
		],
		paths:  {
		/mum/{prog}/cv:  {
		get:  {
		tags:  [
		“mum”
		],
		summary: “…”,
		description: "",
		operationId: “cv”,
		parameters:  [
		 {
		name: "prog",
		in: "path",
		description: “…”,
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which update information must be obtained.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "[deprecated] Specifies the VIN for which update information must be obtained.",
		required: false,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: “…”,
		schema:  {
		$ref: "#/definitions/CvResponse"
		}
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		},
		security:  [
		 {
		apiKey: [ ]
		}
		]
		}
		},
		
		/drm:  {
		get:  {
		tags:  [
		“mr”
		],
		summary: “…”,
		description: "",
		operationId: “rm”,
		parameters:  [
		 {
		name: "prog",
		in: "query",
		description: “…”,
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: “…”,
		required: true,
		type: "string"
		},
		 {
		name: "version",
		in: "query",
		description: “…”,
		required: true,
		type: "string"
		},
		 {
		name: "toVersion",
		in: "query",
		description: "If specified then DRM for 'version to versionTo' will be prepared.",
		required: false,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "Specifies the vin for which the DRM file must be prepared. Multiple vin parameters are supported.",
		required: true,
		type: "array",
		items:  {
		type: "string"
		},
		collectionFormat: "multi",
		x-example: "vin=VIN1&vin=VIN2"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "DRM file returned successfully."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Problem to generate drm",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		}
		}
		},
		/amum/{program}/tags:  {
		post:  {
		tags:  [
		"amum"
		],
		summary: "Returns a mapping from update regions which should be updated to URL of update packages' PACKAGE.CFGs.",
		description: "",
		operationId: "tags",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which update information must be obtained.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which update information must be obtained.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "[deprecated] Specifies the VIN for which update information must be obtained.",
		required: false,
		type: "string"
		},
		 {
		in: "body",
		name: "body",
		description: "Contains additional information of the client.",
		required: true,
		schema:  {
		$ref: "#/definitions/TagRequest"
		}
		}
		],
		responses:  {
		200:  {
		description: "No update is needed."
		},
		202:  {
		description: "Some update packages must be updated.",
		schema:  {
		$ref: "#/definitions/TagResponse"
		}
		},
		204:  {
		description: "Update is available but it is not provided due to OTC flag turned on."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		429:  {
		description: "Transfer quota was exceeded.",
		schema:  {
		$ref: "#/definitions/TagResponse"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		},
		security:  [
		 {
		apiKey: [ ]
		}
		]
		}
		},
		/vins/{vin}/markets:  {
		get:  {
		tags:  [
		"vins"
		],
		summary: "Returns markets which the specified vin is entitled to access ",
		description: "",
		operationId: "markets",
		parameters:  [
		 {
		name: "program",
		in: "query",
		description: "Specifies the program for which markets shall be returned.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "path",
		description: "Specifies the vin for which markets shall be returned. Multiple vin parameters are supported.",
		required: true,
		type: "string",
		x-example: "vin=VIN1&vin=VIN2"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "markets returned successfully",
		schema:  {
		$ref: "#/definitions/Markets"
		}
		},
		400:  {
		description: "The sent request contains input errors",
		schema:  {
		type: "string"
		}
		},
		500:  {
		description: "Problem to retrive markets",
		schema:  {
		type: "string"
		}
		}
		}
		}
		},
		/amum/{program}/sync/vl:  {
		put:  {
		tags:  [
		"amum"
		],
		summary: "Performs a sync of map version information.",
		description: "",
		operationId: "vl",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which data must be synced.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which data must be synced.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "[deprecated] Specifies the VIN for which update information must be obtained.",
		required: false,
		type: "string"
		},
		 {
		in: "body",
		name: "body",
		description: "Contains additional information of the client.",
		required: true,
		schema:  {
		$ref: "#/definitions/SyncRequest"
		}
		}
		],
		responses:  {
		200:  {
		description: "No sync is needed."
		},
		202:  {
		description: "Map update was successfully stored."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		},
		security:  [
		 {
		apiKey: [ ]
		}
		]
		}
		},
		/amum/{program}/sync/update:  {
		put:  {
		tags:  [
		"amum"
		],
		summary: "Performs a sync of car last update status information.",
		description: "",
		operationId: "update",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which data must be synced.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which data must be synced.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "[deprecated] Specifies the VIN for which update information must be obtained.",
		required: false,
		type: "string"
		},
		 {
		in: "body",
		name: "body",
		description: "Contains information on the car update status.",
		required: true,
		schema:  {
		$ref: "#/definitions/Update"
		}
		}
		],
		responses:  {
		200:  {
		description: "successful operation",
		schema:  {
		$ref: "#/definitions/ActionUpdate"
		}
		},
		202:  {
		description: "Update information was successfully stored."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		},
		security:  [
		 {
		apiKey: [ ]
		}
		]
		}
		},
		/whitelist/{program}:  {
		post:  {
		tags:  [
		"whitelist"
		],
		summary: "Whitelists vehicles specified in the parameters for use in the specified program.",
		description: "",
		operationId: "whitelist",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which vehicles shall be whitelisted.",
		required: true,
		type: "string"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		in: "body",
		name: "body",
		description: "Contains the vehicles that should be whitelisted.",
		required: true,
		schema:  {
		$ref: "#/definitions/WhitelistRequest"
		}
		}
		],
		responses:  {
		200:  {
		description: "All the vehicles has been whitelisted successfully."
		},
		202:  {
		description: "Some of the vehicles could not be whitelisted.",
		schema:  {
		$ref: "#/definitions/WhitelistClientError"
		}
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "None of the vehicles has been whitelisted due to errors.",
		schema:  {
		$ref: "#/definitions/WhitelistClientError"
		}
		}
		}
		}
		},
		/downloader/file/{value}:  {
		get:  {
		tags:  [
		"packageinfo"
		],
		summary: "Provides a file encoded with a *value",
		description: "",
		operationId: "file",
		parameters:  [
		 {
		name: "value",
		in: "path",
		description: "URL path parameter defined in map downloder configuration. See: /fullmap endpoint.",
		required: true,
		type: "string"
		}
		],
		responses:  {
		307:  {
		description: "File was returned successfully"
		},
		400:  {
		description: "The sent request contains input errors",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Problem to download file",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		}
		}
		},
		/downloader/drm/{value}:  {
		get:  {
		tags:  [
		"packageinfo"
		],
		summary: "Provides a DRM file (PACKAGE.SLIST) encoded with a *value.",
		description: "",
		operationId: "drm",
		parameters:  [
		 {
		name: "value",
		in: "path",
		description: "URL path parameter defined in map downloder configuration. See: /fullmap endpoint.",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "PACKAGE.SLIST file was generated successfully.",
		schema:  {
		$ref: "#/definitions/PackageListSigned"
		}
		},
		400:  {
		description: "The sent request contains input errors",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		}
		}
		}
		},
		/downloader/conf/{value}:  {
		get:  {
		tags:  [
		"packageinfo"
		],
		summary: "Provides map downloader configuration.",
		description: "",
		operationId: "conf",
		parameters:  [
		 {
		name: "value",
		in: "path",
		description: "URL path parameter defined in map downloder configuration. See: /fullmap endpoint.",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "Full map configuration was returned successfully.",
		schema:  {
		$ref: "#/definitions/PackageListConfiguration"
		}
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Problem to generate full map configuration.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		}
		}
		},
		/downloader/fullmap:  {
		get:  {
		tags:  [
		"packageinfo"
		],
		summary: "Returns the location of the full map downloader configuration for the specified parameters.",
		description: "",
		operationId: "fullmap",
		parameters:  [
		 {
		name: "program",
		in: "query",
		description: "Specifies the program for which the configuration URL must be prepared.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which the configuration URL must be prepared.",
		required: true,
		type: "string"
		},
		 {
		name: "version",
		in: "query",
		description: "Specifies the market version for which the configuration URL must be prepared.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "Specifies the vin for which the configuration URL must be prepared. Multiple vin parameters are supported.",
		required: true,
		type: "array",
		items:  {
		type: "string"
		},
		collectionFormat: "multi",
		x-example: "vin=VIN1&vin=VIN2"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		303:  {
		description: "Full map configuration URL was computed successfully. See redirect URL."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Problem occurred during processing a request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		}
		}
		},
		/amum/{program}/{market}/reports/transfers/daily:  {
		get:  {
		tags:  [
		"packageinfo"
		],
		summary: "Returns the daily report for VIN transfer usage.",
		description: "",
		operationId: "dailyTransfers",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which the report be prepared.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "path",
		description: "Specifies the market for which the report must be prepared.",
		required: true,
		type: "string"
		},
		 {
		name: "brand",
		in: "query",
		description: "Specifies the brand for which the report must be prepared. If not specified all brands for the program are included.",
		required: false,
		type: "string"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "The report returned successfully",
		schema:  {
		$ref: "#/definitions/Transfers"
		}
		},
		400:  {
		description: "The sent request contains input errors",
		schema:  {
		type: "string"
		}
		},
		500:  {
		description: "Problem to retrive report",
		schema:  {
		type: "string"
		}
		}
		}
		}
		},
		/amum/{program}/{market}/reports/transfers/monthly:  {
		get:  {
		tags:  [
		"packageinfo"
		],
		summary: "Returns the monthly report for VIN transfer usage.",
		description: "",
		operationId: "monthlyTransfers",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which the report must be prepared.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "path",
		description: "Specifies the market for which the report must be prepared.",
		required: true,
		type: "string"
		},
		 {
		name: "brand",
		in: "query",
		description: "Specifies the brand for which the report must be prepared. If not specified all brands for the program are included.",
		required: false,
		type: "string"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "The report returned successfully",
		schema:  {
		$ref: "#/definitions/Transfers"
		}
		},
		400:  {
		description: "The sent request contains input errors",
		schema:  {
		type: "string"
		}
		},
		500:  {
		description: "Problem to retrive report",
		schema:  {
		type: "string"
		}
		}
		}
		}
		},
		/amum/{program}/flags/otc_on:  {
		put:  {
		tags:  [
		"amum"
		],
		summary: "Turns on OTC flag.",
		description: "",
		operationId: "otcOn",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which OTC flag must be turned on.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which OTC flag must be turned on.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "[deprecated] Specifies the VIN for which update information must be obtained.",
		required: false,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "OTC flag was turned on."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		},
		security:  [
		 {
		apiKey: [ ]
		}
		]
		}
		},
		/amum/{program}/flags/otc_off:  {
		put:  {
		tags:  [
		"amum"
		],
		summary: "Turns off OTC flag.",
		description: "",
		operationId: "otcOff",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which OTC flag must be turned off.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which OTC flag must be turned off.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "[deprecated] Specifies the VIN for which update information must be obtained.",
		required: false,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "OTC flag was turned off."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		},
		security:  [
		 {
		apiKey: [ ]
		}
		]
		}
		},
		/amum/admin/{program}/{market}/vin/{vin}:  {
		delete:  {
		tags:  [
		"amum-admin"
		],
		operationId: "remove",
		parameters:  [
		 {
		name: "program",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "path",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "successful operation",
		schema:  {
		$ref: "#/definitions/ActionAnyContent"
		},
		headers: { }
		}
		}
		}
		},
		/amum/admin/{program}/{market}/sync/transfers/{vin}:  {
		get:  {
		tags:  [
		"amum-admin"
		],
		summary: "",
		description: "",
		operationId: "transfers",
		parameters:  [
		 {
		name: "program",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "successful operation",
		schema:  {
		$ref: "#/definitions/ActionAnyContent"
		}
		}
		}
		}
		},
		/amum/admin/{program}/{market}/tags/{vin}:  {
		get:  {
		tags:  [
		"amum-admin"
		],
		summary: "",
		description: "",
		operationId: "tags",
		parameters:  [
		 {
		name: "program",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "successful operation",
		schema:  {
		$ref: "#/definitions/ActionAnyContent"
		}
		}
		}
		}
		},
		/amum/admin/{program}/{market}/sync/config/{vin}:  {
		get:  {
		tags:  [
		"amum-admin"
		],
		summary: "",
		description: "",
		operationId: "config",
		parameters:  [
		 {
		name: "program",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "successful operation",
		schema:  {
		$ref: "#/definitions/ActionAnyContent"
		}
		}
		}
		}
		},
		/amum/admin/{program}/{market}/sync/updates/{vin}:  {
		get:  {
		tags:  [
		"amum-admin"
		],
		operationId: "updates",
		parameters:  [
		 {
		name: "program",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "path",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "path",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "successful operation",
		schema:  {
		$ref: "#/definitions/ActionAnyContent"
		},
		headers: { }
		}
		}
		}
		},
		/amum/admin/{program}/{market}/sync/vls/{vin}:  {
		get:  {
		tags:  [
		"amum-admin"
		],
		summary: "Returns list of ur's and versions after sync based on vin.",
		description: "",
		operationId: "vls",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which update information must be obtained.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "path",
		description: "Specifies the market for which update information must be obtained.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "path",
		description: "Specifies the VIN for which update information must be obtained.",
		required: true,
		type: "string"
		},
		 {
		name: "app_id",
		in: "query",
		description: "app_id of the client which connects to the service",
		required: true,
		type: "string"
		},
		 {
		name: "app_code",
		in: "query",
		description: "app_code of the client which connects to the service",
		required: true,
		type: "string"
		}
		],
		responses:  {
		200:  {
		description: "Information about ur's and versions."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		}
		}
		},
		/amum/{program}/sync/transfer:  {
		put:  {
		tags:  [
		"amum"
		],
		summary: "Performs a sync of car's periodic transfer consumption information.",
		description: "",
		operationId: "transfer",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which data must be synced.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which data must be synced.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "[deprecated] Specifies the VIN for which update information must be obtained.",
		required: false,
		type: "string"
		},
		 {
		in: "body",
		name: "body",
		description: "Contains information on the car transfer consumption.",
		required: true,
		schema:  {
		$ref: "#/definitions/Transfer"
		}
		}
		],
		responses:  {
		200:  {
		description: "successful operation",
		schema:  {
		$ref: "#/definitions/ActionTransfer"
		}
		},
		202:  {
		description: "Transfer information was successfully stored."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		},
		security:  [
		 {
		apiKey: [ ]
		}
		]
		}
		},
		/amum/{program}/sync/config:  {
		put:  {
		tags:  [
		"amum"
		],
		summary: "Performs a sync of car config information.",
		description: "",
		operationId: "config",
		parameters:  [
		 {
		name: "program",
		in: "path",
		description: "Specifies the program for which data must be synced.",
		required: true,
		type: "string"
		},
		 {
		name: "market",
		in: "query",
		description: "Specifies the market for which data must be synced.",
		required: true,
		type: "string"
		},
		 {
		name: "vin",
		in: "query",
		description: "[deprecated] Specifies the VIN for which update information must be obtained.",
		required: false,
		type: "string"
		},
		 {
		in: "body",
		name: "body",
		description: "Contains information on the car config.",
		required: true,
		schema:  {
		$ref: "#/definitions/Config"
		}
		}
		],
		responses:  {
		200:  {
		description: "successful operation",
		schema:  {
		$ref: "#/definitions/ActionConfig"
		}
		},
		202:  {
		description: "Config was successfully stored."
		},
		400:  {
		description: "The sent request contains input errors.",
		schema:  {
		$ref: "#/definitions/ParameterValidationError"
		}
		},
		500:  {
		description: "Errors occurred during processing the request.",
		schema:  {
		$ref: "#/definitions/GenericError"
		}
		}
		},
		security:  [
		 {
		apiKey: [ ]
		}
		]
		}
		}
		},
		definitions:  {
		….
		}
		}

**Comment by shockey** [comment]
@camomileann, looks like your definition lacks `securityDefinitions` for your `apiKey` security scheme. Your annotation library is probably the cause of this!
