### ISSUE TITLE
Error messages display on screen briefly before disappearing

### ISSUE THREAD

**Issue by jimcullenaus** [swagger-api/swagger-ui#5214]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04.1 LTS
 - Browser: Chrome 72.0.3626.81, Firefox 65.0.1
 - Swagger-UI version: 3.21.0, 3.20.6
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Any invalid OpenAPI configuration.

One common example is not including query parameters under a `schema` object in a 3.0 config, and instead simply declaring their type directly under the parameter.

### Describe the bug you're encountering

When loading the swagger ui, an error briefly appears at the top of the page, for a small fraction of a second. It then immediately disappears.

No messages are left in the console log.

### To reproduce...

1. Create an OpenAPI spec with some errors in it.
2. Load that spec using the swagger-ui
3. Observe error messages flash at the top of the page and disappear

### Expected behavior

Errors should remain at the top of the page until and unless manually dismissed.

Errors should also ideally be added to the console log.

### Screenshots

Screenshots taken at various stages in the loading of the page.

![vlcsnap-2019-03-04-10h24m51s609](https://user-images.githubusercontent.com/6212837/53704368-f1281400-3e67-11e9-9d77-b4a15154c877.png)
![vlcsnap-2019-03-04-10h25m05s537](https://user-images.githubusercontent.com/6212837/53704369-f1281400-3e67-11e9-84ea-255126708608.png)
![vlcsnap-2019-03-04-10h25m16s546](https://user-images.githubusercontent.com/6212837/53704370-f1c0aa80-3e67-11e9-9eb4-69ee3504edd9.png)

**Comment by shockey** [comment]
Hi @jimcullenaus, thanks for filing this.

You see no difference in behavior between 3.21.0 and 3.20.6 with your definition? I ask because we specifically made a change last week that should persist resolver error messages (https://github.com/swagger-api/swagger-ui/pull/5193).

> Any invalid OpenAPI configuration.
> 
> One common example is not including query parameters under a schema object in a 3.0 config, and instead simply declaring their type directly under the parameter.

Swagger UI doesn't generate error messages for invalid definitions - only for network and resolver problems, generally. Are you referring to the embedded Swagger UI found within Swagger Editor?

**Comment by jimcullenaus** [comment]
You should be able to see the errors in the screenshots above. Faded, because the messages appear so briefly that the screen recording software I used couldn't grab them properly. The errors I have been able to capture do all seem to be resolver errors, however.

From what I could tell, yes, the problem occurs in both 3.21.0 and 3.20.6. Unfortunately the only way I could find to tell what version is actually running was from code, not from the browser, so it is not impossible that somehow the version running was not the version specified in the package.json. However everything I can see suggests that the version was updated and that the error still occurred.

**Comment by shockey** [comment]
Each Swagger UI 3x version comes with a version identifier baked into it - see the [version detection](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/version-detection.md) documentation for more information. Long story short, checking `window.versions.swaggerUi` in your console will give you the exact version present on the page.

If you're able to get back to your original example, that may help confirm your assumptions 😄

**Comment by jimcullenaus** [comment]
Hmm, it does indeed seem to be running the older version still. Not sure why. I have been unable to get it to upgrade to the latest version whatever I try. However, it does confirm that I can't confirm the issue occurs even on 3.21.0, so unless there's more to add, I'll close off this ticket.
