### ISSUE TITLE
Example value for integer with minimum and maximum is out of bounds

### ISSUE THREAD

**Issue by ilya-spv** [swagger-api/swagger-ui#5216]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: 72
 - Method of installation: visual studio code extension (openapi-designer)
 - Swagger-UI version: [e.g. 3.21.0]
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
I use a visual studio extension to render things on the fly (openapi-designer) and have checked that it uses the latest version of swagger-ui

```yaml
dueDay:
  type: integer
  minimum: 1
  maximum: 31
```

### Describe the bug you're encountering
Generated example shows 0 though it cannot be accepted according to specifications
```
"dueDay": 0,
```

### To reproduce...

1. Render YAML with type: string and format: date
2. Open an example value in the browser

### Expected behavior
Expected to see a value between minimum and maximum
```
"dueDay": 15,
```

P.S. This probably is valid for other parameters like e.g. `Multiples`. It's possible that this is also a feature request and not a bug, I am not quite sure. There is of course an easy workaround to provide own example

**Comment by mmicu** [comment]
I need this feature. If you want, you can assign me this issue.

**Comment by webron** [comment]
@mmicu thanks for offering to solve this issue. Please make sure to follow our [Contribution Guide](https://github.com/swagger-api/.github/blob/master/CONTRIBUTING.md).

**Comment by hkosova** [comment]
Support for `minimum` and `maximum` values in example generator was added in [v. 3.45.0](https://github.com/swagger-api/swagger-ui/releases/v3.45.0) (PR: https://github.com/swagger-api/swagger-ui/pull/7043).
