### ISSUE TITLE
Corrupted ZIP file through swagger - direct link works

### ISSUE THREAD

**Issue by excrucio** [swagger-api/swagger-ui#5217]
File download triggered via the Content-Disposition header will result in a link to download the file, but the file will be corrupt. I am also seeing this issue in my environment.

For now only happens with zip files.
File downloaded through swagger is corrupted and double in size.

The response headers:
{
"Cache-Control": "no-cache, no-store",
"Content-Disposition": "attachment; filename="example.zip"",
"Transfer-Encoding": "chunked",
"Content-Type": "application/octet-stream"
}

This is the download URL that it displays in the UI. If I download via this link, I get a corrupt file. If I use the link directly from the browser, I get a valid download.
blob:http%3A//localhost%3A8090/9222e8a1-8628-476f-9341-372d68729d58

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!

**Comment by excrucio** [comment]
@shockey 
Oh, thin of details. Do not give me that crap.
It is a known issue. You have at least 7 same tickets.

But, newermind, I solved it with custom OperationFilter

**Comment by shockey** [comment]
> Do not give me that crap

@excrucio, you didn't provide _any_ of these things:
- which of Swagger UI's 166 versions you're using
- which browser you're using (download issues are frequently browser-specific)
- an OpenAPI definition or live server that we can use to reproduce your issue
- attachments of the resulting downloads that we could inspect to see what you're seeing
- screenshots
- links to the "7 same tickets" (...why open a new one instead of commenting on an existing one?)

We have an issue template that prompts you for all of this information, but you chose to ignore it.

We're providing support to you at no cost. The least you can do is be respectful of our process.

CC https://github.com/swagger-api/swagger-ui/issues/3952.

**Comment by jvinkovicdink** [comment]
Sorry for inappropriate language before.
Problem is that you are closing issues without resolving the.
This same issue is from 2014.

Just a few
#4638 
#4465
#5217

**Comment by akshayuppal3** [comment]
is it resolved?
I am facing the same issue while downloading the zip file. I am using swagger 2.0

I get the download link in response but it is corrupted

```responses":{"200":{"content":{"application/zip":{"schema":{"type":"file"}}},"description":"Returns a zip file containing model scores, data prediction, mpr validation(TP, TN), and wiki scores"}},"summary":"MPR Scores for validation data","tags":["Validation service"]}}},"swagger":"2.0"}```

The open api json def:
{"definitions":{},"info":{"description":"Swagger docs for validation service web API.","termsOfService":"/tos","title":"Validation service","version":"1.0.0"},"paths":{"/":{"get":{"description":"Home endpoint<br/>","responses":{"200":{"description":"Something went right"},"500":{"description":"Something went wrong"}},"summary":"Themis API","tags":["Themis endpoint"]}},"/mpr/":{"get":{"description":"Blueprint home endpoint<br/><br/>","responses":{"200":{"description":"Something went right"},"500":{"description":"Something went wrong"}},"summary":"Demo Blueprint","tags":["Home"]}},"/mpr/get_scores":{"post":{"parameters":[{"collectionFormat":"csv","description":"Input validation data","in":"formData","name":"input_data","required":true,"type":"file"},{"description":"Zip file include model training files (architecture, weights) and model.json files","in":"formData","name":"model","required":true,"type":"file","x-mimetype":"application/zip"},{"description":"Specify the target label that we need to capture","example":"governing_law_vhr","in":"formData","name":"target_labels","required":true,"type":"string"},{"description":"Set to true if require weighted scores","example":true,"in":"formData","name":"weighted","required":true,"type":"boolean"}],"responses":{"200":{"content":{"application/zip":{"schema":{"type":"file"}}},"description":"Returns a zip file containing model scores, data prediction, mpr validation(TP, TN), and wiki scores"}},"summary":"MPR Scores for validation data","tags":["Validation service"]}}},"swagger":"2.0"}

**Comment by mikip91** [comment]
@akshayuppal3  @jvinkovicdink 
Did you guys solve this issue. I am also running with the same with. I am using swagger 2.1.10

**Comment by jvinkovic** [comment]
Let me provide my solution.
On controller method use:
`[SwaggerProducesAttribute("application/octet-stream")]`

Content disposition header should be "attachment"

That attribute is:
```
    [AttributeUsage(AttributeTargets.Method)]
    public class SwaggerProducesAttributeAttribute : Attribute
    {
        public SwaggerProducesAttributeAttribute(params string[] contentTypes)
        {
            this.ContentTypes = contentTypes;
        }

        public IEnumerable<string> ContentTypes { get; }
    }
```

Return type must be registered so make custom operation filter:
```
public class Produces : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            var attribute = apiDescription.GetControllerAndActionAttributes<SwaggerProducesAttributeAttribute>().SingleOrDefault();
            if (attribute == null)
            {
                return;
            }

            operation.produces.Clear();
            operation.produces = attribute.ContentTypes.ToList();
        }
    }
```
And in swagger config register it:
`c.OperationFilter<Produces>();`

Full example on one controller method
```
        [HttpGet]
        [Route("Download")]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(byte[]))]
        [SwaggerResponse(HttpStatusCode.BadRequest)]
        [SwaggerProducesAttribute("application/octet-stream")]
        public async Task<HttpResponseMessage> GetAllAsZip(Guid taskId)
        {
            _service.TaskId = taskId;

            var fileModel = await _service.GetAllAsZip().ConfigureAwait(false);

            if (null == fileModel)
            {
                return new HttpResponseMessage(HttpStatusCode.NotFound)
                {
                    Content = new StringContent("No files. Nothing to download.")
                };
            }

            var fileDownloadName = fileModel.Filename + '.' + fileModel.Extension;
            var fileContents = fileModel.Data;

            HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StreamContent(fileContents)
            };
            response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");
            response.Content.Headers.ContentType = new MediaTypeHeaderValue(fileModel.ContentType);
            response.Content.Headers.ContentDisposition.FileName = fileDownloadName;

            return response;
        }
```
