### ISSUE TITLE
npm run dev stuck at 69%

### ISSUE THREAD

**Issue by kt236** [swagger-api/swagger-ui#5222]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by kt236** [comment]
OS: [WINDOWS 10]

npm run dev at 69%

 69% building 963/969 modules 6 active ...-ui\node_modules\zenscroll\zenscroll.j
 69% building 964/969 modules 5 active ...-ui\node_modules\zenscroll\zenscroll.j
 69% building 965/969 modules 4 active ...-ui\node_modules\zenscroll\zenscroll.j
 69% building 966/969 modules 3 active ...-ui\node_modules\zenscroll\zenscroll.j
 69% building 966/970 modules 4 active ...odules\fbjs\lib\createArrayFromMixed.j
 69% building 966/971 modules 5 active ...gger-ui\node_modules\fbjs\lib\isNode.j
 69% building 967/971 modules 4 active ...gger-ui\node_modules\fbjs\lib\isNode.j
 69% building 967/972 modules 5 active ...\node_modules\fbjs\lib\getMarkupWrap.j
 69% building 967/973 modules 6 active ...ger-ui\node_modules\remarkable\index.j
 69% building 967/974 modules 7 active ...gger-ui\node_modules\url-parse\index.j
 69% building 968/974 modules 6 active ...gger-ui\node_modules\url-parse\index.j
 69% building 969/974 modules 5 active ...gger-ui\node_modules\url-parse\index.j
 69% building 970/974 modules 4 active ...gger-ui\node_modules\url-parse\index.j
 69% building 970/975 modules 5 active ...ode_modules\es5-ext\object\keys\shim.j
 69% building 970/976 modules 6 active ...s\es5-ext\object\keys\is-implemented.j
 69% building 971/976 modules 5 active ...s\es5-ext\object\keys\is-implemented.j
 69% building 972/976 modules 4 active ...s\es5-ext\object\keys\is-implemented.j
 69% building 972/977 modules 5 active ...agger-ui\node_modules\lodash\toLower.j
 69% building 972/978 modules 6 active ...e_modules\es6-symbol\validate-symbol.j
 69% building 973/978 modules 5 active ...e_modules\es6-symbol\validate-symbol.j
 69% building 974/978 modules 4 active ...e_modules\es6-symbol\validate-symbol.j
 69% building 975/978 modules 3 active ...e_modules\es6-symbol\validate-symbol.j
 69% building 976/978 modules 2 active ...e_modules\es6-symbol\validate-symbol.j
 69% building 977/978 modules 1 active ...PROJECTS\swagger-ui\src\style\main.scs
 69% building 977/979 modules 2 active ...odules\babel-runtime\core-js\promise.j
 69% building 977/980 modules 3 active ...gger-ui\node_modules\lodash\isString.j
 69% building 977/981 modules 4 active ...bel-runtime\helpers\asyncToGenerator.j
 69% building 977/982 modules 5 active ...S\swagger-ui\node_modules\lodash\set.j
 69% building 977/983 modules 6 active ...gger-ui\node_modules\lodash\debounce.j
 69% building 977/984 modules 7 active ...ui\node_modules\remarkable\lib\index.j
 69% building 978/984 modules 6 active ...ui\node_modules\remarkable\lib\index.j
 69% building 979/984 modules 5 active ...ui\node_modules\remarkable\lib\index.j
 69% building 980/984 modules 4 active ...ui\node_modules\remarkable\lib\index.j
 69% building 981/984 modules 3 active ...ui\node_modules\remarkable\lib\index.j
 69% building 981/985 modules 4 active ...i\node_modules\dompurify\dist\purify.j
 69% building 981/986 modules 5 active ...ib\react-immutable-pure-component.es.j
 69% building 982/986 modules 4 active ...ib\react-immutable-pure-component.es.j
 69% building 982/987 modules 5 active ...ui\node_modules\es6-symbol\is-symbol.j
 69% building 982/988 modules 6 active ...dules\js-file-download\file-download.j
 69% building 982/989 modules 7 active ..._modules\xml-but-prettier\dist\index.j
 69% building 983/989 modules 6 active ..._modules\xml-but-prettier\dist\index.j
 69% building 984/989 modules 5 active ..._modules\xml-but-prettier\dist\index.j
 69% building 985/989 modules 4 active ..._modules\xml-but-prettier\dist\index.j
 69% building 986/989 modules 3 active ..._modules\xml-but-prettier\dist\index.j
 69% building 986/990 modules 4 active ...gger-ui\node_modules\lodash\_baseSet.j
 69% building 986/991 modules 5 active ...S\swagger-ui\node_modules\lodash\now.j
 69% building 987/991 modules 4 active ...S\swagger-ui\node_modules\lodash\now.j
 69% building 987/992 modules 5 active ...de_modules\swagger-client\dist\index.j
 69% building 987/993 modules 6 active ...ules\babel-runtime\regenerator\index.j
 69% building 988/993 modules 5 active ...ules\babel-runtime\regenerator\index.j
 69% building 988/994 modules 6 active ...node_modules\remarkable\lib\renderer.j
 69% building 988/995 modules 7 active ...e_modules\remarkable\lib\parser_core.j
 69% building 988/996 modules 8 active ..._modules\remarkable\lib\parser_block.j
 69% building 988/997 modules 9 active ...modules\remarkable\lib\parser_inline.j
 69% building 988/998 modules 10 active ...ui\node_modules\remarkable\lib\ruler.
 69% building 989/998 modules 9 active ...ui\node_modules\remarkable\lib\ruler.j
 69% building 990/998 modules 8 active ...ui\node_modules\remarkable\lib\ruler.j
 69% building 990/999 modules 9 active ..._modules\remarkable\lib\common\utils.j
 69% building 990/1000 modules 10 active ...dules\remarkable\lib\configs\default
 69% building 990/1001 modules 11 active ..._modules\remarkable\lib\configs\full
 69% building 990/1002 modules 12 active ...es\remarkable\lib\configs\commonmark
 69% building 991/1002 modules 11 active ...es\remarkable\lib\configs\commonmark
 69% building 992/1002 modules 10 active ...es\remarkable\lib\configs\commonmark
 69% building 993/1002 modules 9 active ...es\remarkable\lib\configs\commonmark.
 69% building 994/1002 modules 8 active ...es\remarkable\lib\configs\commonmark.
 69% building 995/1002 modules 7 active ...es\remarkable\lib\configs\commonmark.
 69% building 996/1002 modules 6 active ...es\remarkable\lib\configs\commonmark.
 69% building 997/1002 modules 5 active ...es\remarkable\lib\configs\commonmark.
 69% building 998/1002 modules 4 active ...es\remarkable\lib\configs\commonmark.
 69% building 999/1002 modules 3 active ...es\remarkable\lib\configs\commonmark.
 69% building 1000/1002 modules 2 active ...de_modules\swagger-client\dist\index
 69% building 1001/1002 modules 1 active ...PROJECTS\swagger-ui\src\style\main.s
 69% building 1001/1003 modules 2 active ...e_modules\core-js\library\fn\promise
 69% building 1001/1004 modules 3 active ...ui\node_modules\remarkable\lib\rules
 69% building 1001/1005 modules 4 active ...ules\remarkable\lib\rules_core\block
 69% building 1001/1006 modules 5 active ...dules\remarkable\lib\rules_core\abbr
 69% building 1001/1007 modules 6 active ...les\remarkable\lib\rules_core\inline
 69% building 1001/1008 modules 7 active ...arkable\lib\rules_core\footnote_tail
 69% building 1001/1009 modules 8 active ...markable\lib\rules_core\replacements
 69% building 1001/1010 modules 9 active ...emarkable\lib\rules_core\smartquotes
 69% building 1001/1011 modules 10 active ...remarkable\lib\rules_core\reference
 69% building 1001/1012 modules 11 active ...markable\lib\rules_block\state_bloc
 69% building 1001/1013 modules 12 active ...ules\remarkable\lib\rules_block\cod
 69% building 1001/1014 modules 13 active ...es\remarkable\lib\rules_block\fence
 69% building 1001/1015 modules 14 active ...ules\remarkable\lib\rules_block\lis
 69% building 1001/1016 modules 15 active ...es\remarkable\lib\rules_core\linkif
 69% building 1001/1017 modules 16 active ...emarkable\lib\rules_block\blockquot
 68% building 1001/1018 modules 17 active ...odules\remarkable\lib\rules_block\h
 68% building 1001/1019 modules 18 active ...remarkable\lib\rules_block\htmlbloc
 68% building 1001/1020 modules 19 active ...s\remarkable\lib\rules_block\headin
 68% building 1001/1021 modules 20 active ...\remarkable\lib\rules_block\lheadin
 68% building 1001/1022 modules 21 active ...s\remarkable\lib\rules_block\deflis
 68% building 1001/1023 modules 22 active ...dules\remarkable\lib\common\entitie
 68% building 1001/1024 modules 23 active ...rkable\lib\rules_inline\state_inlin
 68% building 1001/1025 modules 24 active ...les\remarkable\lib\rules_inline\tex
 68% building 1001/1026 modules 25 active ...remarkable\lib\rules_block\paragrap
 68% building 1001/1027 modules 26 active ...emarkable\lib\rules_inline\backtick
 68% building 1001/1028 modules 27 active ...les\remarkable\lib\rules_block\tabl
 68% building 1001/1029 modules 28 active ...s\remarkable\lib\rules_inline\escap
 68% building 1001/1030 modules 29 active ...\remarkable\lib\rules_inline\newlin
 68% building 1001/1031 modules 30 active ...ules\remarkable\lib\rules_inline\de
 68% building 1001/1032 modules 31 active ...remarkable\lib\rules_inline\emphasi
 68% building 1001/1033 modules 32 active ...ules\remarkable\lib\rules_inline\su
 68% building 1001/1034 modules 33 active ...les\remarkable\lib\rules_inline\mar
 68% building 1001/1035 modules 34 active ...ules\remarkable\lib\rules_inline\in
 67% building 1001/1036 modules 35 active ...ules\remarkable\lib\rules_inline\su
 67% building 1001/1037 modules 36 active ...es\remarkable\lib\rules_inline\link
 67% building 1001/1038 modules 37 active ...ble\lib\rules_inline\footnote_inlin
 67% building 1001/1039 modules 38 active ...remarkable\lib\rules_inline\autolin
 67% building 1001/1040 modules 39 active ...\remarkable\lib\rules_inline\htmlta
 67% building 1001/1041 modules 40 active ...ules\remarkable\lib\rules_core\abbr
 67% building 1001/1042 modules 41 active ...s\remarkable\lib\rules_inline\entit
 67% building 1001/1043 modules 42 active ...ui\node_modules\querystringify\inde
 67% building 1001/1044 modules 43 active ...rkable\lib\rules_inline\footnote_re
 67% building 1001/1045 modules 44 active ...\remarkable\lib\rules_block\footnot
 67% building 1001/1046 modules 45 active ...-ui\node_modules\requires-port\inde
 67% building 1002/1046 modules 44 active ...-ui\node_modules\requires-port\inde
 67% building 1003/1046 modules 43 active ...-ui\node_modules\requires-port\inde
 67% building 1004/1046 modules 42 active ...-ui\node_modules\requires-port\inde
 67% building 1005/1046 modules 41 active ...-ui\node_modules\requires-port\inde
 67% building 1006/1046 modules 40 active ...-ui\node_modules\requires-port\inde
 67% building 1007/1046 modules 39 active ...-ui\node_modules\requires-port\inde
 67% building 1008/1046 modules 38 active ...-ui\node_modules\requires-port\inde
 67% building 1009/1046 modules 37 active ...-ui\node_modules\requires-port\inde
 67% building 1010/1046 modules 36 active ...-ui\node_modules\requires-port\inde
 67% building 1011/1046 modules 35 active ...-ui\node_modules\requires-port\inde
 68% building 1012/1046 modules 34 active ...-ui\node_modules\requires-port\inde
 68% building 1013/1046 modules 33 active ...-ui\node_modules\requires-port\inde
 68% building 1014/1046 modules 32 active ...-ui\node_modules\requires-port\inde
 68% building 1015/1046 modules 31 active ...-ui\node_modules\requires-port\inde
 68% building 1016/1046 modules 30 active ...-ui\node_modules\requires-port\inde
 68% building 1017/1046 modules 29 active ...-ui\node_modules\requires-port\inde
 68% building 1018/1046 modules 28 active ...-ui\node_modules\requires-port\inde
 68% building 1019/1046 modules 27 active ...-ui\node_modules\requires-port\inde
 68% building 1020/1046 modules 26 active ...-ui\node_modules\requires-port\inde
 68% building 1021/1046 modules 25 active ...-ui\node_modules\requires-port\inde
 68% building 1022/1046 modules 24 active ...-ui\node_modules\requires-port\inde
 68% building 1023/1046 modules 23 active ...-ui\node_modules\requires-port\inde
 68% building 1024/1046 modules 22 active ...-ui\node_modules\requires-port\inde
 68% building 1025/1046 modules 21 active ...-ui\node_modules\requires-port\inde
 68% building 1026/1046 modules 20 active ...-ui\node_modules\requires-port\inde
 68% building 1027/1046 modules 19 active ...-ui\node_modules\requires-port\inde
 68% building 1028/1046 modules 18 active ...-ui\node_modules\requires-port\inde
 69% building 1029/1046 modules 17 active ...-ui\node_modules\requires-port\inde
 69% building 1030/1046 modules 16 active ...-ui\node_modules\requires-port\inde
 69% building 1031/1046 modules 15 active ...-ui\node_modules\requires-port\inde
 69% building 1032/1046 modules 14 active ...-ui\node_modules\requires-port\inde
 69% building 1033/1046 modules 13 active ...-ui\node_modules\requires-port\inde
 69% building 1034/1046 modules 12 active ...-ui\node_modules\requires-port\inde
 69% building 1035/1046 modules 11 active ...-ui\node_modules\requires-port\inde
 69% building 1036/1046 modules 10 active ...-ui\node_modules\requires-port\inde
 69% building 1037/1046 modules 9 active ...-ui\node_modules\requires-port\index
 69% building 1038/1046 modules 8 active ...-ui\node_modules\requires-port\index
 69% building 1039/1046 modules 7 active ...-ui\node_modules\requires-port\index
 69% building 1040/1046 modules 6 active ...-ui\node_modules\requires-port\index
 69% building 1041/1046 modules 5 active ...-ui\node_modules\requires-port\index
 69% building 1042/1046 modules 4 active ...-ui\node_modules\requires-port\index
 69% building 1043/1046 modules 3 active ...-ui\node_modules\requires-port\index
 69% building 1044/1046 modules 2 active ...dules\remarkable\lib\common\entities
 69% building 1044/1047 modules 3 active ...\library\modules\es7.promise.finally
 69% building 1044/1048 modules 4 active ...\core-js\library\modules\es6.promise
 69% building 1045/1048 modules 3 active ...\core-js\library\modules\es6.promise
 69% building 1045/1049 modules 4 active ...e-js\library\modules\es7.promise.try
 69% building 1045/1050 modules 5 active ...es\remarkable\lib\common\url_schemas
 69% building 1045/1051 modules 6 active ...es\remarkable\lib\common\html_blocks
 69% building 1045/1052 modules 7 active ...odules\remarkable\lib\common\html_re
 69% building 1045/1053 modules 8 active ...arkable\lib\helpers\parse_link_label
 69% building 1045/1054 modules 9 active ...arkable\lib\helpers\parse_link_title
 69% building 1045/1055 modules 10 active ...e\lib\helpers\parse_link_destinatio
 69% building 1045/1056 modules 11 active ...able\lib\helpers\normalize_referenc
 69% building 1045/1057 modules 12 active ...emarkable\lib\helpers\normalize_lin
 69% building 1046/1057 modules 11 active ...emarkable\lib\helpers\normalize_lin
 69% building 1047/1057 modules 10 active ...emarkable\lib\helpers\normalize_lin
 69% building 1048/1057 modules 9 active ...emarkable\lib\helpers\normalize_link
 69% building 1049/1057 modules 8 active ...emarkable\lib\helpers\normalize_link
 69% building 1049/1058 modules 9 active ...wagger-ui\node_modules\lodash\assign
 69% building 1049/1059 modules 10 active ...er-ui\node_modules\lodash\startsWit
 69% building 1050/1059 modules 9 active ...er-ui\node_modules\lodash\startsWith
 69% building 1050/1060 modules 10 active ...ger-ui\node_modules\lodash\cloneDee
 69% building 1050/1061 modules 11 active ...\swagger-ui\node_modules\lodash\pic
 69% building 1051/1061 modules 10 active ...\swagger-ui\node_modules\lodash\pic
 69% building 1052/1061 modules 9 active ...\swagger-ui\node_modules\lodash\pick
 69% building 1053/1061 modules 8 active ...\swagger-ui\node_modules\lodash\pick
 69% building 1054/1061 modules 7 active ...\swagger-ui\node_modules\lodash\pick
 69% building 1054/1062 modules 8 active ...dules\babel-runtime\core-js\weak-map
 69% building 1055/1062 modules 7 active ...dules\babel-runtime\core-js\weak-map
 69% building 1056/1062 modules 6 active ...dules\babel-runtime\core-js\weak-map
 69% building 1056/1063 modules 7 active ...-ui\node_modules\repeat-string\index
 69% building 1057/1063 modules 6 active ...-ui\node_modules\repeat-string\index
 69% building 1058/1063 modules 5 active ...-ui\node_modules\repeat-string\index
 69% building 1059/1063 modules 4 active ...-ui\node_modules\repeat-string\index
 69% building 1060/1063 modules 3 active ...-ui\node_modules\repeat-string\index
 69% building 1061/1063 modules 2 active ...-ui\node_modules\repeat-string\index
 69% building 1061/1064 modules 3 active ...library\modules\_species-constructor
 69% building 1061/1065 modules 4 active ...-js\library\modules\_promise-resolve
 69% building 1062/1065 modules 3 active ...-js\library\modules\_promise-resolve
 69% building 1062/1066 modules 4 active ...odules\core-js\library\modules\_task
 69% building 1062/1067 modules 5 active ...core-js\library\modules\_an-instance
 69% building 1062/1068 modules 6 active ...s\core-js\library\modules\_microtask
 69% building 1062/1069 modules 7 active ...rary\modules\_new-promise-capability
 69% building 1062/1070 modules 8 active ...les\core-js\library\modules\_perform
 69% building 1062/1071 modules 9 active ...\core-js\library\modules\_user-agent
 69% building 1062/1072 modules 10 active ...core-js\library\modules\_set-specie
 69% building 1062/1073 modules 11 active ...ules\core-js\library\modules\_for-o
 69% building 1062/1074 modules 12 active ...ore-js\library\modules\_redefine-al
 69% building 1062/1075 modules 13 active ...s\regenerator-runtime\runtime-modul
 69% building 1063/1075 modules 12 active ...s\regenerator-runtime\runtime-modul
 69% building 1064/1075 modules 11 active ...s\regenerator-runtime\runtime-modul
 69% building 1065/1075 modules 10 active ...s\regenerator-runtime\runtime-modul
 69% building 1066/1075 modules 9 active ...s\regenerator-runtime\runtime-module
 69% building 1067/1075 modules 8 active ...s\regenerator-runtime\runtime-module
 69% building 1068/1075 modules 7 active ...s\regenerator-runtime\runtime-module
 69% building 1069/1075 modules 6 active ...s\regenerator-runtime\runtime-module
 69% building 1070/1075 modules 5 active ...s\regenerator-runtime\runtime-module
 69% building 1071/1075 modules 4 active ...s\regenerator-runtime\runtime-module
 69% building 1072/1075 modules 3 active ...s\regenerator-runtime\runtime-module
 69% building 1073/1075 modules 2 active ...s\regenerator-runtime\runtime-module
 69% building 1073/1076 modules 3 active ...\node_modules\lodash\_createAssigner
 69% building 1073/1077 modules 4 active ...er-ui\node_modules\lodash\_baseClamp
 69% building 1073/1078 modules 5 active ...ger-ui\node_modules\lodash\_basePick
 69% building 1074/1078 modules 4 active ...ger-ui\node_modules\lodash\_basePick
 69% building 1074/1079 modules 5 active ...ger-ui\node_modules\utf8-bytes\index
 69% building 1074/1080 modules 6 active ...er-ui\node_modules\encode-3986\index
 69% building 1074/1081 modules 7 active ...dules\cross-fetch\dist\fetch-browser
 69% building 1074/1082 modules 8 active ...ss-fetch\dist\fetch-browser-polyfill
 69% building 1074/1083 modules 9 active ...swagger-ui\node_modules\qs\lib\index
 69% building 1074/1084 modules 10 active ...e_modules\fast-json-patch\lib\duple
 69% building 1075/1084 modules 9 active ...e_modules\fast-json-patch\lib\duplex
 69% building 1076/1084 modules 8 active ...e_modules\fast-json-patch\lib\duplex
 69% building 1076/1085 modules 9 active ...ules\querystring-browser\querystring
 69% building 1077/1085 modules 8 active ...ules\querystring-browser\querystring
 69% building 1077/1086 modules 9 active ...S\swagger-ui\node_modules\btoa\index
 69% building 1077/1087 modules 10 active ...-ui\node_modules\utfstring\utfstrin
 69% building 1077/1088 modules 11 active ...swagger-ui\node_modules\cookie\inde
 69% building 1077/1089 modules 12 active ...ules\core-js\library\modules\_invok
 69% building 1078/1089 modules 11 active ...ules\core-js\library\modules\_invok
 69% building 1079/1089 modules 10 active ...ules\core-js\library\modules\_invok
 69% building 1080/1089 modules 9 active ...ules\core-js\library\modules\_invoke
 69% building 1081/1089 modules 8 active ...ules\core-js\library\modules\_invoke
 69% building 1082/1089 modules 7 active ...ules\core-js\library\modules\_invoke
 69% building 1082/1090 modules 8 active ...les\isomorphic-form-data\lib\browser
 69% building 1083/1090 modules 7 active ...les\isomorphic-form-data\lib\browser
 69% building 1083/1091 modules 8 active ..._modules\regenerator-runtime\runtime
 69% building 1084/1091 modules 7 active ..._modules\regenerator-runtime\runtime
 69% building 1085/1091 modules 6 active ..._modules\regenerator-runtime\runtime
 69% building 1086/1091 modules 5 active ..._modules\regenerator-runtime\runtime
 69% building 1087/1091 modules 4 active ..._modules\regenerator-runtime\runtime
 69% building 1088/1091 modules 3 active ..._modules\regenerator-runtime\runtime
 69% building 1089/1091 modules 2 active ..._modules\regenerator-runtime\runtime
 69% building 1089/1092 modules 3 active ...ger-ui\node_modules\lodash\_baseRest
 69% building 1089/1093 modules 4 active ...r-ui\node_modules\lodash\_basePickBy
 69% building 1089/1094 modules 5 active ...e_modules\autolinker\dist\Autolinker
 69% building 1089/1095 modules 6 active ...ger-ui\node_modules\qs\lib\stringify
 69% building 1089/1096 modules 7 active ...agger-ui\node_modules\qs\lib\formats
 69% building 1089/1097 modules 8 active ...swagger-ui\node_modules\qs\lib\parse
 69% building 1089/1098 modules 9 active ..._modules\core-js\library\fn\weak-map
 69% building 1090/1098 modules 8 active ..._modules\core-js\library\fn\weak-map
 69% building 1090/1099 modules 9 active ...ode_modules\fast-json-patch\lib\core
 69% building 1090/1100 modules 10 active ..._modules\fast-json-patch\lib\helper
 69% building 1091/1100 modules 9 active ..._modules\fast-json-patch\lib\helpers
 69% building 1092/1100 modules 8 active ..._modules\fast-json-patch\lib\helpers
 69% building 1093/1100 modules 7 active ..._modules\fast-json-patch\lib\helpers
 69% building 1094/1100 modules 6 active ..._modules\fast-json-patch\lib\helpers
 69% building 1095/1100 modules 5 active ..._modules\fast-json-patch\lib\helpers
 69% building 1096/1100 modules 4 active ..._modules\fast-json-patch\lib\helpers
 69% building 1097/1100 modules 3 active ...ode_modules\fast-json-patch\lib\core
 69% building 1098/1100 modules 2 active ...e_modules\autolinker\dist\Autolinker
 69% building 1098/1101 modules 3 active ...core-js\library\modules\es6.weak-map
 69% building 1098/1102 modules 4 active ...e-js\library\modules\es7.weak-map.of
 69% building 1098/1103 modules 5 active ...js\library\modules\es7.weak-map.from
 69% building 1098/1104 modules 6 active ...swagger-ui\node_modules\qs\lib\utils
 69% building 1099/1104 modules 5 active ...swagger-ui\node_modules\qs\lib\utils
 69% building 1100/1104 modules 4 active ...swagger-ui\node_modules\qs\lib\utils
 69% building 1101/1104 modules 3 active ...swagger-ui\node_modules\qs\lib\utils
 69% building 1102/1104 modules 2 active ...swagger-ui\node_modules\qs\lib\utils
 69% building 1103/1104 modules 1 active ...PROJECTS\swagger-ui\src\style\main.s
 69% building 1103/1105 modules 2 active ...re-js\library\modules\_array-methods
 69% building 1103/1106 modules 3 active ...-js\library\modules\_collection-weak
 69% building 1103/1107 modules 4 active ...\core-js\library\modules\_collection
 69% building 1103/1108 modules 5 active ...library\modules\_validate-collection
 69% building 1103/1109 modules 6 active ...s\library\modules\_set-collection-of
 69% building 1103/1110 modules 7 active ...library\modules\_set-collection-from
 69% building 1104/1110 modules 6 active ...library\modules\_set-collection-from
 69% building 1105/1110 modules 5 active ...library\modules\_set-collection-from
 69% building 1106/1110 modules 4 active ...library\modules\_set-collection-from
 69% building 1107/1110 modules 3 active ...library\modules\_set-collection-from
 69% building 1108/1110 modules 2 active ...library\modules\_set-collection-from
 69% building 1109/1110 modules 1 active ...PROJECTS\swagger-ui\src\style\main.s
 69% building 1109/1111 modules 2 active ...ger-ui\node_modules\deep-equal\index
 69% building 1109/1112 modules 3 active ...ibrary\modules\_array-species-create
 69% building 1110/1112 modules 2 active ...ibrary\modules\_array-species-create
 69% building 1111/1112 modules 1 active ...PROJECTS\swagger-ui\src\style\main.s
 69% building 1111/1113 modules 2 active ...-ui\node_modules\deep-equal\lib\keys
 69% building 1111/1114 modules 3 active ..._modules\deep-equal\lib\is_arguments
 69% building 1112/1114 modules 2 active ..._modules\deep-equal\lib\is_arguments
 69% building 1113/1114 modules 1 active ...PROJECTS\swagger-ui\src\style\main.s
 69% building 1113/1115 modules 2 active ...y\modules\_array-species-constructor
 69% building 1114/1115 modules 1 active ...PROJECTS\swagger-ui\src\style\main.s
 69% building 1115/1116 modules 1 active ...node_modules\css-loader\lib\css-base

**Comment by shockey** [comment]
@kt236, have you tried opening http://localhost:3200?

Sometimes Webpack doesn't give a final readout when it's done spinning up.

**Comment by kt236** [comment]
Yep, I tried that and it worked. But initially I was lost on what was
really going. on. Your reply clarifies that. Thank you.

**Comment by shockey** [comment]
No problem! I've been meaning to take a look at newer versions of webpack-dev-server, perhaps there are some improvements in the 2/3 series in this regard.

Glad you got it figured out! Closing as resolved.
