### ISSUE TITLE
state parameter is missing in OAuth2 request

### ISSUE THREAD

**Issue by victorsmirnov** [swagger-api/swagger-ui#524]
`state` parameter is missing in the authorization request. It is recommended in the [specification](http://tools.ietf.org/html/rfc6749#section-4.1.1) and sometimes it is required by server implementations.

The fix might be do add one more line after [this one](https://github.com/wordnik/swagger-ui/blob/master/dist/lib/swagger-oauth.js#L105) but in the source file.

```
    url += '&state=state';
```

**Comment by mohsen1** [comment]
This was fixed by https://github.com/swagger-api/swagger-ui/pull/936
