### ISSUE TITLE
Parameters under path item object does not load

### ISSUE THREAD

**Issue by jimcullenaus** [swagger-api/swagger-ui#5245]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04.1 LTS
 - Browser: Chrome, Firefox
 - Swagger-UI version: 3.20.6
 - Swagger/OpenAPI version: OpenApi 3.0

### Content & configuration

Including `parameters` directly under a path item object, as opposed to as part of an operation object.

Example Swagger/OpenAPI definition:
```yaml
  /status:
    get:
      tags:
        - Service
      summary: Information about the current status of the API
      responses:
        '200':
          description: Service OK
          content:
            '*/*':
              schema:
                type: string
                example: Service is running
  /v1/users/{userId}:
    parameters:
      $ref: '#/components/parameters/UserId'
    put:
      summary:
        ...
      requestBody:
        ...
      responses:
        ...
    get:
      summary:
        ...
      requestBody:
        ...
      responses:
        ...
components:
  parameters:
    UserId:
      $ref: ./components/parameters/UserId.yaml
```

### Describe the bug you're encountering

When the method is opened, nothing displays except a spinner.

When a *different* method is opened, nothing displays except a spinner.

When opening it up, the console prints:

```
TypeError: [object Object] is not iterable!                                               actions.js:221
    at e.exports.n.getIterator (core.get-iterator.js:5)
    at index.js:1
    at t.normalizeSwagger (index.js:1)
    at Function.<anonymous> (index.js:1)
    at w (runtime.js:62)
    at Generator._invoke (runtime.js:296)
    at Generator.e.(/documentation/apis/swagger-ui/anonymous function) [as next] (http://my-swagger-ui-path/swagger-ui-bundle.js:70:346936)
    at r (asyncToGenerator.js:17)
    at asyncToGenerator.js:35
    at new Promise (<anonymous>)


Uncaught (in promise) TypeError: Cannot read property 'resultMap' of undefined            actions.js:224
    at actions.js:224
    at w (runtime.js:62)
    at Generator._invoke (runtime.js:296)
    at Generator.e.(/documentation/apis/swagger-ui/anonymous function) [as throw] (http://my-swagger-ui-path/swagger-ui-bundle.js:70:346936)
    at r (asyncToGenerator.js:17)
    at asyncToGenerator.js:30
```

### To reproduce...

1. Create a path with a parameter in it, such as `/api/collection/{id}`.
2. Put a `parameters` object directly under that path
3. Place the path parameter in the parameters object.
4. Do *not* place a path parameter in the operation.

### Expected behavior

Parameters in the path should display the same as path parameters placed in the operation.

![image](https://user-images.githubusercontent.com/6212837/54582794-c7710e80-4a5d-11e9-9b61-8091000264ee.png)

### Additional context or thoughts
If I move that exact same ref into the parameters property under individual operations (i.e., under the `put` and `get` properties), it displays correctly.

May be related to #4456, #4327, #1119, and #617. Note however that I am running on a much more recent version of the swagger-ui than those, and that with all of those the rest of the operation would display correctly with the exception of path parameters. In my case, the presence of path parameters seems to break all operations in the API.

**Comment by shockey** [comment]
@jimcullenaus, did you figure out the issue here? Was this intentionally closed?

**Comment by jimcullenaus** [comment]
Hi, yes it was. The issue was a lack of a dash (`-`) before the `$ref`.
