### ISSUE TITLE
ft/remove-react-addons-perf release

### ISSUE THREAD

**Issue by pgoldtho** [swagger-api/swagger-ui#5250]
### How can we help?

I'm looking for a release that includes https://github.com/swagger-api/swagger-ui/pull/5229.  The PR text suggests a release date of March 16.  I don't see anything on https://github.com/swagger-api/swagger-ui/releases.  Do I need to apply it as a patch?

**Comment by shockey** [comment]
@pgoldtho sorry for the delay there, I'm responsible for running Swagger UI releases and I was ill on the 15th/16th. Hope the current version is working well for you 😄

**Comment by pgoldtho** [comment]
Thanks, @shockey.  I'm no longer working for the company that needed the fix.  They laid off a bunch of people a few weeks ago
