### ISSUE TITLE
Swagger-UI Not Escaping HTML Special Characters / Symbols

### ISSUE THREAD

**Issue by abrenner** [swagger-api/swagger-ui#526]
Swagger-UI is not escaping any HTML special characters / symbols. When you have an API call and it takes two or more parameters, the ampersand is used, and the second, third, etc one happens to contain characters that make up a symbol, it does not get escaped.

Example Request URL:
http://localhost:9090/api/aws/ec2?instance=m3.large&region=us-west

The `&reg` part of the URL, will be treated as the registered trademark symbol in the browser. This makes the swagger-ui unusable. Please safe escape the URL. So it it sent to browser as `&amp;`

I do not know CoffeeScript or the code base. Any pointers on where to look or patches are welcomed.

**Comment by fehguy** [comment]
This should be fixed in develop_2.0 branch--please reopen if you're still having issues.
