### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by AndriiHavrylyak** [swagger-api/swagger-ui#5263]
I want to map the photo to the server by using POST via http, but I get an error "TypeError: Failed to fetch" . Why can this be?
![121](https://user-images.githubusercontent.com/38010614/54917422-73a27180-4f04-11e9-9ecd-ec8fd5dba856.png)

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!

**Comment by AndriiHavrylyak** [comment]
https://github.com/swagger-api/swagger-ui/issues/5280

чт, 28 бер. 2019 о 21:47 kyle <notifications@github.com> пише:
