### ISSUE TITLE
Hide info.description

### ISSUE THREAD

**Issue by Leon99** [swagger-api/swagger-ui#5267]
It would be great to have an option to not show info.description.
Use case: we use ReDoc to present API's documentation, however, we still want to have Swagger UI to be able to execute operations. Swagger UI, unlike ReDoc, doesn't generate anchors for Markdown headers, which gives an impression that the documentation is broken. Besides, it requires a user to scroll through the description to get to the operation list.

**Comment by hkosova** [comment]
Here's a plugin that hides the `info.description` text:
```js
// index.html

const HideInfoDescriptionPlugin = () => {
  return {
    wrapComponents: {
      info: (Original, system) => (props) => {
        return system.React.createElement(Original, {
          ...props,
          info: props.info.set("description", "")
        })
      }
    }
  }
}

// Build a system
const ui = SwaggerUIBundle({
  url: "https://petstore.swagger.io/v2/swagger.json",
  ...
  plugins: [
    HideInfoDescriptionPlugin    // <------
  ],
  ...
})
```

**Comment by Yahayasabiyu** [comment]
intitle:"Swagger UI - " + "Show/Hide"
