### ISSUE TITLE
response type is not correct

### ISSUE THREAD

**Issue by jwpaxx** [swagger-api/swagger-ui#5269]
response type is not correct
class com.github.pagehelper.Page

when i use the pagehelper as response type
the response type will be 
```
[
  {
    "createTime": "2019-03-29T03:08:24.345Z",
    "fileHash": "string",
    "fileName": "string",
    "filePath": "string",
    "fileSize": 0,
    "fileType": "string",
    "id": "string",
    "keyMsg": "string",
    "sourceMark": "string",
    "systemId": "string",
    "userId": "string",
    "userType": "string",
    "widget": "string"
  }
]
```
this page info is gone

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
