### ISSUE TITLE
Access denied on IE 9 due to xhr.open with cross domain

### ISSUE THREAD

**Issue by dakshika** [swagger-api/swagger-ui#527]
If you host this on one domain and send request to http://petstore.swagger.wordnik.com/api/api-docs, it returns access denied on below code. 

xhr.open(
        params.method || 'GET',
        (params.scheme || 'http') + '://' + uri,
        true
    );

Normally IE9 

shred.bundle.js line: 2564

**Comment by fehguy** [comment]
Hi, the UI should be defaulting you to use jquery, where this is supported.  This is an old ticket so please reopen if still an issue.
