### ISSUE TITLE
OAS3 — Path specific servers are not supported

### ISSUE THREAD

**Issue by davesag** [swagger-api/swagger-ui#5270]
### Q&A (please complete the following information)
 - OS: macOS Mojave
 - Browser: all
 - Method of installation: `dist` (embedded in `swagger-ui-express`)
 - Swagger-UI version: 3.22.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
servers:
- url: /api/v1
paths:
  /ping:
    get:
      servers:
      - url: /
      tags:
      - root
      summary: Checks that the server is alive
      operationId: ping
      responses:
        200:
          description: 'Information about the server'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
```

### Describe the bug you're encountering

My API offers some root level routes such as

```
/ping
```

and then versioned API routes such as

```
/api/v1/search/{param}
```

I've defined a main base path using the `servers` block but then, for the root level paths I defined a path specific `servers` block. This is not reflected in the UI however.

See image

![Screen Shot 2019-03-29 at 11 01 37 am](https://user-images.githubusercontent.com/387098/55211537-62ae7480-5212-11e9-898f-cd7aa84fb5d8.png)

### Expected behavior

I guess this needs some thought but I'd expect to see tag-specific (maybe) or path specific base path overrides in the UI.

### Additional context or thoughts

I appreciate this is non-trivial to solve.

**Comment by hkosova** [comment]
Path-specific servers are supported and are currently displayed during try-it-out:

![Path-specific servers in Swagger UI](https://user-images.githubusercontent.com/8576823/55218239-8bcf0500-5212-11e9-9854-a57ed706bfa4.png)

**Comment by davesag** [comment]
Well there you go.  I had no idea. Thanks.
