### ISSUE TITLE
Missing JsonSubTypes in Swagger Code Gen for jaxrs-jersey

### ISSUE THREAD

**Issue by rajeswarikolluri** [swagger-api/swagger-ui#5271]
Below is the sample yaml with Inheritance and Polymorphism.  While generating server stubs  for **JAXRS-JERSEY.**  Model objects doesn't contain @JsonTypeInfo and @JsonSubTypes .  Is this supported in latest  swagger-codegen-cli-3.0.5.jar ?

openapi: "3.0.0"
info:
  description: "This is a sample server Petstore server."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
tags:
- name: "pets"
  description: "Everything about your Pets"
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
              discriminator:
                propertyName: pet_type
      responses:
        '200':
          description: Updated
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
        mapping:
          cachorro: Dog
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
    Dog:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Dog`
        properties:
          bark:
            type: string
    Lizard:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Lizard`
        properties:
          lovesRocks:
            type: boolean

**Comment by shockey** [comment]
Hi @rajeswarikolluri,

As this is a Codegen question, please ask it in the [Codegen repository](https://github.com/swagger-api/swagger-codegen).
