### ISSUE TITLE
Backslash in body string in curl command

### ISSUE THREAD

**Issue by adaamz** [swagger-api/swagger-ui#5273]
### Q&A
 - OS: *
 - Browser: *
 - Method of installation: FROM node:10.9.0-alpine; RUN npm install -g swagger-cli

request:
![image](https://user-images.githubusercontent.com/4347332/55253046-927e6c00-5254-11e9-873a-6777b7cea4fb.png)

generated curl command:
![image](https://user-images.githubusercontent.com/4347332/55253089-b3df5800-5254-11e9-8bd6-ca88b82fe4e2.png)

As you see, there are continuation backslashes, but they are in request string, which makes json invalid.

Correct curl command is
```shell
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
   "applications": [
     {
       "app_name": "string",
       "fast_file_hashes": [
         [
           "0D9B6663EE594475427BB1A32044983C"
         ]
       ],
       "file_hashes": [
         [
           "0D9B6663EE594475427BB1A32044983C"
         ]
       ],
       "installer_package_name": "string",
       "label": "string",
       "package_name": "string",
       "permissions": [
         "string"
       ],
       "signature_hashes": [
         "0D9B6663EE594475427BB1A32044983C"
       ],
       "source_dir": "string",
       "target_sdk_version": 55,
       "version_code": 66,
       "version_name": "string"
     }
   ],
   "reference_id": "string"
 }' 'http://localhost:9090/apps/v1/android/apps'
```

**Comment by shockey** [comment]
Hi @adaamz!

We're no longer working on or supporting the 2.x series of the UI (which you provided screenshots of) - please upgrade to v3.

Thanks for the report, though!

**Comment by adaamz** [comment]
@shockey Hi, thanks for response.
Please can you tell me where can I get Swagger UI version 3?
I use these commands to build swagger ui:
`
docker run -d --rm --name "${DOCKER_CONTAINER_NAME}" -p 63999:8080 -e "SWAGGER_JSON=/${API_YAML_NAME}" -e "VALIDATOR_URL=null" -v "${SOURCE_API_FILE}":"/${API_YAML_NAME}" swaggerapi/swagger-ui

wget -E -k -p -nH -q -P "${DIST_FOLDER}/swagger-ui/" http://127.0.0.1:63999
`
