### ISSUE TITLE
HTML5 Placeholder in Parameter Fields

### ISSUE THREAD

**Issue by lucas1000001** [swagger-api/swagger-ui#528]
Hi, 

Following on from my [groups post](https://groups.google.com/forum/#!topic/swagger-swaggersocket/AqfW8ShRv68) I think it'd be useful to utilize the HTML5 placeholder attribute for parameter input fields within swagger UI - basically as a helpful cue for the user.

For example, if I had a date field the input box could start with a placeholder of 'yyyy-mm-dd' - the default value couldn't be used here as the format suggestion isn't actually valid input.

I guess there'd need to be an additional field on the annotation, e.g. 

> @ApiParam(placeholder="yyyy-mm-dd")

I'd be more than happy to contribute the change myself if you guys think that it's worthwhile

Cheers

**Comment by fehguy** [comment]
Hi @lucas1000001 would this be better in the `defaultValue`?

**Comment by fehguy** [comment]
Please feel free to open an issue on swagger-core for this.
