### ISSUE TITLE
parameterMacro not working with Open API spec

### ISSUE THREAD

**Issue by mtraynham** [swagger-api/swagger-ui#5282]
### Q&A
 - OS: macOS
 - Browser: Chrome
 - Version: 73
 - Method of installation: npm
 - Swagger-UI version: 3.22.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Any generic configuration will do as the bug is functionality related.

### Describe the bug you're encountering
With an older Swagger 2.0 spec, I had a [`parameterMacro`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#macros) that would provide a default value for various request parameters.  After a switch to using an OpenAPI 3.0 spec, that `parameterMacro` function no longer seems to work and these default values aren't set.  It does seem to fire, but that seems to do nothing.

### To reproduce...
Implement a `parameterMacro` when using an OpenAPI 3.0 spec.  Notice the function fires, but it does nothing.

### Expected behavior
The parameterMacro function is executed and set's a default value for the parameter.

**Comment by shockey** [comment]
Looks like a bug!

**Comment by mtraynham** [comment]
Closing as resolved via #5617
