### ISSUE TITLE
validating field in a schema with optional fields as well ? oneOf 

### ISSUE THREAD

**Issue by pitiwari** [swagger-api/swagger-ui#5285]
I have a particular field for which one value is required and then there can be one extra value from amongst 6 possible values as struct shows below, name is required and then there can be optional one more value from exact_match,regex_match .... invert_match. How can i do this optional check for presence of _match fields ?
 
{
  "name": "...",
  "exact_match": "...",
  "regex_match": "...",
  "range_match": "{...}",
  "present_match": "...",
  "prefix_match": "...",
  "suffix_match": "...",
  "invert_match": "..."
}

**Comment by shockey** [comment]
Closing this - not clear how/if this is related to Swagger UI.
