### ISSUE TITLE
report multiple body parameters are not allowed

### ISSUE THREAD

**Issue by xiaoice** [swagger-api/swagger-ui#5292]
swagger: "2.0"，found this error report，Any good solutions？

```
/user/createWithArray:
    post:
      tags:
      - "user"
      summary: "Creates list of users with given input array"
      description: ""
      operationId: "createUsersWithArrayInput"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "List of user object"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/User"
      - in: "body"
        name: "head"
        description: "List of user object"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Category"
      responses:
        default:
          description: "successful operation"
```

**Comment by hkosova** [comment]
Only one body parameter is allowed per operation. The body parameter defines the request body content, such as the JSON or XML object being passed in the request body. Check out [Describing Request Body](https://swagger.io/docs/specification/2-0/describing-request-body/) for more details and examples.

In your example, it looks like the 2nd body parameter (with `name: "head"`) is included by mistake and is not supposed to be there:
```yaml
      - in: "body"
        name: "head"
        description: "List of user object"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Category"
```

**Comment by xiaoice** [comment]
I know, but I do have this requirement on my side. Is there any solution, such as modifying the source code，how to modify？thanks

**Comment by hkosova** [comment]
Please open a ticket with whatever library/tool you used to generate the API definition because it generated an invalid definition. This is not a Swagger UI issue.

**Comment by xiaoice** [comment]
at    /src/core/plugins/spec/actions.js   at line 358 

// multiple body parameters are not allowed 
    let paramsKeyArr = Object.keys(req.parameters)
    if (paramsKeyArr.length > 1) {
      let obj = {}
      for ( let key in req.parameters) {
        let paramsKey = (key || "").replace("body.", "")
        obj[paramsKey] = JSON.parse(req.parameters[key]) || {}
      }

      let paramsBody = JSON.stringify(obj, null, 2)
      req.parameters = {}
      paramsKeyArr.forEach((bodyKey) => {
        req.parameters[bodyKey] = paramsBody
      })
    }

**Comment by MaruthiRaghuveer** [comment]
I am also facing same issue of Multiple body parameters are not allowed in the swagger editor please find below :
- name: relationships
          in: body
          description: List of relationships object
          required: false
          schema:
            type: array
            items:
              $ref: '#/definitions/Relationships'
        - name: PVS
          in: body
          description: List of PVS object
          required: false
          schema:
            type: array
            items:
              $ref: '#/definitions/PVS'
      responses:
        '200':
          description: Success!
