### ISSUE TITLE
swagger-ui-react - docExpansion in changelog for 3.22.0, but not in release on NPM

### ISSUE THREAD

**Issue by davidsmf** [swagger-api/swagger-ui#5294]
### Q&A (please complete the following information)
 - OS: all
 - Version: 3.22.0
 - Method of installation: npm

### Content & configuration
```
$ npm install swagger-ui-react@3.22.0
$ grep docExpansion node_modules/swagger-ui-react/index.js
$
```

### Describe the bug you're encountering
It looks like the npm release doesn't reflect the contents of the tag/release notes.

**Comment by laurence-hudson-mindfoundry** [comment]
@shockey Did transpiling the change from #5242 get missed out of the 3.22.0 release process?

**Comment by shockey** [comment]
Thanks for the heads-up, @davidsmf!

Not sure what happened here with 3.22.0, but I've just run a test release of `swagger-ui-react@3.22.1-alpha.0` from CI and the `docExpansion` content made it in correctly.

I'll check the 3.22.1 release contents once it's live in a few minutes, before I close this out.

**Comment by shockey** [comment]
OK, `swagger-ui-react@3.22.1` is now live on npm!

looks like it has the latest changes:

```
➜ curl -s https://unpkg.com/swagger-ui-react@3.22.1/index.js | grep docExpansion 
        docExpansion: this.props.docExpansion
```

closing, thanks again @davidsmf @laurence-hudson-mindfoundry!
