### ISSUE TITLE
Pass data directly

### ISSUE THREAD

**Issue by manasarora119** [swagger-api/swagger-ui#5302]
Is it possible to pass  data directly , rather than passing  json  url in URL ,

I want to pass json  directly to UI Bundle

**Comment by hkosova** [comment]
Use the [`spec`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-spec) parameter:

```js
const ui = SwaggerUIBundle({
  "dom_id": "#swagger-ui",
  spec: {
    "swagger": "2.0",
    "info": { ... },
    "paths": { ... },
    ...
  },
  ...
})
```
