### ISSUE TITLE
relative paths and https support

### ISSUE THREAD

**Issue by GitDsFn** [swagger-api/swagger-ui#531]
Hi team wordnik,

When i try to work with relative paths and https protocol the generated json files will not be loaded from swagger-ui. The json files will be loaded under the http protocol, but my application needs the https protocol.
To fix this problem temporarily I use the "useJQuery : true" parameter in the SwaggerUi object. So requesting jsons with https is working correctly.
I think it would be possible that there is a bug in shred.bundle.js and the https protocol should be set correctly even if I work with relative paths for my swagger url.

Cheers

**Comment by fehguy** [comment]
I believe this is fixed but will confirm and close out afterwards.

**Comment by fehguy** [comment]
confirmed fixed.
