### ISSUE TITLE
OAS 3.0 `content/../examples` out of spec

### ISSUE THREAD

**Issue by vprohorov-ellation** [swagger-api/swagger-ui#5315]
### Q&A (please complete the following information)
 - OS: http://editor.swagger.io/
 - Browser: chrome
 - Version: 73
 - Method of installation: live demo
 - Swagger-UI version: 3.22
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Swagger Petstore
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
  /pet:
    get:
      summary: Update an existing pet
      operationId: getPet
      responses:
        '200':
          description: All good
          examples:
            Wrong:
              id: 1000
              category:
                id: 2000
                name: Should not be displayed!
              name: doggie
              photoUrls:
                - string
              tags:
                - id: 3000
                  name: string
              status: available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              examples:
                one:
                  summary: Uno pet
                  value:
                    id: 1
                    category:
                      id: 2
                      name: string
                    name: doggie
                    photoUrls:
                      - string
                    tags:
                      - id: 3
                        name: string
                    status: available
                two:
                  summary: Duo pet
                  value:
                    id: 4
                    category:
                      id: 5
                      name: string
                    name: doggie
                    photoUrls:
                      - string
                    tags:
                      - id: 6
                        name: string
                    status: available

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Category
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    Pet:
      required:
      - name
      - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
          - available
          - pending
          - sold
      xml:
        name: Pet
```

### Describe the bug you're encountering

According to OpenAPI 3.0, and as the editor is pointing out:
```
'200': should NOT have additional properties (examples)
```

The uno and duo pets from `content/../examples` should be displayed as examples overriding the schema generated example. When removing the `Wrong` examples, only the schema generated remains, although spec specifies that `examples` should override it.

Using `content/../example` (singular) - works as intended and overrides the schema generated example.

### To reproduce...

1. Open swagger-editor site
2. Paste in provided OpenAPI spec from this ticket
3. Click to unfold the `GET /pet` endpoint in live preview
4. See error in editor and `Wrong` example in live preview.

### Expected behavior

Uno and duo pets examples should be displayed for the 200 response examples.

### Screenshots

![image](https://user-images.githubusercontent.com/37533923/56422591-e6f39500-62b0-11e9-83b7-c1edc9a7276d.png)
![image](https://user-images.githubusercontent.com/37533923/56422606-f83ca180-62b0-11e9-97fc-b50aa6e502ad.png)

### Additional context or thoughts

This bug can be replicated using swagger-ui docker image.

[OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#mediaTypeObject)

**Comment by hkosova** [comment]
`content.<media-type>.examples` are currently not supported, this is tracked in #2651.

**Comment by vprohorov-ellation** [comment]
@hkosova, #2651 mentions a slightly different problem and the very first comment is (considering that I'm already using 3.X):
> This should be addressed in 3.X.

Since this particular feature is buried deep within the comments, decided to open a separate ticket for a more transparent tracking.

**Comment by hkosova** [comment]
`content.<media-type>.examples` are now supported in Swagger UI 3.23.0 and later.
