### ISSUE TITLE
Required Headers Param hangs in Execute

### ISSUE THREAD

**Issue by nab0310** [swagger-api/swagger-ui#5323]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 73.0
 - Method of installation: web
 - Swagger-UI version: latest
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
This is a bug I found when using the https://editor.swagger.io/ site.

Example Swagger/OpenAPI definition:
I used the Petstore example and added a required header in the post path.

```yaml
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
...
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "header"
        description: "workspace identifier"
        required: true
        schema:
          type: "string"
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
...
```

### Describe the bug you're encountering
When including a required header and not passing anything in for it, if you try to submit a request the ui hangs.

### To reproduce...

1. Go to `https://editor.swagger.io/`
2. Add a required header to the POST /pets endpoint.
To do this, in the parameters for the endpoint add this yaml:
```
      - in: "header"
        name: "header"
        description: "workspace identifier"
        required: true
        schema:
          type: "string"
```
3. After the UI updates, go to the POST /pets endpoint and click 'Try it out' then `Execute` without filling any value for the required header.
4. The UI will hang on the 'Loading...' image.

### Expected behavior
The required header field that is empty should shake and warn the user to fill out the required field.

### Screenshots
Here is the console error: 
<img width="400" alt="Screen Shot 2019-04-23 at 11 14 32 AM" src="https://user-images.githubusercontent.com/11669595/56601207-23303980-65c0-11e9-97eb-085079320611.png">

The screen with the loading image hanging:
<img width="794" alt="Screen Shot 2019-04-23 at 12 06 28 PM" src="https://user-images.githubusercontent.com/11669595/56601268-49ee7000-65c0-11e9-812e-0e281960bf8c.png">

### Additional context or thoughts
It looks like the error is correctly being reported, it is just not triggering any change in the UI like missing path or body params do.

**Comment by hkosova** [comment]
In the header parameter, replace
```yaml
        schema:
          type: "string"
```
with
```
        type: "string"
```

In OpenAPI 2.0, non-body parameters use `type` directly without `schema`.
