### ISSUE TITLE
Swagger 3.x with ASP.NET Web API 2

### ISSUE THREAD

**Issue by ganesh-sahastrabuddhe** [swagger-api/swagger-ui#5329]
jQuery 1.8 which is used in Swagger 2 has security issues. Swashbuckle 5.6.0 is using jQuery 1.8.

![Swagger-Jquery-Version-Issue](https://user-images.githubusercontent.com/32063551/56792466-46a8ed80-6827-11e9-85ed-302124fe8c52.png)

How to use Swagger 3.X in ASP.NET Web API 2 or how to update jQuery version used in Swagger?

**Comment by tesfayea** [comment]
I am in the same boat. It would be great if there was an update the uses a newer version of jquery

**Comment by hkosova** [comment]
Swagger UI 2.x is no longer supported or maintained, you should upgrade to Swagger UI 3.x. Version 3 no longer uses jQuery.

I believe the latest version of `Swashbuckle.AspNetCore` uses Swagger UI 3.x. You can also download the [`dist` assets](https://github.com/swagger-api/swagger-ui/tree/master/dist) from this repository and use them directly.

**Comment by Vikasnarwade55** [comment]
Hi @hkosova  can we use this witt ASP.Net MVC with .Net framework 4.5.2 or 4.6.1

**Comment by hkosova** [comment]
@Vikasnarwade55 Please check Swashbuckle documentation. Swashbuckle is not our project so we don't know those details.
