### ISSUE TITLE
response body is no content, but if in real browser return json/string

### ISSUE THREAD

**Issue by toshim45** [swagger-api/swagger-ui#534]
please help, if i open my apps from real browser will return this
![screen shot 2014-08-16 at 5 59 10 am](https://cloud.githubusercontent.com/assets/8453594/3939970/9889861c-24d1-11e4-8217-08077e001ae6.png)
but if I open it from "try it out" return this
![screen shot 2014-08-16 at 5 58 53 am](https://cloud.githubusercontent.com/assets/8453594/3939973/af8ed308-24d1-11e4-8a7c-90c70b38fd32.png)
I only change index.html 

<pre>
/* url: "http://petstore.swagger.wordnik.com/api/api-docs", */ 
url: "http://localhost:8080/pena-im/api-docs",
</pre>

Am I missing some configuration ?
by the way I'm just using dist folder, not building from source

Thanks in advance

**Comment by bijayy33** [comment]
If you are using .NET Core. Using this in startup.cs file

services
.AddMvc()
.AddJsonOptions(x => x.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);
