### ISSUE TITLE
response integer type not shown on swagger-ui ( openapi 3.0.1)

### ISSUE THREAD

**Issue by Willing-Xyz** [swagger-api/swagger-ui#5345]
if type is integer/number, response is not shown.

![image](https://user-images.githubusercontent.com/12200332/57534941-bc5aa080-7373-11e9-9caa-11aa190e6eb4.png)

but if type if string, response is shown.

![image](https://user-images.githubusercontent.com/12200332/57535022-eb711200-7373-11e9-843b-938e22ecb03c.png)

here is code:

```yml
openapi: 3.0.1
info:
  version: "1.0"
  title: rest doc title
  description: rest doc desc
servers:
  - url: /
    description: server
tags:
  - name: ResponseController
 
paths:
  /response/simple:
    get:
      tags:
        - ResponseController
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: integer
```

**Comment by hkosova** [comment]
@Willing-Xyz could you please try the latest version? Your example work fine for me in Swagger UI 3.23.4 and Swagger Editor 3.6.32.

![image](https://user-images.githubusercontent.com/8576823/62618544-2c4dd800-b91d-11e9-8990-68eda636a471.png)

**Comment by Willing-Xyz** [comment]
thanks @hkosova . it works.
