### ISSUE TITLE
How do I get current selected server value from a plugin?

### ISSUE THREAD

**Issue by Grafu** [swagger-api/swagger-ui#5357]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74
 - Method of installation: npm
 - Swagger-UI version: 3.10.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

```
onAuthorize(event) {
        const username = this.state.username;
        const password = this.state.password;
        const pin = this.state.pin;

        var serversNode = document.getElementsByClassName("servers")[0];
        var labelNode = serversNode.childNodes[0];
        var selectNode = labelNode.childNodes[0];
        var selected = selectNode.nodeValue;

        alert(`Session details were submitted: ${this.state.username} ${this.state.password}`);
        event.preventDefault();
    }
```

### Screenshots

![image](https://user-images.githubusercontent.com/11540828/57915069-a6c80800-7898-11e9-9d03-10a66aff9aeb.png)

### How can we help?
I am replacing authorization popup window with custom logic. How do I get the value of currently selected server inside the custom authorization popup plugin? I've tried the code below but 'selected' does not seem to return the value. Is there any official method to get values of other hardcoded components?

**Comment by brpeterman** [comment]
While the AuthorizationPopup component itself doesn't know anything about the servers, you can definitely get the selected server from the DOM:

```javascript
const serversList = document.querySelector('.servers select');
const selectedServer = serversList.options[serversList.selectedIndex];
const apiRoot = selectedServer.value;
```
