### ISSUE TITLE
try out input fields got erased

### ISSUE THREAD

**Issue by thian4** [swagger-api/swagger-ui#5374]
swagger.yaml
```
swagger: "2.0"
paths:
  /users/register:
    post:
      tags:
        - "user"
      summary: "register user"
      description: ""
      operationId: "register"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          type: "string"
          required: true
        - name: "email"
          type: "string"
          required: true
        - name: "password"
          type: "string"
          required: true

      responses:
        400:
          description: "Invalid input"

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

```

### Describe the bug you're encountering
Can't enter the parameter input in the input fields, when I stop typing the input will clear the entered value

### Screenshots
<img src="https://i.imgur.com/rrMVi7a.gif" />

**Comment by hkosova** [comment]
The parameter definitions are missing the [`in`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-parameterin) attribute (e.g. `in: formData` or similar). If you paste your definition into https://editor.swagger.io it will flag these syntax errors. Once you fix these errors the inputs will work fine.
