### ISSUE TITLE
ENDPOINTS

### ISSUE THREAD

**Issue by victorgp89** [swagger-api/swagger-ui#5375]
### Q&A 
 - OS: ubuntu
 - Browser:chrome
 - Version: ]
 - Method of installation: npm
 - Swagger-UI version: ^3.22.1

### Content & configuration
Is posible to define some endpoints? 

Swagger/OpenAPI definition:

Swagger-UI configuration options:
<pre>
//Set up routes tripadvisor
  app.use('/', tripadvisorRoute);
  app.use('/', trivagoRoute);

  // Swagger UI
  // Hack around changing URL for swagger.json
  // https://github.com/swagger-api/swagger-ui/issues/4624
  const swaggerIndexContent = fs
    .readFileSync(`${pathToSwaggerUi}/index.html`)
    .toString()
    .replace('https://petstore.swagger.io/v2/swagger.json', '/swagger.json');

  console.log(pathToSwaggerUi);

  app.get('/api-docs/index.html', (req, res) => res.send(swaggerIndexContent));
  app.get('/api-docs', (req, res) => res.redirect('/api-docs/index.html'));
  app.use('/api-docs', express.static(pathToSwaggerUi));
</pre>

<pre>
/**
 * Swagger definition.
 */
const swaggerDefinition = {
    info: {
        title: process.env.APP_NAME,
        version: process.env.APP_VERSION,
        description: process.env.APP_DESCRIPTION
    },
    basePath: '/trivago'
};

/**
 * Options for the swagger docs.
 */
const swaggerOptions = {
    // import swaggerDefinitions
    swaggerDefinition: swaggerDefinition,
    // path to the API docs
    apis: [
        path.join(__dirname, '/routes.js'),
        path.join(__dirname, '/docs/*.js'),
        path.join(__dirname, '/docs/*.yml'),
        path.join(__dirname, '/docs/*.yaml')
    ]
};

/**
 * Initialize swagger-jsdoc.
 */
const swaggerSpec = swaggerJSDoc(swaggerOptions);

/**
 * GET /swagger.json
 */
router.get('/swagger.json', (req, res) => {
    res.json(swaggerSpec);
});
</pre>

### How can we help?
I need to configure several APIs but it always overwrites me.

**Comment by hkosova** [comment]
This question seems to be about the `swagger-ui-express` middleware, not Swagger UI. You should ask in the `swagger-ui-express` repository:
https://github.com/scottie1984/swagger-ui-express
