### ISSUE TITLE
Support for defaultValue property in model schema

### ISSUE THREAD

**Issue by statueofmike** [swagger-api/swagger-ui#539]
The ability to provide default values for model properties as seen in 
http://petstore.swagger.wordnik.com/#!/pet/partialUpdate
Clicking on the model schema next to a parameter inserts that schema for interactive test input.

The petstore example seems to use Scala to set these default values. I believe it is "@BeanProperty var id: Long = 0" from 
https://github.com/wordnik/swagger-core/blob/e32403e87aea6e43abec2660d8459116b3352725/samples/scala-jaxrs-fileupload/src/main/scala/com/wordnik/swagger/sample/model/Pet.scala

According to https://groups.google.com/forum/#!searchin/swagger-swaggersocket/Default$20values$20for$20model$20schema/swagger-swaggersocket/glJND84drJo/re7OhrUjASUJ
and 
https://groups.google.com/forum/#!searchin/swagger-swaggersocket/Default%2420values%2420for%2420model%2420schema/swagger-swaggersocket/TPb3dcitmpw/34TW3YQYA5oJ
There doesn't seem to be any support for the defaultValue property provided by javax.xml for the non-Scala users of Swagger.

**Comment by fehguy** [comment]
Will look at adding the `defaultValue` from JAXB annotations.

**Comment by statueofmike** [comment]
Is there an existing annotation for java that doesn't require Scala?

**Comment by fehguy** [comment]
Yes, the swagger-annotations library doesn't require scala. As for the framework, the 1.5.0-SNAPSHOT is pure Java.

**Comment by fehguy** [comment]
moved here:  https://github.com/swagger-api/swagger-core/issues/844
