### ISSUE TITLE
Dollar sign not works on copy / paste of curl command line

### ISSUE THREAD

**Issue by jbarotin** [swagger-api/swagger-ui#5390]
### Content & configuration
I'm using swagger-ui to document an odata api

The curl command generated looks like this one :
```
curl -X GET "https://myservice.net/odata/v4/Items?$top=3" -H  "accept: application/json"
```

### Is your feature request related to a problem?

A copy / copy and paste of the following command line (on Unix based OS), the url will be interpreted as `https://myservice.net/odata/v4/Items?=3`

### Describe the solution you'd like

In order to make sure the dollar is not interpreted, it would be nice to have this kind of command line with parameter using single quote. 
```
curl -X GET 'https://myservice.net/odata/v4/Items?$top=3' -H  'accept: application/json'
```
### Describe alternatives you've considered

Otherwise dollar could be escaped, but I'm not sure it works under Windows :
```
curl -X GET "https://myservice.net/odata/v4/Items?\$top=3" -H  "accept: application/json"
```

Maybee using the url encoding code :
```
curl -X GET "https://myservice.net/odata/v4/Items?%24top=3" -H  "accept: application/json" 
```

**Comment by shockey** [comment]
Depending on the tradeoffs, it might be better to just always use singlequotes.

**Comment by shockey** [comment]
per @hkosova:

> single quotes are for Bash and won't work in Windows cmd

**Comment by jbarotin** [comment]
Also, the "Add a backslash before '$'" solution is fine to me

**Comment by shockey** [comment]
Yeah, perhaps we should just be using an escape library (a la [`shell-escape`](https://www.npmjs.com/package/shell-escape)). 

Conveniently, we do build up an args array in our curlify function:

https://github.com/swagger-api/swagger-ui/blob/9ea7fd98784f19d6cd8c098e1da913e992d46ca5/src/core/curlify.js#L4-L9
