### ISSUE TITLE
Missing client Id input

### ISSUE THREAD

**Issue by sm2017** [swagger-api/swagger-ui#5397]
Flow: `authorizationCode` has no client_id input in swagger ui

![image](https://user-images.githubusercontent.com/19644997/59271589-64ac9f00-8c69-11e9-98db-cde7eea77835.png)

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
