### ISSUE TITLE
Execute button not working when one of the parameters is required boolean

### ISSUE THREAD

**Issue by asholokh** [swagger-api/swagger-ui#5400]
I'm using swagger-ui version 3.22.0, have discovered weird behaviour occurring when one of the parameters is type boolean. After loading page 'Execute' button is active, but cannot be clicked (no reaction). The solution is changing the value of boolean from/to true/false and after this 'Execute' will be able to perform some action.

### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: chrome
 - Version: 74.0
 - Swagger-UI version: [e.g. 3.22.0]
 - Swagger/OpenAPI version:Swagger 2.0, OpenAPI 3.0

It seems that the issue which was previously reported and fixed is now reproducible again:
https://github.com/swagger-api/swagger-ui/issues/3407

Also, seems that current code version does not contain the fix provided by the following pull request:
https://github.com/swagger-api/swagger-ui/pull/4613

**Comment by shockey** [comment]
@asholokh, does the boolean parameter in question have a default value set? #3407 and #4613 were specifically addressing a problem with `default` values alongside `required: true`.

This is why our issue template asks for an OpenAPI document that illustrates your use case 😉

**Comment by shockey** [comment]
To put this in concrete terms, here's what should be expected behavior:

```yaml
openapi: 3.0.2
info:
  version: 0.0.1
  title: Show examples

paths:
  /:
    get:
      parameters:
      - name: requiredNoDefault
        description: |
          should block the request from executing unless you manually select a value, because it is required but a value has not been provided
        in: query
        required: true
        schema:
          type: boolean
      - name: requiredTrueDefault
        description: |
          should not block the request from executing unless you manually pick `--`, which would omit the parameter, which is not allowed b/c of `required: true`. 
          
          should send `true` by default.
        in: query
        required: true
        schema:
          type: boolean
          default: true
      - name: requiredFalseDefault
        description: |
          should not block the request from executing unless you manually pick `--`, which would omit the parameter, which is not allowed b/c of `required: true`. 
          
          should send `false` by default.
        in: query
        required: true
        schema:
          type: boolean
          default: false
      responses:
        200:
          description: ok
```

**Comment by asholokh** [comment]
In my case the parameter is defined with only property "required = true". No default value is set.

The problem is that on the UI, in combobox the there is "true" selected by default. But, seems that it is not considered as selected value, because the request execution is blocked. 
Probably, this is the UI issue.

**Comment by shockey** [comment]
@asholokh okay, what you're describing sounds like a bug! Happy to investigate further if you can provide an OpenAPI definition that we can use to reproduce the problem.

**Comment by t9t** [comment]
@shockey I'm facing this issue as well. I've constructed the following minimal yaml which demonstrates the issue:
```yaml
swagger: '2.0'
info:
  description: Boolean param demonstration
  version: '1.0'
  title: Demo
paths:
  /boolean-example:
    post:
      consumes:
        - text/plain
      produces:
        - text/plain
      parameters:
        - name: boolparam
          in: query
          required: true
          type: boolean
      responses:
        '200':
          description: successful operation
```

If you enter this on https://editor.swagger.io/, then in the UI on the right press "Try it out" you can see that for the `boolparam` it defaults to `true`. However when you immediately press Execute, it will shake the `boolparam` input and make it red, indicating there is an error with it. Switching it to `false` and then back to `true` works around this issue.

Besides this issue, I must say that I'm not too fond of the change where a required boolean parameters default to `true` (at least in the UI), rather than `--` as it was before (and still is when using `required: false`). That meant when using the Swagger UI, the user had to explicitly make a choice between true/false, which for my specific use case is much more preferable than using either default value.

**Comment by hkosova** [comment]
In Swagger UI 3.43.0, _required_ boolean parameters no longer default to `--`, and all of the provided definitions work as expected.

Closing as fixed.

**Comment by mohanstrat** [comment]
how to change "Try it out!" to "Submit"
