### ISSUE TITLE
window.opener is null in oauth2-redirect.html

### ISSUE THREAD

**Issue by sm2017** [swagger-api/swagger-ui#5403]
![image](https://user-images.githubusercontent.com/19644997/59580227-8680a880-90e5-11e9-8c61-5cafb9956221.png)

Why in `oauth2-redirect.html` window.opener is null ?

**Comment by sm2017** [comment]
My authentication server redirect broweser so I loose window.opener
How can I fix it , as there is two callback in swaggerUIRedirectOauth2 I have no idea

**Comment by stvstvstv** [comment]
Hi, have you managed to find a fix?

**Comment by sm2017** [comment]
@stvstvstv in redirection you must keep origin, dont Change origin

**Comment by dan-cooke** [comment]
@sm2017 any more information on this one? 

I am not changing origin, my swagger ui is running on http://localhost:4000/docs and i redirect to http://localhost:4000/docs/oauth2-redirect.html

but yet i get this error.

**Comment by pramotetrs** [comment]
@toficzak If you use the open-source as your authentication server, try to add `Cross-Origin-Opener-Policy: "same-origin"` to the authentication server and keep the origin
