### ISSUE TITLE
Authorize button does not change for different securitySchemes

### ISSUE THREAD

**Issue by andresf-celfocus** [swagger-api/swagger-ui#5404]
**Q&A**
OS: Windows and Linux
Browser: Firefox 67.0.2 (64-bit), Chrome Version 74.0.3729.169 and Internet Explorer 11.829.17134.0
Swagger-UI version: 3.17.2
Swagger/OpenAPI version: 3.0.0
Reproducible: Always

**Description:**
We have several APIs, ones that use Basic Authentication as an authorization method and others that use Bearer Token.
When navigating through the several APIs, the Available Authorizations which appear when clicking the Authorize Button (Basic Auth or Bearer Token) are fixed to the first case that we open, i.e. if we click the Authorization Button for a BasicAuth case, all the other APIs will have BasicAuth in the Authorization Button (and the same for the BearerToken).
The only workaround is to refresh the browser (F5), but the issue will repeat again.

Added two videos illustrating the issue (one where all the AuthorizationButtons stay with BasicAuth case, and another for the bearerToken).
In those videos, the M2MAuthorize API is BasicAuth, and the m2m-network-v2 and m2m-basecountry are bearerToken.
Also added the YAML files for the 3 APIs.
Also added a code extract which corresponds to the Javascript code which "changes" the swagger API.

All these videos and files can be found in: https://app.celfocus.com/storeit/index.php/s/tpAonrm9rRgdfrx
Password: swagger

Can someone help with this issue? We are not sure if it is a bug or that we are not correctly reloading each API.

**Comment by hkosova** [comment]
Related (or duplicate): #5540

**Comment by mathis-m** [comment]
Have added the auth data flush on url load with #7046.
