### ISSUE TITLE
Is it possible to reference one value of an enum in the yml?

### ISSUE THREAD

**Issue by torta1526** [swagger-api/swagger-ui#5430]
Hi All,
Is it possible to reference one value of an enum in the yml? 

Say there is an enum:

components:
  schemas:
    Color:
      - red
      - blue
      - white

Can I reference one of these values?
    Fireengine:
      properties:
        FireColor:
          $ref: '#components/schema/Color/red'

Thank you!

**Comment by hkosova** [comment]
No it's not possible to reference a subset of an enum.

**Comment by torta1526** [comment]
Thank you!

**Comment by shockey** [comment]
closing as resolved!
