### ISSUE TITLE
in the Examples UI, modified values should be associated with an underlying example value

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#5434]
### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0

paths:
  /:
    post:
      requestBody:
        content:
          text/plain:
            schema:
              type: string
            examples:
              First:
                value: abc
                description: >
                  This is my first example
              Second:
                value: 123
                description: >
                  This is my second example
      responses:
        "200":
          description: OK!
```

### To reproduce...

1. Open the operation.
2. Click "Try it out".
3. Observe that "First" is the active example.
4. Modify the request body value.
5. Observe that `[Modified value]` is now displayed in the Examples dropdown.
  * Note that you have just "derived" your new modified value from "First".
6. Select "Second" in the Examples dropdown. 
  * Observe that "Second" is now displayed in the dropdown and example detail section.
8. Select "[Modified value]" in the Examples dropdown.

Observe that you're back to the modified value you derived from First, but Second is now displayed alongside your modified value.

### Expected behavior

When an input value transitions from an Examples value to a modified one, Swagger UI should make note of which example the modified value was derived from, and use that information to always render the underlying example alongside that modified value.

**Comment by drewkerrigan** [comment]
I'm running into this as well.

**Comment by mathis-m** [comment]
Cannot reproduce this with the current version. I provided some fixes to the mutliple examples process. Maybe this was fix too with that.

@drewfreyling can you check if you are using the latest version of swagger-ui v3.44.0.


https://editor.swagger.io/?url=https://gist.githubusercontent.com/mathis-m/abbeb8533c8aa50379a938d7d29a5574/raw/e708c5e61df546cc742923662fdb71248858321e/aDb7fXdYYF.txt

**Comment by mathis-m** [comment]
@tim-lai this issue can be closed.
