### ISSUE TITLE
Swagger doesn't send matrix parameters within a request

### ISSUE THREAD

**Issue by entrix** [swagger-api/swagger-ui#5447]
Please excuse me if my answer is not correct because is use Swagger only as an external tool for testing API.

I discovered that matrix parameters doesn't send for an appropriate request:

Q | A
------------ | -------------
Bug or feature request? | Bug
Which Swagger/OpenAPI version? | 3.0.1
Which Swagger-UI version? | 3.23.0
How did you install Swagger-UI? | Copy distribution from master
Which broswer & version? | Chrome (75.0.3770.100)
Which operating system? | Windows 10 Pro

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: test
  version: 1.0.0
servers:
- url: /rest-service/
paths:
  /rest/testRequest:
    post:
      description: update params
      operationId: updateParams
      parameters:
      - name: param1
        in: path
        required: true
        style: matrix
        schema:
          type: integer
          format: int32
      - name: param2
        in: path
        required: true
        style: matrix
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
```

Swagger-UI configuration options: default configuration

?yourQueryStringConfig: see screenshot

### Describe the bug you're encountering
Matrix parameters are ignored

### To reproduce...
ust send request with matrix parameters

### Expected behavior
Parameters sends along with a request in query string

### Screenshots
![Image](https://i.ibb.co/kGF9YDC/example.png)

**Comment by hkosova** [comment]
The correct way to define matrix parameters is as follows (see [this link](https://stackoverflow.com/a/44697098/113116) for details):
```yaml
paths:
  /rest/testRequest{param}:
    post:
      description: update params
      operationId: updateParams
      parameters:
      - name: param
        in: path
        required: true
        style: matrix
        explode: true
        schema:
          type: object
          properties:
            param1:
              type: integer
              format: int32
            param2:
              type: string
          required:
            - param1
            - param2
```
When using "try it out", enter the parameter list as a JSON object:
```
{"param1": 42, "param2": "foo"}
```
and the request will be sent to:
```
<your-server>/rest-service/rest/testRequest;param1=42;param2=foo
```

**Comment by entrix** [comment]
Thanks!
