### ISSUE TITLE
`Add item` to array button hidden when array is not full, after `Remove item`

### ISSUE THREAD

**Issue by JDUNNIN** [swagger-api/swagger-ui#5448]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Eclipse internal web browser (Internet Explorer 7 compatibility mode)
 - Version:  (Eclipse Platform Version: 4.6.3)
 - Method of installation: Embedded in Eclipse based software
 - Swagger-UI version: 2.2+ (unsure of exact version, will try find)
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
Swagger UI running in a Jetty server and loaded using Eclipse's internal web browser/

Example Swagger/OpenAPI definition:
```swagger.json
{
  "swagger" : "2.0",
  "info" : {
    "description" : "",
    "version" : "1.0.0",
    "title" : "person"
  },
  "host" : "localhost:8080",
  "basePath" : "/name",
  "schemes" : [ "https", "http" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : {
    "/" : {
      "post" : {
        "tags" : [ "person" ],
        "operationId" : "postBug",
        "parameters" : [ {
          "in" : "body",
          "name" : "postBug_request",
          "description" : "request body",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/postBug_request"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/postBug_response_200"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "postBug_request" : {
      "type" : "object",
      "properties" : {
        "details" : {
          "type" : "object",
          "properties" : {
            "PERSON" : {
              "type" : "object",
              "properties" : {
                "name_array" : {
                  "type" : "array",
                  "items" : {
                    "type" : "string",
                    "maxLength" : 32
                  },
                  "maxItems" : 5,
                  "minItems" : 0
                }
              }
            }
          }
        }
      }
    },
    "postBug_response_200" : {
      "type" : "object",
      "properties" : {
        "details" : {
          "type" : "object",
          "properties" : {
            "PERSON" : {
              "type" : "object",
              "properties" : {
                "name_array" : {
                  "type" : "array",
                  "items" : {
                    "type" : "string",
                    "maxLength" : 32
                  },
                  "maxItems" : 5,
                  "minItems" : 0
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Swagger-UI configuration options:
```js
None
```

### Describe the bug you're encountering
The `Add item` button for adding elements to an array is not being added back to the UI following an array moving from full state (e.g. 5/5 elements) to non-full (4/5 elements). 

### To reproduce...
1. Open Swagger UI using provided yaml file in Eclipse's internal browser.
2. Click `expand operations` button.
3. In the parameters section, click `Add item` button 5 times. Expect the `Add item` button to disappear as the array is full, it does.
4. Click the `Delete item` button.
5. Expect the `Add item` button to re-appear as the array is no longer full, but it does not.

Similarly, using an external browser such as Firefox 68.0 (64-bit), results in a similar behaviour in that `Delete item` does cause the `Add item` button to be displayed, but the `Delete last item` button does not.

### Expected behavior
Upon clicking the `Delete item` or `Delete all items` or `Delete last item` buttons, the `Add item` button should be available i.e. anytime the array is not full, the `Add item` button should be displayed.

### Screenshots
The array starts as empty.
<img width="956" alt="initial_state" src="https://user-images.githubusercontent.com/25950902/60882003-d95e0380-a23e-11e9-8abb-e3e83d4a889c.png">

I have added 5 items and the `Add item` button is hidden, all good so far.
<img width="950" alt="full_array_state" src="https://user-images.githubusercontent.com/25950902/60882018-e4b12f00-a23e-11e9-9dfa-7377245e70e5.png">

I press the `Delete item` button and the `Add item` button is not visible, so I can no longer add to the array. This error state also occurs if any of the delete buttons are pressed, I am forced to refresh the page.
<img width="950" alt="not_full_no_add_state" src="https://user-images.githubusercontent.com/25950902/60882030-ebd83d00-a23e-11e9-9047-54118aa73b48.png">

**Comment by shockey** [comment]
We're no longer working on or supporting the 2.x series of the UI - please upgrade to v3.

Thanks for the report, though!
