### ISSUE TITLE
Swagger UI is displaying actual data as Example Values

### ISSUE THREAD

**Issue by HarithK92** [swagger-api/swagger-ui#5451]
I haven't specified any sample/example responses in the code but Swagger UI uses the actual values in the database to create example values. or rather values I have used with Swagger UI.
### Screenshots
 
![image](https://user-images.githubusercontent.com/34083662/60946602-3e335f80-a30c-11e9-853c-971267e8423e.png)
 
Is it possible to disable this option or Is there a workaround for this?

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
