### ISSUE TITLE
Selecting "--" choice in dropdown throws error

### ISSUE THREAD

**Issue by dalbani** [swagger-api/swagger-ui#5452]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 75
 - Method of installation: Docker
 - Swagger-UI version: 3.23.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

OpenAPI definition:
```yaml
openapi: "3.0.0"
info:
  title: Testcase API
  version: 2.0.0
paths:
  '/endpoint':
    get:
      parameters:
        - name: type
          in: query
          example: fruit
          schema:
            type: string
            enum:
              - fruit
              - vegetable
              - drink
      responses:
        '200':
          description: 200 response
```

### Describe the bug you're encountering

Selecting the `--` choice in a dropdown menu throws an error about not being able to render the component.

### To reproduce...

1. Go to the Swagger Editor
2. Copy/paste the YAML definition
3. Select the `--` choice in the dropdown for the `type` parameter.
4. See following error:
```😱 Could not render this component, see the console.```

### Expected behavior
No error should be reported to the user, the dropdown should support being set to `--`.

### Screenshots
![image](https://user-images.githubusercontent.com/1470270/60966059-ac315400-a317-11e9-99a3-ca1af5018430.png)

### Additional context or thoughts
The issue has apparently to do with code at https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/layout-utils.jsx#L187.

![image](https://user-images.githubusercontent.com/1470270/60966009-915edf80-a317-11e9-9f4f-2740dd1d9f15.png)

The value of `this.state.value` is `null` for the `--` select option, thus failing when trying to access the `.toJS` property.

Or am I simply missing something obvious in my OpenAPI definition?!?

**Comment by shockey** [comment]
@dalbani, just curious, is this working for you in older versions (e.g. `3.22.x`)?

**Comment by dalbani** [comment]
Oh, indeed, you're right. I didn't check from which version the issue appeared.

**Comment by shockey** [comment]
Also, I'm curious -- did you have to do any work to get the stack trace in your screenshot (e.g. loading source maps), or was it there by default?

**Comment by dalbani** [comment]
No I didn't have to do anything special. I was using the Docker image by the way.
Do you mean this debug information shouldn't have been there in the first place?

**Comment by hkosova** [comment]
@shockey fyi this issue affects OAS2 too:
https://petstore.swagger.io/?url=https://vocadb.net/swagger/docs/v1#/ActivityEntryApi/ActivityEntryApi_GetList

**Comment by shockey** [comment]
> Do you mean this debug information shouldn't have been there in the first place?

@dalbani not at all, I was just happy to see our source maps working for you 😄

**Comment by shockey** [comment]
Fixed!

Will ship this tonight. Thanks for the report @dalbani!
