### ISSUE TITLE
Regression: Responses without content are displayed with empty Schema and Example Value

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#5453]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: any
 - Method of installation: https://editor.swagger.io
 - Swagger-UI version: 3.23.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.2
info:
  title: Response without a schema
  version: 1.0.0
paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
```

### Describe the bug you're encountering
Responses without `content` are now displayed with empty "Example Value" and "Schema" sections. This is a regression introduced in v. 3.23.0 by swagger-api/swagger-ui/pull/5427.

### Expected behavior
Responses without `content` should NOT have the "Example Value" and "Schema" sections.

### Screenshots
![Empty "Example Value" and "Schema" sections in a response](https://user-images.githubusercontent.com/8576823/60987180-bcfabd80-a349-11e9-8dea-422d677865e9.png)

**Comment by shockey** [comment]
Thanks @hkosova!

Based on your report, this appears to be limited to us incorrectly rendering an empty ModelExample -- that is, we aren't ever _not_ displaying valid data. As such, I think a hot fix isn't necessary, we can fix this in the next couple of weeks and ship it out on a Friday.

Let me know if I've missed something, or you disagree!
