### ISSUE TITLE
Regression: OAS2 response examples are not displayed

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#5458]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: any
 - Method of installation: https://editor.swagger.io
 - Swagger-UI version: 3.23.0
 - Swagger/OpenAPI version: OpenAPI 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
swagger: "2.0"
info:
  title: test
  version: 1.0.0
paths:
  /foo1:
    get:
      summary: Response without a schema
      produces:
        - application/json
      responses:
        200:
          description: Successful response
          examples:
            application/json:
              foo: custom value
  /foo2:
    get:
      summary: Response with schema
      produces:
        - application/json
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Foo'
          examples:
            application/json:
              foo: custom value

definitions:
  Foo:
    type: object
    properties:
      foo:
        type: string
        example: bar
```

### Describe the bug you're encountering
swagger-api/swagger-ui/pull/5427 seems to have introduced an issue where OAS2 response `examples` are not displayed if the response does not have a `schema` defined. Previous versions of Swagger UI rendered the response `examples` in this case.

### Expected behavior
Both `/foo1` and `/foo2` display the following response example, as it was in Swagger UI v. 3.22.3:

```json
{
  "foo": "custom value"
}
```
![Response example in Swagger UI](https://user-images.githubusercontent.com/8576823/61133200-99f51880-a4c5-11e9-918e-5ecb828f1879.png)

### Actual behavior
`/foo1` does not display any example.
`/foo2` displays schema-based example instead of the custom example from `examples`.

![Wrong response examples](https://user-images.githubusercontent.com/8576823/61133007-3f5bbc80-a4c5-11e9-9533-04ae7781bd93.png)

**Comment by shockey** [comment]
(P1 in order to push this above #5453 and #5455)

**Comment by shockey** [comment]
thanks as always @hkosova!

**Comment by shockey** [comment]
## _wait a second_

My implementation missed the mark, it's generating `custom value` instead of the entire object.

Reopening.

**Comment by shockey** [comment]
:shipit:
