### ISSUE TITLE
index.js in latest release 3.23.1 is empty

### ISSUE THREAD

**Issue by Mykolas-Zenitech** [swagger-api/swagger-ui#5469]
Please fix this - cause its breaking builds!

**Comment by shockey** [comment]
@Mykolas-Zenitech, I assume you're using `swagger-ui-react`?

We identified the problem with the version right after it was release, but it looks like npm silently failed to process our `npm unpublish` for it.

I've opened a ticket with npm support to get it pulled off the registry. If we don't hear back by tomorrow morning, we're going to do another UI release to bump the version and solve this.

Sorry for the inconvenience!

**Comment by shockey** [comment]
`swagger-ui-react@3.23.1` is now unpublished 👍

@Mykolas-Zenitech, you should be good to go now. Let me know if you're seeing any lingering issues on your end!

**Comment by Mykolas-Zenitech** [comment]
I confirm it is fixed - thanks for prompt response!
