### ISSUE TITLE
Misaligned Parameters columns

### ISSUE THREAD

**Issue by Mykolas-Zenitech** [swagger-api/swagger-ui#5472]
![image](https://user-images.githubusercontent.com/37137051/61372843-143fe700-a890-11e9-849a-a9c4511b1283.png)

Same view for responses: first column takes most of the space.

I use Chrome: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!

**Comment by shockey** [comment]
(This looks like a problem that needs fixing, but I have no way to reproduce it, and I have no idea if you're on the latest version. The issue template gives us answers to this sort of thing.)
