### ISSUE TITLE
Is OIDC support with Swagger UI on the way?

### ISSUE THREAD

**Issue by OLDOY** [swagger-api/swagger-ui#5473]
Hi there !

I've been trying to setup authorization for our service with OIDC (KeyCloak) following the official documentation: (https://swagger.io/docs/specification/authentication/openid-connect-discovery/) 

At the end of the documentation, it's shown that Swagger UI is not supported by OIDC yet and relate to this issue: https://github.com/swagger-api/swagger-ui/issues/3517

My question is the following: Is there any update/roadmap about supporting OIDC with Swagger UI? The issue is from August 2017 and I would like to know if there is any update on that topic.

Cheers,
Olivier

**Comment by webron** [comment]
There's nothing in our immediate roadmap to add support to OIDC, but of course, PRs are welcome. If you'd like to support the ticket, please 👍 the original linked ticket.

**Comment by OLDOY** [comment]
Thank you for your quick response !

**Comment by hkosova** [comment]
OIDC is now supported in Swagger UI v 3.38.0.
