### ISSUE TITLE
broken new Line parsing YAML 

### ISSUE THREAD

**Issue by HenriPro** [swagger-api/swagger-ui#5475]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome, safari, firefox
 - Method of installation: dist bundle, swagger.io demo
 - Swagger-UI version: 3.18.3
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

![Screen Shot 2019-07-17 at 4 22 50 PM](https://user-images.githubusercontent.com/15886900/61418416-41e85880-a8af-11e9-91a4-1541180d1f1b.png)

Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'
info:
  description: broken line break
  version: 1.0
basePath: /test
schemes:
  - https
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: apikey
paths:
  /test/brokennewline:
    get:
      tags:
        - Broken New Line
      summary: Broken new Line example
      description: Broken new line YAML example
      operationId: BrokenNewLine
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - ApiKeyAuth: []
      parameters:
        - name: X-applicationNameA
          description: |
            This works note the dash on the line bellow
            e.g. CXMOBILE-56789
          in: header
          required: true
          type: string 
        - name: X-applicationNameB
          description: | 
            This should be also be two lines
            e.g. CXMOBILE156789
          in: header
          required: true
          type: string           

```

### Describe the bug you're encountering

Fails to render new lines for parameter description as expected.
Both parameter descriptions should be two lines. Only the first one is rendered with a <br>

The second without the dash does not get split into a new line. Adding a character like a comma or dash does result in correct render.

### To reproduce...

Load yaml file 

### Expected behavior
All new lines in parameter description to be rendered as separate lines in html

**Comment by shockey** [comment]
Might be best to just remove our plaintext optimization to solve this:

https://github.com/swagger-api/swagger-ui/blob/15cdfe14dd2df48a91cf9088b6605b75dd3cee25/src/core/components/providers/markdown.jsx#L22-L27
