### ISSUE TITLE
Add a callback for when all endpoints have been expanded 

### ISSUE THREAD

**Issue by dblock** [swagger-api/swagger-ui#550]
When you use `docExpansion: list` there's a bunch of network requests happening, then everything is expanded. In the meantime it just looks like it hangs for the user.

First, it would be nice to add a callback for when the expansion has finished. Right now I hack this:

``` coffeescript
  window.swaggerUi = new SwaggerUi
    onComplete: (swaggerApi, swaggerUi) ->
      swaggerUi.showMessage('loading API metadata ...')
      setTimeout( =>
          $('#message-bar.swagger-ui-wrap').fadeOut(300, => @remove())
        3000)
    docExpansion: "list"
```

Maybe Swagger-UI could also display something with each endpoint being expanded asynchronously to show progress.

**Comment by fehguy** [comment]
this is fixed.  The whole multi-file requests have been managed so callbacks are only called once.
