### ISSUE TITLE
CURL header authorization not escaping $

### ISSUE THREAD

**Issue by thomas-reinke** [swagger-api/swagger-ui#5501]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Chrome, Firefox
 - Version: all
 - Method of installation: git
 - Swagger-UI version: [unknown - recently deployed from git]
 - Swagger/OpenAPI version: [1.0.0]

### Describe the bug you're encountering
If Bearer authorization is used, and an authorization header value containing '$' is used, the curl command line option cannot be cut and paste, because
a) the $ are not escaped,
b) the string is quoted using double quotes, resulting in $ being interpreted as a shell variable and being removed.

An example curl command provided by swagger for use on the command line:

curl -X GET "http://test.examplecom/api/companies" -H  "accept: application/json" -H  "Authorization: Bearer r4ME2Jl$2BOwaJTZaWY7VoJ$2B7YzKaVELg8g33Kd2yyoW2WoxE3s3576VgeDDs$2BP0QCRw1SdlvI$2BoFIvvheUTgP7MB3$2FTAf1fDph1$2FxV4VywiKxAMLQogMIt95AiJD0l5515Bi7IB4xIOmHQyCKv$2BIEIRmXjGensm6MI$2FTZY0X3aUh8m$2B00jCjFedKaKnnAxCE$3D"

This above example, will NOT result in the bearer token being presented to the API correctly, all the $ symbols will be removed by the shell before they get to CURL.

Solution is dependent, I suppose - either proper escaping, or use of single quotes, would accomplish a fix.

### Expected behavior
Should be able to simply cut and paste the string into a shell for execution..

**Comment by hkosova** [comment]
Thanks for the report! This issue is already tracked in #5390.

**Comment by webron** [comment]
Closing as duplicate.
