### ISSUE TITLE
Something wrong when I used the annotation @Validated 

### ISSUE THREAD

**Issue by fengcharles** [swagger-api/swagger-ui#5506]
- OS: [macOS]
 - Browser: [chrome]
 - Version: [2.6.1]
 - Method of installation: [npm]
 - Swagger-UI version: [2.6.1]
 - Swagger/OpenAPI version: [Swagger 2.0]

When i not use this annotation  @Validated （org.springframework.validation.annotation）
the UI show like this ,and  This is the format I want.

![image](https://github.com/fengcharles/HelloWord/blob/master/%E6%B2%A1%E7%94%A8%E4%B9%8B%E5%89%8D.jpg?raw=true)

But when i use the annotation @Validated In my method.  
The UI shows
![image](https://github.com/fengcharles/HelloWord/blob/master/after.jpg?raw=true)

This is my controller code:

`
@ApiOperation(value = "导出财务销售数据",notes = "导出财务销售数据")
@PostMapping(value = "/exportFinanceReport")
public void exportFinanceReport(HttpServletResponse response,@Validated ReportSaleReqDto req){.....}
`
@Data
@ToString
@ApiModel(description = "请求参数")
public class ReportSaleReqDto {

    @NotNull(message = "开始时间不能为空")
    @ApiModelProperty(value = "数据开始时间",required = true)
    private Date startDate;

    @NotNull(message = "结束时间不能为空")
    @ApiModelProperty(value = "数据结束时间",required = true)
    private Date endDate;

    @ApiModelProperty(value = "订单类型")
    private Integer orderType;

    @ApiModelProperty(value = "发货方式")
    private Integer purchaseType;

}`

**Comment by fengcharles** [comment]
I want to decorate my code with @Validated, and I want the UI to look like the one shown above.

**Comment by webron** [comment]
@fengcharles - this looks like an issue with whichever library you use to generate your API definition, I guess in this case it's Springfox. You'd need to ask them how to achieve what you want, as the UI just renders the definition, it doesn't control it.
