### ISSUE TITLE
Docs.shebang: undefined is not a function 

### ISSUE THREAD

**Issue by dblock** [swagger-api/swagger-ui#551]
Confirmed that this is a problem with the latest dist, too.

in `Docs.shebang`, `var fragments = $.param.fragment().split('/');` is failing for me, `param` is a function, and `$.param.fragment()` is undefined.

I am not sure whether this is a conflict or something else. The entire app is in https://github.com/artsy/doppler and you can see this in https://developers-staging.artsy.net/playground.

**Comment by javabrett** [comment]
> I had this issue when jQuery was included twice in the page.

This happened to me when trying to use Tampermonkey with Swagger UI, with a script which did `// @require http://code.jquery.com/jquery...`, resulting in two copies of jQuery being loaded. Removing the `@require` fixes that.
