### ISSUE TITLE
system.js:461 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by JavaHelper** [swagger-api/swagger-ui#5523]
I am getting below error. I am using Spring Boot Data Jpa example, with @OneToMany and @ManyToOne example.  Also, this issue comes with @ManyToMany relationship as well.

```
<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>${springfox-swagger-version}</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>${springfox-swagger-version}</version>
			<exclusions>
				<exclusion>
					<groupId>io.swagger</groupId>
					<artifactId>swagger-models</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

![image](https://user-images.githubusercontent.com/8208031/62706613-8af27f00-ba0d-11e9-91b8-c5d5674e50d8.png)

**Comment by webron** [comment]
Please follow the issue template when filing a ticket. It's there to avoid back and forth for initial information that's needed to solve issues. It also contains information specifically about Springfox.

**Comment by JavaHelper** [comment]
I apologized for the same. Could you please guide me on how to fix this issue ? Or it is yet to be taken care into springfox latest version ?

**Comment by javaHelper** [comment]
Any updates on this please ? I am facing same issue 2.9.2
