### ISSUE TITLE
Numeric string example displayed as a number in request body

### ISSUE THREAD

**Issue by pnederlof** [swagger-api/swagger-ui#5528]
### Numeric string example displayed as a number in request body
When a property has the type String and the example is numeric, the Request Body part displays it as a number, so without quotes. This issue can be resolved by putting single quotes around the number, but could be determined by looking at the properties' type. 

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Swagger Petstore
  description: 'This is a simple example'
  version: 1.0.0
paths:
  /pet:
    put:
      tags:
      - pet
      summary: Update an existing pet
      operationId: updatePet
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            examples:
              Numeric String:
                value:
                  name: 123
              Numeric String with quotes:
                value:
                  name: '123'
              Alphanumeric String:
                value:
                  name: name
        required: true
      responses:
        400:
          description: Invalid ID supplied
          content: {}
```

### Expected behavior
Display numeric String examples as Strings with double quotes in the Request body

### Screenshots
![image](https://user-images.githubusercontent.com/26160644/62861205-f89af580-bd02-11e9-8ae4-d43742210310.png)

**Comment by webron** [comment]
The behavior is as expected. According to the spec, examples SHOULD follow the type whatever type they are describing, but this it is not required. This was done explicitly to avoid having tools check whether the examples make sense or not. While in the describe case it be easy, it gets more complicated with objects and so on.

**Comment by shockey** [comment]
To add on here: the example above is simple enough, but if we started coercing example value types based on the schema, it would open up a whole can of worms... 

Say my schema is `type: array` and my example value is `"1,2,3"`... should that yield an array of `[1, 2, 3]`? or `["1", "2", "3"]`? or `["1,2,3"]`?

Another interesting one: `type: string` and example value `null`. Does that yield `"null"` or `""`?

This is a lot of editorialization for a tool to be doing 😅 

---

Regardless, thanks for the report @pnederlof! Even the ones we don't act on help us make Swagger UI better over time.

**Comment by Oduig** [comment]
For anyone looking, this also happens with `example: '123'` with recent OpenAPI and Swagger UI versions.

There are two alternative ways of fixing this:

- Prefix the number by a zero, e.g. `example: '0123'`. This will turn the example into a string.
- Add additional quotes e.g. `example: '"123"'`. 

In my humble opinion, this behavior is very unintuitive and it should default to the type used in the `type` property, if possible, and then fall back to verbatim examples if it's hard or impossible to convert.

**Comment by mathis-m** [comment]
@tim-lai @Oduig Thanks for the ping. I am analyzing this currently. Looks like the internal example generator generates the correct example but within the ui components in case of multiple examples (possibly ExampleValueRetainer) the value is being wrongly stored due to back and forth Immutable.js <-> js.

**Comment by Oduig** [comment]
> @tim-lai @Oduig Thanks for the ping. I am analyzing this currently. Looks like the internal example generator generates the correct example but within the ui components in case of multiple examples (possibly ExampleValueRetainer) the value is being wrongly stored due to back and forth Immutable.js <-> js.

Personally I have just been using a single `example:`, for what it's worth. Perhaps the leading zero is something to go on, as that might be easier to search for in code than a bunch of type casts 😉

**Comment by mathis-m** [comment]
@Oduig no have a look at https://editor.swagger.io/?url=https://gist.githubusercontent.com/mathis-m/8879f95fc6aebf7c65c698ff44ae6b8e/raw/d351c1ced1f21d03dc5b9d639e9af7a749330297/bLPoA7dT6e.txt `example:` is the one that works in expected way.

**Comment by Oduig** [comment]
@mathis-m It looks like this was a bug but it was fixed. It works as intended in the latest release (3.42.0) and when I upgraded our problem disappeared. (Our previous version was downloaded only about a month ago.) Good to see improvements are being made to the UI! :)
