### ISSUE TITLE
error in shred.bundle url based @ doesn t work

### ISSUE THREAD

**Issue by sebadiaz** [swagger-api/swagger-ui#553]
A discussion on the issue from original code parseUri
http://blog.stevenlevithan.com/archives/parseuri/comment-page-5#comment-312053

I have replaced 
 /^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/
by
/^(?:(?![^:@?]+:[^:@?\/]*@?)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@?]*)(?::([^:@?]*))?)?@?)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/

**Comment by fehguy** [comment]
Hi, I really need a sample URL that is failing before patching this.  Please reopen if you can supply one.

**Comment by sebadiaz** [comment]
https://opensocial.atlassian.net/wiki/display/OSD/3.0+REST+API+Updates

@me and @self are in open social

http://www.lbenitez.com/2012/05/how-to-post-events-into-opensocial.html

**Comment by fehguy** [comment]
addressed in https://github.com/swagger-api/swagger-ui/commit/7d3d1004013d28a2a60aa519334664baceee079d
