### ISSUE TITLE
Cannot View Swagger-UI via Docker for Win

### ISSUE THREAD

**Issue by 8thHalfHour** [swagger-api/swagger-ui#5533]
### Q&A (please complete the following information)
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 78.0.3880.4
 - Method of installation: Docker for Windows
 - Swagger-UI version: 3.23.5
 - Swagger/OpenAPI version: N/A

### Content & configuration
1. I installed swagger-ui via docker, using the commands:
```
docker pull swaggerapi/swagger-ui
docker run -p 80:8080 swaggerapi/swagger-ui
```

2. I opened my browser and tried to access https://localhost:8080/swagger-ui.html. No page was found.

Swagger/OpenAPI definition:
N/A

Swagger-UI configuration options:
N/A

### Screenshots
![image](https://user-images.githubusercontent.com/44852729/63189059-e5946800-c017-11e9-942c-0ec03dbdfbce.png)

### How can we help?
I'd like to know what I'm doing wrong and fix it, if possible. Thank you, in advance.

**Comment by shockey** [comment]
Hi @8thHalfHour!

Two things:
1. `-p 80:8080` means "map my host's port 80 to the Docker container's port 8080"
2. the Docker container serves Swagger UI at `/`, not `/swagger-ui.html`.

You should be able to see Swagger UI if you open `http://localhost:80/`.

**Comment by 8thHalfHour** [comment]
I see; I was following this tutorial, here, which indicated it was at `http://localhost:80/swagger-ui.html`. I will give it a go at `http://localhost:80` and report back!

**Comment by 8thHalfHour** [comment]
Okay, so oddly, it only worked when I changed the Windows port to 8080 also. . . so I am guessing something was conflicting with port 80. Thanks! All is working now!

**Comment by shockey** [comment]
Glad to hear it, closing!

**Comment by jayadityan** [comment]
Hi I am also facing similar issue. Can you please help?

I am trying using http://localhost:8080/ but getting empty page

Can you help here? I am using my work laptop is there any restriction?

**Comment by VardanyanSedrak** [comment]
How did you solve this problem, because I am also faced with this problem.

**Comment by vit100** [comment]
same issue
