### ISSUE TITLE
Swagger UI is creating incorrect json value for enum element Enumarated to String

### ISSUE THREAD

**Issue by govi20** [swagger-api/swagger-ui#5534]
I have a following java model class to hold the JSON payload

```
 public class Application {
    private long applicationId;
    private String email;
    private String resumeText;

    @Enumerated(EnumType.STRING)
    private ApplicationStatus status;
    // Getter and Setting
}

```
Swagger UI created following JSON model for above, which is incorrect.

```
  {
      "applicationId": 0,
      "email": "string",
      "resumeText": "string",
      "status": "ApplicationStatus{value='APPLIED'}"
    }
```
Correct value for status should be plan string `"status": "APPLIED"`

**Comment by webron** [comment]
That looks like an issue with whichever library you use to generate your API definition. Do you use swagger-core? Springfox? A different one?

**Comment by govi20** [comment]
Springfox. Do you want me to raise the issue there?

**Comment by webron** [comment]
Yup, there's not much we can do about it from Swagger UI's side.
