### ISSUE TITLE
allowableValues Ignored by the UI

### ISSUE THREAD

**Issue by maryatplatfora** [swagger-api/swagger-ui#554]
I have an Enum defined in code. I'm trying to restrict the values shown in the Model with this:

```
 @ApiModelProperty(value="One of the defined types.", allowableValues = "CSV,HIVE,PROTON,APACHE,REGEX,LINE,JSON,AVRO,DYNAMIC,XML,PLUGIN,LENS")
    public Kind getAdapterType() {
        return adapterType;
    }
```

The UI is ignoring the list I provided.

**Comment by mohsen1** [comment]
In 2.0 specs you can use `enum` in your parameter and UI will show a dropdown for that. for 1.2 we show a text filed which works but don't show a dropdown.
