### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rattada** [swagger-api/swagger-ui#5544]
i am using Swagger 4.0.1 version, still i am getting Maximum call stack size exceeded.

### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by webron** [comment]
There's no 'Swagger 4.0.1' Please make sure you're posting your issue in the right project. If you find out that Swagger UI is the right project, make sure to fill in all the details in the issue template so we can assist you better.
