### ISSUE TITLE
Swashbuckle with Authorize button

### ISSUE THREAD

**Issue by kambleaa007** [swagger-api/swagger-ui#5545]
### Q&A (please complete the following information)
 - OS: Win10
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### How can we help?

I want to use Authorize OAuth2 button for implicit token selection
rather than Writting `Bearer xxxxxx`

**Comment by hkosova** [comment]
Since this is a Swashbuckle question please ask it in the Swashbuckle repository.

https://github.com/domaindrivendev/Swashbuckle
https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by kambleaa007** [comment]
@hkosova  Ok do you know any solution to this???

**Comment by hkosova** [comment]
@kambleaa007 Sorry I'm not familiar with Swashbuckle, it's a different project. I'd recommend that you check out Swashbuckle documentaiton, and if no information is available, file a ticket with them for further support.
