### ISSUE TITLE
Swagger UI overrides accept header parameter - openApi 3.0

### ISSUE THREAD

**Issue by henriqueweiand** [swagger-api/swagger-ui#5567]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Swagger/OpenAPI version: OpenAPI 3.

### Content & configuration

Swagger/OpenAPI definition:
```yaml
paths:
  /v1/auth/login:
    post:
      tags:
        - admin
      summary: Login
      operationId: loginAdmin
      description: |
        Realiza o login na aplicação
      responses:
        '200':
          description: login success
        '422':
          description: 'invalid input, object invalid'
      parameters:
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            example: application/json
            default: application/json
        - name: Accept
          in: header
          required: true
          schema:
            type: string
            example: application/json
            default: application/json
```

### Problem:
My header when testing always converts accpet to * / * and I need to keep it fixed in application / json

### Screenshots
![Screen Shot 2019-08-26 at 10 06 10](https://user-images.githubusercontent.com/6539492/63692927-2bf08080-c7e9-11e9-8051-0592fbbade99.png)

**Comment by hkosova** [comment]
That's expected - the OpenAPI Specification says:
> If `in` is `"header"` and the `name` field is `"Accept"`, `"Content-Type"` or `"Authorization"`, the parameter definition SHALL be ignored.

The `Accept` and `Content-Type` headers should be defined via request/response media types instead:
```yaml
paths:
  /v1/auth/login:
    post:
      ...
      requestBody:
        content:
          application/json:  # <--------
            schema:
              ...
      responses:
        '200':
          description: login success
          content:
            application/json:  # <--------
              schema:
                ...
        '422':
          description: invalid input, object invalid
```

**Comment by henriqueweiand** [comment]
Cool! my problem was the lack of the answer model

**Comment by sillekyatha** [comment]
How can the same be achieved with Get requests without request body?

**Comment by herbherbherb** [comment]
Having similar question, any suggestion on how can we override header field "Accept"?

**Comment by osteel** [comment]
Same issue here. Made sure to upgrade to the latest version (3.49.0) but it still sets the `accept` header to `*/*` instead of `application/vnd.api+json` for GET requests with no response body.

**Comment by laitinenp** [comment]
> Having similar question, any suggestion on how can we override header field "Accept"?

I have been wondering the same. For instance if your endpoint should provide response for the GET request in different formats for different purposes or clients, e.g. application/json, text/csv and so on.
