### ISSUE TITLE
default zero not allowed in parameters

### ISSUE THREAD

**Issue by readyjamil** [swagger-api/swagger-ui#5573]
"pageNumber": {
			"name": "pageNumber",
			"in": "query",
			"type": "integer",
			"required": true,
			"description": "Page number is location of page",
			"default": 0
		},

![image](https://user-images.githubusercontent.com/20238596/63853341-0d8caf80-c9b8-11e9-8d9f-20f25ec6a490.png)

**Comment by shockey** [comment]
@readyjamil what's the problem here?

**Comment by hkosova** [comment]
@shockey If a parameter has the default/example value of 0, "try it out" does not initialize the parameter value with 0. If you change 0 to, say, 5, the default/example value is initialized correctly during "try it out".

```yaml
swagger: '2.0'
info:
  title: Zero as default/example param value
  version: 0.0.0
paths:
  /foo:
    get:
      parameters:
        - name: bar
          in: query
          required: true
          type: integer
          x-example: 0
        - name: baz
          in: query
          type: integer
          default: 0
      responses:
        '200':
          description: OK
```

```yaml
openapi: 3.0.2
info:
  title: Zero as default/example param value
  version: 0.0.0
paths:
  /foo:
    get:
      parameters:
        - name: param1
          in: query
          required: true
          schema:
            type: integer
          example: 0

        - name: param2
          in: query
          required: true
          schema:
            type: integer
            example: 0

        - name: param3
          in: query
          required: true
          schema:
            type: integer
          examples:
            zero:
              value: 0
            one:
              value: 1
  
        # Works here though
        - name: param4
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: OK
```

**Comment by bitnot** [comment]
I have noticed the same issue: when `example` value for an integer parameter is set to `0`, UI does not render the value in the input of the "try it out" form.

```yaml
            schema:
                type: integer
                enum: [0, 1, 2, 3]
                example: 0 # does not work
```

```yaml
            schema:
                type: integer
                enum: [0, 1, 2, 3]
                example: 3 # works
```

```yaml
            schema:
                type: integer
                enum: [0, 1, 2, 3]
                example: "0" # also works, even though the type is wrong
```

**Comment by bitnot** [comment]
To reproduce replace `https://petstore.swagger.io/v2/swagger.json` with `https://gist.githubusercontent.com/bitnot/289061bd7d122bd666029fcde5e011bf/raw/3d96dbabd8c36af3d16580038c057964959d6b5e/petstore.swagger.json`

**Comment by SledgeHammer01** [comment]
> @shockey If a parameter has the default/example value of 0, "try it out" does not initialize the parameter value with 0. If you change 0 to, say, 5, the default/example value is initialized correctly during "try it out".
> 
> ```yaml
> swagger: '2.0'
> info:
>   title: Zero as default/example param value
>   version: 0.0.0
> host: httpbin.org
> schemes: [https, http]
> paths:
>   /get:
>     get:
>       parameters:
>         - name: bar
>           in: query
>           required: true
>           type: integer
>           x-example: 0
>         - name: baz
>           in: query
>           type: integer
>           default: 0
>       responses:
>         '200':
>           description: OK
> ```
> 
> ```yaml
> openapi: 3.0.2
> info:
>   title: Zero as default/example param value
>   version: 0.0.0
> servers:
>   - url: https://httpbin.org
>   - url: http://httpbin.org
> paths:
>   /get:
>     get:
>       parameters:
>         - name: param1
>           in: query
>           required: true
>           schema:
>             type: integer
>           example: 0
> 
>         - name: param2
>           in: query
>           required: true
>           schema:
>             type: integer
>             example: 0
> 
>         - name: param3
>           in: query
>           required: true
>           schema:
>             type: integer
>           examples:
>             zero:
>               value: 0
>             one:
>               value: 1
>   
>         # Works here though
>         - name: param4
>           in: query
>           schema:
>             type: integer
>             default: 0
>       responses:
>         '200':
>           description: OK
> ```

Is this going to be fixed?
