### ISSUE TITLE
v3.23.7 breaks try-it-out on POST method

### ISSUE THREAD

**Issue by zhsj** [swagger-api/swagger-ui#5581]
### Q&A (please complete the following information)
 - OS: [e.g. Linux Debian testing]
 - Browser: [Chromium]
 - Version: [76.0.3809.100]
 - Method of installation: [dist assets]
 - Swagger-UI version: [v3.23.7]
 - Swagger/OpenAPI version: [Swagger 2.0]

### Content & configuration

Just http://petstore.swagger.io/

Example Swagger/OpenAPI definition:

https://petstore.swagger.io/v2/swagger.json

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

The execute button on POST method doesn't trigger an HTTP request

### To reproduce...

1. Open http://petstore.swagger.io/#/store/placeOrder
2. Click "Try it out"
3. Click "Excute"

### Expected behavior

An HTTP request is sent

This works on v3.23.6

### Screenshots
![image](https://user-images.githubusercontent.com/227180/64108392-401b1b80-cdaf-11e9-9d8b-db6bd53328be.png)

**Comment by shockey** [comment]
Thanks for the report, publishing a hotfix in a few minutes!
