### ISSUE TITLE
How to set request header in swagger-ui-react component?

### ISSUE THREAD

**Issue by GloriaCHL** [swagger-api/swagger-ui#5584]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Method of installation: yarn
 - Swagger-UI-React version: 3.23.8
 - Swagger/OpenAPI version: OpenAPI 3.0

Swagger-UI configuration options:
```js
import styles from './index.less';

import React from 'react';
// tslint:disable
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';
// tslint:able

const SwaggerComp = params => {
    const auth = params.authorization;
    return (
        <div className={styles.wrapper}>
         <SwaggerUI
           url="/v2/swagger-file-url"
           withCredentials
         />
       </div>
    )
};

export default SwaggerComp;
```

### How can we help?
I want to set authorization into swagger api header. I fount something [here](https://stackoverflow.com/questions/31057343/adding-basic-authorization-for-swagger-ui) but I don't know how to config in swagger-ui-react. Can I get an example?

**Comment by andreibratuleanu21** [comment]
Seems that it supports either url with specs or you can pass specs directly. I did this:

```javascript
componentDidMount() {
	fetch('/api/swaggerdefinition/'+this.props.match.params.id, {headers: { 'Authorization': 'JWT ' + window.sessionStorage.getItem('jwt') }}).then(r => r.json().then(data => {
		this.setState({swaggerSpecs: {...data}});
	}));
}

render() {
	return <SwaggerUI specs={this.state.swaggerSpecs} />
}
```

See [this file on repo](https://github.com/swagger-api/swagger-ui/blob/9253c0bf03ff83aac7b8a51dc83fe087502eef99/flavors/swagger-ui-react/index.js#L14) or [this docs](https://www.npmjs.com/package/swagger-ui-react#spec--proptypesobject)

**Comment by scheiblr** [comment]
Just, if somebody steps by:
Write a requestInterceptor which includes the token. Here I call the function `getAccessToken()` which returns the JWT.
```
const requestInterceptor = (req) => (
  {
    ...req, 
    headers: {
      Authorization: `Bearer ${getAccessToken()}`
    }
  }
);
```
Afterwards put this `requestInterceptor` into the SwaggerUI component:
```
<SwaggerUI 
    url='http://someurl/rest/'
    requestInterceptor={requestInterceptor} />
```

**Comment by hamidrezaghanbari** [comment]
> ```js
> specs
> ```

spec not specs but thank you for this good answer
