### ISSUE TITLE
Malformed or unreadable swagger supplied shown at bottom of page only in production

### ISSUE THREAD

**Issue by JFCote** [swagger-api/swagger-ui#5587]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: chrome
 - Version: Version 76.0.3809.132 (Official Build) (64-bit)
 - Method of installation: webjar
 - Swagger-UI version: 3.23.5
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

When I open swagger-ui page in my local environment, I have no error. 

http://localhost:9000/assets/lib/swagger-ui/index.html?url=/assets/swagger.yaml

When I open the same swagger-ui page, with the same url, but in prod, I get this message at the bottom of the page: "Error". 

https://cs-dev.business.stingray.com/assets/lib/swagger-ui/index.html?url=/assets/swagger.yaml

When I click on it, it shows this url:

https://online.swagger.io/validator/debug?url=https%3A%2F%2Fcs-dev.business.stingray.com%2Fassets%2Fswagger.yaml

### Screenshots

![image](https://user-images.githubusercontent.com/14336900/64201212-22f05680-ce5c-11e9-856d-e2aa6ab8a525.png)

### How can we help?

1) Why is the result of swagger-ui different in local vs prod? 
2) Why is it considered malformed? It's exactly the same spec.
3) Why is there no real error with line number provided?

**Comment by webron** [comment]
By default, Swagger UI will display the validator badge when the file is local. The reason being that the validator will not have access to read the content of the file to perform validation.

Checking why the file is considered malformed, would be an issue for the validator-badge project.

**Comment by JFCote** [comment]
@webron Did you mean "Swagger UI will NOT display the validator badge" ? That would explain why I don't see it in local.

Also, I didn't know there was a separate project for the validator-badge. Will check with them! Thanks
Closing this.

**Comment by webron** [comment]
Yes, sorry, meant to write that by default it will NOT, sorry about that.
