### ISSUE TITLE
HTTPS domain revert to http request after click try it out

### ISSUE THREAD

**Issue by JayHJ** [swagger-api/swagger-ui#5589]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
our application running on the HTTPS domain, e.g: https://myapplication.com. there are some apis on the page, and after we click the "try it out", it show use it trying to call http domain. the curl command generated is in http format.  e.g: curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Bearer XXX' -d '{"ttlSeconds": 0}' 'http://myapplication.com/v1.0/test/xxxxxx/test' 
```

### Screenshots
![pic](https://user-images.githubusercontent.com/8286945/64247640-d97a3700-cf41-11e9-9ec0-29446c3a77ef.png)

### How can we help?
our application running on the HTTPS domain, e.g: https://myapplication.com. there are some apis on the page, and after we click the "try it out", it show use it trying to call http domain. the curl command generated is in http format.  e.g: curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Bearer XXX' -d '{"ttlSeconds": 0}' 'http://myapplication.com/v1.0/test/xxxxxx/test' 

what's the possible issue for this?

**Comment by webron** [comment]
You're using a very old version of Swagger UI which we no longer support. Please update to the latest version and if the issue persists, file a new ticket.
