### ISSUE TITLE
string path parameter

### ISSUE THREAD

**Issue by odibat** [swagger-api/swagger-ui#559]
Hello,
i have a GET method but the path parameter of swagger is String. i get invalid JSon for my request:
For request 'GET /users/handleSignup/6119474c-f0e0-4bb8-b027-1636a0073854' [Invalid Json]

when i change the pameter to Integer it works fine but my id needs to be string:
im using this version of swagger:   "com.wordnik" %% "swagger-play2" % "1.3.9"

this is my method:
 @GET
    @Produces({MediaType.APPLICATION_JSON})
    @ApiOperation(
            value = "handle signup",
            notes = "confirm email",
            response = Secured.class,
            responseContainer = "List",
            nickname = "confirm user",
            httpMethod = "GET"
    )

    @ApiResponses( value = { @ApiResponse(code = 100, message = "email confirmed" ),
            @ApiResponse(code = 101, message = "email not confimred")

    })
    @BodyParser.Of(BodyParser.Json.class)
    public static Result handleSignup(@ApiParam( value = "token Id", required = true )
                                         @PathParam("tokenId") String tokenId) 
{
......
}

any idea how to solve that!

**Comment by fehguy** [comment]
Hi, I'm not sure, if you can reopen if you're still stuck and provide more detail we can help.
