### ISSUE TITLE
File to download is corrupted

### ISSUE THREAD

**Issue by a-a-k** [swagger-api/swagger-ui#5590]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: chrome
 - Version: last
 - Method of installation: swashbuckle
 - Swagger-UI version: IDK, seems 2.2.10
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
I do not familiar with all these schemes, I'm just using swashbuckle which is doing all the job under the hood.

I have an API method for getting pdf file to download, it works as expected in my web app through UI - I can download a file and that will be a correct file. But doing the same in Swagger UI going wrong. I steel able to download a file but it will be corrupted (_empty for pdf and non-readable for excel_). 

Have no idea what is wrong there. Could you help to figure out?

### Screenshots

![image](https://user-images.githubusercontent.com/5455861/64251940-d7b17300-cf43-11e9-8f66-de28c5e8c3cc.png)
![image](https://user-images.githubusercontent.com/5455861/64251979-ea2bac80-cf43-11e9-8893-1d44432dfcb6.png)

**Comment by webron** [comment]
Unfortunately, this is a very old version of Swagger UI which we no longer support. I understand you're getting it through Swashbuckle. I believe the latest Swashbuckle versions do use our current versions, but not quite certain. As an alternative, you can install Swagger UI separately as part of your application. Please upgrade the the current version and try again, and if the issue persists file a new ticket.

**Comment by a-a-k** [comment]
@webron thank you for your attention.

**Comment by mikip91** [comment]
@a-a-k  Were you able to fix this?

**Comment by a-a-k** [comment]
> @a-a-k Were you able to fix this?

Unfortunately no
