### ISSUE TITLE
What's the right way to add custom headers?

### ISSUE THREAD

**Issue by dblock** [swagger-api/swagger-ui#561]
It seems that `window.authorizations.add("key", new ApiKeyAuthorization("api_key", key, "header"));` is a strange way to add a "custom header". Maybe my header is not for authorization?

Is there a better way to do this? Should the DSL be extended?

It's also a bit weird that it's a property on `window`, maybe there should be a way to just do `window.swaggerUi.addHeader`?

**Comment by fehguy** [comment]
see also https://github.com/swagger-api/swagger-js/issues/178

**Comment by mohsen1** [comment]
If you want to have custom headers now you can use global parameter definitions and include your parameter in all operations/paths in version 2.0 of specs. UI should show header parameter fields to user.
