### ISSUE TITLE
Broken urlencoding in curl example

### ISSUE THREAD

**Issue by spaceone** [swagger-api/swagger-ui#5611]
The swagger-ui generated a broken URL which causes `curl` to reject the URL with the error message:
`$ curl -X GET "https://example.net/search?query[]=%2A" -H "accept: application/json"`
`curl: (3) [globbing] bad range specification in column XX`

→ `[]` must be urlencoded to `%5B%5D`.

The OpenAPI v3 schema contains a deepObject query string parameter:
```json
{
                        "in": "query",
                        "name": "query",
                        "style": "deepObject",
                        "schema": {"type": "object"},
                        "description": "The value to search for",
                        "example": {"": "*"},
}
```

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
