### ISSUE TITLE
Regex Quantifier Parsing for "Try it out!"

### ISSUE THREAD

**Issue by statueofmike** [swagger-api/swagger-ui#562]
When using a regex path variable that contains an explicit quantifier, an extra end-curly-bracket "}" is left at the end of the URL.

Example: 
`@Path( "/{uuid : (?i)[a-fA-F\\d]{32}}" )`

produces from the UI's "Try it out!" button:
`Request URL`
`http://domain/path/71000000000000000000000000000000}`

The additional "}" at the end is incorrect and causes the UI REST call to fail.

**Comment by fehguy** [comment]
yes this is fixed

**Comment by wsutter** [comment]
I've just run into this very issue with Swagger-UI 2.1.1...
Could anyone please confirm that this bug is fixed in 2.1.1?

Thanks
