### ISSUE TITLE
5.0 RC3 / .Net Core 3.0.100 not passing in authorization header

### ISSUE THREAD

**Issue by SledgeHammer01** [swagger-api/swagger-ui#5621]
.Net Core 3.0.100
Swagger 5.0 RC3

* Method in controller has [Authorize] header
* Using documented OAuth2SecurityFilter class
* Lock icon is shown on UI
* UI prompts for Oauth Header

Curl request generated is missing Oauth header. Note -H has no value (worked in 4.0):

curl -X GET "http://localhost:52580/sample/testMethod?APNSampleRequestValue=Sample%20APN%20Request%20Value&SampleComplexRequest.SampleTestBValue=123&SampleComplexRequest.SampleTestAValue=1" -H  "accept: application/json"

OAuth2SecurityFilter looks like this... Am I missing something? I don't want the UI to prompt for the client id & secret and call the token, I just want it to pass in the value in the text box as it did in 4.0 and earlier:

				operation.Parameters.Add(new OpenApiParameter()
				{
					Name = "Authorization",
					In = ParameterLocation.Header,
					Description = Properties.Resources.SecurityDescription,
					Required = true,
					Schema = new OpenApiSchema() { Type = "string" }
				});

				operation.Security.Add(new OpenApiSecurityRequirement()
				{
					{
						new OpenApiSecurityScheme()
						{
							Type = SecuritySchemeType.OAuth2,
							In = ParameterLocation.Header,
							Scheme = "Bearer",
							Flows = new OpenApiOAuthFlows()
							{
								ClientCredentials = new OpenApiOAuthFlow()
								{
									Scopes = new Dictionary<string, string>
									{
										{ "readAccess", "Access read operations" },
										{ "writeAccess", "Access write operations" }
									},
									TokenUrl = new Uri("/token", UriKind.Relative)
								}
							}
						},
						new List<string>()
					}
				});
			}

**Comment by KarlJorgen** [comment]
I have a similar issue after upgrading to .Net Core 3.0 and 5.0 RC3

**Comment by webron** [comment]
This seems like an issue you're having with your code or the library you use to generate your API definition. Unfortunately, that's not something we can help with. Swagger UI simply loads and renders the input it gets.

If you find the issue is indeed with how it's rendering the input, please file a new ticket, following the issue template, and providing the requested details.
