### ISSUE TITLE
Do not resolve $ref in examples..value

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#5625]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome latest
 - Method of installation: https://editor.swagger.io
 - Swagger-UI version: 3.23.11
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
```yaml
openapi: 3.0.0
info:
  title: Incorrect example reference syntax
  version: 1.0.0
paths:
  /foo:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
            
              incorrect:
                value:
                  - $ref: '#/components/examples/MyExample'
                summary: This is not a valid example reference

              correct:
                $ref: '#/components/examples/MyExample'
  
      responses:
        '200':
          description: OK

components:
  examples:
    MyExample:
      value:
        foo: bar
```

### Describe the bug you're encountering
Swagger UI resolves the `$ref` inside `examples.<name>.value`, which is incorrect. `$ref` should only be resolved if used directly under `examples.<name>`, but not inside `value`.

### Expected result
The `incorrect` example should be rendered as
```
[
  {
    "$ref": "#/components/examples/MyExample"
  }
]
```

### Actual result
The `incorrect` example is rendered as
```
[
  {
    "value": {
      "foo": "bar"
    },
    "$$ref": "#/components/examples/MyExample"
  }
]
```

**Comment by shockey** [comment]
I'm surprised this is happening again, but this looks like a bug indeed.
