### ISSUE TITLE
Debug/test parameter mode for POST and PUT endpoints

### ISSUE THREAD

**Issue by Justvuur** [swagger-api/swagger-ui#5645]
From the swagger UI side, when the user is "trying out" a POST or a PUT endpoint, I would like to tell the endpoint/backend that for this request, a user/someone is executing this POST/PUT from the swagger UI. Is there a way of sending a hidden undocumented optional parameter in the query string or in the request body that can be used to tell if its being executed from the swagger ui?

The reason why I'm asking is, we want users to test/try out requests from the swagger UI but we are afraid that when it comes to the PUT/POST that they might make a mistake that would affect production data (or when they are "testing" through the UI).

**Comment by shockey** [comment]
Yes! You can use a [`requestInterceptor`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#requestinterceptor) to attach anything you'd like to the request.

I'd recommend adding something to your query string — `req.url` in the interceptor and the [`URL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL) browser API should allow you to manipulate the query string pretty easily.
