### ISSUE TITLE
How to pass a header value on click of the 'Try it out' button on the Swagger UI page?

### ISSUE THREAD

**Issue by DeeptiKrishnan** [swagger-api/swagger-ui#5646]
I am creating a web API which takes in a API key header parameter. Can I pass the header value on click of the 'Try it out' button? For applications consuming this API they will need to pass the header, but for the Swagger UI testing page I want to be able to pass the API key from the swagger UI js fie. Any help?

**Comment by shockey** [comment]
If you'd like to programmatically set up authorization that you've defined in your API document, you can use [`swaggerUi.preauthorizeApiKey()`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#preauthorizeApiKey).

If you'd prefer for the authorization to be completely opaque to users, the [`requestInterceptor` option](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#requestinterceptor) will allow you to attach any header value you'd like.

**Comment by DeeptiKrishnan** [comment]
Thank you! requestInterceptor seems to be the option I want to proceed with. This is the code I have in my Index.cshtml <script> section

`.............window.swaggerUi = new SwaggerUi({
                url: url,
                **requestInterceptor: function(req) {
                    req.headers.custom_header = "True";
                return req;
                },**
                dom_id: "swagger-ui-container",
                supportedSubmitMethods: ['get', 'post'],
................`

On doing this I am getting the error - "Uncaught TypeError: Cannot read property 'headers' of undefined". How do I set the value of an API key header here?

**Comment by shockey** [comment]
@DeeptiKrishnan, what version of Swagger UI are you using?

**Comment by DeeptiKrishnan** [comment]
@shockey : I am using Swagger UI version 2.2.8

**Comment by shockey** [comment]
Unfortunately, we don't have the capacity or ability to look into changes around versions earlier than `3.0.0`. Support for v2 ended in 2017.

You can continue using those versions as-is, or update to the latest and get support on those versions.

**Comment by JonBishopFox** [comment]
@shockey I added the `preauthorizationApiKey` but I don't it in the request header

```
      const ui = SwaggerUI({
        dom_id: '#swagger-ui',
        layout: 'BaseLayout',
        url: '/assets/json/swagger.json',
        operationsSorter: 'alpha',
        onComplete: function () {
          ui.preauthorizeApiKey(
            'Authorization',
            'Bearer token'
          );
        },
      });
```

Any suggestion? I am using swagger-ui `^4.5.0`

**Comment by Meera9** [comment]
@JonBishopFox  this is work for me i hope it will work for you also 

window.onload = function() {
        // Build a system
        const ui = SwaggerUIBundle({
            dom_id: '#swagger-ui',
            url: "{!! $urlToDocs !!}",
            operationsSorter: {!! isset($operationsSorter) ? '"' . $operationsSorter . '"' : 'null' !!},
            configUrl: {!! isset($configUrl) ? '"' . $configUrl . '"' : 'null' !!},
            validatorUrl: {!! isset($validatorUrl) ? '"' . $validatorUrl . '"' : 'null' !!},
            oauth2RedirectUrl: "{{ route('l5-swagger.'.$documentation.'.oauth2_callback', [], $useAbsolutePath) }}",

            **requestInterceptor: function(request) {
                request.headers['X-CSRF-TOKEN'] = '{{ csrf_token() }}';
                request.headers['Content-Lang'] = 'en';
                request.headers['Content-Timezone'] = 'Asia/Calcutta';
                request.headers['Content-Timezone'] = 'Asia/Calcutta';
                request.headers['X-Requested-With'] = 'XMLHttpRequest';
                return request;
            },**

            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],

            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],

            layout: "StandaloneLayout",
            docExpansion : "{!! config('l5-swagger.defaults.ui.display.doc_expansion', 'none') !!}",
            deepLinking: true,
            filter: {!! config('l5-swagger.defaults.ui.display.filter') ? 'true' : 'false' !!},
            persistAuthorization: "{!! config('l5-swagger.defaults.ui.authorization.persist_authorization') ? 'true' : 'false' !!}",

        })

        window.ui = ui

        @if(in_array('oauth2', array_column(config('l5-swagger.defaults.securityDefinitions.securitySchemes'), 'type')))
        ui.initOAuth({
            usePkceWithAuthorizationCodeGrant: "{!! (bool)config('l5-swagger.defaults.ui.authorization.oauth2.use_pkce_with_authorization_code_grant') !!}"
        })
        @endif


    }
