### ISSUE TITLE
Validation of deep objects seems to be broken

### ISSUE THREAD

**Issue by betabandido** [swagger-api/swagger-ui#5648]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 77
 - Method of installation: copying dist folder and serving it statically
 - Swagger-UI version: both master and 3.23.11
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```json
{
  "openapi": "3.0.1",
  "info": {
    "contact": {
      "email": "none@none.com",
      "name": "None"
    },
    "title": "None",
    "version": "v1"
  },
  "servers": [{"url": "/api/v1"}],
  "paths": {
    "/test": {
      "get": {
        "summary": "test",
        "parameters": [
          {
            "description": "test",
            "in": "query",
            "name": "map",
            "style": "deepObject",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
          }
        }
      }
    }
  }
}
```

Swagger-UI configuration options:
I use the default options. I simply copied the contents of the `dist` folder into a folder in my application. Then I created `swagger.json` in that folder, and I modified `index.html` to point to that JSON file. Swagger is statically served by a Go application.

### Describe the bug you're encountering
If I enter a non-valid JSON into the text area for parameter `map` and I click execute, a spinning wheel appears and it just stays there forever. No request is received by the backend.

Older versions of swagger UI (e.g., 3.23.6 or 3.22.3) work correctly: the text area becomes red and a message stating that a valid JSON is required appears. So, the correct behavior must have been broken at some point after 3.23.6.

### To reproduce...

1. Statically serve the `swagger.json` shown above
2. Type some invalid JSON (e.g., foobar) in the only field
3. Click execute

### Expected behavior
Swagger UI should behave as it did in previous versions.

### Screenshots

Current behavior where spinning wheel appears and swagger UI freezes:

<img width="1418" alt="Screen Shot 2019-10-09 at 11 31 57 AM" src="https://user-images.githubusercontent.com/5481662/66469704-9c491d80-ea88-11e9-915a-938973e0318b.png">

Old behavior where invalid JSON is detected:

<img width="1420" alt="Screen Shot 2019-10-09 at 11 32 58 AM" src="https://user-images.githubusercontent.com/5481662/66469709-9fdca480-ea88-11e9-9a44-a67ff2c69dd6.png">

**Comment by shockey** [comment]
Looks like this was introduced in #5571: 

https://github.com/swagger-api/swagger-ui/commit/c9c3b2338ebec4e11f83217d402c5396aa565c4e#diff-47300e7ecd8989b6246221de88fc9a3cL524-R549

**Comment by shockey** [comment]
Fixed! Will be released today.
