### ISSUE TITLE
Add folding json

### ISSUE THREAD

**Issue by garagatyi** [swagger-api/swagger-ui#565]
Some API returns long JSON in response.
Making components of JSON collapsable will improve UX for such JSONs

**Comment by montogeek** [comment]
This would be extremely great!

**Comment by webron** [comment]
Please consider providing a contribution to the project for this functionality.

**Comment by webron** [comment]
Going to close this one out. It's been open for a very long time, and nobody picked it up. If anyone in the future submits a PR to introduce this functionality, we'd be happy to review it.

**Comment by dlevesque1980** [comment]
You can find json folding in swagger 3.x with this plugin 
https://github.com/dlevesque1980/swagger-ui-json-folding-plugin
