### ISSUE TITLE
swagger-ui.html    error

### ISSUE THREAD

**Issue by sunxingyuqaq** [swagger-api/swagger-ui#5654]
![image](https://user-images.githubusercontent.com/26001714/66553701-2e7f1d80-eb7e-11e9-9c4c-4f32ca700af0.png)
swagger-ui.html    send   /csrf request   error401 or 404

**Comment by jserra91** [comment]
same #5649 5649

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
