### ISSUE TITLE
Sort input column name for self define

### ISSUE THREAD

**Issue by CzyerChen** [swagger-api/swagger-ui#5661]
### Content & configuration
Whether user can define the input column sorting order by themselves?
For Example:
Now, Required columns show first, and then common columns ordered by characters order, like password first, and then username, because P is before U.
But It is not friendly shown for users at swagger-ui.html.
Maybe we like to see username than password.

### Describe the solution you'd like
```text
@Target({ElementType.PARAMETER, ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface ApiParam {
    String name() default "";

    String value() default "";

    String defaultValue() default "";

    String allowableValues() default "";

    boolean required() default false;

    String access() default "";

    boolean allowMultiple() default false;

    boolean hidden() default false;

    String example() default "";

    Example examples() default @Example({@ExampleProperty(
    mediaType = "",
    value = ""
)});

    String type() default "";

    String format() default "";

    boolean allowEmptyValue() default false;

    boolean readOnly() default false;

    String collectionFormat() default "";
}
```
@ApiParam can give chances to set up the order ,like adding "order",so that we can easily rank the input param at swagger-ui.html

**Comment by shockey** [comment]
Hi @CzyerChen!

Swagger UI sorts operation parameters based on the order they appear in your JSON/YAML document.

For example:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/680248/66959934-4c3a0000-f020-11e9-8a5f-7a2baefa5265.png">

---

It's likely that your annotation library is sorting parameters somehow, which is causing what you're seeing, but Swagger UI itself isn't doing this.

I'm going to close this for now, let me know if you have any further concerns. Hope this helps!
