### ISSUE TITLE
Set-Cookie is missing in the Response header

### ISSUE THREAD

**Issue by Senthuran100** [swagger-api/swagger-ui#5670]
**Description** : We have a backend that passes Set-Cookie in the response header. When we see the response header the Set-Cookie header is not passed in the swagger console in the Response Headers section. Is this the limitation of swagger. It is printing only the "content-type": "application/json".  We have tested this scenario using Open API 2.0 and 3.0. Please refer the below image.

![image](https://user-images.githubusercontent.com/32807418/67382538-43f73d00-f5ab-11e9-8afe-d87539985ac6.png)

**Comment by shockey** [comment]
@Senthuran100 FYI: it looks like you're using Swagger UI v2.x, which is very old and no longer supported.
