### ISSUE TITLE
Please, could someone help me with this error?

### ISSUE THREAD

**Issue by BrunyC** [swagger-api/swagger-ui#5671]
I have a swagger-ui in my localhost and works well. When i try up out my application to a web server(nginx) they dont found my swagger html. This is my link of stackoverflow https://stackoverflow.com/questions/58376925/how-can-i-configure-nginx-to-find-my-swagger-ui.

**Comment by webron** [comment]
Thanks for opening the issue, but unfortunately this is not one we can help with. We can't support the different deployment options out there as there are too many of them. It'd be better if you ask at the deployment tool's forums why it misbehaves.
