### ISSUE TITLE
Offer a way to pre-set certain set of values to the input masks

### ISSUE THREAD

**Issue by dothebart** [swagger-api/swagger-ui#5675]
When documenting an API one may want to demonstrate certain sets of parameters to ease the users grasping of what are sensible values to achieve a certain thing with the API.

Right now the input masks will only offer a valid value that is accepted in order to the  value definition as default ala: 
```
"path": "string",
``` 
so while `string` may be an acceptable value for this API according to the API definition, its educational value isn't as high in telling the user which values bring the API to life in a sensible way.

If one would now be able to pre-set a set of parameters into the formulars one could i.e. have 
- one set named `temporary file` setting `path` to `/tmp/some-temporary-file.txt`
- another set named `User document` setting `path`to `~/Documents/some-document.txt` 

and thus teaching the user in a better way how to use the API above its fundamental definition. 

Such sets of values could be read from another json structure similar to the swager route matching part: 
```
'/this/route/foo'.post = [
{
  description: 'temporary file'
  body: { path: '/tmp/some-temporary-file.txt' }
  PathParameters: { ...}
  HeaderParameters: {...}
},
{
  description: 'User document'
  body: { path: '~/Documents/some-document.txt' }
  PathParameters: { ...}
  HeaderParameters: {...}
}
```

**Comment by shockey** [comment]
@dothebart, OpenAPI's Parameter Objects [have `example` and `examples` fields](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameter-object) that allow you to provide an initial input value to Swagger UI.

Further, if you're interested in having multiple OpenAPI files that mirror each other's structure and provide additional data about a definition, check out the several OpenAPI Overlays proposals (https://github.com/OAI/OpenAPI-Specification/issues/1843).

This sounds like what you're looking for, so I'm going to close this out. Feel free to reply if there's something I've missed!

**Comment by Simran-B** [comment]
The issue with `examples` is that it is bound to a single parameter, and there is apparently no way to define examples for a combination of parameters (or by extension requests).

You can have individual examples like this:

![image](https://user-images.githubusercontent.com/7819991/85867039-9fc43680-b7c8-11ea-8c32-a9ce0b6d11aa.png)

But not examples like `{ "attr1": "foo", "attr2": "bar"}` to show that a particular set of parameter values does something meaningful.

![image](https://user-images.githubusercontent.com/7819991/85868042-0d249700-b7ca-11ea-98a9-8c848b93043b.png)

This seems to be a spec issue in the first place however and is probably better discussed in e.g. this issue:
https://github.com/OAI/OpenAPI-Specification/issues/2197
