### ISSUE TITLE
swagger generation fails in .net core 3.0 for object parameters

### ISSUE THREAD

**Issue by miker55** [swagger-api/swagger-ui#5680]
If I have a class with a field that is an object type, and I use that class as a parameter to an api method, the swagger UI blows up with a 500 internal error.

I cloned the https://github.com/aspnet/AspNetCore.Docs.git repo and then changed the controller in the AspNetCore.Docs\aspnetcore\tutorials\web-api-help-pages-using-swagger\samples\3.0\TodoApi.Swashbuckle project like so:

```
namespace TodoApi.Controllers
{
    public class MyClass
    {
        public StringBuilder sb;
    }

    [Route("api/[controller]")]
    [ApiController]
    public class TodoController : ControllerBase
    {
        [HttpGet]
        public ActionResult<IActionResult> GetAll(MyClass mc)
        {
            return Ok();
        }

   }
}
```

After doing that if I hit `http://localhost:58103/swagger/index.html`, I get:

```Fetch errorInternal Server Error /swagger/v1/swagger.json```

If I change the type of the field in `MyClass` from `StringBuilder` to `int`, it works fine.

**Comment by shockey** [comment]
@miker55, I'm closing this issue since (a) this appears to be unrelated to Swagger UI, and (b) you haven't followed the issue template we provide.

Feel free to open a new issue if you identify an issue with Swagger UI that we can help with 🙂
