### ISSUE TITLE
Map of arrays in a GET request

### ISSUE THREAD

**Issue by betabandido** [swagger-api/swagger-ui#5698]
### Q&A (please complete the following information)
 - Method of installation: dist assets
 - Swagger-UI version: master
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "test",
    "version": "v1"
  },
  "paths": {
    "/endpoint": {
      "get": {
        "summary": "test",
        "parameters": [
          {
            "description": "test",
            "in": "query",
            "name": "param",
            "style": "deepObject",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "example": {
              "key": [
                "value1",
                "value2"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  }
}
```

### Describe the bug you're encountering
According to the [OpenAPI 3.0 specification](https://swagger.io/docs/specification/data-models/dictionaries) a map where the keys are strings and the values are string arrays should be a valid parameter type:

> A dictionary (also known as a map, hashmap or associative array) is a set of key/value pairs. OpenAPI lets you define dictionaries where the keys are strings. To define a dictionary, use type: object and use the additionalProperties keyword to specify the type of values in key/value pairs. 

> The additionalProperties keyword specifies the type of values in the dictionary. Values can be primitives (strings, numbers or boolean values), arrays or objects.

The `swagger.json` shown above includes an example where a map value is an array of two elements. I would expect this to be a valid configuration. But, swagger UI doesn't seem to accept it. When sending a request to the endpoint using swagger (with the example shown above) the curl command is: `curl -X GET "http://localhost:8000/endpoint" -H "accept: */*"`. Notice that the query string is missing.

### Expected behavior
The map containing arrays as values gets encoded as a query string.

### Additional context or thoughts
Are map where the values are arrays only supported in a request body (e.g., using POST method)? Or should this also work in a query string as part of a GET request?

**Comment by hkosova** [comment]
Currently OpenAPI Specification does not support this scenario. The issue is that the `deepObject` behavior is only defined for simple objects with primitive properties (such as a string-to-string dictionary) but [not for arrays](https://github.com/OAI/OpenAPI-Specification/issues/1006#issuecomment-289196647) or [nested objects](https://github.com/OAI/OpenAPI-Specification/issues/1706) (such as a string-to-array dictionary).

This feature requires a change to the OpenAPI Specification (https://github.com/OAI/OpenAPI-Specification/issues/1706) before it could be implemented in Swagger UI.
