### ISSUE TITLE
'Try it out' button disappeared for 'Delete'

### ISSUE THREAD

**Issue by JeroenMinnaert** [swagger-api/swagger-ui#57]
For a DELETE operation, the 'Try it out' button fails to show. Path fields don't show up either for a DELETE.

**Comment by ptarpan** [comment]
I am still having this issue, GET/POST/PUT show up fine after modifying the swagger config file but DELETE does not. The sample api-docs.html file already has supportedSubmitMethods, 'delete' in it. Does anyone know where and how DELETE needs to be specified?

**Comment by webron** [comment]
@ptarpan - commenting on an issue that was closed in 2012 (!) is probably not the best approach for help. It also sounds like you're using an old version of the UI. Try upgrading and see what's next.

**Comment by ptarpan** [comment]
@webron - you are right. Let me troubleshoot and perhaps upgrade.
