### ISSUE TITLE
highlighted required after value is entered

### ISSUE THREAD

**Issue by oleksiivasylenko** [swagger-api/swagger-ui#5703]
I found think similar issue(issues/5622) in closed tread, but I do not see solutions and activities in that thread.

Problem 1
 When data is entered in required field it is still highlighted as required. I found that problem occurs when the name of parameter in attribute "[HttpGet("{id}")]" is the same as the name of parameter in method "Get1(Guid id)". 
---- Look at - WeatherForecastController.cs -> 29-30 lines

Problem 2(found while testing problem 1)
 When the name in attribute is different from the name in method parameter
EG: [HttpGet("byname/{name}")], Get2(Guid id)
Filed "Id" in swagger UI becomes required when you enter any data in it
---- Look at - WeatherForecastController.cs -> 46-47 lines

ASP NET core 3.0
Swashbuckle.AspNetCore - 5.0.0-rc3

Here is link to git repository with this error
https://github.com/oleksiivasylenko/swaggerUI-required-error.git
Here is the link to video which shows problems 
https://youtu.be/LlEi3ycAiY0

**Comment by webron** [comment]
Please provide both the API definition that's loaded into Swagger UI and the Swagger UI version. We don't have the capacity to run examples in different languages, and we have no idea what version of Swagger UI is included with libraries that provide it as part of themselves.

**Comment by oleksiivasylenko** [comment]
@webron, Sorry, I thought it related only to .net. 

![Swagger versions](https://user-images.githubusercontent.com/28143505/68367715-fe0bae80-013e-11ea-8766-3aa0c1f03d61.jpg)

Here is swagger generated json.
[swagger.txt](https://github.com/swagger-api/swagger-ui/files/3818294/swagger.txt)

**Comment by webron** [comment]
Thanks for providing the details, definitely helps.

The issue in this case is that the `id` parameter in both cases (whether path or query) is defined a `string` with a format `uuid`. In some cases, Swagger UI is able to validate the input based on the format, and it does for this case. If you hover the red input box, it will tell you what's wrong.

If you use a value like `123e4567-e89b-12d3-a456-426655440000`, it would work.

**Comment by oleksiivasylenko** [comment]
@webron Thank you for clarifying.

Never met this behavior before that's why didn't get where the problem is.
