### ISSUE TITLE
Set default clientId/clientSecret in swagger-ui-react

### ISSUE THREAD

**Issue by gavmck** [swagger-api/swagger-ui#5704]
I've previously set the default clientId and secret using the swagger-ui package via the initOAuth instance method.

```
ui.initOAuth({
  clientId: "myAwesomeId",
  clientSecret: "superSecret123",
});
```

I've had to move to swagger-ui-react for compatibility with React 16. 
How do I set the defaults there? I don't see a way of accessing the instance.

Thanks!

**Comment by gavmck** [comment]
Anybody out there?

**Comment by gavmck** [comment]
OK figured it out.

You can use the onComplete prop which gives you back the instance so you can access the methods.

```
<SwaggerUI
          url="/spec.json"
          onComplete={(system) => {
            system.initOAuth({
              clientId: 'MyAwesomeId',
              clientSecret: 'MySuperSecret',
            });
          }}
/>
```

**Comment by ZeroCoderC00l** [comment]
@gavmck you sir, are a life saver!, Just know that. I had the same issue, thanks for helping out!
Did you have the chance to hide the clientId and clientSecret from the view?

**Comment by gavmck** [comment]
> @gavmck you sir, are a life saver!, Just know that. I had the same issue, thanks for helping out!
> Did you have the chance to hide the clientId and clientSecret from the view?

I'm afraid not, we went live with it showing.
