### ISSUE TITLE
Change the name from Swagger

### ISSUE THREAD

**Issue by vfaller** [swagger-api/swagger-ui#5706]
Change the name from Swagger to something else, maybe AutoDoc or something less annoying

**Comment by webron** [comment]
Thank you for taking the time to make this suggestion, however, at this point we're not going to consider changing the name.

**Comment by vfaller** [comment]
ah too bad because swagger is a terrible name

**Comment by fmvilas** [comment]
![](https://media.giphy.com/media/fH9LpzpCbRNNvi3z2R/giphy.gif)
