### ISSUE TITLE
Question : Scroll to pre-selected path

### ISSUE THREAD

**Issue by naveenkumaran** [swagger-api/swagger-ui#5709]
Background : We use a autocomplete in the parent page which will list all the end points of Swagger files uploaded to the application. 

From a autocomplete if I select a path(for Example : /pet/{petId}) and pass the variable to Swagger UI, is there a possibility to auto scroll the page to the offset where the selected path(/pet/{petId}) is present in the Swagger file?

**Comment by webron** [comment]
Do you mean something like http://petstore.swagger.io/#/user/createUser?

**Comment by naveenkumaran** [comment]
Yes Exactly, but keeping the INFO and Scheme container position fixed. Can I just tweak the CSS?

**Comment by naveenkumaran** [comment]
Resolved using CSS and Deep Linking.
