### ISSUE TITLE
can't parse JSON.  Raw result: in Swagger UI v3.13.6 [Extension of 4098]

### ISSUE THREAD

**Issue by yatheeshgd** [swagger-api/swagger-ui#5714]
### Meta Info
 - OS: Ubuntu 18.04
 - Browser: Mozilla Firefox
 - Version: 70.0.1-1
 - Method of installation: exe
 - Swagger-UI version: 3.13.6
 - Swagger/OpenAPI version: OpenAPI 3.0.1

Example Swagger/OpenAPI definition:
```json
{
  "openapi": "3.0.1",
  "info": {
    "contact": {},
    "license": {
      "name": "Apache 2.0 License",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
```

Swagger-UI configuration options:
```js
SwaggerUI({
			<groupId>org.webjars</groupId>
			<artifactId>swagger-ui</artifactId>
			<version>3.13.6</version>
})
```

### Describe the bug you're encountering
Getting "can't parse JSON. Raw result" line in the API response as the first line followed by the actual API response

### To reproduce...

1. Launch swagger UI
2. Perform an API invocation
3. Scroll down to API response
4. Notice that the first line of the response is having the line "can't parse JSON. Raw result"

### Expected behavior
can't parse JSON. Raw result -> should not have displayed in the API response in Swagger UI

### Screenshots
![image](https://user-images.githubusercontent.com/10626626/68872972-dd39ef00-0724-11ea-8300-e9ae09db68ac.png)

### Additional context or thoughts
This is similar or same as the defect reported here https://github.com/swagger-api/swagger-ui/issues/4098 and is locked due to inactivity, however when tested with above mentioned versions, we still see the issue reproducible

**Comment by webron** [comment]
That does not seem like a bug. The response is not JSON even though JSON is expected.

**Comment by yatheeshgd** [comment]
Closing this defect as it is not a defect, the response should be parsed to JSON string instead of nor normal string to overcome this issue
