### ISSUE TITLE
red asterisk is not displayed when required is true

### ISSUE THREAD

**Issue by fy-kenny** [swagger-api/swagger-ui#5723]
version: 2.9.2
```java
    @ApiModelProperty(value = "视频切片ID", required = true)
    private Integer vSplitId;
```
red asterisk is not displayed when `required = true` and the first word of the variable is only one char.
if I modify the variable to `vidSplitId`, the red asterisk will be displayed rightly.

thx
kenny

**Comment by webron** [comment]
Hi @fy-kenny - based on what you shared I'm guessing you're using SpringFox. Swagger UI simply renders what SpringFox give is. Based on what you're describing, it sounds like the issue is with SpringFox, so you need to file an issue with that project.
