### ISSUE TITLE
Swagger is not working due to *deprecated* issue

### ISSUE THREAD

**Issue by ajaythakor** [swagger-api/swagger-ui#5727]
I am not able to debug API with swagger due to below issue:

![image](https://user-images.githubusercontent.com/8626928/69525656-9b177580-0f8e-11ea-9932-7a0046df7f15.png)

 OS: Windows 10
 - Browser: Chrome
 - Version: v4.0.30319
 - Method of installation: Servicestack.API.Swagger
 - Swagger-UI version: 5.1.0
 - Swagger/OpenAPI version: 

We are using Swagger with Servicestack.API.Swagger.
I am not sure if this is right place to raise the issue or not, if someone is aware of this issue please help me on this.

**Comment by webron** [comment]
That's a screenshot from a very very old version of Swagger UI which we no longer support. Either use the latest version of the project directly, or reach out to the Servicestack maintainers and ask them to update the version.
