### ISSUE TITLE
Hyperlink to specific documentation?

### ISSUE THREAD

**Issue by l8nite** [swagger-api/swagger-ui#573]
Is there a way to link to a shared installation of swagger from a couple of different applications and have the API page for each app load automatically (or at least pre-fill the input box) ?

I.e., I want to have something like
```html
<a href="http://myswagger/?url=http://localhost/myapp/swagger_docs">View Documentation</a>
```

**Comment by fehguy** [comment]
This will be in the `external docs` field in swagger-spec 2.0

**Comment by mohsen1** [comment]
#1000 will fix this.

**Comment by mohsen1** [comment]
Duplicate of https://github.com/swagger-api/swagger-ui/issues/608
