### ISSUE TITLE
How to config replace \n character to tag <br/> in note

### ISSUE THREAD

**Issue by luuvthanh87** [swagger-api/swagger-ui#574]
Hi all,

My api note has many lines seprate by character '\n', can I config swagger auto replace it to tag <br/>?

**Comment by mohsen1** [comment]
Hi @luuvthanh87 

If you upgrade to Swagger 2.0 you will get Markdown support in descriptions. You can have line breaks in Markdown. 

If you are already using Swagger 2.0 then Markdown support has been added recently. Please let me know either way.
