### ISSUE TITLE
Bad generated curl for PUT request multipart/form-data

### ISSUE THREAD

**Issue by artemmysikigorevich** [swagger-api/swagger-ui#5740]
Please, change condition in file
https://github.com/swagger-api/swagger-ui/blob/master/src/core/curlify.js
line 22,
replace
    if(type === "multipart/form-data" && request.get("method") === "POST") {
with
    if(type === "multipart/form-data" &&( request.get("method") === "POST"||request.get("method") === "PUT")) {

**Comment by webron** [comment]
@artemmysikigorevich PRs are welcome.

**Comment by jmullo** [comment]
PATCH too.

**Comment by CoalaJoe** [comment]
There seems to be more off then just the curlifying process. The actual requests is not being sent as a file as well.

**Comment by CoalaJoe** [comment]
Nevermind. It seems to be okay, but PHP has a quirk when uploading files with PUT https://www.php.net/manual/en/features.file-upload.put-method.php

So maybe we can just update the curlify method to generate the correct curl request. I am not sure how the actual request from open api looks like.
