### ISSUE TITLE
Swagger is not working in nest implementation

### ISSUE THREAD

**Issue by Igaiya** [swagger-api/swagger-ui#5747]
This is the swagger code we are using:

 const app = await NestFactory.create(AppModule);
  const options = new DocumentBuilder()
    .setTitle('WorryFree API')
    .setDescription('WorryFree API')
    .setVersion('1.0')
    .setSchemes('http', 'https')
    .addBearerAuth('Authorization', 'header', 'apiKey')
    .build();

  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('api', app, document);

_**We are trying to run swagger in our code using nest . But while running the command, It throws the below error. Could anyone please help fix this issue.**_ 

(node:2115) UnhandledPromiseRejectionWarning: TypeError: swaggerUi.generateHTML is not a function
    at Function.setupExpress (/home/ubuntu-07/Documents/mynest/nest-basics/demo/node_modules/@nestjs/swagger/dist/swagger-module.js:23:39)
    at Function.setup (/home/ubuntu-07/Documents/mynest/nest-basics/demo/node_modules/@nestjs/swagger/dist/swagger-module.js:17:21)
    at /home/ubuntu-07/Documents/mynest/nest-basics/demo/src/main.ts:20:17
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu-07/Documents/mynest/nest-basics/demo/src/main.ts:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:2115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2115) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by webron** [comment]
Please file the ticket again following the issue template and provide the required details for us to be able to assist.
