### ISSUE TITLE
Swagger UI with many basePath

### ISSUE THREAD

**Issue by StephanKrauss** [swagger-api/swagger-ui#5749]
Hello,

in the moment i test a swagger api.
There are 2 locations for my test.
A docker host on a remote computer and my
local test enviroment.

The main test is on the remote pc.
When i have a problem in the test,
i will switch in the api to my local pc.
This is important for debugging ... .

Is there a way to build in the api a enum menue to switch the basePath to my local pc ?

Your sincerly 

Stephan

**Comment by hkosova** [comment]
OpenAPI 3.0 supports multiple `servers` - check out the examples here:
https://swagger.io/docs/specification/api-host-and-base-path/
