### ISSUE TITLE
Relative paths problematic on https hosts

### ISSUE THREAD

**Issue by dtrupcevic** [swagger-api/swagger-ui#575]
Hi guys.

Been using swagger-ui for a while, but a new use-case came up where I can't use absolute paths - deploying an API a non-static ip/hostname virtual machine behind HTTPS.

The problem is the following:
basePath set to "/".
the api path in the apis array is properly set to "path/to/api/keys"

api-docs request is fine and gets loaded properly, but something goes wrong while creating the paths from the apis array.

so instead of 
https://host/path/to/api/keys the request goes off to http://host/path/to/api/keys. I don't want to enable CORS, nor can I change the requirements.

I'm aware that the preffered way to do this is to give the absolute path as the basePath, but sadly that's just not an option, since people can turn off/on their VM's and get a different hostname (IP). It would be really awesome if the swagger-ui worked out-of-the box, since it seems that the only problem is that the schema check is ignored and/or missing somewhere while creating the absolute path to the apis.

**Comment by fehguy** [comment]
please reopen if still an issue.

**Comment by Armanda888** [comment]
Hi, I have similar issue, I set the basePath to be "http://localhost:8085" for BeanConfig, and it works in my local, I can see the Swagger UI, and send request calls, but when I deploy it to vm, I can see Swagger UI, but when I send request, it went to localhost:8085/****. how am I supposed to solve it?
