### ISSUE TITLE
Download Excel file from a link as a response from Open Api 3

### ISSUE THREAD

**Issue by raghav-a-gupta** [swagger-api/swagger-ui#5750]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78
 - Method of installation: Working on editor.swagger.io
 - Swagger-UI version: Using website editor.swagger.io
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Excel Download Link test
  version: 0.0.0

servers:
  - url: "http://localhost:48094"
    description: "Python server"

paths:
                
  /xls/export:
    post:
      summary: "JSON to Excel conversion"
      description: "Used for converting the Ontology JSON to Excel in a specified format. It is using python for achieving this"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              
      responses:
        200:
          description: "JSON to Excel conversion succeeded"
          content:
            application/vnd.ms-excel:
              schema:
                type: string
                format: binary
            application/octet-stream:
              schema:
                type: string
                format: binary
                      
        400:
          description: "JSON to Excel conversion failed"
```

Swagger-UI configuration options:
Using editor.swagger.io

Have started the python server locally on port 48094 which has api endpoint exposed.

### Screenshots

![image](https://user-images.githubusercontent.com/31531617/70771425-1357a680-1d97-11ea-9c76-3b6e6c4b8787.png)

### How can we help?

In postman when I try this endpoint and do send and download, I am able to get a excel file saved locally. Through curl command also I am able to download the excel file. But in Swagger UI through editor.swagger.io I am facing this issue of **could not render the component**. See the screenshot above. What can be done?

**Comment by raghav-a-gupta** [comment]
Ok figured out. This is resolved when we expose **content disposition** header in the server code.

**Comment by 10nitinkumar** [comment]
> Ok figured out. This is resolved when we expose **content disposition** header in the server code.

@raghav-a-gupta Sorry didn't get it. How did you solve it. I am also facing the same issue.
