### ISSUE TITLE
send xdebug params

### ISSUE THREAD

**Issue by StephanKrauss** [swagger-api/swagger-ui#5752]
Hello,

is there a way to send params for a debugger.
I work with xdebug / php in a local enviroment.

For example:
I will use OpenAPI for debugging or profiling.

When I start debugging I want to add a parameters to the URL,

http://localhost/myRoute/myAction?XDEBUG_SESSION=PHPSTORM

Is there such a way?

Yours sincerely

Stephan

**Comment by hkosova** [comment]
Have you considered using Xdebug browser extensions? See the "Using a browser extension" section here: https://xdebug.org/docs/remote

**Comment by StephanKrauss** [comment]
Thanks !
