### ISSUE TITLE
CURL not updating properly in POST

### ISSUE THREAD

**Issue by ashera96** [swagger-api/swagger-ui#5755]
### Q&A (please complete the following information)
 - OS: ubuntu
 - Browser: chromium
 - Version: 79.0.3945.79
 - Method of installation: npm
 - Swagger-UI version: 3.24.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

Under the swagger console, when using POST, the Payload and string is fixed and does not update with the proper values within the curl.

### To reproduce...

1. Go to the swagger console
2. Add a payload and string to the request body of a POST request
3. Click on execute
4. Then the generated curl contains payload and string, and not the actual values which were entered for those placeholders

### Expected behavior

When using POST, the Payload and string found within the curl should be updated properly with the user entered values.

### Screenshots

![WSO2 APIM Developer Portal](https://user-images.githubusercontent.com/30475839/71084717-e999e780-21bb-11ea-8d23-7a45174a4c2b.png)

![image](https://user-images.githubusercontent.com/30475839/71058422-d1a77100-2185-11ea-89a2-5277e914be68.png)

**Comment by webron** [comment]
Please provide a full API definition we can use to test the issue.

**Comment by ashera96** [comment]
{"openapi":"3.0.1","info":{"title":"Country","version":"1.0.0"},"servers":[{"url":"https://localhost:8243/country/1.0.0"},{"url":"http://localhost:8280/country/1.0.0"}],"security":[{"default":[]}],"paths":{"/":{"post":{"requestBody":{"description":"Query or mutation to be passed to graphQL API","content":{"application/json":{"schema":{"type":"object","properties":{"Payload":{"type":"string"}}}}},"required":true},"responses":{"200":{"description":"OK"}},"security":[{"default":[]}],"x-auth-type":"Application & Application User","x-throttling-tier":"Unlimited"}}},"components":{"securitySchemes":{"default":{"type":"oauth2","flows":{"implicit":{"authorizationUrl":"","scopes":{}}}}}}}

**Comment by webron** [comment]
Unfortunately, I'm unable to reproduce the problem using the definition and versions you provided. Can you make sure you're using the specified version? You can check by opening your browser's console and running `versions` in it.

**Comment by ashera96** [comment]
I'm also unable to reproduce the issue. It works alright when I checked again. Sorry for the inconvenience caused.
