### ISSUE TITLE
Swagger doesn't work after custom annotation replacing @requestbody

### ISSUE THREAD

**Issue by qq443672581** [swagger-api/swagger-ui#5765]
Hello there
I need to do an encryption before the spring controller receives the parameters
So, I have defined my own annotations to replace @requestBody, but after using my own annotations, swagger does not work. Can I implement a request interface operation for an interface? What do I need to do? 
Thank you

example：
postman post：+c8Xl8mj/Rk9p0VYWLwJSw==（AES/ECB/PKCS5Padding）
my implementation do transfer：+c8Xl8mj/Rk9p0VYWLwJSw== -> {"test":"123"}
controller get:  {"test":"123"}

**Comment by webron** [comment]
This is a Spring question, not a Swagger UI one.
