### ISSUE TITLE
Swagger-UI is generating same request and response example for all the api's if the name of class is same.

### ISSUE THREAD

**Issue by munawwerali** [swagger-api/swagger-ui#5768]
I am using below dependencies

      compile "io.springfox:springfox-swagger2:2.9.2"
      compile "io.springfox:springfox-swagger-ui:2.9.2"

with spring boot, I have built a few rest APIs in which all are accepting the Request as RequestBody and returning Response as ResponseBody, here names are the same but the type of Request and Response are different. but in the swagger UI, it's creating the example values for all the requests and responses is same.

If I change the Request to Request1 then it's creating the sample values properly, is there anything which I can configure to fix this or do I need to rename all my classes, or shouldn't swagger create the request and response value by picking the class by its type, not by the name.

### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: gradle
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

**Comment by webron** [comment]
We don't really know which version is provided with Spriingfox as it's not our project. Swagger UI simply renders what it gets, so it's more likely an issue with Springfox. If you find that what Springfox generates is fine, please file a new ticket providing us with the required details in the issue template.
