### ISSUE TITLE
Question: Ordering of models

### ISSUE THREAD

**Issue by alferpal** [swagger-api/swagger-ui#5771]
Hello. 

I can't find in the documentation if there's a way to do this. so, is there a way to order models the same way you can order tags or operations?

Thank you.

**Comment by webron** [comment]
Currently, there isn't a direct configuration for it.

**Comment by alferpal** [comment]
Would this be welcome in a PR?

**Comment by alferpal** [comment]
@webron Sorry for bothering. Would a PR be welcomed for adding this feature / exposing the configuration?

**Comment by alferpal** [comment]
@webron @shockey Is this something that might be of interest to the project or no?
