### ISSUE TITLE
Swagger 2 - ui ignoring "description" fields?

### ISSUE THREAD

**Issue by kasztelan** [swagger-api/swagger-ui#578]
Just trying to use swagger for the first time and I decided to start with second version. I cloned develop_2.0 branch as suggested here: https://github.com/wordnik/swagger-ui/issues/568

I commented the line in index.html that load swagger.js and left the swagger-client.js one. It seems to work with 2.0 spec now but it doesn't seem to display description fields neither from Operation Object nor from model's properties. I'm using the example from http://wordnik.github.io/swagger-editor/ and though there are many descriptions there they aren't displayed by the swagger-ui

**Comment by AvihayTsayeg** [comment]
This is happening  using online swagger editor and master branch

**Comment by webron** [comment]
@AvihayTsayeg - the [swagger-editor](https://github.com/wordnik/swagger-editor) is an independent project. If you experience issues with it, please open a ticket on it directly.

**Comment by AvihayTsayeg** [comment]
Thx for the answer,
The editor is just fine and it is showing the description, 
The description is not displayed using swagger-ui (master build)

tags:
  - name: Reports
    description: "My Description"
paths: ....

**Comment by mohsen1** [comment]
The editor shows tag description in `title` attribute of the tag elements.

**Comment by AvihayTsayeg** [comment]
Thx @mohsen1,
Does swaggerUi display this tag description somewhere ? 

again thx for your answers !

**Comment by mohsen1** [comment]
It's not an issue as of 3249125
![screen shot 2015-02-25 at 4 27 23 pm](https://cloud.githubusercontent.com/assets/543633/6383984/671ce33a-bd0b-11e4-8471-7f62e6c3d319.png)
