### ISSUE TITLE
Array elements in Schema have duplicate descriptions

### ISSUE THREAD

**Issue by Andrew3431** [swagger-api/swagger-ui#5780]
- OS: macOS
 - Browser: chrome
 - Version:  79
 - Method of installation: springdoc-openapi-ui
 - Swagger-UI version:  3.18.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

When schema has an array element present, the description is duplicated and is shown twice in the UI.
```json
      "Filter": {
        "required": [
          "itemIds",
          "itemNames"
        ],
        "type": "object",
        "properties": {
          "itemIds": {
            "uniqueItems": true,
            "type": "array",
            "description": "A list of items",
            "items": {
              "type": "string",
              "description": "A list of items"
            }
          },
          "itemNames": {
            "uniqueItems": true,
            "type": "array",
            "description": "A list of item names",
            "items": {
              "type": "string",
              "description": "A list of item names"
            }
          }
        },
        "description": "The list of filters to use"
      }
```
**FilterModel.java**
```java
    public class Filter {

        @Schema(description = "A list of items", required = true)
        Set<String> itemIds = new HashSet<>();

        @Schema(description = "A list of item names", required = true)
        Set<String> itemNames = new HashSet<>();
    }
```

![image](https://user-images.githubusercontent.com/58496081/71946359-6b0ee500-317e-11ea-8557-fc43e2a2af5b.png)

How to avoid giving a description for the variable as well as giving a description for array item ?
I just want one description to be present.

**Comment by webron** [comment]
That's an issue with how springdoc reads the annotations and generate the definitions. Please file a ticket with that project.
