### ISSUE TITLE
Swagger UI will not transfer array[file] params to formdata

### ISSUE THREAD

**Issue by tsball** [swagger-api/swagger-ui#5781]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: swagger-ui-dist@3.12.1/swagger-ui-bundle.js,swagger-ui-dist@3.12.1/swagger-ui-standalone-preset.js
 - Method of installation: dist assets
 - Swagger-UI version: 3.12.1
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
My HTML
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="UTF-8">
  <title>API Document</title>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3.12.1/swagger-ui.css">

  <style>
    html, body {
      padding: 0px;
      margin: 0px;
    }
  </style>
</head>
<body>

<div id="swagger-ui"></div>

<script src="https://unpkg.com/swagger-ui-dist@3.12.1/swagger-ui-standalone-preset.js"></script>
<script src="https://unpkg.com/swagger-ui-dist@3.12.1/swagger-ui-bundle.js"></script>

<script>
    window.onload = function() {
      // 生成 api 路径
      const url = new URL(window.location.href)
      const searchParams = url.search.split('=')
      const apiDocUri = searchParams.length > 1 ? searchParams[1] : '/api/v3/swagger_doc'
      let swaggerJsonUrl = `${url.origin}${apiDocUri}`

      // Build a system
      const ui = SwaggerUIBundle({
        url: swaggerJsonUrl,
        dom_id: '#swagger-ui',
        deepLinking: true,
        docExpansion: 'none',
        presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIStandalonePreset
        ],
        plugins: [
            SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
      window.ui = ui
    }
</script>
</body>
</html>
```
Part of the params definition
```json
{
  in: "formData",
  name: "picture",
  description: "Picture",
  type: "file",
  required: false
},
{
  in: "formData",
  name: "pictures",
  description: "Pictures",
  type: "array",
  items: {
    type: "file"
 },
 required: false
}
```
### Describe the bug you're encountering
I can add the multi pictures and run the [Execute] in swagger ui, but it will not post the data with 'multipart/form-data'. It post with 'application/json'.

When I pass params [picture] and [pictures], it will post with 'formdata', but the [pictures] can not get right value. Just like:
```
"picture"=>
  {"filename"=> real file.... }
"pictures"=>["{}"],
```

### Expected behavior
```
"picture"=>
  {"filename"=> real file.... }
"pictures"=>[file1, file2, file3],
```

### Additional context or thoughts
I try to config [requestInterceptor] on SwaggerUIBundle, and change the content-type, but not working.

**Comment by webron** [comment]
Swagger/OpenAPI 2.0 does not support array of files, and so Swagger UI does not support it either. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject.
