### ISSUE TITLE
Facing issue while using Xml/MISMO format schema in swagger UI

### ISSUE THREAD

**Issue by prashantb018** [swagger-api/swagger-ui#5782]
We have schema's defined in XML or MISMO format for most of our API's. Does swagger or open API standard support XML/MISMO format schema? Even the number of lines is around 80000, what are the limitation for number of lines for swagger to render such spec?

**Comment by webron** [comment]
There's limited support for XML, you can read about it here - https://swagger.io/docs/specification/data-models/representing-xml.

Technically there's no limit to the file size, but it would depend on the machine running it.

**Comment by prashantb018** [comment]
If we remove those schema, spec is rendering fine. Schema lines are around 8000 for one api and 1000 for another.
