### ISSUE TITLE
Error creating hook

### ISSUE THREAD

**Issue by Salvador1994** [swagger-api/swagger-ui#5783]
I am experiencing content_type error while hooking, that is saying that content_type is invalid, as shown in the figures.

I need you to help me troubleshoot this error, if you can help I would appreciate

![webhook](https://user-images.githubusercontent.com/44473356/72061835-e71c4080-32d6-11ea-90a9-05709d0b7824.png)
![webhook1](https://user-images.githubusercontent.com/44473356/72061859-ed122180-32d6-11ea-897b-ac619cd41b56.png)

**Comment by webron** [comment]
Going to close the ticket as the issue template was not followed and too many details are missing. From a quick look, it seems like the issue is at the server and has nothing to do with the UI.

**Comment by Salvador1994** [comment]
The issue is that when I try to save the webhook using the api the content-type  is invalid
