### ISSUE TITLE
Problem testing API terminal hook creation via POST method

### ISSUE THREAD

**Issue by Salvador1994** [swagger-api/swagger-ui#5786]
Q&A (please complete the following information)
OS: Linux
Browser: Chromium Web Browser
Version: 68
Method of installation: https://try.gitea.io/api/swagger
Swagger-UI version: I suppose newest 3.23.5
Swagger/OpenAPI version: 2.0

Content & configuration

Configuration of the https://try.gitea.io/api/swagger/ example

Describe the bug you're encountering

When trying to hook through the swagger API, I'm having an error in content_type that says content_type is invalid as it shows the pictures.

To reproduce ...
![hook](https://user-images.githubusercontent.com/44473356/72143879-d089ee00-3397-11ea-943b-05acf12b06b3.png)
![hook1](https://user-images.githubusercontent.com/44473356/72143888-d5e73880-3397-11ea-98c4-f8206b983372.png)

Expected behavior

Intend post reply can view webhook created in specified repository

Additional context or thoughts

**Comment by hkosova** [comment]
This does not seem to be a Swagger UI issue. Based on the error message, the problem could be with the API definition at https://try.gitea.io/api/swagger - maybe it specifies incorrect `consumes` value for that operation. Or the problem could be server-side. I suggest you open a ticket with the provider of `try.gitea.io`.
