### ISSUE TITLE
I need a copy-to-clipboard icon next to each swagger route 

### ISSUE THREAD

**Issue by shah-vidhi** [swagger-api/swagger-ui#5799]
### Is your feature request related to a problem?
I’d love to be able to select the route and copy it, or a little copy-to-clipboard button would work too. Unfortunately, right now if I try to select the text I end up dragging it all the way through.

### Describe the solution you'd like
I want a copy-to-clipboard icon next to each route.

### Additional context
![image](https://user-images.githubusercontent.com/59335758/72429304-a2e8de80-37b5-11ea-8920-b6b2dfce9cda.png)

**Comment by iamandrewluca** [comment]
I will maybe start to implement this feature.

Related component: https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/operation-summary.jsx

**Comment by iamandrewluca** [comment]
Added this in `src/core/components/operation-summary.jsx`

![image](https://user-images.githubusercontent.com/1881266/101831975-60539180-3b3f-11eb-87ac-52c5c1e5965b.png)

Having this, and it works

![image](https://user-images.githubusercontent.com/1881266/101832029-73fef800-3b3f-11eb-91f6-dc653ebbce6e.png)

**Comment by iamandrewluca** [comment]
@tim-lai do you have any interest in adding such a feature in SwaggerUI?
I played around with this feature in draft PR #6706, just to see how easy would be to contribute to SwaggerUI.
If you are interested in this feature, ping me so I'll try to invest more time in checking the boxes in the PR, otherwise I'll close it.
Any feedback is welcome!

ps: open source is hard to maintain

**Comment by tim-lai** [comment]
Hi all, revisiting this issue, some updated questions and comments.

Q: Why is it helpful to "select and copy" the entire operation?
Q: SwaggerUI allows for a sort by tag vs sort by operation? Does this request have the same need for improvement regardless of sort method?
Q: Would you expect the Method type to be included? Why or why not?
Q: Would it be helpful to be able to "select and copy" more than one operation? Perhaps all within a sort group? This may be a separate issue.

Comments: 
- While I think it would be a nice feature to have a copy/paste button, such an implementation generates a lot of visual clutter for definitions that have a lot of operations.
- A possible alternative would be to make it easier to select a block of text (as part of UI rendering).

cc: @iamandrewluca , also I think we can close the draft PR for now.

**Comment by WardenDrew** [comment]
We'd be interested in this as a feature as well. In regards to the visual clutter, leaving it as an option that can be enabled/disabled would be a good compromise to allow teams to determine if they want it or not.

**Comment by readandwrite864** [comment]
I am fine with or without a button, my thing is that I can't even select route manually by Alt + Left click drag, accordion triggers instead

**Comment by nev-21** [comment]
Hi, please, how can i copy the route, I'm using windows/chrome  it doesnt work

**Comment by Teraskull** [comment]
@nev-21 The "Copy" button was broken in the last 2 releases. [v5.3.1](https://github.com/swagger-api/swagger-ui/releases/tag/v5.3.1) fixed the bug.
