### ISSUE TITLE
Add "as curl" syntax

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#580]
as you type, would be nice to show the curl syntax to call the API, as well as different client generators.

**Comment by fehguy** [comment]
added in https://github.com/swagger-api/swagger-ui/commit/21d8a89316ffbb8e5156f1ba1bdcd91a2140dbcf with tests in swagger-js.

**Comment by joelparkerhenderson** [comment]
Great feature - is there a way to see how to use it? For example, I'm using Swagger UI and would like to see the curl commands.

**Comment by fehguy** [comment]
currently it's in the swagger-js client but not exposed in swagger-ui.  Please open a ticket if you want to get it in the UI.

**Comment by joelparkerhenderson** [comment]
Thanks. To open a ticket, is that the same thing as creating a new GitHub issue here? (Or is there a different way to do it?)

**Comment by webron** [comment]
@joelparkerhenderson - yup, just open a new issue.

**Comment by joelparkerhenderson** [comment]
Thanks, I created https://github.com/swagger-api/swagger-ui/issues/1073
