### ISSUE TITLE
Feature: An option to remember authentications

### ISSUE THREAD

**Issue by silverwind** [swagger-api/swagger-ui#5803]
Authentications are lost on page reload and I think a elegant way to solve it would be a "Remember Authorization" checkbox for each auth that was entered. With it enabled, auths could be stored persistently in `localStorage` and applied on page load again after a sanity check that the auth parameters have not changed since it was last stored.

Related: https://github.com/swagger-api/swagger-ui/issues/4851

**Comment by f9fwtf** [comment]
Hi, is it possible to have a "remember me" option so the user can decide if his token gets persisted?

**Comment by ahmedivy** [comment]
Is there is a way to persist the session with fastapi?

**Comment by enkhjile** [comment]
@ahmedivy 
You do that with the following
```python
app = FastAPI(swagger_ui_parameters={"persistAuthorization": True})
```

**Comment by devlopersabbir** [comment]
Okay, there are any way to do it on nestjs??
and i thing swagger should able to do this dynamically.
