### ISSUE TITLE
When i use swagger generate curl command special character escape error

### ISSUE THREAD

**Issue by CarsarSky** [swagger-api/swagger-ui#5807]
- OS: macOS
 - Browser: chrome
 - Version: 2.8.0
 - Swagger-UI version: 2.8.0
When i use swagger try it out a post request.it generate curl command.but curl command some character is escape error.  "\n" is to "\". so it cause json Deserialization failed.

**Comment by webron** [comment]
Please resubmit the ticket following the issue template properly and providing *all* the requested details. You might also notice there's no version 2.8.0 of Swagger UI.
