### ISSUE TITLE
Can't switch between examples in IE.

### ISSUE THREAD

**Issue by miklosvekony** [swagger-api/swagger-ui#5808]
### Q&A (please complete the following information)
 - OS: Windows 10 64 bit
 - Browser: Internet Explorer
 - Version: 11.0.9600.19572, 11.592.18362.0, 11.914.17763.0
 - Method of installation: dist assets
 - Swagger-UI version: 3.24.3
 - Swagger/OpenAPI version: OpenAPI 3.0.1

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Some API
  version: 1.0.0
paths:
  /logon:
    get:
      summary: Login user
      tags:
        - '/logon'
      parameters:
        - name: Client
          in: query
          required: true
          examples:
            zero:
              value: '0'
              summary: A sample limit value
            max:
              value: '50'
              summary: A sample limit value
          schema:
            type: string
      responses:
        '200':
          description: Success response
```

### Describe the bug you're encountering
In IE I can't switch between examples. When I try to switch it remains on the first example and I see an error message in the console.

### To reproduce...

Steps to reproduce the behaviour:
1. Open an API in IE what has multiple examples.
2. Try to switch examples.
3. See error in the console: 
`SCRIPT5007: Unable to get property '0' of undefined or null reference
swagger-ui-bundle.js (51,89721)`

**Comment by webron** [comment]
I'm sorry to say that IE11 is officially not supported anymore. There are some existing workarounds in the code to make parts of it work in IE11, but the maintenance cost of it is too high for us to continue with it.

**Comment by shockey** [comment]
**Closing as IE11 is not supported.**

@miklosvekony, FYI: running Swagger UI's assets through a browser-targeting transpiler (e.g. `babel-preset-env` with IE11 configured as a target) may help you solve this error.
