### ISSUE TITLE
DeepLink Hash is rewritten to prefix with "/"

### ISSUE THREAD

**Issue by kyeotic** [swagger-api/swagger-ui#5810]
### Q&A (please complete the following information)
 - OS: MacOS, windows
 - Browser: Chrome, Brave
 - Version: swagger-ui-dist ^3.24.3
 - Method of installation: swagger-ui-dist ^3.24.3

### Content & configuration

Swagger-UI configuration options:
```js
SwaggerUI({
  deepLinking: true,
})
```

### Describe the bug you're encountering
When loading a page with a `location.hash` after a moment the hash is re-written to include a `/` prefix. 

### To reproduce...

Load any `deepLink` with a has

### Expected behavior
Hash should not be altered

**Comment by shockey** [comment]
@kyeotic, I'm unable to reproduce this by adding `deepLinking: false` to the default development configuration of Swagger UI (in `dev-helpers/index.html`) — are you certain that there isn't some of your own code on the page that is causing this?

**Comment by kyeotic** [comment]
I’m sorry, it’s “true” that causes the issue. I will edit the original comment

**Comment by shockey** [comment]
Ah, I see! That's expected behavior — when you pass `deepLinking: true` and load the page, the UI sets `#/` as the first URL state to reflect no specific operations being expanded on page load.

Is this causing problems for your use case?

**Comment by kyeotic** [comment]
Yes, we have other content on the page that we want to hash-link to, but we cannot scroll to the correct target when the hash gets modified before it loads. Is there a way to keep `deepLink` without the url rewrite?

**Comment by kyeotic** [comment]
@shockey any thoughts?
