### ISSUE TITLE
Model is shown empty without data inside it. 

### ISSUE THREAD

**Issue by batimac25** [swagger-api/swagger-ui#5814]
I'm using swagger in spring boot project. My model data is empty in swagger ui.html.
![Swagger Ui Model Empty](https://user-images.githubusercontent.com/30214559/73441523-23443d80-4379-11ea-86ac-192be47d48b5.jpg)

Following is the dependencies I added in pom.xml
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>

		<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-bean-validators</artifactId>
				<version>2.9.2</version>
		</dependency>

Please anyone let me know the issue. Also the model data is not dispalyed in parameter descriptions as shown in pic below

![image](https://user-images.githubusercontent.com/30214559/73441832-a5346680-4379-11ea-824e-c87ea44d4f73.png)

**Comment by webron** [comment]
Please file an issue with Springfox.
