### ISSUE TITLE
readOnly is ignored when using $ref

### ISSUE THREAD

**Issue by vicpon** [swagger-api/swagger-ui#5816]
I have a schema definition in which I use the readOnly flag on a property that is type object and uses $ref to point to another definition. In the UI, this still shows up in the request body schema. This seems to be a bug.

**Comment by hkosova** [comment]
Can you provide the schema definition to reproduce the issue?

**Comment by vicpon** [comment]
> Can you provide the schema definition to reproduce the issue?

Here's an example:
```
openapi: 3.0.0
info:
  title: Example API
  version: 0.1
servers:
  - url: http://localhost:4000/
paths:
  /mymodel:
    post:
      summary: Creates a model
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model'
      responses:
        '201':
          description: The ID of the new entity.
          content:
            application/json:
              schema:
                type: integer
components:
  schemas:
    model:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        active_definition:
          type: object
          $ref: '#/components/schemas/model_definition'
          readOnly: true
        draft_definition:
          type: object
          $ref: '#/components/schemas/model_definition'
    model_definition:
      type: object
      properties:
        type:
          type: string
```

and it produces this:
![image](https://user-images.githubusercontent.com/2129528/73473835-6b546780-435b-11ea-9d98-4abfef4d0a2b.png)

**Comment by hkosova** [comment]
In OpenAPI 3.0.x, in order to combine a `$ref` with other properties, the `$ref` needs to be wrapped into `allOf`:
```yaml
        active_definition:
          allOf:
            - $ref: '#/components/schemas/model_definition'
          readOnly: true
```

(This will change in the next version, OpenAPI 3.1, which will use the latest JSON Schema that supports keywords alongside $refs.)

<br/>

You can use [Swagger Editor](https://editor.swagger.io) to validate your definitions, it would flag this issue and suggest the solution:

![Swagger Editor warning about keys alongside $ref](https://user-images.githubusercontent.com/8576823/73475861-40d9cd00-43a2-11ea-8ae1-d4e7ff399726.png)

**Comment by vicpon** [comment]
> In OpenAPI 3.0.x, in order to combine a `$ref` with other properties, the `$ref` needs to be wrapped into `allOf`:
> 
> ```yaml
>         active_definition:
>           allOf:
>             - $ref: '#/components/schemas/model_definition'
>           readOnly: true
> ```
> 
> (This will change in the next version, OpenAPI 3.1, which will use the latest JSON Schema that supports keywords alongside $refs.)
> 
> 
> You can use [Swagger Editor](https://editor.swagger.io) to validate your definitions, it would flag this issue and suggest the solution:
> 
> ![Swagger Editor warning about keys alongside $ref](https://user-images.githubusercontent.com/8576823/73475861-40d9cd00-43a2-11ea-8ae1-d4e7ff399726.png)

That did the trick. Thank you! Yes, I should probably use the editor instead of hand coding it :)
