### ISSUE TITLE
OAS3.0.2 version not rendering for OAS 3.0.2 spec

### ISSUE THREAD

**Issue by alok87** [swagger-api/swagger-ui#5823]
## Rendering which is happening
<img width="710" alt="Screenshot 2020-02-04 at 6 54 37 PM" src="https://user-images.githubusercontent.com/9006763/73748825-40657b80-4780-11ea-852d-eef9658c5394.png">

## Rendering which is expected
<img width="652" alt="Screenshot 2020-02-04 at 6 58 44 PM" src="https://user-images.githubusercontent.com/9006763/73748918-625efe00-4780-11ea-9ac7-003f458e860b.png">

OAS3 and 1.0.0 version tags are not getting rendered for OAS3.0.2 specifications

**Comment by webron** [comment]
Please resubmit the issue following the issue template, providing all the requested details. We won't be able to help otherwise.

**Comment by alok87** [comment]
Sure
