### ISSUE TITLE
Provide XML examples as well as JSON

### ISSUE THREAD

**Issue by jugglingcats** [swagger-api/swagger-ui#583]
Apologies if this is a duplicate, I couldn't find it in open issues and very little in other forums.

It would be very nice if Swagger UI could generate XML examples (input and response) for services that produce or consume XML.

It might be possible to implement (relatively) easily by adding conversion methods to ApiListingResource. It could use Jackson to convert from the JSON example to POJO then use JAXB to produce the XML representation, to return to Swagger UI. I guess this would mean changing swagger-jersey-jaxrs, but cannot see how it could be done purely client side. Unfortunately I don't do Scala well, so can't have a go at it...!

Thanks.

**Comment by fehguy** [comment]
depends on https://github.com/swagger-api/swagger-ui/issues/1248

**Comment by fehguy** [comment]
Please track meta issue #1248
