### ISSUE TITLE
Better Customization Examples

### ISSUE THREAD

**Issue by RPGillespie6** [swagger-api/swagger-ui#5842]
### How can we help?
Previously I had installed what is now called swagger-ui 2.X for my company. I added some customizations, such as the ability to select which OpenAPI documention to load from a database, the ability to filter routes by string (and not just simple tag filter, but search through descriptions and parameter names, too), and the ability to serialize the document to PDF:

![image](https://user-images.githubusercontent.com/9853156/74683984-86ffa080-5198-11ea-9dd6-a9c52eccb68a.png)

This was fairly quick and easy to do since 2.X uses just plain old HTML and JS. I've since been asked to upgrade to the latest version, and - let me just say - while the UI looks good, the code is extremely labyrinthine now. I'm lost in an ocean of arbitrary front-end framework files and jargon and I have no idea where to even begin porting these features to the newest version of swagger-ui.

Do I need to learn React? Is the "plugins" framework suitable for this? 

I read some stuff about using `npm install swagger-ui` so I can use it in my own application. Is there a simple API where I can just feed swagger the json document to render and my app will take care of the rest? (selecting document from database, filtering, serializing to pdf, etc)? If so, I couldn't find it (but again, the move to what looks like React has made this code impossible to traverse since I'm not a React developer).

**Comment by RPGillespie6** [comment]
Nevermind, I'm just going to advise that we stay on 2.X. It's clear that the amount of complexity introduced into 3.X is too much for anyone but developers that do front-end web dev full time.

**Comment by Kazanz** [comment]
I agree with this.  There is no good example's on how to customize the React library.  This would make the project far more approachable.

**Comment by RPGillespie6** [comment]
Do you think it's worth re-opening the issue?
