### ISSUE TITLE
Context description is not shown for properties on objects that have an allOf key word

### ISSUE THREAD

**Issue by runebaekkelund** [swagger-api/swagger-ui#5847]
### Q&A
 - OS: windows
 - Browser: chrome
 - Version: Version 80.0.3987.106
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Test
  version: '1'
paths:
  /test: {}
components:
  schemas:
    recipe:
      type: object
      description: Contains recipe data
      properties:
        ingredients:
          type: string
        steps:
          type: string
    restaurant:
      type: object
      description: A restaurant
      properties:
        signatureDish:
          description: The signature dish
          allOf:
            - $ref: '#/components/schemas/recipe'
    pizzaPlace:
      type: object
      description: A pizza place
      allOf:
        - $ref: '#/components/schemas/restaurant'
      properties:
        pasta:
          description: Mmmmm pasta
          allOf:
            - $ref: '#/components/schemas/recipe'
```
### Describe the bug you're encountering
When an object inherits properties from another object through the allOf keyword, then the context description for all properties with their own allOf keyword on the object is ignored.

### Steps to reproduce the behavior:
1. Go to https://editor.swagger.io/
2. Paste the given YAML specification in the editor
3. Click on pizzaPlace component
4. Click on pasta property
5. The context description "Mmmmm pasta" is not shown, instead it shows the default description for the recipe component. However the signatureDish property in restaurant has its context description shown.

### Expected behavior
I would expect that Swagger UI show the description "Mmmmm pasta" for the pasta property on pizzaPlace.

### Screenshots
![Capture](https://user-images.githubusercontent.com/11718350/74737656-94c72b80-5255-11ea-8913-f48c7da7a49c.JPG)

### Additional context or thoughts
To the best of my knowledge the OpenAPI specification is valid, and it seems to be the recommended approach for context descriptions: https://github.com/OAI/OpenAPI-Specification/issues/2033.

**Comment by hkosova** [comment]
If you move `properties` inside `allOf` then the custom `description` will be displayed:

```yaml
    ...
    pizzaPlace:
      description: A pizza place
      allOf:
        - $ref: '#/components/schemas/restaurant'
        - properties:   # <-----
            pasta:
              description: Mmmmm pasta
              allOf:
                - $ref: '#/components/schemas/recipe'
```

**Comment by runebaekkelund** [comment]
Thank you for the fast reply.

It fixes the issue in Swagger UI and shows the descriptions. 

But, the changes to the open api specification resulted in changes for the worse when we autogenerate clients. 

Is it not allowed for an object that inherits properties from another object to have its own set of properties?

**Comment by hkosova** [comment]
Your definition is fine. My example is just a slightly different way to write your definition, but techically they are the same.

It's OK to have `properties` (and other keywords) directly alongside `allOf`, but in my experience some tools produce a better result when extra `properties` are defined inside `allOf`, not alongside it.

**Comment by runebaekkelund** [comment]
Alright, thank you.

I managed to get the clients to look the same by tweaking our framework a bit.

Thank you so much for your help!
