### ISSUE TITLE
"raw" link doesn't respect api_key

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-ui#585]
If you input an api_key in the UI, it is not used when clicking the 'raw' link of an item and gives only partial results.

**Comment by fehguy** [comment]
since 2.1 doesn't show the link by default, I'm guessing this might not need to be supported.

**Comment by mohsen1** [comment]
I believe SwaggerJS should provide the complete link in the model.

**Comment by mohsen1** [comment]
The Raw link is gone. We're converting all old specs to 2.0 before rendering
