### ISSUE TITLE
Input unclear when using an array of a model as "body" input.

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-ui#586]
When the body is an array of a model, the "Model Schema" section is represented properly, but from the "Model" section it may seem that the proper value is a single model. Perhaps we should find a way to clarify it.

**Comment by fehguy** [comment]
will look into this for M1

**Comment by fehguy** [comment]
I think that the model section shouldn't necessarily try to render it exactly, notice how we add dependent models.  I'll move this to m2 for further discussion.

**Comment by fehguy** [comment]
should be fixed in develop_2.0

**Comment by fehguy** [comment]
Verified fixed.  This:

```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Title was not specified"
  },
  "paths": {
    "/pets": {
      "get": {
        "description": "",
        "responses": {
          "200": {
            "description": "Return all pets",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Cat"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Cat": {
      "properties": {
        "id": {
          "type": "string"
        }
      }
    }
  }
}
```
shows this:

![image](https://cloud.githubusercontent.com/assets/249413/6859985/06f555c0-d3de-11e4-986f-c78c8ecb885b.png)
