### ISSUE TITLE
In Swagger-UI Add a Visual Cue that an API is Depreciated

### ISSUE THREAD

**Issue by chalbersma** [swagger-api/swagger-ui#5870]
### Visual Cue API Depreciated

Swagger/OpenAPI definition:
 ```json
...
    "/to/be/retired": {
      "get": {
        "description": "my description",
        "depreciated": true,
        "tags": ...
...
 ```

### Is your feature request related to a problem?
No

### Describe the solution you'd like
I'd like to see a visual dimming or warning of some sort displayed in the UI for api endpoints that get tagged with depreciated. The functionality is noted [here](https://swagger.io/docs/specification/paths-and-operations/) in the spec, but it doesn't do anything in the UI to warn people not to build/use it.

### Describe alternatives you've considered
I mean you could not. It's still does it's main job. It's really just an enhancement.

**Comment by hkosova** [comment]
This functionality already exists - the operation is displayed in gray color, the endpoint path is struckthrough, and the "Warning: Deprecated" label is added at the top of the operation description.

For an example, see `/pet/findByTags` in the Petstore demo:
http://petstore.swagger.io/#/pet/findPetsByTags

**Comment by chalbersma** [comment]
I'm trying to use the /dist methodology to include it directly in a project. Is it possible it's working with the NodeJS version but not the dist version? I'll do some more looking around though. This could be a PEBCAK.

**Comment by hkosova** [comment]
Your example contains a typo - `"deprec*i*ated": true`; it should be `"deprecated": true`. You can use [Swagger Editor](https://editor.swagger.io) to validate your API definitions.

**Comment by chalbersma** [comment]
Damnit. Definitely PEBCAK. So sorry for reporting it.

**Comment by hkosova** [comment]
No problem, glad this is sorted out. :)
