### ISSUE TITLE
file corrupted on download

### ISSUE THREAD

**Issue by graphicsxp** [swagger-api/swagger-ui#5874]
downloading the file from Postman works just fine and the response is correct

but clicking on the hyperlink gives me a corrupted file 

![image](https://user-images.githubusercontent.com/4160415/75329774-8d6cd700-5880-11ea-8cfe-25a6a681decc.png)

I've seen similar bugs reported and it is supposed to be fixed with swagger-ui 3.0 but that's the version I'm using and I still face the problem.

### Q&A (please complete the following information)
   using Swashbuckle 5.6
 - Swagger-UI version: 3
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

**Comment by webron** [comment]
That's a screenshot from Swagger UI 2.x which we no longer support. Please upgrade to the latest version. If the problem persists, file a new ticket.

**Comment by mikip91** [comment]
@graphicsxp : Were you able to resolve this?
