### ISSUE TITLE
swagger-ui show Unknown Type on nullable fields

### ISSUE THREAD

**Issue by bambamboole** [swagger-api/swagger-ui#5879]
### Q&A (please complete the following information)
 - OS: macOS 10.15.3
 - Browser: Chrome
 - Version: 80
 - Method of installation: npm
 - Swagger-UI version: 3.25.0
 - Swagger/OpenAPI version: OpenAPI 3.0

Example Swagger/OpenAPI definition:
openapi.yaml
```yaml
openapi: 3.0.0
info:
  title: test
paths:
  /vendor:
    get:
      operationId: get-organizations-id-vendors
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: vendor.json

```

and next to this file is a `vendor.json` file:
```json
{
  "title": "Vendor",
  "type": "object",
  "description": "A vendor relates to an organization and contains articles",
  "properties": {
    "transformed_type": {
      "type": [
        "string",
        "null"
      ]
    },
    "transformed": {
      "type": [
        "object",
        "null"
      ]
    },
    "article_count": {
      "type": [
        "integer",
        "null"
      ]
    }
  },
  "required": [
    "article_count"
  ]
}
```

Swagger-UI configuration options:
```js
SwaggerUI({
    dom_id: '#swagger-ui',
    url: '/schemas/reference/datapump.v1.yaml'
});
```

### Describe the bug you're encountering
Swagger UI shows `"Unknown Type: string,null"` but this is normal OAS 3 spec to have multiple types for one property. 

### To reproduce...

1. Simply look at the example value in the response

### Expected behavior
Show correctly that this is a nullable field

### Screenshots
![Screenshot 2020-02-27 at 19 30 13](https://user-images.githubusercontent.com/8823695/75474622-98665b00-5997-11ea-8ee8-4ad2f6827cbb.png)

This is how stoplight studio shows this:
![Screenshot 2020-02-27 at 19 33 00](https://user-images.githubusercontent.com/8823695/75474828-f98e2e80-5997-11ea-8638-4e80731bfba4.png)

### Additional context or thoughts

I have no clue why swagger ui does not parse this correctly. Maybe its an issue with json or something like this.

**Comment by hkosova** [comment]
OpenAPI 3.0 does not support type arrays and `type: null`, you need to use [`nullable: true`](https://github.com/OAI/OpenAPI-Specification/blob/v3.0.3-dev/versions/3.0.3.md#user-content-schemanullable) instead:
```
    "transformed_type": {
      "type": "string",
      "nullable": true
    },
```

`type: [..., "null"]` will be supported in the next version, OpenAPI 3.1.

**Comment by webron** [comment]
Furthermore, OAS3 does not support arrays for types, only single values. As @hkosova mentioned, this will be supported in OAS3.1. In this case, Stoplight studio is doing something that does not conform with the spec.

**Comment by bambamboole** [comment]
ok thx for the information!
