### ISSUE TITLE
setting Customized Example for @ApiResponse

### ISSUE THREAD

**Issue by subhransu-das** [swagger-api/swagger-ui#5888]
I am using swagger 2.9.2 and want to put some custom example in the response and my code is as follows

	@ApiResponse(code=200,
		message="fetch test lists",
		examples=@Example(
			value = @ExampleProperty(
				mediaType = "application/json",
				value = "{testingId: 1234, testingName = Testing Name}"
			)
		)
	)
But getting response example value as

	[
		{}
	]

Kindly suggest solution to get my expected response as 

	[
		{
		"testingId": "1234",
		"testingName" = "Testing Name"
		}
	]

**Comment by subhransu-das** [comment]
@dilipkrish can you help me on this?

**Comment by hkosova** [comment]
This looks like a Springfox question. Please ask it in their repository:
https://github.com/springfox/springfox/issues
