### ISSUE TITLE
Where to get source code of swagger-ui 2.9.2 ?

### ISSUE THREAD

**Issue by billysAnna** [swagger-api/swagger-ui#5889]
I checked releases [https://github.com/swagger-api/swagger-ui/releases](https://github.com/swagger-api/swagger-ui/releases) and tags [https://github.com/swagger-api/swagger-ui/tags](https://github.com/swagger-api/swagger-ui/tags), but didn't find the specified version. Can anyone help me ?

**Comment by hkosova** [comment]
There's no Swagger UI 2.9.2, the last 2.x version was 2.2.10.

Did you mean [Springfox](https://github.com/springfox/springfox) 2.9.2?

**Comment by billysAnna** [comment]
@hkosova Thanks for your correction.
