### ISSUE TITLE
Need to show Extensions in swagger-ui-react 

### ISSUE THREAD

**Issue by CrowleyRajapakse** [swagger-api/swagger-ui#5892]
### Q&A (please complete the following information)
 - OS:  macOS
 - Browser: chrome, safari
 - Swagger-ui-react npm Version: 3.25.0
 - Method of installation: npm
 - Swagger-UI version: 3.25.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### Content & configuration

Swagger-UI configuration options:
```js
const SwaggerUI = (props) => {
    const {
        spec, accessTokenProvider, authorizationHeader, api, securitySchemeType,
    } = props;

    const componentProps = {
        spec,
        showExtensions: true,
        showCommonExtensions: true,
        validatorUrl: null,
        defaultModelsExpandDepth: -1,
        docExpansion: 'list',
        requestInterceptor: (req) => {
              <!-- logic -->      
              return req;
        },
        defaultModelExpandDepth: -1,
        plugins: [disableAuthorizeAndInfoPlugin],
    };
    return <SwaggerUILib {...componentProps} />;
};
```

### Screenshots
When using editor.swagger.io tool swagger ui does show the extensions for the swagger file.
<img width="1576" alt="Screenshot 2020-03-04 at 15 16 04" src="https://user-images.githubusercontent.com/23296184/75866598-45732480-5e2b-11ea-8fc4-11dcdda477e1.png">

### How can we help?
When i try to enable the extensions by adding 'showExtensions:true', it doesn't reflect on the swagger console. 
In the swagger-ui-react npm library it is said "Not all configuration bindings are available.". does this include this extensions as well.
If so can we add this functionality as well?

**Comment by naima-shk** [comment]
@char0n  Can I try this one please?

**Comment by tim-lai** [comment]
@naima-shk All PRs welcome!
