### ISSUE TITLE
How to select Scopes check-boxes by default in Authorization pop-up

### ISSUE THREAD

**Issue by mihalios** [swagger-api/swagger-ui#5895]
- OS: Windows 10 
 - Browser: Chrome
 - Version: 80
 - Method of installation: Nuget
 - Swagger-UI version: 3.25.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Swagger/OpenAPI definition:
```
 services.AddOpenApiDocument(document =>
            {
                document.DocumentProcessors.Add(new SecurityDefinitionAppender("Bearer", Enumerable.Empty<string>(),
                    new OpenApiSecurityScheme
                    {
                        Type = OpenApiSecuritySchemeType.OAuth2,
                        Flow = OpenApiOAuth2Flow.AccessCode,
                        Scopes = new Dictionary<string, string> {{"myScope", "myScope"}},
                        AuthorizationUrl = "redacted",
                        TokenUrl = "redacted"
                    }));
            }); 
```

Swagger-UI configuration options:
```
 app.UseSwaggerUi3(settings =>
            {
                settings.OAuth2Client = new OAuth2ClientSettings
                {
                    ClientId = "MyClientID",
                    ClientSecret = string.Empty,
                    AppName = "My App",
                    UsePkceWithAuthorizationCodeGrant = true
                };
            });
```

### Screenshots
![image](https://user-images.githubusercontent.com/2817656/75901965-3a25f600-5e37-11ea-8593-31f33646ee51.png)

### How can we help?
Is there a way to ensure the all scopes are checked by default? In my use case, they should always be so just want to save users from having to click on the check-box?

**Comment by hkosova** [comment]
@mihalios  Swagger UI v. 3.26.1 and later has the [`scopes`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md) configuration for this purpose.

It looks like you are using Swagger UI bundled with the NSwag library, and NSwag doesn't expose the `scopes` configuration yet (https://github.com/RicoSuter/NSwag/issues/2922). You should follow up with NSwag to address this issue.

Alternatively, you can try serving Swagger UI's [`dist` assets](https://github.com/swagger-api/swagger-ui/tree/master/dist) directly and configure them as required.

**Comment by dmrickey** [comment]
@hkosova Even with that link I don't see how to do this in an environment where it is configurable. Can you provide an example in this closed issue that asks this question so that people that are lead here by Google can find the answer they need?

**Comment by MohammadRoshani** [comment]
You can do it in version 6.0 by `OAuthScopes` method.

[![enter image description here][1]][1]


Reference: https://github.com/abpframework/abp/pull/7740

  [1]: https://i.stack.imgur.com/5nFAr.png
