### ISSUE TITLE
Leading and trailing double quotes removed from strings when using Java annotations

### ISSUE THREAD

**Issue by jmoraleda** [swagger-api/swagger-ui#5898]
### Q&A (please complete the following information)
 - OS: [Linux debian]
 - Browser: [firefox]
 - Version: [68.4.1esr]
 - Method of installation: [maven via springdoc-openapi 1.2.33 dependency]
 - Swagger-UI version: [3.25.0]
 - Swagger/OpenAPI version: [Swagger 2.1.1, OpenAPI 3.0]

### Content & configuration
![image](https://user-images.githubusercontent.com/23492126/75958602-72e2c100-5e71-11ea-9389-0ad1a4bc4098.png)

Example Swagger/OpenAPI definition:
```java
@Parameter(description="Optional json string that value associated with key must contain",
           example="\"text/x-python\"" )
@RequestParam(required=false) String value,
```

### Describe the bug you're encountering
I expect to see `"text/x-python"` as sample value instead of `text/x-python`. 

I have also tried doubling the quotes like `example = "\"\"text/x-python\"\""` but in this case no value shows. I have also tried using back slashes to escape as  `example = "\\\"text/x-python\\\""` which then shows as  `\"text/x-python"\`

### Additional context or thoughts
This seems to be a case of an over zealous parser.

**Comment by webron** [comment]
It's a bit hard to say because you've not provided the actual API definition that's loaded into Swagger UI. The Java code itself is irrelevant to how it's rendered in a sense, because there's no way of telling what is actually being sent to the UI. Can you provide with the actual API definition?

**Comment by jmoraleda** [comment]
Hello @webron. Thank you. I gather that you are asking about how springdoc-openapi calls swagger ui. I am not familiar with the library, but I just poked inside a little, and I found that https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/GenericParameterBuilder.java has the following code starting at line 147. Does this help?

```java
if (StringUtils.isNotBlank(parameterDoc.example())) {
	try {
		parameter.setExample(Json.mapper().readTree(parameterDoc.example()));
	}
	catch (IOException e) {
		parameter.setExample(parameterDoc.example());
	}
}
```
 (Above variable `parameter` is of type `io.swagger.v3.oas.models.parameters.Parameter`)

**Comment by jmoraleda** [comment]
In case it helps, through further experimenntation I have found that
```java
@Parameter(description="Optional json string that value associated with key must contain",
           example="\"\\\"text/x-python\\\"\"" )
```
produces the correct result.
![image](https://user-images.githubusercontent.com/23492126/76042606-197aa080-5f0a-11ea-8543-07fb3c3f786f.png)

**Comment by webron** [comment]
Unfortunately, no Java code is going to help in solving the issue. Swagger UI loads a json or yaml file in it, and that's the file you need. If you can't find the URL where the file is exposed, you can use the network panel of your browser to find the file.

**Comment by jmoraleda** [comment]
This is what I get in the large json file that appears in the api-docs URL:  
```json
{"name":"value",
 "in":"query",
 "description":"Optional json string that value associated with key must contain",
 "required":false,
 "schema":{"type":"string"},"example":"\"text/x-python\""}
```

This is in when I type in my annotation `example="\"\\\"text/x-python\\\"\""` and I get in the UI what I want: `"text/x-python"`.

Why does the example get parsed as json  when the schema says it is a string?

**Comment by webron** [comment]
Can't help you with the Java part of the question, unfortunately. While the annotation you use is ours (from swagger-core), an annotation does not contain any logic. The tool that does the parsing, in your case, springdoc-openapi, seems to have a funky behavior, and you'd need to file an issue with them to resolve it.

**Comment by jmoraleda** [comment]
Thank you for your help @webron. I will close the issue and open one with springdoc-api, referencing this one in case someone has this same problem and finds this answer.
