### ISSUE TITLE
How to configure swagger.json for building swagger-ui?

### ISSUE THREAD

**Issue by vvksahoo** [swagger-api/swagger-ui#5899]
I am building a swagger-ui for my project , have swagger.json which is specific to my project . 
i am wondering that is there any way we can load that json and then swagger-ui come up?  

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
        organizationConfig: null,
        definitionList: null,
        definitionLink: "https://petstore.swagger.io/v2/swagger.json"
      } 
 

```

```
?yourQueryStringConfig
```

### How can we help?

```definitionLink: "https://petstore.swagger.io/v2/swagger.json"``` with this its working fine but i would like to modify for my project , is there any way we can ready the json show on UI?

**Comment by tim-lai** [comment]
Configuration documentation can be found here: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
