### ISSUE TITLE
Failed to convert value of type 'java.lang.String' to required type 'java.util.List'

### ISSUE THREAD

**Issue by bma6026** [swagger-api/swagger-ui#5900]
Hello, 
I upgraded springfox from 2.8.0 to 3.0.0.SNAPSHOT and spring boot from 1.5 to 2.2.
I have an issue with items parameter (type List<Long>()).
Here the openApi code : 
`/services/rest/..../{idPersonne}/.../{idPreferenceContact}:
    put:
      tags:
        - "Personne V4"
      summary: "Modifier ....."
      description: ""
      operationId: "modifierPreferenceContact"
      parameters:
        - name: "idPersonne"
          in: "path"
          description: "Id de ..."
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "idPreferenceContact"
          in: "path"
          description: "Id de ..."
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "canauxContact"
          in: "query"
          description: "Liste des Id de ..."
          schema:
            type: "array"
            items:
              type: "integer"
              format: "int64"
      responses:
        200:
          description: "OK"
        400:
          description: "erreur dans la requête"
        404:
          description: "élement non trouvé"`

My dependencies in pom.xml : 

`            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>${swagger.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>${swagger.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-core</artifactId>
                <version>${swagger.core.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${swagger-annotations.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-data-rest</artifactId>
                <version>${swagger.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.plugin</groupId>
                <artifactId>spring-plugin-core</artifactId>
                <version>2.0.0.RELEASE</version>
            </dependency>

            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-spring-web</artifactId>
                <version>${swagger.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.integration</groupId>
                <artifactId>spring-integration-http</artifactId>
                <version>5.1.4.RELEASE</version>
            </dependency>`

and the error is 

`{
  "timestamp": "2020-03-05T11:42:55+0100",
  "status": 400,
  "error": "Bad Request",
  "message": "Failed to convert value of type 'java.lang.String' to required type 'java.util.List'; nested exception is java.lang.NumberFormatException: For input string: \"newArrayList<Long>()\"",
  "path": "/bic-service-webapp/services/rest/.../1002590762/preference-contact/20"
}`

Any Help please !

**Comment by hkosova** [comment]
Open an issue with Springfox: https://github.com/springfox/springfox/issues
