### ISSUE TITLE
Nullable Enums do not display as dropdown

### ISSUE THREAD

**Issue by chrisheil** [swagger-api/swagger-ui#5904]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version: Both 80
 - Method of installation: editor.swagger.io
 - Swagger-UI version: 3.18.3 (assuming latest is running on site)
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
YAML is created using NSwag v13.2.4.0 (NJsonSchema v10.1.7.0 (Newtonsoft.Json v9.0.0.0))
SwaggerUI is used to render the YAML via editor.swagger.io

Example Swagger/OpenAPI definition:
```yaml
x-generator: NSwag v13.2.4.0 (NJsonSchema v10.1.7.0 (Newtonsoft.Json v9.0.0.0))
openapi: 3.0.0
info:
  title: My Title
  version: 1.0.0
servers:
  - url: 'https://localhost:44359'
paths:
  /Demo:
    get:
      tags:
        - Demo
      operationId: Demo_Get
      parameters:
        - name: DemoSelection
          in: query
          schema:
            $ref: '#/components/schemas/DemoEnum'
          x-position: 1
        - name: DemoSelectionNullable
          in: query
          schema:
            nullable: true
            oneOf:
              - $ref: '#/components/schemas/DemoEnum'
          x-position: 2
      responses:
        '200':
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
components:
  schemas:
    DemoEnum:
      type: integer
      description: ''
      x-enumNames:
        - value1
        - value2
      enum:
        - 0
        - 1
```

### Describe the bug you're encountering
In the example above, an Enum is defined and used by two query parameters. The first parameter uses the Enum directly, the second marks it as nullable

When rendering the first query parameter, a dropdown is created for the values defined by the Enum. When rendering the second query parameter, only a textbox is displayed with no Enum values described

### Screenshot

![image](https://user-images.githubusercontent.com/39273281/76112562-09b19980-5fa8-11ea-8fb6-d5dfb93f9f3f.png)

### To reproduce...

1. Copy provided spec into editor.swagger.io
2. See error

### Expected behavior
A dropdown in both query parameters

### Additional context or thoughts

When testing the schema against ReDoc, it recognizes the second parameter as a nullable integer type, with possible values being the expected Enum

http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/chrisheil/EnumGenExample/master/swagger.json

[Link to the original issue](https://github.com/RicoSuter/NJsonSchema/issues/1134) in the NJsonSchema project which is the tool generating the api spec, but the author recommended I post it here as well.

**Comment by hkosova** [comment]
According to the [recent clarifications](https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md#detailed-design) from OpenAPI Specification maintainers, that's not how nullable enums are defined in OAS 3.0.x.

Firstly, `nullable: true` only has effect when `type` is specified in the same Schema Object (that is, when `type` and `nullable` are adjacent within the same schema). `nullable: true` [does not modify](https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md#can-allof-be-used-to-define-a-nullable-subtype-of-a-non-nullable-base-schema-see-1368) the subschemas in `allOf`/`oneOf`/`anyOf`.

Secondly, the `null` value [must be included](https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md#if-a-schema-specifies-nullable-true-and-enum-1-2-3-does-that-schema-allow-null-values-see-1900) in the `enum` value list.

So the correct way to define a nullable enum is:
```yaml
components:
  schemas:
    NullableDemoEnum:
      type: integer
      nullable: true
      enum:
        - 0
        - 1
        - null
```

<br/>
The next version of the spec, OAS 3.1, will make things easier thanks to full support of JSON Schema 2019-09. In OAS 3.1 your example can be written as follows:

```yaml
        - name: DemoSelectionNullable
          in: query
          schema:
            oneOf:
              - type: 'null'   # Note the quotes around 'null'
              - $ref: '#/components/schemas/DemoEnum'
          x-position: 2
```

**Comment by chrisheil** [comment]
Thank you for the explanation, that makes more sense now.

**Comment by RicoSuter** [comment]
What? They now introduce “null” type after introducing nullable property? What a mess..

**Comment by RicoSuter** [comment]
> Firstly, nullable: true only has effect when type is specified in the same Schema Object 

and

> So the correct way to define a nullable enum is: null value

That’s also very bad - what if i want to reference the enum in a nullable and non nullable property/context? I also dont want to duplicate the enum as this would generate it twice...

**Comment by hkosova** [comment]
@RicoSuter 
> what if i want to reference the enum in a nullable and non nullable property/context?

In OAS 3.0.x you need 2 schemas. Or make the base schema nullable and then [disallow nulls](https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md#can-allof-be-used-to-define-a-non-nullable-subtype-of-a-nullable-base-schema) in contexts where they are not allowed:
```yaml
components:
  schemas:
    NullableEnum:
      type: integer
      nullable: true
      enum: [0, 1, null]
...

# Non-nullable enum
allOf:
  - $ref: '#/components/schemas/NullableEnum'
  - not:
      enum: [null]
```
If you ask me, I think the `not` approach is counter-intuitive. This might be one of the reasons why OAS 3.1 has switched from its own flavor of JSON Schema (aka "extended subset") to full JSON Schema including `type: 'null'`.

OAS 3.1 will make use case easier to define and interpret, you can have a base non-nullable schema and then make it nullable when needed by using `oneOf` + `type: 'null'` as shown in my [previous answer](https://github.com/swagger-api/swagger-ui/issues/5904#issuecomment-595931625).
