### ISSUE TITLE
Swagger UI - Docker Not working

### ISSUE THREAD

**Issue by jayadityan** [swagger-api/swagger-ui#5912]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by jayadityan** [comment]
Tried to open Swagger UI http://localhost:8080/ from laptop but now roking. Can you please help?

**Comment by webron** [comment]
Looks like you commented on a related issue, no reason to open a new one.

**Comment by sanleon** [comment]
I found typo(?) on [installation](https://github.com/swagger-api/swagger-ui/blame/master/docs/usage/installation.md#L65).


can't access port 80 for nginx. need to using port 8080
e.g.) can run with below command.
```
docker run -p 8080:8080 swaggerapi/swagger-ui
```
