### ISSUE TITLE
Internal Server Error.

### ISSUE THREAD

**Issue by mathewsun** [swagger-api/swagger-ui#5916]
![image](https://user-images.githubusercontent.com/2837780/76607829-b4383800-6525-11ea-9e5e-015b9ab9fd4b.png)

Reinstall swagger, not resolve problem.
Swagger not show error description.

**Comment by mathewsun** [comment]
Swagger broken when add controller with routing [Route("[controller]")], if add [Route("api/[controller]")] all is work fine.

**Comment by mathewsun** [comment]
Resolve problem.
Add [HttpGet] attribute to Index method.

**Comment by webron** [comment]
This does not seem to be a Swagger UI issue. If you think otherwise, please file a new issue following the issue template.
