### ISSUE TITLE
Mapping OData Route with swagger

### ISSUE THREAD

**Issue by kisalay1988** [swagger-api/swagger-ui#5924]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser:Chrome
 - Version: [e.g. 22]
 - Method of installation: npm
 - Swagger-UI version: 5.1.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### How can we help?
I have created a .NET Core 3.0 Web API with OData and Swagger. Configured the OData route as below in Configure method of `Startup.cs`

```csharp
app.UseMvc(routeBuilder =>
            {
                routeBuilder.EnableDependencyInjection();
                routeBuilder.Select().OrderBy().Filter().MaxTop(200).Count().SkipToken();
                routeBuilder.ServiceProvider.GetRequiredService<ODataOptions>().UrlKeyDelimiter = Parentheses;
                routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());
            });
```

In my controller the Route is configured as :

```csharp
   [Route("api/[controller]")]
    public class ControlController : ODataController
    {
...
```

1. If I make a call using http://localhost/odata/Control - Data is returned in Odata format as its routed through Odata
2. If I make a call using http://localhost/api/Control - Data is returned an array of my return type object but not in odata format
3. If I change Route attribute value over controller to "odata/[controller]", then no data in Odata format is returned but returned as point 2 above.

Is there a way I can make swagger to route through the mapped odata service route and get the desired output?

**Comment by webron** [comment]
There's actually no Swagger project for .net (except code generation), so this is not an issue for us to address. You should file a ticket with whichever project you do use (likely Swashbuckle, but could be others).
