### ISSUE TITLE
Authorization header is completely ignored at API level 

### ISSUE THREAD

**Issue by primesoft-mdubey** [swagger-api/swagger-ui#5928]
### Q&A (please complete the following information)
 - OS: [Windows]
 - Browser: [chrome]
 - Version: [80.0.3987.132]
 - Swagger-UI version: [3.0.0]
 - Swagger/OpenAPI version: [Swagger 3.0, OpenAPI 3.0]

Example Swagger/OpenAPI definition:
```yaml
 /xyz/api:
    parameters:
      - $ref: '#/components/parameters/auth'
    get:
      summary: Fetch list of api
      security:
             - bearerAuth: []
      tags:
        - API
   
```

```
```

### Describe the bug you're encountering

1. I want to have bearer authorization at API level. I have removed the security tag in components, and added Authorization header as normal header at api level. when I am sending request by adding bearer auth token in Authorization header.In request header Authorization header is not being passed by swagger due to which authentication is failing.
 
or 

2. I want to have bearer authorization at API level. I have included the security tag in components, and added 
security: - bearerAuth: [] at api level. when I am sending request by adding bearer auth token. In request header Authorization header is not being passed by swagger due to which authentication is failing.

When I added 
security: - bearerAuth: [] at global level then it is sending the Authorization header as part of the request header.

API level authorization is not working as expected
### 

### Expected behavior

1.When we add Authorization header as normal headers it should send Authorization as part of the request

or 

2.When we add 
security: - bearerAuth: [] at API level. it should send the Authorization header as part of the request.

**Comment by hkosova** [comment]
Hi @primesoft-mdubey, can you post your full API definition?

Also please double-check which Swagger UI version you use. Open the browser developer tools, evaluate `versions` and check the version there.

**Comment by hkosova** [comment]
> 1. ... I have removed the security tag in components, and added Authorization header as normal header at api level. when I am sending request by adding bearer auth token in Authorization header.In request header Authorization header is not being passed by swagger due to which authentication is failing.

This is not going to work - OpenAPI 3.0 says that [tools should ignore](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#user-content-parametername) header parameters named `Authorization`. Authentication should be defined using `securitySchemes` + `security` instead - see https://swagger.io/docs/specification/authentication/.

<br/>

As for 2, we cannot troubleshoot this without a full example. If this is still an issue for you, post a full API definition that demonstrates the issue and I will reopen the ticket.

**Comment by Vladlysenko75** [comment]
@primesoft-mdubey , yeah, @hkosova  is right.

I'll show you my solution for this:

First of all, i am using swagger-jsdoc lib, it allows me to use my config in js format.

First you need to add these parameters in your swaggerConfig.definition: 

`components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
    },`

Then, in those paths, where you need JWT token auth add this parameters like these:

`'/your/path: {
    post: {
      security: [{ bearerAuth: [] }],
      parameters: [
        {
          in: 'header',
          name: 'Authorization',
          required: true,
          schema: {
            type: 'string',
            example: 'Bearer <token>',
          },
        },
      ],
    },
};`

After this you will see little padlock in the end of your pass. After pressing on it the modal will show up where you need to pass your token to authorize(insert just token, without word 'Bearer'). After that your Authorization headers will be sent.

![image](https://user-images.githubusercontent.com/90869283/177755137-0298641d-f200-433d-b16b-cb8649ee2d62.png)
![image](https://user-images.githubusercontent.com/90869283/177755172-3a0ab014-0e41-4949-b1de-76a02b65e3a6.png)
