### ISSUE TITLE
Problem with x-www-form-urlencoded and arrays

### ISSUE THREAD

**Issue by ShortByte** [swagger-api/swagger-ui#5929]
### Q&A
 - OS: Windows 10
 - Browser: Chrome
 - Swagger/OpenAPI version: OpenAPI 3.0.0
 - OpenAPI Server: NodeJS

### Content & configuration

Hello,

I have a problem with defining arrays in OpenAPI. What am I doing wrong?

GUI:

![chrome_90uPhS0xEY](https://user-images.githubusercontent.com/10292289/77239122-43ed7e80-6bd7-11ea-8586-447bbb1031d8.png)

Error:

![chrome_3hiKqcx3iY](https://user-images.githubusercontent.com/10292289/77239128-4c45b980-6bd7-11ea-9c53-8358ecbc93fd.png)

Example Swagger/OpenAPI definition:
```yaml
  /test:
    post:
      operationId: test
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                color:
                  type: array
                  items:
                    type: string
            encoding:
              color:
                style: form
                explode: false
      responses:
        "200":
          description: 200 OK
      x-swagger-router-controller: Default
```

**Comment by hkosova** [comment]
Your definition is syntactically correct.

Are you sure your server expects comma-separated array values `color=red,blue`? Maybe it wants a different format, e.g. `color=red&color=blue`.

**Comment by ShortByte** [comment]
> Your definition is syntactically correct.
> 
> Are you sure your server expects comma-separated array values `color=red,blue`? Maybe it wants a different format, e.g. `color=red&color=blue`. If you run this cURL command does it work?
> 
> ```
> curl -X POST "http://localhost:8080/v1/test" -H "accept: */*" -H "Content-Type: application/x-www-form-urlencoded" -d "color=red&color=blue"`
> ```

@hkosova Thanks for answering.

Curl command from swagger ui
```curl
curl -X POST "http://localhost:8080/v1/test" -H "accept: */*" -H "Content-Type: application/x-www-form-urlencoded" -d "color=asdasd%2Casdasd"
```

Your curl command
```curl
curl -X POST "http://localhost:8080/v1/test" -H "accept: */*" -H "Content-Type: application/x-www-form-urlencoded" -d "color=red&color=blue"
```

With your curl command it works and the NodeJS server accepts it as JsonObject with JsonArray. Apparently Swagger UI does not get the correct formatting.

**Comment by hkosova** [comment]
If your server accepts an exploded array i.e. `color=red&color=blue` then you need to use `explode: true` in the array encoding attributes:
```yaml
            encoding:
              color:
                style: form
                explode: true  # <----
```

However, exploded arrays in form data are not supported yet, this is tracked in #4836.

**Comment by hkosova** [comment]
Closing - please follow #4836 for updates on support for exploded arrays.
