### ISSUE TITLE
Swagger-ui 2.2.10 corrupting the .ecf files.

### ISSUE THREAD

**Issue by mikip91** [swagger-api/swagger-ui#5933]
### Q&A (please complete the following information)
 - OS: [macOS]
 - Method of installation: dist
 - Swagger-UI version: [2.2.10]
 - Swagger/OpenAPI version: [Swagger 2.0]

### Content & configuration

Swagger-UI configuration options:
```js
SwaggerUI({
   * @version v2.2.10
 * @link http://swagger.io
 * @license Apache-2.0
})
```

### Describe the bug you're encountering
I have a requirement of downloading an .ECF file. I can get the file successfully but when I download it and open it the ecf file gets corrupted.

### Expected behavior
File should not get corrupted. 

### Response Headers
 access-control-expose-headers: Content-Disposition 
 allow: GET, HEAD, OPTIONS 
 cache-control: no-cache 
 content-disposition: attachment; filename=Jurassic Client 2017_XDM_EBS_Cloud_E2E_test_Profiling_20200324_113807.ecf 
 content-length: 9549 
 content-type: application/octet-stream 
 date: Tue, 24 Mar 2020 22:53:03 GMT 
 pragma: no-cache 
 status: 200 
 strict-transport-security: max-age=15724800; includeSubDomains 
 vary: Origin 
 x-frame-options: SAMEORIGIN 

@webron @shockey @fehguy

**Comment by hkosova** [comment]
Swagger UI 2.x is no longer supported. Please upgrade to the latest version (3.25.0) and if the problem persists, open a new ticket.
