### ISSUE TITLE
Does Swagger documentation create controller ou route while executing ?

### ISSUE THREAD

**Issue by Eric-Bryan** [swagger-api/swagger-ui#5936]
Hello everybody,
I am trying to set rights (according to my own database repository) to my C# Rest Api Swagger documentation.
In other words, I would like to decide who can display the Swagger documentation for my Rest Api.
I would like to know how does Swagger works.
Does it create controllers, routes when executing which I can catch by code to check the rights before displaying ?
What are the objects I can interact with ?
I would like to read the current routes to check in my database who can display documentation for this route.
Thank you very much in advance.
Eric.

**Comment by webron** [comment]
Swagger UI simply renders the API definition it's given. It does not provide access control out-of-the-box. If you're looking for that, you'd need to implement it yourself.

**Comment by hkosova** [comment]
This looks like a Swashbuckle question and not a Swagger UI question.

**Comment by Eric-Bryan** [comment]
hkosova, webron :
Thanks for your answers.
I will follow your advices.
Eric
