### ISSUE TITLE
Swagger UI is blank: Spring boot

### ISSUE THREAD

**Issue by strivedi7** [swagger-api/swagger-ui#5937]
Getting hundred of this error, 

Refused to load http://localhost:8080/webjars/springfox-swagger-ui/swagger-ui-bundle.js?v=2.8.0-SNAPSHOT because it does not appear in the script-src directive of the Content Security Policy. 

It seems like "Content Security Policy" is the issue. 

Spring boot application with the following dependencies. 
```
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>

```
I see a few other bugs are closed but did not find any suitable solution.

**Comment by webron** [comment]
Please file an issue with Springfox.
