### ISSUE TITLE
Valid tuple schemas are rejected by Swagger UI

### ISSUE THREAD

**Issue by julienrf** [swagger-api/swagger-ui#5938]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Firefox
 - Version: 74
 - Method of installation: online editor at https://editor.swagger.io
 - Swagger-UI version: unknown
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:

```yaml
openapi: 3.0.3
info:
  title: API
  version: 1.0.0
paths:
  '/foo':
    get:
      responses:
        '200':
          description: ''
components:
  schemas:
    bar:
      type: array
      items:
      - type: number
      - type: number
```

### Describe the bug you're encountering

The UI shows the following error:

![Screenshot from 2020-03-27 11-10-53](https://user-images.githubusercontent.com/332812/77745487-a7ced780-701b-11ea-9619-fea080e7a9ef.png)

If I expand the schema of `bar`, I see another error:

![Screenshot from 2020-03-27 11-12-54](https://user-images.githubusercontent.com/332812/77745656-f67c7180-701b-11ea-8150-51bcc1efdf1d.png)

### To reproduce...

1. Go to https://editor.swagger.io
2. Paste the YAML document provided above

### Expected behavior

Tuple schemas are valid array schemas and should be supported by Swagger UI. From the [specification](https://tools.ietf.org/html/draft-zyp-json-schema-00#section-5.3):

> When this is an array of schemas and the instance value is an array, each position in the instance array must conform to the schema in the corresponding position for this array.  This called tuple typing.

They should not be reported as an error, and expanding an array schema that is a tuple schema should display the successive schemas of the elements of the tuple.

**Comment by hkosova** [comment]
This is not valid in OpenAPI 3.0 but will be valid in OpenAPI 3.1 which will support full JSON Schema.

In OpenAPI 3.0, `items` requires a single schema and doesn't support JSON Schema tuple syntax. See [OpenAPI Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object).
```yaml
# OAS 3.0
type: array
items:
  type: number
```
