### ISSUE TITLE
When using a ModelBinder with Name the UI doesn't send param value in QueryString

### ISSUE THREAD

**Issue by davidikin45** [swagger-api/swagger-ui#5943]
public string Include { get; set; }

[ModelBinder(BinderType = typeof(UserIncludeModelBinder), Name = nameof(Include))]
public IncludeSpecification<T> IncludeSpecification { get; set; }

An 'include' textbox is shown on the UI as expected but when clicking execute the value entered is not submitted as QueryString param

![image](https://user-images.githubusercontent.com/20446892/78331688-78215180-757e-11ea-8f0e-8f24734191ef.png)

**Comment by webron** [comment]
Please file the issue again following the issue template. Too many details are missing for us to be able to assist.
