### ISSUE TITLE
Group Operations multi levels in a tree like

### ISSUE THREAD

**Issue by lakani** [swagger-api/swagger-ui#5947]
hi 

i'm new to Swagger, but i really likes it,
i'm rewriting our backend to be be a rest web api

we have many controllers in different namespaces and we are planing for version 2 of our API
example Route,
1 - /sis/openCore/api/v1/def-mgmt/DefGL 
2- /sis/openCore/api/v1/def-mgmt/DefAcct
3- /sis/openCore/api/v1/Trans/DefAE
4- /sis/openCore/api/v1/Trans/AmortAE

and we have the same controllers for v2

and for each controller we have all of the methods (PUT , GET, POST, DELETE)

can we have something like group for V1 and within it another group for (def-mgmt) and within it another group for ( DefGL ) and below it the operations for that controller 

some thing like this

-v1
-----def-mgmt
----------DefGL
---------------PUT
---------------POST
---------------GET
----------DefAcct
---------------PUT
---------------POST
---------------GET

**Comment by hkosova** [comment]
Nested tags are not supported by the OpenAPI Specification, see https://github.com/OAI/OpenAPI-Specification/issues/1367.

You can emulate nested tags by using something like `tag1/tag2` or `tag1.tag2` but you'd have to modify the source code if you want to render that as nested tags.
