### ISSUE TITLE
Support YAML file loading

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#595]
The current 2.0 spec should be supported with either YAML or JSON.

**Comment by webron** [comment]
Since we're currently not going to support this, I'm going to close it.

**Comment by pmackay** [comment]
Are there any tools that can convert a standalone YAML file into JSON? I take the point about not updating all the dependent libraries and tools to be able to take YAML as input, but it would be good to have a 1 step command line process to handle conversion so YAML can be used as the origin of a spec **outside** the editor.

**Comment by webron** [comment]
https://www.npmjs.com/package/yamljs
http://yamltojson.com/
http://www.commandlinefu.com/commands/view/12218/convert-yaml-to-json

Also, contrary all my rant here, we **are** going to support loading of YAML here. 
https://github.com/swagger-api/swagger-ui/issues/1047

**Comment by Petah** [comment]
+1

**Comment by webron** [comment]
@Petah - it's already supported...
