### ISSUE TITLE
Render locally uploaded file in a web page (Vue component)

### ISSUE THREAD

**Issue by TNSaturday** [swagger-api/swagger-ui#5954]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80, 64bit
 - Method of installation: npm
 - Swagger-UI version: 3.25
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
any LOCAL yaml file
```

Swagger-UI configuration options:
```js
SwaggerUI({
  url: "file uploaded from a form",
  dom_id: "swagger-ui",
  deepLinking: false,
  layout: "BaseLayout",
})
```

### Screenshots
![image](https://user-images.githubusercontent.com/27682909/78799321-a493fe00-79c2-11ea-9c8b-2a75cf1221ef.png)

### How can we help?
In my Vue component I have a form that allows user to upload a file. Basically, what I want is to render api file uploaded by a user IN the same web page, without putting it somewhere on the server and then giving SwaggerUI an URL. Is that possible?

**Comment by tim-lai** [comment]
@TNSaturday This is possible with SwaggerUI, so I assume also possible with a Vue project. Take a look at `https://editor.swagger.io`, File -> Import file. `swagger-editor` project can be found here: https://github.com/swagger-api/swagger-editor
