### ISSUE TITLE
Basic Authorization: Curl example use low case Authorization

### ISSUE THREAD

**Issue by 6543** [swagger-api/swagger-ui#5956]
Basic Authorization as defined in https://tools.ietf.org/html/rfc7617

use `Authorization` but swagger-ui show `authorization` as example

**Comment by hkosova** [comment]
HTTP header names are case-insensitive according to RFC 7230 section 3.2.
https://tools.ietf.org/html/rfc7230#section-3.2

> Each header field consists of a **case-insensitive field name** followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.
