### ISSUE TITLE
XML Body parameter examples not shown

### ISSUE THREAD

**Issue by wsalembi** [swagger-api/swagger-ui#5962]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version:  80.0.3987.100
 - Method of installation: N/A
 - Swagger-UI version: latest from editor.swagger.io
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'
info:
  version: '1.0'
  title: MockBackend SOAP in Swagger format
  contact: {}
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /MockBackend/v1/:
    post:
      description: Generate a valid SOAP response compliant with XML schema
      operationId: generateValid
      deprecated: false
      produces:
      - text/xml
      consumes:
      - text/json
      parameters:
      - name: SOAPBody
        in: body
        required: true
        description: ''
        schema:
          type: object
          xml:
            name: GenerateValidRequest
            namespace: http://example.com/mock/v1
          example: "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:v1=\"http://example.com/mock/v1\" xmlns:v11=\"http://example.com/mock/types/v1\">\n   <soapenv:Header/>\n   <soapenv:Body>\n      <v1:GenerateValidRequest>\n         <v11:Message>?</v11:Message>\n         <!--Optional:-->\n         <v11:Status>?</v11:Status>\n      </v1:GenerateValidRequest>\n   </soapenv:Body>\n</soapenv:Envelope>"
      - name: SOAPAction
        in: header
        required: true
        type: string
        default: "http://example.com/mock/v1/generateValid"
      responses:
        200:
          description: OK
          headers: {}
          schema: 
            type: object
          examples:
            text/xml:
              "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:v1=\"http://example.com/mock/v1\" xmlns:v11=\"http://example.com/mock/types/v1\">\n   <soapenv:Header/>\n   <soapenv:Body>\n      <v1:GenerateValidResponse>\n         <v11:Message>?</v11:Message>\n         <!--Optional:-->\n         <v11:Status>?</v11:Status>\n      </v1:GenerateValidResponse>\n   </soapenv:Body>\n</soapenv:Envelope>"
```

Swagger-UI configuration options:
N/A

### Describe the bug you're encountering
I admit, describing SOAP in a Swagger format is a bit odd, but we use a commercial tool that does this.

This issue is the XML example of the SOAPBody parameter is not displayed. Instead a generated one based on the xml tags is.

### To reproduce...

1. Go to editor.swagger.io
2. Copy the swagger above
3. See error

### Expected behavior
If an example is provided, I would like it to be displayed, cfr. what happens for responses.

### Screenshots
![default](https://user-images.githubusercontent.com/168668/79045310-b667e200-7c0a-11ea-8015-a0aee5cc5c17.png)
![consumes_text_json](https://user-images.githubusercontent.com/168668/79045311-b7007880-7c0a-11ea-9344-029e6b007f29.png)
![type_string](https://user-images.githubusercontent.com/168668/79045313-b7990f00-7c0a-11ea-9563-34b10b4073a5.png)

### Additional context or thoughts
Two remarks:
* If you put consumes: application/json, the example is displayed
* If you change the type of SOAPBody to string, the content of the SOAP Body is displayed but XML charecters are escaped

**Comment by webron** [comment]
It looks like indeed this is a bug related to the example generation if you specify the media type to be `application/xml`. However, given your use case (and the fact that OpenAPI is not even remotely intended to describe SOAP APIs), we can't really prioritize fixing this.
