### ISSUE TITLE
Support Hierarchical Tags

### ISSUE THREAD

**Issue by kael-shipman** [swagger-api/swagger-ui#5969]
### Is your feature request related to a problem?

There is growing support in the OAS community for the idea of hierarchical tags (see OAI/OpenAPI-Specification#1367). The current consensus is that UIs like SwaggerUI can implement this with no change required in the OAS, and that this would be a much appreciated feature. I would like to implement it in SwaggerUI and would like help identifying the best way to do so.

### Describe the solution you'd like

Tags such as `Petstore|Mammals|Dogs` should render as

```
## Petstore

### Mammals

#### Dogs

....
```

## EDIT: Permanent Solution

**I've implemented and published a plugin for this. Instructions for use are [here](https://github.com/kael-shipman/swagger-ui-plugins/blob/hierarchical-tags-self-hosted/packages/hierarchical-tags/README.md).** It works well as an ES module include in a webpack scenario OR as a global module via unpkg. ~~There is also a PR out for this ([here](https://github.com/swagger-api/swagger-ui/pull/7050)), but it is long stale and I doubt that Swagger will ever take interest in it.~~ (The PR has now been closed without merging.)

**Comment by kael-shipman** [comment]
I'm willing and able to implement this, even if just for my own fork of SwaggerUI, so regardless of whether this feature gets official approval or not, I'd love for someone to give me a hint at where to start.

**Comment by MarcusBondezan** [comment]
This would be great! The doc would be much more organized for the front end folks of my project.

**Comment by kael-shipman** [comment]
Thanks for commenting! Good to know others find this desirable.

To the devs: I repeat my offer to implement this and PR it if you'll give me a push to start me in the right direction ;).

**Comment by effrafax** [comment]
Yes, would be great to have such a feature!

**Comment by SaiSrinivasM** [comment]
Yes, I am also looking for the same

**Comment by leandrofnunes** [comment]
It'd be awesome to have such feature available - as of now, I need to create composed tags which causes lots of duplicates.

**Comment by donaldduy-lb** [comment]
I would also love this feature!

**Comment by daveKoala** [comment]
I am also looking for the same thing. 
My use case is, I have an existing API with 2 versions, about to start on the third, consumers add a field in the header asking for specified version. I think sub or hierarchical tags would make life so much easier for developers and readers of the docs. As i need to keep all versions in a single doc

Happy to be told that header accept version can be documented in a different manner

**Comment by mairead** [comment]
We need this feature too. Our API serves several products but also we have utility endpoints, global endpoints and product specific endpoints. It would be really helpful to be able to add sub headings and also even a description to each sub heading so you could explain the purpose of the grouping

**Comment by arkanmgerges** [comment]
Yes it is a good feature

**Comment by jwpegram** [comment]
Any movement on this feature?

**Comment by mathis-m** [comment]
@kael-shipman you could probably just override the component https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/operation-tag.jsx using the plugin api. https://swagger.io/docs/open-source-tools/swagger-ui/customization/plugin-api/

then implement recursive rendering of the operation-tag within the render function of the component.

**Comment by kael-shipman** [comment]
@mathis-m thanks for the specific tip and documentation! Very helpful. I'm a bit swamped at work right now, but I'll look into maybe building a plug-in for this when I get a chance.

**Comment by mathis-m** [comment]
@kael-shipman for the plugin part I would use the wrapComponents plug point to conditional render either the hirachical operation tag component or the original component.

**Comment by kael-shipman** [comment]
Hi to everyone following this. Any thoughts on styling? This is what it looks like so far:

![Screenshot_2021-03-02_20-40-28](https://user-images.githubusercontent.com/3475586/109744235-8feec480-7b97-11eb-9adb-8c2a5d0381a8.png)

I tried left-justifying, too, but that made the hierarchy significantly less useful. Open to suggestions. If anyone's a whiz with this kind of stuff (css, react, etc.), feel free to PR my PR over at [kael-shipman/swagger-ui-plugins@hierarchical-tags](https://github.com/kael-shipman/swagger-ui-plugins/tree/hierarchical-tags)

**Comment by kael-shipman** [comment]
Also, if anyone's _really itchin'_ to get this going on their site, I just published the pre-release (v1.0.0-rc1) on github packages. You can get it by doing the following:

1. Add `@kael-shipman:registry=https://npm.pkg.github.com/kael-shipman` to your package-local `.npmrc` file.
2. Run `npm install --save @kael-shipman/swagger-ui-plugin-hierarchical-tags`
3. Follow instructions in README.md

I _believe_ that will work, but if it doesn't, I'd be happy to work through it with you.

**Comment by mathis-m** [comment]
@kael-shipman let's make this a PR against swagger-ui.
I can give you guiding, let's connect to get this going!

**Comment by dmrickey** [comment]
> Hi to everyone following this. Any thoughts on styling? This is what it looks like so far:
> 
> ![Screenshot_2021-03-02_20-40-28](https://user-images.githubusercontent.com/3475586/109744235-8feec480-7b97-11eb-9adb-8c2a5d0381a8.png)
> 
> I tried left-justifying, too, but that made the hierarchy significantly less useful. Open to suggestions. If anyone's a whiz with this kind of stuff (css, react, etc.), feel free to PR my PR over at [kael-shipman/swagger-ui-plugins@hierarchical-tags](https://github.com/kael-shipman/swagger-ui-plugins/tree/hierarchical-tags)

At least in the APIs I work with, this could still be very long. It'd be nice to have some kind of vertical gray line on the left to signify how deeply something is nested.

**Comment by mathis-m** [comment]
> At least in the APIs I work with, this could still be very long. It'd be nice to have some kind of vertical gray line on the left to signify how deeply something is nested.

How about:
![HierarchicalTags](https://user-images.githubusercontent.com/11584315/109988239-a451cf00-7d07-11eb-9c6d-7457ca9e264d.png)

**Comment by kael-shipman** [comment]
Love it! That looks great!

**Comment by kael-shipman** [comment]
@tim-lai, @mathis-m and I are working on a PR to `swagger-ui` to address this issue and we've run into some questions:

First, are you interested in this being part of `swagger-ui`? If not, we can stick to the plugin approach already mentioned above.

Second, if it seems acceptable for `swagger-ui`, what is your preferred architecture? I've implemented it as a backward-compatible core addition in [this branch](https://github.com/kael-shipman/swagger-ui/pull/3/files), but @mathis-m has suggested it may be more appropriate to build it as a core plugin, which he's started working on in [this branch](https://github.com/kael-shipman/swagger-ui/pull/2/files). I think either way is fine for us, but we'd like guidance before investing too much in one direction or the other.

**Comment by mathis-m** [comment]
In addition specification wise we are good to implement it.
> Tagged operations may be handled differently by tools and libraries. For example, Swagger UI uses tags to group the displayed operations.

**Comment by JAdamCain** [comment]
I desperately need this functionality now. I'm a novice but willing to try it . Is it available as a plug-in I can just drop in. Corporate frowns on unofficial versions of major software but plug-ins are fair game!

**Comment by kael-shipman** [comment]
Yes, this is available as a plugin in at least a rudimentary form. See instructions [up the page](https://github.com/swagger-api/swagger-ui/issues/5969#issuecomment-789388002).

I think the only thing that doesn't have is the nice styling that @mathis-m brought to it. @mathis-m , and chance you could backport your styling to the plugin version of this, while they're sitting on our PR over there at the main project?

**Comment by mathis-m** [comment]
@kael-shipman I don't think we are able to integrate the styling like shown in my comment other wise I will try to catch up on the PR and create needed tests for it hopeful we have this feature soon.

**Comment by JAdamCain** [comment]
Let me preface this by saying this is a dumb question but I'm trying to figure out how so many swagger sites have
"Show/Hide" "List Operations" and "Expand Operations" at each tag but mine doesn't. is there some simple attribute that I'm missing or what... I can't find the answer anywhere

**Comment by mathis-m** [comment]
> Let me preface this by saying this is a dumb question but I'm trying to figure out how so many swagger sites have
> "Show/Hide" "List Operations" and "Expand Operations" at each tag but mine doesn't. is there some simple attribute that I'm missing or what... I can't find the answer anywhere

Can you give us some context probably Screenshot and spec used?

**Comment by JAdamCain** [comment]
@mathis-m - thank you for offerign to help.
Here is an example of those hyperlink/buttons on a public website https://transport.tamu.edu/BusRoutesFeed/swagger/ui/index#/ Routes has multiple methods under it so it does a good job of illustrating what those 3 actions do.
and then my own site is at https://pricing.smc3.com/RateWarePlus/api/ i would like to have the api tag and others in the future use those same buttons. I have searched google like crazy and know I am probably missing some easy feature to turn or a plugin to add but I cannot find it. I am using OAS3. our tech stack includes Java 11, Tomcat 9, and Spring Boot 4.3(I think that's the right version number)

**Comment by mathis-m** [comment]
Actually the difference you are experiencing is due to major version difference of swagger-ui package used.

**Comment by JAdamCain** [comment]
@mathis-m - Thx I will get with developers on team about updating swagger-ui package Thanks!

**Comment by mathis-m** [comment]
Yes but the new version is the one that does not include these hyperlinks. http://petstore.swagger.io you see the latest version in action.

**Comment by JAdamCain** [comment]
@mathis-m So an older version has the better features then drat. While as the documnet guy I could convince peopel to go wiht newer I dont knwo that I can convince them to do a downgrade just to have a few cool buttons. Curious as to how old I have to go to get the buttons though

**Comment by mathis-m** [comment]
What functionality are you missing you can collapse the tag by clicking on it. You can configure swagger-ui to use different expansion levels on default. The only thing that is missing is that you can not expand all operations under tag. Which is what I think not a common workflow.

**Comment by JAdamCain** [comment]
Yeah you’re right just as our API expands the tag collapse would be nice.

From: Mahtis Michel ***@***.***>
Sent: Friday, April 9, 2021 5:01 PM
To: swagger-api/swagger-ui ***@***.***>
Cc: Adam Cain ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [swagger-api/swagger-ui] Support Hierarchical Tags (#5969)

This message originated outside SMC³. Please exercise caution opening attachments or following any instructions within.
________________________________
What functionality are you missing you can collapse the tag by clicking on it. You can configure swagger-ui to use different expansion levels on default. The only thing that is missing is that you can not expand all operations under tag. Which is what I think not a common workflow.

**Comment by JAdamCain** [comment]
@kael-shipman tried grabbing the plugin by doing:
npm install --save swagger-ui-plugin-hierarchical-tags
but i get  404 not found. any help would be great.

**Comment by kael-shipman** [comment]
Yes, as indicated in my answer [above](https://github.com/swagger-api/swagger-ui/issues/5969#issuecomment-789388002), the package is hosted on github, so you have to add my repo to your `.npmrc` file (I prefer project-local `.npmrc` files because then the configuration sticks with the repo and it becomes transparent to all other devs, but you can also put it in your global `~/.npmrc` file). Additionally, you have to prefix the package name with `@kael-shipman`. Here are the instructions, copied for convenience:

1. Add `@kael-shipman:registry=https://npm.pkg.github.com/kael-shipman` to your package-local `.npmrc` file.
2. Run `npm install --save @kael-shipman/swagger-ui-plugin-hierarchical-tags`
3. Follow instructions in [README.md](https://github.com/kael-shipman/swagger-ui-plugins/blob/hierarchical-tags-self-hosted/packages/hierarchical-tags/README.md)

(Note that, while this package will remain available ad infinitum, this should be considered a temporary solution until swagger gets around to reviewing our PR and integrating this feature into their core codebase.)

**Comment by JAdamCain** [comment]
totally glossed over those steps then had to figure out what tehy meant. then had to figure out how to actually login in npmjs... and generate a token on github but finally it all worked. now I'll do the redme.md part again

**Comment by kael-shipman** [comment]
Haha yes, this stuff gets awfully deep.... Let us know if you get stuck again. To be honest, I'm fairly new to swagger myself. When I publish docs, I usually use [redoc](https://www.npmjs.com/package/redoc-cli), although the reason I started this thread to begin with was because they didn't have hierarchical tags either (and still don't).

**Comment by JAdamCain** [comment]
I have it working. If you ever make the plugin have the additional bars that would make it look even better but the indented subsets are a nice add. Will go a long way to making my swagger page as user friendly as possible. Thank you both for your patience with me. Next on my list is css colors to brand it for my company... that should be interesting

**Comment by kael-shipman** [comment]
Yaaaaay! Glad you got it working!

**Comment by monirul017** [comment]
@kael-shipman I am trying to use it with nest js application is there any way to use it with nest js?

**Comment by kael-shipman** [comment]
@monirul017 mmm, I don't know. I've never really used nest, so wouldn't know how to integrate a plugin. Something makes me think it should be possible, though....

**Comment by ASchwad** [comment]
@kael-shipman @mathis-m Great work! Any updates if (or when) this feature is merged into swagger-ui?

**Comment by kael-shipman** [comment]
@ASchwad unfortunately I think we're a little stalled out here. The [original (draft) PR](https://github.com/swagger-api/swagger-ui/pull/7050) is now WAY behind the main branch and neither I nor @mathis-m seem to have much time or energy to push it through.

I would say your best bet would be to use it in plugin form.

@mathis-m, I know you commented above that it was not possible to integrate the styling that you devised into the plugin. Can you be more specific about the problem? I would be happy to see if I can at least get the plugin styled up nicely and then we can just let it be.

**Comment by Edweezu** [comment]
Hey @kael-shipman, Great plugin! Does your script approach (https://github.com/kael-shipman/swagger-ui-plugins/tree/hierarchical-tags/packages/hierarchical-tags) still work? I'm using the docs.html approach in order to load up the swagger-ui. Unable to require it in my client side app & apply to Swagger instance as I'm working w/ this in the backend

**Comment by kael-shipman** [comment]
@Edweezu sorry, it looks like I updated the docs on my self-hosted branch [here](https://github.com/kael-shipman/swagger-ui-plugins/tree/hierarchical-tags-self-hosted/packages/hierarchical-tags), but not on the branch that I've got a PR out for. Read through those docs and lemme know if you can't get it to work.

**Comment by Edweezu** [comment]
@kael-shipman I was trying to get it to work, but unsuccessful so far. Is this link still working for the script? https://unpkg.com/swagger-ui-plugin-hierarchical-tags

**Comment by Edweezu** [comment]
Gotcha gotcha, yea that would be super helpful as I could then easily use it as a script in my docs.html

**Comment by kael-shipman** [comment]
Hm. I have to say, I'm totally new to this area of of front-end development. I can't seem to get it to work. I published a version to npm at `v1.0.0-rc1`, but it doesn't seem to show up on unpkg. If you (or anyone else) know how to get us over this hump, I'd be more than happy to give you publish permissions on the npm package. Lemme know.

**Comment by Edweezu** [comment]
hmm it takes a while, but looks like it's on npm now (https://www.npmjs.com/package/swagger-ui-plugin-hierarchical-tags). Doesn't seem like it's building properly tho (https://unpkg.com/swagger-ui-plugin-hierarchical-tags@1.0.0-rc1). Was also running into the same issue when trying to require the package as stated in the README

**Comment by dmrickey** [comment]
So, uh, no options for anyone using .net's Swashbuckle?

**Comment by kael-shipman** [comment]
Alright folks, I believe I've just successfully published the package. I've also updated the readme at https://github.com/kael-shipman/swagger-ui-plugins/tree/hierarchical-tags/packages/hierarchical-tags, so instructions there should yield a successful deployment. Let me know if it doesn't work.

**Comment by mathis-m** [comment]
> So, uh, no options for anyone using .net's Swashbuckle?

@dmrickey Yea sure have a look at using your own [`index.html`](https://github.com/domaindrivendev/Swashbuckle.WebApi/tree/swagger_2.0#provide-your-own-index-file). Use it to register the plugin.

**Comment by Randerspl** [comment]
> Alright folks, I believe I've just successfully published the package. I've also updated the readme at https://github.com/kael-shipman/swagger-ui-plugins/tree/hierarchical-tags/packages/hierarchical-tags, so instructions there should yield a successful deployment. Let me know if it doesn't work.

Great tool @kael-shipman  and its working great for me, but i think i found a small bug and i don't know where to report it so i say it here.
For example i have 3 endpoints:
* endpoint 1: Tag1|SubTag1
* endpoint 2: Tag1|SubTag1
* endpoint 3: Tag1|SubTag1

Now for better grouping i changed endpoint 2 to have another sub tag for example to this: Tag1|SubTag1|SubSubTag1.
This is shown ok in swagger UI, but endpoints 1 and 2 just disappeared. It looks like adding new level just removed previous level entries (they still are in my swagger.json file).

**Comment by kael-shipman** [comment]
Aha, thanks, @Randerspl , for the bug report. I just got back from vacation - and also am recovering from covid :( :( - so I won't be able to look into this right away, but I'll try to fix it this weekend.

**Comment by kael-shipman** [comment]
Hmm.... @Randerspl I'm afraid I'm not able to replicate this. Can you post a swagger.json file that correctly replicates the problem? I just tried exactly what you said in your bug report and I got the expected results - see screenshots below.

The three endpoints as described originally:
![subtag1](https://user-images.githubusercontent.com/3475586/175446681-67302bac-7597-4dd4-8b8f-fdf925e5f196.png)

The endpoints after changing endpoint 2 to have a further level of hierarchy:
![subtag2](https://user-images.githubusercontent.com/3475586/175446760-3d00cce8-2862-4e0e-966d-d60696c5e0a0.png)

**Comment by Randerspl** [comment]
Hello, sorry for long time for response @kael-shipman.
I wrote similar but simpler http server that i used when i had problem and generated swagger json with replication of problem. 

On first attempt endpoints were shown properly in GUI (all tags were ending on "Third Tag"), but when i changed one endpoint to end on "Second Tag" then this endpoint disappeared from GUI.

Im using akka-http and swagger-akka-http for json file generation (that's why Function1RequestContextFutureRouteResult scheme exists) and then i just serve web-jar swagger-ui (version 4.10.3) in server and use generated swagger.json on page.

Im using tags with spaces, maybe this is a problem?

swagger.json generated by my server.
```
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "",
    "description" : "",
    "termsOfService" : "",
    "version" : ""
  },
  "servers" : [ {
    "url" : "http://127.0.0.1:9000"
  } ],
  "security" : [ ],
  "paths" : {
    "/http/test1" : {
      "get" : {
        "tags" : [ "First Tag|Second Tag|Third Tag" ],
        "operationId" : "route1",
        "responses" : {
          "default" : {
            "description" : "default response",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Function1RequestContextFutureRouteResult"
                }
              }
            }
          }
        }
      }
    },
    "/http/test2" : {
      "get" : {
        "tags" : [ "First Tag|Second Tag|Third Tag" ],
        "operationId" : "route2",
        "responses" : {
          "default" : {
            "description" : "default response",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Function1RequestContextFutureRouteResult"
                }
              }
            }
          }
        }
      }
    },
    "/http/test3" : {
      "get" : {
        "tags" : [ "First Tag|Second Tag" ],
        "operationId" : "route3",
        "responses" : {
          "default" : {
            "description" : "default response",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Function1RequestContextFutureRouteResult"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Function1RequestContextFutureRouteResult" : {
        "type" : "object"
      }
    }
  }
}
```
When test3 endpoint ends on "Second Tag"
![image](https://user-images.githubusercontent.com/9450923/176955716-0e09f1c0-6915-47f0-90f5-e9eb25c3cd9c.png)
When test3 endpoint ends on "Third Tag"
![image](https://user-images.githubusercontent.com/9450923/176955819-4088b1fb-1229-40fa-992f-a5460c17771f.png)

When test1 and test2 ends on "Second Tag" and test3 ends on "Third Tag" then UI is OK.
![image](https://user-images.githubusercontent.com/9450923/176956967-af5bf189-2c12-4d2f-8fbb-910428262b8b.png)

**Comment by mathis-m** [comment]
@kael-shipman @Randerspl Hi guys! I found some minutes for a minor investigation. I just looked at the code and with the knowledge of the swagger ui system from back then I think this because of this lines of code: https://github.com/kael-shipman/swagger-ui-plugins/blob/hierarchical-tags/packages/hierarchical-tags/src/HierarchicalOperations.jsx#L79-L98

The `taggedOperations` selector of swagger-ui returns a map to a datastructure containing information about the tag itself and about its operations. So operations on the same level will work with the current plugin logic. But in case there are hirachical tags that end on different levels there is a issue. 
What the plugin tries to do is to create a nested map by splitting the tags at a delimiter. In case that a nested tag at any level already exists, like in your example tag1  and tag2. And then a tag follows that ends at at a already tracked tag level like first level or second level, nothing will be done. Instead the logic should combine the operations on this level with the ones of the current tag. And probably also add the tag information if available.
```js
const parts = // split tag
for(const tag of parts) 
{
  // old logic if
  else if(tag === parts[parts.length - 1])
    //merge operations and tag info
  //old logic
} 
```

I will try to provide PR when I get home later today.

Best Regards
Mathis

Sent from a mobile phone – please excuse the brevity of the comment.

**Comment by Randerspl** [comment]
Hello @kael-shipman, i asked a question in [PR#1](https://github.com/kael-shipman/swagger-ui-plugins/pull/1#issuecomment-1177328293) about webjar release some time ago. It is possible to get webjar release or my only solution is to change to npm?

**Comment by kael-shipman** [comment]
Sorry, @Randerspl , just replied over there!

**Comment by peterskudder** [comment]
@kael-shipman Any pointers on how to add this plugin if a Swagger controller has been implemented please?

**Comment by kael-shipman** [comment]
Unfortunately I have no idea :(. I haven't actually done all that much with swagger.

**Comment by chesiren** [comment]
Hello @kael-shipman , i have a problem with your plugin and i would need your help to fix it:
When multiple subtags are named the same but are in different nested tags, clicking one will show/hide all the others ones as well.
How can i make it so they don't interact with each other without having to change their name?
You can see the problem in the petstore example included in your plugin package by clicking the view,create or delete tags
(or video bellow to show the problem)
https://user-images.githubusercontent.com/44122832/213244155-1886039c-ae14-4b76-9a0e-ceaf27147f46.mp4

**Comment by cocodee** [comment]
Are you still working on this?

**Comment by nop1984** [comment]
Looking for that too

**Comment by kael-shipman** [comment]
> Hello @kael-shipman , i have a problem with your plugin and i would need your help to fix it: When multiple subtags are named the same but are in different nested tags, clicking one will show/hide all the others ones as well. How can i make it so they don't interact with each other without having to change their name? You can see the problem in the petstore example included in your plugin package by clicking the view,create or delete tags (or video bellow to show the problem) https://user-images.githubusercontent.com/44122832/213244155-1886039c-ae14-4b76-9a0e-ceaf27147f46.mp4

@chesiren sorry I missed this! I don't have time to mess with this right now, but I'm putting it on my to-do list and I'll see if I can get to it at some point. It's probably not a hugely difficult thing to fix. Will keep you posted.

**Comment by ChadBakkt** [comment]
we need this.

**Comment by Davidos533** [comment]
Yes we need this!

**Comment by geanruca** [comment]
We need this :D can I create a PR?

**Comment by mgrazianoc** [comment]
please merge this, we need it

**Comment by fabhed** [comment]
This would be a great feature to have merged!

**Comment by kael-shipman** [comment]
From the description above:

> **I've implemented and published a package for this. Instructions for use are [here](https://github.com/kael-shipman/swagger-ui-plugins/blob/hierarchical-tags-self-hosted/packages/hierarchical-tags/README.md).** ~~There is also a PR out for this ([here](https://github.com/swagger-api/swagger-ui/pull/7050)), but it is long stale and I doubt that Swagger will ever take interest in it.~~ (The PR has now been closed without merging.) For now, your best bet is to use my published package, which works well as an ES module include in a webpack scenario OR as a global module via unpkg.

**Comment by kael-shipman** [comment]
**Since the Swagger team decided ([here](https://github.com/swagger-api/swagger-ui/pull/7050)) that this won't be a core feature, and since there is a published plugin for it [here](https://github.com/kael-shipman/swagger-ui-plugins/blob/hierarchical-tags-self-hosted/packages/hierarchical-tags/README.md), I'm closing this issue as "completed".**

**Comment by chrisnore94** [comment]
A important question:

Why the plugin could not be become in a npm package (uploaded to the npm repos)? Do not you think it could be easier to install it by a simple "npm install" command and not having the need to use a .npmrc file in any project?

Thanks for advance. :)

**Comment by kael-shipman** [comment]
That's a good point, and actually it's a documentation problem. The package has been hosted on npm for a while now and I just forgot to update the docs. I've now updated the docs (see the same link above), so you should be good to go.

**Comment by chrisnore94** [comment]
Oh! Great! I installed it, but, when I import and use this package, the following error is displaying:

TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at [project-path]/node_modules/swagger-ui-plugin-hierarchical-tags/build/index.js:6:14895
    at Module.<anonymous> ([project-path]/node_modules/swagger-ui-plugin-hierarchical-tags/build/index.js:6:15172)
    at Module.<anonymous> ([project-path]/node_modules/swagger-ui-plugin-hierarchical-tags/build/index.js:6:15300)
    at r ([project-path]/node_modules/swagger-ui-plugin-hierarchical-tags/build/index.js:1:110)
    at [project-path]/node_modules/swagger-ui-plugin-hierarchical-tags/build/index.js:1:902
    at Object.<anonymous> ([project-path]/node_modules/swagger-ui-plugin-hierarchical-tags/build/index.js:1:912)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)

How can I solve it? Thanks for advance. :)

**Comment by chrisnore94** [comment]
Oh! Great thing! Another question: I know the plugin can be used on a client-side project, but, is it possible to use this plugin on any express project? 

Example to use:

const express = require("express");
const app = express();

const HierarchicalTagsPlugin = require('swagger-ui-plugin-hierarchical-tags');
const swaggerUi = require('swagger-ui-express');
const swaggerDocument = require('./swagger-output.json');

const swaggerOptions = {
  swaggerOptions: {
    plugins: [HierarchicalTagsPlugin]
  }
} 

// Swagger Documentation
app.use('/api/v1/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, swaggerOptions));

Could it be possible with your plugin? if not, are you planning to develop the plugin to be used with express.

Thanks in advance. :)

**Comment by mathis-m** [comment]
> That's a good point, and actually it's a documentation problem. The package has been hosted on npm for a while now and I just forgot to update the docs. I've now updated the docs (see the same link above), so you should be good to go.

@char0n would there be a option to create like an third party plugins page within the swagger documentation?

That would contribute to the overall position on market, cause it shows potential users or devs what can be done with the base product.

I know that #5027 is there, but it is closed. Why not use the traffic that is there like on this PR, and take action, create a global entry point for swagger third party plugins.

**Comment by kael-shipman** [comment]
Love this idea :point_up: :point_up:

**Comment by akhateeb22** [comment]
Package not found in NPM!
Any idea ?!

**Comment by kael-shipman** [comment]
Mm.... I just checked and [here](https://www.npmjs.com/package/swagger-ui-plugin-hierarchical-tags) it is?

**Comment by akhateeb22** [comment]
Does it work on server side (nestjs) ?!

**Comment by kael-shipman** [comment]
@akhateeb22 not sure exactly what use-case you're referring to. You can install it just like any other npm package, but of course it's a front-end package, so the code needs to make it to your front-end somehow. NestJS is a back-end microservice framework, so not sure what you're going for here.

**Comment by kforkaran** [comment]
@kael-shipman is there something similar for Redoc? Support for Hierarchical Tags?

**Comment by gulgulia17** [comment]
I started looking for something to add a tree view and found it. It's just amazing work!

**Comment by 1nVitr0** [comment]
> Does it work on server side (nestjs) ?!

@akhateeb22 I presume you mean, how to include it in the Swagger module for nestjs? I have managed to include it, though it is quite "hacky":

```ts
// Include this in your bootstrap function in main.ts (or wherever you setup your nest app

const swaggerConfig = new DocumentBuilder()
    .setTitle('Hierarchical Tags')
    .build();
const document = SwaggerModule.createDocument(app, swaggerConfig);
SwaggerModule.setup('api', app, document, {
    swaggerOptions: {
        plugins: [
            (...args: any[]) => (window as any).HierarchicalTagsPlugin(...args),
           // This is added by nestjs by default and would be overridden if not included
            (...args: any[]) => (window as any).SwaggerUIBundle.plugins.DownloadUrl(...args),
        ],
        hierarchicalTagSeparator: '/', // This must be a string, as RegExp will not survive being json encoded
    },
    customJs: ['https://unpkg.com/swagger-ui-plugin-hierarchical-tags'],
});
```

The `SwaggerUIBundle.plugins.DownloadUrl` plugin is sourced from the js template of the `@nestjs/swagger` [init template](https://github.com/nestjs/swagger/blob/b29dc1da9656be043cea368870d1d3f04a5de25a/lib/swagger-ui/constants.ts#L88C1-L132C3). I haven't checked what it does, but I'm sure it's used for something.

The encapsulation of the plugins into functions is necessary, because this get's used client-side and functions are the only properties that are passed on as-is (see [@nestjs/swagger/swagger-ui/helpers.ts](https://github.com/nestjs/swagger/blob/master/lib/swagger-ui/helpers.ts)).

Also `hierarchicalTagSeparator` **MUST** be a string, as RegExp cannot be JSON encoded. This does limit the separator to a single character, but that didn't bother me.

It's definitely not an ideal solution as it plays with the internal functioning of `@nestjs/swagger` and may break at any time.

**Comment by cse210001015** [comment]
> > Does it work on server side (nestjs) ?!
> 
> @akhateeb22 I presume you mean, how to include it in the Swagger module for nestjs? I have managed to include it, though it is quite "hacky":
> 
> ```ts
> // Include this in your bootstrap function in main.ts (or wherever you setup your nest app)
> 
> const swaggerConfig = new DocumentBuilder()
>     .setTitle('Hierarchical Tags')
>     .build();
> const document = SwaggerModule.createDocument(app, swaggerConfig);
> SwaggerModule.setup('api', app, document, {
>     swaggerOptions: {
>         plugins: [
>             (...args: any[]) => (window as any).HierarchicalTagsPlugin(...args),
>            // This is added by nestjs by default and would be overridden if not included
>             (...args: any[]) => (window as any).SwaggerUIBundle.plugins.DownloadUrl(...args),
>         ],
>         hierarchicalTagSeparator: '/', // This must be a string, as RegExp will not survive being json encoded
>     },
>     customJs: ['https://unpkg.com/swagger-ui-plugin-hierarchical-tags'],
> });
> ```
> 
> The `SwaggerUIBundle.plugins.DownloadUrl` plugin is sourced from the js template of the `@nestjs/swagger` [init template](https://github.com/nestjs/swagger/blob/b29dc1da9656be043cea368870d1d3f04a5de25a/lib/swagger-ui/constants.ts#L88C1-L132C3). I haven't checked what it does, but I'm sure it's used for something.
> 
> The encapsulation of the plugins into functions is necessary, because this get's used client-side and functions are the only properties that are passed on as-is (see [@nestjs/swagger/swagger-ui/helpers.ts](https://github.com/nestjs/swagger/blob/master/lib/swagger-ui/helpers.ts)).
> 
> Also `hierarchicalTagSeparator` **MUST** be a string, as RegExp cannot be JSON encoded. This does limit the separator to a single character, but that didn't bother me.
> 
> It's definitely not an ideal solution as it plays with the internal functioning of `@nestjs/swagger` and may break at any time.

how did you get the `window` variable?

**Comment by 1nVitr0** [comment]
> how did you get the `window` variable?


@cse210001015 Yeah, that's the hacky bit. Unless `@nestjs/swagger`has changed their code or you're using an older version, functions inside the plugin section are compiled as-is into the client code for the swagger route. That's why I used `window as any`, the `window`global is non-existing in the context of your `main.ts` file, but it will be on the client the swagger docs are served to.


> > The encapsulation of the plugins into functions is necessary, because this get's used client-side and functions are the only properties that are passed on as-is (see [@nestjs/swagger/swagger-ui/helpers.ts](https://github.com/nestjs/swagger/blob/master/lib/swagger-ui/helpers.ts)).


I haven't tried this with SSR, but I'm fairly sure it should still be executed client-side.

**Comment by marlenekoh** [comment]
seems like OAS 3.2 may support this - https://github.com/OAI/OpenAPI-Specification/pull/4288
