### ISSUE TITLE
Zeroth Enum value gets picked up as Data Type for the fields in Response (Example Value) and Request payload

### ISSUE THREAD

**Issue by vinaysharma77** [swagger-api/swagger-ui#5974]
For all the fields that are associated to an enum, there's an array of enum values associated to those. These fields when rendered in either the Example Value in the UI or the POST/PATCH/PUT request payload, the zeroth value of the enum array gets picked up instead of the data type of the field. I would like to have the datype show up for those in my Example Value  or the request payloads for those fields. 
![image](https://user-images.githubusercontent.com/3733770/80131866-df706700-8568-11ea-9968-6f6fa9d6661c.png)

![image](https://user-images.githubusercontent.com/3733770/80132058-21011200-8569-11ea-8eec-9da7c96919e5.png)

![image](https://user-images.githubusercontent.com/3733770/80132740-20b54680-856a-11ea-8740-4a75149c0088.png)

![image](https://user-images.githubusercontent.com/3733770/80132858-50644e80-856a-11ea-88f5-4d457439616d.png)

In our code where we're building our custom swagger objects, we're assigning the request and response models when building Parameter object. Why is the UI not picking up the respective data type if there're values in enum collection? Any help/advice in this regard will be greatly appreciated!

**Comment by hkosova** [comment]
The data types are displayed on the "Model" tab.

The "Example Value" tab, as the name suggests, displays an _example_ value for the given schema; in case of enums - one of the enum values. You can customize the auto-generated examples by providing your own `example` values for objects and properties.

**Comment by vinaysharma77** [comment]
This helps. Thanks.
