### ISSUE TITLE
'duplicated mapping key' error occurred, if set same paths with different method (OAS3)

### ISSUE THREAD

**Issue by qzrt** [swagger-api/swagger-ui#5984]
## 'duplicated mapping key' error occurred, if set same paths with different method (OAS3)

1. Docker Run swagger-ui with yaml file below
2. Then See errors 'duplicated mapping key'

### Q&A
 - OS: OSX High Sierra
 - Browser: Safari
 - Version: 13.1
 - Method of installation: docker run
 - Swagger-UI version: 3.18.3
 - Swagger/OpenAPI version: OpenAPI 3.0

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  description: bug test
  version: "1.0"
  title: sample
tags:
  - name: user
    description: user
paths:
  /user:
    post:
      tags:
        - user
      summary: User Register
      description: ""
      operationId: UserPost
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        "400":
          description: エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                    message:
                        type: string
  /user:
    delete:
      tags:
        - user
      summary: User Deletion
      description: ""
      operationId: UserDelete
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        "400":
          description: エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                    message:
                        type: string
```

**Comment by hkosova** [comment]
This is not a valid API definition.

Each path must be listed only once, and all HTTP methods applicable to that path must be listed under that path, as follows:

```yaml
paths:
  /user:
    post:
      ...
    delete:
       ...
```

**Comment by vegassw** [comment]
Thanks a lot

**Comment by gi-hu-se** [comment]
<img width="564" alt="스크린샷 2021-04-28 오전 11 01 07" src="https://user-images.githubusercontent.com/83322872/116335034-2397e680-a811-11eb-8719-e74379369469.png">

paths: 
  /epg-stbservice: 
    get:
     tags: 
     - WEPG
     summary: IF-WEPG-301 
     parameters: 
      - name: m 
        in: query 
        description: 메서드 명
        required: false 
        schema: 
         type: string
    get: 
     tags: 
     - WEPG
     summary: IF-WEPG-303 #요약개념 -> 설명
     parameters: 

There is a problem with duplicate mapping keys Why?

**Comment by hkosova** [comment]
@gi-hu-se You can't have two `get` inside a path (or, in general, multiple instances of the same HTTP method). If you are designing a new API, split this path into two different paths, each with its own `get`.

Here's a related feature request in the OpenAPI Specification repository:
https://github.com/OAI/OpenAPI-Specification/issues/182

**Comment by 8ivek** [comment]
> This is not a valid API definition.
> 
> Each path must be listed only once, and all HTTP methods applicable to that path must be listed under that path, as follows:
> 
> ```yaml
> paths:
>   /user:
>     post:
>       ...
>     delete:
>        ...
> ```

Thanks for this

**Comment by Jaguar-cloud** [comment]
Please, I need assistance. I don't know why I keep getting this error msg: 

"Errors
Parser error 
duplicated mapping key" 


 /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
        
    get:
      tags:
      - jobs
      summary: Get Single Job
      operationId: GetSingleJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    patch:
      tags:
      - jobs
      summary: Update Job
      operationId: UpdateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
            example:
              company: youtube
              position: full stack developer
              status: interview
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    delete:
      tags:
      - jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []

**Comment by TastyMinion** [comment]
Can someone help me with this Problem?! I got this problem from Aternos! Its the only one, which is showing an Error!
![image](https://user-images.githubusercontent.com/84205028/154836833-fb6be1af-5810-4202-a443-4d8d03360233.png)
