### ISSUE TITLE
Swagger Editor shows a bug but in the schema documentation name in securityschemes is allowed

### ISSUE THREAD

**Issue by benzanderuni** [swagger-api/swagger-ui#5985]
Swagger Editor shows a bug but in the schema documentation name in securityschemes is allowed. Generating clients is also working.

![swagger editor bug](https://user-images.githubusercontent.com/64593744/80959101-6691ca80-8e06-11ea-91a1-d462275990ad.png)

**Comment by hkosova** [comment]
OAuth 2 security schemes do not have the `name` property. They may have a `description` though.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#securitySchemeObject

`name` is only used in security schemes with `type: apiKey`.
