### ISSUE TITLE
Add deep linking for models

### ISSUE THREAD

**Issue by mdhtr** [swagger-api/swagger-ui#5986]
### Content & configuration
When Model definitions are present.
### Is your feature request related to a problem?
I would like to directly link to a Model on the Swagger UI, similarly to how I can link to an Endpoint, like this: `https://petstore.swagger.io/#/definitions/User`
### Describe the solution you'd like
Extend existing solution for deep linking to include models, or introduce a separate option for models only 
### Describe alternatives you've considered
I couldn't think of any alternatives
### Additional context
If someone would like to implement HATEOAS link relations, they would need to provide a uri to the specification of the object. I would like to use the Model object in Swagger UI for this purpose, with a deep link.

**Comment by arucard21** [comment]
This seems to be a duplicate of #1369.

**Comment by mdhtr** [comment]
> This seems to be a duplicate of #1369.

True. For some reason I didn't find it when I searched the issues.
