### ISSUE TITLE
swagger-ui-react: Setting defaultModelExpandDepth to -1 has no effect

### ISSUE THREAD

**Issue by cdscse** [swagger-api/swagger-ui#5987]
**Version:** 
swagger-ui-react@3.25.0

**Usage:**
`<SwaggerUI url={'/swagger'} defaultModelExpandDepth={-1} docExpansion={'none'} />`

**Expected Behavior:** 
Setting `defaultModelExpandDepth: -1` should cause the models to be completely hidden

**Observed Behavior:** 
The models section is still visible

**Comment by emulienfou** [comment]
The doc seems to be wrong, you should use `defaultModelsExpandDepth={-1}` (**Models**) parameter instead of `defaultModelExpandDepth={-1}` (**Model**)

**Comment by tim-lai** [comment]
@emulienfou is correct. One should use `defaultModelsExpandDepth={-1}`, note the plurality of Model**s**.

The `defaultModelExpandDepth`, without the plurality, is targeting a model example for an operation, which is a different component.

Closing ticket and updating the labels as "not-a-bug"
