### ISSUE TITLE
Warning: Unknown prop `initialValue` on <input> tag. Remove this prop from the element. 

### ISSUE THREAD

**Issue by maxisam** [swagger-api/swagger-ui#5989]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version:  80.0.3987.149
 - Method of installation: both swagger-ui 
 - Swagger-UI version: 3.25.1
 - Swagger/OpenAPI version: v2 ( https://petstore.swagger.io/v2/swagger.json)

### Content & configuration

Swagger-UI configuration options:
```js
SwaggerUI({
			url: 'https://petstore.swagger.io/v2/swagger.json',
			domNode: this.container.nativeElement,
			deepLinking: true,
			presets: [SwaggerUI.presets.apis, SwaggerUI.SwaggerUIStandalonePreset]
});
```

### Describe the bug you're encountering
warning.js:33 Warning: Unknown prop `initialValue` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop 

**However, it works with swagger-ui-dist **

### To reproduce...
https://github.com/agoncal/swagger-ui-angular6

- yarn && ng serve 
- click Authorize

You can find this error in console

**Comment by chanmj96** [comment]
Hello @maxisam, the linked PR should fix the issue that is reported. Let me know if you have any questions.
