### ISSUE TITLE
Is it possible to add swaggerui.setup function to accept the array of "swaggerDoc"?

### ISSUE THREAD

**Issue by brt-srini-rama** [swagger-api/swagger-ui#5992]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
 # your YAML here
 ```

 Swagger-UI configuration options:
 ```js
 SwaggerUI({
   // your config options here
 })
 ```

 ```
 ?yourQueryStringConfig
 ```

### Is your feature request related to a problem?
  Yes, Currently I think either Design-First or Code-First option is supported, not both at the same time, it would be nice if the swaggerDoc argument is allowed to pass as an array, so that the existing project documentation using swagger-jdoc and also the enhancement of the project with Design-First approach is achieved by passing the static imports of .ts definition files".

### Describe the solution you'd like
Let the swaggerUI.setup function to receive an array of swaggerDoc argument, and internally parse and merge the tags from both of these sources.

### Describe alternatives you've considered
Could not get the alternative for this.

### Additional context
Right now no other options to support both the dynamic document generation and static API definition.

**Comment by hkosova** [comment]
It looks like your question is about **swagger-ui-express**. It's a different project (not ours), its repository is here:
https://github.com/scottie1984/swagger-ui-express
