### ISSUE TITLE
@Boolean type in apimodelproperty cannot be displayed

### ISSUE THREAD

**Issue by lzhpo** [swagger-api/swagger-ui#5995]
@The 'Boolean' type in apimodelproperty cannot be displayed
1. I annotated information in isnewrecord, which is of boolean type and cannot display my annotated information. I've tested that everything works except for the boolean type.
2. I set hidden = true. It will not be hidden. Other types can be hidden.
Is this the cause of my configuration or a bug? thank you!

![image](https://user-images.githubusercontent.com/42663571/81493713-592c8280-92d5-11ea-8821-862a53813f70.png)

![image](https://user-images.githubusercontent.com/42663571/81493708-4914a300-92d5-11ea-8997-690dc2d59db0.png)

**Comment by webron** [comment]
This is most likely due to the `@JsonIgnore`, however, this has nothing to do with Swagger UI. If it's not rendered in the UI, it's not provided to the UI. If you think it _is_ provided to the UI, please file a new ticket providing *all* the requested details in the issue template.
