### ISSUE TITLE
Is the requestInterceptor parameter supported in swagger-config.yaml?

### ISSUE THREAD

**Issue by jschaefer77** [swagger-api/swagger-ui#6023]
Hi,
I would like to set a requestInterceptor in the swagger-config.yaml.

`---
url: "https://petstore.swagger.io/v2/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://validator.swagger.io/validator"
requestInterceptor: ...`

Does anybody know if this is supported at all?
If so, it would be really great the get a simple working example.

thx a lot
Joerg

**Comment by jschaefer77** [comment]
Has anyone used the parameter requestInterceptor in swagger-config.yaml successfully before and can send me an example. I appreciate any hint.

**Comment by apiglue** [comment]
im also interested in this. 

Im my tests, SwaggerUIBundle JS component doesnt not render the requestInterceptor coming from the swagger-config.yaml.

**Comment by tim-lai** [comment]
@jschaefer77 The `requestInterceptor` MUST be a function, so no, you can't define it in a swagger-config.yaml
