### ISSUE TITLE
How to use fetch in custom examples?

### ISSUE THREAD

**Issue by verilog15** [swagger-api/swagger-ui#6027]
### Q&A (please complete the following information)
 - Swagger-UI version: 3.0.1
 - Swagger/OpenAPI version: OpenAPI 3.0 

### How can we help?
I'm trying to understand how custom examples work. I have a route: ` /collection/type/{typeName}`
which returns all of the values per the `typeName` (JSON). I would like to add an example in the `200` status or in the body so the input is `user` and the output is all of the users (JSON's Array). I didn't see an option of "input" in the docs. Also, I don't want it to be custom (written by me), I want it to fetch the data by itself without adding a `$ref`. For example if the input is `user` then it will do the GET request and get the data. Is it something that is possible using Swagger?

**Comment by hkosova** [comment]
OAS3 `examples` keyword can use [`externalValue`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#user-content-exampleexternalvalue) to specify an URL containing an external example value. But Swagger UI does not support `externalValue` yet, this is tracked in #5433.

```yaml
openapi: 3.0.3
info:
  title: externalValue example
  version: 1.0.0
servers:
  - url: https://myserver.com
paths:
  /collection/type/{typeName}:
    get:
      parameters:
        - in: path
          name: typeName
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {}
              examples:
                userTypes:
                  description: The example value should be fetched from this URL
                  externalValue: https://myserver.com/collection/type/user
```

**Comment by verilog15** [comment]
Thank you @hkosova. Is it known when `externalValue` will be supported in Swagger UI?

**Comment by hkosova** [comment]
@verilog15 There's no ETA for this yet. Please follow #5433 for status updates.
