### ISSUE TITLE
Why is this not just a standalone .html file?

### ISSUE THREAD

**Issue by mcandre** [swagger-api/swagger-ui#6029]
I don't understand why deploying Swagger UI has to be this complicated. The one thing to configure is the HTTP(S) route to the Swagger spec document, which could be done as follows:

Attempt to load a `/public/swagger.js` asset which defines a standard variable `swaggerSpecRoute`. When undefined, swagger-ui defaults to `/public/swagger.yaml`.

This allows for customizing the exact path to the spec, without having to do silly NPM installs in non-Node.js projects.

**Comment by webron** [comment]
That's exactly the `/dist` directory of the project.
