### ISSUE TITLE
How to use latest swagger version in Asp.Net MVC and .Net framework 4.6.1 

### ISSUE THREAD

**Issue by Vikasnarwade55** [swagger-api/swagger-ui#6032]
Hi guys,

I am using old swagger version which using old jquery version  in .Net framework 4.5.2 / 4.6.2  but due to security issue I have to update jquery version  of swagger please help me on this

**Comment by webron** [comment]
See https://github.com/swagger-api/swagger-ui/issues/5329#issuecomment-633596660.
