### ISSUE TITLE
Description for field with complex data type will be ignored

### ISSUE THREAD

**Issue by xinfli** [swagger-api/swagger-ui#6046]
### Q&A
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.61
 - Method of installation: Source code
 - Swagger-UI version: 3.25.5
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
I have api definition below:
```json
    "NewRequestDto": {
      "allOf": [
        {
          "type": "object",
          "description": "Creates a new request",
          "required": [
            // ...
            "Period",
            // ...
          ],
          "properties": {
            // ...
            "Period": {
              "description": "Datetime period in specified timezone, should not earlier than today",
              "$ref": "#/definitions/DateTimePeriodDto"
            },
            // ...
          }
        }
      ]
    },
    // ...
    "DateTimePeriodDto": {
      "type": "object",
      "properties": {
        "StartTime": {
          "type": "string",
          "description": "Start time of period",
          "format": "date-time"
        },
        "EndTime": {
          "type": "string",
          "description": "End time of period",
          "format": "date-time"
        }
      }
    },
    // ...
```

The description for field "Period" is ignored in SwaggerUI, only data type "DateTimePeriodDto" displayed.

### Expected behavior
Should show description "Datetime period in specified timezone, should not earlier than today" for the field "Period"

### Screenshots
![image](https://user-images.githubusercontent.com/1798198/83267663-d6f0f900-a1c4-11ea-9b3d-1dba194d4938.png)

### Additional context or thoughts
Nothing

**Comment by hkosova** [comment]
In OpenAPI 2.0 and 3.0, any sibling properties alongside `$ref` [are ignored](https://stackoverflow.com/a/45530219/113116) - this is how `$ref` works. If you paste your definition into https://editor.swagger.io it will flag the keywords alongside $refs and suggest workarounds (look for the ⚠️ warning icons in the gutter).

The next version of the spec - OpenAPI 3.1 - will support `$ref` with a sibling `description` property.
