### ISSUE TITLE
[develop 2.0] Display URL in Extenal Documentation Object

### ISSUE THREAD

**Issue by edmondchui** [swagger-api/swagger-ui#608]
I'm not sure if this is an enhancement or a bug.

In my YAML file, under definitions -> object_name -> properties -> property_name, I use URL to define an external documentation object. I see the external URL link in the preview section of the swagger-editor. When I download the json from the editor, I see the link in the json file as well.

However, when I use swagger-ui to see the json, I don't see the URL in both the Model and Model Schema section. It would be great if we can see and click on the external URL in hte documentation object.

Thanks,
Edmond

**Comment by fehguy** [comment]
I'm moving this to M2 so we can spend more time on the design

**Comment by mohsen1** [comment]
#1000 will fix this. If SwaggerJS provide externalDocs of course

**Comment by mohsen1** [comment]
![screen shot 2015-03-26 at 12 38 08 pm](https://cloud.githubusercontent.com/assets/543633/6855399/04227040-d3b5-11e4-81a8-7e27072ad62d.png)
