### ISSUE TITLE
@ApiModel  注解相同value，出现奇怪的现象

### ISSUE THREAD

**Issue by tangwangcheng** [swagger-api/swagger-ui#6080]
@ApiModel(value = "相同")
class ModelA{
    String fieldA;
    String fieldB;
     省略get/set.....
}
@ApiModel(value = "相同")
class ModelB{
    String fieldC;
    String fieldD;
     省略get/set.....
}

ModelController {
    void testA( @RequestBody ModelA request){
}
 void testB( @RequestBody ModelB request){
}
}
发现奇怪的现象，@ApiModel 注解的value 相同时，方法testA 和 testB 在swagger-ui 页面中，
requestbody 的 Data Type 中 model 样例出现错误显示，方法 testB 的requestbody 的 Data Type 中 model 样例应该显示的是     
{
    “fieldC“：”string”,
    “fieldD“：”string”
}
然而却显示 ModelA的
{
    “fieldA“：”string”,
    “fieldB“：”string”
}

版本
<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.6.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.6.1</version>
            <scope>compile</scope>
        </dependency>

请问是否处理避免这个奇怪的现象呢？

**Comment by hkosova** [comment]
Please ask Springfox questions in their own repository:
https://github.com/springfox/springfox/issues
