### ISSUE TITLE
FileUpload changes in generated curl request when adding a header using requestInterceptor

### ISSUE THREAD

**Issue by mike2184** [swagger-api/swagger-ui#6082]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)
 - Method of installation: dist assets
 - Swagger-UI version: 3.10.0 (I've tried several versions and it happens with them all)
 - Swagger/OpenAPI version: Swagger 2.0 (Happens with both Swagger 2.0 and OpenAPI 3.0)

### Content & configuration
I created an example project on github to demonstrate the issue. https://github.com/mike2184/swagger-ui-test
Swagger UI hosted on GItHub pages here: https://mike2184.github.io/swagger-ui-test/#/pet/uploadFile

Example Swagger/OpenAPI definition:
I'm using https://petstore.swagger.io/v2/swagger.json in the example I created to show this issue.

Swagger-UI configuration options:
```js
const ui = SwaggerUIBundle({
				url : "./swagger.yaml",
				dom_id : '#swagger-ui',
				deepLinking : true,
				presets : [ SwaggerUIBundle.presets.apis,
						SwaggerUIStandalonePreset ],
				plugins : [ SwaggerUIBundle.plugins.DownloadUrl ],
				layout : "StandaloneLayout",
				requestInterceptor : function(req) {
					// Having the following line of code that adds a header causes the generated curl request to change from
					// -F "file=@cake.jpg;type=image/jpeg" to -d {"file":{}}
					req.headers['x-test-header'] = 'test value'; 
					return req;
				}
			})
```

### Describe the bug you're encountering
If I make any changes to the headers using the requestInterceptor it changes the file upload in the generated curl request from -F "file=@cake.jpg;type=image/jpeg" to -d {"file":{}}

### To reproduce...

1. Go to https://mike2184.github.io/swagger-ui-test/#/pet/uploadFile
2. Click Try it out for /pet/{petId}/uploadImage API
3. Set petId to 1
4. Click choose file and select any image file
5. Click execute
6. Notice: generated curl request has -d {"file":{}} instead of -F "file=@cake.jpg;type=image/jpeg"

### Expected behavior
Generated curl request should be -F "file=@cake.jpg;type=image/jpeg"

### Screenshots
![Screen Shot 2020-06-04 at 8 50 24 AM](https://user-images.githubusercontent.com/12974007/83773870-4e4ddf00-a642-11ea-9041-544d05444fbc.png)

**Comment by tim-lai** [comment]
@mike2184 Please update SwaggerUI to latest. In particular, [3.26.0](https://github.com/swagger-api/swagger-js/releases/tag/v3.10.6) resolved issues with curl strings.

**Comment by mike2184** [comment]
@tim-lai - I updated my test git repo to use swagger-ui 3.26.2 and I am still seeing the issue.

**Comment by tim-lai** [comment]
@mike2184 Fyi, this fix is in today's release. Thanks.

**Comment by mike2184** [comment]
@tim-lai - Just updated to the new version and gave it a try and it is now working as expected. Thanks so much for looking into this and for the speedy fix!
