### ISSUE TITLE
[develop 2.0] File upload not working in 2.0

### ISSUE THREAD

**Issue by mkrouwer** [swagger-api/swagger-ui#609]
File upload is not working in 2.0, it comes back with a javascript error

**Comment by edwardpig** [comment]
This change resolves my original issue, but I've encountered another.

Now when I click 'Try it out!', I get a JavaScript error on l. 753 of swagger-client.js: 'Uncaught TypeError: Cannot read property 'api' of undefined'.

Thanks.

**Comment by fehguy** [comment]
this has been fixed in the develop_2.0 branch

**Comment by stevendearborn** [comment]
Is there a test sample for using multipart/form-data and single file upload that the Swagger UI user can specify the content-type for the file contents?  I am having trouble specifying this in Swagger 2.0 in a way that generates the correct request.

**Comment by webron** [comment]
@stevendearborn the spec doesn't allow specifying a content type for specific form data parameters. It's a limitation of the spec.

**Comment by stevendearborn** [comment]
I have seen screen captures of this working with Swagger 1.2, where Swagger UI paces a content-type drop-down box next to the file upload command button.  Is this still possible in Swagger 2.0?  Does anyone have a Swagger 2.0 example that works in Swagger UI?
