### ISSUE TITLE
Swagger-UI-React Plugin not working

### ISSUE THREAD

**Issue by neo7337** [swagger-api/swagger-ui#6124]
### Q&A (please complete the following information)
 - OS: [e.g. macOS] Windows
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] 80
 - Method of installation: [e.g. npm, dist assets] npm
 - Swagger-UI version: [e.g. 3.10.0] "swagger-ui-react": "3.24.3"
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] OpenAPI 3.0

### Content & configuration
I am trying to use a plugin in the swagger-react-ui package implementation in React App but it doesn't seem to be working. 

Example Swagger/OpenAPI definition:
```yaml
https://api.mna.dev.spsapps.net/swagger/?format=openapi
```

Swagger-UI configuration options:
```js
import SwaggerUI from "swagger-ui-react";

import "swagger-ui-react/swagger-ui.css";

const DisableTryItOutPlugin = function() {
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    }
  };
};

function App() {
  const plg = [DisableTryItOutPlugin];

  return (
    <div className="App">
      <SwaggerUI
        url="https://api.mna.dev.spsapps.net/swagger/?format=openapi"
        plugins={plg}
      />
    </div>
  );
}
```

### Describe the bug you're encountering
I am trying to use a plugin in the swagger-react-ui package implementation in React App but it doesn't seem to be working. I am trying to remove the try it out using the plugin above but it does not seem to work.

### Screenshots

![image](https://user-images.githubusercontent.com/17389779/84238101-d69a1b80-ab3d-11ea-93d5-7e6a4e3e50ea.png)

**Comment by suvirbhargav** [comment]
I am also looking to learn more about plugin, do you know where one can read more about allowTryItOutFor?

**Comment by suvirbhargav** [comment]
Maybe this is useful, https://github.com/shockey/swagger-ui-plugins ?

**Comment by suvirbhargav** [comment]
Actually, all plugin works for me, including DisableTryItOutPlugin from above code. I upgraded to "swagger-ui-react": "3.26.2", that's the latest version.

**Comment by neo7337** [comment]
> Actually, all plugin works for me, including DisableTryItOutPlugin from above code. I upgraded to "swagger-ui-react": "3.26.2", that's the latest version.

This works!
