### ISSUE TITLE
Allow support other formats on strings with a plugin

### ISSUE THREAD

**Issue by jclx** [swagger-api/swagger-ui#6131]
### Content & configuration

Swagger/OpenAPI definition:
 ```json
 {
  "StartDate" : {
       "format" : "local-date-time",
       "type" : "string"
    }
}
 ```

 Swagger-UI configuration options:
 ```js
 SwaggerUI({
   // your config options here
 })
 ```

 ```
 ?yourQueryStringConfig
 ```

### Is your feature request related to a problem?
Support for additional formats on strings other than those provide.

### Describe the solution you'd like
  Add support for a plugin to provide sample values for different formats other than default supplied.
In /swagger-ui/src/core/plugins/samples/fn.js , support for string_date-time is an example.
the format local-date-time is a custom format. Adding plugin could provide for other formats than the default provided. This could also support when an regexp is used for the format.

### Additional context
Also having some context like name of field could allow different sample values.

**Comment by tim-lai** [comment]
@jclx The SwaggerUI Plugin API is available to the community for the reasons you cited. If you have a helpful plugin to share with the community, please feel free to create a PR. Thanks.
