### ISSUE TITLE
Multiple file Upload using .net core 3.1

### ISSUE THREAD

**Issue by sumankumarsahu** [swagger-api/swagger-ui#6134]
Hello these are bellow codes.

    public class SwaggerFileOperationFilter : IOperationFilter
    {

        private readonly IEnumerable<string> _actionsWithUpload = new[]
        {
            //add your upload actions here!
            NamingHelpers.GetOperationId<FileUploadController>(nameof(FileUploadController.Index))
        };

        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            if (operation.Tags.All(p => p.Name != "FileUploads")) return;

            var fileParameter = operation.Parameters.FirstOrDefault(x => x.Name == "file");
            if (fileParameter != null)
                operation.Parameters.Remove(fileParameter);

            var uploadFileMediaType = new OpenApiMediaType()
            {
                Schema = new OpenApiSchema()
                {
                    Type = "object",
                    Properties =
                    {
                        ["Files"] = new OpenApiSchema()
                        {
                            Description = "Upload File",
                            Type = "file",
                            Format = "formData",
                            MultipleOf = 10
                        }
                    },
                    Required = new HashSet<string>() { "Files" }
                }
            };

            operation.RequestBody = new OpenApiRequestBody
            {
                Content = { ["multipart/form-data"] = uploadFileMediaType }
            };
        }
  

    public class NamingHelpers
    {
  
        public static string GetOperationId<T>(string actionName) where T : ControllerBase => $"{GetControllerName<T>()}{actionName}";

        public static string GetControllerName<T>() where T : ControllerBase => typeof(T).Name.Replace(nameof(ControllerBase), string.Empty);
    }
}

startup.csservices.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Title = "DSA File Upload Api",
                    Version = "v1.0.0",
                    Contact = new OpenApiContact
                    {
                        Name = "DSA_Leads",
                        Email = "DSA_Leads@Dell.com",
                    }
                });
                c.CustomSchemaIds(type => type.ToString());
                //c.OperationFilter<SwaggerFileOperationFilter>();
            });

Controller  [HttpPost("fileUploads")]
        public IActionResult Index([FromForm] FileUploadRequest fileUploadRequest)
        {
            var outPut = _fileUploader.ExtractFilesAndScan(fileUploadRequest);
            return Ok(new
            {
                outPut.FilesUploaded,
                outPut.FilesScanned,
                ScanResult = outPut.ScanResult.ToString(),
                outPut.Messages
            });
        }
class Modelclass{
[Required]
        public string UploadType { get; set; }
        [Required]
        public ICollection<IFormFile> Files { get; set; }
}

Using postman Getting values.But Using Swagger not getting null vlaues like bellow screenshots.

<img width="960" alt="JsonFile" src="https://user-images.githubusercontent.com/32834431/84588948-19633880-ae49-11ea-8406-cbf8cc2952d8.png">
<img width="960" alt="Postman" src="https://user-images.githubusercontent.com/32834431/84588949-1a946580-ae49-11ea-9322-a48735a636bc.png">
<img width="960" alt="ValueHaving" src="https://user-images.githubusercontent.com/32834431/84588957-1bc59280-ae49-11ea-9d9f-f43e0219ea06.png">
<img width="960" alt="SwaggerUI" src="https://user-images.githubusercontent.com/32834431/84588954-1bc59280-ae49-11ea-97ef-3104d5f89737.png">
<img width="960" alt="SwaggerRequest" src="https://user-images.githubusercontent.com/32834431/84588953-1b2cfc00-ae49-11ea-91d5-6839734af898.png">

Thanks & Regards,Suman Kumar Sahu

**Comment by webron** [comment]
Unfortunately, we can't help with any .net code. For assistance with Swagger UI, please file a new ticket following the issue template. You should provide the swagger/opepiapi json/yaml file and the version of swagger ui that you use.

**Comment by sumankumarsahu** [comment]
Hi Webron.
I am using 5.4.1 version.Swagger.I have attached swagger. Json file.Can you please help on it.
