### ISSUE TITLE
Need to display the response as application/json instead of text/html

### ISSUE THREAD

**Issue by syedkhajafairoz** [swagger-api/swagger-ui#6135]
I am using the swagger library (https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.17.6/swagger-ui-bundle.js). Currently the response is displaying as text/html, I need to change this to application/json. Anyone help me to do this please?
Below is the current and expected response for reference.
Current:
![image](https://user-images.githubusercontent.com/51500321/84629948-c2bd3380-af08-11ea-89ae-b8e8e11772c1.png)

Expected:
{
“type1”: “test1”,
“type2”: “test2”
}

**Comment by suvirbhargav** [comment]
In your swagger yml or definition file, you can add option,   
    
`
      produces:
        - "application/text"
        - "application/csv"
        - "application/json"
`

And then you can choose the option in UI. What do you select at the moment when you request the data? Try to see in the console what is the reponse you get from server side.

**Comment by hkosova** [comment]
@syedkhajafairoz the response headers on your screenshot are the ones returned by your API that is running on `localhost:10006`. You need to change the API implementation code and/or the server configuration in order to get the proper `Content-Type` header in responses.
