### ISSUE TITLE
swagger-ui-bundle.js (~1MB) file too big for hosting in AWS Lambda behind ALB

### ISSUE THREAD

**Issue by DamianKedzior** [swagger-api/swagger-ui#6146]
### Q&A (please complete the following information)
 - OS: client Windows / server: Amazon Linux 2, AWS Lambda
 - Browser: all affected (it's a server issue)
 - Version: N/A
 - Method of installation: via [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore)
 - Swagger-UI version: 3.25.0
 - Swagger/OpenAPI version: N/A

### Describe the bug you're encountering
This issue is related to size of the `swagger-ui-bundle.js` file. Currently it's close to 1MB which makes it not possible to host in AWS Lambda (behind AWS ALB - Application Load Balancer).
[AWS ALB + AWS Lambda has a limit for files it can transfer which is set to 1MB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-502-issues) which has been already reached when trying to serve `swagger-ui-bundle.js` file from version 3.25.0

This issue is to open the discussion about how we could potentially solve it, e.g.:
- is there a chance to decrease size of `swagger-ui-bundle.js` file?
- could we split this file into smaller chunks?

### Expected behavior
SwaggerUI can be hosted in AWS Lambda.

**Comment by webron** [comment]
@DamianKedzior what size _would_ work?

**Comment by DamianKedzior** [comment]
@webron I am pretty sure current size of 974KB just passed the treshold. I used some older version where file size was around 956KB it was working fine.

**Comment by DamianKedzior** [comment]
So if there is a chance to add some additional minification or remove some not needed code it could make it work again.

**Comment by webron** [comment]
Thanks @DamianKedzior. Our general size check is for the bundle to be < 1MB (as part of our CI). However, it's been long enough since we last did a manual size audit, so it's probably time to do one again.

**Comment by DamianKedzior** [comment]
Hi @webron,
just wanted to follow up with you and ask if you have a plan in mind to address this issue?

**Comment by ronl** [comment]
Workaround - enable gzip response compression for mime type  application/javascript.  This will compress the bundle js file within .net core, thus greatly reducing the size and getting under the 1mb lambda limit.   We do this also for json and other mime types in order to be able to provide much larger responses to our api clients than we could without it.    They are required to specify the accept-encoding gzip, deflact request header.

Chrome and I assume other modern browsers will automatically specify the accept-encoding header when retrieving content.  You can see in the response headers that the bundler js comes back as gzip and reduced to around 350kb.

`services.AddResponseCompression(options =>
                    {
                        options.Providers.Add<GzipCompressionProvider>();
                        options.EnableForHttps = true;
                        options.MimeTypes = new[]
                                {
                                    "application/json",
                                    "text/tab-separated-values",
                                    "application/javascript",
                                    "text/csv",
                                    "text"
                                };
                    }
                );
`

**Comment by tim-lai** [comment]
@DamianKedzior I think @ronl has a good answer, and probably the most reliable long term answer. That said, there has been effort to reduce the bundle size as well as offer an es2015 bundle. The most recent release of [swagger-ui@3.32.3](https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.3) is ~960KB

**Comment by rschiefer** [comment]
Added the startup code from @ronl but its not gzipping the file.  Anything else others had to do?

**Comment by ronl** [comment]
> Added the startup code from @ronl but its not gzipping the file. Anything else others had to do?

What browser are you using?  If you watch in the developer tools, is it sending the request header "accept-encoding"  with gzip and deflate?

**Comment by rschiefer** [comment]
yes

**Comment by ronl** [comment]
@rschiefer , on the IAppLIcationBuilder app,  try ...

   app.UseResponseCompression()

to enable

**Comment by srudenkord** [comment]
Just to confirm the workaround works.  Code should be like the following

```
  public void ConfigureServices(IServiceCollection services)
        {

             ...

            services.AddResponseCompression(options =>
            {
                options.Providers.Add<BrotliCompressionProvider>();
                options.Providers.Add<GzipCompressionProvider>();
                options.MimeTypes = new[] {"application/json", "text/tab-separated-values", "application/javascript", "text/csv", "text"};
            });

            
        }
        
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            .....
            
            app.UseResponseCompression();

            .....   
        }        
```

**Comment by kenberkeley** [comment]
For Node.js users, the most convenient solution is using [`compression`](https://github.com/expressjs/compression).

**Comment by rr-nagasyamala-appikatla** [comment]
I am facing the [same issue](https://stackoverflow.com/questions/75528385/swagger-ui-is-not-working-with-quarkus-aws-lambda-application) in my java Quarkus lamda application. How can we solve this in a java application. My quarkus version is **2.7.5.Final**, java version: 11 and using the plugin **quarkus-smallrye-openapi**. 
Note: Swagger is working good with same application in my local but not in qa/prod. I have spent lot of time but not able find the correct fix. Can anyone please help me. Thanks.

**Comment by astsiatsko** [comment]
Hi guys, do you have solution for spring boot? I also can't host swagger due to the same issue ...

**Comment by lebenitza** [comment]
> @DamianKedzior I think @ronl has a good answer, and probably the most reliable long term answer. That said, there has been effort to reduce the bundle size as well as offer an es2015 bundle. The most recent release of [swagger-ui@3.32.3](https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.3) is ~960KB

As the <1MB size is not the case anymore (and for some time now), see: https://unpkg.com/swagger-ui-dist@5.11.0/swagger-ui-bundle.js which is ~1.4MB, the actual solution remains to enable compression on your HTTP backend server that contains the static files.

I ran into this using Rust, Utoipa and Axum and solved it using compression layer from Tower: https://docs.rs/tower-http/latest/tower_http/compression/index.html The context is ALB + Lambda for some internal, private access to SwaggerUI.

**Make sure to use gzip compression!** I wanted to use Brotli and wasted too much time not understanding why it is not working. Unfortunately I could not find documentation on the supported compression algorithms in AWS ALB and it blows my mind than in 2024 Brotli is not supported but it is was it is.

Hope this helps someone.
