### ISSUE TITLE
Bad authorize dialog for multiple combined authorization API keys

### ISSUE THREAD

**Issue by futape** [swagger-api/swagger-ui#6155]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.106
 - Method of installation: https://editor.swagger.io/
 - Swagger-UI version: ?
 - Swagger/OpenAPI version: OpenAPI 3.0.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
security:
  - SessionId: []
    SystemId: []
paths:
  /:
    get:
      operationId: foo
      summary: Test operation
      responses:
        '200':
          description: Success
components:
  securitySchemes:
    SessionId:
      type: apiKey
      in: query
      name: X-Session-Id
    SystemId:
      type: apiKey
      in: query
      name: X-System-Id
```

Swagger-UI configuration options:
?

### Describe the bug you're encountering

According to [OpenAPI specification ](https://swagger.io/docs/specification/authentication/#multiple) the definition above defines an authentication using a combination of 2 API keys in the headers.
I would expect a dialog of 2 inputs, one for each header, and 1 "authorize" button, since this is 1 combination. In contrast, I would expect 2 inputs with 2 buttons, one per input, for a definition of

```yaml
security:
  - SessionId: []
  - SystemId: []
```

since these are combined with a logical OR.

However, Swagger UI always displays be a dialog with 2 inputs and 2 buttons.

![image](https://user-images.githubusercontent.com/4106712/84888703-f9758400-b097-11ea-97d1-08416d4079b6.png)

I found an [issue from 2016](https://github.com/swagger-api/swagger-ui/issues/2399) which says, that this is more a UX question and that the described dialog is fine since the "authorize" button at the top is intended to show *all available authorizations* and not the ones really to use for a specific operation.
[That comment](https://github.com/swagger-api/swagger-ui/issues/2399#issuecomment-248426627) also says that when clicking on the authorize button for a specific operation, the dialog should display combined API keys accordingly (and it does in the screenshot in the comment). However, I can't figure out how to get that dialog. It always should ne with 2 inputs and 2 buttons.

**Comment by hkosova** [comment]
Thanks for the feedback! This issue is tracked in #3521, so I'll close this one as a duplicate.

**Comment by futape** [comment]
Whoops, seems as I haven't searched well enough. Thank you.
