### ISSUE TITLE
When using  javax.validation.constraints annotation  on method parameters，the parameter is recognized as the request body

### ISSUE THREAD

**Issue by zx472010602** [swagger-api/swagger-ui#6171]
### Q&A (please complete the following information)
 - OS: windows
 - Browser: firfox 2020.2
 - Version: 2.9.2
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 2.9.2
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### To reproduce...

![image](https://user-images.githubusercontent.com/31379313/85496894-a9ef0500-b60f-11ea-97d2-60d0336c7cfe.png)
![image](https://user-images.githubusercontent.com/31379313/85496910-b1161300-b60f-11ea-9403-a6da925ad132.png)
![image](https://user-images.githubusercontent.com/31379313/85496938-bbd0a800-b60f-11ea-8c64-6f5a259258c5.png)
![image](https://user-images.githubusercontent.com/31379313/85497156-0eaa5f80-b610-11ea-9b44-45ffcce9120b.png)
![image](https://user-images.githubusercontent.com/31379313/85497258-31d50f00-b610-11ea-9a82-adafa9af825c.png)

**Comment by hkosova** [comment]
That's a question for [Springfox](https://github.com/springfox/springfox/), not Swagger UI.
