### ISSUE TITLE
Docker swagger-ui with BASE_URL problem

### ISSUE THREAD

**Issue by ReiSchneider** [swagger-api/swagger-ui#6172]
I have recently hosted the docker image version of the swaggerapi/swagger-ui with the following command

```
docker run -d -p 8091:8080 -e BASE_URL=/swagger -e 'API_URLS=[
  { url: "/swagger/specs/XXX_v1.yml", name: "XXXv1"},
  { url: "/swagger/specs/XXX_v2.yml", name: "XXXv2"},
  { url: "/swagger/specs/XXX_v3.yml", name: XXXv3"},
  { url: "/swagger/specs/YYY_v1.yml", name: "YYYlv1"},
  { url: "/swagger/specs/YYY_v2.yml", name: "YYYv2"}]' -v /home/me/mgmt-swagger/swagger:/usr/share/nginx/html/specs swaggerapi/swagger-ui
```

Everything works when I access it via localhost, but when I deploy it to an AWS instance and access via an application load balancer, it does not load but instead shows up these errors in the browser console

GET https://[REDACTED].com/swagger/swagger-ui.css net::ERR_ABORTED 404...
(index):36 GET https://[REDACTED].com/swagger/swagger-ui-bundle.js net::ERR_ABORTED 404...
(index):37 GET https://[REDACTED].com/swagger/swagger-ui-standalone-preset.js net::ERR_ABORTED 404...
(index):42 Uncaught ReferenceError: SwaggerUIBundle is not defined...

**Comment by ReiSchneider** [comment]
Seems like the issue is the with listening of the ALB. Nevermind, fixed

**Comment by sylvaindd** [comment]
Hello, I know it's a bit old, but I have the same issue, everything OK in local, but can't make it work behind ALB.
Do you remember what the problem was ?
