### ISSUE TITLE
Cannot add XML documentation for object read with [FromQuery] attribute

### ISSUE THREAD

**Issue by SpiritBob** [swagger-api/swagger-ui#6173]
When objects are mapped from the body, we can add description for each of the properties by using the XML `<param>` tag and then outlining in full detail the contents of the object.

But, if the object is being mapped from the query string, I have no control over it when using `<param>` XML tag. Swagger UI simply ignores whatever I write in there. It populates the properties correctly, allowing the users to input things into them, but neither (as before) can I use nested XML summary tags on properties to add clarification as to what they are used for (because swagger up to now does not support this), but the possible workaround with the `<param>` tag is now also not available.

The only possible solution to this, is to dump all of my tooltips with a `<remark>` XML tag, which in a way is unconventional because it will appear below ALL the fields the user can input data in - before the user understands what each field is used for, they'll have to scroll down to a blob of text, only to scroll back up.

**Comment by hkosova** [comment]
This looks like a question for [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) or [Swagger-Net](https://github.com/heldersepu/Swagger-Net) - these are the tools that generate OpenAPI definitions from XML comments in .NET code.
