### ISSUE TITLE
security scopes on operations not displayed properly

### ISSUE THREAD

**Issue by CameronGo** [swagger-api/swagger-ui#6174]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: 83
 - Method of installation: Swagger Hub and Docker image
 - Swagger-UI version: 3.23.0 and Swagger Hub
 - Swagger/OpenAPI version: OpenAPI 3.0]

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0

info:
  version: "1.0.0"
  title: Sample Application Flow OAuth2 Project
  description: >-
    This is an example of using OAuth2 Application Flow in a specification to describe security to your API.

paths:
  /example:
    get:
      summary: example read operation
      security: 
        - application: [read]
      description: >-
        This should only display the read scope
      responses:
        '200':
          description: OK
    put:
      summary: example write operation
      security:
      - application: [write]
      responses:
        '204':
          description: OK
  /ping:
    get:
      summary: Server heartbeat operation
      description: >-
        This appears to successfully override the security and shows unsecured
      security: []
      responses:
        '200':
          description: OK
components:
  schemas: {}
  securitySchemes:
    application:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources
```

### Describe the bug you're encountering
On the GET operation I expect to see only the read scope displayed whereas on the PUT operation I expect to see only the write scope.  I have also tried it with and without a global security tag, but no matter what all of the scopes described under the securitySchemes are displayed everywhere there is an authorization button.

### To reproduce...

1. View the authorization for both the GET and PUT operations

### Expected behavior
I expect to see only the read scope on the GET operation authorization and only the write scope on the PUT operation authorization.

### Screenshots

![image](https://user-images.githubusercontent.com/14074983/85631021-bb9dd000-b642-11ea-9464-0a0983f8a9de.png)

**Comment by hkosova** [comment]
Thanks for the feedback! This issue is tracked in #5062 so I'll close this one as duplicate.
