### ISSUE TITLE
Description is not rendered for a property of object type

### ISSUE THREAD

**Issue by provegard** [swagger-api/swagger-ui#6179]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Edge
 - Version: 83.0.478.56
 - Method of installation: dist assets
 - Swagger-UI version: 3.27.0
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```json
{
    "swagger": "2.0",
    "info": {
        "title": "API",
        "description": "Test",
        "version": "v1"
    },
    "host": "localhost",
    "basePath": "/",
    "schemes": ["file"],
    "paths": {
        "/api": {
            "post": {
                "summary": "create stuff",
                "description": "creates stuff",
                "operationId": "operation1",
                "parameters": [{
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/ADocument"
                        },
                        "name": "body",
                        "description": "a document",
                        "required": true
                    }
                ],
                "responses": {
                }
            },
            "parameters": []
        },
    },
    "definitions": {
        "ADocument": {
            "properties": {
                "data": {
                    "description": "This is an important description!",
                    "$ref": "#/definitions/AnotherDocument"
                },
                "type": {
                    "description": "I'm the type",
                    "type": "string"
                }
            },
            "description": "This is a document.",
            "type": "object"
        },
        "AnotherDocument": {
			"description": "This is another document.",
            "properties": {},
            "type": "object"
        },
    }
}
```

Swagger-UI configuration options:
```js
        SwaggerUIBundle({
            spec: spec,
            dom_id: '#swagger-ui',
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],
            layout: "StandaloneLayout"
        })
```

### Describe the bug you're encountering

The description of a property is not rendered when the property type is an object, i.e. the property has `$ref`. However, when the property is a primitive, e.g. a string, the property description is rendered:

### To reproduce...

Open Swagger-UI with the JSON supplied above.

### Expected behavior

I expect the description of a property to be shown regardless of property type.

### Screenshots

![image](https://user-images.githubusercontent.com/795010/85930873-227bed00-b8c0-11ea-95cb-c33a4338085e.png)

Note how "I'm the type" is rendered, but "This is an important description!" is not.

### Additional context or thoughts

Right now, I have to move a property description to the property type. This of course only works if a type is unique for a property. Most of my types are, but I have a few shared types. When a property uses a shared type, I have to move the description of that property to be included in the description of the type that the property belongs to, and that quickly becomes unwieldy.

**Comment by hkosova** [comment]
See https://github.com/swagger-api/swagger-ui/issues/6046#issuecomment-636086023.

**Comment by provegard** [comment]
Thank you for the reference.
