### ISSUE TITLE
Support for Example Object

### ISSUE THREAD

**Issue by edmondchui** [swagger-api/swagger-ui#618]
It seems like the example object is not shown in the UI. Here is a sample JSON file with example object:

https://github.com/wordnik/swagger-spec/blob/master/fixtures/v2.0/json/resources/resourceWithExamplePayload.json

When will this be added?

Thanks,
Edmond

**Comment by fehguy** [comment]
examples are now put in the model definitions.

**Comment by muralilaxman** [comment]
I am still not able to see the "examples" object in Swagger -Local editor (Local Instance). But the same is working fine in Swagger Online Editor. Please advice
My swagger version is 0.7.5 --

my Yaml Code
---
  info: 
    title: "IPS API"
    version: "1.0.0"
    description: "API for Investment Product Services "
    license: 
      name: "IPS"
    contact: {}
  paths: 
    /strategies: 
      get: 
        responses: 
          200: 
            description: "Success"
            schema: 
              items: 
                $ref: "#/definitions/strategies"
              type: "array"
            examples: 
              application/json: 
                - 
                  url: "http://yaml-online-parser.appspot.com/"
                  name: "Yahoo"
                - 
                  url: "http://yaml-online-parser.appspot.com/"
                  name: "Yahoo"

**Comment by webron** [comment]
@muralilaxman you're looking for [swagger-editor](https://github.com/swagger-api/swagger-editor), and if you're running locally version 0.7.5, then you're using a very old one. Try updating to the latest.

**Comment by muralilaxman** [comment]
@webron - I installed the latest swagger editor (2.9.8) locally and ran  the above YAML script . But still the exampes model is not showing up.. 

I followed the steps mentioned in this link to install the Swagger-Editor locally.

https://github.com/swagger-api/swagger-editor

**Comment by webron** [comment]
Then you should open a ticket on that project.
