### ISSUE TITLE
Broken CSS swagger-ui-react

### ISSUE THREAD

**Issue by camin-mccluskey** [swagger-api/swagger-ui#6181]
### Q&A (please complete the following information)
 - OS: [macOS]
 - Browser: [chrome]
 - Version: [Version 83.0.4103.116]
 - Method of installation: [e.g. npm]
 - Swagger-UI version: [e.g. 3.27.0 swagger-ui-react]
 - Swagger/OpenAPI version: [e.g. Swagger 2.1,3, OpenAPI 3.0.1]

### Content & configuration

Using an openapi.json file which has displayed correctly in the past, the UI appears to be broken for react apps. Screenshot shows petshop example api definition suffers from the same issue.

Minimal Example
```
import React from 'react';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';

const App = () => <SwaggerUI url="https://petstore.swagger.io/v2/swagger.json" />;

export default App;
```

### To reproduce...

1. Install `swagger-ui-react`
2. Use `SwaggerUI` component with petshop api url

### Expected behavior

Displays correctly, with CSS loaded

### Screenshots

<img width="1440" alt="Screenshot 2020-06-29 at 00 47 46" src="https://user-images.githubusercontent.com/18604525/85961537-fdac7600-b9a2-11ea-8693-5faf68172316.png">

**Comment by char0n** [comment]
@camin-mccluskey thank you for reporting this, but I was enable to reproduce. 

### Steps of Reproduction

1. npx create-react-app my-app
2. cd my-app
3. npm i --verbose swagger-ui-react@3.27.0
4. modified index.js to render the API


`index.js`
```js
import React from 'react';
import ReactDOM from 'react-dom';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <React.StrictMode>
    <SwaggerUI url="https://petstore.swagger.io/v2/swagger.json" />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

```

**Comment by camin-mccluskey** [comment]
Hi @char0n thanks for looking into this. Indeed you're absolutely right, when I recreated a new CRA project it worked. I discovered the project I was using had an outdated version of `react-scripts`, which seemed to be causing the issue.

**Comment by char0n** [comment]
@camin-mccluskey np, closing this for now.
