### ISSUE TITLE
Missing commas in response header values in "try it out" results

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#6183]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Method of installation: https://editor.swagger.io
 - Swagger-UI version: 3.25.4, 3.28.0
 - Swagger/OpenAPI version: 2.0, 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
swagger: "2.0"
info:
  title: Response headers test
  version: 1.0.0
host: httpbin.org
schemes: [https]
paths:
  /response-headers:
    get:
      summary: Run the request using the default parameter values
      parameters:
        - in: query
          name: X-Header1
          type: string
          x-example: 'value1,value1'
          required: true
        - in: query
          name: X-Header2
          type: string
          x-example: 'value1, value1'
          required: true
        - in: query
          name: X-Header3
          type: array
          items:
            type: string
          x-example: [value1, value2]
          collectionFormat: multi
          required: true
        - in: query
          name: Access-Control-Expose-Headers
          type: string
          x-example: 'X-Header1, X-Header2, X-Header3, Access-Control-Expose-Headers'
          required: true
      responses:
        200:
          description: ok
```

### Describe the bug you're encountering
Consider response headers that contain comma-separated values:
```
X-Header1: value1,value2
X-Header2: value1, value2  # note the space after comma
```
In "try it out" results, the first header is displayed correctly, but the second header is displayed as `X-Header2: value1value2`, that is without the `, ` characters.

### Steps to reproduce

1. Open https://editor.swagger.io and paste the definition provided above.
2. Open the browser dev tools > Network tab.
3. Run the request with the default parameter values.
4. Compare the response header values displayed in Swagger UI with the values on the Network tab in dev tools.

### Actual result
The values of the `access-control-expose-headers`, `X-Header2` and `x-header3` headers are missing inner `, ` characters.
```
access-control-expose-headers: X-Header1X-Header2X-Header3Access-Control-Expose-Headers
content-length: 289
content-type: application/json
x-header1: value1,value1
x-header2: value1value1
x-header3: value1value2
```

### Expected result
The values of the `access-control-expose-headers`, `X-Header2` and `x-header3` headers include commas (and match the values in dev tools > Network):
```
access-control-expose-headers: X-Header1, X-Header2, X-Header3, Access-Control-Expose-Headers
content-length: 289
content-type: application/json
x-header1: value1,value1
x-header2: value1, value1
x-header3: value1, value2
```

### Screenshots
![Response headers](https://user-images.githubusercontent.com/8576823/85999741-47ce3f80-ba15-11ea-96ae-90aa4d995807.png)

### Additional context or thoughts
n/a

**Comment by tmurray222** [comment]
I tracked this down to where the response headers are built in src/core/live-response.jsx, in the render() function starting at line 50.  If headers[key] is an array, then the React text string gets rendered as the array elements joined without commas or anything.  I tried the following and it appears to work:
```
    const returnObject = headersKeys.map(key => {
		var joinedHeader = Array.isArray(headers[key])
		? headers[key].join()
		: headers[key];
      return <span className="headerline" key={key}> {key}: {joinedHeader} </span>
```
I'd consider submitting a pull request for this, but I'm not familiar enough with the Swagger UI open source project to know if this proposed change would break anything or whether it's correct.  Check this approach out and see if it works.

**Comment by s0rbus** [comment]
Ah, interesting. I suspect this is why there is no space between the day and date when the date header from Response is shown. i.e. I would expect to see date: Wed 19 Aug 2020 16:19:10 but I see Wed19 Aug 2020 16:19:10

A small thing, but annoying when you are not sure if it is formatting in the ui or something you have done in your code.

**Comment by jackneer** [comment]
hi, may I help this, thanks!
