### ISSUE TITLE
Using version 3.0.0 format, does not generate JSON in sent request body correctly

### ISSUE THREAD

**Issue by XANi** [swagger-api/swagger-ui#6191]
- OS: Linux
 - Browser: Chrome
 - Version: 83.0
 - Method of installation: npm pack swagger-ui-dist[e.g. npm, dist assets]
 - Swagger-UI version: 3.28.0
 - Swagger/OpenAPI version: 3.0.0

Following YAML (it is a snipped from bigger one and edited for clarity)

```yaml
---
openapi: "3.0.0"
#swagger: "2.0.0"
basePath: /api/v1
servers:
  - url: /api/v1
    description: local instance
tags:
    - name: "encoding"
      description: "encoding"
schemes:
    - "https"
    - "http"
paths:
    /transcode:
        post:
            operationId: "encode"
            consumes:
                - "application/json"
            produces:
                - "application/json"
            parameters:
                - in: "body"
                  name: "body"
                  description: "encoding parameters"
                  schema:
                      $ref: "#/definitions/encode"
            responses:
                "202":
                    description: "accepted"
                "503":
                    description: "bad input"
definitions:
    encode:
        type: "object"
        properties:
            source:
                type: "object"
                properties:
                    url:
                        type: "string"
                        description: "download string for the source"
```
produces object/body test in preview but does not submit that JSON when sending it via "Execute", and doesn't generate proper curl commandline:

![2020-06-30_17-37](https://user-images.githubusercontent.com/147394/86146399-73762600-baf8-11ea-97d3-fe4ff7740d4c.png)

Changing version to 2.0.0 (as in commented out part of the YAML), makes generation correct:

![2020-06-30_17-41](https://user-images.githubusercontent.com/147394/86146887-0911b580-baf9-11ea-9ddb-61f0d97f40ca.png)

**Comment by hkosova** [comment]
Your example uses OAS2 syntax, and simply replacing `swagger: '2.0'` with `openapi: 3.0.0` is not enough to make it valid OAS3. You can use https://editor.swagger.io to convert OAS2 definitions to OAS3 (Edit > Convert to OpenAPI 3) and validate the syntax. See also [OpenAPI 3.0 Syntax Guide](https://swagger.io/docs/specification/basic-structure/).

**Comment by XANi** [comment]
@hkosova Thanks for the hint ...but editor is still broken ? It shouldn't interpret the obsolete tags and it shouldn't display the body if it won't send it?

**Comment by hkosova** [comment]
@XANi Swagger UI (including the UI panel in Swagger Editor) expects a valid OpenAPI definition. If the API definition is invalid, the behavior is undefined, which can result in rendering issues and inconsistencies - as you've seen.

Swagger UI does not include a syntax validation engine, but Swagger Editor does, and there are other validators as well. It is expected that people validate the syntax of their OpenAPI definitions and fix the errors before trying to render API docs with Swagger UI.

**Comment by XANi** [comment]
Thanks for clarification :)
