### ISSUE TITLE
Swagger is not honoring the server variable URL for /Authorize and /token endpoints

### ISSUE THREAD

**Issue by rajasekhar1240** [swagger-api/swagger-ui#6192]
If we have a server variable which takes base URL then it is reflecting only for the invocation endpoint and not updating at the other places like for Client credentials and Auth code flows it should consider the same base URL (for /authorize , /token ,/refreshtoken etc..) otherwise it will endup giving the error while trying to get the token.

Please let me know if i need to provide more details to understand the issue better.

**Comment by hkosova** [comment]
Thanks for the report! This issue is tracked in #3992 so I'll close this one as a duplicate.
