### ISSUE TITLE
Custom Authentication

### ISSUE THREAD

**Issue by abolfazlmohammadiseif** [swagger-api/swagger-ui#6195]
I need to be able to authenticate in swagger-ui using Username+Psssword+TenantId. So that user could fill all three fields of the form and login. then use the authorized webApis. what is the best way to do so?

**Comment by gaeljw** [comment]
You could probably use a custom `requestInterceptor`.

Define your 3 fields in your spec as authorizationKey for instance, and do some logic in the request interceptor to retrieve these and compute whatever auth you need to compute.
