### ISSUE TITLE
Problem with build React.js + Next.js

### ISSUE THREAD

**Issue by DjVreditel** [swagger-api/swagger-ui#6198]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.116
 - Method of installation: npm
 - Swagger-UI version: ^3.28.0
 - Swagger/OpenAPI version: v2

### Console output in build time
`Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
(node:5372) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (10)
    at Hash.update (internal/crypto/hash.js:82:11)
    at D:\web\node_modules\next\dist\build\webpack\plugins\hashed-chunk-ids-plugin.js:24:41
    at Array.forEach (<anonymous>)
    at D:\web\node_modules\next\dist\build\webpack\plugins\hashed-chunk-ids-plugin.js:24:25
    at SyncHook.eval [as call] (eval at create (D:\web\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (D:\web\node_modules\tapable\lib\Hook.js:154:20)
    at D:\web\node_modules\next\node_modules\webpack\lib\Compilation.js:1275:30
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\web\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\web\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (D:\web\node_modules\next\node_modules\webpack\lib\Compilation.js:1244:27)
(node:5372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()
. To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Example Swagger/OpenAPI definition:
https://petstore.swagger.io/v2/swagger.json

Swagger-UI configuration options:
```js
SwaggerUI({
           domNode: document.getElementById("swaggerContainer"),
           url: "https://petstore.swagger.io/v2/swagger.json"
})
```

### Describe the bug you're encountering
I tryed to use swagger-ui-react and now trying to use swagger-ui, but on both i getting same error in build time

### To reproduce...
1. Setting up project with ReactJs and NextJs
2. Create a swagger page
```js
import React from "react";
import dynamic from 'next/dynamic'
import "swagger-ui-react/swagger-ui.css"

const SwaggerUI = dynamic(() => import('swagger-ui-react'), {ssr: false});

export default () => <SwaggerUI url="https://petstore.swagger.io/v2/swagger.json" docExpansion="list"/>
```

**OR**

```js
import React, {useEffect} from "react";
import 'swagger-ui/dist/swagger-ui.css'


export default ({data}) => {
    useEffect(() => {
        import('swagger-ui').then((module) => {
            module.default({
                domNode: document.getElementById("swaggerContainer"),
                url: "https://petstore.swagger.io/v2/swagger.json"
            })
        })
    }, [])
    return <div id="swaggerContainer"/>

}

```

3. Try to build project with `next build`

### Expected behavior
successful build

### P.S.
Feel free to ask me if you need more information

**Comment by DjVreditel** [comment]
Also i tried **swagger-ui-dist**
With it bundle complete successful, but when i trying to open page with swagger, i getting error: `TypeError: o is not a function`

### Example: 
```js
import React, {useEffect} from "react";
import 'swagger-ui-dist/swagger-ui.css'
const SwaggerUIBundle = require('swagger-ui-dist').SwaggerUIBundle


export default ({data}) => {
    useEffect(() => {
        SwaggerUIBundle({
       domNode: document.getElementById("swaggerContainer"),  
        url: "https://petstore.swagger.io/v2/swagger.json"})
    }, [])
    return <div id="swaggerContainer"/>
}

```

**Comment by DjVreditel** [comment]
> I'm having problems also with this package when building my app.

I updated to next.js v.11.0.1 and now all works fine

**Comment by char0n** [comment]
@DjVreditel glad to hear the issue was resolved!
