### ISSUE TITLE
cURL remembers form data parameters from previously selected media type with different schema

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#6201]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome latest
 - Method of installation: https://editor.swagger.io
 - Swagger-UI version: 3.25.5 - 3.28.0. Didn't check earlier versions.
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
```yaml
openapi: 3.0.0
info:
  title: Form data test
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  /post:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Foo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bar'
      responses:
        '200':
          description: ok

components:
  schemas:
    Foo:
      type: object
      properties:
        foo:
          type: string
          example: ''
    Bar:
      type: object
      required: [bar]
      properties:
        bar:
          type: integer
          example: 1
```

### Describe the bug you're encountering
In the definition above, the POST operation uses two media types with different schemas. If you switch the media type to `multipart` then back to `application/x-www-form-urlencoded`, the generated cURL command will also include the required fields from the `multipart` schema.

This issue is somewhat similar to #5872, not sure if it's the same issue.

### To reproduce...

1. Go to https://editor.swagger.io and paste the definition avove.
2. In the UI, expand the operation and click "Try it out".
3. Switch the request media type to `multipart/form-data`.
4. Switch the request media type back to `application/x-www-form-urlencoded`.
5. Click "Execute".
6. Examine the generated cURL command.

### Expected behavior
```
... -d "foo=value"
```

### Actual behavior
```
... -d "foo=value&bar=1"
```
Note the extra `bar=1` parameter which is not actually present in the schema for `application/x-www-form-urlencoded`.

### Screenshots
n/a

### Additional context or thoughts
n/a

**Comment by hkosova** [comment]
A variation of this bug, where cURL remembers ALL (not just required) fields from the previously selected media type:

```yaml
openapi: 3.0.0
info:
  title: Form data test
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  /post:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bar'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Foo'
      responses:
        '200':
          description: ok

components:
  schemas:
    Foo:
      type: object
      properties:
        foo:
          type: string
          example: 'value'
    Bar:
      type: object
      required: [bar]
      properties:
        bar:
          type: integer
          example: 1
        baz:
          type: string
          example: 'zzz'
```
Steps:
1. Go to https://editor.swagger.io and paste the definition avove.
2. In the UI, expand the operation and click "Try it out".
3. Switch the request media type back to application/x-www-form-urlencoded.
4. Click "Execute".
5. Examine the generated cURL command.

Expected:
```
-d "foo=value"
```

Actual:
```
-d "bar=1&baz=zzz&foo=value"
```

**Comment by char0n** [comment]
This bug must be been with us for a longer time. I went back as far as Nov 18, 2019 ([v3.24.3](https://github.com/swagger-api/swagger-ui/commit/94e101924b84435585896f4ea7c4092182a91f23)) but the bug is still manifesting there. Switching from trying to figure out what caused it into fixing it mode.

**Comment by char0n** [comment]
Cause of the bug:

`requestBody` now being maintained in one single place instead of separating `requestBodies` by `requestContentType`. Attached [PR](https://github.com/swagger-api/swagger-ui/pull/6214) fixes the problem and data are now being maintained per `requestContentType`.

**Comment by tim-lai** [comment]
This issue is specific to content types that also have/reference different schemas, which seems like an edge case to me. I updated the title description.

1. In the case of same schema (normal use case), the cURL updates properly.

E.g. If you modify the definition provided, and use $ref: '#/components/schemas/Bar' for both content types, everything appears to work as expected. e.g. `form-data input bar: 1 -> execute -> curl: "bar=1"`, then switch `urlencoded input bar:23 -> execute -> curl: "bar=23"`

2. In the case where different content types have their own separate schema... The proper fix would to re-resolve the spec on a content type switch to pick up any possible schema changes. However, if no schema change, keep in memory any user input data, and maintain existing UX. Otherwise, re-render is required because the fields are dependent on the schema used, and the schema will have changed.
