### ISSUE TITLE
Disable example data generation

### ISSUE THREAD

**Issue by dandew** [swagger-api/swagger-ui#6207]
I have an issue with a loading an OpenAPI v3 spec: because of reentrancy in the data model, the example data that gets generated is massive and makes the UI freeze (need to close the browser tab).

As a sanity check, I've run `swagger-codegen generate -l html -I openapi.json` which produced a massive 3MB HTML file out of my 240KB OpenAPI spec. The generated HTML contains a huge and virtually useless example data section.

I have not found a documented way of disabling this but is there any other way to turn of example data generation?

**Comment by tim-lai** [comment]
@dandew There does not currently exist a method to turn off data generation of Example. Since it's part of the resolver process, I'm not sure it could be done either.
