### ISSUE TITLE
Fetch errorNot Found ./swagger.json

### ISSUE THREAD

**Issue by kbonevska** [swagger-api/swagger-ui#6211]
### Q&A (please complete the following information)
 - Swagger-UI version: 3.28.0

### Describe the bug you're encountering
When I execute **docker run -p 80:8080 -e BASE_URL=/swagger -e SWAGGER_JSON=/data/backend.json swaggerapi/swagger-ui** I am experiencing this ![image](https://user-images.githubusercontent.com/37846123/86630587-b2fbb100-bfd5-11ea-9600-e13f8593ae6d.png)

### To reproduce...

**docker run -p 80:8080 -e BASE_URL=/swagger -e SWAGGER_JSON=/data/backend.json swaggerapi/swagger-ui**

### Expected behavior
After executing **docker run -p 80:8080 -e BASE_URL=/swagger -e SWAGGER_JSON=/data/backend.json swaggerapi/swagger-ui** I should see
![image](https://user-images.githubusercontent.com/37846123/86631131-6d8bb380-bfd6-11ea-9d99-7b3c0804b6b5.png)

**Comment by kbonevska** [comment]
@waterkip ;) thanks

**Comment by waterkip** [comment]
The bug reporting went initially via mail and I got the following response from @kbonevska:

> Its ok :) I have already done it and it worked like a charm(branch: mini-revert-swagger-json-root).
> I will try to file a bug. Thanks for helping. I was thinking I am doing something totally wrong.

**Comment by tim-lai** [comment]
fixed in #6212
