### ISSUE TITLE
Is it possible to only enable the 'Try it out' button when the user is Authorized?

### ISSUE THREAD

**Issue by matsch01** [swagger-api/swagger-ui#6217]
I see that it's possible to enable/disable the Try it out button using the following plugin:

```
const DisableTryItOutPlugin = function() {
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    }
  }
}

SwaggerUI({
  plugins: [
    DisableTryItOutPlugin
  ]
})
```

But I would like to make this conditional on whether the user is Authorized. Is this possible?

**Comment by tim-lai** [comment]
@matsch01 You could extend the `DisableTryItOutPlugin` with authorization rules in your application.
