### ISSUE TITLE
BUG: @ApiImplicitParam does not support required=true when paramType = "header" 

### ISSUE THREAD

**Issue by kishorepurushothaman20** [swagger-api/swagger-ui#6225]
implementation "io.springfox:springfox-boot-starter:3.0.0"
Spring boot version: 2.3.0.RELEASE

When we define @ApiImplicitParam like below,
@ApiImplicitParams({
            @ApiImplicitParam(name = Headers.AUTHORIZATION, required = true, dataType = "String", paramType = "header"),
            @ApiImplicitParam(name = Headers.CLIENT_CHANNEL, required = true, dataType = "String", paramType = "header", example = "mobile-app", value = "Source of initiation")
    })

Swagger allows the form submission to the api and the page is kept on loading and the web console has the error written
![image](https://user-images.githubusercontent.com/36532751/87445470-624d0f00-c5f8-11ea-8885-ca7dcf8014d0.png)
![image](https://user-images.githubusercontent.com/36532751/87445514-6ed16780-c5f8-11ea-9091-28149d94206a.png)

Reference:
https://github.com/springfox/springfox/issues/3394

**Comment by hkosova** [comment]
Please post your API definition (YAML/JSON) file. You can export it from Swagger UI as [explained here](https://stackoverflow.com/a/48525934).

**Comment by kishorepurushothaman20** [comment]
Hi,

Posting the JSON

[swagger.txt](https://github.com/swagger-api/swagger-ui/files/4980593/swagger.txt)

**Comment by kishorepurushothaman20** [comment]
Posting the swagger json
[swagger.txt](https://github.com/swagger-api/swagger-ui/files/4980610/swagger.txt)

**Comment by hkosova** [comment]
The `Authorization` header is missing the `type`. I'm not sure, but I think you need to use
```java
@ApiImplicitParam(..., dataType = "string", ...),
```
with lowercase `"string"` to generate the correct `type` value.

You can use https://editor.swagger.io to check your API definition for syntax errors. When the API definition is generated from source code (as in your case), these errors are usually caused by misconfigured annotations.

**Comment by kishorepurushothaman20** [comment]
Thanks for the reply.
It works when I remove datatype and type parameter instead placing a new paramenter dataTypeClass = String.class.
My annotation is looking something like this,
 @ApiImplicitParams({
            @ApiImplicitParam(name = Headers.AUTHORIZATION, required = true, paramType = "header", dataTypeClass = String.class),
            @ApiImplicitParam(name = Headers.CLIENT_CHANNEL, required = true, dataTypeClass = String.class, paramType = "header", example = "Webben", value = "Source from where the signing is initiated")
    })

But we end up having a compatibility issues and also when we do an upgrade from 2.x to 3.0 we may need to make a code change of this parameter across all the places isn't it?
Do you think it needs to be fixed in Swagger ui instead or update the docs stating this?

**Comment by hkosova** [comment]
> But we end up having a compatibility issues and also when we do an upgrade from 2.x to 3.0 we may need to make a code change of this parameter across all the places isn't it?

It looks like you are using [Springfox](https://github.com/springfox/springfox) to generate the API definitions from Java annotations. If Springfox has any compatibility issues you should open a ticket with Springfox to address those issues.

**Comment by kishorepurushothaman20** [comment]
Thanks let me connect this issue in springfox
