### ISSUE TITLE
Avoiding Unnecessary Parameters for API

### ISSUE THREAD

**Issue by SaiHarishVyshu** [swagger-api/swagger-ui#6238]
If any path receives query parameters or body parameters not defined in swagger spec, it is not throwing any error but just responding just in a successful way! 

Say for example if any path has no parameters(query) defined in swagger spec and if we send request to that path with some extra parameters like /path?key=value it is responding properly as such no query parameter is passed

Is there any option for swagger spec to validate in a strict mode and reject the request due to unnecessary parameters sent?

**Comment by hkosova** [comment]
This looks like a question to the server-side framework that you use (Swashbuckle, Springfox, Swagger-PHP, etc.), not Swagger UI. Swagger UI is a documentation renderer and it displays only those parameters that are explicitly defined in your API definition.

**Comment by SaiHarishVyshu** [comment]
Thanks for the info
Yes you are correct, this is a question to swagger server code

FYI, I have found parameter "strict_validation=True" parameter  in Connexion so that swagger is throwing error if any undefined parameter is being passed to the API
