### ISSUE TITLE
Swagger UI Put Request with multipart/form-data is not properly configured

### ISSUE THREAD

**Issue by cyantarek** [swagger-api/swagger-ui#6239]
I'm trying to send put request with multipart/form-data. But the request is kinda off.

Here's the curl request swagger is showing:
```curl -X PUT "http://0.0.0.0:8080/api/degree/1a9614ef-98ad-446e-9a3e-0096bb8e53bb" -H  "accept: application/json" -H  "x-user-id: 1a9614ef-98ad-446e-9a3e-0096bb8e53b6" -H  "Content-Type: multipart/formdata" -d "{  \"name\": \"FCPS\"}"```

If I try to send the request, my Go API server doesn't get the form data.

If I try using Postman, it works fine. Here's the postman generated curl command:
```curl --location --request PUT 'http://localhost:8080/api/degree/1a9614ef-98ad-446e-9a3e-0096bb8e53bb' --header 'x-user-id: cedd4473-a70c-4117-a87d-a2a68d249b0e' --form 'name=FCPS'```

It's completely different.

**Comment by hkosova** [comment]
Please post your API definition (YAML/JSON file).

Also, what version of Swagger UI do you use? (Open browser dev tools > Console tab > evaluate `versions`.)

**Comment by hkosova** [comment]
@cyantarek It's possible you're seeing [this bug](https://github.com/swagger-api/swagger-ui/issues/5740) which was fixed in Swagger UI v. 3.26.0. Please try the latest version.

Also make sure your multipart request is defined correctly. You can use https://editor.swagger.io to check for syntax errors.

OpenAPI 3.0:
```yaml
paths:
  /something:
    put:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
```
OpenAPI 2.0:
```yaml
paths:
  /something:
    put:
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: name
          type: string
```

**Comment by cyantarek** [comment]
Thanks, I ditched multipart-formdata with application/json.
