### ISSUE TITLE
Syntax highlighting does not work in OAS3 parameters

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#6240]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome latest
 - Method of installation: dist assets
 - Swagger-UI version: 3.30.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Objects in parameters
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  /get:
    get:
      parameters:
        - in: query
          name: params
          schema:
            type: object
            properties:
              foo:
                type: string
              bar:
                type: integer
      responses:
        '200':
          description: OK
```

### Describe the bug you're encountering
This is a follow-up to PR https://github.com/swagger-api/swagger-ui/pull/6236. The syntax highlighting feature added in that PR does not apply to object parameters in OAS3 definitions.

### To reproduce...
1. Create a gist containing the definition above and load it into https://petstore.swagger.io.
2. Expand the operation and see how the `params` parameter is displayed.

### Expected behavior
Code examples in parameters should use the same syntax highlighting as request/response bodies.

### Screenshots
![image](https://user-images.githubusercontent.com/8576823/87912286-c860e880-ca75-11ea-8415-16abc7093cfc.png)

**Comment by tim-lai** [comment]
PR https://github.com/swagger-api/swagger-ui/pull/7199 should resolve this issue.
