### ISSUE TITLE
Not able to execute request for multipart/form-data

### ISSUE THREAD

**Issue by vinaylondhe-highspot** [swagger-api/swagger-ui#6250]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Method of installation: dist
 - Swagger-UI version: 3.29.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
When multipart/form-data is selected as the Content-Type and a file is selected to be uploaded, nothing happens after clicking on `Execute`. The `Execute` button does not work at all. 

### To reproduce...

1. Go to swagger ui page
2. Select multipart/form-data as the Content-Type in the request body
3. Upload file to be sent in the request
4. Click on 'Execute'

### Expected behavior
The request should be made to the appropriate endpoint. Instead, the request is not made at all

**Comment by hkosova** [comment]
@vinaylondhe-highspot can you provide an OpenAPI definition to reproduce the issue?

**Comment by vinaylondhe-highspot** [comment]
@hkosova So I can confirm that I am able to execute the request just fine when I have something like 
```
   requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - filename
              properties:
                filename:
                  type: string
                  description: The file
                  format: binary
```

But when I have something like the below definition (basically when you can send either of multipart/form-data or application/json content for the same endpoint), I can confirm that the Execute button does not work
```
requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  description: The file
                  format: binary
          application/json:
            schema:
              $ref: '#/components/schemas/item-spec'
``` 

And I want to use this version because of this bug fix https://github.com/swagger-api/swagger-ui/pull/6223

**Comment by vinaylondhe-highspot** [comment]
And this is happening for the versions 3.29.0 and 3.30.0.

**Comment by tim-lai** [comment]
I believe that this issue has the same root cause as #6201. My [comment](https://github.com/swagger-api/swagger-ui/issues/6201#issuecomment-661258166)

**Comment by tim-lai** [comment]
@vinaylondhe-highspot Imo, it would be much better api design to have separate api endpoints for `multipart/form-data`. Then you would know to explicitly expect and handle various files, permissions, and security.

**Comment by vinaylondhe-highspot** [comment]
@tim-lai I agree that its a much better API design to have separate api endpoints. Unfortunately, I cannot do that right now since it will break our existing clients
