### ISSUE TITLE
When clicked, endpoint automatically moves under "default" tag.

### ISSUE THREAD

**Issue by sumitdhungana14** [swagger-api/swagger-ui#6252]
When an endpoint is clicked, it automatically moves under "default" tag.

![before](https://user-images.githubusercontent.com/25248164/88147352-c7b68680-cc1c-11ea-8b97-d3eabbc04e79.png)

 
Now, when an endpoint under "projects" tag is clicked, it is automatically moved under "default" tag.

![after](https://user-images.githubusercontent.com/25248164/88147385-d56c0c00-cc1c-11ea-85db-8c3b8978caab.png)

Everything was working fine until yesterday. Some changes had been made in yaml file and now this issue appears out of nowhere.

**Comment by mrkovalchuk** [comment]
Same issue. "default" with endless loader.
![image](https://user-images.githubusercontent.com/18255783/88151930-faa44e80-cc0b-11ea-9bb3-55192399536c.png)

**Comment by mrkovalchuk** [comment]
Looks like duplicate https://github.com/swagger-api/swagger-ui/issues/6249

**Comment by hkosova** [comment]
Closing as a duplicate of #6249.
