### ISSUE TITLE
Would like the ability to create code snippets in various languages using swagger-ui-react

### ISSUE THREAD

**Issue by johnwhitton** [swagger-api/swagger-ui#6256]
### Content & configuration

Swagger/OpenAPI definition:
[emasset.api.v1.swagger.json.txt](https://github.com/swagger-api/swagger-ui/files/4963000/emasset.api.v1.swagger.json.txt)

 Swagger-UI configuration options:
 
[swagger.js.txt](https://github.com/swagger-api/swagger-ui/files/4963011/swagger.js.txt)

### Is your feature request related to a problem?
Would like the ability to create code snippets in various languages using swagger-ui-react.

### Describe the solution you'd like
I would like to be able to use swagger-ui to create code examples in various languages.
Ideally this could be configured using extensions in the openapi document and would be displayed via swagger-ui-react.
As an example you can see [this document](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-audit-records/#api-rest-api-3-auditing-record-get) 
<img width="843" alt="Screen Shot 2020-07-22 at 3 34 37 PM" src="https://user-images.githubusercontent.com/1572027/88235996-e4f55000-cc30-11ea-9f76-e7f425aa85a1.png">

Having a look at this functionality it appears to have been built as follows
* [readme.com](https://readme.com/) leverages [api extensions](https://docs.readme.com/guides/docs/openapi-extensions)
* Specifically you can set the following in your swagger.json
```
  "x-samples-enabled": true,
  "x-samples-languages": ["curl", "node", "ruby", "javascript", "python","go","c"],
```
* This then leverages [httpsnippet](https://www.npmjs.com/package/httpsnippet)

### Describe alternatives you've considered
Currently we're using 
* [docusarus](https://docusaurus.io/)
* And creating a page using [swagger-ui-react](https://www.npmjs.com/package/swagger-ui-react)
* Also have done some initial investigation into [api](https://www.npmjs.com/package/api)

### Additional context
I'd like to thank and send encouragement to the team for building out this highly useful software.
It looks like a number of teams are using this in conjunction with [docusarus](https://docusaurus.io/)
Some of which are running into [this build issue](https://github.com/swagger-api/swagger-ui/issues/6136)

**Comment by mathis-m** [comment]
With this PR #6910 the cURL part is already refactored to the style shown here.
