### ISSUE TITLE
Send byte data as POST request body

### ISSUE THREAD

**Issue by hansbretscher** [swagger-api/swagger-ui#6257]
### Q&A (please complete the following information)
 - OS: Linux, Windows
 - Browser: Firefox 76.0.1 (64-Bit), Chromium 83.0.4103.116
 - Method of installation: came with 'pip install fastapi'
 - Swagger-UI version: 3.30.0
 - Swagger/OpenAPI version: fastapi 0.60.1

### How can we help?
My requires a request body sent as a binary string. Is it possible to send a request like that with swagger-ui?
I see two methods to send a body, one as a JSON construct, one as form-field. But I do not see an option to send binary data 'as is' in the request body. Am I missing something?
It would be ideal if the automatically generated openapi.json could generate such a field from my interface description. As it does with header fields. But I could customize that file by hand. If openapi has the required option for that.

**Comment by hkosova** [comment]
OpenAPI 3.0 Specification supports binary request bodies:
```
openapi: 3.0.0

paths:
  /something:
    post:
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
```
Since you use a library (FastAPI) to generate the API definition, please refer to that library's documentation to see if it has a way to generate such definition.
