### ISSUE TITLE
Parameter objects at the same level as "get" or "post" are not taken into account when the data underneath a path is taken from another file.

### ISSUE THREAD

**Issue by SSchwaiger** [swagger-api/swagger-ui#6260]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: current
 - Method of installation: Springdoc
 - Swagger-UI version: org.webjars.swagger-ui: 3.30.1-SNAPSHOT
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

openapi.yaml:
```yaml
openapi: '3.0.3'
info:
  title: API
  version: '0.1.0'
servers:
  - url: https://api.server.test/v1

tags:
  - name: Account
    description: Login/-out

paths:
  /sessions/{session-id}:
    $ref: 'del.yaml#/del'
```

del.yaml:
```yaml
del:
  parameters:
    - name: session-id
      in: path
      description: Session-Id, die beim Login vergeben wurde
      required: true
      schema:
        type: string
  delete:
    description: Logout
    operationId: logout
    tags:
      - Account
    responses:
      default:
        description: Logout war erfolgreich
```

### Describe the bug you're encountering
The UI shows the DELETE of the path having no parameters - but as far as I understand the spec, moving the parameters to the same level as "delete" is valid.

### Expected behavior
The DELETE operation shows the "global" parameters and the "Try it out" feature allows me to specify a value.

### Additional context or thoughts
If I embed the code from del.yaml directly in openapi.yaml it works fine.

**Comment by hkosova** [comment]
Thanks for the report! This issue is tracked in #5667 so I'll close this one as a duplicate.
