### ISSUE TITLE
Swagger UI shows empty page - How to fix?

### ISSUE THREAD

**Issue by SetTrend** [swagger-api/swagger-ui#6262]
I added Swashbuckle.AspNet.Core to my repository and initialized everything using the default values.

Although I can see JSON output from `/swagger/v1/swagger.json` opening `/swagger/index.html` just yields an empty page.

Why?

<br/>

[![enter image description here][1]][1]

<br/>
<hr/>

### Here's my code

```c#
public void ConfigureServices(IServiceCollection services)
{
  services
    .AddSwaggerGen()
    .AddControllers()
    ;
}

// This method gets called by the runtime once. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, Options options)
{
  if (env.IsDevelopment()) app.UseDeveloperExceptionPage();

  app
    .UseHttpsRedirection()
    .UseRouting()
    .UseAuthorization()
    .UseEndpoints(endpoints => endpoints.MapControllers())
    .UseSwagger()
    ;

  if (env.IsDevelopment()) app.UseSwaggerUI();
}
```

  [1]: https://i.stack.imgur.com/AUHZL.png

**Comment by hkosova** [comment]
Please open an issue with Swashbuckle:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues

**Comment by SetTrend** [comment]
@hkosova :

This may need your opiniont:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1756#issuecomment-666589659

Please have a look there.
