### ISSUE TITLE
Swagger UI documentation Required Properties

### ISSUE THREAD

**Issue by daymar23** [swagger-api/swagger-ui#6263]
Hello!!

 I am trying to create more documentation in some APIs, 

1. I want to change the optional field to a required field.

![image](https://user-images.githubusercontent.com/68713491/88432870-498fe680-cdba-11ea-98cd-7aa3c8d98aa2.png)

But when I add the DataAnnotations [Required] in a property, swagger returns me a 500 error. 

![image](https://user-images.githubusercontent.com/68713491/88432739-06ce0e80-cdba-11ea-827f-c414a56bb76d.png)

![image](https://user-images.githubusercontent.com/68713491/88433017-8956ce00-cdba-11ea-8749-f06a7f43fa93.png)

I read from a lot of documentation and this is supposed to work

Could somebody help me please?

**Comment by hkosova** [comment]
This looks like an issue with the .NET library that you use to include Swagger UI in your app. Please open an issue with that library.

Swashbuckle: https://github.com/domaindrivendev/Swashbuckle/issues
Swashbuckle.AspNetCore: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues
Swagger-Net: https://github.com/heldersepu/Swagger-Net/issues
