### ISSUE TITLE
Swagger Edtior Post Request Example: 😱 Could not render n, see the console

### ISSUE THREAD

**Issue by DesHorsley** [swagger-api/swagger-ui#6268]
I'm having trouble rendering an example request body in openapi. I've distilled it down to this simple example:

    openapi: 3.0.2
    info:
    title: Test
    version: "1"
    paths:
    /Users:
        post:
        requestBody:
            content:
            application/json:
                example: 
                name: "John"
                
        responses:
            "200":
            description: Fetches them
            content:
                application/json:
                example:
                    - name: John Doe
                

All I get is:

😱 Could not render n, see the console.

Although, the response body renders fine as expected.

If I add 

          schema:
          type: object

Then the the example is displayed as expected. 

Is schema supposed to be required to display the example, its confusing that it works for the response with out it. 

This question was asked and answered here: https://stackoverflow.com/questions/63110319/swagger-edtior-post-request-example-could-not-render-n-see-the-console

**Comment by omgitsaheadcrab** [comment]
I get this error even when a schema is defined, albeit a reference to one.

**Comment by damian-polewski-sb** [comment]
Hi everyone, 
This issue was already solved in this release: https://github.com/swagger-api/swagger-ui/releases/tag/v5.3.2
