### ISSUE TITLE
Simple type as request body does not display input/textbox

### ISSUE THREAD

**Issue by smarts** [swagger-api/swagger-ui#6269]
### Q&A (please complete the following information)
 - OS: macOS Catalina 10.15.6 (19G73)
 - Browser: Firefox
 - Version: 78.0.2 64-bit
 - Method of installation: embedded in [this NuGet package](https://www.nuget.org/packages/Swashbuckle.AspNetCore/5.0.0)
 - Swagger-UI version: 3.24.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### Content & configuration
?

Swagger/OpenAPI definition:
?

Swagger-UI configuration options:
?

### Screenshots
![Screen Shot 2020-07-27 at 23 38 57](https://user-images.githubusercontent.com/1002257/88628315-9bf33080-d062-11ea-8f47-8b33751e0fc0.png)

### How can we help?
No input/textbox is displayed for my request bodies that are simple integers (as opposed to an object).
Please let me know if this is a bug in this project or in the aforementioned NuGet package that uses this project.

**Comment by hkosova** [comment]
Please post an API definition (YAML/JSON file) that demonstrates the issue.

**Comment by smarts** [comment]
I apologize, the input is there and this was user [AKA my] error. I'll look into whether a separate issue is warranted for the type of input that is displayed. Thanks for the quick response!
