### ISSUE TITLE
swagger-ui-react crashes when built with parcel-bundler since inclusion of react-syntax-highlighter

### ISSUE THREAD

**Issue by fabiradi** [swagger-api/swagger-ui#6285]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 78
 - Method of installation: yarn + parcel-bundler
 - Swagger-UI version: 3.31.1 (React)
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
(UI does not load at all)

Swagger-UI configuration options:
```js
import SwaggerUI from 'swagger-ui-react'
import 'swagger-ui-react/swagger-ui.css'

<SwaggerUI docExpansion="list" defaultModelExpandDepth={10} spec={/* YAML data */} />
```

### Describe the bug you're encountering
The React **application crashes** after updating to the version that includes `react-syntax-highlighter`. The browser does not show anything other than an error in the console.

```
Uncaught (in promise) Error: Cannot find module '../../../../node_modules/refractor/lang/markup.js'
    at newRequire (swagger.8783f1c7.js:37)
    at newRequire (core.4d163a5a.js:29)
    at newRequire (refractor.0f505be5.js:29)
    at newRequire (core.4d163a5a.js:21)
    at localRequire (core.4d163a5a.js:53)
    at Object.parcelRequire.../../../../node_modules/refractor/core.js.hastscript (core.4d163a5a.js:2484)
    at newRequire (core.4d163a5a.js:47)
    at newRequire (refractor.0f505be5.js:29)
    at newRequire (swagger.8783f1c7.js:21)
    at localRequire (swagger.8783f1c7.js:53)
```

The missing point seems to be `refractor`, which leads to **issues with `react-syntax-highlighter` and `parcel-bundler`**:

- react-syntax-highlighter: [Runtime error (missing node module) when using ParcelJS #180](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/180)
- parcel-bundler: [Cannot find module '../node_modules/refractor/lang/markup.js' #3176](https://github.com/parcel-bundler/parcel/issues/3176)

### To reproduce...

1. Run `parcel src/doc/swagger.html``
2. Open http://localhost:1234 in the browser
3. Open the developper console (CTRL-ALT-C)
4. See tab **console**

### Expected behavior
SwaggerUI-react build as in the previous version did. 

### Additional context or thoughts
I tried installing `refractor`, but it did not change anything.

**Comment by tim-lai** [comment]
@fabiradi @penghaizhang Thanks for the issue report. The most recent release of swagger-ui-react based on swagger-ui [v3.32.1](https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.1) may resolve this issue. Specifically, using swagger-ui-react's new es2015 module may help with dependency resolution. Also, fyi, swagger-ui does not actually use `refractor` within `react-syntax-highlighter`.

**Comment by fabiradi** [comment]
🤷‍♂️ Sorry, the problem is still there. I could no see any difference. The error is still the same, although I was hoping that the ES2015 module would solve the problem.

I also use `react-syntax-highlighter` in my project and had to change the _general_ import to a more specific one (importing the ES2015 module directly?) to get it working as described in an [issue](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/216):

If you change https://github.com/swagger-api/swagger-ui/blob/14278e83dc1e1282b5d1b36fb5da9c335cc6e64f/src/core/syntax-highlighting.js#L1

to this
```javascript
// import { Light as SyntaxHighlighter } from "react-syntax-highlighter" 
import SyntaxHighlighter from 'react-syntax-highlighter/dist/esm/light'
```

it should work.

⚠️ I would **not** recommend changing the import _just_ for parcel. There has to be a solution that would work for everyone.

**Comment by tim-lai** [comment]
@fabiradi [swagger-ui@3.32.3](https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.3) properly includes the es2105 module I was referring to. If you could give it one more try, I would like to know the result. If it still doesn't work, it might be a problem with Parcel interpreting imports from `react-syntax-highlighter`, in which case I recommend creating an issue with `react-syntax-highlighter`

**Comment by PenghaiZhang** [comment]
> @fabiradi [swagger-ui@3.32.3](https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.3) properly includes the es2105 module I was referring to. If you could give it one more try, I would like to know the result. If it still doesn't work, it might be a problem with Parcel interpreting imports from `react-syntax-highlighter`, in which case I recommend creating an issue with `react-syntax-highlighter`

Thanks @tim-lai  swagger-ui@3.32.3 does fix the problem!
