### ISSUE TITLE
Authorization Flow w/PKCE asks for Client Secret

### ISSUE THREAD

**Issue by FizzBuzz791** [swagger-api/swagger-ui#6290]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84
 - Method of installation: Swashbuckle
 - Swagger-UI version: 3.26
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### Content & configuration

Any API with Authorization Flow and PKCE enabled.

I'm using DotNet Core and Swashbuckle, so it's a little hard to provide anything here.

### Describe the bug you're encountering

The Authorize UI still prompts for the Client Secret even though it's not required for the PKCE flow.

### To reproduce...

1. Click on 'Authorize'
2. See 'client_secret' field is shown (empty)
  a. Passing any value (valid or not) in that field and clicking 'Authorize' will cause an error.
  b. Leaving the field blank, will cause the auth flow to work correctly.

### Expected behavior
When 'UsePKCE' flag is enabled, Client Secret field is not shown.

### Screenshots
![image](https://user-images.githubusercontent.com/2747764/89612656-ebcbc600-d8b2-11ea-8776-276c19ef170a.png)

**Comment by FinHorsley** [comment]
+1 for this. It would be ideal if the `client_secret` input field was hidden in this case with Authorisation Code Flow + PKCE

**Comment by airen29** [comment]
+1 also. If you have `Auth flow + PKCE` you can basically put everything in the `client_secret` field now and it will be override so what is the purpose to have that field there anyway?

**Comment by ch-egli** [comment]
+1 as well.

**Comment by ch-egli** [comment]
May I address this issue with a small pull-request that omits the `client_secret` field from the OAuth2 dialog when the parameter `usePkceWithAuthorizationCodeGrant` is set to true? Or do you first need a further analysis of the issue?

**Comment by arturciesielskisteelseries** [comment]
Hi there,

I've just encountered this issue and I don't know what to think.

OAuth2 still recommends using both the client secret and PKCE in conjunction for confidential clients, as using a secret does not prevent the same class of vulnerabilities as PKCE.

A lot of top Google search results for OAuth2 and PKCE mention that those two are not replacements for each other:

https://oauth.net/2/pkce/
https://www.oauth.com/oauth2-servers/pkce/

Why have those been treated as mutually exclusive when they are not?

**Comment by OFark** [comment]
I am shocked by this, Confidential clients use both PKCE and ClientSecret, PKCE is not a replacement for a client_secret, a white list of redirect URLs is. I still need an input for Client Secret, Swagger is useless to me without it. Have the option to toggle it, sure, and have it change behaviour when it's empty sure. But to reduce the security of an API because 6 people find having the box shown mildly irritating seems ridiculous.
