### ISSUE TITLE
Configure scheme in docker container

### ISSUE THREAD

**Issue by enfoqueNativo** [swagger-api/swagger-ui#6293]
### Q&A (please complete the following information)
 - OS: Xubuntu 19.10
 - Browser: Firefox
 - Version: 78.0.2
 - Method of installation: docker container
 - Swagger-UI version: 3.32.5
 - Swagger/OpenAPI version: Swagger 2.0

### Screenshots
![swagger-wrong2](https://user-images.githubusercontent.com/12297079/90076644-a6eec780-dcd6-11ea-81ff-f38aea6c8e32.png)

### How can we help?

As seen in the picture swagger-ui isn't respecting url's scheme, you load the json via http scheme, but swagger insists using https scheme when trying out.

Is it some way to configure swagger container? or scheme should be forced in the json definition?

Regards

**Comment by qixiang-liu** [comment]
Have you solved it?

**Comment by enfoqueNativo** [comment]
> Have you solved it?

Yes, forcing it through `schemes` in Swagger Object for OpenApi 2.0 seems to work.
