### ISSUE TITLE
Validate server responses against schema

### ISSUE THREAD

**Issue by mknj** [swagger-api/swagger-ui#6299]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
 # no additions
 ```

 Swagger-UI configuration options:
 ```js
 SwaggerUI({
   validateServerResponses:true # default false
 })
 ```

### Is your feature request related to a problem?
  "I'm always frustrated when I test a server and the response does not match the provided schema"

### Describe the solution you'd like
The swagger UI should highlight differences between the specification and the actual response.

### Describe alternatives you've considered
Additionally i am experimenting with extracting the schema from the specifications and use them in automated testing.
Having automated tests is clearly a better approach, but in cases without automated testing the validation inside swagger UI would be really helpful.

### Additional context

We have the model definition and validators why not use them?

**Comment by mknj** [comment]
related to #2605

**Comment by tim-lai** [comment]
@mknj SwaggerUI would not know the source of truth of between a schema and server response. As noted in the related issue, it is not a feature SwaggerUI would support.
