### ISSUE TITLE
Depending on the SwaggerUI server, the full list of response headers is not shown.

### ISSUE THREAD

**Issue by shookmon** [swagger-api/swagger-ui#6306]
### Q&A (please complete the following information)
 - OS: Win10
 - Browser: Firefox (and others)
 - Version: 79
 - Method of installation: https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js
 - Swagger-UI version: unknown, assumed to be latest
 - Swagger/OpenAPI version: OpenAPI 3.0.3

### Content & configuration

How you can see this is by trying the entries in this matrix:

| Swagger UI Host | Schema Source | SwaggerUI x-api... |
|-----------------|---------------|--------------------|
| localhost       | swaggerHub    | missing            |
| localhost       | ninja         | missing            |
| localhost       | com           | missing            |
| localhost       | local         | missing            |
| ninja           | swaggerHub    | missing            |
| ninja           | ninja         | missing            |
| ninja           | com           | missing            |
| ninja           | local         | missing            |
| com             | swaggerHub    | shown              |
| com             | ninja         | shown              |
| com             | com           | shown              |
| com             | local         | shown              |
| swagger.io      | swaggerHub    | missing            |
| swagger.io      | ninja         | missing            |
| swagger.io      | com           | missing            |
| swaggerHub      | swaggerHub    | shown              |

localhost = win10: python serve 
ninja = https://toolbox.omegatower.ninja/tryuispa.html : AWS S3 Website / CloudFront stack
com = https://toolbox.omegatower.com/tryuispa.html : LAMP server at Ionos with no CDN
swagger.io = https://petstore.swagger.io/ : unknown server stack
swaggerHub = https://app.swaggerhub.com/apis-docs/OTDP/Toolbox/1.2.0.13 : unknown server stack

Swagger/OpenAPI definition:

local = ../oas/swagger.json
ninja = https://toolbox.omegatower.ninja/oas/swagger.json
com = https://toolbox.omegatower.com/oas/swagger.php
swaggerHub = https://api.swaggerhub.com/apis/OTDP/Toolbox/1.2.0.13/swagger.json

Swagger-UI configuration options:
```js
SwaggerUIBundle({
    "dom_id": "#swagger-ui",
    deepLinking: true,
    presets: [
    SwaggerUIBundle.presets.apis,
    SwaggerUIStandalonePreset
    ],
    plugins: [
    SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout",
    validatorUrl: "https://validator.swagger.io/validator",
    //url: "https://api.swaggerhub.com/apis/OTDP/Toolbox/1.2.0.13/swagger.json"
    urls: [
        {
            url: "https://api.swaggerhub.com/apis/OTDP/Toolbox/1.2.0.13/swagger.json",
            name: "SwaggerHub"
        },
        {
            url: "https://toolbox.omegatower.ninja/oas/swagger.json",
            name: "ninja"
        },
        {
            url: "https://toolbox.omegatower.com/oas/swagger.php",
            name: "com"
        },
        {
            url: "../oas/swagger.json",
            name: "local"
        }
    ]
})
```

```
?yourQueryStringConfig
none
```

### Screenshots

**headers good**
![headers_good](https://user-images.githubusercontent.com/69769427/90343851-5a5f0100-dfe2-11ea-86a2-88f78f4969f0.png)

**headers bad**
![headers_bad](https://user-images.githubusercontent.com/69769427/90343856-5fbc4b80-dfe2-11ea-9799-7211cc821a57.png)

**Firefox Network**
![firefox_network](https://user-images.githubusercontent.com/69769427/90343844-50d59900-dfe2-11ea-8c26-43e79f111db3.png)

### How can we help?

Depending on the SwaggerUI server, the full list of response headers is not shown.

As you can see from above, only 4 headers are shown some of the time, but all headers are shown the rest of the time.
I looked through the bugs to see if this had already been noted, but in those cases it seemed to either be an unrelated issue or when things were weird, it was ALWAYS weird.
Those don't seem to match my results where some times it's OK, and other times it's not.

In all cases, Firefox Network inspector shows that the CORS header and the full list of headers is in the reponse header from the resource.

This is especially important in my use case as the x-api... custom headers are needed.

At this point I'm am not sure where the problem really lies. But, since swagger.io and SwaggerHub give different results as well, I think it's somehow internal to the SwaggerUI script and how it resolves the response from the resource.

My ultimate goal is to get the S3/CloudFront stack working, as I am trying to transition there away from the LAMP at Ionos. I am less concerned if the localhost gives "unique" results. 

Any help resolving this issue would be appreciated.

Thanks!!

Michael D. Shook | https://Mike.OmegaTower.com | Mike@OmegaTower.com

**Comment by hkosova** [comment]
See if this helps:
https://github.com/swagger-api/swagger-ui/issues/3340#issuecomment-313550973
https://github.com/swagger-api/swagger-ui/issues/4576#issuecomment-390783413

**Comment by shookmon** [comment]
*forehead slap*
"It's not the **access**, it's the **ACCESS**!!!"

My first response to hkosova was going to be " **whine** but I AM sending those headers when the .json is retreived... **whine**"

And then it hit me, I've been so focused on getting CORS correct to be able to retrieve the schema from where it's located for testing, I TOTALLY forgot that the API also has to have CORS set correctly so that it will work as expected.

I've spent two days trying to figure what I was missing. Thanks hkosova!!!!! your 5 minute fix is the answer.

Summary:

* The specification file has to have CORS set correctly so that SwaggerUI can read it.
* The API has to have CORS set correctly so that SwaggerUI can properly use it and display it.

Thanks again!

-mike
