### ISSUE TITLE
testing an array in multipart/form-data and application/json got difference result

### ISSUE THREAD

**Issue by FauzanAr** [swagger-api/swagger-ui#6311]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84.0.4147.125
 - Method of installation: npm
 - Swagger-UI version: 4.1.4
 - Swagger/OpenAPI version: OpenAPI 3

### Describe the bug you're encountering

When i create endpoint documentation i try to use 2 requestBody method using 'application/json' and 'multipart/form-data'. it run correctly when i use application/json with same schema but it caused error when i use multipart/form-data with same configuration of schma, i don't know why because i've set same configuration for those 2 requestBody method
### To reproduce...

1. Sending data with multipart/form-data

### Expected behavior

Both using 'application/json' or 'multipart/form-data' sending data and caught by beckend

### Screenshots
1. This is while i test using 'application/json' with same configuration like 'multipart/form-data'
![Application/json test](https://i.ibb.co/XJ0qfst/1.png)
And this is how backend see the link property
![Backend result](https://i.ibb.co/HXfr4pY/5.png)

2. This is while i test using 'multipart/form-data'
![Multipart/form-data](https://i.ibb.co/7SJgJdk/3.png)
And this is how my backend receive undefined value from it's request
![Backend receive undefined](https://i.ibb.co/XXxsxSK/4.png)

**Comment by tim-lai** [comment]
@FauzanAr There exists an issue in SwaggerUI where one cannot have both `multipart/form-data` with a different `contentType` in the same endpoint. Marking as duplicate.
