### ISSUE TITLE
"😱 Could not render n, see the console." when providing nested lists.

### ISSUE THREAD

**Issue by reder9** [swagger-api/swagger-ui#6326]
**Environmental information**:
I'm running this out of the `swaggerapi/swagger-ui:v3.32.2` image 
Using `"openapi": "3.0.3",`

**Problem:**
I have the following parameter that I would like to display in my swagger api doc page. The first one displays fine since its a simple list but the second has problems since it is a nested list:
```
      "parameters": [
          {
            "name": "simple_list",
            "in": "query",
            "description": "Just a list of ints",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
               "type": "integer",
               "format": "int32"
               }
             }
          },
          {
            "name": "nested_list",
            "in": "query",
            "description": "List of list of ints",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
               "type": "array",
               "items": {
                  "type": "integer",
                  "format": "int32"
               }
              }
            }
          }
        ],
```

As seen in this screenshot when I try to add an element to the nested lists I get `😱 Could not render n, see the console.`
![Screen Shot 2020-08-19 at 10 40 59 AM](https://user-images.githubusercontent.com/11050179/90657854-7e9c2700-e208-11ea-8357-8910db307960.png)

From what I can see I'm providing the nested array properly according to https://swagger.io/docs/specification/data-models/data-types/

Please let me know if theres any other information I can provide

**Comment by acote-coveo** [comment]
@reder9 You probably have console errors that you could share here :)

**Comment by swasical** [comment]
Any resolution on this? I have the same error. The console error I see is:

swagger-ui-bundle.js:2 TypeError: a.getIn is not a function
    at n.value (swagger-ui-bundle.js:2)
    at n.I.t.render (swagger-ui-bundle.js:2)
    at u._renderValidatedComponentWithoutOwnerOrContext (swagger-ui-bundle.js:2)
    at u._renderValidatedComponent (swagger-ui-bundle.js:2)
    at u._updateRenderedComponent (swagger-ui-bundle.js:2)
    at u._performComponentUpdate (swagger-ui-bundle.js:2)
    at updateComponent (swagger-ui-bundle.js:2)
    at u.receiveComponent (swagger-ui-bundle.js:2)
    at Object.receiveComponent (swagger-ui-bundle.js:2)
    at Object.updateChildren (swagger-ui-bundle.js:2)

**Comment by mathis-m** [comment]
valid minimal reproduction yaml:
https://editor.swagger.io/?url=https://gist.githubusercontent.com/mathis-m/24e22a3e1f2f6e82cf0f9987f49f3ffc/raw/195c45acd7fbc172bbc55d2ab8be8add223ac5ec/KgSeOGeGyq.txt
```yaml
openapi: 3.0.3
info:
  title: asd
  version: 0.0.1
paths:
  /test:
    get:
      parameters:
      - name: simple_list
        in: query
        description: Just a list of ints
        required: false
        schema:
          type: array
          items:
            type: integer
            format: int32
      - name: nested_list
        in: query
        description: List of list of ints
        required: false
        schema:
          type: array
          items:
            type: array
            items:
              type: integer
              format: int32

      responses:
        200:
          description: ok
```
