### ISSUE TITLE
swagger-ui npm module has not dist/index.html

### ISSUE THREAD

**Issue by Kin9Jon9** [swagger-api/swagger-ui#6339]
Swagger-ui was installed through npm to proceed with the project.

However, 'node_modules/swagger-ui/dist/index.html' did not exist.

Not only in the local environment, but also in the cloud environment.

Was it my mistake? Is it a problem with npm?

**Comment by tim-lai** [comment]
@Kin9Jon9 Using npm to install swagger-ui as its own project will include `dist/index.html` in the project directory. If you are trying to use swagger-ui as a module, you need to import and configure it, per the docs: https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation/
