### ISSUE TITLE
Markdown not rendered

### ISSUE THREAD

**Issue by Salubrio** [swagger-api/swagger-ui#634]
Markdown in the descriptions is not rendered in Swagger-UI, even though it is rendered in the Swagger online editor.

* Swagger editor:

![schermafbeelding 2014-10-02 om 14 10 23](https://cloud.githubusercontent.com/assets/2655392/4490540/369a7f2a-4a2d-11e4-9466-68d3418ebeb9.png)

* Swagger-UI:

![schermafbeelding 2014-10-02 om 14 10 46](https://cloud.githubusercontent.com/assets/2655392/4490544/3e928f92-4a2d-11e4-9582-89e36b7f0c8f.png)

**Comment by webron** [comment]
Implemented with #824.
