### ISSUE TITLE
When using $ref: file.yml on paths Schema tab is not shown

### ISSUE THREAD

**Issue by javiercbk** [swagger-api/swagger-ui#6342]
### Q&A (please complete the following information)
 - OS: linux
 - Browser: chrome
 - Version: 85.0.4183.83 (Official Build) (64-bit)
 - Method of installation: npm dist assets
 - Swagger-UI version: "swagger-editor-dist": "^3.12.0",
 - Swagger/OpenAPI version: 3.0.0

### Content & configuration
```javascript
const path = require('path');
const express = require('express');
 
const pathToSwaggerUi = require('swagger-ui-dist').absolutePath();

const app = express();

app.use(express.static(pathToSwaggerUi));
// api folder contains api.yml and endpoint.yml
app.use('/api', express.static(path.join(__dirname, 'api'), {
    etag: false
}));

app.listen(3000);
```

Example Swagger/OpenAPI definition:
The following file shows the schema tab

full.yml
```yaml
openapi: 3.0.0

info:
  title: API
  description: API
  version: "1.0.0"

servers:
  - url: https://api.com/v1
    description: Production

components:
  schemas:
    A:
      type: object
      required:
        - a
      properties:
        a:
          type: string

paths:
  /endpoint:
    post:
      tags:
        - User
      summary: Summary.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/A'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/A'
```

Importing an endpoint as **$ref** will fail to show the schema tab

partial.yml
```yaml
openapi: 3.0.0

info:
  title: API
  description: API
  version: "1.0.0"

servers:
  - url: https://api.com/v1
    description: Production


paths:
  /endpoint:
    $ref: './endpoint.yml'
```

endpoint.yml
```yml
components:
  schemas:
    A:
      type: object
      required:
        - a
      properties:
        a:
          type: string

post:
  tags:
    - User
  summary: Summary.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/A'
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/A'
```

Swagger-UI configuration options:
The UI config is not changed. The script provided in the **Content & configuration** section will produce the exact config as mine

### Describe the bug you're encountering
When using a **$ref** in the path, the endpoint is shown as part of the API but the schema tab is not being shown. When using a single file approach, the schema tab is shown.

### To reproduce...

- Copy the script I've provided in the Content & configuration into a folder
- run `npm init` in the script's folder
- run `npm install express swagger-ui-dist --save` in the script's folder
- run `node index.js` in the script's folder
- create an `api` folder inside the script's folder create the `full.yml`, `partial.yml` and `endpoint.yml` provided in the **Example Swagger/OpenAPI definition** section
- open a browser at localhost:3000 and swagger UI will be shown
- load the following URL in swagger UI `http://localhost:3000/api/full.yml`. The Schema tab will be shown
- load the following URL in swagger UI `http://localhost:3000/api/partial.yml`. The Schema tab will be NOT be shown

### Expected behavior
When using a **$ref: file.yml** in the **paths** property, the schemas used in the imported endpoints should be shown in the Schema Tab

### Screenshots
![2020-08-27-112237_1503x731_scrot](https://user-images.githubusercontent.com/1448426/91454807-c13caf80-e857-11ea-9453-7c6b6e425193.png)
![2020-08-27-112256_1509x586_scrot](https://user-images.githubusercontent.com/1448426/91454823-c4d03680-e857-11ea-8ba8-8af47c3d200e.png)
![2020-08-27-112541_1503x841_scrot](https://user-images.githubusercontent.com/1448426/91455133-18db1b00-e858-11ea-8c44-20975c8c9a21.png)

### Additional context or thoughts
Notice that the endpoint is detected and the request and response is correctly mapped. But the schema tab may be trying to resolve schemas from within the context of the main file, which would be an error

**Comment by hkosova** [comment]
Related (or duplicate): #5318

**Comment by javiercbk** [comment]
Sorry...I'll comment on that ticket
