### ISSUE TITLE
How do I disable expand/collapse on tags and operations

### ISSUE THREAD

**Issue by davidjstewart** [swagger-api/swagger-ui#6347]
We are using the latest npm version of swagger-ui in our frontend app. We have some familiarity with customising its experience via the plugins. Does anyone know if it is possible to disable the expand/collapse functionality on the operations and/or tags via the plugin api? I.e. we want everything to be permanently expanded

**Comment by debargharoy** [comment]
If I'm getting you right, what you mean to say is the person viewing the Swagger UI should not be able to collapse the tag/endpoint.

If so, I guess that'll be a bad idea as when your number of APIs increase, you'll end up scrolling a lot more than expected which is bad from a User's perspective.

**Comment by davidjstewart** [comment]
We have implemented a left menu by way of the plugin, I.e. using wrapcomponent. Thus we don’t necessarily need the collapse operation feature

**Comment by tim-lai** [comment]
@davidjstewart You can use the `docExpansion` config option when loading SwaggerUI. https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
