### ISSUE TITLE
UI won't load properly, if configUrl returns an empty array

### ISSUE THREAD

**Issue by VasilVasilev93** [swagger-api/swagger-ui#6350]
Using OpenAPI 3.0 and the master version of swagger-ui.
### Content & configuration

Swagger-UI configuration options:
```js
     SwaggerUIBundle({
		configUrl: location.protocol + "//" + window.location.host + "/swagger/config.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
```

What I expect to happen is get the default page with no OpenAPI definitions found, but instead I get 
😱 Could not render n, see the console.
What happens if I pass non-empty array, is that the UI loads properly and displays the definitions passed.

Return empty array from configUrl's url

### Screenshots
![screenshot-swagger](https://user-images.githubusercontent.com/8179335/91711673-eea69780-eb8e-11ea-8aa0-97ae7ee444f3.png)

![swagger-2](https://user-images.githubusercontent.com/8179335/91711802-34636000-eb8f-11ea-95fd-484b27a3a763.png)

Is this a bug, and how should I workaround it?

**Comment by tim-lai** [comment]
@VasilVasilev93 `configUrl` is expected to be of type String

**Comment by VasilVasilev93** [comment]
@tim-lai configUrl is of type String it's value is "http://localhost:8080/swagger/config.json", which is an endpoint on the server and returns list of urls, which if not empty results in proper page load and openApi definitions load, but if result is an empty array of urls: urls:[], then this error happens.
