### ISSUE TITLE
"Cannot read property 'getScrollToKey' of undefined" when displaying the model of a request

### ISSUE THREAD

**Issue by Kenan13** [swagger-api/swagger-ui#6360]
> In Chrome, the error is:
> 
> ```
> Uncaught TypeError: Cannot read property 'getScrollToKey' of undefined
>     at model-collapse.jsx:69
>     at ReactRef.js:18
>     at Object.o.attachRefs (ReactRef.js:40)
>     at $.o (ReactReconciler.js:21)
>     at e.notifyAll (CallbackQueue.js:74)
>     at p.close (ReactReconcileTransaction.js:78)
>     at p.closeAll (Transaction.js:207)
>     at perform (Transaction.js:154)
>     at y.perform (Transaction.js:141)
>     at y.perform (ReactUpdates.js:87)
> ```
> 
> This issue also prevents nested models from being expanded.
> 
> Steps to reproduce:
> 
> 1. Open https://petstore.swagger.io.
> 2. Open the browser dev toops > Console tab.
> 3. Scroll down to the Models section.
> 4. Expand the "Pet" model.
> 5. Try to expand the `photoUrls` or `tags` subschemas, or the enum of the `status` property.
> 
> Expected results: Subschemas and enums are expanded.
> 
> Actual result: Subschemas and enums are NOT expanded.

Hi all,

Hi. I am still having this issue in swagger-ui-express. :(

Is there actually a connection between this repository and the swagger-ui-express repository?

_Originally posted by @Kenan13 in https://github.com/swagger-api/swagger-ui/issues/6305#issuecomment-686337314_

**Comment by tim-lai** [comment]
@Kenan13 In the latest version of swagger-ui & petstore.swagger.io, I am unable to reproduce. `swagger-ui-expresss is a separate project with a different maintainer. If you are still experiencing this issue, please contact them. Thanks.
