### ISSUE TITLE
Button "Choose file" missed if type byte

### ISSUE THREAD

**Issue by alex-pancho** [swagger-api/swagger-ui#6361]
If I create:

```
     requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                base64Image:
                  type: string
                  format: binary
```
I can see button "Choose file" in swagger UI

but when I use
 ```
    requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                base64Image:
                  type: string
                  format: byte
```
button "Choose file" has missed

**Comment by tim-lai** [comment]
@alex-pancho  according to the OpenAPI spec, you should be using` type: string, format: base64`, or `type: string, format: binary` for file uploads. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#considerations-for-file-uploads
