### ISSUE TITLE
Render the detailed structure of the objects of the arguments

### ISSUE THREAD

**Issue by Ninroot** [swagger-api/swagger-ui#6364]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
---
openapi: 3.0.2
info:
  title: API for role test
  description: API for role test
  version: 0.1.0
paths:
  /tasks/test:
    post:
      requestBody:
        description: Using requestbody allows swagger ui to display the details of required parameters
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  state:
                    type: string
                    enum: [enum1, enum2, enum3]
      responses:
          '201':
            description: Created
    get:
      description: Using header, path, query or cookie to render the details of required parameters is not supported by swagger ui yet
      parameters:
        - in: header  # Do not touch this var, please
          name: param01
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                name:
                  type: string
                state:
                  type: string
                  enum: [enum1, enum2, enum3]
          required: true
      responses:
        '200':
          description: "ok"
        '500':
          description: "error"
 ```

Test on https://editor.swagger.io/

### Is your feature request related to a problem?

Header, path, query and cookie parameters do not render the details of the arguments.

### Describe the solution you'd like

Render the arguments object details the same way as in a requestbody

### Additional context

![image](https://user-images.githubusercontent.com/11426226/92451258-c76a4e80-f1bc-11ea-9cb6-794595443dbb.png)
![image](https://user-images.githubusercontent.com/11426226/92451274-cc2f0280-f1bc-11ea-99bd-9326ce0a72fb.png)

Redoc always previews details of objects, that's nice! Let's have that also for swagger ui rendering.

<img width="647" alt="Screen Shot 2020-09-08 at 10 20 48 AM" src="https://user-images.githubusercontent.com/11426226/92451472-09939000-f1bd-11ea-920c-a2baf3a0c956.png">

**Comment by hkosova** [comment]
Hi @Ninroot, this is tracked in #4581 so I'll close this one as a duplicate.
