### ISSUE TITLE
Jest: unhandled promise rejection

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-ui#6365]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Existing Jest unit test. `/test/unit/core/plugins/auth/actions.js`

### Describe the bug you're encountering

The unit tests pass, however there are `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'newAuthErr' of undefined`

```
(node:48945) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'newAuthErr' of undefined
(node:48945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

This might be a problem with the Jest test itself, e.g. not configuring/mocking `errActions` method.

### To reproduce...

1. (Optional) Run single Jest unit test file via `testMatch: ['**/test/unit/core/plugins/auth/actions.js'],`
2. See error above

### Expected behavior

There should be no `UnhandledPromiseRejectionWarning`

**Comment by tmarkovic** [comment]
I have a fix ready for this!
