### ISSUE TITLE
Trigger API calls from plugin

### ISSUE THREAD

**Issue by dogusev** [swagger-api/swagger-ui#6370]
Hello!
I'm working on a custom plugin, and it should automatically emulate one of the GET requests, and render the response in plugins custom UI, as well after some updates at custom UI, the plugin should trigger another POST request with updated data.

Could you please help with this, or advice somebody, or at least the docs with working examples...

### Q&A (please complete the following information)
 - macOS
 - chrome
 - Version: 3.23.11
 - Method of installation:dist assets
 - Swagger-UI version: 3.23.11

### Content & configuration
I have the similar API
GET /configuration
POST /configuration

GET retrieves existing config like: 
```
{
a:1,
b:2
}
```
The POST updates the config values.

### How can we help?
How can I automatically load current configuration to the plugin, draw it in a custom view, and after some ui changes POST it back?

**Comment by tim-lai** [comment]
@dogusev There is a point where a `mutatedRequest` is generated after a http call has been made to swagger-client. This would probably be the ideal point to hook a plugin to followup on a response. Probably less ideal is to hook into the curl component render, which fyi I think is the only "user" of `mutatedRequest`. Afterwards, you would have to create a new http request, but not sure you can leverage swagger-client as-is at that time. Documentation for SwaggerUI plugin API can be found here:
https://swagger.io/docs/open-source-tools/swagger-ui/customization/plugin-api/
