### ISSUE TITLE
I've got a similar problem with the latest versions. Tried 20-25 different versions.. Facing the same error

### ISSUE THREAD

**Issue by arjunnehru** [swagger-api/swagger-ui#6382]
I've got a similar problem with 
* http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/ExampleService.openapi3.json

`Resolver error: Cannot read property 'items' of undefined`

Note: my problem was solved with Swagger UI 3.11.0, example now works fine.

_Originally posted by @ralfhandl in https://github.com/swagger-api/swagger-ui/issues/3366#issuecomment-365659899_

**Comment by tim-lai** [comment]
closing as duplicate. #6383 is also duplicate, but left open
