### ISSUE TITLE
Add Response Code to Response Class and Response Message Section

### ISSUE THREAD

**Issue by edmondchui** [swagger-api/swagger-ui#640]
With respect to the fix for https://github.com/wordnik/swagger-ui/issues/637, we need to show the response code (20x) in the Response Class and Response Message section so that the API users know what is the response code to expect. Before that issue the response code was always 200.

**Comment by edmondchui** [comment]
Thx. When will it be merged to master?

**Comment by fehguy** [comment]
it has been as of this morning.  Give it a whirl and reopen if you see issues.

**Comment by edmondchui** [comment]
Reopen this issue as the response for 201 or 204 is not shown under the Response Class section. Only 200 works.

**Comment by edmondchui** [comment]
BTW, how do I reopen? I don't see the button for reopen.

**Comment by webron** [comment]
Reopened it for you.

**Comment by edmondchui** [comment]
Thanks Ron.

**Comment by fehguy** [comment]
we should be rendering the `lowest 2xx` response for the top response method, or `default` if not present.

**Comment by mohsen1** [comment]
waiting for https://github.com/swagger-api/swagger-js/issues/325

**Comment by fehguy** [comment]
added reference to parent issue
