### ISSUE TITLE
Evaluating plugin to support cacert on curl calls

### ISSUE THREAD

**Issue by gee4vee** [swagger-api/swagger-ui#6403]
I'm evaluating if it's possible to develop a plugin to support the cacert option on the curl calls generated by Swagger UI. Someone opened an issue a while ago on this (https://github.com/swagger-api/swagger-ui/issues/3479). Would the plugin mechanism support this? Any pointers to get me started on it?

The need for it is we are deploying Swagger UI in an OpenShift cluster, and for the host we are using the Kube API server at `kubernetes.default.svc.cluster.local`. Hitting the HTTPS API endpoints there requires specifying the CA certificate.

### Q&A (please complete the following information)
 - OS: macOS 10.15.6
 - Browser: Firefox
 - Version: 80.0.1
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 4.14
 - Swagger/OpenAPI version: 2.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by tim-lai** [comment]
@gee4vee In theory, it is possible for you to create a custom plugin to generate an off-spec curl command. I don't know that the existing curl component is easily extractable into a plugin, but you could mimic it with a new plugin component that fires after receiving a http response from swagger-client, or after the existing curl component receives data/is able to render. The latter option might be easier to hook into. For documentation on SwaggerUI plugin API, please take a look here: https://swagger.io/docs/open-source-tools/swagger-ui/customization/plugin-api/
