### ISSUE TITLE
Add global parameters that apply to all paths

### ISSUE THREAD

**Issue by costeaalex** [swagger-api/swagger-ui#6414]
This is somewhat of an oversight by I think it would be a very handy thing to be able to define global custom headers (which is what I need and found a couple of others needing) and have them apply to all requests. Cluttering the paths with refs is not very maintainable nor efficient.

Thanks

**Comment by hkosova** [comment]
@costeaalex please submit your feature request to https://github.com/OAI/OpenAPI-Specification/issues - they are the folks in change of OpenAPI syntax.
