### ISSUE TITLE
Invalid charset 

### ISSUE THREAD

**Issue by mgrishkov** [swagger-api/swagger-ui#6417]
### Q&A (please complete the following information)
 - OS: Windows/macOs
 - Browser: chrome/safari
 - Version: 85.0.4183.102 / 14
 - Method of installation: dist assets
 - Swagger-UI version: 3.18.3
 - Swagger/OpenAPI version: Swagger 2.0

### Describe the bug you're encountering
I faced with a problem with encodind "/" characted. After uploading json to Swagger Ui it shows `���/1���/Bypass` but original url is '/1/Bypass`

Here part of json-document:
```
{
  "swagger": "2.0",
  "info": {
    "title": "XXXX.Proxy.Api",
    "description": "Service that acts as proxy to external and internal http-requests, extends requestes with athenticatio>    "version": "1.0"
  },
  "paths": {
    "/1/Bypass": {
      "post": {
        "tags": [
          "Bypass"
        ],
        "summary": "Bypass a request to external services.",
        "consumes": [
          "application/json",
          "text/json",
          "application/*+json"
        ],
```

**Comment by hkosova** [comment]
@mgrishkov Please try the latest version of Swagger UI - 3.34.0.

**Comment by mgrishkov** [comment]
Yes, It's Ok now
