### ISSUE TITLE
How to update request body (state and textarea) from plugin?

### ISSUE THREAD

**Issue by dogusev** [swagger-api/swagger-ui#6426]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration
I have a simple plugin, with POST endpoint

Swagger/OpenAPI definition:
```yaml
post:
      tags:
      - Configuration Resource
      summary: Create a configuration for specified product and channel
      operationId: createConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductConfiguration'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductConfiguration'
        "500":
          description: Unexpected count of created items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
```

Swagger-UI configuration options:
```js
SwaggerUI({
  url: url,
        dom_id: '#swagger-ui',
        deepLinking: true,
        supportedSubmitMethods: ["options", "head", "get", "post", "put", "patch", "delete"],
        showExtensions: true,
        showCommonExtensions: true,
        displayOperationId: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          StrategiesOrderPreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ]
})
```

### How can we help?
When I click on "Try It" button, I want my plugin to write a JSON to request body parameter.
I tried to use action and reducer, but nothing happens.

**Comment by tim-lai** [comment]
@dogusev I don't quite understand what you are trying to accomplish. Clicking on "Execute" button will generate a http request based on the api definition and user input. If the content-type is "application/json", it will generate the request as as JSON. That said, here is a link to our plugin API documentation:
https://swagger.io/docs/open-source-tools/swagger-ui/customization/plugin-api/
