### ISSUE TITLE
Alter data from OpenAPI specification file

### ISSUE THREAD

**Issue by debargharoy** [swagger-api/swagger-ui#6428]
### Q&A
 - OS: Windows
 - Browser: Any
 - Method of installation: dist assets
 - Swagger-UI version: 3.32.5
 - Swagger/OpenAPI version:2.1.4

The problem that I have is, the server that's returning the OpenAPI specification file is only giving the context-path of the APIs, e.g. */api*. But I also need the server part to contain the name of the host the Swagger UI is accessed at (e.g. *http://localhost/api*). Is there a way which can help to modify the Swagger-UI object when using the dist assets.

**Comment by tim-lai** [comment]
@debargharoy In OpenAPI 2, you can use the 'schemes', `host` and `basePath` to define server host. https://swagger.io/docs/specification/2-0/api-host-and-base-path/

You can do this in OpenAPI 3.0 with the `servers` object. https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by debargharoy** [comment]
@tim-lai 
Can you help with a small example on how we can alter the code in index.html to achieve the same.

**Comment by wll8** [comment]
@debargharoy 

[change demo Swagger.js#L111](https://github.com/wll8/mockm/blob/22c774cc17f566b89583abc933f97608c32d631c/client/src/ApiDetailCom/Swagger.jsx#L111)

``` js
const UrlMutatorPlugin = (system) => ({
  rootInjects: {
    setScheme: (scheme) => {
      const jsonSpec = system.getState().toJSON().spec.json;
      const schemes = Array.isArray(scheme) ? scheme : [scheme];
      const newJsonSpec = Object.assign({}, jsonSpec, { schemes });

      return system.specActions.updateJsonSpec(newJsonSpec);
    },
    setHost: (host) => {
      const jsonSpec = system.getState().toJSON().spec.json;
      const newJsonSpec = Object.assign({}, jsonSpec, { host });

      return system.specActions.updateJsonSpec(newJsonSpec);
    },
    setBasePath: (basePath) => {
      const jsonSpec = system.getState().toJSON().spec.json;
      const newJsonSpec = Object.assign({}, jsonSpec, { basePath });

      return system.specActions.updateJsonSpec(newJsonSpec);
    }
  }
});

window.ui = SwaggerUI({
  dom_id: '#myDomId',
  plugins: [
    UrlMutatorPlugin,
  ],
  onComplete: () => {
    // this will set appropriate data when swagger-ui ready
    window.ui.setScheme('http');
    window.ui.setHost('www.google.com');
    window.ui.setBasePath('v3');
  }   
})
```
