### ISSUE TITLE
Swagger UI Response: 😱 Could not render n, see the console

### ISSUE THREAD

**Issue by andersdd** [swagger-api/swagger-ui#6436]
- OS: Ubuntu
 - Browser: Chrome
 - Version: 85
 - Method of installation: dist assets
 - Swagger-UI version: 3.34.0
 - Swagger/OpenAPI version: Swagger 2.0

When using references ($ref) to define the various API Response codes, the message "😱 Could not render n, see the console" is displayed despite the definition being correct and despite the response codes being correctly rendered.

**Example Path:**
ExpCatCreate:
    post:
      summary: Create Expense Categories.
      tags:
        - Accounting
      description: Create Expense Categories.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: expensecategory
          schema:
            $ref: '../definitions/expensecategory.yaml#ExpenseCategoryPost'
      responses:
        $ref: 'post_response.yaml'

And the file post_response.yaml:
200:
  description: Success
  schema:
    $ref: '../definitions/common.yaml#PostResponse'
400:
  description: Bad Request.  The request has errors that could not be processed by the server.  Server error messages are typically returned in the message.
  schema:
    $ref: '../definitions/common.yaml#Errors'
401:
  description: Unauthorized. Authentication or permission error, e.g. incorrect API keys
  schema:
    $ref: '../definitions/common.yaml#Errors'  
422:
  description: Invalid or malformed token
  schema:
    $ref: '../definitions/common.yaml#Errors'  
5XX:
  description: Internal Server Error.  Please check the return message or server logs for details
  schema:
    $ref: '../definitions/common.yaml#Errors'

**Comment by hkosova** [comment]
There are several syntax errors:

1) `$ref` values need a `/` after `#`, e.g.:
```yaml
$ref: '../definitions/expensecategory.yaml#/ExpenseCategoryPost'

$ref: '../definitions/common.yaml#/Errors'
```

2) `responses` cannot use `$ref` directly, you can only `$ref` individual responses, like so:
```
responses:
  200:
    $ref: 'post_response.yaml#/200'
  400:
    $ref: 'post_response.yaml#/400'
  401:
    $ref: 'post_response.yaml#/401'
  ...
```

3) OpenAPI 2.0 doesn't support response code ranges such as `5XX` (this is an OpenAPI 3.0 thing), you can only define individual status codes such as 500.

Please fix the errors and see if this resolves the issue. If this doesn't help, can you please also provide the contents of expensecategory.yaml, common.yaml, and any other referenced files?

**Comment by andersdd** [comment]
@hkosova Thank you for the prompt response.  I was getting confused as the reposnes rendered correctly but the error still occurred.
Using your point #2 has resolved the problem for me.
Thanks!!

**Comment by andersdd** [comment]
The ref including a slash was not required.  Also OpenAPI 2.0 had no issues with using 5XX.

However splitting the responses into individual codes resolved the Render issue reported.

**Comment by mahanfakhimi** [comment]
1. @andersdd rg
2. fd
3. f
4. d
5. s
6. d
7. sd
8. s
9. ds
10. ds
11. d
12. s
13. dds
14. d
15. s



















s
d
s
d
