### ISSUE TITLE
List of Nested schema

### ISSUE THREAD

**Issue by Ashish-Ghora** [swagger-api/swagger-ui#6439]
I am trying to use swagger ui to display a list of nested schema with 'multipart/form-data'.
When I click 'Try it out', the display for the input field is blank i.e it does not show the json schema to make changes in values.

When I use a simple nested schema (without a list), it displays the nested schema fine.

I have attached the 2 json files that could be loaded in swagger ui to see the behaviour.

[with-list.zip](https://github.com/swagger-api/swagger-ui/files/5277221/with-list.zip)

**Comment by Ashish-Ghora** [comment]
This issue is still not fixed. When I have a single item of a Nested class... doing a 'try it out' shows the dummy schema properly.
{
  "company": "string"
}

But on using a list of the Nested class it shows an empty text box. I expected it to contain the above when I do 'Add Item'

**Comment by mathis-m** [comment]
@Ashish-Ghora could you check if this still issue is still there. And provide a minimal repoduction yaml or json.
