### ISSUE TITLE
When did Swagger UI officially drop support for IE11?

### ISSUE THREAD

**Issue by scottohara** [swagger-api/swagger-ui#6460]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: IE
 - Version: 11
 - Method of installation: dist assets
 - Swagger-UI version: [e.g. 3.33.0]
 - Swagger/OpenAPI version: OpenAPI 3.0

### How can we help?

On 3 October 2020, one of our users reported problems rendering their API documentation in Internet Explorer 11 (a script error was appearing in the console).

We traced the script error back to a 3rd party dependency that uses ES2015+ rest parameters (which is syntax not supported in IE 11).

The offending code was found in the `highlight.js` library, which is a dependency of `react-syntax-highlighter`.

The timeline appears to be as follows (in reverse chronological order):

| Time | Where | What |
| ---- | ----- | ---- |
| 19 August 2020 | SwaggerUI v3.32.2 | `react-syntax-highlighter` dep was bumped from v12.2.1 -> v13.5.0 (https://github.com/swagger-api/swagger-ui/pull/6312) |
| 3 July 2020 | `react-syntax-highlighter` v13.0.0 | `highlight.js` dep was bumped from ~9.13.0 -> ^10.0.0 (https://github.com/react-syntax-highlighter/react-syntax-highlighter/commit/31529aa3487c6fa8f70bdcbde3950570885ff5ad) |
| 11 March 2020 | `highlight.js` v10.0.0 | IE 11 no longer supported (https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_BREAKING_CHANGES.md) |
| 22 Jan 2020 | Swagger UI `README` | IE quietly removed from supported browsers list (https://github.com/swagger-api/swagger-ui/commit/553d48a0cad8e2f110e07737e93107bade885c3d#diff-04c6e90faac2675aa89e2176d2eec7d8) |

Other than the change to the `README` file, I can't see anything in the Swagger UI release notes around the time of v3.25.x to indicate that IE support was officially being dropped.

Was this announced anywhere else?

To be clear, we have **no issues** with Swagger UI dropping support for IE.

However, as there was no mention (as far as I can tell) of this in any release notes, we didn't advise our users that IE support was going away, and that if they wanted to continue using IE they would need to remain on an older version.

Is somewhere that officially mentions support for IE ceasing? We now need to have a slightly uncomfortable conversation with our remaining IE users, so having some official Swagger UI announcement would certainly help us in this regard.

**Comment by tim-lai** [comment]
https://github.com/swagger-api/swagger-ui/issues/5808#issuecomment-576953636
