### ISSUE TITLE
When using apiKey authorizations, UI should mark endpoints with authorization required 

### ISSUE THREAD

**Issue by STRML** [swagger-api/swagger-ui#647]
Endpoints that use OAuth2 authorization show a visual indicator in the endpoint description. It would be nice if apiKey authorizations were also indicated visually somehow, perhaps via the (!) icon that changes or disappears once an apiKey is entered in the header.

**Comment by claude** [comment]
:+1:

**Comment by webron** [comment]
We now have the lock icon to indicate that an operation has security defined with it. If the lock is open - no authorization information was provided. If it's closed, you're set.
