### ISSUE TITLE
requestBody examples do not respect media-type

### ISSUE THREAD

**Issue by mathis-m** [swagger-api/swagger-ui#6475]
### Q&A (please complete the following information)
OS: [e.g. macOS] Windows 10 Pro
Browser: [e.g. chrome, safari] chrome
Version: [e.g. 22] Version 85.0.4183.102 (Official Build) (64-bit)
Method of installation: [e.g. npm, dist assets] raw code
Swagger-UI version: [e.g. 3.10.0] master
Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] 3.0.1
### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
 title: Example Swagger
 version: '1.0'
servers:
 - url: /api/v1
paths:
 /xmlTest:
   post:
     summary: sample issues
     operationId: registerSubscription
     parameters: []
     requestBody:
       description: Simple Test
       content:
           application/xml:
              schema:
               $ref: "#/components/schemas/Test"
              example: 
                x: should be xml
     responses:
       '200':
         description: Simple example
         content: {}
components:
 schemas:
   Test:
     type: object
     xml:
       name: root
     properties:
       x:
         type: string
       other:
         type: string
         format: email
     example: 
       x: what the f
```

### Describe the bug you're encountering

When providing examples via `examples` or `example` keyword for requestBody content it will not be rendered according to content-type.

### To reproduce...
Open yaml at editor and try to view xml requestBody sample. You can delete the `example` part and it will render it in xml.

### Expected behavior
Examples provided via `examples` or `example` for requestBody definition should be rendered respecting the content-type.
With `example` requestBody:
![image](https://user-images.githubusercontent.com/11584315/95211448-e3c5cf00-07ec-11eb-9dfc-7e1b8aaf5d85.png)
Without:
![image](https://user-images.githubusercontent.com/11584315/95211505-f6d89f00-07ec-11eb-9f76-17906a33165f.png)

### Additional context or thoughts
Same as for Responses #6442

**Comment by scholzi100** [comment]
Are there updates to this? Looks like handling for response does work as of the latest release.

**Comment by mathis-m** [comment]
@scholzi100 Unfortunately I didn't have time to create a PR, but it shouldn't be a big problem. I will probably manage to create a pr next week.
