### ISSUE TITLE
requestBody sample Try-out should use content-type to generate matching example if switched.

### ISSUE THREAD

**Issue by mathis-m** [swagger-api/swagger-ui#6476]
### Q&A (please complete the following information)
OS: [e.g. macOS] Windows 10 Pro
Browser: [e.g. chrome, safari] chrome
Version: [e.g. 22] Version 85.0.4183.102 (Official Build) (64-bit)
Method of installation: [e.g. npm, dist assets] raw code
Swagger-UI version: [e.g. 3.10.0] master
Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] 3.0.1
### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
 title: Example Swagger
 version: '1.0'
servers:
 - url: /api/v1
paths:
 /xmlTest:
   post:
     summary: sample issues
     operationId: registerSubscription
     parameters: []
     requestBody:
       description: Simple Test
       content:
           application/xml:
             schema:
               $ref: "#/components/schemas/Test"
           application/json:
             schema:
               $ref: "#/components/schemas/Test"
     responses:
       '200':
         description: Simple example
         content:
           application/xml:
             schema:
               $ref: "#/components/schemas/Test"
           application/json:
             schema:
               $ref: "#/components/schemas/Test"
components:
 schemas:
   Test:
     type: object
     xml:
       name: root
     properties:
       x:
         type: string
       other:
         type: string
         format: email
     example: 
       x: what the f
```

### Describe the bug you're encountering

Go into requestBody try out mode. Switch the content-type.
Example will not be updated to respect content-type.
### To reproduce...
Open yaml at editor and try out and switch content-type.
### Expected behavior
Should use current example-value to generate new example for content-type, when new content-type is selected.

**Comment by tim-lai** [comment]
related to #6250 and #6201, likely same root cause. specifically, neeed to re-resolve the operation subtree if content-type is changed.
