### ISSUE TITLE
migrate to enzyme@3

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-ui#6487]
### Content & configuration

### Is your feature request related to a problem?

for swagger-ui, prep work already done for global setup... just uncomment lines in /test/unit/setup.js

This ticket impacts additional files beyond the 3 remaining Mocha-based tests

migration docs: https://github.com/enzymejs/enzyme/blob/2b9a4db899099dc3669ddb6c202421359223f166/docs/guides/migration-from-2-to-3.md

### Describe the solution you'd like

Enzyme 3 replaces Enzyme 2

### Additional context

related to: #6486 , "Migrate 3 Mocha+Enzyme test files"

* swagger-editor already uses enzyme@3. Although some refactoring could be done to implement a global setup instead of each test file.

* React 16 may require enzyme@3

**Comment by iamjoross** [comment]
Hello @tim-lai , I am interested in doing this task. Can I be assigned to it?

**Comment by tim-lai** [comment]
outdated issue. SwaggerUI now uses `enzyme@3` as part of the `swagger-ui@4` update
