### ISSUE TITLE
Swagger UI to display only Selected routes for an Action

### ISSUE THREAD

**Issue by MukulGupta12** [swagger-api/swagger-ui#6488]
[.Net Core]
So, I have an Action with multiple Route and all of them are displayed in Swagger UI.
Is it possible to restrict the route in Swagger UI for that Action ?

Example - Simple API with multiple routes.
[HttpPost]
[Route("v1/Data")]
[Route("v2/Data")]
public async string Data(string val)
{
	return val;
}

In Swagger UI it displays both Routes.
v1/Data ->
v2/Data ->

But I Need to only display a single Route.
v1/Data ->

**Comment by hkosova** [comment]
Since your API definition is generated from code, the displayed routes are probably controlled by code annotations. Check the documentation for the .NET library that you use (Swashbuckle, Swagger-Net, or something else) or open a ticket with that library for support.
