### ISSUE TITLE
Special characters not allowed on Request Param of type String

### ISSUE THREAD

**Issue by BESAFX** [swagger-api/swagger-ui#6502]
#5095 # Q&A 
 - OS: Ubuntu
 - Browser: chrome
 - Version: 22
 - Method of installation: Java
 - Swagger-UI version: 3.10.0
 - Swagger/OpenAPI version:  Swagger 2.0, OpenAPI 3.0

I just need to be able to pass special characters like (: < >&&..) on Query param for request, 
Like for example following implementation for @Paramter: 
`@Parameter(
                in = ParameterIn.QUERY,
                description = "Enter search query.",
                name = "search",
                schema = @Schema(
                        type = "string",
                        pattern = "name:value",
                        defaultValue = "name:value"
                )
)` 

But when i make request from UI, this pattren (name:value) converted into (name%3Avalue) and this will not give me correct response.

So is there any way to force Swagger to accept these special symbols on URLs ?

**Comment by tim-lai** [comment]
Hi, swagger-ui handles serialization of reserved characters based on the api definition. You can use 'style' and 'explode' options to set a desired serialization method. For more information, please take a took at https://swagger.io/docs/specification/serialization/
