### ISSUE TITLE
Syntax highlighting is broken in server response

### ISSUE THREAD

**Issue by Gragog** [swagger-api/swagger-ui#6508]
### Q&A (please complete the following information)
 - OS: [Ubuntu 20.04.1]
 - Browser: [Opera]
 - Version: [71]
 - Method of installation: [npm]
 - Swagger-UI version: [^3.32.2]
 - Swagger/OpenAPI version: [OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition: not relevant
Swagger-UI configuration options: default options (React)

### Describe the bug you're encountering

The response body that is shown when trying out an API endpoint uses syntax highlighting.
This highlighting is broken and highlights the response wrong. In my case there are many hexadecimal string-IDs in the response which don't get recognized as strings, causing many HTML tags to alternate between a character and a number (see screenshot), making the response hard to read and causing the browser tab to hang on huge responses.

### To reproduce...

1. Try out an API that returns the following JSON response
2. Click on 'Execute'
3. See error

```json
{
  "request": {
    "parma": "de",
    "parmb": "fuzzy",
    "parmc": "rel_desc",
    "parmd": 1,
    "parme": 1
  },
  "result": {
    "count": 1,
    "total": 66014291,
    "array": [
      {
        "id": "9d20d34d755b244b808159c3d03998c9d9180b7964699465c2ac0ab79e78df3b",
        "number": "4011885192793",
        "title": "Golden Head - schwarz",
        "description": "4 Kreditkartenfächer mit Druckknopfverschluss",
        "category": {
          "id": null
        },
        "image": {
          "url": "https://cdn.example.com/dynimg/b-BivUcRyqh8xrxnUefwwr5RzKY-Pw9q9LKbtkA0_z9EIBjuz3A4vS2TFag/671296140_large.png"
        },
        "thumbnail": {
          "url": "https://cdn.example.com/dynimg/QX-6zM7oXtog6wKgeWcAvfudc_-yTA2FcxKY-Pw9q9L94KbtkA0_z9EIBjuz3Xa5Wqp3cC18WIYE230-c/671296140_small.png"
        },
        "score": 0
      }
    ]
  }
}
```

### Expected behavior

Syntax highlighting should work correctly, as it did in `swagger-ui-react` version `3.32.1`

##### Broken
![Broken](https://user-images.githubusercontent.com/36130475/100077986-47f72d80-2e43-11eb-8a3c-d824ad44ad6f.png)

##### Expected (version `3.32.1`)
![Expected](https://user-images.githubusercontent.com/36130475/100077997-4cbbe180-2e43-11eb-8726-c4d3c118fcb5.png)

### Additional context or thoughts

It seems the strings in the response are highlighted from their end to the beginning of the next string, like if the first quote is overlooked. The JSON itself has a valid syntax.
The issue exists even in the latest version (`3.35.0`).

**Comment by andrefilipesilva73** [comment]
Same happening to me :( Current specs worked well before and work well on [https://petstore.swagger.io/](https://petstore.swagger.io/)

**Comment by thSoft** [comment]
Unfortunately, I can still reproduce this bug by using the SwaggerUI component in swagger-ui-react.
