### ISSUE TITLE
Swagger 3.0.19 ver. does not represent chinese charaters in response header 

### ISSUE THREAD

**Issue by KRunets** [swagger-api/swagger-ui#6509]
If filename encoded in UTF-8 it represents as %E5%A5%97%E4%BB%B6%E6%88%90%E7%BB%A9%E5%8D%95.txt
If filename in default encoding it represents as ??????.txt

The original filename is 測試.txt

![image](https://user-images.githubusercontent.com/26008069/95747463-2ed65b00-0ca1-11eb-91d9-874fe9d6fa5e.png)

Could you please review?

**Comment by hkosova** [comment]
Your screenshot shows Swagger UI version 2.x which is a very old version and is no longer supported. Please try the latest version of Swagger UI - 3.35.2. If the problem also exists in the latest version, please [open a new issue](https://github.com/swagger-api/swagger-ui/issues/new) and fill in the details requested in the issue template.
