### ISSUE TITLE
ERROR index.html & facicon.ico

### ISSUE THREAD

**Issue by KoalaGeo** [swagger-api/swagger-ui#6510]
#5095 # Q&A (please complete the following information)
 - OS: Unix
 - Browser: Firefox/Chrome
 - Version: 81
 - Method of installation: docker
 - Swagger-UI version: 3.35.1
 - Swagger/OpenAPI version: Swagger 1.0, OpenAPI 3.0]

### Content & configuration
  Clicking GET only gets churning circle. 

Logs: 
`[error] 38#38: *6 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.233.70.4, server: localhost, request: "GET /favicon.ico HTTP/1.1",`
`[error] 38#38: *7 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 10.233.70.4, server: localhost, request: "GET / HTTP/1.1"`

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```
FROM swaggerapi/swagger-ui:v3.35.1

EXPOSE 8080

COPY content/openapi.json /app/swagger.json
ENV SWAGGER_JSON=/app/swagger.json
ENV BASE_URL=/sensors
```

```
#/default/get_v1_0_Actuators
```

### Describe the bug you're encountering
  Clicking GET only gets churning circle. 

### To reproduce...

Click GET

### Expected behavior
Should GET the response

**Comment by tim-lai** [comment]
Looks like you might need to configure nginx with permissions to all files in `swagger-ui/dist`?
