### ISSUE TITLE
Markdown paragraphs ignored.

### ISSUE THREAD

**Issue by Skeeve** [swagger-api/swagger-ui#6514]
### Q&A (please complete the following information)
 - OS: MacOS 10.15.7 with Docker Desktop 2.4.0.0 using image "swaggerapi/swagger-editor"
 - Browser: Firefox
 - Version: 81.0.1
 - Method of installation: docker
 - Swagger-UI version: No clue how to get that information
   Does this help?
```
Digest: sha256:e1bd44262e23eafa7097eb60b35f4f1156c456d621e07b5b5b4a871f7ce3d41a
Status: Image is up to date for swaggerapi/swagger-editor:latest
```
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.2
paths:
  /test:
    get:
      description: >
       this is just
       
       one line
       
       but should be,
       
       according to markdown,
       
       five paragraphs
```

Swagger-UI configuration options:
Didn't change that so it's oob

```
?withCredentials=true
```

### Describe the bug you're encountering

According to markdown an empty line denotes a paragraph.

Unfortunately there will be no paragraph for empty lines.

### To reproduce...

1. Use above given example OpenAPI spec
2. View the description of the `/test` path

### Expected behavior

Empty lines should cause new paragraphs.

### Screenshots

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/725404/95951837-63f4c180-0df7-11eb-9a3b-795878e1d09b.png">

**Comment by Skeeve** [comment]
Looking at https://github.com/swagger-api/swagger-ui/issues/5330 I see that there "|" instead of ">" is used.

When changing to "|", markdown is rendered. Must have missed the documentation for that. Sorry for interrupting. Going to close now.

**Comment by hkosova** [comment]
When using `>`, a _single empty line_ is replaced with a space, and you need _two empty lines_ to start a new paragraph:

```yaml
paths:
  /test:
    get:
      description: >
       this is just


       one line


       but should be,


       according to markdown,


       five paragraphs
```

See https://yaml-multiline.info/ for details.
