### ISSUE TITLE
Re-add the button "Reset" to reset the request body

### ISSUE THREAD

**Issue by JessyMDS** [swagger-api/swagger-ui#6517]
Hello,

You deleted the button "Reset" that was available under the request body box.

Please re-add it because now we must refresh the page in order to "reset" the request body.

Thank you

**Comment by Nankh** [comment]
Yeah feature needed.

:)

**Comment by tim-lai** [comment]
Can you point to a swagger-ui version that had a "reset" button? In the meantime, I would agree that this would be a nice feature.

**Comment by tim-lai** [comment]
Are you referring to the "Clear" button, which appears after clicking on "Execute"? Although, that only clears the response, and does not reset the request body input.

**Comment by JessyMDS** [comment]
Hello,

Version 2.9.2

**Comment by JessyMDS** [comment]
Screenshot

**Comment by JessyMDS** [comment]
![reset](https://user-images.githubusercontent.com/72877225/96555567-39ec4500-12b8-11eb-8034-e7317635f24d.PNG)

**Comment by tim-lai** [comment]
Ah, ok. Yeah, swagger-ui@3.x doesn't have this feature.

**Comment by JessyMDS** [comment]
> Ah, ok. Yeah, [swagger-ui@3.x](mailto:swagger-ui@3.x) doesn't have this feature.

So? Will you re-add it?

(If no, why?)

**Comment by tim-lai** [comment]
We are open to any and all contributions. 😉

**Comment by mathis-m** [comment]
@tim-lai Have a look at PR #6837!
> ### Description
>  https://user-images.githubusercontent.com/11584315/105664630-6cb86180-5ed5-11eb-91e7-436c865b77b2.mp4
> 1. Media-Type change is now reflected within the request-body editor.
> 2. When clicking the new `Try It Out Reset Button` the request body will be reset to its initial state.
> 3. When the user switches the media-type in the try-out mode, the experience is as follows:
>    
>    * If the user did edit the request body the body wont be touched and only media type is updated. This is to ensure that user content is NEVER accidentally overwritten with a default value.
>    * If the user did not edit the request body it is safe to be replaced by the default value of the target media-type.
