### ISSUE TITLE
Authorization popup not updating when switching between specs

### ISSUE THREAD

**Issue by mbaeuerle** [swagger-api/swagger-ui#6537]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Firefox (also Chrome 86.0.4240.75)
 - Version: 81.0.2
 - Method of installation: npm using swagger-ui-dist
 - Swagger-UI version: starting 3.25.1 (until newest)
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
* First YAML with api-token & basic auth:  https://gist.githubusercontent.com/mbaeuerle/64e6da854f92cfb0d4f5c1ddd1d75a8c/raw/3780712de1d6fc39a340887429fb1cbb8f8c3edb/first.yaml
* Second YAML with basic auth only: https://gist.githubusercontent.com/mbaeuerle/64e6da854f92cfb0d4f5c1ddd1d75a8c/raw/3780712de1d6fc39a340887429fb1cbb8f8c3edb/second.yaml

From Gist https://gist.github.com/mbaeuerle/64e6da854f92cfb0d4f5c1ddd1d75a8c

Swagger-UI configuration options:
- Use the pet store example https://petstore.swagger.io/

### Describe the bug you're encountering
- The authorization mechanism pop up is not updating when switching between OpenAPI specifications in the drop down, it's always using the authorization of the spec loaded first.

### To reproduce...

1. Go to https://petstore.swagger.io/ load the first YAML from above and check the authorization mechanism by selecting "Authorize" (shows API token & Basic Auth)
2. Load the second YAML
3. Check the authorization mechanism again, it still shows the Auth from before (API token & Basic Auth instead of basic auth only)

### Expected behavior
- After changing the spec from the drop down the authorization pop up should show the authorization methods for the new spec only

### Additional context or thoughts
- I tracked down that this behaviour started to occur with version 3.25.1. The previous version 3.25.0 does not have this issue.
- SwaggerUI version 3.25.1 is using SwaggerJS 3.10.1. It could also be an issue there
- I can verify this issue also with the drop down mechanism (using specific urls)

**Comment by hkosova** [comment]
Related (or duplicate): #5540

**Comment by mbaeuerle** [comment]
@hkosova its only a little bit related. In the other issue I showed that one stays logged in when switching the spec.
Here it is about a bug which doesn't even show the authorization mechanisms of the newly loaded spec.

**Comment by mbaeuerle** [comment]
It's an interesting, because when switching between the PetStore example and one of my Gists seem to work without issues. The main difference seems like Petstore is using Swagger 2.0 whereas the Gists use OpenAPI 3.0

**Comment by mathis-m** [comment]
Have added the auth data flush on url load with #7046.
