### ISSUE TITLE
Consider using gulp.js as a build tool

### ISSUE THREAD

**Issue by dnephin** [swagger-api/swagger-ui#655]
Hello,

I'm curious if you've considered replacing the `Cakefile` with a tool like http://gruntjs.com/ or http://gulpjs.com/. I think the big advantage with these tools is their large plugin community, so instead of having to write all the build code, you can add a few lines of configuration and they work.

I was hoping to add a concat of all the file (or at least all the swagger ones), but it looks like with cake I would have to write the whole thing, with grunt it would be just using this plugin https://github.com/gruntjs/grunt-contrib-concat

Using plugins means fewer bugs as well (because they are often more widely used)!  I noticed there is actually a bug with `cake dist` right now. When I use `vim` it creates `.*.swp` files, and if I'm editing a handlebars file `dist` is trying to compile those as a template.

I'm willing to contribute a PR if there is interest.

**Comment by mohsen1** [comment]
This is done.

**Comment by dnephin** [comment]
:tada:
