### ISSUE TITLE
How do swagger enumerations in. Net core appear as enumeration names instead of numbers?

### ISSUE THREAD

**Issue by shaohuatsou** [swagger-api/swagger-ui#6551]
I used the latest swagger. How do swagger enumerations appear as enumeration names instead of numbers in. Net core?

`public enum ClientType
    {
        Website = 0,
        Mobile = 1,
        Client = 2
    }`

![image](https://user-images.githubusercontent.com/50793943/96897756-8787ce00-14c1-11eb-8d3e-d9f5a290af19.png)

**Comment by hkosova** [comment]
This is a question for the .NET library that generates your API definition - most likely Swashbuckle but could be others. Please open an issue with that library instead.
