### ISSUE TITLE
Swagger UI getting stuck while expanding any of the endpoint

### ISSUE THREAD

**Issue by prataparunsingh** [swagger-api/swagger-ui#6586]
I am trying to integrate Swagger to .Net Core 3.1 web api project. Below is the piece of code I have added to the startup file.
In Configure Services method
services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("address", new OpenApiInfo { Title = "MyPlus", Version = "address" });
                c.SwaggerDoc("user", new OpenApiInfo { Title = "MyPlus", Version = "user" });
                c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
            }); 

In Configure method
app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("swagger/address/swagger.json", "Address");
                c.SwaggerEndpoint("swagger/user/swagger.json", "User");
                c.DefaultModelsExpandDepth(-1);
            });

By using I am able to get the UI correctly and quickly. But I when I am trying to expand any of the Endpoint the UI is getting stuck. I have added the screenshot below. Can you please help me on this.

![Swagger](https://user-images.githubusercontent.com/57321795/98318363-77fd9e80-2004-11eb-9217-349f21bb65a6.PNG)

**Comment by hkosova** [comment]
Please post your API definition that is located at `https://localhost:44382/swagger/address/swagger.json`.

**Comment by hkosova** [comment]
Closing due to no response.
