### ISSUE TITLE
UI try it out will not replace route value

### ISSUE THREAD

**Issue by lv-conner** [swagger-api/swagger-ui#6587]
This is and  sample case:
My controller like that:
[Route("api/[controller]")]
    [ApiController]
    public class PersonController : ControllerBase
    {
        private static List<Person> _persons = new List<Person>()
        {

        };
        public PersonController()
        {

        }
        [HttpGet]
        public ActionResult<List<Person>> Gets()
        {
            return _persons;
        }
        [HttpGet]
        [Route("{id}")]
        public ActionResult<Person> Get(string Id)
        {
            var p = _persons.FirstOrDefault(p => p.Id == Id);
            if(p == null)
            {
                return NotFound();
            }
            else
            {
                return p;
            }
        }
        [HttpPost]
        public ActionResult Post(Person p)
        {
            _persons.Add(p);
            return Ok();
        }
        [HttpPut]
        [Route("{id}")]
        public ActionResult Put(string id,string name)
        {
            var p = _persons.FirstOrDefault(p => p.Id == id);
            if(p == null)
            {
                return NotFound();
            }
            else
            {
                p.Name = name;
                return Ok();
            }
        }
        [HttpDelete]
        [Route("{id}")]
        public ActionResult Delete(string id)
        {
            var p = _persons.FirstOrDefault(p => p.Id == id);
            if(p == null)
            {
                return NotFound();
            }
            else
            {
                _persons.Remove(p);
                return Ok();
            }
        }

    }

    public class Person
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }

And the swagger generate ui as follows：
![image](https://user-images.githubusercontent.com/20316048/98318856-78a12f80-201a-11eb-9496-a8fd0140fb4e.png)
 
when i try it 👍 ![image](https://user-images.githubusercontent.com/20316048/98318919-9ff7fc80-201a-11eb-8a29-b26b02867432.png)

but the real parameter will not replace:
![image](https://user-images.githubusercontent.com/20316048/98319011-c4ec6f80-201a-11eb-8643-a391cb0c76f0.png)

in browser:

![image](https://user-images.githubusercontent.com/20316048/98319077-eb120f80-201a-11eb-83fb-a5d8ffdec66e.png)
It doesn't replace the route value "{id}"

**Comment by hkosova** [comment]
```csharp
    [Route("{id}")]
    public ActionResult<Person> Get(string Id)
```
Change the parameter name `Id` to `id` (lowercase) so that it matches the route.
