### ISSUE TITLE
Response examples line break not working

### ISSUE THREAD

**Issue by kevinccbsg** [swagger-api/swagger-ui#6595]
### Q&A
 - OS: macOS & windows
 - Browser: chrome & safari
 - Version: 3.36.2
 - Method of installation: npm
 - Swagger-UI version: 3.36.2
 - Swagger/OpenAPI version: OpenAPI 3.0

### Here an example of the result.

Parameters works fine.
<img width="1041" alt="Screen Shot 2020-11-08 at 16 58 21" src="https://user-images.githubusercontent.com/12685053/98470077-a84f6380-21e3-11eb-8502-28a1b7e820e4.png">

But responses don't render the `\n`.
<img width="1036" alt="Screen Shot 2020-11-08 at 16 58 27" src="https://user-images.githubusercontent.com/12685053/98470079-abe2ea80-21e3-11eb-9c43-4bb02d0df286.png">

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Pet store
  description: Add your description
  license:
    name: MIT
    url: ''
  termsOfService: ''
  version: 1.0.0
servers: []
components:
  schemas:
    Song:
      description: A song
      required:
        - title
      type: object
      properties:
        title:
          description: The title
          type: string
        artist:
          description: The artist
          type: string
        year:
          description: The year
          type: integer
          format: int64
    Pet:
      description: A pet
      required:
        - name
        - type
      type: object
      properties:
        name:
          description: The name
          type: string
        type:
          description: The type of pet
          type: string
        breed:
          description: The breed
          type: string
paths:
  /api/v1/pet:
    post:
      deprecated: false
      summary: ''
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Song'
            examples:
              example1:
                summary: payload example
                value: |-
                  {
                    "title": "Bury The Light",
                    "artist": "Casey Edwards ft. Victor Borba",
                    "year": 2020
                  }
              example2:
                summary: other payload example
                value: |-
                  {
                    "title": "The war we made",
                    "artist": "Red",
                    "year": 2020
                  }
        description: song info
        required: true
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              examples:
                xml:
                  summary: A sample XML response
                  value: |-
                    '<objects>
                      <object><id>1</id><name>new</name></object><object><id>2</id></object></objects>'
                example1:
                  summary: example success response
                  value: |-
                    [
                       "example": "asdasd"
                    ]
                example2:
                  summary: second example success response
                  value: |-
                    [
                      {
                        "name": "Hachiko",
                        "type": "Dog"
                        "breed": "Akita Inu"
                      },
                    ]
        '403':
          description: forbidden request response
          content:
            application/json:
              schema:
                type: object
              examples:
                example3:
                  summary: example error response
                  value: |-
                    {
                      "message": "you cannot access pet data",
                    }
      parameters: []
      tags: []
tags: []
```

Swagger-UI configuration options:
The same as this library https://github.com/scottie1984/swagger-ui-express

### Describe the bug you're encountering
We found a problem with the response examples when we use editor.swagger.io. The line breaks are not working. This only happens on this website which is using v3.36.2 of this library. If we use [swagger-ui-dist](https://www.npmjs.com/package/swagger-ui-dist) this doesn't happen 🤔 we are using that library in [this package](https://github.com/BRIKEV/express-jsdoc-swagger) and the problem does not happen there, maybe that helps to find the solution.

### To reproduce

1. Go to https://editor.swagger.io/
2. Paste the yaml that I wrote above
3. Scroll down to responses

### Expected behavior
Example response adds a line break.

### Screenshots
Parameters works fine.
<img width="1041" alt="Screen Shot 2020-11-08 at 16 58 21" src="https://user-images.githubusercontent.com/12685053/98470077-a84f6380-21e3-11eb-8502-28a1b7e820e4.png">

But responses don't render the `\n`.
<img width="1036" alt="Screen Shot 2020-11-08 at 16 58 27" src="https://user-images.githubusercontent.com/12685053/98470079-abe2ea80-21e3-11eb-9c43-4bb02d0df286.png">

### Additional context or thoughts
I think this problem appears after this [version](https://github.com/scottie1984/swagger-ui-express/blob/master/package.json#L49) because as I said in [this package](https://github.com/BRIKEV/express-jsdoc-swagger) the problem does not happen.

**Comment by mathis-m** [comment]
@kevinccbsg #6827 will fix that. Expect for the invalid json examples when using json media-type:
- xml no valid json sample so it will be rendered as json string
- same for trailing comma in json examples, since this is no valid json
