### ISSUE TITLE
Error rendering XML response with an example

### ISSUE THREAD

**Issue by eduardoj** [swagger-api/swagger-ui#6616]
### Q&A
 - OS: openSUSE Tumbleweed, VERSION="20201111"
 - Browser: Google Chrome 
 - Version: 86.0.4240.198
 - Method of installation: dist assets
 - Swagger-UI version: 3.36.2
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0.0

Tested also with Firefox 82.0.3, and Chromium 86.0.4240.183.

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  description: Error rendering XML with example
  version: "1.0.0"
  title: XML Example Error
paths:
  /about:
    get:
      summary: About
      description: Generic information
      responses:
        '200':
          description: OK. The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api_response'
              example:
                code: ok_json
                summary: Ok json
            application/xml; charset=utf-8:
              schema:
                $ref: '#/components/schemas/api_response'
              example:
                code: ok_xml
                summary: Ok xml
components:
  schemas:
    api_response:
      type: object
      properties:
        code:
          type: string
          xml:
            attribute: True
        summary:
          type: string
      xml:
        name: status
```

### Describe the bug you're encountering

Switching the "Media type" to "application/xml; charset=utf8" results in this error: "😱 Could not render n, see the console."

### To reproduce...

1. Go to your Swagger-UI local instance.
1. Load the provided example yaml file.
1. Click in the "GET /about" endpoint section.
1. Chose the "application/xml; charset=utf8" option from the select box "Media type".
1. See error "😱 Could not render n, see the console.".

### Expected behavior

No error. Instead, this xml should be rendered when switching the "Media type" select box:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<status code="ok_xml">
	<summary>Ok xml</summary>
</status>
```

### Additional context or thoughts

This does not happen in SwaggerHub. Only in my local Swagger-UI instance, created from the `dist` assets.

Link to a working example, in SwaggerHub: https://app.swaggerhub.com/apis/eduardoj/xmlExampleError/1.0.0

This error also does not happen when an `example` section is defined in the `api_response` schema.

And also the error does not happen when the `code` attribute is removed completely from the specification file.

**Comment by hkosova** [comment]
Fixed in v. 3.37.0 (PR https://github.com/swagger-api/swagger-ui/pull/6634).

**Comment by eduardoj** [comment]
Thanks a lot!
