### ISSUE TITLE
two classes inheritance from same model, but swagger generates model differently

### ISSUE THREAD

**Issue by developerTN** [swagger-api/swagger-ui#6622]
Hi,

I have two classes in c# which inherit from same model. I also have a CommandValidator which is the same for the two classes (excat same). Swagger generates one model with fields nullable while the other it generates them as required.

**Comment by hkosova** [comment]
This is not the correct repository for your issue. You need to open an issue with the .NET library you're using - Swashbuckle, Swagger-Net, etc.
