### ISSUE TITLE
External examples' `value` attribute included in response body

### ISSUE THREAD

**Issue by arusahni** [swagger-api/swagger-ui#6626]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Firefox
 - Version: 82
 - Method of installation: dist assets
 - Swagger-UI version: 3.20.5
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  version: v0
  title: My API
servers:
  - url: '/api/v0'
    description: My API Server
tags:
  - name: Example Tag
    description: An example test

paths:
  /example:
    post:
      tags:
        - Example tag
      summary: A bug
      description: >
        Note that the example's `value` property is rendered
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulExampleResponse'

components:
  schemas:

    ExSchema:
      description: An example schema
      type: object
      properties:
        exobj:
          description: The example object.
          example:
            $ref: '#/components/examples/ExObj'

    SuccessfulExampleResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/ExSchema'

  examples:
    ExObj:
      value:
        field_name: field_value
        another_field_name: another_field_value
```

### Describe the bug you're encountering

When using an external, reusable example in the `components` block, the `value` attribute is included in the example response body.

```json
{
  "results": [
    {
      "exobj": {
        "value": {
          "field_name": "field_value",
          "another_field_name": "another_field_value"
        }
      }
    }
  ]
}
```

### To reproduce...

1. Go to https://editor.swagger.io/
2. Paste the sample schema into the editor
3. In the preview pane, expand the panel for the `/example` request
4. Scroll down to the "200" response
5. Observe that the example request includes a `value` hierarchy level.

### Expected behavior

The `value` level should be excluded, with it's children as direct children of the `exobj` field.

### Screenshots

<img width="605" alt="Screen Shot 2020-11-17 at 10 01 03 AM" src="https://user-images.githubusercontent.com/139487/99406395-d441a780-28bb-11eb-91f5-11b4827db8b6.png">

### Additional context or thoughts

The OpenAPI spec requires that external examples have their properties as children of a `value` tag. See ["Reusing Examples"](https://swagger.io/docs/specification/adding-examples/).

**Comment by hkosova** [comment]
Unlike `examples`, the `example` keyword does not support `$ref`. The example must must be specified inline.

**Comment by arusahni** [comment]
Interesting. Thanks for getting to the bottom of this!

**Comment by hkosova** [comment]
Closing in favor of #6628.
