### ISSUE TITLE
Regression: OAS2 response examples are not displayed if response has no schema

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#6631]
Issue #5458 reappeared in v. 3.36.2.

### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome, Firefox (latest)
 - Method of installation: https://editor.swagger.io
 - Swagger-UI version: 3.36.2
 - Swagger/OpenAPI version: 2.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
swagger: "2.0"
info:
  title: OAS2 response examples
  version: 1.0.0
produces:
  - application/json
paths:
  /foo1:
    get:
      summary: Response without a schema
      responses:
        200:
          description: Successful response
          examples:
            application/json:
              foo: custom value
  /foo2:
    get:
      summary: Response with schema
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Foo'
          examples:
            application/json:
              foo: custom value

definitions:
  Foo:
    type: object
    properties:
      foo:
        type: string
        example: bar
```

### Describe the bug you're encountering
v. 3.36.2 has a regression where OAS2 response `examples` are not displayed if the response does not have a `schema` defined. Previous versions of Swagger UI rendered the response examples in this case.

### Expected behavior
Both `GET ​/foo1` and `GET /foo2` should display the same response example:
```json
{
  "foo": "custom value"
}
```

### Actual behavior
`GET ​/foo1` does NOT display a response example. But if you add `schema: {}` to its /foo1's response then the example appears.

### Workaround
Add a `schema` for responses that have examples. Even an empty schema `schema: {}` will work.

**Comment by tim-lai** [comment]
@hkosova I am unable to reproduce the issue as described with the provided definition. When loaded into editor.swagger.io, both endpoints display 
```
{
  "foo": "custom value"
}
```

However, I do observe an issue of updating. If the example in`/foo1` (without schema) is updated in the editor, swagger-ui does not re-render and display the updated value. However, the example in `/foo2` does display the updated value.

**Comment by hkosova** [comment]
@tim-lai you're right, it must have happened during editor updates. Is this a UI issue or editor issue then?

<br>

Steps to reproduce:
1. Paste this spec into editor:
```yaml
swagger: "2.0"
info:
  title: OAS2 response examples
  version: 1.0.0
produces:
  - application/json
paths:
  /foo1:
    get:
      summary: Response without a schema
      responses:
        200:
          description: Successful response

  /foo2:
    get:
      summary: Response with schema
      responses:
        200:
          description: Successful response
          schema: {}
          examples:
            application/json:
              foo: custom value
```
2. In the UI panel, expand both operations.
3. Copy `examples` (but not `schema`) from the second operation's response to the first operation's response.

Expected result: First operation should display newly added response example.

Actual result: Newly added example is not displayed.

**Comment by tim-lai** [comment]
Yup, it's swagger-ui. I can see that the `res` value doesn't reflect incoming arguments to `memoizedSampleFromSchema`. https://github.com/swagger-api/swagger-ui/blob/24225e47bf522b79a872ab9d0758095ef8d701f8/src/core/utils.js#L570
