### ISSUE TITLE
The operation in SwaggerUIBundle is not responsive

### ISSUE THREAD

**Issue by MastersoftGroup** [swagger-api/swagger-ui#6647]
I am using SwaggerUIBundle, everything works fine but I've noticed the operation is not responsive. You can see it when you inspect and switch it to mobile with vertical (tall) view:
![image](https://user-images.githubusercontent.com/22928311/99891291-5b2bc100-2cbc-11eb-8b11-2021b3d1e641.png)

The mobile horizontal (wide) view looks OK:
![image](https://user-images.githubusercontent.com/22928311/99891302-7991bc80-2cbc-11eb-8ee6-46ca9cbf9540.png)

It would be nice if it can get rendered similar like the actual swagger-ui.html:
![image](https://user-images.githubusercontent.com/22928311/99891313-9b8b3f00-2cbc-11eb-98f1-4f0e86d4d365.png)

**Comment by trentprynn** [comment]
+1, I'm developing an [open source daily habit tracking web app](https://github.com/trentprynn/habitapper.com) with [public API documentation](http://localhost:3000/documentation) using swagger-ui react and it looks great on a desktop and not-so-great on a phone (most of my users are mobile so this kind of stinks) 

desktop view (great)
![image](https://user-images.githubusercontent.com/22459581/143687067-bafa5aab-8eae-4663-9989-710f85dc33ec.png)

mobile view (note-so-great -- iphone 13 pro)
<img width="388" alt="image" src="https://user-images.githubusercontent.com/22459581/143687085-87484ade-bce5-4444-9f5d-a392280ab029.png">

**Comment by sshah98** [comment]
is this fixed yet?

**Comment by palmy-investing** [comment]
> is this fixed yet?

This was my solution 
.swagger-ui .opblock .opblock-summary-path {
    max-width: none !important;
}
