### ISSUE TITLE
 Swagger UI not working in IE 

### ISSUE THREAD

**Issue by roymanish1982** [swagger-api/swagger-ui#6655]
Hello,

I have recently update the Swashbuckle.AspNetCore & Swashbuckle.AspNetCore.Swagger from **5.0.0-rc5 to 5.6.3**. For previous version it as working as expected but after update its stops working on IE 
![Capture1](https://user-images.githubusercontent.com/2704397/100080212-928ca000-2e6b-11eb-9def-48cbd7dce066.PNG)
Its working on Chrome & Edge as expected.

Below is the Issue Which its generating:

![Capture2](https://user-images.githubusercontent.com/2704397/100080468-e4352a80-2e6b-11eb-84ae-76ad120b66b6.PNG)
![Capture3](https://user-images.githubusercontent.com/2704397/100080475-e6978480-2e6b-11eb-9c8d-00f014509881.PNG)

**Comment by hkosova** [comment]
Internet Explorer is not supported.
https://github.com/swagger-api/swagger-ui#browser-support
