### ISSUE TITLE
Unable to render this definition.The provided definition does not specify a valid version field

### ISSUE THREAD

**Issue by Parweiz** [swagger-api/swagger-ui#6734]
- OS: Windows 10 Home 64-bit (Version 1909)
 - Browser: Chrome
 - Version: 87.0.4280.88 (Officiel Build) (64-bit)
 - Method of installation: Manual (dotnet add package Swashbuckle.AspNetCore --version 5.6.3)
 - Swagger-UI version: 3.18.3
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: ParkShare API
  description: BackEnd GET/POST/PATCH/DELETE
  version: v1
servers:
  - url: /Test/API
paths:
  XXXXXX
```

Swagger-UI configuration options:
```csharp
public void ConfigureServices(IServiceCollection services)
{

  services.AddDbContextPool<ParkShareDbContext>(options => options.UseSqlServer(Configuration
                .GetValue<string>("ConnectionStrings:ParkShareDB")).UseLazyLoadingProxies());

  services.AddSwaggerGen(c =>
      {
           c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Version = "v1",
                    Title = "ParkShare API",
                    Description = "BackEnd GET/POST/PATCH/DELETE"

                }); 
      });

            
   services
       .AddCors()
       .AddControllersWithViews()
       .AddNewtonsoftJson();


}

 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
 {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.) specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");

            });

            app.UseHttpsRedirection();
            app.UseRouting();

            // global cors policy
            app.UseCors(x => x
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                );

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
}
```

### The bug / issue
I deployed my .NET Core application to a Windows server and I have now an issue about opening the Swagger-UI with the public ip-address. I get this following error:

```
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).
```

It's quite odd for me, because as you can see in the beginning of the yaml code or [Swagger.json file](http://18.193.85.66/Test/API/swagger/v1/swagger.json) then OpenAPI version field is already set to a valid version (3.0.1). I can even copy-paste the json-file into [Editor Swagger](https://editor.swagger.io/) and see the endpoints through that site.

Bonus-info: I don't have this kind of problem, when I run it through localhost. The swagger.json from localhost contains still same openapi version

Many thanks.

**Comment by hkosova** [comment]
This looks like a problem with Swashbuckle, e.g. missing or incorrect configuration. Open an issue in the Swashbuckle repository:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues

**Comment by thetumper** [comment]
Getting the same error message.  And I don't use Swashbuckle.  There's a console error:

YAMLException: end of the stream or a document separator is expected at line 14, column 17
YAMLException: end of the stream or a document sep…i/external/api-docs/swagger-ui-bundle.js:2:377535

But the page renders with an error displaying:

Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

**Comment by hkosova** [comment]
@thetumper please open a new issue and fill in the issue template.
