### ISSUE TITLE
Pretty Print Response JSON

### ISSUE THREAD

**Issue by tavor** [swagger-api/swagger-ui#6737]
### Content & configuration

 Swagger-UI configuration options:
 ```js
 SwaggerUIBundle({
   .  .  .
   printPrintJsonResponse: true
 })
 ```

### Is your feature request related to a problem?
Would make reading JSON responses easier.

### Describe the solution you'd like
By default pretty print json and have the option to show the raw one line

### Describe alternatives you've considered
A chrome extension but none of the extensions I've seen would know what JSON looks like on the Swagger UI and prettify them.

**Comment by hkosova** [comment]
I believe Swagger UI pretty-prints JSON responses by default. What `Content-Type` does your response have? And what version of Swagger UI do you use? (check the `versions` value the dev tools console)

**Comment by tavor** [comment]
Running 3.38.0. `Content-Type` was text, so there was a bug in my code.
