### ISSUE TITLE
Header Field not displaying in SwaggerUI

### ISSUE THREAD

**Issue by hashweather** [swagger-api/swagger-ui#6738]
### Content & configuration

Swagger/OpenAPI definition:
 ```json
    "accounts/me": {
            "get": {
                "tags": [
                    "Account"
                ],
                "summary": "Fetch the account details of the currently logged in user",
                "parameters": {
                    "in": "header",
                    "x-api-key": {
                        "type": "string"
                    }
                }
            }
        }
 ```

 Swagger-UI configuration options:

**Comment by hkosova** [comment]
Your parameter definition is incorrect. Please see the syntax guide for the correct syntax:
OpenAPI 3.0: https://swagger.io/docs/specification/describing-parameters/
OpenAPI 2.0: https://swagger.io/docs/specification/2-0/describing-parameters/

Alternatively, you can define your API key as a security scheme:
OpenAPI 3.0: https://swagger.io/docs/specification/authentication/api-keys/
OpenAPI 2.0: https://swagger.io/docs/specification/2-0/authentication/api-keys/

You can use https://editor.swagger.io to validate your OpenAPI definition, it will flag the lines with syntax errors.
