### ISSUE TITLE
Updated `requestBody` restores to example after closing endpoint view and openning again

### ISSUE THREAD

**Issue by yarsanich** [swagger-api/swagger-ui#6817]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Firefox
 - Version: 84
 - Method of installation: editor.swagger.io
 - Swagger-UI version: 3.39.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Swagger Petstore
  description: This is a sample server Petstore server
  version: 1.0.0
paths:
  /pet:
    post:
      tags:
      - pet
      summary: Add a new pet to the store
      operationId: addPet
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    Pet:
      required:
      - name
      - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        status:
          type: string
          description: pet status in the store
          enum:
          - available
          - pending
          - sold
      xml:
        name: Pet
```

### Describe the bug you're encountering
Updated value in `requestBody` is cleared after closing endpoint.

### To reproduce...

1. Click POST /pet.
2. Click 'Try it out'.
3. Change one parameter in the text editing area. E.G 'id' from 0 to 2.
4. Click POST /pet.
5. Click POSt /pet one more time.
6. Check text editing area.

### Expected behavior
The updated value should be present after closing and opening endpoint

### Screenshots
https://user-images.githubusercontent.com/15478059/104196916-0a6b5580-542d-11eb-9027-9ada789002c9.mov

### Additional context or thoughts
After adding one more supported schema to `requestBody.contents` for example `application/xml`. The updated value is still present after closing and opening again.

https://user-images.githubusercontent.com/15478059/104197349-8fef0580-542d-11eb-8187-20f593f02b2b.mov

After small investigation(downgrading from 3.39.0 to 3.35.0 gradually) an issue was found in [3.35.1](https://github.com/swagger-api/swagger-ui/releases/tag/v3.35.1)

After code check the possible issue might be in next changes: 

* parameter-row: rendering of default/example values of 0 (#6454) (797929f)

* examples multipart array sample generation for items (#6461) (f4bdf2f)

**Comment by mathis-m** [comment]
Currently analyzing this issue. Actually this was introduced by #6518 (3905fadfbea8806be3644e6f45a956f617319403).
@tim-lai This is caused by Parameters Component `onChangeMediaType` calling `oas3Actions.clearRequestBodyValue`.
https://github.com/swagger-api/swagger-ui/blob/3905fadfbea8806be3644e6f45a956f617319403/src/core/components/parameters/parameters.jsx#L80-L93
This is because of `specSelectors.isMediaTypeSchemaPropertiesEqual` does not take into account that incase of currentMediaType and targetMediaType are the same it should return true.
https://github.com/swagger-api/swagger-ui/blob/3905fadfbea8806be3644e6f45a956f617319403/src/core/plugins/spec/selectors.js#L517-L526
Going to fix this via PR by adding following check:
```
  if((currentMediaType || targetMediaType) && currentMediaType === targetMediaType ) {
    return true
  }
```

**Comment by yarsanich** [comment]
@mathis-m thanks for the quick response. Sorry for wrong assumptions about the root cause.

**Comment by mathis-m** [comment]
@yarsanich Thank you for leading me in the right direction and for reporting this issue!
