### ISSUE TITLE
oauth2: "click to authenticate" doesn't work

### ISSUE THREAD

**Issue by tschaffter** [swagger-api/swagger-ui#682]
I have followed the tutorial below to enable oauth2 authentication in my Java project.
http://developers-blog.helloreverb.com/enabling-oauth-with-swagger/

In Swagger UI, an On/Off button (hower message: "click to authenticate") appeared for one of my request. This button is followed by an exclamation point in a red disc (hower message: "write:items", the scope).

The issue is that nothing happens when I click on the On/Off button and no error is thrown in the JS console. What is the expected behavior?

Startup message:
no zlib library shred.bundle.js:1726
no iconv library shred.bundle.js:1734
not a valid 2.0 spec, loading legacy client swagger-ui.js:71
Unable to Load SwaggerUI swagger-ui.js:71
Loaded SwaggerUI swagger-ui.js:71
Loaded SwaggerUI

**Comment by smoebody** [comment]
@tschaffter what step did you miss? im experiencing the same behavior. do you use swagger 1.2 or 2.0?

**Comment by tschaffter** [comment]
Sorry I didn't mention what step I missed... I can only recommend you to look once again closely at every steps of the tutorial. I was using Swagger 1.2.

**Comment by smoebody** [comment]
ok, i think it might be the `loginEndpoint` field which is not available in swagger 2.0 anymore. thanks anyway
