### ISSUE TITLE
HTML Description broken when upgrading

### ISSUE THREAD

**Issue by boris-meerovich-sp** [swagger-api/swagger-ui#6846]
Please, see this [issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1865#issuecomment-762264143)
Swashbuckle.AspNetCore suggest that the problem in swagger-ui
Please, advise

**Comment by hkosova** [comment]
By default, Swagger UI's HTML sanitizer removes inline `style`, `class`, and `data-*` attributes for security reasons. To keep these attributes, you need to configure Swagger UI with [`useUnsafeMarkdown`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-useunsafemarkdown)=`true`.

Check with Swashbuckle if they provide a configuration option for `useUnsafeMarkdown`.

**Comment by hkosova** [comment]
By the way, you can format code blocks in descriptions either using three backticks ` ``` ` or by indenting the line/block with four spaces. In YAML it would looks like:

```yaml
openapi: 3.0.0
info:
  title: Code block test
  version: 1.0.0
  description: |-
    ### Get Token - Sample Request

    ```
    curl -X POST http://site.com -H 'content-type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials&client_id=...&client_secret=...'
    ```

    or

        curl -X POST http://site.com -H 'content-type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials&client_id=...&client_secret=...'

paths: {}
```

![Code blocks in OpenAPI descriptions](https://user-images.githubusercontent.com/8576823/104951999-b2a48f80-59d4-11eb-9a8c-112a74237c3a.png)
