### ISSUE TITLE
Newline in description (CommonMark)

### ISSUE THREAD

**Issue by alex-700** [swagger-api/swagger-ui#6849]
### Q&A (please complete the following information)
 - OS: linux
 - Browser: chromium
 - Version: 87.0.4280.141
 - Method of installation: editor.swagger.io
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
Change `info.description` of pet-store example to the following.
```yaml
info:
  description: | 
    a line 
    should be on the same line
```
### Describe the bug you're encountering

This description must be rendered like an one line [according](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#rich-text-formatting) to [CommonMark spec](https://spec.commonmark.org/0.27/#soft-line-breaks), but it isn't.

It is connected with #3078 #3353 #4653

**Comment by mathis-m** [comment]
@alex-700 could not reproduce with editor:
https://editor.swagger.io/?url=https://gist.githubusercontent.com/mathis-m/69cab38d6fc4d0ceab89f80e4a2ab7cf/raw/3ee3f514cb4ef90a1f2b86c07313b6a7817df428/Pko9ec5me9.txt
```yaml
openapi: 3.0.0
info:
  title: some
  version: asd
  description: | 
    a line 
    should be on the same line
paths:
  /about:
    get:
      summary: About
      description: Retrieves generic information
      responses:
        '200':
          description: Generic information.
```

**Comment by alex-700** [comment]
@mathis-m thanks for checking. Now I know, that `swagger: "2.0"` is important part here. You can try to replace `openapi: 3.0.0` with it and reproduce the bug. 

P.S. The original comment was updated with this important detail.

**Comment by jdegre** [comment]
hi,
i left a comment on the thread of PR #7942, but maybe it does not have much visibility there, so maybe a comment on this "open issue" thread is better...

so, Swagger UI versions prior to 4.9.1 were rendering the description snippet in the OP as one line; that was (imo) correct, according to CommonMark 0.27.

then, after PR #7942, i.e. versions 4.9.1 onward, the rendering changed to two lines; I wonder if that behavior is really compliant to CommonMark spec???

If a 2-line rendering is desired, shouldn't [hard line breaks](https://spec.commonmark.org/0.27/#hard-line-break) be used? (e.g. 2 white spaces, or a "\" char at the end of the line).
