### ISSUE TITLE
Expanding operations triggers a failing network request to "GET /[object%20Module]"

### ISSUE THREAD

**Issue by scottohara** [swagger-api/swagger-ui#6850]
### Q&A (please complete the following information)
 - OS: [e.g. macOS] macOS
 - Browser: [e.g. chrome, safari] chrome
 - Version: [e.g. 22] 89.0.4384.0 (Official Build) dev (x86_64)
 - Method of installation: [e.g. npm, dist assets] N/A (petstore.swagger.io)
 - Swagger-UI version: [e.g. 3.10.0] 3.39.0+
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] 2.0

### Content & configuration

Bug is present on https://petstore.swagger.io

### To reproduce...

1. Go to 'https://petstore.swagger.io'
2. Open DevTools, and go to the Network tab
3. Click on the first operation (/pet/{petId}/uploadImage) to expand it
4. Note the network request to `GET https://petstore.swagger.io/[object%20Module]`, which naturally returns a 404

### Expected behavior

Expanding an operation should not trigger a network request

### Screenshots

![bad](https://user-images.githubusercontent.com/289327/105113685-7cbcf380-5b19-11eb-8cf5-61c00e60656a.png)

**Comment by psaha84** [comment]
After upgrading to the latest version I am also getting the same issue.

**Comment by antt0n** [comment]
I encounter exactly the same bug.

**Comment by mathis-m** [comment]
Introduced with #6709 may be fixed with #6861

**Comment by akshayatbcg** [comment]
Facing the same issue after updating to the latest version. I am using the NestJs swagger UI bundle.
