### ISSUE TITLE
Support configuration of background colour and headerbar (icon)

### ISSUE THREAD

**Issue by maecval** [swagger-api/swagger-ui#6859]
### Is your feature request related to a problem?
**Need to be able to control the background colour (and headerbar/icon) via configuration**
As a user of (springdoc-openapi which uses) swagger-ui in a SpringBoot 2.3 application I want to be able to configure the background colour (and headerbar's clolour/icon) of the Swagger-UI via the configuration of the SpringBoot 2.3 application.
In this application it is a requirement to have different background colours depending on the target environment (e.g. test, staging, production).

### Describe the solution you'd like
**Support configuration of background colour (and headerbar/icon) of the Swagger-UI**
e.g. application.properties
```
swagger-ui.background.colour=#3b4151
```

### Additional context
**setup of SB 2.3 application**
- org.springdoc:springdoc-openapi-ui:1.4.8
- org.webjars:swagger-ui:3.34.0

**Comment by hkosova** [comment]
Hi @maecval, since you request is about springdoc-openapi library configs and not Swagger UI itself, you should post it in the springdoc-openapi repo:
https://github.com/springdoc/springdoc-openapi

Swagger UI colors can be changed by adding custom CSS on top of the default one.

**Comment by maecval** [comment]
Hi Helen, 

Thanks for your quick reply.
**BUT:** I did a 1st request to the springdoc-openapi library and they replied that this is not in their area but in the swagger-ui domain.
see: [springdoc-openapi-ui: Support configuration of background colour and headerbar (icon) #1028 CLOSED](https://github.com/springdoc/springdoc-openapi/issues/1028#issuecomment-763602686)

So please advice how to achieve the requested behaviour.

Thx !

**Comment by hkosova** [comment]
@maecval Swagger UI supports customization of header color and logo via CSS. For example:

```css
.swagger-ui .topbar {
  background-color: lightblue;
}

.topbar-wrapper img {
  content: url(https://placeholder.com/wp-content/uploads/2018/10/placeholder.com-logo1.png)
}
```

There are more examples in https://github.com/swagger-api/swagger-ui/issues/4390
