### ISSUE TITLE
Issue with swagger-ui-react after update: Buffer is not defined

### ISSUE THREAD

**Issue by fedema92** [swagger-api/swagger-ui#6869]
After the update of swagger-ui-react to 3.40.0 this error message appear in console anytime I open the page with swagger component

```
deep-extend.js?383b:32 Uncaught ReferenceError: Buffer is not defined
    at isSpecificValue (deep-extend.js?383b:32)
    at eval (deep-extend.js?383b:132)
    at Array.forEach (<anonymous>)
    at eval (deep-extend.js?383b:110)
    at Array.forEach (<anonymous>)
    at module.exports (deep-extend.js?383b:104)
    at Qr (swagger-ui.js?f5c3:2)
    at SwaggerUI.componentDidMount (index.js?6dc0:59)
    at commitLifeCycles (react-dom.development.js?61bb:20663)
    at commitLayoutEffects (react-dom.development.js?61bb:23426)
```

**Comment by mathis-m** [comment]
Do you use webpack >= 5? I guess this is due to https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed. If so try to add the Node.Js Buffer Polyfill: https://github.com/webpack/changelog-v5/issues/10#issuecomment-615877593

Besides that I could not reproduce the issue. Sandboxes used: [swagger-ui-react](https://codesandbox.io/s/swagger-ui-react-tfjhd?file=/public/index.html:0-1544), [swagger-ui-react-webpack](https://codesandbox.io/s/swagger-ui-react-webpack-gmsf8?file=/webpack.config.js)

**Comment by fedema92** [comment]
> @fedema92 Do you use webpack >= 5? I guess this is due to https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed. If so try to add the Node.Js Buffer Polyfill: [webpack/changelog-v5#10 (comment)](https://github.com/webpack/changelog-v5/issues/10#issuecomment-615877593)
> 
> Besides that I could not reproduce the issue. Sandboxes used: [swagger-ui-react](https://codesandbox.io/s/swagger-ui-react-tfjhd?file=/public/index.html:0-1544), [swagger-ui-react-webpack](https://codesandbox.io/s/swagger-ui-react-webpack-gmsf8?file=/webpack.config.js)

Yes, I had just updated webpack to v6. I hadded the ProvidePlugin to webpack configuration and it works like a charm.

**Comment by DenisLopatin** [comment]
I replaced `"module": "CommonJS"` with `"module": "ES6"` in typescript.config and it worked. I didn't use any polyfiles and used a minimal webpack build.

**Comment by AdithyaGallage** [comment]
> @fedema92 Do you use webpack >= 5? I guess this is due to https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed. If so try to add the Node.Js Buffer Polyfill: [webpack/changelog-v5#10 (comment)](https://github.com/webpack/changelog-v5/issues/10#issuecomment-615877593)
> 
> Besides that I could not reproduce the issue. Sandboxes used: [swagger-ui-react](https://codesandbox.io/s/swagger-ui-react-tfjhd?file=/public/index.html:0-1544), [swagger-ui-react-webpack](https://codesandbox.io/s/swagger-ui-react-webpack-gmsf8?file=/webpack.config.js)

This works for me, thanks @mathis-m
