### ISSUE TITLE
Unresponsive Response body frame when json response are too long

### ISSUE THREAD

**Issue by haizad** [swagger-api/swagger-ui#6881]
- OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.104
 - Method of installation: npm
 - Swagger-UI version: UI 3.x
 - Swagger/OpenAPI version: Swagger 2.0
### Unresponsive Response body frame when json response are too long.
The response body frame exceed the webpage. If you refer Curl section, there is a horizontal scrollbar. Any possibility to add scrollbar into the response body?

### Screenshots
![image](https://user-images.githubusercontent.com/23258127/106408830-31400900-647a-11eb-8b99-641b469e588e.png)

**Comment by mathis-m** [comment]
@haizad this was fixed with [v3.40.0](https://github.com/swagger-api/swagger-ui/compare/v3.39.0...v3.40.0) with #6831.

Verified with https://editor.swagger.io/.

**Comment by haizad** [comment]
Thank you sir.
