### ISSUE TITLE
Custom type parameter in GET action shown as query parameters in Swagger UI.

### ISSUE THREAD

**Issue by bahramzy** [swagger-api/swagger-ui#6892]
In my ASP.NET Web API 2 project I have an Action that takes a complex type as parameter. By default ASP.NET looks for values in the request body for complex types. But Swagger UI does not create the parameter as body parameter type. Swagger UI creates query parameters for every field of my complex type. Whys is that, and how to change this behavior?

## Swashbuckle VERSION: ##
5.6.0

## STEPS TO REPRODUCE: ##
Declare a complex type object, say Person with FirstName and LastName properties.
Write a GET action, SearchPerson(Person person)
Navigate to /swagger/ui
Swagger UI shows the person parameter as query parameter. I would expect Swagger UI to create body parameter for the type Person. How to get this behavior. The endpoint works fine with body parameter from when testing with Poastman.

## EXPECTED RESULT: ##
I would expect Swagger UI to create body parameter for the type Person for this endpoint.

## ACTUAL RESULT: ##
Swagger UI shows the person parameter as query parameter for the endpoint.

## ADDITIONAL DETAILS ##
The endpoint works fine with body parameter from when testing with Poastman.

**Comment by mathis-m** [comment]
@bahramzy 
1. This is a question related to swashbuckle not swagger-ui. This is the wrong place for the issue.
2. Hint: [FromBody] Attribute could solve this.
FYI: https://tools.ietf.org/html/rfc7231#section-4.3.1
>  A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.

**Comment by bahramzy** [comment]
Hi @mathis-m, thanks for your response.
[FromBody] doesn't do anything. That's the default when having complex type parameter in the action. As I mentioned, the endpoint works fine. It expects the payload in the body. I have tested successfully with Postman.

**Comment by mathis-m** [comment]
@bahramzy did you have a look at the generated swagger definition? I guess it's swashbuckle generator who is creating the query definition.
In case the swagger definition states a query param I think it is swashbuckle's responsibility to generate this right.

**Comment by bahramzy** [comment]
Yes, the parameter is defined as query type in the definition.
Ok, I'll report the issue in Swashbuckle repo.
