### ISSUE TITLE
Swagger 2.0 - no client-side validation for required body parameters

### ISSUE THREAD

**Issue by domaindrivendev** [swagger-api/swagger-ui#691]
I'm seeing this behavior on master - is it a known issue?

Also, just wondering if master is the best branch to stay up-to-date with the Swagger 2.0 dev work. Or should I use "develop" instead?

**Comment by domaindrivendev** [comment]
Hey there - just wondering what's the plan for getting this into a swagger-ui alpha release. I'm using v2.1.0-alpha.6 and am still able to repro

**Comment by fehguy** [comment]
Hi, it's slated for release this week in 2.1.0-M1.  I'll reopen this just to make sure it's tested for the release.

**Comment by domaindrivendev** [comment]
@fehguy - thanks, I really appreciate the quick response.

Also just came across this - #857 and thought it might be worth looking at before release

Finally, what does the "-M1" stand for in the tag name? Are you getting close to a stable release? This would be awesome, as my project is sitting in an alpha state pending a stable release of swagger-ui

Cheers

**Comment by webron** [comment]
@domaindrivendev - the M1 is the first milestone release of the UI before a final version. It's release should be very soon.

**Comment by fehguy** [comment]
confirmed fixed for M1.
