### ISSUE TITLE
Nesting of schema is not working in latest version

### ISSUE THREAD

**Issue by anshul7931** [swagger-api/swagger-ui#6926]
![image](https://user-images.githubusercontent.com/16503842/107351945-41e32580-6af1-11eb-93ca-8430d009f8a1.png)

Trying with the above schema structure on 3.40 bundle where an error is coming, but in 3.18 bundle this schema structure was working fine. 
Functionality wise the response is coming as expected, but this error is getting logged in the UI.

Schema Structure:

components:
    schema:
        SCHEMA_FILE_WEBWB_PZADDFOLLOWERS:
              title: "users"
              type: "array"
              items:
                $ref: "#/components/schemas/SCHEMA_FILE_WEBWB_PZADDFOLLOWERS/components/schema/User"
              components:
                    schema:
                      User:
                        title: "user"
                        type: "object"
                        properties:
                           nestedProp:
                            title: "nestedProp"
                            type: "string"
Error: 

Structural error at components.schemas.SCHEMA_FILE_WEBWB_PZADDFOLLOWERS
should NOT have additional properties
additionalProperty: components
Jump to line 3911

**Comment by hkosova** [comment]
The `User` schema is in a wrong place. It must be in the global `components/schemas` section, on the same level as `SCHEMA_FILE_WEBWB_PZADDFOLLOWERS`.

Here's the correct version:
```yaml
components:
  schemas:
    SCHEMA_FILE_WEBWB_PZADDFOLLOWERS:
      title: "users"
      type: "array"
      items:
        $ref: "#/components/schemas/User"  # <-----------
  
    User:             # <-----------
      title: "user"
      type: "object"
      properties:
        nestedProp:
          title: "nestedProp"
          type: "string"
```

**Comment by anshul7931** [comment]
@hkosova But this schema is working fine with the earlier version and even with version the results are coming along with the error message in UI. 
In our use case, we are generating this schema from a yaml file in runtime. So we can have this kind of structure there.
