### ISSUE TITLE
Validation error if an empty integer parameter is passed that is not mandatory

### ISSUE THREAD

**Issue by TactiusTertius** [swagger-api/swagger-ui#6927]
### Q&A 
 - OS: Windows 10
 - Browser: chrome
 - Version: 88.0.4324.150
 - Method of installation: npm
 - Swagger-UI version: 3.42.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### Content & configuration
"FDBTitleFilter--titletypeid": {
                "name": "titletypeid",
                "in": "query",
                "description": "to filter by title type id.",
                "required": false,
                "schema": {
                    "type": "integer",
                    "format": "int32",
                    "nullable": true
                },
                "example": null
            }

### Describe the bug you're encountering
Since version 3.42.0 there is a validation error if there is no input for an integer defined field.
It is irrelevant whether the parameter was declared nullable or not.

### To reproduce...

1. Define an integer request parameter that is not required
2. Perform a query with empty parameter

### Expected behavior
See screenshot

### Screenshots
![image](https://user-images.githubusercontent.com/76955781/107531483-2e9d8c00-6bbd-11eb-8966-8974d0ad05df.png)

**Comment by mathis-m** [comment]
Minimal Reproduction yaml: https://editor.swagger.io/?url=https://gist.githubusercontent.com/mathis-m/c91a866c88a62e8cd2c9cf4f509ca757/raw/8d6fbfe50f2be1f15cee622297a721bd8ca79b1a/MMvSCoiMOH.txt
