### ISSUE TITLE
Request Headers could be displayed when you "Try it out!"

### ISSUE THREAD

**Issue by ecourreges-orange** [swagger-api/swagger-ui#693]
When you click "Try it out!",
Everything from the request/response is there and displayed nicely in the UI except for the Request Headers which are necessary for some APIs.
As such you are forced to use firebug or wireshark on the side to get them.

**Comment by webron** [comment]
Fix is merged in develop_2.0.

**Comment by 73J35H** [comment]
Does Swagger UI displays Request Headers in the UI?
