### ISSUE TITLE
Unable to Remove escape characters in Example value given in Api Docs where As in Swagger Ui automatically it will remove. I have an Escape characters and new line in My Api 

### ISSUE THREAD

**Issue by Venkob** [swagger-api/swagger-ui#6940]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by hkosova** [comment]
I'm going to close this because you didn't fill in the information requested in the issue template.

Feel free to open a new issue, but please provide all the requested details. We won't be able to help otherwise.
