### ISSUE TITLE
Swagger 3.x version not loading in IE and also not showing any error in console

### ISSUE THREAD

**Issue by Mrinnaal** [swagger-api/swagger-ui#6957]
Is there any way i can inject any js to make Swagger 3.x UI work in Internet Explorer?

**Comment by hkosova** [comment]
Internet Explorer is not supported.

https://github.com/swagger-api/swagger-ui#browser-support

> **Browser support**
> Swagger UI works in the latest versions of Chrome, Safari, Firefox, and Edge.

A possible workaround might be to run Swagger UI's assets through a browser-targeting transpiler (e.g. `babel-preset-env` with IE11 configured as a target), as was [suggested here](https://github.com/swagger-api/swagger-ui/issues/5808#issuecomment-578462941).

**Comment by Mrinnaal** [comment]
@hkosova I tried configuring it with IE 11 but still the SwaggerUI bundle error is thrown.

'SwaggerUIBundle' is undefined. Any suggestions on that?

**Comment by Mrinnaal** [comment]
@hkosova  after updating it like this, it seems to work in IE:
presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset,
          **'@babel/preset-env',
          { 'targets': { "ie": "11" } }**
        ]

But, when i try to access the same through CefSharp browser, it throws me script error. Any suggestions?
