### ISSUE TITLE
Response Messages > HTTP Status Code > Sort ASC order

### ISSUE THREAD

**Issue by tschaffter** [swagger-api/swagger-ui#696]
Sort response message by their HTTP status code in ASC order

**Comment by fehguy** [comment]
will do this in M2

**Comment by mohsen1** [comment]
If you mean responses in operation they're already sorted.

For this specs, this is what I get:
```
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Pets Store"
    },
    "paths": {
        "/pets": {
            "get": {
                "responses": {
                    "500": {
                        "description": "Wow"
                    },
                    "200": {
                        "description": "Returns all the pets"
                    },
                    "400": {
                        "description": "blah"
                    },
                                        "302": {
                        "description": "One of responses"
                    }
                }
            }
        }
    }
}
```
@fehguy can we close this?


![screen shot 2015-03-05 at 12 43 24 pm](https://cloud.githubusercontent.com/assets/543633/6514182/413f4aec-c335-11e4-9116-30bdad2c95aa.png)

**Comment by fehguy** [comment]
if we're sorting them in the UI by key then yes.

**Comment by mohsen1** [comment]
Yes, `responseMessages` array is already sorted. Closing. 

@tschaffter Please let me know if you're still having this issue.

**Comment by skironDotNet** [comment]
When option servers is used 
![image](https://github.com/swagger-api/swagger-ui/assets/2981715/0547abe6-fd14-473f-86eb-34543973b74e)

the responses are not sorted 
![image](https://github.com/swagger-api/swagger-ui/assets/2981715/d2a0799d-f73d-48b6-b9b0-11c2a354ba09)

**Comment by skironDotNet** [comment]
@mohsen1 the order is swagger.json look at your own answer 500,200,400
and it's random, hard to do text based compare
