### ISSUE TITLE
Mix Content Issue with Kestrel Running behind Proxy

### ISSUE THREAD

**Issue by kritsda-jiwatrakan** [swagger-api/swagger-ui#6960]
Can we please remove security feature where it checks mix content between HTTP and HTTPS?  .NET Core Kestrel suggest that we can run behind local proxy without SSL.  This breaks it if we run Kestrel behind Apache or Nginx on Linux.  Please reconsider or build something that takes in configuration to shut that off. Forwarding header doesn't help.

Thank you,

**Comment by hkosova** [comment]
Closing as this question doesn't seem to be about Swagger UI.
