### ISSUE TITLE
Can't use named import for component Parameters in base.js

### ISSUE THREAD

**Issue by suhasbhatta** [swagger-api/swagger-ui#6969]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Method of installation: npm
 - Swagger-UI version: v3.19.3
 - Swagger/OpenAPI version: Swagger 2.0

### Describe the bug you're encountering
npm build is failing with the following error. 
```

WARNING in ./src/core/presets/base.js 123:18-28
"export 'Parameters' was not found in '../components/parameters'
 @ ./src/core/presets/apis.js
 @ ./src/core/index.js
 @ multi ./src/polyfills.js ./src/core/index.js
 ```

**Comment by tim-lai** [comment]
@suhasbhatta Are you using the latest version of SwaggerUI? `swagger-ui@3.19.3` is pretty old.

**Comment by tim-lai** [comment]
@suhasbhatta Closing this issue along with its corresponding PR (fails CI). There might be a configuration issue with your setup. If you are still having issues, please feel free to open another ticket. Thanks.
