### ISSUE TITLE
For Forms: Enum Contains Default Against Configuration, and Default is Unsubmittable Anyways

### ISSUE THREAD

**Issue by MarioIshac** [swagger-api/swagger-ui#6976]
### Q&A (please complete the following information)
 - OS: Ubuntu 20.04.1
 - Browser: Firefox, Chrome
 - Installation: Tested on editor.swagger.io
 - Swagger-UI version:  3.43.0
 - Swagger/OpenAPI version: OpenAPI 3.0.3

### Content & configuration
```yaml
openapi: 3.0.3
paths:
  /test:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema: 
              $ref: '#/components/schemas/TestBody'
components:
  schemas:
    TestBody:
      required:
        - test_enum
      type: object
      properties:
        test_enum:
          allOf:
            - $ref: "#/components/schemas/TestEnum"
    TestEnum:
      enum:
        - A
        - B
```
Plug into editor.swagger.io.

### Describe the bug you're encountering
1) Enum contains default even though no default was configured.
2) Leaving default selected leaves request unsubmittable with red visual indicator, must manually select.

### To reproduce
1. Expand /test.
2. Press Try it out.
3. Press execute.
4. See red visual indicator.

### Expected behavior
Enum should not have default available in first place, but looking past this, the default should be submittable anyways. Instead, manual selection is required. Not sure if these bugs are related or separate.

### Screenshots
![Submission](https://user-images.githubusercontent.com/14341439/108593380-2c0f0500-7328-11eb-929b-e67ca0450731.png)

### Additional Context
Same issue as https://github.com/swagger-api/swagger-ui/issues/3706 and https://github.com/swagger-api/swagger-ui/issues/3890, both closed in 2017. 

This applies to enums in form bodies, not as parameters (see below comments). So `application/x-www-form-urlencoded` and `multipart/form-data` are affected.

**Comment by mathis-m** [comment]
valid Minimal Reproduction:
https://editor.swagger.io/?url=https://gist.githubusercontent.com/mathis-m/c3c097c16174acad5415affcc22886e1/raw/7cd158e43b1062aeb4c1eea5ffa88af7824cefc0/KCgSSD1Lqe.txt

```yaml
openapi: 3.0.3
info:
  title: asd
  version: 0.0.1
paths:
  /test:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema: 
              $ref: '#/components/schemas/TestBody'
      responses:
        200:
          description: ok
components:
  schemas:
    TestBody:
      required:
        - test_enum
      type: object
      properties:
        test_enum:
          allOf:
            - $ref: "#/components/schemas/TestEnum"
    TestEnum:
      enum:
        - A
        - B
```

**Comment by mathis-m** [comment]
Could you include `multipart/form-data` in the issues description and title because I could not reproduce this for parameters.
``

**Comment by MarioIshac** [comment]
Thanks for fixing up my example to add the fields I missed, and will change title & description to include `multipart/form-data` (and also `application/x-www-form-urlencoded`, was able to reproduce w/ that).
