### ISSUE TITLE
Show default value if the parameter is required

### ISSUE THREAD

**Issue by MaelREBOUX** [swagger-api/swagger-ui#698]
I wanted to document a very simple API, all parameters in the URL.

Some "base" parameters are mandatory and we can recommend to set a default value for helping test the API throught swagger.
Example : "version=1.0"

When the parameter is required, it may make sense to auto-fill that value. In either case, documentation-wise, the default value should be represented in the UI 

Read more on the mailing-list : https://groups.google.com/forum/#!topic/swagger-swaggersocket/ft2LUc4xxiQ

```
"parameters": [
            {
                "name": "key",
                "in": "query",
                "description": "Clé d'accès fournie lors de l'inscription.",
                "required": true,
                "type": "string"
            },
            {
                "name": "version",
                "in": "query",
                "description": "Version de l'APi à laquelle on passe la commande.",
                "required": true,
                "type": "string",
                "format": "string",
                "default": "1.0"
            }
        ]
```

In this screenshot, off the api key, all parameters have default values :

![screenshot151](https://cloud.githubusercontent.com/assets/6370443/4828869/313a527e-5f83-11e4-9a02-d30330212550.png)

Thank you for this fix.

**Comment by zh-wowtv** [comment]
Doesn't work in new Swagger version.

**Comment by webron** [comment]
If an issue exists, please file a new ticket.
