### ISSUE TITLE
OAuth 2.0 Access token is not refreshed with refresh token 

### ISSUE THREAD

**Issue by eugcomax** [swagger-api/swagger-ui#6991]
### Q&A (please complete the following information)
 - Swagger-UI version: 3.0.0

I use Authorization code flow. I'm able to get a bearer token that looks like:
{
  "code": null,
  "access_token": "",
  "refresh_token": "",
  "scope": "",
  "token_type": "Bearer",
  "expires_in": 300
}

The trouble that I experience is that access_token is not refreshed after expires_in time passed. I passed refreshUrl url which should be used for refreshing access token but from documentation it's a url which is used to acquire a refresh token. So the question is how to set url to use for refreshing access tokens?
Could you please point me to the part of code which is responsible for access_token refreshing?

### Screenshots

![](https://user-images.githubusercontent.com/5268682/108386359-40aea880-7215-11eb-8182-b223d0d745ae.png)

### How can we help?
Could you please point me to the part of code which is responsible for access_token refreshing.

**Comment by labedzkim** [comment]
Hi @eugcomax, have You resolved this issue? I'm getting the same with version 3.46.0. Best regards, Maciej.

**Comment by eugcomax** [comment]
Hi @labedzkim , no. I use springfox and I wasn't sure if it's a swagger or springfox issue so I just closed it. 
There's the same issue but with springdoc: [https://github.com/swagger-api/swagger-ui/issues/7257](url) It really looks like that it's a swagger issue

**Comment by eugcomax** [comment]
It's a duplicate of https://github.com/swagger-api/swagger-ui/issues/7257
