### ISSUE TITLE
Required parameters of type enum should be visualised as required

### ISSUE THREAD

**Issue by ilons** [swagger-api/swagger-ui#700]
Swagger UI version: 2.1.0-alpha.3 (Confirmed in older version as well)
Scenario: When setting required=true on a parameter of type enum, the UI should visualise it the same way as it does with other parameters.

Current behaviour: Shows up in the same way as a non required enum.
Expected behaviour: Shows up with parameter name and description in bold.

	 *    @SWG\Parameters(
	 *     @SWG\Parameter(
	 *      name="API_ACCESS_TOKEN",
	 *      description="Authentication token",
	 *      paramType="header",
	 *      type="string",
	 *      required=true
	 *     ),
	 *     @SWG\Parameter(
	 *      name="Content-type",
	 *      description="Content type for request",
	 *      paramType="header",
	 *      type="string",
	 *      enum="['application/json','application/xml','text/xml','text/json']",
	 *      required=true
	 *     ),
	 *     @SWG\Parameter(
	 *      name="Accept",
	 *      description="Response content type, could be used to return json response for a xml request",
	 *      paramType="header",
	 *      type="string",
	 *      enum="['application/json','application/xml','text/xml','text/json']",
	 *      required=false
	 *     ),
	 *     @SWG\Parameter(
	 *      description="Create video requests",
	 *      paramType="body",
	 *      type="CreateVideoRequests"
	 *     )
	 *    )

![screen shot 2014-10-30 at 13 35 10](https://cloud.githubusercontent.com/assets/6905634/4843364/428274ae-6031-11e4-9844-e3a30abfe73c.png)

Is this the expected behaviour, a bug or did I do something wrong?

**Comment by fehguy** [comment]
I believe this has been fixed, but will move to M2 for verificaiton.

**Comment by mohsen1** [comment]
This is still a bug currently(a20825e).

**Comment by mohsen1** [comment]
This was fixed by 13ac198da20ce11cde81f663c07046fd83c4ec94
