### ISSUE TITLE
How to add FilterContainer to swagger-ui-react?

### ISSUE THREAD

**Issue by alexrejto** [swagger-api/swagger-ui#7002]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 88.0.4324.182
 - Method of installation: yarn add swagger-ui-react
 - Swagger-UI version: 3.35.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml

```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by mathis-m** [comment]
@alexrejto using the following Swagger-UI configuration options:

```js
SwaggerUI({
  filter: true
})
```

```
?filter=true
```

Example:
https://petstore3.swagger.io/?filter=pet

**Comment by alexrejto** [comment]
I'm beyond interested in your PR #6851. In the mean time, I was hoping to use the basic filter. I use swagger-ui-react so am unable to pass filter through to the swaggerUI instance. Is there a workaround?

**Comment by alexrejto** [comment]
Resolved! The solution was a plugin to the filter state selector.
```
const enableFilterPlugin = function(system) {
  return {
    statePlugins: {
      layout: {
        selectors: {
          currentFilter: (state) => (state.get('filter') == null ? true : state.get('filter')),
        },
      },
    },
  };
};
```

**Comment by mathis-m** [comment]
@alexrejto I think it you can keep the issue open. 
Cc @tim-lai shall the filter configuration not be available through `swagger-ui-react`. Eg. `<SwaggerUI filter="true" />`.

**Comment by maicWorkGithub** [comment]
docker `-e filter=true` not work, help
