### ISSUE TITLE
Send JSON from UI?

### ISSUE THREAD

**Issue by johncox00** [swagger-api/swagger-ui#704]
Is it possible to send JSON rather than form data from SwaggerUI's "Try it now" feature? Am I missing something?

**Comment by coder32** [comment]
Please Help me to resolve this same issue . I am trying to post json from UI but it returns array(0) in PHP . What i am missing . Please let me know . 
Here is my json file 
{
    "basePath": "apis/item/",
    "swaggerVersion": "1.2",
    "apiVersion": "0.2",
    "resourcePath": "/item",
    "apis": [
        {
            "path": "save_item",
            "operations": [
                {
                    "method": "post",
                    "summary": "Add New Inventory Item",
                    "nickname": "add inventory item",
                    "parameters": [
                        {
                            "paramType": "header",
                            "name": "Access_token",
                            "type": "string",
                            "required": true,
                            "description": "Access token"
                        },
                        {
                            "paramType": "header",
                            "name": "License_id",
                            "type": "string",
                            "required": true,
                            "description": "License ID"
                        },
                        {
                            "paramType": "header",
                            "name": "Device_id",
                            "type": "string",
                            "required": true,
                            "description": "Device ID"
                        },
                        {
                            "paramType": "header",
                            "name": "User_id",
                            "type": "integer",
                            "required": true,
                            "description": "User id"
                        },
                        {
                            "paramType": "header",
                            "name": "Store_id",
                            "type": "integer",
                            "required": true,
                            "description": "Store id"
                        },
                        {
                            "paramType": "body",
                            "name": "data",
                            "type": "json_array",
                            "required": true,
                            "description": "valid json to add item"
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 400,
                            "message": "Invalid request"
                        },
                        {
                            "code": 404,
                            "message": "Not found"
                        }
                    ],
                    "notes": "get department api"
                }
            ]
        },
        {
            "path": "verify_coupon",
            "operations": [
                {
                    "method": "post",
                    "summary": "Verify Coupon And Get Details",
                    "nickname": "verify coupon",
                    "parameters": [
                        {
                            "paramType": "header",
                            "name": "Access_token",
                            "type": "string",
                            "required": true,
                            "description": "Access token"
                        },
                        {
                            "paramType": "header",
                            "name": "License_id",
                            "type": "string",
                            "required": true,
                            "description": "License ID"
                        },
                        {
                            "paramType": "header",
                            "name": "Device_id",
                            "type": "string",
                            "required": true,
                            "description": "Device ID"
                        },
                        {
                            "paramType": "header",
                            "name": "User_id",
                            "type": "integer",
                            "required": true,
                            "description": "User id"
                        },
                        {
                            "paramType": "header",
                            "name": "Store_id",
                            "type": "integer",
                            "required": true,
                            "description": "Store id"
                        },
                        {
                            "paramType": "form",
                            "name": "code",
                            "type": "string",
                            "required": true,
                            "description": "Valid Coupon Code"
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 400,
                            "message": "Invalid request"
                        },
                        {
                            "code": 404,
                            "message": "Not found"
                        }
                    ],
                    "notes": "verify coupon api"
                }
            ]
        },
        {
            "path": "get_applied_coupons",
            "operations": [
                {
                    "method": "post",
                    "summary": "Get All Applied Coupon By search ID",
                    "nickname": "get coupon",
                    "parameters": [
                        {
                            "paramType": "header",
                            "name": "Access_token",
                            "type": "string",
                            "required": true,
                            "description": "Access token"
                        },
                        {
                            "paramType": "header",
                            "name": "License_id",
                            "type": "string",
                            "required": true,
                            "description": "License ID"
                        },
                        {
                            "paramType": "header",
                            "name": "Device_id",
                            "type": "string",
                            "required": true,
                            "description": "Device ID"
                        },
                        {
                            "paramType": "header",
                            "name": "User_id",
                            "type": "integer",
                            "required": true,
                            "description": "User id"
                        },
                        {
                            "paramType": "header",
                            "name": "Store_id",
                            "type": "integer",
                            "required": true,
                            "description": "Store id"
                        },
                        {
                            "paramType": "form",
                            "name": "search",
                            "type": "string",
                            "required": false,
                            "description": "Filter records, Search Coupons by this api . Send Empty Field To get all valid Coupons And Fetch Record According to any column name like [ item_id:65 , department_id:2 , category_id:6 ]"
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 400,
                            "message": "Invalid request"
                        },
                        {
                            "code": 404,
                            "message": "Not found"
                        }
                    ],
                    "notes": "verify coupon api"
                }
            ]
        },
        {
            "path": "add_favorite",
            "operations": [
                {
                    "method": "post",
                    "summary": "Add items in Favorite List",
                    "nickname": "add favorite",
                    "parameters": [
                        {
                            "paramType": "header",
                            "name": "Access_token",
                            "type": "string",
                            "required": true,
                            "description": "Access token"
                        },
                        {
                            "paramType": "header",
                            "name": "License_id",
                            "type": "string",
                            "required": true,
                            "description": "License ID"
                        },
                        {
                            "paramType": "header",
                            "name": "Device_id",
                            "type": "string",
                            "required": true,
                            "description": "Device ID"
                        },
                        {
                            "paramType": "header",
                            "name": "User_id",
                            "type": "integer",
                            "required": true,
                            "description": "User id"
                        },
                        {
                            "paramType": "header",
                            "name": "Store_id",
                            "type": "integer",
                            "required": true,
                            "description": "Store id"
                        },
                        {
                            "paramType": "form",
                            "name": "item_id",
                            "type": "integer",
                            "required": true,
                            "description": "Item ID"
                        },
                        {
                            "paramType": "form",
                            "name": "is_favorite",
                            "type": "integer",
                            "enum": [0, 1],
                            "default": 0,
                            "required": true,
                            "description": "is favorite or not (1,0)"
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 400,
                            "message": "Invalid request"
                        },
                        {
                            "code": 404,
                            "message": "Not found"
                        }
                    ],
                    "notes": "verify coupon api"
                }
            ]
        }
    ],
    "produces": [
        "application/json"
    ]
}


When i am using paramType 'form' . it works fine but when i try to send JSON as paramType 'body' it returns null array .

**Comment by coder32** [comment]
@webron Please help me to fix this .

**Comment by webron** [comment]
This is an issue that was closed in 2014, we're in 2018. Nothing in the current code base is related to that code base. If you have any similar issues, please file a new ticket.
