### ISSUE TITLE
Veracode Issue CWE259 reported in SwaggerUICore

### ISSUE THREAD

**Issue by Joyaprita** [swagger-api/swagger-ui#7058]
Veracode Vulnerabilities **Use of Hard-coded Password (CWE ID 259)** reported in the below path-

Path for the reported issue -
 SwaggerUICore/src/core/components/auth/oauth2.jsx  line 129

can you let us know any ETA for this issue to be fixed.

Link for Veracode issue details ->
http://cwe.mitre.org/data/definitions/259.html

**Comment by hkosova** [comment]
Duplicate of #7057
