### ISSUE TITLE
Execute button becomes unresponsive when an optional field is omitted

### ISSUE THREAD

**Issue by vy** [swagger-api/swagger-ui#7086]
### Setup
 - OS: Xubuntu 20.04.2 LTS
 - Browser: Brave
 - Version: 1.21.74 Chromium: 89.0.4389.72
 - Method of installation: `org.webjars.npm:swagger-ui-dist` Maven Artifact
 - Swagger-UI version: 3.42.0, 3.43.0, 3.44.0, 3.44.1, 3.45.0, 3.46.0
 - Swagger/OpenAPI version: Swagger 2.0

### Configuration

```yaml
swagger: '2.0'
info:
  version: '1.0'
  title: v1
tags:
  - name: Order Candidates V1
paths:
  '/v1/order-candidates':
    put:
      tags:
        - Order Candidates V1
      summary: Set order delivery location
      operationId: setDeliveryLocation
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: The delivery location for the item.
          required: false
          schema:
            $ref: '#/definitions/OrcaDeliveryLocation'
      responses:
        '200':
          description: successful operation
definitions:
  OrcaDeliveryLocation:
    type: object
    properties:
      pickupLocation:
        $ref: '#/definitions/PickupPointLocation'
  PickupPointLocation:
    type: object
    required:
      - validated
    properties:
      validated:
        type: boolean
```

### Actual behavior

After clicking to _Try it out_ button of `PUT /v1/order-candidates` method, Swagger auto-fills the `body`. Clicking on _Execute_ executes the request as expected. When the optional (i.e., not `required`) `pickupLocation` entry is removed from the `body`, clicking on _Execute_ doesn't respond.

### Expected behavior

When the optional (i.e., not `required`) `pickupLocation` entry is removed from the `body`, clicking on _Execute_ should execute the request.

### Additional context

Issue is reproducible on 3.42.0, 3.43.0, 3.44.0, 3.44.1, 3.45.0, 3.46.0 versions of the Maven artifact. The issue disappears on 3.41.1. As of this date, one can also reproduce the issue using https://editor.swagger.io/ website.

**Comment by WinniX** [comment]
Does anybody know the status on this one? If it's not so easy to fix - please tell us, so we just downgrade to the 3.41.1. 
Thanks in advance!

**Comment by vy** [comment]
Thanks so much @mathis-m! It indeed fixes the problem. Great job!
