### ISSUE TITLE
"Structural error" message for responses '2XX', '4XX' etc.

### ISSUE THREAD

**Issue by marcuszierke** [swagger-api/swagger-ui#7093]
I tried to define a range for potential status codes like

```
      responses:
        '2XX':
          description: "OK"
          schema:
            $ref: "#/definitions/customerRisk"
        "4XX":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/Problem"
        "5XX":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Problem"
```

I am getting the following error message: "Structural error at [...] should only have three-digit status codes, `default`, and vendor extensions (`x-*`) as properties" but I can't see how I should adjust the swagger to match the docs description / example https://swagger.io/docs/specification/describing-responses/ (under HTTP STATUS CODES).

Can anybody help with this issue? Thanks!

**Comment by hkosova** [comment]
Response ranges are only supported in OpenAPI 3 (`openapi: 3.x.x`). They are not supported in OpenAPI 2.0 (`swagger: '2.0'`).
