### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by rdiehl** [swagger-api/swagger-ui#710]
We are using the latest version of swagger and swagger-ui, hitting an Apache CXF backend with dynamically generated endpoints.  We currently have around 30 documented endpoints, that number will double over time as we port from SOAP to REST.  When we load the swagger docs page, the list of endpoints loads relatively quickly, within 1-2 seconds.  However, all of the individual endpoints are not fully loaded for 10-15 seconds.  I can use the Chrome dev tools to watch the timeline, each individual request takes about 2 seconds for the actual request.

I have 2 questions.  First, does the swagger-ui project have a way to display a loading indicator for each endpoint?  Ideally it would show as loading from the point that the view is initially added, until the request comes back.

Secondly, is there a way to improve the speed for the api-docs requests?  Since we are using CXF and dynamically generating the endpoints, I assume that's where the slowness is coming in.  Is that something I would need to post in the swagger-core group?

Thanks in advance,
Ryan

**Comment by wahyufrombandung** [comment]
My solved solutions (Using C# .Net in visual studio 2015):
on your code, check the upper part of every controller that needs to be accessed from swagger, please add comments below:
`/// <summary>
        /// 
        /// </summary>
        /// <param name="fromDate"></param>
        /// <param name="toDate"></param>
        /// <param name="transactionType"></param>
        /// <param name="options"></param>
        /// <param name="mini"></param>
        /// <returns></returns>`

then between the controller and the comments, put the swagger access as follows:
`[VersionedRoute("your-versioned-route")]
        [Authorize(Roles = "your roles")]
        [ResponseType(typeof(return type ))]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(return type))]
        [HttpPost] //access method
        [ActionName("yourControllerActionName")]`


NB: don't forget to make sure the return type provided by the controller is the same as the return type you provide to swagger. in my problems , i have forget to put the right return type so the swagger is finding the viewmodel that i never pass

hope it can helps
