### ISSUE TITLE
Which files in "dist" are actually needed? Documentation needed.

### ISSUE THREAD

**Issue by M-Reimer** [swagger-api/swagger-ui#7106]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Firefox
 - Version: 86.0.1
 - Method of installation: dist
 - Swagger-UI version: always latest
 - Swagger/OpenAPI version: OpenAPI 3.0 (would prefer 3.1 but not supported by Swagger UI)

### How can we help?

I use Swagger UI in a business project. For convenience reasons the whole project (which includes the Swagger UI files) is in one big GIT repo.

Now I'm wondering which files in your "dist" I actually have to put on my server and which ones can be left out as they are not used at all.

I'm using your provided "index.html" which has:
```
    <script src="./swagger-ui-bundle.js" charset="UTF-8"> </script>
    <script src="./swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
```

So I'll need "**swagger-ui-bundle.js**" for sure.

What is this "**swagger-ui-standalone-present.js**" about? What does it do?

What about all the other ".js" files:

- swagger-ui-es-bundle-core.js
- swagger-ui-es-bundle.js
- swagger-ui.js

Can they be left out or does "swagger-ui-bundle.js" load them in some situation?

**Comment by tim-lai** [comment]
@M-Reimer `swagger-ui-bundle.js` and `swagger-ui-standalone-preset.js` are the two `dist` files needed by most users. The other files cited are alternative bundle module formats.
