### ISSUE TITLE
Problems with "/api-docs/{path}", WAS + ApacheWink JAX-RS + swagger-servlet

### ISSUE THREAD

**Issue by tokra** [swagger-api/swagger-ui#711]
Hi,
I am using WAS with JAX-RS (implementation Apache Wink).
My configuration web.xml:
![image](https://cloud.githubusercontent.com/assets/2188084/4937200/4ad89256-65c1-11e4-9c3f-3705909b5782.png)

![image](https://cloud.githubusercontent.com/assets/2188084/4937207/536d88ea-65c1-11e4-8162-3053f83c6644.png)

![image](https://cloud.githubusercontent.com/assets/2188084/4937218/5ed93580-65c1-11e4-97ae-499471bf078e.png)

My REST resource class:
![image](https://cloud.githubusercontent.com/assets/2188084/4937222/6e2c03a0-65c1-11e4-9152-5e86dab59c39.png)

and one more called Math.

So REST api is accessible via:
http://localhost:9080/api/hello/{name}  ...works fine
http://localhost:9080/api/math/{count}  ...works fine

Swagger Api-docs are accessible via:
http://localhost:9080/api-docs/ ... ok
but resources like:
   http://localhost:9080/api-docs/hello
   http://localhost:9080/api-docs/math
...returns 404

I have swagger-ui in root:
http://localhost:9080/swagger/index.jsp ...ok

Problem is that api-docs generates this:
![image](https://cloud.githubusercontent.com/assets/2188084/4937230/7c5a30fa-65c1-11e4-908f-f5f7586cff41.png)
![image](https://cloud.githubusercontent.com/assets/2188084/4937234/8609b364-65c1-11e4-9f22-2035dc0e0c31.png)
![image](https://cloud.githubusercontent.com/assets/2188084/4937242/99123ecc-65c1-11e4-886d-91c04bceec82.png)

which leads to : 
![image](https://cloud.githubusercontent.com/assets/2188084/4937138/c4969eae-65c0-11e4-8852-ffa3813da0ee.png)

So its not grouping APIs like here:
![image](https://cloud.githubusercontent.com/assets/2188084/4937151/e12dd046-65c0-11e4-9514-c2bee92ca160.png)

How can I achieve that grouping of API methods under APIs ???

**Comment by adityadha** [comment]
Hi to-kra,

I have done exactly same configuration in web.xml and i am using WAS+Wink. When i hit url for api-docs this is what i get. {"apiVersion":"1.0.0","swaggerVersion":"1.2"}.

Could you please tell me what init param name you have used to set scan param to true?

**Comment by to-kra** [comment]
Hi,
Now I have declaration in web-fragment (web-fragment.xml), as we wanted to separate project from main, but in principle its same for web.xml

![selection_010](https://cloud.githubusercontent.com/assets/2188084/8232179/cf05c33e-15cd-11e5-9764-ada185ebe3ac.png)

If you need more info write me an email to: tomas.kramaric@tokra.sk
