### ISSUE TITLE
Script error for "esprima", needed by... swagger-ui-dist is not dependency free as it claims to be

### ISSUE THREAD

**Issue by mig8447** [swagger-api/swagger-ui#7110]
### Q&A (please complete the following information)
 - OS: [e.g. macOS] macOS
 - Browser: [e.g. chrome, safari] chrome
 - Version: [e.g. 22] 83
 - Method of installation: [e.g. npm, dist assets] npm
 - Swagger-UI version: [e.g. 3.10.0] 3.45.1
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] 3.0

### Content & configuration

I'm using requirejs in a project and besides the fact that in the npm package swagger-ui-dist claims to be dependency-free, it requires esprima as a dependency, which makes the package not to work out of the box

### Describe the bug you're encountering

Library, when imported via requirejs depends on esprima

### To reproduce...

1. Create a web page including requirejs
2. Configure require with the paths to swagger-ui-dist
3. Render the page
4. An error occurs trying to import esprima from the current path

### Expected behavior

Either change the documentation to indicate that the library requires esprima ro work or bundle esprima as part of the file

**Comment by mig8447** [comment]
Turns out that the dependency is not even used inside of the library but rather is included as part of the webpack packaging. Nevertheless the fact that when used in an AMD environment it is part of the dependencies makes the whole application crash when esprima is not imported. 

As a workaround for it to work the same as it does in a non CommonJS/AMD environment (In pure JS with the browser alone, where there's no esprima imported) you can define esprima **before** requiring swagger-ui as follows:

```js
require.config( {
    paths: { 'swagger-ui': './node_modules/swagger-ui-dist/swagger-ui-bundle' }
} );
/*
    IMPORTANT: Esprima is an optional dependency for Swagger-UI, therefore we define it to return
    undefined so that whenever the swagger-ui factory function kicks in the variable is undefined,
    causing the same behavior as importing the library in a plain browser environment. Remove this line
    if at some point you import esprima as a dependency and make sure that it is part of the paths and
    appropriately configured ro be "required"
*/
define( "esprima", [], () => undefined );
require( [ 'swagger-ui' ], SwaggerUIBundle => { /* ... */ } );
```

**Comment by char0n** [comment]
[SwaggerUI@3.52.0](https://github.com/swagger-api/swagger-ui/releases/tag/v3.52.0) no longer ships with esprima. You should no longer have issues with requirejs.
