### ISSUE TITLE
empty optional array with validation constraints is considered invalid

### ISSUE THREAD

**Issue by mathis-m** [swagger-api/swagger-ui#7111]
I know I'm late to the party, but I think this is relevant to this PR. I believe you can have a non-required string array param in the query, with `minItems: 1` to represent "either don't pass it at all, or if you do it must include at least 1 item". Well, I think so anyway..
I know you can have a non-required, non-nullable parameter meaning "either don't provide it, or provide a non-null value, but never provide `x: null`". So I believe you can additionally constrain the array with `minItems: 1` IIRC.

I am trying this in https://editor.swagger.io :
```yaml
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
paths:
 /test:
   get:
     parameters: 
       - name: names
         in: query
         required: false
         schema:
           type: array
           minItems: 1
           items:
             type: string
     responses:
       200:
         description: OK
```

I would like to be able to test omitting the `names` parameter by not providing any elements, but swagger-ui tells me I must provide at least 1 value.

Should these minItems validation checks include whether or not the param is required? Or am I way off here and the spec doesn't allow that?

_Originally posted by @dferretti in https://github.com/swagger-api/swagger-ui/issues/7003#issuecomment-805309633_

**Comment by mathis-m** [comment]
Actually I may be off on what I'm talking about anyways - I was initially reading this older PR https://github.com/swagger-api/swagger-ui/pull/6878, but poking through this PR I do see some null/required checking going on. Maybe editor.swagger.io is not running this code yet (is there an easy way to see what version it is running?).
Tomorrow I'll try just running swagger-ui locally on this version and see if it still is happening.

_Originally posted by @dferretti in https://github.com/swagger-api/swagger-ui/issues/7003#issuecomment-805316116_

**Comment by mathis-m** [comment]
@drewfreyling I had a look at how it is handled for type: string minLength:
https://editor.swagger.io/?url=https://gist.githubusercontent.com/mathis-m/416a5796511d27cc7a6160bc9f9866fa/raw/4c8968e09386b67318c29827831c84994cf86d03/WZOi9WH0TP.txt
```yaml
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
paths:
 /test:
   get:
     parameters: 
       - name: names
         in: query
         required: false
         schema:
           type: string
           minLength: 2
     responses:
       200:
         description: OK
```
It allows optional or minLength of 2 both is valid.

**Comment by tim-lai** [comment]
> is there an easy way to see what version it is running?

Yes, open the developer console, and type `window.versions`
