### ISSUE TITLE
Spec v1.2 Duplicate HTTP Methods

### ISSUE THREAD

**Issue by adrianbk** [swagger-api/swagger-ui#712]
Have you guys seen any instances of HTTP methods being repeated on the UI without the swagger JSON containing duplicates? See [here](https://github.com/martypitt/swagger-springmvc/issues/480). I have noticed occasional duplicate async requests for API declarations while debugging in chrome.

cc: @johnyUA

**Comment by rashmingadhavi** [comment]
We implement Restful API with Sub resources.
For example 
http://localhost/Resource1/subresource1
Another is 
http://localhost/Resource1/IntermediateResource1/subresource1

But the Resource1 and IntermediateResource1 do not have concrete implementations. So I can not apply @APIOperations and @ApiParam.

When I apply annotations at subresource1 - I get duplicate API paths. 

How to handle this?

**Comment by webron** [comment]
@rashmingadhavi - Please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) to ask the question with more details (including swagger-core version and so on).
