### ISSUE TITLE
partitioned table

### ISSUE THREAD

**Issue by bitlab-code** [swagger-api/swagger-ui#7120]
- OS: macOS
 - Browser: safari
 - Swagger-UI version: 3.45
 - Swagger/OpenAPI version: Swagger 2.0
 
--
with partitioned tables, swagger-ui show api for each partition, instead it should only show the api for the partitioned table

**Comment by bitlab-code** [comment]
hi @tim-lai, closed because fixed? won't fix? expected behavior? unable to reproduce?
Thanks

**Comment by tim-lai** [comment]
@bitlab-code Hello, if you would like to reopen this issue, please provide additional information describing the problem and how to reproduce, as well as any potentially helpful information as suggested by the issue template. Thanks.
