### ISSUE TITLE
Using multiple examples (both inline and $referenced) do not show up in the "Example Value" field

### ISSUE THREAD

**Issue by Tobias4872** [swagger-api/swagger-ui#7124]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Chrome
 - Version: 88.0.4324.182
 - Method of installation: Docker
 - Swagger-UI version: 3.18.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0

info:
  version: "0.0.1"
  title: Product Builder API

servers:
  - url: 'http://localhost:7001'

tags:
  - name: Products
    description: |
      Endpoints to manage products.
  - name: Monitoring
    description: |
      Endpoints to determine status, version and performance metrics. Partly restricted.

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string

  examples:
    ProductRequest:
      name: Test Product Request (Referenced)
    ProductResponse:
      name: Test Product Response (Referenced)

paths:
  /product:
    post:
      tags:
        - Products
      summary: Create a new product
      description: |
        This request will create a new product.
      responses:
        201:
          description: |
            The product was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                Inline:
                  name: Test Product Response (Inline)
                Referenced:
                  $ref: '#/components/examples/ProductResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            examples:
              Inline:
                name: Test Product Request (Inline)
              Referenced:
                $ref: '#/components/examples/ProductRequest'
```

Swagger-UI configuration options:

Run with the official swagger-ui/swagger-ui image.

```
http://localhost:7000/#/Products/post_product
```

### Describe the bug you're encountering

Both the inline as well as the referenced examples to do not show up properly. They should show up as
```
{
  "name": "string"
}
```
If I just use the singular example node, it shows up fine.

### Actual behavior

1. Run the official docker image
2. Go to 'http://localhost:7000/#/Products/post_product'
3. Select "Inline" from the examples dropdown for the **request**.
3. Find the example value field for the request. It only shows the definition, not the example.
4. Switch from "Inline" to "Referenced"
5. Same behaviour.
6. Select "Inline" from the examples dropdown for the **response**.
7. Find the example value field for the response. It only shows the definition, not the example.
8. Switch from "Inline" to "Referenced"
9. Same behaviour.

### Expected behavior

Expected behavior is that both the "Inline" as well as the "Referenced" example show up properly in both example value fields for the request as well as for the response.

### Screenshots
Inline
![Inline](https://user-images.githubusercontent.com/22483371/112766418-fab5e300-9011-11eb-9637-3d087130a986.png)

Referenced
![Referenced](https://user-images.githubusercontent.com/22483371/112766423-fe496a00-9011-11eb-8d45-00f91d7498f1.png)

**Comment by hkosova** [comment]
Replace
```yaml
  examples:
    ProductRequest:
      name: Test Product Request (Referenced)
    ProductResponse:
      name: Test Product Response (Referenced)
```
with:
```yaml
  examples:
    ProductRequest:
      value:  # <------
        name: Test Product Request (Referenced)
    ProductResponse:
      value:  # <------
        name: Test Product Response (Referenced)
```

Note the extra [`value`](user-content-examplevalue) key that wraps the actual example value.

Inline examples also need the `value` key:
```yaml
              examples:
                Inline:
                  value:  # <----
                    name: Test Product Response (Inline)
```
