### ISSUE TITLE
Swagger performance

### ISSUE THREAD

**Issue by Vox1984** [swagger-api/swagger-ui#7185]
### Q&A (please complete the following information)
 - OS: swagger node:10 docker image
 - Browser: Firefox
 - Version: 75.0 64 bit
 - Method of installation: npm
 - Swagger-UI version: 3.45.1
### Content & configuration
Swagger/OpenAPI definition:
```yaml
{
  "openapi": "3.0.0",
  "info": {
    "title": "webbackend",
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://mydomain:8080/api"
    }
  ],
  "paths": {
    "/path1": {
      "$ref": "main/endpoints/first.json"
    },
    "/path2": {
      "$ref": "main/endpoints/second.json"
    },
    "/path N": {
      "$ref": "main/endpoints/N-th.json"
    },
```

Swagger-UI configuration options:
```js
SwaggerUI({
url: "https://mydomain.com
dom_id: "#swagger-ui"
validatorUrl: null
})
```
### How can we help?
I am using swagger-ui for a while, and I was happy with it. With time though the size of the OpenApi definion (yaml) grew enough, so I decided to logically split it to smaller files.
I am loading this smaller files like in the example code posted above... I am unhappy with the fact that swagger-ui takes up to 20 seconds to load all of this smaller files.

My Question is - are this files being loaded by swagger-ui one-by-one?
GET first.json, then after receiving it GET second.json and so on?

Is there any way to load those json files in parallel?

**Comment by Vox1984** [comment]
I did some testing and swagger-ui takes up to 20 seconds to load all this files....

**Comment by tim-lai** [comment]
Hi @Vox1984 Yes, afaik, the files are loaded in order of occurrence as the definition gets parsed.

**Comment by Vox1984** [comment]
Well, in that case performance is poor, and perhaps should be improved in the future?
Something to consider.
