### ISSUE TITLE
"urls" parameter not working in 3.30

### ISSUE THREAD

**Issue by triforcely** [swagger-api/swagger-ui#7190]
### Q&A (please complete the following information)
 - OS: Doesn't matter
 - Browser: Chrome 
 - Version: Latest
 - Method of installation: NPM and CDN
 - Swagger-UI version: 3.30
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Full repro on codepen:
https://codepen.io/wilski-micha/pen/OJWEYZm

Swagger-UI configuration options:
```js
SwaggerUIBundle({
    urls: [
      {
        "name": "Test",
        "url": "https://petstore.swagger.io/v2/swagger.json"
      }
    ],
    dom_id: '#swagger'
 })
```

### Describe the bug you're encountering
After configuring swagger-ui as described in the documentation, I'm getting a message that "No API definition provided". When I use "URL" property, it works fine but I want to display more than one definition in the UI.

### To reproduce...
https://codepen.io/wilski-micha/pen/OJWEYZm

### Expected behavior
It should work.

**Comment by sameerthekhans** [comment]
Hey @triforcely How did you solved this, I am also facing this issue.

**Comment by triforcely** [comment]
Hey @sameerthekhans , I figured out that these settings work:

```js
import { SwaggerUIBundle, SwaggerUIStandalonePreset } from "swagger-ui-dist";
import "swagger-ui-dist/swagger-ui.css";

SwaggerUIBundle({
    urls: [
        {
            "name": "Test",
            "url": "https://petstore.swagger.io/v2/swagger.json"
        }
    ],
    dom_id: "#swagger",
    deepLinking: true,
    presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
    layout: "StandaloneLayout",
  });
  ```
  
  Not really sure what it fixes but it works for me :)

**Comment by sameerthekhans** [comment]
Thanks! I also fixed it by adding the below config, I think with the default layout it has some issue.

```js
...
presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
layout: "StandaloneLayout",
```

I also faced another issue `can't resolve module "path"` when used `swagger-ui-dist` instead of `swagger-ui` in webpack.

Fixed that by installing
```
npm i path
```

**Comment by lhapaipai** [comment]
With `swagger-ui` I used this:

```js
import SwaggerUI from "swagger-ui";
import "swagger-ui/dist/swagger-ui.css";
import SwaggerUIStandalonePreset from "swagger-ui/dist/swagger-ui-standalone-preset";

SwaggerUI({
  urls: [
    {
      "name": "Test",
      "url": "https://petstore.swagger.io/v2/swagger.json"
    }
  ],
  dom_id: "#root",
  deepLinking: true,
  presets: [SwaggerUI.presets.apis, SwaggerUIStandalonePreset],
  plugins: [SwaggerUI.plugins.DownloadUrl],
  layout: "StandaloneLayout",
});
```
