### ISSUE TITLE
Problem sending parameters via POST

### ISSUE THREAD

**Issue by marlandy** [swagger-api/swagger-ui#72]
Hi all, 

I´m experimenting with swagger and swagger-ui with my REST API (Jersey). I have an operation named "addUser" (POST) that receives two parameters "id" and "name". When I try to test this operation via swagger-ui-1.1.1 I set values in their inputs (id and name) but when I send it to the server there´s not parameters in the request. It seems they are not being sent to the server. I have another three operations in my API (GET, PUT and DELETE) and works fine. I hope you can help me.

Thanks and regards

**Comment by rrallo** [comment]
What would you recommend for uploading an image file as well as some additional metadata about the image (i.e. a caption) as a POST? Since only one @requestbody is allowed, do you recommend bundling  everything as JSON and encode the image in base64 or something like that?

**Comment by ponelat** [comment]
Just a thought (i'm no expert on multipart mime types), but what about POSTing the image, which returns it's id. Then POST the meta data referencing that id?
So this would mean two requests though...

**Comment by webron** [comment]
@rrallo - that's really a question for the framework that you use rather than the UI. In a multipart request, there's no problem sending multiple 'files', some of which are the metadata, and one (or more) would be the actual file. You'd need to check the documentation, in your case, I believe it's Spring-MVC.

**Comment by flik** [comment]
I have the same issue and here is my swagger.json

```
{
    "swagger": "2.0",
    "info": {
        "title": "Sample API",
        "version": "1.0.0"
    },
    "paths": {
        "/dogs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Returns a list of dogs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Dog"
                            }
                        }
                    }
                }
            }
        },
        "/dogs/?id={id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Dog ID",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns a single dog by its ID",
                        "schema": {
                            "$ref": "#/definitions/Dog"
                        }
                    },
                    "404": {
                        "description": "No dog with the given ID was found"
                    }
                }
            }
        },
        "/login/index.php": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "email",
                        "in": "path",
                        "description": "User Email",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "password",
                        "in": "path",
                        "description": "User Password",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns a single dog by its ID",
                        "schema": {
                            "$ref": "#/definitions/Login"
                        }
                    },
                    "404": {
                        "description": "No dog with the given ID was found"
                    }
                }
            }
        }
    },
    "definitions": {
        "Dog": {
            "required": [
                "id",
                "name",
                "age"
            ],
            "properties": {
                "id": {
                    "description": "The ID of the dog",
                    "type": "integer"
                },
                "name": {
                    "description": "The name of the dog",
                    "type": "string"
                },
                "age": {
                    "description": "The age of the dog",
                    "type": "integer"
                }
            }
        },
        "Login": {
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "User Password",
                    "type": "string"
                },
                "password": {
                    "description": "The password of the user",
                    "type": "string"
                }
            }
        }
    }
}
```

**Comment by rolandroos** [comment]
If you add this above your controller:

    @RestController
    @RequestMapping(value = "/api/users",
        produces = {"application/json"})
...
public class UserController {

 @PostMapping(value = "/test")
    @ApiOperation(value = "Create user role")
    public boolean Test(
            @ApiParam(value = "User role information", required = true)
            UserDTO user)
    {
        return true;
    }
}

it should work like a charm.
Tested with 
 <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
        </dependency>
 <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.9.2</version>
        </dependency>

**Comment by MohdTalib368** [comment]
Sir i Have a question: when in  Hit on Post method and pass mendatory value in property like i have two property  EmployeteName and EmplyeeJob and i also have numbers of property but these two are mendatory to pass so when i pass those two value in parameter then it will save in db and others property value save as null. pls solve my issue becouse i cant  able to save null values in my db and am using SQL Server and my emailid:talibit.ssgc@gmail.com
pls tell me as soon as possible

**Comment by MohdTalib368** [comment]
{
  "facilityId": 0,
  "facilityName": "string",
  "description": "string",
  "address1": "string",
  "address2": "string",
  "city": "string",
  "stateId": 0,
  "regionId": 0,
  "countryId": 0,
  "postalCode": "string",
  "phoneNumberId": 0,
  "emailAddress": "string",
  "additionalDetails": "string",
  "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
  "modifiedUserName": "string",
  "timeZone": "string",
  "country": {
    "countryId": 0,
    "countryName": "string",
    "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
    "modifiedUserName": "string",
    "locations": [
      {
        "locationId": 0,
        "parentLocationId": 0,
        "locationName": "string",
        "locationType": "string",
        "description": "string",
        "address1": "string",
        "address2": "string",
        "city": "string",
        "stateId": 0,
        "postalCode": "string",
        "countryId": 0,
        "emailAddress": "string",
        "additionalDetails": "string",
        "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
        "modifiedUserName": "string",
        "facilityId": 0,
        "phoneNumberId": 0,
        "m3LocationId": "string",
        "sequence": 0,
        "phoneNumber": {
          "phoneNumberId": 0,
          "countryCode": "string",
          "areaCode": "string",
          "number": "string",
          "extension": "string",
          "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
          "modifiedUserName": "string",
          "locations": [
            null
          ]
        }
      }
    ]
  },
  "region": {
    "regionId": 0,
    "regionName": "string",
    "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
    "modifiedUserName": "string",
    "facilities": [
      null
    ]
  },
  "state": {
    "stateId": 0,
    "stateName": "string",
    "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
    "modifiedUserName": "string",
    "locations": [
      {
        "locationId": 0,
        "parentLocationId": 0,
        "locationName": "string",
        "locationType": "string",
        "description": "string",
        "address1": "string",
        "address2": "string",
        "city": "string",
        "stateId": 0,
        "postalCode": "string",
        "countryId": 0,
        "emailAddress": "string",
        "additionalDetails": "string",
        "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
        "modifiedUserName": "string",
        "facilityId": 0,
        "phoneNumberId": 0,
        "m3LocationId": "string",
        "sequence": 0,
        "phoneNumber": {
          "phoneNumberId": 0,
          "countryCode": "string",
          "areaCode": "string",
          "number": "string",
          "extension": "string",
          "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
          "modifiedUserName": "string",
          "locations": [
            null
          ]
        }
      }
    ]
  },
  "locations": [
    {
      "locationId": 0,
      "parentLocationId": 0,
      "locationName": "string",
      "locationType": "string",
      "description": "string",
      "address1": "string",
      "address2": "string",
      "city": "string",
      "stateId": 0,
      "postalCode": "string",
      "countryId": 0,
      "emailAddress": "string",
      "additionalDetails": "string",
      "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
      "modifiedUserName": "string",
      "facilityId": 0,
      "phoneNumberId": 0,
      "m3LocationId": "string",
      "sequence": 0,
      "phoneNumber": {
        "phoneNumberId": 0,
        "countryCode": "string",
        "areaCode": "string",
        "number": "string",
        "extension": "string",
        "modifiedTimestamp": "2020-04-20T13:46:39.272Z",
        "modifiedUserName": "string",
        "locations": [
          null
        ]
      }
    }
  ]
}

this is my json data which are generate in swagger and in this i want pass the only two mandatory value i.e. facilityName and decription and others are save as null so how can i save null
