### ISSUE TITLE
Outdated React version on integrating Swagger UI with React App

### ISSUE THREAD

**Issue by neo7337** [swagger-api/swagger-ui#7215]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: Version 90.0.4430.85
 - Method of installation: dist asset
 - Swagger-UI version: 3.47.1
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration
I have Swagger UI and Swagger Editor integrated with my React App but on checking the React Developer Tools, It gives an alert that the page is using an outdated version of React.
I know that npm dependencies of swagger-editor and swagger-ui both have the react dependency of v15.7.0 which can lead to this alert.
But I did try using the swagger-ui-dist and swagger-editor-dist, but no luck the react tools still say the outdated react version warning.

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
import React from "react";
import SwaggerUIBundle from "swagger-ui-dist/swagger-ui-bundle"
import SwaggerUIStandalonePreset from "swagger-ui-dist/swagger-ui-standalone-preset"
import "swagger-ui-dist/swagger-ui.css"

export default function App() {

  React.useEffect(() => {
    const ui = SwaggerUIBundle({
      url: "https://petstore.swagger.io/v2/swagger.json",
      dom_id: '#swagger-ui',
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      layout: "StandaloneLayout"
    })

    window.ui = ui
  })

  return (
    <div>
      <div id="swagger-ui"></div>
    </div>
  );
}
```

```
?yourQueryStringConfig
```

### Screenshots
<img width="521" alt="image" src="https://user-images.githubusercontent.com/17389779/116239507-5ba31900-a780-11eb-9464-29905d689ca8.png">

### How can we help?
Is there a way to get rid of this outdated React version error on the app?

**Comment by hkosova** [comment]
Try using [`swagger-ui-react`](https://www.npmjs.com/package/swagger-ui-react) instead of `swagger-ui-dist`.

**Comment by neo7337** [comment]
@hkosova tried the `swagger-ui-react` as well. Same error!

**Comment by tim-lai** [comment]
Swagger UI 3.x is tied to React 15. This includes swagger-ui-react. There are known compatibility issues with React 16 and React 17. If you are using React 16/17, I recommend that you render the applications separately. Closing this issue in favor of #7341.
