### ISSUE TITLE
Support passing a service.json along in the swagger api url.

### ISSUE THREAD

**Issue by StuAtGit** [swagger-api/swagger-ui#725]
I generate my swagger json as part of my build process using the swagger-maven-plugin. This generates a services.json test file. However, the swagger ui seems to assume that the path given in the ui text box to the docs points to a dynamic web app that returns the contents in services.json. 

I think the main problem with giving that full path to services.json is that it assumes the path given is also the base path for the api documentation.

Initially,  worked around this by changing the name of services.json to index.html, but that's just a hack ;)

I've since taken to patching my code with (from my git changelist):

-------------------------------- lib/swagger.js --------------------------------
index 0c63a38..1177c93 100644
@@ -365,7 +365,12 @@
       if (this.path.substring(0, 4) === 'http') {
         this.url = this.path.replace('{format}', 'json');
       } else {
-        this.url = this.api.basePath + this.path.replace('{format}', 'json');
-        if( this.api.basePath.length > 4 && 
-            this.api.basePath.substring(this.api.basePath.length-4) === "json" ) {
-            var endBasePath = this.api.basePath.lastIndexOf( "/" );
-            this.api.basePath = this.api.basePath.substring(0,endBasePath);
-        }
-       this.url = this.api.basePath + this.path.replace('{format}', 'json');
     }
     this.api.progress('fetching resource ' + this.name + ': ' + this.url);
     var obj = {
  @@ -401,8 +406,10 @@

This basically lets the swagger-ui read in the service info from services.json, but then strips the "[whatever].json" off the end of the path before constructing the path to the API. Not sure if it's the right answer in general, but works for me! :)

**Comment by porjo** [comment]
Shouldn't the url parameter support url encoded values (it currently does not)?

**Comment by webron** [comment]
If you feel there's a problem, feel free opening an issue.
