### ISSUE TITLE
Add the option to let "Try It Out" button have been clicked by default

### ISSUE THREAD

**Issue by xuhdev** [swagger-api/swagger-ui#7252]
### Is your feature request related to a problem?
User has to click on "Try It Out" button first before they can actually try it out. But this is confusing and users are thinking the UI is not working. For example, we have received multiple complaints similar to https://github.com/IBM/MAX-Object-Detector/issues/169 : People are thinking the fields should be available by default without clicking "try it out" button, because they have clicked on the tab to expand it:

![](https://user-images.githubusercontent.com/1094878/117401989-90774480-aed3-11eb-97fa-5c76af21f58d.png)

### Describe the solution you'd like
Add an option to set "try it out" button being clicked by default. After a user expands a tab, all fields should become available.

**Comment by hkosova** [comment]
Set the [`tryItOutEnabled`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-tryitoutenabled) option to `true` in your Swagger UI configuration code. This option was added in v. 3.41.0.

Demo: https://petstore.swagger.io/?tryItOutEnabled=true

**Comment by xuhdev** [comment]
This is strange. I tried that option but it wasn't working. Will figure out what's going on.
