### ISSUE TITLE
Is there a reason to use port 8080 for the docker image?

### ISSUE THREAD

**Issue by x-yuri** [swagger-api/swagger-ui#7262]
### Is your feature request related to a problem?
It took me some time to figure out how to run Swagger UI under Docker together with [`nginx-proxy`][a]. The latter decides which port container is using by inspecting the exposed ports. Right now `nginx` image exposes port 80, `swagger-ui` port 8080. In that case `nginx-proxy` chooses port 80 and fails to connect to `swagger-ui`.

[a]: https://hub.docker.com/r/jwilder/nginx-proxy

### Describe the solution you'd like
Change the port when running under Docker to port 80. That way documentation will also become a little bit more straightforward.

https://github.com/swagger-api/swagger-ui/blob/v3.48.0/Dockerfile#L13
https://github.com/swagger-api/swagger-ui/blob/v3.48.0/Dockerfile#L30
https://github.com/swagger-api/swagger-ui/blob/v3.48.0/docs/usage/installation.md#docker

### Describe alternatives you've considered
The workaround is to add the `VIRTUAL_PORT` environment variable (`VIRTUAL_PORT=8080`) to the container.

**Comment by tim-lai** [comment]
Hi, thanks for asking the question.  Although Docker defaults to port 8080, container networking with Docker is entirely configurable. I'd expect configuration setup depending on one's use of server and proxy.

https://docs.docker.com/config/containers/container-networking/

**Comment by x-yuri** [comment]
@tim-lai You're missing the point, indeed one can map ports however one likes, but `nginx-proxy` makes decisions based on exposed ports, not published.

Let me put it this way. `nginx` image you're basing on exposes [port 80][a]. You make `nginx` listen to port 8080, expose [port 8080][b]. But that doesn't override the previous [EXPOSE][c] instruction. The `swagger-ui` image exposes ports 80 and 8080. Which is not true. And that has practical consequences (`nginx-proxy` and potentially more). Is there a reason to expose 8080, not to stick with port 80?

[a]: https://github.com/nginxinc/docker-nginx/blob/f3fe494531f9b157d9c09ba509e412dace54cd4f/mainline/debian/Dockerfile#L112
[b]: https://github.com/swagger-api/swagger-ui/blob/v3.50.0/Dockerfile#L30
[c]: https://docs.docker.com/engine/reference/builder/#expose

**Comment by tim-lai** [comment]
@x-yuri port 8080 is a commonly used alternative http port (and not https). For a many users, port 80 is already "claimed" by another web application, or even blocked in some cases for security reasons. SwaggerUI provides a working sample configuration for docker, but is agnostic to which ports are actually implemented by the user.
