### ISSUE TITLE
Show required OAuth scopes on each endpoint in swagger for .net core 

### ISSUE THREAD

**Issue by priyankasingh0692** [swagger-api/swagger-ui#7267]
The API I am documenting has a lot of scopes available. However, a single endpoint usually only requires one scope. Currently I am able to show all scopes the API has.

It would be great to know which individual scopes are required per endpoint.

 [Authorize(Roles = "read_account, gread_account")]
[Get]api/values

 [Authorize(Roles = "write_account, gwrite_account")]
[Post]api/values

**Comment by hkosova** [comment]
Duplicate of #5062.
