### ISSUE TITLE
JSON example no longer generated for object form-data properties

### ISSUE THREAD

**Issue by bfreuden** [swagger-api/swagger-ui#7268]
### Q&A 
 - OS: Ubuntu 18.04 
 - Browser: Firefox
 - Version: 88.0
 - Method of installation: snap
 - Swagger-UI version: 3.48.0
 - Swagger/OpenAPI version:OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
---
openapi: 3.0.2
info:
  title: Conversion API doc
  description: Conversion API documentation
  version: '1.0'
tags:
- name: converters
  description: Converters
paths:
  "/convert/tutu":
    post:
      summary: ''
      tags:
      - converters
      operationId: tutuconvert
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                parameters:
                  "$ref": "#/components/schemas/TutuConverterTutuParameters"
      responses:
        '200':
          description: List of converted documents
          application/json:
            schema:
              type: array
              items:
                "$ref": "#/components/schemas/Document"
        '500':
          description: Error
      description: ''
components:
  schemas:
    Document:
      required:
      - text
      type: object
      properties:
        text:
          type: string
    TutuConverterTutuParameters:
      type: object
      properties:
        stuff:
          type: string

```

Swagger-UI configuration options:

Nothing special here, I'm using the "dist package" as is.

### Describe the bug you're encountering

The JSON example of object form-data properties is no longer generated.

### To reproduce...

1. Click on the /convert/tutu endpoint
2. Click on the "try it out" button
3. The parameters field has no generated JSON example

Screenshot:
![swagger-ui-ko](https://user-images.githubusercontent.com/5137152/118287469-c455f980-b4d3-11eb-8d8d-671bba6f80a4.png)

### Expected behavior

In swagger-ui 3.41.0 we used to have a json example for object properties of form-data bodies:
![swagger-ui-ok](https://user-images.githubusercontent.com/5137152/118287372-aee0cf80-b4d3-11eb-9491-8f894e05b9f8.png)

### Additional context or thoughts

It might be something incorrect in my spec though: maybe swagger-ui 3.42.0 is expecting something 3.41.0 was not expecting.
If it is the case I apologize for the bug report and I would be grateful for any hint that might help me correcting my spec.

If not I have narrowed the regression down to the following commit:
```
commit 8ed6c34958ddb333473f953969e69a23d0a419b3
Author: <hidden>
Date:   Wed Feb 3 21:04:12 2021 +0100

    feat: sample-gen mulit and form media-type (#6874)
    
    * application/x-www-form-urlencoded || **multipart/** initial value should rely on sample gen
```
So it seems to be related to this pull request:
https://github.com/swagger-api/swagger-ui/pull/6874

Here is what I did to support my claim:
```bash
# checkout source code before the commit (somewhere between  3.41.0 and  3.42.0)
git checkout 23323bbbff2235c8b3ccd7d60a345dcb8c31706b
# build
npm install
npm run build
# use the swagger-ui/dist to perform the OK screenshot above
# clean 
git checkout -f ; git clean -fd
git checkout master
# checkout source code at the immediate following commit 
git checkout 8ed6c34958ddb333473f953969e69a23d0a419b3
# build
npm run build
# use the swagger-ui/dist to perform the KO screenshot above
```

**Comment by tim-lai** [comment]
@bfreuden Here is a fixed definition excerpt that works for me in https://editor.swagger.io. 
```yaml
      responses:
        '200':
          description: List of converted documents
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
```

**Comment by bfreuden** [comment]
@tim-lai No problem! Thank you for having taken a look at the issue ^^

**Comment by bfreuden** [comment]
@tim-lai Thank you for fixing the issue! I've just tested the latest master branch and it works very well :)
