### ISSUE TITLE
Make Responses section collapsible inside Operations

### ISSUE THREAD

**Issue by kowalskidev** [swagger-api/swagger-ui#7274]
### Content & configuration

### Is your feature request related to a problem?
I'm always frustrated when I expand Operations as I have long list of Responses (400, 401...etc.) for each operation and I don't want to look at responses every time, just need to try out so it becomes difficult to scroll between the operations. Refer Screenshot below

### Describe the solution you'd like
It would be great if we have the Responses section collapsible just like Models and Operation, So it would be easy to navigate between operations as each operation would take less space. 

### Describe alternatives you've considered
I tried looking into documentation for options and I found options `defaultModelsExpandDepth`, `defaultModelExpandDepth` but these options are for Models section, I wanted the same for Responses Section as well.

### Additional context
I'm adding the screenshot for reference.
![image](https://user-images.githubusercontent.com/15380913/118484315-b5ba4d00-b734-11eb-8bba-00515f73c9c2.png)

**Comment by ShivamJoker** [comment]
I also need this feature.

**Comment by deep-sangani** [comment]
I also want this feature.

**Comment by hkosova** [comment]
Thanks for the feedback. This has been suggested before in #6630 so I'll close this one as a duplicate. Please follow #6630 for updates.
