### ISSUE TITLE
Deprecated not working with 1.2 spec

### ISSUE THREAD

**Issue by timroes** [swagger-api/swagger-ui#728]
In the 1.2 spec the deprecated field was of type `string` with either "true" or "false" as a value.

Though the README states, that current version of Swagger-UI should work with the 1.2 spec, it doesn't correctly in that case. The comparison if the deprecated warning should be shown assumes, that the deprecated field contains a boolean value. In case of the 1.2 spec the field is always shown, since the not empty string is truthy.

**Comment by posto** [comment]
+1

**Comment by qq291462491** [comment]
+1

**Comment by ollin** [comment]
+1

**Comment by boeboe** [comment]
+1

**Comment by cpacz** [comment]
+1

**Comment by fehguy** [comment]
this has been fixed in the develop_2.0 branch

**Comment by ndhar-1** [comment]
I am getting the issue of Warning: Deprecated on all my APIs. I am using swagger 2.0 spec and not using Spring-mvc. So i believe this issue is fixed in the most current release of Swagger UI - v2.1.1?

**Comment by webron** [comment]
The current release is 2.1.0. Try it out.
