### ISSUE TITLE
Endpoint text wrapping after v3.49.0

### ISSUE THREAD

**Issue by OskarLiew** [swagger-api/swagger-ui#7290]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: 90.0.4430.212
 - Method of installation: FastAPI
 - Swagger-UI version: v3.49.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Using configuration provided by FastAPI: [https://github.com/tiangolo/fastapi/blob/master/fastapi/openapi/docs.py](https://github.com/tiangolo/fastapi/blob/master/fastapi/openapi/docs.py)

I am pretty sure that the problem is not coming from FastAPI, but instead from the stylesheet used having changed after v3.49.0

### Describe the bug you're encountering
Textboxes for the endpoints seem to be too small, causing the text to wrap and be written vertically.

### To reproduce...

Create an API with FastAPI in Python: [https://fastapi.tiangolo.com/tutorial/first-steps/](https://fastapi.tiangolo.com/tutorial/first-steps/)

### Expected behavior
I expect the endpoints to be written horizontally and not vertically

### Screenshots
![swagger](https://user-images.githubusercontent.com/43787643/118957070-7e2fe880-b960-11eb-8601-60682ae3b0a9.png)
![swagger](https://user-images.githubusercontent.com/43787643/118957011-68babe80-b960-11eb-996d-f4b651b173f0.png)

### Additional context or thoughts
It worked as expected yesterday. I saw that you had a new release 12h ago. It seemed to contain changes to to the CSS

CSS stylesheet downloaded from: [https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui.css](https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui.css)

**Comment by calag4n** [comment]
Same here, I was a little surprised about that new style this morning ^^'

**Comment by xordoquy** [comment]
Q&A (please complete the following information)

- OS: OSX
- Browser: Chrome, Firefox, safari
- Version: 90.0.4430.212, 88.0.1, 14.1 (16611.1.21.161.6) (same order as browser)
- Method of installation: Flask (https:/:cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js)
- Swagger-UI version: N/A
- Swagger/OpenAPI version: OpenAPI 3.0

**Comment by chris-allnutt** [comment]
This was initially broken for us this morning but on hard refresh it's working for us; so this may have been resolved by a CDN push?
- OS: OSX
- Browser: Chrome
- Version: 90.0.4430.212
- Method of Install: Poetry via FastAPI
- Fast API Version: 0.61.2

**Comment by csangonzo** [comment]
> This was initially broken for us this morning but on hard refresh it's working for us; so this may have been resolved by a CDN push?
> 
> * OS: OSX
> * Browser: Chrome
> * Version: 90.0.4430.212
> * Method of Install: Poetry via FastAPI
> * Fast API Version: 0.61.2

Same here on Ubuntu 21.04.

**Comment by olledalow** [comment]
same 

> This was initially broken for us this morning but on hard refresh it's working for us; so this may have been resolved by a CDN push?
> 
> * OS: OSX
> * Browser: Chrome
> * Version: 90.0.4430.212
> * Method of Install: Poetry via FastAPI
> * Fast API Version: 0.61.2

**Comment by tim-lai** [comment]
Per comments above, looks like it might have been a CDN issue. It looks fine on https://petstore.swagger.io and https://editor.swagger.io. I also tested with a much longer operation path, and everything appears normal and responsive.

**Comment by kpflugshaupt** [comment]
Not working in Switzerland as of now. Will check again tomorrow, but glad to know it's nothing on our end.

**Comment by avico78** [comment]
Same here , 
Actually tried to downgrade fastapi to lower version and issue remain till version 0.61.0 .

**Comment by ArcLightSlavik** [comment]
@avico78 Downgrading fastapi won't really work. The latest version does not have locking for a specific version of the dist. There *are* some versions that do have locking but they are quite old.
To fix it on FastAPI side u have to do https://github.com/tiangolo/fastapi/issues/3255#issuecomment-844658537

**Comment by avico78** [comment]
@ArcLightSlavik - 
Actually downgrade to 0.61.0  did help but prefer your "Monkey" patch which actually saved me - thanks much!
Do know when it will be fixed ?I understand from some reason it doesn't impact all user (regional )?

**Comment by ArcLightSlavik** [comment]
@avico78 Yeah there seems to be some CDN caching issue, which might the reason your downgrade worked, probably downloaded from some other server. 
About the fix, I'm not sure. Tiangolo wants to replicate it locally but wasn't able to do it so far. There's proposition to indefinitely lock the library and upgrade it via releases (aka 0.70 fastapi brigns 5.0 of swagger-ui) but that might take a while to come. For now I would keep the monkeypatch and upgrade the version when you see fit.

**Comment by mrtanatorn44** [comment]
Quick Fix : inspect `.swagger-ui` styles uncheck `display : flex`

**Comment by elementum** [comment]
Same problem again
