### ISSUE TITLE
Tag specified in @ApiOperation not overriding tag specified in @Api swagger ui

### ISSUE THREAD

**Issue by sarahpsequeira** [swagger-api/swagger-ui#7297]
I have specified a tag at the class level as "Users" and have an API specified under this class with tag as "User Details". However on swagger ui I can see this api appearing under both the tags. How is it possible to show this API on swagger under "User Details" tag only and not under "Users" tag

@Api(tags = {"Users"}, description = "Manage Users")
@RestController
@RequestMapping("/api/users")
public class UserController {

    @Autowired
    UserService userService;

    @Autowired
    UserRepository userRepository;

    @Autowired
    AuditLogService auditLogService;

    Logger logger = LoggerFactory.getLogger(UserController.class);

    @ApiOperation(tags = {"User Details"})
    @GetMapping("/lastName/{lastName}")
    public List<UserGetResponse> findByLastName(@PathVariable String lastName) throws InterruptedException {
        logger.info("Received request to get users by last name, time: {}", LocalDateTime.now());
        List<UserGetResponse> userGetResponses = userService.getUsersByLastName(lastName);
        logger.info("Received response, Going to publish message to MQ, time: {}", LocalDateTime.now());
        auditLogService.publishMessage();
        return userGetResponses;
    }

**Comment by neiser** [comment]
@sarahpsequeira I think you've raised this issue in the wrong project. I suppose you're using a library such as springfox or springdoc to generate a specification. Those libraries do have limitations on how tags are handled. So maybe that's the right place to handle your issue?

This repo here though is only concerned with the UI, and thus a generated spec (YAML or JSON) which shows the issue within the UI is helpful if you're still sure it's not a problem of generating the spec.

**Comment by hkosova** [comment]
@sarahpsequeira - as @neiser said, that's a question for the library that generates your API definition. Please ask it in the library's repository.

* Springfox: https://github.com/springfox/springfox/issues
* Springdoc: https://github.com/springdoc/springdoc-openapi/issues
* Swagger Core: https://github.com/swagger-api/swagger-core/issues

**Comment by neiser** [comment]
@sarahpsequeira Shameless plug: If you're into checking out another library, see this one: https://github.com/qaware/openapi-generator-for-spring It does have some flexible tag handling :)
