### ISSUE TITLE
hide validator for 2.0 specs running on localhost

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#731]
Without using an HTTP post, it is impossible to run the validator against services on localhost, unless you are running the online validator locally.

If the validatorUrl is overridden, should show the validator regardless.  This allows running the api and validator locally.

If the validatorUrl is not overridden and the service is on localhost, the validator should be hidden

**Comment by DavidDeSloovere** [comment]
I'm also running swagger on "localhost", except I use *.localtest.me (see http://readme.localtest.me/)

Might I suggest not showing the validator result as an error if the validator can't access the docs?

**Comment by webron** [comment]
I don't think hiding it is wise but rather displaying an icon that it is unavailable or unreachable. If the service is down and the docs are not hosted on localhost, it could be unclear if just hidden.

**Comment by DavidDeSloovere** [comment]
That's even better!





        Sent by Outlook for Android




On Thu, Jan 29, 2015 at 5:45 AM -0800, "Ron" <notifications@github.com> wrote:
I don't think hiding it is wise but rather displaying an icon that it is unavailable or unreachable. If the service is down and the docs are not hosted on localhost, it could be unclear if just hidden.

---
