### ISSUE TITLE
Tags' font is weirdly positioned

### ISSUE THREAD

**Issue by zoispag** [swagger-api/swagger-ui#7311]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 90
 - Method of installation: npm
 - Swagger-UI version: 3.49.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering

Since the last update, the titles of the tags are not bold anymore.

### To reproduce...

1. Go to swagger
2. See tags

### Expected behavior
They should look bold as before

### Screenshots
See comparison between new and old:

![119485496-6fc64000-bd57-11eb-9189-02f22312c09f](https://user-images.githubusercontent.com/21138205/119485681-a603bf80-bd57-11eb-9a83-6023ef387994.png)

**Comment by tim-lai** [comment]
@zoispag I am unable to reproduce this on https://petstore3.swagger.io/ or https://editor.swagger.io. The tags look bold as expected.
