### ISSUE TITLE
Schema type in paths.parameters is changed from array to string after building and deploying from yaml files

### ISSUE THREAD

**Issue by wangzining** [swagger-api/swagger-ui#7321]
### Q&A 
- OS: macOS
 - Browser: chrome
 - Version: chrome version 90.0.4430.93
 - Method of installation: npm
 - Swagger-UI version: 3.26.2
 - Swagger/OpenAPI version: Swagger 3.0, OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  title: Sample app
  version: 1.0.0
servers:
  - url: 'xxx'
    description: Inferred Url
tags:
  - name: testName
    description: xx
paths:
  /api/testapp:
    get:
      tags:
        - testapp
      summary: xxx
      description: xxx
      operationId: getAppList
      parameters:
        - name: filter
          in: query
          description: How many items to return at one time
          required: false
          style: form
          explode: true
          schema: 
            type: array
            items:
              type: string
        - $ref: '#/components/parameters/filtering'


      responses:
        '403':
          description: Forbidden
        '404':
          description: Not Found
          
components:
  parameters:
    pageSize:
      name: size
      in: query
      description: Number of objects returned per page
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        exclusiveMinimum: true
        maximum: 100
        exclusiveMaximum: false
        multipleOf: 10
        default: 20
    pageNumber:
      name: page
      in: query
      description: Page number
      required: false
      schema:
        type: integer
        default: 1
        minimum: 1
    sortType:
      name: sort
      in: query
      description: sort type - asc or desc
      required: false
      schema:
        type: string
        enum:
          - asc
          - desc
        default: asc
    sortBy:
      name: sortBy
      in: query
      description: sort column by which objects needs to be sorted
      required: false
      schema:
        type: string
    filtering:
      name: filter
      in: query
      required: false
      description: How many items to return at one time by wzn
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false

```

### Describe the bug you're encountering
As shown in above yaml, filtering schema should be array of string. However after compiling local maven project and deploy the jar file on server, the swagger UI page is showing schema type as string, which causing "Add item" tab missing. Same yaml file works for OpenAPI 2.0 version. 

### To reproduce...

1. Edit yaml file and set schema type as array
2. Compile module and deploy the jar file 
3. See the swagger UI page - corresponding path
4. See the issue that this parameter type is string

### Expected behavior
Should show the schema as type array

### Screenshots
3.0
![Screen Shot 2021-05-27 at 10 46 55 AM](https://user-images.githubusercontent.com/16752480/119872988-e8083f00-bed8-11eb-9e05-495f4377a696.png)
2.0 (which works as expected before upgrading to 3.0, see the type here is array, and the button part there's an Add item tab)
![Screen Shot 2021-05-27 at 10 48 18 AM](https://user-images.githubusercontent.com/16752480/119873161-138b2980-bed9-11eb-9908-6006483991c1.png)

### Additional context or thoughts
I tried online swagger editor with this yaml example, looks fine with converting. But if deploying on server the schema type went wrong. In addition, in the java file generated locally, this parameter is showing as "List<String>" instead of "string", but after deploying the swagger UI link is showing string only.
![Screen Shot 2021-05-27 at 10 51 44 AM](https://user-images.githubusercontent.com/16752480/119873593-8c8a8100-bed9-11eb-8a26-b41f0d4fb533.png)

**Comment by tim-lai** [comment]
@wangzining Thanks for investigating details for this ticket. As you noted, this looks like an issue with Maven/Java, and not with `swagger-ui` itself.
