### ISSUE TITLE
Are there any tutorials on how to use it without a framework?

### ISSUE THREAD

**Issue by cata0309** [swagger-api/swagger-ui#7331]
Hello! I am trying to use swagger-ui in a website that I made for a university project. The requirement is that I cannot use any frameworks like express, fastify, koa, etc.
I made my own router using the `http` module. Is there any way I can integrate swagger-ui without installing a framework? The web is full of swagger+express tutorials.
I read that swagger is framework independent.
Thank you!

**Comment by ponelat** [comment]
Hey @cata0309 you can serve the static js/html/css files that will run swagger-ui in the browser without express or other frameworks. Take a look at https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#plain-old-htmlcssjs-standalone

**Comment by cata0309** [comment]
You are right! I managed to serve them without problems. Thank you!
