### ISSUE TITLE
Is it possible to add a TAB like the bottom that generates a TypeScript interface?

### ISSUE THREAD

**Issue by ahnuchen** [swagger-api/swagger-ui#7343]
Example Value | Model | **ts interface**

interface CliConfig {
  api: string;

  /** directory */
  outputDir: string;

  /** Service template file path */
  templateDir?: string;

  /** type default ts */
  type?: 'ts' | 'js' = 'ts';

  /** defination file namespace */
  namespace?: string = 'API';

  /**ingnore files  */
  ignoreDelete: string[] = [];

  /** hooks of data opeartion */
  hook?: {
    /** custom function name */
    customFunctionName?: (data: OperationObject) => string;
    /** custom file name */
    customfileName?: (tagName: string) => string;
  } = {};
}

I can copy this content and use it directly in my typescript code

**Comment by tim-lai** [comment]
@ahnuchen Thanks for reaching out. A custom plugin should work for this functionality. Here's some info on the SwaggerUI plugin system: https://github.com/swagger-api/swagger-ui/blob/master/docs/customization/plugin-api.md
