### ISSUE TITLE
Servers section is not rendered

### ISSUE THREAD

**Issue by rols2015** [swagger-api/swagger-ui#7345]
![image](https://user-images.githubusercontent.com/16349586/121967359-35403980-cd3e-11eb-800a-dcbef9f1274b.png)

**Comment by rols2015** [comment]
![image](https://user-images.githubusercontent.com/16349586/121967952-56555a00-cd3f-11eb-8b74-6fc1930495ee.png)

**Comment by hkosova** [comment]
@rols2015 please create a new issue and fill in the details in the issue template. Without that information we can't help you.
