### ISSUE TITLE
swagger editor

### ISSUE THREAD

**Issue by AlexJMcloud** [swagger-api/swagger-ui#7346]
Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.

Until now, your editor cannot correctly identify the error codes.
The headers are all spelled out.

Access-Control-Allow-Headers: *
Access-Control-Allow-Origin: *

swagger.yaml:

schemes:
  - https
basePath: /api

**Comment by AlexJMcloud** [comment]
From another site I am making a request via curl. And I get the server responses that should be.
When will your editor be able to read headlines normally?

**Comment by hkosova** [comment]
What's the full error message on the Console tab in the browser dev tools?

**Comment by mathis-m** [comment]
> From another site I am making a request via curl. And I get the server responses that should be.
> When will your editor be able to read headlines normally?

Network errors can not be read by Javascript this is a Browser security feature. See _Originally posted by @mathis-m in https://github.com/swagger-api/swagger-ui/pull/6938#issuecomment-780254982_

Second thing is that CORS is something that the client decides to enforce or not, browsers do other tools like postman or curl don't.

**Comment by char0n** [comment]
Hi @AlexJMcloud,

In order to help you, we'd need more information.

- When you mentioned Editor did you mean https://editor.swagger.io/?
- Are you using swagger-editor npm package and integrating in your application?
- What is the OAS definition source (if you can disclose it)?

**Comment by AlexJMcloud** [comment]
Thanks. But I already solved this issue back in July.

**Comment by muhammadrivaldy** [comment]
@AlexJMcloud how to fix that?

**Comment by o-medizadeh-Ard** [comment]
hi

 how to fix that?

**Comment by AlexJMcloud** [comment]
Re: [swagger-api/swagger-ui] swagger editor (#7346)



Hello, omid.

Send 12 мая 2022 г., 0:44:10:





hi
how to fix that?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>



Yes.

--
 Alex                         ***@***.***

**Comment by gustavo-mungarro** [comment]
In my case I was using `springdoc-openapi-ui`, and I was trying to use the swagger-ui while running the application in the cloud, followed this doc and it fixed it:
https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy

**Comment by tobiolusa** [comment]
I am currently facing similar issue, How can I resolve it.

**Comment by o-medizadeh-Ard** [comment]
> I am currently facing similar issue, How can I resolve it.

hi.
plese use this :
`app.UseCors(x => x.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());`
in startup file Configure method.
and use `app.UseSwaggerAndUI();` after the `app.UseRouting();` and `app.UseEndpoints();` in this method.
i resolve it with this way.

**Comment by Artur470** [comment]
я у меня такая проблема с cors на удаленном сервере   ошибка с cors  а локальном все правильно работает   django rest framework

**Comment by Artur470** [comment]
помогите мне пожайлуста как можно решить это

**Comment by o-medizadeh-Ard** [comment]
> помогите мне пожайлуста как можно решить это

Hi Artur470.
I write .NET code and Django did not work.
But, you can get help from the following links:

https://www.youtube.com/watch?v=OIbndrrUYiY
https://forum.djangoproject.com/t/django-and-cors/19176/7
https://medium.com/django-unleashed/handling-cors-in-django-rest-framework-a-comprehensive-guide-ec11b0bc6807
https://stackoverflow.com/questions/35760943/how-can-i-enable-cors-on-django-rest-framework
https://osirusdjodji.medium.com/cross-origin-resource-sharing-in-django-rest-api-feec58e1253a
...

**Comment by Mukhsin0508** [comment]
---

✅ **Resolved:** In our case, the issue was due to **Swagger UI being served over HTTPS** (via Ngrok), but the Swagger-generated API requests were targeting **HTTP endpoints**, which modern browsers block due to **mixed content**.

### 🛠 Solution:

- We explicitly set the `url=` argument in `get_schema_view(...)` to match the correct `https://` endpoint:

```python
schema_view = get_schema_view(
    openapi.Info(
        title="Catering API",
        default_version="v1",
        description="API documentation for Catering Project 🚀",
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
    url="https://your-ngrok-subdomain.ngrok-free.app",  # ✅ Force HTTPS
)
```

- We also made sure `SWAGGER_DOCS_BASE_URL` in `.env` was correct and used it dynamically in production.

- Bonus: we added this to `settings.py` to ensure HTTPS works behind Ngrok and similar proxies:

```python
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
```

Now everything works smoothly — no more **“Failed to fetch / Mixed Content”** nonsense from Swagger 🎉

Hope this helps someone else stuck on the same boat!

---

Want me to submit that on your behalf too? Or you can post it and drop the link here for future reference.
