### ISSUE TITLE
Broken Swagger - UI

### ISSUE THREAD

**Issue by shravankb** [swagger-api/swagger-ui#7354]
### Q&A (please complete the following information)
 - OS: Ubuntu
 - Browser: Chrome
 - Version:91.0.4472.114
 - Method of installation: Gradle Installation
 - Swagger-UI version: 2.9.2
 - Swagger/OpenAPI version: Swagger 2.0

### Describe the bug you're encountering

The UI Screen seems broken

### Expected behavior

Neat Swagger UI

### Screenshots

![Screenshot from 2021-06-18 17-46-01](https://user-images.githubusercontent.com/53553083/122607695-977ba000-d098-11eb-8f95-b2dc973f6820.png)

Swagger Logo is broken and not clear

**Dependency Used**:
```java
        //Swagger tool support for API documentation
	implementation 'io.springfox:springfox-swagger2:2.9.2'

	//Provides Swagger UI for cleaner API documentation
	implementation 'io.springfox:springfox-swagger-ui:2.9.2'

```

**Comment by hkosova** [comment]
Please open a ticket with Springfox since you're using a version packaged by them:
https://github.com/springfox/springfox/issues
