### ISSUE TITLE
Generate example schema for default values of Array

### ISSUE THREAD

**Issue by marlenekoh** [swagger-api/swagger-ui#7360]
### Screenshots
![image](https://user-images.githubusercontent.com/28558150/122861681-6c23da00-d352-11eb-96be-e5c4b69730dc.png)
![image](https://user-images.githubusercontent.com/28558150/122861746-865db800-d352-11eb-97de-8b401b3365b3.png)

### How can we help?

Hi, I observed that the tags example schema will be generated if a default value is not set.
However, if the default value is set to `[]`, the schema representation is lost in the example.

Is it possible to generate the schema
```
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
```
even if the default is set for arrays?

It is a common use case for arrays to be initialised as `[]`.

**Comment by hkosova** [comment]
Add an `example` value, it takes precedence over `default` when generating examples.
```yaml
      tags:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/Tag"
        default: []
        example:       # <-------
          - id: 0
            name: string
```
