### ISSUE TITLE
Swagger UI - POST object in RequestBody doesn't render FileUpload button in Safari

### ISSUE THREAD

**Issue by jji2019** [swagger-api/swagger-ui#7365]
### Q&A
 - OS: macOS
 - Browser: Safari browser  (Firefox and Chrome do not have the same problem)
 - Version: Safari Version 14.1.1 (16611.2.7.1.4)
 - Method of installation: download the whole source zip from https://github.com/swagger-api/swagger-ui.git
 - Swagger-UI version: 3.50.0
 - Swagger/OpenAPI version: OpenAPI 3.0.3

### Configurations
OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  title: test
  version: ""
servers:
- url: /test
tags:
- name: test
  description: all operations
paths:
  /student:
    post:
      tags:
      - test
      summary: Upload a student profile file
      description: upload a student profile file
      operationId: postFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
```
Swagger-UI configuration options:

Files distribution:
```
./index.html
./dist/swagger-ui-bundle.js
./dist/swagger-ui-bundle.js.map
./dist/swagger-ui.css
./dist/swagger-ui.css.map
./dist/test.yml
```
Index.html include below script:
```
<script src="./dist/swagger-ui.js" charset="UTF-8"></script>
<script src="./dist/swagger-ui-bundle.js" charset="UTF-8"></script>
<script>
  window.onload = function() {
    // Build a system
    const ui = SwaggerUIBundle({
    // core
    url : "./dist/test.yml",
    dom_id : '#swagger-ui',
    ...
    })
  window.ui = ui
  }
</script>
```

### Describe the bug you're encountering
The above configuration can render the file upload button in Filefox and Chrome browsers as the `type: object` is setting in the `RequestBody`, but the configuration cannot render the file upload button in Safari browser.

### Screenshots
This is the snapshot from Chrome Version 91.0.4472.114 (Official Build) (x86_64):
<img width="777" alt="Screen Shot 2021-06-23 at 10 15 31 AM" src="https://user-images.githubusercontent.com/49252772/123140271-f2502700-d40b-11eb-8ab1-726f8f8db6bf.png">

This is the snapshot from Safari Version 14.1.1 (16611.2.7.1.4):
<img width="893" alt="Screen Shot 2021-06-23 at 10 17 10 AM" src="https://user-images.githubusercontent.com/49252772/123140470-2deaf100-d40c-11eb-9284-b52bba8309b6.png">

**Comment by tim-lai** [comment]
@jji2019 Hi, thanks for the report. Please try using the newest version of SwaggerUI, [v3.51.0](https://github.com/swagger-api/swagger-ui/releases/tag/v3.51.0). This version should resolve the issue, at least for me it does. Thanks!

**Comment by jji2019** [comment]
@tim-lai 👍 Thanks for proving the information. After upgrading to the v3.51.0, the file upload button could be rendered correctly.

**Comment by jji2019** [comment]
@tim-lai 
There is a minor question:
Currently sample-gen provides curl samples. Does sample-gen provide java script/ruby/python/java sample? Is there any documentation I can refer to? 😃

**Comment by tim-lai** [comment]
@jji2019 SwaggerUI's sample gen only provides curl samples. You may want to take a look at Swagger Editor's code generator [here:](https://editor.swagger.io). Thanks.
