### ISSUE TITLE
Default order on UI for same endpoint

### ISSUE THREAD

**Issue by lrozenblyum** [swagger-api/swagger-ui#7421]
### Q&A (please complete the following information)
 - Swagger-UI version: 3.47.1
 - Swagger/OpenAPI version: Swagger 2.1.9, OpenAPI 3.0

### Content & configuration
We have multiple endpoints for GET/POST/PUT/DELETE/OPTIONS/HEAD/PATCH methods for the same URL.
On swagger-ui they're currently sorted in the following order:
GET
PUT
POST
DELETE
OPTIONS
HEAD
PATCH

### How can we help?
We'd like to know if this order is deterministic/subject to change in next versions or fixed and we can rely on it?
We need to know that for documentation and automation purposes.

**Comment by hkosova** [comment]
By default, Swagger UI displays operations in the same order as they appear in your OpenAPI YAML/JSON file. You can use the [`operationSorter`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#operationsSorter) config parameter to sort operations by path, HTTP method, or in a custom order.

**Comment by lrozenblyum** [comment]
Thanks @hkosova !
