### ISSUE TITLE
Swagger and OData URIs integration

### ISSUE THREAD

**Issue by xuzhg** [swagger-api/swagger-ui#7426]
Copy from: https://github.com/OData/AspNetCoreOData/issues/236

Hey,

So I've got everything working in that an swagger.json file and the UI is working however for one of our controllers in particular with OData Uri options it seems to append the Uri option onto the end rather than where it has been specified in the OData route....

Example:

![image](https://user-images.githubusercontent.com/9426627/125991814-76efed4f-bd25-47ef-8aff-c825082f3067.png)

The {systemId} in the URL should be swapped for 'Test'... so it becomes B2B/ActiveTransaction/FromSystem(SystemId='Test') rather than B2B/ActiveTransaction/FromSystem(({systemId}))?systemId=Test
The controller & model is defined as follows...

        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        [HttpGet]
        public IActionResult FromSystem([FromODataUri] string systemId)
        {
            var systems = systemId.Split(',');
            return Ok(Service.GetAll().Where(t => systems.Contains(t.SourceSystemId)));
        }
The OData model has the following entry...

Builder.EntityType<ActiveTransaction().Collection.Function("FromSystem").ReturnsCollectionFromEntitySet<ActiveTransaction>("activeTransactionsFromSystem").Parameter<string>("systemId");
Yet the swagger UI seems to be getting this wrong.

Thanks,
Callum

**Comment by hkosova** [comment]
The API spec generated by your app is not quite correct. You need to change the annotations so that `systemId` is generated as a _path parameter_ rather than query parameter. The generated spec should look like this (YAML version):

```yaml
paths:
  /B2B/ActiveTransaction/FromSystem(systemId={systemId}):
    get:
      parameters:
        - in: path          # <---------
          name: systemId
          required: true    # <---------
          ...
```

We are not familiar with AspNetCoreOData so cannot help with their annotations. Please follow up with the AspNetCoreOData project directly for further troubleshooting.

**Comment by TehWardy** [comment]
I disagree with this ...
   /B2B/ActiveTransaction/FromSystem(systemId={systemId})
   
Is specified as the path route, the swagger framework when given this MVC route should honour it.
It's clearly not doing that.

Instead it's decided "hey i know better" and then appends the query param it found in that route template to the url again.
    /B2B/ActiveTransaction/FromSystem(systemId={systemId})?systemId=...
    
Swagger hasn't honoured the specification given.

**Comment by hkosova** [comment]
> the swagger framework

There are no official [Swagger](https://github.com/swagger-api) libraries for .NET or OData. The library you're using (OData/AspNetCoreOData) is not one of our projects, it's a third-party community project. We have no knowledge of this library so we don't know how it generates specs and cannot help with your .NET code.

Swagger UI simply renders the API spec generated by your app. Something in your code needs to be changed to generate the correct parameter type in the API spec. The folks at OData/AspNetCoreOData should be able to point you in the right direction.

**Comment by TehWardy** [comment]
Ah ok, I thought the swagger info was coming from the MVC framework directly since all OData does is add a bunch of stuff in to the Odata routing tables at this point.

It's not clear where Swagger gets the meta from to me.

**Comment by hkosova** [comment]
It might be coming from the MVC framework or from OData or from some other .NET library used (Swashbuckle?), I don't know. The point is, the problem is with the way the API spec is generated, and that is controlled by either the app code or the libraries used (or both). Unfortunately, that's not something we can help with.

**Comment by TehWardy** [comment]
Ok that's fair ... does swagger build it's UI from the json ?
in odata the json output is pushed to a url like ~/swagger/v1/swagger.json 

so if I can look at that and see that it's wrong that might help me give the OData guys the right bit of info regarding the fix needed or if it's something I can control I may be able to find the relevant OData doc / code fragment that's building the problem spec portion.

**Comment by hkosova** [comment]
> does swagger build it's UI from the json ?

Yes, Swagger UI renders the doc based on the info in the OpenAPI JSON/YAML file.

In your example, the `systemId` parameter is currently generated as `"in": "query"` but it needs to be `"in": "path"`. Path parameters also need `"required": true`. The JSON needs to look like this:

```
  "/B2B/ActiveTransaction/FromSystem(systemId={systemId})": {
    "get": {
      "parameters": [
        {
          "name": "systemId",
          "in": "path",
          "required": true,
          ...
        }
      ]
```
