### ISSUE TITLE
No Component section using apispec with flask

### ISSUE THREAD

**Issue by E-Kalla** [swagger-api/swagger-ui#7427]
### Q&A (please complete the following information)
 - OS: [Ubuntu]
 - Browser: [Firefox]
 - Method of installation: [pip]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
components:
  schemas:
    Fish:
      properties:
        babies:
          default: null
          items:
            $ref: '#/components/schemas/Fish'
          nullable: true
          type: array
        birthday:
          format: date-time
          type: string
        color:
          type: string
        name:
          type: string
        race:
          type: string
        scales:
          type: integer
        waterbreathing:
          default: false
          type: boolean
      type: object
info:
  description: A minimal API
  title: SPA
  version: 1.0.0
openapi: 3.0.3
paths:
  /polypets/add:
    get:
      description: addpolypet
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fish'

```

app configuration options:
```Python
app = Flask(__name__)  # Flask app instance initiated

class FishSchema(Schema):
    name = fields.String()
    color = fields.String()
    race = fields.String()
    waterbreathing = fields.Bool(default=True, required=False, missing=False)
    birthday = fields.DateTime()
    scales = fields.Integer()
    babies = fields.List(fields.Nested(lambda: FishSchema),required=False, missing=None)

api = Api(app)

spec = APISpec(
    title="SPA",
    version="1.0.0",
    openapi_version="3.0.3",
    info=dict(description="A minimal API"),
    plugins=[FlaskPlugin(), MarshmallowPlugin()],
)


@api.route("/polypets/add", methods=["GET"])
class createPet(Resource):
    def get(self):
        """polypetadd view
        ---
        description: addpolypet
        responses:
          200:
            content:
              application/json:
                schema: Fish
        """
        print(spec.to_yaml())
        print("SPEC: ", json.dumps(spec.to_dict()))
        return "Done"


spec.components.schema("Fish", schema=FishSchema)
method_view = createPet.as_view("Fish")
app.add_url_rule("/polypets/add", view_func=method_view)
with app.test_request_context():
    spec.path(view=method_view)
```

### Describe the bug you're encountering

I have no Component section on the swagger-ui when I start the app.
I only have Path section.
### To reproduce...

Create small flask app using apispec and marshmallow schema as I did.
Start the app and check the documentation url

### Expected behavior

Swaggerui should display Path section AND Component Section

### Screenshots
LighshotScreenshot
https://prnt.sc/1d1qo0x

### Additional context or thoughts
When I check swagger.json I have : https://prnt.sc/1d1rcmk
I can't see the component section

**Comment by hkosova** [comment]
This is not a Swagger UI issue but a problem with the spec generated by your app - there are no schemas in it. Swagger UI simply renders the API definition it's given.

I have no experience with Flask, but from a quick look there are two main issues:

1) For some reason the generated spec is `swagger: "2.0"` rather than `openapi: 3.0.3` as specified by the `openapi_version="3.0.3"` line.
2) All annotations inside `def get(self)` seem to be treated as the description text rather than parsed into response annotations.

Check the documentation of Flask and/or Marshmallow to see how to properly generate the spec you need, or open an issue with these projects for support.
