### ISSUE TITLE
Client sends ?param=undefined when query parameter is empty

### ISSUE THREAD

**Issue by ghost** [swagger-api/swagger-ui#743]
Seems to me that it should not send anything at all in this case (the query parameter was not specified as required = true).

**Comment by toymachiner62** [comment]
Query params are still defaulting to undefined. Has this issue resurfaced?

**Comment by seanoneillcode** [comment]
I'm seeing this issue too. If the response is 
```
{
    parameters: {
        _foo: {
             in: query,
             name: "_foo",
             required: false,
             type: "string"
        }
    }
}
```

then the resulting swagger UI uses the value 'undefined' for a _foo parameter.

**Comment by webron** [comment]
If such an issue exists, please open a new ticket. A ticket that was closed in 2014 is unlikely to be related to it since the code base has significantly changed.
