### ISSUE TITLE
Show schema objects as XML if content type is XML

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-ui#744]
Using latest master swaggerui code with swagger 2. 
If the content type is only XML then it looks odd for schema objects to be shown as JSON in swaggerUI.
I haven't yet experimented with the Example object, will that help show the examples as XML instead of JSON? Its hard to tell when there aren't any examples in the swagger 2 spec yet.
It would be good if the model schema representation changed as the content type changed, that way users could more easily cut and paste into the body field to test the api.

**Comment by chrisdudley** [comment]
That would be great, any idea when 2.1.0-M2 will be? 
I'm happy to give it a test if that would help?

**Comment by mohsen1** [comment]
Once the API from client is ready to get the raw schema we can render the schema in both JSON and XML formats. 

https://github.com/swagger-api/swagger-js/issues/311#issuecomment-85179689 is opened to provide that API

**Comment by Tucura** [comment]
Can you tell in which period the xml support will be available?

**Comment by fehguy** [comment]
Hi, it was targeted to the latest release (2.1.0-M2) but this feature didn't make it.  Will be by 2.1 proper.

**Comment by foufee** [comment]
When do you think that 2.1 proper will be ready, the XML feature would be very useful.

**Comment by webron** [comment]
@foufee - we aim for 2-3 weeks but can't guarantee.

**Comment by acazsouza** [comment]
+1 for XML support

**Comment by andrecastro** [comment]
Hi. When this feature will be done? I have a Rest API that works only with XML, it would be very useful for me. thanks.

**Comment by firefoxNX** [comment]
:+1:

**Comment by eq-3** [comment]
+1 :-)

**Comment by litti** [comment]
:+1:

**Comment by m-jedynak** [comment]
:+1:

**Comment by chreble** [comment]
:+1:

**Comment by jnupponen** [comment]
:+1:

**Comment by seoj** [comment]
:+1:

**Comment by foxsmart** [comment]
:+1:

**Comment by xurde** [comment]
This would be great. :+1: 
Can we help somehow?

**Comment by fehguy** [comment]
please track meta issue #1248
