### ISSUE TITLE
Private IP of build machine is being exposed!

### ISSUE THREAD

**Issue by pedrolamas** [swagger-api/swagger-ui#7446]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: edge
 - Version: 93
 - Method of installation: NuGet (.NET)
 - Swagger-UI version: (latest)
 - Swagger/OpenAPI version: (latest?)

### Describe the bug you're encountering

We are using [OWASP Zed Attack Proxy (ZAP)](https://www.zaproxy.org/) scan in our builds, and we just noticed a warning from "swagger-ui-bundle.js", specifically that it is exposing a Private IP.

When we looked, it was the build machine IP that was on the file, I believe caused by [this line](https://github.com/swagger-api/swagger-ui/blob/cc408812fc927e265da158bf68239530740ab4cc/webpack/_config-builder.js#L72).

### Expected behavior
No private information should be output. Personally, I can't think of any reason for the build machine name/ip to be part of the output bundle!

**Comment by char0n** [comment]
Hi @pedrolamas,

Thanks for pointing this out!

The addition of HOSTNAME in definition plugins comes from this commit: https://github.com/swagger-api/swagger-ui/commit/b7bbead9c7f97760bc29a372f28fcf3473a8367f#diff-1ebec643c7cac50a42cb61[…]389ad60f5ed0991fc3f10edf736a

It is associated with this ticket: https://github.com/swagger-api/swagger-ui/issues/1334

I've investigated and we don't use it nor need it AFAICT

**Comment by char0n** [comment]
Released in https://github.com/swagger-api/swagger-ui/releases/tag/v4.0.0-rc.0

**Comment by char0n** [comment]
Released in https://github.com/swagger-api/swagger-ui/releases/tag/v3.52.1
