### ISSUE TITLE
XMLElementWrapper - duplicated key mapping

### ISSUE THREAD

**Issue by luthionb** [swagger-api/swagger-ui#7461]
We upgraded the version of swagger-ui from 2.1.4 to 3.25.0. Unfortunately we are getting exception "duplicated mapping key" while opening the ui. The problem is the fact how we are using Xml annotations on our java class. The class looks like:

    @XmlRootElement(name = "Queue")
    public class Queue {
         private List<Process> activeProcesses = new ArrayList<>();
         private List<Process> endedProcesses = new ArrayList<>();
         private List<Process> endedWithErrorProcesses = new ArrayList<>();

        @XmlElementWrapper(name = "Active")
        @XmlElement(name = "Process")
        public List<BackgroundProcessSO> getActiveProcesses() {
             return activeProcesses;
        }

        @XmlElementWrapper(name = "Ended")
        @XmlElement(name = "Process")
        public List<BackgroundProcessSO> getEndedProcesses() {
             return endedProcesses;
        }

        @XmlElementWrapper(name = "EndedWithError")
        @XmlElement(name = "Process")
        public List<BackgroundProcessSO> getEndedWithErrorProcesses() {
             return endedWithErrorProcesses;
        }
    }

As a result our schema looks like:

    {
    "swagger": "2.0",
    "info" : {
          "description" : "Info.",
          "termsOfService" : "terms",
          "version" : "0.0.0",
          "title" : "Rest API"
    },
    "basePath" : "/restapi",
    "schemes" : [],
    "tags" : [],
    "definitions" : {
      "xml_ns0_queue" : {
        "type" : "object",
        "title" : "Queue",
        "allOf" : [
          {
            "properties" : {
              "Process" : {
                "xml" : {
                  "name" : "Active",
                  "wrapped" : true,
                  "namespace" : ""
                },
                "description" : "Active processes",
                "type" : "array",
                "items" : {
                  "$ref" : "#/definitions/xml_ns0_process"
                }
              },
              "Process" : {
                "xml" : {
                  "name" : "EndedWithError",
                  "wrapped" : true,
                  "namespace" : ""
                },
                "description" : "Ended with error processes",
                "type" : "array",
                "items" : {
                  "$ref" : "#/definitions/xml_ns0_process"
                }
              },
              "Process" : {
                "xml" : {
                  "name" : "Ended",
                  "wrapped" : true,
                  "namespace" : ""
                },
                "description" : "Ended processes",
                "type" : "array",
                "items" : {
                  "$ref" : "#/definitions/xml_ns0_process"
                }
              }
            }
          }
        ],
        "description" : "Processes Queues"
      }
      ,
      "xml_ns0_process" : {
        "type" : "object",
        "title" : "Process",
        "allOf" : [
          {
            "properties" : {
              "Created" : {
                "xml" : {
                  "attribute" : true,
                  "namespace" : ""
                },
                "description" : "Creation date",
                "type" : "string"
              },
              "Description" : {
                "xml" : {
                  "attribute" : true,
                  "namespace" : ""
                     },
                "description" : "Process description",
                "type" : "string"
                   }
                 }
               }
                  ],
                  "description" : "Process"
                }
    },
    "paths": {
      "\/queues/{id}" : {
        "get" : {
          "produces" : [ "application/xml" ],
          "parameters" : [
            {
              "name" : "id",
              "in" : "path",
              "required" : true,
              "type" : "string",
              "description" : "The id of the queue"
            }
          ],
          "responses" : {
            "200" : {
              "schema" : {
                "description" : "",
                "$ref" : "#/definitions/xml_ns0_queue"
              },
              "headers" : {
              },
              "description" : ""
            },
            "default" : {
              "description" : "Unexpected error."
            }
          }
        }
      }
    }
    }

In case there is a wrapped element around our property shouldn't swagger-ui correctly interpret such property?

**Comment by char0n** [comment]
Hi @luthionb,

Unfortunately this was a breaking change when migrating from 2.x to 3.x version of SwaggerUI. Our underlying YAML/JSON parser has a `json` option with default value of `false`:

`json (default: false) - compatibility with JSON.parse behavior. If true, then duplicate keys in a mapping will override values rather than throwing an error.`

If you generate OAS definitions with duplicate keys, I'd utilize some post-processing step where you get rid of duplicates. The easiest way how to achieve that is run your generated JSON document via standard JSON stringify -> JSON parse process and this will get rid of duplicates keys by override.

**Comment by char0n** [comment]
Closing this, assuming the proposed workaround worked.
