### ISSUE TITLE
Bug/Response Tabs not keyboard navigable

### ISSUE THREAD

**Issue by Cgfor3** [swagger-api/swagger-ui#7463]
### Q&A (please complete the following information)
 - OS: macOS 11.5 Big Sur
 - Browser: Chrome
 - Version: 92.0.4515.131
 - Method of installation: npm
 - Swagger-UI version: 3.52.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
The tabs implementation for `Example Value` and `Schema/Model` is not keyboard navigable.

### To reproduce...

1. Navigate to https://petstore.swagger.io/ 
2. Select the endpoint labeled "Add a new pet to the store" under the "Pet" API.
3. Press `Tab` 4 times to move through the elements in order
4. On the fourth `Tab` press you will notice that the focused elements skip from the `Try it out` button to the `Parameter content type` dropdown, skipping the entire tabs section.

### Expected behavior
The fourth tab press should focus on the element labeled `Example Value`. The next `Tab` press should focus the element labeled `Schema/Model`. Pressing `Enter` or `Space` should focus the unselected tab and update the visible tabpanel accordingly.

### Screenshots
**Tab focus to Example Value**
<img width="1166" alt="Screen Shot 2021-08-16 at 10 26 53 AM" src="https://user-images.githubusercontent.com/81174472/129579861-0f829971-bdfc-4a81-8783-86055cb459d5.png">

**Tab focus to Model**
<img width="1147" alt="Screen Shot 2021-08-16 at 10 27 08 AM" src="https://user-images.githubusercontent.com/81174472/129579884-bb3b1f1e-12e4-4d47-bd68-512f85fa7759.png">

**Tab focus to Tabpanel section**
<img width="1152" alt="Screen Shot 2021-08-16 at 10 27 24 AM" src="https://user-images.githubusercontent.com/81174472/129579904-aaca4336-e6bd-4925-a0f1-7a2b905b4bc9.png">

### Additional context or thoughts
Aria roles and other attributes will be necessary to accommodate screen reader a11y.

**Comment by char0n** [comment]
This is probably already detected in https://github.com/swagger-api/swagger-ui/issues/7350

It has been agreed in #7350 that the original reporters will start working on small PRs fixing keyword navigation issues related to a11y. You can help us a well if you wish.

**Comment by Cgfor3** [comment]
@char0n I will be putting up a PR soon that addresses this issue. I would appreciate any and all feedback. Should I link the PR on the issue you mentioned as well for visibility?

**Comment by char0n** [comment]
> I would appreciate any and all feedback

Of course, that what we're here for ;]

> Should I link the PR on the issue you mentioned as well for visibility?

Sure, the more cross-referenced we are the better.
