### ISSUE TITLE
GET doesn't work with request body

### ISSUE THREAD

**Issue by tamanna2702** [swagger-api/swagger-ui#7469]
Swagger UI gives the error : 'TypeError : Failed to execute fetch on Window.Request with GET/HEAD method cannot have body'.

Citing https://github.com/swagger-api/swagger-ui/issues/5388 which is closed now but since then OpenApi has allowed request body for GET/DELETE methods. : https://github.com/OAI/OpenAPI-Specification/pull/2117

**Comment by hkosova** [comment]
GET/HEAD/DELETE request bodies are allowed in OpenAPI v. 3.1, which is not supported yet. You can follow #5891 for updates on OAS 3.1 support.

**Comment by rererihab** [comment]
> GET/HEAD/DELETE request bodies are allowed in OpenAPI v. 3.1, which is not supported yet. You can follow #5891 for updates on OAS 3.1 support.

I have version 3.52.1 and it shows the same error when calling a get method with body

**Comment by FilipeMarch** [comment]
Is it possible to make a GET request with body nowadays in any branch?
I am still getting the error `TypeError: Request has method 'GET' and cannot have a body`

**Comment by emlaver** [comment]
Is this fixed in either v4 or v5?
