### ISSUE TITLE
Automatically parsing numbers as `Number`. How to allow `BigInt`?

### ISSUE THREAD

**Issue by lowercase00** [swagger-api/swagger-ui#7478]
### Q&A (please complete the following information)
 - OS: 11.5.2
 - Browser: Chrome 92.0, Safari 14.2
 - Method of installation: FastAPI
 - Swagger-UI version: 3.0.2

### Content & configuration
A JSON with the value `71788098513536042` returns `71788098513536040` (changes the last digit to zero). I'm using FastAPI and Pydantic e everything works fine in curl, etc.

**Comment by lowercase00** [comment]
That seemed to be a problem with 3.0.2, it seems fixed with 3.0.3. Closing

**Comment by lowercase00** [comment]
Not fixed actually. Don't know exactly why/when it rounds to zero. Is there any restriction on changing `Number` to `BigInt`?

**Comment by char0n** [comment]
Hi @lowercase00,

[JSON specification, section 6 (Numbers)](https://datatracker.ietf.org/doc/html/rfc7159) is quite clear about supported number ranges. Going beyond them creates issues of correctly interpreting numbers.

Another thing is that exposing integers via API in JSON format, that may be really big  is not a good idea. Accidentally one can generate a number that is outside of the range and different platforms consuming the JSON will interpret the number differently. Even [JSON:API](https://jsonapi.org/examples/) has a convention of sending numbers as strings to avoid that problem.Some time ago JavaScript landed a new type BigInt that can support ranges outside of 253 - 1. Unfortunately this type is not JSON serializable and the only recommended way of transferring it via JSON is: [transfer it as a string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Use_within_JSON). That way, every platform can deal with it as it likes.

Related https://github.com/swagger-api/swagger-ui/issues/2030

**Comment by lowercase00** [comment]
@char0n thanks a lot for your explanation, makes sense and I went on different route to get a shorter ID. Thanks a lot
