### ISSUE TITLE
Fix DELETE pill's width/alignment is off

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#7479]
Source: https://twitter.com/avantar/status/1432273563420135424

### Describe the bug you're encountering

The DELETE pill is too wide, compared to the others (GET/POST/etc)

### To reproduce...

See screenshot 

### Screenshots

![image](https://user-images.githubusercontent.com/8438485/131517945-e758d62a-452c-4ddf-8c5b-3ab126418f72.png)

### Additional context or thoughts

Either increase the other pills or decrease the DELETE pill

**Comment by ponelat** [comment]
## UI/UX Notes

- Any method is allowed, not just the common ones. How should long method names be handled?
- `OPTIONS` is even longer than DELETE (see screenshot below)

![image](https://user-images.githubusercontent.com/8438485/131522587-879ae6bc-f98f-4399-9474-85089c5bff8a.png)

**Comment by twjasa** [comment]
Hello ,

Did this 

![image](https://user-images.githubusercontent.com/12849040/134801522-6249374c-d959-4685-b9c3-070b99a0d4d7.png)

To me looks okay. Can I create the PR? 😄

**Comment by char0n** [comment]
Hi @twjasa,

Yeah looks good. `OPTIONS` and `DELETE` http verbs are the longest one currently supported. Go for a PR; looking forward to reviewing it
