### ISSUE TITLE
Removing option "try it out"

### ISSUE THREAD

**Issue by lochetti** [swagger-api/swagger-ui#749]
Is there a way to remove the option to try the api in some APIs? (Not all of them)

**Comment by bssarath** [comment]
Did you try passing an empty array to  the "supportedSubmitMethods" parameter while creating the Swagger UI object. As per the documentation  https://github.com/swagger-api/swagger-ui#parameters 
"An array of of the HTTP operations that will have the 'Try it out!' option. An empty array disables all operations. This does not filter the operations from the display."

**Comment by to-kra** [comment]
@webron find out how to disable it.. I did find out but after a while..

**Comment by paparthi** [comment]
Got it working for me in SpringFox 2.7.0.
Ref https://g00glen00b.be/documenting-rest-api-swagger-springfox/
And, create a bean like this:

    @Bean
    public UiConfiguration uiConfig() {
        String[] supportedMethods = {};
        return new UiConfiguration(null, supportedMethods);
    }
