### ISSUE TITLE
Console error on scroll: Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by kristina-kovacikova-acn** [swagger-api/swagger-ui#7497]
OS: [windows, mac]
Browser: [chrome, edge]
Swagger-Editor version: 3.52.2
Swagger/OpenAPI version: [OpenAPI 3.0.3]

### Description of the issue
When scrolling "Example value" =  inside class .highlight-code the following error is thrown in the browser's console
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

### Steps to reproduce
[swagger.txt](https://github.com/swagger-api/swagger-ui/files/7159312/swagger.txt)
1. Copy past OpenAPI definition from the file above into https://editor.swagger.io/
2. collapse /pet endpoint
3. open console in the dev tools
4. scroll inside body -> example value  -> error will be shown in the console

**Comment by char0n** [comment]
Hi @kristina-kovacikova-acn,

Thanks for reporting this. Would you be willing to entertain investigating this issue and providing a fix for it via PR?

**Comment by kristina-kovacikova-acn** [comment]
Hi @char0n, 

sure. I will can investigate the issue and provide PR.

**Comment by char0n** [comment]
@kristina-kovacikova-acn great!

**Comment by char0n** [comment]
Fixed on release/4.x branch.
