### ISSUE TITLE
Skip having the stream library as a dependency

### ISSUE THREAD

**Issue by dhenneke** [swagger-api/swagger-ui#7499]
We are having some trouble with the `stream` package because it only implements the `Stream` interface itself but doesn't support things like `stream.Readable`. This is problematic because we are including this library in a larger application ([backstage](https://github.com/backstage/backstage)) and it clashes with other dependencies that need some stream features (in our case [`pdfkit`](https://www.npmjs.com/package/pdfkit)). Since it is provided by this package, a configured polyfill fallback in webpack doesn't work anymore because the dependency is favoured over the other.

https://github.com/swagger-api/swagger-ui/issues/7341 aims to move it to a direct dependency, but for us, it woul be better to skip depending on the `stream` package. Maybe one can advice users to install it by themselves if they get problems? Or maybe make it a `peerDependency` so users can decide if they want to install it or not?

Using a more complete polyfill like [`stream-browserify`](https://www.npmjs.com/package/stream-browserify) would also be nice, but I assume this would again require a fork of the `xml` package.

**Comment by char0n** [comment]
I haven't found a reference of `stream` anything withing the code. We used the `stream` library in swagger-client library which is the dependency of swagger-ui, but we don't use it anymore and use more isomorphic approach. Let's try to remove it from deps and see if all the tests passes.

**Comment by char0n** [comment]
I've removed `stream` lib in https://github.com/swagger-api/swagger-ui/pull/7379/commits/211643dd598360a50c187608fa04a1a89d13741a and all the tests passed. Now I'm verifying that the appropriate pollyfix has been applied.

**Comment by char0n** [comment]
Webpack@4 applied `stream-browserify` and there hasn't been any significant increase in bundle sizes. I'll release this change in `4.0.0-rc.2`

**Comment by dhenneke** [comment]
> Webpack@4 applied `stream-browserify` and there hasn't been any significant increase in bundle sizes. I'll release this change in `4.0.0-rc.2`

Awesome, thanks! Any plans when you want to release the rc.2? We are eager to try the new version and see if the issue is fixed on our end.

**Comment by char0n** [comment]
During today

**Comment by char0n** [comment]
Released in https://github.com/swagger-api/swagger-ui/releases/tag/v4.0.0-rc.2
