### ISSUE TITLE
[Question] Support for groups (different domain views)

### ISSUE THREAD

**Issue by boeboe** [swagger-api/swagger-ui#750]
Hi,

I was wondering if swagger-ui already supports swagger **groups** (#116).

I have split my REST API to make a distinction between mobile clients (optimized for bandwidth) and other domain operations:
- http://localhost:9090/rest/api-docs?group=mobile
- http://localhost:9090/rest/api-docs?group=domain

Is there a way that I can use one swagger UI instance accessing both sup-API's or should I deploy 2 instances, each pointing to the proper part:

```
$(function () {
    var apiUrl = window.location.protocol + "//" + window.location.host;
    if (window.location.pathname.indexOf('/api') > 0) {
        apiUrl += window.location.pathname.substring(0, window.location.pathname.indexOf('/api'))
    }
    apiUrl += "/rest/api-docs?group=mobile";
    log('API URL: ' + apiUrl);
    window.swaggerUi = new SwaggerUi({
        url: apiUrl,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
        ...
```

Best regards,
Bart

**Comment by gkozyryatskyy** [comment]
Is this already possible with swagger-ui?
