### ISSUE TITLE
deepExtend makes some properties unconfigurable

### ISSUE THREAD

**Issue by RobertLowe** [swagger-api/swagger-ui#7505]
https://github.com/swagger-api/swagger-ui/blob/fdef4ead7a28b3b0aeb42ee544bf68578664a6fa/src/core/index.js#L120

For example, as soon as you turn on `requestSnippetsEnabled`

All default generators are enabled:

https://github.com/swagger-api/swagger-ui/blob/fdef4ead7a28b3b0aeb42ee544bf68578664a6fa/src/core/index.js#L57-L70

There is no way to exclude any of:

curl_powershell, curl_cmd, curl_bash

Once enabled. This is because of how options are merged together

This is really encumbersome if you're using your own snippet generators as there is no way to turn off any of those...

**Comment by char0n** [comment]
According to the [documentation](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#display) you should be able to use `languagesMask` option to only display generators that you wish.

```js
SwaggerUI({
  url: "https://petstore.swagger.io/v2/swagger.json",
  requestSnippetsEnabled: true,
  requestSnippets: {
    generators: {
      customGenerator1: {  ...  }
    },
    languagesMask: ['customGenerator1']
  }
})
```

Unfortunately I think there is a bug in on this line: 

https://github.com/swagger-api/swagger-ui/blob/8405fa01011f8bae3fa4f99ea924f43aa6c9bf24/src/core/plugins/request-snippets/selectors.js#L10

So if the above configuration doesn't work for you, we can fix this line by changing `languages` to `languagesMask` and problem should be solved.

**Comment by RobertLowe** [comment]
I think you're correct, I found that `languagesMask` had no effect.

The way configuration is handled still seems a bit odd to me

**Comment by RobertLowe** [comment]
Off topic: Update `languages` works, so the documentation is out-of-date.

**Comment by char0n** [comment]
@RobertLowe I assume your problem has been resolved, right? 

> The way configuration is handled still seems a bit odd to me

Sure, but it is what it is now and forms public API which is very hard to break off. 

I'll issue a PR for doc fix.

**Comment by char0n** [comment]
PR for docfix has been issued and merged to master: https://github.com/swagger-api/swagger-ui/pull/7509
