### ISSUE TITLE
[Question] @ApiModel used by swagger UI?

### ISSUE THREAD

**Issue by boeboe** [swagger-api/swagger-ui#751]
Hi,

I am experimenting with domain specific annotation to further extend the documentation generated by Swagger and displayed with Swagger-UI.

	@ApiModel(value="User", description="Model for showing user details")
	public class RestUser extends ResourceSupport implements Serializable {

		@JsonProperty("id")
		private Long userId;

		private String firstName;

		private String lastName;

		private String email;

		@JsonIgnore
		private String password;

		@ApiModelProperty(value = "gender of a person", allowableValues = "MALE, FEMALE")
		private Gender gender;

		...
	}

The `@ApiModelProperty` information is displayed in swagger UI. I can't find any information about the `@ApiModel` annotated information however. It this expected behavior or am I looking in the wrong place (swagger-springmvc issue)?

![screenshot from 2014-11-27 13 54 38](https://cloud.githubusercontent.com/assets/415310/5217143/fd10f45a-763c-11e4-875d-ae90403948c6.png)

Kindly,
Bart

**Comment by fehguy** [comment]
there is now a tool-tip for the swagger-2.0 properties, thanks to https://github.com/swagger-api/swagger-ui/pull/877

**Comment by Medii** [comment]
I have the same issue, still it doesn't work, I have the models's description in JSON object but swagger-ui doesn't render it. I tested it with both 2.1.0-M1 dist and latest trunk version.
