### ISSUE TITLE
Path parameter is missing

### ISSUE THREAD

**Issue by flwd3m** [swagger-api/swagger-ui#7512]
### Q&A (please complete the following information)
 - OS: linux
 - Browser: chrome
 - Version: 93.0.4577.63
 - Method of installation: npm
 - Swagger-UI version: 3.52.2
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'
info:
  title: QuickStart
  version: v1
host: quick.localhost
basePath: /api/v1
paths:
  /author/{id}/:
    get:
      operationId: author_get
      parameters: 
        - name: id
          in: query
          description: Id
          required: false
          type: integer
      responses:
        '200':
          description: OK
    parameters:
      - name: id
        in: path
        description: Id
        required: true
        type: integer

```

### To reproduce...
Create schema with the path that has two parameters with the same name.

### Expected behavior
Swagger UI will display both parameters

### Screenshots
Example

![Screenshot_20210917_171937](https://user-images.githubusercontent.com/16516528/133741301-a93acf72-4d05-42a8-b6e8-0a1e6e354b51.png)

**Comment by hkosova** [comment]
Thanks for the report! This issue is tracked in #7430 so I'll close this one as duplicate.
