### ISSUE TITLE
Cannot find module `querystring-browser`

### ISSUE THREAD

**Issue by benjdlambert** [swagger-api/swagger-ui#7556]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets] yarn
 - Swagger-UI version: [e.g. 3.10.0] - 4.0.0rc
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration
`Module not found: Error: Can't resolve 'querystring-browser' in '/tmp/backstage-e2e-fvJBjP/test-app/node_modules/swagger-ui-react'`

Looks like due to the `3.17.0` release of `swagger-client` which removed the `querystring-browser` dependency, this module fails to build with the latest stuff.

Had to force to use the older `3.16.0` of `swagger-client` to get this to work.

**Comment by mathis-m** [comment]
@char0n have a look at this! Probably due to the buffer PR.

**Comment by char0n** [comment]
Closing this for now. If any additional problems arise, please reopen.

**Comment by JeremyKennedy** [comment]
I can confirm that the 7 missing dependencies mentioned above are an issue when using the PnP feature of Yarn 2. I was able to fix it by repeatedly running `yarn add` with the dependencies reported as missing.

**Comment by kaiyoma** [comment]
Sounds like something about swagger doesn't work correctly with next-generation package managers.
