### ISSUE TITLE
Need to send OIDC ID Token instead of Access Token to API endpoints

### ISSUE THREAD

**Issue by JohnSchneider** [swagger-api/swagger-ui#7561]
### Q&A (please complete the following information)
 - OS: *
 - Browser: Firefox
 - Version: 93
 - Method of installation: dist assets
 - Swagger-UI version: 3.52.5
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: "Identity Management (IDM) Services"
  version: "2.2.0"
  description: ""
  contact:
    email: "apiteam@swagger.io"
servers:
- url: http://localhost:8080/idm-services/
components:
  securitySchemes:
    oidcAuthorizationCode:
      description: OpenID Connect Authorization Code Flow. Uses Proof Key for Code Exchange (PKCE).
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://acme.test/oauth2/default/v1/authorize
          tokenUrl: https://acme.test/oauth2/default/v1/token
          scopes:
            openid: OpenID Connect
            profile: User profile
            email: E-mail Address
security:
  - oidcAuthorizationCode:
      - openid
      - groups
      - profile
      - email
paths:
  /user/{userId}:
    get:
      tags:
      - user
      summary: Find user by ID
      description: Returns a single user
      operationId: getUserById
      parameters:
      - name: userId
        in: path
        description: ID of user to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
        204:
          description: No user found with given ID
          content: {}
        403:
          description: Access to the requested user information is denied
          content: {}
```

Swagger-UI configuration options:
```js
window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "swagger.yaml",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        oauth2RedirectUrl: "http://localhost:8080/idm-services-docs/oauth2-redirect.html"
      });
      // End Swagger UI call region

      ui.initOAuth({
        clientId: "redacted",
        scopeSeparator: " ",
        scopes: "openid profile email",
        usePkceWithAuthorizationCodeGrant: true
      });

      window.ui = ui;
```

### How can we help?
I've successfully hooked up Swagger UI to an OIDC Authorization server and I'm able to use the OAuth 2 authorization code flow with PKCE in order to login, get an authorization code and exchange code for both an access token and ID token.  However, I can't find a way to configure Swagger UI to use the obtained ID token rather than the access token when calling API endpoints.

Here is an example response that Swagger UI receives from my OIDC auth server's token endpoint, with the token strings redacted for clarity:
{"token_type":"Bearer","expires_in":3600,"access_token":"foo","scope":"openid email profile","id_token":"bar"}

Swagger successfully adds a Bearer token to API endpoints, however it is the value of "access_token" ("foo" in example above) and I need it to be the value of the id_token.

If I set persistAuthorization: true when instantiating SwaggerUIBundle, then Swagger UI stores an object named "oidcAuthorizationCode" in browser local storage and that does contain the needed id_token.  So, it seems that Swagger UI has access to the ID Token and I just need to be able to configure it to use that ID token value.  Perhaps a new boolean parameter with a name like "useIdToken" within the initOAuth method can be set up.  If set to true and an ID token is obtained, then the ID token would be used as the bearer token, otherwise the access token would be used.

**Comment by char0n** [comment]
@JohnSchneider would be great if you could produce a PR with a patch to our documentation where you feel it could be better.

**Comment by inouiw** [comment]
I created a workaround using wrapActions that uses the implicit flow with id_token and nonce.
A working example is at https://github.com/inouiw/SwaggerUIJsonWebToken
