### ISSUE TITLE
for 3.0.0 "callbacks" readonly: true parameters are not a part of callbacks

### ISSUE THREAD

**Issue by ityonemo** [swagger-api/swagger-ui#7562]
Example Swagger/OpenAPI definition:

https://app.swaggerhub.com/apis/ityonemo/Example-ReadOnly-Bug/1.0

### Describe the bug you're encountering

The reused component in the callback does not have the "id" parameter.

### Expected behavior
The reused component in the callback should have the "id" parameter, as a POST
in the callback direction has access to the read-only "id".

**Comment by hkosova** [comment]
Thanks for the providing the spec to reproduce the issue. This issue is tracked in #6294 so I'll close this one as a duplicate.
