### ISSUE TITLE
External schema definitions shall be shown in schema table, too

### ISSUE THREAD

**Issue by sdoeringNew** [swagger-api/swagger-ui#7573]
### Content & configuration

Swagger/OpenAPI definition - called ``minimal.yaml``:
 ```yaml
openapi: 3.0.3
info:
  title: title
  version: '1.0'
paths:
  /endpoint:
    get:
      summary: summary
      responses:
        200:
          description: description
          content:
            application/json:
              schema:
                $ref: './outsourced.yaml#/components/schemas/Result'
 ```
Nested schema definition - called ``outsourced.yaml``:
 ```yaml
components:
  schemas:
    Result:
      type: object
      properties:
        value:
          type: string
 ```

 Swagger-UI configuration options:
 ```js
 SwaggerUIBundle({
  url: "../minimal.yaml",
  dom_id: '#swagger-ui',
  deepLinking: true,
  presets: [
    SwaggerUIBundle.presets.apis,
    SwaggerUIStandalonePreset
  ],
  plugins: [
    SwaggerUIBundle.plugins.DownloadUrl
  ],
  layout: "StandaloneLayout"
})
 ```

Version:
e.g.: 3.30.2 or 3.52.5

### Is your feature request related to a problem?
There are no schemas on the swagger-ui page for the OpenAPI definition although there is one model in this minimal example. That model is defined in an externalized schema definition.

This is how it looks:
![no_external_schemas](https://user-images.githubusercontent.com/20087258/138511228-d4270a7b-4865-4c76-8710-7759e317811a.png)

### Describe the solution you'd like
I would like to see externalized schemas in the schema table, too.

Like this:
![with_external_schemas](https://user-images.githubusercontent.com/20087258/138511769-4315d95e-f761-4915-bfed-bd434cc57fd8.png)

### Describe alternatives you've considered
It's possible to workaround it to some degree:
 ```yaml
openapi: 3.0.3
info:
  title: title
  version: '1.0'
paths:
  /endpoint:
    get:
      summary: summary
      responses:
        200:
          description: description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
components:
  schemas:
    Result:
      $ref: './outsourced.yaml#/components/schemas/Result'
 ```

### Additional context
Although there is no schema table on the page the rest of the functionality works as expected. If I open the endpoint definition I even see an example for the externalized model. Hence the externalized definition can be accessed.

**Comment by hkosova** [comment]
Thanks for the feedback! This issue is tracked in #5318 so I'll close this one as a duplicate.
