### ISSUE TITLE
Support for Map<String,String>

### ISSUE THREAD

**Issue by theunreal** [swagger-api/swagger-ui#7579]
- Swagger-UI version: 3.26.2
 - Swagger/OpenAPI version: Springfox 3 (Swagger 2)

I have the following API definition:

`@RequestBody(required = false) Map<String, String> emailMapping) `

While in swagger UI it is shown without any input. I have no way to update the swagger-ui version since it's hardcoded in Springfox 3, I am asking to check if there is any workaround for it?

**Comment by hkosova** [comment]
Closing due to lack of response. Please reopen if you can provide more info.
