### ISSUE TITLE
4.x docker image

### ISSUE THREAD

**Issue by tughril** [swagger-api/swagger-ui#7580]
### Content & configuration

Thank you for releasing 4.x swagger-ui.
But the latest docker image version is still 3.x.
I want to use an open api 3.1 spec with docker in my development. So I'm waiting for a 4.x docker image published.

### Describe the solution you'd like
Please push a 4.x docker image to Docker Hub.

**Comment by char0n** [comment]
Hi @tughril,

> Thank you for releasing 4.x swagger-ui.

NP. Actually swagger-ui@4 is still in RELEASE CANDIDATE phase, currently in [RC4](https://www.npmjs.com/package/swagger-ui/v/4.0.0-rc.4).

> But the latest docker image version is still 3.x.

You can access v4.0.0-rc.4 docker image here: https://hub.docker.com/layers/swaggerapi/swagger-ui/v4.0.0-rc.4/images/sha256-eec8c5c485f05a2703ffcd23de751e22dafae6ee83813085a621ea5eb8e2196c?context=explore

The actuall full tag is: `swaggerapi/swagger-ui:v4.0.0-rc.4`

> I want to use an open api 3.1 spec

Please be advised that swagger-ui@4 doesn't come with support for Open API 3.1 (https://swagger.io/blog/api-design/what%E2%80%99s-ahead-for-swaggerui-v4-and-swaggereditor-v4/)
