### ISSUE TITLE
Cannot view the schema for a request body while in 'Try It Out' with OpenAPI v3

### ISSUE THREAD

**Issue by thomashardwick** [swagger-api/swagger-ui#7583]
### Content & configuration

Swagger/OpenAPI definition:
Try https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.json
vs https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/json/petstore.json 

### Is your feature request related to a problem?
Editing request bodies can be tricky, being able to refer back to the documentation is useful. Swagger used to give an easy way to do that with v2 API docs as you can switch back to the model while editing the body. This has gone away with v3, you can not switch. 

### Describe the solution you'd like
The option to switch back to the schema at any time like you could with the model with v2 api docs.

**Comment by hkosova** [comment]
Closing in favor of #7790.
