### ISSUE TITLE
Disabled syntax highlighting is broken in 4.0.0

### ISSUE THREAD

**Issue by M-Reimer** [swagger-api/swagger-ui#7603]
I’ve just updated to Swagger-UI version 4.0.0. And it seems like disabled syntax highlighting is broken in several ways.

At first: the config param “syntaxHighlight: false” is broken. Even if it is set, I still have syntax highlighting everywhere.

So I tried to change this to “syntaxHighlight: { activated: false, theme: "agate"}” which seems to get rid of syntax highlight. But now the layout is broken.

After digging a bit I found out that in some “class” attributes space characters seem to be missing. To get the layout fixed I had to add these workaround CSS rules:

      /* HACK. Disabled syntax highlight is broken in 4.0.0 */
      .swagger-ui .opblock-body pre.body-param__examplemicrolight,
      .swagger-ui .opblock-body pre.examplemicrolight,
      .swagger-ui .opblock-body pre.undefinedmicrolight {
        font-size: 12px;
        margin: 0;
        padding: 10px;
        white-space: pre-wrap;
        word-wrap: break-word;
        word-break: break-all;
        word-break: break-word;
        -webkit-hyphens: auto;
        -ms-hyphens: auto;
        hyphens: auto;
        border-radius: 4px;
        background: #333;
        overflow-wrap: break-word;
        font-family: monospace;
        font-weight: 600;
        color: #fff;
      }

Can someone please test disabled syntax highlighting? Thanks in advance.

**Comment by char0n** [comment]
I might have introduce the regression in this commit: https://github.com/swagger-api/swagger-ui/commit/46b4e5cf3f96a4dea0d2d8d78f6e4a90023c04ec

Investigating

**Comment by char0n** [comment]
Regression has been confirmed and fix has been created in https://github.com/swagger-api/swagger-ui/pull/7614.

**Comment by char0n** [comment]
Fix will be released in next minor or patch version of SwaggerUI.
