### ISSUE TITLE
The only place I've seen the default used is in the Get requests:

### ISSUE THREAD

**Issue by mjza** [swagger-api/swagger-ui#7631]
The only place I've seen the default used is in the Get requests:
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=Company#/Company/Company_Get2

![image](https://user-images.githubusercontent.com/545474/38422449-d08afe46-3978-11e8-9e0c-2622101f4006.png)

But in the Example Value it uses the data from example...
**_IF_** this is going to change the Example Value should use the default only if there is no example

_Originally posted by @heldersepu in https://github.com/swagger-api/swagger-ui/issues/4369#issuecomment-379246851_

**Comment by mjza** [comment]
Hi @heldersepu 

Could you please share a code that shows how can I use default values for GET parameters?

**Comment by heldersepu** [comment]
Just in case if you are not familiar how to navigate the json:
http://swagger-net-test.azurewebsites.net/swagger/docs/V1

```
    "/api/Company/Get2": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "GET Echo test of company",
        "operationId": "Company_Get2",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "text/html"
        ],
        "parameters": [
          {
            "name": "c.id",
            "in": "query",
            "description": "The Unique Company ID",
            "required": true,
            "type": "integer",
            "format": "int32",
            "default": 456
          },
          {
            "name": "c.myId",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "c.name",
            "in": "query",
            "description": "The Company Name",
            "required": false,
            "type": "string",
            "default": "My Company"
          },
          ...
```

**Comment by mjza** [comment]
Actually I am using .Net Core 6.0.
Could you please take a look to this question:

https://stackoverflow.com/questions/69899771/add-default-value-to-swagger-path-parameters

Maybe you can give me some hints.

**Comment by heldersepu** [comment]
same you need to add default to your generated json

**Comment by heldersepu** [comment]
@mjza you can close this issue this not no a swagger-ui issue

**Comment by heldersepu** [comment]
this might be of help
https://github.com/domaindrivendev/Swashbuckle.AspNetCore
