### ISSUE TITLE
OpenAPI 3.0 doesn't correctly handle escaped newlines in YAML/Markdown (ie: description) fields.

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#7641]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: Online
 - Swagger-UI/Editor version:
 ```js
  {
  "swaggerEditor": "4.0.1/gab9f22c-dirty",
  "swaggerUi": {
    "version": "4.1.0",
    "gitRevision": "gb71446c",
    "gitDirty": true,
    "buildTimestamp": "Mon, 08 Nov 2021 13:01:36 GMT"
  }
}
```

### Content & configuration
Using editor.swagger.io.

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  title: Newlines
  version: 1.0.0
  description: "One \nTwo" # Should render two lines
    
paths:
  /pet:
    post:
      description: "one \n two" # Should render two lines
      responses:
        default:
          description: A response
```
```yaml
swagger: "2.0"
info:
  title: Newlines
  version: 1.0.0
  description: "One \nTwo" # Correctly renders on two lines
    
paths:
  /pet:
    post:
      description: "one \n two" # Correctly renders on two lines
      responses:
        default:
          description: A response
```

### Describe the bug you're encountering
YAML has some weird ways of handling strings. One is that escaped newlines, like `\n`, are parsed as literal newlines when the string is wrapped in quotes. https://yaml-multiline.info/ is helpful  for figuring that stuff out.

I'm seeing a difference between OAS 3.0 and OAS 2.0 rendering, which I think is a bug.

### To reproduce...

1. Load the sample OpenAPI 3.0 definition into editor.swagger.io
2. View the rendering
3. Load the sample OpenAPI 2.0 definition into editor.swagger.io
4. View the rendering

### Expected behavior
For OAS 3.0, the descriptions are rendered with `One` and `two` on separate lines.
OAS 2.0 has the correct behaviour.

### Screenshots
OAS 3.0
![image](https://user-images.githubusercontent.com/8438485/141462588-41e2f903-44cb-4aa4-9a05-77dafb8afda3.png)

OAS 2.0
![image](https://user-images.githubusercontent.com/8438485/141462793-1b6c9ad9-178f-4398-9bc3-5ffe0c37290f.png)

### Additional context or thoughts
No idea why the YAML parsing or the markdown rendering is different between the two spec versions.

**Comment by hkosova** [comment]
Related: #6849
