### ISSUE TITLE
Lots of `TypeError: e.get(...) is undefined` in console for swagger-ui-react

### ISSUE THREAD

**Issue by cameron-toy** [swagger-api/swagger-ui#7658]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Firefox 91.2.0esr
 - Method of installation: npm
 - Swagger-UI version: 3.52.5 (swagger-ui-react)
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI unknown

### Bug
Rendering the API docs creates lots of error messages like in the title (but everything seems to be working fine). Expanding sections creates n + 1 more errors where n is the number of items in the expanded section.

Component is created like:
```jsx
<SwaggerUI
    spec={swaggerJSON}
    defaultModelsExpandDepth={-1}
    docExpansion="none"
    withCredentials={true}
    persistAuthorization={true}
    // Needed to allow cross-origin credentials
    requestInterceptor={r => Object.assign({}, r, { credentials: "include" })}
/>
```

### Expected behavior
Console is quiet

### Screenshots
![Screen Shot 2021-11-17 at 1 28 02 PM](https://user-images.githubusercontent.com/38936057/142285182-51a34602-d8ea-42cf-a192-9ee1f8f48a16.png)

**Comment by vldnovikov** [comment]
In my case, this error appears when by default I pass to `spec={undefind}` and then when  I receive `json` or `yaml` and replace it with `undefind`.

**Comment by cameron-toy** [comment]
@vldnovikov thanks, it turned out to be an async fetch issue for me. Doing a nullish check on `swaggerJSON` solved the issue.
