### ISSUE TITLE
@ParameterObject List Cannot be generated correctly

### ISSUE THREAD

**Issue by leshalv** [swagger-api/swagger-ui#7667]
![image](https://user-images.githubusercontent.com/30397655/142719882-b1e63d1b-fc6d-4be9-b48c-07fe4b5ce7a5.png)
![image](https://user-images.githubusercontent.com/30397655/142719916-de5ad112-90e8-4f50-b1ed-4ea54b70a4bf.png)

**Comment by mathis-m** [comment]
@leshalv seems like this is not an issue with swagger-ui. Please reach out to the project of the library you use!
