### ISSUE TITLE
swagger cant handle big responses

### ISSUE THREAD

**Issue by xpawko** [swagger-api/swagger-ui#7668]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 96
 - Method of installation: dev environment
 - Swagger-UI version:  3.25.0
 - Swagger/OpenAPI version: Swagger 3.0, OpenAPI 3.0

### Content & configuration

default

### Describe the bug you're encountering

After triggering recently introduced endpoint expecting massive response body (40mb+) swagger takes over 10 seconds to load then crashes.
Triggering the same endpoint in Postman succeeded;
Applying filters to the request in order to return about 10% of the response above, returns HTTP 200 OK but hangs later on.

### To reproduce...

1. Trigger endpoint expecting massive response body.

### Expected behavior

status OK 200 with corresponding response body

### Screenshots
no need

### Additional context or thoughts
none

**Comment by hkosova** [comment]
This issue is tracked in #3832. Closing as a duplicate.
