### ISSUE TITLE
multipart/form-data with file and json not working 

### ISSUE THREAD

**Issue by tweetysat** [swagger-api/swagger-ui#7691]
I'm having a spring boot application with a simple endpoint using multipart/form-data composed of 2 parts : an object and a file.

    @PostMapping(value = "/students", consumes = { MediaType.MULTIPART_FORM_DATA_VALUE })
    public ResponseEntity<String> storeStudent(
            @RequestPart("student") Student student,
            @RequestPart("file") MultipartFile file
    ) {
        System.out.println(student);
        System.out.println(file.getSize());
        return new ResponseEntity<>("Student stored", HttpStatus.OK);
    }

The open api 3 file contains

    {
      "openapi": "3.0.1",
      ...
      "paths": {
        "/api/students": {
          "post": {
            "tags": [
              "Dispatching"
            ],
            "operationId": "storeStudent",
            "requestBody": {
              "content": {
                "multipart/form-data": {
                  "schema": {
                    "required": [
                      "file",
                      "student"
                    ],
                    "type": "object",
                    "properties": {
                      "student": {
                        "$ref": "#/components/schemas/Student"
                      },
                      "file": {
                        "type": "string",
                        "format": "binary"
                      }
                    }
                  }
                }
              }
            },
            "responses": {
              ...
            }
          }
        },
      "components": {
        "schemas": {
          "Student": {
            "type": "object",
            "properties": {
              "firstName": {
                "type": "string"
              },
              "lastName": {
                "type": "string"
              }
            }
        }
      }
    }

When sending the request via Swagger UI I can see

    curl -X 'POST' \
      'http://127.0.0.1:8090/api/students' \
      -H 'accept: */*' \
      -H 'Content-Type: multipart/form-data' \
      -F 'student={
      "firstName": "string",
      "lastName": "string"
    }' \
      -F 'file=@2021-12-03 08_56_56-Postman.png;type=image/png'

Which gives me 

    {
      "code": 415,
      "status": "UNSUPPORTED_MEDIA_TYPE",
      "message": "Content type 'application/octet-stream' not supported",
      "timestamp": "2021-12-03 13:09:41"
    }

because there the student content type is not application/json.

How can I set that the student is application/json ?  There is nothing in the ui.

I tried adding

            encoding:  # at the same level as schema
              reply:
                contentType: application/json

But it has no effect on the ui and the curl request.

With postman I can choose the type which gives me

    curl --location --request POST 'http://127.0.0.1:8090/api/students' --form 'student="{\"firstName\": \"string\",\"lastName\": \"string\"}";type=application/json' --form 'file=@"/C:/Users/freiser/Downloads/2021-12-03 08_56_56-Postman.png"'

and there it is working.  I received a 200 response.

**Comment by hkosova** [comment]
Thanks for the bug report. The `multipart` + JSON issue is a known issue tracked in #4826 and #5356; also related to #6462. Please follow those issues for updates.

**Comment by LouCastaldo** [comment]
Same issue here, those tickets show issue has been open since 2018, 4years ??  When is this going to be fixed ?

**Comment by oyushko-rfhl** [comment]
I'll add the response from another issues which is helped me to solve the same issue...
You just need to add openApi configuration in your project:
`@Configuration
public class OpenApiConfig {

    @Bean
    public MappingJackson2HttpMessageConverter octetStreamJsonConverter() {
        MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
        converter.setSupportedMediaTypes(Arrays.asList(new MediaType("application", "octet-stream")));
        return converter;
    }
}`

**Comment by imbaTapac** [comment]
@oyushko-rfhl it then breaks all swagger answers in UI, it does not show any JSON but returns all responses as file
