### ISSUE TITLE
url parameter no longer works.

### ISSUE THREAD

**Issue by tettsuan** [swagger-api/swagger-ui#7702]
I have updated my document server (docker) with latest swagger-ui container (v4.1.3)
Since then, the url parameter is ignored and petshop document is displayed instead of my documents.

### Q&A (Client)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.93
 - Method of installation: docker 
 - Swagger-UI version: v4.1.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
URL that worked with v4.1.2 : http://xxxxxx/doc/v1/swagger/index.html?url=/doc/v1/apidocs/my-api.yaml&layout=BaseLayout

after upgrade the image to latest (v4.1.3). it displays petshop api.

### Describe the bug you're encountering
Somehow the url parameter is no longer evaluated.

### To reproduce...
Start container with v4.1.3 and open index.html with url parameter.

### Expected behavior
Swagger UI displays the document from url instead of default pet-shop document.

### Additional context or thoughts
I've downgraded the container temporarily (not 'latest' but with 'v4.1.2') and it works.

**Comment by fgrutsch** [comment]
Check the changelog of the v4.1.3 release [here](https://github.com/swagger-api/swagger-ui/releases/tag/v4.1.3).

Reading config from URL query params has been disabled by default, but there is a setting to enable it again. (consider the [security implications](https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx) though)

**Comment by tettsuan** [comment]
Thanks a lot for the information!
