### ISSUE TITLE
Syntax Highlighting multi line strings, using "|" seems broken

### ISSUE THREAD

**Issue by Skeeve** [swagger-api/swagger-ui#7703]
### Q&A (please complete the following information)
 - OS: macOS Version 10.15.7 (Build 19H1519)
 - Browser: Vivaldi
 - Version: 5.0.2497.28 (Stable channel) (x86_64)
 - Method of installation: docker swagger/swagger:latest
 - Swagger-UI version: 4.0.4
 - Swagger/OpenAPI version: OpenAPI 3.0.3

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  title: CSApi
  version: "1.0.16"
  x-info: |
    - Login information in user data
    - Password reset
    - email change
  description: API for accessing information in Database
  contact:
    email: support@my.do.main
    name: My Name
    url: "https://my.do.main"
servers:
  - url: "http://localhost:3181/api/v1"
    description: Developer instance
```

Swagger-UI configuration options:

Using OOTB docker container

```
?withCredentials=true
```

### Describe the bug you're encountering

Syntax highlighting of multi line strings is broken.

### To reproduce...

Insert the (partial) YAML given above and see everything after "x-info" be highlighted as a string.

### Expected behavior

From "description:" on, it shouldn't be highlighted as a string anymore

### Screenshots

![image](https://user-images.githubusercontent.com/725404/145960743-5d9d346d-6462-48fe-9582-8a8e1492650a.png)

### Additional context or thoughts

When you outdent "description:" to the very left, syntax highlighting is resumed.

**Comment by Skeeve** [comment]
Update: This also happens on editor.swagger.io

**Comment by Skeeve** [comment]
Workaround: Put a single "#" at the beginning of a new line after the end of the string.

**Comment by hkosova** [comment]
Thanks for the report! This issue is tracked in https://github.com/swagger-api/swagger-editor/issues/2828 so I'll close this one as a duplicate.
