### ISSUE TITLE
The name attribute of the annotation @ApiModelProperty does not take effect

### ISSUE THREAD

**Issue by huayangMr** [swagger-api/swagger-ui#7720]
When the second letter of the attribute `name `of my entity class is capitalized, swagger will interpret my letter as lowercase. At this time, I use the `name `attribute of `@ApiModelProperty `to solve the problem. It is found that it does not take effect. I hope to use the `name `attribute value to overwrite the original attribute value after JSON serialization, otherwise name does not play its due role, but will cause misunderstanding, I think this is a problem; I can understand if only the first letter is capitalized, but the second letter needs to be capitalized in many business scenarios

**Comment by hkosova** [comment]
Open an issue with the Java library that you use - [Springfox](https://github.com/springfox/springfox), [Springdoc](https://github.com/springdoc/springdoc-openapi), or [Swagger Core](https://github.com/swagger-api/swagger-core).
