### ISSUE TITLE
pluginLoadType: "chain" not working

### ISSUE THREAD

**Issue by JohnBednarczyk** [swagger-api/swagger-ui#7730]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 96.0.4664.110
 - Method of installation: dist assets
 - Swagger-UI version: 4.1.3
 - Swagger/OpenAPI version: OpenAPI 3.0

Swagger-UI configuration options:
```js
const ui = SwaggerUIBundle({
    url: baseRootUrl + "/test/openapi.json",
    dom_id: '#swagger-ui',
    docExpansion: 'none',
    tagsSorter: 'alpha',
    operationsSorter: 'alpha',
    deepLinking: true,
    pluginsOptions: {pluginLoadType: "chain"},
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
    ],
    plugins: [
        CollapsibleInfoPlugin,
        ExtendedInfoPlugin
    ],
    layout: "StandaloneLayout"
});
```

### Screenshots
![Screen Shot 2022-01-12 at 3 19 47 PM](https://user-images.githubusercontent.com/10479452/149223114-4afac466-2815-4759-b96f-ade29d8123ae.png)

### How can we help?
When I have pluginsOptions set to `pluginsOptions: {pluginLoadType: "legacy"}`, the error above does not display, but only one of my plugins works (both my plugins wrap the same component; info). I want to be able to chain load these plugins, but can't seem to do it

**Comment by JohnBednarczyk** [comment]
I'm have a lot of trouble testing this change. The exception is no longer thrown, however I haven't been able to compile the code with two of the same plugins yet.

I created a simple plugin based on the example [here](https://github.com/swagger-api/swagger-ui/blob/master/docs/customization/plugin-api.md#components) and added it to src/core/plugins. I also added the plugin to the plugins object in src/core/index.js:90, but when I start the dev server, the plugin is never loaded. This happens regardless of my change.

**Comment by char0n** [comment]
Right, thanks for pointing this out. The problem is in: https://github.com/swagger-api/swagger-ui/blob/e3b3bf03d46f7288371cc505a73f7a49b75da1db/src/core/plugins/swagger-js/index.js#L6

This creates immutable objects which cannot be mutated by our plugin system.
