### ISSUE TITLE
Accordion cannot be closed if type is a primitive

### ISSUE THREAD

**Issue by seressakos** [swagger-api/swagger-ui#7755]
Looks like the Swagger UI for the primitive types like string, int, bool, etc. does not wrap the content in the component.
That's why the content cannot be collapsed again after it is opened.
<img width="1397" alt="Screenshot 2022-01-14 at 10 50 46" src="https://user-images.githubusercontent.com/31951647/149526504-954c595f-7ab4-415e-b0d9-3cea3bdfb0e4.png">

**Comment by hkosova** [comment]
Thanks for the feedback! This issue is tracked in #7549 so I'll close this one as a duplicate. Please follow the linked issue for status updates.
