### ISSUE TITLE
Consider upgrading third party libraries

### ISSUE THREAD

**Issue by thegecko** [swagger-api/swagger-ui#776]
Swagger-ui uses outdated versions of jQuery, Backbone, underscore and Handlebars and in some cases relies on deprecated functionality.

Please consider making swagger-ui use more recent versions which support AMD and don't force a developer to use outdated versions -or- have to support downloading multiple versions of a library.

**Comment by mohsen1** [comment]
jQuery 1.8 is as far as we can go with the plugins and browser support. Rest of deps are updated in #883

**Comment by warmwaffles** [comment]
Is the IE6+ support that important? I'd be willing to bet that the people who are using swagger UI are developers with recent browser versions.

**Comment by fehguy** [comment]
We have some very large deployments which require this. Will drop support for ie7 or lower in 2.2.x.
