### ISSUE TITLE
Images *.jpeg are missing from repository

### ISSUE THREAD

**Issue by noirbizarre** [swagger-api/swagger-ui#778]
Hi!

I just noticed that some images used in templates are missing:
- apikey.jpeg in [src/main/template/apikey_button_view.handlebars](//github.com/swagger-api/swagger-ui/blob/master/src/main/template/apikey_button_view.handlebars)
- password.jpeg in [src/main/template/basic_auth_button_view.handlebars](//github.com/swagger-api/swagger-ui/blob/master/src/main/template/basic_auth_button_view.handlebars)

**Comment by fehguy** [comment]
fixed in templates.  will put this back when the auth ui becomes dynamic.
