### ISSUE TITLE
Response code and description columns are not aligned

### ISSUE THREAD

**Issue by lonix1** [swagger-api/swagger-ui#7850]
### Q&A (please complete the following information)
 - OS: linux
 - Browser: firefox
 - Version: 96 (latest)
 - Method of installation: asp.net core + swashbuckle 6.2.2 (latest)
 - Swagger-UI version: 3.52.1

### Content & configuration

Example Swagger/OpenAPI definition:
n/a

Swagger-UI configuration options:
n/a

### Describe the bug you're encountering

<img src="https://i.stack.imgur.com/xlUwD.png"/>

As you can see in the image, the response code and description are not aligned.

That is because the description has a `<p>` tag with `margin-top`.

### To reproduce...

1. Go to any swagger page
2. Click on any endpoint that is anotated with responses
3. See misalignment 

### Expected behavior
Alignment of code and description

### Screenshots
as above

### Additional context or thoughts
n/a

**Comment by j-andrespuk** [comment]
@lonix1 I wonder if you found a solution for this?

**Comment by lonix1** [comment]
@j-andrespuk No, sorry. It's a css bug in the library.

**Comment by smzelek** [comment]
I have opened a [PR to fix this ](https://github.com/swagger-api/swagger-ui/pull/8963), since it was just 2 lines of bad CSS causing the issue.
