### ISSUE TITLE
Query parameter with case-insensitive RegExp search fails

### ISSUE THREAD

**Issue by scott-fisher-iii** [swagger-api/swagger-ui#7891]
### Q&A (please complete the following information)
 - OS: Windows 10 x64
 - Browser: Chrome 98.0.4758.102 (Official Build) (64-bit), Edge 98.0.1108.62 (Official build) (64-bit)
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 3.52.1
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

When having a case-insensitive regular expression for a query parameter, Swagger reports a console error about invalid RegExp group and fails to send the call to the API, but the same code as a route/path parameter works fine without error.

The query parameter I am using is a required query parameter and I have tried toggling the required tag to make it optional, but get the same error.
This was happening with the underlying API was running .NET Core 3.1 (LTS) which has now been updated to .NET 6 (LTS) and the issue has persisted after the update.
The API uses the NuGet package `"Swashbuckle.AspNetCore" Version="6.2.3"`

It appears as if some logic that parses case-insensitive regular expressions is different between the route/path and query parameter types.

*EDIT 2022-03-24* I can create the same console error with a route parameter so it doesn't appear to be specific to query parameters.

### Code setup (from swagger.json)
When the "in" is "query" the call fails/hangs:
```"/protected/something": {
   "put": {
      "tags": [
         "Protected"
      ],
      "summary": "Test Something",
      "description": "A protected endpoint",
      "parameters": [
         {
            "name": "action",
            "in": "query",
            "required": true,
            "schema": {
               "pattern": "(?i)(ADD|REMOVE)",
               "type": "string"
            }
         }
      ]
   }
}
```

When the "in" is "path" the call is successful:
```"/protected/something": {
   "put": {
      "tags": [
         "Protected"
      ],
      "summary": "Test Something",
      "description": "A protected endpoint",
      "parameters": [
         {
            "name": "action",
            "in": "path",
            "required": true,
            "schema": {
               "pattern": "(?i)(ADD|REMOVE)",
               "type": "string"
            }
         }
      ]
   }
}
```

### Expected behavior
Able to have a case-insensitive query parameter and submit a call to the API from Swagger UI.

### Screenshots
![image](https://user-images.githubusercontent.com/54987387/156809975-4d0eaa8f-e8a8-46c9-85eb-1291b721a563.png)

**Comment by soundstripe** [comment]
I think this issue is the same as mine. I use commented regular expressions in this format: `"(?#Letters, Numbers, Spaces)[A-Za-z0-9 '\-]+"` within my (Python) API. These are valid in Python, but of course regular expression syntax varies across languages. The code that attempts to validate the regex on the frontend needs to be wrapped in an exception handler that allows the API to do the validation.

**Comment by scott-fisher-iii** [comment]
I agree with that suggestion, @soundstripe.
I also played around with it a little bit and could get it to throw a console error for route parameters too, where I couldn't at first.
So it doesn't appear to be specific to query vs. route parameters.
