### ISSUE TITLE
Multipart forms don't work as expected

### ISSUE THREAD

**Issue by wdiu** [swagger-api/swagger-ui#790]
I have a multipart form with 3 parts: form parameter, JSON, and file upload.
1) If I treat all 3 of them as "body" parameters, only the "file" upload will be sent in the HTTP request.
2) If I treat the first part as "form" parameter and the JSON and file upload as "body" parameters, only the first part and the "file" upload will be sent in the HTTP request.
3) If I treat the first part as "form" parameter and datatype "string," the second part as "form" parameter and datatype "MyCustomObject," and the third part as "file" and "body," the HTTP request works perfectly but the problem is that MyCustomObject only appears as single line in the UI.  It should really be multiline!  Worse, even though under "Model Schema" it states "Click to set as parameter value," clicking will not populate the textbox.

With options 1 and 2, the UI displays properly but the HTTP request is missing parts.  With option 3, the UI doesn't display properly but the HTTP request is correct.

**Comment by NoumanSaleem** [comment]
@fehguy passing each property as a form parameter doesn't seem to work either

When submitting [uploadFile](http://petstore.swagger.io/#!/pet/uploadFile)
The `additionalMetadata` is not sent with the request
