### ISSUE TITLE
Build failure from possible new release

### ISSUE THREAD

**Issue by babarinde** [swagger-api/swagger-ui#7902]
Hi and thanks for the great work
We are running "swagger-ui": "^4.1.3",
We are noticing this error in [our build logs ](https://gist.github.com/babarinde/ddd5e5d7f17f09d7eff7a584053e4855)
We had this working a few hours before build.

**Comment by scottohara** [comment]
As of version 4.6.0, swagger-ui is now built using webpack 5.

If you are also using webpack 5 (which no longer includes node polyfills), you may need to include them.

In our case, after upgrading to v4.6.0 we had to install `buffer` and `stream-browserify`, and then update our webpack config:

```js
resolve: {
  fallback: {
    stream: require.resolve(‘stream-browserify’)
  }
},
plugins: [
  new webpack.ProvidePlugin({
    ‘buffer’: [‘Buffer’, ‘buffer’]
  })
]
```

**Comment by babarinde** [comment]
Downgraded to 4.5.2 in the mean time in order to figure this out

**Comment by char0n** [comment]
I've produced https://github.com/swagger-api/swagger-ui/pull/7946 which should remedy this issue completely. No `resolve.fallbacks` and `ProvidePlugin` required anymore and the SwaggerUI will work with Create React App out of the box.

**Comment by char0n** [comment]
Fixed in https://github.com/swagger-api/swagger-ui/releases/tag/v4.10.0
