### ISSUE TITLE
docker: use docker-entrypoint.d-script instead of own cmd

### ISSUE THREAD

**Issue by Blaimi** [swagger-api/swagger-ui#7915]
`Dockerfile` overwrites the upstream `CMD` with it's own script to configure swagger-ui which itself start the original command at the end.

Instead of overwriting the `nginx`-command with `sh`, the configuration should be done via a script inside of `/docker-entrypoint.d/`. `/docker-entrypoint.sh` from nginx executed these scripts only if the `CMD` is `nginx` but not on any other `CMD` like here.

This improvement does not only reenable the scripts inside this directory which are placed upstream, but also allows any user to add their own scripts, e.g. by mounting them from the container-engine inside this directory like they are used to do with original nginx-containers.

**Comment by joshmcgrath08** [comment]
After this change, it's no longer the case that the installation/startup instructions for docker work. Is this intended? If so, what's the new, recommended way?

![image](https://user-images.githubusercontent.com/2574964/162602133-eee7f071-9fa5-492a-b255-7d3a96bb2315.png)
https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation/#docker

**Comment by Blaimi** [comment]
@joshmcgrath08 can you provide some additional information about your environment or some error-messages?

**Comment by joshmcgrath08** [comment]
@Blaimi My apologies. I can confirm there is no issue. It broke a way I was using it (different from the recommended instructions) and I thought I was testing the recommended instructions I linked properly, but I was mistaken. (Because I never remember the order of ports for Docker I assumed that the instructions bound container 80 to host 8080, but I had it backwards in my testing.) Sorry about that.

**Comment by Blaimi** [comment]
> Because I never remember the order of ports for Docker I assumed that the instructions bound container 80 to host 8080, but I had it backwards in my testing.

Classic :D I also need to always rtfm to get the order.
