### ISSUE TITLE
Swagger-UI doesn't apply OAuth2 header to requests

### ISSUE THREAD

**Issue by si14** [swagger-api/swagger-ui#792]
I'm using the latest master https://github.com/swagger-api/swagger-ui/commit/d6a1dafd5cb43a80ea25167c2c69add0da558b4c with Swagger Spec 1.2 and OAuth2-protected API. I've got authorization running, but the problem is that Swagger just skips `Authorization` header altogether, despite `window.authorizations` being correctly set up.

Here is how it looks like:
![screenshot1](https://cloud.githubusercontent.com/assets/316910/5557630/4e7dc444-8d17-11e4-980c-9ca841a4a491.png)

However, there is no `Authorization: Bearer blah-blah` header:
![screenshot2](https://cloud.githubusercontent.com/assets/316910/5557640/659fdf0e-8d17-11e4-8039-002f4c1f9d5b.png)

It looks like Shred is used instead of JQuery, if this can help.

**Comment by fehguy** [comment]
Thank you--I'll see how to get this verified shortly

**Comment by fehguy** [comment]
I cannot reproduce this, but will keep open and retry in M2

**Comment by mohsen1** [comment]
I can't reproduce it at bcd09ed. It seems that we're now doing what @pgkehle is suggesting in his comment. Please let us know if you're still having this issue.
