### ISSUE TITLE
swagger-ui npm module doesn't compile with Angular 11

### ISSUE THREAD

**Issue by LittleBaiBai** [swagger-api/swagger-ui#7935]
### Q&A
 - OS: macOS, Linux
 - Browser: n/a
 - Version: n/a
 - Method of installation: npm
 - Swagger-UI version: upgrading from `4.1.3` (working fine) to `4.8.1` for `@braintree/sanitize-url` upgrade
 - Swagger/OpenAPI version: n/a
 - Angular: 11.2.18
 - Node: 12.18.4

### Describe the bug you're encountering
Similar to [this issue](https://github.com/swagger-api/swagger-ui/issues/4971) closed in 2018:

```
> Task :npm_run_build

> ng build --prod

- Generating browser application bundles...
✔ Browser application bundle generation complete.

Warning: /tmp/build/80754af9/my-repo/app.component.ts depends on 'swagger-ui'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies


Error: ./node_modules/xml/lib/xml.js
Module not found: Error: Can't resolve 'stream' in '/tmp/build/80754af9/my-repo/node_modules/xml/lib'
resolve 'stream' in '/tmp/build/80754af9/my-repo/node_modules/xml/lib'
  Parsed request is a module
  using description file: /tmp/build/80754af9/my-repo/node_modules/xml/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /tmp/build/80754af9/my-repo
        using description file: /tmp/build/80754af9/my-repo/package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /tmp/build/80754af9/my-repo/package.json (relative path: ./stream)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build/80754af9/my-repo/stream doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /tmp/build/80754af9/my-repo/stream.ts doesn't exist
            ...............
```

### To reproduce...

Repo: https://github.com/LittleBaiBai/swagger-ui-angular-bug

```
nvm use 12.18.4
npm install
npm start
```

Then you will get the error:
```
Error: ./node_modules/xml/lib/xml.js
Module not found: Error: Can't resolve 'stream' in '/Users/ybai/workspace/tmp/my-app/node_modules/xml/lib'
```

### Expected behavior
Run without error.

### Additional context or thoughts
A little bit digging in the commit history:
- To address the similar issue I linked above, there was [a fix in 2018](https://github.com/swagger-api/swagger-ui/pull/4985) to stop using the `xml` dependency but use `@kyleshockey/xml` instead. 
- Then that was reverted/reworked in Nov 2021 in [this commit](https://github.com/swagger-api/swagger-ui/commit/cf9a3657cca2efd41dc3297e5ca12344b9124750) by adding the `stream` dependency. 
- Then `stream` was taken out again in [this commit](https://github.com/swagger-api/swagger-ui/commit/b90c6b5a09471bdc278e723f84f8633d9660088a) on the same day. 
- All that history happened before the 4.0.0 release.

Still not sure why we are getting this error from the 4.1.3->4.8.1 upgrade, but hope that saves you some investigation time.

**Comment by mikegehard** [comment]
This error also happens with a 4.1.3 -> 4.2.0

```
diff --git a/ng-api-portal/package.json b/ng-api-portal/package.json
index f254686..4eb11c4 100644
--- a/ng-api-portal/package.json
+++ b/ng-api-portal/package.json
@@ -29,7 +29,7 @@
     "lunr": "^2.3.9",
     "ngx-clipboard": "^13.0.1",
     "rxjs": "~6.5.5",
-    "swagger-ui": "^4.1.3",
+    "swagger-ui": "^4.2.0",
     "tslib": "^2.0.0",
     "zone.js": "~0.10.3"
   },
```

```
Error: ./node_modules/xml/lib/xml.js
Module not found: Error: Can't resolve 'stream' in '/myapp/node_modules/xml/lib'
resolve 'stream' in '/myapp/node_modules/xml/lib'
```

**Comment by char0n** [comment]
Hi everybody,

`stream` is part of Node.js API. In past we used [stream npm package](https://www.npmjs.com/package/stream) We dropped support for this package as it's last release is 7 years old. Instead we use [stream-browserify](https://www.npmjs.com/package/stream-browserify) (which has more frequent releases) when building build fragments as demonstrated here: https://github.com/swagger-api/swagger-ui/blob/master/webpack/_config-builder.js#L114

As far as I understand the Angular build system uses webpack as well. In order for build to work correctly `resolve.fallback` needs to be provided to webpack as demonstrate in above webpack config. Would that work for you?

**Comment by mikegehard** [comment]
@char0n We will try that and see what happens.

**Comment by mikegehard** [comment]
@char0n I don't think that this solution will work for us.

Angular 11 still defaults to webpack 4 and I can't seem to find any docs on how to configure webpack4 to do fallbacks:
https://v4.webpack.js.org/configuration/resolve/#resolve

We could try to upgrade to webpack5 to get the fallback functionality but I wanted to see if there was anything you could do from your end to help first.

**Comment by char0n** [comment]
@mikegehard, if you're using webpack@4 you have couple of options:

### Possible solution 1

If webpack build target is unspecified or `web` then internal webpack plugin called `NodeSourcePlugin` kicks in automatically and by setting `stream: true` it will include the polyfill.

```
node: {
  stream: true
} 
```

### Possible solution 2

I haven't tested this, but should most possibly work as well. First install `stream-browserify`.

```
resolve: {
  alias: {
     stream: require.resolve("stream-browserify"),
  } 
}
```

> We could try to upgrade to webpack5 to get the fallback functionality but I wanted to see if there was anything you could do from your end to help first.

Don't think it's necessary to upgrade. webpack@4 with `Possible solution 1` should work and apply the `stream` polyfill. There's not much we can do on our side, except again using 7 years old stream library or switch `xml` package to different one. But that will require significant effort. If you're using webpack@4 for building this shouldn't be an issue. Please try the possible solution I've documented and let me know.

**Comment by char0n** [comment]
Fixed in https://github.com/swagger-api/swagger-ui/releases/tag/v4.10.0
