### ISSUE TITLE
Attempted import error: 'randexp' does not contain a default export (imported as 'i').

### ISSUE THREAD

**Issue by w0rmr1d3r** [swagger-api/swagger-ui#7962]
### Q&A (please complete the following information)
 - OS: macOS Big Sur 11.6.5
 - Browser: doesn't apply
 - Version: version of the browser?
 - Method of installation: npm
 - Swagger-UI version: 4.10.0
 - Swagger/OpenAPI version: don't now

### Content & configuration

File `package.json`:
```
"swagger-ui-react": "^4.10.0",
```

### To reproduce...
1. Migrated from `4.1.2` to `4.10.0`
1. Run `npm run build`
2. Obtained the error below

```
Creating an optimized production build...
Failed to compile.

./node_modules/swagger-ui-react/swagger-ui-es-bundle-core.js
Attempted import error: 'randexp' does not contain a default export (imported as 'i').
```

### Expected behaviour
Able to run the command.

**Comment by tim-lai** [comment]
@w0rmr1d3r I'm running a project with `swagger-ui-react@4.10.0` and can build without issues. There may be an issue with the configuration in your build tool. Perhaps you could provide a link to your project, and a community member might be able to help troubleshoot?

**Comment by w0rmr1d3r** [comment]
Hi @tim-lai !
Thank you for your answer.

I can't share the project, since it's company internal. But I might be able to provide more info regarding the build tool.

What information may you need for it?

thanks

**Comment by tim-lai** [comment]
@w0rmr1d3r Any platform/environment details would be helpful. e.g. there are recent closed issues related to recent bundling changes where the users were using Typescript. Thanks.

**Comment by w0rmr1d3r** [comment]
Hi @tim-lai 
Let me provide more context:

I'm using React with version `17.0.2`

Using these engines:
```json
  "engines": {
    "node": "^16.13.0",
    "npm": "^8.1.0"
  },
```

Importing the library like so:
```typescript
import SwaggerUI from 'swagger-ui-react';
```

Thought this was related to this, https://github.com/swagger-api/swagger-ui/issues/7970 , upgraded to 4.10.3 but it reported the same failure.
Reviewed more issues such as:
https://github.com/swagger-api/swagger-ui/issues/7935
https://github.com/swagger-api/swagger-ui/issues/7944
https://github.com/swagger-api/swagger-ui/issues/7893

And PRs such as:
https://github.com/swagger-api/swagger-ui/pull/7946
https://github.com/swagger-api/swagger-ui/pull/7927

I'm not an expert on this subject, found this post:
https://bobbyhadz.com/blog/javascript-does-not-contain-default-export
Which it seemed to me to be related to this issue.

This project is using randexp in https://github.com/swagger-api/swagger-ui/blob/b825e440770d9328996a116784cb77b05ab24c6c/src/core/plugins/samples/fn.js#L2
Which is a project that hasn't been updated in 4 years, is it possible to use another one instead? A newer one?

Thanks in advance!

**Comment by char0n** [comment]
Hi guys,

I haven't been able to reproduce this. If I run following code in Node.js engine:

```js
import * as i from "randexp"; // i.default === RandExp
import RandExp from "randexp";
```

We're getting correct results. @w0rmr1d3r without providing more information, this issue will not be actionable. Could you please create a public GitHub repo with minimal steps to reproduce this problem?

webpack@5 handles it also well. I assume that the problem is somehow caused by your build system which has limited interoperability between ESM and CommonJS. But again without the GitHub repo with minal steps to reproduce, we cannot help more.

**Comment by w0rmr1d3r** [comment]
Hello @char0n ,
Thank you for the information provided.

Since I can't share the entire repo because it's private and sharing a part of it wouldn't match the scenario, I'd rather look into it privately.
As discussed and tested, it might be more of an internal issue rather than related to the package.

Thank you again for your information. I will pass this issue to our teams 😄

**Comment by w0rmr1d3r** [comment]
Hello @char0n ,

Managed to solve the issue.
We bumped the project, so it uses now:
```text
Now using node v16.15.1 (npm v8.11.0)
```

And was able to bump from `4.1.2` to `^4.10.0`, all I needed to do was add `"randexp": "^0.5.3",` in the `devDependencies`.

The `build` step of the project can now finish successfully, test pass and all.

Cheers!
