### ISSUE TITLE
Is there a way to always stay logged in swagger-php UI ? (green padlock Authorize button)

### ISSUE THREAD

**Issue by pascalf22** [swagger-api/swagger-ui#7966]
Hello !

I wonder if it's possible to prevent to always have to click on 'authorize' button on every page refresh to copy/past the token?

Is it possible, by code.. to specify the token to use on my dev server ? So on every refresh page or page load.. we will be logged in ?

Thank you so much !
Have a great day !
Pascal

**Comment by mathis-m** [comment]
You can use the `persistAuthorization` option. Then you only need to authorize once.

**Comment by pascalf22** [comment]
Thank you for your response ! I really appreciated it ! I will try it ! 
Have a great day !
