### ISSUE TITLE
4.9.1 breaks loading of /api-docs and loads petstore by default

### ISSUE THREAD

**Issue by lukasimha2** [swagger-api/swagger-ui#7972]
Our application uses the below config

```
springdoc:
  swagger-ui:
    path: "/"
  api-docs:
    path: "/api-docs"
```

and the following version of the libraries

       <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.6</version>
        </dependency>

       <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>swagger-ui</artifactId>
            <version>4.8.1</version>
        </dependency>

Until swagger-ui, 4.8.1 we see these 2 lines in index.html of swagger-ui (default) and hence the /api-docs loads correctly
  "configUrl" : "/api-docs/swagger-config",
  "validatorUrl" : ""

```
<script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "https://petstore.swagger.io/v2/swagger.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout" ,

  "configUrl" : "/api-docs/swagger-config",
  "validatorUrl" : ""

      });
      // End Swagger UI call region

      window.ui = ui;
    };
</script>
```

Once swagger-ui was upgraded to 4.9.1 we see that there are multiple .js files that are loaded and now the "/api-docs" does not load and always loads the PetStore configuration.

Loading the url http://localhost:8080/swagger-ui/index.html?configUrl=/api-docs/swagger-config also has no effect. Only entering the "/api-docs" in the search box loads the application configuration correctly.

**Comment by char0n** [comment]
Hi @lukasimha2,

I think you're being affected by https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx

Try to set `queryConfigEnabled` to `true` and let's see if it resolves your problem.

```html
<script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        queryConfigEnabled: true,
        url: "https://petstore.swagger.io/v2/swagger.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout" ,

  "configUrl" : "/api-docs/swagger-config",
  "validatorUrl" : ""

      });
      // End Swagger UI call region

      window.ui = ui;
    };
</script>
```
