### ISSUE TITLE
Installation docs are out of date

### ISSUE THREAD

**Issue by tomjoht** [swagger-api/swagger-ui#7974]
### Q&A (please complete the following information)
 - OS: Mac
 - Browser: Chrome
 - Version: latest
 - Method of installation: dist
 - Swagger-UI version: 4.10.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Issue

The docs on installation seem out of date. On https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md, in the "Plain old HTML/CSS/JS (Standalone)" section, step 3 says:

> Open index.html in your HTML editor and replace "https://petstore.swagger.io/v2/swagger.json" with the URL for your OpenAPI 3.0 spec.

It seems that `index.html` is no longer the file where the swagger.json file is configured. Instead, it is `swagger-initializer.js`. 

Also, just curious, but I no longer get a CORS issue when viewing the Swagger UI file locally in my browser. (Previously, I had to run simple server to view the file locally.) Is that because of this change?

**Comment by tim-lai** [comment]
@tomjoht Yup, missed a spot in the docs that need to get updated. `installation.md` should get updated to match `https://github.com/swagger-api/swagger-ui/blob/master/docs/development/setting-up.md`. Happy to accept a PR on this! 😉
