### ISSUE TITLE
BasicAuthButton is not created for basic auth declarations in the securityDefinitions api spec section

### ISSUE THREAD

**Issue by kcq** [swagger-api/swagger-ui#798]
The button code/view is there (in MainView.coffee: "if auth.type is "basicAuth" and $("#basic_auth_button").length is 0"), but it's not working because it's not wired up yet :-)

Also, it appears that there's a disconnect between the swagger spec (v2) and the UI code. According to the spec the basic auth type value is "basic", but the UI code expects it to be "basicAuth".

**Comment by fehguy** [comment]
OK moving this into M2, it won't be ready this weekend :(

**Comment by tarlog** [comment]
+1

**Comment by codeHatcher** [comment]
+1111111

**Comment by phxql** [comment]
+1

**Comment by torgeir** [comment]
+1

**Comment by boillodmanuel** [comment]
Hello, we want to contribute to this issue. Did you have any advice to do it? We can work on it next week.

Thanks

**Comment by fehguy** [comment]
Thank you!  In general we need html support for rendering authentication info in the ui based on the spec. There are api key, basic auth, and oauth flows. Designs would be helpful and there are support classes built in coffeescript

**Comment by quilicicf** [comment]
Hi, I'm a coworker of @boillodmanuel's and will be working on this topic. Could you give more precise inputs as to how you'd like us to contribute and maybe specific location of the code that needs an update ? 
You can email me if you don't want to pollute this thread.

**Comment by webron** [comment]
@quilicicf - should we use the email in your profile?

**Comment by quilicicf** [comment]
Yes please.

**Comment by webron** [comment]
@quilicicf - I'll get the description to you today.

**Comment by jfacorro** [comment]
+1

**Comment by iHateCode** [comment]
+1

**Comment by nakedpony** [comment]
+1

**Comment by mohsen1** [comment]
This is duplicate of https://github.com/swagger-api/swagger-ui/issues/764
