### ISSUE TITLE
The "Authorization" basic auth header is not sent when the target operation has the "security" field set

### ISSUE THREAD

**Issue by kcq** [swagger-api/swagger-ui#799]
This happens when the target operation references a basic auth scheme declared in the "securityDefinitions" section.

**Comment by fehguy** [comment]
I can't reproduce this, but will keep it open and look more in M2

**Comment by mohsen1** [comment]
This is a basic swagger with working backend to reproduce this issue:

https://gist.githubusercontent.com/mohsen1/3498d865c1d5ebb9f50f/raw/1629039c99ef34dea06c67fb5c0023ba393484a0/swagger.json

**Comment by fehguy** [comment]
I've confirmed that swagger-ui is working fine, simply supply authorizations like such:

window.authorizations.add("basicAuth", new PasswordAuthorization("basicAuth", "user", "pass"))

![image](https://cloud.githubusercontent.com/assets/249413/6475524/2507288e-c1c0-11e4-8777-04a36d186668.png)

**Comment by fehguy** [comment]
please reopen if you still see an issue.
