### ISSUE TITLE
Response Body as Array of Primitives

### ISSUE THREAD

**Issue by heme** [swagger-api/swagger-ui#800]
**Issue:** Swagger UI is displaying the response body incorrectly
**I Expect** it to display the array of strings that definition describes
**Instead** it displays my definition object as the response body

**Disclaimer:** I am making an assumption here that swagger definition objects correlate to json-schema definitions. That may be the source of my issue here.

 **Background:** The response body contains an array of the IDs of steps that are part of instructions, and the order of those IDs describe their sequence. [More at Google Groups](https://groups.google.com/forum/#!msg/swagger-swaggersocket/PFG21prP7Sg/MePG08TLHtkJ)

##### My Definition
```JSON
"InstructionSequence": {
    "title": "InstructionSequence",
    "description": "The sequence of steps that make up the Instructions",
    "type": "array",
    "items": {
        "type": "string"
    }
}
```

##### Path & Response
```JavaScript
"/instructions/{ID}/sequence": {
    "get": {
//...
        "responses": {
            "200": {
                "description": "Instruction's Sequence",
                "schema": {
                    "$ref": "InstructionSequence",
                    "example": [
                        "stepID",
                        "stepID",
                        "stepID"
                    ]
                }
            }
        }
    }
}
```

##### Swagger UI
![screen shot 2014-12-29 at 11 04 47 am](https://cloud.githubusercontent.com/assets/587462/5570647/aafcd70c-8f4a-11e4-9486-8b88782d9cb4.png)

**Comment by simar15** [comment]
Is this fixed?
My Rest API returns array of array of strings without key values, how can that be modelled in swagger?

`[
"1459451302225",
"INFO",
"INFO\taudit\t20,225\tRequest GET
/rest/foo&skip=0&limit=25
exesults count: 10 (Status
200 OK) 135ms",
"admin"
] `

**Comment by webron** [comment]
It should be fixed, yes.
