### ISSUE TITLE
'help' is not a valid tag, breaks UI

### ISSUE THREAD

**Issue by stnever** [swagger-api/swagger-ui#802]
Hello, the sample Swagger 2.0 document at the end of this comment will cause this error (currently in Firefox 34.0.5) and not show the UI at all:

    TypeError: operationGroup.apis is undefined
      operationGroup.apis.push(operationObject);
      swagger-client.js (line 460, col 12)

Note that my `GET /help-articles` operation has a `help` tag. If I change that to `help2` everything works.

I'm using the /dist directory directly, my version is:
```
    // swagger-ui.js
    // version 2.1.0-alpha.7
```

This is the relevant portion of the swagger file.
```
{
 "swagger": "2.0",
 "info": {
  "title": "sample-api",
  "version": "1.10.2",
  "description": "A sample API."
 },
 "paths": {
  "/help-articles": {
   "get": {
    "tags": [
     "help"
    ],
    "responses": {
     "default": {
      "description": "Default response."
     }
    }
   }
  }
 }
}
```

**Comment by lenstr** [comment]
Hey guys, same issue for a tag `build`. Renaming `SwaggerClient.prototype.build` to `SwaggerClient.prototype.__build` will do the job, but is there another way to do so?

**Comment by fehguy** [comment]
I believe @whitlockjc is addressing this in swagger-js

**Comment by mohsen1** [comment]
This is an issue in SwaggerJS. 


https://github.com/swagger-api/swagger-js/issues/194

**Comment by zdila** [comment]
See #1061: It is caused for tag `info`. Client version is 2.1.8-M1.

**Comment by webron** [comment]
@zdila - please try the latest master.
