### ISSUE TITLE
Make direct URLs with urls.primaryName query param possible without QUERY_CONFIG_ENABLED 

### ISSUE THREAD

**Issue by gueuselambix** [swagger-api/swagger-ui#8039]
Because of https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx you have disabled QUERY_CONFIG_ENABLED by default, but this breaks direct links to specs when working with _urls_.

The topbar itself adds _"?urls.primaryName=<name>"_ to the address bar, but when you refresh the page you end up on the first spec.

Users are now forced to enable QUERY_CONFIG_ENABLED (which has security implications), just to allow those direct URLs.

So I think you either don't add that queryParam to the address bar (because it sets the wrong expectation), or you explicitly allow that _urls.primaryName_ without having to set QUERY_CONFIG_ENABLED to true

**Comment by cgockeln42** [comment]
I would also be very interested in a fix and solution for this. Introducing a security issue to use the direct links is not really worth the possible problems coming later. Therefore, like the previous speakers, I hope that a fix will come quickly.

**Comment by gueuselambix** [comment]
Any news on this?
