### ISSUE TITLE
externalDocs Object never shows up

### ISSUE THREAD

**Issue by zhoubinjason** [swagger-api/swagger-ui#805]
{
  2     "apiVersion": "1.0.0",
  3     "swagger": "2.0",
  4     "info": {
  5         "title": "ARChem API",
  6         "description": "ARChem RESTful API for Communication to the archem server",
  7         "version": "1.0.0"
  8     },
  9     "host": "192.168.146.14",
 10     "schemes": [
 11         "http",
 12         "https"
 13     ],
 14     "basePath": "/ARChem",
 15     "produces": [
 16         "application/json"
 17     ],
 18     "authorizations": {},
 19     "paths":{
 20        "/HelloWorld":{
 21             "get":{
 22                 "tags":[
 23                     "HelloWorld"
 24                 ],
 25                 "summary":"Just a example try",
 26                 "description":"",
 27                 "externalDocs" : {
 28                     "description" : "A test",
 29                     "url" : "http://www.google.ca"
 30                 },
 31                 "operationId":"Get a example working",
 32                 "consumes":[
 33                     "application/json",
 34                     "application/xml"
 35                 ],
 36                  "produces":[
 37                     "application/json",
 38                     "application/xml"
 39                 ],
 40                     "responses":{
 41                         "405":{
 42                             "description":"Invalid input"
 43                         }
 44                     }
 45             }
 46         }
}

Line 27 - 30 will not be interpreted. The externalDocs will not show up.

**Comment by fehguy** [comment]
Yes, this is not implemented in swagger-js or swagger-ui.

**Comment by fehguy** [comment]
combining to #608
