### ISSUE TITLE
Swagger-ui does not send code parameter to token endpoint for OIDC

### ISSUE THREAD

**Issue by skion** [swagger-api/swagger-ui#8065]
### Q&A

 - OS: Ubuntu 22.04
 - Browser: Firefox and Chromium
 - Version: 101.0.1 and 102.0.5005.115
 - Method of installation: FastAPI
 - Swagger-UI version: 4.1.2
 - Swagger/OpenAPI version: OpenAPI 3.0.2

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.2
info:
  title: Test API
  version: dev
paths:
  /hello/{name}:
    get:
      summary: Say Hello
      operationId: say_hello_hello__name__get
      parameters:
      - required: true
        schema:
          title: Name
          type: string
        name: name
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OpenIdConnect: []
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: stringa
        type:
          title: Error Type
          type: string
  securitySchemes:
    OpenIdConnect:
      type: openIdConnect
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
```

Swagger-UI configuration options:
```js
    SwaggerUIBundle({
        url: '/openapi.json',
    "dom_id": "#swagger-ui",
"layout": "BaseLayout",
"deepLinking": true,
"showExtensions": true,
"showCommonExtensions": true,
oauth2RedirectUrl: window.location.origin + '/docs/oauth2-redirect',
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
    })
```

### Describe the bug you're encountering

The UI seems to omit passing the authorization code into the token endpoint call, causing the UI to show:

    auth errorError: Bad Request, error: invalid_request, description: Missing required parameter: code

### To reproduce...

- Click Authorize
- Fill out `client_id` and `client_secret`
- Select scope `openid` in the `authorization_code` flow
- Press Authorize

### Expected behavior

I would expect the authorization code flow to successfully exchange the `code` for an `access_token` and `id_token`. 

### Screenshots

Request body to Google's token endpoint is like this:

    grant_type=authorization_code&client_id=CLIENT_ID&client_secret=CLIENT_SECRET&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fdocs%2Foauth2-redirect

which responds with

```json
{
  "error": "invalid_request",
  "error_description": "Missing required parameter: code"
}
```

![image](https://user-images.githubusercontent.com/532192/174476146-f7de6c2d-a617-4258-84c4-e9065655ffa9.png)

**Comment by MaxDXDX** [comment]
I have the same problem. @skion , did you solve it ?

**Comment by skion** [comment]
Nope, not yet...

**Comment by skion** [comment]
@MaxDXDX Actually it does work correctly now with the latest version for me, which appears to be `swagger-ui-dist@4.15.5`... I'm closing this issue.
