### ISSUE TITLE
Add Auth Tokens to local storage

### ISSUE THREAD

**Issue by Martincic** [swagger-api/swagger-ui#8076]
### Is your feature request related to a problem?
It is very frustrating to manually input the token every time I refresh the page. Every time an endpoint is changed, eg. path for an endpoint, I need to refresh, and then the Auth token dissapears. 

### Describe the solution you'd like
It would be super useful to have Auth token stored to localstorage and whenever it's set, automatically pull it on each request. Much better alternative then refreshing website each time a new change is added.

### Describe alternatives you've considered
If this is unwnated feature, there could be at least a flag or a button to enable/disable this feature, but I think it would be super useful.

**Comment by mathis-m** [comment]
This is already possible. Just use the [`persistAuthorization`](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#:~:text=persistAuthorization) option!
E.g. via query parameters: `https://url-to-ur-swagger.com?persistAuthorization=true`
