### ISSUE TITLE
Building swagger-ui on windows 7 does not work

### ISSUE THREAD

**Issue by brunoroussel** [swagger-api/swagger-ui#811]
Hello,
I'm trying to build a swagger-ui distribution on windows 7, but I have some issues with npm, cake and handlebars configuration.

I found a previous bug fix #68 but it doesn't work for me.

Has anyone already done that ?

Note: Ok, I've already created an issue about this, but I think like posting a new subject here is more appropriate.

I have a couple fixes and functionalities that I'd like to submit as pull resquests on swagger-ui but... first I need to compile swagger-ui from the source code. Until now, I've done all the work straight in javascript on the dist code... So, I back on the right track :)

step 1: npm run-script build

swagger-ui@0.1.14 build c:\workspace\swagger-ui
PATH=$PATH:./node_modules/.bin cake dist
but cake does not started.. nothing happens.
step 2 : I tried to run cake on command line : cake dist

Build distribution in ./dist
path.existsSync is now called fs.existsSync.
: Reading src/main/coffeescript/SwaggerUi.coffee
: Reading src/main/coffeescript/view/HeaderView.coffee
: Reading src/main/coffeescript/view/MainView.coffee
: Reading src/main/coffeescript/view/ResourceView.coffee
: Reading src/main/coffeescript/view/OperationView.coffee
: Reading src/main/coffeescript/view/StatusCodeView.coffee
: Reading src/main/coffeescript/view/ParameterView.coffee
: Reading src/main/coffeescript/view/SignatureView.coffee
: Reading src/main/coffeescript/view/ContentTypeView.coffee
: Precompiling templates...
: Compiling src/main/template/content_type.handlebars
: Compiling src/main/template/main.handlebars
: Compiling src/main/template/operation.handlebars
: Compiling src/main/template/param.handlebars
: Compiling src/main/template/param_list.handlebars
: Compiling src/main/template/param_readonly.handlebars
: Compiling src/main/template/param_readonly_required.handlebars
: Compiling src/main/template/param_required.handlebars
: Compiling src/main/template/resource.handlebars
: Compiling src/main/template/signature.handlebars
: Compiling src/main/template/status_code.handlebars

c:\workspace\pfmediation\pfs\pfs-tools\swagger-ui\swagger-ui-master\swagger-ui\Cakefile:56
throw err;
^
Error: Command failed:
at ChildProcess.exithandler (child_process.js:637:15)
at ChildProcess.EventEmitter.emit (events.js:98:17)
at maybeClose (child_process.js:735:16)
at Process.ChildProcess.handle.onexit (childprocess.js:802:5)

handlebars templates are not generated. exec command does not work properly.

step3 : I found a previous issue that seems to be related :

#68

I tried to install handlebars and cake as global node modules
still the same errors...

step5 : I tried to generate the handlebars template on command line.

ok this work, the template is correctly generated.

so I don't understand why the exec command is not working, it seems that launching handlebars from cakefile does not work on windows 7...

finally
I'm kind of stuck in the middle of the build...

Thanks for your help all.

Best Regards
Bruno

**Comment by smbecker** [comment]
I was able to build successfully on my Windows machine by manually manipulating my path to include ./node_modules/.bin and the [GOW utilities](https://github.com/bmatzelle/gow). Then you can run `cake dist` from the command line.

**Comment by martoe** [comment]
I needed to patch the cakefile to make it work on Windows: https://github.com/martoe/swagger-ui/commit/9fe0737ca68ead6c5b0aa61e82ea51f0036f3882 (havent pull-requested it because I guess it won't work on *ix systems now)

The other gotcha is that you must git-clone with `core.autocrlf=false`, otherwise you end up with lots of `\r` chars in the output files...

**Comment by fehguy** [comment]
now that gulp has been added in develop_2.0, the cakefile and windows issues should be resolved.  please reopen if you see otherwise.

**Comment by cblaze22** [comment]
How did you fix this? What are exact steps?

**Comment by fehguy** [comment]
```
npm install -g gulp
npm install
gulp
```

**Comment by mohsen1** [comment]
or `npm run build`

**Comment by cblaze22** [comment]
Nothing happens in my dist folder after I execute those.

`
F:\Test\Swagger\Websites\swagger-ui>npm run build

> swagger-ui@2.1.0-alpha.7 build F:\Test\Swagger\Websites\swagger-ui
> PATH=$PATH:./node_modules/.bin cake dist
`

**Comment by mohsen1** [comment]
You shouldn't use `npm run` scripts in Windows. Please follow @fehguy's instructions and make sure you have Node.js installed and also you have the latest.

**Comment by cblaze22** [comment]
I did do his, but I dont have a GULP file.  I am using 2.7 of Swagger, does it only work with the newest build?

**Comment by webron** [comment]
There's no 2.7 of Swagger...

**Comment by cblaze22** [comment]
Sorry, that is RestExpress. 2.1.0-alpha.7 is what I have for the UI project.

**Comment by webron** [comment]
I'd suggest pulling from master as it includes quite a few fixes for issues in 2.1.0-alpha.7. If you still have an issue with that, please let us know.

**Comment by cblaze22** [comment]
Yep latest worked with gulp, thanks guys.

**Comment by webron** [comment]
:+1:

**Comment by vsix27** [comment]
windows 7/64 bit, swagger ui was built but able to process only file from your server  http://petstore.swagger.io/v2/swagger.json
it does not take local json file - neither from swagger-ui/dist directory, placed as ../m.json,
error: Please specify the protocol for file:///C:/a_work/Carnegie/swagger-ui/dist/index.html/../m.json

nor from local website
error: Can't read from server. It may not have the appropriate access-control-origin settings.

tried to launche Crome with option --allow-file-access-from-files or -allow-file-access-from-files - it is not working anymore...

any idea how to use swagger ui for local json file in windows??
that file is legit - i can see it in swagger editor
