### ISSUE TITLE
Updating 4.13.0 -> 4.13.1 causes "Module not found: Error: Can't resolve 'util'" when building

### ISSUE THREAD

**Issue by AuroraLS3** [swagger-api/swagger-ui#8136]
### Q&A (please complete the following information)
 - OS: ubuntu (Github actions)
 - Browser: none
 - Version: -
 - Method of installation: npm (yarn)
 - Swagger-UI version: 4.13.1
 - Swagger/OpenAPI version: -

### Content & configuration

Swagger-UI configuration options:
```js
        SwaggerUI({
            dom_id: "#swagger-ui",
            url: baseAddress + "/docs/swagger.json"
        });
```

### Describe the bug you're encountering

Build is failing if swagger is updated by dependabot https://github.com/plan-player-analytics/Plan/pull/2527 (builds using 4.13.0 successful)
```
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'util' in '/home/runner/work/Plan/Plan/Plan/react/dashboard/node_modules/swagger-ui/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

error Command failed with exit code 1.
```

### To reproduce...

Steps to reproduce the behavior: (speculative)
1. Create a react app
2. Add swagger 4.13.1 as dependency
3. Build

### Expected behavior

No errors during npm build

### Additional context or thoughts

- I'm unsure if react app builds with older version of webpack, or if the version 4.13.1 changed webpack version to be higher
- https://github.com/plan-player-analytics/Plan/pull/2527

**Comment by char0n** [comment]
Additional problem with 4.13.1 is that logical nullish assignment (??=) is no longer transformed by babel which disqualifies testing SwaggerUI in Node.js@14.

**Comment by char0n** [comment]
Fixes provided in https://github.com/swagger-api/swagger-ui/pull/8137

**Comment by char0n** [comment]
Regression with `util` fixed by not installing `util` in our dependency tree
---
Regression with logical nullish assignment fixed by always using transformation provided by `@babel/plugin-proposal-logical-assignment-operators` as part of running babel preset env tranformations.

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v4.13.2

**Comment by AuroraLS3** [comment]
Thank you for the quick fix - I'll report back tomorrow when dependabot updates again.

**Comment by char0n** [comment]
@AuroraLS3 your CI is green on 4.13.2 - https://github.com/plan-player-analytics/Plan/pull/2529

**Comment by AuroraLS3** [comment]
Yep indeed it is, thanks!
