### ISSUE TITLE
Email address parameter in query hits wrong host. Needs url encoding

### ISSUE THREAD

**Issue by ruhley** [swagger-api/swagger-ui#814]
Putting an email address in a query parameter field hits the host of the email address. To fix this I had to encode the components. I put my hack at the start of parseUri, but it should probably go somewhere else.
```javascript
function parseUri (str) {
  str = str.replace(/\?(.*)/gi, function($0, $1) {
    var parts = $1.split('='),
      hasQuestion = $0.indexOf('?') === 0,
      encoded = encodeURIComponent(parts[0]) + '=' + encodeURIComponent(parts[1]);

    if (hasQuestion) {
      encoded = '?' + encoded;
    }
    return encoded;
  });
```

**Comment by fehguy** [comment]
Please update your swagger.js to 2.0.48 or later, verified working in https://github.com/swagger-api/swagger-js/commit/7ab00749ac93b4119ba28017a2a4ff33b91cfee3

**Comment by skddc** [comment]
> Please update your swagger.js to 2.0.48 or later, verified working in swagger-api/swagger-js@7ab0074

I'm using 2.0.48 and still have this problem in swagger-ui. The release notes don't mention this fix: https://github.com/swagger-api/swagger-js/releases/tag/v2.0.48

**Comment by webron** [comment]
I'll have to leave it to @fehguy.

**Comment by fehguy** [comment]
OK I believe the issue here is that you're using swagger-client.js, which supports swagger-spec 2.0.  This is a different library and still has the bug.

**Comment by mooyoul** [comment]
+1 this issue.
