### ISSUE TITLE
Double slash in the URL when basePath ends with '/' and resource API path starts with '/'

### ISSUE THREAD

**Issue by bajtos** [swagger-api/swagger-ui#819]
See https://github.com/swagger-api/swagger-js/issues/116, the GUI has the same problem as the code-generator.

When the `basePath` ends with a slash, and the API resource `path` starts with a slash, a URL with a double slash is produced.

```js
// GET /explorer/resources/products

{ 
  apiVersion: '1.6.3',
  swaggerVersion: '1.2',
  basePath: 'http://127.0.0.1:62232/',
  resourcePath: '/resources',
  apis: [ { path: '/products', operations: { /* ... */ } },
  // etc.
}

// produces URL http://127.0.0.1:62232//products
```

The workaround is to remove the trailing slash from `baseUrl` (see e.g. strongloop/loopback-explorer#84)

**Comment by webron** [comment]
@bajtos - to be clear, you're talking about 1.2 specs only, right?

**Comment by fehguy** [comment]
this is a swagger-js issue, see here:

https://github.com/swagger-api/swagger-js/issues/202

**Comment by fehguy** [comment]
please update to 2.0.48 of swagger-js

**Comment by bajtos** [comment]
Yes, I am talking about 1.2 spec and `swagger-ui@2.0.24`. There is no swagger-js in my dependency tree.

**Comment by bajtos** [comment]
Screenshot:

![screenshot](http://content.screencast.com/users/RandMck/folders/Jing/media/03dfef33-3110-43fa-a0ea-73e17ffcb63b/00000146.png)

**Comment by fehguy** [comment]
hmm.  If strongloop is bundling swagger-js into swagger-ui, then you'll have to get them to rebuild the bundle with swagger-js 2.0.48.  If you open your browser debug window, you should be able to tell.

**Comment by bajtos** [comment]
Here is the source code in question: 

 - module: https://github.com/strongloop/loopback-explorer

 - some extra stuff added on top of swagger-ui: https://github.com/strongloop/loopback-explorer/tree/master/public

 - [package-json](https://github.com/strongloop/loopback-explorer/blob/master/package.json) has only swagger-ui dependency, no swagger-js:

  ```json
  {
  "dependencies": {
    "cors": "^2.4.2",
    "debug": "~1.0.3",
    "express": "3.x",
    "lodash": "^2.4.1",
    "swagger-ui": "~2.0.18"
  }
  }
  ```

I am one of the developers of loopback-explorer. Perhaps I am missing some link here? How is swagger-js related to swagger-ui 2.0.18?

Here is the list of all scripts loaded in the browser as shown in DevTools:

```
hint.js
shred.bundle.js
jquery-1.8.0.min.js
jquery.slideto.min.js
jquery.wiggle.min.js
jquery.ba-bbq.min.js
handlebars-1.0.0.js
underscore-min.js
backbone-min.js
swagger.js
swagger-ui.js
highlight.7.3.pack.js
swagger-oauth.js
loadSwaggerUI.js
jquery-1.9.1.js
indicator.js
postmessage.js
tpc-check-add-cookie.js
```

The file swagger.js contains the following header:

```
// swagger.js
// version 2.0.39
```

I have upgraded swagger-ui to 2.0.24 (the latest version from npmjs.org), the swagger-js file is still `swagger.js version 2.0.39`

**Comment by fehguy** [comment]
copy in swagger-js 2.0.48 (https://raw.githubusercontent.com/swagger-api/swagger-js/master/lib/swagger.js) and test it out.  I can push a new version of swagger-ui to npmjs.org, although we have been more focused on the 2.1.0.alpha-x releases

**Comment by bajtos** [comment]
Thanks, I'll give it a try next week.

**Comment by bajtos** [comment]
> copy in swagger-js 2.0.48 and test it out.

I tried it out, the problem is not fixed in 2.0.48.

If I understand the implementation in swagger-js correctly, the code handling double-slash in the URL is inside the method `this.getAbsoluteBasePath`, which is unfortunately not invoked when the basePath is already a full URL. See [swagger.js#L451](https://github.com/swagger-api/swagger-js/blob/1f8984acebe76d055d5304420a5dfe38f9af4556/lib/swagger.js#L451):

```js
this.basePath = response.basePath.indexOf('http') === -1 ? 
  this.getAbsoluteBasePath(response.basePath) : 
  response.basePath;
```

Later, when the user clicks on the "Try it out!" button, the method `urlify` performs a simple concatenation to build the URL and thus a double-slash is produced. see [swagger.js#988](https://github.com/swagger-api/swagger-js/blob/1f8984acebe76d055d5304420a5dfe38f9af4556/lib/swagger.js#L988):

```js
var url = this.resource.basePath + this.pathJson();
// url = "http://localhost:3000/" + "/products" 
```

**Comment by fehguy** [comment]
fixed in develop_2.0

**Comment by bajtos** [comment]
Thank you. Any ETA on when this may get released to npmjs.org?

**Comment by fehguy** [comment]
You should see 2.1.0-M1 released tomorrow (fingers crossed)

**Comment by trungtin** [comment]
Well, now the problem rise up again, I'm building from latest source (master branch) and have this error as well

**Comment by MateuszKubuszok** [comment]
@trungtin: I think we need to open new bug for it...
