### ISSUE TITLE
swagger-ui doesn't use resourcePath in "Try it out!" call

### ISSUE THREAD

**Issue by mbde** [swagger-api/swagger-ui#821]
Hi,
 I ran in to a possible bug.
In the raw output of my endpoint the `resourcePath` is correctly displayed
When I click "Try it out!" `basePath + path` are used in the call : `http://localhost:8080/rest/hello`

I thought `basePath + resourcePath + path` would be used : `http://localhost:8080/rest/string/static/hello`.

I made an [example app to illustrate the issue]( /mbde/swagger-example) it uses : 
 * jersey 1.18.2 
 * spring 3.2.9 
 * swagger-jersey-jaxrs_2.10 1.3.12
 * swagger-ui 2.0.24 from org.webjars

Output of raw : 
````json
{
  "apiVersion": "0.1",
  "swaggerVersion": "1.2",
  "basePath": "http://localhost:8080/rest",
  "resourcePath": "/string/static",
  "apis": [
    {
      "path": "/{string}",
      "operations": [
        {
          "method": "GET",
          "summary": "identity function",
          "notes": "",
          "type": "string",
          "nickname": "getStatic",
          "parameters": [
            {
              "name": "string",
              "required": true,
              "type": "string",
              "paramType": "path",
              "allowMultiple": false
            }
          ]
        }
      ]
    },
    {
      "path": "/hello",
      "operations": [
        {
          "method": "GET",
          "summary": "hello world",
          "notes": "",
          "type": "string",
          "nickname": "getStaticHelloWorld",
          "parameters": []
        }
      ]
    }
  ]
}
 ````
Thanks for the good work :)

**Comment by fehguy** [comment]
Hi, resource path is really used just for the organization of docs:

```
# base path
http://my.server.com/api

# resource listing, serves up list of all available apis
http://my.server.com/api/api-docs

# api declaration, serves up a single api definition under the path `users`, which is the `resourcePath`
http://my.server.com/api/api-docs/users

# base path, where the `users` api is called, from `basePath` + `path` (in api declaration):
http://my.server.com/api/users
```

**Comment by mbde** [comment]
Hi,
 ok, so I was mistaken :(
It seems that a path which consists  of several `@Path`-Annotations in different classes is a problem.
Is there a possible way to work around it?
Or should each method have the complete path in its `@Path`-Annotation?

**Comment by fehguy** [comment]
OK looking at your example app, it looks like you have an issue with subresources.  There are some known tickets around this area but I have yet to have a concrete explanation of how they're expected to work with swagger.

**Comment by fehguy** [comment]
Moving this to swagger-core, which is where the issue lies.  Please add any info you might have to the ticket:

https://github.com/swagger-api/swagger-core/issues/394
