### ISSUE TITLE
Converge swagger-ui and swagger editor markup/css

### ISSUE THREAD

**Issue by fishermand46** [swagger-api/swagger-ui#822]
I use swagger editor and swagger-ui frequently, and I find it confusing switching between the two as the layouts are a bit different. I prefer the listing that swagger editor gives and would like to see it merged into the swagger-ui project so that one can host that nice format locally.

**Comment by mikemalloyapigee** [comment]
There is a discussion under way regarding how best to do this.  Nothing has been formally decided, but your idea is on track.  There are some considerations of how best to do something like this, and when.  Certainly, any change in this regard would be well discussed before being implemented.

**Comment by nrekretep** [comment]
+1

**Comment by fehguy** [comment]
I'm going to close this out.  It's not really the goal of the two projects to share code or implementation.  That may change in the future but it's not worth tracking for now.
