### ISSUE TITLE
Request for ValidatorBadge returns 404 Not Found

### ISSUE THREAD

**Issue by inmindtechnologies** [swagger-api/swagger-ui#8226]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Edge, Chrome
 - Method of installation: dist assets
 - Swagger-UI version: [v4.14.3](https://github.com/swagger-api/swagger-ui/releases/tag/v4.14.3)
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
swagger-ui-4.14.3\dist\index.html

### Describe the bug you're encountering
When using Swagger UI's code directly in HTML, the ValidatorBadge return an error. The request to validator.swagger.io returns 404 Not Found

### To reproduce...

1. Download [Source code](https://github.com/swagger-api/swagger-ui/archive/refs/tags/v4.14.3.zip)
2. Open swagger-ui-4.14.3\dist\index.html
3. Scroll at the bottom of the page

### Expected behavior
The request to validator is currently the following: https://validator.swagger.io/validator?url=https%3A%2F%2Fpetstore3.swagger.io%2Fapi%2Fv3%2Fopenapi.json

To fix the issue, there should be a "/" before the query string like: https://validator.swagger.io/validator/?url=https%3A%2F%2Fpetstore3.swagger.io%2Fapi%2Fv3%2Fopenapi.json

### Screenshots
![image](https://user-images.githubusercontent.com/89091132/195648230-815650bf-26d5-4926-8c58-827885952fd5.png)

**Comment by char0n** [comment]
@inmindtechnologies thanks for reporting this. We're working on it now.

**Comment by char0n** [comment]
@inmindtechnologies issue has been fixed now.
