### ISSUE TITLE
Enhance card in landing page

### ISSUE THREAD

**Issue by Shurtu-gal** [swagger-api/swagger-ui#8232]
### Content & configuration
 - Web Browser :   Google Chrome                                                                                     

### Is your feature request related to a problem?

The cards are not resetting to initial state on not being hovered.

### Describe the solution you'd like

Resetting of cards when they are not hovered on.
### Additional context

![Screenshot from 2022-10-15 09-15-06](https://user-images.githubusercontent.com/100484401/195969259-fc87d187-c0f7-49e3-8e48-c3b358fc4cef.png)

**Comment by Shurtu-gal** [comment]
Can I get Assigned to it?

**Comment by mnosov622** [comment]
Hi !

I would love to work on this issue. Could you assign it to me, please ?

**Comment by char0n** [comment]
Issue moved to [swagger-api/swagger.io #325](https://github.com/swagger-api/swagger.io/issues/325) via [**Zenhub**](https://www.zenhub.com/)
