### ISSUE TITLE
Swagger UI doesn't handle GFM

### ISSUE THREAD

**Issue by Vaseltior** [swagger-api/swagger-ui#825]
Swagger Spec 2.0 specify that description fields now accept GFM. But Swagger UI does not format it.

**Comment by webron** [comment]
Did you try the latest master, because #824 was merged a few hours ago.

**Comment by Vaseltior** [comment]
No I got the yesterday version

**Comment by webron** [comment]
Try pulling the master and check it again please.

**Comment by Vaseltior** [comment]
There is no lib/marked.js on the master branch...

**Comment by webron** [comment]
Right, my bad. Try the develop branch.

**Comment by Vaseltior** [comment]
ok

**Comment by bshamblen** [comment]
The reset.less file removes a lot of the formatting natively used by markdown. There were already several manual fixes for the .markdown class in the specs.less file, so I didn't add any additional formatting. I can add more if there are specific styles you'd like to have implemented.

**Comment by webron** [comment]
@Vaseltior - for future reference, editing a comment doesn't send a notification, and I was unaware of your input until @bshamblen added his comment. It's normally better to just add a new comment.

**Comment by Vaseltior** [comment]
Ok, I'll know that. Strong works, italic does not indeed since the `<em>` tag is reset.

**Comment by somethingShiny** [comment]
I am also on the develop branch and am having some issues with GFM. The only features I have been able to use properly are bold, links, and strikethrough. Swagger-editor shows more features including italics and tables working properly, but using them in my spec is not rendered as it should be on swagger ui,

**Comment by fehguy** [comment]
@somethingShiny will be looking into this shortly.

**Comment by somethingShiny** [comment]
Just some followup/clarification: After messing around, I've found that most features of GFM work fine in the description from the info for the spec. Where it does not work is the description for a method on any path.

**Comment by fehguy** [comment]
merged into develop_2.0

**Comment by duncanhall** [comment]
Just wanted to get clarification on exactly which MD syntax is supposedly now supported, as the develop_2.0 branch still seems to lack support for many features which are available in the swagger editor.

For example, headers, tables and italics seem don't seem to be working.

**Comment by fehguy** [comment]
@duncanhall let's get a complete list of places where GFM is not supported, where the spec says it is.  If you can list them all here, we can get them all implemented.  It'd be very helpful.

**Comment by somethingShiny** [comment]
Here's a basic sample spec listing what is supported and where that I've tried.
```json
{
  "swagger": "2.0",
  "info": {
    "title": "sampleSpec",
    "description": "Working: Bold, links, url-autolinking, strikethrough, tables, lists (unordered), syntax highlighting, multiple underscores within words not being parsed as italics, headings, inline code formatting.
      Not working: italics, numbered lists, "
  },
  "paths": {
    "/sample/path": {
      "description": "Working: Bold, strikethrough, links, url-autolinking"
    }
  }
}
```

I know this isn't complete as it doesn't test things like parameter or response descriptions but it's what I've been able to test so far. If I get a chance to test more areas I'll post another comment listing what is supported there.

**Comment by rob3c** [comment]
Hi,
I see this is closed, but response descriptions don't seem to support GFM in v2.1.1-M2 even though they're also mentioned in the spec:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#response-object

Cheers,
Robert

**Comment by mohsen1** [comment]
@rob3c Please open a new issue here for response descriptions

**Comment by rob3c** [comment]
@mohsen1 Ok, I made one for Response Object GFM support:
https://github.com/swagger-api/swagger-ui/issues/1233

and also one for Tag Object GFM support:
https://github.com/swagger-api/swagger-ui/issues/1234
