### ISSUE TITLE
Latest package not working with CommonJS

### ISSUE THREAD

**Issue by ankitchoudary** [swagger-api/swagger-ui#8311]
### Q&A (please complete the following information)
 - OS: Win 10 pro
 - Browser: chrome
 - Version: 108.0.5359.73
 - Method of installation: npm
 - Swagger-UI version: 4.15.5
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
 url: 'http://localhost:7071/api/swagger.json',
 dom_id: '#body'
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

I am getting following error while starting the nodejs server
'Cannot use import statement outside a module'
Stack: C:\Development\connect-supplier-link\Dev\ConnectSupplierLink\node_modules\react-syntax-highlighter\dist\esm\light.js:1   
import highlight from './highlight';
^^^^^^

### To reproduce...

Try to use SwaggerUI package with CommonJS

const SwaggerUI = require('swagger-ui');
SwaggerUI({
    url: 'http://localhost:7071/api/swagger.json',
    dom_id: '#body'
})

Getting following error on server startup:

'Cannot use import statement outside a module'
Stack: C:\Development\connect-supplier-link\Dev\ConnectSupplierLink\node_modules\react-syntax-highlighter\dist\esm\light.js:1   
import highlight from './highlight';
^^^^^^

### Expected behavior

I should be able to use SwaggerUI with CommonJS

**Comment by char0n** [comment]
Documentation for current SwaggerUI build fragments: https://github.com/swagger-api/swagger-ui/issues/7831

**Comment by char0n** [comment]
This issue have been addressed in https://github.com/swagger-api/swagger-ui/pull/9137.

Following exports field has been used:

```json
  "exports": {
    "./dist/swagger-ui.css": "./dist/swagger-ui.css",
    "./dist/oauth2-redirect.html": "./dist/oauth2-redirect.html",
    "./dist/swagger-ui-standalone-preset": "./dist/swagger-ui-standalone-preset.js",
    ".": {
      "browser": {
        "import": "./dist/swagger-ui-es-bundle-core.js",
        "require": "./dist/swagger-ui.js"
      },
      "node": {
        "import": "./dist/swagger-ui-bundle.js",
        "require": "./dist/swagger-ui-es-bundle.js"
      },
      "default": {
        "import": "./dist/swagger-ui-bundle.js",
        "require": "./dist/swagger-ui-es-bundle.js"
      }
    }
  }
```

---

Explanation:

1. When in Node.js environment and  `import SwaggerUI from 'swagger-ui'` is used, then `swagger-ui-bundle.js` is used. This is UMD build that does include production dependencies and exports SwaggerUIBundle symbol on global object.

2. When in Node.js environment and `const SwaggerUI = require('swagger-ui')` is used, then `swagger-ui-es-bundle.js` is used. This is `commonjs2` build that does include production dependencies.

3. When in Browser environment and  `import SwaggerUI from 'swagger-ui'` is used, then `swagger-ui-es-bundle-core.js` is used. This is true ESM bundle that doesn't include production dependencies.

4. When in Browser environment and  `const SwaggerUI = require('swagger-ui')` is used, then `swagger-ui.js` is used. This is UMD build that doesn't include production dependencies and exports SwaggerUICore symbol on global object.

**Comment by char0n** [comment]
Fixed by https://github.com/swagger-api/swagger-ui/pull/9137
