### ISSUE TITLE
Test framework

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#833]
This project needs a robust testing framework

**Comment by DinisCruz** [comment]
Are these the only tests that exist?

https://github.com/swagger-api/swagger-ui/tree/master/src/test

for reference here is the environment that I currently have in one of my dev projects:
 * https://github.com/TeamMentor/TM_4_0_Design/wiki/Running-QA-tests-from-WebStorm (setup instructions)
 * http://blog.diniscruz.com/2015/01/achieving-98-code-coverage-by-running.html (video of the tests running)

**Comment by fehguy** [comment]
Yes, that's it.  I was thinking about getting Selenium to run on travis-ci for better coverage.

**Comment by mohsen1** [comment]
https://github.com/swagger-api/swagger-ui/pull/864 will add e2e tests and travis integration

**Comment by fehguy** [comment]
added in https://github.com/swagger-api/swagger-ui/commit/f3b856c1df896eef0d99a39ccc79fd45c2eb2a71
