### ISSUE TITLE
Named regex parameter substitution fails

### ISSUE THREAD

**Issue by tagliola** [swagger-api/swagger-ui#835]
We are using named parameters with a regex pattern, and the substitution fails.

In attached example, the parameters are defined as:
`GET /{year:[\d]{4}}-{month:[\d]{2}}-{day:[\d]{2}}`
when filling in the parameters, this results in the following URL:
`https://localhost:10891/2014}-01}-01}`
with one superfluous curly bracket still there.

This is with swagger-ui 2.0.24 and swagger 1.3.5.

**Comment by tagliola** [comment]
![parametersubstitution](https://cloud.githubusercontent.com/assets/1526633/5799084/7d57159e-9fce-11e4-969e-2a3fe9b4b8bc.png)

**Comment by webron** [comment]
Swagger does not support such a declaration for path templates. Each part that's surrounded with curly braces is considered a parameter, and the regex within it is irrelevant.

Swagger 2.0 supports the `pattern` property which allows you to limit the value to a certain regex, but it is not yet implemented in the UI. There's going to be a PR soon (community contribution) that will display the required pattern, but the PR to allow validation of it will take a bit longer.

**Comment by tagliola** [comment]
Validation is not needed here, the server will do that. The issue is with constructing the URL, it trips over the nested pair of curly brackets. I did see #831, is that the PR you are referencing and would that fix the construction of the URL?

**Comment by webron** [comment]
No, it's not related to #831. The problem with constructing the URL is that your spec is invalid. Your path can't be defined as `/{year:[\d]{4}}-{month:[\d]{2}}-{day:[\d]{2}}`, it has to be defined as `/{year}-{month}-{day}`

**Comment by tagliola** [comment]
Is it invalid for swagger-ui, as it's valid spec for the runtime.

We're using RestEasy, which has regular expression support in the @Path (see [their docs](http://docs.jboss.org/resteasy/docs/1.1.GA/userguide/html/Using__Path_and__GET___POST__etc..html)). It's also mentioned in the [JAX-RS 1.0 specs](https://wikis.oracle.com/display/Jersey/Overview+of+JAX-RS+1.0+Features).

For now, we can remove the regex so at least the swagger integration doesn't break as that's confusing for the user, but it seems like a valid feature of the @Path parameter.

At least, thanks for the quick response!

**Comment by webron** [comment]
It is invalid for the spec. Just because JAX-RS allows it, doesn't mean Swagger allows it. 

At the moment, we do not allow specifying regex as part of the template itself, but as said, in Swagger 2.0 you can specify the regex as part of the parameter *definition*.

What you're describing is a possible bug with swagger-core as it should replace the regex with the path parameter definition (not necessarily an easy match and switch). Feel free to open an issue on swagger-core about it.

**Comment by fehguy** [comment]
Ron is right, please see https://github.com/swagger-api/swagger-js/commit/ac50be8a34be24a818efe8506957aff322c78f41 for an example of how you'd do this with the swagger path param construct.

**Comment by chriskessel** [comment]
Necro on this I guess. Swagger-ui doesn't understand the regex, but having the regex in place is required for my app since it handles a lot of 404 cases where the user boffs the input parameter. We're using Java.

So, I'm a bit stuck. We use Swagger. We use Java. And we use the regex. What's the workaround to generate json that's valid for the UI? Some sort of custom annotation parser? Fork and modify code to try and look for regex and strip it when generating the swagger.json?

**Comment by webron** [comment]
@chriskessel - your issue isn't really clear. It's not that the isn't support for regex, it just comes in a different way. Where does it fail you?

**Comment by chriskessel** [comment]
Sorry, I guess it's not the UI specifically. It's in the generated swagger spec from the swagger-jaxrs, which is then used in the GUI. For example, it takes this complicated regex which should result in a single itemId parameter and instead thinks it's a long path:

    @Path("/{itemId: [0-9]{4}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{3}/[A-Za-z0-9]+}")

    "/api/{itemId}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{3}/[A-Za-z0-9]+}": { "get": { ...

So, the UI ends up showing an incorrect endpoint description. It should either be /"api/{itemId}" (perhaps with the regex info), but instead comes across  as a long path definition of /api/{itemId}/a/bunch/of/path/items/that/are/really/itemid/regex.

Hopefully that makes sense. Poking around in the code, I think it's an assumption that the first close brace it finds closes the parameter opening brace, but that's not true when the regex is there:
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L262

**Comment by webron** [comment]
@chriskessel - yup, it does make sense... but that would require an issue on [swagger-core](https://github.com/swagger-api/swagger-core). Mind opening a ticket there?

**Comment by chriskessel** [comment]
Will do.
