### ISSUE TITLE
Swagger fails to create proper request ui when hosted NOT under root directory

### ISSUE THREAD

**Issue by cppexpert** [swagger-api/swagger-ui#836]
Hi guys,

Here is input information

1) I'm using Swagger for Spray (https://github.com/gettyimages/spray-swagger)
2) Servlet root for my service is `/api` (and that's causes problems I think)
3) Here is how I initialize Swagger servlet
```scala
  val swaggerService = new SwaggerHttpService {
    override def apiTypes = Seq(typeOf[AuthenticateSwagger])
    override def apiVersion = "2.0"
    override def baseUrl = "/api" // let swagger-ui determine the host and port
    override def docsPath = "api-docs" // This path is ignored by swagger-ui. There is hardcoded one in index.html
    override def actorRefFactory = context
    override def apiInfo = Some(new ApiInfo("My API", "Documentation on RESTful JSON-based My API", null, null, null, null))
```

Therefore Swagger json is located at `/api/api-docs` and Swagger UI at `/api/swagger/`

Now when I attempt to make request using UI it fails because Swagger-UI calls

`/api/api/authenticate`

for the sake of experiment I changed value in `baseUrl` which shockingly made requests look like

`/api2/authenticate`

I'm not familiar with JavaScript but why would Swagger behave like that ? I couldn't find such comparison in the code (something like where it compares portions of URI).

Thanks.

**Comment by webron** [comment]
As far as I know, spray-swagger uses Swagger 1.2, and Swagger 1.2 simply does not support relative URLs for the `baseUrl` property. You have to use the full path if you want it to work properly.

**Comment by cppexpert** [comment]
What version exactly would you recommend to uses ? spray-swagger uses 1.3.

Also on maven I see only this
http://mvnrepository.com/artifact/com.wordnik/swagger-core_2.11/1.3.12

**Comment by webron** [comment]
1.3 is the version of swagger-core. I know it's a bit confusing.

swagger-core 1.3 produces Swagger 1.2 docs.
swagger-core 1.5 (which is currently under development and there's no stable version yet) produces Swagger 2.0 docs, and I'm not sure spray-swagger can use that. In fact, as far as I know, spray-swagger build its own docs and uses only the annotations from swagger-core. If you want to check about its ability to produce 2.0 spec, I'd suggest opening an issue on their repository.

**Comment by fehguy** [comment]
Hi please reopen if still an issue.
