### ISSUE TITLE
Weird display of entrypoints on Edge since last version

### ISSUE THREAD

**Issue by leolivier** [swagger-api/swagger-ui#8397]
### Q&A (please complete the following information)
 - OS: Windows 10 for browsing, swagger-ui installed on RHEL 7.9
 - Browser: Edge
 - Version: 109.0.1518.61
 - Method of installation: dist assets
 - Swagger-UI version: 4.15.5
 - Swagger/OpenAPI version: all

### Content & configuration

[screenshot](https://www.zupimages.net/viewer.php?id=23/07/ilm8.png )

Example Swagger/OpenAPI definition:
Pet store sample but same issue for all yaml files, whatever swagger or openapi and version

Swagger-UI configuration options:
```js
        const ui = SwaggerUIBundle({
          urls: urls,
          dom_id: '#swagger-ui',
          deepLinking: true,
          presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIStandalonePreset
          ],
          plugins: [
            SwaggerUIBundle.plugins.DownloadUrl
          ],
          layout: "StandaloneLayout"
        })
```

```
?urls.primaryName=test
```

### Describe the bug you're encountering
The entrypoint names are displayed vertically in Edge!
It works ok on Firefox and Chrome

### To reproduce...
Just open any yaml file in Edge and scrolldown to the first entrypoints

pets
GET
[
/
p
e
t
s
]
List all pets

### Expected behavior
Should be displayed as 
pets
GET
[/pets]
List all pets
### Screenshots
[screenshot](https://www.zupimages.net/viewer.php?id=23/07/ilm8.png)

**Comment by tammynewbie** [comment]
So confused. I need to have it as if it was written for a 1st grader. This all seems so foreign to me.

**Comment by leolivier** [comment]
looks like it's now working again (maybe a new version of edge installed?)
