### ISSUE TITLE
Special operation nicknames put swagger out of order

### ISSUE THREAD

**Issue by cmeresse** [swagger-api/swagger-ui#840]
If you use some "reserved words" for operation nicknames, swagger is completely lost.
Try for instance to set "nickname":"name"

This is due to the SwaggerOperation function in swagger.js.
At line 805, SwaggerOperation stores a function in this.resource[this.nickname]:

```javascript
this.resource[this.nickname] = function(args, callback, error) {
    return _this["do"](args, callback, error);
};
```
The problem is that this.resource has some particular properties yet (id, name, description, basePath, etc...) so they are overwritten and this can lead to very odd behaviors of swagger.

**Comment by fehguy** [comment]
I've opened an issue on swagger-js and referenced this.

**Comment by fehguy** [comment]
will confirm in m1 and close when verified.

**Comment by fehguy** [comment]
this is related to https://github.com/swagger-api/swagger-js/issues/209 and will be looked at in m2

**Comment by mohsen1** [comment]
This is duplicate of https://github.com/swagger-api/swagger-ui/issues/802

Please follow this issue here https://github.com/swagger-api/swagger-js/issues/194

**Comment by whitlockjc** [comment]
This should be fixed in the latest `develop_2.0` build of `swagger-js`.
