### ISSUE TITLE
Docker nginx config only binds to ipv4 not ipv6

### ISSUE THREAD

**Issue by Southclaws** [swagger-api/swagger-ui#8437]
https://github.com/swagger-api/swagger-ui/blob/f606c77ebfcc55964f4bf6e822b6621aea2b2ef4/docker/nginx.conf#L32

I ran into a networking issue when deploying to Fly.io and it turns out the cause was the nginx instance serving Swagger-UI wasn't binding to all ipv6 interfaces, only ipv4.

https://community.fly.io/t/private-networking-internal-domain-not-working-for-one-service/11096/7

It seems the solution is to simply add another `listen` directive:

```nginx
listen 8080;
listen [::]:8080;
```

I can open a PR for this if needed. I need to fork the repo anyway in order to get Swagger-UI working in our Fly.io internal VPN.

**Comment by char0n** [comment]
In the light of https://github.com/swagger-api/swagger-ui/issues/8447, I've issued https://github.com/swagger-api/swagger-ui/pull/8449. The change that we've introduced in https://github.com/swagger-api/swagger-ui/pull/8438 is backward incompatible.

The PR https://github.com/swagger-api/swagger-ui/pull/8449 makes the change backward compatible by disabling `listen` directory for IPv6 by default and with possibility to turn it on with `PORT_IPV6` env variable.

Example usage:

`set PORT_IPV6=8088`

This will add following line to nginx config:

```
listen            [::]:8088;
```
