### ISSUE TITLE
Building from master results in older /dist content than is committed in /dist?

### ISSUE THREAD

**Issue by skddc** [swagger-api/swagger-ui#844]
I cloned this repo and ran the build script, and the most obscure thing happened: the generated content in /dist looks *older* than what's committed in the repo there. The version number is one patch level below and the code doesn't match.

**Comment by fehguy** [comment]
which version number and in which file?

**Comment by skddc** [comment]
`dist/lib/swagger.js` is generated with `2.0.47` but committed with `2.0.48`, and termsOfServiceUrl turned into termsOfService in `/dist/swagger-ui.js`.

**Comment by fehguy** [comment]
This should be fixed now.
