### ISSUE TITLE
swagger-ui-bundle.js Does not appear to be updated with OAS3.1 support

### ISSUE THREAD

**Issue by davidpryor** [swagger-api/swagger-ui#8441]
### Q&A (please complete the following information)
 - OS: N/A
 - Browser: N/A
 - Version: N/A
 - Method of installation: N/A
 - Swagger-UI version: [4.17
 - Swagger/OpenAPI version: OpenAPI 3.1

### Describe the bug you're encountering
The current swagger-ui-bundle.js file does not seem to have support for OpenAPI3.1 in the 4.17 release 
`https://github.com/swagger-api/swagger-ui/blob/v4.17.0/dist/swagger-ui-bundle.js`

It does appear the isOpenAPI31 function is in the `https://github.com/swagger-api/swagger-ui/blob/v4.17.0/dist/swagger-ui-bundle.js.map` file but not `https://github.com/swagger-api/swagger-ui/blob/v4.17.0/dist/swagger-ui-bundle.js`

I have also checked 4.17 coming from multiple CDNs and they also seem to be serving pre-oas3.1 support js files.

### To reproduce...

Attempt to render a openapi 3.1 spec using the v4.17 js bundle

1. Load an editor, webpage utilizing the 4.17 js bundle
    The online editor seems to be using the 4.17 bundle:
    https://editor.swagger.io/
2. If using https://editor.swagger.io/, update the "openapi" version key to 3.1.0.

### Expected behavior
`https://github.com/swagger-api/swagger-ui/blob/v4.17.0/dist/swagger-ui-bundle.js` should be serving the code with support for OAS3.1

### Screenshots
![image](https://user-images.githubusercontent.com/79552751/222791046-ebb2ff54-6eab-436d-9166-6da0c446df60.png)
![image](https://user-images.githubusercontent.com/79552751/222792046-3401de22-b2fa-4428-9ee6-b737da7113d4.png)
![image](https://user-images.githubusercontent.com/79552751/222792207-be8fe69a-a4bc-45f5-a5ad-654e0377e117.png)
![image](https://user-images.githubusercontent.com/79552751/222792304-c81dda9d-f96e-4dae-9ac8-ab1ec77d9924.png)

**Comment by char0n** [comment]
Hi @davidpryor,

SwaggerUI@4.17.0 doesn't have support for OpenAPI 3.1.0 rendering. The purpose of SwaggerUI@4.17.0 was to integrate with swagger-client@3.19.0-beta.* which brings support for processing OpenAPI 3.1.0 definition and provide it to SwaggerUI. Given I've seen no issues reported for this release, it means that integration was successful and fully backward compatible.

OpenAPI 3.1.0 rendering support will be introduced via SwaggerUI@5.x.y channel by commencing work on these two following issues:

 - https://github.com/swagger-api/swagger-ui/issues/8402
 - https://github.com/swagger-api/swagger-ui/issues/8403

After that, bunch of other issues will be created, dealing with various OpenAPI 3.1.0 features rendering.

Hope this answers your question.
