### ISSUE TITLE
When using email as query param, the request URL is destroyed

### ISSUE THREAD

**Issue by skddc** [swagger-api/swagger-ui#845]
I have an email query param, but apparently the `@` is handled poorly, so when sending a request, the URL is just the hostname of the email address instead of the actual API URL.

**Comment by webron** [comment]
Have you seen #814?

**Comment by skddc** [comment]
Ah, thanks. Haven't seen it.

Then again, when I build from master, I run into #844.

**Comment by webron** [comment]
Yeah, sorry about #844, but for now, if you can replace the libs manually it should work.
