### ISSUE TITLE
Template generated from JSON schema does not contain nested fields

### ISSUE THREAD

**Issue by cipresso** [swagger-api/swagger-ui#847]
Hello.  
swagger-ui seems to have an issue generating templates for JSON schemas that have nested fields. The following snippets show the reference to the JSON schema and the schema itself. The capture at the bottom shows the template generated by swagger-ui.  I'm using version 2.1.0-alpha.7. Thank you.

![image](https://cloud.githubusercontent.com/assets/10523271/5848871/5685396c-a192-11e4-972c-da6e072f0542.png)

![image](https://cloud.githubusercontent.com/assets/10523271/5848876/6cd0f026-a192-11e4-9fde-716df5b95cc3.png)

![image](https://cloud.githubusercontent.com/assets/10523271/5848848/16cc5dd2-a192-11e4-9241-070abbf21ff1.png)

**Comment by webron** [comment]
For testing purposes, can you extract the `INPUT_MSG` object to a separate definition and use a `$ref` to it from the field?

**Comment by cipresso** [comment]
Thanks for replying.  Breaking out `INPUT_MSG` into a separate definition and using a `$ref` gives the result I was hoping for :).  Is this a bug or something I'm doing wrong?

![snap1](https://cloud.githubusercontent.com/assets/10523271/5865732/61383cf2-a240-11e4-9a46-1c3fd9b0c58a.jpg)

![snap2](https://cloud.githubusercontent.com/assets/10523271/5865665/dff9eb9a-a23f-11e4-9cf7-bf48bc445d1c.jpg)

**Comment by fehguy** [comment]
Yes, nesting in the definition is not supported in swagger-ui.  See https://github.com/swagger-api/swagger-js/issues/189

**Comment by cipresso** [comment]
OK. Do you think you might implement this in the future? swagger-editor does render nested objects, so it's a bit confusing when switching between the two components.  Thanks.

**Comment by fehguy** [comment]
Absolutely.  It's targeted for the M2 release of swagger-js

**Comment by mohsen1** [comment]
It's somehow related to https://github.com/swagger-api/swagger-js/issues/270
