### ISSUE TITLE
OpenAPI 3.1.0 support: refactor code related changes of `next` branch

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-ui#8474]
The goal of the refactor is to concentrate OpenAPI 3.1.0 related code into separate `oas31` plugin. `oas31` plugin will be another layer on top of `oas3` plugin.

**Comment by char0n** [comment]
Code related to OpenAPI 3.1.0 has been identified, and concentrated to new `oas31` plugin.

**Comment by char0n** [comment]
All changes related to OpenAPI 3.1.0 has been concentrated to `oas31` plugin.

**Comment by pk-work** [comment]
Is there a documentation how I can use swagger-ui with latest OpenAPI 3.1 features?

**Comment by char0n** [comment]
Hi @pk-work,

We're still in v5-alpha pre-release phase. Everything is still fluid and prone to change. I would recommend to follow release notes for now. We've just released swagger-ui@5.0.0-alpha.1 ([link](https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.1)), and the release contains notes what features of OpenAPI 3.1.0 are now available and links to the issues with more information. 

Would that suffice for now?
