### ISSUE TITLE
How to configure default expanded field annotations ？

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [swagger-api/swagger-ui#8480]
### Q&A (please complete the following information)
 - OS: [e.g. macOS] Windows 10
 - Browser: [e.g. chrome, safari] Google Chrome 111.0.5563.65
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0] 
     - org.webjars:swagger-ui:4.17.1
     - org.springdoc:springdoc-openapi-ui:1.6.15
     - org.springdoc:springdoc-openapi-javadoc:1.6.15
     - org.springdoc:springdoc-openapi-security:1.6.15
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### How can we help?

![image](https://user-images.githubusercontent.com/46893436/225924843-a6bb39b1-f76c-4972-ac20-bcae14a1a0e1.png)

**Comment by Elia2909** [comment]
Same problem

**Comment by Elia2909** [comment]
maybe u have some update about solve it?

**Comment by xuxiaowei-com-cn** [comment]
> @xuxiaowei-com-cn i have a ready solution for u. In configuration springdoc `springdoc.swagger-ui.default-model-expand-depth: 2`

thank you

**Comment by itsmenarayan** [comment]
```
docExpansion: 'full',
defaultModelsExpandDepth: 10, // tree height
```
