### ISSUE TITLE
OpenAPI 3.1.0 support: "Could not render Je, see the console" when expanding any operations in OpenAPI 3.1 definitions

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#8498]
### Q&A (please complete the following information)
 - OS: macOS 12.6.3
 - Browser: Chrome latest
 - Method of installation: https://editor-next.swagger.io/
 - Swagger-Editor version: UI v. 5.0.0-alpha.2; editor v. 5.0.0-alpha.52
 - Swagger/OpenAPI version: OpenAPI 3.1

### Content & configuration
n/a

### Describe the bug you're encountering
If you expand any operation in an OpenAPI 3.1 definition, "😱 _Could not render Je, see the console_" error is displayed below the operation description, and the Parameters / Request body sections are not rendered.

### To reproduce...

1. Go to https://editor-next.swagger.io/.
2. Select File > Load Example > OpenAPI 3.1 Petstore.
3. Expand any operation in the UI panel.

### Expected behavior
No errors.

### Actual behavior

"😱 _Could not render Je, see the console_" error is displayed below the operation description.

There are errors in the browser console:
```
system.js:490 RangeError: Maximum call stack size exceeded
    at He.get (immutable.js:1243:25)
    at He.getIn (immutable.js:4545:48)
    at o (system.js:256:46)
    at Object.isOAS31 (system.js:260:55)
    at fn.js:24:42
    at system.js:487:17
    at Object.webhooks (system.js:264:19)
    at wrap-selectors.js:5:43
    at fn.js:48:45
    at Object.o [as hasUserEditedBody] (system.js:205:26)

react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'hasIn')
    at wrap-selectors.js:5:43
    at fn.js:48:45
    at Object.o [as hasUserEditedBody] (system.js:205:26)
    at wrap-selectors.js:12:33
    at fn.js:48:45
    at Object.o [as hasUserEditedBody] (system.js:205:26)
    at wrap-selectors.js:12:33
    at fn.js:48:45
    at Object.o [as hasUserEditedBody] (system.js:205:26)
    at wrap-selectors.js:12:33

error-boundary.jsx:18 TypeError: Cannot read properties of null (reading 'hasIn')
    at wrap-selectors.js:5:43
    at fn.js:48:45
    at Object.o [as hasUserEditedBody] (system.js:205:26)
    at wrap-selectors.js:12:33
    at fn.js:48:45
    at Object.o [as hasUserEditedBody] (system.js:205:26)
    at wrap-selectors.js:12:33
    at fn.js:48:45
    at Object.o [as hasUserEditedBody] (system.js:205:26)
    at wrap-selectors.js:12:33 {componentStack: '\n    at Je (https://editor-next.swagger.io/static/…itor-next.swagger.io/static/js/main.js:14:7875608'}
```

### Screenshots
<img width="669" alt="'Could not render Je, see the console' error" src="https://user-images.githubusercontent.com/8576823/226705437-4c8cb63f-d3cc-439a-9747-361c06d7ec78.png">

### Additional context or thoughts
n/a

**Comment by char0n** [comment]
Hi @hkosova,

Thanks for reporting this. I'm assigning this issue to OpenAPI 3.1.0 epic and assigning it high priority.

**Comment by char0n** [comment]
Bug addressed in https://github.com/swagger-api/swagger-ui/pull/8499

**Comment by char0n** [comment]
The issues was in [hasUserEditorBody](https://github.com/swagger-api/swagger-ui/blob/abfca2dead2855e23b1e8be0b3ffeda0419db92a/src/core/plugins/oas31/oas3-extensions/wrap-selectors.js#L6) selector wrapper. It is using [createOnlyOAS31SelectorWrapper](https://github.com/swagger-api/swagger-ui/blob/abfca2dead2855e23b1e8be0b3ffeda0419db92a/src/core/plugins/oas31/fn.js#L42) which under the hood already calls original selector implicitly if spec is not of OpenAPI 3.1.0 type. Unfortunately I've called the original selector explicitly as well, which resulted in infinite recursion.

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.3. SwaggerEditor@5 will follow tomorrow morning.

**Comment by char0n** [comment]
There was one more hidden bug which was addressed in https://github.com/swagger-api/swagger-ui/pull/8500. 

Explanation:

> Affected wrapped selector was hasUserEditedBody.
This commit fixes the bug by calling the original
selector when path+method combination is not found in OpenAPI.webhooks field.

Original selector must not be called from the system, but must be called as function provided by selector wrapper. This avoids infinite recursion and enables the functionality of detecting request body user edits again.

**Comment by char0n** [comment]
SwaggerEditor@5 released and deployed as https://github.com/swagger-api/swagger-editor/releases/tag/v5.0.0-alpha.53
