### ISSUE TITLE
OpenAPI 3.1.0 support: add rendering support for JSON Schema 2020-12

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-ui#8513]
The goal of this issue is to add rendering support for [JSON Schema 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-4.2.1) within SwaggerUI. Currently there **isn't** any JSON Schema 2020-12 capable renderer. 

There are multiple ways how JSON Schema 2020-12 can be represented depending on the use case. This issue will deal with an **Object Representation**. In this approach, the JSON Schema is represented as a JavaScript object that can be used in the React application. The goal of this object representation is to visualize the JSON Schema is such a way, that person look at this representation will easily understand what the JSON Schema does.

Implementation for the renderer should be done in separate SwaggerUI plugin where all JSON Schema 2020-12 related code will be concentrated. This will allow further to possibly decouple this code from SwaggerUI in future. We should not use SwaggerUI plugin system features (to allow future decupling), but rather classic React ones (like contexts).

### MVP1

This phase includes rendering Core vocabulary identifier keywords. This includes:

- [x] displaying `properties` keyword so that MVP1 have some value
- [x] creating recursive mechanism of rendering JSON Schema 2020-12
- [x] creating UI components 
- [x] displaying schema type
- [x] displaying schema format
- [x] displaying schema description
- [x] displaying schema title
- [x] support for boolean schemas
- [x] basic collapsible behavior
- [x] extended collapsible behavior (expanding embedded schemas)
- [x] BooleanJSONSchema(false) should return `never` as type
- [x] infer type if type not defined
- [x] handling cycles while computing schema type
- [x] handling cycles during rendering
- [x] detect if schema is expandable
- [x] tracking embedding level
- [x] integrate MVP1 into `Schemas section` + lazy schema resolution
- [ ] ~~integrate deep linking into `Schemas section~~ (not implemented for Draft 4 Schemas)
- [x] add support for `defaultModelsExpandDepth` config option

#### Current visual representation

![image](https://user-images.githubusercontent.com/193286/232070091-b41ee333-6dff-4a4b-b242-9c7dae15da5b.png)

### MVP2

- [x] [add support for Validation vocabulary](https://github.com/swagger-api/swagger-ui/issues/8513#issuecomment-1501820685)

### MVP3

- [x] [add support for OpenAPI base vocabulary](https://github.com/swagger-api/swagger-ui/issues/8513#issuecomment-1521208733)

### MVP4

- [x] prepare code to use MVP3 in Operations
- [x] prepare code to use MVP3 in Webhooks
- [x] integrate MVP3 in Operations
- [x] integrate MPV3 in Callbacks 
- [x] integrate MVP3 in Webhooks
- [x] include/exclude read-only properties from rendering
- [x] include/exclude write-only properties from rendering

**Comment by char0n** [comment]
# Existing implementation

Here is the list of researched existing implementations.

## atlassian json viewer

Supports [JSON Schema Draft 07](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01) only. 

**Repo**: https://github.com/atlassian-labs/json-schema-viewer

![image](https://user-images.githubusercontent.com/193286/230905443-5800f4a8-114a-4011-a2ac-c8b9a57e2c1f.png)

---

## asyncapi-react

Supports rendring JSON Schema Draft [04](https://tools.ietf.org/html/draft-zyp-json-schema-04)/[05](https://tools.ietf.org/html/draft-wright-json-schema-00). To me personally, this looks like the most understandable representation.

**Repo**:

![image](https://user-images.githubusercontent.com/193286/230906102-ee69b353-cc5e-4648-825f-570b3d5a1bb5.png)

---

#### List of additional implementations

**Comment by char0n** [comment]
# Core vocabulary support

**Comment by char0n** [comment]
# [OpenAPI Specification's base vocabulary](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields-20)

**Comment by char0n** [comment]
Released in https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.13

**Comment by robbieaverill** [comment]
Hi @char0n, firstly thank you for sharing [your research](https://github.com/swagger-api/swagger-ui/issues/8513#issuecomment-1501790887). With these changes, does Swagger UI support rendering JSON schema data in isolation, or only as a part of OpenAPI 3.1.0 support?
