### ISSUE TITLE
swagger-ui-react v5.0.0-alpha incorrectly taggued as current release on npm

### ISSUE THREAD

**Issue by xfournet** [swagger-api/swagger-ui#8518]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: non relevant
 - Version: 5.0.0-alpha.4
 - Method of installation: npm
 - Swagger-UI version: 5.0.0-alpha.4
 - Swagger/OpenAPI version: non releveant

### Content & configuration

non relevant

### Describe the bug you're encountering

Latest tag on NPM is 5.0.0-alpha.4, instead this version should be tagged on alpha, not current

### To reproduce...

1. npm install swagger-ui-react
2. check package.json, the version 5.0.0-alpha.4 is installed

### Expected behavior
Latest stable version is installed (v4.18.1 at that time)

### Screenshots
![image](https://user-images.githubusercontent.com/461943/227770584-27f2bf9d-18bf-4a1e-8041-e47cc2e9ccf7.png)

### Additional context or thoughts
No

**Comment by silverwind** [comment]
Yes, please don't tag unstable releases as `latest`. This is a very common publishing error.

**Comment by char0n** [comment]
Hi everybody,

Thanks for reporting this. I've made sure that CD pipeline mark the swagger-ui-react/swagger-ui-dist @5 releases with `alpha` dist tag and v4 with `latest` dist tag.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/8526

**Comment by char0n** [comment]
Resolved by https://github.com/swagger-api/swagger-ui/releases/tag/v4.18.2 and https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.5 respectively
