### ISSUE TITLE
support：@ConditionalOnProperty注解导致Swagger-UI展示不正常的问题

### ISSUE THREAD

**Issue by postGL** [swagger-api/swagger-ui#8519]
@ConditionalOnProperty注解
1、会导致SwaggerUI的GroupName和apiInfo自定义失效。
2、会展示自带的basic-error-controller、operation-handler、web-mvc-links-handler，path过滤无效 .paths(Predicates.not(PathSelectors.regex("/error.*")))。

**Comment by char0n** [comment]
Closing this as this doesn't seem to be related to this repository.
