### ISSUE TITLE
deprecated on non deprecated methods

### ISSUE THREAD

**Issue by i022098** [swagger-api/swagger-ui#852]
Hello
the JSON that returns from the server states "deprecated":"false", and in the UI i got warning that the function is deprecated.
this is a bug.
in order to fix it, please change swagger-ui.js file and replace:

helpers['if'].call(depth0, depth0.deprecated --> 
helpers['if'].call(depth0, depth0.deprecated == 'true'

this change the value from String to Boolean and fix the problem
Regards
i022098

**Comment by webron** [comment]
Can you submit a PR for it?

**Comment by i022098** [comment]
done
