### ISSUE TITLE
OpenAPI 3.1.0: incorrect resolution using `https://smartbear.com` as `baseURI`

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-ui#8525]
> Thanks for the excellent work on implementing Open Api 3.1 support.
I tried to switch my schemas to 3.1 - and I see a problem with resolving $ref: paths in $ref are being resolved using smartbear.com as the host.
It's rather weird because I don't see smartbear.com in the swagger-ui code - I can't figure out where it then gets such a value as a host?
I tried to override this behavior by all means (including setting servers at the root of swagger.yaml, as well as by packing all $ref into components/schemas) - it didn't help.
Please fix determination of host when resolving $ref.

Originally reported in https://github.com/swagger-api/swagger-ui/issues/5891#issuecomment-1486189242 by @PatchRanger

**Comment by char0n** [comment]
@PatchRanger can you please describe steps of reproduction?

I've tried to reproduce using either spec URI or spec object, but with no luck. Do you use swagger-ui docker image or do you use SwaggerUI npm package with your configuration? 


The `smartbear.com` host comes from `swagger-client` (specifically [here](https://github.com/swagger-api/swagger-js/blob/2a39fb43e8fa4390b416186ea5bfbd9dd55305e1/src/resolver/strategies/openapi-3-1-apidom/resolve.js#L45)) and it's a fail-safe mechanism if `baseURI` is not provided or cannot be computed.

---

**It would help if you would fill the following bug template:**



### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration


Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering


### To reproduce...

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected behavior


### Screenshots


### Additional context or thoughts

**Comment by PatchRanger** [comment]
I've workarounded it by setting absolute URLs to `urls` config setting. Looks like the reason of this bug is that OpenApi 3.1 can't resolve relative urls passed by `urls` config setting.
For now I have another problem though. I am going to create another issue for it.

**Comment by char0n** [comment]
HI @PatchRanger,

Thank for the additional info.

`BASE_URL` is not related to definition resolution. Here is an excerpt from the [documentation](https://github.com/swagger-api/swagger-ui/blob/v5.0.0-alpha.4/docs/usage/installation.md#docker) what it does:

![image](https://user-images.githubusercontent.com/193286/228810895-e1a8f54a-9b96-4cdb-a2e4-66a74be9b0ba.png)

To say it simply, it's a way to influence how docker nginx serve the SwaggerUI  - under which URL.

---

Having said that, I've dug deep and found out the original issue. 

You used relative URLS in `URLS` env variable:

```sh
      URLS: "[
      { url: \"swagger/internal.yaml\", name: \"Internal\" }
    ]"
```

More idiomatic way how to achieve the same result is  `SWAGGER_JSON` env var. Both env variables will result in the same bug tough. The bug is actually related to the fact that the relative URL is provided to swagger-client for resolution. OpenAPI 3.1.0 requires absolute retrievalURL to actually perform the resolution. 

I'll create a bug fix in upstream is swagger-client to make sure that we handle the case of relative URLs passed as retrieval URL.


I could reproduce with following command:

```sh
$ docker run -p 80:8080 -e BASE_URL=/swagger -e SWAGGER_JSON=/foo/schemas/internal/v1/swagger.yaml -v /home/char0n/Documents/GitHub/swagger-ui:/foo swagger-api/swagger-ui
```

**Comment by char0n** [comment]
Addressed upstream in https://github.com/swagger-api/swagger-js/pull/2905

**Comment by char0n** [comment]
Addressed for SwaggerUI in https://github.com/swagger-api/swagger-ui/pull/8533. 

Tested with following steps:

```sh
# clone the repo and checkout to the next branch
$ npm i --verbose
$ npm build
$ docker build . -t swaggerapi/swagger-ui:latest
$ docker run -p 80:8080 -e BASE_URL=/swagger -e SWAGGER_JSON=/foo/schemas/internal/v1/swagger.yaml -v /home/char0n/Documents/GitHub/swagger-ui:/foo swaggerapi/swagger-u
```
Open `http://localhost/swagger/` in your favorite browser. In browser Network tab I can see the resolution now uses `http://localhost/swagger/` and not `https://smartbear.com`.

**Comment by PatchRanger** [comment]
@char0n Looks like [`latest` now leads to v4.18.2](https://hub.docker.com/r/swaggerapi/swagger-ui/tags) - they have the same sha256. So cuurently I don't see a way to pull the latest fixes, I've posted a request for it here: https://github.com/swagger-api/swagger-ui/commit/b99436b26536ac96235caa69fa34242b89c2c43c#commitcomment-106856887 - please take a look.

**Comment by char0n** [comment]
Swagger-ui@5 release will come during today as well as swagger-editor@4 and swagger-editor@5. 

And yes, only swagger-ui/swagger-editor v5 have support for OpenAPI 3.1.0.

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.5
