### ISSUE TITLE
OpenAPI 3.1.0 support: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by WilliamALiang** [swagger-api/swagger-ui#8537]
### Q&A (please complete the following information)
 - OS: [macOS]
 - Browser: [chrome]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [5.0.0-alpha.54]
 - Swagger/OpenAPI version: [Swagger 3.0, OpenAPI 3.1]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  //default
})
```

```
//default
```

### To reproduce...

1. Go to 'https://editor-next.swagger.io/?_ga=2.185794858.2005013735.1680249491-2072638638.1670232233'
2. enter openapi json
```
{
    "openapi": "3.1.0",
    "info": {
        "title": "API",
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.txt"
        },
        "version": "1.0"
    },
    "servers": [
        {
            "url": "http://192.168.0.105:11010",
            "description": "Generated server url"
        }
    ],
    "paths": {
        "/security/role-config/menu-tree": {
            "get": {
                "tags": [
                    "角色配置管理"
                ],
                "summary": "查询平台菜单树",
                "operationId": "menuTree",
                "parameters": [
                    {
                        "name": "code",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/com.cacao.operation.security.model.PlatformMenuTreeNode"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "com.cacao.operation.security.model.PlatformMenuTreeNode": {
                "properties": {
                    "children": {
                        "type": "array",
                        "description": "子节点",
                        "items": {
                            "$ref": "#/components/schemas/com.cacao.operation.security.model.PlatformMenuTreeNode"
                        }
                    },
                    "resources": {
                        "type": "array",
                        "description": "菜单下挂的资源",
                        "items": {
                            "$ref": "#/components/schemas/com.cacao.operation.security.model.PlatformMenuTreeResourceNode"
                        }
                    }
                }
            },
            "com.cacao.operation.security.model.PlatformMenuTreeResourceNode": {
                "description": "菜单下挂的资源",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "description": "ID"
                    }
                }
            }
        }
    }
}
```
3. Click menu '/security/role-config/menu-tree'

### Expected behavior

show the request and response

### Screenshots

<img width="1061" alt="eg" src="https://user-images.githubusercontent.com/23047536/229079540-c4080ed3-114a-4201-b60a-0c35c7d567ee.png">

**Comment by WilliamALiang** [comment]
schema json: 

`{
    "openapi": "3.1.0",
    "info": {
        "title": "服务端接口API",
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.txt"
        },
        "version": "1.0"
    },
    "servers": [
        {
            "url": "http://192.168.0.105:11010",
            "description": "Generated server url"
        }
    ],
    "paths": {
        "/security/role-config/menu-tree": {
            "get": {
                "tags": [
                    "角色配置管理"
                ],
                "summary": "查询平台菜单树",
                "operationId": "menuTree",
                "parameters": [
                    {
                        "name": "code",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "platformId",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    },
                    {
                        "name": "level",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/com.cacao.operation.security.model.PlatformMenuTreeNode"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "com.cacao.operation.security.model.PlatformMenuTreeNode": {
                "properties": {
                    "children": {
                        "type": "array",
                        "description": "子节点",
                        "items": {
                            "$ref": "#/components/schemas/com.cacao.operation.security.model.PlatformMenuTreeNode"
                        }
                    },
                    "resources": {
                        "type": "array",
                        "description": "菜单下挂的资源",
                        "items": {
                            "$ref": "#/components/schemas/com.cacao.operation.security.model.PlatformMenuTreeResourceNode"
                        }
                    }
                }
            },
            "com.cacao.operation.security.model.PlatformMenuTreeResourceNode": {
                "description": "菜单下挂的资源",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "description": "ID"
                    }
                }
            }
        }
    }
}`

**Comment by char0n** [comment]
This is an issue with [ApiDOM](https://github.com/swagger-api/apidom), which is used by swagger-client that facilitates OpenAPI 3.1.0 dereference for the SwaggerUI.

It seems that all the cycles haven't been eliminated in swagger-client which resulted in error in transducer. Transducer can only handle acyclic directed graphs.

**Comment by char0n** [comment]
Minimal reproducible fixture is this one:

```json
{
  "openapi": "3.1.0",
  "components": {
    "schemas": {
      "PlatformMenuTreeNode": {
        "properties": {
          "children": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PlatformMenuTreeNode"
            }
          },
          "resources": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PlatformMenuTreeResourceNode"
            }
          }
        }
      },
      "PlatformMenuTreeResourceNode": {
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "description": "ID"
          }
        }
      }
    }
  }
}
```

**Comment by char0n** [comment]
Fix provided upstream as https://github.com/swagger-api/apidom/releases/tag/v0.69.2

**Comment by char0n** [comment]
Tested with upstream fixes in SwaggerUI@5 using swagger-client@3.19.6:

![image](https://user-images.githubusercontent.com/193286/229722254-6de224a3-772d-4479-b7ab-b87e642d8d7c.png)

**Comment by char0n** [comment]
Fixed in SwaggerUI - https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.6. The SwaggerEditor@5 integration will follow  during today.

**Comment by char0n** [comment]
Reopening as I can still reproduce the issue by expadning `Com.cacao.operation.security.model.PlatformMenuTreeNode` in bottom section of the SwaggerUI:

![image](https://github.com/swagger-api/swagger-ui/assets/193286/6a40af81-d1ae-4095-9696-6a3b2a4f751e)

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-js/pull/2970

**Comment by char0n** [comment]
Verified locally that the bug is gone after using swagger-client@3.19.8 (with https://github.com/swagger-api/swagger-js/pull/2970 included).

**Comment by char0n** [comment]
Will be available in next SwaggerUI@5 release.
