### ISSUE TITLE
defaultValue is not filled in anymore

### ISSUE THREAD

**Issue by daedeloth** [swagger-api/swagger-ui#855]
DefaultValue of parameters used to be filled in by default.
Right now they are not anymore.

(swagger 1.2)

**Comment by mohsen1** [comment]
In current master(a75c9c1) it works for me

![screen shot 2015-01-28 at 10 09 55 am](https://cloud.githubusercontent.com/assets/543633/5943668/d7b19d8a-a6d5-11e4-8219-6298197381ee.png)

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-js/commit/47605dbd720a8835e9be60c35cfc3bb31638f586 pushed to develop_2.0
