### ISSUE TITLE
Incorrect base URL

### ISSUE THREAD

**Issue by AmiraAbdo** [swagger-api/swagger-ui#8551]
The base URL at /swagger path is still **petstore.swagger.io/v2**, even though I changed it in swagger-initializer.js

This is what my swagger-initializer.js file looks like:

window.onload = function() {
  //<editor-fold desc="Changeable Configuration Block">

  // the following lines will be replaced by docker/configurator, when it runs in a docker-container
  window.ui = SwaggerUIBundle({
    url: "http://localhost/doc.php",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  });

  //</editor-fold>
};

I am using XAMPP on mac

**Comment by char0n** [comment]
Hi @AmiraAbdo,

Can you maybe corroborate with more details, what the actual issue is?
