### ISSUE TITLE
supportedSubmitMethods () returns NULL

### ISSUE THREAD

**Issue by daedeloth** [swagger-api/swagger-ui#856]
```
isMethodSubmissionSupported = jQuery.inArray(this.model.method, this.model.supportedSubmitMethods()) >= 0;
```

this.model.supportedSubmitMethods() returns NULL, marking all my models as read only.
swagger v1.2: http://api.quizwitz.com/specs/

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-ui/commit/1be0f9fa35bda8b6d74e44dff41e14198aa857be
