### ISSUE TITLE
error : Failed to load API definition.

### ISSUE THREAD

**Issue by lotushn** [swagger-api/swagger-ui#8608]
Hello guys,

I'm writing a new project and I got some previous code from another project. I'm having an error in the Swagger UI and I can't find the solution. Here's my code:

#region using

using Abp.Dependency;
using Abp.Domain.Repositories;
using SATA.DOC.DomianModel.Sama.Model;
using SATA.DOC.Sama.BaseClass;
using SATA.DOC.Sama.Common.Dto;
using SATA.DOC.Sama.Helper;
using SATA.DOC.Sama.ManageSanjeh.Dto;

using System;

#endregion

namespace SATA.DOC.Sama.ManageSanjeh
{

    public class ManageSanjehAppService : GridAppService<
            int,
          ManageSanjehGridSearchDto,
           ManageSanjehGridRowDto,
           ManageSanjehViewDto,
           ManageSanjehCrudDto,//create
           ManageSanjehCrudDto,//update
           ManageSanjehCrudDto,//getItem
           ManageSanjehDeleteDto,
           ResultDto<string>>,

        IManageSanjehAppService
    {

        #region Initilize
        private readonly IRepository<MeasureAttachment, int> _repositoryPerson;

        /// <param name="iocResolver"></param>
        public ManageSanjehAppService(IIocResolver iocResolver)
        {
            _repositoryPerson = DependencyManager<IRepository<MeasureAttachment, int>>.Resolve(iocResolver);

        }

        #endregion

    }
}

And here's the error message I'm getting in Swagger UI:

Failed to load API definition.
Fetch error
response status is 500 /swagger/v1/swagger.json

Can anyone help me find the solution to this issue? Thank you.

**Comment by char0n** [comment]
Unfortunately your issue is not related to SwaggerUI JavaScript implementation, but the (C#?) that it's wrapping it. We're not able to help more. SOrry.
