### ISSUE TITLE
OpenAPI 3.1.0 support: Unrequested component name capitalization

### ISSUE THREAD

**Issue by souenzzo** [swagger-api/swagger-ui#8611]
### Q&A (please complete the following information)
 - OS: macos
 - Browser: firefox
 - Version: recent :)
 - Method of installation: tar.gz
 - Swagger-UI version: 5.0.0-alpha.8
 - Swagger/OpenAPI version: 3.1.0

### Describe the bug you're encountering

The `Schemas` section, on the bottom of the screen, when using 3.1.0 with a new view, auto-capitalize the names.

Please avoid this auto-capitalization or expose as a config (with default to false?!).

### To reproduce...

1. Open swagger-ui
2. Open any 3.1.0 API
3. Scroll down 
4. Note that all names are capitalized

### Expected behavior
names as-is in the json pointer

**Comment by char0n** [comment]
You're right. This is a regression. I'll return the behavior to the same one that the v4 has. In V5 it is possible to configure how the how to `Schema Object` name renderes.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/8710
