### ISSUE TITLE
swagger-ui-dist: vite warning `"path" has been externalized

### ISSUE THREAD

**Issue by silverwind** [swagger-api/swagger-ui#8629]
### Q&A (please complete the following information)
 - OS: any
 - Browser: any
 - Version: 4.8.13
 - Method of installation: npm
 - Swagger-UI version: 4.8.13
 - Swagger/OpenAPI version: any

### Describe the bug you're encountering
When bundling `swagger-ui-dist` via `vite`, vite will try to resolve the node-only `path` dependency and emit a warning because `path` is not present in a browser environment so it will emit a warning during every build because [of these exports](https://github.com/swagger-api/swagger-ui/blob/a2b43c181a727ec6d59cd7337b81633d6c6cd759/swagger-ui-dist-package/index.js#L13-L17).

### To reproduce...

1. Create a vite app
2. Add `swagger-ui-dist` dependency
3. Import is via `import {SwaggerUIBundle} from "swagger-ui-dist"`
4. Build it
5. Observe warning

```
[plugin:vite:resolve] Module "path" has been externalized for browser compatibility, imported by "/app/node_modules/swagger-ui-dist/absolute-path.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

### Expected behavior
No warning during vite build

### Additional context or thoughts
Either converting the module to ESM or adding `sideEffects: false` may possibly fix the issue because this may allow the bundler to exclude these unused code paths in the build output via tree-shaking.

**Comment by char0n** [comment]
Hi @silverwind,

IMHO using [swagger-ui](https://www.npmjs.com/package/swagger-ui) or [swagger-ui-react](https://www.npmjs.com/package/swagger-ui) would make this error go away.

**Comment by silverwind** [comment]
The primary reason I use `swagger-ui-dist` is because it comes pre-bundled with dependencies. I recall having issues with multiple versions of react loading at the same time in an react app, so by using the bundled version, I avoid such a possibility entirely and swagger-ui gets it's own react instance.

**Comment by char0n** [comment]
Right, so you can bypass the `main` entry point and go directly for the UMD bundle:

```js
import SwaggerUIBundle  from 'swagger-ui-dist/swagger-ui-bundle.js';
```

**Comment by silverwind** [comment]
Thanks that works, should have thought about this myself sooner.
