### ISSUE TITLE
Swagger UI version showing older version event after updating to latest version

### ISSUE THREAD

**Issue by raiajithkumarr** [swagger-api/swagger-ui#8635]
Hi Team,

We are using below mentioned framework

![image](https://user-images.githubusercontent.com/22548964/237017752-0cfcc669-3f05-4e96-be5e-5ed933e2978f.png)

And the project is azure function app even after upgrading Swashbuckle.AspNetCore to latest version (it is having internally having swaggerui dll)

when we launch the swagger endpoint for function app  while doing this we observed that, in browser console when we try to see 
**JSON.stringify(versions)** it is showing older version can you please let us why it is showing older version did we miss anything here.

![image](https://user-images.githubusercontent.com/22548964/237018688-9d5949fb-207a-4c72-afad-dc79b4417521.png)

**Comment by char0n** [comment]
Hi,

I'm sorry but this repo is only concerned with SwaggerUI JavaScript library and has nothing to do any zure function or  Swashbuckle.AspNetCore.
