### ISSUE TITLE
Content-type set to "text/plain; charset=UTF-8" for POST

### ISSUE THREAD

**Issue by vbauer** [swagger-api/swagger-ui#87]
When POSTing to a REST API, the Content-Type is set to "text/plain; charset=UTF-8", not to "application/json".

**Comment by kamil-kielczewski** [comment]
I use [this](https://stackoverflow.com/a/48413161/860099)

 *     consumes={"multipart/form-data"},
 *     produces={"text/plain, application/json"},

**Comment by ashwath20** [comment]
Have you changed the mode is set to `no-cores` then it changes the Content-type . this header filed become immutable
