### ISSUE TITLE
i have 55 end points but in the UI only 17 are visible

### ISSUE THREAD

**Issue by i022098** [swagger-api/swagger-ui#875]
Hi
i get from server 55 end points, but in the UI only 17 are visible,
any ideas?

**Comment by webron** [comment]
Is this 1.2 or 2.0?

**Comment by i022098** [comment]
i have download the source a week ago and use the Dist directory

**Comment by webron** [comment]
Sorry, I meant which version of the spec. 

You should also try pulling master again.

**Comment by i022098** [comment]
i am using swagger-springmvc version 0.9.4 to generate the server response. did it answer your question?

**Comment by webron** [comment]
Yes, it does. Can you try pulling master and retest?

**Comment by i022098** [comment]
this is the error i get in the client:
Cannot read property 'toLowerCase' of undefined

**Comment by webron** [comment]
That implies there's a problem with your spec. Can you share it?

**Comment by i022098** [comment]
do you need the JSON that return from server from /api-docs?

**Comment by webron** [comment]
Yes, but also the ones under the /api-docs, per resource.

**Comment by i022098** [comment]
ok, i have found the problem.

i have a parm with:
absoluteType="array"
and the type is undefined
will try to investigate.
thanks

**Comment by fehguy** [comment]
@i022098 this means your spec is not well formed.  Regardless, I'd like the UI to not have a problem loading, so https://github.com/swagger-api/swagger-js/commit/4a9de6050cc554ab11bd0e3b8996f54b18f1831c has been applied to swagger.js
