### ISSUE TITLE
array of enums has type inside "items" therefore there is an exception in swagger-ui.js

### ISSUE THREAD

**Issue by i022098** [swagger-api/swagger-ui#894]
i have a RequestParam that is an array of enums.
the json return is 
```
{
                            "items": {
                                "type": "string",
                                "absoluteType": "string"
                            },
                            "absoluteType": "array",
                            "name": "measurements",
                            "description": "measurementsArray",
                            "defaultValue": "",
                            "required": false,
                            "allowMultiple": true,
                            "enum": [
                                "roi",
                                "numOfExecutions",
                                "avgExecutionTime",
                                "resultDistribution"
                            ],
                            "paramType": "query",
                            "paramAccess": null
                        }
```
so the "type" property is inside the "items" object, 

but the code tries to access the type directly and cause to an exception:
in swagger-ui line 2351:
```
 if (param.type.toLowerCase() === 'array' || param.allowMultiple) 
```
any ideas? maybe it should look for "absoluteType" instead?

**Comment by i022098** [comment]
after checking this looks like a bug. can you please fix it?

**Comment by i022098** [comment]
i have a workaround that works for me. replace the order from:
 param.type.toLowerCase() === 'array' || param.allowMultiple
to:
param.allowMultiple || param.type.toLowerCase() === 'array'
in swagger-ui.js

**Comment by webron** [comment]
Apologies for taking a while to reply.

It looks like you're using Swagger 1.2. In Swagger 1.2 there's no way to define an enum for values within an array, it is just not supported (it is supported in 2.0).

Also, `absoluteType` is not an applicable property for Swagger.

**Comment by i022098** [comment]
i am using swagger-springmvc so they are using spec 1.2.
is it correct?

**Comment by webron** [comment]
That may depend on the version, and if that's the output you're getting, I suspect you're not using the latest version (earlier versions have known bugs). I'd suggest opening a ticket on their repository if you do experience this output with the latest version, and I'd be happy to assist there where I can.

**Comment by i022098** [comment]
i am using the latest 0.9.5. and this is the output i get.

**Comment by webron** [comment]
Then I would definitely urge you to open a ticket there. You can mention me (@webron) there and I'll explain the possible issues with the output.

**Comment by i022098** [comment]
Done
https://github.com/martypitt/swagger-springmvc/issues/578

**Comment by webron** [comment]
Closing it now since it is not really supported.
