### ISSUE TITLE
Headers are no long being passed on try it out after updating to M1

### ISSUE THREAD

**Issue by jbexten** [swagger-api/swagger-ui#895]
We updated our version of swagger from the Alpha1 to M1 this morning. We pass a custom header to some of our endpoints, but not all of them. When I use "Try it out" this custom header is no longer being sent.

Here is one path from our spec as an example

    "/quote/{quoteId}/{streamRevision}": {
            "patch": {
                "tags": [
                    "quote"
                ],
                "summary": "Update quote data",
                "operationId": "updateQuote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                     {
                        "in": "path",
                        "name": "quoteId",
                        "type": "string",
                        "required": true
                    },
                    {
                        "in": "path",
                        "name": "streamRevision",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "quoteAuthToken",
                        "in": "header",
                        "description": "Api Authorization token",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "description": "Quote information",
                        "required": true,
                        "schema":{
                            "$ref": "#/definitions/UpdateQuote"
                        }

                    }
                ],
                "responses": {
                    "200": {
                        "description": "It's all good",
                        "schema": {
                            "$ref": "#/definitions/Commit"
                        }
                    },
                    "400": {
                        "description": "Input information is incorrect"
                    },
                    "401": {
                        "description": "Quote auth token is not valid or expired"
                    },
                    "409":{
                        "description": "Stream revision is does not match the server revision"
                    }
                },
                "security": []
            }
        },

**Comment by webron** [comment]
Can you try pulling master again and retesting? We had a little mishap that may have caused that issue.

**Comment by jbexten** [comment]
I just pulled the most recent code and I'm still not seeing the headers passed. Also I don't know if it's related, but my dev console for Chrome is showing this error

GET http://localhost:8083/swagger-ui/dist/lib/underscore-min.map 404 (OK) :8083/swagger-ui/dist/lib/underscore-min.map:1

**Comment by fehguy** [comment]
@jbexten can you please share two things--one where you define the header in your `securityDefinitions` section and two, how you're setting the header for the client?

The `securityDefinitions` definition should look something like this:

```json
"securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
}
```

**Comment by fehguy** [comment]
ok @webron just pointed out that I'm missing something on this ticket, that you're not talkng about auth, but header params.
