### ISSUE TITLE
A tag cannot be named "debug"

### ISSUE THREAD

**Issue by giacomodrago** [swagger-api/swagger-ui#896]
If an operation is tagged with a tag named "debug" (case sensitive) the API specification fails to load, and this error is printed on the console:

    Uncaught TypeError: Cannot set property 'help' of undefined

Changing it to "Debug" or anything else fixes the problem.

My user agent is:

    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36

**Comment by fehguy** [comment]
see this ticket https://github.com/swagger-api/swagger-js/issues/209

**Comment by mohsen1** [comment]
#802 is duplicate of this
