### ISSUE TITLE
OpenAPI 3.1.0 support: "No parameters" with Path parameters and OAS 3.1.0

### ISSUE THREAD

**Issue by dvitek** [swagger-api/swagger-ui#8971]
### Q&A (please complete the following information)

This is a regression in the recent 5.1.0 release.  The bug does not exist in 5.0.0.

 - OS: windows
 - Browser: chrome
 - Version: 114.0.5735.110 (Official Build) (64-bit)
 - Method of installation: `curl -L https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.1.0.tar.gz | tar xzf -`
 - Swagger-UI version: 5.1.0
 - Swagger/OpenAPI version: OpenAPI 3.1.0

### Content & configuration

Example Swagger/OpenAPI definition:
```json
{
    "openapi": "3.1.0",
    "paths": {
        "/pet/{petId}": {
            "parameters": [
                {
                    "name": "petId",
                    "in": "path",
                    "schema": {
                        "type": "integer",
                        "format": "int64"
                    }
                }
            ],
            "get": {
                "summary": "Find pet by ID"
            }
        }
    }
}
```

Swagger-UI configuration options:
```js
  window.ui = SwaggerUIBundle({
    url: "petstore3.json",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  });
```

### Describe the bug you're encountering
![image](https://github.com/swagger-api/swagger-ui/assets/12000320/1a51902a-581a-4e9c-bd88-50a88bc7fe3b)

As you can see it says "No parameters" in Swagger UI.  However, as you can also see, there is a parameter in the openapi document.

### To reproduce...

1. cd to some directory mounted by a web server.  I've tried this with two unrelated webservers, so I don't think it matters which one.
2. `rm -fr swagger-ui-5.1.0`
3. `curl -L https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.1.0.tar.gz | tar xzf -`
4. `echo '{"openapi":"3.1.0","paths":{"/pet/{petId}":{"parameters":[{"name":"petId","in":"path","schema":{"type":"integer","format":"int64"}}],"get":{"summary":"FindpetbyID"}}}}' > swagger-ui-5.1.0/dist/petstore3.json`
5. `sed -i 's|https://petstore.swagger.io/v2/swagger.json|petstore3.json|' swagger-ui-5.1.0/dist/swagger-initializer.js`
6. Navigate to `http://...../swagger-ui-5.1.0/dist/` in your web browser
7. Click the GET /pet/{petId} Operation
8. Witness that it says "No parameters"

### Expected behavior
![image](https://github.com/swagger-api/swagger-ui/assets/12000320/bdedb328-b90d-4157-a809-f8a8425cf096)

I expect to see the petId parameter.

### Additional context or thoughts

My openapi document differs from the vanilla petstore sample in that I have hoisted "parameters" from the GET Operation into its parent Path.

I have discovered 4 different workarounds:

- Refresh the web browser once the address bar ends with `#/default/get_pet__petId_`.  Suddenly there are parameters!
    - Delete the fragment from the address bar to return to the broken behavior.
- Change "openapi" to "3.0.2".  Suddenly there are parameters!
- Move the parameter into the GET Operation instead of the Path.  Suddenly there are parameters!
    - OAS 3.1.0 still allows parameters to be specified in the Path, which is sensible for path parameters, so I don't think I'm doing anything wrong w.r.t. the standard.
- Use swagger-ui v5.0.0.  Suddenly there are parameters!

**Comment by wfjake** [comment]
This is still an issue in 5.6.2 unfortunately.

**Comment by Pradeep-Singhh** [comment]
In the 5.7.2 version the parameters are not coming up at all even after refreshing the swagger UI with the endpoint selected. There is just a glimpse of path parameters on refresh and after that they vanish.

**Comment by char0n** [comment]
Thanks to [@jux](https://github.com/jux61), this has been addressed in https://github.com/swagger-api/swagger-js/releases/tag/v3.24.6.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9426

**Comment by char0n** [comment]
Resolved by https://github.com/swagger-api/swagger-ui/releases/tag/v5.10.5
