### ISSUE TITLE
parameters of type array are not represented correctly in the UI

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#898]
If you look at http://petstore.swagger.wordnik.com/v2/swagger.json, the findByTags operation allows an array of strings however it's listed as type `string` in the UI.  Should be `Array[string]` or something like that.

**Comment by calfzhou** [comment]
:+1: really need this!

**Comment by fehguy** [comment]
It's fixed in 2.1.1-M1. Check it out!

**Comment by calfzhou** [comment]
@fehguy It works, thanks!
