### ISSUE TITLE
Include the swagger UI version number in the meta tags

### ISSUE THREAD

**Issue by JaredAAT** [swagger-api/swagger-ui#9011]
### Describe the solution you'd like
There isn't an easy way to identify what version of Swagger UI is running on the web.  It'd be nice if the `meta` tags in the head included the version number:

```
<meta name="swagger-ui" content="5.1.0" />
```

**Comment by char0n** [comment]
Hi @JaredAAT,

There actually is. Open is a browser console and type `versions`.

![image](https://github.com/swagger-api/swagger-ui/assets/193286/a2f7bae5-e0dd-4314-8bf8-20ff0b5e743f)

The same applies for SwaggerEditor.
