### ISSUE TITLE
Can we have a multiple swagger UI?

### ISSUE THREAD

**Issue by michnath** [swagger-api/swagger-ui#902]
I'm using swagger-ui for my nodeJS project and it works great.
Now I'm developing new version of my site with quite different APIs.

Currently, my swagger ui is located at localhost:2052/docs
Is it possible to have another swagger ui located at another path (let's say located:2052/v2.0)?

**Comment by mohsen1** [comment]
With recent changes to the code now you can have multiple instance of `SwaggerUi` in a single page. 

If you want to have multiple SwaggerUi instances on different paths, you just need to copy index.html and serve the second index.html from your second path. Of course you need to update js and css paths in your second html file.
