### ISSUE TITLE
OpenAPI 3.1.0 support: `additionalProperties: false` adds `additionalProp1` to samples

### ISSUE THREAD

**Issue by adavis444** [swagger-api/swagger-ui#9022]
### Q&A
 - OS: macOS
 - Browser: chrome
 - Version: Version 114.0.5735.198 (Official Build) (arm64)
 - Method of installation: git & npm
 - Swagger-UI version: [v5.1.1](https://github.com/swagger-api/swagger-ui/tree/v5.1.1)/[`89f04d3`](https://github.com/swagger-api/swagger-ui/tree/89f04d3f11288b4a63bf1f6dda3a7ca297ed69ff) (latest master)
 - Swagger/OpenAPI version: OpenAPI 3.1.0 - Not an issue in OpenAPI 3.0.x

#### Example OpenAPI definition
Minimal example that demonstrates the issue for `"additionalProperties": false` with OpenAPI 3.1.0 
```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "foo",
    "version": "0.1.0"
  },
  "paths": {
    "/": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "bar": {
                    "type": "string"
                  }
                },
                "additionalProperties": false,
                "type": "object",
                "title": "Foo"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response"
          }
        }
      }
    }
  }
}
```

### Describe the bug you're encountering
When the value of `openapi` in the OpenAPI definition is `3.0.3`, the sample body for a `POST /` request is correctly rendered as
```json
{
  "bar": "string"
}
```

However, when the value of `openapi` is `3.1.0`, the sample body for a `POST /` request is incorrectly rendered as
```json
{
  "bar": "string",
  "additionalProp1": {}
}
```

### To reproduce...

1. Follow the instructions in https://github.com/swagger-api/swagger-ui/blob/master/docs/development/setting-up.md#steps to set up dev environment
2. Save the above OpenAPI definition to `dev-helpers/examples/openapi.json`
3. Follow the instructions in https://github.com/swagger-api/swagger-ui/blob/master/docs/development/setting-up.md#using-your-own-local-api-definition-with-local-dev-build to modify `dev-helpers/dev-helper-initializer.js` by replacing `https://petstore.swagger.io/v2/swagger.json` with `./examples/openapi.json`
4. Go to http://localhost:3200/ in browser
5. See error in sample request body: `additionalProp1` field is present, violating `"additionalProperties": false` in OpenAPI definition

Modifying the value of `openapi` to `3.0.3` (or any existing 3.0.x version) in `dev-helpers/examples/openapi.json` will display a correct sample.

### Expected behavior
The sample request body for OpenAPI 3.1.0+ should not generate additional properties when `"additionalProperties": false` is present, instead maintaining consistency with OpenAPI 3.0.x samples.

### Screenshots

Correct sample with OpenAPI 3.0.3:
<img width="431" alt="image" src="https://github.com/swagger-api/swagger-ui/assets/11576729/01c33cd9-1c8f-4719-94f8-2014ac554c1a">

Incorrect sample with OpenAPI 3.1.0:
<img width="421" alt="image" src="https://github.com/swagger-api/swagger-ui/assets/11576729/05b794c1-2441-4e57-a77a-fa2335885865">

### Additional context or thoughts

Introduced in the implementation of #8577 in the PR #8910 in 
`src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js`
with change from `if (additionalProperties === true) {` to `if (isBooleanJSONSchema(additionalProperties)) {`.

**Comment by char0n** [comment]
Hi @adavis444,

It's legit, I've introduced the bug myself, thanks for providing a PR for it ;]

**Comment by char0n** [comment]
Fixed in https://github.com/swagger-api/swagger-ui/pull/9023
