### ISSUE TITLE
How is json getting aligned properly in the response 

### ISSUE THREAD

**Issue by komaravellySandeep** [swagger-api/swagger-ui#903]
I would like to know how the sample content in response class or the actual response is getting aligned automatically. I am sending json in normal format. But I see a new line and few spaces after comma after values of each attributes in the response. Would like to which Js or CSS handles this ?

**Comment by komaravellysandeep** [comment]
Hi Tony,

I have attached two images here.
Let me ask the question in clear.

In the image 1.png which is attached, I see sample json in the response
class.
And my question is about how is the json getting automatically aligned in a
pretty way. I mean how is an enter and spaces getting added after comma
which is present after the  "id":  value i.e., 0.

You can see the same in 2.png. After the value span you see a comma and
extra line and spaces in the html code that is generated.

How is this happening. Is there any JS function in swagger which aligns the
json in a neat manner.

I dont see this happening when I tried putting Swagger into my Application.
You can see that in 3.png.


On Tue, Feb 3, 2015 at 9:30 PM, Tony Tam <notifications@github.com> wrote:

> Please send sample specs or screenshots. It's too hard to understand what
> you mean without them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-ui/issues/903#issuecomment-72676384>
> .
>



-- 
Thanks
Sandeep Komaravelly
Software Engineer @ PegaSystems
Mobile: +91-9963856833

**Comment by webron** [comment]
I don't think you can attach images using emails. You either need to share links or do that directly in github.

**Comment by komaravellysandeep** [comment]
I have uploaded them here. Could you please have a look at those once and guide me.
