### ISSUE TITLE
Duplicate $ref tags not expanded in Model for UI 

### ISSUE THREAD

**Issue by jbexten** [swagger-api/swagger-ui#904]
I'm working with the M1 release. I pulled the new code this morning. The Alpha release had some issues with repeated references. The first $ref element would be expanded fully and the second would show 'null'. The M1 release no longer shows null, but now none of the $ref elements that have multiples are expanded. See below for an example.

We have a model that uses the same $ref in two places. 

     "NonDescribedVehicle": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "coverages": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/Coverage"
                    }
                },
                "permissiveUserCoverages": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/Coverage"
                    }
                }
            }
        },

The referenced object is defined as such

    "Coverage": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": ["BodilyInjury","PropertyDamage","UninsuredMotorist","MedicalPayments","Collision","Comprehensive"],
                    "default": "Collision"
                },
                "limits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Limit"
                    }
                }
            }
        },

When the UI renders this object it only shows the name of the reference
![ui-sample](https://cloud.githubusercontent.com/assets/503389/6025229/70f31248-ab96-11e4-9e20-be8f24597015.png)

Ideally I think all the $ref elements should be expanded to get a clear picture of the model.

**Comment by fehguy** [comment]
please see #934 and tests for the fix:  https://github.com/swagger-api/swagger-js/blob/c16f45196f4749071c794babae136b45655ec399/test/models.js#L204
