### ISSUE TITLE
Non-intuitive `oneOf` in the rendered documentation

### ISSUE THREAD

**Issue by xeppaka** [swagger-api/swagger-ui#9055]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Chromium
 - Version: 114.0.5735.198
 - Method of installation: online
 - Swagger-UI version: 5.1.3
 - Swagger/OpenAPI version: OpenAPI 3.1.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: 3.1.0
info:
  title: Test API
  version: '0.0.1'
paths:
  /data/test:
    post:
      tags:
      - Test API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
        required: true
      responses:
        '200':
          description: OK
      security:
      - httpAuth: []

components:
  schemas:
    Input:
      oneOf:
      - $ref: '#/components/schemas/InputOne'
      - $ref: '#/components/schemas/InputTwo'
      - $ref: '#/components/schemas/InputThree'
      discriminator:
        propertyName: vv
        mapping:
          INPUT_ONE: '#/components/schemas/InputOne'
          INPUT_TWO: '#/components/schemas/InputTwo'
          INPUT_THREE: '#/components/schemas/InputThree'
    InputOne:
      required: 
        - somefield
      type: object
      properties: 
        somefield: 
          type: string
    InputTwo:
      required: 
        - somefield
      type: object
      properties: 
        somefield: 
          type: string
    InputThree:
      required: 
        - somefield
      type: object
      properties: 
        somefield: 
          type: string
  securitySchemes:
    httpAuth:
      type: http
      scheme: bearer
```

Swagger-UI configuration options:
```js
SwaggerUIBundle({
    urls: [
      { url: "api-private/test-api.yaml", name: "test-api" }
    ],
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout",
    validatorUrl: "none"
  });
```

### Screenshots
![Screenshot_1](https://github.com/swagger-api/swagger-ui/assets/1098039/f5b62b51-9cb6-4d8b-a377-1323f73034dd)

### How can we help?
Hi, we updated to the new SwaggerUI version and from our point of view the rendering of `oneOf` objects is not intuitive for documentation reader. The `#1`, `#2`, `#3` references from the screenshot above looks a bit weird... Is it possible to use mapping value names instead of `#1`, `#2`, `#3` or make it at least the same way as it was before? Like that:

```
oneOf -> InputOne
      -> InputTwo
      -> InputThree
```

**Comment by BertSvensson** [comment]
try adding a "title" maybe?

```
InputOne:
      title: InputOne
      required: 
        - somefield
      type: object
      properties: 
        somefield: 
          type: string
```

**Comment by xeppaka** [comment]
> try adding a "title" maybe?
> 
> ```
> InputOne:
>       title: InputOne
>       required: 
>         - somefield
>       type: object
>       properties: 
>         somefield: 
>           type: string
> ```

Looks better after adding title. Thanks for the suggestion!

**Comment by gustaf-annotell** [comment]
Adding a title works, but it gets very wordy when you add it in a lot of places.

Why isn't a title generated automatically (like it was previous to 3.1.0)?
