### ISSUE TITLE
look into deprecated tag

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#907]
from https://github.com/swagger-api/swagger-ui/commit/703d3d048e2f4fe98df7906c11a2ce2edac2a670#commitcomment-9579003

**Comment by agubler** [comment]
Guys, this looks like a bug in the swagger-client.js, where is this lib maintained?

**Comment by webron** [comment]
swagger-client.js is part of the [swagger-js](https://github.com/swagger-api/swagger-js) project.

**Comment by fehguy** [comment]
please fetch 2.1.2-M1 of swagger-ui for the fix.

**Comment by agubler** [comment]
Thanks I was using the `develop_2.0` branch that I saw someone note had the fix in (It did not).

I'll update to the ` 2.1.2-M1` tag
