### ISSUE TITLE
Can I pass json files with v1.2 spec in URL

### ISSUE THREAD

**Issue by nikhiljindal** [swagger-api/swagger-ui#908]
Hi,

I want to pass my json files with swagger spec as part of the URL to generate swagger UI for them.
I know that this is possible in Swagger 2.0 using the spec param (https://github.com/swagger-api/swagger-ui#parameters), but I want to know if there is way to do this in v1.2
I cant upgrade to 2.0, since some of the frameworks I use to generate the spec only support v1.2

**Comment by fehguy** [comment]
Sorry, this is a 2.0-only feature right now.  The challenge with 1.2 is that it is required to live in multiple files, which is what made passing an object difficult.
