### ISSUE TITLE
Basic Auth only working for initial api-docs request when using window.authorizations.add(.. method

### ISSUE THREAD

**Issue by William1444** [swagger-api/swagger-ui#912]
Hi
I am trying to add the basic auth header for swagger requests using the following: window.authorizations.add("apiAuthHeader", new ApiKeyAuthorization("Authorization", auth, "header"));

This works for the initial api-docs requests, that returns the array of APIs to further query. When swagger-client.js then attempts to load the api specific information, it fails to authenticate. I have debugged the swagger-client.js code and notice that when making the first request, the value of window.authorizations.SwaggerAuthorizations has the expected ApiKeyAuth on it (from above), however when making subsequent requests, it is not there.

Please find attached the screenshot of the network tab to hepefully demo what I mean:

![swagger-basic-auth-issue](https://cloud.githubusercontent.com/assets/3598248/6069159/07a1b980-ad7a-11e4-9296-8a5153224a09.png)

The 401 requests are all missing the Basic Auth header, that the api-docs request has. Note all of those requests are going to the same domain (besides the swagger js and dependency files)

Thanks

**Comment by webron** [comment]
Which version of the ui do you use?

**Comment by William1444** [comment]
hey, thanks for getting back to me so quickly.

I am using the latest 2.1.1-M1

Many thanks

**Comment by William1444** [comment]
The server hosted REST APIs are using Swagger 1.2. 

I have figured out that on the response callback from the first request, the window.authorizations.SwaggerAuthorizations changes. The custom auth I put on there is gone after the initial request. 

I have created a fork to show you my quick hack https://github.com/William1444/swagger-ui/commit/eada451af958ee53b7061f605a41e4b090f78517.

**Comment by William1444** [comment]
forget it. I think I had an old version of a swagger js file hanging around that was being used. Closing the issue
