### ISSUE TITLE
attributes of type "object" (Map) do not show additionalProperties

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-ui#913]
There is a workaround for supporting Maps in swagger-core 2 that uses the "additionalProperties" field to hold details. However, the UI continues to show "object" in the model field and ignores additionalProperties

Ideally this would show map[string, foo]

**Comment by fehguy** [comment]
Yes, this is all planned for 2.1.0-M2.  See here for tracking:

https://github.com/swagger-api/swagger-js/issues/230

**Comment by todd-richmond** [comment]
Using latest 1.5.2-M1 core and 2.1.8 UI, swagger-ui does not include the required model in the response class section. In this case, the returned model Host, should had it's inner class Disk included in the response and "disks (object, optional): disk" should be "disks (Map[Disk], optional): disk"

Code:
```java
    @ApiModel
    public class Host {
        @ApiModelProperty(value = "disks", dataType =
        "Map[string,com.foo.model.Host$Disk]")
        private DiskMap disks;

        @ApiModel(description = "disk attributes")
        public static class Disk implements Serializable {
            @ApiModelProperty("disk selected")
            private boolean selected;
            @ApiModelProperty("disk size")
            private String size;
        }
    }
```
and output spec:
```js
    Host:  {
       properties: {
           disks: {
               type: "object",
               description: "disks",
               additionalProperties: {
                   $ref: "#/definitions/Disk"
               }
            }
       }
    },
    Disk: {
        properties: {
            selected: {
                type: "boolean",
                description: "disk selected"
            },
            size: {
                type: "string",
                description: "disk size"
            }
        },
        description: "disk attributes"
    }

**Comment by fehguy** [comment]
I don't believe inner classes can work.  Can you please see about making the class public and report back?

**Comment by todd-richmond** [comment]
Sorry - not sure I understand. The inner class is public - it is com.foo.bar.Host$Disk. This is a fairly common object oriented design to prevent creating top level classes that can only exist within the context of another class. In this case, you would never want to instantiate Disk instead of Host.Disk because it can only be used by the Host object

Tthe swagger definition seems to link them correctly, though there will be potential namespace conflicts if Disk is an inner class of multiple other classes. 

My comment was that the Disk class doesn't seem to be listed in the UI at all for the Host object, even though it has an additionalProperties linking to Disk

**Comment by mohsen1** [comment]
Follow this issue in SwaggerJS repo https://github.com/swagger-api/swagger-js/issues/298

**Comment by todd-richmond** [comment]
did you close the wrong side of the duplication?

**Comment by vishalsolanki888** [comment]
how to map below json:
{
 "category": {
    "id": 0,
    "name": "string"
  },
  "name": "doggie",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

what will be the annotation for this in swagger ui  in php?
