### ISSUE TITLE
remove "or" from enum list

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-ui#914]
An enum with numerous values ends up becoming a very long string in the Model details. No need to join them with 'XXX' or 'YYY' or 'ZZZ'. Instead, just use XXX, YYY, ZZZ. Don't even need quotes because enums can't have spaces in them

**Comment by fehguy** [comment]
java enums can't have spaces, but that's not a constraint for the json-schema enum value.  It's an easy fix and makes sense https://github.com/swagger-api/swagger-js/issues/416
