### ISSUE TITLE
2.0 spec - operation under multiple tags - toggleOperationContent expands under wrong tag

### ISSUE THREAD

**Issue by rmullinnix** [swagger-api/swagger-ui#916]
When I have multiple tags on a Operation Object, the operations are showing correctly in each section.  However, when I click to expand in one section, it expands in the other section.

This is in the swagger-ui.js file -  OperationView.prototype.toggleOperationContent

From what I can see, it uses the parentId of the Operation.  There is only one copy of the operation in the overall model and the last tag overwrites the previous parentId (previous tag) of the operation. An operation could have multiple parentIds (tags), but the js code doesn't appear to be supporting this.

(Mac OS, Chrome, swagger-ui.js version v2.1.1-M1)

**Comment by fehguy** [comment]
Fixed, thanks
