### ISSUE TITLE
`swagger-ui-dist` does not export `SwaggerUIBundle`

### ISSUE THREAD

**Issue by KostyaTretyak** [swagger-api/swagger-ui#9163]
### Q&A (please complete the following information)
 - OS: Ubuntu 22.04
 - Method of installation: npm
 - Swagger-UI version: `swagger-ui-dist` v5.4.2

### Describe the bug you're encountering

The [documentation](https://github.com/swagger-api/swagger-ui/blob/155660d7b0f97e7717177966d5b4050baa321881/docs/usage/installation.md) says I can use `SwaggerUIBundle`, which is not actually exported from `swagger-ui-dist` v5.4.2.

### To reproduce...

```ts
console.log(require('swagger-ui-dist'));
```

Outputs:

```text
{
  absolutePath: [Function: getAbsoluteFSPath],
  getAbsoluteFSPath: [Function: getAbsoluteFSPath]
}
```

### Expected behavior

Either the documentation needs to be updated or `SwaggerUIBundle` needs to be exported.

**Comment by oxypomme** [comment]
By checking the file ([swagger-ui-dist-package/index.js](https://github.com/swagger-api/swagger-ui/blob/master/swagger-ui-dist-package/index.js)), we can find :

```js
try {
  module.exports.SwaggerUIBundle = require("./swagger-ui-bundle.js")
  module.exports.SwaggerUIStandalonePreset = require("./swagger-ui-standalone-preset.js")
} catch(e) {
  // swallow the error if there's a problem loading the assets.
  // allows this module to support providing the assets for browserish contexts,
  // without exploding in a Node context.
  //
  // see https://github.com/swagger-api/swagger-ui/issues/3291#issuecomment-311195388
  // for more information.
}
```

So `SwaggerUIBundle` _can_ be exported, but it depends if an error is throwed or not

**Comment by KostyaTretyak** [comment]
So, as described in the comments of the "catch" block, this feature is intended for the browser and is apparently not available for Node.js. Therefore, it is better to write about it in the documentation, so that the developers do not think that it is a bug.
