### ISSUE TITLE
Strange PATCH problem

### ISSUE THREAD

**Issue by neilyoung** [swagger-api/swagger-ui#917]
This JSON (below) doesn't display the box to input "nr". Instead this is shown.

![shot1](https://cloud.githubusercontent.com/assets/731020/6099989/c4ad2530-b006-11e4-96ee-1221b309b760.png)

If I change it to POST or PUT everything is fine and the display looks like this (as it should).

![shot2](https://cloud.githubusercontent.com/assets/731020/6099996/e59db386-b006-11e4-886b-fffe0cf4afde.png)

    {
        "swagger": "2.0",
        "host": "localhost:5000",
        "schemes": [
            "http",
            "https"
        ],
        "basePath": "/api/v1",
        "produces": [
            "application/json"
        ],
        "paths": {
            "/info/{nr}": {
                "patch": {
                    "parameters": [
                        {
                            "name": "nr",
                            "in": "path",
                            "description": "...",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "responses": {
                        "200": {
                        }
                    }
                }
    		}
        }
    }

**Comment by fehguy** [comment]
Check your `supportedSubmitMethods` in your index.html.  If nothing is set, you should be able to remove the entry entirely, and it'll allow everything.  If that doesn't work, it's a bug.  Please check it out and post back.

**Comment by neilyoung** [comment]
Yepp. That worked.... The solution was so close...

Thanks
