### ISSUE TITLE
Cannot find module: '#swagger-ui'.

### ISSUE THREAD

**Issue by day-xue** [swagger-api/swagger-ui#9171]
when use yarn build throw Error  Cannot find module: '#swagger-ui'.

**Comment by char0n** [comment]
Hi @day-xue,

You need to provide more context. What version of Node.js are you using? What build system (bundler and version) are you using?

**Comment by char0n** [comment]
Most likely it's related to the fact that your blunder doesn't support [imports field](https://nodejs.org/api/packages.html#imports).

**Comment by philipwhiuk** [comment]
I'm using browserify and it doesn't seem to work. Is browserify unsupported? It used to work.

**Comment by char0n** [comment]
Hi @philipwhiuk,

> Is browserify unsupported?

Yes, I would say so. Last version of browserify was released almost 4 years ago. You'll have to use some older version of SwaggerUI with browserify. Sorry.

I recommend you start using some industry standard modern bundlers. Here is a wiki we maintain to demonstrate seamless integration of SwaggerUI with modern bundlers: https://github.com/swagger-api/swagger-ui/wiki/Seamless-Integration-with-Bundlers-&-Test-Tools
