### ISSUE TITLE
UI Rendering takes over 5 minutes with large dataset

### ISSUE THREAD

**Issue by bpatters** [swagger-api/swagger-ui#918]
I was protyping using swagger ui for our product and in combination with swagger-springmvc generated api docs. Our product has a very large set of endpoints and parameters. the swagger-springmvc slows down our startup by several minutes. However the real problem is once the swagger-ui has finished downloading all of the api data (a few megabytes) it takes over 5+ minutes to render and chrome uses 3.5 gigabytes of memory and it ends up not even rendering correctly (have to click the wait button several times). 

Is there a minimal version of the UI that can be used without all of the edit fields etc?

**Comment by fehguy** [comment]
Wow what???  If you can anonymize the JSON output and share it--even privately--I'd like to look into it.

**Comment by fgaule** [comment]
I have been experiencing same issue since i've updated swagger-ui to the master branch code (not 5 minutes, but it's taking more time than before)

**Comment by webron** [comment]
@fgaule - just like @bpatters, if you can share your JSOn with us in any way, it would help us debug the issue and solve it.

**Comment by fgaule** [comment]
@webron Sure, it will take me a while to obfuscate it

Here is a profiling i have done recently. Maybe it gives you a clue
![screenshot from 2015-02-10 11 16 54](https://cloud.githubusercontent.com/assets/5197835/6128658/836a3642-b116-11e4-9e85-32eb7d586178.png)

**Comment by webron** [comment]
Great, thanks. You can send it to apiteam@swagger.io and it'll reach both Tony and myself.

**Comment by bpatters** [comment]
I'll try and get some anonymized data uploaded and/or profiling information

**Comment by bpatters** [comment]
Attached is a profiel with a .png extension, hopefully you can download it and load into chrome.

![cpu-20150210t150358 cpuprofile](https://cloud.githubusercontent.com/assets/2925592/6136487/9405712c-b136-11e4-9f29-63db8ad8a3c5.png)

**Comment by bpatters** [comment]
Here's another one, same error but the profile data still gives you an idea:
swagger-client.js:1734 Uncaught TypeError: Cannot read property 'toLowerCase' of undefinedswagger-client.js:1734 (anonymous function)swagger-client.js:1642 Handlebars.templates.param_list.Handlebars.template.mainhandlebars-2.0.0.js:27 eswagger-client.js:1769 ParameterView.renderswagger-client.js:1220 OperationView.addParameterswagger-client.js:1202 OperationView.renderswagger-client.js:1921 ResourceView.addOperationswagger-client.js:1903 ResourceView.renderswagger-client.js:916 MainView.addResourceswagger-client.js:895 MainView.renderswagger-client.js:317 SwaggerUi.renderswagger-client.js:248 (anonymous function)swagger-client.js:1664 SwaggerClient.selfReflectswagger-client.js:1787 SwaggerResource.addApiDeclarationswagger-client.js:1731 obj.on.response

This one was big so I had to compress it. Use the following process:
Download image to png
Rename to debug2.cpuprofile.Z
uncompress debug2.cpuprofile.Z



![cpu-20150210t153123 cpuprofile](https://cloud.githubusercontent.com/assets/2925592/6136929/7bc627f6-b13a-11e4-925b-c77c0b231a7c.png)

**Comment by fehguy** [comment]
@bpatters can you give this branch a shot?  Should be substantially faster:

https://github.com/swagger-api/swagger-ui/tree/feature/legacy-cleanup

Still in development but would like your feedback.  It is about 100x faster from other large specs that I've tested.

**Comment by bpatters** [comment]
That rendered a lot faster before flopping out and giving me the error below:
swagger-ui.js:1734 Uncaught TypeError: Cannot read property 'toLowerCase' of undefinedswagger-ui.js:1734 (anonymous function)swagger-ui.js:1642 Handlebars.templates.param_list.Handlebars.template.mainhandlebars-2.0.0.js:27 eswagger-ui.js:1769 ParameterView.renderswagger-ui.js:1220 OperationView.addParameterswagger-ui.js:1202 OperationView.renderswagger-ui.js:1921 ResourceView.addOperationswagger-ui.js:1903 ResourceView.renderswagger-ui.js:916 MainView.addResource


Might be related to this error I get in the network panel:

/Users/bpatterson/code/swagger-ui/dist/lib/underscore-min.map 
GET	(failed)
net::ERR_FILE_NOT_FOUND
index.html:1
Parser
0 B
0 B
89 ms
-

**Comment by fehguy** [comment]
That smells like a parameter is missing a name.  Would help a lot if you can anonymize your specs and share them.

**Comment by bpatters** [comment]
Can you point me to a program to anonymize the dataset? Unfortunately I can't upload the API specs to our entire enterprise application here without  obfuscating it.

**Comment by fehguy** [comment]
I don't know of one (but it would be very helpful).  Perhaps you can email them directly, or take away the hostnames, etc.

**Comment by fehguy** [comment]
in 2.1.3-M1 there was a fix which massively increases loading speed.  100X+ in larger sets.  Please update to that version and post back.

**Comment by fgaule** [comment]
@fehguy Seems to be fix here!

**Comment by fehguy** [comment]
@fgaule looking into that.

**Comment by bpatters** [comment]
That fixed it. I still have the exception but that appears to be a missing type issue which is not your problem. Good job!

**Comment by fehguy** [comment]
Awesome.  @bpatters can you tell me which parameter is missing?  I'd rather have some nice error message instead of a javascript error.

**Comment by bpatters** [comment]
Attached screenshot of the line of code and function.

The Object value in the parameter is:
`Object {name: "isArray", hash: Object, fn: function, inverse: function, data: Object}data: Objectroot: ObjectabsoluteType: "array"allowMultiple: trueallowableValues: ObjectdescriptiveValues: Array[20]__proto__: Objectconsumes: Array[1]0: "application/json"length: 1__proto__: Array[0]default: ""defaultValue: ""description: "services"enum: Array[20]0: "TWITTER"1: "FACEBOOK"2: "YOUTUBE"3: "LINKEDIN"4: "FLICKR"5: "BLOGGER"6: "SLIDESHARE"7: "BAZAARVOICE"8: "GOOGLEPLUS"9: "BRANDWATCH"10: "RSS"11: "GOOGLE"12: "GOOGLEBLOGSEARCH"13: "BOARDREADER"14: "SOCIALMENTION"15: "CRIMSON_HEXAGON"16: "WORDPRESS"17: "INSTAGRAM"18: "SINAWEIBO"19: "PINTEREST"length: 20__proto__: Array[0]isList: trueitems: ObjectabsoluteType: "string"type: "string"__proto__: Objectname: "services"paramAccess: nullparamType: "query"required: truesampleJSON: undefinedsignature: undefinedtype: undefined__proto__: Object__proto__: Object`
![swagger](https://cloud.githubusercontent.com/assets/2925592/6191397/a245c162-b36e-11e4-8904-3c800ce8d1d9.png)

**Comment by fehguy** [comment]
it'd really be helpful if you can share the `name` parameter from this operation in json format.

**Comment by fehguy** [comment]
ok the speed has been addressed and I'm happy to dig into this more but it seems to be a malformed spec, and without it, hard to debug.
