### ISSUE TITLE
Missing redirect_uri in OAuth2 access token request 

### ISSUE THREAD

**Issue by stefanotravelli** [swagger-api/swagger-ui#919]
When authenticating swagger-ui with OAuth2 access code flow against [Keycloak](http://keycloak.jboss.org/), the authentication fails because in the access token request there is no redirect_uri parameter.

I think Keycloak is right here since redirect_uri is REQUIRED in [RFC6749#4.1.3](http://tools.ietf.org/html/rfc6749#section-4.1.3).

I was able to make it works hardcoding the redirect_uri in [swagger-oauth.js](https://github.com/swagger-api/swagger-ui/blob/master/lib/swagger-oauth.js#L202). It should be stored somewhere during the authorization code request.

**Comment by webron** [comment]
@bshamblen, do you happen to have an input on that?

**Comment by stefanotravelli** [comment]
In pull request #920 I used a global variable to store the redirect_uri.

**Comment by webron** [comment]
Should be fixed now. Please reopen if still an issue.
