### ISSUE TITLE
Render only specified api (1.2) or tag (2.0)

### ISSUE THREAD

**Issue by ksimka** [swagger-api/swagger-ui#922]
We have a very large set of paths and methods in our api. And we don't want to load every doc every time. So it'd be great to have a possibility to render only specified api (as for version 1.2) or tag (version 2.0 and later). With that feature we can have separate html pages with swagger-ui clients, each rendering only one part of our api.

I feel that it's not too difficult. Do you plan something like this? If not then can you please give any advice on how to hack swagger-ui to make this possible?

**Comment by ksimka** [comment]
I have a quite dirty solution: to generate full separate docs for each part, like it's a separate api, but it'd be better to have just an option for swagger-ui :)

**Comment by fehguy** [comment]
hi @ksimka i have a fix for the 1.2 support in swagger-client.  It is about 100x faster to load, so you may not have a problem with the size of your specs.

It's in cleanup and testing mode, please try this branch if you'd like:

https://github.com/swagger-api/swagger-ui/tree/feature/legacy-cleanup

**Comment by ksimka** [comment]
Thanks, I'll try it anyway, but the thing is — it's not about performance. To be accurate — not about **client** performance. There are two reasons
- I want to reorganize docs for better user experience. I think that separate static page with its own manually written text description and a small portion of api is much better than dozens of paths in one page. 
- for our devel environment we generate swagger-spec in realtime, and it's really slow (developer visits the docs page, swagger sends dozens of requests for json, server runs realtime generation for each), cause our server preprocessing is quite slow. We have workarounds, but still.

**Comment by fehguy** [comment]
Got it.  So the way I would support this right now would be to load the specific api in the UI (for example, you can load http://petstore.swagger.io/api/api-docs/pet directly in the API).  You can handle this loading via javascript in your app, and even base the list of APIs to show from the resource listing.

Lazy-loading them is not going to be in the 2.1.0 release

**Comment by ksimka** [comment]
> (for example, you can load http://petstore.swagger.io/api/api-docs/pet directly in the API)

Ha, that's exactly what I wanted, and it works! Shame on me for not trying that ) Thanks, Tony!

**Comment by fehguy** [comment]
Sweet!
