### ISSUE TITLE
Can't resolve '#swagger-ui'

### ISSUE THREAD

**Issue by davidh0** [swagger-api/swagger-ui#9227]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Opera, Chrome
 - Version: latest
 - Method of installation: npm, yarn
 - Swagger-UI version: 5.7.2
 - Swagger/OpenAPI version: N/A

### Content & configuration
Installing "swagger-ui-react" with:
`yarn add swagger-ui-react`

Include with:
```
import SwaggerUI from "swagger-ui-react"
import "swagger-ui-react/swagger-ui.css"
```

Example Swagger/OpenAPI definition:
N/A

Swagger-UI configuration options:
N/A

### Describe the bug you're encountering
On compilation of the react project, I get following error:
```
./node_modules/swagger-ui-react/index.mjs
Module not found: Can't resolve '#swagger-ui' in '...\node_modules\swagger-ui-react'
```

### To reproduce...

1. Install "swagger-ui-react" with:
`yarn add swagger-ui-react`

2. Include with:
```
import SwaggerUI from "swagger-ui-react"
import "swagger-ui-react/swagger-ui.css"
```

3. Compile with:
`yarn start`

### Expected behavior
Compiles without error.

### Screenshots
<img width="707" alt="Screenshot 2023-09-19 124340" src="https://github.com/swagger-api/swagger-ui/assets/106731097/16ec36d9-999f-4e44-897b-f9592433cff1">

### Additional context or thoughts
Don't know why this error doesn't occur to anyone else. I also tried lower version till 5.4.2.
I checked the source code and there is no swagger-ui package and inside the node_modules. Also no package named #swagger-ui was installed.

It's just a fresh install of the package and include of the files. Nothing more.

**Comment by davidh0** [comment]
Seems to be a special case of the project. In a new react project everything works.

**Comment by Philipp-Werminghausen** [comment]
Running into the same issue. How did you resolve it?

**Comment by H-pun** [comment]
this is vite.config.js related issue

with this config I encounter same issue

`import fs from 'fs'
import * as path from 'path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import rollupNodePolyFill from 'rollup-plugin-node-polyfills'
import NodeGlobalsPolyfillPlugin from '@esbuild-plugins/node-globals-polyfill'

export default () => {
  return defineConfig({
    plugins: [react()],
    define: {
      global: 'globalThis'
    },
    server: {
      port: 3000,
      proxy: 'https://ismilelab-telu.com/',
      cors: {
        origin: ['https://ismilelab-telu.com/', 'http://localhost:3000'],
        methods: ['GET', 'PATCH', 'PUT', 'POST', 'DELETE', 'OPTIONS'],
        allowedHeaders: ['Content-Type', 'Authorization', 'X-Requested-With']
      }
    },
    css: {
      preprocessorOptions: {
        scss: {
          includePaths: ['node_modules', './src/assets']
        }
      },
      postcss: {
        plugins: [require('postcss-rtl')()]
      }
    },
    resolve: {
      alias: [
        {
          find: /^~.+/,
          replacement: val => {
            return val.replace(/^~/, '')
          }
        },
        { find: 'stream', replacement: 'stream-browserify' },
        { find: 'crypto', replacement: 'crypto-browserify' },
        { find: '@src', replacement: path.resolve(__dirname, 'src') },
        { find: '@store', replacement: path.resolve(__dirname, 'src/redux') },
        { find: '@configs', replacement: path.resolve(__dirname, 'src/configs') },
        { find: 'url', replacement: 'rollup-plugin-node-polyfills/polyfills/url' },
        { find: '@styles', replacement: path.resolve(__dirname, 'src/@core/scss') },
        { find: 'util', replacement: 'rollup-plugin-node-polyfills/polyfills/util' },
        { find: 'zlib', replacement: 'rollup-plugin-node-polyfills/polyfills/zlib' },
        { find: '@utils', replacement: path.resolve(__dirname, 'src/utility/Utils') },
        { find: '@hooks', replacement: path.resolve(__dirname, 'src/utility/hooks') },
        { find: '@assets', replacement: path.resolve(__dirname, 'src/@core/assets') },
        { find: '@layouts', replacement: path.resolve(__dirname, 'src/@core/layouts') },
        { find: 'assert', replacement: 'rollup-plugin-node-polyfills/polyfills/assert' },
        { find: 'buffer', replacement: 'rollup-plugin-node-polyfills/polyfills/buffer-es6' },
        { find: 'process', replacement: 'rollup-plugin-node-polyfills/polyfills/process-es6' },
        { find: '@components', replacement: path.resolve(__dirname, 'src/@core/components') },
        { find: '@custom-components', replacement: path.resolve(__dirname, 'src/components') }
      ]
    },
    esbuild: {
      loader: 'jsx',
      include: /.\/src\/.*\.js?$/,
      exclude: [],
      jsx: 'automatic'
    },
    optimizeDeps: {
      esbuildOptions: {
        loader: {
          '.js': 'jsx'
        },
        plugins: [
          NodeGlobalsPolyfillPlugin({
            buffer: true,
            process: true
          }),
          {
            name: 'load-js-files-as-jsx',
            setup(build) {
              build.onLoad({ filter: /src\\.*\.js$/ }, async args => ({
                loader: 'jsx',
                contents: await fs.readFileSync(args.path, 'utf8')
              }))
            }
          }
        ]
      }
    },
    build: {
      rollupOptions: {
        external: ['#swagger-ui'],
        plugins: [rollupNodePolyFill()]
      }
    }
  })
}
`

**Comment by Chimpicus** [comment]
Also having this issue, has anyone got a solution? The project I'm trying to implement this in is CRA not Vite.

**Comment by H-pun** [comment]
This might be rollup related issue in vite.config.js
 #9443 You guys might want to see this

**Comment by Ronald-Saunfe** [comment]
I am using Nextjs 14.2.6

running this command fixed the issue
`npm i swagger-ui-react `

**Comment by mihirverma7781** [comment]
> Also having this issue, has anyone got a solution? The project I'm trying to implement this in is CRA not Vite.

Have you solved the issue? I am getting the same issue.

**Comment by Chimpicus** [comment]
> > Also having this issue, has anyone got a solution? The project I'm trying to implement this in is CRA not Vite.
> 
> Have you solved the issue? I am getting the same issue.

Hey, so we got around this by using the package `swagger-ui-dist`, We couldn't get the React package to work within CRACO but i was able to run it in a fresh CRA project. Try it and let me know how it goes please.

**Comment by mihirverma7781** [comment]
> > > Also having this issue, has anyone got a solution? The project I'm trying to implement this in is CRA not Vite.
> > 
> > 
> > Have you solved the issue? I am getting the same issue.
> 
> Hey, so we got around this by using the package `swagger-ui-dist`, We couldn't get the React package to work within CRACO but i was able to run it in a fresh CRA project. Try it and let me know how it goes please.

I used react-app-rewired as a dev dependency to create the build for my project. In my investigation, I found that it uses an old version of Webpack which I guess is not compatible with swagger-ui-react. So I have configured the project to use the latest version webpack and babel for transpiling and  creating a build which solved the issue for me.

**Comment by mihirverma7781** [comment]
> dist

Is the package you are mentioning is like to like replacement for swagger-ui-react or is this a totally different package?
