### ISSUE TITLE
How to can I set default values on class attributes?

### ISSUE THREAD

**Issue by murkein** [swagger-api/swagger-ui#923]
I want to set default values on class attributes and that those values be showed on my swagger ui. It would be wonderfull...

**Comment by webron** [comment]
Which version of Swagger do you use?

**Comment by murkein** [comment]
it is my swagger dependence content:

        
        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jersey2-jaxrs_2.10</artifactId>
            <scope>compile</scope>
            <version>1.3.7</version>
            <exclusions>
                <exclusion>
                    <groupId>org.glassfish.jersey.media</groupId>
                    <artifactId>jersey-media-multipart</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.glassfish.jersey.containers</groupId>
                    <artifactId>jersey-container-servlet-core</artifactId>
                </exclusion>
                
                <exclusion>
                    <groupId>javax.ws.rs</groupId>
                    <artifactId>jsr311-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by webron** [comment]
So this sounds like a question for [swagger-core](https://github.com/swagger-api/swagger-core) then.

**Comment by murkein** [comment]
ok thanks
