### ISSUE TITLE
npm i --save swagger-ui-react throws error: Could not find any Python installation to use, but python is not mentioned in installation steps 

### ISSUE THREAD

**Issue by ITConsultingLink** [swagger-api/swagger-ui#9255]
1. run npm install --save swagger-ui-react

From what i read in documentation, this should install swagger ui react.

In my case, i get an error:

checking Python explicitly set from command line or npm configuration
gyp ERR! find Python - "--python=" or "npm config get python" is "python3.11.5"
gyp ERR! find Python - "python3.11.5" is not in PATH or produced an error

I have installed latest python and did set a path.

What else do I need to do?

**Comment by HarshDubey1011** [comment]
See this issue https://github.com/nodejs/node-gyp/issues/2664 they also got similar error.

**Comment by ITConsultingLink** [comment]
I managed to solve this one, but now i get runtime errors.
It seems, that the newest python version has a change, with wich dependencies cant work. I had to install python 3.1.0 to get it working.
