### ISSUE TITLE
Empty selection (`--') of query parameter with array of enum

### ISSUE THREAD

**Issue by zorba128** [swagger-api/swagger-ui#9266]
### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.1.0
paths:
  /getdata
    get:
      parameters:
      - name: user_id
        in: query
        required: false
        schema:
          type: integer
          format: int64
      - name: state
        in: query
        required: false
        schema:
          type: array
          items:
            $ref: '#/components/schemas/State'
        example:
        - STARTED

components:
  schemas:
    State:
      type: string
      enum:
      - STARTED
      - SUBMITTED
      - RESUBMISSION
      - APPROVED
      - DECLINED
      - EXPIRED
```

### Describe the bug you're encountering

Endpoint as uses optional `state` query string parameter to pick only matching values. Its optional, as I want to allow unfiltered result also. Rendered UI looks like
![image](https://github.com/swagger-api/swagger-ui/assets/6301362/300cbb2b-a85c-4279-96ec-9bb9b0dd5572)

Everything works fine, except `--` option - which causes problems.
With `--` selected I get request like:
`https://localhost/api/v1/getdata?state=`

Valid requests are: 
`https://localhost/api/v1/getdata?state=STARTED&state=SUBMITTED`
`https://localhost/api/v1/getdata`

It is possible to generate valid request by unselecting all the entries, but then the `--` option is misleading.
I see two options to fix that:
- get rid of `--` from the selection box; user can generate request with no filter - by manually unselecting all the list items
- keep `--`, but give it special handling:
  -  do not render it as query parameter
  -  and have simple behavior that 'selecting `--` should deselect all other entries'

**Comment by zorba128** [comment]
Also with 
```
        in: query
        required: false
        explode: false
```
its even worse - I'm unable to send request with no value listed.

**Comment by char0n** [comment]
Hi @zorba128,

You need to use `allowEmptyValue` Parameter Object field.

```
        in: query
        required: false
        explode: false
        allowEmptyValue: true
```

**Comment by char0n** [comment]
Closing as duplicated of https://github.com/swagger-api/swagger-ui/issues/5176
