### ISSUE TITLE
compile errors with swagger ui react included.

### ISSUE THREAD

**Issue by ITConsultingLink** [swagger-api/swagger-ui#9272]
Hi,

when I use swagger ui react as followed:

```
import SwaggerUIReact from "swagger-ui-react";
...

<>
<SwaggerUIReact url="https://..../swagger/docs/v1" />....
</>


```
INTERNAL ERROR
Error loading https://component-id.invalid/db2320eb-8648-4782-a310-489eaadceffe_0.0.1
	Module parse failed: \node_modules\source-map-loader\index.js!...\node_modules\swagger-client\es\resolver\index.js Unexpected token (19:4)
You may need an appropriate loader to handle this file type.
|   })(retrievalURI));
|   const strategyOptions = {
|     ...options,
|     spec: retrievedSpec
|   };
CALLSTACK:
Error
    at t [as constructor] (http://.../_layouts/15/next/spclient/de-de/sp-webpart-workbench-assembly.js?uniqueId=65RaA:297:15766)
    at new t (http://..._layouts/15/next/spclient/de-de/sp-webpart-workbench-assembly.js?uniqueId=65RaA:928:22189)
    at e.buildErrorWithVerboseLog (http://.../_layouts/15/next/spclient/de-de/sp-webpart-workbench-assembly.js?uniqueId=65RaA:928:14423)
    at e.buildLoadComponentError (http://.../_layouts/15/next/spclient/de-de/sp-webpart-workbench-assembly.js?uniqueId=65RaA:928:10844)
    at http://.../_layouts/15/next/spclient/de-de/sp-webpart-workbench-assembly.js?uniqueId=65RaA:928:62110

Do I miss something? I am running react 18 with function components....

Thanks.

**Comment by grbknr1996** [comment]
Is this issue from babel config loader?

**Comment by ITConsultingLink** [comment]
I am not sure, if this is an issue with babel.

When I jump into the code, I am landing at this import:

import*as y from"swagger-client/es/resolver" which is located in swaggerui/config/config.json....

So it could be a reason.

**Comment by char0n** [comment]
```
18:  const strategyOptions = {
19:    ...options,
20:    spec: retrievedSpec
21:  };
```

You're hitting error on line `19`. It seems your Node.js version or bundling framework doesn't support `destructuring` and all related constructs supported since Node.js >= 6. You'll have to babelify it even though it's inside `node_modules`. 

> Do I miss something? I am running react 18 with function components....

Be cautious as SwaggerUI technically still officially doesn't support React 18. See more in here :https://github.com/swagger-api/swagger-ui/pull/8414
