### ISSUE TITLE
No support for global parameters

### ISSUE THREAD

**Issue by aroemen** [swagger-api/swagger-ui#929]
The swagger editor seems to render them, but they are not rendered at all in this project for paths that use them.

**Comment by aroemen** [comment]
Additional note: this happens when loading the spec directly and not specifying a URL. I have not tested if this is an issue loading the spec via a url.

**Comment by fehguy** [comment]
Yes, this should be supported in 2.1.0-M2 of swagger-js.  I think there's an open issue, but if not, could you please open one in that project?

**Comment by webron** [comment]
@fehguy - https://github.com/swagger-api/swagger-js/issues/258 is opened as the global params and is closed in reference to https://github.com/swagger-api/swagger-js/issues/255. However https://github.com/swagger-api/swagger-js/issues/255 is talking about `$ref` in paths and not params under it, so this covered or not?

**Comment by fehguy** [comment]
suported as of swagger-client-2.1.3-M2
