### ISSUE TITLE
Download link missing for payloads that are not application/octet-stream

### ISSUE THREAD

**Issue by nick-coremont** [swagger-api/swagger-ui#9298]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: chrome
 - Version: latest
 - Method of installation: From NSwag
 - Swagger-UI version: latest
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

This PR, https://github.com/swagger-api/swagger-ui/pull/8579/files, caused a regression for payloads that are not `application/octet-stream`.

For example, given these Response Headers:
```
Content-Disposition: attachment; filename=users.csv; filename*=UTF-8''users.csv
Content-Length: 6460682
Content-Type: text/csv
```

the type of `content` on [this line](https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/response-body.jsx#L67) is `string`, and therefore `content.size === undefined`.

### Screenshots

![image](https://github.com/swagger-api/swagger-ui/assets/135146799/a92372b5-9992-4378-90f6-fb0e5df029de)

**Comment by char0n** [comment]
I can confirm, you're absolutely right! Thank you for catching this.

**Comment by char0n** [comment]
Closed by https://github.com/swagger-api/swagger-ui/pull/9343

**Comment by char0n** [comment]
Closed by https://github.com/swagger-api/swagger-ui/pull/9343
