### ISSUE TITLE
add response headers in output

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#930]
While shown in the response payload, the possible response headers are not shown from the swagger definition

**Comment by mohsen1** [comment]
Is this version 2.0 specific? Do you mean we should render `headers` object in a response? I've done something similar in Swagger Editor. https://github.com/swagger-api/swagger-editor/commit/ceaecfe0e505ea64a51e4a737c77535472223712

**Comment by webron** [comment]
I believe this is 2.0 specific since it refers to the definition and it didn't exist in prior versions.

**Comment by mohsen1** [comment]
The rendering part is done. When SwaggerJS issue 293 is fixed this will automatically work.
