### ISSUE TITLE
Docker unable to build versions 5.7.2+

### ISSUE THREAD

**Issue by jerryatcape** [swagger-api/swagger-ui#9305]
### Q&A 

 - OS: macOS
 - Browser: Chrome
 - Version: Chrome - 116.0.5845.187, npm - 9.8.1, node - 18.18.0
 - Method of installation: npm
 - Swagger-UI version: 5.7.2, 5.9.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

package.json dependencies:

                 "@auth0/auth0-react": "^1.10.1",
		"@date-io/date-fns": "^2.13.1",
		"@emotion/is-prop-valid": "^1.1.2",
		"@emotion/react": "^11.9.0",
		"@emotion/styled": "^11.8.1",
		"@fontsource/material-icons": "^4.5.4",
		"@fontsource/source-code-pro": "^5.0.8",
		"@mapbox/mapbox-gl-draw": "^1.3.0",
		"@mapbox/mapbox-gl-draw-static-mode": "^1.0.1",
		"@mui/base": "^5.0.0-alpha.80",
		"@mui/icons-material": "^5.6.2",
		"@mui/lab": "^5.0.0-alpha.81",
		"@mui/material": "^5.10.0",
		"@react-google-maps/api": "^2.12.1",
		"@reduxjs/toolkit": "^1.8.1",
		"@sentry/integrations": "^7.3.1",
		"@sentry/react": "^7.3.1",
		"@sentry/tracing": "^7.3.1",
		"@testing-library/jest-dom": "^5.16.4",
		"@testing-library/react": "13.2.0",
		"@turf/area": "^6.5.0",
		"@turf/bbox": "^6.5.0",
		"@turf/buffer": "^6.5.0",
		"@turf/difference": "^6.5.0",
		"@turf/helpers": "^6.5.0",
		"@turf/turf": "^6.5.0",
		"@types/mixpanel-browser": "^2.38.0",
		"axios": "^0.27.2",
		"browserslist": "^4.21.11",
		"date-fns": "^2.28.0",
		"history": "^5.3.0",
		"i18next": "^21.8.1",
		"i18next-browser-languagedetector": "^6.1.4",
		"i18next-http-backend": "^1.4.0",
		"lodash": "^4.17.21",
		"mapbox-gl": "^2.9.1",
		"maplibre-gl": "^2.4.0",
		"mixpanel-browser": "^2.45.0",
		"normalize.css": "^8.0.1",
		"papaparse": "^5.3.2",
		"react": "^18.1.0",
		"react-dom": "^18.1.0",
		"react-draggable": "^4.4.5",
		"react-dropzone": "^14.2.1",
		"react-fullstory": "^1.4.0",
		"react-hook-form": "^7.31.1",
		"react-hotjar": "^5.1.0",
		"react-hotkeys-hook": "^4.3.7",
		"react-i18next": "^11.16.9",
		"react-map-gl": "^7.0.16",
		"react-redux": "^8.0.1",
		"react-router-dom": "^6.3.0",
		"react-scripts": "5.0.1",
		"react-virtualized": "^9.22.3",
		"recharts": "^2.1.9",
		"storybook-addon-designs": "^6.3.1",
		"swagger-ui-react": "5.4.2",
		"tinycolor2": "^1.4.2",
		"typescript": "^4.6.4",
		"uuid": "^8.3.2",
		"web-vitals": "^1.1.2"

### Screenshots

<img width="597" alt="image" src="https://github.com/swagger-api/swagger-ui/assets/101132375/50d020d7-ca58-433d-b21f-dbc46dd9d907">

### How can we help?

Hi, I have a web application that generates a swagger-ui page for clients based on their apikey, but for some reason Docker is unable to successfully build versions 5.7.2 and 5.9.0. I get the following message:

npm ERR! Invalid: lock file's ramda@0.28.0 does not satisfy ramda@0.29.1
npm ERR! Missing: ramda@0.28.0 from lock file 

I see that the swagger-api has a ramda dependency and I have various versions of ramda 0.29.x in my package-lock.json, but I don't understand why is this complaining about having a newer version? One workaround I found was to directly install ramda using npm, but that still installs version 0.29.x, adds extra lines to my package.json, and I want to minimize the amount of dependencies in my package.json

My webapp builds and runs perfectly fine locally, it's only when I use Docker to build my code that I get this message.
I deprecated my swagger version to 5.4.2 and the error message went away when I built the container in Docker 

What cause this and will this be resolved in future swagger-ui versions?

I can provide more of my package.json and package-lock.json if requested but certain parts must be redacted 

Thanks

**Comment by char0n** [comment]
Hi @jerryatcape,

The `ramda` dep comes from [ApiDOM](https://github.com/swagger-api/apidom) that swagger-ui uses under the hood. From the information you provided I cannot tell you what is wrong as it's problem specific to your project.

I've just issued this PR https://github.com/swagger-api/apidom/pull/3384 that updates ramda to v0.29.1 for ApiDOM (before 0.29.0 was used). 

I can only speculate that during your install the npm re-conciliates the dependencies and only installs ramda@0.29.1 and fails to install ramda@0.28.0 (needed by other dependencies in your project). 0.29.x and 0.28.x are backward incompatible versions of ramda.

Sorry that all I've got from the information in the description of this issue.
