### ISSUE TITLE
Make swagger-ui usable as an npm dependency

### ISSUE THREAD

**Issue by rbelouin** [swagger-api/swagger-ui#931]
Hi all,

Is there a good reason for not defining `dist/swagger-ui.js` as the main file in `package.json`?

I would like to use Swagger UI in an existing project, and I don't understand why I should copy all swagger static files (and dependencies) into this project manually. I'd like to browserify all that stuff, and it does not seem possible currently.

Is it something you are planning to do? Should I submit a PR?

Thanks.

**Comment by fehguy** [comment]
Hi, I don't see why not.  if the dependencies are correct in package.json, it should be fine.  Please feel free to send a PR into develop_2.0

**Comment by rbelouin** [comment]
Thank you all, I'll give it a try this afternoon :)
