### ISSUE TITLE
webpack build output name is not legal

### ISSUE THREAD

**Issue by day-xue** [swagger-api/swagger-ui#9355]
- OS: macOS
 - Browser: chrome
 - Version:115
 - Method of installation:npm
 - Swagger-UI version:5.7.2
 - Swagger/OpenAPI version:Swagger 2.0,

![image](https://github.com/swagger-api/swagger-ui/assets/95938844/5dcc1be1-9e53-43ab-a617-9f8736704b4b)
webpack build output name  is not legal 
The chunk file cannot be found when I open it in my browser

**Comment by char0n** [comment]
Hi @day-xue,

I'm sorry but there is no build fragment named like that in official swagger-ui npm distribution package: https://unpkg.com/browse/swagger-ui@5.7.2/dist/.
