### ISSUE TITLE
Swagger 2.0: description appearing in group heading

### ISSUE THREAD

**Issue by domaindrivendev** [swagger-api/swagger-ui#937]
Seeing this in v2.1.4-M1. Not sure if it's a recently added feature but seems like odd behavior ...

Given this description:

    paths: {
      /Test: {
        get: {
          tags: [
            "Test"
          ],
          summary: "This comment will go into swagger to explain what the method does.",
          description: "this comment will end up in implementation notes BUT ALSO in the title",
          operationId: "Test_GetExample",
          consumes: [ ],
          produces: [
            "application/json",
            "text/json",
            "application/xml",
            "text/xml"
          ],
          responses: {
            200: {
              description: "OK",
             schema: {
                type: "string"
          }
        }
    }

The operation is displayed as follows:

![screen-shot](https://cloud.githubusercontent.com/assets/1434343/6232981/a1ee7d3a-b684-11e4-88c2-eab8fded314e.png)

**Comment by webron** [comment]
@fehguy may not like me for saying it, but... Heh.

**Comment by kinlane** [comment]
I thought it was odd too when I first discovered, but once you start using
to group endpoints, it really becomes handy.

Kin Lane (API Evangelist)
kinlane@gmail.com
@kinlane <https://twitter.com/kinlane>
--
apievangelist.com
*apisjson.org <http://apisjson.org/>*
apicommons.org
apistrategyconference.com
--

**Comment by webron** [comment]
@kinlane - there's a specific way to set the tag's description. Following this way can lead to conflicts.

**Comment by fehguy** [comment]
This is a bug.  Just opened this to track it:

https://github.com/swagger-api/swagger-js/issues/243

**Comment by fehguy** [comment]
addressed in swagger-client-2.1.5-M1
