### ISSUE TITLE
Add print CSS to be able to print to PDF

### ISSUE THREAD

**Issue by gmarziou** [swagger-api/swagger-ui#938]
Hi,

Would it be possible to define a print specific CSS that would expand all sections but hide the interactive ones (e.g. buttons, links) so that printing to a PDF file from browser would generate a static doc without any additional tool.

Thanks

**Comment by dmelo** [comment]
+1. It would be great.

**Comment by fehguy** [comment]
yes, someone can send a PR for this, it should be simple.

**Comment by fehguy** [comment]
This has been supported, please try master.
