### ISSUE TITLE
Add an option to not generate sandbox

### ISSUE THREAD

**Issue by brki** [swagger-api/swagger-ui#941]
For my use case (and from a blog post or two I've seen I know I'm not alone in this), I'd like to have the
nice swagger-ui interface, but without the try-it-out sandboxes.  I just want it to generate documentation, not an interactive API.

I'm not a javascript wizard, but from my glance at swagger-ui.js, it doesn't seem possible to pass an option to disable the generation of the sandbox section.

Did I miss something? Is there already a way to do this?

**Comment by webron** [comment]
Even though people ask about it repeatedly, we neglected documenting this option. All fixed now though! Please take a look at https://github.com/swagger-api/swagger-ui/blob/master/README.md#parameters, specifically the last parameter `supportedSubmitMethods`.

**Comment by brki** [comment]
Excellent, thank you!
