### ISSUE TITLE
 Unhandled Runtime Error in Next.js 13/14 App - Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Siddharth2212** [swagger-api/swagger-ui#9446]
This is my code giving this error: Unhandled Runtime Error
Error: Class extends value undefined is not a constructor or null

This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component

'use client';

import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';

type Props = {
  spec: Record<string, any>,
};

function ReactSwagger({ spec }: Props) {
  return <SwaggerUI spec={spec} />;
}

export default ReactSwagger;

"use_client" should be added at top of react component in the package. Please add it

**Comment by char0n** [comment]
Hi @Siddharth2212,

Please have a look at https://github.com/swagger-api/swagger-ui/wiki/Seamless-Integration-with-Bundlers-&-Test-Tools, specifically on https://github.com/char0n/swagger-ui-nextjs, which does provide full setup for SwaggerUI@5 + Next.js
