### ISSUE TITLE
idea: edit mode

### ISSUE THREAD

**Issue by seriousme** [swagger-api/swagger-ui#948]
Would be nice if one could use the UI to edit as well: e.g. when the edit mode switch is toggled you can:
- add a new path or modify/delete an existing path
- add a new operation or modify/delete an existing operation within a path
etc.

Then when the user hits the "Download spec" it downloads the modified swagger spec
Optionally an ACE editor could be added and the result could  completely replace Swagger Editor ;-)

**Comment by kinlane** [comment]
I've build a JS Swagger Editor that runs on Github. Its totally in alpha, and is completely separate from Swagger UI. While I think adding editor to UI is good idea, I'm not sure we should be adding more bloat to existing tool....but think we need a whole suite of different editors people can use. I will be publishing mine when it gets a little more mature.

**Comment by webron** [comment]
This is exactly why we have the Swagger-Editor. At some point, some of the functionality (in one way or another) would converge. We're definitely going to duplicate the functionality between the two (it's enough we have different UIs for the editor and this project which would converge).
