### ISSUE TITLE
Adjusting element style color of field variables using swagger-ui.css

### ISSUE THREAD

**Issue by Eric-Zaluzec-Vertiv** [swagger-api/swagger-ui#9481]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: latest
 - Method of installation: dist 
 - Swagger-UI version: latest
 - Swagger/OpenAPI version: latest

### Screenshots
![image](https://github.com/swagger-api/swagger-ui/assets/65047813/380b6698-0275-4139-ba58-3d1899e9b7eb)

### How can we help?
Hello! Quick question. Apologies if some terminology is incorrect here. 
I'd like to adjust the color of the [.swagger-ui .opblock-body pre.microlight](https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui.css#L1C121197-L1C121226) that gets pulled from the API json files. I can add `color: red !important;` to the swagger-ui.css file under the pre.microlight section to change the field names to red but the output variable colors remain the same (note in the screenshot, the red and green). 

Is there a way to modify these colors without building from source?
If not, could anyone provide help provide the source files to modify these fields? 
Thanks for any help & support on this.

**Comment by Eric-Zaluzec-Vertiv** [comment]
This seemed to work. There is probably a better way:
```
.swagger-ui .opblock-body pre span {
    color: #1e46db !important
}
```

![image](https://github.com/swagger-api/swagger-ui/assets/65047813/61cbc05f-9f8f-43d1-bd16-85125c0578f7)

**Comment by nhoktenz** [comment]
I am wondering if I only want to change the color of the number such as "code": 0 from your example from red to yellow? I don't want to change the whole block color, only the color of that number. Do you have any idea how to do it?
