### ISSUE TITLE
Missing lib

### ISSUE THREAD

**Issue by zhoubinjason** [swagger-api/swagger-ui#949]
Hello, my Swagger API has issues with GET. I saw this in Chrome developer tools.

Please take a look. Thank you very much.

HTTP Status 404 - /swagger/lib/underscore-min.map

type Status report

message /swagger/lib/underscore-min.map

description The requested resource is not available.

Apache Tomcat/6.0.43

**Comment by mohsen1** [comment]
When you open Chrome developer tools, it will make a request to source-map file if the source file has a source-map comment. however if you don't open Chrome dev tools this request will no be made so you don't need to worry about it.
 
@fehguy we can either add [underscore's source-map file](https://github.com/jashkenas/underscore/blob/master/underscore-min.map) or remove (this)[https://github.com/swagger-api/swagger-ui/blob/master/lib/underscore-min.js#L6) line to completely resolve this. Adding source-map can help debugging.
