### ISSUE TITLE
Release 4.20 with newer swagger client ?

### ISSUE THREAD

**Issue by ericproulx** [swagger-api/swagger-ui#9515]
### How can we help?
I was wondering if it's possible to release a new 4.X  with an update on swagger-client to at least ^3.20.6 ? 

We're facing this [issue](https://github.com/swagger-api/swagger-js/issues/1418) which was fixed in `v3.20.6` but latest 4.X is `3.19.8`.

We're using plain `swagger-ui-dist`.

Thanks

**Comment by char0n** [comment]
Hi @ericproulx, 

Unfortunately [v4](https://github.com/swagger-api/swagger-ui/tree/4.x) is no longer maintained. Only significant security issues will be considered. If you need special v4 release, I would recommend checking out https://github.com/swagger-api/swagger-ui/tree/4.x locally and creating a custom build or npm package. 

Sorry about the bad news.
