### ISSUE TITLE
HTML missing ids

### ISSUE THREAD

**Issue by regesmendes** [swagger-api/swagger-ui#9523]
As a user, I'd like to add the swagger-ui into my API having no errors coming from this package.

I noticed two missing ID's on HTML elements, due to error and warning messages in the console. Here's a screenshot:
![image](https://github.com/swagger-api/swagger-ui/assets/12453415/c1cff32d-c75e-42a1-b0a6-c5c0b263dcf7)

Found the references in the code at:
https://github.com/swagger-api/swagger-ui/blob/f9ecb01aa8afb686b3d0fcb04a249632f3af3436/src/standalone/plugins/top-bar/components/TopBar.jsx#L144

https://github.com/swagger-api/swagger-ui/blob/f9ecb01aa8afb686b3d0fcb04a249632f3af3436/src/core/plugins/oas3/components/servers.jsx#L75

**Comment by char0n** [comment]
There is an additional missing id in https://github.com/swagger-api/swagger-ui/blob/8c79e2a375eea268973ed6784bc68a646889d2d2/src/core/components/schemes.jsx#L45

**Comment by char0n** [comment]
Addressed by https://github.com/swagger-api/swagger-ui/pull/9563
