### ISSUE TITLE
Cannot get $res to work with paths

### ISSUE THREAD

**Issue by wodka** [swagger-api/swagger-ui#953]
I'm trying to split my API documentation into several files - but somehow nothing is showing up :(

Even if I try https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions.json it just does now show anything. (no error in development console of chrome)

(using v2.1.7-M1)

**Comment by fehguy** [comment]
path refs are not supported in swagger-js as of 2.1.8-M1.  Please file a ticket in swagger-js so you can get updates when it is.

**Comment by wodka** [comment]
oki, created the issue there as well - as a workaround I'm loading the data in the paths loop (ugly, but it works for now)

(around line 477 in swagger-client.js)
```javascript
  for(path in response.paths) {
    if(typeof response.paths[path] === 'object') {
      var httpMethod;
      // start workaround
      if(response.paths[path].$ref !== undefined) {
        if (response.paths[path].$ref.match(/#/)) {
            console.error('only external $refs are supported in paths');
            continue;
        }
        jQuery.ajax({
            url: response.paths[path].$ref,
            async: false,
            dataType: 'json',
            success: function (result) {
                response.paths[path] = result;
            }
        });
      }
      // end workaround
      for(httpMethod in response.paths[path]) {
```

**Comment by fehguy** [comment]
thanks for opening the issue.  The fix will be simple in swagger-js, if you want to send a PR to the develop_2.0 branch:

https://github.com/swagger-api/swagger-js/blob/master/src/js/resolver.js

**Comment by wodka** [comment]
sent the PR :)

**Comment by fehguy** [comment]
This should be supported with the latest develop_2.0 of swagger-client
