### ISSUE TITLE
AMD compliant packaging?

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#955]
Is it possible to package this project for AMD deployments?  Worth looking into it

**Comment by whitlockjc** [comment]
If you started packaging swagger-ui using browserify, you could get this for free.  Not suggesting it, just food for thought.

**Comment by mohsen1** [comment]
Swagger UI has CSS, Handlebars and HTML dependencies. We can't package all of that in a AMD/UMD module. What we can do is to provide bower packaging which it can contain all dependencies and a pointer to entry file (`index.html`)
