### ISSUE TITLE
Optional header parameter: Javascript error when not filling the header

### ISSUE THREAD

**Issue by fengelniederhammer** [swagger-api/swagger-ui#9550]
### Q&A (please complete the following information)
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 122
 - Method of installation: `org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0`
 - Swagger-UI version: `5.10.3` (at least that's what I infer from springdoc giving me `org.webjars:swagger-ui:5.10.3`)
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/dummy": {
      "get": {
        "tags": [
          "Dummy-controller"
        ],
        "description": "Dummy",
        "operationId": "dummy_1",
        "parameters": [
          {
            "name": "X-Request-ID",
            "in": "header",
            "description": "a dummy header",
            "required": false,
            "content": {
              "text/plain": {
                "schema": {}
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Dummy",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}

```

Swagger-UI configuration options:

None that I did myself - maybe Springdoc does something.

### To reproduce...

Given an endpoint definition with an optional header parameter (example is above)
When I click on "Try out" and "Execute" of that endpoint without filling the header parameter:
The "Loading" spinner keeps spinning infinitely and there is a JS error in the browser console.

The error from the console as text:
```
TypeError: i is undefined
    serialize content-serializer.js:12
    parameter_builders_header parameter-builders.js:89
    execute_buildRequest index.js:234
    execute_buildRequest index.js:201
    executeRequest actions.js:454
    systemThunkMiddleware index.js:174
    bindActionCreator Redux
    wrap_actions_executeRequest wrap-actions.js:33
    newAction system.js:175
    wrapWithTryCatch system.js:487
    actions_execute actions.js:501
    systemThunkMiddleware index.js:174
    bindActionCreator Redux
    execute wrap-actions.js:9
    newAction system.js:175
    wrapWithTryCatch system.js:487
    handleValidationResultPass execute.jsx:66
    handleValidationResult execute.jsx:80
    onClick execute.jsx:90
    React 11
        Rb
        Xb
        Yb
        Ze
        se
        jd
        lt
        Nb
        jd
        yc
        hd
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
        gg
        Hb
        gd
system.js:490:16
```

### Expected behavior

The request should be sent.

### Screenshots

![grafik](https://github.com/swagger-api/swagger-ui/assets/92720311/3d049e1a-3b9f-40c3-858f-c130842fe18a)

![grafik](https://github.com/swagger-api/swagger-ui/assets/92720311/46a3da13-3217-49c7-87fe-37c790cb4bc9)

**Comment by glowcloud** [comment]
Looking at OpenAPI 2.0, if we somehow get an undefined value for `path`, we'll replace the parameter in path with `undefined`, ex.: `https://petstore.swagger.io/v2/pet/undefined/uploadImage`.
And for `body`, it looks like we'll also have `undefined`, from `buildRequest` test:
```
{
  url: 'http://swagger.io/me',
  credentials: 'same-origin',
  headers: {},
  method: 'POST',
  body: undefined
}
```

**Comment by char0n** [comment]
Fixes to OpenAPI 3 definitions addressed upstream in [swagger-client@3.26.1](https://github.com/swagger-api/swagger-js/releases/tag/v3.26.1).

**Comment by char0n** [comment]
This is going to be available in next SwaggerUI release. Please reopen if it's still manifesting in new release.

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.12.2
