### ISSUE TITLE
SwaggerUI doesn't render response bodies for non-200 responses

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-ui#9556]
### Describe the bug you're encountering
When using `try it out` for an endpoint that returns a response with non-200 status code, the response body is not rendered.

### To reproduce...

1. Start a server that would return response with a body and 400 status code for a certain endpoint
2. Open Swagger Editor
3. Add a spec for this server
4. Send a request to the endpoint returning 400 response
5. See error

### Expected behavior

Renders a response body as it would for responses with 2XX status codes

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9555
