### ISSUE TITLE
spec: reducers set parameters as an array

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-ui#9566]
### Describe the bug you're encountering

The value set in `UPDATE_PARAM` reducer https://github.com/swagger-api/swagger-ui/blob/3a86443322c0cc3aab62c4006921779fc444476f/src/core/plugins/spec/reducers.js#L56 for multi-value parameters is an array, while the expected type of the set value is an Immutable List. 

### To reproduce...

1. Add a `console.log(List.isList(value))` to the reducer
2. Load the default Petstore definition
3. Scroll down to /pet/findByStatus
4. Try it out with at least one value chosen
5. Open console and see `false`

### Expected behavior

The value should be converted from an array to an Immutable List in the reducer.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9567
