### ISSUE TITLE
Empty query params cause extra "&" symbols to be added to the request URL

### ISSUE THREAD

**Issue by mpetkov** [swagger-api/swagger-ui#959]
@version v2.1.3-M1
If you have query params, if at least one of them is filled int then an "&" symbol is added for each query param regardless if its filled in. Here are screenshots to illustrate the problem:

If there are no params filled out, everything works as it should.
![noparams](https://cloud.githubusercontent.com/assets/8858458/6376737/6c19bb9a-bce5-11e4-8b30-9207eb842496.png)

If you fill in at least one param, there are extra "&" symbols added for the remaining params.
![oneparam](https://cloud.githubusercontent.com/assets/8858458/6376738/6c1a14fa-bce5-11e4-8cdd-dbebba1e8de7.png)

**Comment by kojoru** [comment]
I did a relevant pull request to swagger-js, let's see if it gets accepted.

**Comment by mohsen1** [comment]
This issue was fixed by #260.
