### ISSUE TITLE
SwaggerUI ctor produces console error

### ISSUE THREAD

**Issue by Christoph142** [swagger-api/swagger-ui#9598]
### Q&A (please complete the following information)
 - OS: Win
 - Browser: Vivaldi
 - Version: 6.5
 - Method of installation: [npm
 - Swagger-UI version: 5.11.4
 - Swagger/OpenAPI version: 3.0.3

### Describe the bug you're encountering
Calling SwaggerUI ctor results in "Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client"." error message.

Seems to have regressed from 5.11.3

**Comment by char0n** [comment]
Hi @Christoph142,

Yes we are aware of that. It was introduced in https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.0. This was the only way how we could support React@18 in backward compatible way. People still need to use SwaggerUI with React@16.8 or React@17. 

The warning that you're seeing is only present in development mode. In production the console will be clear.
