### ISSUE TITLE
Swagger Docs for dcm4chee-arc only shows subsets of APIs

### ISSUE THREAD

**Issue by vrindanayak** [swagger-api/swagger-ui#9645]
https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/

Rendering of all APIs was working properly until Friday 22.02

Tested with normal / private / incognito windows of Google Chrome / Firefox browsers.

Is https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.8 (Release date 23.02) impacting this in anyway?

**Comment by am-burban** [comment]
I noticed it, too with our spec. and managed to track it down: https://github.com/swagger-api/swagger-js/issues/3385

**Comment by vrindanayak** [comment]
We're currently working around this by : 
- download https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.7 
- start dist/index.html 
- use URL https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/ in the input field to see the complete API list

**Comment by am-burban** [comment]
Yeah, v5.11.7 is fine, because it uses the older swagger-client version (v3.25.1 vs. 3.25.1 in swagger-ui 5.11.8).

**Comment by amitkma** [comment]
We are also facing the same issue. We solved it temporarily by reverting to v5.11.7

**Comment by kiblik** [comment]
We have a similar problem at https://github.com/DefectDojo/django-DefectDojo/issues/9629

Check: https://demo.defectdojo.org/api/v2/oa3/swagger-ui/
- The example value for `POST /api/v2/credentials/` works fine
- but the example value for `POST /api/v2/engagements/` just says `"string"`

**Comment by char0n** [comment]
Hi everybody,

Quick status update: We're currently in the process of trying to solve this issue.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9658. ETA of release - next Monday

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.9

Please reopen is you still see more issues with your definitions.
