### ISSUE TITLE
Swagger not sending body in the post request.

### ISSUE THREAD

**Issue by steowens** [swagger-api/swagger-ui#965]
When I issue the POST request from the swagger UI, the body I am pasting in the body parameter is not getting posted.  When I look at the network request it is sending a POST with a content length of 0.

![screen shot 2015-02-25 at 4 14 22 pm](https://cloud.githubusercontent.com/assets/978310/6383804/71d95c74-bd09-11e4-8a47-b2b7eaa9788c.png)

**Comment by steowens** [comment]
Here is the swagger spec that the error occurs with:

{"swagger":"2.0","consumes":["application/json"],"produces":["application/json"],"info":{"version":"1.0.0","title":"Subscription Service","description":"Manages subscriptions between producers and consumers.","contact":{"name":"Disney Web Services","url":"https://confluence.disney.com/display/FND/Disney+Web+Services","email":"DTSS.Disney.Web.Services@disney.com"}},"paths":{"/entities":{"get":{"operationId":"queryEntities","summary":"List all ENTITY objects I can see","description":"Get secured entities for all ENTITY objects maintained by system","produces":["application/json"],"parameters":[{"in":"header","name":"Authorization","required":true,"type":"string","description":"Must be of the form 'SESSION {token}' where {token} is the session token returned from session service.  See response body for more details."}],"responses":{"200":{"description":"Successful operation","schema":{"type":"array","items":{"$ref":"#/definitions/Entity"}}},"401":{"description":"Either the authorization header is missing/badly formed, the token is not valid, or the token is expired, or session service is down.  See response body for more details."},"500":{"description":"An unexpected error occured or a service dependency is down.  See response body for more details.  See response body for more details."}}},"post":{"operationId":"createEntity","summary":"Create new ENTITY","description":"Creates a new entity, registers the secured entity for the entity, and assigns ownership to the caller session.","consumes":["application/json"],"produces":["application/json"],"parameters":[{"in":"header","name":"Authorization","required":true,"type":"string","description":"Must be of the form 'SESSION {token}' where {token} is the session token returned from session service."},{"in":"body","description":"The new Entity to create","schema":{"$ref":"#/definitions/Entity"}}],"responses":{"200":{"description":"Successful operation","schema":{"$ref":"#/definitions/Entity"}},"401":{"description":"Either the authorization header is missing/badly formed, the token is not valid, or the token is expired, or session service is down.  See response body for more details."},"403":{"description":"A permission check failed, input was invalid, or an integrity constraint would be violated if the operation were completed.  See response body for more details."},"500":{"description":"An unexpected error occured or a service dependency is down.  See response body for more details."}}}},"/entities/{name}":{"get":{"operationId":"getEntity","summary":"Get actual entity object by name","description":"Get full entity object with the given name","produces":["application/json"],"parameters":[{"in":"header","name":"Authorization","required":true,"type":"string","description":"Must be of the form 'SESSION {token}' where {token} is the session token returned from session service.  See response body for more details."},{"in":"path","name":"name","required":true,"type":"string","description":"Then name field of the entity to retrieve"}],"responses":{"200":{"description":"Successful operation","schema":{"$ref":"#/definitions/Entity"}},"401":{"description":"Either the authorization header is missing/badly formed, the token is not valid, or the token is expired, or session service is down.  See response body for more details."},"403":{"description":"Caller does not have permission to read entity.."},"404":{"description":"No entity with the given name was found in the system."},"500":{"description":"An unexpected error occured or a service dependency is down.  See response body for more details.  See response body for more details."}}},"delete":{"operationId":"deleteEntity","summary":"Delete entity object by name","description":"Delete entity object with the given name","produces":["application/json"],"parameters":[{"in":"header","name":"Authorization","required":true,"type":"string","description":"Must be of the form 'SESSION {token}' where {token} is the session token returned from session service.  See response body for more details."},{"in":"path","name":"name","required":true,"type":"string","description":"Then name field of the entity to delete"}],"responses":{"200":{"description":"Successful operation","schema":{"$ref":"#/definitions/Entity"}},"401":{"description":"Either the authorization header is missing/badly formed, the token is not valid, or the token is expired, or session service is down.  See response body for more details."},"403":{"description":"Caller does not have permission to delete entity.."},"404":{"description":"No entity with the given name was found in the system."},"500":{"description":"An unexpected error occured or a service dependency is down.  See response body for more details.  See response body for more details."}}},"put":{"operationId":"updateEntity","summary":"Update an existing entity object","description":"Update an existing entity object","produces":["application/json"],"parameters":[{"in":"header","name":"Authorization","required":true,"type":"string","description":"Must be of the form 'SESSION {token}' where {token} is the session token returned from session service.  See response body for more details."},{"in":"path","name":"name","required":true,"type":"string","description":"Then name field of the entity to delete"},{"in":"body","schema":{"$ref":"#/definitions/Entity"},"description":"The existing entity object with updated properties"}],"responses":{"200":{"description":"Successful operation","schema":{"$ref":"#/definitions/Entity"}},"401":{"description":"Either the authorization header is missing/badly formed, the token is not valid, or the token is expired, or session service is down.  See response body for more details."},"403":{"description":"Caller does not have permission to delete entity.."},"404":{"description":"No entity with the given name was found in the system."},"409":{"description":"The revision on the entity passed in does not match the revision on the entity in the system."},"500":{"description":"An unexpected error occurred or a service dependency is down.  See response body for more details.  See response body for more details."}}}}},"definitions":{"Feature":{"type":"object","properties":{"name":{"type":"string","description":"Unique identifier with respect to the Provider Entity for the feature."},"description":{"type":"string","description":"Describes what the feature is or does."},"onboardingLink":{"type":"string","description":"The link for onboarding onto this feature.","format":"url"},"subscriptionMetadataSchema":{"type":"object","description":"The json schema of the subscription metadata for the feature."}}},"Entity":{"id":"Entity","type":"object","properties":{"_id":{"type":"string","description":"Unique system identifier for the entity.  This will be assigned by the system and need not be provided by the client for new entities."},"revision":{"type":"integer","description":"Assigned by the system to track revisions, and coordinate predictable updates.  This will be assigned (and maintained) by the system and need not be provided by the client for new entities."},"name":{"type":"string","description":"A name that IS unique that may not be so friendly.","required":true},"type":{"type":"string","enum":["GUEST","CAST_MEMBER","APPLICATION","SERVICE","DEVICE"],"required":true},"featuresProvided":{"type":"array","items":{"$ref":"#/definitions/Feature"}}},"example":{"_id":"54ed3472cd3a24dc57679a2e","revision":0,"type":"SERVICE","name":"ACE","contactEmail":"DTSS.Disney.Web.Services@disney.com","description":"Fine grained dynamic, self service authorization provider.","featuresProvided":[{"name":"rights-management","description":"Register items to secure and assign permissions to manage those items to users, groups and based on other criteria.","onboardingLink":"https://beta.dws.cloud.corp.dig.com/","subscriptionMetadataSchema":null}]}},"SecuredEntityForEntitySchema":{"id":"SecuredEntityForEntity","type":"object","properties":{"domain":{"type":"string","description":"Ace domain name"},"containerId":{"type":"string","description":"Ace container for Entities in domain.","default":"Entities"},"instanceId":{"type":"string","description":"Name of the ENTITY"},"type":{"type":"string","description":"Secured entity type","default":"ENTITY"},"listingData":{"type":"object","properties":{"name":{"type":"string","description":"Name of the ENTITY, (matches instanceId)"},"description":{"type":"string","description":"A creator specified description for the entity"},"contactEmail":{"type":"string","format":"email","description":"Email to contact regarding this entity"},"type":{"type":"string","description":"Entity type","enum":["GUEST","CAST_MEMBER","APPLICATION","SERVICE","DEVICE"]},"featureNames":{"type":"array","description":"Names of features this entity provides.","items":{"type":"string"}}}}}}}}

**Comment by fehguy** [comment]
your body param is missing a name.  If you set it like such:

```json
          {
            "in": "body",
            "name": "body",
            "description": "The new Entity to create",
            "schema": {
              "$ref": "#/definitions/Entity"
            }
          }
```

Leaving this open as it should either (a) throw an error or (b) provide a default name.

**Comment by steowens** [comment]
Thanks!

**Comment by ebiven** [comment]
I'm getting the same 0-byte post but I've verified my parameters both have names.

```
    "/keyRequests": {
      "post": {
        "operationId": "createKeyRequest",
        "summary": "Create a key from an invite code",
        "description": "Create a key from an invite code.",
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "inviteCode",
            "description": "invite code",
            "in": "formData",
            "type": "string"
          },
          {
            "name": "note",
            "description": "note",
            "in": "formData",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "items": {
                "$ref": "#/definitions/keyRequests"
              }
            }
          }
        }
      }
    },
```

This path works fine:
```
    "/inviteCodeRequests": {
      "post": {
        "operationId": "createInviteCodeRequest",
        "summary": "Create an invite code",
        "description": "Create an invite code for an API Key.",
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "note",
            "description": "note",
            "in": "formData",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "items": {
                "$ref": "#/definitions/inviteCodeRequests"
              }
            }
          }
        }
      }
    },
```

**Comment by fehguy** [comment]
@ebiven I cannot reproduce your error.  I've run both specifications in a test environment and the values are definitely being submitted.  Please provide more information, including the versions, network panel debug info, etc.

**Comment by ebiven** [comment]
It looks like we're running a slightly older version, 2.1.0-alpha.7. I'll try updating to latest and see if that helps.

**Comment by fehguy** [comment]
Great, please do report back after updating

**Comment by ebiven** [comment]
Running v2.1.8-M1 we get the same result.

![image](https://cloud.githubusercontent.com/assets/369855/6421237/84460f26-be92-11e4-97cc-a9b29457a51e.png)

![image](https://cloud.githubusercontent.com/assets/369855/6421264/a5a6c610-be92-11e4-84fc-78383b3f0165.png)

**Comment by ebiven** [comment]
On further inspection it seems to be a problem with both routes. If there is data in the fields the body is 0 bytes. I hadn't noticed that before because the notes field in inviteCodeRequests is optional.

**Comment by MrLeebo** [comment]
I work with @ebiven and traced the issue to a problem when using `swagger-tools` and another bodyParser middleware. In effect, swagger-tools gets stuck streaming the request body for formData params but the stream has already ended.

This is not related to swagger-ui specifically. I opened the following issue with swagger-tools.
https://github.com/apigee-127/swagger-tools/issues/172

**Comment by webron** [comment]
Thanks for the info, @MrLeebo. I'm sure @whitlockjc will look into it.

**Comment by mohsen1** [comment]
I can't reproduce this. The initial issue was raised with invalid specs. If you're still having this issue with valid spec please comment here.

**Comment by itsprakash84** [comment]
Hey

I am facing the similar issue,  using the below version.
        <swagger-codegen.version>2.4.7</swagger-codegen.version>
        <swagger-annotations.version>1.5.22</swagger-annotations.version>

My yaml is below
      responses:
        '200':
          schema:
            $ref: '#/definitions/Employee'
          description: Success
definitions:
  Employee

what is wrong in this, as mentioned in above using type as "object" it is working.
Is there any way mentioning custom type say "Employee"

TIA
~~
Sathya

**Comment by webron** [comment]
@itsprakash84 please file a new issue following the issue template. This issue is from 2015 and is referring a very old version of Swagger UI which is no longer supported.
