### ISSUE TITLE
All examples, based on schema, shows as "string"

### ISSUE THREAD

**Issue by top1Dron** [swagger-api/swagger-ui#9652]
When an API consists of a huge number of endpoints, a "string" is displayed instead of examples created based on schemas. Reproduced using swagger-ui-dist files version 5.11.8. Displays correctly on other older versions

**Comment by amitkma** [comment]
:+1:

**Comment by amitkma** [comment]
We are also facing the same issue. Version 5.11.7 fixes it.

**Comment by design1online** [comment]
I'm seeing the same issue using hapi-swagger. Installing swagger-ui-dist@5.11.7 manually fixed it for us.

**Comment by yama-safi-charter-2024** [comment]
We are also experiencing the same problem and it took us 3 hours to figure out what was happening. We need this fixed so we dont include packages in our build that we dont rely on.

**Comment by char0n** [comment]
Hi everybody,

This is related to https://github.com/swagger-api/swagger-ui/issues/9645 and has been addressed in https://github.com/swagger-api/swagger-ui/pull/9658.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.9. 

Please reopen is you still see the issues with your definitions.
