### ISSUE TITLE
errors rendering non-existing schemas when defaultModelRendering is set to model 

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-ui#9666]
### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.1.0
info:
  title: Empty response test case
  version: '1'
paths:
  '/':
    get:
      responses:
        '200':
          description: no content
        '201':
          description: no schema but an example
          content:
            application/json:
              example:
                foo: bar
        '202':
          description: no schema but examples
          content:
            application/json:
              examples:
                first:
                  value:
                    foo: bar
                second:
                  value:
                    baz: foobar
        '203':
          description: no schema no example
          content:
            application/json: {}
```

Swagger-UI configuration options:
```js
SwaggerUI({
    url: "./examples/oas31-empty-response.yaml",
    dom_id: "#swagger-ui",
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    defaultModelRendering: "model",
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
})
```

### Describe the bug you're encountering

Swagger UI tries to render schemas when no schema has been provided, if `defaultModelRendering` is set to `model`. This causes errors: 

<img width="485" alt="error01" src="https://github.com/swagger-api/swagger-ui/assets/44094416/e94419fe-33a4-4f76-a38c-c15f8c7f5912">

and renders the `Could not render ModelWrapper` message:

<img width="773" alt="error02" src="https://github.com/swagger-api/swagger-ui/assets/44094416/dc843b94-c908-4c58-8cda-90f0bb813713">

If we switch to the example tab, we will correctly not be able to switch back to schema:

<img width="625" alt="error03" src="https://github.com/swagger-api/swagger-ui/assets/44094416/c764f8c6-202a-49de-8d56-e72bd3964de2">

### To reproduce...

1. Load the provided specification with `defaultModelRendering` set to `model`
2. Expand the `GET /` operation
3. See the `Could not render ModelWrapper` message and errors in console 

### Expected behavior

Swagger UI should not render the schema tab if no schema has been provided.

**Comment by char0n** [comment]
So this is related to the fact that we're trying to render (forcing with configuration) a component that it's not event accessible from standard UI workflow.

Sensible thing to do would be ignoring `defaultModelRendering=model` when there is no `schema`.

**Comment by glowcloud** [comment]
Addressed by https://github.com/swagger-api/swagger-ui/pull/9667

**Comment by char0n** [comment]
Released in https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.10
