### ISSUE TITLE
swagger-ui adds "fake" parameter to form-data payload

### ISSUE THREAD

**Issue by z0mt3c** [swagger-api/swagger-ui#968]
I just noticed that swagger-ui adds a "fake" attribute to my form-data payload in case the optional file field is empty? Is this really necessary? Looks quite strange :-)

https://github.com/swagger-api/swagger-ui/blob/05588bb6697387abe219a2186ae4e082ea703690/src/main/coffeescript/view/OperationView.coffee#L213

Version: 2.1.8-M1

Schema:

```json
"/test/fileUpload": {
    "post": {
    	"tags": ["api"],
    	"parameters": [{
    		"required": false,
    		"type": "string",
    		"name": "namaae",
    		"in": "formData"
    	}, {
    		"required": false,
    		"type": "file",
    		"name": "file",
    		"in": "formData"
    	}],
    	"consumes": ["multipart/form-data"],
    	"responses": {
    		"default": {}
    	},
    	"produces": ["application/json"]
    }
}
```

Payload:

Request payload
```
------WebKitFormBoundaryNfpwuLQsoticyIKZ
Content-Disposition: form-data; name="name"

adsf
------WebKitFormBoundaryNfpwuLQsoticyIKZ
Content-Disposition: form-data; name="fake"

true
------WebKitFormBoundaryNfpwuLQsoticyIKZ--
```

**Comment by fehguy** [comment]
interesting, that may be a remnant from some development.  Will confirm why it's there and get it removed.

**Comment by mohsen1** [comment]
@fehguy Do you know why we're doing this?
https://github.com/swagger-api/swagger-ui/blob/master/src/main/coffeescript/view/OperationView.coffee#L279-L280

**Comment by fehguy** [comment]
I will dig in soon but my understanding is it can go away. I'll assign to myself.
