### ISSUE TITLE
Does swagger-ui 5.x support rendering AsyncAPIs?

### ISSUE THREAD

**Issue by whoareyoukid** [swagger-api/swagger-ui#9731]
### Q&A (please complete the following information)
 - OS: Windows 11
 - Browser: Chrome
 - Version: 122
 - Method of installation: npm
 - Swagger-UI version: 5.12.0
 - Swagger/OpenAPI version: asyncapi 2.0.0

### Content & configuration

Swagger/OpenAPI definition:
```json
{
  "asyncapi": "2.0.0",
  "info": {
    "title": "Account Service",
    "version": "1.0.0",
    "description": "Manages user accounts in the system.\n",
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": {
    "production": {
      "url": "mqtt://test.mosquitto.org",
      "protocol": "mqtt",
      "description": "Test MQTT broker"
    }
  },
  "channels": {
    "user/signedup": {
      "subscribe": {
        "operationId": "emitUserSignUpEvent",
        "message": {
          "$ref": "#/components/messages/UserSignedUp"
        }
      }
    }
  },
  "components": {
    "messages": {
      "UserSignedUp": {
        "name": "userSignedUp",
        "title": "User signed up event",
        "summary": "Inform about a new user registration in the system",
        "contentType": "application/json",
        "payload": {
          "$ref": "#/components/schemas/userSignedUpPayload"
        }
      }
    },
    "schemas": {
      "userSignedUpPayload": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string",
            "description": "foo"
          },
          "lastName": {
            "type": "string",
            "description": "bar"
          },
          "email": {
            "type": "string",
            "format": "email",
            "description": "baz"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}
```

Swagger-UI configuration options:
```js
SwaggerUI({
        spec: apiSpec,
        defaultModelsExpandDepth: -1,
        dom_id: '#container',
        defaultModelRendering: 'model',
        showExtensions: true,
        deepLinking: true
})
```

### How can we help?
With the above specification and configuration, nothing gets rendered. Is asyncapi 2.x supported by swagger-ui? If so, are there any specific configuration settings that I am missing? What exactly is the issue? I am under the impression that since swagger editor renders this perfectly, I would be able to achieve the same with swagger-ui. Please let me know if I am wrong or if there is another way to achieve this.

**Comment by char0n** [comment]
Hi @whoareyoukid,

It does't support AsyncAPI out of the box.

But SwaggerUI@5 integrates with SwaggerEditor@5 preview plugins so you can easily achieve rendering AsyncAPI definitions via SwaggerUI. Read more here: https://github.com/swagger-api/swagger-editor/tree/next?tab=readme-ov-file#using-preview-plugins-in-swaggerui
