### ISSUE TITLE
Incorrect api path

### ISSUE THREAD

**Issue by tapan-d-thakkar** [swagger-api/swagger-ui#979]
Hi, I have downloaded swagger from https://github.com/swagger-api/swagger-ui. I am able to see swagger API page successfully. But when I try to execute any API, its generating incorrect URI.

for eg: my app is running on http://localhost:8080/app, swagger api docs url is http://localhost:8080/app/api-docs.

I have one API to fetch client details as http://localhost:8080/app/client/{id}, but when i execute that API using swagger it generates url as http://localhost:8080/app/app/client/{id}.

I am not sure why its adding /app twice, i tried to debug code, in this method of swagger-client.js
SwaggerOperation.prototype.urlify = function(args), value of this.resource.basePath is coming like http://localhost:8080/app/app/ and it appends client/{id} to it which is wrong.

Let me know if i have to make any changes for this.

Thanks.

**Comment by webron** [comment]
What's your `basePath` and operation path as described by Swagger?

**Comment by tapan-d-thakkar** [comment]
@Ron, this is resource url http://localhost:8080/app/api-docs/client, below is the json response ...
```json
{
    "apiVersion": "1.4.0-SNAPSHOT",
    "swaggerVersion": "1.2",
    "basePath": "app",
    "resourcePath": "/client",
    "produces": [
        "application/json"
    ],
    "consumes": [
        "application/json"
    ],
    "apis": [
        {
            "path": "/client/{id}",
            "operations": [
                {
                    "method": "GET",
                    "summary": "Get client by Id.",
                    "notes": "",
                    "type": "clientProxy",
                    "nickname": "findById",
                    "parameters": [
                        {
                            "name": "Username",
                            "description": "Username of the acting user",
                            "required": true,
                            "type": "string",
                            "paramType": "header",
                            "allowMultiple": false
                        },
                        {
                            "name": "id",
                            "description": "Id of the requested client",
                            "required": true,
                            "type": "integer",
                            "format": "int64",
                            "paramType": "path",
                            "allowMultiple": false
                        },
                        {
                            "name": "verbose",
                            "description": "Whether or not to return sub-objects; defaults to false",
                            "required": false,
                            "type": "boolean",
                            "paramType": "query",
                            "allowMultiple": false
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 200,
                            "message": "Success"
                        },
                        {
                            "code": 400,
                            "message": "Invalid Parameter supplied"
                        },
                        {
                            "code": 404,
                            "message": "Site with specified id not found."
                        },
                        {
                            "code": 500,
                            "message": "Internal Server Error"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by webron** [comment]
That's not a valid `basePath` for Swagger 1.2 as it has to be a full URL.

What happens here is that swagger-ui takes the URL where the /api-docs is hosted (http://localhost:8080/app in this case), appends the basePath (/app) and the path of the operation itself, and that's how you end up with the double /app.

**Comment by tapan-d-thakkar** [comment]
Thanks @Ron

So I need to return http://localhost:8080/app in basePath is that what you
are saying by full path ?

Or as you mentioned it taks /api-docs url and appends basePath and then
operation, so if I return empty basePath string will it work ?

**Comment by webron** [comment]
It's better that you use http://localhost:8080/app as the value. In Swagger 2.0  you have nicer control over it.

**Comment by tapan-d-thakkar** [comment]
@Ron,

I have taken latest swagger-ui code from master and I have configured 1.3.12 in maven settings for swagger. Also, to keep http://localhost:8080/app, will not be a good option, as basePath will change for different env, so is there a way to configure it dynamically ?

**Comment by webron** [comment]
Can you upgrade to swagger-core 1.5.X?

**Comment by tapan-d-thakkar** [comment]
@Ron, as per maven repo, http://mvnrepository.com/artifact/com.wordnik/swagger-core_2.10, I see latest version is 1.3.12. can you please confirm once this is correct or not ?

**Comment by webron** [comment]
Please take a look here - http://mvnrepository.com/artifact/com.wordnik/swagger-core. 1.5.X has switched to Java from Scala, and so does not contain the scala version in its name anymore (2.10, 2.11 and so on).

**Comment by tapan-d-thakkar** [comment]
@Ron, 

I will try to migrate my current implementation to 1.5.x, and give you feedback but is there any documentation / particular scenario which i need to take care in migration process ?

**Comment by webron** [comment]
Unfortunately not yet, but there are the samples for 1.5.

**Comment by tapan-d-thakkar** [comment]
@Ron,

As you mentioned, i have changed maven dependencies version to 1.5.2-M1, but still i am when i execute api url http://localhost:8080/app/api-docs/client, still i am getting swaggerVersion as 1.2 not 2.0

**Comment by ron** [comment]
@tapan-d-thakkar mentions work just like twitter, use @webron instead

**Comment by webron** [comment]
@tapan-d-thakkar - if you're getting a response from .../api-docs, then you didn't update your dependencies properly. Swagger 2.0 doesn't use the /api-docs structure anymore.

Run `mvn tree:list` to see which dependencies you actually pull in.

**Comment by tapan-d-thakkar** [comment]
@webron I did clean build, now i see `swagger-annotations-1.5.2-M1.jar, swagger-jaxrs-1.5.2-M1.jar. swagger-core-1.5.2-M1.jar` in my libs, but if I execute url http://localhost:8080/app/api-docs I get this error `java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forPackage(Ljava/lang/String;[Ljava/lang/ClassLoader;)Ljava/util/Set;`. I have this `reflections-0.9.9.jar` on my classpath.

I tried to execute `http://localhost:8080/app/swagger.json`, but for this server response is `not found`

**Comment by webron** [comment]
Can you share the output of `mvn dependency:tree`? You can email me directly if you don't want to share it here.

**Comment by webron** [comment]
@tapan-d-thakkar - any updates on this?

**Comment by tapan-d-thakkar** [comment]
@webron Ron, I resolved this issue. I updated swagger-ui project to version 2.0, still backend runs on 1.2. but that resolved the issue. Thanks so much for the help.

**Comment by webron** [comment]
@tapan-d-thakkar - great, thanks for the update.
