### ISSUE TITLE
Errors displaying schemas with oneOf

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-ui#9790]
### Q&A (please complete the following information)
 - OS: macOs
 - Browser: chrome
 - Version: 123.0.6312.107 
 - Swagger-UI version: 5.14.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Test
  description: 'Test'
  license:
    name: 'Apache 2.0'
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: '1.0'
servers:
  -
    url: 'https://localhost:8000'
components:
  schemas:
    OneOfParent:
      title: OneOfParent
      properties:
        additionalData:
          oneOf:
            -
              $ref: '#/components/schemas/FirstOneOf'
            -
              $ref: '#/components/schemas/SecondOneOf'
            -
              $ref: '#/components/schemas/ThirdOneOf'
      type: object
    FirstOneOf:
      title: FirstOneOf
      type: object
      allOf:
        -
          $ref: '#/components/schemas/OneOfParent'
        -
          properties:
            numberProp:
              type: number
              example: '1'
          type: object
    SecondOneOf:
      title: SecondOneOf
      type: object
      allOf:
        -
          $ref: '#/components/schemas/OneOfParent'
        -
          properties:
            person:
              properties:
                id:
                  type: string
              type: object
          type: object
    ThirdOneOf:
      title: ThirdOneOf
      type: object
      allOf:
        -
          $ref: '#/components/schemas/OneOfParent'
        -
          properties:
            person:
              properties:
                id:
                  type: string
                name:
                  type: string
                surname:
                  type: string
              type: object
          type: object

```

### Describe the bug you're encountering

There are issues displaying OneOf objects in Swagger UI. It works properly in Swagger Editor. 

In Swagger UI:

<img width="546" alt="Screenshot 2024-04-08 at 14 58 16" src="https://github.com/swagger-api/swagger-ui/assets/44094416/030a8431-b801-41be-bb2c-26b4f4f3def2">

In Swagger Editor:

<img width="570" alt="Screenshot 2024-04-08 at 14 57 25" src="https://github.com/swagger-api/swagger-ui/assets/44094416/e20c841f-1127-4b00-9f07-bd46deefdbbd">

### To reproduce...

1. Load the specification
2. Expand `OneOfParent`
3. See that the names of the schemas are different than Swagger Editor and only include the referenced schema properties

### Expected behavior

The names should be displayed the same way as in Swagger Editor.

**Comment by glowcloud** [comment]
The issue on the surface looks like it was introduced by https://github.com/swagger-api/swagger-ui/commit/7300e6c04ec9248f0d7c5c4e0674572847fcd213 but it seems like it actually uncovered a different issue, which you can see in Swagger Editor. 

The names there are displayed correctly:

<img width="556" alt="Screenshot 2024-04-08 at 15 35 55" src="https://github.com/swagger-api/swagger-ui/assets/44094416/73b7e0a5-cba8-4a6b-ae74-98f066c14d5a">

but if we actually expand the schemas:
<img width="761" alt="Screenshot 2024-04-08 at 15 38 58" src="https://github.com/swagger-api/swagger-ui/assets/44094416/861eacdb-a455-47e1-a776-6377cbd447fd">

you can see that `additionalData` from FirstOneOf is missing and the references are also not resolved properly. 

The resolved subtree for OneOfParent:
```
{
    "title": "OneOfParent",
    "properties": {
        "additionalData": {
            "oneOf": [
                {
                    "$ref": "http://localhost:3200/examples/regressionJson.json#/components/schemas/OneOfParent",
                    "properties": {
                        "numberProp": {
                            "type": "number",
                            "example": "1"
                        }
                    },
                    "type": "object",
                    "title": "FirstOneOf",
                    "$$ref": "http://localhost:3200/examples/regressionJson.json#/components/schemas/FirstOneOf"
                },
                {
                    "$ref": "http://localhost:3200/examples/regressionJson.json#/components/schemas/OneOfParent",
                    "properties": {
                        "person": {
                            "properties": {
                                "id": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object",
                    "title": "SecondOneOf",
                    "$$ref": "http://localhost:3200/examples/regressionJson.json#/components/schemas/SecondOneOf"
                },
                {
                    "$ref": "http://localhost:3200/examples/regressionJson.json#/components/schemas/OneOfParent",
                    "properties": {
                        "person": {
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "surname": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object",
                    "title": "ThirdOneOf",
                    "$$ref": "http://localhost:3200/examples/regressionJson.json#/components/schemas/ThirdOneOf"
                }
            ]
        }
    },
    "type": "object"
}
```

We can see both the resolved `$$ref` and unresolved `$ref` - because of this the names are different and we only get the schema under `$ref`, as that was one of the changes in this commit https://github.com/swagger-api/swagger-ui/commit/7300e6c04ec9248f0d7c5c4e0674572847fcd213

If we expand FirstOneOf first and then OneOfParent, we'll get this:

<img width="757" alt="Screenshot 2024-04-08 at 15 40 48" src="https://github.com/swagger-api/swagger-ui/assets/44094416/3682260c-9275-4122-a7ac-ca200f86873d">

This looks to me like an issue with the resolver - perhaps with the allOf plugin which, if I remember correctly, shouldn't keep the `$ref`.

**Comment by glowcloud** [comment]
In theory, we could pass `fn` to our `Model` component and use `mergeJsonSchema` - in place of
https://github.com/swagger-api/swagger-ui/blob/6e91056859edc81ee57c18594ebdb85dd50e8904/src/core/components/model.jsx#L72-L82
have something like this:
   ```
 if ($ref) {
      const refName = this.getModelName($ref)
      const refSchema = this.getRefSchema(refName)
      if (Map.isMap(refSchema)) {
        schema = fromJS(fn.mergeJsonSchema(schema.toJS(), refSchema.toJS()))
        name = name || refName
        if (!$$ref) {
          schema = schema.set("$$ref", $ref)
          $$ref = $ref
        }
      } else if (!$$ref) {
        schema = null
        name = $ref
      }
    }
```
this will work for the spec in the issue:
<img width="921" alt="Screenshot 2024-04-09 at 09 59 53" src="https://github.com/swagger-api/swagger-ui/assets/44094416/2ebe6625-5fd8-4bd1-bdf3-bec4e4748f2b">

But it will not solve it for cases where we have more than one circular reference, as the `$ref` property will get replaced by the next defined `$ref`. To illustrate it, we can have this spec:
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Test",
    "description": "Test",
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://localhost:8000"
    }
  ],
  "components": {
    "schemas": {
      "Parent": {
        "title": "Parent",
        "properties": {
          "parentData": {
            "$ref": "#/components/schemas/OneOfParent"
          }
        },
        "type": "object"
      },
      "OneOfParent": {
        "title": "OneOfParent",
        "properties": {
          "additionalData": {
            "oneOf": [
              {
                "$ref": "#/components/schemas/FirstOneOf"
              }
            ]
          }
        },
        "type": "object"
      },
      "FirstOneOf": {
        "title": "FirstOneOf",
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/Parent"
          },
          {
            "$ref": "#/components/schemas/OneOfParent"
          },
          {
            "properties": {
              "numberProp": {
                "type": "number",
                "example": "1"
              }
            },
            "type": "object"
          }
        ]
      }
    }
  }
}
```
and our rendered model will be missing `parentData`:
<img width="829" alt="Screenshot 2024-04-09 at 09 56 44" src="https://github.com/swagger-api/swagger-ui/assets/44094416/9405986e-faf4-4c7a-9d5f-1434b49ae3d6">

If we swap the order of references in `allOf` in `FirstOneOf`:
  ```
 "FirstOneOf": {
        "title": "FirstOneOf",
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/OneOfParent"
          },
          {
            "$ref": "#/components/schemas/Parent"
          },
          {
            "properties": {
              "numberProp": {
                "type": "number",
                "example": "1"
              }
            },
            "type": "object"
          }
        ]
      }
```
This time `additionalData` will be missing:
<img width="940" alt="Screenshot 2024-04-09 at 09 57 25" src="https://github.com/swagger-api/swagger-ui/assets/44094416/a3b320c9-9bff-465a-9cb4-7c178eeff2d5">

It looks to me like we would somehow need to keep these unresolved `$refs` in an array (as `$ref: [<unresolved_ref_0>, <unresolved_ref_1>, ...]`) instead of only having a string there, that gets replaced when we get another `$ref`

**Comment by char0n** [comment]
- we will assume that every schema with $ref field and one or more additional fields is a result of allOf keyword merge
- given that Reference Object cannot have any additional fields than $ref, the assumption is almost correct
- we will use Immutable.mergeDeep to merge the referenced schema with the referencing one (which makes it compatible with swagger-client `allOf` specmap plugin)
- this can introduce possible circular references (cycles) again into the deferenced tree

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9794
