### ISSUE TITLE
Ability to sort parameters by name or type

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-ui#980]
For APIs with a lot of parameters it would be useful to let the user sort the parameters either by name or by type (headers together for example).

**Comment by fehguy** [comment]
i really don't know that we want this.  Parameters are ordered by the server in an array intentionally.  If we allow sorting, it should be an option, not the default.

**Comment by mohsen1** [comment]
If it's a "nice to have" lets move it to Future. I guess it should be like when you click on column header it sorts based on column

**Comment by fehguy** [comment]
i think this belongs as part of a redesign.  I'm going to close it as an issue.
