### ISSUE TITLE
Make `parseSearch` and `serializeSearch` compliant with the WHATWG specification

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-ui#9804]
Right now the `parseSearch` and `serializeSearch` functions in `utils` use custom string parsing:
https://github.com/swagger-api/swagger-ui/blob/1a22b316c9cf5ade5d1bbd12076b77b0c35258b5/src/core/utils/index.js#L607-L633

Instead, we should move to using `URLSearchParams` which will make these functions compliant with the [WHATWG specification](https://url.spec.whatwg.org/).

The functions should be rewritten into:
```
export const parseSearch = () => {
  const searchParams = new URLSearchParams(win.location.search)
  return Object.fromEntries(searchParams)
}

export const serializeSearch = (searchMap) => {
  const searchParams = new URLSearchParams(Object.entries(searchMap))
  return String(searchParams)
}
```
Based on: https://github.com/swagger-api/swagger-ui/pull/9722#issuecomment-2047613658

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9809#pullrequestreview-1994734321

**Comment by glowcloud** [comment]
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.15.2
