### ISSUE TITLE
Add type casting for Swagger UI configuration options

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-ui#9808]
When the configuration options are defined in the URL query parameters, we are actually getting `strings`. This causes issues if the value of the configuration parameter should not be a `string`.

For example, for `deepLinking` we should actually have a `boolean` value, but instead we'll have a string `"true"`. This means that this configuration option won't actually be activated.

To fix this, we need to cast values into proper types if we can, ex. for `number` and `boolean`. We won't be parsing `object` and `array` type values.

**Comment by char0n** [comment]
Le'ts concentrate the type casting int `config/type-cast` module.

```
const Boolean = (string) => boolean

Map
 - syntaxHighlight.activated: Boolean
 
```

**Comment by glowcloud** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9829

**Comment by glowcloud** [comment]
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.16.0
