### ISSUE TITLE
Swagger UI doesn't send Authorization header

### ISSUE THREAD

**Issue by Ma-ve** [swagger-api/swagger-ui#981]
It authenticates properly, I get an authorization_code, it then posts the required data to the server, and retrieves an access_token. However, Swagger UI in no form tries to send the header that should contain Authorization: Bearer 123abc. 

Request headers:
```
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,nl;q=0.6
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:GET
Connection:keep-alive
DNT:1
Host:rest.local
Origin:http://localhost
Referer:http://localhost/swagger/
```
In the `onOAuthComplete()` function, it properly returns the following:

`console.log('Authorization: ' + 'Bearer ' + b + ', header');`

As this would be required by:

`window.authorizations.add(oauth2KeyName, new ApiKeyAuthorization('Authorization', 'Bearer ' + b, 'header'));`

I can't figure it out. What am I missing?

**Comment by fehguy** [comment]
is this swagger spec 1.2 or 2.0?  Both have security definitions which are "no security required" but the syntax is slightly different.  Would need to see your spec.

**Comment by Ma-ve** [comment]
Swagger 1.2: http://pastebin.com/rydPpsz8.

**Comment by fehguy** [comment]
that is your resource listing.  Can you show what an api declaration looks like?  You should have something like this:

```
        {
          "method": "DELETE",
          "summary": "Deletes a pet",
          "notes": "",
          "type": "void",
          "nickname": "deletePet",
          "authorizations": {
            "oauth2": [
              {
                "scope": "write:pets",
                "description": "modify pets in your account"
              }
            ]
          },
          "parameters": [
            {
```

If you don't have the `authorizations` object, it won't try to send them.

**Comment by Ma-ve** [comment]
Apologies. This is the /products listing, freshly generated:

http://pastebin.com/mVGpFkzT

**Comment by fehguy** [comment]
That looks fine. Can you please confirm what version of swagger ui you are using?  Should be at the top of swagger-ui.js.

**Comment by Ma-ve** [comment]
@version v2.1.4-M1

**Comment by fehguy** [comment]
Sorry for the lag.  Did you get this sorted out?

**Comment by mohsen1** [comment]
I can't reproduce this with petstore and current master

**Comment by fehguy** [comment]
Your spec has been removed from pastebin--please reopen if this is still an issue.

**Comment by ahallora** [comment]
How was this solved? 

I have a swagger 2.0 spec with apiKey defined as securityDefinition and set to a api endpoint. It works in the Swagger Editor where the apiKey is sent in the authorization header. However, when I test the same spec in the Swagger UI no authorization headers are sent. 

Any help is appreciated... 😄

**Comment by Ma-ve** [comment]
I don't recall, but I do know this:

If you try and do an cross domain request from Swagger (from http://localhost to https://test.something.com/ for example), there's always a preflight request sent. This preflight request is always an `OPTIONS` on the same URL you're going to do `GET`/`POST`/whatever on. `OPTIONS` does *not* and will not send any Authorization headers.

**Comment by ahallora** [comment]
I eventually figured out why the authorization header wasn't set in Swagger UI. The javascript initiated with swagger UI was not set up properly. Thanks to [darenleeweber](https://github.com/darrenleeweber) for point out my obvious flaws, see  https://github.com/swagger-api/swagger-ui/issues/1244#issuecomment-245638234 . 😄 

```javascript
var authKey = new ApiKeyAuthorization('Authorization', 'Bearer ' + yourtoken, 'header');
window.authorizations.add('the-name-of-your-swagger-security-definition', authKey);
```

Just in case somebody else (like me) stumbles upon this old thread looking for a solution. 👍
