### ISSUE TITLE
Address getting configUrl value from options in query

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-ui#9819]
According to our [docs](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md), the setting for getting configuration options from an URL is `configUrl`.

In our code, we have the following for getting the `configUrl` from our defined options:
https://github.com/swagger-api/swagger-ui/blob/68eb346a2366d1035d2d08a3aae138bb5cff075b/src/core/index.js#L64 

We need to investigate whether this `config` option is expected somewhere else or if we can safely change this to 
```js
const configURL = mergedOptions.configUrl 
```
as `mergedOptions` should have the `configUrl` from `queryOptions`, if it was defined there.

If we do this change, we need to properly document it, as some users might be using `config` instead of `configUrl`.

**Comment by glowcloud** [comment]
It looks like this line
```js
 const configURL = queryOptions.config ?? mergedOptions.configUrl 
```
was added in https://github.com/swagger-api/swagger-ui/commit/8130168c97ac78e70e3cbe0d3afc6b10679052cf as:
```js
let configUrl = queryConfig.config || constructorConfig.configUrl
```

It actually included this logic that was there before, added in https://github.com/swagger-api/swagger-ui/commit/f22a6289345a3025650c687ab482a9e1a6369b07: 
https://github.com/swagger-api/swagger-ui/blob/f22a6289345a3025650c687ab482a9e1a6369b07/src/plugins/configs/index.js#L46-L47

It also looks like it was always just `configUrl` that was mentioned in the docs, here's the commit where it was added: https://github.com/swagger-api/swagger-ui/commit/8e80ca9583fc9da17e6095c568390f4721173587

In my opinion, we can remove the ```queryOptions.config``` - the value should be specified in the `configUrl`option and we should have it in `mergedOptions` at this point.

**Comment by char0n** [comment]
> These options can be used altogether, the order of inheritance is following (from the lowest priority to the highest):
`swagger-config.yaml` -> config passed to `SwaggerUIBundle` -> config fetched from `configUrl` passed to `SwaggerUIBundle` -> config fetched from URL passed as a query parameter `config`

So this at least does confirm my assumptions in https://github.com/swagger-api/swagger-ui/issues/9818

**Comment by char0n** [comment]
> - change default configs in `swagger-config.yaml` *Note: after changing, the project must be re-built*

This confirms my stipulation that it's a compile time thing

**Comment by char0n** [comment]
> There are three options of passing config:
- add a query parameter `config` with URL to a server where the configs are hosted. For ex. http://petstore.swagger.io/?configs=http://localhost:3001/config.yaml
- add a config `configUrl` with URL to SwaggerUIBundle

Notice the `config` vs `configs` discrepancy.

**Comment by glowcloud** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9840
