### ISSUE TITLE
Lib update leads to console error and fails to render

### ISSUE THREAD

**Issue by Christoph142** [swagger-api/swagger-ui#9857]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Vivaldi (Chromium)
 - Version: 6.6 (122)
 - Method of installation: npm
 - Swagger-UI version: 5.16.2

### Describe the bug you're encountering
traverse 0.6.9 depends on [typed-array-byte-offset](https://github.com/inspect-js/typed-array-byte-offset).
I opened a [Library Issue](https://github.com/inspect-js/typed-array-byte-offset/issues/2), but the author does not intend to support a browser context, but solely node. This contradicts the sole purpose of swagger-ui.

### To reproduce...

1. npm install
2. npm start

### Expected behavior
Swagger API displayed

### Screenshots
![image](https://github.com/swagger-api/swagger-ui/assets/1440823/6e5e0078-fe2e-44d2-88c7-6437e779d95c)

**Comment by Christoph142** [comment]
For anyone encountering the same issue:
Add
```
"overrides": {
    "traverse": "0.6.8"
}
```
into your package.json

**Comment by char0n** [comment]
Hi @Christoph142,

I've pinned the `traverse` version to `v0.6.8` in https://github.com/swagger-api/swagger-js/pull/3479. The eventual goal is to remove the library from our dep tree.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9868

**Comment by Christoph142** [comment]
Thanks for the quick fix! Very appreciated. 🏅
