### ISSUE TITLE
swagger-ui-react onComplete is no longer called with a SwaggerUi instance

### ISSUE THREAD

**Issue by julien-capellari** [swagger-api/swagger-ui#9876]
### Q&A (please complete the following information)
 - OS: Wwindows
 - Browser: Chrome
 - Method of installation: npm
 - Swagger-UI-React version: 5.17.0
 - Swagger/OpenAPI version: 3.0

### Configuration
Swagger-UI-React configuration options:
```js
const handleComplete = useCallback((swagger) => {
  ...
  swagger.preauthorizeApiKey('bearer', token);
}

return <SwaggerUI spec={spec} onComplete={handleComplete} />
```

### Describe the bug you're encountering
`handleComplete` is called, but with no arguments. Instead I see this error : TypeError: Cannot read properties of undefined (reading 'preauthorizeApiKey')

### Expected behavior
`handleComplete` should be called with a SwaggerUI instance.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9895
