### ISSUE TITLE
apiKey authorization header is not set on request

### ISSUE THREAD

**Issue by themihai** [swagger-api/swagger-ui#988]
I describe  a request which requires authentication, provide the auth header value  in the apiKey field (top right corner of swagger-ui) but  when I try the request using the "Try it out" button the authentication header is not set in the HTTP request. Is it a known issue?
  I'm using the master branch which I suppose is the latest stable version. The schema version 2.0 

Edit: It seems the apiKey (name, value) is set as query string if the request method is ``get``. Even so the name is incorrectly set to ``api_key`` (the name defined in securityDefinitions is ``example-authorization``). When the method is ``post`` the key is not set neither in the query string nor in the body. Either way I think there is a valid bug. The key should be set in the header as specified in ``securityDefinitions`` and the header name should be ``example-authorization`` not api_key regardless the method of the request.

The security definition:

```js
 "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "example-authorization",
      "in": "header"
    }
```

The request spec:

```js
{
  "post": {
    "description": "\n description of the request",
    "parameters": [
      {
        "name": "no_name",
        "in": "body",
        "required": false,
        "schema": {
          "$ref": "#/definitions/example.io/idp/idp.Object"
        }
      }
    ],
    "responses": {
      "200": {
        "description": "",
        "schema": {
          "$ref": "#/definitions/example.io/api.apiRsp"
        }
      }
    },
    "security": [
      {
        "apiKey": []
      }
    ]
  }
}
```

**Comment by mohsen1** [comment]
#981 is related to this
