### ISSUE TITLE
Swagger UI 5.17.3 not visible on NPM

### ISSUE THREAD

**Issue by breun** [swagger-api/swagger-ui#9902]
https://github.com/swagger-api/swagger-ui/releases/tag/v5.17.3 shows that Swagger UI 5.17.3 was released yesterday, but https://www.npmjs.com/package/swagger-ui-dist still shows 5.17.2 as the latest version.

**Comment by char0n** [comment]
Should be fixed now. Some of Jenkins agents in CD pipelines were offline.
