### ISSUE TITLE
Expose mechanism to support vendor extensions

### ISSUE THREAD

**Issue by aurelian** [swagger-api/swagger-ui#991]
Swagger 2.0 added vendor extensions, potentially some could be useful to enhance swagger-ui.

As a use case: send a header parameter with Accept-Language but have it as a drop down menu near Response Content-Type in the UI.

**Comment by aurelian** [comment]
How about having the vendor extensions added as data-attributes to html elements?

For example: ```"x-data-json-editor": true``` on a Parameter Object in the spec will add a ```data-json-editor="true"``` as attribute for the parameter in swagger-ui.
Observing this kind of attributes from javascript can enhance swagger-ui without adding much clutter to the code base. In this case, a ```json-editor``` such as the one that's been cooking on in #1088 can be enabled.

**Comment by webron** [comment]
Resolved in 2.1.1.

**Comment by aurelian** [comment]
oh wow... sweet thanks @webron !

**Comment by webron** [comment]
It's all you, it's your PR. And well, @fehguy's effort for reviewing it. I just tag/close/move issues around ;)
