### ISSUE TITLE
Swagger UI not showing on vercel? I have a solution here it is

### ISSUE THREAD

**Issue by onepunya** [swagger-api/swagger-ui#9924]
When I try to start swagger UI using swagger express in my nodejs application, the swag UI is blank white, but I tried something by adding css style swagger The result UI appears, yes it works without the swagger express module!  Come here to see the code https://github.com/onepunya/express-api-swagger-UI-.git
![Screenshot_2024-05-06-11-42-50-533_com android chrome](https://telegra.ph/file/b0d1a42fce2b1418259a3.jpg)

**Comment by onepunya** [comment]
I will upload the code that I create to my repository. If you need help, please contact me via GitHub

**Comment by char0n** [comment]
HI @onepunya,

Thanks for the recipe! I'll close this issue for now.

**Comment by agustin-sanc** [comment]
I'm using Nest.js, I added these objects inside the `routes` array inside of the `vercel.json` file and now the Swagger styles and JavaScript files are working fine.

```json
{
      "src": "/api/swagger-ui.css",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui.min.css"
    },
    {
      "src": "/api/swagger-ui-bundle.js",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-bundle.min.js"
    },
    {
      "src": "/api/swagger-ui-standalone-preset.js",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-standalone-preset.min.js"
    },
```

**Comment by clicktodev** [comment]
just include this package in your build because vercel auto deletes it because the files aren't explicitly imported

  "builds": [
    {
      "src": "src/index.ts",
      "use": "@vercel/node",
      "config": {
        "includeFiles": ["node_modules/swagger-ui-dist/**"]
      }
    }
  ],
