### ISSUE TITLE
Only first path parameter is replaced in "Try it out"

### ISSUE THREAD

**Issue by afdaniele** [swagger-api/swagger-ui#9928]
### Q&A (please complete the following information)
 - OS: Linux (Ubuntu 22.04)
 - Browser: Chrome
 - Version: 124.0
 - Method of installation: dist assets
 - Swagger-UI version: 5.17.7
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```json
{
    "openapi": "3.0.3",
    "info": {
        "title": "My API",
        "version": "1.0",
        "description": "My API description"
    },
    "paths": {
      "/api/v1/docker/image/metadata/{registry}/{organization}/{repository}/{tag}/latest/": {
        "get": {
            "operationId": "docker/image/metadata/latest",
            "description": "Get the latest metadata of a docker image",
            "summary": "Get latest Image Metadata",
            "parameters": [
                {
                    "in": "path",
                    "name": "registry",
                    "schema": {
                        "type": "string"
                    },
                    "required": true
                },
                {
                    "in": "path",
                    "name": "organization",
                    "schema": {
                        "type": "string"
                    },
                    "required": true
                },
                {
                    "in": "path",
                    "name": "repository",
                    "schema": {
                        "type": "string"
                    },
                    "required": true
                },
                {
                    "in": "path",
                    "name": "tag",
                    "schema": {
                        "type": "string"
                    },
                    "required": true
                }
            ],
            "tags": [
                "Docker"
            ],
            "responses": {
                "200": {
                    "description": "No response body"
                }
            }
        }
      }
  }
}
```

### Describe the bug you're encountering
The path defines `4` parameters, when the API endpoint is tested using the "Try it out" button, only the first parameter is replaced, the others are left as placeholders (see image below).

### To reproduce...

1. Point an instance of swagger-ui (default configuration and options) to the OpenAPI description above;
2. Click on 'Try it out' for the only endpoint defined;
3. Populate the `4` parameter values;
4. Click on "Execute"
5. See how only the first parameter is replaced with the given value;

### Expected behavior
All parameters should be replaced in the endpoint's path.

### Screenshots
![image](https://github.com/swagger-api/swagger-ui/assets/22665009/fdca156c-b442-4592-a243-3387fb1c0e22)

**Comment by dfad1469** [comment]
I can confirm I am seeing this and rolling back to 5.17.6 restores this.

**Comment by afdaniele** [comment]
@dfad1469 Thanks. 
I confirm that the problem is not present in v5.17.6.

![image](https://github.com/swagger-api/swagger-ui/assets/22665009/9cd626b2-6296-4d3d-9b1e-5f7035edc804)

**Comment by glowcloud** [comment]
Addressed in https://github.com/swagger-api/swagger-ui/pull/9927 with a swagger-client change: https://github.com/swagger-api/swagger-js/pull/3511

**Comment by char0n** [comment]
Released in https://github.com/swagger-api/swagger-ui/releases/tag/v5.17.8
