### ISSUE TITLE
ramda-adjunct tried to access ramda

### ISSUE THREAD

**Issue by simPod** [swagger-api/swagger-ui#9929]
### Q&A (please complete the following information)
 - OS: any
 - Browser: any
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Describe the bug you're encountering

When bumping swagger-ui-react 5.17.7 -> 5.17.8 it gives following error:

> Module not found: Error: ramda-adjunct tried to access ramda (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

### To reproduce...

Use yarn pnp and compile

### Expected behavior
No error

### Additional context or thoughts
Related https://github.com/swagger-api/swagger-ui/issues/7722

**Comment by char0n** [comment]
Hi @simPod,

Could you try to regenerate your package-lock.json or yarn.lock and reinstall your project?

**Comment by char0n** [comment]
Address in SwaggerUI by https://github.com/swagger-api/swagger-ui/pull/9930

**Comment by char0n** [comment]
Fix released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.17.9
