### ISSUE TITLE
using / in tags breaks shebang

### ISSUE THREAD

**Issue by ralphvanetten** [swagger-api/swagger-ui#994]
I want to use a `/` character in the tag name when grouping resources but this breaks the shebang stuff.

For example if I have a tag named `/login` to group all resources related to login I get an url like: `http://....../apidocs/#!//login/login_profile_get` which does not automatically expand.

**Comment by mohsen1** [comment]
We need to use `encodeURIComponent` and `decodeURIComponent` to serialize/deserialize tags to avoid this. If you can, a PR that will fix it would be nice.

**Comment by ralphvanetten** [comment]
I am not that good with JavaScript and all that but I tried. It seems those tags are also used inside CSS selectors so jquey tries to select an element with '#%2Flogin' which it does not like so it seems just en-/decoding it is not enough.
For now I think I just do not use tags with special characters in them.

**Comment by mohsen1** [comment]
if we decode before passing it to jQuery it should be fine.

```
decodeURIComponent('#%2Flogin') === "#/login"
```

**Comment by mohsen1** [comment]
This was fixed by #1042
