### ISSUE TITLE
Path Parameter is not being passed through Request URL and Curl Command.

### ISSUE THREAD

**Issue by krishnaktcs** [swagger-api/swagger-ui#9979]
Hi Everyone,

I am facing issues in swagger UI, all APIs are working fine in my local but not working in Production (only few APIs are working).
Earlier APIs was working fine in my local and Production but suddenly It stopped working. 

version: Local and Production same version I am using.

    "swagger-jsdoc": "^6.2.5",
    "swagger-ui-express": "^4.5.0", 
    "node": "^14.17.6"

example : 
GET [/ABC/{First Parameter / ID}/{Second Parameter}]

Response :-

Code	Details
404	
Error: Not Found
Response body
Unrecognized response type; displaying content as text.

Download
[ xyz - BackEnd Application Server ] - Unknown Comman

Request URL

[https://abc.com/ABC/](https://abc.com/ABC/%7BFirst){First Parameter / ID}/{Second Parameter}

curl -X 'GET' \  'https://abc.com/ABC/{First Parameter / ID}/{Second Parameter}' \  -H 'accept: */*'

Anyone can help me on this?

**Comment by char0n** [comment]
It's most probably because of the fact that swagger-client now utilizes spec compliant Path Templating implementation. The spec is still ambiguous about various cases like the one that probably affects you. More info https://github.com/OAI/OpenAPI-Specification/issues/3256#issuecomment-2152144357

**Comment by krishnaktcs** [comment]
Hi @char0n,
 
Thanks for addressing this issue.
 
We were also suspecting the same. So, we tried to remove extra space from endpoints parameter names, it works for single path parameter, but it doesn't work for more than one Path-parameter.
 
In case of multi parameters - we could see the value only for the first param and the second param will have undefined.
 
example :
GET [/ABC/{FirstParameter/ID}/{SecondParameter}]
 
FirstParameter:- 'xyz',
SecondParameter;- 'jkl'

Request URL
https://abc.com/ABC/xyz/{SecondParameter}

Response :-
Code Details
404
Error: Not Found
Response body
Unrecognized response type; displaying content as text.
Download
[ xyz - BackEnd Application Server] - Unknown Command


we also tried 
GET [/abc/{firstparameterid}/{secondparameter}]
 
Response:  same as above
 
Please let us know if there is any other alternative way to resolve this issue. Your help would be greatly appreciated.

Thanks.

**Comment by char0n** [comment]
Hm then that's strange. If you have path parameters matching the template (have you changed the `Parameter Object`.`name` field?), it should just resolve. There is a test guarantying this to work: https://github.com/char0n/openapi-path-templating/blob/main/test/resolve.js#L18

**Comment by igor-tatarnikov-idt** [comment]
Hi @char0n @krishnaktcs 

Facing a similar problem with path parameter and URL like `/api/books/isbn={isbn}` - the **isbn** required parameter populated on Swagger UI never gets submitted in URL or cURL in an ASP.NET Core app referencing SwaggerUI v6.6.2 NuGet (5.17.10, if i'm mapping versions correctly). It does replace the URL template value with actual value in SwaggerUI v6.5.0.

So, my question is do you recognize a URL like `api/foo={bar}` as a non-RFC-compliant? or is it rather a bug?

**Comment by W-Lawless** [comment]
@char0n I am also seeing this issue.

Using 

```
    "node_modules/swagger-ui-express": {
      "version": "5.0.1",
```

Here is there relevant yaml commented in-line using  swagger-js-doc , with some details changed for security. 

```
 * /api/v2/parent/{paramOne}/child/{paramTwo}:
 *   post:
 *     security:
 *       - bearerAuth: []
 *     description: Changes the pump of a specific lift station by lift station ID.
 *     tags: []
 *     consumes: ["application/json"]
 *     parameters:
 *       - name: paramTwo
 *         in: path
 *         required: true
 *         description: The dial number of the Lift Station (either 1 or 2).
 *         schema:
 *           type: string
 *         example: 1
 *       - name: paramOne
 *         in: path
 *         required: true
 *         description: The ID of the Lift Station.
 *         schema:
 *           type: string
 *         example: 35
```

In my testing, only the first parameter listed is properly interpolated into the cURL statement, and this behavior is consistently observable when re-ordering the parameters. 

The relevant cURL statement will be as follows: 
```

curl -X 'POST' \
  'http://localhost:3000/api/v2/parent/{paramOne}/child/1' \
```

**Comment by falbert-ptc** [comment]
Hello @char0n @krishnaktcs

I have recently updated Swagger UI to 5.17.14 and I am seeing regressions for all path parameters that contain the "=" sign (similar to the issue reported by @igor-tatarnikov-idt ).

My Swagger Spec looks like this:
`"/GetMetaInfo(EntityName='{EntityName}')" : {
    "get" : {
      "tags" : [ "Service Endpoints" ],
      "summary" : "",
      "description" : "",
      "operationId" : "Function_GetMetaInfo_With",
      "parameters" : [ {
        "name" : "EntityName",
        "in" : "path",
        "description" : "The fully qualified entity or complex type name",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      } ],
      "responses" : {
        "200" : {
          "description" : "Success",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/MyFQN.EntityMetaInfo"
              }
            }
          }
        }
      }
    }
  }`

I cannot revert to Swagger UI 5.17.6 because of DOMPurity library vulnerability.

**Comment by char0n** [comment]
Can you please confirm you can still see the issues in [latest SwaggerUI release](https://github.com/swagger-api/swagger-ui/releases/tag/v5.18.2)?

**Comment by falbert-ptc** [comment]
This seems to be resolved

**Comment by char0n** [comment]
@falbert-ptc thanks for confirming. Closing this issue. Please reopen if this is not resolved.
