### ISSUE TITLE
Resolver error at $ref Could not resolve reference: JSON Pointer evaluation failed while evaluating token "paths" against an unexpected Element

### ISSUE THREAD

**Issue by javac9** [swagger-api/swagger-ui#9986]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome 64-Bit
 - Version: 125.0.6422.112
 - Method of installation: docker
 - Swagger-UI version: 5.17.14
 - Swagger/OpenAPI version: OpenAPI 3.1.0

### Content & configuration
I wanted to split my specification file into several reusable parts. The generator works without issues but in the Swagger UI I'm getting:
Resolver error at $ref
Could not resolve reference: JSON Pointer evaluation failed while evaluating token "paths" against an unexpected Element

I've found a similar issue: https://github.com/swagger-api/swagger-ui/issues/9304

### Describe the bug you're encountering

1) I extracted the `paths` node
2) then I wanted to reference one of the paths from within the "main" spec file; in IntelliJ IDE I right-clicked on the path (`/products`) and selected "Copy JSON pointer" and pasted the value (`/paths/~1product`)
3) generator was happy with it
4) but the Swagger UI wasn't - hence the above error

### Expected behavior
Swagger UI can understand the reference to the external "paths" json
```
"/product": {
      "$ref": "../_shared/paths/product.json#/paths/~1product"
    }
```

### Additional context or thoughts
It seems like the special characters mentioned in the linked issue above should include tilda "~" as well, whicht might solve my issue

**Comment by gabriellemunson** [comment]
Hello @javac9, I see that this issue was closed so I'm assuming you solved it. I'm running into that same issue currently and wondered if you could post what you did to fix it?
