### ISSUE TITLE
$ref property of path item object specified in swagger spec is not getting resolved properly when using swagger ui.

### ISSUE THREAD

**Issue by RashmiRam** [swagger-api/swagger-ui#999]
The below piece of code is in swagger.json

```
"paths":{
    "/path/to/action":{
        "$ref":"http://same.domain.com/action_doc.json"
    }
}
```
references another file in the same domain.
As shown in the example here
https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions.json#L32

Any advise would be helpful.

**Comment by mohsen1** [comment]
For now you can use many JSON Schema tools that resolve `$ref`s before passing it to Swagger UI.

**Comment by rmarscher** [comment]
@mohsen1 Any chance you can recommend a tool that can do this? There seem to be a lot of tools that validate but don't provide a way to output the json after resolving `$ref`s. Thanks!

**Comment by mohsen1** [comment]
@rmarscher check this out https://www.npmjs.com/package/json-refs

**Comment by rmarscher** [comment]
@mohsen1 Thanks a lot. That worked perfectly to resolve the references. I think my problem was searching for JSON Schema tools instead of JSON References.

**Comment by mohsen1** [comment]
Please follow this issue here: https://github.com/swagger-api/swagger-js/issues/270
