### ISSUE TITLE
Docker images for version v5.17.14 is missing all non-amd64 arch images

### ISSUE THREAD

**Issue by Ilyes512** [swagger-api/swagger-ui#9995]
Just a FYI:

The latest Docker image `v5.17.14` is missing all non-amd64 arch versions. See the 2 screenshot with the differences between `v5.17.14` and `v5.17.13`:

![Screenshot 2024-06-01 at 16 20 17](https://github.com/swagger-api/swagger-ui/assets/2445415/492e2e38-fc45-4daf-8d78-e03e0d7de8d9)
![Screenshot 2024-06-01 at 16 20 24](https://github.com/swagger-api/swagger-ui/assets/2445415/0891d685-97fd-4418-b1a7-7cfb09c32c4a)

**Comment by char0n** [comment]
Hi @Ilyes512,

The tags are there now. Jobs creating the additional non-amd64 tags failed. I needed to rerun them.
